### ISSUE TITLE
unable to create feature or even lines

### ISSUE THREAD

**Issue by ajay098patro** [qgis/QGIS#47618]
### What is the bug or the crash?

I am unable to create small features in projected coordinate system. at the scale of 1:617 in the map scale, but on the under hand I was able the create feature in geographic coordinate system.

### Steps to reproduce the issue

toggle and edit and add polygon or line feature at the scale of 1:617 

### Versions

3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

.

**Comment by gioman** [comment]
@ajay098patro not replicable with the (too few) provided informations. Are you sure you have tested with a new QGIS profile? if yes then please add more details (or even better add a sample project).
