### ISSUE TITLE
Attribute Table: sorting by clicking do not work anymore afrer resizing columns width

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#47613]
### What is the bug or the crash?
Opening a vector layer's attribute table, and clicking column headings to sort results in an apparent bug.  On clicking a column heading, some columns will not sort - and/or the sort order indicator arrow disappears.  This behavior happens for several vectors in my project, whether they were geopackage based, or in-memory layers created by QGIS.  The field type of a given column does not seem to matter to this bug.

### Steps to reproduce the issue

This behavior occurs when opening the attribute tables of several vector layers I tested. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
coordinates_converter | 1.0
latlontools | 3.6.2
MagneticDeclination | 2.3.1
profiletool | 4.2.2
QCopycanvas | 0.5
qgis2web | 3.16.0
qgis_resource_sharing | 0.16.0
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
latlontools
3.6.2
MagneticDeclination
2.3.1
profiletool
4.2.2
QCopycanvas
0.5
qgis2web
3.16.0
qgis_resource_sharing
0.16.0
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I encountered the same bug when using QGIS Version 3.22.4 LTR

**Comment by gioman** [comment]
I confirm as I have been seeing the same. I was not able to understand exactly what is the source of the issue. At some point I filed this https://github.com/qgis/QGIS/issues/47517 but the problem really affects columns of several different data types.

**Comment by nilhos** [comment]
I confirm too, as I've been experiencing the same issue with the QGIS 3.22 version. 
In older versions like 3.16 sorting attribute table by clicking the header used to work fine.

**Comment by gioman** [comment]
This is very concerning, but I can't find a way to reliably replicate this.

**Comment by SrNetoChan** [comment]
I can confirm it on 3.24, and that 3.16 the problem was not there, so we are facing a regression

**Comment by kiri03** [comment]
I can confirm too on 3.24.
This is the way to replicate the problem:
when I change the width of a field, close de attribute table and open again, clicking on that field doesn't sort anymore.

**Comment by gioman** [comment]
> when I change the width of a field, close de attribute table and open again, clicking on that field doesn't sort anymore.

@kiri03 right!

**Comment by pigreco** [comment]
I confirm on QGIS 3.22.4 and 3.24.0 

## OSGeo4W v2 WIN 10 pro 64b

**Comment by robbitt** [comment]
QGIS 3.24.1 seems to have fixed this sorting problem - in the handful of vector tables I tested.
