### ISSUE TITLE
QGIS Style Manager: Export Items as PNG/SVG not working

### ISSUE THREAD

**Issue by Sidapo** [qgis/QGIS#47627]
### What is the bug or the crash?

When trying to export items as PNG or SVG from the style manager a pop up File manager window opens, but it only lets me select existing files/folders & I can't create a new file (see screenshot). It appears to be the wrong File manager pop up window, when exporting an item as xml the correct File pop up window opens & I can create a new file.
File pop-up when exporting as PNG or SVG:
![image](https://user-images.githubusercontent.com/7354662/156623020-160f2fea-76e0-4e55-b077-a633dc9a5ad3.png)
File pop-up when exporting as XML:
![image](https://user-images.githubusercontent.com/7354662/156623771-c34d0f07-c4b7-4626-9788-213d7f4d869b.png)

### Steps to reproduce the issue

1. Got to Style Manager
2. Select item for export
3. right click & select export as svg of export as png
4. the wrong file pop up window appears. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
osminfo | 0.7.1
MapsPrinter | 0.9
cartolinegen | 3.0.1
ORStools | 1.5.0
QuickOSM | 2.0.0
joinmultiplelines | Version 0.4.1
ViewshedAnalysis | 1.7
mmqgis | 2021.9.10
trail_elevation_stats | 0.2
batchvectorlayersaver | 0.9
QRectangleCreator | 0.3
loadthemall | 3.3.0
WalkingTime-master | 0.2
color_attribute | 0.2.1
qNote | 2.2
coordinate_capture | 0.2
qtiles | 1.7.1
processing_saga_nextgen | 0.0.7
qgis2web | 3.16.0
path_sorting | 0.3
geometric_attributes | 0.3
nominatim | 1.4.1
BezierEditing | version 1.3.2
AppendFeaturesToLayer | 1.2.0
profiletool | 4.2.1
OpenTopography-DEM-Downloader | 1.0
quick_map_services | 0.19.28
pointsamplingtool | 0.5.3
HCMGIS | 21.8.28
MagneticDeclination | 2.3.1
SRTM-Downloader | 3.1.15
sagaprovider | 2.12.99
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
osminfo
0.7.1
MapsPrinter
0.9
cartolinegen
3.0.1
ORStools
1.5.0
QuickOSM
2.0.0
joinmultiplelines
Version 0.4.1
ViewshedAnalysis
1.7
mmqgis
2021.9.10
trail_elevation_stats
0.2
batchvectorlayersaver
0.9
QRectangleCreator
0.3
loadthemall
3.3.0
WalkingTime-master
0.2
color_attribute
0.2.1
qNote
2.2
coordinate_capture
0.2
qtiles
1.7.1
processing_saga_nextgen
0.0.7
qgis2web
3.16.0
path_sorting
0.3
geometric_attributes
0.3
nominatim
1.4.1
BezierEditing
version 1.3.2
AppendFeaturesToLayer
1.2.0
profiletool
4.2.1
OpenTopography-DEM-Downloader
1.0
quick_map_services
0.19.28
pointsamplingtool
0.5.3
HCMGIS
21.8.28
MagneticDeclination
2.3.1
SRTM-Downloader
3.1.15
sagaprovider
2.12.99
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Sidapo on Windows you choose the folder, an files (png or svg) are created in there with the same name of the selected symbols. Does not work like that on Ubuntu?

**Comment by Sidapo** [comment]
Ah okay, so the pop up window is actually not wrong. Then the issue actually is that no files get created after selecting a folder

**Comment by gioman** [comment]
> Then the issue actually is that no files get created after selecting a folder

that is the question. Works on Windows. And works fine on Linux Mint 20.2 too.

**Comment by ismailsunni** [comment]
It seems to depend on what kind of item you want to export. Testing with exporting many items, there are some items that are not exported.

**Comment by Sidapo** [comment]
okay, thank you all for your quick feedback & clarification. The issue is now much clearer to me: I've tested with a bunch of items, and yes, I can confirm that for me as well some items get exported and some don't. I initially tried with two color ramps & an svg icon, all of which didn't get exported. Should I resubmit a new bug report and clarify that the actual issue is that some items don't get exported?
Also, it was very confusing for me that for one export type (xml) the user is expected to specify a file name (to me the expected behavior) while for the other export types the user is expected to only select a folder & the files will be automatically created & named. Should I submit a separate feature request issue for this as well? (sorry for all my questions, this is my first bug report)

**Comment by gioman** [comment]
> Should I resubmit a new bug report and clarify that the actual issue is that some items don't get exported?

@Sidapo not necessary, you can edit title and description of this ticket.

> Should I submit a separate feature request issue for this as well? (sorry for all my questions, this is my first bug report)

We cannot assume this is a bug, maybe it is by design. You should ask in the developers mailing list first.
