### ISSUE TITLE
Interactive vector merge tool always creating a new feature id instead of preserving the existing one

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#47629]
### What is the bug or the crash?

The interactive merge tool allows to combine 2 or more selected vector features to be merged into a single feature.

![image](https://user-images.githubusercontent.com/884476/156717337-28d3365b-955b-4c3d-8174-387ecc417343.png)

In the "Merge Features" dialogue one can select one feature from which to take over the attributes, or take attributes from feature with the longest length. This works fine for all attributes, except the "feature_id" (primary key).

![image](https://user-images.githubusercontent.com/884476/156717794-2d52bfda-d69b-460a-ac5c-1cf3c6c3d16c.png)

It is very important that this also works for the primary key, because, in more complex data models, a lot of other tables can link to the selected feature where the primary key needs to be preserved, or otherwise many other relations will fail, when the primary key is changed by QGIS.

### Steps to reproduce the issue

1. Create a simple table in Postgis, something like:

```
CREATE TABLE test.river (
	t_id serial4 NOT NULL,
	geometrie geometry(linestring, 2056) NOT NULL,
	name text NULL,
	CONSTRAINT river_pkey PRIMARY KEY (t_id)
);
```

2. Create a couple of line string geometry objects

3. Select 2 or more features

4. Use the merge tool as described above

5. Select one of the features as the main feature of which to take all attributes from. Make sure the "t_id" column is not skipped

6. Merge the features

7. See that the newly merged feature gets a new "t_id" instead of taking over the "t_id" of the selected main feature of which to take the attributes from.

### Versions

This is regardless of the version. I tried several ones (master, 3.22, 3.24) - all seem to have this bug.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by andreasneumann** [comment]
Here is a screencast:

https://user-images.githubusercontent.com/884476/156719646-cc164b91-3977-43f8-94ff-df8aa3d0f35e.mp4

**Comment by gioman** [comment]
Agree, I have noticed this one a few days back but I was not sure if to open a ticket. Did it worked differently in the past? I will have a look.

**Comment by andreasneumann** [comment]
> Did it worked differently in the past? I will have a look.

I don't know - but I doubt that it worked fine in the past.

**Comment by andreasneumann** [comment]
> Yeah it seems the same in all 3.* releases.

Thanks for testing!
