### ISSUE TITLE
Snapping bug related to CRS Transformation in 3.22 LTR

### ISSUE THREAD

**Issue by onemanjam** [qgis/QGIS#47636]
### What is the bug or the crash?

When snapping to a vertex on another layer, if the two layers are different CRS (eg, layer 1 = 4326 [WGS84] and layer 2 = 4269 [Nad83]), the resulting point seems to be offset from where it should have snapped.

If you change the layer CRS to match the snapped point it looks correct, so I think somehow the snapping logic is not using the transformation when setting the geometry.

NOTE: This was not previously an issue as far as I can tell (I've confirmed that it is not a issue in 3.20 or 3.10).

![snapping-1](https://user-images.githubusercontent.com/56447695/156818316-6488aa69-1f35-4e10-8375-e75e97da4065.png)
![snapping-2](https://user-images.githubusercontent.com/56447695/156818390-ae0cddb8-356b-4086-afc8-8defd79f54ce.png)
![snapping-3](https://user-images.githubusercontent.com/56447695/156818440-c0128234-ad1a-4373-b325-4d721c0fdc11.png)

### Steps to reproduce the issue

1. make a point in 4326
2. make a line in 4269
3. snap 4269  line to 4326 point
4. zoom in to see there is a slight offset (maybe only 20cm, but not topologically correct).
5. set 4269 line layer to 4326, witness that it looks correct, conclude that the snapping did not user the transformation correctly.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins
changeDataSource | 3.1
ClusterPoints | 3.3
contour | 2.0.8
DirectionalSlope | 1.3.2
FreehandRasterGeoreferencer | 0.8.3
Generalizer3 | 1.0
geometry_paster | 0.1.1
geoscience | 1.5
LayerBoard | 1.0.1
MemoryLayerSaver | 4.0.4
pointsamplingtool | 0.5.3
qchainage | 3.0.1
qProf | 0.4.4
quick_attribution | 3.6
quick_map_services | 0.19.28
scriptrunner3 | 3.0.5
splitmultipart | 1.0.0
valuetool | 3.0.15
VectorBender | 0.2.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[ce8e65e9](https://github.com/qgis/QGIS/commit/ce8e65e9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
changeDataSource
3.1
ClusterPoints
3.3
contour
2.0.8
DirectionalSlope
1.3.2
FreehandRasterGeoreferencer
0.8.3
Generalizer3
1.0
geometry_paster
0.1.1
geoscience
1.5
LayerBoard
1.0.1
MemoryLayerSaver
4.0.4
pointsamplingtool
0.5.3
qchainage
3.0.1
qProf
0.4.4
quick_attribution
3.6
quick_map_services
0.19.28
scriptrunner3
3.0.5
splitmultipart
1.0.0
valuetool
3.0.15
VectorBender
0.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> * make a point in 4326
> 
> * make a line in 4269
> 
> * snap 4269  line to 4326 point
> 
> * zoom in to see there is a slight offset (maybe only 20cm, but not topologically correct).
> 
> * set 4269 line layer to 4326, witness that it looks correct, conclude that the snapping did not user the transformation correctly.

@onemanjam please test on a new QGIS profile  (you didn't despite checking the checkbox) and if the issue persist then attach sample project with data. Thanks.

**Comment by onemanjam** [comment]
sorry, I didn't understand what that meant, but I tried it on a couple of other machines and it happens on all of them.

I've now made a new a profile and tried it there and it works there. So what does that mean? This is something that was not previously an issue and now it is. 

Did something happen with profiles being imported from older versions? It persists on several users computers with different profiles, but not on new ones?

**Comment by gioman** [comment]
> So what does that mean?

@onemanjam it means that likely the issue is caused by a 3rd party plugin,  plugin you probably have installed on your machines. Try figure what plugin is and then make the author/s know. There is not much else left to do here.

**Comment by onemanjam** [comment]
thanks
