### ISSUE TITLE
Fedora 35 QGIS version conflict

### ISSUE THREAD

**Issue by LeonDBL** [qgis/QGIS#47649]
### What is the bug or the crash?

Fresh install of Fedora 35, enabled the Dani GIS copr repo and followed instructions.

Failing to install due to multiple "conflicts between attempted installs of qgis-3.20.3-1.fc35.i686 and qgis-3.24.0-1.fc35.x86_64"

### Steps to reproduce the issue

- Install Fedors 35, update/upgrade
- sudo dnf copr enable dani/qgis
- sudo dnf install qgis python3-qgis qgis-grass

### Versions

Copr repo states 3.22 but is trying to install versions from 3.20 to 3.24

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@LeonDBL not 100% sure, but I don't think we manage the packages in that repo.

**Comment by LeonDBL** [comment]
Ahh, OK, sorry, I thought it redirected me here to report. I'll double check.
