### ISSUE TITLE
QGIS crashes when "Digitize shape" option is turned on

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#47648]
### What is the bug or the crash?

See below

## User Feedback

1. Toggle to edit a polygon layer
2. Enable the "Add polygon" tool
3. From the "Advanced digitizing" toolbar, select the "Digitize shape" option from the drop-down menu (second button)
4. Kaboum

![Peek 05-03-2022 21-20](https://user-images.githubusercontent.com/7983394/156898853-f0b4fbcf-0d94-421f-8e85-5256cf82368a.gif)

## Report Details

**Python Stack Trace**
```
Fatal Python error: Segmentation fault

Current thread 0x00007f05ad7c8480 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.25.0-Master
QGIS code revision: 734dae74da
Compiled against Qt: 5.12.8
Running against Qt: 5.12.8
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: linux
Kernel Version: 5.13.0-30-generic

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.25.0-Master | Révision du code | 734dae74da
-- | -- | -- | --
Version de Qt | 5.12.8
Version de Python | 3.8.10
Version de GDAL/OGR | 3.0.4
Version de Proj | 6.3.1
Version de la base de données du registre EPSG | v9.8.6 (2020-01-22)
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Version de SQLite | 3.31.1
Version du client PostgreSQL | 12.9 (Ubuntu 12.9-0ubuntu0.20.04.1)
Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.2
Version de l'OS | Ubuntu 20.04.4 LTS
  |   |   |  
Cette copie de QGIS dispose d'une sortie de débogage.
  |   |   |  
Extensions Python actives
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
Confirmed on Windows too.

**Comment by nyalldawson** [comment]
Looks like this has since been fixed -- can you confirm?

**Comment by DelazJ** [comment]
yes, I can't reproduce anymore

**Comment by SrNetoChan** [comment]
I am getting this again on 3.26.1 on Linux. From my tests this happens if the shape digitizing toolbar has not been enabled, and none of the shapes have ever been selected, when you try draw using shapes instead of segments, it crashes.

**Comment by SrNetoChan** [comment]
@3nids FYI

**Comment by 3nids** [comment]
https://github.com/qgis/QGIS/pull/49592 should fix this

**Comment by SrNetoChan** [comment]
I can't test it now. I will try to do it in a few days.
