### ISSUE TITLE
Exporting map to PDF using PyQGIS keeps running infinitely

### ISSUE THREAD

**Issue by geogeek11** [qgis/QGIS#47644]
### What is the bug or the crash?

I try to export PDF using PyQGIS 3 API, when the execution reaches the `exporter.exportToPdf(pdf_fpath,exportSettings)` call it keeps running infinitely, and no PDF is exported. even though I can export the PDF manually from the saved QGIS project. This issue occurs only in Windows, and do not occur in linux.

### Steps to reproduce the issue

Please find below the used source code:
```
        exporter = QgsLayoutExporter(layout)
        logging.info(f"layout exporter created ")
        exportSettings = QgsLayoutExporter.PdfExportSettings()
        exportSettings.dpi=double(self.hum_event.default_pdf_res_dpi)
        qgs_project.write()
        logging.info(f"layout export dpi param setted -exporting to pdf ..{pdf_fpath}.")
        exporter.exportToPdf(pdf_fpath,exportSettings)
```

### Versions

QGIS (3.16)

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> QGIS (3.16)

@geogeek11 this is EOL, try on 3.22.4




> exporter = QgsLayoutExporter(layout)
>         logging.info(f"layout exporter created ")
>         exportSettings = QgsLayoutExporter.PdfExportSettings()
>         exportSettings.dpi=double(self.hum_event.default_pdf_res_dpi)
>         qgs_project.write()
>         logging.info(f"layout export dpi param setted -exporting to pdf ..{pdf_fpath}.")
>         exporter.exportToPdf(pdf_fpath,exportSettings)

Is this the full script?

**Comment by geogeek11** [comment]
Thanks for your swift reply, I will test on 3.22 , then I will send you the test script.
