### ISSUE TITLE
Crash loading geotiff Ubuntu Fatal Python error: PyThreadState_Get: no current thread

### ISSUE THREAD

**Issue by JorisFransman** [qgis/QGIS#47654]
### What is the bug or the crash?

While trying to load the BX24_GeoTifv1-02-clip.tif QGIS 3.24 crashes. I tried the current QGIS version 3.24 and the previous version 3.10. The tif file seems ok when I open it in an image viewer.

Debug information:
Files used:
https://www.linz.govt.nz/sites/default/files/topo/Topo50_raster_images/GeoTIFFTopo50/BX24_GeoTifv1-06.tif
https://www.qgistutorials.com/downloads/BX24_GeoTifv1-02-clip.tif

OS: NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)"
QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4

Syslog:
Mar 3 11:22:32  org.qgis.qgis.desktop[887756]: Fatal Python error: PyThreadState_Get: no current thread
Mar 3 11:22:32  org.qgis.qgis.desktop[887756]: Python runtime state: initialized
Mar 3 11:22:32  org.qgis.qgis.desktop[887756]: Current thread 0x00007fd5621a6440 (most recent call first):
Mar 3 11:22:32  org.qgis.qgis.desktop[887756]: <no python="" frame="">
Mar 3 11:22:33  systemd[12047]: gnome-launched-org.qgis.qgis.desktop-887756.scope: Succeeded.

### Steps to reproduce the issue

Download files and drag file into QGIS or Layer, Add Layer, Add Raster Layer, ... select file, OK, add.

### Versions

OS: NAME="Ubuntu" VERSION="20.04.4 LTS (Focal Fossa)"
QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Creating a new profile solved the crash.

**Comment by gioman** [comment]
> Creating a new profile solved the crash.

@JorisFransman then there is no issue here. The problem likely was caused by a 3rd party plugin.
