### ISSUE TITLE
add support for the LandXML format

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#47655]
### Feature description

I would like to export and import from LandXML.

Points, lines, arcs and terrain models(tin).

It would realy help me in my field of work.

**Comment by gioman** [comment]
@APOS80 these are the channels for support: https://qgis.org/en/site/forusers/support.html

**Comment by gioman** [comment]
@APOS80 sorry, maybe it was really a feature request? if it is can you please elaborate?

**Comment by gioman** [comment]
Probably the right place where to request support for this format http://www.landxml.org/ is here https://gdal.org/drivers/vector/index.html

**Comment by gioman** [comment]
There is this converter: https://github.com/lekks/tin2dem

and this plugin: https://plugins.qgis.org/plugins/LandXml/

**Comment by APOS80** [comment]
Its an open format for geodetic data, it schould be supported in qgis i think.

I would like to export tin to landxml.

**Comment by gioman** [comment]
> Its an open format for geodetic data, it schould be supported in qgis i think.

@APOS80 is not usual to have specific formats support written directly in QGIS: we have rdbms providers, ogc services, dwg and not much more I think. The bulk of the support for rasters and vectors comes from GDAL/OGR. You probably should file the request there.

**Comment by palmerj** [comment]
> and this plugin: https://plugins.qgis.org/plugins/LandXml/

Give this a try and see if it meets you needs. You can raise requests for this plugin here: https://github.com/linz/QGIS-LandXML-Plugin
