### ISSUE TITLE
"Add Group" creates group above current group

### ISSUE THREAD

**Issue by shoefone** [qgis/QGIS#47657]
### What is the bug or the crash?

This is a UI bug, I believe. In QGIS version 3.24.0 on Windows 10 (21H2/ build 19044.1526), in the 'Layers' panel, if a Group is selected, and the 'Add Group' button is pressed, a new Group is created *above* the selected Group, making the selected Group a sub-Group of the newly created Group. 

This is in contrast with the (correct, I believe) behaviour in previous versions. In previous versions, if a Group is selected in the Layers panel, and the 'Add Group' button is pressed, a new Group is created *below* the selected group, making the new Group a sub-Group of the selected Group.

### Steps to reproduce the issue

1. Open QGIS 3.24.0 with no plugins (qgis-bin.exe --noplugins)
2. Create a New Project (ctrl-n) (note: this behaviour occurs in existing projects, as well)
3. In the Layers panel, click the 'Add Group' button
4. Single-click the new Group (called 'group1' by default)
5. Click the 'Add Group' button again

At this point, a new group called 'group2' will be created, with 'group1' as a subgroup.

### Versions

QGIS 3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I don't recall seeing this in the previous version (3.23), though I haven't tested that. It is definitely fairly new behaviour, though.

**Comment by nicogodet** [comment]
Yeah I noticed this new behavior too.
Is it intended or a regression ?

**Comment by nicogodet** [comment]
@alexbruy Could be your PR https://github.com/qgis/QGIS/pull/46704 ?

**Comment by shoefone** [comment]
Thanks!

**Comment by gacarrillor** [comment]
> Thanks!

Thanks for your report!
