### ISSUE TITLE
EXC_BAD_ACCESS (SIGABRT) while setting up an Oracle connection

### ISSUE THREAD

**Issue by agodfrind** [qgis/QGIS#47669]
### What is the bug or the crash?

QGIS crashes whenever I try and setup a connection to an Oracle database. This has been happening on previous versions too, and still happens in 3.24 RC

### Steps to reproduce the issue

1. Go to top menu Layer
2. Select Add Layer
3. Select Add Oracle Spatial Layer
4. Click New (for new connection)
5. Fill connection details (host, port, service name, user, password)
6. Click "Test Connect"

QGIS then crashes with a EXC_BAD_ACCESS (SIGABRT) exception

### Versions

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.2
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 12.2

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

[crash_3.22.txt](https://github.com/qgis/QGIS/files/8197006/crash_3.22.txt)

**Comment by agodfrind** [comment]
I found out that similar issues have been reported, hinting that the problem is with the version of QT. So I looked and poked, and I got QGIS to work by setting this…

**Comment by gioman** [comment]
Maybe related to https://github.com/qgis/QGIS/issues/47225

**Comment by agodfrind** [comment]
> I found out that similar issues have been reported, hinting that the problem is with the version of QT. So I looked and poked, and I got QGIS to work by setting this…:

export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/Cellar/qt/6.2.0/plugins/platforms/

Prior to that, I had is setup to

export QT_QPA_PLATFORM_PLUGIN_PATH=/usr/local/Cellar/qt/5.15.2/plugins/platforms/

**Comment by gioman** [comment]
> And most important of all: **DO NOT CRASH THE APPLICATION**

@agodfrind I'm pretty sure that is not on purpose...

**Comment by agodfrind** [comment]
True: it could be that this sort of exception is unexpected. I would say that any operation that involves libraries not included with the product package need to be secured by a try/catch to handle the fact that the library may not be available.

**Comment by morganb240** [comment]
Has there been any resolution found to this issue?

**Comment by troopa81** [comment]
Fixed by #53201
