### ISSUE TITLE
Hashed line fill pattern is not rendered correctly anymore in print composer

### ISSUE THREAD

**Issue by micdeluca** [qgis/QGIS#47672]
### What is the bug or the crash?

In QGIS 3.24 the hashed line fill pattern is not rendered correctly in the print composer. 
In QGIS 3.22 the rendering is correct.
I attach examples and project files in QGIS 3.24 and 3.22 versions.
(Sorry for my English)
[Test_HashLine.zip](https://github.com/qgis/QGIS/files/8199189/Test_HashLine.zip)
.

### Steps to reproduce the issue

I attach examples and project files in QGIS 3.24 and 3.22 versions.

### Versions

3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I can't see any difference in the rendering here between 3.16/3.22/3.24.
