### ISSUE TITLE
"Add Group" in Layers panel should add group immediately above or below selected ungrouped layer

### ISSUE THREAD

**Issue by shrublanderGIS** [qgis/QGIS#47676]
### Feature description

When adding a group in the Layers panel (as of QGIS 3.22.1), the new group is added to the bottom of the list of layers if an ungrouped layer is selected when clicking the "Add Group" button. Conversely, having a group or layer within a group selected will add the new group as a sub-group. 

It would be more convenient for a new group to be added either immediately above or below the selected ungrouped layer, which is often one of the layers I want to add to the new group anyway. This would be especially helpful when dealing with a project that has a long list of layers. This feature should not affect how new groups are added when a group or grouped layer is selected (i.e. in that case, the new group would still be added as a sub-group).

**Comment by nicogodet** [comment]
In 3.24, if an ungrouped layer is selected, clicking "Add group" will create a group with the selected layer inside.

Somehow related to https://github.com/qgis/QGIS/issues/47657

**Comment by nicogodet** [comment]
@shrublanderGIS https://github.com/qgis/QGIS/pull/46704
Fixed in 3.24

**Comment by shrublanderGIS** [comment]
@nicogodet thank you—I hadn't installed 3.24 before posting the request.
