### ISSUE TITLE
Oracle connection not retried in case of intermittent failure

### ISSUE THREAD

**Issue by agodfrind** [qgis/QGIS#47685]
### What is the bug or the crash?

The problem happens in the following circumstances:
- I have a connection to Oracle
- I have a project with one or more layers from that Oracle connection
- Connectivity to the Oracle database is interrupted
- When connectivity is re-instated, QGIS does not try to re-establish the connection.

In my case, I was connected to a VM where Oracle runs. I then saved the state of the VM. Then I restarted the VM. When I tried to view the data of the Oracle layer, QGIS appears to hang (the blue bar indicating activity is on permanently, and the layer data does not refresh when zooming or panning).

There is no way at all to recover: even refreshing the connection hangs. The only way is to close QGIS and start it up again.

We should do two things here:
- When a connection is detected as no longer working, flag it as such visually (with some icon)
- Allow "Refresh connection" to establish a new connection if the connection is marked as failed

Also this:
- keep on trying the connection at regular intervals (settable ?) and automatically re-establish it when possible.

### Steps to reproduce the issue

1. Create an Oracle connection if necessary
2. Select a table and bring it in a project
3. Stop the database, or break the connectivity to the database (for example close the VM where the database run, close the network from the desktop where QGIS runs ...)
4. Try panning or zooming: no data is returned.
5. Reinstate the connectivity to the database
6. Panning and zooming still does not work
7. Refresh connection hangs

### Versions

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.2
  |   |   |  
Active Python plugins
oneatlas-qgis-plugin-1_0_1 | 1.1.2
oscars-georaster-qgis-plugin | 0.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 12.2

Active Python plugins
oneatlas-qgis-plugin-1_0_1
1.1.2
oscars-georaster-qgis-plugin
0.1
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This problem most likely happens with other connections to databases or external services that become temporarily unavailable. In all cases we should have a "refresh/check" mechanism, ideally with automatic reset.

**Comment by agodfrind** [comment]
> The only way is to close QGIS and start it up again.
That actually does not work. Using the "Quit" menu item actually hangs. On macOS, the only option is actually to "Force Quit" QGIS.

**Comment by uclaros** [comment]
Same as #35855 ?

**Comment by agodfrind** [comment]
Yes, it looks like https://github.com/qgis/QGIS/issues/35855
