### ISSUE TITLE
Additional python package

### ISSUE THREAD

**Issue by mattfack** [qgis/QGIS#47699]
### Feature description

I would love to have the package rpy2 in the qgis python distribution

### Additional context

There are some plugins that use rpy2 to integrate R inside python.

**Comment by gioman** [comment]
> I would love to have the package rpy2 in the qgis python distribution

@mattfack on linux you typically would do `sudo apt-get install python3-rpy2` and on Windows/OSGeo4W just open the osgeo4w and do `pip install...`. Isn't enough?

**Comment by mattfack** [comment]
I couldn't install using OSGeo4W console, but I managed to install it like this

1. install the package on my system python distribution
2. find the folder where the package is installed
3. copy paste the two reltive folders to C:\Program Files\QGIS 3.22.4\apps\Python39\Lib\site-packages

Anyway, I think it could be easier if QGIS came with the package included!

**Comment by gioman** [comment]
> Anyway, I think it could be easier if QGIS came with the package included!

@mattfack sure, but speaking about Windows then you must file the request in the OSGeo4W tracker, not here.

**Comment by mattfack** [comment]
Unfortunately, I do not have an account for that.

**Comment by mattfack** [comment]
Anyway, it's sort of the same issue as #47632 I guess this can be closed
