### ISSUE TITLE
GDAL Dissolve with temporal layers misses geometries

### ISSUE THREAD

**Issue by Bastarrika** [qgis/QGIS#47717]
### What is the bug or the crash?

When doing a Dissolve using the GDAL library, the process missess some geometries. It is reproduced with a temporal layer, but if you save it in a Shapefile, it works well.

### Steps to reproduce the issue

[Data.zip](https://github.com/qgis/QGIS/files/8222662/Data.zip)

1) We do an intersect between the SeccCensales Layer and the Vias Ciclistas layer, in order to get the 'Vias Ciclistas' with the SECCION attribute. Result is a temporary layer
![image](https://user-images.githubusercontent.com/101328861/157647430-3dce978b-5321-4d71-8daa-e5744438eb19.png)

2) We do a dissolve with the GDAL, setting the 'SECCION' attribute as the dissolve-attribute. The 
![image](https://user-images.githubusercontent.com/101328861/157647620-bf7e40b8-6ee5-4472-bf1e-79922b65bd71.png)

3)Result missing some geometries (red is the result of step1, green is the dissolved result illustrating missing geometries)
![image](https://user-images.githubusercontent.com/101328861/157648047-ffb28bf2-e4d4-40c5-b164-905c4f34887f.png)

### Versions

3.16.14 version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Bastarrika it is because your inputs have an FID field, and when creating a temp output this is kept by default, but with repeated values that then make the gdal dissolve partially fail.

solutions: 1) when intersecting choose what fields to keep and, uncheck the FID fields 2) in the result of the intersection remove the FID field before dissolving

**Comment by Bastarrika** [comment]
Thanks for your message, Giovanni. It works.
Best regards
