### ISSUE TITLE
Possible bug when calculating oriented minimum bounding box 

### ISSUE THREAD

**Issue by elitonfilho** [qgis/QGIS#47726]
### What is the bug or the crash?

Calculation of orientedMinimumBoundingBox on some geometries seems incorrect

### Steps to reproduce the issue

1. Run QgsGeometry.fromWkt('MultiPolygon (((-57 -30, -56.5 -30, -56 -30, -55.5 -30, -55.5 -29.6667, -55.5 -29.333, -55.5 -29, -56 -29, -56.5 -29, -57 -29, -57 -29.3333, -57 -29.6666, -57 -30)))').orientedMinimumBoundingBox()
2. Result: (<QgsGeometry: Polygon ((-57 -30, -57 -31.5, -56 -31.5, -56 -30, -57 -30))>, 1.5, 90.0, 1.0, 1.5)
3. Visual interpretation: (blue: original, orange: oriented minimum bbox)
![image](https://user-images.githubusercontent.com/37584879/157758011-7c744e42-24b3-4ebf-b73a-b8847b4479c4.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.1-Białowieża | QGIS code revision | 663dcf8fb9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.0-CAPI-1.16.0
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DsgTools | 4.2.0
gridGenerator | 1.3
plugin_edicao | 0.1
plugin_reloader | 0.8.2
quick_map_services | 0.19.28
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.1-Białowieża
QGIS code revision
[663dcf8fb9](https://github.com/qgis/QGIS/commit/663dcf8fb9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DsgTools
4.2.0
gridGenerator
1.3
plugin_edicao
0.1
plugin_reloader
0.8.2
quick_map_services
0.19.28
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elitonfilho** [comment]
Similar issue at #36632

**Comment by Derrailer** [comment]
I've experienced the same issue since v3.22.0. The bug seems to not be present in earlier versions.

**Comment by agiudiceandrea** [comment]
With QGIS 3.16 this bug does not occur:
`QgsGeometry.fromWkt('MultiPolygon (((-57 -30, -56.5 -30, -56 -30, -55.5 -30, -55.5 -29.6667, -55.5 -29.333, -55.5 -29, -56 -29, -56.5 -29, -57 -29, -57 -29.3333, -57 -29.6666, -57 -30)))').orientedMinimumBoundingBox()`
returns
`(<QgsGeometry: Polygon ((-57 -30, -55.5 -30, -55.5 -29, -57 -29, -57 -30))>, 1.5, 0.0, 1.5, 1.0)`
