### ISSUE TITLE
ST-DBSCAN algorithm uses wrong value for time threshold

### ISSUE THREAD

**Issue by dougmccune** [qgis/QGIS#47727]
### What is the bug or the crash?

The ST-DBSCAN implementation asks for user input for the time duration to use as the max allowed distance between points within a cluster. That value from the user gets converted into milliseconds and fed into the algorithm, however, the actual algorithm assumes the value is in seconds. 

**Workaround:** 
Divide your intended value by 1000 and enter that into the GUI. For example, if you want the max duration to be 3 days, enter 0.003 days. That will get you a proper value of 3 days.

**Suggested fix:**
On line 117 of qgsalgorithmdbscanclustering.cpp change this line:
`const double eps2 = parameterAsDouble( parameters, QStringLiteral( "EPS2" ), context );`
to this:
`const double eps2 = parameterAsDouble( parameters, QStringLiteral( "EPS2" ), context ) / 1000;`

### Steps to reproduce the issue

1. Run the ST-DBSCAN processing algorithm using the shapefile [points_with_date.shp](https://github.com/qgis/QGIS/blob/master/python/plugins/processing/tests/testdata/custom/points_with_date.shp) 
2. Set Date/time field to date, Min cluster size to 1, Max distance to 10, and Max time duration to 3 years. The goal here is to not cluster by geographic distance at all (hence the large value) but only to cluster by date.
3. Run the algorithm
4. Notice your results are in a single cluster (plus 2 points not assigned to a cluster). They should be in 3 distinct clusters based on the dates in the data

### Versions

3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The algorithm was [initially implemented](https://github.com/qgis/QGIS/commit/f68ef8fb60449ecfbdb12b11403cee398222129d#diff-2eb283b5a2d6b844e99189282dc7813b4d2a7e1cfc91244d5dce8cb2947c01eaR117) by @nirvn with a hardcoded time input in day units. 

Then it was updated in September to allow the user to control the time units, but [that commit](https://github.com/qgis/QGIS/commit/4d2c24e850580a9647d224d69ec32a5721bfa531#diff-2eb283b5a2d6b844e99189282dc7813b4d2a7e1cfc91244d5dce8cb2947c01eaR117) introduced the mismatch between milliseconds (being fed into the algorithm) and seconds (expected by the algorithm).

**Comment by nyalldawson** [comment]
Ping @nirvn

**Comment by nirvn** [comment]
Fix incoming, @dougmccune , good catch.
