### ISSUE TITLE
Bug with Ctrl+Z in atlas

### ISSUE THREAD

**Issue by sylvain258** [qgis/QGIS#47720]
### What is the bug or the crash?

There is a problem when editing atlases in qGIS 3.22. If use Ctrl+Z to cancel last modification, qGis crash. There is the same using menu "Edit > Cancel"

### Steps to reproduce the issue

Ctrl+Z in atlases
Edit > Cancel (for me in french, Editer > Annuler)

### Versions

qGIS 3.22 Bialowiecza LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@sylvain258 what do you exactly mean with "edit an atlas"?

**Comment by sylvain258** [comment]
"Edit an atlas" it's the menu "Print layouts"

**Comment by sylvain258** [comment]
@gioman I don't know what is the name in English version, in French this names "Mise en page" (Projet > Mise en page)

**Comment by gioman** [comment]
> @gioman I don't know what is the name in English version, in French this names "Mise en page" (Projet > Mise en page)

@sylvain258 

Projet > Nouvelle Mise en page

creates a new print layout, ok. Then I create a new atlas, then what? Please list the detailed steps that lead to the crash, or even better add a screencast.

**Comment by sylvain258** [comment]
@gioman

I create an atlas and I add several tables (with attributes or fixed tables)
If I move one table and that I cancel action, qGIS project crashes. That is problematic if tables are moved by mistake.

The most surprising is this crash have no impact on others qGis projects. It's just the current project which crash.
