### ISSUE TITLE
Join Attributes by Location causes crash

### ISSUE THREAD

**Issue by gjsa73** [qgis/QGIS#47729]
## User Feedback

Join Attributes by Location causes QGIS to crash in the following circumstances:

- both input layers have polygon geometries
- invalid features exist in the Join Layer
- processing settings are set to "Do not filter (better performance)"
- the join type for the Join Attributes by Location is "Take attributes from the feature with the largest overlap only (one-to-one)

## Report Details

**Crash ID**: [4c8e96c30f6fdd825b5bfa09c09c4ccc3189862d](https://github.com/qgis/QGIS/search?q=4c8e96c30f6fdd825b5bfa09c09c4ccc3189862d&type=Issues)

**Stack Trace**
<pre>
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Steps to reproduce the issue

![Capture1](https://user-images.githubusercontent.com/21994806/157770889-9858f13e-f3ae-4c78-a9ca-e2a22cf8b30d.PNG)

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows Server 2016 Version 1809

Active Python plugins
MemoryLayerSaver
4.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@gjsa73 cannot replicate here, please attach a sample dataset.

**Comment by alexbruy** [comment]
Stacktrace is not related to Join by Location, it is from Import Photos.

**Comment by gjsa73** [comment]
Have repeated the crash and pasted the stack trace again below.  I have also attached two layers for testing (base_layer and join_layer).  Note that the join layer here is entirely ridiculous - it contains one feature that has totally invalid geometry, but the point of this layer is simply to highlight that when there are invalid features in the join layer and invalid feature filtering is turned off, this triggers a crash.  The original layer with many features (mostly valid ones) that caused the crash has since had the geometries fixed, so can no longer be used to generate the crash.

[data.zip](https://github.com/qgis/QGIS/files/8240763/data.zip)

## User Feedback

Join By Location with invalid features in join layer and no invalid feature filtering

## Report Details

**Crash ID**: [4c8e96c30f6fdd825b5bfa09c0

9c4ccc3189862d](https://github.com/qgis/QGIS/search?q=4c8e96c30f6fdd825b5bfa09c09c4ccc3189862d&type=Issues)


**Stack Trace**
<pre>
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by gjsa73** [comment]
Just bumping this - I've provided all the information needed to diagnose the original issue.  The 'Import Photos' stack trace is apparently  separate bug.

**Comment by thymaro** [comment]
I just had the same issue and, instead of opening a new thread, am reporting this here. I will go and rectify the layers before proceeding with the operation.

## User Feedback

tried to join two gpkg layers' attributes by location

## Report Details

**Crash ID**: [4c8e96c30f6fdd825b5bfa09c09c4ccc3189862d](https://github.com/qgis/QGIS/search?q=4c8e96c30f6fdd825b5bfa09c09c4ccc3189862d&type=Issues)


**Stack Trace**
<pre>
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsImportPhotosAlgorithm::tags :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
