### ISSUE TITLE
QGIS Quit Unexpectedly (regularly happening after I close the window)

### ISSUE THREAD

**Issue by tbpantua** [qgis/QGIS#47730]
### What is the bug or the crash?

Afer I close the QGIS window it always sends a prompt that QGIS quit  unexpectedly.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/101374283/157785606-cfd672fd-cece-4e2b-8948-655948b8c851.png)

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
ee_plugin
0.0.4
GeometryShapes
0.7
Hy2roresO-master
0.0.1
OSMDownloader
1.0.3
pcraster_tools
0.2.0
QuickOSM
2.0.1
SVG2ColoR
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is a known issue with the pcraster tools plugin
