### ISSUE TITLE
Labels, always selects two like: "Above line' & 'Below line' or 'Above line' & 'On line'

### ISSUE THREAD

**Issue by K6ORJ** [qgis/QGIS#47748]
### What is the bug or the crash?

Labels, always selects two like: "Above line' & 'Below line' or 'Above line' & 'On line' or 'Below line' & 'On line" or all three.  There's no way to uncheck the other box

<img width="515" alt="Screenshot 2022-03-11 134150" src="https://user-images.githubusercontent.com/101201112/157974566-8b12dd08-97de-44ba-ac4f-dd270579d2f5.png">
.

### Steps to reproduce the issue

Go to Single labels placement.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qgis_resource_sharing | 0.16.0
quick_map_services | 0.19.28
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
qgis_resource_sharing
0.16.0
quick_map_services
0.19.28
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@K6ORJ can't confirm

![image](https://user-images.githubusercontent.com/1951107/158013959-3a79dd5b-efba-4374-9964-f9510ffd661b.png)


![image](https://user-images.githubusercontent.com/1951107/158013965-53b5fcf9-7523-41be-b3ce-64ae30688da6.png)


![image](https://user-images.githubusercontent.com/1951107/158013973-c7784ed2-d7b4-4c30-bca1-5591637e8aa3.png)

**Comment by K6ORJ** [comment]
Okay, I wonder why I it's happening to me.  I downloaded 3.16 and had the same problem, any ideas?

https://user-images.githubusercontent.com/101201112/158044429-9ded60f6-5033-4f30-8df2-4bdac11e72b1.mp4

**Comment by K6ORJ** [comment]
Deleted all of the QGIS folders in the sub folders of C:\Users\\AppData  problem gone.

**Comment by K6ORJ** [comment]
Broken again!  It brakes when:

 Settings > Options > General > Application > UI Theme > [Night Mapping]

If set to [Default] works fine.

**Comment by gioman** [comment]
> Settings > Options > General > Application > UI Theme > [Night Mapping]

@K6ORJ can't replicate

![image](https://user-images.githubusercontent.com/1951107/158050372-ebba5434-09ea-4e2b-a616-cf2df7dccdde.png)

**Comment by K6ORJ** [comment]
> > Settings > Options > General > Application > UI Theme > [Night Mapping]
> 
> @K6ORJ can't replicate
> 
> ![image](https://user-images.githubusercontent.com/1951107/158050372-ebba5434-09ea-4e2b-a616-cf2df7dccdde.png)

Is your box checked it didn't seem to change color like in mine?  Never the less I got it working, in normal theme.  Since I work in a darkened room much of the time, the dark theme is easier on the eyes.  Just out of my own curiosity I will install and check it on another windows box when I get time, but back to work for now.
