### ISSUE TITLE
Data Source Manager -> Vector -> Options pane not scrollable

### ISSUE THREAD

**Issue by marisn** [qgis/QGIS#47741]
### What is the bug or the crash?

Data Source Manager -> Vector -> Options pane contains a variable (auto-generated?) content. In a case of GML source, there could be a lot of options. When the Options pane is open, it is not possible to shrink the window in a vertical direction thus the window can be taller than screen vertical space.

### Steps to reproduce the issue

1. Go to Data Source Manager
2. Select Vector
3. Choose a GML file
4. Unfold Options pane
5. Try to resize window to less than 1080px height

### Versions

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.10
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
Compiled against SQLite | 3.37.2 | Running against SQLite | 3.38.0
PostgreSQL client version | 14.2 (Debian 14.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
Active Python plugins
plaingeometryeditor | 3.0.0
ImportPhotos | 3.0.3
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by marisn** [comment]
![QGIS_vector_option_height_bug](https://user-images.githubusercontent.com/17123023/157866845-700eb198-c248-4946-bd84-2571b849fb8e.png)
A screen shot with the window on a 1080px tall screen. Adding a scroll bar to Options pane or whole Vector tab content would solve the problem.

Nesting the content of active tab in a container with scroll bar could be an option as there are also other tabs in Data Source Manager that are not small screen friendly.

**Comment by gioman** [comment]
@marisn this is part of a more general UI issue (search the tracker, there are several reports about it) that affects several dialogs that are not suitable for screen resolutions under a certain size (i.e. I use frequently a 12.5 inches laptop with a 1360x768 pixels resolution and several dialogs are basically not usable).

**Comment by marisn** [comment]
@gioman I know :( I also reported an issue on the main window when I had to do a training with a 1024x768 beamer. But all of them need to be solved one by one. This is a bug report on one area and thus it can be closed in a single PR.
