### ISSUE TITLE
QgsRendererRange() needs old parameters in 3.16.16 standalone script

### ISSUE THREAD

**Issue by petrarch1603** [qgis/QGIS#47761]
### What is the bug or the crash?

According [to the docs](https://qgis.org/pyqgis/3.16/core/QgsRendererRange.html) the QgsRendererRange class takes on a QgsClassificationRange parameter. However when I run it in a standalone script (for a plugin), the class throws an error because it wants two int parameters (lower, upper) like in the old [3.0 QgsRenderRange](https://qgis.org/pyqgis/3.16/core/QgsRendererRange.html) . 

When the script runs: print(f"Version: {Qgis.version()}") in the plugin script it returns: Version: 3.16.16-Hannover

However when I try to initialize a QgsRendererRange in the python console it allows the QgsClassification parameter

### Steps to reproduce the issue

In standalone script attempt to initiate QgsRendererRange with a QgsClassificationRange and it throws error.

### Versions

3.16.16-Hannover

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
As 3.16 is EOL, you need to test on 3.22 or 3.24.
It won't be fixed on 3.16.
