### ISSUE TITLE
DB Manager the geometry field is not handled for virtual layers

### ISSUE THREAD

**Issue by FERRATON** [qgis/QGIS#47770]
### What is the bug or the crash?

In DB Manager
for virtual layers the geometry field is not displayed with 
A query
select * from matable
or
select geometry from my table
Oddly enough, if you load the table, even though you can't specify the geometry field, it is present.

### Steps to reproduce the issue

see above

### Versions

QGIS 3.22.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@FERRATON duplicate https://github.com/qgis/QGIS/issues/46025
