### ISSUE TITLE
Non-functional Oracle's panel in datasource

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#47794]
### What is the bug or the crash?

Hi,

In QGIS 3.24, the Oracle panel of the data source manager has no functional buttons (connect, new, edit, remove, load, save), clicking on one doesn't open a new windows as expected. The same actions in QGIS 3.22.4 does work.

Regards,
JR

### Steps to reproduce the issue

1. Go to **Data source Manager** > **Oracle**
2. Click on **New**
3. Nothing :)

### Versions

* Windows 10 Version 2009
* downloaded from qgis.org
  * QGIS 3.24.0-Tisler 6b44a42058
  * QGIS 3.22.4-Białowieża ce8e65e9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment]
I can reproduce on master, looks like Qt autoconnection signal/slot is not working anymore, not sure why though.

**Comment by Jean-Roc** [comment]
@ismailsunni it works on 3.22.4, the regression is in 3.24

**Comment by ismailsunni** [comment]
@Jean-Roc ah my bad, I thought it was not working on both (only read the `versions` part). Sorry for the noise
