### ISSUE TITLE
2022-03-15T11:47:03     CRITICAL    Error in the logs, in the QuickOSM pane

### ISSUE THREAD

**Issue by nkongdem** [qgis/QGIS#47793]
### What is the bug or the crash?

2022-03-15T11:47:03     CRITICAL    Error in the logs, in the Quick OSM pane

### Steps to reproduce the issue

2022-03-15T11:47:03     CRITICAL    Error in the logs, in the Quick OSM pane

### Versions

3.22.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
1. Note the latest QGIS version and not supported according to roadmap --> Wrong
2. You obviously didn't try with a new profile (as it's plugin related)
3. Plugin error should not be reported here but on plugin repository directly

**Comment by alexbruy** [comment]
Duplicates #47789.
