### ISSUE TITLE
Loading large attribute form using PostGIS provider freezes QGIS   

### ISSUE THREAD

**Issue by jarnokin** [qgis/QGIS#47797]
### What is the bug or the crash?

Loading large attribute form using PostGIS provider freezes QGIS. This happens when using table which have approx. 1 Million rows. We tested with table having 100 000 rows, which loaded well, but when table have 1 Million rows, loading took over 1 minute in local database and over 5 minutes in remote database (AWS).

When investigating the issue, we noticed that QGIS makes many duplicate SQL queries to the database which could cause at least some of the slowness. We created a [performance test project](https://github.com/GispoCoding/qgis-postgis-performance-test) to address this issue. 

It can be seen from the [logs](https://github.com/GispoCoding/qgis-postgis-performance-test/blob/main/logs/open%20form%20lot5.log) that QGIS generates many duplicate queries. For example
```sql
BEGIN READ ONLY;DECLARE qgis_138 BINARY CURSOR FOR SELECT "id","name"::text FROM "qgisdbtest"."land_parcel"
FETCH FORWARD 2000 FROM qgis_138
CLOSE qgis_138;COMMIT
BEGIN READ ONLY;DECLARE qgis_140 BINARY CURSOR FOR SELECT "id","name"::text FROM "qgisdbtest"."land_parcel"
FETCH FORWARD 2000 FROM qgis_140
CLOSE qgis_140;COMMIT
BEGIN READ ONLY;DECLARE qgis_142 BINARY CURSOR FOR SELECT "id","name"::text FROM "qgisdbtest"."land_parcel"
FETCH FORWARD 2000 FROM qgis_142
CLOSE qgis_142;COMMIT
```
It also checks the PostGIS version many times:
```sql
SELECT postgis_version()
SELECT postgis_version()
SELECT postgis_version()
```
Could there be some room for optimization in the database queries or can some kind of paging be utilised when opening large tables?

### Steps to reproduce the issue

We created a testbed and environment for you to test and validate the issue. Please follow these instructions: 

**1. Establish a new PostGIS in connection in QGIS with following parameters:**

- PostGIS instance IP: 18.195.144.58
- Port: 5432 
- User: readonly
- Password: readonly

**2. Open a QGIS project stored in the database**

- You can find it from qgisdbtest schema (project name: qgis-project) 
- The project contain tables 'buildings' and 'land_parcel'. The tables have randomly generated content.

**3. Open Attribute Table and see how long loading will take and how QGIS freezes meanwhile** 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.22.2-Białowieża | QGIS code revision | 1601ec46d0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | 12.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.3
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.2-Białowieża
QGIS code revision
[1601ec46d0](https://github.com/qgis/QGIS/commit/1601ec46d0)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
12.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.3

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

If you want to improve our performance test project, feel free to contribute.

**Comment by Joonalai** [comment]
Could the pipeline mode introduced in postgresql14 libpq be reduce those latencies as mentioned in the [mailing list](https://lists.osgeo.org/pipermail/qgis-developer/2022-March/064584.html)?

**Comment by LKajan** [comment]
I did some modifications to the sample project https://github.com/GispoCoding/qgis-postgis-performance-test elaborating the issue.

We had a small talk at Foss4g with @vpicavet and he thought that you @troopa81 and @m-kuhn might have some ideas of these qgis forms and duplicate queries.

**Comment by m-kuhn** [comment]
Thanks for opening.

We need to distinguish between two different things:

1. Optimizing the attribute table as it is now. We have "modes" for it, e.g. "only show features visible on canvas" which improve the initial loading time. We could likely also look into some minor optimization along the line of reducing the postgis_version detection. The other "duplicate" query is not actually duplicate but a result of loading the features in batches (of 2000 IIRC). Pipeline mode could possibly improve the performance too.
2. Rework the attribute table, e.g. by introducing paging, making better use of background processes etc. This is non-trivial work which should be conducted at some point by an experienced QGIS developer, but before doing that a proper concept should be established and ideally a prototype outside of QGIS core should be developed to allow a couple of iterations and user testing before being ported to QGIS core and being locked into QGIS core's release schedule, review process and API stability guarantee.

**Comment by LKajan** [comment]
Thanks @m-kuhn for taking a look!

We have quite a good or tolerable performance when working in table mode/view of a layer. But the issue raises when opening a form view of a single "parent" feaure with Info Tool. It might take 10-40 seconds to load the form.

> The other "duplicate" query is not actually duplicate but a result of loading the features in batches (of 2000 IIRC). Pipeline mode could possibly improve the performance too.

Batch loading would show differently, I think. Like this:
```
DECLARE qgis_26 BINARY CURSOR FOR SELECT "id","name"::text FROM "qgisdbtest"."land_parcel";
FETCH FORWARD 2000 FROM qgis_26;
FETCH FORWARD 2000 FROM qgis_26;
FETCH FORWARD 2000 FROM qgis_26;
FETCH FORWARD 2000 FROM qgis_26;
CLOSE qgis_26;
```
Now it creates three separate cursors and fetches 2000 from each.

**Comment by m-kuhn** [comment]
That's likely linked to specific widgets on this form then (most suspect relation ones).

**Comment by m-kuhn** [comment]
> I think there is possible optimizations to avoid duplicated request, but it's not easy fix

Do you have something specific in mind?

At the origin the following things were put in place to mitigate situations like this:

- lazy loading only when visible, e.g. putting a relation editor widget on a separate tab will only load it when this tab is shown
- background iterators, loading should work in the background and the form loaded "instantly" while "slow" widgets receive content or functionality only after a while

I did not check if these things are still fully functional in their current state

**Comment by troopa81** [comment]
> Do you have something specific in mind?

Regarding value relation there were some quite easy small optimisations, like we execute the request in the constructor and then after the call of setExtraColumn which is called just after. Or check in setters if value has changed before calling the update method.

Or having a vectorlayercache at the higher level and share it among form, attribute table, search widget wrapper...

It looks like also that we get the geometry when we evaluate the relation, though we don't always need it in form.

But, this is just quick ideas from what I remember, it needs a more thorough study.

**Comment by m-kuhn** [comment]
> > Do you have something specific in mind?
> 
> Regarding value relation there were some quite easy small optimisations, like we execute the request in the constructor and then after the call of setExtraColumn which is called just after. Or check in setters if value has changed before calling the update method.
> 

That sounds good

> Or having a vectorlayercache at the higher level and share it among form, attribute table, search widget wrapper...

I'd be very cautious doing something like that it will add a layer of complexity that might come at a very expensive (maintenance) price

> 
> It looks like also that we get the geometry when we evaluate the relation, though we don't always need it in form.
> 
> But, this is just quick ideas from what I remember, it needs a more thorough study.

Agreed

**Comment by troopa81** [comment]
> I'd be very cautious doing something like that it will add a layer of complexity that might come at a very expensive (maintenance) price

I agree, it's certainly best to go for small optimizations at first

**Comment by nyalldawson** [comment]
> > Or having a vectorlayercache at the higher level and share it among form, attribute table, search widget wrapper...

>>I'd be very cautious doing something like that it will add a layer of complexity that might come at a very expensive (maintenance) price

Honestly this seems like a reasonable approach to me. At least we should start by adding a Widget Context class and passing that around from the form to the widgets so that we've got a future place to put things like this....

**Comment by m-kuhn** [comment]
We will have to deal with cache invalidation and adding logic to decide which features/requests can be served from the cache at hand. I think this deserves a good concept before starting something.

**Comment by nyalldawson** [comment]
@m-kuhn 

QgsVectorLayerCache should already have all that logic in place... It's what we use for the main feature of the form, after all, so I'd be surprised if it wouldn't work sufficiently well for the child widgets

**Comment by m-kuhn** [comment]
It was designed with one "view" with one specific filter at a time in mind. Not to feed multiple ones with different filters in parallel.
I would recommend evaluating under that context first.

**Comment by nyalldawson** [comment]
@m-kuhn 

True, good point :+1: 

I'd love to revisit layer caching at some point... it would be very nice to use the cache for rendering too.

**Comment by MorriganR** [comment]
Sorry, but before adding another cache, you should look at the still open issue #31251, the consequences of this can be unpredictable... :)

**Comment by m-kuhn** [comment]
> I'd love to revisit layer caching at some point... it would be very nice to use the cache for rendering too.

Sounds good, it just needs to be optional. It could also be considered to combine this with the WFS caching where something alike is already present.

**Comment by MorriganR** [comment]
Hi @LKajan.
> Have the "Auto open form for single feature result" setting enabled and use Identify Feature tool to click some land parcel. It takes about 20 seconds for me to get the form to open.

There must be something wrong with the project file. The form for "land parcel" took more than a minute to open. Something is causing QGIS to load all the data from the tables before showing the form to the user.

![00002](https://user-images.githubusercontent.com/31573086/189232898-8108e744-8204-407d-8ca0-1f8ea7e0b0e7.PNG)

I created a new QGIS project with your data, in it the form for "land parcel" opens in a few seconds, which is quite good, considering that the delay to the PG server from my machine is 100ms.

[qqqqq.qgz](https://github.com/qgis/QGIS/files/9530877/qqqqq.zip)

**Comment by LKajan** [comment]
Thanks @MorriganR for taking a look into this!
I tested your sample project and indeed it didn't have this problem (at first). I dug a bit your xml-project file and noticed that in your project there is no `relation reference` set up for the `land_parcel_id` field on `buildings` table. I wondered a bit how you even managed to create that kind of project file :) .
Apparently if you save the project without ever visiting the `Attributes form` of the building layer it doesn't save configuration and you end up with this kind of xml in the project file:
```xml
        <field configurationFlags="None" name="land_parcel_id">
          <editWidget type="RelationReference">
            <config>
              <Option/>
            </config>
          </editWidget>
        </field>
```
But if you go the Attributes Form settings and just select the land_parcel_id field and without even changing anything hit apply then it saves the RelationReference configuration:
```xml
        <field configurationFlags="None" name="land_parcel_id">
          <editWidget type="RelationReference">
            <config>
              <Option type="Map">
                <Option type="bool" value="false" name="AllowAddFeatures"/>
                <Option type="bool" value="false" name="AllowNULL"/>
                <Option type="bool" value="false" name="MapIdentification"/>
                <Option type="bool" value="false" name="OrderByValue"/>
                <Option type="bool" value="false" name="ReadOnly"/>
                <Option type="QString" value="dbname='postgres' host=18.195.144.58 port=5432 user='readonly' sslmode=disable key='id' estimatedmetadata=true srid=3857 type=Polygon checkPrimaryKeyUnicity='1' table=&quot;qgisdbtest&quot;.&quot;land_parcel&quot; (geom)" name="ReferencedLayerDataSource"/>
                <Option type="QString" value="land_parcel_fcc7347a_8060_4df2_9e0c_94008de3cd71" name="ReferencedLayerId"/>
                <Option type="QString" value="land_parcel" name="ReferencedLayerName"/>
                <Option type="QString" value="postgres" name="ReferencedLayerProviderKey"/>
                <Option type="QString" value="building_7dfafa1a_ec2e_4731_b01d_429b57f8da79_land_parcel_id_land_parcel_fcc7347a_8060_4df2_9e0c_94008de3cd71_id" name="Relation"/>
                <Option type="bool" value="false" name="ShowForm"/>
                <Option type="bool" value="true" name="ShowOpenFormButton"/>
              </Option>
            </config>
          </editWidget>
        </field>
```

So the Relation Reference Widget seems to be the cause of querying ALL names from the land_parcel table three times.

Here's the simples way to reproduce the issue:
1. Load tables `building` and `land_parcel` to the project
2. Add a relationship `Project Properties -> Relations -> Discover Relations -> select land_parcel_fk -> OK` 
Now opening a form for a single land_parcel takes just couple of seconds or so.
But if you 
3. Set `land_parcel_id` on the `building` form to be a `Relation Reference` widget things goes bad.

**Comment by strk** [comment]
> It also checks the PostGIS version many times:
> 
> ```sql
> SELECT postgis_version()
> SELECT postgis_version()
> SELECT postgis_version()
> ```


The duplicated PostGIS version string fetching was also reported in
https://github.com/qgis/QGIS/issues/47391
It seems to be an ineffective reuse of connections

**Comment by alexbruy** [comment]
What is the status of this? As far I can see at least some things were fixed.

**Comment by troopa81** [comment]
> What is the status of this? As far I can see at least some things were fixed.

I would be in favor to close the issue since things have been improved in this particular area. If there is still freeze happening, I would be interested to know when and how?

@jarnokin Do you agree?
