### ISSUE TITLE
Layer could not be generated

### ISSUE THREAD

**Issue by Ozgurylmz1997** [qgis/QGIS#47802]
### What is the bug or the crash?

I am getting this error when using the Saga Thiessen polygon command. Output layer is not created.
I am getting this error on all SAGA commands. I saved output layer to different fields but it is not created. (save to file)

Qgis 3.16.0
QGIS code revision: 43b64b13f3
I use win10

I did following link but It is not created.
https://github.com/qgis/QGIS/commit/286fd207c42b11b4b8cc980f446088201ec1a5fa

This error;
The following layers were not correctly generated.
• C:/Users/özgür/AppData/Local/Temp/processing_VwvPoV/ad67039ce33b44e0970b4ade2dac6174/POLYGONS.shp
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Steps to reproduce the issue

![asd](https://user-images.githubusercontent.com/101656928/158420619-22d16b19-70fd-4861-a352-ffb78bb0bc2c.JPG)

### Versions

QGIS version
3.16.0-Hannover
QGIS code revision
43b64b13f3
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
profiletool; 
quick_map_services; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Ozgurylmz1997 Hello, from my understanding, SAGA 7.8.2 is not officially supported by QGIS. If that is the case with your installation, it is normal to encounter a few issues here and there. Anyway, could you try with a new profile? 
If that doensn't work. this would be the solution:
[https://www.youtube.com/watch?v=VKdaripCups](url)

**Comment by alexbruy** [comment]
Which SAGA version are you using? As @Pedro-Murteira said, QGIS supports only SAGA 2.x, for other versions you should use one of the 3rd party plugins.

Looking at the location of your data, there are non-ASCII charactes in the path. Please test using path which does not have any non-ASCII characters. Also it is worth checking whether SAGA produce valid results when run directly with the same data.

**Comment by Ozgurylmz1997** [comment]
> @Ozgurylmz1997 Hello, from my understanding, SAGA 7.8.2 is not officially supported by QGIS. If that is the case with your installation, it is normal to encounter a few issues here and there. Anyway, could you try with a new profile? If that doensn't work. this would be the solution:
> 
> * https://www.youtube.com/watch?v=VKdaripCups
