### ISSUE TITLE
Pie Chart does not work with expression values (QGIS 3.24)

### ISSUE THREAD

**Issue by brandtf** [qgis/QGIS#47800]
### What is the bug or the crash?

I created a pie chart based on a polygon feature layer. The combination of attributes of the features represent a specific status in a workflow. The pie chart should visualize the percentage of areas with a specific status. To accomplish this, I defined pie chart attributes for each status with the expression editor. I used aggregation functions to sum up the features with a specific combination of attributes :

(SUM("uebernahme_db" IS NULL AND "uebernahme_atkis_beginn" IS NULL AND "abgabe_atkis" IS NULL AND "gt_bearb_ab" IS NOT NULL AND "plan_atkis" > now()) / 590) * 100

This results in an percentage of 13.220, which is correctly previewed in the expression editor. Unfortunately, the pie chart remains emtpy when I confirm my formulas. When I simply enter the integer value of 13.220, it is shown in the diagram.

### Steps to reproduce the issue

![piechart](https://user-images.githubusercontent.com/100597297/158394164-23ed4f04-76b2-487e-b915-71ea13393a60.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.24.0-Tisler | QGIS-Codeversion | 6b44a42058
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20

</body></html>QGIS-Version
3.24.0-Tisler
QGIS-Codeversion
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I confirm

## OSGeo4W64 v2 Win 10 Pro 64b

**Comment by pigreco** [comment]
the problem is also present in QGIS 3.22.4 LTR

![image](https://user-images.githubusercontent.com/7631137/158579937-40595636-f7e3-46b1-a328-dab22823bdf2.png)

## OSGeo4W64 v2 Win 10 Pro 64b

**Comment by pigreco** [comment]
## OSGeo4W64 v2 Win 10 Pro 64 bit - QGIS dev 3.25.0-252

it does not work

![image](https://user-images.githubusercontent.com/7631137/172044323-7a5fee7a-bcec-4936-bb31-b5fcb1592511.png)

**Comment by pigreco** [comment]
Thank you very much!

![image](https://user-images.githubusercontent.com/7631137/172774140-f7ec2bbd-6aab-4b24-8d93-e667eaefc2b2.png)
