### ISSUE TITLE
Zoom Last zooms out further than the previous scale, rather than to the exact scale in scale history (ROTATED MAPS ONLY)

### ISSUE THREAD

**Issue by EG-Biology** [qgis/QGIS#47810]
### What is the bug or the crash?

"Zoom Last" **should** go back to the exact scale in the scale history.

I'm manually digitizing features on 12,000 square miles of land from satellite imagery. On my computer I can visually scan an area scaled to 1:6500, but I often need a closer look when I find a feature. I use the zoom tool to get as close as I need to, digitize the feature, and then click "Zoom Last". At this point, the map zooms out to 1:7151 [see note 2], which makes the satellite imagery too small to scan, and I have to manually re-scale each time, which is an enormous time suck. 

I haven't been able to find any other reports of this issue or workarounds. I even tried to find a way to force predefined scales, but it doesn't seem to be possible. 

**Note 1:** To be clear this bug happens regardless of starting scale, or the method or amount of zooming in one step (e.g. single click vs. drawing a bounding box).

**Note 2:** While typing this bug report, the ending scale was _consistently 1:7151_ every time I started at 1:6500. This was true whether I clicked to zoom, drew a small bounding box, or drew a large bounding box. HOWEVER, when I tested the bug on a new user profile, the ending scale was _consistently 1:7133_. It turns out that this variation is due to the width of the left-docked panels going back to the default width on the new instance of QGIS [see Troubleshooting Tip below].

**Note 3:** After the first instance of incorrect rescaling, if I zoom in again, then "Zoom Last" operates appropriately. But at this point the last scale is incorrect.

**Troubleshooting Tips:**
1. I figured out that the left-docked panel width affects the amount of error, but not in any consistent pattern that I could see.
2. Basically, it seems as though QGIS doesn't like my chosen scale, so it picks something close.

### Steps to reproduce the issue

**UPDATE: Issue only occurs when map rotation is non-zero.** I'm working with the map rotated -3.7 degrees to align the grid of cadastre sections with my monitor and get more imagery on-screen. I checked for the bug with the rotation set to positive, negative, and zero values, and it only occurs when rotation is non-zero. Maddeningly, sometimes the error occurs right after changing the rotation, and other times I have to pan the map after changing the rotation, reset the scale to the preferred value, and try again.

0. Set map rotation to a non-zero value
1. Set scale
2. Use Zoom In tool either with a single click or drawing a box (NOT using scroll wheel or trackpad scrolling gesture)
3. Click "Zoom Last"
4. Denominator of scale is larger than that set in step 1. If not, pan the map a bit and go back to step 1.
5. Repeat step 2 without otherwise rescaling.
6. Click "Zoom Last"
7. Denominator of scale is the same as in step 4

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | 3f4577ce6e
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 11.6
  |   |   |  
Active Python plugins
lockzoom | 3.0.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[3f4577ce6e](https://github.com/qgis/QGIS/commit/3f4577ce6e)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 11.6

Active Python plugins
lockzoom
3.0.3
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have two WMS layers for satellite imagery: Google Satellite and Bing Maps. I also have Open Street Maps loaded as XYZ tiles.

**Comment by uclaros** [comment]
Can't reproduce on master on linux.

> HOWEVER, when I tested the bug on a new user profile, the ending scale was _consistently 1:7133_

Did you test on a new profile before adding any plugins? Especially *lockzoom* sounds suspicious!

**Comment by EG-Biology** [comment]
I'm a brand new QGIS user, and this issue existed with a clean install. I installed _lockzoom_ as a desperate attempt to fix the issue, but it only works with two projections that aren't what I'm using in this project.

But to answer your question, yes. The version information above is from the default user profile, but I created a new user profile as instructed while writing up this bug report. I didn't add any plugins to the new user profile.

Also I don't know if it makes a difference, but I'm using a Mac, not Linux.

**Comment by EG-Biology** [comment]
**UPDATE: Issue only occurs when map rotation is non-zero.** I'm working with the map rotated -3.7 degrees to align the grid of cadastre sections with my monitor and get more imagery on-screen. I checked for the bug with the rotation set to positive, negative, and zero values, and it only occurs when rotation is non-zero. Maddeningly, sometimes the error occurs right after changing the rotation, and other times I have to pan the map after changing the rotation, reset the scale to the preferred value, and try again.

I've added this paragraph to the troubleshooting notes above.

**Comment by EG-Biology** [comment]
This issue also happens when _zooming in_ when the map is rotated.
0. Set Zoom Factor to 200%
1. Set scale to 1:6500 and rotation to -3 degrees.
2. Using the Zoom In tool, single-click map. Scale changes to 1:3504. Your exact results may vary, depending on width of left-docked panels*.
3. Click Zoom Last. Scale changes to 1:7007. Same caveat as in previous step.

* The fact that the width of the left-docked panels alters the behavior of zooming a rotated map should probably be considered a separate bug.

**Comment by EG-Biology** [comment]
If you Zoom In, Zoom Last, Pan, and _repeat without manually rescaling_, the scale denominator increases with each Zoom Last. Since this is my entire workflow (other than digitizing), the map keeps zooming out farther and farther with each iteration. Every time that happens I have to manually zoom in.

**Comment by uclaros** [comment]
Ok, I confirm, rotating the map messes the extent history indeed.

**Comment by EG-Biology** [comment]
> Ok, I confirm, rotating the map messes the extent history indeed.

It's nice to know it's not just me! :)

**Comment by ismailsunni** [comment]
Probably related to https://github.com/qgis/QGIS/issues/46775

**Comment by Djedouas** [comment]
Reproduced today on master rev b7a7e17f33

**Comment by Djedouas** [comment]
> Probably related to #46775

Fixing one will not fix the other, but they are both issues about not taking rotation into account 👍🏼 

Here it's about the zoom level in the zoom history, in #46775 it's about zooming to the extent of a layer.
