### ISSUE TITLE
PostGIS Raster loading extrem long in QGIS 3.16 and 3.22

### ISSUE THREAD

**Issue by gisp45des** [qgis/QGIS#47815]
### What is the bug or the crash?

For QGIS 3.16 and 3.22 I can report the following issue.
When I try to add a PostGIS raster with 32 bit floating point and a resolution of 2m into QGIS the query SELECT ST_SummaryStatsAgg() needs a lot of time at least 10-20 minutes on database.

### Steps to reproduce the issue

Add a postgis raster with float32 bit and high resolution [2m] .

### Versions

QGIS 3.16 or 3.22

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

QGIS 3.10.4 loads the same raster nearly instantly.

**Comment by elpaso** [comment]
What's the size (number of cells) of the raster?

**Comment by gisp45des** [comment]
The number of pixels for the 2m resolution raster are 10'773'483'520 including nodata pixels

**Comment by elpaso** [comment]
Did you create overviews? That should help as a workaround.

**Comment by gisp45des** [comment]
Yes, I created 6 overviews and also Indices .

**Comment by elpaso** [comment]
Ok, it's hard to tell exactly which code path is taken here, if overviews rare available and the raster is tiled and there is no subset filter, the provider is supposed to run ST_SummaryStatsAgg on the whole overview dataset (the rationale is that we are using an overview which is already an approximation of the real data so we try to gather full statistics).

Can you check the server logs and see if this is the case (i.e. it is running ST_SummaryStatsAgg on the overview) ? 

Also, can you check if in the layer's connection settings of the raster "Use estimated metadata" is checked?

**Comment by elpaso** [comment]
I can confirm that overviews are used to gather statistics if they are available.

On my test case this query is executed:

`SELECT (ST_SummaryStatsAgg( "rast", 1, TRUE, 1 )).* FROM "copernicus"."o_32_eu_dem_v11_E40N10"`

```sql
      r_table_name      | scale_x | scale_y 
------------------------+---------+---------
 eu_dem_v11_E40N10      |      25 |     -25
 o_4_eu_dem_v11_E40N10  |     100 |    -100
 o_16_eu_dem_v11_E40N10 |     400 |    -400
 o_32_eu_dem_v11_E40N10 |     800 |    -800
 o_64_eu_dem_v11_E40N10 |    1600 |   -1600
```

If there are no overviews or the overviews resolution is too low it falls back to the full table, but with a sample size of 250000 px which is converted to a percentage.

Is there any chance you can get me an access to your table so that I can see what's going on? 
You can send me a pm with the access information.

**Comment by gisp45des** [comment]
I apoligize for the late answer. I was doing a course on postgis the last three days. Unfortunately I can not give you the access to the database due to securtiy restrictions. But it is possible to share the screen via Skype, Teams, Zoom, etc..  

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/pbircher/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/pbircher/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



r_table_name | r_raster_column | srid | scale_x | scale_y | blocksize_x | blocksize_y | same_alignment | regular_blocking | num_bands | pixel_types | nodata_values | out_db | extent | spatial_index
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
swissalti3d_2m_gesamt | rast | 2056 | 2 | -2 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {t} | 01030000200808000001000000050000000000000084F5424100000000403C30410000000084F542410000000050CE334100000000289F45410000000050CE334100000000289F454100000000403C30410000000084F5424100000000403C3041 | WAHR
o_8_swissalti3d_2m_gesamt | rast | 2056 | 16 | -16 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000403C30410000000084F542410000000050CE3341000000002C9F45410000000050CE3341000000002C9F454100000000403C30410000000084F5424100000000403C3041 | WAHR
o_64_swissalti3d_2m_gesamt | rast | 2056 | 128 | -128 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000503C30410000000084F542410000000050CE334100000000449F45410000000050CE334100000000449F454100000000503C30410000000084F5424100000000503C3041 | WAHR
o_4_swissalti3d_2m_gesamt | rast | 2056 | 8 | -8 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000403C30410000000084F542410000000050CE334100000000289F45410000000050CE334100000000289F454100000000403C30410000000084F5424100000000403C3041 | WAHR
o_32_swissalti3d_2m_gesamt | rast | 2056 | 64 | -64 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000503C30410000000084F542410000000050CE334100000000249F45410000000050CE334100000000249F454100000000503C30410000000084F5424100000000503C3041 | WAHR
o_2_swissalti3d_2m_gesamt | rast | 2056 | 4 | -4 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000403C30410000000084F542410000000050CE334100000000289F45410000000050CE334100000000289F454100000000403C30410000000084F5424100000000403C3041 | WAHR
o_16_swissalti3d_2m_gesamt | rast | 2056 | 32 | -32 | 256 | 256 | WAHR | FALSCH | 1 | {32BF} | {-9999} | {f} | 01030000200808000001000000050000000000000084F5424100000000303C30410000000084F542410000000050CE334100000000249F45410000000050CE334100000000249F454100000000303C30410000000084F5424100000000303C3041 | WAHR



</body>

</html>

**Comment by gisp45des** [comment]
A further interesting aspect i discovered is, that the long lasting Query St_summarystatsAgg() only appears on a windows client with QGIS. When a ubuntu client via windows subsystem for linux is used the loading time is fast.

**Comment by gisp45des** [comment]
Log-file Linux-client:
src/core/raster/qgsrasterlayer.cpp:210 : (lastModified) [0ms] name=dbname='database' host=xxx.xxx.xxx.xx port=5432 sslmode=disable estimatedmetadata=true srid=2056 table="a_ba_stopo"."DEM_2m" (rast)
src/core/raster/qgsrasterlayer.cpp:876 : (setDataProvider) [0ms] exiting.
src/core/raster/qgsrasterlayer.cpp:1487 : (setDefaultContrastEnhancement) [0ms] Entered
src/core/raster/qgsrasterpipe.cpp:259 : (interface) [0ms] role = Renderer
src/core/raster/qgsrasterlayer.cpp:1471 : (defaultContrastEnhancementSettings) [0ms] key = singleBand
src/core/raster/qgsrasterlayer.cpp:1474 : (defaultContrastEnhancementSettings) [0ms] myAlgorithmString = StretchToMinimumMaximum
src/core/raster/qgsrasterlayer.cpp:1479 : (defaultContrastEnhancementSettings) [0ms] myLimitsString = MinMax
src/core/raster/qgsrasterpipe.cpp:259 : (interface) [3ms] role = Renderer
src/core/raster/qgsrasterlayer.cpp:1109 : (setContrastEnhancement) [0ms] theAlgorithm = 1 limits = 1 extent.isEmpty() = 1
src/core/raster/qgsrasterinterface.cpp:42 : (initStatistics) [0ms] theBandNo = 1 sampleSize = 250000
src/core/raster/qgsrasterinterface.cpp:72 : (initStatistics) [0ms] xRes = 571.545 yRes = 571.545
src/core/raster/qgsrasterinterface.cpp:90 : (initStatistics) [0ms] theStatistics.width = 611 statistics.height = 410
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2348 : (bandStatistics) [0ms] Using overview for statistics read: "a_ba_stopo"."o_64_DEM_2m"
src/providers/postgres/qgspostgresconn.cpp:1336 : (PQexec) [0ms] Executing SQL: SELECT (ST_SummaryStatsAgg( "rast", 1, TRUE, 1 )).* FROM "a_ba_stopo"."o_64_DEM_2m" 
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2393 : (bandStatistics) [**166ms**](_)************ STATS **************
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2394 : (bandStatistics) [0ms] MIN 193.393
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2395 : (bandStatistics) [0ms] MAX 4574.71
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2396 : (bandStatistics) [0ms] RANGE 4381.32
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2397 : (bandStatistics) [0ms] MEAN 1284.75
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2398 : (bandStatistics) [0ms] STDDEV 807.779
src/core/raster/qgsrasterlayer.cpp:1073 : (computeMinMax) [0ms] band = 1 min = 193.393 max = 4574.71
src/core/raster/qgscontrastenhancement.cpp:202 : (setMinimumValue) [0ms] called value: 193.393 generate lookup table: 1
src/core/raster/qgscontrastenhancement.cpp:176 : (setMaximumValue) [0ms] called value: 4574.71 generate lookup table: 1
src/core/raster/qgsrasterpipe.cpp:259 : (interface) [0ms] role = Renderer

**Comment by gisp45des** [comment]
Log-file Windows-client:
src/core/raster/qgsrasterlayer.cpp:210 : (lastModified) [0ms] name=dbname='database' host=xxx.xxx.xxx.xx port=5432 sslmode=disable estimatedmetadata=true srid=2056 table="a_ba_stopo"."DEM_2m" (rast)
src/core/raster/qgsrasterlayer.cpp:876 : (setDataProvider) [0ms] exiting.
src/core/raster/qgsrasterlayer.cpp:1487 : (setDefaultContrastEnhancement) [0ms] Entered
src/core/raster/qgsrasterpipe.cpp:259 : (interface) [0ms] role = Renderer
src/core/raster/qgsrasterlayer.cpp:1471 : (defaultContrastEnhancementSettings) [0ms] key = singleBand
src/core/raster/qgsrasterlayer.cpp:1474 : (defaultContrastEnhancementSettings) [0ms] myAlgorithmString = StretchToMinimumMaximum
src/core/raster/qgsrasterlayer.cpp:1479 : (defaultContrastEnhancementSettings) [0ms] myLimitsString = MinMax
src/core/raster/qgsrasterpipe.cpp:259 : (interface) [0ms] role = Renderer
src/core/raster/qgsrasterlayer.cpp:1109 : (setContrastEnhancement) [0ms] theAlgorithm = 1 limits = 1 extent.isEmpty() = 1
src/core/raster/qgsrasterinterface.cpp:42 : (initStatistics) [0ms] theBandNo = 1 sampleSize = 250000
src/core/raster/qgsrasterinterface.cpp:72 : (initStatistics) [0ms] xRes = 571.545 yRes = 571.545
src/core/raster/qgsrasterinterface.cpp:90 : (initStatistics) [0ms] theStatistics.width = 611 statistics.height = 410
src/providers/postgres/qgspostgresconn.cpp:1336 : (PQexec) [0ms] Executing SQL: SELECT (ST_SummaryStatsAgg( "rast", 1, TRUE, 0 )).* FROM "a_ba_stopo"."DEM_2m" 
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2393 : (bandStatistics) [**877283ms**](_) ************ STATS **************
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2394 : (bandStatistics) [2ms] MIN 189.144
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2395 : (bandStatistics) [0ms] MAX 4632.37
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2396 : (bandStatistics) [0ms] RANGE 4443.22
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2397 : (bandStatistics) [0ms] MEAN 6727.58
src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2398 : (bandStatistics) [0ms] STDDEV 1848.43
src/core/raster/qgsrasterlayer.cpp:1073 : (computeMinMax) [0ms] band = 1 min = 189.144 max = 4632.37
src/core/raster/qgscontrastenhancement.cpp:202 : (setMinimumValue) [0ms] called value: 189.144 generate lookup table: 1
src/core/raster/qgscontrastenhancement.cpp:176 : (setMaximumValue) [0ms] called value: 4632.37 generate lookup table: 1

**Comment by elpaso** [comment]
Ok, from the logs Linux is using the overview "o_64_DEM_2m" for stats while windows is not.

I have no idea why it happens, the code is supposed to be the same.

**Comment by Joonalai** [comment]
> It seems to calculate statistics only for the main table. The "use estimated metadata" is checked for the postgis connection. An interesting aspect is that when I use the gdal provider insteatd of the native QGIS provider the raster loads nearly instantly.

I am suffering from the same problem. How exactly @gisp45des you used GDAL provider to add the raster layer to QGIS? I couldn't find any example of this over the internet.

**Comment by gisp45des** [comment]
@Joonalai 
I could not solve the above mentioned issue in Windows. But when I installed QGIS via WSL (Windows Subsystem Linux) the postgis-raster seems to work properly. 
See WSL: https://learn.microsoft.com/de-de/windows/wsl/install

**Comment by Joonalai** [comment]
Unfortunately WSL or any other Linux based system is not an option for our production environment. It seems that we have to use a separate WCS for this.

**Comment by Joonalai** [comment]
After debugging with master branch (commit 1aa417) on both Linux and Windows 10, I was able to reproduce the bug using the similar data. I noticed that for some reason Windows turns calculation of pixelsRatio negative when the double is small enough

https://github.com/qgis/QGIS/blob/b762001968e43bd4c686af2227c07ba9243812ac/src/providers/postgres/raster/qgspostgresrasterprovider.cpp#L2421

With my test data, the calculation of 250000 / (384000 * 624000) becomes 1.0433e-06 on Linux and **-0.0003** on Windows. 

Thus desiredOverviewFactor becomes 979 on Linux and 0 on Windows on line https://github.com/qgis/QGIS/blob/b762001968e43bd4c686af2227c07ba9243812ac/src/providers/postgres/raster/qgspostgresrasterprovider.cpp#L2427

and no overview level is obviously smaller than that.

Here is gdb output from Windows 10:
<details>

```
Thread 1 hit Breakpoint 1, QgsPostgresRasterProvider::bandStatistics (this=0x211108bba80, bandNo=1,
    stats=<optimized out>, extent=..., sampleSize=250000, feedback=0x0)
    at /QGIS/src/providers/postgres/raster/qgspostgresrasterprovider.cpp:2420
2420    /QGIS/src/providers/postgres/raster/qgspostgresrasterprovider.cpp: No such file or directory.
(gdb) p sampleSize
$1 = 250000
(gdb) p mWidth
$2 = 384000
(gdb) p mHeight
$3 = 624000
...
(gdb) p pixelsRatio
$4 = -0.00027711007305135843
(gdb) p static_cast<double>( sampleSize ) / ( mWidth * mHeight )
$5 = -0.00027711007305135843
(gdb) p pixelsRatio < 0
$6 = true
...
(gdb) p desiredOverviewFactor
$7 = 0
```
</details>

and here are the relevant variables as a screenshot from QtCreator on Linux:

<details>

<img src="https://github.com/qgis/QGIS/assets/33314057/80a288b0-3e82-4dbb-98a0-5d970005acd9" alt="qtcreator debug variables" width="400"/>

</details>

I would be interested in fixing the bug. @elpaso what would be a correct fix for this? I noticed that just turning the pixelsRatio as an absolute number helps to get the wanted result with this example.

**Comment by elpaso** [comment]
@Joonalai good catch, thank you!! 
This issue has been bugging me for a while.

The solution is to turn long to qlonglong.

```patch
diff --git a/src/providers/postgres/raster/qgspostgresrasterprovider.h b/src/providers/postgres/raster/qgspostgresrasterprovider.h
index 48bcd48f137..0f761a06baf 100644
--- a/src/providers/postgres/raster/qgspostgresrasterprovider.h
+++ b/src/providers/postgres/raster/qgspostgresrasterprovider.h
@@ -126,9 +126,9 @@ class QgsPostgresRasterProvider : public QgsRasterDataProvider
     //! Has spatial index
     bool mHasSpatialIndex = false;
     //! Raster size x
-    long mWidth = 0;
+    qlonglong mWidth = 0;
     //! Raster size y
-    long mHeight = 0;
+    qlonglong mHeight = 0;
     //! Raster tile size x
     int mTileWidth = 0;
     //! Raster tile size y
```

See:
https://godbolt.org/z/6615EW5q8

**Comment by Joonalai** [comment]
Thank you @elpaso, I will post PR shortly!
