### ISSUE TITLE
Can not import excel File with new version of QGIS

### ISSUE THREAD

**Issue by Bodhi34** [qgis/QGIS#47838]
### What is the bug or the crash?

Hello,

I upgraded from QGIS 3.18 to 3.22.4 and 3.24. Since then, it is impossible to import an excel layer, I have an "invalid data source" message. With QGIS 3.18, i can import this excel file, but i want to work with the new version of QGIS!.
 Do you have a solution ?

![QGIS EXCEL](https://user-images.githubusercontent.com/101341870/158791488-78793d40-bac0-476d-bf8a-a5dde280c284.JPG)

Thanks,

Cyril

### Steps to reproduce the issue

Add Vector Layer

### Versions

Version de QGIS
3.22.3-Białowieża
Révision du code
1628765ec7
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.4.1
Version de Proj
8.2.1
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.0-CAPI-1.16.0
Version de SQLite
3.35.2
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.3
Version de QScintilla2
2.11.5
Version de l'OS
Windows Server 2012 R2 Version 6.3 (Build 9600)

Extensions Python actives
qfieldsync
v3.1.10
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Bodhi34 can you attach a data sample?

**Comment by Bodhi34** [comment]
> @Bodhi34 can you attach a data sample?

**Comment by Bodhi34** [comment]
@Pedro-Murteira 
[DEMANDE DE CLASSEMENT 2022_03_10 TEST.xls](https://github.com/qgis/QGIS/files/8304951/DEMANDE.DE.CLASSEMENT.2022_03_10.TEST.xls)

**Comment by Pedro-Murteira** [comment]
@Bodhi34 I can confirm aswell, can't load the file onto qigs. I don't have a workaround, but we can leave the ticket open in case someone might have a solution.

**Comment by rouault** [comment]
The regression is in the FreeXL library used by GDAL to read .xls files.
I've found a patch and proposed it to upstream per https://groups.google.com/g/spatialite-users/c/ORVQ5VOWEtg

**Comment by rouault** [comment]
I see in https://www.gaia-gis.it/fossil/freexl/info/b7c2aa3747c81419 that my patch has been merged into FreeXL upstream. Creating OSGeo4W ticket https://trac.osgeo.org/osgeo4w/ticket/746 to ask for it to be applied

**Comment by alexbruy** [comment]
Closing. Works fine on Windows, for Linux user GDAL needs to be rebuild with FreeXL 2.0.0 or with patched version of FreeXL.
