### ISSUE TITLE
Explorer crash and misc issues with MSSQL databases

### ISSUE THREAD

**Issue by djes** [qgis/QGIS#47865]
### What is the bug or the crash?

Hi, I encounters several little glitches that are serious enough to avoid the migration to 3.22.4

On QGIS 3.22.4, in an explorer window :

1. I encounter crashes when trying to list detail of layers. Sometimes if works, sometimes it crash. It is particularly sensitive at start as it seems to detect/load everything at the same time when opening a schema. It is not happening on 3.16.4. I don't know how to debug to help.
2. For some layers, I have a red cross when opening fields saying that the table is not found in the schema. I don't understand what's the difference between functional tables and others. It works on 3.16.4
![image](https://user-images.githubusercontent.com/12065874/158973254-0d8e7ada-668a-4e36-853b-3b56be13cf66.png)
3. On a click in the explorer, a random large selection sometimes occurs.

4. Apart of this, when opening a layer with a dependant layer, the dependant layer is correctly loaded automatically but not the associated integrated style. Adding (geom) with the "change vector datasource" plugin corrects the problem and allows to load the integrated style from database. I don't understand what's the purpose of (geom) in the style management... 

Thank you

`Stack Trace

RtlEnterCriticalSection :
EnterStmtCS :
SQLFetchScroll :
QSqlQuery::next :
providerMetadataFactory :
QgsAbstractDatabaseProviderConnection::QueryResult::rows :
providerMetadataFactory :
QgsAbstractDatabaseProviderConnection::table :
QgsFieldsItem::QgsFieldsItem :
providerMetadataFactory :
QgsDataItem::runCreateChildren :
QgsDataItem::runCreateChildren :
QgsDataItem::removeChildItem :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044`

### Steps to reproduce the issue

For most of the bugs, just use an explorer panel with a defined MSSQL connection.

### Versions

QGIS 3.22.4 LTR
MS SQL Server 11.0.7493.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Mia-BCC** [comment]
Hi! Are there any advances on this issue? 
I am getting the same error when opening a mssql layer and the Attribute table does not show all data, only shows one record, with corrupted characters. 

![image](https://user-images.githubusercontent.com/119272323/204178931-c3a4fb78-31c6-43bd-85a0-259fc6dbcfd2.png)

**Comment by NathanW2** [comment]
This is related to https://github.com/qgis/QGIS/issues/50865 which will be fixed in the next package run.
