### ISSUE TITLE
Database Styles Manager dialog opens on wrong screen

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#47868]
### What is the bug or the crash?

When you are using QGIS in a setup with 2 monitors, en you have the Layer Properties open of a Vector layer,  the Database Styles Manager dialog  opens on the other screen. As if the parent of it is not set.
Below you seen the Style button to open it active, and the dialog centered in the properties window as it (I think) should behave:

![Screenshot-20220318113633-829x768](https://user-images.githubusercontent.com/731673/158988105-e3d203f2-e3c8-47e8-9bdd-a3efbf70442e.png)

Not sure if it is possible to call it's parent though.. just seeing this

### Steps to reproduce the issue

- 2 monitors
- start qgis in one screen, open vector layer, open proeprties, click style button
- dialod opens on other screen
- (this is on Linux)

### Versions

QGIS version | 3.25.0-Master | QGIS code revision | 43d2ebbb037
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.10
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
QuickWKT | 3.1
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 3.7.3
plugin_reloader | 0.9.1
meetwagen | 0.3.2
pdok_locatieserver_locator_filter | 0.2.1
RIVM_PluginConfigManager | 1.0.6
DataPlotly | 3.8.1
latlontools | 3.6.1
qgis-safecast-plugin-master | 2.1dev
safecast | 1.0alpha
SectorPlot | 1.1.5
Nuclear-Energy-Plant-Radiations- | 1.8
sagaprovider | 2.12.99
processing | 2.12.99
grassprovider | 2.12.99
jrodos | 2.0.11

</body></html>QGIS version
3.25.0-Master
QGIS code revision
[43d2ebbb037](https://github.com/qgis/QGIS/commit/43d2ebbb037)
Qt version
5.15.2
Python version
3.9.10
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux bookworm/sid

This copy of QGIS writes debugging output.

Active Python plugins
QuickWKT
3.1
nominatim_locator_filter
0.2.4
pdokservicesplugin
3.7.3
plugin_reloader
0.9.1
meetwagen
0.3.2
pdok_locatieserver_locator_filter
0.2.1
RIVM_PluginConfigManager
1.0.6
DataPlotly
3.8.1
latlontools
3.6.1
qgis-safecast-plugin-master
2.1dev
safecast
1.0alpha
SectorPlot
1.1.5
Nuclear-Energy-Plant-Radiations-
1.8
sagaprovider
2.12.99
processing
2.12.99
grassprovider
2.12.99
jrodos
2.0.11

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
I'm unable to reproduce on Windows 10. (QGIS 3.22.4 and 3.24.0.)
