### ISSUE TITLE
crashed when tried to digitize

### ISSUE THREAD

**Issue by sanchitapal1234** [qgis/QGIS#47860]
## User Feedback

i was digitizing and it just crashed.

## Report Details

**Crash ID**: [c0a37a1b3c41c82b414c254ba588c9a192ef69b3](https://github.com/qgis/QGIS/search?q=c0a37a1b3c41c82b414c254ba588c9a192ef69b3&type=Issues)

**Stack Trace**
<pre>
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:14859
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2800
QgisApp::onActiveLayerChanged qgisapp.cpp:717
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
</pre>

**QGIS Info**
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

## User Feedback

i was digitizing and it just crashed.

## Report Details

**Crash ID**: [c0a37a1b3c41c82b414c254ba588c9a192ef69b3](https://github.com/qgis/QGIS/search?q=c0a37a1b3c41c82b414c254ba588c9a192ef69b3&type=Issues)

**Stack Trace**
<pre>
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions qgisapp.cpp:14859
QMetaObject::activate :
QgisApp::activeLayerChanged moc_qgisapp.cpp:2800
QgisApp::onActiveLayerChanged qgisapp.cpp:717
QMetaObject::activate :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QTreeView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
</pre>

**QGIS Info**
QGIS Version: 3.18.2-Z�rich
QGIS code revision: 515138c171
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Versions

3.18.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

its crashed when tried to digitize

**Comment by nicogodet** [comment]
3.18 is EOL
Retry on 3.22 or 3.24 and with a new profile

**Comment by benclinch2008** [comment]
I have had multiple crashes too when trying to digitise (using topology rules).

tried under new profile.  same issue.


Crash ID: [33c15cfb2812e57e5008092be4cb219af2447185](https://github.com/qgis/QGIS/search?q=33c15cfb2812e57e5008092be4cb219af2447185&type=Issues)


Stack Trace


QgsFixAttributeDialog::reject :
QModelIndex::data :
QgsFixAttributeDialog::reject :
QgsFixAttributeDialog::reject :
QObject::qt_static_metacall :
QAbstractItemModel::endRemoveRows :
QgsFixAttributeDialog::reject :
QObject::qt_static_metacall :
QgsSimplifyUserInputWidget::toleranceUnitsChanged :
QgsFixAttributeDialog::reject :
QgsFixAttributeDialog::reject :
QObject::qt_static_metacall :
QgsVectorLayer::beforeCommitChanges :
QgsVectorLayer::commitChanges :
QgisApp::toggleEditingVectorLayer :
QgisApp::toggleEditing :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043
