### ISSUE TITLE
Ability to Manage User Profiles from within QGIS

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#47877]
### Feature description

Currently you are only able to add new profile but not delete, workaround was provided by @SrNetoChan to :

Click the open active profile folder. Move one folder up. Delete the desired profile folder. Done.

Was just wondering if the process could be done within QGIS which would make it easier for users

### Additional context

Current Window

![image](https://user-images.githubusercontent.com/4627073/159048662-6058070e-acea-4a60-bfd6-ccff843fc2af.png)

**Comment by agiudiceandrea** [comment]
The Profile Manager plugin https://plugins.qgis.org/plugins/profile-manager/ could be of some help.
See https://wheregroup.com/blog/details/verwaltung-von-qgis-profilen-mit-dem-plugin-profil-manager/.

**Comment by DelazJ** [comment]
Duplicate of #38243

**Comment by antoniolocandro** [comment]
@DelazJ ah yest it is a duplicate, could you merge and close?
