### ISSUE TITLE
C++ API website doesn't build

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#47886]
### What is the issue about the documentation?

The site https://api.qgis.org/api/ last build is
> Generated on Mon Mar 14 2022 00:42:30 for QGIS API Documentation by doxygen 1.9.1

**Comment by jef-n** [comment]
Part of the nightlies - used to install unstable's qgis-api-doc - but unstable's build has been failed last time around.  Extracts now the latest qgis-api-doc package regardlest of the distribution (will usually still be unstable as that is built last).

**Comment by DelazJ** [comment]
https://api.qgis.org/api/3.24 doesn't work @jef-n
