### ISSUE TITLE
Raster histogram not updating from user-defined min/max

### ISSUE THREAD

**Issue by lgouzin** [qgis/QGIS#47889]
### What is the bug or the crash?

Raster histogram doesn't update after new min max value have been entered. Prefs/Actions have 'Zoom to min/max' and 'Update style to min/max' enabled, but for some reason, in some cases, the histogram doesn't update itself automatically once values have been entered.
Sometime pressing TAB between selecting the min and the max, helps, but sometimes it doesn't. Starting a new project and reloading the same raster does make the histogram work.  

Issue described https://gis.stackexchange.com/questions/411700/how-to-manually-adjust-qgis-raster-histogram-x-values 

### Steps to reproduce the issue

Not straightforward to reproduce. It seem to affect raster files loaded with others file in a project. Raster files loaded on their own seem to behave fine. 

### Versions

QGIS version
3.22.0-Białowieża
QGIS code revision
d9022691f1
Qt version
5.15.2
Python version
3.9.5
Compiled against GDAL/OGR
3.3.2
Running against GDAL/OGR
3.3.3
PROJ version
8.1.1
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
nominatim
1.4.1
ntv2_transformations
0.20
OSMDownloader
1.0.3
QuickOSM
2.0.0
S3_CIP_Geodownload_dock_version
0.8
Serval
3.10.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (a52133202070a747277d37ed17c0181372cc6772)

**Comment by lgouzin** [comment]
The histogram does seem to work (QGIS 3.32), but the user has to set the raster symbology to user defined min/max beforehand. When viewing a raster using hillshade for example, the histogram is not responsive to the histogram panel min/max line_edit boxes.
