### ISSUE TITLE
Python Stack Trace - Windows fatal exception: access violation

### ISSUE THREAD

**Issue by mlsthmpsn** [qgis/QGIS#47888]
## User Feedback

Add a single feature class to the map, with only one feature in the shapefile. In properties, I click the field calculator button and the fatal error occurs.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002248 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Steps to reproduce the issue

1. Open a new project
2. Add a single shapefile layer, with one feature in it
3. Right-click on the shapefile > Properties > Fields
4. Select field I'm trying to calculate geometry for
5. Click the Field Calculator button.
6. Fatal crash

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code revision | 5709b824
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins
LAStools | 1.4
latlontools | 3.6.3
mgrs | 3.0.1
open_lidar_tools | 2.1
postgis_geoprocessing | 0.9
qfieldsync | v4.0.0
quick_map_services | 0.19.29
TerrainShading | 0.9.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.1-Tisler
QGIS code revision
[5709b824](https://github.com/qgis/QGIS/commit/5709b824)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
LAStools
1.4
latlontools
3.6.3
mgrs
3.0.1
open_lidar_tools
2.1
postgis_geoprocessing
0.9
qfieldsync
v4.0.0
quick_map_services
0.19.29
TerrainShading
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The issue resolves with the new test profile

**Comment by nicogodet** [comment]
Really try with a new profile (no plugins installed)

**Comment by VulcanTrekkie45** [comment]
I'm having the same issue with manipulating OSM data. I can't go more than about 10 minutes without a crash on some projects. I did notice that the project I'm working on is a suspended UWP in the task manager. Could that be part of it?

**Comment by nicogodet** [comment]
@VulcanTrekkie45 Same, have you tried with a fresh profile ?
Preference -> User profiles -> New profile

**Comment by VulcanTrekkie45** [comment]
> @VulcanTrekkie45 Same, have you tried with a fresh profile ?
> Preference -> User profiles -> New profile

I haven’t because many of my workflows rely on access to QuickOSM, so it kinda feels like treating a paper cut by cutting off the arm

**Comment by alexbruy** [comment]
@mlsthmpsn add plugins one by one and test.

**Comment by stev-0** [comment]
> I haven’t because many of my workflows rely on access to QuickOSM, so it kinda feels like treating a paper cut by cutting off the arm

Not really because if the fault lies with QuickOSM (which it sounds like it might) then you are reporting the bug in the wrong place - Quick OSM should have it's own issue tracker.

**Comment by nicogodet** [comment]
@ccampbell9 Are you able to provide steps to reproduce this issue ?
And sample data ?

If so, can you open a separate ticket ?
