### ISSUE TITLE
When using Temporal Controller, the 'Select All Features' Tool also selects non visible features 

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#47893]
### What is the bug or the crash?

Using the Temporal Controller, I was searching for a way to select the features during 'current time frame'.

It earlier appeared to me that:
- when you use selection tools (like rectangle select), you can only select the visible features (GOOD!!!)
- but when you use the option 'Select All Features':
![Screenshot-20220321130117-343x171](https://user-images.githubusercontent.com/731673/159257117-3cd72ec7-8cd6-4cc7-a9d9-186428b74ec9.png)
ALL features are selected, visible and non visible..

I'm not sure if that is intended or not, reading this commit:
https://github.com/qgis/QGIS/commit/645b583cc996a368c94927b12c390ea95fbda9d2
we wanted to NOT select invisible features (which are hidden by the Temporal Controller).

So eager to know: is the full selection intended or not?

If not, this is an issue
If it is as it should work, then I'm eager to know how to select (programmatically) only the features which are currently visible (by using the Temporal Controller), other then using a rectangle...

### Steps to reproduce the issue

To test/check:

Open this dataset (after unzipping), it is Temporal Controller enabled, and it has  a default style:

[temporal_selection.zip](https://github.com/qgis/QGIS/files/8315338/temporal_selection.zip)

When you enabled the Temporal Controller, you will see 6 features (if not, you will have 138 features (over that 6 places))

![Screenshot-20220321131651-832x381](https://user-images.githubusercontent.com/731673/159259187-6812a88b-4bf0-4049-be2e-72e094605af0.png)

When using the Rectangle Select Tool and selecting over that 6 points, you will see (in status bar): 6 features selected:

![Screenshot-20220321132040-706x380](https://user-images.githubusercontent.com/731673/159259820-51175e23-a534-4b83-9da9-485e0af9fc3c.png)

But using the 'Select All' 138 features are selected (132 of them non visible):

![Screenshot-20220321132149-803x427](https://user-images.githubusercontent.com/731673/159259995-9bcb854e-ef51-474d-9d16-a36c52df5df8.png)

We can discuss about what 'Select All' means:
- Select All features (not hidden by expressions or temporal controller) 
- Really Select ALL (which is current behaviour)

It is just that now it looks like our selection tools do not behave consequent: one is taking the invisible ones into account, other does not.

Any input appreciated...

### Versions

QGIS version | 3.25.0-Master | QGIS code revision | 43d2ebbb037
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.10
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid

</body></html>QGIS version
3.25.0-Master
QGIS code revision
[43d2ebbb037](https://github.com/qgis/QGIS/commit/43d2ebbb037)
Qt version
5.15.2
Python version
3.9.10
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux bookworm/sid

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rduivenvoorde** [comment]
Another observation:

When using the python interface to select features in that layer using a rectangle (being the extent of the data)... it behaves like the Select All tool, that is it does not take the Temporal Controller hidden features in account: it selects ALL.

To check: load the data above, make sure you select that layer and then in python console:

```
iface.mapCanvas().currentLayer().selectByRect(iface.mapCanvas().currentLayer().extent())
```

You will see that ALL features will be selected (or at least that is what the status line tells us):

![Screenshot-20220321142524-814x145](https://user-images.githubusercontent.com/731673/159270300-c25e753e-8cfe-415a-b1c7-e1cb9284e9d7.png)

**Comment by Pedro-Murteira** [comment]
@rduivenvoorde I've removed feature request by accident, should we leave it as you labeled? Bug + feature request?

**Comment by nyalldawson** [comment]
I don't think this particular one is a bug -- the Select All ALWAYS selects ALL features, regardless of whether they are visible or not. The same applies to any features which are hidden because of missing categories/classes, or those filtered out by scale dependent rule based renderer rules. They'll still get selected when you pick "Select ALL".

I think this is instead a feature request for something like a "select all visible features" action. (But that wording somewhat imples that features which are outside of the canvas view won't be selected either!)

**Comment by rduivenvoorde** [comment]
@nyalldawson I agree with you about the 'Select All'.
But (and I know that this is created later), the fact that if you do a 'selectByRect' (by drawing a rect in QGIS itslef) vs the pyqgis 'selectByRect' both work differently (first one only selecting the temporal visible, the second not taking the Temporal Controller (TC) in account) is not Ok, I think ?

Also agree with a 'select current/only visible features' feature as request. That would be in line with the Ctrl-F6 (Show attributes of visible features).
Though I'm not so aware of an actual use case for it (other then for use with the TC)...

So 'the model' is:
- we are FILTERING data (coming directly from provider) via 'Filtering'
- then we HIDE/not show  (potentially filtered) data using styling/classes...
then there is the Temporal Controller, is in? The second one... because data is there we are just not rendering/showing it..

So this feature request is about the selecting of available but 'hidden' features.

Sorry, just thinking out loud here, I think clear concepts are needed for the complexity QGIS is working with :-)

Thanks for the pseudo code snippet in the mailing list, will try it now.

**Comment by nyalldawson** [comment]
@rduivenvoorde 
> But (and I know that this is created later), the fact that if you do a 'selectByRect' (by drawing a rect in QGIS itself) vs the pyqgis 'selectByRect' both work differently (first one only selecting the temporal visible, the second not taking the Temporal Controller (TC) in account) is not Ok, I think ?

I don't see a problem there. The PyQgis method does exactly what the documentation for that method says: "Selects features found within the search rectangle (in layer's coordinates)" -- there's no mention there of filtering those features depending on renderer settings or map canvas or scale or temporal ranges. (For reference, this method **isn't** actually used in QGIS itself -- it's provided as a convenience method for plugin authors/scripts only).

> OR another option: add a checkbox 'Select Only Visibles' (which would work on all select tools)??

This is probably the most user friendly/straightforward approach

**Comment by rduivenvoorde** [comment]
Ok, you are right, but it's not what I expected...

I'll close this one, and create a new one 'Select Only Visibles' Feature Request later
