### ISSUE TITLE
Software freezes while moving vertices

### ISSUE THREAD

**Issue by johnnycosmos** [qgis/QGIS#47891]
### What is the bug or the crash?

Software freezes while editing vertices. Software freezes for couple of minutes while manually moving vertices using the Vertex tool. It freezes after the vertex is moved to desired position. While it is frozen Windows task manager reports software as Not responding. After it unfreezes, the vertex is in the position where it was placed.

### Steps to reproduce the issue

1. Click on 'Toggle editing'
2. Click on 'Vertex tool'
3. Go to vertex
4. Click and hold left mouse button on a vertex
5. Move vertex to a desired position
6. Software freezes

### Versions

3.22.5-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@johnnycosmos Hello, I'm not being able to reproduce this. Can you also reproduce with a new profile?

**Comment by johnnycosmos** [comment]
Hello,
I've tried using a fresh profile - the problem stays the same.
My technical data:PC - Intel i7 / 16 GB RAMWindows 11QGIS 3.22.5 LTRInternet connection - 200 Mbps down / 50 Mbps up
The dataset I'm working with is quite big, it is a PostgreSQL layer with 34000 polygon features on a remote server.
It is worth mentioning, that prior to update I've been working on a 3.16.16 LTR version and there were no software freezes while moving vertices. The problem appeared only after the update to 3.22.5 LTR. Now I've downgraded to 3.16.16 LTR and there is no problem moving vertices.
    On Monday, 21 March 2022, 15:58:15 EET, Richard Duivenvoorde ***@***.***> wrote:  
 
 


Often the issue is here, either a rogue plugin or a huge dataset. By using a new profile you factor out a plugin.
IF still having troubles when having a fresh profile, please report more info about your data and what you are exactly doing (OS, QGIS version etc etc)
