### ISSUE TITLE
QGIS (MSI installer) Crashes in map composer when using Legend

### ISSUE THREAD

**Issue by patrickazevedo** [qgis/QGIS#47896]
### What is the bug or the crash?

All versions of Qgis with MSI Installer have high power consumption and slow map composite when activating Legend with the option to "show only linked map items".

QGIS takes time to respond to commands to zoom, move, edit texts, insert new items, among other procedures. every problem is solved when you detain the Legend item or if you hide it.

In the attached images I show a printscreen of the High Consumption of Qgis and also a Gif, where I show the behavior when using Qgis, when it is activated, with the option "show only linked map items" and how it behaves when hiding the legend

All these procedures were performed with a new Profile.
 
![Screenshot_1](https://user-images.githubusercontent.com/58080370/159288378-9ede8d44-4c88-48da-98d6-05e52024fce0.jpg)
![QGIS_3 22 5_MSI_Trava_com_Legenda_Lincada](https://user-images.githubusercontent.com/58080370/159288422-c5e5e7f2-b61f-4451-ac2c-8d6a89a88bba.gif)
.

### Steps to reproduce the issue

1 - I added the layers with municipal and state limits of Brazil.
2 - I created a vector layer (polygon) of the study area.
3 - I added MDS layers from the study area.
4 - Extract contours (contours) within the study area.
5 - Added a WMS layer from Open Street Map.
6 - Open the map composer.
7 - I created the Main Map item with coordinate grids.
8 - I activated the atlas linked to the study area.
9 - I entered the north, SRC, Graphic and Numerical Scale.
10 - Insert the caption
11 - In subtitles, I activated the option
"show only linked map items"
12 - And then the Qgis becomes sluggish and consuming a lot of energy.
13 - To regain control over the map composer, click on hide legend under Items. That way, I can create, modify, move and edit the other items in real time, with no delay in the response.

### Versions

Versão do QGIS
3.22.5-Białowieża
Código da versão do QGIS
c2723178
Qt version
5.15.2
Versão do Python
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
Versão PDAL
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
Versão QScintilla2
2.11.5
OS version
Windows 10 Version 2004

Active Python plugins
autoSaver
2.6
AzimuthDistanceCalculator
2.0.2
bulkvectorexportwithstyle
0.6
CalculateGeometry
0.6.4
cbers4a
0.3.1
changeDataSource
3.1
DEMto3D
3.4
inde
1.1
kml_style_importer
0.9.1
latlontools
3.6.3
lftools
1.6.1
OpenTopography-DEM-Downloader
1.0
Qgis2threejs
2.6
QuickOSM
2.0.1
quicksaveqml
0.1.5
quick_map_services
0.19.28
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

- The problem only occurs in QGIS versions that were installed with MSI as QGIS-OSGeo4W-3.16.16-1.msi; QGIS-OSGeo4W-3.24.1-1.msi and QGIS-OSGeo4W-3.22.5-1.msi. In version QGIS-OSGeo4W-3.16.16-1-Setup-x86_64.exe this problem does not occur.
- The crash only compromises Qgis. Other software and operating system respond normally.
- These procedures were tested on 3 computers with WINDOWS 10 Pro 64 and video cards. (According to the attached pintscreen)

![Screenshot_2](https://user-images.githubusercontent.com/58080370/159292160-e5c807fc-9393-4a38-8bdd-a9ea13d64b8c.jpg)
![Screenshot_3](https://user-images.githubusercontent.com/58080370/159292167-4ceb848d-fe6f-4f86-8861-c8cd65ba4131.jpg)
![Screenshot_4](https://user-images.githubusercontent.com/58080370/159292170-9d7f21f5-d68f-4a7a-9790-c72470c3b58e.jpg)
![Screenshot_5](https://user-images.githubusercontent.com/58080370/159292173-06ffeef4-647b-4e0b-88e9-57c21672f90d.jpg)
![Screenshot_6](https://user-images.githubusercontent.com/58080370/159292175-628bad42-7d89-46d3-82b4-32ab4bb73969.jpg)

**Comment by alexbruy** [comment]
Can't reproduce using latest MSI for 3.32 and my own data. Please try with clean profile and if issue persist attach sample project.
