### ISSUE TITLE
QGIS freezes for minutes when updated SpatiaLite SQL Layer

### ISSUE THREAD

**Issue by sigeal** [qgis/QGIS#47906]
### What is the bug or the crash?

QGIS freezes with hourglass for about 2 minutes when I click on close button of Update SQL Layer dialog, even if I didn't modify the query.
If I click on Execute button, I get this error : "an error occurred while opening GPKG dbname=..."
This happens with a big database file (600 Mb), only with with query returning hundreds of rows.

### Steps to reproduce the issue

Add SQL Layer from DB Manager (simple query like `select * from table`)
Right click on the layer then Update SQL Layer
Click Close button
QGIS freezes with hourglass for about 2 minutes...

### Versions

QGIS 3.22.5/3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It's difficult to provide example data, as it happens with big databases (600 Mb - french cadastre) with many tables (~150).

**Comment by sigeal** [comment]
Testing again with QGIS 3.16.16, I don't have any problem at all with old behaviour : DB Manager opened when I click on Update SQL Layer.
So this sounds clearly like a regression linked to the new "Update SQL Layer" dialog/behaviour.

**Comment by elpaso** [comment]
I cannot reproduce this issue, in all my tests with huge layers they are damn slow to load in the canvas but the SQL Query widget remains fast and responsive.

**Comment by sigeal** [comment]
I suspect it has to do with some kind of Sqlite DB locking, as I randomly get this error message when I click execute button :
> An error occured while opening GPKG dbname='mydb.sqlite' (translated from french)

I can send you a link by private message so you can download the database, but I can't make the link public because the database contains private data.

**Comment by elpaso** [comment]
If you send me the DB and a screen-recording showing exactly how to reproduce the problem step-by-step I will possibly have a look.  My address is apasotti at gmail dot com

Aren't you by chance trying to change the SQL Query of the layer while the layer is still loading in the canvas ?

As I mentioned, if I test with a huge GPKG layer, it takes up to 10 minutes to fully load in the canvas, this has nothing to do with the SQL Query widget operations.

**Comment by sigeal** [comment]
Link sent.
I tested further, trying to reduce the db size : no problem with a database containing only the table used for the query, but the problem occurs with the whole db (about 150 tables).

**Comment by sigeal** [comment]
Thanks, I'll give it a try as soon as it will be merged and released.

**Comment by sigeal** [comment]
Obviously the fix hasn't been backported in 3.22, neither in 3.24. Any reason ?
It is said to be "added to the [3.26.0] milestone", which is quite far ahead...

**Comment by sigeal** [comment]
Still there in freshly released 3.22.7 and 3.24.3 :-(

**Comment by sigeal** [comment]
Corrected in 3.26.0 :-) but unfortunately not in LTR 3.22.8 :-(
