### ISSUE TITLE
Moving Label

### ISSUE THREAD

**Issue by ronaldskewes** [qgis/QGIS#47917]
### What is the bug or the crash?

when I try to move the labels I receive the Following message:

Move Label: The label X/Y columns “auxiliary_storage_labeling_positionx” and “auxiliary_storage_labeling_positiony” do not exist in the layer

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/9868959/159547318-7d4548da-ed48-43c6-b98e-0eb5510d1bd2.png)

### Versions

![image](https://user-images.githubusercontent.com/9868959/159547426-cfef87c1-6136-42c6-ae32-82c4cf9d81e8.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@ronaldskewes Could you attach a data sample?

**Comment by ronaldskewes** [comment]
Yes

**Comment by Pedro-Murteira** [comment]
> Yes

I think you forgot to attach the data in your comment.

**Comment by ronaldskewes** [comment]
Sorry, for forgetting the data

**Comment by Pedro-Murteira** [comment]
@ronaldskewes no problem, although it would be better if you could attach the entire project with all the data.

**Comment by ronaldskewes** [comment]
[Provincias.zip](https://github.com/qgis/QGIS/files/8342546/Provincias.zip)

**Comment by djohandupreez** [comment]
I have the same problem , getting the message  The label X/Y columns "auxiliary_storage_labeling_positionsx" and "auxiliary_storage_labeling_positionyx"  do not exist in the layer. Does anyone have a solution to this?

**Comment by Isaacson33** [comment]
Yep, same problem here too. Does anyone know what the fix was because this was closed in March, but the problem clearly want's fixed in 3.22 or 3.24?

**Comment by dacalizaya** [comment]
A

**Comment by dacalizaya** [comment]
I HAD THAT PROBLEM AND I DID THIS FOR BOTH...
![AEA](https://user-images.githubusercontent.com/112834911/200994438-dadc72fa-fc5b-49df-8807-376a06c70f28.jpg)

**Comment by dacalizaya** [comment]
I HAD THAT PROBLEM AND I DID THIS...
![AEA](https://user-images.githubusercontent.com/112834911/200994680-f2841e62-b036-4362-9bd7-d04f9782826b.jpg)

**Comment by igorkosten** [comment]
https://github.com/qgis/qgis/issues/47917

**Comment by Serrynne** [comment]
Thanks so much! This solved the error.

> I HAD THAT PROBLEM AND I DID THIS... THEN YOU CAN MOVE THE LABEL ![AEA](https://user-images.githubusercontent.com/112834911/200994680-f2841e62-b036-4362-9bd7-d04f9782826b.jpg)
