### ISSUE TITLE
Adding Join while attribute table is open causes Qgis to hang

### ISSUE THREAD

**Issue by Promethean-Roil** [qgis/QGIS#47921]
### What is the bug or the crash?

When you join to layers (via layer properties) if the attribute table of the destination layer is open (in the background, minimised etc) qgis will hang indefinitely.

### Steps to reproduce the issue

1. Load any two layers; Let's say layer A is a point layer with an "ID" attribute (unique) and layer B is a CSV (with additional fields)
2. Open the attribute table of layer A.
3. On layer A, open "Layer Properties" > "Joins"
4. "Add a new join" and set "Join Layer" to layer B
5. Hit ok, Qgis becomes unresponsive.

### Versions

QGIS version
3.24.1-Tisler
QGIS code revision
5709b824
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.18
go2streetview
8.1
QuickOSM
2.0.0
quick_map_services
0.19.19
realcentroid
1.0.3
searchlayers
3.0.2
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Works fine if the attribute table is closed. (Annoyingly layer properties/add join windows hold the focus so you can't easily close any attribute table you may have left open).
Have had this occur many times and doesn't appear to be restricted to any particular layer formats (I'm typically using shp, csv and/or geojson files).

**Comment by pigreco** [comment]
I confirm on QGIS 3.22.5, 3.24.1 and master

## OSGeo4W64 v2 Win 10 Pro

**Comment by decheu** [comment]
same for me on QGIS 3.22.4 OSGeo4W install in Win10
also with clean default user profile
had this already several times in the past (I guess for years), never knew what caused the problem - thanks for reporting @Promethean-Roil !

**Comment by agiudiceandrea** [comment]
> * in QGIS 3.16.13 OK, no bug
> * in QGIS 3.16.14 BUG!!!    <--------------------------------------------------------------

It seems there are only 10 commits between 3.16.13 and 3.16.14 https://github.com/qgis/QGIS/compare/final-3_16_13%E2%80%A6final-3_16_14 and no one, at first sight, seems related to this bug.

Is the Qt version (and other libraries) the same of both your installation of QGIS 3.16.13 and QGIS 3.16.14?

**Comment by pigreco** [comment]
@agiudiceandrea 

## in QGIS.3.20.3 Odense NO BUG !!!

![image](https://user-images.githubusercontent.com/7631137/163261756-ab3558c2-43a3-43f7-996e-bfbb43483a37.png)

**Comment by ludovico85** [comment]
> > * in QGIS 3.16.13 OK, no bug
> > * in QGIS 3.16.14 BUG!!!    <--------------------------------------------------------------
> 
> It seems there are only 10 commits between 3.16.13 and 3.16.14 https://github.com/qgis/QGIS/compare/final-3_16_13%E2%80%A6final-3_16_14 and no one, at first sight, seems related to this bug.
> 
> Is the Qt version (and other libraries) the same of both your installation of QGIS 3.16.13 and QGIS 3.16.14?

I've made a test with 3.16.3 and 3.16.4.
QGIS 3.16.3 no bug

![3 16 13](https://user-images.githubusercontent.com/24815399/163347367-a59a0bee-6d43-404b-bd06-621fce6baf8e.JPG)

QGIS 3.16.4 with the bug

![3 16 14](https://user-images.githubusercontent.com/24815399/163347391-22e8e42e-9c98-45b8-9cdb-72402452ddbe.JPG)

@pigreco

**Comment by rduivenvoorde** [comment]
I'd start to say that I think there is a lot of loud noise about this issue, both on Twitter, here and on the Mailing list. Why the drama? Is there an old issue (plz link to), or is this the first time?
About the "it's already open for 21 days": it's not always that easy to fix a seamingly easy to fix bug...

So please stay gentle and polite. Create a proper issue with some dataset here, and eventually ask for help on the mailing list?

But... I can confirm this on my Debian, version 3.25-master

![gnome-shell-screenshot-2vt63f](https://user-images.githubusercontent.com/731673/163440707-a62f522c-2ed8-4fe0-af4f-004476b20477.png)

Some small dataset to test, 12 records of shp and 12 lines of csv: join on provcode: 

[data.zip](https://github.com/qgis/QGIS/files/8491098/data.zip)

QGIS hangs at:
```
src/gui/symbology/qgsrendererpropertiesdialog.cpp:63 : (_initRenderer) [0ms] Set for embeddedSymbol
src/gui/attributetable/qgsattributetablemodel.cpp:177 : (removeRows) [17556ms] remove 12 rows at 0 (rows 12, ids 12)
```

**Comment by rduivenvoorde** [comment]
Duh, thank @jef :-)
