### ISSUE TITLE
Sync 2D and 3D navigation does not respect 3D rotation

### ISSUE THREAD

**Issue by ptitjano** [qgis/QGIS#47935]
### What is the bug or the crash?

Once sync is activated between the 2D view and a 3D view, zooming in from the 2D view resets the rotation in the 3D view. 

### Steps to reproduce the issue

1. Display some data
2. Launch a 3D view
3. Activate both sync from the 3D view (`2D Map view follows 3D Camera` and `3D Camera Follows 2D Map View`)
4. Apply a rotation in the 3D view
5. Go to the 2D view and zoom in.
6. Go back to the 3D view: rotation is lost

### Versions

QGIS commit https://github.com/qgis/QGIS/commit/37abd1b5c4

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is not a bug but rather is intentional. If you don't reset the view's rotation then you haven't really synced the views, ie the views do not show the same thing!

**Comment by alexbruy** [comment]
Should we close this if this is intentional behaviour?
