### ISSUE TITLE
Measuring tool immediately crashes QGIS on opening. 

### ISSUE THREAD

**Issue by 7Fitzy8** [qgis/QGIS#47939]
### What is the bug or the crash?

On opening the measuring tool QGIS Version 3.22.5 immediately crashes. I have a small number of projected layers in the project EPSG 28355 and base layers sourced from rest services in CRS EPSG 3857.  My project CRS is set to EPSG 28355 and the default layer CRS is EPSG 4326. 

I am aiming to estimate slope between contours using the measuring tool which then causes the crash, however I would like to use the measuring tool for other purposes but it simply will not work.

### Steps to reproduce the issue

Click on measuring tool icon, attempt to measure distance using either ellipsoidal or cartesion option and system crashes.  

### Versions

The latest LTR release 3.22.5, however this issue has been ongoing in previous versions.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@7Fitzy8 Hello, can you attach the project and data being used?

**Comment by 7Fitzy8** [comment]
Hi,

Thanks for getting in touch.

Please see my study area attached and below the feature services layers I am using.

Name
Wetland points
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/5
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/5'
Provider
arcgisfeatureserver


Name
Wetland lines
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/10
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/10'
Provider
arcgisfeatureserver


Name
Wetland areas
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/15
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/15'
Provider
arcgisfeatureserver

**Comment by 7Fitzy8** [comment]
Apologies, I forgot to attach the project.

Here it is.

From: Anton Fitzgerald
Sent: Thursday, 24 March 2022 11:33 PM
To: qgis/QGIS ***@***.***>; qgis/QGIS ***@***.***>
Cc: Mention ***@***.***>
Subject: RE: [qgis/QGIS] Measuring tool immediately crashes QGIS on opening. (Issue #47939)

Hi,

Thanks for getting in touch.

Please see my study area attached and below the feature services layers I am using.

Name
Wetland points
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/5
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/5'
Provider
arcgisfeatureserver


Name
Wetland lines
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/10
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/10'
Provider
arcgisfeatureserver


Name
Wetland areas
URL
https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/15
Source
crs='EPSG:3857' url='https://gisservices.information.qld.gov.au/arcgis/rest/services/Biota/Wetlands/MapServer/15'
Provider
arcgisfeatureserver

**Comment by Pedro-Murteira** [comment]
@7Fitzy8 I can't acess the project you mentioned, perhaps it would be better if you could just upload the project here.

**Comment by 7Fitzy8** [comment]
I have attached the project and shapefile here. Thanks.

[Central_QLD.zip](https://github.com/qgis/QGIS/files/8345821/Central_QLD.zip)

**Comment by 7Fitzy8** [comment]
Apologies, I didn't realise I needed to submit something. The last correspondence asked that I attach the Project and data being used, which I did as a Zip file titled Central_QLD.zip. If there is anything else I can provide, I would be happy to.

Thanks.

**Comment by 7Fitzy8** [comment]
It doesn't appear that this issue can be resolved and should probably be closed. Thanks.
