### ISSUE TITLE
Multi-edit overwrites all fields of selected features when opened from attributes table

### ISSUE THREAD

**Issue by domhinch** [qgis/QGIS#47936]
### What is the bug or the crash?

Using the multi-edit tool ![](https://raw.githubusercontent.com/qgis/QGIS/master/images/themes/default/mActionMultiEdit.svg) from the attributes table causes data to be overwritten.

Tested on versions 3.22.4 and 3.22.5

Multi-edit behaves as expected when accessed from the digitising toolbar.

### Steps to reproduce the issue

***Tested with shapefiles, geopackage & postgis***

## Reproduction
1. Toggle any layer into editing mode.
2. Open attribute table for layer.
3. Select a few features.
![image](https://user-images.githubusercontent.com/63502520/159779692-edbb13f1-5844-4870-9a35-c7aa38eaa6cf.png)
5. Toggle into multi-edit mode.
![image](https://user-images.githubusercontent.com/63502520/159780049-b9a2e90a-e477-4109-8681-632606038fcd.png)
As you can see it states 'Attribute changes for multiple features applied' before user has made any changes to the field/s.
6. Switching back to table view shows data across multiple fields has been changed unexpectedly.
![image](https://user-images.githubusercontent.com/63502520/159780772-ebb7ec51-849a-46e7-a823-b711618c3e68.png)
7. Commiting layer edits at this stage results in data corruption if not noticed.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[ce8e65e9](https://github.com/qgis/QGIS/commit/ce8e65e9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Possibly related to
#46306
#47485
#47223

**Comment by MrChebur** [comment]
Just now trying to change one value for some records overwrote the values of ALL fields. As a result, I lost all my data in the database because of this problem.

**Comment by Jeroen-GroeneBij** [comment]
Hi,
Just tested this issue in 3.26.2 and I can not reproduce the bug. I tested on a Windows machine using a new profile on a gpkg and a shp-file.
Maybe it got fixed?

**Comment by gis-nis-ibw** [comment]
Hi,
The current version of QGIS is 3.28.9.  tested with gpkg

multiple edit mode under "open attribut table" dont Work correctly, it changes all the values not only the one which was edited.

multiple edit mode under "digitize toolbar" which is available when data from a layer is selected in the map, works.

does somebody share this oppinion?

**Comment by MrChebur** [comment]
@gis-nis-ibw 
Here's a screencast - how to use this tool:
![qgis-bin_gUemNRydpY](https://github.com/qgis/QGIS/assets/20655102/995813e0-1e5a-4271-80c5-237953895589)

**Comment by MrChebur** [comment]
@gis-nis-ibw 
Upgrade QGIS to the latest version and test again.

**Comment by EVWK** [comment]
Hi, I'm not sure why this has been closed, the problem is persisting in the latest version of Q.

**Comment by beb190** [comment]
Hi, I have
 tests with the latest version and it’s the same problem. When in form mode the multiple update is not stable and induces input errors... If you could do something, that would be great! This is a feature that saves a lot of typing time. Thank you in advance.

**Comment by EVWK** [comment]
This is the same as this: https://github.com/qgis/QGIS/issues/58431#issue-2473543504

**Comment by agiudiceandrea** [comment]
@elpaso, should this issue report be reopened?

**Comment by beb190** [comment]
Hi Yes It's good for best user experience...
The problem is also present when you have a linked drop-down list set in the sheet. Multiple editing creates inconsistencies.
