### ISSUE TITLE
Wrong Max Zoom on vector tiles in 3.24

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#47933]
### What is the bug or the crash?

I face a regression using vector tiles.
OK on 3.22.4 (on the left)
NOK on 3.24.1 (on the right)

![image](https://user-images.githubusercontent.com/39594821/159725704-037be029-f65f-4528-9b55-c356a47658fa.png)
![image](https://user-images.githubusercontent.com/39594821/159725895-073c524b-e9ee-4a91-a6f7-ac7f2b3f90fe.png)

### Steps to reproduce the issue

1. add this connection [tuiles-vectorielles_gh.zip](https://github.com/qgis/QGIS/files/8333967/tuiles-vectorielles_gh.zip)
2. Add the layer to QGIS
3. Zoom in France
 

### Versions

3.24.1 OSGeo4W 
3.22.4 OSGeo4W

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
It's hard to test this -- I can't tell where there's supposed to be data for that layer. Can you provide a sample project please?

**Comment by nicogodet** [comment]
@nyalldawson I will test your fix.

This is hard to find data because of the other issue related to symbology (#47934).

**Comment by nicogodet** [comment]
Sample project
[GH_47933_47934.zip](https://github.com/qgis/QGIS/files/8339374/GH_47933_47934.zip)
