### ISSUE TITLE
QGIS crashes when trying to edit a fixed table object

### ISSUE THREAD

**Issue by evelina-bw** [qgis/QGIS#47944]
### What is the bug or the crash?

We are using QGIS version 3.12.0-București. I have created a fixed table feature on my layout, and populated with required row and column details.  When I select "Edit Table" from the Main Properties section of the Table Item Properties, QGIS crashes.
Has anyone reported this?  Is there a work-around?

### Steps to reproduce the issue

Open A3 Landscape Layout.
Select ADD FIXED TABLE option from toolbars
Click on layout to select location.
Type in content for rows/columns
Select table and adjust properties for font, grid width, frames, background etc.
Noticed error in table, click on Main Properties > Edit Table...
QGIS crashes

### Versions

QGIS version
3.12.0-București
QGIS code revision
cd141490ec
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.1
Running against PROJ
Rel. 6.3.1, February 10th, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.12 is way to old and not supported anymore
Upgrade to 3.22.5 or 3.24.1

**Comment by alexbruy** [comment]
No crash with the latest master (a52133202070a747277d37ed17c0181372cc6772) and 3.32.

**Comment by evelina-bw** [comment]
upgraded version and doesn't crash anymore
