### ISSUE TITLE
Changing scale of map in print layout makes wms aireal dissapear.

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#47947]
### What is the bug or the crash?

a bug

### Steps to reproduce the issue

use a vector layer, add google satelite.

add print layout and map view. change scale on map.

### Versions

QGIS version
3.22.3-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not reproducible with the latest master (a52133202070a747277d37ed17c0181372cc6772)
