### ISSUE TITLE
Flow Accumulation (one-step)

### ISSUE THREAD

**Issue by ARTCON2020** [qgis/QGIS#47948]
### What is the bug or the crash?

Her is the error feedback from Flow Accumulation(one-step) analysis.
==============================================
QGIS version: 3.22.5-Białowieża
QGIS code revision: c2723178
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
SAGA Next Gen version: 0.0.7
Algorithm started at: 2022-03-24T14:07:02
Algorithm 'Flow accumulation (one step)' starting…
Input parameters:
{ 'DEM' : 'D:/Rekvikvannet/DTM/data/dtm1_33_148_187.tif', 'FLOW_ROUTING' : 4, 'PREPROCESSING' : 0, 'SCA' : 'TEMPORARY_OUTPUT', 'TCA' : 'TEMPORARY_OUTPUT' }

toolchains_terrain_analysis "Flow Accumulation (One Step)" -DEM "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/2a02298ec5aa46edbaa8cb5b857ea198/dtm133148187.sgrd" -PREPROCESSING 0 -FLOW_ROUTING 4 -TCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat" -SCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat"

C:\Users\Administrator\Documents>set SAGA=C:/OSGeo4W/apps\saga

C:\Users\Administrator\Documents>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

C:\Users\Administrator\Documents>PATH=C:\OSGeo4W\apps\qgis-ltr\bin;C:\OSGeo4W\apps\grass\grass78\lib;C:\OSGeo4W\apps\grass\grass78\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\windows\system32;C:\windows;C:\windows\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

C:\Users\Administrator\Documents>saga_cmd toolchains_terrain_analysis "Flow Accumulation (One Step)" -DEM "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/2a02298ec5aa46edbaa8cb5b857ea198/dtm133148187.sgrd" -PREPROCESSING 0 -FLOW_ROUTING 4 -TCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat" -SCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

89 loaded tool libraries (789 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_proj4
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_gdal
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *

*) tool chain libraries

Error: select a library
type -h or --help for further information

C:\Users\Administrator\Documents>exit
Execution completed in 3.06 seconds
Results:
{'SCA': 'C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat',
'TCA': 'C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat
• C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
![QGIS3 22 5](https://user-images.githubusercontent.com/72500978/159924794-9168f24e-9745-4c1f-a29f-c0ec3e1cd5a7.PNG)

### Steps to reproduce the issue

QGIS version: 3.22.5-Białowieża
QGIS code revision: c2723178
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: 9f35b7)
SAGA Next Gen version: 0.0.7
Algorithm started at: 2022-03-24T14:07:02
Algorithm 'Flow accumulation (one step)' starting…
Input parameters:
{ 'DEM' : 'D:/Rekvikvannet/DTM/data/dtm1_33_148_187.tif', 'FLOW_ROUTING' : 4, 'PREPROCESSING' : 0, 'SCA' : 'TEMPORARY_OUTPUT', 'TCA' : 'TEMPORARY_OUTPUT' }

toolchains_terrain_analysis "Flow Accumulation (One Step)" -DEM "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/2a02298ec5aa46edbaa8cb5b857ea198/dtm133148187.sgrd" -PREPROCESSING 0 -FLOW_ROUTING 4 -TCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat" -SCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat"

C:\Users\Administrator\Documents>set SAGA=C:/OSGeo4W/apps\saga

C:\Users\Administrator\Documents>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

C:\Users\Administrator\Documents>PATH=C:\OSGeo4W\apps\qgis-ltr\bin;C:\OSGeo4W\apps\grass\grass78\lib;C:\OSGeo4W\apps\grass\grass78\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\windows\system32;C:\windows;C:\windows\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

C:\Users\Administrator\Documents>saga_cmd toolchains_terrain_analysis "Flow Accumulation (One Step)" -DEM "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/2a02298ec5aa46edbaa8cb5b857ea198/dtm133148187.sgrd" -PREPROCESSING 0 -FLOW_ROUTING 4 -TCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat" -SCA "C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

89 loaded tool libraries (789 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_proj4
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_gdal
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *

*) tool chain libraries

Error: select a library
type -h or --help for further information

C:\Users\Administrator\Documents>exit
Execution completed in 3.06 seconds
Results:
{'SCA': 'C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat',
'TCA': 'C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/905091473a53453b8ddb977d98cf48a8/TCA.sdat
• C:/Users/azmtas01/AppData/Local/Temp/processing_wMmdgT/b875e530f05942939e9aeaef5014b94f/SCA.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Versions

QGIS 3.22.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
As noted above, should be reported to the plugin authors.

**Comment by ARTCON2020** [comment]
Thank you both @alexbruy and @nicogodet.
I uploaded as recommended and waiting for a positive feedback
