### ISSUE TITLE
QGIS Crash after running custom model (Export Print Layout as PDF alg)

### ISSUE THREAD

**Issue by hadallen** [qgis/QGIS#47955]
### What is the bug or the crash?

QGIS freezes upon completion of a .model3 model built with graphical modeler. QGIS is then frozen and requires xkill or similar to terminate.

```
An error has occurred while executing Python code: 

TypeError: unable to convert a C++ 'QVariantMap' instance to a Python object 
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmDialog.py", line 332, in runAlgorithm
    ok, results = execute(self.algorithm(), parameters, self.context, self.feedback)
  File "/usr/share/qgis/python/plugins/processing/gui/AlgorithmExecutor.py", line 64, in execute
    results, ok = alg.run(parameters, context, feedback)
TypeError: unable to convert a C++ 'QVariantMap' instance to a Python object


Python version: 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] 
QGIS version: 3.24.1-Tisler Tisler, exported 

Python Path:
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_fusion
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/LAStools
/usr/share/qgis/python
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python310.zip
/usr/lib/python3.10
/usr/lib/python3.10/lib-dynload
/usr/lib/python3.10/site-packages
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/kmltools/libs
/home/hadallen/.local/share/QGIS/QGIS3/profiles/default/python/plugins/qgis_versioning
.
/dropbox/.../test
```

 

### Steps to reproduce the issue

1. Open qgis_error_mar24.qgz
2. Open qgis_error_mar24..model3 
3. Run qgis_error_mar24.model3
4. Error after map is exported

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.2
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
kmltools | 3.1.16
qgis_versioning | 1.0
LAStools | 1.4
processing_fusion | 3.1
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Model uses `Export Print Layout as PDF` algorithm, with the advanced field `Map layers to assign to unlocked map item(s)` set to  `array_append( @map_layer_ids , @raster)` in order to append the raster layer to the list of activated layers for the exported map (actual model exports 3 maps with various layers activated).

Files are attached in a zip. Project, model, polygon shapefile and raster tif included

![Screenshot_2022-03-24-54_966x77](https://user-images.githubusercontent.com/6172964/159975856-f2b15d07-65d2-4681-b28d-1b5b830dc0c0.png)

![Screenshot_2022-03-24-58_765x413](https://user-images.githubusercontent.com/6172964/159976368-47160cc8-5ebf-46c9-a53e-a0ca3778f51d.png)

[qgis_error_mar24.zip](https://github.com/qgis/QGIS/files/8344066/qgis_error_mar24.zip)

**Comment by Pedro-Murteira** [comment]
I can reproduce the freeze and the error message aswell.

**Comment by pathmapper** [comment]
Looks like this is a regression and not limited to the `Export Print Layout as PDF` algorithm.

Similar error with freeze when running the following model on Windows which works fine with QGIS 3.22.3:

https://kreis-viersen.github.io/qgis-models-and-scripts/models/wfs_daten_kvie/alle_flurstuecke_kvie.model3

![grafik](https://user-images.githubusercontent.com/20856381/160060290-a8678014-e51b-4724-84d3-0b44df4f47f9.png)

**Comment by pathmapper** [comment]
Confirmed on `master` (https://github.com/qgis/QGIS/commit/14e27c2075) on Ubuntu, there's no freeze anymore but similar error message and running the model fails:

![image](https://user-images.githubusercontent.com/20856381/160084679-93ce86ad-07a0-44bf-8744-b9da1c048c02.png)
