### ISSUE TITLE
When a field contains a line break, expressions  will not find the content  - EDIT: same with import of .csv files

### ISSUE THREAD

**Issue by spacerat1** [qgis/QGIS#47957]
### What is the bug or the crash?

I just updated from 3.16.16 to 3.22.5

I have some fields in my layers, that contain line breaks. it's no difference whether the field has Multiline activated or not.

Some symbols and Labels are looking for a specific expression in this fields. (search with wildcards %)

If the field contains no line breaks, the result is True.
The same text with line breaks gets me a False.
Even if i look for the exact content of the field (without wildcards) , strings, that contain a line break returning a False.

The "Test" button next to the filter line (for example in Symbols) is working correct. It's just the expression string builder that has the issue.

### Steps to reproduce the issue

create a layer and a field "description" (String)
enter text in this field - with and without line breaks (like 'one line' or 'first line second line'
apply a filter in symbols that contains wildcards - for example: description ilike '%line%'
press the test-button - this will get you the correct amount of expressions ( in the attached layer this will show all four entries)

enter the expression string builder - only the features, that doesn't contain a line break are True

(you can use the attached layer - it should show you the numbers 1 to 4 if the filter works correct

[Testlayer - Line Break.zip](https://github.com/qgis/QGIS/files/8348233/Testlayer.-.Line.Break.zip)

![Screenshot 3 16 16](https://user-images.githubusercontent.com/46305700/160069038-1141f5db-11e4-472d-9b92-0dbf5941e274.jpg)
result with QGIS 3.16.16
![Screenshot - 3 22 5](https://user-images.githubusercontent.com/46305700/160069045-9933fc3f-cdc4-4bc3-be40-9610f5f99fad.jpg)
result with QGIS 3.22.5

### Versions

QGIS-Version
3.22.5-Białowieża
QGIS-Codeversion
c2723178
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
Debug_VSCode
0.7
quick_map_services
0.19.28
refFunctions
1.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context
EDIT:  Just tried to import a csv file with the data source manager. The headlines from some fields in the .csv file contained a line break. Qgis couldn't find any data in the csv. after removing the line breaks, QGIS could find and load the values.
_No response_

**Comment by felixvons** [comment]
Hey,

in QGIS 3.22.10 (QGIS about -> 6a63fd37) and 3.26.2 still not working.

The example expression with `'Herbert\nCarl' ILIKE '%carl%'` do not work.

A bad and working workaround is to use `replace` or `regexp_match` functions in the expression editor.

Any plans to fix this issue?

<details>
<summary>3.22.10-Białowieża</summary>
QGIS-Version
3.22.10-Białowieża

QGIS-Codeversion
6a63fd37

Qt-Version
5.15.3

Python-Version
3.9.5

GDAL-Version
3.5.1

PROJ-Version
9.0.1

EPSG-Registraturdatenbankversion
v10.064 (2022-05-19)

GEOS-Version
3.10.3-CAPI-1.16.1

SQLite-Version
3.38.1

PDAL-Version
2.4.2

PostgreSQL-Client-Version
14.3

SpatiaLite-Version
5.0.1

QWT-Version
6.1.6

QScintilla2-Version
2.13.1

BS-Version
Windows 10 Version 2009
</details>

<details>
<summary>3.26.2-Buenos Aires</summary>
QGIS-Version
3.26.2-Buenos Aires

QGIS-Codeversion
feec3d3b12f

Qt-Version
5.15.3

Python-Version
3.9.5

GDAL-Version
3.5.1

PROJ-Version
9.0.1

EPSG-Registraturdatenbankversion
v10.064 (2022-05-19)

GEOS-Version
3.10.3-CAPI-1.16.1

SQLite-Version
3.38.1

PDAL-Version
2.4.2

PostgreSQL-Client-Version
unknown

SpatiaLite-Version
5.0.1

QWT-Version
6.1.6

QScintilla2-Version
2.13.1

BS-Version
Windows 10 Version 2009
</details>

Kind regards,
Felix

**Comment by agiudiceandrea** [comment]
I can confim the issue is a regression, as the expression works correctly with QGIS 3.20.3 and previous version, while it doesn't since QGIS 3.22.0. It seems to me this issue could be a side effect of the "migration" from QRegExp to QRegularExpression and in particular of the commit https://github.com/qgis/QGIS/commit/86fa201640632d4dad0aac3d260e33cfd0cc1851 (https://github.com/qgis/QGIS/pull/44137).

@felixvons, I've submitted a PR that fixes this issue according to my tests.
