### ISSUE TITLE
Support for near infrared channel

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#47953]
### Feature description

In LAS/LAZ 1.4 file format, there is also support for near infrared (NIR) channel (Point Data Record Format 8). It seems that currently we do not support this attribute at all.

Sample data:
https://geoportaal.maaamet.ee/index.php?lang_id=2&plugin_act=otsing&kaardiruut=467494&andmetyyp=lidar_laz_tava&dl=1&f=467494_2021_tava.laz&no_cache=623afa694c49d&page_id=664

Note: it seems that CloudCompare does not support NIR either (I didn't find a way how to display that attribute there)

**Comment by NEDJIMAbelgacem** [comment]
I added the support for NIR while implementing QLazInfo class. 
The problem I'm facing with this dataset is that it is unreadable with PDAL and I get the following error running `pdal info` :
`
(pdal info readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: crs not found
(pdal info readers.las Error) GDAL failure (1) PROJ: proj_create_from_database: crs not found
PDAL: Can't create dimension with invalid name 'Pulse width'.
`

**Comment by NEDJIMAbelgacem** [comment]
Turns out I just needed to change the attribute name to infrared and use PDAL 2.4
