### ISSUE TITLE
Error running SAGA fill sink (wang&liu)

### ISSUE THREAD

**Issue by deepnpisgah** [qgis/QGIS#47965]
### What is the bug or the crash?

QGIS version: 3.24.1-Tisler
QGIS code revision: 9d1e5b189a
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2022-03-25T11:24:35
Algorithm 'Fill sinks (wang & liu)' starting…
Input parameters:
{ 'ELEV' : '/Volumes/10_TB-2020/QGIS_Projects/ClipCathyDEM.tif', 'FDIR' : '/Volumes/10_TB-2020/QGIS_Projects/CathyFlowDir.sdat', 'FILLED' : '/Volumes/10_TB-2020/QGIS_Projects/CathyFillSinks.sdat', 'MINSLOPE' : 0.01, 'WSHED' : '/Volumes/10_TB-2020/QGIS_Projects/CathyWatershed.sdat' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "/Volumes/10_TB-2020/qgis/tmp/processing_QoyQtS/d646b8003a2842f09d3ed44ade7bd6c9/ClipCathyDEM.sgrd" -FILES "/Volumes/10_TB-2020/QGIS_Projects/ClipCathyDEM.tif"
ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "/Volumes/10_TB-2020/qgis/tmp/processing_QoyQtS/d646b8003a2842f09d3ed44ade7bd6c9/ClipCathyDEM.sgrd" -MINSLOPE 0.01 -FILLED "/Volumes/10_TB-2020/QGIS_Projects/CathyFillSinks.sdat" -FDIR "/Volumes/10_TB-2020/QGIS_Projects/CathyFlowDir.sdat" -WSHED "/Volumes/10_TB-2020/QGIS_Projects/CathyWatershed.sdat"
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E
Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
Expected in: /Applications/QGIS.app/Contents/MacOS/lib/libprotobuf-lite.dylib
in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
/Applications/QGIS.app/Contents/MacOS/bin/saga_cmd: line 9: 73081 Abort trap: 6 "$THISDIR/_saga_cmd" "$@"
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E
Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
Expected in: /Applications/QGIS.app/Contents/MacOS/lib/libprotobuf-lite.dylib
in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
/Applications/QGIS.app/Contents/MacOS/bin/saga_cmd: line 9: 73086 Abort trap: 6 "$THISDIR/_saga_cmd" "$@"
Execution completed in 0.36 seconds

### Steps to reproduce the issue

Trying to use SAGA tools 'fill sink (wang & liu). 
Choose a DEM raster, take default minimum slope = 0.010

error on 
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E
Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
Expected in: /Applications/QGIS.app/Contents/MacOS/lib/libprotobuf-lite.dylib
in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
/Applications/QGIS.app/Contents/MacOS/bin/saga_cmd: line 9: 73081 Abort trap: 6 "$THISDIR/_saga_cmd" "$@"
dyld: Symbol not found: __ZN20wireless_diagnostics6google8protobuf2io16CodedInputStream24default_recursion_limit_E
Referenced from: /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
Expected in: /Applications/QGIS.app/Contents/MacOS/lib/libprotobuf-lite.dylib
in /System/Library/PrivateFrameworks/WirelessDiagnostics.framework/Versions/A/Libraries/libprotobuf.dylib
/Applications/QGIS.app/Contents/MacOS/bin/saga_cmd: line 9: 73086 Abort trap: 6 "$THISDIR/_saga_cmd" "$@"

### Versions

QGIS version | 3.24.1-Tisler | QGIS code revision | 9d1e5b189a
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS Mojave (10.14)
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.6
QuickOSM | 2.0.1
profiletool | 4.2.2
lines_ranking | 1.0
quick_map_services | 0.19.29
Hy2roresO-master | 0.0.1
LAStools | 1.4
SRTM-Downloader | 3.1.17
latlontools | 3.6.2
qfieldsync | v4.0.0
qgis_resource_sharing | 0.16.0
pointsamplingtool | 0.5.3
GroupStats | 2.2.5
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.24.1-Tisler
QGIS code revision
[9d1e5b189a](https://github.com/qgis/QGIS/commit/9d1e5b189a)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS Mojave (10.14)

Active Python plugins
numericalDigitize
0.4.6
QuickOSM
2.0.1
profiletool
4.2.2
lines_ranking
1.0
quick_map_services
0.19.29
Hy2roresO-master
0.0.1
LAStools
1.4
SRTM-Downloader
3.1.17
latlontools
3.6.2
qfieldsync
v4.0.0
qgis_resource_sharing
0.16.0
pointsamplingtool
0.5.3
GroupStats
2.2.5
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

System Version:	macOS 10.14.6 (18G103)
  Kernel Version:	Darwin 18.7.0

previously had trouble with RASTER clip to layer and had to adjust multiple symlinks in QGIS lib directory due to other missing symbol errors

ln -s /System/Library/Frameworks/ImageIO.framework/Resources/libJPEG.dylib libjpeg.dylib
ln -s /System/Library/Frameworks/ImageIO.framework/Resources/libTIFF.dylib libtiff.dylib
ln -s /System/Library/Frameworks/ImageIO.framework/Resources/libpng.dylib libtpng.dylib
ln -s ./local/Cellar/sqlite/3.38.1/lib/libsqlite3.dylib libsqlite3.dylib

**Comment by alexbruy** [comment]
Looks like MacOS packaging issue.

**Comment by deepnpisgah** [comment]
I will try from command line. Without the symlinks the GDAL processing fails prior to SAGA. I need the GDAL files to get to the SAGA processing parts.

**Comment by deepnpisgah** [comment]
I was unable to run from cmd line, segmentation fault.

Now the odd part...

I restarted QGIS and was able to run the Fill and Sink. no issues
 When I tried to Channel Network and Drainage Basins I get again the same error , symbol not found in libproto
I restarted QGIS again and no errors. 

I can try a fresh install of QGIS again and see about recreating.

**Comment by alexbruy** [comment]
Then it is most likely local issue.
