### ISSUE TITLE
Error running 'Points to Path'

### ISSUE THREAD

**Issue by AlexC84** [qgis/QGIS#47966]
### What is the bug or the crash?

Attempting to run Points to Path on a small points shapefile layer

```
Traceback (most recent call last):
              File ".../qgis/Library/./python/plugins\processing\gui\AlgorithmDialog.py", line 194, in runAlgorithm
              self.cancelButton().setEnabled(self.algorithm().flags() & QgsProcessingAlgorithm.FlagCanCancel)
             TypeError: setEnabled(self, bool): argument 1 has unexpected type 'Flags'
```

### Steps to reproduce the issue

1. I created a points layer using 'Add delimited Test Layer' from a csv file; successfully displays on the canvas
2. Exported the points layer to a shapefile and added that layer to the project
3. Attempted to convert the points shapefile layer to a polyline using the 'Points to Path' tool from the 'Processing>Toolbox>Points to Path' menu
4. The layer was preselected in the 'Points to Path' dialogue
5. Left the options at their default values
6. Pressed 'Run'
7. Got an error message telling me to look at 'Python error' in the Log Messages pane:

```
Traceback (most recent call last):
              File ".../qgis/Library/./python/plugins\processing\gui\AlgorithmDialog.py", line 194, in runAlgorithm
              self.cancelButton().setEnabled(self.algorithm().flags() & QgsProcessingAlgorithm.FlagCanCancel)
             TypeError: setEnabled(self, bool): argument 1 has unexpected type 'Flags'
```

### Versions

QGIS version
3.18.3-Zürich
QGIS code branch
Release 3.18
Compiled against Qt
5.12.9
Running against Qt
5.12.9
Compiled against GDAL/OGR
3.4.0
Running against GDAL/OGR
3.4.0
Compiled against GEOS
3.10.1-CAPI-1.16.0
Running against GEOS
3.10.1-CAPI-1.16.0
Compiled against SQLite
3.37.0
Running against SQLite
3.37.1
Compiled against PDAL
2.3.0
Running against PDAL
2.3.0 (git-version: Release)
PostgreSQL Client Version
13.5
SpatiaLite Version
5.0.1
QWT Version
6.1.6
QScintilla2 Version
2.11.2
Compiled against PROJ
8.2.0
Running against PROJ
Rel. 8.2.0, November 1st, 2021
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Qgis installed with conda

**Comment by agiudiceandrea** [comment]
I cannot confirm using QGIS 3.18 QGIS 3.22 and QGIS 3.24 installed via OSGeo4W. Probably a conda issue. Does any of the other QGIS processing algorithm work?

**Comment by AlexC84** [comment]
I just tried 'Processing>Toolbox>Layer Tools>Extract layer extent' and I get the same error.

Sorry, I am new to GIS/QGIS and hadn't realized the conda install wasn't officially supported. I'll try the OSGeo4W install

**Comment by AlexC84** [comment]
OK; I've just installed 3.24.1-Tisler via OSGeo4W and the Point to Path tool works fine.
Thanks

**Comment by udaf-mcq** [comment]
I have been using Points to Path for several days without an issue.  Today I converted successfully several more files without a problem.  However the application runs but it is not generating any data in the shape files (1k) for all files.  Here is the log notice it shows no path created.
QGIS version: 3.34.12-Prizren
QGIS code revision: eeb6af3638
Qt version: 5.15.13
Python version: 3.12.7
GDAL version: 3.9.3
GEOS version: 3.13.0-CAPI-1.19.0
PROJ version: Rel. 9.5.0, September 15th, 2024
PDAL version: 2.8.1 (git-version: a06325)
Algorithm started at: 2024-11-05T12:55:54
Algorithm 'Points to path' starting…
Input parameters:
{ 'CLOSE_PATH' : False, 'GROUP_EXPRESSION' : '', 'INPUT' : 'F:/SanPitch-Sterling/colorCorrected-sfrFiles-6-15-23/Points-6-15-23-SanPitch/MAX_0001.csv', 'NATURAL_SORT' : False, 'ORDER_EXPRESSION' : '', 'OUTPUT' : 'F:/SanPitch-Sterling/colorCorrected-sfrFiles-6-15-23/Points-6-15-23-SanPitch/SanPitch-6-15-23-VideoShape/MAX_0001.shp' }

Loading points…
Creating paths…
Execution completed in 0.14 seconds
Results:
{'NUM_PATHS': 0,
'OUTPUT': 'F:/SanPitch-Sterling/colorCorrected-sfrFiles-6-15-23/Points-6-15-23-SanPitch/SanPitch-6-15-23-VideoShape/MAX_0001.shp'}

Loading resulting layers
Algorithm 'Points to path' finished
