### ISSUE TITLE
Crash report when clicking on the arrow next to the color ramp for a raster

### ISSUE THREAD

**Issue by jwilliamrozelle** [qgis/QGIS#47977]
### What is the bug or the crash?

Crash ID: [39e1178f5cc6590c3f9c740003a0b8c1aa71ac7a](https://github.com/qgis/QGIS/search?q=39e1178f5cc6590c3f9c740003a0b8c1aa71ac7a&type=Issues)

Stack Trace

QgsSymbolLayerUtils::colorRampPreviewPixmap :
QgsSymbolLayerUtils::colorRampPreviewIcon :
QgsColorRampButton::prepareMenu :
QObject::qt_static_metacall :
QMenu::popup :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

I'm not sure how to reproduce it specifically. Opened a raster, clicked properties, symbology, and the drop-down error next to the color ramp.

### Versions

QGIS Version: 3.22.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
If there's no way to reproduce this then there's little we can do
