### ISSUE TITLE
QGIS 3.4.1 crashes while creating new GRASS mapset

### ISSUE THREAD

**Issue by abhijitekbote** [qgis/QGIS#47973]
### What is the bug or the crash?

h2. User Feedback

Crashed when creating new Grass mapset

h2. Report Details

*Crash ID*: 878c26343d2e5e53eb9680fbfcb9bfc4d454fcc7

*Stack Trace*
<pre>
RtlRaiseStatus :
RtlUnwindEx :
setjmpex :
G_fatal_error :
G_getenv :
read_datum_table :
GPJ_osr_to_grass :
GPJ_wkt_to_grass :
version :
version :
QMetaObject::activate :
QWizard::subTitleFormat :
QWizard::next :
QMetaObject::activate :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.4.1-Madeira
QGIS code revision: commit:383851c597
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.3.2
Running against GDAL: 2.3.2

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

see error

### Versions

QGIS 3.4.1 crashed when creating new mapset in Grass.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@abhijitekbote Is it replicable?

**Comment by lbartoletti** [comment]
> ###
> 
> QGIS 3.4.1 crashed when creating new mapset in Grass.

Please try with a supported version, at least 3.22
