### ISSUE TITLE
QGIS Unexpectedly ended when zoom out

### ISSUE THREAD

**Issue by ImRobinAguilar** [qgis/QGIS#47975]
### What is the bug or the crash?

While i'm working on a map, i zoom out faster and QGIS crash.

Crash ID: 43c4e6728110657d0fb92947d50aab0e149231e3

Stack Trace

QgsTemplatedLineSymbolLayerBase::renderPolylineVertex :
QgsTemplatedLineSymbolLayerBase::renderPolyline :
QgsMarkerLineSymbolLayer::renderPolyline :
QgsLineSymbol::renderPolylineUsingLayer :
QgsLineSymbol::renderPolyline :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.14-Hannover
QGIS code revision: 42791986
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

1. Scroll down at anyplace of the map, making a fast zoom out.
2. See error

### Versions

Versión de QGIS
3.16.14-Hannover
Revisión del código de QGIS
42791986
Compilado contra Qt
5.15.2
Ejecutándose contra Qt
5.15.2
Compilado contra GDAL/OGR
3.4.0
Ejecutándose contra GDAL/OGR
3.4.0
Compilado contra GEOS
3.10.0-CAPI-1.16.0
Ejecutándose contra GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
Versión del cliente PostgreSQL
13.0
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.3
Versión de QScintilla2
2.11.5
Compilado contra PROJ
8.2.0
Ejecutándose contra PROJ
Rel. 8.2.0, November 1st, 2021
Versión del SO
Windows 10 Version 2009
Active python plugins
OnlineRoutingMapper; 
openlayers_plugin; 
OSMDownloader; 
quick_map_services; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Please update to a newer support qgis release --this bug is already fixed.
