### ISSUE TITLE
'Identify Features' cannot be toggled off once activated

### ISSUE THREAD

**Issue by wendybug** [qgis/QGIS#47984]
### What is the bug or the crash?

Identify features cannot be toggled back off again, once activated.

Tisler 3.24

### Steps to reproduce the issue

Open QGIS
Add shapefile
Activate 'identify features' button
Try to deactivate ... wil not do so
restart QGIS to clear

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code revision | 5709b82461
-- | -- | -- | --

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Just select another tool such as pan, all the tools are this way.

**Comment by wendybug** [comment]
Thank you. These things seem obvious once one is informed.

**Comment by weca-theo** [comment]
Hate to bring this up from the dead, but selecting a totally different tool (ie. Pan) to change the activity of another tool (Identify Features) doesn't sound right at all. It's a dirty work around IMO.

My example below, where I've identified a feature from a polygon layer which full covers the map area. With the Identify tool enabled, I can't 'un-identify' to clear the red area. Clicking outside the polygon will identify another polygon, right clicking brings up the identify list, pressing Esc does nothing, clicking outside the layer area involves moving away from where I am (and also runs the risk of me identifying another layer hiding elsewhere).
![image](https://github.com/qgis/QGIS/assets/83225776/945ba7f1-6f5c-409d-bcdc-faa91c26e3d6)

There needs to be a keyboard shortcut to un-identify. I'm often in situations giving training and users are clicking all over the map to get rid of a mess of red shade. The more they click, the more mess too.

**Comment by saudeoud** [comment]
I also have a problem with the identify tool.
No way to close, move, or pin the identify panel, it even come in the first view when switching to other applications :
- doucle click on the upper bar of the pannel,
- click on the closing cross that appears in the top of the pannel,
- pressing escape,
- choosing another tool,
nothing happens 

The only way to get rid of it is to close QGIS.

Configuration :

Version de QGIS | 3.40.2-Bratislava

Révision du code | 14826ca1e4a
 
Libraries
Version de Qt | 5.15.8
Version de Python | 3.11.2
Version de GDAL/OGR | 3.6.2
Version de Proj | 9.1.1
Version de la base de données du registre EPSG | v10.076 (2022-08-31)
Version de GEOS | 3.11.1-CAPI-1.17.1
Version de SQLite | 3.40.1
Version du client PostgreSQL | 15.8 (Debian 15.8-0+deb12u1)
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.13.3
Version de l'OS | Debian GNU/Linux 12 (bookworm)
 
Extensions Python actives
cadastre | 1.20.0
qgis_hub_plugin | 0.2.0
InvisibleLayersAndGroups | 2.2
BezierEditing | version 1.3.8
layer_style_master | 0.1
qgis_adjust_style | 2.0
qgis-maptiler-plugin | 3.4.0
Majic | 0.3
prettier_maps | 1.2.0
LAStools | 2.2.0
qgis2web | 3.24.0
db-style-manager | 0.8
transparency_setter | 0.2
Submission | 0.10
changeDataSource | 3.1
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99



Obviously this is very annoying.

**Comment by gareth-d-ga** [comment]
I seem to be having the same issue as @saudeoud (ubuntu 24.04, QGIS 3.44.1). 

The identify feature tool opens a panel in a separate window, which I cannot move or close (i.e. nothing happens if I click and drag the window, or click the top right 'x'). 

I can get rid of it by right clicking on the identify tool icon in the main interface. This opens up a list naming many panels, and I can uncheck 'Identify Results Panel' to remove it. Otherwise I have to close QGIS.

Ideally I would like for the panel to be docked to the main interface, but can't find that as an option anywhere. 

<img width="1920" height="1080" alt="Image" src="https://github.com/user-attachments/assets/06b03e3a-27f9-4530-be57-dad589c5cb8a" />

**Comment by agiudiceandrea** [comment]
@gareth-d-ga please create a new issue report.
