### ISSUE TITLE
Georeferencer Plugin

### ISSUE THREAD

**Issue by vals996** [qgis/QGIS#47997]
### What is the bug or the crash?

Hi! 
I am working on QGis 3.22.5 and, since yesterday, the Georeferencer Plugin won't work. In particular, after importing the image and setting the control points, the plugin starts working but, then, it stops at 3-6%.
I already tried different images and also a new file but nothing changed so, right now, I cannot use this plugin. 

### Steps to reproduce the issue

Go to "Georefencer plugin"
Import the new image
set the control points by map
choose the transformation (ex. Thin Plate Spline (TPS))
play
the plugin stops at 3-6%

### Versions

QGis 3.22.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@vals996 Hello, I'm not able to reproduce it. Can you try with a new profile?

**Comment by vals996** [comment]
Hello! I tried one minute ago with a new profile and apparently the plugin works, however with the new profile i have a problem when I close the software. I don't know the reason but If I work on the "standard" profile and the I close it, everything works; on the contrary, when I use the second/new profile and I close the software, it stops working and appear a crash window.

**Comment by vals996** [comment]
![crash](https://user-images.githubusercontent.com/102526189/160400683-78e84d03-e57a-41ba-8ba5-ff7b41d83f99.png)

**Comment by Pedro-Murteira** [comment]
@vals996 If that crash is consistent, and if you can reproduce it everytime, you can file a new issue, so that problem can also be adressed accordingly

**Comment by vals996** [comment]
Ok, thank you!
