### ISSUE TITLE
No transform is available after Update to QGIS 3.22.5 and GRASS 7.8.7 

### ISSUE THREAD

**Issue by anandita473** [qgis/QGIS#47999]
### What is the bug or the crash?

I updated QGIS from Hannover to QGIS Bialowieza but after successful run in Hannover it is showing following error while running the new version.

No transform is available between ETRS89 / UTM zone 32N and EPSG:4326 - WGS 84.
No coordinate operations are available between these two reference systems

Kindly help me fix this issue as this error should not happen when importing existing project in new QGIS.

### Steps to reproduce the issue

![qgis error](https://user-images.githubusercontent.com/102523549/160401571-ac796675-62df-487c-a72d-01c6fff8cd96.jpg)

### Versions

QGIS from Hannover 3.16.16 to QGIS Bialowieza 3.22.5, 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
How QGIS is installed (msi or OSGeo4W) ?
Did you try with a new profile (we can see some plugins in your screen) ?

**Comment by anandita473** [comment]
As MSI. yes there are SWAT+ plugins. New profile? I did not quite understand what do you mean by that but I have created the new project but the raster's and layers were created in the older version.

**Comment by nicogodet** [comment]
Preferences -> User profiles -> New profile

**Comment by anandita473** [comment]
preferences in QGIS? under which tab, I am fairly new to QGIS.

**Comment by nicogodet** [comment]
Settings*

**Comment by anandita473** [comment]
![image](https://user-images.githubusercontent.com/102523549/160406909-fe3fbe6b-c642-4ea2-93dd-aadd941508cd.png)

**Comment by nicogodet** [comment]
Create a new one and try to open your project again

**Comment by anandita473** [comment]
![qgis error_new profile](https://user-images.githubusercontent.com/102523549/160407255-484ab156-63ea-4768-a127-d1a1b35ff33d.jpg)


i am getting same error.

**Comment by nicogodet** [comment]
Try to re-assign properly the faulty layers, save and re-open.

**Comment by anandita473** [comment]
ok, I will do. thank you for your help. I will post if the error is not resolved

**Comment by anandita473** [comment]
solved , thanks to nicogodet.
