### ISSUE TITLE
Geopackage from network location is not a valid or recognized data source

### ISSUE THREAD

**Issue by T3xtM4rk3r** [qgis/QGIS#48003]
### What is the bug or the crash?

After updating to QGIS 3.24.1-2 yesterday, it fails to recognize geopackages from a network location as a valid data source

### Steps to reproduce the issue

1. Open Qgis 3.24.1-2
2. create new geopackage layer with point geometry on local harddrive (e. g. desktop)
![grafik](https://user-images.githubusercontent.com/92782306/160553721-44852b25-dda3-464a-a56b-9330e2c3a925.png)
3. add some points and save edits
4. copy and past created geopackage to a network location in windows explorer - in our case something like \\\\xxxx-server\GIS\xxxx_GmbH\Geodaten\
5. drag and drop geopackage from network location back to qgis project

6. 2022-03-29T09:12:04     CRITICAL    Invalid Data Source : //xxx-server/GIS/xxxx_GmbH/Geodaten/test.gpkg is not a valid or recognized data source.
![test](https://user-images.githubusercontent.com/92782306/160556438-cb3211ec-3b93-4ad8-b420-d7943d5e4725.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.24.1-Tisler | QGIS-Codeversion | 5709b82461
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
Kompiliert mit GDAL/OGR | 3.4.1 | Läuft mit GDAL/OGR | 3.4.2
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.054 (2022-02-13)
GEOS-Version | 3.10.2-CAPI-1.16.0
Kompiliert mit SQLite | 3.37.2 | Läuft mit SQLite | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.24.1-Tisler
QGIS-Codeversion
[5709b82461](https://github.com/qgis/QGIS/commit/5709b82461)
Qt-Version
5.15.2
Python-Version
3.9.5
Kompiliert mit GDAL/OGR
3.4.1
Läuft mit GDAL/OGR
3.4.2
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.054 (2022-02-13)
GEOS-Version
3.10.2-CAPI-1.16.0
Kompiliert mit SQLite
3.37.2
Läuft mit SQLite
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Cannot reproduce on 3.24.0

**Comment by agiudiceandrea** [comment]
@T3xtM4rk3r, are you sure you have installed the package qgis-3.24.1-2 from OSGeo4W repository? The "about" page should report "GDAL/OGR version	3.4.2" and not "Kompiliert mit GDAL/OGR	3.4.1	Läuft mit GDAL/OGR	3.4.2": i.e. QGIS 3.24.1 from qgis-3.24.1-2 is compiled with GDAL 3.4.2, not with GDAL 3.4.1.

**Comment by agiudiceandrea** [comment]
Issue confirmed using QGIS 3.24.1 (5709b82461) on Windows 10 from OSGeo4W (package qgis 3.24.1-2) compiled against GDAL/OGR 3.4.2 and using GDAL/OGR 3.4.2 runtime:
` CRITICAL    Invalid Data Source : //192.168.1.1/test/test.gpkg is not a valid or recognized data source.`
`WARNING    Unable to load //192.168.1.1/test/test.gpkg`

The issue does not occur using the same QGIS 3.24.1 (5709b82461) on Windows 10 from OSGeo4W (package qgis 3.24.1-2) compiled against GDAL/OGR 3.4.2 but using GDAL/OGR 3.4.1 runtime.

The issue does not occur using QGIS 3.22.5 (c27231782f) on Windows 10 from OSGeo4W (package qgis-ltr 3.22.5-2) compiled against GDAL/OGR 3.4.2 and using GDAL/OGR 3.4.2 runtime.

Maybe related to https://github.com/qgis/QGIS/pull/47098?

**Comment by T3xtM4rk3r** [comment]
> @T3xtM4rk3r, are you sure you have installed the package qgis-3.24.1-2 from OSGeo4W repository? The "about" page should report "GDAL/OGR version 3.4.2" and not "Kompiliert mit GDAL/OGR 3.4.1 Läuft mit GDAL/OGR 3.4.2": i.e. QGIS 3.24.1 from qgis-3.24.1-2 is compiled with GDAL 3.4.2, not with GDAL 3.4.1.

I am sorry for the confusion. At first i added the about page of an existing profile with plugins still active. When I noticed this, i switched to a new profile without any plugins enabled and copied the new about page.  The critial error still occurs.
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS-Version | 3.24.1-Tisler | QGIS-Codeversion | 5709b82461
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.4.2
PROJ-Version | 9.0.0
EPSG-Registraturdatenbankversion | v10.054 (2022-02-13)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.3
QScintilla2-Version | 2.11.5
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.24.1-Tisler
QGIS-Codeversion
[5709b82461](https://github.com/qgis/QGIS/commit/5709b82461)
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.2
PROJ-Version
9.0.0
EPSG-Registraturdatenbankversion
v10.054 (2022-02-13)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009




Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by agiudiceandrea** [comment]
@Pedro-Murteira, I think this should be tagged as `Regression`.

**Comment by rouault** [comment]
Apparently this isn't fixed. See https://github.com/qgis/QGIS/pull/48059#issuecomment-1090109953. I don't have the development setup to debug this
