### ISSUE TITLE
Crash on start up

### ISSUE THREAD

**Issue by Trennez** [qgis/QGIS#48026]
## User Feedback

Crashes on opening

## Report Details

**Crash ID**: [Not available](https://github.com/qgis/QGIS/search?q=Not available&type=Issues)

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

start the program

### Versions

3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Cannot create profile as I cannot start the program

**Comment by Pedro-Murteira** [comment]
@Trennez Is the crash still consistent even after uninstalling>installing QGIS?

**Comment by Trennez** [comment]
No, a reinstallation appears to have corrected this problem and some other bugs I was having with the previous installation.
