### ISSUE TITLE
Cannot add GeoPackage layer with hash symbol # in file path

### ISSUE THREAD

**Issue by MalikAlMaut** [qgis/QGIS#48024]
### What is the bug or the crash?

**Adding or connecting to any Geopackage with the hash symbol "#" in file path is no longer possible** in QGIS 3.24.1
It is working in QGIS LTR.
edit:
Opening any saved Project also shows added layers as unavailable. Browsing to the gpkg in the 'Handle Unavailable Layers' dialoque cannot reestablish the connection

Adding via drag & drop or vie Data Source Manager results in
"Invalid Data Source file/path/with#/any.gpkg is not a valid or recognized data source"

Connecting via Data Source Manager results in a defective connection:
It appears empty in the Data Source Manager itself
The Browser Panel shows the connection, but "The file does not contain any layer or there was an error opening the file."
The DB Manager shows the connection and a preview of the table, but no preview of geometries. Adding any layer to the canvas results in a unavailable layer (leading to the Repair Data Source dialoque). SQL queries show a preview of the data, but cannot be loaded as new layer (error: "There was an error creating the SQL layer, please check the logs for further information." But in the Log Messages Panel there are no entries)

### Steps to reproduce the issue

1. Open new project

2. with hash symbol "#" in file path either:
- drag & drop any gpkg into project
- Data Source Manager > Vector > Add 
3. "Invalid Data Source file/path/with#/any.gpkg is not a valid or recognized data source"

2. Data Source Manager  > New Connection > Connect
3. nothing / empty / defective connection

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code revision | 5709b82461
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
alkisplugin | 2.0.53
AttributeAssignment | 2.3
changeDataSource | 3.1
create_layer_from_selected_features | 1.2
firstaid | 2.1.5
getthemfiltered | 0.1.3
GroupStats | 2.2.5
joinmultiplelines | Version 0.4.1
KP_find | 3.0.5
LayerBoard | 1.0.1
lftools | 1.6.1
los_tools | 0.5
numericalDigitize | 0.4.6
profiletool | 4.2.2
qfieldsync | v4.0.0
QGIS3-getWKT | 1.4
QuickOSM | 2.0.1
SaxonyCadastralParcels | 0.3.4
searchlayers | 3.0.7
splitmultipart | 1.0.0
unique_values_viewer | 0.2
VectorBender | 0.2.1
ViewshedAnalysis | 1.7
VoGisProfilTool | 3.0.2
db_manager | 0.1.20
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@MalikAlMaut Hello, did you try with a new profile? I see that a lot of plugins are installed according to your version info, it might be related.

**Comment by MalikAlMaut** [comment]
Hello @Pedro-Murteira, yes I did.
Sorry for the long Versions-Table. I wasn't quite sure, if I should shorten the list, since there are also core plugins mentioned.

**Comment by agiudiceandrea** [comment]
Issue confirmed using QGIS 3.24.1 (https://github.com/qgis/QGIS/commit/5709b824612b70f1eb93c77fc88963ced34a16df) on Windows 10 from OSGeo4W (package qgis 3.24.1-2) compiled against GDAL/OGR 3.4.2 and using GDAL/OGR 3.4.2 runtime:
CRITICAL Invalid Data Source : C:/te#st/test.gpkg is not a valid or recognized data source.
WARNING Unable to load C:/te#st/test.gpkg

The issue does not occur using the same QGIS 3.24.1 (https://github.com/qgis/QGIS/commit/5709b824612b70f1eb93c77fc88963ced34a16df) on Windows 10 from the same OSGeo4W package (qgis 3.24.1-2) compiled against GDAL/OGR 3.4.2 but forced to use GDAL/OGR 3.4.1 runtime.

The issue does not occur using the same QGIS 3.24.1 (https://github.com/qgis/QGIS/commit/5709b824612b70f1eb93c77fc88963ced34a16df) on Windows 10 from the previous OSGeo4W package (qgis 3.24.1-1) compiled against GDAL/OGR 3.4.1 and using GDAL/OGR 3.4.1 runtime.

The issue does not occur using QGIS 3.22.5 (https://github.com/qgis/QGIS/commit/c27231782f46fb67183d8d26bfe41b93cb30f1b6) on Windows 10 from OSGeo4W (package qgis-ltr 3.22.5-2) compiled against GDAL/OGR 3.4.2 and using GDAL/OGR 3.4.2 runtime.

Maybe related to https://github.com/qgis/QGIS/pull/47098?

**Comment by agiudiceandrea** [comment]
@Pedro-Murteira, I think this should be tagged as `Regression`.

**Comment by rouault** [comment]
GDAL fix in https://github.com/OSGeo/gdal/pull/5554

**Comment by agiudiceandrea** [comment]
@MalikAlMaut the fix for this issue is now contained in the OSGeo4W `gdal` and `gdal304-runtime` packages version 3.4.2-2. You can update those packages to version 3.4.2 in OSGeo4W in order to fix the issue.
