### ISSUE TITLE
QGIS 3.22 Crash using Merge Vectorlayer

### ISSUE THREAD

**Issue by Elkahuna83** [qgis/QGIS#48025]
### What is the bug or the crash?

When using the "Merge Vector Layers" processing tool, QGIS keeps crashing. 
I have my data on a cloud.
Since the error happens all the time, I have also tried turning off the cloud sync. Unfortunately, this also has no effect on how often QGIS crashes.

### Steps to reproduce the issue

Go to processing tool.
Click on "shortest path point to point"
Create multiple single line layers. 
Then click on "merge vector layers" in processing tool.
Select all temporary single layers, select the projectEPSG.
Click on start and QGIS crashes.

what can i do to stop this from happening?

## Report Details

**Crash ID**: [f952c03d3d8c0ccfce3d423f5fe11f006532a31f](https://github.com/qgis/QGIS/search?q=f952c03d3d8c0ccfce3d423f5fe11f006532a31f&type=Issues)

**Stack Trace**
<pre>
QMimeType::staticMetaObject :
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QObject::qt_static_metacall :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QObject::qt_static_metacall :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QObject::qt_static_metacall :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgsProject::addMapLayer :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForCompletion :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Versions

QGIS-Version
3.22.4-Białowieża
QGIS-Codeversion
ce8e65e9
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
alkisplugin
2.0.53
GeometryShapes
0.7
HCMGIS
21.8.28
kmltools
3.1.16
MapsPrinter
0.9
mmqgis
2021.9.10
MultipleLayerSelection
2.0
nominatim
1.4.2
openlayers_plugin
2.0.0
OSMDownloader
1.0.3
qgis2web
3.16.0
QRectangleCreator
0.3
QuickOSM
2.0.1
QuickPrint
3.6.1
quick_map_services
0.19.29
wfsclient
0.9.11
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Try with a new profile please

**Comment by Elkahuna83** [comment]
ok. I had no idea that I used a user profile.
Do you have a tutorial page where I can look up how to create the new profile?

**Comment by Elkahuna83** [comment]
Ah ok sry. found the settings. i will try with a new profile. I have been using the default profile all this time.

**Comment by Elkahuna83** [comment]
I have now created a new profile. All additional plugins are inactive. At first everything worked wonderfully. I could even merge about 60 temp layers at once. But then after about 30min it started again that QGIS crashes when merging.

Now I don't know what to do. I will now create a maximum of 10 temporary layers and then merge them. 

Unfortunately I have the problem already since the version LTE 3.16.

Do you have maybe another idea?

Translated with www.DeepL.com/Translator (free version)

**Comment by Elkahuna83** [comment]
## User Feedback

The same again. I have reinstalled QGIS over the OSGeo4W_Qgis.
QGIS closes with an error message when running the Merge Vector Layers tool.
The program stops responding and hangs.

Even if I only want to merge 2 temporary layers the error comes.

QGIS runs just 5 minutes.

## Report Details

**Crash ID**: [f952c03d3d8c0ccfce3d423f5fe11f006532a31f](https://github.com/qgis/QGIS/search?q=f952c03d3d8c0ccf
ce3d423f5fe11f006532a31f&type=Issues)


**Stack Trace**
<pre>
QMimeType::staticMetaObject :
QgsMapCanvas::
setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QObject::qt_static_metacall :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QObject::qt_static_metacall :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QObject::qt_static_metacall :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgsProject::addMapLayer :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForCompletion :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: c27231782f
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000
![Screenshot 2022-04-01](https://user-images.githubusercontent.com/102652584/161273469-4dbe8b2c-4b46-4445-a136-c4f9c5a0d56d.png)

**Comment by Elkahuna83** [comment]
Hi, 
I have now done the following.
Completely uninstalled QGIS. All remaining folders deleted by hand. Restarted the computer. 
Then installed the current LTE Edition 3.22.5 using the installation software OSGew4W_Qgis.

At first there was no improvement. Again the crashes.
But...
After I have also created a completely new profile and have checked that no foreign plugins are activated, QGIS runs now for several hours without errors. 

I leave it for now so. 

Translated with www.DeepL.com/Translator (free version)
