### ISSUE TITLE
QGIS 3.24.1 (Windows) destroys my VRT raster mosaic

### ISSUE THREAD

**Issue by cxcandid** [qgis/QGIS#48052]
### What is the bug or the crash?

I'm using a very big VRT raster file to merge thousands of single band DEM files into one raster mosaic.
Everything works fine until I change the default rendering of my VRT layer (i.e. to Hillshade or Pseudocolor) and close the QGIS project. QGIS immediately clears the VRT file (file size 0 KB). The same effect happens when I remove the VRT layer from the project after changing the default rendering.

### Steps to reproduce the issue

see bug description above.

### Versions

QGIS-Version
3.24.1-Tisler
QGIS-Codeversion
5709b824
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.1
PROJ-Version
8.2.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.37.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here is an excerpt from my VRT file:

```
<VRTDataset rasterXSize="152501" rasterYSize="87566">
  <SRS dataAxisToSRSAxisMapping="2,1">PROJCS["MGI / Austria GK Central",GEOGCS["MGI",DATUM["Militar-Geographische_Institut",SPHEROID["Bessel 1841",6377397.155,299.1528128,AUTHORITY["EPSG","7004"]],AUTHORITY["EPSG","6312"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4312"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",13.3333333333333],PARAMETER["scale_factor",1],PARAMETER["false_easting",0],PARAMETER["false_northing",-5000000],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Northing",NORTH],AXIS["Easting",EAST],AUTHORITY["EPSG","31255"]]</SRS>
  <GeoTransform> -4.3750250000000000e+04,  1.0000000000000000e+00,  0.0000000000000000e+00,  3.6200025000000000e+05,  0.0000000000000000e+00, -1.0000000000000000e+00</GeoTransform>
  <VRTRasterBand dataType="Float32" band="1">
    <NoDataValue>-999</NoDataValue>
    <ColorInterp>Gray</ColorInterp>
    <ComplexSource>
      <SourceFilename relativeToVRT="0">\\myserver\DHM\Land_OOE_OpenDHM\G-T4133-06.tif</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="2501" RasterYSize="2001" DataType="Float32" BlockXSize="256" BlockYSize="256" />
      <SrcRect xOff="0" yOff="0" xSize="2501" ySize="2001" />
      <DstRect xOff="0" yOff="32000" xSize="1250.5" ySize="1000.5" />
      <NODATA>-999</NODATA>
    </ComplexSource>
    ...
    ...
    <ComplexSource>
      <SourceFilename relativeToVRT="0">\\myserver\DHM\Land_SLZBG_OpenDHM\DHM\dgm_50339.tif</SourceFilename>
      <SourceBand>1</SourceBand>
      <SourceProperties RasterXSize="15001" RasterYSize="10001" DataType="Float32" BlockXSize="256" BlockYSize="256" />
      <SrcRect xOff="0" yOff="0" xSize="15001" ySize="10001" />
      <DstRect xOff="18750" yOff="49500" xSize="15001" ySize="10001" />
      <NODATA>-999</NODATA>
    </ComplexSource>
  </VRTRasterBand>
</VRTDataset>
```

**Comment by cxcandid** [comment]
Unfortunately, QGIS 3.26.1 (Windows) is still a VRT killer 🙁

**Comment by rouault** [comment]
I can't replicate with QGIS and GDAL master on Linux

**Comment by cxcandid** [comment]
I upgraded my QGIS to version 3.26.3 (Windows 64), created a new profile without plugins, and the problem still occurs. When I remove the raster layer, the VRT file is always destroyed (0 KB) and QGIS seems to hang. I realized that it doesn't matter if I change the rendering before or not. Why does QGIS (Windows) open the VRT file in read/write mode?

**Comment by rouault** [comment]
I believe I know what happened. This is related to VRT files with ComplexSource with NODATA members, and the sources being in a "slow" file system. GDAL fix in https://github.com/OSGeo/gdal/pull/6426 that will be available in 3.5.3

**Comment by cxcandid** [comment]
@rouault I'm very sorry, but unfortunately the issue persists in QGIS 3.28.0 Windows (GDAL/OGR 3.5.2).
My VRT file references 4798 single band TIF (DEM) files on a file server using UNC pathes. The VRT size is 2240 KB.
As soon as I enable the layer, change the rendering to "Hillshade" and remove the layer afterwards, the size of the VRT file changes to 0 KB. Looks like it's only a matter of changing the rendering style to "Hillshade" in QGIS.

**Comment by rouault** [comment]
> but unfortunately the issue persists in QGIS 3.28.0 Windows (GDAL/OGR 3.5.2).

totally expected, given that the fix will only be available in 3.5.3 that should be released today

**Comment by cxcandid** [comment]
@rouault thank you for clarification! ...arrg, reading for sense sometimes helps 😊

**Comment by cxcandid** [comment]
@rouault upgrading GDAL/OGR to version 3.5.3 keeps my VRT file alive... thanks a lot! But it also changes the content of the file (original size: 2240 KB, new size: 1747 KB). Why does GDAL not leave the original VRT as it is?

**Comment by cxcandid** [comment]
Last question: what happens if I do not have write permissions to the VRT file?

**Comment by rouault** [comment]
> Last question: what happens if I do not have write permissions to the VRT file?

it should remain unchanged : QGIS+GDAL can't do magic :-)

**Comment by cxcandid** [comment]
@rouault GDAL/OGR is full of magic for me! 😁 ... and I bow down to you magicians! ✨🧙‍♂️
Thanks for your endless effort!!
