### ISSUE TITLE
This feature "Generate XYZ tiles" display different levels of tiles

### ISSUE THREAD

**Issue by xdsking** [qgis/QGIS#48053]
### What is the bug or the crash?

This feature has  bugs,toolbox->Raster tools->Generate XYZ tiles ,display different levels of tiles
![image](https://user-images.githubusercontent.com/9930104/161242493-9d9c7677-f703-448c-a890-f4d8c4885d77.png)

![image](https://user-images.githubusercontent.com/9930104/161242256-2770ff18-79c3-4e38-ab3c-698c76293e14.png)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/9930104/161242764-b3e8a882-78e5-4fc2-9da2-c75c097196a0.png)

### Versions

v3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by enzedrailmaps** [comment]
I'm finding your query difficult to understand. You have selected zoom levels 8 to 14, This will generate folders 8, 9, 10, 11, 12, 13 and 14 in your directory as shown in the screen dump, these folders correspond to the range of zoom levels selected.
