### ISSUE TITLE
Crush during indexing big file

### ISSUE THREAD

**Issue by LevashevIlia** [qgis/QGIS#48079]
## User Feedback

I wanted to measure distance beetween two points (layer is very massive - 346Mb GeoPackage with near the 89K features). I clicked on the measure tool, when indexing starts QGIS crashed

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x0005bc48 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

### Steps to reproduce the issue

Unfortunately I can`t share confidential data, but the way looks like below:
1. Load layer, which is very large (89К features,  346Mb GeoPackage)
2. Activate Measure tool
3. See error

### Versions

**QGIS Info**
QGIS Version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19041

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@LevashevIlia Can you replicate the crash using the same data, but with a new Profile?

**Comment by LevashevIlia** [comment]
I don`t know why but now it works, i didn`t make new profile
