### ISSUE TITLE
SAGA Next Gen >> Terrain Analysis - Hydrology >> Upslope area failure in QGIS 3.25.0-Master rev b25d09b838

### ISSUE THREAD

**Issue by fgfletcher** [qgis/QGIS#48083]
### What is the bug or the crash?

SAGA Next Gen >> Terrain Analysis - Hydrology >> Upslope area fails to run, log:

QGIS version: 3.25.0-Master
QGIS code revision: b25d09b838
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
SAGA Next Gen version: 0.0.7
Algorithm started at: 2022-04-04T11:42:29
Algorithm 'Upslope area' starting…
Input parameters:
{ 'AREA' : 'TEMPORARY_OUTPUT', 'CONVERGE' : 1.1, 'ELEVATION' : '/Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif', 'METHOD' : 0, 'SINKROUTE' : None, 'TARGET' : None, 'TARGET_PT_X' : 960530.668, 'TARGET_PT_Y' : 89712.55 }

ta_hydrology "Upslope Area" -TARGET_PT_X 960530.668 -TARGET_PT_Y 89712.55 -ELEVATION "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/bfa3440cda4d4a42a28e96a164b9c77e/NEDDEMWangLiu.sgrd" -METHOD 0 -CONVERGE 1.1 -AREA "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/19d3836e2e564c848d5dff1997716b26/AREA.sdat"
____________________________
##### ## ##### ##
____________________________
SAGA Version: 7.8.2

Error: tool needs graphical user interface [Upslope Area]
/Applications/QGIS-Dev_3_25_0_2022_03_27_nightly.app/Contents/MacOS/bin/saga_cmd: line 9: 20701 Segmentation fault: 11 "$THISDIR/_saga_cmd" "$@"
Execution completed in 1.62 seconds
Results:
{'AREA': '/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/19d3836e2e564c848d5dff1997716b26/AREA.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• /private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/19d3836e2e564c848d5dff1997716b26/AREA.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

===============================================
The "old" version does run (same DEM, same X,Y starting point):
    SAGA >> Terrain Analysis - Hydrology >> Upslope area; log:

QGIS version: 3.25.0-Master
QGIS code revision: b25d09b838
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
SAGA version 7.8.2 is not officially supported - algorithms may encounter issues
Algorithm started at: 2022-04-04T11:44:38
Algorithm 'Upslope area' starting…
Input parameters:
{ 'AREA' : 'TEMPORARY_OUTPUT', 'CONVERGE' : 1.1, 'ELEVATION' : '/Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif', 'METHOD' : 0, 'SINKROUTE' : None, 'TARGET' : None, 'TARGET_PT_X' : 960530.668, 'TARGET_PT_Y' : 89712.55 }

ta_hydrology "4" -TARGET_PT_X 960530.668 -TARGET_PT_Y 89712.55 -ELEVATION "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/e463d51484d646b0a61ee8b9eb92b8e5/NEDDEMWangLiu.sgrd" -METHOD 0 -CONVERGE 1.1 -AREA "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/85c3448dc85f4221a28ce8684aab1be8/AREA.sdat"
____________________________
##### ## ##### ##
____________________________
SAGA Version: 7.8.2
____________________________
library path: /Applications/QGIS-Dev_3_25_0_2022_03_27_nightly.app/Contents/MacOS/lib/saga/
library name: libta_hydrology
library : ta_hydrology
tool : Upslope Area
identifier : 4
author : O.Conrad (c) 2001
____________________________

Loading grid: /private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/e463d51484d646b0a61ee8b9eb92b8e5/NEDDEMWangLiu.sgrd...

Parameters
Grid System: 29.682447; 2005x 2669y; 930582.875034x 56376.711924y
Target Area: <not set>
Target X coordinate: 960530.668000
Target Y coordinate: 89712.550000
Elevation: NEDDEMWangLiu
Sink Routes: <not set>
Upslope Area:
Method: Deterministic 8

/Applications/QGIS-Dev_3_25_0_2022_03_27_nightly.app/Contents/MacOS/bin/saga_cmd: line 9: 21110 Segmentation fault: 11 "$THISDIR/_saga_cmd" "$@"
Execution completed in 20.77 seconds
Results:
{'AREA': '/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_LikeNg/85c3448dc85f4221a28ce8684aab1be8/AREA.sdat'}

Loading resulting layers
Algorithm 'Upslope area' finished

### Steps to reproduce the issue

select projected DEM
record X,Y coords of starting point (Strahler)
SAGA Next Gen >> Terrain Analysis - Hydrology >> Upslope area
enter X, Y coords,  select Method = Deterministic 8
Run

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.25.0-Master | QGIS code revision | b25d09b838
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS High Sierra (10.13)
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
VectorBender | 0.2.1
AzimuthMeasurement | 0.2.2
rectanglify | 1.0.3
MagneticDeclination | 2.3.1
GarminCustomMap | 3.3
BezierEditing | version 1.3.2
ViewshedAnalysis | 1.7
processing_saga_nextgen | 0.0.7
mask | 1.10.2
TerrainShading | 0.9.4
spline | 0.2
MemoryLayerSaver | 4.0.4
parcel_plugin | 3.8
valuetool | 3.0.15
shapetools | 3.4.4
mapswipetool_plugin | 1.2
coordinate_capture | 0.2
processing | 2.12.99
sagaprovider | 2.12.99
otbprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.25.0-Master
QGIS code revision
[b25d09b838](https://github.com/qgis/QGIS/commit/b25d09b838)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS High Sierra (10.13)

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
VectorBender
0.2.1
AzimuthMeasurement
0.2.2
rectanglify
1.0.3
MagneticDeclination
2.3.1
GarminCustomMap
3.3
BezierEditing
version 1.3.2
ViewshedAnalysis
1.7
processing_saga_nextgen
0.0.7
mask
1.10.2
TerrainShading
0.9.4
spline
0.2
MemoryLayerSaver
4.0.4
parcel_plugin
3.8
valuetool
3.0.15
shapetools
3.4.4
mapswipetool_plugin
1.2
coordinate_capture
0.2
processing
2.12.99
sagaprovider
2.12.99
otbprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

same problem with QGIS 3.24.0;  log:

QGIS version: 3.24.0-Tisler
QGIS code revision: e6ab9473e0
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
SAGA Next Gen version: 0.0.7
Algorithm started at: 2022-04-04T12:05:49
Algorithm 'Upslope area' starting…
Input parameters:
{ 'AREA' : 'TEMPORARY_OUTPUT', 'CONVERGE' : 1.1, 'ELEVATION' : '/Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif', 'METHOD' : 0, 'SINKROUTE' : None, 'TARGET' : None, 'TARGET_PT_X' : 960530.668, 'TARGET_PT_Y' : 89712.55 }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_GJjrBL/b4a74644ec0c48b1b75c0d77c122ac20/NEDDEMWangLiu.sgrd" -FILES "/Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif"
ta_hydrology "Upslope Area" -TARGET_PT_X 960530.668 -TARGET_PT_Y 89712.55 -ELEVATION "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_GJjrBL/b4a74644ec0c48b1b75c0d77c122ac20/NEDDEMWangLiu.sgrd" -METHOD 0 -CONVERGE 1.1 -AREA "/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_GJjrBL/884542ddb9884c8bacc11756735a0a1c/AREA.sdat"
____________________________
##### ## ##### ##
____________________________
SAGA Version: 7.8.2
____________________________
library path: /Applications/QGIS_3-24_0.app/Contents/MacOS/lib/saga/
library name: libio_gdal
library : io_gdal
tool : Import Raster
identifier : 0
author : O.Conrad (c) 2007 (A.Ringeler)
____________________________

Parameters
Grids: No objects
Files: "/Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif"
Multiple Bands Output: automatic
Select from Multiple Bands:
Transformation: true
Resampling: B-Spline Interpolation
Extent: original

loading: /Users/garth/GPS MASON/DEM_NED/DEM_NED_WangLiu.tif
Driver: GTiff
Bands: 1
Rows: 2005
Columns: 2669

Transformation:
x' = 930568.033800 + x * 29.682447 + y * 0.000000
y' = 135584.323000 + x * 0.000000 + y * -29.682447

loading: DEM_NED_WangLiu
warning: top-to-bottom and left-to-right cell sizes differ.
Difference: 0.000000
using cellsize: 29.682447

_saga_cmd(24769,0x7fffb6cc6380) malloc: *** error for object 0x7f9e17e51340: pointer being freed was not allocated
*** set a breakpoint in malloc_error_break to debug
/Applications/QGIS_3-24_0.app/Contents/MacOS/bin/saga_cmd: line 9: 24769 Abort trap: 6 "$THISDIR/_saga_cmd" "$@"
____________________________
##### ## ##### ##
____________________________
SAGA Version: 7.8.2

Error: tool needs graphical user interface [Upslope Area]
/Applications/QGIS_3-24_0.app/Contents/MacOS/bin/saga_cmd: line 9: 24845 Segmentation fault: 11 "$THISDIR/_saga_cmd" "$@"
Execution completed in 16.72 seconds
Results:
{'AREA': '/private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_GJjrBL/884542ddb9884c8bacc11756735a0a1c/AREA.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• /private/var/folders/bh/s7sjrm_10qq3bg8nswr8jyr80000gn/T/processing_GJjrBL/884542ddb9884c8bacc11756735a0a1c/AREA.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by alexbruy** [comment]
This should be reported to the plugin bugtracker.

**Comment by fgfletcher** [comment]
Problem replicates in QGIS 3.18.3, 3.20.3, 3.22.3, and 3.24.0

I will report to the plugin bugtracker, once I figure out how to do that.
Thanks.
