### ISSUE TITLE
QGIS keeps on crashing when a polygon overlaps with itself.

### ISSUE THREAD

**Issue by blacknightshade** [qgis/QGIS#48100]
### What is the bug or the crash?

Simply QGIS keeps on crashing when a polygon overlaps with itself or, sometimes, when it is snapped with itself.
This issue **occurs always** when there is an intersection in the same polygon.

You can understand that it is pretty frustrating.

Crash ID: [714cdebb4294d246220d704f0aa9214c11d910ad](https://github.com/qgis/QGIS/search?q=714cdebb4294d246220d704f0aa9214c11d910ad&type=Issues)

Stack Trace

QgsGeometryValidator::checkRingIntersections :
QgsGeometryValidator::run :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.0-Hannover
QGIS code revision: 43b64b13f3
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

1 click on vertex tool
2 click on a vertex or on a side of a polygon
3 modify a polygon so that it overlaps with itself

### Versions

Hannover

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@blacknightshade Can you give it a try with one of the newer releases? 3.22.5 or 3.24.1? 3.16 is not supported anymore.

**Comment by blacknightshade** [comment]
Sorry for the delay in replying.
I have installed version 3.22.5 and now everything seems to be ok. No crashes when a polygon touches itself or overlaps with itself. No issues to create a hole nor to divide elements.
Thanks to the staff who created the new version.
