### ISSUE TITLE
Ended unexpectedly after saving 

### ISSUE THREAD

**Issue by HH-LMS** [qgis/QGIS#48101]
### What is the bug or the crash?

When I change field names of a layer and save these, it crashes 95% of the time.

### Steps to reproduce the issue

1. Go to a Layer
2. Choose properties
3. Go to field and edit these, remove and change names
4. Click the pencil above to finish the editing of the fields and save.
5. After saving 95% of the time it crashes and the program is terminated.

### Versions

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00004630 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@henry6210 can you try with a new profile?
