### ISSUE TITLE
"Split Features" tool does't work as supposed with self-intersecting LineStrings

### ISSUE THREAD

**Issue by AdriNicolau** [qgis/QGIS#48115]
### What is the bug or the crash?

When you split a LineString that intersects with itself using the "Split Features" tool, this feature is split on the specified point with the tool but is also split at the self-intersect point. This results in more features that spected.

See the GIF below:

![qgis_split_bug](https://user-images.githubusercontent.com/29370959/162187156-0c95639b-db85-4f32-95df-5b070604ebfd.gif)

### Steps to reproduce the issue

1. Start edition on a LineString vector layer.
2. Use the "Split Tool" from "Advanced Digitalizing Tools"
3. Split a self-intersecting feature from the layer.

### Versions

 QGIS 3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is a very old bug and should be fixed with  #47306

**Comment by AdriNicolau** [comment]
Ty for the answer @uclaros, i'll close this issue then!
