### ISSUE TITLE
Python Console crash

### ISSUE THREAD

**Issue by dmaheswaran1998** [qgis/QGIS#48130]
### What is the bug or the crash?

My code runs fine, but I am trying to loop it and it will crash QGIS 1/2 times sometimes and other twims will work fine.  I am trying to write multiple maps and export them as a loop but qgis continues to freeze and is unable to run the code. The code I ultimately want to run is below. This is through the windows shell ocmmand. It will run for a bit and freeze and will never run to the end. I am using the long-term-release. 

### Steps to reproduce the issue

from qgis.core import *
import pandas as pd
import geopandas as gpd
import pyproj

# sa2=gpd.read_file("C:\\Users\\qgis_data\\SA2\\SA2_2016_AUST.shp")
# sa2["SA2_MAIN16"]=sa2["SA2_MAIN16"].astype(int)
# sa2_attributes=pd.read_csv("C:\\Users\\MAHESWARAND\\Documents\\Public_Housing_Maps\\sa2_2016_ph.csv")
# print(len(sa2))
# print(len(sa2_attributes))
# print(sa2_attributes.head())

 
# Join = sa2.merge(sa2_attributes, left_on='SA2_MAIN16', right_on='sa2_2016')
# print(len(Join))
# Join['sh_o_tdr']=Join['sh_o_tdr'].fillna(0)
# Join['sh_o_td']=Join['sh_o_td'].fillna(0)
# Join['social_housing']=Join['social_housing'].fillna(0)
# Join.to_file('C:\\Users\\MAHESWARAND\\Documents\\SA2_test.shp', driver='ESRI Shapefile')
# print("end")

# del Join
# del sa2
# del sa2_attributes
 
# # Supply path to qgis install location
# QgsApplication.setPrefixPath("C:\Program Files\QGIS 3.24.1", True)

# Create a reference to the QgsApplication.  Setting the
# second argument to False disables the GUI.
qgs = QgsApplication([], True)

# Load providers
qgs.initQgis()

from PyQt5 import QtGui as QtGui
from PyQt5 import QtCore as QtCore
from PyQt5.QtGui import QColor
from PyQt5.QtGui import QFont
from qgis.gui import QgsMapCanvas, QgsLayerTreeMapCanvasBridge, QgsLayerTreeView
from PyQt5.QtCore import QSize
from qgis.core import QgsLayoutItemScaleBar
from qgis.utils import iface

### change print layout name 
# change canvas extent, sentre and scale 

####### melbourne centre co-ordinates and scale: scale : 
#canvas.setCenter(QgsPointXY(145.088,-37.764))

### renaming layer dependinding on name 

#open and execute inside the QGIS environment 
layer = QgsVectorLayer("C:\\Users\\MAHESWARAND\\Documents\\SA2_test.shp",
                               "SA2", "ogr") 
if layer.isValid() is True: 
    print("Layer {} loaded".format(layer.name()))
    print(layer.crs())
    
QgsProject.instance().addMapLayer(layer)

print(layer)

### COLOUR SCHEME, UPPER LIMITS, LEGEND LABELS, LEGEND SUBGROUP TITLE 

field_dict={'sh_o_tdr':{"name": "Social Housing/Total Rented Dwellings", "color": ['#ff8b94', '#ffaaa5', '#ffd3b6', '#dcedc1', '#a8e6cf'], "upper_list": [0.05, 0.075, 0.1, 0.2], "label":["0 - 5%", "5 - 7.5%", "7.5 - 10%", "10-20%", "20% or more"]}, 
"sh_o_td": {"name": "Social Housing/Total Dwellings", "color": ["#D2D2D2", "#BEBEBE", "#EBECF0", "#F5C5C5", "#F1B2B5"], "upper_list": [0.005, 0.01, 0.03, 0.06], "label":["0 - 0.5%", "0.5 - 1%", "1 - 3%", "3 - 6%", "6% or more"]},
"social_hou": {"name": "Total Social Housing","color": ["#490665", "#6a1067", "#880579", "#e514a3", "#e23bbf"], "upper_list": [200, 500, 1000, 1500], "label":["0 - 200", "200 - 500", "500 - 1000", "1000 - 1500", "1500 or more"]},
}

print(field_dict["sh_o_tdr"]["color"])

fld_list=['sh_o_tdr', "sh_o_td", "social_hou"]

for fld in fld_list:

    vals = []
   
    name=field_dict[fld]["name"]

    layer.setName(f"{name}")
    layer = QgsProject.instance().mapLayersByName(f"{name}")[0]

    #### replace null values with 0
    for f in layer.getFeatures():
        if f[fld]==None:
            vals.append(0)
        else:
            vals.append(f[fld])
        
        
    ### coding vals.replace for 
    # If you don't like these colors, change them out for ones you do, using hexcodes,
    # RGB codes etc. as long as the items in this list are valid strings you
    # can pass to a QColor constructor 
    colors =  field_dict[fld]["color"]
    lower=0
    top=sorted(vals)[-1]

    upper_list=field_dict[fld]["upper_list"]
    upper_list.append(top)

    label_list=field_dict[fld]["label"]

    range_list = []

    i=0
    for c in colors:
        cat = [lower, upper_list[i], c]
        print(cat)
        sym = QgsSymbol.defaultSymbol(layer.geometryType())
        sym.setColor(QColor(cat[2]))
    
        rng = QgsRendererRange(cat[0], cat[1], sym, label_list[i])
        range_list.append(rng)
        lower = (upper_list[i])
        i=i+1
    renderer = QgsGraduatedSymbolRenderer(fld, range_list, )
    layer.setRenderer(renderer)
    layer.triggerRepaint()

    #### DICTIONARY OF CAPITAL INCLUDING AUSTRALIA -STATE FOR NOW 

    # canvas.setCenter(QgsPointXY(138.963, -35.060)) (ADELAIDE) scale 440230 
    # canvas.setCenter(QgsPointXY(144.9623,-37.824)) (MELBOURNE), scale 500950
    # canvas.setCenter(QgsPointXY(150.765, -33.765)) (SYDNEY), scale 350342
    # canvas.setCenter(QgsPointXY( 152.893, -27.36)) (BRISBANE) scale 423631

    # canvas.setCenter(QgsPointXY(115.95, -32.09)) (PERTH) scale 257528
    # canvas.setCenter(QgsPointXY(131.566, -12.638)) (DARWIN) scale 1514515

    # canvas.setCenter(QgsPointXY(147.354, -42.887)) (HOBART) scale 175942

    capital_city={"Adelaide": {"centre_coord":[138.963, -35.060], "scale":440230}, "Melbourne": {"centre_coord":[144.9623,-37.824], "scale":500950},
    "Sydney": {"centre_coord":[150.765, -33.765], "scale":350342}, "Brisbane": {"centre_coord":[152.893, -27.36], "scale":423631}, 
    "Perth": {"centre_coord":[115.95, -32.09], "scale":257528}, "Darwin": {"centre_coord":[131.566, -12.638], "scale":1514515},
    "Hobart": {"centre_coord":[147.354, -42.887], "scale":175942},"Australia": {"centre_coord":[133.25, -26.15], "scale":17023254}}

    cap_city_list=[]
    for key in capital_city.keys():
        cap_city_list.append(key)

    for city in cap_city_list:

        #Creating the Print Composer 
        project = QgsProject.instance()         
        manager = project.layoutManager()       
              
        layoutName = f"PrintLayout" #insert chosen layout name here
        layouts_list = manager.printLayouts()
        for layout in layouts_list:
            if layout.name() == layoutName:
                manager.removeLayout(layout) 

        #initializes default settings for blank print layout canvas
        layout = QgsPrintLayout(project)  
        layout.initializeDefaults()  

        layout.setName(layoutName)
        manager.addLayout(layout)
        map = QgsLayoutItemMap(layout)

        #I have no idea what this does, but it is necessary
        map.setRect(20, 20, 20, 20)                                     

        #Move & Resize map on print layout canvas
        #map.attemptMove(QgsLayoutPoint(0, 0, QgsUnitTypes.LayoutMillimeters))

        length_map=297
        width_map=210

        map.attemptResize(QgsLayoutSize(length_map, width_map, QgsUnitTypes.LayoutMillimeters))

        ##### IMPORTANT PARAMTERS

        ### scale 5,10,15,20,25,30

        #this code is key, it links the project to the canvas bridge 
        canvas = QgsMapCanvas()
        print(canvas.scale())
        bridge = QgsLayerTreeMapCanvasBridge(
        project.layerTreeRoot(), canvas)
        bridge.setCanvasLayers()

        centre_x=capital_city[city]["centre_coord"][0]
        centre_y=capital_city[city]["centre_coord"][1]
        scale=capital_city[city]["scale"]

        canvas.setCenter(QgsPointXY(centre_x, centre_y))#CENTRE THE CANVAS POINT WHERE NEEDED (x-coord, y-coord)

        map.setExtent(canvas.extent()) #canvas that is needed 
                
        #sets map extent to current map canvas
        map.setScale(scale) #setting a certain scale

        #set Backjground color 
        map.setBackgroundColor(QColor(173,207,230)) #background color 

        layout.addLayoutItem(map)

        legend=QgsLayoutItemLegend(layout)
        legend.setTitle(f"{city} Area") #set title of Map 
        layerTree=QgsLayerTree()
        layerTree.addLayer(layer)
        legend.model().setRootGroup(layerTree)
        legend.setBackgroundColor(QColor(239,245,250))

        #move and resizing the legend 
        legend.attemptMove(QgsLayoutPoint(5, 10, QgsUnitTypes.LayoutMillimeters))
        legend.attemptResize(QgsLayoutSize(30, 50, QgsUnitTypes.LayoutMillimeters))

        #styling legend title and the different subgroups 
        #chose font style 
        titleFont = QFont("Source Sans Pro", 20)
        newFont = QFont("Source Sans Pro", 10)

        #changing the font of the legend 
        legend.setStyleFont(QgsLegendStyle.Title, titleFont)
        legend.setStyleFont(QgsLegendStyle.Subgroup, titleFont)
        legend.setStyleFont(QgsLegendStyle.SymbolLabel, newFont)
        layout.addLayoutItem(legend)

        #exporting to a pdf/jepg image 
    
        item = QgsLayoutItemScaleBar(layout)
        item.setStyle('Numeric') # optionally modify the style
        item.setLinkedMap(map) # map is an instance of QgsLayoutItemMap
        item.applyDefaultSize()
        layout.addItem(item)

        item.attemptMove(QgsLayoutPoint(0, 190, QgsUnitTypes.LayoutMillimeters))
        item.attemptResize(QgsLayoutSize(48.217, 50, QgsUnitTypes.LayoutMillimeters))

        layerTree=QgsLayerTree()
        layerTree.addLayer(layer)
        legend.model().setRootGroup(layerTree)
        legend.setBackgroundColor(QColor(239,245,250))

        exporter = QgsLayoutExporter(layout)

        #save the pdf in choden path 
        #pdf_name="C:/Users/MAHESWARAND/Documents/Public_Housing_Maps/pink_purple3.pdf"
        #exporter.exportToPdf(f"{pdf_name}", QgsLayoutExporter.PdfExportSettings())
        png_name=f"C:\\Users\\MAHESWARAND\\Documents\\Public_Housing_Maps\\{fld}_{city}.png"
        image_export_settings=QgsLayoutExporter.ImageExportSettings()
        image_export_settings.dpi = 100 #setting dpi 
        # image_export_settings.imageSize = QSize(200, 200) # pixels
        exporter.exportToImage(f"{png_name}", image_export_settings)

    #removing layout

### remove priont layout 

##exit
qgs.exitQgis()

### Versions

QGIS 3.22.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Try to split your script in several elementary code bloc to isolate the issue...

**Comment by dmaheswaran1998** [comment]
As in run a little bit at a time?

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by dmaheswaran1998** [comment]
I was hoping to run the whole thing at once to save time, but all good if that’s the only way

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nicogodet** [comment]
The point is to isolate which line of the script causes the freeze.

Github is not for general help, you can try mailing list or IRC for this.

**Comment by dmaheswaran1998** [comment]
Thanks!

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by nyalldawson** [comment]
You should never create a second instance of QgsApplication when running in the python console. That should only ever be done from standalone scripts.
