### ISSUE TITLE
cp1250 processed as ISO-8859-1 when loading shp

### ISSUE THREAD

**Issue by andrzej-gmt** [qgis/QGIS#48138]
### What is the bug or the crash?

When I load a shp layer, I select manually encoding 1250. First, value 1250 appears in menu twice. Whichever I select, map is loaded as ISO-8859-1 and text attributes are damaged.

### Steps to reproduce the issue

Prepare a shp dataset without *.cpg file.
Select menu Layer ->  Add Layer -> Add Vector Layer
Select encoding 1250, it is repeated twice in menu
Load dataset
Check layer properties, see encoding

![cp1250-1](https://user-images.githubusercontent.com/67877708/162470895-8d0a9ca7-994e-45ab-9171-4bcbf923ddd2.jpg)
![cp1250-2](https://user-images.githubusercontent.com/67877708/162470901-7d91f112-4002-4e1a-9393-b9a91bc66eb7.jpg)
![cp1250-3](https://user-images.githubusercontent.com/67877708/162470903-c13b7b49-fe15-4c38-842b-7975c3fcb182.jpg)
.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.5-Białowieża | QGIS code revision | c2723178
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.5-Białowieża
QGIS code revision
[c2723178](https://github.com/qgis/QGIS/commit/c2723178)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (a52133202070a747277d37ed17c0181372cc6772). Is this still an issue?

**Comment by andrzej-gmt** [comment]
I have tested with Qgis 3.32.3 and 3.28.11. Both versions work correctly for me. Thanks!

**Comment by agiudiceandrea** [comment]
Thanks for checking.
