### ISSUE TITLE
Algorithm output node is placed half outsize model canvas

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#48132]
### What is the bug or the crash?

When adding a "final" Model Output to an algorithm, a new green node will be placed on the model canvas. This node gets placed in the top left corner, half outside the visible model canvas.

I use "asd" as name here:
![image](https://user-images.githubusercontent.com/7661092/162395188-6024b8b6-44c0-4d1e-82bd-98bf660ef532.png)

# master (dd6e83b2fa6)
![image](https://user-images.githubusercontent.com/7661092/162394808-4aec1aef-68e9-48ed-a892-e3bac4aec3b0.png)

# In 3.16 and 3.24 this is fine
![image](https://user-images.githubusercontent.com/7661092/162394843-27d2160f-0059-48ec-a8ce-cbcf6d9751d2.png)

### Steps to reproduce the issue

1. Add a Model Output to a model algorithm
2. Look at where the resulting node is placed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
Compiled against GDAL/OGR | 3.4.0 | Running against GDAL/OGR | 3.5.0dev-673993b9f3-dirty
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.2
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | Arch Linux

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I compiled master myself. 3.16 is from conda-forge. 3.24 is https://archlinux.org/packages/community/x86_64/qgis/. 
The same profile was used for all of them.

Version information for the 3.24 one:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
Compiled against GDAL/OGR | 3.4.0 | Running against GDAL/OGR | 3.5.0dev-673993b9f3-dirty
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.2
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | Arch Linux

</body></html>

**Comment by alexbruy** [comment]
Tested with c69fcd7ed4 and everything works fine. Probably local issue.

**Comment by kannes** [comment]
Doesn't seem to happen for me anymore either in master on Arch or in the Ubuntu nightlies so I guess it was an intermediate issue.

**Comment by kannes** [comment]
Sorry, I spoke too soon and managed to reproduce it again with the nightly 6b426f5f8a on Ubuntu 20.04.4

I think the missing steps were: "create the algorithm node without specifying its final output" and then "open the algorithm node and specify a final output"

**Comment by kannes** [comment]
It also happens with 3.24 on Archlinux if I do it like that.
