### ISSUE TITLE
Do not add `*` at begin of filename when saving script in Python console

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#48139]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/39594821/162476412-a51a2fbb-124a-4720-a45f-b5fd1c84f584.png)

Even if most people would change the filename, you can't save a file with an `*` in its name.

### Steps to reproduce the issue

1. create script in python console and modify it
2. Save as... and press save button
3. You can't cause there is a * in filename

### Versions

3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
I can confirm, with step 1.5: change the script so that the * indicator appears.

**Comment by nicogodet** [comment]
@kannes Right I forgot to mention that ! First comment fixed. Thank you !

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/blob/2ce495f4391079e61de7d7a19ce083cb6e3cc1a2/python/console/console.py#L710
to
```python
  fileName = self.tabEditorWidget.tabText(index).replace('*', '') + '.py' 
```

https://github.com/qgis/QGIS/blob/2ce495f4391079e61de7d7a19ce083cb6e3cc1a2/python/console/console_editor.py#L653-L656
to
```python
 self.path, filter = QFileDialog().getSaveFileName(self, 
                                                   saveTr, 
                                                   os.path.join(folder, self.tw.tabText(index).replace('*', '') + '.py'), 
                                                   "Script file (*.py)") 
```

do the trick

**Comment by agiudiceandrea** [comment]
@nicogodet I can confirm your patches (the first one for "Save As" and the second one for "Save") fix the issue.

**Comment by agiudiceandrea** [comment]
Anyway, also without the parches, when a previously saved script is modified in the Python console editor, then the tab title will correctly contains the leading asterisk but the filename (both with "Save As" and "Save") will not contain such leading asterisk.
May be there is another way to fix the issue, mimicking how it works for a previously saved script?

**Comment by nicogodet** [comment]
When a script is saved, `path` is populated with a valid filename and `tabText(index)` is never called again.
