### ISSUE TITLE
Georeferencer will not run with default output raster name

### ISSUE THREAD

**Issue by Peter-E-Martin** [qgis/QGIS#48149]
### What is the bug or the crash?

The georeferencer throws the error "Transform Failed: Failed to compute GCP transform: Transform is not solvable." when the Output raster file name is left as the default ("[original name]_modified.tif", but runs smoothly when the default is changed. See attached screen grab as example.

![image](https://user-images.githubusercontent.com/76170591/162541568-aa161408-fb60-4e96-9d6f-3f53c284e790.png)

### Steps to reproduce the issue

1. open georeferencer and click open raster, choose file (bug discovered using .png)
2. open settings and select Transformation Parameters; do not change Output raster name in the Output settings box.
3. click "Start georeferencing"

### Versions

QGIS version
3.16.16-Hannover
QGIS code revision
f5778a89df
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
pointsamplingtool; 
profiletool; 
quick_map_services; 
shapetools; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Peter-E-Martin could you please attach the raster image (or a link to download it), the GCPs and specify all the setting of the Georeferencer plugin?
Anyway QGIS 3.16 is no longer maintained.

**Comment by VickyGarnett** [comment]
HI there - I was running a workshop in QGIS yesterday, and lots of my participants were getting this same error message.  They were using 2.36 Buenos Aires.  Is this a known bug, or is there a solution for this?  Thanks :)

**Comment by agiudiceandrea** [comment]
@VickyGarnett @Peter-E-Martin could you please attach the raster image (or a link to download it) and the GCPs and specify all the settings of the Georeferencer plugin?

**Comment by VickyGarnett** [comment]
Hi there - thanks for following up.  That would indeed be incredibly useful if I had that information.  Unfortunately, this was happening on other people's laptop that I don't have access to.  I can only tell you that changing the output file name didn't make a difference.  They were using MacBooks, if that is on any help?  Mind you, so was everyone else in the class, and no one else had this issue. - Thanks 🙂 V
________________________________

**Comment by agiudiceandrea** [comment]
> can only tell you that changing the output file name didn't make a difference

@VickyGarnett, so, probably, the issue experienced by the participants is not the same reported in this bug report.

**Comment by Peter-E-Martin** [comment]
@VickyGarnett @agiudiceandrea Thanks for bringing this back to my attention-- I started a new job soon after reporting this issue and it slipped my mind in the transition. I just tried to reproduce the problem in 3.22 and everything seems to be running well for me now, so I'm going to close the issue.
