### ISSUE TITLE
Adding additional layers to GPKG does not load them correctly

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#48154]
### What is the bug or the crash?

If a layer is added to a geopackage after editing the geopackage (either having just created the .gpkg or having just added a different layer) the layer will not load correctly and will give a layer not found error. If the project is restarted the layers are found and work as expected. Once the the geopackage is no longer functioning any layers added to it from the browser etc can not be found and the geometry type can not be determined. Tried this in both 3.24 and 3.25. I assume that this has something to do with the new no-lock settings on GPKG's (which otherwise has been great!). 

### Steps to reproduce the issue

Create a new project. 
Create a new geopackage with a point layer. 
Create a new temporary point scratch layer. 
Add a point. 
Save layer. 
Make scratch layer permanent by saving it to the geopackage. (or by exporting featers to geopackage)
Saved layer will show a warning that the layer is unavailable and datasource could not be found. If the geopackge already exists this will not occur until you add a second layer.    
Here is a GIF where I add 2 layers to an existing geopackage. 
![geopackage](https://user-images.githubusercontent.com/15817745/162583051-5705cf5d-8046-4489-ab6a-fd4c76350d6c.gif)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.25.0-Master | QGIS code revision | 857c98fb5d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.25.0-Master
QGIS code revision
[857c98fb5d](https://github.com/qgis/QGIS/commit/857c98fb5d)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@baswein does the issue occur also using QGIS 3.22.5 (qgis-ltr 3.22.5-2 OSGeo4W package) with GDAL 3.4.2?

**Comment by agiudiceandrea** [comment]
I can confirm the issue using the following versions of QGIS on Windows 10 from OSGeo4W:

3.24.1 (qgis 3.24.1-2) build with GDAL 3.4.2
3.25.0-Master build with GDAL 3.4.2
3.22 nightly (qgis-ltr-dev 3.22.5-87-2ee7f31f) build with GDAL 3.4.2

The issue does not occur using the following versions of QGIS on Windows 10 from OSGeo4W:

3.24.1 (qgis 3.24.1-1) build with GDAL 3.4.1 and running either with GDAL 3.4.1 or GDAL 3.4.2 runtime
3.25.0-Master build with GDAL 3.4.1 and running either with GDAL 3.4.1 or GDAL 3.4.2 runtime
3.22.5 (qgis-ltr either 3.22.5-1 or 3.22.5-2) build with GDAL 3.4.2

So, I think the assumption that the issue is related to #47098 could be correct.

This issue will occur in the forthcoming QGIS 3.22.6 LTR version if build against GDAL 3.4.2 (as it is now in OSGeo4W repository).
