### ISSUE TITLE
GoTo locator broken in EPSG:4326?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#48153]
### What is the bug or the crash?

Hi, trying to update https://github.com/qgis/QGIS/pull/46028/ to include some new code additions:

https://github.com/qgis/QGIS/commits/master/src/app/locator/qgsgotolocatorfilter.cpp
(@nirvn if I am right to respect crs ordering and other epsg:4326 related things?)

I thought to start from master again and add my code (had troubles merging)...

But: to me it looks like something is broken now?

The GoTo locator is not going to the right position anymore? At least not in a EPSG:4326 project

And using - signs in the numbers also creates havoc

### Steps to reproduce the issue

Create Fresh profile in QGIS master
(I have an US/english locale/setting)

Open a new map EPSG:4326 and add 'world' to it

Move over the map (and notice that in the Coordinate input, for example in The Netherlands (around lat 52 lon 5) indeed you now see 52.xx, 5.xx instead of 5.xx, 52,xx in earlier QGIS versions)

Now in the locator: type '52 5' (lat lon now)
You will see 'Go To 52*N 5*E (EPSG:4326 WGS84)' but the little flashing geometry shows somewhere around 0, 0 ?
(instead popping up in The Netherlands)

Another observation: type '-52 5'  (lat lon now)
And you will  see: 'Go To -52*N 5*E (EPSG:4326 WGS84)' but the little flashing geometry shows somewhere around 0, 0 ?
(is that possible? To go -52*N ?)

Now (using the world map is OK, only looking a little funny)
Change your project crs to EPSG:28992 (dutch national CRS)
And type: 150000  450000  (x,y)
You will see: 'Go To 150000E 450000N (Map CRS, EPSG:28992)'
The flashing geom is ok now, but should the E and N show in such crs's?

Doing the same in an older QGIS still works OK.

@nirvn in my PR I also added code to the GoTo locator, which made that if you ask for a coordinate OUTSIDE of the extent of a crs, that it is actually ignored/not shown, I think that is a good addition also?
Would it be an option, to first pull my PR and then fix the things you want to be fixed in the GoTo locator?

### Versions

Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nirvn** [comment]
Hey @rduivenvoorde , just letting you know I've seen this, will have a look at it tomorrow. If I forget, please ping me on the matrix channel.

**Comment by rduivenvoorde** [comment]
Thanks, no rush. As said: in the PR @nyalldawson also asked met to change the logic so there were no 2 lookalike code parts anymore (so I merged that in one). As said: I'm eager to first pull my part and then try to add your work on top, not sure if that is ok with you?
