### ISSUE TITLE
Layer styling window issue

### ISSUE THREAD

**Issue by forrayferenc** [qgis/QGIS#48167]
### What is the bug or the crash?

The "Layer Styling Panel" elements of the Tabs (properties like Information, Source, Symbology ...) are not visible, just ~75% of the icons.
![Capture](https://user-images.githubusercontent.com/103416971/162706617-0a236032-31e7-4105-98da-15216564dbba.PNG)

### Steps to reproduce the issue

Right-click on the menu ribbon and chose from "Panels" the "Layer Stylin Panel".
The tabs just show 75% of the icons and not the text, despite trying to adjust the left margin to accommodate the information.

### Versions

3.24.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Some more information on reproducing this is required -- it's not reproducible on most installs. Do you have any non-standard scaling/dpi/font sizing set on your Windows install?
