### ISSUE TITLE
Unable to open ECW in 3.24.1

### ISSUE THREAD

**Issue by jbell6** [qgis/QGIS#48174]
### What is the bug or the crash?

I can't open an ecw. I created a fresh user profile and had the same problem. I can't open ECWs. It works in 3.16.16.

### Steps to reproduce the issue

Attempted to open an ecw.

Received error "not a valid or recognised data source"

### Versions

QGIS version
3.24.1-Tisler
QGIS code revision
5709b824
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
How did you install QGIS ?

**Comment by jef-n** [comment]
gdal-ecw not installed?
