### ISSUE TITLE
Aborted inserts in Postgis geometryless tables are saved anyway

### ISSUE THREAD

**Issue by dd-a** [qgis/QGIS#48171]
### What is the bug or the crash?

Hi,
I have a project with many PostGIS tables, including relations, and I activated the option to automatically create transaction groups in the project properties.  If I start to edit a table without geometry with the intention to insert a new item in it, but then decide to quit the edition mode without saving the changes, the item is nevertheless saved in the table.  I can remove it afterward by editing the table again and deleting it.

AFAIK this does not happen with the "create transaction groups" not activated, or on a layer with a geometry.  

### Steps to reproduce the issue

1. Select a Postgis layer without geometry
2. Open the attribute table
3. Click on the yellow pen
4. Click on the icon to add an entity
5. write something in the required attribute
6. Click on the yellow pen
7. Choose 'Don't save'. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.5-Białowieża | Révision du code | 2a0a86f142
-- | -- | -- | --
Version de Qt | 5.14.2
Version de Python | 3.8.7
Version de GDAL/OGR | 3.2.1
Version de Proj | 6.3.2
Version de la base de données du registre EPSG | v9.8.6 (2020-01-22)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.31.1
Version du client PostgreSQL | 12.3
Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.4
Version de l'OS | macOS High Sierra (10.13)
  |   |   |  
Extensions Python actives
SpreadsheetLayers | 2.0.1
save_attributes_processing | 0.1
go2streetview | 8.3
Assisted-MapMatching | 1.1
DataDrivenInputMask | 2.4.3
freehandEditing3 | version 1.1.0
trackable_project_files | v1.2.2
qgis_hats | 1.8
oneatlas-qgis-plugin-1_0_1 | 1.3.0
toggle_labels_widget | 1.0.2
quick_map_services | 0.19.29
track_profile_2_web | 1.3
save_attributes | 0.1
qdraw | 3.0.2
Discovery | 2.5.7
buienradar_plugin | 1.4
GeoCoding | 2.18
ImportPhotos | 3.0.3
MagicWand-master | 1.3.1
pluginbuilder3 | 3.2.1
HCMGIS | 21.8.28
latlontools | 3.6.3
AutomaticBackup-master | 1.0
processing_r | 3.1.1
relation_batchinsert | 0.3.2
Qgis2threejs | 2.7.1
OSMDownloader | 1.0.3
searchlayers | 3.0.7
profiletool-master | 4.1.6
report | 1.0.0
AutoLayoutTool | 1.1
postgis_geoprocessing | 0.9
plugin_reloader | 0.9.1
raster_tracer | 0.3.2
autoSaver | 2.6
mmqgis | 2021.9.10
layerfromclipboard | 0.12
MultiEdit | 1.1
Mergin | 2022.1
nominatim_locator_filter | 0.2.4
InvisibleLayersAndGroups | 2.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
LoadQSS | 1.4.2

</body></html>Version de QGIS
3.22.5-Białowieża
Révision du code
[2a0a86f142](https://github.com/qgis/QGIS/commit/2a0a86f142)
Version de Qt
5.14.2
Version de Python
3.8.7
Version de GDAL/OGR
3.2.1
Version de Proj
6.3.2
Version de la base de données du registre EPSG
v9.8.6 (2020-01-22)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.31.1
Version du client PostgreSQL
12.3
Version de SpatiaLite
4.3.0a
Version de QWT
6.1.4
Version de QScintilla2
2.11.4
Version de l'OS
macOS High Sierra (10.13)

Extensions Python actives
SpreadsheetLayers
2.0.1
save_attributes_processing
0.1
go2streetview
8.3
Assisted-MapMatching
1.1
DataDrivenInputMask
2.4.3
freehandEditing3
version 1.1.0
trackable_project_files
v1.2.2
qgis_hats
1.8
oneatlas-qgis-plugin-1_0_1
1.3.0
toggle_labels_widget
1.0.2
quick_map_services
0.19.29
track_profile_2_web
1.3
save_attributes
0.1
qdraw
3.0.2
Discovery
2.5.7
buienradar_plugin
1.4
GeoCoding
2.18
ImportPhotos
3.0.3
MagicWand-master
1.3.1
pluginbuilder3
3.2.1
HCMGIS
21.8.28
latlontools
3.6.3
AutomaticBackup-master
1.0
processing_r
3.1.1
relation_batchinsert
0.3.2
Qgis2threejs
2.7.1
OSMDownloader
1.0.3
searchlayers
3.0.7
profiletool-master
4.1.6
report
1.0.0
AutoLayoutTool
1.1
postgis_geoprocessing
0.9
plugin_reloader
0.9.1
raster_tracer
0.3.2
autoSaver
2.6
mmqgis
2021.9.10
layerfromclipboard
0.12
MultiEdit
1.1
Mergin
2022.1
nominatim_locator_filter
0.2.4
InvisibleLayersAndGroups
2.2
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
LoadQSS
1.4.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

It is the same with QGIS 3.24.1

**Comment by Pedro-Murteira** [comment]
@dd-a Did you try with a new profile?

**Comment by dd-a** [comment]
@Pedro-Murteira no, but I tried on another computer, and also on a new project + another DB.  Always the same result.

**Comment by dd-a** [comment]
@Pedro-Murteira Just to confirm that with a new profile the problem is still there.

**Comment by elpaso** [comment]
I'm not sure I can reproduce the issue: what I see here is that the row is not actually added to the DB but it remains in the attribute table, hitting the refresh button it disappears:

![bug_48171](https://user-images.githubusercontent.com/142164/169503128-fecde443-2e86-4ffc-a6c2-fcb1a85c2b17.gif)

This would be a bug on its own but I want to be sure I am not overlooking something.
