### ISSUE TITLE
QGIS Crashes while searching in the expression builder

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#48189]
### What is the bug or the crash?

QGIS segfaults if the *search* widget in the expression builder is cleared and typed into fast enough

### Steps to reproduce the issue

1. add a vector layer
2. use Select by expression to open an Expression Builder dialog
3. type 'asdf' in the search input widget
4. click the input widget's clear button
5. immediately start typing 'asdf' once more
6. kiss your unsaved work goodbye!
7. in case of no crash repeat from step 4

### Versions

master ca5355ac14 on Debian testing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I guess some typing delays and a cooldown should be implemented for the search. I assume it's due to longer search time due to the tags.

**Comment by nyalldawson** [comment]
I can't reproduce this. Is it still an issue?

**Comment by BathoryPeter** [comment]
The issue has gone. It crashed my QGIS many times while working on translating expression strings a month ago, but I cannot reproduce it anymore.

I note I tested it using the nightly build of 30 April, because there is no newer version in Ubuntu PPA.

**Comment by uclaros** [comment]
I can still reliably get the crash in last week's master, on Linux with qt 5.15.2
