### ISSUE TITLE
Preferred Transformation Not Available / Install Grid Shift File - osgb36_xrail84 - ignores file installation

### ISSUE THREAD

**Issue by mussels** [qgis/QGIS#48193]
### What is the bug or the crash?

When changing canvas projection from EPSG:277000 to EPSG:102400 QGIS prompts the user with a Preferred Transformation Not Available dialog. The dialog displays the following message:

The preferred transform between ESRI:102400 - London_Survey_Grid and EPSG:27700 - OSGB36 / British National Grid is not available for use on the system.
This transformation requires the grid file “uk/osgb36_xrail84”, which is not available for use on the system.
Current transform “Inverse of London_Survey_Grid + Ballpark geographic offset from GCS_Xrail84 to OSGB36 + British National Grid” has an unknown accuracy, while the preferred transformation “Inverse of London_Survey_Grid + Inverse of OSGB_1936_To_Xrail84_NTv2 + British National Grid” has accuracy 0.5 meters.

On the same dialog, below the message, within the Install Grid Shift File a button named 'Install uk/osgb36_xrail84 from Folder...'

After pointing to the correct file,  i.e. osgb36_xrail84.gsb , QGIS display the message: The uk/osgb36_xrail84 grid shift file has been successfully installed. Please restart QGIS for this change to take effect.

Restarting QGIS and attempting the same transformation described in the first paragraph above prompts the user with the same identical message as if the installation never happened.

### Steps to reproduce the issue

Soon after QGIS installation the following GSB files need be downloading from UK Ordnance Survey and copied into the appropriate folder:
1. Download:
OSTN02_NTv2.gsb
OSTN15_NTv2_ETRStoOSGB.gsb
OSTN15_NTv2_OSGBtoETRS.gsb
From: https://www.ordnancesurvey.co.uk/business-government/tools-support/os-net/for-developers
Copy into: \\..\QGIS 3.22.4\share\proj\
2. Restart QGIS
3. Change canvas current projection (on-the-fly) to EPSG:27700
4. Change canvas current projection (on-the-fly) to ESRI:102400
5. QGIS displays warning: Cannot use preferred transformation between EPSG:27700 and ESRI:102400
6. On the warning message click 'Details' 
7. QGIS shows the Preferred Transformation Not Available dialog
8. Click Install uk/osgb36_xrail84 from Folder...
9. Find the osgb36_xrail84.GSB file (I can provide this file) and install it.
10. Restart QGIS

Repeating points 3 and 4 should set the ESRI:102400 projection without warning. This is not happening. QGIS is still showing the same warning. When attempting a transformation with data in ESRI:102400 (I can provide) to EPSG:27700 the preferred high accuracy transformation is greyed out and not available. This transformation should be available.

![image](https://user-images.githubusercontent.com/8593836/163003033-f22a8c85-9d5d-4bf0-8db9-833020488fbd.png)

The Select Transformation dialog states: This transformation requires the grid file "uk/osgb36_xrail84", which is not available for use on the system" even though it was supposedly installed earlier.

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 1909

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Transformation from EPSG:27700 to EPSG:4326 to ESRI:102400 works correctly. It works vice-versa too.
The transformation from EPSG:27700 to ESRI:102400 and vice-versa does not. Using the only ballpark transformation available results in an inaccuracy of 162m.
This transformation should work using the supplied files including the supposedly installed grid shift... but it doesn't. Instead QGIS behaves as if the file was never installed. I also tried saving the file directly into \\...\QGIS 3.22.4\share\proj\ folder with no success.
Admittedly this is not a very common transformation. Data in ESRI:102400 is used by the London's Crossrail project (Elizabeth line) i.e. not a lot of people, and CAD/GIS people likely using software other than QGIS. However, I can't see no reason why this shouldn't work in QGIS also.

**Comment by agiudiceandrea** [comment]
Hi @mussels, the dialog windows asks for a file named "osgb36_xrail84", not "osgb36_xrail84.GSB". Please try to rename "osgb36_xrail84.GSB" to "osgb36_xrail84" and try again.

**Comment by mussels** [comment]
Hi @agiudiceandrea, I've just tried renaming it as you suggested (and also resetting the profile) then reinstall it... no joy.
The dialog actually asks for “uk/osgb36_xrail84", and I find that "uk/" a bit puzzling. I cannot rename the file with a "/" in it; I tried creating a "uk/" folder and moving the osgb36_xrail84 file (with or without the file extension).. is still ignored.
"This transformation requires the grid file “uk/osgb36_xrail84”, which is not available for use on the system." and the "Install uk/osgb36_xrail84" sentences in the dialog message both contains "uk/". Perhaps I'm on the wrong trail but I find that strange.

**Comment by mussels** [comment]
@agiudiceandrea  I think you are right, mine it's more of a work-around, not a fix. I can confirm the workaround works with both the proj directory in the installation path and the user profile (I tried that individually ).
But the problem seems to be in the definitions somewhere. I cannot find such definition, not even in the srs.db file. This definition is instructing the mechanism to use uk/osgb36_xrail84, which is a path and file. It's odd and unlike all other transformation I've installed.
The instruction/definition should really read osgb36_xrail84.gsb instead of uk/osgb36_xrail84. If that was the case I'm sure the mechanism (which I think is correct) would simply install the osgb36_xrail84.gsb file in the proj folder.

**Comment by agiudiceandrea** [comment]
> But the problem seems to be in the definitions somewhere. I cannot find such definition, not even in the srs.db file

The grid file name is listed in the grid_transformation table of the proj.db SQLite database. As you can see, rhere are other grid files that are supposed to be stored in a subfolder (`portugal/`, `netherlands/`, `uk/`, `spain/`, ...).

**Comment by mussels** [comment]
@agiudiceandrea thank you for pointing me to the proj.db file. Yes, it seems storing in a subfolder is not unique to the xrail transformation. 
I support your suggestion that this seems to be a bug; in particular that the mechanism, for whatever reason, fails to create a folder within the proj folder; it installs the transformation file directly in the proj folder but then when such transformation is used (or attempted to) QGIS is looking for the transformation file in a subfolder and cannot find it.
