### ISSUE TITLE
Geospatial PDF output omitting/skipping features

### ISSUE THREAD

**Issue by Enten-Jaeger** [qgis/QGIS#48194]
### What is the bug or the crash?

When choosing "GeoSpatial PDF" as output option in the Map composer, shape features are not written to the output completely. It almost certainly is caused by "Geospatial", because normal PDF output works fine, as well as TIF output does. I created a shapefile with a lot of vertices (waveform lines) because it obviously happens especially on larger datasets. Small ones might work fine. The "simplify" output option has no effects on the outcome.

### Steps to reproduce the issue

**1. open QGIS and load shapefile
2. choose "Geospatial PDF" as PDF output option
3. compare to my sample PDFs**
[GeoSpatialPDF_output.pdf](https://github.com/qgis/QGIS/files/8475414/GeoSpatialPDF_output.pdf)
[sample_shape.zip](https://github.com/qgis/QGIS/files/8475406/sample_shape.zip)
[nonGeoSpatialPDF_output.pdf](https://github.com/qgis/QGIS/files/8475409/nonGeoSpatialPDF_output.pdf)
[GeoSpatialPDF_output_simplified.pdf](https://github.com/qgis/QGIS/files/8475412/GeoSpatialPDF_output_simplified.pdf)

### Versions

QGIS 3.22 on Windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rduivenvoorde** [comment]
@Enten-Jaeger: I just loaded your pdf in QGIS (my own build on Linux), created a layout which shows all 6 squares, and created both a normal and a geospatial pdf from it, and they look all fine/identical:

[normal.pdf](https://github.com/qgis/QGIS/files/8481231/normal.pdf)
[geopdf.pdf](https://github.com/qgis/QGIS/files/8481229/geopdf.pdf)

If that is different from your results, can you maybe describe more what exactly you are doing when you have this issue?
En describe what exactly is going wrong: are these always the same shapes that are missing? Or is it random, or are the missing shapes always partly on the screen or so?
Currently I cannot reproduce your issue

**Comment by rduivenvoorde** [comment]
Hi, I just tried on a Windows Virtual Machine with current development verson of QGIS (sorry I do not have 3.24 there), and all look fine:

[GeoSpatialPDF_output.pdf](https://github.com/qgis/QGIS/files/8499474/GeoSpatialPDF_output.pdf)

Can you try to create it on another machine?

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (a52133202070a747277d37ed17c0181372cc6772).
