### ISSUE TITLE
metasearch fails to parse CSW getcapabilities from geonetwork 3.8

### ISSUE THREAD

**Issue by landryb** [qgis/QGIS#48201]
### What is the bug or the crash?

`Erreur de recherche : StartTag: invalid element name, line 1, column 2 (<string>, line 1)` message when querying a geonetwork 3.8 instance via csw

### Steps to reproduce the issue

- add a csw catalog using https://ids.craig.fr/geocat/srv/fre/csw (a geonetwork 3.8 instance)
- try searching for 'atmo'
- an error message is shown, the server sees a CSW getcapabilities request and replies correctly to metasearch

### Versions

reproduced with metasearch version bundled with qgis 3.24.1 on OpenBSD

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by landryb** [comment]
i can see that querying netherland's national CSW works, but that's geocat BV and not really geonetwork. the iceland geonetwork instance running 3.11.something works. Querying a locally installed GN4 instance also fails with the same error message.

**Comment by agiudiceandrea** [comment]
@landryb I think you can fix/workaround the issue just setting the "Disable SSL verification" option.

**Comment by landryb** [comment]
> @landryb I think you can fix/workaround the issue just setting the "Disable SSL verification" option.

i dont really see how this would help since the server has a perfectly valid SSL Cert... and no, sadly it doesnt help in my case.

**Comment by agiudiceandrea** [comment]
@landryb, just tested with QGIS 3.22.6 (latest LTR) and it works checking the "Disable SSL verification" option.

**Comment by landryb** [comment]
well damn.. can that be a missing dependency of the plugin ? that makes no sense...

**Comment by agiudiceandrea** [comment]
@landryb it seems to me you could fix the issue just modifying the following lines in yourQGISinstallation/python/plugins/MetaSearch/dialogs/newconnectiondialog.py
https://github.com/qgis/QGIS/blob/5709b824612b70f1eb93c77fc88963ced34a16df/python/plugins/MetaSearch/dialogs/newconnectiondialog.py#L97-L98
```python
            self.settings.setValue('%s/username' % key, conn_username)
            self.settings.setValue('%s/password' % key, conn_password)
```
to
```python
            if conn_username != '':
                self.settings.setValue('%s/username' % key, conn_username)
            else:
                self.settings.remove('%s/username' % key)
            if conn_password != '':
                self.settings.setValue('%s/password' % key, conn_password)
            else:
                self.settings.remove('%s/password' % key)
```
then you need to remove and add again the catalog service entry or edit the existing catalog service entry and just click OK.

**Comment by landryb** [comment]
well.. you're onto something, because indeed this now works. With QGIS not running, i've manually edited the config file to remove those silly empty username/password fields, and after starting QGIS now the search now works.
```
--- .local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini.bak Wed Apr 20 14:05:38 2022
+++ .local/share/QGIS/QGIS3/profiles/default/QGIS/QGIS3.ini     Wed Apr 20 14:06:29 2022
@@ -86,11 +86,8 @@
 UK%20Location%20Catalogue%20Publishing%20Service\url=https://data.gov.uk/csw
 UNEP%20GRID-Geneva%20Metadata%20Catalog\catalog-type=OGC CSW 2.0.2
 UNEP%20GRID-Geneva%20Metadata%20Catalog\url=https://datacore-gn.unepgrid.ch/geonetwork/srv/eng/csw
-disableSSL=true
 ids\catalog-type=OGC CSW 2.0.2
-ids\password=
 ids\url=https://ids.craig.fr/geocat/srv/fre/csw
-ids\username=
 selected=ids
```
are you going to send a PR ? otherwise i can take care of it..

**Comment by landryb** [comment]
@agiudiceandrea thanks, that definitely looks right !

**Comment by agiudiceandrea** [comment]
@landryb don't you experience also the issue reported at https://github.com/qgis/QGIS/issues/48290 navigating trough the search results?
