### ISSUE TITLE
Missing in Shape digitizing toolbar...

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#48206]
### Feature description

If you want to start making a polygon  you klick on "add polygon" then you start with a line and then an arc...
Problem is you have to klick "add polygon" again to do a straight line and that feels strange.

I would suggest putting a button in "shape digitizing toolbar" for straight line.

**Comment by baswein** [comment]
If I am understanding you correctly this already exists - In the advanced editing toolbar there is a button to toggle on and off the curve function. 
Here is a GIF of me drawing a polygon and switching between straight and curve.
![draw with curve](https://user-images.githubusercontent.com/15817745/163211184-10499245-6dfa-4b9f-bb74-d46f4829941c.gif)
