### ISSUE TITLE
Error opening from windows

### ISSUE THREAD

**Issue by oliolijestem** [qgis/QGIS#48235]
### What is the bug or the crash?

Hi, 
When selecting tools or a file from a pop-up Windows window, the program hangs (a circle is spinning) and the following error info pops up:

Crash ID: f7d8a454947fbc2602e837b9fcb168fa73cf03a5

Stack Trace

RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2031
CComActivator::DoCreateInstance immact.hxx:386
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::RefreshOverlayImages :
GetIconOverlayManagerImpl :
CFSFolder::_GetOverlayInfo :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CAutoDestItemsFolder::GetOverlayIndex :
CRegFolder::_GetOverlayInfo :
CRegFolder::GetOverlayIndex :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.11-Hannover
QGIS code revision: 26cc1c762f
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044 

System Windows 10

(Google Translator)

### Steps to reproduce the issue

X

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Wersja QGIS | 3.24.1-Tisler | Rewizja QGIS | 5709b82461
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Wersja QGIS
3.24.1-Tisler
Rewizja QGIS
[5709b82461](https://github.com/qgis/QGIS/commit/5709b82461)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by oliolijestem** [comment]
X

**Comment by jef-n** [comment]
This is probably caused by a windows shell extension (eg. to provide previews for data files of some locally installed software).   But QGIS 3.16 is EOL anyway.
