### ISSUE TITLE
Please help me!! 

### ISSUE THREAD

**Issue by povarenaysol** [qgis/QGIS#48236]
### What is the bug or the crash?

program give me this:
"Unable to save auxiliary storage ('Cannot open /private/var/folders/ry/hgfd5d_n1gd1z670f843z2k80000gn/T/QGIS3.UlDHKt for input')"

### Steps to reproduce the issue

I pressed the button "save"   

### Versions

3.16.10-Hannover

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@povarenaysol Can you try on QGIS 3.22.5 and 3.24.1? 3.16 is no longer being maintained.
