### ISSUE TITLE
Overriding actual defaultProfile setting on QGIS close/quit

### ISSUE THREAD

**Issue by CATER-COM** [qgis/QGIS#48232]
### Feature description

Actually QGIS define defaultProfile in profiles.ini as the loaded profile when QGIS close. If you load specific profile (A) with command line option --profile and quit GGIS after. The next time you will launch QGIS without specifying anything, QGIS will start on A profile instead of default profile. This is not convenient and i can't find anyway to override this behaviour.

I tried to use QgsUserProfileManager methods with "onClose()" macro but there is no effect until you use loadUserProfile ans start new session...

It would be handy to get in QGIS Options "Profile on load when not specified" :
1. Use last profile
2. Use always 'default' profile
3. Use always 'A' profile
4. Use always 'B' profile
6. Ask on load

Number one is the actual behaviour. I won't use some specific .bat .bash in QGIS program or profile as i need an handy way for non tech user when deploying some projects. At least i would like to force "defaultProfile=default " in profiles.ini

The priority would be check if --profile option is set and if not check the setting defined above.

### Additional context

I could make some test but i don't know how to help. I didn't found any informations about profiles.ini and how where the actual behaviour is set. If i loose something and  there is some hidden option to manage this please let me know.

**Comment by agiudiceandrea** [comment]
@CATER-COM, if I've correctly understood your issue, I think you could use the QGIS global settings functionality [qgis_global_settings.ini](https://github.com/qgis/QGIS/blob/master/resources/qgis_global_settings.ini) https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#globalsettingsfile and properly set the `defaultProfile` and the [`overrideLocalProfile`](https://api.qgis.org/api/classQgsUserProfileManager.html#aa7503b3c11828d84fb0b3de0830008a5) options.

**Comment by CATER-COM** [comment]
@agiudiceandrea thank you for your idea, i will try it. I saw e [overrideLocalProfile](https://api.qgis.org/api/classQgsUserProfileManager.html#aa7503b3c11828d84fb0b3de0830008a5) but i wasn't able to understand how to use it. It's not very clear how qgis_global_setting.ini  looks like, but if i understand some other post i should take QGIS3.ini as exemple.

**Comment by geobrun** [comment]
"overrideLocalProfile" works when you open a new QGIS blank instance, but it doesn't work when you open a QGIS project file (.qgs/.qgz). In this case, it seems the "overrideLocalProfile" property is ignored and that QGIS uses the "defaultProfile" specified in "profiles.ini" to load the project file.

**Comment by geobrun** [comment]
Sorry, my mistake... I was opening my QGIS projects with a 3.10 QGIS version instead of a 3.22 version. As the "overrideLocalProfile" property has been defined in the 3.16 QGIS version if I remember well, it seems to work perfectly fine if you use the good QGIS version!

**Comment by CATER-COM** [comment]
@agiudiceandrea your suggestion work fine, however i think the ablility to set default QGIS behaviour in GUI could be nice, because using specific profile on load is only available via CLI parameter or by editing shortcut to send this parameter and changing default proffile in "Appdata  and ini file" isn't user friendly. I can also understand that's not very useful for most peoples in global uses cases.

Choosing specific profile at project level would be maybe better, but the project is read after profile launched :-/
