### ISSUE TITLE
Measure tool with different CRS

### ISSUE THREAD

**Issue by zanollim** [qgis/QGIS#48242]
### What is the bug or the crash?

The CRS of my project is EPSG:25832

if I measure a segment, I notice big difference in distance (meters) between
EPSG:25832
EPSG:3857
EPSG:4326

see the screenshot, the correct measure is 120 meters, not 173

Is it normal? I hope not
Thanks

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/1912915/163683231-fd24ff68-a865-42b6-82f0-c42255f10e8c.png)

### Versions

Tested with 3.22 and 3.24

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Yes this is normal, this is not even a qgis issue.

**Comment by agiudiceandrea** [comment]
@zanollim when you use a very non equidistant CRS like EPSG:3857 or a lat/lon geographic CRS like EPSG:3857, you need to use the ellipsoidal mode measuring if you want to measure the distance between two point on the surface of the spheroid instead on the Cartesian plane of the map.
You will find more info on this subject for example at https://docs.qgis.org/3.22/en/docs/gentle_gis_introduction/coordinate_reference_systems.html and https://docs.qgis.org/3.22/en/docs/user_manual/introduction/general_tools.html#measuring

**Comment by zanollim** [comment]
thanks @agiudiceandrea 
I was missing the parameter "Ellipsoid" in the project's general properties
