### ISSUE TITLE
Depends: qtbase-abi-5-15-2 but it is not installable on Ubuntu Jammy

### ISSUE THREAD

**Issue by RJDan** [qgis/QGIS#48240]
### What is the bug or the crash?

I can't install QGIS on Ubuntu Jammy via the repo. 
Here is the error I get.
```
sudo apt install qgis qgis-plugin-grass
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qgis-providers : Depends: qtbase-abi-5-15-2 but it is not installable
E: Unable to correct problems, you have held broken packages.
```
My qtbase-dev info 
```
qtbase5-dev is already the newest version (5.15.3+dfsg-2).
```

### Steps to reproduce the issue

 Follow the Quickstart instructions for Debian/Ubuntu on the QGIS Installers web page. Note: The Quickstart instructions automatically insert jammy into the sources list.

### Versions

QGIS and OS versions

Ubuntu Jammy 22.04 development
QGIS -- whatever version is on the repo at the time of this post.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I had QGIS installed in a previous release of Ubuntu but I uninstalled it a while a go when migrating to 22.04.

**Comment by jef-n** [comment]
See note in https://qgis.org/en/site/forusers/alldownloads.html#repositories (BTW new release packages will be produces in the next round of nightlies).

**Comment by RJDan** [comment]
Thank you for the reply. 
Can I check that I understand the situation?
I have tried the ppa for ubuntugis stable, unstable,  and testing and none of them work. 
I get some variation of 
```
E: The repository 'https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-testing/ubuntu jammy Release' does not have a Release file.
```

I should either manually install a nightly build or wait for a stable jammy release?

**Comment by ouinouin** [comment]
hi, 
exact same issue here, there is th price of the bleeding edge. (and this reminds us that the packaging system for such desktop apps would gain to tend toward appimage.

**Comment by jef-n** [comment]
> hi, exact same issue here for the normal release or the ltr release, the nightly release seems to generate a correct list of packages to install

yup, the note is there for a reason.   try jammy again.

**Comment by AndKe** [comment]
and almost same issue for Ubuntu 22.10   - but now:
```
The following packages have unmet dependencies:
 qgis-providers : Depends: qtbase-abi-5-15-4 but it is not installable
```

**Comment by edurojasr** [comment]
Same for me in Ubuntu 22.10, I think its just waiting for the next point release as the Note in https://qgis.org/en/site/forusers/alldownloads.html#repositories says.

**Comment by zzhuolun** [comment]
Same problem. I also couldn't install `qgis` with `apt install` on my Ubuntu 22.04 because of broken packages (e.g. `qtbase-abi-5-15-3`). 

I finally installed `qgis` with flatpak: https://flathub.org/apps/org.qgis.qgis
