### ISSUE TITLE
Import Layer Definitions from existing *.qgs *.qgz files

### ISSUE THREAD

**Issue by disarticulate** [qgis/QGIS#48252]
### Feature description

Often when preparing current maps/evaluations, I need to pull in existing layers I'd develop in other layout files.

Currently, the workflow to do this is:
1. Open other project file
2. Save it as a layer definition file
3. Import the layer definition file.

I'd propose the following:
1. Menu item under Layer, beneath "Add from Layer Definition File", add "Add from QGis Project File"
2. Dialog lists layers, and groups
3. Selecting a layer or group would create a 'temporary' layer definition file thats then piped to the "Add from Layer Definition File"

This would make it easier to share layers across files. There's even more functionality you could consider, such as not allowing modifications to these imported layers, etc.

### Additional context

This would make it easier to unify certain types of layers and information

**Comment by alexbruy** [comment]
If I understand correctly this is exactly what embedded layers are for.
