### ISSUE TITLE
QGIS Freeze layer>create layer>new shapefile

### ISSUE THREAD

**Issue by Brokenrock** [qgis/QGIS#48255]
### What is the bug or the crash?

When I try to create a new layer (layer>create layer>new shapefile QGIS freezes and I have to close it using task manager. Downloaded a new version of QGIS still happens. Tried restarting. Tried same workflow in a blank project. Happens every time. Please help!

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/103958121/163854095-85af36bb-d4e3-4122-b36e-50928dd85dc2.png)
layer>create layer>new shapefile
Very simple workflow

### Versions

Version 3.22.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Brokenrock Did you install any plugins after re-installing QGIS? If so, can you try with new profile without any 3rd party plugins?

**Comment by Brokenrock** [comment]
Thanks!
I didn't install any plugins but the plugins I had previously installed automatically showed up in the new version I downloaded. I created the new profile and that resolved the problem. So I guess it was associated with a plugin. Now to figure out which one...

**Comment by Brokenrock** [comment]
For anyone else, to create a new profile:
Open QGIS
Settings>User Profiles>New Profile
