### ISSUE TITLE
white box - tools do not appear 

### ISSUE THREAD

**Issue by tony2sampaio** [qgis/QGIS#48253]
### What is the bug or the crash?

the second time I launch some qgis  #tools/boxes, the icons and menus are not available.
Ex.: the graphical modeler is blank and there is no option to enable algorithms and others

### Steps to reproduce the issue

open the graphic modeler for the second time

### Versions

3.18.0 and 3.22 and upper

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

the issue occour with others tools/boxes
in the second time the box is openned

**Comment by Pedro-Murteira** [comment]
I'm not being to reproduce it. (QGIS 3.22.5 and 3.24.1 on Windows 10)
