### ISSUE TITLE
3.22 LTR Not Responding / Very slow to recover after updating existing query layer 

### ISSUE THREAD

**Issue by bobryegis** [qgis/QGIS#48264]
### What is the bug or the crash?

QGIS does not respond for several minutes after either clicking the Update Layer button **or** closing the Update SQL window.
On exiting the mouse pointer is normal, after approx 7 seconds the application greys out and the title bar adds the standard (Not Responding) text. The mouse cursor changes to busy over the application window. Task manager shows the application as Not Responding, 0% CPU, 258MB memory, 0% Disk, 0% Network.
Application will occasionally recover, most of the time I terminate it after 5 minutes. Example logs below was 19 minutes before it responded, and that query was changing select * from table where session::int >= 163 to session::int >= 159
Occurs with layers in an existing template, layers imported from .qlr or created with the DB Manager. 
Occurs with queries against single tables, single views and multiple tables/views 
Queries can be deleted and recreated with no issue. The layer filter function works fine.

### Steps to reproduce the issue

1 Open DB Manager
2 navigate to PostGIS database
3 Open SQL window
4 Create and execute simple query - select * from table where item_num >= 150
5 load as new layer 
6 Right click on new layer
7 select Update SQL
8 either:
8.1 edit and click update
or
8.2 Close window with X or cancel button
 Application is now unresponsive

### Versions

QGIS version
3.22.5-Białowieża
QGIS code revision
c2723178
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
1.1
Go2NextFeaturePlus
2.10
lasview
version 0.13.3
mmqgis
2021.9.10
nominatim_locator_filter
0.2.4
StreetView
3.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Messages:
2022-04-19T13:16:33     WARNING    Python error : An error has occurred while executing Python code: See message log (Python Error) for more details.
2022-04-19T13:33:25     SUCCESS    Layer Update Success : The SQL layer was updated successfully
Python Log:
2022-04-19T13:16:33     WARNING    Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\db_manager\dlg_sql_window.py", line 342, in loadAsLayerToggled
              self.fillColumnCombos()
              File "C:\PROGRA~1/QGIS32~1.5/apps/qgis-ltr/./python/plugins\db_manager\dlg_sql_window.py", line 543, in fillColumnCombos
              for col in cols:
             TypeError: 'NoneType' object is not iterable

**Comment by bobryegis** [comment]
Updated to 3.22.6 no change to behaviour

**Comment by bobryegis** [comment]
Upgraded to LTR 3.22.6, issue is the same
Downgraded to 3.16.0, issue is not present

**Comment by bobryegis** [comment]
So from your comment in that thread
> Corrected in 3.26.0 :-) but unfortunately not in LTR 3.22.8 :-(
A fix is live in the nightly, but not LTR, correct?

I'll grab 3.26.0 tomorrow to test.

**Comment by bobryegis** [comment]
Tested in 3.26.0

Not Responding / Very slow to recover behavior is not present.

Will wait for next LRT release

**Comment by bobryegis** [comment]
Downloaded and installed LTR 3.22.8. Confirmed behavior is still present.

**Comment by bobryegis** [comment]
LTR 3.22.8 Downloaded and installed. Fix not present

**Comment by bobryegis** [comment]
LTR 3.22.9 Downloaded and installed. Confirmed behavior is still present

**Comment by DelazJ** [comment]
Should be fixed in next point release.

**Comment by josemcorderoc** [comment]
Hi, is this issue fixed? I'm having the same problem both in 3.28.1 ​and 3.22.13 :(
