### ISSUE TITLE
Suggested (simple) usability enhancements for profile tool

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#48286]
### Feature description

Much appreciate the integrated elevation and profile tool functionality being added. As I try it out on an existing, fairly complex mapping project (see out-of-the-box rendering below), a few suggestions to improve usability for projects not designed with elevation in mind from the get-go:

1. When a raster is specified in project properties as being the terrain provider, turn on its layer "provides elevation surface" setting by default.
3. Allow showing the elevation surface in the profile tool even if the terrain provider layer is not being displayed in 2D. In the example, I have a DEM but am not displaying it on the canvas (the 2D map is more useful if terrain is displayed via my constructed vector contour layer and shading from a TRI layer). In the profile (which shows the North Trail feature in the middle of the canvas), it's therefore only showing elevation where the contours are crossed as opposed to using the DEM throughout. Unless I go and "show" the DEM in 2D completely transparently or on the bottom of the stack, just so I can use it in profile plots.
4. Allow specifying a vector layer's Profile chart appearance as "do not display" or symbol as Null. Right now, a lot of the noise on the profile chart below comes from QGIS earnestly plotting presumed elevation from my vegetation polygons, and even the polygons making up the 250m dotted grid on the canvas, all at constant elevation 0 relative to the DEM value at their centroid! Just like raster layers can be set to NOT be providing an elevation surface, it would be helpful if vector layers can be set to not provide (or at least not display as) meaningful elevation info. This is partially addressed by https://github.com/qgis/QGIS/pull/48248 in the queue, but I think in addition it should be a layer-level setting. Basically, don't force me to go through all my layers and figure out conceptually what the elevation clamping, extrusion, and binding settings should be; or fake invisible symbols as a workaround; all just to show my first legible and useful elevation profile.

I recognize these are nice-to-have, not urgent. And that a workaround is to create a 2nd project including only a subset of the layers, those relevant for an elevation profile. But usability would be much enhanced if this is not necessary, and so the profile tool is more easily usable "out of the box".

![example](https://user-images.githubusercontent.com/48919900/164202263-48330642-5868-48bb-9636-703b56fb1097.png)

### Additional context

Testing this out on OSGeo4Win dev master from https://github.com/qgis/QGIS/commit/7119976ece18a81f99e9d1c0a6ad1cf53bfcc3cd

**Comment by nyalldawson** [comment]
> Allow showing the elevation surface in the profile tool even if the terrain provider layer is not being displayed in 2D

That's addressed by https://github.com/qgis/QGIS/pull/48248 -- currently there's a shortcut hack which syncs the profile layers with visible canvas layers, which is removed in the PR
