### ISSUE TITLE
[MetaSerach] QGIS 3.24 and Master: "Search error: list object has no attribute 'toXML'"

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#48290]
### What is the bug or the crash?

Using QGIS 3.24.2 and QGIS 3.25.0-Master (6ea5ffb270) on Windows 10 (OSGeo4W), after a successful search, navigating the search results lead to the following error after the second time the navigation buttons are pressed:
![image](https://user-images.githubusercontent.com/16253859/164258166-da211173-2c6b-4cc6-9d10-81a03beaf8f1.png)
`Search error: list object has no attribute 'toXML'`

https://user-images.githubusercontent.com/16253859/164258229-16d3c9c0-81f3-421d-aa1e-540d3553a7a0.mp4

The issue doesn't occur using QGIS 3.22.6:

https://user-images.githubusercontent.com/16253859/164259597-a8cdd04d-e590-4c3e-8be1-db50d7ddf310.mp4

### Steps to reproduce the issue

with the MetaSearch Plugin
1. select a catalog service and make a search that returns more than 20 (or 2*max) records
2. click on the > Next button
3. click on the > Next button
4. the error window `Search error: list object has no attribute 'toXML'` is displayed

### Versions

QGIS 3.24.2 and QGIS 3.25.0-Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by landryb** [comment]
can confirm the issue with 3.24.1 on OpenBSD. PR #48298 also fixes it here.
