### ISSUE TITLE
Mesh layer spatial indices are not populated -- breaks numerous mesh functionality

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#48292]
### What is the bug or the crash?

Only meshlayer
![image](https://user-images.githubusercontent.com/39594821/164265445-66877f70-eaf1-4925-825b-bfe67609ddc3.png)

With another layer (vector here)
![image](https://user-images.githubusercontent.com/39594821/164265687-960e51d2-75c1-4790-a82d-c049ce431cb2.png)

Profile tool report a falsy 0 elevation 

### Steps to reproduce the issue

1. Load this [geo_malpasset-small.zip](https://github.com/qgis/QGIS/files/8522855/geo_malpasset-small.zip)
2. Try to plot Bottom or Free surface

### Versions

from layer tree PR

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is a deeper underlying issue not related to the elevation profile chart. 

@vcloarec it seems that QgsTriangularMesh mSpatialFaceIndex is **only** ever populated when calling QgsTriangularMesh::update with a coordinate transform set. If I don't need to transform the mesh (ie it's already in the desired crs), then the "// FIND OUT IF UPDATE IS NEEDED" shortcut is triggered and the spatial index is never built anywhere.

Do you have any insights into this code? I'm reluctant to change any of this as I've not familiar with that at all

**Comment by vcloarec** [comment]
hmmm, looking at the data and its format (SELAFIN), first this format does not support Z value on vertices, so in any cases the profile will have always 0 as Z value.

Then, the mesh layer profile should also have 0 value, here we don't have value...

But I don't have the transform issue on my side, everything is OK with `QgsTriangularMesh`.
On my side the profile becomes with Z as NaN value here: https://github.com/qgis/QGIS/blob/a190b2abfa45d39e8beeea003a149938c7bc447e/src/core/mesh/qgsmeshlayerprofilegenerator.cpp#L99

Before this line we have the Z values (0), but after the profile has only NaN value:
![image](https://user-images.githubusercontent.com/7416892/164342890-b2f56243-586d-4b6c-87aa-62029d8e059d.png)

**Comment by nyalldawson** [comment]
@vcloarec 

> But I don't have the transform issue on my side, everything is OK with QgsTriangularMesh.

The issue comes from QgsMeshLayerUtils::interpolateZForPoint -- that calls QgsTriangularMesh::faceIndexForPoint_v2, which always returns -1 because the spatial index is empty (has never been built), so `interpolateZForPoint` returns nan as a result

**Comment by vcloarec** [comment]
> The issue comes from QgsMeshLayerUtils::interpolateZForPoint -- that calls QgsTriangularMesh::faceIndexForPoint_v2, which always returns -1 because the spatial index is empty (has never been built), so `interpolateZForPoint` returns nan as a result

What I have:
![image](https://user-images.githubusercontent.com/7416892/164343887-ad92cc31-95db-4a64-9763-1083c2f9ed42.png)

`heigh == 0` so everything is ok with `QgsMeshLayerUtils::interpolateZForPoint`

**Comment by nyalldawson** [comment]
@vcloarec 

Ah, you're right. Sorry for the noise!
