### ISSUE TITLE
QGIS crashes after enabling map labels

### ISSUE THREAD

**Issue by jose1711** [qgis/QGIS#48302]
### What is the bug or the crash?

When a `.shp` file is opened in QGIS and user enables map labels QGIS crashes with
```
/usr/include/c++/11.2.0/bits/stl_vector.h:1045: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](std::vector<_Tp, _Alloc>::size_type) [with _Tp = int; _Alloc = std::allocator<int>; std::vector<_Tp, _Alloc>::reference = int&; std::vector<_Tp, _Alloc>::size_type = long unsigned int]: Assertion '__n < this->size()' failed.

```

### Steps to reproduce the issue

1. unzip the attached file
2. run `qgis directory_with_the_map_files`
3. double click layer name
4. in Labels dropdown select Single labels - accept the default value (`naz_zuj`)
5. Click OK

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.0
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.2
PDAL version | 2.4.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | Arch Linux
  |   |   |  
Active Python plugins
GpxSegmentImporter | 2.3
openlayers_plugin | 2.0.0
MapsPrinter | 0.5
qgis-maptiler-plugin | 1.1.3
quick_map_services | 0.19.10.1
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
sagaprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.24.1-Tisler
QGIS code branch
[Release 3.24](https://github.com/qgis/QGIS/tree/release-3_24)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.38.2
PDAL version
2.4.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.2
OS version
Arch Linux

Active Python plugins
GpxSegmentImporter
2.3
openlayers_plugin
2.0.0
MapsPrinter
0.5
qgis-maptiler-plugin
1.1.3
quick_map_services
0.19.10.1
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
sagaprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

[hranice_obci.zip](https://github.com/qgis/QGIS/files/8530190/hranice_obci.zip)

**Comment by Pedro-Murteira** [comment]
I'm unable to replicate the crash on QGIS 3.22.6 and 3.24.2 (Windows 10.)

**Comment by nyalldawson** [comment]
I can't reproduce either.

**Comment by jose1711** [comment]
It's still crashing on my system.

**Comment by nyalldawson** [comment]
Could you share a complete project please? It may be related to the font/label settings

**Comment by jose1711** [comment]
[project.zip](https://github.com/qgis/QGIS/files/8714045/project.zip)

Not sure exactly how it's done - I did Project - Save and zipped the result. Is it of any use?

**Comment by elpaso** [comment]
@jose1711 the project is fine but you need to attach the data (a small sample is probably enough) as well or we cannot use it.

**Comment by jose1711** [comment]
@elpaso The data (full file) is attached to the very first post.
