### ISSUE TITLE
Incorrect 3d rendering of extra classes in point cloud

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#48303]
### What is the bug or the crash?

Using this test file: https://github.com/PDAL/data/blob/master/autzen/autzen-classified.laz

Some classes used in that file are not in our hard-coded list of classes - it seems the file also uses class number 0 and 19.

When I add these extra classes to the 2d classified renderer, everything seems to render as expected:

![autzen-classified-2d](https://user-images.githubusercontent.com/193367/164456458-eff7dcbd-e06c-4bc4-a224-d465c781840d.png)

But when I add these extra classes to the 3d classified renderer, the results are not correct:

- class 0 should be red, but it's rendered black
- class 19 should be blue, but it's rendered red

![autzen-classified-3d](https://user-images.githubusercontent.com/193367/164456571-f7f34fac-5d90-4161-a656-a22e93fc4afe.png)

### Steps to reproduce the issue

As described above.

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Probably related: if classified by another attribute (eg. ReturnNumber using hand crafted ept.json stats) then toggling a category in the 3d renderer widget actually toggles visibility of the previous category in the 3d view.
ie: 
uncheck cat 0, nothing happens
uncheck cat 1, points of cat 0 disappear
uncheck cat 2, points of cat 1 disappear
etc

**Comment by NEDJIMAbelgacem** [comment]
This appears to be fixed in https://github.com/qgis/QGIS/pull/48523

**Comment by uclaros** [comment]
It's still there, it only applies to 3D view.
Reordering the classes also messes things up. It seems like the item's index is used somewhere instead of the Value
