### ISSUE TITLE
d002fcac1df61335e20a32e2feb6a04b4ce000d6

### ISSUE THREAD

**Issue by agajj1** [qgis/QGIS#48308]
### What is the bug or the crash?

An error pops up and the program shuts down.

### Steps to reproduce the issue

f

### Versions

QGIS 3.14.0-PiQ

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@agajj1 It's impossible for me and for the devs to try and understand what the ticket is about, the version is also very old and won't receive any updates. Can you make a new ticket regarding the issue?
