### ISSUE TITLE
Mouse wheel does not work when a tooltip is displayed in map canvas

### ISSUE THREAD

**Issue by kadirsahbaz** [qgis/QGIS#48312]
The mouse wheel does not work when a tooltip is displayed in the map canvas. To be able to zoom in/out, I have to move the cursor a little.

![image](https://user-images.githubusercontent.com/15310223/164542661-d09009ec-ad11-435b-b42a-254bebe50d14.png)

### Steps to reproduce the issue

1. Move the cursor over a feature in the active layer.
2. Wait for a tooltip to be displayed.
3. Use the mouse wheel without moving the mouse.

### Versions

QGIS version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Qt version: 5.15.2
Windows 10

**Comment by agiudiceandrea** [comment]
Confirmed also using QGIS 3.16 on Windows with Qt 5.11.2  or Qt 5.15.2.

**Comment by uclaros** [comment]
This is an old issue, the tooltips grab all mouse events. See #33981
There was an attempt to fix this by offsetting the tooltip along the x axis, but that made it impossible for the user to click any links within the tooltip, since it disappeared before the mouse could even enter it.
