### ISSUE TITLE
Problem with the print composer

### ISSUE THREAD

**Issue by achianese** [qgis/QGIS#48326]
### What is the bug or the crash?

I use the print composer to merge the cartographic information (Maps and attribute table frames, legends) of my postgis database and I use the mail merge with the atlas to choose the records to print.
I notice that the moment I click on the atlas icon, the composer becomes particularly slow or even crashes. 
I would like to ask if there is a setting that allows me to speed up the printing process
Thanks

### Steps to reproduce the issue

 
![img](https://user-images.githubusercontent.com/104215768/164746038-3f04d36e-187a-48d5-86ab-fea135c0775f.png)

### Versions

Versione di QGIS
3.22.6-Białowieża
Revisione codice QGIS
b6f33b1a
Versione Qt
5.15.2
Versione Python
3.9.5
Versione GDAL/OGR
3.4.2
Versione PROJ
9.0.0
Versione database del Registro EPSG
v10.054 (2022-02-13)
Versione GEOS
3.10.2-CAPI-1.16.0
Versione SQLite
3.38.1
Versione PDAL
2.3.0
Versione client PostgreSQL
13.0
Versione SpatiaLite
5.0.1
Versione QWT
6.1.3
Versione QScintilla2
2.11.5
Versione SO
Windows 10 Version 2009

Plugins Python attivi
clipper
1.2
excel_sync
3.6
ImportPhotos
3.0.3
kmltools
3.1.17
latlontools
3.6.3
layer2kmz
1.5.3
numericalDigitize
0.4.6
pointsamplingtool
0.5.3
qad
3.0.4
rivergis
3.0
send2google_earth
0.3.1
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@achianese Hello, could you change the title to something more descriptive? Also, you can try to reproduce the process but on a new profile, with the minimum amount of plugins installed, that way we can rule out the possibilty of it being plugin related.

**Comment by achianese** [comment]
I registered a new profile but the situation has not changed. I always register a slowness in making a zoom and the image remains frozen for several seconds. Also I notice that my notebbok's fan increases its speed. (I7 CPU, RTX30 video card, windows 11)

**Comment by katagen** [comment]
I have this when I have a rotation for my map caneva and a north arrow set with zoom and fit?
Cause it's related to https://github.com/qgis/QGIS/issues/37460

Is it your case?

**Comment by achianese** [comment]
No, this is not the problem I have reported. I notice a notable slowdown, even in zooming in on the layout, with atlas when I use a geographic data source from postgis. In the layout I have prepared there are two / three maps and two / three table boxes. I repeat that both the maps and the tables are linked to data that come from postgis

**Comment by Pedro-Murteira** [comment]
@achianese By "registered a new profile", do you mean that on QGIS you went: Settings > User Profiles > New Profile ?

**Comment by roya0045** [comment]
I assume your legend use filter by atlas and maybe not filter by map extent? If so could be related the same bug as #47033

**Comment by achianese** [comment]
> @achianesePer "registrato un nuovo profilo", intendi che su QGIS sei andato: Impostazioni > Profili utente > Nuovo profilo?

yes. I did just that. I selected settings and then registered a new user profile

**Comment by nyalldawson** [comment]
Potentially fixed by https://github.com/qgis/QGIS/pull/48686
