### ISSUE TITLE
Apply guides to all pages crashed QGIS

### ISSUE THREAD

**Issue by defermelowie** [qgis/QGIS#48327]
### What is the bug or the crash?

QGIS crashes after I add 2 new pages to my layout and use" apply to all pages" from guides. The existing pages are containing (the same) guides already

### Steps to reproduce the issue

Add 2 new pages, then apply guides to all pages

### Versions

QGIS Version: 3.22.6-Bia?owie?a

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

## Report Details

**Crash ID**: [0cf00dd68a7d2920dfcd3c0b82ae105419a21116](https://github.com/qgis/QGIS/search?q=0cf00dd68a7d2920dfcd3c0b82ae105419a21116&type=Issues)

**Stack Trace**
<pre>
QgsLayoutGuideCollection::applyGuidesToAllOtherPages :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.6-Bia?owie?a
QGIS code revision: b6f33b1a
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by nyalldawson** [comment]
I can't reproduce. Can you post step-by-step instructions to reproduce this crash?
