### ISSUE TITLE
1f9631ee732fe1c494a262e8ba577ae9da0fdb62

### ISSUE THREAD

**Issue by Simone-Brotto** [qgis/QGIS#48325]
### What is the bug or the crash?

CRASH when quitting.
When I quit QGIS application, it quits but also gives crash messages which are different according to version 3.24.2 or 3.22.6.
It does not matter if I open and work on a project or not. I tried with new profile, same crash messages. I am experiencing this issue from quite some time (I guess something like 6 months). OSGEO4W installation, software updated, Windows 10 PRO.
Please excuse me if there is something wrong in my report, first time reporting.
Best regards, Simone Brotto 

*** CRASH MESSAGE ON QGIS 3.22.6

Crash ID: 1f9631ee732fe1c494a262e8ba577ae9da0fdb62

Stack Trace

GDALDestroyDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.6-Bia?owie?a
QGIS code revision: b6f33b1a
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

*** CRASH MESSAGE ON QGIS 3.24.2

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000015d8 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. launch QGIS
2. eventually open a project
3. quit QGIS
4. CRASH

### Versions

3.22.6 and 3.24.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It looks like a local issue.

Could you try uninstall pcraster and try again ?

**Comment by Simone-Brotto** [comment]
@nicogodet yes it works, thank you!

**Comment by nicogodet** [comment]
If you really need pcraster, consider opening an issue on pcraster repo (if it exists).
