### ISSUE TITLE
Wrong OSM encoding bug

### ISSUE THREAD

**Issue by aflexus** [qgis/QGIS#48328]
### What is the bug or the crash?

BUG.

Some osm-files (overpass api xml response) are being interpreted and opened by QGIS as having ANSI encoding. Even if they have correct utf-8 encoding and correct xml encoding tag in the header.

NOTE: Issue hapens only under Windows environment.

### Steps to reproduce the issue

 - Download an example of osm-response - https://drive.google.com/file/d/1tL-vMOZoHiDODZuIMIi9-ghCur1N9CPI/view?usp=sharing
 - Unpack and open with drag'n'drop or any other way
 - Choose "multipoligons" (anyway there is only one item of this type there)
 - Check cyryllic fields encodings.

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
qgis2web
3.16.0
QuickOSM
2.0.1
quick_map_services
0.19.29
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Happens with the latests 3.24.0 and it's minor versions. But it seems that this bug is present in older major builds like 3.18.0 - https://github.com/3liz/QuickOSM/issues/369

And yes, this issue is related to the QuickOSM plugin but as to me the main reason is QGIS itself. 

Regards.

**Comment by jratike80** [comment]
Seems to work for me with the provided test data on Windows by using drag-and-drop. QGIS version is 3.32.2, installed with OSGeo4W.

<img width="331" alt="image" src="https://github.com/qgis/QGIS/assets/1751612/c2235e75-18f2-469c-afda-74e56d37e7d8">

<img width="182" alt="image" src="https://github.com/qgis/QGIS/assets/1751612/1c12ae62-17e3-401e-985d-62dcb139430e">

**Comment by pathmapper** [comment]
@jratike80 interesting, which encoding do you get when drag-and-drop [test.zip](https://github.com/qgis/QGIS/files/12476543/test.zip)?

**Comment by jratike80** [comment]
UTF-8
<img width="419" alt="image" src="https://github.com/qgis/QGIS/assets/1751612/c5376590-d706-403f-9b35-03b5af7d9862">

**Comment by alexbruy** [comment]
Not reproducible with latest dev build on Windows 10.
![image](https://github.com/qgis/QGIS/assets/776954/218afac5-f5fd-4e2f-9006-142d8c714ac2)
