### ISSUE TITLE
Data Source Manager Filter Bug

### ISSUE THREAD

**Issue by samgalls** [qgis/QGIS#48329]
### What is the bug or the crash?

When you click 'open data source manager' button, try to set a 'filter', click 'ok', and then 'add' the added layer will not be filtered. It appears that after the latest update when you try to add a new filtered layer once you click Ok within the window the filter is wiped. This was not an issue on the previous version.

Caveat: The filters can be changed and successfully applied if you are manipulating an existing filtered layer already in your environment (added using an old version). The issue only occurs when trying to set a filter on a new layer.

### Steps to reproduce the issue

1. Open Data Source Manager
2. Find filterable layer, click 'Set Filter'
3. Enter a query/filter, click test 'shows accurate number of features
4. Click 'ok'
5. Click 'add'
6. The layer inserted into the environment no longer has the entered filter, seems to just disappear.

### Versions

3.24.2-Tisler

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
## I confirm OSGeo4W v2 Win 10 Pro 64b
- QGIS 3.24.2
- MASTER 
- 
![image](https://user-images.githubusercontent.com/7631137/164914054-f704a774-9e5c-4bb5-bed7-27ceaf294480.png)

![image](https://user-images.githubusercontent.com/7631137/164914044-6bcefdb4-4630-42f3-ab07-d69548dffffb.png)
