### ISSUE TITLE
When exporting a 3D animation, terrain tiles go missing on a number of frames

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#48334]
### What is the bug or the crash?

Check this video:

https://user-images.githubusercontent.com/1728657/164850185-c8a9a190-126b-438a-be10-359de5823de7.mp4

You'll notice part of the terrain "flashes" on a number of frames during this video. Here's an example of a few exported frames:

![image](https://user-images.githubusercontent.com/1728657/164851106-1bfd0106-1e68-48d1-bb23-7a921fa9c81b.png)

You can see frame 54 and 64 have tiles missing. It's not random, if I re-export, the same tiles will go missing for the same frames.

Needless to say, it's not great :)

### Steps to reproduce the issue

1. Create a scene of a few square kilometers
2. Set the terrain to be a DEM layer
3. Make a quick flight over the terrain, export animation
4. Notice the tiles going missing on a number of frames

### Versions

QGIS master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nirvn** [comment]
Test project:
[dem.zip](https://github.com/qgis/QGIS/files/8546208/dem.zip)

**Comment by nirvn** [comment]
Still an issue as of today:
![image](https://user-images.githubusercontent.com/1728657/174041586-7b6927a6-868d-4f3c-8a70-c82136fefec7.png)

**Comment by nirvn** [comment]
An extra detail: the blank tiles are actually missing tiles (i.e. you can see the background through the missing tile(s)):
![image](https://user-images.githubusercontent.com/1728657/174426536-6b11dce6-cbc3-4fdd-bcb2-b589682a4ee3.png)

**Comment by nirvn** [comment]
@wonder-sk , your honor, allow me to introduce Lutra's tweet (https://twitter.com/lutraconsulting/status/1582258155584905216) as further evidence of the tiles going missing :wink:

**Comment by wonder-sk** [comment]
Yeah I have seen that flicker too  :see_no_evil:  :grin:
