### ISSUE TITLE
the Python API of Class: QgsUserProfileManager.userProfile() always returns NoneType instead of active user profile

### ISSUE THREAD

**Issue by enrizhou** [qgis/QGIS#48337]
### What is the bug or the crash?

when I call QgsUserProfileManager.userProfile() to get the active user profile, but it always returns NoneType, the version includes  3.22-3 and 3.24

### Steps to reproduce the issue

1 . go to python consol
2. run QgsUserProfileManager().allProfiles() , it returns all user profile names as expected
3. run QgsUserProfileManager().getProfile('default').name(), it also works well
4. but if run QgsUserProfileManager().userProfile().name() , you get "AttributeError: 'NoneType' object has no attribute 'name'"

### Versions

3.22 and 3.24

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you create a new profile and check if it returns None ?

**Comment by nicogodet** [comment]
On my side, `QgsUserProfileManager().allProfiles()` does not return profiles name but list content of working directory

**Comment by enrizhou** [comment]
> Could you create a new profile and check if it returns None ?

Yes, I created another two profiles with names 'user1' and 'user2',  so in my PC running Win10 there are 3 profiles( names are default, user1, user2) , if I use user1 or user2, with  QgsUserProfileManager().allProfiles() I get ['1033', 'gdalplugins'] as result, it is not right and strange. but if I use the 'default' profile, it return ['default', 'user1', 'user2'].

**Comment by ismailsunni** [comment]
> On my side, QgsUserProfileManager().allProfiles() does not return profiles name but list content of working directory

Same as me, tested on Ubuntu. But when I tested on Windows, it returns the list of profiles correctly.

**Comment by ismailsunni** [comment]
@nicogodet ah sorry, I was wrong. I also got the list of directories on Windows. The directories' name was like a profile's name.

**Comment by YoannQDQ** [comment]
There was nothing to fix really... And `QgsUserProfileManager` might still be instantiated, provided one calls it with the correct path, but I agree the documentation would benefit from clearly stating it should be accessed from `iface` instead. I do not know why the constructor `rootLocation` parameter was given a default value, but removing it now would be an API break.

**Comment by kannes** [comment]
Is there any way to get the current user profile if one creates a new instance?

**Comment by YoannQDQ** [comment]
Depends what you're trying to do. 

You can use the following functions to get the current profile name and profile root


```Python
def current_profile_name():
    settings_path = Path(QgsSettings().fileName())
    return settings_path.parent.parent.name

def profiles_root():
    settings_path = Path(QgsSettings().fileName())
    return str(settings_path.parent.parent.parent)
```

You can then init a newly created `QgsUserProfileManager`

```Python
manager = QgsUserProfileManager(profiles_root())
current_profile = manager.profileForName(current_profile_name())
```

You cannot use `QgsUserProfileManager.userProfile` though. Calling setActiveProfile on the manager then accessing userProfile makes QGIS crash.

Unless... Bonus (Hacky solution):

```Python
def user_profile_manager():
    manager = QgsUserProfileManager(profiles_root())
    profile_name = current_profile_name()
    manager._profile = manager.profileForName(profile_name)
    manager.userProfile = lambda:  manager._profile
    return manager

>>> user_profile_manager().userProfile().name()
'default'
```

**Comment by kannes** [comment]
Haha, thanks! I think it sounds safe to say that one should never use it in any normal circumstances but the existing instance is really what one most probably wants. :D
