### ISSUE TITLE
Vector Tiles style converter fails to find font

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#48342]
### What is the bug or the crash?

When adding a Vector Tile layer, some warnings appears regarding missing fonts.

![image](https://user-images.githubusercontent.com/39594821/165034552-6dfc3e2b-cdaf-4070-b249-64c58bc395f3.png)

But these fonts are installed on my system 

![image](https://user-images.githubusercontent.com/39594821/165034656-e024bebd-bd97-460c-ab5d-a56e29820ee5.png)

### Steps to reproduce the issue

1. add this connection [tuiles-vectorielles_gh.zip](https://github.com/qgis/QGIS/files/8333967/tuiles-vectorielles_gh.zip)
2. Add the layer to QGIS
3. See warnings

### Versions

Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Could be linked to https://github.com/qgis/QGIS/issues/44418

**Comment by nyalldawson** [comment]
@nicogodet 

The style URL referenced in that file doesn't exist anymore (https://wxs.ign.fr/static/vectorTiles/styles/PCI/n&b.json )

Are you able to re-test with current master and confirm if this is still an issue?

**Comment by nicogodet** [comment]
@nyalldawson 
I just noticed they removed this black and white style..
I can still reproduce on Master [d73baa680c](https://github.com/qgis/QGIS/commit/d73baa680c) with the below style 
https://wxs.ign.fr/static/vectorTiles/styles/PCI/pci.json

**Comment by nyalldawson** [comment]
Can you point to a location I can find that font?

**Comment by nicogodet** [comment]
Go to 514934 6475733 in EPSG:2154 at scale 1/25000
![image](https://user-images.githubusercontent.com/39594821/175093579-13ee162f-2915-4968-8c4d-284222477b2b.png)

**Comment by nicogodet** [comment]
All font's labels fall back to MS Shell Dlg 2

**Comment by nicogodet** [comment]
And I still had this issue https://github.com/qgis/QGIS/issues/47934 when looking for a location to share

**Comment by nyalldawson** [comment]
I mean I need that TTF font. It's not available anywhere I can find

**Comment by nicogodet** [comment]
Well can't remember where I found it...
[Fonts.zip](https://github.com/qgis/QGIS/files/8973444/Fonts.zip)
An archive with all Sans Serif fonts I have.

Maybe IGN should use a more common font..
