### ISSUE TITLE
[profile tool] Add option to draw a line between points

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#48341]
### Feature description

When sampling a point layer, drawing a line between points could be useful.

![image](https://user-images.githubusercontent.com/39594821/165033152-20a5f432-4600-4caf-a5d5-633f6e807927.png)

**Comment by nyalldawson** [comment]
Snapping works with the profile line tool, isn't that enough?

**Comment by nicogodet** [comment]
This is mainly for visualization purpose. In the above screenshot, points and DEM both represent the terrain but one was surveyed by a surveyor, the other is LiDAR. 
Linking the points with a line would help to visualize and compare the 2 data.

And snapping would only occur on sampled point not on the linking line.

**Comment by nyalldawson** [comment]
I still don't totally understand -- could you post a illustration of what you're referring to?

**Comment by nicogodet** [comment]
Same data, same location
Current
![image](https://user-images.githubusercontent.com/39594821/165231241-7518230a-e594-4475-b836-8efaa7cee337.png)

Desired
![image](https://user-images.githubusercontent.com/39594821/165231461-e64a6ceb-324f-4932-bbdb-f4707b4fff0a.png)

**Comment by nyalldawson** [comment]
Thanks, I completely misinterpreted the request!
