### ISSUE TITLE
Random crash after closing QGIS without opening a project

### ISSUE THREAD

**Issue by shayaknyc** [qgis/QGIS#48366]
### What is the bug or the crash?

Load QGIS 3.22.6 on Windows 10 x64. Close QGIS without loading a project, and it just crashes.

### Steps to reproduce the issue

1. Load QGIS
2. Close QGIS
3. CRASH

### Versions

3.22.6-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

## User Feedback

Just opened QGIS, then just closed it without opening a project, and got this error

## Report Details

**Crash ID**: [f26e947319260720a4bf05ba4d601320801e99fb](https://github.com/qgis/QGIS/search?q=f26e947319260720a4bf05ba4d601320801e99fb&type=Issues)

**Stack Trace**
<pre>
QThread::currentThread :
QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsProcessingToolboxModel::addProvider :
QgsProcessingToolboxModel::rebuild :
QObject::qt_static_metacall :
QgsProcessingRegistry::providerRemoved :
QgsProcessingRegistry::removeProvider :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyDict_GetItemString :
PyArena_New :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QObject::qt_static_metacall :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.6-Białowieża
QGIS code revision: b6f33b1a
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by alexbruy** [comment]
Have you tried with new profile?

**Comment by shayaknyc** [comment]
This is a clean install, so not sure what might be causing this.

**Comment by Skipper-is** [comment]
Do you have any plugins installed? I seemed to get the issue when I had some additional plugins installed. Cleared them all out and the problem went away. However, I couldn't localise it to one single plugin
