### ISSUE TITLE
Snapping Settings

### ISSUE THREAD

**Issue by Hestemanden** [qgis/QGIS#48361]
### What is the bug or the crash?

[SHP-files.zip](https://github.com/qgis/QGIS/files/8570360/SHP-files.zip)
When I'm trying make a new polygon of the whole area (within the red line) it's situated on top of all layers, nevertheless that the snapping settings are set to "Avoid overlap".

Best regards Anders

### Steps to reproduce the issue

Make a new layer in Deciduous trees over the two areas of conifers
![Deciduous_trees](https://user-images.githubusercontent.com/79996337/165478852-e79de441-66ee-41ef-bfff-909c68b2da5a.JPG)

### Versions

3.22.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Hestemanden The plugin "Buffer Without Overlaps" might help as a workaround.

**Comment by nicogodet** [comment]
If your other features is not in the same layer, make your snap settings is set to "All layers"

The "avoid overlap" setting can fail if one geometry is invalid.

**Comment by Pedro-Murteira** [comment]
@Hestemanden As stated by @nicogodet, the avoid overlap can fail if a geometry is invalid, after running Topology Checker, I found out that there is an invalid geometry in a feature within the layer "Lakes". After fixing the geometry or deleting it, you can avoid overlap with no further issues.
