### ISSUE TITLE
Add Temporal Controller support for WMTS layer

### ISSUE THREAD

**Issue by ashleysommer** [qgis/QGIS#48364]
### Feature description

A WMTS service can advertise additional dimensions available on a dataset layer. An example of an additional dimension is Time.
QGIS already recognizes the additional dimension, because when adding the WMTS layer it asks which "time" point I'd like to use, and shows a list of available times (populated from the dimension values list in the capabilities document).

However, it appears QGIS does not hook up this time dimension support to the new QGIS Temporal Controller and Dynamic Temporal Control features. like it does with regular WMS (using the WMS-T protocol extension).

See here for an example for a WMTS service that implements a working Time dimension:  https://landscapes-mapserver.tern.org.au/mapcache/wmts/?service=WMTS&version=1.0.0&request=GetCapabilities

### Additional context

Testing on QGIS 3.24.2 on Ubuntu 20.04.

**Comment by nyalldawson** [comment]
@ashleysommer https://github.com/qgis/QGIS/pull/48930 implements this, but I noticed something is broken in the landscapes tern.org.au server wrt TIME dimension handling (specifically, the "default" values for the time dimension are incorrectly formatted with millisecond components, yet the server does not accept strings of this format)

**Comment by ashleysommer** [comment]
Thank you for implementing this feature! Nice work.

And thanks for pointing out the issue with my default time values, that is indeed an error in my Mapcache config, I'll fix that up asap.
