### ISSUE TITLE
VERSION  3.22.6 y VERSIONS 3.24.1 y 3.24.2 IN THE ADD-ON WINDOW THE ITEM "NOT INSTALLED" DOES NOT EXIST

### ISSUE THREAD

**Issue by olipad** [qgis/QGIS#48367]
### What is the bug or the crash?

in 3 installed versions, in window "COMPLEMENTS" the item not installed does not appear to be able to install new complements to QGIS
The space where the address of the official QGIS server was found does not appear either.

### Steps to reproduce the issue

1. go to COMPLEMENTS
2. Clik admin and install complements
3. go to Configuration
4. the ITEM "Not Installed" does not appear on the screen to download new plugins, and in the rest of the screen on the right, it is blank, where the connection address to the official QGIS plugin server should be, it is blank

### Versions

3.22.6
3.24.1 
3.24.2
[WINDOW COMPLEMENTS CONFIGURATION.odt](https://github.com/qgis/QGIS/files/8575654/WINDOW.COMPLEMENTS.CONFIGURATION.odt)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@olipad what is the Operating System on which you installed QGIS?

**Comment by TheKronosSama** [comment]
I have the same problem, i can't install any complements.  I use Windows 7 service pack 1.

If you find a solution I would really appreciate it.

**Comment by agiudiceandrea** [comment]
The latest available OSGeo4W versions of QGIS for Windows do support Windows 7 64 bit.
