### ISSUE TITLE
Set M Value processing tool does not behave as expected

### ISSUE THREAD

**Issue by Ojaybee** [qgis/QGIS#48373]
### What is the bug or the crash?

The [documentation and help](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/vectorgeometry.html#qgissetmvalue) for the Set M Value processing tool states that "If no M values exist, the geometry will be upgraded to include M values and the specified value used as the initial M value for all geometries". Existing features have their M value updated according to the value set in the tool. New features created default to a NULL M value regardless of what is set using the processing tool. I've tested this with geopackages and shapefiles for line and multiline geometry types both with m value capability initially created and added later using the tool.

### Steps to reproduce the issue

Go to processing toolbox > set m values. Choose the input layer, set the m value to a number. Click Run. With the created temporary layer begin editing and add a new feature. Save your edits and stop editing.

Again using the processing toolbox find the tool "Extract M Values".  Set the summaries to first, last and count and extract the M values. Open the attribute table of the resultant layer. Newly added features through editing will have an M Value of NULL. Features existing prior to running the set M values tool will have the M values as set using the set M values tools.

### Versions

3.16.9
3.22.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It may be that this is the desired behaviour in which case I would suggest an update to the documentation to make this clear. I'd be happy to make said update.

**Comment by agiudiceandrea** [comment]
@Ojaybee the "Set M Value" algorithm, as probably all the other ones, can only operate on the geometries currently contained in the layer. It obviously cannot modify the geometries not currently contained in the layer but added afterwards.

**Comment by alexbruy** [comment]
As mentioned above, tool works correctly and updates M value for existing features.
