### ISSUE TITLE
QGIS crash

### ISSUE THREAD

**Issue by MontigoZ** [qgis/QGIS#48379]
### What is the bug or the crash?

Crash ID: [6f7bb1e2207b67793f1a4ada1054453ffcb7095a](https://github.com/qgis/QGIS/search?q=6f7bb1e2207b67793f1a4ada1054453ffcb7095a&type=Issues)

Stack Trace

QObject::blockSignals :
QgsMapCanvas::cancelJobs :
QgsMapCanvas::~QgsMapCanvas :
QgsPluginRegistry::operator= :
QgisApp::~QgisApp :
QgsPluginRegistry::operator= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: c2723178
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.5-Białowieża | QGIS code revision | c2723178
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DEMto3D | 3.4
ezprinter | 1.3.1
FreehandRasterGeoreferencer | 0.8.3
Generalizer3 | 1.0
layout_loader | 1.1
Qgis2threejs | 2.6
qgsAzimuth | 0.9.15
quick_map_services | 0.19.28
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.5-Białowieża
QGIS code revision
[c2723178](https://github.com/qgis/QGIS/commit/c2723178)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DEMto3D
3.4
ezprinter
1.3.1
FreehandRasterGeoreferencer
0.8.3
Generalizer3
1.0
layout_loader
1.1
Qgis2threejs
2.6
qgsAzimuth
0.9.15
quick_map_services
0.19.28
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

When I try to close QGIS I keep getting not responding message and after the error above.

**Comment by nyalldawson** [comment]
Fix is https://github.com/qgis/QGIS/pull/48591
