### ISSUE TITLE
CSV loading issue

### ISSUE THREAD

**Issue by carlosmnc21** [qgis/QGIS#48382]
### What is the bug or the crash?

Hi to whom may concern,
I had trouble loading an csv file,.First of all I loaded the csv file but abruptly change the File Format automatically to Custom delimiters, which is not the case for the csv file I loaded in. Second, at the Geometry Definition , at X and Y Field, these random icons shows up, not letting me select the specific field I wanted.

I would like to know which is the problem, or what am Im doing wrong.
PD: I've attached a screenshot of the issue.
Thank you in advance.

### Steps to reproduce the issue

1. Go to "Add limited text layer"
2. Click on File name
3. And the randoms icons showed up
![CSV loading issue](https://user-images.githubusercontent.com/104600184/165857956-88d33d0e-d7f9-4a18-a5ee-355da1875708.jpg)

### Versions

QGIS version
3.22.6-Białowieża
QGIS code revision
b6f33b1a
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthMeasurement
0.2.2
clipper
1.2
GarminCustomMap
3.3
GeometryShapes
0.7
geoscience
1.5
profiletool
4.1.8
Qgis2threejs
2.6
SemiAutomaticClassificationPlugin
7.10.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you provide the file ?
Looks like an encoding issue to me

**Comment by carlosmnc21** [comment]
Thanks, I've checked the encoding of my file with the notepad (UTF-8), and it didnt match the one selected in the Encoding displayed list (UTF-32), so I changed this, and it recognized the fields.

Thanks for taking your time to answer.

**Comment by nicogodet** [comment]
If everything is fine, you can close this issue ;)
