### ISSUE TITLE
mac系统操作Raster--Miscellaneous--Merge时报错

### ISSUE THREAD

**Issue by rongjianghai** [qgis/QGIS#48388]
### What is the bug or the crash?

<img width="1004" alt="1" src="https://user-images.githubusercontent.com/104621369/165915439-5fe293ca-bd4a-4e68-b4b6-9e9eb483e569.png">

### Steps to reproduce the issue

把下载好的5个地形纹理文件拖进QGIS中，点击Raster -> Miscellaneous -> Merge，输入5个图层并全选，点击运行按钮，就会报出GDAL命令输出错误ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS版本 | 3.22.6-Białowieża | QGIS代码版本 | a9824e4192
-- | -- | -- | --
Qt版本 | 5.14.2
Python版本 | 3.8.7
GDAL/OGR版本 | 3.2.1
PROJ版本 | 6.3.2
EPSG注册数据库版本 | v9.8.6 (2020-01-22)
GEOS版本 | 3.9.1-CAPI-1.14.2
SQLite版本 | 3.31.1
PostgreSQL客户端版本 | 12.3
SpatiaLite版本 | 4.3.0a
QWT版本 | 6.1.4
QScintilla2版本 | 2.11.4
操作系统版本 | macOS 12.2
  |   |   |  
激活Python插件
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS版本
3.22.6-Białowieża
QGIS代码版本
[a9824e4192](https://github.com/qgis/QGIS/commit/a9824e4192)
Qt版本
5.14.2
Python版本
3.8.7
GDAL/OGR版本
3.2.1
PROJ版本
6.3.2
EPSG注册数据库版本
v9.8.6 (2020-01-22)
GEOS版本
3.9.1-CAPI-1.14.2
SQLite版本
3.31.1
PostgreSQL客户端版本
12.3
SpatiaLite版本
4.3.0a
QWT版本
6.1.4
QScintilla2版本
2.11.4
操作系统版本
macOS 12.2

激活Python插件
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
<img width="902" alt="2" src="https://user-images.githubusercontent.com/104621369/165916893-f9ae766e-0702-4541-bc21-cacfc4e72f1e.png">

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Looks like there is an issue with your QGIS install.
