### ISSUE TITLE
Docked attribute tables - cannot toggle between tables

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#48396]
### What is the bug or the crash?

If I open and dock more than one attribute table, I cannot toggle between tables by clicking the tabs below the table.

### Steps to reproduce the issue

1. open and dock more than one attribute table
2. Try and change which table is displayed by clicking the tabs below the table.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.2-Tisler | QGIS code revision | 13c1a028
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
coordinates_converter | 1.0
LandXml | 2.3
latlontools | 3.6.2
MagneticDeclination | 2.3.1
profiletool | 4.2.2
QCopycanvas | 0.5
qgis2web | 3.16.0
qgis_resource_sharing | 0.16.0
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.2-Tisler
QGIS code revision
[13c1a028](https://github.com/qgis/QGIS/commit/13c1a028)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
LandXml
2.3
latlontools
3.6.2
MagneticDeclination
2.3.1
profiletool
4.2.2
QCopycanvas
0.5
qgis2web
3.16.0
qgis_resource_sharing
0.16.0
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@robbitt Can you try with a new profile? So we can exclude it being plugin related.

**Comment by pigreco** [comment]
I just did a test, I can't confirm, it works fine for me.

## OSGeo4W64 v2 Win Pro 64

![image](https://user-images.githubusercontent.com/7631137/166098381-ac402cd3-493f-4e87-8627-daaadee4be3f.png)

**Comment by bkepl** [comment]
I have also noticed this. The only way I can resolve it is by moving the attribute tables off to their own window. Once doing this, I can click from one tab to another.
