### ISSUE TITLE
LIDAR HD and laz/las

### ISSUE THREAD

**Issue by Sevys26** [qgis/QGIS#48407]
### What is the bug or the crash?

![Capture d’écran 2022-05-01 QGIS 195237](https://user-images.githubusercontent.com/94762373/166158201-e0239b46-0774-4091-ac49-2e09b91bb75e.png)

### Steps to reproduce the issue

????

### Versions

5.15.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Sevys26** [comment]
Hello, I can't convert or read LAZ files in LAS ???? Help

**Comment by nicogodet** [comment]
You are talking about Lastools plugin.
Not a QGIS issue.
