### ISSUE TITLE
Point cloud layers fail to render on the 2D map canvas

### ISSUE THREAD

**Issue by nirvn** [qgis/QGIS#48400]
### What is the bug or the crash?

While testing @nyalldawson 's point cloud profile stuff, I noticed a point cloud dataset that rendered fine in previous versions of QGIS now fails on current master. It renders once when the layer is added, but then subsequent renderings by panning around or zooming in and out fail, leaving a blank canvas.

### Steps to reproduce the issue

1. Download this point cloud dataset (https://pointcloud.hcmgis.vn/app/point-cloud/detail/banteay-kdei-temple-angkor-cambodia-5f6addf14bd68) and add it to QGIS
2. Zoom in, notice rendering fails

### Versions

master (to become 3.26)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by NEDJIMAbelgacem** [comment]
Hi @nirvn , can you check again if this works for you on master. I tested this and it appears to be fixed.

**Comment by uclaros** [comment]
I can still reproduce this. It only looks fixed because the pointcloud is indexed into a copc now.
Loading the ept file which was generated with a previous version makes the bug appear again.
