### ISSUE TITLE
QGIS Crash (While creating layout)

### ISSUE THREAD

**Issue by tapasmahesh** [qgis/QGIS#48413]
### What is the bug or the crash?

[caaf7738f9ef8489ee9dea88d15537c7c4013427](https://github.com/qgis/QGIS/search?q=caaf7738f9ef8489ee9dea88d15537c7c4013427&type=Issues)

QGIS crashed when I tried to create multiple maps using single layout

specifically QGIS crashes when I load third map 

### Steps to reproduce the issue

Just after adding third map for layout

### Versions

3.16

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by tapasmahesh** [comment]
![image](https://user-images.githubusercontent.com/96664116/166163590-eed5dc31-6d8b-49da-9375-30eee2deaa80.png)

**Comment by tapasmahesh** [comment]
![image](https://user-images.githubusercontent.com/96664116/166163596-8bdafbd0-7b6c-4d9b-9613-03cee9912487.png)

**Comment by nicogodet** [comment]
3.16 is not maintained anymore 
Please upgrade to 3.22 at least

**Comment by tapasmahesh** [comment]
Sounds good; thanks; I need to check the SWAT+ plugin's compatibility in QGIS 3.22.
