### ISSUE TITLE
TIFFReadEncodedStrip() fail

### ISSUE THREAD

**Issue by josaes** [qgis/QGIS#48412]
### What is the bug or the crash?

Hi!

I hope somebody can help me about one issue.

I'm advanced QGIS user but I change windows version per linux version and I have some errors that I don't understand it.

I have some rasters that in sdat format works fine but in tiff format returns this error:

`2022-05-01T22:00:16     WARNING    Alinear2_Raster_RedComunicaciones : Alinear2_Raster_RedComunicaciones.tif, band 1: IReadBlock failed at X offset 0, Y offset 6: TIFFReadEncodedStrip() failed.`

This error may ocurr in some raster process (GDAL, SAGA, QGIS). I think maybe is a library issue but I don't sure.

Thanks.

### Steps to reproduce the issue

1. Load Raster
2. Process these raster in .sdat. Works Fine.
3. Process and save result in .tiff can produce this crash or invalid results in final raster.

![image](https://user-images.githubusercontent.com/104736438/166163327-e7a17783-1ad4-48a3-a1f8-c12b51aaace7.png)

Note: This raster should be only 1 or 0 values.

### Versions

Versión de QGIS | 3.24.2-Tisler | Rama del código de QGIS | Release 3.24
Versión Qt | 5.15.2
Versión de Python | 3.10.4
Versión de GDAL/OGR | 3.3.3
Versión de PROJ | 8.2.1
Versión del registro de base de datos EPSG | v10.041 (2021-12-03)
Versión de GEOS | 3.9.2-CAPI-1.14.3
Versión de SQLite | 3.36.0
Versión de PDAL | 2.3.0
Versión del cliente de PostgreSQL | unknown
Versión de SpatiaLite | 5.0.1
Versión de QWT | 6.1.5
Versión de QScintilla2 | 2.13.0
Versión del SO | Fedora Linux 35 (Workstation Edition)

Complementos activos de Python
processing_saga_nextgen | 0.0.7
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
This probably should be reported GDAL as QGIS uses GDAL to work with rasters.

**Comment by rouault** [comment]
Please provide an input dataset and the exact workflow to reproduce the issue

**Comment by josaes** [comment]
I think that I found the problem.

Some GDAL processes break when path length is too big. I changed my project path to other folder and GDAL processes worked fine.

I think that this issue should be closed.

Thanks to all.
