### ISSUE TITLE
QGIS takes forever to render ArcGIS World Imagery

### ISSUE THREAD

**Issue by AllieRosie** [qgis/QGIS#48429]
### What is the bug or the crash?

I'm currently using QGIS 3.16.5. I am using the ArcGIS World Imagery - High Resolution 30cm Imagery layer to select training data for land cover classification. For the last two months, I was able to zoom into the layer at the scale of 1:936 and rendering happened pretty quickly. Yesterday, my QGIS crashed and after that, QGIS takes forever to render the layer when zooming in (even at higher scale like 1:1575). I have come crossed a few posts on speeding up QGIS rendering, and have made sure that the "use render caching","render layers in parallel" and "simplification" are turned on. I have also installed the new release (3.22.6) but the issue persisted. My colleagues and I also tested on three other computers with QGIS 3.16, 3.18 and 3.10 and the same thing happened. One of my colleagues said the issue started since last Friday 29 April for her.

![220502 rendering issue](https://user-images.githubusercontent.com/32089307/166342762-00b145a1-0cd2-42b5-a056-29e252f92a89.jpg)
 

### Steps to reproduce the issue

1. Open a new project.
2. Open Data Source Manager/ArcGIS Map Service.
3. Click New and use this URL: http://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer
4. Click Connect and select the layer High Resolution 30cm Imagery, and click Add.
5. Zoom into the layer. Even at scale of 1:4000000 the rendering takes hours.

### Versions

QGIS version
3.16.5-Hannover
QGIS code revision
58ba7c1ed6
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Tested on a month old version of master on windows cannot reproduce. Have you checked if the issue is related to your network and not qgis. That would seem more likely if your setup did not change and everyone experienced this at the same time.

**Comment by AllieRosie** [comment]
Hi Alex,

Thanks for your email.

I was also not sure if it's QGIS or it's the map server itself. In terms of
WiFi networks, I have tested at my house and my company and the issue
persists.

Anyhow, I have found a solution. It seems that the path to the map server
has changed. The older path was:
https://server.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer.
When I used the latest path (
https://services.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer)
to connect to the server, the rendering resumed to almost normal speed.
When I say "almost", it means that previously when I zoom in to ESRI World
Imagery at the scale of 1:1000 it took less than 1 sec to render that layer
(I could see that it's a different layer, but I didn't see any missing tile
due to rendering-in-progress), but now I can see some tiles have already
finished rendered and somes are still rendering.

Kind regards,
Quynh (Allie).

**Comment by ismailsunni** [comment]
I tested on Ubuntu 20.04 and QGIS 3.24.3, it seems indeed normal for me. I compare the result with loading OSM, it also has less than 1-second missing tile. But, I guess that is normal and probably more related to the network and the map server?

My feeling, if you use the same QGIS version, and there are something changes in performance suddenly, perhaps it's more on the map server-side or network :)

Anyway, we should update the title, since it's no longer forever :)

**Comment by alexbruy** [comment]
Is this still an issue? I tested with the latest master (a52133202070a747277d37ed17c0181372cc6772) on Linux and 3.32 on Windows and it works fine.
