### ISSUE TITLE
QGIS 3.22.3-1 loads WFS much slower that 3.20.3-1 and not stable

### ISSUE THREAD

**Issue by pocwiard** [qgis/QGIS#48428]
### What is the bug or the crash?

When loading WFS data using QGIS 3.22.3-1 with the same setting as 3.20.2-1 the data loads three times slower and sometimes does not finish. The styling freezes and never ends. 
What can I do to make it load faster and stable? 
thanks

### Steps to reproduce the issue

Load WFS layer and compare the loading time to 3.20.

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
kmltools
3.1.17
LandXml
2.3
landxml2qgis
0.3.2
LAStools
1.4
layer2kmz
1.5.3
mmqgis
2021.9.10
pointsamplingtool
0.5.3
profiletool
4.2.2
QGIS-terrain-shading-master
0.9.4
rvt-qgis
0.9.0
shapetools
3.4.4
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@pocwiard Hello, can you give it a try with a new profile on 3.22.3?

**Comment by pocwiard** [comment]
Hi

What are the missing information I should provide? I will be happy to do
that as we work a lot with WFS data.

kind regards
Pawel Pocwiardowski

**Comment by pocwiard** [comment]
Hi Andrea

I downloaded 3.22.6. I reset the whole profile thing and started fresh.
It seems that the WFS with this version works at sort of the same speed as
the 3.20. But it is still very slow.
I was wondering if there is anything you guys can put on the road map to
improve it?
I am working a lot with Geoserver and the WMS/WFS. While WMS is very fast,
the WFS is painfully slow.

Thanks a lot for your consideration

kind regards
Pawel Pocwiardowski

**Comment by pocwiard** [comment]
Hi

It seems the same. Much slower than V20.
We use WFS quite often and WFS has been always slower, but now it is
painfully slow.

Pawel
