### ISSUE TITLE
not reading CSV TXT sources not 

### ISSUE THREAD

**Issue by grandebooz** [qgis/QGIS#48422]
### What is the bug or the crash?

After updating project file to version 3.22.6 (ltr) and closing qgis, when reloading it it doesn't load the txt or csv sources.
It doesnt work auto-correct, 'browse' doesnt open and 'repair data source', doesnt see the txt files and reselecting csv sources seems to work but not always. maybe with ';' separator only, otherwise it looses the geometry from crd fields..
Anyway after saving , closing, reopening, we are back to start condition.

Thanx
grandebooz

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/104769117/166233428-c7dff361-82d8-42ba-b8b6-bd5580f819de.png)

### Versions

3.22.6 ltr

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Never seen in 3.16 version, it started now with 3.22 after saving the project file.
Using win 11 pro and loading data from smb  files sources. (net volume assigned)

**Comment by Pedro-Murteira** [comment]
@grandebooz Can you attach those files for further testing?

**Comment by grandebooz** [comment]
[RIDUTTORI.txt](https://github.com/qgis/QGIS/files/8603450/RIDUTTORI.txt)
[TEST.zip](https://github.com/qgis/QGIS/files/8603458/TEST.zip)

WELL, 
you can extract the zip file, there is a very simple txt source, wich is loaded fina by the test_316.qgs prj file.
Onece this file is saved by 3.22 qgis in the test_322.qgs, then becomes not functional

**Comment by Pedro-Murteira** [comment]
I can confirm aswell, file does not load on 3.22.6 and 3.24.2.

**Comment by grandebooz** [comment]
yes.
although test_322 file is correctly loaded under qgis 316 , isn't it ?

**Comment by Pedro-Murteira** [comment]
@grandebooz Correct, I've tested on QGIS 3.16.16 and both prj files load just fine.

**Comment by grandebooz** [comment]
well, so if you whant to replicate the bug you can load the 316 project with qgis 322 and save as new file. 
Then you reload with the qgis 322.
If it works then the trouble is on my pc.
Thanks  a lot!
Seeyou.

**Comment by Pedro-Murteira** [comment]
@grandebooz I see, it did work, it might be related to your pc.

**Comment by grandebooz** [comment]
thank you very much.
I did a osg4w online install and something should have gone wrong.
I will reinstall 3.22 from a standalone package.
Solved! (I guess)

**Comment by alexbruy** [comment]
Is this still an issue?

**Comment by alexbruy** [comment]
Tested on Windows and Linux with the latest master (2d64df22a4eb4e7e6718f747c9eb1ed4e5f81903) and can't reproduce

**Comment by grandebooz** [comment]
I think it has been resolved.
Now i'm using the build 3.28-6 and it works fine.
Thanks to everyone.
