### ISSUE TITLE
annotationManager().addAnnotation() leads to crash

### ISSUE THREAD

**Issue by Ludwig-K** [qgis/QGIS#48424]
### What is the bug or the crash?

Annotations added via annotationManager crashes QGis when iterating over iface.mapCanvas().scene().items()

### Steps to reproduce the issue

create some QgsTextAnnotations via
```
xy = [
[312199,5632543],
[312299,5632643],
[312399,5632743]
]

canvas = iface.mapCanvas()
for p in xy:
    txt = QTextDocument('Point x/y:' + str(p[0]) + '/' + str(p[1]))
    annot = QgsTextAnnotation(canvas)
    annot.setDocument(txt)
    annot.setFrameSize(QSizeF(50.0, 25.0))
    annot.setMapPosition(QgsPointXY(p[0],p[1]))
    annot.setFrameSize(QSizeF(txt.size().width(),txt.size().height()))
    annot.setFrameOffsetFromReferencePoint(QPointF(10, 5))
    QgsProject.instance().annotationManager().addAnnotation(annot)
```
if there are some annotation-items added via annotationManager().addAnnotation(...) iterating over all canvas-items via
```
for item in iface.mapCanvas().scene().items():
    print(type(item))
```
crashes QGis. 
(But no crash occurs, if the above annotations were added to canvas via `QgsMapCanvasAnnotationItem(annot, canvas)` instead of `addAnnotation(annot)`)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
From the documentation of that function: " Ownership of the annotation is transferred to the manager.". So you can't safely just add annotations which belong to something else. And in this case you're parenting the annotations to the canvas (`annot = QgsTextAnnotation(canvas)`). Hence the crash. Solution is to remove the parent argument from the QgsTextAnnotation constructor, .ie. `annot = QgsTextAnnotation()`.

**Comment by Ludwig-K** [comment]
That makes sense, thanks for the quick answer and your great work!
