### ISSUE TITLE
Project Transformation Not Available

### ISSUE THREAD

**Issue by jaredcing** [qgis/QGIS#48425]
### What is the bug or the crash?

When I open my project, I get an error that I cannot use project transform between EPSG:3857 and EPSG:4269. If I try to install the missing transform file from folder, I get an error that the file can't be copied. I have confirmed folder permissions, and was able to manually copy the file into the proper destination, but I continue to receive the error.

I started an empty new project, and it does not have the error. When I add an XYZ Tiles layer linked to Google Maps via the link: http://mt0.google.com/vt/lyrs=s&hl=en&x=%7Bx%7D&y=%7By%7D&z=%7Bz%7D I get the exact same error and issues.

There is a Plugin processing notice at login that a plugin is disabled because it previously crashed QGIS, which may or may not be related. There are only two active plugins: DB Manager and MetaSearch Catalog Client.

I must admit, I have not much experience with this program so there may be a really simple fix that I am missing.

### Steps to reproduce the issue

1. Open QGIS
2. Project -> Open -> (projectname)
3. Red banner at top of screen below the banners says "Cannot use project transform between EPSG:3857 and EPSG:4269"
4. Click on Details button to the right side of the banner
5. Project Transformation Not Available popup window opens, Click "Install cnhpgn.gsb from Folder..." button
6. Locate file in Downloads (does not show up when searching for cnhpgn.gsb, have to widen search to Grid Shift Files)
7. Select cnhpgn.gsb
8. Click "Open" button
9. Popup window opens titled "Install Grid File" with error message on it: "Could not copy cnhpgn.gsb to C:/Users/jcurry/AppData/Roaming/QGIS/QGIS3\profiles\default/proj/cnhpgn.gsb.tif. Please check folder permissions and retry."

I attempted to use a different download file to see if that would resolve the issue, but the error is the same as in this image.
![QGIS Error](https://user-images.githubusercontent.com/104657894/166080251-c98859cf-ac6b-4621-b3b5-0ec7c2d3aa1d.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.16-Hannover | QGIS code revision | f5778a89
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.4.1 | Running against GDAL/OGR | 3.4.1
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.2-CAPI-1.16.0
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.37.2
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.2.1 | Running against PROJ | Rel. 8.2.1, January 1st, 2022
OS Version | Windows 10 Version 2009
Active python plugins | db_manager; MetaSearch

</body></html>QGIS version
3.16.16-Hannover
QGIS code revision
[f5778a89](https://github.com/qgis/QGIS/commit/f5778a89)
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.4.1
Running against GDAL/OGR
3.4.1
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.2-CAPI-1.16.0
Compiled against SQLite
3.35.2
Running against SQLite
3.37.2
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.2.1
Running against PROJ
Rel. 8.2.1, January 1st, 2022
OS Version
Windows 10 Version 2009
Active python plugins
db_manager; 
MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@jaredcing Hello, QGIS 3.16 is no longer being maintained, could try and see if the problem still remains on 3.22 or 3.24?

**Comment by jaredcing** [comment]
Thanks for catching this, I didn’t realize I was using an out-of-date version. It appears that updating to 3.22 has resolved my problem.
Is there any way that you are aware of to have QGIS auto-update?

Jared Curry, EIT
Project Coordinator

Inglenook
PO Box 208 | 1991 Saint Helena Highway, Rutherford, CA 94573
Phone: (707) 955-0311

**Comment by Pedro-Murteira** [comment]
@jaredcing If there is a way to auto-update QGIS, i'm unware of it. If someone from the dev team or an experienced user bumps into this, they might have an answer to your question. Or perhaps submiting the question on qgis stack exchange or the user mailling list might help you aswell. For the time being, I will close this issue since updating QGIS fixed the problem.
