### ISSUE TITLE
QgsMapCanvas::showEvent access violation / QGIS crash

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#48438]
### What is the bug or the crash?

If a QgsMapCanvas has been removed from an widget but still exists, it's can cause an Access violation that crashes QGIS if the former parent widget is moved between different screens.

The exception occurs in windows when the signal-slot connection created in `QgsMapCanvas::showEvent` is called:

![grafik](https://user-images.githubusercontent.com/1404870/166452346-a217cebb-e4c1-4fc5-b732-5d4fcc03c7a8.png)

Call stack:
![grafik](https://user-images.githubusercontent.com/1404870/166452874-5e58fe07-c83f-42a7-9493-1f6d87d5ada5.png)

### Steps to reproduce the issue

Run the code below from QGIS python shell. Requires a setup with at least 2 screens.

````python
import gc
import sys

from qgis.PyQt.QtGui import QScreen
from qgis.PyQt.QtWidgets import QWidget, QVBoxLayout, QPushButton
from qgis.core import QgsApplication
from qgis.gui import QgsMapCanvas
from qgis.testing import start_app

app = QgsApplication.instance()
if not isinstance(app, QgsApplication):
    app = start_app()
    call_exec = True
else:
    call_exec = False

assert len(app.screens()) > 1, 'This test requires at least 2 screens'
canvas = QgsMapCanvas()


class MyWidget(QWidget):

    def __init__(self, *args, **kwds):
        super(MyWidget, self).__init__(*args, **kwds)
        self.btn = QPushButton('Remove canvas')
        self.btn.clicked.connect(self.onClicked)
        self.canvas = canvas
        layout = QVBoxLayout()
        layout.addWidget(self.btn)
        layout.addWidget(self.canvas)
        self.setLayout(layout)

    def onClicked(self):
        if isinstance(self.canvas, QgsMapCanvas):
            # self.layout().takeAt(self.layout().indexOf(self.canvas))
            self.layout().removeWidget(self.canvas)
            self.canvas.setParent(None)
            self.canvas = None

        app.processEvents()
        gc.collect()
        print(f'REFCOUNT={sys.getrefcount(canvas)}')


# 1. create widget with QgsMapCanvas on default screen
w = MyWidget()
w.show()
app.processEvents()

# 2. Remove QgsMapCanvas, but keep a python reference on, so that is still exists
w.btn.click()
app.processEvents()

# 3. Move widget to 2nd screen. This raises an access violation on windows systems
nextScreen: QScreen = [s for s in app.screens() if s != w.screen()][0]
nextScreenCenter = nextScreen.geometry().center()
w.move(nextScreenCenter)
app.processEvents()

if call_exec is True:
    app.exec()

````

### Versions

windows OSGEO4W dev
QGIS Version: 3.25.0-Master
QGIS code revision: 7be1b02a71
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

(~~seems to be fine in linux/ubuntu~~ I don't have a linux or macOS plattform with `len(QApplication.instance().screens()) > 1`)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jakimowb** [comment]
I updated the python example. It now moves the created widget to another screen and does not require "manual" user interaction.

**Comment by rouault** [comment]
Confirmed on Linux too
