### ISSUE TITLE
Make it possible to disable a (part)style in a composite style (Symbol layers)

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#48435]
### Feature description

When designing a composite style with multiple symbol layers, it would be very handy if a single symbol layer could be disabled/enabled with a button, see picture.

![Capture](https://user-images.githubusercontent.com/8887576/166412782-ab3bec15-d48d-45cd-9e41-410eb049164e.PNG)

**Comment by DelazJ** [comment]
@Jakob-Lanstorp There's already an "[Enable symbol layer](https://docs.qgis.org/3.22/en/docs/user_manual/style_library/symbol_selector.html#common-parameters)" button that allows this. Its position is however questionable as you can see in #33861.
Closing as a duplicate. If not, please clarify and feel free to reopen.
