### ISSUE TITLE
Highlight of identified feature not displaying correctly on "geometry generator" marker from different CRS   

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#48439]
### What is the bug or the crash?

Highlight of identified feature (symbol outline in red by default) is not displaying correctly when symbol is created with geometry generator option.

Start point is correct (in project CRS), but endpoint seems to be used from layer CRS rather than in project CRS so we get weird red highlight visualization of identified feature.

See attached GPKG which includes project and data, demo in video below.

[![QGIS Identify Highlight bug](https://user-images.githubusercontent.com/1849293/166454515-e5766684-efcd-4a03-a7e3-645bea3afae7.png)](http://www.youtube.com/watch?v=baJPCEe6NRw "QGIS Identify Highlight bug")

### Steps to reproduce the issue

See attached GPKG which includes project and data.
"Project -> Open From -> GeoPackage..."
[highlight_bug.zip](https://github.com/qgis/QGIS/files/8610408/highlight_bug.zip)

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
EquirectangularViewer
1.4
ImportPhotos
3.0.3
mmqgis
2021.5.16
plaingeometryeditor
3.0.0
QuickWKT
3.1
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Unfortunately this isn't a simple bug to fix. The class which does the highlight was not designed to deal with geometry generators and it does the geometry transformation early in the process resulting in a wrong make_line (first point is transformed and second one isn't), I'm trying to find a solution.

**Comment by phidrho** [comment]
@nyalldawson @elpaso
Thank you for this bugfix! It really confused my coworkers.
