### ISSUE TITLE
Problem with OTB tools not showing in Toolbox

### ISSUE THREAD

**Issue by bravemaster3** [qgis/QGIS#48444]
I am having a hard time getting OTB to work in QGIS 3.22 and despite the OTB provider activated in the plugin manager, I still do not see any OTB tools in the Processing toolbox.
I also went in the toolbox options, and for OTB, there is no button for activating it unlike other toolboxes such as GRASS.
I have no idea also what to set (if I have to) for the options like "geoid", application folder.... 
Any help will be greatly appreciated as I urgently need to do some classifications.
I have the lasted version of QGIS (3.22), installed today (2022-05-04) along with several other tools using OSGeo4W. I made sure to uninstall all previous installations and removed the OSGeo4W folder before installing it again.

See referenced comment to a similar problem...

Thanks,
Koffi

![image](https://user-images.githubusercontent.com/39010414/166627644-10a0d424-b60a-407a-8ee8-e6d3382c3949.png)

![image](https://user-images.githubusercontent.com/39010414/166627567-8a7a5af9-9cb9-4255-ab0f-d766370c4874.png)

_Originally posted by @bravemaster3 in https://github.com/qgis/QGIS/issues/46945#issuecomment-1116950845_

**Comment by alexbruy** [comment]
Duplicates #46945.

**Comment by bravemaster3** [comment]
@alexbruy 
Is this really a duplicate of the other issue?
I hope you saw my comment there as well. I started from that closed issue, where you said to actor the plugin. 
I'm my case, I have already activated it as you can see in the screenshot, and yet I am not able to use OTB... I didn't find enough help in the documentation. So, if there is something you can point me towards for solving the issue, I would be grateful.
Thank you,
Koffi
