### ISSUE TITLE
QGIS crash by opening a form with relation content

### ISSUE THREAD

**Issue by beli2go** [qgis/QGIS#48443]
### What is the bug or the crash?

Postgis Data. A mother-child relation integrated in the form. (it crashes in ui form same as in drag&drop form)
By opening the form it opens in table form -> changing to the form view it crashes.
The project works fine with 3.16
It's a new installation with 3.22 and 3.24.

### Steps to reproduce the issue

Postgis Data. A mother-child relation integrated in the form. (it crashes in ui form same as in drag&drop form)
By opening the form it opens in table form -> changing to the form view it crashes.
The project works fine with 3.16
It's a new installation with 3.22 and 3.24.

### Versions

QGIS-Version
3.22.6-Białowieża
QGIS-Codeversion
b6f33b1a
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.4.2
PROJ-Version
9.0.0
EPSG-Registraturdatenbankversion
v10.054 (2022-02-13)
GEOS-Version
3.10.2-CAPI-1.16.0
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
13.0
SpatiaLite-Version
5.0.1
QWT-Version
6.1.3
QScintilla2-Version
2.11.5
BS-Version
Windows 10 Version 1607

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Can you please attach a sample project with data to reproduce the issue?

**Comment by beli2go** [comment]
[qgis_relation.zip](https://github.com/qgis/QGIS/files/8705303/qgis_relation.zip)

This is a very simple example for the issue.
The two tables "table1" and "child1" are in relation. Both have a ui-form.
When you open the "table1"-form inside qgis and try to click on tab2 (tab2 contains the child feature) qgis 3.22 crashes.
When you remove  the ui form from the table "child1" and do the same -> it works.
I guess it's something at the QGisRelationReferenceWidget.
The same in QGis 3.16 works fine with the ui-forms.
Thank you.

**Comment by 3rm4c** [comment]
Hello i also have the same problem on ubuntu 22.04

<code>
$ qgis
<string>:1: DeprecationWarning: setapi() is deprecated
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
Qt: Session management error: networkIdsList argument is NULL
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 6297, resource id: 14813869, major code: 40 (TranslateCoords), minor code: 0
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 7829, resource id: 14814042, major code: 40 (TranslateCoords), minor code: 0
Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied.
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 19862, resource id: 14817301, major code: 40 (TranslateCoords), minor code: 0
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 29915, resource id: 14818023, major code: 40 (TranslateCoords), minor code: 0
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 31301, resource id: 14821863, major code: 40 (TranslateCoords), minor code: 0
Warning: QXcbConnection: XCB error: 3 (BadWindow), sequence: 47282, resource id: 14823478, major code: 40 (TranslateCoords), minor code: 0
Segmentation fault
</code>

for "Warning 4: Failed to open /usr/share/qgis/resources/data/world_map.gpkg: Permission denied." 

$ ls -l /usr/share/qgis/resources/data/world_map.gpkg
-rw-r--r-- 1 root root 13M 2022-02-19 18:53 /usr/share/qgis/resources/data/world_map.gpkg

**Comment by elpaso** [comment]
> 

A crash is not nice but you are not using the widget correctly, see the constructor: 

```python
In [2]: QgsRelationEditorWidget?
Init signature: QgsRelationEditorWidget(self, /, *args, **kwargs)
Docstring:     
The default relation widget in QGIS.

.. versionadded:: 3.18

QgsRelationEditorWidget(config: Dict[str, Any], parent: QWidget = None)
Constructor

:param config: widget configuration
:param parent: parent widget
```

it takes a config dict in the constructor.

**Comment by beli2go** [comment]
sorry, but i build the ui using the qt designer like i did always. I am not coding the constructor manually.
i searched the internet for your info, but can't find a solution or example how to fix my problem.
i can not imagine that i have to use code to get the relation widget work.
if the constructor is wrong, maybe there is a problem in the ui designer?!

**Comment by vamue** [comment]
I have the same issue also with an ui form using a QgsRelationEditorWidget set up with Qt Designer 5.15.13. 

`Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003b7c (most recent call first):
  


Stack Trace


QObject::property :
QgsAttributeForm::createWrappers :
QgsAttributeForm::init :
QgsAttributeForm::QgsAttributeForm :
QgsDualView::initAttributeForm :
QObject::qt_static_metacall :
QgsFeatureListView::currentEditSelectionChanged :
QgsFeatureListView::editSelectionChanged :
QObject::qt_static_metacall :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QItemSelectionModel::select :
QgsFeatureListView::setEditSelection :
QgsFeatureListView::updateEditSelection :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.38.1-Grenoble
QGIS code revision: 3d4177afc6
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.1
Running against GDAL: 3.9.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631`
