### ISSUE TITLE
Vector and Raster are not working properly

### ISSUE THREAD

**Issue by Ashia25** [qgis/QGIS#48447]
### What is the bug or the crash?

when I click the Vector menu, the dropdown menu doesn't appear. Same thing happens to the Raster menu, but only 3 options appears. 

### Steps to reproduce the issue

![2022-05-05 (2)](https://user-images.githubusercontent.com/104891230/166858034-1ed95f7f-e1f1-4eb4-a952-06811e765326.png)
![2022-05-05 (3)](https://user-images.githubusercontent.com/104891230/166858038-c8645758-ca38-40a0-99f4-facda2e8e7ee.png)
![2022-05-05 (1)](https://user-images.githubusercontent.com/104891230/166858041-dac82419-f915-4034-b92d-2e7e2f4683e8.png)

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
openlayers_plugin
2.0.0
XYZHubConnector
1.9.2
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Ashia25 Does the issue still occur with a new profile?

**Comment by roya0045** [comment]
How was QGIS installed?

**Comment by Ashia25** [comment]
> @Ashia25 Does the issue still occur with a new profile?

yes, it still occur on a new profile.

**Comment by Ashia25** [comment]
I uninstalled the application then tried to install a new version but still it does not work. and also the plugin option in the help dropdown box is also not working.

**Comment by Ashia25** [comment]
> How was QGIS installed?

could you please elaborate the question? sorry it is my first time having trouble in using QGIS so.
