### ISSUE TITLE
creatensis.pl unpacks downloaded tar files in arbitrary order, resulting in different files/dll

### ISSUE THREAD

**Issue by benvanbasten-ns** [qgis/QGIS#48448]
### What is the bug or the crash?

We accidentally stumbled upon the following. 

When using creatensis.pl multiple times, we noticed that the resulting installers could contain different versions of a handful of files (for example, libpng16.dll, netcdf.h and pyQt5.api). 

Even though creatensis.pl always downloads the same tar files, it seems the order in which they are unpacked differs. The files described above occur in multiple tars [1], and hence, as they are unpacked to the same folder, the order in which the tars are unpacked determines the resulting file in the installer.

It seems that the different order comes from the fact that the packages are stored in a Perl hash (%pkgs), which seems to be (randomized) unordered [2].

Obviously, it is unclear which version of those files is better, but I think it is worthwhile to at least ensure that the resulting installer is the same for multiple consecutive builds. Perhaps the hash can be replaced with an array, or ordering can be enforced.

[1] For example, libpng16.dll occurs in both libpng-1.6.3-1.tar.bz2 and libpng-vc14-1.6.29-1.tar.bz2. Both versions have been seen ending up in the final installer.

[2] https://stackoverflow.com/questions/30340027/why-do-hash-keys-have-different-order-when-printing

### Steps to reproduce the issue

1. Run creatensis.pl multiple times
2. Log the resulting console output 
3. Note that some files (libpng.dll, netcdf.h, pyQt5.api) can differ (in size, and contents) between runs

### Versions

3.16.6, but creatensis.pl barely changed over time, so this issue is likely to occur in later versions as well.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jef-n** [comment]
creatensis.pl is not used anymore (build recipes are in https://github.com/jef-n/OSGeo4W/  - including createmsi.pl)
