### ISSUE TITLE
Wrong method used for slot in qgscameracontroller.cpp

### ISSUE THREAD

**Issue by VolkerEnderlein** [qgis/QGIS#48454]
### What is the bug or the crash?

In [src/3d/qgscameracontroller.cpp:65](https://github.com/qgis/QGIS/blob/master/src/3d/qgscameracontroller.cpp#L65) the wrong method for a slot is used. Instead of `Qt3DInput::QMouseHandler::setEnabled` the method `Qt3DInput::QKeyboardHandler::setEnabled` has to be used.

### Steps to reproduce the issue

none

### Versions

current

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@VolkerEnderlein Do you think you can provide the necessary fix in a pull-request, please? Thanks.

**Comment by VolkerEnderlein** [comment]
Done. See #48456
