### ISSUE TITLE
Generate XYZ Tiles (Directory) silently fails (tiles doesn't get created at all)

### ISSUE THREAD

**Issue by Bencilari** [qgis/QGIS#48460]
### What is the bug or the crash?

Trying to generate XYZ tiles silently fails. Tiles doesn't get created, just the html viewer is created.
I've tried various combination (output to a directory, temporary directory, png or jpg format).
The process end claiming success, but the output dir is empty.
Even launching QGis from a console, no error messages are displayed.
So everything seems fine (it even takes a lot o time to complete, and CPUs are occupied), but no output or error messages

### Steps to reproduce the issue

Processing -> Raster -> Generate XYZ Tiles (Directory)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.20.3-Odense | branch codice QGIS | Release 3.20
-- | -- | -- | --
Versione Qt | 5.15.2
Versione Python | 3.10.0
Compilato con GDAL/OGR | 3.3.1 | Esecuzione con GDAL/OGR | 3.3.3
Compilato con PROJ | 8.1.0.%3.%4 | Esecuzione con PROJ | 8.2.1
Versione database del Registro EPSG | v10.041 (2021-12-03)
Compilato con GEOS | 3.9.1-CAPI-1.14.2 | Esecuzione con GEOS | 3.9.2-CAPI-1.14.3
Versione SQLite | 3.36.0
Versione client PostgreSQL | 13.4
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.5
Versione QScintilla2 | 2.11.6
Versione SO | Fedora Linux 35 (Thirty Five)
  |   |   |  
Plugins Python attivi | qgis2webquick_map_servicesQuickOSMImportPhotosGeneralizer3MetaSearchdb_managerprocessing

</body></html>Versione di QGIS
3.20.3-Odense
branch codice QGIS
[Release 3.20](https://github.com/qgis/QGIS/tree/release-3_20)
Versione Qt
5.15.2
Versione Python
3.10.0
Compilato con GDAL/OGR
3.3.1
Esecuzione con GDAL/OGR
3.3.3
Compilato con PROJ
8.1.0.%3.%4
Esecuzione con PROJ
8.2.1
Versione database del Registro EPSG
v10.041 (2021-12-03)
Compilato con GEOS
3.9.1-CAPI-1.14.2
Esecuzione con GEOS
3.9.2-CAPI-1.14.3
Versione SQLite
3.36.0
Versione client PostgreSQL
13.4
Versione SpatiaLite
5.0.1
Versione QWT
6.1.5
Versione QScintilla2
2.11.6
Versione SO
Fedora Linux 35 (Thirty Five)

Plugins Python attivi
qgis2web
quick_map_services
QuickOSM
ImportPhotos
Generalizer3
MetaSearch
db_manager
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> 3.20.3-Odense

and a newer and maintained version (3.22, 3.24)?

**Comment by Bencilari** [comment]
> @Bencilari Does it still occur with a new profile?

Hi @Pedro-Murteira . Did you mean user profile (i.e. with another/new user)?

**Comment by DelazJ** [comment]
no, he meant https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles

**Comment by Bencilari** [comment]
> @Bencilari Does it still occur with a new profile?

ok, tried. Same results, nothing's changed. No tiles created, just .html viewer file

**Comment by Bencilari** [comment]
> and a newer and maintained version (3.22, 3.24)?

i'd like to stick to the version provided by the distro. Even if it's a problem related to this version/package, i think it can affect a lot of people.
Probably i'll test another version when fedora 36 will be released (in 10/20 days, it seems).

**Comment by nyalldawson** [comment]
It's caused by a mismatch between python > 3.9 and older qgis.solution is to update to a newer qgis release which is compatible with python 3.9+
