### ISSUE TITLE
Export layer metadata

### ISSUE THREAD

**Issue by DavideDC9** [qgis/QGIS#48473]
### What is the bug or the crash?

I have a categorized sample layer with 2 categories, let s say high and low. When exporting and adding to the map the categories are lost during the export process. I have tried several formats but none is keeping the metadata.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/84395463/167137609-5aa6b80b-13c4-4b14-89e2-6a866e2219ec.png)

### Versions

3.24.2-Tisler

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pathmapper** [comment]
@DavideDC9 you didn't provide detailed information, but I guess this is expected. You need to export/import also the style, for Geopackage see e.g. https://www.youtube.com/watch?v=K0J_NdlXfzg.

**Comment by alexbruy** [comment]
Not a bug. Styling is not a part of the metadata, also data formats does not support QGIS styling.
