### ISSUE TITLE
Topology checker: QGIS crash on exit, after activating the topology checker panel

### ISSUE THREAD

**Issue by PeterZamudio** [qgis/QGIS#48470]
### What is the bug or the crash?

This is the same issue from 2019. After activating the Topology checker plugin, QGIS 3.24.2 crashes every time when closing the program.

### Steps to reproduce the issue

1. Started with a new user
2. load any layer
3. activate the Topology checker plugin
4. save the project
5. click exit and crash
6. If I do the same without the Topology checker it does a clean normal exit

### Versions

3.24.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by PeterZamudio** [comment]
Hello Nyall
Thankyou for your reply. Sorry I am so late getting back to you. I have updated QGIS to 3.24.3 and although QGIS still crashes a lot when I exit, I can no longer say for certain that it is the Topology checker plugin. As no damage is done it's not so bad. Just looks silly if someone is watching when the crash report comes. Fact is that QGIS crashes about once on every 3 exits now and I don't know why. I have googled and it seems it's not a new problem. I have made new users and reinstalled, and although it helps for a while, the problem always seems to come back. The first time I noticed it was about 2 years ago. We can close this issue here, I think you know it's a general on going problem. Thank you for you great work.
Peter

**Comment by nyalldawson** [comment]
Can you get one of the crash reports from that screen and paste it here?

**Comment by PeterZamudio** [comment]
Hello Nyall

It is not happening as much as before and I am nolonger certain it's the Topology checker causing it. But here is an example:

Python Stack Trace
Windows fatal exception: code 0x8001010d

Current thread 0x00006520 (most recent call first):

Windows fatal exception: access violation

Current thread 0x00006520 (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by PeterZamudio** [comment]
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00005830 (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by PeterZamudio** [comment]
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000047cc (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by PeterZamudio** [comment]
All crashes on exit
