### ISSUE TITLE
Frozen Python Console

### ISSUE THREAD

**Issue by pushheap** [qgis/QGIS#48482]
### What is the bug or the crash?

Hello.

I have a small script, to calculate the area and update text fields in the Shapefiles tables, in QGIS 3.24.2 under Windows.

A loop works with the list of layers in QGIS and the other with the features of each Shapefile, at the beginning of the second loop Layer is used.

Data on the Python console are progressively shown.

In Windows, the Python console is blocked and ceases to be refreshed, this is very annoying, for a large number of shapefiles.

This does not happen in QGIS 3.18.3 under Linux.

### Steps to reproduce the issue

1. Load many shapefiles
2. Run Script

```
area = QgsDistanceArea()
layers = QgsProject.instance().mapLayers().values()

print('BEGIN')

for layer in layers:

	print(layer.name())

	layer.selectAll()
	layer.startEditing()

	selection = layer.selectedFeatures()
	for feature in selection:
		geom = feature.geometry()

		areapoly = (area.measureArea(geom) / 10000)

		print('\t' + "{:,.4f}".format(abs(feature['hectareas'] - areapoly)) + ' O: ' + str(feature['hectareas']) + ' C: ' + "{:,.4f}".format(areapoly))

		feature['granja'] = 'Darguna'
		feature['hectareas'] = areapoly

		layer.updateFeature(feature)

	layer.commitChanges()
	layer.removeSelection()

print('FINISHED')
```

### Versions

3.24.2 (Windows)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pushheap** [comment]
No python console freezes, the whole QGIS application freezes until the process is finished.

The suggestion you made to me in Issue #51597 @nyalldawson, about using iface.mapCanvas().refresh() obviously doesn't work, as it freezes the entire QGIS Windows application.

**Comment by nyalldawson** [comment]
Insert a `QApplication.processEvents()` after each print statement if you want to force an early redraw of the QGIS window. Be very careful doing this do -- while it's (moderately) safe to do in this script, calling processEvents() in the wrong place can result in unpredictable behaviour / crashes.
