### ISSUE TITLE
@project_keywords are no longer tested on Rule based filters

### ISSUE THREAD

**Issue by yannisps** [qgis/QGIS#48480]
### What is the bug or the crash?

Use a Rule-based filter no longer returns data in 3.22.6 but works in 3.22.5

### Steps to reproduce the issue

Go to Project Properties, Metadata, Keywords tab.
Create a Concept called 'render' and add its value 'edit'
Click Apply, then OK

Create a Temporary Scratch Layer of Point geometry and add one point on the project.

Then, go to the Properties of that layer, Symbology and switch to Rule-based
Add a rule filter: @project_keywords['render']='edit'

In 3.22.5 you will see the point layer
In 3.22.6 the point layer disappears

### Versions

QGIS version
3.22.6-Białowieża
QGIS code revision
b6f33b1a
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthDistanceCalculator
2.0.1
CalculateGeometry
0.5.1
Coordtransform
1.1
db-style-manager
0.8
DigitizingTools
1.5.1
FreehandRasterGeoreferencer
0.8.3
GeoCoding
2.18
LAStools
1.4
layerfromclipboard
0.12
MagneticDeclination
2.3.1
OpenTripPlannerPlugin
1.0
OSMDownloader
1.0.3
plaingeometryeditor
3.0.0
pluginbuilder3
3.2.1
plugin_reloader
0.8.2
poiexport
3.0.3
QuickOSM
2.0.1
shapetools
3.3.16
waymap
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by yannisps** [comment]
On further testing, the string that is returned from the @project_keywords['render'] has white spaces. 
When used with the trim string function, the filter works:
trim(@project_keywords['render']) = 'edit'

It seems the issue is with string management in the new version.

The project file has the keyword without white spaces
    <keywords vocabulary="render">
      <keyword>edit</keyword>
    </keywords>

**Comment by elpaso** [comment]
I don't think this is a bug: 

```python
context = QgsExpressionContext()
context.appendScope(QgsExpressionContextUtils.projectScope(QgsProject.instance()))
QgsExpression("@project_keywords['render']").evaluate(context)
['edit']
QgsExpression("@project_keywords['render'][0]").evaluate(context)
'edit'
```

**Comment by yannisps** [comment]
Hi Alessandro,

The bug is on the filters surfacing the data within the Filter.  It works
in the console but not in the filter as seen in the two screenshots below.

Best regards

Yannis



[image: image.png]
[image: image.png]

**Comment by yannisps** [comment]
Hi @elpaso,

The reported issue is that there is a change between 3.22.5 and 3.22.6 which is documented via the screenshots below.  The Metadata section is less than documented and this report.

The working answer in 3.22.6 shows that the second column "Keywords" is no longer a string as it was up until 3.22.5 but is an array of strings.  The screen does not show this as an array but as a single editable text field, hence the bug report.

Is it then right to represent a single text field as an array? 

Filter in 3.22.6 (not working)
![image](https://user-images.githubusercontent.com/5938098/168750398-1adc760e-dbaf-4df7-8255-3bda758f0b6a.png)

Filter in 3.22.6 (amended filter, working)
![image (1)](https://user-images.githubusercontent.com/5938098/168750433-a0247164-d13e-44c3-8b80-7effd49ab7de.png)

Filter in 3.22.5 (working)
![image (2)](https://user-images.githubusercontent.com/5938098/168750458-22e5fddf-baa1-46ac-9f75-aadaee267d6d.png)

**Comment by agiudiceandrea** [comment]
Maybe this PR https://github.com/qgis/QGIS/pull/47558 backported to 3.22.6 https://github.com/qgis/QGIS/pull/47562) could have changed the behaviour.
