### ISSUE TITLE
QGIS Server Problem with XML namespace - different GetCapabilities response using NGINX or Apache

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#48508]
### What is the bug or the crash?

While I think this problem is not directly related to QGIS Server, others users could face the same problem. The problem is that suddenly my previous QGIS Server project stopped working. After looking what was wrong I noticed that the GetCapabilities response returned by apache was different as it was was before :

**_Apache Response_** (the whole response [in pastebin](https://pastebin.com/ibfkdwCA))

```
<ns0:WMS_Capabilities xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost:8089/qgis_server?SERVICE=WMS&REQUEST=GetSchemaExtension" version="1.3.0">
<ns0:Service>
<ns0:Name>WMS</ns0:Name>
<ns0:Title>Untitled</ns0:Title>
<ns0:KeywordList>
<ns0:Keyword vocabulary="ISO">infoMapAccessService</ns0:Keyword>
</ns0:KeywordList>
<ns0:OnlineResource ns2:type="simple" ns2:href="http://localhost:8089/qgis_server"/>
<ns0:Fees>None</ns0:Fees>
<ns0:AccessConstraints>None</ns0:AccessConstraints>
</ns0:Service>
```

As you can see the XML elements have a namespace (ns with a number : ns0, ns1, ns2, etc.). It happens suddenly and it was working fine before. So it might be related to some packages that have been updated.

The same GetCapabilities Query on the same machine but using nginx give me that : 

**_NGINX Response_** (the whole response [in pastebin](https://pastebin.com/MajYtLvu))

```
<WMS_Capabilities xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost/qgis_server?SERVICE=WMS&REQUEST=GetSchemaExtension" version="1.3.0">
<Service>
<Name>WMS</Name>
<Title>Untitled</Title>
<KeywordList>
<Keyword vocabulary="ISO">infoMapAccessService</Keyword>
</KeywordList>
<OnlineResource xlink:href="http://localhost/qgis_server" xlink:type="simple"/>
<Fees>None</Fees>
<AccessConstraints>None</AccessConstraints>
</Service>
```

The problem is with the namespaces automatically added QGIS Desktop can't read the response as other web mapping client such as Lizmap. 

I know this is not directly related to QGIS Server, but if someone have an explanation that would help me a lot.

Thanks 

### Steps to reproduce the issue

1. Do a GetCapabilities with nginx or apache
2. Different XML response

### Versions

QGIS 3.22 (tried also with 3.16 same result)
Ubuntu 22.04 (tried also with ubuntu 20.04)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rldhont** [comment]
@arno974 which apache modules are activated in your config ?

It seems the response has been validated and rewrote by apahe. If you take a look at the first lines:

WIth NGINX which is exactly the XML provided by QGIS Server:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<WMS_Capabilities 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xmlns:sld="http://www.opengis.net/sld" xmlns:qgs="http://www.qgis.org/wms" 
    xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost/qgis_server?SERVICE=WMS&amp;REQUEST=GetSchemaExtension" 
    xmlns="http://www.opengis.net/wms" 
    version="1.3.0">
```
With Apache, the namespace aliases are updated, the xlink one is moved to document element and the first line is removed:
```xml
<ns0:WMS_Capabilities 
    xmlns:ns0="http://www.opengis.net/wms" 
    xmlns:ns2="http://www.w3.org/1999/xlink" 
    xmlns:ns3="http://www.opengis.net/sld" 
    xmlns:ns4="http://www.qgis.org/wms" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:schemaLocation="http://www.opengis.net/wms http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd http://www.opengis.net/sld http://schemas.opengis.net/sld/1.1.0/sld_capabilities.xsd http://www.qgis.org/wms http://localhost:8089/qgis_server?SERVICE=WMS&amp;REQUEST=GetSchemaExtension" 
    version="1.3.0">
```

**Comment by rldhont** [comment]
@arno974 do you have [mod_proxy_html](https://httpd.apache.org/docs/trunk/mod/mod_proxy_html.html) and/or [mod_xml2enc](https://httpd.apache.org/docs/trunk/mod/mod_xml2enc.html) activated ?

**Comment by arno974** [comment]
Hi René-Luc,

My current Apache modules loaded are :

- core_module (static)
-  so_module (static)
-  watchdog_module (static)
-  http_module (static)
-  log_config_module (static)
-  logio_module (static)
-  version_module (static)
-  unixd_module (static)
-  access_compat_module (shared)
-  alias_module (shared)
-  auth_basic_module (shared)
-  authn_core_module (shared)
-  authn_file_module (shared)
-  authz_core_module (shared)
-  authz_host_module (shared)
-  authz_user_module (shared)
-  autoindex_module (shared)
-  cgi_module (shared)
-  deflate_module (shared)
-  dir_module (shared)
-  env_module (shared)
-  fcgid_module (shared)
-  filter_module (shared)
-  headers_module (shared)
-  mime_module (shared)
-  mpm_prefork_module (shared)
-  negotiation_module (shared)
-  php_module (shared)
-  proxy_module (shared)
-  proxy_http_module (shared)
-  reqtimeout_module (shared)
-  rewrite_module (shared)
-  setenvif_module (shared)
-  socache_shmcb_module (shared)
-  ssl_module (shared)
-  status_module (shared)

**Comment by arno974** [comment]
After day of searching, I've found that the problem comes from a custom QGIS Server plugins... 
Nothing related to Apache or NGINX.
