### ISSUE TITLE
QGIS Server should degrade gracefully when (only) one layer has errors

### ISSUE THREAD

**Issue by rdewit** [qgis/QGIS#48507]
### What is the bug or the crash?

When trying to access the QGIS Server WFS or WMS service where one of the layers has an error (e.g. shapefile is not available anymore), the whole service fails with the error `<ServerException>Layer(s) not valid</ServerException>`.

Imagine we have 2 layers: 'Road' and 'Railway'. When the source of the 'Road' has been removed for example, the `GetCapabilities` (both WMS and WFS) as well as any request for the remaining layer(s), like `GetFeature` or `DescribeFeatureType` will not work and produce the same error as above.

Besides the error `Layer(s) not valid` being quite cryptic for someone that may not have access to the error logs, I'd expect the whole service (with potentially many dozens of layers) to **not** completely fail when only one of the layers has a problem.

Ideally, the `GetCapabilities` would return all other valid layers and would in the comments show what layer has a problem, so operations on other layers would keep working as expected. When a user tries to access the faulty layer, an appropriate exception would be returned.

Happy to provide more information if/where needed.

Below is a snippet of our error log (note that the request was for a layer unrelated to the one that has an issue):

```
12:14:15 INFO Server[7496]: ******************** New request ***************
[...]
12:14:15 INFO Server[7496]: REQUEST:GetFeature
12:14:15 INFO Server[7496]: SERVICE:WFS
12:14:15 INFO Server[7496]: TYPENAME:Railway
12:14:15 INFO Server[7496]: VERSION:1.1.0
12:14:15 WARNING OGR[7496]: Cannot open <PATH TO>/Road.shp.()
12:14:15 CRITICAL Server[7496]: Error, Layer(s) Road_3acfc27c_4320_4c25_92a9_f9f8cce0571c not valid in project <PATH TO>/vicmap-tmp.qgs
12:14:15 WARNING Server[7496]: <ServerException>Layer(s) not valid</ServerException>
```

### Steps to reproduce the issue

1. Create a project
2. Add 2 vector layers
3. Enable QGIS server in project file and save
4. Confirm both layers are available in the `GetCapabilities` (WMS and WFS)
5. Remove the source of one vector layer in the file system
6. Re-request the `GetCapabilities`
7. Observe the error
8. Request `GetFeature` for the remaining, valid layer
9. Observe the same error

### Versions

**Env:** Windows 64-bit
**QGIS version:** 3.16 LTR as well as 3.22 LTR (both for OSGeo4W)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by arno974** [comment]
Hi,

Did you try to add the option QGIS_SERVER_IGNORE_BAD_LAYERS with value 1 to your apache/nginx configuration ?
This should avoid this problem. More option here -> https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables

**Comment by rdewit** [comment]
> Hi,
> 
> Did you try to add the option QGIS_SERVER_IGNORE_BAD_LAYERS with value 1 to your apache/nginx configuration ? This should avoid this problem. More option here -> https://docs.qgis.org/3.22/en/docs/server_manual/config.html#environment-variables

😳 How could I have missed that? Yes, that solves the problem. Thanks so much, @arno974, I'll close the issue.
