### ISSUE TITLE
Reading GeoParquet in QGIS

### ISSUE THREAD

**Issue by rafapereirabr** [qgis/QGIS#48517]
### Feature description

[GeoParquet](https://github.com/opengeospatial/geoparquet) is a new geospatial vector data format that is built on Parquet. It looks super efficient in terms of storage and loading/saving data files. It would be great if QGIS had the capability to read GeoParquet files without users having to develop plugins. 

Here is an example of a GeoParquet file: [example.parquet](https://github.com/opengeospatial/geoparquet/blob/main/examples/example.parquet).

**Comment by DelazJ** [comment]
The best way to have QGIS read it is to have it read by GDAL, which seems to be the case if I understand https://gdal.org/drivers/vector/parquet.html. So the fix is to install a QGIS version that embarks GDAL 3.5 (maybe Windows nightlies have it already?)

**Comment by jef-n** [comment]
> So the fix is to install a QGIS version that embarks GDAL 3.5 (maybe Windows nightlies have it already?)

https://lists.osgeo.org/pipermail/qgis-developer/2022-May/064730.html

**Comment by nmarchio** [comment]
Just to flag: it looks like the MacOS QGIS 3.26.3 currently ships with GDAL 3.3.2 which doesn't support GeoParquet files (Windows ships with GDAL 3.5.1).

I did some testing and was able to confirm this is the case. GeoParquet files load fine on Windows and in MacOS QGIS throws an invalid data source error. 

Would it be possible to update the MacOS QGIS release to use GDAL 3.5.1?

**Comment by doublebyte1** [comment]
I am on QGIS 3.34.4-Prizren, which ships with GDAL 3.8.4. In theory, [the support for geoparquet should be there from GDAL 3.5](https://gdal.org/drivers/vector/parquet.html), but I am still unable to read geoparquet files.

Any updates or pointers to make it work, would be really appreciated!

![Screenshot from 2024-04-16 12-47-17](https://github.com/qgis/QGIS/assets/1038897/cf35cb36-0e75-4058-a61a-949b313c7a21)

![Screenshot from 2024-04-16 12-46-41](https://github.com/qgis/QGIS/assets/1038897/4eb71069-1212-46b2-bbc7-65a7c501bf24)


`Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.4 LTS
Release:	22.04
Codename:	jammy`

**Comment by agiudiceandrea** [comment]
@doublebyte1 , please provide the full QGIS version info: "In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."

**Comment by doublebyte1** [comment]
@agiudiceandrea 

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.4-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.37.2
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
SensorThingsAPI | 1.1.12
quick_map_services | 0.19.34
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

**Comment by agiudiceandrea** [comment]
@doublebyte1 , how have you installed QGIS on your system? If using Flatpak, then the issue is due to a an issue in the Flatpak build of the GDAL library https://github.com/flathub/org.qgis.qgis/issues/272

**Comment by jef-n** [comment]
arrow is not yet in debian (and ubuntu), see https://bugs.debian.org/970021 (and https://lists.debian.org/debian-gis/2024/03/msg00002.html ff)

**Comment by agiudiceandrea** [comment]
> arrow is not yet in debian (and ubuntu)

@jef-n, Ubuntu 22.04 ships GDAL 3.4.1, so it looks like @doublebyte1 isn't using GDAL privided by his Ubuntu 22.04 system.

**Comment by jef-n** [comment]
> @jef-n, Ubuntu 22.04 ships GDAL 3.4.1 according to https://packages.ubuntu.com/search?keywords=gdal, so it looks like @doublebyte1 isn't using GDAL privided by his Ubuntu 22.04 system.

My guess would be ubuntugis, which has GDAL 3.8.4, proj 9.3.1 and geos 3.12.1 - and no arrow.

**Comment by doublebyte1** [comment]
@jef-n @agiudiceandrea https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu jammy InRelease

**Comment by prusswan** [comment]
> > @jef-n, Ubuntu 22.04 ships GDAL 3.4.1 according to https://packages.ubuntu.com/search?keywords=gdal, so it looks like @doublebyte1 isn't using GDAL privided by his Ubuntu 22.04 system.
> 
> My guess would be ubuntugis, which has GDAL 3.8.4, proj 9.3.1 and geos 3.12.1 - and no arrow.

yeah this is unfortunate, just found out this is the reason why ogr2ogr (bundled as part of QGIS) does not support parquet as a format, while I had no issue loading parquet in Anaconda (which is a separate Python environment from QGIS). There is also [gpq](https://github.com/planetlabs/gpq) if you just need to convert GeoJSON <-> GeoParquet

**Comment by prusswan** [comment]
> Any viable solution for ubuntu 22.04? `GDAL 3.8.4` from official deb repositories does not support `parquet` files, nor QGIS

See flathub/org.qgis.qgis#272

**Comment by prusswan** [comment]
So there is a workaround for flatpak build (PR that builds with geoparquet support but yet to be merged).

The other option is to contact the UbuntuGIS team. https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable

I don't fully understand the process, but it appears to me that without a system package for arrow available, the maintainers of the qgis package for Debian/Ubuntu will need to build the arrow dependencies from source (which they may or may not want to do).

@agiudiceandrea can you reopen this?

**Comment by agiudiceandrea** [comment]
@prusswan, AFAIK the issue is not due to QGIS itself: it's a downstream issue and there is nothing in the QGIS source code that can be changed in order to fix such issue.
AFAIK [QGIS distributed by Conda-forge](https://aneto.pt/posts/tutorials/2019-05-29-using-qgis-from-conda/) is able to handle GeoParquet layers.

**Comment by prusswan** [comment]
> @prusswan, AFAIK the issue is not due to QGIS itself: it's a downstream issue and there is nothing in the QGIS source code that can be changed in order to fix such issue. AFAIK [QGIS distributed by Conda-forge](https://aneto.pt/posts/tutorials/2019-05-29-using-qgis-from-conda/) is able to handle GeoParquet layers.

@agiudiceandrea conda-forge is an option but this is not always suitable if only the gdal command line tools is needed (conda is additional overhead). QGIS *could* do something by informing users there are additional dependencies needed for parquet driver to work (granted, this is useless for most users if they need to build the software). At this point, QGIS installers for Linux are listed on the website. QGIS also bundles gdal tools (without providing options for users to choose/use a different version with the drivers they need), so if gdal tools (as part of the larger QGIS bundle) are "broken" or do not meet user expectations, imho this is still partly a QGIS issue. Anyway I did contact UbuntuGIS team while relying on the unofficial flatpak build in the mean time..

**Comment by do-me** [comment]
> @prusswan, AFAIK the issue is not due to QGIS itself: it's a downstream issue and there is nothing in the QGIS source code that can be changed in order to fix such issue. AFAIK [QGIS distributed by Conda-forge](https://aneto.pt/posts/tutorials/2019-05-29-using-qgis-from-conda/) is able to handle GeoParquet layers.

For anyone reading this issue, here is the code: https://github.com/qgis/QGIS-Mac-Packager/issues/156#issuecomment-1630959088

**Comment by prusswan** [comment]
@byander long story short, QGIS maintainers (for this repo) see this as a downstream issue. Linux is not exactly a monolith either, so whoever that is building QGIS on some specific distro, may or may not see this as a priority (geoparquet support is "optional" and builders can exclude the functionality if they choose to build gdal without parquet support), judging from the situation with flatpak and UbuntuGIS builds.

What the QGIS project **can** do (imho) is to make geoparquet support mandatory, so downstream builders cannot just exclude/ignore this functionality

@rouault what's your take on this situation on Linux? not saying this is gdal's responsibility of course

**Comment by rouault** [comment]
> what's your take on this situation on Linux?

not much to add. Packaging is a galaxy over which upstream projects have little influence on. libarrow/libparquet are difficult beats to package because they have difficult dependencies (AWS SDK CPP in particular) that make it difficult to attract volunteers
