### ISSUE TITLE
Support for native mac m1

### ISSUE THREAD

**Issue by amorfinv** [qgis/QGIS#48531]
### Feature description

Hello,

From what I can tell, most dependencies are now available natively in ```osx_arm64``` architecture. The last big holdout was ```pyqt5```. However, that is now available via ```conda-forge``` ([here](https://github.com/conda-forge/qt-main-feedstock)) 

I looked at QGIS dependencies that come via ```conda-forge``` and it seems like only a couple dependencies had some issues. Since the ```conda-forge``` version is at 3.18 perhaps some of these aren't required for latest qgis.

Qt related libraries missing in osx-arm64 via ```conda-forge``` 
- ```pyqt-impl```  - deprecated in Qt5.15?
- ```qtkeychain``` - available with homebrew
- ```qtlocation``` - seems to come with ```qt-main``` 
- ```qtserialport``` - seems to come with ```qt-main```
- ```pyqtwebkit``` and ```qtwebkit```   - can be ignored? use ```pyqtwebengine``` or ```qtwebengine```
- ```qca``` - available with homebrew
- ```qjson``` - available with homebrew
- ```qscintilla2```- available with homebrew
- ```qwtpolar``` - available with homebrew (only big sur) [here](https://formulae.brew.sh/formula/qwtpolar#default)

Other missing libraries in osx-arm64 via ```conda-forge``` 
- ```libtasn1``` - available with homebrew

I am going to attempt to build with these and report any updates. I have never tried before so may take a while.

-Andres

**Comment by nyalldawson** [comment]
Proper support for M1 wasn't added until qt version 6, and qgis isn't yet compatible with that. You may get somewhere with the qt 5 packages but ultimately support needs to wait till the (in progress) qt 6 port is complete.

**Comment by amorfinv** [comment]
Hello @nyalldawson ,

Thanks for the response. I am happy to help with qt6 transition if needed. 

I am excited to get a qgis native build on M1. I will close this for now then.
