### ISSUE TITLE
Custom projection behavior incorrect in two ways

### ISSUE THREAD

**Issue by geoglrb** [qgis/QGIS#48533]
### What is the bug or the crash?

According to the proj website ( https://proj.org/operations/conversions/noop.html ) when coordinates are reprojected into the projection "+proj=noop" the outputs should be the same as the inputs.

There are two resulting bugs using this projection in the 'Test' under Custom Projections in MacOS 3.24.2, Windows 3.24.2, and Linux 3.24.2.

1) The inputs are treated as degrees and converted to radians for output, whereas the same numbers inputted should emerge as outputs;

2) The outputs are flipped in x,y.

NOTE: It _seems_ that in 3.18 the output flip had not yet occurred.

 

### Steps to reproduce the issue

In Settings > Custom Projections...

Set Format to "Proj String"

Change Parameters to:   `+proj=noop`

Under Test, enter Latitude as 10 and Longitude as 180.

Resulting coordinates are: 3.1416 and 0.1745

As noted above, this poses two problems. First, the inputs and outputs are not the same--it appears the degrees are treated as degrees and converted to radians, which is not what the proj manual says should happen. Second, the x and y coordinates are swapped.

### Versions

As noted above, I am comparing behavior on several platforms. Here, I paste in my MacOS 3.24.2 info for convenience:

 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.24.2-Tisler | QGIS code revision | 573ca40c96
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.3

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rouault** [comment]
Using +proj=noop doesn't make sense in QGIS context
