### ISSUE TITLE
unselectable polygon, not part of any layer, cannot be removed - where to look for its geometry?

### ISSUE THREAD

**Issue by fgfletcher** [qgis/QGIS#48548]
### What is the bug or the crash?

A polygon was created in a project (probably using Shape Tools) which is not part of any layer and cannot be selected, moved or deleted.
Turning off all layers - polygon still present.
Deleted project's .qgz.mldata file, restarted QGIS, opened project - polygon still present
Using Settings > new profile (so only standard plugins installed) - polygon still present.
Opening project with QGIS 3.16 LTR, 3.20, 3.22, 3.24 - polygon still present.

Question: where could the polygon data be being stored?  
It must be in some project specific file, but apparently not in the .qgz.mldata file.
So in the project .qgz file?  What would it look like so I can find it and delete it.

### Steps to reproduce the issue

Unknown as to how the polygon was created in the project.

### Versions

QGIS 3.16, 3.20, 3.22, 3.24
All running under Mac OS X 10.13.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by fgfletcher** [comment]
removed ~/Library/Cashes/QGIS/QGIS3, restarted QGIS, opened project - polygon still present

**Comment by nicogodet** [comment]
Annotations ?

**Comment by fgfletcher** [comment]
Yes, it is an annotation. Thank you!!!
I looked for hours and never thought of that.
It isn't clear how to delete the polygon so I set the rendering opacity to 0 and problem is solved.
Thanks again!

**Comment by fgfletcher** [comment]
Very simple to select using "Modify Annotations" tool and then delete.
The mansion of QGIS is huge with innumerable rooms - after spending 5 years exploring it there still remains vast unexplored areas...

**Comment by AiSwathiV** [comment]
> Annotations ?

Thank you, this helped me too.
