### ISSUE TITLE
Spelling mistake in German translation: 'Jahrszehl'

### ISSUE THREAD

**Issue by Norwi** [qgis/QGIS#48549]
### What is the bug or the crash?

The German translation for 'Year number. Years 1 to 99 are interpreted as is. Year 0 is invalid.' is wrong. 'Jahrszehl' should be 'Jahreszahl'. It can be found in i18n/qgis_de.ts in line 65285.

### Steps to reproduce the issue

1. Set user interface translation to German 
2. Click on 'Feldrechner öffnen' -> 'Datum und Zeit' -> 'make_date'
3. See description for argument 'year'
![jahrszehl](https://user-images.githubusercontent.com/18899671/168425302-17b5fafc-af37-4605-b87b-f9a947547979.png)

### Versions

QGIS version 3.24.2-Tisler ([13c1a02865](https://github.com/qgis/QGIS/commit/13c1a02865))

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
Fixed in transifex
