### ISSUE TITLE
native:rasterlayerstatistics SUM_OF_SQUARES replication

### ISSUE THREAD

**Issue by cefect** [qgis/QGIS#48576]
### What is the bug or the crash?

I'm having trouble replicating the output of algorithm [native:rasterlayerstatistics](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/qgis/rasteranalysis.html?highlight=qgis%20rasterlayerstatistics#raster-layer-statistics) , specifically SUM_OF_SQUARES. 

Can someone point me to the source code?  I found [qgsrasterbandstats.h](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsrasterbandstats.h
), but got lost in the C.

Thank you,

### Steps to reproduce the issue

compute cells^2 using raster calculator. compute sum. compare to algo output

### Versions

3.16.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@cefect can you try to reproduce on a recent version? (3.22 or 3.24) 3.16 is no longer being maintained. Also, try and reproduce the same behaviour ou a new profile, it might be plugin related.

**Comment by alexbruy** [comment]
Sum of squares is not what you are calculating with cells^2 formula.

**Comment by cefect** [comment]
@alexbruy thank you for the clarification. Can you point me to the source code so I can see what is meant to be calculated by this?
