### ISSUE TITLE
Proj.db and gcs.csv not found for GDAL tools on QGIS 3.22 Mac all-in-one installer

### ISSUE THREAD

**Issue by R4Roman** [qgis/QGIS#48574]
### What is the bug or the crash?

merge give an error on QGIS3.22 Mac because it can't find proj.db and gcs.csv. On windows 11 through parallels it works fine, no errors.

"ERROR 1: PROJ: proj_create_from_database: Cannot find proj.db" - this can be fixed using method described here: https://github.com/qgis/QGIS/issues/39801

"ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files." - this issue can not be fixed (path to gdal folder is specified, if check using os.environ)

### Steps to reproduce the issue

go to raster -> merge and try to merge something

### Versions

QGIS version: 3.22.7-Białowieża
QGIS code revision: 5a65627acb
Qt version: 5.14.2
Python version: 3.8.7
GDAL version: 3.2.1
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 6.3.2, May 1st, 2020

macOS: 12.3.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Maybe better to (also) report to the QGIS-Mac-Packager repository https://github.com/qgis/QGIS-Mac-Packager/issues

**Comment by rouault** [comment]
> "ERROR 4: Unable to open EPSG support file gcs.csv. Try setting the GDAL_DATA environment variable to point to the directory containing EPSG csv files." - this issue can not be fixed (path to gdal folder is specified, if check using os.environ)
> ###

that error message comes from GDAL < 3. I suspect a mix of GDAL versions on your system

**Comment by Rikuoja** [comment]
Having the same problem with all 3.22 versions, including LTR.

"PROJ_LIB" env variable is not set in QGIS python console. All other GDAL env variables seem to be correctly set.

os.environ
environ({'USER': 'riku', '__CFBundleIdentifier': 'org.qgis.qgis3', 'COMMAND_MODE': 'unix2003', 'LOGNAME': 'r
