### ISSUE TITLE
QgsProcessingParameterFile warning messages and macOS: error unknown

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#48598]
### What is the bug or the crash?

The QgsProcessingParameterFile processing parameter can be used to collect file pathes for a QgsProcessingAlgorithms.
This is usefull to collect none-standard / none-geospatial file formats which are required to run an algorithm.

However, 
1. calling QgsProcessingParameterFile functions like `.valueAsString(...)`, `.valueAsPythonString(...)` or `.valueAsJsonObject(...)` cause that other dataproviders (gdal, ogr, pdal, ...) try opening the file path collected by the QgsProcessingParameterFile . As this fails, warning messages are shown. This is missleading, because at this point nobody expects a data provider to open the file.

![grafik](https://user-images.githubusercontent.com/1404870/168999050-1ec9d0cd-5f5c-4cde-b82e-4232402ad157.png)

![grafik](https://user-images.githubusercontent.com/1404870/168999106-70a1f8c5-629f-48c1-af78-3c583813d979.png)

2. In case of macOS the hidden tests agains different data providers can lead to a crash with Exception: unknown. This can kill the algorithm execution, e.g. when running it from a AlgorithmDialog where the algorithms `.asMap(...)` function is called to save the history details, which itself will calls the parameters `.valueAsJsonObject(...)` .

```
/Applications/QGIS.app/Contents/MacOS/bin/python3 "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py" --multiproc --qt-support=auto --client 127.0.0.1 --port 49522 --file /Users/jakimowb/Repositories/enmap-box/tests/src/issues/test_issue_1330_QGIS.py
Connected to pydev debugger (build 211.7442.45)
Application state:
QGIS_PREFIX_PATH env var:       /Applications/QGIS.app/contents/MacOS
Prefix:     /Applications/QGIS.app/contents/MacOS
Plugin Path:        /Applications/QGIS.app/contents/MacOS/../PlugIns/qgis
Package Data Path:  /Applications/QGIS.app/contents/MacOS/../Resources
Active Theme Name:  
Active Theme Path:  /Applications/QGIS.app/contents/MacOS/../Resources/resources/themes//icons/
Default Theme Path: :/images/themes/default/
SVG Search Paths:   /Applications/QGIS.app/contents/MacOS/../Resources/svg/
        /tmp/QGIS-PythonTestConfigPathfe6_5gvl/profiles/default/svg/
User DB Path:   /Applications/QGIS.app/contents/MacOS/../Resources/resources/qgis.db
Auth DB Path:   /tmp/QGIS-PythonTestConfigPathfe6_5gvl/profiles/default/qgis-auth.db

OGR(1): Cannot open /private/var/folders/1d/23g39kb961387shpwfm6lh280000gn/T/processing_wqOGjl/f4ef3715d3e148c6a67fcf8e8ed255b4/tempfile.txt ().()
ERROR 4: `/private/var/folders/1d/23g39kb961387shpwfm6lh280000gn/T/processing_wqOGjl/f4ef3715d3e148c6a67fcf8e8ed255b4/tempfile.txt' not recognized as a supported file format.
ERROR 4: `/private/var/folders/1d/23g39kb961387shpwfm6lh280000gn/T/processing_wqOGjl/f4ef3715d3e148c6a67fcf8e8ed255b4/tempfile.txt' not recognized as a supported file format.
ERROR 4: `/private/var/folders/1d/23g39kb961387shpwfm6lh280000gn/T/processing_wqOGjl/f4ef3715d3e148c6a67fcf8e8ed255b4/tempfile.txt' not recognized as a supported file format.
ERROR 4: `/private/var/folders/1d/23g39kb961387shpwfm6lh280000gn/T/processing_wqOGjl/f4ef3715d3e148c6a67fcf8e8ed255b4/tempfile.txt' not recognized as a supported file format.
ERROR: Status 3: Unable to load mesh (null)
Traceback (most recent call last):
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/pydevd.py", line 1483, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "/Applications/PyCharm CE.app/Contents/plugins/python-ce/helpers/pydev/_pydev_imps/_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "/Users/jakimowb/Repositories/enmap-box/tests/src/issues/test_issue_1330_QGIS.py", line 12, in <module>
    print(f'asString={parameter.valueAsString(path, context)}')
Exception: unknown
```

### Steps to reproduce the issue

run this code in a macOS QGIS python shell:

```
import pathlib
context = QgsProcessingContext()
parameter = QgsProcessingParameterFile('file', fileFilter='Any file (*.*)')
path = QgsProcessingUtils.generateTempFilename('tempfile.txt')
with open(path, 'w') as f:
    f.write('Dummy')
assert pathlib.Path(path).is_file()
assert parameter.checkValueIsAcceptable(path, context)
print(f'asString={parameter.valueAsString(path, context)}')
print(f'asPythonString={parameter.valueAsPythonString(path, context)}')
print(f'asJsonObject={parameter.valueAsJsonObject(path, context)}')
```

### Versions

QGIS for macOS 3.24
QGIS OSGeo4W 3.25 rev [95a55f9782](https://github.com/qgis/QGIS/commit/95a55f9782)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Related issue #46534.

**Comment by lbartoletti** [comment]
I have a similar issue on QGIS 3.26 (only tested on FreeBSD for now), with [LSCI plugin](https://gitlab.com/Oslandia/qgis/landsurveycodesimport)

But, it's ok on QGIS 3.22.

**Comment by SirChasm** [comment]
I continue to have this same problem when running scripts for all versions after 3.22.* (just confirmed in 3.26.3). As a result most macOS users I know can't use any of those updates.

**Comment by nyalldawson** [comment]
Just for completeness: the issue does NOT affect valueAsPythonString, only valueAsString/valueAsJsonObject
