### ISSUE TITLE
QGIS 3.22.6 - Mode d'édition multiple

### ISSUE THREAD

**Issue by Apgl-64** [qgis/QGIS#48612]
### What is the bug or the crash?

Bug : au passage en mode édition multiple, les entités sélectionnées sont mises à jour automatiquement avec les attributs d'un des éléments de la sélection

### Steps to reproduce the issue

1 : ouvrir une table d'attribut
2 : sélectionner des entités
3 : passer en mode édition multiple

### Versions

3.22.6

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Pas de problème avec la version 3.16

**Comment by roya0045** [comment]
This is a duplicate, already reported #47936
