### ISSUE TITLE
DXF export on Windows 11 Access Violation

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#48626]
### What is the bug or the crash?

Immediate crash when exporting to DXF setting parameters

## User Feedback

Exporting to DXF

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000035b0 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.25.0-Master
QGIS code revision: 400fa80ec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0dev-fea1523496
Running against GDAL: 3.6.0dev-efd4398104

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Export DXF using Project, export DXF and clip to map extent

### Versions

happens on 3.24 and dev version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Using dev version on purpose, but I tried also 3.24

Following are the settings used
![image](https://user-images.githubusercontent.com/4627073/169171206-9822b79d-5042-4dd5-a463-9c314e70c210.png)

**Comment by antoniolocandro** [comment]
The project has temporary scratch layers which I do not know if they make a difference in the issue

**Comment by antoniolocandro** [comment]
Access violation doesn't happen if set to no symbology, so something about the symbology makes the project crash on export to DXF

**Comment by rouault** [comment]
We would need access to a minimum stanalone project+datasets that can reproduce the issue
