### ISSUE TITLE
Python error on start up when processing core plugin is enabled.

### ISSUE THREAD

**Issue by davethegeo** [qgis/QGIS#48647]
### What is the bug or the crash?

Python error is displayed on start up. 
"Python error: An error has occurred while executing Python code: See message log (Python Error) for more details."
Python Error details in the log are;
 "2022-05-19T10:13:50     WARNING    Traceback (most recent call last):
              File "D:\Program Files/QGIS 3.24.0/apps/qgis/./python/plugins\processing\script\ScriptAlgorithmProvider.py", line 119, in loadAlgorithms
              folder = ScriptUtils.resetScriptFolder(folder)
              File "D:\Program Files/QGIS 3.24.0/apps/qgis/./python/plugins\processing\script\ScriptUtils.py", line 115, in resetScriptFolder
              commonSettingPath = os.path.join(paths[appIndex], paths[profileIndex])
             IndexError: list index out of range"

When I disable the Processing plugin, QGIs works perfectly.

### Steps to reproduce the issue

Tried different versions and different projects

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.4
CalculateGeometry
0.6.4
Coordtransform
1.1
joinmultiplelines
Version 0.4.1
latlontools
3.6.2
linecomparison
0.1
LocatePoints
0.3.4
openlayers_plugin
2.0.0
ParallelLineConstruction
0.2
qchainage
3.0.1
QPackage
1.5
quick_map_services
0.19.28
redLayer
2.2
shapetools
3.4.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@davethegeo Does it still occur even on a new profile with no plugins installed?

**Comment by elpaso** [comment]
I would not call a python error a "crash", unless the QGIS application actually crashed.

**Comment by davethegeo** [comment]
I could not resolve this issue by uninstalling plugins and creating a new profile. 
Finally however, by uninstalling QGIS completely from my PC, removing all references to "qgis" from the registry and installing a fresh copy of 3.24.3, the problem is resolved. No more python errors.

**Comment by davethegeo** [comment]
Yes you may close it. Problem solved.
