### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by nguyenvanthi2020** [qgis/QGIS#48643]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000047d0 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a02865
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.21996

### Steps to reproduce the issue

Close/Exit QGIS

### Versions

3.24.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@nguyenvanthi2020 Is it possible to reproduce the crash in any way? It might be plugin related.
