### ISSUE TITLE
mac-QGIS renders WMS in bad quality (QGIS3.22 on macOS 12.3) on HiRes-monitor

### ISSUE THREAD

**Issue by Kristianrev** [qgis/QGIS#48655]
### What is the bug or the crash?

When using a WMS-layer in Intel-Mac-QGIS, lines are like stairs and text is simply unreadable on my 27"-monitor of a resolution of 5120 × 2880 pix.
Is QGIS in general not rendering WMS well, or is QGIS specifically not supporting HiRes-monitors well? In ArcGIS 10.8 on Windows 10 the WMS is of fairly good quality. Also in norgeskart.no the layer is fairly good.

Here is a comparison between ArcGIS on Win and QGIS on macOS:
<img width="2559" alt="Skjermbilde 2022-05-19 kl  15 41 02" src="https://user-images.githubusercontent.com/103507781/169316702-507cc277-9718-4377-84cf-1a6c1412cd42.png">

### Steps to reproduce the issue

Load a WMS-layer, eg. https://openwms.statkart.no/skwms1/wms.topo4, in QGIS on an Intel-iMac 27".

### Versions

QGIS-LTR 3.22.5 on macOS 12.3 for Intel.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Profile is new.

**Comment by Kristianrev** [comment]
For the QGIS-project I used EPSG 25833. As far as I can understand GetCapabilities, this is supported (Image 1). Changing to 4258 doesn't make it better (Image 2). In ArcGIS the project was also set to EPSG 25833.

Can I force QGIS to use server-reprojection?

<img width="988" alt="Skjermbilde 2022-05-19 kl  17 23 01" src="https://user-images.githubusercontent.com/103507781/169335810-048f52d2-ebb6-4d1c-be1b-0ba64dc27b09.png">
<img width="1001" alt="Skjermbilde 2022-05-19 kl  17 31 42" src="https://user-images.githubusercontent.com/103507781/169336988-e0bbf51c-39c8-40a5-ad59-046cb38d003e.png">

**Comment by rduivenvoorde** [comment]
Can you open de Development Tools panel, zoom to Oslo, and then copy the URL that you see there.

![Screenshot from 2022-05-19 18-04-29](https://user-images.githubusercontent.com/731673/169346335-ebca0b92-48e9-4fdc-8a8d-4e951aa0c4c9.png)

For example for me QGIS is firing this url in Oslo:

https://openwms.statkart.no/skwms1/wms.topo4?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=267257.1535537759773,6652459.543410468847,267387.5518325266894,6652614.999259851873&CRS=EPSG:25833&WIDTH=791&HEIGHT=943&LAYERS=topo4_WMS&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE

(as you can see it is the exact same image as in my screenshot)

Eager to see what your QGIS is requesting...

Maybe the HDPI screen is playing up with this service...

You can maybe test this service: https://www.openbasiskaart.nl/mapcache/?SERVICE=WMS&VERSION=1.1.1&REQUEST=GetCapabilities which has both HDPI layers as normal layers. CRS = EPSG:28992

**Comment by Kristianrev** [comment]
... maybe a Feature-request:  changing the CRS with the button to the lower-right in the Status-bar does override the reprojection of CRS of added layers/WMS in the TOC.

Norway uses three standard-CRS: 25832, 25833 and 25835, so choosing "Use CRS from the first layer added" in the Options for CRS for Projects is a handy choice for e.g. local shapes.
