### ISSUE TITLE
TIN Mesh Creation bug - > to ply

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#48662]
### What is the bug or the crash?

Unable to create a TIN mesh as PLY

### Steps to reproduce the issue

Vector layer: points
Value on vertex - > Z value

Vactor layer

output format - > PLY
Output coordinate sytem -> EPSG:  5850

Output - > ply file

### Versions

QGIS version
3.24.1-Tisler
QGIS code revision
5709b824
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
HCMGIS
21.8.28
kmltools
3.1.19
LandSurveyCodesImport
0.3.0-beta7
lftools
1.6.1
lnns
1.0.7
nominatim
1.4.2
openlayers_plugin
2.0.0
OpenTopography-DEM-Downloader
1.0
osminfo
0.7.1
profiletool
4.2.2
qad
3.0.4
qgis_resource_sharing
1.0.0-beta1
QuickOSM
2.0.1
raster_tracer
0.3.2
spline
0.2
valuetool
3.0.15
volume_calculation_tool
0.4
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Algorithm 'TIN Mesh Creation' starting…
Input parameters:
{ 'CRS_OUTPUT' : QgsCoordinateReferenceSystem('EPSG:5850'), 'MESH_FORMAT' : 2, 'OUTPUT_MESH' : 'C:/Users/andreas.olsson/OneDrive - NYAB Sverige AB/MA1003_Saltängen/gis/befintlig asfalt/asfalt.ply', 'SOURCE_DATA' : [{'source': 'Ritning1_b29e85ff_a806_4c3b_8166_73d6276046f9','type': 0,'attributeIndex': -1}] }

Adding vertices layer(s) to the triangulation
Creating mesh from triangulation
Saving mesh to file
Execution completed in 0.12 seconds
Results:
{'OUTPUT_MESH': 'C:/Users/andreas.olsson/OneDrive - NYAB Sverige '
'AB/MA1003_Saltängen/gis/befintlig asfalt/asfalt.ply'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/andreas.olsson/OneDrive - NYAB Sverige AB/MA1003_Saltängen/gis/befintlig asfalt/asfalt.ply
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

**Comment by vcloarec** [comment]
@APOS80, I can't reproduce this issue, maybe you can share your vector layer data that leads to your issue?
