### ISSUE TITLE
.qml style ignored when opening a Mapinfo .TAB layer in qgis 3.22

### ISSUE THREAD

**Issue by ddt-adl-sig** [qgis/QGIS#48667]
### What is the bug or the crash?

The style renderer is automaticaly set to "Embedded Symbols" and the default style of the layer is ignored.  
"Embedded Symbols" is a great feature for some Mapinfo layers. **But when there is a QML default style, it should be applied**. In our organisation, basic users won't be able to find and apply the right qml.

### Steps to reproduce the issue

1. Open a Mapinfo .TAB layer
2. Go to the Layer Styling panel

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.7-Białowieża | QGIS code revision | 5a65627a
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.4.3
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
031_donnees | 1.0.0
creer_menus | 3.9.0
csv_helper | 0.9.0
localiserparcelle | 3.5.6
multi_user | 1.0.0
nettoyeur | 3.4.0
MemoryLayerSaver | 4.0.4
plugin_reloader | 0.9.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99

</body></html>QGIS version
3.22.7-Białowieża
QGIS code revision
[5a65627a](https://github.com/qgis/QGIS/commit/5a65627a)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
creer_menus
3.9.0
csv_helper
0.9.0
localiserparcelle
3.5.6
multi_user
1.0.0
nettoyeur
3.4.0
MemoryLayerSaver
4.0.4
plugin_reloader
0.9.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@ddt-adl-sig can you try with a new profile? it might be plugin related

**Comment by ddt-adl-sig** [comment]
@Pedro-Murteira same issue with a new profile all plugins disabled. With every TAB I tried : polygons, LineStrings...

**Comment by mnelsondnr** [comment]
I'm not sure if this is the same issue, but in 3.22.7, the .qml style is ignored if we have loaded a .sid raster layer. The map preview shows the style applied, but if the user clicks "Apply" or "Ok" the .qml is not applied and the map preview reverts to how it looked prior to loading the .qml.
