### ISSUE TITLE
Dialog to open an embedded project in Geopackage doesn't always show any projects in the user dialog combobox  

### ISSUE THREAD

**Issue by bvthomsen** [qgis/QGIS#48676]
### What is the bug or the crash?

The userdialog shown in QGIS menu "Project" -> "Open from" -> "GeoPackage..." won't show the embedded projects in the chosen geopackage.  

### Steps to reproduce the issue

- You have a GeoPackage with one or more  embedded project(s) 
- You try to open this project using QGIS menu "Project" -> "Open from" -> "GeoPackage..."
- In the "Load project from GeoPackage" userdialog , the "Project" combobox does not show any embedded projects if the wanted project happens to be in the first (and implicit selected) GeoPackage in the "connection" combobox dropdown list.
- However: *If* you first choose *another* geopackage and the  *re-choose* the original GeoPackage - the projects from the GeoPackage will be shown in the "Project" combobox.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code revision | ce8e65e9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
Dataforsyningen | 0.3
dmp_manager | 0.1
eco_model | 0.1
plotcut_docker | 0.3
pluginbuilder3 | 3.2.1
plugin_reloader | 0.8.2
QlrBrowser | 3.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.4-Białowieża
QGIS code revision
[ce8e65e9](https://github.com/qgis/QGIS/commit/ce8e65e9)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Dataforsyningen
0.3
dmp_manager
0.1
eco_model
0.1
plotcut_docker
0.3
pluginbuilder3
3.2.1
plugin_reloader
0.8.2
QlrBrowser
3.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by bvthomsen** [comment]
Sorry I didn't check that. And:

No I can't replicate the problem with a new profile. There is a new situation: 

- When working with a *fresh* profile and using QGIS menu "Project" -> "Open from" -> "GeoPackage...", the "Load project from GeoPackage" userdialog is shown *without* any Geopackages chosen. When the user then choose a geopackage from the drop-down list, the "project" combobox is populated with the projects inside the GeoPackage; i.e: The *correct* behaviour.

- In my *old* profile  and using QGIS menu "Project" -> "Open from" -> "GeoPackage...", the "Load project from GeoPackage" userdialog is shown *with* a GeoPackage already shown in the text part of "connection" combo-box - but without the "Project" combobox populated with project name(s) from the same geopackage. 
If the user then *a*: chooses another geopackage and *b*: re-choose the first geopakage the "Project" drop-down list will be filled with the names of the project inside the chosen geopackage.

I surmise, that some plugin or whatnot is setting the value of the "connection" combobox *without* triggering the "currentIndexChanged()" signal from the "connection" combobox, which would activate the function to fill the "project" drop-down list.

**Comment by elpaso** [comment]
Cannot reproduce on linux/master.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (2d64df22a4eb4e7e6718f747c9eb1ed4e5f81903) on Linux.
