### ISSUE TITLE
New GeoPackage layer cannot be loaded (QGIS thinks it's invalid but it isn't really)

### ISSUE THREAD

**Issue by mercergeoinfo** [qgis/QGIS#48671]
### What is the bug or the crash?

When creating a new GeoPackage layer in an existing GeoPackage the layer is created but cannot be added to the project by the "New GeoPackage Layer" tool. Instead it throws up an error "x is an invalid layer and cannot be loaded", where x is the layer name.
The layer has been created and can be loaded by using the Data Source Manager, it's just that the New GeoPackage Layer can't load it.

### Steps to reproduce the issue

1. Create a GeoPackage with a layer
2. Create a second layer in the same GeoPackage

### Versions

QGIS version 3.24.2 and QGIS version 3.24.3
 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried creating an object in the first layer before creating a new layer; it didn't help.

**Comment by Pedro-Murteira** [comment]
I can reproduce this aswell on both 3.24.3 and 3.22.7.

**Comment by mercergeoinfo** [comment]
Can confirm it occurs on the 3.22.7 LTR

**Comment by elpaso** [comment]
I can confirm on master.

**Comment by agiudiceandrea** [comment]
The issue doesn't occur with QGIS 3.24.0 (GDAL 3.4.1) or with previous versions (3.16.16, 3.20.3, ...).
It seems to me this issue is similar to https://github.com/qgis/QGIS/issues/48154.
It think it could be possible this issue is related to https://github.com/qgis/QGIS/pull/47098.

**Comment by antoniolocandro** [comment]
Today when creating a GPKG layer QGIS entered into crash mode and become not killable in Windows needed to reboot, when I rebooted and opened the GPKG the layer was indeed inside with all the fields, probably related to this issue.


QGIS version
3.25.0-Master
QGIS code revision
a96368e943
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.0dev-07147d9495
Running against GDAL/OGR
3.6.0dev-e0dbcbc021
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




This copy of QGIS writes debugging output.




Active Python plugins
cartography_tools
1.2.1
changeDataSource
3.1
DigitizingTools
1.5.1
latlontools
3.5.8
MemoryLayerSaver
4.0.4
mmqgis
2021.5.16
QPackage
1.5
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
