### ISSUE TITLE
QGIS version 3.22.6 freezes

### ISSUE THREAD

**Issue by jorgealpala** [qgis/QGIS#48679]
### What is the bug or the crash?

I have installed versions 3.22.6 and 3.22.7 and both of them freeze suddenly when I am using QGIS, I don't know if they require some additional plug-in but they don't work well.

### Steps to reproduce the issue

![Error-QGIS](https://user-images.githubusercontent.com/106001603/169676785-59189f2f-7c84-432c-b14c-194f543c67d8.png)

### Versions

3.22.6
3.22.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@jorgealpala It might be related to the data being used. Can you attach a data sample for testing?
