### ISSUE TITLE
LAS file not opening if folder has special character

### ISSUE THREAD

**Issue by uchris13** [qgis/QGIS#48703]
### What is the bug or the crash?

No error message, the LAS file wont open

### Steps to reproduce the issue

Drag and drop LAS file that is stored on a folder containing an special character. In my case Z:\HLD Projects Database\España -REE\Filename.las

### Versions

latest stable 3.22.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/41833

**Comment by DelazJ** [comment]
@nicogodet So it is fixed in master, right?

**Comment by saberraz** [comment]
Not yet. It gets indexed correctly but still you can not see the data.

**Comment by DelazJ** [comment]
I can't find if it was backported to 3.22 (what @uchris13 is using)

**Comment by wonder-sk** [comment]
Reopened #41833 and closing this one as a duplicate...
