### ISSUE TITLE
Problema al importar DXF

### ISSUE THREAD

**Issue by AMARINDU** [qgis/QGIS#48730]
### What is the bug or the crash?

Acabo de comenzar a  trabajar con el software QGIS el caso es que no logro importar ciertos archivos dxf, no se si será por el formato de los elementos del cad, linea, polilinea.

Me da el error fuente no valida al añadir capa, probando con la versión normal y la de largo plazo.

También he probado con el plugin anotherdxfimporter y me da error de proceso.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/106179656/170100295-2a1d092a-f415-48a3-805f-55818d43e0b7.png)

### Versions

Versión de QGIS
3.22.7-Białowieża
Revisión del código de QGIS
5a65627a
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.4.3
Versión de PROJ
9.0.0
Versión del registro de base de datos EPSG
v10.054 (2022-02-13)
Versión GEOS
3.10.2-CAPI-1.16.0
Versión de SQLite
3.38.1
Versión de PDAL
2.3.0
Versión del cliente de PostgreSQL
13.0
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by antoniolocandro** [comment]
@AMARINDU debes colocar la informacion en ingles ya que es un foro en este idio, sino dificilmente tendras resultados

Did you try drag-n-drop into QGIS? Also having a test file would make it easier to debug

**Comment by DelazJ** [comment]
You probable should go this way instead https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/opening_data.html#importing-a-dxf-or-dwg-file

**Comment by sigmoe** [comment]
I have developped, for some customers, a specific DXF Import plugin. So, can you provide your dxf file in other that I test it with my plugin and perhaps I would be able to tell you what is the problem in the DXF.
