### ISSUE TITLE
TypeError: commitChanges() takes no keyword arguments

### ISSUE THREAD

**Issue by bastiencyr** [qgis/QGIS#48749]
Hello, 
When I use the commitChanges method like this in the python API: 
```python
self.access_layer = QgsVectorLayer("path_to_shapefile.shp", "Access", "ogr")
self.access_layer.commitChanges(stopEditing=False)
```
I have the error given in the title.
QGis version: 3.10.4-A Coruna
OS: Ubuntu 20.04.4

I have also another issue, I can't add a raster layer with WMS anymore in this version. All is solved if I upgrade QGis (but the stable version in the apt repositories of Ubuntu 20.04 is 3.10.4).

Thanks,
Bastien

**Comment by jef-n** [comment]
[QgsVectorLayer.commitChanges()](https://qgis.org/pyqgis/3.10/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.commitChanges) [QgsVectorLayer::commitChanges()](https://api.qgis.org/api/3.10/classQgsVectorLayer.html#afab34baf331320a8c3212993f5fccfa1) doesn't take any  arguments.

**Comment by bastiencyr** [comment]
Mmh ok my bad, recent version of QGis actually takes an argument (stopEditing) and I didn't pay attention when I switch to another laptop. So thanks.

I have always an issue with WMS raster in this version.

**Comment by bastiencyr** [comment]
This code will not print the wms map: 
```python
def read_from_file():
    config = configparser.ConfigParser()
    config.optionxform = str 
    config.read("env.ini")
    params = {}
    section="BACKGROUND_BD_ORTHO20_WMS"
    for key in config[section]:
          params[key] = config[section][key]
    url = urllib.parse.urlencode(params)
    return url

url = read_from_file()
layer = QgsRasterLayer(url, "name", "wms")
```
And the env.ini file:
```ini
[BACKGROUND_BD_ORTHO20_WMS]
url=https://wxs.ign.fr/essentiels/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities
crs=EPSG:3857
dpiMode=7
format=image/jpeg
layers=ORTHOIMAGERY.ORTHOPHOTOS
styles=normal
featureCount=10
contextualWMSLegend=0
```
