### ISSUE TITLE
Drag and Drop Postgis-Table in QGIS Browser alters name of Geometry-Column

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#48748]
### What is the bug or the crash?

If I copy a table from one postgres-db to another one using the QGIS-Browser the name of the geometry-column changes form "the_geom" to "geom".
The sequence of the attributes also changes...
See attached screencast

https://user-images.githubusercontent.com/40065134/170282660-9fbf6436-6b7b-44e6-8c13-b1787b74358d.gif

Peter

### Steps to reproduce the issue

Simply use drag and drop in in QGIS Browser to copy a postgis-table - aee attached screencast

### Versions

3.24.3 and 

QGIS-Version | 3.25.0-Master | QGIS-Codeversion | a96368e943
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
Kompiliert mit GDAL/OGR | 3.6.0dev-07147d9495 | Läuft mit GDAL/OGR | 3.6.0dev-e0dbcbc021
PROJ-Version | 9.0.0
EPSG-Registraturdatenbankversion | v10.054 (2022-02-13)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
#48796 is a partial fix, limited to the geometry column name.

The other issues are a won't fix IMO: the implementation of the layers exporter is provider-agnostic and needs to work with all data providers, for this reason it makes some assumptions and simplifications (e.g., the geom col is always created before the fields as well as the PK which is always automatically generated).

The tool is not intended for verbatim copy of the DB table structure but to allow data interchange between different data sources.

Of course it is not excluded that this will change in the future but given the current situation of the code it would be quite an effort and it cannot be done as a task in bugfixing campaign.
