### ISSUE TITLE
QGIS crashes while adding raster

### ISSUE THREAD

**Issue by pradip333** [qgis/QGIS#48777]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00002a84 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00002a84 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Versions

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00002a84 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you share the raster ?

(And try a new profile just in case)
