### ISSUE TITLE
Error While Clipping WMS to Vector

### ISSUE THREAD

**Issue by AshtonKem** [qgis/QGIS#48775]
### What is the bug or the crash?

I am attempting to clip a WMS raster layer to a vector, and I get the following error message:

```
The following layers were not correctly generated.
• /private/var/folders/kk/bw75xg4n7zx741b8klw5ql1w0000gn/T/processing_LiKOfL/9cc9e053c8584bcfb4feaa9150f5ebe1/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm
```

The only log message I get is this

```
2022-05-26T22:20:29     INFO    gdalwarp -overwrite -te -117.243027 41.988209 -111.043564 49.000911 -te_srs EPSG:4269 -of GTiff -cutline /private/var/folders/kk/bw75xg4n7zx741b8klw5ql1w0000gn/T/processing_LiKOfL/07c7e9d30684472d8408d4a8e4030d5b/OUTPUT/NAME_Idaho.gpkg -cl NAME_Idaho -crop_to_cutline "contextualWMSLegend=0&crs=EPSG:3857&dpiMode=7&featureCount=10&format=image/jpeg&layers=cl3nm2tih000214nv4nfrbs4h&styles=default&tileMatrixSet=GoogleMapsCompatible&url=https://api.mapbox.com/styles/v1/<USERNAME>/<MAPID>/wmts?access_token%<TOKEN>" /private/var/folders/kk/bw75xg4n7zx741b8klw5ql1w0000gn/T/processing_LiKOfL/9cc9e053c8584bcfb4feaa9150f5ebe1/OUTPUT.tif
```

This error is pretty unclear, and it leaves me wondering if there's something I did wrong, if there's an error with the WMS server I'm using (mapbox, by the by), or if this is just a limitation of WMS and that I should try and do something different. If it's the last case, documentation would be excellent.

### Steps to reproduce the issue

1. Add a WMS layer
2. Add a vector layer
3. Clip the WMS layer to the vector layer

### Versions

QGIS version | 3.24.0-Tisler | QGIS code revision | e6ab9473e0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
qgis-maptiler-plugin | 3.0.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

Active Python plugins
qgis-maptiler-plugin
3.0.1
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Please see https://github.com/qgis/QGIS/issues/48710#issuecomment-1136767644.
It seems to me this is due to the same underlying issue of https://github.com/qgis/QGIS/issues/15322 and https://github.com/qgis/QGIS/issues/48710, isn't it @alexbruy?

**Comment by alexbruy** [comment]
This is actually the same issue as #48710, Processing GDAL provider does not support WMS datasources (as well as MBTiles, WCS etc).

**Comment by agiudiceandrea** [comment]
> Processing GDAL provider does not support WMS datasources

@alexbruy, it would be useful if WMS layers (and other non supported layers) are filter out from the processing algorithms GUIs of the GDAL provider.

**Comment by alexbruy** [comment]
@agiudiceandrea see #19870.
