### ISSUE TITLE
Crash working with the layout manager

### ISSUE THREAD

**Issue by solisgb** [qgis/QGIS#48782]
## User Feedback

Working with the layout manager: second crash in the same session

## Report Details

**Crash ID**: [4d8d09ae642f81dc661a53f706c93c126c46f42a](https://github.com/qgis/QGIS/search?q=4d8d09ae642f81dc661a53f706c93c126c46f42a&type=Issues)

**Stack Trace**
<pre>
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::setLegendFilter :
QgsLayoutItemLegend::doUpdateFilterByMap :
QgsLayoutItemLegend::paint :
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Working with legends. Copy legend , paste in place, move position new legend, crash

### Versions

LTR in Windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
A sample project would be optimal.
