### ISSUE TITLE
Pointcloud layer Symbology not initially applied

### ISSUE THREAD

**Issue by hamishcampbell** [qgis/QGIS#48799]
### What is the bug or the crash?

Using QGIS nightlies (82e9dbed42), the initial symbology of a pointcloud layer is not correctly applied when the layer is first added to the map.

### Steps to reproduce the issue

Add a Pointcloud layer with RGB data to the map. The initial display will appears e.g. as follows:

![Screen Shot 2022-05-31 at 12 05 02 PM](https://user-images.githubusercontent.com/295074/171069737-b8535698-5ca5-40a0-9157-91df2c1b2cf1.png)

Opening the layer symbology shows the initial RGB setting correctly configured:

![Screen Shot 2022-05-31 at 12 05 31 PM](https://user-images.githubusercontent.com/295074/171069772-b9e9a822-6978-4f81-8448-e05795813f1a.png)

Pressing "OK" _with no other interaction or modifications_ applies the correct symbology:

![Screen Shot 2022-05-31 at 12 05 57 PM](https://user-images.githubusercontent.com/295074/171069795-c43ed345-f6cc-49c9-9476-cddc8df8638b.png)

### Versions

QGIS version | 3.25.0-Master | QGIS code revision | 82e9dbed42
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.3
  |   |   |  
Active Python plugins
kart | 1.0.0
koordinatesexplorer | 1.0.0
LAStools | 1.4
pluginbuilder3 | 3.2.1
QuickWKT | 3.1
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This was working in QGIS 3.24.3-Tisler (current stable).

**Comment by hamishcampbell** [comment]
Also confirmed on Windows

QGIS version | 3.25.0-Master
--|--
QGIS code revision | 4044c882c4
Qt version | 5.15.3
OS version | Windows 10 Version 2009

**Comment by hamishcampbell** [comment]
It looks like this might be resolved on later builds.

**Comment by alexbruy** [comment]
@hamishcampbell can we close this?

**Comment by hamishcampbell** [comment]
Yes this is fixed, thanks.
