### ISSUE TITLE
Unable to generate previews for non-COPC Pointcloud LAS

### ISSUE THREAD

**Issue by hamishcampbell** [qgis/QGIS#48798]
### What is the bug or the crash?

Using QGIS nightlies (82e9dbed42), unable to generate previews for non-COPC LAS files.

Fails while running "Generating Pointcloud Index" with the error:

```
Untwine error: unordered_map::at: key not found
```

Attached file where this error occurs.

[island.las.zip](https://github.com/qgis/QGIS/files/8801032/island.las.zip)

Note that COPC files are fine (presumably because the indexing is not required)

### Steps to reproduce the issue

1. Add a non-COPC LAS file to the map
2. Await the indexing process
3. Eventually fails with the error `Untwine error: unordered_map::at: key not found`
4. Only PC extent is displayed

### Versions

QGIS version | 3.25.0-Master | QGIS code revision | 82e9dbed42
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.3
  |   |   |  
Active Python plugins
kart | 1.0.0
koordinatesexplorer | 1.0.0
LAStools | 1.4
pluginbuilder3 | 3.2.1
QuickWKT | 3.1
plugin_reloader | 0.9.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This was working in QGIS 3.24.3-Tisler (current stable), so appears to be a regression.

**Comment by wonder-sk** [comment]
Hmm... works for me fine on linux. Anyone on Mac to confirm?

**Comment by hamishcampbell** [comment]
@wonder-sk What build are you using?

**Comment by wonder-sk** [comment]
I'm using self-compiled QGIS master build, ubuntu 20.04.

**Comment by soester** [comment]
@wonder-sk yes, i am able to open the same dataset with this setup:

QGIS version | 3.24.2-Tisler | QGIS code revision | 573ca40c96
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 10.15
  |   |   |  
Active Python plugins
QgisModelBaker | v6.3.4
DataPlotly | 3.9
VectorBender | 0.2.1
changeDataSource | 3.1
quick_map_services | 0.19.11.1
AnotherDXF2Shape | 1.2.4
SRTM-Downloader | 3.1.9
pg_history_viewer | 2.2
swiss_locator | 1.3.4
processing | 2.12.99
sagaprovider | 2.12.99
db_manager | 0.1.20

**Comment by hamishcampbell** [comment]
Have since updated to [3943ef5e10](https://github.com/qgis/QGIS/commit/3943ef5e10), same error persists.

**Comment by wonder-sk** [comment]
Confirmed as an upstream issue in untwine: https://github.com/hobuinc/untwine/issues/123

**Comment by hobu** [comment]
Fixed upstream at https://github.com/hobuinc/untwine/commit/4e60f8a7f5edd094d4e5d44e7093677e841a1213 please test and confirm.

**Comment by dvmepi** [comment]
I am having the same issue on Mac OS - tried both QGIS 3.26 and 3.22

"Layer [xyz]: Untwine error: unordered_map::at: key not found"

**Comment by hobu** [comment]
rename the file with ascii characters until 3.26.1 is released.

**Comment by vethno** [comment]
> 

Sorry, not sure what you mean. New to QGIS.

**Comment by dvmepi** [comment]
> rename the file with ascii characters until 3.26.1 is released.

Please provide me some additional information, I haven't used QGIS in quite a long time. Thanks.

**Comment by soester** [comment]
@hobu my filenames don't contain non-ascii characters:
```10_Geodata/00_Grundlagen/LIDAR_Laserscanning-Punktwolke_-_2017-2018_-OGD/2673_1252.laz```

**Comment by saberraz** [comment]
Could you copy/move the file to another location (e.g. Documents)?

**Comment by soester** [comment]
Indeed the other directory was on a shared network volume (smb)

With: ```/Users/sam/Documents/test/2673_1252.laz```
I get: ```Layer 2673_1252: Untwine error: unordered_map::at: key not found```

**Comment by dvmepi** [comment]
None of those have worked for me: Layer 123123: Untwine error: unordered_map::at: key not found

**Comment by hobu** [comment]
It won't be fixed until 3.26.1

**Comment by hamishcampbell** [comment]
Thanks @hobu, much appreciated!

**Comment by mapninja** [comment]
Having the same issue in 3.26.1

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | b609df9ed4
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code revision
[b609df9ed4](https://github.com/qgis/QGIS/commit/b609df9ed4)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.4




Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6`

**Comment by wonder-sk** [comment]
Sorry I haven't pulled the upstream fixes yet, so this will likely get fixed in 3.26.2

**Comment by Spartacus1** [comment]
> Sorry I haven't pulled the upstream fixes yet, so this will likely get fixed in 3.26.2

Thank you. I'am experiencing the same bug in macOS and QGIS 3.26.1. Waiting for the fix then. 
Best regards

**Comment by alexbruy** [comment]
Is this still an issue? In my tests on Linux and WIndows with the latest 3.32 and master (2d64df22a4eb4e7e6718f747c9eb1ed4e5f81903) everything works fine.

**Comment by spatialthoughts** [comment]
I am able to load `island.las` on QGIS 3.28.9 on Mac without any issues.

**Comment by hamishcampbell** [comment]
Confirmed fixed.
