### ISSUE TITLE
Elevation Profile does not support terrain from WMTS layer

### ISSUE THREAD

**Issue by wonder-sk** [qgis/QGIS#48806]
### What is the bug or the crash?

When I try to use Mapzen Global Terrain layer with elevation profile, there's no profile showing up. (I have marked the layer as representing elevation surface):

![image](https://user-images.githubusercontent.com/193367/171171521-79a89b5a-09d6-4cd3-b978-f3525300810d.png)

### Steps to reproduce the issue

1. load Mapzen Global Terrain from XYZ Tiles in browser dock
2. open layer properties, Elevation tab, check that it represents elevation surface
3. open elevation profile tool
4. draw a curve -> no profile gets shown

### Versions

QGIS master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
@wonder-sk this should already be fixed -- can you still reproduce?

**Comment by nyalldawson** [comment]
Specifically it was fixed by https://github.com/qgis/QGIS/pull/50795

**Comment by wonder-sk** [comment]
Indeed I can confirm it is fixed now!
