### ISSUE TITLE
A QgsProcessingParameter with custom WidgetWrapper can't be connected correctly in the Model Designer

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#48816]
### What is the bug or the crash?

I want to implement a QgsProcessingAlgorithm with a QgsProcessingParameterFile that has a custom WidgetWrapper.

Here is a minimal example:

```
from processing.gui.wrappers import WidgetWrapper
from qgis._core import QgsProcessingParameterFile, QgsProcessingAlgorithm
from qgis._gui import QgsFileWidget


class MyAlgorithm(QgsProcessingAlgorithm):

    def displayName(self):
        return 'My Algorithm'

    def name(self):
        return 'MyAlgorithm'

    def shortDescription(self):
        return 'dummy'

    def group(self):
        return 'Debugging'

    def createInstance(self):
        return type(self)()

    def initAlgorithm(self, configuration):

        # add a normal parameter
        self.addParameter(QgsProcessingParameterFile('file1', 'Normal File'))

        # add a parameter with custom widget
        param = QgsProcessingParameterFile('file2', 'Custom File')
        param.setMetadata({'widget_wrapper': {'class': MyWidgetWrapper}})
        self.addParameter(param)

    def processAlgorithm(self, parameters, context, feedback):
        return {}


class MyWidgetWrapper(WidgetWrapper):
    widget: QgsFileWidget

    def createWidget(self):
        return QgsFileWidget()

    def setValue(self, value):
        self.widget.setFilePath(value)

    def value(self):
        return self.widget.filePath()

```

Executing the algorithm in the Processing Toolbox works fine.

![image](https://user-images.githubusercontent.com/45030715/171350415-0827ad30-8173-4e07-abc9-f89a6f5fa58c.png)

Using the algorithm in the Model Designer is not working as expected:

![image](https://user-images.githubusercontent.com/45030715/171349478-1f9c8a9f-c16e-44e1-990b-8cdc3660a5cf.png)

The menu-button for correctly connecting previous outputs is missing:
![image](https://user-images.githubusercontent.com/45030715/171350140-6803010e-9293-4166-b970-1f08111ad304.png)

This makes it impossible to actually use the algorithm inside a model.

### Steps to reproduce the issue

1. Add the algorithm from above to a processing provider of your choice.
2. Use the algorithm in the Model Designer.
3. See the bug: the "123"  menu-button is not shown.

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a02865
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.4
enmapboxplugin
3.10.0.20220524T082114.TEST
geetimeseriesexplorer
2.0
qgis-maptiler-plugin
3.0.3
timeseriesviewerplugin
1.17.20210312T143004.master
vrtbuilderplugin
0.9.20210222T174536.master
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
The WidgetWrapper class is deprecated -- this is a wontfix

**Comment by janzandr** [comment]
Can anybody point me to an example or documentation?
I understand that WidgetWrapper class is deprecated, but how would I implement a custom widget correctly?

**Comment by janzandr** [comment]
Hi @alexbruy, I understand, that the WidgetWrapper class is deprecated.
But what would be the correct API to use? Any PyQGIS examples available?
Regards, Andreas.

**Comment by 0graph** [comment]
@janzandr did you find any solution / alternative?

I've been using QgsAbstractProcessingParameterWidgetWrapper as I thought it was the successor to the WidgetWrapper but I have the same issue with model builder.

Thanks!

**Comment by janzandr** [comment]
No unfortunately not.
My colleque @jakimowb (correct me if I'm wrong), also suggested to use the _QgsAbstractProcessingParameterWidgetWrapper_, but I never tried it.
Looks like we will have a handful of deprecated widgets, when QGIS 4 will be released :-)

**Comment by florianneukirchen** [comment]
@janzandr  @0graph I had the problem that WidgetWrapper is crashing Qt6-builds of Qt6 on Windows and in the QGIS source code there are comments "remove in QGIS 4".

I rewrote the UI of my plugin Scipy Filters by subclassing QgsProcessingAlgorithmDialogBase and doing most things QGIS does in AlgorithmDialog.py myself, but with my custom widgets. This way, you can wire the widgets directly with signals, without an intermediate widget wrapper class. Everything I tested works on both, Qt5 and Qt6 builds. I didn't really tested the model builder yet, though.  

For an idea how this could work: https://github.com/florianneukirchen/scipy_filters/blob/main/ui/scipy_processing_dialog.py
