### ISSUE TITLE
Slow SVG color customization

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#48819]
### What is the bug or the crash?

Using a custom SVG to create color classes of symbols seems to be very slow in QGIS LTR and master (Since 3.22 at least)

![Slow_SVG_customisation](https://user-images.githubusercontent.com/8614223/171395748-c01a0c19-9e37-4462-85c2-45cb17619e52.gif)

I'm not sure but it seems to be linked more to the data connexion than to the symbol itself. The whole color selection windows seems to be laggy.

It's a bit less laggy when using a simple symbol.

Symbol used :
![consommateur_interieur_generic](https://user-images.githubusercontent.com/8614223/171397935-e577a857-8334-42dc-99aa-00588571836b.svg)

### Steps to reproduce the issue

1. Add a point layer
2. Set SVG symbol as symbology
3. Change outline or inline color

### Versions

Version de QGIS
3.22.7-Białowieża
Révision du code
5a65627a
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.4.3
Version de Proj
9.0.0
Version de la base de données du registre EPSG
v10.054 (2022-02-13)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.38.1
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
changeDataSource
3.1
document_management_system
0.3.1
DPFE
1.3.7
EasyImport
3.3.0
geomapfish_locator
1.3.1
LandSurveyCodesImport
0.3.0-beta6
linking_relation_editor
v1.0.0
nominatim_locator_filter
0.2.4
openlayers_plugin
2.0.0
pg_history_viewer
2.2
qfieldsync
v4.1.1
qgepplugin
1.5.5
QgisModelBaker
v7.1.6
trackable_project_files
v1.2.2
wincan2qgep
1.1.0
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Available for any other informations

**Comment by nyalldawson** [comment]
I can't reproduce this. Could you share a sample project demonstrating this issue?

**Comment by ponceta** [comment]
It's a bit everything in the layer symbology definition that becomes very Laggy when dealing with custom svg files for visualisation :

![Laggy_svg_customization](https://user-images.githubusercontent.com/8614223/201270399-1ada9b3a-4345-4e5f-8f95-f64767b9d01d.gif)

We use that in almost every project we have to define generic svg to avoid defining a file for every color set possible for symbology.

.qgs project to 
[Export.zip](https://github.com/qgis/QGIS/files/9986738/Export.zip)

Reproduced on QGIS 3.28.0 too
