### ISSUE TITLE
changing existing Layout: changing layer of <Attribute table frame> crashs qgis 

### ISSUE THREAD

**Issue by hoyomer** [qgis/QGIS#48829]
### What is the bug or the crash?

I use many "old" layouts to create Prints.
Most of them use maps, scalebar, some Text and \<Attribute table frames\>

As Attributes for the attrbute tableframes i use some fields and calculations.
Source is one layer. I want to change the Layer to an compareable but not 100% identical Layer and qgis crashs.

### Steps to reproduce the issue

sry, its not not 100% reproduceable
U need an an project with old layouts (created with older version of qgis)
In this Layout u need an \<Attribute table frame\>

Open the Layout, activate the \<Attribute table frame\> Item and change Item Properties - Layer to an other Layer. --> Crash

If i create a new \<Attribute table frame\> in the same Layout i could change everything. Nothing happens.
Only the old Items make this problems.

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.1
MBTiles2img
0.4
Multi_Ring_Buffer
1.1
openlayers_plugin
2.0.0
QuickPrint
3.6.0
SaxonyCadastralParcels
0.3.2
SemiAutomaticClassificationPlugin
7.1.1
spatial_query_with_values
1.0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

i don't know exactly how old the layout was. There was a change in qgis, after which then sometimes maps were no longer displayed in the layout.
EDIT: change visibility of \< and \>

**Comment by alexbruy** [comment]
Please provide a dataset so the issue can be reproduced.
