### ISSUE TITLE
include ntv2 gsb file for Berlin

### ISSUE THREAD

**Issue by jmbwb** [qgis/QGIS#48822]
### Feature description

Hi,

by default in QGIS the beta2007.gsb is included to transform between EPSG:3068 and EPSG:25833 for example.

In Berlin we use the ntv2berlin gsb file for transformation, which is much more precise than the beta2007.gsb.

Ist it possible to include ntv2berlin gsb file by default into QGIS? You can get the official file here:
https://www.stadtentwicklung.berlin.de/geoinformation/bezugssysteme/download/ntv2berlin20130508.zip

Thanks and kind regards

**Comment by alexbruy** [comment]
QGIS does not come with transformation grids, they are installed separately from proj resources. You need to ask in the OSGeo4W bugtracker.
