### ISSUE TITLE
Lock function in Layout not working

### ISSUE THREAD

**Issue by hayleyg123** [qgis/QGIS#48826]
### What is the bug or the crash?

The lock function for the map in layout mode is not working. Changes to layer visiblity in the QGIS main window are still showing up in the layout view.

Have tried with multiple map files, users, and computers.

### Steps to reproduce the issue

1) Go to layout mode
2) Add map
3) Lock map (Item list on right hand side)
4) Make changes to visible layers in QGIS main window
5) Refresh layout view to see that locked map has changed and has not actually been locked

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
LAStools
1.4
quick_map_services
0.19.29
VectorBender
0.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
I can reproduce this aswell. (QGIS 3.22.7 and 3.24.3)

**Comment by nyalldawson** [comment]
I can't reproduce.

Are you sure you're using the "lock layers" option for map items, and not the general "lock item position" option?

![image](https://user-images.githubusercontent.com/1829991/171787237-ab3a9854-99cb-411f-a642-7858b6328272.png)

**Comment by Pedro-Murteira** [comment]
@nyalldawson Hello, yes, I can still replicate, even with "Lock layers" checked. Changes are always made in the layout.

**Comment by nyalldawson** [comment]
@Pedro-Murteira 

Can you share a sample project?

**Comment by Pedro-Murteira** [comment]
I've created a sample project with 3 simple layers and a layout, 
[test_48826.zip](https://github.com/qgis/QGIS/files/8831778/test_48826.zip)

**Comment by hayleyg123** [comment]
Thank Nyall, your solution worked for me! Everything I'd read so far only indicated one lock button was present. Thanks!!
