### ISSUE TITLE
WMTS webp image crashes in 3.22.7

### ISSUE THREAD

**Issue by RobinChesterfield** [qgis/QGIS#48842]
## User Feedback

WMTS basemap image webp crashes in 3.22.7  , image png and jpeg open OK.

Note image webp opens OK in 3.16.8

## Report Details

**Crash ID**: [c70e470769fb8c901fc8882c619d1f0bc84ff925](https://github.com/qgis/QGIS/search?q=c70e470769fb8c901fc8882c619d1f0bc84ff925&type=Issues)

**Stack Trace**
<pre>
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
QImageReader::read :
QImageReader::read :
QImage::fromData :
QImage::fromData :
QgsTileCache::tile :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

got to WMS/WMTS
click on "aerial"
select image/webp

GIS hangs thenafter a time a crash report produced.

### Versions

QGIS version
3.22.7-Białowieża
QGIS code revision
5a65627a
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
active_fire
0.2
annotationManager
0.5
Climb
1.1
go2streetview
8.1
GpxSegmentImporter
2.5
ImportPhotos
2.2.2
JSONEater-master
0.3
kmltools
3.1.16
linz-data-importer
2.2.3
profiletool
4.1.8
Qgis2threejs
2.6
qgsAzimuth
0.9.15
quick_map_services
0.19.19
trail_elevation_stats
0.2
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@RobinChesterfield Is this replicable even with a new profile?

**Comment by RobinChesterfield** [comment]
Tried a new profile and same fault.

## User Feedback

With a new profile 3.22.7 same problem with loading webp image. Crash
report below.
The linz data importer plugin has been stable since june 2021 the last
update.

## Report Details

**Crash ID**: [9ecc11ccf673b6d0bb9253b8c91afbdb7ecf94dd](
https://github.com/qgis/QGIS/search?q=9ecc11ccf673b6d0bb9253b8c91afbdb7ecf94dd&type=Issues
)


**Stack Trace**
<pre>
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
qt_plugin_query_metadata :
QImageReader::read :
QImageReader::read :
QImage::fromData :
QImage::fromData :
QObject::qt_static_metacall :
QTcpServer::proxy :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
Robin Chesterfield
+64226514928

**Comment by RobinChesterfield** [comment]
At this stage I have not tried a new profile.
I have reinstalled QGIS 3.22.7  and fault remains.

I have a second independent desktop running 3.22.6
and the webp image load is OK.

Both desktops are set to default profile.
I will create a new profile tomorrow.
Robin





Robin Chesterfield
+64226514928

**Comment by nicogodet** [comment]
3.22.7 isn't the latest release, could you try with 3.22.11 or 3.26.3 ?

**Comment by RobinChesterfield** [comment]
I loaded 3.22.11 and it fixes the issue with crashing when loading webp
images.
I now want to uninstall 3.22.7, but Win10  control panel app remove does
not work. is there another way to uninstall. I have not had this problem
with previous updates.

Regards
Robin Chesterfield
+64226514928

**Comment by RobinChesterfield** [comment]
The webp #48842 can be closed. 3.22.11does not exhibit this webp image crash.
