### ISSUE TITLE
Native Buffer tool doesn't finish in 3.24.3 and master

### ISSUE THREAD

**Issue by SrNetoChan** [qgis/QGIS#48849]
### What is the bug or the crash?

Native buffer tool takes way too much time or doesn't finish after more than 10 minutes, while it takes less than 1 minute in QGIS 3.16.16, and 3.22.7

I have tried in several machines with clean profiles.

### Steps to reproduce the issue

1. Download the following test data: 
https://mega.nz/file/VQ9y0KoZ#PoGgwC7SOoEtM3wob36_iZe3uxKAK8b4ULI5HiBwgcY
2. Load it in QGIS 3.24 or master
3. run the native buffer tool choosing 1m distance and dissolve results
4. wait...

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)

</body></html>QGIS version
3.24.3-Tisler
QGIS code revision
[cf22b74e01](https://github.com/qgis/QGIS/commit/cf22b74e01)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Tested

**Comment by nyalldawson** [comment]
Highly likely due to changes in geos -- I'd suggest reporting this there along with wkt of the geometries

**Comment by SrNetoChan** [comment]
@nyalldawson so, copy paste the features into text file would work?

**Comment by SrNetoChan** [comment]
How wait, you suggest report on GEOS?

**Comment by uclaros** [comment]
Execution completed in 7.98 seconds


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>


QGIS version | 3.25.0-Master | QGIS code revision | 9aa9683739
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.12
GDAL/OGR version | 3.4.3
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.5
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid

</body></html>

**Comment by SrNetoChan** [comment]
I tested on master too. But it seems my linux machine has older versions of gdal and geos.

**Comment by uclaros** [comment]
I've had other issues too with geos 3.8.0, eg. #34998

**Comment by nyalldawson** [comment]
> it seems my linux machine has older versions of gdal and geos.

So it seems this is already fixed upstream then?

**Comment by SrNetoChan** [comment]
Yes, I guess so. I will create a manual test case for the next LTR release and close this ticket.
