### ISSUE TITLE
Saved SLD-style is missing "uom" attribute if unit of measure is metre 

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#48847]
### What is the bug or the crash?

Saved SLD-style is missing `uom` attribute if unit of measure is metre:
`uom="http://www.opengeospatial.org/se/units/metre"`

This leads to a false SLD-style because

> If no uom is set insideof Symbolizer, all units are measured in pixel

Source: SE Spec (11 Symbolizers) https://portal.ogc.org/files/?artifact_id=16700

![image](https://user-images.githubusercontent.com/20856381/171829476-bcb652f6-12cf-4125-9945-65ab445a5d51.png)

### Steps to reproduce the issue

1. Open [sample_project.zip](https://github.com/qgis/QGIS/files/8831386/sample_project.zip)

2. Inspect symbology of the polygon layer -> `Stroke width` is in _Meters at Scale_
![image](https://user-images.githubusercontent.com/20856381/171830319-1dc87d8e-d60c-4b9b-9f7c-61d2a2332f12.png)

3. Save SLD-Style for polygon layer

4. Inspect SLD style -> see error -> no uom attribute: `uom="http://www.opengeospatial.org/se/units/metre"`

![image](https://user-images.githubusercontent.com/20856381/171830909-9e53fb0d-2ea7-4b84-86db-9ab236bc40d2.png)

5. If you load the exported SLD-style for the Polygon layer, units are changed to `Pixels`:

![image](https://user-images.githubusercontent.com/20856381/171831435-010506dd-72f9-4314-ad3f-5112b6bbafe8.png)

### Versions

QGIS version | 3.25.0-Master | QGIS code revision | c226109b61
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PostgreSQL client version | 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
I can reproduce this aswell, QGIS 3.22.7 and 3.24.3.
