### ISSUE TITLE
test_core_gdalprovider modifies tests/testdata/zip/landsat_b1.zip source file

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#48846]
### What is the bug or the crash?

Spin-off of #25830 specific for a single test `test_core_gdalprovider`.

### Steps to reproduce the issue

1. build
2. git checkout . # ensure no local modification exist
3. builddir$ xvfb-run ctest --output-on-failure -R test_core_gdalprovider
4. srcdir$ git status -uno # will show tests/testdata/zip/landsat_b1.zip being modified

### Versions

Current master branch as of June 1st 2022 - 1af9c8150c0c45b1bd0072c5e707c45cdfb88508

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Additional context can be found in https://github.com/qgis/QGIS/pull/48654#issuecomment-1145762759 where I've added automatic check of source tree NOT being changed (reviews welcome).

**Comment by strk** [comment]
The modification to the source file is done by the `testGdalProviderQuerySublayers` method, so can be triggered by this smaller call:

> xvfb-run ./output/bin/test_core_gdalprovider testGdalProviderQuerySublayers

**Comment by strk** [comment]
This block of code inside the (too large) testGdalProviderQuerySublayers function responsible for the modification of the source file is this one:
```
  // zip archive, only 1 file
  res = gdalMetadata->querySublayers( QStringLiteral( TEST_DATA_DIR ) + "/zip/landsat_b1.zip" );
  QCOMPARE( res.count(), 1 );
  QCOMPARE( res.at( 0 ).layerNumber(), 1 );
  QCOMPARE( res.at( 0 ).name(), QStringLiteral( "landsat_b1.tif" ) );
  QCOMPARE( res.at( 0 ).description(), QString() );
  QCOMPARE( res.at( 0 ).uri(), QStringLiteral( "/vsizip/%1/zip/landsat_b1.zip/landsat_b1.tif" ).arg( QStringLiteral( TEST_DATA_DIR ) ) );
  QCOMPARE( res.at( 0 ).providerKey(), QStringLiteral( "gdal" ) );
  QCOMPARE( res.at( 0 ).type(), QgsMapLayerType::RasterLayer );
  QCOMPARE( res.at( 0 ).driverName(), QStringLiteral( "GTiff" ) );
  rl.reset( qgis::down_cast< QgsRasterLayer * >( res.at( 0 ).toLayer( options ) ) );
  QVERIFY( rl->isValid() );
```

@rouault is it expected that just opening a zip file, via `/vsizip/` modifies it ?

**Comment by strk** [comment]
Among the above block, it's just this single line that triggers the modification of the file:
```
  rl.reset( qgis::down_cast< QgsRasterLayer * >( res.at( 0 ).toLayer( options ) ) );
```

And in particular, this expression:
```
res.at( 0 ).toLayer( options )
```

**Comment by rouault** [comment]
> is it expected that just opening a zip file, via `/vsizip/` modifies it ?

this is indeed the current GDAL behavior. If you do "gdalinfo /vsizip/byte.tif.zip/byte.tif -stats", it will create a byte.tif.aux.xml file inside the ZIP with the statistics. Whether this is a bug or a feature depends on point of view.

**Comment by strk** [comment]
No switch/env variable to state one's point of view ? It would be handy, for the testsuite, being able to open files in read-only mode (similar need to the one with .gpkg files).

Failing that the only fix to this issue would be to copy the .zip to a separate directory prior to opening it. Or maybe make sure the zip file already contains the stats inside ...

**Comment by rouault** [comment]
setting GDAL_PAM_ENABLED=NO configuration option / environment variable disables .aux.xml file generation

**Comment by strk** [comment]
Sounds like one of those "subtle side-effects" documented in https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_PAM_ENABLED -- is there any other option ? More clarity is better, IMHO. Is there no concept, in GDAL, of opening a dataset in read-only mode ?

**Comment by rouault** [comment]
> Sounds like one of those "subtle side-effects" documented in https://trac.osgeo.org/gdal/wiki/ConfigOptions#GDAL_PAM_ENABLED

That's not quite a subtle side-effect ;-) The main purpose of PAM is to handle .aux.xml files.
The "subtle side-effects" of disabling PAM were addressed in GDAL 3.5.0 per https://github.com/OSGeo/gdal/commit/e6fe8e507ab2a1ec4dc9542e71879b2c4b759a20 . 
Anyway, you don't want to disable in general PAM, but on a case by case basis. If for the scope of this test, disabling temporarily PAM make the test pass (with GDAL < 3.5), then it should be fine

> Is there no concept, in GDAL, of opening a dataset in read-only mode ?

there is. But generating PAM files is an "accepted" behavior even in read-only mode (at least GDAL has done this during the last 20 years or so). Read-only mode only affects not modifying the main file and its official side cars, no the GDAL specific .aux.xml  side car file.

**Comment by rouault** [comment]
by the way, you should avoid looking at Trac. It is completely unmaintained. The official doc is at https://gdal.org/user/configoptions.html (although I can see GDAL_PAM_ENABLED is not documented there yet)

**Comment by strk** [comment]
On Wed, Jun 08, 2022 at 03:14:51AM -0700, Even Rouault wrote:
> by the way, you should avoid looking at Trac. It is completely unmaintained. The official doc is at https://gdal.org/user/configoptions.html (although I can see GDAL_PAM_ENABLED is not documented there yet)

Trac is what Google considered valuable. May be useful to add an
header on each and every trac page to point to the new place, to
augment the official doc page ranking...

--strk;

**Comment by strk** [comment]
@rouault I've filed #48917 to disable PAM for that specific test. Fixes this issue for me.
