### ISSUE TITLE
test_3d_3drendering occasionally aborts

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#48858]
### What is the bug or the crash?

the test_3d_3drendering test occasionally crashes.
This is a spin-off of issue https://github.com/qgis/QGIS/issues/47395

### Steps to reproduce the issue

Run `xvfb-run ctest --output-on-failure -R test_3d_3drendering`  from the build dir, in a loop. It sometimes aborts.

### Versions

Current master branch as of 3 June 2022 - 45b2270253f720b0e869c7b8d4fd77db9478284e

\cc @benoitdm-oslandia (you seem to be the one who last added many tests there)

Example abort: https://github.com/qgis/QGIS/runs/6730275975?check_suite_focus=true#step:13:1826

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by strk** [comment]
Happened again (in 3_22 branch):
https://github.com/qgis/QGIS/runs/6920979676?check_suite_focus=true#step:13:1744

**Comment by strk** [comment]
Again (in 3_22 branch):
https://github.com/qgis/QGIS/runs/6925507606?check_suite_focus=true#step:13:1753

**Comment by nyalldawson** [comment]
@strk are you looking into this one? It's quite well known and has been present for years, so a fix would be well appreciated 👍

**Comment by strk** [comment]
The test in the subject was renamed so not sure how to try at reprpoducing it. A loop of runs of `test_core_25drenderer` seem to survive in a stable way ( in the branch associated with #51891 ) , so I'll just be optimistic and bet on this being fixed
