### ISSUE TITLE
Saving a Project with copc-laz-Files creates additional File proj_attachments.zip

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#48857]
### What is the bug or the crash?

When I load a copc-lidarfile in qgis 3.25 (Master from today on Win10) and save then the project as "projectname.qgs" an additional file named "projectname_attachments.zip" is created in the same folder containing one or many files named CHANGINGNAME_styles.db.
the .db-File is more or less empty.
I can delete the .zip and the project still opens fine but it is recreated as soon as I save the project again,

Peter

### Steps to reproduce the issue

open copc-laz-File in qgis 3.25
save project as .qgs
additional zip is created

See [copcs.zip](https://github.com/qgis/QGIS/files/8833402/copcs.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.25.0-Master | QGIS-Codeversion | 1af9c8150c
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
Kompiliert mit GDAL/OGR | 3.6.0dev-07147d9495 | Läuft mit GDAL/OGR | 3.6.0dev-dad6fb5681
PROJ-Version | 9.0.0
EPSG-Registraturdatenbankversion | v10.054 (2022-02-13)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Diese QGIS-Kopie schreibt Debugausgaben.
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS-Version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is expected, and unrelated to copc files. It's storing the new project specific style database. (Note that other operations will also cause creation of the attachments file, eg moving labels). If you save as .qgz then the attachments are embedded in the qgz file.

**Comment by Gustry** [comment]
> save then the project as "projectname.qgs" an additional file named "projectname_attachments.zip" is created in the same folder

> It's storing the new project specific style database. (Note that other operations will also cause creation of the attachments file, eg moving labels)

Thanks @nyalldawson for the answer. Related question, can we somehow disable this "new" behavior ?

I just checked the content of the ZIP. Indeed it contains a `XXX_styles.db` but then all tables are empty in this file database. IMHO, if all tables inside are empty, it seems we can skip the creation of this ZIP, no ?

Some customers are just switching from QGIS 3.22 to 3.28 (for LTR reasons), so discovering this new file added automatically these days.

**Comment by nyalldawson** [comment]
@Gustry 

> can we somehow disable this "new" behavior

No, that's not supported. Keep in mind that this file isn't only used for project styles, but also auxiliary storage and other project add ons. I'd adapt your internal processes to handle it instead.

**Comment by Gustry** [comment]
>  I'd adapt your internal processes to handle it instead.

No worries, it does handle it ;-)

I was just curious if it was possible to bypass this new file, if and only if we could detect that the database (or the ZIP) wasn't used.

Before, it was only created if needed. Now, it seems automatically created, even if it's empty.
