### ISSUE TITLE
Could not Create Layer .... Is not a directory

### ISSUE THREAD

**Issue by Werafa** [qgis/QGIS#48868]
### What is the bug or the crash?

workflow:
run a vector geometery tool (most will do this, the current one is 'Vector Union'.
Save output to file
File already exists - do you want to replace it? Yes

result is:
Could not create layer D:/............/combined roads buffer.shp: Creation of data source failed (OGR error: D:/........./combined roads buffer.shp is not a directory.)
Execution failed after 0.04 seconds

Expected result is: process output replaces original file
process always works if I delete the original file first.

conclusion: 
1: QGIS operation fails due to pre-existing file with same name.
2: instruction to overwrite pre-existing file fails
3: this occurs on many of the vector geometry tools - therefore is not a problem with any one tool.

software info:
Win 10

### Steps to reproduce the issue

run a vector geometry tool and save the result as a shapefile
ensure that new shapefile is not loaded in QGIS
run a new vector geometry process and save as file -> overwrite previous file

process fails due to pre-existing file - despite instruction to overwrite it.

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.4
latlontools
3.6.3
planet_explorer
2.2.0
Qgis2threejs
2.6
qgis_gee_data_catalog
0.4.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by ismailsunni** [comment]
I can't reproduce it on Ubuntu, perhaps Windows only?
Tested on Ubuntu 20.04, QGIS 3.24.3

**Comment by agiudiceandrea** [comment]
Confirmed with QGIS 3.24.3 (OSGeo4W) on Windows 10 saving to an ESRI Shapefile output layer.
The issue doesn't occur with QGIS 3.22.7 (OSGeo4W) on the same system.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master on Windows when saving to shapefile.

**Comment by agiudiceandrea** [comment]
Confirmed not reproducible neither using QGIS 3.28 nor QGIS 3.33.0-Master.
