### ISSUE TITLE
Add raster to points feature

### ISSUE THREAD

**Issue by bethebest22** [qgis/QGIS#48877]
### What is the bug or the crash?

Add raster to points feature
![image](https://user-images.githubusercontent.com/42592310/172092502-b0eca393-01cf-4bfb-8efd-c4a4390d8d43.png)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/42592310/172092536-5bf4daaf-646a-40d7-b354-f88b9b74a8a8.png)

### Versions

QGIS version
3.22.7-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
SAGA versions higher than 2.x are not officially supported. You one of the 3rd party plugins with new SAGA versions.
