### ISSUE TITLE
QGIS 3.22 LTR missing Lidar support on Mac (Regression)

### ISSUE THREAD

**Issue by spatialthoughts** [qgis/QGIS#48897]
### What is the bug or the crash?

The latest ltr QGIS 3.22.7 on mac is unable to open laz files. Upon inspection it seems PDAL dependency is missing. QGIS 3.24 works fine on the same machine.

<img width="1504" alt="qgis" src="https://user-images.githubusercontent.com/5227506/172314915-57425a22-356a-42cd-bf12-1a575ab3325d.png">

I also reported this in QGIS Mac Packager repo more than 1 month before but it didn't get any attention. This is a serious issue affecting the LTR that needs to be addressed soon. Hope the fix is simple. Happy to provide additional info and test builds.

### Steps to reproduce the issue

Load any LAS/LAZ file and QGIS doesn't recognize it.

### Versions

QGIS 3.22.x on Mac

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://github.com/qgis/QGIS-Mac-Packager/issues/149

**Comment by alexbruy** [comment]
Is this still an issue?

**Comment by spatialthoughts** [comment]
This is no longer an isseu on QGIS 3.28 LTR.
