### ISSUE TITLE
QGIS hangs when using vector tile sets as source in a virtual layer

### ISSUE THREAD

**Issue by Titou325** [qgis/QGIS#48908]
### What is the bug or the crash?

Hi folks!

I have been working on a little project to mimic a style similar to the Mapbox base map using Mapbox tile sets, and it seems that we cannot use remote vector tile sets as a source to a virtual layer. Using the layer in the standard layer interface does the job, but it can become a little clunky and won't show in the legend.

I have thus tried copying and pasting the source URL and providers as an embedded layer in the Virtual Layer interface, but this crashes as soon as I try running a query. Here is an example of the setup.

![image](https://user-images.githubusercontent.com/18631734/172501763-aba3e5d6-8948-4d61-b4fc-24bfc955527a.png)

I believe that vector tiles may not be supported at the current time, as these layers don't show up in the "import" pane? However, the option is here and may be confusing. If not possible, I guess the feature would be very helpful for some of us.

### Steps to reproduce the issue

* Add a working vector tileset source to QGIS.
* It works fine when added to the map layers as-is
* Copy the source attribute from the layer metadata
* Create a new virtual layer from the interface
* Add a vectortile embedded layer and paste the copied source
* Select arbitrary features using SQL
* Click Add or Test
* QGIS hangs

### Versions

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
QuickOSM | 2.0.0
quick_map_services | 0.19.26
MemoryLayerSaver | 4.0.4
qgiscloud | 3.3.11
qgis_resource_sharing | 0.16.0
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

[sample-project.qgz.zip](https://github.com/qgis/QGIS/files/8857182/sample-project.qgz.zip)

Using the file above, go to Virtual Layer > add > vectortile, name it ``terrain``, add source ``type=xyz&url=https://api.mapbox.com/v4/mapbox.mapbox-terrain-v2/%7Bz%7D/%7Bx%7D/%7By%7D.vector.pbf?access_token%3Dsk.eyJ1IjoidGl0b3UzMjUiLCJhIjoiY2w0NHRmeDlxMDUybjNycWYyNmZ0bnNhNCJ9.EL19i2rmKBlpMaTm69_M9g&zmax=14&zmin=0`` and type in the following SQL query:

````
SELECT * FROM terrain.contour
````

QGIS hangs

**Comment by nyalldawson** [comment]
@Titou325 https://github.com/qgis/QGIS/pull/48988 fixes the hang -- but note that using a vector tile layer as a source layer for a virtual layer isn't supported, and won't work even with that fix. (The fix avoids the hang, and also prevents users from selecting a vector tile provider in that dialog)
