### ISSUE TITLE
Layout's Map background color does not follow project's background color

### ISSUE THREAD

**Issue by LoulouLouis** [qgis/QGIS#48931]
### Feature description

Hi there, 
I have a project and corresponding layout. 
On the project, the background color was white, leading to countries appearing surrounded by a white ocean. The layout was showing the same color theme.
I decided to change the project's background color, but is was not modified in the layout, even though I refreshed and saved-closed-restared. Of course I made sure the map was unlocked.
The only thing that worked was adding another map on the layout, this new map would have the new background color included.
I suggest modifying this by allowing the colors on the layout to reflect directly the project's background color. 
Thank you, 

Best, 

Louis

**Comment by baswein** [comment]
@LoulouLouis - Just wanted to make sure you knew that the background color of the map layout item can be changed in item properties under the background section. This doesn't allow for syncing the background color with the main canvas but does give you control without having to add another map.

**Comment by LoulouLouis** [comment]
@baswein - Thank you for your suggestions. yes, I knew about it. This will change the background of the layout, but won't change the background of the map. The map's background, in my case, represents the sea around the country that I am willing to show and without adding a specific layer for the sea.  Changing the layout's background color will only change the color outside the frame of the map.

**Comment by baswein** [comment]
Try this:

1. Select your map frame in your layout 
2. In the Item Properties of the map frame
3. Scroll down until you see Background 
4. The color box there will allow you to change the background of your map 

![image](https://user-images.githubusercontent.com/15817745/173166454-b3a24bb7-26c3-43f1-9fab-f7a8ef2d2ad2.png)

**Comment by baswein** [comment]
Another hack that I sometimes use is add an empty layer at the bottom of your project. Then set the style to inverted polygon and the color to whatever color you are interested in. This will create a global layer the color of your choosing that you can change at any time and it will be updated in your layout map view. 
![image](https://user-images.githubusercontent.com/15817745/173166849-d12a0be6-bab4-49d3-83a1-af98c44e5354.png)

**Comment by LoulouLouis** [comment]
Thank you so much! Both options work great.
