### ISSUE TITLE
test_analysis_processing modified source file tests/testdata/points_gpkg.gpkg

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#48937]
### What is the bug or the crash?

Running test_analysis_processing modified source file tests/testdata/points_gpkg.gpkg

### Steps to reproduce the issue

xvfb-run ctest -V --output-on-failure -R 'test_analysis_processing$'

### Versions

QGIS master - ecdf73621bb3be7c8b893b9ef6ac1e588619cf80
GDAL 3.2.0 
Sqlite 3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Spin-off of #25830

**Comment by strk** [comment]
Also fails in [CI](https://github.com/qgis/QGIS/runs/6804502176?check_suite_focus=true#step:13:194) with libsql 3.31 and GDAL 3.0.4

\cc @rouault

**Comment by strk** [comment]
Setting qgis/walForSqlite3 to false was uneffective, with both GDAL versions.
Here are some debugging logs:
```
QDEBUG : TestQgsProcessing::convertCompatible() XXX: opening points.gpkg now
QDEBUG : TestQgsProcessing::convertCompatible() XXXX CPLGetConfigOption(OGR_SQLITE_JOURNAL, nullptr):  
QDEBUG : TestQgsProcessing::convertCompatible() XXXX QgsSettings().value( QStringLiteral( 'qgis/walForSqlite3' ), true ).toBool():  false
QDEBUG : TestQgsProcessing::convertCompatible() XXXX bIsLocalGpkg:  false
QDEBUG : TestQgsProcessing::convertCompatible() XXXX bUpdate:  true
QDEBUG : TestQgsProcessing::convertCompatible() XXXX setting OGR_SQLITE_JOURNAL to DELETE
```

**Comment by strk** [comment]
I find the `bIsLocalGpkg` variable somewhat confusing as its value depends on `qgis/walForSqlite3` qgis setting and `OGR_SQLITE_JOURNAL` CPL config option. The logic of that is not clear to me

**Comment by strk** [comment]
Interesting fact (found on old now closed PR as a comment and verified now):

Marking the source file as non-writeable avoids the modification w/out breaking the test:

     chmod -w tests/testdata/points_gpkg.gpkg

**Comment by strk** [comment]
@rouault does it sound like a bug that I can get the behaviour I want by acting on file permissions but NOT by using the `qgis/walForSqlite3` setting ? Or should there be a different setting to express wanting to do that ?

**Comment by rouault** [comment]
I let you investigate what's going wrong. Normally when qgis/walForSqlite3 is false, bIsLocalGpkg should be false and it should reach https://github.com/qgis/QGIS/blob/4b255af80aeeda0afc23a0705b0cc98b7831383c/src/core/providers/ogr/qgsogrproviderutils.cpp#L1042

**Comment by strk** [comment]
I verified that OGR_SQLITE_JOURNAL was also set to DELETE but the file was still modified.
Are you saying that OGR_SQLITE_JOURNAL=DELETE should not result in a modified gpkg file ?

**Comment by rouault** [comment]
> Are you saying that OGR_SQLITE_JOURNAL=DELETE should not result in a modified gpkg file ?

that shouldn't. Except if the original GeoPackage file has it s journal_mode set to WAL. Can you ``echo "PRAGMA journal_mode" | sqlite3 the.gpkg`` ? If it reports WAL, then the journal_mode of the source file must be first changed in git with "PRAGMA journal_mode = delete"

**Comment by strk** [comment]
```
$ echo "PRAGMA journal_mode" | sqlite3 tests/testdata/points_gpkg.gpkg
delete
```

I'll investigate further. Maybe this has to do with gdal version too ? I'm running 3.2.2 and CI is running 3.0.4 ...

**Comment by strk** [comment]
As other .gpkg files in the repository have a WAL journal_mode I filed #48948 to turn them all into DELETE

**Comment by strk** [comment]
Testing this can be done using (from build dir): ./output/bin/test_analysis_processing convertCompatible

I've added more debugging and run with this simple operation, which MODIFIES the `points_gpkg.gpkg` file:

 > QgsVectorLayer( testDataDir + "points_gpkg.gpkg" );

Here are the debug lines from QgsOgrProviderUtils::GDALOpenWrapper:

    XXXX bIsGpkg:  true
    XXXX walForSqlite3:  false
    XXXX OGR_SQLITE_JOURNAL:
    XXXX bIsLocalGpkg:  false
    XXXX setting OGR_SQLITE_JOURNAL=DELETE thread-local config option
    XXXX papszOpenOptions are:

So, as you say `bIsLocalGpkg` is false when `walForSqlite3` is false, and `OGR_SQLITE_JOURNAL` is set to DELETE.

BUT, the file is still modified (and the file's `journal_mode` is set to `delete` in the file itself).

**Comment by strk** [comment]
Additional debugging:
````
XXXX bUpdate:  true
XXXX nOpenFlags:  5
```

**Comment by strk** [comment]
This block is the responsible for the gpkg modification:
https://github.com/qgis/QGIS/blob/master/src/core/providers/ogr/qgsogrproviderutils.cpp#L1087
Note it only runs for GDAL < 3.3.1 which is the case both on my machine and on CI

In particular, in that block, the culprit is:
> DROP TRIGGER gpkg_metadata_reference_column_name_update

Should that trigger simply be removed from the testcase directly then ? Or is that needed to test that rmoval ?

Besides, I wonder why simply creating a layer ends up calling QgsOgrProviderUtils::GDALOpenWrapper with the bUpdate parameter set to true, is that expected that layers open datasets in read-write mode by default ?

**Comment by rouault** [comment]
> Should that trigger simply be removed from the testcase directly then ?

I suspect the .gpkg file was created with GDAL < 2.4.0. It should be sufficient to update in git the version with the fixed trigger

**Comment by strk** [comment]
@rouault I've filed #48953 with batch removal of that trigger, it was in many files! It's also going to conflict with #48948 which does the journal_mode=delay change, so I wonder if I should ONLY do the trigger removal in the PR having CI check for modifications and be done if it passes.

**Comment by strk** [comment]
Ok I confirm that BOTH setting qgis/walForSqlite3 to false AND dropping the bogus trigger from the gpkg file are required to fix this issue. I pushed both to #48904 where CI is also going to look for changes in source tree. Fingers crossed !
