### ISSUE TITLE
I can't install qgis on my windows 10.

### ISSUE THREAD

**Issue by danielcst37** [qgis/QGIS#48955]
### What is the bug or the crash?

Whenever I try to install QGIS, after downloading the application, an error occurs.

### Steps to reproduce the issue

Whenever I try to install QGIS, after downloading the application, an error occurs. Can you help me?
The text that appears is the following:
This processor type does not support this installation package. Contact the product supplier.

### Versions

3.22.7 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@danielcst37, What is your CPU? Is it a 64-bit (x86-64 architecture) CPU? Is your Operative System 64-bit?

**Comment by danielcst37** [comment]
Good afternoon. My Operative System is 32 bits, processor based on x64.
Thank you very much for your attention.

Em sáb., 11 de jun. de 2022 às 08:12, Andrea Giudiceandrea <
***@***.***> escreveu:

**Comment by agiudiceandrea** [comment]
> Good afternoon. My Operative System is 32 bits

Hi @danielcst37, "32 bit binaries are not produced anymore" (see https://qgis.org/en/site/forusers/download.html). QGIS 3.22 and QGIS 3.24 installer for Windows are only available for 64 bit systems.

The more recent QGIS versions it is possible to install on a 32 bit Windows system are:
QGIS 3.16.16 (2022-01-15) https://download.qgis.org/downloads/QGIS-OSGeo4W-3.16.16-1-Setup-x86.exe
QGIS 3.18.3 (2021-05-15) https://download.qgis.org/downloads/QGIS-OSGeo4W-3.18.3-1-Setup-x86.exe

**Comment by danielcst37** [comment]
Thank you soo much

Em sáb., 11 de jun. de 2022 19:35, Andrea Giudiceandrea <
***@***.***> escreveu:
