### ISSUE TITLE
Cannot build qgis_native using Qt6 on Windows

### ISSUE THREAD

**Issue by MCA4213** [qgis/QGIS#48956]
### What is the bug or the crash?

The QWinExtra in Qt6 has been removed , so these headers not exist any more:

#include <QtWinExtras/QWinTaskbarButton>
#include <QtWinExtras/QWinTaskbarProgress>
#include <QtWinExtras/QWinJumpList>
#include <QtWinExtras/QWinJumpListItem>
#include <QtWinExtras/QWinJumpListCategory>

### Steps to reproduce the issue

buildin using:
 msvc 2022
 Windows 11
 Qt 6.3

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Qgis isn't qt 6 compatible yet -- there's a significant amount of work remaining for this. For now we aren't accepting tickets regarding qt 6 builds
