### ISSUE TITLE
At closing I had this ...

### ISSUE THREAD

**Issue by Bavarello** [qgis/QGIS#48950]
## User Feedback

At closing I had this ...

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000b24 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

,

### Versions

.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Useless without more details or anything that may help replicability.
