### ISSUE TITLE
Freeze/bugs/errors on Qgis when using map

### ISSUE THREAD

**Issue by alexbbit** [qgis/QGIS#49009]
### What is the bug or the crash?

We have a computer (computer1) with this configuration :  I9-10980XE 3Ghz +  motherboard : Asus Prime X299-A II + 128Go Ram + Nvidia GeForce RTX 3080 + 2to flash. On this computer, we have lot of lags and bugs when we use Qgis. We haven’t any problem on others applications. We tried our Qgis and same map on an other computer (computer2) (I7 8700 + 32gb de ram + ssd nvme 970 evo + gtx 1060 3gb) and there is no problem. All works well. 

On the computer 1, we updated all the components, changed settings in CPU usage (add overclocking), updated windows. It’s look like the processor is not used well at its maximum level for Qgis. After 10mn of usage the software starts to slowdown.

Do you have any idea or have already seen this kind of problems with Intel I9 processor ? Is there prerequisite for Qgis and optimisation ? 

### Steps to reproduce the issue

export and navigate on the map

### Versions

3.22.5

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
You should try with a new [User profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) on that computer, as suggested in the issue report template? Probably some local/plugins configs...

**Comment by alexbbit** [comment]
We already tried that and that changed nothing. Do you use Qgis on the same CPU as us ?

Regards,

Cordialement,

***@***.***
[LinkedIn]<https://linkedin.com/company/bluebearsit>
[Twitter]<https://twitter.com/bluebearsit>
***@***.***>

Alexis CHALUS
Administrateur Systèmes et Réseaux


***@***.***
Fixe +33 4 28 29 86 50
13 rue des Aulnes, 69760 LIMONEST
www.bluebearsit.com<http://www.bluebearsit.com/>




De : Harrissou Sant-anna ***@***.***>
Envoyé : jeudi 16 juin 2022 21:10
À : qgis/QGIS ***@***.***>
Cc : Alexis Chalus ***@***.***>; Author ***@***.***>
Objet : Re: [qgis/QGIS] Freeze/bugs/errors on Qgis when using map (Issue #49009)


You should try with a new User profile<https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles> on that computer, as suggested in the issue report template? Probably some local/plugins configs...

**Comment by DelazJ** [comment]
No. But you didn't mention that you tried it nor checked the corresponding option. Hence my suggestion (and because it used to solve this kind of local issues).

**Comment by nyalldawson** [comment]
There's nothing actionable here. If additional details on reproducing/tracking down this issue can't be supplied then the ticket should be closed.
