### ISSUE TITLE
Missing CP949(Korean), UTF-8 encoding at Export Project to DXF menu

### ISSUE THREAD

**Issue by gooooooooodeasy** [qgis/QGIS#49018]
### What is the bug or the crash?

There's no CP949(Korean) and UTF-8 encoding at [Export Project to DXF] menu at QGIS 3.24.3. That encoding was there at QGIS 3.16
Can anyone fix this issue?

Steps to reproduce the issue
go to Project > Export Project to DXF menu.

Versions
QGIS 3.24.3

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/107596641/173977668-eb33ec72-0bff-4982-b82c-44ae8a0f4bb4.png)

![image](https://user-images.githubusercontent.com/107596641/173977789-063a0956-b6c2-4286-ba2b-011dae239974.png)

![image](https://user-images.githubusercontent.com/107596641/173977892-4839bb27-062b-4b01-a48e-8657977c6951.png)

### Versions

QGIS 버전
3.24.3-Tisler
QGIS 코드 리버전
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
tmsforkorea
3.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gooooooooodeasy** [comment]
fix plz...
![image](https://user-images.githubusercontent.com/107596641/173978731-878832a9-6d2a-4b50-8ce9-9bd9130d98b3.png)


![image](https://user-images.githubusercontent.com/107596641/173978720-c3a1a8e7-4c85-4b7a-b17b-934ae0aac7e6.png)

**Comment by alexbruy** [comment]
Duplicates #44756.

**Comment by gooooooooodeasy** [comment]
> Duplicates #44756.

NO!!! THIS ISSUE AGAIN!!!!
