### ISSUE TITLE
layer_property(layer, 'path') returns NULL for local raster layer

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#49011]
### What is the bug or the crash?

The expression function `layer_property(layer, property)` says:
`path: File path to the layer data source. Only available for file based layers.`

For me it returns `NULL` for any raster file layer I have tried, in different locations on my local system. It works correctly for vector layers, e.g. the "world" easter egg layer's file.

### Steps to reproduce the issue

1. Load a raster file as layer
2. Use any place you can get the expression editor dialog (e.g. Processing -> "Geometry by expression")
3. Enter `layer_property('Your Layer ID', 'path')`

The preview should show the path to the layer but instead shows `NULL`.

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by kannes** [comment]
Thanks @nyalldawson <3

**Comment by colinvv** [comment]
I am seeing the same behavior in QGIS 3.40.2 Bratislava, for polygons as well as rasters. Is there a fix to this?

**Comment by kannes** [comment]
> I am seeing the same behavior in QGIS 3.40.2 Bratislava, for polygons as well as rasters. Is there a fix to this?

Please make a new bug report with the exact steps to reproduce the issue.
