### ISSUE TITLE
Create connections to the Oracle Database using JDBC strings

### ISSUE THREAD

**Issue by karinpatenge** [qgis/QGIS#49014]
### Feature description

Database tools like SQL Developer typically provide the possibility to directly use the JDBC string and the Oracle JDBC Thin Client to connect to the Oracle Database. This feature would also be helpful to configure a wallet-less connection using TLS to an Oracle Autonomous Database.
![Capture](https://user-images.githubusercontent.com/37591997/173866389-47874cb1-7597-4b88-b529-cdd7ee66b87d.PNG)

**Comment by jef-n** [comment]
QGIS doesn't use jdbc.  The part following @ however should work in "database".
