### ISSUE TITLE
Error in converting .gpkg to .shp

### ISSUE THREAD

**Issue by VAPS16** [qgis/QGIS#49022]
### What is the bug or the crash?

Export to vector file failed.
Error: Creation of field name:is failed (OGR error: Can't create field name_is in Shape DBF file, reason unknown.)

### Steps to reproduce the issue

1. export
2. ESRI shapefile
3. name and location
4. save

### Versions

3.22 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ismailsunni** [comment]
@VAPS16 could you give sample data? I tried to replicate it with attribute names `name:is` and `name_is`, and both are working fine.
