### ISSUE TITLE
QGIS startup fails: Couldn't load plugin 'processing_saga' 

### ISSUE THREAD

**Issue by cathsaigh** [qgis/QGIS#49034]
### What is the bug or the crash?

When starting QGIS, I receive an Error Window stating that startup failed due to plugin load failure.  If I hit close, QGIS will continue to load.  

ModuleNotFoundError: No module named 'processing.core.ProcessingLog' 
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 401, in loadPlugin
    __import__(packageName)
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/__init__.py", line 24, in 
    from processing_saga.sagaProviderPlugin import SagaProviderPlugin
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaProviderPlugin.py", line 27, in 
    from processing_saga.sagaProvider import SagaProvider
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaProvider.py", line 33, in 
    from processing_saga.sagaAlgorithm import SagaAlgorithm
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaAlgorithm.py", line 51, in 
    from processing_saga import sagaUtils
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
  File "/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/sagaUtils.py", line 31, in 
    from processing.core.ProcessingLog import ProcessingLog
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 888, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
ModuleNotFoundError: No module named 'processing.core.ProcessingLog'

Python version: 3.8.10 (default, Mar 15 2022, 12:22:08) [GCC 9.4.0] 
QGIS version: 3.24.3-Tisler Tisler, cf22b74e01 

Python Path:
/usr/share/qgis/python
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/home/casey/.local/lib/python3.8/site-packages
/usr/local/lib/python3.8/dist-packages
/usr/lib/python3/dist-packages
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/mmqgis/forms
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools

### Steps to reproduce the issue

1. Startup QGIS
2. Upon startup, Error Message Window appears
3. QGIS won't continue to load until I close Error Message Window

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
easy_raster_splitter | 2.0
quick_map_services | 0.19.29
profiletool | 4.2.2
PointConnector | 2.0
mmqgis | 2021.9.10
DigitizingTools | 1.5.1
TerrainShading | 0.9.3
processing_wbt | 1.3.4
openlayers_plugin | 2.0.0
GeoCoding | 2.18
DEMto3D | 3.5
qgis2web | 3.16.0
LayerBoard | 1.0.1
nominatim | 1.4.2
Qgis2threejs | 2.7.1
layer2kmz | 1.5.3
qgisnetworklogger | 0.2.0
QuickWKT | 3.1
FreehandRasterGeoreferencer | 0.8.3
AzimuthDistanceCalculator | 2.0.2
ParallelLineConstruction | 0.2
QuickOSM | 2.0.1
ee_plugin | 0.0.4
spatial_query_with_values | 1.0.2
pg_raster_import | 1.0.10
shapetools | 3.4.6
LAStools | 1.4
latlontools | 3.6.4
parcel_plugin | 3.8
wbt_for_qgis | 1.0.5
osminfo | 0.7.1
TopoUSM-QGIS-master | 0.2
Check_defined_Convert_CRS | 0.2
rvt-qgis | 0.9.2
open_lidar_tools | 2.2.1
qgis-maptiler-plugin | 3.0.3
dimensioning | 0.2
qgis_resource_sharing | 0.16.0
qconsolidate3 | 0.2.0
qgsAzimuth | 0.9.15
OSMDownloader | 1.0.3
grassprovider | 2.12.99
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.24.3-Tisler
QGIS code revision
[cf22b74e01](https://github.com/qgis/QGIS/commit/cf22b74e01)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
easy_raster_splitter
2.0
quick_map_services
0.19.29
profiletool
4.2.2
PointConnector
2.0
mmqgis
2021.9.10
DigitizingTools
1.5.1
TerrainShading
0.9.3
processing_wbt
1.3.4
openlayers_plugin
2.0.0
GeoCoding
2.18
DEMto3D
3.5
qgis2web
3.16.0
LayerBoard
1.0.1
nominatim
1.4.2
Qgis2threejs
2.7.1
layer2kmz
1.5.3
qgisnetworklogger
0.2.0
QuickWKT
3.1
FreehandRasterGeoreferencer
0.8.3
AzimuthDistanceCalculator
2.0.2
ParallelLineConstruction
0.2
QuickOSM
2.0.1
ee_plugin
0.0.4
spatial_query_with_values
1.0.2
pg_raster_import
1.0.10
shapetools
3.4.6
LAStools
1.4
latlontools
3.6.4
parcel_plugin
3.8
wbt_for_qgis
1.0.5
osminfo
0.7.1
TopoUSM-QGIS-master
0.2
Check_defined_Convert_CRS
0.2
rvt-qgis
0.9.2
open_lidar_tools
2.2.1
qgis-maptiler-plugin
3.0.3
dimensioning
0.2
qgis_resource_sharing
0.16.0
qconsolidate3
0.2.0
qgsAzimuth
0.9.15
OSMDownloader
1.0.3
grassprovider
2.12.99
sagaprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is a local issue - you've somehow got an old version of the plugin in `/home/casey/.local/share/QGIS/QGIS3/profiles/default/python/plugins/processing_saga/` -- I'd tried removing that folder and reloading

**Comment by cathsaigh** [comment]
Thanks - that did it.
