### ISSUE TITLE
Versions information copied from QGIS to GitHub issue has broken rendering

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#49054]
### What is the bug or the crash?

When filing a bug we are instructed to "In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here."

If I do that, the result is what's between the two OOOOOOOOOOOOOOOOOOOOOO lines below:

OOOOOOOOOOOOOOOOOOOOOO

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e01
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.4 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS version
3.24.3-Tisler
QGIS code revision
[cf22b74e01](https://github.com/qgis/QGIS/commit/cf22b74e01)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

OOOOOOOOOOOOOOOOOOOOOO

The table has broken columns (I presume), a false header, some inline CSS shown as code, and the text appearing again as list below.

### Steps to reproduce the issue

1. Help -> About
2. Click in table
3. Ctrl-A, Ctrl-C
4. Paste to GitHub

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e01
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.10 (Ubuntu 12.10-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Also happening on uptodate Archlinux IIRC. Also this is not a new bug but has been happening for many months (or more) already.

**Comment by alexbruy** [comment]
Duplicates #42037?

**Comment by kannes** [comment]
Hm, might be the same root cause but for me I **do** get a Markdown formatted table with bugs plus extra redundant text.
