### ISSUE TITLE
QGis crash during polygon editing

### ISSUE THREAD

**Issue by Bubusf** [qgis/QGIS#49056]
### What is the bug or the crash?

QGis frozen and crash

### Steps to reproduce the issue

During editing polygons. Erase, add vertex, combine, cut polygon etc.

### Versions

QGis 3.22.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

## User Feedback

Try to modifie a polygone. It's the second crash since this morning for the same reson

## Report Details

**Crash ID**: [f4216db6ee0f63ce51b0d1c1de03b0c8295793de](https://github.com/qgis/QGIS/search?q=f4216db6ee0f63ce51b0d1c1de03b0c8295793de&type=Issues)

**Stack Trace**
<pre>
QgsVertexTool::~QgsVertexTool :
QgsPointLocator::verticesInRect :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::nearestVertex :
QgsVertexTool::findCoincidentVertices :
QgsVertexTool::startDraggingMoveVertex :
QgsVertexTool::startDragging :
QgsVertexTool::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Bubusf** [comment]
Come on, another one...

During points (along line) modifications. Move, erase, create new, etc.

## User Feedback

efq

## Report Details

**Crash ID**: [f4216db6ee0f63ce51b0d1c1de03b0c8295793de](https://github.com/qgis/QGIS/search?q=f4216db6ee0f63ce51b0d1c1de03b0c8295793de&type=Issues)


**Stack Trace**
<pre>
QgsVertexTool::~QgsVertexTool :
QgsPointLocator::verticesInRect :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::nearestVertex :
QgsVertexTool::findCoincidentVertices :
QgsVertexTool::startDraggingMoveVertex :
QgsVertexTool::startDragging :
QgsVertexTool::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by uclaros** [comment]
Can you run check validity on your data?
