### ISSUE TITLE
Crashing when closing 3D view

### ISSUE THREAD

**Issue by klakar** [qgis/QGIS#49065]
### What is the bug or the crash?

Closing a 3D view, creating a new project when a 3D view is open or in other ways closing the 3D view will crash QGIS.
 

### Steps to reproduce the issue

(Any project with a 3D view open.)
1. Add "World" and set a projected coordinate system.
2. Open 3D view (ctrl + alt + M) and interact with it.
4. Close the 3D view
5. Crash

I've tried with different data sources, but only on one installation (Ubuntu Focal).

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Zorin OS 16.1
  |   |   |  
Active Python plugins
processing | 2.12.99
MetaSearch | 0.3.6
sagaprovider | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Zorin OS 16.1

Active Python plugins
processing
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The behavior was recorded during Live Stream on YouTube where QGIS 3.26 was "unboxed".

https://youtu.be/E8WRiRm1tQ0

First crash at 30:38 then a couple of more times later in the stream.
More crashes at 41:23, 46:02 (with some additional bug tracking https://youtu.be/E8WRiRm1tQ0?t=2760) ...

**Comment by klakar** [comment]
Now also tested on Ubuntu (Pop_OS!) 22.04.
And the same problem is NOT affecting this installation.
So far only problems with Zorin, that is based on 20.04.

**Comment by klakar** [comment]
The QT version is very likely the issue. I just tried the Flatpak version of 3.26 on Zorin, which has 5.15, and it works just fine.
So I guess the builds for Ubuntu 20.04 should come with a "warning".
If you want 3D, use the Flatpak in stead.

**Comment by nyalldawson** [comment]
I think we can close this -- all the official builds are based on 5.15 now
