### ISSUE TITLE
No settings validation when settings values from QgsSettings

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#49060]
### What is the bug or the crash?

I'm not sure if this should be a feature request or a bug but I noticed that when settings a value from `QgsSettings` , I noticed that there are no type check and this then changes the value type.

I'm unsure if this could lead to some issues but I think that at least type-checking should be doable.

### Steps to reproduce the issue

1. Open the python console
2. 
```
settings = QgsSettings()
currentSetting = settings.value('app/projections/promptWhenMultipleTransformsExist')
settings.setValue('app/projections/promptWhenMultipleTransformsExist','5')
```

3. Check the setting value in settings-> advanced mode 

### Versions

Tested on 3.22 in win10 , issue should still be present in any versions.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
There's a newer settings which sits on top of qgssettings and provides validation. Check the various settings registry classes.
