### ISSUE TITLE
Metasearch Catalog Client crash QGIS when connecting to CSW server over https

### ISSUE THREAD

**Issue by lindhor** [qgis/QGIS#49061]
### What is the bug or the crash?

When connecting to a CSW service using https via Metasearch Catalog Client it shows the attached error and crashes the whole QGIS process.

Using the same CSW service via http works, so related to https. Probably related to "I’ve compiled a program under Windows and it crashes: why?" on https://www.openssl.org/docs/faq.html

Disabling SSL verification under the Settings tab does not help.

Running on Windows Server 2019.

<img width="664" alt="image" src="https://user-images.githubusercontent.com/5376093/174457757-9660fb88-f28b-46f8-91ab-4a3bdf9fb2f1.png">

### Steps to reproduce the issue

1. Click Metasearch 
2. Select the Services Tab
3. Click New to add new CSW service config
4. Specify a name and a https based csw service url like https://localhost/CSW?service=CSW&request=GetCapabilities&version=2.0.2
4. Click Service Info
5. Watch the Crash!

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 1809

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lindhor** [comment]
Tested this in 3.28.1-1 release. Same issue still.

**Comment by pathmapper** [comment]
Not reproducible with current `master`, tested with https://geodatenkatalog-niederrhein.de/csw.
