### ISSUE TITLE
QGIS crashes if you add a QgsExtentGroupBox and try to Draw on the Canvas

### ISSUE THREAD

**Issue by stuartmarsden** [qgis/QGIS#49066]
### What is the bug or the crash?

QGIS crashes immediately as you press the Draw on Canvas button on a QgsExtentGroupBox. I have seen this on QGIS 3.24.3 on both Windows and Linux.

### Steps to reproduce the issue

1. Run this code in the python console:

```
from PyQt5.QtGui import * 
from PyQt5.QtCore import * 

from qgis.gui import QgsExtentGroupBox

qeg = QgsExtentGroupBox()
dw = QDockWidget("Test Widget")
dw.setWidget(qeg)
iface.addDockWidget(QtCore.Qt.RightDockWidgetArea, dw)
qeg.setMapCanvas(iface.mapCanvas())
```
2. Press the Draw on Canvas button on the dock that appears on the right.
3. QGIS has now crashed.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.3-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.5
GDAL/OGR version | 3.4.3
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.38.5
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Arch Linux
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.1
poi_visibility_network | 0.3
quick_map_services | 0.19.29
mapflow | 1.6.2
QuickOSM | 2.0.1
ORStools | 1.5.2
ViewshedAnalysis | 1.7
OSMDownloader | 1.0.3
DataPlotly | 3.8.1
Qgis2threejs | 2.7
qchainage | 3.0.1
VoGisProfilTool | 3.0.2
ew_tool | 0.1
SRTM-Downloader | 3.1.17
los_tools | 0.5
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.24.3-Tisler
QGIS code branch
[Release 3.24](https://github.com/qgis/QGIS/tree/release-3_24)
Qt version
5.15.4
Python version
3.10.5
GDAL/OGR version
3.4.3
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.38.5
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.3
OS version
Arch Linux

Active Python plugins
plugin_reloader
0.9.1
poi_visibility_network
0.3
quick_map_services
0.19.29
mapflow
1.6.2
QuickOSM
2.0.1
ORStools
1.5.2
ViewshedAnalysis
1.7
OSMDownloader
1.0.3
DataPlotly
3.8.1
Qgis2threejs
2.7
qchainage
3.0.1
VoGisProfilTool
3.0.2
ew_tool
0.1
SRTM-Downloader
3.1.17
los_tools
0.5
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ismailsunni** [comment]
Confirmed on Ubuntu 20.04 and QGIS 3.26 also
