### ISSUE TITLE
the georeferencer gets stuck

### ISSUE THREAD

**Issue by beathabibi** [qgis/QGIS#49062]
### What is the bug or the crash?

I regularly use the georeferencer on my computer with Windows 7 and QGIS 3.16.16. Recently, I changed my computer to Windows 10, with an NVIDIA 3060 card and I have QGIS 3.16.16 and 3.22.7 installed, but with both the georeferencer freezes, when I hit run it doesn't progress from 0%. I have tried enabling or disabling OpenGL acceleration. The type of transformation I use is "linear". Could it be a configuration problem or a bug? Thanks and regards

### Steps to reproduce the issue

It may be a configuration problem of my QGIS on my hardware

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.16.16-Hannover | Revisión del código de QGIS | f5778a89
-- | -- | -- | --
Compilado contra Qt | 5.15.2 | Ejecutándose contra Qt | 5.15.2
Compilado contra GDAL/OGR | 3.4.1 | Ejecutándose contra GDAL/OGR | 3.4.1
Compilado contra GEOS | 3.10.0-CAPI-1.16.0 | Ejecutándose contra GEOS | 3.10.0-CAPI-1.16.0
Compilado contra SQLite | 3.35.2 | Corriendo contra SQLite | 3.35.2
Versión del cliente PostgreSQL | 13.0 | Versión de SpatiaLite | 5.0.1
Versión de QWT | 6.1.3 | Versión de QScintilla2 | 2.11.5
Compilado contra PROJ | 8.2.1 | Ejecutándose contra PROJ | Rel. 8.2.1, January 1st, 2022
Versión del SO | Windows 10 Version 2009
Active python plugins | attributeBasedClustering; DataPlotly; DEMto3D; GeoCoding; HCMGIS; Hqgis; LAStools; mmqgis; pgRoutingLayer; pointsamplingtool; processing_fusion; profiletool; qad; Qgis2threejs; qgis2web; qgisgbifapi; quick_map_services; raster_tracer; rivergis; SemiAutomaticClassificationPlugin; SentinelHub; SRTM-Downloader; ViewshedAnalysis; VoGisProfilTool; db_manager; MetaSearch; processing

</body></html>Versión de QGIS
3.16.16-Hannover
Revisión del código de QGIS
[f5778a89](https://github.com/qgis/QGIS/commit/f5778a89)
Compilado contra Qt
5.15.2
Ejecutándose contra Qt
5.15.2
Compilado contra GDAL/OGR
3.4.1
Ejecutándose contra GDAL/OGR
3.4.1
Compilado contra GEOS
3.10.0-CAPI-1.16.0
Ejecutándose contra GEOS
3.10.0-CAPI-1.16.0
Compilado contra SQLite
3.35.2
Corriendo contra SQLite
3.35.2
Versión del cliente PostgreSQL
13.0
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.3
Versión de QScintilla2
2.11.5
Compilado contra PROJ
8.2.1
Ejecutándose contra PROJ
Rel. 8.2.1, January 1st, 2022
Versión del SO
Windows 10 Version 2009
Active python plugins
attributeBasedClustering; 
DataPlotly; 
DEMto3D; 
GeoCoding; 
HCMGIS; 
Hqgis; 
LAStools; 
mmqgis; 
pgRoutingLayer; 
pointsamplingtool; 
processing_fusion; 
profiletool; 
qad; 
Qgis2threejs; 
qgis2web; 
qgisgbifapi; 
quick_map_services; 
raster_tracer; 
rivergis; 
SemiAutomaticClassificationPlugin; 
SentinelHub; 
SRTM-Downloader; 
ViewshedAnalysis; 
VoGisProfilTool; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@beathabibi have you tried if the issue occurs using a new QGIS user profile without any non core plugin installed?

**Comment by beathabibi** [comment]
Thanks for the advice, @agiudiceandrea. This is how it works, that is, it must be an installed plugin that causes the block. I don't have any experimental ones, they are all from the official QGIS repository

**Comment by agiudiceandrea** [comment]
@beathabibi, although the plugins are in the official QGIS repository, it is not guaranteed they will work well and not badly interfere with QGIS core functionalities.
It would be great if you could find the offending plugin or setting.

**Comment by beathabibi** [comment]
I will try to identify which plugin is causing the problem. Thanks for your help, @agiudiceandrea

**Comment by gazhay** [comment]
in 3.26 there is no georeferencer - at least it isn't in the raster menu and not listed as a plugin....

**Comment by agiudiceandrea** [comment]
> in 3.26 there is no georeferencer - at least it isn't in the raster menu and not listed as a plugin....

@gazhay, see https://github.com/qgis/QGIS/issues/49139#issuecomment-1164055349

**Comment by gazhay** [comment]
Ok, seems to be a documentation fault, but I had looked at changelogs for references to georeferencing and hadn't seen any about it moving menus. With the large amount of docs and tuts out there, I doubt I'll be the last to miss the change.

**Comment by agiudiceandrea** [comment]
> I had looked at changelogs for references to georeferencing and hadn't seen any about it moving menus.

See the animated GIF at https://www.qgis.org/it/site/forusers/visualchangelog326/index.html#feature-georeferencing-vector-layers-in-georeferencer

**Comment by gazhay** [comment]
I think there needs to be a text description mentioning the move as an animated gif doesn't really cut it.

Ymmv

**Comment by agiudiceandrea** [comment]
> I will try to identify which plugin is causing the problem.

@beathabibi have you found the offending plugin or setting?

**Comment by beathabibi** [comment]
I haven't had a chance to find out which plugin is causing the problem. When I need it, what I do is open a QGIS session with a profile that doesn't load the plugins, do the georeferencing I need, and then go back to the normal profile that has all the plugins loaded.
