### ISSUE TITLE
No Vector toolbar

### ISSUE THREAD

**Issue by bholtdwyer** [qgis/QGIS#49070]
### What is the bug or the crash?

There's no Vector menu in QGIS 3.22.5 on MacOS 10.15.7. I've tried re-installing the program twice, but the menu continues to just randomly disappear.

### Steps to reproduce the issue

Literally just install QGIS and the Vector menu isn't there in the top toolbar.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.5-Białowieża | QGIS code revision | 2a0a86f142
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 10.15
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.5-Białowieża
QGIS code revision
[2a0a86f142](https://github.com/qgis/QGIS/commit/2a0a86f142)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 10.15

Active Python plugins
sagaprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

I tried Settings > Profiles > New Profile and QGIS immediately crashed.

**Comment by SrNetoChan** [comment]
The current LTR version in 3.22.7, can you try with that?

Can you open the processing toolbox?

**Comment by DelazJ** [comment]
Probably Processing not being activated on the installation. Try enabling (in Plugins menu).

**Comment by bholtdwyer** [comment]
I reinstalled it (for a third time) and it now seems to be working fine in
3.22.8. I think in a previous run something from the Vector toolbar had
caused QGIS to crashed, so it disabled (and deleted) the toolbar. Still, I
shouldn't have to reinstall QGIS every time it crashes from an unexpectedly
heavy operation.

**Comment by alexbruy** [comment]
Is this still an issue?

**Comment by bholtdwyer** [comment]
No, it seems to have gone away after the reinstall.

**Comment by DelazJ** [comment]
> Still, I shouldn't have to reinstall QGIS every time it crashes from an unexpectedly heavy operation

Many people still do/advise that but they shouldn't have to; starting with a new user profile most of the times cleans up the mess.
> Is this still an issue?

@alexbruy Could there be a situation during a reinstall where Processing could get deactivated (and reactivating would fail), leading to missing vector and Processing menus upon restarting? I'm asking because I had that feeling (#52623, #50478, #51662, #49956) although but again their reports it is unclear if installation was a trigger or an attempt to fix it. Or people deactivate Processing without noticing?

**Comment by agiudiceandrea** [comment]
@DelazJ, maybe ensuring that, even when the Processing core plugin is disabled, the Vector menu is present and contains an item like: "Activate the Processing plugin" which activates the Processing plugin or opens the Plugins manager.

**Comment by DelazJ** [comment]
It coule ne an option indeed, @agiudiceandrea

**Comment by alexbruy** [comment]
Let's close this, as the original issue is solved, and open a feature request as per @agiudiceandrea suggestion.
