### ISSUE TITLE
[layout] Lossless image compression not applied when exporting to PDF with "Print as raster" export setting checked

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#49079]
### What is the bug or the crash?

The rasterized layout image in a PDF exported from a print layout (Layout->Export as PDF...), with the "Print as raster" export setting checked, is always compressed with the "Lossy (JPEG)" method, although "Lossless" is selected as "Image compression" method in the "PDF Export Options" window.

### Steps to reproduce the issue

1. In the Layout window, check the layout "Print as raster" export setting
2. In the Layout window, click on the "Export as PDF..." button (or select the Layout->Export as PDF... menu item)
3. In the PDF Export Options window, select the "Lossless" image compression method
4. Save the PDF

Then, repeat from 2 to 4 and select the "Lossy (JPEG)" image compression method.

The generated PDF files result identical and the rasterized layout image within them result compressed with a JPEG (lossy) compression.

Sample QGIS project with two PDF files exported from the print layout with "Lossy (JPEG)" and "Lossless" image compression methods
[TEST_LOSSLESS_PDF.zip](https://github.com/qgis/QGIS/files/8937953/TEST_LOSSLESS_PDF.zip)

See the typical JPEG compression artifacts in both exported PDF files
![image](https://user-images.githubusercontent.com/16253859/174536072-f0001fc9-087b-47fd-9edb-4b75fa83756b.png)

The same happens also when setting the `QgsLayoutRenderContext.FlagLosslessImageRendering` flag in `QgsLayoutExporter.PdfExportSettings` and exporting the layout using the `QgsLayoutExporter` `exportToPdf` function.

### Versions

QGIS 3.22.7 and QGIS 3.24.3 (from OSGeo4W) on Windows 10

QGIS version
3.22.7-Białowieża
QGIS code revision
5a65627a
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1903

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1903

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The "Lossless" image compression method for PDF exported from layout has been introduced with PR https://github.com/qgis/QGIS/pull/37594.

**Comment by nyalldawson** [comment]
@agiudiceandrea 

does adding

      painter.setRenderHint( QPainter::LosslessImageRendering, mLayout->renderContext().flags() & QgsLayoutRenderContext::FlagLosslessImageRendering );

to qgslayoutexporter.cpp line 597 help?

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea
> 
> does adding
> 
> ```
>   painter.setRenderHint( QPainter::LosslessImageRendering, mLayout->renderContext().flags() & QgsLayoutRenderContext::FlagLosslessImageRendering );
> ```
> 
> to qgslayoutexporter.cpp line 597 help?

It seems to me adding
`      p.setRenderHint( QPainter::LosslessImageRendering, mLayout->renderContext().flags() & QgsLayoutRenderContext::FlagLosslessImageRendering );`
in qgslayoutexporter.cpp at https://github.com/qgis/QGIS/blob/597e8eebd47fedc9b9fc7278cce08ef79384b53d/src/core/layout/qgslayoutexporter.cpp#L591-L600 doesn't fix the issue
```c++
      QPainter p;
      if ( !p.begin( &printer ) )
      {
        //error beginning print
        return FileError;
      }

      p.setRenderHint( QPainter::LosslessImageRendering, mLayout->renderContext().flags() & QgsLayoutRenderContext::FlagLosslessImageRendering );
      layerExportResult = printPrivate( printer, p, false, subSettings.dpi, subSettings.rasterizeWholeImage );
      p.end();
      return layerExportResult;
```

**Comment by nyalldawson** [comment]
@agiudiceandrea 

Thanks for the testing! What about adding it to ALL the QPainters contracted throughout that class?
