### ISSUE TITLE
In case of WKT geometry NULL, it is saved to gpkg as "Linestring EMPTY" rendering impossible to use "Add Part" tool

### ISSUE THREAD

**Issue by djagar** [qgis/QGIS#49086]
### What is the bug or the crash?

The feature table is correctly imported as tab delimited text layer, with WKT geometry column value NULL.
After saving the feature table to a gpkg layer, all NULL geometries are exported as "Linestring EMPTY", which renders impossible to use the "Add part" GUI tool in order to populate the non existing geometries.

### Steps to reproduce the issue

See the description.

### Versions

3.22.5 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Expected result wuld be to leave the NULL value when saving to the gpkg layer. In this case, the "Add Part" GUI tool works, allowing the addition of geometries to a feature without an exisitng one (i.e. with a NULL value).

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a). In my case features with NULL geometry are excluded from export.

Please share test data and information about which export options are you using.

**Comment by djagar** [comment]
The issue is more than 1 year old, so I don't have the test data any more. I will close it for now and re-open if I encounter it in the actual version.
