### ISSUE TITLE
QGIS 3.26 OSGeo4W qgis_app.dll not found

### ISSUE THREAD

**Issue by kiri03** [qgis/QGIS#49104]
### What is the bug or the crash?

I installed QGIS QGIS (3.26.0). QGIS not loads at all.
![image](https://user-images.githubusercontent.com/79694334/174766987-c5e423d9-d819-44e4-8ff1-36ff475c74cd.png)
![image](https://user-images.githubusercontent.com/79694334/174769018-c6cfe176-3352-48ea-a422-55e354a0fe00.png)
![image](https://user-images.githubusercontent.com/79694334/174769327-7731c431-a499-49b5-86d3-598c164c869e.png)

### Steps to reproduce the issue

Completely remove original OSGeo4W
Download new OSGeo4W
Express Install
QGIS
GDAL
GRASS GIS
Error about crssync.exe

### Versions

QGIS not load.
Edición	Windows 10 Pro
Versión	21H2
Instalado el	‎26/‎05/‎2020
Compilación del sistema operativo	19044.1766
Experiencia	Windows Feature Experience Pack 120.2212.4180.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I looked at qgis-bin.env files and found nothing out of the ordinary when comparing it to qgis-bin.env from version 3.24.3 that works fine.

**Comment by jef-n** [comment]
Not reproducable.  BTW OSGeo4W issues should be filed on https://trac.osgeo.org/osgeo4w/
