### ISSUE TITLE
SAGA GIS fails to load due to JPEG.dll

### ISSUE THREAD

**Issue by jnederend** [qgis/QGIS#49102]
### What is the bug or the crash?

SAGA GIS does not load when launched from GUI or within QGIS processing Toolbox

### Steps to reproduce the issue

1. Install QGIS and SAGA GIS using advanced option in osgeo4w-setup.exe
2. Run SAGA GIS GUI
3. Immediately encounter system error "The code execution cannot proceed because jpeg.dll was not found. Reinstalling the program may fix this problem"
4. Open QGIS v3.26.0
5. Open Log messages panel
6. Encounter error message "Problem with SAGA installation: SAGA was not found or is not correctly installed" under 'Processing' [note: same error for GRASS]

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
()
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GroupStats
2.2.5
mapswipetool_plugin
1.2
MemoryLayerSaver
4.0.4
oneclickrasterstacking
1.1.0
plot_boundary
0.1.2
SemiAutomaticClassificationPlugin
7.10.6
vertical_photo_placer
0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Seems similar to this issue: https://github.com/qgis/QGIS/issues/47571

GRASS is also unavailable in QGIS.

I previously uninstalled QGIS from the old osgeo4w installer by uninstalling all components, then deleting the C:/OSGEO directory, and all traces of QGIS from the AppData folder, as well as from the Windows registry.

**Comment by jnederend** [comment]
possibly related to this GRASS issue too: https://github.com/OSGeo/grass/issues/2255

**Comment by jef-n** [comment]
Fixed OSGeo4W issue.

**Comment by jnederend** [comment]
Thank you!

**Comment by jef-n** [comment]
> Same problem here. What is now the correct solution? Wait for a newer build of QGIS? Use an older version of QGIS until this is fixed? How can I use SAGA GIS 7.8.2 which is included in QGIS 3.26 installation?

Update OSGeo4W.
