### ISSUE TITLE
Crashed while saving file

### ISSUE THREAD

**Issue by ElvesInTheWood** [qgis/QGIS#49100]
## User Feedback

Crashed during saving file

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002548 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Just adjust some attributes and tried to save the file before closing it.

### Versions

3.24.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> QGIS Version: 3.24.2-Tisler

@ElvesInTheWood I'm not sure there is enough information for the developers in this report but you should first consider addressing the two checkboxes in the issue template, that is:
- try on a new user profile
- test on a more recent version: 3.24 is no longer supported so either 3.22ltr or 3.26 might get more chances for a fix (if still occurs)
