### ISSUE TITLE
Crash on Exit

### ISSUE THREAD

**Issue by ChrisAtBFC** [qgis/QGIS#49108]
## User Feedback

Exited QGIS.  Crash happens when clicking top right X or using Project Menu.

## Report Details

**Crash ID**: [f26e947319260720a4bf05ba4d601320801e99fb](https://github.com/qgis/QGIS/search?q=f26e947319260720a4bf05ba4d601320801e99fb&type=Issues)

**Stack Trace**
<pre>
QThread::currentThread :
QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsProcessingToolboxModel::addProvider :
QgsProcessingToolboxModel::rebuild :
QObject::qt_static_metacall :
QgsProcessingRegistry::providerRemoved :
QgsProcessingRegistry::removeProvider :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyDict_GetItemString :
PyArena_New :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QObject::qt_static_metacall :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

### Steps to reproduce the issue

Click on X in top right or use Project Menu and exit QGIS

### Versions

QGIS version
3.22.7-Białowieża
QGIS code revision
5a65627a
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.18
mmqgis
2021.9.10
nominatim_locator_filter
0.2.4
SpreadsheetLayers
2.0.1
StreetView
3.2
vector_tiles_reader
3.2.2
what3words
4.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Have just installed 3.22.7 to replace 3.16 (which is still on the PC)  Am staying with Long Term Release versions.

**Comment by ismailsunni** [comment]
@ChrisAtBFC could you try with a new profile or without any plugins?

**Comment by ChrisAtBFC** [comment]
Hi,

I removed all of the optional plugins and this has fixed the issue.  The application starts and exits properly now.

Many thanks,

Chris
