### ISSUE TITLE
QGIS 3.24.* freezes for few seconds on each new window focus

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#49111]
### What is the bug or the crash?

Dear all,

I have been using QGIS for years but experiencing a very annoying problem for a few days. QGIS is very slow for many actions, when I click on menu, section, zoom... It freezes for a few seconds (with the waiting mouse icon, and "not responding" indication into the window title bar). After a freeze, I can do several actions without problem before a new freeze.

I can't explain when it started. But since then, I completely uninstalled QGIS (deleted app, folders, profiles) and the problem is still there, whatever version 3.24.3 or 3.24.2 used (which both worked well before).

I checked the message log panels, couldn't see any worrying message. Is there a kind of debug mode, to have more log messages to help you know more about what occurs ? I have no clue for now of the origin of the problem.

Any help will be greatly appreciated.

PS : my colleague works on the same qgz files, on the same network and Qgis version, and has no problem.

### Steps to reproduce the issue

The freeze often occurs when the Qgis windows get focus back.
I think the problem comes from an incompatibility between my OS (W11) and QGIS, maybe after system update ?

### Versions

3.24.2
3.24.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rbonnefoi** [comment]
After several new checks, it appears that getting the focus back on the Qgis window leads to a freeze for a few seconds, systematically.

**Comment by agiudiceandrea** [comment]
@rbonnefoi, have you really tried with a "new QGIS profile"? Could you please go to "QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here."?

**Comment by rbonnefoi** [comment]
Thanks for investigating my problem.

> @rbonnefoi, have you really tried with a "new QGIS profile"?
Yes I did. I also try to completely delete the Appdata/Qgis folder before clean reinstall

> Could you please go to "QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here."?

`<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


Version de QGIS | 3.24.3-Tisler | Révision du code | cf22b74e
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.4.3
Version de Proj | 9.0.0
Version de la base de données du registre EPSG | v10.054 (2022-02-13)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.38.1
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.24.3-Tisler
Révision du code
[cf22b74e](https://github.com/qgis/QGIS/commit/cf22b74e)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.4.3
Version de Proj
9.0.0
Version de la base de données du registre EPSG
v10.054 (2022-02-13)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.38.1
Version de PDAL
2.3.0
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009




Extensions Python actives
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99`

**Comment by legnad** [comment]
This issue seems to be related to the browser widget. I had this issue in the past and it reappeared for me just recently when I switched to 3.28 LTR.

Closing the Browser Widget solved this issue for me (again). Might be related to mapped network drives that are not available sometimes.

**Comment by rbonnefoi** [comment]
Thanks for the tip. I keep it in mind in case the problem would be back again.

**Comment by pluberd** [comment]
I just switched to 3.28.15 and have the same problem. Closing the Browser-Widget helps.

**Comment by pluberd** [comment]
The reason is a unrechable share (I only can access the share while beeing in homeoffice):

![grafik](https://github.com/qgis/QGIS/assets/113139382/b04106c0-2cd5-4881-b399-9fa91dfd2716)

**Comment by vengelson** [comment]
Same problem. QGIS was "not responding" for 10 seconds, then worked again for 30-40 seconds.  You have to click on unreachable shared drive icon in Explorer and ask to disconnect it.  Then the problem is solved.
