### ISSUE TITLE
Forms. Slider control. Slider does not work in edit mode on double type field

### ISSUE THREAD

**Issue by Mario-F-F** [qgis/QGIS#49127]
### What is the bug or the crash?

In a double type field, the slider control is working properly when creating a feature, but it does not work when editing the field

### Steps to reproduce the issue

[TEST_slider.zip](https://github.com/qgis/QGIS/files/8958064/TEST_slider.zip)
Create any layer with a double type field. Configure form to use slider.
When you create a new feature, the slider allows to modify the value. 
If you edir the feature, the slider is set to 0, and any modification is not applied

(see attached database sample)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.26.0-Buenos Aires | Revisión del código de QGIS | 0aece2818e
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.5
Versión de GDAL/OGR | 3.5.0
Versión de PROJ | 9.0.1
Versión del registro de base de datos EPSG | v10.064 (2022-05-19)
Versión de GEOS | 3.10.3-CAPI-1.16.1
Versión de SQLite | 3.38.1
Versión de PDAL | 2.3.0
Versión del cliente de PostgreSQL | unknown
Versión de SpatiaLite | 5.0.1
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.1
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
cartography_tools | 1.2.1
DigitizingTools | 1.5.1
GroupStats | 2.2.5
kmltools | 3.1.21
mmqgis | 2021.9.10
OSMDownloader | 1.0.3
processing_r | 3.1.1
qchainage | 3.0.1
qgis_resource_sharing | 0.16.0
QuickOSM | 2.0.1
RasterAttributeTable | 1.1
shapetools | 3.4.6
SpreadsheetLayers | 2.0.1
valuetool | 3.0.15
ViewshedAnalysis | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Versión de QGIS
3.26.0-Buenos Aires
Revisión del código de QGIS
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.5.0
Versión de PROJ
9.0.1
Versión del registro de base de datos EPSG
v10.064 (2022-05-19)
Versión de GEOS
3.10.3-CAPI-1.16.1
Versión de SQLite
3.38.1
Versión de PDAL
2.3.0
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
cartography_tools
1.2.1
DigitizingTools
1.5.1
GroupStats
2.2.5
kmltools
3.1.21
mmqgis
2021.9.10
OSMDownloader
1.0.3
processing_r
3.1.1
qchainage
3.0.1
qgis_resource_sharing
0.16.0
QuickOSM
2.0.1
RasterAttributeTable
1.1
shapetools
3.4.6
SpreadsheetLayers
2.0.1
valuetool
3.0.15
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
I can confirm aswell on the most recent versions.
