### ISSUE TITLE
Trying to move one layer over another layer

### ISSUE THREAD

**Issue by harpertc** [qgis/QGIS#49137]
## User Feedback

I was trying to move the NSW mapping layer over the height layer

## Report Details

**Crash ID**: [2b3e95f249bc74ca5af5c0c8f5928912ac83781e](https://github.com/qgis/QGIS/search?q=2b3e95f249bc74ca5af5c0c8f5928912ac83781e&type=Issues)

**Stack Trace**
<pre>
QRhiGles2InitParams::newFallbackSurface :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QgsMapRendererCache::transformedCacheImage :
QgsMapRendererJob::layerImageToBeComposed :
QgsMapRendererJob::composeImage :
QgsMapRendererParallelJob::renderedImage :
QgsMapCanvas::mapUpdateTimeout :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Moving a layer in hierachy 

### Versions

QGIS version
3.22.7-Białowieża
QGIS code revision
5a65627a
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
1.1
contour
2.0.8
LAStools
1.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

The NSW maps and height layers do come from the AUS plugin

**Comment by Pedro-Murteira** [comment]
@harpertc more information is needed in order to adress this issue. A data sample of the project would help. Also, can you reproduce the issue on a fresh profile without plugins?

**Comment by harpertc** [comment]
I have tried to repeat the error but have not been able to do so. Sorry
