### ISSUE TITLE
QGIS consisently crashing 

### ISSUE THREAD

**Issue by jtrudd** [qgis/QGIS#49138]
### What is the bug or the crash?

using custom plugins/scripts I can crash qgis repeatedly. I get the same similar details every time.I think it has something to do with the mapTool. 

Stack Trace

QgsPaintEffect::boundingRect :
QgisApp::mapToolChanged :
QObject::qt_static_metacall :
QgsMapCanvas::mapToolSet :
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QObject::qt_static_metacall :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QObject::qt_static_metacall :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.3-Bia?owie?a
QGIS code revision: 1628765ec7
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

 Its when I add a new layer (that is created in a thread), then edit that layer using toggle editing and vertex tool, then click anywhere in the Layers window. 

### Versions

QGIS Version: 3.22.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Djedouas** [comment]
Hi @jtrudd 

Which custom plugins/scripts are you using? They are needed to investigate the issue, thanks.
