### ISSUE TITLE
What can I do?

### ISSUE THREAD

**Issue by SandroTibi** [qgis/QGIS#49143]
### What is the bug or the crash?

unexpected shutdown

### Steps to reproduce the issue

geos::noding::NodedSegmentString::size :
geos::geom::prep::PreparedGeometryFactory::prepare :
initGEOS :
GEOSPreparedIntersects_r :
pal::LabelPosition::intersects :
pal::Pal::extract :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.8-Hannover
QGIS code revision: 8c50902e
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Versions

QGIS Info
QGIS Version: 3.16.8-Hannover

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

en francais merci

**Comment by roya0045** [comment]
Update first, could be fixed by now.

**Comment by Pedro-Murteira** [comment]
@SandroTibi QGIS 3.16 is no longer being maintained, try QGIS 3.22 or 3.24. Can you specify what tools or part of QGIS were you working with when it crashed?
