### ISSUE TITLE
Logarithmic graduated symbology classes disappear from dialog when editing

### ISSUE THREAD

**Issue by guspolly** [qgis/QGIS#49141]
### What is the bug or the crash?

Normally, when you have chosen symbology classes, you can re-open the layer properties dialog and edit them again. But when I choose Logarithmic scale mode under the Graduated option, the already-chosen classes aren't transferred back into the dialog, and it acts as though I'm starting over completely.

### Steps to reproduce the issue

Right click layer
"Properties"
"Symbology"
"Graduated"
"Logarithmic scale"
Apply a scale from a value. Change the value, change the color ramp, change the number of classes.
"Apply"
"OK"
Right click layer
"Properties"
"Symbology"
The classes that had just been defined are no longer editable in the dialog box and must be re-created from scratch

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.2-Tisler | QGIS code revision | 13c1a028
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.2
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
cartogram3 | 3.1.4
coordinator | 0.4
latlontools | 3.6.3
quick_map_services | 0.19.29
processing | 2.12.99

</body></html>QGIS version
3.24.2-Tisler
QGIS code revision
[13c1a028](https://github.com/qgis/QGIS/commit/13c1a028)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
cartogram3
3.1.4
coordinator
0.4
latlontools
3.6.3
quick_map_services
0.19.29
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a).
