### ISSUE TITLE
On empty vector layers columns in attribute tables does not hide correctly

### ISSUE THREAD

**Issue by Kamzarr** [qgis/QGIS#49142]
### What is the bug or the crash?

On empty vector layer, when hiding columns in attribute table, column you want to hide doesn't hide. Instead last column in attribute table is hiding. When vector layer have any features, everything works correctly. The bug occurs at least in versions 3.22.0 - 3.26.0

![image](https://user-images.githubusercontent.com/75135894/175289965-593d3f56-c1ae-4152-bdec-ad48e34c45e1.png)

As you can see in screenshot, in "Organize Columns..." field2 is set to be invisible and others are set to be visible, but in the attribute table, last column (field4) is invisible and other columns are visible (including field2). 

### Steps to reproduce the issue

1. Create new empty vector layer with a few fields (do not add any features)
2. Go to attribute table
3. 
Right click on second column and select "hide column"
or
Choose "Organize Columns..." and uncheck second column, click ok
4. Second column is still visible but last column is not visible

### Versions

Wersja QGIS
3.26.0-Buenos Aires
Rewizja QGIS
0aece2818e
Wersja Qt
5.15.3
Wersja Pythona
3.9.5
Wersja GDAL/OGR
3.5.0
Wersja PROJ
9.0.1
Wersja bazy danych Rejestru EPSG
v10.064 (2022-05-19)
Wersja GEOS
3.10.3-CAPI-1.16.1
Wersja SQLite
3.38.1
Wersja PDAL
2.3.0
Wersja klienta PostgreSQL
unknown
Wersja SpatiaLite
5.0.1
Wersja QWT
6.1.6
Wersja QScintilla2
2.13.1
Wersja systemu operacyjnego
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

Wersja QGIS
3.22.0-Białowieża
Rewizja QGIS
d9022691f1
Qt version
5.15.2
Python version
3.9.5
Skompilowane z GDAL/OGR
3.3.2
Uruchomione z GDAL/OGR
3.3.3
PROJ version
8.1.1
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.18
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
qfieldsync
v4.1.1
quick_map_services
0.19.26
Submission
0.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Still valid in QGIS 3.28 and 3.34.
