### ISSUE TITLE
Qgis 3.26 geometry display error

### ISSUE THREAD

**Issue by AntonioDiSipio** [qgis/QGIS#49157]
### What is the bug or the crash?

When zooming in on geometries, the symbology of the geometries is not displayed correctly.
The same project opened with qgis 3.24 works perfectly.

### Steps to reproduce the issue

here the link of the geopackage
[https://drive.google.com/file/d/1Erw6wO81Zz74-FGleTk43ERr6v8vnigG/view?usp=sharing](url)

![Qgis 3 24](https://user-images.githubusercontent.com/105495205/175762732-15251b33-1d0d-4891-8676-631df6e6f33c.png)
![Qgis 3 26](https://user-images.githubusercontent.com/105495205/175762736-2742fd5a-3df9-442b-8ddf-d23bc9726b1f.png)

### Versions

Versione di QGIS
3.26.0-Buenos Aires
Revisione codice QGIS
0aece2818e
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.5.0
Versione PROJ
9.0.1
Versione database del Registro EPSG
v10.064 (2022-05-19)
Versione GEOS
3.10.3-CAPI-1.16.1
Versione SQLite
3.38.1
Versione PDAL
2.3.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I confirm the problem on OSGeo4W64 v2 QGIS 3.26.0 RC

**Comment by roya0045** [comment]
Had similar issues with geometries, but I couldn't quickly make a quick sample, thanks for making a demo project.

**Comment by roya0045** [comment]
I did some minimal testing with the project, changed symbol, changed file type and project crs. The issue still occurs.

Though I noticed that the data could not be exported to geojson and resulted in invalid geometry, shapefile was fine.

I'm not sure if the error may come from the rendering or from something deeper or even geos.

**Comment by Djedouas** [comment]
Confirmed on Ubuntu 21.04 hirsute
