### ISSUE TITLE
QGIS 3.26 crashes after loading las file with classification values > 127

### ISSUE THREAD

**Issue by redtreevole** [qgis/QGIS#49155]
## User Feedback

QGIS crashed after loading a las file, converting to copc.laz

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004534 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

copy laz file into project
QGIS displays bounding box of point cloud
QGIS builds copc.laz,
when done qgis crashes

### Versions

3.26

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Can you share the las file?

**Comment by redtreevole** [comment]
There is more nuance to this situation.  I am using QGIS 3.26 on Windows.  The crashing occurs after a las file has been built and the copc.laz would be loaded into the QGIS session.  One population of las files that are breaking this are products from the R lidR package.  However other point clouds have crashed this as well.  After I restart a session after a crash, I sometimes can load the copc.laz file that was built from las and it operates as expeceted.  However when I load larger copc.laz files QGIS will still crash.  I am adding a small las file that caused a crash.  But then will subsequently open when loading a copc.laz built from  it.

**Comment by redtreevole** [comment]
[seg_ctg_norm_filtered_-1119_501_norm.zip](https://github.com/qgis/QGIS/files/8985656/seg_ctg_norm_filtered_-1119_501_norm.zip)
This is a las file that has been previously been filtered and extracted from a USGS Lidar point cloud using the R package LidR

**Comment by uclaros** [comment]
Thanks for the dataset, I could replicate the crash.
Apparently, the point Classification data is somewhere erroneously handled as `signed char` instead of `unsigned char`, causing values greater that 127 to be returned as negatives, leading to a crash (current code asserts classification values are always positive).
The attached dataset has three points with a classification attribute of `135` which is interpreted as `-121` by qgis.

**Comment by redtreevole** [comment]
OK, thank you.  We have seen these classifications 125-140 before from a generation of PDAL pipelines we had used in 2021 on this specific USGS lidar point cloud. I will follow this upstream.  Thank you for your help.
