### ISSUE TITLE
Merging lines in geopackage won't allow saving

### ISSUE THREAD

**Issue by moendopi** [qgis/QGIS#49151]
### What is the bug or the crash?

I tried to merge two lines with the same attributes, and it did that fine, but when I went to save I get an error message and am unable to save my edits. I get a yellow ribbon and when I click see more I get a window with the following message:

"Commit Errors
Errors: ERROR: 1 geometry not changed.
Provider errors:
OGR error changing geometry: feature 0 not found"

### Steps to reproduce the issue

In the provided Geopackage I start with setting up the Attribute Form for the ContactsAndFaults layer. LocationConfidenceMeters is hidden and is set to a default value of 250, ExistenceConfidence is hidden and set to a default of 'Certain', same for IdentityConfidence, Symbol is a set to a Value Map widget using a .csv for the value (also provided) with the default value set to '15.02', notes is left as a Text Edit widget, and all other field are set to hidden. 

Snapping is turned on, with vertex, segment, middle of segments, and line endpoints checked as well as topological editing, intersection snapping, and snapping will take into consideration current state button turned on. 

In the ContactsAndFaults layer in the provided Geopackage there are two lines that intersect each other. I used the Merge Selected Features tool to merge them together. I then saved the edits and get a yellow ri
[Geopackage for merge error.zip](https://github.com/qgis/QGIS/files/8976572/Geopackage.for.merge.error.zip)
bbon that says "**Commit errors**: Could not commit changed to layer ContactsAndFaults". When I close that bar I get a red bar that reads "**Layer ContactsAndFaults:** OGR error changing geometry: feature 0 not found". 
[contacts_symbol_simple.csv](https://github.com/qgis/QGIS/files/8976566/contacts_symbol_simple.csv)

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
LAStools
1.4
pointsamplingtool
0.5.3
profiletool
4.2.2
qgis-maptiler-plugin
2.0.0
qProf
0.4.4
quick_map_services
0.19.28
raster_tracer
0.3.2
slyr_community
4.0.1
splitmultipart
1.0.0
VectorBender
0.2.1
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I had tried closing QGIS and reopening because sometimes that works. It didn't this time. The error was consistent. The provided Geopackage is not the one that I was using when I got the error. That one was a test to try in a new project with a clean geopackage (a copy of my standard one). I drew two lines and tried merging them and had the same result as I did when I first encountered the error so I know this wasn't just a one-off thing.

**Comment by Djedouas** [comment]
I reproduced this on QGIS 3.26 - Ubuntu 21.04

If I don't hide the `fid`field in the attribute form configuration, then it works.

I don't know if this behavior is supposed to be normal regarding a hidden field from the merging process point of view.

**Comment by vdmek** [comment]
You will also notice that when you remove the layer and then immediately re-associate the layer, edits will be committed.

So, on speculation, at some stage the layer will be erroneously flagged as read only or unable to commit, maybe due to temporary loss to original file system such as on servers.

Our system regularly goes off line and then comes back on and therefore the speculation that temporary loss of access to file system might trigger an event to flag layer to prevent editing.  However, when access to the file system is restored, there is no trigger to remove the previous flag.

Hope this may assist in trouble shooting.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a).

**Comment by Djedouas** [comment]
I don't reproduce the issue any more with latest LTR 3.28.11
