### ISSUE TITLE
Different font colors for legend item, group and subgroups

### ISSUE THREAD

**Issue by nik21las** [qgis/QGIS#49150]
### Feature description

It would be really neat to be able to color legend items different from subgroups or groups either via a click-option or as a data-defined override option.
In my line of works legends can sometimes be complex but need to fit in an DIN A5 formatted page, so the options to improve readability of the legend are quite limited (i.e., playing around with boldtype, italics and and sizes). In my opinion it would help to have groups / subgroups in black, items in darkish grey.

### Additional context

I tried to find out, whether my desired solution exists, e.g. as a data-defined override or something similar. QGIS documentation does not give any hints that such an option exists (https://docs.qgis.org/3.22/en/docs/user_manual/print_composer/composer_items/composer_legend.html). 
I think there was a somewhat similar feature request in 2015 but that lead nowhere so far.

**Comment by YoannQDQ** [comment]
Implemented in https://github.com/qgis/QGIS/pull/50959 (QGIS 3.30)
