### ISSUE TITLE
NULL + increment --> 0 for signed int field in Feature Attributes dialog for new feature

### ISSUE THREAD

**Issue by timothy-holmes** [qgis/QGIS#49163]
### Feature description

Default value in `line_num` field:
![image](https://user-images.githubusercontent.com/46288522/175863592-777d934e-a846-478c-9121-5ed374ef38ef.png)

Value in field at single increment:
![image](https://user-images.githubusercontent.com/46288522/175863662-85e2e779-74be-4fec-a502-b54cfd7f432b.png)

Possibly a 'feature' of Qt, but would really cool if an up arrow was to give a zero rather than the first number in a signed int. Eg. NULL + up = 0, NULL + down = -1.

**Comment by DelazJ** [comment]
Duplicate of #29019?

**Comment by timothy-holmes** [comment]
Yes,, it's a duplicate
