### ISSUE TITLE
Try using the following class:QgsGeometryCheck

### ISSUE THREAD

**Issue by usejustonce** [qgis/QGIS#49164]
### What is the issue about the documentation?

1.I was trying to develop the function of overlapping points in topology in QGIS. I went to the official qGIS documentation and found a suspected interface class:QgsGeometryCheck
 [https://qgis.org/pyqgis/3.22/analysis/QgsGeometryCheck.html](url)

2.However, according to the description of the document, I found that I could not meet the requirements of the document, maybe THERE was something wrong with my understanding of the document. Or maybe the interface class I'm looking for isn't relevant to my needs.
3.But the core is that I want to call the interface of QGIS to realize the function of checking overlapping points in topology. I checked a lot of materials, but none of them solved the problems I met. I hope someone can provide solutions or ideas.
4. I don't know how the code works, but it works in QGIS on the desktop.
![检查规则](https://user-images.githubusercontent.com/52092838/175895236-6a04dba8-4ee1-4eb8-a15d-49a12f8e5158.PNG)
![期望结果](https://user-images.githubusercontent.com/52092838/175895272-5d0e6d68-675a-4be4-a2e3-7717b57b020a.PNG)

**Comment by nicogodet** [comment]
GitHUb is used to report issues. Not to ask how QGIS works.

Same answer as https://github.com/qgis/QGIS/issues/49162
