### ISSUE TITLE
class：QgsGeometryCheck

### ISSUE THREAD

**Issue by usejustonce** [qgis/QGIS#49162]
### What is the issue about the documentation?

I was trying to do geometry checking in Python and found the QgsGeometryCheck class that could possibly be used by QGIS, but it is an unstable API, how should I use it?

**Comment by nicogodet** [comment]
Questions should be asked on qgis mailing list.

**Comment by lbartoletti** [comment]
cf https://github.com/qgis/QGIS-Enhancement-Proposals/issues/236

cc @Koyaani
