### ISSUE TITLE
Layout - expression for raster image keeps setting radiobutton to SVG image

### ISSUE THREAD

**Issue by 404-Geoscience** [qgis/QGIS#49165]
### What is the bug or the crash?

When creating an expression for dynamically loading raster images in a QGIS from a local folder, on clicking OK, the radiobutton jumps to .SVG image and the raster image will not load.

### Steps to reproduce the issue

Insert placeholder for raster image.
Data defined override expression: concat(@project_folder, '\\H_ALIGNMENT\\' ,"plotboxID", '_MBES.png').
 Expression is valid 
Press OK
Radiobutton Raster image has now jumped to SVG image

### Versions

QGIS version
3.24.0-Tisler
QGIS code revision
6b44a42058
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BezierEditing
version 1.3.2
DeepLearningTools
0.2.0
league_tools
0.1
openlayers_plugin
2.0.0
ParallelLineConstruction
0.2
plugin_reloader
0.9.1
pointsamplingtool
0.5.3
qchainage
3.0.1
slyr_community
4.0.1
SplitPolygonShowingAreas
0.13
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
See also https://github.com/qgis/QGIS/issues/47981, https://github.com/qgis/QGIS/issues/38031, https://github.com/qgis/QGIS/issues/37804 and the allegedly fixed https://github.com/qgis/QGIS/issues/42280.

**Comment by 404-Geoscience** [comment]
Further testing shows that the error does not always appear in every session. I can't find a reason why this happens in one session and not in the next

**Comment by nicogodet** [comment]
@3nids Is this line mandatory ?
https://github.com/qgis/QGIS/blob/d1ce6c0d8c17fabfe3361688cde4b4a144326b05/src/core/layout/qgslayoutitempicture.cpp#L355

Removing it solve the issue but I could miss something important

**Comment by 3nids** [comment]
@nicogodet good catch, yes, this fixes the issue.
You do the PR or want me to do it?

**Comment by nicogodet** [comment]
@3nids I would like to test a bit more.
It fixes the atlas related issue but I didn't test all other issues. Did you ?

**Comment by nicogodet** [comment]
@404-Geoscience It works fine even without my fixes on 3.26.1.
On windows, path should be with `/` (forward slash), not with `\` (backward slash).
