### ISSUE TITLE
Choosing CRS in Reproject makes QGIS freeze (Mac)

### ISSUE THREAD

**Issue by Kristianrev** [qgis/QGIS#49178]
### What is the bug or the crash?

On Mac:
When trying to select a target-CRS for an input layer to be reprojected, QGIS freezes and needs to be reopened.

### Steps to reproduce the issue

0. Find an Apple iMac 27" i7 (2020) with macOS Monterey 12.4 and QGIS 3.22.8 installed.
1. Open "Reproject Layer"
2. choose an input layer
3. in "Target CRS" click the "Globe"-button.
4. nothing happens and no more button is reacting.

### Versions

The current available LTR version of QGIS is 3.22.8. 
The latest available version of QGIS is 3.26.0. 
We are working on 3.27-Master. It will go into feature freeze on 2022-09-09 12:00:00 UTC and be released as 3.28 on 2022-10-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

<img width="449" alt="Skjermbilde 2022-06-28 kl  09 54 15" src="https://user-images.githubusercontent.com/103507781/176126815-f8c3b435-6852-4f63-8365-ece16d0176be.png">

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

macOS 12.4 (Monterey) on a iMac i7 (2020)

**Comment by nicogodet** [comment]
You didn't check "I tried with a new QGIS profile". Can you try with a new profile ?

**Comment by Kristianrev** [comment]
Ah, in a new profile it works. And now it's also working in the standard window.

P.S.: is QGIS-profile a trick to have multiple QGIS-projects open in Mac? So far I could only work with one project at a time and had to close when opening another project.
