### ISSUE TITLE
Label masks working in layout view but not in PDF plot

### ISSUE THREAD

**Issue by drewperkins** [qgis/QGIS#49174]
### What is the bug or the crash?

I'm trying to use layout masks on contour lines elevation values. When I look at the labels on my screen (both in the map window and layout window) the masks work as desired. When I plot the map as a PDF, the label masks go away.

Layout view
<img width="806" alt="Screen Shot 2022-06-27 at 5 14 32 PM" src="https://user-images.githubusercontent.com/12028954/176060379-d6bddf19-6c0f-4c61-a8f6-1e7afb940997.png">
w

PDF
<img width="879" alt="Screen Shot 2022-06-27 at 5 15 18 PM" src="https://user-images.githubusercontent.com/12028954/176060444-e218da7c-ec35-43e4-a129-64f51f8d3abb.png">

Here are layer settings
![Screen Shot 2022-06-27 at 5 20 49 PM](https://user-images.githubusercontent.com/12028954/176060939-0d42433c-b767-4364-99b6-1b8b6798ac99.png)

![Screen Shot 2022-06-27 at 5 25 19 PM](https://user-images.githubusercontent.com/12028954/176061298-53902118-48fd-49ef-a495-5a7c5af51bcf.png)

### Steps to reproduce the issue

This behavior has been consistent across several maps. I have at least one map that plots label masks correctly, but saving style settings from that layer and using them in another map doesn't make masks plot correctly. I've tried to figure out if there were any other settings that may be at play but couldn't not identify anything different.

If I make a new map, and only add the contours to it, and label it, it works as it is supposed to. There seems to be some setting that is overriding the masking in the PDF generation, but I have not been able to identify it. 

### Versions

QGIS version | 3.24.2-Tisler | QGIS code revision | 573ca40c96
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
lrs | 1.2.1
profiletool | 4.2.2
joinmultiplelines | Version 0.4.1
NNJoin | 3.1.3
qchainage | 3.0.1
qgis_resource_sharing | 0.16.0
LocatePoints | 0.3.4
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.24.2-Tisler
QGIS code revision
[573ca40c96](https://github.com/qgis/QGIS/commit/573ca40c96)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.4

Active Python plugins
lrs
1.2.1
profiletool
4.2.2
joinmultiplelines
Version 0.4.1
NNJoin
3.1.3
qchainage
3.0.1
qgis_resource_sharing
0.16.0
LocatePoints
0.3.4
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Please try on 3.26 -- numerous fixes were implemented for this functionality in that version

**Comment by drewperkins** [comment]
Updated to 3.26. Still having this issue. It is not consistent across all projects. Since upgrading I also get crashes pretty consistently when zooming/moving/resizing a map layout, but I will follow up with a separate report.

Made brand new layout
![image](https://user-images.githubusercontent.com/12028954/179311384-9dfecc00-ce08-49d3-88d2-393ed1efd0b2.png)
Layout view

<img width="1192" alt="image" src="https://user-images.githubusercontent.com/12028954/179311456-453e92bb-49b1-4ba5-a471-c278e6667482.png">
PDF

**Comment by alexbruy** [comment]
Works fine with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a)

**Comment by FeroEQ** [comment]
In 32.28.12 LTR still does not work properly.
We are awaiting solution.

**Comment by alexbruy** [comment]
Can you check latest dev build?

**Comment by drewperkins** [comment]
Just wanted to follow up and say I am still getting this issue even occasionally in brand new project/layouts. QGIS 3.34
Layout view: 
<img width="443" alt="image" src="https://github.com/qgis/QGIS/assets/12028954/a40fc2bb-d0b7-4bc1-9f15-3e881bd9d38a">
PDF:
<img width="680" alt="image" src="https://github.com/qgis/QGIS/assets/12028954/2590cb17-c259-41ce-b2e5-dedd8c585a1d">
