### ISSUE TITLE
Georrefenciador

### ISSUE THREAD

**Issue by CEAmorim** [qgis/QGIS#49173]
### What is the bug or the crash?

When placing an image for georeferencing in the georeferencing it only shows an indication of progress at 0% and does not perform the georeferencing.

### Steps to reproduce the issue

Next

### Versions

QGIS 3.22.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Next

**Comment by roya0045** [comment]
> Deactivate Semi Automatic Classification Plugin, restart QGIS and try again. Cheers

^this probably.

Next time you fill a report add you qgis info as requested.

**Comment by CEAmorim** [comment]
> Desative o Plugin de Classificação Semiautomática, reinicie o QGIS e tente novamente. Felicidades

Thank you, that was exactly it.
