### ISSUE TITLE
CSV source layer not available when openening saved QGIS project on Windows

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#49186]
### What is the bug or the crash?

CSV source layer not available when openening saved QGIS project.

![grafik](https://user-images.githubusercontent.com/20856381/176222573-0aee2c3e-f8d2-4200-8f41-e21ecd689937.png)

![grafik](https://user-images.githubusercontent.com/20856381/176222905-2575c070-6205-4050-8349-f45a7fc37ab6.png)

Before saving the project, both layers were available. 

The only difference between the two CSV files is the umlaut "ö" in the header field 
- Höhe (layer based on CSV not loading)
- Hoehe (layer based on CSV loading)

![grafik](https://user-images.githubusercontent.com/20856381/176223075-f9789db6-9c78-4e85-8b99-60734f883251.png)

So the issue might be related how source paramteter values are saved within or read from the QGIS project:.

### Steps to reproduce the issue

Download the sample project and data in the same folder and open the project:

[testdata_not_loading.txt](https://github.com/qgis/QGIS/files/9002601/testdata_not_loading.txt)
[testdata_loading.txt](https://github.com/qgis/QGIS/files/9002602/testdata_loading.txt)
[project.zip](https://github.com/qgis/QGIS/files/9002604/project.zip)

Both layers werde added to the project with the following settings:

![grafik](https://user-images.githubusercontent.com/20856381/176220743-2a09001e-1768-4413-b838-b35d8e6084c4.png)

![grafik](https://user-images.githubusercontent.com/20856381/176220451-195e6470-9701-4111-8f3b-73e8249b52c9.png)

### Versions

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I've got the impression that the issue happens sometimes only after saving the project with the added CSV layers several times.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc). Attached project opens without errors and both layers are available. I also tried to create new project using provided files and it also opens fine.

**Comment by pathmapper** [comment]
confirmed this is fixed
