### ISSUE TITLE
AttributeError: 'MapTitle' object has no attribute 'line2' 

### ISSUE THREAD

**Issue by anandita473** [qgis/QGIS#49192]
### What is the bug or the crash?

I am trying to visualize my hydrological swat model output using QGIS but it is crashing saying AttributeError: 'MapTitle' object has no attribute 'line2' and plugin option is not working.
please suggest

### Steps to reproduce the issue

![error in qgis](https://user-images.githubusercontent.com/102523549/176408922-2b9f9f59-896d-494b-9882-afb6717f7963.jpg)
![image](https://user-images.githubusercontent.com/102523549/176409425-866b5cb9-4ae0-41c4-9522-1673f619f0d1.png)
![error in qgis2](https://user-images.githubusercontent.com/102523549/176409509-6efbc640-c625-4c24-9f10-2132ab7a9ff6.jpg)

### Versions

QGIS version
3.22.5-Białowieża
QGIS code revision
c2723178
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
GeometryShapes
0.7
openlayers_plugin
2.0.0
QRectangleCreator
0.3
QSWATPlus3_9
2.2.4
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@anandita473 the error is generated by the QSWATPlus3_9 plugin.

**Comment by DelazJ** [comment]
And to complete @agiudiceandrea's comment, you should report the issue in that plugin repo. You will find url in its description from within the "Install/Manage Plugins" dialog in QGIS.
I'm closing as we can't do anything in this repo.
