### ISSUE TITLE
Removing processing script outputs can crash qgis

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#49197]
### What is the bug or the crash?

When using a script with some processing based on the existing template with more processing to do, removing the temporary output from the project will crash QGIS.

I cannot provide openly any script made that causes this, but the behaviour is consistent.

### Steps to reproduce the issue

1. Create a moderately complex processing script based on the template
2. Run the script to create a temporary layer.
3. Remove the layer from the project
4. Crash & no stack.

### Versions

3.27 based on Master on the 27-06-2022.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pathmapper** [comment]
You could try to add the following to your class based on `class ExampleProcessingAlgorithm(QgsProcessingAlgorithm)`:

````python
def flags(self):
    return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
````

ref https://github.com/qgis/QGIS/issues/44095#issuecomment-927122944, https://github.com/qgis/QGIS/issues/44095#issuecomment-927176819, https://gis.stackexchange.com/a/312884/

**Comment by alexbruy** [comment]
Never seen this behaviour with simple and very complex scripts. Might be something related to your code.

**Comment by alexbruy** [comment]
Is this still an issue? I have never been able to reproduce this with very complex scripts using native and 3rd party algorithms.

**Comment by roya0045** [comment]
> Is this still an issue? I have never been able to reproduce this with very complex scripts using native and 3rd party algorithms.

Might be windows or build specific, will close for now.
