### ISSUE TITLE
Processing script vector source UI initiation issue with filtered types

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#49196]
### What is the bug or the crash?

Very minor bug but can be annoying. When using a python processing script with a QgsProcessingParameterFeatureSource,  filtered by type, if the first choice has selected features, the option to use only selected feature is greyed out.

To enable the checkbox one need to switch to another layer and then go back to the first layer to have access to the checkbox.

### Steps to reproduce the issue

1. Use the qgis template script
2. Replace `[QgsProcessing.TypeVectorAnyGeometry]` by `[QgsProcessing.TypeVectorPoint]`
3. Select features from the source that should be listed up top
4. Run the script

### Versions

Tested with custom 3.27 master based on the main branch on 2020-06-27.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a).

**Comment by roya0045** [comment]
will close, assuming thi is solved
