### ISSUE TITLE
Stdev problem in the field calculator

### ISSUE THREAD

**Issue by mapemonde** [qgis/QGIS#49207]
### What is the bug or the crash?

In the field calculator of the attribute table, the "stdev" function doesn't seem to work.
**stdev("Depth",group_by:="id")** doesn't produce the same result as :
**sqrt( sum(("Depth"-mean("depth",group_by:="id"))^2,group_by:="id")/count("id",group_by:="id"))**

I don't want to waste your time (i am just learning how to use QGIS), and I hope i didn't miss something, but the second method give me the good standard deviation but not the first.
Just for the context : I'am working with grid (as a shapefile), there can be several depth values for a bin (so an entity), and i wanted to calculate the standard deviation on each bin. (it's for an hydrographic project)

### Steps to reproduce the issue

Use one of the file used in the project (you can find it attached in "jointure_file.zip".
Go to the attribute table of the layer and trie to create a new field with the Field Calculator
Then uses the stdev function, which doesn't to calculate the good standard deviation.
![stdev_function](https://user-images.githubusercontent.com/80745623/176694383-d29ad3a5-d4b2-48f6-894a-46200bf283c4.PNG)
![adapted_function](https://user-images.githubusercontent.com/80745623/176694390-de5bd5b7-2204-4058-baf9-3086ee757b95.PNG)
![entity_used](https://user-images.githubusercontent.com/80745623/176694392-b93d0473-458a-4074-a8e2-4c88ccf1f98b.PNG)
[jointure_file.zip](https://github.com/qgis/QGIS/files/9020323/jointure_file.zip)

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Just as a note, the stdev function uses `QgsAggregateCalculator::StDevSample` instead of `QgsAggregateCalculator::StDev`, this may explain the difference in results as both methods yield differing results. See https://github.com/qgis/QGIS/blob/3d4224d410c6e2248484543a8aba021ec5580050/tests/src/python/test_qgsaggregatecalculator.py#L86 as proof.

If you used the `aggregate` method/function with `stdev` as the aggregate type, does that work ok for you?

**Comment by agiudiceandrea** [comment]
@roya0045 @Pedro-Murteira it seems to me this is a valid bug. Isn't it?

**Comment by roya0045** [comment]
> @roya0045 @Pedro-Murteira it seems to me this is a valid bug. Isn't it?

I'd guess so, not sure why aggregate and stdev yield differing results, hard to guess if this was intentional or not.

**Comment by agiudiceandrea** [comment]
There are basically two different standard deviation: the **population standard deviation** and the **sample standard deviation**.

The expression `sqrt( sum(("Depth"-mean("depth",group_by:="id"))^2,group_by:="id")/count("id",group_by:="id"))` calculates the **population standard deviation**, while the `stdev` function calculates the **sample standard deviation**.
That explains the different results.

It looks like the documentation of the `stdev` function is incomplete / misleading: it should specify that it calculates the **sample standard deviation**.

Moreover, unfortunately there is also an inconsistency with the `aggregate` and `relation_aggregate` function where the 'stdev' aggregation method calculates the **population standard deviation** (while the `stdev` function calculates the **sample standard deviation**) and the 'stdevsample' aggregation method calculates the **sample standard deviation**.

@DelazJ @nyalldawson any thought about what would be the best way to fix those issues?
