### ISSUE TITLE
OSGeo4W Shell, GRASS GIS 7.8.7 dont start and there is not QGIS Desktop with Grass

### ISSUE THREAD

**Issue by Rubenturtle** [qgis/QGIS#49205]
### What is the bug or the crash?

After installing the 3.22.8 version of QGIS (msi installer). I cannot launch any of the plugins installed within. Also, in this version and the recent ones. We do have no QGIS desktop with GRASS. 

I tried to reinstall it several times but still, I get nothing.

I am working on a Windows 10 Pro OS with the version 21H2

Thank you in advance.

### Steps to reproduce the issue

To replicate the issue, I just downloaded and installed QGIS following the steps.
After that, when I click on the shortcuts that are created on the Desktop "QGIS 2.33.8" nothing happens. I also went to the source location, and still, I get nothing

### Versions

3.22.8

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Rubenturtle** [comment]
I used MSI installer. Oh, I see, then I should download one of the previous versions (if they still have "QGIS Desktop with Grass") Thanks!

**Comment by nicogodet** [comment]
Well not necessary. Current versions have GRASS.
The fact that nothing is working for you is a local issue (aka on your computer). Everything works fine on mine with latest MSI.

**Comment by Rubenturtle** [comment]
Okay, I think I found the result of both issues.
- Due to the absence of "QGIS Desktop with Grass", it has to be activated inside.
- OSGeo4W Shell is not working because the cmd is not working on my local machine. That is an issue I have to solve by myself

**Comment by brunopermo** [comment]
I have the same problem! I've tried to reinstall it in different versions (3.16.9, 3.22.13, 3.20.2, etc), but I didn't solve it.  I am working on a Windows 10 Pro OS with version 22H2 and installed QGIS all from msi installer.
I have another machine with Windows 7 running QGIS 3.16.9 and it works fine when I launch QGIS with GRASS.

**Comment by agiudiceandrea** [comment]
@brunopermo, try using  only ASCII chars in the layer file path and name.
