### ISSUE TITLE
Elevation profile based on individual Z values of a line vertices

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#49201]
### Feature description

The new Profil tool is very nice, but it doesn't allow something that I tought would be there from the start:
- ploting the elevation change of a line based on the Z values of its own vertices.

So for a line like `LineStringZ (0 0 0, 0 10 10)` I would have expected to be able to use the _Capture Curve From Feature_ button to click on the line and get a plot with a line starting at (0,0) and ending at (10,10) instead nothing at all. Maybe it's already possible, but I messed with all the parameters without being able to achieve that. I even tried to overlap a new feature (with the same geometry) and use the other line as an elevation reference but it didn't work either.

My use case here is to plot the elevation change of a LineStringZ representing a river or a road.

**Comment by huber-j** [comment]
+1 from me. When planning underground pipes it would be important to be able to plot the pipe along its path in relation to surrounding geology. Currently, the feature selected for the profile isn't plotted at all, only features crossing the profile line.

**Comment by SsaltyFiish** [comment]
@huber-j 
I got the same problem and need to figure it out. BTW I'm developing a GIS web for sewer.

**Comment by humberto77** [comment]
Following this as well.  Very similar, we input GPS tracks as LinestringZ and I'm surprised I can't find a way to plot this profile along it's captured self-curve.  Today I am trying to compare those elevations to DEM data from a raster.  I so far can't do this without exporting the data from QGIS and doing it elsewhere.

**Comment by humberto77** [comment]
> @humberto77 have you tested with qgis 3.32?

Sorry, I have not.  I am working on an LTR version, 3.28.7.

I'll add I can produce an effective elevation profile plot if I extract the vertices from the LinestringZ layer.

**Comment by jfbourdon** [comment]
I haven't seen that it has been added. Great!
For anyone getting here, in order to plot a profile based on the Z values of a linestring, you need to set the Elevation Clamping to "Absolute" and change the Profile Chart Appearance Interpretation to "Continuous Surface (e.g. Contours)"
