### ISSUE TITLE
Project doesn't recognize change in projection for previously added layer

### ISSUE THREAD

**Issue by marcp1999** [qgis/QGIS#49213]
### What is the bug or the crash?

When a layer is added to a project the projection information is retrieved and any necessary reprojection occurs. However once that layer has been added it is never checked again, so if the layer is reprojected somehow, in another project or another tool, it will be displayed incorrectly when the original project is reopened.

This seems like a really poor attempt at optimization. The extents of a layer are checked when it is opened but the projection is not. 

### Steps to reproduce the issue

[Aberdeen.zip](https://github.com/qgis/QGIS/files/9021721/Aberdeen.zip)

1. Create a new project and set the project CRS to EPSG:26913
2. Add the attached Aberdeen.gpkg raster file.
3. Observe the correct stats and CRS in the layer properties.
4. Save the layer as Aberdeen.gpkg to a different folder with a different CRS, say EPSG:4326. Don't add it to the project.
5. save the project and close
6. copy the reprojected gpkg over the original in the project directory
7. Reopen the project. The first thing you will notice is that the layer is no longer in view. 
8. Check the stats on the layer. It will show the extents as the Lat-Long extents and the CRS as EPSG:26913 which is incorrect.

This is a very artificial example but demonstrates the problem.

### Versions

QGIS version
3.22.2-Białowieża
QGIS code revision
1601ec46d0
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.0
PROJ version
8.2.0
EPSG Registry database version
v10.038 (2021-10-21)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
latlontools
3.6.4
quick_map_services
0.19.29
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
'duplicate' of #36878

**Comment by marcp1999** [comment]
On that previous example in 2020 someone decided that this is desirable behavior because there are instances where the user might want to override the projection info in the file.  I would suggest that unless someone DID override it, this is a bug. Dealing with projections is one of the most confusing and error prone parts of GIS, and this behavior makes it worse.

**Comment by alexbruy** [comment]
Duplicates #36878.
