### ISSUE TITLE
MDAL does not release (netcdf/mesh) file when layer unloaded from QGIS?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#49215]
### What is the bug or the crash?

Having a little python script here which creates an ugrid.nc I see that QGIS after loading a mesh (and then unloading it) keeps a file open apparently (checked with `lsof`).

### Steps to reproduce the issue

- Create a fresh netcdf
- Load it in QGIS
- Unload the layer (or new project)
- Try to write the netcdf again (no permission because QGIS still having it in it's claws)
- test with lsof <filename>

Tested it with a shp file, and then one is just released after the unloading of the layer.

### Versions

QGIS version | 3.27.0-Master | QGIS code revision | 415c545bae3
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

If needed I can provide a small test python script which actually writes the nc file

**Comment by vcloarec** [comment]
seems not fixed by https://github.com/lutraconsulting/MDAL/pull/423
