### ISSUE TITLE
Working with Custom Coordinate Reference Systems

### ISSUE THREAD

**Issue by MrBeee** [qgis/QGIS#49225]
### What is the bug or the crash?

In creating a custom CRS in QGIS Desktop 3.26.0, it appears **twice** in the CRS-list (accessible from Settings -> Custom Projections). This bug/feature did not happen with the earlier QGIS 2.20.0 version. 

To create a new custom CRS, I paste a WKT string in the Paramaters field, followed by checking the "Validate" button.
Then I close this dialog, and select the newly created CRS, using Project -> Properties -> CRS.

In the CRS tab, the WKT String is properly shown. In my example, it starts with 

**DERIVEDPROJCRS["Abtswoudseweg",
    BASEPROJCRS["Amersfoort / RD New",
        BASEGEOGCRS["Amersfoort",
            DATUM["Amersfoort",**

However, when I look at the same CRS in the list accessible from Settings -> Custom Projections, I see a WKT string that starts with : 

**DERIVEDPROJCRS["Abtswoudseweg",
    BASEPROJCRS["GDA94 / MGA zone 56",
        BASEGEOGCRS["GDA94",
            DATUM["Amersfoort",**

Please note that I have **other** custom CRS-es that start as follows:

**DERIVEDPROJCRS["Historic site grid",
    BASEPROJCRS["GDA94 / MGA zone 56",
        BASEGEOGCRS["GDA94",
            DATUM["Geocentric Datum of Australia 1994",**

 The reason for this, is that I started working with a custom CRS, based on [this example ](https://gis.stackexchange.com/questions/366578/custom-crs-for-historic-site-grid) on stack exchange

So it seems to me, that the parameter string shown in the **Custom CRS Dialog** gets 'messed up' with information from other entries. This appears not to be the case when you preview the WKT string from Project -> Properties -> CRS.

### Steps to reproduce the issue

Please use the following WKT string as an example

DERIVEDPROJCRS["Abtswoudseweg",
    BASEPROJCRS["Amersfoort / RD New",
        BASEGEOGCRS["Amersfoort",
            DATUM["Amersfoort",
                ELLIPSOID["Bessel 1841",6377397.155,299.1528128,
                    LENGTHUNIT["metre",1]]],
            PRIMEM["Greenwich",0,
                ANGLEUNIT["degree",0.0174532925199433]]],
        CONVERSION["RD New",
            METHOD["Oblique Stereographic",
                ID["EPSG",9809]],
            PARAMETER["Latitude of natural origin",52.1561605555556,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8801]],
            PARAMETER["Longitude of natural origin",5.38763888888889,
                ANGLEUNIT["degree",0.0174532925199433],
                ID["EPSG",8802]],
            PARAMETER["Scale factor at natural origin",0.9999079,
                SCALEUNIT["unity",1],
                ID["EPSG",8805]],
            PARAMETER["False easting",155000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8806]],
            PARAMETER["False northing",463000,
                LENGTHUNIT["metre",1],
                ID["EPSG",8807]]]],
    DERIVINGCONVERSION["Affine",
        METHOD["Affine parametric transformation",
            ID["EPSG",9624]],
        PARAMETER["A0",-257755.075549441,
            LENGTHUNIT["metre",1],
            ID["EPSG",8623]],
        PARAMETER["A1",0.914845326707141,
            SCALEUNIT["coefficient",1],
            ID["EPSG",8624]],
        PARAMETER["A2",0.403804443019272,
            SCALEUNIT["coefficient",1],
            ID["EPSG",8625]],
        PARAMETER["B0",-374175.442874562,
            LENGTHUNIT["metre",1],
            ID["EPSG",8639]],
        PARAMETER["B1",-0.403804443019272,
            SCALEUNIT["coefficient",1],
            ID["EPSG",8640]],
        PARAMETER["B2",0.914845326707141,
            SCALEUNIT["coefficient",1],
            ID["EPSG",8641]]],
    CS[Cartesian,2],
        AXIS["(E)",east,
            ORDER[1],
            LENGTHUNIT["metre",1]],
        AXIS["(N)",north,
            ORDER[2],
            LENGTHUNIT["metre",1]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["Netherlands - onshore, including Waddenzee, Dutch Wadden Islands and 12-mile offshore coastal zone."],
        BBOX[50.75,3.2,53.7,7.22]]]

### Versions

3.20 - 3.26

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Working on Windows 10

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a). here is what I did:
1. created a custom CRS using provided WKT string (Settings→Custom projections)
2. go to "Project → Properties → CRS" and make sure that WKT for newly created CRS matches the provided WKT
3. go to "Settings → Custom projections" and check WKT of the custom CRS. It is the same as provided and one from "Project → Properties → CRS"
