### ISSUE TITLE
CRS 6316 doesn't cover all area

### ISSUE THREAD

**Issue by bidrizi74** [qgis/QGIS#49224]
### What is the bug or the crash?

In QGIS 3.26 version, in list of Coordinate Reference Systems (CRS), CRS with code EPSG 6316 doesn't cover area of North Macedonia. With this, North Macedonian CRS based on EPSG 6316 parameters cannot be used in QGIS. 
This probably is because of two zones that cover EPSG 6316 (https://epsg.org/crs_6316/MGI-1901-Balkans-zone-7.html?sessionkey=z3r4rmfri7), one for other exYugoslavia countries (EPSG 1711) and second one for North Macedonia (EPSG 1148). This can be practicaly recogized if you add data in other CRS than WGS84 and if you use "Ask for datum transformation if several are available" option in "Settings/Options/Coordinate transformation and operations". In that case if you use EPSG 6316, all datum transformations will be available except datum transformation for North Macedonian territory which should be done by using EPSG 6206 as default datum transformation. 
This issue can be solved only in a case to give other-separate EPSG code for North Macedonia with the second extend (EPSG 1148, extend of national area) of EPSG 6316, or to define sub-code of EPSG 6316 for second extend 1148, that should be linked to 6206 as default datum transformation for this area. 

![image](https://user-images.githubusercontent.com/79769916/177005537-4ca1cbb5-b79d-4bc5-9071-c2d8282d5db8.png)

### Steps to reproduce the issue

Best way to reproduce this issue is to: 
To create sepparate CRS for North Macedonian area with second extend (EPSG 1148) of NMacedonian area, which will be used default datum transformation EPSG 6206 from MGI 1901 to WGS 84. 
Or, to define subcode of EPSG 6316 for the area of North Macedonia with extend 1148, which should be linked to EPSG 6206 for datum transformation. 

Example of projstring for North Macedonian area: 
+proj=tmerc +lat_0=0 +lon_0=21 +k=0.9999 +x_0=7500000 +y_0=0 +ellps=bessel +towgs84=521.748,229.489,590.921,4.029,4.488,-15.521,-9.78 +units=m +no_defs

In a case of any missunderstanding, please get in touch me via email bashkim.idrizi@yahoo.com any time. 

https://epsg.org/crs_6316/MGI-1901-Balkans-zone-7.html?sessionkey=z3r4rmfri7   

### Versions

QGIS V 3.26.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Also reported in OSGeo/PROJ repository https://github.com/OSGeo/PROJ/issues/3246.

**Comment by nyalldawson** [comment]
Closing as an upstream issue

**Comment by bidrizi74** [comment]
@nyalldawson Can you please give me feedback on this issue. 
In QGIS V 3.26.1 situation is same. There is no change in CRS for North Macedonia. 
Some additional details in order to give more clear view on this problem. 

In EPSG codes, CRS with EPSG 6316 (https://epsg.org/crs_6316/MGI-1901-Balkans-zone-7.html?sessionkey=poxbm3et26) has 2 extends, 1 (one) for 7th balkan zone (EPSG 1711 code for extend) and another for North Macedonia (EPSG 1148 code for zone extend). 
![image](https://user-images.githubusercontent.com/79769916/180670076-29b825d8-6f9f-49ac-8288-7fed9c55667a.png)

In QGIS 3.26.0 and 3.26.1 versions, when using EPSG 6316, software by default use first zone from EPSG registry database (7th balkan zone with EPSG 1711 code for extend), while second zone that belongs to North Macedonian area (EPSG 1148 code for zone extend) is totaly excluded from QGIS. 
![image](https://user-images.githubusercontent.com/79769916/180670301-5fada4c7-bffa-4235-8313-9eff893e3c66.png)

Main aim of separating zone of North Macedonia from general 7th balkan zone (EPSG 1711) is to establish sepparate CRS for North Macedonia, which later via Proj to be linked to default datum transformation parameters, in a same way as EPSG 6204 and 9945, sinse in North Macedonia official geospatial data are available in three CRS's (6316, 6204 and 9945). This is the reason why all three CRSs' should be defined correctly with all parameters. 
EPSG 6204 and 9945 and correctly defined and their ussage is perfect. Now problem with 6316 for North Macedonia have to be solved!  
![image](https://user-images.githubusercontent.com/79769916/180670445-c69079a1-de5c-450a-a245-960e1ef1ada4.png)

Best way to reproduce this issue is to create sepparate CRS for North Macedonian area with second extend (EPSG 1148) of EPSG 6316, which will be use default datum transformation EPSG 6206 from MGI 1901 to WGS 84, or to define subcode of EPSG 6316 for the area of North Macedonia with extend 1148, which should be linked to EPSG 6206 for datum transformation, as previously EPSG 6204 and EPSG 9945 are linked to EPSG 6206 for datum trasformation (Example of projstring: +proj=tmerc +lat_0=0 +lon_0=21 +k=0.9999 +x_0=7500000 +y_0=0 +ellps=bessel +towgs84=521.748,229.489,590.921,4.029,4.488,-15.521,-9.78 +units=m +no_defs). 

For any further questions, please don't hesitate to write me. 
Best regards, 
Bashkim.

**Comment by nyalldawson** [comment]
@bidrizi74 

You need to add your comments to https://github.com/OSGeo/PROJ/issues/3246 -- that's where this issue is tracked

**Comment by bidrizi74** [comment]
@nyalldawson Thanks!
