### ISSUE TITLE
QGIS 3.26 geopackage with styles problem 

### ISSUE THREAD

**Issue by karbokPL** [qgis/QGIS#49227]
### What is the bug or the crash?

Hello. I often use qgis 3.16.x but 3.26 has so many nice functions and features that i want to use. I've create a geopackage for optical fibre network but when I add it to project, qgis starts slowing down, layers randers very slow etc. even when there is no object in layers. My quess is problem with styles in my geopackage.
One more thing, when i unmark the whole group everything start runs like ferrari ;)
EPSG: 2177
[Projekt POPC 3.26 v1.zip](https://github.com/qgis/QGIS/files/9034413/Projekt.POPC.3.26.v1.zip)
 

### Steps to reproduce the issue

Add OpenStreetMap to new project, then load the geopackage. Turn on and off to see qgis speed

### Versions

3.26

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@karbokPL I'm not being able to reproduce it on QGIS 3.26. The geopackage loads onto QGIS without problems. Does it still occur with a new profile?

**Comment by karbokPL** [comment]
You can see it when you add OpenStreetMaps as a layer, then you can compare the speed turning on and off geopackage. 
I've updeted the "Steps to reproduce the issue" section with this discription.

**Comment by nyalldawson** [comment]
I can't reproduce. @Pedro-Murteira did you manage to reproduce?

**Comment by Pedro-Murteira** [comment]
> I can't reproduce. @Pedro-Murteira did you manage to reproduce?

I wasn't able to reproduce it too.

**Comment by nyalldawson** [comment]
@karbokPL can you provide additional steps to reproduce?
