### ISSUE TITLE
No list in combobox when they have filter expression, in "Modify the attributes of all Selected Features Simultaneously"

### ISSUE THREAD

**Issue by vidarusny** [qgis/QGIS#49238]
### What is the bug or the crash?

For data quality issues, the operation should be the same when modifying 1 or more elements. A field with a filter should only be able to be filled if the filter condition is ok. 

In my case the Combobox  should list value of "Child field", when "Mater field" have value. 
![image](https://user-images.githubusercontent.com/32432122/177167197-f7b8b756-cfa2-4552-ae5c-a80a3635fa6f.png)

But "Child Field" have no list.

### Steps to reproduce the issue

1. select multi object
2. click on ![image](https://user-images.githubusercontent.com/32432122/177169670-23222d00-f487-4445-86b1-7efb6d6b0ea5.png)
3. try to add value on "Master field" for example List 1
4. Try to list any value in "Child field"

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
flowTrace
1.1.1
french_locator_filter
1.0.2
LAStools
1.4
StreetView
3.2
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

The configuration of table test is : 
A "Master field" as integer. A value relation with A master_list is configure.
![image](https://user-images.githubusercontent.com/32432122/177168714-081cc176-859f-4157-9803-f3d0a65f82c7.png)
A "Child field" as integer. A value relation with A child_list is configure, and a filter expression on a master_id of Child_list table
![image](https://user-images.githubusercontent.com/32432122/177168686-3333715d-06d5-4ba2-a31f-f968a6744230.png)

Table Master_list
![image](https://user-images.githubusercontent.com/32432122/177168840-328aec2e-274c-4ecf-baa1-04101af943d7.png)
Table Child_list
![image](https://user-images.githubusercontent.com/32432122/177168926-0b6b1923-0259-4126-942f-b5143e2f118d.png)
[test_child_field.zip](https://github.com/qgis/QGIS/files/9039965/test_child_field.zip)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a).
