### ISSUE TITLE
Atlas much longer with QGIS 3.22 than with QGIS 3.16

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#49236]
### What is the bug or the crash?

When you create an atlas, for the same project, it's much longer in QGIS 3.22 than in QGIS 3.16 (x4).
You'll find attached a project than you can use to test.
Using this project, the times are:
1) With QGIS 3.16:
- creation of 1st page = 4 seconds
- creation of 2nd page = 3 seconds
- creation of 3rd page = 11 seconds
1) With QGIS 3.22:
- creation of 1st page = 16 seconds
- creation of 2nd page = 17 seconds
- creation of 3rd page = 41 seconds
[Uploading Pb Atlas QGIS 3-22.zip…]()

### Steps to reproduce the issue

Create and edit an atlas in QGIS 3.22
See my video attached

https://user-images.githubusercontent.com/55922863/177136621-73cfc2da-3773-4584-ad54-2de3d1f273ce.mp4

### Versions

Version de QGIS
3.22.8-Białowieża
Révision du code
8d5e9761df
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.0
Version de Proj
9.0.1
Version de la base de données du registre EPSG
v10.064 (2022-05-19)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.38.1
Version de PDAL
2.3.0
Version du client PostgreSQL
14.3
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Tested only with Windows 10

**Comment by roya0045** [comment]
Did you try with 3.26 to validate ?

**Comment by sigmoe** [comment]
@roya0045 Just tested with 3.26, and there's the same problem: 4 times more longer than with QGIS 3.16.

**Comment by sigmoe** [comment]
New test with QGIS 3.22.8 on MacOs: it's much faster than with QGIS 3.16 on Windows 10 !
Using the same project, the times with QGIS 3.22.8 on MacOS (v11.6.5)  are:
- creation of 1st page = 2 seconds
- creation of 2nd page = 2 seconds
- creation of 3rd page = 6 seconds

So no problem with QGIS 3.22.8 on MacOs.
The problem of slowness seems to be only on Windows ...

**Comment by nyalldawson** [comment]
It's possibly related to the geos version. Can you compare the version numbers from the about dialog on both systems?

**Comment by sigmoe** [comment]
@nyalldawson You're right. On MacOs, the GEOS version is 3.9.1-CAPI-1.14.2 whereas on Windows, the GEOS version is 3.10.3-CAPI-1.16.1
But also lots of other version differences. Here is the 'About QGIS' on MacOs:
Version de QGIS
3.22.8-Białowieża
Révision du code
2c33bc4c29
Version de Qt
5.14.2
Version de Python
3.8.7
Version de GDAL/OGR
3.2.1
Version de Proj
6.3.2
Version de la base de données du registre EPSG
v9.8.6 (2020-01-22)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.31.1
Version du client PostgreSQL
12.3
Version de SpatiaLite
4.3.0a
Version de QWT
6.1.4
Version de QScintilla2
2.11.4
Version de l'OS
macOS 11.6
Extensions Python actives
cadastre
1.12.1
GeofoncierEditeurRFU
2.1.4
SgmAggregAttMultiLyr
3.0.0
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

**Comment by nyalldawson** [comment]
Are you using any expressions involving intersections, or special clipping effects?

**Comment by sigmoe** [comment]
I'm using the automatic clipping of the map using the atlas object in the atlas map.

**Comment by nyalldawson** [comment]
Ok -- in that case it's definitely geos version related. The Mac os build and older windows release use a geos version which predates a major change in how geos handles intersections. There's nothing qgis can do to change this, any optimisation must be made in the geos library.

Feel free to open a ticket on the geos tracker and link to this ticket for details, but for now I'm closing this as an upstream issue.

**Comment by sigmoe** [comment]
@nyalldawson Ok, but in this case, isn't it possible to use GEOS 3.9.1 instead of GEOS 3.10.3 in QGIS 3.22.9 for Windows (like for MacOs) and keep the new GEOS version for the next LTR (3.28) ?
Because this slowness is very annoying.

**Comment by nyalldawson** [comment]
I can, but not till I'm back in front of a computer (I'm away and on mobile only)

**Comment by andreasneumann** [comment]
> I can, but not till I'm back in front of a computer (I'm away and on mobile only)

Enjoy your holiday!

**Comment by cesarcorreo** [comment]
It probably doesn't bring anything new to the table, but in my case, version 3.16 is much faster than any other version (3.26.1 right now)  and I have to use it frequently.
