### ISSUE TITLE
Layout crashing if another zoom or refresh is requested before its fully refreshed 3.26 Win 11

### ISSUE THREAD

**Issue by TonyShep** [qgis/QGIS#49231]
### What is the bug or the crash?

Layout crashes if:
Refresh or zoom button is pressed when in a layout before the blue progress bar has finished refreshing
OR
Same thing happens if the scroll wheel is used to zoom in and then zoomed again before a the blue status progress bar has finished indicating that a redraw or refresh has been completed.

So I assume the bug happens if the layout redraw has not fully completed before requesting another.

This did not happen prior to 3.26

### Steps to reproduce the issue

as above

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ImportPhotos
3.0.3
linz-data-importer
2.2.3
quick_map_services
0.19.29
splitmultipart
1.0.0
SplitPolygonShowingAreas
0.13
db_manager
0.1.20
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by TonyShep** [comment]
Python Stack Trace
Fatal Python error: Aborted

Current thread 0x00004b9c (most recent call first):

Windows fatal exception: access violation

Current thread 0x00004b9c (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by agiudiceandrea** [comment]
@TonyShep, have you really tried with a new QGIS profile?
Linked thread on qgis-user mailing list: https://lists.osgeo.org/pipermail/qgis-user/2022-July/051589.html.

**Comment by TonyShep** [comment]
Yes, clean profile was created.  I have done some more testing and in my case it appears that if a layer has Masked Symbol Labels enabled then zooming/refreshing/redrawing the layout crashes QGIS.  If I disable masked symbol layers on the layer it appears I can then zoom, refresh the layout window without having to wait for a full redraw to have completed.

**Comment by TonyShep** [comment]
I have tried with minimal plugins.  It looks like as long as the blue scroll bar at the bottom has not finished doing its refresh and the scroll wheel is turned OR a zoom button or refresh button is pressed on the toolbar then it crashes.  If the blue progress bar has finished then it does not crash.  
If all aerial imagery is removed then the refresh happens so fast that I cant really test properly. I have replicated this behavior with QMS plugin (google or esri imagery) and LINZ plugin (NZ base imagery) as they logically take tome to refresh in the layout window .
I have created clean profiles multiple times and reinstalled QGIS from the repository several times.
This is close to being unusable.
Hope this helps.
Cheers

**Comment by jmasselink** [comment]
The project with which I was previously encountering this issue has no apparent issues after upgrading to 3.26.1

**Comment by TonyShep** [comment]
This also appears to be the case for me after loading 3.26.1.  It looks like I can now successfully scroll or shift layout items while the blue progress bar is still moving without QGIS crashing.

 

Cheers

**Comment by TonyShep** [comment]
Yes you are correct. I've since tested with a clean profile and get exactly the same behaviour. I have added a comment re my latest test to my GitHub bug report. It appears it may be related to having masking on curved labels enabled. See notes in GitHub. CheersTony Shepherd  FarmMaps NZ  027 435 6193Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Andrea Giudiceandrea ***@***.***> Date: 5/07/22  9:23 pm  (GMT+12:00) To: qgis/QGIS ***@***.***> Cc: TonyShep ***@***.***>, Mention ***@***.***> Subject: Re: [qgis/QGIS] Layout crashing if another zoom or refresh is
  requested before its fully refreshed 3.26 Win 11 (Issue #49231) 
@TonyShep, I asked because I see various non core plugins installed in your profile (ImportPhotos, linz-data-importer, quick_map_services, splitmultipart, SplitPolygonShowingAreas): this means such profile is not a clean new one.

**Comment by agiudiceandrea** [comment]
It appears the issues no longer occurs with QGIS 3.26.1 or newer. Isn't it?

**Comment by TonyShep** [comment]
Correct

 

 

Cheers

Tony

 

Tony Shepherd  |  GeoSpatial / Mapping Manager

 

Ph 027 435 6193  |  E  ***@***.***> ***@***.***  |  W  <http://shepherdphotos.co.nz/> shepherdphotos.co.nz

 



 

 

 <https://www.wunderground.com/personal-weather-station/dashboard?ID=ISTLGORE2>
