### ISSUE TITLE
Raster as geopackage not shown in QGIS 3.26

### ISSUE THREAD

**Issue by 9ls1** [qgis/QGIS#49239]
### What is the bug or the crash?

I have not received any replies to https://lists.osgeo.org/pipermail/qgis-user/2022-June/051571.html about raster image saved as geopackage (created with the code found [here at QField](https://docs.qfield.org/reference/data-format/?h=raster#raster-data)) is displayed in QGIS 3.22 but not in QGIS 3.26, so I'm asking here as well to potentially reach out to other users/developers. 

Is there a new policy (e.g. I have to activate something) or is this a bug?

The image turns up in 3.22
![raster_as_gpkg](https://user-images.githubusercontent.com/10632163/177169558-18d8937d-33e6-45b7-a3e6-24eedfab374e.png)
![raster_shows_3 22](https://user-images.githubusercontent.com/10632163/177169560-6a6eff0d-4b94-4b92-b66c-774a0262a2f9.png)

but not in 3.26
![no_raster](https://user-images.githubusercontent.com/10632163/177169565-791dfbf5-eabb-48c0-b33f-3b03fc0eaf8d.png)

The images is shown in QField 2.1.4 as well.

### Steps to reproduce the issue

Extract the zip-file and open the geopackage-file in QGIS 3.26.
[saerheim_of.zip](https://github.com/qgis/QGIS/files/9040031/saerheim_of.zip)
 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
ClipMultipleLayers | 3.2.0
coordinator | 0.4
DataPlotly | 3.9
get_nib-main | 0.6
Go2NextFeature3 | 2.1
GroupStats | 2.2.5
ibamaprocessing | 1.6
InvisibleLayersAndGroups | 2.2
NavTable | 0.1.1
plugin_reloader | 0.9.1
qfieldsync | v4.1.1
Qgis2threejs | 2.7.1
qgis2web | 3.16.0
qgis_range_filters-master | 0.1
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
ClipMultipleLayers
3.2.0
coordinator
0.4
DataPlotly
3.9
get_nib-main
0.6
Go2NextFeature3
2.1
GroupStats
2.2.5
ibamaprocessing
1.6
InvisibleLayersAndGroups
2.2
NavTable
0.1.1
plugin_reloader
0.9.1
qfieldsync
v4.1.1
Qgis2threejs
2.7.1
qgis2web
3.16.0
qgis_range_filters-master
0.1
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I can't reproduce -- this works as expected for me

**Comment by agiudiceandrea** [comment]
I can confirm the issue on Windows 10 with both QGIS 3.26.0 and QGIS 3.22.8 (both using GDAL runtime 3.5.0) installed by the previous OSGeo4W Standalone Installer QGIS-OSGeo4W-3.26.0-3.msi and OSGeo4W-3.22.8-3.msi.

The issue doesn't occur with both QGIS 3.26.0 and QGIS 3.22.8 (both using GDAL runtime 3.5.1) installed by the OSGeo4W Network Installer and updated to the latest packages versions.

I guess the issue doesn't occur also with QGIS 3.26.0 and QGIS 3.22.8 installed by the newer OSGeo4W Standalone Installer QGIS-OSGeo4W-3.26.0-4.msi and OSGeo4W-3.22.8-4.msi.

**Comment by agiudiceandrea** [comment]
Issue confirmed as specific to the OSGeo4W build of GDAL.
With `gdalinfo saerheim_of.gpkg` from GDAL 3.5.0 shipped by OSGeo4W the following warning is displayed:
`Warning 1: Table saerheim_of contains WEBP tiles, but GDAL configured without WEBP support. Data will be missing`
With `gdalinfo saerheim_of.gpkg` from GDAL 3.5.1 shipped by OSGeo4W no warning is displayed.

**Comment by 9ls1** [comment]
Thanks for testing and confirming.

**Comment by rouault** [comment]
Issue should now been fixed per https://github.com/qgis/QGIS/issues/49366#issuecomment-1186429338
