### ISSUE TITLE
Latest and LTR releases out of date in msstore (winget) library

### ISSUE THREAD

**Issue by HedRat** [qgis/QGIS#49245]
### What is the bug or the crash?

winget qgis and winget qgis-ltr do not get the latest releases.

For example...
```
commandline>winget show qgis-ltr
Found **QGIS LTR** [OSGeo.QGIS_LTR]
Version: **3.16.16**
Publisher: QGIS Development Team
Publisher Url: https://www.osgeo.org/
Publisher Support Url: https://www.qgis.org/en/docs/index.html
Moniker: qgis-ltr
Description: QGIS is a user friendly Open Source Geographic Information System (GIS) licensed under the GNU General Public License. QGIS is an official project of the Open Source Geospatial Foundation (OSGeo). It runs on Linux, Unix, Mac OSX, Windows and Android and supports numerous vector, raster, and database formats and functionalities.
Homepage: https://qgis.org
License: GNU General Public License GPLv2
License Url: https://www.gnu.org/licenses/old-licenses/gpl-2.0.html
Installer:
  Type: nullsoft
  Locale: en-US
  Download Url: https://qgis.org/downloads/QGIS-OSGeo4W-3.16.16-1-Setup-x86_64.**exe**
  SHA256: 16306f23e969f6026e52305518a52dc241656ba217f01d797f081d0cc30da946
```

...is the results for the latest qgis-ltr. And this is not even the msi package. The results for 'qgis' come back with release 3.24.2 when 3.26 is the latest.

### Steps to reproduce the issue

winget show qgis
winget show qgis-ltr

### Versions

Expected: 3.22.8 (latest LTR)
Available: 3.16.16

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Maybe better to report this issue in the proper repository https://github.com/microsoft/winget-pkgs/issues.

**Comment by HedRat** [comment]
Thanks @agiudiceandrea - I have submitted a request for an update to QGIS_LTR.

**Comment by agiudiceandrea** [comment]
Fixed with https://github.com/microsoft/winget-pkgs/pull/65172.
