### ISSUE TITLE
uuid generator trims uuid-string when field length is set to 38

### ISSUE THREAD

**Issue by lindacamathias** [qgis/QGIS#49240]
### What is the bug or the crash?

uuid generator creates uuid in another format than what default value uuid() does when field length is set to 38 . (38 is enough for the whole string to fit in)

When a field length is set to 38, the generated UUID entry differs from what is generated with default value uuid()  -> see screenshot 
![image](https://user-images.githubusercontent.com/77726342/177189953-39118216-a40f-4c10-a252-321f5be7ff9c.png)

expected  (length is 38):                                {87930f61-81a3-47cf-ae0a-c0be4e7b74ef}   
what uuid generator actually generates:      fc19fdec95c140babdc2534be110682f}         

### Steps to reproduce the issue

1.  create a text field in a vector feature. set field length to 38
2.  go to attribute form and choose widget uuid generator for that field 
3. create a new feature

### Versions

3.22.8 and 3.26.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@lindacamathias it seems this behaviour is by design
https://github.com/qgis/QGIS/blob/2f3d6b9e5ddd64f002d6eef642ec798ad04df5d1/src/gui/editorwidgets/qgsuuidwidgetwrapper.cpp#L26-L37
I'll propose to only truncate the Uuid string if the field length < Uuid string length.

**Comment by lindacamathias** [comment]
i totally agree that it's basically a good idea to truncate it, but as you proposed @agiudiceandrea , it should only be truncated if the field is too short for the whole string, thus if the field length is < 38

**Comment by kannes** [comment]
Trimming almost arbitrary parts of the UUID feels super icky to me. I'd expect the string simply being truncated at the end, not missing a leading `{` or the `-` dashes inside.
