### ISSUE TITLE
Crash on Identify Tool click on vector

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#49248]
## User Feedback

I clicked the identify tool and then clicked on a vector feature on the map, then QGIS ended unexpectedly.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000008b8 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Opened a QGIS project with many layers, leaving 1 or more vector visible on the map canvas.  Activated Identify Tool with identify results mode set to "Top Down, Stop at First" or "Current Layer". Then clicked clicked on a vector layer.  Then QGIS quits unexpectedly.  

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
coordinates_converter | 1.0
LandXml | 2.3
latlontools | 3.6.3
MagneticDeclination | 2.3.1
profiletool | 4.2.2
QCopycanvas | 0.5
qgis2web | 3.16.0
qgis_resource_sharing | 0.16.0
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
LandXml
2.3
latlontools
3.6.3
MagneticDeclination
2.3.1
profiletool
4.2.2
QCopycanvas
0.5
qgis2web
3.16.0
qgis_resource_sharing
0.16.0
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This bug happens even after closing and re-opening the project, or saving the project to a new QGZ file.

**Comment by roya0045** [comment]
Is the issue specific to a project or layer(s)?
