### ISSUE TITLE
Weird point legends in Layers panel when using "Meters at Scale" point sizes

### ISSUE THREAD

**Issue by HegerM** [qgis/QGIS#49249]
### What is the bug or the crash?

I am displaying point layers using graduated colour schemes, with the point sizes set to the "Meters at Scale" option. I've noticed that this leads to weird behaviour in the Layers panel. I'm attaching screenshots from a small test case. Setting the point size to 29 m leads to tiny dots in the legend; whereas at 30 m, they become ridiculously large. Note also how the "3000 m" symbols appear smaller than the "30 m" symbols.

![29m](https://user-images.githubusercontent.com/104789487/177417911-d5c67fdb-0b34-4373-8b1d-d6897fdc6b0f.png) ![30m](https://user-images.githubusercontent.com/104789487/177417903-c549c0eb-130b-48c0-926b-8ef22d0a384f.png) ![3000m](https://user-images.githubusercontent.com/104789487/177417919-f92c71e0-b143-4a68-a4d8-36252268c6b2.png)

### Steps to reproduce the issue

1. Create or load a point layer with some sample points and associated data values (in the above case, 3 points with values 1.0, 2.0, 3.0)
2. Under "Symbology", set display to "Graduated"
3. Configure symbol and set point size to "Meters at Scale".

### Versions

3.26.0-Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a).

**Comment by HegerM** [comment]
Yup, currently on 3.32.3 and this isn't an issue anymore. Seems it went away somewhere along the way.
