### ISSUE TITLE
QGIS 3.22.8-Białowieża crashes when closing the program

### ISSUE THREAD

**Issue by seateazen** [qgis/QGIS#49242]
## User Feedback

crash happens everytime I close QGIS.

## Report Details

**Crash ID**: [df7ab36d97299e20a77faa2780932f1ee15ee61c](https://github.com/qgis/QGIS/search?q=df7ab36d97299e20a77faa2780932f1ee15ee61c&type=Issues)

**Stack Trace**
<pre>
CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/76140648/177282810-c731fcdc-c4f7-4792-8a84-f69627db444e.png)

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
spatialanalysistoolbox
0.3
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It seems caused by pcraster
I suppose you used OSGeo4W installer, could you try to remove pcraster and try again ?

**Comment by seateazen** [comment]
yes, I used the OSGeo4W installer. I removed the PC raster tools plugin as suggested, but QGIS still crashed on closing. The crash doesn't seem to affect any of my saved projects, but it happens every time when I close QGIS; I'm worried that this might affect something in the long run. 

## User Feedback

removed PC raster tools but still crashed upon closing QGIS

## Report Details

**Crash ID**: [df7ab36d97299e20a77faa2780932f1ee15ee61c](https://github.com/qgis/QGIS/search?q=df7ab36d97299e20a77faa2780932f1ee15ee61c&type=Issues)


**Stack Trace**
<pre>
CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by nicogodet** [comment]
Not only the plugin but also the package in OSGeo4W Installer

**Comment by seateazen** [comment]
that actually stopped the crash upon exit. thanks!

**Comment by nyalldawson** [comment]
Upstream issue: https://github.com/pcraster/pcraster/issues/361
