### ISSUE TITLE
Issues while loading in-house plugin

### ISSUE THREAD

**Issue by coderodyhpc** [qgis/QGIS#49253]
### What is the bug or the crash?

While trying to load an in-house (under development) plugin placed in a Github repository, the system is producing the error:
```
Server response is 200 OK, but that doesn't contain plugin metadata. 
This is most likely caused by a proxy or a wrong repository URL. 
You can configure proxy setting in QGIS options.

```

### Steps to reproduce the issue

1. Go to Plugins menu
2. Click on 'Settings'
3. Click on 'Show also experimental plugins'
4. Scroll down to 'Plugin Repositories' and click on 'Add'
5. Fill Name (e.g. myplugin) and URL (e.g. https://github.com/myrepository/myplugin). Did not touch Parameters (showing ?qgis=3.25), Authentication (blank) or Enabled (checked mark).
6. Click OK
The screenshot shows the error:
![QGIS_error01](https://user-images.githubusercontent.com/79646720/177544691-f36f4f17-0ea3-4f33-a9e0-5a42ea50470c.jpg)

### Versions

QGIS version
3.25.0-Master
QGIS code revision
695b5bbe37
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PostgreSQL client version
12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I also tried rebooting QGIS after setting 'Use proxy for Web Access' in the network options and even clearing the cache, but the error persists.

**Comment by nicogodet** [comment]
You are trying to point to a GitHub repository ?!

**Comment by nicogodet** [comment]
Are you pointing to a "plugin.xml" or root url of your repo ?

**Comment by nicogodet** [comment]
Does this have ever worked by the past ?

It's not how it works.
Plugin repository should point to a XML document like https://plugins.qgis.org/plugins/plugins.xml?qgis=3.26
Plugins should be placed in $profile_directory/python/plugins

**Comment by nicogodet** [comment]
As you use GitHub for development, you should check for qgis-plugin-ci and use it in GitHub actions to generate the xml file and zip file automatically

**Comment by nicogodet** [comment]
At the end, not a QGIS issue.

**Comment by nicogodet** [comment]
For $profile_directory, in QGIS, Settings, User Profiles, Open Active Profile Folder

**Comment by alexbruy** [comment]
Not a bug.
