### ISSUE TITLE
Open MDB file in qgis like arcgis

### ISSUE THREAD

**Issue by Rubrirostris** [qgis/QGIS#49264]
### Feature description

How to open *.mdb file in qgis like arcgis.

I added environment variables like this, "set OGR_SKIP=ODBC 
set PGEO_DRIVER_TEMPLATE=DRIVER=Microsoft Access Driver (*.mdb, *.accdb);DBQ=%%s". it didn't work .

**Comment by nyalldawson** [comment]
Neither environment variable is required anymore. You just need to make sure the 64 bit jet odbc driver is installed (from https://www.microsoft.com/en-us/download/details.aspx?id=54920)
