### ISSUE TITLE
Line Extension not work if the project and layer CRS are not the same

### ISSUE THREAD

**Issue by Koyaani** [qgis/QGIS#49267]
### What is the bug or the crash?

The Line Extension tool (Advanced Digitizing) seems not to work when the project CRS and the layer CRS are not the same.

![line extension issue](https://user-images.githubusercontent.com/37629967/177727344-14b84b3c-2712-4bdf-aa87-197ac76c0e97.png)

### Steps to reproduce the issue

Add a layer with a CRS (eg EPSG:3950) different from the project one (eg EPSG:4326)
Activate the Line Extension tool in the Advanced Digitizing Dock
Try to use it.

### Versions

QGIS version: 3.26.0-Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
I think it would be safer if such tools were only available for layers with the same CRS of the project.

**Comment by Koyaani** [comment]
For this tool, I think it's the developer (me) who forgot a transformation somewhere. I don't think we fix regression by removing (or limiting) features but by adding tests. Unfortunately, integration tests for these tools are quite complex and long to write... :/
