### ISSUE TITLE
ZPolyLine Profile with new profile tool doesn't work

### ISSUE THREAD

**Issue by martial-chateauvieux** [qgis/QGIS#49279]
### What is the bug or the crash?

The Profile widget (new in 3.26).
When using a ZPolyLine to "Capture Curve for Feature", the ZPolyLine itself is not displayed on the profile.

### Steps to reproduce the issue

I am trying out the new QGIS 3.26 profile tool. I imported a SRTM DEM. I can create a ZPolyLine and use it to plot the Terrain Elevation of the SRTM layer under the line by:

   1. Ticking the SRTM Layer in the profile widget,
    2. Selecting the "Capture Curve from Feature" tool and selecting my ZPolyLine in the map. all good so far.

Now I want to add the ZPolyLine itself (The Z values of the ZPolyline are slightly higher that the corresponding SRTM values) to the profile. I would expect to just have to tick the ZPolyLine layer in the profile tool. But that doesn't display it.

### Versions

Linux 3.26
Linux build of today's master: 2f3d6b, so 3.27

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

The workaround is to extract the vertices from the ZPolyLine. Ticking the layer with the extracted vertices displays the profile of the vertices, and making it a "Surface" brings the line between the vertices. but there must be something easier right?
There is a question open for the topic: https://gis.stackexchange.com/q/435350?sem=2

**Comment by uclaros** [comment]
The profile displays linear features that intersect the captured curve as points on their intersections. Linear features that share a segment with the captured curve are not displayed.

**Comment by martial-chateauvieux** [comment]
So sharing a segment is not an intersection?
...
I understand this as a bug.
Also the "Capture feature" layer is in the list of things you can "Tick" to be displayed...

**Comment by uclaros** [comment]
I completely agree, I was just pointing the source of the issue

**Comment by nicogodet** [comment]
If you add a little buffer to profile line, does it help ?

> Also the "Capture feature" layer is in the list of things you can "Tick" to be displayed...
@martial-chateauvieux Can you create a separate feature request for this ?

**Comment by martial-chateauvieux** [comment]
> If you add a little buffer to profile line, does it help ? ![image](https://user-images.githubusercontent.com/39594821/189597269-248edf9e-7369-41ce-bd17-fb83d8c1b4d0.png)

No it doesn't.
Also cloning the line doesn't help. The clone doesn't intersect either.

**Comment by nicogodet** [comment]
Can you share a sample project ?

**Comment by martial-chateauvieux** [comment]
> Can you share a sample project ?

Give me a couple of hours. I'll give you something to reproduce...

**Comment by martial-chateauvieux** [comment]
![image](https://user-images.githubusercontent.com/108923302/189617561-da73522c-cc93-4d17-ae67-e25aa7d3f119.png)
[QGis-3DViewer-ZPolyline-Bug.zip](https://github.com/qgis/QGIS/files/9546592/QGis-3DViewer-ZPolyline-Bug.zip)

The project is using OSM as the background map and Mapzen terrain data. 
The ZPolyline I set to 600m altitude, the duplicated line at 700m. 

Now I also played with the "Capture curve". It also doesnt intersect with the curved parallel to the capture curve.

Tell me if you need more...

**Comment by nicogodet** [comment]
If profile line **intersects** ZPolyline --> OK
If profile line **equals** ZPolyline --> NOK

Similar issue:
If a PointZ is on profile line **segment** --> NOK
If a PointZ is on profile line **vertex** --> OK
