### ISSUE TITLE
Polygon fill corruption if entire shape isn't visible on the canvas

### ISSUE THREAD

**Issue by BryanWall** [qgis/QGIS#49292]
### What is the bug or the crash?

Zooming in causes filled polygons to render incorrectly. The fill color "spills" out into the wrong places. In my example, I have several transparent polygons representing different highlighted areas on a map. If I zoom out so the entire polygons can be seen, the display is fine. If I zoom in, at some zoom level the display breaks and every notch of zoom causes the display to change like a kaleidoscope. I have been using this project for a while and did not see this behavior in previous versions of QGIS. 

These were originally Shapefiles. I tried converting them to GeoJSON and KML and the behavior is the same. I also tried creating spatial indexed and have verified the CRS. I tried only having one polygon enabled at a time and the issue still happens, so it's not happening only with multiple adjacent polygons. 

The first screen shot below shows the polygons rendered correctly. The second is after zooming in 2 levels. Zooming causes the polygons to seem to fold and twist. I also attached a video. 

<img width="1118" alt="QGIS-Rendering-OK" src="https://user-images.githubusercontent.com/5903057/178071778-2e0a1daf-6a52-4553-8336-11eecd76da29.png">

<img width="1121" alt="QGIS-Rendering-Broken" src="https://user-images.githubusercontent.com/5903057/178071774-f42f1dfe-c24f-493b-9d08-2bfec8e10a36.png">

https://user-images.githubusercontent.com/5903057/178072706-aa9151f2-de1e-4854-8194-a5b626f5332b.mov

 

### Steps to reproduce the issue

Zoom in and out of project containing filled polygons. 

### Versions

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
ORStools | 1.5.2
OnlineRoutingMapper | 0.9
quick_map_services | 0.19.29
latlontools | 3.6.3
OSMDownloader | 1.0.3
qad | 3.0.4
nextgis_connect | 0.13.6
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.4

Active Python plugins
ORStools
1.5.2
OnlineRoutingMapper
0.9
quick_map_services
0.19.29
latlontools
3.6.3
OSMDownloader
1.0.3
qad
3.0.4
nextgis_connect
0.13.6
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Same as https://github.com/qgis/QGIS/issues/49157 ?

**Comment by nyalldawson** [comment]
Yes, this is a duplicate
