### ISSUE TITLE
fail to merge rasters on macOS

### ISSUE THREAD

**Issue by yukihuang0422** [qgis/QGIS#49296]
### What is the bug or the crash?

When I was trying to merge 3 rasters, the GDAL command output:
**Process gdal_merge.py failed to start. Either gdal_merge.py is missing, or you may have insufficient permissions to run the program.**

The whole log is:
Processing algorithm…
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['/Users/yuki_huang/Library/Application Support/QGIS/QGIS3/profiles/default/processing/outputs/merge_2.vrt','/Users/yuki_huang/Library/Application Support/QGIS/QGIS3/profiles/default/processing/outputs/merge_3.vrt','/Users/yuki_huang/Library/Application Support/QGIS/QGIS3/profiles/default/processing/outputs/merge.vrt'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
gdal_merge.py -ot Float32 -of GTiff -o /private/var/folders/6n/2l97lvf57ybb_y78ktcgt6b80000gn/T/processing_ehhETO/4a465f20eb5a4283892d2dfcdffad7d6/OUTPUT.tif --optfile /private/var/folders/6n/2l97lvf57ybb_y78ktcgt6b80000gn/T/processing_ehhETO/3cb209287d10442d8b99cec38e28794e/mergeInputFiles.txt
GDAL command output:
Process gdal_merge.py failed to start. Either gdal_merge.py is missing, or you may have insufficient permissions to run the program.
Execution failed after 0.08 seconds

Loading resulting layers
Algorithm 'Merge' finished

### Steps to reproduce the issue

1. Go to Toolbar
2. Click on Raster
3. Choose Miscellaneous -> Merge...
4. Choose rasters, then click run
5. See error

### Versions

QGIS version: 3.18.3-Zürich
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 7.2.1, January 1st, 2021

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.2.2 | Running against GDAL/OGR | 3.2.2
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
PostgreSQL Client Version | 12.5 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.6 | QScintilla2 Version | 2.11.6
Compiled against PROJ | 7.2.1 | Running against PROJ | Rel. 7.2.1, January 1st, 2021
OS Version | macOS 11.6
Active python plugins | SemiAutomaticClassificationPlugin; ee_plugin; pca4cd; processing; db_manager; MetaSearch

</body></html>QGIS version
3.18.3-Zürich
QGIS code branch
[Release 3.18](https://github.com/qgis/QGIS/tree/release-3_18)
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.2.2
Running against GDAL/OGR
3.2.2
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
PostgreSQL Client Version
12.5
SpatiaLite Version
5.0.1
QWT Version
6.1.6
QScintilla2 Version
2.11.6
Compiled against PROJ
7.2.1
Running against PROJ
Rel. 7.2.1, January 1st, 2021
OS Version
macOS 11.6
Active python plugins
SemiAutomaticClassificationPlugin; 
ee_plugin; 
pca4cd; 
processing; 
db_manager; 
MetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This is the screenshot of error.
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/93780466/178125568-f3e7489a-c7f3-441b-9272-a4af44b1678d.png">

**Comment by DelazJ** [comment]
> QGIS version: 3.18.3-Zürich

@yukihuang0422 can you please test on a more recent version (3.22/3.26)? 3.18 has reached its end of life and related issues are no longer treated.

**Comment by yukihuang0422** [comment]
Hi, I have change to 3.22. Now I have run into the following problem:
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/93780466/178141845-0c2af270-813f-4b65-9c17-cdb700c7c523.png">
I have tried method from #39801, but it doesn't work.

## Versions
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.22.8-Białowieża | QGIS code revision | 2c33bc4c29
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 11.6
  |   |   |  
Active Python plugins
ee_plugin | 0.0.4
pca4cd | 22.2.12
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
SemiAutomaticClassificationPlugin | 7.10.6

</body></html>QGIS version
3.22.8-Białowieża
QGIS code revision
[2c33bc4c29](https://github.com/qgis/QGIS/commit/2c33bc4c29)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 11.6




Active Python plugins
ee_plugin
0.0.4
pca4cd
22.2.12
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
SemiAutomaticClassificationPlugin
7.10.6

**Comment by agiudiceandrea** [comment]
See also https://github.com/qgis/QGIS-Mac-Packager/issues/151, https://github.com/qgis/QGIS/issues/48574, https://github.com/qgis/QGIS/issues/39801.

**Comment by gioman** [comment]
@DelazJ I think we can close this in favor of https://github.com/qgis/QGIS-Mac-Packager/issues/151 agree?
