### ISSUE TITLE
manually set selection colour does not persist

### ISSUE THREAD

**Issue by Werafa** [qgis/QGIS#49305]
### What is the bug or the crash?

Manually setting the colour of selected item to 100% transparency does not persist when selecting the next item

### Steps to reproduce the issue

open shapefile with data type = point
set marker to 'dot'
set simple marker fill color to 100% transparent
open atribute table
select item 
zoom to item (item is highlighted yellow)

open settings/options/canvas and set selection color = 100% transparent
check selected item - is no longer highlighted yellow

go to attribute table and select new item
zoom to item
item is highlighted yellow and 100% opaque
canvas setting still shows 100% transparent

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.4
planet_explorer
2.2.0
Qgis2threejs
2.7.1
qgis_gee_data_catalog
0.4.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
dissect_dissolve_overlaps
0.2
latlontools
3.6.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by andywicht** [comment]
The transparency for the selection color is also set in the project which can override the QGIS setting. Check out `Project > Properties > General > Selection color`

Maybe it helps

**Comment by alexbruy** [comment]
As pointed out by @andywicht, selection color also can be set in the project properties. If you change global settings, all new projects will inherit it.
