### ISSUE TITLE
QGIS 3.26.0: extract tiff from WMS 

### ISSUE THREAD

**Issue by LaMoee** [qgis/QGIS#49307]
### What is the bug or the crash?

I'm trying to extract a TIFF from a WMS-service based on a vectorlayer mask. The error documented below is appearing.

### Steps to reproduce the issue

GDAL-Befehlsausgaben:
ERROR 4: contextualWMSLegend=0&crs=EPSG:25832&dpiMode=7&featureCount=10&format=image/png&layers=web_light_grau&styles&url=https://sgx.geodatenzentrum.de/wms_topplus_open&http-header:referer=: No such file or directory 
ERROR 4: Failed to open source file contextualWMSLegend=0&crs=EPSG:25832&dpiMode=7&featureCount=10&format=image/png&layers=web_light_grau&styles&url=https://sgx.geodatenzentrum.de/wms_topplus_open&http-header:referer=
Prozeß lieferte Fehlercode 2
Execution completed in 0.15 seconds
Results:
{'OUTPUT': 'P:/Neuss '
'Mobilitätsentwicklungskonzept/GIS-Basisdaten-Neuss/erstellte '
'Layer/Neuss_Gebietskörperschaft_light_grau.tiff'}

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.26.0-Buenos Aires | QGIS-Codeversion | 0aece2818e
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.5.0
PROJ-Version | 9.0.1
EPSG-Registraturdatenbankversion | v10.064 (2022-05-19)
GEOS-Version | 3.10.3-CAPI-1.16.1
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
AutoLayoutTool | 1.1
HCMGIS | 21.8.28
layout_panel-main | 0.2
OnlineRoutingMapper | 0.9
ORStools | 1.5.2
qgis_resource_sharing | 0.16.0
QNEAT3 | 1.0.4
QuickOSM | 2.0.1
quick_map_services | 0.19.29
simplesvg | 3.0.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
CustomToolBar | 1.1

</body></html>QGIS-Version
3.26.0-Buenos Aires
QGIS-Codeversion
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.0
PROJ-Version
9.0.1
EPSG-Registraturdatenbankversion
v10.064 (2022-05-19)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
AutoLayoutTool
1.1
HCMGIS
21.8.28
layout_panel-main
0.2
OnlineRoutingMapper
0.9
ORStools
1.5.2
qgis_resource_sharing
0.16.0
QNEAT3
1.0.4
QuickOSM
2.0.1
quick_map_services
0.19.29
simplesvg
3.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
CustomToolBar
1.1

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@LaMoee Can you try to reproduce with a new profile?

**Comment by LaMoee** [comment]
Already tried with a new profil, didnt work. But I found a work aroung. I just used the export tool to generate a TIFF. With that TIFF the extract by mask tool worked.

**Comment by agiudiceandrea** [comment]
This issue was already reported multiple times: see e.g. https://github.com/qgis/QGIS/issues/48775, https://github.com/qgis/QGIS/issues/48710, https://github.com/qgis/QGIS/issues/15322, ...
See the comment at https://github.com/qgis/QGIS/issues/48710#issuecomment-1136767644.
