### ISSUE TITLE
[Regression] single_sided_buffer creates a closed polygon

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#49310]
### What is the bug or the crash?

Hi, the behavior of the single_sided_buffer function has changed between 3.24 and 3.26/nightly : instead of creating a one-sided buffer along a line, it draw a closed polygon by creating a segment between the first and last vertex. The processing tool shows the same behavior.

![single_sided_buffer](https://user-images.githubusercontent.com/736212/178235270-4e5d6c31-62b9-4c7d-b39e-a5364a6bde31.jpeg)
x

### Steps to reproduce the issue

1. create a line
2. use 
  a.  processing **Single sided buffer** tool
  b. **Single sided buffer** expression in a geometry generator

### Versions

Works on 3.24.2
Doesn't work on 3.26.0 [d4ccf669](https://github.com/qgis/QGIS/commit/d4ccf669) and above

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@Jean-Roc Can you still reproduce it on a new profile?

**Comment by Jean-Roc** [comment]
@Pedro-Murteira yes, I updated the initial message

**Comment by alexbruy** [comment]
@Pedro-Murteira this is not related to Processing, it is a regression in the expression function.

**Comment by alexbruy** [comment]
This is what I get with the native Processing tool using master.
![img](https://user-images.githubusercontent.com/776954/178269921-a9632297-272f-4fdd-96a4-0d24a8441b75.jpg)

Anyway it is still not a Processing issue. Processing just uses the same geometry classes as the rest of QGIS, nothing specific is done at the algorithm side.

**Comment by agiudiceandrea** [comment]
I cannot reproduce the reported behavior on Windows with QGIS 3.26.1.
@Jean-Roc, could you please attach a sample layer and the exact configurations and steps to reproduce the issue?

**Comment by Jean-Roc** [comment]
Hi @agiudiceandrea, thank for your feedback, I tried again on QGIS 3.24 and 3.26.1 and 3.27 (qgis-rel and qgis-dev from osgeo4w) by creating a new linestring layer, a new object and a polygon geometry generator using this expression `single_sided_buffer($geometry, 1). And it worked.

So I went back to the previous test sample from our dataset and was able to reproduce the regression, the difference between the two attempts is that our geometry are LineStringZ while the new one was LineString.
`
Here a gpkg containing two layers with default styles applied :
[single_side_buffer.zip](https://github.com/qgis/QGIS/files/9218027/single_side_buffer.zip)

**Comment by agiudiceandrea** [comment]
I can confirm the issue occurs with QGIS 3.26.0, 3.26.1and the latest 3.27.0-Master f5487ecc6f from OSGeo4W when the input layer is a LineStringZ or MultiLineStringZ or LineStringZM or MultiLineStringZM.
The issue doesn't occur with QGIS 3.22.9, QGIS 3.24.2 and previous versions.

**Comment by Jean-Roc** [comment]
I retried the single sided buffer from processing in 3.26.1 with the linestringZ and got the same wrong output than with the expression, I do not have screen video capture on this computer but I'll give it a try this weekend on mine.

**Comment by agiudiceandrea** [comment]
@Jean-Roc anyway it seems to me this is not exactly an issue of the "Single sided buffer" processing algorithm, nor in the underlying functions QgsGeometry::singleSidedBuffer and QgsGeos::singleSidedBuffer. I don't see any relevant change in the code of such functionalities between 3.24/3.22 and 3.26.

It seems to me the output of the "Single sided buffer" processing algorithm in QGIS 3.26 and in QGIS 3.24/3.22 are the same, anyway it is correctly displayed in QGIS 3.24/3.22, while it is wrongly displayed in QGIS 3.26.

Could you please save the output of the algorithm from QGIS 3.24/3.22 and open it in QGIS 3.26 and vice versa? Is the output of the algorithm from QGIS 3.24/3.22 correctly displayed in QGIS 3.24/3.22 and wrongly displayed in QGIS 3.26? Is the output of the algorithm from QGIS 3.26 correctly displayed in QGIS 3.24/3.22 and wrongly displayed in QGIS 3.26?

**Comment by Jean-Roc** [comment]
I tried to follow the steps you pointed on 3.26.1, the processing output as a memory layer presents the same defect (green) but the same object when saved in a gpkg and loaded is normal (blue)

![single_sided_buffer_processing_diff](https://user-images.githubusercontent.com/736212/182160293-9aafcb8c-b09e-4e7e-a44d-282aabf9f799.jpeg)
