### ISSUE TITLE
Topological editing with avoid overlap creates vertices in different ways for new and edited features

### ISSUE THREAD

**Issue by komima** [qgis/QGIS#49312]
### What is the bug or the crash?

When topological editing and avoid overlap is enabled:

- drawing a new overlapping polygon on first layer creates vertices automatically on the second layer (overlap is clipped, second layer feature has new vertices created along the segment where features meet)
- editing a feature on the first layer by dragging an existing vertex over a feature on the second layer does not create vertices on the second layer (overlap is clipped, second layer feature has no vertex along the segment where features meet)
- editing a feature on the first layer with reshape tool to overlap a feature on the second layer does not create vertices on the second layer (overlap is clipped, second layer feature has no vertex along the segment where features meet)

### Steps to reproduce the issue

- Open [testing.zip](https://github.com/qgis/QGIS/files/9083119/testing.zip) project file (open from - geopackage)
- Enabled editing on both vector layers
- Digitize a new feature on first layer that overlaps the second layer feature, observe that overlap is clipped and topological vertices are created
  - ![image](https://user-images.githubusercontent.com/58747243/178238940-de88a7ca-aafa-4760-ba50-69e1e25fbc8c.png)
- Drag the midpoint of the segment on the northernmost feature with the vertex tool to overlap the second layer feature, observe that overlap is clipped but topological vertices are not created
  - ![image](https://user-images.githubusercontent.com/58747243/178238993-16795989-8bd1-4ec7-a732-10e902eaaeda.png)
- Reshape the southernmost feature to overlap the second layer feature, observe that overlap is clipped but topological vertices are not created
  - ![image](https://user-images.githubusercontent.com/58747243/178239029-1879eace-8ac4-464e-8161-6818c08fc14b.png)

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.0
Running against GDAL/OGR
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It is possible to use reshape tool with snapping on segment enabled, create a vertex on the reshape rubberband on the segment, and a topological vertex will be created when reshape is done, regardless whether geometry precision is enabled or not. For vertex tool edits this only works if no precision is set on the edited layer, see separate issue https://github.com/qgis/QGIS/issues/49311

**Comment by ismogis** [comment]
The PR #53632 fixes partly also this issue.

"Digitize a new feature on first layer that overlaps the second layer feature, observe that overlap is clipped and topological vertices are created"

- This is the wanted outcome. I tested it working also in #53632.

"Drag the midpoint of the segment on the northernmost feature with the vertex tool to overlap the second layer feature, observe that overlap is clipped but topological vertices are not created"

- This is fixed by #53632.

"Reshape the southernmost feature to overlap the second layer feature, observe that overlap is clipped but topological vertices are not created"

- This is not fixed by #53632. The topological vertices are not created.

**Comment by troopa81** [comment]
> "Reshape the southernmost feature to overlap the second layer feature, observe that overlap is clipped but topological vertices are not created"

 >   This is not fixed by https://github.com/qgis/QGIS/pull/53632. The topological vertices are not created.

Indeed, this is a different map tool (reshape map tool) so it's not the same code. Ideally, it would be best to have separate issues. The first 2 ones will be close with #53632 . The third one will need a separate PR
