### ISSUE TITLE
Extending a vertex on current edit layer interpolates non finite values and fails to save the shapefile

### ISSUE THREAD

**Issue by sharon92** [qgis/QGIS#49315]
### What is the bug or the crash?

While editing a shapefile, extending a vertex from the endpoints interpolate nan values in M values.
This results in failure to save the edits and in turn the file

### Steps to reproduce the issue

1. Start editing a Polyline layer
2. Enable Node editor
3. Go to a vertex in the endpoints of Polyline 
4. Click on + to start extending the Polyline
5. Toggle edit Mode and save
6. Fails to save

### Versions

QGIS-Version
3.26.0-Buenos Aires
QGIS-Codeversion
0aece2818e
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.0
PROJ-Version
9.0.1
EPSG-Registraturdatenbankversion
v10.064 (2022-05-19)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2004

Aktive Python-Erweiterungen
contour
2.0.10
crayfish
3.6.0
imodqgis
0.2.2
LAStools
1.4
pluginbuilder3
3.2.1
profiletool
4.2.2
qgis2web
3.16.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@sharon92 Can you still replicate this on a new profile?

**Comment by sharon92** [comment]
@Pedro-Murteira I just saved the new profile and started editing it again and now its also interpolating nan values!

**Comment by thbaumann** [comment]
Same happens sometimes also to the X- and Y-Values of vertices when using the extend (+)-option while working with the vertex tool. Geometries like these are getting created: 
```

MultiLineString ((nan nan, 399290.73371136630885303 5322361.46528119500726461, 399290.87993753829505295 5322361.43563245981931686, 399291.01740483951289207 5322361.37763347662985325, 399291.14067627640906721 5322361.29357817489653826, 399291.24487631861120462 5322361.18679103907197714, 399291.32588373159524053 5322361.06149563007056713, 399291.38049457711167634 5322360.92264752369374037, 399291.40654893172904849 5322360.77573832869529724, 399292.38913358090212569 5322347.34977189172059298, 399300.42585233907448128 5322347.46139298565685749))

MultiLineString ((399405.48494374030269682 5322204.06024124752730131, 399389.75373832177137956 5322202.37285614293068647, 399389.39508558338275179 5322202.32795385736972094, 399389.05380641244119033 5322202.3928582975640893, 399388.75045579968718812 5322202.5525833573192358, 399388.50559354241704568 5322202.79216245003044605, 399388.33977844886248931 5322203.0966291269287467, nan nan))
```

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master (4178ace22a4a79e31c4fff016e0c5b9e6413515a)

**Comment by sharon92** [comment]
@alexbruy as of 3.30 this is not an issue.
