### ISSUE TITLE
Georeferencer "Save GCP points" and "Load in project when done" without function using "create world file only"

### ISSUE THREAD

**Issue by mrtwister3142** [qgis/QGIS#49331]
### What is the bug or the crash?

In (raster) georeferencer, the options "Save GCP points" and "Load in project when done" do not work if the option "Create world file only" is checked.

### Steps to reproduce the issue

1. Try to georeference a raster image, set "Create world file only" and check "Save GCP points" and "Load in project when done".
2. Start georeferncing
3. Neither Layer is loaded in project nor GCP points are saved.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.5.0 | Running against GDAL/OGR | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
NavTable | 0.1.1
shlocator | v1.4
SpreadsheetLayers | 2.0.1
swiss_locator | 1.4.9
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.0
Running against GDAL/OGR
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
NavTable
0.1.1
shlocator
v1.4
SpreadsheetLayers
2.0.1
swiss_locator
1.4.9
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by mrtwister3142** [comment]
No changes with new profile...

**Comment by agiudiceandrea** [comment]
Confirmed with QGIS 3.26.0.
@Pedro-Murteira, the issue doesn't occur with QGIS 3.22.8 and previous versions, so it seems to me this is a regression.
