### ISSUE TITLE
No ProductCode of ProductVersion when deploying via Microsoft Intune

### ISSUE THREAD

**Issue by worangeb** [qgis/QGIS#49365]
### What is the bug or the crash?

When I want to deploy QGIS, 3.22 or 3.26, in Microsoft Intune/Endpoint Management, I receive the error:
"The selected app package does not appear to have either a ProductCode or ProductVersion.".
Is it possible to give a code or version within the msi installer?

### Steps to reproduce the issue

In Endpoint Management, go to Apps, Add App, Line-of-Business app, then Select App package file.

### Versions

3.22 or 3.26

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
It seems to me this is an issue specific to the OSGeo4W Standalone Installer and might be better to report it to the OSGeo4W issue tracking system at https://trac.osgeo.org/osgeo4w/.

This is a duplicate of https://github.com/qgis/QGIS/issues/45333.

**Comment by jef-n** [comment]
> This is a duplicate of #45333 (which should be reopened).

As far as I can tell both are there - at the comment in #45333 already states.

**Comment by Doev** [comment]
I found this issue cause I have the same problem. Any news?
