### ISSUE TITLE
Consistent crashes when panning/zooming map window in layout view in projects created in previous versions

### ISSUE THREAD

**Issue by drewperkins** [qgis/QGIS#49376]
### What is the bug or the crash?

Since upgrading to 3.26 I have been getting consistent crashes while panning/zooming the map in a layout view on a Mac when working in projects created in previous versions. Sometimes it happens right away, sometimes I can move around for a bit but eventually get a crash. No issues in the main window. 

I've made a brand new project as a test and cannot replicate the behavior.

Here is the report Mac OS gives me. I've gotten at least two different versions (I haven't looked at it closely each time) I can paste whole thing in if useful.

QGIS quit unexpectedly.

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QGIS [24518]
Path:                  /Applications/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis3
Version:               3.26.0 (3.26.0 ())
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-07-15 14:53:33.3586 -0700
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        0CDA6CAA-1396-B375-2AA2-DE260A34597E

Sleep/Wake UUID:       9466D5F6-B5B2-40F8-9ECD-A57ADE361BDF

Time Awake Since Boot: 26000 seconds
Time Since Wake:       8555 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000cfe3984c47b8 -> 0x00004fe3984c47b8 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x0000cfe3984c47b8
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0x4fe3984c47b8 is not in any region.  Bytes after previous region: 15788984248249  Bytes before following region: 17714184960072
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      JS JIT generated code    41876f801000-41876f802000 [    4K] ---/rwx SM=NUL  
--->  GAP OF 0x1e78907fe000 BYTES
      MALLOC_NANO              600000000000-600008000000 [128.0M] rw-/rwx SM=PRV  

Kernel Triage:
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage
VM - pmap_enter failed with resource shortage

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff897b92940 ???
1   libsystem_kernel.dylib        	    0x7ff8075e300e __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff8076191ff pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff8075272d8 raise + 26
4   libsystem_platform.dylib      	    0x7ff80762edfd _sigtramp + 29
5   ???                           	       0x155b6a370 ???
6   ???                           	    0x600001b36d30 ???
.......
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QGIS [22136]
Path:                  /Applications/QGIS.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis3
Version:               3.26.0 (3.26.0 ())
Code Type:             X86-64 (Translated)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2022-07-15 14:25:24.5545 -0700
OS Version:            macOS 12.4 (21F79)
Report Version:        12
Anonymous UUID:        0CDA6CAA-1396-B375-2AA2-DE260A34597E

Sleep/Wake UUID:       9466D5F6-B5B2-40F8-9ECD-A57ADE361BDF

Time Awake Since Boot: 24000 seconds
Time Since Wake:       6866 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x500007fcaa44e469 -> 0x000007fcaa44e469 (possible pointer authentication failure)
Exception Codes:       0x0000000000000001, 0x500007fcaa44e469
Exception Note:        EXC_CORPSE_NOTIFY

VM Region Info: 0x7fcaa44e469 is not in any region.  Bytes after previous region: 8300733457514  Bytes before following region: 71274463959959
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      commpage (reserved)        1000000000-7000000000   [384.0G] ---/--- SM=NUL  ...(unallocated)
--->  GAP OF 0x485f8b600000 BYTES
      JS JIT generated code    48cf8b600000-48cf8b601000 [    4K] ---/rwx SM=NUL  

Kernel Triage:
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get
VM - Compressor failed a blocking pager_get

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   ???                           	    0x7ff897b92940 ???
1   libsystem_kernel.dylib        	    0x7ff8075e300e __pthread_kill + 10
2   libsystem_pthread.dylib       	    0x7ff8076191ff pthread_kill + 263
3   libsystem_c.dylib             	    0x7ff8075272d8 raise + 26
4   libsystem_platform.dylib      	    0x7ff80762edfd _sigtramp + 29
5   ???                           	       0x15c41e4f0 ???
6   ???                           	       0x1089ef080 ???
..........

### Steps to reproduce the issue

https://user-images.githubusercontent.com/12028954/179316664-5f927110-edca-4f25-9832-454378d52f65.mov

### Versions

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.4
  |   |   |  
Active Python plugins
lrs | 1.2.1
profiletool | 4.2.2
joinmultiplelines | Version 0.4.1
NNJoin | 3.1.3
qchainage | 3.0.1
qgis_resource_sharing | 0.16.0
LocatePoints | 0.3.4
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.4

Active Python plugins
lrs
1.2.1
profiletool
4.2.2
joinmultiplelines
Version 0.4.1
NNJoin
3.1.3
qchainage
3.0.1
qgis_resource_sharing
0.16.0
LocatePoints
0.3.4
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This should be fixed in 3.26.1 -- please reopen if not.
