### ISSUE TITLE
Graphical Modeler - Create a layer group and store result inside

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#49370]
### Feature description

Sometimes when using the graphical modeler I generate multiple files. It would really help if we could have the possibility to specify the possibility to store all the results inside a layer group instead of being simply added to the QGIS interface.

For example, in the model properties we could have a text box and if this text box as a value (the new layer group name), QGIS will create the layer group and store all result inside.

**Comment by mercerraa** [comment]
This is not passed on the the Python code.
