### ISSUE TITLE
CP949(Korean) and other encodings missing in [Export Project to DXF menu]

### ISSUE THREAD

**Issue by endofcap** [qgis/QGIS#49378]
### What is the bug or the crash?

CP949(Korean) and other several encodings are missing in [Export Project to DXF menu] 

This issue already has been discussed [here](https://github.com/qgis/QGIS/issues/44756) and has not been clearly fixed. According to the aforementioned discussion, this issues seemed to be related to the Qt library shipped with the new (v2/msi) OSGeo4W installers not old (v1/exe) one. Since then Korean users are recommended to install QGIS using the old (v1/exe) OSGeo4W to avoid this issue. 

However old (v1/exe) OSGeo4W installers are now deprecated and there's no way to get the proper encoding codec except editing qgis_core.dll directly using hex editor as guided [here](https://lists.osgeo.org/pipermail/qgis-user/2021-November/050126.html) 

It's not the genetic solution and I hope the issue get fixed just like before. 

### Steps to reproduce the issue

Go to [Project[ -> [Import/Export] -> [Export Project to DXF] -> [Encoding] and you'll see only 13 codecs like below. 

['ISO-8859-1', 'ISO-8859-2', 'ISO-8859-3', 'ISO-8859-4', 'ISO-8859-5', 'ISO-8859-6', 'ISO-8859-7', 'ISO-8859-8', 'ISO-8859-9', 'Shift_JIS', 'Big5', 'CP936', 'GB2312']

However that menu usually lists 28 codecs including CP945 and others like below. 

['ISO-8859-1', 'Big5', 'CP950', 'CP949', 'Shift_JIS', 'GB2312', 'CP936', 'MacRoman', 'CP1258', 'CP1257', 'CP1256', 'CP1255', 'CP1254', 'CP1253', 'CP1252', 'CP1251', 'CP1250', 'CP866', 'CP874', 'CP850', 'ISO-8859-9', 'ISO-8859-8', 'ISO-8859-7', 'ISO-8859-6', 'ISO-8859-5', 'ISO-8859-4', 'ISO-8859-3', 'ISO-8859-2']

### Versions

QGIS 3.20. and all the higher versions that shipped with the new (v2/msi) OSGeo4W installers.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Why create a new ticket while you mention the exact same issue ?

The previous ticket is still open so not fixed yet. No need to create a new.

**Comment by endofcap** [comment]
Sorry for that. I was confused #44756 was closed.

**Comment by alexbruy** [comment]
Duplicates #44756
