### ISSUE TITLE
WFS3 collections field name/displayName mix in request/response

### ISSUE THREAD

**Issue by domi4484** [qgis/QGIS#49399]
### What is the bug or the crash?

In WFS3 collections request field names (no alias) are required as property names.
But in the response displayNames are used.

I do not know what makes more sense for the API, alias or normal name, but it should remain consistent in request/response.

Maybe the request could accept both and return `name()` or `displayName()` depending on what was requested.

![image](https://user-images.githubusercontent.com/9881900/179489501-1232ffbd-8762-4dbc-9741-492d23c69d2f.png)

### Steps to reproduce the issue

1. Prepare and serve a project with some alias defined.
2. Send a collections request using aliases 
3. You get a Bad request error:  "Argument 'properties' is not valid. Comma separated list of feature property names to be added to the result. Valid values: %1".
4. Send a collections request using field names.
5. You get an answer that use aliases as properties.

### Versions

Development

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@domi4484 this report is about QGIS server, right?

**Comment by domi4484** [comment]
@gioman yes

**Comment by elpaso** [comment]
I think it's best to accept both versions as input but always output display name.
