### ISSUE TITLE
Crash on saving shapefile points

### ISSUE THREAD

**Issue by markseaman** [qgis/QGIS#49400]
## User Feedback

Trying to move shapefile points and save result

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002c4c (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. Go to vertex
2. Move points
3. Close vertex
4. Press save
5. Crashes

### Versions

3.26.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@markseaman Can you still reproduce the crash on a new profile?

**Comment by markseaman** [comment]
No, it now seems to be working OK and I have been able to move points around without a problem. When it crashed the first time it did actually save the points in their new position.

**Comment by Pedro-Murteira** [comment]
@markseaman Since it seems to be resolved, we can close for now. We can always reopen if needed.
