### ISSUE TITLE
WFS/QgsOapifProvider does not take the pageSize from the dialog into account

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#49404]
### What is the bug or the crash?

Having a simple table in Postgres here (around 300 features), with pf_featureserv in front of it to serve "OGC API - Features", I never received more then 100 features.
Same with the public pygeoapi demo server: url='https://demo.pygeoapi.io/master/' requesting the 'dutch_windmills' layer...

Trying to debug it looks like QGIS always ends up here:
https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgsoapifprovider.cpp#L134

while in my connection dialog I instructed it to have a page size and a max size:

![gnome-shell-screenshot-h73g97](https://user-images.githubusercontent.com/731673/179538484-daf238ab-ba51-4cfa-b90d-d53a3e7f2659.png)

It looks like the page size is not ending up in the provider uri?

### Steps to reproduce the issue

See above

### Versions

QGIS version | 3.27.0-Master | QGIS code revision | 6fd8f424a2c
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
pdokservicesplugin | 4.0.0
db_manager | 0.1.20
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.27.0-Master
QGIS code revision
[6fd8f424a2c](https://github.com/qgis/QGIS/commit/6fd8f424a2c)
Qt version
5.15.4
Python version
3.10.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.39.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux bookworm/sid

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rduivenvoorde** [comment]
Ok, did some futher experimenting using pyqgis:

```
# defaults, just like the GUI uses an url with a fixed limit=100 like: http://localhost:9000/collections/public.gemeenten/items?limit=100
qgis.utils.iface.addVectorLayer(
"typename='public.gemeenten' url='http://localhost:9000/'",
"WFSexample",
"OAPIF")

# getting/using some WFS constants from https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsconstants.cpp

# using pagingEnabled=1 ALL items are requested in one go
qgis.utils.iface.addVectorLayer(
"pagingEnabled='1' typename='public.gemeenten' url='http://localhost:9000/'",
"WFSexample",
"OAPIF")

# using maxNumFeatures=10 requests 10 items via http://localhost:9000/collections/public.gemeenten/items?limit=10
qgis.utils.iface.addVectorLayer(
"maxNumFeatures='10' typename='public.gemeenten' url='http://localhost:9000/'",
"WFSexample",
"OAPIF")

# "pageSize='50' requests just 50 items via http://localhost:9000/collections/public.gemeenten/items?limit=50
qgis.utils.iface.addVectorLayer(
"pageSize='50' typename='public.gemeenten' url='http://localhost:9000/'",
"WFSexample",
"OAPIF")

# setting both a pageSize and pagingEnabled, seems to requests ALL in one go again: http://localhost:9000/collections/public.gemeenten/items
qgis.utils.iface.addVectorLayer(
"pageSize='50' pagingEnabled='1' typename='public.gemeenten' url='http://localhost:9000/'",
"WFSexample",
"OAPIF")

```

Is should OAPIF provider be able to do paging?

Or is it using some (hidden) cache to determine itself if it should request more 'pages' or not?

**Comment by rduivenvoorde** [comment]
More info: OAPIF IS PAGING! Using the following PUBLIC pygeoapi service you can try:

```
# this one is the one picked from the UI, WORKS:
qgis.utils.iface.addVectorLayer(
"restrictToRequestBBOX='1' typename='dutch_windmills' url='https://demo.pygeoapi.io/master/'",
"WFSexample",
"OAPIF")

# this one also works, fetching sets of 50 features at a time, ONLY for the bbox:
qgis.utils.iface.addVectorLayer(
"restrictToRequestBBOX='1' pageSize='50' typename='dutch_windmills' url='https://demo.pygeoapi.io/master/'",
"WFSexample",
"OAPIF")

# THIS also works: ALL features (ignoring the bbox) all retrieved in sets of 50...
qgis.utils.iface.addVectorLayer(
"restrictToRequestBBOX='0' pageSize='50' typename='dutch_windmills' url='https://demo.pygeoapi.io/master/'",
"WFSexample",
"OAPIF")
```

**Comment by rduivenvoorde** [comment]
Ok, tried do some tests and debugging (using the public 'https://demo.pygeoapi.io/master/'-service, around 1800 features), some conclusions (please correct me if I am wrong):

- while using the pyqgis interface, the pageSize is taken into account (and thus working to retrieve all items within given boundingbox), when using QGIS itself, it seems that the pageSize is ALWAYS reset/cleared: 
https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsnewconnection.cpp#L88

- it looks like when you use the wfs provider dialogs, as if the pageSize is forgotten the moment you start requesting a layer. 
=> should the pageSize='xx' not have been added to the base uri here:
https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgswfsdatasourceuri.cpp#L107
(at that moment the uri only holds the host uri and the version type...)

- the oapif provider seems not to cache/hold id's, like other WFS versions? When I zoom in and out from the dutch_windmills collection above, it keeps requesting all points (like: starting from zero, paging to the last item)
Is that deliberate?

- in https://github.com/qgis/QGIS/blob/master/src/providers/wfs/qgsoapifapirequest.h#L46-L50 there is both a maxLimit and a defaultLimit both stating: "... number of features that are requested at once (-1 if unknown)"
It is not clear (to me) which one will be mapped to 'pageSize' in case of paging, and which one will be the actual maxFeaturesRequested possible

It's just not clear to me where to 'keep' (or move into the uri) the pageSize param from the connection page, so the requests will have it and the provider starts paging. I have commented out some places with `wfsPageSizeLineEdit()->clear()` but that did not help...

OR is it deliberately? Should an OAPIF never be requested paging if it is not mentioning one of the maxLimit or defaultLimit parameters in its capabilities?

Which brings me to the big WFS question: how is a server keeping clients (like QGIS) away from always paging the full dataset (serveral times) from the server?

The combi of maxLimit and restrictToRequestBBOX?

- if restrictToRequestBBOX is NOT given you can only request the maxLimite
else?
- you can start paging within the restrictToRequestBBOX
BUT you can set it to the maxBBOX without an issue, so you are able to do a full dataset download every time...

HOW can you limit this?

**Comment by rduivenvoorde** [comment]
@rouault @elpaso can you maybe give me a hint? Or should I put this to rest... :-)

**Comment by elpaso** [comment]
@rduivenvoorde It's actually Even's code, I implemented the QGIS Server component.

**Comment by gioman** [comment]
> @rduivenvoorde It's actually Even's code, I implemented the QGIS Server component.

@rouault gentle ping here.

**Comment by haubourg** [comment]
issue confirmed during the pygeoapi workshop. Paging size is ignored, but also the option to disable paging is ignored. 

@pblottiere does that ring a bell to you ?

**Comment by haubourg** [comment]
@troopa81 😘

**Comment by haubourg** [comment]
@rouault 😘

**Comment by rduivenvoorde** [comment]
Don't I get any kisses? ;-)

**Comment by haubourg** [comment]
@rduivenvoorde 😘😘
