### ISSUE TITLE
PostGIS reports "Invalid PostgreSQL layer" with no details on data that seems fine

### ISSUE THREAD

**Issue by jschultz** [qgis/QGIS#49416]
### What is the bug or the crash?

I had a QGIS project that worked fine until I updated a PostGIS table that it used. Now when I open the project I get an unavailable data layer and the message `WARNING    Invalid PostgreSQL layer` in the PostGIS log. I've looked through updates to the table and can't see anything wrong (ie geometries are valid, no weird values in any columns). Is it possible to get more detailed information about why PostGIS is rejecting the data layer?

### Steps to reproduce the issue

I don't know.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.5
Compiled against GDAL/OGR | 3.5.0 | Running against GDAL/OGR | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
Compiled against GEOS | 3.10.3-CAPI-1.16.1 | Running against GEOS | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.38.5 | Running against SQLite | 3.39.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
mask | 1.10.2
MetaSearch | 0.3.6
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.4
Python version
3.10.5
Compiled against GDAL/OGR
3.5.0
Running against GDAL/OGR
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
Compiled against GEOS
3.10.3-CAPI-1.16.1
Running against GEOS
3.11.0-CAPI-1.17.0
Compiled against SQLite
3.38.5
Running against SQLite
3.39.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux bookworm/sid

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
mask
1.10.2
MetaSearch
0.3.6
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jschultz** [comment]
For what it's worth I found a couple of related facts:

1. If I create a view from the query, PostGIS rejects the view as a layer, complaining about a lack of primary key.
2. If I create a table from the query, PostGIS accepts it and everything works OK. So this is a work-around for now.

**Comment by gioman** [comment]
> If I create a view from the query, PostGIS rejects the view as a layer, complaining about a lack of primary key.

@jschultz QGIS always needed a column with unique values to be able to load views.

**Comment by jschultz** [comment]
I guess I'm not getting any traction here, not too surprising I suppose. I'll try other forums.
