### ISSUE TITLE
The default base maps cannot be seen or replaced after deletion

### ISSUE THREAD

**Issue by fitmos** [qgis/QGIS#49412]
### What is the bug or the crash?

First, I removed the default base maps "Mapzen Global Terrain" and "OpenStreetMap" from XYZ Tiles, then I loaded my connections from an XML file that includes "Mapzen Global Terrain" and "OpenStreetMap". At the moment, the XYZ tile list is blank.
However, it pops up a notification that the connections with these two names already exist. Overwrite?
No matter I choose to overwrite or not, these two connections can not be seen in the XYZ Tiles list. They become invisible items that no one can access.

### Steps to reproduce the issue

1. remove "Mapzen Global Terrain" and "OpenStreetMap" from XYZ Tiles
2. Load connections from an XML file which includes "Mapzen Global Terrain" and "OpenStreetMap"
3. see error.

### Versions

QGIS 3.26.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@fitmos does it still occur with a new profile?

**Comment by fitmos** [comment]
> 

No, a new profile can get things back to normal. Then I replaced the default profile with this new one and everything worked fine.
Nevertheless, you should be aware of this bug.
