### ISSUE TITLE
QgsOptionsPageWidget - helpKey and helpSearchPath are not working

### ISSUE THREAD

**Issue by Guts** [qgis/QGIS#49421]
### What is the bug or the crash?

Hello QGIS dev fellows,

I'm facing an issue to make the `Help` button on my plugins'options page open the appropriate URL.

### Steps to reproduce the issue

Considering a plugin using the `QgsOptionsPageWidget` and `QgsOptionsWidgetFactory` classes as described in the cookbook: https://docs.qgis.org/3.22/en/docs/pyqgis_developer_cookbook/plugins/snippets.html#interface-for-plugin-in-the-options-dialog

```python
from qgis.core import QgsSettings
from qgis.PyQt.QtWidgets import QHBoxLayout
from qgis.gui import QgsOptionsWidgetFactory, QgsOptionsPageWidget

class MyPluginOptionsFactory(QgsOptionsWidgetFactory):

    def __init__(self):
        super().__init__()

    def icon(self):
        return QIcon('icons/my_plugin_icon.svg')

    def createWidget(self, parent):
        return ConfigOptionsPage(parent)

class ConfigOptionsPage(QgsOptionsPageWidget):

    def __init__(self, parent):
        super().__init__(parent)
        layout = QHBoxLayout()
        layout.setContentsMargins(0, 0, 0, 0)
        self.setLayout(layout)

    def helpKey(self) -> str:
        return "qgis/my-plugin-doc/"
        # I've also tried the full URL, not working too
        # return "https://oslandia.gitlab.io/qgis/my-plugin-doc/"

class MyPlugin:
    def __init__(self, iface: QgisInterface):
        """Constructor.

        :param iface: An interface instance that will be passed to this class which \
        provides the hook by which you can manipulate the QGIS application at run time.
        :type iface: QgsInterface
        """
        self.iface = iface

    def initGui(self):
        self.options_factory = MyPluginOptionsFactory()
        self.options_factory.setTitle(self.tr('My Plugin'))
        iface.registerOptionsWidgetFactory(self.options_factory)

        # trying to add my base URL to HelpSearchPath
        QgsSettings().setValue(
            "help/helpSearchPath",
            [
                "https://docs.qgis.org/$qgis_short_version/$qgis_locale/docs/user_manual/",
                "https://oslandia.gitlab.io/",
            ],
        )

    def unload(self):
        iface.unregisterOptionsWidgetFactory(self.options_factory)

```

Then:

1. Open Options menu
2. Go the plugin tab
3. Click on the help button (bottom left)
4. It tries to open (as showed in the messages panel): `https://docs.qgis.org/3.22/fr/docs/user_manual/qgis/my-plugin-doc/` (or `https://docs.qgis.org/3.22/fr/docs/user_manual/https://oslandia.gitlab.io/qgis/my-plugin-doc/`)

### Versions

Version de QGIS | 3.22.8-Białowieża | Révision du code | 8d5e9761df
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.10.4
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 14.3 (Ubuntu 14.3-0ubuntu0.22.04.1)
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.6
Version de l'OS | Ubuntu 22.04 LTS
  |   |   |  
Extensions Python actives
geotuileur | 0.5.1
plugin_reloader | 0.9.1
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

With the help of @troopa81, we dove into the source code and found out that there is probably an issue when QGIS tries every base URL in the helpSearchPath, every response, even 40*, are interpreted as 200.

**Comment by gioman** [comment]
you should *also* post your question in the developers mailing list.

**Comment by troopa81** [comment]
@gioman Why do you think we should discuss this on developers mailing list ? I think this is not really a question, simply an issue that need to be fixed.

**Comment by gioman** [comment]
>  think this is not really a question, simply an issue that need to be fixed.

ok.
