### ISSUE TITLE
Projected shape files

### ISSUE THREAD

**Issue by steverichmondnas** [qgis/QGIS#49426]
### What is the bug or the crash?

I have a shape file that when i apply a projected coordinate system too - always lands at the South Pole

Every shape file does this

Others can use the same shapefile with no issue

### Steps to reproduce the issue

happens with all projected coordinate systems

eg EPSG:32754

### Versions

3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@steverichmondnas could you please report all the information in the Help->About window? Could you please attach the Shapefile layer zipped files and specify all the exact steps to replicate the issue? Could you please try using a new QGIS user profile?
