### ISSUE TITLE
SQL Server Spatial CRS Not Recognized

### ISSUE THREAD

**Issue by DeanRother** [qgis/QGIS#49434]
### What is the bug or the crash?

I have a table in SQL Server with a geometry column.  I have created the ogc metadata table and provided metadata for the table, e.g. select f_table_catalog, f_table_schema, f_table_name, f_geometry_column, coord_dimension, srid, geometry_type
from dbo.geometry_columns.  I have written the srid into the table along with the other metadata.  When I add the layer to my QGIS project 3.22.5, I am prompted to provide a CRS.  When I inspect the layer properties, the dialog reports the EPSG code in the General section, but the Coordinate Reference System (CRS) reports unknown.

### Steps to reproduce the issue

CREATE TABLE [dbo].[geometry_columns](
	[f_table_catalog] [varchar](128) NOT NULL,
	[f_table_schema] [varchar](128) NOT NULL,
	[f_table_name] [varchar](256) NOT NULL,
	[f_geometry_column] [varchar](256) NOT NULL,
	[coord_dimension] [int] NOT NULL,
	[srid] [int] NOT NULL,
	[geometry_type] [varchar](30) NOT NULL,
 CONSTRAINT [geometry_columns_pk] PRIMARY KEY CLUSTERED 
(
	[f_table_catalog] ASC,
	[f_table_schema] ASC,
	[f_table_name] ASC,
	[f_geometry_column] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

create table dbo.segment (
	id integer not null identity(1,1),
	system_name varchar(50) null,
	geom geometry not null
)
go
alter table dbo.segment add constraint pk_segment primary key clustered (id)
go

Add data to the table.

1. Open QGIS.
2. Create a connection to the SQL Server database.
3. Open SQL Server connection.
4. Right click the segment table and choose Layer Properties...
5. Also, add the segment table to the map and you should get a dialog that request the CRS be specified.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.5-Białowieża | QGIS code revision | c2723178
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 13.0
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
qgis2web | 3.16.0
quick_map_services | 0.19.29
db_manager | 0.1.20
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.5-Białowieża
QGIS code revision
[c2723178](https://github.com/qgis/QGIS/commit/c2723178)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
qgis2web
3.16.0
quick_map_services
0.19.29
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This post suggest other users have had the same issue: https://github.com/qgis/QGIS/issues/42038.

**Comment by gioman** [comment]
@DeanRother adding same data would improve the chances to have this confirmed/looked at.
