### ISSUE TITLE
QgsMemoryProviderUtils method to create a memory layer from an existing layer

### ISSUE THREAD

**Issue by komima** [qgis/QGIS#49430]
### Feature description

Adding a function like `createMemoryLayerFromLayer` for creating an empty memory layer from an existing layer (with fields configurations fully cloned) could be a helpful addition to the `QgsMemoryLayerUtils` api.

```python
new_layer = QgsMemoryLayerUtils.createMemoryLayerFromLayer(layer)
```

Using [QgsMemoryProviderUtils.createMemoryLayer](https://github.com/qgis/QGIS/blob/master/src/core/providers/memory/qgsmemoryproviderutils.cpp#L63) with parameters (fields, type, crs) taken from an existing layer does not fully preserve the field configurations (for example field defaults, since fields are only used to build the query string config), and extra steps are needed to make the new layer behave like an existing layer but with memory provider instead.

Interactions between `QgsVectorLayer`, `QgsFields` and `QgsEditFormConfig` are not very clear from the code, but it seems constraints, widget setups, etc. are stored [on the layer](https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectorlayer.cpp#L5789) as well as [on the field](https://github.com/qgis/QGIS/blob/master/src/core/vector/qgsvectorlayer.cpp#L4093), but setting these must be done through the layer methods like `setEditorWidgetSetup`, or inherited from data provider.

### Additional context

Currently using a workaround by initializing a memory layer with empty fields, adding existing fields to data provider directly and calling `updateFields` seems to work, but this seems like a hack due to uncertainty how these things interact:

```python
new_layer = QgsMemoryProviderUtils.createMemoryLayer(
    layer.name(),
    QgsFields(),
    layer.wkbType(),
    layer.crs(),
)
new_layer.dataProvider().addAttributes(layer.fields())
new_layer.updateFields()
```

**Comment by nyalldawson** [comment]
You can use QgsFeatureSource.materialize (https://qgis.org/pyqgis/master/core/QgsFeatureSource.html#qgis.core.QgsFeatureSource.materialize) for this.

Eg.

```
    new_memory_layer = layer.materialize(QgsFeatureRequest())

    # or with filters/etc
 
    new_memory_layer = layer.materialize( QgsFeatureRequest().setFilterExpression('"my_field" > 5') )
```

**Comment by komima** [comment]
> You can use QgsFeatureSource.materialize (https://qgis.org/pyqgis/master/core/QgsFeatureSource.html#qgis.core.QgsFeatureSource.materialize) for this.
> 
> Eg.
> 
> ```
>     new_memory_layer = layer.materialize(QgsFeatureRequest())
> 
>     # or with filters/etc
>  
>     new_memory_layer = layer.materialize( QgsFeatureRequest().setFilterExpression('"my_field" > 5') )
> ```

It seems it only wraps the same `QgsMemoryLayerUtils.createMemoryLayer` call with added bonus of copying features to the new layer, but does not really clone fully the [fields](https://github.com/qgis/QGIS/blob/master/src/core/qgsfeaturesource.cpp#L158) or any other options that `QgsVectorLayer.clone` for example would? 

To use `QgsVectorLayer.splitFeatures` on the new layer fields defaults are needed, since if there is a default clause on uuid primary key field, splitFeatures works by adding new features that respect the defaults, and generates new ids for those. Without defaults the new split features retain the original feature id, and passing the features back from the new layer to the original will fail due to duplicate primary keys.

Optimal api probably would combine both `QgsVectorLayer.clone` and `QgsFeatureSource.materialize`, memory data provider filled with the features from the request, and otherwise acts as clone by copying all the behavior-changing and user-visible things like defaults, forms, etc. 

Also kind of related to this, clone does not copy geometry options, even though those affect behavior of edits on the layer, is that intentional or should those be clones as well?
