### ISSUE TITLE
file INSTALL cannot find "python/plugins/db_manager/resources_rc.py"

### ISSUE THREAD

**Issue by ArchangeGabriel** [qgis/QGIS#49441]
### What is the bug or the crash?

Packaging fails with:
```
CMake Error at build/python/plugins/db_manager/cmake_install.cmake:46 (file):
  file INSTALL cannot find
  "/build/qgis/src/build/python/plugins/db_manager/resources_rc.py": No such
  file or directory.
Call Stack (most recent call first):
  build/python/plugins/cmake_install.cmake:47 (include)
  build/python/cmake_install.cmake:523 (include)
  build/cmake_install.cmake:68 (include)
```

### Steps to reproduce the issue

I’m building QGIS like this:
```
cmake -S qgis-3.26.1 -B build -G Ninja \
    -DCMAKE_INSTALL_PREFIX=/usr \
    -DWITH_3D=TRUE \
    -DWITH_QUICK=TRUE \
    -DBINDINGS_GLOBAL_INSTALL=TRUE \
    -DSIP_GLOBAL_INSTALL=TRUE \
    -DWITH_STAGED_PLUGINS=FALSE \
    -DWITH_SERVER=TRUE \
    -DWITH_CUSTOM_WIDGETS=TRUE \
    -DWITH_PDAL=TRUE \
    -DHAS_KDE_QT5_PDF_TRANSFORM_FIX=TRUE \
    -DHAS_KDE_QT5_SMALL_CAPS_FIX=TRUE \
    -DHAS_KDE_QT5_FONT_STRETCH_FIX=TRUE
cmake --build build
cmake --install build
```

### Versions

3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

**Comment by gioman** [comment]
@ArchangeGabriel for build from source issue you should really write in the developers mailing list.

**Comment by ArchangeGabriel** [comment]
@gioman I’m already receiving way too much emails per day, I’m not fond of the idea of subscribing to yet another mailing list (since posting is of course subscriber only)…

**Comment by nicogodet** [comment]
You can try on [IRC](https://qgis.org/en/site/forusers/support.html#matrix-irc) or [Revolt chat](https://app.revolt.chat/invite/8ETadcj8)

**Comment by nicogodet** [comment]
And in any case, provide more infos.
Versions of Qt, python, etc etc

Regarding the error message, it seems the it fails to compile the .qrc file (it use `pyrcc5`, is it available ?) but without further infos, hard to spot the culprit.

**Comment by ArchangeGabriel** [comment]
I’ll try Matrix then. And of course I should have provided way more information, you’re right.

So I’m building for [Arch Linux](https://archlinux.org), the following dependencies being installed at build time:
```
ocl-icd proj geos gdal expat spatialindex qwt libzip sqlite3 protobuf
zlib exiv2 postgresql-libs libspatialite zstd pdal qt5-base
qt5-svg qt5-serialport qt5-location qt5-webkit qt5-3d qt5-declarative
qscintilla-qt5 qtkeychain-qt5 qca-qt5 gsl python-pyqt5 python-qscintilla-qt5
hdf5 netcdf libxml2
```
The version for any of them can be seen through https://archlinux.org/packages/. Qt is 5.15.5 + KDE maintenance patches, Python 3.10.6. `pyrcc5` is available as part of the `python-pyqt5` package.

[Full build log](https://gist.github.com/ArchangeGabriel/ba07092bfe39ef0801d70b52f22238ed).

Note that the issue does not appear with our current (but seemingly outdated, e.g. QWTPOLAR is gone AFAIU) build flags: https://github.com/archlinux/svntogit-community/blob/packages/qgis/trunk/PKGBUILD#L36. I don’t remember exactly why I made the changes, but they must have seemed reasonable at the time. I’ll try to pinpoint the responsible flag.

**Comment by ArchangeGabriel** [comment]
OK, so the issue is caused by `-DWITH_STAGED_PLUGINS=FALSE`. I’ll check again if that is really needed/a good idea to have, but not tonight.
