### ISSUE TITLE
Message for new versions points to download.qgis.org, which is not very convenient

### ISSUE THREAD

**Issue by myxBeni** [qgis/QGIS#49446]
### What is the bug or the crash?

Might as well be a feature request. 

The message for new versions points to download.qgis.org

<img width="961" alt="image" src="https://user-images.githubusercontent.com/109787519/180384273-793299ab-5d5c-4072-8cda-5d43f137de15.png">

Whilst it technically is possible to download the newest version of qgis there, it is not very convenient, as shown below.
<img width="1496" alt="image" src="https://user-images.githubusercontent.com/109787519/180385022-0e69d393-67a0-42cf-9df1-725e062ddda9.png">

I found myself skipping updates just because I got lost on this download page and was not sure which to choose.

I suggest to either direct towards the language specific https://www.qgis.org/de/site/forusers/download.html
or the top level domain qgis.org.

### Steps to reproduce the issue

Open an old version of qGis

### Versions

QGIS-Version | 3.26.0-Buenos Aires | QGIS-Codeversion | 0aece2818e
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.2
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.11.5
BS-Version | macOS 12.4
  |   |   |  
Aktive Python-Erweiterungen
SpreadsheetLayers | 2.0.1
slyr_community | 4.0.1
qfieldsync | v4.1.1
Generalizer3 | 1.0
qlyrx | 0.3.3
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS-Version
3.26.0-Buenos Aires
QGIS-Codeversion
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.3.2
PROJ-Version
8.1.1
EPSG-Registraturdatenbankversion
v10.028 (2021-07-07)
GEOS-Version
3.9.1-CAPI-1.14.2
SQLite-Version
3.35.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.11.5
BS-Version
macOS 12.4

Aktive Python-Erweiterungen
SpreadsheetLayers
2.0.1
slyr_community
4.0.1
qfieldsync
v4.1.1
Generalizer3
1.0
qlyrx
0.3.3
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@myxBeni, this may be due to a redirection issue.
It seems to me https://download.qgis.org/ used to be redirected to https://qgis.org/en/site/forusers/download.html or https://download.qgis.org/en/site/ at least until last April, but now it results redirected to https://download.qgis.org/downloads/.

**Comment by myxBeni** [comment]
this might well be! Do you know who would be able to fix that?

**Comment by agiudiceandrea** [comment]
@myxBeni I think it would be best to report this issue at https://github.com/qgis/QGIS-Website where also the script https://github.com/qgis/QGIS-Website/blob/master/scripts/mkversion.py resides. Anyway, I think @jef-n could probably know more about this.

**Comment by jef-n** [comment]
https://download.osgeo.org/ is now rewritten to https://qgis.org/$lang/site/forusers/download.html
