### ISSUE TITLE
Delete / Unlink Function available in Relation Editor Widget

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#49445]
### What is the bug or the crash?

With "right-click" on Feature in Relation Editor Widget "Delete Feature" and "Unlink Feature" is always possible, even when those buttons are hidden.

![image](https://user-images.githubusercontent.com/28384354/180382923-02b4545e-b5fb-4d81-a681-25666c937ee1.png)

But still:
![image](https://user-images.githubusercontent.com/28384354/180382966-aa0bee7c-7750-4ee4-aebd-629446cc3fcc.png)

### Steps to reproduce the issue

1. Open Attribute Table on Layer "language"
2. Go to entry "english"
3. See the Relation Editor in the Form View: There the buttons are hidden but with right click (in editing-mode) the options are visible.

### Versions

Tested on:
```
QGIS version | 3.24.3-Tisler | QGIS code revision | e4feab1714
```
and 
```
QGIS version | 3.27.0-Master | QGIS code revision | d0b9569f9d
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context
[relation_editor.zip](https://github.com/qgis/QGIS/files/9165508/relation_editor.zip)

**Comment by signedav** [comment]
Not sure if it's really a BUG or just a missing bit. For the users this appears to be a bug. But I belief it's just not implemented.

**Comment by agiudiceandrea** [comment]
It seems to me these settings are for the toolbar buttons and not for the context menu items. So I think new settings should be added for the context menu items.
In fact, the visibility of these context menu items is not affected by such settings and they are always visible if the layer is editable:
https://github.com/qgis/QGIS/blob/567315d658874323c214ae722d1a85ff8bed848f/src/gui/qgsrelationeditorwidget.cpp#L561-L573

**Comment by signedav** [comment]
Thanks for pointing to the place in the code. Yes, I totally agree, that the menu should be built according to the button settings. Good thought to rename the settings then as well.

**Comment by gioman** [comment]
> So I think new settings should be added for the context menu items.

@agiudiceandrea so this would not be better suited for a feature request/improvement rather than a bug?

**Comment by agiudiceandrea** [comment]
Hi @gioman, I think this is a valid bug. I've proposed a PR https://github.com/qgis/QGIS/pull/49455 that fixes this bug reusing the the settings already available instead of adding new ones.

**Comment by gioman** [comment]
> Hi @gioman, I think this is a valid bug. I've proposed a PR #49455 that fixes this bug reusing the the settings already available instead of adding new ones.

ok
