### ISSUE TITLE
Geoparquet support

### ISSUE THREAD

**Issue by ricardobarroslourenco** [qgis/QGIS#49454]
### Feature description

Geoparquet is becoming available in GDAL 3.5 (refer to [documentation](https://gdal.org/drivers/vector/parquet.html)). Myself  and @rafapereirabr (refer to [here](https://gis.stackexchange.com/q/430973/60281)) are interested in such feature becoming available in QGIS, given the good performance on data compression (and speed during its I/O).

**Comment by agiudiceandrea** [comment]
On Windows (OSGeo4W), GDAL 3.5.1 is already available for QGIS 3.22.9 and 3.26.1, and GDAL 3.6.0 is already available for QGIS 3.27.0-Master nightly build

**Comment by ricardobarroslourenco** [comment]
So @agiudiceandrea is it already supported from a GUI perspective, or only from a programmatic one?

**Comment by agiudiceandrea** [comment]
Have you tried?
![image](https://user-images.githubusercontent.com/16253859/180592656-4a053dd9-6d31-45ec-bf48-97b6f2f83d17.png)

**Comment by ricardobarroslourenco** [comment]
It seems that for MacOS (v 3.26.1) it is not available... Can you point me where can I find the nightly build of the 3.27 for MacOS?
![Screen Shot 2022-07-23 at 14 08 27](https://user-images.githubusercontent.com/7102375/180617718-95544c88-c10f-4022-b2dc-3d29ddc8357e.png)

**Comment by agiudiceandrea** [comment]
> Can you point me where can I find the nightly build of the 3.27 for MacOS?

@ricardobarroslourenco, the latest macOS nigthly build qgis-macos-nightly.dmg is available at https://download.qgis.org/downloads/macos/
Anyway, the feature does not depend on the QGIS version, but on the GDAL version, which AFAIK is at 3.3.2 in macOS installers.

**Comment by cholmes** [comment]
Note that for geoparquet support in gdal it 'is only enabled if the driver is built against the arrowdataset C++ library.' (from https://gdal.org/drivers/vector/parquet.html) In conda there is a `libgdal-arrow-parquet` library, so if you install qgis on conda (`conda install qgis libgdal-arrow-parquet`) then you can get a working QGIS on mac. But ideally the dmg packages would include the arrow drivers.

**Comment by agiudiceandrea** [comment]
@ricardobarroslourenco could you please file the feature request to the https://github.com/qgis/QGIS-Mac-Packager repository if it is still relevant for you?

**Comment by sandeepgadhwal** [comment]
is this format support in QGIS ubuntu ?

**Comment by matkoniecz** [comment]
> Have you tried?

Yes, and I see no way to use it, at least in 3.27.0-Master QGIS code revision on Lubuntu 20.04.

![screen](https://github.com/user-attachments/assets/feaf9e4e-b1bb-45f1-8b43-ba7787ea2d90)

**Comment by 300000kms** [comment]
Working on QGIS version 3.44.3-Solothurn (gdal 3.8.4) geoparquet is not available. This is an error or there's a big delay implementing this option respect the other OS

**Comment by cholmes** [comment]
It'll be in QGIS 4.0, which I believe is slated for next month. You can try it out now at https://github.com/opengisch/qgis-notarize - it's pretty stable at this point, I've been using it.
