### ISSUE TITLE
When using a computed or virtual field that refers to other layers's fields having the same name, the wrong value is returned.

### ISSUE THREAD

**Issue by garci66** [qgis/QGIS#49469]
### What is the bug or the crash?

We have a layer that has a virtual field with a sum of multiple relation aggregates. It seems that there is some sort of cache for relations and the wrong value is returned.

The virtual field is set to the following expression:
```
relation_aggregate( 'ganancia_a_Cable_acceso_FK_Cable_Acce_fid','sum',"Longitud") + relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid") + relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")  
```

All three relations use `Cable_Acceso` as the referenced layer, `fid` as the referenced field, and `Cable_acceso_FK` as the referencing field as it can be seen below:

![image](https://user-images.githubusercontent.com/10575320/180797214-fe9e9c9d-8ac2-4fd2-873c-b91ccadac875.png)

Now the problem is in the formula, the `relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")` is returning the same value as `relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")`

Is it possible there is a cache of the aggregate result of sorts and its not using the relation_id as part of the key?

Even if I apply the `relation_aggregate('Cierre_Emp_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")` as a new virtual field and a second field with `relation_aggregate('CTO_134c70_Cable_Acceso_FK_Cable_Acce_fid','count',"fid")`, in the expression editor, looking at each value, the correct result is shown, but then, in the table view, both columns show the same value.

### Steps to reproduce the issue

At least three layers are needed:

* Cable (layer)
  `Name (Text)`
* CTO (layer)
  `Name (Text)`
  `Cable_FK (Uint64)`
* CE (layer)
  `Name (Text)`
  `Cable_FK (Uint64)`

Then the following relations are created:

![image](https://user-images.githubusercontent.com/10575320/180810872-53ecb017-9a75-4607-8c89-43c9e2971a48.png)

and the same one for CTO_2_Cable

It should look as this:
![image](https://user-images.githubusercontent.com/10575320/180811269-4bf71ae1-086b-4358-8049-69431a484768.png)

Then create some polylines in the "Cable" layer and add some CE points, associating them to the polylines (the relation field should appear already) and some CTO points as well, also associated

The `CE` table should look as follows:
![image](https://user-images.githubusercontent.com/10575320/180813589-8bf4ebe8-7d2e-4c9c-b7e0-d7e31aa6302b.png)

while the `CTO` table would have data similar to this:
![image](https://user-images.githubusercontent.com/10575320/180813695-a8730f53-5618-4280-a41a-dfdd762db8b4.png)

Finally, in the Cable table, we create three new virtual fields:

The first one, called `sum_count` as type integer with the following expression:
```relation_aggregate('CE_6be67ee_Cable_FK_rel_agg_bu_fid','count',"fid") + relation_aggregate('CTO_023987_Cable_FK_rel_agg_bu_fid','count',"fid")```

which looks like the following:
![image](https://user-images.githubusercontent.com/10575320/180814610-cd6c5039-6cbc-4622-8c23-8335f4057ef0.png)

and we already see the problem. The sum is wrong as it can be seen below:

![image](https://user-images.githubusercontent.com/10575320/180815289-8fabae9e-cc53-4d18-b752-342ddd821b17.png)

 If only a single relation (CE) is used (in the whole form) the value is correct:
![image](https://user-images.githubusercontent.com/10575320/180815438-1d06376a-3304-40b7-b23e-3b8ed73a3dcd.png)

result:
![image](https://user-images.githubusercontent.com/10575320/180815520-240573df-dcbb-4c46-96a4-63a7b4385edc.png)

or the other relation (CTO)
![image](https://user-images.githubusercontent.com/10575320/180815680-8ab4d33c-c743-4bd6-aadd-d09510cb7f30.png)

result:
![image](https://user-images.githubusercontent.com/10575320/180815736-751af42e-39cb-4995-bdd6-57e6eec63fe5.png)

Finally.. if all formulas are used at the same time:
![image](https://user-images.githubusercontent.com/10575320/180816003-1d788c82-477f-4c74-8c1d-656d9aadb9f8.png)

the values are wrong:
![image](https://user-images.githubusercontent.com/10575320/180816113-92d76bdf-559d-45f8-87a0-5d45a7d69f5a.png)

And one final detail, if the order of usage of the relations is changed, the totals change:
In this case, we refer to the `CTO` relation first:
``` relation_aggregate('CTO_023987_Cable_FK_rel_agg_bu_fid','count',"fid") + relation_aggregate('CE_6be67ee_Cable_FK_rel_agg_bu_fid','count',"fid")```

![image](https://user-images.githubusercontent.com/10575320/180816461-f0164363-766c-4ac4-b247-0df359c0c6fe.png)

and the result is the following:
![image](https://user-images.githubusercontent.com/10575320/180816606-ecced319-15b5-4979-946f-ab39ec9df070.png)

![image](https://user-images.githubusercontent.com/10575320/180816661-e1b753c2-5e08-4aa9-85cc-60198cd1a25f.png)

### Versions

Also reproducible in 3.16.11 and 3.16.9 as well as the following:

QGIS version
3.22.9-Białowieża
QGIS code revision
a8e9e6fa
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.4
AppendFeaturesToLayer
1.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This was reproduced in multiple QGIS versions on different machines / users / even in a brand new project

Attached is a zip file with the corresponding project and geopackage

[rel-agg.zip](https://github.com/qgis/QGIS/files/9182658/rel-agg.zip)
.

**Comment by garci66** [comment]
dear @Pedro-Murteira do you need any more info from my side? (not sure what the different task icons represent). Thanks!

**Comment by Pedro-Murteira** [comment]
@garci66 I think the issue is well described. I'm not capable of looking further into it. But the ticket remains open, and the devs will try and resolve the issue.

**Comment by CharlesGag** [comment]
I have the exact same problem, using multiple relation_aggregate as well.

**Comment by garci66** [comment]
For the moment i've given up on relation aggregates... seems to cause too many stability issues.

**Comment by phidrho** [comment]
Hi @garci66, @CharlesGag,

I have narrowed down the issue. Seems that this bug report is not related to "Relations" but with "Expression editor".

@agiudiceandrea
This also is not related only to virtual fields, it also affects computed fields so the bug report name should be corrected.

**The bug happens when foreign key column in related tables have the same name**, it seems that expression editor fetches field names only once (first that comes) and uses them for entire expression.

![workaround](https://github.com/qgis/QGIS/assets/1849293/db963880-f4bf-47d6-9978-64e64ad6081b)

I'm attaching an example projects with bug and workaround:
[qgis_relation_aggregate_bug.zip](https://github.com/qgis/QGIS/files/12675767/qgis_relation_aggregate_bug.zip)

@signedav
Have you maybe encountered this bug, since you worked a lot with relations? Is there any other workaround?

**Comment by garci66** [comment]
thanks! thats good to know... in my case, since I use FID everywhere (And its the native QGIS field).. i dont have too many options to change it. (I my FK reference is to the FID... so I can't use a different field unfortunately).

not sure if we need more details.. or can we change anything else

**Comment by signedav** [comment]
I haven't encountered this bug, but I agree it's a nasty one.

As a workaround in your case you could use other fields. Since you don't need to pass the FK as the expression in the `relation_aggregate`. The last parameter there could afaik be any field of your child-layer.

_Btw. it should be avoided to use fids as FKs. This "technical" GPKG id is not stable and as soon as you start to merge data from two different GPKGs you will encounter problems. But this has nothing to do with this issue._

**Comment by garci66** [comment]
Thanks! indeed.. im aware of the pitfalls of FIDs as FKs... Right now
projects are "self-contained" withing a single GPKG and we developed a
little tool to migrate / re-number FKs when needed, but indeed, UUIDs would
be much better from a data stability POV.

On the other hand, in a lot of cases, we need to access the QGIS object
pointed by the FK.. and being able to use the FID directly without an
additional lookup sped up things quite considerably for us in the python /
qgis side.

In that particular example, given I was using only "count", indeed, I
wouldnt need to use FID but just any other non-null field.. but overall,
I've found that just configuring relations tended up to really make qgis a
lot less stable so we ended up doing them "manually".

thanks!

**Comment by agiudiceandrea** [comment]
> This also is not related only to virtual fields, it also affects computed fields so the bug report name and label should be corrected.

@phidrho, the issue report title can be changed by @garci66.

**Comment by garci66** [comment]
Just re-titled the issue... not sure if the name is better. I don't think I can change the labels myself though

**Comment by phidrho** [comment]
Just a note, I also tested:

- if you have the `FIELD` with the same name in the source table, and try to call it, bug also affects that
  - in my case I have field named `AREA` in all three tables (source table and two related tables) and expression is evaluated only for first referenced `AREA` field

- this bug doesn't seem to affect other functions
![image](https://github.com/qgis/QGIS/assets/1849293/80811cf1-4a7c-45c5-a347-5820861c9337)

**Comment by agseaton** [comment]
It is a year and a half since this bug was reported. Presumably it is difficult to fix, but would it be possible to at least mention it in the documentation? This might save people a lot of wasted time!

**Comment by garci66** [comment]
agree.. a mention in the RN would be good

**Comment by PetitMote** [comment]
Hi there,
Just wanted to say I’ve also met this bug. I hope someone can fix it someday!

My workaround was to rename the referencing field: I have 2 tables with the same fields, because I needed to separate them. The two have a field named "zae", which reference the "nom_zae" field on my referenced layer. Simply renaming one of the field "zae_" made the relation aggregates work correctly.

**Comment by lp-dj** [comment]
Hello, the next fellow sufferer here.

Was starting to doubt my sanity until I slowly understood the bug after almost a full day of work. Now to post it here, I see it has been reported for over 2 years.

Thanks so far to everyone involved @garci66, @phidrho & @signedav !

What can we "non-QGIS programmers" do to help fix this bug?

Would love to check the code myself. Can't find the right place in the source code and unfortunately my programming skills are limited to a bit of python. Presumably the corresponding code is written in C++ anyway?

Does throwing money at it help? If so, how much is needed and where is the appropriate donation pot?

Nasty piece of bug, let's finally get rid of it! ;)

**Comment by phidrho** [comment]
Hi @lp-dj,

if you're interested in funding bugfix yourself, you can contact companies from official list that offer commercial support to QGIS project:
https://qgis.org/resources/support/commercial-support/

Otherwise, you can always donate to QGIS project, most of the money is spent on bugfixes, but not in particular order (bugs that affect most users are fixed first):
https://qgis.org/funding/donate/

**Comment by lp-dj** [comment]
Hi @phidrho,

Thanks for your feedback.

Yes, I have already talked my employer into a sustaining membership ;)

If I knew approximately how much this bugfix would cost, I would try to organize an order via commercial support, as this feature is relatively important for my/ our work.

Thanks for the tip about commercial support. I'll ask one or two companies for a rough cost estimate!

**Comment by agiudiceandrea** [comment]
@lp-dj, as already suggested, you could contact companies from official list that offer commercial support to QGIS project https://qgis.org/resources/support/commercial-support/ and ask if they want to fix this bug and how much it will cost.

**Comment by elpaso** [comment]
It would be nice if someone could test my patch here: https://github.com/qgis/QGIS/pull/58819

**Comment by elpaso** [comment]
If you are on windows you can test this build: https://github.com/qgis/QGIS/pull/58819#issuecomment-2363785966

**Comment by lp-dj** [comment]
And thanks again! Looks like it's working perfectly now!

In my MWE all relation_aggregates are now executed correctly.

What a relief! :smile: :rocket:
