### ISSUE TITLE
Dots in file name crashing QGIS - Vector Join

### ISSUE THREAD

**Issue by robbochartis** [qgis/QGIS#49460]
### What is the bug or the crash?

One of the users we work with was using the "Vector Join" tool and had dots in the name of the non spatial dataset that was being used to join. See pic below. This crashed QGIS. The file name was changed to use underscores and then all was OK.

![image](https://user-images.githubusercontent.com/21251304/180701802-283ea43a-1ad9-448c-b6e3-6bcf7a0256d8.png)

### Steps to reproduce the issue

1. Drag and drop csv file in (dots in the file name)
2. Open spatial layer to be joined
3. Double click spatial layer and select joins
4. Create a join as per screenshot
5. QGIS crashes

### Versions

3.22.9 - LTR build

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Pedro-Murteira have you tested this on 3.26?

**Comment by uclaros** [comment]
I cannot reproduce on master.
@robbochartis can you reproduce the crash and share the data that caused it?
