### ISSUE TITLE
"evaluate default value on providers side" is not saved as checked when saving projects on QGIS 3.26

### ISSUE THREAD

**Issue by ijustloveit13** [qgis/QGIS#49463]
### What is the bug or the crash?

I have a Postgis table whose id is generated by a sequence.
Previously, on GIS 3.24 an older versions, when I inserted it without saving, it used to write down the id, but in 3.26, it writes the sequence and the id is retrieved after the object is saved. It causes problem when there are other layers joined with this object using its id. I should first save and then join other objects to it.
![1](https://user-images.githubusercontent.com/4344314/180747980-2a92db09-1807-4bea-bd31-09999bb8c27f.png)
![2](https://user-images.githubusercontent.com/4344314/180748001-8ea939a4-c13a-48e4-9220-4e433ef2684f.png)
 

### Steps to reproduce the issue

![1](https://user-images.githubusercontent.com/4344314/180748118-49b97919-fb54-4b3b-b865-b534734c92b9.png)
![2](https://user-images.githubusercontent.com/4344314/180748124-7af06434-b3fd-482d-9dd6-a3600d4d1970.png)

### Versions

QGIS version
3.26.1-Buenos Aires
QGIS code revision
b609df9ed4d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 1607

Active Python plugins
logs_searcher
1.0.5
networkanalysis
1.9.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99

-----
QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 1607

Active Python plugins
logs_searcher
1.0.5
networkanalysis
1.9.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99
------

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
Can you see how it plays with checking "Evaluate default values on provider side" option in the project Properties > Data Sources dialog, please?

**Comment by ijustloveit13** [comment]
There is no difference if this is checked or not.

**Comment by gioman** [comment]
> Previously, on GIS 3.24 an older versions, when I inserted it without saving, it used to write down the id, but in 3.26, it writes the sequence and the id is retrieved after the object is saved. It causes problem when there are other layers joined with this object using its id. I should first save and then join other objects to it.

@ijustloveit13 I don't recall to have aver been different from what you describe. But as you haven't really added the steps/data to replicate is hard to say.

**Comment by ijustloveit13** [comment]
I posted the image both in 3.243 and 3.26.1. I have been working for a couple of years and I had no problem, but the problem appeared in 3.26.1. 
Replicating it is so easy. Create a table in postgis and set the id to be filled with a sequence. Now, load it in QGIS and insert a record.

**Comment by gioman** [comment]
> Create a table in postgis and set the id to be filled with a sequence. Now, load it in QGIS and insert a record.

@ijustloveit13 I did, and it works as in your screenshots for 3.26.1, but that is has always worked, as far as I remember, for columns with an column with values controlled by a sequence. Example on 3.22:

![image](https://user-images.githubusercontent.com/1951107/183614708-b5610ddc-0f30-435d-9f85-0f9a797c45cd.png)

**Comment by ijustloveit13** [comment]
@gioman 
Dear Giovanni
If you check this checkbox, it will be as I showed in the images
![Untitled](https://user-images.githubusercontent.com/4344314/183621243-94a60c9b-0441-4e86-814f-7bea575dbdaf.png)
.

**Comment by gioman** [comment]
> If you check this checkbox, it will be as I showed in the images

A rather important piece of info, anyway works as expected here on both 3.26 and 3.22

![image](https://user-images.githubusercontent.com/1951107/183626075-e83973a7-70eb-4fc3-a0e5-213fa8948ee9.png)

**Comment by ijustloveit13** [comment]
@gioman 
Dear Giovanni
Please save the project (QGZ for example) and open it once more. You will see that the id is not generated by the database and nextval.. is written instead.

**Comment by gioman** [comment]
> Please save the project (QGZ for example) and open it once more. You will see that the id is not generated by the database and nextval.. is written instead.

@ijustloveit13 I edited the title to better reflect what the problem is.

**Comment by ijustloveit13** [comment]
@gioman 
Dear Giovanni
To be more specific, "evaluate default value on provider's side" is written in the QGS file, but it does not work.
