### ISSUE TITLE
DB Manager: Columns not retrieved in SQL console

### ISSUE THREAD

**Issue by doskabouter** [qgis/QGIS#49467]
### What is the bug or the crash?

In DB Manager, when adding a new layer, the button "Retrieve columns" doesn't work anymore

### Steps to reproduce the issue

Menu: Database, choose DB Manager.
from there connect with your database, open a new SQL Window.
There put in any query (f.e. select * from osm.planet_osm_polygon).
Select "Load as new layer" and click "Retrieve columns"
In older versions, the drop-down next to that button  ("Geometry column") got filled with the available columns, so you can choose the correct column.
In current versions (3.26.0 and 3.26.1) nothing gets added to that dropdown and I get an error in the log-window:
`Traceback (most recent call last):
              File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins\db_manager\dlg_sql_window.py", line 543, in fillColumnCombos
              for col in cols:
             TypeError: 'NoneType' object is not iterable`

### Versions

3.26.0 and 3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Only after running that query (by clicking execute) the dropdown gets filled, but it's a bit awkward having to think about adding a limit 1 to it to prevent loads of data being send over the line

**Comment by gioman** [comment]
> In older versions, the drop-down next to that button ("Geometry column") got filled with the available columns, so you can choose the correct column.

@doskabouter before running the query? seems weird to me, in fact it works the same on 3.22 (and previous) and also I see the same error in the logs in 3.22.

**Comment by gioman** [comment]
> in the 3.14 and the 2.xx versions it retrieve columns did fill the dropdownlist.

again, seems odd to me, can you check?

**Comment by doskabouter** [comment]
Just checked 3.14.0-Pi and that indeed fills in the dropdown.
even (if not yet selected) selecting the load as new layer triggers filling of the dropdown

**Comment by alexbruy** [comment]
Duplicates #48395.
