### ISSUE TITLE
QGIS 3.22.8 crash when merging selected shapes

### ISSUE THREAD

**Issue by DerrickDFS** [qgis/QGIS#49477]
## User Feedback

I was editing a polygon layer from one of our PostGIS databases that is located on an Amazon server. I selected three polygon shapes and split them using the Split Tool. I then selected two of the split shapes of one of the features and tried putting them back together. During this step QGIS 3.22.8 crashed.  I have been able to do this using QGIS 3.22.7 successfully.  I have also tried this process using QGIS 3.22.9 and received the same negative results.

## Report Details

**Crash ID**: [419683f53643e3cb537b9999f5a781cf8ca4978c](https://github.com/qgis/QGIS/search?q=419683f53643e3cb537b9999f5a781cf8ca4978c&type=Issues)

**Stack Trace**
<pre>
QUrl::~QUrl :
QTranslator::translate :
QVariant::clear :
QVariant::operator= :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveActiveLayerEdits :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.8-Bia?owie?a
QGIS code revision: 8d5e9761df
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. start with a blank 3.22.8 project
2. add a layer from one of our postgis databases stored on an Amazon server
3. start an edit session
4. select a polygon shape
5. use the split feature tool to divide the shape into two pieces
6. reselect the new shapes and use the Merge Selected Features tool to join them back to one feature
7. while trying to save edits with the Toggle Editing tool QGIS crashed

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
changeDataSource
3.1
FilterLayersAtOnce-master
1.0
latlontools
3.6.4
MagneticDeclination
2.3.1
shapetools
3.4.6
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This error does not occur when I do the same steps to the same data using QGIS 3.33.7

**Comment by nicogodet** [comment]
@Pedro-Murteira Regression too

**Comment by gioman** [comment]
I'm not able to replicate on 3.26.1 or 3.22.9 on Windows 10, more details are needed.
