### ISSUE TITLE
QGIS 3.26 - Access Violation when splitting line feature (Win 10)

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#49475]
### What is the bug or the crash?

Attempted to split a line into two features. The line layer does not have Z, M, or curve (R) support.

Error from VS debugger:
```
Exception thrown at 0x00007FFD08A8A930 (qgis_core.dll) in qgis-bin.exe: 0xC0000005:
Access violation reading location 0x0000000000000000.
```

Code throwing the exception:
https://github.com/qgis/QGIS/blob/6fd8f424a2cdf5f975dc5dd7b4bc7608ab559127/src/core/geometry/qgsgeos.cpp#L989-L990
Where `splitGeom` is for some reason, an empty unique pointer, so line 990 throws an exception.

`GEOSsplitPoint` is optimized away in the release build.

### Steps to reproduce the issue

1. Have line layer
2. Attempt to split
3. Access Violation exception

### Versions

QGIS version
3.26.1-Buenos Aires
QGIS code revision
b609df9ed4d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
MemoryLayerSaver
4.0.4
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I am not able to share the dataset which causes this. It is in an ESRI File Geodatabase using the filegdb read/write driver. I haven't had this issue in previous QGIS versions.
I am also not able to reliably reproduce this issue either.

**Comment by gioman** [comment]
> I am not able to share the dataset which causes this.

@esnyder-rve you don't need to share the whole dataset, it is enough just the (a) feature that shows this behavior.

**Comment by gischimp** [comment]
I recently installed 3.26.2 and every time I try to split a line feature in a very small shapefile feature class, a Windows fatal exception is thrown. I attached three shapefiles that I tested. Running Windows 11 Pro (10.0.22000 build 22000). Dell Inspiron laptop x64, 16 GB RAM, 12th Gen Intel (R) Core (TM) i5-1235U, 1300 Mnz, 10 cores, 12 logical processors. Here is the report from the crash. Thanks!

## User Feedback

Trying to use split features tool to split a line in a shapefile. Everytime I select the feature and use the tool (draw a line across the line to be split, right-click), the project crashes. Every time.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000042ec (most recent call first):
<no Python frame>
```


**Stack Trace**
No stack trace is available.


**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000


[line_shps_tested.zip](https://github.com/qgis/QGIS/files/9530297/line_shps_tested.zip)

**Comment by gischimp** [comment]
Found potential cause but still exploring. Qgis py console can import ogr but when I try to install adv line editing plugin, fails saying cannot find ogr. Potential conflict with anaconda. (?) Will post again after I run some possible fixes. Could be related to split tool issue. Thanks.

**Comment by gischimp** [comment]
Sorry, was out for a bit. I thought Anaconda install might have broke py paths so uninstalled 3.26.2 and installed 3.26.3. Same thing happens. Put line shapefile in edit mode, select line feature, select split tool, draw line to split and project crashes with same access violation error. Thanks for tracking.
