### ISSUE TITLE
qgis 3.26 chash when select editing shapes

### ISSUE THREAD

**Issue by aliasatp** [qgis/QGIS#49470]
### What is the bug or the crash?

Hi,
recently I downloaded QGIS 3.26 I have a issue when I select shapes editing in digitize tools

### Steps to reproduce the issue

Start editing a vector layer, click on shapes digitizing mode and QGIS chashes

### Versions

3.26.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
More info needed regarding the conditions of the crash and the host. 

Try in an empty project with a new profile and see if it's specific to something.

**Comment by aliasatp** [comment]
It crashes even with new QGIS profile in an empty project. No Bug report
WINDOWS11

**Comment by nicogodet** [comment]
Can you share the data ?

Create a new project, add the faulty layer, retry. Does it crash ?

**Comment by IltonMarcos** [comment]
![image](https://user-images.githubusercontent.com/49507795/189751027-e3e8a8ef-f40c-431e-a5fb-f45f467a4d11.png)
![image](https://user-images.githubusercontent.com/49507795/189751362-6a44ce54-8aa5-4862-af38-430f58ba0b60.png)

**Comment by aliasatp** [comment]
> ![image](https://user-images.githubusercontent.com/49507795/189751027-e3e8a8ef-f40c-431e-a5fb-f45f467a4d11.png) ![image](https://user-images.githubusercontent.com/49507795/189751362-6a44ce54-8aa5-4862-af38-430f58ba0b60.png)

Which version are you using? 3.26.2 solved this issue for me

**Comment by nicogodet** [comment]
Please update to 3.26.3
If it still occurs, I will re-open
