### ISSUE TITLE
Topology Checker Plugin Not Working Properly

### ISSUE THREAD

**Issue by Vijayguptag339** [qgis/QGIS#49482]
### What is the bug or the crash?

Topology Checker Plugin Not Working Properly, Whenever we are Running Topology Checker like 'Must Not Overlap', it is not showing all the overlaps in the Whole Layer.

and also where there is no overlap of feature, it reflect as error in some location

### Steps to reproduce the issue

Topology Checker Plugin Not Working Properly, Whenever we are Running Topology Checker like 'Must Not Overlap', it is not showing all the overlaps in the Whole Layer.

and also where there is no overlap of feature, it reflect as error in some location

### Versions

version of QGIS is 3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you share your data and add details about settings ( used to check topology ?

Can you illustrate what you obtain and what it should be ?

**Comment by Vijayguptag339** [comment]
Find The attached Image Where Topology Rule like 'Must Not Overlap', it is detect all the overla
![Untitled](https://user-images.githubusercontent.com/98526036/181223196-82e099a6-508c-44f4-b116-6ff441d3ec8e.png)
p

**Comment by Vijayguptag339** [comment]
> Can you share your data and add details about settings used to check topology ?
> 
> Can you illustrate what you obtain and what it should be ?
![Untitled](https://user-images.githubusercontent.com/98526036/181227573-3c553687-5017-4797-b2f0-b74fbc840a3f.png)

find The attached Image Where Topology Rule like 'Must Not Overlap', it does not detect all the overlap

**Comment by gioman** [comment]
> find The attached Image Where Topology Rule like 'Must Not Overlap', it does not detect all the overlap

@Vijayguptag339 you must attach a sample dataset, the screenshot is not enough.
