### ISSUE TITLE
Managing Styles. Maybe to many changes at once.

### ISSUE THREAD

**Issue by AntonioManuel87** [qgis/QGIS#49486]
## User Feedback

Managing Styles. Maybe to many changes at once.

## Report Details

**Crash ID**: [fe19da7dc84d2d02fabaee01c5f83852a44969a9](https://github.com/qgis/QGIS/search?q=fe19da7dc84d2d02fabaee01c5f83852a44969a9&type=Issues)

**Stack Trace**
<pre>
QPaintDevice::logicalDpiY :
QgsSvgMarkerSymbolLayer::QgsSvgMarkerSymbolLayer :
QgsTextRenderer::drawBuffer :
QgsTextRenderer::drawTextInternalHorizontal :
QgsTextRenderer::drawTextInternal :
QgsTextRenderer::drawText :
QgsTextPreview::paintEvent :
QWidget::event :
QFrame::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QApplication::windowIcon :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QMetaObject::activate :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Z�rich
QGIS code revision: 735cc85be9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

.

### Versions

.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Pedro-Murteira** [comment]
@AntonioManuel87 ccan you share the dataset from which the crash occurred?

**Comment by AntonioManuel87** [comment]
> @AntonioManuel87 can you share the dataset from which the crash occurred?

Is was a simple line shapefile that I created at the moment with only four features. No big deal. I just configure the style as arrows and then change a few more configurations and I think it crash in Labels, Placement dialogue box.

I hope it help.

**Comment by roya0045** [comment]
3.18 isn't supported anymore regardless.

**Comment by gioman** [comment]
> QGIS Version: 3.18.3-Z�rich

@AntonioManuel87 you must upgrade to 3.22 or 3.26 and try with a new QGIS profile.

**Comment by roya0045** [comment]
> > QGIS Version: 3.18.3-Z�rich
> 
> @AntonioManuel87 you must upgrade to 3.22 or 3.26 and try with a new QGIS profile.

Glad to see you back Gio, was worried I wouldn't see you around anymore.

**Comment by gioman** [comment]
> Glad to see you back Gio, was worried I wouldn't see you around anymore.

@roya0045 thanks! I had some personal matter to take care of, and it took a while to get back in track.
