### ISSUE TITLE
3.22.9-Białowieża Nested legend no longer working

### ISSUE THREAD

**Issue by Reserl5** [qgis/QGIS#49487]
### What is the bug or the crash?

In the prior version, I could build 'nested' legends in layer properties > Symbology. I saw them in the layer Properties window and in the table of layers on the left. After updating, I can still build a nested legend in Layer Properties, but that does not change the legend in the table of layers.
Now: 
![image](https://user-images.githubusercontent.com/110105902/181251820-b479e8df-dd1b-40c4-90c6-dd7b9f94b692.png)

Prior: 
![image](https://user-images.githubusercontent.com/110105902/181252005-2360f8a4-78e8-4f1a-976a-267ccf6803b5.png)

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/110105902/181252234-b7f0ae90-2d6b-4547-9f19-5c30a1fbbd8c.png)

This was working in the older version, but no longer

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.9-Białowieża
-- | --

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@Reserl5 there are no steps to replicate in your description, so one is left to wonder if this is a about the "refine selected rules" option in the rule based renderer. If yes then it seems to work fine here on 3.26.1 on Windows 10.

**Comment by gioman** [comment]
Also on 3.22.9 (ok).
