### ISSUE TITLE
QGIS Keep crashing when I try to add or edit polygon, point, or line features

### ISSUE THREAD

**Issue by pichaell** [qgis/QGIS#49480]
### What is the bug or the crash?

I am currently running QGIS desktop 3.26.1 and am having issues every time I click the "add line feature" in the digitizing toolbar. This occurs when I am working with a new shapefile layer, as well as trying to edit and create lines on existing data layers. I will click toggle editing and then try to add line feature and I get the error "Add feature: cannot capture a shape without a shape tool defined". I get this error immediately after clicking the add line (or point or polygon) feature button in the toolbar, and once I click away from the layer it causes QGIS to crash.

I am doing the exact same thing that had previously worked for me for weeks, and now for some reason it keeps causing QGIS to crash. I have tried downloading the most recent version of QGIS, as well as saving the shapefiles as geopkg's; neither of these have helped the issue. I have also made a new user profile, this fixes this issue temporarily but overtime the bug comes back and begins to crash my QGIS session again. 

One thing I did before the start of getting this error was add the "Advanced Digitizing Panel" and "Advanced Digitizing Toolbar" to my original user profile, but I'm not sure that would cause this error and QGIS to crash.

### Steps to reproduce the issue

Open QGIS, add data to map, create a new geopackage polygon (or line, or point) layer, click toggle edit, click add polygon feature, click onto map and get the error. 

### Versions

3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![Screenshot 2022-07-25 180827](https://user-images.githubusercontent.com/110050987/181153454-e99708eb-44a6-446c-9752-42cc6003a831.png)

**Comment by nicogodet** [comment]
As I do your steps to reproduce every days without crash, it might be a more specific steps that cause the crash.

Try with a new profile et do your steps to reproduce.
If it requires more steps to crash QGIS, please tell us.

**Comment by agiudiceandrea** [comment]
See also (probably from the same user): https://gis.stackexchange.com/questions/436872/qgis-crashes-every-time-i-click-add-line-feature-in-the-digitizing-toolbar
