### ISSUE TITLE
QGIS crash when building on Linux with mingw64

### ISSUE THREAD

**Issue by sirtimrod** [qgis/QGIS#49489]
### What is the bug or the crash?

I'm trying to build QGIS from source on Fedora using the ms-windows/mingw/build.sh script. But at 71% the assembly crashes. What could be the problem?

![изображение](https://user-images.githubusercontent.com/66429509/181272899-eda2edb4-c027-427e-a0fe-a633b190b0f5.png)

![изображение](https://user-images.githubusercontent.com/66429509/181273192-f6466912-037d-4019-a9af-4d37fcd46889.png)

### Steps to reproduce the issue

1. Download QGIS source code on Fedora
2. Unzip
3. Install required packages via ms-windows/mingw/mingwdeps.sh script
4. Install yarn
5. Run build script ms-windows/mingw/build.sh
6. Wait...
7. Get crashed at 71%

### Versions

QGIS - 3.26.0
Yarn - 1.22.19
Fedora - Linux fedora 5.17.5-300.fc36.x86_64

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@sirtimrod when building from source you should ask in the developers mailing list fisrt, rather than assuming is a bug in the code.

**Comment by sirtimrod** [comment]
@gioman thnx, I'll try
