### ISSUE TITLE
Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method 

### ISSUE THREAD

**Issue by YinSun0** [qgis/QGIS#49492]
### What is the bug or the crash?

I recently installed QGIS 3.26.1-Buenos Aires. Every time I open QGIS, an error message is displayed, saying:

> Couldn't load plugin 'MetaSearch' due to an error when calling its classFactory() method 
> 
> ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py) 
> Traceback (most recent call last):
>   File "/app/share/qgis/python/qgis/utils.py", line 423, in _startPlugin
>     plugins[packageName] = package.classFactory(iface)
>   File "/app/share/qgis/python/plugins/MetaSearch/__init__.py", line 29, in classFactory
>     from MetaSearch.plugin import MetaSearchPlugin
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/share/qgis/python/plugins/MetaSearch/plugin.py", line 34, in 
>     from MetaSearch.dialogs.maindialog import MetaSearchDialog
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 48, in 
>     from MetaSearch.dialogs.manageconnectionsdialog import ManageConnectionsDialog
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/share/qgis/python/plugins/MetaSearch/dialogs/manageconnectionsdialog.py", line 35, in 
>     from MetaSearch.util import (get_connections_from_file, get_ui_class,
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/share/qgis/python/plugins/MetaSearch/util.py", line 38, in 
>     from jinja2 import Environment, FileSystemLoader
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/lib/python3.9/site-packages/jinja2/__init__.py", line 12, in 
>     from .environment import Environment
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/lib/python3.9/site-packages/jinja2/environment.py", line 25, in 
>     from .defaults import BLOCK_END_STRING
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/lib/python3.9/site-packages/jinja2/defaults.py", line 3, in 
>     from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
>   File "/app/share/qgis/python/qgis/utils.py", line 888, in _import
>     mod = _builtin_import(name, globals, locals, fromlist, level)
>   File "/app/lib/python3.9/site-packages/jinja2/filters.py", line 13, in 
>     from markupsafe import soft_unicode
> ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/usr/lib/python3.9/site-packages/markupsafe/__init__.py)
> 
> 
> Python version: 3.9.9 (main, Nov 10 2011, 15:00:00) [GCC 11.3.0] 
> QGIS version: 3.26.1-Buenos Aires Buenos Aires, exported

### Steps to reproduce the issue

The problem happens when I simply open QGIS.

### Versions

3.26.1-Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Looks like a local issue 

Os ? Repo used for QGIS ? Etc...

**Comment by agiudiceandrea** [comment]
This is an issue specific to the Flatpak QGIS package. See: https://github.com/flathub/org.qgis.qgis/issues/174.
It has been fixed some months ago but now it occurs again.
@YinSun0, as a workaround, if you don't use the MetaSearch core plugin, then you can disable it in QGIS via Plugins->Manage and Install Plugins..., so the error message will no longer be displayed.

**Comment by YinSun0** [comment]
@agiudiceandrea Indeed I installed QGIS via Flatpak and unfortunately I do need to use the MetaSearch core plugin.

@nicogodet Ubuntu 21.04, installed QGIS 3.26.1 via Flatpak.

**Comment by agiudiceandrea** [comment]
> @agiudiceandrea Indeed I installed QGIS via Flatpak and unfortunately I do need to use the MetaSearch core plugin.
> 
> @nicogodet Ubuntu 21.04, installed QGIS 3.26.1 via Flatpak.

QGIS 3.26.1 is available for Ubuntu 21.04 Hirsute Hippo via the official QGIS repository: please see https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu for instructions to install it.

**Comment by agiudiceandrea** [comment]
@YinSun0, if you have fixed the issue installing QGIS using the official QGIS repository, please close this issue report as it is not related to QGIS itself but with the flatpak installation procedure.

**Comment by agiudiceandrea** [comment]
This issue has been fixed with https://github.com/flathub/org.qgis.qgis/pull/215 and https://github.com/flathub/org.qgis.qgis/pull/214.
