### ISSUE TITLE
Raster to vector tools malfunction in v 3.26.1

### ISSUE THREAD

**Issue by dalyk2** [qgis/QGIS#49490]
### What is the bug or the crash?

Using raster tile index tool or raster to vector with ascii file as input fails to output a spatial file when selecting "save to temporary file". Output tables are created but lacking spatial definition. 

When select an output file location it works ok. Checked version 3.16 and it works ok to temporary file. 

Similar issue when checked 'raster to vector' (rasterise)

[manning.zip](https://github.com/qgis/QGIS/files/9200132/manning.zip)

### Steps to reproduce the issue

Raster>>Misc>>Tile Index>>choose ascii grid and output to temporary file

Same approach for rasterise tool

### Versions

3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by dalyk2** [comment]
Also checked with latest LTR v 3.22.9 and apparent bug is not present.

**Comment by dalyk2** [comment]
I have retried by creating a new user profile and the issue is resolved. So something within my default user profile has caused the issue it seems.

**Comment by Pedro-Murteira** [comment]
@dalyk2 it is probably plugin-related, we can close for now, and reopen if necessary in the future.

**Comment by dalyk2** [comment]
ok thanks
