### ISSUE TITLE
QGIS 3.22 Unable to add feature when Joining attributes from SQL result

### ISSUE THREAD

**Issue by webtutorial101-2021** [qgis/QGIS#49499]
### What is the bug or the crash?

hi!

I just want to report that in QGIS 3.22 I was not able to save a feature to my layer with attributes joined.
The attributes I joined is from result of my sql query from postgres.

This is my query string "SELECT id, concat(firstname, ', ' , lastname) FROM database. (using DB Manager) 
I added the result as layer then join it to a polygon layer with reference to the "id" column.

The problem now is when I add a feature to my polygon layer, the "OK" button is disabled.

I did not encountered this in QGIS 3.4.12

![select](https://user-images.githubusercontent.com/81403987/181401135-406015a1-b20f-48cc-bf54-a71824a49e65.PNG)
![join](https://user-images.githubusercontent.com/81403987/181401345-3ef6c7e8-965f-432a-a3c7-e2c8e43feb29.PNG)
![add_feature](https://user-images.githubusercontent.com/81403987/181401436-06a325b7-fc43-479f-aa30-827c9a0b03b6.PNG)

### Steps to reproduce the issue

see images

### Versions

QGIS 3.22.5

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Query layers (layers based on a SQL statement) are read only.
