### ISSUE TITLE
data type is  int64 can't show

### ISSUE THREAD

**Issue by xcroot** [qgis/QGIS#49509]
### What is the bug or the crash?

when my database data is bigint and the value is very big  like this:
![image](https://user-images.githubusercontent.com/16606884/181719727-28abd45b-baec-43d7-851b-57ad96cad96d.png)
when they opne in qgis the data is error and show the same data
![image](https://user-images.githubusercontent.com/16606884/181719644-eb0351e4-9848-4d3e-a79b-b8599e395d9b.png)

### Steps to reproduce the issue

open the sq3 data

### Versions

3.22.9

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@xcroot which database? Can you provide a sample (dump) of the data?
