### ISSUE TITLE
QGIS 3.27 crashing on "Setting up the GUI"

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#49507]
### What is the bug or the crash?

When I start QGIS 3.27 by clicking the icon in the start menu, QGIS crashes as soon as it gets to *Setting up the GUI*. 

The crash-handler doesn't provide a stack trace or a report. 

- Running QGIS 3.27 using the `Command Prompt` everything works fine. 
- Using the `Command Prompt` to navigate to my `Documents` folder `C:\Users\MY-USER\Documents` and run QGIS 3.27 from there crashes. The QGIS 3.27 shortcut refers to running the file `C:\osgeo4w\bin\qgis-dev-bin.exe` starting in my documents folder, which is why I tried to start it manually from this folder.

So what is the difference between starting QGIS 3.27 from my documents folder and a random folder?

I have installed QGIS 3.27 using OSGeo4W.

### Steps to reproduce the issue

1. Open a `Command Prompt`
2. Navigate to `C:\Users\YOUR-USER`
3. Run `C:\Osgeo4w\bin\qgis-dev-bin.exe`
4. Expect QGIS to start normally.
5. Navigate to `C:\Users\YOUR-USER\Documents`
6. Run `C:\Osgeo4w\bin\qgis-dev-bin.exe`
7. Expect QGIS to crash.

### Versions

QGIS Info
QGIS Version: 3.27.0-Master
QGIS code revision: f5487ecc6f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0dev-030ff40cf8
Running against GDAL: 3.6.0dev-36c083fbfd

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19042

**Comment by nicogodet** [comment]
Did you try with a new profile ?

**Comment by chau-intl** [comment]
> Did you try with a new profile ?

I have created a new profile and made it the default profile by editing `profiles.ini` but QGIS 3.27 still crashes.

**Comment by nicogodet** [comment]
Can't reproduce here

**Comment by agiudiceandrea** [comment]
Do you have any other QGIS version (qgis or qgis-ltr) installed using the OSGeo4W Network Installer? Do also such QGIS versions behave like qgis-dev? What files are in your Documents folder? Does the issue occur also if you remove all the files from the Documents folder?
Anyway, I think this issue is related to the OSGeo4W packaging system and not to QGIS itself, so it would be better to report this issue at https://trac.osgeo.org/osgeo4w/.

**Comment by chau-intl** [comment]
I have 3.22.9, 3.26.1, 3.27 (from now) and all from OSGeo (the new installer). Only 3.27 crashes on start up.

About the contents of my Documents folder it seems you are on the right track. I have a file with non-ASCII letters (Danish letters like æ, ø and å) in the filename and indeed when moving this file away from my Documents folder, QGIS 3.27 starts without issues.

**Comment by agiudiceandrea** [comment]
> I have a file with non-ASCII letters (Danish letters like æ, ø and å) in the filename and indeed when moving this file away from my Documents folder, QGIS 3.27 starts without issues

Good to know! I can replicate the issue also with non-ASCII Italian accented letters (è, é, ...) in files or folders names in the user "Documents" directory.
I've reported the issue also at https://trac.osgeo.org/osgeo4w/ticket/759.

**Comment by chau-intl** [comment]
@agiudiceandrea, thanks for checking and confirming. 

Just curious why do you suspect the issue to be with the packaging and not with QGIS it self?

**Comment by agiudiceandrea** [comment]
> Just curious why do you suspect the issue to be with the packaging and not with QGIS it self?

It could indeed be in the code of QGIS itself (since qgis-dev crashes, while qgis and qgis-ltr not).
Anyway, the issue would not occur if the shortcut link to launch QGIS, created during the OSGeo4W installation procedure, didn't contain the "Documents" user folder path in the "Start in" properties but a safer folder like the actual OSGeo4W installation folder (which doesn't contain any file with non-ASCII characters).

**Comment by nicogodet** [comment]
By the way, in https://trac.osgeo.org/osgeo4w/ticket/728, pdal python bindings does not work if QGIS is started in another folder.
Not sure how this is related.

As I maintain QGIS in my company with a custom OSGeo4W package, I had to change shortcup creation.
```bash
xxmklink "%OSGEO4W_STARTMENU%\%APPNAME%.lnk" "%OSGEO4W_ROOT%\bin\qgis-ltr.bat" "" "" "" 1 "%OSGEO4W_ROOT%\apps\qgis-ltr\icons\QGIS.ico"
```
compared to 
```bash
xxmklink "%OSGEO4W_STARTMENU%\%APPNAME%.lnk" "%OSGEO4W_ROOT%\bin\@package@-bin.exe" "" "%DOCUMENTS%"
```

**Comment by agiudiceandrea** [comment]
@chau-intl @EranGeo, the issue was fixed in OSGeo4W. You can fix the issue just updating the pdal and pdal-libs packages to version 2.3-8.
