### ISSUE TITLE
QgsDistanceArcProperter() is not working.

### ISSUE THREAD

**Issue by Avijit009** [qgis/QGIS#49519]
### What is the bug or the crash?

My code:

`vl = network_layer
director = QgsVectorLayerDirector( vl, -1, '', '', '', 3 )
properter = QgsDistanceArcProperter()
director.addProperter( properter )
crs = vl.crs()
builder = QgsGraphBuilder( crs )`

### Steps to reproduce the issue

`Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "<string>", line 66, in <module>
NameError: name 'QgsDistanceArcProperter' is not defined`

### Versions

qgis 3.22.8 ltr
python 3.9.10.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

How can I solve this problem?

**Comment by nicogodet** [comment]
According to https://api.qgis.org/api/api_break.html, it has been moved to QgsDistanceStrategy in 3.XX

**Comment by alexbruy** [comment]
Please check API docs, this class was renamed.
