### ISSUE TITLE
Atlas_pagename or other related atlas data in labels expression

### ISSUE THREAD

**Issue by sasuandrei** [qgis/QGIS#49511]
### What is the bug or the crash?

In the Properties-> Labels -> Text -> Size -> Edit expression when inserting @atlas_pagename is returning blank/nothing.
![image](https://user-images.githubusercontent.com/26470340/181740542-5fc6f69c-3f2d-4ad9-8a97-df72dad695be.png)

IN Symbology -> Opacity -> Edit expression @atlas_pagename is returning correct data (name of page).
![image](https://user-images.githubusercontent.com/26470340/181740455-61a98ddf-7af5-4d00-bd67-224a0ffbf125.png)

### Steps to reproduce the issue

1. Right Click Properties on layer
2. Symbology - > edit opacity by expression 
3. Insert @atlas_pagename - return a value
4. Go to Labels -> Text-> size-> edit size by expression
5. Insert @atlas_pagename - returns nothing (empty)

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I just did some tests following the directions on the label and opacity: everything works fine for me.
Small note: the atlas must be activated via the Preview Atlas icon

## OSGeo4W64 v2 QGIS 3.26.1 Win 10 PRO

**Comment by sasuandrei** [comment]
I have 3.26.0
The atlas was activated. I will install 3.26.1 to see how it goes. And I will give a feedback

**Comment by sasuandrei** [comment]
I have installed 3.26.1 and still not working.
I've forgot to mention that I have 2 layouts. In future I will have more (3 layouts). 
Thank you
![image](https://user-images.githubusercontent.com/26470340/181993167-9fa73edd-5469-4da5-9ca3-b1d12bacc5f8.png)

**Comment by pigreco** [comment]
it works for me, I attach videos

https://user-images.githubusercontent.com/7631137/182014334-2713f213-1d5a-4dd8-b26d-5bca4214aa35.mp4

**Comment by sasuandrei** [comment]
In your video it doesn't retrieve anything. Watch at preview. At symbology shows 20 and at label it doesn't show anything.

**Comment by pigreco** [comment]
> In your video it doesn't retrieve anything. Watch at preview. At symbology shows 20 and at label it doesn't show anything.

You don't have to rely on the field calculator preview, because it often doesn't work well, you have to see the result, you have to see if it works and by me it works.

**Comment by sasuandrei** [comment]
Well, I wanted to retrieve the width of the geometry from atlas. To automatically scale the text. Like this  CASE WHEN bounds_width(geometry(get_feature_by_id('Planse',@atlas_pagename)))=1808 THEN 12
 ELSE 6
 END
And the result is always 6.
So the function doesn't work. Thank you

**Comment by pigreco** [comment]
@sasuandrei 
Your expression works for me, I advise you to double check the data

**Comment by sasuandrei** [comment]
And it gives the right result? It works for me too.. But the result is bad because it doesn't retrieve atlas page name value. So if I want to filter the data I can't because @atlas_pagename is empty. I don't think it's working for you. Are you a developer for qgis? Did you triple checked the condition?

**Comment by DelazJ** [comment]
@sasuandrei can you share a minimalist copy of your project file and data? I'm questioned by this expression```get_feature_by_id('Planse',@atlas_pagename)```. What is it supposed to retrieve? How is atlas_pagename defined?
> Are you a developer for qgis?

With all due respect, I don't get the relevance of this question. QGIS (speaking of the coding part) is made by people who write the code, but also by numerous people that do not write codes but report bugs (what you are doing), check and test bugs so that only actual bugs are retained and to save time for developers, test fixes and features afterwards so that new releases are free from bugs (as far as possible). I don't remember if @pigreco made code but I would classify him in the other groups. Does that change anything form your perspective and the question raised in this bug report?

**Comment by sasuandrei** [comment]
I know is made by people who write code. I was just curios. Sorry if it is offending. 
About the expressions - > try this expression 
`bounds_width(geometry(get_feature_by_id('Planse',@atlas_pagename)))`
I want to retrieve the width of atlas_pagename. Because I will have 2 types of width. Based on this value i want the label to be bigger or smaller. 
So the expression above for Symbology section it returns 1808 which is correct.
![image](https://user-images.githubusercontent.com/26470340/182025291-86db3a8e-7223-4875-aed3-430071920338.png)

But, for label part:
![image](https://user-images.githubusercontent.com/26470340/182025331-99b5fa0f-8f56-4104-b344-4086c0a799e8.png)
is null.

IN this case 
```
CASE WHEN bounds_width(geometry(get_feature_by_id('Planse',@atlas_pagename)))=1808 THEN 12
 ELSE 6
 END
```
It should return 12. For symbology is 12. But for labels is returning 6, which is not correct - because the width is 1808. I will attach
[qgis bug 2.zip](https://github.com/qgis/QGIS/files/9228821/qgis.bug.2.zip)
a project with some layers and "Planse" layer which is the atlas layer. 
Sorry if the question about pigreco has offended anyone or it was offending. 

And the syntax get_Feature_by_id('Planse',@atlas_pagename) should retreive the ID feature of 'Planse' where is equal with the @atlas_pagename. So if you have @atlas_pagename=3 , it should result the third feature of 'PLanse' layer.
In this case: `bounds_width(geometry(get_feature_by_id('Planse',@atlas_pagename)))` i want to retrieve the width of feature. 

Thank you

**Comment by pigreco** [comment]
I used your project data:
1. for me it works (in the preview I see 6, but it applies value 12, because in the preview it does not evaluate the variable correctly, but in execution it evaluates it correctly)
2. I suggest you use the expression:
```
CASE WHEN
bounds_width(@atlas_geometry)= 1808 THEN 12
ELSE 0
END
```

4. As mentioned before, the preview does not always return the correct or expected values, so you need to test.
![image](https://user-images.githubusercontent.com/7631137/182028503-43e152ee-b44b-46a2-bd43-78d30f4ae3c7.png)


> Are you a developer for qgis?

No, but I use a lot of print composer and atlas.

**Comment by sasuandrei** [comment]
Ok. Thanks for answer. I will then close this. Thanks again

**Comment by sasuandrei** [comment]
In that case situation It showed always 6, not 12 as it should.

**Comment by sasuandrei** [comment]
The preview line can show wrong data but execution is right.
