### ISSUE TITLE
QtWebEngineView import error in python console 

### ISSUE THREAD

**Issue by jbp35** [qgis/QGIS#49512]
### What is the bug or the crash?

Trying to import QtWebEngineView in QGIS python console causes the following error:

`ImportError: QtWebEngineWidgets must be imported before a QCoreApplication instance is created or Qt::AA_ShareOpenGLContexts must be set to true`

### Steps to reproduce the issue

In python console, enter the following command:
`from PyQt5.QtWebEngineWidgets import QWebEngineView`

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have been able to fix this issue and use QtWebEngineView in a plugin by doing the following: 

**1) Fix a typo in "src/app/main.cpp" line 923:** 

"QT_OS_WIN" should be replaced by "Q_OS_WIN" without a T or removed entirely.

This typo prevents Qt::AA_ShareOpenGLContexts to be set to true as the test never pass.

I already created a PR to fix this but didn't get a review for it:
https://github.com/qgis/QGIS/pull/47873/commits/f27f7cf25258532aa979c4d5ceb27233a9544fdc#diff-214bd4636579818fc26242a65aee285dbdca02666343ff789ba776caae1ddc9a

**2) Upgrading manually PyQtWebEngine python binding to version 5.15.6**

Currently, OSGEO4W installs version 5.15.5 which dose not take into account Qt::AA_ShareOpenGLContexts flag. This has been fixed in version 5.15.6.

To try it out, in command line run the following command to upgrade manually:
`C:\OSGeo4W\apps\Python39\Scripts\pip3.exe install PyQtWebEngine --upgrade`

It would be great to fix this issue, as it opens a lot of possibilities to develop plugins with modern browser capabilities (QtWebEngine with QT 5.15 is based on chronium 83 which is much more recent than QtWebKit). Also it is quite trivial to resolve this issue...

**Comment by nyalldawson** [comment]
@jbp35 

Thanks for re-raising this issue!

> This has been fixed in version 5.15.6.

Have you got some links regarding this? I've searched around and can't find any release notes or other documentation regarding the .6 changes 😱

**Comment by jbp35** [comment]
> @jbp35
> 
> Thanks for re-raising this issue!
> 
> > This has been fixed in version 5.15.6.
> 
> Have you got some links regarding this? I've searched around and can't find any release notes or other documentation regarding the .6 changes 😱

Here is the changelog of PyQtWebEngine  5.15.6:
[ChangeLog.txt](https://github.com/qgis/QGIS/files/9225470/ChangeLog.txt)

The relevant change is the latest one:

```
2022-03-15  Phil Thompson  <phil@riverbankcomputing.com>

	* NEWS, PyQtWebEngine.msp:
	Allow Qt.AA_ShareOpenGLContexts to be specified before a
	QCoreApplication is created to allow PyQtWebEngineWidgets to be
	imported.
	[140468b2e1b2] [5.15.6] <5.15-maint>
```

I have been in touch directly with the author of pyqt to address this. Version .5 will throw the following error when initialized if a QCoreApplication already exists: 

```
ImportError "QtWebEngineWidgets must be imported before a 
> QCoreApplication instance is created"
```

The only difference with version .6 is that it checks if Qt::AA_ShareOpenGLContexts is set to true and do not throw the previous error in that case.

**Comment by jbp35** [comment]
@nyalldawson thank you for the review. Where should I report this issue to upgrade PyQtWebEngine module packaged in OSGEO4W?

**Comment by nyalldawson** [comment]
@jbp35 

That would be at https://trac.osgeo.org/osgeo4w/report

**Comment by nyalldawson** [comment]
Note: I had to revert the AA_ShareOpenGLContexts flag in https://github.com/qgis/QGIS/pull/49888 -- this breaks QGIS 3D. It seems webengine and Qt 3d are currently mutually exclusive. See details in :

- https://interest.qt-project.narkive.com/GYwuMDac/qwebengineview-qsurfaceformat-errors-in-console
- https://bugreports.qt.io/browse/QTBUG-60614
- https://bugreports.qt.io/browse/QTBUG-60605

**Comment by disarticulate** [comment]
On Windows 10
```

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b12f
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
```
I just get
```
from PyQt5 import QtCore, QtWebEngineWidgets
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
ImportError: cannot import name 'QtWebEngineWidgets' from 'PyQt5' (C:\PROGRA~1\QGIS32~1.2\apps\Python39\lib\site-packages\PyQt5\__init__.py)
```

**Comment by nyalldawson** [comment]
@disarticulate 

This is expected -- it's currently completely **impossible** to use both QtWebEngine AND Qt 3D in the one application, and unfortunately QGIS 3D is based on Qt 3D. So there's no way to use webengine at ALL in QGIS right now.

**Comment by disarticulate** [comment]
Is it frowned upon to install the required dependencies for something like cefPython: https://github.com/cztomczak/cefpython

I've been pondering a plugin that provides services via a PWA, using things like webrtc for universal service/portal.
