### ISSUE TITLE
Two consecutive crashes while working in the layout window

### ISSUE THREAD

**Issue by unaltroaccountchepalle** [qgis/QGIS#49521]
### What is the bug or the crash?

QGIS crashed while working in the layout window, deleting some items from a subgroup that I previously copyied and pasted in place, toggling the visibility check.
It is the second time that QGIS do it consecutively.
Crash id: [4ce4d57f67af89fd66fe18d392ada96ef5ee6bc2]

Stack trace:
QgsLayerTreeModel::node2index :
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayoutLegendWidget::mRemoveToolButton_clicked :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

QGIS crashed two times consecutively while trying the described operation, the third time it worked, a lucky try!

### Versions

QGIS Info
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pigreco** [comment]
@unaltroaccountchepalle 
You have to describe the problem a little better, and share a minimal project with which to replicate the problem, maybe write the steps, step by step, to replicate the problem.

**Comment by unaltroaccountchepalle** [comment]
@pigreco Thanks for the attention, however as I wrote the third time I tried the thing went on, so I think it's not replicable.
Next time I'll try to describe better the problem.
