### ISSUE TITLE
Can not toggle between "shape digitization tool" (circle, square, etc) and the standard "Add polygon feature"

### ISSUE THREAD

**Issue by Nicholson7979** [qgis/QGIS#49541]
### What is the bug or the crash?

Can not toggle between "shape digitization tool" (circle, square, etc) and the standard "Add polygon feature". After selecting one of the shape digitization tools the app can not revert back to using the freeform "add polygon feature". I had to install earlier version 3.22.9

### Steps to reproduce the issue

Create a circle using the shape digitization panel and select the freeform polygon tool. (even after switching edit mode on/off)

### Versions

3.26.0 and 3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I confirm problem.

## OSGeo4W64 v2 QGIS 3.26.1 Win 10 PRO

**Comment by liuxsdev** [comment]
Same problem in QGIS 3.26.1

**Comment by pigreco** [comment]
I confirm problem.

## OSGeo4W64 v2 QGIS 3.26.3 Win 10 PRO

**Comment by agiudiceandrea** [comment]
It seems to me this is related to https://github.com/qgis/QGIS/pull/46687,

**Comment by DelazJ** [comment]
I'm failing to understand the issue. The digitizing tools have been refactored and digitize shape is one of the methods of drawing polygons (using "Add polygon feature" tool) along with curve, segment and freehand methods. It is a sub option of the "add polygon" so you can't expect to "switch from one to the other". Please give a read to https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#adding-features and https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#geometry-editing-techniques
I think here you just need to switch to "Digitize with segment" 
![image](https://user-images.githubusercontent.com/7983394/193418858-83b2c741-c83d-4d1b-a8e4-bc22ec2295c8.png)

**Comment by pigreco** [comment]
I confirm that it works, you need to switch from Digitize Shape to Digitize Segment.
Thank you @DelazJ 
![2022-10-01_18h38_25](https://user-images.githubusercontent.com/7631137/193419408-c758c56d-61d7-4905-b3c4-6b679b0ce8af.gif)

**Comment by agiudiceandrea** [comment]
@DelazJ, I think this is a bug. Please consider this scenario: in a new QGIS user profile the "Digitizing" toolbar is enabled by default while the "Shape Digitizing" and the "Advanced Digitizing" toolbars are not enabled, the uses starts the editing of a polygon vector layer:

- pre https://github.com/qgis/QGIS/pull/46687:
- - digitize a "normal" polygon feature: click on the "Add Polygon Feature" button in the "Digitizing" toolbar
- - digitize a "shape": activate the "Shape Digitizing" toolbar and then click on one of the shapes buttons in such toolbar
- - digitize a "normal" polygon feature: click on the "Add Polygon Feature" button in the "Digitizing" toolbar

- post https://github.com/qgis/QGIS/pull/46687: 
- - digitize a "normal" polygon feature: click on the "Add Polygon Feature" button in the "Digitizing" toolbar
- - digitize a "shape": activate the "Shape Digitizing" toolbar and then click on one of the shapes buttons in such toolbar
- - digitize a "normal" polygon feature: you now - not so obviously - need to activate another toolbar, the "Advanced Digitizing" toolbar, and then you need to click on the "Digitize Shape" button and then select the "Digitize with Lines" option.

It seems to me the post https://github.com/qgis/QGIS/pull/46687 behaviour is a GUI/UX bug: to use the "Shape Digitizing" methods you need to only use the "Shape Digitizing" toolbar; but to deactivate such method and return to the normal "Digitizing" method then the "Digitizing" and "Shape Digitizing" toolbars are not enough an you need to also activate a third toolbar.

I think that some possible solutions would be:
- put the "Digitize Shape" / "Digitize with Lines" / ... button also in the "Shape Digitizing" toolbar

OR
- merge the "Shape Digitizing" toolbar and the "Advanced Digitizing" toolbar

OR
- mimic the previous behavior and deactivate the "Add Polygon Feature" button in the "Digitize" toolbar when the user clicks on one of the shapes buttons in the "Shape Digitizing" toolbar so he can again click on the "Add Polygon Feature" button in the "Digitize" toolbar when he wants to return to the normal digitizing method

**Comment by 3nids** [comment]
Some other approaches would be to:

- **D** make the advanced digitizing toolbar visible as soon as you digitize a shape
- **E** like A, but only show it if the advanced toolbar is not shown
- **F** move the digitizing mode button to the simple digitizing toolbar

Regarding C, I personally don't like it:
* the checking/unchecking of the button  is automatically done by map canvas on the button (action) set for this map tool (this will require some specific code)
* it is based on the specific case of the add feature tool (which button/action is not in the advanced digitizing toolbar)

**A**: I'm -0: while it makes a lot of sense to have this it will make the UX too crowded. 

My personal preference would be:

1. **B** (merging the 2 toolbars): this is the simplest solution (it might require a bit of work to have the actions correctly registered, so one could still remove the button using the customization tool)
2. **E** (move the mode button from advanced toolbar to shape tool bar when required): a bit of code to move the action, but it might be the best in terms of UX.

I'd like to have some UX experts here for another opinion. ping @nirvn

**Comment by agiudiceandrea** [comment]
@3nids, thanks for looking at this.
Since we're at it, I think there is also another inconsistency about the "Digitize with curve" method in the "Advanced Digitizing" toolbar and the "Circular string by radius" tool in the "Shape Digitizing" toolbar: they actually seems two quite similar methods/tools to add circular segments, but now they are selectable in two different toolbars.

**Comment by 3nids** [comment]
@agiudiceandrea can you create a new issue for this one?

**Comment by DelazJ** [comment]
@agiudiceandrea @3nids Not sure if/how they overlap, but see #49783 and #49784

**Comment by nirvn** [comment]
I'd vote for the **F** option; IMHO the button would best fit sitting in between the Add {point, line, polygon} feature and the vertex node buttons.

It'd likely feel odd in the shape digitizing toolbar as we have quite a few modes in there that aren't shape-bound. 

As for moving the button around across toolbars based on visibility, I can see it being slightly confusing for newcomers, and a tiny bit harder to properly document.

**Comment by agiudiceandrea** [comment]
@3nids any news on this issue? It's occurring also with QGIS 3.28.0.

**Comment by ddettrick** [comment]
I like option C you click the edit button the line or polygon button and then if you want shapecontrol click on that too. You can then click on shapecontorl to turn it off, if you wish t ohand draw a shape, point or line. Thanks!
