### ISSUE TITLE
Unavailable icon in TOC if use expression with project var

### ISSUE THREAD

**Issue by yellow-sky** [qgis/QGIS#49548]
### What is the bug or the crash?

Small bug with icons in TOC. Vector layer has "SVG Marker" symbol type. URL of SVG file specified as expression.

If expression for path does not contains project vars -> OK.
Example: 
'https://uxwing.com/wp-content/themes/uxwing/download/location-travel-map/' || 'maps-pin-black-icon.svg'

If expression contains project var -> '?' icon in TOK (but correct view on map canvas).
Example: 
@svg_site_url || 'maps-pin-black-icon.svg'

Example project:
[project_var_in_expression.zip](https://github.com/qgis/QGIS/files/9244203/project_var_in_expression.zip)

### Steps to reproduce the issue

Open example project

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.20.3-Odense | QGIS code branch | Release 3.20
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.10.0
Compiled against GDAL/OGR | 3.3.1 | Running against GDAL/OGR | 3.3.3
Compiled against PROJ | 8.1.0.%3.%4 | Running against PROJ | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.2-CAPI-1.14.3
SQLite version | 3.36.0
PostgreSQL client version | 13.4
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | Fedora Linux 35 (KDE Plasma)
  |   |   |  
Active Python plugins | quick_map_servicesQGIS3-getWKTchangeDataSourcegisquick2QuickOSMQuickWKTqtilesplugin_reloaderkartpluginbuilder3gisquick-qgis-plugindb-style-managergis_cloud_publisherTraffic-Viewerbulkvectorexportwithstylegeoflow_connectorprocessingdb_managerMetaSearch

</body></html>QGIS version
3.20.3-Odense
QGIS code branch
[Release 3.20](https://github.com/qgis/QGIS/tree/release-3_20)
Qt version
5.15.2
Python version
3.10.0
Compiled against GDAL/OGR
3.3.1
Running against GDAL/OGR
3.3.3
Compiled against PROJ
8.1.0.%3.%4
Running against PROJ
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.2-CAPI-1.14.3
SQLite version
3.36.0
PostgreSQL client version
13.4
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.11.6
OS version
Fedora Linux 35 (KDE Plasma)

Active Python plugins
quick_map_services
QGIS3-getWKT
changeDataSource
gisquick2
QuickOSM
QuickWKT
qtiles
plugin_reloader
kart
pluginbuilder3
gisquick-qgis-plugin
db-style-manager
gis_cloud_publisher
Traffic-Viewer
bulkvectorexportwithstyle
geoflow_connector
processing
db_manager
MetaSearch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Try with QGIS LTR 3.22.9

**Comment by alexbruy** [comment]
Not reproducible with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc), in both cases a standard icon for downloadable svg is shown.
