### ISSUE TITLE
QGIS Server freeze if project var in expression

### ISSUE THREAD

**Issue by yellow-sky** [qgis/QGIS#49550]
### What is the bug or the crash?

Vector layer has "SVG Marker" symbol type. URL of SVG file specified as expression.

If expression for path does not contains project vars -> OK.
Example:
'https://uxwing.com/wp-content/themes/uxwing/download/location-travel-map/' || 'maps-pin-black-icon.svg'

If expression contains project vars -> qgis server freezes.
Example:
@svg_site_url || 'maps-pin-black-icon.svg'

Example project:
[project_var_in_expression_qgs_server.zip](https://github.com/qgis/QGIS/files/9244493/project_var_in_expression_qgs_server.zip)

### Steps to reproduce the issue

1. Extract example project
2. qgis_mapserver -p ~/tmp/project_var_in_expression_qgs_server.qgs
3. Open in Desctop QGIS url of local QGIS server and add "0 level layer" to project
4. QGIS server freeze

### Versions

OS: Ubuntu 22.04
QGIS Server 3.22.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@yellow-sky I can't replicate the (server) freeze here (using QGIS Server/Apache).

**Comment by gioman** [comment]
> I used qgis_mapserver, not fcgi

sure, I was just pointing that this probably don't apply to all cases, in particular using a web server that is suggested for production purposes. I guess that the title should be improved then.
