### ISSUE TITLE
Conditional Formatting in Print Layout attribute table not working when filtering attribute fields

### ISSUE THREAD

**Issue by Gabriel-Diosan** [qgis/QGIS#49564]
### What is the bug or the crash?

When applying the "Apply layer conditional styling colors" to an attribute table in the print layout, the conditional formatting will not be applied if some of the attributes in the attribute table have been hidden by using the "Select Attributes" window. This was working correctly in previous QGIS versions so it may be a regression.

### Steps to reproduce the issue

1. Apply conditional formatting in an attribute table for a field. In my case the field was "Amend_Status".
2. Insert an attribute table into a print layout and remove some of the attributes using the "Select Attributes" window.
3. Enable the "Apply layer conditional styling colors" for the attribute table.

![QGIS_Screenshot_1](https://user-images.githubusercontent.com/87681737/182760903-c6835290-2db1-49da-a770-1acd2689fd40.png)

4. The conditional formatting is not applied. If no attributes are removed using the "Select Attributes" window, the conditional formatting shows up correctly.

![QGIS_Screenshot_2](https://user-images.githubusercontent.com/87681737/182760962-6504d1ae-76f5-4794-a3bd-2464ce89b6a4.png)

5. I also tested with a different project and noticed similar behaviour except in that instance the conditional formatting would appear or disappear depending on zoom level in the print layout.

### Versions

Tested with the following versions of QGIS and noticed the same behaviour in all versions:

QGIS version | 3.24.3-Tisler | QGIS code revision | cf22b74e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.4.3
PROJ version | 9.0.0
EPSG Registry database version | v10.054 (2022-02-13)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 1809
  |   |   |  
Active Python plugins
DataPlotly | 3.9
GeometryShapes | 0.7
qfieldsync | v4.1.1
qgis_resource_sharing | 0.16.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | fc5faa84bf
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.6.0dev-023d25cf45 | Running against GDAL/OGR | 3.6.0dev-854e6007ab
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 1809
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.27.0-Master
QGIS code revision
[fc5faa84bf](https://github.com/qgis/QGIS/commit/fc5faa84bf)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.0dev-023d25cf45
Running against GDAL/OGR
3.6.0dev-854e6007ab
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1809

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
I have run tests following the directions above, but I cannot reproduce the problem.

Only thing I don't understand is: where is "Select Attributes" in point 2 of the description.

![2022-08-04_09h10_55](https://user-images.githubusercontent.com/7631137/182786113-f1ed3226-1a76-43cb-8a7e-d8299ff65427.gif)

## OSGeo4W64 v2 QGIS dev 286 - code revision fc5faa84bf

![image](https://user-images.githubusercontent.com/7631137/182786931-3898a64a-f729-4471-a3e9-a14589c29a26.png)

**Comment by Gabriel-Diosan** [comment]
@pigreco The Select Attributes window is the window that comes up when you click on the "Attributes" button under the "Main Properties" for the attribute table in the print layout.

I have tested further and the projects that I was using to test seem to be working correctly now...strange. Maybe there was an issue with my setup that has sorted itself out. I think this issue can be closed for now. If I notice it again I can reopen the issue.

Sorry for the noise.
