### ISSUE TITLE
Map composer fails to clip vector layers within map borders while rendering.

### ISSUE THREAD

**Issue by erydit** [qgis/QGIS#49560]
### What is the bug or the crash?

I am trying to render a map with several map elements and large vector layer displayed on them. 
The map composition in the Composer looks as expected:
![expected](https://user-images.githubusercontent.com/25078871/182643324-75b999ce-0c0e-4853-94a4-bfa94feef25b.jpg)

But after rendering in any format (I tried jpg, pdf, tif) it results in a wrong clipped vector parts in the between maps space:
![actual_render](https://user-images.githubusercontent.com/25078871/182643567-f353722e-b0e9-4f4f-b80f-811f49dd7e21.jpeg)
 

### Steps to reproduce the issue

I attached a minimal example with map project and two vector layers:
[example.zip](https://github.com/qgis/QGIS/files/9252754/example.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Версия QGIS | 3.26.1-Buenos Aires | Кодовая ветка QGIS | Release 3.26
-- | -- | -- | --
Версия Qt | 5.15.5
Версия Python | 3.10.5
Версия GDAL/OGR | 3.5.1
Версия PROJ | 9.0.1
Версия базы данных реестра EPSG | v10.064 (2022-05-19)
Версия GEOS | 3.11.0-CAPI-1.17.0
Версия SQLite | 3.39.1
Версия PDAL | 2.4.2
Версия PostgreSQL | unknown
Версия SpatiaLite | 5.0.1
Версия QWT | 6.2.0
Версия QScintilla2 | 2.13.3
Версия ОС | Manjaro Linux
  |   |   |  
Включенные модули Python
processing_saga_nextgen | 0.0.7
processing_r | 3.1.1
valuetool | 3.0.15
OSMDownloader | 1.0.3
SRTM-Downloader | 3.1.17
osminfo | 0.7.1
AcATaMa | 19.11.21b
quick_map_services | 0.19.29
processing_wbt | 1.3.5
maplibrary | 1.2
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>Версия QGIS
3.26.1-Buenos Aires
Кодовая ветка QGIS
[Release 3.26](https://github.com/qgis/QGIS/tree/release-3_26)
Версия Qt
5.15.5
Версия Python
3.10.5
Версия GDAL/OGR
3.5.1
Версия PROJ
9.0.1
Версия базы данных реестра EPSG
v10.064 (2022-05-19)
Версия GEOS
3.11.0-CAPI-1.17.0
Версия SQLite
3.39.1
Версия PDAL
2.4.2
Версия PostgreSQL
unknown
Версия SpatiaLite
5.0.1
Версия QWT
6.2.0
Версия QScintilla2
2.13.3
Версия ОС
Manjaro Linux

Включенные модули Python
processing_saga_nextgen
0.0.7
processing_r
3.1.1
valuetool
3.0.15
OSMDownloader
1.0.3
SRTM-Downloader
3.1.17
osminfo
0.7.1
AcATaMa
19.11.21b
quick_map_services
0.19.29
processing_wbt
1.3.5
maplibrary
1.2
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by jmasselink** [comment]
I may be experiencing a similar issue, with vector tile layers in my case. I posted to [closed issue #37443](https://github.com/qgis/QGIS/issues/37443#issuecomment-1204062709)

I'm using 3.26.1 and this screenshot shows the exported map (.png) drawing the blue water from the MapTiler Planet layer outside of the map frame.
![image](https://user-images.githubusercontent.com/11066771/182877155-4f3a5931-0aa6-4530-ba48-3d3e2b4f2c7f.png)

**Comment by gioman** [comment]
@erydit same as https://github.com/qgis/QGIS/issues/49638 ?

**Comment by mblesius** [comment]
I think this is the same issue. I have experienced this bug in QGIS 3.26 for different polygon vector layers, too. I have seen it most often when using the _Line Pattern Fill_ as symbology for the polygons, but also for the _Simple Fill_  and _Point Pattern Fill_. For the _Line Pattern Fill_, sometimes, changing the _Clipping_ setting to _Clip Lines before Renderer_ fixes the issue.

**Comment by erydit** [comment]
> @erydit same as #49638 ?

Yes, it looks like a similar issue.

**Comment by gioman** [comment]
> Yes, it looks like a similar issue.

@erydit I'm closing this as duplicate, reopen if you find that is actually a different issue.
