### ISSUE TITLE
'Delete holes' bug when 'area' argument is used

### ISSUE THREAD

**Issue by TomasJohansson** [qgis/QGIS#49578]
### What is the bug or the crash?

I discovered that 'Delete holes' does not work reliable when you use the 'area' argument i.e. when you want to delete all holes smaller than a specified area.
Sometimes holes larger than the specified area are incorrectly removed.
Therefore I have created a small example in an attached geopackage file which shows the problem.

### Steps to reproduce the issue

Open the attached geopackage which is uploaded below within the zip file.
It contains one layer named "delete_holes" defined in the Swedish CRS "SWEREF 99 TM" i.e. the unit are meters.
There is only one polygon in the layer and the outer ring  is a square (20x20 meters) and all four inner rings are also squares and with these sizes:
4 (2x2) , 9 (3x3) , 16 (4x4) , 36 (6x6)
When 'Delete holes' is used with the area argument 12 then only the two smaller holes (with areas 4 and 9) should be removed, but as you can see in a screenshot  below, the largest hole with area 36 is also removed.
[delete_holes.zip](https://github.com/qgis/QGIS/files/9262143/delete_holes.zip)
![delete_holes_dialog](https://user-images.githubusercontent.com/1504507/182919790-d0cb0586-b587-4c21-8df5-b5c5469b6d8b.gif)
![delete_holes_incorrect_result](https://user-images.githubusercontent.com/1504507/182919835-88860ec4-22bb-4246-98a8-2fac3f695804.gif)

### Versions

QGIS 3.22 but the problem is also in the current master and I will soon create a pull request.
As you can see in an attached screenshot I am using the 'master' branch code as of github commit '4861ee8a2f'

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Regarding the QGIS version, I discovered the problem when using Windows 10 and QGIS 3.22 but the problem is still there in the 'master' branch.
I know that since I decided to try and solve the problem myself, so I have setup the development environment for my Linux Ubuntu,
and when debugging it **I have found the problem and will create a pull request**.

So, you do not need to try figure out what the problem is since I intend to very soon (at least within 24 hours and probably sooner) create a pull request, when I have finished a unit test case, referring to this github issue.

**Comment by TomasJohansson** [comment]
![qgis_feedback_answers](https://user-images.githubusercontent.com/1504507/184196200-7cd0700b-9235-4936-83ff-b3890d2916f2.gif)
"Waiting on the submitter for answers"? @gioman 
Should I answer something?
My last commit was four days ago, and since then I have not seen any question or comment.
https://github.com/qgis/QGIS/pull/49583#discussion_r939704288
Maybe there is something I do not understand regarding this pull request process.
What am I expected to do?

**Comment by gioman** [comment]
> Should I answer something?

@TomasJohansson the label was removed.
