### ISSUE TITLE
QGIS crashes when deleting objects in print layout

### ISSUE THREAD

**Issue by mmbento** [qgis/QGIS#49573]
### What is the bug or the crash?

Frequently QGIS have been crashing when deleting objects from print layout, happening most commonly with text boxes and images. I'm using the lastest version - 3.26.1 -  but this issue have been happening to me with several QGIS versions.

### Steps to reproduce the issue

1. Open a poreviously created print layout
2. Delete and object from it

### Versions

3.26.1 - Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@mmbento can't confirm here on Windows 10. Have you really tried on a new QGIS profile?

**Comment by mmbento** [comment]
Yes, I did. It also happened to me sometimes, not frequently but several times on Windows 10. Now I am on Windows 11 and it happens more frequently.

**Comment by gioman** [comment]
> Yes, I did. It also happened to me sometimes, not frequently but several times on Windows 10. Now I am on Windows 11 and it happens more frequently.

@mmbento without a clear way to replicate is hard to troubleshoot.

**Comment by nicogodet** [comment]
Same issue
I will try to create a sample project

**Comment by nicogodet** [comment]
## Step to reproduce
1. Open sample project [temp.zip](https://github.com/qgis/QGIS/files/9584608/temp.zip)
2. Open print layout named "Mise en page 1"
3. Drap and select everything
4. Hit "del" key
5. Should crash 

I tried with a new profile.
