### ISSUE TITLE
Application will not open

### ISSUE THREAD

**Issue by bgulanowski** [qgis/QGIS#49582]
### What is the bug or the crash?

MacOS refuses to run the QGIS application.

![Screen Shot 2022-08-04 at 4 04 56 PM](https://user-images.githubusercontent.com/186680/182942743-42e67630-4b7f-4c02-b9b4-319f2497a66f.png)

### Steps to reproduce the issue

1. Download
2. copy to HD
3. double-click

### Versions

"QGIS 3.26.1-Buenos Aires (), © 2002-2019 QGIS Development Team" taken from Info window.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

macOS Monterey 12.3.1

**Comment by kannes** [comment]
https://qgis.org/en/site/forusers/download.html -> "Download for macOS" says
> QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.

Did you do that?

**Comment by bgulanowski** [comment]
I did not see those instructions. It did open when I did that.

I hope you will get notarized!
