### ISSUE TITLE
Stale bot does NOT remove the Stale label when receiving a comment on pull requests

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#49593]
### What is the bug or the crash?

Stale bot does NOT remove the Stale label when receiving a comment

### Steps to reproduce the issue

File a pull request, wait until stale bot applies the Stale label and send you an email telling you how much the qgis project care about your contribution and how sorry they are to close your PR, comment on the PR that it's still relevant. Watch StaleBot ignoring you.

### Versions

This is about github setup, not qgis

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

See how my comment was ignored by StaleBot here:
https://github.com/qgis/QGIS/pull/49124#issuecomment-1206125962

**Comment by m-kuhn** [comment]
Thanks @pathmapper
