### ISSUE TITLE
The extractlabels algorithm crashes QGIS when no labels are generated and output is set to geojson

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#49602]
### What is the bug or the crash?

The new `native:extractlabels` algorithm crashes QGIS when no labels are generated and output is set to geojson.

Notes:
- It works when saving to other formats (tried shapefile and temporary layer)
- Other processing algorithms seem to have no issue exporting empty geojson (tried with centroid with an empty input)
- In the steps below, for simplicity, I created no layer, but in real world project empty output can arise with scale dependent labels or if you extract an empty extent

### Steps to reproduce the issue

1. blank project
2. open the python console
3. run the following code
```python
import tempfile
processing.runAndLoadResults(
    "native:extractlabels",
    {
        "EXTENT": iface.mapCanvas().extent(),
        "SCALE": 1000,
        "OUTPUT": os.path.join(tempfile.gettempdir(), "test.geojson"),
    }
)
```
4. see crash

### Versions

QGIS version
3.24.1-Tisler
QGIS code revision
5709b82461
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
autocurve
dev
plugin_reloader
0.8.1
qfieldsync
dev
QgisModelBaker
dev
qgepplugin
1.0.0
QuickWKT
3.1
swiss_locator
1.3.6
trackable_project_files
v1.2.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Crash report:

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000075b8 (most recent call first):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72 in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\core\Processing.py", line 187 in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\tools\general.py", line 151 in runAndLoadResults
    return Processing.runAlgorithm(alg, parameters=parameters, onFinish=handleAlgorithmResults, feedback=feedback,
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90 in runcode
    exec(code, self.locals)
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 74 in runsource
    self.runcode(code)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 559 in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 526 in runCommand
    more = self.runsource(src)
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 506 in entered
    self.runCommand(self.text())
  File "C:\OSGeo4W/apps/qgis/./python\console\console_sci.py", line 344 in keyPressEvent
    self.entered()
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b82461
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by nirvn** [comment]
@olivierdalang , https://github.com/qgis/QGIS/pull/49612

**Comment by gioman** [comment]
@olivierdalang the patch was merged, can we close this? @nirvn

**Comment by nirvn** [comment]
Ya
