### ISSUE TITLE
Background color in layout changes when a layer with label masks is activated

### ISSUE THREAD

**Issue by TrailguidePeter** [qgis/QGIS#49614]
### What is the bug or the crash?

When a layer with text label mask is activated (in my case a road line layer that is masked by place names), the background color in the print layout changes. It gets a lot brighter, so that it is almost like there is no background anymore.

I have a couple of other layers as well. Raster layers with the blending mode "multiply" and "lighten". But they seem to have no influnce. First image shows print layout without the masks (darker slightly brownish background), second image with masks (same background, but appears to be white):

![printlayout_no_masks](https://user-images.githubusercontent.com/35575312/183240381-2182610a-8fb4-4c90-b29b-d3e1a2cdfe60.JPG)
.
![printlayout_with_masks](https://user-images.githubusercontent.com/35575312/183240398-d948c8e5-13e9-47b0-a19f-a376f0e185d5.JPG)

I figured out two workarounds:
1) Create a polygon as background layer (background color as polygon fill)
2) Darken the background color in the print layout. But that seems to have a different effect.

### Steps to reproduce the issue

Import a few layers (raster, vector)
Import a line layer 
Import a layer containing text on top, create text labels
Create masks for the text labels
Activate those masks in the line layer
Open the print layout, activate and deactivate the line layer to see the difference

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.9-Białowieża | QGIS code revision | a8e9e6fa
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
batch_gps_importer | version 1.0.1
FreehandRasterGeoreferencer | 0.8.3
joinmultiplelines | Version 0.4.1
OSMDownloader | 1.0.3
profiletool | 4.1.8
QuickOSM | 2.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.9-Białowieża
QGIS code revision
[a8e9e6fa](https://github.com/qgis/QGIS/commit/a8e9e6fa)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batch_gps_importer
version 1.0.1
FreehandRasterGeoreferencer
0.8.3
joinmultiplelines
Version 0.4.1
OSMDownloader
1.0.3
profiletool
4.1.8
QuickOSM
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> ### Steps to reproduce the issue
> 
> Import a few layers (raster, vector) Import a line layer Import a layer containing text on top, create text labels Create masks for the text labels Activate those masks in the line layer Open the print layout, activate and deactivate the line layer to see the difference

@TrailguidePeter can you please attach a sample project + data? thanks.
