### ISSUE TITLE
Orthogonalize Processing Forces Close To Desktop

### ISSUE THREAD

**Issue by FajrAlim** [qgis/QGIS#49621]
### What is the bug or the crash?

When trying to `run` the Orthogonalize processing, the QGIS forces close without any warning or any report about crash :(

### Steps to reproduce the issue

1. I have vector building with total of 860 features manually digitized and some are slightly not squared.
2. Go to `Processing Toolbox`, search `Orthogonalize`, and choose the building layer as Input Layer and using default parameter.
3. QGIS Force Close

### Versions

3.26.0 Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

When copying as Python command and running it, the console will look like this:

```
processing.run("native:orthogonalize", {'INPUT':'I:/RDTR/SIG/Temp/ALI 2/Bangunan.shp','ANGLE_TOLERANCE':15,'MAX_ITERATIONS':1000,'OUTPUT':'TEMPORARY_OUTPUT'})
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1/QGIS/apps/qgis/./python/plugins\processing\tools\general.py", line 108, in run
    return Processing.runAlgorithm(algOrName, parameters, onFinish, feedback, context)
  File "C:\PROGRA~1/QGIS/apps/qgis/./python/plugins\processing\core\Processing.py", line 187, in runAlgorithm
    ret, results = execute(alg, parameters, context, feedback, catch_exceptions=False)
  File "C:\PROGRA~1/QGIS/apps/qgis/./python/plugins\processing\gui\AlgorithmExecutor.py", line 72, in execute
    results, ok = alg.run(parameters, context, feedback, {}, False)
Exception: unknown
```

**Comment by gioman** [comment]
@FajrAlim please attach sample data.

**Comment by FajrAlim** [comment]
@gioman 
[Building.zip](https://github.com/qgis/QGIS/files/9281757/Building.zip)

**Comment by gioman** [comment]
Crash confirmed here.

**Comment by nicogodet** [comment]
It fails at feature.id() = 26, 376, 378

26
`<QgsGeometry: MultiPolygonZ (((642249.10760000010486692 9969984.30960000120103359 0, 642236.80450000031851232 9969984.30960000120103359 0, 642222.91380000067874789 9969984.30960000120103359 0, 642222.91380000067874789 9969999.39090000092983246 0, 642227.27950000006239861 9969999.39090000092983246 0, 642249.10760000010486692 9969999.39090000092983246 0, 642249.10760000010486692 9969984.30960000120103359 0)))>`

376
`<QgsGeometry: MultiPolygonZ (((643379.88069999881554395 9970582.94419999979436398 0, 643370.95029999979306012 9970575.26400000043213367 0, 643364.12409999885130674 9970583.20150000043213367 0, 643373.0543999990914017 9970590.8814999982714653 0, 643379.88069999881554395 9970582.94419999979436398 0)))>`

378
`<QgsGeometry: MultiPolygonZ (((643410.15068266459275037 9970659.29480401799082756 0, 643410.15068266459275037 9970654.92920401692390442 0, 643399.83208266308065504 9970654.92920401692390442 0, 643399.83208266308065504 9970668.42310401797294617 0, 643410.15068266459275037 9970668.42310401797294617 0, 643410.15068266459275037 9970659.29480401799082756 0)))>`

```python
>>> geom.orthogonalize( 1.0e-8, 1000, 45)
Traceback (most recent call last):
  File "C:\OSGeo4W\apps\Python39\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
Exception: unknown
```

Running in debug : 
[19696] Warning: Qt Concurrent has caught an exception thrown from a worker thread.
[19696] This is not supported, exceptions thrown in worker threads must be
[19696] caught before control returns to Qt Concurrent.

**Comment by agiudiceandrea** [comment]
@nicogodet it seems to me the issue occurs if a polygon contains at least a vertex on a straight line (i.e. the angle between previous and next vertex is 180 degrees).

For example, a simple square:
```python
QgsGeometry().fromWkt('Polygon ((0 0, 10 0, 10 10, 0 10, 0 0))').orthogonalize()
<QgsGeometry: Polygon ((0 0, 10 0, 10 10, 0 10, 0 0))>
```
while, adding the vertex at 5 0 right on the 0 0 - 10 0 edge
```python
QgsGeometry().fromWkt('Polygon ((0 0, 5 0, 10 0, 10 10, 0 10, 0 0))').orthogonalize()
Traceback (most recent call last):
  File "F:\QGIS\OSGEO4~1.5\qgis\apps\Python37\lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
Exception: unknown
```
while, moving the added vertex a little bit out of the 0 0 - 10 0 line
```python
QgsGeometry().fromWkt('Polygon ((0 0, 5 0.1, 10 0, 10 10, 0 10, 0 0))').orthogonalize()
<QgsGeometry: Polygon ((0 0, 5.00037102623359697 0.02795654064377098, 9.97670684912965733 0.02426453308625822, 9.98434135992863503 9.98446590818970137, 0.00778312202609196 9.99219543454641013, 0 0))>
```

**Comment by nicogodet** [comment]
@agiudiceandrea I narrowed the issue to these functions too

Weird that an issue has not been raised sooner...
