### ISSUE TITLE
Georeferencer is missing

### ISSUE THREAD

**Issue by cezar-b** [qgis/QGIS#49624]
### What is the bug or the crash?

The Georeferencer option is missing in the raster menu in QGIS 3.26.1 on Linux Mint 20.3 Cinnamon.
Processing is ticked on and all the other raster tools show up as expected.
Also, manually or automatically searching for it doesn't return any results.

### Steps to reproduce the issue

1. Go to Plugins menu > Manage and Install Plugins
2. Tick the Processing Plugin
3. Go to the Raster menu
4. Georeferencer doesn't show up

### Versions

Versiune QGIS | 3.26.1-Buenos Aires | Revizia codului QGIS | b609df9ed4
-- | -- | -- | --
Versiune Qt | 5.12.8
Versiune Python | 3.8.10
Versiune GDAL/OGR | 3.0.4
Versiune PROJ | 6.3.1
Versiunea bazei de date a Registrului EPSG | v9.8.6 (2020-01-22)
Compilat cu GEOS | 3.8.0-CAPI-1.13.1 | Rulează cu GEOS | 3.8.0-CAPI-1.13.1
Compilat cu SQLite | 3.31.1 | Rulează cu SQLite | 3.36.0
Versiune PDAL | 2.0.1
Versiunea clientului PostgreSQL | 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
Versiune SpatiaLite | 4.3.0a
Versiune QWT | 6.1.4
Versiune QScintilla2 | 2.11.2
Versiune SO | Linux Mint 20.3
  |   |   |  
Plugin-uri Python active
TerrainShading | 0.9.3
QuickOSM | 2.0.1
GeoCoding | 2.18
processing_saga_nextgen | 0.0.7
mmqgis | 2021.9.10
Qgis2threejs | 2.7.1
db_manager | 0.1.20
karika | 1.5
LocatePoints | 0.3.4
contour | 2.0.10
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Georeferencer, since 3.26, is now in layer menu.
