### ISSUE TITLE
Layout bleeding to edge outside map window

### ISSUE THREAD

**Issue by TonyShep** [qgis/QGIS#49638]
### What is the bug or the crash?

When printing (both to PDF or direct to printer) a layout that some of the map is printing beyond the Map Window extents, and extending right out to the edge of the page.  It seems (in my case) that it only happens to polygons that have a line pattern fill.  I have attached a PDF that clearly shows this bug.  See the top margin and the blue hatching bleeding to the page edge.  THe same issue occurs when printing directly to the printer.
[12 - Genetics Unit - Management Map 2022 Crop.pdf](https://github.com/qgis/QGIS/files/9278015/12.-.Genetics.Unit.-.Management.Map.2022.Crop.pdf)

It has only been since 3.26 (both 3.26 and 3.26.1).

Both new/clean and old profiles.

### Steps to reproduce the issue

Print or export to PDF

### Versions

3.26.1 and 3.26.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

[12 - Genetics Unit - Management Map 2022 Crop.pdf](https://github.com/qgis/QGIS/files/9278012/12.-.Genetics.Unit.-.Management.Map.2022.Crop.pdf)

**Comment by gioman** [comment]
@TonyShep can you attach a small sample project with data? Thanks.

**Comment by TonyShep** [comment]
[Test Project.zip](https://github.com/qgis/QGIS/files/9288696/Test.Project.zip)
Hi
I have attached a test project with 3 layers.  I created a layout with two map windows, each using a different map theme.  In the zip file is also a PDF of the layout printed as a PDF.  Note that the top window is bleeding over the map window extents. The bottom map window is not.  The difference between the two is that the layer "Contours" is enabled on the top map window but not the bottom.  So it looks like that layer is causing the bleeding, but why? 
Cheers

**Comment by TonyShep** [comment]
v3.26.2 has the same behavior.

Can anybody acknowledge that this is a bug?

Sample PDF from a production map in 3.26.2 is attached.  Same thing happens if the print job is sent directly to the printer.

Cheer
[Mataura-Chimneys Ltd. 2022 Harvest Map Block 7. 3482.pdf](https://github.com/qgis/QGIS/files/9419814/Mataura-Chimneys.Ltd.2022.Harvest.Map.Block.7.3482.pdf)
s

**Comment by mblesius** [comment]
Hey,

I also think this is a bug, the same problem occurred to me since v 3.26.0 in different projects when working with _Polygon vector layers_. For _Line Pattern Fills_, sometimes changing the `Clipping setting` to `Clip Lines before Renderer` fixes the issue, but for other Styles I have no workaround.

**Comment by jmasselink** [comment]
I'm having this same recurrent issue with 3.26.x map layouts that have have more than one map window.

**Comment by troopa81** [comment]
You are using mask and *Always export as vector* option when exporting. If you remove one or another you'll see the issue disappear. Same as #48624

This is well known and described [here](https://github.com/qgis/QGIS/pull/47459) :

>    In the exported pdf, result is not correctly clipped to the frame when mask painter path is involved. It's because the mask clipping doesn't fit well with the overall clipping defined in [QgsLayoutItemMap](https://github.com/qgis/QGIS/blob/master/src/core/layout/qgslayoutitemmap.cpp#L1048) even with the option Qt::IntersectClip. I opened 2 QT BUG regarding this issue (https://bugreports.qt.io/browse/QTBUG-100422 and https://bugreports.qt.io/browse/QTBUG-100420). There are maybe dirty workaround but it will be IMHO better to wait for an upstream fix (second one has already been fixed in Qt 6).

It's a Qt upstream issue, nothing we can do about except hoping they will eventually fix the issues I reported. Or possibly funding someone to fix it.

**Comment by bridgefisher** [comment]
Same problem here with QGIS 3.40.3.  And exported PDF looks okay but when printed the map bleeds past the defined extent of the map and can overlap with titles, legends, and other map items.

**Comment by troopa81** [comment]
@nyalldawson Should your work on #57498 have fixed this issue ? Or is it not applied in this case ?

**Comment by nyalldawson** [comment]
I think there's a few different issues at play. The masking related bleeding should be fixed, but there's definitely still bleed issues with svg exports. Maybe direct printing has similar ones...

**Comment by troopa81** [comment]
@nyalldawson OK, so it should be fixable. I reopen the issue and I'll try to fix it next bug fix round

**Comment by ndn53** [comment]
I think I found a solution to the problem: go to the properties of the vector layer that's causing the issue, then under 'Rendering', check 'Force layer to render as a raster'. I then re-exported my map as a PDF, and the bug was gone

**Comment by troopa81** [comment]
https://github.com/qgis/QGIS/pull/57498 has fixed this issue

<img width="1078" height="637" alt="Image" src="https://github.com/user-attachments/assets/2e490eb1-6596-4466-b473-f461531bac6a" />

There are still SVG issues but that's a different matter than the one described here (it's also more complicated and user is warned correctly when exporting)

I'm closing
