### ISSUE TITLE
Not able to find documentation and python code for elevation profile

### ISSUE THREAD

**Issue by gis-kernel** [qgis/QGIS#49656]
### What is the issue about the documentation?

We wish to modify elevation profile (The documentation we need it for 3.26 version and not master.)

https://github.com/qgis/QGIS/blob/master/src/app/elevation/qgselevationprofiletoolidentify.cpp

as per our needs. But unfortunately we are not able to find documentation and python code for the same. We can find c++ code but python code is missing. 

Can someone please help us with that.

**Comment by nicogodet** [comment]
The core and GUI parts are exposed to PyQGIS:
https://qgis.org/pyqgis/master/search.html?q=Qgsprofile
https://qgis.org/pyqgis/master/search.html?q=Qgsabstractprofile
https://qgis.org/pyqgis/master/search.html?q=Qgselevation
https://qgis.org/pyqgis/master/search.html?q=Qgsplot

**Comment by gis-kernel** [comment]
How do we modify identify tool used here ? We want to increase the number of points than 1000.

**Comment by gis-kernel** [comment]
The documentation we need it for 3.26 version and not master.

**Comment by nicogodet** [comment]
> The documentation we need it for 3.26 version and not master.

3.26 seems broken but master and 3.26 API are the same at this point.



> How do we modify identify tool used here ? We want to increase the number of points than 1000.

The resolution increase as soon as you zoom in.
See implementation here: https://github.com/qgis/QGIS/pull/48360

**Comment by nicogodet** [comment]
But I'm not sure there is an hardcoded value of 1000 in core elevation tool.

There is one in https://plugins.qgis.org/plugins/profiletool/ but we are not talking about this plugin here?

**Comment by gis-kernel** [comment]
The problem is identify tool of elevation profile takes on 1000 points in one go...we need to increase that irrespective of scale

**Comment by nicogodet** [comment]
I don't understand your need.

Maybe it would be better to ask on qgis dev mailing list rather than in a github ticket.

**Comment by senpagapriya23** [comment]
we wish to add button in the elevation profile like identify tool. Is it possible?

**Comment by nicogodet** [comment]
@senpagapriya23 You mean this ?
![image](https://user-images.githubusercontent.com/39594821/183902324-bcdf2d48-d0ed-4b5e-88d9-886ed49dd6c7.png)

**Comment by senpagapriya23** [comment]
Yes, Like that we want to add one more button in the elevation profile

**Comment by nicogodet** [comment]
Ohhh got it.

I think it's not possible at the moment.
The feature request would be to allow customisation of elevation profile widget by adding new actions.

**Comment by senpagapriya23** [comment]
So that We are trying create new elevation profile. But It's difficult to include that basic tools in our new elevation profile.  Please, help us to create that basic tools in our new elevation profile.

**Comment by nicogodet** [comment]
The only person that can help is @nyalldawson which seems busy right now and he spent way more budget on this tool than initially planned.
I think the only way would be to sponsor him for necessary features to customize elevation widget.

**Comment by nicogodet** [comment]
@gioman I think you can remove feedback and rename the feature request

**Comment by nicogodet** [comment]
Maybe you can interact with the QDockWidget.

```python
# Get the widget
for child in iface.mainWindow().findChildren(QDockWidget):
  if child.windowTitle() == "Elevation Profile":  # Replace "Elevation Profile" by the traduction in your language
    elevationDockWidget = child 

# Play with elevationDockWidget
```

**Comment by senpagapriya23** [comment]
how to interact with profile plot like mapcanvas().

**Comment by nicogodet** [comment]
You will have to read some documentation about PyQGIS API and Qt. I will not do everything for you.
RTFM 😄

**Comment by senpagapriya23** [comment]
Thank you

**Comment by nyalldawson** [comment]
Not a bug
