### ISSUE TITLE
QGIS crashes when clicking "digitize shape"

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#49661]
### What is the bug or the crash?

QGIS crashes when clicking "digitize shape"

### Steps to reproduce the issue

Add a polygon layer

Activate both advanced digitizing panel and toolbar

Toggle editing

Choose the "add polygon feature" tool

In the advanced digitizing toolbar, in the second from left icon, click the black arrow and click on "digitize shape"

![image](https://user-images.githubusercontent.com/1951107/183453523-ddf5b6a0-4be1-4797-8f59-b11e2e27d6e2.png)

Crash

### Versions

3.26.1 Windows 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@gioman Duplicate of #47648. wanna try #49592?

**Comment by gioman** [comment]
@DelazJ thanks, as said I have been out for a while.

**Comment by DelazJ** [comment]
:smile: Welcome back and no worries we remarked your absence.
