### ISSUE TITLE
Expression do not split string in multiple lines

### ISSUE THREAD

**Issue by geoinfobih** [qgis/QGIS#49666]
### What is the bug or the crash?

I'm trying to split coordinates in 3 lines - for example
6500450 to be displayed like thi:
6
500
450

shown near to grid
I set show coordinates to show and in format choose custom and set this in expression based annotation dialog
left( @grid_number ,1) ||  '\n'  || substr(@grid_number,1,3) ||  '\n'  || right(@grid_number,3)

### Steps to reproduce the issue

Go to print Layout
Add map
make new Grid
Edit Grid
make x and y distances 15000 15000 to show only few grid lines
go to show coordinates and turn on
chose for format custom go to expression builder and type expression
left( @grid_number ,1) ||  '\n'  || substr(@grid_number,1,3) ||  '\n'  || right(@grid_number,3)

still coordinates are not splitted in 3 lines but shown as one line even if in expression builder they appear in 3 lines

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Add_a_point_road_sign
1.0.1
db-style-manager
0.8
GeoCoding
2.18
latlontools
3.6.4
qad
3.0.4
qgis-maptiler-plugin
3.1.1
vertex_compare
0.0.1
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
> left( @grid_number ,1) || '\n' || substr(@grid_number,1,3) || '\n' || right(@grid_number,3)

what about

```

left( @grid_number ,1) || '
' || substr(@grid_number,1,3) || '
' || right(@grid_number,3)
```

**Comment by geoinfobih** [comment]
> > left( @grid_number ,1) || '\n' || substr(@grid_number,1,3) || '\n' || right(@grid_number,3)
> 
> what about
> 
> ```
> 
> left( @grid_number ,1) || '
> ' || substr(@grid_number,1,3) || '
> ' || right(@grid_number,3)
> ```

Nope still same...

**Comment by nicogodet** [comment]
Workaround:
Choose a character like `+`, `;`, what ever but one that you do not plan to display.
 `left( @grid_number ,1) || '+' || substr(@grid_number,1,3) || '+' || right(@grid_number,3) and use `+` has wrap character in formatting tab.

**Comment by geoinfobih** [comment]
> ~Workaround: Choose a character like `+`, `;`, what ever but one that you do not plan to display. `left( @grid_number ,1) || '+' || substr(@grid_number,1,3) || '+' || right(@grid_number,3)` and use `+` has wrap character in formatting tab.~
> 
> Forget about this. It seems very specific to grid coordinates in map layout

yeah I was woundering how to make it :) but tnx anyway

Seems we should see another way or add functionality as for labels.
