### ISSUE TITLE
Custom dash pattern problem

### ISSUE THREAD

**Issue by unaltroaccountchepalle** [qgis/QGIS#49697]
### What is the bug or the crash?

The "Custom dash pattern" utility in the Symbol selector seems not to work properly, dashes and spaces seems not to respond correctly to inserted measures, increasing values of dashes or spaces do not correspond to increasing length of dashes and spaces proportionally. You can look at attached project and images.
In the attached images you can see that dashed lines red, green, yellow and blue have pattern with different spaces, however the inserted measure is ever '40', while green line has a dash of '20', but is longer than the blue one, which has a dash of '40'.
The offset is '0' ever, but it changes for every line.
Changing the values for the offset, other strange things happen.
It'a big problem when you have to realize a pre-defined pattern, like the one in the attached "Prova pattern. png" image.
[Prova custom dash pattern.zip](https://github.com/qgis/QGIS/files/9293024/Prova.custom.dash.pattern.zip)
![Prova custom dash pattern 10-40](https://user-images.githubusercontent.com/110332766/183710471-ecc65ab3-dce4-4e16-80dc-e9118c6e4cf8.png)
![Prova custom dash pattern 20-40](https://user-images.githubusercontent.com/110332766/183710524-e120ffa7-19c4-42db-a24f-dfcf00751a36.png)
![Prova custom dash pattern 30-40](https://user-images.githubusercontent.com/110332766/183710552-19505780-b3a1-455e-85f1-01a434be86f8.png)
![Prova custom dash pattern 40-40](https://user-images.githubusercontent.com/110332766/183710585-0689775e-5b14-4501-ab9e-11a8076a058a.png)
![Prova pattern](https://user-images.githubusercontent.com/110332766/183712329-4638a5d4-a705-4b0c-83bb-4c52b4a277a6.png)

### Steps to reproduce the issue

1. Open a new project
2. Create a polygon layer
3. Open the Symbol selector window for the layer
4. Choose the 'Line pattern fill', put a 0° angle, and a proper spacing between lines, in order to add other parallel lines with different patterns
5. Tick 'Use custom dash pattern'
6. Try the measures '10 - 40' in Map Units for dashes and spaces
7. Copy the Line pattern fill, put a proper offset, and change the the dash pattern to '20 - 40'
8. Repeat 7. for patterns '30 - 40' and '40 - 40', and so on, and look at the results.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.9-Białowieża | QGIS code revision | a8e9e6fa
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
cartography_tools | 1.2.1
ClipMultipleLayers | 3.2.0
clipper | 1.2
DataPlotly | 3.9
DigitizingTools | 1.5.1
FreehandRasterGeoreferencer | 0.8.3
FS3 | 1.0.1
HCMGIS | 21.8.28
LAStools | 1.4
latlontools | 3.6.4
lftools | 1.7.0
multilayerselect | 1.4.1
MultipleLayerSelection | 2.0
nominatim | 1.4.2
numericalDigitize | 0.4.7
OSMDownloader | 1.0.3
polystrip | 3.0.1
qad | 3.0.4
qgeric | 1.91
qgis-maptiler-plugin | 2.0.0
QuickOSM | 2.0.1
quick_map_services | 0.19.29
raster_tracer | 0.3.2
SelectWithin | 0.4
slyr_community | 4.0.2
SplitPolygonShowingAreas | 0.13
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.9-Białowieża
QGIS code revision
[a8e9e6fa](https://github.com/qgis/QGIS/commit/a8e9e6fa)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
cartography_tools
1.2.1
ClipMultipleLayers
3.2.0
clipper
1.2
DataPlotly
3.9
DigitizingTools
1.5.1
FreehandRasterGeoreferencer
0.8.3
FS3
1.0.1
HCMGIS
21.8.28
LAStools
1.4
latlontools
3.6.4
lftools
1.7.0
multilayerselect
1.4.1
MultipleLayerSelection
2.0
nominatim
1.4.2
numericalDigitize
0.4.7
OSMDownloader
1.0.3
polystrip
3.0.1
qad
3.0.4
qgeric
1.91
qgis-maptiler-plugin
2.0.0
QuickOSM
2.0.1
quick_map_services
0.19.29
raster_tracer
0.3.2
SelectWithin
0.4
slyr_community
4.0.2
SplitPolygonShowingAreas
0.13
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@unaltroaccountchepalle this is the pattern you expect?

![image](https://user-images.githubusercontent.com/1951107/183725391-95c2b432-33fb-43ca-b0ea-a5282b27e721.png)


it seems that the option "clipping" is the one that makes the difference.

**Comment by unaltroaccountchepalle** [comment]
@gioman YES! (Almost perfect... *) The only problem is that I've not such an option like that in my 'Layer properties -> Simbology -> Line pattern fill. Look at the newly attached image. Am I missing something?

*The 'Almost perfect' clause is for I expect that the blue line has dashes and spaces of same length, in your image dashes seems longer. However it could be a great improvement if I could reach it.

> @unaltroaccountchepalle this is the pattern you expect?
> 
> ![image](https://user-images.githubusercontent.com/1951107/183725391-95c2b432-33fb-43ca-b0ea-a5282b27e721.png)
> 
> it seems that the option "clipping" is the one that makes the difference.
![Prova pattern - Line pattern window](https://user-images.githubusercontent.com/110332766/184962922-9bd62933-2c13-4356-80f1-a940f7e86450.png)

**Comment by unaltroaccountchepalle** [comment]
Ok, I replied 20 days ago, what have I to do to make this thing go on or to know if it'll be abandoned?
For now, it seems to me that a new release of QGIS has almost at all resolved the problem, but it's not true for the LTR (last upgrade 3.22.10-1), so I'm asking myself what should be the LTR's usefulness...
Especially now, that I've found another editing problem in LTR, which is resolved in 3.24.

**Comment by unaltroaccountchepalle** [comment]
Hi, I answered 20 days ago.

Il giorno mar 9 ago 2022 alle ore 19:58 Giovanni Manghi <
***@***.***> ha scritto:
