### ISSUE TITLE
Add a geometry expression to make features valid (QgsGeometry.makeValid() )

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#49729]
### Feature description

Sometimes aggregating geometries in the expression builder can lead to invalid geometries, adding an expression to make said feature valid again and usable in something else would be useful.

Adding a function that could call the makeValid method of the QgsGeometry would be ideal.

### Additional context

I'll probably have a gander at it.

**Comment by roya0045** [comment]
Got the code done along with another function to convert geometries to arrays (for filtering and such), will try to test and open the PR soon.

**Comment by lbartoletti** [comment]
Related to https://github.com/qgis/QGIS-Enhancement-Proposals/issues/236
