### ISSUE TITLE
Windows code page 1250 not working properly in QGIS TOC and Layout legend

### ISSUE THREAD

**Issue by MarkoGerbec** [qgis/QGIS#49727]
### What is the bug or the crash?

While I nicely created ESRI shape file in QGIS and managed to enter characters like "č", "š", "ž" in Attribute table, in Layers view, text in Names of the Features does not correctly present character "č" (latin small letter c with caron, character code 010D from Unicode), while "š" and "ž" are correctly presented. Instead, "?" is presented.
Same issue with a map's legend in Layout Manager
![Screenshot 2022-08-10 144246](https://user-images.githubusercontent.com/110983889/183905022-6303b5cd-cf2e-4ea8-84cf-ada29cf061ee.jpg)
.

### Steps to reproduce the issue

1. create a new shape file
2. name features
3. define a map view

### Versions

6.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
> While I nicely created ESRI shape file in QGIS

@MarkoGerbec please attach the shapefile.




> 6.22

there is no such QGIS version.

**Comment by MarkoGerbec** [comment]
Please see attached shapefile files.

Sorry, my mistake: QGIS version is 3.22 

OS is Windows 11, country Slovenia.

 

Marko Gerbec

**Comment by agiudiceandrea** [comment]
@MarkoGerbec please attach the file directly in the issue report on GitHub at https://github.com/qgis/QGIS/issues/49727, not via e-mail message (the attached file is not available if sent via e-mail message).

**Comment by MarkoGerbec** [comment]
Done.

**Comment by agiudiceandrea** [comment]
@MarkoGerbec, to correctly attach the file you need to go to https://github.com/qgis/QGIS/issues/49727 using a Web browser and put it in a comment.

**Comment by djes** [comment]
Not confirmed on 3.22.10 (Windows/FR) with a shapefile layer.
![image](https://user-images.githubusercontent.com/12065874/185069785-042006e5-12fd-4cc7-a1f7-c1027090242d.png)
