### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by crtownsend** [qgis/QGIS#49722]
### What is the bug or the crash?

QGIS unexpectedly ended after opening and closing without opening any projects. Error occured on closing QGIS
"It looks something unexpected happened that we didn't handle and QGIS ended unexpectedly"
![Capture](https://user-images.githubusercontent.com/110967006/183840594-0bd06306-6d0f-465e-9431-7518e20dce48.JPG)
.
## Report Details

**Crash ID**: [df7ab36d97299e20a77faa2780932f1ee15ee61c](https://github.com/qgis/QGIS/search?q=df7ab36d97299e20a77faa2780932f1ee15ee61c&type=Issues)

**Stack Trace**
<pre>
CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. Open QGIS
2. Close QGIS

### Versions

3.22.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by gioman** [comment]
@crtownsend you must test with a new QGIS profile and report if this is replicable in a consistent way (it it was a one time thing it could be hard to troubleshoot).

**Comment by crtownsend** [comment]
Hi Giovanni, the problem doesn't occur when using a new QGIS profile. Regards Craig

**Comment by nicogodet** [comment]
See https://github.com/pcraster/pcraster/issues/361
Not a QGIS issue.
