### ISSUE TITLE
TIN mesh creation causes crash in Model Designer

### ISSUE THREAD

**Issue by GVDDQGIS** [qgis/QGIS#49749]
### What is the bug or the crash?

Using the TIN mesh creation algorithm outside of a model works. First run of the model works. 2nd and subsequent attempts give errors in this tool. Any attempt to edit this tool in the model causes QGIS to crash. 
 
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001db4 (most recent call first):
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 157 in edit
    if dlg.exec_():
  File "C:\PROGRA~1/QGIS32~1.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 178 in editComponent
    self.edit()
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

This is the model:

[volume from DEM2.pdf](https://github.com/qgis/QGIS/files/9309187/volume.from.DEM2.pdf)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code revision | 5709b824
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
clipper | 1.2
dissolve_adjacent_polygons | 0.1
FreehandRasterGeoreferencer | 0.8.3
MagicWand-master | 1.3.1
mmqgis | 2021.9.10
networks | 2.6.8
NNJoin | 3.1.3
parcel_plugin | 3.8
processing_saga_nextgen | 0.0.7
profiletool | 4.2.2
Qgis2threejs | 2.7.1
qgis2web | 3.16.0
qgsAzimuth | 0.9.15
quick_map_services | 0.19.29
SelectWithin | 0.4
shapetools | 3.4.6
tc_tlag | 0.1
valuetool | 3.0.15
volume_calculation_tool | 0.4
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.24.1-Tisler
QGIS code revision
[5709b824](https://github.com/qgis/QGIS/commit/5709b824)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
clipper
1.2
dissolve_adjacent_polygons
0.1
FreehandRasterGeoreferencer
0.8.3
MagicWand-master
1.3.1
mmqgis
2021.9.10
networks
2.6.8
NNJoin
3.1.3
parcel_plugin
3.8
processing_saga_nextgen
0.0.7
profiletool
4.2.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
qgsAzimuth
0.9.15
quick_map_services
0.19.29
SelectWithin
0.4
shapetools
3.4.6
tc_tlag
0.1
valuetool
3.0.15
volume_calculation_tool
0.4
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Upgrade to 3.26.1 or use latest LTR 3.22.9

Try with a new profile too.

**Comment by gioman** [comment]
> QGIS Version: 3.24.1-Tisler

@GVDDQGIS this is unsupported, try on 3.26 with a new QGIS profile. If the problem persist share a project+data+model.

**Comment by GVDDQGIS** [comment]
Installed 3.26.1 and opened the model with TIN Mesh Creation tool, see attached. Prior to running the model. Checked validity, and model was valid. Clicked TIN RAW to try changing dependencies and just clicking on the tool in the model crashed QGIS:
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000aec (most recent call first):
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 180 in edit
    if dlg.exec_():
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 201 in editComponent
    self.edit()
```


**Stack Trace**
No stack trace is available.


**QGIS Info**
QGIS Version: 3.26.1-Buenos Aires
QGIS code revision: b609df9ed4d
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

FOUND THE SOLUTION!
I reopened QGIS and the model. Deleted everything from the bottom up to and including the TIN Mesh Creation tools. No crash. Rebuilt the model with no dependencies on the TIN creation, and it runs OK.

Best Regards

Scott Godfrey, E.I.
GIS Analyst
(970) 242-4343 Ext 1008
***@***.******@***.***>

http://thedrainagedistrict.org/

**Comment by GVDDQGIS** [comment]
I spoke too soon!
Closed and reopened QGIS and the model. When I ran the model, there was an error in the TIN Creation tool that stopped the model but did not crash it:
Here is the log from that run:

QGIS version: 3.26.1-Buenos Aires
QGIS code revision: b609df9ed4d
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.5.1
GEOS version: 3.10.3-CAPI-1.16.1
PROJ version: Rel. 9.0.1, June 15th, 2022
PDAL version: 2.3.0 (git-version: 988ee3)
Algorithm started at: 2022-08-11T14:45:13
Algorithm 'volume from DEM2' starting…
Input parameters:
{ 'contourswithhole' : 'S:/Scott Temp/QGIS DataBase/VOLUME CALCULATION/CONTOURS WITH HOLE.shp', 'gdal:rastercalculator_1:DIFFERENCE' : 'TEMPORARY_OUTPUT', 'native:rastersurfacevolume_1:VOLUME' : 'TEMPORARY_OUTPUT', 'rawcontours' : 'S:/Scott Temp/QGIS DataBase/VOLUME CALCULATION/RAW CONTOURS.shp' }

Prepare algorithm: native:tinmeshcreation_1
Running TIN RAW [1/6]
Input Parameters:
{ CRS_OUTPUT: 'ProjectCrs', MESH_FORMAT: 2, OUTPUT_MESH: 'C:/Users/sgodfrey/AppData/Local/Temp/processing_ChBEDB/6e8ec1735e9a41de9c9499846fd2bde1/OUTPUT_MESH.file', SOURCE_DATA: [{'source': 'RAW_CONTOURS_22c0a3f8_acfd_43b8_8f7f_617bf8f3255c','type': 2,'attributeIndex': 1}] }
Error encountered while running TIN RAW
Execution failed after 0.07 seconds

Loading resulting layers
Algorithm 'volume from DEM2' finished

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005714 (most recent call first):
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 180 in edit
    if dlg.exec_():
  File "C:\PROGRA~1/QGIS32~2.1/apps/qgis/./python/plugins\processing\modeler\ModelerGraphicItem.py", line 201 in editComponent
    self.edit()
```


**Stack Trace**
No stack trace is available.


**QGIS Info**
QGIS Version: 3.26.1-Buenos Aires
QGIS code revision: b609df9ed4d
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

So I’m back to square one!

Best Regards

Scott Godfrey, E.I.
GIS Analyst
(970) 242-4343 Ext 1008
***@***.******@***.***>

http://thedrainagedistrict.org/

**Comment by GVDDQGIS** [comment]
Exported the model to a Python script, minor tweaks to clean it up, runs like a champ! Therefore, the issue is TIN Mesh Creation in the Graphical Modeler. Having to do the tweaks every time I run a new study with this model/scrip is more work than just running a series of tools independently.

Best Regards

Scott Godfrey, E.I.
GIS Analyst
(970) 242-4343 Ext 1008
***@***.******@***.***>

http://thedrainagedistrict.org/

**Comment by GVDDQGIS** [comment]
Nothing new to add, after updating to 3.26, same behavior. Having the TIN Creation tool in Graphic Modeler causes QGIS to crash as soon as it is selected for edit.

Best Regards

Scott Godfrey, E.I.
GIS Analyst
(970) 242-4343 Ext 1008
***@***.******@***.***>

http://thedrainagedistrict.org/

**Comment by nicogodet** [comment]
As it was said before, please share a project, data and model.
Make sure to do it directly github and not via email.
