### ISSUE TITLE
MSSql no coordinate reference system set (OSGeo4W install)

### ISSUE THREAD

**Issue by jkr-wrk** [qgis/QGIS#49759]
### What is the bug or the crash?

When adding a Layer from MSSql to the project, the project does not recognize the coordinate reference system (questionmark icon with the layer).

In the properties-information tab, this is the source string:
dbname='mydb' host=blablabla.database.windows.net user='myuser' estimatedmetadata=true srid=28992 type=Polygon disableInvalidGeometryHandling='0' extentInGeometryColumns='0' table="mySchema"."myTable" (geom)

The srid 28992 is available in the dbo.spatial_ref_sys

I have QGis 3.26.1 installed with the OSGeo4W installer, with this bug.
I have QGis 3.22.9 installed with the OSGeo4W installer, with this bug.
Both have GDAL/OGR version 3.5.1

I have QGis 3.24.0 installed with the EXE installer. Normal behavior.
GDAL/OGR version 3.4.1
I have QGis 3.4.15 installed with the EXE installer. Normal behavior.

What could be the reason for this strange behavior?

### Steps to reproduce the issue

Installing QGis with the OSGeo4W installer and installing QGis without the OSGeo4W installer and adding the same table from a MSSql database.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.9-Białowieża | QGIS code revision | a8e9e6fa
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | ()
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
b4udignl2 | 2.3.0
easy_right_angle_draw | 1.0
pdokservicesplugin | 3.7.4
profiletool | 4.2.2
qgis2web | 3.16.0
QuickWKT | 3.1
quick_map_services | 0.19.29
ReverseFlow | 0.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.22.9-Białowieża
QGIS code revision
[a8e9e6fa](https://github.com/qgis/QGIS/commit/a8e9e6fa)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
()
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
b4udignl2
2.3.0
easy_right_angle_draw
1.0
pdokservicesplugin
3.7.4
profiletool
4.2.2
qgis2web
3.16.0
QuickWKT
3.1
quick_map_services
0.19.29
ReverseFlow
0.2
db_manager
0.1.20
processing
2.12.99

-----

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | b609df9ed4d
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | ()
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
b4udignl2 | 2.3.0
easy_right_angle_draw | 1.0
pdokservicesplugin | 3.7.4
profiletool | 4.2.2
qgis2web | 3.16.0
QuickWKT | 3.1
quick_map_services | 0.19.29
ReverseFlow | 0.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code revision
[b609df9ed4d](https://github.com/qgis/QGIS/commit/b609df9ed4d)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
()
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
b4udignl2
2.3.0
easy_right_angle_draw
1.0
pdokservicesplugin
3.7.4
profiletool
4.2.2
qgis2web
3.16.0
QuickWKT
3.1
quick_map_services
0.19.29
ReverseFlow
0.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by jkr-wrk** [comment]
Tried with a new Profile and the latest QGis 3.26.2 but this did not change the result.

Are there more people using QGis with a MSSql database? Because it seams this is not a very stable combination.

**Comment by jkr-wrk** [comment]
Am I the only one actively using QGis with a MSSql database?

**Comment by elpaso** [comment]
Can you attach the minimal SQL to create the table to reproduce the issue and a small sample project?
