### ISSUE TITLE
Shapefile layer exported as CSV is missing points both in attribute table of export layer and final CSV file

### ISSUE THREAD

**Issue by gomj-aba** [qgis/QGIS#49750]
### What is the bug or the crash?

old maps are scanned and saved as .tif files (attached is the JPEG version after Georeferencing with QGIS)
[ketambenorth_lt_hg_18061981_r_i_groupsplit](https://user-images.githubusercontent.com/110571516/184149065-719ebc29-ebc1-499b-8493-bee55f5b306f.jpeg)
I pull up this layer over a basemap layer and create a shapefile layer in which I add timepoints manually (steps below). Then I export the .shp file as a CSV file which had all the points I entered until I updated to QGIS version 3.26.1 (run on Ubuntu 22.04 Jammy jellyfish)

### Steps to reproduce the issue

[ketambenorth_lt_hg_18061981_r_i.odg](https://github.com/qgis/QGIS/files/9309122/ketambenorth_lt_hg_18061981_r_i.odg)
when you have the modified.tif opened, follow the steps below:
1.In top menu, select 'Layer' --> 'Create Layer' --> 'new shapefile layer'
2. Name the .shp file and under “geometry” select “points” and make sure the CRS matches the basemap (EPSG:4326 - WGS 84) and georeferenced map. 
3. Hit “OK”
4. add timepoints manually --> 'Toggle editing' --> 'Add Point Feature' and then just click on the timepoints marked on the daily range and enter the value in the Fields list.
5. Click on the shapefile layer under Layers --> 'open attribute table' for the shapefile layer to get a count of points you have entered
6. Click on this shapefile layer --> 'Export' --> 'Save features as' --> Comma Separated Value (CSV) --> choose 'Extent (current layers) --> Under ‘Layer Options’ select Geometry and next to it select “AS_XY”
7. check the attribute table for the new (duplicate layer) CSV file - if the bug exists in your QGIS 3.26.1 you will not find all the points that were in the original shapefile layer! Random points go missing 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | b609df9ed4
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
db_manager | 0.1.20

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code revision
[b609df9ed4](https://github.com/qgis/QGIS/commit/b609df9ed4)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by gioman** [comment]
@gomj-aba can you please attach the shapefile? thanks.

**Comment by gomj-aba** [comment]
@gioman I attached the shapefile as jpeg- since tiff is not accepted here! Hope you mean this one
![ketambenorth_lt_hg_18061981_r_i_groupsplit](https://user-images.githubusercontent.com/110571516/184327352-0653a3a8-6a6c-4c18-880a-f60dcd4428cb.jpeg)
.

**Comment by gomj-aba** [comment]
@gioman do you also want the basemap (vector layer)? I can email you that and the .tif of the shapefile, thanks.
