### ISSUE TITLE
Raster -> Georeferencer... Menu Item missing on QGis 3.26.0

### ISSUE THREAD

**Issue by MrBeee** [qgis/QGIS#49768]
### What is the bug or the crash?

I am using QGis 3.26.0, and wanted to georeference a proprietary map (*.png).

Alas, the **Raster -> Georeferencer...** Menu Item is **missing** on QGis 3.26.0, 
and you cannot install this plugin separately

So I had to revert back to QGis 3.20.0, where this problem does not occur.

Please fix...
Thanks every much

### Steps to reproduce the issue

Install V3.26.0 and check the menu items

### Versions

Version 3.26.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This problem does not occur with version 3.20.0

**Comment by gioman** [comment]
@MrBeee it is in "layer" now, as it can georeference also vectors.

**Comment by MrBeee** [comment]
Hi Giovanni,

Thanks for your quick reply. 
You are completely right, and I had not spotted (or expected) this.

Kind regards,
Bart
