### ISSUE TITLE
Incorrect SQL for MSSQL in QGIS Browser

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#49760]
### What is the bug or the crash?

When trying to run a SQL against a MSSQL DB you encounter the following
![Sql-error](https://user-images.githubusercontent.com/2510900/184322020-9b6f5b7d-41e0-45ac-9848-34eadd7ac9c8.png)

Removing the `Limit 10` allows the SQL to run properly
![correct](https://user-images.githubusercontent.com/2510900/184322227-a9d3ac0a-6b14-4784-9057-a6dcddeca431.png)

an

### Steps to reproduce the issue

* setup a MSSQL connection in QGIS browser
* open a table and right click
* Choose `Execute SQL`
* Run the SQL and see the error
* Edit the SQL expression removing `Limit 10` and run the 

### Versions

![about-qgis](https://user-images.githubusercontent.com/2510900/184323534-4a4c0d2e-8f5d-4087-898d-e0a1abdb86f3.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@NyakudyaA are you sure the `LIMIT` clause is supported by MSSQL? It seems to me it isn't.
See for example https://www.w3schools.com/sql/sql_top.asp, https://stackoverflow.com/questions/31704424/incorrect-syntax-near-limit-using-mssql, https://stackoverflow.com/questions/50996666/limit-n-vs-top-n-in-sql-server, https://stackoverflow.com/questions/595123/is-there-an-ansi-sql-alternative-to-the-mysql-limit-keyword.

**Comment by NyakudyaA** [comment]
@agiudiceandrea The problem is that the `Execute SQL` option natively opens with the `LIMIT` clause appended to it.

**Comment by agiudiceandrea** [comment]
@NyakudyaA OK, now it is more clear: the issue is due to the fact that the "SQL dialog" query is automatically pre-set with a statement that contains the `LIMIT` clause which is not supported by all the *SQL DBs
https://github.com/qgis/QGIS/blob/51e3c0833b36db96bf8ded1dfa26f0d2b041ece6/src/app/browser/qgsinbuiltdataitemproviders.cpp#L1730-L1739

**Comment by elpaso** [comment]
> @NyakudyaA OK, now it is more clear: the issue is due to the fact that the "SQL dialog" query is automatically pre-set with a statement that contains the `LIMIT` clause which is not supported by all the *SQL DBs (specifically it is not supported by MSSQL).
> 
> https://github.com/qgis/QGIS/blob/51e3c0833b36db96bf8ded1dfa26f0d2b041ece6/src/app/browser/qgsinbuiltdataitemproviders.cpp#L1730-L1739

An ugly but easy fix is to make an exception for MSSQL provider.

**Comment by agiudiceandrea** [comment]
@NyakudyaA @elpaso I've just proposed a simple fix #49770. Anyway I cannot actually check with a MSSQL connection...

**Comment by NyakudyaA** [comment]
You can spin up a database relatively easy using docker https://docs.microsoft.com/en-us/sql/linux/quickstart-install-connect-docker?view=sql-server-ver16&pivots=cs1-bash

Will compile and test

**Comment by tschlarman** [comment]
Sorry to chime in on this. Yes, this is a MySQL query. 

The equivalent SQL Server query is:

SELECT top 10 * FROM "<schema>"."<table>"

Not sure if this affects your fix or not.

**Comment by agiudiceandrea** [comment]
> The equivalent SQL Server query is:
> 
> SELECT top 10 * FROM "schema"."table"

This is exactly what my PR does.

**Comment by tschlarman** [comment]
Sounds great. Well done and thank you.

**Comment by agiudiceandrea** [comment]
@tschlarman, a new proposed fix: https://github.com/qgis/QGIS/pull/49950.
