### ISSUE TITLE
Using "night mode", all checkbox checks are invisible ?

### ISSUE THREAD

**Issue by LorenAmelang** [qgis/QGIS#49775]
### What is the bug or the crash?

Using "night mode", all checkbox checks are invisible. In QGIS settings, in plugins, anywhere they appear. No way to tell if they are checked or not, without changing the mode and restarting QGIS. 

![Checkbox bug](https://user-images.githubusercontent.com/1297090/184580291-668610d7-4ad5-41d4-99cc-10c64034ceac.png)

### Steps to reproduce the issue

Choose Dark mode: 
Settings -> Options -> General -> Application -> UI Theme -> Night Mapping

Restart. Look at any dialog that includes a checkbox...

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
Mergin
2022.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Sorry, I don't get the details of which versions are supported. Do I need a newer one? It takes hours to download one here...

**Comment by AlisterH** [comment]
The green boxes are checked and the grey ones are unchecked.  Am I missing something?
![image](https://user-images.githubusercontent.com/714600/214253625-40d21dd7-89cd-4733-af0d-578ad713a340.png)

**Comment by AlisterH** [comment]
Having said that, in some places like the plugin manager there are normal checkboxes with a tick, which are nearly invisible:
![image](https://user-images.githubusercontent.com/714600/214254523-48b60591-a4e1-4686-8dfa-3eceb7b817e5.png)

**Comment by LorenAmelang** [comment]
> The green boxes are checked and the grey ones are unchecked. Am I missing something? 

I know I have lousy vision for both color and detail, but I would never have guessed those boxes were different colors! The Meazure app shows they are...  I hope there can be a solution that jumps out obviously for those of us who need it!

**Comment by AlisterH** [comment]
But it's the same green and grey used everywhere.  Does that mean there are places all over QGIS where you can't see what is selected?
Can you see that "Qt default" is selected?  "General" is obviously different because the rest of that tree is dark grey, not light.
![image](https://user-images.githubusercontent.com/714600/214466939-820a9395-eda7-4fc6-b783-c0e9f891c24a.png)

> I know I have lousy vision for both color and detail

Your monitor, screen brightness etc would contribute too.  I run my screen so dark that in some software I have to change colours to be able to see things.

Loading the screenshot into QGIS and testing with "View>Preview Mode" I can easily see what is selected using the other  colour blindness modes, but I can't see it with the achromatopsia mode.  
In any case, I think it is bad practice to show selections just using colour - if a lighter green was used so that everyone could distinguish it from the grey it still wouldn't be satisfactory because it wouldn't always be obvious which colour 
(or shade of grey for the colour blind) means selected and which means unselected.  There should be a checkmark (or something else depending on the widget) that makes it clear what is selected.  I think this is what they call "semantic design".

**Comment by LorenAmelang** [comment]
"But it's the same green and grey used everywhere. Does that mean there are places all over QGIS where you can't see what is selected? Can you see that "Qt default" is selected?

The "Qt default" text is obviously brighter - I assume that means it is selected...  But yes, I'm pretty much color blind when the areas involved are small or the brightness is low. And I'm really insensitive to blue at any level, so the difference between that green and gray is only the tiny change in red level. 

I find similar quirks in Libre Office, which also uses Qt. They had developed a super-complex color system, and then various people tried to flip it into a dark mode. The interactions are just mind boggling. Maybe the Qt people need to deal with this? But yes, "semantic design"!

**Comment by AlisterH** [comment]
A quick google suggests it should be possible to test the UI itself with simulated colour blindness, at least under KDE: https://www.qt.io/blog/2017/09/15/testing-applications-color-blindness.
Hopefully that KWin plugin is still working and available somewhere - I haven't pursued it past https://phabricator.kde.org/D7832 to find out where it actually ended up...

**Comment by AlisterH** [comment]
Do you have any other problems in night mapping mode?  Any problems when not in night mapping mode?

It might be worth editing the title of this ticket to something like "checkbox selection invisible to color blind people in night mode"

**Comment by AlisterH** [comment]
> A quick google suggests it should be possible to test the UI itself with simulated colour blindness, at least under KDE: https://www.qt.io/blog/2017/09/15/testing-applications-color-blindness. Hopefully that KWin plugin is still working and available somewhere - I haven't pursued it past this https://phabricator.kde.org/D7832 to find out where it actually ended up...

That comment was obviously for anybody else who might want to test QGIS as if they were colour blind.  For information on doing this with other platforms: https://nevyan.blogspot.com/2018/08/enabling-grayscale-in-gnome-kde-and.html
Turns out Windows 10 has it as a built-in feature!

**Comment by AlisterH** [comment]
Here is a possible set of svgs to fix this issue in the night mapping theme:
![qcheckbox-checked_tick](https://user-images.githubusercontent.com/714600/215941327-18d43231-78fb-4558-a1e0-bc9a6fe9e04d.svg)
![qradiobox-checked-disabled](https://user-images.githubusercontent.com/714600/215941329-4890757d-c8b4-474c-bf65-fcfd62ce13c7.svg)
![qradiobox-checked](https://user-images.githubusercontent.com/714600/215941331-2fa1c7e8-1104-4b80-b03d-f40d91d9cdff.svg)
![qcheckbox-intermediary](https://user-images.githubusercontent.com/714600/215941334-791560f2-97c3-4176-9ecc-f5c0686fcef5.svg)
![qcheckbox-checked-disabled](https://user-images.githubusercontent.com/714600/215941335-2590380d-43f5-4e5f-b202-b5f56aad7943.svg)
![qcheckbox-checked](https://user-images.githubusercontent.com/714600/215941336-9211e3ac-b63c-4a96-bb47-3378127df6a6.svg)

**Comment by AlisterH** [comment]
I'd actually prefer this, but it was hurting my head trying to figure out the best colours to use for the three different icons:
![qcheckbox-checked_tick](https://user-images.githubusercontent.com/714600/215941327-18d43231-78fb-4558-a1e0-bc9a6fe9e04d.svg)

**Comment by LorenAmelang** [comment]
I called the "possible svgs" correctly, but didn't trust my perception until the Meazure app confirmed them. The ones with white boundaries seem a bit more visible to me. But absolutely, making the checkmark obvious is the best solution! 

As for other problems in night mode, I don't remember any where there was no alternative clue without restarting the app. Lots of things could be more visible, but I realize I'm not the average user. What I really need is a maximum contrast white-on-black mode. But "Night mode" is better than the normal glaring white background.

**Comment by AlisterH** [comment]
Slight improvement for the radioboxes:
![qradiobox-checked](https://user-images.githubusercontent.com/714600/215960222-75f16e15-14cc-4a00-8357-6a09922c8ac0.svg)
![qradiobox-checked-disabled](https://user-images.githubusercontent.com/714600/215960227-a398bd7b-32f8-4f16-9a34-82e62bca3764.svg)

**Comment by AlisterH** [comment]
Sorry, I didn't notice it renames the files

I figured out how to actually test the "disabled" svgs, and they needed another changing to make everything less visually confusing.

Here is a set of all the changed svgs; I think we just need to sort out a pull request now.
[icons.zip](https://github.com/qgis/QGIS/files/10554073/icons.zip)

**Comment by LorenAmelang** [comment]
Yes! Those totally work for me. As for "we" and the pull request, I'm afraid I'm no help. But thank you if you go ahead!

**Comment by AlisterH** [comment]
> > A quick google suggests it should be possible to test the UI itself with simulated colour blindness, at least under KDE: https://www.qt.io/blog/2017/09/15/testing-applications-color-blindness. Hopefully that KWin plugin is still working and available somewhere - I haven't pursued it past this https://phabricator.kde.org/D7832 to find out where it actually ended up...
> 
> That comment was obviously for anybody else who might want to test QGIS as if they were colour blind. For information on doing this with other platforms: https://nevyan.blogspot.com/2018/08/enabling-grayscale-in-gnome-kde-and.html Turns out Windows 10 has it as a built-in feature!

Actually, although its greyscale preset is useful for testing, the Windows feature is the opposite.  It is an accessibility feature providing presets intended to help colour blind people directly by making colours more distinct.

It might be worth trying them if you haven't already Loren.  It also has "inverted" and "inverted greyscale" filters.

**Comment by LorenAmelang** [comment]
The Windows protanopia and tritanopia filters make a big difference between the green and brown squares - green turns black - but still give no clue which is "checked". Would you guess black? 

Inverting the daytime QGIS might help, except Windows inverts _everything_, all apps all over the screen, making every other tool and view problematic. My iPad can automatically invert or "smart invert" single apps - much more useful!

**Comment by alexbruy** [comment]
Can we close this? As I understand #54093 solved the issue.

**Comment by nirvn** [comment]
@alexbruy , yeah, let's close this.
