### ISSUE TITLE
Package for QField in QGis 3.22.9

### ISSUE THREAD

**Issue by ols1-ch** [qgis/QGIS#49780]
### What is the bug or the crash?

This error occurs in QGis 3.22.9 but not in 3.14.16
When I use "Package for QField"
I get:
An error has occurred while executing Python code: 

TypeError: decorated slot has no signature compatible with progressModeSet(QgsOfflineEditing::ProgressMode,long long) 
Traceback (most recent call last):
  File "C:\Users/ols1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\package_dialog.py", line 120, in package_project
    offline_convertor = OfflineConverter(
  File "C:\Users/ols1/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\libqfieldsync\offline_converter.py", line 95, in __init__
    offline_editing.progressModeSet.connect(self.on_offline_editing_max_changed)
TypeError: decorated slot has no signature compatible with progressModeSet(QgsOfflineEditing::ProgressMode,long long)

### Steps to reproduce the issue

1. Prepare some geopackages und raster files
2. Click on  "Package for QField"
3. Click create

### Versions

QGis 3.22.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
Hi @ols1-ch Issues with plugins should be reported at plugins issue tracker, and in this case at https://github.com/opengisch/QFieldSync/issues. Please first check that this is not reported already.
