### ISSUE TITLE
WMTS with EPSG:2180 projection doesn't work with QGIS 3.26

### ISSUE THREAD

**Issue by kapiwko** [qgis/QGIS#49781]
### What is the bug or the crash?

WMTS Layer:

Name | ORTOFOTOMAPA
-- | --
URL | http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetCapabilities
Source | crs=EPSG:2180&dpiMode=7&format=image/jpeg&layers=ORTOFOTOMAPA&styles=default&tileMatrixSet=EPSG:2180&url=http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE%3DWMTS%26REQUEST%3DGetCapabilities&http-header:referer=
Provider | wms

### Steps to reproduce the issue

1. Add WMTS Layer (http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetCapabilities)
2. Layer is unavailable in QGIS 3.26
![image](https://user-images.githubusercontent.com/9286521/184684591-37ffe594-6a52-43ac-b2f9-d863b2a47f66.png)

3. Tried with QGIS 3.22 and works perfectly

### Versions

QGIS version | 3.26.1-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Qt version | 5.15.5
Python version | 3.10.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.1 | Running against SQLite | 3.39.2
Compiled against PDAL | 2.4.2 | Running against PDAL | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
QuickOSM | 2.0.1
firstaid | 2.1.5
changeDataSource | 3.1
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by kapiwko** [comment]
### Information from provider

QGIS | Extent
-- | --
3.26 | Empty
3.22 | 118322.2938740439713001,103601.3148151570931077 : 896351.9119938735384494,806302.0717712882906199

**Comment by nyalldawson** [comment]
That site doesn't respond at all for me -- http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetCapabilities just comes back with an error.

Are you sure the service wasn't just offline?

**Comment by agiudiceandrea** [comment]
I can connect to http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetCapabilities and add and display the ORTOFOTOMAPA layer with EPSG:2180 without issues using QGIS 3.26.1 on Windows 10 and Ubuntu 22.04.

Name	ORTOFOTOMAPA
URL	http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE=WMTS&REQUEST=GetCapabilities
Source	contextualWMSLegend=0&crs=EPSG:2180&dpiMode=7&featureCount=10&format=image/jpeg&layers=ORTOFOTOMAPA&styles=default&tileMatrixSet=EPSG:2180&url=http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE%3DWMTS%26REQUEST%3DGetCapabilities
Provider	wms

Extent	118322.2938740439713001,103601.3148151570931077 : 896351.9119938735384494,806302.0717712882906199

![image](https://user-images.githubusercontent.com/16253859/184815115-d752ba27-4438-4453-8550-e163433d64dd.png)

**Comment by kapiwko** [comment]
Yes, I can confirm, that on Windows it works. I'll try to downgrade GDAL and PROJ and recompile QGIS.

**Comment by agiudiceandrea** [comment]
@kapiwko, on Windows / OSGeo4W, QGIS 3.26.1 uses the same exact version of GDAL 3.5.1 and PROJ 9.0.1.

**Comment by kapiwko** [comment]
Ok, I've upgraded QGIS on my second machine (Manjaro Linux) and I've reproduced issue.

When I open QGIS 3.26 and add WMTS layer with EPSG:2180 **using Data Source Manager** - it works perfectly:
![image](https://user-images.githubusercontent.com/9286521/184871589-0355037c-562f-4566-b404-05f6cff264ab.png)
![image](https://user-images.githubusercontent.com/9286521/184871655-b4bd9a44-e524-45eb-9b2b-26f3c433d87e.png)

When I open QGIS 3.26 and add WMTS layer with EPSG:2180 **using Browser** it doesn't work:
![image](https://user-images.githubusercontent.com/9286521/184871976-d7885d49-90c5-48e6-96f5-09da799af429.png)

When I open QGIS 3.26 and open project containing that WMTS Layer -  it doesn't work:
![image](https://user-images.githubusercontent.com/9286521/184872263-5b02bfd5-4449-4bad-9829-aa83e2c6a723.png)

But... if I first add WMTS layer with EPSG:2180 **using Data Source Manager** and then I close project and add WMTS layer with EPSG:2180 **using Browser** OR open project containing that WMTS Layer - IT WORKS!

But... if I first add WMTS layer with EPSG:2180 **using Browser** OR open project containing that WMTS Layer and then I try to add layer  **using Data Source Manager** - it doesn't work.

**Comment by kapiwko** [comment]
Similar behaviour I've with geotiffs. When I load them using drag&drop - it works:
![image](https://user-images.githubusercontent.com/9286521/184874128-1b9887bb-8129-4e06-8b23-8522f182502f.png)

When I save project, close QGIS and open project again - it works.

When I add WMTS layer in EPSG:2180 using Data Source Manager - it still works:
![image](https://user-images.githubusercontent.com/9286521/184874694-b394ca0a-6d42-4fe2-ae29-2bef0e584743.png)

But then if I close QGIS and open project again - only EPSG:2178 layer is displayed.
![image](https://user-images.githubusercontent.com/9286521/184875321-85840327-2dda-46b3-acb4-068046997a60.png)
![image](https://user-images.githubusercontent.com/9286521/184875419-0db9c9f6-520f-45c7-bcd0-6a88c3b8fb02.png)

**Comment by kapiwko** [comment]
Test project is here: https://drive.google.com/file/d/1DP2USqQxVmwipoGDJ-yfzzasH_LxvEk7/view?usp=sharing

**Comment by agiudiceandrea** [comment]
@kapiwko, I don't see any issue adding the layer (EPSG:2180) through the Browser panel using QGIS 3.26 on Windows / OSGeo4W and on Ubuntu 22.04 / Flatpak:

https://user-images.githubusercontent.com/16253859/184887291-975e5341-09df-4149-a28c-e4fbb1d7a762.mp4

**Comment by kapiwko** [comment]
Yes, on Windows it works.

Now i tried with this python code in console:

`iface.addRasterLayer("crs=EPSG:2180&dpiMode=7&format=image/jpeg&layers=ORTOFOTOMAPA&styles=default&tileMatrixSet=EPSG:2180&url=http://mapy.geoportal.gov.pl/wss/service/PZGIK/ORTO/WMTS/StandardResolution?SERVICE%3DWMTS%26REQUEST%3DGetCapabilities&http-header:referer=", "ortofoto", "wms")`

[simplescreenrecorder-2022-08-16_17.49.10.webm](https://user-images.githubusercontent.com/9286521/184925316-7c356475-de83-442c-a62d-122732415b62.webm)

[simplescreenrecorder-2022-08-16_17.50.39.webm](https://user-images.githubusercontent.com/9286521/184925346-db43bd85-0455-453a-9f6d-b28e339dc2fd.webm)
