### ISSUE TITLE
"Circular string by radius" tool can not be combined with other tools to draw a feature

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#49784]
### What is the bug or the crash?

Before recent refactoring, the "add circular string by radius" could be combined with straight lines, that is, drawing a polygon, part of the geometry can be made with the circular tool, then you switch to straight lines for few vertices and finish again with the circular part (or do it in whatever order you want).
Now while using the "Circular string by radius", switching to the straight lines mode makes you lose the geometry you were drawing, and vice versa. The "circular string by radius" tool is now meant to be used alone to draw a complete geometry (although unlike the other "shape digitizing" tools, its output is not that predictable, and not really of a common shape type)

### Steps to reproduce the issue

1. Toggle a polygon layer to edit and Enable the "Add features" tool.
2. Enable the "Shape digitizing toolbar" and select the "Circular string by radius" tool
3. Start digitizing a feature: 3 left clicks to create an arc
4. Try to switch digitizing mode: on the "Advanced digitizing toolbar, switch from the "shape digitize" method to anything else.
5. Your geometry is gone!!!

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | 96298dbe3f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
This use  case is now covered by the new "Digitize with curves" introduced by #37685

**Comment by DelazJ** [comment]
@YoannQDQ no computer around to check but are you sure of the PR you mention? It is almost two years older than the report.

**Comment by YoannQDQ** [comment]
I may be wrong, but I think #37685 made digitizing complex geometries with "circular string by radius" redundant, so the possibility to use it as you described was later removed.
