### ISSUE TITLE
Layer tree view is not refreshing correctly

### ISSUE THREAD

**Issue by Kaemer1645** [qgis/QGIS#49803]
### What is the bug or the crash?

After creating a point symbols and set them expression, the layer tree view show wrong color.

### Steps to reproduce the issue

1. Craete point symbol
![image](https://user-images.githubusercontent.com/62249638/184867139-3fee5305-588b-4cb6-b06e-0aa34351f414.png)

2. Set expression to fill color and stroke color.
For me it was '1,255,18,255'
![image](https://user-images.githubusercontent.com/62249638/184865458-2225a9c8-70e8-449f-a0d8-994e9c7010c8.png)
3. Layer tree view show incorrect colors.
![image](https://user-images.githubusercontent.com/62249638/184867266-a4d85df2-b05c-4617-aab1-596331b956ff.png)

### Versions

I was checking this bug on two QGIS versions 3.24 and 3.26

QGIS version
3.24.2-Tisler
QGIS code revision
https://github.com/qgis/QGIS/commit/13c1a028655f9197b7f88a72fb526b8b002cddd2
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.1
QMapa
1.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

QGIS version
3.26.0-Buenos Aires
QGIS code revision
https://github.com/qgis/QGIS/commit/0aece2818e5259f7c96b653570ce12736c31fd96
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.1
QMapa
1.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by andreasneumann** [comment]
Dynamic legends taking into account data defined properties never worked in any previous QGIS version. If you use data-defined properties with expressions, there could potentially (too) many possible combinations and would probably harm performance quite a lot, if for every redraw of the map you would have to regenerate the legends all the time.

I would classify this as a "feature request" rather than a bug. And I am pretty sure there are other open issues if you search for it - some of them potentially opened many years ago.

**Comment by roya0045** [comment]
Agreed, assuming a symbol to behave perfectly with DD elements is silly. The only way is to have multiple symbols with hard set elements to cover this case.

**Comment by elpaso** [comment]
Should we close this issue?
