### ISSUE TITLE
SVG Symbol on newer version of QGIS (3.22.7/8/10 tested) make the software lag a lot (and not on 3.4 version).

### ISSUE THREAD

**Issue by FlorianBEJC** [qgis/QGIS#49818]
### What is the bug or the crash?

Hello !

We use QGIS at work. We were on 3.4 since recently and decided to move forward to 3.22. Since this change, when a SVG is applied as style (especially on a categorized style of layer, with about 40 points), everything bugs and is slowed down (but there is no crash). On 3.4 it doesn't happen.  In this particular case, we have to rotate the symbol for each point it is really hard when each rotation of 1 degree takes 5 seconds to be done. 

Let me know if you need more information.

Have a nice day !

Florian.

### Steps to reproduce the issue

1. Create a vector layer with around 20-40 points
2. Categorize the style and sort it by id.
![STEP 1 CATEGORIZED](https://user-images.githubusercontent.com/111421573/185077856-ddbbb7bb-d699-4296-9232-b0fd2568a157.jpg)
4. Apply a SVG symbol to the elements (from 5Ko to 20 Ko).
5. Everything is lagging.
![STEP 2 APPLY SVG](https://user-images.githubusercontent.com/111421573/185077867-dfdcd22c-27b7-42e9-9bea-191bbd535bfa.jpg)
 As said before it worked perfectly on 3.4 version. 

### Versions

3.22.7-Białowieża
3.22.8-Białowieża
3.22.10-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ponceta** [comment]
I had a similar issue with network stored svg on a drive that was not available anymore. This made QGIS laggy and freezy. Once the path fixed everything was smooth again.

**Comment by troopa81** [comment]
Could you share a sample project and data ? 

I try to reproduce with data of my own and did notice a really slightly slow down but no bugs or big lags. 

QGIS is caching SVG file but when we change svg symbol color (which is the case here), we cache the modified SVG (with the category color) and read several time the SVG file from disk. But I would say cache disk might lower the read issue.

**Comment by ponceta** [comment]
This happens only with custom svg where you can change the color / width / ...

**Comment by djes** [comment]
> This happens only with custom svg where you can change the color / width / ...

Are you sure ? Most of ours are simple SVG. Replacing all of them with PNG gives us a boost. Custom SVG could be really useful anyway, I hope new QGIS versions will correct this problem.
