### ISSUE TITLE
QGIS crashes when moving a feature 

### ISSUE THREAD

**Issue by lyroy93** [qgis/QGIS#49814]
### What is the bug or the crash?

Crash ID: [9fc70e16611e3d3a59a5958d1ca5cb749a790fe2](https://github.com/qgis/QGIS/search?q=9fc70e16611e3d3a59a5958d1ca5cb749a790fe2&type=Issues)

Stack Trace

Index::~Index :
qsort :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
Index::~Index :
QgsPointLocator::onFeatureDeleted :
QgsPointLocator::onGeometryChanged :
QMetaObject::activate :
QgsVectorLayer::geometryChanged :
QMetaObject::activate :
QgsVectorLayerEditBuffer::geometryChanged :
QUndoStack::push :
QgsVectorLayerEditBuffer::changeGeometry :
QgsVectorLayer::changeGeometry :
QgsVertexTool::applyEditsToLayers :
QgsVertexTool::moveVertex :
QgsVertexTool::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.10.2-A Coru�a
QGIS code revision: d4cd3cfe5a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.3
Running against GDAL: 3.0.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

### Steps to reproduce the issue

Move a feature in a specific SHP Point Layer on map canvas with the "Move Feature" tool activated, Edit mode enabled on the point layer and with snapping enabled.

### Versions

QGIS version
3.10.2-A Coruña
QGIS code revision
d4cd3cfe5a
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.3
Running against GDAL/OGR
3.0.3
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.0
Running against PROJ
Rel. 6.3.0, January 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
db_manager; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
3.10.2 is EOL.  Please verify the issue with current 3.22.10 or 3.26.2.

**Comment by lyroy93** [comment]
I still get the same issue even after upgrading to 3.22.10.
Crash ID: [701cac5eecf585931de949b05b747f7cde3a536c](https://github.com/qgis/QGIS/search?q=701cac5eecf585931de949b05b747f7cde3a536c&type=Issues)


Stack Trace


SpatialIndex::TPRTree::Data::Data :
qsort :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::onFeatureDeleted :
QgsPointLocator::onGeometryChanged :
QObject::qt_static_metacall :
QgsVectorLayer::geometryChanged :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::geometryChanged :
QUndoStack::push :
QgsVectorLayerEditBuffer::changeGeometry :
QgsVectorLayer::changeGeometry :
QgsMapToolMoveFeature::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.10-Bia?owie?a
QGIS code revision: 6a63fd37
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by roya0045** [comment]
Is it in a specific project or a single data source? If so could you share the problematic data or just sample geometries for others to test?
