### ISSUE TITLE
Mid-marker ("+") for inserting a new vertex is not appearing at the center of the visible part

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#49817]
### What is the bug or the crash?

It used to be that the "+" icon for inserting a new vertex on a linestring does appear at the _**center of the visible part**_ of segment. That seemed to work for any zoom level you are in. 
In QGIS 3.26 the "+" marker does not behave this way and that it might actually not appear at all unless one starts to pan around to search for it. This is a setback in usability. 

![image](https://user-images.githubusercontent.com/66669404/185074078-2e7c9e97-dd94-43d5-b725-1a07396f083f.png)

![image](https://user-images.githubusercontent.com/66669404/185074125-ae5075d0-bfca-4d4c-97f3-41e38ece851d.png)

![image](https://user-images.githubusercontent.com/66669404/185074163-2d3903f9-e9f2-4d91-bb62-3d081fdd78c3.png)

![image](https://user-images.githubusercontent.com/66669404/185074199-4d47f618-aa0f-4f3d-ae67-1819146449bd.png)

![image](https://user-images.githubusercontent.com/66669404/185074240-b54f80ea-1aa5-4ae7-9a04-21da13c617fd.png)

(Note 1: screenshots always show the entire viewport)

(Note 2: the linestring's label is behaving in the correct way: it is always positioned at the center of the visible part of the segment. The "+" icon is expected to behave the same way and it was in earlier versions of QGIS - e.g.: current LTR version)

(Note 3: the screenshots show another issue reported here: https://github.com/qgis/QGIS/issues/45200)

### Steps to reproduce the issue

Draw a line and hover over it in different zoom levels and check the position of the "+" icon.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
7Cs RNW AIS | 1.0
7Cs RNW Editor | 1.0
7Cs RNW Manager | 1.0
7Cs RNW Viewer | 1.0
db-style-manager | 0.8
DigitizingTools | 1.5.1
latlontools | 3.6.4
layerGroupFilter | 0.2
multiple_layers_tools | 1.2
postgis_geoprocessing | 0.9
shapetools | 3.4.6
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code revision
[feec3d3b12f](https://github.com/qgis/QGIS/commit/feec3d3b12f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db-style-manager
0.8
DigitizingTools
1.5.1
latlontools
3.6.4
layerGroupFilter
0.2
multiple_layers_tools
1.2
postgis_geoprocessing
0.9
shapetools
3.4.6
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I don't know if this is a bug or something fixed, notably if you have lines where part overlap, this would lead to issues distinguishing which was selected if the two extended beyond the view. With a static midpoint this solves this issue.

**Comment by beyhh** [comment]
In the example I describe and as can be seen from the screenshots, there are no lines which overlap. There are only other lines snapped to the vertex of the line in the center of the viewport.

**Comment by roya0045** [comment]
@uclaros I suspect this is related to the change in logic introduced by #42561, but I may be mistaken. Would you know if the change in logic could have generated this? And if it was intentional?

**Comment by uclaros** [comment]
I doubt it's related, my guess is it's related to the clipper similar to the mentioned #45200
Can you replicate this on other CRSs?

**Comment by uclaros** [comment]
@roya0045 You're right, I checked the code and my logic was definitely flawed!

**Comment by roya0045** [comment]
> @roya0045 You're right, I checked the code and my logic was definitely flawed!

Glad I could help! Thanks for the quick PR 👍

**Comment by uclaros** [comment]
@beyhh Until the fix is merged, instead of searching for the cross icon, you can just double click anywhere on the line to add a new vertex. Also, shift-doubleclick directly adds a vertex in place.
