### ISSUE TITLE
Crash on Raster to contour

### ISSUE THREAD

**Issue by ChrisCarrigan** [qgis/QGIS#49821]
## User Feedback

Doing a extract of contours from raster at 1m crashed at 98% completion. 

## Report Details

**Crash ID**: [ee2e21046ae5579cc2f96cda25bc7b17113a2b5d](https://github.com/qgis/QGIS/search?q=ee2e21046ae5579cc2f96cda25bc7b17113a2b5d&type=Issues)

**Stack Trace**
<pre>
QObject::thread :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.1-Bia?owie?a
QGIS code revision: 663dcf8fb9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.0
Running against GDAL: 3.4.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

take a DTM_2m raster specifically SX19sw_DTM_2m from the UK gov site and convert to contour. Can't upload this as not a supported file type.  

### Versions

QGIS Version: 3.22.1-Bia?owie?a

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
> take a DTM_2m raster specifically SX19sw_DTM_2m from the UK gov site and convert to contour. Can't upload this as not a supported file type.

@ChrisCarrigan you could specify the link to download the raster layer file from the UK gov site or you can use a free file sharing host to upload the raster layer file an specify the link to such file.
