### ISSUE TITLE
Displaced icons in Project properties

### ISSUE THREAD

**Issue by seabilwe** [qgis/QGIS#49857]
### What is the bug or the crash?

Whenever opening the project properties in QGIS 3.26.1, the icons in the window are misplaced.

![image](https://user-images.githubusercontent.com/56301949/185653688-06a76941-8c55-4e9e-8ebc-7d746cb73d60.png)

### Steps to reproduce the issue

![misplaced-icons](https://user-images.githubusercontent.com/56301949/185662014-568327c4-37ae-4e60-ab1a-e3ffadc74574.gif)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | b609df9ed4d
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
densityanalysis | 2022.7.6
kart | 1.0.2
latlontools | 3.6.4
LayerStyleLoader | 0.2
lizmap | 3.8.3
MagneticDeclination | 2.3.1
maplibrary | 1.2
mask | 1.10.2
Mergin | 2022.5
OpenTopography-DEM-Downloader | 1.0
OSMDownloader | 1.0.3
parcel_plugin | 3.8
profiletool | 4.2.2
qfieldsync | v4.1.1
qgis_resource_sharing | 0.16.0
qgis_stac | 1.0.0
QuickOSM | 2.1.0
quick_map_services | 0.19.29
SelectWithin | 0.4
SpeciesExplorer | 0.1
SpreadsheetLayers | 2.0.1
SRTM-Downloader | 3.1.17
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code revision
[b609df9ed4d](https://github.com/qgis/QGIS/commit/b609df9ed4d)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
densityanalysis
2022.7.6
kart
1.0.2
latlontools
3.6.4
LayerStyleLoader
0.2
lizmap
3.8.3
MagneticDeclination
2.3.1
maplibrary
1.2
mask
1.10.2
Mergin
2022.5
OpenTopography-DEM-Downloader
1.0
OSMDownloader
1.0.3
parcel_plugin
3.8
profiletool
4.2.2
qfieldsync
v4.1.1
qgis_resource_sharing
0.16.0
qgis_stac
1.0.0
QuickOSM
2.1.0
quick_map_services
0.19.29
SelectWithin
0.4
SpeciesExplorer
0.1
SpreadsheetLayers
2.0.1
SRTM-Downloader
3.1.17
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you try with a new profile ?

**Comment by DelazJ** [comment]
@nicogodet Have you been added to the team that helps triaging reports?

**Comment by nicogodet** [comment]
@DelazJ Not yet

**Comment by seabilwe** [comment]
@nicogodet Yes, I created a new profile, and it was fine. But I opened this ticket because this often happens.

**Comment by DelazJ** [comment]
@seabilwe If QGIS own tabs do not overlap under a new profile then it is probably not a QGIS issue, but something that comes from plugins you installed. Your screenshots shows settings from Mergin Maps, which is not a default tab for QGIS. so I'd suggest to deactivate that plugin and see if you still reproduce. If so, then deactivate them one by one until you find the culprit, then report to the authors (indicated in the plugin description). Thanks

**Comment by saberraz** [comment]
@seabilwe this is likely due to https://github.com/MerginMaps/qgis-mergin-plugin/issues/440

**Comment by DelazJ** [comment]
Let's close, then...
