### ISSUE TITLE
Flatpak "cannot find proj.db"

### ISSUE THREAD

**Issue by mankoff** [qgis/QGIS#49882]
### What is the bug or the crash?

When running QGIS LTS installed with flatpak:

```bash
$ flatpak run --branch=lts org.qgis.qgis
proj_create_from_database: Cannot find proj.db
```

### Steps to reproduce the issue

On my system, open QGIS. The `proj.db` error is reported, and no CRS of any files seem to be respected.

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have `PROJ_LIB=/usr/share/proj` which is a folder that does exist on the OS level, but,

```bash
$ locate proj.db
```

returns

```
/usr/share/proj/proj.db
/var/lib/flatpak/app/org.qgis.qgis/x86_64/lts/4ee848b99c0b270931a31296b40d0b4b1369de0df67297ae14b0e9046094594c/files/share/proj/proj.db
```

Among many other (miniconda) proj.db files. If I set `PROJ_LIB` to the flatpak version, nothing changes.

**Comment by mankoff** [comment]
There is a surprisingly small number of bugs and issues found when searching GitHub or Google and requiring "flatpak"

**Comment by nicogodet** [comment]
As described here : https://www.qgis.org/fr/site/forusers/alldownloads.html#flatpak, Flatpak issues should be reported on [QGIS Flatpak repo](https://github.com/flathub/org.qgis.qgis/issues)

**Comment by mankoff** [comment]
Thanks for the link to flatpak issues. Continuing conversation at https://github.com/flathub/org.qgis.qgis/issues/221
