### ISSUE TITLE
macOS PR and LTR builds are stale

### ISSUE THREAD

**Issue by multiquadric** [qgis/QGIS#49909]
### What is the bug or the crash?

QGIS on macOS prompts for a download of the latest LTR versions.

The new (latest) versions are not available for macOS due to build failures. Looking at the directories below for status and the latest versions.
https://download.qgis.org/downloads/macos/pr/?C=M;O=D
https://download.qgis.org/downloads/macos/ltr/?C=M;O=D

### Steps to reproduce the issue

n/a

### Versions

3.26.2 is not available
3.22.10 is not available

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Known issue -> https://github.com/qgis/QGIS-Mac-Packager/issues/154

**Comment by 3nids** [comment]
now fixed.
