### ISSUE TITLE
QgsMapToolEmitPoint doesn't work correctly when defined in function

### ISSUE THREAD

**Issue by Nobel9** [qgis/QGIS#49906]
### What is the bug or the crash?

I have the following simple script (which works as desired):

```
def foo(tool):
    print(tool.x(), tool.y())

canvas = iface.mapCanvas()
tool = QgsMapToolEmitPoint(canvas)
tool.setCursor(Qt.CrossCursor)
tool.canvasClicked.connect(foo)

canvas.setMapTool(tool)
```

But when i try to write the second part i a function, the Map Tool changes to the standardcursor and clicking on the Map doesnt print anything:
```
def foo(tool):
    print(tool.x(), tool.y())

def trigger():
    canvas = iface.mapCanvas()
    tool = QgsMapToolEmitPoint(canvas)
    tool.setCursor(Qt.CrossCursor)
    tool.canvasClicked.connect(foo)

    canvas.setMapTool(tool)

trigger()
```

So i added a foo(tool) at the End of the second Function. And of course this throws an error ('QgsMapToolEmitPoint' object has no attribute 'x') because tool.x() and tool.y() arent defined when i didnt click on the map:
```
def foo(tool):
    print(tool.x(), tool.y())

def trigger():
    canvas = iface.mapCanvas()
    tool = QgsMapToolEmitPoint(canvas)
    tool.setCursor(Qt.CrossCursor)
    tool.canvasClicked.connect(foo)

    canvas.setMapTool(tool)
    foo(tool)

trigger()
```

I tried to work with try and except in the function foo. It doesnt throw an error, but it doesnt work too:
```
def foo(tool):
    try:
        print(tool.x(), tool.y())
    except:
        print('xy not defined')

def trigger():
    canvas = iface.mapCanvas()
    tool = QgsMapToolEmitPoint(canvas)
    tool.setCursor(Qt.CrossCursor)
    tool.canvasClicked.connect(foo)

    canvas.setMapTool(tool)
    foo(tool)

trigger()
```

It seems QgsMapToolEmitPoint just works from inside a function when its triggered once by code...
Is there a way to fix it inside a function? I need this as a part of a plugin...
If not: is there a way to just supress just this error-message, without try/except? When in execute as Script the error is ok, but when i execute it inside a Plugin i get pushMessage in the message bar, that isnt nice...

I also tested it with QGIS 3.26 -> Same Issue

Thanks for your help

### Steps to reproduce the issue

1. Open QGIS
2. Open Python Console
3. Open New Script
4. Paste the following into the Script:
   `def foo(tool):
    print(tool.x(), tool.y())

def trigger():
    canvas = iface.mapCanvas()
    tool = QgsMapToolEmitPoint(canvas)
    tool.setCursor(Qt.CrossCursor)
    tool.canvasClicked.connect(foo)

    canvas.setMapTool(tool)
    #foo(tool)

trigger()`
6. Execute the Script -> Doesnt work
7. Comment out -> Works, but naturally throws Error

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.9-Białowieża | QGIS code revision | a8e9e6fa
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autodetect | 1.0
flurstuecksfinder-nrw | 1.1.4
ImportPhotos | 3.0.4
lizmap | 3.7.7
naficp | 1.0
nominatim | 1.4.2
points2reach | 1.0
profiletool | 4.2.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.9-Białowieża
QGIS code revision
[a8e9e6fa](https://github.com/qgis/QGIS/commit/a8e9e6fa)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autodetect
1.0
flurstuecksfinder-nrw
1.1.4
ImportPhotos
3.0.4
lizmap
3.7.7
naficp
1.0
nominatim
1.4.2
points2reach
1.0
profiletool
4.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Not a QGIS issue.

Inside `trigger`, canvas, tool are local variable and will be destroyed as soon as you leave the function.
Set canvas as argument and defining tool as a global variable will work but it is quite ugly.
```python
def trigger(canvas):
    global tool
    tool = QgsMapToolEmitPoint(canvas)
    tool.setCursor(Qt.CrossCursor)
    tool.canvasClicked.connect(foo)
    canvas.setMapTool(tool)
```
