### ISSUE TITLE
QgsFeature in Python isn't hashable anymore

### ISSUE THREAD

**Issue by jmonticolo** [qgis/QGIS#49932]
### What is the bug or the crash?

When I try to hash a `QgsFeature` object on the new QGIS 3.26.2 (Windows 10 21H2, Python 3.9.5), it throws the following error :

```
TypeError: unhashable type: 'QgsFeature'
```

It worked on earlier versions (on 3.26.1).

Is-it intended ?

### Steps to reproduce the issue

1. Open the Python Console
2. Load a geometry layer with at least one feature
3. Execute the following code :
    ```py
    # get the active layer
    vl = iface.activeLayer()
    # get a list of its features
    feats = list(vl.getFeatures())
    # make a Python dict with the first feature as key
    my_dict = {feats[0]: "it produces an error on 3.26.2"}
    # or more simply
    hash(feats[0])
    ```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.26.2-Buenos Aires | Révision du code | feec3d3b12f
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.5.1
Version de Proj | 9.0.1
Version de la base de données du registre EPSG | v10.064 (2022-05-19)
Version de GEOS | 3.10.3-CAPI-1.16.1
Version de SQLite | 3.38.1
Version de PDAL | 2.4.2
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
MemoryLayerSaver | 4.0.4
qgis_resource_sharing | 0.16.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Is it for specific features or any feature will do this?

By now if this was widespread it would have caused many issues for plugins and processing scripts and I didn't get any issues with 3.27, but my build may predate the change that caused this.

**Comment by jmonticolo** [comment]
I didn't test it exhaustively, but it seems to not work with : polygons, points, polylines, curves. So, I'm tempted to say it's not specific. The "lack" of issues is maybe due to this time of the year and the very recent release of 3.26.2.

**Comment by nicogodet** [comment]
I suspect a SIP change without being able to confirm...

**Comment by agiudiceandrea** [comment]
I can confirm that the issue does occur using QGIS 3.26.2 and QGIS 3.27.0-Master (81ac7eb29d) and that it didn't occur using QGIS 3.26.1.
The issue doesn't occur also using QGIS 3.22.10.

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.27.0-Mater at commit fd59c5acd0 while it does occur at commit fc5faa84bf.
The commit comparison https://github.com/qgis/QGIS/compare/fd59c5a...fc5faa8 makes me think the issue may be a side effect of https://github.com/qgis/QGIS/pull/49523 (or https://github.com/qgis/QGIS/pull/49411)

**Comment by agiudiceandrea** [comment]
I've checked that the issue occurs at https://github.com/qgis/QGIS/commit/26eaa24934d3dc23654419d7e0c372e969e0f6e0 while it doesn't occur at https://github.com/qgis/QGIS/commit/d6a9d7b2ad9bb3d5a23d2e98e96fbf937b60b3ca. That should confirm the issue is related to https://github.com/qgis/QGIS/pull/49523.
