### ISSUE TITLE
qgis won't start without DISPLAY env var

### ISSUE THREAD

**Issue by trbjo** [qgis/QGIS#49935]
### What is the bug or the crash?

On wayland, that doesn't use DISPLAY, the env var is still needed. 

Code should be written to not require that if `XDG_SESSION_TYPE=wayland`

### Steps to reproduce the issue

Open a terminal in a wayland session.

run qgis. 

To alleviate the issue:
Run `export DISPLAY=:0` before launching qgis. 

### Versions

QGIS 3.27.0-Master 'Master' (0a45c064bd1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Using Arch Linux.

**Comment by nyalldawson** [comment]
Current QGIS versions aren't really wayland compatible. They kind of work, but with lots of bugs. We can't get offer decent Wayland support before moving to Qt 6 based builds, as all the serious wayland work is only available in Qt 6+.

For now, I'd strongly recommend sticking to an x11 session.
