### ISSUE TITLE
Generate XYZ tiles freezes on / never advances past 1% progress

### ISSUE THREAD

**Issue by bellegis** [qgis/QGIS#49931]
### What is the bug or the crash?

Attempting to make tiles out of a small geoTIFF (113 MB). 

When I run the program, it does not give any feedback (no fail error) but does not advance past 1% progress.

OS is Mac and here is the dialog box with QGIS version 3.22.9-Białowieża and other details
<img width="1047" alt="Screen Shot 2022-08-23 at 8 19 07 AM" src="https://user-images.githubusercontent.com/21337146/186159262-f2a87b65-5418-4817-b6c9-f321b00fe9d2.png">

### Steps to reproduce the issue

Extent: Calculate from layer 
-68.189041875,112.567014849,19.997011249,77.552965717 [EPSG:4326]

Min Zoom 12
Max Zoom 21

DPI 96

Background color #000000 
0% opacity

Tile format JPG

Quality 75

Metatile size originally used default 4, but have tried 20, same thing happens

Here is the log, there is never any additional info in the log, because it just stays at 1%:

QGIS version: 3.22.9-Białowieża
QGIS code revision: a8e9e6fae5
Qt version: 5.14.2
Python version: 3.8.7
GDAL version: 3.2.1
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 6.3.2, May 1st, 2020
Algorithm started at: 2022-08-23T08:39:24
Algorithm 'Generate XYZ tiles (Directory)' starting…
Input parameters:
{ 'BACKGROUND_COLOR' : QColor(0, 0, 0, 0), 'DPI' : 96, 'EXTENT' : '-68.189041875,112.567014849,19.997011249,77.552965717 [EPSG:4326]', 'METATILESIZE' : 2, 'OUTPUT_DIRECTORY' : '/Users/irlipton/Downloads', 'OUTPUT_HTML' : '/Users/irlipton/Downloads/index.html', 'QUALITY' : 75, 'TILE_FORMAT' : 1, 'TILE_HEIGHT' : 256, 'TILE_WIDTH' : 256, 'TMS_CONVENTION' : False, 'ZOOM_MAX' : 21, 'ZOOM_MIN' : 12 }

### Versions

3.22.9-Białowieża
QGIS code revision: a8e9e6fae5
Qt version: 5.14.2
Python version: 3.8.7
GDAL version: 3.2.1
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 6.3.2, May 1st, 2020

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

No tile folders or index.html show up in designated file path

**Comment by nicogodet** [comment]
@bellegis I can't reproduce on 3.22.10 and 3.26.2.

Can you provide the raster file so we can test in exact same condition ?

**Comment by bellegis** [comment]
@nicogodet thanks, yes: https://drive.google.com/file/d/12T4QzRzGWaYKi-13MsYUZ2DsPgGzi0oT/view?usp=sharing

**Comment by nicogodet** [comment]
This is a very large extent at a high zoom level.
My guess is that it will just take times. How long did you wait ?

It took 15mins to compute level 12 here
![image](https://user-images.githubusercontent.com/39594821/186169719-816f9704-9d2b-438e-a702-aab43c693c59.png)
I stopped the alg after

**Comment by bellegis** [comment]
Thanks @nicogodet. I did just run level 12 for about thirty minutes and it did get to 2%. And at 2% it did add the tiles folder to the output directory. Without knowing the expected behavior, I wasn't sure if it's a bug, but looks like the problem is just the slowness.

**Comment by nicogodet** [comment]
So no issue 😃 

Slowness is not a bug but depends on your computing power.
