### ISSUE TITLE
GPS information panel (information in panel is not correct)

### ISSUE THREAD

**Issue by mhnplm** [qgis/QGIS#49948]
### What is the bug or the crash?

see BUG #48483 which has been completed with more info
"Quick status indicator" shows wrong value, "RED" even if signal is strong

### Steps to reproduce the issue

see BUG #48483 which has been completed with more info

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.10-Białowieża | QGIS code revision | 6a63fd37b0
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.4 (Ubuntu 14.4-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.29
Discovery | 2.5.7
Qgis2threejs | 2.7.1
processing | 2.12.99
MetaSearch | 0.3.5
db_manager | 0.1.20
sagaprovider | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.22.10-Białowieża
QGIS code revision
[6a63fd37b0](https://github.com/qgis/QGIS/commit/6a63fd37b0)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.4 (Ubuntu 14.4-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
quick_map_services
0.19.29
Discovery
2.5.7
Qgis2threejs
2.7.1
processing
2.12.99
MetaSearch
0.3.5
db_manager
0.1.20
sagaprovider
2.12.99
grassprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I did not succeed in reopening the old bug report, sorry

**Comment by nicogodet** [comment]
> I did not succeed in reopening the old bug report, sorry

@mhnplm I can. Should I re-open ?

**Comment by mhnplm** [comment]
Yes, please, then I perhaps can add more info.

Regards Per

Den tors 25 aug. 2022 09:47Nicolas Godet ***@***.***> skrev:

**Comment by alexbruy** [comment]
Is this still an issue? Seems this is the same as #48483 which is already fixed.

**Comment by mhnplm** [comment]
Hello,

It's not an issue for me anymore :) /Per

QGIS-version

3.28.11-Firenze


QGIS kodrevision

b02458a196 <https://github.com/qgis/QGIS/commit/b02458a196>

Qt version

5.15.3

Python version

3.10.12

GDAL/OGR version

3.4.1

PROJ version

8.2.1

Den fre 27 okt. 2023 kl 11:02 skrev Alexander Bruy ***@***.***
