### ISSUE TITLE
Crash on exit

### ISSUE THREAD

**Issue by dataspun** [qgis/QGIS#49940]
## User Feedback

Closing QGIS

## Report Details

**Crash ID**: [c58a631124b05c88ebe1dc137d9decdd85863c90](https://github.com/qgis/QGIS/search?q=c58a631124b05c88ebe1dc137d9decdd85863c90&type=Issues)

**Stack Trace**
<pre>
CRYPTO_memcmp :
QCA::BigInteger::fromString :
QCA::BigInteger::fromString :
QCA::PKeyContext::publicFromPEM :
QCA::deinit :
QCA::Initializer::~Initializer :
QgsAuthManager::~QgsAuthManager :
QgsAuthMethodRegistry::operator= :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
QgsPluginRegistry::operator= :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.18.3-Zurich
QGIS code branch: Release 3.18
Compiled against Qt: 5.12.9
Running against Qt: 5.12.9
Compiled against GDAL: 3.3.3
Running against GDAL: 3.3.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Click the X or close QGIS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code branch | Release 3.18
-- | -- | -- | --
Compiled against Qt | 5.12.9 | Running against Qt | 5.12.9
Compiled against GDAL/OGR | 3.3.3 | Running against GDAL/OGR | 3.3.3
Compiled against GEOS | 3.10.0-CAPI-1.16.0 | Running against GEOS | 3.10.0-CAPI-1.16.0
Compiled against SQLite | 3.36.0 | Running against SQLite | 3.39.2
Compiled against PDAL | 2.3.0 | Running against PDAL | 2.3.0 (git-version: Release)
PostgreSQL Client Version | 13.3 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.6 | QScintilla2 Version | 2.11.2
Compiled against PROJ | 8.1.1 | Running against PROJ | Rel. 8.1.1, September 1st, 2021
OS Version | Windows 10 (10.0)
Active python plugins | basinscout_processing; DataPlotly; plugin_reloader; db_manager; MetaSearch; processing

</body></html>QGIS version
3.18.3-Zürich
QGIS code branch
[Release 3.18](https://github.com/qgis/QGIS/tree/release-3_18)
Compiled against Qt
5.12.9
Running against Qt
5.12.9
Compiled against GDAL/OGR
3.3.3
Running against GDAL/OGR
3.3.3
Compiled against GEOS
3.10.0-CAPI-1.16.0
Running against GEOS
3.10.0-CAPI-1.16.0
Compiled against SQLite
3.36.0
Running against SQLite
3.39.2
Compiled against PDAL
2.3.0
Running against PDAL
2.3.0 (git-version: Release)
PostgreSQL Client Version
13.3
SpatiaLite Version
5.0.1
QWT Version
6.1.6
QScintilla2 Version
2.11.2
Compiled against PROJ
8.1.1
Running against PROJ
Rel. 8.1.1, September 1st, 2021
OS Version
Windows 10 (10.0)
Active python plugins
basinscout_processing; 
DataPlotly; 
plugin_reloader; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

QGIS installed only in a conda virtual environment.

**Comment by nicogodet** [comment]
> QGIS Version: 3.18.3-Zurich

This version is EOL -> please upgrade to 3.22.10 or 3.26.2

> Active python plugins basinscout_processing; DataPlotly; plugin_reloader;

They are not part of core python plugins -> please try with a new profile

**Comment by dataspun** [comment]
@nicogodet thanks!  Does qgis team update the conda-forge packages, as that's the source of the EOL version.

**Comment by nicogodet** [comment]
@dataspun QGIS Organisation is not in charge of conda-forge package. I remember conda team had trouble to update the package...

**Comment by nicogodet** [comment]
I close but feel free to comment if you encounter the bug on a supported version of QGIS.
