### ISSUE TITLE
can't add layer > vector layer from database Mysql

### ISSUE THREAD

**Issue by zura1sama** [qgis/QGIS#49951]
### What is the bug or the crash?

Invalid Data Source : MySQL:qgis,host=localhost,port=3306|option:TABLES=bangunan is not a valid or recognized data source.
![image](https://user-images.githubusercontent.com/94884636/186571654-8ec93bc9-f054-416d-afcf-a879b7db1808.png)

The database name and the table
![image](https://user-images.githubusercontent.com/94884636/186571527-f6727432-f861-4a49-a57d-9775493376b5.png)

The table sturctur
![image](https://user-images.githubusercontent.com/94884636/186572136-56234f2d-d392-45f3-a8f7-0e9d73e1c3b3.png)

![image](https://user-images.githubusercontent.com/94884636/186572287-ea907215-cdc4-43f0-a21a-cc76a53dee51.png)

but it's work in Qgis ver. 2.8

### Steps to reproduce the issue

1.
![image](https://user-images.githubusercontent.com/94884636/186571796-0c5e7f50-7760-4db5-b72e-3bf420855912.png)

2.
![image](https://user-images.githubusercontent.com/94884636/186571869-3a607a9f-a1d7-49c2-9358-afa73d34fa0b.png)

3.Test connection
![image](https://user-images.githubusercontent.com/94884636/186572569-270f0c6c-bc52-4bff-a1f9-08196ae882ad.png)

4. after click add
![image](https://user-images.githubusercontent.com/94884636/186571918-ad7a3bd2-2cb0-4d32-a434-5235ca652b54.png)

### Versions

QGIS version
3.16.16-Hannover
QGIS code revision
f5778a89df
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.16 is EOL. Please try with 3.22.10 or 3.26.2.

**Comment by zura1sama** [comment]
thanks for the suggestion

I was tried both Qgis ver. 3.22.10 & 3.26.2 and had same result.

Ver. 3.22.10
![3 22 10](https://user-images.githubusercontent.com/94884636/186801897-db106c6a-c334-4ac1-8426-87e3947a4d85.PNG)

Ver. 3.26.2
![3 26 2](https://user-images.githubusercontent.com/94884636/186801973-e4a3b36e-dede-4ed1-964d-8d4e600ddbd0.PNG)

**Comment by nicogodet** [comment]
Could you share a dump of the layer ?

Is it the same if you add the MS SQL connection first in browser then you try to add the layer ?

**Comment by zura1sama** [comment]
> Could you share a dump of the layer ?

sure. anyway... I was imported it to Mysql with FWtools "ogr2ogr" from SHP file and was tried with plugin called MySQL Importer, but still got same result.
[bangunan.zip](https://github.com/qgis/QGIS/files/9431937/bangunan.zip)

> Is it the same if you add the MS SQL connection first in browser then you try to add the layer ?

this is what you mean ?, if so... still had same result

https://user-images.githubusercontent.com/94884636/186873559-64947dc0-691b-4324-9abd-5af6eed94b33.mp4

**Comment by zura1sama** [comment]
i don't know why... work well in Qgis 2.8.9. Unfortunately, ver 2.8.9 not compatible anymore with plugin or XYZ tile 

https://user-images.githubusercontent.com/94884636/186877198-42618de1-3884-495e-a003-2afae4358ffd.mp4

please help me. 

Thank you so much

**Comment by nicogodet** [comment]
> this is what you mean ?, if so... still had same result

I mean this
![image](https://user-images.githubusercontent.com/39594821/186894691-29bb49f2-413d-4897-8972-9081da7ff4c1.png)

**Comment by zura1sama** [comment]
oh i see... surely won't connected because I used MySQL with mariaDB engine database 

![image](https://user-images.githubusercontent.com/94884636/186971529-4a7d9f80-b972-4894-a114-6c524b30f29f.png)

**Comment by rduivenvoorde** [comment]
@nicogodet MySQL(spatial) != MSSQL (which is Micrsoft SQL Server)

MySQL and MariaDB are (I think pretty much interchangeable?)

@zura1sama can you view the data in other spatial viewers?

OR are you able to view other spatial tables in QGIS?

(just to be sure it is not a data issue)

**Comment by zura1sama** [comment]
> @zura1sama can you view the data in other spatial viewers?

sure, i was it tried on Qgis ver 2.8.9, I can view well with it.

> i don't know why... work well in Qgis 2.8.9. Unfortunately, ver 2.8.9 not compatible anymore with plugin or XYZ tile
>  qgis2.9.8.mp4

> OR are you able to view other spatial tables in QGIS?

I have no other table on MySQL database, I have same table with PostgreSQL Database and can view well with it.

https://user-images.githubusercontent.com/94884636/187113967-3c313fb6-0e71-4d32-a695-73050495a759.mp4

**Comment by bbrala** [comment]
Just stepping in to say, same problem. Set of tables with perfectly valid geometry, they add, it scans and count, it knows what type of geometry is contained in the layer. No go.

MySQL 5.7 - qGis - 3.28.3 

I've tried on windows, and in WSL (ubuntu 22.04)

**Comment by rduivenvoorde** [comment]
@bbrala out of curiosity, I installed mariadb-server on my Debian laptop, imported the sql from @ zura1sama and could see the data in QGIS (via ogr database connection).
So please show more information (eg which driver were you using?), or share some example data.
Else I propose to close this issue

**Comment by rduivenvoorde** [comment]
![Screenshot from 2023-02-26 11-06-51](https://user-images.githubusercontent.com/731673/221404257-faa03a35-3066-4442-b2d3-c87d8bab4042.png)

![Screenshot from 2023-02-26 11-07-38](https://user-images.githubusercontent.com/731673/221404267-8fe4f42b-27e8-473f-af1b-340886a14980.png)

**Comment by alexbruy** [comment]
Is this still an issue? Works fine for me using OGR driver with latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc) on Linux.

**Comment by bbrala** [comment]
Good question, haven't needed since. But seeing little others it might not be an issue anymore.

Verzonden vanaf Outlook voor Android<https://aka.ms/AAb9ysg>
________________________________
