### ISSUE TITLE
Raster file transparency 

### ISSUE THREAD

**Issue by Geonick-Straddie** [qgis/QGIS#49953]
### What is the bug or the crash?

When I use the raster (colour multiband) transparency function to change white to transparent using the picker, the area concerned changed to cyan, and then the red in the image disappeared - had to go back to grey scale, then back to multiband colour to reinstate.  My very experienced colleague tried it on the Linux version and it did the same.

### Steps to reproduce the issue

1. Layer properties transparency - currently a multiband colour image
2. Choose picker to make white edges transparent
3. Transparent area turned cyan
4. Loss of red end of the colour spectrum from multiband colour image (and the white gone too...)
5. Solved with a change to grey, then back to multiband colour
6. The correct colours are preserved when you open the file from scratch, it is just when you change things around ... not all the time but perhaps 50 % .... and I have not worked out quite the routine that prevents or causes the issue.

### Versions

3.26.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![Screenshot_17](https://user-images.githubusercontent.com/48612774/186581165-b408a38c-3ff0-442d-920f-aebc81af53cd.jpg)

**Comment by nicogodet** [comment]
Could you provide a sample project and data to reproduce ?

**Comment by Geonick-Straddie** [comment]
Sure, I will make a small simple file. Cheers

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by nicogodet** [comment]
Make sure to share it directly on Github (and not via email) is you plan to attach something or use a sharing link.

**Comment by Geonick-Straddie** [comment]
Thanks, will do

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
