### ISSUE TITLE
QGIS crashed while loading a new raster

### ISSUE THREAD

**Issue by sebanti-m** [qgis/QGIS#49954]
## User Feedback

Adding raster layer. None of the options like Geoprocessing>buffer are showing up when I click on the Vector legend. Please fix this.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004028 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

1. Layer> Add layer> Add raster layer> Data Source Manager| Raster 
2. QGIS crashed

### Versions

3.26.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Try with a new profile 
Settings -> User profiles -> New profile...

**Comment by sebanti-m** [comment]
Working from a new profile resolved this issue. Thank you so much for your suggestions!
