### ISSUE TITLE
Project Export DXF: Output Layer Attribute not visible

### ISSUE THREAD

**Issue by MalikAlMaut** [qgis/QGIS#49958]
### What is the bug or the crash?

The column 'Layer' and the column 'Output Layer Attribute' in the Project DXF Export cannot be resized. Consequently the option 'Output Layer Attribute' is not visible without scrolling at the bottom. 

![grafik](https://user-images.githubusercontent.com/102646618/186608638-1ddd329c-a0b8-40d5-930a-7236a1482cba.png)
![grafik](https://user-images.githubusercontent.com/102646618/186608809-0ece4ef4-5a90-4dee-9c97-b943c9159b45.png)

### Steps to reproduce the issue

Project -> Import/Export -> Export Project to DXF...

### Versions

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I suspect, many don't even know of this possibility (see [issue 48724)](https://github.com/qgis/QGIS/issues/48724)

**Comment by DelazJ** [comment]
This is a regression considering that it is currently impossible to resize the columns so that they fall in the "table" extent. That was possible in the past, as shown in [the docs](https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/create_layers.html#creating-new-dxf-files)

**Comment by alexbruy** [comment]
Duplicates #45441.
