### ISSUE TITLE
Buffer tool not opening

### ISSUE THREAD

**Issue by sebanti-m** [qgis/QGIS#49956]
### What is the bug or the crash?

vector icon under menu toolbar is not showing the drop-down menu of different tools (like Geoprocessing). 

### Steps to reproduce the issue

1. Go to menu toolbar
2. Click on "Vector"
3. The drop-down menu is not displayed 

### Versions

3.26.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Try with a new profile and check that "Processing" is enabled in extensions.

**Comment by sebanti-m** [comment]
Thank you. It worked!
