### ISSUE TITLE
PyQgis: Second Iteration over Features doesnt work without new definition of Features

### ISSUE THREAD

**Issue by asdro-f** [qgis/QGIS#49967]
### What is the bug or the crash?

When i try two iterate twice over features of a Layer with PyQgis, the second iteration seems to do nothing... It is fixed by defining the features again.

Why does this happen? i do not delete the variable where the Features are saved in...

### Steps to reproduce the issue

1. Open QGis
2. Load a Vectorlayer with features
3. Open Python Console
4. Open Empty Script
5. Copy the following into it: 
```
fs = iface.activeLayer().getFeatures()

for f in fs:
    print(1)
    print(f)

for f in fs:
    print(2)
    print(f)
```
6. Execute -> Second Loop doesnt work
7. Add ```fs = iface.activeLayer().getFeatures()``` befor the second loop
8. Execute again -> Second Loop works

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.22.9-Białowieża | QGIS-Codeversion | a8e9e6fa
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.5.1
PROJ-Version | 9.0.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.3-CAPI-1.16.1
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 14.3
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS-Version
3.22.9-Białowieża
QGIS-Codeversion
[a8e9e6fa](https://github.com/qgis/QGIS/commit/a8e9e6fa)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.1
PROJ-Version
9.0.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
14.3
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Definitely not a QGIS issue.

When you iterate over `fs`, it "empty" it.
So obviously it will fail if you try again.

Best to reference the layer then call `getFeatures()` at each loop.
