### ISSUE TITLE
Layout PDF export ignores styles of OTF fonts

### ISSUE THREAD

**Issue by stees** [qgis/QGIS#49976]
### What is the bug or the crash?

Layout PDF export ignores styles of OTF fonts. The example below uses fonts Museo (OTF) and Segoe UI (TTF).

Print composer
<img width="538" alt="image" src="https://user-images.githubusercontent.com/57099996/187009256-24af1a98-6d60-4252-9b39-b1fc73a0f75d.png">

Exported PDF
<img width="692" alt="image" src="https://user-images.githubusercontent.com/57099996/187009262-0c5080dd-0978-4bb0-ae67-46c508df3bed.png">

PDF export options
![image](https://user-images.githubusercontent.com/57099996/187009297-54ad60aa-2463-49b2-a10d-c9bddc046ab9.png)

### Steps to reproduce the issue

Project > print composer > add label > use a OTF and a TTF font with bold or black style > export as PDF

### Versions

3.16 Hannover and 3.22 Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Seems works fine with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc)
![image](https://github.com/qgis/QGIS/assets/776954/3e5f21cc-8ded-40c6-ba07-d3312dccf2f2)
