### ISSUE TITLE
Export mesh faces no longer works with tested E3T 2DM files - Wrong or missing parameter value: Dataset groups

### ISSUE THREAD

**Issue by Brent-Edwards** [qgis/QGIS#49973]
### What is the bug or the crash?

The "Export mesh faces" processing tool does not seem to recognize datasets in 2DM files and therefore won't run and yields the "Wrong or missing parameter value: Dataset groups" warning.

### Steps to reproduce the issue

1) Load sample 2DM file
[test_simple_e3t_2dm_file.zip](https://github.com/qgis/QGIS/files/9435395/test_simple_e3t_2dm_file.zip)

2) Check Available Datasets (see attached screenshot)
![image](https://user-images.githubusercontent.com/13538726/186964985-eca96184-201f-44af-bb6d-1bd82406cc50.png)

3) Attempt to run the "Export mesh faces" processing tool. Note that no "Dataset groups" can be selected as none are available.

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
basemesh
2.0.11
changeDataSource
3.1
DataPlotly
3.9
gmsh
version 0.2.2
HCMGIS
22.8.8
ImportPhotos
3.0.3
LAStools
1.4
latlontools
3.6.4
leastcostpath
1.0
openlayers_plugin
2.0.0
processing_fusion
3.3
QPackage
1.5
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.29
splitmultipart
1.0.0
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Confirmed on Master too

**Comment by vcloarec** [comment]
Indeed, the "bed elevation" dataset group is a dataset set group on vertices, not on faces. And the algorithm does not allow exporting mesh element with no dataset group selected. As there is no dataset group on faces, export faces is for now not possible.
The solution should to allow export elements without dataset, the result will be a vector layer without field associated to dataset group.

**Comment by nicogodet** [comment]
@vcloarec So it's a feature request ?

**Comment by vcloarec** [comment]
@nicogodet , not sure... we are on the borderline between bug and feature request...

**Comment by Brent-Edwards** [comment]
> 
This seems to be a new constraint. I don't have a previous LTR on my machine to test, but the tool worked since the early Crayfish plugin days until recently without the described constraint. The "Export mesh faces" worked with the default "Bed elevation" dataset group yielding a polygonZ layer with z values from the "Bed elevation".

**Comment by Brent-Edwards** [comment]
> Previously, this alg was part of Crayfish plugin and is now part of QGIS core (between 3.16 and 22, don't remember). This "regression" could be link to the portage.

Just to be clear, the tool worked since its integration into the QGIS core and the dataset group constraint happened sometime in the last few QGIS versions.

**Comment by vcloarec** [comment]
I think this issue comes from https://github.com/qgis/QGIS/pull/47197
