### ISSUE TITLE
QGIS crash on Identify Feature tool click on map

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#50008]
### What is the bug or the crash?

QGIS ends unexpectedly when using the Identify Feature tool on the map

### Steps to reproduce the issue

1). Activated Identify Feature tool 
2). Click on the map 
3). QGIS ends unexpectedly

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
coordinates_converter | 1.0
LandXml | 2.3
latlontools | 3.6.3
MagneticDeclination | 2.3.1
profiletool | 4.2.2
QCopycanvas | 0.5
qfieldsync | v4.1.1
qgis2web | 3.16.0
qgis_resource_sharing | 0.16.0
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code revision
[feec3d3b12f](https://github.com/qgis/QGIS/commit/feec3d3b12f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
LandXml
2.3
latlontools
3.6.3
MagneticDeclination
2.3.1
profiletool
4.2.2
QCopycanvas
0.5
qfieldsync
v4.1.1
qgis2web
3.16.0
qgis_resource_sharing
0.16.0
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

It does not seem to matter if identify results are set to Mode: Top Down or Current Layer
I saved the project to a new project, and the error persisted as before.

Report details from Uh-oh! window:

Windows fatal exception: access violation

Current thread 0x00001da4 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by MrChebur** [comment]
Try clean (new) profile it may be caused by plugins.
