### ISSUE TITLE
Predefining project properties, such as data storage location

### ISSUE THREAD

**Issue by joergdd** [qgis/QGIS#50002]
### Feature description

When creating a new project, you should be prompted to define the following project parameters:
- Project folder
- Project file name
- Folder for source data (below the project folder), default: "Sources"
- possibly the project coordinate system to be used

When adding geodata files, you should then be asked whether the source data should be automatically copied OR moved to the source data folder.

This minimizes the possibility of error that you pass on QGIS projects without source data.

**Comment by nyalldawson** [comment]
This isn't something which belongs in qgis itself -- it's very specific to certain user requirements and instead should be solved via a plugin.
