### ISSUE TITLE
QGIS stop working (qgis-ltr-bin.exe has stopped working) while exceute python console

### ISSUE THREAD

**Issue by AmazeCoconut** [qgis/QGIS#50017]
### What is the bug or the crash?

Crash ID: [bc82a4793acf4314e56037aa779d5bc116b95bd5](https://github.com/qgis/QGIS/search?q=bc82a4793acf4314e56037aa779d5bc116b95bd5&type=Issues)

Stack Trace

QgsVectorLayer::~QgsVectorLayer :
PyInit__core :
QgsMapLayerStore::removeMapLayers :
QgsMapLayerStore::removeMapLayer :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyDict_GetItemString :
PyArena_New :
PyRun_StringFlags :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFloat_FromDouble :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.10-Bia?owie?a
QGIS code revision: 6a63fd37
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

### Steps to reproduce the issue

I run below script, only this script make QGIS crash.
========================
Sel_layer=iface.activeLayer()
Sel_features = Sel_layer.selectedFeatures()
fields = Sel_layer.fields()
siteList=[]
for Sel_feat in Sel_features:
    Site5Digit =Sel_feat.attribute("Sitename")
    siteList.append(Site5Digit)
siteList.append('xxxxx')
#**** Remove duplicate site 5 digit list by convert list to dict then convert back to list
siteList = list(dict.fromkeys(siteList))
#print (siteList)

siteListTuple=tuple(siteList)
print (siteListTuple)

layersH=QgsProject.instance().mapLayersByName('PMS PRB H')
if layersH:
    QgsProject.instance().removeMapLayer(layersH[0].id())
statLayer_H = QgsVectorLayer("Point?crs=epsg:4326", "PMS PRB H", "memory")

layersM=QgsProject.instance().mapLayersByName('PMS PRB M')
if layersM:
    QgsProject.instance().removeMapLayer(layersM[0].id())
statLayer_M = QgsVectorLayer("Point?crs=epsg:4326", "PMS PRB M", "memory")

layersL=QgsProject.instance().mapLayersByName('PMS PRB L')
if layersL:
    QgsProject.instance().removeMapLayer(layersL[0].id())
statLayer_L = QgsVectorLayer("Point?crs=epsg:4326", "PMS PRB L", "memory")
print('Removed PMS Layer')
provider_H = statLayer_H.dataProvider()
provider_M = statLayer_M.dataProvider()
provider_L = statLayer_L.dataProvider()
statLayer_H.startEditing()
statLayer_M.startEditing()
statLayer_L.startEditing()
provider_H.addAttributes(fields)
provider_M.addAttributes(fields)
provider_L.addAttributes(fields)
statLayer_H.updateFields()
statLayer_M.updateFields()
statLayer_L.updateFields()
print('Finish create field')
Systems=['4G1800','4G2100','4G2100_TOT','4G2600_F5','4G2600_F1','4G900','4G700']
for Sys in Systems:
    layer=QgsProject.instance().mapLayersByName(Sys)[0]
    print (layer)
    layer.selectByExpression("\"Sitename\" IN {}".format(siteListTuple))
    if layer.selectedFeatureCount()!=0:
        for feat in layer.selectedFeatures():
            x1=feat['Long']
            y1=feat['Lat']
            DIR=feat['DIR']
            SecType=feat['Sectoromni']
            xSystem=feat['System']
            CellName = feat['Cellname']
            Offset = 0
            if SecType == 'OMNI':
                Width = 15
                if CellName[9:10] == 'P':
                    Offset = 0
                elif CellName[9:10] == 'Q':
                    Offset = 32.7
                elif CellName[9:10] == 'R':
                    Offset = 65.4
                elif CellName[9:10] == 'S':
                    Offset = 98.1
                elif CellName[9:10] == 'T':
                    Offset = 130.9
                elif CellName[9:10] == 'U':
                    Offset = 163.6
                elif CellName[9:10] == 'V':
                    Offset = 196.36
                elif CellName[9:10] == 'W':
                    Offset = 229.1
                elif CellName[9:10] == 'X':
                    Offset = 261.8
                elif CellName[9:10] == 'Y':
                    Offset = 294.5
                elif CellName[9:10] == 'Z':
                    Offset = 327.2
                            
            if xSystem=='4G1800':
                scale=100
            elif xSystem=='4G2100':
                scale=150
            elif xSystem=='4G2100_TOT':
                scale=500
            elif xSystem=='4G2600_F1':
                scale=150
            elif xSystem=='4G2600_F5':
                scale=100
            elif xSystem=='4G900':
                scale=85
            elif xSystem=='4G700':
                scale=70
            else:
                scale=50
            SecSize=feat['SectorSize']/scale
            angle = math.radians(DIR + Offset + 90)
            Dx, Dy = \
            (SecSize * math.cos(angle), SecSize * math.sin(angle))
            x2=x1-Dx
            y2=y1+Dy
            feat.setGeometry(QgsGeometry.fromPointXY(QgsPointXY(x2,y2)))
            if layer.name() in ('4G2600_F5','4G2600_F1'):
                statLayer_H.addFeature(feat)
            elif layer.name() in ('4G1800','4G2100','4G2100_TOT'):
                statLayer_M.addFeature(feat)
            elif layer.name() in ('4G900','4G700'):
                statLayer_L.addFeature(feat)
        layer.removeSelection()
    else:
        print('{} No selected feature'.format(Sys))

#Create calculate field SysId 
SysIdField = QgsField( 'SysId', QVariant.String )
statLayer_H.dataProvider().addAttributes([SysIdField])
statLayer_M.dataProvider().addAttributes([SysIdField])
statLayer_L.dataProvider().addAttributes([SysIdField])
statLayer_H.updateFields()
statLayer_M.updateFields()
statLayer_L.updateFields()
statLayer_H.endEditCommand() # Stop editing return TRUE
statLayer_M.endEditCommand() # Stop editing return TRUE
statLayer_L.endEditCommand() # Stop editing return TRUE
statLayer_H.commitChanges() # Save changes return TRUE
statLayer_M.commitChanges() # Save changes return TRUE
statLayer_L.commitChanges() # Save changes return TRUE
QgsProject.instance().addMapLayer(statLayer_H)
QgsProject.instance().addMapLayer(statLayer_M)
QgsProject.instance().addMapLayer(statLayer_L)
expression = QgsExpression('substr( Cellname ,7,3)')
context = QgsExpressionContext()
#print(expression.hasParserError())
context.appendScopes(QgsExpressionContextUtils.globalProjectLayerScopes(statLayer_H))
context.appendScopes(QgsExpressionContextUtils.globalProjectLayerScopes(statLayer_M))
context.appendScopes(QgsExpressionContextUtils.globalProjectLayerScopes(statLayer_L))

with edit(statLayer_H):
    for f in statLayer_H.getFeatures():
        #print (f['Cellname'])
        context.setFeature(f)
        f['SysId'] = expression.evaluate(context)
        statLayer_H.updateFeature(f)

with edit(statLayer_M):
    for f in statLayer_M.getFeatures():
        #print (f['Cellname'])
        context.setFeature(f)
        f['SysId'] = expression.evaluate(context)
        statLayer_M.updateFeature(f)

with edit(statLayer_L):
    for f in statLayer_L.getFeatures():
        #print (f['Cellname'])
        context.setFeature(f)
        f['SysId'] = expression.evaluate(context)
        statLayer_L.updateFeature(f)
        

layer_settings  = QgsPalLayerSettings()
layer_settings.isExpression = True
text_format = QgsTextFormat()

text_format.setFont(QFont("Arial", 2))
text_format.setSize(6)
buffer_settings = QgsTextBufferSettings()
buffer_settings.setEnabled(True)
buffer_settings.setSize(1)
buffer_settings.setColor(QColor("white"))

text_format.setBuffer(buffer_settings)
layer_settings.setFormat(text_format)
#layer_settings.fieldName = "concat(SysId,':',QueryStat_AVG_PRB_DL)"
layer_settings.fieldName = "concat(SysId,':')"
layer_settings.placement = 6

layer_settings.enabled = True

layer_settings = QgsVectorLayerSimpleLabeling(layer_settings)
statLayer_H.setLabelsEnabled(False)
statLayer_H.setLabeling(layer_settings)
statLayer_M.setLabelsEnabled(False)
statLayer_M.setLabeling(layer_settings)
statLayer_L.setLabelsEnabled(False)
statLayer_L.setLabeling(layer_settings)

Sel_layer.removeSelection()

iface.setActiveLayer(Sel_layer)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.10-Białowieża | QGIS code revision | 6a63fd37
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows Server 2016 Version 1607
  |   |   |  
Active Python plugins
search_site | 0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.10-Białowieża
QGIS code revision
[6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 1607

Active Python plugins
search_site
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
You need to debug you script (and properly quote it in github)...
Execute it by elementary code block.

Based on stack trace, it could come from your call of `QgsProject.instance().removeMapLayer()`
