### ISSUE TITLE
UNC Paths ...

### ISSUE THREAD

**Issue by MRK-IT-de** [qgis/QGIS#50025]
### Feature description

With / from which QGiS version are Windows UNC paths supported or possible?

### Additional context

See also https://wiki.windata.de/index.php?title=UNC-Pfad

**Comment by nicogodet** [comment]
They are supported but with forward slashes `/`
![image](https://user-images.githubusercontent.com/39594821/187614877-0f0e49c8-64e5-4b4a-a405-4a0ff9af995b.png)

If it's not what you asked for, please provide more info or describe your issue
