### ISSUE TITLE
Problemas de Python a la hora de enlazar con el proveedor de FUSION

### ISSUE THREAD

**Issue by tgc1995** [qgis/QGIS#50026]
### What is the issue about the documentation?

Hola.

Estoy teniendo problemas a la hora de enlazar a FUSION, me aparece un error de Phyton y no sé que puede estar pasando. El error es:

RuntimeError: wrapped C/C++ object of type AttachRasterValuesToLineVertices has been deleted 
Traceback (most recent call last):
  File "C:\Users/Oficina/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\TlugProcessing\ThToolBox_algorithms_provider.py", line 101, in loadAlgorithms
    self.addAlgorithm( alg )
RuntimeError: wrapped C/C++ object of type AttachRasterValuesToLineVertices has been deleted

Versión de Python: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
Versión de QGIS: 3.22.1-Białowieża Białowieża, 663dcf8fb9 

Agradecería una respuesta. Saludos

**Comment by nicogodet** [comment]
It's related to plugin `TlugProcessing`. Report the issue on plugin repo (link should be in plugin description).

Not a QGIS issue.
