### ISSUE TITLE
QGIS 3.22.10  cursor at the wrong place while writing a filter

### ISSUE THREAD

**Issue by bertramrabe** [qgis/QGIS#50030]
### What is the bug or the crash?

When I write a filter for a QGIS-Layer, the cursor is not at the right place (directly after the sign I just wrote) - the cursor seems to be further to the right. So it is difficult to write filters more complicated. The mistake does not occur when I use QGIS in American English, but it occurs for example in German or in Spanish. The mistake does not occur in QGIS 3.26, it occurs only in QGIS 3.22.10 (as far as I know the mistake did not occur in QGIS 3.22.9)

### Steps to reproduce the issue

1. Open a new filter for an existing layer
2. write for example "name"='Switzerland'

you will see, that the cursor is not at the end of ='Switzerland' - but further right. So if you want to modificate the filter, or delete some letters, it is difficult to handle.
![1](https://user-images.githubusercontent.com/56157092/187697535-01b41b1b-4d73-4218-acc1-95aad74c9d6b.png)

### Versions

QGIS 3.22.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
But I had the issue on both 3.26 ad Master few days ago and only difference was dependency upgrade that came along Ubuntu upgrade.

**Comment by bertramrabe** [comment]
yes, I am on Ubuntu jammy, it is possible that the problem occurs since the upgrade von ubuntu 20.04 to 22.04 some weeks ago.
My screen is old (1280x1024). I do not use python console, but if I start in QGIS the advanced python calculator the problem does not occur. I tried on another (very old) 32-bit laptop with the OS antix (Linux), there I installed QGIS 3.26, and there the problem did not occur.

**Comment by bertramrabe** [comment]
When I change the font size in QGIS settings from 9 to 11 - after new start of QGIS the problem remains the same.

**Comment by cliffpat** [comment]
I have the same cursor issue with Ubuntu 22.04.01 LTS (jammy) with QGIS 3.22.11 when using the python console and the expression builder. I suspect this is related to the Ubuntu version and some conflicting dependency. I tested on another machine running QGIS 3.22.9 on Ubuntu 20.04 and both the python console and expression builder work as expected. 

The only other difference between both machines is the one running Ubuntu 22.04 is running dual 4k monitors scaled to 200% whereas the other machine is a laptop with a 1920x1080 display. I also tested the issue by decreasing the resolution to 1920x1080 but no improvement. I also increased the font size in QGIS options, but no improvement.

**Comment by cliffpat** [comment]
Interesting thing just happened. The problem with at the wrong place goes away when I create a new profile. In the default profile, the cursor is never in the right location in the expression builder and the Python console, but in the new profile everything works as expected.

**Comment by alexbruy** [comment]
Still an issue with latest versions?

**Comment by bertramrabe** [comment]
I cannot check, if the issue still exists. In August 2022 the bug existed in my OS ubuntu 22.04. (QGIS 3.22.10). Later I changed my OS to LinuxMint 21, and under LinuxMint the bug did not exist. Now I don't have a PC with ubuntu any more. In LinuxMint & QGIS 3.28.11 everything is ok.
