### ISSUE TITLE
"Digitize mesh elements" (rubberband) is not persistent across tools selection

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#50037]
### What is the bug or the crash?

1. Select the "Digitize mesh elements" and start drawing a face. You get the rubber band.
1. Select another layer or another tool (feature identifier, select mesh elements,...). The rubber band is still there.
1. Reactivate the "Digitize mesh elements" tool. I would expect the rubber band to be reactivated also and follow the cursor so that I'd continue digitizing my feature. But instead you have to abort the previous drawing and start a new one. Not consistent with vector behavior.

### Steps to reproduce the issue

https://user-images.githubusercontent.com/7983394/187785562-31033b6a-0ce2-448c-aff1-d1443487f173.mp4

In this video, I'm unable to get the rubber band follow the cursor, and I can't really tell how I ended up with the final face; it looks like the rubber band was actually following the cursor but just not updated in the canvas!?

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | fb97c10d00
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
As discussed with Harrissou:
I confirm, there are effectively a double issue:
- the rubber-band is still displayed when the tool is not active
- when we come back to the tool, the rubber-band disappears, but its seems the tool continue to work with works already done in memory.
Here, the solution could
- to kill completely the action begun by the tool
- continue properly the action with a good rubber-band

**Comment by alexbruy** [comment]
Fixed by #50401.
