### ISSUE TITLE
[Mesh] Pressing Backspace removes new edges of a face being drawn but not the new vertices

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#50035]
### What is the bug or the crash?

When drawing a mesh layer face, pressing backspace key undoes the actions. If you are digitizing the faces by adding their own vertices (that is, not snapping to already existing ones), I'd expect the backspace button to also remove the vertex the process is adding, not only the edges. Otherwise, you end up with free vertices over the map canvas (you'd have to delete in a further step).
IOW, vertex addition should also be in the history of actions when you are creating a face.
[Capture vidéo du 31-08-2022 22:00:27.webm](https://user-images.githubusercontent.com/7983394/187771343-ff3f8a74-20eb-4dae-8a5a-1b9796abfa8f.webm)

### Steps to reproduce the issue

In the video, when I press Backspace key, the edges that were being drawn are rolled back. But not the vertices I added in parallel. To remove the vertices, I had to press the Undo button

[Capture vidéo du 31-08-2022 22:00:27.webm](https://user-images.githubusercontent.com/7983394/187771343-ff3f8a74-20eb-4dae-8a5a-1b9796abfa8f.webm)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | fb97c10d00
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
As discussed with Harrissou:
The approach will be changed. Once entered in face drawing, new vertex position will be added with a simple click. Vertices will be added to the mesh only when the face will be validate by right click. So only the rubber-band will be concerned by the backspace, no more free vertices after it.

**Comment by alexbruy** [comment]
Fixed by #50401.
