### ISSUE TITLE
No obvious way to fix a broken mesh layer

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#50041]
### What is the bug or the crash?

 I got a crash while I had some mesh layers in edit mode. When I reopened the project I was unable to toggle one of them to edit mode again (`WARNING    Mesh editing : Unable to start mesh editing for layer "basetest"`). Reason I could find in the Log --> General tab is `Unable to start editing of mesh layer "basetest": Face 1824 is flat`. Great! But as far as I know, there is no way to find that 1824th face without going to edit mode...

### Steps to reproduce the issue

Sorry I no longer have the data

### Versions

QGIS 3.27 on Ubuntu 22.04

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
We **really** need a algorithms that repairs broken files.
