### ISSUE TITLE
pLEASE NEED HELP WITH THIS CRASH!

### ISSUE THREAD

**Issue by elyzuaz** [qgis/QGIS#50040]
## User Feedback

I HAVE THE CRASH WHEN I TRY TO EXPORT VECTORIAL PDF FILE

## Report Details

**Crash ID**: [f0c38b075a3f14bf0542ff838897ede2563baa29](https://github.com/qgis/QGIS/search?q=f0c38b075a3f14bf0542ff838897ede2563baa29&type=Issues)

**Stack Trace**
<pre>
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
geos::noding::snapround::MCIndexSnapRounder::computeVertexSnaps :
GEOSEquals_r :
QgsGeos::shortestLine :
QgsGeometry::shortestLine :
QgsPointXY::operator/ :
QgsSimpleLineCallout::draw :
QgsCallout::render :
QgsVectorLayerLabelProvider::drawCallout :
QgsVectorLayerLabelProvider::drawLabelBackground :
QgsLabelingEngine::drawLabels :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::start :
QgsMapRendererCustomPainterJob::renderSynchronously :
QgsLayoutItemMap::drawMap :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLayoutExporter::exportToPdf :
QgisApp::actionAddWcsLayer :
QMetaObject::activate :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

I HAVE THE CRASH WHEN I TRY TO EXPORT VECTORIAL PDF FILE

### Versions

QGIS Info
QGIS Version: 3.10.5-A Coru�a
QGIS code revision: 984615fe1e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@elyzuaz QGIS 3.10 is way too old and no longer maintained. You might want to upgrade to a more recent version (3.22LTR or 3.26) and try again.
