### ISSUE TITLE
Configuring the Processing Framework - options not set

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#50069]
### What is the bug or the crash?

When I try and set the 'Invalid features filtering' in the Processing options, and hit OK after setting, a 'Custom Coordinate Reference System' dialog pops up with a message "Cannot save '* Generated CRS.. Try changing the CRS definition to WKT format instead'.   On clicking OK to dismiss this dialog, the processing options are not saved.

### Steps to reproduce the issue

1). Click settings --> Options --> Processing tab.
2). In the general block, change Invalid features filtering from default value
3). Click OK

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
coordinates_converter | 1.0
LandXml | 2.3
latlontools | 3.6.3
MagneticDeclination | 2.3.1
profiletool | 4.2.2
QCopycanvas | 0.5
qfieldsync | v4.1.1
qgis2web | 3.16.0
qgis_resource_sharing | 0.16.0
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code revision
[feec3d3b12f](https://github.com/qgis/QGIS/commit/feec3d3b12f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
coordinates_converter
1.0
LandXml
2.3
latlontools
3.6.3
MagneticDeclination
2.3.1
profiletool
4.2.2
QCopycanvas
0.5
qfieldsync
v4.1.1
qgis2web
3.16.0
qgis_resource_sharing
0.16.0
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@robbitt, could you please try again using a new QGIS profile? Does the issue also occur trying to change any other setting option?
