### ISSUE TITLE
QgsApplication::initQgis()  crash！！！

### ISSUE THREAD

**Issue by dansirming** [qgis/QGIS#50065]
### What is the bug or the crash?

I has written code as follow:

#include "GISDemo.h"
#include <QtWidgets/QApplication>
#include <qgsapplication.h>
int main(int argc, char *argv[])
{
	QgsApplication a(argc, argv, true);
	QgsApplication::setPrefixPath(R"("C:\OSGeo4W\apps\qgis")", true);
	QgsApplication::initQgis();    //初始化QGIS应用

	CGISDemo w;    //创建一个窗体，类似于Qt
	w.show();
	return a.exec();
}

but crashed! it crashed "QgsApplication::initQgis(); ", the qgis.exe which I Compiled by QGIS-master 3.26.2 also has the problem! I debuged and found it crashed at exec [at : sqlite3_exec( handler, .....) Line]of  QgsAuxiliaryStorage.cpp in qgs_core module。can you help me？ thank you very much！
<img width="322" alt="2022-09-02_135018" src="https://user-images.githubusercontent.com/38598451/188067950-a5723b3d-ff8e-46c6-b2e5-36652fe43be1.png">

### Steps to reproduce the issue

I has written code as follow:

#include "GISDemo.h"
#include <QtWidgets/QApplication>
#include <qgsapplication.h>
int main(int argc, char *argv[])
{
	QgsApplication a(argc, argv, true);
	QgsApplication::setPrefixPath(R"("C:\OSGeo4W\apps\qgis")", true);
	QgsApplication::initQgis();    //初始化QGIS应用

	CGISDemo w;    //创建一个窗体，类似于Qt
	w.show();
	return a.exec();
}

but crashed! it crashed "QgsApplication::initQgis(); ", the qgis.exe which I Compiled by QGIS-master 3.26.2 also has the problem! I debuged and found it crashed at exec [at : sqlite3_exec( handler, .....) Line]of  QgsAuxiliaryStorage.cpp in qgs_core module。can you help me？ thank you very much！
<img width="322" alt="2022-09-02_135018" src="https://user-images.githubusercontent.com/38598451/188067950-a5723b3d-ff8e-46c6-b2e5-36652fe43be1.png">

### Versions

 the qgis.exe which I Compiled by QGIS-master 3.26.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Maybe ask on the dev mailing list, I don't think this 'issue' is related to the official app.
