### ISSUE TITLE
WMS connection doesn't honor the port - removes port if listed ex: http://localhost:8686/ turns into http://localhost/

### ISSUE THREAD

**Issue by worthwhileindustries** [qgis/QGIS#50064]
### What is the bug or the crash?

WMS connection doesn't honor the port - removes port if listed ex: http://localhost:8686/ turns into http://localhost/

![image](https://user-images.githubusercontent.com/3536254/188059952-ac7b7673-b1eb-43eb-96dd-a148d3ea9f8f.png)

### Steps to reproduce the issue

Setup WMS connection with url and a port number like http://localhost:8686/ and check messages tab for error

![image](https://user-images.githubusercontent.com/3536254/188059952-ac7b7673-b1eb-43eb-96dd-a148d3ea9f8f.png)

### Versions

This also happened to the LTS version 3.22.4 which is why I upgraded to the latest stable available today and problem still exists.

![image](https://user-images.githubusercontent.com/3536254/188060209-1824e785-83b8-4350-b58b-e31cf1f4d8b6.png)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

WFS works fine with the port number and WMS works fine on port 80.

**Comment by agiudiceandrea** [comment]
Using the Debugging/Development Panel I see that the Capabilities document is correctly requested using the URL including the port number:

![image](https://user-images.githubusercontent.com/16253859/188143211-81c95188-7586-484f-b8b1-49347b5c9c6b.png)

Are you sure the Capabilities document of your server exposes the correct URL (including the port number) for the GetMap operation?
Does the issue occur also if you set the Ignore "GetMap/GetTile/... URI reported in capabilities" option in the WMS service configuration dialog window?

**Comment by worthwhileindustries** [comment]
Closing this. You are correct, it was a configuration on the other side. Seems like maybe there's some caching going on. Had to remove and add the connection back a couple of times before it kicked in. Sorry about that.
