### ISSUE TITLE
Distance units error in buffer tool. QGIS 3.26

### ISSUE THREAD

**Issue by 016852902FREDY** [qgis/QGIS#50084]
### What is the bug or the crash?

<img width="819" alt="buffer qgis 3 26 2" src="https://user-images.githubusercontent.com/86328327/188330406-47591264-8fa4-4de3-874c-ce266bc2fd0d.png">
There is a difference with respect to previous versions regarding the units for the creation of buffer, before in the distance field meters, km, miles, etc. were selected. Now the problem is that the tool only shows geographic degrees and generating a buffer is a bit more complex since the conversion from geographic degrees to meters or another unit must be done.

### Steps to reproduce the issue

The minimum unit is a geographic degree that is equivalent to 111.12 km, therefore to make a buffer of a few meters it becomes complex to do the conversion. in version 3.22.x this did not happen with the buffer tool.
<img width="819" alt="buffer qgis 3 26 2" src="https://user-images.githubusercontent.com/86328327/188330530-83209500-e0fd-4d27-8148-c3f71e89e423.png">

### Versions

3.26.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Not a bug, and not true, this has been like this for a while. Just reproject your data before using tools.
