### ISSUE TITLE
Missing output after export processing model as script algorithm

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#50089]
### What is the bug or the crash?

Missing output after export processing model as script algorithm.

The name parameter for both `QgsProcessingParameterFeatureSink` is an empty string.

![image](https://user-images.githubusercontent.com/20856381/188370413-65d7872b-4650-4042-92f9-347041867c12.png)

### Steps to reproduce the issue

1. Open [test_model](https://github.com/qgis/QGIS/files/6824112/test_model_output.zip) (taken from #44184)

2. `Export as Script Algorithm...`

3. Run the script

4. See error -> missing output

**Model exported as script:**
![image](https://user-images.githubusercontent.com/20856381/188369814-eecda29c-0075-4ec5-a0ff-3705cafa79a5.png)

**Original model:**
![image](https://user-images.githubusercontent.com/20856381/188368720-31ca4b38-ed1d-41d4-8929-cb68ea4b4998.png)

### Versions

QGIS version | 3.27.0-Master | QGIS code revision | 775e333ec3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not a bug, names can't start with a digit like in Python.

**Comment by pathmapper** [comment]
Thanks @alexbruy, what about showing a warning to the user if such a model is exported as script?

Or don't allow creating models where names start with a digit at all?

**Comment by pathmapper** [comment]
Looks like the missing output is related to identical output names: [model.zip](https://github.com/qgis/QGIS/files/11651798/model.zip)

![grafik](https://github.com/qgis/QGIS/assets/20856381/5f73e1ce-5b9b-41b1-bfc0-f8037c8c3f42)

![grafik](https://github.com/qgis/QGIS/assets/20856381/c170d7d0-3552-4cc8-a526-9ab09bd0ac7e)

**Comment by pathmapper** [comment]
Closing here in favor of https://github.com/qgis/QGIS/issues/54150
