### ISSUE TITLE
utf-8 encoding issue in DB manager

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#50091]
### What is the bug or the crash?

I am actually not sure what the bug is or even if it is bug.
When importing a shp-file with encoding win-1252 into a postgresql database using DB manager encoding the imported layer to utf-8 results in misread characters. When saving (exporting) the same shp-file to gpkg, the encoding to utf-8 has no issues, there are no misread characters.
Also, when saving the shp-file as a new shp-file in utf-8 and then importing the new shp-file into the postgresql database, there are no misread characters.
It seems db manager (or some connection to the database) has trouble converting win-1252 to utf-8.

### Steps to reproduce the issue

You can use the attached shp-file for testing.
[test_enc_1252.zip](https://github.com/qgis/QGIS/files/9488290/test_enc_1252.zip)

Open the shp-file in Qgis, check the encondig (it should be win-1251)
Open the attribute table and you will see some fields containing non-standard characters, for example â

Import the shp-file into a postgresql utf-8 encoded database using utf-8 as the encoding option.
Add the database layer to qgis and check the attribute table, the non-standard characters are not recognized

Next, save the original shp-file as gpkg (encoding is set to utf-8 by default and greyed out in my case), check for non-standard characters (no issues) and then import the gpkg into the database.
Add this layer from the database to qgis and the non-standard characters are recognized.

Next, save the original shp-file as shp-file with encoding set to utf-8, check for non-standard characters (no issues) and then import the new shp-file into the database.
Add this layer from the database to qgis and the non-standard characters are recognized.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-versie | 3.22.7-Białowieża | QGIS code revisie | 5a65627a
-- | -- | -- | --
Qt versie | 5.15.3
Python versie | 3.9.5
GDAL/OGR versie | 3.4.3
PROJ versie | 9.0.0
EPSG-register databaseversie | v10.054 (2022-02-13)
GEOS versie | 3.10.2-CAPI-1.16.0
SQLite versie | 3.38.1
PDAL versie | 2.3.0
PostgreSQL client versie | 13.0
SpatiaLite versie | 5.0.1
QWT versie | 6.1.6
QScintilla2 versie | 2.13.1
OS versie | Windows 10 Version 2009
  |   |   |  
Actieve Python plug-ins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS-versie
3.22.7-Białowieża
QGIS code revisie
[5a65627a](https://github.com/qgis/QGIS/commit/5a65627a)
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.4.3
PROJ versie
9.0.0
EPSG-register databaseversie
v10.054 (2022-02-13)
GEOS versie
3.10.2-CAPI-1.16.0
SQLite versie
3.38.1
PDAL versie
2.3.0
PostgreSQL client versie
13.0
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This issue might be related to feature request [#48050](https://github.com/qgis/QGIS/issues/48050)

**Comment by agiudiceandrea** [comment]
@Jeroen-GroeneBij, such encoding option is for specify the encoding of the input layer. Have you tried to import the layer unchecking the Encoding checkbox?

**Comment by Jeroen-GroeneBij** [comment]
@agiudiceandrea thank you for this insight. I have misunderstood this option. I thought the Encoding checkbox was to set the encoding in which the imported layer will be stored. So it actually is to specify what the encoding of the origin layer is?
If I indeed uncheck this option, the non-standard characters are recognized.

Hmm, then this issue maybe is not a bug?
Would it clarify to rename this option to Source encoding?
Or would users then expect an additional option to set Target encoding?

**Comment by agiudiceandrea** [comment]
So, this is a documentation issue rather than a bug: https://github.com/qgis/QGIS-Documentation/issues/7763.

**Comment by agiudiceandrea** [comment]
@Jeroen-GroeneBij, I've also proposed to add a tooltip to the Encoding option to try avoid misunderstanding: see https://github.com/qgis/QGIS/pull/50135. Do you think it may be of some help?

**Comment by Jeroen-GroeneBij** [comment]
Very nice solution, thank you.
And thanks for spotting the 'only 4 encoding options'. I did notice it, but assumed it had to do with either limitations of DB manager or the settings of the database. When I create a new database I always set it to UTF-8 encoding, so maybe these four options are somehow tied to the encoding of the database?

**Comment by agiudiceandrea** [comment]
> maybe these four options are somehow tied to the encoding of the database?

No. As said before, they are not related to the database encoding but to the encoding of the layer to import.

**Comment by agiudiceandrea** [comment]
I think this issue report can be closed now as fixed by #49932. The fix will be available since QGIS 3.28.0.
