### ISSUE TITLE
Georeferencing doesn't work at all in 3.26.2 MAC

### ISSUE THREAD

**Issue by hvdosten** [qgis/QGIS#50107]
### What is the bug or the crash?

in QGIS 3.26.2, Mac version georeferencing doesn't work at all. It starts and then freezes. The jpg which should be georeferences is << 1 MB.

There are issues of a program called zerre running which can not stopped. Maybe this is the cause for the georeferencing issue?

### Steps to reproduce the issue

Go to "georeferencing"

### Versions

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/bruser1729/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/bruser1729/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/bruser1729/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=DE style='tab-interval:35.4pt'>

QGIS-Version | 3.26.2-Buenos Aires | QGIS-Codeversion | b0f8302dbc
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.2
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.11.5
BS-Version | macOS 12.5
  |   |   |  
Aktive Python-Erweiterungen
GeometryShapes | 0.7
FreehandRasterGeoreferencer | 0.8.3
QuickOSM | 2.1.1
SemiAutomaticClassificationPlugin | 7.10.6
ee_plugin | 0.0.5
osminfo | 0.7.1
latlontools | 3.6.4
oam_qgis3_express | 0.1.0
OSMDownloader | 1.0.3
qad | 3.0.4
OSMDataSync | 0.2
openlayers_plugin | 2.0.0
tile_plus | 0.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

<p class=MsoNormal><o:p>&nbsp;</o:p></p>

</body>

</html>
QGIS-Version	3.26.2-Buenos Aires	QGIS-Codeversion	[b0f8302dbc](https://github.com/qgis/QGIS/commit/b0f8302dbc)

Qt-Version	5.15.2
Python-Version	3.9.5
GDAL-Version	3.3.2
PROJ-Version	8.1.1
EPSG-Registraturdatenbankversion	v10.028 (2021-07-07)
GEOS-Version	3.9.1-CAPI-1.14.2
SQLite-Version	3.35.2
PDAL-Version	2.3.0
PostgreSQL-Client-Version	unknown
SpatiaLite-Version	5.0.1
QWT-Version	6.1.6
QScintilla2-Version	2.11.5
BS-Version	macOS 12.5
			
Aktive Python-Erweiterungen
GeometryShapes	0.7
FreehandRasterGeoreferencer	0.8.3
QuickOSM	2.1.1
SemiAutomaticClassificationPlugin	7.10.6
ee_plugin	0.0.5
osminfo	0.7.1
latlontools	3.6.4
oam_qgis3_express	0.1.0
OSMDownloader	1.0.3
qad	3.0.4
OSMDataSync	0.2
openlayers_plugin	2.0.0
tile_plus	0.1
processing	2.12.99
sagaprovider	2.12.99
grassprovider	2.12.99
db_manager	0.1.20
MetaSearch	0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@hvdosten, could you please try again actually using a new QGIS user profile? Could you explain with more details what you mean with "There are issues of a program called zerre running which can not stopped"?

**Comment by roya0045** [comment]
SemiAutomaticClassificationPlugin 7.10.6 is present, that's likely the main issue, not a QGIS bug.

**Comment by agiudiceandrea** [comment]
I agree with you @roya0045.
Some related issue reports for reference: https://github.com/qgis/QGIS/issues/46327, https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/189.

**Comment by agiudiceandrea** [comment]
https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/189#issuecomment-1239923553
> Thank you for your feedback.
> I have changed the behavior of the SCP in version 7.10.7 to avoid the triggering of this issue.
> 
> To be clear, the Georeferencer plugin issue is not caused by the SCP.
> The SCP sets the GDAL configuration option GDAL_NUM_THREADS.
> The Georeferencer plugin has issues if this option GDAL_NUM_THREADS is greater than 1.
> Georeferencer plugin developers may have to fix this issue, because other plugins or users could change this option and trigger the issue in the future.

**Comment by roya0045** [comment]
> [semiautomaticgit/SemiAutomaticClassificationPlugin#189 (comment)](https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/189#issuecomment-1239923553)
> 
> > Thank you for your feedback.
> > I have changed the behavior of the SCP in version 7.10.7 to avoid the triggering of this issue.
> > To be clear, the Georeferencer plugin issue is not caused by the SCP.
> > The SCP sets the GDAL configuration option GDAL_NUM_THREADS.
> > The Georeferencer plugin has issues if this option GDAL_NUM_THREADS is greater than 1.
> > Georeferencer plugin developers may have to fix this issue, because other plugins or users could change this option and trigger the issue in the future.

I don't get why they say the plugin isn't responsible if it changes the variable that causes the crash, though our options would be to not show a progress bar if multithread is enabled, or always set the variable to 1 core everytime a georeferencing is done.

**Comment by agiudiceandrea** [comment]
@nyalldawson, would it be possible to make the Georeferencer not crash when the GDAL_NUM_THREADS env var is set to a value greater than 1?

**Comment by agiudiceandrea** [comment]
@roya0045, maybe just setting GDAL_NUM_THREADS=1 when the Georeferencer is working would avoid the crash.

**Comment by roya0045** [comment]
I guess that's an object for debate with plugins, should qgis awlays override the variable to be safe or should the plugin only set it when they need to use the georeferencer and revert it to 1 once they are done.

**Comment by agiudiceandrea** [comment]
The variable could also be set by the user itself. I think QGIS should not crash in any case.
