### ISSUE TITLE
QGIS not responding when entering page size using custom width or height fields

### ISSUE THREAD

**Issue by jbp35** [qgis/QGIS#50104]
### What is the bug or the crash?

QGIS is very slow/unresponsive after entering manually the width or height of the page in the item properties panel (layout). Eventually it comes back after waiting 10-20secondes otherwise I have to kill the process and restart QGIS. 

### Steps to reproduce the issue

Create a new project and add a new layout
Type a custom size in the page size properties like width=250.00mm
QGIS becomes slow after typing the letter 2 and becomes unresponsive after typing letter 5.

### Versions

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b12f
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Can't reproduce can you share a project and data where the issue can be reproduced?
