### ISSUE TITLE
QGIS crash while opening directory from projects list

### ISSUE THREAD

**Issue by Spartacus1** [qgis/QGIS#50105]
### What is the bug or the crash?

QGIS 3.26.2, after opening the app, go to the recent projects list in the main Canvas (before opening any project), if we right click a project and choose "Open directory", QGIS will crash. 

### Steps to reproduce the issue

Open QGIS, from the main canvas -> Recent projects, right click on any and choose "open directory". 

### Versions

3.26.2-Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

QGIS 3.26.2 running in MacOS Monterey 12.5.1.

**Comment by agiudiceandrea** [comment]
It seems to me the issue doesn't occur on either Windows 10 or Ubuntu Linux 22.04, so it seems macOS specific.

**Comment by alexbruy** [comment]
@Spartacus1 is this still an issue?

**Comment by Spartacus1** [comment]
Hello Alexander

This is no longer an issue. It’s solved. It can be closed. 
Thank you the care and attention. 
Best regards
