### ISSUE TITLE
snapgeometries only snaps to vertices, not segments

### ISSUE THREAD

**Issue by Martin-BKT** [qgis/QGIS#50121]
### What is the bug or the crash?

When snapping a point layer to a line layer, QGIS 3.16 snapped the points to the closest segment when using parameter 1, as seen in the example (yellow line layer as reference layer, red point layer, green result layer)
<img width="296" alt="Behaviour QGIS 3 16" src="https://user-images.githubusercontent.com/102960293/188748685-a5504d26-c0f5-4496-bf3d-282b8b625b17.png">

In QGIS 3.26, the same algorithm with the same parameter and inputs no longer snaps to segments, but only to vertices:
<img width="338" alt="Behaviour QGIS 3 26" src="https://user-images.githubusercontent.com/102960293/188748833-767db3b4-2e79-445e-a8f4-8bc63abdc659.png">

### Steps to reproduce the issue

Create a point and a line layer. use snapgeometries to snap points to the lines using parameter 1.

### Versions

QGIS 3.16.16: OK
QGIS 3.26.2: Not OK.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
> Create a point and a line layer. use snapgeometries to snap points to the lines using parameter 1.

Can you clarify what you mean by "using parameter 1"?

**Comment by Martin-BKT** [comment]
Yes, of course.

It’s the behaviour parameter, in full text: „"Prefer closest point, insert extra vertices where required"

Kind regards,
Martin Götzer


Von: Nyall Dawson ***@***.***>
Gesendet: Mittwoch, 7. September 2022 00:19
An: qgis/QGIS ***@***.***>
Cc: Martin Götzer ***@***.***>; Author ***@***.***>
Betreff: Re: [qgis/QGIS] snapgeometries only snaps to vertices, not segments (Issue #50121)


Create a point and a line layer. use snapgeometries to snap points to the lines using parameter 1.

Can you clarify what you mean by "using parameter 1"?

**Comment by roya0045** [comment]
Pretty sure this is a user error and not a QGIS one, did you check https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#snapping-and-digitizing-options ?

**Comment by Martin-BKT** [comment]
> Pretty sure this is a user error and not a QGIS one, did you check https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#snapping-and-digitizing-options ?

The issue is not about snapping during edit, but when using snapgeometries in processing mode. Just open QGIS 3.16 and QGIS 3.26 with an initial user profile, create the 2 layers and use snapgeometries processing, and I would be surprised if you would get identical results.

**Comment by roya0045** [comment]
> The issue is not about snapping during edit, but when using snapgeometries in processing mode. Just open QGIS 3.16 and QGIS 3.26 with an initial user profile, create the 2 layers and use snapgeometries processing, and I would be surprised if you would get identical results.

Ah right, it seems the 'closest' point' is now the closest vertex and not closest point on surface. And that's delegated to the QgsGeometrySnapper.

**Comment by Martin-BKT** [comment]
> Ah right, it seems the 'closest' point' is now the closest vertex and not closest point on surface. And that's delegated to the QgsGeometrySnapper.

Yes, that's the issue. Unfortunately, the function is quite important for us, so we cannot update to the newest version until the issue is resolved.

**Comment by roya0045** [comment]
> Yes, that's the issue. Unfortunately, the function is quite important for us, so we cannot update to the newest version until the issue is resolved.

Your options are to keep using your current version. Hope someone wants to fix the bug eventually, or try to get it fixed (by submitting a fixing or funding a dev to fix it for you.)

**Comment by untsvn** [comment]
Sorry I'm new to logging issues like this - is it possible to reopen this as an issue or is the etiquette to open a new issue?

Have just encountered this issue in v3.22 so tried an upgrade to v3.24. Appears the "Prefer closest point" options are not working and is falling back to "Prefer aligning nodes"

See below screen shot for what I expect snap to nearest point to do with a 3m tolerance. I would expect the input vertices to snap to the closest point on the segment (indicated by arrows) and add vertices to that line depending on which behaviour was selected.

`processing.run("native:snapgeometries", {'INPUT':'S:/OneDrive/Desktop/temp.gpkg|layername=ref_1_input','REFERENCE_LAYER':'S:/OneDrive/Desktop/temp.gpkg|layername=ref_2a','TOLERANCE':3,'BEHAVIOR':1,'OUTPUT':'TEMPORARY_OUTPUT'})`

![image](https://github.com/qgis/QGIS/assets/67664763/e4f6c5eb-6bf0-4fba-b1a6-28428d29144c)

GPKG with embedded QGIS project attached whcih demonstrates this exmaple.

[qgis_snap_issue.zip](https://github.com/qgis/QGIS/files/13465280/qgis_snap_issue.zip)

**Comment by uclaros** [comment]
Fixed in #56426
