### ISSUE TITLE
QGIS 3.22.8 LTR - problems with wms services

### ISSUE THREAD

**Issue by FHList** [qgis/QGIS#50129]
### What is the bug or the crash?

Hi,
we have upgraded to QGIS version 3.22.8 LTR. But in this version we have problems with some WMS services. The connection to the service is established, the layer can be loaded, but it does not show any data. Only after repairing the data source and referencing the same service again, the data is displayed. Such problems did not occur in previous versions, for example QGIS 3.4.8 or 3.22.4. In newer versions, such as QGIS 3.24.3, the service works without problems. However, we need the version 3.22.8 LTR described above and we cannot simply switch.

Example: https://geodienste.sachsen.de/wms_geosn_dtk-pg-color/guest

If I leave QGIS in default settings, i.e. CRS: EPSG 4326 then the service is loaded correctly. However, I need CRS: EPSG 25833 as default and with that it only works as described above.

### Steps to reproduce the issue

1. Open Settings
2. Go on 'CRS' 
3. Choose in CRS for Projects 'Use a default CRS -EPSG:25833' 
4. Choose in CRS for Layers 'Use project CRS'
5. Restart QGIS 
6. Open Data Source Manager
7. Go to 'WMS/WMTS'
8. Go to 'New'
9. Fill in the connection details:  
- Name: for Example "DTK_GeoSN_Bunt"
- URL:https://geodienste.sachsen.de/wms_geosn_dtk-pg-color/guest
- leaving the remaining settings as set by default
10. Click on ok
11. Leave the remaining settings as set
12. Click on Connect
13. Select the Layer 'SN DTK Produktgruppe Color'
14. Select 'Add'
15. Layer is loaded in layers panel but without data
16. Click on layer and on 'warning triangle' - 'Repair Data Source'
17. Navigate to 'WMS/WMTS' and choose 'DTK_GeoSN_Bunt'
18. Select the layer 'SN DTK Produktgruppe Color' and click on 'ok'
19. Data is displayed correctly

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.22.8-Białowieża | QGIS-Codeversion | 8d5e9761df
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.5.0
PROJ-Version | 9.0.1
EPSG-Registraturdatenbankversion | v10.064 (2022-05-19)
GEOS-Version | 3.10.3-CAPI-1.16.1
SQLite-Version | 3.38.1
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 14.3
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
searchlayers | 3.0.12
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS-Version
3.22.8-Białowieża
QGIS-Codeversion
[8d5e9761df](https://github.com/qgis/QGIS/commit/8d5e9761df)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.0
PROJ-Version
9.0.1
EPSG-Registraturdatenbankversion
v10.064 (2022-05-19)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.3.0
PostgreSQL-Client-Version
14.3
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
searchlayers
3.0.12
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@FHList I've just followed the provided steps to reproduce the issue on my system with QGIS 3.22.10, which is the latest version currently available and supported) in Windows 10 64-bit and I cannot reproduce the issue: after step 14 the layer is correctly added to the Layers panel and is visible in the map:

https://user-images.githubusercontent.com/16253859/189182705-42a2183b-e977-41f9-a422-0ec7263c7fc1.mp4

Have you actually tried with a new QGIS user profile? Have you tried with the current supported QGIS version 3.22.10?
