### ISSUE TITLE
Open only selected features in attribute table

### ISSUE THREAD

**Issue by jhpoosthoek** [qgis/QGIS#50128]
### Feature description

Say I have a dataset with a lot of point features. If I select a couple of features in the map window sometimes I would like to see the attribute table of my selection. Then you first need to open the attribute table (which if the dataset is huge will take a lot of time) and then show only selected features. Would it be possible to have a shortcut where you only show the attribute table of the selection?

**Comment by nyalldawson** [comment]
Shift + f6 does this already.

**Comment by jhpoosthoek** [comment]
Wow, that is awesome! Ok I will close the request ;-)
