### ISSUE TITLE
qgis crashes as i open install and manage plugin 

### ISSUE THREAD

**Issue by mellow2334** [qgis/QGIS#50138]
### What is the bug or the crash?

as i open install and manage plugin, qgis freezes. i tried re-installing different versions of qgis for several times but still same problem.

### Steps to reproduce the issue

open qgis 
click on 

### Versions

every verions of qgis3
![image](https://user-images.githubusercontent.com/113101982/189092823-138e223c-ec34-4319-a001-b41d655ddf34.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
ok, going to need more info if you want help, otherwise good luck.

**Comment by eox-cs1** [comment]
Hi there,  

I'm experiencing the same issue as described above. 
As soon as I open the "Plugin Manager" and select a Plugin or any of the "Plugin-Tabs" QGis freezes.  It doesn't freeze, however, in the "Settings-Tab" or the "Install from ZIP-Tab".  Once frozen only "xkill" can remove the QGis instance. 

If tried it with 3.10LTS as well as with QGis 3.26 - always the same. 
I'm running it on  Ubuntu 20.04.5 LTS" (-> kubuntu)
and installed 3.10 the from the Ubuntu repos and the 3.26 from the QGis site.
