### ISSUE TITLE
QGIS crashes when i use coordinateSequence() in my plugin

### ISSUE THREAD

**Issue by axinav** [qgis/QGIS#50145]
### What is the bug or the crash?

Its the crash

### Steps to reproduce the issue

In my plugin i call  vertSec = curLayer.getGeometry(f).constGet().coordinateSequence() where curLayer is curren layer
And QGIS crashes/
If i call             vertSec = curLayer.getGeometry(f).constGet(), all right

### Versions

QGIS 3.26.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by axinav** [comment]
And when i call my plugin in console without QGIS desktop, all good

**Comment by nyalldawson** [comment]
The geometry is going out of scope and python garbage collector is cleaning it up early.

Try

```
geom = curLayer.getGeometry(f)
vertSec = geom.constGet().coordinateSequence()
```

**Comment by axinav** [comment]
Thanks, its works!
