### ISSUE TITLE
"Unknown option' in SAGA Gaussian Filter

### ISSUE THREAD

**Issue by alecomunian** [qgis/QGIS#50142]
### What is the bug or the crash?

When I run from the Toolbox the `SAGA > Raster Filter > Gaussian filter` there is the complaint `Unknown option 'MODE'`.
I suspect that there was a change in the name of the variable, that in QGIS is named `MODE`, while SAGA expects a variable named `KERNEL_TYPE`.
In fact, when I run the command from an external command line (`saga_cmd`) the algorithm works fine.
This happens on a Ubuntu 22.04 LTS machine, with QGIS 3.22.4 and SAGA Version 7.3.0.
Hope this helps.

### Steps to reproduce the issue

Running from the Toolbox the `SAGA > Raster Filter > Gaussian filter`.

This is the complete log file
```
QGIS version: 3.22.4-Białowieża
Qt version: 5.15.3
Python version: 3.10.3
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
SAGA version 7.3.0 is not officially supported - algorithms may encounter issues
Algorithm started at: 2022-09-08T15:12:55
Algorithm 'Gaussian filter' starting…
Input parameters:
{ 'INPUT' : '/DATA/scienza/siti/ITA/XXXXX/out/idro/h_TIN_qgis.tif', 'MODE' : 1, 'RADIUS' : 3, 'RESULT' : 'TEMPORARY_OUTPUT', 'SIGMA' : 1 }

grid_filter "Gaussian Filter" -INPUT "/tmp/processing_MKVATJ/ca0360616f134837838e6664ec7cf7ae/hTINqgis.sgrd" -SIGMA 1.0 -MODE 1 -RADIUS 3 -RESULT "/tmp/processing_MKVATJ/b682706a8cb743bd880fbe6fb0bbd57f/RESULT.sdat"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 7.3.0

Unknown option 'MODE'
____________________________
library path: /usr/lib/x86_64-linux-gnu/saga/
library name: libgrid_filter
library : grid_filter
tool : Gaussian Filter
identifier : 1
author : A.Ringeler (c) 2003
processors : 8 [8]
____________________________


Usage: saga_cmd grid_filter 1 [-INPUT <str>] [-RESULT <str>] [-SIGMA <double>] [-KERNEL_TYPE <str>] [-KERNEL_RADIUS <num>]
-INPUT:<str> Grid
Grid (input)
-RESULT:<str> Filtered Grid
Grid (optional output)
-SIGMA:<double> Standard Deviation
Floating point
Minimum: 0.000100
Default: 50.000000
-KERNEL_TYPE:<str> Kernel Type
Choice
Available Choices:
[0] Square
[1] Circle
Default: 1
-KERNEL_RADIUS:<num> Kernel Radius
Integer
Minimum: 1
Default: 2
Execution completed in 0.71 seconds
Results:
{'RESULT': '/tmp/processing_MKVATJ/b682706a8cb743bd880fbe6fb0bbd57f/RESULT.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• /tmp/processing_MKVATJ/b682706a8cb743bd880fbe6fb0bbd57f/RESULT.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

### Versions

QGIS 3.22.4 and SAGA Version 7.3.0.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
As written 
> SAGA version 7.3.0 is not officially supported - algorithms may encounter issues

Use Saga Next Gen plugin to run SAGA algorithms and report any issues on plugin repo, not here.
See https://github.com/qgis/QGIS-Enhancement-Proposals/issues/230 for further details.

**Comment by alecomunian** [comment]
Thank you @nicogodet for the quick reply, and sorry for the mistake in reporting. Thank you also for the suggestion about the *Saga Next Gen* plugin, that worked fine for me.
