### ISSUE TITLE
Unable to see Maps view/ Street view in Background

### ISSUE THREAD

**Issue by Satya3363** [qgis/QGIS#50159]
### Feature description

 I am new to this tool, I am using QGIS for creating drive routes besides out 5g/ 4G Sites using maps/ street.

I have downloaded HCMGIS plugin for maps but still I dont see maps in back ground 

Can anyone help me please.!!
![QGIS Issue](https://user-images.githubusercontent.com/113188941/189368854-49288304-93e9-4d16-804f-ff6287bc496e.JPG)

**Comment by roya0045** [comment]
This is not a QGIS issue, search online how to add a basemap.
