### ISSUE TITLE
Bad performance with panning/zooming when using project CRS 3832

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#50158]
### What is the bug or the crash?

Panning and zooming with project CRS 3832 is quite laggy when using WMS/XYZ Tiles (e.g. OpenStreetMap) - especially in the area near the antimeridian (180° E/W). 
Compared to CRS 3857, the performance with 3832 is quite bad.

### Steps to reproduce the issue

Create new blank project
Change project CRS to 3832
From XYZ Tiles section, pull in the OpenStreetMap and start panning and zooming around, especially in the near the antimeridian

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | feec3d3b12f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db-style-manager | 0.8
DigitizingTools | 1.5.1
latlontools | 3.6.4
layerGroupFilter | 0.2
multiple_layers_tools | 1.2
postgis_geoprocessing | 0.9
shapetools | 3.4.6
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.2-Buenos Aires
QGIS code revision
[feec3d3b12f](https://github.com/qgis/QGIS/commit/feec3d3b12f)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.1
latlontools
3.6.4
layerGroupFilter
0.2
multiple_layers_tools
1.2
postgis_geoprocessing
0.9
shapetools
3.4.6
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
You can just not force the reprojection of all your web layer by using their native projection. I don't think it's a bug IMO. It's just that projections are usually split at the pacific and handling it the other way is expensive.

**Comment by nyalldawson** [comment]
This is expected-- by using web mercator/EPSG:3875 tiles in a non web-mercator projection it becomes necessary to fetch a WHOLE lot of extra tiles. It works, it's just extremely inefficient! The solution is to use the web mercator projection for your project whenever you use a tile layer in this projection.
