### ISSUE TITLE
Overlay conditions with lines seems inconsistent ( GEOS version 3.10.3-CAPI-1.16.1)

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#50162]
### What is the bug or the crash?

Maybe this is resolved already, but 3.26 should still have this issue (my 3.27 build is getting old).

When testing conditions I noticed some strangeness. 
![overlay_exp](https://user-images.githubusercontent.com/12854129/189388947-9372e9ed-4986-4ac5-ad83-b592a3c21001.gif)

When changing the middle vertex of a line, where the edge vertex should be snapped on the line, displacing the middle vertex changes the results.

I don't know if the issue comes with the snapping or the tolerance threshold in GEOS or something else, but this seems problematic if we want reliable results.

### Steps to reproduce the issue

[test_overlay_conditions.zip](https://github.com/qgis/QGIS/files/9536871/test_overlay_conditions.zip)

Use the provided project to test overlay agl and results by moving vertices, do the same as in the gif.

### Versions

Tested on 3.27 on win 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc)

**Comment by roya0045** [comment]
will close in this case
