### ISSUE TITLE
Python Console not found in QGIS (windows 7 ultimate)

### ISSUE THREAD

**Issue by Nadja28** [qgis/QGIS#50163]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/50308656/189426033-8051fad4-8687-46bb-a39f-2532db4618be.png)

### Steps to reproduce the issue

Open Qgis in window 7 ultimate

### Versions

QGIS 3.16.X and QGIS 3.22.X

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I used system operative windows 7 ultimate and when I downland Qgis in these versions in the console, I don't saw python console.

**Comment by nicogodet** [comment]
On recent QGISversion, Python 3.9 is used and this version is not supported by W7.

See `NOTE` here https://www.qgis.org/en/site/forusers/download.html#windows

**Comment by jef-n** [comment]
OSGeo4W has a workaround for that - install the api-ms-win-core-path-HACK package.

**Comment by Nadja28** [comment]
Installed the version Qgis 3.10 and I don't had troubles, thanks for their recommendations.

**Comment by maresi999** [comment]
> OSGeo4W has a workaround for that - install the api-ms-win-core-path-HACK package.

I have tried - without success. Can You tell how to make it ? I have tried to install 3.22 with OSGeo4W with api HACK, It seems that QGIS working fine - I can see plugin repository, but with some plugins Python consoles gives errors not working. Thank You Marek
