### ISSUE TITLE
Failed to load Legacy provider

### ISSUE THREAD

**Issue by xairwolfcn** [qgis/QGIS#50177]
### What is the bug or the crash?

I compile qgis in vs2019,vcpkg,only need c++, without pyhon binging.

vcpkg-2022.08.15 privde Dependent Library！
CMAKE set python binding off，and other related python library off

set the correct “qgis.env”

the program run，and display the splash picture，then，exit！！

In the qgis.sln, I set the project "qgis_app" as .exe program,run, also display splash picture and then  console window report "Failed to load Legacy provider"

the program can't run correctly.

### Steps to reproduce the issue

nothing..

### Versions

I test
QGIS-final-3_22_10
QGIS-final-3_26_2
QGIS-final-3_22_0

the same problem！！

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by m-kuhn** [comment]
Which triplet are you building?

**Comment by xairwolfcn** [comment]
what triplet meaning!

**Comment by xairwolfcn** [comment]
i can't find in qigs code source ,could not find any matched "Failed to load Legacy provider"

**Comment by m-kuhn** [comment]
Iirc this is related to a platform plugin of qt and building statically.
https://vcpkg.readthedocs.io/en/latest/users/triplets/

**Comment by xairwolfcn** [comment]
qt-vs2019-x64-5.15.2
vcpkg install *** :x64-windows

**Comment by xairwolfcn** [comment]
windows 10

**Comment by m-kuhn** [comment]
x64-windows is dynamic. I'd recommend checking if qt plugin path is found at runtime it seems this is a build, runtime, vcpkg issue.

**Comment by xairwolfcn** [comment]
I install qt-vs2019-x64-5.15.2 separate from another lib

**Comment by xairwolfcn** [comment]
> x64-windows is dynamic. I'd recommend checking if qt plugin path is found at runtime it seems this is a build, runtime, vcpkg issue.

I check the qgis.exe loaded dll,include qt,qtplugin,..etc library.

'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\bin\Release\qgis_app.exe'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\ntdll.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\kernel32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\KernelBase.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\shell32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msvcp_win.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\ucrtbase.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\user32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\win32u.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\gdi32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\gdi32full.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qwt-6.2.0\bin\qwt.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\bin\Release\qgis_gui.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\bin\Release\qgis_analysis.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\bin\Release\qgis_native.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\ole32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\rpcrt4.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\combase.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Widgets.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Gui.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Core.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\ws2_32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\advapi32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msvcrt.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\sechost.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\qscintilla2_qt5.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\bin\Release\qgis_core.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Sql.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Xml.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Svg.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Network.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\crypt32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Concurrent.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\proj.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\geos_c.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\gdal.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\oleaut32.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\sqlite3.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5PrintSupport.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\comdlg32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\SHCore.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\shlwapi.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\spatialite.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\OpenCL.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\cfgmgr32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\vcruntime140_1.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5OpenGL.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5QuickWidgets.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\qca-qt5.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Qml.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\gsl.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\spatialindex-64.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5WinExtras.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\uxtheme.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\dwmapi.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msvcp140_1.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\d3d11.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\dxgi.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\mpr.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\userenv.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\version.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\netapi32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\winmm.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\wsock32.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\qtkeychain\bin\qt5keychain.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libexpat.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\zip.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\bcrypt.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libprotobuf-lite.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\zlib1.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\exiv2.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\psapi.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Positioning.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\secur32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\dnsapi.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\IPHLPAPI.DLL'. 
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\tiff.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libcurl.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\geos.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libcrypto-3-x64.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libssl-3-x64.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\liblzma.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\qhull_r.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\jpeg62.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\geotiff.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libpng16.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\zstd.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\gif.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\netcdf.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\webp.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libpq.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\pcre2-8.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\libxml2.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\json-c.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\hdf5.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\openjp2.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\iconv-2.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\winspool.drv'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\WinSxS\amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647\comctl32.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\freexl-1.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5Quick.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\gslcblas.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\bz2.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'E:\library\vcpkg\installed\x64-windows\bin\hdf5_hl.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\bin\Qt5QmlModels.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\netutils.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\sspicli.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\srvcli.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\cryptbase.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\imm32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\nsi.dll'. 
The thread 0x227c has exited with code 0 (0x0).
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\windows.storage.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\wldp.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\profapi.dll'. 
- cfg: Release
- cfg: Release
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\platforms\qwindows.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\wtsapi32.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\kernel.appcore.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\bcryptprimitives.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\powrprof.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\umpdc.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\styles\qwindowsvistastyle.dll'. Symbols loaded.
- cfg: Release
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\iconengines\qsvgicon.dll'. Symbols loaded.
- cfg: Release
- cfg: Release
- cfg: Release
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qgif.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qicns.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qico.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qjpeg.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qsvg.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qtga.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qtiff.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qwbmp.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\imageformats\qwebp.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\d3d9.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\igdumdim64.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\setupapi.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvdlistx.dll'. 
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvdlistx.dll'
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvldumdx.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msasn1.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\cryptnet.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\drvstore.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\wintrust.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\imagehlp.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\cryptsp.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\rsaenh.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvd3dumx.dll'. 
The thread 0x1db8 has exited with code 0 (0x0).
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvd3dumx.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\drvstore.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\devobj.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvldumdx.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\setupapi.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\igdumdim64.dll'
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvldumdx.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\drvstore.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\devobj.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvd3dumx.dll'. 
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\drvstore.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\devobj.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvldumdx.dll'
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\DriverStore\FileRepository\nvamig.inf_amd64_72cfb1f98b341668\nvd3dumx.dll'
The thread 0x2578 has exited with code 0 (0x0).
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\msctf.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\TextInputFramework.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\CoreMessaging.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\CoreUIComponents.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\ntmarta.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\WinTypes.dll'. 
'qgis_app.exe' (Win32): Unloaded 'C:\Windows\System32\WinTypes.dll'
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\bearer\qgenericbearer.dll'. Symbols loaded.
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc6.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\dhcpcsvc.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\clbcatq.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\netprofm.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\npmproxy.dll'. 
'qgis_app.exe' (Win32): Loaded 'C:\Windows\System32\DWrite.dll'. 
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\geometrycheckerplugin.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\offlineeditingplugin.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_arcgisfeatureserver.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_arcgismapserver.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_db2.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_delimitedtext.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_geonode.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_gpx.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_mdal.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_mssql.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_postgres.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_postgresraster.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_spatialite.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_virtuallayer.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_virtualraster.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_wcs.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_wfs.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\provider_wms.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'E:\QGIS\compile\QGIS-final-3_22_10B\output\plugins\Release\topolplugin.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\crypto\qca-gnupg.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\crypto\qca-logger.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\crypto\qca-ossl.dll'. Module was built without symbols.
'qgis_app.exe' (Win32): Loaded 'C:\Qt\5.15.2\msvc2019_64\plugins\crypto\qca-softstore.dll'. Module was built without symbols.
The thread 0x1e5c has exited with code 1 (0x1).
The thread 0x2aec has exited with code 1 (0x1).
The thread 0x34fc has exited with code 1 (0x1).
The thread 0x29f8 has exited with code 1 (0x1).
The thread 0x1fb4 has exited with code 1 (0x1).
The thread 0x3f64 has exited with code 1 (0x1).
The thread 0xba0 has exited with code 1 (0x1).
The thread 0x28b4 has exited with code 1 (0x1).
The thread 0x432c has exited with code 1 (0x1).
The thread 0x2210 has exited with code 1 (0x1).
The thread 0x439c has exited with code 1 (0x1).
The thread 0x4130 has exited with code 1 (0x1).
The thread 0xf60 has exited with code 1 (0x1).
The thread 0x4580 has exited with code 1 (0x1).
The thread 0x132c has exited with code 1 (0x1).
The thread 0x2d98 has exited with code 1 (0x1).
The thread 0x408c has exited with code 1 (0x1).
The thread 0x31dc has exited with code 1 (0x1).
The thread 0x1d74 has exited with code 1 (0x1).
The thread 0x4c0 has exited with code 1 (0x1).

**Comment by m-kuhn** [comment]
It's about openssl actually. See e.g. https://github.com/openssl/openssl/issues/19191 .

**Comment by xairwolfcn** [comment]
> It's about openssl actually. See e.g. [openssl/openssl#19191](https://github.com/openssl/openssl/issues/19191) .
I trace the code ,find.
  exit in QgsApplication::initQgis() 
i trace into qgsauthmanager.cpp,line201 --->bool QgsAuthManager::init( const QString &pluginPath, const QString &authDatabasePath ) 
crash here if ( !QCA::isSupported( "cert", QStringLiteral( "qca-ossl" ) ) )
then I test qca library it also report "Failed to load Legacy provider"
