### ISSUE TITLE
Attribute Table Integer entries not showing due to window size

### ISSUE THREAD

**Issue by meisterlix** [qgis/QGIS#50181]
### What is the bug or the crash?

![int_variable_not_showing](https://user-images.githubusercontent.com/76969431/189847828-e6c50a0e-d799-4456-af6f-9a1ae1ec28b8.JPG)

Attributes containing integer values are flush right, and therefore out of bounds of the window even though there is enough space to display them. Can lead to the window to open in a size that makes the attributes seem empty at first glance.

Expected behaviour would probably be to show the integer values flush right but end the actual field at the edge of the window. Minimum size of the field is too large at the moment.

### Steps to reproduce the issue

1. Open any project containing a layer with at least one Integer Attribute.
2. Open the layers attribute table.
3. Resize the opened window.

### Versions

3.26.2. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by andreasneumann** [comment]
Yes - that something that also bother's me a lot. There is no control over the size of a column, widget, etc. and quite often there are scrollbars in cases where the scrollbar wouldn't be necessary.

However, I believe, you need to fix the sentence "Minimum size of the field is too smalk at the moment." --> shouldn't this read too "large"?

**Comment by meisterlix** [comment]
I think minimum size is too small is right isn't it? Because the Integer fields cannot resize to be smaller than some current size minimum, therefore they are longer than the window itself if the window is resized to be shorter than that minimum size.

Might be I'm mistaken though, haven't had my morning coffee yet!

**Comment by andreasneumann** [comment]
Well, if the "minimum size of a widget is too large", then the form cannot shrink the widgets further and a scrollbar has to be added.

Don't worry - drink coffee ;-) I think the person who would work on this, would know what to do.

**Comment by meisterlix** [comment]
Had my coffee now, you are, of course, completely right! :D
Thanks for telling me, have a nice day!
