### ISSUE TITLE
Digitize shape crashes QGIS

### ISSUE THREAD

**Issue by matself** [qgis/QGIS#50185]
## User Feedback

"Digitize shape" invariably crashes QGIS.
I have tried a number of formats with the same result.
This goes for 3.26.0 as well as 3.26.2
In 3.22, this feature was several menu choices: Add rectangle - circle - ellips etc, with subselects for different insertion points.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003ca4 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Add a scratch layer, polygon type.
Click add polygon
Select Digitize shape in the Advanced Digitize Toolbox
First time, the wrong tool gets chosen
Retry Digitize shape
QGIS crashes at once

### Versions

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b12f
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
brand_gis
1.0
geocatbridge
4.3
LAStools
1.4
nominatim
1.4.2
processing_fusion
3.3
Qgis2threejs
2.7.1
quick_map_services
0.19.29
rvt-qgis
0.9.3
SentinelHub
2.0.0
slyr_community
4.0.3
SpreadsheetLayers
2.1.0-alpha1
timemanager
3.6
WaterNetAnalyzer-master
1.7
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you please update to 3.26.3 ?
There was some fixes about this recently.

**Comment by matself** [comment]
I thougt so too, so I went from 3.26.0 too 3.26.2 before i ran the bug report. Where is 3.26.3, please?
It is not provided on the front page of qgis.org.

**Comment by nicogodet** [comment]
https://download.qgis.org/downloads/QGIS-OSGeo4W-3.26.3-1.msi

**Comment by matself** [comment]
Thanx. I shall try. Will the link be fixed?

**Comment by nicogodet** [comment]
> Will the link be fixed?

Probably

**Comment by matself** [comment]
Upgrading to 3.26.3 took care of the crash.
But the wrong selection of tool persists. The second click on Digitize shape activates the tool.
And I can draw circular objects - nothing else. I expected to choose type of shape and draw method. 
Please bring back the options from 3.22 because this is a regression.

**Comment by nicogodet** [comment]
Can you open a separate issue ?

**Comment by matself** [comment]
![image](https://user-images.githubusercontent.com/12749960/190115987-f3ddb584-ca42-487a-ae9e-cf60605b57f5.png)
![image](https://user-images.githubusercontent.com/12749960/190116214-1739ccf1-98f7-460e-ad3f-3d1281091ba6.png)
These two images explain the behaviour. The new Digitize Shape - button requires the Shape Digitizing Toolbar to be active. In that, you get to choose form of shape and draw mode.
In 3.22, these options were available in the Edit menu, as well as in the Shape Digitizing Toolbar but the latter did not need to be activated. Which I never had before, since I only occasionally do this kind of shape digitizing. 
Suggestion: Check for an active Shape Digitizing Toolbar before activating the Digitize Shape tool.
