### ISSUE TITLE
Wrong scale in Layout

### ISSUE THREAD

**Issue by kunsebeirene** [qgis/QGIS#50193]
### What is the bug or the crash?

By producing a Layout the choosen scale (1:10000 see example in screenshot)
is not the scale of the output (see Map of 10 x 10 cm on DinA4 and the scale below).
The difference is a factor of arround 0.675

![Bildschirmfoto 2022-09-14 um 09 15 08](https://user-images.githubusercontent.com/113507001/190101427-1192ef75-ec2f-4726-9b50-959180b54ca7.png)

### Steps to reproduce the issue

1. create new Layout A4
2. place a map
3. adjust the size of the map to 10 x 10 cm
4. choose a scale of 1:10000
5. check the size of the map shown in the main window by mesuring it
6. it's not 1000 but arround 675 m
![Bildschirmfoto 2022-09-14 um 09 15 08](https://user-images.githubusercontent.com/113507001/190103367-e37daef4-fec4-4d13-8dc4-c6a510a8a7a8.png)

### Versions

QGIS-Version
3.26.2-Buenos Aires
QGIS-Codeversion
b0f8302dbc
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.3.2
PROJ-Version
8.1.1
EPSG-Registraturdatenbankversion
v10.028 (2021-07-07)
GEOS-Version
3.9.1-CAPI-1.14.2
SQLite-Version
3.35.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.11.5
BS-Version
macOS 12.6

Aktive Python-Erweiterungen
QuickOSM
2.1.1
quick_map_services
0.19.29
qgis2web
3.16.0
simplesvg
3.0.3
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Don't use Web mercator as a projection if you want accurate measurement/scale where you are.

It's not a QGIS issue.

**Comment by felixvons** [comment]
@kunsebeirene, maybe the coordinate reference system EPSG:25832 is an option for you.
