### ISSUE TITLE
QGIS crashes as soon as plugin manager is opened 

### ISSUE THREAD

**Issue by mellow2334** [qgis/QGIS#50190]
### What is the bug or the crash?

QGIS crashes as soon as plugin manager is opened 

### Steps to reproduce the issue

open plugin manager 

### Versions

3.2.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> 3.2.2

If it is really 3.2.2, update to 3.22.11 or 3.26.3.

Try with a new user profile too.

**Comment by roya0045** [comment]
Might be a duplicate of #50138
