### ISSUE TITLE
Georeferencer tool -  QGIS version 3.26.1-Buenos Aires

### ISSUE THREAD

**Issue by Gersonevlopes** [qgis/QGIS#50195]
### What is the bug or the crash?

Dear,

I am using Georeferencer tool in QGIS to extract some information from a site. However, after selecting couple of points, the produced raster looks weird.

Any issue with the version of QGIS? See enclosed steps

Thank you in advance for the support

BR
Gerson

### Steps to reproduce the issue

Step 1. Input raster + reference pts
![image](https://user-images.githubusercontent.com/113521769/190146412-bb600d89-c02b-4c70-bb7d-7fcffaee9901.png)

Step 2. Resulting raster
![image](https://user-images.githubusercontent.com/113521769/190146558-90fd1113-3ed5-4503-a934-5e8303b4cd69.png)

### Versions

QGIS version
3.26.1-Buenos Aires

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Gersonevlopes, what are the Output Settings and the Transformation Parameters you have set? Are you sure the Target resolution was properly set?
