### ISSUE TITLE
Split by line should be Split

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#50207]
### What is the bug or the crash?

Split by line processing alg, should be able to handle polygons as well. I am filing it as a bug, hoping it can be added to 3.28!

### Steps to reproduce the issue

1- open two polygon layers
2- try to split one with another using Split by line
3- you need to convert one to a line to do that

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by albertograva** [comment]
I can confirm the problem

**Versions**
3.26

**Supported QGIS version**
 I'm running a supported QGIS version according to the roadmap.

**New profile**
 I tried with a new QGIS profile

**Additional context**
Ubuntu 20.04

**Comment by pigreco** [comment]
I can confirm the problem
