### ISSUE TITLE
Copy report

### ISSUE THREAD

**Issue by carolinaadp** [qgis/QGIS#50204]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00004310 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.0-Tisler
QGIS code revision: 6b44a420
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

See error

### Versions

QGIS Desktop 3.24.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you describe what is your issue ?
Copy/paste the stacktrace isn't enough....

And update to 3.26.3 or 3.22.11, 3.24 is EOL.
