### ISSUE TITLE
QGIS 3.26 hangs and slows down in projects with many print layouts on Windows 10, example files included

### ISSUE THREAD

**Issue by unacomn** [qgis/QGIS#50209]
### What is the bug or the crash?

Ever since upgrading from QGIS 3.16 to 3.22 and then to 3.26, on Windows 10, I have encountered an issue where a project in particular, used for generating printed maps, loads very slowly and any changes to symbology can take minutes to take effect, all the while the program is locked.
This issue did not occur on QGIS 3.16 and seems to be caused by the way newer versions handle print layouts. The more there are, the slower any change to symbology will take and the slower the the entire project takes to load.

### Steps to reproduce the issue

In a QGIS project, create a multitude of print layouts of various shapes (A4, A3, A0, portrait and landscape, all with a SVG north star, a legend, a title and a scale). I believe that the tipping point is somewhere around 30, beyond which the slow down becomes aggravating.

### Versions

3.26.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

It's as if all the layouts are opened and the program tries to update them all at the same time, causing every little change to take ages. This is just my guess, I don't presume to understand how QGIS handles updating layouts, but once they're all deleted, it runs normally, just like 3.16.

This issue is very inconvenient, since it means that the print project, which is used extensively, can't be upgraded to a newer version of QGIS without deleting the old templates, which I still want to keep around, because I need to create updated versions of older maps as new data is added, with no other changes to the layout.

I have added a ZIP file containing a project that is set up in a way that should cause this issue. There are 3 geopackages within the ZIP file, alongside the project file. Attempting to change the symbology layers will result in QGIS 3.26 hanging for around 5 seconds, both after clicking Apply and after clicking OK. It takes even longer with larger, more complex project files. This issue did not exist in QGIS 3.16 and it seems to appear only in the Windows build of QGIS, it is not present in Linux.

[Issue.zip](https://github.com/qgis/QGIS/files/9607205/Issue.zip)

**Comment by elpaso** [comment]
Honestly this is going to be hard to debug and time consuming to set up. 

You chances to have a developer looking at the issue will increase dramatically if you can provide (attach a zip) a test project and data to reproduce the issue.

**Comment by unacomn** [comment]
> Honestly this is going to be hard to debug and time consuming to set up.
> 
> You chances to have a developer looking at the issue will increase dramatically if you can provide (attach a zip) a test project and data to reproduce the issue.

I wish I could, but the data I'm using is stored on a server and I'm not allowed to freely share it

**Comment by unacomn** [comment]
> Honestly this is going to be hard to debug and time consuming to set up.
> 
> You chances to have a developer looking at the issue will increase dramatically if you can provide (attach a zip) a test project and data to reproduce the issue.

I wish I could, but the data I'm using is stored on a server and I'm not allowed to share it. I'll try to slap together something off-line, with dummy data, and see if that also replicates the issue. Thanks for the suggestion.

**Comment by unacomn** [comment]
Issue has been resolved in QGIS 3.34
