### ISSUE TITLE
QGIS 3.26.2 Cannot read .dfs2 files anymore

### ISSUE THREAD

**Issue by daniel-caichac-DHI** [qgis/QGIS#50212]
### What is the bug or the crash?

In previous QGIS version (3.18, 3.20, 3.22) it was possible to read `.dfsu` and `.dfs2` data without any plugin, just with the MDAL driver (from `https://www.mikepoweredbydhi.com/download/mike-by-dhi-tools/generaltools/qgis`)
In present QGIS version (3.26.2) only reading of `.dfsu` files work, but loading any `.dfs2` files crashes the software.

### Steps to reproduce the issue

* Download MDAL driver from following website and add to QGIS path
`https://www.mikepoweredbydhi.com/download/mike-by-dhi-tools/generaltools/qgis`
* Drag and drop either a `dfsu` file or `dfs2` file as a new layer

### Versions

3.26.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I understand that this is not a plugin hence why I am posting this bug here. 
If this post be should be somewhere, indications on where is appreciated.

**Comment by nicogodet** [comment]
It seems to me you are using an external lib that add a functionality to QGIS.
So not a QGIS issue to me

There is a contact on linked page.

**Comment by nicogodet** [comment]
@vcloarec Any thought on this ?

**Comment by daniel-caichac-DHI** [comment]
I just realised (thanks to tagging of vcloarec) that there is an MDAL github repo with DHI driver, so I reposted this bug in that repo instead: https://github.com/lutraconsulting/MDAL/issues/430
Hence, this post could be closed, I guess.
