### ISSUE TITLE
wkbType of geometries is not same as the layer with z and with geopackage

### ISSUE THREAD

**Issue by Koyaani** [qgis/QGIS#50218]
### What is the bug or the crash?

When geometries are fetch from a Geopackage table with Z, the `wkbType` of geometries are 25D type (`0x80000001`) while the `wkbType` of the layer is Z (`10XX`). The problem is not present with other providers like shapefile or PostGis, nor when there is no Z or when there is ZM.

### Steps to reproduce the issue

1. Create a new table in a Geopackage with Z (but without M)
2. Create a new geometry, but without save the layer
3. Open the python console and execute `[f.geometry().wkbType() for f in iface.activeLayer().getFeatures()]`
   -> The print displays : `[1003]`
5. Save the layer
6. Execute `[f.geometry().wkbType() for f in iface.activeLayer().getFeatures()]`
   -> The print displays : `[-2147483645]`
7. Execute `iface.activeLayer().wkbType()`
   -> The print displays : `1003`

[Peek 15-09-2022 15-11.webm](https://user-images.githubusercontent.com/37629967/190412979-74d1cb2b-ede5-4e13-9c2c-e769c8c9c056.webm)

### Versions

3.22, 3.26 and master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lbartoletti** [comment]
@rouault I wonder why it works for shapefile and the geopackage needs a “better” cast?

**Comment by rouault** [comment]
> @rouault I wonder why it works for shapefile and the geopackage needs a “better” cast?

I'm not sure either, but your fix looks good to me

**Comment by lbartoletti** [comment]
> @rouault I wonder why it works for shapefile and the geopackage needs a “better” cast?

Because Shapefile use ZM and not only Z.
