### ISSUE TITLE
QGIS unexpectedly ended

### ISSUE THREAD

**Issue by GEHill-geh** [qgis/QGIS#50213]
### What is the bug or the crash?

QGIS crashes after I attempt to close the application

### Steps to reproduce the issue

1. Opened QGIS using shortcut on taskbar
2. Clicked on one of my projects
3. When I closed the application X, 
4. the following message appeared...
5. 
![image](https://user-images.githubusercontent.com/67903735/190361549-1562f2f4-6724-4908-97db-ea8ddb376767.png)

### Versions

QGIS Info
QGIS Version: 3.22.10-Bia?owie?a
QGIS code revision: 6a63fd37
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Try with a new profile (the box you didn't check 😃)

**Comment by GEHill-geh** [comment]
Didn't work.

I added a new profile and named it.  I opened a couple of existing projects using the new profile.  When I went to close the application, I got the above QGIS unexpectedly ended dialogue box again, so....Bug not fixed!
