### ISSUE TITLE
Processing algorithm "Lines to polygons" produces incorrect polygons

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#50226]
### What is the bug or the crash?

When using the processing algorithm "Lines to polygons" with certain data, it produces incorrect polygons.

Here is a simple (topologically correct) line layer to test the bug with: [lines_simplified.zip](https://github.com/qgis/QGIS/files/9581708/lines_simplified.zip)

### Steps to reproduce the issue

1. Add lines_simplified.json to the project 
![image](https://user-images.githubusercontent.com/33314057/190582982-f534d66e-2e9f-451d-a2e2-e2f2ba0608c4.png)

2. Run "Lines to polygons" processing algorithm with the layer 
![image](https://user-images.githubusercontent.com/33314057/190583033-87ac8d31-06ae-4c97-9747-f17dcd9778bf.png)

### Versions

QGISin versio
3.22.9-Białowieża
QGIS-koodin versio
a8e9e6fa
Qt:n versio
5.15.3
Python-versio
3.9.5
GDAL/OGR:n versio
3.5.1
PROJ-versio
9.0.1
EPSG-rekisteritietokannan versio
v10.064 (2022-05-19)
GEOS-versio
3.10.3-CAPI-1.16.1
SQLite-versio
3.38.1
PDAL-versio
2.3.0
PostgreSQL:n asiakkaan versio
14.3
SpatiaLite-versio
5.0.1
QWT-versio
6.1.6
QScintilla2-versio
2.13.1
Käyttöjärjestelmän versio
Windows 10 Version 2009

Aktiiviset python-lisäosat
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
plugin_reloader
0.9.1
Ilre
0.1.0

Also tested with QGIS 3.26.2 on Arch Linux

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The problem might lie with the dataset used. The same dataset causes the problems in #50227

**Comment by uclaros** [comment]
I didn't test the supplied dataset but the result you posted looks like an expected *Lines to polugons* output.
I suspect you want to use *Polygonize* instead

**Comment by Joonalai** [comment]
You are absolutely correct, with *Polygonize* it actually produces the wanted output! Thank you.
![image](https://user-images.githubusercontent.com/33314057/190954717-d85ce2ca-9971-420d-b721-78e4b139b424.png)

Still I am not sure how the original output looks like an expected but anyway, I'm closing this issue now.

**Comment by uclaros** [comment]
Lines to polygons creates a single polygon with the vertices of *each feature* in the input line layer. If the input lines are not closed, then the resulting polygon looks strange as it the first and last vertex are automatically connected to form the polygon.
There are valid use cases where this tool is irreplaceable, but I believe that most users expect it to work the way polygonize does. We probably should advertise Polygonize more!
