### ISSUE TITLE
Processing algorithm "Split with lines" does not split polygon

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#50227]
### What is the bug or the crash?

When using the processing algorithm "Split with lines" to split poylgon with certain line data, it does not split polygon at all.

Here is a simple (topologically correct) line layer to test the bug with: [lines_simplified.zip](https://github.com/qgis/QGIS/files/9581708/lines_simplified.zip)

### Steps to reproduce the issue

1. Add lines_simplified.json to the project 
![image](https://user-images.githubusercontent.com/33314057/190583751-450e71d4-f6a7-4a90-b9ab-fbfccebb0269.png)
2. Create polygon from layer's extent (with alg "Polygon from layer extent") 
![image](https://user-images.githubusercontent.com/33314057/190583872-abb1be63-95db-4416-befa-bc21df36f129.png)
3. Run algorithm "Split with lines" using the extent layer and the line layer and get the following output 
![image](https://user-images.githubusercontent.com/33314057/190584560-652cc702-f16b-4c30-a76e-3c7dec85684b.png)

The output has actually two polyons. One large one, and one tiny one of the upper right corner
![image](https://user-images.githubusercontent.com/33314057/190584795-151fd15f-5785-44fd-86bf-05d77075616c.png)

### Versions

QGISin versio
3.22.9-Białowieża
QGIS-koodin versio
a8e9e6fa
Qt:n versio
5.15.3
Python-versio
3.9.5
GDAL/OGR:n versio
3.5.1
PROJ-versio
9.0.1
EPSG-rekisteritietokannan versio
v10.064 (2022-05-19)
GEOS-versio
3.10.3-CAPI-1.16.1
SQLite-versio
3.38.1
PDAL-versio
2.3.0
PostgreSQL:n asiakkaan versio
14.3
SpatiaLite-versio
5.0.1
QWT-versio
6.1.6
QScintilla2-versio
2.13.1
Käyttöjärjestelmän versio
Windows 10 Version 2009

Aktiiviset python-lisäosat
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
plugin_reloader
0.9.1
Ilre
0.1.0

Also tested with QGIS 3.26.2 on Arch Linux

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The problem might lie with the dataset used. The same dataset causes the problems in #50226

**Comment by elpaso** [comment]
I've investigated this issue but I'm not sure that this is a bug: the lines_simplified contains several linestrings and it seems to me that only one intersects the extent in 2 places, that's why you get only one split operation.

Am I wrong?

**Comment by Joonalai** [comment]
Actually you are right. I thought that it was going to split the polygon according to other line strings as well but maybe I have to search an alternative algorithm for that (or code one myself).
