### ISSUE TITLE
.ci/run_tests.sh: test_core_networkaccessmanager (Timeout)

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#50234]
### What is the bug or the crash?

.ci/run_tests.sh reports a failure in test_core_networkaccessmanager

Seems related to #47395

### Steps to reproduce the issue

Run: .ci/run_tests.sh

### Versions

commit 6f9da191b4d8edbea8e8cb3ab20b8acd199b4282

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by troopa81** [comment]
It should be fixed with #50443 once merged
