### ISSUE TITLE
Allow multiple clicks in the toolbar hide/show selector (right-click on the toolbar area)

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#50245]
### Feature description

When willing to reorganize toolbar visibility it'd be useful for the selector to remain visible for the user to check/uncheck multiple items before being done.

See also #50244

**Comment by lnicola** [comment]
Pretty much a dupe of https://github.com/qgis/QGIS/issues/34635, but having menus stay open after a click seems weird UX to me.

**Comment by strk** [comment]
Thanks, closing as duplicate
