### ISSUE TITLE
print layout: cursor jumps when changing cell size of fixed table 

### ISSUE THREAD

**Issue by lindacamathias** [qgis/QGIS#50257]
### What is the bug or the crash?

In print layout when changing the cell size of a fixed table column/row in a fixed table the cursor "jumps" to the right after each single edit.
Example: when i want to change 71.55 into 62.55 i place the cursor behind the 7 > delete 7 and type 6 instead
(cursor jumps after the delete to the right and has to be placed in front of the 1 again to type 6. )
![cell_size_jumps](https://user-images.githubusercontent.com/77726342/191232377-f299e802-b272-4413-ad9a-fd8b20c5d982.gif)

### Steps to reproduce the issue

1. go to print layout
2. insert a fixed table
3. change row or column cell size
4. change for example 71.55 into 62.55 by placing the cursor behind the 7 > delete 7 and type 6 instead
(cursor jumps after the delete to the right and has to be placed in front of the 1 again to type 6. 

### Versions

3.26.2 and 3.22.10  (and older versions)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by antoniolocandro** [comment]
confirmed experienced the same in dev version today
