### ISSUE TITLE
Select field in table with 1 record with tabulator doesn't work

### ISSUE THREAD

**Issue by sercin** [qgis/QGIS#50264]
### What is the bug or the crash?

In QGIS 3.24 WIN - While editing a layer (points) and having the table open to change fields' content, and if only 1 record is displayed (selected or displayed) the tabulator doesn't move properly.
For example from field n. 5 it returns back to field 1.

Tabulator works properly with more than 1 record

### Steps to reproduce the issue

Load a layer (points)
Edit the layer
Open the Attribute table and select "Show selected features" 
Select a feature
Edit a field in the table
Try to use Tab to move

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.24.0-Tisler | Revisione codice QGIS | 6b44a42058
-- | -- | -- | --
Versione Qt | 5.15.2
Versione Python | 3.9.5
Versione GDAL/OGR | 3.4.1
Versione PROJ | 8.2.1
Versione database del Registro EPSG | v10.041 (2021-12-03)
Versione GEOS | 3.10.2-CAPI-1.16.0
Versione SQLite | 3.37.2
Versione PDAL | 2.3.0
Versione client PostgreSQL | unknown
Versione SpatiaLite | 5.0.1
Versione QWT | 6.1.3
Versione QScintilla2 | 2.11.5
Versione SO | Windows 10 Version 2009
  |   |   |  
Plugins Python attivi
beePen | 0.2.2
openlayers_plugin | 2.0.0
OSMDownloader | 1.0.3
QGISSortAndNumber-master | 1.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Versione di QGIS
3.24.0-Tisler
Revisione codice QGIS
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Versione Qt
5.15.2
Versione Python
3.9.5
Versione GDAL/OGR
3.4.1
Versione PROJ
8.2.1
Versione database del Registro EPSG
v10.041 (2021-12-03)
Versione GEOS
3.10.2-CAPI-1.16.0
Versione SQLite
3.37.2
Versione PDAL
2.3.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.3
Versione QScintilla2
2.11.5
Versione SO
Windows 10 Version 2009

Plugins Python attivi
beePen
0.2.2
openlayers_plugin
2.0.0
OSMDownloader
1.0.3
QGISSortAndNumber-master
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc).

**Comment by alexbruy** [comment]
Similar issue #35590.
