### ISSUE TITLE
Which kind of error is this? How to solve it?

### ISSUE THREAD

**Issue by Mumichel** [qgis/QGIS#50267]
## User Feedback

Below is the message l get when l try to edit a Feature table, then the system closes!! 

Windows fatal exception: access violation

Thread 0x000032ac (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x000032ac (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by agiudiceandrea** [comment]
@mumichel, could you please modify this issue report title to something more meaningful like "Crash editing the attribute table"?
Does the issue occurs also using a new QGIS user profile without external plugins?
Could you please provide the affected layer and exact steps to reproduce the issue?

**Comment by Mumichel** [comment]
Really I was trying to extend the Shape file by editing the attribute table, using the "Open field calculator" to get the data from the CSV File attribute table. It is being done normally, but at the time of saving the edited shape file, I get that message, no other option remaining except that the project closes itself.

I have also installed the HCMGIS Plugin. Is it a problem to save an edited or created shape file on Disc D? Sometimes this problem also rises.

Thank you!
