### ISSUE TITLE
Suspected reduced precision in "QGIS" vector Check Validity method causing false negatives.

### ISSUE THREAD

**Issue by JesseRMeyer** [qgis/QGIS#50262]
### What is the bug or the crash?

QGIS will report the polygon `POLYGON ((-998000 -292000,-998000 -284096.11976889,-992722.998884085 -285410.073094352,-992299.787312271 -281787.828810877,-993492.945112339 -292000,-998000 -292000))` (ESRI:102003 - USA_Contiguous_Albers_Equal_Area_Conic coordinate system) as invalid using its own method, claiming to suffer from an intersection.  I noticed I was able to trigger the same error manually in Python when performing intersection tests using 4 byte floats instead of the native 8 byte doubles. 

Does QGIS perform these validity checks with floats instead of doubles?  If so, I recommend to, at the least, respect the storage size when choosing what level of precision to preform arithmetic on.  Evidenced below, GEOS via OGR and Shapely confirm the polygon's validity, presumably due to the increased precision.

I leafed through 3 pages of related issues to see if this is a duplicate but did not find a match.

```python
import sys
import osgeo
from numpy import float32 as f32
from osgeo import ogr
import shapely
import shapely.wkt

ogr.UseExceptions()

# QGIS: This polygon is invalid - segments 1 and 3 of line 0 intersect at -992723, -285410
#POLYGON ((-998000 -292000,-998000 -284096.11976889,-992722.998884085 -285410.073094352,-992299.787312271 -281787.828810877,-993492.945112339 -292000,-998000 -292000))


def main():

    # floating point tolerance for coordinate system
    epsilon = float(0.0001)
    print(f'epsilon = {epsilon}')

    wkt = 'POLYGON ((-998000 -292000,-998000 -284096.11976889,-992722.998884085 -285410.073094352,-992299.787312271 -281787.828810877,-993492.945112339 -292000,-998000 -292000))'

    # OGR sez it's valid
    try:
        polygon = ogr.CreateGeometryFromWkt(wkt)
    except Exception as e:
        print(f'CreateGeometryFromWkt raised exception {str(e)}')
        sys.exit(1)
    if polygon is None:
        print(f'CreateGeometryFromWkt failed')
        sys.exit(1)
    if not polygon.IsValid():
        print(f'CreateGeometryFromWkt generated an invalid polygon')
        sys.exit(1)
    print(f'CreateGeometryFromWkt generated a polygon of area {polygon.Area()}')

    # Shapely also sez it's valid
    try:
        spolygon = shapely.wkt.loads(wkt)
    except Exception as e:
        print(f'shapely.wkt.loads raised exception {str(e)}')
        sys.exit(1)
    if spolygon is None:
        print(f'shapely.wkt.loads failed')
        sys.exit(1)
    if not spolygon.is_valid:
        print(f'shapely.wkt.loads generated an invalid polygon')
        sys.exit(1)
    print(f'shapely.wkt.loads generated a polygon of area {spolygon.area}')

    #  form the line segments between each pair of adjacent vertices
    ring = polygon.GetGeometryRef(0)
    npts = ring.GetPointCount()
    linesegs = []
    for p in range(npts - 1):
        # form the line segment between vertex p and p+1
        pt1 = ring.GetPoint(p)
        pt2 = ring.GetPoint(p+1)
        lineseg = ogr.Geometry(ogr.wkbLineString)
        lineseg.AddPoint(pt1[0],pt1[1])
        lineseg.AddPoint(pt2[0],pt2[1])
        linesegs.append(lineseg)

    # check each line segment for crossing with all of the others- Crosses does not complain
    for l in range(npts - 1):
        this_lineseg = linesegs[l]
        for m in range(npts - 1):
            if m!=l:
                if this_lineseg.Crosses(linesegs[m]):
                    crossing_point = this_lineseg.Intersection(linesegs[m])
                    print(f'Line segment {l+1} crosses line segment {m+1} at point {crossing_point.GetPoint(0)}')

    # the crossing lines connect points 1 and 2 (line A), and points 3 and 4 (line B), indexing from 0
    x1, y1, _ = ring.GetPoint(1)
    x2, y2, _ = ring.GetPoint(2)
    x3, y3, _ = ring.GetPoint(3)
    x4, y4, _ = ring.GetPoint(4)

    # slope and intercept for line containing each segment
    slopeA = (y2 - y1)/(x2 - x1)
    intA = y1 - slopeA*x1
    slopeB = (y4 - y3)/(x4 - x3)
    intB = y3 - slopeB*x3

    # intersection point between the lines
    ipx = (intA - intB)/(slopeB-slopeA)
    ipy = slopeA*ipx + intA
    print(f"Potential crossing point at ({ipx},{ipy})")

    # is the intersect point between the first line segment endpoints?
    # if so, it's a crossing point
    crossprod = (ipy - y1)*(x2 - x1) - (ipx - x1)*(y2 - y1)
    print(f'crossprod = {crossprod}')
    if abs(crossprod) > epsilon:
        print(f'The lines do not cross, cross product {crossprod} is greater than fp zero {epsilon}')
        sys.exit(0)
    dotprod = (ipx - x1)*(x2 - x1) + (ipy - y1)*(y2 - y1)
    if dotprod < 0:
        print(f'The lines do not cross, dot product {dotprod} is < 0')
        sys.exit(0)
    squaredlength = (x2 - x1)*(x2 - x1) + (y2 - y1)*(y2 - y1)
    if dotprod > squaredlength:
        diff = dotprod - squaredlength
        print(f'The lines do not cross, dot product {dotprod} is > squared length {squaredlength} (diff {diff})')
    else:
        print(f'The lines intersect at point ({ipx},{ipy})')

    # slope and intercept for line containing each segment
    # 4 byte floats
    x1, y1 = f32(x1), f32(y1)
    x2, y2 = f32(x2), f32(y2)
    x3, y3 = f32(x3), f32(y3)
    x4, y4 = f32(x4), f32(y4)
    slopeA = (y2 - y1)/(x2 - x1)
    intA = y1 - slopeA*x1
    slopeB = (y4 - y3)/(x4 - x3)
    intB = y3 - slopeB*x3

    # intersection point between the lines
    ipx = (intA - intB)/(slopeB-slopeA)
    ipy = slopeA*ipx + intA
    print(f"Potential crossing point at ({ipx},{ipy})")

    # is the intersect point between the first line segment endpoints?
    # if so, it's a crossing point
    crossprod = (ipy - y1)*(x2 - x1) - (ipx - x1)*(y2 - y1)
    print(f'crossprod = {crossprod}')
    if abs(crossprod) > epsilon:
        print(f'The lines do not cross, cross product {crossprod} is greater than fp zero {epsilon}')
        sys.exit(0)
    dotprod = (ipx - x1)*(x2 - x1) + (ipy - y1)*(y2 - y1)
    if dotprod < 0:
        print(f'The lines do not cross, dot product {dotprod} is < 0')
        sys.exit(0)
    squaredlength = (x2 - x1)*(x2 - x1) + (y2 - y1)*(y2 - y1)
    if dotprod > squaredlength:
        diff = dotprod - squaredlength
        print(f'The lines do not cross, dot product {dotprod} is > squared length {squaredlength} (diff {diff})')
        sys.exit(0)
    print(f'The lines intersect at point ({ipx},{ipy})')



if __name__ == '__main__':
    main()
```

### Steps to reproduce the issue

Happy to upload a GPKG of the polygon. 

Vector -> Geometry Tools -> Check Validity -> QGIS method

(Does not occur with neither GEOS nor manual algebraic method)

### Versions

Tried 3.22.8 LTR and 3.26.3 PR on OSX 12.6 and

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@JesseRMeyer, the "Check Validity" processing algorithm doesn't report any error (with both QGIS and GEOS methods) for the `POLYGON ((-998000 -292000,-998000 -284096.11976889,-992722.998884085 -285410.073094352,-992299.787312271 -281787.828810877,-993492.945112339 -292000,-998000 -292000))` geometry using QGIS 3.22.11 (OSGeo4W, GDAL/OGR 3.5.1, GEOS 3.10.3-CAPI-1.16.1) on my Windows 10 system.

Maybe a macOS specific issue?

**Comment by lbartoletti** [comment]
> @JesseRMeyer, the "Check Validity" processing algorithm doesn't report any error

Same on FreeBSD (clang compiler), but the geometry checker returns a self-contact

![current](https://user-images.githubusercontent.com/7521540/191493294-ea621c7e-ae33-4fd6-bf32-2634d467783b.png)

**Comment by agiudiceandrea** [comment]
> geometry checker returns a self-contact

Confirmed also on my system. Anyway the Geometry Checker plugin error checking depends on the Tolerance parameter. If you set it to 1E-10, the error is no longer reported.

**Comment by JesseRMeyer** [comment]
> 

Thanks!  Interesting about the OS behavioral difference.

Yes, that's expected.  That is showing that the intersection is only detected when the analysis is treating the inputs as 32bit floats.

AFAIK QGIS is using the libraries it is shipping with and not system / user provided ones (Glad to be educated otherwise).  If true, then there is some nefarious build setting that is either using fast-math or targeting floats for OSX targets.

**Comment by agiudiceandrea** [comment]
No error reported also using QGIS 3.26.3 on Ubuntu 22.04 (both from official repository and from Flatpak).
@JesseRMeyer, anyway you forgot to attach the layer, so my check was against the WKT imported in a Memory layer.

**Comment by JesseRMeyer** [comment]
TIL Github supports file uploading in comments!

[qgis_osx_validate.gpkg.zip](https://github.com/qgis/QGIS/files/9617856/qgis_osx_validate.gpkg.zip)

I don't know the project's organization or release process.  Is there someone we can tag who oversees the OSX build?

**Comment by JesseRMeyer** [comment]
Same validation failure on Win10.

![snip](https://user-images.githubusercontent.com/5846309/191543843-d82ca043-9633-4965-86f7-c8d50bb95e89.JPG)

**Comment by agiudiceandrea** [comment]
@JesseRMeyer, the Check Validity processing algorithm with QGIS method reports an error in a feature geometry contained in the layer you provided also using QGIS on Windows.

The WKT you provided has too less decimals so it doesn't represent the original geometry with sufficient precision. For this reason, my (and supposedly also the @lbartoletti's ones) previous checks did not report errors.

The error is reported instead using a WKT exported with more (17, the default) decimals:
`Polygon ((-998000 -292000, -998000 -284096.11976889020297676, -992722.99888408510014415 -285410.07309435232309625, -992299.78731227130629122 -281787.82881087699206546, -993492.94511233922094107 -292000, -998000 -292000))`

Using such WKT, you Python scripts outputs:

```Python
epsilon = 0.0001
CreateGeometryFromWkt generated a polygon of area 35704973.53452587
shapely.wkt.loads generated a polygon of area 35704973.53452551
Potential crossing point at (-992722.9988840851,-285410.0730943523)
crossprod = 0.0
The lines intersect at point (-992722.9988840851,-285410.0730943523)
Potential crossing point at (-992723.0,-285410.0625)
crossprod = 0.0
The lines intersect at point (-992723.0,-285410.0625)
```

**Comment by JesseRMeyer** [comment]
Ah, thank you.  I should have checked those myself before submitting this ticket.  Apologies for the red herring and thank you all again for debugging this issue for me.
