### ISSUE TITLE
Typing search bar ends with qgis crash

### ISSUE THREAD

**Issue by mchauvetnoreade** [qgis/QGIS#50274]
### What is the bug or the crash?

I type a search for the town "Somain" and qgis crashed

## User Feedback

I type a search for the town "Somain" and qgis crashed

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006584 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.1-Buenos Aires
QGIS code revision: b609df9ed4d
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Versions

qgis 3.26 Buenos Aires

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
QGIS does not have a built-in nominatim.

Are you using a plugin to search for a town ?
