### ISSUE TITLE
Hide items in the legend makes wrong feature count

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#50275]
### What is the bug or the crash?

When using `hide items` (right click on one legend item) and then selecting `show feature counts` all legend items (exept the one that has been activated before if one has been activated) only shows 0 feature count.

![image](https://user-images.githubusercontent.com/425243/191501886-eac3fc33-1327-4ac0-a605-4a65f2b05819.png)

Expected :
![image](https://user-images.githubusercontent.com/425243/191501972-6e615cf5-8601-4d7b-bce9-9fb5b8475500.png)

### Steps to reproduce the issue

1- Classify features 
2- Right click on one layer's legend item and then hide all
3- Activate (or not) one of the legend item
4- Select show feature count

### Versions

Tested on 3.26.0 and 3.22.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@arno974, following the steps you provided, it seems to me the issue doesn't occur on my Windows 10 system with both QGIS 3.22.11 and 3.26.3.
Could you please actually try the latest supported QGIS version using a new QGIS user profile?

**Comment by arno974** [comment]
You are right. Did the test again and everything seems to work as expected... Sorry !
