### ISSUE TITLE
Data alteration over several decimals of presicion

### ISSUE THREAD

**Issue by latot** [qgis/QGIS#50280]
### What is the bug or the crash?

I was checking how many decimals works with QGIS in WGS84, I notice QGIS changes the precision of the original data without perform any operation.

The idea, QGIS should never changes the original data, well obvs, if we move a point or do some ops the new geoms will be written with QGIS precision, but that should be do only when we perform an operation, the app it self should not change the data.

### Steps to reproduce the issue

I did the next thing:

1. Create a file with -33, -70 as initial coords
2. A table with a linestring from that point to the same but + 1*10^-precision
3. The table has 100 rows
4. Save the data as gpkg

That data is uploaded ```data.gpkg```, the code is uploaded too (in R).

6. Open the data in QGIS
7. Save the layer in other gpkg file
8. Compare with the original data

The result if uploaded too as ```qgis.gpkg```

The comparisons of the results, the end file should be the same as the original data, without any modification.

[data.zip](https://github.com/qgis/QGIS/files/9618239/data.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.11-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.5
Python version | 3.10.6
GDAL/OGR version | 3.5.2
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.39.2
PostgreSQL client version | 14.5
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.1
OS version | Gentoo Linux
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.5
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.11-Białowieża
QGIS code branch
[Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)
Qt version
5.15.5
Python version
3.10.6
GDAL/OGR version
3.5.2
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.39.2
PostgreSQL client version
14.5
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.1
OS version
Gentoo Linux

This copy of QGIS writes debugging output.

Active Python plugins
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.5
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by latot** [comment]
:O That was really an unexpected answer, maybe is a very different issue.

The issue I tryied to explain is that QGIS should not touch the data by default, change the precision of the numbers because was loaded is not great.

Load the data, and save it without do nothing should result in the same data.

As a second issue, as you explain, remains the question of how much precision would be necessary, this will depends completely of for what, but..., if I need to choose, would be a precision that depends on the zoom, if we are creating linestring of cm or more, we can detect it with that, there is the option to try to deduce it with some properties, like the length of linestrings, area of polygons and set an acceptable error based on how that properties changes. Still I think that would be other issue.

**Comment by latot** [comment]
Hi, seems I was wrong, does not seems QGIS changes the precision, in fact all the data is the same, so why the data changes? due to the gpkg, while I generated data in R that has 323 decimals, gpkg only supports 14 decimals for precision

This means, for this particular case, QGIS was able to handle the 14 decimal of gpkg, still I haven't tested a format that can support more than 14, shp has 14 too.

Ideal if someone of QGIS can confirm the app does not aprox the data.

Thx!

**Comment by roya0045** [comment]
STill think it's related to https://en.wikipedia.org/wiki/Double-precision_floating-point_format

**Comment by latot** [comment]
Yeah, seems pretty related, float64 seems is close to 15 decimals of precision, so, the tests should be moved to see if is possible use more than 64bits in geometries.

From the QGIS perspective, the question would be, QGIS supports float128, float256? or if depends on some lib that choose how to read that data.

**Comment by latot** [comment]
D: there is no way to get a more than that? after checking more this, I found the next thing.

QGIS should support enough decimals to can work in the resolution/zoom is able to show, if that support is double then that is right.

But..., even if it supports as a max double, QGIS should never round the data it gets/read, only round when there is an operation or in the features that was edited.

At least in my case, there has been a lot of problem with other App due to this, when values are rounded or truncated it can break networks and topologies saved as vectors D:

Maybe, there is a better approach to avoid break the topology (?

**Comment by latot** [comment]
Oks, after checking more about this, I think QGIS should support at least based in the specifications of the source.

In the particular case of GPKG, there is:
https://www.geopackage.org/spec/#gpb_format

Then, in the WKBGeometry we go to I9:
http://portal.opengeospatial.org/files/?artifact_id=25355

Then, in the downloaded document, page 21 (document page, not the footer number), we can found something like this:
```
Geometry
Point
+ X() : Double
+ Y() : Double
+ Z() : Double
+ M() : Double
```
I didn't read all the docs.., is too much, but probably all the precision of GPKG or even geometries depends on the precision of the point feature, in this case, is double, well, says double, 64bits, so as @elpaso says, QGIS do a good job for that, maybe the question is if we can have enough zoom to can use that precision.

In other cases, like Postgres, in my tests, IIRC it uses 47 decimals, its a lot, in that case, QGIS don't fully support this db D:

Even if is not supported a format completely, I think the min is tell the user if there will be a data lost, like save a Postgres to GPKG can cause this, or we connect to Postgres know there will be some decimals that will be list due to double.

**Comment by alexbruy** [comment]
Should we close this?

**Comment by latot** [comment]
QGIS use float64 (doubles) OGC SF says doubles, GPKG uses doubles, so in first place, from the original gpkg file, QGIS should not change any data, if is changing something, means in some place, there is a round/truncate or non double type.

D:
