### ISSUE TITLE
Algorithm can't be executed if `.` in filename

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#50288]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/39594821/191698921-3fed35fa-40ee-40bb-8c26-e0ce48d70f88.png)

It fails to determine the extension

### Steps to reproduce the issue

Try to output to a file with a `.` in filename

### Versions

3.22.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Is that only with the qgis processing tool or also directly with gdal? If it's the former, I suspect it shouldn't be unique to only GDAL tools.

**Comment by nicogodet** [comment]
Work fine in OSGeo Shell 
It's QGIS that miss interpret the file extension.

**Comment by nicogodet** [comment]
Not specific to GDAL alg

**Comment by nicogodet** [comment]
Faulty function 
https://github.com/qgis/QGIS/blob/529e5840ec7df22ee1a2f77f657fc1b00c6bdaf8/src/core/processing/qgsprocessingutils.cpp#L721

**Comment by nicogodet** [comment]
I agree that it is tricky to handle

**Comment by roya0045** [comment]
> I agree that it is tricky to handle

Should just find the last . or check only in the last x chars. use `filename()` then split with `.`, get last item. I don't think we have composite extensions as possible output as far as I remember.

Otherwise just add a notice/warning when more than one dot in the filename?

**Comment by agiudiceandrea** [comment]
Hi @nicogodet, see also https://github.com/qgis/QGIS/issues/49147#issuecomment-1165477524, https://github.com/qgis/QGIS/issues/40160#issuecomment-730073073, https://github.com/qgis/QGIS/issues/36353#issuecomment-626809574.

**Comment by nicogodet** [comment]
It seems that `suffix()` would be enough.
