### ISSUE TITLE
QGIS crash when I try to edit a shapefile

### ISSUE THREAD

**Issue by yaks48** [qgis/QGIS#50289]
### What is the bug or the crash?

If I try to create a new shapefile or if I try to edit an existing one, every time I click Toggle Editing and then Add Line Feature I get the error "Add feature: Cannot capture a shape without a shape tool defined". After I get this error and if click anywhere away from it it causes QGIS to crash. I am doing things exactly how I was doing them before without issues, and now for some reason this is happening and I cannot add new features to existing layers or new layers and QGIS crashes right after. 

thanks for the help !

### Steps to reproduce the issue

when editing and add a new feature, qgis crashes

### Versions

3.26.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Update to 3.26.3, it has been fixed
