### ISSUE TITLE
Random crashes while displaying file dialog on Ubuntu 22.04

### ISSUE THREAD

**Issue by enzedrailmaps** [qgis/QGIS#50284]
### What is the bug or the crash?

When attempting to perform file open or save operations such as but not limited to the following:

- Add a raster layer to the current project
- Save a layer definition file from a set of selected layers in the current project.
Qgis crashes just before the file operation dialog is displayed.

### Steps to reproduce the issue

Open a project
Attempt to perform an operation such as adding a raster layer or saving a layer definition file from a project.

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
processing
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This issue has been observed for many months and seems to be quite random in nature. Although creating a new profile resolves the issue for the moment, it seems to recur from time to time.

The issue goes away when a new profile is created. It is not clear what could be a cause of a problem in a profile since only the core plugins are in use (plugins being well known as a possible cause of problems) and the same plugins selected in the two profiles.

Attached are old_profile and new_profile. 

Initial analysis showed old_profile nearly twice the size of new_profile. This appears to be mainly in additional images in the preview_images folder. Clearing the contents of this folder does not clear the problem however, therefore any possible cause must be somewhere in user settings or other profile data.
[new-profile.zip](https://github.com/qgis/QGIS/files/9621731/new-profile.zip)
[old-profile.zip](https://github.com/qgis/QGIS/files/9621732/old-profile.zip)

**Comment by enzedrailmaps** [comment]
A further test with a new profile saw the issue recur, so it seems there is not an obvious profile related aspect to the crash.

**Comment by nicogodet** [comment]
Try to update to latest point release.
But if the crash is random, hard to troubleshoot...

**Comment by enzedrailmaps** [comment]
These issues never happen on the flatpak builds.
Is the reason we are not seeing more reports like this because a lot of people haven't yet updated to the new 22.04 LTS.

**Comment by nicogodet** [comment]
I'm on 22.04 @ home and QGIS does not crash when I add a raster.

Flatpak run in sandbox.
So could be related to your system environment

**Comment by enzedrailmaps** [comment]
It happens on multiple computers.
