### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by ezefer83** [qgis/QGIS#50297]
## User Feedback

Closing QGIS

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000df8 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

## User Feedback

Closing QGIS

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000df8 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Versions

3.24.3-Tisler

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Need more info and 3.24 is EOL, update to 3.26.3.

Provide steps to reproduce, describe what you were doing, etc...
