### ISSUE TITLE
3D Map View OBJ Export Crash

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#50294]
## User Feedback

I was attempting to export an OBJ model from the 3D Map View, and then QGIS crashed. The problem seems to occur when I use Rule-Based 3d symbols. The export works when I use the single-symbol setting.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005f60 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Set multiple Rule-Based 3D Symbols and attempt to export from 3d Map View to OBJ file.

### Versions

2.26.3

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you provide a sample project to reproduce ?

**Comment by alexbruy** [comment]
Not reproducible with the latest master (06b5c5112726b9d29a35fdc5d4bb0e428cf25061) both on Linux and Windows.
