### ISSUE TITLE
Exporting to PDF - fails to render the correct opacity level

### ISSUE THREAD

**Issue by AlanJMauger** [qgis/QGIS#50299]
### What is the bug or the crash?

I have layers of the GIS loaded over a hillshaded dtm. The layers have 35% opacity so as to drape them over the dtm. Everything is ok on the screen and saves into a project file ok but when I export to pdf the opacity returns to 100%. There don't appear to be any controls in the dialogue to adjust this if it is meant to be a feature..

### Steps to reproduce the issue

see above

### Versions

![image](https://user-images.githubusercontent.com/25891878/191874011-2c8d50f5-ecaf-4cd1-953f-c1854476e044.png)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please update to a supported version (3.22.11 or 3.26.3). 3.12 is EOL

**Comment by AlanJMauger** [comment]
Thankyou - problem solved
