### ISSUE TITLE
CTRL+SHIFT+TAB and CTRL+TAB not hiding panels

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#50298]
### What is the bug or the crash?

The key combos should hide/unhide panels in map canvas, is used to work but seems no longer...I am using Win 11 someone on twitter mentioned it did work for them under Ubuntu 20.04

### Steps to reproduce the issue

Open QGIS 3.26.3
load layers in map canvas
use CTRL+TAB or CTRL+SHIFT+TAB to hide panels, nothing happens

### Versions

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
latlontools
3.6.4
MemoryLayerSaver
4.0.4
mmqgis
2021.9.10
qconsolidate3
0.2.0
quick_map_services
0.19.29
shapetools
3.4.7
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It seems F11 is not working either

**Comment by nicogodet** [comment]
All shortcuts you mentioned work on my 3.26.3 on Win10.
Can you try on a Win10 machine ?

It could be linked to Win11...

**Comment by uclaros** [comment]
Also works fine on Debian
FYI since #48920 keyboard shortcuts should also work in ctr+shift+tab mode!

**Comment by antoniolocandro** [comment]
Huh, it seems to be specific to one profile today. Any way I can check what could be the profile issue?

**Comment by antoniolocandro** [comment]
Will look into this and report back

**Comment by antoniolocandro** [comment]
The only thing that I have is that for the profile having issues I have hidden quite a number of icons and menus which I find to be duplicated for me in a try to make it minimalist, maybe some interaction due to that but I suspect hiding toolbars, menus and icons shouldn't have an effect on the shortcut behaviour

**Comment by nicogodet** [comment]
If you can, could try to deactivate icons and menu one by one on a new profile until you reproduce the issue that you have with your current profile ?

**Comment by uclaros** [comment]
The keyboard shortcuts are assigned to Actions, and actions are added to toolbars and menus. When they are not visible, the shortcuts will not work, this is what was causing #40424 too in the first place.

**Comment by antoniolocandro** [comment]
Can the feedback label be removed, I will try to check which one of the toolbars or menu causes this but in my opinion hiding one of those should not impact the ability to hide panels using the current shortcuts

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc) on Windows and Linux. @antoniolocandro is this still a valid issue?

**Comment by antoniolocandro** [comment]
It is still valid, problem seems to happen because some other plugin or setting has taken over the key combination to be able to use Ctrl+Shift+Tab. Not probably this can be closed as it is not an issue with QGIS itself although I don't know what caused the overwrite of the shortcut keys
