### ISSUE TITLE
Map Composer - Legend does not display my layer (when using Only show items inside linked map with Data-defined Size Legend)

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#50301]
### What is the bug or the crash?

When using a point layer with the point size defined by attributes (to make proportional circles), if I use the `Only show items inside linked map` option, my layer disappear from the legend even if the layer is displayed on the map.

Before checking `Only show items inside linked map`

![image](https://user-images.githubusercontent.com/425243/191960941-be316ac4-28ba-4780-8868-90eb1a5286ed.png)

After checking `Only show items inside linked map`

![image](https://user-images.githubusercontent.com/425243/191961071-3f224541-722e-4906-a9cb-012c156b3fea.png)

### Steps to reproduce the issue

1. Add a point layer 
2. Specify a style for the point layer where the size is defined by attributes (using the assistant)
3. In map Composer add a map and a legend
4. Check Only show items inside linked map

### Versions

3.26.3.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@arno974, are you actually using a point layer with "the point size defined by attributes" or instead with Pie Chart Diagrams?
If the latter, I can confirm the issue.

**Comment by arno974** [comment]
@agiudiceandrea , I use a point layer with "the point size defined by attributes".

**Comment by arkottke** [comment]
I also get this bug. I would say that a better way to describe this bug is that a "Data-defined Size Legend" is not shown if the "Only show items inside linked map" is enabled.

**Comment by wonder-sk** [comment]
This may be a bit tricky - what should QGIS show when "Only show items inside linked map" is enabled? I can see several options what to show:
1. always show data-defined legend vs only show it when at least one symbol from that legend is visible
2. full data-defined legend vs partial legend - show all sizes in the data-defined legend or only the relevant sizes for symbol in the current map view

My gut feeling is that from (1) I would choose to show data-defined legend only when at least one symbol is visible on the map, and from (2) I would choose to always show the full data-defined legend. But I am curious what others think...
