### ISSUE TITLE
QGIS 3.26.3 GDAL Raster unavailable

### ISSUE THREAD

**Issue by Gorgazzo** [qgis/QGIS#50319]
### What is the bug or the crash?

Installed QGIS 3.26.3 on Windows 10. Allowed all permissions. Looking for GDAL Georeferencer in Raster menu. Not found. Search in installed plugins to activate it, Unavailable. 

### Steps to reproduce the issue

Opened QGIS
Opened a project
Opened Raster menu
Georeferencer not found
----
Opened plugins menu
looking for Georeferencer od GDAL Georeferencer
not found

### Versions

QGIS 3.26.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Gorgazzo the Georeferencer is in the "Layer" menu as it can now georeference both raster and vector layers.
