### ISSUE TITLE
Unstable CI test due to unavailable network service 503 Service Unavailable 

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#50316]
### What is the bug or the crash?

CI occasionally fails for problems which are related to network services being unavailable.
See:

https://github.com/qgis/QGIS/actions/runs/3114868919/jobs/5051179064#step:11:2995

Extract:
```
yarn install v1.22.19
  [1/4] Resolving packages...
  [2/4] Fetching packages...
  info There appears to be trouble with your network connection. Retrying...
  error An unexpected error occurred: "https://registry.yarnpkg.com/estree-walker/-/estree-walker-2.0.2.tgz: Request failed \"503 Service Unavailable\"".
```

The test succeeded in another run (for the same code):
https://github.com/qgis/QGIS/pull/50279#pullrequestreview-1119189900

### Steps to reproduce the issue

Create a pull request, hope that it fails
( don't do this, this are the steps to reproduce the issue )

### Versions

Current master branch as of 24 September 2022

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Passing the GitHub-Actions robot check is currently required by contributors to the project

**Comment by m-kuhn** [comment]
Is this a one time failure or has it been observed repeatedly?

**Comment by strk** [comment]
Personally I've only observed it once, but this is the first pull request I open since July 15 and the problem stroke me on first try.
