### ISSUE TITLE
crashes on exit

### ISSUE THREAD

**Issue by blackthornecol** [qgis/QGIS#50320]
## User Feedback

Always crashes when exiting QGIS

## Report Details

**Crash ID**: [f26e947319260720a4bf05ba4d601320801e99fb](https://github.com/qgis/QGIS/search?q=f26e947319260720a4bf05ba4d601320801e99fb&type=Issues)

**Stack Trace**
<pre>
QThread::currentThread :
QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsProcessingToolboxModel::addProvider :
QgsProcessingToolboxModel::rebuild :
QObject::qt_static_metacall :
QgsProcessingRegistry::providerRemoved :
QgsProcessingRegistry::removeProvider :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyDict_GetItemString :
PyArena_New :
PyRun_StringFlags :
instance :
instance :
QgsPluginRegistry::unloadAll :
QgisApp::saveWindowState :
QObject::qt_static_metacall :
QCoreApplicationPrivate::execCleanup :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Project > Exit QGIS

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Could you please try if QGIS also crashes on exit using a new QGIS user profile?
