### ISSUE TITLE
Browser shows wrong name for raster in gpky

### ISSUE THREAD

**Issue by Llaves** [qgis/QGIS#50334]
### What is the bug or the crash?

My project contains an 8 bit one band raster called Test_raster. Using the layer->Export dialog I export this to a new gpkg called raster1 and name the new layer  Test_raster. If I connect the gpkg to the Browser panel and expand the contents, the exported raster appears as raster1, same name as the gpkg. If I add this layer to the project, it is listed as raster 1. I now open the same gpkg in the DB Manager. The raster layer appears (correctly) as Test_raster. If I double-click Test_raster in the DB Manager it is added to the project and the layer is (correctly) named Test_raster. 

Summary - Browser shows the wrong name for raster in gpkg and uses that wrong name when adding to a project. DB Manager displays correct name for same gpkg, and adds layer with correct name.

### Steps to reproduce the issue

[raster1.zip](https://github.com/qgis/QGIS/files/9642788/raster1.zip)

Open blank project.
Connect file above to Browser under geopackages.
Expand the gpkg.
Note that gpkg contains raster dataset named raster1
Open DB Manager
expand same gpkg
note that the raster is now named Test_raster.
Add raster to project from Browser and from DB Manager
Note that the new layers have different names.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.0-Buenos Aires | QGIS code revision | 0aece2818e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.0
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
ClipMultipleLayers | 3.2.0
GeodesicDensifier | 1.2
joinmultiplelines | Version 0.4.1
latlontools | 3.4.4
MemoryLayerSaver | 4.0.4
PluginLoadTimes | 3.0.1
plugin_reloader | 0.7.9
qgis2web | 3.16.0
SRTM-Downloader | 3.1.17
vector_tiles_reader | 3.2.2
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.0-Buenos Aires
QGIS code revision
[0aece2818e](https://github.com/qgis/QGIS/commit/0aece2818e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ClipMultipleLayers
3.2.0
GeodesicDensifier
1.2
joinmultiplelines
Version 0.4.1
latlontools
3.4.4
MemoryLayerSaver
4.0.4
PluginLoadTimes
3.0.1
plugin_reloader
0.7.9
qgis2web
3.16.0
SRTM-Downloader
3.1.17
vector_tiles_reader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This was fixed in later 3.26 patch releases -- please update.
