### ISSUE TITLE
Invalid geometry after 'split parts" in a multipolygon using QGIS 3.26.3

### ISSUE THREAD

**Issue by kiri03** [qgis/QGIS#50348]
### What is the bug or the crash?

After making 'split parts' to a multipolygon, the result has been a multipolygon with invalid geometries.
A message appears that says:
"No part division has been done: The geometry is invalid. Please fix it before trying to split it."

### Steps to reproduce the issue

1. Select a polygon (I have a layer with only one polygon).
2. switch edition
3. Press the split parts icon
4. select two points that intersect the polygon to split it
5. do the same on one of the resulting parts
6. a yellow bar appears at the top of the screen with the mentioned error

### Versions

Versión de QGIS
3.26.3-Buenos Aires
Revisión del código de QGIS
65e4edfdada
Versión Qt
5.15.3
Versión de Python
3.9.5
Compilado contra GDAL/OGR
3.5.1
Ejecutándose contra GDAL/OGR
3.5.2
Versión de PROJ
9.1.0
Versión del registro de base de datos EPSG
v10.074 (2022-08-01)
Versión de GEOS
3.10.3-CAPI-1.16.1
Versión de SQLite
3.38.1
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I don't know if this also happens in previous versions

Can I only use the Split Parts tool on a polygon once? Yes
The second time throws an error of:
"Geometry is invalid"

I don't think the "2 parts" works either although I'm a bit surprised it does produce a polygon that can be saved. The polygon has a self-intersection geometry error, however, and while self intersection errors can often be ignored, many tools won't run on them and that's probably why you can't do a third "split". If you run a fix geometries on it you'll get back your original polygon. If you run multipart to single part you get a split like a split features would do. So there's no gain, just pain

**Comment by 3nids** [comment]
A polygon with 2 adjacent parts is an invalid geometry for GEOS. 
Not sure what is best here:
* a. prevent QGIS from producing them (difficult for the split too) or saving them (?)
* b. try to bring better message to the user about the reason of invalidity
* c. try to work on the part level (instead of feature level) when using the split tool

I am not an expert regarding the geometry engines. @nyalldawson what would you suggest?

**Comment by DelazJ** [comment]
For reference regarding pain with this tool https://github.com/qgis/QGIS/issues/20853#issuecomment-495846012 might be of interest (and if you can find an archive of the ML discussion...)
