### ISSUE TITLE
Georeferencer Tool Missing

### ISSUE THREAD

**Issue by ydqajap686** [qgis/QGIS#50359]
### What is the bug or the crash?

There is no Georeferencer in the plugins, raster menu, or processing toolbox.

### Steps to reproduce the issue

1. Open QGIS.
2. Search for Georeferencer option/dialog.

### Versions

QGIS version | 3.26.2-Buenos Aires | QGIS code branch | Release 3.26
Qt version | 5.15.5
Python version | 3.10.6
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.2 | Running against SQLite | 3.39.3
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | Manjaro Linux

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Possibly related, GDAL is having issues on Arch:

https://bugs.archlinux.org/task/75749?project=0&order=id&sort=desc&string=ed

**Comment by eurojam** [comment]
The tool is moved to the layer menu
![grafik](https://user-images.githubusercontent.com/46351209/192449956-348b211a-f851-46fc-a488-37b82814b84c.png)
