### ISSUE TITLE
Shapefle and geopackage render same data differently

### ISSUE THREAD

**Issue by joekbullard** [qgis/QGIS#50350]
### What is the bug or the crash?

The same data (A regular spaced point grid) renders differently in Shapefile and Geopackage when zoomed out beyond a specific scale. The geopackage viewed at scale displays a pattern that is not present in the shapefile.

## Geopackage
<img width="574" alt="Geopackage at 1:150000 scale" src="https://user-images.githubusercontent.com/35529853/192330209-f8014f64-00bf-441a-8994-9f13a4ba8c7b.png">

## Shapefile
<img width="566" alt="Shapefile grid at 1:150000 scale" src="https://user-images.githubusercontent.com/35529853/192330465-6fb87112-c9d3-4191-a521-206cc5241630.png">

### Steps to reproduce the issue

1. Create a regular point grid using Regular points tool, save as geopackage format

2. Zoom out to around 1:150000 scale

3. View result in map canvas

### Versions

3.26.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
That's just dependent on rendering order, I doubt this can be considered a bug, all the points are there.

**Comment by nyalldawson** [comment]
As @roya0045 noted, this is due to the internal differences in how these two formats order features. If you rely on a specific ordering of features during rendering then you should manually set a rendering order.
