### ISSUE TITLE
QGIS 3.26.3 - WMS GetMap requests failed with "Host requires, authentication", but not WMS GetCapabilities?

### ISSUE THREAD

**Issue by bangph** [qgis/QGIS#50369]
### What is the bug or the crash?

 I've tried to connect QGIS version 3.26.3  with a WMS service endpoint
 protected with basic authentication.

 The strange thing is, it can send WMS GetCapabilities without problem
 (with username and password given in the QIGS WMS login form).

 Images:

 - https://i.imgur.com/P8OJD7S.png

 - https://i.imgur.com/TUcOOFG.png

 However, it failed to send WMS GetMap with the given credentials. What
 is wrong here?

`
2022-09-27T05:56:29     WARNING    Map request failed [error: Host requires authentication url: https://URL/rasdaman/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=28.18762229046242851,-17.63489821170520599,42.61855979046242737,11.10185305274566048&CRS=EPSG:4326&WIDTH=689&HEIGHT=346&LAYERS=mundi.earthserver.xyz%3A7000%3AEU_DEM&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE]
`

### Steps to reproduce the issue

 Images:

 - https://i.imgur.com/P8OJD7S.png

 - https://i.imgur.com/TUcOOFG.png

 However, it failed to send WMS GetMap with the given credentials. What
 is wrong here?

`
2022-09-27T05:56:29     WARNING    Map request failed [error: Host requires authentication url: https://URL/rasdaman/ows?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=28.18762229046242851,-17.63489821170520599,42.61855979046242737,11.10185305274566048&CRS=EPSG:4326&WIDTH=689&HEIGHT=346&LAYERS=mundi.earthserver.xyz%3A7000%3AEU_DEM&STYLES=&FORMAT=image/png&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi:96&TRANSPARENT=TRUE]
`

### Versions

3.26.3 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by bangph** [comment]
@agiudiceandrea I didn't see anything in Debugging panel (F12). It is not a problem from WMS server, but from QGIS itself I can say.

**Comment by agiudiceandrea** [comment]
To see the requests in the "Debugging/Development Tools" panel, you need to use the "Network Logger" and start the logging with the "Record Log" button before adding the WMS layer to the map. Please see the linked user manual page for more info.

**Comment by bangph** [comment]
@agiudiceandrea thanks, I got it. I can capture the requests like below. 

![image](https://user-images.githubusercontent.com/6914451/192552622-72427ad6-84c0-43df-b90c-a65c3d448790.png)

The strange thing is, the black lines contain the Header with authentication. But the red lines don't contain the header with authentication. 

The black line contains the basic header (credentials are hidden here) which is good:

![image](https://user-images.githubusercontent.com/6914451/192553232-814f5e0e-f2ab-473c-b3bb-a852969161d5.png)


Here is the header in one of  the red line (no basic header is sent).

![image](https://user-images.githubusercontent.com/6914451/192553033-94828f7f-3d35-4c41-ac17-a155494d2f29.png)

**Comment by bangph** [comment]
@agiudiceandrea oh I see why, the red ones are HTTPS but the black ones are HTTP. 
This server end point is [HTTPS](https://URL/rasdaman/ows)

**Comment by agiudiceandrea** [comment]
So, is the correct WMS URL an http or an https one? Did you add the WMS URL in QGIS as http or https?
Is the GetMap operation OnlineResource URL in the capabilities xml document the same as the one you specified as the WMS URL in QGIS? If it is different, have you tried the "Ignore GetMap/GetTile/... URI reported in capagilities" option?

Anyway, it would be great if you could specify the WMS server URL and auth. credentials. Otherwise, it could be useful if you could share a evenly redacted version of the WMS capabilities xml document and of the network request sent to the WMS server by QGIS in order to let the developers better understand what's going wrong.

**Comment by bangph** [comment]
@agiudiceandrea For the record, the issue belongs to the server endpoint. I put https for WMS in QGIS, but the server contains WMS GetCapabilities with http instead of https. That was the issue which caused both QGIS 2.14 and QGIS 3.26.3 cannot work with WMS with basic header authentication enabled.

`
 <Request>
            <GetCapabilities>
                <Format>text/xml</Format>
                <DCPType>
                    <HTTP>
                        <Get>
                            <OnlineResource xlink:href="http://URL/rasdaman/ows" xlink:type="https://weather.cube4envsec.org/rasdaman/ows"/>
                        </Get>
                        <Post>
                            <OnlineResource xlink:href="http://URL/rasdaman/ows" xlink:type="https://weather.cube4envsec.org/rasdaman/ows"/>
                        </Post>
                    </HTTP>
                </DCPType>
            </GetCapabilities>
            <GetMap>
                <Format>image/jpeg</Format>
                <Format>image/png</Format>
                <Format>image/tiff</Format>
                <DCPType>
                    <HTTP>
                        <Get>
                            <OnlineResource xlink:type="http://URL/rasdaman/ows" xlink:href="https://weather.cube4envsec.org/rasdaman/ows"/>
                        </Get>
                        <Post>
                            <OnlineResource xlink:href="http://URL/rasdaman/ows" xlink:type="https://weather.cube4envsec.org/rasdaman/ows"/>
                        </Post>
                    </HTTP>
                </DCPType>
            </GetMap>
        </Request>
`
