### ISSUE TITLE
Windows "Please Wait"

### ISSUE THREAD

**Issue by cobeit** [qgis/QGIS#50365]
### What is the bug or the crash?

I don't know if this is the right place to post this. 
When we install QGIS (tried with different versions) our users will get a "Pleas wait" before they can log on to there domain joined Windows 10 computers. Sometimes it is up to 40 min. If we uninstall QGIS and clean the reg. the problem will disappear. Also if we remove the LAN cable or disable the wifi. Any idea how to solve this ?

### Steps to reproduce the issue

.

### Versions

3.14.0, 3.22.1, 3.26,2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue?
