### ISSUE TITLE
Add tooltips in metadata tabs for layers

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#50367]
### Feature description

# Problem

When updating metadata records for a layer, the validation tab specifies that a link should be added for that records. The link tab also contains some mandatory fields which need to be filled but the scroll bar for the link type is too small to read what link types mean

Link type
![Screenshot from 2022-09-27 11-04-48](https://user-images.githubusercontent.com/2510900/192484321-7135ff2a-d71c-4fee-a0fe-c959b375f4b1.png)

Same as the mime types
![image](https://user-images.githubusercontent.com/2510900/192484264-79fea7b1-fdf1-4493-ae77-367492a660cd.png)

**Comment by agiudiceandrea** [comment]
Doesn't just enlarging the columns makes the options fully readable?

**Comment by NyakudyaA** [comment]
School boy error, Actually had forgotten to do this
