### ISSUE TITLE
Unable to install after system update Ubuntu.

### ISSUE THREAD

**Issue by marshallcoz** [qgis/QGIS#50376]
### What is the bug or the crash?

After today's system update (27/September/2022) including a security update for a kubuntu 20.04 PC, QGIS was uninstalled as part of the update, and can no longer be installed from ubuntu-ltr bullseye repository. Neither from the Buenos Aires release.

The _apt_ output message includes:

> The following packages have unmet dependencies:
 qgis : Depends: libexiv2-27 (>= 0.27.3) but 0.27.2-8ubuntu2.7 is to be installed
        Depends: libqgis-3d3.22.11 but it is not going to be installed
        Depends: libqgis-analysis3.22.11 but it is not going to be installed
        Depends: libqgis-app3.22.11 but it is not going to be installed
        Depends: libqgis-core3.22.11 but it is not going to be installed
        Depends: libqgis-gui3.22.11 but it is not going to be installed
        Depends: libqt5core5a (>= 5.15.1) but 5.12.8+dfsg-0ubuntu2.1 is to be installed
        Depends: libqt5network5 (>= 5.15.1) but 5.12.8+dfsg-0ubuntu2.1 is to be installed
        Depends: python3-qgis (= 1:3.22.11+16bullseye) but it is not going to be installed
        Depends: qgis-providers (= 1:3.22.11+16bullseye) but it is not going to be installed
        Depends: qgis-common (= 1:3.22.11+16bullseye) but 1:3.26.3+16bullseye is to be installed
        Recommends: qgis-plugin-grass but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

### Steps to reproduce the issue

sudo apt update
sudo apt install qgis

### Versions

bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Klemet** [comment]
I'm having the exact same issue. Can't install QGIS at all on my side. Even aptitude is lost.

**Comment by alexbruy** [comment]
Is this still valid with the latest versions?
