### ISSUE TITLE
Multiple selections and completer does not work together in Value Relation

### ISSUE THREAD

**Issue by 9ls1** [qgis/QGIS#50371]
### What is the bug or the crash?

If I activate both "Allow multiple selections" and "Use completer", only multiple selections is possible/available. It is not possible start entering a value to get a list with the option(s).
![image](https://user-images.githubusercontent.com/10632163/192543670-1594a5c4-fc2b-4607-add7-876270f8a98e.png)

Nowhere to start entering a value (a species name in this case):
![image](https://user-images.githubusercontent.com/10632163/192543904-455bfbe6-6194-4754-81ca-c20540146646.png)

(If I don't activate "Allow multiple selections", the completer appears and I can start entering a name:
![image](https://user-images.githubusercontent.com/10632163/192543101-291ac9aa-29f4-4305-9476-46fec31cd305.png))

I may combine the mentioned options with "Allow NULL values" and "Order by value", but doesn't the use of check boxes indicate that you may check whatever options you want, e.g. all four of them?

### Steps to reproduce the issue

Having a list (CSV-file) and a point-layer that may be joined through value relation.
1. Go to Layer Properties - Attributes Form - Autogenerate
2. Click on the the field and set widget type to "Value Relation"
3. Check both "Allow multiple selections" and "Use completer".
4. Set point layer in edit mode and add a point. 
5. In the Features Attributes window, the completer will be missing.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdada
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
DataPlotly | 3.9.2
get_nib-main | 0.7
GroupStats | 2.2.6
InvisibleLayersAndGroups | 2.2
LAStools | 1.4
legend_data_filter | 0.1
plugin_reloader | 0.9.1
Projestions | 1.0.1
qfieldsync | v4.2.0
Smart_Map | 1.2
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdada](https://github.com/qgis/QGIS/commit/65e4edfdada)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
DataPlotly
3.9.2
get_nib-main
0.7
GroupStats
2.2.6
InvisibleLayersAndGroups
2.2
LAStools
1.4
legend_data_filter
0.1
plugin_reloader
0.9.1
Projestions
1.0.1
qfieldsync
v4.2.0
Smart_Map
1.2
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I was hoping for the same behavior as in Input from Mergin Maps [(https://merginmaps.com/docs/layer/settingup_forms/#value-relation)](https://merginmaps.com/docs/layer/settingup_forms/#value-relation) based on QGIS core library):
![image](https://user-images.githubusercontent.com/10632163/192544489-dd145756-09f6-4298-aa10-3fd4d0e91c67.png)

**Comment by saberraz** [comment]
Here is an example of the way it should work:

Having a list of 400 species, among these: betty blue, lady in red, mid-blue fish, pink panter, redcat, nemo, silly season.

Out in the field I observe betty blue, mid-blue fish and redcat.

In that case I would like to start typing “blue”, the list will the be narrowed down to all species containing the string blue. I will then tick the check boxes for betty blue and mid-blue fish.

After checking these two boxes, I clear the search (completer) field and start typing “red”. The list will now only show the species containing red in their name. I tick the check box for redcat. No more species to see, so I finish my registration.

So I have check-marked three alternatives, and all three observations are to be stored in an attribute called “obs_art” (so when looking in the attribute table after registration, the attribute (column) obs_art will contain something similar to: { ‘betty blue’, ‘mid-blue fish’, ‘redcat’} or {14, 32, 59} if the corresponding values are stored.
