### ISSUE TITLE
Export to .csv fails when overwriting existing file

### ISSUE THREAD

**Issue by lbell** [qgis/QGIS#50389]
### What is the bug or the crash?

Exporting a geopackage layer to a CSV that already exists should overwrite the file (with a warning perhaps). Instead, it throws this error:

```
Save File Error:
Export to vector file failed.
Error: Creation of layer failed (OGR error: Attempt to create csv layer (file) against a non-directory datasource.)
```

### Steps to reproduce the issue

1. Export a layer to CSV
2. Choose an existing CSV as the path to export
3. Export

### Versions

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
joinmultiplelines | Version 0.4.1
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
joinmultiplelines
Version 0.4.1
sagaprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Not reproducible with the latest master (8c8a43b44e06af3c6577d287fecf672c7c1fe3dc). QGIS asks whether you want to overwrite file, overwrite layer, etc. and correctly overwrites existing file.

**Comment by lbell** [comment]
Agreed - seems to be working now.
