### ISSUE TITLE
"On the fly raster" does not work correctly in Raster Processing

### ISSUE THREAD

**Issue by moonstripe** [qgis/QGIS#50390]
### What is the bug or the crash?

Expected behavior: by clicking the "on the fly raster" checkbox and typing a layer name, I expect to be able to add a raster layer without needing to save a geoTIFF file.

Current behavior: first clicking "on the fly raster", then typing a layer name, and finally clicking OK, the "calculating raster" doesn't appear.

Current workaround: I need to save the geoTIFF in order to see my calculated raster.

### Steps to reproduce the issue

1. Go to "Raster Calculator", click the "Create on-the-fly raster without saving to disk".
2. Name the Raster Layer
3. Perform a calculation, eg: NDVI = (nir - red)/(nir + red), make sure expression is valid
4. Click "OK"
5. Raster calculation progress bar does not appear.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.2-Buenos Aires | QGIS code revision | b0f8302dbc
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 11.2
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

QGIS version
3.26.2-Buenos Aires
QGIS code revision
[b0f8302dbc](https://github.com/qgis/QGIS/commit/b0f8302dbc)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 11.2

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Can you clarify what the error actually is? You wouldn't expect to see any progress bars here, the raster will be dynamic created on demand (ie during render)
