### ISSUE TITLE
Exiting QGIS 3.22.11 causes a crash.

### ISSUE THREAD

**Issue by jlwillers** [qgis/QGIS#50392]
## User Feedback

Exiting QGIS 3.22.11 causes the crash.

## Report Details

**Crash ID**: [df7ab36d97299e20a77faa2780932f1ee15ee61c](https://github.com/qgis/QGIS/search?q=df7ab36d97299e20a77faa2780932f1ee15ee61c&type=Issues)

**Stack Trace**
<pre>
CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
pcraster::python::Globals::setRandomSeed :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
pcraster::python::Globals::setRandomSeed :
pcraster::python::Globals::setRandomSeed :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

Clicked on 'Exit QGIS'.  Projected being worked on was created by QGIS 3.26,2, but I needed pc raster and pc raster tools to determine flow direction, so I needed to use 3.22.11 LTR to do that task.

### Versions

QGIS version
3.22.11-Białowieża
QGIS code revision
106d33d7
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
crayfish
3.6.0
pcraster_tools
0.2.0

RasterAttributeTable
1.1
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
See https://github.com/pcraster/pcraster/issues/361
Not a QGIS issue.
