### ISSUE TITLE
"RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted" 

### ISSUE THREAD

**Issue by JDawson0523** [qgis/QGIS#50405]
### What is the issue about the documentation?

When running any .model3, I receive the following error...

> An error has occurred while executing Python code: 
> 
> RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted 
> Traceback (most recent call last):
> 
>   File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 292, in on_complete
>     self.tr(elapsed_time(start_time, 'Execution failed after')))
> 
>   File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 236, in elapsed_time
>     str_hours = [self.tr("hour"), self.tr("hours")][hours > 1]
> 
> RuntimeError: wrapped C/C++ object of type AlgorithmDialog has been deleted
> 
> 
> Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
> QGIS version: 3.26.3-Buenos Aires Buenos Aires, 65e4edfdada 
> 
> Python Path:
> ...

I attempted to add the model to the toolbox directly, checked that all plugins were installed and turned on, and checked for any updates (none were found).  I didn't find any way to further configurate the tools, but I may have missed something.  I tried running a dataset that had already been successfully run through the tool and it failed.  Each time the error occurs at the "split lines by maximum length" tool.  This is happening on the company remote machine and my local machine. and there have been no other changes to those computers since the error began yesterday (9/28/22).  Online research indicates this is likely a bug in the Processing Toolbox.

**Comment by nicogodet** [comment]
Did you try with a new profile ?
(Settings -> User profiles -> New profile)

If error still happens, could you share a sample model + dataset to reproduce ?
