### ISSUE TITLE
Crash after "Adjust to content" to the Legend properties

### ISSUE THREAD

**Issue by vbonnal** [qgis/QGIS#50414]
### What is the bug or the crash?

QGis unexpeted end after cliking on "Adjust to containt" to the Legend properties. This crashes on several occasions with 2 legends

### Steps to reproduce the issue

in the layout manager, with a map object and 2 legend objects
I want to adjust the frame of my legend freely, I uncheck Adjust to content of the 1st legend, and when I uncheck Adjust to content of the 2nd legend, there is a crash
 
![image](https://user-images.githubusercontent.com/7264734/193344892-077d70be-df20-43c6-b28c-6dc178dc0dee.png)

`## User Feedback

I'm just clicking on  "Adjust to containt" to the Legend properties. This crashes on several occasions.

## Report Details

**Crash ID**: [e47593f0efa96ccbed54293a1a34edfd4d76fb31](https://github.com/qgis/QGIS/search?q=e47593f0efa96ccbed54293a1a34edfd4d76fb31&type=Issues)

**Stack Trace**
<pre>
QgsLayerTreeModel::node2index :
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::setLegendFilter :
QgsLayoutItemLegend::doUpdateFilterByMap :
QgsLayoutItemLegend::paint :
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

**QGIS Info**
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
</pre>`

### Versions

3.22.11 for Windows

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by troopa81** [comment]
Can you share a project and data ?
