### ISSUE TITLE
Crash after selecting Fixed Interval mode in graduated symbology

### ISSUE THREAD

**Issue by rnlbd** [qgis/QGIS#50416]
### What is the bug or the crash?

I'm new to QGIS and have just been following the Training Manual "§3.3.3. Ratio Classification" using the training files provided. In that chapter it is asked to create a graduated symbology based on an area field. In my case, the mode was by default "Fixed interval" so that when I clicked "Classify" it crashed. I realised that the screenshot used in the training had the mode "Equal count (quantile)" selected. Using that mode doesn't crash.

### Steps to reproduce the issue

To reproduce the issue, just follow the training, chapter 3.3.3 [https://docs.qgis.org/3.22/en/docs/training_manual/vector_classification/classification.html](url)

1.Open the Layer properties dialog’s Symbology tab for the landuse layer
2.Change the classification style from Categorized to Graduated
3.Change the Value to AREA _<-- this requires having already added a field AREA in the attributes table of the layer "Landuse"_
4.Under Color ramp, choose the option Create New Color Ramp…:
5.Choose Gradient (if it’s not selected already) and click OK.
6.Click OK
7.Click Classify **<-- crashes if the mode Fixed interval" is already selected **

### Versions

Version de QGIS
3.26.3-Buenos Aires
Révision du code
65e4edfdada
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.1
Version de Proj
9.1.0
Version de la base de données du registre EPSG
v10.074 (2022-08-01)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.38.1
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
OSMDownloader
1.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is a duplicate of #49333 and there is already a pending pr to address it (#50290)

The default fixed interval value is 1, so in your case it generates way too many classes between minimum and maximum area causing the crash

**Comment by rnlbd** [comment]
Ok, thanks for the feedback. I didn't manage to find the post you mentionned before writing mine.

**Comment by uclaros** [comment]
No problem! Thanks for taking the time to report anyway :)

**Comment by OisinSlevin** [comment]
I'm running into this issue still, while there is a way around it its not at all intuitive considering most will attempt to work from top to bottom, fill out the value field, then select the mode "fixed interval" and then change the interval size. needs addition of an error message with max number of intervals reached and the fixed interval with value 1 should not automatically apply when the mode is selected

**Comment by widmerc** [comment]
Experiencing this issue also in 3.42.3 'Münster'. I think the default class size = 1 is the problem?

**Comment by OisinSlevin** [comment]
> Experiencing this issue also in 3.42.3 'Münster'. I think the default class size = 1 is the problem?

as far as I remember, this is the cause where it automatically applies when you select fixed interval, so when class size=1 it starts working and if there are too many classes it crashes.  It  should automatically calculate class size to make ~10 classes at first  so not to crash the programme
