### ISSUE TITLE
ESRI/EPSG codes mismatch on export>Save Features As...

### ISSUE THREAD

**Issue by mapninja** [qgis/QGIS#50419]
### What is the bug or the crash?

Exporting a shapefile using `ESRI:102999` results in a shapefile with` EPSG:6419` CRS defined. 

### Steps to reproduce the issue

Exporting an `EPSG:4269` shapefile to a new shapefile using `ESRI:102999 - NAD_1983_2011_StatePlane_California_III_FIPS_0403` as the output CRS results in a shapefile with `EPSG:6419 - NAD83(2011) / California zone 3` as it's CRS. Not a show stopper, but definitely confusing and not the expected behavior. 

Discovered while writing this, so here is the full workflow:
https://github.com/mapninja/Earthsys144/blob/master/Labs/Week_02/Coordinate_Systems_Geodesy.md

### Versions

MacOS Monterey
QGIS 3.26.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Might be related to proj and handling esri's code, as I assume they might be closed source or some other limiting factor related to them.

**Comment by agiudiceandrea** [comment]
I can also confirm the issue on Windows with QGIS 3.22.10: when a vector layer (with any CRS) is exported as an ESRI Shapefile layer selecting the "ESRI:102999 - NAD_1983_2011_StatePlane_California_III_FIPS_0403" CRS, then the exported layer CRS is recognised by QGIS as "EPSG:6419 - NAD83(2011) / California zone 3" instead.

The exported ESRI Shapefile layer *.prj sidecar file contains the `PROJCS["NAD_1983_2011_StatePlane_California_III_FIPS_0403",GEOGCS["GCS_NAD_1983_2011", ...` string.

The issue doesn't occur if the layer is exported e.g. as GeoPackage, GeoJSON or FlatGeobuf: in this cases the exported layer CRS is recognised by QGIS as "ESRI:102999 - NAD_1983_2011_StatePlane_California_III_FIPS_0403"

It seems to me this is a GDAL and/or PROJ issue.

**Comment by rouault** [comment]
EPSG:6419 and ESRI:102999 are aliases of each other. When writing a shapefile .prj, ESRI WKT must be used, and the representation of them is identical, and ESRI WKT doesn't contain a AUTHORITY:CODE.
When reading back, OGR will prefer the EPSG code to the ESRI one when 2 CRS match the ESRI WKT definition, because that's more interoperable
So for me works as intented, and there's not much that can be done to change that behavior.
