### ISSUE TITLE
Show clicked row/column of raster in Identify Results

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#50421]
### Feature description

When clicking a location in a raster it would often be helpful to see the row and column coordinates of the clicked pixel. This could go nicely into the "derived" tree.

![image](https://user-images.githubusercontent.com/7661092/193421620-8c795120-acf0-44db-a6d5-13d62e3af706.png)

For vector layers there are already a lot of additional information shown in "derived" for the clicked feature:

![image](https://user-images.githubusercontent.com/7661092/193421639-acd241db-7061-41c6-8818-ed4477f48fad.png)

### Additional context

The Value Tool plugin does this but it would be a great feature for a standard QGIS setup. (https://twitter.com/kgjenkins/status/1575929503968555008)

**Comment by nyalldawson** [comment]
Fixed in 5e2fddd
