### ISSUE TITLE
QGIS crashes without any info in log

### ISSUE THREAD

**Issue by strokovnjaka** [qgis/QGIS#50428]
### What is the bug or the crash?

I'm consistently crashing my QGIS windows installation for certain data that I'm loading. 
I've tried logging every possible thing (with the recipe from https://stackoverflow.com/a/53170689), but cannot find any info as to what is happening there.

I'm using my own python plugin, which loads some data from an SQL server and creates some layers and does some calculations. It works very well for more than 1000 different datasets, but consistently crashes the whole QGIS app on a single one (so far).  The app simply disappears, there is no "QGIS unexpectedly ended" or similar, even nothing in any logs.

To make it weirder, on a rare occasion (1 out of ~20 tries) it works fine with this 'problematic' dataset. So, the problem is not the plugin (well, it may be, but the app shouldn't crash, right?) nor the data. Unfortunately, I cannot share neither the plugin nor the data.

Are there any options left for getting some info about what is crashing the app, besides getting the whole QGIS project source and debugging it?

### Steps to reproduce the issue

Open plugin and load data.

### Versions

3.22, 3.26.2, 3.27.0-master 8706c7e27a all crash the same way

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
You have no other choice than sharing the data or debug it yourself. If the plugin is responsible for the crash you should file a bug in the plugin repository, not here.

**Comment by strokovnjaka** [comment]
It seems debugging is the way to go. I would expect, however, from the app (any app for that matter) that it wouldn't crash the way it does...
