### ISSUE TITLE
Georeferencer not find in 3.26.3

### ISSUE THREAD

**Issue by ghgeosnap** [qgis/QGIS#50420]
### What is the bug or the crash?

Georeferencer not find in 3.26.3,  Win 64
not in Menu: Raster/
not in Menu: Extensions / acquire and install /

### Steps to reproduce the issue

a

### Versions

Georeferencer not find in 3.26.3,  Win 64

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by kannes** [comment]
https://gis.stackexchange.com/questions/434544/finding-georeferencer-in-qgis -> Check the Layer menu.

**Comment by roya0045** [comment]
Not a bug, just changed place.
