### ISSUE TITLE
Hard crash when zooming out to approximately > 1:25,000,000 in a project converted to 3.26.3 from 3.26.0

### ISSUE THREAD

**Issue by lhilarides** [qgis/QGIS#50437]
### What is the bug or the crash?

QGIS crashes unexpectedly when zooming out to a continental / global level. This only seems to happen in projects converted from earlier versions of QGIS before being upgraded to 3.26.3. When I copy/paste all layers from the existing 3.26.0 project into a newly created 3.26.3 project the crash does not occur.

### Steps to reproduce the issue

1. Create a project in 3.26.0
2. Add some layers (I used a mix of .gpkg, xyz and tiffs)
3. Upgrade to 3.26.3
4. Open the project
5. Zoom out to a continental or global level
6. Crash

### Versions

3.26.0 / 3.26.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue with latest versions? Can you attach a test dataset?

**Comment by lhilarides** [comment]
No, seems to have been fixed 😁

I've been running 3.28 since it became LTR
