### ISSUE TITLE
QGIS Docker image does not include the PDAL library

### ISSUE THREAD

**Issue by glegarec** [qgis/QGIS#50444]
### What is the bug or the crash?

I am running QGIS 3.26.1 in a Singularity image converted directly from the latest Docker image available from the [official QGIS docker repository](https://hub.docker.com/r/qgis/qgis/) : 
```DIGEST:sha256:e12a43b0b9e25c0e13eff8410936618044f937769f96287585bdb9aa404750b3```

When I try to open a .las or .laz file with QGIS, I am getting the following message :

```
LAS and LAZ files cannot be opened by this QGIS install. This QGIS build does not include the PDAL library dependency required for opening LAS or LAZ point clouds.
```

![MicrosoftTeams-image (25)](https://user-images.githubusercontent.com/18538995/192788019-b2ac7fa5-a64d-4f37-a460-ca1b653b169b.png)

### Steps to reproduce the issue

1. Open QGIS
2. Drag and drop any .las or .laz file into the main window.

### Versions

QGIS version
3.26.1-Buenos Aires
QGIS code branch
Release 3.26
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PostgreSQL client version
12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.4 LTS

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by qiang-lau** [comment]
I had the same problem

**Comment by jsmoreau** [comment]
Same here. @qiang-lau Did you find a workaround?

**Comment by jsmoreau** [comment]
@3nids seems to be the maintainer for the image. Is there a way to fix this?

**Comment by joostmeulenbeld** [comment]
I have the same problem as OP, using docker tag `qgis/qgis:release-3_28` from docker hub: when running QGIS from that image, I cannot open an LAZ file.

Interestingly the base image that is currently used [does include `libpdal-dev`](https://github.com/qgis/QGIS/blob/ca130dd49c27aac1aa40b2dcfbc2774a043fa486/.docker/qgis3-qt5-build-deps.dockerfile#L181), as is mentioned in the QGIS build guidelines. To confirm, PDAL itself is installed within the docker file:

`docker run qgis/qgis:release-3_28 pdal --version` ->
```
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
pdal 2.3.0 (git-version: Release)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

**Comment by rbeber** [comment]
Same here.

**Comment by ktiits** [comment]
https://github.com/qgis/QGIS/blob/master/.docker/qgis.dockerfile seems to be missing:

- WITH_PDAL: Determines whether PDAL support should be built
- WITH_COPC: Determines whether Cloud Optimized Point Cloud (COPC) support should be built

**Comment by jsmoreau** [comment]
I think this issue should be closed. I tested QGIS using a docker image last week and I was able to use both laz and copc files.
