### ISSUE TITLE
FileExistsError: [Errno 17] File exists:

### ISSUE THREAD

**Issue by Lily0000000** [qgis/QGIS#50456]
### What is the bug or the crash?

An error occurred while executing Python code：
![Uploading image.p
<img width="317" alt="image" src="https://user-images.githubusercontent.com/111733764/193809389-9bba9439-098c-42ab-b6b6-76486af16253.png">
ng…]()
![Uploading image.png…]()

### Steps to reproduce the issue

After installing the plug-in quickosm, click the plug-in quickosm, and then in the open box, click Quick Query on the left. In the right column, select Boundary, and then enter the city name. After clicking Run Query, the downloaded data will not be displayed and an error will appear.

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Report this to the plugin authors, this is the wrong place.
