### ISSUE TITLE
Wrong GPS satellites count in master

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS#50462]
Previously QGIS reported 9 satellites in use with the folloowing NMEA message, now it reports 0. 
```
$GNRMC,121717.00,A,4806.1881312,N,01706.3552070,E,0.03,249.31,310122,,,D*47
$GNGGA,121717.00,4806.1881312,N,01706.3552070,E,5,09,3.2,153.026,M,43.903,M,1.0,1957*5A
$GPGSA,A,3,12,15,24,,,,,,,,,,5.9,3.2,4.9*33
$GLGSA,A,3,70,71,73,,,,,,,,,,5.9,3.2,4.9*2B
$GAGSA,A,3,03,05,25,,,,,,,,,,5.9,3.2,4.9*22
$GBGSA,A,3,,,,,,,,,,,,,5.9,3.2,4.9*20
$GPGSV,1,1,03,12,42,243,49,15,36,196,37,24,75,298,45,,,,*4A
$GLGSV,1,1,03,70,42,256,39,71,29,320,47,73,17,276,37,,,,*56
$GAGSV,1,1,03,03,39,298,46,05,48,219,40,25,40,256,46,,,,*54
$GNVTG,249.31,T,,M,0.03,N,0.05,K,D*2D
$GNGST,121717.00,4.815,,,,0.022,0.029,0.041*62
$GNZDA,121717.00,31,01,2022,00,00*7A
```

Probably related to changes from #49820.

**Comment by elpaso** [comment]
Is that your cat walking on the keyboard ? :smile_cat:

**Comment by bettellam** [comment]
@alexbruy , @agiudiceandrea  Good evening.
Each GNSS receiver uses its own order for the sequence of messages in NMEA sentences.

The only difference I see in NMEA message sequence compared to my GNSS receiver (U-Blox ZED-F9P) is location of the GxVTG message:
- in my case GxVTG is before GxGSA and GxGSV,
- while in your case GxVTG is after GxGSA and GxGSV

The GxVTG message is used as a "clock" message for resetting the counts for visible satellites and satellites in use !!

Qgis GPS Tools displays the data from the NMEA message, loop on the NMEA sentence.

@alexbruy  Are you using QGis master version 3.28?
Could you please indicate the type of GNSS receiver you use?
Can you attach a slightly longer NMEA log from your receiver?
Thank you

**Comment by bettellam** [comment]
@alexbruy ,ciao @agiudiceandrea  I updated PullRequest #50248
The NMEA GxGGA message is used to reset the count: satellites in use and satellites in view.
My test is positive
![image002](https://user-images.githubusercontent.com/23143342/194371548-70d4af07-0423-4257-89b1-124e95300ad4.jpg)

**Comment by alexbruy** [comment]
@bettellam sorry for the delay. Here is a longer log taken with EMLID RRS-1P receiver. Hope this helps.

**Comment by bettellam** [comment]
@alexbruy  Ok, thanks for information.
I hope the change I made is valid for you too.
I have no idea when the Pull Request #50248 will be approved.
Let me know if it will work for your job.
Ciao

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/50248
