### ISSUE TITLE
Layout Legend changes when the created project in QGIS 3.16 opened in QGIS 3.22

### ISSUE THREAD

**Issue by mhgzadeh** [qgis/QGIS#50467]
### What is the bug or the crash?

I created a project in QGIS 3.16. This project has 10 layers with different symbology. In the layout I chose one of this layers symbology for Legend. Now I have upgradeed my QGIS to 3.22. When I want to open this project in QGIS 3.22, It shows all layers symblogy in legend. The legend in QGIS 3.16 is not same as QGIS 3.22. It automatically activates all layers symbols in legend.

### Steps to reproduce the issue

![1](https://user-images.githubusercontent.com/56732643/194098561-adc82b32-37b4-49da-93d5-bf44fc4e13db.PNG)
The frst image is my layout in QGIS 3.16. I just want to show feature that the age is belong to group A and G.

When I import project in QGIS 3.22.10, all other layers symbol appear in legen. It seems that auto update option is activate automatilly when I import project.  
![2](https://user-images.githubusercontent.com/56732643/194099449-87459c67-bf98-497f-944f-5546ea35ba91.PNG)

### Versions

QGIS 3.16 and QGIS 3.22.10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@mhgzadeh could you provide a sample project with needed layer in order to replicate the issue?
