### ISSUE TITLE
QGIS won't load shapefile layer. Only dragging-in entire folder works

### ISSUE THREAD

**Issue by rodnaskorn** [qgis/QGIS#50469]
### What is the bug or the crash?

I am new to QGIS. 

I followed the installation guide (https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu). My distribution is **Ubuntu 22 jammy**

I am following the training manual (https://docs.qgis.org/2.14/en/docs/training_manual/introduction/preparation.html) along with the exercise_data (https://github.com/qgis/QGIS-Training-Data/archive/QGIS-Training-Data-v1.0.zip) but run into issues on the first exercise.

I try adding a **rivers.shp** using the **new shapefile layer button**. But it doesn't detect any fields, geometries
![Screenshot from 2022-10-05 13-37-39](https://user-images.githubusercontent.com/70451793/194137222-e7055bc6-7b30-4519-9417-ff7d5bd22fd5.png)

The information about the layer appears empty, without any features:
![Screenshot from 2022-10-05 13-39-38](https://user-images.githubusercontent.com/70451793/194137316-b97048f5-8a21-445b-8860-430e0ca56960.png)

I researched the problem online and found this previous issue (https://github.com/qgis/QGIS/issues/37527). I think it is the same problem. 

When I try loading the epsg4326 folder containing the shp files, this works **except for the rivers.shp file** that I previously loaded. **It seems to **"corrupt"** the rivers.shp file and QGIS no longer detects the geometry features**. I have to completely replace the file with a fresh **rivers.shp** from the zip file.  After replacing the files and dragging/dropping the folder I am able to see the shp correctly in QGIS.
![Screenshot from 2022-10-05 13-50-45](https://user-images.githubusercontent.com/70451793/194139016-1da52604-e2ee-48a7-971d-e61557656ed9.png)

When I check the properties, everything looks fine:
![Screenshot from 2022-10-05 14-18-38](https://user-images.githubusercontent.com/70451793/194144121-05f6eeb3-33d0-49ee-845a-8190b2f0ee92.png)

I went ahead to section 3.1.3 of the training manual (https://docs.qgis.org/2.14/en/docs/training_manual/basic_map/vector_data.html) and tried loading **landuse.sqlite** using the **New SpatiaLite Layer button**. Once again the **geometries are not being detected and the file gets corrupted.**
![Screenshot from 2022-10-05 13-58-09](https://user-images.githubusercontent.com/70451793/194140437-f4830f09-1b4a-4bdb-b69b-b68b52cd1485.png)

When I extract a fresh copy of **landuse.sqlite** from the zip file and make a New Connection **directly from the browser pane**. It loads correctly and I am able to add the layer to the project:
![Screenshot from 2022-10-05 14-08-19](https://user-images.githubusercontent.com/70451793/194142326-f732afbc-bf94-4d93-be78-81b5be887c46.png)

Here it works.

![Screenshot from 2022-10-05 14-04-20](https://user-images.githubusercontent.com/70451793/194141582-f4647f2b-6e2b-4661-8e60-797cfa667f3f.png)

For now I think I can find a workaround for loading the shp files but I do think there is a bug with my specific system configuration. The previous issue (https://github.com/qgis/QGIS/issues/37527) was closed but I think it was left unsolved.

Thank you for your efforts creating and maintaining open-source GIS

### Steps to reproduce the issue

1. Click New Shapfile layer button.
2. Select rivers.shp from the training_manual files: epsg4326/rivers.shp
3. No fields are detected. The shp file is imported to the layer completely empty.

### Versions

![Screenshot from 2022-10-05 13-32-55](https://user-images.githubusercontent.com/70451793/194135947-142c8ef5-3bbf-4903-9240-1500ad33ad22.png)

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6
grassprovider
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
Hi @rodnaskorn 
First of all, please follow training manual of your QGIS version instead of a 2.14's. The former might be a bit more up to date than the latter.
Then, instructions ask to load the layer using the "Add vector layer" button, not the "New shapefile" button (or whatever it was called). Using the "New shapefile" button you are creating a layer over the existing one, hence the empty layer. Same logic for sqlite.
Not a QGIS issue
