### ISSUE TITLE
Crash with offline-editing-core-plugin converting to offline project layer with empty polygon

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#50466]
### What is the bug or the crash?

QGIS crashes when exporting project with only one layer with offline-editing-core-pluigin which datasource is a postgresql-materialized view.

(The materialized view dissolves lots of polygons to some outlines). While exporting this project with this layer to a local folder (default styling) QGIS crashes.

If the layer is exported to a local gpkg before export (and the postgresql-connection is removed) QGIS does not crash.

### Steps to reproduce the issue

1) empty project
2) add a postgresql-materialized view (polygon, point ....) as a new layer to this project
3) run offline-editing-core-plugin
4) see QGIS-crash:

_**Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000019c0 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044**_

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.26.3-Buenos Aires | QGIS-Codeversion | 65e4edfdada
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.5.1
PROJ-Version | 9.1.0
EPSG-Registraturdatenbankversion | v10.074 (2022-08-01)
GEOS-Version | 3.10.3-CAPI-1.16.1
SQLite-Version | 3.38.1
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
qfieldsync | v4.1.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS-Version
3.26.3-Buenos Aires
QGIS-Codeversion
[65e4edfdada](https://github.com/qgis/QGIS/commit/65e4edfdada)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.1
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
qfieldsync
v4.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by koenigherford** [comment]
A materialized view is not editable by definition. But it's sometime usefull to add such a layer into a mobile (offline-**editing**) additionally project as a background layer to simplify oritation in the field.

**Comment by koenigherford** [comment]
I did the same steps as described by you some days ago with the nighly build.

Got still a crash (with materialized-view-dataset from postgresql (using PostgreSQL 12.1, compiled by Visual C++ build 1914, 64-bit) too.
When exporting the dataset to a local gpkg before and changing the layer-datasource-connection from postgresql to local gpkg everything works fine
![grafik](https://user-images.githubusercontent.com/28433436/196106951-a8f26987-2961-4360-87df-195da74c62bc.png)


Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000013b0 (most recent call first):



Stack Trace
No stack trace is available.


QGIS Info
QGIS Version: 3.27.0-Master
QGIS code revision: adec434efc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0dev-37e447fc2c
Running against GDAL: 3.6.0dev-592be23900



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.27.0-Master | QGIS code revision | adec434efc
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.6.0dev-37e447fc2c | Running against GDAL/OGR | 3.6.0dev-592be23900
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
Compiled against SQLite | 3.38.1 | Running against SQLite | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.27.0-Master
QGIS code revision
[adec434efc](https://github.com/qgis/QGIS/commit/adec434efc)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.0dev-37e447fc2c
Running against GDAL/OGR
3.6.0dev-592be23900
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
Compiled against SQLite
3.38.1
Running against SQLite
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




This copy of QGIS writes debugging output.




Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by koenigherford** [comment]
Made some additional tests with the dataset. The issue is not related to materialized views but to normal tables too, but I think I could narrow down the reason:

When removing the  'POLYGON EMPTY'-Polygons in PostgreSQL from the materialized view with follwing code, the crash disappears. 

So maybe the issue has to do with the handling of "empty polygons" in export-process of offline-editing-plugin

```
 create table __test_umringe_aller_objekte_incl_vereinf_subtypen_without_empty_polygon (id integer, geom geometry) ;
 
 insert into __test_umringe_aller_objekte_incl_vereinf_subtypen_without_empty_polygon
 SELECT a.id,
    st_geomfromtext(ST_AsText(st_curvetoline(a.geom)),25832) AS geom
FROM mv_umringe_aller_objekte_incl_vereinf_subtypen a
 WHERE NOT st_astext(st_curvetoline(a.geom)) = 'POLYGON EMPTY'::text 
 ;
```
The table **without** last line of code produces a crash, the table **with** last line of code 
(
`WHERE NOT st_astext(st_curvetoline(a.geom)) = 'POLYGON EMPTY'::text` 
)
does not produce a crash.

**Comment by koenigherford** [comment]
By setting up a new table with a empty polygon with
```
create table __test_with_empty_polygon (id integer, geom geometry) ;
 
 insert into __test_with_empty_polygon values
 (1, ST_GeomFromText('POLYGON((-71.1776585052917 42.3902909739571,-71.1776820268866 42.3903701743239,
-71.1776063012595 42.3903825660754,-71.1775826583081 42.3903033653531,-71.1776585052917 42.3902909739571))',4269)),
 (2, ST_GeomFromText('POLYGON EMPTY',4269));

```
**you can not reproduce the issue** - which seems to be very strange as the `"WHERE NOT st_astext(st_curvetoline(a.geom)) = 'POLYGON EMPTY'::text"`-code removed the issue before

**Comment by strk** [comment]
It could be a memory corruption, which typically results in bugs that are triggered or not based on external conditions. Can you provide a dump of the smallest table with which you are able to produce the crash ?
Can you reproduce the crash by simply converting the table from PostgreSQL to GeoPackage via ogr2ogr ?

**Comment by koenigherford** [comment]
same data as before (sql-export-format) additionally in "backup"-export-format. Hope it helps.  

(I always had problems with restoring backup-files with pgadmin III. Maybe you could provide additional information how to make a correct dump so that you can use the data too for test-purposes.

[test503_504_backup.zip](https://github.com/qgis/QGIS/files/9799937/test503_504_backup.zip)

**Comment by koenigherford** [comment]
managed with ogr2ogr a postgis to gpkg-conversion within the local nightly-build-installation-directory with the result 
[test503_504.zip](https://github.com/qgis/QGIS/files/9800306/test503_504.zip)

Offline-editing plugin does not create a crash but warning "Offline Editing Plugin: ERROR: 2 features not added - geometry type is not compatible with the current layer."

**Comment by strk** [comment]
Thanks, I can finally reproduce. QGIS from current 3.26 branch is also affected (final-3_26_3 aka 65e4edfdada4512d81f5171ed7e7f87e70de1344)

**Comment by strk** [comment]
I reproduced on Ubuntu 22.04.1 LTS thus removed the Windows label.

**Comment by strk** [comment]
Here's a fix: https://github.com/qgis/QGIS/pull/50577
