### ISSUE TITLE
Crash window not as verbose as before

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#50472]
### What is the bug or the crash?

This is a « regression » (feel free to remove the tag if not appropriate) introduce between 3.22 and 3.26.

Here is an fresh exemple taken from #50466.

Crash report on 3.26

> Python Stack Trace
> Windows fatal exception: access violation
> 
> Current thread 0x000019c0 (most recent call first):
> 
> Stack Trace
> No stack trace is available.
> 
> QGIS Info
> QGIS Version: 3.26.3-Buenos Aires
> QGIS code revision: https://github.com/qgis/QGIS/commit/65e4edfdada4512d81f5171ed7e7f87e70de1344
> Compiled against Qt: 5.15.3
> Running against Qt: 5.15.3
> Compiled against GDAL: 3.5.1
> Running against GDAL: 3.5.1
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.19044

Crash report on 3.22

> Stack Trace
> QgsPolygon::toCurveType :
> QgsVectorDataProvider::convertToProviderType :
> QgsVectorLayerEditBuffer::commitChanges :
> QgsVectorLayer::commitChanges :
> QgsOfflineEditing::convertToOfflineLayer :
> QgsOfflineEditing::convertToOfflineProject :
> PyInit__core :
> PyArg_ParseTuple_SizeT :
> PyEval_EvalFrameDefault :
> PyFloat_FromDouble :
> PyEval_EvalFrameDefault :
> PyFloat_FromDouble :
> PyEval_EvalFrameDefault :
> PyFunction_Vectorcall :
> PyFloat_FromDouble :
> PyVectorcall_Call :
> PyObject_Call :
> PyInit_QtCore :
> PyInit_QtCore :
> PyInit_QtCore :
> PyInit_QtCore :
> QObject::qt_static_metacall :
> QAbstractButton::clicked :
> QAbstractButton::click :
> QAbstractButton::mouseReleaseEvent :
> QWidget::event :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify :
> QCoreApplication::notifyInternal2 :
> QApplicationPrivate::sendMouseEvent :
> QSizePolicy::QSizePolicy :
> QSizePolicy::QSizePolicy :
> QApplicationPrivate::notify_helper :
> QApplication::notify :
> QgsApplication::notify :
> QCoreApplication::notifyInternal2 :
> QGuiApplicationPrivate::processMouseEvent :
> QWindowSystemInterface::sendWindowSystemEvents :
> QEventDispatcherWin32::processEvents :
> qt_plugin_query_metadata :
> QEventLoop::exec :
> QCoreApplication::exec :
> main :
> BaseThreadInitThunk :
> RtlUserThreadStart :
> 
> QGIS Info
> QGIS Version: 3.22.2-Bia?owie?a
> QGIS code revision: 1601ec46d0
> Compiled against Qt: 5.15.2
> Running against Qt: 5.15.2
> Compiled against GDAL: 3.4.0
> Running against GDAL: 3.4.0
> 
> System Info
> CPU Type: x86_64
> Kernel Type: winnt
> Kernel Version: 10.0.19044

Not sure if it is a bug or intended behavior or a windows only issue.

### Steps to reproduce the issue

1. Find a way to crash QGIS (report the issue of not done already)
2. Compare crash window on 3.22 and 3.26

### Versions

Windows 3.22 and 3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Could have been introduced by https://github.com/qgis/QGIS/pull/46381

**Comment by strk** [comment]
I'd expect availability of stack trace to depend on how QGIS was built,are you sure this is not the difference you are seeing ? (debug vs. non-debug build)

**Comment by nicogodet** [comment]
Even on non-debug build, stack trace was available in previous version.
