### ISSUE TITLE
Problem with "Select feature by value" 

### ISSUE THREAD

**Issue by bidrizi74** [qgis/QGIS#50470]
### Feature description

In QGIS option for selection by value (Select feature by value), in a case when attributes in first characters have same values (for example first attribute is "Bashkim" and second one is "Bashkim Idrizi"), selection options doesn't divide as two attributes. 
If we make selection by using "Select feature by value" with attribute "Bashkim", software will select both features with attributes "Bashkim" and "Bashkim Idrizi", because first part of second attribute is fully equal with first attribute. 
In second case, if we perfomr selection by using "Select feature by value" with attribute "Bashkim Idrizi", software will only features with attributes "Bashkim Idrizi" and will not select features with attribute "Bashkim", which is correct. 

Bellow is one example: 
In attribute table we have two attributes "ВАСИЛ ЈОВАНОВСКИ" and "ВАСИЛ ЈОВАНОВСКИ 1".
In a case of trying to select with first attrbute "ВАСИЛ ЈОВАНОВСКИ", QGIS selects features with both attributes "ВАСИЛ ЈОВАНОВСКИ" and "ВАСИЛ ЈОВАНОВСКИ 1". This happens because first 16 characters between two attributes are same! 
In other case, when the selection criteria is based on second attribute "ВАСИЛ ЈОВАНОВСКИ 1", QGIS selects only features with this attribute "ВАСИЛ ЈОВАНОВСКИ 1". 
![image](https://user-images.githubusercontent.com/79769916/194177494-c4854df5-2946-4af1-a222-c7877dc58cfd.png)

**Comment by nyalldawson** [comment]
Just changing the "Contains" option to "Equals" should get you what you want

**Comment by bidrizi74** [comment]
THanks for quick response. 
In a case of attributes between two tabels with predefined relation, "Equals" sometimes doesn't work! 
Bellow is an example. In a case of using same attribute with "Equals" selection resulted with zero selected features, while by using "Contains" selection resulted with 19 selected features. 
Please check it, and thanks again. 
![image](https://user-images.githubusercontent.com/79769916/194177633-6773d08f-09c9-45f6-9061-6314754bb9f5.png)
![image](https://user-images.githubusercontent.com/79769916/194177726-2f90b5de-e32e-43f7-8114-ae4a51908a5e.png)
![image](https://user-images.githubusercontent.com/79769916/194177805-27306dcd-d6e3-4fd9-a31a-4f33da96d53d.png)

**Comment by bidrizi74** [comment]
Today I checked the same issue, and in a case of relation between two layers same problem is recognized! 
It should be solved for new version.
