### ISSUE TITLE
Bug on Vector and Raster menu

### ISSUE THREAD

**Issue by BeatriceM94** [qgis/QGIS#50478]
### What is the bug or the crash?

When I click on Vector" or "Raster" menu on the top of the panel nothing apppend!
I can't use "cut","Union"... tool because I cannot select none of them!

### Steps to reproduce the issue

CLick on Raster and Vector on the top of the screen and nothing is gonna happend

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you try with a new profile ? (As requested by the form...)

**Comment by agiudiceandrea** [comment]
@BeatriceM94 what is the Operative System you use QGIS on?

**Comment by DelazJ** [comment]
@BeatriceM94 If by "nothing happens" you mean the menus are somehow empty then, you have to enable Processing (in Plugins -> Install and manage plugins".) Those  tools are nothing more than shortcuts to the Processing algorithms

**Comment by BeatriceM94** [comment]
Tank you @DelazJ 
You solve my problem!
