### ISSUE TITLE
Can not set layout page size

### ISSUE THREAD

**Issue by Werafa** [qgis/QGIS#50486]
### What is the bug or the crash?

Can not set A4 page size in Layout/Printer Page Setup.
Can select A4 in 'Page Size' but setting will not save.

Page size is currently set to 'Custom', and provides a 1/4 scale printout

### Steps to reproduce the issue

Create a layout
go to Layout/Printer page setup/Size
Change paper size
Click ok

repeat - setting is not persistent/is not saved

### Versions

QGIS version
3.26.0-Buenos Aires
QGIS code revision
0aece2818e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
dissect_dissolve_overlaps
0.2
ee_plugin
0.0.4
GroupStats
2.2.6
ImageServerConnector
2.1.1
latlontools
3.6.4
planet_explorer
2.2.0
Qgis2threejs
2.7.1
qgis_gee_data_catalog
0.4.2
quick_map_services
0.19.29
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I can save as image or pdf, and then print - but it should be easy to set the print scaling from within QGIS
I've not yet found a way to scale the printed map to anything other than 1/4 A4

**Comment by agiudiceandrea** [comment]
@Werafa, that setting is about your system default printer. You can set the layout page size just right clicking on an empty space in the layout page and select "Page Properties..." https://docs.qgis.org/3.22/en/docs/user_manual/print_composer/overview_composer.html#working-with-the-page-properties.

**Comment by Werafa** [comment]
That is already done, and is already set to A4
Default printer is set to A4
QGIS is set to custom scaling - and this one setting can not be changed.

Saving to PDF or image and then printing to the default printer gives an A4 printout
Printing from within QGIS gives 'custom scaling'

Thanks
Tim

**Comment by agiudiceandrea** [comment]
I cannot replicate the issue on my Windows 10 system using QGIS 3.26.3 or QGIS 3.22.11.
AFAIK, those printer settings are managed by the operative system, not by QGIS.
Anyway, could you please try actually using a "supported QGIS version" (currently 3.26.3 and 3.22.11) and a new QGIS user profile?
