### ISSUE TITLE
PyQGIS QgsPointXY has a __hash__ function, even though it is mutable

### ISSUE THREAD

**Issue by frozar** [qgis/QGIS#50488]
### What is the bug or the crash?

An instance of QgsPointXY is hashable in python but it should not. The justification is exactly the same as in issue #17481. A QgsPointXY is a mutable object has it has the methods `setX` and `setY`. In accordance to the [python documentation](http://docs.python.org/2/glossary.html#term-hashable) :
> An object is hashable if it has a hash value which never changes during its lifetime (it needs a [__hash__()](https://docs.python.org/2/reference/datamodel.html#object.__hash__) method), and can be compared to other objects (it needs an [__eq__()](https://docs.python.org/2/reference/datamodel.html#object.__eq__) or [__cmp__()](https://docs.python.org/2/reference/datamodel.html#object.__cmp__) method). Hashable objects which compare equal must have the same hash value.

To fix this, the `hash()` function of `QgsPointXY` should be deleted:
https://github.com/qgis/QGIS/blob/65bf297d29abe4d76ddfe7dac65e999728778807/src/core/qgspointxy.h#L380-L383

### Steps to reproduce the issue

Python data structures which rely on a unique hash during the lifetime of an object are currently broken which the current implementation of the `QgsPointXY` class.  
I execute the following code in a python interpretor:
```
>>> from qgis.core import QgsPointXY
>>> a = QgsPointXY(1, 2)
>>> b = QgsPointXY(10, 2)
>>> c = set([a, b])
>>> print(c)
{<QgsPointXY: POINT(1 2)>, <QgsPointXY: POINT(10 2)>}
>>> a.setX(10)
>>> print(c)
{<QgsPointXY: POINT(10 2)>, <QgsPointXY: POINT(10 2)>}
>>> print(hash(a))
14
>>> print(hash(b))
14
```

### Versions

Current `master` branch.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
The previous issue https://github.com/qgis/QGIS/issues/17481 reported for the QgsPoint class was allegedly fixed by @m-kuhn with commit https://github.com/qgis/QGIS/commit/44b7767134e442b95b6d99a1cbe612d2aeb856c7, but it seems the issue was not actually fixed so the issue report was reopened. Then the issue "migrated" to the QgsPointXY class as the QgsPoint class was renamed QgsPointXY https://github.com/qgis/QGIS/commit/2bbadbacb714224a4801a8e87fc5123d53f701fd.

**Comment by nyalldawson** [comment]
This can't be changed for 3.x -- it would break plugins

**Comment by frozar** [comment]
I see. Should this issue stays open until it resolution in a future 4.x version? To keep track of this kind of small issue (but with big impact on plugins actually), do you have a `4.0` label?

**Comment by nicogodet** [comment]
@frozar https://github.com/qgis/qgis4.0_api

**Comment by frozar** [comment]
Oh, interesting. Should I open an issue over there or you'll take it into account yourself (or not, depending of your decision)?
