### ISSUE TITLE
Georeferencer - drag and drop doesn't work

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#50517]
### What is the bug or the crash?

Unable to drag and drop any raster file to georeferencer window.

### Steps to reproduce the issue

1. Open the Georeferencer window (Layer =>Georeferencer).
2. Drag any image into the window (nothing happened).

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdada
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
Compiled against PDAL | 2.4.3 | Running against PDAL | 2.4.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.2.0
ContrastHomogenizer | 3.2
fast_field_filler | 1.0
FreehandRasterGeoreferencer | 0.8.3
Go2NextFeature3 | 2.1
latlontools | 3.6.6
loadthemall | 3.3.0
MapsPrinter | 0.9
pluginbuilder3 | 3.2.1
PluginLoadTimes | 3.0.1
plugin_reloader | 0.9.2
profiletool | 4.2.2
qgsAzimuth | 0.9.15
rasterstats | 0.4.3
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdada](https://github.com/qgis/QGIS/commit/65e4edfdada)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
Compiled against PDAL
2.4.3
Running against PDAL
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.2.0
ContrastHomogenizer
3.2
fast_field_filler
1.0
FreehandRasterGeoreferencer
0.8.3
Go2NextFeature3
2.1
latlontools
3.6.6
loadthemall
3.3.0
MapsPrinter
0.9
pluginbuilder3
3.2.1
PluginLoadTimes
3.0.1
plugin_reloader
0.9.2
profiletool
4.2.2
qgsAzimuth
0.9.15
rasterstats
0.4.3
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

![explorer_uqjKy6Mec5](https://user-images.githubusercontent.com/20655102/195252592-981f7c74-c475-4b78-bcb3-3bf2ef81e242.gif)

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/49175
