### ISSUE TITLE
SpatiaLite - Added feature vanishes, attribute dialog does not show required fields

### ISSUE THREAD

**Issue by jechterhoff** [qgis/QGIS#50523]
### What is the bug or the crash?

The primary bug is that a valid feature which is added to a spatialite-based layer - after a sql error has been reported while editing that layer beforehand (adding an invalid feature, i.e. one which does not satisfy all constraints of the database schema) - simply vanishes, without any error message.

The secondary bug/issue is that the attribute dialog, which is opened when editing a spatialite-based layer, does not automatically show required database columns.

Files to reproduce the issue (a database schema and sqlite database created with that schema) are attached in [test3.zip](https://github.com/qgis/QGIS/files/9763423/test3.zip).

### Steps to reproduce the issue

1. Open a new qgis project
1. Connect to testdb3.sqlite database
1. Add table1 as new layer to the project
1. Select layer table1
1. Go into edit mode
1. Draw a polygon and confirm by right-clicking
1. In the dialog that opens, set 'atttext' value to: t1. NOTE: The dialog does not show 'atttext' as required, even though it is marked as NOT NULL in the database schema
1. Save layer edits
1. Leave edit mode (the new feature has been created)
1. Go into edit mode again
1. Draw another polygon and confirm by right-clicking
1. In the dialog that opens, do NOT set any value for 'atttext' - just confirm the dialog by clicking OK
1. Save layer edits -> Log messages appear that inform the user that edits could not be saved due to failed NOT NULL constraint
1. Leave edit mode (discard the changes)
1. Go into edit mode again
1. Draw yet another polygon and confirm by right-clicking
1. In the dialog that opens, set 'atttext' value to: t2
1. Save layer edits -> **the new polygon simply vanishes**
1. Leave edit mode
1. Open the attribute table of layer table1 -> only a single feature exists there

### Versions

QGIS-Version | 3.26.3-Buenos Aires | QGIS-Codeversion | 65e4edfdada
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.5.1
PROJ-Version | 9.1.0
EPSG-Registraturdatenbankversion | v10.074 (2022-08-01)
GEOS-Version | 3.10.3-CAPI-1.16.1
SQLite-Version | 3.38.1
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
@jechterhoff thanks for the ticket, the next time please add separate tickets for separate issues (there seems to be at least two here).

**Comment by elpaso** [comment]
See: https://github.com/qgis/QGIS/issues/50535
