### ISSUE TITLE
modeller - Aggregate functions bug in Field Calculator ?

### ISSUE THREAD

**Issue by simogeo** [qgis/QGIS#50524]
### What is the bug or the crash?

Hi, 

I'm building a model from Graphic Modeller but I'm facing an issue related to _Aggregate_ functions.

From what I have read, I would say it should work, but it does not ...

**The bug (?) is similar to this closed issue : https://github.com/qgis/QGIS/issues/25198**

### Steps to reproduce the issue

To test, please : 

1. download attached Zip file
2. extract data
3. open QGIS and load test-data.geojson file
4. import the model
5. Run the model with 'test-data' as Input

[modeler-agg-bug.zip](https://github.com/qgis/QGIS/files/9764660/modeler-agg-bug.zip)

**Here is the error I get :** 
> Prepare algorithm: native:fieldcalculator_2
> Running Calculatrice de champ total_area [3/3]
> Input Parameters:
> { FIELD_LENGTH: 0, FIELD_NAME: 'total_area', FIELD_PRECISION: 0, FIELD_TYPE: 1, FORMULA: 'aggregate( @Calculatrice_de_champ_lcz_area_OUTPUT , "sum", "lcz_area")', INPUT: 'memory://MultiPolygon?crs=EPSG:2154&field=LCZ_PRIMARY:integer(0,0)&field=lcz_area:double(0,0)&uid={dd646f59-2e51-4940-9d22-c10a7c5a27d8}', OUTPUT: 'TEMPORARY_OUTPUT' }
> Error encountered while running Calculatrice de champ total_area
> Execution failed after 1.01 seconds

I've also tried replacing `aggregate()` call with `sum('lcz_area')` expression with error as well ...

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.4
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
Beeline | 0.2.0
cartogram3 | 3.1.4
nominatim_locator_filter | 0.2.4
DataPlotly | 3.9.1
QuickOSM | 2.1.1
french_locator_filter | 1.0.2
quick_map_services | 0.19.29
SRTM-Downloader | 3.1.17
GeoCoding | 2.18
mask | 1.10.2
Nuclear-Energy-Plant-Radiations- | 1.8
MetaSearch | 0.3.6
sagaprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.15.3
Python version
3.10.4
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
Beeline
0.2.0
cartogram3
3.1.4
nominatim_locator_filter
0.2.4
DataPlotly
3.9.1
QuickOSM
2.1.1
french_locator_filter
1.0.2
quick_map_services
0.19.29
SRTM-Downloader
3.1.17
GeoCoding
2.18
mask
1.10.2
Nuclear-Energy-Plant-Radiations-
1.8
MetaSearch
0.3.6
sagaprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by simogeo** [comment]
well spotted, @nicogodet  ! Thanks !

Still It would be nice to let user know that he needs to use single quotes only for `aggregate` param.

At least, the calculator should display "Expression is invalid" in Preview to let user know something is wrong.

**Comment by nicogodet** [comment]
It displays the error when layer (and feature) is available to evaluate the expression.
In your configuration, input layer does not exist yet so it can't evaluate the expression.

It's shown in examples that it should be single quoted but a reminder in function description would be nice too.

**Comment by simogeo** [comment]
Thanks again for fix and explanation
