### ISSUE TITLE
QGIS 3.27 very slow compared to 3.26 with WFS layer?

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#50528]
### What is the bug or the crash?

Always running self compiled master, I needed a WFS layer to load, but had the feeling that I had to wait a long time ...

Then I saved the project (2 public online layers: WMST and WFS), and opened it in QGIS 3.26: snap and it is loaded

Can others maybe try to reproduce? Or have any idea what is my problem?

(Note the WFS data is all houses of The Netherlands, so be gentle with zooming out)

### Steps to reproduce the issue

This zip contains a qgz project with both layers:
[wfs.zip](https://github.com/qgis/QGIS/files/9766203/wfs.zip)

Unzip it and open the project in:
- current master/3.27
- 3.26

WIth me 3.27 stalls for like 30 sec, 3.26 opens it in 2 seconds

I've used fresh profile folders using: `qgis --profiles-path /tmp/foo` and `faa` for every version...

### Versions

QGIS version | 3.27.0-Master | QGIS code revision | 34227bdf1ce
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.7
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.4
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4

My 3.26 is a little older:

QGIS version | 3.26.1-Buenos Aires | QGIS code revision | e80d5e6fb62
-- | -- | -- | --
Qt version | 5.15.4
Python version | 3.10.5
Compiled against GDAL/OGR | 3.5.1 | Running against GDAL/OGR | 3.5.2
Compiled against PROJ | 9.0.1.%3.%4 | Running against PROJ | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.1 | Running against SQLite | 3.39.4
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@rduivenvoorde No information from the dev/debugging panel? It has a "project load" profiler now.

**Comment by pathmapper** [comment]
@rduivenvoorde while #50650 fixes this issue, maybe inform the server project you`re using that the response for the following request with bbox parameter is very slow: 

https://service.pdok.nl/lv/bag/wfs/v2_0?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=bag:pand&STARTINDEX=0&COUNT=1&SRSNAME=urn:ogc:def:crs:EPSG::28992&BBOX=-100000000,-100000000,100000000,100000000,urn:ogc:def:crs:EPSG::28992

![image](https://user-images.githubusercontent.com/20856381/199778062-d3fe1ee1-3522-4dce-a995-9ee5ed69c7e8.png)

For comparison the same request without bbox parameter:

https://service.pdok.nl/lv/bag/wfs/v2_0?SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=bag:pand&STARTINDEX=0&COUNT=1&SRSNAME=urn:ogc:def:crs:EPSG::28992

![image](https://user-images.githubusercontent.com/20856381/199778729-7825fad6-3d05-439f-87a4-20c0233ca53f.png)

Maybe the performance could be improved somehow, seems like the server is checking all features regarding the bbox despite only one feature (count=1) is requested.
