### ISSUE TITLE
Incorrect Proj4 definition for EPSG:23700 (HD72 / EOV)

### ISSUE THREAD

**Issue by danzig666** [qgis/QGIS#50546]
### What is the bug or the crash?

The PROJ.4 definition for EPSG:23700 (HD72 / EOV) is incorrect.

QGIS EPSG:23700 PROJ.4 is missing +towgs84 values:
`+proj=somerc +lat_0=47.1443937222222 +lon_0=19.0485717777778 +k_0=0.99993 +x_0=650000 +y_0=200000 +ellps=GRS67 +units=m +no_defs`
The correct definition is:
`+proj=somerc +lat_0=47.1443937222222 +lon_0=19.0485717777778 +k_0=0.99993 +x_0=650000 +y_0=200000 +ellps=GRS67 +towgs84=52.17,-71.82,-14.9,0,0,0,0 +units=m +no_defs +type=crs`
[Link to epsg.io](https://epsg.io/23700.proj4)

### Steps to reproduce the issue

Open Project properties/CRS, select EPSG:23700, look at definition

### Versions

3.22.11 and 3.26.3 tested, possibly others

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Epsg.io is not an authoritative site. It contains outdated information.

**Comment by nyalldawson** [comment]
>Epsg.io is right this time though. This definition is incorrect and is causing real issues in production.

Well - no. QGIS gets the proj definition of a CRS **directly** from the proj library, which is the **definitive** source and origin of proj codes! In any case proj strings are a lossy format and aren't recommended for use in high accuracy situations -- you should be using a WKT definition instead. 

> My search results on OpenStreetMap and Google Streetview are off by tens of meters since QGIS changed this.

That's like a different issue, eg. you haven't selected the correct datum transform between wgs84 and EPSG:23700. There's two different ones:

![image](https://user-images.githubusercontent.com/1829991/195738093-80fb3418-c794-46a8-9f8e-8366d2733785.png)
