### ISSUE TITLE
QGIS 3.26 crashing

### ISSUE THREAD

**Issue by ChamathAkalanka94** [qgis/QGIS#50547]
### What is the bug or the crash?

When I’m trying to export a 3d Map using QGIS, the software keeps crashing. I tried different ways as stated in google by reducing the resolution etc, but it didn’t work. This happens only when I’m trying to export 3d maps only for 2d maps it works fine.

In addition, georeferencing didn't succeed 

### Steps to reproduce the issue

Open a new 3d map view

Then print layout with the 3d map

Export it to PDF/ JPEG

QGIS crashes

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Can you attach a sample project and data which demonstrates this issue?

**Comment by uclaros** [comment]
Does it crash or hang indefinitely? This seems like a #50067 duplicate
