### ISSUE TITLE
cant find the main menu bar

### ISSUE THREAD

**Issue by nebulabiu** [qgis/QGIS#50558]
### What is the bug or the crash?

just installed the 3.26 version of QGIS. However, strangely there is no main menu bar to add plugins in the QGIS as well as QGIS-LTR with M1 pro chip and MacOS montererey 12.6. 
Also I've tried to add the plugin toolbars, but there was no change pannel

### Steps to reproduce the issue

Download 3.26
put it into application file
open it 

### Versions

3.26

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@nebulabiu please try using the latest currently supported QGIS version.
