### ISSUE TITLE
r.sim.water parameters

### ISSUE THREAD

**Issue by baharmon** [qgis/QGIS#50568]
### What is the bug or the crash?

The input parameters *infil* and *flow_control* for the GRASS algorithm *r.sim.water* are mandatory in QGIS, but should be optional. The Boolean parameter *time series* should be set to *No* by default. The time series option does not seem to work in QGIS, although I have not tested this extensively yet. 

Documentation: [https://grass.osgeo.org/grass-stable/manuals/r.sim.water.html](https://grass.osgeo.org/grass-stable/manuals/r.sim.water.html)

### Steps to reproduce the issue

1. Run r.sim.water

![r-sim-water-qgis-dialog](https://user-images.githubusercontent.com/10392927/196074678-4218be71-5f6e-44d2-8b1e-2ff17a9977c8.jpg)

### Versions

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DEMto3D
3.4
ee_plugin
0.0.4
LAStools
1.4
mapswipetool_plugin
1.2
mmqgis
2021.9.10
processing_r
3.0.0
qlyrx
0.3.3
QuickOSM
2.1.1
quick_map_services
0.19.26
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
You can try by yourself to make these param optional by editing the description file located in `$INSTALL_DIR/apps/qgis/python/plugins/grassprovider/description`
The 5th param (False in example) make the param optional or not
> QgsProcessingParameterRasterLayer|infil|Name of the runoff infiltration rate raster map [mm/hr]|None|_**False**_

False : Mandatory
True : Optional

**Comment by baharmon** [comment]
I tested the following and it works as expected:
```
r.sim.water
Overland flow hydrologic simulation using path sampling method (SIMWE).
Raster (r.*)
QgsProcessingParameterRasterLayer|elevation|Name of the elevation raster map [m]|None|False
QgsProcessingParameterRasterLayer|dx|Name of the x-derivatives raster map [m/m]|None|False
QgsProcessingParameterRasterLayer|dy|Name of the y-derivatives raster map [m/m]|None|False
QgsProcessingParameterRasterLayer|rain|Name of the rainfall excess rate (rain-infilt) raster map [mm/hr]|None|True
QgsProcessingParameterNumber|rain_value|Rainfall excess rate unique value [mm/hr]|QgsProcessingParameterNumber.Double|50|True|None|None
QgsProcessingParameterRasterLayer|infil|Name of the runoff infiltration rate raster map [mm/hr]|None|True
QgsProcessingParameterNumber|infil_value|Runoff infiltration rate unique value [mm/hr]|QgsProcessingParameterNumber.Double|0.0|True|None|None
QgsProcessingParameterRasterLayer|man|Name of the Mannings n raster map|None|True
QgsProcessingParameterNumber|man_value|Manning's n unique value|QgsProcessingParameterNumber.Double|0.1|True|None|None
QgsProcessingParameterRasterLayer|flow_control|Name of the flow controls raster map (permeability ratio 0-1)|None|True
QgsProcessingParameterFeatureSource|observation|Sampling locations vector points|0|None|True
QgsProcessingParameterNumber|nwalkers|Number of walkers, default is twice the number of cells|QgsProcessingParameterNumber.Integer|None|True|None|None
QgsProcessingParameterNumber|niterations|Time used for iterations [minutes]|QgsProcessingParameterNumber.Integer|10|True|None|None
QgsProcessingParameterNumber|output_step|Time interval for creating output maps [minutes]|QgsProcessingParameterNumber.Integer|2|True|None|None
QgsProcessingParameterNumber|diffusion_coeff|Water diffusion constant|QgsProcessingParameterNumber.Double|0.8|True|None|None
QgsProcessingParameterNumber|hmax|Threshold water depth [m]|QgsProcessingParameterNumber.Double|4.0|True|None|None
QgsProcessingParameterNumber|halpha|Diffusion increase constant|QgsProcessingParameterNumber.Double|4.0|True|None|None
QgsProcessingParameterNumber|hbeta|Weighting factor for water flow velocity vector|QgsProcessingParameterNumber.Double|0.5|True|None|None
QgsProcessingParameterBoolean|-t|Time-series output|False
QgsProcessingParameterRasterDestination|depth|Water depth [m]
QgsProcessingParameterRasterDestination|discharge|Water discharge [m3/s]
QgsProcessingParameterRasterDestination|error|Simulation error [m]
QgsProcessingParameterVectorDestination|walkers_output|Name of the output walkers vector points layer|QgsProcessing.TypeVectorAnyGeometry|None|True
QgsProcessingParameterFileDestination|logfile|Name for sampling points output text file.|Txt files (*.txt)|None|True
```

**Comment by baharmon** [comment]
I will open a separate issue for the time series output.
I would like to check the parameters for other GRASS algorithms.
Should I make an issue for each that need updating? Or a single issue for all of the them?

**Comment by nicogodet** [comment]
> I tested the following and it works as expected:

[...]

> The changes are: L9
> 
> ```
> QgsProcessingParameterRasterLayer|infil|Name of the runoff infiltration rate raster map [mm/hr]|None|True
> ```
> 
> L13
> 
> ```
> QgsProcessingParameterRasterLayer|flow_control|Name of the flow controls raster map (permeability ratio 0-1)|None|True
> ```
> 
> L22
> 
> ```
> QgsProcessingParameterBoolean|-t|Time-series output|False
> ```

You can open a pull request if you want to with this proposed changes.
https://github.com/qgis/QGIS/blob/master/python/plugins/grassprovider/description/r.sim.water.txt

Regarding time series output, it's a bit more complex

> Output walker, water depth and discharge maps can be saved during simulation using the time series flag -t and output_step parameter defining the time step in minutes for writing output files. Files are saved with a suffix representing time since the start of simulation in minutes (e.g. wdepth.05, wdepth.10). Monitoring of water depth at specific points is supported. A vector map with observation points and a path to a logfile must be provided.

**Comment by baharmon** [comment]
@nicogodet I submitted pull request #50637
