### ISSUE TITLE
Dependency problems during installation

### ISSUE THREAD

**Issue by robertocspinto** [qgis/QGIS#50583]
### What is the bug or the crash?

I've been facing a dependency problem when installing QGis in Linux Ubuntu 18.04.6 LTS, GCC gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0 and Python 2.7
Here are log messages:
robertocsp@robertocsp-Aspire-A515-51G:~$ sudo apt install qgis qgis-plugin-grass
[sudo] senha para robertocsp: 
Lendo listas de pacotes... Pronto
Construindo árvore de dependências       
Lendo informação de estado... Pronto
Alguns pacotes não puderam ser instalados. Isto pode significar que
você solicitou uma situação impossível ou, se você está usando a
distribuição instável, que alguns pacotes requeridos não foram
criados ainda ou foram retirados da "Incoming".
A informação a seguir pode ajudar a resolver a situação:

Os pacotes a seguir têm dependências desencontradas:
 qgis : Depende: libgcc-s1 (>= 3.0) mas não é instalável
        Depende: libgdal28 (>= 1.11) mas não é instalável
        Depende: libproj19 (>= 5.0.0) mas não é instalável
        Depende: libqgis-3d3.26.3 mas não será instalado
        Depende: libqgis-analysis3.26.3 mas não será instalado
        Depende: libqgis-app3.26.3 mas não será instalado
        Depende: libqgis-core3.26.3 mas não será instalado
        Depende: libqgis-gui3.26.3 mas não será instalado
        Depende: libqt5core5a (>= 5.15.1) mas 5.9.5+dfsg-0ubuntu2.6 está para ser instalado
        Depende: libqt5network5 (>= 5.15.1) mas 5.9.5+dfsg-0ubuntu2.6 está para ser instalado
        Depende: libqt5webkit5 (>= 5.212.0~alpha3) mas 5.212.0~alpha2-7ubuntu1 está para ser instalado
        Depende: python3-qgis (= 1:3.26.3+16bullseye) mas não será instalado
        Depende: qgis-providers (= 1:3.26.3+16bullseye) mas não será instalado
 qgis-plugin-grass : Depende: qgis-provider-grass (= 1:3.26.3+16bullseye) mas não será instalado
                     Depende: grass785 mas não é instalável
                     Depende: libc6 (>= 2.29) mas 2.27-3ubuntu1.6 está para ser instalado
                     Depende: libgcc-s1 (>= 3.0) mas não é instalável
                     Depende: libgdal28 (>= 1.11) mas não é instalável
                     Depende: libqgis-app3.26.3 mas não será instalado
                     Depende: libqgis-core3.26.3 mas não será instalado
                     Depende: libqgis-gui3.26.3 mas não será instalado
                     Depende: libqgisgrass7-3.26.3 mas não será instalado
                     Depende: libqt5core5a (>= 5.15.1) mas 5.9.5+dfsg-0ubuntu2.6 está para ser instalado
                     Depende: libqt5gui5 (>= 5.11.0~rc1) mas 5.9.5+dfsg-0ubuntu2.6 está para ser instalado ou
                              libqt5gui5-gles (>= 5.11.0~rc1) mas não é instalável
                     Depende: libqt5webkit5 (>= 5.212.0~alpha3) mas 5.212.0~alpha2-7ubuntu1 está para ser instalado
                     Depende: libqt5widgets5 (>= 5.11.0~rc1) mas 5.9.5+dfsg-0ubuntu2.6 está para ser instalado
E: Impossível corrigir problemas, você manteve (hold) pacotes quebrados.
robertocsp@robertocsp-Aspire-A515-51G:~$ 

### Steps to reproduce the issue

sudo apt install gnupg software-properties-common

sudo mkdir -m755 -p /etc/apt/keyrings

sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg

sudo apt update

sudo apt install qgis qgis-plugin-grass

### Versions

Ubuntu 18.04.6 LTS
GCC gcc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0
Python 2.7

robertocsp@robertocsp-Aspire-A515-51G:/usr/bin$ cat /etc/apt/sources.list.d/qgis.sources
Types: deb deb-src
URIs: https://qgis.org/ubuntu
Suites: bullseye
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Ubuntu 18.04 is too old to install QGIS.
See supported distribution here: https://www.qgis.org/en/site/forusers/alldownloads.html#repositories

**Comment by agiudiceandrea** [comment]
@robertocspinto, please read carefully the installation instruction at https://qgis.org/en/site/forusers/alldownloads.html#quickstart:

```
Note
'Suites' in above lines depends on your distribution. lsb_release -cs will show your distribution name.
```

So, if your distribution is Ubuntu 18.04, then the `Suites:` parameter is not `bullseye`, but `bionic`.
