### ISSUE TITLE
VSIZIP Processing tool inputs incorrectly rejected in PyQGIS

### ISSUE THREAD

**Issue by aharfoot** [qgis/QGIS#50588]
### What is the bug or the crash?

I'm trying to run the _gdal:buildvirtualraster_ processing tool through PyQGIS, and when I specify a list of VSIZIP inputs it is rejected with the following error message:

_File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 183, in runAlgorithm
    raise QgsProcessingException(msg)_
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for INPUT_

The same set of VSIZIP inputs will successfully run using the GDAL command line tool, and generate a VRT that successfully loads into QGIS.

I believe that the parsing of the PyQGIS processing call is incorrectly flagging the VSIZIP interface (and presumably other VSI interfaces) as invalid.

### Steps to reproduce the issue

1. Download a couple of SRTM tiles as zipped GeoTIFFs:
 [srtm_36_10.zip](https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_36_10.zip)
 [srtm_36_11.zip](https://srtm.csi.cgiar.org/wp-content/uploads/files/srtm_5x5/TIFF/srtm_36_11.zip)

2. Load the GeoTIFFs directly from the ZIP files (ie without unzipping) into QGIS (using the GDAL VSIZIP interface)
3. Build a VRT using the _Build virtual raster_ tool, choosing the zipped GeoTIFF layers as inputs
4. Use the processing history to extract the Python command for the tool, which will look something like this:
 `processing.run("gdal:buildvirtualraster", {
    'INPUT':['/vsizip/C:/temp/srtm_37_10.zip/srtm_37_10.tif','/vsizip/C:/temp/srtm_37_11.zip/srtm_37_11.tif'],
    'RESOLUTION':0,
    'SEPARATE':False,
    'PROJ_DIFFERENCE':False,
    'ADD_ALPHA':False,
    'ASSIGN_CRS':None,
    'RESAMPLING':0,
    'SRC_NODATA':'',
    'EXTRA':'',
    'OUTPUT':'C:/temp/SRTM.vrt'
})`

5. Paste this into a script in the QGIS Python console and run. An error message will be shown as follows:

```
File "C:\OSGeo4W/apps/qgis-ltr/./python/plugins\processing\core\Processing.py", line 183, in runAlgorithm
    raise QgsProcessingException(msg)
_core.QgsProcessingException: Unable to execute algorithm
Incorrect parameter value for INPUT
```

### Versions

QGIS version
3.22.11-Białowieża
QGIS code revision
[106d33d7](https://github.com/qgis/QGIS/commit/106d33d7)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can reproduce on 3.22.11

Can't reproduce on 3.26.3
```python
>>> processing.run("gdal:buildvirtualraster", {'INPUT':['/vsizip/D:/Downloads/srtm_36_10.zip/srtm_36_10.tif','/vsizip/D:/Downloads/srtm_36_11.zip/srtm_36_11.tif'],'RESOLUTION':0,'SEPARATE':False,'PROJ_DIFFERENCE':False,'ADD_ALPHA':False,'ASSIGN_CRS':None,'RESAMPLING':0,'SRC_NODATA':'','EXTRA':'','OUTPUT':'TEMPORARY_OUTPUT'})
{'OUTPUT': 'C:/Users/godet/AppData/Local/Temp/processing_ZwujHi/217a70c70f624cd19aaeb6a6dc9ad973/OUTPUT.vrt'}
```

**Comment by aharfoot** [comment]
@nicogodet Thanks for testing the LR. Any idea what has changed and whether this is able to be backported to the LTR?

**Comment by nicogodet** [comment]
It seems specific to GDAL alg for now
On 3.22.11
```python
>>> processing.run("native:cellstackpercentile", {'INPUT':['/vsizip/D:/Downloads/srtm_36_10.zip/srtm_36_10.tif','/vsizip/D:/Downloads/srtm_36_11.zip/srtm_36_11.tif'],'METHOD':0,'PERCENTILE':0.25,'IGNORE_NODATA':True,'REFERENCE_LAYER':'/vsizip/D:/Downloads/srtm_36_11.zip/srtm_36_11.tif','OUTPUT_NODATA_VALUE':-9999,'OUTPUT':'TEMPORARY_OUTPUT'})

{'CRS_AUTHID': 'EPSG:4326', 'EXTENT': '-5.0000000000000000,5.0000000000000000 : 0.0000000000000000,10.0000000000000000', 'HEIGHT_IN_PIXELS': 6000, 'OUTPUT': 'C:/Users/godet/AppData/Local/Temp/processing_AnidBx/667ed89f5bee4aedb23bed7aecbde10e/OUTPUT.tif', 'TOTAL_PIXEL_COUNT': 36000000, 'WIDTH_IN_PIXELS': 6000}
```

**Comment by nicogodet** [comment]
1. Open a fresh QGIS 3.22.11
2. Try to run `processing.run("native:cellstackpercentile", {'INPUT':['/vsizip/D:/Downloads/srtm_36_10.zip/srtm_36_10.tif','/vsizip/D:/Downloads/srtm_36_11.zip/srtm_36_11.tif'],'METHOD':0,'PERCENTILE':0.25,'IGNORE_NODATA':True,'REFERENCE_LAYER':'/vsizip/D:/Downloads/srtm_36_11.zip/srtm_36_11.tif','OUTPUT_NODATA_VALUE':-9999,'OUTPUT':'TEMPORARY_OUTPUT'})`
3. Fail
4. Load both layers in QGIS
5. Retry the command
6. Success

**Comment by nicogodet** [comment]
@aharfoot is it still a valid issue ?
Please test on 3.34.8 or 3.38

**Comment by aharfoot** [comment]
@nicogodet I've just tested on 3.34.8 and can't reproduce the error any more.
