### ISSUE TITLE
qgis_srs: try to use pcs.csv and gcs.csv removed since GDAL 2.5

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS#50599]
### What is the bug or the crash?

`scripts/qgis_srs.sh ` try to use [pcs.csv](https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/scripts/qgis_srs.sh#L197-L216) and [gcs.csv](https://github.com/qgis/QGIS/blob/2d1aa68f0d044f2aced7ebeca8d2fa6b754ac970/scripts/qgis_srs.sh#L221-L237). But these files are removed from GDAL since v2.5.

Shall we fix this script/remove these lines?

ping @rouault @jef-n 

### Steps to reproduce the issue

run scripts/qgis_srs.sh

### Versions

all versions

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rouault** [comment]
I doubt this script is used at all those days. It should probably just be removed, as well as resources/README
You rather want to use the crssync utility
