### ISSUE TITLE
Every run of qgis from build dir results in a new directory created and never removed in TMPDIR ( qgis-python-crash-info-#### )

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#50609]
### What is the bug or the crash?

Whenever you run qgis from the build dir a qgis-python-crash-info-XXX directory is created in the TMPDIR and 

### Steps to reproduce the issue

output/bin/qgis

### Versions

current master at time of writing ( e8dcb8998829f518252d506df3afbe140a9707fe )

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
This file is is probably generated by https://github.com/qgis/QGIS/blob/18cafd8b3e24d8cbca08ccc7b2ef91fb6df26bd5/src/python/qgspythonutilsimpl.cpp#L221-L229
