### ISSUE TITLE
GeoPDF export shifted line geometry duplications when simplify geom is turned off, or ISO32000 format is selected

### ISSUE THREAD

**Issue by gregorwebdev** [qgis/QGIS#50600]
### What is the bug or the crash?

I tried to find a good setting for a GeoPDF export for later FME usage, and that's why i run into this issue.
I noticed in FME that there are shifted line duplications with ISO32000 format, and/or with no geometry simplification in GeoPDF files exported by QGIS. 
If i choose OGC best practice format with simplification, there are only single lines with color.
Probably, somewhy the simplified geometry also exported with this setting. But the not simplied geomtry has no style atttributes.
The problem, that it's not possible to create a spatially precise, not redundant export. 
Left picture is good but not precise. Right side picture is the bug.
![bug](https://user-images.githubusercontent.com/89207969/196642916-a0207659-ef7a-4318-a0b9-61743a151b0d.JPG)

### Steps to reproduce the issue

Load some line data into a project (wgs84 not sure this is needed)).
Open Project menu - Import/Export submenu, open Export Map to PDF.
Export a GeoPDF with recommened format.
or/and
Export a GeoPDF with no geometry simplification.
Open with Safe FME Data Inspector.
Zoom in.

### Versions

QGIS version
3.22.11-Białowieża
QGIS code revision
106d33d7
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.3-CAPI-1.16.1
Compiled against SQLite
3.38.1
Running against SQLite
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
mmqgis
2021.9.10
qgis-maptiler-plugin
2.0.0
Qgis2threejs
2.7.1
QuickOSM
2.0.0
quick_map_services
0.19.26
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
MapsPrinter
0.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Still valid?
