### ISSUE TITLE
Processing output as shapefile is missing CPG

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#50603]
### What is the bug or the crash?

~~Model~~ Processing output as shapefile is missing CPG and PRJ.

### Steps to reproduce the issue

1. Run model [test.zip](https://github.com/qgis/QGIS/files/9819717/test.zip) with shapefile output
![image](https://user-images.githubusercontent.com/20856381/196670059-3c3ae66a-8e5e-4504-84d7-c4d1bab851c5.png)
2. See error: -> no CPG file is created:
![image](https://user-images.githubusercontent.com/20856381/196670386-c7c566b3-094e-488c-95a8-aa70f7ba2122.png)

### Versions

QGIS version | 3.27.0-Master | QGIS code revision | e8dcb89988
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Not related to modeller, `native:deletecolumn` does not create this file

**Comment by nicogodet** [comment]
I tried 4 different algs, none of them creates .cpg

**Comment by pathmapper** [comment]
PRJ is also missing.

**Comment by nicogodet** [comment]
This is odd.

I manage to create .prj 6 time over 9 try without knowing how. 
I change encoding param, .cpg was created but not .prj. 
Close and reopen model, none of them is created.

**Comment by pathmapper** [comment]
@nicogodet are you also on `master`?

**Comment by nicogodet** [comment]
@pathmapper 3.26.3

**Comment by FERRATON** [comment]
I also notice that the cpg file is missing from the output of the algorithms in shp format when writing to disk.
This causes a problem because when opening the file, the encoding is interpreted as windows1252 instead of UTF-8.
QGIS 3.28.4

**Comment by lbartoletti** [comment]
Cannot reproduce with QGIS 3.26.1 (GDAL 3.5.1) on windows and QGIS 3.30.0 (GDAL 3.6.4) on FreeBSD.

@FERRATON what is your version of GDAL? @FERRATON @pathmapper Can you try with the latest update?

**Comment by nicogodet** [comment]
Just tried with 3.30.2 (GDAL 3.6.4) and can't reproduce

**Comment by FERRATON** [comment]
Test completed with QGIS 3.30.2 gdal 3.6.4
problem still present

**Comment by pathmapper** [comment]
The issue is still reproducible with `master` (https://github.com/qgis/QGIS/commit/74849dad8d7cccc68a0158e092fcc09ab4bf7170) on Ubuntu.

Did several test runs, CPG was missing all the time, PRJ was created for one run and otherwise missing as well.

**Comment by nicogodet** [comment]
@pathmapper Can you confirm that if you change encoding (ex: to UTF-8) in drop down menu in processing window, .cpg is created ?
![image](https://github.com/qgis/QGIS/assets/39594821/1fa69eca-2fd1-4262-bafd-6cc3984d36c2)


.prj is always created here, could be link to GDAL version...

**Comment by FERRATON** [comment]
Yes the cpg file is created (QGIS 3.28 and 3.30) if you change the output encoding of the files with this option.
This option is stored in QGIS3.ini
[processing]
...
encoding=UTF-8

A bit strange to have to change this option which is a processing setting at this place of the interface !

**Comment by pathmapper** [comment]
@nicogodet confirmed the CPG is created when changing encoding from System -> UTF-8.

However, the PRJ is still missing.

> A bit strange to have to change this option which is a processing setting at this place of the interface !

I would second that :smiley:

**Comment by lbartoletti** [comment]
> Il would leave it open as the creation of .cpg is a bit strange

What would you expect here? Update the documentation accordingly is the best answer imho. Since the .cpg is only required for shapefile and so in the "output encoding" parts, non?

**Comment by pathmapper** [comment]
> What would you expect here?

Maybe that a .cpg is also created for `encoding = System` by default using the system encoding? So a user doesn't have to discover this kind of hidden setting...

**Comment by lbartoletti** [comment]
> > What would you expect here?
> 
> Maybe that a .cpg is also created for `encoding = System` by default using the system encoding? So a user doesn't have to discover this kind of hidden setting...

OK, I've made a proposal in https://github.com/qgis/QGIS/pull/53518

I'm uncertain if it's a good idea or the good fix, but it works

cc @nicogodet for your advice and tests if possible
