### ISSUE TITLE
Failed to load a raster clipped by mask layer in a 3d map view

### ISSUE THREAD

**Issue by DiegoUasPilot** [qgis/QGIS#50611]
### What is the bug or the crash?

After clipping an [ALOS PALSAR ](https://www.asf.alaska.edu/sar-data-sets/alos-palsar/) DEM using a poligon shapefile, we tried to load it in a 3d map view as the terrain. Then the 3D map went frozed and grayed. We had to terminate Qgis using Task manager

this is the Report Detail produced by the "QGIS unexpectedly endend" window:

## User Feedback

After clipping an [ALOS PALSAR ](https://www.asf.alaska.edu/sar-data-sets/alos-palsar/) DEM using a poligon shapefile, we tried to load it in a 3d map view as the terrain. Then the 3D map went frozed and grayed. We had to terminate Qgis using Task manager

## Report Details

**Crash ID**: [a4d6d8802247f30b5b18483159c7ec01851f6f95](https://github.com/qgis/QGIS/search?q=a4d6d8802247f30b5b18483159c7ec01851f6f95&type=Issues)

**Stack Trace**
<pre>
QgsPointCloudLayer3DRenderer::writeXml :
QgsPointCloudLayer3DRenderer::writeXml :
QgsTerrainDownloader::tileImageToHeightMap :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
Qgs3DMapCanvasDockWidget::configure :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.11-Bia?owie?a
QGIS code revision: 106d33d7
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

1. in a 3D map window, select from the menu Options, Configure
2. In Terrain, set Type to DEM (raster layer)
3. Select the DEM clipped we create using Raster/ Extraction/ Clip Raster by Mask Layer in a previos process
4. 3D map window an Qgis went frozed and grayed
![image](https://user-images.githubusercontent.com/116244086/196854878-6a8f651e-2be6-4c9d-a99e-d4f5dd54e51e.png)

### Versions

3.22.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you try with a new profile ?
If you can, could you try on Master too (nightly build) ?

And provide a sample project.
