### ISSUE TITLE
qgis_process temporary files are not cleaned up

### ISSUE THREAD

**Issue by florisvdh** [qgis/QGIS#50623]
### What is the bug or the crash?

On each call to `qgis_process`, two new files are created in the user's temporary directory, but they are not removed afterwards:

- an empty file `QGIS3.xxxxxx`
- a file in a subdirectory: `QGIS3-yyyyyy/zzzzzz_styles.db`. This is a SQLite database with 14 tables having 0 rows.

The xxx/yyy/zzz strings seem random.

With several tested algorithms, these files all appear to remain empty / with 0 rows. If this is always the case, then perhaps the files shouldn't be there?

When checking the R package qgisprocess, this behaviour yields a note about remaining detritus (https://github.com/paleolimbot/qgisprocess/issues/62).

### Steps to reproduce the issue

In a Linux shell:

```bash
$ find /tmp -type f \( -name "QGIS*" -o -name "*_styles.db" \)
$ 
$ qgis_process &> /dev/null
$ 
$ find /tmp -type f \( -name "QGIS*" -o -name "*_styles.db" \)
/tmp/QGIS3-UJyKwM/KHMJUP_styles.db
/tmp/QGIS3.BHULds
$ 
$ qgis_process &> /dev/null
$ 
$ find /tmp -type f \( -name "QGIS*" -o -name "*_styles.db" \)
/tmp/QGIS3-UJyKwM/KHMJUP_styles.db
/tmp/QGIS3.BHULds
/tmp/QGIS3.YBTuhF
/tmp/QGIS3-Ovuiht/hHUlfq_styles.db
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.4.3
PROJ version | 8.2.0
EPSG Registry database version | v10.038 (2021-10-21)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.31.1
PDAL version | 2.2.0
PostgreSQL client version | 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Linux Mint 20
  |   |   |  
Active Python plugins
geopunt4Qgis | 2.2.4
ViewshedAnalysis | 1.7
cartography_tools | 1.2.1
quick_map_services | 0.19.27
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
otbprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by florisvdh** [comment]
I haven't checked yet with current development version, but the released 3.28.2 appears to segfault with `native:printlayouttopdf`. Observed in the shell in Linux Mint 21.1 at least, but same problem appears to exist in Windows as well when checked from R (https://github.com/paleolimbot/qgisprocess/pull/118#issuecomment-1371305999).

**Comment by nicogodet** [comment]
@florisvdh Could you open a new issue with sample data and step to reproduce ?

**Comment by florisvdh** [comment]
Continued in related issue https://github.com/qgis/QGIS/issues/51474.
