### ISSUE TITLE
Trace Tool Glitch - Creating vertex outside of map bounds in a random location which I have no selected instead of creating traced polygon/line

### ISSUE THREAD

**Issue by lauren9796** [qgis/QGIS#50622]
## User Feedback

Trace tool is glitching and placing a point in a random location off the map bounds where I have not clicked. e.g Im creating a small polygon in the Sydney area and when i click to trace around a second polygon in a different layer a point which will form my boundary line, a vertex is instead created in the centre of antarctica (not an exaggeration) and no tracing occurs. 

I caused this error but it had nothing to do with the tracing error. Error was caused when digitised segment was selected and i clicked it again to turn it off since I thought this might be the reason for the above error. 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005f9c (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. Using the "add polygon feature" tool, make first selection for location of the first vertex for a polygon
2. Enable snapping and "trace" tool 
3. Attempt to trace around surrounding edge of polygon by creating a vertex along the bounds of said polygon (which is in another layer)
4. Error occurs where vertex is created in a random location south of where point was meant to be created (e.g. map bounds are in sydney and vertex randomly created in antarctica) 
5. Unable to undo vertex creation and therefore continue so must restart and trace tool is unusable, work is lost.

### Versions

QGIS version
3.10.6-A Coruña
QGIS code revision
ec80021f49
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.0.4
Running against GDAL/OGR
3.0.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
quick_map_services; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Do you use same CRS for both layer and project ?

**Comment by lauren9796** [comment]
Your right !! I wasnt using the Project CRS, stupid mistake on my part.thank you !!
