### ISSUE TITLE
3.22.11 and 3.26 Keep freezing/stalling after few tasks. 

### ISSUE THREAD

**Issue by ArieSpun** [qgis/QGIS#50628]
### What is the bug or the crash?

I install a VPN access for the job, then TEAMS and a other version of Office. It shouldn't be related, but since then, all the version of Qgis I have tried (I did desinstall and reinstall it many times), the program is still freezing/stalling after few task EACH time I use it. It doesn't crash tho, but it make my work longer and unefficient. I desinstall all extensions, same problem. Any idea where to tart to fix that issue? That would be sooo appreciated! 

### Steps to reproduce the issue

I don't see the error. It's just freezing... 

### Versions

Version de QGIS
3.22.11-Białowieża
Révision du code
106d33d7
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.1
Version de Proj
9.1.0
Version de la base de données du registre EPSG
v10.074 (2022-08-01)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.38.1
Version de PDAL
2.4.3
Version du client PostgreSQL
14.3
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
MultiDistanceBuffer
3.2.4
qfieldsync
v4.2.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Are you accessing file through the VPN? Or are you using local data.

**Comment by ArieSpun** [comment]
I am using my local data.

**Comment by agiudiceandrea** [comment]
@ArieSpun, could you please try if the issue occurs also using a new QGIS profile?

**Comment by ArieSpun** [comment]
Oh! Would you mind to explain me how to create a new profile?

**Comment by ArieSpun** [comment]
Oki! Seems like we reinstall WASHLANE VPN access and now QGIS is working
just fine. the IT that reconfigure my VPN access has no idea why or the
link with that QGIS issue, but now, all is good!
