### ISSUE TITLE
How to carry out this process with multi-layers? "mergevectorlayers" 

### ISSUE THREAD

**Issue by castrofd** [qgis/QGIS#50648]
### What is the issue about the documentation?

I'm trying to perform a function to execute the "native:mergevectorlayers" process, but the Layer Input doesn't accept a list type variable. How to carry out this process with multi-layers?
![image](https://user-images.githubusercontent.com/80858378/197240863-49260f5f-dc0c-46dc-b8c6-ce240352f8db.png)

**Comment by agiudiceandrea** [comment]
@castrofd, it the list_paths argument is a list of paths, then the LAYERS parameter should be list_paths, not [list_paths] (which is a list of a list).

**Comment by roya0045** [comment]
I don't think this is an issue with qgis...

**Comment by castrofd** [comment]
Hello guys, I made the change but I believe that the "native:mergevectorlayers" process does not accept a list as a parameter.

Thanks.
