### ISSUE TITLE
Watershed Delineation - Using SAGA NextGen plugin

### ISSUE THREAD

**Issue by NaniNagendra22** [qgis/QGIS#50643]
### What is the bug or the crash?

From the suggestions of Nicolas Godet, member of QGIS (https://github.com/qgis/QGIS/issues/50621#issuecomment-1285465535) on the issue "Watershed delineation Error #50621", I tried "Processing SAGA NextGen provider" as suggested by Nicolas Godet. Still we are getting the same error note as shown in uploaded image. Kindly advise how to proceed or resolve the bug.
![Screenshot Upslope Area - Error](https://user-images.githubusercontent.com/116272460/197125494-c27660a8-db7e-4242-a9fd-2ed15022aefd.jpg)

### Steps to reproduce the issue

![Screenshot Upslope Area - Error](https://user-images.githubusercontent.com/116272460/197125952-937cf071-5a8f-4d8e-b83a-fc156d9ff3e9.jpg)

### Versions

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
HCMGIS
22.9.9
processing_saga_nextgen
0.0.7
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Should be reported on plugin repo https://github.com/north-road/qgis-processing-saga-nextgen/issues

**Comment by nicogodet** [comment]
In fact, issue is already known https://github.com/north-road/qgis-processing-saga-nextgen/issues/16

**Comment by NaniNagendra22** [comment]
Ok. Thanks for the quick response. Kindly advise how to proceed to run the tool successfully.

**Comment by nicogodet** [comment]
Could you read answers on https://github.com/north-road/qgis-processing-saga-nextgen/issues/16 ?
