### ISSUE TITLE
Report Pictures dynamic filepath can't handle Expressions or Attributes

### ISSUE THREAD

**Issue by TehemGo** [qgis/QGIS#50649]
### What is the bug or the crash?

I'm creating a report.
In this report, I want a Picture to be inserted dynamically, according to [the documentation](https://docs.qgis.org/testing/en/docs/user_manual/print_composer/create_reports.html#including-pictures-in-a-report). I'm trying to set its filepath to an Attribute.

When I set the picture path manually, with the path of one of the Features' picture, the picture shows.
![manual path](https://user-images.githubusercontent.com/69685886/197267961-a6c55b25-7eeb-4663-b902-5f5e336a5d4b.png)

The Picture filename is in one of the Layer's Attributes.
![attribute values](https://user-images.githubusercontent.com/69685886/197264697-2ae6a788-35d5-4b24-85f6-fc01fc88fb9a.png)
It is the exact same as the picture filename that just worked when set manually (I copied and pasted it, no mistake possible)

I now try to set the picture path through the Expression builder, using a real simple concatenation of the absolute path as a String, and the Layer String Attribute for the filename.
![expression](https://user-images.githubusercontent.com/69685886/197264744-8d21976a-218e-460a-b9e4-508812564001.png)
Notice how the filepath folder uses the '/' delimiter and not '\\', as it worked in the manually set path (and is customary for French users, as shown in nicogodet's answer for [bug 49252](https://github.com/qgis/QGIS/issues/49252)).

The Image type immediately switches to SVG to be able to show the red cross associated with errors.
![SVG cross](https://user-images.githubusercontent.com/69685886/197264918-01889080-f311-4969-8fbd-b4a2089c7da0.png)

The actual error is shown through one of the Export Report buttons : "Picture source is missing or corrupt" "The source for picture “<Picture>” could not be loaded or is corrupt:".
![error](https://user-images.githubusercontent.com/69685886/197266028-579c1c79-c948-460b-980c-b31ebde2b0dc.png)

What hints at a bug is : 
- the fact that the error doesn't show any filepath or filename or such, but <Picture>
- [bug 49252](https://github.com/qgis/QGIS/issues/49252) that was closed by reinstalling QGIS
- it's awfully similar to [bug 43485](https://github.com/qgis/QGIS/issues/43485) and [bug 43589](https://github.com/qgis/QGIS/issues/43589) that were set as duplicates of [bug 42280](https://github.com/qgis/QGIS/issues/42280), except as far as I know, the filepath is the right one (as validated when set manually and copying-pasting)
- it also looks like it's the same as in [a stackexchange thread](https://gis.stackexchange.com/questions/414805/feature-linked-image-in-report-layout-qgis) for an earlier version, that was solved by a workaround I can't use (I need a Report and not an Atlas) although I tried some of the tricks listed, to no avail.

I also tried to put the complete filepath into its own Attribute and refer to it through the Attribute Field in the Data Defined  Override -- same behaviour.

### Steps to reproduce the issue

as explained in the detail
1 create a report with Features with a Field Group Section
2 insert a picture
3 set the picture filepath through the Data defined override (Expression or Attribute) referring to Attributes of the Layer set in the Field Group Section definition

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.1-Tisler | QGIS code revision | 5709b824
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
BezierEditing | version 1.3.3
profiletool | 4.2.2
quick_map_services | 0.19.29
ViewshedAnalysis | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99
PointConnector | 2.0

</body></html>QGIS version
3.24.1-Tisler
QGIS code revision
[5709b824](https://github.com/qgis/QGIS/commit/5709b824)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
BezierEditing
version 1.3.3
profiletool
4.2.2
quick_map_services
0.19.29
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
PointConnector
2.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
All quoted issues are fixed.
You are using an old version. 3.24 is EOL.
Retry when 3.28 will be available next week.

**Comment by troopa81** [comment]
It looks like related to issues which were fixed with #50277. The fix is only in 3.28 and 3.22 not 3.24. Could you give it a try with either one of this 2 versions and report if you still have the issue?
