### ISSUE TITLE
Core Plugin "Processing" is Missing

### ISSUE THREAD

**Issue by GHRKU** [qgis/QGIS#50661]
### What is the bug or the crash?

Just installed QGIS 3.22.11 and I am unable to find the core "processing" plugin in the plugin manager.

When I open the plugin manager I see only the following:

![2022-10-22_Bug Report_Missing Processing Plugin_2](https://user-images.githubusercontent.com/95153843/197368345-17cc9b80-9aaa-4c9f-a28f-eb511465bf29.JPG)

### Steps to reproduce the issue

1. Go to 'Plugins'
2. Click on 'Manage and install plugins'

### Versions

QGIS version | 3.22.11-Białowieża | QGIS code revision | 106d33d7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 7 Version 6.1 (Build 7601: SP 1)
  |   |   |  

</body></html>QGIS version
3.22.11-Białowieża
QGIS code revision
[106d33d7](https://github.com/qgis/QGIS/commit/106d33d7)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 7 Version 6.1 (Build 7601: SP 1)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have reviewed all the documentation and bug reports I could find. Sorry if I missed something. Any assistance would be much appreciated.

**Comment by DelazJ** [comment]
> Windows 7 Version 6.1 (Build 7601: SP 1)

Your issue might reside there. Windows 7 is no longer supported because of its lower version of Python (the best you can directly get, without tricks, is QGIS 3.18 if I'm correct). It's stated in the download page.
> QGIS requires Windows 8 64 bit or higher because QGIS uses Python 3.9 or later, which is not available for Windows 7.

**Comment by nicogodet** [comment]
If you have no choice, use network installer, it offers a workaround 
See https://github.com/qgis/QGIS/issues/50163#issuecomment-1242480067

**Comment by GHRKU** [comment]
Installed QGIS 3.18.3 (QGIS-OSGeo4W-3.18.3-1-Setup-x86_64.exe) without difficulty and it appears to have resolved the issue. Many thanks!

**Comment by nicogodet** [comment]
Note that you won't get any support with this version installed.
3.18 is EOL (as Win7)
