### ISSUE TITLE
`netcdf` files not properly imported

### ISSUE THREAD

**Issue by leomiquelutti** [qgis/QGIS#50660]
### What is the bug or the crash?

QGIS does not properly imports the `netcdf` files.

[Here](https://www.unidata.ucar.edu/software/netcdf/examples/files.html) are several `netcdf` example files that are not correctly imported in QGIS. The only one that gets "close" to a right importing is this [sea surface temperatures file](https://www.unidata.ucar.edu/software/netcdf/examples/tos_O1_2001-2002.nc).

I am trying to export a `xarray.Dataset` object to netcdf with the `to_netcdf` method in Python. The same `xarray`, when exported to `geotiff` with the `to_raster` method from `rioxarray` works fine (image inside the smaller yellow rectangle - the correct place). The gray image in the map below shows the result of importing the `netcdf` file generated with this [Google Colab notebook](https://colab.research.google.com/drive/1T0UWeKP2Ydt7lh77nJ0DNUSsoecPtbh8?usp=sharing).

![image](https://user-images.githubusercontent.com/9113903/197360951-da81e701-f9d4-4026-bbba-426e2bdd98e1.png)

### Steps to reproduce the issue

To reproduce this error, you can:
1. get any `netcdf` file from [this website](https://www.unidata.ucar.edu/software/netcdf/examples/files.html)
2. get the `netcdf` file generated in this [Google Colab notebook](https://colab.research.google.com/drive/1T0UWeKP2Ydt7lh77nJ0DNUSsoecPtbh8?usp=sharing).

Then you open QGIS and add the chosen `netcdf` file:
1. Click on the tab _Layer_
2. Scroll down to _Add Layer_
3. Click on _Add Raster Layer_
4. Choose your `netcdf` (usually `.nc` extension) and add it to the map

### Versions

3.26.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I also opened an [issue](https://github.com/pydata/xarray/issues/7195) at the `xarray` GitHub Issues.

**Comment by rouault** [comment]
Solution at https://gis.stackexchange.com/a/442392

**Comment by leomiquelutti** [comment]
It didn't work for me.

**Comment by leomiquelutti** [comment]
That didn't work for me 😥

**Comment by leomiquelutti** [comment]
> Solution at https://gis.stackexchange.com/a/442392

That didn't work for me 😥
