### ISSUE TITLE
Feature Attributes form should have a way to highlight feature on map

### ISSUE THREAD

**Issue by nlssjritakallio** [qgis/QGIS#50671]
### Feature description

When creating new features on a vector layer it is possible (and sometimes justifiable) to digitize multiple features on a row and leave the "Feature attributes" forms open on all of them. Once the user is done digitizing and want's to save new features and possibly edit their attributes, the user has multiple "Feature Attributes" forms open and it is impossible to know for sure which form belongs to which map feature.

Feature Attributes form should have a way to highlight the feature in question on the map canvas. This would be especially useful for the forms that open automatically after digitizing a new feature. 

![current_attribute_form](https://user-images.githubusercontent.com/101117929/197483399-6095af22-288a-4f8a-94e2-4a8d7a49e08c.PNG)

Could this problem be solved by adding "Flash feature" and/or "Zoom to feature" button(s) to Attributes Form?

![improved_attribute_form](https://user-images.githubusercontent.com/101117929/197486517-3ed18005-f3eb-454c-b814-e91dda535300.PNG)

### Additional context

For example the "Select Features" form currently has similar functionality and buttons:

![select_features_form](https://user-images.githubusercontent.com/101117929/197487959-a761de5e-7cf8-4aed-9141-8bd60158d642.PNG)

You can also find the same functionality in the Attribute Table of a vector layer: when right clicking a row the context menu has these same options.

Our biggest use case for this "multi digitizing" process is when user digitizes features in a separate stereo mapping application (produces only geometry) that communicates with QGIS through a plugin. Plugin adds digitized features to correct QGIS vector layers and attribute forms are opened automatically for each feature so that it's attributes can be modified. This process leads to a situation where user has many attributes forms open and no way to know which is the corresponding map feature.

**Comment by antoniolocandro** [comment]
It would be less disruptive if by selecting the appropriate form QGIS automatically added a highlight to the selected feature like a flash or some other form instead of manually needing to do that, it would certainly be one less click for the operator which could be a lot of time saved if they are already doing this type of digitizing is due to having several features

**Comment by Joonalai** [comment]
I agree, the flashing of the feature whenever the focus changes back to the attribute window is less disruptive than extra buttons. This would definitely make digitizing multiple features easier and faster.
