### ISSUE TITLE
$x and $y formulas don't work

### ISSUE THREAD

**Issue by Beschito** [qgis/QGIS#50673]
### What is the bug or the crash?

When you try to capture the coordinates of a geometry with field calculator the $x and $y formulas produce only a NULL value as result.

### Steps to reproduce the issue

-Open field calculator from a vector table. Create a new field (real, lenght: 10, precision: 5).
-write the formula: $x
-click ok
-nothing is written in the new field 

### Versions

3.22.12-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Share a sample project please.

**Comment by agiudiceandrea** [comment]
@Beschito please see https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#x:

> 12.2.13.117. $x
> Returns the x coordinate of the current point feature.

and https://docs.qgis.org/3.22/en/docs/user_manual/expressions/functions_list.html#id33:

> 12.2.13.118. x
> Returns the x coordinate of a point geometry, or the x coordinate of the centroid for a non-point geometry.

If your layer contains non point geometry and you want to calculate the x coordinate of the centroid of such geometry, then you need to use the `x` function and not the `$x` one.

**Comment by Beschito** [comment]
@agiudiceandrea @roya0045 oh yes sorry! I forgot about that. 
Thank you for your help you can close the ticket.
