### ISSUE TITLE
DBManager SQL Window auto-completes MixedCase table/column names of  PostgreSQL tables but does not quote them

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#50685]
### What is the bug or the crash?

DBManager SQL window auto-completes identifiers of postgresql objects but doesn't double-quote them so any identifier containing uppercase variables need manual intervention to fix.

### Steps to reproduce the issue

Create a table with a capitalized letter in the name (ie: MixedCase), open DBManager, open SQL Window, type 'SELECT * FROM M' wait for the popup giving you a list of things starting with M, pick MixedCase from the list, see result being unquoted. 

### Versions

3.22.11-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Duplicates #28986.
