### ISSUE TITLE
GPS Live Tracker works in 3.28 but not in 3.22

### ISSUE THREAD

**Issue by jackbeagley** [qgis/QGIS#50699]
### What is the bug or the crash?

Connecting to the same `gpsd` server, QGIS 3.28 reports a green "good fix" and displays the location correctly and QGIS-LTR reports a red "bad fix", not displaying the location. Despite this, all of the GPS metadata (latitude, longitude, satellites, etc) is identical in each instance. I have tried QGIS 3.28 and QGIS-LTR 3.22 on my Macbook Pro M1 Pro and QGIS-LTR 3.22 on a Windows 10 machine. `gpsd` is running on a Raspberry Pi

### Steps to reproduce the issue

Enter in the ip address and port of the `gpsd` instance and check GPS status

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.0
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.7
RenameField | 0.1
qgis2web | 3.16.0
Serval | 3.10.5
linz-data-importer | 2.2.3
datetimetools | 3.0.7
valuetool | 3.0.15
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f](https://github.com/qgis/QGIS/commit/ed3ad0430f)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.8-Białowieża | QGIS code revision | 2c33bc4c29
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 13.0
  |   |   |  
Active Python plugins
numericalDigitize | 0.4.7
RenameField | 0.1
qgis2web | 3.16.0
Serval | 3.10.5
linz-data-importer | 2.2.3
datetimetools | 3.0.7
valuetool | 3.0.15
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.8-Białowieża
QGIS code revision
[2c33bc4c29](https://github.com/qgis/QGIS/commit/2c33bc4c29)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 13.0

Active Python plugins
numericalDigitize
0.4.7
RenameField
0.1
qgis2web
3.16.0
Serval
3.10.5
linz-data-importer
2.2.3
datetimetools
3.0.7
valuetool
3.0.15
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.0

Active Python plugins
numericalDigitize
0.4.7
RenameField
0.1
qgis2web
3.16.0
Serval
3.10.5
linz-data-importer
2.2.3
datetimetools
3.0.7
valuetool
3.0.15
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

3.28 is the first version where GPS tracking *has* worked for me.

**Comment by nicogodet** [comment]
Try with latest LTR 3.22.12

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/48483
