### ISSUE TITLE
Process gdal_merge.bat failed to start

### ISSUE THREAD

**Issue by bluewave-aqua** [qgis/QGIS#50697]
### What is the bug or the crash?

When raster>miscellaneous>merge is called, tiffs from local directory selected, and run, I get the following error:

GDAL command:
gdal_merge.bat -ot Float32 -of GTiff -o C:/Users/bluewave/AppData/Local/Temp/processing_RvWLVF/c4de5132247247b9b80baf786b7ccf77/OUTPUT.tif --optfile C:/Users/bluewave/AppData/Local/Temp/processing_RvWLVF/7a971cde8ab6403c969d90a358e7d975/mergeInputFiles.txt
GDAL command output:
Process gdal_merge.bat failed to start. Either gdal_merge.bat is missing, or you may have insufficient permissions to run the program.
Execution failed after 0.42 seconds

I have installed QGIS at R:\OSGEO4W. 

Using a command window, if I go to R:\OSGeo4W\apps\Python39\Scripts and paste the GDAL command, it fails with "The system cannot find the path specified." 

If I set the path in the command window:
set osgeo4w_root=r:\osgeo4w 
and then paste the GDAL command, it executes correctly and successfully.
I can see the osgeo4w_root path listed correctly in the "current environment variables" under QGIS>options (so not sure why my command window doesn't know about it, but I don't understand the scope of these things) 

This same behaviour occurs with a direct install of QGIS (not via osgeo4w), and also occurs if the installers are run as administrator, or QGIS is executed as administrator. Continues after repeated uninstalls / reinstalls, installing in different location and on different drives (and with tiffs in different locations).

**...HOWEVER - creating a new profile fixes the issue.** (I scrolled down to the check box requesting this!). So this is a workaround, but a nuisance for anyone not wanting to run more than the default profile, so I will still report.

### Steps to reproduce the issue

raster>miscellaneous>merge
select two or more tiffs from local directory
run

### Versions

QGIS version | 3.22.11-Białowieża | QGIS code revision | 106d33d7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.5.1 | Running against GDAL/OGR | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
Compiled against SQLite | 3.38.1 | Running against SQLite | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
ImportPhotos | 3.0.3
shapetools | 3.4.5
ViewshedAnalysis | 1.8
vrtbuilderplugin | 0.9.20210222T174536.master
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.11-Białowieża
QGIS code revision
[106d33d7](https://github.com/qgis/QGIS/commit/106d33d7)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
Compiled against SQLite
3.38.1
Running against SQLite
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ImportPhotos
3.0.3
shapetools
3.4.5
ViewshedAnalysis
1.8
vrtbuilderplugin
0.9.20210222T174536.master
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> HOWEVER - creating a new profile fixes the issue. (I scrolled down to the check box requesting this!). So this is a workaround, but a nuisance for anyone not wanting to run more than the default profile, so I will still report.

It is not about wanting to run a second profile. If it works in a new profile (which is like restarting QGIS from zero on a new machine), it means that the bug is certainly not in QGIS default settings but is due to a change that happened in your other profile. Desinstalling/reinstalling on the same machine still relies on the active profile so if the bug is in the profile, it will continue to pop up.
You can also try to run after uninstalling third-party plugins. They can also create troubles.

**Comment by nicogodet** [comment]
So not a QGIS issue.
Closing
