### ISSUE TITLE
can't select a vector table in QgsProcessingParameterVectorLayer processing parameter widget

### ISSUE THREAD

**Issue by janzandr** [qgis/QGIS#50707]
### What is the bug or the crash?

It is not possible to select a vector table (i.e. a vector layer that has no geometry) in a **QgsProcessingParameterVectorLayer** processing parameter widget.

### Steps to reproduce the issue

1. Create/open a vector table (e.g. by creating a new scratch layer)
![image](https://user-images.githubusercontent.com/45030715/198048760-ce45ce1c-099e-47ef-bf40-65ff03bcb7cd.png)

2. Open any processing algorithm that includes a QgsProcessingParameterVectorLayer processing parameter. E.g.
![image](https://user-images.githubusercontent.com/45030715/198049224-ed46bbac-46bf-4f42-9ade-91624061f4d7.png)

3. See error: vector table can't be selected.

### Versions

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
BivariateRenderer
1.0.0
ee_plugin
0.0.4
enmapboxplugin
3.12-alpha.1
force4qgis
1.0.1
geetimeseriesexplorer
2.0
magnetic_bearing_measurement
0.5
mesma
1.0.8
nominatim_locator_filter
0.2.4
qgis-maptiler-plugin
3.0.3
rasterdataplotting
1.7
rastertimeseriesmanager
1.8
timeseriesviewerplugin
1.17.20210312T143004.master
vrtbuilderplugin
0.9.20210222T174536.master
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
This is not a bug, these algorithms are working only on layers with geometry.

**Comment by janzandr** [comment]
Thanks @alexbruy, it works fine if I pass _[QgsProcessing.SourceType.TypeVector]_ as **types** argument to _QgsProcessingParameterVectorLayer_.

BTW - I was wondering, if algorithms like QGIS _Random Selection_ should also do it that way? Selecting random features from a table would also make sense, right?
