### ISSUE TITLE
DXF Export transfers no Text labels

### ISSUE THREAD

**Issue by JeltoBuurman** [qgis/QGIS#50716]
### What is the bug or the crash?

No texts in DXF export

### Steps to reproduce the issue

1. Insert a line with a text attribute, i.e. Your name
2. define a label with the attribute, that you see your name
3.  goto file "File" Export to dxf and Export it
4. there is no name in the dxf

### Versions

3.22.11
3.27.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by JeltoBuurman** [comment]
I found a past, that the export of label works, only if you define the textsize in Mapunits. I tried, and this works with 3.22.l2

**Comment by alexbruy** [comment]
@JeltoBuurman can be closed then?
