### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by King546123** [qgis/QGIS#50725]
### What is the bug or the crash?

When Selecting Coverage layer in generate an atlas, QGIS ended unexpectedly
It happening every time while selecting
Try to fix it.

## User Feedback

When Selecting Coverage layer in generate an atlas, QGIS ended unexpectedly
It happening every time while selecting
Try to fix it.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002f14 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

## User Feedback

When Selecting Coverage layer in generate an atlas, QGIS ended unexpectedly
It happening every time while selecting
Try to fix it.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002f14 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.24.1-Tisler
QGIS code revision: 5709b824
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Versions

3.24 version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.24 is EOL
Retry with a currently supported version (3.22.12 or 3.28.0)
