### ISSUE TITLE
HTML Widget in Attribute form adding '/n'

### ISSUE THREAD

**Issue by matjash** [qgis/QGIS#50727]
### What is the bug or the crash?

HTML Widget in Attributes form displaying /n for every line.

Same symbology, how it looks in 3.22.12:
![slika](https://user-images.githubusercontent.com/32578708/198523418-7507e83a-5796-43b1-bca6-1c773d90cc21.png)

and how it looks like until 3.22.9:
![slika](https://user-images.githubusercontent.com/32578708/198523726-67bdef22-097d-4d96-80c3-b1cd1c6b4752.png)

### Steps to reproduce the issue

1. Go to layer properties
2. Attributes form
3. Configure HTML widget

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Različica programa | 3.22.12-Białowieża | Kodna različica | b8534cb1
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2004
  |   |   |  
Active Python plugins
agis | 1.4.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Različica programa
3.22.12-Białowieża
Kodna različica
[b8534cb1](https://github.com/qgis/QGIS/commit/b8534cb1)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2004

Active Python plugins
agis
1.4.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
The issue may be related to the PR https://github.com/qgis/QGIS/pull/49876 (backported to 3.22.12 with https://github.com/qgis/QGIS/pull/49890 - https://github.com/qgis/QGIS/pull/50165).
