### ISSUE TITLE
Not possible to create single part shapefile

### ISSUE THREAD

**Issue by Beschito** [qgis/QGIS#50720]
### What is the bug or the crash?

When you create a new shapefile is not possible to set if the geometry must be polygon or multipolygon. Only the option polygon is selectable but actually the geometry created is multipolygon.
Even if you try to use 'from multi-part to single-part' algorithm and you save the result as shapefile you will obtain a multipolygon.

The algorithm goes well because i checked the geometry type of the result. The problem is in the creation of the shapefile or when you try to save a vector as shapefile.

It is very important to have the possibility to choose wath kind of geometry create especially if you have to load them in to a Data-Base to udpate an existing table.

### Steps to reproduce the issue

You can see this problem in two ways:

1- Create a new shapefile. In the cascade menù of geometry type the options of the previous versions of QGIS disappeared. For the polygon type you cannot choose if single-part or multi-part. Selecting polygon you will obtaion only a Multipolygon.

2- Create a temporary layer and select polygon as geometry type. Check the geometry type in properties info and you will see Polygon (Polygon). Then export the virtual layer as shapefile and check its geomtry type in properties. You will read Polygon (Multipolygon).
![nuovo shapefile](https://user-images.githubusercontent.com/49171940/198307697-b6398749-d75b-484a-8977-5771304f0434.PNG)
![propietà](https://user-images.githubusercontent.com/49171940/198308211-d0dae4e2-fc03-463d-9983-9113f051e46c.PNG)

### Versions

3.22.12-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is because the shapefile format does not differentiate between polygon and multipolygon.
If you need to force singleparts in your dataset then you should probably use a newer format like a geopackage.

**Comment by nicogodet** [comment]
@uclaros closing as not a real issue ?

**Comment by Beschito** [comment]
Sorry but that are you saying is not correct. In the same Project i have one shapefile marked as single part and another one created today marked with multi polygon. This problem happened after the upgrade from 3.22.11 to 3.22.12. In the office i have one computer with the previous version and it's possibile to distinguish the two kinds of geometry during the creation of a shapefile. I have no problems on postregs tables with shapefile with single part geometry but i have problems with theese shapefile created with the newest version of QGIS when i try spatial SQL queries, so that means that shapefile can distinguish between the two kinds of geometry and this affects the postgres tables.

**Comment by uclaros** [comment]
Well, you can check the spec if you want or https://en.wikipedia.org/wiki/Shapefile

Maybe your one shapefile *has* some multipolygons in it while the other has only *singleparts*

**Comment by Beschito** [comment]
Thank you for the answer. The shapefile i created today is not complicate it is maden by 4 polygons drawed without multiparts. Tomorrow i will do some tests with different qgis versions and will show you the result. Please wait to close this ticket 😉

**Comment by Beschito** [comment]
Hello, I did some tests but i can't no more reproduce the results i obtained months ago. 
Now i want to explain wath i have to do. I have to load a shapefile into postgres, appending the new informations to an already existing table. I use this command to load the shp.:

shp2pgsql -a -I -S -i -s 32632 [path-to-shp] [tablename] | psql -U postgres -d [dbname] -h localhost -p 5432

After the load i have to create a grid on the new geometries but with all the new geometries added i'm not able to make the query working and i'm obtaining this error:

ERROR: ERRORE:  invalid memory alloc request size 1085997440

I think that this error is generated  by the presence of a multi-part geometry. 

The wierd thing is that all the geometries added in the past months don't have this problem and return the right result.

Today i tried to load on the DB one shp with only one polygon:
 
![today geometry](https://user-images.githubusercontent.com/49171940/198561988-21f53258-996f-4f9a-beb5-2d754ab5065b.PNG)

How you can see there are not multipolygons here. I can load the geometry with shp2pgsql (note that -S parameter Generates simple geometries instead of MULTI geometries) but i can't make working the spatial query i have to run. 
So in the same table the query works for the geometries i added with the same method months ago but for this new polygon it doesn't work.
The same problem occurs if try to load the geometry in a new empty table with the DB manager selecting the option 'Do not transform in multi-parts'.

So this is the weird problem that is blocking my work. For that i thought that the problem consists in the fact of that QGIS shapefile do not more distinguish between polygon and multipolygon during the export. I seem to remember that in the previous versions this was a property of the shapefiles. I know that shp cannot store topology and that arcgis shapefile do not have differences between single parts and multi-part. But i'm not explaining to myself wath is going wrong.

maybe the problem stands in the new version of postgres.

**Comment by agiudiceandrea** [comment]
I think this issue report can be closed as there is no evidence the original report is an actual QGIS issue.

@Beschito, ss written in previous comments, the line (PolyLine) and polygon (Polygon) ESRI Shapefile layer types are actually multi-part layer types which can store multi-part geometries with only one part or with more than one part (https://www.esri.com/Library/Whitepapers/Pdfs/Shapefile.pdf/). Only the point layer type has two different ESRI Shapefile layer types: the ESRI Shapefile Point type (which is a single-part type) and the ESRI Shapefile MultiPoint type (which is a multi-part type).
Please reopen this issue report if you really think the originally reported issue is a QGIS issue or file another issue report in the correct repository (QGIS / Postgres) with detailed instructions and sample layers to replicate the issue.

**Comment by Beschito** [comment]
Ok thank you @agiudiceandrea.
