### ISSUE TITLE
QR Barcode Layout Item plugin

### ISSUE THREAD

**Issue by Milopezc16** [qgis/QGIS#50733]
### What is the bug or the crash?

I´m using the QR Barcode Layout Item plugin in a print composer, i´m configuring an attribute value from a layer to build the link, in the box "insert Expresion for barcode data " 
the expresion call the correct value but when i select ok the expression pass like a text [%"DOCUMENTO"%]

### Steps to reproduce the issue

I´m using the QR Barcode Layout Item plugin in a print composer, i´m configuring an attribute value from a layer to build the link, in the box "insert Expresion for barcode data " 
the expresion call the correct value but when i select ok the expression pass like a text [%"DOCUMENTO"%]

### Versions

3.16 y 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
This is not a QGIS issue but plugin's. Please report to the [author](https://github.com/gkahiu/qrbarcodeitem-plugin/issues)
