### ISSUE TITLE
No help found

### ISSUE THREAD

**Issue by rutson** [qgis/QGIS#50751]
### What is the bug or the crash?

Tried to get 'Help'

Default browser opened with title: 'No help found'

`
Oops!
QGIS help is currently not available. This is likely because:

No internet connection is available
The offline help files are not available or the location of these files is not properly configured
No help content is available for the requested topic
Please check that the correct location of the offline help files is specified in the QGIS options dialog (Settings → Options →System).`

### Steps to reproduce the issue

Install QGIS
Cick 'Help' menu then 'Help Contents'

### Versions

https://github.com/qgis/QGIS/commit/ed3ad0430f

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rutson** [comment]
To be clear, a new profile *did* fix the issue, but the problem persists in my default profile

**Comment by DelazJ** [comment]
@rutson QGIS in English or another language?

**Comment by kannes** [comment]
Any proxy configured?

**Comment by DelazJ** [comment]
Issue confirmed with 3.28 in French but not in English. This is due to translated versions not being available for 3.28 docs yet and they fail to redirect to English.
@rduivenvoorde ?

**Comment by DelazJ** [comment]
@rutson Is this issue till occurring?

**Comment by rutson** [comment]
@DelazJ - English

Yes, still have the issue, end result the same but an extra tab in the meantime.

Opens this URL in default browser:
https://docs.qgis.org/3.28/en/docs/user_manual/index.html
Hangs for several seconds, then shows the attached image.

Then another tab with:
file:///Applications/QGIS.app/Contents/Resources/doc/nohelp.html

<img width="1011" alt="image" src="https://user-images.githubusercontent.com/14196062/199935414-266a3b37-2f9e-4a64-be10-17fd8652e14b.png">

**Comment by DelazJ** [comment]
Hummm... the whole qgis.org seems (docs, website, pyqgis) down currently, or takes too much time to open. After many attempts, I could open your url
![image](https://user-images.githubusercontent.com/7983394/199945722-a8e9aa07-15d2-42f1-b79f-cc77c48f7bc0.png)

**Comment by agiudiceandrea** [comment]
It seems to me there is no issue now. Is the issue fixed also for you, @rutson? If yes, please close this issue report.
