### ISSUE TITLE
Command panel and command status bar percentage done don't always match

### ISSUE THREAD

**Issue by MatthewHerbst** [qgis/QGIS#50769]
### What is the bug or the crash?

There seems to be lag between the percentage displayed in the command panel and the percentage displayed in the command status bar. See the screenshot for an example:

![Screen Shot 2022-11-02 at 2 54 17 PM](https://user-images.githubusercontent.com/1287375/199610285-bce5ee3a-cc74-4d36-b6c5-1556bd747263.png)

### Steps to reproduce the issue

I see this when running a long-lived "Generate XYZ Tiles (MBTiles)" raster command

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.6
  |   |   |  
Active Python plugins
QuickOSM | 2.1.1
vector_tiles_reader | 3.2.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
@MatthewHerbst is this still an issue with the latest dev version?

**Comment by MatthewHerbst** [comment]
> @MatthewHerbst is this still an issue with the latest dev version?

Hey. I'm not sure, I haven't used the new version yet and don't have plans to in the near future. Should be pretty easy to repo if it's not though, just start some long-running tile cutting job.
