### ISSUE TITLE
QGIS 3.28RC -  SAGA and GRASS missing from processing panel. 

### ISSUE THREAD

**Issue by Spartacus1** [qgis/QGIS#50768]
### What is the bug or the crash?

The GRASS and SAGA modules do not appear in the current 3.28 RC version for macOS. They appear just fine in 3.22 LTR and 3.26 (although have a few issues in this version). 

### Steps to reproduce the issue

Go to panel "processing"  -  GRASS and SAGA are absent and are also absent if search for any particular SAGA or Grass module. 

### Versions

3.28 RC under macOS. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Spartacus1 , it seems to me this is very likely an issue related to the macOS distribution of QGIS and not to QGIS itself, so I think it could be better to file the issue report to the QGIS macOS repository https://github.com/qgis/QGIS-Mac-Packager and then close this. Do you agree?

**Comment by Spartacus1** [comment]
Done. Thanks Andrea.

**Comment by agiudiceandrea** [comment]
https://github.com/qgis/QGIS-Mac-Packager/issues/158
