### ISSUE TITLE
Inaccurate error message in expression builder

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#50761]
### What is the bug or the crash?

Instead of "end of file" which looks quite confusing, I'd expect "end of input"

![image](https://user-images.githubusercontent.com/7983394/199422294-abfbc6aa-22b8-4212-969f-79b7873d3fa4.png)

### Steps to reproduce the issue

see above

### Versions

e907edf640

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by NathanW2** [comment]
Agree @DelazJ this is a bit confusing for users.

@nyalldawson @wonder-sk I was going to tackle this one but was wondering if the best option might just be a string replace inside `parserErrorString()` and replace the string with something nicer.     I had a look but couldn't see the best way to handle it in the parser files.  Maybe inside `parseExpression` but would be the same thing in the end

e.g just replace `syntax error, unexpected end of file` with something more user friendly

**Comment by wonder-sk** [comment]
@NathanW2 if we wanted to handle it in the parser file (.yy), we could use `%define parser.error custom` and provide our own syntax error reporting function - see https://www.gnu.org/software/bison/manual/html_node/Syntax-Error-Reporting-Function.html  (looks like one needs Bison >= 3.6 released back in 2020 for this, which should not be a problem)

Replacing the current syntax error message could also work, but probably it is more fragile in case the default bison error changes (could be handled by a simple auto test though).
