### ISSUE TITLE
Remaning rubberband and plot data after clearing 

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#50766]
### What is the bug or the crash?

![Animation](https://user-images.githubusercontent.com/39594821/199547664-fbef302e-480c-4f8f-8fd5-b814b2d3e1ff.gif)

### Steps to reproduce the issue

See above

### Versions

3.28.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Jakob-Lanstorp** [comment]
I have experienced this a few times, and can not find a way to reproduce it. A profile stays as a rubberband when creating a new profile, closing a project wont fix it, you need to reboot QGIS. It seems to come when you are having multiple profile windows open. Some how the link between the profile and the profile line in the map gets lost.

**Comment by nicogodet** [comment]
This issue is partialy fixed in 3.38.3.

The snap on elevation canvas remains after clearing.
