### ISSUE TITLE
Incorrect MSVC Version in INSTALL.md

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#50767]
### What is the bug or the crash?

QGIS now requires C++17 or higher, and the INSTALL.md document (for compiling under Windows) still says to use MSVC 2015.
Following the directions will not compile QGIS.

Compiler errors include:
`D9002: ignoring unknown option '/std:c++17'`
`C2433: 'inline' not permitted on data declarations`

### Steps to reproduce the issue

1. Attempt to compile QGIS with MSVC 2015
2. Errors galore

### Versions

*Whenever QGIS started to require C++17*

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Seems already fixed, INSTALL.md mentions MSVC 2019
