### ISSUE TITLE
Keep freezing/stalling after few tasks any version tested 3.22.11, 3.22.12, 3.26 and 3.28

### ISSUE THREAD

**Issue by ArieSpun** [qgis/QGIS#50773]
### What is the bug or the crash?

Qgis is freezing after few tasks, mainly when saving or using some tool in the program. It seems it started after installing WASHGUARD vpn, but even after desinstalling it, it still freezing. 

It's almost impossible to work with QGIS since that issue arise... Your ideas and help would be gladly appreciated. 

### Steps to reproduce the issue

When opening project, saving layers or projets, using differents tools. Pretty consistent. 

### Versions

Version de QGIS
3.28.0-Firenze
Révision du code
ed3ad0430f3
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.5.2
Version de Proj
9.1.0
Version de la base de données du registre EPSG
v10.074 (2022-08-01)
Version de GEOS
3.10.3-CAPI-1.16.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
DDG_Street_Images
1.0.3
GpxSegmentImporter
2.5
MultiDistanceBuffer
3.2.4
Multi_Ring_Buffer
1.1
qfieldsync
v4.2.0
quick_map_services
0.19.32
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Install and desinstall many times, different version 3.22.11; 3.22.12, 3.26 and 3.28. Issue is still happening.

**Comment by alexbruy** [comment]
@ArieSpun can you provide reliable way to reproduce this? Otherwise I'm afraid, it should be closed.

**Comment by ArieSpun** [comment]
We finally founf out that a VPN installed by my job causes all the
inteferences with QGIS. I think it’s a valuable information to share…

Thanks for the follow up !

Le jeu. 2 nov. 2023 à 10:09, Alexander Bruy ***@***.***> a
écrit :

**Comment by alexbruy** [comment]
Have you tested with the latest versions? Am I right that you are accessing projects/data via VPN? Does it happen with local projects/data?

**Comment by ArieSpun** [comment]
No, I have not tested the latest version since I reported that issue. The
VPN have been desinstalled since then. It was affecting the local project
since some data are online based ex: WYZ and WMS layers, as far as I
understand.

Le jeu. 2 nov. 2023 à 13:15, Alexander Bruy ***@***.***> a
écrit :
