### ISSUE TITLE
crashing when I use Python Threading and QTextEdit widget

### ISSUE THREAD

**Issue by win895564** [qgis/QGIS#50774]
### What is the bug or the crash?

I create a QGIS Plugins
When I use threading and QtextEdit in definition
The program will crash but not using print I don't know why

it's my button connect code
"""
self.t = threading.Thread(target = self.DoorPlateRegex)
self.t2 = threading.Thread(target = self.CustomerRegex)
self.t.start()
self.t2.start()
"""

"""
self.dlg.textEdit.setText(str(dt.datetime.now()) + " export successful !" + "\n" + str(self.dlg.textEdit.toPlainText()))
"""

### Steps to reproduce the issue

https://user-images.githubusercontent.com/90327297/199635926-6afe6c62-5875-4c96-aec3-acee9a11ed88.mp4

### Versions

QGIS version
3.22.9-Białowieża
QGIS code revision
a8e9e6fa
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AutoLayoutTool
1.1
DataPlotly
3.9.2
door_plate_match
0.1
map_canvas
0.1
openlayers_plugin
2.0.0
pgRoutingLayer
3.0.1
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
qgis_auto_features
0.1
qgis_caculate_road
0.1
qgis_ftth_manage
0.1
qgis_ftth_support
0.1
qgs_selection
0.1
qgs_set_id
0.1
QNEAT3
1.0.4
save_attributes
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
It's beneficial to do some learning on the qt framework before developing qgis plugins. In this case it's an absolute requirement that all GUI interaction is done in the main thread.

**Comment by win895564** [comment]
Because I use pandas to process my csv file
And the data of one of the dataframes must be calculated based on the data of the previous dataframe

**Comment by nyalldawson** [comment]
@win895564 

you should use Qt's signal and slot mechanisms to pass messages from background threads back to the main threads, and ensure all gui related code resides ONLY in the main thread. That's the only safe way to do this.

**Comment by win895564** [comment]
@nyalldawson
ok so i get it, thx

**Comment by win895564** [comment]
@nyalldawson 
But when I use Qlabel threading works fine
What is the reason

**Comment by win895564** [comment]
I think I found the cause of the problem
Just because I used "\n" in the string
If alone textEdit.setText("\n")
also cause the program to crash

**Comment by nyalldawson** [comment]
Have a read of https://doc.qt.io/qt-5/thread-basics.html

Basically: trust me on this. I've over a decade experience in using the qt library on a daily basis. Accessing GUI from non main thread is an absolute DO NOT DO UNDER ANY CIRCUMSTANCES! 👍

**Comment by AsimAziz** [comment]
I'm doing all the GUI stuff in the main thread using signals, but still, when I perform more than 5 to 10 actions in a single run of the plugin, the QGIS crashed suddenly.
