### ISSUE TITLE
QGIS Debian/Ubuntu packages don't reflect current release

### ISSUE THREAD

**Issue by LoonSongSoftware** [qgis/QGIS#50783]
### What is the bug or the crash?

After following the instructions provided [here](https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu), I only see v3.26 as the "current" release for Ubuntu 'focal.'

It looks like the repository files were last update on Sept. 11, 2022.  So...is there a problem with the automatic package builder?  Or did I miss some documentation that Ubuntu LTS installations will only receive QGIS LTS packages (or some such)?

### Steps to reproduce the issue

On a Ubuntu 20.04 (focal) machine, follow the QGIS package install directions for Linux (link cited above).  The version that will be installed is 3.26.3, 

Alternatively, surf around the repository directories at https://ubuntu.qgis.org/ubuntu/dists and note the file dates for the various Ubuntu distributions.  Look at the 'Packages' file--the highest package version number seems to be 3.26.3.

### Versions

Headless server.  Here's the output from /usr/bin/qgis_mapserver -v

QGIS 3.26.3-Buenos Aires 'Buenos Aires' (65e4edfdad)
QGIS code revision 65e4edfdad
Qt version 5.12.8
Python version 3.8.10
GDAL/OGR version 3.0.4
PROJ version 6.3.1
EPSG Registry database version v9.8.6 (2020-01-22)
Compiled against GEOS 3.8.0-CAPI-1.13.1
Running against GEOS 3.8.0-CAPI-1.13.1
SQLite version 3.31.1
OS Ubuntu 20.04.5 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by LoonSongSoftware** [comment]
Should be labeled with "Build/Install," but I can't figure out how to do that...

**Comment by nicogodet** [comment]
https://qgis.org/en/site/forusers/alldownloads.html#id13
