### ISSUE TITLE
QGIS crashes when i try to create a new field in the attribute table

### ISSUE THREAD

**Issue by amesq19** [qgis/QGIS#50792]
### What is the bug or the crash?

QGIS crashes when i try to create a new field in the attribute table. I'm trying to copy a existing field that it's configured as text to a new field configured as number.

Crash ID: [a5e71cb067f89f07adba087fdafc92631a15f8ba](https://github.com/qgis/QGIS/search?q=a5e71cb067f89f07adba087fdafc92631a15f8ba&type=Issues)

Stack Trace

QgsAttributeTableModel::prefetchSortData :
QgsAttributeTableFilterModel::setAttributeTableConfig :
QgsDualView::hideEvent :
QObject::qt_static_metacall :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsFieldCalculator::accept :
QObject::qt_static_metacall :
QDialogButtonBox::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgsAttributeTableDialog::mActionOpenFieldCalculator_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

### Steps to reproduce the issue

1. Edit attribute table
2. Open the field calculator
3. Create a new field
4. Open Field and Values
5. Select the field to copy 
6. OK

### Versions

3.22.9-Bia?owie?a

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by roya0045** [comment]
And is that for every layer or only this one?

**Comment by gioman** [comment]
@amesq19 please try with a new QGIS profile.
