### ISSUE TITLE
Shapefile not working 

### ISSUE THREAD

**Issue by IGEM009** [qgis/QGIS#50796]
### What is the bug or the crash?

I Create shapefile in point format and given point are not Visible in my study area. please do something ASAP 

Things and regards

![2022-09-27](https://user-images.githubusercontent.com/117503792/200106014-94e95e34-5fc9-4f57-b3c5-328e08383578.png)

### Steps to reproduce the issue

 3.16v, 3.18v

### Versions

3.18v and 3.16v

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
First, GitHub issue's form are designed for you to check couple of things before opening one. You are running out-dated versions of QGIS (you need to check with 3.22.12 or 3.28.0). You have plugins installed which is incompatible with "I tried with a new profile".

Second, "do something ASAP" is not a nice way to ask for help.

**Comment by roya0045** [comment]
@nicogodet this is clearly a user error, they are working with an unprojected raster in WGS84 at an impossible scale and impossible coordinates and they are blaming the software.
