### ISSUE TITLE
cut a polygon in one layer, from a polygon in a seperate layer

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#50790]
### Feature description

The cut with polygon tool only works with polygons in the same layer.  It would be great to have a tool which will cut a polygon from another layer.  

### Additional context

For example, land to be disposed layer. Use the polygon to cut out of the freehold land once disposed.

**Comment by saberraz** [comment]
Is it not duplicate of this: https://github.com/qgis/QGIS/issues/50207

**Comment by KSmapping** [comment]
Sorry I hadn’t seen that.  New to github.  But what I’m asking for is the cut with polygon tool to work on separate layers as well as within a single layer

50207 is for how to use a line to spit.  I don’t want to cut I want to create a hole/ring by using a polygon.

Karen Salisbury
Technical Officer (Estates & Assets)
Planning & Development

***@***.***

[Phone] 01706 923288<tel:+441706923288>
[Mail] ***@***.******@***.***>

Rochdale Borough Council
Floor 3, Number One Riverside
Smith Street, Rochdale, OL16 1XU

To access our services go to www.rochdale.gov.uk<https://www.rochdale.gov.uk/>
For news, events and social media updates go to www.rochdale.gov.uk/newsandevents<https://www.rochdale.gov.uk/newsandevents/>

Please consider the environment before printing this email.

**Comment by uclaros** [comment]
> I don’t want to cut I want to create a hole/ring by using a polygon.

@KSmapping I suspect the _Difference_ algorithm is what you are looking for?

**Comment by KSmapping** [comment]
> > I don’t want to cut I want to create a hole/ring by using a polygon.
> 
> @KSmapping I suspect the _Difference_ algorithm is what you are looking for?

No, that creates a new layer.  Its being able to cut a layer.  Difference is great, but as I say creates a new layer

**Comment by uclaros** [comment]
Difference supports edit in place mode. You can apply it to an existing layer without creating a new output layer

**Comment by KSmapping** [comment]
I thought i had replied to the comment regarding applying difference to an existing layer.  I would appreciate more information on how to do this.  I am only able to create a new layer.

**Comment by nicogodet** [comment]
![image](https://user-images.githubusercontent.com/39594821/204229419-17b5febc-4ab7-43fa-96d6-566c389b4500.png)
![image](https://user-images.githubusercontent.com/39594821/204229555-6c9fe287-0f28-4b0d-bde8-fbdacc51fa29.png)

**Comment by nicogodet** [comment]
No need of `Advanced Parameters`, just run the alg.
I gave all the info you need to cut in place a polygon...

**Comment by uclaros** [comment]
1. Select the layer you want to make the holes to
2. Start editing
3. Select Edit in place mode
4. Select the difference algorithm
5. Select the layer that contains the 'cutter' polygons
6. Press modify all features

What does not work?

**Comment by KSmapping** [comment]
> 1. Select the layer you want to make the holes to
> 2. Start editing
> 3. Select Edit in place mode
> 4. Select the difference algorithm
> 5. In the algorithm window, select the layer that contains the 'cutter' polygons
> 6. Press modify all features
> 
> What does not work?

I am trying to cut a feature with another feature in the same layer.  Difference normally only creates a second layer, but I have been given advice by nicogodet, on how to edit within the layer.  Its that that I cant get to work. It deletes the smaller feature, , rather than creating a hole in the larger feature

**Comment by nicogodet** [comment]
> I am trying to cut a feature with another feature in the same layer

That's not the title of your issue...

> cut a polygon in one layer, from a polygon in a **seperate** layer

I start to believe there is no issue here but just a lack of knowledge about the software...

**Comment by KSmapping** [comment]
> > I am trying to cut a feature with another feature in the same layer
> 
> That's not the title of your issue...
> 
> > cut a polygon in one layer, from a polygon in a **seperate** layer
> 
> I start to believe there is no issue here but just a lack of knowledge about the software...

Nicolas.  sorry we arent all experts in QGIS.  this is why I asked the question.  I am sorry i have offended you.

**Comment by nicogodet** [comment]
No offend here ;)

Just Github is not the place to ask for help, you can first ask on user mailing, try on GIS stackexchange, etc etc.

Could you provide sample data, what you want to achieve with this data and the steps you tried ?

**Comment by uclaros** [comment]
> It deletes the smaller feature, , rather than creating a hole in the larger feature

You probably have your layers reversed then! Big feature layer should be selected in layer tree. Small feature layer should be selected within the _Difference algorithm_ dialog when run with _edit features in place_

**Comment by Almeida100** [comment]
There is a new plugin for QGis3 named "Polygon Cut" to do what is asked in the title above (cut a polygon in one layer, from a polygon in a seperate layer).
