### ISSUE TITLE
"Project home" dialog is unresponsive

### ISSUE THREAD

**Issue by dmparrishphd** [qgis/QGIS#50793]
### What is the bug or the crash?

"Project home" dialog window is unresponsive.

The same behavior occurs after deleting the Flatpak configuration file tree ~/.var/app/org.qgis.qgis file tree.

### Steps to reproduce the issue

From a newly launched QGIS session, start a new project. Use the Project menu to enter Properties. In the General tab, click the "..." button to the right of the "Project home" text box. A window pops up; this window is unresponsive; it cannot even be closed using the OS's "close window" icon in the window title bar.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Qt version | 5.15.6
Python version | 3.9.9
GDAL/OGR version | 3.5.2
PROJ version | 8.2.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.36.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | KDE Flatpak runtime
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code branch
[Release 3.26](https://github.com/qgis/QGIS/tree/release-3_26)
Qt version
5.15.6
Python version
3.9.9
GDAL/OGR version
3.5.2
PROJ version
8.2.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.36.0
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.11.6
OS version
KDE Flatpak runtime

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

We are running a Flatpak installation of 3.26.3-Buenos Aires on a RedHat system (NAME="Red Hat Enterprise Linux Server"
VERSION="7.9 (Maipo)").

**Comment by agiudiceandrea** [comment]
@dmparrishphd, it seems to me this is very likely an issue related to the Flatpak distribution of QGIS and not to QGIS itself, so I think it could be better to file the issue report to the QGIS Flatpak repository https://github.com/flathub/org.qgis.qgis and then close this. Do you agree?
