### ISSUE TITLE
Lowercase HTTP headers on WMS service cause error in Identify Results on FeatureInfo

### ISSUE THREAD

**Issue by spike83** [qgis/QGIS#50800]
### What is the bug or the crash?

We are using Istio service mesh together with geoservers and try to add such a geoserver wms layer into QGIS. Images work as expected but the identify feature is not working when using Feature mode.
![image](https://user-images.githubusercontent.com/16322660/200131373-555700a1-511f-4369-a326-e450552f7b21.png)

We are getting the error "GML schema no element found" "Cannot guess schema" "Cannot identify".

Digging down with the dev tools I found that the only difference to a working wms is the casing of the headers.  I was also able to make my wms work using Burp Proxy which seems to change the case of the headers.

The lowercase headers make the format checks in here fail: https://github.com/qgis/QGIS/blob/aaf7c89603c1be1f908d5ffc172c31246a9a51b4/src/providers/wms/qgswmsprovider.cpp#L3617-L3625

Lowercase headers seems to be compliant according to the relevant RFC. https://www.rfc-editor.org/rfc/rfc7230#section-3.2

### Steps to reproduce the issue

- Add a wms layer from https://geo.ur.ch/wms
- try to identify a feature
- change the format to `Feature`

### Versions

Some different version of the recent months up to 3.28.0-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by lisagur** [comment]
fixed with #50981

**Comment by DelazJ** [comment]
Good catch @lisagur . it duplicates #50891 fixed in #50995, backported to 3.28.2 so @spike83 you might need to test on a more recent version (3.28.0 is 6-7 monts old)

**Comment by spike83** [comment]
I can confirm it works. Was resolved with https://github.com/qgis/QGIS/pull/50995.
