### ISSUE TITLE
Alignement for line or point patterns symbology not fixed !

### ISSUE THREAD

**Issue by bsaglio2001** [qgis/QGIS#50811]
### What is the bug or the crash?

With previous versions of QGIS (for example 3.10), all layers and all entities configured with line or point pattern symbology  shared the same grid and origin when rendering their patterns. It was thus possible to configure different patterns on different layers that avoid symbology overlapping.

### Steps to reproduce the issue

I configured the symbology of 2 layers, so that they shared the same point pattern settings, with just a displacement on one of them.The result of overlapping patterns was fixed in QGIS 3.10, even when zooming in or out.

![OVERLAPPING_PATTERNS_01_QGIS_310](https://user-images.githubusercontent.com/47885683/200357198-20561078-970a-4e48-a325-6fe0bd8ea7e1.png)
![OVERLAPPING_PATTERNS_02_QGIS_310](https://user-images.githubusercontent.com/47885683/200357206-0d782296-3b85-41bd-81df-e25f7e7322b2.png)

In QGIS 3.22, I tried to reimport these 2 layers and their symbology. I also tried to configure the same settings from scratch. In both case, the result of overlapping pattern is not aligned between entities and layers. Moreover, the alignment changes when zooming in or out. 

![OVERLAPPING_PATTERNS_01_QGIS_322](https://user-images.githubusercontent.com/47885683/200357242-669b7f84-3235-42e2-a572-64390bdfea03.png)
![OVERLAPPING_PATTERNS_02_QGIS_322](https://user-images.githubusercontent.com/47885683/200357244-34b7f0f7-e57d-43b4-9004-1a3d0d7b7590.png)

Here is a sample of my layers with default point pattern symbology, so you can reproduce the bug in your own QGIS 3.22.
[elements_to_test.zip](https://github.com/qgis/QGIS/files/9953399/elements_to_test.zip)

Please note that there is a similar bug with lines patterns.

There is probably a link with this issue : #46946

### Versions

QGIS 3.22.11

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
I can cofirm that the issue occurs using QGIS 3.22.11 (OSGeo4W) on Windows 10.
The issue doesn't occur using QGIS 3.10 on the same system.

**Comment by nyalldawson** [comment]
This is what the symbol alignment option is designed to control:

https://qgis.org/en/site/forusers/visualchangelog324/index.html#feature-coordinate-reference-mode-setting-for-line-pattern-and-point-pattern-fill-symbol-layers
