### ISSUE TITLE
Some QGis projects crash when zooming in and out quickly

### ISSUE THREAD

**Issue by Massi919** [qgis/QGIS#50828]
## User Feedback

I have recently installed an older version of QGis (3.16), because the one I used (3.22) did not have some functions that the older one had.
The problem I faced was that when I opened some projects (which I built with the 3.22 version) with the recently installed 3.16 QGis  and I zoomed in and out fast, the projects were crashing without leaving error messages.
So I tried to rebuild one of my project from 0, but then after I added some layers and then zoomed in and out quickly to make sure I didn't have this problem anymore, it actually happened again that the project crashed. However this time the Qgis page "Qgis unexpectedly ended" appeared.
What could be the reason and the solution to the problem?

## Report Details

**Crash ID**: [fc4b25945b8684770dd1dd420ce97cdda575be37](https://github.com/qgis/QGIS/search?q=fc4b25945b8684770dd1dd420ce97cdda575be37&type=Issues)

**Stack Trace**
<pre>
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
</pre>

**QGIS Info**
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89df
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

To see the project I am working on follow the link:
https://we.tl/t-8nj7L9EuZS

### Versions

Versione di QGIS
3.16.16-Hannover
Revisione codice QGIS
f5778a89df
Compilato con Qt
5.11.2
Esecuzione con Qt
5.11.2
Compilato con GDAL/OGR
3.1.4
Esecuzione con GDAL/OGR
3.1.4
Compilato con GEOS
3.8.1-CAPI-1.13.3
Esecuzione con GEOS
3.8.1-CAPI-1.13.3
Compilato su SQLite
3.29.0
In esecuzione su SQLite
3.29.0
Versione client PostgreSQL
11.5
Versione SpatiaLite
4.3.0
Versione QWT
6.1.3
Versione QScintilla2
2.10.8
Compilato con PROJ
6.3.2
Esecuzione con PROJ
Rel. 6.3.2, May 1st, 2020
Versione SO
Windows 10 (10.0)
Attiva python plugin
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
3.16 is not supported, if you want to keep using it have fun with the crashes.

**Comment by Massi919** [comment]
Alright, but in 3.16 I can now utilize some functions I need that I couldn't use in 3.22.
So isn't there a way to solve the crashing problem without having to install a new version of Qgis?

**Comment by DelazJ** [comment]
> I have recently installed an older version of QGis (3.16), because the one I used (3.22) did not have some functions that the older one had.

@Massi919 Can you name the functions in 3.16 that are no longer in 3.22? There is maybe a replacement you are not aware of.

**Comment by Massi919** [comment]
Well, Qgis 3.22 doesn't read .ecw files, and also a function of GRASS (r.watershed) does not work...

**Comment by esnyder-rve** [comment]
According to the discussion on Telegram, ECW files were able to be brought in directly. I proposed the solution to install QGIS via the OSGeo4W installer and install the `gdal-ecw` driver for ecw support.

**Comment by esnyder-rve** [comment]
Use the OSGeo4W installer to install QGIS.
1. Click Advanced Install
2. Download from Internet
3. Pick somewhere to install (typically `C:\OSGeo4W`) & Just Me
4. Just click Next for the Local Package Directory
5. Setup proxy (if behind a proxy)
6. Select a mirror
7. Under `Desktop` check `qgis` for latest version (3.28) or `qgis-ltr` for the LTR version (3.22) (or search)
8. Under `Libs` select `gdal-ecw` for ecw support (or search)
9. The installer will automatically select dependencies and install them
10. You will get a registry editor popup, that's normal

**Comment by Massi919** [comment]
Thank you so much for your help.
I will try it out and if any problem occurs I will repost it here below. Otherwise I will close the comment.
