### ISSUE TITLE
QGIS 3.28 New 3d Map View crash

### ISSUE THREAD

**Issue by merkato** [qgis/QGIS#50821]
### What is the bug or the crash?

After creating new 3D Map view, QGIS draws new window, then crashing.

As I have problems with getting gdb backtrace only console output here:
[consolelog.txt](https://github.com/qgis/QGIS/files/9958207/consolelog.txt)

### Steps to reproduce the issue

1. Set project CRS to EPSG:2180
2. Add raster layer (downloaded from https://opendata.geoportal.gov.pl/NumDaneWys/NMT/4266/4266_94328_M-34-63-A-b-1-3.asc)
3. Set layer CRS to EPSG:2180
4. Add WMS/WMTS layer: https://mapy.geoportal.gov.pl/wss/service/WMTS/guest/wmts/TOPO?SERVICE=WMTS&REQUEST=GetCapabilities
5. Select View -> 3D Map View -> New 3D Map

### Versions

Wersja QGIS
3.28.0-Firenze
Rewizja QGIS
[ed3ad0430f](https://github.com/qgis/QGIS/commit/ed3ad0430f)
Wersja Qt
5.15.3
Wersja Pythona
3.10.6
Wersja GDAL/OGR
3.4.1
Wersja PROJ
8.2.1
Wersja bazy danych Rejestru EPSG
v10.041 (2021-12-03)
Wersja GEOS
3.10.2-CAPI-1.16.0
Wersja SQLite
3.37.2
Wersja PDAL
2.3.0
Wersja klienta PostgreSQL
unknown
Wersja SpatiaLite
5.0.1
Wersja QWT
6.1.4
Wersja QScintilla2
2.11.6
Wersja systemu operacyjnego
Ubuntu 22.04.1 LTS

Active Python plugins
pobieracz_danych_gugik
1.0.2
ViewshedAnalysis
1.8
gissupport_plugin
1.13
inspireatomclient
0.8.1
QuickOSM
2.1.1
MetaSearch
0.3.6
grassprovider
2.12.99
sagaprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Crash is reproducible with that dataset on another Ubuntu machine, and on Windows 10.

**Comment by saberraz** [comment]
I am not able to reproduce your issue with QGIS 3.28 with your description on Ubuntu 22.04:
(note: your WMS link only accepts http not https for me)
![3d_not_crash](https://user-images.githubusercontent.com/2649047/200506217-7c411846-77e6-4cd2-97c7-0e1b0886b3d6.gif)

**Comment by saberraz** [comment]
Could you try with a new profile?

**Comment by merkato** [comment]
http/https thing is something wrong with polish state geoportal server. sometimes works.

Yes. I tried with clean profile, same.

**Comment by gsapijaszko** [comment]
The same for me with the set, qgis crashes. strace log attached.
[qgis.tar.gz](https://github.com/qgis/QGIS/files/9964184/qgis.tar.gz)


QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
