### ISSUE TITLE
Pressing "DEL"-button on keyboard not working after "split features" of selected feature

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#50830]
### What is the bug or the crash?

Pressing "DEL"-button on keyboard is not working after "split features" of selected feature. 
Selected feature can only be deleted by "Delete selected"-button or selecting the feature again.

### Steps to reproduce the issue

1) create a polygon layer and digitize a feature
2) select feature (colour yellow by default)
3) split feature (as a result one of the new pieces is selected (colour yellow))

4.1) press "del" on keyboard -> nothing happens althrough a feature is selected **-> unexpected behaviour (issue)**
or
4.2) press "delete selected"-button -> new (selected) piece will be deleted
or
4.3.1) press "select feature by area or single click"-button and select (already selected) piece again
4.3.2) press "del" on keyboard ->new (selected) piece will be deleted

->behaviours of 4.1 and 4.3.2 are not the same

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f3](https://github.com/qgis/QGIS/commit/ed3ad0430f3)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
It's actually not a bug ; the del key is captured by the split tool, which uses it to delete the last point added on the split path. So while the split parts/split feature tool is active, you cannot use Del to delete features, even before splitting anything.
