### ISSUE TITLE
Deleting label text causes label to be removed

### ISSUE THREAD

**Issue by koebi** [qgis/QGIS#50831]
### What is the bug or the crash?

When trying to remove text in the *Main properties* of a *Label* in any *Print Layout* by pressing `Delete` or `BackSpace`, it deletes the whole label.

### Steps to reproduce the issue

1. Open a QGIS project
2. `Ctrl-P` or Click on *New Print Layout*
3. Click on *Add Label*
4. Draw Label on Canvas
5. Click on *Item Properties* of said Label
6. Click on the textfield of the *Main Properties*-Tab, see a blinking cursor after the default `Lorem Ipsum`
7. Press `BackSpace`
8. See the label get removed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.12-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.6
Python version | 3.10.8
Compiled against GDAL/OGR | 3.5.2 | Running against GDAL/OGR | 3.5.3
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.4
PostgreSQL client version | 15.0 (Debian 15.0-2)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
Active Python plugins
ohsomeTools | 0.2.1-alpha
quick_map_services | 0.19.27
ORStools | 1.5.2
valhalla | 2.2.1
OnlineRoutingMapper | 0.9
veloroutes_voies_vertes | 1.0.0
TerrainShading | 0.9.3
qgis2web | 3.16.0
plugin_reloader | 0.9.1
sagaprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
processing | 2.12.99
grassprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

There was a [similar issue](https://github.com/qgis/QGIS/issues/25680) a while back, yet the fix seems to only apply to mac.
I was looking for other issues for this, but couldn't find any, so apologies if this is a duplicate :)

**Comment by roya0045** [comment]
That's weird, I'm not sure if it's more of a qt issue on your OS and I didn't experience that in windows. It sounds like the signal is sent to the layout as if you wanted to delete the item itself instead of being in the text area.

**Comment by koebi** [comment]
I am a bit reluctant to build from source to test this - is there any other way I could support further investigation?

**Comment by alexbruy** [comment]
You can test nightly builds from OSGeo4W or download arifact from the latest commit on GitHub.

**Comment by koebi** [comment]
With the latest updates to both the OS and QGIS, this doesn't seem to be an issue anymore.
Thank you for your support :)
