### ISSUE TITLE
postgresraster provider no longer handles views, critical errors on filtering

### ISSUE THREAD

**Issue by thayeray** [qgis/QGIS#50841]
### What is the bug or the crash?

Two bugs are noted related to PostGIS rasters: 

1) When attempting to filter a postgresraster table, e.g. from the context menu of the Layers panel, if there are no results from the filter expression, a critical PostGIS error is thrown: "CRITICAL    An error occurred while fetching raster metadata"

2) Attempting to add a layer from a view or materialized view (with unique and spatial indexes) on a raster table fails with the following warnings: 'WARNING    Could not find a primary key for PostGIS raster table "schema"."table_name"',  'WARNING    PostgreSQL raster layer has no primary key.',  'WARNING    Invalid PostgreSQL raster layer',  'WARNING    Data type size for band 1 could not be found: num bands is: 0 and the type size map for bands contains: 0 item(s).' 

In both cases the map canvas' state remains the same as that prior to attempting to filter or add a layer.

### Steps to reproduce the issue

For filtering:
1. right click on a postgresraster that has been added to the map canvas and displays successfully
2. select 'Filter'
3. enter a filter expression that will return an empty set of rasters, e.g. 'rid < 0'.

For adding a layer from a raster view:
1) Create a view of a raster table in a PostGIS database, e.g.: 
  'CREATE VIEW add_rast AS SELECT rid, rast FROM raster_table WHER rid < 20;'
2) Attempt to add the view to the QGIS map canvas using any of the following methods:
  a) Browser Panel
  b) Database Manager
  c) Data Source Manager

### Versions

Addition of postgresraster views worked in QGIS version 3.10. This stopped working by 3.14 and continues to be a problem, e.g. 3.26.3. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This bug was first noted by Dirk Pispers in a message to the QGIS user listserve. @elpaso has asked to be tagged so he can assign it to himself. Thanks to both Dirk and Alessandro!

**Comment by elpaso** [comment]
Thank you for reporting.

They seems two separate issues, next time please file two separate tickets, it makes it easier for developers to manage.

**Comment by thayeray** [comment]
Thanks, will do.
-T

    On Friday, November 11, 2022 at 03:28:54 AM EST, Alessandro Pasotti ***@***.***> wrote:  
 
 


Thank you for reporting.

They seems two separate issues, next time please file two separate tickets, it makes it easier for developers to manage.
