### ISSUE TITLE
rasterUnitsPerPixel<X,Y> in graphical modeler

### ISSUE THREAD

**Issue by feefladder** [qgis/QGIS#50856]
### Feature description

Expose The raster pixel size as an input or parameter in the graphical modeler. Currently it _is_ possible to do something like that by:
[Python file saved as .txt](https://github.com/qgis/QGIS/files/9981214/constant_raster_like.txt)

with relevant lines:

```python
        reference = self.parameterAsRasterLayer(parameters, 'reference', context)
        if (reference.rasterUnitsPerPixelX() != reference.rasterUnitsPerPixelY()):
            feedback.reportError("Raster units differ: x-y=" + str(reference.rasterUnitsPerPixelX() - reference.rasterUnitsPerPixelY()))

        # Create constant raster layer
        alg_params = {
            'PIXEL_SIZE': reference.rasterUnitsPerPixelX(),
        }
```

But it would be very nice to be able to do that directly in the graphical modeler. Possibly by adding an input called RasterUnitsPerPixel? Inputs seem to be the only things that can be anything. I tried making a process that adds it, but they can only have layers or html files as output, not numbers.
Also I tried with the expression builder, but that returned null values.

### Additional context

![image](https://user-images.githubusercontent.com/33122845/201109286-83a6d93b-4340-4db3-9f51-b8790766eb75.png)

**Comment by nyalldawson** [comment]
You can use the "Raster layer properties" algorithm to derive this value in your models.

**Comment by feefladder** [comment]
Thanks a lot! I was doing too complicated things!

For anyone else coming here: You can then use those with the `pre-calculated value`:
![image](https://user-images.githubusercontent.com/33122845/203271856-94957be7-a836-48db-a65a-ad8e3e1742b8.png)
