### ISSUE TITLE
Export to EPSG:3857 with GeoJSON format on MacOS doesn't work

### ISSUE THREAD

**Issue by matpascaud** [qgis/QGIS#50857]
### What is the bug or the crash?

I created a shape using temporary layer in memory.
I choose the SCR ESPG:3857 for the layer.
When I save the layer to GeoJSON, the format is not the one expected.
`{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ] ], [ [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ], [ 0.0000134, 0.0003915 ] ] ] } }
{ "type": "Feature", "properties": { "id": null }, "geometry": { "type": "Polygon", "coordinates": [ [ [ 1.4945714, 43.5783213 ], [ 1.494518, 43.5771948 ], [ 1.4950284, 43.5771776 ], [ 1.4950818, 43.5779042 ], [ 1.4945714, 43.5783213 ] ], [ [ 1.4946842, 43.5776377 ], [ 1.4947198, 43.5779128 ], [ 1.4949335, 43.5775775 ], [ 1.4948741, 43.5773367 ], [ 1.4946842, 43.5776377 ] ] ] } }
`

### Steps to reproduce the issue

Create a new layer using SCR ESPG:3857
Save the layer using GeoJSON format to disk.
Open the file and see the that the format is not the one expected

### Versions

Version de QGIS | 3.26.3-Buenos Aires | Révision du code | 65e4edfdad
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.3.2
Version de Proj | 8.1.1
Version de la base de données du registre EPSG | v10.028 (2021-07-07)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.11.5
Version de l'OS | macOS 12.6
  |   |   |  
Extensions Python actives
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>Version de QGIS
3.26.3-Buenos Aires
Révision du code
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.3.2
Version de Proj
8.1.1
Version de la base de données du registre EPSG
v10.028 (2021-07-07)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.35.2
Version de PDAL
2.3.0
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.11.5
Version de l'OS
macOS 12.6

Extensions Python actives
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
I believe your are talking about coordinates written in .geojson ?

If so, please see GeoJSON specifications regarding coordinates: https://www.rfc-editor.org/rfc/rfc7946#page-12

**Comment by matpascaud** [comment]
The problem I see is that the export is not made using EPSG:3857 but EPSG:4326.  If you check at the JSON I paste, coordinates are in degrees and not meters.
On QGIS, I can see that the selected SCR is EPSG:3857 but I do not understand why when I save to GeoJSON, coordinates are not EPSG:3857.

**Comment by nicogodet** [comment]
Did you read the link ?

> The coordinate reference system for all GeoJSON coordinates is a geographic coordinate reference system, using the World Geodetic System 1984 (WGS 84) [WGS84] datum, with longitude and latitude units of decimal degrees.

**Comment by matpascaud** [comment]
Sorry, I missed that part. 
I was overwhelmed because a colleague of mine did export using EPSG:3857.

**Comment by nicogodet** [comment]
Using QGIS ?

**Comment by matpascaud** [comment]
Yes. Probably an older version.

**Comment by nicogodet** [comment]
Indeed.
Could you try with latest version (3.28.0) ?

I tried on Linux and I can export using another CRS.

**Comment by matpascaud** [comment]
It failed with 3.28.0. I guess it has something to do with the OS.
