### ISSUE TITLE
Lack of feedback about QGIS not working

### ISSUE THREAD

**Issue by jonathan-geoseer** [qgis/QGIS#50852]
### What is the bug or the crash?

Brand new install of QGIS OSGEO4W 3.18.3 on Windows 7.
There's only 3 options under "Raster" and none under "Vector". The Plugins page all seems fine unless you read the bit on the plugins-> Settings which says in an ordinary font: `The settings on this page are only applicable for Python Plugins. No Python Support detected.`

And if you know about the console you can see:
> 2022-11-10T09:58:36     WARNING    Couldn't load Python support library: Cannot load library qgispython: The specified module could not be found.

The bug is: There's a complete lack of user feedback that nothing is going to work and they have access to none of the QGIS tooling or plugins. This stumped me for 10+ minutes because while I'm a long-time QGIS user (10+ years) I've not used it much lately. A completely new user won't have a clue what's going on or why none of the online guides are reflecting their installation "Raster -> Miscellaneous.... I don't have a Miscellaneous button..." etc).

### Steps to reproduce the issue

See above

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.18.3-Zürich | QGIS code revision | 735cc85be9
-- | -- | -- | --
Compiled against Qt | 5.15.2 | Running against Qt | 5.15.2
Compiled against GDAL/OGR | 3.3.0 | Running against GDAL/OGR | 3.3.0
Compiled against GEOS | 3.9.1-CAPI-1.14.2 | Running against GEOS | 3.9.1-CAPI-1.14.2
Compiled against SQLite | 3.35.2 | Running against SQLite | 3.35.2
Compiled against PDAL | 2.2.0 | Running against PDAL | 2.2.0 (git-version: 365171)
PostgreSQL Client Version | 13.0 | SpatiaLite Version | 5.0.1
QWT Version | 6.1.3 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 8.0.1 | Running against PROJ | Rel. 8.0.1, March 5th, 2021
OS Version | Windows 7 Version 6.1 (Build 7601: SP 1)

</body></html>QGIS version
3.18.3-Zürich
QGIS code revision
[735cc85be9](https://github.com/qgis/QGIS/commit/735cc85be9)
Compiled against Qt
5.15.2
Running against Qt
5.15.2
Compiled against GDAL/OGR
3.3.0
Running against GDAL/OGR
3.3.0
Compiled against GEOS
3.9.1-CAPI-1.14.2
Running against GEOS
3.9.1-CAPI-1.14.2
Compiled against SQLite
3.35.2
Running against SQLite
3.35.2
Compiled against PDAL
2.2.0
Running against PDAL
2.2.0 (git-version: 365171)
PostgreSQL Client Version
13.0
SpatiaLite Version
5.0.1
QWT Version
6.1.3
QScintilla2 Version
2.11.5
Compiled against PROJ
8.0.1
Running against PROJ
Rel. 8.0.1, March 5th, 2021
OS Version
Windows 7 Version 6.1 (Build 7601: SP 1)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

(It's not at all clear what a "supported QGIS version" is from the link. You may wish to make that more user friendly)

**Comment by jonathan-geoseer** [comment]
Thank you but you've missed the entire point of this ticket:

QGIS SHOULD TELL THE USER THAT IT'S NOT WORKING.
So unless you've done something in the "supported" versions that does in fact tell the user that it's not working, this ticket remains valid.

You have more Windows 7 users than you do Linux users of QGIS. (This is globally the case for these respective Desktop OS's too). I appreciate you're not supporting Windows 7 (too late to change that), but that doesn't mean QGIS should be silently failing.

**Comment by alexbruy** [comment]
QGIS **does** tell you about problems with your installation. "No Python Support detected" and "Couldn't load Python support library: Cannot load library qgispython: The specified module could not be found" messages are pretty clear.

**Comment by jonathan-geoseer** [comment]
> QGIS **does** tell you about problems with your installation. "No Python Support detected" and "Couldn't load Python support library: Cannot load library qgispython: The specified module could not be found" messages are pretty clear.

As I already stated:
>  This stumped me for 10+ minutes because while I'm a long-time QGIS user (10+ years) I've not used it much lately. A completely new user won't have a clue what's going on or why none of the online guides are reflecting their installation "Raster -> Miscellaneous.... I don't have a Miscellaneous button..." etc).

A new user isn't going to see either of those things. They're not going to read the same-font-as-everything-else message, nor are they going to know there's a console.
This is BAD UI. I don't know how I can be more explicit than this.

**Comment by nicogodet** [comment]
There is a clear message on QGIS download page too 

> QGIS requires Windows 8 64 bit or higher because QGIS uses Python 3.9 or later, which is not available for Windows 7.

**Comment by jonathan-geoseer** [comment]
> There is a clear message on QGIS download page too
> 
> > QGIS requires Windows 8 64 bit or higher because QGIS uses Python 3.9 or later, which is not available for Windows 7.

Yes, there is. And as I have pointed out in the list, this should point to the latest version that DOES run on Windows 7. Not doing so is like telling Linux users "the latest version doesn't work for you" and then letting them figure out for themselves which version to use with no help.

Furthermore, the person downloading it is not always the person running it. I really don't get this aversion to actually having an error message that tells the user "This is very broken and won't work properly". Especially given there are likely other scenarios other than Windows 7 that will trigger this and again, there's nothing to indicate to a lay-user that everything is broken.

**Comment by nicogodet** [comment]
It could be reported on OSGeo4W tracker : https://trac.osgeo.org/osgeo4w/report
