### ISSUE TITLE
Windows update KB5019959 causes issues with MSSQL connections

### ISSUE THREAD

**Issue by jackgreengis** [qgis/QGIS#50865]
### What is the bug or the crash?

Recent windows update KB5019959 updates the sql driver C:\Windows\System32\sqlsrv32.dll this has a flow on effect to MSSQL connections in QGIS. The zoom to layer function will no longer work on layers. Identify tool causes QGIS to crash with some layers. Opening some attribute tables causes QGIS to crash. 
This has been tested on the following versions:
3.22.4, 3.22.12, 3.28 

### Steps to reproduce the issue

Ensure latest windows updates have been installed, KB5019959 cumulative release definitely has the update but others may as well. 
Check that C:\Windows\System32\sqlsrv32.dll has been updated. 
In QGIS create a MSSQL connection to spatial layers or use an existing one. 
Add a layer to a new map - screen will remain blank
Right click layer > Zoom To Layer - nothing will happen

### Versions

3.22.4
3.22.12
3.28 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Chris76FiSi** [comment]
There are more MS Update KB's, which causes this issue. All have replaced the sqlsrv32.dll
KB5019964
KB5020010
KB5020023

**Comment by harry202211** [comment]
I've tested it with 64-bit version 3.14.1，seriously，qgis 3.14.1 can no longer be used after windows 10  updated KB5019959

**Comment by SpatialSpath** [comment]
I can confirm that this is also affecting all City of Swan users. Just steering clear of the Identify Tool for the time being...

**Comment by j-lippmann** [comment]
I can confirm. May be all qgis versions are affected. Thats why the issue should have a high prio please.

**Comment by nyalldawson** [comment]
This isn't a qgis specific issue -- there's lots of reports of that kb breaking odbc SQL server connections elsewhere. Let's hope for a speedy fix from Microsoft.

**Comment by nanos87** [comment]
Depeding on the QGIS version I experienced more issues then just the identify tool (missing entries in attribute table, missing layer extent, server error on QGIS Servers GetFeatureInfo-requests)
 
As Microsoft does not recommend to use „SQL Server“ ODBC driver anymore – I’m not sure if there will be a quick fix by Microsoft.
https://learn.microsoft.com/en-us/sql/connect/connect-history?view=sql-server-ver16&redirectedfrom=MSDN&viewFallbackFrom=sqlallproducts-allversions

At least a workaorund is to install and reference the recommended „ODBC Driver 18 for SQL Server“ either in QGIS MSSQL Connection panel or defining a DSN.
Instead of using the latest driver form MS, the OSGeo4W installer delivers the msodbcsql17.dll, which can be added into odbc.ini (registry) as well.

![image](https://user-images.githubusercontent.com/22340023/202842063-5cff97ae-8e94-4c2e-92f4-828796248904.png)

I guess a general setting or a combo box within the dialog to define the default odbc driver would be great at this point.

**Comment by agiudiceandrea** [comment]
msodbcsql has been updated to 18.0 in OSGeo4W https://github.com/jef-n/OSGeo4W/commit/3547835c8171fca1f37109e42e1957f7a71b71af

**Comment by j-lippmann** [comment]
> msodbcsql has been updated to 18.0 in OSGeo4W [jef-n/OSGeo4W@3547835](https://github.com/jef-n/OSGeo4W/commit/3547835c8171fca1f37109e42e1957f7a71b71af)

in my case this does not solve the problem

**Comment by j-lippmann** [comment]
qgis reports:
``2022-11-20T20:25:24     CRITICAL    Qt : qGetStringData: Error while fetching data ( "[Microsoft][ODBC SQL Server Driver]Fehler in der Funktionsreihenfolge" )``

**Comment by jef-n** [comment]
msodbcsql is only linked to GDAL, while the mssql provider uses the the system-wide ODBC driver (on Windows)

**Comment by nyalldawson** [comment]
@NathanW2 has done extensive digging and has some further insights here

**Comment by rdewit** [comment]
Not sure if the following is helpful or if I'm creating noise: one of our clients using QGIS Server noticed that some layers using MSSQL stopped working after their Windows updates.

They deduced that the layers that failed had a field of type `float`. Converting the relevant database column to type `real` appeared to solve their issue.

**Comment by jonnygis** [comment]
> Not sure if the following is helpful or if I'm creating noise: one of our clients using QGIS Server noticed that some layers using MSSQL stopped working after their Windows updates.
> 
> They deduced that the layers that failed had a field of type `float`. Converting the relevant database column to type `real` appeared to solve their issue.

This certainly helped us out. We are working again, albeit more slowly at the moment.

**Comment by NathanW2** [comment]
@jef-n @nyalldawson  Hey sorry, been meaning to get back to this.    It is quite annoying indeed.

Have spent some time digging into this more over the last few days.

It seems like something is broken down in the windows SQLSRV32.DLL related to reading floats into `double` using SQLGetData in and `SQL_C_DOUBLE` type:

` r=SQLGetData(hstmt, 1, SQL_C_DOUBLE, &floatValue, 0, &n);`

Looking down into the Qt code this is what they are using for reading float values:

- https://github.com/openwebos/qt/blob/master/src/sql/drivers/odbc/qsql_odbc.cpp#L1206
- https://github.com/openwebos/qt/blob/master/src/sql/drivers/odbc/qsql_odbc.cpp#L528

Some other users reporting issues around the same time as the patches are:

- https://stackoverflow.com/questions/74447805/sqlgetdata-doesnt-work-in-the-same-way-after-install-kb5019959
- https://qtcentre.org/threads/71971-ODBC-to-MS-SQL-Server-failes-since-KB5019959 


Tonight I hacked together some super nasty C code to hopefully show the issue as raw as possible. Get ready for some eye bleeding bad C code

```
#include <windows.h>
#include <stdio.h>
#include <sql.h>
#include <sqlext.h>

#define BUFSIZE 300

SQLHANDLE hDbc;
SQLHENV env;

main() {

  char path[BUFSIZE];
  char *envvar = "CONN_STRING";

      // Make sure the buffer is large enough to hold the environment variable
    // value. 
    if(snprintf(path, BUFSIZE, "%s", getenv(envvar)) >= BUFSIZE){
        fprintf(stderr, "BUFSIZE of %d was too small. Aborting\n", BUFSIZE);
        exit(1);
    }
    printf("PATH: %s\n", path);

  char driver[256];
  char attr[256];
  SQLSMALLINT driver_ret;
  SQLSMALLINT attr_ret;
  SQLUSMALLINT direction;
  SQLRETURN ret;

  SQLAllocHandle(SQL_HANDLE_ENV, SQL_NULL_HANDLE, &env);
  SQLSetEnvAttr(env, SQL_ATTR_ODBC_VERSION, (void *) SQL_OV_ODBC3, 0);

  direction = SQL_FETCH_FIRST;
  while(SQL_SUCCEEDED(ret = SQLDrivers(env, direction,
                                       driver, sizeof(driver), &driver_ret,
                                       attr, sizeof(attr), &attr_ret))) {
    direction = SQL_FETCH_NEXT;
    printf("%s - %s\n", driver, attr);
    if (ret == SQL_SUCCESS_WITH_INFO) printf("\tdata truncation\n");
  }

   SQLSMALLINT cso;
   SQLCHAR     outConnection[2048];
   SQLRETURN retcode;

   retcode = SQLAllocHandle( SQL_HANDLE_DBC, env, &hDbc );

   HWND desktopHandle = GetDesktopWindow(); 

   if (retcode == SQL_SUCCESS || retcode == SQL_SUCCESS_WITH_INFO) {
	retcode = SQLDriverConnect( hDbc, desktopHandle, (SQLCHAR*)"driver=SQL Server;Database=qgistest;Server=localhost", 
	_countof("driver=SQL Server;Database=qgistest;Server=localhost"),
	outConnection, sizeof(outConnection) - 1, &cso, SQL_DRIVER_PROMPT);

	printf("%s \n",outConnection);

	if (retcode == SQL_SUCCESS || retcode == SQL_SUCCESS_WITH_INFO){
		printf("Connected!!\n ");

		db_fetch();

	} else {
		printf("FAILED %d\n", retcode);
		if (retcode == SQL_ERROR){ 
			SQLCHAR state[6];
			SQLCHAR msg[SQL_MAX_MESSAGE_LENGTH];
			SQLINTEGER error;
			SQLSMALLINT msgLen;
			retcode = SQLGetDiagRec(SQL_HANDLE_DBC, hDbc, 1, state, &error, msg, sizeof(msg), &msgLen);
			printf("ERROR: %s \n", msg);
		}
	}
    }
}

int db_fetch()
{
  SQLRETURN r;
  SQLHSTMT hstmt;
  SQLCHAR sql[256];
  SQLLEN n;
  SQLCHAR name[20];
  double floatValue;
  SQL_DATE_STRUCT birthday;
  SQL_TIMESTAMP_STRUCT create_timestamp;

  if(hDbc==NULL) return 0;

  r=SQLAllocHandle(SQL_HANDLE_STMT, hDbc, &hstmt);
  if(!(r==SQL_SUCCESS||r==SQL_SUCCESS_WITH_INFO)) return 0;

  strcpy(sql,"select floatcol, textcol from data");
  r=SQLExecDirect(hstmt, sql, SQL_NTS);
  if(r!=SQL_SUCCESS) 
  {
		SQLCHAR state[6];
		SQLCHAR msg[SQL_MAX_MESSAGE_LENGTH];
		SQLINTEGER error;
		SQLSMALLINT msgLen;
		SQLRETURN retcode = SQLGetDiagRec(SQL_HANDLE_STMT, hDbc, 1, state, &error, msg, sizeof(msg), &msgLen);
		printf("ERROR: %s \n", msg);
    printf("cannot access [%s]\n", sql);
    SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
    return 0;
  }

  while(1)
  {
    r=SQLFetch(hstmt);
    if(r==SQL_SUCCESS||r==SQL_SUCCESS_WITH_INFO)
    {
      r=SQLGetData(hstmt, 1, SQL_C_DOUBLE, &floatValue, 0, &n);
      r=SQLGetData(hstmt, 2, SQL_C_CHAR, name, 20, &n);
      printf("FLOATCOL=%f, TEXTCOL=%s\n", floatValue, name);
    }
    else if(SQL_NO_DATA==r) {
	printf("End of data \n");
	break;
    }
    else
    {
      printf("%s\n", "fail to fetch data");
      break;
    }
  }
  SQLFreeHandle(SQL_HANDLE_STMT, hstmt);
  return;
}

```

Sample data for SQL Server:

```
CREATE TABLE [dbo].[data](
	[floatcol] [float] NULL,
	[textcol] [varchar](50) NULL
) ON [PRIMARY]

insert into data (floatcol, textcol) values (1234.56, 'something');
```

On my home PC the above reports:

![image](https://user-images.githubusercontent.com/381660/203550688-607ed1e8-63a3-4ddf-b2a4-b11a11e42638.png)

However, my home PC is behind in Windows updates and doesn't seem to have this patch.  Tomorrow I can confirm using the above code if machines with those patches return bad data for this.

What I'm not understanding is the lack of notes anywhere about why this changed.  Seems to have had a little bit of impact around the place.  Trying to work out exactly what changed in a windows patch is like pull teeth.

The ODBC docs seem to indicate that this is supported:

![image](https://user-images.githubusercontent.com/381660/203551193-cba75e42-d0ae-4325-bfd9-62332684513c.png)

**Comment by NathanW2** [comment]
There is some workarounds we can do in QGIS, such as setting numericalPrecisionPolicy on our QSqlDatabase connections however that means any doubles are returned as strings and we would need to convert back in all the different place.  A bit of a gross hack considering ODBC is meant to be stable......................

This bug only seems to affect the `SQL Server` driver. `SQL Server Native Driver 11.0` and above don't seem to be affected.

I have some ideas on how we might present this as options in the UI for the user because we really should avoid the base SQL Server driver anyway, but still would be nice to find some notes from MS about why this is now busted so we don't need to add a bunch of hacks.

**Comment by NathanW2** [comment]
For those that are affected (@SpatialSpath) I would recommend installing the native ODBC drivers if you can and using those with a DSN.  It is also possible to supply `Driver={SQL Server Native Client 11.0}` in the connection string which avoids changing data or issues.

**Comment by TonyFMCMC** [comment]
I think I have the same issue.  https://gis.stackexchange.com/questions/445874/azure-sql-database-tables-are-suddenly-extremely-slow-to-respond-in-qgis-to-a-cl

I will try with Nathan's recommendation "For those that are affected (@SpatialSpath) I would recommend installing the native ODBC drivers if you can and using those with a DSN. It is also possible to supply Driver={SQL Server Native Client 11.0} in the connection string which avoids changing data or issues."

**Comment by jackgreengis** [comment]
@NathanW2 thanks for your follow up work investigating what the actual errors are. We tested some of the suggested workarounds using other drivers with success. Our biggest issue is IT not wanting us to install additional drivers, that plus all the QGIS projects that have already been created with the current configuration. Our interim solution has been to just replace the sqlsrv32.dll with the previous version post any windows updates. Hopefully a future Windows update fixes the problem.

**Comment by NathanW2** [comment]
I was able to replicate this with the above C code (tweaked) to show the issue with the driver:

![image](https://user-images.githubusercontent.com/381660/203925953-7a79add5-4696-40d0-9e3a-3249ede93592.png)


This is reading a float col and then text columns, it breaks after reading the float col.

**Comment by TonyFMCMC** [comment]
> I will try with Nathan's recommendation "For those that are affected (@SpatialSpath) I would recommend installing the native ODBC drivers if you can and using those with a DSN. It is also possible to supply Driver={SQL Server Native Client 11.0} in the connection string which avoids changing data or issues."

But I was using Intramaps Roam, which generated errors as is hasn't been designed (I figure) to use other than the default driver...  So Instead I have just converted all my float fields in relevant databases to decimals (fortunately none demanded super-high accuracy).

**Comment by NathanW2** [comment]
@TonyFMCMC Roam will be using whatever driver that connection in QGIS was setup with, which is the detault one.  If you update the connections in your project file it will fix those issues.

Sometimes changing to decimals is the right call, or `real` if you still need float.

**Comment by NathanW2** [comment]
Have been doing some more digging.

Seems there is a change of behavior around one of the parameters in `SQLGetData`.  The `BufferLength` 

https://learn.microsoft.com/en-us/sql/odbc/reference/syntax/sqlgetdata-function?view=sql-server-ver16

in older versions, you can set `0` for this value for fixed-size data (which I assume float being 8 bytes is what they mean by that):

Used to work but doesn't now (This is what Qt framework is doing):

```
	SQLDOUBLE value;
	SQLLEN lengthIndicator = 0;
	SQLRETURN r;
	r = SQLGetData(hstmt, col, SQL_C_DOUBLE, &value, 0, &lengthIndicator);
```   

HOWEVER the following works for me:

```
	SQLDOUBLE value;
	SQLLEN lengthIndicator = 0;
	SQLRETURN r;
	r = SQLGetData(hstmt, col, SQL_C_DOUBLE, &value, sizeof(value), &lengthIndicator);
```

This will return the correct data for me

![image](https://user-images.githubusercontent.com/381660/203960549-c35c0f07-5110-49f8-b91b-9869db1b9784.png)


@jef-n do you build your own version of Qt for Windows with forked Qt code e.g is there a way for us to patch this?  If not we might have to raise it with Qt project and see if they can patch upstream.

**Comment by NathanW2** [comment]
@jef-n we migth not even need to patch full Qt as the ODBC stuff is done as a driver:


https://github.com/qt/qtbase/tree/32df595275f5d50ab4458620808f80121bb9c6a0/src/plugins/sqldrivers/odbc

Affected areas:

https://github.com/qt/qtbase/blob/32df595275f5d50ab4458620808f80121bb9c6a0/src/plugins/sqldrivers/odbc/qsql_odbc.cpp#L563

Is it possible to patch and build only that driver to ship with QGIS?   I'm just looking for options if getting a upstream patch is a slow process.

Looks like passing 0 for the buffer length here isn't supported in the default driver anymore (bug or not).  All other places that I have check pass `sizeof(value)` here.  Have check places like:

- pyodbc
- gdal

Which confirms what I have found above.

**Comment by jef-n** [comment]
Does replacing http://download.osgeo.org/osgeo4w/v2/x86_64/release/qt5/qt5-libs/qsqlodbc.dll help (or installing updating qt5-libs to test version 5.15.3-4)?

**Comment by NathanW2** [comment]
@jef-n getting a 403 on that link

**Comment by jef-n** [comment]
try again

**Comment by jef-n** [comment]
nice. 5.15.3-4 promoted to current.

**Comment by NathanW2** [comment]
@jef-n thanks for the super quick fix on that. Really appreciate it

Which QGIS builds will that make it into? Current LTR and latest?

**Comment by jef-n** [comment]
QGIS doesn't need to be rebuilt.

**Comment by TonyFMCMC** [comment]
> Roam will be using whatever driver that connection in QGIS was setup with, which is the detault one. If you update the connections in your project file it will fix those issues.

@NathanW2 I tried using ODBC Driver 17 in the Roam project file, and in QGIS it worked fine.  But when I opened the project file using Roam, it was fine until I tried to select a polygon when I got the following error:

> Traceback (most recent call last):

  File "C:\Users\Nathan\dev\Roam\src\roam\infodock.py", line 511, in generate_info
  File "C:\Users\Nathan\dev\Roam\src\roam\infodock.py", line 600, in results_from_query
  File "C:\Users\Nathan\dev\Roam\src\roam\dataaccess\database.py", line 55, in fromLayer
  File "C:\Users\Nathan\dev\Roam\src\roam\dataaccess\database.py", line 81, in connect
roam.dataaccess.database.DatabaseException: [Microsoft][ODBC SQL Server Driver][Shared Memory]SQL Server does not exist or access denied. [Microsoft][ODBC SQL Server Driver][Shared Memory]ConnectionOpen (Connect()). QODBC3: Unable to connect

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Nathan\dev\Roam\src\roam\infodock.py", line 366, in layerIndexChanged
  File "C:\Users\Nathan\dev\Roam\src\roam\infodock.py", line 451, in update
  File "C:\Users\Nathan\dev\Roam\src\roam\infodock.py", line 518, in generate_info
AttributeError: 'DatabaseException' object has no attribute 'message'

It seemed to me the code in the connect method of database.py might not have been set up for a datasource like:
<datasource>service='driver=ODBC Driver 17 for SQL Server;server=10.10.X.X;database=mydatabase;' user='user@my-azure-sql-server' password='my-password' estimatedmetadata=true srid=0 disableInvalidGeometryHandling='0' table="dbo"."AllAllocations" sql=</datasource>

**Comment by NathanW2** [comment]
@jef-n is it possible to get a new package/installer done for windows please?  The latest and LTR.   Would be good for people to grab installers and have the fix applied as it is causing a bit of grief for users.

**Comment by NathanW2** [comment]
@jef-n does  5.15.3-4 include the patched dll?   I grabbed it using the osgeo install but it still presents the bug but using the above patched dll works correctly.

**Comment by olegsbogdanovics** [comment]
> http://download.osgeo.org

thanks! it works!

**Comment by jef-n** [comment]
> @jef-n does 5.15.3-4 include the patched dll? I grabbed it using the osgeo install but it still presents the bug but using the above patched dll works correctly.

Of course it should have.  So I take it you didn't try before requesting new standalones...

**Comment by NathanW2** [comment]
I tried the new -2 standalones and installs via the osgeo4w installs just
before and the bug was still present.   Dropping the DLL into the folder
fixes the issue again.

So possible the build didn't include the patch correctly?

I will test again to double confirm

**Comment by jef-n** [comment]
qt-libs is updated.

**Comment by NathanW2** [comment]
@jef-n working with `qt5-libs-5.15.3-5` 

Tested via OSGeo installer.

Sorry about before I had only tested the drop in dll and not the full `qt5-libs-5.15.3-4` package when I had confirmed it worked before.  Was late at night and didn't even think to do it using the full package.

**Comment by jackgreengis** [comment]
FYI - Microsoft has identified that they have an issue and are working on a fix https://support.microsoft.com/en-us/topic/november-8-2022-kb5019959-os-builds-19042-2251-19043-2251-19044-2251-and-19045-2251-f65e0600-2135-4efd-a979-08d1df34dce8 

![image](https://user-images.githubusercontent.com/48906895/207203976-e073a8a0-bebe-4030-bf0e-399ee7e219ed.png)

**Comment by KymB577** [comment]
The latest January 10 Microsoft release KB5022282 seems to have fixed the issue with QGIS reading SQL tables for float types. 

sqlsrv32.dll. has been updated in this release.

https://support.microsoft.com/en-us/topic/january-10-2023-kb5022282-os-builds-19042-2486-19044-2486-and-19045-2486-9587e4e3-c2d7-48a6-86e2-8cd9146b47fd
