### ISSUE TITLE
Neither processing tools or plugin instalation work after installing QGIS

### ISSUE THREAD

**Issue by hectorsampi** [qgis/QGIS#50860]
### What is the bug or the crash?

I´ve been working one year with QGIS. After installing the new versions. 3.22 or 3.28 appreared.

Once I install QGIS, I realice neither vector, raster, or any other processing tool are available. In the eginning I thought I just had to available the plugin. However, I cannot install any plugin neither. There are only 4 plugin available: Geometry Checker, Grass, OfflineEditing and Topology Checker.  Once I open the Plugin window only 3  options appear: All, Installed, and Settings. Furthermore, If I click on settings the following message appears: "The settings on this tab are only applicable for Python Plugins. No python support detected, thus no settings available".
And finally, I have to report that python console isn´t working neither, even if I press Ctrl+alt+p.

I am using Windows 7. It could be the reason why this is not working

Thanks in advance.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/83606394/201204621-8c078b51-c36c-481b-a3a9-5c42ca6f16e1.png)

![image](https://user-images.githubusercontent.com/83606394/201204521-86aaa8be-e0a0-442e-9dd6-fc9a510df841.png)

### Versions

QGIS 3.22.2 or 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> I am using Windows 7. It could be the reason why this is not working

It IS the reason. So either you try with 3.20 or 3.18 (I can't remember the latest compatible) or you use the osgeo4w installer in advanced mode and add api-ms-win-core-path-HACK package in the process.

**Comment by nicogodet** [comment]
latest Win7 QGIS is 3.18.3 (.exe installer)

**Comment by DelazJ** [comment]
According to https://github.com/qgis/QGIS-Website/pull/1084#issuecomment-1311698629 the limitation should be removed in a couple of days and newer versions being available on windows 7 also.
