### ISSUE TITLE
Crash ID: [3525c58327e9ba63204641bf49a3d56ae772d4b6]

### ISSUE THREAD

**Issue by aura134** [qgis/QGIS#50877]
### What is the bug or the crash?

Crash ID: [3525c58327e9ba63204641bf49a3d56ae772d4b6]

Stack Trace

QMetaObject::cast :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QObject::qt_static_metacall :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgsProject::addMapLayer :
QgisApp::addSublayers :
QgisApp::addVectorLayersPrivate :
QgisApp::addVectorLayers :
QgisApp::qt_static_metacall :
QObject::qt_static_metacall :
QgsDataSourceManagerDialog::addVectorLayers :
QObject::qt_static_metacall :
QgsAbstractDataSourceWidget::addVectorLayers :
QgsProjectStorageGuiProvider::QgsProjectStorageGuiProvider :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :

QGIS Info
QGIS Version: 3.22.12-Bia?owie?a
QGIS code revision: b8534cb1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

bvb

### Versions

3.22.12

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you describe what you were doing ?
How to reproduce the crash ?

If the crash is reproducible, share a sample project and data so dev can reproduce and fix it.
