### ISSUE TITLE
Support for Ubuntu 22.04 Jammy is missing at https://qgis.org/ubuntugis

### ISSUE THREAD

**Issue by Schnarrschrecke** [qgis/QGIS#50874]
### Feature description

The repository [ubuntugis-unstable](https://qgis.org/ubuntugis) provides different QGIS releases for Ubuntu compiled with the Ubuntugis-unstable dependencies, but not for the latest Ubuntu LTS version 22.04. It would be very helpful, if 22.04/Jammy could be provided to work with the latest QGIS *and* GRASS version. Thank you!

**Comment by jef-n** [comment]
https://qgis.org/ubuntugis-ltr/dists/jammy
https://qgis.org/ubuntugis/dists/jammy

**Comment by Schnarrschrecke** [comment]
Thank you very much! This is very helpful for using QGIS.
