### ISSUE TITLE
Support for Ubuntu 22.04 Jammy is missing at ubuntugis-unstable

### ISSUE THREAD

**Issue by Schnarrschrecke** [qgis/QGIS#50871]
### Feature description

The repository ubuntugis-unstable provides different Ubuntu releases, but not the latest LTS version 22.04. It would be very helpful, if 22.04/Jammy could be provided to work with the latest QGIS *and* GRASS version. Thank you!

**Comment by jef-n** [comment]
We don't maintain the ubuntugis repository.  See https://launchpad.net/~ubuntugis for details.
