### ISSUE TITLE
Dependency issues with QGIS install on clean Ubuntu 22.04 install

### ISSUE THREAD

**Issue by paddleman** [qgis/QGIS#50878]
### What is the bug or the crash?

OS: Ubuntu 22.04 (Jammy)

QGIS (both 3.28 and the version  from the Canocial Software Store) will not install --- citing unmet dependencies.
 
--output from:  `sudo apt install qgis qgis-plugin-grass`

The following packages have unmet dependencies:
 qgis : Depends: libgdal28 (>= 1.11) but it is not installable
        Depends: libproj19 (>= 5.0.0) but it is not installable
        Depends: libqgis-3d3.28.0 but it is not going to be installed
        Depends: libqgis-analysis3.28.0 but it is not going to be installed
        Depends: libqgis-app3.28.0 but it is not going to be installed
        Depends: libqgis-core3.28.0 but it is not going to be installed
        Depends: libqgis-gui3.28.0 but it is not going to be installed
        Depends: python3-qgis (= 1:3.28.0+16bullseye) but it is not going to be installed
        Depends: qgis-providers (= 1:3.28.0+16bullseye) but it is not going to be installed
 qgis-plugin-grass : Depends: qgis-provider-grass (= 1:3.28.0+16bullseye) but it is not going to be installed
                     Depends: grass785 but it is not installable
                     Depends: libgdal28 (>= 1.11) but it is not installable
                     Depends: libqgis-app3.28.0 but it is not going to be installed
                     Depends: libqgis-core3.28.0 but it is not going to be installed
                     Depends: libqgis-gui3.28.0 but it is not going to be installed
                     Depends: libqgisgrass7-3.28.0 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.

This is on a brand new install of Ubuntu 22.04 --- with postgresql14 and postgis 3.3 installed --- and that is about it.

All help/fixes are appreciated.

Thanks.
DJ

### Steps to reproduce the issue

Followed instructions for Ubuntu installation from qgis.org

at the command prompt:

`sudo apt install qgis qgis-plugin-grass`

### Versions

QGIS 3.28.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jef-n** [comment]
Looks like your sources list is wrong - bullseye != jammy

**Comment by paddleman** [comment]
I am idiot.  Sorry for the bother.  I truly appreciate the help.
Thanks again.
DJ

**Comment by rogozinds** [comment]
I had the same trouble, just to give more context for others. The instructions from [here](https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu), provides an instruction to add a repository. But it lists instructions for Debian first. It's easy to miss it and add repository for a different OS (debian instead of Ubuntu). So when you add a debian repository for your ubuntu, the QGIS won't be installed.
That's what @jef-n means by "bullseye != jammy".
To fix the problem, remove debian entries from /etc/apt/sources.list.d/qgis.sources (or just remove the file completely), then do the following:
`
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ubuntugis/ppa
sudo apt-get -y install qgis 
`

**Comment by jef-n** [comment]
@rogozinds That way you won't get any qgis.org packages.

**Comment by jef-n** [comment]
There's a note right below qgis.sources pointing out that the Suite depends on your distribution.

**Comment by ArturoMendes** [comment]
> I had the same trouble, just to give more context for others. The instructions from [here](https://www.qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu), provides an instruction to add a repository. But it lists instructions for Debian first. It's easy to miss it and add repository for a different OS (debian instead of Ubuntu). So when you add a debian repository for your ubuntu, the QGIS won't be installed. That's what @jef-n means by "bullseye != jammy". To fix the problem, remove debian entries from /etc/apt/sources.list.d/qgis.sources (or just remove the file completely), then do the following:
> 
> ```
> sudo apt-get install python-software-properties
> sudo add-apt-repository ppa:ubuntugis/ppa
> sudo apt-get -y install qgis 
> ```

For me **I just had to edit the sources** as suggested by @jef-n answer so the `Suites` matched my distribution which I got by typing `lsb_release -a` under `Codename`, sample:

Types: deb deb-src
URIs: https://qgis.org/debian-ltr
Suites: jammy
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg

**Comment by xgirouxb** [comment]
I'm also getting a collection of similar errors on install, even though I'm using the proper release for the "Suites". Specifically, when I try to install via either the ubuntugis or ubuntugis-ltr repos: 

```
Types: deb deb-src  
URIs: https://qgis.org/ubuntugis-ltr  
Suites: jammy  
Architectures: amd64  
Components: main  
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
```


I get:

```
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help resolve the situation:

The following packages have unmet dependencies:
 qgis : Depends: libgdal32 (>= 1.11) but it is not installable
        Depends: libproj25 (>= 5.0.0) but it is not installable
        Depends: libqgis-3d3.28.4 but it is not going to be installed
        Depends: libqgis-analysis3.28.4 but it is not going to be installed
        Depends: libqgis-app3.28.4 but it is not going to be installed
        Depends: libqgis-core3.28.4 but it is not going to be installed
        Depends: libqgis-gui3.28.4 but it is not going to be installed
        Depends: python3-qgis (= 1:3.28.4+36jammy-ubuntugis) but it is not going to be installed
        Depends: qgis-providers (= 1:3.28.4+36jammy-ubuntugis) but it is not going to be installed
 qgis-plugin-grass : Depends: qgis-provider-grass (= 1:3.28.4+36jammy-ubuntugis) but it is not going to be installed
                     Depends: grass820 but it is not installable
                     Depends: libgdal32 (>= 1.11) but it is not installable
                     Depends: libqgis-app3.28.4 but it is not going to be installed
                     Depends: libqgis-core3.28.4 but it is not going to be installed
                     Depends: libqgis-gui3.28.4 but it is not going to be installed
                     Depends: libqgisgrass8-3.28.4 but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

As stated on the install page:
> For Ubuntu we also used to have extra packages in a separate repository that are based on [ubuntugis](https://launchpad.net/~ubuntugis), which held more uptodate versions of other GIS packages than Ubuntu itself for LTS versions. If you want those you also need to include ubuntugis-unstable ppa in your /etc/apt/sources.list.d/qgis.list file (see [ubuntugis documentation](https://trac.osgeo.org/ubuntugis/wiki/UbuntuGISRepository)).

Yet @jef-n states here that this approach wouldn't use the packages from qgis.org

If I change `URIs` to `https://qgis.org/ubuntu-ltr` or `https://qgis.org/ubuntu`, then no dependency errors are encountered.

What is the correct approach for ubuntugis packages?

**Comment by xgirouxb** [comment]
I've resubmitted this as a distinct issue given it was not directly related to `ubuntugis-ltr`. See https://github.com/qgis/QGIS/issues/52440#issue-1646717576

**Comment by parisa-hr** [comment]
@xgirouxb  I have this problem too, what should i do? or better to ask what did you do?

**Comment by TimNmn** [comment]
Hi @parisa-hr, I had the same prob. Editing the Suites in qgis.sources did bring me the errors. I then also changed the URIs to qgis.org/ubuntu instead of Debian. That did the job.

**Comment by parisa-hr** [comment]
> Hi @parisa-hr, I had the same prob. Editing the Suites in qgis.sources did bring me the errors. I then also changed the URIs to qgis.org/ubuntu instead of Debian. That did the job.  

Hi
I changed my OS to Fedora.
I didn't understand what should I do to fix it.
I am not sure that this was issue for Ubuntu because it works there and after some install and Uninstall packages I had too many issues.
