### ISSUE TITLE
The 'Add feature' popup windows shifts downwards each time a new feature is added

### ISSUE THREAD

**Issue by andrew-plowright** [qgis/QGIS#50886]
### What is the bug or the crash?

When editing vector data and using the 'Add feature' tool, a pop-up window appears in which you can enter attributes for the new feature.

Every time a new feature is added and that pop-up reappears, it has shifted downwards. This is an issue since it eventually leaves the screen and must be dragged back. This disrupts workflows that involve adding hundreds of features.

### Steps to reproduce the issue

1. Create a new vector layer
2. Activate 'Toggle Editing' (yellow pencil)
3. Click on Add Feature (second button to the right of the yellow pencil)
4. Create a few new features
5. Observe the pop-up window shifting downward

### Versions

QGIS version
3.28.0-Firenze
QGIS code revision
ed3ad0430f3
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.5.2
Running against GDAL/OGR
3.5.3
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/44050
