### ISSUE TITLE
QGIS crash on Opensuse 15.4 - H5::DataSpaceIException

### ISSUE THREAD

**Issue by jack-sprat** [qgis/QGIS#50897]
### What is the bug or the crash?

QGIS fails to start.

```
terminate called after throwing an instance of 'H5::DataSpaceIException'
Aborted (core dumped)
```

### Steps to reproduce the issue

Fresh upgrade of OpenSUSE from 15.3 to 15.4
zypper dup
QGIS installed from SLE-15-SP4 backports

### Versions

3.18.3 (from Yast2 Versions tab - QGIS version dialogue is not available)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap. (this is latest version built for OpenSuse)

### New profile

- [ ] I tried with a new QGIS profile (not possible w/o accessing QGIS)

### Additional context

I had the same issue with OpenSUSE 15.3 after some recent additional software installation - I'd hoped that a full system upgrade might sort the H5 issue. I was wrong.

**Comment by nicogodet** [comment]
> 3.18.3 (from Yast2 Versions tab - QGIS version dialogue is not available)

This version is EOL. Please update to 3.22.12 or 3.28.0.

Try with a new profile too.

**Comment by jack-sprat** [comment]
Yup - I thought you'd say that. Hence, why I'm trying to figure out how to build from source, as OpenSUSE has nothing more recent than 3.18 (other than in Tumbleweed, which comes with a whole bunch of other issues)

...and how do I select  a new profile when QGIS doesn't start? (i.e. when I can't do this: https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).

**Comment by jack-sprat** [comment]
Hmmm... failed with new profile (which I suspected as it also failed on 15.3 after having worked for a couple of years).

Now I see that build instructions are for Debian/Ubuntu or Fedora (https://github.com/qgis/QGIS/blob/release-3_22/INSTALL.md) - this is going to be an uphill struggle... and I'm not even using HDF5 that I know of. Sigh.

Here we go...
