### ISSUE TITLE
qGIS Crash on Exit

### ISSUE THREAD

**Issue by Hendrik62** [qgis/QGIS#50900]
## User Feedback

This crash allways occurs when I close qGIS.

## Report Details

**Crash ID**: [58873961325ad0aa6797683782de88e974aafc02](https://github.com/qgis/QGIS/search?q=58873961325ad0aa6797683782de88e974aafc02&type=Issues)

**Stack Trace**
<pre>
QThread::currentThread :
QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsProcessingRegistry::removeProvider :
QgsProcessingRegistry::~QgsProcessingRegistry :
QgsProcessingRegistry::~QgsProcessingRegistry :
QgsValidityCheckResult::QgsValidityCheckResult :
QgsApplication::~QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Exit qGIS

### Versions

QGIS Version: 3.20.0-Odense
QGIS code revision: decaadbb31
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> QGIS Version: 3.20.0-Odense

This version is EOL. Update to 3.22.12 or 3.28.0.

Try with a new profile too.

**Comment by Hendrik62** [comment]
Can you still help further?

**Comment by nicogodet** [comment]
3.8.0 is a downgrade. Not a update 
You need 3.28.0 or 3.22.12

**Comment by Hendrik62** [comment]
Hi there.  I upgraded to 3.22.12 but still have the same issue.  Can you help?
Thank-you so much!



## User Feedback

helo

## Report Details

**Crash ID**: [58873961325ad0aa6797683782de88e974aafc02](https://github.com/qgis/QGIS/search?q=58873961325ad0aa6797683782de88e974aafc02&type=Issues)


**Stack Trace**
<pre>
QThread::currentThread :
QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsProcessingRegistry::removeProvider :
QgsProcessingRegistry::~QgsProcessingRegistry :
QgsProcessingRegistry::~QgsProcessingRegistry :
QgsValidityCheckResult::QgsValidityCheckResult :
QgsApplication::~QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>


**QGIS Info**
QGIS Version: 3.22.12-Bia?owie?a
QGIS code revision: b8534cb1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

________________________________
