### ISSUE TITLE
Option to print PDF without (white paper) background object

### ISSUE THREAD

**Issue by Intuos5** [qgis/QGIS#50916]
### Feature description

I would like to be able to export (pdf) files from any of my maps without the white paper being part of the file (i.e. a white rectangle). The reason for this is that this allows me to link heavy files directly in a vector editor of choice without having to edit the individual PDFs. Linking is beneficial so I can quickly iterate over the files, make changes if necessary and reprint, without having to re-delete the background object. With the white background, it becomes impossible to layer the files properly.

**Comment by cxcandid** [comment]
If you create your PDF from a layout, you can remove the background in the `Page Properties...` dialog. To open the dialog you have to right click into the layout page. Remove the fill style from the background symbol settings. And additionally you need to remove the background of your map item in the item properties dialog.
