### ISSUE TITLE
QGIS 3.28 RC doesn't recognize LAZ 

### ISSUE THREAD

**Issue by rjhale1971** [qgis/QGIS#50923]
### What is the bug or the crash?

I am running QGIS 3.28.0 (just upgraded to 3.28 nightly) and I can't view LAZ files on Ubuntu  22.10 

### Steps to reproduce the issue

1. Download 3.28.0 Release Candidate. 
2. If you use the Data Source Manager to add LAZ files you get get no error and no LAZ file. 
3. Drag and Drop a LAZ file into QGIS and you get the following error (screenshot) 

![Uploading Screenshot from 2022-11-17 14-48-03.png…]()

### Versions

3.28.0 Release candidate on Ubuntu 22.11 
3.28.X Nightly Build on Ubuntu 22.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Pdal was completely removed from Ubuntu/debian repositories for political reasons. You'll need to build your own if you want laz support on Ubuntu now 😱

**Comment by nyalldawson** [comment]
See https://lists.debian.org/debian-gis/2022/02/msg00004.html

**Comment by rjhale1971** [comment]
Holy. Crap. I didn't know that.

**Comment by nyalldawson** [comment]
Yep -- far from an ideal situation all round!

**Comment by rjhale1971** [comment]
Holy.Crap.
