### ISSUE TITLE
3.28.0 regression with WFS layers not showing any data

### ISSUE THREAD

**Issue by kommen** [qgis/QGIS#50935]
### What is the bug or the crash?

A project's WFS layer which displays fine in 3.26.3 doesn't display any data when opened with 3.28.0

### Steps to reproduce the issue

1) open this minimal sample project: [wfsbug.qgz.zip](https://github.com/qgis/QGIS/files/10044550/wfsbug.qgz.zip)
2) try do display the data of the `Radabstellanlagen` layer in QGIS 3.28.0.

The features of that layer are shown in the Attribute Table, but not on the map. The layer doesn't even have a check box in the Layers panel to show it.

This works fine when opened with QGIS 3.26.3.

### Versions

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.0
  |   |   |  
Active Python plugins
QuickOSM | 2.1.1
vector_tiles_reader | 3.2.2
quick_map_services | 0.19.32
splitmultipart | 1.0.0
GeoCoding | 2.18
qgis2web | 3.16.0
mmqgis | 2021.9.10
StreetView | 3.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
qgiscloud | 3.7.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Note: this is my first QGIS bug report, please let me know if the report is incorrect or incomplete in any way.

**Comment by pathmapper** [comment]
This regressed in https://github.com/qgis/QGIS/commit/ec96b494901006b01df7a3c324415aa7189a2e40.

The issue is, that with this change for WFS 1.0 there was no GetFeature on one feature anymore to guess the geometry type if we do not know the exact geometry type from DescribeFeatureType:

https://github.com/qgis/QGIS/blob/5dc2ab95746f554365bcbc1d591188f6839e0011/src/providers/wfs/qgswfsprovider.cpp#L184

Possible fix in #50943.
