### ISSUE TITLE
Displaying wrong OS in Help/About

### ISSUE THREAD

**Issue by dek0n** [qgis/QGIS#50945]
### What is the bug or the crash?

I've opened Help/About in QGIS and I am not sure if I am right, but is it displaying MY Operating System? Because, it is written there "Windows 10 2009 edition", but I definitly have Windows 11 Pro.

### Steps to reproduce the issue

In the QGIS Help menu -> About

### Versions

QGIS version
3.28.0-Firenze
QGIS code revision
ed3ad0430f3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
CalculateGeometry
0.6.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
It seems to me this is a Qt issue. QGIS uses `QSysInfo::prettyProductName()` Qt function

https://github.com/qgis/QGIS/blob/5eadfee47303b0e8821648f04e88e697369ad93a/src/app/qgisapp.cpp#L5463-L5464

which is affected by a bug https://bugreports.qt.io/browse/QTBUG-99225 that was allegedly fixed for Qt 5.15.8 and 6.2.

**Comment by agiudiceandrea** [comment]
QGIS distributed by OSGeo4W currently uses kde Qt 5.15.13.
