### ISSUE TITLE
QGIS 3.26 crashes when performing "split with line".

### ISSUE THREAD

**Issue by makend119** [qgis/QGIS#50948]
### What is the bug or the crash?

Crash when executing "Split by Line".
It occurs when a specific feature is included, but the cause is unknown.
It occurs when you select the feature with id=97 in the L1 layer of the attached file and divide it by L2. Everything is fine except for that line.
[L1-L2.zip](https://github.com/qgis/QGIS/files/10053543/L1-L2.zip)
![disp](https://user-images.githubusercontent.com/38060287/202970705-62053228-d0d9-470e-931d-3ae95953943a.png)

### Steps to reproduce the issue

1. Unzip the Zip file and open L1 and L2 with QGIS.
2. Open the Processing Toolbox and run "Split by Line" in Vector Overlay.
3. Select L1 for the input layer and L2 for the cutting line layer.
4. Execute the command.

### Versions

QGISバージョン
3.26.3-Buenos Aires
QGISコードリビジョン
65e4edfdada
Qtバージョン
5.15.3
Pythonバージョン
3.9.5
GDAL/OGRバージョン
3.5.1
PROJバージョン
9.1.0
EPSG Registry databaseバージョン
v10.041 (2021-12-03)
GEOSバージョン
3.10.3-CAPI-1.16.1
SQLiteバージョン
3.38.1
PDALバージョン
2.4.3
PostgreSQLクライアントバージョン
unknown
SpatiaLiteバージョン
5.0.1
QWTバージョン
6.1.6
QScintilla2バージョン
2.13.1
OSバージョン
Windows 10 Version 2009

Active pythonプラグイン
autoSaver
2.6
contour
2.0.10
dissolve_related
1.2
mmqgis
2021.9.10
networks
2.7.3
openlayers_plugin
2.0.0
QNEAT3
1.0.4
timemanager
3.6
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you try on 3.28.1 ?
3.26 is EOL.

Try with a new profile too.

If it still happens, share the data.

**Comment by uclaros** [comment]
This is also true on master and not specific to the Split with Lines algorithm.
Here's a nice failing test:

```python
line = QgsGeometry.fromWkt("LineString ( -63294.10966012725839391 -79156.27234554117603693, -63290.25259721937618451 -79162.78533450335089583, -63290.25259721936890855 -79162.78533450335089583)")
split = [QgsPointXY(-63290.25259721936890855, -79165.28533450335089583), QgsPointXY(-63290.25259721936890855, -79160.28533450335089583)]
line.splitGeometry(split,False)
```

**Comment by nicogodet** [comment]
Can't confirm on 3.22.12

```python
>>> line = QgsGeometry.fromWkt("LineString ( -63294.10966012725839391 -79156.27234554117603693, -63290.25259721937618451 -79162.78533450335089583, -63290.25259721936890855 -79162.78533450335089583)")
>>> split = [QgsPointXY(-63290.25259721936890855, -79165.28533450335089583), QgsPointXY(-63290.25259721936890855, -79160.28533450335089583)]
>>> line.splitGeometry(split,False)
(<GeometryOperationResult.Success: 0>, [], [])
```

**Comment by uclaros** [comment]
Yes, that's expected, the two lines share their last vertex, so splitting shouldn't produce any new geometries

**Comment by makend119** [comment]
Dear  Nicogode,  Uclaros
Thank you very much.
solved.
I didn't realize there was a zero length segment mixed in.
Once I removed the indicated line, it worked fine.

**Comment by uclaros** [comment]
I'm keeping this open, as QGIS should not crash.

**Comment by makend119** [comment]
It seems there was another problem.
When I tried using some of the sample data, it was completed successfully, but when I used all the data, it crashed.
I'll try some more. I'll let you know how it goes. 
If you have a point to build, I would appreciate your advice.
3.28.0 is crashing as well.

**Comment by uclaros** [comment]
@makend119 try using the _Remove duplicate vertices_ algorithm on your data. If that doesn't fix the crash, could you share the data that causes it?

**Comment by makend119** [comment]
I created the attached model with a graphical modeler.
I took your advice and made it work.
It may contain inappropriate code, but please ignore it.
Since the character code is UTF-8, garbled characters may occur.

[Split Lines at Points4b.zip](https://github.com/qgis/QGIS/files/10080702/Split.Lines.at.Points4b.zip)

**Comment by uclaros** [comment]
Your model performs _Delete duplicate geometries_ before splitting. Add a _Remove duplicate vertices_ there too in order to avoid crashing, until there is a proper fix in QGIS.

**Comment by makend119** [comment]
Thank you for giving me good advice.
I decided to include "Delete duplicate geometries" before splitting

**Comment by obrl-soil** [comment]
Not sure if this is related, but I'm finding 3.28.2 crashes if I go to split a line and accidentally have more than one line selected. GPKG linestring source file.
