### ISSUE TITLE
Crash App

### ISSUE THREAD

**Issue by CafarellaL** [qgis/QGIS#50953]
### What is the bug or the crash?

Crash ID: [ea5189dc03e3a6336b57664445950cc54fbd5c97](https://github.com/qgis/QGIS/search?q=ea5189dc03e3a6336b57664445950cc54fbd5c97&type=Issues)

Stack Trace

QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::updateEditorGeometries :
QAbstractItemView::updateGeometries :
QTableView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTableView::doItemsLayout :
QTableView::visualRect :
QAbstractItemView::keyPressEvent :
QAbstractItemView::focusNextPrevChild :
QWidget::focusNextPrevChild :
QWidget::focusNextPrevChild :
QWidgetPrivate::hide_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QAbstractItemView::rowsAboutToBeRemoved :
QObject::qt_static_metacall :
QAbstractItemModel::beginRemoveRows :
QSortFilterProxyModel::removeRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::beginRemoveRows :
QgsAttributeTableModel::removeRows :
QgsAttributeTableModel::featuresDeleted :
QObject::qt_static_metacall :
QgsVectorLayer::featuresDeleted :
QgsVectorLayer::onFeatureDeleted :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::featureDeleted :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveEdits :
QgsAttributeTableDialog::mActionSaveEdits_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: c2723178
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Query point info or copy and move point, ecc...

### Versions

QGIS Version: 3.22.5-Biatowieza

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> QGIS Version: 3.22.5-Bia?owie?a

is a bit out-dated, could you try on 3.22.13 (or 3.28.1)

Try with a new profile too.

If it still persists, share a sample project and detailed steps to reproduce.

**Comment by CafarellaL** [comment]
Thank you very much for your reply. Unfortunately the crash also occurs with version 3.28 Florence.

**Comment by CafarellaL** [comment]
New Error:

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003350 (most recent call first):



Stack Trace


QSortFilterProxyModel::parent :
QModelIndex::parent :
QTableView::visualRect :
QAbstractItemView::updateEditorGeometries :
QAbstractItemView::updateGeometries :
QTableView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTableView::doItemsLayout :
QAbstractItemView::timerEvent :
QObject::event :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.0-Firenze
QGIS code revision: ed3ad0430f3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by CafarellaL** [comment]
thanks for pointing me to the correct channel

**Comment by nicogodet** [comment]
Closing as not a QGIS issue.
