### ISSUE TITLE
VECINO NATURAL

### ISSUE THREAD

**Issue by EDWIN1522** [qgis/QGIS#50958]
### What is the bug or the crash?

al utilizar la herramienta " vacino natural", presenta el siguiente error al momento de compilar:  (SAGA version 7.8.2 is not officially supported - algorithms may encounter issues)
![error](https://user-images.githubusercontent.com/118789409/203217896-dc86e2b5-bbfa-4489-bdfc-58548b62f182.jpg)

### Steps to reproduce the issue

layer / add layer / add vector layer  / processing toolbox  / natural neighbour  // RUN

### Versions

![image](https://user-images.githubusercontent.com/118789409/203218451-b43f76c1-24c7-48dc-a2ac-3a33aa53e4e5.png)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
The SAGA support has now been removed from QGIS, and is no longer maintained. Please use the 3rd party "SAGA Netx Gen" plugin instead.
