### ISSUE TITLE
EPSG 3125 Offset

### ISSUE THREAD

**Issue by joesungajr** [qgis/QGIS#50956]
### What is the bug or the crash?

PRS 92 Zone 5 (And I think this goes for the other zones), is offset.

### Steps to reproduce the issue

1. Open a vector in any coordinate system.
2. Export the vector to PRS 92 Zone 5 (EPSG 3125)
3. The exported vector will plot few hundred meters northwest.

### Versions

QGIS version
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
numericalDigitize
0.4.7
profiletool
4.2.2
Qgis2threejs
2.6
ViewshedAnalysis
1.7
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@joesungajr, I cannot reproduce the issue using the latest QGIS 3.28 and 3.22 versions. Could you please try using the latest QGIS versions and a new QGIS user profile and provide a sample layer and detailed instructions to reproduce the issue?

**Comment by joesungajr** [comment]
Sorry I meant to say when exporting to Mapinfo Tab in PRS 92 Zone 5 (EPSG 3125).

In the image, the original shape file (black line) is in Lon/Lat WGS84.

Exported to PRS92 Zone 5 shape file (pink line, sharing the same space as the black line [original file]).

Exported to PRS92 Zone 5 mapinfo tab file (white line, offset by about 167 meters)

![image](https://user-images.githubusercontent.com/47583247/204177138-766f4667-32eb-489b-9bda-edd371a94163.png)

**Comment by agiudiceandrea** [comment]
@joesungajr, this is a Mapinfo Tab specific issue.
Have you checked what it the CRS assigned by QGIS to the created and imported Mapinfo Tab layer? It seems to me it is an incorrect CRS. As a workaround, you can fix the issue just assigning (from the layer Properties - Source - Assigned Coordinate Reference System) the correct CRS to such Mapinfo Tab layer.

Maybe @rouault have a clue if this is a QGIS or a GDAL issue: it occurs also with the latest QGIS 3.28.1 / GDAL 3.6.0.

**Comment by rouault** [comment]
GDAL fix queued in https://github.com/OSGeo/gdal/pull/6813
