### ISSUE TITLE
Silent crash when trying to Insert or Edit Expression in a legend for a raster

### ISSUE THREAD

**Issue by JanChytry** [qgis/QGIS#50975]
### What is the bug or the crash?

I wanted to make a simple map of a categorized TIFF raster (10 categories). When in Print Layout, I wanted to create an expression for one of the legend symbols of the raster. When clicking on the button `Insert or Edit Expression...`, QGIS crashed silently. I could not reproduce the issue for the second time with very similar conditions (except for what I've lost what was unsaved). 

### Steps to reproduce the issue

Add a TIFF, make it categorized in `Styling`. Create a `Print Layout`, add map with this raster and create legend. Disable `Auto Update` for the legend, access one of the categorized items of the raster and, under label in a text area, click on `Insert or Edit Expression...`. Alternatively, try to just play around with the label in the text area, it might have crashed already because of that, I might have clicked here and there too fast.

### Versions

QGIS 3.28.1 Firenze
(all functionalities dealt with were native)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
It does not crash for me on master/linux.
