### ISSUE TITLE
Exporting 3D scene to .obj stores the same feature 16x

### ISSUE THREAD

**Issue by raymondnijssen** [qgis/QGIS#50971]
### What is the bug or the crash?

I made a 3D scene containing a layer with only one polygon. When exporting this to .obj (and .mtl) the obj contains the same 3D-object 16 times.

![image](https://user-images.githubusercontent.com/681851/203500478-eb31958f-0485-4423-9709-e649b084116d.png)

### Steps to reproduce the issue

* Create a polygon scratch layer
* Draw one polygon and save
* Set layer's 3D View settings to height: 0, extrude: 20
* Open 3D View
* Save scene with default options

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.29.0-Master | QGIS code revision | 5fe715a6c3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
BGTImport | 3.16
ImaerPlugin | version 3.2.0
pdokservicesplugin | 4.1.2
grassprovider | 2.12.99
MetaSearch | 0.3.6
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
StreetView | 3.2

</body></html>QGIS version
3.29.0-Master
QGIS code revision
[5fe715a6c3](https://github.com/qgis/QGIS/commit/5fe715a6c3)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
BGTImport
3.16
ImaerPlugin
version 3.2.0
pdokservicesplugin
4.1.2
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
StreetView
3.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by benoitdm-oslandia** [comment]
I had created a fix but the exported objects will always be grouped by quadtree node. You will not be able to have every single feature.

**Comment by AbdelghaniTamort** [comment]
> I had created a fix but the exported objects will always be grouped by quadtree node. You will not be able to have every single feature.

Is there a way to separate the grouped features post-export ?
