### ISSUE TITLE
Vertex Tool not moving vertices on MSSQL Server layer

### ISSUE THREAD

**Issue by MimiBeto** [qgis/QGIS#50987]
### What is the bug or the crash?

Hi,

We are using QGIS 3.28.1-Firenze

We load our layers from SQL server. One of the polygon layers is all of a sudden causing problems. It was ok yesterday, this morning our PCs were restarted and now we are unable to move vertices in one of the polygon layers. We can move vertices in other layers but not this one. We copied the SQL layer to a local drive and loaded it into QGIS and this local layer is editable and we can move the vertices. We have also copied a feature and moved it to temporary scratch layer and we can edit that polygon. We checked the projections and cant find an issue. 
No idea what is going on, we haven't changed anything, it was fine last night and not working today after the PCs were restarted. 

Any ideas?

Thanks!

### Steps to reproduce the issue

When we click Toggle Editing, then Vertex tool and we go to the feature in that layer a blue loading bar appears at the bottom of the QGIS screen

### Versions

QGIS 3.28.1-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Linked to https://github.com/qgis/QGIS/issues/50865 ?

**Comment by MimiBeto** [comment]
Thanks, will check

**Comment by nicogodet** [comment]
@MimiBeto a patch has been deployed on OSGeo. See linked issue.
could you try and see if it fixes this issue ?
