### ISSUE TITLE
OAuth 2 authentication for Cloud Optimized GeoTIFF (COG)

### ISSUE THREAD

**Issue by drnextgis** [qgis/QGIS#50999]
### What is the bug or the crash?

OAuth 2 authentication configuration doesn't work for COG rasters. The same configuration works fine for WMS and WFS services.

![image](https://user-images.githubusercontent.com/866124/203858699-60fc78b1-a18c-4297-b283-f5340c3a1a76.png)
![image](https://user-images.githubusercontent.com/866124/203859524-d7ae0efc-1ac7-468e-a262-363416ccce6c.png)

### Steps to reproduce the issue

1. Put COG behind OAuth 2 authentication
2. Create corresponding auth configuration in QGIS (tested with Resource Owner grant flow)
3. Layer -> Add Layer -> Add Raster Layer -> Protocol
4. Add URL to the URI field
5. Select needed auth configuration
6. Press Add button
7. See error: `Unsupported Data Source: /vsicurl/http://***/api/resource/14154/cog authcfg='847js0s' is not a supported raster data source`

### Versions

3.26.3-Buenos Aires

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
This was never implemented, I believe the only supported auth method for GDAL rasters is "Basic". From a QGIS perspective, raster layers can be handled by different providers, PostGIS and WMS support all QGIS auth methods but GDAL only supports Basic. 

The bug here is that the auth configuration should not show  unsupported methods.

**Comment by drnextgis** [comment]
Fair enough @elpaso. Thanks for the fix!

**Comment by drnextgis** [comment]
@rouault I'm wondering what do you think would be the better place for that functionality: QGIS or GDAL?

**Comment by rouault** [comment]
> @rouault I'm wondering what do you think would be the better place for that functionality (adding OAuth2 support for `/vsicurl` files): QGIS or GDAL?

complicated story.

There is a way of plugging an alternate network layer than cURL in GDAL for the CPLHTTPFetch() function: https://github.com/OSGeo/gdal/blob/master/port/cpl_http.h#L116
CPLHTTPFetch() is used by a number of OGR network-based drivers, like ElasticSearch, and QGIS make use of it per https://github.com/qgis/QGIS/blob/master/src/core/qgscplhttpfetchoverrider.cpp. So you can already use QGIS OAuth2 with a OGR ElasticSearch connection.

However /vsicurl/ and its brothers /vsis3/ etc use directly the cURL API, and not CPLHTTPFetch(). It should probably be possible to modify /vsicurl/ to use the pluggin network API, or an extended form of it, so QGIS authentication can be used, but there's "a bit" of work to do so.
GDAL itself has some minimum support for OAuth2 for the /vsigs/ network file system, but the issue with OAuth2 is that some variant of it involve user interaction through a browser, so they cannot be really supported through GDAL, and thus re-using QGIS authentication would be ideal.

**Comment by drnextgis** [comment]
Many thanks for the prompt reply!

**Comment by jbp35** [comment]
> However /vsicurl/ and its brothers /vsis3/ etc use directly the cURL API, and not CPLHTTPFetch(). It should probably be possible to modify /vsicurl/ to use the pluggin network API, or an extended form of it, so QGIS authentication can be used, but there's "a bit" of work to do so.

I just faced the same issue while trying to use COG on s3 using oauth2. After looking at gdal documentation, I found that it is possible to pass configuration options in the vsicurl command. 

> Starting with GDAL 2.3, options can be passed in the filename with the following syntax: /vsicurl?[option_i=val_i&]*url=http://... where each option name and value (including the value of "url") is URL-encoded. Currently supported options are:

I am wondering if it would be possible to pass the oauth token obtained by qgis using this mechanism:
/vsicurl?[GDAL_HTTP_HEADERS=qgis_token_header: qgis_token]*url=http://http://***/api/resource/14154/cog
