### ISSUE TITLE
Saving workspace in 3.28 causes style to reset in some older version

### ISSUE THREAD

**Issue by hizperion** [qgis/QGIS#50991]
### What is the bug or the crash?

We have a shared workspace used by some users. Users saving the workspace using latest version (3.28, not sure if this occur in older version too) causes other user opening the workspace (tested in 3.14) has the style reset to blue colour.

Workspace saved in 3.28 (workspace created in 3.14)
![image](https://user-images.githubusercontent.com/9959241/203665380-cc568bb3-94bc-482d-982f-27ed34eb5fe3.png)

Workspace reopened in 3.14
![image](https://user-images.githubusercontent.com/9959241/203665323-6b3380ad-b3f3-4d79-bb9a-6f445e711c9a.png)

### Steps to reproduce the issue

1. Create and save a workspace using multiple colour for polygon layer in QGIS 3.14
2. Open the same workspace in QGIS 3.28, do some changes and save the workspace
3. Reopen the same workspace in QGIS 3.14, check if the colours still maintain same

### Versions

QGIS version
4.28.1-Firenze
QGIS code revision
fde3b8fbb8c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is expected -- QGIS projects saved in newer versions will not be losslessly compatible with older QGIS releases. That's why you get the warning messages when loading them.
