### ISSUE TITLE
[Version 3.28.] Georeferencer is Missing

### ISSUE THREAD

**Issue by Foskopolitano** [qgis/QGIS#51016]
### What is the bug or the crash?

Hello everyone!
I'm a new geographer here in Github and I like to be always up to date with updates and today, when I trying to georeference a raster with QGis 3.28. from my laptop, I noticed that in the raster tab does not appear the Georeferencing tool.

I have been about 30 minutes looking for it, if I had it deactivated or it had become an add-on (which would be rare), even looking at tutorials if there was any missing link in the process that I did not know. It has given me to open the tower computer that has QGis 3.18 and it appears.

So, I come to report this error, that the georeferencing tool is not in the raster tab of Qgis 3.28.

### Steps to reproduce the issue

Version 3.28. (W11: it's in spanish version)
![imagen_2022-11-25_204537614](https://user-images.githubusercontent.com/119077070/204049126-498389f5-58cd-4c75-8c47-55de22f44ee0.png)

Version 3.18. [W10: it's in spanish version)![BDF8E2E8CBE44453A929C0E2D28CFB62](https://user-images.githubusercontent.com/119077070/204049236-592e93cb-6bd3-4f3b-be8a-80f940493f19.png)

### Versions

3.28. and 3.18.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It has been moved to "Layers" menu.

**Comment by 54188145200000** [comment]
我找你找的好苦啊
