### ISSUE TITLE
Elevation Profile: Multiple Elevation Profile windows

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#51030]
### Feature description

The Elevation Profile is an fine tool for viewing geological models with several subsurface layers. It would be nice if you could have several Elevation Profile, where each Profile Windows. It would require that on each profile, you can select a table with profiles and an rowid or profilename for which profile line to use. 

### Additional context

Right now there seems to be a bug, showing multiple Profile Windows, only the first one is rendering a profile, the rest stay blank, which can be confusing if the dialogs stack on top of each other in an docked profile window.

**Comment by nicogodet** [comment]
I can render multiple window here
![image](https://user-images.githubusercontent.com/39594821/204283827-eb6bc64f-e871-4a18-86ec-b4ed48d0fe8b.png)

**Comment by Jakob-Lanstorp** [comment]
Ok, found my mistake, one needs to actively press the Capture Curve button, which then toggles on the other profiles, I thought it was enough with just having the profile window active. This request / issue can be closed.
