### ISSUE TITLE
QGIS server

### ISSUE THREAD

**Issue by Accuracy-Global** [qgis/QGIS#51048]
### What is the bug or the crash?

Hi team,

we have already the QGIS Desktop version with windows and working on it! And now we are trying to install the QGIS server version.

Is the Qgis server and qgis desktop both are different? if yes how to install qgis server version can you please help me with link?

### Steps to reproduce the issue

Hi team,

we have already the QGIS Desktop version with windows and working on it! And now we are trying to install the QGIS server version.

Is the Qgis server and qgis desktop both are different? if yes how to install qgis server version can you please help me with link?

### Versions

3.24

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
See https://github.com/qgis/QGIS-Documentation/issues/7902#issuecomment-1330148958
