### ISSUE TITLE
"Not responding" once I open the Plugins manager window

### ISSUE THREAD

**Issue by loongfee** [qgis/QGIS#51058]
### What is the bug or the crash?

Once I clicked the "Manage and Install Plugins..." menu, QGIS became "not responding".

![image](https://user-images.githubusercontent.com/1845667/204666896-713208bf-6286-4aa4-b0f1-3a648c4b2d43.png)

### Steps to reproduce the issue

1. Go to "Plugins"
2. Click on "Manage and Install Plugins..."

### Versions

QGIS version
3.22.13-Białowieża
QGIS code revision
02ff117c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

I have tried to reinstall QGIS of different versions and to delete the QGIS folder in "C:\Users\*\AppData\Roaming", but the issue still exists.

**Comment by alexbruy** [comment]
Looks like a local issue. Are you behind proxy or using VPN?
