### ISSUE TITLE
QGIS lockup on identify of features in many MSSQL database layers, since Windows update kb5019959

### ISSUE THREAD

**Issue by andrew-glos** [qgis/QGIS#51053]
### What is the bug or the crash?

QGIS locks up (hangs) when Identifying a feature in an MSSQL layer.

This seems to be a problem handling "float" fields, and has been happening since a recent Windows update (KB5019959 on Windows 10 with QGIS 3,22,13, or kb5020013/kb5020000 on Windows Server 2008 R2 with QGIS 3.16.11)

Opening attribute tables will also either hang or show only partial data.

Using a "float" field in a data defined override in label positioning causes labelling to fail (Ordnance Survey MasterMap text)

Zoom to layer doesn't work for any MSSQL layer.

### Steps to reproduce the issue

1. In SQL, create a table by
USE [Geostore_Test]
GO

/****** Object:  Table [dbo].[arch_nmp_polys_test1]    Script Date: 29/11/2022 11:53:44 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[arch_nmp_polys_test99](
	[qgs_fid] [int] IDENTITY(1,1) NOT NULL,
	[geom] [geometry] NULL,
	[ogr_fid] [bigint] NULL,
	[fid] [int] NULL,
	[OBJECTID] [int] NULL,
	[LAYER] [nvarchar](max) NULL,
	[MONARCH] [float] NULL,
	[PERIOD] [nvarchar](max) NULL,
	[TYPE] [nvarchar](max) NULL,
	[EVIDENCE] [nvarchar](max) NULL,
	[PHOTO] [nvarchar](max) NULL,
	[PROJECT] [nvarchar](max) NULL,
 CONSTRAINT [PK_arch_nmp_polys_test99] PRIMARY KEY CLUSTERED 
(
	[qgs_fid] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

USE [Geostore_Test]
GO

SET ARITHABORT ON
SET CONCAT_NULL_YIELDS_NULL ON
SET QUOTED_IDENTIFIER ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
SET NUMERIC_ROUNDABORT OFF
GO

/****** Object:  Index [qgs_geom_sidx]    Script Date: 29/11/2022 11:54:48 ******/
CREATE SPATIAL INDEX [qgs_geom_sidx] ON [dbo].[arch_nmp_polys_test99]
(
	[geom]
)USING  GEOMETRY_GRID 
WITH (BOUNDING_BOX =(351498, 175759, 425780, 250216), GRIDS =(LEVEL_1 = MEDIUM,LEVEL_2 = MEDIUM,LEVEL_3 = MEDIUM,LEVEL_4 = MEDIUM), 
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

INSERT INTO [dbo].[geometry_columns]
([f_table_catalog],[f_table_schema],[f_table_name],[f_geometry_column],[coord_dimension],[srid],[geometry_type])
values('Geostore_Test','dbo','arch_nmp_polys_test99','geom',2,27700,'MULTIPOLYGON')
GO

2. In QGIS (blank project, new profile with default ESPG set to 27700), add the attached shapefile (arch_nmp_polys_test.zip, 11 features)
3.  Open an MSSQL connection to the database you created the layer in, and add the empty layer
4. Select All from the shapefile layer, and Copy the features
5. Start editing the (empty) MSSQL layer and paste the copied features
6. Turn off the shapefile layer, deselect everything, and identify some polygons in the MSSQL layer.
7. Save the edits
8. Identify a feature in the MSSQL layer --> QGIS hangs
9. Kill the QGIS process in Task Manager
10. In MSSQL, run "ALTER TABLE [dbo].[arch_nmp_polys_test99] ALTER COLUMN [MONARCH] [decimal](10,0) NULL"
11.  Restart QGIS and add in the shapefile layer (to set the map location) and then the MSSQL layer.
12. Identify features in the MSSQL layer --> works fine.

[arch_nmp_polys_test.zip](https://github.com/qgis/QGIS/files/10112889/arch_nmp_polys_test.zip)

### Versions

MSSQL database is SQL Server 2016 (13.0 7016.1)
Windows 10 patched to update KB5019959 

QGIS version
3.22.13-Białowieża
QGIS code revision
02ff117c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried changing the type of the float field (MONARCH) to numeric(18,0) in a copy of the root layer (110000 features) using a SQL "Alter table" statement, and that seemed to fix the matter.
Manually digitising a small number of features (up to 6) may allow partial use of Identify, but the float field and fields after it show as NULL, and identify highlighting doesn't work properly.

**Comment by nicogodet** [comment]
Please search before opening an issue.

Duplicates https://github.com/qgis/QGIS/issues/50865
