### ISSUE TITLE
QGIS crashes upon the opening of a specific .qgz file

### ISSUE THREAD

**Issue by emanuele0933** [qgis/QGIS#51055]
### What is the bug or the crash?

Crash ID: [e3dbec00bb3c7a16cea85d9040883e81a92779d8](https://github.com/qgis/QGIS/search?q=e3dbec00bb3c7a16cea85d9040883e81a92779d8&type=Issues)

Stack Trace

QgsProcessingDxfLayersWidget::setProject :
QgsEmbeddedSymbolRendererWidget::setContext :
QgsRendererPropertiesDialog::setContext :
QgsLayerStylingWidget::updateCurrentWidgetLayer :
QObject::qt_static_metacall :
QListWidgetItem::`default constructor closure' :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QListWidget::setCurrentRow :
QgsLayerStylingWidget::setLayer :
QObject::qt_static_metacall :
QgsMapLayerComboBox::layerChanged :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsMapLayerModel::addLayers :
QObject::qt_static_metacall :
QgsProject::layersAdded :
QObject::qt_static_metacall :
QgsMapLayerStore::layersAdded :
QgsMapLayerStore::addMapLayers :
QgsProject::addMapLayers :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.20.3-Odense
QGIS code revision: 495fbaec
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Simply opened a .qgz file

### Versions

Versione di QGIS
3.20.3-Odense
Revisione codice QGIS
495fbaec
Versione Qt
5.15.2
Versione Python
3.9.5
Versione GDAL/OGR
3.3.1
Versione PROJ
8.1.1
Versione database del Registro EPSG
v10.028 (2021-07-07)
Versione GEOS
3.9.1-CAPI-1.14.2
Versione SQLite
3.35.2
Versione PDAL
2.3.0
Versione client PostgreSQL
13.0
Versione SpatiaLite
5.0.1
Versione QWT
6.1.3
Versione QScintilla2
2.11.5
Versione SO
Windows 10 Version 2009

Plugins Python attivi
coordinate_capture
geometric_attributes
quick_map_services
StreetView
db_manager
MetaSearch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@emanuele0933, QGIS 3.20 is no longer supported. Please try with a current supported version of QGIS and with a new user profile. If the issue still occurs, please attach a sample project with layer(s) in order to replicate the issue.
