### ISSUE TITLE
Voronoi polygons hung and crashed

### ISSUE THREAD

**Issue by TehemGo** [qgis/QGIS#51065]
### What is the bug or the crash?

Ran Voronoi polygons. It hung. Then QGIS crashed.

### Steps to reproduce the issue

Have points (I had 967).
Run Voronoi Polygons with Buffer region = 40%

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.1-Firenze | QGIS code revision | fde3b8fbb8c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
BezierEditing | version 1.3.4
PointConnector | 2.0
profiletool | 4.2.2
Qgis2threejs | 2.7.1
quick_map_services | 0.19.32
Submission | 0.7
ViewshedAnalysis | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.1-Firenze
QGIS code revision
[fde3b8fbb8c](https://github.com/qgis/QGIS/commit/fde3b8fbb8c)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
BezierEditing
version 1.3.4
PointConnector
2.0
profiletool
4.2.2
Qgis2threejs
2.7.1
quick_map_services
0.19.32
Submission
0.7
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Crash report :  
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000798 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

PyFunction_Vectorcall :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QgsProcessingAlgRunnerTask::executed :
QgsProcessingAlgRunnerTask::finished :
PyInit__core :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForCompletion :
QObject::event :
PyInit__core :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by kannes** [comment]
Can you provide a minimal, reproducible example with data that can be publicly shared?

**Comment by nicogodet** [comment]
Try with a new profile too.

**Comment by TehemGo** [comment]
I must say... it may not be reproducible, even with my data set. After two failed attempts (which prompted the bug report), I failed to reproduce it with the same dataset. It works every time now.
As the error stack mentioned is a memory access violation, it may have happened on the OS level.
