### ISSUE TITLE
Elevation Profile: PostGIS raster vs. GRD files performance

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#51078]
### Feature description

I think this is more a feature request than an issue. Using the profile on raster loaded from a PostGIS storage is a lot slower than using the profile tool on raster loaded from local GRD files. I prefer to have large rasters in a database, since updating and sharing raster is easier than handling GRD files. But GRD files won't perform on a network drive, they need to be copied to the local computer for good performance. It would be good if the performance of using database raster would match that of using local GRD files.

**Comment by saberraz** [comment]
I am not sure if there is already a ticket for PostGIS raster performance. But it appears the performance (loading, rendering) of PG raster has issues and memory leaks. I suggest to close this ticket and file a new one specifically for PG raster.

**Comment by nicogodet** [comment]
@saberraz This one https://github.com/qgis/QGIS/issues/47815 ?

**Comment by saberraz** [comment]
@nicogodet correct. Let's close this in favour of the other issue.
