### ISSUE TITLE
Profile tool MapTools disable « space » shortcut to quickly drag canvas

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#51079]
### What is the bug or the crash?

Title says it all.

### Steps to reproduce the issue

1. Activate Identifying tool
2. Press Space bar et see, you can move canvas 
3. Open Profile tool widget and activate one of capture curve method
4. Press space bar
5. See nothing happens

### Versions

3.28.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
It's actually not disabling the space shortcut -- it's just that the canvas is no longer focused, so the shortcut has no effect (just like if you select a layer in the layer tree and press space)

If you click in the canvas then the space bar becomes active again, because the canvas is focused.
