### ISSUE TITLE
Error in the graphical modeler when using expression (as algorithm parameter) to compare an attribute value with a model variable

### ISSUE THREAD

**Issue by vidlb** [qgis/QGIS#51095]
### What is the bug or the crash?

If I try to use the "extract by expression" with a pre-computed expression and a model parameter, the algorithm doesn't work.  
Is this the expected behavior ?

### Steps to reproduce the issue

I'm trying to create a simple graphical model, the workflow is as follow :  
Binary mask > Rasterization > Polygonize > Extract by expression
The first example work with the following value in the expression : `DN=1`

Then I try to add a model parameter (number) to allow filtering polygons by min area as follow (expression as parameter).
`DN=1 and $area > @minarea`

This provokes an error.  
In QGIS 3.22 : "syntax error, unexpected $end"
In QGIS 3.28 : same problem but different message, just something like "Algorithm failed"

I also tried to comput an "area" attribute first then use the following expression which also failed
`DN=1 and area > @minarea`

### Versions

I tried with several versions :  

* 3.22.10
* 3.22.13
* 3.28.1

All windows

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile (well I tried in a classrooms with a lot of machines, mostly with default profiles)

**Comment by troopa81** [comment]
Could you share a sample project please?

**Comment by vidlb** [comment]
Hi @troopa81, sorry for the delay, I had to fetch some old files in order to find the problematic qgis model ; I'll try to send you a project this week

**Comment by vidlb** [comment]
Okay, I realized I was doing it wrong.
The pre-computed expression must produce a string that is evaluated as another expression.
And I was passing a raw expression to the algorithm.

Looks like there was some improvements because errors were different now I updated to QGIS 3.28.4.
Closing it now, sorry for the false alarm...
