### ISSUE TITLE
QGIS Vector Tile Atlas Clipping crash

### ISSUE THREAD

**Issue by nmaysgs** [qgis/QGIS#51093]
## Report Details

**Crash ID**: [9dded6df96e1f3fb23c6706f8482fc392d7804a3](https://github.com/qgis/QGIS/search?q=9dded6df96e1f3fb23c6706f8482fc392d7804a3&type=Issues)

**Stack Trace**
<pre>
QgsMapToPixelSimplifier::operator= :
QgsSymbol::renderFeature :
QgsFeatureRenderer::renderFeature :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.8-Hannover
QGIS code revision: 8c50902e
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.0
Running against GDAL: 3.3.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

## User Feedback

Maybe something to do with vector tile layers, clipping through use of Atlas features? Using a vector tile layer and using the atlas clip function including forcing labels within atlas boundary causing QGIS to crash. 

### Versions

QGIS Version: 3.16.8-Hannover

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@nmaysgs QGIS 3.16 is no longer supported. Could you please try with the latest available supported version of QGIS and with a new QGIS user profile? If the issue does occur also in this case, could you please provide a sample project/layer(s) ad exact steps to reproduce the issue?
