### ISSUE TITLE
Delete button in Python expression function editor deletes wrong script

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#51107]
### What is the bug or the crash?

Clicking the red "-" button in the Python expression function editor deletes the wrong script.

### Steps to reproduce the issue

1. Have three entries in the script list, each with unique content, for example:
    - 1.py: Containing just a `1`
    - 2.py: `2`
    - 3.py: `3`
2. Select the middle one, 2.py
4. Click the red delete button
5. There is no 2.py anymore in the file system
    - I did not check if the file was renamed or removed
6. 3.py now contains the contents of the just deleted script 2.py
    - I did not check if the file was renamed or rewritten
7. The contents of the script 3.py below the selected, meant-to-be-deleted script 2.py is now deleted and lost for the user

Video (Ignore my German language, I tested this in a fresh English profile):

https://user-images.githubusercontent.com/7661092/205511748-e9a8d354-8587-4ff5-b65b-c9df4bf37e42.mp4

### Versions

master from ~10 days ago: https://github.com/qgis/QGIS/commit/ade4f0cf0f2
I am pretty sure this has made me lose scripts in the past but I did not investigate back then.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Yikes! This is quite bad!

**Comment by agiudiceandrea** [comment]
The "Remove selected functions file" functionality was added in QGIS 3.14 with PR https://github.com/qgis/QGIS/pull/35901 by @alexbruy (who I hope may have a look at this issue).
