### ISSUE TITLE
Newly added Python expression script is not deletable

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#51108]
### What is the bug or the crash?

When you have no Python expression script and add a new one, the delete button is not activated.

### Steps to reproduce the issue

1. Open Python expression function editor
2. Remove any existing scripts (use a new profile, so you don't lose anything...)
3. Add a new script using the green add button
4. The new script is selected but the delete button is not available
5. Add another one and switch between them, the delete button is still not available

It will be available once the dialog is re-opened.

### Versions

master from ~10 days ago: https://github.com/qgis/QGIS/commit/ade4f0cf0f2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@agiudiceandrea Looks to me like this is not on the "Python Console" but the Expression "function editor".
