### ISSUE TITLE
Bug: Simple label preview is correct but actual map shows null for a value

### ISSUE THREAD

**Issue by chapmanjacobd** [qgis/QGIS#51100]
### What is the bug or the crash?

Simple label preview shows the correct result 

![image](https://user-images.githubusercontent.com/7908073/205378171-587bbd4f-a604-4077-976d-478484141597.png)

but actual label shows incorrect result

![image](https://user-images.githubusercontent.com/7908073/205381789-c5a93723-94e7-4cec-8f5a-5fd1705de753.png)

### Steps to reproduce the issue

[data.zip](https://github.com/qgis/QGIS/files/10144090/data.zip) (Maybe this is also a bug in OGR Layer Algebra)

```
'A: ' || if(A, A, 'NULL') || '\n' ||
'B: ' || if(B, B, 'NULL') || '\n' ||
'C: ' || if(C, C, 'NULL')
```

### Versions

QGIS version | 3.24.3-Tisler | QGIS code branch | Release 3.24
-- | -- | -- | --
Compiled against Qt | 5.15.5 | Running against Qt | 5.15.7
Python version | 3.10.5
GDAL/OGR version | 3.4.3
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.36.0
Compiled against PDAL | 2.4.0 | Running against PDAL | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 36 (KDE Plasma)
  |   |   |  
Active Python plugins
loadthemall | 3.3.0
Serval | 3.10.5
QCopycanvas | 0.5
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
Fascinating! I can confirm it and it also happens with a more minimal `if(A, 'Bug, if this is shown')` or `coalesce(A, 'Bug, if this is shown')`.

**Comment by agiudiceandrea** [comment]
I would add another weirdness: you can create a virtual field using the provided expression and such virtual field will contain the correct text; however, if you use such virtual field as the value of the label, the label will display the incorrect text which is different from the text contained in the virtual field.

**Comment by agiudiceandrea** [comment]
Looking better at the layer, it seems there is an issue in it.
The layer is considered by QGIS to have 4 field A (int), A_1 (int), C (int), B (string), and contains 1 feature with the corresponding values 11, NULL, 8, NULL.
The layer is instead reported by GDAL/OGR to have 4 field A, A, C, B: it actually has two field with the same name A.

```
ogrinfo 2022-12-02T2010_0x242ac120004_AhaLN.fgb layer_algebra
INFO: Open of `2022-12-02T2010_0x242ac120004_AhaLN.fgb'
      using driver `FlatGeobuf' successful.

Layer name: layer_algebra
[...]
A: Integer (10.0)
A: Integer (10.0)
C: Integer (10.0)
B: String (10.0)
OGRFeature(layer_algebra):0
  A (Integer) = 11
  C (Integer) = 8
  MULTIPOLYGON (((1 2,1 3,3 3,3 2,1 2)))
```

**Comment by chapmanjacobd** [comment]
Also, I noticed that when trying to delete the A or A_1 column in the QGIS attributes table the results were nondeterministic. Sometimes I would get what I wanted but sometimes, after ctrl-z and deleting the same column again, QGIS would delete the other A column.

**Comment by roya0045** [comment]
What if you use `If ( "A" IS NULL` or `coalesce` in your expressions? Might be a workaround if getting this to work is critical.

**Comment by nyalldawson** [comment]
This isn't a QGIS bug -- as noted earlier the file is corrupt and contains duplicate field names.
