### ISSUE TITLE
StatusBar error: Object has no attribute 'showMessage'

### ISSUE THREAD

**Issue by coderodyhpc** [qgis/QGIS#51127]
### What is the bug or the crash?

Trying to print a simple text in the statusBar fails with: Object has no attribute 'showMessage' (see attached screenshot)
![showMessageerror01](https://user-images.githubusercontent.com/79646720/206021662-ff4716d7-5c12-4e18-a0b8-f1cc381d0cf4.jpg)
I checked the methods associated with iface.mainWindow().statusBar() and showMessage is there (see 2nd screenshot).
![showMessageerror02](https://user-images.githubusercontent.com/79646720/206022194-a718729a-81f1-4e91-a8ff-57cbcc8df0a0.jpg)

### Steps to reproduce the issue

Open python shell.
Type: 
```
text = 'TESTING'
iface.mainWindow().statusBar().showMessage(text)

```

### Versions

3.25.0-Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Please carefully review the error message Python is raising, as it explains your issue:

iface.mainWindow().statusBar.showMessage()

> AttributeError: 'builtin_function_or_method' object has no attribute 'showMessage'


You should be calling

iface.mainWindow().statusBar().showMessage()
