### ISSUE TITLE
QGIS crashing at the saving of PostgreSQL layer after merging features

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#51122]
### What is the bug or the crash?

QGIS crashes when editing a PSQL layer (specifically merging features) and then hitting save. This is reproducible, tested on both 3.28 and 3.22.

### Steps to reproduce the issue

Follow along with the video in the zip. 

SQL code and map are also attached to create the layer.

[crash.zip](https://github.com/qgis/QGIS/files/10157790/crash.zip)

### Versions

3.28 and 3.22 LTR

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

Crash ID: [0dfb5b2e81d9973c919f17cf6df1ee6e7358fbf0](https://github.com/qgis/QGIS/search?q=0dfb5b2e81d9973c919f17cf6df1ee6e7358fbf0&type=Issues)

Stack Trace

QVariant::clear :
QVariant::operator= :
QgsVectorLayerEditBuffer::commitChanges :
QgsVectorLayer::commitChanges :
QgisApp::saveVectorLayerEdits :
QgisApp::saveActiveLayerEdits :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.13-Bia?owie?a
QGIS code revision: 02ff117c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.18363

**Comment by elpaso** [comment]
Confirmed on current master/linux

**Comment by elpaso** [comment]
Probably introduced by https://github.com/qgis/QGIS/pull/47822
