### ISSUE TITLE
Add "final-3_26_2" and "final-3_26_3" Docker images to Dockerhub

### ISSUE THREAD

**Issue by erakhmatulina** [qgis/QGIS#51134]
### What is the bug or the crash?

bug: missing docker images in Dockerhub 

### Steps to reproduce the issue

search qgis dockerhub for final-3_26_3

### Versions

3.26.2 and 3.26.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

version 3.26.3 has an updated GDAL version which I need

**Comment by nicogodet** [comment]
3.26 is EOL and 3.28.1 should be on dockerhub (if not, this is an issue).

GDAL on 3.28.1 should be the same than in 3.26 image (or even more up to date).

**Comment by erakhmatulina** [comment]
@nicogodet, separate issue but with docker images 3.28+, gdal (and maybe other) qgis processing scripts get stuck with the message "QProcess: Destroyed while process ("whoami") is still running.". Not sure how to get around it. Everything else equal 3.26 runs everything just fine. I can start a separate thread for that issue, but figured if I could have the 2.26.3 image, my issue would be resolved.

**Comment by nicogodet** [comment]
@erakhmatulina Indeed, could you open a separate PR describing the issue and step to reproduce ?
Better fixing the issue than rely on outdated QGIS version.

**Comment by dasaderto** [comment]
I am getting the same error in version 3_28. No solution found?
<img width="522" alt="Снимок экрана 2023-01-29 в 01 04 18" src="https://user-images.githubusercontent.com/38347951/215293144-b10558d8-89c6-4557-9733-5b17f40193cd.png">
In my opinion the error is in src/core/qgsapplication.cpp

**Comment by fireai-developer** [comment]
> "QProcess: Destroyed while process ("whoami") is still running."

@nicogodet I did not want to spam this thread with a solution to that unrelated issue, but I also was not able to find any other issues, so I created a new one here: https://github.com/qgis/QGIS/issues/52681

Just mentioning it here in case anyone stumbles across this via google search, as I did. The additional information section of that issue includes a solution that worked for me (M1 specific problem in my case).

**Comment by alexbruy** [comment]
Closing as 3.26 is EOL.
