### ISSUE TITLE
(Repeatable) Crah upon fixed table creation within Layout view

### ISSUE THREAD

**Issue by ogclarence** [qgis/QGIS#51163]
### What is the bug or the crash?

QGIS instance crashes upon creation and attempted editing of a fixed table within the layout view.

### Steps to reproduce the issue

1. Open a new layout from a template, one that I had already made and was attempting to edit.
2. create new fixed table feature
3. click on table to edit size/cells
4. delete text box
5. crash upon settings window open

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.1-Firenze | QGIS code revision | fde3b8fbb8c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.2.5
batch_gps_importer | version 1.0.1
FreehandRasterGeoreferencer | 0.8.3
Importer2OSMbasemap | 1.0
latlontools | 3.6.6
OSMDownloader | 1.0.3
precisioncursor4qgis-main | 0.2E
qgis-maptiler-plugin | 3.1.1
quick_map_services | 0.19.32
VectorBender | 0.2.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.1-Firenze
QGIS code revision
[fde3b8fbb8c](https://github.com/qgis/QGIS/commit/fde3b8fbb8c)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.5
batch_gps_importer
version 1.0.1
FreehandRasterGeoreferencer
0.8.3
Importer2OSMbasemap
1.0
latlontools
3.6.6
OSMDownloader
1.0.3
precisioncursor4qgis-main
0.2E
qgis-maptiler-plugin
3.1.1
quick_map_services
0.19.32
VectorBender
0.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

The instance crashes either upon deletion of a text box or when attempting to edit a table

**Comment by agiudiceandrea** [comment]
@ogclarence have you actually tried if the issue does occur using a new clean QGIS user profile (it doesn't seem like it to me, judging by the list of installed plugins)? Could you please provide a sample project with which the issue does occur?
