### ISSUE TITLE
QGIS crashes while attempting to fix a defect geometry

### ISSUE THREAD

**Issue by mhaelsig** [qgis/QGIS#51166]
### What is the bug or the crash?

I isolated a defect geometry (attached), which seems to have a ring self intersection. When I apply the function 'fix geometry' to this geometry, QGIS crashes. 
[2020_gegenEinbahn.defekt.zip](https://github.com/qgis/QGIS/files/10199914/2020_gegenEinbahn.defekt.zip)

### Steps to reproduce the issue

Apply the function 'fix geometry' (German: Geometrien reparieren) to the attached geometry. 
QGIS crashes. 

### Versions

QGIS-Version | 3.28.1-Firenze | QGIS-Codeversion | fde3b8fbb8
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.2
GDAL-Version | 3.2.2
PROJ-Version | 7.2.1
EPSG-Registraturdatenbankversion | v10.008 (2020-12-16)
GEOS-Version | 3.9.0-CAPI-1.16.2
SQLite-Version | 3.34.1
PDAL-Version | 2.2.0
PostgreSQL-Client-Version | 13.8 (Debian 13.8-0+deb11u1)
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Aktive Python-Erweiterungen
mapswipetool_plugin | 1.2
OnlineRoutingMapper | 0.9
GroupStats | 2.2.6
db-style-manager | 0.8
nominatim_locator_filter | 0.2.4
OSMDownloader | 1.0.3
qgis_stac | 1.1.1
SelectWithin | 0.4
minimum_spanning_tree | 2.1
quick_map_services | 0.19.32
DB_Werkzeug | 0.1
vector_tiles_reader | 3.2.2
qgis-maptiler-plugin | 3.1.1
QNEAT3 | 1.0.4
Beeline | 0.2.0
postgisQueryBuilder | 2.0.1
maplibrary | 1.2
qgis2web | 3.16.0
ORStools | 1.5.2
qgis_resource_sharing | 1.0.0
StreetView | 3.2
searchlayers | 3.0.12
QuickOSM | 2.1.1
AppendFeaturesToLayer | 1.2.0
AutoLayoutTool | 1.1
Offline-MapMatching | 3.0.0
active_fire | 0.3
latlontools | 3.6.6
OpenTopography-DEM-Downloader | 1.0
postgis_geoprocessing | 0.9
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS-Version
3.28.1-Firenze
QGIS-Codeversion
[fde3b8fbb8](https://github.com/qgis/QGIS/commit/fde3b8fbb8)
Qt-Version
5.15.2
Python-Version
3.9.2
GDAL-Version
3.2.2
PROJ-Version
7.2.1
EPSG-Registraturdatenbankversion
v10.008 (2020-12-16)
GEOS-Version
3.9.0-CAPI-1.16.2
SQLite-Version
3.34.1
PDAL-Version
2.2.0
PostgreSQL-Client-Version
13.8 (Debian 13.8-0+deb11u1)
SpatiaLite-Version
5.0.1
QWT-Version
6.1.4
QScintilla2-Version
2.11.6
BS-Version
Debian GNU/Linux 11 (bullseye)

Aktive Python-Erweiterungen
mapswipetool_plugin
1.2
OnlineRoutingMapper
0.9
GroupStats
2.2.6
db-style-manager
0.8
nominatim_locator_filter
0.2.4
OSMDownloader
1.0.3
qgis_stac
1.1.1
SelectWithin
0.4
minimum_spanning_tree
2.1
quick_map_services
0.19.32
DB_Werkzeug
0.1
vector_tiles_reader
3.2.2
qgis-maptiler-plugin
3.1.1
QNEAT3
1.0.4
Beeline
0.2.0
postgisQueryBuilder
2.0.1
maplibrary
1.2
qgis2web
3.16.0
ORStools
1.5.2
qgis_resource_sharing
1.0.0
StreetView
3.2
searchlayers
3.0.12
QuickOSM
2.1.1
AppendFeaturesToLayer
1.2.0
AutoLayoutTool
1.1
Offline-MapMatching
3.0.0
active_fire
0.3
latlontools
3.6.6
OpenTopography-DEM-Downloader
1.0
postgis_geoprocessing
0.9
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/50888

**Comment by mhaelsig** [comment]
Hi,
thank you for your quick reply. 

As fas as I understand, the fix for #50888 has been included in 3.28.0. But I 
am using already 3.28.1. Therefore, the fix does not help for this issue?

Kind regards
Michael Hälsig

-- 
Dr. Michael Hälsig
Diefenbachstr. 9
81479 München

Tel.: +49 89 79199563
Mob.:+49 171 333 7558
Am Samstag, 10. Dezember 2022, 12:09:21 CET schrieb Nicolas Godet:

**Comment by nicogodet** [comment]
#50888 is not fixed yet that's why you still have the issue on 3.28.1.
