### ISSUE TITLE
Cannot instantiate QgsModelDesignerDialog using PyQGIS

### ISSUE THREAD

**Issue by nicolnt** [qgis/QGIS#51183]
### What is the bug or the crash?

```python
dlg = QgsModelDesignerDialog()
```
```
Traceback (most recent call last):
  File "/Applications/QGIS-LTR.app/Contents/MacOS/../Resources/python/code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
TypeError: qgis._gui.QgsModelDesignerDialog represents a C++ abstract class and cannot be instantiated
```

### Steps to reproduce the issue

Instanciate `QgsModelDesignerDialog` class

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.10-Białowieża | QGIS code revision | 44701d6dd7
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 12.6
  |   |   |  
Active Python plugins
ORStools | 1.5.2
debug_vs | 0.7
quick_map_services | 0.19.32
nominatim | 1.4.2
pluginbuilder3 | 3.2.1
latlontools | 3.6.6
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5
contexte_metha | 0.1

</body></html>QGIS version
3.22.10-Białowieża
QGIS code revision
[44701d6dd7](https://github.com/qgis/QGIS/commit/44701d6dd7)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 12.6

Active Python plugins
ORStools
1.5.2
debug_vs
0.7
quick_map_services
0.19.32
nominatim
1.4.2
pluginbuilder3
3.2.1
latlontools
3.6.6
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5
contexte_metha
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Partial fix but still getting some warnings:

```python
class MyQgsModelDesignerDialog(gui.QgsModelDesignerDialog):
    def __init__(self, parent=None):
        super().__init__(parent)

dlg = MyQgsModelDesignerDialog()
```

Warning message:

> WARNING    NotImplementedError: QgsModelDesignerDialog.repaintModel() is abstract and must be overridden

**Comment by nyalldawson** [comment]
This is not a bug -- this class isn't designed to be used externally, it's exposed to Python solely for use by the Processing plugin.

**Comment by nicolnt** [comment]
OK, I was looking for a way to load a QGIS model (.model3) file and run it from a plugin and came across this method on StackOverflow I think, and it works like that. Is there any official way to run a load and run a model in Python @nyalldawson?

**Comment by nicolnt** [comment]
@nyalldawson do you have any advice on how to correctly load a .model3 file with python script and run it?

**Comment by nicogodet** [comment]
After few search on www, https://gis.stackexchange.com/questions/329323/qgis3-call-model-from-windows-path-with-python-script

Otherwise, you should ask on qgis user mailing list. Github is not the place to ask for help.
