### ISSUE TITLE
las2las in OSGeo4W Shell: las2las (libLAS 1.8.1 with GeoTIFF 1.4.2) --> LASzip is missing

### ISSUE THREAD

**Issue by weisev-repo** [qgis/QGIS#51193]
### What is the bug or the crash?

If I'm running the following cmd-line in OSGeo4W Shell:
>> las2las 3dm_32_510_5704_1_nw.laz --output out.laz --extent "510100 5703500 510900 5704500"

The following error occurs:
>> error: Compression support not enabled in liblas configuration

I noticed that if I'm running las2las in the cmd-line I get in the header:  

--------------------------------------------------------------------
    las2las (libLAS 1.8.1 with GeoTIFF 1.4.2)
--------------------------------------------------------------------

But I think LASzip is missing and therefore the error of compression support occurs.

What is a little confusing if I navigate to C:\Program Files\QGIS 3.22.13\bin, there is laszip3.dll

Do you have any advice?

I'm using QGIS 3.22.13 LTR. 

### Steps to reproduce the issue

1. Go to https://wheregroup.com/blog/details/visualisierung-und-manipulation-von-lidar-daten-mit-qgis-und-pdal/ and download the LIDAR Testdaten aus OpeGeoData.NRW
2. Open OSGeo4W Shell and type "las2las" --> Check the header
3. Paste the following into the command line: las2las 3dm_32_510_5704_1_nw.laz --output out.laz --extent "510100 5703500 510900 5704500"

### Versions

QGIS 3.22.13 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
This sould be reported on [OSGeo4W Tracker](https://trac.osgeo.org/osgeo4w/query?status=assigned&status=closed&status=new&status=reopened&col=id&col=summary&col=status&col=type&col=priority&col=component&col=resolution&col=time&col=changetime&col=reporter&desc=1&order=id&report=12).
