### ISSUE TITLE
(new) Elevation profile doesn't plot on North/South and East/West traces

### ISSUE THREAD

**Issue by martial-chateauvieux** [qgis/QGIS#51196]
### What is the bug or the crash?

(new) Elevation profile doesn't plot on North/South and East/West traces.

[QGis-ProfileTool-NorthSouth-Bug.zip](https://github.com/qgis/QGIS/files/10216901/QGis-ProfileTool-NorthSouth-Bug.zip)

### Steps to reproduce the issue

In the attached project, Mapzen is the project Terrain layer.

- open the Elevation profile,
- Use the "Capture from Curve" feature to select the lines in the "NorthSouth trace" layer.
- The 3 segment line, and the 30° lines display the Terrain profile,
- The North/South and the East/West segments don't show the terrain profile

![image](https://user-images.githubusercontent.com/108923302/207291557-3e9f0edf-2963-4858-9762-4f045e0d7962.png)
![image](https://user-images.githubusercontent.com/108923302/207291643-34ec3571-03a7-4a61-833a-f58441f565e5.png)
![image](https://user-images.githubusercontent.com/108923302/207291730-b3db61d8-8118-4c17-a278-88d1cf9a1a69.png)
![image](https://user-images.githubusercontent.com/108923302/207291790-268b47cc-386a-4493-b9ad-3d4e446fe465.png)

### Versions

<html>
<body>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.1-Firenze | QGIS code revision | fde3b8fbb8
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PostgreSQL client version | 13.8 (Debian 13.8-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins
reconstruct_line | 0.7
QuickOSM | 2.1.1
SRTM-Downloader | 3.1.17
coordinates_converter | 1.0
GeometryShapes | 0.7

</body></html>
</body>
</html>
QGIS version
3.28.1-Firenze
QGIS code revision
[fde3b8fbb8](https://github.com/qgis/QGIS/commit/fde3b8fbb8)
Qt version
5.15.2
Python version
3.9.2
GDAL/OGR version
3.2.2
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.9.0-CAPI-1.16.2
SQLite version
3.34.1
PostgreSQL client version
13.8 (Debian 13.8-0+deb11u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Debian GNU/Linux 11 (bullseye)

Active Python plugins
reconstruct_line
0.7
QuickOSM
2.1.1
SRTM-Downloader
3.1.17
coordinates_converter
1.0
GeometryShapes
0.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Version is compiled from source on Debian/Linux by myself from github 3_28_1 tag.

**Comment by nicogodet** [comment]
@martial-chateauvieux Duplicates of https://github.com/qgis/QGIS/issues/49279 ?

**Comment by martial-chateauvieux** [comment]
No. This one is the Terrain layer not displaying.
49279, it was the trace not displaying over the terrain.
(Both reports are from me. That’s all they have in common 😉)




Martial Châteauvieux
Software Development Lead
Tel: +41 61 377 68 78
Martial.Chateauvieux @***@***.***>
________________________________

***@***.***
[UMS SKELDAR AG  Gewerbepark Bata 8  4313 Möhlin  Switzerland]          [UMS SKELDAR SWEDEN AB  Låsbomsgatan 18  589 41 Linköping      Sweden]





P: +41 61 377 68 68
***@***.******@***.***>
www.umsskeldar.aero<http://www.umsskeldar.aero/>

IMPORTANT: The contents of this email and any attachments are confidential. They are intended for the named recipient(s) only. If you have received this email by mistake, please notify the sender immediately and do not disclose the contents to anyone or make copies thereof.

From: Nicolas Godet ***@***.***>
Sent: Tuesday, 13 December 2022 11:39
To: qgis/QGIS ***@***.***>
Cc: Martial Chateauvieux ***@***.***>; Mention ***@***.***>
Subject: [EXTERNAL]Re: [qgis/QGIS] (new) Elevation profile doesn't plot on North/South and East/West traces (Issue #51196)


@martial-chateauvieux<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmartial-chateauvieux&data=05%7C01%7Cmartial.chateauvieux%40umsskeldar.aero%7C515b7fb5c2a8483d1aaf08dadcf632ac%7C43cb11ed491f435292efe60421b51e24%7C0%7C0%7C638065247232631747%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=hjjh5fT3Rfp2GgHXNEWl8r3r3UxwmrJ9sZ4U2BOvIPM%3D&reserved=0> Duplicates of #49279<https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fqgis%2FQGIS%2Fissues%2F49279&data=05%7C01%7Cmartial.chateauvieux%40umsskeldar.aero%7C515b7fb5c2a8483d1aaf08dadcf632ac%7C43cb11ed491f435292efe60421b51e24%7C0%7C0%7C638065247232787966%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2BH7e1OKMe8LXJWOwl9flfnOIGKVOjTrr0vh5CsK%2BEZo%3D&reserved=0> ?

**Comment by nicogodet** [comment]
Oh ! I see ! (Read too fast..)

Seems specific to Mapzen layer. I tried on local raster without issue.

**Comment by nicogodet** [comment]
By any chance, could you try on 3.26 ?

**Comment by martial-chateauvieux** [comment]
> Seems specific to Mapzen layer. I tried on local raster without issue.
I will try that too and report.
I do not have 3.26 at hand.

**Comment by martial-chateauvieux** [comment]
You are correct, the SRTM layer doesn't have the problem
![image](https://user-images.githubusercontent.com/108923302/207313411-ff986cf7-46c2-41d7-b616-40225c8c4b19.png)
![image](https://user-images.githubusercontent.com/108923302/207313510-d3692661-683a-483e-8eeb-1332180e4760.png)
