### ISSUE TITLE
setDataSource崩溃

### ISSUE THREAD

**Issue by lizilizixuan** [qgis/QGIS#51205]
### What is the bug or the crash?

我在用postgres生成layer后，在更新dataSource时qgis会崩溃

### Steps to reproduce the issue

 pr = layer.dataProvider()
 provider_options = pr.ProviderOptions()
 layer.setDataSource(uri, layer.name(), layer.providerType(), provider_options,flags=pr.FlagTrustDataSource)

在setDataSource的时候，如果layer比较多的话，qgis会崩溃

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS版本 | 3.28.0-Firenze | QGIS代码版本 | ed3ad0430f
-- | -- | -- | --
Qt版本 | 5.15.2
Python版本 | 3.9.5
GDAL/OGR版本 | 3.3.2
PROJ版本 | 8.1.1
EPSG注册数据库版本 | v10.028 (2021-07-07)
GEOS版本 | 3.9.1-CAPI-1.14.2
SQLite版本 | 3.35.2
PDAL版本 | 2.3.0
PostgreSQL客户端版本 | unknown
SpatiaLite版本 | 5.0.1
QWT版本 | 6.1.6
QScintilla2版本 | 2.11.5
操作系统版本 | macOS 13.0
  |   |   |  
已激活的Python插件
quick_map_services | 0.19.32
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS版本
3.28.0-Firenze
QGIS代码版本
[ed3ad0430f](https://github.com/qgis/QGIS/commit/ed3ad0430f)
Qt版本
5.15.2
Python版本
3.9.5
GDAL/OGR版本
3.3.2
PROJ版本
8.1.1
EPSG注册数据库版本
v10.028 (2021-07-07)
GEOS版本
3.9.1-CAPI-1.14.2
SQLite版本
3.35.2
PDAL版本
2.3.0
PostgreSQL客户端版本
unknown
SpatiaLite版本
5.0.1
QWT版本
6.1.6
QScintilla2版本
2.11.5
操作系统版本
macOS 13.0

已激活的Python插件
quick_map_services
0.19.32
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please report in english.
And add more info on what you try to achieve, steps your tried and where it fails.
