### ISSUE TITLE
Conditional Salt-affected soil calculation for in QGIS Raster Calculator

### ISSUE THREAD

**Issue by POTCHARAARIYA** [qgis/QGIS#51204]
### Feature description

![317855055_703292497714812_3402316665988068578_n](https://user-images.githubusercontent.com/113614616/207487798-de5b7564-2d14-430a-aba6-aca016b63e64.jpg)

I would like to write a formula for classifying soil salinity according to this table from 2 raster maps (EC,ESP). How do I write a formula?

**Comment by nicogodet** [comment]
You should ask on user mailing list and read some documentation about QGIS.
Github is for bug reporting, not question on how to use the software.
