### ISSUE TITLE
Can't connect to ODBC system DSN (Windows)

### ISSUE THREAD

**Issue by pedrohsroque** [qgis/QGIS#51219]
### What is the bug or the crash?

I'm trying to connect QGIS with Snowflake using the ODBC method. It's working in other apps, but the I try on QGIS I receive the following error:

Connection failed - Check settings and try again.
Extended error information:
Unable to initialize ODBC connection to DSN for {user}/{password}@{dbname}

### Steps to reproduce the issue

Click on 'Add Vector Layer...'
under Source Type select Database
under Database select ODBC
create new connection with all specs Name: CONNECTIONNAME, Host: localhost, Database: DATABASENAME, Port: leave empty
click on 'Test Connection'

### Versions

Versão do QGIS
3.28.1-Firenze
Código da versão do QGIS
fde3b8fbb8c
Versão Qt
5.15.3
Versão do Python
3.9.5
Versão GDAL/OGR
3.6.0
Versão PROJ
9.1.0
Versão da base de dados do registro EPSG
v10.074 (2022-08-01)
Versão GEOS
3.11.1-CAPI-1.17.1
Versão SQLite
3.39.4
Versão PDAL
2.4.3
Versão cliente PostgreSQL
unknown
Versão SpatiaLite
5.0.1
Versão QWT
6.1.6
Versão QScintilla2
2.13.1
Versão OS
Windows 10 Version 2009

Plugins Python ativos
QuickOSM
2.1.1
quick_map_services
0.19.29
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by sfc-gh-obielov** [comment]
hey @pedrohsroque Snowflake just released [QGIS-Snowflake Connector](https://github.com/snowflakedb/qgis-snowflake-plugin)
