### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by SurendraLn** [qgis/QGIS#51237]
Python Stack Trace
Windows fatal exception: access violation

Thread 0x00004ba8 (most recent call first):

Windows fatal exception: access violation

Thread 0x00004ba8 (most recent call first):

Windows fatal exception: access violation

Thread 0x00004ba8 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19043

**Comment by jef-n** [comment]
Wrong repository, no steps to reproduce and using a non-supported QGIS version (3.26.3 is EOL; use QGIS 3.22 (LTR) or 3.28)
