### ISSUE TITLE
Unable to use many functions

### ISSUE THREAD

**Issue by FrancescoCandini** [qgis/QGIS#51249]
### What is the bug or the crash?

Hi, I downloaded the last long term version (3.22) and some function disappeared. I can't open the panel of processing tools and either the option "vector" in the top of the screen.
I need some functions to manipulate different layers like: union, 

### Steps to reproduce the issue

![Immagine 2022-12-16 155110](https://user-images.githubusercontent.com/101177052/208124464-927af82d-4755-4cf1-a95e-54387b163785.png)
There aren't 2 panels that i had in last version i had. I tried also to uninstall and install again, but there is the same problem.

### Versions

Versione di QGIS
3.22.13-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
This seems like a local issue as there may be conflicts with your prior installs. Give more details on your os and how you installed it if you want more helpful responses, but I'm pretty sure similar tickets have been raised and solved previously.

**Comment by FrancescoCandini** [comment]
![image](https://user-images.githubusercontent.com/101177052/208128131-296f61b0-76d5-454f-8435-9ed823016095.png)

**Comment by FrancescoCandini** [comment]
Ok thank you.
I have Windows 10, version 22H2.
I installed this version from the qgis site: https://www.qgis.org/it/site/forusers/download.html#

**Comment by agiudiceandrea** [comment]
@FrancescoCandini, is the Processing core plugin active? If not, activate it. Otherwise, could you please try creating and using a new QGIS user profile?

**Comment by FrancescoCandini** [comment]
Just checked, i didn't have the plugin enabled.

**Comment by FrancescoCandini** [comment]
Now It works, thank you very much
