### ISSUE TITLE
"Combine rasters" error

### ISSUE THREAD

**Issue by ftrinco** [qgis/QGIS#51243]
### What is the bug or the crash?

When combining two rasters, the result is wrong, see images:
First raster:
![image](https://user-images.githubusercontent.com/63117500/207916044-dc86ebe6-e5b8-43ce-a0f4-b075a342b68e.png)

Second raster:
![image](https://user-images.githubusercontent.com/63117500/207916083-c88d744d-7b26-4131-8ddc-541122b87423.png)

Combined:
![image](https://user-images.githubusercontent.com/63117500/207916124-65f09a71-d017-4ad8-b4d9-1ae4304372f4.png)
(bad result 1)

Combined:
![image](https://user-images.githubusercontent.com/63117500/207918338-0754dff4-fa81-4d61-83f5-2f187313e5ad.png)
(bad result 2)

### Steps to reproduce the issue

Impor rasters from: https://agroubaar-my.sharepoint.com/:f:/g/personal/ftrinco_agro_uba_ar/EsFB5BTK4WNGhSwC2q4snO8Brk2a0j-IIAcyA5-ns04_rA?e=xrsYrc

Combine them

Error in the result

### Versions

Versión de QGIS
3.28.1-Firenze
Revisión del código de QGIS
fde3b8fbb8c
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.0
Versión de PROJ
9.1.0
Versión del registro de base de datos EPSG
v10.074 (2022-08-01)
Versión de GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
FragScape
2.0.6
LecoS
3.0.1
SRTM-Downloader
3.1.17
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

There is no "Settings ► User Profiles menu "

**Comment by agiudiceandrea** [comment]
The "User Profiles" menu is right there in the "Settings" menu
![image](https://user-images.githubusercontent.com/16253859/207994517-e4e545f8-5c24-43b8-b59e-44c5072034ad.png)

Could you please specify better what processing algorithm are you using?

It seems the provided link doesn't work
![image](https://user-images.githubusercontent.com/16253859/207995038-b1b31529-6b1f-4dda-8969-c9c44d165904.png)
