### ISSUE TITLE
MSSQL overlay* functions problem

### ISSUE THREAD

**Issue by djes** [qgis/QGIS#51240]
### What is the bug or the crash?

Overlay* functions doesn't work anymore on full table edition with MS SQL Server. It works with a geopackage.
 

### Steps to reproduce the issue

Works on expression editor
![image](https://user-images.githubusercontent.com/12065874/207873717-95da4c1a-5dd7-4286-8ced-552cdfb9f8fa.png)

Doesn't work on field calculator nor table 
![image](https://user-images.githubusercontent.com/12065874/207874071-b4e22797-fd09-406e-b307-629545355399.png)

### Versions

QGIS 3.22.13 (Windows)
QGIS 3.28.1 (Windows)
MS SQL Server 11.0.7493.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Just to make sure, do you still have the drivers or you got the update that removed them?

**Comment by nicogodet** [comment]
See https://github.com/qgis/QGIS/issues/50865 ?

**Comment by djes** [comment]
@nicogodet @roya0045 yes, I've mentionned my QGIS versions, we were concerned by the problem (we have more than 10 people using QGIS and MS SQL Server here).

**Comment by roya0045** [comment]
> @nicogodet @roya0045 yes, I've mentionned my QGIS versions, we were concerned by the problem (we have more than 10 people using QGIS and MS SQL Server here).

You completely missed our point, this is not about qgis but Windows.

**Comment by djes** [comment]
> > @nicogodet @roya0045 yes, I've mentionned my QGIS versions, we were concerned by the problem (we have more than 10 people using QGIS and MS SQL Server here).
> 
> You completely missed our point, this is not about qgis but Windows.

Afaik, the latest packaged QGIS includes the correct driver but I've also verified the DLL version as in https://github.com/qgis/QGIS/issues/50865#issuecomment-1327403099. Please also note that the previous QGIS was unusable.

**Comment by colliera** [comment]
My experience is... aggregate and overlay functions work on SQL layers in the field calculator or if set as default field values, e.g.

`array_to_string (overlay_intersects ('Postal Addresses', address || ', ' || postcode))`
`aggregate(layer:='Postal Addresses', aggregate:='max', expression:="Address" || ', ' || "Postcode", filter:=contains($geometry, geometry(@parent)))`

However, they do not work if set within the Symbology or Labelling of a layer, e.g.

`overlay_within('TTRO', filter:= Archive=0)`
`aggregate(layer:='TTRO', aggregate:='max', expression:="Archive"=0, filter:=contains($geometry, geometry(@parent)))`

However, this is just a problem with SQL, as the functions work for Symbology and Labelling with GeoPackage, WFS, SQLite of the same data.

Tested QGIS 3.22.16 and 3.28.12 (the latest LTR)
SQL Server Driver: 10.00.19041.3570 updated 16/10/2023

**Comment by djes** [comment]
I just discovered that removing geometric indexes on the layers fixed the issue.
