### ISSUE TITLE
Topological editing does not work when project CRS is different than layer CRS

### ISSUE THREAD

**Issue by jvanegmond93** [qgis/QGIS#51245]
### What is the bug or the crash?

If you are trying to topologically edit a layer while your project crs is different than the layer crs, the vertex editor will only move one layer vertex and not both. 

### Steps to reproduce the issue

Create layer in a CRS, set project to different CRS. Split layer, then try moving the shared vertex. Only one will move.

### Versions

3.28.1 

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Seems to have been fixed in 3.26 with [45357](https://github.com/qgis/QGIS/pull/45357) , but has reappeared in 3.28.1

**Comment by roya0045** [comment]
Just a minor nitpick, the PR you mention hasn't been merged, #48853 should have been the one to fix this issue.

**Comment by gioman** [comment]
See also https://github.com/qgis/QGIS/issues/32977 and https://github.com/qgis/QGIS/issues/29648

**Comment by IdrissaD** [comment]
I can confirm, I reproduce the bug in 3.28.5
