### ISSUE TITLE
Georreferenciador GDAL 

### ISSUE THREAD

**Issue by caroline2199** [qgis/QGIS#51255]
### What is the bug or the crash?

My isuue is that I do not have Georeferenciador GDAL installed, I have already looked for it and I can not find it. 
HELP¡  

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/120980376/208315692-02ae362e-bf7a-4763-8f45-fb9587e8a496.png)
![image](https://user-images.githubusercontent.com/120980376/208315711-a5a4c370-0602-4b5b-9aa3-e2c860cb3433.png)

### Versions

The current released version of QGIS is 3.28.1. 
We are working on 3.29-Master. It will go into feature freeze on 2023-01-13 12:00:00 UTC and be released as 3.30 on 2023-02-17 12:00:00 UTC. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Menu "Layer" -> "Georeferencer" ?

**Comment by agiudiceandrea** [comment]
@caroline2199, in QGIS there is no longer a "Georeferencer GDAL" plugin and the "Georeferencer" is a core functionality since more than 2 years ago. Please see https://docs.qgis.org/3.28/en/docs/user_manual/working_with_raster/georeferencer.html.

**Comment by caroline2199** [comment]
> Menu "Layer" -> "Georeferencer" ?

Yes¡ In spanish is Georreferenciador Gdal

**Comment by nicogodet** [comment]
If you found it, can you close this issue ?

**Comment by caroline2199** [comment]
Close #51255

**Comment by agiudiceandrea** [comment]
> In spanish is Georreferenciador Gdal

@caroline2199, it's weird... It seems it is actually "Georreferenciador" (setting the GUI language as "español de España"), not "Georreferenciador Gdal"

![image](https://user-images.githubusercontent.com/16253859/208377580-93ff7eab-5fbf-4f11-81ce-b92be883c5cf.png)
