### ISSUE TITLE
Crashes while accessing MySQL DB table during Add Vector Layer

### ISSUE THREAD

**Issue by droth4711** [qgis/QGIS#51251]
### What is the bug or the crash?

Hey!
I tried to Add Layer/Vector Layer/MySQL table with INT/CHAR/POINT (example: 144428//0x0000000001010000007E54C37E4FC4254027F8A6E9B3054840) with about 3500 records. Then crashes like what you see here. I tried this now with some delay for two years. Obviously, the problem was not reported earlier. What can we do here? I'm starting with QGIS. We are working for a Swiss database of sundials and would like to make a field app, where we can add data, photos while visiting a sundial. Thank you so much for assisting!
Best regards
Daniel Roth

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003f84 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.0-Tisler
QGIS code revision: 6b44a42058
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

I tried to Add Layer/Vector Layer/MySQL table with INT/CHAR/POINT (example: 144428//0x0000000001010000007E54C37E4FC4254027F8A6E9B3054840) with about 3500 records

### Versions

QGIS 3.24.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.24.0 is EOL.
Please update to 3.22.14 or 3.28.2 as soon as they are available on your plateform and retry.
