### ISSUE TITLE
pyproj 3.4.1 incompatible with 3.26.1

### ISSUE THREAD

**Issue by nilsnolde** [qgis/QGIS#51268]
### What is the bug or the crash?

`import pyproj` from Python console crashes QGIS with a bad alloc.

### Steps to reproduce the issue

1. Open Python console
2. `import pyproj`
3. crash

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.1-Buenos Aires | QGIS code branch | Release 3.26
-- | -- | -- | --
Compiled against Qt | 5.15.5 | Running against Qt | 5.15.7
Python version | 3.11.0
Compiled against GDAL/OGR | 3.5.1 | Running against GDAL/OGR | 3.5.2
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
Compiled against SQLite | 3.39.1 | Running against SQLite | 3.40.0
Compiled against PDAL | 2.4.2 | Running against PDAL | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 37 (Workstation Edition)
  |   |   |  
Active Python plugins
valhalla | 2.2.1
network_analyst | 0.0.2
quick_map_services | 0.19.32
plugin_reloader | 0.9.2
access_road_generator | 0.1.30
ORStools | 1.5.2
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.1-Buenos Aires
QGIS code branch
[Release 3.26](https://github.com/qgis/QGIS/tree/release-3_26)
Compiled against Qt
5.15.5
Running against Qt
5.15.7
Python version
3.11.0
Compiled against GDAL/OGR
3.5.1
Running against GDAL/OGR
3.5.2
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
Compiled against SQLite
3.39.1
Running against SQLite
3.40.0
Compiled against PDAL
2.4.2
Running against PDAL
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.0
OS version
Fedora Linux 37 (Workstation Edition)

Active Python plugins
valhalla
2.2.1
network_analyst
0.0.2
quick_map_services
0.19.32
plugin_reloader
0.9.2
access_road_generator
0.1.30
ORStools
1.5.2
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I'm on Fedora 37 and here's `pyproj 3.4.1` available, so super new. But QGIS is a bit old-ish with 3.26.1, so maybe it was fixed already? 

I'm also very new to Fedora, usually using Arch. Will Fedora update (QGIS) releases (patch/minor) or it only gets a new version with a new Fedora release? So far I feel like Fedora is far ahead of even Arch in terms of package releases (pyproj 3.4.1 was released last week), so I'm surprised it doesn't have QGIS 3.28.x.

**Comment by nyalldawson** [comment]
This isn't a qgis issues -- it's either a upstream Fedora packaging issue or a local issue (eg caused by pip installing a library). Either way it can't be solved by qgis and needs filing elsewhere.
