### ISSUE TITLE
[Oracle] Digitizing a new curve not working with QGIS 3.28.1

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#51263]
### What is the bug or the crash?

Hi,

We have a change of behaviour when editing an Oracle layer to add or edit a curve using the digitizing tools, QGIS 3.24 saves a correct 3-nodes arc while 3.28 saves a densified linestring. The base layer and the project are strictly the same.

On this screencap, the upper geometry was created and saved with 3.24.2 and the lower with 3.28.1

![curves](https://user-images.githubusercontent.com/736212/208435656-0afefd78-ef4e-471c-ab88-8d47ead5c085.png)

### Steps to reproduce the issue

1. Open an Oracle table (geom type multiline)
1. QGIS 3.24.2   
   1. Toggle editing
   1. Add a new line feature and toggle Digitize with Curve
   1. Trace a single curve and save
   1. Toggle the vertex tool and click on the created curve -> it shows a curve with only 3 nodes as intended
1. QGIS 3.28.1
   1. Toggle editing
   1. Add a new line feature and toggle Digitize with Curve
   1. Trace a single curve and save
   1. Toggle the vertex tool and click on the created curve -> it shows a densified linestring

### Versions

Both are the official windows packages

QGIS version 3.24.2-Tisler
QGIS code revision 13c1a028

QGIS version 3.28.1-Firenze
QGIS code revision fde3b8fbb8c

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by troopa81** [comment]
#51378 will fix new added layer, but for existing projects, you need to change the geometry type with `CompoundCurve`.

To migrate, with python, you can iterate on your layers and change the dataSource with the following instruction

```python
new_uri=iface.activeLayer().dataProvider().dataSourceUri().replace("type=LineString","type=CompoundCurve")
iface.activeLayer.setDataSource(new_uri, 'test', 'oracle')
```
