### ISSUE TITLE
Cannot save custom CRS

### ISSUE THREAD

**Issue by crclwcca** [qgis/QGIS#51272]
### What is the bug or the crash?

I have fully defined a custom CRS in WKT format. When I try to save it the program attempts to save a custom CRS that is already defined instead of the new one called northwest coast albers - see image.
![qgis custom crs issue](https://user-images.githubusercontent.com/78457199/208812156-c353ea0b-3544-49fd-bdac-3c65ebb6dec0.JPG)

### Steps to reproduce the issue

Try creating a new custom CRS and see if it will properly create the new one.

### Versions

QGIS version
3.22.4-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you share WKT string ?
