### ISSUE TITLE
Yandex online-maps are not displayed

### ISSUE THREAD

**Issue by AnnaBorisenko13** [qgis/QGIS#51275]
### What is the bug or the crash?

dear developers, during proceeding with online maps, few weeks ago we realized that Yandex online maps didn't displayed any more. 

### Steps to reproduce the issue

As I know, Yandex stopped data exchange via the http protocol.
Now only **https** protocol works. Please change source descriptions for Yandex maps on page https://github.com/nextgis/quickmapservices_contrib/commit/91c920d1ee5f25b6ade003be1832cd0cfa4c6336
Thank you for your job! 

### Versions

3.16.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Issue should be reported in https://github.com/nextgis/quickmapservices_contrib/issues. Not a QGIS issue.

**Comment by AnnaBorisenko13** [comment]
ok, i have rescheduled the task into https://github.com/nextgis/quickmapservices_contrib/issues
