### ISSUE TITLE
Value Map

### ISSUE THREAD

**Issue by PennyJClarke** [qgis/QGIS#51274]
### What is the bug or the crash?

I have created a shapefile with (widget type) value map entries in an attribute table, as I would like to standardise terms used in annotating data. When I take the saved shapefile and put it in a new project to ensure I can use the same values, all the columns appear in the new project, but the value map entries are not available and the widget type returns to the default, text edit. Is there a way a shapefile can be created with value maps and then used as template in other projects, retaining all the values?

Thank you for your guidance.

### Steps to reproduce the issue

Select New Shape Layer File from the main toolbar and create a new point shapefile for example. Switch ‘Toggle Editing’ on using the ‘Toggle Editing’ button on the menu (yellow pencil), mark 1 or 2 point features. Right click the shapfile layer, select ‘Properties’ choose 'Fields' from the left sub-menu. Create 2 or 3 new columns in the attribute table (for example, Text (string) type columns), using the 'New field' button when in 'Toggle editing mode'. In the ‘Attributes Form’ tab from the left menu, select the ‘Fields’/columns you wish to create a dropdown for by clicking on the field name, in the widget type select 'value map' and create entries for drop downs. Once the attributes are saved to the shapefile, save and close the project. Re-open a new blank project, from the directory your shapefile is saved to, drop the .shp file into the new project, right click the shapfile layer, select ‘Open Attribute Table’ and see that all columns are visible in the new project, but all drop down options are no longer available.

### Versions

QGIS 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Not  a bug, those are saved in the style, if you want to reuse it just export the style (the full style or only the Forms). Then reload that. I know there is some way to make that more permanent but I'm not sure if that's only a thing in gdb or cannot be done in qgis at the moment.
