### ISSUE TITLE
Node tool 2D + 3D enhancement

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#51270]
### Feature description

When using the node tool on a polyline, it would be great to have length and altitude of nodes and segments displayed on the canvas :

![image](https://user-images.githubusercontent.com/8614223/208692940-622d48da-efc9-4063-b84e-ff8b46030805.png)

This would ease a lot the altimetry control which can be sometimes tidious when searching for a node that is badly referenced in terms of altitude.

### Additional context

Open for any aditional comments on this.

**Comment by saberraz** [comment]
IMO, this can be achieved by the existing labelling. You can simply create a map them for digitizing and switch to that map theme for see these types of information.

**Comment by ponceta** [comment]
@saberraz the idea to to have it diplayed only when editing to avoid any conflict with any map theme.

To my knowledge this can only be achieved on existing entities (and this is a QGIS expert parametrisation that could be brought to any QGIS user)

**Comment by ponceta** [comment]
Searching for developpement proposal.

**Comment by ponceta** [comment]
Listed as a QGIS enhancement proposal submitted to the QGIS-CH group.
