### ISSUE TITLE
Crash on loading a pdf into Georeferencer

### ISSUE THREAD

**Issue by spono** [qgis/QGIS#51289]
### What is the bug or the crash?

the Georeferencer crashes while loading a pdf (both by drag&drop and normal loading); the same pdf loaded in QGIS as a non-referecenced image, shows no issues at all.
After the creation of a new profile, the bug disappears.

### Steps to reproduce the issue

1. drag&drop or load file
2. crash

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.14-Białowieża | QGIS code revision | 4cde646c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.1
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qfieldsync | v4.2.0
QuickOSM | 2.1.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.14-Białowieża
QGIS code revision
[4cde646c](https://github.com/qgis/QGIS/commit/4cde646c)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
qfieldsync
v4.2.0
QuickOSM
2.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Crash ID: [879a975756be959afc2c0bb03704d6ed4641a535](https://github.com/qgis/QGIS/search?q=879a975756be959afc2c0bb03704d6ed4641a535&type=Issues)

Stack Trace

QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_context_delete_cpp_context :
osgeo::proj::operation::Transformation::targetCRS :
_CallSettingFrame_LookupContinuationIndex handlers.asm:98
__FrameHandler4::CxxCallCatchBlock frame.cpp:1393
RcConsolidateFrames :
proj_create :
QgsCoordinateReferenceSystem::operation :
QgsExpressionContextUtils::mapSettingsScope :
QgsMapCanvas::createExpressionContext :
QgsMapCanvas::refreshMap :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.14-Bia?owie?a
QGIS code revision: 4cde646c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.1
Running against GDAL: 3.6.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by nicogodet** [comment]
> After the creation of a new profile, the bug disappears.

Well, it's not a QGIS issue then. 😃 

It's kinda hard to debug this kind of problem...
First, you could try to disable all non-core plugins.
