### ISSUE TITLE
How to Object Capture？

### ISSUE THREAD

**Issue by zhubing1996** [qgis/QGIS#51288]
### Feature description

![image](https://user-images.githubusercontent.com/89522717/209048700-6b86c86a-fc06-4c63-847c-8dc2897113d3.png)
In QGIS, how to draw a new linestring whose starting point is the end of the previous linestring？The magnet icon is on, but there is no object capture。

**Comment by zhubing1996** [comment]
The problem has been resolved and object capture Settings are required

**Comment by DelazJ** [comment]
OK. Then closing.
For reference, this repository is to handle QGIS code and report issues. Not about asking questions. For questions you might need to [check the docs](https://docs.qgis.org/latest) or join the qgis-user mailing list (see [support channels](http://qgis.org/en/site/forusers/support.html)).
Thanks.
