### ISSUE TITLE
Error at raster conversion from Tiff to MRF

### ISSUE THREAD

**Issue by Gurkitier** [qgis/QGIS#51290]
### What is the bug or the crash?

In the gdal raster tool "raster conversion" there is an error if i try to convert a 3-channel tiff (aerial image with 20cm GSD) to the format MRF. I used jpeg compression. 
The converted MRF isn't complete and has pixel errors (just coloured pixels).
Also if i try to convert it without compression the mrf-file has just coloured pixel as result.
Isn't it possible to convert images with 3 channels or it is a bug.

First is the original image, second after conversion to MRF.
![image](https://user-images.githubusercontent.com/121234568/209139045-7c6f2f78-4568-4669-b501-c145d8ee07d4.png)
![image](https://user-images.githubusercontent.com/121234568/209139324-888b47dc-fd81-4b8d-9418-6fe458f769f1.png)

Best regards
Isabell

### Steps to reproduce the issue

1. Go to Raster ->conversion -> convert
2. Input image: 3-channel-tiff (RGB)
![image](https://user-images.githubusercontent.com/121234568/209140215-f4bca5e4-1ec3-4452-ac6a-62649aa5bf9c.png)

### Versions

QGIS-Version
3.22.13-Białowieża
QGIS-Codeversion
02ff117c
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.0
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
14.3
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
copy_coords
0.2
hoehengenauigkeitanflaechen
0.1
ndom_berechnen
0.1
schwellwertndvi
0.1
wbt_for_qgis
1.0.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can you reproduce the issue running the GDAL command (the one displayed at bottom of alg window) in OSGeo4W Shell ?

If yes, it might be a GDAL issue and should be reported on https://github.com/OSGeo/gdal/issues

**Comment by Gurkitier** [comment]
Hello, 
sorry for the late answer (holidays : ) ). It doesn't work in the OSGeo4W Shell neither using the same GDAL command. Maybe the problem are the three channels? I just use the GDAL command

gdal_translate -a_srs EPSG:25832 -of MRF C:/Temp/AdV/COG_Gdal/Data/122013_0_0275_rgbi.tif C:/Temp/AdV/COG_Gdal/Output/122013_0_0275_rgbi.mrf

Do I have to specify the three channels somewhere?

Best regards
Isabell

**Comment by nicogodet** [comment]
You could ask on https://lists.osgeo.org/mailman/listinfo/gdal-dev.

As it doesn't work either in shell, it's not a QGIS issue.
Closing for now, don't hesitate to ask for re-open if it ends being a QGIS issue after all.
