### ISSUE TITLE
filter by array

### ISSUE THREAD

**Issue by yulinhuyang** [qgis/QGIS#51308]
### Feature description

I use    id = [14680832, 56, 12] in json, but it can not filter by qgis  ，can you provide the filter feature for the arry filter

**Comment by m-kuhn** [comment]
Does [`setFilterFids`](https://qgis.org/pyqgis/3.0/core/Feature/QgsFeatureRequest.html#qgis.core.QgsFeatureRequest.setFilterFids) or `setFilterExpression` with `"attribute" in (14680832, 56, 12)"` work for you?
