### ISSUE TITLE
QGIS 3.28.2 gpx files missing / unselectable

### ISSUE THREAD

**Issue by derEremit** [qgis/QGIS#51307]
### What is the bug or the crash?

After latest update of the flatpack opening a workig project I get a prompt about missing files
the gpx files are in the project directory

I can ignore to load the project but in the browser no gpx files show up, at locations where they are definitely located

when reverting flathub to a previous version everything works again

### Steps to reproduce the issue

Try to open a gpx file with said version

### Versions

QGIS version | 3.28.2-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.7
Python version | 3.9.9
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.36.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Does this happen with the latest versions? Does this happen when QGIS is installed from official packages?

**Comment by derEremit** [comment]
I cannot reproduce it anymore
was fixed with some flatpack update

running 3.28 deb
and 3.32 flatpack 
on different machines without problem
