### ISSUE TITLE
Updating Windows build instruction

### ISSUE THREAD

**Issue by Kanahiro** [qgis/QGIS#51305]
### Feature description

I was not sure whether this issue is suited here or https://github.com/qgis/QGIS-Documentation but documents regarding compiling are in this repo and posted this issue here.

These days I've tried to compile QGIS for Windows. I could get informations in https://github.com/qgis/QGIS/blob/master/INSTALL.md . This is great for Ubuntu but for Windows the description seems to be obsolete. For example, the documents instruct using Visual Studio 2015 but this is not available now.

On the other hand, I was also able to get a description about build "Portable" QGIS in [Github Actions Workflow](https://github.com/qgis/QGIS/blob/master/.github/workflows/mingw64.yml). This works well but it seems to include minimum features for debugging.

Question:
1. Is there any documentation about compiling QGIS for Windows with full features? (Python, GRASS, SAGA... same to installers distributed in QGIS-website)
2. If the answer for `1` is no, IMHO it may be very good to improve documents, how do you think?

**Comment by alexbruy** [comment]
Already updated.
