### ISSUE TITLE
Processing algorithms hang when accessing authManager without loaded master key

### ISSUE THREAD

**Issue by olivierdalang** [qgis/QGIS#51317]
### What is the bug or the crash?

When a processing algorithm makes use of the authManager and the master password is not in the cache, the user is prompted for the master password. However, when entering the correct password, the algorithm then hangs.

### Steps to reproduce the issue

1. Make sure the master password can't be retrieved from the password manager automatically by unchecking `Integrate master password with you password manager` in `Settings>Authentication>Management>Utilities`
2. Make sure the master password is not set by running `QgsApplication.instance().authManager().clearMasterPassword()` in the console
3. Create a python algorithm containing the following snippet
```python
from qgis.core import QgsProcessingAlgorithm, QgsApplication

class ExampleProcessingAlgorithm(QgsProcessingAlgorithm):
    # ...
    def processAlgorithm(self, parameters, context, feedback):
        # ...
        manager = QgsApplication.instance().authManager()
        value = manager.authSetting("MY_KEY", None, True)
        feedback.pushInfo(f"Auth setting `MY_KEY` is {value}"
```
4. Run the algorithm
5. When prompted, enter your master password
6. It hangs

### Versions

QGIS version
3.28.1-Firenze
QGIS code revision
fde3b8fbb8c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.2
QuickWKT
3.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I guess it has to do with threading, since when running the exact same algorithm from python using processing.run, it does not hang.

**Comment by nicogodet** [comment]
Does adding the following in your class help ?

```python
    def flags(self):
        return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

**Comment by olivierdalang** [comment]
Yes it does (doesn't hang, works as expected), so the issue is definitely linked to threading. Thanks for the input !

**Comment by nicogodet** [comment]
Not sure this is a real issue.
You are accessing GUI from another thread than main thread.

Maybe you should have a look at https://qgis.org/pyqgis/master/core/QgsProcessingAlgorithm.html#qgis.core.QgsProcessingAlgorithm.prepareAlgorithm

Gentle ping @nyalldawson. Your insight would be more than welcome.

**Comment by m-kuhn** [comment]
[`prepareAlgorithm`]([qgis.org/pyqgis/master/core/QgsProcessingAlgorithm.html#qgis.core.QgsProcessingAlgorithm.prepareAlgorithm](https://qgis.org/pyqgis/master/core/QgsProcessingAlgorithm.html#qgis.core.QgsProcessingAlgorithm.prepareAlgorithm)) is definitely the way to go, where any data from objects living on the main thread (`object.thread() == QgsApplication.instance().thread()`) can be copied safely to a temporary location from where the processing thread can access it.

> prepareAlgorithm should be used to handle any thread-sensitive preparation which is required by the algorithm

Note: there are tricks to access this in a _safer_ way via [`BlockingQueuedConnection`](https://doc.qt.io/qt-6/qt.html#ConnectionType-enum) however _safer_ is not necessarily _safe_.

**Comment by nicogodet** [comment]
@m-kuhn Let's close ?
