### ISSUE TITLE
Qgis 3.22.14 doesn't find .csv files

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#51312]
### What is the bug or the crash?

I've a project saved in Qgis 3.22.12 with a couple of .csv files.
When I open this project with Qgis 3.22.14 everything works well, but if I save the project and then I reopen it, Qgis tells me that it can't find the 2 .csv files.

If I reopen the project saved with old 3.22.12 Qgis shows the files.

So there's something wrong with the saving process to the new Qgis verison 3.22.14
[fari.csv](https://github.com/qgis/QGIS/files/10313333/fari.csv)

### Steps to reproduce the issue

I tried to repair the sources for the 2 .csv but nothing happens and Qgis can't show me the files.

I tried to add them from scratch to both projects  saved in 3.22.12 and .14 with last Qgis but it doesn't work.

I tried to add the from scratch in a blank project and it shows the files, but if I save the project and then I reopen it Qgis doesn't find the .csv files.

If I reopen the project saved with old 3.22.12 Qgis shows the files.

### Versions

Versione di QGIS
3.22.14-Białowieża
Revisione codice QGIS
4cde646c
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.6.1
Versione PROJ
9.1.1
Versione database del Registro EPSG
v10.076 (2022-08-31)
Versione GEOS
3.11.1-CAPI-1.17.1
Versione SQLite
3.39.4
Versione PDAL
2.4.3
Versione client PostgreSQL
14.3
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
azimuth_distance_measurement
0.4
clipper
1.2
coordinates_converter
1.0
DigitizingTools
1.5.1
latlontools
3.6.6
map-coords-plugin
2.0.0
points2one
3.0.1
profiletool
4.2.2
Qgis2threejs
2.7.1
quick_map_services
0.19.32
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Is it a flatpack install ?

**Comment by nicogodet** [comment]
Looks similar to #51307

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (b4c24c72e986c6de621bba0a6201466e27401bcf).
