### ISSUE TITLE
QGIS 3.22.14 does not show timestamp values from PostgreSQL EDB 

### ISSUE THREAD

**Issue by nlssakokorhonen** [qgis/QGIS#51315]
### What is the bug or the crash?

QGIS 3.22.14 attribute table shows null value in timestamp column from PostgreSQL EDB. Database manager shows correct values.

Database version
PostgreSQL 14.5 (EnterpriseDB Advanced Server 14.5.0) on x86_64-pc-linux-gnu, compiled by gcc (GCC) 8.5.0 20210514 (Red Hat 8.5.0-10), 64-bit

### Steps to reproduce the issue

1. create table with timestamp column for example
create table example (
id serial,
created_at timestamp without time zone NOT NULL
   DEFAULT (current_timestamp AT TIME ZONE 'UTC'))
)
2. add some data and add table to project
3. open attribute table

Screenshots from database manager, attribute table and layer properties below
![image](https://user-images.githubusercontent.com/75304649/209806894-0db595b8-e1d9-4ae3-a504-0ab84ad9062d.png)

![image](https://user-images.githubusercontent.com/75304649/209807361-f8c297db-adf3-4a7f-9b27-1f8c672095aa.png)

### Versions

QGIS version
3.22.14-Białowieża
QGIS code revision
4cde646c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by troopa81** [comment]
I fail to reproduce the issue on Postgres 14.5 on Debian with a QGIS 3.22.12.

I'm updating on last QGIS 3.22 check if I can reproduce.

I don't have Postgres EDB but I really doubt that it could be related to this.

**Comment by troopa81** [comment]
> I'm updating on last QGIS 3.22 check if I can reproduce.

it works also with 3.22.15

**Comment by troopa81** [comment]
Did you configure something in the attribute form?

**Comment by troopa81** [comment]
or did you change something in the project properties?

**Comment by nlssakokorhonen** [comment]
no I did not change the attribute form. this is reproducible only with EDB database. this issue https://github.com/qgis/QGIS/issues/39929 seems similar to this one

**Comment by troopa81** [comment]
Ok, I managed to install a edb postgres version and reproduce the issue. Let see if I can do something

**Comment by troopa81** [comment]
Enterprisedb change default datestyle but ISO format is expected by QGIS. According to Postgres [documentation](https://www.postgresql.org/docs/9.1/datatype-datetime.html)

> The SQL standard requires the use of the ISO 8601 format

So I'd say that it's normal that QGIS expect this date format. 

You can change the default style of your postgres cluser by modifying `postgresql.conf` file 

> datestyle = 'iso'

**Comment by LKajan** [comment]
Thanks @troopa81 for finding the issue!
May I still suggest a fix to QGIS? Could QGIS set the datestyle to iso format for the session when connecting to PostgreSQL style database? I think it is better to explicitly set the datestyle rathen than just assume database has a right configuration.

**Comment by troopa81** [comment]
@LKajan Yes, you probably right. I'll try to propose a fix by the end of the month

**Comment by nlssakokorhonen** [comment]
Fixed by setting environment variable PGDATESTYLE=iso in QGIS startup script

**Comment by troopa81** [comment]
I'm re-opening this issue in order to propose a fix that would avoid setting the environment variable
