### ISSUE TITLE
Only the first parameter is displayed in the methods summary table

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#51325]
### What is the issue about the documentation?

For example, in https://qgis.org/pyqgis/3.28/core/QgsGeometryCollection.html, the [asGml2](https://qgis.org/pyqgis/3.28/core/QgsGeometryCollection.html#qgis.core.QgsGeometryCollection.asGml2) and [asGml3](https://qgis.org/pyqgis/3.28/core/QgsGeometryCollection.html#qgis.core.QgsGeometryCollection.asGml3) methods take more than one parameter but only the first one (`doc`) is displayed in the table

![image](https://user-images.githubusercontent.com/7983394/209980013-ab7fa202-330b-4a9a-b487-ed6c0c1a89e4.png)

**Comment by nyalldawson** [comment]
This looks fixed now
