### ISSUE TITLE
QGis.layerTreeView.selectedNodes has wrong return type

### ISSUE THREAD

**Issue by Kristof-Carlier** [qgis/QGIS#51322]
### What is the bug or the crash?

According to documentation: 
QGis.layerTreeView.selectedNodes() should return List[QgsLayerTreeNode]. Instead, it returns List[QgsLayerTreeLayer]

I think it is a bug rather than a mistake in the documentation because there is another function (selectedLayerNodes() ) that returns List[QgsLayerTreeLayer] as well.

### Steps to reproduce the issue

Open the console window, create a new python script and run the code below.

_iface = qgis.utils.iface
layerTree = iface.layerTreeView()
selectedNodes = layerTree.selectedNodes(False) # => list of QgsLayerTreeLayer
print("selectedNodes:")
print(selectedNodes) 
selectedLayerNodes = layerTree.selectedLayerNodes() # => list of QgsLayerTreeNode
print("selectedLayerNodes:")
print(selectedLayerNodes)_ 

I have one layer selected in the legend. Running the code yields this output:
selectedNodes:
[<QgsLayerTreeLayer: _[layerName]_>]
selectedLayerNodes:
[<QgsLayerTreeLayer: _[layerName]_>]

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-versie | 3.22.10-Białowieża | QGIS code revisie | 6a63fd37
-- | -- | -- | --
Qt versie | 5.15.3
Python versie | 3.9.5
GDAL/OGR versie | 3.5.1
PROJ versie | 9.0.1
EPSG-register databaseversie | v10.064 (2022-05-19)
GEOS versie | 3.10.3-CAPI-1.16.1
SQLite versie | 3.38.1
PDAL versie | 2.4.2
PostgreSQL client versie | 14.3
SpatiaLite versie | 5.0.1
QWT versie | 6.1.6
QScintilla2 versie | 2.13.1
OS versie | Windows 10 Version 2009

</body></html>QGIS-versie
3.22.10-Białowieża
QGIS code revisie
[6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.5.1
PROJ versie
9.0.1
EPSG-register databaseversie
v10.064 (2022-05-19)
GEOS versie
3.10.3-CAPI-1.16.1
SQLite versie
3.38.1
PDAL versie
2.4.2
PostgreSQL client versie
14.3
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> I have one layer selected in the legend. Running the code yields this output:

@Kristof-Carlier Add a group to your project and retry with both the group and layer selected: you won't get the same result; selectedNodes would return both layers and group (hence a list of [QgsLayerTreeNode](https://qgis.org/pyqgis/master/core/QgsLayerTreeNode.html#qgis.core.QgsLayerTreeNode)) while selectedLayerNodes returns only layers.
Not an issue afaics.

**Comment by roya0045** [comment]
I agree with @DelazJ , it literally can't return anything else https://github.com/qgis/QGIS/blob/087e55d5291c166dea25b6266ed952187a9ea438/src/gui/layertree/qgslayertreeview.h#L244
