### ISSUE TITLE
Just a crash report.

### ISSUE THREAD

**Issue by QuickDoc** [qgis/QGIS#51338]
## User Feedback

I opened QGIS.  I did NOT open a project.
I hid two network/thumb drives in the browser.  
Neither of them is being used in my current project. 
I exited QGIS.
I re-opened QGIS.
I tried to launch my current project.
QGIS crashed.

It has been several versions since I used QGIS as my primary GIS program.
This version has been VERY SLOW.
Any time I click on ANYTHING, there are several minutes of waiting due to QGIS "not responding."  I was trying to disconnect the network drives to fix this problem.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000134e4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

I opened QGIS.  I did NOT open a project.
I hid two network/thumb drives in the browser.  
Neither of them is being used in my current project. 
I exited QGIS.
I re-opened QGIS.
I tried to launch my current project.
QGIS crashed.

### Versions

QGIS Info
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I'm one version (3.28.1) behind the current.  This is the first project launch crash I've had, so I'll update to the current version and see if it happens again.

**Comment by agiudiceandrea** [comment]
@QuickDoc could you please try if the issue does occur also using a new QGIS user profile? Does the issue also occur also deactivating the Browser panel?
