### ISSUE TITLE
How to update manually an R package in QGIS (folder rlibs)

### ISSUE THREAD

**Issue by Cebrian007** [qgis/QGIS#51332]
### Feature description

Good morning everyone.

I can't run an R script in QGIS because I need to update one package in the folder rlibs, where are all the R packages in QGIS.
Could someone tell me how to update manually a package in the folder rlibs. I have been searching for a solution for various days but I cannot find it. 

Many thanks and merry xmas everyone.

Best wishes,

David

**Comment by agiudiceandrea** [comment]
@Cebrian007 "Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features."
