### ISSUE TITLE
Unable to install on Windows 11 21H2

### ISSUE THREAD

**Issue by scribaoliv** [qgis/QGIS#51336]
### What is the bug or the crash?

I bought a new machine and am trying to install Qgis. At the end of the installation I get the following 2 error messages... 
and the installation is cancelled. 
The problem occurs with both 3.22 and 3.28 installers (QGIS-OSGeo4W-3.22.0-3.msi, QGIS-OSGeo4W-3.28.2-1.msi).
I specify that I had no problem with the previous machine (Windows 10 version 2004).
Please help ! Thanks.
![Messag2](https://user-images.githubusercontent.com/96916422/210062154-7d9eaef5-56da-4f13-a62d-793bd2b0a58f.png)
![Messag1](https://user-images.githubusercontent.com/96916422/210062157-e8a5f2d6-2944-4e2d-9790-0cf035e7facc.png)

### Steps to reproduce the issue

Launch the installers.

### Versions

Édition	Windows 11 Professionnel
Version	21H2
Build 	22000.918
Expérience Pack  1000.22000.918.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
Hi @scribaoliv This is not a QGIS issue. Please search for "windows error code 2502" on the Internet and you might find many pages explaining what this issue is and how to fix it. I'm not enough a Windows user to advise one particular link.
Closing as upstream.
