### ISSUE TITLE
Bug for Mac OSx - Qgis doesn't open after download

### ISSUE THREAD

**Issue by ghost** [qgis/QGIS#51334]
### What is the bug or the crash?

Hi, 

These past few days I've been trying to use again Qgis with the same computer as before and it doesn't work.
I've downloaded the two last versions for Mac (3.28 and 3.22) and after the download is complete, when I try to open the app it never succeeds. Finally after trying to open it many times in a row, my computer showed me a message saying that it wasn't sure that this app was safe so it wouldn't authorise it to open and I should contact the app support…

Can someone help me?

Thanks, 

IMS

### Steps to reproduce the issue

1. download the app
2. verifications
3. trying to open
4. opening denied 

### Versions

Qgis 3.28 and 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Isabault, have you read the advise in the QGIS installer for macOS download page?
"macOS High Sierra (10.13) or newer is required. QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open."
![image](https://user-images.githubusercontent.com/16253859/210157002-5c8dd631-61ec-48d0-9837-c6370b67f61a.png)
Is such advise useful for you?
