### ISSUE TITLE
Atlas Export to PDF

### ISSUE THREAD

**Issue by elch-0815** [qgis/QGIS#51344]
### Feature description

When exporting an atlas, it is possible to export to pdf 
with using @atlas_featurenumber or @atlas_featureid
as <filename>.pdf

when you use @atlas_pagename then a new directory is created 
and a file named 000.pdf is created.
This also happens when you use a fieldcontent as pdf-filename.

This is, when you want to create many files pretty unpractible.

When the filename will be unique, it should also be possible to 
export to @atlas_pagename.

**Comment by roya0045** [comment]
Is this a bug report?
