### ISSUE TITLE
No entry for QgsPainting.BlendXor in layer blending properties (GUI)

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#51340]
### What is the bug or the crash?

While looking for details on the blend masking options, I came across a BlendXor option that is available in source code
(https://github.com/qgis/QGIS/search?q=blendxor) and exposed in [pyQGIS docs](https://qgis.org/pyqgis/master/core/QgsPainting.html#qgis.core.QgsPainting.BlendXor) but I can't find it in QGIS GUI.
It is also mentioned in the [QEP](https://github.com/qgis/QGIS-Enhancement-Proposals/issues/235)

### Steps to reproduce the issue

1. Add layers to a group
2. In layer Styling panel, set the group to "render layers as a group"
3. Select a layer and still in the layer styling panel, symbology tab, unfold the "Layer rendering" group
4. click a blending mode drop-down menu: you get 6 additional options at the bottom instead of 7

Seems there is a missing entry here
https://github.com/qgis/QGIS/blob/0889bb92c3ac78e0c14676fc4d6b6450bb31a63e/src/gui/qgsblendmodecombobox.cpp#L61-L70

### Versions

QGIS 3.28 and master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I omitted this because I can't see *any* time when an XOR blending will give useful results...

**Comment by alexbruy** [comment]
Can be closed?
