### ISSUE TITLE
QGIS crashes or quits automatically when trying to calculate the latitude of a point layer

### ISSUE THREAD

**Issue by rinelfi-git** [qgis/QGIS#51342]
### What is the bug or the crash?

When generating latitude coordinate from a point the application crashes. It doesn't happen when I want to calculate the longitude coordinate.

### Steps to reproduce the issue

on a point shape, go to attribute table > field calculator > search for "$y" > double click on it > press OK

### Versions

3.22.14-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@rinelfi-git could you please
1. specify the operative system used?
2. provide the layer with the feature geometry that causes the issue?
3. try if the issue does occur also with a new QGIS user profile?

**Comment by rinelfi-git** [comment]
the issue happens both on windows and linux for the version 3.22 LTR and 3.28 non LTR. On linux it simply quits and doesn't give a report, though on Windows it shows a report message when I reopen the program after it crashes.
The layer is a vector, a point.

**Comment by agiudiceandrea** [comment]
@rinelfi-git could you please provide the layer with which the issue does occur?

**Comment by agiudiceandrea** [comment]
@rinelfi-git what is report message displayed by QGIS after the crash?

**Comment by rinelfi-git** [comment]
I think it's solved by reinstalling it. I use the 3.22 LTR now and it works.
