### ISSUE TITLE
Program Crashed on Raster Calculator

### ISSUE THREAD

**Issue by joseluislandivars** [qgis/QGIS#51350]
## User Feedback

I tried using the Raster calculator to substract 2 layers.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004b0c (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Add 2 raster layers (DSM & DTM .tiff)
Open raster calculator
CHM = DSM - DTM
Click on "Run"
-> Program Crashed

### Versions

QGIS version
3.26.2-Buenos Aires
QGIS code revision
feec3d3b12f
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
LAStools
1.4
pointsamplingtool
0.5.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
3.26.2 is outdated, also did you use the assignment operator in the formula or only the subtraction?

**Comment by joseluislandivars** [comment]
@roya0045 this is what I did: "20220616_cc_p4r_parking_25m_NTRIP_dsm@1" - "20220616_cc_p4r_parking_25m_NTRIP_dtm@1"

**Comment by nicogodet** [comment]
Can you update to 3.28.2 ?
Retry with a new profile ?

If you can still reproduce the crash, can you share the data ?

**Comment by joseluislandivars** [comment]
I uninstalled QGIS running ‘C:\OSGeo4W64\bin\osgeo4w-setup.exe’ and then deleted the C:\OSGeo4W64\ folder to remove installer files.
Then, I installed the latest LTR (Version 3.22.14 LTR). This has solved my problem.

Thank you everyone!

Best regards,
Jose L. Landivar

From: Nicolas Godet ***@***.***>
Date: Monday, January 2, 2023 at 1:47 AM
To: qgis/QGIS ***@***.***>
Cc: Jose Luis Landivar Scott ***@***.***>, Author ***@***.***>
Subject: Re: [qgis/QGIS] Program Crashed on Raster Calculator (Issue #51350)

Can you update to 3.28.2 ?
Retry with a new profile ?

If you can still reproduce the crash, can you share the data ?
