### ISSUE TITLE
user error on startup in Qgis

### ISSUE THREAD

**Issue by Alexandra1906** [qgis/QGIS#51354]
### What is the bug or the crash?

user error table vw_srs already exists on startup
Reinstalling the program doesn't help.
The program starts but lacks many functions
Please help, it's been too long...

### Steps to reproduce the issue

See error on starup

### Versions

Qgis 3.24.14 and Qgis 3.28.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Alexandra1906 could you please specify the Operative System on which QGIS runs and also report the whole info contained in the Help->About QGIS window (as requested in the issue report form)?
