### ISSUE TITLE
Measure dialog box closure closes the application

### ISSUE THREAD

**Issue by parsexyz** [qgis/QGIS#51365]
### What is the bug or the crash?

QGIS 3.28.2 Firenze code version b47e00ba60 
The dialog box for measure in length works properly.
Switch to Measure Angle or Bearing measurement. 
Do a measurement and then close the dialog box and see the application crash

### Steps to reproduce the issue

Open a project
1. Measure Angle
2. Close the dialog box

### Versions

QGIS 3.28.2 Firenze code version b47e00ba60 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Can you provide the full info needed about your setup?

**Comment by parsexyz** [comment]
Mac OS, I provided the version of software in the Buy report. OS is Venture 13.0.1

Jay Fallah| Founder & CTO| [Parsedata](https://www.parsedata.xyz)
t: 647.927.9990 | ***@***.******@***.***
1655 Dupont Street, Suite 101 Toronto ON M6P 3T1 CANADA
Disclaimer: This e-mail message is intended only for the person or entity to which it is addressed and is confidential, subject to copyright and may be legally privileged. Any unauthorized review, use or disclosure is prohibited. If you received this in error, please contact the sender and delete all copies of the e-mail together with any attachments.

------- Original Message -------
