### ISSUE TITLE
Atlas WIDTH does not fit to coverage layer

### ISSUE THREAD

**Issue by sylviaobk** [qgis/QGIS#51364]
### What is the bug or the crash?

Hi all,

when creating an atlas the result bounding-boxes differ from the shapes. But only WIDTH, not HEIGHT. I removed some results to show the effect. All results are complete but in the same way too wide:
![Anmerkung 2023-01-03 143344](https://user-images.githubusercontent.com/20552367/210367437-5474fb6e-8422-4a8c-a6ae-ad9dc48a9250.png)

Thank you, Sylvia

### Steps to reproduce the issue

This is the coverage layer:
![Abdeckungslayer](https://user-images.githubusercontent.com/20552367/210368388-09d87a74-6551-4b9d-a19d-3aa780ec1574.png)
Create an atlas:
![Layout](https://user-images.githubusercontent.com/20552367/210368271-7721cd17-904b-40c4-b011-fe6d324f4cbe.png)
![Atlas](https://user-images.githubusercontent.com/20552367/210368295-5ac5afa2-5f36-4ecb-877d-c746b9ff8de2.png)
![Elementeigenschaften](https://user-images.githubusercontent.com/20552367/210368307-e451177d-b26a-4046-bb14-4177b7f120af.png)
![Export](https://user-images.githubusercontent.com/20552367/210368326-10b50609-1e53-4ea5-aa7e-51936033e476.png)

### Versions

QGIS-Version
3.10.7-A Coruña
QGIS-Codeversion
7b4ca4c8d0
Kompiliert gegen Qt
5.11.2
Laufendes Qt
5.11.2
Kompiliert mit GDAL/OGR
3.0.4
Läuft mit GDAL/OGR
3.0.4
Kompiliert mit GEOS
3.8.1-CAPI-1.13.3
Läuft mit GEOS
3.8.1-CAPI-1.13.3
Kompiliert mit SQLite
3.29.0
Läuft mit SQLite
3.29.0
PostgreSQL-Client-Version
11.5
SpatiaLite-Version
4.3.0
QWT-Version
6.1.3
QScintilla2-Version
2.10.8
Kompiliert mit PROJ
6.3.2
Läuft mit PROJ
Rel. 6.3.2, May 1st, 2020
BS-Version
Windows 10 (10.0)
Aktive Python-Erweiterungen
attributeBasedClustering; 
bkggeocoder; 
drucker; 
geometry_paster; 
OSMDownloader; 
pluginbuilder3; 
punkte_setzen; 
qdraw; 
spw2_print_straßenverzeichnis; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by sylviaobk** [comment]
Sorry, I wrote the wrong Version, 
this one is right:

QGIS-Version
3.22.11-Białowieża
QGIS-Codeversion
106d33d7
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.1
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.4.3
PostgreSQL-Client-Version
14.3
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009




Aktive Python-Erweiterungen
attributeBasedClustering
2.2
bkggeocoder
1.3.2
drucker
3.1.0
geometry_paster
0.1.1
OSMDownloader
1.0.3
pluginbuilder3
3.2.1
punkte_setzen
1.0
qdraw
3.0.1
spw2_print_straßenverzeichnis
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

**Comment by andreasneumann** [comment]
@sylviaobk - can you share a project?

Did you make sure that the width/height ratio of your coverage layer polygons is the same in the map frame in your layout? QGIS doesn't automagically adjust your map frame to the ratio of the polygons in your coverage layer - you have to make sure yourself that the width/heigh ratios are matching ...

**Comment by sylviaobk** [comment]
Hello Andreas,

I didn't adjust the ratio. When I do everything is fine!
Thank you.
