### ISSUE TITLE
Georefeencing: 3.36 works correctly but 3.28 display wrong coordinate in a file previously referenced in 3.26

### ISSUE THREAD

**Issue by ambrogiomanzino** [qgis/QGIS#51367]
### What is the bug or the crash?

BUG
In a 3.26 Buenos Aires version I've georefered a cadastral map with local coordinates (Italian Cassini Soldner with local origin). The X coordinates increase from left to right an Y from bottom to top, but the Ys are negative.
Whith the 3.26 version all works correctly and the world file is correct.
With the Firenze version the world file is incorrect, but, also...
Using the jpeg and the world file correctly refered in 3.26 version into Firenze edition the coordinates displayed are wrong.
NEXT VERSION
Can you add Cassini Soldner reference system?
Can you add a local system (name sometime Eulerian system?)
[34.zip](https://github.com/qgis/QGIS/files/10339934/34.zip)
 

### Steps to reproduce the issue

Use georeference raster

### Versions

3.28.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@ambrogiomanzino, could you please create a bug report for each bug, create a feature request for each feature request, provide the CRS of the layer 34.jpg/34.jgw and provide the content of the QGIS Help menu -> About window as requested in the issue report form?

**Comment by mmokrejs** [comment]
I had some aerial images roughly georeferenced from the Cadastral institute and that broke QGIS and thy also loaded in a completely wrong area. Zap the georef values info before opening them in Georeferencerer. See bug #51814.

**Comment by mmokrejs** [comment]
Still I do not understand why the existing georeferencing info cannot be just ignored during data import/reading. Deriving a modified copy with removed georeferences info is awkward and takes space. Moreover, seems there are many ways to embed the georeferencing info into a file or into an adjacent file, causing more confusion.

**Comment by mmokrejs** [comment]
Still I do not understand why the existing georeferencing info cannot be just ignored during data import/reading. Deriving a modified copy with removed georeferences info is awkward and takes space. Moreover, seems there are many ways to embed the georeferencing info into a file or into an adjacent file, causing more confusion.

**Comment by mmokrejs** [comment]
Still I do not understand why the existing georeferencing info cannot be just ignored during data import/reading. Deriving a modified copy with removed georeferences info is awkward and takes space. Moreover, seems there are many ways to embed the georeferencing info into a file or into an adjacent file, causing more confusion.
