### ISSUE TITLE
Layer removing problem

### ISSUE THREAD

**Issue by Elpasha55** [qgis/QGIS#51366]
### What is the bug or the crash?

Layer removing error

### Steps to reproduce the issue

I try to delete one of the layer (line) from Qgis, but it can not be deleted. It is just stuck/adhered, although I untick/deactivate all the layer from Layers panel. This is the third time happening, last time I exported the file, and opened again with new, it dissapeared. 

### Versions

QGIS Desktop 3.22.14

![elgun_unremoved_linee](https://user-images.githubusercontent.com/121881765/210387618-d74eaa42-fb24-47c6-9981-40152317d859.jpg)

 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It looks like the temporary rubberband that is created by Measuring Tool.
![image](https://user-images.githubusercontent.com/39594821/210395365-df71f3bc-fbb0-4bf7-b3ae-d1306f342f7d.png)

You didn't check "I tried with a new profile". Please try with a new qgis user profile to avoid any interference with plugins...

**Comment by Elpasha55** [comment]
Thanks. I have another question in regard to removing the text. I clicked -Create Text at Point, but I can't find the way to remove them. Thank
![Removing Text words](https://user-images.githubusercontent.com/121881765/210859907-f9266eb9-9b49-4bbb-b1e0-b168d5e9da38.jpg)
 you

**Comment by Elpasha55** [comment]
Thank you
