### ISSUE TITLE
Unable to save the GPS tracking in a Log file

### ISSUE THREAD

**Issue by bdelangue** [qgis/QGIS#51372]
### What is the bug or the crash?

Since several QGIS versions, the GPS tracking doesn’t work because it is impossible to define a path and a file. In the GPS Information panel, even when the Log file is activate, the button below, used to define the path and the file, stays grayed out and remains inactive.

### Steps to reproduce the issue

Go to the GPS Information Panel 
Scroll down to the bottom of the panel
Activate the Log File
The issue is that the Log file buttom stay grayed out and is unusable.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.10-Białowieża | QGIS code revision | 6a63fd37
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.38.1
PDAL version | 2.4.2
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geo2france | 0.9.2
HCMGIS | 22.8.8
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.10-Białowieża
QGIS code revision
[6a63fd37](https://github.com/qgis/QGIS/commit/6a63fd37)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.2
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geo2france
0.9.2
HCMGIS
22.8.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@bdelangue, this bug was already fixed for QGIS 3.28 with https://github.com/qgis/QGIS/pull/49912 by @nyalldawson, but it seems the fix wasn't backported to 3.22.

**Comment by agiudiceandrea** [comment]
The 3.22 release has reached end of support.
