### ISSUE TITLE
3D map failure due to `QGIS_PROTECT_QOBJECT_THREAD_ACCESS`

### ISSUE THREAD

**Issue by benoitdm-oslandia** [qgis/QGIS#51381]
### What is the bug or the crash?

I was unable to load a DTM + building objects (from testdata) due to the `QGIS_PROTECT_QOBJECT_THREAD_ACCESS` macro in `QgsMapLayer::extent()`. 

The 3D view tries infinitly to load the tiles.

### Steps to reproduce the issue

1. load the [tests/testdata/3d/buildings.shp](file:///home/bde/prog/2010_25_lille_3d/qgis/tests/testdata/3d/buildings.shp) and the [tests/testdata/3d/dtm.tif](file:///home/bde/prog/2010_25_lille_3d/qgis/tests/testdata/3d/dtm.tif) DTM
2. open the 3D map view 
3. wait in loop

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

If I comment the macro `QGIS_PROTECT_QOBJECT_THREAD_ACCESS`  in `QgsMapLayer::extent()`, it works but with a lot of logged messages from other `QGIS_PROTECT_QOBJECT_THREAD` macro. 

To remove all flooding logs I had to:
* comment the macro `QGIS_PROTECT_QOBJECT_THREAD_ACCESS`  in `QgsRasterLayer::dataProvider`.
* remove the **failing** calls to `moveToThread` in `QgsRasterLayerRenderer` 
   ```
   src/core/qgsmessagelog.cpp:29 : (logMessage) [42ms] [thread:0x5647018dc530] 2023-01-05T16:25:55 Qt[1] QObject::moveToThread: Current thread (0x5647018dc530) is not the object's thread (0x564700d184e0).
   Cannot move to target thread (0x5647018dc530)
   ```

* remove the **failing** calls to `moveToThread` in `_readDtmData`  from `qgsdemterraintileloader_p.cpp`

By the way, as the tile loading is made in different threads (see `qgsvectorlayerchunkloader_p.cpp#100`) I do not know how to fix this issue (may be by using something like `QgsExpressionUtils::runMapLayerFunctionThreadSafe`?).

**Comment by uclaros** [comment]
This has been taken care of in #51304
