### ISSUE TITLE
Checking "Render layers as a group" is automatically reverted

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#51393]
### What is the bug or the crash?

Days I'm playing with the "Render layers as a group" option and I might have checked/unchecked it successfully about a hundred times. But suddenly I realized that if I check the option, switch to a layer and get back to the group, the option is unchecked.
Afaict, I did no special changes in-between (no install, no update, no rebuild, same layers); i might have saved the project as in the meantime.
I tried the project in a new profile: still buggy but testing the option in another project in both profiles works correctly.

Here is the culprit project file: you might need memory layer saver plugin.
[blending_examples.zip](https://github.com/qgis/QGIS/files/10367301/blending_examples.zip)

Here an "older" version of the file that worked
[blending_examples_correct.zip](https://github.com/qgis/QGIS/files/10367348/blending_examples_correct.zip)

### Steps to reproduce the issue

Notice in the screencast that the blend clipping modes are unavailable in the layer's properties, as if the checkbox was deselected even before i clicked that combobox.

[Kazam_screencast_00007.webm](https://user-images.githubusercontent.com/7983394/211172681-5c918db8-16e6-47d5-8b16-af9fd901c196.webm)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.29.0-Master | QGIS code revision | 7e2e6220e8
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
MemoryLayerSaver | 4.0.4
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nboisteault** [comment]
Hi,
Same bug here:

https://github.com/qgis/QGIS/assets/2145040/c059436b-e8ce-498f-b5ed-863db6707bac


<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


Version de QGIS | 3.28.6-Firenze | Révision du code | 868c9fa03b
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.10.6
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.6
Version de l'OS | Ubuntu 22.04.2 LTS
  |   |   |  
Extensions Python actives
AutomaticBackup-master | 1.0
latlontools | 3.6.6
LayerBoard | 1.0.1
lizmap | master
plugin_reloader | 0.9.3
quick_map_services | 0.19.33
QGIS3-getWKT | 1.4
trackable_project_files | v1.2.2
geometry_paster | 0.2
DataPlotly | 4.0.0
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

**Comment by nyalldawson** [comment]
Is this still reproducible? I can't replicate.

**Comment by nboisteault** [comment]
It works in QGIS 3.8.11 👍
