### ISSUE TITLE
3.28.2-Firenze: error at start

### ISSUE THREAD

**Issue by aborruso** [qgis/QGIS#51403]
### What is the bug or the crash?

Hi,
I have used the OSGeo4W Network Installer to install 3.28.2-Firenze, [64a1f375a12](https://github.com/qgis/QGIS/commit/64a1f375a12), using the default options. The OS is win11 22H2.

One of these options is this

![image](https://user-images.githubusercontent.com/30607/211291488-c3071c88-437b-411b-b5a3-93f39b3fa284.png)

Everytime I run QGIS I have this error 

```
Qt: QTemporaryDir: Unable to remove "C:\\Users\\aborr\\AppData\\Local\\Temp\\QGIS3-ojzqoF" most likely due to the presence of read-only files.
```

Is it normal that at the end of a standard installation I have this?

### Steps to reproduce the issue

- use osgeo installer
- install qgis-rel-dev
- run QGIS

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
64a1f375a12
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by pigreco** [comment]
Caro @aborruso 

I use the same installation method as you, but I chose to install qgis:QGIS Desktop and I don't get any error messages.

Most likely the error is related to the `dev` versions, in fact I read that you have installed `qgis-rel-dev`

I know, I'm not helping you much, but try to install the same version as me.

**Comment by aborruso** [comment]
> I know, I'm not helping you much, but try to install the same version as me.

Ok, maybe this issue is useful to solve a qgis-rel-dev problem

Thank you

**Comment by agiudiceandrea** [comment]
> Is it normal that at the end of a standard installation I have this?

Installing `qgis-rel-dev` is not a recommended installation. `qgis-rel-dev` is a nightly build which is a debug build (including debugging output) for testing purpose. Debugging output is not always useful for standard users and it does not always show actual bugs.

See also the QGIS testing warning at https://qgis.org/en/site/forusers/alldownloads.html#qgis-testing-warning.

Please refer to the QGIS Web site for [instruction](https://qgis.org/en/site/forusers/alldownloads.html#osgeo4w-installer) about standard recommended installation:

> Choose Express Install and select QGIS to install the latest release and/or QGIS LTR to install the long term release.

**Comment by aborruso** [comment]
Thank you

**Comment by mrtwister3142** [comment]
I am getting the `QTemporaryDir: Unable to remove "C:\\Users\\...\\AppData\\Local\\Temp\\python-qfvcqV" most likely due to the presence of read-only files.` error when running QGIS 3.30.0-4 through a standalone script (batch file/python script; see attachment) and using `qgs.exitQgis()` in the end. I have no dev packages installed.
[test.zip](https://github.com/qgis/QGIS/files/11097124/test.zip)
