### ISSUE TITLE
QGIS Digitization : group features as multipart

### ISSUE THREAD

**Issue by jp136769** [qgis/QGIS#51402]
### Feature description

Hi all,

Considering a layer accepting Multi* geometries (Multi polygon, multi linestring, etc...), would it be possible to have a digitizing tool that would permit the grouping of two features into a single multipart feature (without dissolving or touching the geometries).

I mean a tool similar to 
![image](https://user-images.githubusercontent.com/36761525/211290309-be277ecd-900e-4c1b-b3d2-9598d73a1102.png)
but that would perform on selected features and : 
- keep the selected features geometries
- ask for the attributes to keep (among selected geometries, as for the tool "Merge Attributes of Selected Features")

**Comment by uclaros** [comment]
This is what the _Merge selected features_ tool does now when the selected features do not intersect. If they _do_ intersect, the resulting multipart feature would be invalid as it would be self-intersecting, that's why it is dissolved and a singlepart feature is returned.
