### ISSUE TITLE
crash when importing svgis in python console

### ISSUE THREAD

**Issue by juliepierson** [qgis/QGIS#51410]
### What is the bug or the crash?

QGIS crashes when importing svgis module in the python console.

Here's what I get in console (launching QGIS from console) : 
`terminate called after throwing an instance of 'std::bad_alloc'`
`  what():  std::bad_alloc`
`Abandon (core dumped)`

svgis is imported without any problem from a python console. I use Ubuntu 20.04 and QGIS 3.22.14.

### Steps to reproduce the issue

1. Launch QGIS
2. Open Python console
3. Type `import svgis`

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.14-Białowieża | Révision du code | 4cde646cf9
-- | -- | -- | --
Version de Qt | 5.12.8
Version de Python | 3.8.10
Version de GDAL/OGR | 3.0.4
Version de Proj | 6.3.1
Version de la base de données du registre EPSG | v9.8.6 (2020-01-22)
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Version de SQLite | 3.31.1
Version de PDAL | 2.0.1
Version du client PostgreSQL | 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.2
Version de l'OS | Ubuntu 20.04.5 LTS
  |   |   |  
Extensions Python actives
processing_wbt | 1.3.5
qgis2web | 3.16.0
mapswipetool_plugin | 1.2
DataPlotly | 3.9.2
qconsolidate3 | 0.2.0
Generalizer3 | 1.0
geometric_attributes | 0.3
pluginbuilder3 | 3.2.1
line_similarity | 0.2
DissolveWithStats | 0.6
SLD4raster | 1.0
geobretagne | 2.1.1
Qgis2threejs | 2.7.1
flipbook | 0.1
FreehandRasterGeoreferencer | 0.8.3
mmqgis | 2021.9.10
river_tools_processing | 0.1
GeoCoding | 2.18
processing_r | 3.1.1
networks | 2.7.3
qgis_resource_sharing | 1.0.0
QuickOSM | 2.1.1
plugin_reloader | 0.9.2
OSMDownloader | 1.0.3
QNEAT3 | 1.0.4
redLayer | 2.2
ViewshedAnalysis | 1.8
cartolinegen | 3.2.2
quick_map_services | 0.19.32
LAStools | 1.4
nominatim_locator_filter | 0.2.4
GroupStats | 2.2.6
rename_bands | 0.1
french_locator_filter | 1.0.4
d3datavis | 3.0.3
ptm4Qgis | 0.1
qconsolidate | 1.1.0
plugin_templater_test | 0.1.0
coastline_change | 0.1
qgiscloud | 3.7.1
Unfolded | 1.0.2
gis_cloud_publisher | 1.0.9
mappia_publisher | 2.9.11
dist_cartogram | 0.4
simplesvg | 3.0.3
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.22.14-Białowieża
Révision du code
[4cde646cf9](https://github.com/qgis/QGIS/commit/4cde646cf9)
Version de Qt
5.12.8
Version de Python
3.8.10
Version de GDAL/OGR
3.0.4
Version de Proj
6.3.1
Version de la base de données du registre EPSG
v9.8.6 (2020-01-22)
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Version de SQLite
3.31.1
Version de PDAL
2.0.1
Version du client PostgreSQL
12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
Version de SpatiaLite
4.3.0a
Version de QWT
6.1.4
Version de QScintilla2
2.11.2
Version de l'OS
Ubuntu 20.04.5 LTS

Extensions Python actives
processing_wbt
1.3.5
qgis2web
3.16.0
mapswipetool_plugin
1.2
DataPlotly
3.9.2
qconsolidate3
0.2.0
Generalizer3
1.0
geometric_attributes
0.3
pluginbuilder3
3.2.1
line_similarity
0.2
DissolveWithStats
0.6
SLD4raster
1.0
geobretagne
2.1.1
Qgis2threejs
2.7.1
flipbook
0.1
FreehandRasterGeoreferencer
0.8.3
mmqgis
2021.9.10
river_tools_processing
0.1
GeoCoding
2.18
processing_r
3.1.1
networks
2.7.3
qgis_resource_sharing
1.0.0
QuickOSM
2.1.1
plugin_reloader
0.9.2
OSMDownloader
1.0.3
QNEAT3
1.0.4
redLayer
2.2
ViewshedAnalysis
1.8
cartolinegen
3.2.2
quick_map_services
0.19.32
LAStools
1.4
nominatim_locator_filter
0.2.4
GroupStats
2.2.6
rename_bands
0.1
french_locator_filter
1.0.4
d3datavis
3.0.3
ptm4Qgis
0.1
qconsolidate
1.1.0
plugin_templater_test
0.1.0
coastline_change
0.1
qgiscloud
3.7.1
Unfolded
1.0.2
gis_cloud_publisher
1.0.9
mappia_publisher
2.9.11
dist_cartogram
0.4
simplesvg
3.0.3
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This isn't a QGIS issue -- it will relate to how svgis was installed on your system which has caused multiple incompatible system libraries to be used. Did you install from pip or the ubuntu repos?

**Comment by juliepierson** [comment]
Ok, thanks Nyall, I'll look into this. I installed svgis from pip.
