### ISSUE TITLE
Private Layer visible in the print layout legend

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#51427]
### What is the bug or the crash?

Although a Private Layer has been defined in the project properties, it is always visible in the Print Layout legend.

![image](https://user-images.githubusercontent.com/7631137/211625497-0a3c00b8-a42e-4e7d-aad9-242bdfe72186.png)

1️⃣ Progject Properties;
2️⃣ Layer Panel;
3️⃣ Legend in Print Layout;
4️⃣ Object properties Legend

### Steps to reproduce the issue

1. load two vector layers;
2. From the Project properties, select the Data Sources tab
3. check private on one of the two layers
4. Create a print layout and add the legend

the Private layer is also visible in the legend

![image](https://user-images.githubusercontent.com/7631137/211626769-59d7bd75-abda-4950-8e16-1fd7ae8a8874.png)

## OSGeo4W Network Installer 

QGIS 3.28.2 Firenze
win 10 PRO

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I guess a skip would need to be added in the layer loop in QgsMapHitTest https://github.com/qgis/QGIS/blob/22c16f206778b80571479985e59f44c34b1ae0a7/src/core/qgsmaphittest.cpp#L61

**Comment by hblGP** [comment]
I've noticed the same error, I have a set of domain value tables I've set as private layers, and the users have no possible way of removing these from the legend. A quick workaround is to use the button "Only show items inside linked map". However this only works for me beacuse it's tables i'm hiding not anything with a geometry so it's a poor workaround.

![image](https://github.com/qgis/QGIS/assets/60741008/dfe8e42d-c7c9-4c57-b9ae-3ad7d9d827de)

I hope a solution to this can be found soon.

**Comment by MieWinstrup** [comment]
In the QGIS User Group Denmark we would like to fund this feature request - if within our financial possibilities. Therefore, we would like to hear if anyone would be interested in solving this feature request, what the price approximately would be, and if possible it could be done before the feature freeze for QGIS 3.40 (the 13th of September). The user group can be contacted at [info@qgis.dk](mailto:info@qgis.dk)

**Comment by agiudiceandrea** [comment]
@MieWinstrup, I suggest to write to the qgis-developer mailing list https://lists.osgeo.org/mailman/listinfo/qgis-developer

**Comment by agiudiceandrea** [comment]
@MieWinstrup, I suggest to contact the support contractors https://www.qgis.org/resources/support/commercial-support/.
