### ISSUE TITLE
Eratic zooming and location jumping whilst scrolling/moving with mouse

### ISSUE THREAD

**Issue by vicpaine** [qgis/QGIS#51421]
### What is the bug or the crash?

As stated in heading, impossible to control location or zoom with mouse making QGIS unusable.  3.22 on Win 11 is working well with no problems but I prefer the desktop Ubuntu with big screen to Win laptop. 

### Steps to reproduce the issue

Just need to load any project or start new and the problem starts.  There was an OS update this morning when i fired it up but problem still there.  All other programs are running correctly.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.3
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | 14.2 (Ubuntu 14.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.32
what3words | 4.2
aderyn | 1.0
QuickOSM | 2.1.1
GpxSegmentImporter | 2.5
OSMDownloader | 1.0.3
AreaAlongVector | 2.0
clipper | 1.2
MetaSearch | 0.3.5
processing | 2.12.99
grassprovider | 2.12.99
sagaprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.22.4-Białowieża
QGIS code branch
[Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)
Qt version
5.15.3
Python version
3.10.3
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
14.2 (Ubuntu 14.2-1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.1 LTS

Active Python plugins
quick_map_services
0.19.32
what3words
4.2
aderyn
1.0
QuickOSM
2.1.1
GpxSegmentImporter
2.5
OSMDownloader
1.0.3
AreaAlongVector
2.0
clipper
1.2
MetaSearch
0.3.5
processing
2.12.99
grassprovider
2.12.99
sagaprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@vicpaine could you please try using a new QGIS user profile and the latest available currently supported QGIS version on your system?

**Comment by davidafuller01** [comment]
There is a history of (potentially) similar reports:

- https://github.com/qgis/QGIS/issues/47212 ... I commented on this Issue on 2022-04-25
- https://github.com/qgis/QGIS/issues/47317
- https://github.com/qgis/QGIS/issues/47472
- https://github.com/qgis/QGIS/issues/49319

**Comment by vicpaine** [comment]
Not completely resolved, still erratic at times.  However away form offending desktop for 5 weeks so closing.
