### ISSUE TITLE
Exiting from editing mode on vector layer swipes any unsaved feature modificaton without any warning

### ISSUE THREAD

**Issue by rbonnefoi** [qgis/QGIS#51425]
### What is the bug or the crash?

Hi all,

I recently moved to 3.28.2 Qgis version (from 3.28.1) and I just realised that when editing a vector layer, if I unclick the pen button to exit the editing mode, it removes every modification which was not saved before thanks to the save button (the floppy disk button with a red pen).

Previously, on exit edit mode button click, a message box was displayed, asking whether the modifications had to be saved or not. Now it doesn't ask anything and decides not to save...

### Steps to reproduce the issue

1. Go to edit mode of any vector layer (yellow pen button)
2. Make some feature modifications (either editing existing ones or adding or removing)
3. Exit the edit mode
4. Check the loss of modifications.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.28.2-Firenze | Révision du code | b47e00ba601
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Compilé avec GDAL/OGR | 3.6.1 | Utilisé avec GDAL/OGR | 3.6.2
Version de Proj | 9.1.1
Version de la base de données du registre EPSG | v10.076 (2022-08-31)
Version de GEOS | 3.11.1-CAPI-1.17.1
Version de SQLite | 3.39.4
Version de PDAL | 2.4.3
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
BoundingBox | 2.1
EquirectangularViewer | 1.4
GeoCoding | 2.18
quick_map_services | 0.19.32
StreetView | 3.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>Version de QGIS
3.28.2-Firenze
Révision du code
[b47e00ba601](https://github.com/qgis/QGIS/commit/b47e00ba601)
Version de Qt
5.15.3
Version de Python
3.9.5
Compilé avec GDAL/OGR
3.6.1
Utilisé avec GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
BoundingBox
2.1
EquirectangularViewer
1.4
GeoCoding
2.18
quick_map_services
0.19.32
StreetView
3.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
I still get the prompt in master... Does this happen with any layer/layer type and with a new user profile?

**Comment by agiudiceandrea** [comment]
Not reproducible using QGIS 3.28.2 on Windows.

**Comment by rbonnefoi** [comment]
Hi Andra, Hi Alex,

Thanks for having spent time on my problem.

I think I had some messy things in my Qgis installation since I recently moved to a osgeo4w install management.

Did a clean fresh resinstallation, no more problem.

Sorry for the wrong bug signal, and many thanks for the job done on Qgis.

I close the thread.

Have a good day.

**Comment by roya0045** [comment]
@rbonnefoi All good, thanks for the followup!
