### ISSUE TITLE
bug creating vrt with raster in jp2

### ISSUE THREAD

**Issue by Geoscope19** [qgis/QGIS#51424]
### What is the bug or the crash?

Sorry, I use a translator (I am francophone)
qgis plant when creating vrt with orthophoto 2020 in jp2. See pj.

### Steps to reproduce the issue

When I create a vrt from raster in jp2, the operation indicates that the process is completed successfully, but everything freezes, I am forced to close qgis. The vrt is created, but does not open is qgis plant.
![vrt to jp2](https://user-images.githubusercontent.com/81222128/211593321-532d2203-d0f3-4785-8e4e-ddd2fb5a5283.png)

### Versions

Qgis 3.26
Windows 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Geoscope19, could you please tray using a new QGIS user profile and a currently supported QGIS version? Could you share the minimum set of layers and exact step and parameters in order to reproduce the issue?

**Comment by nicogodet** [comment]
Update your QGIS to latest available versions : 3.22.14 or 3.28.2.

Could be linked to https://github.com/qgis/QGIS/issues/49285

**Comment by Geoscope19** [comment]
Yes, is good with version 3.28 ! thank you :-)
