### ISSUE TITLE
Vertex Editor table shows incorrect columns in QGIS 3.28

### ISSUE THREAD

**Issue by RBA-deepbv** [qgis/QGIS#51433]
### What is the bug or the crash?

I have 3 line layers: LineStringZ, LineStringM and LineStringZM. The difference between them are only in Z/M components. 

I use the Vertex Editor to see the node data. If I select the LineStringM layer as first, the table in Vertex Editor shows correctly x, y, m ,r columns
![image](https://user-images.githubusercontent.com/65605420/211813370-d00ddf30-b4de-419b-af94-e4566768df9e.png)

However if I check any other layer in Vertex Editor and then come back to LineStringM, the columns shown are x,y,z,r and z column is filled with nan values. m, which is filled with valid values remains hidden. 
![image](https://user-images.githubusercontent.com/65605420/211813934-409a1c48-b3b7-470f-b9e6-5c571ebc34a2.png)

Layers with geometry with components Z or ZM seem to be shown correctly.

The only way I could fix it was to restart QGIS. But that just restarts the cycle.

### Steps to reproduce the issue

1. Open a new instance of QGIS
2. Load a project with at least 2 line layers with following geometry types: 

- LineStringM (make sure M are valid values)
- LineStringZ and/or LineStringZM (make sure Z and M are valid values)

3. Enter editing mode on LineStringM
4. Use Vertex Editor to see the nodes list in a table.
5. Exit editing mode on LineStringM (it will close Vertex Editor)
6. Select the other layer in the project and enter editing mode on that one.
7. Use Vertex Editor to see the nodes list.
8. Exit editing mode on current layer
9. Come back to LineStringM layer
10. Enter editing mode and open again Vertex Editor. 
11. See the displayed columns (for me at this point they are still x,y,z,r)

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.6.0
Running against GDAL/OGR
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

It seems that the issue started in QGIS 3.28 and does not affect QGIS 3.22.

**Comment by nicogodet** [comment]
Could you make a tarball of your 3 layers ? (devs are busy and it's always nicer to have a ready to go project/data to test something)

**Comment by RBA-deepbv** [comment]
Sure thing! Anything I can do to make it easier to solve. I prepared a geopackage with test data, as I can't share the original. It is enough for testing. A .tar.gz archive is attached to this message. 
Let me know if I can do anything else.
[demo_linedata.tar.gz](https://github.com/qgis/QGIS/files/10393553/demo_linedata.tar.gz)

**Comment by agiudiceandrea** [comment]
I can confirm the issue using QGIS 3.28 while it seems to me it doesn't occur using QGIS 3.22.
