### ISSUE TITLE
SQL Server link issues Crash ID: 1424dce50679f1b1abb8e058f892cb75d9ca6f87

### ISSUE THREAD

**Issue by panda1967** [qgis/QGIS#51447]
### What is the bug or the crash?

SQL server link issues. Each time that I try to interrogate the layer, QGIS crashes. I've checked the server end but cannot see any difference in the setup.

### Steps to reproduce the issue

This is the crash report:
Stack Trace

QMutex::lock :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayerFeatureIterator::close :
QgsVectorLayerFeatureIterator::~QgsVectorLayerFeatureIterator :
QgsVectorLayerFeatureSource::~QgsVectorLayerFeatureSource :
QgsVectorLayerJoinInfo::setEditable :
QgsVectorLayerJoinInfo::setEditable :
QgsMapRendererParallelJob::renderLayerStatic :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.4-Bia?owie?a
QGIS code revision: ce8e65e9
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Versions

QGIS 3.22.4

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
@panda1967 3.22 is EOL, may I ask you to test with the latest versions?
