### ISSUE TITLE
make visible null value for boolean field

### ISSUE THREAD

**Issue by npltr62** [qgis/QGIS#51454]
### Feature description

In Attribute table a "null" value is rendered  with false value in boolean field, also in identify results panel is there a way to set tristate to checkbox object?

### Additional context

In pgadmin the third choice look like : ![question_mark](https://user-images.githubusercontent.com/40625762/212124531-61461681-d08c-4728-b715-dcba53332892.png)

**Comment by quassy** [comment]
I would classify this as a Bug not a Feature Request. Displaying `False` when the actual value is `Null` (and other field types like string support `Null`) made me think we had lots of data errors.

**Comment by alexbruy** [comment]
Duplicates #44556.
