### ISSUE TITLE
Qgis crashes on startup on a fresh install

### ISSUE THREAD

**Issue by tuxrinku** [qgis/QGIS#51457]
### What is the bug or the crash?

As soon as I start qgis, I see the logo of the 3.22 version and it crashes. Log joined.
[qgis_crash.log](https://github.com/qgis/QGIS/files/10405701/qgis_crash.log)

### Steps to reproduce the issue

Launch qgis from terminal or gui

### Versions

3.22

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

### Additional context

My system is ubuntu 22.04

**Comment by agiudiceandrea** [comment]
@tuxrinku does the issue occurs every time you try to start QGIS? How have you installed QGIS? Have you tried to start QGIS using a new QGIS user profile?

**Comment by tuxrinku** [comment]
Yes it occurs everytime, QGIS is installed with apt using ubuntu repository. I tried purging it, removing folder in .config/QGIS and any other remaining qgis folder.

**Comment by agiudiceandrea** [comment]
The profile folder on a Linux system is usually at `.local/share/QGIS/QGIS3/profiles/` in your `HOME` user folder (see https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). You can also start QGIS with a new user profile from the CLI using `qgis --profile name_of_new_profile`. What is the exact version of QGIS installed?

**Comment by tuxrinku** [comment]
I tried with a new profile, and even after completely removing the .local/share/QGIS directory, still the same error. The exact version is 3.22.10. But I also tried adding the qgis repo to get the last version but it still happens.

**Comment by tuxrinku** [comment]
An upgrade to Ubuntu 23.04 seems to have fixed it. Qgis version is 3.22.16
