### ISSUE TITLE
The layout view is very slow when using a filtered legend (QGIS 3.28.2)

### ISSUE THREAD

**Issue by fischerteamplan** [qgis/QGIS#51455]
### What is the bug or the crash?

The layout view is very slow when using a filtered legend (QGIS 3.28.2). 

### Steps to reproduce the issue

This has been mentioned in some older issues of QGIS 3.22 (https://github.com/qgis/QGIS/issues/47033) without presenting a solution for normal QGIS-users. 

### Versions

QGIS-Version
3.28.2-Firenze
QGIS-Codeversion
b47e00ba601
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.1
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
changeDataSource
3.1
DigitizingTools
1.5.1
flae2halt
0.1
go2nextfeature-qgis3_version
2.00
halt2str
0.1
ImportPhotos
3.0.3
import_ascii
0.1
nominatim
1.4.2
pluginbuilder3
3.2.1
profiletool
4.2.2
qdraw
3.0.2
qfieldsync
v4.1.1
qgis-fischerteamplan
version 1.2
Qgis2threejs
2.7.1
QPackage
1.5
quick_map_services
0.19.29
stempel_ausfuellen
0.1
valuetool
3.0.15
wfsclient
0.9.11
xyz2tif
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
CustomToolBar
1.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I need a sample project to investigate this further.
