### ISSUE TITLE
Make it possible to print the hidden items of a layout (as a workaround for dealing with the known Bug: filtered legend slows down the layout view)

### ISSUE THREAD

**Issue by fischerteamplan** [qgis/QGIS#51452]
The layout view is very slow when using a filtered legend (QGIS 3.22.14 and also QGIS 3.28.2). This has been mentioned in some older issues (https://github.com/qgis/QGIS/issues/47033) without presenting a solution for normal QGIS-users.

A Workaround could be:
to hide the legend in the layout (which accelarates the layout view) and then set QGIS to also print the hidden legend.

Currently ist not possible to print the hidden items (they don't show on the pdf). Would be nice if the developer make this possible.

### Versions

QGIS 3.22.14 and also QGIS 3.28.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@fischerteamplan:
`Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.`

**Comment by fischerteamplan** [comment]
> @fischerteamplan: `Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.`

I am suggesting a new Feature. Imagine the developer make it possible to print out the hidden items, then we have a work around for the already known BUG (slow View in Layout)

**Comment by agiudiceandrea** [comment]
@fischerteamplan then please modify this bug request as a request of a new feature with a correct title and a "clear and concise description of what you want to happen" or open a new feature request.

**Comment by fischerteamplan** [comment]
> 

my new issue got automatically a Bug-Label. didn't figure out how to change the label

**Comment by fischerteamplan** [comment]
> @fischerteamplan then please modify this bug request as a request of a new feature with a correct title and a "clear and concise description of what you want to happen" or open a new feature request.

my new issue got automatically a Bug-Label. didn't figure out how to change the label

**Comment by agiudiceandrea** [comment]
Please change the title and the description.
