### ISSUE TITLE
Crash when trying to add a child point feature

### ISSUE THREAD

**Issue by valttlapp** [qgis/QGIS#51464]
### What is the bug or the crash?

I'm running a QGIS project from PostgreSQL and using PostgreSQL layers. The project is used in spatial planning in Finland. The project has a geometry feature called zoning_element. Zoning_element has regulations and regulations with different values that are their own tables. One type of value is point geometry.

When creating a zoning_element and adding a regulation to it and then adding a geometry value to it qgis crashes.

### Steps to reproduce the issue

1. Create a geometry feature and add a data child to it
 ![image](https://user-images.githubusercontent.com/106655208/212261869-a17d3de1-1656-4c0f-b95e-c74e6314e596.png)
2. For the data child add a geometry feature child by pressing "Add Point Child Feature"
![image](https://user-images.githubusercontent.com/106655208/212262197-ef05ebef-0c10-4de2-8fba-b1575536b370.png)
3. QGIS crashes

### Stack Trace
QObject::isWidgetType :
QWidget::ensurePolished :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QgsRelationEditorWidget::mapToolDeactivated qgsrelationeditorwidget.cpp:483
QObject::qt_static_metacall :
QgsMapCanvas::unsetMapTool qgsmapcanvas.cpp:2412
QgsMapTool::~QgsMapTool qgsmaptool.cpp:39
QgsMapToolDigitizeFeature::`vector deleting destructor' :
QgsRelationEditorWidget::~QgsRelationEditorWidget :
QgsRelationEditorWidget::`vector deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QStackedWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAttributeFormRelationEditorWidget::`vector deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QSizePolicy::operator== :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsScrollArea::`vector deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QStackedWidget::~QStackedWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsTabWidget::`vector deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QWidget::`scalar deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAttributeForm::`vector deleting destructor' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAttributeDialog::`scalar deleting destructor' :
QDialog::exec :
QgsFeatureAction::addFeature qgsfeatureaction.cpp:277
QgsGuiVectorLayerTools::addFeature qgsguivectorlayertools.cpp:41
QgsTrackedVectorLayerTools::addFeature qgstrackedvectorlayertools.cpp:28
QgsAbstractRelationEditorWidget::addFeature qgsabstractrelationeditorwidget.cpp:214
QtPrivate::QFunctorSlotObject,0,QtPrivate::List,void>::impl qobjectdefs_impl.h:443
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:514
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:514
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1667
BaseThreadInitThunk :
RtlUserThreadStart :

### Versions

QGISin versio
3.22.12-Białowieża
QGIS-koodin versio
b8534cb1
Qt:n versio
5.15.3
Python-versio
3.9.5
Käännetty käyttäen GDAL/OGR:ia
3.5.2
Suoritetaan käyttäen GDAL/OGR:ia
3.5.3
PROJ-versio
9.1.0
EPSG-rekisteritietokannan versio
v10.074 (2022-08-01)
GEOS-versio
3.10.3-CAPI-1.16.1
SQLite-versio
3.39.4
PDAL-versio
2.4.3
PostgreSQL:n asiakkaan versio
14.3
SpatiaLite-versio
5.0.1
QWT-versio
6.1.6
QScintilla2-versio
2.13.1
Käyttöjärjestelmän versio
Windows 10 Version 2009

Aktiiviset python-lisäosat
debug_vs
0.7
Kauko
0.1.1
pluginbuilder3
3.2.1
plugin_reloader
0.9.2
Tieosoitetyokalu
1.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Everything works when adding the geometry child direct from the regulations form, but when the regulation is created as a child from another form the crash happens.

**Comment by agiudiceandrea** [comment]
@valttlapp doese the issue also occur using non PostgreSQL layers? If yes, could you please provide a sample project and layers? Have you tried if the issue does occur also using a new QGIS user profile?

**Comment by valttlapp** [comment]
@agiudiceandrea  Yes this also happens in non PostgreSQL layers. I have tried this with new profiles and also all of our users have experienced same crash. I attached example project and a gif of the crash.
![Recording 2023-01-17 at 12 39 35](https://user-images.githubusercontent.com/106655208/212878224-0c0c9ed3-7748-4258-b408-fe7b3ad13375.gif)
[qgis_crash.zip](https://github.com/qgis/QGIS/files/10434090/qgis_crash.zip)

**Comment by agiudiceandrea** [comment]
The crash doesn't occur on my Windows system using QGIS 3.28:

https://user-images.githubusercontent.com/16253859/212882649-840785db-f71b-4a30-9b99-6e90e96f7306.mp4

**Comment by valttlapp** [comment]
Seems to be fixed in 3.28. We have been using LTR 3.22.14 where the crash occurs.

**Comment by troopa81** [comment]
@valttlapp You can try with last LTR 3.22.16 see if it fixes it. 

I close it because 3.28 will become new LTR the 3rd of march and no other 3.22 will be released

**Comment by Rikuoja** [comment]
Interestingly, this still occurs on my Mac OS with QGIS 3.28.3. Apparently on Windows this is fixed?

Anyone with a Mac OS that can verify my report on 3.28 using valttlapps example?

QGISin versio | 3.28.3-Firenze | QGIS-koodin versio | 9ae208a46d
-- | -- | -- | --
Qt:n versio | 5.15.2
Python-versio | 3.9.5
GDAL/OGR:n versio | 3.3.2
PROJ-versio | 8.1.1
EPSG-rekisteritietokannan versio | v10.028 (2021-07-07)
GEOS-versio | 3.9.1-CAPI-1.14.2
SQLite-versio | 3.35.2
PDAL-versio | 2.3.0
PostgreSQL:n asiakkaan versio | unknown
SpatiaLite-versio | 5.0.1
QWT-versio | 6.1.6
QScintilla2-versio | 2.11.5
Käyttöjärjestelmän versio | macOS 13.2
  |   |   |  
Aktiiviset python-lisäosat
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGISin versio
3.28.3-Firenze
QGIS-koodin versio
[9ae208a46d](https://github.com/qgis/QGIS/commit/9ae208a46d)
Qt:n versio
5.15.2
Python-versio
3.9.5
GDAL/OGR:n versio
3.3.2
PROJ-versio
8.1.1
EPSG-rekisteritietokannan versio
v10.028 (2021-07-07)
GEOS-versio
3.9.1-CAPI-1.14.2
SQLite-versio
3.35.2
PDAL-versio
2.3.0
PostgreSQL:n asiakkaan versio
unknown
SpatiaLite-versio
5.0.1
QWT-versio
6.1.6
QScintilla2-versio
2.11.5
Käyttöjärjestelmän versio
macOS 13.2




Aktiiviset python-lisäosat
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6
