### ISSUE TITLE
MingW64 Windows 64bit Build fails randomly at 78%

### ISSUE THREAD

**Issue by YoannQDQ** [qgis/QGIS#51468]
### What is the bug or the crash?

When all checks (Github Actions) are run, when opening/updating a PR for instance), _MingW64 Windows 64bit Build_ randomly fails at around **78%** (it happened at least thrice with thi exact progress number). 

I tried to find out why in the log (see attached file) but had no luck.
When I close / reopen the PR, it completes without error.

It's kind of a meta issue, so I'm not sure this is the right canal to report it.

[log_fail.txt](https://github.com/qgis/QGIS/files/10411738/log_fail.txt)

### Steps to reproduce the issue

Trigger a pipeline run (commit to any branch, open a PR...)

### Versions

Latest version of QGIS/actions

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Seems situation improved recently. Can we close this?

**Comment by YoannQDQ** [comment]
Closing. What fixed this though?
