### ISSUE TITLE
Some "Deprecated" warning in PyQGIS docs are incorrectly displayed

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#51478]
### What is the issue about the documentation?

Some examples:

in https://qgis.org/pyqgis/3.28/gui/QgisInterface.html

`Deprecated since version Use: [actionZoomToLayers()](https://qgis.org/pyqgis/3.28/gui/QgisInterface.html#qgis.gui.QgisInterface.actionZoomToLayers) instead.`

`Deprecated since version QGIS: 3.26 shape digitizing is now part of the add feature tool. `

in https://qgis.org/pyqgis/3.28/core/QgsLayoutItemLabel.html

`Deprecated since version use: [textFormat()](https://qgis.org/pyqgis/3.28/core/QgsLayoutItemLabel.html#qgis.core.QgsLayoutItemLabel.textFormat) instead (since QGIS 3.24)`

**Comment by nyalldawson** [comment]
Fixed in master
