### ISSUE TITLE
processing.createAlgorithmDialog not filling default enum parameter

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#51489]
### What is the bug or the crash?

When creating an algorithm with a `QgsProcessingParameterEnum` parameter, if the algorithm dialog is created with the `createAlgorithmDialog` method, default values to fill the enum are not taken into account.

### Steps to reproduce the issue

Here is the gist with the whole algorithm (it is not doing anything, I'm just focused on the `initAlgorithm` method): https://gist.github.com/ghtmtt/b1be418c9630e36b8af04011b82a642e

Just save the Processing script so it is added in the Script Provider and then try to create the instance with:

```
dialog = processing.createAlgorithmDialog(
    'script:myscript2',
    {
       'INPUT': ['a', 'b', 'c']
    }
)
dialog.exec_()
```

the enum list will be empty.

### Versions

We are working on 3.29-Master. It will go into feature freeze on 2023-01-27 12:00:00 UTC and be released as 3.30 on 2023-03-03 12:00:00 UTC. 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ghtmtt** [comment]
thanks for the reply. So it is not possible to pass directly a list of options from the `createAlgorithmDialog` method if the options have not been created in the main algorithm, so basically without knowing them (the options) before

**Comment by ghtmtt** [comment]
So for instance, if I don't know the options of the enum parameter, is there any chance to have the list filled from the `createAlgorithmDialog` method?

```python
    def initAlgorithm(self, config=None):

        self.addParameter(
            QgsProcessingParameterEnum(
                self.INPUT,
                self.tr('Enum'),
                options=[],
                allowMultiple=True
            )
        )

dialog = processing.createAlgorithmDialog(
    'script:myscript2',
    {
       'INPUT': ['a', 'b', 'c']
    }
)
dialog.exec_()
```

**Comment by agiudiceandrea** [comment]
Maybe it would be more useful for you to ask the question to the qgis-user / qgis-develper ml or on [stackexchange](https://gis.stackexchange.com/).

**Comment by agiudiceandrea** [comment]
@ghtmtt maybe it would be more useful for you to ask the question to the qgis-user / qgis-develper ml or on [stackexchange](https://gis.stackexchange.com/) and close this bug report or modify it as a feature request (if necessary).

> Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.

**Comment by ghtmtt** [comment]
done, thanks: https://gis.stackexchange.com/questions/449775/processing-createalgorithmdialog-not-filling-default-enum-parameter
