### ISSUE TITLE
QGIS Crashes after I hit exit button

### ISSUE THREAD

**Issue by rodreras** [qgis/QGIS#51488]
### What is the bug or the crash?

Since I upgraded to QGIS 3.22.11 a couple of days ago, I got this error whenever I shut QGIS down. It does not compromise my work, but for sure there is something wrong. 

Interestingly, this crash does not happen with another profile. Maybe some plugin?

Here is the code from the crash window: 

``` 
Crash ID: [f7fa77a8ccd087d4de5cfbf53f2030b52933045f](https://github.com/qgis/QGIS/search?q=f7fa77a8ccd087d4de5cfbf53f2030b52933045f&type=Issues)


Stack Trace


CPLODBCDriverInstaller::RemoveDriver :
dal::GDALRasterDriver::deregisterGDALDrivers :
dal::Client::~Client :
calc::DataStorageId::setId :
::operator() :
__crt_seh_guarded_call::operator(), &, > :
execute_onexit_table :
calc::vs2CsfVs :
calc::vs2CsfVs :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.22.14-Bia?owie?a
QGIS code revision: 4cde646c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.1
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
``` 

### Steps to reproduce the issue

1. Click to exit the program;
2. Wait for it to load the crash window;

### Versions

Versão do QGIS
3.22.14-Białowieża
Código da versão do QGIS
4cde646c
Versão Qt
5.15.3
Versão do Python
3.9.5
Compilado sobre GDAL/OGR
3.6.1
Rodando sobre GDAL/OGR
3.6.2
Versão PROJ
9.1.1
Versão da base de dados do registro EPSG
v10.076 (2022-08-31)
Versão GEOS
3.11.1-CAPI-1.17.1
Versão SQLite
3.39.4
Versão PDAL
2.4.3
Versão cliente PostgreSQL
14.3
Versão SpatiaLite
5.0.1
Versão QWT
6.1.6
Versão QScintilla2
2.13.1
Versão OS
Windows 10 Version 2009

Plugins Python ativos
cbers4a
0.3.2
dados_censo
0.40
ee_plugin
0.0.6
enmapboxplugin
3.9.20211123T125541.master
LAStools
1.4
lnns
1.0.7
mapswipetool_plugin
1.2
Qgis2threejs
2.7.1
qgis_resource_sharing
1.0.0
QuickOSM
2.1.1
quick_map_services
0.19.29
rvt-qgis
0.9.4.1
SemiAutomaticClassificationPlugin
7.10.10
sentinel2_download
3.5.7
SRTM-Downloader
3.1.17
wbt_for_qgis
1.0.5
open_lidar_tools
2.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I uploaded QGIS to 3.22.11 and via OSGeo4W Shell, and also installed PCRaster extension.

**Comment by nicogodet** [comment]
PCRaster is the root cause. It's not linked to QGIS it self.

See https://github.com/pcraster/pcraster/issues/361
