### ISSUE TITLE
Hovering field type in "Refactor Fields" tool select entire row - only in Night Mapping theme

### ISSUE THREAD

**Issue by jgruszka93** [qgis/QGIS#51507]
### What is the bug or the crash?

I've got a vector layer that has multiple fields. When I open "Refactor fields" tool from Processing Toolbox and I click on for example fourth field name (to select it) when i move my mouse to "Delete selected field" icon on the right side, and my cursor at any time will be over "Field Type" of another field (for exemple third one), when I press "Delete selected field" icon, the third field will be deleted, not the previously selected fourth one. 
![Qgis_refactor_bug](https://user-images.githubusercontent.com/37851321/213131695-17483c71-96b4-4778-965c-c99449ccd0d7.gif)

This bug only occurs with the "Night Mapping" theme. In the default theme everything is fine.
![Qgis_refactor_bug2](https://user-images.githubusercontent.com/37851321/213132366-ee114bfb-e541-4104-baeb-0b5dbe00a7a8.gif)

This is very annoying because I have to carefully move my cursor up the "Name" column to the header and be careful not to accidentally hover over the "Type" column, and only then move my cursor to the "Delete selected field" icon. otherwise a different field than I wanted is removed.

### Steps to reproduce the issue

1. Open qgis
2. Go to Settings -> Options
3. Change UI theme to "Night Mapping", then click OK
4. restart qgis
5. Import (or create) vector layer with at least two fields
6. From processing toolbox choose "Refactor fields"
7. Select second field by clicking on its name
8. Hover (but dont click) your cursor over first field "Type" 
9. Press "Delete selected field" icon on right side
10. First field was deleted, not the second one you choosed.

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nirvn** [comment]
Fixed in #53864
