### ISSUE TITLE
A macOS app icon that meets Apple's standards

### ISSUE THREAD

**Issue by Jerry23011** [qgis/QGIS#51516]
### Feature description

Hi, I noticed that the QGIS app icon doesn't yet meet [Apple's human interface standards](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons/) for app icons, so QGIS looks a little abrupt on macOS. I think a modified version would look nicer.
Thanks for the great platform :)

### Additional context

This is how QGIS looks compared to other macOS apps.
<img width="519" alt="截屏2023-01-19 20 42 40" src="https://user-images.githubusercontent.com/89069957/213446752-94aa008f-0d17-4187-b629-05dfcb229314.png">

**Comment by agiudiceandrea** [comment]
@Jerry23011 could you please file this request to the https://github.com/qgis/QGIS-Mac-Packager?

**Comment by Jerry23011** [comment]
> @Jerry23011 could you please file this request to the https://github.com/qgis/QGIS-Mac-Packager?

Yes, thank you :)
