### ISSUE TITLE
Bloqueo al cargar elementos de leyenda

### ISSUE THREAD

**Issue by SigTerra** [qgis/QGIS#51512]
### What is the bug or the crash?

Estoy trabajando con el atlas y al momento de agregar un elemento de leyenda, se bloquea el Qgis, estoy trajando con la versión 3.22.8, tambien se bloquea, y no me ha permitido trabajar de esa manera, cuando agrego otra pagina e intento copiar los cuadros que ya tengo elaborados del atlas. 

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/117939209/213287086-679c9d58-2d73-4ff3-b307-480703c11fb1.png)

![image](https://user-images.githubusercontent.com/117939209/213287189-acc6bd8a-4ce5-410b-8887-01090b501c4f.png)

![image](https://user-images.githubusercontent.com/117939209/213287272-c3904493-a580-4fa5-8fe5-a5314d10c54f.png)

![image](https://user-images.githubusercontent.com/117939209/213287338-39a8a93f-fe4d-4f12-a082-9d0e005be22c.png)

![image](https://user-images.githubusercontent.com/117939209/213287418-1016ffb0-4177-4417-ab5a-39afe9f48242.png)

Despues de dar aceptar, se bloquea

### Versions

Versión de QGIS
3.22.11-Białowieża
Revisión del código de QGIS
106d33d7
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.5.1
Versión de PROJ
9.1.0
Versión del registro de base de datos EPSG
v10.074 (2022-08-01)
Versión GEOS
3.10.3-CAPI-1.16.1
Versión de SQLite
3.38.1
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
14.3
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
mapswipetool_plugin
1.2
nominatim
1.4.2
OSMDownloader
1.0.3
QgisModelBaker
v6.1.1.5
quick_map_services
0.19.29
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue? Please test using latest versions.
