### ISSUE TITLE
0,0 coordinate marker on point symbol selector

### ISSUE THREAD

**Issue by Skipper-is** [qgis/QGIS#51519]
### Feature description

The addition of a cross hair, or origin indicator on the point symbol selector, at 0,0.

### Additional context

The addition of a crosshair at 0,0 would help to create point symbology that is accurate to it's origin. For example, if using a triangle, which bit of the triangle is on the actual point? Is it the middle of the triangle? One of the tips? Who knows. An origin marker on the symbol preview would help to position symbology accurately.
![image](https://user-images.githubusercontent.com/28678069/213458108-676e1a4c-b838-4bf2-991e-a11123ee831a.png)

It could add some confusion as to whether that crosshair will appear on the actual map - is the only issue I can forsee.

**Comment by BlazkovaKatka** [comment]
Crosshair lines were in previous version of QGIS, but after updating to 3.28.1 they´re missing. They were really helpfull, especialy when working with offset. I´m attaching pictures from oldest version (with lines) and from 3.28.1 (without lines).

![oldest](https://user-images.githubusercontent.com/47855304/213984733-7407efeb-ada3-4e06-a9cf-a242e002f0fc.png)


![new](https://user-images.githubusercontent.com/47855304/213984760-30f779ed-5bb3-4e32-98c9-ed7c5b15381c.png)
