### ISSUE TITLE
Remaining geometry-issues in dataset after applying "fix geometries"-processing tool  

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#51514]
### What is the bug or the crash?

The "fix-geometries"-processing-tool is expected to remove and repair all geometry-issues from a dataset 

After applying the tool to the (sample-dataset "ewf5.shp") QGIS shows, that all geometries are valid.

![grafik](https://user-images.githubusercontent.com/28433436/213403752-fa207321-a840-40ce-b93e-46ac56441822.png)

But in a 3rd-party-software which uses gis-data we could not import the dataset.

To narrow down the issue, we checked the dataset with ArcMap (CheckGeometry-Tool)

It showed still "intersection with itself"-issues (and a spatial index issue)
![grafik](https://user-images.githubusercontent.com/28433436/213402290-c3b8cdeb-d5b1-4e0d-ba09-a7cb51b66eb3.png)

The fix-geometies-tool in ArcMap had to be run twice to fix the issues of the sample dataset. But in the end the new, valid dataset (export_output_3.shp) coud be used in 3rd-party-software.

Sample-data (shp-file with 2 invalid polygons) can be downloaded from [https://databox0230.krz.de/public/download-shares/fm9EPlb5JdrEEjWBLbgduiTOTa6T3QX7](url)

### Steps to reproduce the issue

1) Take dataset "ewf5.shp" (from (https://databox0230.krz.de/public/download-shares/fm9EPlb5JdrEEjWBLbgduiTOTa6T3QX7) and apply "processing-fix-geometries" tool
1.1) Settings: Edit in place
1.2) Apply with repair-method "structure"
2) Take fixed dataset and apply "processing-fix-geometries" tool
2.1) Settings: Edit in place
2.2) Apply with repair-method "linework"
3) Check validity of dataset in QGIS ("Check validity-processing-tool")
4) Check validity of dataset / repair dataset in ArcMap ("GeometryChecker")

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.0-Firenze | QGIS code revision | ed3ad0430f3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99
qfieldsync | v4.2.0

</body></html>QGIS version
3.28.0-Firenze
QGIS code revision
[ed3ad0430f3](https://github.com/qgis/QGIS/commit/ed3ad0430f3)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
qfieldsync
v4.2.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
This is not a bug, your geometries are indeed valid.
ArcMap fails to load them because it silently tries to _snap to a grid_ based on the cluster tolerance of the geodatabase. Your geometries have vertices that are 0.00189 apart which are messed after this snapping.
