### ISSUE TITLE
Problem with SAGA's "Raster Filter" tools

### ISSUE THREAD

**Issue by palsome** [qgis/QGIS#51526]
### What is the bug or the crash?

I am unable to get output while running raster filter tools in QGIS.
I recieve the following message in the Log "
"The following layers were not correctly generated."

The log file is attached

Is it a bug or something wrong from my end?
[Log.txt](https://github.com/qgis/QGIS/files/10467456/Log.txt)

Thank you 

### Steps to reproduce the issue

1. Import any Raster in QGIS
2. In processing toolbox type "dtm filter (slope based)" and run the tool
3. Keeping the default settings, click "Ok"

### Versions

QGIS version
3.28.1-Firenze
QGIS code revision
fde3b8fbb8c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
profiletool
4.2.2
qfieldsync
v4.2.0
QuickOSM
2.1.1
quick_map_services
0.19.32
Smart_Map
1.2
SRTM-Downloader
3.1.17
Submission
0.7
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
processing_saga_nextgen
0.0.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I have tried the same with other raster filter tools such as Gaussian filter and Laplacian filter, and facing the same error

**Comment by agiudiceandrea** [comment]
@palsome, please check if the issue occurs using the latest supported QGIS version available (3.28.2 / 3.22.14) and using a new QGIS user profile. Please provide a sample raster layer with which the issue does occur.
The issue does not occur on my Windows system with QGIS 3.28.2.

**Comment by palsome** [comment]
@agiudiceandrea Thank you for the reply
After installing QGIS 3.28.2, I'm not facing the issue anymore

Thank you for your assistance
