### ISSUE TITLE
Pestana Vectorial

### ISSUE THREAD

**Issue by 23Pato** [qgis/QGIS#51536]
### What is the bug or the crash?

Me dejó de funcionar la pestaña Vectorial desde la versión 3.24-3.26, ahora ni con la 3.28. Lo he intentado hasta con la 3.10 y nada, no creo que mi computadora sea el problema, ya que en esta misma he usado los Buffer en la 3.24.

### Steps to reproduce the issue

See error

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please report in English.
Try with a new user profile.
Provide sample data and add detailed steps to reproduce.

**Comment by jir59** [comment]
I had the same problem, the Vectorial menu and bar didn´t work. I was using the default profile. 
I created a new one and the issue was resolved

Thank you!!!
