### ISSUE TITLE
distutils is deprecated but still used

### ISSUE THREAD

**Issue by sebastic** [qgis/QGIS#51532]
### What is the bug or the crash?

From [What’s New In Python 3.10](https://docs.python.org/3/whatsnew/3.10.html#distutils-deprecated):
> The entire `distutils` package is deprecated, to be removed in Python 3.12. Its functionality for specifying package builds has already been completely replaced by third-party packages `setuptools` and `packaging`, and most other commonly used APIs are available elsewhere in the standard library (such as [platform](https://docs.python.org/3/library/platform.html#module-platform), [shutil](https://docs.python.org/3/library/shutil.html#module-shutil), [subprocess](https://docs.python.org/3/library/subprocess.html#module-subprocess) or [sysconfig](https://docs.python.org/3/library/sysconfig.html#module-sysconfig)). There are no plans to migrate any other functionality from distutils, and applications that are using other functions should plan to make private copies of the code. Refer to [PEP 632](https://peps.python.org/pep-0632/) for discussion.

`distutils` is still used in:

 * [`cmake/FindSIP.py:40`](https://github.com/qgis/QGIS/blob/final-3_22_14/cmake/FindSIP.py#L40)
 * [`tests/src/python/test_qgslayertreeview.py:17`](https://github.com/qgis/QGIS/blob/final-3_22_14/tests/src/python/test_qgslayertreeview.py#L17)
 * [`tests/src/python/test_qgssymbollayer.py:32`](https://github.com/qgis/QGIS/blob/final-3_22_14/tests/src/python/test_qgssymbollayer.py#L32)

[`packaging.version`](https://packaging.pypa.io/en/stable/version.html) seems like a good alternative for `StrictVersion`.

[Python Issue 41282](https://bugs.python.org/issue41282) suggests using [`sysconfig.get_path()`](https://docs.python.org/3/library/sysconfig.html#sysconfig.get_path) instead of `get_python_lib()`.
To get the same value on Debian the `deb_system` scheme needs to be used:
```python
>>> import distutils
>>> import sysconfig
>>> distutils.sysconfig.get_python_lib()
'/usr/lib/python3/dist-packages'
>>> sysconfig.get_path('purelib', 'deb_system')
'/usr/lib/python3/dist-packages'
>>> sysconfig.get_path('platlib', 'deb_system')
'/usr/lib/python3/dist-packages'
```

### Steps to reproduce the issue

Run lintian from Debian unstable after the Debian package build.

Alternatively:
```bash
grep distutils . -r 2> /dev/null | grep import
```

### Versions

QGIS version | 3.22.14-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.1 (Debian 15.1-1+b1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  
Active Python plugins
quick_map_services | 0.19.29
sagaprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

**Comment by roya0045** [comment]
Don't forget that [cmake/FindSIP.py](https://github.com/qgis/QGIS/blob/6fd34ca92b3e2bc7674ad4f15d08a76a6d70e75e/cmake/FindSIP.py) uses it too.

**Comment by sebastic** [comment]
> Don't forget that [cmake/FindSIP.py](https://github.com/qgis/QGIS/blob/6fd34ca92b3e2bc7674ad4f15d08a76a6d70e75e/cmake/FindSIP.py) uses it too.

The comments in [Python Issue 41282](https://bugs.python.org/issue41282) show that `sysconfig.get_path()` needs some conditionals to replace `get_python_lib()` on all supported OSes.
