### ISSUE TITLE
"Digitizing mesh elements" tool becomes "unresponsive" if you press undo while adding a face

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#51530]
### What is the bug or the crash?

If you undo while adding a new face, the face rubberband disappears as well as the last action you did before you start digitizing the face.
Then the "digitizing mesh elements" tool no longer shows the small triangle to snap to in order to start a new face.
You however can click the canvas and draw a linear rubberband that is hard to get something out (though I twice happened to create a new face from it but i'm unable to reproduce).
Lines of that rubberband are removed using backspace.

Afaict, the only way to get a responsive "Digitize mesh elements" tool is to press backspaces as many times as you added vertices to your next-to-be face. This is what is done at the end of the screencast to get the triangle back (sorry I don't know what tool others use to display mouse or keyboard action on their vids. Any suggestion...)
It looks like if the rubberband I was drawing at the start was somehow kept in "memory" or wherever it is

### Steps to reproduce the issue

[Kazam_screencast_00010.webm](https://user-images.githubusercontent.com/7983394/213849138-99f7ddc9-6ed1-433a-bdb2-0318838a5c28.webm)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.29.0-Master | QGIS code revision | 606cc0a5ad
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.1 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

my build is made with `ninja qgis` so no Python and some other things. Not sure it affects anything here but better inform...

**Comment by uclaros** [comment]
You can also hit _Esc_ to get back into a working state

**Comment by vcloarec** [comment]
should be fix by https://github.com/qgis/QGIS/pull/52259
