### ISSUE TITLE
Bug or new behaviour on default fields values on QGIS 3.28.X

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#51543]
### What is the bug or the crash?

Default values are called on every field update instead of only at the opening of the form even if the update default is not checked :

![QGEP_rp_from_to_fields_demo](https://user-images.githubusercontent.com/8614223/214012619-eb4b4451-e02a-4676-bf12-5ecbd875f748.gif)

![image](https://user-images.githubusercontent.com/8614223/214013074-c5a0b0f4-d450-4bf9-9e04-5c559bc688ec.png)

### Steps to reproduce the issue

1. Create a layer with some attributes
2.  Set a default value base on $geometry or $z value for one of the values
3. Create a feature with this default value used
4. Edit the default value
5. Edit another field

-> The default value for the first field is reset to default value

Expected : updated value is still present instead of default.

### Versions

QGIS 3.28.X

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Parent issue :
https://github.com/QGEP/QGEP/issues/779

[qgep.zip](https://github.com/QGEP/QGEP/files/10478562/qgep.zip) qgis project used

(demo-data)
https://github.com/QGEP/datamodel/releases/download/1.5.6-1/qgep_1.5.6-1_structure_and_demo_data.backup

**Comment by nicogodet** [comment]
I noticed this too
I believe this is an unwanted behavior and a regression...

**Comment by andreasneumann** [comment]
@elpaso - are you sure that "Apply on update" should only be triggered on form opening? Do you read that from the code?

I was sort of relying on the fact that the "Apply on update" also updates when another field changes the value while the form is open. At least it worked like this since a few versions. It would be a regression of the regression if we change that behavior now - but maybe we are the only ones relying on that feature?

However, I totally agree that for complex forms, the current mechanism doesn't work well (too many unnecessary updates --> form becomes unresponsive). I am currently discussing this with @domi4484 and @m-kuhn to find strategies to improve the "Apply on update" situation. But this error seems to be a different "regression", somehow related to geometry changes?

**Comment by nyalldawson** [comment]
> was sort of relying on the fact that the "Apply on update" also updates when another field changes the value while the form is open

I can confirm that this IS the intended behaviour. It's for fields like "last updated"/"last updated by" which get refreshed whenever the user makes any changes to the feature.

**Comment by elpaso** [comment]
> > was sort of relying on the fact that the "Apply on update" also updates when another field changes the value while the form is open
> 
> I can confirm that this IS the intended behaviour. It's for fields like "last updated"/"last updated by" which get refreshed whenever the user makes any changes to the feature.

So the error left here is that the default is updated even if "Apply on update" isn't checked.

**Comment by m-kuhn** [comment]
This behavior was intentionally introduced ~4 years ago for apply on update in
https://github.com/qgis/QGIS/pull/31167

In the case here (without apply on update) something else seems to be fishy.

**Comment by domi4484** [comment]
@elpaso are you working on this? otherwise i can take over

**Comment by elpaso** [comment]
@domi4484 it's all yours :⁠-⁠)

**Comment by ponceta** [comment]
@signedav is a backport to QGIS 3.28.5 planned?

@andreasneumann this works now fine on QGIS nightly but it is now a dangerous bug on recently published LTR 3.28.4.

/!\/!\/!\

This is a real issue for us because we are stuck on QGIS 3.22 until this is fixed, and since 3.28.4 is published we can't deploy any QGIS 3.22.X installation with osgeo4w. :( /!\/!\/!\

**Comment by signedav** [comment]
It's pushed to 3.30 and planned to backport it.

**Comment by ponceta** [comment]
Thank you @signedav for the feedback!
