### ISSUE TITLE
Can't load KMZ, but can load KML, on EndeavourOS

### ISSUE THREAD

**Issue by dgva** [qgis/QGIS#51548]
### What is the bug or the crash?

QGIS does not recognize and open KMZ files, forcing me to uncompress the file to KML, when using EndeavourOS. On Windows, and Linux Mint, it's possible to import directly KMZ files.

### Steps to reproduce the issue

1. Try to import KMZ file.
2. The import fails with following error:
>  Invalid Data Source : /home/.../Zone_6-Pomar.kmz is not a valid or recognized data source.

### Versions

QGIS version | 3.28.2-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.9
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PDAL version | 2.5.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.3
OS version | EndeavourOS
  |   |   |  
Active Python plugins
CalculateGeometry | 0.6.8
changeDataSource | 3.1
quick_map_services | 0.19.32
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

Active Python plugins
CalculateGeometry
0.6.8
changeDataSource
3.1
quick_map_services
0.19.32
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I have searched for some clues regarding `libkml`, but couldn't find any solutions.

**Comment by nicogodet** [comment]
How did you install QGIS on EndeavourOS ?

**Comment by nyalldawson** [comment]
This suggests that the GDAL library used by EndeavourOS wasn't compiled with support for KMZ -- you'll need to ask the package maintainers to add this to their build.

**Comment by dgva** [comment]
> How did you install QGIS on EndeavourOS ?

For reference, EndeavourOS pulls QGIS, GDAL, and respective dependencies from the original Arch repositories. Only some OS-specific packages are pulled from EndeavourOS's servers.
