### ISSUE TITLE
Deleting the "Text"

### ISSUE THREAD

**Issue by Elpasha55** [qgis/QGIS#51559]
### What is the bug or the crash?

Deleting the "Text"

### Steps to reproduce the issue

I have question in regard to removing the text. I clicked -Create Text at Point, but I can't find the way to remove them. Thanks
![image](https://user-images.githubusercontent.com/121881765/214251390-e4b0c87c-1c07-498a-9e6d-050d7107472e.png)

### Versions

QGIS Desktop 3.22.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@Elpasha55 Select it with the "Modify Annotations" tool and press Del or Backspace key. Read https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#interaction
Please note that questions should be asked on mailing lists (see [support channels](http://qgis.org/en/site/forusers/support.html)). This repository is for issue reports or feature requests. Thanks.

**Comment by Elpasha55** [comment]
thanks
