### ISSUE TITLE
QGIS memory issues when exporting from print composer

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#51567]
### What is the bug or the crash?

I have a large QGIS project which consists of several postgres layers. When I export TIF files from the Print composer the application freezes when using QGIS versions newer than 3.24. 

When I use version 3.24.3 the memory that is allocated goes up to over 20-30 GB (looking at the Activity Monitor) but with newer versions of QGIS the memory being used is stuck around 4 GB and QGIS freeze and is stuck until I force quit the application.

I have tried versions 3.26.3 and 3.28.2.

So it seems like newer versions of QGIS can't use more memory for some reason which is not enough for my export and then the application get stuck.

### Steps to reproduce the issue

Print composer –> Export to image.

### Versions

3.24.3 is the version that works.
3.26.3 and 3.28.2 does not work.

Computers used during tests are iMac (intel), Mac Mini (intel) and MacbookPro 13" (M2).

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by troopa81** [comment]
Are you using masks ?

**Comment by troopa81** [comment]
it could be related to this #50543

**Comment by oskarlin** [comment]
Yes, seems like it might be the same bug.

**Comment by agiudiceandrea** [comment]
Closed as dulicate of https://github.com/qgis/QGIS/issues/50543.
