### ISSUE TITLE
Unexpected Close of Application When Using actionSplitFeatures() Function

### ISSUE THREAD

**Issue by ranjanport** [qgis/QGIS#51562]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00003330 (most recent call first):
  File "C:\OSGeo4W\apps\Python39\lib\selectors.py", line 315 in _select
    r, w, x = select.select(r, w, w, timeout)
  File "C:\OSGeo4W\apps\Python39\lib\selectors.py", line 324 in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\OSGeo4W\apps\Python39\lib\socketserver.py", line 232 in serve_forever
    ready = selector.select(poll_interval)
  File "C:\OSGeo4W\apps\Python39\lib\threading.py", line 892 in run
    self._target(*self._args, **self._kwargs)
  File "C:\OSGeo4W\apps\Python39\lib\threading.py", line 954 in _bootstrap_inner
    self.run()
  File "C:\OSGeo4W\apps\Python39\lib\threading.py", line 912 in _bootstrap
    self._bootstrap_inner()

Current thread 0x00003680 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Run this code from Python Console
layer = iface.activeLayer()
def feature_added():
    layer.featureAdded.disconnect()
    layer.commitChanges()  
layer.featureAdded.connect(feature_added)
layer.startEditing()
iface.actionSplitFeatures().trigger()

2. Drag the pointer on any layer containing Line String
3. The Program will hang.

### Versions

Any Qgis with Version 3.22.7 or Higher or may be lower also have.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you correctly indent python code ?

**Comment by ranjanport** [comment]
It was as It comes from Qgis No modification has been made It was Copied and Pasted Here.

**Comment by nicogodet** [comment]
I mean this

> Run this code from Python Console
> layer = iface.activeLayer()
> def feature_added():
> layer.featureAdded.disconnect()
> layer.commitChanges()
> layer.featureAdded.connect(feature_added)
> layer.startEditing()
> iface.actionSplitFeatures().trigger()

You define a function but without proper indentation, no way to know where it ends

**Comment by ranjanport** [comment]
`# Get the active layer
layer = iface.activeLayer()
# Define a function called when a feature is added to the layer
def feature_added():
    layer.featureAdded.disconnect()
    layer.commitChanges()    
layer.featureAdded.connect(feature_added)
layer.startEditing()
iface.actionSplitFeatures().trigger()`

**Comment by ranjanport** [comment]
`
layer = iface.activeLayer()
def feature_added():
  layer.featureAdded.disconnect()
  layer.commitChanges()
layer.featureAdded.connect(feature_added)
layer.startEditing()
iface.actionSplitFeatures().trigger()
`

**Comment by nicogodet** [comment]
```python
layer = iface.activeLayer()

def feature_added():
  layer.featureAdded.disconnect()
  layer.commitChanges()

layer.featureAdded.connect(feature_added)
layer.startEditing()
iface.actionSplitFeatures().trigger()
```

No crash on 3.28.2
