### ISSUE TITLE
Problem with white background and masking in Print composer

### ISSUE THREAD

**Issue by oskarlin** [qgis/QGIS#51569]
### What is the bug or the crash?

When making maps using symbol layer type _Mask_, for some reason, areas of the map that does not have any polygons covering then the white background turns gray in the Print composer. 

A not so great workaround: If I create a huge polygon covering the whole map and style it white, then the background in the Print composer will be white.

_First image: map project without any Mask layers. See the center where there are green dots._
_Second image: map project with one layer that has Mask layers. See the center where there are green dots._

<img width="811" alt="Screenshot 2023-01-24 at 14 55 34" src="https://user-images.githubusercontent.com/2736990/214314026-8ac5a61b-a23c-4ecd-a017-4cf363bffb5f.png">

<img width="812" alt="Screenshot 2023-01-24 at 14 55 59" src="https://user-images.githubusercontent.com/2736990/214314041-8d54d904-780c-4454-8a78-6fd0d5a3ced5.png">

<img width="581" alt="Screenshot 2023-01-24 at 15 02 57" src="https://user-images.githubusercontent.com/2736990/214314876-5c524cb1-6f6f-47a0-9cbf-bfffdb6fdc60.png">

_The properties of the mask layer_

### Steps to reproduce the issue

Use layers with Symbol layer type _Mask_

### Versions

Tried both 3.24.2 and 3.28.2 on Macs.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Is this still reproducible in 3.38?
