### ISSUE TITLE
Configuration of symbol with line

### ISSUE THREAD

**Issue by Elpasha55** [qgis/QGIS#51575]
### Feature description

How can I straighten the symbol with adjacent line. I must always rotate to stabilize the symbol (traffic sign) according to the street.
![image](https://user-images.githubusercontent.com/121881765/214444573-678b1fcf-87b4-43a8-bad5-4fb302809374.png)

**Comment by andreasneumann** [comment]
@Elpasha55 - this is not a support forum. You can ask this question on the mailing list or GIS stack exchange.

There are multiple ways to achieve this - either with geometry generators on the same layer using expressions, or using expressions to find the closest line and then the angle of that segment. All of these tools exist in the QGIS expression engine.

Please use one of the QGIS support channels to ask such questsions: https://www.qgis.org/en/site/forusers/support.html or https://www.qgis.org/en/site/forusers/commercial_support.html
