### ISSUE TITLE
Attribute Table Automatic Scroll After Editing

### ISSUE THREAD

**Issue by jls7301** [qgis/QGIS#51572]
### What is the bug or the crash?

After editing a road layer's qualitative attribute in its attribute table and pressing enter, the attribute table automatically scrolls all the way to the bottom. This wouldn't be that annoying if I wasn't working with such a big dataset.

### Steps to reproduce the issue

1. Obtain a dataset with an attribute table of 10 or more rows, such that a scroll bar is needed.
2. Filter by an attribute in a vector layer (ex. ("PROPOSAL_STATUS" ILIKE '%REVIEW%') ).
3. Start editing that layer by clicking the pencil button.
4. Edit this field to be something other than what was filtered for (ex. ACCEPTED).
5. Press enter to lock in the edit.
6. The edited row should disappear from the table because it's no longer being filtered for.
The attribute table then scrolls down to the bottom of the table.

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.32
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This just started happening out of the blue--it didn't always do this. Additionally, I have already tried closing the program and reopening it and restarting my computer.

**Comment by agiudiceandrea** [comment]
@jls7301 could you please try with a new QGIS profile?
