### ISSUE TITLE
"Join by nearest" regression on 3.28 (from 3.22) when multiple geometry colums are present

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#51580]
### What is the bug or the crash?

Having a nodes layer with multiple geometries I usually did on 3.22 LTR the join by nearest algorithm to find out nodes that are closer than 0.003 m.

With 3.28.2 there's an error now:
```
Feature could not be written to Joined_layer_.....: Could not store attribute "geometry_alt1": Could not convert value "" to target type "string"
Could not write feature into OUTPUT
Execution failed after 0.11 seconds
```

### Steps to reproduce the issue

1. Add the following SQL to your PostgreSQL database:

```
CREATE TABLE public.nodes (
    id integer NOT NULL,
    fk_district integer,
    fk_pressurezone integer,
    fk_printmap integer[],
    fk_precision integer,
    fk_precisionalti integer,
    fk_object_reference integer,
    altitude numeric(10,3) DEFAULT NULL::numeric,
    _printmaps text,
    _geometry_alt1_used boolean,
    _geometry_alt2_used boolean,
    _pipe_orientation double precision DEFAULT 0,
    _pipe_schema_visible boolean DEFAULT false,
    geometry public.geometry(PointZ,3844) NOT NULL,
    geometry_alt1 public.geometry(PointZ,3844),
    geometry_alt2 public.geometry(PointZ,3844)
);

INSERT INTO public.nodes VALUES (58957, NULL, NULL, '{}', 101, 101, 101, NULL, NULL, false, false, -8.627881391886133, true, '01010000A0040F00000000000018451B4100000000044018410000000000000000', NULL, NULL);
INSERT INTO public.nodes VALUES (58971, NULL, NULL, '{}', 101, 101, 101, NULL, NULL, false, false, -18.95382931168005, true, '01010000A0040F00000000000018451B4100000000084018410000000000000000', NULL, NULL);

ALTER TABLE ONLY public.nodes
    ADD CONSTRAINT node_pkey PRIMARY KEY (id);


CREATE INDEX node_geoidx ON public.nodes USING gist (geometry);


CREATE INDEX node_geoidx_alt1 ON public.nodes USING gist (geometry_alt1);

CREATE INDEX node_geoidx_alt2 ON public.nodes USING gist (geometry_alt2);
```

2. Run the join by nearest algo:

![image](https://user-images.githubusercontent.com/3179646/214541557-c6bc1f72-8b7b-444b-9b60-0d5cada053fc.png)

3. The error is shown:
```
Feature could not be written to Joined_layer_.....: Could not store attribute "geometry_alt1": Could not convert value "" to target type "string"
Could not write feature into OUTPUT
Execution failed after 0.11 seconds
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.2-Firenze | QGIS code revision | d33b8750f3
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.5.2
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.40.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 37 (Thirty Seven)
  |   |   |  
Active Python plugins
slyr_community | 4.0.6
QuickWKT | 3.1
project_export_inspire | 1.0.0
water_topology | 0.1
plugin_reloader | 0.9.3
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.2-Firenze
QGIS code revision
[d33b8750f3](https://github.com/qgis/QGIS/commit/d33b8750f3)
Qt version
5.15.8
Python version
3.11.1
GDAL/OGR version
3.5.2
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.40.0
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.13.0
OS version
Fedora Linux 37 (Thirty Seven)

Active Python plugins
slyr_community
4.0.6
QuickWKT
3.1
project_export_inspire
1.0.0
water_topology
0.1
plugin_reloader
0.9.3
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
CREATE INDEX node_geoidx_alt2 ON public.nodes USING gist (geometry_alt2);
ERROR:  schema "qwat_od" does not exist
LINE 13:     _pipe_node_type qwat_od.pipe_connection,

**Comment by tudorbarascu** [comment]
@elpaso Sorry. I edited the issue and posted the right SQL. All the best. Thank you.

**Comment by elpaso** [comment]
@tudorbarascu what was the 3.22 behavior with those extra geom fields?

**Comment by elpaso** [comment]
... in other words: what is the expected behavior (besides not erroring out)?

**Comment by tudorbarascu** [comment]
@elpaso Hello. The expected behavior is to join the 2 points in a layer the attributes combined. It works like this in 3.22 and it also joins the extra geometry columns.

**Comment by elpaso** [comment]
@tudorbarascu my question was more about the extra geometry columns support: if the output is a memory layer there is no support for additional geometry columns in memory provider so I don't get how 3.22 could handle those columns in the output layer (when set to "memory").

**Comment by tudorbarascu** [comment]
Oh, it just makes them as QString! Sorry :)

I temporarily filled in a geometry_alt1 in one of the points just so it shows.

![image](https://user-images.githubusercontent.com/3179646/218483758-47618b1c-d742-4695-8518-ba69bd6df58e.png)

![image](https://user-images.githubusercontent.com/3179646/218483871-682530f7-ec93-4766-9ddb-cbc9060f8162.png)
