### ISSUE TITLE
QGIS can not open, (QGIS unexpectedly ended)

### ISSUE THREAD

**Issue by Elpasha55** [qgis/QGIS#51581]
### What is the bug or the crash?

Crash ID: [62c06df51ba84c32376002e25009cb4640285a25](https://github.com/qgis/QGIS/search?q=62c06df51ba84c32376002e25009cb4640285a25&type=Issues)

Stack Trace

QNetworkAccessManager::cookieJar :
QgsNetworkAccessManager::setupDefaultProxyAndCache :
QgsNetworkAccessManager::instance :
QgsNetworkContentFetcher::fetchContent :
QgsNetworkContentFetcherTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.14-Białowieża
QGIS code revision: 4cde646c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.1
Running against GDAL: 3.6.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

I try to open QGIS b
![image](https://user-images.githubusercontent.com/121881765/214573381-2f7abf4f-d2d7-4b20-86ee-0817c8e963c6.png)
![image](https://user-images.githubusercontent.com/121881765/214573422-7da5f457-64bd-4c98-8aac-79c65de56029.png)
ut "unexpected ended" written

### Versions

QGIS Desktop 3.22.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Is this still an issue with the latest versions?
