### ISSUE TITLE
'Pick Color' cursor does not work beyond original window

### ISSUE THREAD

**Issue by greenoguy** [qgis/QGIS#51592]
### What is the bug or the crash?

When editing the font color in the Title Lable Decoration, I could not use the color picker to match the title color with the color for the rest of the map.  The color picker 'cursor' stops working when it moves beyond the original window, in this case the Title Lable Text Format window.  It turns into a regular cursor when I try to click anywhere on the map.

### Steps to reproduce the issue

1. Go to 'View'
2. Go to 'Decorations' > 'Title Label'
3. Click on large box next to 'Font'
4. in the 'Text' category, click on the little arrow next to 'Color'
5. Select 'Pick Color'
6. Move cursor to desired color on map.
7. See error

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.14-Białowieża | QGIS code revision | 4cde646cf9
-- | -- | -- | --
Qt version | 5.14.2
Python version | 3.8.7
GDAL/OGR version | 3.2.1
PROJ version | 6.3.2
EPSG Registry database version | v9.8.6 (2020-01-22)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.31.1
PostgreSQL client version | 12.3
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.4
OS version | macOS 13.1
  |   |   |  
Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.5

</body></html>QGIS version
3.22.14-Białowieża
QGIS code revision
[4cde646cf9](https://github.com/qgis/QGIS/commit/4cde646cf9)
Qt version
5.14.2
Python version
3.8.7
GDAL/OGR version
3.2.1
PROJ version
6.3.2
EPSG Registry database version
v9.8.6 (2020-01-22)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PostgreSQL client version
12.3
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.4
OS version
macOS 13.1

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I turned my permissions on for QGIS recording my screen, which I saw online could have been the issue.  So I am not sure why it is still not working.

**Comment by mblesius** [comment]
Have you tried using the space bar to pick a color from another window?

**Comment by nicogodet** [comment]
Which error ?

i reproduce your steps on Windows with 3.22.14 and 3.28.3, no error and I'm able to pick color both inside (with correct cursor) and outside (with wrong cursor but it is not new) QGIS window.

**Comment by nyalldawson** [comment]
This is a limitation on the macos platform -- I'm not aware of any workarounds.

**Comment by greenoguy** [comment]
Thank you for looking into this.  I was able to find a workaround by clicking and dragging my mouse to outside of the original window.  It works if you do that.  Upon reading comments from users with the same issue, it's clear this is an issue with just macs and it does not happen in Windows.  I wonder if QGIS will look into a fix for this for future versions.

**Comment by greenoguy** [comment]
> Have you tried using the space bar to pick a color from another window?

I have not tried this.  Is this similar to the click and drag workaround?

**Comment by mblesius** [comment]
> I have not tried this. Is this similar to the click and drag workaround?

It's actually not a workaround but the keyboard shortcut for the color picker tool. Try to move the cursor out of the original window and instead of left/right clicking to take the color, press the space bar. The advantadge is, that this will not change the window focus. But, I'm not familiar with macOS so I can't guarantee you that it works.

**Comment by m-kuhn** [comment]
> This is a limitation on the macos platform -- I'm not aware of any workarounds.

Did you look into using the native dialog instead? Apparently that's how others do.

**Comment by nyalldawson** [comment]
@m-kuhn 
The native dialog is extremely limited -- it would be a big regression to use that
