### ISSUE TITLE
Console Without Redrawing

### ISSUE THREAD

**Issue by pushheap** [qgis/QGIS#51597]
### What is the bug or the crash?

I run a small script, it works on about 40 shapefiles, calculates the area of each feature, stores it in the table, and then prints the sum to the console.

The console and QGIS remain without redrawing (frozen), until the process is finished.

I thought, that in each interaction with each file the console shows the result, but this is not the case.

When the process is finished, it displays all the results together.

This maybe a bug.

### Steps to reproduce the issue

layers = iface.mapCanvas().layers()

for layer in layers:
	shapes.append(layer)

for layer in layers:

	asum = 0.00
	for feature in layer.getFeatures():

		geom = feature.geometry()
		area = (geom.area()/10000)

		asum = (asum + area)

		with edit(layer):
			feature['HECTAREAS'] = area
			layer.updateFeature(feature)

	print(layer.name() + ' | ' + str(round(asum, 2)) + 'ha')

### Versions

3.28.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
> I thought, that in each interaction with each file the console shows the result, but this is not the case.

No, that's up to you to handle

You could insert something like a `iface.mapCanvas().refresh()` in there to manually redraw the map
