### ISSUE TITLE
Browser is very slow if GDB is shown within currently visible directories

### ISSUE THREAD

**Issue by ztgis** [qgis/QGIS#51595]
### What is the bug or the crash?

Navigating near a FileGeodatabase or accessing it freezes QGIS for 5-30 seconds.

I am wondering if QGIS is doing some file operation/lookup or updating statistics, ... when I sees a GDB??

### Steps to reproduce the issue

I guess my issue does not occur everywhere. To hopefully find the issue, I have uploaded a sample dataset: 
[performance.gdb.zip](https://github.com/qgis/QGIS/files/10509342/performance.gdb.zip)

1. Open Browser
2. Navigate to a directory that contains a GDB
3. QGIS freezes > does this also happen at your machine?

### Versions

QGIS-Version
3.28.2-Firenze
QGIS-Codeversion
b47e00ba601
Qt-Version
5.15.3
Python-Version
3.9.5
Kompiliert mit GDAL/OGR
3.6.1
Läuft mit GDAL/OGR
3.6.2
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
Mergin
2022.6
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
qfieldsync
v4.2.0
qgiscloud
3.7.1
QuickOSM
2.1.1
StreetView
3.2
ztgis-tools
0.3
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ztgis** [comment]
See also https://github.com/OSGeo/gdal/pull/7131

**Comment by rouault** [comment]
closing as upstream bug

**Comment by anaxonda** [comment]
Running the latest gdal (3.6.3) and browser is unusably slow when viewing GDB files.

```
QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.10
GDAL/OGR version | 3.6.3
Compiled against PROJ | 9.1.1.%3.%4 | Running against PROJ | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.4
OS version | Arch Linux
  |   |   |  
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code branch
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Qt version
5.15.8
Python version
3.10.10
GDAL/OGR version
3.6.3
Compiled against PROJ
9.1.1.%3.%4
Running against PROJ
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.4
OS version
Arch Linux




Active Python plugins
db_manager
0.1.20
MetaSearch
0.3.6
grassprovider
2.12.99
processing
2.12.99
```
