### ISSUE TITLE
qGIS 3.28 on MAC M2

### ISSUE THREAD

**Issue by ETszn** [qgis/QGIS#51616]
### What is the bug or the crash?

As I try to open qGIS 3.28 on MAC M2 appears a window saying:" Impossibile aprire “QGIS” perché Apple non può verificare la presenza di malware. È necessario aggiornare il software. Per ulteriori informazioni, contatta lo sviluppatore." in English: It is impossible to open QGIS because Apple cannot veryfy the presence of a malware. For further info, contact the developer.

### Steps to reproduce the issue

Open

### Versions

QGIS 3.28.2-Firenze (), © 2002-2019 QGIS Development Team

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@ETszn have you read and followed the advise in the [download page](https://qgis.org/en/site/forusers/download.html) for macOS?

> macOS High Sierra (10.13) or newer is required. QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.

![image](https://user-images.githubusercontent.com/16253859/215084538-0218a2d5-1829-4332-881a-0da6c433879d.png)

**Comment by ETszn** [comment]
Thank you, If you hold the option key you cannot choose Open. I have macOS Ventura 13.0!
Maybe I have to wait…
et

**Comment by agiudiceandrea** [comment]
@ETszn try:
- right click on the icon in menu -> Open -> Open
or
- follow the advise at https://support.apple.com/it-it/guide/mac-help/mchleab3a043/mac: in Finder locate the app then Control-click the app icon -> Open -> Open
or
- follow the advise at https://support.apple.com/en-gb/HT202491

**Comment by ETszn** [comment]
Thank you so much: this worked 
> 
> in Finder locate the app then Control-click the app icon -> Open -> Open
Have a good time
et
