### ISSUE TITLE
If some layers are not identifyable, QGIS Server WMS "GetFeatureInfo" returns LayerNotQueryable

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#51613]
### What is the bug or the crash?

If you use WMS GetFeatureInfo with LAYER set to the project name (to gather all layers), but one layer is not identifyable, the QGIS SERVER returns LayerNotQueryable.

QGIS server should skip those layers.

### Steps to reproduce the issue

1. Set one layer to do not be identifyable
2. Issuse a WMS GetFeatureInfo with LAYER to the project name
3. QGIS Server returns LAYERNOTQUERYABLE

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Cannot reproduce. 

I also wrote some additional tests to verify that everything works as expected.
