### ISSUE TITLE
Crash on closing of QGIS

### ISSUE THREAD

**Issue by 22111972** [qgis/QGIS#51612]
### What is the bug or the crash?

h2. User Feedback

When closing the program. First there was the question to save the project, after clicking yet it was asked a second itme, and after clicking OK the program crashed.

h2. Report Details

*Crash ID*: 62f1fcd2045780cb9f127836e6b579b8665f3e63

*Stack Trace*
<pre>
proj_lpz_dist :
proj_lpz_dist :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::QgsCoordinateTransform :
QHashData::free_helper :
QgsCoordinateTransform::addToCache :
QgsCoordinateTransform::invalidateCache :
QgsApplication::exitQgis :
QgisApp::~QgisApp :
CPLStringList::operator[] :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

*QGIS Info*
QGIS Version: 3.6.1-Noosa
QGIS code revision: commit:2468226bc9
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 2.4.1
Running against GDAL: 2.4.1

*System Info*
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.14393

### Steps to reproduce the issue

Not reproducable

### Versions

QGIS Desktop 3.6.1 - Noosa

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@22111972 QGIS 3.6 is no longer supported. Please try using a new currently supported QGIS version and/or a new QGIS user profile.
