### ISSUE TITLE
"Save layer as..." back to context menu

### ISSUE THREAD

**Issue by winnewoerp** [qgis/QGIS#51620]
### Feature description

In older QGIS versions (maybe < version 3, I'm not sure), it was possible to right-click layers in the layer list and select "Save Layer As..." from the context menu. Now, the "Layer" menu in the main menu has to be used. It's both the same number of clicks, but I find it more intuitive to do it via the layers list. IMHO it would be extremely useful to "re-add" that option to the context menu!

**Comment by agiudiceandrea** [comment]
The functionality is right there in the layer contextual menu:

![image](https://user-images.githubusercontent.com/16253859/215252765-08d1bde8-61d8-4acd-955b-90285d68af55.png)

Please see the QGIS Desktop User Guide/Manual at https://docs.qgis.org/3.22/en/docs/user_manual/managing_data_source/create_layers.html#creating-new-layers-from-an-existing-layer

**Comment by winnewoerp** [comment]
Thank you. I must have been blind or I did not expect that saving a layer is actually under "Export". Of course newer QGIS versions never remove good old functionalities. :)
