### ISSUE TITLE
Layer name in save dialog no longer matches main database name

### ISSUE THREAD

**Issue by djwalkr** [qgis/QGIS#51629]
### What is the bug or the crash?

This is a bug in the behaviour of 3.28 that differs from the default behaviour (or LTR) whereby the layer name when saving any spatial database no longer default to the base file name.

### Steps to reproduce the issue

The steps are as follows and occur when any file is saved. For an example (and to eliminate file drivers as an issue). 
1. Create a New Temporary Scratch Layer. Call it 'Bill'. Make it any type (point, line or polygon). Use point for simplicity. Don't bother adding a field or add one - doesn't matter.
2. Use any standard CRS - EPSG 4326 (for simplicity)
3. When added to the Layer Panel right-click and Export to a new geopackage (for simplicity) or Make Permanent. Doesn't matter - error also happens with other formats.
5. In the Save Scratch Layer dialog click by 'File name' and use the system dialog to "Save file as" and save the file in a directory using the name 'Sally'. Click Save
6. In the main Save Scratch Layer dialog, the Layer name should (based on past behaviour) be 'Sally' to be saved in a geopackage called Sally.gpkg. In 3.28 the layer will still say 'Bill' to be saved in the file Sally.gpkg.

### Versions

3.28 works properly in 3.22 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This was an intentional change, designed to retain the current layer name whenever the layer is saved in a "database style" format like GPKG/FileGeodatabase.

**Comment by stephane-rds** [comment]
IMO the previous behavior was better.
Not sure how hard it would me to have a setting for this, but it would be nice.
