### ISSUE TITLE
Problem with Widget Type in Attributes Form

### ISSUE THREAD

**Issue by juliaroska** [qgis/QGIS#51624]
### What is the bug or the crash?

So I've opened an Attributes Form for my layer and chose one of my Available Widgets. Then in Wigdet Type I wanted to choose "Range" but it is in gray color and unavailable to click. What should I do make it work?

Here's a screenshot:
![image](https://user-images.githubusercontent.com/123818252/215271446-f9fc1967-ed89-47d7-87b9-97e86548cc19.png)

### Steps to reproduce the issue

.

### Versions

.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
Range works for numeric fields. Are you sure your field is (recognized by QGIS as) a numeric field ?

**Comment by agiudiceandrea** [comment]
It seems the field is a text / string type field. so it is normal that the Range widget is not available since it is available only for numeric type fields.
![image](https://user-images.githubusercontent.com/16253859/215337704-6323cca6-5604-43ee-b302-e0adf3c5823a.png)

**Comment by DelazJ** [comment]
Good catch @agiudiceandrea 
I didn't think to zoom in and see the field type.
