### ISSUE TITLE
Help for custom functions is missing from Ctrl+click interaction

### ISSUE THREAD

**Issue by anitagraser** [qgis/QGIS#51628]
### What is the bug or the crash?

I followed the instructions in https://docs.qgis.org/3.22/en/docs/user_manual/expressions/expression.html#function-editor and noticed that the help for the function does not always show up as expected:

### Steps to reproduce the issue

1. Go to the Function Editor
2. Create a new function file. This file should come with the default dummy "my_sum" function
3. Save and Load the function
4. Back in the Expression window, the help of my_sum is displayed fine when we select the function from the function list in the center ![image](https://user-images.githubusercontent.com/590385/215349184-6bb3f222-fc8e-4743-a624-c13f7421deb8.png)
5. However, when you Ctrl+click on the function name in the expression editor (on the left), the help window displays an error message:
![image](https://user-images.githubusercontent.com/590385/215349225-07a028b1-cafa-4d60-b20e-c3babe378d4a.png)

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DataPlotly
3.9.2
MemoryLayerSaver
4.0.4
minimal_processing
1.0
pluginbuilder3
3.2.1
PluginLoadTimes
3.0.1
plugin_reloader
0.9.2
processing_r
3.1.1
processing_trajectory
1.0.3
qgis_resource_sharing
1.0.0
QuickOSM
2.1.1
quick_map_services
0.19.32
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Duplicates #26964.
