### ISSUE TITLE
2D read as 3D

### ISSUE THREAD

**Issue by qgiscirrus** [qgis/QGIS#51656]
### What is the bug or the crash?

My QGIS started reading all shapefiles as 3D files rather than 2D files. I uploaded a 2D file which it randomly read as a 3D file and then it changed all of my other already uploaded files to 3D files. When i load it onto a different computer, it once again reads it as a 2D file. I've uninstalled the program and have tried saving the files without a z axis but regardless of what i do, it won't read any file as 2D files.

### Steps to reproduce the issue

example opened up on another computer where it works perfectly fine
![image](https://user-images.githubusercontent.com/124028718/215694965-1aababc0-0004-4e9c-a0fc-828629e438ca.png)
exactly the same file opened up on the computer that changes everything to 3D
<img width="824" alt="Screenshot 2023-01-31 at 09 25 06" src="https://user-images.githubusercontent.com/124028718/215694977-1f62cbdd-4461-4635-91c5-c92a1d58cbc9.png">

### Versions

QGIS version | 3.28.2-Firenze | QGIS code revision | b47e00ba60
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.1
  |   |   |  
Active Python plugins
SRTM-Downloader | 3.1.17
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.2-Firenze
QGIS code revision
[b47e00ba60](https://github.com/qgis/QGIS/commit/b47e00ba60)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.1

Active Python plugins
SRTM-Downloader
3.1.17
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I work on a macbook, i tried on my other laptop that is an acer and it worked, but i got someone else to open the same files in their macbook and it worked there as well.

**Comment by uclaros** [comment]
It seems that the properties dialog is switched to the _3d view_ tab which handles 3d symbology. You can select the _Symbology_ tab to alter 2d symbology.
![image](https://user-images.githubusercontent.com/11358178/215707789-50d32567-b45a-4496-85af-67980c591163.png)

If you only need to change the symbology you can use the styling panel (try hitting F7) instead of opening the layer properties.

Closing this as there doesn't seem to be a bug here :)
