### ISSUE TITLE
Strange behavior in Python Console

### ISSUE THREAD

**Issue by see7e** [qgis/QGIS#51650]
### What is the bug or the crash?

After executing some code (created and tested before), the Console started to print (attached image) all feat geometries infinitely, I really don't know what is the reason for this behavior. I tried to stop the processing somehow, closed QGis in the Task Manager and even restarted the computer.

If I open a file that already contains some geometry, it follows the same pattern, but if I open an empty file, it doesn't print anything or show any errors.

![image](https://user-images.githubusercontent.com/15942792/215594133-07d9f88a-1258-4166-9d26-8f56ae0367c3.png)
![image](https://user-images.githubusercontent.com/15942792/215594280-bbd11ca1-4ce5-4af3-9881-dab3aa53acf2.png)

### Steps to reproduce the issue

The code I've just runned imports some shapefiles to a group and makes some geometries adjustments, and then copies again to a definitive layer witch are defined styles and categories.

### Versions

**QGIS version**
3.22.4-Białowieża
QGIS code revision
ce8e65e9
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

**Active Python plugins**
autoSaver
2.6
ClipMultipleLayers
3.2.0
joinmultiplelines
Version 0.4.1
LoadQSS
1.4.2
qmapshaper
0.8.0
refFunctions
1.6
SelectWithin
0.4
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

If needed I can dipose some code snippets to additional info.

**Comment by see7e** [comment]
I found a clue, actually most likely not due to the script, I went back to an earlier version of the template and ran the same code with the same shapefiles and:

![image](https://user-images.githubusercontent.com/15942792/215599363-4f8c8893-d742-4704-8770-9269aacf225d.png)

**Comment by see7e** [comment]
**Sorry, I've accidentally closed the Issue.** 

I found a clue, actually most likely not due to the script, I went back to an earlier version of the template and ran the same code with the same shapefiles and:

![image](https://user-images.githubusercontent.com/15942792/215599563-c826e70a-5f65-409b-ac42-e5dea0011312.png)

**Comment by Rimann91** [comment]
The seems like it is likely a problem with your script, not with QGIS. You say that you tested it before, what environment did you test it in?

**Comment by see7e** [comment]
I didn't create any new environment after QGis installation. The only modifications made in (file) template were new shapes with designed styles. Running the code in previous version worked as expected, without the loop.

This shows even after I close and reopen the instance.

**Comment by uclaros** [comment]
> The seems like it is likely a problem with your script, not with QGIS.

It's pretty definitely you script... In your _successful_ run you can even see that it say `DXF export skipped`, which is probably where those print statements reside. You may share your script, but note that github is not supposed to be the dev support channel. You can seek further assistance at the qgis mailing lists (dev/user) or gis.stackexchange.com

**Comment by see7e** [comment]
The export statement is basically a code snippet (print) that should organize the shapes in terms of exposure for the export itself, but I mostly left it commented, as my superiors had other, more urgent demands.

![image](https://user-images.githubusercontent.com/15942792/215712346-ba5f7f35-a5c0-437b-9d96-6305c62f16f2.png)

**Comment by uclaros** [comment]
Sorry, your script is missing _at least 466_ lines!

**Comment by see7e** [comment]
> Sorry, your script is missing _at least 466_ lines!

You want it all?
`import os
import os.path
from qgis.core import *
from PyQt5.QtCore import QVariant #FOR MODIFYING LYR ATTRIBUTES
import processing
import time

""" log
v1.7=added tools functions, other modifications
v1.6=bug fixes
v1.5=cable labels in a separate script
v1.4.1=bug fixes
v1.4=cable lables info
v1.3=added fix geometries
v1.2=added DHH equipm
v1.1=fixed some bugs, changed Join fields
v1.0=first dev version (missing export)
"""

#0.0 DEFINITIONS
prj = QgsProject.instance()
prjTitle = prj.title()
root = prj.layerTreeRoot()
start_time = time.time()    #Timer

progression = 0 #index management
"""0=import / 1=layers / 2=fix geometries / 3=joins / 4=copies / 5=export"""

#0. set directories structure
project_path = prj.readPath("./")
qgis_layers_path = project_path + "/Shapes de Base"
export_layers_path = project_path + "/export_shapes/"
_temp_path = project_path+"/_temp/"
#scriptpath = "c:/QGIS/Reference Data/Scripts/"  #DEFINIR CAMINHO

#0.2 Progress bar
progressMessageBar = iface.messageBar().createMessage("Processing...")
progress = QProgressBar()
progress.setMaximum(7)
progress.setAlignment(Qt.AlignLeft|Qt.AlignVCenter)
progressMessageBar.layout().addWidget(progress)
iface.messageBar().pushWidget(progressMessageBar, Qgis.Info)
progression = 0

#0.3 Project Title
if prjTitle == 'prj_title':
    qid = QInputDialog()
    title = "Title"
    label = "Insert Value: "
    mode = QLineEdit.Normal
    default = "<title>"
    tit, ok = QInputDialog.getText(qid, title, label, mode, default)
    prjTitle = prj.setTitle(tit)

#0.4 clearSelection Function
def ClearSelection ():
    mc = iface.mapCanvas()
    for layer in mc.layers():
        if layer.type() == layer.VectorLayer:
            layer.removeSelection()
    mc.refresh()

#0.5 Copy Funct
#exp - '\"layer\"= \'export - D-HH\''
def copyByExp(source,target,exp):   #src:<lyr>|trg:<lyr>|exp:'str'
    source.selectByExpression(exp)
    iface.copySelectionToClipboard(source)

    target.startEditing()
    iface.pasteFromClipboard(target)
    target.commitChanges()


def copyAll(source,target): #src:<lyr>|trg:<lyr>
    source.selectAll()
    iface.copySelectionToClipboard(source)

    target.startEditing()
    iface.pasteFromClipboard(target)
    target.commitChanges()

#0.6 Processing Run
#def processingRun (name,param):
#    #name:'string'|param:{dic}
#    processing.run('native:snapgeometries', {
#        'BEHAVIOR': 2,  # Prefer aligning nodes, don't insert new vertices
#        'INPUT': ALL_PT['OUTPUT'],
#        'REFERENCE_LAYER': export_paal_lyr,
#        'TOLERANCE': 0.15,
#        #'OUTPUT': parameters['Snapped_aerialboxes']
#        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
#    })

# 1.0 LAYERS MANAGEMENT
## 1.1 EXPORTED LAYERS FROM GEOSTRUCT TO "export" GROUP
if progression == 0:
    groupName="export"
    group = root.addGroup(groupName)

    vlyrMap = ["export - A-Cable", "export - A-Duct", "export - A-Area", "export - Aerial Box",
                "export - Aerial Duct", "export - Aerial Route", "export - BE",
                "export - CO", "export - D-Cable", "export - D-Duct", "export - HLDDuct", "export - D-HH",
                "export - DP", "export - Drop Cable", "export - Façade Route",
                "export - HP", "export - F-Cable", "export - Paal", "export - Geul", "export - Persing",
                "export - Riser", "export - Termination Box", "export - Koppeling"]
                #ADICIONAR O KOEPELING

    #1.1.1 pode ser definida "path" e adicionar cm map loop
        #https://gis.stackexchange.com/questions/290938/adding-layer-to-group-in-layers-panel-using-pyqgis
    for shape in vlyrMap:
        export_layers_path = export_layers_path + shape + ".shp"
        vlayer = QgsVectorLayer(export_layers_path, shape,"ogr")
        prj.addMapLayer(vlayer, False)
        group.addLayer(vlayer)
          
        
        #print(vlayer.name() + ' added')  #debug        
        export_layers_path = project_path + "/export_shapes/"    #reset path
    
    progression += 1 #jump
    progress.setValue(progression)

else:
    #progression = progression + 1 #jump
    print('[i1.1] - Import from GeoStruct skipped')

## 1.2 DEFINE LAYERS IN PROJECT
    #set the layers variable = a list of all the layer objects open in the QGIS interface
if progression == 1:
    #lyrs
    co_lyr = prj.mapLayersByName('CO')[0]
    dp_lyr = prj.mapLayersByName('DP')[0]
    dhh_lyr = prj.mapLayersByName('DHH')[0]
    riser_lyr = prj.mapLayersByName('Riser')[0]
    poleClosure_lyr = prj.mapLayersByName('Pole Closure')[0]
    facadeClosure_lyr = prj.mapLayersByName('FacadeClosure')[0]
    terminationBox_lyr = prj.mapLayersByName('TerminationBox')[0]
    dropCable_lyr = prj.mapLayersByName('DropCable')[0]
    distCables_lyr = prj.mapLayersByName('Distribution Cables')[0]
    feedCable_lyr = prj.mapLayersByName('Feeder Cable')[0]
    multFus_lyr = prj.mapLayersByName('MultiFus')[0]
    dDucts_lyr = prj.mapLayersByName('D-Ducts')[0]
    be_lyr = prj.mapLayersByName('BE')[0]
    paal_lyr = prj.mapLayersByName('Paal')[0]
    hp_lyr = prj.mapLayersByName('HPs')[0]
    bk_lyr = prj.mapLayersByName('BK')[0]
    #csv
    aerial_enclosures_lyr = prj.mapLayersByName('aerial_enclosures')[0]
    dp_enclosures_lyr = prj.mapLayersByName('dp_enclosures')[0]
    dhh_enclosures_lyr = prj.mapLayersByName('dhh_enclosures')[0]

    layers = prj.mapLayers().values()
    for layer in layers:
        #print(layer.name()) #debug        
        #export
        if layer.name() == "export - CO":
            export_co_lyr = layer
        if layer.name() == "export - DP":
            export_dp_lyr = layer
        if layer.name() == "export - D-HH":
            export_dhh_lyr = layer
        if layer.name() == "export - Riser":
            export_riser_lyr = layer
        if layer.name() == "export - Aerial Box":
            export_ab_lyr = layer
        if layer.name() == "export - Termination Box":
            export_terminationBox_lyr = layer
        if layer.name() == "export - A-Cable":  #dropCables
            export_aCable_lyr = layer
        if layer.name() == "export - A-Area":
            export_aArea_lyr = layer
        if layer.name() == "export - D-Cable":
            export_dCables_lyr = layer
        if layer.name() == "export - F-Cable":
            export_fCable_lyr = layer
        if layer.name() == "export - A-Duct":
            export_aDuct_lyr = layer
        if layer.name() == "export - D-Duct":
            export_dDucts_lyr = layer
        if layer.name() == "export - BE":
            export_be_lyr = layer
        if layer.name() == "export - Paal":
            export_paal_lyr = layer
        if layer.name() == "export - HP":
            export_hp_lyr = layer
        if layer.name() == "export - HLDDuct":
            export_hldD_lyr = layer
        if layer.name() == "export - Koppeling":
            export_bk_lyr = layer

    progression += 1 #jump
    progress.setValue(progression)
else:
    #progression = progression + 1 #jump
    print('[i1.2] - Layers Defnition skipped')

## 1.3 FIX GEOMETRIES
if progression == 2:
    #processing calfunctions
    outputs = {}
    #outp_list = ['\"Snapped_aerialboxes\"', '\"Snapped_dducts\"', '\"Snapped_dcables\"', '\"Snapped_fcables\"', '\"Snapped_dropcables\"']
    #outp_list = ['\"SnapAerialboxToPaal\"', '\"SnapDductToAerialBoxes\"', '\"SnapfxDcableToDp\"', '\"SnapfxDcableToDp\"', '\"SnapFxFcableToCo\"', '\"SnapFxdropcableToHp\"']
    outp_list = ['SnapAerialboxToPaal', 'SnapDductToAerialBoxes', 'SnapfxDcableToDp', 'SnapfxDcableToDp', 'SnapFxFcableToCo', 'SnapFxdropcableToHp']
    _temp_list = []
    
    _temp_groupName="_temp"
    _tempGroup = root.addGroup(_temp_groupName)
    #print(_temp_list)  #debug

    #JUNTA TODOS OS PONTOS
    ALL_PT = processing.run("native:mergevectorlayers", 
    {'LAYERS':[export_dp_lyr, export_riser_lyr, export_ab_lyr, export_terminationBox_lyr, export_co_lyr, export_dhh_lyr, export_be_lyr, export_hp_lyr, export_bk_lyr],
    'CRS':QgsCoordinateReferenceSystem('EPSG:31370'),
    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT})
    
    SNAP_PONTOS = processing.run('native:snapgeometries', {
        'BEHAVIOR': 2,  # Prefer aligning nodes, don't insert new vertices
        'INPUT': ALL_PT['OUTPUT'],
        'REFERENCE_LAYER': export_paal_lyr,
        'TOLERANCE': 0.15,
        #'OUTPUT': parameters['Snapped_aerialboxes']
        'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
    })

    #ATUALIZA O CAMPO ID
    ALL_PT = processing.run("native:fieldcalculator", 
    {'INPUT':SNAP_PONTOS['OUTPUT'],
    'FIELD_NAME':'ID',
    'FIELD_TYPE':2,
    'FIELD_LENGTH':250,
    'FIELD_PRECISION':0,
    'FORMULA':"$ID",
    'OUTPUT':_temp_path+'Points_Final.shp'
    }) #########################
    vlayer = QgsVectorLayer(_temp_path+'Points_Final.shp', 'Points_Final', "ogr")
    prj.addMapLayer(vlayer, False)
    _tempGroup.addLayer(vlayer)
    
    #FIX AS (dist) CABLES AOS ALL_PT
    DIST_CABLES = processing.run("native:fixgeometries", 
    {'INPUT':export_dCables_lyr,
    'OUTPUT':QgsProcessing.TEMPORARY_OUTPUT})

    #ATRAI AS (dist) CABLES AOS ALL_PT
    DIST_CABLES = processing.run("native:snapgeometries", 
    {'INPUT':DIST_CABLES['OUTPUT'],
    'REFERENCE_LAYER':ALL_PT['OUTPUT'],
    'TOLERANCE':0.15,
    'BEHAVIOR':0,
    'OUTPUT':QgsProcessing.TEMPORARY_OUTPUT})

    #CAMPOS DE ORIGEM E DESTINO
    DIST_CABLES = processing.run("native:fieldcalculator", 
    {'INPUT':DIST_CABLES['OUTPUT'],
    'FIELD_NAME':'ORIGEM',
    'FIELD_TYPE':2,
    'FIELD_LENGTH':250,
    'FIELD_PRECISION':0,
    'FORMULA':"aggregate(\r\nlayer:= 'Points_Final',\r\naggregate:='concatenate',\r\nexpression:= to_string(ID),\r\nconcatenator:=',',\r\nfilter:=intersects($geometry, start_point(geometry(@parent))))\r\n",'OUTPUT':'TEMPORARY_OUTPUT'})

    DIST_CABLES = processing.run("native:fieldcalculator", 
    {'INPUT':DIST_CABLES['OUTPUT'],
    'FIELD_NAME':'DESTINO',
    'FIELD_TYPE':2,
    'FIELD_LENGTH':250,
    'FIELD_PRECISION':0,
    'FORMULA':"aggregate(\r\nlayer:= 'Points_Final',\r\naggregate:='concatenate',\r\nexpression:= to_string(ID),\r\nconcatenator:=',',\r\nfilter:=intersects($geometry, end_point(geometry(@parent))))\r\n",'OUTPUT':'TEMPORARY_OUTPUT'})

    DIST_CABLES = processing.run("native:addfieldtoattributestable", 
    {'INPUT':DIST_CABLES['OUTPUT'],
    'FIELD_NAME':'Label',
    'FIELD_TYPE':2,
    'FIELD_LENGTH':150,
    'FIELD_PRECISION':0,
    'OUTPUT':_temp_path+'Cable_Dist.shp'
    }) #########################
    vlayer = QgsVectorLayer(_temp_path+'Cable_Dist.shp', 'Cable_Dist', "ogr")
    prj.addMapLayer(vlayer, False)
    _tempGroup.addLayer(vlayer)

    #ADICIONA (others) CABLES AOS ALL_PT
    OTHR_CABLES = processing.run("native:mergevectorlayers", 
    {'LAYERS':[export_aCable_lyr, export_aDuct_lyr, export_fCable_lyr, export_dCables_lyr, export_dDucts_lyr],
    'CRS':QgsCoordinateReferenceSystem('EPSG:31370'),
    'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT})

    OTHR_CABLES = processing.run("native:fixgeometries", 
    {'INPUT':OTHR_CABLES['OUTPUT'],
    'OUTPUT':QgsProcessing.TEMPORARY_OUTPUT})

    OTHR_CABLES = processing.run("native:snapgeometries", 
    {'INPUT':OTHR_CABLES['OUTPUT'],
    'REFERENCE_LAYER':ALL_PT['OUTPUT'],
    'TOLERANCE':0.2,
    'BEHAVIOR':0,
    'OUTPUT':_temp_path+'Cable_others.shp'
    }) #########################
    vlayer = QgsVectorLayer(_temp_path+'Cable_others.shp', 'Cable_others', "ogr")
    prj.addMapLayer(vlayer, False)
    _tempGroup.addLayer(vlayer)

    _temp_othrCable_lyr = prj.mapLayersByName('Cable_others')[0]
    _temp_distCable_lyr = prj.mapLayersByName('Cable_Dist')[0]
    _temp_points_lyr = prj.mapLayersByName('Points_Final')[0]
  
    progression += 1 #jump
    progress.setValue(progression)
else:
    #progression = progression + 1 #jump
    print('[i1.3] - Fix Geometries skipped')

## 1.4 CREATE JOIN IN LAYER
    #gis.stackexchange.com/questions/133573/joining-table-field-with-shapefile-using-pyqgis
    #gis.stackexchange.com/questions/267732/joining-layers-with-pyqgis-3
if progression == 3:

    ### 1.4.1 remove info in origin lyrs
    toRemove = [export_ab_lyr, export_dp_lyr, export_dhh_lyr]
    for f_lyr in toRemove:
        for f in f_lyr.getFeatures():
            f_lyr.startEditing()
            f_lyr.deleteFeature(f.id())

    ### 1.4.2 GET INFO
    #ab
    copyByExp(_temp_points_lyr,export_ab_lyr,'\"layer\"= \'export - Aerial Box\'')
    #ClearSelection()

    #DP
    copyByExp(_temp_points_lyr,export_dp_lyr,'\"layer\"= \'export - DP\'')
    #ClearSelection()

    #D-HH
    copyByExp(_temp_points_lyr,export_dhh_lyr,'\"layer\"= \'export - D-HH\'')
    ClearSelection()

    ### 1.4.3 Get input (csv) and target (Shapefile) layers
    #shp=iface.activeLayer()
    #csv=iface.mapCanvas().layers()[0] #VER INDICE DO CAMPO OU TALVEZ BUSCAR POR NOME
    csvFiles = ["aerial_enclosures", "dhh_enclosures", "dp_enclosures"]
    joinTargets = ["export - DP", "export - Aerial Box"]
    joinList = [["aerial_enclosures", "dhh_enclosures", "dp_enclosures"], 
                ["export - DP", "export - Aerial Box"]] #[0]lyr - [1]target

    ### 1.4.4 Set properties for the join
    #DP
    shpField='Label'
    csvField='Label'
    joinObject = QgsVectorLayerJoinInfo()

    joinObject.setJoinFieldName(csvField)
    joinObject.setTargetFieldName(shpField)
    joinObject.setJoinLayerId(dp_enclosures_lyr.id())
    joinObject.setUsingMemoryCache(True)
    joinObject.setJoinLayer(dp_enclosures_lyr)
    export_dp_lyr.addJoin(joinObject)

    #AB
    shpField='Label'
    csvField='Label'
    joinObject = QgsVectorLayerJoinInfo()

    joinObject.setJoinFieldName(csvField)
    joinObject.setTargetFieldName(shpField)
    joinObject.setJoinLayerId(aerial_enclosures_lyr.id())
    joinObject.setUsingMemoryCache(True)
    joinObject.setJoinLayer(aerial_enclosures_lyr)
    export_ab_lyr.addJoin(joinObject)

    #DHH
    shpField='Label'
    csvField='Label'
    joinObject = QgsVectorLayerJoinInfo()

    joinObject.setJoinFieldName(csvField)
    joinObject.setTargetFieldName(shpField)
    joinObject.setJoinLayerId(dhh_enclosures_lyr.id())
    joinObject.setUsingMemoryCache(True)
    joinObject.setJoinLayer(dhh_enclosures_lyr)
    export_dhh_lyr.addJoin(joinObject)

    progression += 1 #jump
    progress.setValue(progression)
else:
    print('[i1.4] - Join in Layers skipped')

## 1.5 COPY INFO FROM EXP LYRS FOR EACH LAYER
    #opensourceoptions.com/blog/pyqgis-select-features-from-a-vector-layer/
if progression == 4:

    #joint lyrs
    #Pole Closure
    #copyByExp(source,target,exp)
    copyByExp(export_ab_lyr,poleClosure_lyr,'\"aerial_enclosures_Type\"= \'OFDC-A4\'')
    copyByExp(export_ab_lyr,poleClosure_lyr,'\"aerial_enclosures_Type\"= \'OFDC-B8G\'')
    #ClearSelection()

    #Facade Closure
    copyByExp(export_ab_lyr,facadeClosure_lyr,'\"aerial_enclosures_Type\"= \'Novux Closure\'')
    #ClearSelection()
   
    #DP
    #copyAll(source,target)
    copyAll(export_dp_lyr,dp_lyr)
    #ClearSelection()

    #DHH
    copyAll(export_dhh_lyr,dhh_lyr)
    ClearSelection()

    ############################
  
    #Distribution Cables
    copyAll(_temp_distCable_lyr,distCables_lyr)
    ClearSelection()

    ############################

    #Riser
    copyByExp(_temp_points_lyr,riser_lyr,'\"layer\"= \'export - Riser\'')
    #ClearSelection()

    #D-Ducts
    copyByExp(_temp_othrCable_lyr,dDucts_lyr,'\"layer\"= \'export - D-Duct\'')
    #ClearSelection()

    #Drop Cables
    copyByExp(_temp_othrCable_lyr,dropCable_lyr,'\"layer\"= \'export - A-Cable\'')
    #ClearSelection()

    #Paal
    copyAll(export_paal_lyr,paal_lyr)
    #ClearSelection()

    #Multifus
    copyByExp(_temp_othrCable_lyr,multFus_lyr,'\"layer\"= \'export - A-Duct\'')
    #ClearSelection()

    #CO
    copyByExp(_temp_points_lyr,co_lyr,'\"layer\"= \'export - CO\'')
    #ClearSelection()

    #BE
    copyByExp(_temp_points_lyr,be_lyr,'\"layer\"= \'export - BE\'')
    #ClearSelection()

    #Termination Box
    copyByExp(_temp_points_lyr,terminationBox_lyr,'\"layer\"= \'export - Termination Box\'')
    #ClearSelection()

    #fCable
    copyByExp(_temp_othrCable_lyr,feedCable_lyr,'\"layer\"= \'export - F-Cable\'')
    #ClearSelection()

    #HP
    copyByExp(_temp_points_lyr,hp_lyr,'\"layer\"= \'export - HP\'')
    #ClearSelection()

    #BK
    copyByExp(_temp_points_lyr,bk_lyr,'\"layer\"= \'export - Koppeling\'')
    ClearSelection()
     
    progression += 1 #jump
    progress.setValue(progression)
else:
    print('[i1.5] - Layer Copies skipped')


#2.0 EXPORT FOR .DXF
if progression == 5: #jump

    #2.1 Set Visible Layers
    
    layer_groups = ['Closures','Cables','Ducts','Cadastre', 'Basemaps']

    # 1. Turn on ALL groups
    for lyr_group in layer_groups:
        if lyr_group != None:
            myGroup = root.findGroup(lyr_group)
            myGroup.setItemVisibilityChecked(True) # True or False            
        else:
            myGroup = root.findGroup(lyr_group)
            myGroup.setItemVisibilityChecked(False) # True or False                
                
    # 2. Turn on ALL layers
    layers_names = [] #collect all layers names (even manually added lyrs)
    for layer in prj.mapLayers().values():
        layers_names.append(layer.name())
    for layer in layers_names: #turn all lyrs off
        lyr = prj.mapLayersByName(layer)[0]
        root.findLayer(lyr.id()).setItemVisibilityChecked(True)

    #2.2 Set exporter
        #gis.stackexchange.com/questions/269960/export-dxf-from-qgis-layer-using-pyqgis
    """
    fileName = prjTitle + '_dxfExport.dxf'
    crsID = "EPSG:31370 - BD72 / Belgian Lambert 72"
    crs = QgsCoordinateReferenceSystem("EPSG:31370")
    scale = 0.0021413276231263
    encoding = 'ISO-88859-1'

    #open or create a new file at the compiled file path (append (n) to the filename if there is already an existing file)
    x = 0
    while os.path.isfile (path_d): #returns true if a file exists #MODIFY
        x += 1
        #recompiles the new filename/path
        path_ = path_absolute + "/" + distance + "(" + str(x) + ")" + ".dxf" #MODIFY

    export_lyrs = []

    for layer in prj.mapLayers().values():
        if root.findLayer(layer.id()).isVisible():
            export_lyrs.append(layer)
            #print(layer) #debug

    #for layer in layers:
    #     filename = DirectoryName + "/" + layer.name() + ".dxf"    
    #     QgsVectorFileWriter.writeAsVectorFormat(layer, filename, "utf-8", layer.crs(), "DXF", 1)

    dxfExport = QgsDxfExport()
    settings = iface.mapCanvas().mapSettings()

    dxfExport.setMapSettings(settings)

    #dxfExport.addLayers([dxfExport.DxfLayer(export_lyrs)]) #'unexpected imput: list'
    #dxfExport.addLayers([dxfExport.DxfLayer(lyr_names)]) #gis.stackexchange.com/questions/420926/export-project-to-dxf-dialog-using-python
    dxfExport.addLayers([dxfExport.DxfLayer(lyr) for lyr in prj.mapLayers().values()]) #funciona mas exporta todas as lyers


    dxfExport.setSymbologyScale(scale)
    dxfExport.setSymbologyExport(3) #0/1/2
    #dxfExport.setLayerTitleAsName(-1)
    dxfExport.setDestinationCrs(crs)
    dxfExport.setForce2d(0)
    #dxfExport.setExtent(new_box)

    dxfFile = QFile(fileName)
    dxfExport.writeToFile( dxfFile, 'utf-8' )
    """
    progression += 1 #jump
    progress.setValue(progression)
    
else:
    print('[i2.0] - DXF Export skipped')


iface.messageBar().clearWidgets()

print('========================================')
print("--- END in %s seconds ---" % (time.time() - start_time))
print('========================================')`

**Comment by uclaros** [comment]
Any chance your template has some macro enabled?

**Comment by see7e** [comment]
> Any chance your template has some macro enabled?

![image](https://user-images.githubusercontent.com/15942792/216060220-85b4ecc6-4873-4f05-a26c-60ac17471d2b.png)

**Comment by uclaros** [comment]
_Project properties > Macros_ is what you should check

**Comment by see7e** [comment]
> _Project properties > Macros_ is what you should check

![image](https://user-images.githubusercontent.com/15942792/216064320-b724d951-fb6c-465d-ba85-d10aedd331cf.png)
