### ISSUE TITLE
Can't operate on vector or raster

### ISSUE THREAD

**Issue by Federicomorganti** [qgis/QGIS#51662]
### What is the bug or the crash?

I can't operate with vector or raster because the commands in the menu have disappeared. if i click on the raster menu for example it only displays the raster calculator and nothing more. Commands like merge, cut or extrapolate level curves are no longer displayed. The same issue is for the vector or any algorythim like r.watershed or r.outlet. So now i can only read information about the layers that are already present in a project but i can't create new ones. I've tried to reinstall the program but the issue is still there. The version i'm working on is 3.22.12
![Cattura](https://user-images.githubusercontent.com/124046897/215744104-983da009-7c77-441f-b651-0a83f5c2dbdd.JPG)

### Steps to reproduce the issue

Go to "raster" and you can see the commands are not there

### Versions

3.22.12

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Federicomorganti, please activate the Processing core plugin or create and use a new QGIS user profile.
