### ISSUE TITLE
Map tips image orientation

### ISSUE THREAD

**Issue by arthurtaute** [qgis/QGIS#51709]
### Feature description

When viewing a photo using point features and the "feature form", QGIS shows the correct image orientation.  
When viewing images as "raster image markers" for points the photos also show correctly and even adjust sizes depending on the photo size.
However, clicking on the icon and viewing the same photos in map tips the image is always shown as landscape regardless of its correct orientation. (QGIS 3.28.3).  This was reported some time ago in version 2 but does not appear to have remained an issue or been rectified.  
( I note that for my photos (Samsung S8 and Nikon Coolpix Camera), exiftool  also extracts with largest dimension as imagewidth and the smaller dimension as imageheight  although when querying the photo properties in windows the width and height look OK.)   
Can this please be fixed.  
Use of elements of the same code for both views?
![20230122_163838](https://user-images.githubusercontent.com/20870484/216246450-f72821e2-176a-43f4-be54-f8f853b8ea26.jpg)

**Comment by YoannQDQ** [comment]
Seems like an upstream issue to me. QWebView do not support the image-orientation: from-image css property

**Comment by arthurtaute** [comment]
Thanks Jorge, I would have thought there would have been a simple fix as
the rotation is correct when using the info viewer.
Thanks for your efforts
Arthur Taute
083 274 8885
38 Fairways Ave
Hermanus
7200
