### ISSUE TITLE
NOT STARTING QGIS 3.28.3 ON WIN 10

### ISSUE THREAD

**Issue by TheLordofGods** [qgis/QGIS#51717]
### What is the bug or the crash?

An error occurred during execution of following code:
fault_handler_file=open('C:/Users/amari/AppData/Local/Temp/qgis-python-crash-info-14588', 'wt')

PYTHON CRASH REPORT GENERATED. PLEASE HELP.

### Steps to reproduce the issue

fault_handler_file=open('C:/Users/amari/AppData/Local/Temp/qgis-python-crash-info-14588', 'wt')

### Versions

QGIS 3.28.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by m-kuhn** [comment]
Please provide exact steps, how to reproduce.
