### ISSUE TITLE
QGIS 3.16.16 keeps crashing when saving as qgz.file

### ISSUE THREAD

**Issue by ferraio** [qgis/QGIS#51716]
### What is the bug or the crash?

Crash ID: b8466c3767ca136d5e290ac0e7934860cc6946f1

Stack Trace

RtlpFreeHeapInternal :
RtlFreeHeap :
free :
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2032
CComActivator::DoCreateInstance immact.hxx:392
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.16-Hannover
QGIS code revision: f5778a89df
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Open QGIS 3.16.16
2. Open qgz.file, QGIS Version 3.14
3. Save as qgz.file > 3.16.16
4. QGIS crashes
5. See bug report
![screenshot_QGIS-crash_saving_as](https://user-images.githubusercontent.com/124284598/216381441-258e0be2-72e6-4303-937c-3d5d7696a326.jpg)

### Versions

QGIS-Version | 3.16.16-Hannover | QGIS-Codeversion | f5778a89df
-- | -- | -- | --
Kompiliert gegen Qt | 5.11.2 | Laufendes Qt | 5.11.2
Kompiliert mit GDAL/OGR | 3.1.4 | Läuft mit GDAL/OGR | 3.1.4
Kompiliert mit GEOS | 3.8.1-CAPI-1.13.3 | Läuft mit GEOS | 3.8.1-CAPI-1.13.3
Kompiliert mit SQLite | 3.29.0 | Läuft mit SQLite | 3.29.0
PostgreSQL-Client-Version | 11.5 | SpatiaLite-Version | 4.3.0
QWT-Version | 6.1.3 | QScintilla2-Version | 2.10.8
Kompiliert mit PROJ | 6.3.2 | Läuft mit PROJ | Rel. 6.3.2, May 1st, 2020
BS-Version | Windows 10 (10.0)
Aktive Python-Erweiterungen | qfieldsync; db_manager; MetaSearch; processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I tried it with a new QGIS profile. But I cannot open the file > crash.
Even QGIS 3.22, maybe later versions, don't work.
I used WIN7, but after the upgrade to WIN10 (Version 22H2 Build 19045.2546) by MediaCreationTool22H2 the bug occured.

**Comment by kannes** [comment]
QGIS 3.16 is not supported anymore, sorry. It got out of support more than one year ago.
