### ISSUE TITLE
Invalid digital signature for qgis-ltr-bin.exe 3.22.15

### ISSUE THREAD

**Issue by tomfid** [qgis/QGIS#51718]
### What is the bug or the crash?

A colleague just updated to 3.22.15, which is getting flagged by Norton AV for an invalid digital signature.
![image](https://user-images.githubusercontent.com/2151849/216478610-1856c91c-7d46-4fc9-90bd-f170750ab940.png)

We realize that this could be overzealous AV, but seems more likely it's a real signing issue arising from code or installer.

### Steps to reproduce the issue

Install from:
[https://www.qgis.org/en/site/forusers/alldownloads.html#osgeo4w-installer](https://www.qgis.org/en/site/forusers/alldownloads.html)
-using the link for “Download OSGeo4W Installer and start it”
-include QGIS LTR, GDAL, and GRASS GIS

On launch, Norton flags the exe when it accesses the network for newsfeed and version update checks. These can easily be turned off, but turning off plugin management (which also requires the network) is less convenient.

### Versions

QGIS version
3.22.15-Białowieża
QGIS code revision
ef17ad14
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009
Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@tomfid qgis-ltr-bin.exe from OSGeo4W does not have and never had a "digital signature".
qgis-ltr-bin.exe from latest OSGeo4W qgis-ltr 3.22.15-1 package has SHA-256 5f18673d6acd43501915c5371b41b159fdb91b19b11c15c07882e974acda8371 hash.
VirusTotal states that "No security vendors and no sandboxes flagged this file as malicious": https://www.virustotal.com/gui/file/5f18673d6acd43501915c5371b41b159fdb91b19b11c15c07882e974acda8371

Please contact your firewall customer care.
