### ISSUE TITLE
Broken layers when creating new table on GPKG created by third party

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#51721]
### What is the bug or the crash?

When I create a new vector layer on a GPKG created by a specific third party tool, all the other non-geometry-layers are broken when reopening the GPKG with QGIS (e.g. with drag and drop).

Same behavior when I import a table from another GPKG (with QGIS Browser) and when I create it via *Layer > Create Layer...*

**Reason**

When I create or import a layer an entry is added to the `gpkg_contents` table in the GeoPackage. Opening a GeoPackage works fine when:
a. all tables have an entry in `gpkg_contents`
b. only the spatial tables have an entry in `gpkg_contents`

But if only some non-geometry-layers have an entry in `gpkg_contents` all the other non-geometry-layers cannot be loaded by QGIS.

**I open this as an issue, since QGIS is the one having problems with this GeoPackage. But maybe the misbehavior is in the third party tool (ili2db). The documentation says:**
> The `gpkg_contents` table is intended to provide a list of all geospatial contents (i.e., entity stores) in a GeoPackage. (https://www.geopackage.org/spec/#_contents)

**And indeed the spatial tables cannot be used when they are missing here. But the non-geometry-tables can. Do all tables need to have an entry in `gpkg_contents`? If yes, why is it working for non-geometry tables anyway. If no, why does it QGIS and why is it not able to handle it when some have it and others not? Is this a QGIS issue or is this a missbehavior of the third-party**

### Steps to reproduce the issue

1. I create a GPKG "mostsimple.gpkg" according to an INTERLIS Model with ili2db (third party tool)
2. I have two tables in the GPKG:
    One with geometry:
    ```SQL
    CREATE TABLE building (
      T_Id INTEGER NOT NULL PRIMARY KEY
      ,T_Ili_Tid TEXT(200) NULL
      ,ageometry POINT NOT NULL
    )
    ```
    And one without geometry:
    ```SQL
    CREATE TABLE address (
      T_Id INTEGER NOT NULL PRIMARY KEY
      ,T_Ili_Tid TEXT(200) NULL
      ,street TEXT NULL
    )
    ```
    And I have *one* entry in the `gpkg_contents` table:
    ![image](https://user-images.githubusercontent.com/28384354/216548090-7fd0326c-ba92-4396-bdf8-83b891e13cde.png)
3. I copy the GPKG to "mostsimple_2.gpkg" to have both states.
4. I open it in QGIS and see both tables (and additional meta-tables):
    ![image](https://user-images.githubusercontent.com/28384354/216550018-416f1bd2-9316-4a1e-b86b-b987216ef5b3.png)
5. I create a new non-geometry-table:
    ![image](https://user-images.githubusercontent.com/28384354/216550306-1944d3b8-76a4-437b-9f9e-e2f83997e50f.png)
    Still everything is fine in the project.
6. I reopen the GPKG (drag it into QGIS): All other non-geometry-layers are broken.
    ![image](https://user-images.githubusercontent.com/28384354/216550620-204ef14f-b907-4aad-aa38-d6d62fbf87c6.png)

### Versions

QGIS-Version | 3.22.14-Białowieża | QGIS-Codeversion | 4cde646cf9
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.10.6
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | 14.5 (Ubuntu 14.5-0ubuntu0.22.04.1)
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Ubuntu 22.04.1 LTS

**As well as** 

QGIS-Version | 3.29.0-Master | QGIS-Codeversion | afe52bae78
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.10.6
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Ubuntu 22.04.1 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
What does ogrinfo report?

**Comment by signedav** [comment]
Before adding a layer with QGIS:
```
$ ogrinfo mostsimple.gpkg
INFO: Open of `mostsimple.gpkg'
      using driver `GPKG' successful.
1: building (Point)
2: address (None)
3: T_ILI2DB_BASKET (None)
4: T_ILI2DB_DATASET (None)
5: T_ILI2DB_INHERITANCE (None)
6: T_ILI2DB_SETTINGS (None)
7: T_ILI2DB_TRAFO (None)
8: T_ILI2DB_MODEL (None)
9: T_ILI2DB_CLASSNAME (None)
10: T_ILI2DB_ATTRNAME (None)
11: T_ILI2DB_COLUMN_PROP (None)
12: T_ILI2DB_TABLE_PROP (None)
13: T_KEY_OBJECT (None)
14: T_ILI2DB_META_ATTRS (None)
```

After adding a layer with QGIS:
```
$ ogrinfo mostsimple_2.gpkg
INFO: Open of `mostsimple_2.gpkg'
      using driver `GPKG' successful.
1: building (Point)
2: new_nongeometry_layer (None)
```

**Comment by nyalldawson** [comment]
What if you use ogr2ogr to add a new table? Do you see the same thing?

**Comment by signedav** [comment]
```
$ ogr2ogr -f GPKG -update mostsimple_3.gpkg ../no_ili/shapezeug/nogeom.dbf -nln nogeom_layer

$ ogrinfo mostsimple_3.gpkg
INFO: Open of `mostsimple_3.gpkg'
      using driver `GPKG' successful.
1: building (Point)
2: nogeom_layer (None)
```

Apparently ogr2ogr behaves like QGIS and adds an entry to the `gpkg_contents`.

**Comment by signedav** [comment]
As far as I understand the documentation it only says that "geospatial" data need to have an entry in the `gpkg_contents` table:
> The `gpkg_contents` table is intended to provide a list of all geospatial contents (i.e., entity stores) in a GeoPackage. (https://www.geopackage.org/spec/#_contents)

So it's hard to "blame" the third-party software ([ili2db](https://github.com/claeis/ili2db)) for not making entries there on non-geometry-tables.

What should be the approach for a sollution? Do you have an idea @rouault ?

**Comment by rouault** [comment]
GDAL fix in https://github.com/OSGeo/gdal/pull/7174

The issue is that before OGR creates layers, there are non-spatial layers which are not-registered as "attributes" layers (cf http://www.geopackage.org/spec130/#attributes) in gpkg_contents. On reading, the OGR GPKG driver has a heuristics:
- if it finds "attributes" layers registered in gpkg_contents, it only uses them
- otherwise it looks in sqlite_master for all tables
Before the above fix, on creation of non-spatial layers, OGR would always register them by default as "attributes" layers registered in gpkg_contents. So on re-opening, it would not see the ones that are not registered.

Various workarounds:
- on opening, set the LIST_ALL_TABLES=YES open option
- on layer creation of a non-spatial layer in such database that doesn't have attribute layers, use the ASPATIAL_VARIANT=NOT_REGISTERED layer creation option

**Comment by signedav** [comment]
@rouault Sorry this question. But with this fix, would QGIS be able to open this GPKG:
- Created with old QGIS (and OGR) : Created non-spatial tables (in gpkg_contents)
- Updated with new QGIS (and OGR) : Applied new non-spatial tables (not in gpkg_contents)
Since the heuristics would not cover that. Or is there a fix as well for that?

**Comment by rouault** [comment]
The fix I did is on the creation side, so if you have a database with part of the non-spatial tables registered in gpkg_contents and part not registered into it, by default, OGR will only see the ones registered. You have to use the LIST_ALL_TABLES=YES open option to see all of them

**Comment by signedav** [comment]
Sorry I still don't get it. Where do I need to set `LIST_ALL_TABLES=YES`? Do we need to implement that at default in QGIS?

My concern is, that when we use existing GPKG (where non-spatial tables are in gpkg_contents) and add new tables with QGIS (and they won't be in gpkg_contents), we will not be able to open it properly with drag-and-drop. Or am I missing something?

**Comment by rouault** [comment]
> Where do I need to set `LIST_ALL_TABLES=YES`?

Cf ``vl = QgsVectorLayer(filename + "|option:LIST_ALL_TABLES=YES", 'test', 'ogr')``

> My concern is, that when we use existing GPKG (where non-spatial tables are in gpkg_contents) and add new tables with QGIS (and they won't be in gpkg_contents after your fix), we will not be able anymore to open it properly with drag-and-drop. 

That should work with my fix (just test :-)) since it will either add non-spatial tables as attributes registered table if there are registered attributes table, or add them as non-registered if there are non-registered. What won't work properly without explicit LIST_ALL_TABLES=YES is if you edit a dataset with both attributes registered and non-registered

**Comment by signedav** [comment]
Ah okay. Thanks a lot. 

So the only use case that won't work is on already "broken" GeoPackages...

On what QGIS version do we expect the GDAL version with your fix?

**Comment by rouault** [comment]
> On what QGIS version do we expect the GDAL version with your fix?

It is mostly a policy decision of whoever packages them for you...
