### ISSUE TITLE
Help button does not open file:/// based url

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#51730]
### What is the bug or the crash?

Preferences menu --> Options --> General --> Documentation Paths
You can add many URLs to serve the documentation, and these are tested sequentially until a working URL is returned. People are supposed to add their in-house docs URL to use in this table.
When locally building the docs, html files are stored in a build folder and can be opened as e.g. `file:///path/to/the/docs/repo/folder/build/html/en/docs/user_manual/introduction/qgis_configuration.html`.
I add to the Documentation Paths table `file:///path/to/the/docs/repo/folder/build/html/en/docs/user_manual/` above the default `https://docs.qgis.org/$qgis_short_version/$qgis_locale/docs/user_manual/` but when I hit a Help button, only the official docs is returned. Checking the log message shows:
 > 2023-02-04T23:58:06     INFO    Trying to open help using key 'introduction/qgis_configuration.html'. Full URI is 'file:///path/to/the/docs/repo/folder/build/html/en/docs/user_manual/introduction/qgis_configuration.html'…
2023-02-04T23:58:06     INFO    Trying to open help using key 'introduction/qgis_configuration.html'. Full URI is 'https://docs.qgis.org/3.29/en/docs/user_manual/introduction/qgis_configuration.html'…

The file exists on my machine and I can open it in my browser.

### Steps to reproduce the issue

See above

### Versions

master 3.29 (ubuntu 22.04) and 3.28 (on macOS)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@DelazJ AFAIK you need to insert a normal path without the `file:///` part.

**Comment by DelazJ** [comment]
Great @agiudiceandrea . You are right. Thanks
