### ISSUE TITLE
Project predefined scales are trimmed at thousand separator after project restart/reopening properties

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#51735]
### What is the bug or the crash?

When the "_Show group (thousand) separator_" setting is active, project predefined scales are trimmed after reopening _project properties_ or reopening a project after restarting QGIS.

### Steps to reproduce the issue

Make sure the setting 'Show group (thousand) separator' is enabled in _General_ tab of QGIS settings.
1. (Re-)Start QGIS
2. Create a new empty project
3. Open the project properties
4. Enable project predefined scales
5. Add new scales, apply and/or hit _OK_  --> Predefined scales now selectable for canvas
7. Reopen the project properties --> The scales now show the thousand separator
8. Close the project properties again --> Predefined scales are now trimmed at the thousand separator

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.3-Firenze | QGIS code revision | c12bcb2f76c
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://user-images.githubusercontent.com/78353871/216823281-879006cb-18b0-4663-b91c-41898e05df05.mp4

**Comment by elpaso** [comment]
@mblesius can you share your locale configuration from General tab of QGIS settings?

**Comment by mblesius** [comment]
![grafik](https://user-images.githubusercontent.com/78353871/216924662-4aaf546f-f3d4-447e-a4b6-3fc493f5a3f9.png)
