### ISSUE TITLE
Output of Algorithm jumps top left when moving

### ISSUE THREAD

**Issue by widmerc** [qgis/QGIS#51757]
### What is the bug or the crash?

Hi,

I have noticed, that if I create a new output of a algorithm (see video below), and try to move it a bit, the box of the output will move to the top left. This is quite frustrating, if you have a lot of outputs.

https://user-images.githubusercontent.com/92168021/217021595-8a93e5d1-ac0d-4007-9bff-93861b22e012.mp4

### Steps to reproduce the issue

You can reproduct this step if you add a new algorithm, and create a new output. Then if you try to move the box, it jumps to the top left. (see Video). IT IS IN ALL QGIS VERSIONS.

### Versions

QGIS-Version | 3.28.2-Firenze | QGIS-Codeversion | b47e00ba601
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.6.1
PROJ-Version | 9.1.1
EPSG-Registraturdatenbankversion | v10.076 (2022-08-31)
GEOS-Version | 3.11.1-CAPI-1.17.1
SQLite-Version | 3.39.4
PDAL-Version | 2.4.3
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
HCMGIS | 22.9.9
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
Qgis2threejs | 2.7.1
QuickOSM | 2.1.1
swissbuildings3d_loader | 0.1
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by wsonnekus** [comment]
I am not sure if this is needed: but i can confirm i have seen this as well in V3.30. 
thank you.

**Comment by widmerc** [comment]
Thank you for fixing this bug 💯
