### ISSUE TITLE
Layer WFS-T: HTTPS protocol

### ISSUE THREAD

**Issue by dvieira82** [qgis/QGIS#51751]
### What is the bug or the crash?

When we define a URL for a layer with HTTPS protocol, all POST requests to save the changes, ignore the protocol of the URL.
Ex:
Url WFS layer: **https**://mysite/geoserver/workspace/wfs
**POST request**: **http:**//mysite/geoserver/workspace/wfs

### Steps to reproduce the issue

1. Install QGIS Network Logger plugin
2. Add a Layer WFS
3. QGIS Network Logger show the GET requests with correct protocol
4. Make changes in layer
5. Save changes
6. QGIS Network Logger show the POST requests with wrong protocol

### Versions

Versão do QGIS
3.26.1-Buenos Aires
Revisão do código do QGIS
b609df9ed4d
Qt version
5.15.3
Versão do Python
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
Versão PDAL
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
Versão QScintilla2
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@dvieira82 QGIS 3.26 is no longer supported. Could you try if the issue does also occur using the latest currently supported QGIS version according to the QGIS roadmap? Could you share the WFS server capabilities?

**Comment by agiudiceandrea** [comment]
@rupestre-campos, QGIS 3.38 is no longer supported. Please try if the issue still occurs also running a currentrly supported QGIS version and a new QGIS user profile. If it does, I think it would be better if you opened a new Issue Report providing alla the requested info and all the needed info and step-by-step instructions in order to replicate the issue.

**Comment by rupestre-campos** [comment]
yeah just tested with QGIS 3.40.3 bratislava in a new user profile and indeed the same error. I will create a new issue as suggested with requested info. Thanks for guidance!
