### ISSUE TITLE
Simple line symbol layer with offset is missing parts

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#51750]
### What is the bug or the crash?

Simple line symbol layer with offset is missing parts:

![grafik](https://user-images.githubusercontent.com/20856381/216957347-17c9b21f-4302-45ae-b0bf-5172f8888d82.png)

### Steps to reproduce the issue

1. Open test layer from GPKG with default style: [test.zip](https://github.com/qgis/QGIS/files/10662412/test.zip)
2. See error: Part of the yellow dashed line is missing

### Versions

Artifact from MinGW64 Windows build (https://github.com/qgis/QGIS/commit/d0a9f1249448c5dbde370052852220179df1ee8f)

https://github.com/qgis/QGIS/suites/10798239191/artifacts/543108183

QGIS version | 3.29.0-Master | QGIS code branch | master
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.36.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.0
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

1. Can't reproduce with master on Ubuntu.
2. If the offset is turned off, there is no issue:
![grafik](https://user-images.githubusercontent.com/20856381/216958999-421ce709-bff0-49d8-8594-9d4a55bae3f3.png)
3. Sometime, if the line is not fully visible on the canvas, there is no issue:
![grafik](https://user-images.githubusercontent.com/20856381/216959273-20c37b7a-a4eb-4ab5-a409-8035209e7be9.png)

**Comment by DelazJ** [comment]
@pathmapper duplicate of #51583?

**Comment by pathmapper** [comment]
@DelazJ thanks, seems to be the same issue.

**Comment by dr-jts** [comment]
This issue is actually due to a bug in the JTS/GEOS OffsetCurve functionality.  It is reported as https://github.com/locationtech/jts/issues/957. It will be fixed in JTS as part of https://github.com/locationtech/jts/pull/956, and will be ported to GEOS after that.
