### ISSUE TITLE
Label properties dont work in Label Bar.

### ISSUE THREAD

**Issue by eflaten** [qgis/QGIS#51760]
### What is the bug or the crash?

When I select a feature to edit the text size I get the error: 
"Change Label: Cannot change “Trossetstranda” — the layer “N50_Stedsnavn_tekstplassering” could not be made editable"
The other buttons work like. swich on/off, rotate, move.

The files I edit on is a FGDB from Norwegian Mapping Office, and has a product description attached under. 
[Produktspesifikasjoner_N50 Kartdata_v15_produktspesifikasjon-kartverket-n50kartdata-versjon20170401_.pdf](https://github.com/qgis/QGIS/files/10669678/Produktspesifikasjoner_N50.Kartdata_v15_produktspesifikasjon-kartverket-n50kartdata-versjon20170401_.pdf)

### Steps to reproduce the issue

The layer withe feature i want to edit is selected.

1. click and select a feature
2. click ob the lable tool "Change lable properties"
3. Then the error described over appears.

### Versions

QGIS version | 3.28.3-Firenze | QGIS code revision | 9ae208a46d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.2
  |   |   |  
Active Python plugins
OnlineRoutingMapper | 0.9
beePen | 0.2.4
batch_gps_importer | version 1.0.1
wfsclient | 0.9.11
qgis2web | 3.16.0
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.28.3-Firenze
QGIS code revision
[9ae208a46d](https://github.com/qgis/QGIS/commit/9ae208a46d)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.2

Active Python plugins
OnlineRoutingMapper
0.9
beePen
0.2.4
batch_gps_importer
version 1.0.1
wfsclient
0.9.11
qgis2web
3.16.0
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Do you have the text size bound to a field in the table? If so, you'll need a QGIS build with a more recent GDAL version to have edit support for ESRI File Geodatabases.

**Comment by eflaten** [comment]
I thinks so. I am beginner in qgis and gis so it amateur hour her...But under is  the rows of this feature in the attribute table:

wkt_geom | OBJECTID | FeatureID | ZOrder | AnnotationClassID | Element | SymbolID | Status | TextString | FontName | FontSize | Bold | Italic | Underline | VerticalAlignment | HorizontalAlignment | XOffset | YOffset | Angle | FontLeading | WordSpacing | CharacterWidth | CharacterSpacing | FlipAngle | Override | SHAPE_Length | SHAPE_Area | objtype | streng | oppdateringsdato | datafangstdato | tegnavstand | skrifttype | referansemalestokk | fulltekst | teksttype | tekstreferansepunktnord | tekstreferansepunktost | skriftkode | stedsnavnsnummer | stedsnummer | skrivematenummer | navneobjekthovedgruppe | navneobjektgruppe | navneobjekttype | sprak | sprakprioritering | auxiliary_storage_labeling_positionx | auxiliary_storage_labeling_positiony | auxiliary_storage_labeling_show | auxiliary_storage_labeling_labelrotation | auxiliary_storage_labeling_family | auxiliary_storage_labeling_fontstyle | auxiliary_storage_labeling_size | auxiliary_storage_labeling_bold | auxiliary_storage_labeling_italic | auxiliary_storage_labeling_underline | auxiliary_storage_labeling_color | auxiliary_storage_labeling_strikeout | auxiliary_storage_labeling_multilinealignment | auxiliary_storage_labeling_buffersize | auxiliary_storage_labeling_buffercolor | auxiliary_storage_labeling_bufferdraw | auxiliary_storage_labeling_labeldistance | auxiliary_storage_labeling_hali | auxiliary_storage_labeling_vali | auxiliary_storage_labeling_scalevisibility | auxiliary_storage_labeling_minscale | auxiliary_storage_labeling_maxscale | auxiliary_storage_labeling_alwaysshow | auxiliary_storage_labeling_calloutdraw | auxiliary_storage_labeling_labelallparts
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
MultiPolygon (((576673.8584000002592802 6777037.77370000071823597, 576670.97850000020116568 6777170.75799999944865704, 577456.03880000021308661 6777187.75899999961256981, 577458.91860000044107437 6777054.77480000071227551, 576673.8584000002592802 6777037.77370000071823597))) | 49665 | -1 | 0 | -1 |  | -1 | 0 | Trossetstranda | Arial | 6.**75 |** 0 | 1 | 0 | 2 | 0 | 0 | 0 | 1.243069305099067 | 0 | 100 | 100 | 0 | 0 | 0 | 1836.519484419475 | 104449.60902399053 | StedsnavnTekst | Trossetstranda | 2021-11-11T00:00:00.000 | 1000-01-01T00:00:00.000 | 0 | Arial | 50000 | Trossetstranda |   | 0 | 0 | 215 | 1 | 493816 | 1 | 3000 | 3200 | 3207 | nor |   | 576951.4778132817 | 6777104.998581622 | 1 | 0.46457077619413667 |   |   | 0 | 0 | 0 | 0 |   | 0 |   | 0 |   | 0 | 0 |   |   | 0 | 0 | 0 | 0 | 0 | 0

**Comment by eflaten** [comment]
And thanks for getting back on this.

**Comment by nyalldawson** [comment]
@eflaten 

You need to check what field this setting is set to:

![image](https://user-images.githubusercontent.com/1829991/217106691-6c518d46-0060-44b0-b57f-7472b2b6a89b.png)

**Comment by eflaten** [comment]
The field is set to "auxiliary_storage_labeling_size". By the way if I change size here, the size of all place names are changed. 
<img width="2355" alt="Skjermbilde 2023-02-07 kl  09 00 16" src="https://user-images.githubusercontent.com/2272468/217189544-3dc1aab6-9406-49e4-8aaf-dc40d2038d50.png">

**Comment by eflaten** [comment]
@nyalldawson I guess the function label size, and possible others, can't write to the eauxiliary storage. And that maybe is because the GDAL piece inside qgis is outdated. So maybe th e qgis team should replace the GDAL part? If thats causing the problem.

**Comment by eflaten** [comment]
@qgis-bot Yes its stalled. I guess the gdal component must be updated, but I am not shure.
