### ISSUE TITLE
Add Dynamic Text -> Scale on layout not inserting correct scale

### ISSUE THREAD

**Issue by g-terziev** [qgis/QGIS#51764]
### What is the bug or the crash?

When I try to add dynamic scale text on my layout, it is not working properly.

Instead of inserting the correct scale, it inserts the scale with .99999999. Please look the attached pic. The map has a scale of 
4 000 000, and when I try to add the scale using the add dynamic text scale function it inserts the scale as 3 999 999.9999999.

Please fix this issue asap, I need this option in order to create and export layouts for my work !!

Thanks in advance

![image](https://user-images.githubusercontent.com/117976490/217192908-45f70f2d-7ecc-4361-9e50-349ca9a90905.png)

### Steps to reproduce the issue

![not correct scale](https://user-images.githubusercontent.com/117976490/217193747-60444e0f-32a6-40b6-918e-581a898449ff.png)

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
flurstuecksfinder-nrw
1.3.0
kmltools
3.1.27
latlontools
3.6.7
mmqgis
2021.9.10
OpenTopography-DEM-Downloader
1.0
profiletool
4.2.2
QuickOSM
2.1.1
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> Please fix this issue asap, I need this option in order to create and export layouts for my work !!

For your record, devs hate to see this. If you need an urgent fix that is critical for your work, talk to your employer so he can contract a developer to fix it.

In the mean time, the workaround is pretty simple.
![image](https://user-images.githubusercontent.com/39594821/217199227-be5282b6-5fd6-46be-af4c-bda24a2658bb.png)
`[%item_variables('Carte 1')['map_scale']%]`

![image](https://user-images.githubusercontent.com/39594821/217199311-cd6359a1-bede-4a11-8435-a2e9e3800f5b.png)
`[%round(item_variables('Carte 1')['map_scale'])%]`

Use `round()` function.

**Comment by g-terziev** [comment]
Thanks a lot @nicogodet. Thanks for the quick reply and help. It is working. Sorry for using the word asap, I didn't know that the devs are annoyed with this word.
I was quite asking myself, why this issue is happening over and over again, even after a three updates in a row for QGIS 3.28.x. Thanks again, but also keep in mind that these basic thing are really crucial and important to every day user.

**Comment by nicogodet** [comment]
> I was quite asking myself, why this issue is happening over and over again, even after a three updates in a row for QGIS 3.28.x.

If it wasn't reported before, it can not be fixed :)

**Comment by uclaros** [comment]
This was a duplicate of #45877
