### ISSUE TITLE
Vector map rendering 3d buildings only half of screen.

### ISSUE THREAD

**Issue by Adarsh-Ash** [qgis/QGIS#51781]
### What is the bug or the crash?

we used google maps api to render 3d maps in our application. Map was working fine initially. But now we see only half scree the 3d models in map comes. other half will be plane map. the sample program given in google maps also showing only half maps, initially it was rendering whole screen. i have attached the screen shots of sample examples given by google only

### Steps to reproduce the issue

<img width="413" alt="image" src="https://user-images.githubusercontent.com/54153477/217784842-f92ef030-cdf8-4d3b-a2eb-41d61931655f.png">

### Versions

<img width="413" alt="image" src="https://user-images.githubusercontent.com/54153477/217785119-d57cdcba-846b-43b5-b95f-23d6ef7411e9.png">

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by Adarsh-Ash** [comment]
https://developers.google.com/maps/documentation/javascript/examples/webgl/threejs-overlay-simple this link i am referring to.

**Comment by nicogodet** [comment]
Can you file all necessary info requested in issue form ?
(QGIS version, OS, are you up-to-date ? did you try with a new qgis user profile ?)

**Comment by uclaros** [comment]
Could you also clarify why this is related to QGIS?
