### ISSUE TITLE
Polygon geometry generator fails if a vertex isn't visible

### ISSUE THREAD

**Issue by Jean-Roc** [qgis/QGIS#51796]
### What is the bug or the crash?

Hi,

When using a geometry generator on a LineStringZ layer to produce a visual polygon, it seems that only the vertices inside the active canvas are used. If one vertex is outside, QGIS tries to generate the output symbology with the remaining ones, leading to erroneous geometries.

We tried several versions
- 3.24.2, it works as intended
- 3.26.1, no display at all
- 3.28.2 and >, it shows the issue

Expected result when all the vertices are shown :

![qgis_bug_geometry_generator_before](https://user-images.githubusercontent.com/736212/218065358-10491c25-6aec-47cd-9490-7c0619a68ded.jpg)

Result when one vertex is outside :

![qgis_bug_geometry_generator_after](https://user-images.githubusercontent.com/736212/218065354-9b22f8a4-2b7a-470e-9b93-cb589c5abf92.jpg)

The formula :

``` SQL
CASE 
	WHEN OFFSET_LEFT IS NOT NULL 
	THEN single_sided_buffer( 
			$geometry,
			OFFSET_LEFT * -1 / 100, 1, 2
			)
	ELSE single_sided_buffer( 
			$geometry,
			OFFSET_RIGHT* -1 / 100, 1, 2
			)
	END
```

Here is a sample gpkg with a default style showcasing the issue :
[qgis_geom_generator.zip](https://github.com/qgis/QGIS/files/10706212/qgis_geom_generator.zip)

regards,
jean-roc

### Steps to reproduce the issue

1. load the sample gpkg
2. move the canvas to hide a corner of the geometry

### Versions

QGIS 3.28.3-Firenze c12bcb2f76c
Windows 11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Is it the same issue as https://github.com/qgis/QGIS/issues/38579 ?

**Comment by Jean-Roc** [comment]
Hi, thanks for the pointer, I would say not quite as it is about a lack of generated geometry when the objet is fully outside the rendering view while here it is partially. This usecase was working in 3.24, even if partially out of canvas, the whole object was used to generate the buffer.

![qgis_bug_geometry_generator_324](https://user-images.githubusercontent.com/736212/218123698-52998f62-6b7b-40c0-b8ff-66bb164069c2.jpg)

There is no need here to evaluate all the objects that could be used outside the rendering canvas with a buffer but only the ones already requiered.

**Comment by agiudiceandrea** [comment]
The issue occurs with the single_sided_buffer() function in the geometry generator if the layer is a (Multi)LineStringZ, but not if the layer is a (Multi)LineString.

The issue does occur with QGIS 3.28.3 while it doesn't occur with QGIS 3.22 or QGIS 3.16.

The cause of this issue may be similar to that of https://github.com/qgis/QGIS/issues/49310 and https://github.com/qgis/QGIS/issues/50510.
