### ISSUE TITLE
Key/Value expression constraint is not updated

### ISSUE THREAD

**Issue by valttlapp** [qgis/QGIS#51791]
### What is the bug or the crash?

I have a layer with a JSON field. The JSON field has the following expression constraint:
```
CASE
	WHEN json_field IS NULL
		THEN true
	WHEN
	((map_get(json_field, 'fin') IS NOT NULL AND
		map_get(json_field, 'fin') != '') OR
	NOT map_exist(json_field, 'fin')) AND
	((map_get(json_field, 'swe') IS NOT NULL AND
		map_get(json_field, 'swe') != '') OR
	NOT map_exist(json_field, 'swe'))
		THEN true
ELSE FALSE
END
```
It also has a default value of `from_json('{"fin": "", "swe": ""}')`

When default values are removed from the form, qgis says that the field is invalid despite the fact that it should. When I add new empty key/value pair and delete it, the form becomes valid. See the video:

https://user-images.githubusercontent.com/106655208/218023956-9c27a4ad-066f-4797-9320-52f259c004b7.mp4

### Steps to reproduce the issue

See above.
Here's example project:
[json_bug.zip](https://github.com/qgis/QGIS/files/10704517/json_bug.zip)

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Tieosoitetyokalu
1.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
When you remove the last row an empty map (key value pair dictionary) remains, which is not NULL.

A working expression would be something like: 


```sql
CASE
	WHEN (json_field IS NULL OR array_length( map_akeys( json_field ) ) = 0) 
		THEN true
	WHEN
	((map_get(json_field, 'fin') IS NOT NULL AND
		map_get(json_field, 'fin') != '') OR
	NOT map_exist(json_field, 'fin')) AND
	((map_get(json_field, 'swe') IS NOT NULL AND
		map_get(json_field, 'swe') != '') OR
	NOT map_exist(json_field, 'swe'))
		THEN true
ELSE FALSE
END
```

But there is another issue which does not trigger the constraints check when a row is removed, I'm searching for a fix to this problem.
