### ISSUE TITLE
Color ramp not showing properly

### ISSUE THREAD

**Issue by Afhaim** [qgis/QGIS#51802]
### What is the bug or the crash?

In my QGIS LTR ver 3.22.14, all the intermediate color values are set to null in my color ramps, so it will show the top few values on either end of the min/max line, but not in the middle ranges and draws as transparent.

![image](https://user-images.githubusercontent.com/125044492/218117933-9440773c-4334-4cc4-b51c-859cbd267c6f.png)

![image](https://user-images.githubusercontent.com/125044492/218118608-c5c21a3c-c029-4e28-b844-aba72dcb5b6f.png)

### Steps to reproduce the issue

Color ramp options in symbology window

### Versions

QGIS version
3.22.14-Białowieża
QGIS code revision
4cde646c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
QuickOSM
2.1.1
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
They are not null, just that the transparency is taken into account. I also have that issue when working with different version, do you only have this version of QGIS installed locally?

**Comment by nicogodet** [comment]
Could you try with a new profile too ?

**Comment by JoPiMu** [comment]
Same happens to me lately. I use to work with a USB stick with my projects (and folders) and usually changing PC, but the QGIS versions are the same (usually 3.22.x).

![image](https://user-images.githubusercontent.com/126670476/222118815-f22d1242-9b0f-4c29-98ba-51345a8ea70a.png)

**Comment by KatyaJTN** [comment]
![image](https://github.com/qgis/QGIS/assets/140043367/0fded94c-ffad-4c33-96a5-6b9ed7bb9199)
Hi, I still can't solve this problem, I have tried several versions of qgis, but the error persists.

**Comment by pointi12** [comment]
Possible workaround: https://gis.stackexchange.com/questions/439784/color-ramps-in-qgis-has-transparency-by-default

**Comment by wanderam** [comment]
Hi, all.

Following @nicogodet's suggestion, I solved this bug just by creating a new profile.
QGIS version 3.22.9
OS version Windows 10
