### ISSUE TITLE
QGIS crashs when I try to cut a line

### ISSUE THREAD

**Issue by poudou99** [qgis/QGIS#51815]
### What is the bug or the crash?

QGIS crashs when I try to cut a line using tool "separate entity"

I never had this problem before yesterday, now QGIS crashes after clicking the right mouse button to mark the end of the dotted line of cut

I wanted to cut a line so I have used to "separate entity" tool for this action. I 
![Crash QGIS](https://user-images.githubusercontent.com/125127283/218254961-b08e04d2-df42-4286-8ca5-a73314ebd07c.png)

### Steps to reproduce the issue

1. I select the line to cut
2. I enter in edit mode
3. I click close to the line to cut
4. I drag the mouse to the other side of the line to cut
5. I click on the right mouse button

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.28.3-Firenze | Révision du code | c12bcb2f76c
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.6.2
Version de Proj | 9.1.1
Version de la base de données du registre EPSG | v10.076 (2022-08-31)
Version de GEOS | 3.11.1-CAPI-1.17.1
Version de SQLite | 3.39.4
Version de PDAL | 2.4.3
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
mask | 1.10.2
openlayers_plugin | 2.0.0
OSMDownloader | 1.0.3
PeliasGeocoding | 0.1
quick_map_services | 0.19.33
SpreadsheetLayers | 2.0.1
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.28.3-Firenze
Révision du code
[c12bcb2f76c](https://github.com/qgis/QGIS/commit/c12bcb2f76c)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
mask
1.10.2
openlayers_plugin
2.0.0
OSMDownloader
1.0.3
PeliasGeocoding
0.1
quick_map_services
0.19.33
SpreadsheetLayers
2.0.1
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by poudou99** [comment]
REPORT DETAILS

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000015bc (most recent call first):



Stack Trace


QgsGeos::linePointDifference :
QgsGeos::splitGeometry :
QgsGeometry::splitGeometry :
QgsGeometry::splitGeometry :
QgsVectorLayerEditUtils::splitFeatures :
QgsVectorLayer::splitFeatures :
QgsMapToolSplitFeatures::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :



QGIS Info
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by roya0045** [comment]
Duplicate and should be fixed by https://github.com/qgis/QGIS/pull/51797 I assume

**Comment by agiudiceandrea** [comment]
@poudou99 is the issue that occurs in your system the same as #51501 and #50948? If not, what are the differences? Could you please actually check if the issue does occur also using a new QGIS user profile without any non core plugin installed? Does the issue occur for every layer? Could you share a very sample layer in order to replicate the issue?

**Comment by poudou99** [comment]
> @poudou99 is the issue that occurs in your system the same as #51501 and #50948? If not, what are the differences? Could you please actually check if the issue does occur also using a new QGIS user profile without any non core plugin installed? Does the issue occur for every layer? Could you share a very sample layer in order to replicate the issue?

Hi @agiudiceandrea 

I'm not sure that issues #51501 and #50948 are same as the mine. I use tool "Separate entity" (in french : "sépararer les entités")  
![image](https://user-images.githubusercontent.com/125127283/218260702-918d7ef1-f2cc-4a42-a1a9-2e1902965073.png)
Not tool "split line by point"  (I don't know if this one is the same in french version).
I've tried to use a new profile. Same issue.

I have created a small version of my .qgz project but I don't know how I can share it here (file type not supported)

**Comment by agiudiceandrea** [comment]
@poudou99, just zip it with the needed layer and attach the zip file.

**Comment by agiudiceandrea** [comment]
@poudou99 the tool you are using is "[Split Features](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#split-features)" / "[Séparer les entités](https://docs.qgis.org/3.22/fr/docs/user_manual/working_with_vector/editing_geometry_attributes.html#split-features)" which is the same used in previously reported bug https://github.com/qgis/QGIS/issues/51501 that will be allegedly fixed by https://github.com/qgis/QGIS/pull/51797.

**Comment by poudou99** [comment]
> @poudou99, just zip it with the needed layer and attach the zip file.
Yes indeed
[QGIS - Crash - Poudou99 - V2.zip](https://github.com/qgis/QGIS/files/10713817/QGIS.-.Crash.-.Poudou99.-.V2.zip)

Try to cut the purple line, just below the the intersection with the dotted red line
![Crash QGIS V2](https://user-images.githubusercontent.com/125127283/218262458-e435fbdc-dd35-4861-b474-c63530489441.png)

**Comment by poudou99** [comment]
> @poudou99 the tool you are using is "[Split Features](https://docs.qgis.org/3.22/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#split-features)" / "[Séparer les entités](https://docs.qgis.org/3.22/fr/docs/user_manual/working_with_vector/editing_geometry_attributes.html#split-features)" which is the same used in previously reported bug #51501 that will be allegedly fixed by #51797.

OK. So should be the same

**Comment by agiudiceandrea** [comment]
@poudou99 the provided zip file doesn't contain the affected layer, only a project file. Please attach the missing layer files.

**Comment by poudou99** [comment]
> @poudou99 the provided zip file doesn't contain the affected layer, only a project file. Please attach the missing layer files.

Oups. I'm sorry
here it is
[Bug.zip](https://github.com/qgis/QGIS/files/10716306/Bug.zip)

**Comment by uclaros** [comment]
While the crash is fixed in #51797, this report exposed another bug:
The split tool goes through the splitting logic when right clicking, regardless of the number of digitized points on the rubberband, while it should exit early if there are not enough points, similarly to how other digitizing tools operate.
I can address this on a separate PR.
