### ISSUE TITLE
Interpolated line wizard doesn't allow to set Max. width more than 99.

### ISSUE THREAD

**Issue by serg-bloim** [qgis/QGIS#51817]
### What is the bug or the crash?

Interpolated line wizard doesn't allow to set Max. width more than 99. If may be not enough when using units of type `Meters at Scale`. In my case I'm trying to create an interpolated line for a river which width is 1000m. But due to the limitation I cannot enter `1000`.

### Steps to reproduce the issue

Open `Style Manager` -> Create/modify a line style -> change `Symbol layer type to `Interpolated Line`-> Set Stroke Width with Varying Width -> Try to set Max.width to smth higher than 100.

### Versions

```
QGIS version | 3.28.3-Firenze | QGIS code revision | 9ae208a46d
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.0
  |   |   |  
Active Python plugins
QuickOSM | 2.1.1
osminfo | 0.7.1
quick_map_services | 0.19.33
nominatim | 1.4.5
latlontools | 3.6.8
OpenTopography-DEM-Downloader | 1.0
OSMDownloader | 1.0.3
MemoryLayerSaver | 4.0.4
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
```

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by serg-bloim** [comment]
BTW, It wasn't really clear to me what it means to `Try with a new Qgis profile`. I didn't find what are those profiles and assumed a new project is meant.

**Comment by roya0045** [comment]
99.99 is the default value, I made a PR to increase the max value, I guess it should be enough for a scale based render with the proposed change.

**Comment by serg-bloim** [comment]
Thanks! I hope your PR will get merged soon.
