### ISSUE TITLE
Transforming coordinates are in scientific exp syntax and cause inexact georeferencing

### ISSUE THREAD

**Issue by mmokrejs** [qgis/QGIS#51813]
### What is the bug or the crash?

Hi,
  if you try to georeference an ortho image in EPSG:5514 (both X and Y values are negative in our area) and ask QGIS to _Generate GDAL script_, you may get:

```
gdal_translate -of GTiff -gcp 1358.25 24602.9 -563286 -1.0521e+06 -gcp 1820.85 24201.4 -563231 -1.05204e+06 -gcp 2104.49 24300 -563198 -1.05205e+06 -gcp 2157.88 24564.8 -563193 -1.05208e+06 -gcp 2178.41 24029.5 -563188 -1.05202e+06 -gcp 1425.22 23062.2 -563272 -1.05192e+06 -gcp 1672.73 22818 -563243 -1.05188e+06 -gcp 3485.46 20027.3 -563043 -1.05157e+06 -gcp 3512.83 19999.9 -563040 -1.05157e+06 -gcp 4552.92 19300.7 -562931 -1.05149e+06 -gcp 5459.57 19101.9 -562831 -1.05147e+06 -gcp 5716.75 17784.3 -562805 -1.05133e+06 -gcp 5713.33 17836.6 -562805 -1.05133e+06 -gcp 6655.37 17348.7 -562704 -1.05128e+06 -gcp 7126.93 16833.3 -562654 -1.05122e+06 -gcp 7116.29 16833.3 -562655 -1.05122e+06 -gcp 7105.05 16830.5 -562656 -1.05122e+06 -gcp 7085.93 16836.8 -562658 -1.05122e+06 -gcp 6489.47 15898.7 -562724 -1.05112e+06 -gcp 6525.93 15870.8 -562720 -1.05112e+06 -gcp 3301.14 17769.6 -563076 -1.05134e+06 -gcp 3328.54 17746.6 -563073 -1.05134e+06 -gcp 3828.01 15075.7 -563017 -1.05104e+06 -gcp 3892.8 15060.4 -563010 -1.05104e+06 -gcp 4973.78 15306.8 -562891 -1.05106e+06 -gcp 3275.83 13951.9 -563078 -1.05092e+06 -gcp 1437.31 14976.6 -563289 -1.05104e+06 -gcp 1438.52 13505.9 -563291 -1.05087e+06 -gcp 2160.18 12721.8 -563210 -1.05079e+06 -gcp 2173.09 12324 -563209 -1.05074e+06 -gcp 2169.75 12307 -563210 -1.05074e+06 -gcp 930.139 17117.9 -563353 -1.05128e+06 -gcp 933.958 17038.2 -563352 -1.05127e+06 -gcp 1131.21 17434.9 -563331 -1.05131e+06 -gcp 5959.82 18648.6 -562778 -1.05142e+06 -gcp 5966.56 18584.1 -562777 -1.05141e+06 -gcp 6553.36 18007.4 -562714 -1.05135e+06 -gcp 3044.76 20179 -563091 -1.05159e+06 -gcp 5465.87 19075.9 -562830 -1.05147e+06 "somefile.nocoords.bmp" "/tmp/somefile.nocoords.bmp"
```
If want to keep the values as I entered them or collected from the reference image. This introduces and anwanted error and it impossible to backtrack if I entered the reference points correctly. Maybe related to bug #51792?

![screenshot_of_tiff2bmp_converted_image_georeferencing_TPS_non_scientific_math_syntax](https://user-images.githubusercontent.com/3297852/218249050-c8141533-b254-45bf-9a3c-c1799fc894a2.jpg)

```
QGIS version | 3.28.2-Firenze | QGIS code branch | Release 3.28
Qt version | 5.15.7
Python version | 3.9.16
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PDAL version | 2.5.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.3
OS version | Gentoo Linux
```

### Steps to reproduce the issue

Pick an image , try to georeference it, ideally use as reference to derive the positions EPSG:5514 so the X and Y values will be negative and large too. Then print the GDAL commandline.

### Versions

3.28.2-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
It seems to me #51792 is not related with this issue.

**Comment by mmokrejs** [comment]
I am just guessing is it caused by python reprinting the string floats in sci represeantation?

**Comment by agiudiceandrea** [comment]
> is it caused by eventual python reprinting into string some floats using sci representation?

Yes, this is the cause of the issue.

**Comment by mmokrejs** [comment]
Ideall, as a user I would like to see in the cmdline and Georeferencer GUI (even when re-opening later the image along with its GCPs) the values I entered once into the table. Extra trailing zeroes are fine but one really expect exactly same values, not rounding or loss of precision. Even for sanity checks the numbers should be as they were entered or inferred via the reference image. I think it is obvious. Thank you for finding that.

**Comment by mmokrejs** [comment]
[report.pdf](https://github.com/qgis/QGIS/files/10723404/report.pdf)

An example file from a different attempt, this time with QGIS code revision [48a42c7fae](https://github.com/qgis/QGIS/commit/48a42c7fae).
