### ISSUE TITLE
Point to Point shortest distances but for multiple poairs eg 1000 origins to distinct 1000 destinations so total 1000 OD pairs

### ISSUE THREAD

**Issue by Kaushal333** [qgis/QGIS#51825]
### Feature description

for example: I want to calculate distance from 500 different points to 500 different points in QGIS. In QGis they dont have special tool for this. They just have point to poin (single), point to layer and layer to point.
So I decided to use batch processing on point to point.
But the main problem is :
![image](https://user-images.githubusercontent.com/125223590/218424398-293654f4-c9b6-4587-8f30-bfada56cf816.png)
![image](https://user-images.githubusercontent.com/125223590/218424524-bed37a2a-c96b-49f3-a6d4-8cb0ccf3711c.png)
(The instructions from https://gis.stackexchange.com/questions/441280/qgis-shortest-path-layer-to-layer)

But my question is bit different as I want to find from 500 different points to 500 different points , so in total just 500 paths.

MY PROBLEM

![image](https://user-images.githubusercontent.com/125223590/218424591-18b7591a-319c-4ed8-b247-5787f9510d99.png)

SO I decided to use "add value by expression" for both for start and end points but qgis starts filling the values from the rows where the start values end . FOr eg, for 4 origins to 4 destinations, when i use add by expression in start points, i fill 4 rows , 1-4 , and when i try to fill end points it starts filling from row 5 to row 8 instead of rows 1 to 4.

Note:
There are other ways to generate distant matrices from layer to layer so there will be for example 1000*1000 OD pairs instead of just 1000 OD pairs which i want so i want to use this method )
Regards
Kaushal

**Comment by agiudiceandrea** [comment]
@Kaushal333 to calculate the distances from 500 points in a layer to 500 points in another layer means to calculate 500*500 distances, or, with 500 points in the same layer, 499*500 distances or 499*500/2 unique distances, not only 500.
Could you explain how do you want to calculate only 500 distances?

**Comment by Kaushal333** [comment]
I have 500 distinct origin points and 500 distinct destinations so I want point to point distances.But instead of doing it one by one, i wanted to do it in batch processing. 

I have already found the solution in:

https://gis.stackexchange.com/questions/449686/how-to-put-the-end-points-with-the-same-rows-as-the-start-points-using-shortest
