### ISSUE TITLE
HTML Label doesn't work on curved perimeter

### ISSUE THREAD

**Issue by ThaweK** [qgis/QGIS#51829]
### What is the bug or the crash?

When you select HTML formatting of the label on the polygon, when label placement is set to Perimeter (curved), label behaviour is unexpected. Comparison is given on the below picture:

![label](https://user-images.githubusercontent.com/63213296/218468947-3fbe2e0b-094a-4efe-8bab-a260b119aa88.png)

### Steps to reproduce the issue

1. Take any polygon
2. Add label
3. Set rendering to Perimeter (curved)
4. in text section enable "Allow HTML formatting"

### Versions

3.18
3.28.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
This is functionality "won't fix" (HTML labels cannot be curved). 

I'm tagging as UX because you are right: this is unexpected and we should make it clear to the user that two incompatible options have been selected.

**Comment by nyalldawson** [comment]
Actually HTML labels CAN be curved in qgis land. It works ok for line layers, there's likely just something missing to have the perimeter option handled correctly.

**Comment by ThaweK** [comment]
> Actually HTML labels CAN be curved in qgis land. It works ok for line layers, there's likely just something missing to have the perimeter option handled correctly.

I do agree that with regular polyline it works. It just happened to polygon. Polygons were created based on openAIR data.
