### ISSUE TITLE
array_remove_all expression function returns NULL when trying to remove NULLs

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#51820]
### What is the bug or the crash?

I was trying to remove `NULL` values from an array and thought the `array_remove_all` expression function would be the perfect tool. Unfortunately it returns a plain `NULL` as result when one passes `NULL` as value to _remove_.

### Steps to reproduce the issue

```
array_remove_all(
	array(1, 2, NULL),
	value:=1
)
```
returns `[ 2, NULL ]` which is correct.

```
array_remove_all(
	array(1, 2, NULL),
	value:=NULL
)
```
returns `NULL` but I expected it to return `[ 1, 2 ]`.

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I am not sure if it should support removal of `NULL` values but if not, adding a note to the documentation would be nice to keep others from failing. Considering that other functions like `array_contains`, `array_count` or `array_find` behave in the same way, I assume it is by design. In that case, please close this and if possible, point me to documentation or a list of those functions so I can update their documentation texts. :)

-----

I guess that using `array_filter` is the best alternative:
```
array_filter(
	array(1, 2, NULL),
	expression:=@element IS NOT NULL
)
```
returns `[ 1, 2 ]`

**Comment by agiudiceandrea** [comment]
The list and description of functions is at https://docs.qgis.org/testing/en/docs/user_manual/expressions/functions_list.html and is maintained at https://github.com/qgis/QGIS-Documentation/blob/master/docs/user_manual/expressions/functions_list.rst. The functions help are at https://github.com/qgis/QGIS/tree/master/resources/function_help/json.
