### ISSUE TITLE
GDAL Raster analysis IDW Interpolation - Null Values

### ISSUE THREAD

**Issue by cesarcorreo** [qgis/QGIS#51826]
### What is the bug or the crash?

Null values are considered as 0 in IDW GDAL interpolation

### Steps to reproduce the issue

Time ago I opened (and was solved in #43302) the same problem with IDW and TIN interpolations.
I´m having the same bug with GDAL IDW interpolation.
Example: 
We consider 5 points where 4 of them at the extremes always have a value of 10 and the central point with three assumptions:

1. All values -> All points with a value of 10.
2. 0_Value -> Centre point value of 0
3. Null_Value-> Centre point value of Null

Result:

The resulting interpolated layer behaves:

- In assumption 1 constant raster layer with value of 10.
- Assumptions 2 and 3. The resulting raster layer shows a central depression with a value of 0.

I understand that the result in assumption 1 should be a constant layer with value equal to 10 and not the result that results in the resulting layer giving a value of 0 at the point with null value.
(I have taken into account a very wide search radius value to avoid problems in "locating points")
[IDW_GDAL_ERROR.zip](https://github.com/qgis/QGIS/files/10721440/IDW_GDAL_ERROR.zip)

### Versions

(Also tested in 3.16.16 with the same bug)

Versión de QGIS
3.28.3-Firenze
Revisión del código de QGIS
c12bcb2f76c
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.2
Versión de PROJ
9.1.1
Versión del registro de base de datos EPSG
v10.076 (2022-08-31)
Versión de GEOS
3.11.1-CAPI-1.17.1
Versión de SQLite
3.39.4
Versión de PDAL
2.4.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
Cadastral_Divisions-main
1.2
ClipMultipleLayers
3.2.0
contour
2.0.12
dataexplorer
3.1.1
DataPlotly
3.9.2
kmltools
3.1.27
latlontools
3.6.8
magic_map_loader
1.0
mmqgis
2021.9.10
PlanCreator-3
0.1
PluginLoadTimes
3.0.1
pointsamplingtool
0.5.4
polystrip
3.0.1
processing_saga_nextgen
0.0.7
profiletool
4.2.2
project_report
1.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
QGISSortAndNumber-master
1.0
quick_map_services
0.19.33
refFunctions
1.6
rvt-qgis
0.9.4.1
searchlayers
3.0.12
Serval
3.10.5
Smart_Map
1.2
Spanish_Inspire_Catastral_Downloader
1.1
SpreadsheetLayers
2.1.0-alpha1
StreetView
3.2
Submission
0.7
ThreePointMethod
0.1
valuetool
3.0.15
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
[IDW_GDAL_ERROR.zip](https://github.com/qgis/QGIS/files/10721410/IDW_GDAL_ERROR.zip)

![3](https://user-images.githubusercontent.com/25932761/218437880-19474f28-e2c3-4261-b53d-1b2dee57d43d.jpg)

2.12.99
processing
![4](https://user-images.githubusercontent.com/25932761/218437885-70ae82ca-c0af-4f0e-90ba-9baffa2f5131.jpg)

![2](https://user-images.githubusercontent.com/25932761/218437861-488ceed1-1e7b-4ed9-99d9-a743973c771a.jpg)

2.12.99
![1](https://user-images.githubusercontent.com/25932761/218437841-2f6e90e6-ada9-4ce3-9ac3-49eb2a869322.jpg)

sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
@cesarcorreo could you try with the gdal command shown at bottom of alg window in OSGeo Shell ?
If it results in a similar error, this is a GDAL issue and not a QGIS one and you should report this in https://github.com/OSGeo/gdal/issues

**Comment by cesarcorreo** [comment]
Thanks for your fast answer.
I never used it before. 
The result in OSGeo4W shell seems an error:

C:\Program Files\QGIS 3.28.3>gdal_grid -l Con_null -zfield valor -a invdistnn:power=2.0:smoothing=0.0:radius=5000.0:max_points=12:min_points=0:nodata=0.0 -ot Float32 -of SAGA C:/Users/TYPSA/Desktop/HOY/Interpolaciones-Error/Con_null.fgb C:/Users/TYPSA/Desktop/HOY/Interpolaciones-Error/OsgeoShell.sdat
![5](https://user-images.githubusercontent.com/25932761/218444305-b868ce17-bbdc-4c7e-8830-e5d3a7a2467f.jpg)

0...10...20...30...40...50...60...70...80...90...100 - done.
ERROR 6: Unable to set GeoTransform, SAGA binary grids only support the same cellsize in x-y.

**Comment by rouault** [comment]
will be solved per https://github.com/OSGeo/gdal/pull/7244 (GDAL 3.6.3)
Closing
