### ISSUE TITLE
QGIS Crashing when items deleted from print composer!

### ISSUE THREAD

**Issue by Mozlo** [qgis/QGIS#51823]
## User Feedback

QGIS will always unexpectedly crash when deleting items from the print layout. I would say that whenever I delete something from print layout there is around about a 30-40% chance that qgis will crash. This happens regardless of version or pc specs.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000e2c (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Open a layout in print composer. Select multiple items on that layout. Press delete. Watch QGIS crash. Simple

### Versions

3.28 Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This happens regardless of version or hardware. This has happened to me across all versions in the past year and even with a brand new computer this week, the issue remains the same. I always have to save before doing anything within print composer and if I don't there are times where I have to redo a looooot of work

**Comment by elpaso** [comment]
Can you please attach a sample project and a detailed step by step procedure to reproduce the issue?

**Comment by bkepl** [comment]
I have also had this happen.
