### ISSUE TITLE
QGIS very slow (opening and functionnalities)

### ISSUE THREAD

**Issue by arxitaqu** [qgis/QGIS#51848]
Hello,
### What is the bug or the crash?

For several months, QGIS take more than 1 minute to open and is very slow to handle (using buttons and functionnalities)

### Steps to reproduce the issue

Just open QGIS, or click on any button
(if I execute QGIS as Administrator, it is faster)

### Versions

Version de QGIS
3.22.6-Białowieża
Révision du code
b6f33b1a
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.4.2
Version de Proj
9.0.0
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.38.1
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.3
Version de QScintilla2
2.11.5
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
changeDataSource
3.1
GroupStats
2.2.5
Importer2OSMbasemap
1.0
MultipleLayerSelection
2.0
plugin_reloader
0.9.1
Qgis2threejs
2.7.1
qgis2web
3.16.0
quick_map_services
0.19.29
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by arxitaqu** [comment]
Two colleagues of mine have the same issue

**Comment by anaxonda** [comment]
Unusably slow for me as well. I tried 3.28.3 as well as 3.30.0. It seems like running qgis as root is slightly faster, but still slow.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>


QGIS version | 3.28.3-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.9
Compiled against GDAL/OGR | 3.6.2 | Running against GDAL/OGR | 3.6.3
Compiled against PROJ | 9.1.1.%3.%4 | Running against PROJ | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.1-CAPI-1.17.1
Compiled against SQLite | 3.40.1 | Running against SQLite | 3.41.1
Compiled against PDAL | 2.5.0 | Running against PDAL | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.4
OS version | Arch Linux
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
sagaprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.3-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.8
Python version
3.10.9
Compiled against GDAL/OGR
3.6.2
Running against GDAL/OGR
3.6.3
Compiled against PROJ
9.1.1.%3.%4
Running against PROJ
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.1-CAPI-1.17.1
Compiled against SQLite
3.40.1
Running against SQLite
3.41.1
Compiled against PDAL
2.5.0
Running against PDAL
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.4
OS version
Arch Linux




Active Python plugins
quick_map_services
0.19.33
sagaprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

**Comment by unacomn** [comment]
Hi. How many print layouts with legends (filtered to current map view) are currently saved in your project?
This has been the cause of a lot of slowdown since version 3.22, processing each legend takes about 7-8 times longer than it did in 3.20.
A fix is being implemented in 3.32:
#52161 

That will hopefully resolve the issue, as seen here:
#50209
#51233

**Comment by anaxonda** [comment]
In my case, none.

**Comment by anaxonda** [comment]
I think my issue is related (or just is) to this one https://github.com/qgis/QGIS/issues/51595.

**Comment by alexbruy** [comment]
Is this still an issue with the latest versions?

**Comment by arxitaqu** [comment]
Yes, I tried during trainings and there is still the issue with 3.32 QGIS version

Regards.

Aurélien Quiblier
Chef de projet & Géomaticien
Tél. 01 78 09 94 37 - N° Int. 29
Adr. 70 Cours Tolstoï – 69100 Villeurbanne / Lyon
[https://email.arxit.com/signature/Portraits/AQU.png]
[https://email.arxit.com/signature/Logo/Societes_LY.png]<https://www.arxit.com/>
[https://email.arxit.com/signature/Logo/site_txt.png]<https://www.arxit.com/>
[https://email.arxit.com/signature/Logo/FormationSIG.png]<https://www.formationsig.com/>
[https://email.arxit.com/signature/Logo/ic_in.png]<https://www.linkedin.com/company/11480972/admin/>[https://email.arxit.com/signature/Logo/ic_twitter.png]<https://twitter.com/arxit?lang=fr>[https://email.arxit.com/signature/Logo/ic_youtube.png]<https://www.youtube.com/user/arxit1201>

**Comment by arxitaqu** [comment]
Hello,

I replied two weeks ago.
I tried again with a colleague with 3.32 QGIS version. The only way to prevent these slowdowns is to run QGIS as administrator (via windows).

Regards,
Aurélien QUIBLIER

**Comment by alexbruy** [comment]
There is not enough details to reproduce this. I'm using QGIS everyday with quite heavy projects and don't see any slowness.

**Comment by arxitaqu** [comment]
Ok thanks.
Maybe it is because of our environments (but I saw this problem on many other customers)

Aurélien Quiblier
Chef de projet & Géomaticien
Tél. 01 78 09 94 37 - N° Int. 29
Adr. 70 Cours Tolstoï – 69100 Villeurbanne / Lyon
[https://email.arxit.com/signature/Portraits/AQU.png]
[https://email.arxit.com/signature/Logo/Societes_LY.png]<https://www.arxit.com/>
[https://email.arxit.com/signature/Logo/site_txt.png]<https://www.arxit.com/>
[https://email.arxit.com/signature/Logo/FormationSIG.png]<https://www.formationsig.com/>
[https://email.arxit.com/signature/Logo/ic_in.png]<https://www.linkedin.com/company/11480972/admin/>[https://email.arxit.com/signature/Logo/ic_twitter.png]<https://twitter.com/arxit?lang=fr>[https://email.arxit.com/signature/Logo/ic_youtube.png]<https://www.youtube.com/user/arxit1201>

**Comment by andreasneumann** [comment]
It might be useful to have a look in the debugging panel. Here you can see where QGIS spends how much time in what section during startup and also for opening projects.

Menu "View" --> "Panels" --> "Debugging/Development Tools".

The output should look something like:

![grafik](https://github.com/qgis/QGIS/assets/884476/3bbfccc6-f1c3-49b0-96cb-522768021cf4)

You can usually see that plugins slow down QGIS the most. Deactivating plugins that you don't need helps usually.

Have you checked about plugins?

**Comment by nilsnolde** [comment]
I have the same problem on a fresh Manjaro Xfce 4.18 installation. I installed v3.34 with `pacman` and startup is super slow. The worst offender is `New Project`:
![image](https://github.com/qgis/QGIS/assets/25637358/232b51d7-aa6f-4b94-9e96-c91a1a907d5d)

10 secs is pretty excessive to create a new project. It's a completely fresh installation, I didn't even add a 3rd party plugin yet. Everything else is crazy slow as well to the point of being really unusable. e.g. clicking on a layer to select it in the "Layers" dialog also takes 10 seconds, as well as right-clicking a layer. The tools however work quite fluidly.

**It worked now** rather randomly. All of a sudden it started up just fine, on the 10th time or so. Very fast and reactive. So for anyone that's happening to as well, just keep opening and closing QGIS, maybe restart the computer and it might work at some point;)
