### ISSUE TITLE
Combine problem returning null geometry

### ISSUE THREAD

**Issue by arxitaqu** [qgis/QGIS#51851]
Hello,

### What is the bug or the crash?

I want to combine two geometries and the result is a null geometry.
I think the problem is due to coordinates of the two geometries (they seem to be too similar).
If I use a buffer (Ex : 10 cm), it works.

### Steps to reproduce the issue

Use the following Python code :

`
initGeo = [f.geometry() for f in iface.activeLayer().getFeatures()][0]

modifGeo = [f.geometry() for f in iface.activeLayer().getFeatures()][0]

initGeo.combine(modifGeo)
`

### Versions

Version de QGIS
3.22.6-Białowieża
Révision du code
b6f33b1a
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.4.2
Version de Proj
9.0.0
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.38.1
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.3
Version de QScintilla2
2.11.5
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
changeDataSource
3.1
GroupStats
2.2.5
Importer2OSMbasemap
1.0
MultipleLayerSelection
2.0
plugin_reloader
0.9.1
Qgis2threejs
2.7.1
qgis2web
3.16.0
quick_map_services
0.19.29
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Why did you tick the profile and supported version box if you clearly don't.

Also your ticket has no useful information to indicate if this is a bug or an issue on your end.

**Comment by arxitaqu** [comment]
I have tried with a new profile "aurelien", but I have the same problem

**Comment by arxitaqu** [comment]
Here is the GPKG file containing the two layers with entities i tried to combine

**Comment by arxitaqu** [comment]
Here is the GPKG file containing the two layers with entities i tried to combine
[problem_Combine.zip](https://github.com/qgis/QGIS/files/10733095/problem_Combine.zip)

**Comment by roya0045** [comment]
> Here is the GPKG file containing the two layers with entities i tried to combine [problem_Combine.zip](https://github.com/qgis/QGIS/files/10733095/problem_Combine.zip)

That will be useful, though I'm not sure why your code seem to try to combine the same geometry with itself, unless you select the second layer for the second line. If all is run together you won't have the time to change the active layer.

**Comment by arxitaqu** [comment]
The result is : 
![image](https://user-images.githubusercontent.com/102357196/218771134-7220f7fe-196f-4e2a-a26f-39e6505c6948.png)

**Comment by alexbruy** [comment]
Your layers have features with invalid geometries, after fixing them combine works fine.
