### ISSUE TITLE
Crush and QGIS unexpectedly ended

### ISSUE THREAD

**Issue by qorthdal** [qgis/QGIS#51866]
### What is the bug or the crash?

Crash ID: 9ec337d1fa5b3c1e6708b9acff481ca9e6cbaad6

Stack Trace

QSortFilterProxyModel::trUtf8 :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::nodeAddedChildren :
QObject::qt_static_metacall :
QgsLayerTreeNode::addedChildren :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/125422408/218914902-661d1dd1-1930-46ac-9b14-3010501dd9ea.png)
The image is my QGIS screen.

### Versions

**QGIS Info**
QGIS Version: 3.22.5-Bialowieza
QGIS code revision: c2723178
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I want to use GTFS-Loader plugin. But when I selected file and loaded it, QGIS unexpectedly ended.
To solve this problem, I created new profile and delete all data in 'C:\Users\user\AppData\Roaming\QGIS\QGIS3' 
And then I redownload GTFS-Loader, used other GTFS data, changed the latest QGIS version and etc..
But it still doesn't work. How can I solve this..?

**Comment by nicogodet** [comment]
If it is strictly related to the use of this plugin then it’s not a QGIS issue on first sight.
Please report on plugin repo issue (can be found in plugin info in plugin manager).

**Comment by qorthdal** [comment]
Plugin repo is [](https://plugins.qgis.org/plugins/plugins.xml?qgis=3.22)
It's wrong?

**Comment by qorthdal** [comment]
> If it is strictly related to the use of this plugin then it’s not a QGIS issue on first sight. Please report on plugin repo issue (can be found in plugin info in plugin manager).
Plugin repo is [](https://plugins.qgis.org/plugins/plugins.xml?qgis=3.22)
It's wrong?

**Comment by nicogodet** [comment]
https://plugins.qgis.org/plugins/GTFS_Loader/

https://github.com/ctu-geoforall-lab/qgis-gtfs-plugin/issues

See issue : https://github.com/ctu-geoforall-lab/qgis-gtfs-plugin/issues/11
