### ISSUE TITLE
Problems encountered in creating a new Shapefile layer in QGIS

### ISSUE THREAD

**Issue by dt123456789** [qgis/QGIS#51867]
### What is the bug or the crash?

         QGIS creates a new Shapefile layer, it uses Chinese as the header of the table. After it is successfully saved, the header becomes garbled, and the UTF-8 and GBK codes cannot be converted back to Chinese. What is the problem, or my operation problem, please guide me, thank you

### Steps to reproduce the issue

        When QGIS creates a new Shapefile layer, it uses Chinese as the header of the table. After it is successfully saved, the header becomes garbled, and the UTF-8 and GBK codes cannot be converted back to Chinese. What is the problem, or my operation problem, please guide me, thank you

### Versions

3.28.3-Firenze

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@dt123456789 please follow the issue report instruction: In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.
Please provide a sample layer in order to replicate the issue.
