### ISSUE TITLE
'IDW Interpolation' integration with QGIS Model Designer

### ISSUE THREAD

**Issue by DylanChenoweth** [qgis/QGIS#51864]
### Feature description

IDW Interpolation tool unable to be edited to select model inputs or algorithm outputs within QGIS model Designer as of 15/02/2023 - long standing issue.

### Additional context

Previous issues have been raised that the IDW Interpolation tool can not be used/edited in the QGIS Model Designer application.

See ref [https://gis.stackexchange.com/questions/412255/cant-include-idw-interpolation-in-model-using-qgis](url)

The input vector layer selection options only present a list from the loaded project, rather than model algorithm outputs. 

To streamline workflow it would be extremely helpful if this feature was fixed so that we can use IDW interpolation in our models.

Note in the below image the vector layer selection applet can not be changed for model inputs/algorithm outputs. 
![image](https://user-images.githubusercontent.com/125417663/218895970-6d30b6c6-1ba4-4ab7-aeb5-79884fdfc229.png)

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/30029
