### ISSUE TITLE
r.grow.distance Calculate distance to nearest NULL cell

### ISSUE THREAD

**Issue by rogomax** [qgis/QGIS#51878]
### What is the bug or the crash?

This option do not work using 3.28.3. Looking at the Journal of the tooltip, the option used is "-" instead of "-n". 

### Steps to reproduce the issue

use r.grow.distance command.
Even if the option "Calculate distance to nearest NULL cell" is checked, the distance is computed inside the null region and not outside (distance to NULL cell).

### Versions

Version de QGIS
3.28.2-Firenze
Révision du code
b47e00ba601
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.1
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
geometric_attributes
0.3
gmsh
version 0.2.2
QGIS3-getWKT
1.4
QuickWKT
3.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
@rogomax You can try to modify the description file located in $QGIS_INSTALL_FOLDER/apps/qgis/python/plugins/grassprovider/description as in PRand check if it fixes the issue

**Comment by rogomax** [comment]
Thank you, adding the 'n', so that the option is now '-n' in the file as you recommended, is working. Perhaps can you report the correction to the source code.

**Comment by nicogodet** [comment]
@rogomax Done in https://github.com/qgis/QGIS/pull/51880
