### ISSUE TITLE
Increase offset of hover label in map view away from mouse cursor

### ISSUE THREAD

**Issue by holgerson11** [qgis/QGIS#51879]
### Feature description

The mouse cursor is hiding part of the information in the hover label in the map view (see attached screenshot). 

Offset should be increased or anchor point should be changed to show complete hover label.

### Additional context

![image](https://user-images.githubusercontent.com/10484392/219049283-bf1436ef-48f7-43b3-9a12-8a84f4ae1165.png)

**Comment by uclaros** [comment]
This has been fixed in #48333 :)
