### ISSUE TITLE
Wrong feature count in refined rule renderer

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#51875]
### What is the bug or the crash?

If a rule renderer is used and one of the rule is refined, for example adding some ranges, the feature count next to each class in the legend is 0. The same happens also if a category is used to refine the rule rather than ranges.

Before refining:

![image](https://user-images.githubusercontent.com/2884884/218955372-ae0aac69-24f6-4304-8699-2d84de3643bd.png)

After refining:

![image](https://user-images.githubusercontent.com/2884884/218955512-fa04aa1b-fd36-419f-a051-64d06751274c.png)

### Steps to reproduce the issue

I've prepared a sample project with the data used in the screenshot. Here in attach: 
[sample.zip](https://github.com/qgis/QGIS/files/10740163/sample.zip)

### Versions

QGIS version | 3.29.0-Master | QGIS code revision | 339d41e223
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux bookworm/sid
  |   |   |  

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please try with with latest Master
https://github.com/qgis/QGIS/pull/51740

**Comment by ghtmtt** [comment]
Successfully compiled the last master and bug gone. Thanks!
