### ISSUE TITLE
QGIS won't install correctly on ubuntu 22.04

### ISSUE THREAD

**Issue by lawrencem** [qgis/QGIS#51886]
### What is the bug or the crash?

Setting up qgis-providers (1:3.28.3+36jammy) ...
/usr/lib/qgis/crssync: symbol lookup error: /lib/x86_64-linux-gnu/libspatialite.
so.7: undefined symbol: GEOSFrechetDistanceDensify

### Steps to reproduce the issue

apt install qgis

### Versions

3.28.3+36jammy

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by jef-n** [comment]
Your spatialite is apparently broken.  jammy has:

```
# dpkg -l qgis-providers libspatialite*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                 Version          Architecture Description
+++-====================-================-============-===========================================
ii  libspatialite7:amd64 5.0.1-2build2    amd64        Geospatial extension for SQLite - libraries
ii  qgis-providers       1:3.28.3+36jammy amd64        collection of data providers to QGIS
# ls -l  /lib/x86_64-linux-gnu/libspatialite.so.7*
lrwxrwxrwx 1 root root      22 Oct 27  2021 /lib/x86_64-linux-gnu/libspatialite.so.7 -> libspatialite.so.7.1.2
-rw-r--r-- 1 root root 8257944 Oct 27  2021 /lib/x86_64-linux-gnu/libspatialite.so.7.1.2
```

**Comment by lawrencem** [comment]
I have the exact same output on my system: I have reinstalled it several times. I even tried the unstable version.
$ dpkg -l qgis-providers libspatialite*
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name                    Version          Architecture Description
+++-=======================-================-============-=====================>
ii  libspatialite-dev:amd64 5.0.1-2build2    amd64        Geospatial extension >
ii  libspatialite7:amd64    5.0.1-2build2    amd64        Geospatial extension >
iF  qgis-providers          1:3.28.3+36jammy amd64        collection of data pr>
$ ls -l /lib/x86_64-linux-gnu/libspatialite.so.7
libspatialite.so.7      libspatialite.so.7.1.2  
$ ls -l /lib/x86_64-linux-gnu/libspatialite.so.7*
lrwxrwxrwx 1 root root      22 Oct 27  2021 /lib/x86_64-linux-gnu/libspatialite.so.7 -> libspatialite.so.7.1.2
-rw-r--r-- 1 root root 8257944 Oct 27  2021 /lib/x86_64-linux-gnu/libspatialite.so.7.1.2

**Comment by jef-n** [comment]
Still it unrelated to qgis itself.  spatialite is referencing a symbol not available in geos.   So if it's not spatialite it must be geos.  jammy's geos has GEOSFrechetDistanceDensify that spatialite is looking for:

```
# ldd /lib/x86_64-linux-gnu/libspatialite.so.7.1.2  | grep geos
	libgeos_c.so.1 => /lib/x86_64-linux-gnu/libgeos_c.so.1 (0x00007f1c276f9000)
	libgeos.so.3.10.2 => /lib/x86_64-linux-gnu/libgeos.so.3.10.2 (0x00007f1c26200000)
# objdump -T /lib/x86_64-linux-gnu/libspatialite.so.7.1.2 | grep GEOSFrechetDistanceDensify
0000000000000000      DF *UND*	0000000000000000  Base        GEOSFrechetDistanceDensify
0000000000000000      DF *UND*	0000000000000000  Base        GEOSFrechetDistanceDensify_r
# objdump -T /lib/x86_64-linux-gnu/libgeos_c.so.1 | grep GEOSFrechetDistanceDensify
000000000001a230 g    DF .text	000000000000001c  Base        GEOSFrechetDistanceDensify
000000000001a1c0 g    DF .text	0000000000000068  Base        GEOSFrechetDistanceDensify_r
# dpkg -S libgeos_c.so.1
libgeos-c1v5:amd64: /usr/lib/x86_64-linux-gnu/libgeos_c.so.1.16.0
libgeos-c1v5:amd64: /usr/lib/x86_64-linux-gnu/libgeos_c.so.1
#  apt-cache policy libgeos-c1v5:amd64 
libgeos-c1v5:
  Installed: 3.10.2-1
  Candidate: 3.10.2-1
  Version table:
 *** 3.10.2-1 500
        500 https://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
        100 /var/lib/dpkg/status
```

**Comment by lawrencem** [comment]
Mine all look the same as yours. However, I still cannot install qgis. I deleted all of the qgis packages and their prerequisites, using autoremove. Then I atttempted to reinstall qgis. I get this:

Setting up qgis-providers (1:3.28.3+36jammy) ...
/usr/lib/qgis/crssync: symbol lookup error: /lib/x86_64-linux-gnu/libspatialite.so.7: undefined symbol: GEOSFrechetDistanceDensify
dpkg: error processing package qgis-providers (--configure):
 installed qgis-providers package post-installation script subprocess returned error exit status 127

The error is coming from /usr/lib/qgis/crssync

**Comment by jef-n** [comment]
On Thu, 16. Feb 2023 at 16:30:48 -0800, Lawrence MacIntyre wrote:
> Mine all look the same as yours. However, I still cannot install qgis. I
> deleted all of the qgis packages and their prerequisites, using autoremove.
> Then I atttempted to reinstall qgis. I get this:

Strange.  As said this looks unrelated to qgis as crssync uses spatialite which
has a problem with geos.  crssync is ours, but spatialite and proj come from
ubuntu.

Can you run spatialite from spatialite-bin?

# spatialite -version
3.37.2 2022-01-06 13:25:41 872ba256cbf61d9290b571c0e6d82a20c224ca3ad82971edc46b29818d5dalt1


Jürgen

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/
