### ISSUE TITLE
Cant open file in Qgis

### ISSUE THREAD

**Issue by olya010** [qgis/QGIS#51887]
### What is the bug or the crash?

When I open the project it hangs for a few minutes and i I cannot press any commands and then the project closes itself. What to do in this case?

### Steps to reproduce the issue

The image is my QGIS screen.
https://drive.google.com/file/d/1i5yUWvZxSKHhPR9RNR273XTWwBkntC1q/view?usp=sharing

### Versions

QGIS Info
QGIS Version: 3.22.16-Bialowieza

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you give more info ?
We can't guess what's in your project... (local layers, distant one over local network, over internet, ...)

Provide detailed step to reproduce, provide project and data if you can.
