### ISSUE TITLE
[Plugin] Install from ZIP fails with "QgsSettingsTree.createPluginTreeNode("_plugin_manager")" error

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#51898]
### What is the bug or the crash?

On a fresh QGIS profile, installing the first plugin from zip results in the following error:

```
An error occurred during execution of following code:
pyplugin_installer.instance().installFromZipFile(r'/tmp/HelloWorld-2.3.zip')

Traceback (most recent call last):
  File "", line 1, in 
  File "/home/richard/bin/qgis_/master/debug/share/qgis/python/pyplugin_installer/installer.py", line 581, in installFromZipFile
    QgsSettingsTree.createPluginTreeNode("_plugin_manager").childSetting("last-zip-directory").setValue(QFileInfo(filePath).absoluteDir().absolutePath())
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'setValue'

```

Looks like there is no `last-zip-directory` setting yet?, or @3nids  is this a QSettings thingie?

![Screenshot from 2023-02-16 15-19-10](https://user-images.githubusercontent.com/731673/219389863-c1a1c650-f1b5-4dd8-aa3b-a1a2c03eec95.png)

### Steps to reproduce the issue

Start QGIS in a super clean profile:

`qgis --profiles-path /tmp/foo`

Download the zip of the HelloWorld Plugin and download in /tmp

`wget https://plugins.qgis.org/plugins/HelloWorld/version/2.3/download/`

In QGIS go to the Plugin Manager, and 'install plugin from zip', 
Browse to the temp dir and select /tmp/HelloWorld-2.3.zip

Click button 'Install Plugin'

I get the Python Error above

Even after installing a new plugin from the repo I get this error?

### Versions

master (recent, not super fresh):

QGIS version | 3.29.0-Master | QGIS code revision | 00da22feca8
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.1
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux bookworm/sid

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by 3nids** [comment]
yes my fault
fix in https://github.com/qgis/QGIS/pull/51899
