### ISSUE TITLE
Layer Styling panel: Grey out the button 'Apply' when 'Live update' is checked

### ISSUE THREAD

**Issue by MieWinstrup** [qgis/QGIS#51894]
### Feature description

I do a lot of courses in QGIS, and quite often the attendes are confused by the 'Apply'-button in the lower right part of the layer styling panel. 

I think it would be user friendly if the 'Apply'-button was greyed out/deactivated (like a lot of other places in QGIS) when 'Live update' in checked. 

When 'Live update' is not checked, the 'Apply'-button should activated.

![image](https://user-images.githubusercontent.com/16276034/219350891-e61ab44b-d902-4561-8361-9c5fcf58300b.png)

**Comment by roya0045** [comment]
An alternative would be to only enable the button when the settings have unsaved changes/are dirty. This could give uses a clue if they have any pending style change when live update is not enabled.

**Comment by nyalldawson** [comment]
@roya0045 good idea 👍

**Comment by MieWinstrup** [comment]
Yes - that would be the elegant implementation!
