### ISSUE TITLE
Installing current release of QGIS on Ubuntu 22.04

### ISSUE THREAD

**Issue by Mangoesmapping-GeorgeCorea** [qgis/QGIS#51906]
### What is the bug or the crash?

On a fresh server -only xrdp installed I am unable to install QGIS.

I have tried solutions in 38329 for prev Ubuntu release and am using instructions in https://www.qgis.org/en/site/forusers/alldownloads.html

The errors are as follows - I tried just installing qgis without grass or the server

```
gis@vmi808391:~/Desktop$ sudo apt install qgis
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 qgis : Depends: libgdal32 (>= 1.11) but it is not installable
        Depends: libqgis-3d3.29.0 but it is not going to be installed
        Depends: libqgis-analysis3.29.0 but it is not going to be installed
        Depends: libqgis-app3.29.0 but it is not going to be installed
        Depends: libqgis-core3.29.0 but it is not going to be installed
        Depends: libqgis-gui3.29.0 but it is not going to be installed
        Depends: python3-qgis (= 1:3.29.0+git20230213+48a42c7fae+36jammy-ubuntugis) but it is not going to be installed
        Depends: qgis-providers (= 1:3.29.0+git20230213+48a42c7fae+36jammy-ubuntugis) but it is not going to be installed
        Recommends: qgis-plugin-grass but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

Description:	Ubuntu 22.10
Release:	22.10
Codename:	kinetic

### Steps to reproduce the issue

Follow instructions in documentation for Ubuntu (https://www.qgis.org/en/site/forusers/alldownloads.html)

The only change is that for /etc/apt/sources.list.d/qgis.sources I have tried

URIs: https://qgis.org/ubuntu
Suites: jammy

and

URIs: https://qgis.org/ubuntugis-nightly-release
Suites: jammy

### Versions

Couldn't install current LTR, Nightly or Dev versions

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
You use Kinetic but you wrote Jammy in source list ?
