### ISSUE TITLE
QGIS 3.28.3 Breaks Marker Line symbol styles from previous versions

### ISSUE THREAD

**Issue by kylesomerville** [qgis/QGIS#51918]
### What is the bug or the crash?

Marker lines in projects saved with earlier versions (at least 3.22) with styles defined with markers at start / end of lines, and at midpoint of segments of lines, when opened in 3.28 cause markers to ignore that style.  Markers appear to be opened with default 3mm interval along line. 

### Steps to reproduce the issue

Create line in 3.22 or earlier.  Assign marker line with location set at start of line or end of line or midpoint of segments.  Save project.  Open project in 3.28.  Linetype style will be broken.

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
clipper
coordinate_capture
dem_drainage_analyses
dimensioning
EasyCustomLabeling
FreehandRasterGeoreferencer
go2streetview
group_transparency
ImportPhotos
joinmultiplelines
layerfromclipboard
MemoryLayerSaver
NNJoin
nominatim
openlayers_plugin
OSTranslatorII
pointsamplingtool
profile-manager
profiletool
qad
QChatGPT
qfieldsync
QGISSortAndNumber-master
QPackage
QRectangleCreator
QuickPrint
quick_map_services
rivergis
splitmultipart
SpreadsheetLayers
themeselector
valuetool
ZoomToPostcode
db_manager
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@kylesomerville I cannot confirm on my Windows system using QGIS 3.22.10 and 3.28.3. Could you please provide a sample project and layer in order to replicate the issue? Could you please try if the issue does occur actually using a currently supported QGIS version and a new QGIS user profile? (Judging by the provided info, it seems you are running an old QGIS 3.20.3 version without using a new QGIS user profile)
