### ISSUE TITLE
[Feature]Search bar for Layers

### ISSUE THREAD

**Issue by gafzgarrr** [qgis/QGIS#51929]
### Feature description

If you use a lot of Layers in a lot of Groups or Sub-Groups, sometimes it is hard to find the layer in the layer-tree.
So there sould be a "search" bar over the layer-feature so you can find your layer (if you know the name).

### Additional context

Since i use the "select-multi-layer"-Plugin, i am able to see which Layers are on my curent canvas. But sometimes i need realy long, to find the layers.

**Comment by uclaros** [comment]
fyi, you can use the _Locator_ bar (ctrl+k) and type `l mylayername` to quickly locate _mylayername_ in the table of contents :)
