### ISSUE TITLE
Circle Shape Digitizing tool does not work as expected when map crs != layer crs

### ISSUE THREAD

**Issue by YoannQDQ** [qgis/QGIS#51926]
Duplicates #38493

### What is the bug or the crash?

When the layer CRS is different from the map canvas crs, the Circle Shape Digitizing tool produces incorrect results.

![circle](https://user-images.githubusercontent.com/9693475/219951403-2c8214e3-4dd1-4bb3-9bff-080215e83953.gif)

The Ellipse and polygon tools work as expected though.

### Steps to reproduce the issue

- Create a new project
- (Optionaly add a basemap)
- Set the CRS to EPSG:3857
- Create a new Temporary Scratch Polygon Layer, with EPSG:4326
- Edit the polygon layer
- Display the "Shape Digitizing Toolbar"
- Add a new feature
- In the Shape Digitizing Toolbar, select any of the "Circle" option
- Draw the shape

### Versions

QGIS version
3.29.0-Master
QGIS code revision
994da50a64
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.0dev-986b841325
Running against GDAL/OGR
3.7.0dev-a828b2b5a9
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by baswein** [comment]
Unfortunately this is a longstanding known issue with consequences for all arcs. https://github.com/qgis/QGIS/issues/25167

**Comment by baswein** [comment]
Also see this discussion that goes into a lot more detail. https://github.com/qgis/QGIS/issues/38493

**Comment by YoannQDQ** [comment]
My bad, I forgot to look for similar bugs before posting this... #38493 should be the one kept open though, as #25167 does not provide much information.
