### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by SafariLou** [qgis/QGIS#51946]
### What is the bug or the crash?

QGIS keeps crashing on startup. Splash screen appears, with the status message "Setting up the GUI". About 10-20 seconds later this crash screen appears.
This install of QGIS runs with a Postgres backend on a separate server. Everything was working with it until we had to physically move the QGIS machine to a different place, which involved shutting it down and restarting it.
There are a lot of complicated layers and maps, and I can't afford to lose any of it so I haven't tried updating the software yet

I have tried:
 - rebooting
 - deleting contents of the QGIS folders under AppData
 - checking postgres is reachable via telnet on port 5432

### Steps to reproduce the issue

Attempt to start GQIS

### Versions

3.16
![image](https://user-images.githubusercontent.com/125936120/220224168-df20695a-5916-41fe-a818-17f8a011c555.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

## User Feedback

QGIS keeps crashing on startup. Splash screen appears, with the status message "Setting up the GUI". About 10-20 seconds later this crash screen appears.
This install of QGIS runs with a Postgres backend on a separate server. Everything was working with it until we had to physically move the QGIS machine to a different place, which involved shutting it down and restarting it.
There are a lot of complicated layers and maps, and I can't afford to lose any of it

I have tried:
 - rebooting
 - deleting contents of the QGIS folders under AppData
 - checking postgres is reachable via telnet on port 5432

## Report Details

**Crash ID**: [ed2abba8b854cefbfc03495518d468759b44361c](https://github.com/qgis/QGIS/search?q=ed2abba8b854cefbfc03495518d468759b44361c&type=Issues)

**Stack Trace**
<pre>
GDALRegister_GRIB :
GDALAllRegister :
QgsApplication::applyGdalSkippedDrivers :
QgsApplication::registerGdalDriversFromSettings :
QgsProcessingModelOutput::toVariant :
RtlRunOnceExecuteOnce :
InitOnceExecuteOnce :
__crtInitOnceExecuteOnce winapisupp.cpp:225
QgsProcessingModelOutput::toVariant :
QgsRasterIdentifyResult::operator= :
QgsRasterIdentifyResult::error :
QgsProviderRegistry::init :
QgsProviderRegistry::QgsProviderRegistry :
QgsProviderRegistry::instance :
QgsApplication::initQgis :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.16.3-Hannover
QGIS code revision: 94ac9f21b8
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by nicogodet** [comment]
3.16.3 is EOL, retry on supported version LTR: 3.22.16 but preferably 3.28.3 (next LTR)

**Comment by DelazJ** [comment]
> There are a lot of complicated layers and maps, and I can't afford to lose any of it so I haven't tried updating the software yet

You can make a copy of the project file and open it with a newer QGIS version, installed on that same machine (next to 3.16) or on another one...
