### ISSUE TITLE
HEIF/HEIC image support for Processing -> Import geotagged photos

### ISSUE THREAD

**Issue by shuckc** [qgis/QGIS#51961]
### Feature description

The workflow for importing geotagged photos as a points (as described at https://opengislab.com/blog/2020/8/23/mapping-and-viewing-geotagged-photos-in-qgis) works great for JPG/JPEG files.

It would be great to expand this to handle HEIF (*.heic) files as exported from recent iPhones. I see that [`libheif`](https://github.com/strukturag/libheif) is the go-to C library for parsing, and that GDAL.org 3.2 or above [includes support for reading metadata](https://gdal.org/drivers/raster/heif.html) using `libheif` already.

It looks like some minor changes to  https://github.com/qgis/QGIS/blob/32c2cea54cb92bbb2243b222816c8154c2b9adf9/src/analysis/processing/qgsalgorithmimportphotos.cpp to pass in additional file extension through to GDAL, and to parse the appropriate metadata fields might make this work.

### Additional context

I will attempt this locally, if I can make it work I will open a PR.

**Comment by TimYang-jpg** [comment]
Trying to use this with QGIS version 3.42.1 but doesn't seem to be able to import HEIC files, I get a 'could not open' error in the log
