### ISSUE TITLE
QGIS Firenze crashes immediately

### ISSUE THREAD

**Issue by Ninageonovation** [qgis/QGIS#51963]
### What is the bug or the crash?

Crash ID: [62c06df51ba84c32376002e25009cb4640285a25](https://github.com/qgis/QGIS/search?q=62c06df51ba84c32376002e25009cb4640285a25&type=Issues)

Stack Trace

QNetworkAccessManager::cookieJar :
QgsNetworkAccessManager::setupDefaultProxyAndCache :
QgsNetworkAccessManager::instance :
QgsNetworkContentFetcher::fetchContent :
QgsNetworkContentFetcherTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

1. Open QGIS Firenze 3.28.3
2. The "Uh-oh!" opens immediately. I don't see anything else. 
![image](https://user-images.githubusercontent.com/80698170/220412064-549f9c31-ed7b-468d-abc2-49f58e9f79d1.png)
3. Reloading doesn't work to fix this issue. 

### Versions

3.28.3-Firenze

and

3.26.2-Buenos Aires

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

The only version that works on my desktop right now is QGIS 3.26.2. 
When starting this version, the  "Uh-oh!" screen opens as well. However QGIS still starts to work. This version works okay. But the vector processing tools cannot be opened. 
![image](https://user-images.githubusercontent.com/80698170/220413150-2ee78e3c-33ff-42af-9aae-ea75626ea552.png)

**Comment by DelazJ** [comment]
@Ninageonovation could you try with a new QGIS [user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), please?

**Comment by Ninageonovation** [comment]
Thanks! I did not expect this to work, but it did 👍
