### ISSUE TITLE
Crash when copy paste legend item in map composer

### ISSUE THREAD

**Issue by bwwjohnson** [qgis/QGIS#51976]
## User Feedback

I was in the map composer. In the items tab I copied and pasted a legend item and QGIS pasted it and then crashed directly after

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003440 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsLayerTreeModel::node2index :
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::layerLegendChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsRasterLayer::refreshRenderer :
QgsRasterLayer::refreshRendererIfNeeded :
QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererCustomPainterJob::startPrivate :
QgsLayoutItemMap::recreateCachedImageInBackground :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Load elevation model, polygons, line. Open map composer, set grid to crosses 400mx400m in UTM 42N. Created legend using elevation color bar by deleting all legend items but the DEM. Format by changing spacing options and removing a label by replacing it with a " ". In items bar, select legend item, ctrl-C to copy and ctrl-V to paste. The item pastes and then QGIS crashes.

### Versions

3.28.3 Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I wasn't using any special plugins at the time but had plugins installed.

**Comment by roya0045** [comment]
Just to be clear, you meant to copy the legend itself or the dem layer in the legend?

**Comment by agiudiceandrea** [comment]
@bwwjohnson please try if the issue does occur using a new QGIS user profile. If yes, please provide sample project and layer(s) in and exact steps in order to replicate the issue.
