### ISSUE TITLE
Repeated name display on map need to unique

### ISSUE THREAD

**Issue by narendraneeraj** [qgis/QGIS#51992]
### Feature description

Dear QGIS Team,

As attached snapshot, multiple/duplicate name showing in QGIS, need to remove duplicate name.

BR//

![MicrosoftTeams-image](https://user-images.githubusercontent.com/12167906/220829962-7f1493c2-3a58-4d4d-9c5f-c0cd7e8f790d.png)

**Comment by agiudiceandrea** [comment]
@narendraneeraj, are you asking for instructions? Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/.

**Comment by YoannQDQ** [comment]
Do you mean something like ArcGIS' [remove-duplicate-labels-within-a-given-radius](https://pro.arcgis.com/en/pro-app/latest/help/mapping/text/remove-duplicate-labels-within-a-given-radius.htm) feature?
