### ISSUE TITLE
The Vector bar does not work 

### ISSUE THREAD

**Issue by cosminacst** [qgis/QGIS#52002]
### What is the bug or the crash?

The Vector components do not appear. I reinstalled QGIS 3 times and it didn't fix it. I didn't do anything special, it just didn't work in one day

### Steps to reproduce the issue

**This is the Vector bar that does not appear** --->   ![Screenshot 2023-02-23 141624](https://user-images.githubusercontent.com/126165681/220903119-34a7f1af-63f8-4f63-828b-a6dce4379dee.png).

**The others work** ---> 

![Screenshot 2023-02-23 141810](https://user-images.githubusercontent.com/126165681/220903542-b135e1f9-8b7b-46ba-a41a-28c34e6cb55e.png)
![Screenshot 2023-02-23 141801](https://user-images.githubusercontent.com/126165681/220903548-5fda069a-fe07-4173-b238-42623bc669b5.png)

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
google_maps_geocoder
0.0.3
openlayers_plugin
2.0.0
quick_map_services
0.19.32
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99
VectorBender
0.2.1

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Is the processing plugin active/enabled?

**Comment by cosminacst** [comment]
Yap, that was it =))) I'm an idiot, sorry
thank you very much
