### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by SSiline** [qgis/QGIS#52008]
## User Feedback

Trying to connect to MySQL database to get the geometry table that contents 2000 rows. 

## Report Details

**Crash ID**: [869b4e97c76a40d98c9792abdd0d83eea453625f](https://github.com/qgis/QGIS/search?q=869b4e97c76a40d98c9792abdd0d83eea453625f&type=Issues)

**Stack Trace**
<pre>
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
QgsOgrProviderUtils::GDALOpenWrapper :
QgsMeshMemoryDataProvider::splitMeshSections :
QgsVectorLayer::extent :
QgsMapLayerUtils::combinedExtent :
QgsProjectViewSettings::fullExtent :
QgsMapCanvas::projectExtent :
QgsMapCanvas::zoomToProjectExtent :
QgsLayerTreeMapCanvasBridge::setCanvasLayers :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::dataSourceManager :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.15-Bia?owie?a
QGIS code revision: ef17ad14
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by nicogodet** [comment]
Did you try with a new profile ?

Provide steps to reproduce or even better a sample project and data to reproduce.
