### ISSUE TITLE
constantly crashing

### ISSUE THREAD

**Issue by Wendreda** [qgis/QGIS#52000]
### What is the bug or the crash?

QGIS keeps crashing if I try to close the map I'm working on. I have no idea what the error message means!
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

try and close a project.

### Versions

3.10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
First update your qgis and then create a ticket. 3.10 is old and information are missing.
