### ISSUE TITLE
Collapse legend item with deleted layer name

### ISSUE THREAD

**Issue by bkepl** [qgis/QGIS#52006]
### Feature description

I will often have several symbologies on a layer so I don’t need to include that layer in my map several times over. If I select one symbology to display in the legend, it would be nice if I wasn’t forced to also include the name of the layer on the line above, or if I delete the layer name, an empty space remains in the legend for the layer name. It would be nice if that space would collapse to zero height if I removed the layer name in the legend.

**Comment by roya0045** [comment]
...right clic - hidden, this is already doable.

**Comment by bkepl** [comment]
> ...right clic - hidden, this is already doable.

Really? As of a recent update? I almost always find these little right-click gems, but this one I haven't run across, yet. Thank you!

**Comment by roya0045** [comment]
> > ...right clic - hidden, this is already doable.
> 
> Really? As of a recent update? I almost always find these little right-click gems, but this one I haven't run across, yet. Thank you!

years... I'm pretty sure this can be closed as it would duplicate somethign already present.

**Comment by bkepl** [comment]
> years... I'm pretty sure this can be closed as it would duplicate somethign already present.

How annoying. I almost always discover stuff like this. Yes, I'll close this.

**Comment by YoannQDQ** [comment]
Yes, this is already implemented.
