### ISSUE TITLE
QGIS won´t load delimited text layers

### ISSUE THREAD

**Issue by Rupicolus89** [qgis/QGIS#52016]
### What is the bug or the crash?

Hello, I have a problem with projects created in QGIS. I added a few delimited text layers each containing tens of points with coordinates and attributes, saved the project file. In one of such projects, we use the atlas layout function to create maps showing these points with WMS layer background in places around the country.
Problem:
after a project is finished, saved, and loaded into QGIS the other day (or next time), opening the project it displays the layers are unavailable, altough the text files locations did not change in the PC storage. The "auto-find" won´t find them, the "repair data source" window doesn´t show any .txt files anywhere at all. The original link to the text file seems to be broken - looks sometimes like it is repeated over and over at the bottom of the reapir data source window.
It occurs on a windows 7 with 3.28.3 , and a windows 10 PC with QGIS 3.28.2,. Seems to work fine on an install of QGIS v. 3.18 but no plugins load into v3.18. 
The repair data source window is slowing the PCs performance down under these circumstances, one blue screen crash occured when using it.
As it occurs with project files used across different QGIS versions, we made a new project with newest QGIS 3.28.3, seemed to work fine for a few hours, but other day starting the project, these layers were lost - again the same problem. 
Attempted changing the file names to contain no spaces, also started QGIS as administrator - guessed it could get better access to files, didn´t improve.
I have been using text separated by tabs, containing characters from Slovak language in QGIS for years, and I remember this bug occuring only for a month or two, since v. 3.28. The only workaround now is to add the delimited txt as a new layer.
[BA_kraj_GIS_j.txt](https://github.com/qgis/QGIS/files/10824313/BA_kraj_GIS_j.txt)

### Steps to reproduce the issue

create new project
Add the delimited text (sample attached to this report) as a new layer (using vice versa Y and X coordinates in EPSG:5514)
save project
exit QGIS
open QGIS
load project
layers not available, auto-find won´t find their data source, browser won´t show .txt files, eventually windows crashes
workaround is to add the layers again

### Versions

3.28.2 3.28.3 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Maybe related to https://github.com/qgis/QGIS/issues/48587 ? 

Can you check if the patch for that bug fixes this one too?

Download for windows here: https://github.com/qgis/QGIS/actions/runs/4185753524

**Comment by agiudiceandrea** [comment]
@Rupicolus89 could you please specify what this the encoding of the text and what is the delimiters of the fields? could you please check if the issue does occur also using a new QGIS user profile?

**Comment by Rupicolus89** [comment]
The text file is separated by Tab. 
Encoding is Windows-1250.
Discard one header line. Check first record has field names. I add a screenshot below.

![Snímka](https://user-images.githubusercontent.com/126252657/221515385-186ae7cd-8d2b-4a92-acab-2797df4298b3.PNG)

**Comment by agiudiceandrea** [comment]
@Rupicolus89, it seems to me the issue doesn't occur on my Windows system using QGIS 3.28.3.

https://user-images.githubusercontent.com/16253859/221542966-e6dd6892-e000-4fb0-90b8-b4838f3fedea.mp4

Could you please try using a new QGIS user profile?

**Comment by Rupicolus89** [comment]
The new user profile didn´t fix the issue on 3.28.3

**Comment by Rupicolus89** [comment]
We use a small wired network with a few PC, printers and a server for file storage and internet access. We had the project .qgz file on the server, so attempting to fix this, we copyied the .qgz and all things needed onto offline PC disc storage.
It didn´t fix the delimited text layer loading bug, but may be these network connections cause the problem?
We are updating to the new v. 3.30

**Comment by agiudiceandrea** [comment]
@Rupicolus89 please report back if the issue does or doesn't occur using QGIS 3.30.0. If it does occur, please provide the QGIS project file, exact steps and any other info in order to reproduce the issue.
