### ISSUE TITLE
jpeg2000's show artefacts

### ISSUE THREAD

**Issue by KOENVDW0** [qgis/QGIS#52012]
### What is the bug or the crash?

I'm working for a company that makes orthomosaics based on aerial data. We use FME to make jpeg2000's.
When loading in a jpeg2000 it shows weird artefacts when zoomed in (1:200), after zooming out past a certain level the artefacts disappear. 
We and our customers encounter this problem when using the .msi insallers of Qgis. When we use the .exe installer there is no issue. It's a pity that the latest release with .exe installer is 3.18.3-1. 

artefacts:
![100](https://user-images.githubusercontent.com/126246245/221170457-07fa93b1-0dc4-47c4-8f12-db9a1b346204.png)

specifications of the jpeg2000 in Qgis:
![200](https://user-images.githubusercontent.com/126246245/221170533-48b2298a-9a04-4771-b830-cb95084e17bf.png)

Can the .exe installers come back or can the issue be resolved?

### Steps to reproduce the issue

1 download a jpeg2000 made in FME or make one yourself in FME (didn't test other ones)
2 load the jpeg2000 in Qgis
3 zoom in past 1:200
4 pan around the artefacts should appear

### Versions

QGIS-versie
3.28.0-Firenze
QGIS code revisie
ed3ad0430f3
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.5.2
PROJ versie
9.1.0
EPSG-register databaseversie
v10.074 (2022-08-01)
GEOS versie
3.10.3-CAPI-1.16.1
SQLite versie
3.39.4
PDAL versie
2.4.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
deactivate_active_labels
0.5
GeometryShapes
0.7
geopunt4Qgis
2.2.9.1
group_transparency
0.2
LAStools
1.4
Obliquo webapp
0.1
QChatGPT
0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@KOENVDW0 could you please check if the issue does occur using the latest supported QGIS version (QGIS 3.28.3, which is shipped on Windows with GDAL 3.6.2 and ERDAS JPEG2000 SDK 5.5)? Could you please provide a sample JPEG2000 layer that shows the issue?
