### ISSUE TITLE
Measure Tool does not report in correct units

### ISSUE THREAD

**Issue by TRatNECS** [qgis/QGIS#52018]
### What is the bug or the crash?

I set the preferred distance units as "Feet" in Options, but when I use the Measure tool, it always begins in meters.

I can change the units and get correct results with the measure tool, but I have to change it every time. It appears that the options setting is not working. This has worked in the past.

### Steps to reproduce the issue

Go to Settings, Options
Click on Map Tools
Set the preferred distance units to "Feet"
Click OK
Click on Measure Line in the Attributes toolbar
The units are reported in meters

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
ImportPhotos
3.0.5
mmqgis
2021.9.10
profiletool
4.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
The general setting only affects newly created projects.
To change the default distance unit for your current project, go to Project/Properies/General/Measurements and change the setting there.

If this solves your issue, please close it :)
