### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by abhi8272** [qgis/QGIS#52023]
### What is the bug or the crash?

Windows fatal exception: access violation

Current thread 0x00002930 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
![gis](https://user-images.githubusercontent.com/126350950/221373293-9703faae-18f7-4f7e-8f06-8c3b8b6bead0.jpg)

### Steps to reproduce the issue

Windows fatal exception: access violation

Current thread 0x00002b94 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.2
Running against GDAL: 3.4.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.5
FreehandRasterGeoreferencer
0.8.3
HCMGIS
22.7.20
quick_map_services
0.19.29
SemiAutomaticClassificationPlugin
7.10.6
spectral_libraries
1.1.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
![as](https://user-images.githubusercontent.com/126350950/221373545-303fe299-df50-45e9-9fc1-2efdb34eb329.jpg)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I can`t open qgis properties and can`t change any option .

**Comment by agiudiceandrea** [comment]
@abhi8272 your are using an old and no longer supported version of QGIS. Please actually try if the issue occurs using a supported QGIS version according to the roadmap and actually with a new QGIS user profile.

**Comment by agiudiceandrea** [comment]
@abhi8272 thanks for reporting the issue, anyway your are using an old and no longer supported version of QGIS. Please actually try if the issue occurs using a supported QGIS version according to the roadmap and actually with a new QGIS user profile.
