### ISSUE TITLE
'Additional c++ plugin paths' list doesn't support more than one entry

### ISSUE THREAD

**Issue by c-marcel** [qgis/QGIS#52041]
### What is the bug or the crash?

In **Preferences > Options > System** the **Additional paths for c++ plugins** list doesn't support more than one path. The GUI permits to define many paths but c++ plugins are no more loaded by QGis in this case.

### Steps to reproduce the issue

1. Go to **Preferences > Options > System**, in the **Additional paths for c++ plugins** list, and add a path containing a valid c++ QGis plugin.
2. Open Extensions dialog and activate the plugin.
3. At restart the plugin is successfully loaded.
4. If the list contains more than one entry (even if the 2 entries are the same) the plugin is no more loaded when QGis is starting and is not displayed into the Extensions dialog.

### Versions

Windows 3.22.16-1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@c-marcel, thanks for reporting. I've submitted the Pull Request https://github.com/qgis/QGIS/pull/52047 to fix the issue. If you want, you can test the fix using the QGIS for Windows build artifact available at https://github.com/qgis/QGIS/actions/runs/4292059074.
