### ISSUE TITLE
projection corrupt when exporting mif files

### ISSUE THREAD

**Issue by Sorche** [qgis/QGIS#52049]
### What is the bug or the crash?

When I output a shape as a mif file, there is some information missing from the projection data so the files is mispositioned when loaded.
The projection reads:
CoordSys Earth Projection 8, 104, "m", -2, 49, 0.9996012717, 400000, -100000
When I am expecting it to read:
CoordSys Earth Projection 8, 79, "m", -2, 49, 0.9996012717, 400000, -100000 Bounds (-7845061.1011, -15524202.1641) (8645061.1011, 4470074.53373)

Outputshape files from the same project are correctly positioned. 

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/75370871/221873317-23f558c2-dab6-4193-bc45-7dfc4bcfc79d.png)

### Versions

QGIS version
3.22.3-Białowieża
QGIS code revision
1628765ec7
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.0-CAPI-1.16.0
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
crayfish
3.6.0
plugin_reloader
0.9.1
pointsamplingtool
0.5.3
profiletool
4.2.1
quick_map_services
0.19.27
tuflow
3.1.10
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I am running QGIS from a work machine so have no control over version used

**Comment by agiudiceandrea** [comment]
@Sorche, please try if the issue does occur also using the latest currently supported QGIS version and provide a sample layer to replicate the issue. Please read the GDAL/OGR documentation about the way the MapInfo format https://gdal.org/drivers/vector/mitab.html is supported in QGIS via GDAL/OGR.

**Comment by Sorche** [comment]
Hello

I am sorry, but I don't have access to any other version of QGIS as this is
all controlled by my company. Thank you for the suggestion though.

**Comment by agiudiceandrea** [comment]
@Sorche please provide a sample layer to replicate the issue.

**Comment by Sorche** [comment]
Is this what you need? The shape file is in the correct position, the mif
file is missing some information from the projection.

**Comment by DelazJ** [comment]
@Sorche You can not add files while replying from your webmail client. You need to do it from within Github itself
