### ISSUE TITLE
Upgrade Python version and reinstall QGIS result in Python Error

### ISSUE THREAD

**Issue by adam-sal** [qgis/QGIS#52050]
### What is the bug or the crash?

Recently, i installed additional Python 3.8.15 version on my Ubuntu 20.04.` python3 --version` results in `Python 3.8.15`. The path of this version of python is: /usr/local/bin/python3 .It is set as default python3 version. Unfortunately, I've run into problems with QGIS ever since. I decided to reinstall QGIS. During QGIS launching, no module named 'qgis' error occured like on the printscreen below: 
![CFlUy](https://user-images.githubusercontent.com/77227150/221883332-d366d009-06e1-4793-a60f-389f641d7ef7.png)

I know that the source of the problem is that i overwrote the default Python version on the Ubuntu 20.04, but i tried to add the default Python (3.8.10) to the PYTHON_PATH / PYTHON_HOME and it results in other error:

`asalach@asalach-lap:/bin$ qgis`
`Python path configuration:`
`PYTHONHOME = '/bin/python3'`
`PYTHONPATH = '/bin/python3'`
`program name = 'python3'`
`isolated = 0`
`environment = 1`
`user site = 1`
`import site = 1`
`sys._base_executable = '/usr/local/bin/python3'`
`sys.base_prefix = '/bin/python3'`
`sys.base_exec_prefix = '/bin/python3'`
`sys.executable = '/usr/local/bin/python3'`
`sys.prefix = '/bin/python3'`
`sys.exec_prefix = '/bin/python3'`
`sys.path = [
    '/bin/python3',
    '/bin/python3/lib/python38.zip',
    '/bin/python3/lib/python3.8',
    '/bin/python3/lib/python3.8/lib-dynload',
  ]`
`Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding`
`Python runtime state: core initialized`
`ModuleNotFoundError: No module named 'encodings'`

`Current thread 0x00007f7600a29540 (most recent call first):`
`<no Python frame>`
`QGIS died on signal 11gdb returned 139`
`

Of course, i am able to import encodings module from both version of Python (default - 3.8.10 and alternative 3.8.15).

Has anyone encountered such a problem?

### Steps to reproduce the issue

1. Go to settings and add new env called 'PYTHONPATH' and 'PYTHONHOME' and reference them to the default system python version - 3.8.10
2. Launch QGIS from terminal
3. See error 
`Fatal Python error: init_fs_encoding: failed to get the Python codec of the filesystem encoding`
`Python runtime state: core initialized`
`ModuleNotFoundError: No module named 'encodings'`

### Versions

QGIS version 3.26.3-Buenos Aires
QGIS code revision 65e4edfdad
Qt version 5.12.8
Python version 3.8.10
GDAL/OGR version 3.4.3
PROJ version 8.2.0
EPSG Registry database version v10.038 (2021-10-21)
GEOS version 3.10.2-CAPI-1.16.0
SQLite version 3.31.1
PDAL version 2.2.0
PostgreSQL client version 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version 5.0.1
QWT version 6.1.4
QScintilla2 version 2.11.2
OS version
Ubuntu 20.04.5 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I searched many posts and tried the following:
- add new python version to PYTHONPATH;
- delete my user profile in QGIS;
- uninstall PyQT5.

Unfortunately none of them solved my problem.

**Comment by m-kuhn** [comment]
You will need to either start with your system version of python or build qgis yourself with your desired version of python.
There's nothing that could be done to make qgis support a different python version than the one it was buolt against.
