### ISSUE TITLE
shortest path in tool "Netzwerkanalyse"

### ISSUE THREAD

**Issue by uwerupp** [qgis/QGIS#52053]
### What is the bug or the crash?

Crash occured after editing streetnetwork and doing a routing calculation with shortest path in tool "Netzwerkanalyse".
Crash did happen for the 4th time. 

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00000864 (most recent call first):

Stack Trace

QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

_

### Versions

QGIS Version: 3.28.1-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Is that tool from a plugin? If you try a new profile do you have it by default?

**Comment by agiudiceandrea** [comment]
@uwerupp if the tool is not a plugin, but a processing algorithm, please provide the English name of the algorithm or the algorithm id, a sample layer and exact steps to replicate the issue. Otherwise, please try if the issue does occur also using the latest current supported QGIS version and using a new QGIS user profile.

**Comment by uwerupp** [comment]
I switched to 3.28.3 now

However the crash occurs while using the plugin processing.
It happens while saving a tmp shortest path layer into a physical json layer including the route.

The plugin processing caused QGIS to crash.
Please report this issue to the author of this plugin.


## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000034d4 (most recent call first):
  File "C:\PROGRA~1/QGIS_3.28/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 394 in executeAlgorithm
    dlg.exec_()
  File "C:\PROGRA~1/QGIS_3.28/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 234 in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
```


**Stack Trace**

```

QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QObject::qt_static_metacall :
QgisApp::activeLayerChanged :
QgisApp::onActiveLayerChanged :
QObject::qt_static_metacall :
QgsLayerTreeView::currentLayerChanged :
QgsLayerTreeView::onCurrentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgisApp::autoSelectAddedLayer :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsLayerTreeRegistryBridge::addedLayersToLayerTree :
QgsLayerTreeRegistryBridge::layersAdded :
QObject::qt_static_metacall :
QgsProject::legendLayersAdded :
QgsProject::addMapLayers :
QgsProject::addMapLayer :
QgsAppLayerHandling::addSublayers :
QgsAppLayerHandling::addOgrVectorLayers :
QgsPluginRegistry::operator= :
QgisApp::identifyMapTool :
QObject::qt_static_metacall :
QgsVectorFileWriterTask::completed :
QgsTaskManager::taskStatusChanged :
QObject::qt_static_metacall :
QgsTask::statusChanged :
QgsTask::processSubTasksForCompletion :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QMetaObject::activate :
PyInit_QtCore :
PyInit_QtCore :
PyType_GenericNew :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
PyInit__gui :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

**Comment by agiudiceandrea** [comment]
@uwerupp please provide the English name of the algorithm or the algorithm id.
Please provide a sample layer and exact steps to replicate the issue.
Could you please clarify if the crash occurs actually during the execution of the processing algorithm or when you export a temporary layer to a JSON file (as you mentioned lately)?

**Comment by uwerupp** [comment]
The plugin **processing** caused QGIS to crash.
I can not provide a sample layer, it is customer data that is not intended for public use.
This time the crash occured during exporting. 
However I had crashes that occured when I did something else. there was not the one situation where QGIS crashed.
So I can not even replicate it, it seems more or less a timing issue. 
However, by removing 10 layers from my project and keeping only 2: aerial photo and routing network, QGIS works stable.
Hence the crash might be caused in using one of the other layers and the plugin processing.
