### ISSUE TITLE
Defaults in widget cannot be set for string fields.

### ISSUE THREAD

**Issue by anjoweichbrodt** [qgis/QGIS#52061]
### What is the bug or the crash?

Defaults in widget cannot be set for string fields.

### Steps to reproduce the issue

1. Go to 'layer properties'
2. Click on 'Attributes form'
3. Click on a 'string field'
4. Set 'Default value'
5. Click ' Apply'and 'OK'
6. Repeat step 1-3 and check the 'Default value'

If the same is done with an 'integer field', the set default persists.

### Versions

3.28.3

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@anjoweichbrodt, I cannot replicate the issue on my Windows system using QGIS 3.28.3.
Could you please report the full QGIS version information as requested (QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here)?. Could you please try if the issue does occur also using a new QGIS user profile?

https://user-images.githubusercontent.com/16253859/222216368-fe4b8993-4822-4e87-98d7-a87d5c9b3ec5.mp4

**Comment by andreasneumann** [comment]
@anjoweichbrodt - can you share a small project and data source?

What provider are you using to store the data? Is it a Geopackage, PostgreSQL, ESRI Shapefile or something else?

**Comment by anjoweichbrodt** [comment]
@agiudiceandrea 

You were right. This issue does not occur anymore with a new QGIS user profile.
Sorry my bad, I should have checked this before.

Many thanks.

For completness here the info from the Help menu:


QGIS version | 3.28.3-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.9
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
Compiled against SQLite | 3.40.1 | Running against SQLite | 3.41.0
Compiled against PDAL | 2.5.0 | Running against PDAL | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.4
OS version | Arch Linux
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
