### ISSUE TITLE
I can't use QGIS Processing Executor (qgis_process.exe) on windows 10

### ISSUE THREAD

**Issue by vitor-fessel** [qgis/QGIS#52065]
### What is the bug or the crash?

Crash

### Steps to reproduce the issue

I'm working on windows 10 with OSGeo4W long term version 3.16.15. When running qgis_process.exe, I received a system error message stating "Code execution cannot continue because dll file was not found. Reinstalling the program to fix the problem."

However, I have already reinstalled the program and the message continues, even in the latest version. I looked for a solution but I didn't find it. Can you help me to get qgis_process to run?

### Versions

Versão do QGIS
3.16.15-Hannover
Código da versão do QGIS
e7fdad64
Compilado sobre Qt
5.15.2
Rodando sobre Qt
5.15.2
Compilado sobre GDAL/OGR
3.4.0
Rodando sobre GDAL/OGR
3.4.0
Compilado sobre GEOS
3.10.0-CAPI-1.16.0
Rodando sobre GEOS
3.10.0-CAPI-1.16.0
Compilado no SQLite
3.35.2
Executando contra SQLite
3.35.2
Versão do cliente PostgreSQL
13.0
Versão SpatiaLite
5.0.1
Versão do QWT
6.1.3
Versão QScintilla2
2.11.5
Compilado com PROJ
8.2.0
Em execução com PROJ
Rel. 8.2.0, November 1st, 2021
Versão SO
Windows 10 Version 2009
Ativar complementos python
LAStools; 
profiletool; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
run  qgis_process-qgis.bat / qgis_process-qgis-ltr.bat / qgis_process-qgis-dev.bat / qgis_process-qgis-ltr-dev.bat / qgis_process-qgis-rel-dev.bat

**Comment by vitor-fessel** [comment]
hey jef-n, thanks. Unfortunately it didn't solve the problem. I managed to run only the "run qgis_process-qgis.bat", but it presented the same error of missing the same dll file...

**Comment by meyerlor** [comment]
same for me, is there any solution/workaround for that ?
