### ISSUE TITLE
Browser very slow when a KML file comes into view

### ISSUE THREAD

**Issue by lnicola** [qgis/QGIS#52075]
### What is the bug or the crash?

What the title says. `strace` shows the file being read. Similar to #51595.

### Steps to reproduce the issue

1. Download https://www.townofboothbay.org/sites/g/files/vyhlif311/f/pages/boothbay2018.kmz
2. Unzip it (22 MB)
3. Scroll around the directory where the file is extracted

### Versions

QGIS version | 3.28.3-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.10.9
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
Compiled against SQLite | 3.40.1 | Running against SQLite | 3.41.0
Compiled against PDAL | 2.5.0 | Running against PDAL | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.13.4
OS version | Arch Linux
  |   |   |  
Active Python plugins
QuickWKT | 3.1
Coregistration | 22.5.19
QuickOSM | 2.1.1
temporalprofiletool | 2.1.2
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.3-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.8
Python version
3.10.9
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
Compiled against SQLite
3.40.1
Running against SQLite
3.41.0
Compiled against PDAL
2.5.0
help I'm trapped in a badly-formatted version table, can anyone hear me?
Running against PDAL
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.13.4
OS version
Arch Linux

Active Python plugins
QuickWKT
3.1
Coregistration
22.5.19
QuickOSM
2.1.1
temporalprofiletool
2.1.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

This might be fixed in GDAL, but it might be a good idea to only re-read the datasets when something changes, or the user hits Refresh.

I don't have a QGIS build with proper symbols around, but here's a stack trace:

```
#0  0x00007fe25e7d1ba8 in GDALOpenEx () at /usr/lib/libgdal.so.32
#1  0x00007fe261999c4b in  () at /usr/lib/libqgis_core.so.3.28.3
#2  0x00007fe26195d201 in  () at /usr/lib/libqgis_core.so.3.28.3
#3  0x00007fe261c5e206 in QgsFileDataCollectionItem::databaseConnection() const () at /usr/lib/libqgis_core.so.3.28.3
#4  0x00007fe26623c4ec in  () at /usr/lib/libqgis_app.so.3.28.3
#5  0x00007fe265355a6d in QgsBrowserGuiModel::flags(QModelIndex const&) const () at /usr/lib/libqgis_gui.so.3.28.3
#6  0x00007fe26326e2af in QSortFilterProxyModel::flags(QModelIndex const&) const () at /usr/lib/libQt5Core.so.5
#7  0x00007fe2632592fe in QItemSelection::contains(QModelIndex const&) const () at /usr/lib/libQt5Core.so.5
#8  0x00007fe263259860 in QItemSelectionModel::isSelected(QModelIndex const&) const () at /usr/lib/libQt5Core.so.5
#9  0x00007fe26427a218 in QTreeView::drawRow(QPainter*, QStyleOptionViewItem const&, QModelIndex const&) const () at /usr/lib/libQt5Widgets.so.5
```

**Comment by hadallen** [comment]
also having the same issue on archlinux with 3.28.3. my coworkers on windows do not suffer from the same slowdowns

**Comment by agiudiceandrea** [comment]
It seems to me the issue occurs using QGIS 3.28.3 on Windows, too.

**Comment by lnicola** [comment]
For completeness, @hadallen is using LIBKML, while I'm using the KML driver.

**Comment by hadallen** [comment]
I just tested installing LTR version QGIS 3.22.16 'Białowieża' on Windows and the slowness is completely gone

**Comment by hadallen** [comment]
further testing shows that 3.26.3 has no slowdown, whereas 3.28.0 does
