### ISSUE TITLE
QGIS Crashes frequently when I try to delete something from a duplicated map layout. 

### ISSUE THREAD

**Issue by boonits** [qgis/QGIS#52079]
## User Feedback

This happens frequently. When I duplicate a map, and then try to delete anything from the copy (i.e., a polyline, some text), it's a coin toss if it crashes or not. 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003628 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.3-Firenze
QGIS code revision: c12bcb2f76c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

1. Create a map
2. Add polylines, legends, text etc.
3. Duplicate the map
4. Open duplicated map
5. Try to delete something (e.g.,, a polyline)
6. QGIS crashes

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Thanks for reporting. Have you tried if the issue doues occur also using a new QGIS user profile? Please provide a sample project and layer(s) with which the issue does occur.

**Comment by thbaumann** [comment]
The bug still exists (testet up to QGIS 3.32 ) 
1. open the attached sample project
[testproject.zip](https://github.com/qgis/QGIS/files/12231303/testproject.zip) 
3. duplicate the print layout
4. in the opened duplicated layout zoom in ( ! )
5. click on the textfield with the content "DELETE ME" and delete it
6. QGIS crashes

![grafik](https://github.com/qgis/QGIS/assets/20082727/4fe92d60-04c2-474a-bd2f-bfd65e832f47)

**Comment by nyalldawson** [comment]
This is almost certainly https://bugreports.qt.io/browse/QTBUG-58501

**Comment by Mozlo** [comment]
soooooo....... did we get a solution?

**Comment by nyalldawson** [comment]
@Mozlo this is fixed, just upgrade to a newer version
