### ISSUE TITLE
line on no layer but showing

### ISSUE THREAD

**Issue by tvoide** [qgis/QGIS#52087]
### What is the bug or the crash?

I have a line on my file that wouldn't go even when all layer are turn of. 
Does anyone have an idea? 

### Steps to reproduce the issue

<img width="1305" alt="Capture d’écran 2023-03-03 à 11 16 14" src="https://user-images.githubusercontent.com/94082598/222694397-26f8252c-be64-4e0d-8032-f0c5ab76a4d6.png">

### Versions

3.26.3

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Looks like it's a line on the Main annotation layer. You can use the _Annotations toolbar_ to select or modify it.

However, I consider having a magic invisible annotations layer automatically created as a bug, as it's easy to confuse users, so I'm keeping this open :)

**Comment by tvoide** [comment]
Thank you so much. It workedI
I'm still not really experimented with qgis and couldn't find the solution on google!

**Comment by stev-0** [comment]
@tvoide maybe close the issue in that case
