### ISSUE TITLE
Application start on MacOS Catalina (10.15.7)

### ISSUE THREAD

**Issue by wbelau** [qgis/QGIS#52097]
### What is the bug or the crash?

Version 3.28.3 does not start on MacOS Catalina.

### Steps to reproduce the issue

![Bildschirmfoto 2023-03-04 um 21 15 28](https://user-images.githubusercontent.com/12737700/222927354-80672acb-2ad7-4a47-8bff-ac61bf5e3235.png)

### Versions

Version 3.28.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@wbelau have you read and followed the instructions in the [download page](https://qgis.org/en/site/forusers/download.html) for macOS?

> macOS High Sierra (10.13) or newer is required. QGIS is not yet notarized as required by macOS Catalina (10.15) security rules. On first launch, please right-click on the QGIS app icon, hold down the Option key, then choose Open.

![image](https://user-images.githubusercontent.com/16253859/215084538-0218a2d5-1829-4332-881a-0da6c433879d.png)

If those instructions don't work, please try:
- right click on the icon in menu -> Open -> Open
or
- follow the advise at https://support.apple.com/it-it/guide/mac-help/mchleab3a043/mac: in Finder locate the app then Control-click the app icon -> Open -> Open
or
- follow the advise at https://support.apple.com/en-gb/HT202491

**Comment by wbelau** [comment]
I followed your instructions. The following message is shown (German language):
QGIS.app kann nicht geöffnet werden, da Apple darin nicht Schadsoftware suchen kann. Diese Software muss aktualisiert werden. Wende dich an den Entwickler, ...


You need a translation?

**Comment by agiudiceandrea** [comment]
@wbelau have you tried all the methods?

**Comment by wbelau** [comment]
Locating the app with finder and command open the app will lead to the same error message. 

... the software needs to be updated. Contact developer ...

**Comment by wbelau** [comment]
Initial start QGIS 3.30 (release candidate).
New error message window:

TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool' 
Traceback (most recent call last):
  File "/Applications/QGIS.app/Contents/MacOS/../Resources/python/qgis/utils.py", line 423, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/__init__.py", line 66, in classFactory
    return SemiAutomaticClassificationPlugin(iface)
  File "/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/semiautomaticclassificationplugin.py", line 297, in __init__
    cfg.SCPD = SCPDock()
  File "/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/SemiAutomaticClassificationPlugin/dock/scpdock.py", line 46, in __init__
    cfg.rbbrBnd = cfg.qgisGuiSCP.QgsRubberBand(cfg.cnvs, False)
TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'


Python-Version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS-Version: 3.30.0-'s-Hertogenbosch 's-Hertogenbosch, f186b8efe0 

Python-Pfad:
/Applications/QGIS.app/Contents/MacOS/../Resources/python
/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python
/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins
/Applications/QGIS.app/Contents/MacOS/../Resources/python/plugins
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/statsmodels-0.11.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/rasterio-1.1.5-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/patsy-0.5.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/netCDF4-1.5.4-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Rtree-0.9.7-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/opencv_contrib_python-4.3.0.36-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/GDAL-3.3.2-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/cftime-1.2.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Fiona-1.8.13.post1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/lib-dynload
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/matplotlib-3.3.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numba-0.50.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python39.zip
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/numpy-1.20.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/geopandas-0.8.1-py3.9.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pandas-1.3.3-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/scipy-1.5.1-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/Pillow-7.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Applications/QGIS.app/Contents/MacOS/lib/python3.9/site-packages/pyproj-3.2.0-py3.9-macosx-10.13.0-x86_64.egg
/Users/wolfgangbelau/Library/Application Support/QGIS/QGIS3/profiles/default/python

**Comment by wbelau** [comment]
SemiAutomaticClassificationPlugin seems to have a problem.

**Comment by agiudiceandrea** [comment]
@wbelau it seems you have managed to successfully launch QGIS.
The Semi-Automatic Classification Plugin issue has to be reported to the plugin developers.
