### ISSUE TITLE
[OSGeo4W] network installer Splashscreen QGIS 3.28.4

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#52092]
### What is the bug or the crash?

I just upgraded and installed the new QGIS 3.28.4 and 3.30, QGIS 3.28.4 splashscreen does not have long term release written on red background

fd0fb72ab3

Thanks so much

![image](https://user-images.githubusercontent.com/7631137/222886747-09aecbf8-7a86-4426-81ce-0a125e4d4776.png)

### Steps to reproduce the issue

-

### Versions

fd0fb72ab3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

https://trac.osgeo.org/osgeo4w/ticket/777#ticket

**Comment by agiudiceandrea** [comment]
It seems to me it is fixed now with qgis-ltr 3.28.4-2.

**Comment by jef-n** [comment]
Fixes in 6f669a22ac276d11fcbf1ff0c80f06b4f4380408

**Comment by pigreco** [comment]
![image](https://user-images.githubusercontent.com/7631137/222923300-e95168f8-d749-41df-bdfa-c6e3fbbe7c13.png)

Thanks so much
