### ISSUE TITLE
crash in legend editing

### ISSUE THREAD

**Issue by gizmogizmogizmo** [qgis/QGIS#52108]
## User Feedback

Renaming the legend in map layout mode.
The legend showed only elements included in the map.
The layout had one map, one scale and the format was A1 upright.
The project had only .shp files in it, the project itself had no problems loading, but working in legend editing slowed it down to taking a minute to type a word.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002e34 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QByteArray::QByteArray :
QgsPanelWidgetStack::mouseReleaseEvent :
QgsPanelWidgetStack::closePanel :
QObject::qt_static_metacall :
QgsPanelWidget::panelAccepted :
QObject::qt_static_metacall :
QObject::~QObject :
QgsLayerTreeLayer::QgsLayerTreeLayer :
QgsLayerTreeNode::~QgsLayerTreeNode :
QgsLayerTree::QgsLayerTree :
QgsLayoutItemLegend::setAutoUpdateModel :
QgsLayoutLegendWidget::mCheckBoxAutoUpdate_stateChanged :
QObject::qt_static_metacall :
QCheckBox::nextCheckState :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

[Zwischenstand_HU2.zip](https://github.com/qgis/QGIS/files/10898626/Zwischenstand_HU2.zip)

### Versions

3.28.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@gizmogizmogizmo the provided zip file containing the project misses the layers. Please provide a complete minimal project + layer(s). Please try if the issue does occur using the latest currently supported QGIS versions and using a new QGIS user profile.
