### ISSUE TITLE
DigiCert signing certificate expired

### ISSUE THREAD

**Issue by Dzeneralen** [qgis/QGIS#52128]
### What is the bug or the crash?

Tried downloading the new LTR version 3.28.4 of QGIS. When installing Windows prompts me with unknown publisher claiming the software could not be verified. Seems the certificate expired 9th of february 2023. Are there any plans to renew it?

Was hoping to add it as an installation to the winget repository of Microsoft, but can't add it when it has warning popups during install. 

### Steps to reproduce the issue

1. Download QGIS LTR version 3.28.4
2. Try to install, warning popup from Windows
3. Install works if ignored

### Versions

QGIS version
3.28.4-Firenze
QGIS code revision
fd0fb72ab3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2004

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by jef-n** [comment]
Fixed in MSI 3.30.0-2 and 3.28.4-3.
