### ISSUE TITLE
Custom projections and other settings options

### ISSUE THREAD

**Issue by JoaoPauloMCastro** [qgis/QGIS#52127]
### What is the bug or the crash?

Good afternoon,
In previous versions it was possible to put in the PROJ folder *.gsb files with coordinate transformation parameters and simultaneously create custom projections. However, now QGIS (QGIS version 3.28.3-Firenze) (and the same happens in all versions 3.**) prevents me from changing both the CRS and other things that after being changed in the Setings, giving as a result the error message below. Even if you change it to WKT at the end it won't let you save, warning you of the error message below
Regards

### Steps to reproduce the issue

Settings
Options or Custom projections
ok
Cannot save ' * Generated CRS (+proj=tmerc +lat_0=0 +lon_0=173 +k=0.9996 +x_0=1600000 +y_0=10000000 +ellps=GRS80 +units=m +no_defs)' — this Proj string definition is equivalent to EPSG:2193.

Try changing the CRS definition to a WKT format instead.

### Versions

QGIS version
3.28.3-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@JoaoPauloMCastro do you mean it worked with QGIS 2 while it doesn't work with any QGIS 3 version? So, did you upgrade from QGIS 2.x to QGIS 3.28? Have you tried if the issue does occur using a new QGIS user profile?

**Comment by agiudiceandrea** [comment]
@JoaoPauloMCastro is the issue you are experiencing the same or similar as already previously reported at https://github.com/qgis/QGIS/issues/50743?

**Comment by JoaoPauloMCastro** [comment]
that's it

**Comment by JoaoPauloMCastro** [comment]
Any changes that are made cannot be saved. I have tried changing to WKT but the error message persists and the changes are not saved

**Comment by JoaoPauloMCastro** [comment]
I have never tried to install with another QGIS user profile. I don't even know how to do it.

**Comment by JoaoPauloMCastro** [comment]
I will research how to do it and give feedback later

**Comment by JoaoPauloMCastro** [comment]
Thank you

**Comment by JoaoPauloMCastro** [comment]
Hello,
It worked. In the new profile no CRS appears listed and the error message does not appear. Restarting qgis, it always opens with the default profile. To enter the new profile, you must first enter the default profile. And then opening the new profile, leaving two qgis sessions open. This is a bit annoying. However, by restarting qgis from the default profile I was able to delete all the CRS listed without error message and the remaining settings can be customized. One problem I detected is that in the new profile all plugins have to be installed again. Is it possible to migrate plugins from one profile to another? How can the profiles be managed now? Do you have a solution for deleting the new profile?
Thanks for your help

**Comment by agiudiceandrea** [comment]
@JoaoPauloMCastro the QGIS user profile used by QGIS is the QGIS user profile used by the last instance of QGIS closed. So, first close the QGIS instance that uses the "default" profile, then close the QGIS instance that uses the new QGIS user profile. Next time QGIS will open using the new QGIS user profile. Or you can add the --profile additional parameter to the QGIS launch shortcut. For deleting a user profile you can delete the folder in which the user profile is stored. For any additional info please read https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
A useful plugin to manage user profiles is the "Profile Manager" plugin https://plugins.qgis.org/plugins/profile-manager/.
