### ISSUE TITLE
QgsGeometry::intersects return false on intersecting lines

### ISSUE THREAD

**Issue by AsimAziz** [qgis/QGIS#52126]
### What is the bug or the crash?

I'm tring to check intersection between two lines using **QgsGeometry.intersects** but it returns **False** on intersecting lines.

```
line_feature.geometry().intersects(line_feature.geometry())

```

### Steps to reproduce the issue

.

### Versions

QGIS version
3.22.12-Białowieża

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Could you provide full script and reproducible project ?
