### ISSUE TITLE
Crash when reporting layout to PDF when second map is included

### ISSUE THREAD

**Issue by gabrc52** [qgis/QGIS#52138]
### What is the bug or the crash?

```
/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = std::allocator<int>; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

### Steps to reproduce the issue

1. Attempt to export given layout as PDF with just one map
2. Export successful
3. Attempt to export given layout as PNG with one more map (locator map)
4. Export successful
5. Attempt to export given layout as PDF with one more map (locator map)
6. Export fails

### Versions

QGIS version | 3.28.3-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.5.2
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.40.0
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.13.0
OS version | Fedora Linux 37 (Workstation Edition)
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
OSMDownloader | 1.0.3
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

QGIS terminal output:

```
[rgabriel@vector ~]$ qgis
Warning: QSocketNotifier: Can only be used with threads started with QThread
Warning: Wayland does not support QWindow::requestActivate()
Warning: Wayland does not support QWindow::requestActivate()
Warning: Wayland does not support QWindow::requestActivate()
Warning: Wayland does not support QWindow::requestActivate()
/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = std::allocator<int>; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

File that reproduces issue:

https://drive.google.com/file/d/1UuvpGJMl2rzFq1D1oeCL3p_gkhNR_z9X/view?usp=share_link

Note how removing small map causes export to succeed

Also, it seems like removing the map and re-adding it fixed the crash

**Comment by gabrc52** [comment]
Once it stopped crashing, removing and re-adding a north arrow made it crash again

**Comment by roya0045** [comment]
> Once it stopped crashing, removing and re-adding a north arrow made it crash again

Could you cofirm if it's purely related to the north arrow?

**Comment by agiudiceandrea** [comment]
@gabrc52 trying to export your layout as an image or as a PDF file, the following warning is displayed:
![image](https://user-images.githubusercontent.com/16253859/223869796-c8900667-770c-43b3-8a46-e61021f466f3.png)

Anyway, I cannot reproduce the issue using QGIS 3.28.3 on my Windows system: the layout is exported without issue to both image and PDF file.

[land use.png](https://user-images.githubusercontent.com/16253859/223870722-b7dc0a4d-28d0-452d-86c1-8e54edaa14c8.png)
[land use.pdf](https://github.com/qgis/QGIS/files/10925928/land.use.pdf)

Could you please specify all the export settings used to export to PDF file?
Did you actually try if the issue does occur using a new QGIS user profile?

**Comment by gabrc52** [comment]
New profile, the ZIP file does crash for me. 

I'm using the default settings:

![image](https://user-images.githubusercontent.com/24363938/223891167-880a3389-1936-4048-b4e7-c9dfa6a7dacb.png)

```
[rgabriel@vector ~]$ qgis --profile "new new"
Warning: QSocketNotifier: Can only be used with threads started with QThread
Warning: Wayland does not support QWindow::requestActivate()
Warning: Wayland does not support QWindow::requestActivate()
/usr/include/c++/12/bits/stl_vector.h:1123: std::vector<_Tp, _Alloc>::reference std::vector<_Tp, _Alloc>::operator[](size_type) [with _Tp = int; _Alloc = std::allocator<int>; reference = int&; size_type = long unsigned int]: Assertion '__n < this->size()' failed.
Aborted (core dumped)
```

**Comment by alexbruy** [comment]
Not reproducible with the latest master (36c53ea14ced0975ecde67027f8468770ebcd67d) on Linux.
