### ISSUE TITLE
CRASH

### ISSUE THREAD

**Issue by SantoMAsilla** [qgis/QGIS#52148]
## User Feedback

zummata 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x000046dc (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

 
VEDI ERRORE

### Versions

 
Windows fatal exception: access violation

Thread 0x000046dc (most recent call first):
<no Python frame>
```


**Stack Trace**
No stack trace is available.


**QGIS Info**
QGIS Version: 3.26.2-Buenos Aires
QGIS code revision: feec3d3b12f
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621


### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

_No response_

**Comment by roya0045** [comment]
Too old and no useful information.

**Comment by agiudiceandrea** [comment]
@SantoMAsilla QGIS 3.26 is no longer supported. Please actually try using the latest supported QGIS version.
