### ISSUE TITLE
The field name is too long and automatically intercept

### ISSUE THREAD

**Issue by hahaxiaowai** [qgis/QGIS#52153]
### What is the bug or the crash?

When I save the temporary layer as shapefile，Fields named Startheight become Startheigh, lost a "t"
![image](https://user-images.githubusercontent.com/49934348/223751231-ac8e57b4-0d28-45be-bec1-4ecbd26c5d34.png)
![image](https://user-images.githubusercontent.com/49934348/223751177-0d2b46b9-516a-4f2a-b19e-9e6217496a5e.png)

Maybe this is not a bug, what is it caused by what is it?

### Steps to reproduce the issue

save the temporary layer as shapefile

### Versions

qgis desktop3.26

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Not a bug, it's limited by shapefile design : https://support.esri.com/en/technical-article/000022868#:~:text=Shapefiles%20use%20the%20dBASE%20file,character%20limitation%20for%20field%20names.

**Comment by nicogodet** [comment]
Can you open another issue (as it is totally different that original post of this one) ?
First 3.26 is not supported anymore, update to 3.28.4 or 3.30.0 before reporting
If still an issue, provide all necessary info to reproduce.
