### ISSUE TITLE
Georeferencer hangs after uploading PDF

### ISSUE THREAD

**Issue by JCKumaravel** [qgis/QGIS#52164]
### What is the bug or the crash?

Georeferencer hangs after uploading PDF and crashes

### Steps to reproduce the issue

[G44U2_63D2.pdf](https://github.com/qgis/QGIS/files/10930810/G44U2_63D2.pdf)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.24.0-Tisler | QGIS code revision | 6b44a42058
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.3
QScintilla2 version | 2.11.5
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
bhuvan_web_services-master | 0.3
CalculateGeometry | 0.6.8
geetimeseriesexplorer | 2.0
go2streetview | 8.6
google-street-view-layer-master | 0.1
google_maps_geocoder | 0.0.3
OnlineRoutingMapper | 0.9
qgis_resource_sharing | 1.0.0
scpplugin | 2.0
SemiAutomaticClassificationPlugin | 7.10.10
shapefile_encoding_fixer | 0.7
slyr_community | 4.0.6
StreetView | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99
ee_plugin | 0.0.6
HCMGIS | 23.2.1
quick_map_services | 0.19.33

</body></html>QGIS version
3.24.0-Tisler
QGIS code revision
[6b44a42058](https://github.com/qgis/QGIS/commit/6b44a42058)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
bhuvan_web_services-master
0.3
CalculateGeometry
0.6.8
geetimeseriesexplorer
2.0
go2streetview
8.6
google-street-view-layer-master
0.1
google_maps_geocoder
0.0.3
OnlineRoutingMapper
0.9
qgis_resource_sharing
1.0.0
scpplugin
2.0
SemiAutomaticClassificationPlugin
7.10.10
shapefile_encoding_fixer
0.7
slyr_community
4.0.6
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
ee_plugin
0.0.6
HCMGIS
23.2.1
quick_map_services
0.19.33

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@JCKumaravel QGIS 3.24 is no longer supported. Please use a currently supported QGIS version.

Using QGIS 3.28.4 on Windows, importing the PDF with the Georeferencer plugin takes a vary long time but it succeeds eventually.

It is possible to speed up the importing process of the PDF in the Georeferencer, setting the GDAL_PDF_DPI environmental variable, either in the [QGIS system setting](https://docs.qgis.org/3.22/en/docs/user_manual/introduction/qgis_configuration.html#system-settings) or the OS system settings, to a value like 200 or 150 or even lower.

The issue also occurs directly importing the PDF file in the project map.

**Comment by JCKumaravel** [comment]
Thank you very much, it is of great help. Now Finally the issue is solved
and now I can easily work on toposheets.

*With regards*
*- Kumaravel .C*
