### ISSUE TITLE
Deprecated sagaprovider plugin leaves "Invalid plugin" ghost(?) in 3.30

### ISSUE THREAD

**Issue by Houska1** [qgis/QGIS#52160]
### What is the bug or the crash?

Upgrade of QGIS to 3.30 (Windows OSGeo4Win 3.30-1 standard release) leaves the following inscrutable error message for invalid core plugin sagaprovider when the plugin manager is invoked:
![Screen_Capture_-_8_Mar__9_30_pm](https://user-images.githubusercontent.com/48919900/223901624-20043edf-a8ce-4e54-9931-49a8781199c9.png)

### Steps to reproduce the issue

Install 3.30 over a previous installation (with that plugin)
Go to plugin manager.
Notice "Invalid" category in left hand menu and click there.

### Versions

3.30.0-'s-Hertogenbosch (OSGeo4Win install)
Code revision f186b8efe0e

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Tried with pre-existing "clean testing" profile with no 3rd party plugins, but didn't try recreating a new (not pre-3.30) profile.

I am aware the (old) SAGA provider has been removed sometime in Nov 2022. I believe the issue is that while it is no longer installed, it remains present if an upgrade is made over top of a pre-removal version. Functionality does not seem to be impaired, but the error message is incomprehensible to users due to the red herring about metadata being missing and the warning that as it is a core plugin it cannot be uninstalled.

**Comment by agiudiceandrea** [comment]
@Houska1 thanks for reporting. I think it would be better to report this issue on the OSGeo4W packaging infrastructure at https://trac.osgeo.org/osgeo4w/.

**Comment by Houska1** [comment]
Done. See https://trac.osgeo.org/osgeo4w/ticket/780

I suggest leaving this in hibernation here until picked up there, because I can see them suggesting it is an upstream issue there :)
