### ISSUE TITLE
 object property window position

### ISSUE THREAD

**Issue by yeongjaeseo** [qgis/QGIS#52162]
### What is the bug or the crash?

a line object is added and the object property window appears, but whenever a new object property window is created, the object property window position gradually goes down.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/115768629/223911069-5fc655fd-fdd5-4e1f-b905-6ee832be349e.png)
![image](https://user-images.githubusercontent.com/115768629/223925643-523f9e0f-0244-44c4-9e33-ef6035848e1a.png)

### Versions

3.22.14

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/44050
