### ISSUE TITLE
QGIS 3.28, 3.30 crashing Mac 12.6.3 when running `fix geometries` toolbox

### ISSUE THREAD

**Issue by oeon** [qgis/QGIS#52167]
### What is the bug or the crash?

Observed on QGIS versions:
Version 3.30.0 RC
Version 3.28.4 LTR

Last working version: 3.22.16-Białowieża

Perhaps introduction of new "Repair method"?

<img width="225" alt="image" src="https://user-images.githubusercontent.com/271851/224054682-0a088cc2-15f2-42d2-a4d3-d939e0dd669c.png">

### Steps to reproduce the issue

1. attempt to use `fix geometries` tool from Processing Toolbox with a polygon dataset

### Versions

Version 3.30.0 RC
Version 3.28.4 LTR

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Please search before posting.

Duplicates https://github.com/qgis/QGIS/issues/50888
