### ISSUE TITLE
As usual Qgis crashes and on restart often the "Processing plugin" is the culprit

### ISSUE THREAD

**Issue by Carml82** [qgis/QGIS#52168]
## User Feedback

I was trying to get a measuration with a dtm and various shapefile activated (on local machine) and some data received from the net

## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706be

Current thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Thread 0x00001474 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsFields::operator= :
QgsFeature::setFields :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1.Go to "Measure" tool
2. Try to measure something
3. Qgis crashes

### Versions

3.28.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Carml82** [comment]
## User Feedback

I was trying to get a measuration with a dtm and various shapefile activated (on local machine) and some data received from the net

## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706ba

Thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706be

Current thread 0x00001474 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Thread 0x00001474 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QgsFields::operator= :
QgsFeature::setFields :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by roya0045** [comment]
The title is not related to the crash you got, it seem to have crashed during indexing (I asume you had snaping enabled).

**Comment by Carml82** [comment]
Yes I have always snapping enabled, feel free to change the title if you think it's appropriate to do so, I used only what I thought could be the most correct one

**Comment by Carml82** [comment]
New crash and new(?) report by the software

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003744 (most recent call first):



Stack Trace


QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestLineEndpoints :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMeasureTool::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Carml82** [comment]
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000029a4 (most recent call first):



Stack Trace


QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestLineEndpoints :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Carml82** [comment]
I mentioned the "Processing plugin" because I often see a message saying it's involved, maybe not this time.
I created a long time ago a clean profile, I created a new one, etc but I can't pinpoint a "exact steps" routine because the crashes appears (at least to me) random, this time Qgis crashed while taking a measure, other times crashes while trying to edit a shapefile.

**Comment by nyalldawson** [comment]
@Carml82 If you want to see this fixed, **you** need to make this as EASY AS POSSIBLE for the QGIS team to diagnose. Don't make us drag information out of you as that will just result in this ticket being closed with no action.

**Comment by Carml82** [comment]
@ nyalldawson I know perfectly well what you mean, in fact I'm trying to reduce the possible causes by creating a clean project from scratch. What I can see as a user are random crashes and since I'n not a programmer and I work with Qgis everyday I find annoying seeing it crash and I'm trying to do my part of the work in order to easy yours.
I used in the past to help on forum and I understand, believe me.

**Comment by Carml82** [comment]
New crash, this time I was trying to edit some shapefile after importing some groups of layers, I don't know if the cause can be the importation of a shapefile already opened in another istance of Qgis that was not responding
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000020a4 (most recent call first):



Stack Trace


QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestLineEndpoints :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Carml82** [comment]
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003478 (most recent call first):



Stack Trace


QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestCentroid :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Carml82** [comment]
## User Feedback

I just georeferenced a raster and I was trying to draw a rettangular shapefile

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000046e0 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestCentroid :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMapToolAdvancedDigitizing::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by Carml82** [comment]
## User Feedback

I was drawing the contour of a shapefile with an ongoing connection when accedentally I changed the scale level and got a crash.I don't know if it's relevant, but the project I was working as usual is read from a removable device in order to continue working on it at work and at home.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002f70 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QRhiGles2InitParams::newFallbackSurface :
QRasterPaintEngine::drawImage :
QPainter::drawImage :
QgsMapRendererCache::transformedCacheImage :
QgsMapRendererJob::layerImageToBeComposed :
QgsMapRendererJob::composeImage :
QgsMapRendererParallelJob::renderedImage :
QgsMapCanvas::mapUpdateTimeout :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
[ProgettoPulito2023-03-14.zip](https://github.com/qgis/QGIS/files/11034703/ProgettoPulito2023-03-14.zip)

**Comment by Carml82** [comment]
## User Feedback

I imported some georeferenced rasters, I just activated a group of layers and I was going to take a measure which freezed and then I got the crash info

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002640 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QgsExpression::evaluate :
QgsCategorizedSymbolRenderer::valueForFeature :
QgsCategorizedSymbolRenderer::originalSymbolForFeature :
QgsFeatureRenderer::willRenderFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::init :
QgsPointLocator::nearestCentroid :
QgsSnappingUtils::~QgsSnappingUtils :
QgsSnappingUtils::snapToMap :
QgsMapMouseEvent::snapPoint :
QgsMeasureTool::canvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044
