### ISSUE TITLE
Merge Layers cause a Reflected composite

### ISSUE THREAD

**Issue by billmorgan000** [qgis/QGIS#52174]
### What is the bug or the crash?

When I tried to merge 11 layers to make a composite image of the Emit Data from the ISS, the composite was a reflection about the longitude axis. I am using 3.30.0. I hope you get my screen shot.
![EmitJicarillaComposite](https://user-images.githubusercontent.com/34485767/224237159-77aae220-5417-49bc-ad2d-571b33622881.png)

### Steps to reproduce the issue

Open the raster menu. Then go to merge and click. I next fill out the menu and hit run. The image is returned as a mirror image. 

### Versions

QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
f186b8efe0e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
catalogpl_plugin
2.1.1
ClipMultipleLayers
3.2.0
clipper
1.2
CloudMasking
23.1.7
ClusterMap
1.0
ee_plugin
0.0.6
enmapboxplugin
3.11.1
geetimeseriesexplorer
2.0
geoCore
0.8.1
geoscience
1.9
geosys-plugin
1.1.2
gistools
0.3
ImportPhotos
3.0.5
index_calculator
0.1
JSONEater-master
0.3
LAStools
1.4
layer2kmz
1.5.3
LineDirectionHistogram
3.1.1
MapsPrinter
0.9
NITK_RS-GIS_17
1.2
pca4cd
23.2a
pcraster_tools
0.2.0
pdaltools
0.1.6
PointConnector
2.0
qgis_gee_data_catalog
0.4.3
qgSurf
version 3.0.0
QMarxanToolbox
2.0.2
roof_draw
1.0.0
SampleByArea
0.7
sentinel2_download
3.5.7
SentinelHub
2.0.0
spatial_query_with_values
1.0.2
spectral_libraries
1.1.3
SpreadsheetLayers
2.1.0-alpha1
SRTM-Downloader
3.1.17
ThinGreyscale
3.0
usgs_stream_mapper
0.3
valuetool
3.0.15
open_lidar_tools
2.2.1
wofe_module
0.1
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@billmorgan000 judging from the screenshot, it seems the layers don't have a coordinate reference system set. In order to properly use the GDAL Merge algorithm, all the raster layer must be in the same coordinate system [[1](https://docs.qgis.org/3.22/en/docs/user_manual/processing_algs/gdal/rastermiscellaneous.html#merge)]. Could you please try if the issue does occur when all the layers have the right coordinate reference system set and if the coordinate reference system of all the layers is the same?

**Comment by billmorgan000** [comment]
Andrea:
Thank-you and you are correct. The EMIT hyperspectral-data comes from NASA in a netCDF4 file that Qgis cannot read as well as NASA's Panoply, which is their netCDF4 reading file program. I had to write a JupyteLab notebook python program to extract 11 bands as 11 gray scale images to be used in band-math to calculate mineral indexes. I was thinking I could use Qgis to merge the files and then add the CRS, but now I know cannot. Thank-you for your time.
                                                  Bill Morgan

**Comment by roya0045** [comment]
If you are using python to extract the data, wouldn't it be simpler to merge the bands there and then georeference them if needed? (Until this can be assessed and possibly fixed)

**Comment by billmorgan000** [comment]
Hi Alex:
I'm not that good with python, I had to use ChatGPT to mostly write the code. But, I will try to use python to merge the images, and then use Qgis to georeferenced the merged files.
                  Bill Morgan

**Comment by agiudiceandrea** [comment]
> I was thinking I could use Qgis to merge the files and then add the CRS

@billmorgan000 why don't you try to firs set the CRS for the raster layers and then merge them?

**Comment by billmorgan000** [comment]
Hi:
They are not georeferenced, so I would have to georeferenced each of the 11 images, then set the CRS of each of the 11 images , and then merge for a total of 23 steps. If I merge, that is 11 steps, then two more steps georeferencing and setting the CRS for a total of 13 steps.
                                           Bill Morgan

**Comment by agiudiceandrea** [comment]
@billmorgan000 if the raster layer are derived from bands of an unique multi-spectral image, then the should have the same CRS and georeferencing parameters, so you just need set the same georeferencing parameters and CRS to all the raster layer.
Anyway, it seems to me this is an issue you need to ask for the GDAL library developers mailing list https://lists.osgeo.org/pipermail/gdal-dev/ providing, as already requested here, at least two of the raster layer you need to merge for which the issue does occur.

**Comment by billmorgan000** [comment]
Thank-but I had ChatGpt write the code, and now they are merged. Later today, I will finish getting the file into Qgis.
                                                            Bill Morgan
