### ISSUE TITLE
Delaunay Triangulation inconsistency

### ISSUE THREAD

**Issue by KonstiDE** [qgis/QGIS#52172]
### What is the bug or the crash?

When applying the native delaunay trinangulation process only the centroids of hexagons, we would expect a fishernet kind of layer. However, the triangulation feature fails after almost producing the right output...

![n](https://user-images.githubusercontent.com/116877035/224181571-af3920d8-9cc1-4d3a-b20f-d4dc654a0d5b.PNG)
![n2](https://user-images.githubusercontent.com/116877035/224181584-d028ddde-d85a-48c3-add5-38e715e4c7cd.PNG)
![n3](https://user-images.githubusercontent.com/116877035/224181590-2091d2d3-92ee-4980-a137-bf19947470bf.PNG)

### Steps to reproduce the issue

Create a hexagonial grid with the extend: 8.596003700,9.835141800,41.386694700,43.050699100 [EPSG:4326]
Use Vector > Geometry Tools > Centroids on the grid
Apply Delaunay Triangulation onto the centroids

### Versions

QGIS version: 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by KonstiDE** [comment]
For width and height, I use 10.0 kilometers and Hspacing/Vspacing of 0.0. CRS is the project default: EPSG:3857 - WGS 84 Pseudo-Mercator

**Comment by KonstiDE** [comment]
Any updates?

**Comment by agiudiceandrea** [comment]
@KonstiDE, I can only confirm that the issue occurs using the latest QGIS 3.28 and QGIS 3.30 on Windows.

**Comment by KonstiDE** [comment]
Any updates?
Still fails in QGIS 3.32.3 (Lima)

**Comment by alexbruy** [comment]
It is still open. Obviously no.

**Comment by agiudiceandrea** [comment]
@KonstiDE, it seems to me the issue no longer occurs using the latest QGIS 3.35.0-Master nightly build and the upcoming QGIS 3.34.0. It may have been fixed by https://github.com/qgis/QGIS/pull/53787. Could you please check ASAP?
![image](https://github.com/qgis/QGIS/assets/16253859/dad7d1de-67e0-4ed0-93d5-0d6862381e66)

**Comment by KonstiDE** [comment]
Works like a charm, thank you
