### ISSUE TITLE
Crash when deleting items from a Print Layout

### ISSUE THREAD

**Issue by GeoTim66** [qgis/QGIS#52180]
### What is the bug or the crash?

Frequently crashes when deleting items such as labels, arrows etc from a Print Layout

## User Feedback

Crashes when trying to delete items from a Layout

## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x80040155

Thread 0x000085d8 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x80040155

Thread 0x000085d8 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Current thread 0x000085d8 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.0-'s-Hertogenbosch
QGIS code revision: f186b8efe0e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

Click on item such as label, arrow, scale bar, etc in Print Layout out and hit 'Delete'

### Versions

3.30.0-'s-Hertogenbosch

Also happened on earlier versions

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Thanks for reporting. It seems to me this issue is the same as already previously reported at https://github.com/qgis/QGIS/issues/52166. If so, please close this issue report and comment to the previous issue report, providing a sample project + layer(s) and exact steps in order to replicate the occurrence of the issue. Does the issue occur actually using a new QGIS user profile?
