### ISSUE TITLE
Transformation error when using custom crs

### ISSUE THREAD

**Issue by LoctudyPro** [qgis/QGIS#52184]
### What is the bug or the crash?

Custom project does not give the good result.

![image](https://user-images.githubusercontent.com/126656764/224490951-8c18c154-91f9-429d-830c-6d9aed6d8f87.png)

using a simple python script give the good result

from pyproj import CRS
from pyproj import Transformer

crs = CRS.from_proj4("+proj=tmerc +lat_0=0 +lon_0=27 +k=1 +x_0=0 +y_0=0 +a=6378249.145326 +rf=293.466307 +towgs84=-135.4,-106.7,-291.7,0,0,0,0 +units=m +no_defs +type=crs")

transformer = Transformer.from_crs(4326,crs)

x, y, z = transformer.transform(-26.428225000000, 27.65254105, 1680)

x_expt = 65126.906
y_expt = -2924147.501

x_qgis = 65094.9436
y_qgis = -2924205.9424

print(x - x_expt, y-y_expt) # ==> GOOD
print(x - x_qgis, y-y_qgis) # ==> BAD

![image](https://user-images.githubusercontent.com/126656764/224491382-b500ce5e-7b04-45ac-a202-8904fe6499c0.png)

### Steps to reproduce the issue

see before

### Versions

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.2
  |   |   |  
Active Python plugins
debug_vs | 0.7
QuickOSM | 2.1.1
qgis2web | 3.16.0
Qgis2threejs | 2.7.1
OSMDownloader | 1.0.3
seismicplugin | 3.0.1
remotedebug | 0.4.3
qgiscloud | 3.7.1
plugin_reloader | 0.9.2
crayfish | 3.6.0
timemanager | 3.6
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.2

Active Python plugins
debug_vs
0.7
QuickOSM
2.1.1
qgis2web
3.16.0
Qgis2threejs
2.7.1
OSMDownloader
1.0.3
seismicplugin
3.0.1
remotedebug
0.4.3
qgiscloud
3.7.1
plugin_reloader
0.9.2
crayfish
3.6.0
timemanager
3.6
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by LoctudyPro** [comment]
After further investigation:
Transformation in the canevas is OK that's the good news !
So it's only the test interface which give wrong result

**Comment by agiudiceandrea** [comment]
It seems the issue does not occur using QGIS 3.22 (while the output coordinates are swapped).
