### ISSUE TITLE
Support for HTML in text of legend items

### ISSUE THREAD

**Issue by theudebert** [qgis/QGIS#52190]
### Feature description

QGIS would rock even more if we had the possibility to use HTML Code in the texts of legend items.
For my work I see two important use cases:

- Italic font for scientific names of plants / animals
- Tables for exact placement and alignment of texts

And I am sure, others will find a lot of other great things to do with this!

Regards

**Comment by nyalldawson** [comment]
Qgis 3.30 added this capability

**Comment by theudebert** [comment]
Ah, great! :-)
Didn't know that because I use LTR
