### ISSUE TITLE
Canvas image export does not take into account global terrain shading

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#52199]
### What is the bug or the crash?

1- Open QGIS
2- Add a DTM
3- Add Global Terrain Shading effect under project properties
4- Export the canvas as an image

The exported image ignores the effects applied in step 3.

### Steps to reproduce the issue

See above

### Versions

3.30

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
should be fixed by #52271
