### ISSUE TITLE
custom script to add print layout templates  causes qgis to crash 

### ISSUE THREAD

**Issue by lokesh2b6** [qgis/QGIS#52215]
### What is the bug or the crash?

my custom script to add layout templates(2) to layout manager  causes the qgis to crash during executing through processing toolbox 

### Steps to reproduce the issue

"""
Model exported as python.
Name : TEST
Group :
With QGIS : 32601
"""

from qgis.core import QgsProcessing
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingParameterMapLayer
from qgis.core import QgsProcessingParameterFile
from qgis.core import QgsProject
from qgis.core import QgsLayoutManager
from qgis.core import QgsPrintLayout
from PyQt5.QtXml import QDomDocument
from qgis.core import QgsReadWriteContext
from qgis.core import QgsLayout
from qgis.utils import iface
import processing
import os

project = QgsProject.instance()
layout = QgsPrintLayout(project)
context = QgsReadWriteContext()
layout_manager = project.layoutManager()

def atlascreation(layout_name, template_path):
    template_file = open(template_path, 'r+', encoding='utf-8')
    content = template_file.read()
    template_file.close()
    document = QDomDocument()
    document.setContent(content)
    layout.loadFromTemplate(document, context)
    layout.setName(layout_name)
    layout_manager.addLayout(layout)
    atlas_layout = layout_manager.layoutByName(layout_name)
    atlas_settings = atlas_layout.atlas()
    atlas_settings.setEnabled(False)

atlascreation('Test a3Layout',
     "D:\\R-Lpms\\test\\modeltest\\templates\\A3_LPM_TEMPLATE_GAUTHAMI.qpt")

class Test(QgsProcessingAlgorithm):

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterMapLayer(
            'map_layer', 'map layer ', defaultValue=None, types=[QgsProcessing.TypeVectorPolygon]))
        self.addParameter(QgsProcessingParameterFile('templatefile', 'templatefile', optional=True,
                          behavior=QgsProcessingParameterFile.File, fileFilter='All Files (*.*)', defaultValue=None))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        feedback = QgsProcessingMultiStepFeedback(1, model_feedback)
        results = {}
        outputs = {}

        # Boundary
        alg_params = {
            'INPUT': parameters['map_layer'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Boundary'] = processing.run(
            'native:boundary', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        return results

    def name(self):
        return 'TEST'

    def displayName(self):
        return 'TEST'

    def group(self):
        return ''

    def groupId(self):
        return ''

    def createInstance(self):
        return Test()

atlascreation(
    'Test a4Layout', "D:\\R-Lpms\\test\\modeltest\\templates\\A4_LPM_TEMPLATE_GAUTHAMI.qpt")

### Versions

QGIS version
3.26.1-Buenos Aires
QGIS code revision
b609df9ed4d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
bhu_kamatha
1.0
CalculateGeometry
0.6.8
Mergin
2022.4.1
OpenTopography-DEM-Downloader
1.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.2
qfieldsync
v4.2.0
Qgis2threejs
2.7.1
qrbarcodeitem
0.2.0
SplitPolygonShowingAreas
0.13
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It's more a user mistake rather than a QGIS issue.

**Comment by roya0045** [comment]
> It's more a user mistake rather than a QGIS issue.

Agreed, I think this should be closed and be a better fit for the mailing lists or stackexchange.

**Comment by lokesh2b6** [comment]
working with templates
