### ISSUE TITLE
The program crashes a few minutes after launch.

### ISSUE THREAD

**Issue by Kaply9l** [qgis/QGIS#52218]
### What is the bug or the crash?

The program crashes a few minutes after launch, and error do not appears.

### Steps to reproduce the issue

Run the program and you can just wait or do any action, and after a few minutes it will crash.

### Versions

Version QGIS
3.30.0-'s-Hertogenbosch
Revision
f186b8efe0e
Version Qt
5.15.3
Version Python
3.9.5
Version GDAL/OGR
3.6.2
Version PROJ
9.1.1
Registry database version EPSG
v10.076 (2022-08-31)
Version GEOS
3.11.1-CAPI-1.17.1
Version SQLite
3.39.4
Version PDAL
2.4.3
Version PostgreSQL
unknown
Version SpatiaLite
5.0.1
Version QWT
6.1.6
Version QScintilla2
2.13.1
Version ОС
Windows 7 Version 6.1 (Build 7601: SP 1)

Included modules Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
If your windows 7 is 32 bit that might be the cause, otherwise there's not much to fix if we don't have any clue as to what could cause the crashes.

**Comment by Kaply9l** [comment]
Thanks you for the answer.
