### ISSUE TITLE
Select by location fail

### ISSUE THREAD

**Issue by Octansf** [qgis/QGIS#52212]
### What is the bug or the crash?

When use de icon select by location or select the tool in geoprocessing toolbar and select layer of point to intersect with layer of polygons, when execute the tool, select points that do not intersect polygons
![Bug_qgis_select_by_location](https://user-images.githubusercontent.com/43656948/224808613-12c5dcb9-41d5-4bf6-8b39-9ac61e75f549.PNG)
Errors in red circle

### Steps to reproduce the issue

I have two layers one points, one polygon, both are in the same projection. I made click in the icon " Select by Location". First layers select points second layer polygons. And run the proccess

### Versions

3.22.14 Bialowieza LTR
3.28.2 Firenze LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@Octansf could you please provide the layers with which the issue does occur? Could you please check if the issue does occur also using a new QGIS user profile?

**Comment by roya0045** [comment]
Are the points multipoints or all distinct entities? Otherwise sample data (only a subset) where the error occur would probably be helpful as suggested by Andrea.

**Comment by Octansf** [comment]
Thanks for your response. Issue resolved. I used the tool Validate Geometry. And magic occurred, the layer have 3 issues, then I correct them and finally the tool run.  
If made necessary, run other tools before posting this kind of issue. I apologize for don't exhaust the use of other tools that can give some orientation in the resolve.
Thanks again
