### ISSUE TITLE
GRASS - Crash using module v.to.rast.attr

### ISSUE THREAD

**Issue by eco2000** [qgis/QGIS#52221]
### What is the bug or the crash?

QGIS crash happened while trying to select input vector (previously created using module v.in.ogr.qgis).

### Steps to reproduce the issue

click on dropdown under "loaded layer"

### Versions

Python Stack Trace
Windows fatal exception: code 0xc0000028

Current thread 0x000072bc (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@eco2000 QGIS 3.26 is no longer supported. Please actually use the latest supported QGIS version. Please use try if the issue does occur usin a new QGIS user profile.
