### ISSUE TITLE
QGIS 3.30/ Python - Error using QgsGeometry.convertToType(QgsWkbTypes.PolygonGeometry)

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#52224]
### What is the bug or the crash?

Using 
**QgsGeometry.convertToType(3)** to convert the geometry to a Polygon results in an error: 
_TypeError: QgsGeometry.convertToType(): argument 1 has unexpected type 'int'_

**QgsGeometry.convertToType(QgsWkbTypes.PolygonGeometry)** works.

Both works in 3.22

### Steps to reproduce the issue

Error occurs in Plugin, but I think it is due to change in api...

### Versions

QGIS-Version
3.30.0-'s-Hertogenbosch
QGIS-Codeversion
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.2
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
debug_vs
0.7
Hotlink
0.8.6
PluginLoadTimes
3.0.1
plugin_reloader
0.9.3
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It's related to the move to enum class for QgsWkbTypes (see https://github.com/qgis/QGIS/pull/51948).
I had a similar issue in ProfileTool.

CC @nyalldawson

**Comment by nyalldawson** [comment]
The exception describes your issue -- basically you should never have been calling `QgsGeometry.convertToType(3)` and should always have been using the enums from QgsWbkTypes (which still work). Using the raw int was an API misuse that only worked by chance.

**Comment by PeterDrexel** [comment]
Thank you for the clarification, I updated the plugincode, no it works as expected
