### ISSUE TITLE
Make custom properties in layer visible in UI

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#52243]
### Feature description

When writing plugins, and loading layers with that plugin, I find myself sometimes creating 'custom_properties' of a layer: 
https://qgis.org/pyqgis/master/core/QgsMapLayer.html#qgis.core.QgsMapLayer.setCustomProperty

I use it for example to flag a layer as being loaded by a plugin, or sometimes I use it to set plugin specific layer properties in it.

I tried to find the value of the property in the Layer Properties dialog.

So: either I missed it (then please show me), OR it's just not implemented...

I think the most proper place would be in the 'General' block of the Layer Properties?

![Screenshot from 2023-03-15 10-32-52](https://user-images.githubusercontent.com/731673/225267980-a3c10887-7d31-43ac-802a-ad7dd0c4b023.png)

Though that are key-value pairs. And you can have a set of custom properties. Not sure if we want to distinguish those from 'normal' properties?
The we could add maybe a 'Custom Properties' line above it?

I think this is very easy to implement (if others agree), so I thought to label this a "Good First Issue" issue... but apparently we only have 'Easy fix'... so I added the label :-)

Please let me know if a first compiler wants to pick this up, else I'll do it myself if others agree..

**Comment by anjishnum** [comment]
Hi 

Can you assign me to this issue? I want to try it out.

**Comment by kleenkanteen** [comment]
@elpaso Why didn't your commit get merged in yet?

**Comment by kleenkanteen** [comment]
@rduivenvoorde Can I get assigned this issue since @anjishnum went mia?
