### ISSUE TITLE
Style context menu wording change in german language 

### ISSUE THREAD

**Issue by nts-eschert** [qgis/QGIS#52247]
### What is the bug or the crash?

Using the German language, the word "Stil" (en. 'Style') in the context menu of every layer changes to "Maßstab (n)" (en. 'scale' with n being the number of styles added), when adding one or more styles to a layer.

I expect it to change from "Stil" to "Stile (n)" though.

### Steps to reproduce the issue

1. go to settings
2. turn on system locale override, apply German language and restart
3. add any vector layer with any symbology
4. right click the layer and go to Stil->Hinzufügen...->OK
![image](https://user-images.githubusercontent.com/88319901/225294182-c749d52f-25c3-4665-a5dd-9a40cedee9f8.png)

6. right click the layer again and the word Stil will be changed to Maßstab (2)
![image](https://user-images.githubusercontent.com/88319901/225294306-34aa0ac0-2863-4fca-aebb-53a4c615532e.png)

### Versions

QGIS-Version
3.28.0-Firenze
QGIS-Codeversion
ed3ad0430f3
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.2
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
GeometryShapes
0.7
Go2NextFeaturePlus
2.10
ImportPhotos
3.0.5
LoadQSS
1.4.2
mmqgis
2021.9.10
ORStools
1.5.2
OSMDataSync
0.2
OSMDownloader
1.0.3
processing_saga_nextgen
0.0.7
qdraw
3.0.2
qfieldsync
v4.4.8
qgis-plugin-findreplace-main
1
qgis_resource_sharing
1.0.0
qNote
2.2
QuickOSM
2.1.1
quick_map_services
0.19.33
valhalla
2.3.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This issue appeared from QGIS 3.26.0 on.
I've tried this on multiple machines, with new and old profiles.
The issue does not appear in American English language, I have not tried other languages yet

**Comment by DelazJ** [comment]
@nts-eschert This is a translation issue that afaics has been fixed in transifex yesterday. It should be available in next point release or in dev version.
![image](https://user-images.githubusercontent.com/7983394/225309837-417446e3-e71c-47bf-bc05-89f3bd70dc74.png)
And if you wonder what transifex is and where to help fix wrong translation, follow https://qgis.org/de/site/getinvolved/translate.html#becoming-a-translator.
I'm closing for now.
