### ISSUE TITLE
QGIS layout models: problem from 3.28 to 3.22

### ISSUE THREAD

**Issue by katagen** [qgis/QGIS#52252]
### What is the bug or the crash?

I have different layout models, that I build in 3.22. I can use them in the new LTR (3.28).

But the problem is if I reopen the project in 3.22 (some computers in my office are still in 3.22), all the text blocs lose the police size and the police font.

Does the last LTR introduces a difference in the layout, so that a previous version can't use it? I found strange that it is not compatible between the last two LTR.

### Steps to reproduce the issue

- Create a layout in 3.28, with some text blocs and define police size and font different as default.
- Open the project in 3.22, and all the text blocs are in "default".

### Versions

The last LTR (3.28) and 3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
3.28 introduced a more complex formatting options for text bloc (https://github.com/qgis/QGIS/pull/50959) that may have introduced a backward incompatibility.

A warning message is displayed when you open a project that have been saved in more recent QGIS version.

**Comment by katagen** [comment]
I understand it, but is it a bug?
To be honest, it is problematic that the 2 last LTR are not retrocompatible.
And I have no problem with legend bloc, arrow bloc and so on... only with text bloc!
@nyalldawson

**Comment by nyalldawson** [comment]
@katagen qgis projects have never been backward compatible. They sometimes work in some ways, but there's always unknown breakage.

That's a design choice, and it's not something which is likely to change anytime soon.

**Comment by nicogodet** [comment]
Should I close as "won't fix" ?
