### ISSUE TITLE
Ghost methods displayed for some classes in PyQGIS API doc

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#52250]
### What is the issue about the documentation?

In https://qgis.org/pyqgis/master/gui/QgsLayerTreeView.html you'll find this 

![image](https://user-images.githubusercontent.com/7983394/225265250-879b942b-1952-4f37-bf5f-c1b66e14263a.png)

Methods on lines fully in bold and prepended with the class name DO NOT EXIST as far as I can tell; I checked:
- https://github.com/qgis/QGIS/blob/master/src/gui/layertree/qgslayertreeview.h
- https://api.qgis.org/api/classQgsLayerTreeView.html
- https://github.com/qgis/QGIS/blob/master/python/gui/auto_generated/layertree/qgslayertreeview.sip.in

I can find these "ghost" methods also (at least from the formatting perspective, as I did not track the code) in [QgsPoint](https://qgis.org/pyqgis/master/core/QgsPoint.html#qgis.core.QgsPoint.vertexAt), [QgsAttributeTableModel](https://qgis.org/pyqgis/master/gui/QgsAttributeTableModel.html#qgis.gui.QgsAttributeTableModel.UserRole), [QgsCodeEditorExpression](https://qgis.org/pyqgis/master/gui/QgsCodeEditorExpression.html#qgis.gui.QgsCodeEditorExpression.runPostLexerConfigurationTasks), ...

**Comment by roya0045** [comment]
They belong to the parent class,(see https://doc.qt.io/qt-6/qtreeview.html ) not sure if there is a downside in having them listed.
