### ISSUE TITLE
newer version of GDAL in macos version

### ISSUE THREAD

**Issue by eflaten** [qgis/QGIS#52267]
### Feature description

 I tried to edit on a layer from an FGDB source. Works fine on a PC with QGIS 3.30, but not on Mac with 3.30. The error message was something like: the layer can't be set editable.

The version of GDAL is 3.3.2 on the Mac version. On Windows the GDAL is 3.6.2 which is newer.

My suggestion is that the macos version of qgis get an upgraded GDAL so FGDB layers can be edited e.g with the "label toolbar" and "change label properties".

**Comment by nicogodet** [comment]
See https://github.com/qgis/QGIS-Mac-Packager/issues/153
