### ISSUE TITLE
QT Designer does not start (missing libraries)

### ISSUE THREAD

**Issue by niubii** [qgis/QGIS#52270]
### What is the bug or the crash?

After downloading and installing the QGIS-OSGeo4W-3.28.3-4.msi file, QGIS works normally, instead QT Designer (\Program Files\QGIS 3.28.4\apps\Qt5\bin\designer. exe) does not start because libpng16.dll library is missing.

### Steps to reproduce the issue

1. Download https://ftp.osuosl.org/pub/osgeo/download/qgis/windows/QGIS-OSGeo4W-3.28.4-3.msi
2. Run it as administrator
3. Follow the installation process with default settings
4. Open local directory C:\Program Files\QGIS 3.28.4\apps\Qt5\bin
5. Run program designer.exe

After @agiudiceandrea comment, I also tried to run:
C:\Program Files\QGIS 3.28.4\apps\Qt5\bin\qgis-ltr-designer.bat
but error message is still persistent.

In QGIS directory is present a libpng16-16.dll located in C:\Program Files\QGIS 3.28.4\apps\grass\grass78\bin
I make a copy of this file ad renamed it to lib16.dll, then copied in C:\Program Files\QGIS 3.28.4\apps\Qt5\bin
Now the error message about libpng16.dll is not showed anymore (either starting designer.exe or qgis-ltr-designer.bat.
Instead, a new error message appears, about missing zlib1.dll library.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.4-Firenze | QGIS code revision | fd0fb72ab3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AutomaticBackup-master | 1.0
contour | 2.0.12
csv_tools | 0.7.2
profiletool | 4.2.3
qconsolidate3 | 0.2.0
qfieldsync | v4.4.8
Qgis2threejs | 2.7.1
QuickOSM | 2.1.1
StreetView | 3.2
ViewshedAnalysis | 1.8
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.4-Firenze
QGIS code revision
[fd0fb72ab3](https://github.com/qgis/QGIS/commit/fd0fb72ab3)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
7.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AutomaticBackup-master
1.0
contour
2.0.12
csv_tools
0.7.2
profiletool
4.2.3
qconsolidate3
0.2.0
qfieldsync
v4.4.8
Qgis2threejs
2.7.1
QuickOSM
2.1.1
StreetView
3.2
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Also QGIS 3.22.11 has same problem (designer.exe is not running due a missing library).
Instead QGIS 3.16.7 has a designer.exe that runs fine.

**Comment by nicogodet** [comment]
This should be reported on https://trac.osgeo.org/osgeo4w/report

**Comment by agiudiceandrea** [comment]
@niubii you must launch Qt Designer using the qgis-designer.bat batch file.

**Comment by niubii** [comment]
@agiudiceandrea Thank you for suggestion, but it seems this is not the solution.
Also using \Program Files\QGIS 3.38.4\bin\qgis-ltr-designer.bat, the error message about missing libpng16.dll will appear.

**Comment by agiudiceandrea** [comment]
@niubii there is no need to install QGIS "as administrator". I've just installed QGIS 3.28.4 (QGIS-OSGeo4W-3.28.4-3.msi) on my Windows 10 system as a normal Windows user: the libpng16.dll library file is correctly located in `C:\Program Files\QGIS 3.28.4\bin\` and Qt Designer starts without issues either launching it by clicking the "Qt Designer with QGIS 3.28.4 custom widgets" shortcut link in the Start menu or by double clicking the `qgis-ltr-designer.bat` in `C:\Program Files\QGIS 3.28.4\bin\`, while it doesn't start double clicking `designer.exe` in `C:\Program Files\QGIS 3.28.4\apps\Qt5\bin`: this is an expected behaviour.

**Comment by niubii** [comment]
@agiudiceandrea 
Thank you again for you checks.
At the present, my Company policy don't allow employees to install software by themselves.

Every time I need a new software installed, I ask to IT management team to (approve installation and) install it.
So, my QGIS installation was run by our system administrator.
Just tried to make an installation repair of QGIS 3.28.4 by myself, it needs an administrator account.

Also tried to run qgjs-ltr-designer.bat instructions in command prompt, no error messages were appears, except the missing library at Designer startup.

**Comment by agiudiceandrea** [comment]
@niubii if the `libpng16.dll` file is missing in the `C:\Program Files\QGIS 3.28.4\bin\` folder on your system, then something wrong occurred during the installation procedure or some process (maybe an Antivirus software) deleted such file.
The missing `libpng16.dll` file is available in the OSGeo4W repository at https://download.osgeo.org/osgeo4w/v2/x86_64/release/libpng/libpng-1.6.37-3.tar.bz2

**Comment by agiudiceandrea** [comment]
@niubii have you found the root cause of the issue?

**Comment by agiudiceandrea** [comment]
@niubii please report the issue on https://trac.osgeo.org/osgeo4w/report
