### ISSUE TITLE
WMS connection cannot be removed

### ISSUE THREAD

**Issue by samuelchau** [qgis/QGIS#52275]
### What is the bug or the crash?

I cannot remove a WMS connection that I previously added.

I tried with using the Remove button from the "Data Source Manager - WMS/WMTS" 
and also using the Browser panel, where I right-clicked on my WMS/WMTS service and select "Remove Connection", but both didn't work.

The version of QGIS I'm using is 3.30.0-'s-Hertogenbosch

### Steps to reproduce the issue

Open the "Data Source Manager - WMS/WMTS" , click New to add a new connection. From the popup dialog, enter the Name and URL of your WMS connection, click OK.
Back in the Data Source Manager, you can then test your new connection by clicking on Connect.
Assume it works and loads all the layers to the list.
Now to remove this connection, click on Remove. But nothing seems to happen and you can still see the connect there.

### Versions

3.30.0-'s-Hertogenbosch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
It seems it also occurs for other connections like WFS / WCS / ...
@3nids, maybe it has something to do with the settings migration.

**Comment by MalikAlMaut** [comment]
In which Version was this fixed? It does not work for me in in 3.30.1 nor in 3.28.5 LTR

**Comment by 3nids** [comment]
Backport was missing in 3.30, done here https://github.com/qgis/QGIS/pull/52725#pullrequestreview-1387449035

I will investigate for 3.28.
