### ISSUE TITLE
LineString feature export to GPX doesn't work any more in QGIS 3.28 and 3.30

### ISSUE THREAD

**Issue by cyberang3l** [qgis/QGIS#52287]
### What is the bug or the crash?

In QGIS 3.22, I used to be right clicking on a layer that contains LineStrings, and choose `Export -> Save Features As...`. A new window would appear and one of the options I had was to export to GPX file format.

On the latest QGIS 3.30 (installed from flatpak), the GPX option is gone as you can see in the following screenshot:
![image](https://user-images.githubusercontent.com/5658474/225866519-5214e3e2-fb7e-40c7-b804-f5b24e82691a.png)

My workaround is to export to KML, and then use the gpsbabel command line to convert the KML file to GPX.

### Steps to reproduce the issue

1. `Layer` -> `New Temporary Scratch Layer`. Choose `LineString` for the Geometry type.
2. Start editing the new layer by clicking on the "Toggle Editing" button.
3. Click the `Add Line Feature` and draw a line on the map.
4. Save Layer edits and exit the editing mode
5. Right click on the Layer -> Export -> Save Features As...
6. Click on the `Format` drop down menu and there is no GPX export option.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.9.9
GDAL/OGR version | 3.6.0
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.36.0
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | KDE Flatpak runtime
  |   |   |  
Active Python plugins
OnlineRoutingMapper | 0.9
grdata | 1.0.7
pluginbuilder3 | 3.2.1
go2streetview | 8.6
quick_dem | 0.1
plugin_reloader | 0.9.3
profiletool | 4.2.3
trail_elevation_stats | 0.2
otbprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code branch
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Qt version
5.15.8
Python version
3.9.9
GDAL/OGR version
3.6.0
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.36.0
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.11.6
OS version
KDE Flatpak runtime

Active Python plugins
OnlineRoutingMapper
0.9
grdata
1.0.7
pluginbuilder3
3.2.1
go2streetview
8.6
quick_dem
0.1
plugin_reloader
0.9.3
profiletool
4.2.3
trail_elevation_stats
0.2
otbprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
On Windows, GPX export is still available.
![image](https://user-images.githubusercontent.com/39594821/225878784-23124ee4-c7f2-4a99-ba87-14f891dc62c3.png)

You should report this on QGIS flatpak repo https://github.com/flathub/org.qgis.qgis/issues
This is a packaging issue, not QGIS one.
