### ISSUE TITLE
ogr2ogr driver vs native QGIS driver (Oracle)

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#52286]
### What is the bug or the crash?

Not really a bug but also not really a feature request... I've added both labels :)

Talking about Oracle database and QGIS, I noticed that some tables with *not common geometrical definition*  are not even shown in QGIS (Browser, data source manager, DB Manager, etc). Therefore those tables cannot be loaded, exported, etc.

I was able to export **all** the tables with `ogr2ogr` in the OSGEOW4 Shell without any warnings or issues and without even using some options (except for the `-progress` one)

Tested on Windows (VM) with QGIS 3.28

I discovered (thanks to @nyalldawson) that `ogr2ogr` is a completely different driver.

So it would be awesome to have the same `ogr2ogr` driver also in QGIS

Here a screenshot of the `GEOM` column of one of the table not visible in QGIS:

![image](https://user-images.githubusercontent.com/2884884/225855443-d21c74f5-9436-4caf-8ec7-f7512804729d.png)

### Steps to reproduce the issue

Create an Oracle connection and try to unpack the database schema

### Versions

QGIS 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
You already can access Oracle with the ogr provider (ie. Vectors / Source Type: Database)

**Comment by ghtmtt** [comment]
thanks @jef-n. But still there are 2 different drivers? Some tables are not visible in the Browser while they are visible in ` Vectors / Source Type: Database`

**Comment by jef-n** [comment]
> thanks @jef-n. But still there are 2 different drivers? Some tables are not visible in the Browser while they are visible in ` Vectors / Source Type: Database`

Right, the ogrprovider doesn't have browser support for databases, but also provides alternative access to datasources that have native providers (ie. PostgreSQL, MSSQL, spatialite, hana, delimitedtext…).

**Comment by jef-n** [comment]
Which parts are you referring to?  BTW is there something special in the screenshot of the GEOM column above?  Do the working columns look any different?

**Comment by ghtmtt** [comment]
Browser VS `Vectors / Source Type: Database`

**Comment by nyalldawson** [comment]
I think there was some confusion here -- when I suggested to @ghtmtt to submit this ticket, I was referring to the issue were the QGIS provider can't read that particular geometry. 

I don't believe we should (or even could) remove the native QGIS oracle provider and replace with the GDAL driver.
