### ISSUE TITLE
Stop loading Qgis cause North extension not found

### ISSUE THREAD

**Issue by Azzedoc** [qgis/QGIS#52289]
### What is the bug or the crash?

The QGZ doesnt load. It stops at 24% during loading a WMS layer (from Geoservices IGN).
The error is : Impossible to load Qgis, north extension not found

[200a292a657597f6e3f845ecabc1a26347a76a45](https://github.com/qgis/QGIS/search?q=200a292a657597f6e3f845ecabc1a26347a76a45&type=Issues)

### Steps to reproduce the issue

Crash ID = [200a292a657597f6e3f845ecabc1a26347a76a45](https://github.com/qgis/QGIS/search?q=200a292a657597f6e3f845ecabc1a26347a76a45&type=Issues)

### Versions

Crash ID = [200a292a657597f6e3f845ecabc1a26347a76a45](https://github.com/qgis/QGIS/search?q=200a292a657597f6e3f845ecabc1a26347a76a45&type=Issues)

3.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@Azzedoc you'll need to provide more details on what you were doing and copy paste the stack trace if any. Your URLs lead to nowhere. Or share your qgz or link to the wms you were using.
Also, not sure the "north extension" is a QGIS core feature. You should really try with a new user profile.
Last but not least 3.20 is not a supported version. Abandoned for years. You should consider updating to 3.28.4 or 3.30...
