### ISSUE TITLE
Problem with OTB installation: OTB folder is not set

### ISSUE THREAD

**Issue by GolfBails** [qgis/QGIS#52296]
### What is the bug or the crash?

I am a student beginning to learn how to use QGIS. I just installed it using OSGeo4W. Each time I start QGIS, I keep seeing a Log Message on the Processing tab that says "CRITICAL Problem with OTB installation: OTB folder is not set."

I checked the Processing Settings for OTB. The OTB application folder and OTB folder paths have no values, and I have no idea what those values should be.

What can I do to fix this? I've attached some screenshots:

![Processing Error](https://user-images.githubusercontent.com/18103935/225771278-77d3d514-9d7f-4d00-8ed3-375823dae7cb.png)

![Installed Plugins](https://user-images.githubusercontent.com/18103935/225771210-22cf1a88-471c-4417-bbe6-01a824a8d8fa.png)

![Processing Providers](https://user-images.githubusercontent.com/18103935/225771327-7151318f-faa8-457d-927c-d5707d15bcae.png)

### Steps to reproduce the issue

Open QGIS

### Versions

Version 3.28.4

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@GolfBails, you should activate the "OrfeoToolbox provider" core plugin only if you need to use the OrfeoToolbox applications in QGIS as processing algorithms. In this case you'd also need to properly install the OrfeoToolbox binaries in your system and configure the processing plugin to find the OTB binaries (see https://docs.qgis.org/3.28/en/docs/user_manual/processing/3rdParty.html#otb-applications).
If you don't need to use the OrfeoToolbox applications in QGIS, then you don't need to activate the "OrfeoToolbox provider" plugin and you have to deactivate it if you don't want to see the messages about the OTB installation in the Log Messages panel.
