### ISSUE TITLE
Incompatibility problems between LTR 3.16 and LTR version 3.28

### ISSUE THREAD

**Issue by vrabanos** [qgis/QGIS#52308]
### What is the bug or the crash?

Symbology problem
A project made with LTR version 3.16 opened and saved with LTR version 3.28, modifies the symbology

### Steps to reproduce the issue

1.	In a polygon type layer:
A categorized symbology is used.
a.	If the symbology  is loaded with an SLD file
Applies the “All other values” symbol to all others values.

 ![1](https://user-images.githubusercontent.com/128154790/226295121-3ed7b452-d9c3-45c5-8f56-f17ddcd9362a.png)

If the field is specified to be "null", then it does not apply to the rest.
 		 
![2](https://user-images.githubusercontent.com/128154790/226295270-d7c5a133-8c1a-4db5-bb68-8e5a3e705361.png)

b.	If the symbology  is loaded with a QML file saved with version 3.28, it changes the colors, leaving all the same.
 
![3](https://user-images.githubusercontent.com/128154790/226295343-fb7bc4b4-3331-4ae5-a783-047aaa9eed99.png)

2.	In a line type layer:
A unique symbol used.
Assigns a symbol that has nothing to do with the project.
 
![4](https://user-images.githubusercontent.com/128154790/226295386-0d8db38a-080d-4ee4-93fa-bf21d9ffb0d2.png)

Has anyone had any incompatibility problems between LTR 3.16 and LTR version 3.28?

### Versions

LTR 3.16 
LTR 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
See https://www.qgis.org/en/site/forusers/visualchangelog330/index.html

> Importantly, support for backward compatibility of Symbol Styling has been removed for QGIS 3.16, providing significant optimizations to the project file structure, but limiting the capability of older releases of QGIS for rendering symbologies developed with later releases. This change has been ported to the release of 3.28 LTR as well.
