### ISSUE TITLE
QGIS ended unexpectedly.

### ISSUE THREAD

**Issue by renatodops30** [qgis/QGIS#52320]
### What is the bug or the crash?

Crash ID: [747d6cec905c6ae679d5ad30fb0aac60a80f5fa1](https://github.com/qgis/QGIS/search?q=747d6cec905c6ae679d5ad30fb0aac60a80f5fa1&type=Issues)

Stack Trace

QgsField::QgsField :
QgsFields::operator[] :
QgsKMeansClusteringAlgorithm::updateMeans :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgorithm::run :
PyInit__core :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__core :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
PyInit__core :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.15-Bia?owie?a
QGIS code revision: ef17ad14
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

3,22

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
1. QGIS 3.22 is EOL, please update to a supported version (3.28.4 or 3.30.0)
2. Could you describe what you were doing before the crash ? Is it reproducible ? If yes, can you share sample data and detailed step to reproduce ?
