### ISSUE TITLE
Feature attributes dialog's position cannot stays in the same place when creating new features

### ISSUE THREAD

**Issue by nsunpeak** [qgis/QGIS#52326]
### What is the bug or the crash?

Every time a new feature is created, the feature attributes dialog's position is automatically moved down by 31 pixels， and finally the "ok" button will move out of the screen.

![image](https://user-images.githubusercontent.com/102214269/226507518-e2e203af-a5af-448c-82a9-ffbb2bc971b6.png)

### Steps to reproduce the issue

1. open or creat a line layer
2. click on "Add Line Feature"
3. draw lines on the screen
4. you can see every time a new line feature is created, the feature attributes dialog's position is automatically moved down by 31 pixels

### Versions

QGIS version
3.28.4-Firenze
QGIS code revision
fd0fb72ab3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/44050
