### ISSUE TITLE
Angle snapping interfering with vertex/segment snapping

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#52333]
### What is the bug or the crash?

Not sure if this is considered a "bug":

Having _Advanced Digitizing_ enabled with _Snap to common angles_ functionality switched on,  the snapping to a vertex or a segment will not work when simultaneously snapping to a common angle. The angle snapping always wins, which might not be what the user wants. Having to disable angle snapping before snapping to a vertex or segment is quite cumbersome and annoying when it has to be done frequently.

![QGIS_snapping_simultaneously](https://user-images.githubusercontent.com/66669404/226669942-cb01696a-7ef2-4d43-aff1-d329deed382b.jpg)

![QGIS_snapping_angle_win](https://user-images.githubusercontent.com/66669404/226669959-176c3be7-b924-4bd3-ab77-3eeb2204f99a.jpg)

I know that the problem lies in the fact that neither angle snapping nor vertex/segment snapping are aware of each other and they live inside two different areas within QGIS and they are not talking to each other. 
Ideal scenario would be that the snapping to a vertex/segment/common angle is an event which can be catched/detected somehow (i.e. whenever snapping markers or indicators are drawn on the map canvas this is marks a detectable event or condition). If this was the case, it would be possible to establish some kind of configurable snapping hierarchy. 
Would it be a major development effort to make these snapping events detectable and to modify the API here?

------------------------------------------------

Taking this discussion further, it might be a valid idea to integrate the angle snapping into the QGIS snapping options where all could be configured and their hierarchy level could be set. It would make sense to find the angle snapping option here, rather than in the Advanced Digitizing widget which many users may not even be aware of.
This for sure would be a quite a development effort but would you deem it worth it...? 

### Steps to reproduce the issue

Activate Advanced Digitizing and snapping to common angles. Draw a linestring and try to snap to the vertex or segment of another line.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.4-Firenze | QGIS code revision | fd0fb72ab3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db-style-manager | 0.8
DigitizingTools | 1.5.1
latlontools | 3.6.9
layerGroupFilter | 0.2
mmqgis | 2021.9.10
multiple_layers_tools | 1.2
postgis_geoprocessing | 0.9
shapetools | 3.4.11
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.4-Firenze
QGIS code revision
[fd0fb72ab3](https://github.com/qgis/QGIS/commit/fd0fb72ab3)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db-style-manager
0.8
DigitizingTools
1.5.1
latlontools
3.6.9
layerGroupFilter
0.2
mmqgis
2021.9.10
multiple_layers_tools
1.2
postgis_geoprocessing
0.9
shapetools
3.4.11
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
IMHO, this is not a bug. All advanced digitizing constraints should have a higher priority and be satisfied first.
If a user does not want to snap to common angles, he should disable this setting first (a shortcut would make toggling easier, however, the advanced digitizing shortcuts are hard coded with the current implementation, which is quite bad as they can collide with user set shortcuts). But while _snap to common angles_ is enabled, it should be guaranteed that the digitized points are indeed on those common angles.

**Comment by beyhh** [comment]
I realize that every user might have different needs and the current setup might be exactly what some users need. It would be ideal if this was configurable but for this to happen, we would require some kind of event to make the different snappings become aware of each other. 

At some point it has been decided that angle snapping belongs to "advanced" digitizing but I don't really understand why this is considered advanced. To me, it is just another snapping option on the same level as vertex or segment snapping.

**Comment by elpaso** [comment]
I believe this is bug: from a user perspective the user sees the snapping indicator (purple square) over the vertex, she clicks to release the point and the point isn't snapped, without the possibility for the user to notice the error unless the user zoom level does allow to tell the two points apart.

Additionally: if the vertex snapping had the priority, it would still be possible to apply the angle constraint by zooming in to the point where the vertex is not in the snapping range anymore (a quick mouse wheel movement will do).

In the current situation the is no workaround possible (without disabling the common angle snapping).

I'm working on a PR that fixes this problem and I have made the new behavior optional but I am wondering if I shouldn't just make it the default behavior with no config options.

**Comment by uclaros** [comment]
> from a user perspective the user sees the snapping indicator (purple square) over the vertex, she clicks to release the point and the point isn't snapped, without the possibility for the user to notice the error unless the user zoom level does allow to tell the two points apart.

This is short-sighted as exactly the same argument can be used if you change the existing logic as proposed: the user _has explicitly enabled_ common angle snapping, sees the dashed line that indicates snapping to the _explicitly selected common angle_ yet his/her actual point does not lie upon this angle.

**Comment by elpaso** [comment]
There is still a difference though: now there is no way to snap to a vertex if the common angle constraint kicks in, while if the priority was inverted a simple zoom in would allow to snap to the angle, also locking the angle would allow to snap to the angle. 
Anyway, I'll leave it optional so the users will make their choice according to their workflows.
