### ISSUE TITLE
Right-click layer context menu opens in wrong place

### ISSUE THREAD

**Issue by LydiaWright** [qgis/QGIS#52342]
### What is the bug or the crash?

when you right click a layer, the context menu opens offset above the layer

<img width="217" alt="image" src="https://user-images.githubusercontent.com/105797928/226872391-b3d647e2-93cf-4180-8f3d-c5a11dc0126b.png">

### Steps to reproduce the issue

1. Right click on a layer
2. menu opens in wrong place

### Versions

3.28.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
I could not reproduce this bug. Which OS are you on? Could you try it again with a new profile?
