### ISSUE TITLE
Too many levels of trigger recursion error when saving layer having sql trigger

### ISSUE THREAD

**Issue by nicpitsch** [qgis/QGIS#52346]
### What is the bug or the crash?

On saving QGIS fails with error message (*Commit error*):

```
Could not commit changes to layer point1

Errors: ERROR: 1 attribute value change not applied.
  
  Provider errors:
      OGR error setting feature 1: failed to execute update : too many levels of trigger recursion
```

This happens if the layer has a database sql trigger which updates the layer content. Look at steps to reproduce.

### Steps to reproduce the issue

Setup the simplest possible environment to reproduce the issue (or download [here](https://cloud.pitsch-ing.ch/s/eTE2kM2j8bTJtqP)):

1. Create a new GeoPackage point layer from QGIS menu *Layer.. Create Layer.. New GeoPackage Layer..*. Name the GeoPackage e.g. *trigger_test* and the layer e.g. *point1* and add two text fields to it: *dummy* and *lastchange*.
2. Open QGIS *DB Manger* and connect the new created GeoPacke and open it...
3. ...open an "SQL Window* and execute subsequent SQL.

```sql
--drop trigger if exists point1_set_lastchange;
create trigger point1_set_lastchange after update on point1
begin
	update point1 set lastchange=cast(TIME() as text) where fid=old.fid;
end;
```

4. Load the layer *point1* into QGIS, add a point and save it.
5. Edit the new added point by changing the content of the *dummy* field. This raises the trigger on saving.
6. Try to save the changes.

### Versions

My environment: Windows 11 Pro 64 bit.

The error occurs with QGIS versions 3.28.3, 3.30.0 ([latest revision](https://github.com/qgis/QGIS/commit/f186b8efe0)). I have tested it on two different PC's. Installed using OSGeo4W installer.

The the error **does not occur** with QGIS version 3.22.12 (installed from msi download file)

The error did not happen with earlier versions of QGIS, I don't know with which version it started. I'm sure because I use SQL triggers intensively for a long time.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

[GeoPackage SQL Triggers](https://sqlite.org/lang_createtrigger.html) open up a multitude of application scenarios. I use them intensively with [QField](https://qfield.org). I discovered the error from there, where it was introduced with QField versions after 2.6.3. So this error is relevant to QField too, @m-kuhn.

**Comment by nicpitsch** [comment]
Thanks @m-kuhn for the explication.  
The QGIS default value functionality is not viable for my requirements. I use the triggers e. g. for more advanced validation checks and exposition.

The can be solved using the *of column-names* statement:

```sql
create trigger point1_set_lastchange after update of dummy on point1
begin
	update point1 set lastchange=cast(TIME() as text) where fid=old.fid;
end;
```

**Comment by takyanagida** [comment]
I encountered the same situation, when I updated QGIS from 3.4.4 (GDAL 2.4.0) to 3.40.4 (GDAL 3.10.2) on a GPKG file having the following trigger.

```sql
CREATE TRIGGER "trigger_spots_insert" AFTER INSERT ON "spots"
BEGIN
    UPDATE "spots" SET "created_at" = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'NOW') WHERE fid = NEW.fid;
END;

CREATE TRIGGER "trigger_spots_update" AFTER UPDATE ON "spots"
BEGIN
    UPDATE "spots" SET "updated_at" = STRFTIME('%Y-%m-%dT%H:%M:%fZ', 'NOW') WHERE fid = NEW.fid;
END;
```

This trigger pattern is popular among WebApp frameworks like Ruby on Rails, and is useful as casual editing log.
This trigger still works on QGIS 3.4.4.

Though I would go for _of column-name_ workaround for now, below is my investigation for future reference.

This error is caused by a following portion in GDAL/OGR's `ogr/ogrsf_frmts/gpkg/ogrgeopackagedatasource.cpp`

```C++
    // Turning on recursive_triggers is needed so that DELETE triggers fire
    // in a INSERT OR REPLACE statement. In particular this is needed to
    // make sure gpkg_ogr_contents.feature_count is properly updated.
    SQLCommand(hDB, "PRAGMA recursive_triggers = 1");
```

This portion seems introduced in OGR 3.6.0. as the change below. (from gdal/NEWS.md)

> GPKG driver:
>    - properly update gpkg_ogr_contents on INSERT OR REPLACE statements

And OGR's GPKG driver has the option below. (from OGR document)

> **ADD_GPKG_OGR_CONTENTS=[YES / NO]**: Defaults to YES. Defines whether to add a gpkg_ogr_contents table to keep feature count, and associated triggers.

Making this option configurable from QGIS setting could be an option.

Note that spatialite-gui (`recursive_triggers` not changed from default, which is 0) still works without error even with the trigger above.

**Comment by takyanagida** [comment]
A few days later, I noticed INSERT triggers doesn't support _of column-name_ format.

After some thoughts, I decided to migrate my personal GPKG database to SpatiaLite.
Either can be managed from QGIS, but I feel SpatiaLite is slightly more suitable for this kind of direct SQL manipulation.
