### ISSUE TITLE
Unintentional values applied in fields with value relation in attributes form

### ISSUE THREAD

**Issue by CommunyAS** [qgis/QGIS#52374]
### What is the bug or the crash?

When enabling editing in form view mode, unintentional and undefined data entry happens in all fields for which value relations for data selection are defined, even though no default value is set. Instead of leaving the fields empty (NULL), automatically the first value of the lists specified in *Layer properties > Attributes form > Widget type: value relation > Layer* is entered, leading to incorrect data collection.

### Steps to reproduce the issue

1. Create layer with data fields for data collection and thesauri tables
2. Define value list for data entry setting relations to existing thesauri tables in *Layer properties > Attributes form > Widget type: value relation > Layer/Key column/Value column* - leave *Defaults* empty (unchanged)
3. Select layer for data collection
4. Open form view, enable edit mode

### Versions

QGIS version | 3.28.4-Firenze | QGIS code revision | 766501dd8b
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@CommunyAS thanks for reporting. It would be useful if you could provide a minimal sample project and layer(s) with which the issue does occur.

**Comment by CommunyAS** [comment]
I meanwhile found out, where the problem arises: one has to tick **Allow NULL value** in Relation Reference widget - by default it is not ticked.
