### ISSUE TITLE
Unable to start editing of mesh layer: Face is flat

### ISSUE THREAD

**Issue by jamaa** [qgis/QGIS#52371]
### What is the bug or the crash?

I want to edit a mesh layer but get the error message 

>Unable to start editing of mesh layer "meshlayername": Face XXX is flat

where XXX is the number of the face.

### Steps to reproduce the issue

First, create a mesh (2dm file) using the "TIN Mesh Creation" tool. Input vector layers are some points.

I then want to edit this mesh but get the error message 

>Unable to start editing of mesh layer "meshlayername": Face XXX is flat

I am not sure, what "face is flat" actually means? They are all triangular faces so should all be flat by definition?

Anyway, I tried manually deleting the offending face from the mesh by deleting the relevant line from the 2dm file, and this does seem to work in principle, but is very cumbersome because 
* face numbers in the 2dm file are different from those used by QGIS 
* QGIS only outputs the first offending face it finds. After editing the 2dm file manually, loading it again in QGIS and trying to edit again, I get the number of the next offending face from QGIS. I gave up after manually deleting about a dozen faces.

Possible fixes I can think of, in order of preference:
* The "TIN Mesh Creation" should not create meshes that are not editable in the first place
* QGIS could provide a tool to "fix" a mesh in order to make it editable
* QGIS should output the complete list of all offending faces at once, so that manually fixing the 2dm file is less cumbersome

### Versions

QGIS version | 3.22.12-Białowieża | QGIS code revision | b8534cb1
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.5.2
PROJ version | 9.1.0
EPSG Registry database version | v10.074 (2022-08-01)
GEOS version | 3.10.3-CAPI-1.16.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | 14.3
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DataPlotly | 3.9.2
profiletool | 4.2.2
quick_map_services | 0.19.33
wbt_for_qgis | 1.0.7
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Face is flat means that the face has a surface equal to 0.
https://github.com/qgis/QGIS/issues/50036#issuecomment-1241316704

Could you share your input vector layer ?

**Comment by vcloarec** [comment]
@jamaa 
with QGIS 3.28 you should be able to start the editing. QGIS should purpose to fix the mesh errors.

**Comment by jamaa** [comment]
Yes, QGIS 3.28 fixes the mesh and I am then able to edit it!

![grafik](https://user-images.githubusercontent.com/90166/227537457-130affac-0ec0-4a11-a4e4-69a415088508.png)

I guess we can close this issue, thanks everyone for the help!
