### ISSUE TITLE
Right click menu on model in project models is not activating

### ISSUE THREAD

**Issue by dat-linux** [qgis/QGIS#52388]
### What is the bug or the crash?

No logging.

### Steps to reproduce the issue

Open modeler. 

Create and save a model as a project model. 

Right click on the model in "project models". Nothing happens (should see a menu for editing, executing, etc)

### Versions

3.30 Linux.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
Duplicates #52269
