### ISSUE TITLE
failed to create a layer in project folder which was generated from algorithm when i run it two or more times 

### ISSUE THREAD

**Issue by lokeshmetta** [qgis/QGIS#52381]
[bhu_kamatha.zip](https://github.com/qgis/QGIS/files/11065809/bhu_kamatha.zip)
### What is the bug or the crash?

Could not create layer D:/R-Lpms/test/modeltest/modeltest\Boundary.shp: Creation of data source failed (OGR error: D:/R-Lpms/test/modeltest/modeltest\Boundary.shp is not a directory.)
Execution failed after 1.44 seconds

### Steps to reproduce the issue

# -*- coding: utf-8 -*-

"""
/***************************************************************************
 LpmProcessingModel
                                 A QGIS plugin
 Description
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2023-03-12
        copyright            : (C) 2023 by SurveyoStories
        email                : surveyorstories@gmail.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

from multiprocessing.spawn import import_main_path
from logging import _STYLES
import inspect
from qgis.PyQt.QtGui import QIcon
import processing
from qgis.core import QgsProcessingParameterVectorDestination
from qgis.core import QgsProcessingParameterFeatureSource
from qgis.core import QgsGeometry
from qgis.core import QgsAttributeEditorContainer
from qgis.core import QgsMapLayer
from qgis.core import QgsVectorFileWriter
from qgis.core import QgsFileUtils
from qgis.core import QgsProject
from qgis.core import QgsFeature
from qgis.core import QgsField
from qgis.core import QgsVectorLayer
from qgis.core import QgsExpressionContext
from qgis.core import QgsExpression
from qgis.core import QgsProcessingParameterString
from qgis.core import QgsProcessingParameterFile
from qgis.core import QgsProcessingParameterDistance
from qgis.core import QgsProcessingParameterField
from qgis.core import QgsProcessingParameterVectorLayer
from qgis.core import QgsProcessingMultiStepFeedback
from qgis.core import QgsProcessingAlgorithm
from qgis.core import QgsProcessing
import os
import sys
__author__ = 'SurveyoStories'
__date__ = '2023-03-12'
__copyright__ = '(C) 2023 by SurveyoStories'

# This will get replaced with a git SHA1 when you do a git archive

__revision__ = '$Format:%H$'

from qgis.PyQt.QtCore import QCoreApplication
from qgis.core import (QgsProcessing,
                       QgsFeatureSink,
                       QgsProcessingAlgorithm,
                       QgsProcessingParameterFeatureSource,
                       QgsProcessingParameterFeatureSink)

"""
Model exported as python.
Name : LPM Processing Model
Group :
With QGIS : 32601
"""

# Get the path to the current project folder
project_folder = QgsProject.instance().readPath("./")

class LpmProcessingModelAlgorithm(QgsProcessingAlgorithm):

    def icon(self):
        cmd_folder = os.path.split(inspect.getfile(inspect.currentframe()))[0]
        icon = QIcon(os.path.join(os.path.join(cmd_folder, 'icon.png')))
        return icon

    def flags(self):
        return super().flags() | QgsProcessingAlgorithm.FlagNoThreading

    def initAlgorithm(self, config=None):
        self.addParameter(QgsProcessingParameterVectorLayer('village_final_shape_file',
                          'Village Final Shape File', types=[QgsProcessing.TypeVectorPolygon], defaultValue=None))
        self.addParameter(QgsProcessingParameterField('lpm_number_column', 'LPM Number Column', type=QgsProcessingParameterField.Any,
                          parentLayerParameterName='village_final_shape_file', allowMultiple=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterField('area_in_acres_column_choose_your_acre_column_according_to_your_shape_file', 'Area in Acres Column (Choose Your Acre column according to your shape File)',
                          type=QgsProcessingParameterField.Any, parentLayerParameterName='village_final_shape_file', allowMultiple=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterField('area_in_hectares_column_choose_your_hectares_column_according_to_your_shape_file', 'Area in Hectares Column (Choose Your Hectares column according to your shape File)',
                          type=QgsProcessingParameterField.Any, parentLayerParameterName='village_final_shape_file', allowMultiple=False, defaultValue=None))
        self.addParameter(QgsProcessingParameterDistance('prill_line_length_multi_ring_length', 'Prill Line Length (Multi Ring Length)',
                          parentParameterName='village_final_shape_file', minValue=1, maxValue=20, defaultValue=3))
        self.addParameter(QgsProcessingParameterFile('choose_your_rlrdlr_form38_resurvey_land_register', 'Choose Your RLR/DLR (Form-38 Resurvey Land Register)',
                          behavior=QgsProcessingParameterFile.File, fileFilter='All Files (*.xlsx*)', defaultValue="C:\\Users\\lokes\Desktop\\Install\layer\\Form38data_Report (4).xlsx"))
        self.addParameter(QgsProcessingParameterFile('choose_your_ulpin_layer', 'Choose Your ULPIN Layer',
                          behavior=QgsProcessingParameterFile.File, fileFilter='All Files (*.csv*)', 

        self.addParameter(QgsProcessingParameterString('please_enter_7_digit_village_code',
                          'Please enter 7 Digit village Code ', multiLine=False, defaultValue='code'))
        self.addParameter(QgsProcessingParameterString('village_name_please_enter_your_village_name_in_telugu',
                          'Village Name (Please enter your Village Name in Telugu)', multiLine=False, defaultValue='vill name'))
        self.addParameter(QgsProcessingParameterString('mandal_name_please_enter_mandal_name_in_telugu',
                          'Mandal Name (Please enter Mandal Name in Telugu)', multiLine=False, defaultValue='mandal name'))
        self.addParameter(QgsProcessingParameterString('district_name_please_enter_district_name_in_telugu',
                          'District Name (Please enter District name in Telugu)', multiLine=False, defaultValue='distri'))
        self.addParameter(QgsProcessingParameterString(
            'village_surveyor_name', 'Village Surveyor Name', multiLine=False, defaultValue='vs name'))

    def processAlgorithm(self, parameters, context, model_feedback):
        # Use a multi-step feedback, so that individual child algorithm progress reports are adjusted for the
        # overall progress through the model
        # Get a reference to the current project
        project = QgsProject.instance()

        # Set the names of the layers to remove
        layer_names = ['ULPIN', 'Resurvey_Land_Register', 'Prill_Lines',
                       'Final_Vertices', 'Exploded_Lines', 'Boundary', 'Vertices', 'Clip', 'Multi_Ring']

        # Loop through all the layers in the project
        for layer in project.mapLayers().values():

            # Check if the layer's name is in the list of names to remove
            if layer.name() in layer_names:

                # Remove the layer from the project
                project.removeMapLayer(layer.id())

        feedback = QgsProcessingMultiStepFeedback(40, model_feedback)
        results = {}
        outputs = {}

        # Extract RLR by expression
        alg_params = {
            'EXPRESSION': ' "Field4" != \'4a\'  and\r\n "Field4" != \'Extent\'\r',
            'INPUT': parameters['choose_your_rlrdlr_form38_resurvey_land_register'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['ExtractRlrByExpression'] = processing.run(
            'native:extractbyexpression', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(1)
        if feedback.isCanceled():
            return {}

        # Village_Name
        alg_params = {
            'NAME': 'Village_Name',
            'VALUE': parameters['village_name_please_enter_your_village_name_in_telugu']
        }
        outputs['Village_name'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(2)
        if feedback.isCanceled():
            return {}

        # Save ULPIN Layer to Project Folder
        alg_params = {
            'DATASOURCE_OPTIONS': '',
            'INPUT': parameters['choose_your_ulpin_layer'],
            'LAYER_NAME': '',
            'LAYER_OPTIONS': '',
            'OUTPUT': (project_folder + '/ULPIN.csv'),

        }
        outputs['SaveUlpinLayerToProjectFolder'] = processing.run(
            'native:savefeatures', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(3)
        if feedback.isCanceled():
            return {}

        # Polygon spatial index
        alg_params = {
            'INPUT': parameters['village_final_shape_file']
        }
        outputs['PolygonSpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(4)
        if feedback.isCanceled():
            return {}

        # Village Surveyor Name
        alg_params = {
            'NAME': 'VS_Name',
            'VALUE': parameters['village_surveyor_name']
        }
        outputs['VillageSurveyorName'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(5)
        if feedback.isCanceled():
            return {}

        # Mandal_Name
        alg_params = {
            'NAME': 'Mandal_Name',
            'VALUE': parameters['mandal_name_please_enter_mandal_name_in_telugu']
        }
        outputs['Mandal_name'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(6)
        if feedback.isCanceled():
            return {}

        # Village_Code
        alg_params = {
            'NAME': 'Village_Code',
            'VALUE': parameters['please_enter_7_digit_village_code']
        }
        outputs['Village_code'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(7)
        if feedback.isCanceled():
            return {}

        # District_Name
        alg_params = {
            'NAME': 'District_Name',
            'VALUE': parameters['district_name_please_enter_district_name_in_telugu']
        }
        outputs['District_name'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(8)
        if feedback.isCanceled():
            return {}

        # LPM_NO
        alg_params = {
            'NAME': 'LPM_NO',
            'VALUE': parameters['lpm_number_column']
        }
        outputs['Lpm_no'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(9)
        if feedback.isCanceled():
            return {}

        # Ref_Col Calcluation
        alg_params = {
            'FIELD_LENGTH': 10,
            'FIELD_NAME': 'Ref_Col',
            'FIELD_PRECISION': 0,
            'FIELD_TYPE': 1,  # Integer (32 bit)
            'FORMULA': 'attribute(@LPM_NO)',
            'INPUT': outputs['PolygonSpatialIndex']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['Ref_colCalcluation'] = processing.run(
            'native:fieldcalculator', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(10)
        if feedback.isCanceled():
            return {}

        # Retain fields In RLR
        alg_params = {
            'FIELDS': ['Field1', 'Field4', 'Field6', 'Field8', 'Field12', 'Field13', 'Field14'],
            'INPUT': outputs['ExtractRlrByExpression']['OUTPUT'],
            'OUTPUT': project_folder + '/RLR_excel.xlsx',
            'OUTPUT': project_folder + '/RLR_excel.xlsx'
        }
        outputs['RetainFieldsInRlr'] = processing.run(
            'native:retainfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(11)
        if feedback.isCanceled():
            return {}

        # Boundary
        alg_params = {
            'INPUT': outputs['Ref_colCalcluation']['OUTPUT'],
            'OUTPUT': project_folder +  '/Boundary.shp',
            'OVERWRITE': True

        }
        outputs['Boundary'] = processing.run(
            'native:boundary', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(12)
        if feedback.isCanceled():
            return {}

        # Load ULPIN Layer into project
        alg_params = {
            'INPUT': outputs['SaveUlpinLayerToProjectFolder']['OUTPUT'],
            'NAME': 'ULPIN'
        }
        outputs['LoadUlpinLayerIntoProject'] = processing.run(
            'native:loadlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(13)
        if feedback.isCanceled():
            return {}

        # Area_in_Acres
        alg_params = {
            'NAME': 'Area_in_Acres',
            'VALUE': parameters['area_in_acres_column_choose_your_acre_column_according_to_your_shape_file']
        }
        outputs['Area_in_acres'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(14)
        if feedback.isCanceled():
            return {}

        # Area_in_Hectares
        alg_params = {
            'NAME': 'Area_in_Hectares',
            'VALUE': parameters['area_in_hectares_column_choose_your_hectares_column_according_to_your_shape_file']
        }
        outputs['Area_in_hectares'] = processing.run(
            'native:setprojectvariable', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(15)
        if feedback.isCanceled():
            return {}

        # Load RLR into project
        alg_params = {
            'INPUT': outputs['RetainFieldsInRlr']['OUTPUT'],
            'NAME': 'Resurvey_Land_Register'
        }
        outputs['LoadRlrIntoProject'] = processing.run(
            'native:loadlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(16)
        if feedback.isCanceled():
            return {}

        # Extract vertices
        alg_params = {
            'INPUT': outputs['Ref_colCalcluation']['OUTPUT'],
            'OUTPUT': project_folder + '/Vertices.shp',
            'OUTPUT': project_folder + '/Vertices.shp'
        }
        outputs['ExtractVertices'] = processing.run(
            'native:extractvertices', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(17)
        if feedback.isCanceled():
            return {}

        # Refactor Vertices
        alg_params = {
            'FIELDS_MAPPING': [{'expression': "y( transform( $geometry,@layer_crs,\r\n'EPSG:4326'))", 'length': 10, 'name': 'LATITUDE', 'precision': 6, 'sub_type': 0, 'type': 6, 'type_name': 'double precision'}, {'expression': "x( transform( $geometry,@layer_crs,\r\n'EPSG:4326'))", 'length': 10, 'name': 'LONGITUDE', 'precision': 6, 'sub_type': 0, 'type': 6, 'type_name': 'double precision'}, {'expression': '$x', 'length': 10, 'name': 'EASTING_X', 'precision': 1, 'sub_type': 0, 'type': 6, 'type_name': 'double precision'}, {'expression': '$y', 'length': 10, 'name': 'NORTHING_Y', 'precision': 1, 'sub_type': 0, 'type': 6, 'type_name': 'double precision'}, {'expression': '"Ref_Col"', 'length': 10, 'name': 'Ref_Col', 'precision': 0, 'sub_type': 0, 'type': 4, 'type_name': 'int8'}],
            'INPUT': outputs['ExtractVertices']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['RefactorVertices'] = processing.run(
            'native:refactorfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(18)
        if feedback.isCanceled():
            return {}

        # Boundary spatial index
        alg_params = {
            'INPUT': outputs['Boundary']['OUTPUT']
        }
        outputs['BoundarySpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(19)
        if feedback.isCanceled():
            return {}

        # Explode lines
        alg_params = {
            'INPUT': outputs['BoundarySpatialIndex']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['ExplodeLines'] = processing.run(
            'native:explodelines', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(20)
        if feedback.isCanceled():
            return {}

        # Refactor Exploded Lines
        alg_params = {
            'FIELDS_MAPPING': [{'expression': '"Ref_Col"', 'length': 10, 'name': 'Ref_Col', 'precision': 0, 'sub_type': 0, 'type': 2, 'type_name': 'integer'}, {'expression': 'length3D( $geometry)', 'length': 10, 'name': 'Length', 'precision': 1, 'sub_type': 0, 'type': 6, 'type_name': 'double precision'}],
            'INPUT': outputs['ExplodeLines']['OUTPUT'],
            'OUTPUT': project_folder + '/Exploded_Lines.shp',
            'OUTPUT': project_folder + '/Exploded_Lines.shp'
        }
        outputs['RefactorExplodedLines'] = processing.run(
            'native:refactorfields', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(21)
        if feedback.isCanceled():
            return {}

        # Load Exploded_Lines into project
        alg_params = {
            'INPUT': outputs['RefactorExplodedLines']['OUTPUT'],
            'NAME': 'Exploded_Lines'
        }
        outputs['LoadExploded_linesIntoProject'] = processing.run(
            'native:loadlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(22)
        if feedback.isCanceled():
            return {}
  # Create ULPIN attribute index
        # alg_params = {
        #     'FIELD': "pniu",
        #     'INPUT': outputs['LoadUlpinLayerIntoProject']['OUTPUT']
        # }
        # outputs['CreateUlpinAttributeIndex'] = processing.run(
        #     'native:createattributeindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # feedback.setCurrentStep(23)
        # if feedback.isCanceled():
        #     return {}

        # Multi-ring buffer (constant distance)
        alg_params = {
            'DISTANCE': parameters['prill_line_length_multi_ring_length'],
            'INPUT': outputs['ExtractVertices']['OUTPUT'],
            'OUTPUT': project_folder + '/Multi_Ring.shp',
            'RINGS': 1,
            'OUTPUT': project_folder + '/Multi_Ring.shp'
        }
        outputs['MultiringBufferConstantDistance'] = processing.run(
            'native:multiringconstantbuffer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(23)
        if feedback.isCanceled():
            return {}

        # # Create RLR attribute index
        # alg_params = {
        #     'FIELD': 'Field1',
        #     'INPUT': outputs['LoadRlrIntoProject']['OUTPUT']
        # }
        # outputs['CreateRlrAttributeIndex'] = processing.run(
        #     'native:createattributeindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        # feedback.setCurrentStep(25)
        # if feedback.isCanceled():
        #     return {}

        # Delete duplicates by attribute in Vertices
        alg_params = {
            'FIELDS': QgsExpression(" 'Ref_Col;EASTING_X;NORTHING_Y'").evaluate(),
            'INPUT': outputs['RefactorVertices']['OUTPUT'],
            'OUTPUT': QgsProcessing.TEMPORARY_OUTPUT
        }
        outputs['DeleteDuplicatesByAttributeInVertices'] = processing.run(
            'native:removeduplicatesbyattribute', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(24)
        if feedback.isCanceled():
            return {}

        # Multiring spatial index
        alg_params = {
            'INPUT': outputs['MultiringBufferConstantDistance']['OUTPUT']
        }
        outputs['MultiringSpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(25)
        if feedback.isCanceled():
            return {}

        # Clip
        alg_params = {
            'INPUT': outputs['BoundarySpatialIndex']['OUTPUT'],
            'OUTPUT': project_folder + '/Clip.shp',
            'OVERLAY': outputs['MultiringSpatialIndex']['OUTPUT'],
            'OUTPUT': project_folder + '/Clip.shp'
        }
        outputs['Clip'] = processing.run(
            'native:clip', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(26)
        if feedback.isCanceled():
            return {}

        # Explode Lines spatial index
        alg_params = {
            'INPUT': outputs['LoadExploded_linesIntoProject']['OUTPUT']
        }
        outputs['ExplodeLinesSpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(27)
        if feedback.isCanceled():
            return {}

        # Prill Lines
        alg_params = {
            'INPUT': outputs['Clip']['OUTPUT'],
            'OUTPUT': project_folder + '/Prill_Lines.shp',
            'OUTPUT': project_folder + '/Prill_Lines.shp'
        }
        outputs['PrillLines'] = processing.run(
            'native:explodelines', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(28)
        if feedback.isCanceled():
            return {}

        # Add Point_ID field
        alg_params = {
            'FIELD_NAME': 'Point_ID',
            'GROUP_FIELDS': ['Ref_Col'],
            'INPUT': outputs['DeleteDuplicatesByAttributeInVertices']['OUTPUT'],
            'MODULUS': 0,
            'OUTPUT': project_folder + '/Final_Vertices.shp',
            'SORT_ASCENDING': True,
            'SORT_EXPRESSION': '',
            'SORT_NULLS_FIRST': False,
            'START': 1,
            'OUTPUT': project_folder + '/Final_Vertices.shp'
        }
        outputs['AddPoint_idField'] = processing.run(
            'native:addautoincrementalfield', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(29)
        if feedback.isCanceled():
            return {}

        # Load Final_Vertices into project
        alg_params = {
            'INPUT': outputs['AddPoint_idField']['OUTPUT'],
            'NAME': 'Final_Vertices'
        }
        outputs['LoadFinal_verticesIntoProject'] = processing.run(
            'native:loadlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(30)
        if feedback.isCanceled():
            return {}

        # Load Prill_Lines into project
        alg_params = {
            'INPUT': outputs['PrillLines']['OUTPUT'],
            'NAME': 'Prill_Lines'
        }
        outputs['LoadPrill_linesIntoProject'] = processing.run(
            'native:loadlayer', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(31)
        if feedback.isCanceled():
            return {}

        # Create Final vertices spatial index
        alg_params = {
            'INPUT': outputs['LoadFinal_verticesIntoProject']['OUTPUT']
        }
        outputs['CreateFinalVerticesSpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(32)
        if feedback.isCanceled():
            return {}

        # Create attribute index Final_Vertices
        alg_params = {
            'FIELD': 'Ref_Col',
            'INPUT': outputs['LoadFinal_verticesIntoProject']['OUTPUT']
        }
        outputs['CreateAttributeIndexFinal_vertices'] = processing.run(
            'native:createattributeindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(33)
        if feedback.isCanceled():
            return {}

        # Create Prill line spatial index
        alg_params = {
            'INPUT': outputs['LoadPrill_linesIntoProject']['OUTPUT']
        }
        outputs['CreatePrillLineSpatialIndex'] = processing.run(
            'native:createspatialindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(34)
        if feedback.isCanceled():
            return {}

        # Create explde line attribute index
        alg_params = {
            'FIELD': 'Ref_Col',
            'INPUT': outputs['LoadExploded_linesIntoProject']['OUTPUT']
        }
        outputs['CreateExpldeLineAttributeIndex'] = processing.run(
            'native:createattributeindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(35)
        if feedback.isCanceled():
            return {}

        # Create polygon attribute index
        alg_params = {
            'FIELD': parameters['lpm_number_column'],
            'INPUT': parameters['village_final_shape_file']
        }
        outputs['CreatePolygonAttributeIndex'] = processing.run(
            'native:createattributeindex', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(36)
        if feedback.isCanceled():
            return {}

        # Set Polygon style
        alg_params = {
            'INPUT': parameters['village_final_shape_file'],
            'STYLE': os.path.dirname(__file__)+"/qmlfiles/Polygon_Style.qml"
        }
        outputs['SetPolygonStyle'] = processing.run(
            'native:setlayerstyle', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(37)
        if feedback.isCanceled():
            return {}

        # Set Exploded Lines style
        alg_params = {
            'INPUT': outputs['LoadExploded_linesIntoProject']['OUTPUT'],
            'STYLE': os.path.dirname(__file__)+"/qmlfiles/Exploded_Lines_Style.qml"
        }
        outputs['SetExplodedLinesStyle'] = processing.run(
            'native:setlayerstyle', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(38)
        if feedback.isCanceled():
            return {}

        # Set Final Vertices style
        alg_params = {
            'INPUT': outputs['LoadFinal_verticesIntoProject']['OUTPUT'],
            'STYLE': os.path.dirname(__file__)+"/qmlfiles/Final_Vertices_Style.qml"
        }
        outputs['SetFinalVerticesStyle'] = processing.run(
            'native:setlayerstyle', alg_params, context=context, feedback=feedback, is_child_algorithm=True)

        feedback.setCurrentStep(39)
        if feedback.isCanceled():
            return {}

        # Set Prill Line style
        alg_params = {
            'INPUT': outputs['LoadPrill_linesIntoProject']['OUTPUT'],
            'STYLE': os.path.dirname(__file__)+"/qmlfiles/Prill_lines_Style.qml"
        }
        outputs['SetPrillLineStyle'] = processing.run(
            'native:setlayerstyle', alg_params, context=context, feedback=feedback, is_child_algorithm=True)
        return results

    def name(self):
        return 'LPM Processing Model'

    def displayName(self):
        return 'LPM Processing Model'

    def group(self):
        return ''

    def groupId(self):
        return ''

    def shortHelpString(self):
        return """help"""

    def createInstance(self):
        return LpmProcessingModelAlgorithm()

### Versions

QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

it was working sometimes once i ran for 1 st it works then causes the error

**Comment by nicogodet** [comment]
On windows, you need to use forward slashes in path.
`Could not create layer D:/R-Lpms/test/modeltest/modeltest\Boundary.shp`
You have a backward slash somewhere that cause the issue.

This is not a QGIS issue at first sight, your code needs a fix.

**Comment by lokesh2b6** [comment]
> On windows, you need to use forward slashes in path. `Could not create layer D:/R-Lpms/test/modeltest/modeltest\Boundary.shp` You have a backward slash somewhere that cause the issue.
> 
> This is not a QGIS issue at first sight, your code needs a fix.

I tried with both forward and backward slashes nothing helps

**Comment by nicogodet** [comment]
Your script is quite long. You need to try to identify where it fails exactly (add print, remove part of it temporarily, ...).
