### ISSUE TITLE
bagg

### ISSUE THREAD

**Issue by saim1960** [qgis/QGIS#52403]
### What is the bug or the crash?

 Quando si utilizza QGIS si ha il seguente errore:
 Python Stack Trace
Windows fatal exception: access violation

Thread 0x00001560 (most recent call first):

Stack Trace

QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00001560 (most recent call first):

Stack Trace

QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterDrawer::draw :
QgsRasterLayerRendererFeedback::onNewData :
QgsRasterDataProvider::block :
QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :
QgsRasterIterator::readNextRasterPartInternal :
QgsRasterDrawer::draw :
QgsRasterDrawer::draw :
QgsRasterLayerRenderer::render :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

### Versions

30.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

stesso problema anche su altro pc con windows 11

**Comment by saim1960** [comment]
Buongiorno, il problema non è stato risolto.

E' un crash continuo che si verifica quando si effettuano gli zoom o quando
si attivano o disattivano i layer.
Il problema si verifica sempre ed in ogni caso quando il programma deve
ricalcolare le immagine attive dei layer.
Allego la segnalazione tipica di qgis.

Saluti
Santo



Il giorno mar 11 apr 2023 alle ore 04:38 github-actions[bot] <
***@***.***> ha scritto:

**Comment by agiudiceandrea** [comment]
@sim1960 please:
1. attach the crash report in a comment of this issue report using the GitHub web interface
2. provide the detailed steps / layer(s) / project in order to reproduce the crash
3. try if the issue does occur actually also using a new QGIS user profile
