### ISSUE TITLE
"Fix Geometries" crashing QGIS

### ISSUE THREAD

**Issue by tsmcgrath** [qgis/QGIS#52437]
### What is the bug or the crash?

I'm running QGIS 2.28.4 LTR. Fix Geometries is crashing QGIS as a whole.
What happened: 
- See Repro
Expected: 
- Fix geometries should repair issues preventing clipping the dataset to another polygon.

### Steps to reproduce the issue

What happened:
I downloaded a vector dataset from the Texas Parks and Wildlife GIS data repository. When I tried to clip it to my study area (San Saba Basin) it reported vector geometry errors. So, I ran "Fix Geometry" on a subset that I had manually selected with a rectangle and saved to it's own dataset (since the full Edwards Plateau is so large). Immediately QGIS crashed. I repeated this behavior 2 more times and the same thing happened.

https://tpwd.texas.gov/gis/programs/landscape-ecology/by-ecoregion-vector

### Versions

===
QGIS version | 3.28.4-Firenze | QGIS code revision | 766501dd8b
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.2
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
ORStools | 1.5.2
batchvectorlayersaver | 0.9
batch_gps_importer | version 1.0.1
GpxSegmentImporter | 2.5
QuickOSM | 2.2.0
quick_map_services | 0.19.33
qgis2wegue | 1.1.1
LAStools | 1.4
OpenTripPlannerPlugin | 1.0.1
ImportPhotos | 3.0.5
qgis2web | 3.16.0
Beeline | 0.2.0
qgis-maptiler-plugin | 3.2
CSMapMaker | 0.5
Mergin | 2023.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.4-Firenze
QGIS code revision
[766501dd8b](https://github.com/qgis/QGIS/commit/766501dd8b)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.2

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
ORStools
1.5.2
batchvectorlayersaver
0.9
batch_gps_importer
version 1.0.1
GpxSegmentImporter
2.5
QuickOSM
2.2.0
quick_map_services
0.19.33
qgis2wegue
1.1.1
LAStools
1.4
OpenTripPlannerPlugin
1.0.1
ImportPhotos
3.0.5
qgis2web
3.16.0
Beeline
0.2.0
qgis-maptiler-plugin
3.2
CSMapMaker
0.5
Mergin
2023.1
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
Where you asking it to save the result in a temporary layer and were you on a system with less than ~12GB RAM? The resulting memory layer takes about 8GB so I assume that QGIS ran out of RAM on your machine.

If you tell it to write the result to a file, it should be quite conservative on RAM usage and will probably finish this task successfully.

**Comment by tsmcgrath** [comment]
I recall it was to a temporary layer. I'll try the file. Thanks!

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/50888

**Comment by tsmcgrath** [comment]
I repeated this and set the output to a Geopackage. Same issue. Crashes.

**Comment by tsmcgrath** [comment]
Yes, looks like a dupe of #50888. Sigh. I searched before I opened this. Must have been a bad search. Closing as a duplicate.
