### ISSUE TITLE
Split and save features are not working properly QGIS 3.30 

### ISSUE THREAD

**Issue by sudochek** [qgis/QGIS#52438]
### What is the bug or the crash?

Hi!
I have a problem with the "split features" and "save option." 

The "saving" function is merging all of my features. For instance, I have used cshape file => started to split features => save edited => the program merged everything into one feature. 

And the second problem: every time I am splitting, it just erases the outer border of my polygon.

I have cleared RAM; downloaded different versions of QGIS to check if it's connected to the newest updated one; relaunched the program dozens of times; however, it's still not working properly. I have attached video to illustrate the problems. Hope, it helps!

https://user-images.githubusercontent.com/129289331/228597548-a3c744bd-de09-4b7b-9ee5-89d85273969e.mov

### Steps to reproduce the issue

Start to split features => save edited => the program merged everything into one feature. 

### Versions

QGIS version | 3.30.0-'s-Hertogenbosch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
@sudochek Can you try with a [new user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), and also update the issue title to mention 3.30 and not 3.3?

**Comment by sudochek** [comment]
> @sudochek Can you try with a [new user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), and also update the issue title to mention 3.30 and not 3.3?

Yes, I have tried a new user profile, but the same issue happened, unfortunately :(

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (36c53ea14ced0975ecde67027f8468770ebcd67d). Please provide sample data.
