### ISSUE TITLE
Can no longer do single threaded map rendering

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#52436]
### What is the bug or the crash?

After the changes in #49444, the max cores spinbox does not accept `1` as a value, it switches to max available instead.

### Steps to reproduce the issue

- Go to Settings > Options > Rendering > Maximum cores to use for rendering
- Try to set it to `1`

### Versions

Introduced with #49444, so 3.28 and on

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

With the change to the widget's wording, the keywords `parallel` and `cpu` no longer find this setting using search. It would be nice if they were added back.

**Comment by nicogodet** [comment]
See https://github.com/qgis/QGIS/pull/52078

**Comment by uclaros** [comment]
Thanks, I must have missed that.
