### ISSUE TITLE
"Raster auf Layermaske zuschneiden" crashes when mask filename has a German Umlaut

### ISSUE THREAD

**Issue by ojnssn** [qgis/QGIS#52430]
### What is the bug or the crash?

<img width="1615" alt="Bildschirm­foto 2023-03-29 um 10 14 21" src="https://user-images.githubusercontent.com/129268344/228472395-9fb4517b-091d-4285-a971-83ef8a3cab12.png">

### Steps to reproduce the issue

 use a raster file, create a vector file with umlaut, run the "cut to layer" Geotool - get the bug

### Versions

QGIS LTR 3.22.16

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

workaround is to rename the file having no Umlauts

**Comment by agiudiceandrea** [comment]
@ojnssn QGIS 3.22 is no longer supported. Could you please try if the issue does occur using a currently supported QGIS version? Could you please provide sample layers with which the issue does occur?
