### ISSUE TITLE
Issue with coordinate field and System locale

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#52446]
### What is the bug or the crash?

In the coordinate field of my QGIS installation the coordinates are displayed using comma (",") as is expected in Denmark where I'm located:
![billede](https://user-images.githubusercontent.com/6311686/228816097-bb47aeea-2d1a-4c71-b7a0-b1beefd46cea.png)

- If I try to change the coordinate values using comma as decimal separator, nothing happens. 
- If I instead use a "." instead of "," it works. 

I would expect this to work independently of my regional settings / System locale and I think it used to in the past.

### Steps to reproduce the issue

1. Enable QGIS `Settings/Options/General`: Override System Locale
2. Set *User interface translation* to `American English`
3. Set *Locale (numbers...)* to `Danish Denmark (da_DK)`
4. Add a random layer.
5. Zoom in to specific coordinate until the coordinate field displays a location using the decimal separator.
6. Verify that the coordinate is displayed using comma as the separator.
7. Modify the coordinate to a different location using comma as the separator and press <ENTER>.
8. Verify that nothing happens.
9. Replace the decimal separator both places with a "." and press <ENTER>.
10. Verify that QGIS moved to the modified location.

### Versions

It happens both in 3.28.4 LTS, 3.30.0 and 3.31.0-Master ([288346e097]).

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
Please test this PR as soon as the package is ready https://github.com/qgis/QGIS/pull/52528
