### ISSUE TITLE
Misplaced markers when using offset

### ISSUE THREAD

**Issue by nts-eschert** [qgis/QGIS#52458]
### What is the bug or the crash?

The marker looks different in layer panel, layer styling panel and map canvas. It is very difficult to properly set up a symbology, when it's not wysiwyg.

Here is a picture of what I am talking about:
![image](https://user-images.githubusercontent.com/88319901/229068438-12084c86-6c10-49e8-9296-73fb3581a22f.png)
I am using a svg marker and a text marker, both aligned to bottom (so the pin tip shows the objects placement). This also happens when using two svg markers

### Steps to reproduce the issue

1. Set up a symbology with two markers
2. Align them to bottom
3. Set an offset for the upper marker

### Versions

QGIS-Version
3.28.0-Firenze
QGIS-Codeversion
ed3ad0430f3
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.2
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
GeometryShapes
0.7
Go2NextFeaturePlus
2.10
ImportPhotos
3.0.5
latlontools
3.6.9
LoadQSS
1.4.2
mmqgis
2021.9.10
ORStools
1.5.2
OSMDataSync
0.2
OSMDownloader
1.0.3
processing_saga_nextgen
0.0.7
qdraw
3.0.2
qfieldsync
v4.4.9
qgis-plugin-findreplace-main
1
qgis_resource_sharing
1.0.0
qNote
2.2
QuickOSM
2.2.0
quick_map_services
0.19.33
valhalla
2.4.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rnousia** [comment]
I tried to reproduce this with QGIS 3.30.1 (on linux) but at least using the built-in svg symbols it seems to work correctly:

![image](https://user-images.githubusercontent.com/12234068/233601121-7275932d-a757-4b25-8266-d058c7680489.png)

I aligned both symbol layers to Bottom + HCenter and added some y-offset for the font marker layer.

However, I did notice that your svg marker symbol seems to be aligned in the layer styling preview to the right, so I was wondering maybe there is something different in the svg file in itself? Could you provide the svg file used in your project or is it one of the built-in ones?

The svg seems to aligned bottom left:
![image](https://user-images.githubusercontent.com/12234068/233603827-e65f7baf-75ef-4ef8-ba86-0cd510995cda.png)

Compared to:
![image](https://user-images.githubusercontent.com/12234068/233604076-02c32763-ba2a-4523-b826-9b642b6bfa21.png)

I used these settings for the svg layer:
![image](https://user-images.githubusercontent.com/12234068/233604641-c6e30ffc-1c8d-4ffa-bb4d-b5a94cfb0416.png)
