### ISSUE TITLE
QGIS project crashes at 96% on startup - Windows fatal exception: access violation

### ISSUE THREAD

**Issue by geoman90** [qgis/QGIS#52453]
### What is the bug or the crash?

A colleague has been having trouble opening a project following a company-wide switch to OneDrive cloud storage. About half of the files were linked to the physical server location and half were directly on the computer hard drive. Following the switch to OneDrive, this project crashes at 96% each time it is opened. We have tried on 2 different machines and have replicated the issue. If it is a file linking issue, I would have expected a notification to fix file paths within the project.

We have both tried toggling on/off plugins on both QGIS 3.24, 3.28, and 3.3. A similar, older project with a .qgz format can be opened with many of the same vector/raster/etc files, but this newer file that cannot open is a .qgs format.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00009c8c (most recent call first):
<no Python frame>
```

**Stack Trace**
```
QgsFields::QgsFields :
QgsGrassProvider::fields :
QgsVectorLayer::updateFields :
QgsVectorLayer::readXml :
QgsMapLayer::readLayerXml :
QgsProject::addLayer :
QgsProject::_getMapLayers :
QgsProject::readProjectFile :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.0-Firenze
QGIS code revision: ed3ad0430f3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

1. Open project either from the QGIS File menu or double clicking from location on hard drive
2. QGIS loads to 96%
3. Application crashes, typically without a crash report
4. Where report is produced, the report details are the same.

### Versions

3.24, 3.28.0, and 3.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This was likely fixed by https://github.com/qgis/QGIS/pull/53317 -- please try with a newer QGIS version.

**Comment by nyalldawson** [comment]
(reopen if you can still reproduce)
