### ISSUE TITLE
Text "randomly" disappears from Python editors

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#52459]
### What is the bug or the crash?

Text sometimes, seemingly randomly, disappears from Python editors, e. g. the Python console, the script editor or the editor for editing models (probably the same).

I finally found a way to reproduce at least one of the ghosts that trigger this when switching to another application. It also sometimes happens without switching (on Ctrl-A or Ctrl-C I think) but I have not yet found a way to reproduce that (edit: might be the second steps below).

It seems like something weird happens if one switches from Python editor with selected text to a "text input" (something where my next keypress would enter a character, e. g. a terminal or text editor) of another window.

I have reproduced this with the Python console and its script editor. I have reproduced this with Firefox (while editing this text), Geany, xfce4-terminal, element-desktop. I have not reproduced this with keypassxc and only sometimes with retext.

It does **not** happen if I click on the Field Calculator icon in QGIS (opening a new window) which also results in an active text input. I also could not trigger this by switching to a secondary QGIS window with its Python console open.

### Steps to reproduce the issue A

1. Have a terminal or text editor window open and ready for text input
2. Open QGIS
3. Open the Python console (or script editor)
4. Type something in the Python console
5. Select the text in the Python console
6. Switch to the terminal or text editor (Alt-Tab or by clicking
7. Check the Python console, the text is gone

You should also be able to reproduce this if you open a new application window in step 6 if that application immediately have an active text input (reproduced with geany and xfce4-terminal, I did not test others).

### Steps to reproduce the issue B
1. Have selected text in a Python console or script editor.
1. Switch to another window that does not have a text input (e. g. mpv)
1. Switch to a window that has a text input (e. g. geany or a terminal)
1. Switch back to QGIS
1. Hit Ctrl or Alt
1. The text is gone

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.30.0-'s-Hertogenbosch | QGIS-Codeversion | f186b8efe0
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.10.6
GDAL-Version | 3.4.1
PROJ-Version | 8.2.1
EPSG-Registraturdatenbankversion | v10.041 (2021-12-03)
GEOS-Version | 3.10.2-CAPI-1.16.0
SQLite-Version | 3.37.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.4
QScintilla2-Version | 2.11.6
BS-Version | Ubuntu 22.04.2 LTS
  |   |   |  
Aktive Python-Erweiterungen
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

**If relevant: Clipboard contents (I am on xubuntu, using the Clipman manager, ask if I can test something more specific)**

- _I could not reproduce this later, might be a red herring and untrue_, best ignore: If I Ctrl-V on the application I have switched to, the selected text will be produced. The selected text is NOT what I had in my clipboard previously. E. g. if I Ctrl-A, Ctrl-C, then edit the script to include "foo", Ctrl-A, Alt-Tab to the other window, Ctrl-V, it will produce the last state of the selected text, including the "foo".

- _Might be unrelated but unexpected behaviour_: If I select text in the Python console's output pane (numbered lines above the input) , switch to another text input and Ctrl-V, the selected text will be pasted.

**Comment by kannes** [comment]
I will send a cake to whoever fixes this. No, really!

![giphy](https://user-images.githubusercontent.com/7661092/229077598-ae617b5f-6645-406a-83e9-84255f0b6f64.gif)

**Comment by uclaros** [comment]
This has tested my sanity on the expression editor and the query builder before!

**Comment by kannes** [comment]
> Probably related to #38942

Argh, I never saw that issue before. Looks 100% related but the title is more specific.
