### ISSUE TITLE
Error loading 'DigitizingTools' Plugin

### ISSUE THREAD

**Issue by ethiomoges** [qgis/QGIS#52463]
### What is the bug or the crash?

 While opening QGIS 3.30.0
 
 Python error : Couldn't load plugin 'DigitizingTools' due to an error when calling its initGui() method See message log (Python Error) for more details.

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/22833965/229124197-fe2ee49e-b9da-4fc3-99a1-945ba115cb96.png)

### Versions

3.30.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The tool is working properly with previous version of QGIS i.e. 3.28.3

**Comment by nicogodet** [comment]
Should be reported here : https://github.com/bstroebl/DigitizingTools/issues
