### ISSUE TITLE
PLY file exported in TIN Mesh Creation algorithm is incompatible with other mesh reader

### ISSUE THREAD

**Issue by basilrabi** [qgis/QGIS#52467]
### What is the bug or the crash?

PLY exported in QGIS is not readable in other PLY readers such as Blender, meshlab, and Paraview simply because QGIS uses uppercase for the vertex coordinate property name:

```
ply
format ascii 1.0
element vertex 825
property double X
property double Y
property double Z
```

Simply changing to lower case fixes the compatibility issue:

```
ply
format ascii 1.0
element vertex 825
property double x
property double y
property double z

```

### Steps to reproduce the issue

Use TIN Mesh Creation algorithm and export as ply.

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by vcloarec** [comment]
This is a MDAL issue, I reported the issue here: https://github.com/lutraconsulting/MDAL/issues/450

**Comment by runette** [comment]
Fix in https://github.com/lutraconsulting/MDAL/pull/453
