### ISSUE TITLE
Cannot re-open pull request

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#52478]
### What is the bug or the crash?

This is a management issue, not a code issue, I cannot re-open a pull request of mine:
https://github.com/qgis/QGIS/pull/49124

### Steps to reproduce the issue

I don't know how to reproduce, I suspect it has to do with stale bot closing it, but I'm not sure.

### Versions

N/A

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by m-kuhn** [comment]
There's a tooltip explaining the reasons. Looks like a github policy. I'd just create a new PR and keep this policy in mind.

![image](https://user-images.githubusercontent.com/588407/229275886-0df8e00e-1043-4cf2-8f25-c584e3b5f7ac.png)

**Comment by nyalldawson** [comment]
Not a qgis bug
