### ISSUE TITLE
QGIS window doesnt change size

### ISSUE THREAD

**Issue by chkaval** [qgis/QGIS#52498]
### What is the bug or the crash?

QGIS window doesn't change size when picking from the top and when i maximize the window, the bottom is hiden below the screen. I installed the latest version, tested different screen resolutions but the problem still exists. Suprisingly, when i connect an external screen to my laptop, the problem is solved!

### Steps to reproduce the issue

![capture](https://user-images.githubusercontent.com/47035224/229465663-63f9f9a7-60eb-48a7-9c67-41643a2de3b7.jpg)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
ee_plugin | 0.0.6
SemiAutomaticClassificationPlugin | 7.10.11
Smart_Map | 1.2
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.6
SemiAutomaticClassificationPlugin
7.10.11
Smart_Map
1.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@chkaval thanks for reporting. Could you please try if the issue does occur also using a new QGIS user profile?

**Comment by chkaval** [comment]
@agiudiceandrea The new user profile solved the problem!!! This was strange because previously  i had uninstalled and installed the software several times (trying also older versions) but apparently, the same profile was always somehow retrieved.
Thanks a lot!!!!

**Comment by agiudiceandrea** [comment]
@chkaval the QGIS user profiles folder is not stored in the QGIS installation folder https://docs.qgis.org/3.28/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles so it doesn't change after unistalling and reinstalling QGIS.
