### ISSUE TITLE
Modify the macOS app icon to conform Apple guidelines

### ISSUE THREAD

**Issue by gy-mate** [qgis/QGIS#52495]
### Feature description

According to Apple's [Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/foundations/app-icons#macos/), _"In macOS, app icons share a common set of visual attributes, including a rounded-rectangle shape, front-facing perspective, level position, and uniform drop shadow"_.

Please modify the app icon to conform all Apple guidelines for macOS.

**Comment by agiudiceandrea** [comment]
Duplicate of https://github.com/qgis/QGIS-Mac-Packager/issues/161.

**Comment by gymate-1** [comment]
Sorry about that! Thanks!
