### ISSUE TITLE
[3D] Enabling "show bounding boxes" in advanced settings crashes QGIS

### ISSUE THREAD

**Issue by ptitjano** [qgis/QGIS#52501]
### What is the bug or the crash?

In a 3D View, enabling "show bounding boxes"  in the advanced settings of a 3D View parameters crashes QGIS 

### Steps to reproduce the issue

1. Load some data with a terrain
2. Create a new 3D View
3. Go to the "Advanced" tab of 3D View configuration
4.  Click on "show bounding boxes"
5. Click on "apply" or "ok"
6. Crash

### Versions

3.31 commit 4ec82134755981583f649443dff8b0f85f637d83

I was also able to reproduce it with 3.28 and 3.22. It looks like the recent change to limit the scene extent made it easier to reproduce.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by uclaros** [comment]
Duplicate of #40766 ?

**Comment by ptitjano** [comment]
> Duplicate of #40766 ?

Indeed. My bad, I hadn't found it while searching for duplicates before creating this one.
