### ISSUE TITLE
Can't save Browser connections

### ISSUE THREAD

**Issue by johnwbryant** [qgis/QGIS#52519]
### What is the bug or the crash?

I can't save my Browser connections; the Manage Connections dialogue doesn't list any of them. Same issue with PostgreSQL, WMS, WFS, Vector Tiles, XYZ Tiles, ArcGIS Rest Servers.

### Steps to reproduce the issue

1. In the Browser, right click on a connection type (eg WMS) and choose "Save connections..."
2. In the Manage Connections dialog, there are no connections listed, even though I have several connections in the Browser.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 447e8d717a
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[447e8d717a](https://github.com/qgis/QGIS/commit/447e8d717a)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I am able to load connections in the usual way, just can't save them.

**Comment by agiudiceandrea** [comment]
@3nids, maybe it has something to do with some settings migration?
