### ISSUE TITLE
Missing explicit stdint.h causing build issue of recent openSUSE Tumbleweed

### ISSUE THREAD

**Issue by stoecker** [qgis/QGIS#52526]
### What is the bug or the crash?

QGIS doesn't build.

### Steps to reproduce the issue

Build QGIS 3.30.0 on openSUSE Tumbleweed.

### Versions

3.30.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

Some include files use stdint types, but don't include stdint and rely on other includes to do so. Some changes in includes causes this assumption to fail. Fix is to explicitely include stdint. Patch used for openSUSE is attached.

**Comment by stoecker** [comment]
```
diff -ur qgis-3.30.0/external/lazperf/Extractor.hpp qgis-3.30.0_fix/external/lazperf/Extractor.hpp
--- qgis-3.30.0/external/lazperf/Extractor.hpp	2023-03-03 20:25:40.000000000 +0100
+++ qgis-3.30.0_fix/external/lazperf/Extractor.hpp	2023-04-04 09:00:06.127250079 +0200
@@ -34,6 +34,7 @@
 
 #pragma once
 
+#include <cstdint>
 #include <cstring>
 #include <vector>
 
diff -ur qgis-3.30.0/external/untwine/api/QgisUntwine.hpp qgis-3.30.0_fix/external/untwine/api/QgisUntwine.hpp
--- qgis-3.30.0/external/untwine/api/QgisUntwine.hpp	2023-03-03 20:25:40.000000000 +0100
+++ qgis-3.30.0_fix/external/untwine/api/QgisUntwine.hpp	2023-04-04 09:40:57.344786266 +0200
@@ -1,5 +1,6 @@
 #pragma once
 
+#include <cstdint>
 #include <map>
 #include <string>
 #include <vector>
diff -ur qgis-3.30.0/external/untwine/untwine/VoxelKey.hpp qgis-3.30.0_fix/external/untwine/untwine/VoxelKey.hpp
--- qgis-3.30.0/external/untwine/untwine/VoxelKey.hpp	2023-03-03 20:25:40.000000000 +0100
+++ qgis-3.30.0_fix/external/untwine/untwine/VoxelKey.hpp	2023-04-04 08:48:07.969689579 +0200
@@ -10,6 +10,7 @@
  *                                                                           *
  ****************************************************************************/
 
+#include <cstdint>
 #include <string>
 #include <algorithm>
 

```

**Comment by rouault** [comment]
lazperf/Extractor.hpp issue has already been fixed per https://github.com/qgis/QGIS/pull/52229

CC @wonder-sk for the external/untwine related fixes that aren't patched yet AFAICS

**Comment by rouault** [comment]
Actually the missing include in external/untwine are covered by PR https://github.com/qgis/QGIS/pull/52464, but they need to be upstreamed

**Comment by alexbruy** [comment]
Can be closed?

**Comment by stoecker** [comment]
We dropped our patch with the update to 3.32.0 in July.
