### ISSUE TITLE
QGIS will crash when accessing the scale toggle and won't display the whole scale factor

### ISSUE THREAD

**Issue by tombcd** [qgis/QGIS#52529]
### What is the bug or the crash?

QGIS crashes when trying to access the view scale toggle. It also won't display the whole scale value.

### Steps to reproduce the issue

1. Start the app.
2. Open project (or not).
3. Try to change the scale using the scale toggle at the bottom.

![QGIS_Crash](https://user-images.githubusercontent.com/129850528/229775098-622cdf2f-2d65-4a15-94ec-53f589fe9ead.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
dimensioning | 0.2
gissupport_plugin | 1.14
quick_map_services | 0.19.33
wody_polskie_wms | 1.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
dimensioning
0.2
gissupport_plugin
1.14
quick_map_services
0.19.33
wody_polskie_wms
1.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by elpaso** [comment]
see: https://github.com/qgis/QGIS/pull/52511

**Comment by 3nids** [comment]
fixed by https://github.com/qgis/QGIS/pull/52511
