### ISSUE TITLE
Elevation profile: Save layers configuration

### ISSUE THREAD

**Issue by cesarcorreo** [qgis/QGIS#52549]
### Feature description

Possibility to save the current profile (layers actived in the profile) as a template. When you have lots of layers included in the profile its easy to forget some of them.

### Additional context

When the profile is made up of several layers, each time the tool is opened, the layers appear changed in order (I don't know by what criteria). Would it be possible to save several layer order profiles or at least to keep them as they were the previous time? (In map window and print composer)
![Save layer order](https://user-images.githubusercontent.com/25932761/230056663-a6ecd7ff-3580-4a61-b5de-66cbfb7fba23.jpg)

**Comment by nicogodet** [comment]
@cesarcorreo Should be added with mentioned PR
