### ISSUE TITLE
Elevation profile improvements

### ISSUE THREAD

**Issue by cesarcorreo** [qgis/QGIS#52546]
### Feature description

1. Possibility to export to DXF in coordenates (2D & 3D) as the terrain profile pluging do.
2. Possibility to add authomatic / manual labels (name of the layer and name of the elements in the layer like points, poligons, etc.) 
3. Possibility to save the current profile (layers actived in the profile) as a template. When you have lots of layers included in the profile its easy to forget some of them.
4. Automate the size reserved for the profile in the print composer.
5. Add the possibility of scaling

### Additional context

2- Adding labels to the profile would make it easier to identify elements that sometimes make it difficult to identify the elements represented in the profile. (An example of a geological section with the research campaign is attached). (In map window and print composer)
![Labels](https://user-images.githubusercontent.com/25932761/230023910-173f837c-c48c-409a-9a00-ea8ad6523aad.jpg)
3- When the profile is made up of several layers, each time the tool is opened, the layers appear changed in order (I don't know by what criteria). Would it be possible to save several layer order profiles or at least to keep them as they were the previous time? (In map window and print composer)
![Save layer order](https://user-images.githubusercontent.com/25932761/230024883-c2aa89cf-0b04-4ba7-94ed-3c91cb0447f2.jpg)

4- Generally, in the print designer, a box is drawn to add the elements. 
This size can be automated but it is quite complex to associate the size of this box to the profile to be represented, especially if you are generating an atlas composed of many profiles of different sizes. It would be very practical if the size of the box were limited to the maximum extent of the layers represented in the profile.
![box](https://user-images.githubusercontent.com/25932761/230028007-f56fd71f-6389-4862-a924-19114c5896d4.jpg)

5- Both vertical and horizontal scales are essential, so it would be very practical to add the possibility to choose the scales of each section (e.g. associated to the attribute table).

**Comment by nicogodet** [comment]
As already mention in one of your previous feature request, please create ONE ticket per feature request with a meaningful tittle.

**Comment by nicogodet** [comment]
@cesarcorreo Can close now ?

**Comment by cesarcorreo** [comment]
Yes, Thanks
