### ISSUE TITLE
Navigation in Qfield 

### ISSUE THREAD

**Issue by diegofhernandez98** [qgis/QGIS#52541]
### What is the bug or the crash?

Hello, im using Qfield to navigate in my phone. However, im experimenting a issue because the address are not well positioned over the map, it is showing a straight line. 
![issue](https://user-images.githubusercontent.com/129914865/229955504-b9fb0cc0-0066-4054-ad83-a14c42a50fbb.png)

### Steps to reproduce the issue

setting a destination the issue is coming out. 

### Versions

Qfield

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Please report this issue in the QField [repository](https://github.com/opengisch/QField)
