### ISSUE TITLE
QGIS 3.30.1 Windows: no reaction for any seconds often

### ISSUE THREAD

**Issue by jojo-gfx** [qgis/QGIS#52554]
### What is the bug or the crash?

Was try any versions of QGIS but all have the effect to go in a no reaction modus really often (1x per minute min.) on normal usage and relative anytime, if I used another software (browser or so) between... then nearly 100% the QGIS is sleeping and need many seconds to find themself back to work.
CPU and so on isn't higher then. Also doesnt matter what is opened or also in fresh open state it is the case.
Was try out the bugfix of userprofile reset, but it has no real effect and if yes, so only shortly.

Also other Windows (10/64) users with such problems there? 
QGIS is unusable so and my nerves are ruined per work with it... :(

Can anyone see, where could be the problem here?

### Steps to reproduce the issue

Doesn't matter what I do. It's coming from nowhere. 

### Versions

3.30.1 and also before has hat the problem

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Might be connection issue with your data sources if it's limited by the reading speed of layers or data storage&access (in the browser)

**Comment by jojo-gfx** [comment]
It also is the case if I have nothing open. Only start the QGIS and do nothing and only click around without real activate functions it will start after around 20s and the bug is there.

If it is a connection issue, does QGIS open definded connections also if I not open them in the source browser on the left side?
This would be no good idea and if yes, why does QGIS do that?

**Comment by YoannQDQ** [comment]
Might be related to #52530

**Comment by jojo-gfx** [comment]
Ah, perfect workaround and it works.
But, if the problem is known, why is it still present? Many users will run again a wall so... :(

A good Idea here would be to test such drives one time and on no response, don't try again. Instead would it a good idea to grey out the symbols (not hide completely) automatically, so the user can activate them per hand, if he/she need. :)
I'm not a friend of too much background services, because the most users if this sort of software are on professional niveau in using computers and can self handle data options. Isn't good here to think/program for computer newbies.

Nearby...
Also not so nice is the freezes of the software, if anything is in calculation. Also here would be a symbolic needed what is showing the state of the software. 

Thank you and greetings! :)
