### ISSUE TITLE
Error in the scale tab of the QGIS 3.30 main window

### ISSUE THREAD

**Issue by Danny-Vasco** [qgis/QGIS#52556]
### What is the bug or the crash?

Tengo un pequeño problema e reinstalado QGIS 3.30 y el problema persiste y este es referente a la pestaña de escala la cual aparece recortada y no me permite ver la información, adicionalmente al yo dar clic QGIS se cierra después de unos segundos.

Adjunto una captura y un video del problema.
![image](https://user-images.githubusercontent.com/91226131/230096076-a188edd4-06b8-4942-86d8-a5a9b0821067.png)

https://drive.google.com/file/d/1O54YPLmFvWivoReQWtaKDimxe-LQnYtn/view?usp=share_link

### Steps to reproduce the issue

Al iniciar QGIS ingreso a la página principal y la pestaña de escala me aparece con un bug, y esa no se soluciona agregando capas etc, persiste dicho problema.

El inconveniente se encuentra al dar clic en la opción pues cierra por completo el programa.

![image](https://user-images.githubusercontent.com/91226131/230096413-5c99802e-db0f-4cbf-ab37-f31968f96cde.png)

### Versions

Versión de QGIS
3.30.1-'s-Hertogenbosch
Revisión del código de QGIS
9035a01e
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.6.3
Versión de PROJ
9.2.0
Versión del registro de base de datos EPSG
v10.082 (2023-02-06)
Versión de GEOS
3.11.2-CAPI-1.17.2
Versión de SQLite
3.41.1
Versión de PDAL
2.5.2
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
autoSaver
2.6
coordinate_capture
0.2
layout_loader
1.1
profiletool
4.2.4
qconsolidate3
0.2.0
qgis-maptiler-plugin
3.2
qgisgbifapi
0.3.2
qgis_resource_sharing
1.0.0
quick_map_services
0.19.33
SemiAutomaticClassificationPlugin
7.10.11
SVG2ColoR
1.0
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by jef-n** [comment]
duplicate of #52383

**Comment by Danny-Vasco** [comment]
Gracias por su ayuda

**Comment by abdoulaye2019** [comment]
Thank very much it's work @agiudiceandrea
