### ISSUE TITLE
createVectorTable doesn't work anymore for geopackage table in QGIS 3.28

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#52552]
### What is the bug or the crash?

Since QGIS 3.28, in python plugin, the following python code to create a new geopackage table doesn't work anymore:
`ipath = "C:/TEST/planurba.gpkg"`
`md = QgsProviderRegistry.instance().providerMetadata('ogr')`
`self.conn = md.createConnection(ipath, {})`
`self.conn.createVectorTable('', lrName, vp_flds, spType, self.projCrs, True, {})`
The error message returned is:
_core.QgsProviderConnectionException: Impossible d’obtenir le pilote pour la connexion
(impossible to obtain the driver for the connexion)
The same code works well with QGIS 3.22.16. The problem appears in QGIS 3.28.4

### Steps to reproduce the issue

Use the code above in a python plugin.

### Versions

Version de QGIS
3.28.4-Firenze
Révision du code
fd0fb72ab3
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
SgmDxfImportPro
3.22.20
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
The issue occurs since QGIS versions 3.28.0, while it doesn't occur with QGIS versions <= 3.26.3.
The displayed error in the Python console is:
`_core.QgsProviderConnectionException: Could not retrieve driver for connection`

The issue occurs when the GeoPackage file doesn't exist before the execution of the code, while it doesn't occur if it exists.

It seems to me the issue may have been introduced with https://github.com/qgis/QGIS/pull/49134.

**Comment by nyalldawson** [comment]
This was an API bug in the earlier versions, because it made it impossible to create tables in non gpkg datasets. You should use createEmptyDatabase to create an empty database first. See https://github.com/qgis/QGIS/pull/49342/commits/b0d5612fe7c60187a34ea0a353fddb22a9574a69

**Comment by sigmoe** [comment]
Ok, thank you for the answer. It works with createDatabase.
