### ISSUE TITLE
error when trying to install qgis

### ISSUE THREAD

**Issue by laurasanttoss** [qgis/QGIS#52564]
### What is the bug or the crash?

When I try to install qgis the following error appears "The cabinet file 'application.cab' required for this installation is corrupt and cannot be used. This could indicate a network error, an error reading from the CD-ROM, or a problem with this package". I've tried to solve the problem in every way and I couldn't, I need to use the program for work as soon as possible.

### Steps to reproduce the issue

![WhatsApp Image 2023-04-05 at 22 35 41](https://user-images.githubusercontent.com/96086853/230251549-e6179f08-f651-49e1-a5d9-2c37988ba849.jpeg)

### Versions

Version 3.28.5 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@laurasanttoss could you please check if the downloaded QGIS-OSGeo4W-3.28.5-1.msi file has a size of 1220821504 bytes and the digital signature of the file (Windows File Explorer file properties) is valid or the sha-256 checksum of the file is `062900e711b211042e54ecb5fb3ccfeb2867320b3053cbeeb8b130777666c2f2`?

**Comment by jef-n** [comment]
```
> curl -L https://qgis.org/downloads/QGIS-OSGeo4W-3.28.5-1.sha256sum
062900e711b211042e54ecb5fb3ccfeb2867320b3053cbeeb8b130777666c2f2 *QGIS-OSGeo4W-3.28.5-1.msi
> certutil -hashfile QGIS-OSGeo4W-3.28.5-1.msi sha256
SHA256-Hash von QGIS-OSGeo4W-3.28.5-1.msi:
062900e711b211042e54ecb5fb3ccfeb2867320b3053cbeeb8b130777666c2f2
CertUtil: -hashfile-Befehl wurde erfolgreich ausgeführt.        
```

**Comment by agiudiceandrea** [comment]
@laurasanttoss is the file size of 1220821504 bytes? Please download again the file and ensure it has the correct size and a valid digital signature.

**Comment by laurasanttoss** [comment]
@agiudiceandrea The file size is 1.192.209 KB. I've downloaded it several times and this error always occurs.

**Comment by stefanuhrig** [comment]
Can you press the "View Certificate" button and share the contents of the tabs? It should look like this:

![cert1](https://user-images.githubusercontent.com/10857909/233669630-1422464e-5afc-409f-a84f-2e9289b15d5b.png)
![cert2](https://user-images.githubusercontent.com/10857909/233669649-ea6faf76-977e-40d3-a6f2-8892315b8532.png)
![cert3](https://user-images.githubusercontent.com/10857909/233669661-d6e61fe5-102e-4240-a2b0-292bdc84a650.png)

**Comment by alexbruy** [comment]
Is this still an issue? But anyway looks like the problem is caused by the corrupted download.
