### ISSUE TITLE
Add 'show features count in the layout legend object panel

### ISSUE THREAD

**Issue by albertograva** [qgis/QGIS#52576]
### Feature description

Hi!
I think that adding a check box to activate/de-activate the layer feature count in the layout legend options it will be useful.

**Comment by roya0045** [comment]
There's already the button, not sure what is asked here.

**Comment by albertograva** [comment]
@roya0045 it could be...but I dont't think so...
i'm asking for an easy way to remove the features count from the legend in the layout manager.
If it already exists, i'm sorry but I don't know how it works...
![leg](https://user-images.githubusercontent.com/47315786/231132595-2a8dc552-4cea-40e0-a9ef-d11fc3d1cc43.png)
