### ISSUE TITLE
Display scale on system bar at base of screen

### ISSUE THREAD

**Issue by peterpavlovic** [qgis/QGIS#52583]
### What is the bug or the crash?

Trying to view the scale causes app to crash.

### Steps to reproduce the issue

1. Start desktop
2. Load map
3. Click on up arrow to display scale

### Versions

3.30.1-'s-Hertogenbosch

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
Duplicate of #52529
