### ISSUE TITLE
Layer name automatically changes to Atlas legend

### ISSUE THREAD

**Issue by NvBgm** [qgis/QGIS#52621]
### What is the bug or the crash?

I hope someone can help. When I create an atlas, the following occurs.
Layer  set to categories. Atlas created and legend added. When only 1 of the categories is present within the layer, the layer name changes. If more than one category is present, the layer name will remain. How can I also let the layer name exist for 1 category??

![S2](https://user-images.githubusercontent.com/8125819/230916361-de5ba1f7-c26c-49c4-9721-a3e0d6bea5e9.jpg)
![S3](https://user-images.githubusercontent.com/8125819/230916362-170e570a-0525-42f2-aa6a-692202949659.jpg)
![S1](https://user-images.githubusercontent.com/8125819/230916358-bc1f9748-a0a3-4332-a548-6a785fcd028e.jpg)

**It only occurs when I add the following expression to the layer in the Atlas legend:**

**symbol_label || 
aggregate(layer:= @layer_name, aggregate:='sum',expression:="Aantal",filter:=  "Soort" = @symbol_label  and "Cluster" =  @atlas_pagename )** 

### Steps to reproduce the issue

Create layer and categorize data. 
Create Atlas and add legend
Select Atlas item where only 1 of the categories is present

### Versions

QGIS-versie
3.30.1-'s-Hertogenbosch
QGIS code revisie
9035a01e
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.6.3
PROJ versie
9.2.0
EPSG-register databaseversie
v10.082 (2023-02-06)
GEOS versie
3.11.2-CAPI-1.17.2
SQLite versie
3.41.1
PDAL versie
2.5.2
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009
Actieve Python plug-ins
bfvw_tools
1.3
changeDataSource
3.1
lizmap
3.11.4
pdokservicesplugin
4.1.3
pluginbuilder3
3.2.1
qconsolidate3
0.2.0
qgis2web
3.16.0
qgiscloud
3.8.3
SelectWithin
0.4
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by roya0045** [comment]
A sample project would be better to help whoever will want to fix this. It's not clear what other things are at play.

**Comment by NvBgm** [comment]
Here is a sample project

[testerror.zip](https://github.com/qgis/QGIS/files/11201916/testerror.zip)

**Comment by NvBgm** [comment]
Solved 

![image](https://user-images.githubusercontent.com/8125819/231209338-5253dfff-894b-434d-bc93-d3213468a4a1.png)

**Comment by nicogodet** [comment]
![image](https://user-images.githubusercontent.com/39594821/231366619-9bd8f49c-9493-4b45-8709-38596332a8d2.png)
![image](https://user-images.githubusercontent.com/39594821/231366710-c21e8d06-04c7-480c-a9e2-30a58780a34c.png)
![image](https://user-images.githubusercontent.com/39594821/231366765-4f545020-42dc-4f3e-a632-7e5c40a7ea75.png)
![image](https://user-images.githubusercontent.com/39594821/231366794-d14d96fa-c08a-40fd-ab95-10ec12f08f96.png)

**Comment by roya0045** [comment]
Might be a regression, it works perfectly fine on my home built, the layer name stays and is not replaced by the symbol string when there is only one symbol.

**Comment by nicogodet** [comment]
@roya0045 Which commit ?

**Comment by roya0045** [comment]
> @roya0045 Which commit ?

The last commit from the main branch in my build was https://github.com/qgis/QGIS/commit/c5e915740d1b7ed8c9f1957e5cd81dfa4c26a21c
The rest are my branch that are/were unmerged. The branch is at https://github.com/roya0045/QGIS_1/tree/homebrew_329

**Comment by nicogodet** [comment]
> The last commit from the main branch in my build was https://github.com/qgis/QGIS/commit/c5e915740d1b7ed8c9f1957e5cd81dfa4c26a21c

Before recent optimization of layout legend
Ping @nyalldawson

**Comment by roya0045** [comment]
I did check in  `QgsLegendModel::data` but I couldn't find anything that could easily explain the behaviour where the title becomes the first symbol entries. It's not obvious what could be causing this.

**Comment by NvBgm** [comment]
Is there a walk arround ??

**Comment by NvBgm** [comment]
Solved on the new version 
Tank you..

**Comment by NvBgm** [comment]
On the last update i stil have this error. Can anyone check this for me ??

**Comment by elpaso** [comment]
I can reproduce the issue on current master.
