### ISSUE TITLE
Vectorial menu options

### ISSUE THREAD

**Issue by Carmolqui** [qgis/QGIS#52623]
### What is the bug or the crash?

Hi,
I hopw you are doing well.
Some days ago, all the options from "Vectorial" menu suddenly dissapeared.
I have just updated the QGis version and it is the same. 
In other words, I can not do any geospatial analysis as buffers, merges, etc,... and if it is not solved soon I will need to look for other apps of GIS.
I hope you can solve it soon!
Thanks in advance for your support!
kind regards, Carmen

### Steps to reproduce the issue

![imagen](https://user-images.githubusercontent.com/130393153/230957059-3f0876f6-7904-4cea-aa23-762e6e527788.png)

### Versions

QGIS is 3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
May be related to #52449

**Comment by DelazJ** [comment]
The Processing menu is not available in the screenshot so you probably need to enable it in the Plugins manager dialog (@YoannQDQ it is not the first time I see people reporting that they lose Processing tools after update; something disabled it).

**Comment by Carmolqui** [comment]
Hi,
The processing menu disappeared without doing anything, after that I
updated the QGIS version and it didn´t appear the processing menu.
How can I make them enable? following this instructions (even though it is
not the same case): #52449 <https://github.com/qgis/QGIS/issues/52449>
Thanks in advance to all of you!
Carmen

**Comment by Carmolqui** [comment]
Thank you very much.
They are back!
:-)
