### ISSUE TITLE
'Add' button for adding XYZ layer through Data Source Manager remains disabled

### ISSUE THREAD

**Issue by roel-v** [qgis/QGIS#52622]
### What is the bug or the crash?

I want to add an XYZ layer. The way I used to do that is go through the 'Layer' menu, 'Add layer', 'XYZ layer' which takes me to the XYZ section in the Data Source Manager. In 3.30, you no longer have to add the 'connection', you can enter the URL for the server directly if you want to. On my machine, the connection URL (for Google Maps satellite) was correctly imported. But regardless of whether I select a connection in the drop down, or enter the details manually, the 'Add' button remains disabled, without any indication of why. I understand that for some dialog, it's disabled until all required information is filled in, but it's still frustrating not being able to see what is missing. But since 3.30 I can't get the button to be enabled no matter what I do. Tried this on a blank install (i.e., no previous versions present) also, but same problem.

### Steps to reproduce the issue

Go to the Data Source Manager/XYZ section. Put

`http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}`

in the URL bar (or add a saved connection). 'Add' button is never enabled.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
latlontools | 3.6.9
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
latlontools
3.6.9
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by NvBgm** [comment]
![image](https://user-images.githubusercontent.com/8125819/230927386-2721a56e-e714-4e62-a022-eb03e7b6d4e8.png)

**Comment by roel-v** [comment]
It look like that is the connection editor window, is that right? I'm talking about the dialog in the Data Source Manager. See screenshot. Note that you have OK/Cancel buttons. The Data Source Manager has Close/Add.

![image](https://user-images.githubusercontent.com/568567/230928882-32d7347f-050b-4650-a4dd-e325116cdef6.png)

**Comment by agiudiceandrea** [comment]
Confirmed using QGIS 3.30.1 on Windows (OSGeo4W):
https://user-images.githubusercontent.com/16253859/231128605-2e135b68-34af-40b6-b268-cfcd0c5984bc.mp4
