### ISSUE TITLE
mouse-scroll: zoom and recenter

### ISSUE THREAD

**Issue by sdikiy** [qgis/QGIS#52633]
### Feature description

Hi, in last QGIS I can`t find option
````
2. zoom and recenter
````
it make me unhappy :-) https://github.com/qgis/QGIS/issues/10474

Regards

**Comment by YoannQDQ** [comment]
This was removed from QGIS 2.18, when `QgsMapCanvas::setWheelAction` was deprecated. Not sure exactly why, but it was definitely intentional, so I don't see it making a comeback anytime soon.

I'd argue that zooming and recentering with the mouse wheel is really cumbersome though, as it makes the canvas drift on each tick of the wheel.

**Comment by sdikiy** [comment]
Yes, unfortunately it will most likely never come back...

But about the difficulty of use, I have to disagree with you here, once you get used to this behavior, you will never give it up.
https://forum.kicad.info/t/scroll-with-mouse-wheel-action-zoom-in-and-out/20586/5

Here's another usage video, panning and zooming only with the mouse wheel.
https://youtu.be/vyUrjnFaZcM?t=131

**Comment by sdikiy** [comment]
Are you closing? but it's not a "Bug" it's a "Feature Request"

**Comment by nyalldawson** [comment]
Feature requests can still be closed as a "won't fix".

**Comment by nyalldawson** [comment]
Or for a more helpful answer -- this won't get fixed in QGIS itself. But it's entirely possible to write a small plugin which overrides the default behavior for this tool and restores a zoom and recenter mode. That's the way forward here.

**Comment by sdikiy** [comment]
I haven't looked into QGIS code in a while, but a few years ago I thought it was a fairly non-trivial task.
I’m sorry for taking up your time.
