### ISSUE TITLE
Issues with UMEP

### ISSUE THREAD

**Issue by Heid4631** [qgis/QGIS#52632]
### What is the bug or the crash?

It seems that in the new version the download of plugins have issues. The UMEP plugin seem to not be fully included in the latest version. Students who downloaded the version available the 28th of march does not have issues, but those with the latest version (available the 1st of april) can not use the plugin. 

### Steps to reproduce the issue

![Skærmbillede 2023-04-11 kl  09 59 43](https://user-images.githubusercontent.com/130443516/231095144-896820c2-ee45-4c20-b999-13d3475e0d1b.png)

### Versions

3.30.1-'s-Hertogenbosch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Shoudl be reported here : https://github.com/UMEP-dev/UMEP
