### ISSUE TITLE
Vector Tiles do not display anything beyond max zoom level instead of displaying last zoom level

### ISSUE THREAD

**Issue by Ognian** [qgis/QGIS#52635]
### What is the bug or the crash?

Vector Tiles:
URL: https://maps.wien.gv.at/basemapv/bmapv/3857/tile/{z}/{y}/{x}.pbf
Style: https://maps.wien.gv.at/basemapv/bmapv/3857/resources/styles/root.json
<img width="665" alt="image" src="https://user-images.githubusercontent.com/1231174/231096546-a4cec9e8-69c4-495c-aecc-cdb7a329e8a7.png">
max zoom Level is 16
When zooming in beyond zoom level 16.5 nothing is displayed, instead of zooming into the last provided layer.
Layer Settings:
<img width="1041" alt="image" src="https://user-images.githubusercontent.com/1231174/231097290-d5419674-c998-4c46-ba24-f94a20ad46b0.png">

### Steps to reproduce the issue

1. Setup vector tile data provider from the above data
2. optionally install "Zoom Level" plugin to monitor zoom level
3. Continuously zoom into the map
monitor how the map is displayed up to zoom level 16.5 then everything disappears 

### Versions

QGIS-Version | 3.30.1-'s-Hertogenbosch | QGIS-Codeversion | 447e8d717a
-- | -- | -- | --
Qt-Version | 5.15.2
Python-Version | 3.9.5
GDAL-Version | 3.3.2
PROJ-Version | 8.1.1
EPSG-Registraturdatenbankversion | v10.028 (2021-07-07)
GEOS-Version | 3.9.1-CAPI-1.14.2
SQLite-Version | 3.35.2
PDAL-Version | 2.3.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.11.5
BS-Version | macOS 13.3
  |   |   |  
Aktive Python-Erweiterungen
zoom_level | 0.1
contour | 2.0.12
AustrianElevation | 2.0
DEMto3D | 3.51
qfieldsync | v4.4.9
Qgis2threejs | 2.7.1
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS-Version
3.30.1-'s-Hertogenbosch
QGIS-Codeversion
[447e8d717a](https://github.com/qgis/QGIS/commit/447e8d717a)
Qt-Version
5.15.2
Python-Version
3.9.5
GDAL-Version
3.3.2
PROJ-Version
8.1.1
EPSG-Registraturdatenbankversion
v10.028 (2021-07-07)
GEOS-Version
3.9.1-CAPI-1.14.2
SQLite-Version
3.35.2
PDAL-Version
2.3.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.11.5
BS-Version
macOS 13.3

Aktive Python-Erweiterungen
zoom_level
0.1
contour
2.0.12
AustrianElevation
2.0
DEMto3D
3.51
qfieldsync
v4.4.9
Qgis2threejs
2.7.1
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
![image](https://user-images.githubusercontent.com/39594821/231156244-7dde8244-88e1-4e96-b38a-ded6dbef9144.png)
![image](https://user-images.githubusercontent.com/39594821/231156277-8bd2b459-849b-4a67-b2f8-11733cd0f724.png)
![image](https://user-images.githubusercontent.com/39594821/231156346-ba89c6ac-f49a-44ba-b8b5-f7d2bad0b1a9.png)
![image](https://user-images.githubusercontent.com/39594821/231156386-b578d3f3-e252-4640-a966-68fd17b00bf8.png)
![image](https://user-images.githubusercontent.com/39594821/231156411-4dd8a6e3-9dd6-4392-a75a-bb40162885bb.png)

I can't reproduce on windows

**Comment by Ognian** [comment]
Thats funny:
I tried the exact same location as you did and it worked on mac to.
BUT this location:
<img width="1037" alt="image" src="https://user-images.githubusercontent.com/1231174/231160920-c72798eb-caf3-492d-9b4e-2c6c33597edd.png">
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/1231174/231161144-e072f3d8-c1d3-4ff6-a727-4d6112ff9ec8.png">
<img width="1244" alt="image" src="https://user-images.githubusercontent.com/1231174/231161250-8a857a55-6731-44ca-8180-4d2f8b7ed4c6.png">
any Idea why this happens?
Thanks
Ognian

**Comment by nicogodet** [comment]
Zoom level 16 seems missing from source.
https://maps.wien.gv.at/basemapv/bmapv/3857/tile/16/22874/35730.pbf returns 404
![image](https://user-images.githubusercontent.com/39594821/231372931-7bd35743-a79e-4511-bb32-261966f83eca.png)

I would close as not a QGIS issue

**Comment by Ognian** [comment]
@nicogodet thanks a lot; I understand, looks like they have not enough details for non urban areas...
BUT how can I convince QGIS to fetch just up to a specific layer?
I tried on the connection settings:
<img width="658" alt="image" src="https://user-images.githubusercontent.com/1231174/231395760-529ab754-579e-4249-8adf-3f81f3ff6213.png">
and on the layer settings:
<img width="1034" alt="image" src="https://user-images.githubusercontent.com/1231174/231396475-ff8ac457-f405-4aed-88ec-86c8c63f1f3e.png">
but QGIS is still trying to fetch layer 16:
<img width="1626" alt="image" src="https://user-images.githubusercontent.com/1231174/231396751-89cf79b4-0daa-4959-afaf-6d7eda6cc84c.png">

**Comment by nicogodet** [comment]
Did you remove and re-add layer after you modified max zoom level ?
![image](https://user-images.githubusercontent.com/39594821/231399115-e479ddb7-7fdf-4424-98d7-9838adef388d.png)

**Comment by Ognian** [comment]
@nicogodet Yes you are right! Thanks a lot!!
