### ISSUE TITLE
QGIS crash when editing several legends in layout

### ISSUE THREAD

**Issue by Muidz** [qgis/QGIS#52646]
### What is the bug or the crash?

QGIS crash when I try to edit several legend in layout, simultaneously. Previously also happen on QGIS 3.22
![qgis crash](https://user-images.githubusercontent.com/130520045/231320890-d2710f5d-3cb2-4022-97a8-51be7acc1895.png)

### Steps to reproduce the issue

go to layout
create 2 or 3 legend
change legend item name from legend 1,
change legend item name from legend 2,
repeat

### Versions

Python Stack Trace
Windows fatal exception: code 0xc0000139

Current thread 0x00001f68 (most recent call first):

Windows fatal exception: code 0xc0000139

Thread 0x00001f68 (most recent call first):

Windows fatal exception: code 0xc0000139

Current thread 0x00001f68 (most recent call first):

Windows fatal exception: code 0xc0000139

Thread 0x00001f68 (most recent call first):

Windows fatal exception: code 0xc0000139

Thread 0x00001f68 (most recent call first):

Windows fatal exception: code 0xc0000139

Current thread 0x00001f68 (most recent call first):

Windows fatal exception: access violation

Current thread 0x00001f68 (most recent call first):

Stack Trace

QgsRasterBlockFeedback::isPreviewOnly :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayoutLegendNodeWidget::labelChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QWidgetTextControl::qt_static_metacall :
QWidgetTextControl::qt_metacall :
QObject::qt_static_metacall :
QTextDocumentPrivate::finishEdit :
QTextCursor::insertText :
QTextCursor::insertText :
QWidgetTextControl::isWordSelectionEnabled :
QWidgetTextControl::processEvent :
QWidgetTextControl::processEvent :
QPlainTextEdit::selectionChanged :
QPlainTextEdit::keyPressEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/52268
