### ISSUE TITLE
the processing option tab content is empty.

### ISSUE THREAD

**Issue by sendreams** [qgis/QGIS#52649]
### What is the bug or the crash?

the processing option tab content is empty.

![image](https://user-images.githubusercontent.com/4160051/231374934-2d13957d-086b-4c7e-a69e-bd5105cb0428.png)

### Steps to reproduce the issue

1. setting -> options, select processing tab, type any word to search
2. remove search word
3. switch to processing tab, the content is empty.

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 2009

Active Python plugins
DEMto3D
3.51
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
Does it happen in a new profile too?

**Comment by agiudiceandrea** [comment]
@kannes I can confirm the issue does occur using a new QGIS user profile.

**Comment by DelazJ** [comment]
Revival of #34543?

**Comment by agiudiceandrea** [comment]
@DelazJ very similar. It seems to me that now using 'set' as search string (like in your previous issue report), the issue no longer occurs, while it does occur using e.g. 'asd' as search string.
