### ISSUE TITLE
ErrorRasterInlayoutQgisVer3.28.5

### ISSUE THREAD

**Issue by HugoHvidSorensen** [qgis/QGIS#52654]
### What is the bug or the crash?

A local raster of at terrain model shows correctly in the Map Window but the map window in a layout shows the raster as lead grey.
The issue showed up after indatlling LTR ver. 3.28.5

### Steps to reproduce the issue

After instaling:
 

MapWindow/Cancas:
 
In Layout (raster i blue):
 
This is new (I do think I remember something similar many old versions back)
[ErrorRasterInlayoutQgisVer3.28.5.docx](https://github.com/qgis/QGIS/files/11210385/ErrorRasterInlayoutQgisVer3.28.5.docx)
[ErrorRasterInlayoutQgisVer3.28.5.docx](https://github.com/qgis/QGIS/files/11210388/ErrorRasterInlayoutQgisVer3.28.5.docx)

### Versions

QGIS-version
3.28.5-Firenze
QGIS-koderevision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AutoLayoutTool
1.1
Datafordeler
1.3
Dataforsyningen
0.4
DigitizingTools
1.5.2
felt_tegn
1.26
FreehandRasterGeoreferencer
0.8.3
geosearch_dk
1.3.0
local_dominance
1.0.2
mask
1.10.2
profiletool
4.2.4
ProjectPackager
0.7.1
QCopycanvas
0.7
qgis-plugin-findreplace-main
1
QlrBrowser
3.0.0
quick_map_services
0.19.33
SpreadsheetLayers
2.1.0-alpha1
StreetView
3.2
db_manager
0.1.20
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@HugoHvidSorensen, please actually try if the issue does occur using a new QGIS user profile. If it does, please provide a sample project and layer with which the issue does occur. If not, please report back and close the issue as it may due to an installed plugin or a setting in your user profile.

**Comment by HugoHvidSorensen** [comment]
I will just close and leave as is as I do not have the knowledge to provide wanted information, sorry.

**Comment by DelazJ** [comment]
@HugoHvidSorensen [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by HugoHvidSorensen** [comment]
Cannot find a pattern for the occurrence of the issue in layouts.
So will close it an hope i disappears with a new version 🤗
