### ISSUE TITLE
Elevation profile tolerance catch feature outside tolerance polygon

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#52659]
### What is the bug or the crash?

![image](https://user-images.githubusercontent.com/39594821/231510091-b861cd5a-1091-4cbc-8e67-50d5b16664d1.png)
![image](https://user-images.githubusercontent.com/39594821/231510280-32d75b0f-8eef-47b0-a8c6-6ed0ad8e2953.png)

See on latest image, points are drawn on elevation profile while they a not inside tolerance polygon 

### Steps to reproduce the issue

see above

### Versions

3.30.1 Win 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Some sample data to reproduce this issue is required

**Comment by nicogodet** [comment]
Was my mistake...
Drawn layer in canvas was not plotted layer in profile
