### ISSUE TITLE
Z values are not correctly stored when using MSSQL (issues with both Vertex Tools and Advanced Digitizing Tools)

### ISSUE THREAD

**Issue by kristianrl** [qgis/QGIS#52660]
### What is the bug or the crash?

QGIS does not store the **Z value** correctly when saving the layer in an MSSQL database. It results in the error described below.

### Steps to reproduce the issue

We have created a table in MS SQL with 3D coordinates like ``POLYGON ((523699.41 6231152.17 80.53, 523698.64 6231154.35 79.96, 523694.92 6231152.82 80.21, 523695.8 6231150.68 80.54, 523699.41 6231152.17 80.53))``

In short ``POLYGON((X1 Y1 Z1,X2 Y2 Z2,X3 Y3 Z3,X4 Y4 Z4,X1 Y1 Z1))``

When we add a new node, we expect QGIS to update the MSSQL table with something like ``POLYGON((X1 Y1 Z1,X2 Y2 Z2,X2a Y2a -999, X3 Y3 Z3,X4 Y4 Z4,X1 Y1 Z1))`` , where unknown Z-values are set to -999 (as defined in **Options --> Digitizing --> Feature Creation--> Default Z value**).

#### Vertex Tool
If we use the **Vertex tool** to add the node, and afterwards Save the layer, we get the following error message (Danish with English translation). The data is not saved:

    Kunne ikke gemme ændringer til lag Bygning_QGIS_Test [= Could not save changes to the layer Bygning_QGIS_Test] 
    Fejl: ERROR: 1 geometries not changed.
    Udbyderfejl [=Provider error]:
    [Microsoft][ODBC SQL Server Driver][SQL Server]A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
    System.FormatException: 24142: Expected "NULL" at position 206. The input has "nan,".
    System.FormatException: 
    at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeToken(String token)
    at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalKeyword(String keyword)
    at Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalDouble()
    at Microsoft.SqlServer.Types.WellKnownTextReader.ParseLineStringText()
    at Microsoft.SqlServer.Types.WellKnownTextReader.ParsePolygonText()
    at Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
    at Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
    at Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
    . [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. QODBC3: Kunne ikke eksekvere udsagn [=Could not execute statement]``

We believe that QGIS submits ``POLYGON((X1 Y1 Z1,X2 Y2 Z2,X2a Y2a ,X3 Y3 Z3,X4 Y4 Z4,X1 Y1 Z1))`` to MS SQL (note the ``X2a Y2a ,`` part), and MS SQL then replies “I got a comma instead of a Z-value” , since no **Z2a** value was sent.

#### Advanced Digitizing Tool
When we use the **Advanced Digitizing Tool**, the data can be saved, and it seems like QGIS interpolates a Z value (which often is a bad idea, since in fact, the Z value is unknown).

The behavior we would like is:
We can set the Advanced Digitizing Tool or Vertex Tool to either set a preset Z value (which could be -999 or another value set as an unknown value) or let it interpolate.
Currently, setting the value set in **Options --> Digitizing --> Feature Creation--> Default Z value** does not affect the MS SQL issue described, but we have tested that it works with PostGIS.

### Versions

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AddressToolsDK | 0.1
Datafordeler | 1.3
Dataforsyningen | 0.4
geosearch_dk | 1.2.0
GroupStats | 2.2.6
ImportPhotos | 3.0.5
qdraw | 3.0.2
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

We have reproduced this in several QGIS versions, including 3.30.
Our MS SQL Server is _Microsoft SQL Server 2017 Standard edition_ (version number 14.0.2002.14).

Also see issue #27792 regarding a bug with M values.

**It is critical to us to have this bug fixed soon. We can potentially provide some funding to have this issue fixed.**

Cc: @informatiksilkeborg , @nice-sonderborg and @geomenke .

**Comment by kristianrl** [comment]
Dear @elpaso. @bvthomsen proposed that I reached out to you.
It is critical to my organization to have this bug fixed soon. We can potentially provide some funding to have this issue fixed.

**Comment by elpaso** [comment]
@kristianrl I am unable to reproduce the issue on QGIS master and 3.30

**Comment by kristianrl** [comment]
We thought this could be related to us running MSSQL 2017, so we tested on other setups. We managed to reproduce this on both QGIS 3.28 (MSSQL 2022 - 16.0.1) as well as QGIS 3.30 (MSSQL 2022 - 16.0.1).

We tested this way, first by creating the table:

```
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[test_3d_geometry](
	[id] [int] NOT NULL,
	[geo] [geometry] NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
```

 and populating it with a 3D polygon:

```
INSERT INTO [dbo].[test_3d_geometry]
           ([id]
           ,[geo])
     VALUES
           (1
           , geometry::STGeomFromText ('POLYGON ((523699.41 6231152.17 80.53, 523698.64 6231154.35 79.96, 523694.92 6231152.82 80.21, 523695.8 6231150.68 80.54, 523699.41 6231152.17 80.53))' , 25832))
GO
```


As stated above, we can _move_ an existing anchor point, but cannot _add_ a new anchor point.

<img width="558" alt="image" src="https://github.com/qgis/QGIS/assets/2519890/349c13d0-169c-4961-9c52-a8eb74a466f8">

 The Z value setting seems to be ignored.
<img width="626" alt="image" src="https://github.com/qgis/QGIS/assets/2519890/665ee603-8c85-401d-a226-35d69c259f34">


We get the following error message:

```
Could not commit changes to layer test_3d_geometry

Errors: ERROR: 1 geometry not changed.
  
  Provider errors:
      [Microsoft][ODBC SQL Server Driver][SQL Server]A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
    System.FormatException: 24142: Expected "NULL" at position 280. The input has "nan,".
    System.FormatException: 
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeToken(String token)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalKeyword(String keyword)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalDouble()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParseLineStringText()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParsePolygonText()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
       ved Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
    . [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. QODBC3: Unable to execute statement
```


Which MSSQL server version are you using for your test, @elpaso ?
Did you try this on an empty database?

**Comment by elpaso** [comment]
> Which MSSQL server version are you using for your test, @elpaso ? 

2017

> Did you try this on an empty database?

No, I added a table to an existing one.

**Comment by elpaso** [comment]
Ok, I can reproduce it now following your latest instructions.

**Comment by bvthomsen** [comment]
@kristianrl  : When creating a new spatial table.. Do you register the new table in the geometry_columns meta table (dbo.geometry_columns) ? 
Your problems might have something to do with QGIS missing information from this table and thus guessing values (wrongly) , for example for 2D / 3D values.

You have to update this meta table manually in MS SQL Server

`
INSERT INTO dbo.geometry_columns (f_table_catalog, f_table_schema, f_table_name, f_geometry_column, coord_dimension, srid, geometry_type) VALUES ('my_db_name', 'dbo', 'test_3d_geometry','geo',3, 25832, 'POLYGON')
`

**Comment by bvthomsen** [comment]
Yes, it should have been POLYGONZ (I was just "free-hand typing' the SQL code). The correct code - when the current database name is replaced by the correct one - is: 

`
INSERT INTO dbo.geometry_columns (f_table_catalog, f_table_schema, f_table_name, f_geometry_column, coord_dimension, srid, geometry_type) VALUES ('my_db_name', 'dbo', 'test_3d_geometry','geo',3, 25832, 'POLYGONZ') 
`

**Comment by elpaso** [comment]
> Yes, it should have been POLYGONZ (I was just "free-hand typing' the SQL code). The correct code - when the current database name is replaced by the correct one - is:
> 
> `INSERT INTO dbo.geometry_columns (f_table_catalog, f_table_schema, f_table_name, f_geometry_column, coord_dimension, srid, geometry_type) VALUES ('my_db_name', 'dbo', 'test_3d_geometry','geo',3, 25832, 'POLYGONZ') `

Thanks, are you 100% sure about that? `coord_dimension` also contains that information.

Creating a POLYGONZ table in postgis does not list it in `geometry_columns` view as POLYGONZ but as POLYGON with coord_dimension = 3

**Comment by elpaso** [comment]
Anyway, I've probably found the solution to this issue (which is definitely a bug in the WKB type detection).

**Comment by bvthomsen** [comment]
"How many angels can dance on the head of a pin?" ;-)  And it's good you found the bug...

But actually you're right. I vaguely remember that I made a SQL Server stored procedure some 10 years ago that could automatically populate the geometry_columns table. And I used the "STGeometryType()" method to find the geometry type. According to the MS SQL Server information about the method, it can return:  Point, LineString, CircularString, CompoundCurve, Polygon, CurvePolygon, GeometryCollection, MultiPoint, MultiLineString, and MultiPolygon. So no "Z" component.

**Comment by kristianrl** [comment]
Excellent to hear, @elpaso - and thanks for the workaround-proposal, @bvthomsen .

We will test it as soon as a new build is available and report back.

**Comment by elpaso** [comment]
@kristianrl can you please email me at apasotti gmail dot com ?

**Comment by kristianrl** [comment]
Hi @elpaso, we tested on QGIS 3.32, and it is still not solved:

Our theory is that the Z value is not imported correctly from MSSQL to QGIS. 

When clicking Identify Features, we can see a Closest Verx Z (so something IS indeed imported):
![image](https://github.com/qgis/QGIS/assets/2519890/9ecee1a6-285e-4e14-94b1-71e27d0d34db)

When I move the vertex, it is possible to save.

While when I add a new vertex, it is still not possible to save, with the same error as mentioned above in the ticket.

``` 
Could not commit changes to layer test_3d_geometry

Errors: ERROR: 1 geometry not changed.
  
  Provider errors:
      [Microsoft][ODBC SQL Server Driver][SQL Server]A .NET Framework error occurred during execution of user-defined routine or aggregate "geometry": 
    System.FormatException: 24142: Expected "NULL" at position 134. The input has "nan,".
    System.FormatException: 
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeToken(String token)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalKeyword(String keyword)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.RecognizeOptionalDouble()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParseLineStringText()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParsePolygonText()
       ved Microsoft.SqlServer.Types.WellKnownTextReader.ParseTaggedText(OpenGisType type)
       ved Microsoft.SqlServer.Types.WellKnownTextReader.Read(OpenGisType type, Int32 srid)
       ved Microsoft.SqlServer.Types.SqlGeometry.GeometryFromText(OpenGisType type, SqlChars text, Int32 srid)
    . [Microsoft][ODBC SQL Server Driver][SQL Server]The statement has been terminated. QODBC3: Kunne ikke eksekvere udsagn
``` 

Note that the Advanced Digitizing Panel and the Vertex Editor Panel do not show a Z coordinate.
![image](https://github.com/qgis/QGIS/assets/2519890/159c2dec-1854-467b-8efa-cceb7e400cbf)

**Comment by elpaso** [comment]
@kristianrl did you use an old project or did you add a new layer ?

If you are using the old project the layer geometry type might still be wrong (because of the bug).

Can you try to remove the layer and add it back as a new one?

**Comment by kristianrl** [comment]
> @kristianrl did you use an old project or did you add a new layer ?

I started from scratch, with a new QGIS project.
However, I used the same MSSQL-table - I can try to re-create the SQL table, if you think it'll change anything.

**Comment by elpaso** [comment]
> > @kristianrl did you use an old project or did you add a new layer ?
> 
> I started from scratch, with a new QGIS project. However, I used the same MSSQL-table - I can try to re-create the SQL table, if you think it'll change anything.

That is not necessary, it won't change a thing. Let me check again with 3.32

**Comment by elpaso** [comment]
@kristianrl 3.32 works for me with the test table test_3d_geometry.

Also, the Z is recognized by the vertex editor. Please check the URI string where the type is PolygonZ.

![immagine](https://github.com/qgis/QGIS/assets/142164/ac88b65d-d149-432b-9f98-a76601013c0e)

**Comment by elpaso** [comment]
This bug might indeed be related to https://github.com/qgis/QGIS/issues/53614 if the option "Only look in the geometry_columns metadata table" is not checked.

**Comment by kristianrl** [comment]
> Also, the Z is recognized by the vertex editor. Please check the URI string where the type is PolygonZ.

As you can see, it's _Polygon_ - and no ODBC driver is mentioned.
![image](https://github.com/qgis/QGIS/assets/2519890/1f8a24cb-c3ca-43bf-b99f-18be21cfe111)

When adding the layer, I do not have any options called _PolygonZ_, nor is manual keyboard entry possible.
![image](https://github.com/qgis/QGIS/assets/2519890/9e2bb533-4a0f-49b2-9992-329e7775c35b)

I have tried to find a way to insert the URI string manually, but haven't been succesful.
How do you select PolygonZ when adding your 3D layer, @elpaso ?

**Comment by bvthomsen** [comment]
@kristianrl -
In the **same** database as where your 3-d layer resides: Open the alphanumeric-only table **dbo.geometry_columns**. Hopefully it look like this:
![Capture](https://github.com/qgis/QGIS/assets/1866520/92f9c972-093d-43a5-92ab-ae0e30309e68)

Find your layer-table using columns **f_table_schema** and **f_table_name**. And check the dimensionality of your table using column **coord_dimension**. If it's not 3, then change it to 3.
If the table  is missing altogether in the geometry_columns table, then make a new entry for the missing table. The rightmost column **geometry_type** have to contain one of the strings _POLYGON, MULTIPOLYGON, LINESTRING, MULTILINESTRING, POINT_ OR _MULTIPOINT_ depending on the geometry type of you table.

Although QGIS can handle tables without using the geometry_columns metatable, it sometimes misses. And the metatable is extremely useful when you have lots of tables in your database. Check the "Kig kun i metadata tabellen geometry_columns". This will cause QGIS to only read the geomtetry_columns table and show the contents in the dialog with available tables and views. Otherwise it will scan the entire database and read a couple of rows in each and every table to find the geometry type of the table. This process can be _very_ timeconsuming

**Comment by kristianrl** [comment]
@elpaso , I found a workaround for the bug: I saved the QGIS project in .QG**S** format and manually edited the XML file, changing _Polygon_ to _PolygonZ_.
![image](https://github.com/qgis/QGIS/assets/2519890/45cd6a9b-83a9-4674-a458-2608e9052e53)


@bvthomsen , thank you for that workaround - we are not using QGIS as our main GIS platform (like many municipalities, we are using Spatial Suite for the vast majority of users) - but are trying to migrate from GeoMedia to QGIS as our desktop solution for expert users with extraordinary needs.

**Comment by kristianrl** [comment]
We realized that `SELECT [id] ,[geo].STAsText() FROM [test_3d].[dbo].[test_3d_geometry]` returns only the X and Y coordinates, while  `SELECT [id]  ,[geo].AsTextZM()  FROM [test_3d].[dbo].[test_3d_geometry]` .

@elpaso, could it be that QGIS reads the data as 2D, or that MSSQL does not output the data as 3D?

![image](https://github.com/qgis/QGIS/assets/2519890/006be08a-9f82-47f4-9f40-55766b3bc351)

**Comment by elpaso** [comment]
@kristianrl no, the geometry is read in binary mode.

**Comment by kristianrl** [comment]
Works smoothly as of 3.32.1. Thanks, @elpaso!
