### ISSUE TITLE
Add support to OGC API Collections, through the "Add Layer Menu"

### ISSUE THREAD

**Issue by doublebyte1** [qgis/QGIS#52674]
### Feature description

It would be great to be able to pull OGC API Collections (OGC API Features, OGC API Tiles, OGC API Coverages) through the add layer menu. QGIS would detect the type of collection and present the relevant options (e.g.: TileMatrixSetID, format).

![oapi-collection-qgis](https://user-images.githubusercontent.com/1038897/231704826-e6860361-3f0d-4b5f-9d58-c63abd7173a3.png)

### Additional context

OGC API collections are already supported through [GDAL's OGC API driver](https://gdal.org/drivers/raster/ogcapi.html). There is even a way of activating that driver through the "Add Raster| Add Vector Menu", using the "OGCAPI:" keyword (see explanation on [this](https://github.com/qgis/QGIS/issues/50296) issue.

This is related to the discussion on this issue: https://github.com/qgis/QGIS/issues/50296

**Comment by jerstlouis** [comment]
NOTE: This also supports _OGC API - Maps_ and _OGC API - Processes_ if Part 3: Workflows & Chaining's "Collection Output" requirements class is implemented.

**Comment by doublebyte1** [comment]
@elpaso I am going to close this, as it is addressed in your PR https://github.com/qgis/QGIS/pull/52819 👍🏽
