### ISSUE TITLE
Can't connect to ODBC system DSN (Windows)

### ISSUE THREAD

**Issue by grainnefar** [qgis/QGIS#52689]
### What is the bug or the crash?

I'm trying to connect QGIS with Databricks using the ODBC method. It's working in other apps, eg ArcGIS, but when I try on QGIS I receive the following error:

Connection failed - Check settings and try again.
Extended error information:
Unable to initialize ODBC connection to DSN for {user}/{password}@{dbname}

### Steps to reproduce the issue

Click on 'Add Vector Layer...'
under Source Type select Database
under Database select ODBC
create new connection with all specs Name: CONNECTIONNAME, Host: HOSTNAME Database: DATABASENAME, Port:443
click on 'Test Connection'

### Versions

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by stefanuhrig** [comment]
Can you provide the following details:

- Did you enter the DSN into the "Database" text field (fields "Name" and "Host" are ignored in case of ODBC connections)?
- Are you using 64-bit ODBC drivers?
- Does it work for User DSNs?

**Comment by grainnefar** [comment]
Thank-you now working. I had put the DSN name is the name field and database name in the database field. When I put the DSN in the database field it worked.
