### ISSUE TITLE
Scale tool keeps crashing the software. 3.30

### ISSUE THREAD

**Issue by Seanp2023** [qgis/QGIS#52696]
### What is the bug or the crash?

My scale information is partially hidden at the bottom of the window. It looks like I could just move one of the info panels over, but this is impossible. When I attempt to change the scale of my map, the software crashes and I lose progress. 
![Screenshot 2023-04-14 104650](https://user-images.githubusercontent.com/123578290/232077335-e1d6d54a-9520-40d6-b6c4-7c1122544ac6.png)

### Steps to reproduce the issue

1. Open project
2. Click on the Scale drop down menu to set scale to 1:1250
3. Await imminent crash

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
czech_slovak_freegeodata | 0.6
qfieldsync | v4.4.9
qgis-maptiler-plugin | 3.2
QuickOSM | 2.2.2
quick_map_services | 0.19.33
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
czech_slovak_freegeodata
0.6
qfieldsync
v4.4.9
qgis-maptiler-plugin
3.2
QuickOSM
2.2.2
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/52529
