### ISSUE TITLE
QGIS silently crashed when using "Points along geometry" in a certain vector file

### ISSUE THREAD

**Issue by WhitespaceQ** [qgis/QGIS#52698]
### What is the bug or the crash?

When I tried to apply the "points along geometry" (`native:pointsalonglines`) processing on a certain vector file, QGIS silently crashed without showing any error/stacktrace. 

Refer below for the sample file and screen recording of the error.

Expected behavior: QGIS should not silently error and provide information about the error(s).

The error detail from Event Viewer is as follow:

QGIS 3.28.5
```
Faulting application name: qgis-ltr-bin.exe, version: 0.0.0.0, time stamp: 0x6427574b
Faulting module name: qgis_core.dll, version: 0.0.0.0, time stamp: 0x64275b6f
Exception code: 0xc0000005
Fault offset: 0x0000000000a21d8a
Faulting process id: 0x0x38C0
Faulting application start time: 0x0x1D96F88972D8363
Faulting application path: C:\Program Files\QGIS 3.28.5\bin\qgis-ltr-bin.exe
Faulting module path: C:\PROGRA~1\QGIS32~2.5\apps\qgis-ltr\bin\qgis_core.dll
Report Id: fadd2caf-aac0-4b48-8054-d84dd1a428e1
Faulting package full name: 
Faulting package-relative application ID: 
```

QGIS 3.30.1
```
Faulting application name: qgis-bin.exe, version: 0.0.0.0, time stamp: 0x64284822
Faulting module name: qgis_core.dll, version: 0.0.0.0, time stamp: 0x64284bf1
Exception code: 0xc0000005
Fault offset: 0x0000000000a68c4a
Faulting process id: 0x0x2BD0
Faulting application start time: 0x0x1D96F8C399511D5
Faulting application path: C:\Program Files\QGIS 3.30.1\bin\qgis-bin.exe
Faulting module path: C:\PROGRA~1\QGIS33~1.1\apps\qgis\bin\qgis_core.dll
Report Id: c738ebb1-1c0a-4513-a58f-7552ee36b321
Faulting package full name: 
Faulting package-relative application ID: 
```

### Steps to reproduce the issue

[filtered - points along geometry error sample.zip](https://github.com/qgis/QGIS/files/11239252/filtered.-.points.along.geometry.error.sample.zip)

1. Fresh install QGIS in a new Windows Sandbox instance or use an existing installation
2. Import the provided gpkg
3. Use the "Points along geometry" algorithm with any settings
4. QGIS will silently crash

### Versions

QGIS 3.28.5
QGIS version | 3.28.5-Firenze | QGIS code revision | 50adba36f2
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
batchvectorlayersaver | 0.9
CalculateGeometry | 0.6.8
contour | 2.0.12
FreehandRasterGeoreferencer | 0.8.3
latlontools | 3.6.9
profiletool | 4.2.4
qgsAzimuth | 0.9.15
QuickOSM | 2.2.2
quick_map_services | 0.19.33
shapetools | 3.4.11
SRTM-Downloader | 3.1.17
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>

QGIS 3.30.1
QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
batchvectorlayersaver | 0.9
CalculateGeometry | 0.6.8
contour | 2.0.12
FreehandRasterGeoreferencer | 0.8.3
latlontools | 3.6.9
profiletool | 4.2.4
qgsAzimuth | 0.9.15
QuickOSM | 2.2.2
quick_map_services | 0.19.33
shapetools | 3.4.11
SRTM-Downloader | 3.1.17
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I've tried and can reproduce the problem both in a fresh installation inside a Windows Sandbox instance and from my existing installation. The gpkg provided is created using `Raster -> Extraction -> Contours`, passed through `Reproject` and `Extract using attributes` to select only the fewest amount of feature to analyze.

Screen recording of the error inside a fresh Windows Sandbox and new installation:
https://user-images.githubusercontent.com/68904781/232218319-6a573364-ce7f-4075-a2c2-cce3318d62fd.mp4

**Comment by nicogodet** [comment]
Confirmed on Linux too (pop OS 22.04).

Saving the line in shapefile is enough to prevent crash.

**Comment by WhitespaceQ** [comment]
Another version that I've tried: 3.22.16 and 3.22.10

It's interesting to note that my models that use `Points along geometry` is created at or before version 3.22.10 and I've noticed no crash before. Maybe it's just memory as I've had my hands full right now, I'll try to trace back to found the earliest working version.

@nicogodet thanks for workaround! I'm scratching my head just on continuing my work

**Comment by nicogodet** [comment]
gdb output

```
$ gdb qgis.bin
GNU gdb (Ubuntu 12.1-0ubuntu1~22.04) 12.1
Copyright (C) 2022 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<https://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from qgis.bin...
Reading symbols from /usr/lib/debug/.build-id/a3/5f1b37a06b2c86dc1b40960e347c6e4a0ad10f.debug...
(gdb) run
Starting program: /usr/bin/qgis.bin 

[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffdef85640 (LWP 11904)]
[New Thread 0x7fffde784640 (LWP 11905)]
[New Thread 0x7fffd5f83640 (LWP 11906)]
[New Thread 0x7fffc454f640 (LWP 11907)]
[New Thread 0x7fffc2c82640 (LWP 11908)]
[New Thread 0x7fffc2481640 (LWP 11909)]
[New Thread 0x7fffc1a1b640 (LWP 11910)]
[New Thread 0x7fffb38dc640 (LWP 11912)]
[New Thread 0x7fffb30db640 (LWP 11913)]
[New Thread 0x7fffb28da640 (LWP 11914)]
[New Thread 0x7fffb20d9640 (LWP 11915)]
[New Thread 0x7fffb18d8640 (LWP 11916)]
[New Thread 0x7fff9d3ff640 (LWP 11917)]
[New Thread 0x7fff9cbfe640 (LWP 11919)]
[New Thread 0x7fff8bfff640 (LWP 11920)]
[New Thread 0x7fff8b7fe640 (LWP 11921)]
[Detaching after fork from child process 11922]
[New Thread 0x7fff8affd640 (LWP 11923)]
[Detaching after vfork from child process 11924]
[New Thread 0x7fff36b41640 (LWP 11926)]
[Thread 0x7fff36b41640 (LWP 11926) exited]
[New Thread 0x7fff36b41640 (LWP 11927)]
[New Thread 0x7fff36340640 (LWP 11928)]
[New Thread 0x7fff352fa640 (LWP 11931)]
[New Thread 0x7fff34af9640 (LWP 11932)]
[New Thread 0x7fff273ff640 (LWP 11933)]
[New Thread 0x7fff273ff640 (LWP 11934)]
[Thread 0x7fff273ff640 (LWP 11933) exited]
[New Thread 0x7fff26bfe640 (LWP 11935)]
[Thread 0x7fff273ff640 (LWP 11934) exited]
[Thread 0x7fff26bfe640 (LWP 11935) exited]
[New Thread 0x7fff26bfe640 (LWP 11936)]
[New Thread 0x7fff273ff640 (LWP 11937)]
[Thread 0x7fff26bfe640 (LWP 11936) exited]
[Thread 0x7fff273ff640 (LWP 11937) exited]
[New Thread 0x7fff273ff640 (LWP 11938)]
[New Thread 0x7fff26bfe640 (LWP 11940)]
[New Thread 0x7fff263fd640 (LWP 11941)]
[New Thread 0x7fff25bfc640 (LWP 11942)]
[Thread 0x7fff263fd640 (LWP 11941) exited]
[Thread 0x7fff25bfc640 (LWP 11942) exited]
[New Thread 0x7fff25bfc640 (LWP 11943)]
[New Thread 0x7fff263fd640 (LWP 11944)]
[Thread 0x7fff25bfc640 (LWP 11943) exited]
[Thread 0x7fff263fd640 (LWP 11944) exited]
[New Thread 0x7fff263fd640 (LWP 11947)]
[New Thread 0x7fff25bfc640 (LWP 11948)]
[Thread 0x7fff263fd640 (LWP 11947) exited]
[Thread 0x7fff25bfc640 (LWP 11948) exited]
[Thread 0x7fff273ff640 (LWP 11938) exited]
[Thread 0x7fff352fa640 (LWP 11931) exited]
[New Thread 0x7fff352fa640 (LWP 11950)]
[Thread 0x7fff352fa640 (LWP 11950) exited]

Thread 10 "Thread (pooled)" received signal SIGSEGV, Segmentation fault.
[Switching to Thread 0x7fffb30db640 (LWP 11913)]
0x00007ffff380231f in QgsGeometryCollection::vertexAt (this=<optimized out>, id=...) at ./src/core/geometry/qgsgeometrycollection.cpp:901
901	./src/core/geometry/qgsgeometrycollection.cpp: Aucun fichier ou dossier de ce type.
(gdb) 

```

**Comment by agiudiceandrea** [comment]
The layer contains two features:
- fid 137330 with geometry: 'MultiLineString EMPTY'
- fid 148926 with geometry: 'MultiLineString ((445197.63989494 9162846.19920961, 445198.4…'

The crash occurs if the the fid 137330 feature is processed. The crash doesn't occur if only the fid 148926 feature is processed (either removing the fid 137330 feature from the layer or only selecting the fid 148926 feature and processing only the selected features).

**Comment by nicogodet** [comment]
Note: I try "Fix geometries" and it didn't fix the layer. (crash on "fixed layer") An empty linestring should be invalid, shouldn't be ?
