### ISSUE TITLE
Loading CSV file with non-latin characters via drag-n-dropping or without explicitly defining 'delimitedtext' driver loads file with wrong encoding

### ISSUE THREAD

**Issue by simonreise** [qgis/QGIS#52692]
### What is the bug or the crash?

When loading csv file with cyrillic characters via drag-n-dropping from windows explorer or via QgsVectorLayer funcion without explicitly defining 'delimitedtext' driver (e.g.  `QgsProject.instance().addMapLayer(QgsVectorLayer('C:/path/to/file.csv'))` loads it in windows-1251 encoding instead of utf-8.

Loading the same csv file via data source manager or via QgsVectorLayer funcion with defined 'delimitedtext' driver (e.g. `QgsProject.instance().addMapLayer(QgsVectorLayer('file:///C:/path/to/file.csv', 'a', 'delimitedtext'))` loads it correctly.

### Steps to reproduce the issue

0. Maybe problem is in system locale (Windows system locale - russian, qgis user interface translation - american english, qgis locale - ru_RU)

1. Download file [temp_cities.csv](https://github.com/qgis/QGIS/files/11232660/temp_cities.csv)
2. Open it via drag and dropping from windows explorer or via `QgsProject.instance().addMapLayer(QgsVectorLayer('C:/path/to/file/temp_cities.csv'))`
3. You will see something like '2396', 'Р’РёРЅРѕРіСЂР°РґРѕРІ', '43', 'Р—Р°РєР°СЂРїР°С‚СЃРєР°СЏ РѕР±Р»Р°СЃС‚СЊ', '26', 'РЈРєСЂР°РёРЅР°', '26', 'РЈРєСЂР°РёРЅР°', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '' instead of valid cyrillic text
4. Open it via qgis data source manager or via `QgsProject.instance().addMapLayer(QgsVectorLayer('file:///C:/path/to/file/temp_cities.csv', 'a', 'delimitedtext'))`
5. You will see valid cyrillic text like 2396, 'Виноградов', 43, 'Закарпатская область', 26, 'Украина', 26, 'Украина', NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL, NULL

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
mmqgis
2021.9.10
OSMDownloader
1.0.3
qgis2web
3.16.0
quick_map_services
0.19.33
SemiAutomaticClassificationPlugin
7.10.11
Serval
3.10.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
The Delimited Text provider uses UTF-8 encoding by default. However, when you drag and drop a CSV file, QGIS uses the OGR provider, which uses the default system encoding by default (on Windows it would typically be cp1252). If you loads the CSV via the data source manager as a vector layer (OGR), and keep the encoding as Automatic, you'll get the same (wrong) behavior as when drag and dropping.

I submitted a [PR to fallback to UTF-8](#52702) instead of system encoding when the encoding isn't explicitly specified
