### ISSUE TITLE
I tried to open the expression editor in any place. Then QGIS 3.28 crash

### ISSUE THREAD

**Issue by gasato** [qgis/QGIS#52697]
## User Feedback

Crash start to happen when I tried to do something on map composer on "coordinate format">"expression editor". Then I cannot open the expression editor again widthout crashing qgis.

### Other problems

Despite I moved to qgis 3.28.5 and 3.30 same error persists

```
2023-04-14T16:44:44     WARNING    La expresión de usuario Subscript no es válida
             Traceback (most recent call last):
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\Users/gasato/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\Subscript.py", line 7, in 
              def subscr_num(inputText, feature, parent):
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\core\additions\qgsfunction.py", line 174, in wrapper
              return register_function(func, args, group, **kwargs)
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\core\additions\qgsfunction.py", line 103, in register_function
              name = kwargs.get('name', function.__name__)
             AttributeError: 'QgsPyExpressionFunction' object has no attribute '__name__'
```

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000002bc (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QByteArray::QByteArray :
QgsSettingsEntryBase::definitionKey :
QgsExpressionTreeView::updateFunctionTree :
QgsExpressionTreeView::QgsExpressionTreeView :
QgsExpressionBuilderWidget::setProject :
QgsExpressionBuilderWidget::QgsExpressionBuilderWidget :
QgsExpressionBuilderDialog::setGeomCalculator :
QgsExpressionBuilderDialog::QgsExpressionBuilderDialog :
QgsLayoutMapGridWidget::mAnnotationFormatButton_clicked :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.0-Firenze
QGIS code revision: ed3ad0430f3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

## Report Details for QGIS 3.28.5

2023-04-14T16:44:44     WARNING    La expresión de usuario Subscript no es válida
             Traceback (most recent call last):
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "D:\Users/gasato/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\Subscript.py", line 7, in 
              def subscr_num(inputText, feature, parent):
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\core\additions\qgsfunction.py", line 174, in wrapper
              return register_function(func, args, group, **kwargs)
              File "D:\misc/OSGeo4W/apps/qgis-ltr/./python\qgis\core\additions\qgsfunction.py", line 103, in register_function
              name = kwargs.get('name', function.__name__)
             AttributeError: 'QgsPyExpressionFunction' object has no attribute '__name__'

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x0000086c (most recent call first):

Stack Trace

QgsExpressionTreeView::updateFunctionTree qgsexpressiontreeview.cpp:302
QgsExpressionTreeView::QgsExpressionTreeView qgsexpressiontreeview.cpp:129
Ui_QgsExpressionBuilderWidgetBase::setupUi ui_qgsexpressionbuilder.h:371
QgsExpressionBuilderWidget::QgsExpressionBuilderWidget qgsexpressionbuilderwidget.cpp:79
Ui_QgsExpressionBuilderDialogBase::setupUi ui_qgsexpressionbuilderdialogbase.h:36
QgsExpressionBuilderDialog::QgsExpressionBuilderDialog qgsexpressionbuilderdialog.cpp:28
QgsPropertyOverrideButton::showExpressionDialog qgspropertyoverridebutton.cpp:664
QObject::qt_static_metacall :
QMenu::~QMenu :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:542
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:542
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QToolButton::paintEvent :
QToolButton::showMenu :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
QToolButton::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:542
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:542
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1726
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Go to the "expression builder" wherever it is

### Versions

Problems  happened with version 3.28.0 then crashed persisted on other newer versions like 3.28.5
[h250GeoLayoutComposer.zip](https://github.com/qgis/QGIS/files/11236660/h250GeoLayoutComposer.zip)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I deleted the subscript.py file and it work in different profiles

**Comment by agiudiceandrea** [comment]
@gasato, please actually create and use a new QGIS user profile or just remove your faulty `Subscript.py` script from `D:\Users/gasato/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\`.
