### ISSUE TITLE
Scale does not work

### ISSUE THREAD

**Issue by stefanzumbrunn** [qgis/QGIS#52701]
### What is the bug or the crash?

The "Scale-Feature" in the Status Bar does not work as expected.
1. the Scale-Factor is not visilble (field is too narrow - see screenshot)
2. When clicking on the down-arrow, QGis crashes
<img width="738" alt="QGis-Scale" src="https://user-images.githubusercontent.com/8133908/232289715-5ae0f7dc-12f1-44c4-b676-02b01d389d21.png">

### Steps to reproduce the issue

click the down-arrow of the scale-factor

### Versions

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 447e8d717a
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.6
  |   |   |  
Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[447e8d717a](https://github.com/qgis/QGIS/commit/447e8d717a)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.6

Active Python plugins
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@stefanzumbrunn, thanks for reporting. The issue has been already reported at https://github.com/qgis/QGIS/issues/52383.
To workaround the issue with QGIS 3.30.1, please go to the "Settings->Options..." -> "Map Tools" -> "Predefined Scales" and click on the "Reset to default scales" button in order to restore the predefined scales, populate the map scale listbox and avoid the crash.

**Comment by stefanzumbrunn** [comment]
@agiudiceandrea,   thanks a lot for the very fast reply!
