### ISSUE TITLE
Unable to remove and save wmt/wmts connection

### ISSUE THREAD

**Issue by ShenLY00** [qgis/QGIS#52713]
### What is the bug or the crash?

Unable to remove and save wmt/wmts connection, and unable to save XYZ TILES connection.
![QQ截图20230417103519](https://user-images.githubusercontent.com/96603656/232364722-d99100bb-aac1-435d-9697-de6409c432e8.jpg)
![QQ截图20230417103551](https://user-images.githubusercontent.com/96603656/232364748-2af24379-562d-449c-8525-a41bdec01c5c.jpg)
![QQ截图20230417103907](https://user-images.githubusercontent.com/96603656/232364866-d19b2592-a6af-40e0-b4a2-9d935e052e0d.jpg)

### Steps to reproduce the issue

![QQ截图20230417103907](https://user-images.githubusercontent.com/96603656/232364984-abd93ca4-57a2-419a-9b12-c6a590fc4777.jpg)
![QQ截图20230417103519](https://user-images.githubusercontent.com/96603656/232364964-81aeb151-e2c6-43d2-b085-08c36f4d6548.jpg)
![QQ截图20230417103551](https://user-images.githubusercontent.com/96603656/232364978-0119cd26-e58f-45db-986f-65ec1dc43718.jpg)

### Versions

3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by MalikAlMaut** [comment]
Same here (even with LTR), although it should have been fixed: https://github.com/qgis/QGIS/issues/52275

**Comment by 3nids** [comment]
fixed in https://github.com/qgis/QGIS/pull/52531
