### ISSUE TITLE
MSSQL Provider does not filter SCHEMA while detecting primary key

### ISSUE THREAD

**Issue by mclucky** [qgis/QGIS#52724]
### What is the bug or the crash?

When having same table names in different schema detecting the primary key will fail because the SQL statement does not filter the schema name. 

### Steps to reproduce the issue

Just connect to the MSSQL Server. 

### Versions

QGIS LTR 3.28.x

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

(https://github.com/qgis/QGIS/blob/1c622708ab7188f042a54b5bf02ce37c22b0376a/src/providers/mssql/qgsmssqlprovider.cpp#L3308)

**Comment by agiudiceandrea** [comment]
@mclucky, the issue is currently fixed in recent QGIS 3.31.0-master dev nightly builds and you can test it if you want and reporting back is appreciated. The fix will also be available in the upcoming QGIS 3.30.3 and 3.28.8 versions.
