### ISSUE TITLE
Loss of geometry during conversion and after manipulation

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#52737]
### What is the bug or the crash?

I'm not sure this is a bug or a mistake from my end, but I don't expect QGIS to fail in this way.

When executing a processing script to modify line geomeries, the returned features all have emptry geometry when the following is executed:
```Python
        for current, feature in enumerate(features):
            # Stop the algorithm if cancel button has been clicked
            if feature.hasGeometry():
                fgeom=feature.geometry()
                newline=QgsLineString()
                newline.fromWkt(fgeom.asWkt())
                invertgeom=QgsGeometry(newline.reversed())
                feature.setGeometry(invertgeom)
            if feedback.isCanceled():
                break
            sink.addFeature(feature, QgsFeatureSink.FastInsert)
```
The attributes are preserved but the geometry is null.

### Steps to reproduce the issue

1. Create a new script from template
2. Modify the internal loop with the example provided previously
3. Execute script on a linear vector dataset
4. Result has no geometry

### Versions

Tested on 3.29

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by stefanuhrig** [comment]
`fromWkt` is a static method on `QgsGeometry`, which returns the geometry.

Can you try the following:

```python
newline = QgsGeometry.fromWkt(fgeom.asWkt())
```

**Comment by roya0045** [comment]
@stefanuhrig  yeah you're right, I must have mixed it up with `fromWkb` which is a setter not a static method to create a new instance.....

This means there's not good way to convert a qgsgeometry to a QgsLineString it seems, I'll do things the old way then.

Thanks for the reply!
