### ISSUE TITLE
Adding tianditu to the layout occasionally appears blank

### ISSUE THREAD

**Issue by SharkSyl** [qgis/QGIS#52732]
### What is the bug or the crash?

I have loaded the following services through the desktop application

http://t0.tianditu.gov.cn/DataServer?tk={token}&T=cia_w&x={x}&y={y}&l={z}

![image](https://user-images.githubusercontent.com/86356432/232451619-394471b3-3615-4728-9f9e-9e2a2a3259d5.png)

A blank layer appears when loading a layout
![image](https://user-images.githubusercontent.com/86356432/232452030-9f3eceb7-dc8c-4dc8-ba1b-334462de69c7.png)

### Steps to reproduce the issue

1. Changing the zoom range
2. Open the layout and add map layout items

### Versions

QGIS version
3.20.3-Odense
QGIS code revision
495fbaec
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
MetaSearch
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by daviddvd12002** [comment]
Please refer to TianDiTu document here: http://lbs.tianditu.gov.cn/server/MapService.html . Note that "cia_w" you requested is meant to be "影像注记" (Image Annotation), so what shows in you QGIS is exactly it should be. You may need "img_w" or "img_c" if you need imagery.
