### ISSUE TITLE
Number format of QGIS locale not checked for CSV imports

### ISSUE THREAD

**Issue by garvamel** [qgis/QGIS#52741]
### What is the bug or the crash?

I have my system set to es_CL locale and QGIS accordingly. In this locale, the decimal separator is a comma.

When importing a CSV with this decimal format, the Datasource Manager detects the fields with decimal commas as text/string fields but when importing them with dots as decimal separators they are detected fine. I'm pretty sure it used to work correctly before.

The "decimal comma" file is not properly imported even if the column type is changed to decimal. The values are imported as NULLs in that case.

As far as I can tell, the problem is only at the Datasource Manager level, because after importing the "decimal dot" file, the representation of numbers in the attribute table is displayed with commas.

### Steps to reproduce the issue

1. Go to QGIS preferences, and change the locale to es_CL (the bug most likely replicates on other "decimal comma" locales)
2. Import a CSV via the Datasource Manager and add a CSV with decimal numbers with comma as decimal separator
3. The sample data box should display decimal columns as text columns.  

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.5-Firenze | QGIS code revision | 50adba36f2
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.2
  |   |   |  
Active Python plugins
kmltools | 3.1.28
joinmultiplelines | Version 0.4.1
changeDataSource | 3.1
quick_map_services | 0.19.33
NNJoin | 3.1.3
HCMGIS | 23.2.1
densityanalysis | 2023.3.13
MapsPrinter | 0.9
CalculateGeometry | 0.6.8
autoSaver | 2.6
ProjectPackager | 0.7.1
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.5-Firenze
QGIS code revision
[50adba36f2](https://github.com/qgis/QGIS/commit/50adba36f2)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.2

Active Python plugins
kmltools
3.1.28
joinmultiplelines
Version 0.4.1
changeDataSource
3.1
quick_map_services
0.19.33
NNJoin
3.1.3
HCMGIS
23.2.1
densityanalysis
2023.3.13
MapsPrinter
0.9
CalculateGeometry
0.6.8
autoSaver
2.6
ProjectPackager
0.7.1
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Possible related issue:  #52446

**Comment by elpaso** [comment]
I cannot reproduce using italian locale and checking the right options:

![image](https://user-images.githubusercontent.com/142164/233329722-08dd2a34-db2b-4505-9eab-04d9ca6013fd.png)

Test file (TAB as a delimiter):

name    value   x       y
one     1,2     9       43,1
two     2,3     9,2     44,5

**Comment by garvamel** [comment]
I feel a little dumb, because I had never checked the "record and field options" tree before. I has always been collapsed since the imports always worked fine before without tweaking anything. My "decimal separator is a comma" checkbox was unchecked and now it works fine.

Is this a new feature or did it for some reason become changed upon version update? In any case, maybe it should be warned that locale number formats wont be considered and that they need to be set within the datasource manager.

Thank you for your help!
