### ISSUE TITLE
PyQGIS: RAM filling up and application crashing during multiple XYZ tiles exports

### ISSUE THREAD

**Issue by timbtimbtimb** [qgis/QGIS#52742]
### What is the bug or the crash?

QGIS never seems to clear its cache when running multiple XYZ tiles export processes in a row with PyQGIS, ending up crashing application. QgsMapRendererCache().clear() doesn't do anything.

### Steps to reproduce the issue

Build a QGIS project with many raster layers and export XYZ tiles for each layer's extent in a row. Watch the ressources monitor or wait for QGIS to crash.

### Versions

QGIS 3.30

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by kannes** [comment]
Just to make sure: You are writing to non-temporary files that are not in a ramdisk?

**Comment by timbtimbtimb** [comment]
> Just to make sure: You are writing to non-temporary files that are not in a ramdisk?

Yes

**Comment by timbtimbtimb** [comment]
None of these commands does anything:

```
QgsMapCanvas().clearCache()
QgsMapRendererCache().clear() 
QgsProject.instance().clear() # and then reimporting all layers
```

**Comment by alexbruy** [comment]
Does this happen with the latest dev/nighly version?
