### ISSUE TITLE
Stalebot does not remove the stale label upon pushing more commits in a PR

### ISSUE THREAD

**Issue by strk** [qgis/QGIS#52755]
### What is the bug or the crash?

Stale bot does not remove "stale" label when new commits are pushed to a branch associated with a pull request

### Steps to reproduce the issue

File a pull request, wait 2 weeks for stalebot to apply the stale label. Push more commits to the associated branch.

### Versions

doesn't matter :)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

See it happen here: https://github.com/qgis/QGIS/pull/52510#event-9030720496

**Comment by strk** [comment]
\cc @pathmapper who fixed a similar issue with #49600

**Comment by pathmapper** [comment]
https://github.com/qgis/QGIS/pull/52756 should fix this according to the docs...

**Comment by strk** [comment]
The bot removed the label 6 hours ago, not sure if it was due to your mentioning #52510 in this PR 15 hours ago or to what else. The bot actions motivations are not reported (to where I'm standing at least)
