### ISSUE TITLE
Attribute editor does not support relative paths for image files

### ISSUE THREAD

**Issue by Malvineous** [qgis/QGIS#52754]
### What is the bug or the crash?

In the attribute editor, a field that is for specifying a filename has a browse button next to it.  You can browse for an image such as a .jpg file, and the image will be displayed below the field in the attribute editor.

However this saves the absolute path to the image, even when the project has been configured for relative paths.

Furthermore, if you edit the field and change the path to be relative, the photo does not render in the attribute editor.

### Steps to reproduce the issue

1. Import some geotagged photos through the Processing toolbox.
2. Open the attribute editor for the new layer.
3. Observe the images are loaded from the files and rendered.
4. Edit the field and change the filename to be a relative path.
5. Observe the image is no longer rendered.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code branch | master
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
grassprovider | 2.12.99

</body></html>QGIS version
3.31.0-Master
QGIS code branch
[master](https://github.com/qgis/QGIS/tree/master)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I am trying to import geotagged photos that are stored in a subdirectory inside my project folder.  I have set HTML map tips that render the images via file:// URLs.

This all works, however if I move the project folder to a different computer (or a different folder on the same computer), the images no longer load as the paths are now wrong.

If I change the paths in the attribute editor to be relative, and use the `@project_folder` variable to construct the file:// URL then the images display correctly in the HTML map tooltip, but it requires manually changing the photo paths to be relative in the attribute editor after each change, and you cannot tell whether you have made a mistake in the path or not because the image never loads, even when the relative URL is indeed correct.

I am thinking that by allowing the attribute editor to load images from relative paths, it would solve most of these issues.  It would also be helpful if the browse button trimmed off the project path from the start of the selected file (if it is located within the project folder), if the project is operating in relative path mode.

**Comment by elpaso** [comment]
I cannot reproduce the issue, using "Store Path As" relative to the project.

![image](https://user-images.githubusercontent.com/142164/233307835-663fab5d-f158-482a-9c38-d2df4f07258f.png)

**Comment by Malvineous** [comment]
Ohh I'm sorry, I couldn't find where you configure the widgets so I assumed they were fixed.  Now I see in the layer properties you can change them to relative paths there.

I have changed them to relative paths and done some testing, and I confirm that everything behaves correctly once this change has been made.

My apologies for not investigating more thoroughly first!
