### ISSUE TITLE
"The layer properties comment cannot be saved" Layereigenschaften Kommentar lässt sich nicht speichern!

### ISSUE THREAD

**Issue by cdiegelmann** [qgis/QGIS#52766]
### What is the bug or the crash?

The layer properties comment cannot be saved. Field comments cannot be shown in attribute table anymore after saving the Layer.

### Steps to reproduce the issue

"When entering a comment in the layer properties fields, the comment text is displayed. However, after saving the layer, all comment texts disappear!"

### Versions

3.28.4-Firenze 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by roya0045** [comment]
Going to need more details to be able to figure out what's happening.

**Comment by stefanuhrig** [comment]
What's the type of the layer (e.g. PostGIS, Shapefile, GeoPackage etc.)?

**Comment by cdiegelmann** [comment]
Hello, I use Shapefile. 

[Screenshot 2023-04-21 153612.pdf](https://github.com/qgis/QGIS/files/11296192/Screenshot.2023-04-21.153612.pdf)

**Comment by stefanuhrig** [comment]
AFAIK, shapefiles (or more precisely the DBF file format, which is used by shapefiles to store non-spatial features) do not support column comments (see https://www.clicketyclick.dk/databases/xbase/format/dbf.html#DBF_STRUCT). So, although you can enter them in the UI, there is not way to persist them in the DBF file.

But even if you use a layer type that supports comments (like a PostGIS layer), there seems to be an issue with adding comments (see issue #26300).

**Comment by jgrocha** [comment]
For shapefiles, you should not be able to write comments on fields. On my QGIS (3.31 from master) I can not add comments. The comment field is not displayed at all, as you can see in the following print screen.

![Screenshot from 2023-04-22 11-12-47](https://user-images.githubusercontent.com/163681/233777920-10623e8b-4c5a-49e7-9064-822e9bc5be62.png)

For other provides, like Geopackage or Postgis, you should be able to add comments, but not for shapefiles.

**Comment by cdiegelmann** [comment]
Hello, thank you for your advice. I will try with Geopackege. Kind regards.
