### ISSUE TITLE
Crash after using scale listbox 

### ISSUE THREAD

**Issue by Yves0M** [qgis/QGIS#52762]
### What is the bug or the crash?

The scale drop-list appears too small to show the scale and make Qgis crash if used.
![Clipboard-1](https://user-images.githubusercontent.com/101838517/232835772-8bbe5698-0515-4d9b-bc37-e11b5cf661d3.jpg)

### Steps to reproduce the issue

Open Qgis
Click on scale droplist
Crash (if no Project Predefined scale set)
No crashing if Project Predefined Scale is set, but still too small.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 9035a01e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.3
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[9035a01e](https://github.com/qgis/QGIS/commit/9035a01e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The issue occurs on my laptop (Windows 11 Home, v. 22H2 - 22621.1555).
I have the same versión of Qgis installed on my work desktop computer and it works perfectly under Windows 10 Pro, 64 bit.

**Comment by roya0045** [comment]
Duplicate/related to #52383
