### ISSUE TITLE
QGIS WINDOW RESIZING

### ISSUE THREAD

**Issue by usernameabcdfgh** [qgis/QGIS#52778]
### What is the bug or the crash?

I CANNOT RESIZE THE WINDOW IN QGIS SO THAT QGIS ONLY TAKES UP HALF OF THE PC MONITOR SCREEN. EVERY TIME I TRY TO RESIZE THE QGIS WINDOW TO VIEW THE QGIS WINDOW ALONG WITH THE INTERNET BROWSING WINDOW, THE QGIS WINDOW DOES NOT DIMINISH IN SIZE. 
Versão do QGIS
3.28.3-Firenze
THIS SAME PROBLEM HAPPENS WITH OTHER VERSIONS OF QGIS.

### Steps to reproduce the issue

THIS SAME PROBLEM HAPPENS WITH OTHER VERSIONS OF QGIS.

### Versions

3.28.3-Firenze

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by AlisterH** [comment]
Are you on Windows operating system or what?  How are you trying to resize the window?  What is your screen resolution?
Unless you have a very wide screen you will probably find you can't resize QGIS to half the screen width, unless you turn off or undock some panels.  But normally if you try to snap it to half the screen I would expect it to work, except that it would take up more than half (maybe 3/4).

**Comment by Geoscope19** [comment]
Good morning,

(reverso trad !)
QGis 3.30.1 on windows
The side panel of the layer style is very wide, impossible to reduce without showing the window lift.

Cordially
![panneau lateral large](https://user-images.githubusercontent.com/81222128/233370853-79436cdd-b1e5-4754-8ce5-b5770efa6854.png)

**Comment by usernameabcdfgh** [comment]
I'm trying to split the window as shown in the attached file, but QGIS
takes up the whole screen
I'm using Windows 10
     screen resolution = 1920 X 1080

Atenciosamente,

Welberth Warbler Martins Ferreira - Cadastrador - GECAD
  Superintendência de Limpeza Urbana - SLU
Rua Tenente Garro, 118 |  7º andar - Santa Efigênia - BH/MG
3277 9379  w ***@***.***>ww.pbh.gov.br









Em qui., 20 de abr. de 2023 às 09:49, Elise Henrot ***@***.***>
escreveu:

**Comment by usernameabcdfgh** [comment]
Good morning.
QGIS panels should not be a hindrance to resizing the QGIS window as there
is a scroll bar to access the other parts of the window that are hidden by
resizing the window

Atenciosamente,

Welberth Warbler Martins Ferreira - Cadastrador - GECAD
  Superintendência de Limpeza Urbana - SLU
Rua Tenente Garro, 118 |  7º andar - Santa Efigênia - BH/MG
3277 9379  w ***@***.***>ww.pbh.gov.br









Em qui., 20 de abr. de 2023 às 11:31, Welberth Warbler Martins Ferreira <
***@***.***> escreveu:

**Comment by AlisterH** [comment]
> Good morning,
> 
> (reverso trad !) QGis 3.30.1 on windows The side panel of the layer style is very wide, impossible to reduce without showing the window lift.
> 
> Cordially ![panneau lateral large](https://user-images.githubusercontent.com/81222128/233370853-79436cdd-b1e5-4754-8ce5-b5770efa6854.png)

What do you mean by "showing the window lift"?

**Comment by AlisterH** [comment]
> QGIS panels should not be a hindrance to resizing the QGIS window

Regardless of whether or not you think they _should be_ a hindrance, what I'm saying is that they _are_.

> as there is a scroll bar to access the other parts of the window that are hidden by resizing the window

What scroll bar?  Most of the panels don't have a horizontal scroll bar, and they all have a minimum width.
Or are you suggesting that the entire QGIS GUI should be inside a scrolled view?

**Comment by Geoscope19** [comment]
The minimum size of the side panel "layer style" is very very wide as shown in the screenshot. Look at this new screenshot
![Sans titre](https://user-images.githubusercontent.com/81222128/233570801-e52bb814-cf6c-4425-a066-6719a311d4dc.png)

**Comment by AlisterH** [comment]
For me it is quite narrow - perhaps the difference is the QGIS version or the language.  Or the other panel you have docked with it - which panel is that?
![image](https://user-images.githubusercontent.com/714600/233573828-6e7b405e-0960-40ac-b052-ac89b1655c1e.png)

**Comment by AlisterH** [comment]
Not that the layer styling panel is actually useful that narrow!

**Comment by jgrocha** [comment]
There are obvious limitations on the width of the panels and on the width of the main window. Panels can be detached too. Is up to the user to proper configure QGIS interface for smaller sizes.
Since there is no bug related do main window or panels sizes, I'll close this issue.

**Comment by AlisterH** [comment]
There are probably improvements that could be made to some of the sizing restrictions of the panels and dialogs, if someone wanted to look into it.

- Opening the properties dialog for a vector layer now, I can shrink it to a minimum width of about 1150 pixels, which is much wider than in my screenshot above.  I don't know what makes it different now.
- If I activate the "Diagrams" or "Attribute's form" tab then the divider between the tab bar on the left and the main dialog content moves to the left, shrinking the tab bar.  There is no obvious reason why the "Diagrams" or "Attribute's form" tabs would need more width.
- There are additional vertical dividers within the "Diagrams" and "Attribute's form" tabs, and it behaves very strangely if I tried to drag these left or right - the window seems to become scrollable, although the only way to scroll it is to drag the handle.  The window can even be scrolled to the right until the tab bar is invisible, and there is no way to make it visible again.
- When the other tabs are active, I can drag the divider between the tab bar on the left and the main dialog content much further to the right than is necessary.  So why not let the dialog be narrower if the divider isn't so far to the right?
- After I go to the "Information" tab I can shrink the window to a width of about 824 pixels.  What was restricting it to 1150 pixels previously?  I have no idea.

- Opening the properties dialog for a raster layer, I can shrink the width to about 700 pixels.
- If it is less than about 1310 pixels, the tab bar is collapsed to show only icons.  Why does the tab bar need to be collapsed if the window is 1300 pixels wide, even though it can be shrunk all the way down to 700?  Who knows...
- Other strange things happen, e.g. if the source tab is active I can drag the divider between the tab bar on the left and the main window content on the right, and the window scrolls.  If I drag it to the right and let go, the only way to make the tab bar visible again is to make the window wider.  If I drag it to the right and then back again then the tab bar is visible, but with no icons on it.
- Before I started trying to test this thoroughly and write everything down, I wasn't able to make this dialog narrower than about 1150 pixels, and a couple of the tabs would automatically resize and limit the dialog to about 1250 pixels wide, when I clicked on them.  It isn't clear how I managed to get it down to 700 pixels...
