### ISSUE TITLE
Program window position is disordered

### ISSUE THREAD

**Issue by gh935** [qgis/QGIS#52779]
### What is the bug or the crash?

Program window position is disordered

![image](https://user-images.githubusercontent.com/131321200/233240013-ba526753-a0ab-4690-a3d8-5e15c77b4d12.png)

### Steps to reproduce the issue

Program window position is disordered

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthMeasurement
0.2.2
geohey_toolbox
0.4
latlontools
3.6.9
nominatim
1.4.5
OSMDownloader
1.0.3
QuickOSM
2.2.2
quick_map_services
0.19.33
searchlayers
3.0.12
shapefile_encoding_fixer
0.7
shapetools
3.4.11
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Program window position is disordered

**Comment by agiudiceandrea** [comment]
@gh935 the issue should have been fixed in QGIS 3.30.2 with PR https://github.com/qgis/QGIS/pull/52580. Please try the new version which will be available soon.

**Comment by agiudiceandrea** [comment]
@gh935 to workaround the issue with QGIS 3.30.1, please go to the "Settings->Options..." -> "Map Tools" -> "Predefined Scales" and click on the "Reset to default scales" button in order to restore the predefined scales.
