### ISSUE TITLE
ruleKey of legendSymbol not stable on categorized and graduated symbology

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#52772]
### What is the bug or the crash?

When changing the order of the categorized symbols the ids are apparently reset, so the checked state of them is not stable over MapThemes. PrintLayout Legends are affected as well. When I have a LegendItem with "hidden" symbols, after rearrange the categorized symbology and closing / reopening the project, the LegendItem shows the wrong symbols.

The issue is, that the key of the symbols is used as index as well.

Rule Based Symbology is not affected since of using UUIDs as keys and a a `Rule` object managing the finding of the index etc.

### Steps to reproduce the issue

When I have a MapTheme defining what categorized symbols are checked. Like here the blue category:
![image](https://user-images.githubusercontent.com/28384354/233094599-5a5fd9a0-1713-4d70-bb91-a5f652c5e087.png)

And then I move the symbols in the categorization (or add a new one) - cyan moved up:
![image](https://user-images.githubusercontent.com/28384354/233094773-7f9102b2-4fcf-4111-b9aa-46569b43c26e.png)

The checked state persists, but on choosing now my stored map theme again, cyan got checked:
![image](https://user-images.githubusercontent.com/28384354/233095020-41c13974-b308-4466-abe7-f04d129dc453.png)

It's not an index, it's an id, but apparently on categorized symbology those ids are reset with low numbers.

This in contrast to rule based. Here the id's are represented by UUIDs (see python output):
![image](https://user-images.githubusercontent.com/28384354/233095950-db48f13a-e2c0-4ae9-9f99-b80b8be88f1f.png)

And on modifying the order the checked symbol persists:
![image](https://user-images.githubusercontent.com/28384354/233096180-48c25d23-0f31-4920-882d-8acb79b004b2.png)

### Versions

At least from 3.22 on until b603a2e394d23ba53733c2d70910ccc05d0c4877

QGIS version | 3.31.0-Master | QGIS code revision | b603a2e394
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
linking_relation_editor | v1.1.4
QgisModelBaker | v7.4.0
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context
[catsymbols.zip](https://github.com/qgis/QGIS/files/11273906/catsymbols.zip)

Including Graduated and Rulebased:
[catsymbols_extended.zip](https://github.com/qgis/QGIS/files/11293638/catsymbols_extended.zip)

**Comment by roya0045** [comment]
I got some weird sync between the main layer tree and the layer styling panel, when sometimes only the changes in the layer styling works (ticking symbols or pasting symbols). I know I made a PR regarding rulekey but I don't know if that's the issue or a signal issue.

**Comment by signedav** [comment]
@roya0045 Not sure if the weird sync you describe has anything to do with your PR but I think it's not related to this issue here. Since here the sync is not the problem, the problem is how the key of ***categorized*** symbols is stored and used. 

E.g. here we use numeric keys here `QgsCategorizedSymbolRenderer::baseLegendSymbolItems` and then later we use them as index e.g. `QgsCategorizedSymbolRenderer::setLegendSymbolItem` (while in `QgsRuleBasedRenderer` we have a `Rule` object we can find the rule by key and set the state accordingly.

**Comment by signedav** [comment]
I see two approaches to solve this:
-  making the ruleKey independent from the index (the order of the categories) and implement kind of `Rule` object like in rule based symbology.
- solve it at QgsMapThemeCollection by storing in the record not the value received with `RuleKeyRole` but instead kind of `QgsLayerTreeModelLegendNode::IdentityKeyRole` that has a unique value of the node or the `QgsSymbol` (here we would need to be aware duplication etc.) or whereever
