### ISSUE TITLE
Args handling of Python expression functions is buggy

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#52796]
### What is the bug or the crash?

The `args` argument of the `@qgsfunction` decorator for Python expression functions is totally bonkers and I wonder if we can just nuke it completely. Here are some simple examples which seem reasonable as a developer who just looks at the dialog and the documentation but which fail in various ways. I meant to improve documentation in that area (#51098) but this seems like a very worthy area of simplification.

Why do we even need to expose the `args=` parameter to Python expression function developers? I cannot imagine any case where one would want to set it to a specific number and not use `"auto"`.

PS: This feels totally like a deja-vu, sorry if I reported this before but I guess I never submitted it earlier.

### Steps to reproduce the issue

# Explicit argument counts
If we specify explicit argument counts, for the arguments we as end-users actually will use for the functions, it will not work because of a variety of reasons:

## args=0 and no arguments
```
@qgsfunction(args=0)
def func_args0_noargs():
    return 1
```

`func_args0_noargs()` results in an index error because `QgsPyExpressionFunction.func` always expects more parameters:

```
Eval Error: list index out of range:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 83, in func
    if inspect.getfullargspec(self.function).args[-1] == 'context':
IndexError: list index out of range
```

This is a simple bug, the code should check the length of the args before trying at an index. But the current code would still append `feature` and `parent` and run into the issues of the next examples.

## args=1 and 1 argument
```
@qgsfunction(args=1)
def func_args1_1arg(arg):
    return arg
```

`func_args1_1arg(1)` fails because `feature` and `parent` are automatically appended:

```
Eval Error: func_args1_1arg() takes 1 positional argument but 3 were given:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 85, in func
    return self.function(values, feature, parent)
TypeError: func_args1_1arg() takes 1 positional argument but 3 were given
```

The function does not care about `feature` or `parent`, it just takes something independent, does something and returns something. But `feature` and `parent` are appended automatically anyways, without adjusting the args count simultaneously.

You might think that using `args=3` would fix it but noooooo, that just leads to:
 ```
Parser Errors:
func_args1_1arg function is called with wrong number of arguments. Expected 3 but got 1.
```

:exploding_head: 

## args=2 and 2 arguments
```
@qgsfunction(args=2)
def func_args2_2args(arg1, arg2):
    return arg1 + arg2
```

`func_args2_2args(1, 2)`  fails because `feature` and `parent` are automatically appended:

```
Eval Error: func_args2_2args() takes 2 positional arguments but 3 were given:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 85, in func
    return self.function(values, feature, parent)
TypeError: func_args2_2args() takes 2 positional arguments but 3 were given
```

Same as above.

## args=3 and 3 arguments
```
@qgsfunction(args=3)
def func_args3_3args(arg1, arg2, arg3):
    return arg1 + arg2 + arg3
```

`func_args3_3args(1, 2, 3)` fails but later now because *my* three arguments get stuffed into a list as `arg1`, and `arg2` and `arg3` become `feature` and `parent`...:

```
Eval Error: can only concatenate list (not "QgsFeature") to list:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 85, in func
    return self.function(values, feature, parent)
  File "", line 18, in func_args3_3args
TypeError: can only concatenate list (not "QgsFeature") to list
```

If I add prints to the func_args3_3args function:
```
arg1=[1, 2, 3]
arg2=<qgis._core.QgsFeature object at 0x7f3004dfcc10>
arg3=<QgsExpression: 'func_args3_3args(1, 2, 3) '>
```

Now this one is even more weird for the end-user/expression function developer. Here the arguments get turned into a list. Absolutely non-intuitive and hard to reason for. :zany_face: 

## args=4 and 4 arguments
```
@qgsfunction(args=4)
def func_args4_4args(arg1, arg2, arg3, arg4):
    return arg1 + arg2 + arg3 + arg4
```

`func_args4_4args(1, 2, 3, 4)` fails with an issue around the arguments again, I guess because my four numbers again got stuffed into a single list as `arg1`, then come `feature` and `parent` and no forth parameter :

```
Eval Error: func_args4_4args() missing 1 required positional argument: 'arg4':
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 85, in func
    return self.function(values, feature, parent)
TypeError: func_args4_4args() missing 1 required positional argument: 'arg4'
```

# "auto"matic argument count
## args="auto" and no argument
```
@qgsfunction(args="auto")
def func_auto_noargs():
    return True
```

fails immediately when the user hits the "Save and load functions" button, so it cannot even be used:
```
Traceback (most recent call last):
  File "", line 28, in 
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 174, in wrapper
    return register_function(func, args, group, **kwargs)
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 114, in register_function
    if args[-1] == 'context':
IndexError: list index out of range
```

Same issue as the no argument example above, the list is empty but element `-1` is tried.

## args="auto" and 1 argument
```
@qgsfunction(args="auto")
def func_auto_1arg(arg):
    return arg
```

`func_auto_1arg(1)` results in:
```
Eval Error: func_auto_1arg() takes 1 positional argument but 3 were given:
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/core/additions/qgsfunction.py", line 81, in func
    return self.function(*values)
TypeError: func_auto_1arg() takes 1 positional argument but 3 were given
```

Same as above in the `args=N` examples but 'hey, I said "auto" because I don't care, it should just work?'

This could be fixed by adding `feature` and `parent` explicitly as parameters: `func_auto_1arg(arg, feature, parent)`  
But the function call is still just `func_auto_1arg(value)` and as function developer I do not need `feature` and `parent` there so why are they forced upon me?

## args="auto" and 2 arguments
```
@qgsfunction(args="auto")
def func_auto_2args(arg1, arg2):
    return arg1 + arg2
```

`func_auto_2args(1, 2)` fails with:
```
Parser Errors:
func_auto_2args function is called with wrong number of arguments. Expected 0 but got 2.
```

Two got subtracted because `feature` and `parent` are added but then something else fails anyways.

## args="auto" and 3 arguments
```
@qgsfunction(args="auto")
def func_auto_3args(arg1, arg2, arg3):
    return arg1 + arg2 + arg3
```

`func_auto_3args` fails with:
```
Parser Errors:
func_auto_3args function is called with wrong number of arguments. Expected 1 but got 3.
```

As above.

## args="auto" and 4 arguments
```
@qgsfunction(args="auto")
def func_auto_4args(arg1, arg2, arg3, arg4):
    return arg1 + arg2 + arg3 + arg4
```

`func_auto_4args(1, 2, 3, 4)` fails with:
```
Parser Errors:
func_auto_4args function is called with wrong number of arguments. Expected 2 but got 4.
```

As above.

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

There is a bug in the current code but I have not started thinking how it might be influencing this because it just seems like one small bit of it, and not the cause for the general weirdness: https://github.com/qgis/QGIS/blame/45e5b3fb79ac7ba097bc2f88f43a332fef4d4a55/python/core/__init__.py#L107 seems to _call_ the function once without caring about it and then in the next line not passing `context` in the function that actually gets returned? @m-kuhn probably meant to `return self.function(values, feature, parent, context)` instead?

**Comment by kannes** [comment]
I would like to try to rework https://github.com/kannes/QGIS/blob/master/python/core/additions/qgsfunction.py to _ignore_ any numeric args count (maybe it could be deprecated in QGIS 4?) and do its magic correctly in the background.

My proposal would be that "feature", "parent" and "context" would be the magic words which, if the user uses them as names for their arguments (and in that order? and at the end?), will get the feature, parent and context objects. But if they don't, those will not magically get passed or appended anymore.

It should be possible to write a function as simple as `my_function(a)` and not have to always append `my_function(a, feature, parent)`.

This is scary to touch though as the API is in wide use. Almost feels like QEP material?

Any thoughts?

**Comment by YoannQDQ** [comment]
Hi Hannes. Are you currently working on that? I have a working implementation, which handles the "magic" parent, feature and context, as well as *args, while being backward compatible with existing expressions. Let me know if you want to tackle this on your own, if I can propose my own PR, or if you'd like to have a look at my implementation.

**Comment by kannes** [comment]
Nope, I jumped to other smaller issues :) I'd highly appreciate your PR and will be curious to look at it. Thank you!
