### ISSUE TITLE
strange behaviour of single sided buffer algorithm

### ISSUE THREAD

**Issue by juliepierson** [qgis/QGIS#52795]
### What is the bug or the crash?

I had problems using singlesidedbuffer algorithm in QGIS on a line layer. This tools creates strange looking buffer zones with bits on the other side of the line. I saw 2 posts on gistackexchange relating this problem : https://gis.stackexchange.com/questions/289690/single-sided-buffer-error-qgis and https://gis.stackexchange.com/questions/419028/single-sided-buffer-qgis-strange-behaviour

### Steps to reproduce the issue

1. Create a line layer with some bends
2. Use native:singlesidedbuffer tool with default parameters
3. The output looks strange and has bits on the other side of the line
![image](https://user-images.githubusercontent.com/6247389/233366555-20d3f98e-bb70-423d-ac49-9334b1a7ea8f.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.16-Białowieża | Révision du code | 6f08e4d7b0
-- | -- | -- | --
Version de Qt | 5.12.8
Version de Python | 3.8.10
Version de GDAL/OGR | 3.0.4
Version de Proj | 6.3.1
Version de la base de données du registre EPSG | v9.8.6 (2020-01-22)
Compilé avec GEOS | 3.8.0-CAPI-1.13.1 | Utilisé avec GEOS | 3.8.0-CAPI-1.13.1
Version de SQLite | 3.31.1
Version de PDAL | 2.0.1
Version du client PostgreSQL | 12.13 (Ubuntu 12.13-0ubuntu0.20.04.1)
Version de SpatiaLite | 4.3.0a
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.2
Version de l'OS | Ubuntu 20.04.6 LTS
  |   |   |  
Extensions Python actives
processing_wbt | 1.3.5
mapswipetool_plugin | 1.2
DataPlotly | 3.9.2
Generalizer3 | 1.0
pluginbuilder3 | 3.2.1
DissolveWithStats | 0.6
SLD4raster | 1.0
Qgis2threejs | 2.7.1
mmqgis | 2021.9.10
river_tools_processing | 0.1
processing_r | 3.1.1
QuickOSM | 2.1.1
plugin_reloader | 0.9.3
QNEAT3 | 1.0.4
ViewshedAnalysis | 1.8
cartolinegen | 3.2.2
LAStools | 1.4
nominatim_locator_filter | 0.2.4
GroupStats | 2.2.6
rename_bands | 0.1
french_locator_filter | 1.0.4
d3datavis | 3.0.3
simplesvg | 3.0.3
networks | 2.7.5
db_manager | 0.1.20
grassprovider | 2.12.99
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
coastline_change | 0.1

</body></html>Version de QGIS
3.22.16-Białowieża
Révision du code
[6f08e4d7b0](https://github.com/qgis/QGIS/commit/6f08e4d7b0)
Version de Qt
5.12.8
Version de Python
3.8.10
Version de GDAL/OGR
3.0.4
Version de Proj
6.3.1
Version de la base de données du registre EPSG
v9.8.6 (2020-01-22)
Compilé avec GEOS
3.8.0-CAPI-1.13.1
Utilisé avec GEOS
3.8.0-CAPI-1.13.1 
Version de SQLite
3.31.1
Version de PDAL
2.0.1
Version du client PostgreSQL
12.13 (Ubuntu 12.13-0ubuntu0.20.04.1)
Version de SpatiaLite
4.3.0a
Version de QWT
6.1.4
Version de QScintilla2
2.11.2
Version de l'OS
Ubuntu 20.04.6 LTS

Extensions Python actives
processing_wbt
1.3.5
mapswipetool_plugin
1.2
DataPlotly
3.9.2
Generalizer3
1.0
pluginbuilder3
3.2.1
DissolveWithStats
0.6
SLD4raster
1.0
Qgis2threejs
2.7.1
mmqgis
2021.9.10
river_tools_processing
0.1
processing_r
3.1.1
QuickOSM
2.1.1
plugin_reloader
0.9.3
QNEAT3
1.0.4
ViewshedAnalysis
1.8
cartolinegen
3.2.2
LAStools
1.4
nominatim_locator_filter
0.2.4
GroupStats
2.2.6
rename_bands
0.1
french_locator_filter
1.0.4
d3datavis
3.0.3
simplesvg
3.0.3
networks
2.7.5
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
coastline_change
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

I saw 2 posts on gistackexchange relating this problem : https://gis.stackexchange.com/questions/289690/single-sided-buffer-error-qgis and https://gis.stackexchange.com/questions/419028/single-sided-buffer-qgis-strange-behaviour

It seems the problem stems from the geos library, which is used in other softwares. There is an issue in libgeos here : https://github.com/libgeos/geos/issues/665

In this issue, Paul Ramsey indicates that the singlesidedbuffer tool is deprecated, and the offsetcurve tool should be used instead. I tried the native:offsetline algorithm in QGIS and the result seems ok, but this tools output a line layer and not a polygon layer.

Maybe the problem should be solved in geos so that all softwares using this tool work ok too ?

**Comment by jgrocha** [comment]
Thank you @juliepierson for the detailed information. It provides valuable help for other users still using SingleSidedBuffer in QGIS. 

As we can see from Paul Ramsey comment, SingleSidedBuffer is deprecated. We can't do nothing on our side, unless someone is willing to develop such algorithm.

I will close the issue, since it is a geos upstream issue.

**Comment by juliepierson** [comment]
Great news, thanks a lot  @strk !! I will test it as soon as I figure out how to do so, I don't know if I can update my version of geos to the latest one without breaking anything.

**Comment by strk** [comment]
@juliepierson upgrades of GEOS should be pretty safe, as long as all the clients use the C-API (it is the case for QGIS).
