### ISSUE TITLE
Plugins are slowing down the QGIS at the first time opening.

### ISSUE THREAD

**Issue by mogurlu** [qgis/QGIS#52798]
### Feature description

If there are many plugins are installed, QGIS is slowing down while the first time opening. Is it possible to pass the loading of plugins at the beginning and loading them later would be faster.

**Comment by roya0045** [comment]
Just deactivate the plugin and activate them when you need.

**Comment by jgrocha** [comment]
Hi @mogurlu 

This is already implemented. You can start qgis with:
```
qgis --noplugins
```
