### ISSUE TITLE
Field Calculator does not save Expressions. Must manually re-enter expressions any time data is modified

### ISSUE THREAD

**Issue by rbwood** [qgis/QGIS#52805]
### What is the bug or the crash?

When making an expression in the Field Calculator, it runs the expression once, and then the expression is gone, it doesn't keep the expression anywhere.  If I add more points, or modify the data in the table, the calculated fields do not update. When I go back to the Field Calculator all expressions are blank again.  The Field calculator needs to keep the expressions entered assigned to the fields, otherwise you have to re-write the expression every time you change any of the data. 

I click "Save to store expression" and a save window appears, but it doesn't appear to actually save anything. 
![image](https://user-images.githubusercontent.com/21110207/233476379-10519f21-378f-48be-8aea-895c6fa8929d.png)
![image](https://user-images.githubusercontent.com/21110207/233476454-07184c8d-4e8b-4ce2-9e4c-e34437cbbd3d.png)
![image](https://user-images.githubusercontent.com/21110207/233476530-3e86370f-68fb-451e-8dce-9861a1c43ce3.png)

I also tried to export my user expression, then import it in again when the expression went back to blank, but importing user expressions just adds it to the list of expressions, not to the expression itself, so it's yet another couple clicks to add it to the expression.

### Steps to reproduce the issue

1. "Open Attribute Table"
2. "Open Field Calculator"
3. "Create New Field" or "Update Existing Field"
4. Enter an expression for the field.
5. "Save to store expression" or not, this doesn't seem to save anything anywhere
6. Click "OK" (Field Calculator closes)
7. Edit some data in the attributes table (move a point, add a point), and see that the calculated field remains at the previous value (or "NULL" if adding a new entry)
8. "Open Field Calculator"
9. "Update Existing Field"
10. Expression is blank again

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
contour
2.0.12
coordinate_capture
0.2
FreehandRasterGeoreferencer
0.8.3
profiletool
4.2.4
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
It seems that what you try to achieve is called "Virtual field" ?

Create a new field, check "virtual field", expression will be stored and values continuously updated.
![image](https://user-images.githubusercontent.com/39594821/233593398-5c27c0bd-6adb-4d24-bc5f-a0cc150901f0.png)

**Comment by uclaros** [comment]
Also, you can find list of your recently used expressions in _Recent_ category so you don't have to type them in again.

**Comment by baswein** [comment]
As an alternative to a virtual field you can also set a default value that will update when ever you make a change. But you can't do that from the field calculator. You have to add it in the Attributes Form in the layer properties panel. 
![image](https://user-images.githubusercontent.com/15817745/233680392-0867e454-4b42-43e2-a9b4-aa256cc2aa4a.png)

I have a feature request/proposal to better integrate this into the field calculator here: 
https://github.com/qgis/QGIS/issues/47883
