### ISSUE TITLE
3D View - Eyedome Lighting sometimes disappearing

### ISSUE THREAD

**Issue by andreasneumann** [qgis/QGIS#52817]
### What is the bug or the crash?

When a certain layer is present in the project "Bodenbedeckung Swisstopo" and the geometry of this layer is outside of the visible viewport, then the eyedome lighting disappears. When one navigates back, it appears again.

### Steps to reproduce the issue

1. Download the project from [https://www.carto.net/neumann/temp/solothurn_3d.zip](https://www.carto.net/neumann/temp/solothurn_3d.zip)
2. Unzip and open the project
3. Make sure the layer "Bodenbedeckung Swisstopo" is turned on
4. Navigate in the scene from south toward the north and eventually see the eyedome lighting disappear. When navigating  back to the South then the eyedome lighting is activated again

https://user-images.githubusercontent.com/884476/233676802-28f6a047-94ed-41a0-b4d4-32670fb7f542.mp4

At the Hertogenbosch hackfest it was discovered that it has to do with the far plane - and the file [qgsvectorlayer3drenderer.cpp](https://github.com/qgis/QGIS/blob/master/src/3d/qgsvectorlayer3drenderer.cpp)

and the following source code lines:

```
  constexpr double MINIMUM_VECTOR_Z_ESTIMATE = -5000000;
  constexpr double MAXIMUM_VECTOR_Z_ESTIMATE = 5000000;
```

If both values are set to "0", then problem disappears - but it has to be investigated if this would have side effects ...

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code revision | 0ce567bd306
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
changeDataSource | 3.1
solocator | 1.6.0
pg_raster_import | 3.2.0
trackable_project_files | v1.2.2
linking_relation_editor | v1.1.9
QgisModelBaker | v7.5.0
AtlasExportFunction | 1.1
processing | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.31.0-Master
QGIS code revision
[0ce567bd306](https://github.com/qgis/QGIS/commit/0ce567bd306)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
changeDataSource
3.1
solocator
1.6.0
pg_raster_import
3.2.0
trackable_project_files
v1.2.2
linking_relation_editor
v1.1.9
QgisModelBaker
v7.5.0
AtlasExportFunction
1.1
processing
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by wonder-sk** [comment]
This should be fixed by https://github.com/qgis/QGIS/pull/54229 - please reopen if still an issue...
