### ISSUE TITLE
Editing two maps in Print Layout and QGIS crashes

### ISSUE THREAD

**Issue by Asiacalbear2020** [qgis/QGIS#52843]
### What is the bug or the crash?

Editing two maps in Print Layout and QGIS crashes.
Crash Report follows:
## User Feedback
Working with two data sets in one layer and trying to make two diffent maps on the same 
## Report Details
**Python Stack Trace**
```
Windows fatal exception: access violation
Current thread 0x00004f58 (most recent call first):
<no Python frame>
```
**Stack Trace**
```
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::layerLegendChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsVectorLayer::setRenderer :
QgsRendererPropertiesDialog::apply :
QgsLayerStylingWidget::apply :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
CallWindowProcW :
DispatchMessageW :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```
**QGIS Info**
QGIS Version: 3.30.0-'s-Hertogenbosch
QGIS code revision: f186b8efe0e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2
**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/63313317/233816618-f64d84bb-9706-409f-96e8-f79f5a58b7f9.png)

### Versions

QGIS is crashed with a swirling blue circle. Can't access the help menu. Clicked "Reload QGIS" button, but window disappeared but no reloading.
restarted:
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
DigitizingTools | 1.5.2
latlontools | 3.6.9
processing_saga_nextgen | 0.0.7
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.2
latlontools
3.6.9
processing_saga_nextgen
0.0.7
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Stack trace similar to https://github.com/qgis/QGIS/issues/52268

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/issues/52268 has been closed, adding feedback.
