### ISSUE TITLE
qgis crash when move points

### ISSUE THREAD

**Issue by Brassjo** [qgis/QGIS#52877]
## User Feedback

the bug persists since a few days. 
It happens every time I try to move a lot of points (about 17 000) to coordinates. I tried with a small number of points (about 20) and the problem persists.
The move I want to do, I have done it many times.

## Report Details

**Crash ID**: [1fbd833906a815a76cdfaf02ca255a3ebe12ab9a](https://github.com/qgis/QGIS/search?q=1fbd833906a815a76cdfaf02ca255a3ebe12ab9a&type=Issues)

**Stack Trace**
<pre>
SpatialIndex::TPRTree::Data::Data :
qsort :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::onFeatureDeleted :
QgsPointLocator::onGeometryChanged :
QObject::qt_static_metacall :
QgsVectorLayer::geometryChanged :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::geometryChanged :
QUndoStack::push :
QgsVectorLayerEditBuffer::changeGeometry :
QgsVectorLayer::changeGeometry :
QgsMapToolMoveFeature::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.5-Bia?owie?a
QGIS code revision: c2723178
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.4.1
Running against GDAL: 3.4.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/131673097/233994983-78cbb599-1c07-4208-a096-49c65543320d.png)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.5-Białowieża | Révision du code | c2723178
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 13.0
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.3
Version de QScintilla2 | 2.11.5
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
batch_gps_importer | version 1.0.1
MagneticDeclination | 2.3.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.5
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.22.5-Białowieża
Révision du code
[c2723178](https://github.com/qgis/QGIS/commit/c2723178)
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.4.1
Version de Proj
8.2.1
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.37.2
Version de PDAL
2.3.0
Version du client PostgreSQL
13.0
Version de SpatiaLite
5.0.1
Version de QWT
6.1.3
Version de QScintilla2
2.11.5
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
batch_gps_importer
version 1.0.1
MagneticDeclination
2.3.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Did you actually try with a new qgis user profile ?
There is some non-core plugins listed in your report.

If it still persist, could you share a sample project to reproduce ?

**Comment by Brassjo** [comment]
Yes i try and i have same issue.
[test_points.zip](https://github.com/qgis/QGIS/files/11310725/test_points.zip)

**Comment by nicogodet** [comment]
> Version de QGIS | 3.22.5-Białowieża

Also, this version is out-dated and not maintained. Please try on 3.28.5 or 3.30.1.

**Comment by Brassjo** [comment]
i try with 3.30

## User Feedback

same problem with 3.22

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000062b4 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
SpatialIndex::TPRTree::Data::Data :
QgsPointLocator::onFeatureDeleted :
QgsPointLocator::onGeometryChanged :
QObject::qt_static_metacall :
QgsVectorLayer::geometryChanged :
QObject::qt_static_metacall :
QgsVectorLayerEditBuffer::geometryChanged :
QUndoStack::push :
QgsVectorLayerEditBuffer::changeGeometry :
QgsVectorLayer::changeGeometry :
QgsMapToolMoveFeature::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by nicogodet** [comment]
I tried your dataset. I can't reproduce the crash.
Could you step by step describe how to reproduce with provided sample ?

**Comment by Brassjo** [comment]
select my shapefile
open edition mod
select all my points
select move entities
select one point and the message appear: some of the entities are out of sight, do you want to continue
clic "yes"
i move the points
and after that qgis crash

**Comment by nicogodet** [comment]
No crash
![Animation6](https://user-images.githubusercontent.com/39594821/234038217-ce77f918-caae-4295-9154-805505ddbde0.gif)

But there is something strange with test1_point, this file could be corrupted.
If I selected all visible points, 174 points are selected while there is 191 points in layer.

**Comment by Brassjo** [comment]
ok i will check that and i will be back with.
Thanks a lot

**Comment by jgrocha** [comment]
> No crash ![Animation6](https://user-images.githubusercontent.com/39594821/234038217-ce77f918-caae-4295-9154-805505ddbde0.gif) [ ![Animation6](https://user-images.githubusercontent.com/39594821/234038217-ce77f918-caae-4295-9154-805505ddbde0.gif) ](https://user-images.githubusercontent.com/39594821/234038217-ce77f918-caae-4295-9154-805505ddbde0.gif) [ ](https://user-images.githubusercontent.com/39594821/234038217-ce77f918-caae-4295-9154-805505ddbde0.gif)
> 
> But there is something strange with test1_point, this file could be corrupted. If I selected all visible points, 174 points are selected while there is 191 points in layer.

test1_point has several points like this:

```
OGRFeature(test1_point):174
  Arbre (Real) = 32.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):175
  Arbre (Real) = 361.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):176
  Arbre (Real) = 2005.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):177
  Arbre (Real) = 3349.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):178
  Arbre (Real) = 4828.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):179
  Arbre (Real) = 4860.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):180
  Arbre (Real) = 4863.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):181
  Arbre (Real) = 4994.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):182
  Arbre (Real) = 5033.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):183
  Arbre (Real) = 5076.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):184
  Arbre (Real) = 5166.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):185
  Arbre (Real) = 5197.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):186
  Arbre (Real) = 5254.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):187
  Arbre (Real) = 5262.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):188
  Arbre (Real) = 5266.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):189
  Arbre (Real) = 5333.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)

OGRFeature(test1_point):190
  Arbre (Real) = 7848.000000
  POINT Z (-1.79769313486232E+308 -1.79769313486232E+308 -1.79769313486232E+308)
```

**Comment by Brassjo** [comment]
now I move by small groups of points to try to find the problematic points

**Comment by jgrocha** [comment]
> 

1) Select the visible points
2) Edit → Select → Invert feature selection
3) Remove those points (17 on my side)

Then the file will be ok. Test with valid geometries. You have geometries outside the CRS bounds.

**Comment by Brassjo** [comment]
Yes, it works.
thank a lot
