### ISSUE TITLE
overlay_intersects() not working when snapping on segment

### ISSUE THREAD

**Issue by 9ls1** [qgis/QGIS#52884]
### What is the bug or the crash?

I have a line layer and a point layer. I want the **line** (and it's label) to change color if a point is digitized on it (e.g. the point intersects the line). The expressions seems to only work when snapping type is vertex and not segment.

### Steps to reproduce the issue

I have added this expression for the line color:
`case 
 when overlay_intersects('arter1') is false then color_rgb(255,89,0)  --dark orange
 else color_rgb(175,93,230)  --purple
end`

And this expression for the line label color:
`case
 when aggregate(layer:='arter1', aggregate:='max', expression:="feltarbeider", filter:=intersects($geometry, geometry(@parent))) != '' and aggregate(layer:='arter1', aggregate:='max', expression:="flatenr", filter:=intersects($geometry, geometry(@parent))) = "Flatenr" then color_rgb(175,93,230) --purple
 else color_rgb(255,89,0) --dark orange
end`

Before digitizing a point on line segment no. 5:
![image](https://user-images.githubusercontent.com/10632163/234287418-cd0e6c53-56c4-4351-aca7-bca8fe0c34cc.png)

When the snapping type for the line is set to "**Vertex**" everything works as expected: the line segment and its label changes from orange to purple when a point is digitized (and intersecting the line layer):
![image](https://user-images.githubusercontent.com/10632163/234284902-4f12f795-c0d3-4774-87b1-7819b84ca56c.png)
Result after digitizing a point (and panning the map a little bit):
![image](https://user-images.githubusercontent.com/10632163/234287898-03a6ac51-d686-4bc7-b612-34bcdf31524a.png)

Now changing the snapping type to "**Segment**":
![image](https://user-images.githubusercontent.com/10632163/234285504-6864eac3-5be8-429a-a4ca-643cb09ddb03.png)

And digitizing a new point on line segment no. 4: The line and label color is not changing
![image](https://user-images.githubusercontent.com/10632163/234288785-e905b8a4-0ba3-49f6-b41e-69a423cdc963.png)

I would like to use Segment since some line segments don't have any vertexes (beside the start and end node), and I want to use the different colors to help the users to see if all line segments are visited (no orange line segments left).

### Versions
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0e
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
coordinator | 0.4
get_nib-main | 0.9
Go2NextFeature3 | 2.1
GroupStats | 2.2.7
InvisibleLayersAndGroups | 2.2
kmltools | 3.1.28
legend_data_filter | 0.1
NavTable | 0.1.1
plugin_reloader | 0.9.3
Projestions | 1.0.1
qfieldsync | v4.4.9
raster_tracer | 0.3.2
slyr_community | 4.0.7
Smart_Map | 1.3
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
[f186b8efe0e](https://github.com/qgis/QGIS/commit/f186b8efe0e)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
coordinator
0.4
get_nib-main
0.9
Go2NextFeature3
2.1
GroupStats
2.2.7
InvisibleLayersAndGroups
2.2
kmltools
3.1.28
legend_data_filter
0.1
NavTable
0.1.1
plugin_reloader
0.9.3
Projestions
1.0.1
qfieldsync
v4.4.9
raster_tracer
0.3.2
slyr_community
4.0.7
Smart_Map
1.3
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

A similar issue is mentioned in #47201 (but here working on the same layer).

**Comment by elpaso** [comment]
I'm afraid this is not a bug: when the point is snapped to the edge it is calculated by interpolation with a limited mathematical precision, when the intersection test is executed by GEOS library the intersection will return false.

You can reproduce the issue using QgsGeometry directly from the python console: take the point geometry, the line geometry and call intersects(), it will return false.

A tiny buffer is enough to make the test pass.

```python
pojnt.intersects(line)
False
point.buffer(0.00000000001, 100).intersects(line)
True
```

There is no workaround that I am aware of, a possible enhancement to the `overlay_intersects`  function would be to add an optional argument `buffer` to add a buffer around the geometry before GEOS executes the intersection test.

**Comment by 9ls1** [comment]
@elpaso Thanks for replying and explaning. "There is no workaround that I am aware of, a possible enhancement to the overlay_intersects function would be to **add an optional argument buffer to add a buffer around the geometry before GEOS executes the intersection test**." That would be great! 🤞👍

**Comment by DelazJ** [comment]
![image](https://user-images.githubusercontent.com/7983394/236156183-a1700064-f60a-4722-a00d-97068e208e93.png)

![image](https://user-images.githubusercontent.com/7983394/236155913-616b7086-6cb4-4cb2-a87b-1c4a3b68a7c7.png)

So Should this be reopened or a new issue report on the "buffer" parameter created?

**Comment by elpaso** [comment]
> ![image](https://user-images.githubusercontent.com/7983394/236156183-a1700064-f60a-4722-a00d-97068e208e93.png)
> 
> ![image](https://user-images.githubusercontent.com/7983394/236155913-616b7086-6cb4-4cb2-a87b-1c4a3b68a7c7.png)
> 
> So Should this be reopened or a new issue report on the "buffer" parameter created?

I guess a new issue with the feature request, pointing to this issue, is the right thing to do.
