### ISSUE TITLE
Crashed when clicking the Scale dropdown

### ISSUE THREAD

**Issue by K1DV5** [qgis/QGIS#52882]
## User Feedback

I just opened a shapefile from the browser, zoomed in by double clicking, and clicked the "Scale" dropdown at the bottom bar. That's all.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000028ac (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QLocale::numberOptions :
QCalendarBackend::standaloneWeekDayName :
QString::toInt :
QgsScaleComboBox::showPopup :
QComboBox::showPopup :
QComboBox::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

1. Open a shapefile from the sidebar browser
2. Zoom by double clicking
3. Click the Scale dropdown from the bottom bar

### Versions

**QGIS Info**
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

This is a newly downloaded version and the shapefile I opened is the first one.

**Comment by roya0045** [comment]
This is a duplicate ticket and should be fixed by #52580
