### ISSUE TITLE
Display issue with the QGIS desktop on lunar 23.04

### ISSUE THREAD

**Issue by mr-xed** [qgis/QGIS#52893]
### What is the bug or the crash?

Hello, I would like to report a graphic bug that appeared with the Lunar 23.04 update of Ubuntu. Currently using version 3.30 of QGIS, when I launch the application, the loading screen appears in the upper left corner of the screen, the window has a completely different style with Windows-style icons for maximize, minimize, and close, and the cursors are different from the default system theme. In fact, I end up with huge cursors that make it impossible to use the application properly; this is very annoying because operations like georeferencing are impossible to perform accurately. I could provide photos of these events. If the problem has already been resolved, could you please let me know the steps to follow? Best regards.

### Steps to reproduce the issue

1. Open the application

### Versions

3.30

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

![Schermata del 2023-04-26 10-37-30](https://user-images.githubusercontent.com/131817951/234520487-cf0e8a1b-1864-4879-be1d-7d99a7134ab8.png)

**Comment by mr-xed** [comment]
I check the APP Style in the setting panel and the current active theme it's Fusion

**Comment by agiudiceandrea** [comment]
@mr-xed I don't see any issue in the provided screenshot. Could you please attach a screenshot actually showing the issue or better point out where the issue is shown in the screenshot? Could you please try if the issue does occur also using a new QGIS user profile? Could you please provide the information available in Help->About window as requested in the issue report form?

**Comment by mr-xed** [comment]
![Schermata del 2023-04-26 13-15-31](https://user-images.githubusercontent.com/131817951/234559043-4858ac43-6d1e-4bd3-be9b-42d9fd95ae08.png)

Hello here is a screenshot with the informations from QGIS. As you can see, the cursor it's too big and the screenshoot

**Comment by mr-xed** [comment]
Hello, I would like to come back to you because the problem has been solved. For all users of QGIS in 3.30 on Ubuntu Lunar 23.04, if you encounter the same display problem as on the previous images, you must start your session on Gnome Xorg to no longer have display problems. I think it's a problem of application theme causing a different theme on QGIS with deformation problems.

Sincerely
