### ISSUE TITLE
is it a clerical error?Duplicate assignment

### ISSUE THREAD

**Issue by alingkumo** [qgis/QGIS#52895]
### What is the bug or the crash?

in the line 355,should be labelXMax?

### Steps to reproduce the issue

 clerical error

### Versions

latest

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alingkumo** [comment]
[      switch ( settings.symbolAlignment() )
      {
        case Qt::AlignLeft:
        default:
          labelXMin = ctx->columnLeft;
          labelXMax = ctx->columnLeft + rampWidth;
          break;


        case Qt::AlignRight:
          labelXMin = ctx->columnRight - rampWidth;
          labelXMin = ctx->columnRight;
          break;
      }](https://github.com/qgis/QGIS/blob/3864de6d668fdff04c54448c70923f5effc8f1c7/src/core/layertree/qgscolorramplegendnode.cpp#L345-L357)

**Comment by nicogodet** [comment]
Could you open a PR with the proposed change ?
Indeed, it seems a typo to me.

**Comment by agiudiceandrea** [comment]
@alingkumo, does it generate an actual bug?

**Comment by alingkumo** [comment]
Here's the situation:when I use the raster legend,set the Orientation-> Horizontal,and it works well. at this time,the arrangement is  'Symbols on Left'
![left](https://user-images.githubusercontent.com/49809717/235065604-5f8429c0-2772-4877-ba61-c9bd34203cba.png)
then I change the arrangement to 'Symbols on Right'
![right](https://user-images.githubusercontent.com/49809717/235065640-7f266354-7826-4542-974d-a76086e1a9a2.png)
as you can see ,there is an error in the position of the label.so i read the code and find this typo.
![right2](https://user-images.githubusercontent.com/49809717/235073348-f0e0f199-57f3-470e-8614-0787bc8b1bbf.png)
maybe this should be the right thing.

in the line 355 should be :
labelXMax = ctx->columnRight;

That's all,thanks.

**Comment by agiudiceandrea** [comment]
@alingkumo thanks for reporting! Good catch! Would you prefer to fix the issue by yourself opening a PR?

**Comment by alingkumo** [comment]
My pleasure!I'll try to learn how to open a PR!
