### ISSUE TITLE
QGIS DB manager lowercase conversion is broken

### ISSUE THREAD

**Issue by anniinaiikkanen** [qgis/QGIS#52898]
### What is the bug or the crash?

When importing layer/file to PostGIS via QGIS' DB manager, it converts field names to lowercase even if it's not checked in the "import vector layer" window. I've tried this with multiple vector layers and two different PostGIS databases and the same problem persists.

### Steps to reproduce the issue

1. Open any vector layer to QGIS
2. Go to DB manager and click "import layer/file to PostGIS"
3. Select the vector layer that is open in you QGIS and **do not** check the "convert field names to lowercase" box and click OK
4. Go to the designated PostGIS database and check the layer's field names

### Versions

QGIS 3.28.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Tested with the latest master (36c53ea14ced0975ecde67027f8468770ebcd67d). This happens only with shapefiles.
