### ISSUE TITLE
Project is not displaying in QGIS 3.30.1 eventhough layers are visible

### ISSUE THREAD

**Issue by MinoruAmaya** [qgis/QGIS#52894]
### What is the bug or the crash?

Hi,
i´m not an expert in qgis. I started a project where i create a linestring shapefile und a multipoint shapefile to create something like a "network". I also saved the project and when i reopened my project, there was nothing to see anymore except white. I also zoomed in and out , but my "network " is still invisible. Can somebodoy help me to fix it?

![image](https://user-images.githubusercontent.com/102677572/234502599-8f76b364-7ccb-40d8-ad6d-7b630f6f704b.png)

### Steps to reproduce the issue

Here is the screenshot:
![image](https://user-images.githubusercontent.com/102677572/234503317-b4dd04c1-e782-418b-b47c-c75a4b802f5c.png)

### Versions

The Version is  3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by MinoruAmaya** [comment]
Qutting QGIS and reopening it didn´t also work.

**Comment by alexbruy** [comment]
This seems to be a local issue. Can you provide exact steps to reproduce your issue and maybe share test data?
