### ISSUE TITLE
Advanced digitizing is not disabled for pan and select tools

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#52897]
### What is the bug or the crash?

When using the pan tool or the selection tool the user is still allowed to enable _Advanced digitizing tools_

### Steps to reproduce the issue

1. Activate the pan tool (or select features tool, or identify tool)
2. Enable the _Advanced digitizing toolbar_ or _panel_
3. The button to enable Advanced digitizing tools is enabled (it should be grayed out)
4. If the _floater_ is enabled, it is visible next to the mouse cursor

### Versions

Master (30870dfc), not sure when this first appeared.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (936c53ea14ced0975ecde67027f8468770ebcd67d) on Linux.

**Comment by uclaros** [comment]
Me neither, not sure how this was fixed though :)
