### ISSUE TITLE
Add option to keep field calculator window open after execution

### ISSUE THREAD

**Issue by Martin-BKT** [qgis/QGIS#52901]
### Feature description

When a field calculator calculation is executed, the field calculator window closes. This is fairly inefficient when several similar calculations need to be done for the fields in a table. For each calculation the field calculator needs to be reopened and the code must at least be pasted into the (empty) command window again.

The feature request is to add a checkbox in the field calculator window to keep it open after execution, with all the settings staying the same. This would speed up multiple calculations quite significantly.

**Comment by baswein** [comment]
Martin- I agree with you. There is some discussion on this here: https://github.com/qgis/QGIS-Enhancement-Proposals/issues/255

**Comment by Martin-BKT** [comment]
Yes, when the field calculator gets a general refresh, this option would probably be part of that. However, I think until the global refresh gets done, my proposed option would be useful and not very complicated to implement.

**Comment by roya0045** [comment]
A simpler option would be to have refactor fields work in-place instead of creating a new layer.
