### ISSUE TITLE
Qgis crash when I click on the scale combo box

### ISSUE THREAD

**Issue by CalvinMP** [qgis/QGIS#52906]
## User Feedback

I crashed when I clicked on the scale combo box, it keeps crashing when I click on it. Also it is impossible to read anything, the combo box is too small.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003844 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QString::toInt :
QgsScaleComboBox::showPopup :
QComboBox::showPopup :
QComboBox::mousePressEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Click on the scale combo box

### Versions

Qgis 3.30.1 (Latest)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Fixed in next point release.
Please search before reporting.
