### ISSUE TITLE
GDAL Fill nodata does not work if compression is used 

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#52905]
### What is the bug or the crash?

When I use GDAL Fill nodata in QGIS 3.26, 3.30, 3.31 and any of the compression options are set in the advanced tab the algorithm fails. 

Here is the error report. 

QGIS version: 3.31.0-Master
QGIS code revision: 8f33d5ee70
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.0dev-717dcc0eed
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.0, March 1st, 2023
PDAL version: 2.5.2 (git-version: 57c4e7)
Algorithm started at: 2023-04-26T13:32:27
Algorithm 'Fill nodata' starting…
Input parameters:
{ 'BAND' : 1, 'DISTANCE' : 10, 'EXTRA' : '', 'INPUT' : 'C:/Users/me/Documents/temp_qgis/Fill NoData/to_FIll.tif', 'ITERATIONS' : 0, 'MASK_LAYER' : None, 'NO_MASK' : False, 'OPTIONS' : 'COMPRESS=PACKBITS', 'OUTPUT' : 'TEMPORARY_OUTPUT' }

GDAL command:
gdal_fillnodata.bat -md 10 -b 1 -of GTiff -co COMPRESS=PACKBITS "C:/Users/me/Documents/temp_qgis/Fill NoData/to_FIll.tif" C:/Users/me/AppData/Local/Temp/processing_RuvdkU/c46bffad24d446a8a9bb74efc2f6503b/OUTPUT.tif
GDAL command output:
usage: gdal_fillnodata.py [-h] [-q] [-md max_distance] 
[-si smoothing_iterations] [-o [name=value ...]] 
[-mask filename] [-b band] [-of gdal_format] 
[-co [name=value ...]] 
src_filename dst_filename 
gdal_fillnodata.py: error: the following arguments are required: src_filename, dst_filename
Process returned error code 2
Execution completed in 0.49 seconds
Results:
{'OUTPUT': 'C:/Users/me/AppData/Local/Temp/processing_RuvdkU/c46bffad24d446a8a9bb74efc2f6503b/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/me/AppData/Local/Temp/processing_RuvdkU/c46bffad24d446a8a9bb74efc2f6503b/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
 

### Steps to reproduce the issue

1. Open up QGIS.
2. Add a raster layer with holes 
3. Open up the Fill nodata algo (not to be confused with Fill NoData cells)
4. In **Advanced: Additional creation options** set the compression to any of No, Low, High (Default works)
5. Press Run and get the error.  

### Versions

QGIS version
3.31.0-Master
QGIS code revision
8f33d5ee70
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0dev-717dcc0eed
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

Here is some sample data: 
[fill_nodata_issue.zip](https://github.com/qgis/QGIS/files/11336153/fill_nodata_issue.zip)

**Comment by nicogodet** [comment]
Same error when running command from OSGeo shell directly

**Comment by nicogodet** [comment]
It can be fixed on QGIS side but I will wait until issue get processed on GDAL side.

**Comment by agiudiceandrea** [comment]
I think it should be fixed also on QGIS side, for systems (like Ubuntu Linux) on which the GDAL library will not be updated frequently.
