### ISSUE TITLE
no layer sort via mouse under gnome 44

### ISSUE THREAD

**Issue by gisholger** [qgis/QGIS#52922]
### What is the bug or the crash?

bug

### Steps to reproduce the issue

Load layers and try to change the  position inside the layer panel via mouse.  Also no drag and drop from browser panel.

### Versions

3.30, master, ...

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is a (ridiculous) bug in gnome itself: https://gitlab.gnome.org/GNOME/mutter/-/issues/2715
