### ISSUE TITLE
Can't override dark or light theme setting under Ubuntu 23.04

### ISSUE THREAD

**Issue by mapperfr** [qgis/QGIS#52920]
### What is the bug or the crash?

When set to "default", the UI theme adapts to the global system options. It would be great to have an option to override this behaviour - e.g. keeping QGIS on default light theme while the system is set to dark mode, or the other way around.

See the system options in the top right angle and the "Thème UI" option in the QGIS settings, on the following screenshots:

![Capture d’écran du 2023-04-27 09-59-22](https://user-images.githubusercontent.com/3398608/234799183-be2649f8-acf8-4b8a-b1b1-7e717250ca52.png)
![Capture d’écran du 2023-04-27 09-58-47](https://user-images.githubusercontent.com/3398608/234799198-4c06413f-e85a-49fc-a27b-65bc78ebe3d5.png)

### Steps to reproduce the issue

1. Set your system to dark mode
2. Open QGIS
3. Go to Preferences > Options > General
4. Check "default" in "theme UI"
5. Restart QGIS
6. Check if QGIS is in dark mode or light mode

Repeat the steps by changing step 1 and setting your system to light mode. QGIS theme UI follows the global UI theme with no way to override the behaviour.

### Versions

Version de QGIS | 3.30.1-'s-Hertogenbosch | Branche de code de QGIS | Release 3.30
-- | -- | -- | --
Version de Qt | 5.15.9
Version de Python | 3.10.6
Version de GDAL/OGR | 3.6.3
Version de Proj | 9.2.0
Version de la base de données du registre EPSG | v10.082 (2023-02-06)
Version de GEOS | 3.11.2-CAPI-1.17.2
Version de SQLite | 3.36.0
Version de PDAL | 2.5.3
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.5
Version de QScintilla2 | 2.11.6
Version de l'OS | KDE Flatpak runtime
  |   |   |  
Extensions Python actives
GeoCoding | 2.18
qgiscloud | 3.8.4
qgis_resource_sharing | 1.0.0
track_profile_2_web | 1.3
pgRoutingLayer | 3.0.2
mmqgis | 2021.9.10
GamepadNavigation | 1.0.5
qgis-maptiler-plugin | 3.2
Qgis2threejs | 2.7.1
kart | 1.0.10
LAStools | 1.4
zoom_level | 0.1
profiletool | 4.2.5
cartogram3 | 3.1.5
Mergin | 2023.1
koordinates | 1.0.3
qgis2web | 3.16.0
processing | 2.12.99
otbprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
FYI: https://lists.osgeo.org/pipermail/qgis-developer/2023-April/065773.html

**Comment by DelazJ** [comment]
Hi @mapperfr Same as #33079?

**Comment by mapperfr** [comment]
> FYI: https://lists.osgeo.org/pipermail/qgis-developer/2023-April/065773.html

Yes I've seen it this morning, thanks for the notice @nicogodet! Two things though:
- Drag and drop works with QGIS on my system (Ubuntu 23.04 under Wayland + Gnome 44), I just tried with some random GRB file + a GPKG, they both properly load;
- There are some glitches indeed with the GUI, but nothing critical until now.

**Comment by mapperfr** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/33079

**Comment by Ahmed0Ebrahime** [comment]
I have linux manjaro running KDE , and global theme set to dark breathe, Qgis is based on QT5 library so first you have to setup **QT5 setting** using your package manager.

 1. open terminal.
 2. i use pacman so i typed `sudo pacman -S qt5ct`

3. after installation is done, open `enviroment` file from the following  directory `/etc/`
4. add the following line `QT_QPA_PLATFORMTHEME=qt5ct`
5. save the file and logout and login again.
6. open `Qt5 Configuration Tool` from your application launcher.
7. from **Appearance** tab select **Fusion** from style: and set **Color scheme:** to Default.
8. from **Icon Theme** tab select your light theme icon category.
9. open qgis and go to **Setting-> General** and set **Style:** to **Fusion** or **qt5ct-style**.
10. restart your Qgis program.
