### ISSUE TITLE
editingStopped event not emitted after saving QGSVectorlayer changes pyqgis

### ISSUE THREAD

**Issue by pvarsanyi** [qgis/QGIS#52933]
### What is the bug or the crash?

editingStopped event not emitted after saving QGSVectorlayer changes

### Steps to reproduce the issue

When using my script developed on a previous version the editingStopped event emission is not working. 

def editStopped():
           print("Editing Stopped")

 mem_layer = QgsVectorLayer("Polygon?crs=EPSG:54032","Edit "+featureTypeLabel+" " + sectionname+ " id:" + str(sectionid) , "memory")
    

mem_layer.editingStopped.connect (editStopped);    

### Versions

QGIS version
3.28.5-Firenze
QGIS code revision
50adba36f2
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by YoannQDQ** [comment]
Could you describe what you did after connecting the signal?

**Comment by pvarsanyi** [comment]
I do various PostgresDB calls to save the vector data but even if I do a simple print in the connected it function it does not work.
