### ISSUE TITLE
Scale dropdown displaying wrongly

### ISSUE THREAD

**Issue by sarahhouben89** [qgis/QGIS#52934]
### What is the bug or the crash?

Scale dropdown is not displaying properly on QGIS window

### Steps to reproduce the issue

Shut down and re-open but still there

### Versions

3.30.1.  (on MAC)

![Screenshot 2023-04-28 at 17 34 14](https://user-images.githubusercontent.com/114160212/235191284-b568e0e0-ea4d-4adf-8658-b91dfe63c1d9.png)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by sarahhouben89** [comment]
![Screenshot 2023-04-28 at 17 36 08](https://user-images.githubusercontent.com/114160212/235191835-c9b08b42-ec99-4e2a-9f9a-ab69704dfeff.png)

QGIS also crashed (already 2 times) as I try to click on the scale arrow to modify

**Comment by nicogodet** [comment]
Will be fixed in next release.
