### ISSUE TITLE
PYTHON CRASH

### ISSUE THREAD

**Issue by sgalow** [qgis/QGIS#52955]
### What is the bug or the crash?

Python does not work on windows 11 laptop .

qgis installs ok , but plugins that need pytho have crashed 

### Steps to reproduce the issue

osmdownloader plugin 

### Versions

3.30.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
What's the error ?

But if it only happens with this plugin, consider reporting the issue on https://github.com/lcoandrade/OSMDownloader/issues
