### ISSUE TITLE
Symbol Color expression correctly colors objects but does not color the legend correctly

### ISSUE THREAD

**Issue by cduffett** [qgis/QGIS#52950]
### What is the bug or the crash?

I am using an RGB expression to color shapefiles, and the expression works correctly but it does not update the symbols on the legend to match

### Steps to reproduce the issue

Categorized symbols, then click on the symbol fill, then use the expression to color based on RGB attributes of the layer. It will color everything correctly, but fails to update the legend. 

### Versions

Version 3.10.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
> Version 3.10.9

This version reached its end of life a long time ago.
Please upgrade to 3.28 or 3.30 and retry.

**Comment by ArendjanvdNeut** [comment]
Just tested it in version 3.32.1 and it is also accurring there: If you set the stroke color with the @symbol_color with the expression editor it works fine in the map. But the legend, and also the GUI is not updated. 

Reproducing is simple: create a style with a simple fill symbol and a color ramp. Set the stroke color with an  expression (choose edit in the 'expression' menu, and add the value @symbol_color. Works perfectly in the map, but not in the legend and the GUI.
