### ISSUE TITLE
Merge selected features p

### ISSUE THREAD

**Issue by albertograva** [qgis/QGIS#52985]
### What is the bug or the crash?

Hi!
this malfunction that I have detected does not actually lead to a QGIS crash.
It causes incorrect operation using the "Merge selected features" button (from advance digitizing" toolbar).
When I try to merge and save layer edits QGIS gives me back an error, but if i use "undo" the smaller (or sometimesethe bigger one) d of the merged feature reappears, then if I delete it and save layer edits it works.

I notice this problem trying to merge big areas to small areas (>1 sqm), but it happens also with bigger features.

I've registered a video to explain the problem and I enclose an example file.

### Steps to reproduce the issue

1. select 2 features
2. merge ("Merge selected features")
3. save layer edit >>>> error
4. undo
5. select the feature the re-appears and delete it
6. save layer edit >>>> it works
![save_layer_edit](https://user-images.githubusercontent.com/47315786/235873227-8d0e70da-07f9-4b72-98c3-31fbb7f91d8a.gif)
[test.zip](https://github.com/qgis/QGIS/files/11380983/test.zip)

### Versions

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code revision | 447e8d717a
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
dimensioning | 0.2
shapetools | 3.4.11
SpreadsheetLayers | 2.1.0
multiqml | 0.6.0
qfieldsync | v4.4.9
mmqgis | 2021.9.10
AutomaticBackup-master | 1.0
QuickMultiAttributeEdit3 | version 3.0.3
quick_map_services | 0.19.33
kmltools | 3.1.28
geometric_attributes | 0.3
ProcessX | 1.5
qgis_resource_sharing | 1.0.0
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
[447e8d717a](https://github.com/qgis/QGIS/commit/447e8d717a)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
dimensioning
0.2
shapetools
3.4.11
SpreadsheetLayers
2.1.0
multiqml
0.6.0
qfieldsync
v4.4.9
mmqgis
2021.9.10
AutomaticBackup-master
1.0
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.33
kmltools
3.1.28
geometric_attributes
0.3
ProcessX
1.5
qgis_resource_sharing
1.0.0
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@albertograva, it seems to me this issue has been already reported and allegedly fixed with PR https://github.com/qgis/QGIS/pull/52771.
Please check if the issue does occur using QGIS 3.30.2 or QGIS 3.28.6.

**Comment by albertograva** [comment]
@agiudiceandrea 
I've quickly tested and it seems that on 3.30.2 it is all working fine

**Comment by agiudiceandrea** [comment]
Thanks for reporting and for testing.
