### ISSUE TITLE
geo-referencing process stops after 06% on QGIS versions 3.28.5 and 3.30.1. (not 3.22.16)

### ISSUE THREAD

**Issue by wilcar** [qgis/QGIS#52989]
### What is the bug or the crash?

Hello, the geo-referencing process stops after 06% on versions 3.28.5 and 3.30.1. 
With an  older version (3.22.16), I don't have any issue.

![image](https://user-images.githubusercontent.com/18226229/235899909-511cf809-c8f3-427b-91b5-ff89b9c4bc9f.png)

### Steps to reproduce the issue

-

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.22.16-Białowieża | Révision du code | 6f08e4d7
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.6.2
Version de Proj | 9.1.1
Version de la base de données du registre EPSG | v10.076 (2022-08-31)
Version de GEOS | 3.11.1-CAPI-1.17.1
Version de SQLite | 3.39.4
Version de PDAL | 2.4.3
Version du client PostgreSQL | 14.3
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
batch_hillshader-master | 2.4.3
BezierEditing | version 1.3.4
cartogram3 | 3.0.4
clipper | 1.0
clusterpoints | 5.1
geotuileur | 1.0.0
mmqgis | 2021.9.10
nominatim | 1.4.5
OSMDownloader | 1.0.3
qgis_points2one | 0.3.1
qgis_resource_sharing | 1.0.0
QuickOSM | 2.0.1
quick_map_services | 0.19.29
SpreadsheetLayers | 2.1.0-alpha1
SRTM-Downloader | 3.1.17
thematic | 0.2.32
vector_tiles_reader | 3.2.2
db_manager | 0.1.20
MetaSearch | 0.3.5
processing | 2.12.99

</body></html>Version de QGIS
3.22.16-Białowieża
Révision du code
[6f08e4d7](https://github.com/qgis/QGIS/commit/6f08e4d7)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
14.3
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
batch_hillshader-master
2.4.3
BezierEditing
version 1.3.4
cartogram3
3.0.4
clipper
1.0
clusterpoints
5.1
geotuileur
1.0.0
mmqgis
2021.9.10
nominatim
1.4.5
OSMDownloader
1.0.3
qgis_points2one
0.3.1
qgis_resource_sharing
1.0.0
QuickOSM
2.0.1
quick_map_services
0.19.29
SpreadsheetLayers
2.1.0-alpha1
SRTM-Downloader
3.1.17
thematic
0.2.32
vector_tiles_reader
3.2.2
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

-

**Comment by alexbruy** [comment]
Is this still an issue? If yes, please provide test dataset and exact steps to reproduce the issue.
