### ISSUE TITLE
validity check make false detection of line intersection

### ISSUE THREAD

**Issue by malien24** [qgis/QGIS#52991]
### What is the bug or the crash?

Issue appears when i importing data from json file(contour lines of the terrain relief ). So I received some geometry checking error, immediately after paste data to my layer (with geometry checker turned on), i can delete invalid objects, but if I move  all pasted objects, errors appears in some other objects.
It always intersection on start/end point, I have checked, vertex coordinates of start and end point match exactly to the 30..th decimal place(further only zeros).
Another question, why if I load json with only 3 decimal digits coordinates, if I take a look on vertex coordinates in QGIS, there are a lot more digits after point. I expected zeros after 3rd decimal.

### Steps to reproduce the issue

In layer with geometry type "line" turn on option "IsValid" in layer properties "digitizing". After that paste data to that layer. Some times it apeare after move feature in another place.

File with features which make this error attached.

### Versions

qgis 3.28.5, 3.28.6, 3.30.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

geojson file with features, that make false detection of geometry errors. EPSG 5564
[line-error.zip](https://github.com/qgis/QGIS/files/11383776/line-error.zip)

**Comment by malien24** [comment]
How to add lable "Geometry checker" to this issue?

**Comment by alexbruy** [comment]
Attached files does not contain any vector data, it is a QGIS metadata file.

**Comment by malien24** [comment]
> Attached files does not contain any vector data, it is a QGIS metadata file.
sorry, that file may contain vector data

[test.zip](https://github.com/qgis/QGIS/files/13532684/test.zip)

**Comment by malien24** [comment]
> Can't reproduce with the latest master ([0d94f29](https://github.com/qgis/QGIS/commit/0d94f29250b132fb31bbe1cdc0d502065809a20c))
in QGIS 3.28.13 I have that error. Maybe error in ltr version only?

**Comment by alexbruy** [comment]
Also can't reproduce with 2.28.13 (GEOS 3.12.1). Here is what I did:

- loaded in QGIS geojson from the provided test dataset
- started editing on a layer
- enabled "IsValid" in the layer properties
- selected all features and copied them
- pasted features multiple times
- moved some of the features multiple times
- pasted new features again

**Comment by malien24** [comment]
> Also can't reproduce with 2.28.13 (GEOS 3.12.1). Here is what I did:
> 
>     * loaded in QGIS geojson from the provided test dataset
> 
>     * started editing on a layer
> 
>     * enabled "IsValid" in the layer properties
> 
>     * selected all features and copied them
> 
>     * pasted features multiple times
> 
>     * moved some of the features multiple times
> 
>     * pasted new features again


May be you try 3.28.13? 
I test in 3.28.13 and when I load geojson select all features and copy them, then I create temporary scratch layer whith line geometry type, enable edite mode, enable isvalid and paste features. And after that I have error intersection of first and last vertex of line.

**Comment by malien24** [comment]
pleese try make new scratch layer in epsg 4326
