### ISSUE TITLE
Field calcualor in QGIS 

### ISSUE THREAD

**Issue by ZeinabJ21** [qgis/QGIS#53013]
### What is the bug or the crash?

Why does the Field Calculator expression using field name, work in the Attribute table but not in the Model Builder in QGIS?

### Steps to reproduce the issue

(https://user-images.githubusercontent.com/132601519/236289413-c893fd1c-55e8-4f51-a2df-a701bfb4c6c4.JPG)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.16.5-Hannover | QGIS code revision | 58ba7c1ed6
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | pluginbuilder3; Submission; db_manager; MetaSearch; processing

</body></html>QGIS version
3.16.5-Hannover
QGIS code revision
[58ba7c1ed6](https://github.com/qgis/QGIS/commit/58ba7c1ed6)
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
pluginbuilder3; 
Submission; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by baswein** [comment]
I believe this is because you are using an algorithm output as your input to the field calculator in the Model. Because that layer hasn't been created yet QGIS doesn't know what the field values would be and so can't give you a preview.

**Comment by roya0045** [comment]
Don't rely on the preview, as the layer doesn't exist it can't calculate it. The algorythm will still work. This isn't a bug or something that can be improved.
