### ISSUE TITLE
Hidden vector layers in GeoPDF show as grey features in some PDF viewers

### ISSUE THREAD

**Issue by mattcen** [qgis/QGIS#53024]
### What is the bug or the crash?

When exporting a layout as a GeoPDF and setting a vector layer's default visibility to "hidden", some PDF viewers (e.g. Apple's Preview.app) display the layer's features as grey features in the PDF. The PDF looks fine in Adobe Acrobat, however.

### Steps to reproduce the issue

1. Create a new QGIS project
2. Type 'world' in the coordinate text field to get a world map layer
3. Create a new scratch "Point" layer, with no custom fields
4. Copy the following GeoJSON and paste it as features into the new layer:
```json
{ "type": "FeatureCollection",
"name": "foo",
"features": [
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ -95, 37 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ 47, 55 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ 63, 2 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ -40, -13 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ -23, 66 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ -23, 34 ] } },
{ "type": "Feature", "geometry": { "type": "Point", "coordinates": [ -2, -8 ] } }
] }
```
5. Create a new print layout with this map as the only item on the page
6. Export the print layout to PDF, unchecking the "Initially visible" checkbox for the new scratch layer: 
<img width="601" alt="image" src="https://user-images.githubusercontent.com/4273659/236595132-2aaf6483-cc96-4450-b6b5-6eee384571b2.png">
7. Open the PDF in Preview.app in MacOS, and see the grey artefacts:
<img width="387" alt="image" src="https://user-images.githubusercontent.com/4273659/236595217-2190d209-e2af-489e-8a06-9cf594edb690.png">
8. Open the PDF in Adobe Acrobat and see that it displays correctly (no artefacts, but you can enable the hidden layer and it displays as expected)

Note this does *not* occur if you *also* uncheck the "Include Attributes" checkbox for the scratch layer in the PDF export dialogue box.

### Versions

QGIS version | 3.30.0-'s-Hertogenbosch | QGIS code revision | f186b8efe0
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.3
Preview.app version | Version 11.0 (1044.2)
  |   |   |  
Active Python plugins
QuickOSM | 2.2.2
kmltools | 3.1.29
profiletool | 4.2.5
vector_tiles_reader | 3.2.2
quick_map_services | 0.19.33
MagneticDeclination | 2.3.1
SRTM-Downloader | 3.1.17
qgis2web | 3.16.0
latlontools | 3.6.10
qgsAzimuth | 0.9.15
qgis-maptiler-plugin | 3.2
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I've attached a sample PDF and QGIS project (as a zipped GeoPackage) below:
[simple_map.pdf](https://github.com/qgis/QGIS/files/11411125/simple_map.pdf)
[simple_map.zip](https://github.com/qgis/QGIS/files/11411127/simple_map.zip)

**Comment by nyalldawson** [comment]
Isn't this a bug in those PDF readers?

**Comment by mattcen** [comment]
I don't know; I don't know enough about how PDF works internally to know how to test that, nor how to create a layered PDF in any other tool as a basis for comparison.

What I do know is that if I uncheck "Include Attributes" for the problem layer, the problem goes away, and if I then duplicate that layer and set the duplicate to have no symbology, and have that layer "visible" in the PDF, I get the behavior I want (a layer which is hidden by default, but who's geospatial data is still included in the PDF), but it's an ugly hack, not least because then the PDF lists a layer which seems to do nothing.

**Comment by mattcen** [comment]
I'm not sure what additional feedback I can offer here. I don't have enough experience in this space. Can anybody point me at other free/open-source tools for generating PDFs with Optional Content Groups/Layers so I can test this further, or help me find what library QGIS is using for this so I can dig into it?
