### ISSUE TITLE
Python call of `QgsVectorLayer().type().name` returns `Vector` in QGIS 3.30.x, but `VectorLayer` in previous versions

### ISSUE THREAD

**Issue by suricactus** [qgis/QGIS#53023]
### What is the bug or the crash?

It feels like a regression to me.

I guess the change was part of this commit:
https://github.com/qgis/QGIS/commit/1142e8fface025414c6c35979987e3dcc334f435

https://github.com/qgis/QGIS/blob/master/src/core/qgis.h#LL116C14-L116C41

Not sure if it slipped through reviews or it was intended change?

### Steps to reproduce the issue

1. Open the QGIS python console
2. Execute `QgsVectorLayer().type().name`

### Versions

QGIS 3.30.x

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
I don't think this is a bug we should handle -- we've been changing enum names forever but leaving compatibility code in place to ensure that the numeric representation of these don't change. To me this is a wontfix.

**Comment by nyalldawson** [comment]
Closing as wontfix
