### ISSUE TITLE
in qgsvectorlayereditbuffer.cpp oldFields varibles is right ?

### ISSUE THREAD

**Issue by YuBoTao123** [qgis/QGIS#53038]
### What is the bug or the crash?

in qgsvectorlayereditbuffer.cpp line 387:    QgsFields oldFields = L->fields(); 

i think it should be QgsFields oldFields = provider->fields();

it is used to constract old fields and new fields, but now it's same ?

### Steps to reproduce the issue

![image](https://user-images.githubusercontent.com/49198890/236790886-f6d50825-2db6-4ed9-85ae-052f5383654a.png)

### Versions

master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Maybe @domi4484 knows.

**Comment by YuBoTao123** [comment]
OK, I misunderstand this variable. I thought this variable used to compare the difference between old and new changes. Because I try to add some log to record my operation in qgis. I will close this issue, thanks for your apply!
