### ISSUE TITLE
DXF Export

### ISSUE THREAD

**Issue by Amphibitus** [qgis/QGIS#53042]
### What is the bug or the crash?

After starting DXF Export from QGIS crashed after some second. 
It seemed, that there is a Problem with the labels.  The result DXF file (after WHERST)  
include every Informations but no Labels. 

### Steps to reproduce the issue

![grafik](https://user-images.githubusercontent.com/7237786/236842719-2c2e9a6e-29b0-494d-b293-70bc9df9d016.png)

### Versions

QGIS 3.20.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Tried to export project with labeled layer and there is no crash. Can you provide test data and exact steps to reproduce?
