### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by cedric1960** [qgis/QGIS#53059]
### What is the issue about the documentation?

Good morning
I have been trying to install a plugin (spatial analysis toolbox) but an error keeps coming up each time as shown on the the picture attached below.
So please how can I solve this problem???
![ERROR](https://github.com/qgis/QGIS/assets/133085835/846c610c-cede-4023-ad7c-42d997b57519)

**Comment by nicogodet** [comment]
As explicitly said when creating a new issue, plugin related issues should be reported here.
![image](https://github.com/qgis/QGIS/assets/39594821/2dd4cfc1-6e37-45c4-855d-8a898628edf3)

You need to install `geopandas`.

Not a QGIS issue, closing.
