### ISSUE TITLE
Lock Layers not working properly

### ISSUE THREAD

**Issue by Davido-star** [qgis/QGIS#53078]
### What is the bug or the crash?

The lock function for the map in layout mode is not working. Changes to layer visiblity in the QGIS main window are still showing up in the layout view.

### Steps to reproduce the issue

Have tried with multiple map files, and computers.

Go to layout mode
Add map
Lock map (Item list on right hand side)
Make changes to visible layers in QGIS main window
Refresh layout view to see that locked map has changed and has not actually been locked

Example: I'm working with layer groups to have different map frames in the same layout. When visibility or projection is changed for one layer group, that change is applied to the "Locked Layers" in the layout. 

The lock I'm referencing is in the item properties menu. Not the items menu.   

### Versions

QGIS 3.28.6 LTR 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
"Lock map (Item list on right hand side)" do you mean "Lock Layers"? 

![image](https://github.com/qgis/QGIS/assets/142164/487640e6-95a9-40a8-84a7-2f108e5ffbd3)

Can you attach a sample project and data to reproduce the issue?

**Comment by MattBeamish** [comment]
I am using 3.28.9-Firenze, and I am experiencing this same issue. My maps are not locking when I lock them. I'm a new QGIS user but a long time user of ArcMap. I'm very unfamiliar with GitHub, but I'll do my best to report this behaviour.  


</body></html>

**Comment by elpaso** [comment]
> I am using 3.28.9-Firenze, and I am experiencing this same issue. My maps are not locking when I lock them. I'm a new QGIS user but a long time user of ArcMap. I'm very unfamiliar with GitHub, but I'll do my best to report this behaviour.

Can you please attach a sample project?

**Comment by MattBeamish** [comment]
I am now trying to use a new profile - I hadn't seen that tip before I got
most of the way through submitting a bug report
thanks
Matt
