### ISSUE TITLE
Error reproducing shp layer data after saving and closing the program

### ISSUE THREAD

**Issue by Polina1804** [qgis/QGIS#53085]
### What is the bug or the crash?

The problem is that after working with layers, saving projects and exiting the application, and then re-entering it, the application partially does not display the objects that were added earlier. But the information about the disappeared objects is stored in the attributes. After performing the actions to fix the geometry of the layer, the application claims that the source of the data has not been found, although this layer is present on the device and in the application itself.

### Steps to reproduce the issue

![paRXBSeWUCo](https://github.com/qgis/QGIS/assets/133322864/4e4248a6-83b5-4d2a-a064-3059e1f20ae8)
![HIX2axpM3Gs](https://github.com/qgis/QGIS/assets/133322864/4aac0fc9-24fd-42bb-b0c6-29ef637d44ab)

### Versions

Версия QGIS
3.30.1-'s-Hertogenbosch
Ревизия
9035a01e
Версия Qt
5.15.3
Версия Python
3.9.5
Версия GDAL/OGR
3.6.3
Версия PROJ
9.2.0
Версия базы данных реестра EPSG
v10.082 (2023-02-06)
Версия GEOS
3.11.2-CAPI-1.17.2
Версия SQLite
3.41.1
Версия PDAL
2.5.2
Версия PostgreSQL
unknown
Версия SpatiaLite
5.0.1
Версия QWT
6.1.6
Версия QScintilla2
2.13.1
Версия ОС
Windows 10 Version 2009

Включенные модули Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

### Additional context

The problem is that after working with layers, saving projects and exiting the application, and then re-entering it, the application partially does not display the objects that were added earlier. But the information about the disappeared objects is stored in the attributes. After performing the actions to fix the geometry of the layer, the application claims that the source of the data has not been found, although this layer is present on the device and in the application itself

**Comment by agiudiceandrea** [comment]
@Polina1804, please provide the original layer and project and the exact steps in order for the issue to occur.
