### ISSUE TITLE
Graphic scale

### ISSUE THREAD

**Issue by xdanlima** [qgis/QGIS#53089]
### What is the bug or the crash?

Graphic scale

Good morning.

My graphic scale is not respecting the standard measurements. On a map with a numerical scale of 1:6000 the graphic scale would have to be represented 0____60____120___180___240m where the interval would have to be 1cm but it is giving 0.85cm. Does anyone know how to resolve?

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/133378014/48e27358-7621-4f1d-9544-06bd123bc20d)

### Versions

Versão do QGIS
3.26.1-Buenos Aires
Código da versão do QGIS
b609df9ed4d
Versão Qt
5.15.3
Versão do Python
3.9.5
Versão GDAL/OGR
3.5.1
Versão PROJ
9.0.1
Versão da base de dados do registro EPSG
v10.064 (2022-05-19)
Versão GEOS
3.10.3-CAPI-1.16.1
Versão SQLite
3.38.1
Versão PDAL
2.3.0
Versão cliente PostgreSQL
unknown
Versão SpatiaLite
5.0.1
Versão QWT
6.1.6
Versão QScintilla2
2.13.1
Versão OS
Windows 10 Version 2009

Plugins Python ativos
AzimuthDistanceCalculator
2.0.2
FreehandRasterGeoreferencer
0.8.3
ibamaprocessing
1.6
inde
1.1
lftools
1.9.4
mapflow
1.6.3
planet_explorer
2.2.0
PLUGIN
1.2.2
profiletool
4.2.2
qgsAzimuth
0.9.15
qlyrx
0.3.3
quick_map_services
0.19.29
scpplugin
2.0
slyr_community
4.0.6
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by baswein** [comment]
I'm not sure if this is the problem you are encountering but if you are using a CRS such as 3857 that is for a large area the length measurements will be off. Therefor the scale bar will also be off. Try using a CRS that is local if you aren't already.
