### ISSUE TITLE
Oversized strings in the GUI

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#53097]
### What is the bug or the crash?

I find text size of Recent projects and other news widgets quite bigger than the toolbars/menus items'. Afaict I changed nothing recently (Qt default 10 pt). Maybe related to recent hidpi commits?

![image](https://github.com/qgis/QGIS/assets/7983394/ebc2072e-dc2c-44d7-ae10-d73a8aa6c3a0)

### Steps to reproduce the issue

I simply launched QGIS

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code revision | 367b8ba332
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PostgreSQL client version | 13.11 (Debian 13.11-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is how it's supposed to look -- see below screenshot taken on a low-dpi screen:

![image](https://github.com/qgis/QGIS/assets/1829991/e0d7593d-b151-485b-967b-b5d91d155885)

**Comment by DelazJ** [comment]
Hummm... Sorry if I wasn't clear, I'm also on a low-dpi screen.
Watching the two screenshots, I have the feeling that the text  "A message of peace from..." is way bigger (obviously more readable) than the Processing categories for example in my screenshot. In yours, they look almost the same. Maybe it is a matter of font, or... my eyes(?!)
Feel free to close if my eyes are most likely the ones to blame, or not something we can fix.

**Comment by nyalldawson** [comment]
Please retest on a newer master version -- this should be fixed
