### ISSUE TITLE
Atlas stops incrementing

### ISSUE THREAD

**Issue by tsykes** [qgis/QGIS#53128]
### What is the bug or the crash?

I created an atlas from a layer sourced from PostGIS. There were several hundred images I wanted to export. After completing the export, only about 2/3 of the images were there. I discovered that at some point QGIS would stop incrementing the index and just keep recreating the same image multiple times. I thought this might be something to do with my data or some data type issue so I regenerated the keys as both strings and integers. For the images that it wouldn't do previously, it continued to just reproduce 1 image multiple times. I upgraded QGIS from 3.28.2 to 3.28.6 and got the same behavior. I then found an older QGIS install with version 3.16.0 and the same data set/query generated the images without any error. I could not discover anything special about the records where the Atlas wouldn't increment.  

### Steps to reproduce the issue

1. Generate an Atlas sourced from PostGIS with hundreds of entries
2. Export the Atlas to images 
3. Not all the images get created 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.6-Firenze | QGIS code revision | 868c9fa03b
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.2
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 1909
  |   |   |  
Active Python plugins
d3datavis | 3.0.3
GeoCoding | 2.19
google_maps_geocoder | 0.0.3
GroupStats | 2.2.7
pg_raster_import | 3.2.0
qgis2web | 3.16.0
qgis_resource_sharing | 1.0.0
QuickOSM | 2.2.2
quick_map_services | 0.19.33
rasterstats | 0.4.3
searchlayers | 3.0.12
SpreadsheetLayers | 2.1.0
valuetool | 3.0.15
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99
DataPlotly | 4.0.1

</body></html>QGIS version
3.28.6-Firenze
QGIS code revision
[868c9fa03b](https://github.com/qgis/QGIS/commit/868c9fa03b)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1909

Active Python plugins
d3datavis
3.0.3
GeoCoding
2.19
google_maps_geocoder
0.0.3
GroupStats
2.2.7
pg_raster_import
3.2.0
qgis2web
3.16.0
qgis_resource_sharing
1.0.0
QuickOSM
2.2.2
quick_map_services
0.19.33
rasterstats
0.4.3
searchlayers
3.0.12
SpreadsheetLayers
2.1.0
valuetool
3.0.15
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
DataPlotly
4.0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
What expression did you used for output names ?

![image](https://github.com/qgis/QGIS/assets/39594821/a2740b3e-4384-4be8-9e2d-36e429eb0d2f)

**Comment by tsykes** [comment]
The expression is `"recordid_text" || '_Google'`  I had played around with the key converting it between data types to see if something odd was happening. The recordid field is a unique key. 
![image](https://github.com/qgis/QGIS/assets/10634558/cc1e6909-95ac-47cb-9abd-7250d2889222)
