### ISSUE TITLE
QgsCheckableComboBox in custom ui form doesn't write selected values into field

### ISSUE THREAD

**Issue by d-lombardi-a** [qgis/QGIS#53126]
### What is the bug or the crash?

QgsCheckableComboBox in custom ui form seems not to work properly. I have a custom .ui form with several QgsCheckableComboBox widget in it. I use this custom form to edit feature's attribute within a qgis project. The QgsCheckableComboBox inside the form shows choices correctly but values, when flagged, do not update the binded field that remains empty. Follow below steps to reproduce.

### Steps to reproduce the issue

1. Unzip attached [test.zip](https://github.com/qgis/QGIS/files/11488384/test.zip) file.
2. Open test.qgz file-->Qgis project opens
3. Start editing test layer
4. Insert a new feature--> Attribute form  test.ui opens
5. Make values selection in comboboxes.
6. Click OK button on form.
7. Save edits (optional)
8. Open test layer's attribute table --> No values have been set
9. Edit fields in place (in table view) --> Values are correctly set

The problem seem related only to editing attribute table in form view

### Versions

Tested with  3.22.7-Białowieża 3.22.8-Białowieża and 3.30.2-'s-Hertogenbosch

Versione di QGIS
3.22.7-Białowieża
Revisione codice QGIS
5a65627a
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.4.3
Versione PROJ
9.0.0
Versione database del Registro EPSG
v10.054 (2022-02-13)
Versione GEOS
3.10.2-CAPI-1.16.0
Versione SQLite
3.38.1
Versione PDAL
2.3.0
Versione client PostgreSQL
13.0
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
imposta_gruppo_comuni
0.1
powerpan
2.0
quick_map_services
0.19.33
send2google_earth
0.3.1
send2World_Imagery_Wayback
0.3.1
SentinelHub
2.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

Versione di QGIS
3.30.2-'s-Hertogenbosch
Revisione codice QGIS
0992b533
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.6.4
Versione PROJ
9.2.0
Versione database del Registro EPSG
v10.082 (2023-02-06)
Versione GEOS
3.11.2-CAPI-1.17.2
Versione SQLite
3.41.1
Versione PDAL
2.5.2
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
imposta_gruppo_comuni
0.1
powerpan
2.0
quick_map_services
0.19.33
send2google_earth
0.3.1
send2World_Imagery_Wayback
0.3.1
SentinelHub
2.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
I'm afraid you are doing something wrong. When form open both comboboxes are empty and does not allow to select any value, they are not linked to the data tables.
![image](https://github.com/qgis/QGIS/assets/776954/c2449900-37e3-4d8f-867f-caa45a65479a)
In the layer properties both fields configured to use Value Relation widget.

**Comment by d-lombardi-a** [comment]
Thanks for your reply,
I double checked the described procedure to reproduce the issue using the test.zip provided, I confirm that it correctly highlights the bug described. Don't know why  it didn't work for You. The data tables referenced by comboboxes through the Value Relation widget are named dict_multi_sring and dict_multi_int and you should see them in the project's TOC.
Please let me know if you are able to reproduce the issue eventually.
![image](https://github.com/qgis/QGIS/assets/53909185/1d9f82d1-dd42-4c12-bbb1-a20847ce6e44)

**Comment by d-lombardi-a** [comment]
Feedback given in https://github.com/qgis/QGIS/issues/53126#issuecomment-1794396939
Thanks
[https://opengraph.githubassets.com/770fb89a1ac6b69937ac9ff499854387ff1c8ecf2e3f513f1ffbab111461b98d/qgis/QGIS/issues/53126]<https://github.com/qgis/QGIS/issues/53126#issuecomment-1794396939>
QgsCheckableComboBox in custom ui form doesn't write selected values into field · Issue #53126 · qgis/QGIS<https://github.com/qgis/QGIS/issues/53126#issuecomment-1794396939>
What is the bug or the crash? QgsCheckableComboBox in custom ui form seems not to work properly. I have a custom .ui form with several QgsCheckableComboBox widget in it. I use this custom form to e...
github.com

________________________________
Da: Alexander Bruy ***@***.***>
Inviato: domenica 5 novembre 2023 15:22
A: qgis/QGIS ***@***.***>
Cc: LOMBARDI DARIO ***@***.***>; Author ***@***.***>
Oggetto: Re: [qgis/QGIS] QgsCheckableComboBox in custom ui form doesn't write selected values into field (Issue #53126)


I'm afraid you are doing something wrong. When form open both comboboxes are empty and does not allow to select any value, they are not linked to the data tables.
[image]<https://user-images.githubusercontent.com/776954/280532668-c2449900-37e3-4d8f-867f-caa45a65479a.png>
In the layer properties both fields configured to use Value Relation widget.

**Comment by alexbruy** [comment]
As you can see it does not work, as I stated in https://github.com/qgis/QGIS/issues/53126#issuecomment-1793751625
![Peek 2023-11-26 14-21](https://github.com/qgis/QGIS/assets/776954/ca6c54e9-56da-4b82-86e1-7f7e3cbf23da)

Also note that checkable combobox is a custom widget and is not handled by attribute form, you have connect to the correct signals and handle them in the form code.
