### ISSUE TITLE
crash on starting project

### ISSUE THREAD

**Issue by pecard** [qgis/QGIS#53133]
### What is the bug or the crash?

Simply crash on project start with no other action. 

## User Feedback

python error on start, no other action taken but starting the project with no internet connection

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00000b88 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsRasterLayerRenderer::QgsRasterLayerRenderer :
QgsRasterLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::startPrivate :
QgsMapCanvas::refreshMap :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

simply start QGIS and try to open the very same project closed last day.

### Versions

Versão do QGIS
3.28.4-Firenze
Revisão do código do QGIS
fd0fb72ab3
Qt version
5.15.3
Versão do Python
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
Versão PDAL
2.4.3
Versão do cliente PostgreSQL
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
Versão QScintilla2
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.6
latlontools
3.6.9
quick_map_services
0.19.33
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Hi @pecard, does the crash occur only opening a particular QGIS project or every QGIS project? If the former, could you share such project? Does it occur also when the internet connection is up and working? Does it occur using a new QGIS user profile?
