### ISSUE TITLE
[pyQGIS] QgsSingleBandPseudoColorRendererhas wrong legend in layer view

### ISSUE THREAD

**Issue by moovida** [qgis/QGIS#53131]
### What is the bug or the crash?

The legend of a pyQGIS set colortable for a single band raster turns out wrong.

### Steps to reproduce the issue

The below code uses the raster from: https://github.com/qgis/QGIS/issues/53060#issuecomment-1541499097

Running the below snippet:

```
dtm = "/path_to/dtm_flanginec.asc"
dtmLayer = QgsRasterLayer(dtm, "dtm")
minV = 800
maxV = 2200

crsh = QgsColorRampShader()
crsh.setColorRampType(QgsColorRampShader.Interpolated)
lst = [ 
    QgsColorRampShader.ColorRampItem(minV, QColor(255,0,0)),
    QgsColorRampShader.ColorRampItem(minV + (maxV-minV)/2, QColor(0,255,0)),
    QgsColorRampShader.ColorRampItem(maxV, QColor(0,0,255)) 
]
crsh.setColorRampItemList(lst)
shader = QgsRasterShader()
shader.setRasterShaderFunction(crsh)

renderer = QgsSingleBandPseudoColorRenderer(dtmLayer.dataProvider(), 1, shader)
dtmLayer.setRenderer(renderer)

QgsProject.instance().addMapLayer(dtmLayer)
```

creates the right colortable and the resulting raster looks good.

But the legend in the layer view does not. It seems to be locked between 0 and 255:

![image](https://github.com/qgis/QGIS/assets/390250/91d2316b-c57a-4f41-9191-9763583105e1)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code revision | 0992b53397
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.30.2-'s-Hertogenbosch
QGIS code revision
[0992b53397](https://github.com/qgis/QGIS/commit/0992b53397)
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
```python
# Replace
crsh = QgsColorRampShader()
crsh.setColorRampType(QgsColorRampShader.Interpolated)

# With 
crsh = QgsColorRampShader(
    minimumValue=minV,
    maximumValue=maxV,
    type=QgsColorRampShader.Interpolated  # Not really needed as it is default value
)
```
![image](https://github.com/qgis/QGIS/assets/39594821/b27e9b62-460d-438f-9fe7-128c83d94b68)

It could be worth asking these pyQGIS issues on mailing list first...

**Comment by nicogodet** [comment]
But I'm not sure your method is the correct one as symbology is not correctly set in layer properties or Style panel
![image](https://github.com/qgis/QGIS/assets/39594821/676f6e7f-2be6-4ddc-85b6-599c81858df7)
