### ISSUE TITLE
How to change the font color of tooltips on qgis icons?

### ISSUE THREAD

**Issue by DadoooR3** [qgis/QGIS#53143]
### What is the bug or the crash?

Hello,

I just want to change the color of the font used for the basic tooltips (basic explanations given during the passage on the icons of QGIS)

Currently the font color is white and the tooltip background is light yellow... It's simply unreadable.

Why not use very dark blue instead of black which can be white for some installations?

In the doc, I can't find where are the explanations about the basic tooltips... I'm sorry.

Thanks for your help and have a nice day !
D.

![Capture d’écran du 2023-05-18 06-12-16](https://github.com/qgis/QGIS/assets/27968277/fec9430e-e3c4-47af-bb71-f232f779354e)

### Steps to reproduce the issue

Simply hover over the icons with the mouse...

### Versions

Installation Opensuse Tumbleweed

Version de QGIS | 3.30.2-'s-Hertogenbosch | Branche de code de QGIS | Release 3.30
-- | -- | -- | --
Version de Qt | 5.15.9
Version de Python | 3.10.10
Version de GDAL/OGR | 3.6.3
Version de Proj | 9.2.0
Version de la base de données du registre EPSG | v10.082 (2023-02-06)
Version de GEOS | 3.11.2-CAPI-1.17.2
Version de SQLite | 3.41.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.2.0
Version de QScintilla2 | 2.13.4
Version de l'OS | openSUSE Tumbleweed
  |   |   |  
Cette copie de QGIS dispose d'une sortie de débogage.
  |   |   |  
Extensions Python actives
profiletool | 4.2.4
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

3.30.2-'s-Hertogenbosch
Branche de code de QGIS
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Version de Qt  5.15.9
Version de Python 3.10.10
Version de GDAL/OGR   3.6.3
Version de Proj 9.2.0
Version de la base de données du registre EPSG v10.082 (2023-02-06)
Version de GEOS 3.11.2-CAPI-1.17.2
Version de SQLite 3.41.2
Version de PDAL 2.3.0
Version du client PostgreSQL unknown
Version de SpatiaLite 5.0.1
Version de QWT 6.2.0
Version de QScintilla2 2.13.4
Version de l'OS openSUSE Tumbleweed

Extensions Python actives
profiletool 4.2.4
MetaSearch 0.3.6
db_manager 0.1.20
grassprovider 2.12.99
processing 2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Tooltips styled according to your system theme, it is not related to QGIS.
![image](https://github.com/qgis/QGIS/assets/776954/18b9a16d-9a80-4d24-8fc5-ecfccd6f5fdb)

**Comment by promykPL** [comment]
Hi,
I've found a solution for this problem (which BTW occurred on my Linux installation after installing some plugins, so it's not a system-based problem from the beginning - first everything is OK and then apparently new plugins mess up some settings).
Solution is: go to >settings >options
then choose General tab on the left
and then change "interface style" (I'm translating from polish so the name might be a little bit different in English, that's my best guess) to some other for instance "gtk2" - my default was "Fusion".
Worked for me on Linux Mint with QGis 3.22.4-Białowieża long term release.

**Comment by Colins2** [comment]
Great solution, worked for me using qt5ct-style - medium blue background and white text.
