### ISSUE TITLE
Fonts change in Layout

### ISSUE THREAD

**Issue by jpuenteGSA** [qgis/QGIS#53145]
### What is the bug or the crash?

In QGIS version 3.28.6-Firenze, once and again the fonts from the text blocks change in the layouts. Not just the font tye but also te size, returning to MS Shell Dig2 size 10.

### Steps to reproduce the issue

1. create a new layou
2. Include a Label with  any text
3. change the font type to any other
4. save
5. close QGIS
6. open qgis
7. check the layout

### Versions

3.28.5 and 3.28.6 (at least)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Hi @jpuenteGSA, thanks for reporting the issue, anyway it seems to me the issue doesn't occur on my Windows system using neither QGIS 3.28.5 nor QGIS 3.28.6.
Could you please provide the info in the Help->About menu as requested in the issue report form? Could you please provide a sample project demonstrating the issue?

**Comment by jpuenteGSA** [comment]
Hi Andrea,

It doesn't happen every time. In any case I will upload a file as an example (the linked shapes will not be attached, but they are not affected, as it's just for the fixed texts in the layout).

Javier Puente Bushell

GEOCONTROL, S.A.

Enviado desde mi dispositivo móvil.

________________________________

**Comment by roya0045** [comment]
From my experience this is due to a change in either fonts and/or how the text display attributes are stored that break when opening a project with a new or older version. I don't think this is a bug if opening a newer project with and older version resets the text attribute to default.
