### ISSUE TITLE
Bad performance high cpu and strange log-messages

### ISSUE THREAD

**Issue by thetuxinator** [qgis/QGIS#53161]
### What is the bug or the crash?

For some projects we see a strange behaviour, we see a high CPU usage for much time (up to 30 secs) on the QGIS-Server running in a Container on either Baremetal or on a VM and for the slow requests we see the following in the logs but no additional helpfull message, we see this behaviour on 3.22 up to 3.28.6 on qgis-server on Ubuntu Jammy and Focal.

Logmessage:

 2023.05.19 10:51:42.377 -> Headers: {'Content-Type': 'image/png', 'Server': ' QGIS FCGI server - QGIS version 3.28.6-Firenze'}
May 19 10:51:42 fooserver1.example.net clog_qgis-dev[662]: 2023.05.19 10:51:42.387 -> Body: b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\r4\x00\x00\x07S\x08\x06\x00\x00\x00\xde\xbaW\x80\x00\x00\x00\tpHYs\x00\x00\r\xf3\x00\x00\r\xf3\x01/\xfd=\xfe\x00\x00 \x00IDATx\x9c\xec\xddwx\x14U\xf7\x07\xf0\xef\x99\x99\xdd\xf4F\x02H\x93\x16\xaa\x14\xb1PTT\x8ab\xc3\x8e\xbd`C\x11\x93l\x00\xc1\xfa\x8bX^\x15\x814\x04\xc5\xf2\xda\x1b\x96\xd7^(\x8a ]\x84\xd0{\x95\xd0\xd3\xdb\xee\xcc=\xbf?\x82 JI6\x93\x9d\x84\x9c\xcf\xf3\xf88[\xee\x9do\x12Mvg\xef\xb9\x07\xe0\xc46\xb0\x13\'u\x01\'v\xb2u\xce\xa3h\xc7c\xfa\x8c3\xbf\xb5\xc2\xf8\xe1\xd3+;v\x9e\x99u\xe9|o\xd6\x99\xd5\x91\xabR\xd8s.xXs\xa7c\x08!j0N\xd1\xc0I7\x96\x1f\'\xf6\x03\'5\xfc\xe7S~\xe6\x9f\x8d\xf9\xbe\xacG\xc0\x897\x81A\x01\xcfX\x93\xf1\xa8\x88Q\xbeO~\xbd\xd3|\xe3\xed\xbe\x9b\x93\xd3\xde\xff}\xd22\xa7#\xd5Z<\xa298\xe9{p\x82\x07<\xb2\x81\xd3q\xae\xe7W\x9ex\xc6\xfcl\xe7;\xde\xd9\xb7;\x9d\xa5&\x99\xe5]\xb2v\x8aw\xda\xba\xb1\xe67\xdb\xc1#\xecy\x8d\xc1\x89\x9d\xc0\x89S\xc1\x89\x93l\x99\xcf\x0e\x9c\xf8$xh+\xa7c\xfce~\xd9\x8a\x8e\xf3\xbdY\xf9\t\xe6\xfb?\x82\x93\x06\xd4\x84\xffG\xaa\x05\'\xd4O\xf7}g\xb6\xe0\x94\x9f\xc1\x0f\xb7\x06\xdf\x11{\xf8\xb1\x11q`\xcf\xf5\xe0Q\x8d+1_$8\xe9\x0ep\xd2E\xd5\x11W\x88Z\x8d=\xad\xc0I=\x0e\xdf\x1e\xe2\xba\xc0J{\xbb\x9b\xf9\x9f{\xaeQ\x93\xbf\x06\'\x9e\x1a\xc0,\xbd^\xf1\xfe\xe4\x03\'\x9e\x13\xb0s\x8a\xea\xc1\x83\xf4\xc3\xc7Cc\x0e\x1f\x0fk\x0eN\x8e\x07\x00f\xd6\xda\xf2\xb3\xe7\x9dc\xbet\xf9\xdc\xb2\xac\xf6WY/\xdf\x7f=O\x199\xbf,\xeb\xaay\xa5Y\xc3\x1f\xb7>]5\xc57\x8dc\xf8\xb1j\xbf\xee#\x84\x10\xa2z\xcc\xf1\xfe\xde\xf3^~\xbb\xcb\xdf\xef\xebgM\x18\xd1\x87\xd3\xc6:\x95\xe9\x848\xa9\xe1\xa5V\xe6\x87\xe7\xf8\xc6^\\\xb5y\x86\xc64\xe3\xa7\xce\xbf\xc5z\xe3\xcd\xc7|\x9f\xcc|\xd2\xf7\xe9\xd2\xeb\xacW\x9f\x05\x0fokS\xd2\nd\xf0\\\n~\xa8\xe5\x89\x9e6\x9b\xb3b\x9a\xf0\x93]\x8f\xf8\xfb-\x9c\xc3\x89\x9d\xc0I]N\xfcD\xbb\xce\xf7PK\xb0\xa7\x97\x9dS\xdej\xbe>e\x9c\xf9\xedf\xb0\xa7\x178\xb1\xd2\x9f\x8f\xdda\xbd\xf1\xc1\xf3\xbe\xaf\x97\x1f\xed\xfa\xb4\x10B\x9c\xac\xba[/|\xd2\x93\xc7=\xe6t\x0e!\x84\x10B\x08!NJ\xeciu\xbd5\xf9\xc3\xdb\xac7>n\xcdc\xfa\\e\xbd2\xb1)?a\xefZ\xe6J\xe5I\xbe\xea<5\xfe\xf3\xfe\xbe\xd4\x0b\x1d\xcb \x84\x10B\xd4Q\x06\xc0%\xb6\xceH\xe9Y\xb6\xcew\x0c\xcd\xad\x98\x96^\xb2\xf6\x17\xc1\x97_\xd9\xb1\xa3h\xda5!\x9ak\x16\x80\xdf\xab!Z\xc5Q\xdao\x8e\x9e_\x08Q\xf3\xd1\x18\x05\xe0\xe3\xf2\xe3\x8c\x19G{\xca\xfbj\xfbS?i\xbf\xb8\x00m>\x08\x1c\xc8x\xd5\x82\x93\xba\x00\x9a\x05J]Y\xf5\xc9\xbc\xf5\xebi\xc1\xed\xd6Z{>~d\xec\xd2k\x1bwpo.?Gb\x1f@[\x03J\xcb\xae\xfa9\xea\x00\x06\x01\xbe\xd7\x01\xad/\xa0\x9d\x03\x94Mv:\x92fi\xbd\x0e\xa0,\xb4\xaf\x15\xf6\xab\xd3Yj\x8a\xc1\xe6\x7f\xef\x9eC;T\x18\x1b\xb1+\xb4\xbd9\x00w\x05\'v\x00P\x06\xd0~@\x1d\x00\x8c\xfd\xa0\xd4J\xbe\xf6\xd3\xae\x02p%\xa0\x00\xf6l\x019\xbc\xc8\x8d=-\x00\xcb\x0b\x84\xed\xb6w\xde\x84\xae\x80aV\xf6w\xcfl\xce\x8a\x81O}\t\xe0\x8f\xfb\xf5\xae\x033\xe9V\xaf\xad\xb9j\n\x1e\xe2\x1a\xa3\xfa\xfc\xf6\xad\xb1a\xe9n\x14\xff\x0e\x84n\x07\xbds\xf8k\xa5\xf1\xfb\x00|\nN<\x07\xec9\x05\x94\xb6\xe4\xf8\xf3\r\xd2\x01\xedj\x80v\x80\xd2fVsz!j\x1fJ\xdb\x04Nl\x0cNh\n\xca\xdc\x01\x9a\xe2\x9b\xc5\t\t\x97\xaav\xafn\xa2\x03_\\\xc1m\'|\xc3#\x1e8\xf8\xff^ug\x99\xf767\x1d\x96f]\xfa\xb6\x87\xf9*P\xe6\xaaj?\xa78\x8cS\x0c \xdb\r\xc0\x05\x04\xb9\x01\xdd\x00\x94\x0b`\x17\xa0\x19nh\xeeF\x08\x8dh\x80\xa8\xc8(\xcb\x88\x0c\x86;\xd2\xa5\xeb\x11n\xa5G\x18\xa0p\x8d\x11A\xd0\xc24M\x0b\r\xb6\xb4\xa0\xc1\xde\'w\x02\x88\xf8\xc6Z\xdf\xba\xbf\xf7\xde\xb2`\xb8\xc2~1\xb7\x9c\xa2C\x0b\xe9\xed\xbd\xcb\xbd\xc0\xb7<l\x98v&\x18\x0c\x8d\xc0\x17\xa8\x16%\n(\x06a\x1f\x95\x96h\x97\xbc;\xbf\xc9\xcf\xa7\x87\x7f\x95sV\xee\x16\x87\xbf3B\x08!\xfct\xae\xeb\x8c\x85\xcf\xf3\xfc\xaf\xc0I\xcf\x80\xd2\x17\xf4\xe4\xff\x9c\xab+\xbd\xc7\x0c\xac\xbd\xdb\xe9lG\xc5\xc3\x9b]\xc5\xf1\xa9;\xb5\xfc\t\x8b\xf4G\xe6V~\xfc \x1dh\xd6\xfaZ\x15\x7fC++n@\x1c\x82\xbbnE\xfe\xac\x85\xc6\xce\xd7\xa7c\xcb\xcf\x81\xbf6T6\x1f0\xda\x018x\x8d*!\x08\x94Y\xf6\xcfg\xf5\xa6.9\x00r\x02\x9bM\x1c\x13e\xac\x08\xec\xf9&n\x06\'\xf6\x00\xa7,8x}\xb8\xca4 \xd8d\xe5\x05P\x02pT\xa5\x06\xf3\x10W\x98\xe5\x8e,\xa2\xb2| \xb8\xd4\x8e<\x87\xe7\xf6\x9c\x01\xb8\xf2@/m\xb4u^!\x84\xb0\x01\x93\x16\xa2\x01\x05N\xe7\x10B\x08!\x84\x10\xe2\xa4\xc2C\\W\xe0\xf4{Zs\xd4\xbd\xdb\xb5\xc2\xaf\xdf\xc3\xba4\xd0\x8by\x1b\x19\xbf8\xb6\xee\x8d\x13"]\xd0\xa2\xc3\x94\x11\xf2\xa3\xb1n\xb9#\x19\x84\x10B\x88:\xcc\x00\x94\xbd\x05M\x01\x12\xad\x874+5}\xfb\xa0y\x8b+;\xd6\x82\x15n (\xaf:r\t!D \xcd\xf5.\xed\x96\x8e\x05%\xdb\xb4\xdc\xd9\x80\xb6\xc3\xe9<\xb6\xb0\xb10vN\xf1\x1d\xa5\x86\xcb\x88l:\xfd\xf7w?\x7f\xe1\x86\xcb\x9b\xcf[\x9f\xc7@\x08\x81\xea\x01Q\xfb\xed:\xcfI\x8f\xc0`m?\xc0&\xc0%G[h\x13P\x9c\x10\x19\xae\xdc]\x0b\xd9\x87s\x83?\xa8\x95\xafcl\xc7#\xc3B\x94\xfeX\x04\xbbZ\xef\xa3\x12\xd3k\xf9^\x87k\xc2W\xe5\x8b\xa0\xf7\xc6\x01A\xb1\x00Z\x01\xd6\xd9\xe0D\x05\xca\xf8\xb2\xe2\x93\xabw\x01z\x08\xa0 \x00\xd3\x0f-\xaewN\x07\x00\xbbA\xe3\x8al\x9b\x91\x93\xda\x01\xa4\x83R+\xd5\xc5\xad\x19\xa74\x9ecn\xfe\xaa\xbe\x16\x1a\xf6\xae\xbe\xf4\x91Y\xf4\xf0\xc9Y\xcc\x04\xe0"t~$\x14.\xde\x81\xbc\x9c\x12\xe4\x8d\x07\xbdt\xf4\xaf\x952\xe6\x82\x1fj\x0f\xf6\xf4\x07\xb0\x18\x94\x96{\xf4\x19\xc3\\\x00\x15J1\x93\x10\xc7A\x19s\xc0\x9e\xd3\x0f\xfe\xde\x9d\x0f\xca\xcc\xff\x9e\x1fL\x1eh\x9d6\xf9O\xbd\xf0\xab\xfeV\xb3\xf4\xe9<\xe4>\xd0\x94J\xbf\'\xae\xacy4rJ\x9cob\xab\x14\xeb\xc2\xc7\xc7\xb0>\xf2\xa4-\n\xe7\x14\x03\x80\x06d3\xd0\x88\x81U\x0cLU\xc0\x10\x03\xf0\xea\xa0\xb7\xca\x17o\xf2\xd0\x18\xd0\xe4\xf2\x05\xc6\xfcPc\xc0\xad\x83&l/\xbf=\xbc-\xa0tF\xea\x9a\xfa\x18}f=D\x87\xbc\x83\x81\xeb\xacR=8\xc5\xf5\xd3\xb9A\xba\x11\xec\x86\x16\x02e\x84\xe8P\xc1m\xb9~\xf3R\xe5C\xb6^XdA\x85j\xa0p\x9d\xb5\xc8.\xaaA\x93\rF\xeef\xc3\x82;\x0c\xedC\xa2\xd8\x08\xb6\xa0\x85\x1b\xd0\x83u\xa2\x10\x1dZ\xa8\x01-\x84\x80`\r\xa41\x00\x02A\xb1\xf2Z&\x95X\x9a*6\xd9,U\x8cb\x1f\xac\x12\x9fR%\xa5\xf0\x951PD\x8c]\xdb(\xcfzC_Z\xf8\x90y\xf6\xec%zv\x1b\x0b\\\xd0\xdb:u\x16)U\xf0\xa1ke\xeb\x9d\xc8\xcb\xdf\xaa?=\xb7\'\xdeh\x0b(\x13z\xe6\xc6\xd7\xbe\x7f\xf4\xda\x06\x7f\xcc\x7f\xb8\xc5\xaf\x07\xfe\x83wW\x15:\xf4S\x12B\x08QED\xa4F\xfa>\x98\x90\xab\x9dz\xdfo<,\'\x8a#\x86\xef\xd6\xf2\x9f\x01M\xaaq\xbf\xdb\xe3xT\xbb\xde\xdcr\xec*\xda\xfd\xe4Zz\xaar\xd7\x8b\xd8\xd3\xe8|\xab\xd9\xf9m\xad\xb8\x1bZ"\xfa\x82B\xf6n\xde\xa8\xe5L\x1b\xa7-\xbf\x1f\xc0F\xc7\xaem\x94\xbf\x86\x98\x7f\xf8\x0e\xed\n\x00\x9f9\x92E\xd4p\xfa\x06\xa0 \x1e\xc0:;f\x0b"\x97n(\xf8\x00\xad\x18\xb0*\xd9Y::8\n\xc1a\x05\xf0\x16\x00\xc5\xf6\x164\xc1b\xc0\xb2wJ!\x84\xb0\xc9uV\xbb\xa5E\xec[X\xf9\x8aj!\x84\x10B\x08!\xc4Qqr\xfcM\xe8\xf8\\\x90e\x84|\xad\xaf{`\x13\x8dY|\xe81G7\xf1\xe6\xc6\x9dU\\\xbdB\xf2\xee\x03\xbd,\xeb\xc9\x84\x10B\x88\x003\x80\x10\x9bwSK\xb8\x00\xe0\xf5\xa0\x89;m\x9d\xf7\x1f\xdc\x8a\x9a\x96\xe8j\x1f\x10^\xb9\xc5\xac<H\xd7Yw[\x9ar\xbe\xa0\x89=\x97\x03As@/:\x9fE\x08Q3qb\x1f\xc0\x95\x0f\xf8B@\x19s\xfe\xfe\xd0\\\x9e\x1bB\xa6\xd6\xe7c\xfd\xfe\xe7\xc0\x9ek\x01s\xbbS1k*\xc3\xd0{\x01\xb4\xf8\xb6K\x0b:\xde\xa5\x9a\xb7\xe8\xd3\xe7\xaeG\x08\x13J@\xe9\xb2P\xa4\xd2\xfe\xbc\x15h<\x15\xd0&:\x9d\x04\xd0Z4\xe6\xf0\xf0H\x0e^\x02\x1a\xb7\xc7\xe945CI\\\x1b\x8ek\xe6e\xcb\x8a`\xb7\xb1\x9d\n\xca\x17G\xd1\x18\x13\xc0\xae\x83\xff\x94\xe3\xc1\xc1\x95\x9a\x9a2\xb6\x81=\x1d\x00n\x08`\x06\xa0\x19\xe0\xa4\x0b@\xe9k\xed\xcb_A\x9c\x1c\x02\xf8\x9a\x03F\xa5\n\x8fN\xc8\x9f\xaf\x85S\xdcWXm^m\x83\xb8\x8e\xaf\xd3\xef\xc9\xb3\xb0=\xc6\xd6L5H\'\xf3\xd9\x1b\xafTm\x87\xbd\xcb\xcb\xd6\xe4\xc1\x1c\x06\x9ar\xfcB\x06\x9a\xb8\x06<:\x1b(>\x1b\xec\xd9\x07\x94\xee\x04^\xd9{\xe8\x02$\x8f\xb8\x19P\xc1@\xea[\x01\x88/D\xedFiK\xc1\t\x1d\xc1\t\x17\x03\x99\xd3@\x93v\xcd\xe7\x87G\x9d\x83\x96c\xf7\xe9\xc5?\xf6V\xed\'\xcef\xdc\x13\x88\x0b\xfc_\x1b\x1b^hc\xc5M\x19\xac\xba\xfe\xe7-Nx\xc0\xf1\x02\xe7\xaa\xe2\xc1\xc1@tL\x18\x82\xe2z\xa2I\x97S\xcc\xb0n\xf5\xcc\xe0\x96\x8a8\x94\x11\xaf\x18`\x85V\xec\xd6\xae6-\xa5\xdc.\xe8\xae\x9b\xbd#\xb2\t\x1c\xfc\xb5\xb5\xa1\xc5E\xde\xfb\n\x82\xe0\n\x9annj\xa8\x91\xe6\xee\xe7\x1dl2!x\x8e\xb5=Rc\xb8\x17\xf0rW\x06]\xa1\xed\xa1B@1t\xdd\xc4\x15h\x036a*\xa22\xc5\xca\xa74.\x0bgwX0\x19%a\xec\x0eb0)(\xb6\xa0\xb8\x19"\xdd%\xca\xf4\xe6\xa1,?\x0fe\xc5\x05df\x97\x92Y\xaa\xa0\nL\xc5E\x96\xa6\n\xbc\xb0\xf2K\xd9,(\x86\x95\xbfG/\xc8\xdf\x85\xa2\xbc\\\x94\x96\x02\xe4\x0
May 19 10:51:42 fooserver1.example.net clog_qgis-dev[662]: xdfF\x88\xfch\xac>g\xca7\xfa\xba\xef\x81\x98\xcd\xd5\xffy\x84\x83\x0em\xa0a-\x03\xa8=\x80\xed\x00P\x10\xee\xee\x10^\xe8- \xa0\xd2\x9f\x91\x88\xaa\x88\xda\x02\xe4t\x07\x10\xb8f\x1d6m\x8a\xc7\x0c\xcb h\x80I\x07?\x1f\x0b\x02P\xa1\xcf\xc9\xda"\xb6\x01\x11i\xb9\\f_A\x13\x8fj\n\x94\xcd\x00\xd0\x10\xe0V\xe0A\xdd\x8f\xbc\xfe%\x84\x10NKn\xfc\r\xad;\xed\x05\xec\x8a\x81\x145\t!\x84\x10B\x08Qa\xd7\xf2\xa4\'\x9a\xaa\xe8k?\xd0\x96\xbf\xf9\x95>l\xa2\xd3y\x8e\xcf\xfb4\xe0\xbeR\x87\x16\xd2\x98\xc3\xa6m\xa7\xbc\xfb\x00>\x1d\xa0p\xc0\xfc/\xd8\x93\x04\x14\xef\x02M)>\xf1\\B\x08!\x84\xf0\x97\xbd\x05M\xe5\x0b\x84>\xb2u\xce\xa3p#8\xcc\x05=6[/\xab\xf4n\x84\rA\x11&,\x13\xf0:\xbbC|yw\x0c)H\x10\x15#\xc5Lu\x13\xa5\xcd\xfb\xe7]\x1e~\xff\xd6\x07\xd4w]\x97a\xdb\x87ND\xaav\x9c4\x000\x17\xfb\xd5\xb5\xe6\x1fZ\xa9\xe8n%\xbao{\x01\x8ax\x10w\xd4\x1br\xe4\xc2\xf2E0zoP\xda\xb7v\xc4\xad5\xca;\xd1\x1c\x00\xb0\x1a\x00\xc0\xa3\xa3\x80\x92\x06\x80\xab)`\x9d\x01N\xb2\x00\xb5\xe7`\x91\xd3\x9e\xa3\x17\x93\x98\xb1\x80U\xe5\x9fK\xd5\x05EGSHs\xc5X\xeet\x92*\xa8\x07\xc0\r\xb0\x01l\n\x01Pt\xfc\xa77\xe9\tNl\x0e\xe8\xdb\xcb\x7fN4\x07(.\x02\x0f\xd2\x01\xe4\x02\x853.\xe7\xd6\xfdB\xd8\x1d\xb2\x80\xb6O{\x17[\xfe\x17\x80\xaf\xa1j(}7\x80\xee\x87o\x07\xb0c%\'\xdd\x08DO\xad\xec\xc2\xf6\x18\x1e\x1du\xa9\xd5\xee\xd5X\x0ei\xfa>\xad\xbee+\x8d9i\x8bs.7[>\xb3L\xdf\xd3\x7f\x19\xed\xa9\xa7Co\xb0L\xdf\x7f\x8b\xdf\x93\xf1 \x1d\xe0\x01\xa0\x8c\x8fm\x8c(D\x1d\xa6-\x03T\x17\x00\x0b\xfe\xbag\x86\x9e4\xb6\x8f\x95\xf6\xb2\x17ek\xa2\xac\x90$\xf0\x88\xe5\x81\xd8-\xecK\xfd\xc1\x87\

Any help is much appreciated.

Kind regards

### Steps to reproduce the issue

See above

### Versions

3.22.x and 3.28.x

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by elpaso** [comment]
The logs you pasted do not come from QGIS server core implementation (they are python formatted).

**Comment by GeomaticaNet** [comment]
please fix this bug, any help in july 2023?

**Comment by GeomaticaNet** [comment]
i had to downgrade to 3.22!

**Comment by alexbruy** [comment]
@thetuxinator, @GeomaticaNet please check with the latest versions and provide steps and data allowing to reproduce the issue.
