### ISSUE TITLE
3D viewer for Negative Z values

### ISSUE THREAD

**Issue by Todbury** [qgis/QGIS#53160]
### What is the bug or the crash?

I've created a subsea surface for a geological surface, however to try to view it in 3D viewer (QGiS2threejs) it always references the zero z value and takes the area out side of the surface back to zero.  Is there a way of removing the zero value
![Screenshot 2023-05-19 093725](https://github.com/qgis/QGIS/assets/65807264/d717e936-948a-4289-b421-c6b9b8af8a5c)

### Steps to reproduce the issue

Create a contoured surface with z values range -7,100 ft to -7,300 ft
show in a 3D viewer I use Qgis2threejs
edge of surface always tries to go back to zero z value

### Versions

QGIS version
3.28.0-Firenze
QGIS code revision
ed3ad0430f3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.2
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
clipper
1.2
easy_processing_tool
0.4
LAStools
1.4
pluginbuilder3
3.2.1
processing_r
3.1.1
Qgis2threejs
2.7.1
quick_map_services
0.19.33
Save-DXF
0.1
Smart_Map
1.2
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by saberraz** [comment]
This is related to the plugin. Please file a bug in the plugin repo. QGIS has its own 3D map. Does it work there?

**Comment by nicogodet** [comment]
Not a QGIS issue, closing.
