### ISSUE TITLE
Custom symbols rotation setting for item in key on layout not working

### ISSUE THREAD

**Issue by NigelCowlin** [qgis/QGIS#53166]
### What is the bug or the crash?

This used to work on earlier versions, but since updating to 3.28.6 it seems to have stopped working.

### Steps to reproduce the issue

these are the settings:
![settings](https://github.com/qgis/QGIS/assets/108716444/b58a2e11-8a38-4f80-9ace-2293fa031a3b)
the result is this:
![should be like this](https://github.com/qgis/QGIS/assets/108716444/6b863981-a095-4f5e-a28a-cad7dedf28ab)
it should be like this:
![result](https://github.com/qgis/QGIS/assets/108716444/5b4ad2a0-f8d1-4d8d-b1b1-ae9f8765c3fe)

### Versions

QGIS version
3.28.6-Firenze
QGIS code revision
868c9fa03b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.6
autoSaver
2.6
clipper
1.2
dimensioning
0.2
ImportPhotos
3.0.5
Mergin
2023.1
MultiDistanceBuffer
3.2.4
NNJoin
3.1.3
qfieldsync
v4.4.9
Qgis2threejs
2.7.1
quick_map_services
0.19.33
TomBio
3.4.2
valuetool
3.0.15
ZoomToPostcode
1.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by NigelCowlin** [comment]
Sorry the last two images were the wrong way around!
This is the result:
![result](https://github.com/qgis/QGIS/assets/108716444/3c513519-56e3-4f51-85bc-26b4ef61e1fd)
When it should be like this:
![should be like this](https://github.com/qgis/QGIS/assets/108716444/5ab15e91-9059-4121-9852-7862dcd9c7a9)

**Comment by YoannQDQ** [comment]
This works on my machine (QGIS 3.31).
Could you upload a project sample which demonstrates the issue?
