### ISSUE TITLE
Commit errors: Could not commit changes to layer table1 while using split features

### ISSUE THREAD

**Issue by sudhirsilwal23** [qgis/QGIS#53177]
### What is the bug or the crash?

Could not commit changes to layer table1

Errors: SUCCESS: 1 geometries were changed.
  ERROR: 1 feature(s) not added.
  
  Provider errors:
      PostGIS error while adding features: ERROR:  null value in column "Pondid" of relation "table1" violates not-null constraint
    DETAIL:  Failing row contains (null, null, 0103000020E61000000100000005000000780F04A3B9CA54404E82C37F42333A..., null, null, null, 26.200282271920326, 83.1674879684653, 6152, null, SA, USA, CA, null, null, null, null, null, null, null, null, null, ddd494a0-6f4f-45d3-a160-e13ad6653645, null, null).

Do I need to make any changes at the database level?

### Steps to reproduce the issue

I have connected QGIS to postgres DB and imported the polygon layer 

### Versions

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code branch | Release 3.30
Qt version | 5.15.8
Python version | 3.10.11
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.2
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.14.0
OS version | Ubuntu 18.04.6 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [x] I tried with a new QGIS profile

**Comment by DelazJ** [comment]
> PostGIS error while adding features: **ERROR: null value in column "Pondid" of relation "table1" violates not-null constraint**

I understand that you have the "Pondid" field empty while it should have been filled. Did you fill it?

**Comment by sudhirsilwal23** [comment]
I am not adding new polygon features and splitting the existing features. The system should add new rows with existing "Pondid" and append the existing "Pondid" with _1.

**Comment by nicogodet** [comment]
@sudhirsilwal23 Are you able to test on master ?

**Comment by sudhirsilwal23** [comment]
Are you able to test on Master? Sorry, I don't understand what you mean. But, I can add new polygon features in the system by inputting a new "Pondid" to the polygon. Problems arise when I split features.

**Comment by sudhirsilwal23** [comment]
Ok. Thank You! I will check and let you know if I am to find the solution.

**Comment by DelazJ** [comment]
@sudhirsilwal23 Do you still have this issue with 3.32?
