### ISSUE TITLE
Optional template {usage} parameter not propagated in Download vector tiles algorithm

### ISSUE THREAD

**Issue by lazaa32** [qgis/QGIS#53183]
### What is the bug or the crash?

Related to: https://github.com/qgis/QGIS/pull/53124
Similar to: https://github.com/qgis/QGIS/issues/49217

When trying to download vector tiles from MapTiler Cloud via `Download vector tiles` tool, no tiles are downloaded into MBTiles. `{usage}` parameter should be set to `usage=export` in requests to api.maptiler.com, but instead there is `usage=%7Busage%7D`. Invalid requests return no data and thus no tiles are written into mbtiles.

### Steps to reproduce the issue

1. Get FREE Token at https://cloud.maptiler.com/account/credentials/
2. Add MapTiler Tiles as Vector Tiles source
- URL: https://api.maptiler.com/tiles/v3/{z}/{x}/{y}.pbf?usage={usage}
- Add new Auth configuration - MapTiler HMAC-SHA256 and paste token from Cloud

![image](https://github.com/qgis/QGIS/assets/19833762/599fcdc9-1031-448f-8c26-da30de280776)

3. Add layer to canvas - requests are constructed in a valid form (check the `usage=view` in request url), e.g. `https://api.maptiler.com/tiles/v3/13/4424/2775.pbf?usage=view&key=9686bed528a9421ea02f05dddd16b68c&signature=xTPVV8d-OrtmozU9mXFH71OQuQBitKfWfFfi9Q5Xf2o=`
![image](https://github.com/qgis/QGIS/assets/19833762/09365d4b-ddb6-41b8-84f0-175cecff1afc)

4. Use Download Vector Tiles tool:
![image](https://github.com/qgis/QGIS/assets/19833762/8417a728-a753-43fd-8520-c30f89dab8dd)

Output mbtiles do not contain any downloaded tiles because requests to api.maptiler.com returns 403.
Request contain invalid `usage=%7Busage%7D`, e.g.: `GET https://api.maptiler.com/tiles/v3/0/0/0.pbf?usage=%7Busage%7D&key=9686bed528a9421ea02f05dddd16b68c&signature=qOgswjyf0ZBE2qDx09spZ89FUjTHUFQN68avOQnSlvg=`

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code revision | 4c6018de92
-- | -- | -- | --
Qt version | 5.15.6
Python version | 3.10.7
GDAL/OGR version | 3.5.1
PROJ version | 9.0.1
EPSG Registry database version | v10.064 (2022-05-19)
GEOS version | 3.11.0-CAPI-1.17.0
SQLite version | 3.39.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.10
  |   |   |  
Active Python plugins
rvt-qgis | 0.9.4.1
QGIS3-getWKT | 1.5
shapetools | 3.4.11
zoom_level | 0.1
lockzoom | 3.0.3
Qgis2threejs | 2.7.1
qgis-maptiler-plugin | 3.2
QuickOSM | 2.2.2
qfieldsync | v4.4.9
layertilesmapcanvas | 1.4
interlis | 0.14.8
OSMDownloader | 1.0.3
QuickWKT | 3.1
qgis2web | 3.16.0
plugin_reloader | 0.9.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.31.0-Master
QGIS code revision
[4c6018de92](https://github.com/qgis/QGIS/commit/4c6018de92)
Qt version
5.15.6
Python version
3.10.7
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.11.0-CAPI-1.17.0
SQLite version
3.39.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.10

Active Python plugins
rvt-qgis
0.9.4.1
QGIS3-getWKT
1.5
shapetools
3.4.11
zoom_level
0.1
lockzoom
3.0.3
Qgis2threejs
2.7.1
qgis-maptiler-plugin
3.2
QuickOSM
2.2.2
qfieldsync
v4.4.9
layertilesmapcanvas
1.4
interlis
0.14.8
OSMDownloader
1.0.3
QuickWKT
3.1
qgis2web
3.16.0
plugin_reloader
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
You do not need to specify `usage` in the URL explicitly, it is hadled by QGIS.

**Comment by klokan** [comment]
The bug reported here is about `usage=export` not present in the URL of the requests for the code merged recently into master...

The value `export` is not properly propagated in this case by QGIS - instead, it remains to be not set (it is passed as `usage={usage}` wrongly - without specifying whether it is `view` or `export`).

**Comment by klokan** [comment]
Thank you @nyalldawson ! Amazing
