### ISSUE TITLE
rotate stucks on KDE Wayland

### ISSUE THREAD

**Issue by logan001** [qgis/QGIS#53187]
### What is the bug or the crash?

I have a 4000-5000 lines of vector both as shp and as postgis. i wanted to rotate them but the preview stuck after moving for a little and nothing else happen on wayland. i went to windows and everything work and then i thought to try x11 (cinnamon) and again everything works. just on kde wayland it stucks. i can rotate lines when is just a few on wayland. it just does not work with so many.

### Steps to reproduce the issue

kde wayland session, a layer with lots of lines. rotate.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.9
Python version | 3.11.3
GDAL/OGR version | 3.7.0
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
Compiled against SQLite | 3.41.2 | Running against SQLite | 3.42.0
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.14.0
OS version | Arch Linux
  |   |   |  
Active Python plugins
qgis_easy_query | 1.0.4
postgis_geoprocessing | 0.9
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99

</body></html>QGIS version
3.30.2-'s-Hertogenbosch
QGIS code branch
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Qt version
5.15.9
Python version
3.11.3
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
Compiled against SQLite
3.41.2
Running against SQLite
3.42.0
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.14.0
OS version
Arch Linux

Active Python plugins
qgis_easy_query
1.0.4
postgis_geoprocessing
0.9
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Qt5 support on wayland is buggy.
X11 is very recommended if you want to use QGIS.

See https://github.com/qgis/QGIS/issues/46031#issuecomment-968362346

**Comment by logan001** [comment]
i see. 
i'm not sure if i should close the bug report. do as you see fit

**Comment by alexbruy** [comment]
Closing as Qt 5.x on wayland is buggy.
