### ISSUE TITLE
XYZ Tiles Connection 'Referer' parameter cannot be defined

### ISSUE THREAD

**Issue by NicolaPx** [qgis/QGIS#53195]
### What is the bug or the crash?

Trying to define  a XYZ Tiles connection the 'Rerferer' parameters cannot be defined. At the moment of connection definition I can compile this field on the interface, but when I reopen the propriety of the connection the parameter is lost.

### Steps to reproduce the issue

Browser (Pane)
XYZ Tiles
New connection
<Fill the Referer Field>
OK
<Reopen connection>
the referer field is empty

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
actions_for_relations
1.2.0
clipper
1.2
clusterpoints
5.1
CmtPlugin_QGIS_2
version 0.1
delete_null_fields
0.2
latlontools
3.6.10
lftools
1.10.0
MagneticDeclination
2.3.1
magnetic_bearing_measurement
0.5
MemoryLayerSaver
4.0.4
mmqgis
2021.9.10
nominatim
1.4.5
OSMDownloader
1.0.3
processing_r
3.1.1
qgis_resource_sharing
1.0.0
QuickOSM
2.2.2
quick_map_services
0.19.33
scpplugin
2.0
SelectByRelationship
0.3.3
splitmultipart
1.0.0
timezone_expressions
v0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Looks like a regression to me.
I didn't notice earlier but I have WMS connections with a referer that worked before but not anymore.

**Comment by nicogodet** [comment]
Something between 3.28 and 3.30

3.28:
![image](https://github.com/qgis/QGIS/assets/39594821/8c350b0e-ab02-41d6-a0ab-3f59b36544d2)


3.30
![image](https://github.com/qgis/QGIS/assets/39594821/0d134732-e3f2-48b1-8d8a-77daec76fd63)
