### ISSUE TITLE
"Order by" memory leak

### ISSUE THREAD

**Issue by JlEC1** [qgis/QGIS#53198]
### What is the bug or the crash?

When use

```
request = QgsFeatureRequest()
request.addOrderBy("some_field_name", True)

for f in layer.getFeatures(request):
    ...
```

for GDAL data provider, you get memory leak until you close app.

As i see in QGIS sources, for GDAL data provider is created QList, where store all ordered layer features.
I think, for some reason, these features persist in memory after the iterator is destroyed.

This bug works for several OS and Qgis versions.

### Steps to reproduce the issue

```
request = QgsFeatureRequest()
request.addOrderBy("some_field_name", True)

for f in layer.getFeatures(request):
    ...
```

After that you get memory leak

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.9
Python version | 3.11.3
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.2
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.14.0
OS version | Arch Linux
  |   |   |  
Active Python plugins
mka_gpzu | 1.0.3
clipper | 1.2
quick_map_services | 0.19.33
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.30.2-'s-Hertogenbosch
QGIS code branch
[Release 3.30](https://github.com/qgis/QGIS/tree/release-3_30)
Qt version
5.15.9
Python version
3.11.3
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.2
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.14.0
OS version
Arch Linux

Active Python plugins
mka_gpzu
1.0.3
clipper
1.2
quick_map_services
0.19.33
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by rouault** [comment]
@JlEC1 I don't confirm this

Running the following test on a test .gpkg with 100,000 features, the RAM usage remains stable
```
from qgis.core import QgsVectorLayer, QgsFeatureRequest

vl = QgsVectorLayer("/home/even/gdal/gdal/build_cmake/extract.gpkg", 'test', 'ogr')

i = 0
while True:
    i += 1
    print("Pass", i)
    request = QgsFeatureRequest()
    request.addOrderBy("building_id", True)
    for f in vl.getFeatures(request):
        pass
```

Trying with the original 3.2 million feature dataset, the RAM usage remains stable at ~ 6 GB. I can indeed observe that if after having queried features on the large dataset, I then loop over the extract.gpkg one, the RAM usage remains at its peak, but stable. So I don't believe there's a memory leak. It is just that RAM isn't recovered by the operating system.

**Comment by JlEC1** [comment]
Maybe you're right.

But it normal? What if I upload a large data set, then after that, in order to continue working, I need to close and reopen the application, otherwise it just takes up 19 gigabytes of RAM, almost all.

**Comment by rouault** [comment]
> But it normal?

Probably not, but I'm not aware of portable/safe ways to avoid that.

Anyway https://github.com/qgis/QGIS/pull/53266 fixes the issue (provided your datasource is GeoPackage) by letting SQLite do the sorting instead of QGIS
