### ISSUE TITLE
Join attributes by location (summary) not calculating mean 

### ISSUE THREAD

**Issue by camiaiuti** [qgis/QGIS#53208]
### What is the bug or the crash?

I have to calculate the mean of a certain variable , called visibility, inside an area that correspond to a grid. Therefore I would have to calculate per each grid the mean value. 
It worked only for another variable, called seastate, but now it is not working anymore. 
I have checked the CRS, I have installed again QGIS, and it is the latest version. 
I do not understand because it was working until couple hours ago. 

### Steps to reproduce the issue

Processing-> toolbox-> Join attributes by location (summary)

### Versions

3.30 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
@camiaiuti, could you please provide the info requested in the issue report form ("QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here.")? Could you please provide sample layers and all the processing algorithm options set?
