### ISSUE TITLE
[WFS] - GetFeature problem - Empty attribute table

### ISSUE THREAD

**Issue by jdaranlot** [qgis/QGIS#53212]
### What is the bug or the crash?

I cannot load features from several of my own WFS connexions.
I obtain an empty attribute table. 

### Steps to reproduce the issue

My WFS connexion is not public so I cannot provide the URL.

1. When I look to the WFS properties, I can see the number of features :
![image](https://github.com/qgis/QGIS/assets/99390488/522441e4-6a58-49ee-9e80-974f5f70d84f)

2. But the preview pannel is empy : 
![image](https://github.com/qgis/QGIS/assets/99390488/f093419b-502f-4cec-b96a-dd04cf2637b7)

3. When I load the WFS, I obtain 0 feature in the properties and so, the attribute table is empty.

4. Checking the network logs with QGIS Network Logger, all the URL are in status 200 and the .xml files are openable in a web browser. Even the getFeature call works in web browsers.

5. Loading the .xml getfeature response in QGIS permits to obtain the layer.

6. Loading the WFS with WFS 2.0 Client works

### Versions

3.28.4  
3.30.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by rouault** [comment]
@jdaranlot if the URL can be shared privately though, you can send it to met at even.rouault at spatialys.com . Otherwise addressing the ticket will be hard. At the minimum, you should provide responses to the GetCapabilities, DescribeFeatureType and GetFeature request
