### ISSUE TITLE
Support non rectangular shape for the MAP object in a print composer

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#53210]
### Feature description

It would be an interesting potential to edit the shape of the map object in a print composer.

![image](https://github.com/qgis/QGIS/assets/8614223/d378d5b7-b53e-4301-afb8-165826a35a7d)

The idea behind this is not only to create something covering the rectangular shape of the map object but that the map extent is taking into account its geometry.

If I have such a different geometry map object, the position of my atlas feature could avoid crossing with other objects like the legend.

- [ ] Be able to modify the edges of the map object

I would be interested in any feedbacks regarding this.

My solutions today are:
1. To play with opacity
2. To enlarge the margins around the atlas feature
3. Display the legend / items in another place (additionnal page, under or above the map object)

**Comment by andreasneumann** [comment]
Hi @ponceta ,

This is already possible:

![grafik](https://github.com/qgis/QGIS/assets/884476/937a551a-16c1-440b-9250-896a24c6df30)

and then

![grafik](https://github.com/qgis/QGIS/assets/884476/510a978e-25ff-48ca-a4e0-5bc308f6cb27)

Create a separate polygon and then apply it as a clipping path.

**Comment by ponceta** [comment]
This is an interesting solution but in my case I think I cannot draw a polygon per item I want to represent in my Atlas.

I use the clipping for drawing only some information about lines present in my current atlas feature so that's already a great great QGIS feature.

I really appreciate your feedback! Thank you!

**Comment by andreasneumann** [comment]
"Clip to Item" should be static and doesn't rely on an atlas feature. The "Clip to atlas feature" is the other option. But what you want can be achieved with "Clip to item", if you previously draw a polygon and then select it as a clip path.
