### ISSUE TITLE
PyQGIS: allow user to declare a "postExec" function in QgsProcessingAlgorithm subclasses

### ISSUE THREAD

**Issue by vidlb** [qgis/QGIS#53217]
### Feature description

It would be able to declare a `QgsProcessingAlgorithm` function to be executed after the algorithm has ran. Similar to the `onFinish` processing.run option, but one that can be declared in the processing algorithm class.  
May a postExec like there is an initAlgorithm ? Or just something that enable control on the onFinish behavior of other algorithms used by the one we are building.  
I don't know, I read the docs of classes like context or feedback, I also saw something about pre and post alg scripts, but it seems to apply to all the whole processing module.  

### Additional context

I'm currently writing a processing algorithm where I'd like to make some cleaning after execution.  
There is a layer which is created by the "Execute and load SQL" script and is loaded in the project instance, only after the execution, so I can't delete it within the `runAlgorithm` function, because it's not loaded in the project yet at that step (may be I need to try without the "is child algorithm" option ?).

And I can't use `onFinish` since the script is directly called by the end user, from the GUI.

**Comment by agiudiceandrea** [comment]
@vidlb maybe you can find some help asking to the qgis-user or the qgis-developer [mailing lists](https://qgis.org/en/site/getinvolved/mailinglists.html) or on [stackexchange](https://qgis.org/en/site/forusers/support.html#stackexchange).

**Comment by nyalldawson** [comment]
There's already postProcessAlgorithm which you can implement in your algorithm.

**Comment by vidlb** [comment]
Wow really @nyalldawson ? I searched for this everywhere in the docs, it should be mentioned [here](https://docs.qgis.org/3.28/en/docs/user_manual/processing/scripts.html) don't you think ?

**Comment by vidlb** [comment]
The only page where we can find this info is https://qgis.org/pyqgis/3.0/core/Processing/QgsProcessingAlgorithm.html
