### ISSUE TITLE
Form not showing (randomly) values except when triggering "Editing Mode"

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#53211]
### What is the bug or the crash?

When identifying a point with a custom form, QGIS is randomly showing only some attribute of some fields. The other fields seem empty, but when activating the editing mode, then all the fields are correctly filled.

All the fields have been set up with a `Value Relation` widget and the key field is the same for all the fields.

All tables are on a Postgres database

The attached video shows the behavior. 

[Screencast 2023-05-24 11:31:23.webm](https://github.com/qgis/QGIS/assets/2884884/21819469-dce7-48fb-9622-70f230c79a4e)

### Steps to reproduce the issue

Set up a custom form with relation widget

### Versions

QGIS 3.28.6 and Master ([eab811f9c2](https://github.com/qgis/QGIS/commit/eab811f9c2))

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by ghtmtt** [comment]
Same problem also on geopackage. I've prepared a subset of the original data as a geopackage with a testable project inside.

[test_form.gpkg.zip](https://github.com/qgis/QGIS/files/11562061/test_form.gpkg.zip)

**Comment by elpaso** [comment]
I think there is no bug here: the two "missing" fields (actuator and manufacturer) are NULL and the widget is set to **not** accept NULL as a value, so when you identify without editing mode activated it shows the actual value (NULL) but when you activate editing the widget is set to the first value of the relation (because NULL is not an option).

**Comment by ghtmtt** [comment]
thanks @elpaso for the reply and the explanation!
