### ISSUE TITLE
Not possible to apply QML to a point cloud layer

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#53227]
### What is the bug or the crash?

When I try to apply a QML file to a point cloud, it loads the QML correctly, but then when I close the Properties window, it defaults back to the previous color.

### Steps to reproduce the issue

1- Load a point cloud layer
2- Open the Layer Properties window
3- Apply the attached QML file to your layer (make sure you see the classification styling).
4- In the background, you should see the style has changed
5- Close the window, by pressing OK
6- It reverts back to the old style
[style_file_please_unzip.zip](https://github.com/qgis/QGIS/files/11564047/style_file_please_unzip.zip)
![bug_point_cloud_styling](https://github.com/qgis/QGIS/assets/2649047/f09d3a33-d412-4819-9ecc-a95ecebb6f5e)

### Versions

QGIS 3.30 and master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by meyerjo** [comment]
I experience the same problem with

QGIS version | 3.32.2-Lima | QGIS code revision | c0b88339649
