### ISSUE TITLE
Mac: Menu bar not visible

### ISSUE THREAD

**Issue by Jubbagash** [qgis/QGIS#53232]
### What is the bug or the crash?

QGIS 3.30
MacOS Ventura 13.3.1a

The main menu bar for the application is not visible, making using it extremely difficult (as I'm a total novice).

<img width="1915" alt="Screenshot 2023-05-25 at 16 22 30" src="https://github.com/qgis/QGIS/assets/134629139/bb39383a-3cd7-4972-8020-01663b9e0eec">

I've tried uninstalling/re-installing, reboot etc but nothing works.

Is there a fix for this?

### Steps to reproduce the issue

Download, run application.

### Versions

QGIS 3.30

Cannot access the menu to copy and paste

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
Isn't the mac menu bar shown at the VERY top of the screen? (detached from the QGIS application)

**Comment by Jubbagash** [comment]
Ahhh, you hero! Thank you. I missed the blindingly obvious.

**Comment by Haole16** [comment]
I have the same problem, is there any way to fix it?
