### ISSUE TITLE
Error while extracting GTFS - GTFS Loader

### ISSUE THREAD

**Issue by Rossellaross87polito** [qgis/QGIS#53231]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x0000157c (most recent call first):
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 321 in index
    cursor.execute("CREATE INDEX {0}_index ON {1}({0})".format(field,layer))
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 355 in load_layers_from_gpkg
    self.index(GPKG_path,['shape_id', 'shape_pt_sequence'],'shapes_point')
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 299 in run
    self.load_layers_from_gpkg(gpkg_path, layer_names)

Current thread 0x00002f3c (most recent call first):

Stack Trace

QSortFilterProxyModel::tr :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::nodeAddedChildren :
QObject::qt_static_metacall :
QgsLayerTreeNode::addedChildren :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.6-Firenze
QGIS code revision: 868c9fa03b
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.4
Running against GDAL: 3.6.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Python Stack Trace
Windows fatal exception: access violation

Thread 0x0000157c (most recent call first):
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 321 in index
    cursor.execute("CREATE INDEX {0}_index ON {1}({0})".format(field,layer))
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 355 in load_layers_from_gpkg
    self.index(GPKG_path,['shape_id', 'shape_pt_sequence'],'shapes_point')
  File "C:\Users/rosse/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\GTFS_Loader\GTFS.py", line 299 in run
    self.load_layers_from_gpkg(gpkg_path, layer_names)

Current thread 0x00002f3c (most recent call first):

Stack Trace

QSortFilterProxyModel::tr :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::nodeAddedChildren :
QObject::qt_static_metacall :
QgsLayerTreeNode::addedChildren :
QMetaCallEvent::placeMetaCall :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.6-Firenze
QGIS code revision: 868c9fa03b
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.4
Running against GDAL: 3.6.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

3.28.6-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by Rossellaross87polito** [comment]
here is the gtfs i tried to upload
[gtfs_compressed.zip](https://github.com/qgis/QGIS/files/11566878/gtfs_compressed.zip)

**Comment by nicogodet** [comment]
Not related to QGIS but a plugin.
SHould be reported here : https://github.com/ctu-geoforall-lab/qgis-gtfs-plugin
