### ISSUE TITLE
Boundary algorithm generates a vector with incorrect CRS

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#53241]
### What is the bug or the crash?

When I run Point cloud extraction > Boundary algorithm from the Processing toolbox, I see no result on the map canvas. I can see the attribute table containing one feature.

I then open the output vector data and assign the projection (same one as the input point cloud layer) and the vector polygon appears in the right place.

Here is the message I get in the terminal:
`CRS[1] Transform error caught: Could not transform bounding box to target CRS`

### Steps to reproduce the issue

1- Open QGIS 3.31
2- Load a point cloud layer
3- Run Point cloud extraction > Boundary algorithm from the Processing toolbox
4- There is no output visible on the map

### Versions

3.31

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by alexbruy** [comment]
Looks like this is an upstream issue in `pdal_wrench`. This Processing algorithm does not do anything with CRS.
