### ISSUE TITLE
32719 Projection

### ISSUE THREAD

**Issue by Cajcartografia** [qgis/QGIS#53259]
### What is the bug or the crash?

I want to work in my qgis project on WGS 84 - 19 S (32719 projection), and the coordenates are in º, not in UTM! Why?? 

I try many different ways to resolve the problem, please check it.

### Steps to reproduce the issue

Go to EPSG
Search 32719 projection
Click and select 32719
Check the coordenates

### Versions

3.28.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Can't reproduce on both 3.30.3 and 3.28.7
![image](https://github.com/qgis/QGIS/assets/39594821/0a5cb5cc-df9e-46d5-9cbf-a58bc988dc22)

> Go to EPSG

What do you mean exactly ? This step is unclear
