### ISSUE TITLE
OSGeo4W network installer express mode crashes

### ISSUE THREAD

**Issue by bjoh-01** [qgis/QGIS#53254]
### What is the bug or the crash?

When I run the network installer and select express mode, the program crashes with no error message. The installer simply disappears.

https://www.qgis.org/en/site/forusers/alldownloads.html#

### Steps to reproduce the issue

Download network installer from

https://www.qgis.org/en/site/forusers/alldownloads.html#

Run installation in express mode.

Toggle all packages or any of them (it crashes for any combination) and next.

### Versions

Unknown

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I previously uninstalled and installed some packages using the network installer in advanced mode. Advanced mode still works. Running express mode after advanced mode seems to crash.

**Comment by agiudiceandrea** [comment]
@bjoh-01, could you please report the issue to the OSGeo4W issues report system, opening a ticket at https://trac.osgeo.org/osgeo4w/?

**Comment by alexbruy** [comment]
No crash here on Windows 10 using osgeo4w installer in express and advanced mode. @bjoh-01 if this still an issue, please report at https://trac.osgeo.org/osgeo4w/ as suggested above.
