### ISSUE TITLE
Hang when opening large project "sub::bad_alloc" popup window

### ISSUE THREAD

**Issue by nickskelton2** [qgis/QGIS#53252]
### What is the bug or the crash?

"sub::bad_alloc" popup window when opening a project. Project does not open and hangs

Happens about 20% of the time

MacOS

### Steps to reproduce the issue

when opening a project

### Versions

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code revision | 0992b53397
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.4
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
slyr_community | 4.0.7
batch_gps_importer | version 1.0.1
profiletool | 4.2.6
quick_map_services | 0.19.33
ImageServerConnector | 2.1.1
menu_from_project | v2.0.8
GeoCoding | 2.19
ImportPhotos | 3.0.5
AusMap | 1.1
qgiscloud | 3.8.4
qgis_resource_sharing | 1.0.0
openlayers_plugin | 2.0.0
mmqgis | 2021.9.10
mapswipetool_plugin | 1.2
coordinate_capture | 0.2
Hy2roresO-master copy 2 | 0.0.1
catalogpl_plugin | 2.1.1
processing | 2.12.99
grassprovider | 2.12.99

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code revision
[0992b53397](https://github.com/qgis/QGIS/commit/0992b53397)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.4

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
slyr_community
4.0.7
batch_gps_importer
version 1.0.1
profiletool
4.2.6
quick_map_services
0.19.33
ImageServerConnector
2.1.1
menu_from_project
v2.0.8
GeoCoding
2.19
ImportPhotos
3.0.5
AusMap
1.1
qgiscloud
3.8.4
qgis_resource_sharing
1.0.0
openlayers_plugin
2.0.0
mmqgis
2021.9.10
mapswipetool_plugin
1.2
coordinate_capture
0.2
Hy2roresO-master copy 2
0.0.1
catalogpl_plugin
2.1.1
processing
2.12.99
grassprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

when opening a project

**Comment by nicogodet** [comment]
Never encounter this error, could you try with a new qgis user profile ?
If it still happens, can you share project ?
