### ISSUE TITLE
Inability to Input Japanese Text in QGIS Field Calculator (QGIS 3.28.6 and 3.30.2)

### ISSUE THREAD

**Issue by tohka** [qgis/QGIS#53276]
### What is the bug or the crash?

A bug regarding the Field Calculator in QGIS versions 3.28.6 and 3.30.2. This issue does not occur in QGIS versions 3.28.5 and 3.30.1.

When attempting to input Japanese text within the Field Calculator's input field, it is not possible. Typing on the keyboard and confirming characters using an input method does not result in the text being added to the input field. This also occurs in Expression String Builder. However, it is possible to copy and paste Japanese text from other editors into the Field Calculator.

### Steps to reproduce the issue

When Japanese is input in Field Calculator, the list of candidate conversions for Input Method is displayed, but no text is added even if it is confirmed.

![image](https://github.com/qgis/QGIS/assets/2786765/e83c8e7a-d501-42b8-aca3-c49289ca2c2f)

### Versions

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code revision
0992b533
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is a packaging issue in osgeo4w -- it needs an update to the latest qscintilla version. Can you file at https://trac.osgeo.org/osgeo4w/ please?

**Comment by tohka** [comment]
Thank you for your response.

I launched the included setup.exe in QGIS 3.30.2. I confirmed that qscintilla is already installed with the latest version, 2.13.1-1.

Additionally, when launching QGIS 3.30.2 and executing the script, the result is as follows:

```python
>>> f'{QSCINTILLA_VERSION:06x}'
'020d01'
```

Should I update to the latest version using tools like pip?

Thank you.

**Comment by nyalldawson** [comment]
> , 2.13.1

The upstream fix is in 2.13.4

> update to the latest version using tools like pip

Don't do that -- it'll result in a broken install. The solution is to get the packaged version updated.

**Comment by tohka** [comment]
I tried with QGIS 3.30.3 and similarly could not update to QScintilla 2.13.4 or later.

Does this mean we have to wait until the OSGeo4W package list is updated?
