### ISSUE TITLE
Distance unit not displayed on each value

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#53283]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/39594821/9fcd1187-0c8a-4b01-9542-7a0d12f8bdda)

### Steps to reproduce the issue

.

### Versions

Master 5e79276e73

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This was by design, in order to keep the chart relatively uncluttered.

For charts in layouts you have control over the suffix frequency, but in the interactive charts this option is not exposed.
