### ISSUE TITLE
Profile not redrawn after uncheck lock distance/elevation scale

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#53284]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/39594821/e60e925d-b4cf-42a7-bd9d-dda79c5958a5)
![image](https://github.com/qgis/QGIS/assets/39594821/3d0508ee-20f4-4eae-a5df-9280090c0233)
![image](https://github.com/qgis/QGIS/assets/39594821/5b6511fb-ab4f-45cd-93d1-477a64b52144)

### Steps to reproduce the issue

.

### Versions

Master https://github.com/qgis/QGIS/commit/5e79276e732b0279a75d32be85f94876eb3ea5a3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by nicogodet** [comment]
Triggering "full plot" would be the best I think.

**Comment by nyalldawson** [comment]
I don't think there needs to be any explicit change in visible ranges when unchecking this option. It just applies to all zoom/scale operations performed afterwards.
