### ISSUE TITLE
Crash when manually placing labels

### ISSUE THREAD

**Issue by lueho** [qgis/QGIS#53330]
## User Feedback

This crash happened when I tried to manually place labels.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000013a4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QTranslator::translate :
QTranslator::translate :
QgsVariantUtils::isNull :
QgsMapToolLabel::currentLabelDataDefinedPosition :
QgsMapToolMoveLabel::cadCanvasPressEvent :
QgsMapToolAdvancedDigitizing::canvasPressEvent :
QgsMapCanvas::mousePressEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Create a layer with labels

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
CityJSON-loader
0.8.1
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
qgiscloud
3.8.5
QuickOSM
2.2.2
quick_api
0.1
quick_map_services
0.19.33
save_attributes
0.1
save_attributes_processing
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

1. create layer with labels (PostGIS)
2. click the button to manually place labels
3. assign id column as unique identifier
4. click on label that should be moved
5. move the rectangle to destination location
6. do a left click
==> QGIS freezes and starts the crash report
![image](https://github.com/qgis/QGIS/assets/52178258/d9119fd4-dd2d-4c2f-9ca4-70e7fde31b8a)

**Comment by agiudiceandrea** [comment]
@lueho, could you please try if the issue does occur also using a new QGIS user profile without external plugins installed?

**Comment by lueho** [comment]
@agiudiceandrea, I tried with a fresh profile and it worked.

**Comment by agiudiceandrea** [comment]
Thanks for checking. So the issie may be related to some external plugin or some non default setting, not to QGIS itself.
