### ISSUE TITLE
Unwanted expression behaviour in rule-based symbology (colour fill)

### ISSUE THREAD

**Issue by rjstapel** [qgis/QGIS#53339]
### What is the bug or the crash?

When I apply the following rule to change the colour of a polygon based on the presence of a string (e.g. 'BE') in a value (field: "ADM1"), the colour is not applied, and the standard colour of the symbol is applied instead. There seems to be a hierarchy in terms of the content of a string: in grouped expressions like the ones below, it happens only with one type of string, in this case 'BE'. 

It seems to be new QGIS behaviour (perhaps since updating to the latest QGIS version 3.30.3, but I'm not sure).

### Steps to reproduce the issue

In the symbology tab of a polygon layer with a variable "ADM1" and at least some values that start with 'BE', 'OV', and 'AR', create an empty rule. No filter needs to be selected, but select the standard filling, then change the filling colour using an expression.

Select the following expression: 
CASE WHEN "ADM1" LIKE 'BE%' THEN '#﻿000000' ELSE '#AAAAAA' END 

Result for polygons for which "ADM1" starts with 'BE': '#08AAAAA' (i.e. the predefined colour, which is not overwritten by the expression to '#000000). 
For all other polygons the result is, as intended, '#AAAAAA'. 

If we apply the same expression, but with multiple if-statements:
CASE WHEN "ADM1" LIKE 'OV%' THEN '#﻿000000' ELSE 
CASE WHEN "ADM1" LIKE 'AR%' THEN '#888888' ELSE '#AAAAAA' END END

The same happens with the value 'OV%'. Adding if-statements, will result in just one type of string being affected.

### Versions

QGIS-versie | 3.30.3-'s-Hertogenbosch | QGIS code revisie | 2411cec112
-- | -- | -- | --
Qt versie | 5.15.2
Python versie | 3.9.5
GDAL/OGR versie | 3.3.2
PROJ versie | 8.1.1
EPSG-register databaseversie | v10.028 (2021-07-07)
GEOS versie | 3.9.1-CAPI-1.14.2
SQLite versie | 3.35.2
PDAL versie | 2.3.0
PostgreSQL client versie | unknown
SpatiaLite versie | 5.0.1
QWT versie | 6.1.6
QScintilla2 versie | 2.11.5
OS versie | macOS 13.4
  |   |   |  
Actieve Python plug-ins
VectorBender | 0.2.1
splitmultipart | 1.0.0
polygon_linker | 0.9.6.1
refFunctions | 1.6
qgis2web | 3.16.0
mmqgis | 2021.9.10
processing | 2.12.99
otbprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

QGIS-versie
3.30.3-'s-Hertogenbosch
QGIS code revisie
[2411cec112](https://github.com/qgis/QGIS/commit/2411cec112)
Qt versie
5.15.2
Python versie
3.9.5
GDAL/OGR versie
3.3.2
PROJ versie
8.1.1
EPSG-register databaseversie
v10.028 (2021-07-07)
GEOS versie
3.9.1-CAPI-1.14.2
SQLite versie
3.35.2
PDAL versie
2.3.0
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.11.5
OS versie
macOS 13.4

Actieve Python plug-ins
VectorBender
0.2.1
splitmultipart
1.0.0
polygon_linker
0.9.6.1
refFunctions
1.6
qgis2web
3.16.0
mmqgis
2021.9.10
processing
2.12.99
otbprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Try with: `CASE WHEN "ADM1" LIKE 'BE%' THEN '#000000' ELSE '#AAAAAA' END`
It seems to me there is an issue in your string: it contains a spurious non displayed character.

**Comment by rjstapel** [comment]
Thanks, I wouldn't have spotted this. It works like a charm now (and I spotted the character in the original expression).
