### ISSUE TITLE
Plugin search bar not work

### ISSUE THREAD

**Issue by Korto19** [qgis/QGIS#53332]
### What is the bug or the crash?

Plugin search bar not work

### Steps to reproduce the issue

1. Go to plugin window installer
2. type any in search bar
3. nothing happens

### Versions

QGIS
3.31.0-Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
May be a side effect of https://github.com/qgis/QGIS/pull/53273.
