### ISSUE TITLE
Warnings/Errors when using qgis_process in OSGeo4W Shell `QTemporaryDir: Unable to remove "...\\AppData\\Local\\Temp\\QGIS3-SpndYs" most likely due to the presence of read-only files`

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#53340]
### What is the bug or the crash?

Warnings/Errors when using qgis_process in OSGeo4W Shell `QTemporaryDir: Unable to remove "...\\AppData\\Local\\Temp\\QGIS3-SpndYs" most likely due to the presence of read-only files`

![image](https://github.com/qgis/QGIS/assets/53625184/570b52d4-df7d-4660-b43a-aec69f6567c8)

### Steps to reproduce the issue

Open OSGeo4W Shell. Run the qgis_process-qgis command with any option
```sh
$ qgis_process-qgis --help
```

### Versions

QGIS version
3.28.7-Firenze
QGIS code revision
fedae0eb52
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 1909

Active Python plugins
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
Thanks for reporting. The issue has been already reported at https://github.com/qgis/QGIS/issues/53034.
