### ISSUE TITLE
segfault upon exitting python: qgis@3.28 and QgsProject

### ISSUE THREAD

**Issue by Sinan81** [qgis/QGIS#53344]
### What is the bug or the crash?

```
$ python
Python 3.8.12 (default, Feb 16 2023, 01:53:00) 
[GCC 7.5.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsProject
>>> test = QgsProject.instance()
Application path not initialized
Application path not initialized
Application path not initialized
Application path not initialized
Application path not initialized
>>> exit()
Segmentation fault
```

### Steps to reproduce the issue

See above.
However, no issues with qgis@3.22.16.

### Versions

see above.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by nyalldawson** [comment]
This is expected -- you need to correctly initialise the QgsApplication before you can use the pyqgis classes
