### ISSUE TITLE
Create Print Layout dialog box blank

### ISSUE THREAD

**Issue by nbonharper** [qgis/QGIS#53382]
### What is the bug or the crash?

I recently updated from 3.22.11 to 3.30.3
When using layout manager to create a new print layout the 'create print layout' dialog box is blank:
![image](https://github.com/qgis/QGIS/assets/135713983/c712045a-1a59-4670-b630-a3babfd2b0fb)
I have uninstalled and reinstalled 3.30.3 and still have the same problem. I have installed 3.28 and have the same issue.

### Steps to reproduce the issue

Go to Layout Manager
Click on 'Create'
Create Print Layer dialog box opens but is blank

I just tried to create a new profile and the New Profile Name dialog box is also blank!
![image](https://github.com/qgis/QGIS/assets/135713983/52ebebf3-ebad-471e-9d44-dd55ff0db76c)

### Versions

QGIS version
3.28.7-Firenze
QGIS code revision
fedae0eb52
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
cartography_tools
1.2.1
clipper
1.2
BezierEditing
version 1.3.2
contour
2.0.8
coordinator
0.4
csv_tools
0.7.2
DigitizingTools
1.5.1
DistroMap
1.0.0
ee_plugin
0.0.4
FeatureGridCreator
3.0.0
FreehandRasterGeoreferencer
0.8.3
Generalizer3
1.0
GeometryShapes
0.7
GeoTrace
1.33
ImportPhotos
3.0.3
joinmultiplelines
Version 0.4.1
kmltools
3.1.16
LandXml
2.2
LAStools
1.4
MagicWand-master
1.3.1
nominatim
1.4.1
openlayers_plugin
2.0.0
polystrip
3.0.1
processing_saga_nextgen
0.0.7
profiletool
4.2.2
QGISSortAndNumber-master
1.0
qgis_resource_sharing
0.16.0
qgsAzimuth
0.9.15
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.28
raster_tracer
0.3.2
rectanglify
1.0.3
shapetools
3.4.3
spline
0.2
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
CustomToolBar
1.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to the roadmap.

### New profile

- [X] I tried with a new QGIS profile

**Comment by agiudiceandrea** [comment]
It seems to me the issue doesn't occur on my Windows system using either QGIS 3.28.7 or QGIS 3.30.3 (OSGeo4W).
Could you please try if the issue does occur also creating and using a new QGIS user profile?

**Comment by DelazJ** [comment]
> I just tried to create a new profile and the New Profile Name dialog box is also blank!

@nbonharper Go to your user profile folder (path is mentioned at https://docs.qgis.org/3.28/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), rename the `default` folder and restart QGIS. QGIS should recreate a new user profile for you
