### ISSUE TITLE
HDPI / tablet / pen / Gnome: pointer off by 5 mm, not able to open menu

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#53406]
### What is the bug or the crash?

@nyalldawson testing with current master on hdpi tablet with pen (ThinkPad X1 Tablet Gen3, display 3000*2000), the cursor is off by about 5mm. I'm not able to create a screenshot as that dit not show the cursor.

But I tested with a fresh compiled master versus the Flatpak 3.28/3.30 version in X scale 200% (Debian Testing, Gnome 43)

In the Flatpak version the pen is working fine, but in master it looks like something is wrong with an offset.
If I click on the menu bar (I see the cursor is above the menu), the buttons below it are activated...
Note: the mouse is behaving OK and the pen is working fine in the flatpak version and in other applications... (is there another Qt app I can use to test?)

I can do some more testing, but maybe easier to show in some meeting in which I share the desktop? (unless you have hardware yourself)...

### Steps to reproduce the issue

Put scaling on 200% 
Open QGIS and try to use the pen to navigate

### Versions

QGIS version | 3.31.0-Master | QGIS code revision | eb7cd8ad9f
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4

QGIS version | 3.30.1-'s-Hertogenbosch | QGIS code branch | Release 3.30
-- | -- | -- | --
Qt version | 5.15.9
Python version | 3.10.6
GDAL/OGR version | 3.6.4
PROJ version | 9.2.0
EPSG Registry database version | v10.082 (2023-02-06)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.36.0
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | KDE Flatpak runtime
  |   |   |  

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rduivenvoorde** [comment]
It is NOT depending on scaling, tested 100, 200 and 300%.

Ok, it's Qt(5)? related... I installed Dolphin (KDE file browser) and it has the same issue :-(

**Comment by rduivenvoorde** [comment]
Tested on Windows (downloaded a Test artifact from current master), and there the pen is working fine

**Comment by m-kuhn** [comment]
> Ok, it's Qt(5)? related... I installed Dolphin (KDE file browser) and it has the same issue :-(
> Also installed Scribus and Feecad and these behaves just like QGIS (with pen, mouse is OK)

Looks like this is better reported on debian or qt?

**Comment by rduivenvoorde** [comment]
@m-kuhn yes probably, and also it will be hopefully fixed when going to next Qt.
Will close this one (I first thought it was related to the HDPI work of @nyalldawson, he asked to do some testing)
