### ISSUE TITLE
QgsProcessingParameterEnum with allowMultiple does not show staticStrings

### ISSUE THREAD

**Issue by ztgis** [qgis/QGIS#53420]
### What is the bug or the crash?

Using `allowMultiple=True` and `usesStaticStrings=True` at QgsProcessingParameterEnum does not show any strings (checkbox labels)) in the algorithm dialog.

Currently, `usesStaticStrings=True` only works if `allowMultiple=False`

### Steps to reproduce the issue

Create a processing parameter like this:

```
QgsProcessingParameterEnum(
    self.KENNZIFFER,
    self.tr('Kennziffer'),
    kennziffern,
    allowMultiple=True,  -- set to True
    optional=False,
    usesStaticStrings=True  -- set to True
)
```

Open the algorithm in QGIS
Choose multiple options of the enum parameter within the [...] button
All enum options are listed with the checkbox without a (static) string label

### Versions

QGIS-Version
3.30.0-'s-Hertogenbosch
QGIS-Codeversion
f186b8efe0e
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.2
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.041 (2021-12-03)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
changeDataSource
3.1
Mergin
2023.1
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
qgiscloud
3.8.5
QuickOSM
2.2.2
slyr_community
5.0.0
StreetView
3.2
processing
2.12.99
ztgis-tools
0.6
ztgis-tools-addon
0.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Please check if the issue does occur also using QGIS 3.30.2: PR https://github.com/qgis/QGIS/pull/52143 (backported to 3.30.2) may be related. Please also see if the thread at https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg54815.html could be of some help.

**Comment by ztgis** [comment]
Updating to QGIS 3.30.3 fixes the issue. Thank you for your support.
