### ISSUE TITLE
Crash when running Topology Checker to validate corrective edits.

### ISSUE THREAD

**Issue by ericvmai** [qgis/QGIS#53425]
### What is the bug or the crash?

I've had QGIS crash several times when trying to re-run the Topology Checker after manually correcting overlaps. I'm running into this issue constantly. Both occurs when trying to Validate All and Validate Extent.

### Steps to reproduce the issue

Go to Topology Checker
Set rules
Validate all
Enter edit session to correct overlaps.
Save edits.
Run Topology Checker to verify that edits resolved the topology error.
Process hangs for a bit then crashes the entire program.
Sometimes a crash report comes up and sometimes it doesn't

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lbartoletti** [comment]
Please, can you provide data and project?

**Comment by troopa81** [comment]
I failed to reproduce the issue on master and 3.28 with my own dataset. 

Please provide a dataset (or a subset) with a project sample so we could reproduce and fix

**Comment by DrRichLangford** [comment]
Thanks for your ongoing interest in this issue. Unfortunately, or not, a subset of the data works without issue. I believe that it is simply a function of the size of the dataset and the number of errors. The file is over 100Mb in size and had at least 675 errors. I alerted Andrea Giudiceandrea to this, and believe that it is simply a function of my computer power, software (win10), file size and number of errors. However, if you want a very large file to check it out I can use Dropbox or similar to get it to you.

**Comment by Jesterface23** [comment]
I am having a similar issue after updating QGIS and checking for overlapping in a layer. The first validation is fine and second crashes QGIS.
I ended up installing QGIS version 3.28.13-2 and it works fine. Then I installed version 3.30.0-1 and the issue mentioned above begins.

Here is a data source with overlapping, mz19se23.zip. https://www.weather.gov/gis/MarineZones

**Comment by pip31** [comment]
Having the same issue. Second validation crashes QGIS. Small subset of data works fine.
Running win11, 32Gb RAM, i7 so computer shouldn't be the issue.


regards 
Stefan


QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.5
PROJ version | 9.4.0
EPSG Registry database version | ()
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
  |   |   |  
Active Python plugins
AzimuthMeasurement | 0.2.2
chinesepostman | 0.3.0
chm_from_lidar-master | 0.10
clipper | 1.2
Coordtransform | 1.1
csv_tools | 0.7.2
DataDrivenInputMask | 2.5.0
DigitizingTools | 1.5.2
excel_sync | 3.6
geosys-plugin | 1.3.0
GroupStats | 2.2.7
HCMGIS | 24.1.12
latlontools | 3.6.20
pickLayer | 3.9.12
profiletool | 4.2.6
qfieldsync | v4.9.1
qgis-plugin-findreplace-main | 1
qgis_easy_query | 1.0.4
QuickMultiAttributeEdit3 | version 3.0.3
quick_map_services | 0.19.34
rvt-qgis | 0.9.6
searchlayers | 3.0.16
SentinelHub | 2.0.2
open_lidar_tools | 2.2.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.1-Maidenhead
QGIS code revision
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
()
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009




Active Python plugins
AzimuthMeasurement
0.2.2
chinesepostman
0.3.0
chm_from_lidar-master
0.10
clipper
1.2
Coordtransform
1.1
csv_tools
0.7.2
DataDrivenInputMask
2.5.0
DigitizingTools
1.5.2
excel_sync
3.6
geosys-plugin
1.3.0
GroupStats
2.2.7
HCMGIS
24.1.12
latlontools
3.6.20
pickLayer
3.9.12
profiletool
4.2.6
qfieldsync
v4.9.1
qgis-plugin-findreplace-main
1
qgis_easy_query
1.0.4
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.34
rvt-qgis
0.9.6
searchlayers
3.0.16
SentinelHub
2.0.2
open_lidar_tools
2.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by DrRichLangford** [comment]
Thanks to those who have also highlighted this small problem, and apologies for letting it go stale. The problem map is a 133Mb shapefile with 31,000 polygons. Running on a clean version of the whole dataset there are no gaps, invalid or multipart geometries. Running on an old version with 1000s of gaps causes a crash. My workaround, now using 3.34.5, is Check Geometries and a lot of manual editing, as the Topology Checker is nice to have, but doesn't actually fix anything. The crash is a good indication that I am dealing with a very poor dataset that needs work.
