### ISSUE TITLE
Model help editor adds unwanted HTML content for ALG_DESC and EXAMPLES

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#53435]
### What is the bug or the crash?

So it's not possible to create a help without `ALG_DESC` nor it's possible to remove the `EXAMPLES` section by deleting it's content.

<img src="https://github.com/qgis/QGIS/assets/20856381/e239aa2f-5d41-4325-b42f-f2a827048443" width="500px" />

### Steps to reproduce the issue

1. Create a model with QGIS model designer
2. From the top menu _Model_ -> _Edit Model Help..._
3. Click on _Examples_
<img src="https://github.com/qgis/QGIS/assets/20856381/ead45989-5d34-4101-bc51-f086511f66dc" width="300px" /><br>
4. Click OK
5. Run model -> see error, unwanted HTML content for ALG_DESC anf EXAMPLES:  `p, li { white-space: pre-wrap; }`
6. Open the model with a text editor:
![image](https://github.com/qgis/QGIS/assets/20856381/2fdfc4a4-a5b2-4cb9-8ce9-e8520790772f)

### Versions

QGIS version | 3.31.0-Master | QGIS code revision | 5ba50d8f84
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Looks like this is related to the use of rich text edit (`QgsRichTextEditor`) for `ALGORITHM_DESCRIPTION` and `ALGORITHM_EXAMPLES`:
 
https://github.com/qgis/QGIS/blob/1f2bd72b9d19b6b24c7074adb99b4304e759e77c/src/gui/processing/qgsprocessinghelpeditorwidget.cpp#L163

**Comment by alexbruy** [comment]
Duplicates #/53036.
