### ISSUE TITLE
Legend not updating dynamically when using an atlas

### ISSUE THREAD

**Issue by NadegeOdonat** [qgis/QGIS#53442]
### What is the bug or the crash?

When inserting dynamic values in a symbology (in my case dyamic ranges for a color scale), the maps are behaving correctly. However when the legend is filled dynamically, either in the symbology or in the legend object directly on the map, the text displayed does not update, and keeps showing the ranges for the first atlas feature. The title is correctly refreshed, but the items legends stay stuck. Trying to force a refresh by applying a change (adding a space for example) doesn't do anything either.

(also, yes, I'm aware that it's bad practice to have the same color represent different ranges on similar maps, but I have good reasons to do so)

### Steps to reproduce the issue

**1. Create an atlas table (in my case in Open office). Here I put my data name (gp_tax), and three values to generate the ranges** (s1, s2, s3)
![Atlas fields](https://github.com/qgis/QGIS/assets/136347010/1afe4b7d-26d9-4baf-90e2-6c0ca30c3579)

**2. Create the symbology using the @atlas_feature attributes**
![Raw atlas layer](https://github.com/qgis/QGIS/assets/136347010/6d43a11f-e108-4953-afd4-650df7367b6c)

**3. Create your map layout, generate an atlas, and add a legend. Make sure it's named dynamically (obviously)**
![Raw legend labels](https://github.com/qgis/QGIS/assets/136347010/f2c197b2-e3df-423f-93f6-da832aca2d9f)

**4. Check how the legend look on the first feature. Everything looks just right**
![Legend on 1rst atlas item](https://github.com/qgis/QGIS/assets/136347010/96e05c54-45aa-46aa-9245-e2a545ce14cc)

**5. Check how the legend look on the next features. While the map is behaving correctly and the legend title refresh properly, the items don't update and keep displaying the first ranges**
![Legend on 2nd atlas item](https://github.com/qgis/QGIS/assets/136347010/611e712a-fb26-499e-a25b-7772ad5ccd5f)

### Versions

QGIS version
3.28.6-Firenze
QGIS code revision
868c9fa03b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
dataexplorer
3.1.1
datagrandest
2.01
DataPlotly
4.0.0
lizmap
3.14.0
QuickOSM
2.2.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
And when you export, the output is as in the preview? Just wanted to check whether the issue is not only at preview level...

**Comment by NadegeOdonat** [comment]
I don't know what changed but today, on the same project with updated layers on a very similar atlas, the legend labels do not show any of the dynamic numbers, and neither does the pdf output.

![image](https://github.com/qgis/QGIS/assets/136347010/c8f75ce1-19f3-4e06-a1ca-f94531f59f95)

 I've checked in the assistant that the correct value is outputed by the expression, and it does.
![image](https://github.com/qgis/QGIS/assets/136347010/5768fafe-368b-4ae0-a82f-c5ce9527aa30)


I'm now a confused geomatician. And contrary to what I said earlier the bug is **not just at preview level**
