### ISSUE TITLE
Save Feature as.. creates files with unknown CRS

### ISSUE THREAD

**Issue by mjohenneken** [qgis/QGIS#53469]
### What is the bug or the crash?

I experienced issues with calculating "Distance to nearest hub(points)" where the resulting distances were all NaN. I quickly found that this was caused by the temporary point layers having an unkown CRS. To fix that i followed the advice to save the layers with the "Save Feature As.." action in the Context Menu > Export. This usually allows you to set the appropriate CRS in the file metadata. I also tried "Reproject Layer". However when opening these files in QGIS they still had an unknown CRS. 

**Issue**: In this situation its not possible to use the layers for any calculations basically. 

I investigated more and found a solution for my specific setup eventually. 
First, I had an install, i think it was QGIS 3.22 RC. I reinstalled QGIS 3.26.3 via the Debian LTR Channel on Linux Mint 20.2.
This didn't help. While running gdalinfo i noticed that gdal was complaining about a missing column 
`no such column: area_of_use_auth_name` in proj.db in one of the files. I checked the versions an noticed that proj-data 7.3 was installed via apt. I installed proj-data 6.3.1-1 which fixed the erros in the gdalinfo output and now QGIS can save the CRS to the file again.

I'm not sure whether this was a specific issue of my system environment, a missing dependency constraint between proj and proj-data or something down the line.

I raise the issue within QGIS because the issue was caused by installing it and using it.  

Possible solutions: 
- add version constraint between proj and proj-data
- QGIS should consider error messages raised by gdal and inform the user that something is going wrong with the environment or its dependencies either when writing the file or when reading it with an unknown CRS 

### Steps to reproduce the issue

1. Create a tempoary point layer with a couple points and save it "Make Permanent". 
2. Remove layer 
3. Add layer; Observe that it has an unknown CRS
4. Right click on layer, Export > Save Feature As; Set CRS (I used EPSG:25832), save to a new shapefile
5. Remove layer 
6. Add layer; Observe that it  has unkown CRS

### Versions

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdad
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.9.1-CAPI-1.14.2
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Linux Mint 20.2

Active Python plugins
MetaSearch
0.3.6
grassprovider
2.12.99
sagaprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Did you install QGIS using qgis.org repository as described [here](https://www.qgis.org/fr/site/forusers/alldownloads.html#debian-ubuntu) ?

**Comment by agiudiceandrea** [comment]
@nicogodet @mjohenneken, Linux Mint 20.2 is based on Ubuntu 20.04; the latest available QGIS version for Ubuntu 20.04 on qgis.org is 3.26 https://qgis.org/en/site/forusers/alldownloads.html#id13. So... QGIS 3.26 is no longer supported and thus Linux Mint 20 / Ubuntu 20.04 is no longer supported.

**Comment by mjohenneken** [comment]
> @nicogodet @mjohenneken, Linux Mint 20.2 is based on Ubuntu 20.04; the latest available QGIS version for Ubuntu 20.04 on qgis.org is 3.26 https://qgis.org/en/site/forusers/alldownloads.html#id13. So... QGIS 3.26 is no longer supported and thus Linux Mint 20 / Ubuntu 20.04 is no longer supported.

Oh that is sad to hear. Linux Mint 20 and Ubutu 20.04 still has 2 years of support in LTS. That means every user with that OS won't be able to get a supported version of QGIS for 2 years. Is it planned to release 3.28 for focal?

**Comment by nicogodet** [comment]
> Is it planned to release 3.28 for focal?

No. Qt is too old in Focal, QGIS require 5.13 now and 5.12 is shipped in Focal...

**Comment by agiudiceandrea** [comment]
@mjohenneken you could use QGIS from Flatpak https://www.qgis.org/en/site/forusers/alldownloads.html#flatpak
