### ISSUE TITLE
Deynamic Temporal Control not working with ERSI SHP files in new project

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#53471]
### What is the bug or the crash?

I exported a bunch of layers as ESRI shapefiles and styles as QLDs from a project stored in PostGIS  to take with me on a trip rather than accessing over the Internet.

I created a clean project, then added the exported shapefiles and set their styles from the exported *.qld files. The styles had the dynamic temporal control settings in them, but they do not obey the DTC.

I tried turning the DTC off for each layer, saving the style, exiting QGIS, restarting QGIS and reloading the project, turning DTC back on, to no avail. I tried that with 3.22.16, 3.28, and 3.30, none of them worked.

Weirdly, the very same shapefiles do obey the DTC if loaded as layers in the original project saved in the PostGIS database.

[project.zip.aa.gz](https://github.com/qgis/QGIS/files/11752084/project.zip.aa.gz)
[project.zip.ab.gz](https://github.com/qgis/QGIS/files/11752085/project.zip.ab.gz)
[project.zip.ac.gz](https://github.com/qgis/QGIS/files/11752088/project.zip.ac.gz)
[project.zip.ad.gz](https://github.com/qgis/QGIS/files/11752090/project.zip.ad.gz)
[project.zip.ae.gz](https://github.com/qgis/QGIS/files/11752091/project.zip.ae.gz)

### Steps to reproduce the issue

1. download the files attached above
2. gunzip them
3. piece the zip file back together, on un*x do `cat project.zip.a* >project.zip`
4. make new directory and copy the zip file to it
5. unzip the zipfile
6. start QGIS and load the project `bop.qgz`

### Versions

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code revision
738df48978
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

This copy of QGIS writes debugging output.

Active Python plugins
quick_map_services
0.19.33
buffer_without_overlaps
0.2
splitmultipart
1.0.0
debug_vs
0.7
IPyConsole
version 2.0
naficp
1.0
GroupStats
2.2.7
QuickOSM
2.2.2
otbprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
I can't reproduce -- loading the attached project and then switching on the temporal controller results in the correct features being shown for me.

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (9b2c94e2e34b9d61c809b133887c3b45188156ae).
