### ISSUE TITLE
Scale bar invisible when using cusom CRS

### ISSUE THREAD

**Issue by Daafip** [qgis/QGIS#53475]
### What is the bug or the crash?

I was using a custom CRS in luxembourg, when adding a scalebar to the layout I didnt configure it properly in the first instance. This means it is invisble, but does appear on the printed version. 

maybe little niche but would be nice to be able to select all object in the printlayout: another layer pannel for example. 

### Steps to reproduce the issue

1. Load custom CRS, e.g. 
    > `PROJCRS["unnamed",BASEGEOGCRS["Unknown datum based upon the International 1924 ellipsoid",DATUM["Not specified (based on International 1924 ellipsoid)",ELLIPSOID["International 1924",6378388,297.000000000005,LENGTHUNIT["metre",1]]],PRIMEM["Greenwich",0,ANGLEUNIT["degree",0.0174532925199433]],ID["EPSG",4022]],CONVERSION["Transverse Mercator",METHOD["Transverse Mercator",ID["EPSG",9807]],PARAMETER["Latitude of natural origin",49.8333333333333,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8801]],PARAMETER["Longitude of natural origin",6.16666666666667,ANGLEUNIT["degree",0.0174532925199433],ID["EPSG",8802]],PARAMETER["Scale factor at natural origin",1,SCALEUNIT["unity",1],ID["EPSG",8805]],PARAMETER["False easting",80000,LENGTHUNIT["metre",1],ID["EPSG",8806]],PARAMETER["False northing",100000,LENGTHUNIT["metre",1],ID["EPSG",8807]]],CS[Cartesian,2],AXIS["easting",east,ORDER[1],LENGTHUNIT["metre",1,ID["EPSG",9001]]],AXIS["northing",north,ORDER[2],LENGTHUNIT["metre",1,ID["EPSG",9001]]]]`
3. create a print layout
4. add a scale bar & leave default
5. close the print layout, change the crs & renter. 
6. When you export as image it shows up but not in the print layout

in the editor:
![image](https://github.com/qgis/QGIS/assets/59128851/6a4245ae-31e0-493c-b518-70d2d58c2f45)
Exported 
![mechelbach_overview_river_segment_Measurement locations](https://github.com/qgis/QGIS/assets/59128851/0dcf0df1-c9e8-4eaf-8019-a0ed36535b82)

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
flowTrace
1.1.1
LAStools
1.4
pdokservicesplugin
4.1.3
points_to_catchments
0.1
qdraw
3.0.2
qgis2web
3.16.0
qgistim
0.1
SelectWithin
0.4
SRTM-Downloader
3.1.17
valuetool
3.0.15
vector_tiles_reader
3.2.2
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
This seems similar to https://github.com/qgis/QGIS/issues/46060.

**Comment by DelazJ** [comment]
> maybe little niche but would be nice to be able to select all object in the printlayout: another layer pannel for example

@Daafip Is this not doable with the [items panel](https://docs.qgis.org/3.28/en/docs/user_manual/print_composer/overview_composer.html#the-items-panel)?

**Comment by Daafip** [comment]
Oh right, that does it.
Still weird its completely invisible but this is a work around. Thanks!

**Comment by alexbruy** [comment]
Duplicates #46060.
