### ISSUE TITLE
Impossible to see a point cloud in 3D map

### ISSUE THREAD

**Issue by sigmoe** [qgis/QGIS#53483]
### What is the bug or the crash?

For one specific point cloud, we can see it in the canvas, but it's impossible to view in 3D in the 3D map.

### Steps to reproduce the issue

Load the the specific point cloud (laz)
Activate RVB in the 3D symbology
Open a 3D map
Try to view the point cloud in the 3D map -> the 3D map is empty

### Versions

Version de QGIS
3.28.7-Firenze
Révision du code
fedae0eb52
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.0
Version de Proj
9.2.0
Version de la base de données du registre EPSG
v10.082 (2023-02-06)
Version de GEOS
3.11.2-CAPI-1.17.2
Version de SQLite
3.41.1
Version de PDAL
2.5.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
cadastre
1.17.3
SgmDxfImportPro
3.28.22
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
[extrait pointcloud.copc.zip](https://github.com/qgis/QGIS/files/11762328/extrait.pointcloud.copc.zip)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The problem occurs only with one specific file (the file attached)

**Comment by alexbruy** [comment]
Both suggestions from the previous comment work fine. Probably this can be closed.

**Comment by sigmoe** [comment]
Yes, the suggestion works.
