### ISSUE TITLE
QGIS 3.31 - Point Clouds - Export to raster - multithread processing failed on final stage

### ISSUE THREAD

**Issue by lieti** [qgis/QGIS#53487]
### What is the bug or the crash?

When multithread algorithms (same issue for _Export to raster by using triangulation_) are used it will crash on final stage of process on stitching raster tiles togehter.

### Steps to reproduce the issue

1. Select COPC file for Point Clouds - Export to raster (sample is [here](https://drive.google.com/file/d/1ID5smJxdMHKM3wBS0ohj3Y-IOOLyhYED/view?usp=sharing))
2. Set or keep tile size (in my case 500 because AOI is relatively small)
3. run tool

### Versions

QGIS version
3.31.0-Master
QGIS code revision
8e1a12b921
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.8.0dev-818e536b10
Running against GDAL/OGR
3.8.0dev-931a57a19c
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
changeDataSource
3.1
FreehandRasterGeoreferencer
0.8.3
HCMGIS
23.2.1
latlontools
3.6.9
nominatim
1.4.5
profiletool
4.2.5
rvt-qgis
0.9.6
wbt_for_qgis
1.0.9
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

All folders from error log are empty

error log:
`QGIS version: 3.31.0-Master
QGIS code revision: 8e1a12b921
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.8.0dev-931a57a19c
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.1, June 1st, 2023
PDAL version: 2.5.3 (git-version: 7ec4e6)
Algorithm started at: 2023-06-16T13:57:13
Algorithm 'Export to raster' starting…
Input parameters:
{ 'ATTRIBUTE' : 'Z', 'FILTER_EXPRESSION' : '', 'FILTER_EXTENT' : None, 'INPUT' : 'H:/My Drive/___Trabajo23/230324_PUSR_Hrady/__OUTPUTS_preliminar/BB-HradMuran/PointClouds/BB-HradMuran.copc.laz', 'ORIGIN_X' : None, 'ORIGIN_Y' : None, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RESOLUTION' : 1, 'TILE_SIZE' : 500 }

wrench command: C:/OSGeo4W/apps/qgis-dev/./pdal_wrench.exe to_raster "--input=H:/My Drive/___Trabajo23/230324_PUSR_Hrady/__OUTPUTS_preliminar/BB-HradMuran/PointClouds/BB-HradMuran.copc.laz" --output=F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07/OUTPUT.tif --attribute=Z --resolution=1 --tile-size=500 --threads=16
0....10....20....30....40....50....60....70....80....90....100 - done. 
Warning 1: Can't open F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07\OUTPUT\0_0.tif. Skipping it 
Warning 1: Can't open F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07\OUTPUT\1_0.tif. Skipping it
Warning 1: Can't open F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07\OUTPUT\0_1.tif. Skipping it
Warning 1: Can't open F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07\OUTPUT\1_1.tif. Skipping it

Process completed successfully
Execution completed in 26.09 seconds
Results:
{'OUTPUT': 'F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07/OUTPUT.tif'}

Loading resulting layers
The following layers were not correctly generated.
• F:/x_TMP/processing_aoNyEQ/8d905a87ac0e4b33b706317baac99e07/OUTPUT.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

**Comment by wonder-sk** [comment]
Hmm unfortunately I am unable to reproduce this (tested on linux). If you try to run it multiple times, does it always end up like this?
