### ISSUE TITLE
QGIS 3.31 - Point Clouds - Export to raster - problem with nonstandard character (spaces?) on TMP path

### ISSUE THREAD

**Issue by lieti** [qgis/QGIS#53488]
### What is the bug or the crash?

If the path to TMP file in windows contain non standard character (spaces?)  _export to raster_ function will not run.

After changing of  TMP folder location it almost work (see [#53487](https://github.com/qgis/QGIS/issues/53487)) 

### Steps to reproduce the issue

1. Select COPC file for Point Clouds - Export to raster (sample is [here](https://drive.google.com/file/d/1ID5smJxdMHKM3wBS0ohj3Y-IOOLyhYED/view?usp=sharing))
2. Have weird windows profile name (with spaces)
3. Run...

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.31.0-Master | QGIS code revision | 8e1a12b921
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
Compiled against GDAL/OGR | 3.8.0dev-818e536b10 | Running against GDAL/OGR | 3.8.0dev-931a57a19c
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.31.0-Master
QGIS code revision
[8e1a12b921](https://github.com/qgis/QGIS/commit/8e1a12b921)
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.8.0dev-818e536b10
Running against GDAL/OGR
3.8.0dev-931a57a19c
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

QGIS version: 3.31.0-Master
QGIS code revision: 8e1a12b921
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.8.0dev-931a57a19c
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.1, June 1st, 2023
PDAL version: 2.5.3 (git-version: 7ec4e6)
Algorithm started at: 2023-06-16T14:07:05
Algorithm 'Export to raster' starting…
Input parameters:
{ 'ATTRIBUTE' : 'Z', 'FILTER_EXPRESSION' : '', 'FILTER_EXTENT' : None, 'INPUT' : 'C:/__PIESKOVISKO/BB-HradMuran.copc.laz', 'ORIGIN_X' : None, 'ORIGIN_Y' : None, 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RESOLUTION' : 1, 'TILE_SIZE' : 500 }

wrench command: C:/OSGeo4W/apps/qgis-dev/./pdal_wrench.exe to_raster --input=C:/__PIESKOVISKO/BB-HradMuran.copc.laz "--output=C:/Users/Xxxxxxxý Xxxxx/AppData/Local/Temp/processing_uMEOLh/02b82ddc8c2d4ddcb112ffbf376da4ff/OUTPUT.tif" --attribute=Z --resolution=1 --tile-size=500 --threads=16

Process was unexpectedly terminated
Execution failed after 1.24 seconds

Loading resulting layers
Algorithm 'Export to raster' finished

**Comment by nicogodet** [comment]
`"--output=C:/Users/Xxxxxxxý Xxxxx/AppData/Local/Temp/processing_uMEOLh/02b82ddc8c2d4ddcb112ffbf376da4ff/OUTPUT.tif"`
I think it should be
`--output="C:/Users/Xxxxxxxý Xxxxx/AppData/Local/Temp/processing_uMEOLh/02b82ddc8c2d4ddcb112ffbf376da4ff/OUTPUT.tif"`

**Comment by alexbruy** [comment]
Does this work when using wrench directly?

**Comment by radim-ek** [comment]
I found a problem if you have a "ěščřžýáí" in a path LAZ not open. If you open from path without diacritics all is OK.
OK: D:\SomePath\Without\something.laz
FAIL: D:\SomePath\With_a_ěščřžýáí\something.laz

So, because you use username with diacritics "output=C:/Users/Xxxxxxxý Xxxxx", export fail. You need to set PATH to other TEMP folder (without path of diacritcs)
