### ISSUE TITLE
Grids not coming 

### ISSUE THREAD

**Issue by RamanSandhu809** [qgis/QGIS#53498]
### What is the bug or the crash?

Unable to add grids (columns) in the map. Also facing Bugs that if I add three maps in the New project all gone be the same Even if I locked map 1 and add another. After refreshing every map gone same.

### Steps to reproduce the issue

<img width="1280" alt="Screen Shot 2023-06-18 at 8 40 17 PM" src="https://github.com/qgis/QGIS/assets/137027048/47cd26f5-9af6-40b1-af10-cf155ca64816">

### Versions

3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Please solve it as soon as possible.

**Comment by nicogodet** [comment]
Not reproducible here 
![image](https://github.com/qgis/QGIS/assets/39594821/8233c2db-b97c-46b2-b27d-7ca879b159b0)

Could you describe how to reproduce and settings used for grids ?

> Also facing Bugs that if I add three maps in the New project all gone be the same Even if I locked map 1 and add another. After refreshing every map gone same.

You need to use map theme 
![image](https://github.com/qgis/QGIS/assets/39594821/2b6334f1-bd52-40fc-bdfe-9cd006cc92ab)
Please read user manual for this.

> Please solve it as soon as possible.

Things don't happen "magically". It always needs someone to do the work or contract with someone else to do the work. Once done, it is shared with everybody.
If it is indeed a BUG that is critical for your workflow, feel free to contract a dev or open a Push Request with the fix.
See also http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis/ and http://nyalldawson.net/2016/08/how-to-effectively-get-things-changed-in-qgis-a-follow-up/
