### ISSUE TITLE
QGIS Desktop reports problem with certifcates at frist startup after installation then crashes

### ISSUE THREAD

**Issue by cglebbeek** [qgis/QGIS#53490]
### What is the bug or the crash?

After installation, when QGIS Desktop is started, The program reports a problem with certifcates. It then crashes. When the program is started again the problem does not occur again. The encironement tested are:
- Citrix server
- Windows 10 AVD Image server 

### Steps to reproduce the issue

- intall QGIS choosing standard options
- start QGIS

### Versions

QGIS-versie
3.28.7-Firenze
QGIS code revisie
fedae0eb52
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.7.0
PROJ versie
9.2.0
EPSG-register databaseversie
v10.082 (2023-02-06)
GEOS versie
3.11.2-CAPI-1.17.2
SQLite versie
3.41.1
PDAL versie
2.5.3
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
mmqgis
2021.9.10
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@cglebbeek thanks for reporting. Could you please try if the issue does occur using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?
