### ISSUE TITLE
Output extent (optional): calculate from layer => layer list that cannot be scrolled

### ISSUE THREAD

**Issue by fgfletcher** [qgis/QGIS#53495]
### What is the bug or the crash?

When using
Raster > Conversion > Rasterize (Vector to Raster)
and selecting "Output extent (optional): calculate from layer"
this brings up a full-screen list of layers in the project.

If there are more layers than will fit in the display, there does not appear to be any way to scroll the display to see (nor select) the other (undisplayed) layers.  

### Steps to reproduce the issue

Open a project with a large number of layers (> 200)
select a vector layer
from menu bar: Raster > Conversion > Rasterize (Vector to raster)
at "Output extend (optional)", click on down arrow at right and select "Calculate from layer"
A page will pop up showing a list of all layers in the project, but it will display only as many as it can fit in the page (depends on the window dimensions).
There needs to be a way to scroll the display sideways to show the remaining layers.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.3-'s-Hertogenbosch | QGIS code revision | 2411cec112
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS High Sierra (10.13)
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
slyr_community | 5.0.0
wbt_for_qgis | 1.0.9
GarminCustomMap | 3.4.2
BezierEditing | version 1.3.6
processing_saga_nextgen | 0.0.7
mask | 1.10.2
MBTiles2img | 0.4
MemoryLayerSaver | 5.0.0
parcel_plugin | 3.8
pcraster_tools | 0.2.0
valuetool | 3.0.15
magnetic_bearing_measurement | 0.5
shapetools | 3.4.13
coordinate_capture | 0.2
crayfish | 3.6.0
road_slope_calculator | 0.5
processing | 2.12.99
otbprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
[2411cec112](https://github.com/qgis/QGIS/commit/2411cec112)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS High Sierra (10.13)

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
slyr_community
5.0.0
wbt_for_qgis
1.0.9
GarminCustomMap
3.4.2
BezierEditing
version 1.3.6
processing_saga_nextgen
0.0.7
mask
1.10.2
MBTiles2img
0.4
MemoryLayerSaver
5.0.0
parcel_plugin
3.8
pcraster_tools
0.2.0
valuetool
3.0.15
magnetic_bearing_measurement
0.5
shapetools
3.4.13
coordinate_capture
0.2
crayfish
3.6.0
road_slope_calculator
0.5
processing
2.12.99
otbprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Duplicates #47442. Please search bugtracker before submitting new issue.
