### ISSUE TITLE
Can't allow colliding labels

### ISSUE THREAD

**Issue by Geojim** [qgis/QGIS#53505]
### What is the bug or the crash?

No simple option to display all labels

### Steps to reproduce the issue

Try label dense set of line features. No way to force all labels to be displayed.

### Versions

QGIS version
3.28.7-Firenze
QGIS code revision
fedae0eb52
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
contour
2.0.12
LineDirectionHistogram
3.1.1
SpreadsheetLayers
2.1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
2 ways to easily display them !

![image](https://github.com/qgis/QGIS/assets/39594821/dcd4176a-b9fc-47b1-9408-414c05f63a61)

![image](https://github.com/qgis/QGIS/assets/39594821/a7388957-bef6-4dcc-baac-c868a492bd20)
https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/vector_properties.html#label-toolbar

![image](https://github.com/qgis/QGIS/assets/39594821/834cf3d2-7408-4097-a943-c6300b152625)
https://docs.qgis.org/3.28/en/docs/user_manual/style_library/label_settings.html?highlight=label#label-options

Invalid bug...
