### ISSUE TITLE
QGIS 3.28.7 crash without warning

### ISSUE THREAD

**Issue by RichardClutterbuck** [qgis/QGIS#53510]
### What is the bug or the crash?

QGIS 3.28.7 crash without warning and with no crash report

### Steps to reproduce the issue

Attempt to load vector data in QGIS. This happens when trying to load a Shapefile or open vector data from a GeoPackage. It happens using the Browser and Data Source Manager

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.7-Firenze | QGIS code revision | fedae0eb52
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
Compiled against PROJ | 9.2.0 | Running against PROJ | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.2.7
GeoCoding | 2.19
LAStools | 1.4
profiletool | 4.2.2
qgis-maptiler-plugin | 3.1.1
QGISSortAndNumber-master | 1.0
quick_map_services | 0.19.31
raster_tracer | 0.3.2
realcentroid | 1.0.3
StreetView | 3.2
TerrainShading | 0.9.4
VectorBender | 0.2.1
wbt_for_qgis | 1.0.8
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.7-Firenze
QGIS code revision
[fedae0eb52](https://github.com/qgis/QGIS/commit/fedae0eb52)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
Compiled against PROJ
9.2.0
Running against PROJ
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.2.7
GeoCoding
2.19
LAStools
1.4
profiletool
4.2.2
qgis-maptiler-plugin
3.1.1
QGISSortAndNumber-master
1.0
quick_map_services
0.19.31
raster_tracer
0.3.2
realcentroid
1.0.3
StreetView
3.2
TerrainShading
0.9.4
VectorBender
0.2.1
wbt_for_qgis
1.0.8
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by RichardClutterbuck** [comment]
I'm afraid it happens unpredictably for projects with small vector files (352 KB to 16.59 MB), but some with topological errors: overlapping polygons on one layer. 
I'm afraid I cannot share the data.

The no-warning crash happens when trying to open vector files in the Open Data Source Manager, or the Browser.
 
Yes, it happens with a new profile also. Below are the Version details for this new profile.

Up to 3.28.7 any crash in QGIS resulted in a crash report. No-warning and no report is unusual.



QGIS version | 3.28.7-Firenze | QGIS code revision | fedae0eb52
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
Compiled against PROJ | 9.2.0 | Running against PROJ | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qgis-maptiler-plugin | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.7-Firenze
QGIS code revision
[fedae0eb52](https://github.com/qgis/QGIS/commit/fedae0eb52)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
Compiled against PROJ
9.2.0
Running against PROJ
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
qgis-maptiler-plugin
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by nicogodet** [comment]
Without step to reproduce and/or shared data, I'm afraid this will be hard to fix
Or there is something wrong with your install...

**Comment by RichardClutterbuck** [comment]
When this problem arose I uninstalled QGIS and reinstalled it again. I'm afraid the issue persists. It behaves differently for different profiles: in the older profile I can open the Data Source Manager and load a vector file, but after a short period the programme closes without warning; in the newer profile I try to open the Data Source Manager and the programme closes without warning immediately. I will reinstall the programme again.

**Comment by RichardClutterbuck** [comment]
I have reinstalled QGIS using the OSGeo4 Installer; installed QGIS 3.28.8, the latest LTR. I'm afraid the programme is still shutting down without warning, this time it happened when I try to apply a style to a polygon saved as a vector layer in a GeoPackage. I'm afraid I cannot share the data as it belongs to a client.

Version details here: 

QGIS version | 3.28.8-Firenze | QGIS code revision | 5ac45272b58
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AnotherDXF2Shape | 1.2.7
GeoCoding | 2.19
LAStools | 1.4
profiletool | 4.2.2
qgis-maptiler-plugin | 3.1.1
QGISSortAndNumber-master | 1.0
quick_map_services | 0.19.31
raster_tracer | 0.3.2
realcentroid | 1.0.3
StreetView | 3.2
TerrainShading | 0.9.4
VectorBender | 0.2.1
wbt_for_qgis | 1.0.8
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.8-Firenze
QGIS code revision
[5ac45272b58](https://github.com/qgis/QGIS/commit/5ac45272b58)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
AnotherDXF2Shape
1.2.7
GeoCoding
2.19
LAStools
1.4
profiletool
4.2.2
qgis-maptiler-plugin
3.1.1
QGISSortAndNumber-master
1.0
quick_map_services
0.19.31
raster_tracer
0.3.2
realcentroid
1.0.3
StreetView
3.2
TerrainShading
0.9.4
VectorBender
0.2.1
wbt_for_qgis
1.0.8
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

**Comment by nyalldawson** [comment]
Unfortunately this ticket is currently un-actionable. I'll tag it as needing feedback as it requires some steps or data to reproduce.

**Comment by RichardClutterbuck** [comment]
This issue appears to have resolved itself. I am using QGIS 3.28.5.
