### ISSUE TITLE
Crash when opening SpatiaLite layer from network drive via browser

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#53511]
### What is the bug or the crash?

QGIS crashed - got it only once when trying to open SpatiaLite layer from network drive via browser.

Don't know if the stacktrace is helpful, please close if not.

### Steps to reproduce the issue

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00000308 (most recent call first):

Stack Trace

sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
QgsOgrProviderUtils::getLayer :
QgsPrecalculatedTextMetrics::count :
QgsPrecalculatedTextMetrics::count :
QgsProjectStorage::QgsProjectStorage :
QgsVectorLayer::setDataProvider :
QgsVectorLayer::setDataSourcePrivate :
QgsMapLayer::setDataSource :
QgsVectorLayer::QgsVectorLayer :
providerMetadataFactory :
providerMetadataFactory :
QgsAbstractDatabaseProviderConnection::table :
QgsFieldsItem::QgsFieldsItem :
providerMetadataFactory :
QgsDataItem::runCreateChildren :
QgsDataItem::runCreateChildren :
QgsDataItem::removeChildItem :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Versions

3.30.3 on Windows, please see stacktrace

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
@rouault 

Does this stack trace mean anything to you? I can't see **anywhere** in gdal where CPLODBCDriverInstaller::RemoveDriver is actually called.

**Comment by rouault** [comment]
> I can't see **anywhere** in gdal where CPLODBCDriverInstaller::RemoveDriver is actually called.

indeed !  It is not the first time (actually more the general rule than the exception) that I notice that stack traces in the crash dumps of Windows QGIS builds are (at least partly) garbage. Probably due to optimizations which make guessing the stack of calls unreliable

**Comment by pathmapper** [comment]
> stack traces in the crash dumps of Windows QGIS builds are (at least partly) garbage

So it's not useful here, closing.
