### ISSUE TITLE
Layers: Export → Save Selected Features As... saves an empty file

### ISSUE THREAD

**Issue by kristianrl** [qgis/QGIS#53524]
### What is the bug or the crash?

Layers: Export → Save Selected Features As... results in a file without the selected features.
![image](https://github.com/qgis/QGIS/assets/2519890/73028a68-f09f-40d4-81b7-6b3fa120b012)

### Steps to reproduce the issue

1. Load a polygon layer
![image](https://github.com/qgis/QGIS/assets/2519890/d6b25f55-0301-4804-89c0-f734ce056645)

2. Select a single feature using Select Features By Area or Single Click
![image](https://github.com/qgis/QGIS/assets/2519890/df2b425e-285f-4908-99fc-f4d224e86067)

3. Right click on the layer in the Layers list, click Export and Save Selected Features As.
![image](https://github.com/qgis/QGIS/assets/2519890/048047ed-ec2f-4f04-bafe-c4ed094d6991)

4. Select the output format (we usually deselect the Geometry column). I have tested using _GeoJSON_, _Shapefile_ and _Geopackage_.
![image](https://github.com/qgis/QGIS/assets/2519890/8f3e552e-fb06-46a3-8afe-6aeb39014b5f)

5. After the export is succesful, the selected polygon is not present in the saved file
![image](https://github.com/qgis/QGIS/assets/2519890/f4223dd7-b1a9-4fe7-a9f9-8537552a314c)

The exported GeoJSON file contains the following:
```JSON
{
"type": "FeatureCollection",
"name": "mettre",
"features": [

]
}
```

### Versions

The bug can be recreated using 3.28-3 and 3.30.3 - but the bug did not exist in 3.14. Version 3.14 still exports a usable file.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Cc: @GeodataInformatik @InformatikSilkeborg

**Comment by alexbruy** [comment]
I'd say this is not a bug. If geometry is not saved why do you expect to see anything on the map?

**Comment by roya0045** [comment]
> I'd say this is not a bug. If geometry is not saved why do you expect to see anything on the map?

On the UI side I guess it could be seen as a bug if the user can think the geometry export are an extra. It could be hidden and controlled in the geometry section of the report. 

The report also mentions shapefile and geopackage having the same issues, I don't recall if it was possible to deselect the geometry attribute from that place in the dialog.

**Comment by kristianrl** [comment]
@alexbruy & @roya0045, the `Geometry` column is not QGIS' geometry data, but part of Hexagon's GeoMedia metadata.
I can reproduce the bug without regard to the `Geometry` column being checked or unchecked. Instead, the `Geometry_SPA` column is used for storing the geometry.
No matter what, none of the selected polygon's attributes are saved.

When trying to gather more information, I realized that this is happening when adding layers/tables from our internal MSSQL database server.
When using an external WFS source, it was not reproducible.

**Comment by kristianrl** [comment]
We'll try to figure out the pattern for this issue to occur.
