### ISSUE TITLE
Web Service Geocode Is Not Responding

### ISSUE THREAD

**Issue by wbradjones77** [qgis/QGIS#53527]
### What is the bug or the crash?

I have been attempting to upload a very small file of 9 addresses for geocoding all day today, and I keep getting an error message "Web Service Geocode (Not Responding)."  I was originally running QGIS LTR 3.10, but upgraded to QGIS LTR 3.28.7, and I still have the same issue.  I even reinstalled the MMQGIS plugin for QGIS LTR 3.28.7, and I continue to have the same issue.  I have been using QGIS for almost 10 years, and have never had this issue before.  Because QGIS is now freezing when I try to geocode, I have to now go to Task Manager to end the task.  Please help.

### Steps to reproduce the issue

1.  Click on MMQGIS.
2.  Scroll down to Geocode.
3.  Select Geocode CSV with Web Service.
4.  Upload CSV (UTF-8) file.
5.  Copy and paste Google API key.
6.  Click apply.
Nothing happens after I click apply.  All I see "Ready" in an empty status bar.  No progress occurs whatsoever.  Once I mouse over the Web Service Geocode "(Not Responding)" appears in the header.  I even tried to upload a previous CSV (UTF-8) file with addresses that I successfully mapped a couple of weeks ago, and I get the same error.  It is no longer uploading either, and is causing the plugin to crash.  I end up getting a "qgis-ltr-bin,exe" is not responding error message.

### Versions

QGIS version
3.28.7-Firenze
QGIS code revision
fedae0eb52
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
mmqgis
2021.9.10
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by wbradjones77** [comment]
It finally worked, was just EXTREMELY slow for some reason today.  Took 15 minutes to find 9 addresses today, when normally it would take seconds.

**Comment by nyalldawson** [comment]
This is an issue with the mmqgis plugin, which is a third party plugin. You'll need to report this to the plugin authors.
