### ISSUE TITLE
Web View widget on Windows 10 cant load local images

### ISSUE THREAD

**Issue by grgoje** [qgis/QGIS#53535]
### What is the bug or the crash?

When attempting to use web view form widget to open local files on Linux, it works but not under Windows - there we get WebKit Error 102. This is a regression from previous behaviour which brakes important functionality for us.

See ilustrative images below:

Ubuntu:
![image](https://github.com/qgis/QGIS/assets/5871940/72f449d5-140b-4e9c-a9c0-d5bc3d483328)

Windows:
![image](https://github.com/qgis/QGIS/assets/5871940/393e6d25-00b4-4cd4-8d7b-0284bfc08777)

### Steps to reproduce the issue

Try to view an image with an "file:///" URL trough Web View form widget under windows

### Versions

3.28.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@grgoje thanks for reporting. What is the last version of QGIS working as expected? Could you please provide a simple project and layer in order to replicate the issue?
