### ISSUE TITLE
Removed layer returned by mapLayersByShortName()

### ISSUE THREAD

**Issue by strokovnjaka** [qgis/QGIS#53549]
### What is the bug or the crash?

Recently removed layer is returned by `QgsProject.instance().mapLayersByShortName(name)`.

### Steps to reproduce the issue

1. create a layer and assign it a short name, e.g. 
```
layer = QgsVectorLayer(file_name1, `name1`, 'ogr')
layer.setShortName('samename')
```
2. remove the layer, e.g. with 
```
ln = QgsProject.instance().layerTreeRoot().findLayer(layer)
QgsProject.instance().layerTreeRoot().removeChildNode(ln)
```
3. create a new layer with the same short name, e.g. 
```
new_layer = QgsVectorLayer(file_name2, `name2`, 'ogr')
new_layer.setShortName('samename')
```
4. call `mapLayersByShortName('samename')
```
removed = QgsProject.instance().mapLayersByShortName('samename')[0]
```
5. try to access the removed
```
removed.setSubsetString('')
```
6. observe runtime error
```
RuntimeError
wrapped C/C++ object of type QgsVectorLayer has been deleted
```

### Versions

QGIS version 3.30.0-'s-Hertogenbosch QGIS code revision f186b8efe0e
Qt version 5.15.3
Python version 3.9.5
GDAL/OGR version 3.6.2
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.39.4
PDAL version 2.4.3
PostgreSQL client version unknown
SpatiaLite version 5.0.1
QWT version 6.1.6
QScintilla2 version 2.13.1
OS version Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
When you remove a layer using this approach:

    QgsProject.instance().layerTreeRoot().removeChildNode(ln)

the layer isn't removed immediately, but is instead queued for removal at the next safe opportunity (when the qt event loop finishes executing)

The better way to remove a layer is via the various

   QgsProject.instance().removeMapLayer(... )

methods.
