### ISSUE TITLE
Snapping not working when changing CRS unless I reset Project CRS

### ISSUE THREAD

**Issue by Robotuner** [qgis/QGIS#53540]
### What is the bug or the crash?

Snapping to point layer does not always work when changing layer CRS to match the Project CRS.

### Steps to reproduce the issue

Create a new drawing.
load a world map and navigate to Seattle area (I use OSM Standard, the behaviour appears to be the same with bing and google).  (I need to do this to demonstrate the effect of switching to a different crs.)

- Create a new temporary point vector layer.
- Create a new temporary line vector layer.
- Note that the created layers have a CRS of 4326. The default Project CRS is 3857, but it doesn't seem to matter, it behaves correctly if you change it to 4326.
- Add (insert) several point nodes anywhere on the world map. 
- Save the changes to the layer.
- Insert lines between the nodes on the line layer.  **NOTE that the snapping to those points work.**
- Remove all points and lines.

- Change the project CRS to 6599
- Leave the CRS for the point and line layers at 4326.
- Add several point nodes and save the changes.
- Add lines between those nodes.  **NOTE that the point snapping also work.**
- Remove all point and lines

- Change the CRS for the point and line layers to match the project CRS of 6599
- Add several point nodes and save the changes.
- Insert lines between those nodes. **NOTE that Snapping DOES NOT WORK!**

The only way to get it to work is the change the Project CRS to something else (4326), then back to 6599.  Is this a bug or have I done something wrong or violates an assumption?

### Versions

I discovered this in QGIS Version 3.28.7

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
I'm not sure I'm following the process. But from what I understand you are reusing the same layers and changing their crs in QGIS instead of reprojecting them.

I suspect that this could lead to issue with the indexation and thus cause snapping issue.

If you want to have your data in another crs I recommend reprojecting it with the algorithm instead of simply modifing the crs of the layer. As it doesn't change the coordinate of things.
