### ISSUE TITLE
Map window border doesn't clip features

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#53542]
### What is the bug or the crash?

In layout exported images, features aren't clipped by map window border as shown at the screen!

![test](https://github.com/qgis/QGIS/assets/12034365/fbbc02bb-96f8-4c6a-9d10-5a7176352513)

### Steps to reproduce the issue

. create a layout
. create a map window
. export as image or pdf....

### Versions

Versione di QGIS
3.28.7-Firenze
Revisione codice QGIS
fedae0eb52
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.0
Compilato con PROJ
9.2.0
Esecuzione con PROJ
9.2.1
Versione database del Registro EPSG
v10.088 (2023-05-13)
Versione GEOS
3.11.2-CAPI-1.17.2
Versione SQLite
3.41.1
Versione PDAL
2.5.3
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.0.1
Versione QWT
6.1.6
Versione QScintilla2
2.13.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
azimuth_distance_measurement
0.4
latlontools
3.6.10
qgis_points2one
0.3.1
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Forna73** [comment]
I was forgetting.... the options in the object properties tab to cut features in atlas are all grayed out and I can't do nothing

**Comment by Forna73** [comment]
I discovered that the probleam appears when you enable grid reticols...

**Comment by nyalldawson** [comment]
are you using label text masks at all? if so, this is a known issue

**Comment by Forna73** [comment]
Hi!
I've read something about.
No, I'm not using label mask at all.

**Comment by kitzberdo** [comment]
Hello,
I've got the same problem, both in QGIS LTR (3.28.11) and in the latest version (3.32.3).
I don't use masks either.
The problem appears when using dot pattern filling.
In the layout everything looks fine but when exporting it (as PDF, picture or print doesn't matter) the filling expands over the border of the map.

Layout:
![image](https://github.com/qgis/QGIS/assets/120191895/3f8bd24e-a37c-42c2-a542-b6fb052bc069)

when exported:
![image](https://github.com/qgis/QGIS/assets/120191895/8e4d1873-22d0-43af-9371-7065e05ae4c6)

**Comment by Forna73** [comment]
Hi!
Yes, I've noticed It.
Just disabled "Mask" from every label rules and all Is fine.
I had also problems with trasparency with that feature enabled.
Simply we have to forget the feature unless properly fixed.

Il mar 26 set 2023, 11:44 kitzberdo ***@***.***> ha scritto:

**Comment by kitzberdo** [comment]
Yeah, I don't use the mask-function at all, so there must be another issue cuasing this behaviour as well...
