### ISSUE TITLE
QGis can't create a proper mbtiles file?

### ISSUE THREAD

**Issue by StacktraceException** [qgis/QGIS#53543]
### What is the bug or the crash?

The file size is only about 34 kb for an about 40km2 area at least with zoom level of 5 to 23.  Qgis toolbox -> XYZ generate mbtile file and also the qtiles plugin itself has same problem.

I found an old unsolved reference to this online  too   https://gis.stackexchange.com/questions/331915/generating-mbtiles-in-qgis3-4 

### Steps to reproduce the issue

Load raster map layer from WMTS.
Try to gernerate mbtile file,
see result is a tiny incomplete file. (maybe the tool just tries to use anotr layer which has no data?  There is no option in that tool to select layer...)

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
pobieracz_danych_gugik
1.0.6
qtiles
1.7.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
The issue could come from the source layer, WMTS layer
Is it a public server ? If yes, can you share address and layer you load.

I suggest to try step by step first. Create MBTiles from 5 to 9 or 10 and increment. 23 is a VERY high zoom

**Comment by StacktraceException** [comment]
I did try what you wrote. IT DID NOT HELP. Sorry, I'm so fed up with all
the shortcomings I discovered while spending an entire day with trying to
get offline maps to work.

It should be a straightforward process just like downloading a picture from
Google. There are however many at first unapparent of: bugs, limitations,
lack of documentation etc with several software/assets for qgis and/or in
qgis itself.

In no doubt qgis is quite an advanced software and probably the best of
them all. Nevertheless, after that entire day of frustration I am
completely certain that there was nothing left for me to try and that I
spent way too long for this problem.

Just writing about it now makes me feel the same way again. Maybe in few
years later this will be as straight forward as it needs to be.


Please feel encouraged to contribute further. Even if I won't reply soon,
hopefully others will benefit

Kind regards.


czw., 22 cze 2023, 10:50 użytkownik Nicolas Godet ***@***.***>
napisał:

**Comment by StacktraceException** [comment]
Sorry, I forgot to mention that yes it is a public server. Geoportal 2
polish official map wmts server, and/or wms server. They have bothm

czw., 22 cze 2023, 10:50 użytkownik Nicolas Godet ***@***.***>
napisał:

**Comment by nicogodet** [comment]
Share the link and extent you try to save offline.
