### ISSUE TITLE
QGIS does not render imported tiles correctly?

### ISSUE THREAD

**Issue by StacktraceException** [qgis/QGIS#53541]
### What is the bug or the crash?

In QGIS,  Tiles imported by drag and dropping zip file with nested structure (containing increasing zoom levels) appears blurry, despite that  an external image viewer opens it fine. But in QGIS after moving the tile out of group, then that tile is rendered fine without blurriness. I have made screenshots to confirm that this is the exact same file in exact same path.

Furthermore, there are more rendering issues: Having loaded a known good tile by right clicking -> zoom to layer, and then doing the same for a blank tile (generated as the canvas had an image containing a non-rectangular raster layer with a white background), then the canvas does not get updated.

What's more problematic is that the generated set of tiles should form some sort of cohesive image/map (as I have downloaded the canvas as tiles using the qtiles plugin), but they don't at all, (which is maybe related to them nnot having the proper coordinated, or so it seems, although this maybe can be a qtiles incompatibility or smth, I guess).

  

### Steps to reproduce the issue

Import nested tile directory tree zip file by drg and dropping to view pane
wait forever until it loads (despite no CPU nor RAM etc being used…)
select import all as group
try to view the map from the imprted group

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
Spatia Lite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
gugik_datafeeder
1.0.6
qtiles
1.7.2
db_manager
0.1.20
grassprovider
12/2/99
MetaSearch
0.3.6
processing
12/2/99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is a continuation of my struggles described within previously opened issue here: https://github.com/qgis/QGIS/issues/53538

Please try to be understanding as I am. kind regards.

**Comment by StacktraceException** [comment]
Update: another tile, which is only partially filled,  does not display at all in qgis. (image viewer views it fine though).

**Comment by StacktraceException** [comment]
Update: another tileset with fully filled tile is also rendered blank by qgis. I imported all not as group this time. It seems that this is random  or not so simple.

**Comment by StacktraceException** [comment]
I'm giving up for now. After entired day, it seems that there really is no way to do such an essential thing. Hopefully, this will solved some time later. 

I guess I'll have to resort to downloading smaller map areas,  using the site  I need the map from , the official WMS or WCS service, which presents another problem of having to stitch several of  the maximum allowed 7km2 areas somehow together...

**Comment by alexbruy** [comment]
It is not really clear what is wrong. If you try to load images which are not georeferenced it is natural that they are open in a wrong location and with the wrong scale. For loading local tiles you should use XYZ provider, not GDAL.
