### ISSUE TITLE
Qgis crash

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#53544]
### What is the bug or the crash?

Fresh Qgis install 3.28.7 on Windows 11 Pro.
Every time I open a project as I pan the view, Qgis crash.
Unusable

### Steps to reproduce the issue

Start Qgis
Open a project
Pan the view
crash

Copy report button on GUI Qgis ended unexpectedly grayed out and unusable

### Versions

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00007730 (most recent call first):

Stack Trace

geos::noding::NodedSegmentString::size :
geos::geom::prep::PreparedGeometryFactory::prepare :
initGEOS :
GEOSPreparedIntersects_r :
pal::LabelPosition::intersects :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsMapRendererJob::drawLabeling :
QgsMapRendererParallelJob::renderLabelsStatic :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.7-Firenze
QGIS code revision: fedae0eb52
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
You'll need to share a project and data which demonstrates this issue

**Comment by Forna73** [comment]
Hi Nyall!
Thanks for your attention.... but I can't share files or projects.... sorry
At this time I'm experiencing a lot of problems with this Qgis version.
Starting from the above to the one in the other post about the image exporting problem, label positioning, style expressions and geopackage that doesn't recognize the CSR or simply don't show in the map canvas for no why reason.
Really a mess! I spent over 2000€ for a new PC that runs as a rocket Qgis making operatiobns in seconds than tens of minutes like before, but ALL my projects are reporting problems. I spent these days to try and retry, finding workaround but only to discover new problems....
It is a fresh new install of everything, so I doubt is a problem of my installation. I'm inclined to think is a compatibility issue between Qgis versions and with Windows 11 (maybe youth problem). 
Now I've a lot of work with near exipiration... so to  me the best way is to take back my old PC with Qgis 3.22.16. Now I've to re-do days of work and data updating, but I'm sure that works.
Sorry for my little outburst, but I'm in love with Qgis and its open features, I'm only a little frustrated about an update from LTR version to LTR version (that should guarantee stability) with all these problems.

**Comment by weca-theo** [comment]
does this issues happen with all projects? does it crash when panning an empty project?

**Comment by Forna73** [comment]
Hi!
Sorry for delay but I'm working hard to recover time....
Ok... Now that I have my old PC with 3.22.16 on it, I could make some deep search and confrontations in my projects and this is what I discovered:

In Qgis 3.28.7, 3 of 4 of my projects have this issue.

I opened each project and before doing anything else I turned off all layers (tens of layers: points layers, lines, multipolygon, raster, wms and postgis also...)
I then turned on eachone trying panning the view and I discovered 2 layers that once turned on gave me the problem.

These 2 layers are in all 3 projects in which I have the issue.
However, I did all the procedure with all 3 projects and I assured that these 2 layers are the responsible for the problem.

One is a point layer, the other is a polygon layer, both in the **geopackage** format.
Here the first observation: the point layer is also in the project that doesn't give me any problem, but here it is in **.csv** format.
I tried to load the geopackage version and... here it is... the issue appears.
So I took the .csv and exported in geopackage format and loaded in again... boom... the issue appears again.
After this I tried to load the polygon layer, but in the old **.shp** format and all seems working well. I exported in geopackage, loaded... and the issue appears.
At this point I replaced the geopackage format layers with the .csv and .shp in the 3 projects and now I can pan without crash.

I did all the procedure above in the Qgis 3.22.16 and I had any problems,

To me there's something wrong with the geopackage export. probably something is corrupted in the process.
Starting from this new PC, I was going to mgrate all my layers in the geopackage format, lot less confusion and files and things appears better organized, At this point I stop... I will continue on my old PC with 3.22.16.

I'm sorry i can't share data, but now I've to come back to work ... I will continue building up the same projects in parallel.

So concluding... the cause for this crash appears solved to me =  geopackage format problem.
If you need to close the post it's ok.
Hope my report will help you in someway.
