### ISSUE TITLE
Elevation Profile capture line changes unexpectedly its direction

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#53551]
### What is the bug or the crash?

When using the "Nudge left" or Nudge right" buttons in an elevation profile view, the direction of the line changes from time to time. I can't tell why. But fact is that hitting the nudge button does not bring you to the same direction all the times

https://github.com/qgis/QGIS/assets/7983394/879bf8ed-20d9-4732-8ddf-56cb0a4a4574

### Steps to reproduce the issue

1. Create an elevation profile view
2. Set a greater tolerance (easier for visualizing)
3. Press the "Nudge right" (or "Nudge left") button multiple times.
4. It will happen that the lines goes back and forth. Unexpected IMHO. and if you pay attention to the small arrow at the middle of the line (not really visible in my screencast), you will notice that its direction changed.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.30.2-'s-Hertogenbosch | QGIS code revision | 0992b53397
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.4
  |   |   |  
Active Python plugins
qtribu | 0.14.2
bdtopo_importer | 0.2
MemoryLayerSaver | 4.0.4
MapsPrinter | 0.9
lizmap | 3.8.3
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
I suspect this is GEOS version related. I can't reproduce on a build using GEOS 3.11.

**Comment by alexbruy** [comment]
Is this still an issue? I can't reproduce with the latest master built against GEOS 3.11.1
