### ISSUE TITLE
Trace Tool to also work when editing an existing geometry with the vertex tool

### ISSUE THREAD

**Issue by Jakob-Lanstorp** [qgis/QGIS#53561]
### Feature description

Trace Tool works fine creating new geometries. It would be nice if the also worked when editing an existing geometry with the vertex tool. That is dragging an existing vertex in an existing geometry with the vertex tool and the vertex will trace a line or polygon segment back to the last vertex.

**Comment by uclaros** [comment]
fyi you modify existing geometries using the _Reshape Features_ tool in the advanced digitizing toolbar, in combination with _Enable tracing_

**Comment by Jakob-Lanstorp** [comment]
Thanks it works nicely, did not know the Reshape Feature could act like this. This feature request can be closed :)
