### ISSUE TITLE
Official Plugin Repository unavailable for 3.32

### ISSUE THREAD

**Issue by benz0li** [qgis/QGIS#53568]
### What is the bug or the crash?

The official Plugin Repository reports as unavailable.

Going to the URL for the repository https://plugins.qgis.org/plugins/plugins.xml?qgis=3.32 results in an Nginx 404 error.

### Steps to reproduce the issue

1. Go to Plugins
2. Click on Manage & Install Plugins
3. Go to Settings Tab
4. Plugin Repositories - Official QGIS Repository is listed as unavailable

<img width="640" alt="qgis_plugins_settings" src="https://github.com/qgis/QGIS/assets/20233085/098a2fe2-5b73-468b-bc7a-a5c7767cd963">

### Versions

QGIS version | 3.32.0-Lima | QGIS code branch | Release 3.32
-- | -- | -- | --
Qt version | 5.15.8 |   |  
Python version | 3.11.2 |   |  
GDAL/OGR version | 3.6.2 |   |  
PROJ version | 9.1.1 |   |  
EPSG Registry database version | v10.076 (2022-08-31) |   |  
GEOS version | 3.11.1-CAPI-1.17.1 |   |  
SQLite version | 3.40.1 |   |  
PDAL version | 2.4.0 |   |  
PostgreSQL client version | 15.3 (Debian 15.3-0+deb12u1)n |   |  
SpatiaLite version | 5.0.1 |   |  
QWT version | 6.1.4 |   |  
QScintilla2 version | 2.13.3 |   |  
OS version | Debian GNU/Linux 12 (bookworm) |   |  
  |   |   |  
Active Python plugins |   |   |  
grassprovider | 2.12.99 |   |  
MetaSearch | 0.3.6 |   |  
db_manager | 0.1.20 |   |  
processing | 2.12.99 |   |  

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Please make the plugin repository for a new L[T]R version available as soon as its source code is released.
ℹ️ I am [building QGIS from source](https://github.com/b-data/qgissi) and use it in a [multi-arch (linux/amd64, linux/arm64/v8) JupyterLab docker image](https://github.com/b-data/jupyterlab-qgis-docker-stack).

Thank you.

**Comment by agiudiceandrea** [comment]
@timlinux @rduivenvoorde, this seems a recurring issue.

**Comment by agiudiceandrea** [comment]
The issue will be fixed in an hour. See https://github.com/qgis/QGIS-Django/pull/243#issuecomment-1605280427.

**Comment by benz0li** [comment]
@agiudiceandrea @dimasciput Thank you for the prompt response.
