### ISSUE TITLE
Remove recently used CRS doesn't respect system locale override

### ISSUE THREAD

**Issue by jguelat** [qgis/QGIS#53592]
### What is the bug or the crash?

The new remove CRS context menu doesn't respect the system locale override (see attached screenshot).

![remove_crs](https://github.com/qgis/QGIS/assets/15686289/a556cc96-aeea-44d6-9ef4-50cd1398b11d)

### Steps to reproduce the issue

1. Check that your system is not using English as a default locale
2. In QGIS, go to the global settings, check the "Override system locale", choose English
3. Try to remove a recently used CRS by using the context menu (right-click on the CRS)
4. The context menu is translated in the system locale and not in English

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.32.0-Lima | QGIS code revision | 311a8cb8a65
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
geometry_paster | 0.2
GroupStats | 2.2.7
kart | 1.0.12
qfieldsync | v4.5.0
qgis_geonode | 1.0.1
qgis_stac | 1.1.1
quick_map_services | 0.19.33
RasterAttributeTable | 1.2
swissgeodownloader | 2.0.1
swiss_locator | 2.0.6
VowaConservation | 1.1
VowaSwisstopoBasemapLV95 | 1.0.7
VowaSynthese | 1.1.12
VowaTmoFilter | 1.0.1
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.32.0-Lima
QGIS code revision
[311a8cb8a65](https://github.com/qgis/QGIS/commit/311a8cb8a65)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geometry_paster
0.2
GroupStats
2.2.7
kart
1.0.12
qfieldsync
v4.5.0
qgis_geonode
1.0.1
qgis_stac
1.1.1
quick_map_services
0.19.33
RasterAttributeTable
1.2
swissgeodownloader
2.0.1
swiss_locator
2.0.6
VowaConservation
1.1
VowaSwisstopoBasemapLV95
1.0.7
VowaSynthese
1.1.12
VowaTmoFilter
1.0.1
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
ping @YoannQDQ

**Comment by YoannQDQ** [comment]
In another PR of mine (User Profile Selector #51800), I had to tweak the translation loading. The profile selector is shown before any profile are selected, so whe load the system language translation file first.

So for any translatable string, the resolution order is as follow:

- Try to qgis_<profile_language>.qm
- Fallback to qgis_<system_locale>.qm (⚠️NEW)
- Fallback to the untranslated string

The CRS context menu entries are translated in qgis_de.ts, but they're missing from the current qgis_en.ts, which causes your issue. In time, they will be added to qgis_en.ts, so the problem will eventualy disappear (I'm not very familiar with the Transifex release cycle though)

**Comment by nyalldawson** [comment]
Closing as note a QGIS (code) issue
