### ISSUE TITLE
crash when adjusting text of value in legend in page layout

### ISSUE THREAD

**Issue by robertjackstudio** [qgis/QGIS#53595]
## User Feedback

using 3.10
In Page layout - creating a legend.
I was adjusting the text of the items.
This the second crashin 2 days doing the same exact thing.

## Report Details

**Crash ID**: [5ed3831de34081a5ef6707910989aae86aee7800](https://github.com/qgis/QGIS/search?q=5ed3831de34081a5ef6707910989aae86aee7800&type=Issues)

**Stack Trace**
<pre>
QgsAbstractDatabaseProviderConnection::capabilities :
QgsLayerTreeView::keyPressEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.10.14-A Coru�a
QGIS code revision: 8374282d2a
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.1.4
Running against GDAL: 3.1.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

create page layout
add map and text block for title
add in legend
turn off auto fill and manually add items to include in the legend
adjust the text for the item in the legend
then it crashed - 2 days in a row doing the same operation

### Versions

using 3.10 LTR

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
3.10 is EOL, please update to 3.28 or 3.32 and retry.
