### ISSUE TITLE
Allow specifying min/max for graduated renderer

### ISSUE THREAD

**Issue by mbernasocchi** [qgis/QGIS#53611]
### Feature description

When classifying elements with the graduated renderer, the minimum and maximum value is derived from the data.

![image](https://github.com/qgis/QGIS/assets/233663/98c37a4d-6566-4438-b943-7154449cbf64)

It would be very useful to be able to set the minimum and maximum so that it is possible to create a classification that works, for example, between 0 and 100, even if the data only goes from 7 and 65. 

### Additional context

This is currently available for rasters only.

**Comment by DelazJ** [comment]
@mbernasocchi Duplicate of #20637 ?

**Comment by mbernasocchi** [comment]
> @mbernasocchi Duplicate of #20637 ?

Thanks @DelazJ I searched and searched but did not find it... was a feature request from the FOSS4G 23 QGIS AMA we did.
