### ISSUE TITLE
Processing toolbox doesn't update when 3.32 installed

### ISSUE THREAD

**Issue by MMcBain** [qgis/QGIS#53625]
### What is the bug or the crash?

Installed 3.32 [Lima] over most recent version of 3.31, but the Processing Toolbox doesn't update with the most recent upgrades [in particular the point cloud tools]. I didn't have the upgraded tools even under 3.31, so possibly this is a configuration problem just of my making. Did a complete removal of QGIS and reinstalled, but no improvement. On Ubuntu 23.04.

### Steps to reproduce the issue

Reinstalled whole qgis

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.0-Lima | QGIS code revision | 311a8cb8a6
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.3 (Ubuntu 15.3-0ubuntu0.23.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Ubuntu 23.04
  |   |   |  
Active Python plugins
qgis_stac | 1.1.1
processing_saga_nextgen | 0.0.7
Generalizer3 | 1.0
SemiAutomaticClassificationPlugin | 7.10.11
smooth_geometry | 1.1.1
FreehandRasterGeoreferencer | 0.8.3
grassprovider | 2.12.99
otbprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.32.0-Lima
QGIS code revision
[311a8cb8a6](https://github.com/qgis/QGIS/commit/311a8cb8a6)
Qt version
5.15.8
Python version
3.11.2
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.3 (Ubuntu 15.3-0ubuntu0.23.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Ubuntu 23.04

Active Python plugins
qgis_stac
1.1.1
processing_saga_nextgen
0.0.7
Generalizer3
1.0
SemiAutomaticClassificationPlugin
7.10.11
smooth_geometry
1.1.1
FreehandRasterGeoreferencer
0.8.3
grassprovider
2.12.99
otbprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Not a bug. To have point cloud algorithms you need QGIS built with PDAL support, PDAL is not available in standard Debian and Ubuntu repos. Use ubuntugis repos or build PDAL and QGIS yourself.
