### ISSUE TITLE
Missing Python console in Qgis build on windows

### ISSUE THREAD

**Issue by SI-Lab** [qgis/QGIS#53623]
### What is the bug or the crash?

After successfully building source qgis 3.28 using Cmake and building using VS2019 on windows platform. I opened qgis.exe on command prompt but its missing python console under plugin thus missing Processing menu too.

How can i solve this or what procedure did i miss during building?
![pythn](https://github.com/qgis/QGIS/assets/114161464/d5e0b0be-c32c-483d-ae10-57e96620d3c8)

### Steps to reproduce the issue

Windows 10

Cmake 

Visual Studio 2019

### Versions

Qgis 3.28.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
This is clearly an issue from your build if you didn't include python, this is not an issue with any official provided version of the software.

**Comment by SI-Lab** [comment]
> This is clearly an issue from your build if you didn't include python, this is not an issue with any official provided version of the software.

Thank you for the reply.
Kindly, Where on cmake do I include that or which checkbox should be ON?

**Comment by SI-Lab** [comment]
Got it. On cmake during build,**With_Bindings** should be checked.

**Comment by SI-Lab** [comment]
Lastly, how do I make qgis executable(portable) file from the build solution?

**Comment by alexbruy** [comment]
@SI-Lab please ask questions in the mailing lists or other support channels. GitHub issues are for feature requests and bugreports.

As for your question, you need to collect all libraries and tools used by QGIS similar to what OSGeo4W does.
