### ISSUE TITLE
qgstaskwrapper.py crash 

### ISSUE THREAD

**Issue by simplexitycomms** [qgis/QGIS#53622]
### What is the bug or the crash?

My python startup script crashes and produces:

Python Stack Trace
Windows fatal exception: access violation

Thread 0x000006e0 (most recent call first):
  File "C:/Users/paul/AppData/Roaming/QGIS/QGIS3/startup.py", line 1827 in pollingForNewData
    sleep(theHuntManager.dPollingDelay)
  File "C:\PROGRA~1/QGIS32~1.3/apps/qgis/./python\qgis\core\additions\qgstaskwrapper.py", line 37 in run
    self.returned_values = self.function(self, *self.args, **self.kwargs)

Current thread 0x00006298 (most recent call first):

Stack Trace
No stack trace is available.

QGIS Info
QGIS Version: 3.24.3-Tisler
QGIS code revision: cf22b74e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Run my python script, after about 15 minutes it produces a fatal exception

### Versions

QGIS version
3.24.3-Tisler
QGIS code revision
cf22b74e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.4.3
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
1.1
bh_timer
0.1
OSMDownloader
1.0.3
pluginbuilder3
3.2.1
plugin_reloader
0.9.2
qtiles
1.7.1
QuickOSM
2.1.1
quick_map_services
0.19.32
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
> QGIS Version: 3.24.3-Tisler

This version is EOL. Supported versions are 3.28 and 3.32.

> Run my python script

The issue is your script, not QGIS as QGIS runs smoothly without your script.
And as your script is over 1800 lines, no one will take a look. You need to troubleshoot yourself and isolate the faulty part of your code.

When you find the faulty code, please open a new issue with detailed steps to reproduce.
