### ISSUE TITLE
Coordinates in DD (Decimal degrees) as Dynamic Text in Layout

### ISSUE THREAD

**Issue by g-terziev** [qgis/QGIS#53653]
### Feature description

It should be good if you add a dynamic text option so that we can import the coordinates from our map in DD (decimal degrees) when creating Layouts.

At the moment it is only possible to import the coordintes in units from the chosen CRS. In image below i use the EPSG:25832, and coordinates are in units - meters. It would be good if I have an option where coordinates are shown in DD (I dont want to change my CRS, rather transforming the units from chosen CRS i.e. transforming the meters to degrees). And if you make this option, if possible make it in the following format: LAT (Y) ,LONG (X) with 6 digits decimal degree precision **For ex. 49.852149 (LAT or Y), 8.654981 (LONG or X)**

![image](https://github.com/qgis/QGIS/assets/117976490/6df655f0-f147-4796-b324-73cccda02cc2)

**Comment by roya0045** [comment]
you can make your own expression and get what you want by reprojecting the extent.

**Comment by roya0045** [comment]
> you can make your own expression and get what you want by reprojecting the extent in the expression.
