### ISSUE TITLE
QGIS fails to calculate statistics for a specific point cloud

### ISSUE THREAD

**Issue by Rafabmw** [qgis/QGIS#53670]
### What is the bug or the crash?

Estoy utilizando QGIS en versión 3.28.8 Firenze en mi sistema Windows 10 de 64 bits
He cargado archivos .laz y no veo los puntos en el panel, solo veo una cuadrícula de trazos roja.
No veo la simbología del archivo en la capa, he seleccionado las diferentes opciones: Atributo por rampa, RGB y Clasificación y no me da ningún dato.
También he visto la opción de Estadística en las propiedades de la capa y tampoco tiene contenido.
Son archivos .laz de más de 5 millones de puntos, descargados del CNIG español.
Por si sirve de ayuda, este es uno de ellos:
https://www.dropbox.com/s/ecm5qbwf9tckjky/PNOA_2016_PV_555-4771_ORT_CLA-IRC.laz?dl=0

No sé cuál es el problema de no poder visualizarlo.

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/138241316/686d9bbd-93aa-41f8-b9c9-c800765e500c)

![image](https://github.com/qgis/QGIS/assets/138241316/34f08080-e761-44ff-8f95-0bafe918f6d5)

![image](https://github.com/qgis/QGIS/assets/138241316/1e49a1e2-baed-43f3-bd6e-c982aed56a70)

### Versions

Versión de QGIS
3.28.8-Firenze
Revisión del código de QGIS
5ac45272b5
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.7.0
Versión de PROJ
9.2.1
Versión del registro de base de datos EPSG
v10.088 (2023-05-13)
Versión de GEOS
3.11.2-CAPI-1.17.2
Versión de SQLite
3.41.1
Versión de PDAL
2.5.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
kmltools
3.1.29
LAStools
1.4
slyr_community
5.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The error message displayed is (in English): Failed to calculate statistics of the point cloud ...

**Comment by alexbruy** [comment]
QGIS fails to calculate statistics for the file, and attributes are not detected. `wrench` reports following information
```
LAS 1.2
point format 3
count 5543625
scale 2.3282831545585e-07 2.3283064376229e-07 2.40113586299174e-07
offset 555499.995 4770500 614.55
extent 555000 4770000 98.91
555999.99 4771000 1130.19
crs ETRS89 / UTM zone 30N (EPSG:25830) (vertical CRS missing!)
units horizontal=metre vertical=unknown

Attributes:
- X floating 8
- Y floating 8
- Z floating 8
- Intensity unsigned 2
- ReturnNumber unsigned 1
- NumberOfReturns unsigned 1
- ScanDirectionFlag unsigned 1
- EdgeOfFlightLine unsigned 1
- Classification unsigned 1
- ScanAngleRank floating 4
- UserData unsigned 1
- PointSourceId unsigned 2
- GpsTime floating 8
- Red unsigned 2
- Green unsigned 2
- Blue unsigned 2
```

**Comment by uclaros** [comment]
This file now gets indexed in master (2c58769f) however it only gets rendered as long as its lower left corner is within the map canvas :confused:

**Comment by uclaros** [comment]
This file has a ridiculously small scale (230 nanometers :scream: ) causing some integer variables to overflow
