### ISSUE TITLE
Field names aliases and constraints/default formulas should be stored in "forms" style properties not in "fields"

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#53679]
### What is the bug or the crash?

Aliases for field names and formulas for default/constraints are set up in the "Attributes form" part of a vector properties, yet if you copy/paste that part of the style from one layer to another, this configs are not applied to another layer because instead it seems they are stored (in a very counterintuitive way) in the "fields" part of a layer style.

### Steps to reproduce the issue

See above.

### Versions

3.28.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Duplicates #45146.
