### ISSUE TITLE
Python error while launching QGIS 3.28 or Plugin manager

### ISSUE THREAD

**Issue by REDADRISSI** [qgis/QGIS#53676]
### What is the bug or the crash?

I have installed QGIS 3.28 (Windows 10) and I am getting some errors while launching it.

this error is related to pyplugin_installer :

```
An error occurred during execution of following code: import pyplugin_installer

traceback.print_exception() failed

Python version:

QGIS version: 3.28.8-Firenze 'Firenze', 5ac45272b58

Python path:
```

I have QGIS 3.18 already installed and it works fine.

I have tried to set PYTHONPATH but I still get the same results.

### Steps to reproduce the issue

it's occur when launching QGIS 3.28

### Versions

QGIS 3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by gioman** [comment]
@REDADRISSI have you really tried on new QGIS profile? I can't replicate here.

**Comment by REDADRISSI** [comment]
Thanks for your answer! it's works after changing the user.
