### ISSUE TITLE
Offset Line Symbology Loop Disappears Upon Zooming out

### ISSUE THREAD

**Issue by HughKelley** [qgis/QGIS#53671]
### What is the bug or the crash?

Styling a MultiLinestring or Linestring with a color, width = 1, and offset = 1, symbol will appear as expected at close in zooms, but upon zooming out, the loop part of the feature is not symbolized. 

This is a valid linestring, the line does not actually cross itself, only comes close so that there is no separation in the symbol.

Zoomed in:

![image](https://github.com/qgis/QGIS/assets/38143549/bec7ed5f-4a05-47c8-9270-91400f04da6f)

Zoomed out:
![image](https://github.com/qgis/QGIS/assets/38143549/d34e8ccd-88de-48a7-983c-68e78c69be04)

Close look at the end of the linestring, there is no real intersection in the geom.
![image](https://github.com/qgis/QGIS/assets/38143549/e28dd44a-670e-456c-b5fc-2c7551368460)

### Steps to reproduce the issue

Apply an offset to a line or multiline dataset with a looping section in it. Depending on the zoom level, the feature may or may not be completely shown. 

A QGIS layer style file can be downloaded from https://www.dropbox.com/s/fsd18nrkuwdwvqe/offset_problem_example.qlr?dl=0

### Versions

QGIS version | 3.28.4-Firenze | QGIS code revision | fd0fb72ab3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.39.4
PDAL version | 2.4.3
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
GeoCoding | 2.19
ImportPhotos | 3.0.5
loadthemall | 3.3.0
MapsPrinter | 0.9
mmqgis | 2021.9.10
ProjectPackager | 0.7.2
qgis2web | 3.16.0
quick_map_services | 0.19.33
StreetView | 3.2
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I'd be interested in investigating and adding a fix for this myself if possible. Especially if a more experienced QGIS contributor was willing to answer questions as I have them.

**Comment by agiudiceandrea** [comment]
@HughKelley could you please actually check if the issue does also occur using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a brand new QGIS user profile?

**Comment by HughKelley** [comment]
Apologies, I forgot my work computer is a little behind. I did originally check with a new user profile (despite pasting the info from my default profile), but testing now on 3.28.8 and 3.32.0 this problem is not occuring. 

![image](https://github.com/qgis/QGIS/assets/38143549/8de995c6-e57f-4f29-a904-8ad53b2a9f0a)
