### ISSUE TITLE
Label for field configured as "attachment" is not correctly aligned

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#53689]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/1951107/053f4693-e642-4e50-8ac3-f82d23f56762)

### Steps to reproduce the issue

See above image, compare the "checkbox field". Note: it does not depend on the width of the form dialog

![image](https://github.com/qgis/QGIS/assets/1951107/d813f718-1b5b-44ef-973c-459176051d8d)

### Versions

3.28.8 3.32.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Maybe depends on the used WM/DE? I can't reproduce with the latest master (9b2c94e2e34b9d61c809b133887c3b45188156ae)
