### ISSUE TITLE
GDAL_TRANSLATE to HDR

### ISSUE THREAD

**Issue by dp7x** [qgis/QGIS#53687]
### What is the bug or the crash?

When I try to export a layer to HDR format, the COASP driver is automatically set in the command line (-of COASP) and I get an error like "COASP driver has no creation capabilities".
Anyway, I need another driver saving to HDR format, so I would like to be able the EHdr driver (-of EHdr). This correctly works when launched from a command line, but it is not possible to set it in QGIS form.
Can you add the possibility to change the driver ?

Thank you in advance

### Steps to reproduce the issue

Go to RASTER menu, then CONVERSION, then TRANSFORM.
Choose to export to a file and select the *.HDR extension. 

### Versions

3.28.2 on Windows 11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@dp7x, it seems that if you want to use the EHdr format as export format, you need to select the BIL Files (*.bil) extension.
Have you tried it?
Please see Settings->Options->Data Sources->GDAL->Raster Drivers
See also https://gdal.org/drivers/raster/ehdr.html
