### ISSUE TITLE
Ludicrous default min/max values for the "range" widget

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#53681]
### What is the bug or the crash?

In a PostGIS table for a decimal/double field, when choosing the "range" widget the default min/max values that are proposed are simply ludicrous

![image](https://github.com/qgis/QGIS/assets/1951107/68ca19bd-2da4-4ed2-8155-ff49095e099e)

### Steps to reproduce the issue

See image above

### Versions

3.28.8 3.32.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Duplicates #24725.
