### ISSUE TITLE
Qgis build Packaging windows

### ISSUE THREAD

**Issue by SI-Lab** [qgis/QGIS#53683]
### What is the issue about the documentation?

I have successfully build qgis for source(3.28.6) using cmake and vs2019 and running well on test environment. 
I want to create qgis standalone installer file but no working creatensis.pl.
Can someone provide a working procedure?
Thank you.

**Comment by DelazJ** [comment]
Is this request not better filed in qgis-developers@lists.osgeo.org mailing-list?

**Comment by jef-n** [comment]
The packaging is done in OSGeo4W with https://github.com/jef-n/OSGeo4W/blob/master/scripts/createmsi.pl and the build recipes are also at https://github.com/jef-n/OSGeo4W/blob/master/src/qgis and qgis-ltr, qgis-ltr-dev, qgis-rel-dev and qgis-dev
