### ISSUE TITLE
Missing icons in "save style" dialog

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#53680]
### What is the bug or the crash?

For "elevation" and "notes"

![Screenshot 2023-07-01 131951](https://github.com/qgis/QGIS/assets/1951107/ae1997e6-3376-4b5b-a6ee-78360b315b4e)

### Steps to reproduce the issue

See image above.

### Versions

3.28.8 3.32.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ismailsunni** [comment]
@gioman do you know which icon should we use here? I can help if you know which icon it should be.
