### ISSUE TITLE
Add interpolation of Z values when adding points to 3D geometry using the Vertex Tool

### ISSUE THREAD

**Issue by aeropticdjr** [qgis/QGIS#53699]
### Feature description

When using the vertex tool with 3d geometry, and new points added have a Z value of 0, and the Z value has to be typed into the vertex table. If the new vertex were to have a default Z value calculated from the two vertices it was placed between, it would make editing most 3D geometry much faster.

### Additional context

There may be other, better ways to handle the adding of Z values to new vertices, but even just taking the midpoint of the two adjacent Z values would be enough to be quite useful. As of now, even a polygon with the same Z value at all points will have 0 for any new points.

**Comment by DelazJ** [comment]
Does https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#rules-of-z-coordinate-or-m-value-assignment help understand how Z values are assigned? I think in your case you need to enable topology.

**Comment by aeropticdjr** [comment]
This will work for what I'm trying to do. I didn't know about the Advanced Digitizing toolbar at all. Thanks!
