### ISSUE TITLE
Functions like $area not working in expression for conditional formatting

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#53694]
### What is the bug or the crash?

Say I want to conditionally format my rows based on the area of my polygons, then something like

`$area > 10000`

won't produce any formatting at all.

### Steps to reproduce the issue

See above.

### Versions

3.28.8 3.32.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @gioman, I cannot replicate the issue. Could you please provide a simple layer and the exact expression used?

**Comment by gioman** [comment]
@agiudiceandrea a random PostGIS layer (polygon), EPSG 3763, expression $area > 1000 No effect trying to apply a background color for both full rows or single columns.

**Comment by agiudiceandrea** [comment]
I've tested the "Conditional formatting" functionality using QGIS 3.28.8 on Windows (OSGeo4W): it seems to me it works as expected with a memory layer (and also with an ESRI Shapefile layer or with a GeoPackage layer)

https://github.com/qgis/QGIS/assets/16253859/794f601b-8075-4a58-94db-18237e884597

**Comment by gioman** [comment]
@agiudiceandrea there is something else at play because I see that in some project the formatting style is never applied immediately but is shows up if the table is closed and reopened. If I'll figure what is going on I will reopen this.
