### ISSUE TITLE
Qgis loads, then suddenly freezes and crashes

### ISSUE THREAD

**Issue by xyzadh** [qgis/QGIS#53704]
### What is the bug or the crash?

This has happened a few times lately. I open a Qgis project, it seems to load successfully but just before I can start working it freezes and crashes

### Steps to reproduce the issue

This is the text that comes

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00000534 (most recent call first):

Stack Trace

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.30.0-'s-Hertogenbosch
QGIS code revision: f186b8efe0e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

Qgis 3.30

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
@xyzadh  please test with the new profile and also check if this happens with the latest LTR and nightly build.

**Comment by xyzadh** [comment]
I am very sorry for the late reply. I saved the project under a new name and seemed to fix the issue.
