### ISSUE TITLE
Attribute table stops reloading if layer filter ever returns 0 rows 

### ISSUE THREAD

**Issue by Dan-Knott** [qgis/QGIS#53703]
### What is the bug or the crash?

If an attribute table is open when a filter is applied to the layer which returns 0 rows, the table does not update when the filter is cleared, or a new filter is applied which does return rows. 

### Steps to reproduce the issue

![qgis-bug-report](https://github.com/qgis/QGIS/assets/29566573/1341250d-5754-4890-a807-8877ad944286)
The issue can be reproduced using any layer, but for simplicity it can the following steps will use a temporary scratch layer.

1. Copy the following code block
```
wkt_geom	id	name
Point (1 2)	1	A
Point (1 1)	2	B
Point (1 0)	0	C
```
2. Paste features as a temporary scratch layer. Go to **Edit > Paste Features As > Temporary Scratch Layer ...**
3. Open the layers attribute table, it should display 3 rows.
4. Apply a filter to the layer which will result in 0 rows being returned `id = 3` and click **Ok**
5. The attribute table will now show no rows as expected
6. Clear the filter on the layer (or apply a new filter that would return rows) and click **Ok**
7. The attribute table will continue to show no rows. Clicking **Refresh** has no effect.
8. Opening a new attribute table will show the expected rows.

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a6
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I have also tested this exact same workflow on QGIS 2.28.8 and was unable to replicate the issue. I think the relevant change might be in pull request https://github.com/qgis/QGIS/pull/53168 however I'm not familiar with the QgsVectorLayerCache class and have not been able to track down the issue.

**Comment by alexbruy** [comment]
Not reproducible with the latest master (9b2c94e2e34b9d61c809b133887c3b45188156ae).
