### ISSUE TITLE
Build fails with exiv2 0.28

### ISSUE THREAD

**Issue by ggardet** [qgis/QGIS#53700]
### What is the bug or the crash?

Build fails with exiv2 0.28:
```
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp: In function 'QVariant decodeXmpData(const QString&, Exiv2::XmpData::const_iterator&)':
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp:69:40: error: 'const class Exiv2::Xmpdatum' has no member named 'toLong'
[ 2238s]    69 |         val = QVariant::fromValue( it->toLong() );
[ 2238s]       |                                        ^~~~~~
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp:83:60: error: 'const class Exiv2::Xmpdatum' has no member named 'toLong'
[ 2238s]    83 |         val = QVariant::fromValue( static_cast< int >( it->toLong() ) );
[ 2238s]       |                                                            ^~~~~~
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp: In function 'QVariant decodeExifData(const QString&, Exiv2::ExifData::const_iterator&)':
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp:185:40: error: 'const class Exiv2::Exifdatum' has no member named 'toLong'
[ 2238s]   185 |         val = QVariant::fromValue( it->toLong() );
[ 2238s]       |                                        ^~~~~~
[ 2238s] /home/abuild/rpmbuild/BUILD/qgis-3.30.3/src/core/raster/qgsexiftools.cpp:199:60: error: 'const class Exiv2::Exifdatum' has no member named 'toLong'
[ 2238s]   199 |         val = QVariant::fromValue( static_cast< int >( it->toLong() ) );
[ 2238s]       |                                                            ^~~~~~
```

### Steps to reproduce the issue

Try to build QGIS 3.30.3 against exiv2 0.28

### Versions

3.30.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ggardet** [comment]
Likely because of https://github.com/Exiv2/exiv2/pull/2062

**Comment by a17r** [comment]
See also full build.log in downstream bug report: https://bugs.gentoo.org/906470

Arch Linux use a non-upstreamed patch for >=3.30.3: https://gitlab.archlinux.org/archlinux/packaging/packages/qgis/-/blob/main/exiv2-0.28.patch

**Comment by ggardet** [comment]
@a17r Thanks for the link to the patch. Would be great if you could open a PR to upstream your patch. :)

**Comment by a17r** [comment]
@ggardet well it is not my patch, but maybe @antonio-rojas would

**Comment by dhdeangelis** [comment]
Replacing `toLong()` by `toUInt32() `in `qgsexiftools.cpp` (*) solves the problem in Linux (openSUSE Tumbleweed). Unsure if this will work in Windows too.

(*) [https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsexiftools.cpp](https://github.com/qgis/QGIS/blob/master/src/core/raster/qgsexiftools.cpp)

**Comment by antonio-rojas** [comment]
Done in https://github.com/qgis/QGIS/pull/53762

**Comment by lbartoletti** [comment]
Closed with https://github.com/qgis/QGIS/pull/53762

Thanks @antonio-rojas
