### ISSUE TITLE
Flatpack installation generate like a ddos attack to postgis server conection

### ISSUE THREAD

**Issue by smarcos82** [qgis/QGIS#53710]
### What is the bug or the crash?

I HAD qgis flatpack installed on linux Pop!_OS 22.04 LTS 64b.

With which I work on a project saved in postgis with the layers mostly saved on the same server.

Yesterday I could not continue working with said project, after looking for the problems I came to the conclusion of the title.
I was monitoring the connection with the database and when I started loading the project the sessions were triggered saturating the server connection. From 20 to 100 connections only with the opening of the qgis project. I tried another installation of qgis on windows and it worked normally. So I uninstalled qgis, deleted all settings and reinstalled qgis. I got the same problem. I have also tried a clean installation on another PC with the same system just installed. Giving the same error.
And sometimes it also gives me an error:
"fe_sendauth: no password supplied"
when the credentials have already been provided and are correct.

Finally I uninstalled everything and reinstalled but this time I did it through ".deb" packages, which solved the problem and opened the project with the 3 connections it normally did.

### Steps to reproduce the issue

1. go to open form / postgresql
2. open a proyect

### Versions

flatpack 3.32.0 Lima
deb 3.22.4-Białowieża

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
I'd say this is a duplicate of #53621

**Comment by alexbruy** [comment]
@smarcos82 can you test with the latest version?
