### ISSUE TITLE
Build failed with visual studio 2019 x64 and qt5.15.2 with error: use of undefined type“QgsPolymorphicRelation"

### ISSUE THREAD

**Issue by hello-willy** [qgis/QGIS#53711]
### What is the bug or the crash?

when build qgis3.30.3 with vs2019 and qt5.15.2
build log:
Build started...
1>------ Build started: Project: CRSCore, Configuration: Release x64 ------
1>moc_qgssourcecache.cpp
1>moc_qgsrelation.cpp
1>moc_qgsmaplayermodel.cpp
1>moc_qgsdatabaseschemamodel.cpp
1>moc_qgscombinedstylemodel.cpp
1>moc_qgspointcloudstatscalculator.cpp
1>moc_qgsmaprenderercache.cpp
1>moc_qgscolorramplegendnode.cpp
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3089,1): error C2027: use of undefined type 'QgsAbstractDatabaseProviderConnection' (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>D:\Case\crs\CatfishRS\CRSCore\qgsdatabaseschemamodel.h(28): message : see declaration of 'QgsAbstractDatabaseProviderConnection' (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3088): message : while compiling class template member function 'void std::default_delete<QgsAbstractDatabaseProviderConnection>::operator ()(_Ty *) noexcept const'
1>        with
1>        [
1>            _Ty=QgsAbstractDatabaseProviderConnection
1>        ] (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3198): message : see reference to function template instantiation 'void std::default_delete<QgsAbstractDatabaseProviderConnection>::operator ()(_Ty *) noexcept const' being compiled
1>        with
1>        [
1>            _Ty=QgsAbstractDatabaseProviderConnection
1>        ] (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3125): message : see reference to class template instantiation 'std::default_delete<QgsAbstractDatabaseProviderConnection>' being compiled (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>D:\Case\crs\CatfishRS\CRSCore\qgsdatabaseschemamodel.h(97): message : see reference to class template instantiation 'std::unique_ptr<QgsAbstractDatabaseProviderConnection,std::default_delete<QgsAbstractDatabaseProviderConnection>>' being compiled (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3089,25): error C2338: can't delete an incomplete type (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\memory(3090,1): warning C4150: deletion of pointer to incomplete type 'QgsAbstractDatabaseProviderConnection'; no destructor called (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>D:\Case\crs\CatfishRS\CRSCore\qgsdatabaseschemamodel.h(28): message : see declaration of 'QgsAbstractDatabaseProviderConnection' (compiling source file x64\Release\moc\moc_qgsdatabaseschemamodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits(546,35): error C2139: 'QSize': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_trivially_constructible' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qvariant.h(81): message : see declaration of 'QSize' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qtypeinfo.h(66): message : see reference to class template instantiation 'std::is_trivial<T>' being compiled
1>        with
1>        [
1>            T=QSize
1>        ] (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qtypeinfo.h(84): message : see reference to function template instantiation 'bool qIsTrivial<T>(void)' being compiled
1>        with
1>        [
1>            T=QSize
1>        ] (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(523): message : see reference to class template instantiation 'QTypeInfo<T>' being compiled
1>        with
1>        [
1>            T=QSize
1>        ] (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(522): message : while compiling class template member function 'void QList<QSize>::node_destruct(QList<QSize>::Node *,QList<QSize>::Node *)' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(904): message : see reference to function template instantiation 'void QList<QSize>::node_destruct(QList<QSize>::Node *,QList<QSize>::Node *)' being compiled (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(903): message : while compiling class template member function 'void QList<QSize>::dealloc(QListData::Data *)' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(857): message : see reference to function template instantiation 'void QList<QSize>::dealloc(QListData::Data *)' being compiled (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qlist.h(855): message : while compiling class template member function 'QList<QSize>::~QList(void)' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\Case\crs\CatfishRS\CRSCore\symbology\qgscombinedstylemodel.h(102): message : see reference to function template instantiation 'QList<QSize>::~QList(void)' being compiled (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\Case\crs\CatfishRS\CRSCore\symbology\qgscombinedstylemodel.h(100): message : see reference to class template instantiation 'QList<QSize>' being compiled (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits(546,72): error C2139: 'QSize': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_trivially_copyable' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qvariant.h(81): message : see declaration of 'QSize' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Tools\MSVC\14.29.30133\include\type_traits(561,46): error C2139: 'QSize': an undefined class is not allowed as an argument to compiler intrinsic type trait '__is_trivially_copyable' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qvariant.h(81): message : see declaration of 'QSize' (compiling source file x64\Release\moc\moc_qgscombinedstylemodel.cpp)
1>D:\DevKits\Qt5.14.2\5.14.2\msvc2017_64\include\QtCore\qtypeinfo.h(56): message : see reference to class template instantiation 'std::is_trivially_copyable<T>' being compiled

### Steps to reproduce the issue

![error](https://github.com/qgis/QGIS/assets/9379589/883e8139-3533-4256-bc18-3cc271559cda)

### Versions

qgis3.30.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Is this still an issue with latest versions?
