### ISSUE TITLE
QGIS 3.32 Crash on open QGZ from 3.30.2

### ISSUE THREAD

**Issue by rangus100** [qgis/QGIS#53727]
## User Feedback

Opening a QGZ file that was saved in QGIS 3.30.3

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002c28 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QObjectPrivate::~QObjectPrivate :
QMetaObject::Connection::operator void * __ptr64 QMetaObject::Connection::* __ptr64 :
QgsGroupLayer::~QgsGroupLayer :
QgsLayoutItemMap::setLayers :
QgsLayoutItemMap::readPropertiesFromElement :
QgsLayoutItem::readXml :
QgsLayout::addItemsFromXml :
QgsLayout::readXml :
QgsPrintLayout::readXml :
QgsLayoutManager::readXml :
QgsProject::readProjectFile :
QgsProject::unzip :
QgsProject::read :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

opening a QGZ file in 3.32 that was saved in 3.30.2
still opens in 3.30.2 with no issues

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a6
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AusMap
1.1
geoscience
1.9
qchainage
3.0.1
qgeo
1.3
qgsAzimuth
0.9.15
SpreadsheetLayers
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@rangus100 , thanks for reporting. The issue you reported seems similar to the one already recently reported at https://github.com/qgis/QGIS/issues/53645.
Could you please check if the issuer does also occur using a new QGIS user profile? Could you please provide a QGIS project that generates the crash?

**Comment by rangus100** [comment]
@agiudiceandrea yes it seems like the same issue as #53645 . 
Yes the issue does occur using a new QGIS profile. There is a message saying this project was saved with 3.30.3 and will be updated to the new version, the layer list comes up, status bar gets to 100%, but then just crashes.
Zipped QGZ file attached - but this won't have any of the data in it? I can't send the data as it belongs to a client.
[test.zip](https://github.com/qgis/QGIS/files/11963019/test.zip)

**Comment by roya0045** [comment]
> @rangus100 , thanks for reporting. The issue you reported seems similar to the one already recently reported at #53645. Could you please check if the issuer does also occur using a new QGIS user profile? Could you please provide a QGIS project that generates the crash?

Both stack traces are different, not sure how they are similar, though with the linked backport, I assume this should be fixed.
