### ISSUE TITLE
label border

### ISSUE THREAD

**Issue by NHM55** [qgis/QGIS#53723]
### What is the bug or the crash?

Cannot find steps / method to create / format a label border in 3.32.0. I even have labels with borders in existing project layers, and cannot understand how they are set up.

### Steps to reproduce the issue

I gatherthere is supposed to be some interface between"Mask" and the label border. Cannot see a connection in my existing labels with borders.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.0-Lima | QGIS code revision | 311a8cb8a6
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.0
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.41.1
PDAL version | 2.5.3
PostgreSQL client version | 15.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AzimuthDistanceCalculator | 2.0.2
ee_plugin | 0.0.6
FreehandRasterGeoreferencer | 0.8.3
GeometryShapes | 0.7
getthemfiltered | 0.1.3
GroupStats | 2.2.7
ImportPhotos | 3.0.5
LAStools | 1.4
layerGroupFilter | 0.2
LocatePoints | 0.3.4
mmqgis | 2021.9.10
numericalDigitize | 0.4.7
pointsamplingtool | 0.5.4
profiletool | 4.2.6
qgis_resource_sharing | 1.0.0
qgsAzimuth | 0.9.15
qtiles | 1.7.2
quick_map_services | 0.19.33
raster_tracer | 0.3.3
toggle_labels_widget | 1.0.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.0-Lima
QGIS code revision
[311a8cb8a6](https://github.com/qgis/QGIS/commit/311a8cb8a6)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthDistanceCalculator
2.0.2
ee_plugin
0.0.6
FreehandRasterGeoreferencer
0.8.3
GeometryShapes
0.7
getthemfiltered
0.1.3
GroupStats
2.2.7
ImportPhotos
3.0.5
LAStools
1.4
layerGroupFilter
0.2
LocatePoints
0.3.4
mmqgis
2021.9.10
numericalDigitize
0.4.7
pointsamplingtool
0.5.4
profiletool
4.2.6
qgis_resource_sharing
1.0.0
qgsAzimuth
0.9.15
qtiles
1.7.2
quick_map_services
0.19.33
raster_tracer
0.3.3
toggle_labels_widget
1.0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

In the "Labels > Background" tab, why is there not a checkbox to add a border, and to then then select width and color? .This seem like the simple, straightforward solution.

**Comment by NHM55** [comment]
OK, so i found that if I double click the "color" selector bar I will be able to not only select the background color but also configure the label with a border. 

Issue resolved.

**Comment by kannes** [comment]
Thanks for following up! :)
You should be able to click a button that "closes" the issue.
