### ISSUE TITLE
Default values are not applied when not depending on other fields

### ISSUE THREAD

**Issue by mussels** [qgis/QGIS#53722]
### What is the bug or the crash?

Using default values and doing that with expression is a smart and simple way to speed up editing work and avoid unnecessary human error. Unfortunately this functionality only works when adding a new feature or editing the attributes of an existing one through the table view. 
When adding a new feature a handy form is presented to the user. This is not the case when editing an existing feature. The only way to do this through a table is to change the Identify Results settings to Auto open form for single feature results. Then, using the Identify tool, clicking on a single feature while in edit mode, a form is presented to the user. This (unexpectedly and unintuitively) let the user edit the feature's attributes. However, the default values do not work here.
In my opinion, if this is the only way to take advantage of a form while editing attributes, then default values should work here too, and not just through the table view.
I raise this as a bug. Alternatively, a dedicated feature editing form should be created and behave the same way a new feature form does.

### Steps to reproduce the issue

1. Bring up the properties of a layer and set a few default values using the Attributes Form tab
2. Set the defaults with a simple value or an expression (do this for some attributes but not for others to have a mix of behaviours)
3. Check the Apply default value on update (do this for some attributes but not for others to have a mix of behaviours)
4. Ok this and test behaviour by editing values through the table view. If successful continue with the following steps:
5. Bring up the Identify Results with the Identify Features tool
6. Click on the Identify Settings button
7. Check the Auto open form for single feature results check-box
8. Choose a layer and toggle editing On 
9. Click on a single feature using the Identify Features tool
10. The tool will now display a form for the attributes
11. Test the default values behaviour here

### Versions

QGIS version
3.28.6-Firenze
QGIS code revision
868c9fa03b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Does the status of the "Apply default value on update" changes anything?

![immagine](https://github.com/qgis/QGIS/assets/142164/09d90c9a-fd53-4558-81c3-9165cef28067)

**Comment by alexbruy** [comment]
Works fine for default values with "Apply on update" setting on but values without this setting are not updated and I'd say this is an expected behaviour.

**Comment by mussels** [comment]
After further testing it seems the inconsistency arises from the use expressions with conditional statements.
The field in the form is evaluated at every change of values and reflected in the field containing a 'if' statement. In my case the 'if' statement is evaluated and the value updated instantly (i.e. before ok'ing) when the user changes value in a field referred in the 'if' condition; but if the expression is a simple function, say a lone 'now()' then the field is update AFTER ok'ing.
I hope this is clear and am also happy to close this "issue" if this is expected behaviour.

**Comment by signedav** [comment]
On having expressions with "Apply on update".

1. When expression depends on another field:
     - In attribute table: Default Values are emitted - even when nothing changes (see #54446)
     - In form via identify: Default Values are emitted - even when nothing changes (see #54446)
2. When expression depends **not** on another field:
     - In attribute table: Default Values are emitted (but we don't see it (they are not showing the newly emitted value but they are stored later)
     - In form via identify: Default Values are **not** emitted (main topic of this issue)

Can you confirm that @mussels ?

**Comment by signedav** [comment]
Keep it open
