### ISSUE TITLE
QGIS Crashes - Path not Awailable

### ISSUE THREAD

**Issue by urlacher23** [qgis/QGIS#53732]
### What is the bug or the crash?

QGIS does not start if the path of the last projects is not available. 

### Steps to reproduce the issue

Detach USB Stick.

### Versions

3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@urlacher23, thanks for reporting. Could you please specify with more details the exact steps in order to replicate the issue?
