### ISSUE TITLE
OpenFileGDB and GPKG drivers (and others) are not listed in the "Vector Drivers" list

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#53734]
### What is the bug or the crash?

The GDAL/OGR vector drivers that are also raster drivers at the same time, are not listed in the "Vector Drivers" list (Settings -> Options... -> Data Sources -> GDAL). They are only listed in the "Raster Drivers" list.

Notably, the OpenFileGDB driver is no longer listed in the "Vector Drivers" list since GDAL 3.7.0, when the support for raster datasets in such driver was introduced by @rouault with https://github.com/OSGeo/gdal/pull/7389.

### Steps to reproduce the issue

1. Go to Settings -> Options... -> Data Sources -> GDAL -> Vector Drivers
![image](https://github.com/qgis/QGIS/assets/16253859/8367a2f5-f66a-4fb5-9d97-fc17666b33f1)

### Versions

QGIS 3.28.8 - QGIS 3.32.0 on Windows using GDAL 3.7.0.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It looks like the possibility that some drivers could have both raster and vector capabilities at the same time was not taken in consideration when the "Vector Drivers" tab was implemented (since QGIS 3.16.0) by @alexbruy with https://github.com/qgis/QGIS/pull/38461:

https://github.com/qgis/QGIS/blob/65d40ee0ce59e761ee2de366ca9a963f35adfcfd/src/app/options/qgsoptions.cpp#L2284-L2291

https://github.com/qgis/QGIS/blob/65d40ee0ce59e761ee2de366ca9a963f35adfcfd/src/app/options/qgsoptions.cpp#L2364-L2371

**Comment by rouault** [comment]
fixed per https://github.com/qgis/QGIS/pull/54254
