### ISSUE TITLE
Display Bug with classification module

### ISSUE THREAD

**Issue by interfacehg** [qgis/QGIS#53745]
### What is the bug or the crash?

In version 3.32 RC : the first time I perform a graded classification : no worries. But then, a display bug occurs in layer properties / symbiology / graduate. 
A window hides the classes and no longer allows any changes.

![qgisbug](https://github.com/qgis/QGIS/assets/59583343/a8b29db0-7047-45a6-8642-59aa91b5a29f)

### Steps to reproduce the issue

1. Go to layer properties (vector)
2. Click on 'Symbiology'
3. Display bug.
![qgisbug](https://github.com/qgis/QGIS/assets/59583343/0361e35c-ebb6-46ff-9e2d-41ff01ec25d8)

### Versions

Version de QGIS 3.32.0-Lima 
Révision du code 311a8cb8a6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
can you provide the rest of the build info, would be helpful to know if the UI issue is related to the OS or something else.

**Comment by interfacehg** [comment]
Version de QGIS | 3.32.0-Lima | Révision du code | 311a8cb8a6
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.10.6
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.6
Version de l'OS | Linux Mint 21.1
  |   |   |  
Extensions Python actives
densityanalysis | 2023.6.12
scpplugin | 2.0
mmqgis | 2021.9.10
quick_map_services | 0.19.33
GroupStats | 2.2.7
cartogram3 | 3.1.5
DataPlotly | 4.0.3
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>Version de QGIS
3.32.0-Lima
Révision du code
[311a8cb8a6](https://github.com/qgis/QGIS/commit/311a8cb8a6)
Version de Qt
5.15.3
Version de Python
3.10.6
Version de GDAL/OGR
3.4.1
Version de Proj
8.2.1
Version de la base de données du registre EPSG
v10.041 (2021-12-03)
Version de GEOS
3.10.2-CAPI-1.16.0
Version de SQLite
3.37.2
Version de PDAL
2.3.0
Version du client PostgreSQL
14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
Version de SpatiaLite
5.0.1
Version de QWT
6.1.4
Version de QScintilla2
2.11.6
Version de l'OS
Linux Mint 21.1




Extensions Python actives
densityanalysis
2023.6.12
scpplugin
2.0
mmqgis
2021.9.10
quick_map_services
0.19.33
GroupStats
2.2.7
cartogram3
3.1.5
DataPlotly
4.0.3
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

**Comment by DelazJ** [comment]
@interfacehg Can you also run with a new profile (as requested in the form)? It could help eliminate the fact that this is the result of a plugin

**Comment by interfacehg** [comment]
It's the same thing.
![bugqgis2](https://github.com/qgis/QGIS/assets/59583343/5d306f27-4952-4239-b577-398827b5b2f7)

**Comment by XaMa76** [comment]
I have the same problem with Qgis 3.28.9, 3.28.10, 3.28.11. The problem is not present on Qgis 3.28.5.

**Comment by maellevd** [comment]
I am currently facing the same issue with the update of the UbuntuGIS-unstable PPA to QGIS 3.28.10 on Jammy (on September 23rd), as indicated here: https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-unstable/+index?batch=75&memo=150&start=150.

This problem also affects our students who are enrolled in a training program, as their computers were configured with this repository. Therefore, I have urgently contacted Martin L to inquire if it would be possible to restore the previous repository (QGIS 3.28.5) in case there is a delay in resolving the bug...

**Comment by maellevd** [comment]
For your information, while waiting for the bug to be resolved, an interim solution to work around this display issue is to use the Layer Styles panel.

**Comment by effjot** [comment]
I can confirm this bug is still present in version 3.28.11. I was not present in 3.28.7, if I remember correctly.

**Comment by DelazJ** [comment]
@effjot This issue report is a duplicate of #54549 which should be fixed by #54943. This is available in 3.34 and was backported to 3.28 branch 3 weeks ago (https://github.com/qgis/QGIS/commit/8a5d44ce3d9decc545ce01d1a27840b292f7b7d3) so should be available in 3.28.13 at the end of the next week.

**Comment by effjot** [comment]
Thanks for the pointers! Issue search led me to this page first ;-)
