### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by guspresa** [qgis/QGIS#53743]
## User Feedback

62c06df51ba84c32376002e25009cb4640285a25

## Report Details

**Crash ID**: [62c06df51ba84c32376002e25009cb4640285a25](https://github.com/qgis/QGIS/search?q=62c06df51ba84c32376002e25009cb4640285a25&type=Issues)

**Stack Trace**

```

QNetworkAccessManager::cookieJar :
QgsNetworkAccessManager::setupDefaultProxyAndCache :
QgsNetworkAccessManager::instance :
QgsNetworkContentFetcher::fetchContent :
QgsNetworkContentFetcherTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.8-Firenze
QGIS code revision: 5ac45272b5
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

see report

### Versions

see report

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@guspresa, thanks for reporting. Could you please describe in what situation or after what operations QGIS crashed? Does the crash happen every time you do the same operations? Could you please try if the issue does occur also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?
