### ISSUE TITLE
When digitizing the form to enter attributes keeps moving a bit down for every new feature - ending up with the 'OK'-button outside the screen

### ISSUE THREAD

**Issue by MieWinstrup** [qgis/QGIS#53740]
### Feature description

When entering attribut information while digitizing, the form moves a little bit every time, as shown in the next four screen dumps:

1. entry
![image](https://github.com/qgis/QGIS/assets/16276034/9a6a655f-2eac-4c0c-94b0-7d570f1f5309)

2. entry - the form has slightly moved downwards:
![image](https://github.com/qgis/QGIS/assets/16276034/fdc307c8-26ab-4dc0-8d5c-ab2e13dadb14)

3. entry - the form has slightly moved downwards again:
![image](https://github.com/qgis/QGIS/assets/16276034/993dd502-13c2-4b02-8dfb-954fc7e25985)

4. entry - the form has slightly moved downwards again, and now the user can't push the 'OK'-button, before the user has moved the form up. 
![image](https://github.com/qgis/QGIS/assets/16276034/9c724ac6-7d17-46db-b4ef-cc23475c7a5f)

That is a bit inconvenient having to move the form up.

I don't know what would be the best solution. Either having a setting to control the behaviour of the form, or just always show it at the same location?

**Comment by roya0045** [comment]
I think this is meant as a issue and not a feature request. It might also be depending on windows and how it likes to tile windows that are not fullscreen.

**Comment by MorriganR** [comment]
https://github.com/qgis/QGIS/issues/44050

**Comment by m-kuhn** [comment]
Which version is this, @MieWinstrup ?

**Comment by MieWinstrup** [comment]
@m-kuhn it is QGIS 3.28.8 on Windows

![image](https://github.com/qgis/QGIS/assets/16276034/55db8e1b-0bbd-4262-ac60-5e52ef42bc8a)

**Comment by MieWinstrup** [comment]
I can see that is has been solved in QGIS 3.32. Thanks!

**Comment by YoannQDQ** [comment]
For reference, solved in #52472
