### ISSUE TITLE
Two settings for network timeout, not possible to change one of them

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#53759]
### What is the bug or the crash?

There are two settings for network timeout in advanced settings and when you change `network-timeout`, the change will be discarded.

![grafik](https://github.com/qgis/QGIS/assets/20856381/5123c1d7-d716-4f29-b89e-97a08657d07a)

### Steps to reproduce the issue

1. `Settings` -> `Options` -> `Advanced` -> confirm to be careful -> search for `timeout`
2. Change network-timeout to `10000`
![grafik](https://github.com/qgis/QGIS/assets/20856381/a9dcc1b9-d85f-4ef5-bfe6-5bcdb26a971a)
3. click OK
4. reopen the settings
5. See error -> the value is still 60000

### Versions

QGIS version | 3.33.0-Master | QGIS code revision | 3ea6656aafb
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.2
GDAL/OGR version | 3.2.2
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.9.0-CAPI-1.16.2
SQLite version | 3.34.1
PDAL version | 2.2.0
PostgreSQL client version | 13.11 (Debian 13.11-0+deb11u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Debian GNU/Linux 11 (bullseye)
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Came across this when looking into https://github.com/qgis/QGIS/issues/53752.

**Comment by pathmapper** [comment]
`network-timout` could be changed via the GUI in Network settings (but not in advanced settings), but this doesn't affect the second one:

![grafik](https://github.com/qgis/QGIS/assets/20856381/91e2b0a2-7eb9-4ad5-9a52-1583b54e39b2)
![grafik](https://github.com/qgis/QGIS/assets/20856381/5436d1cc-5e98-49e5-bdb6-7199a5e4106b)

**Comment by nyalldawson** [comment]
It's probably just a remnant of an old profile. Do you see this in a new profile?

**Comment by pathmapper** [comment]
Yes, after you start QGIS with the fresh profile a second time, both settings are there (directly after creating the new profile none of them is in advanced settings).

Just found some comments in `qgssettingsregistrycore.cpp`

https://github.com/qgis/QGIS/blob/3ea6656aafb434b73e8d2cd57fa1ba383c557cd5/src/core/settings/qgssettingsregistrycore.cpp#L128-L131
https://github.com/qgis/QGIS/blob/3ea6656aafb434b73e8d2cd57fa1ba383c557cd5/src/core/settings/qgssettingsregistrycore.cpp#L139


https://github.com/qgis/QGIS/blob/3ea6656aafb434b73e8d2cd57fa1ba383c557cd5/src/core/settings/qgssettingsregistrycore.cpp#L371
https://github.com/qgis/QGIS/blob/3ea6656aafb434b73e8d2cd57fa1ba383c557cd5/src/core/settings/qgssettingsregistrycore.cpp#L382

So it looks like `qgis/networkAndProxy/networkTimeout` is the deprecated old key which is still kept for backward compatibility. 

---

After all I'm still wondering why 

https://github.com/qgis/QGIS/blob/3ea6656aafb434b73e8d2cd57fa1ba383c557cd5/src/auth/oauth2/core/qgsauthoauth2method.cpp#L192-L196 

is still in the code, but maybe it's just work to be done and the conclusion is that one must currently set the value for network timeout only in
`Settings` -> `Options` -> `Network`
and not in
`Settings` -> `Options` -> `Advanced`

**Comment by pathmapper** [comment]
From https://github.com/qgis/QGIS/pull/51295

> For a cleaner approach (both code and structure of the keys in QSettings), I have migrated some settings keys.
> When QGIS opens, it copies old keys to new keys and delete the old ones. When it exits, old keys are rewritten to ensure backward compatibility.

According to this, IIRC,  `qgis/networkAndProxy/networkTimeout` should never be visible in the GUI.

**Comment by alexbruy** [comment]
@pathmapper can be closed?

**Comment by pathmapper** [comment]
@alexbruy I think there's still an issue regarding the timeout setting  but I'll have to check it out and open a new ticket if that's the case.
