### ISSUE TITLE
Grass algo r.param.scale not working in 3.32

### ISSUE THREAD

**Issue by baswein** [qgis/QGIS#53754]
### What is the bug or the crash?

If I run r.param.scale on 3.32 (OSGeo4W) I get an error that it can't find one of the intermediate files. Other Grass alogs seem to work. I ran this last week on 3.30 before upgrading to 3.32 and it worked. 
Also doesn't work on 3.33 and 3.28 can't seem to find Grass now. 
I did get it to run on a old non OSGeo4W version of 3.26.3 I have on my computer. 
Log of the error in 3.33:
`QGIS version: 3.33.0-Master
QGIS code revision: 891037950a
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.8.0dev-d0acdbabb3
GEOS version: 3.11.2-CAPI-1.17.2
PROJ version: Rel. 9.2.1, June 1st, 2023
PDAL version: 2.5.3 (git-version: 7ec4e6)
Algorithm started at: 2023-07-07T12:09:27
Algorithm 'r.param.scale' starting…
Input parameters:
{ '-c' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'curvature_tolerance' : 0.0001, 'exponent' : 0, 'input' : 'C:/Users/bas/Documents/temp_qgis/Grass-param/DEM_Filled_Holes_50m.tif', 'method' : 0, 'output' : 'TEMPORARY_OUTPUT', 'size' : 3, 'slope_tolerance' : 1, 'zscale' : 1 }

g.proj -c wkt="C:/Users/bas/AppData/Local/Temp/processing_ZjrbNe/5927cccaa379489a9004130344fd2749/crs.prj"
r.in.gdal input="C:\Users\bas\Documents\temp_qgis\Grass-param\DEM_Filled_Holes_50m.tif" band=1 output="rast_64a838b75d5812" --overwrite -o
g.region n=935052.0 s=924102.0 e=115478.0 w=104928.0 res=50.0
r.param.scale input=rast_64a838b75d5812 slope_tolerance=1 curvature_tolerance=0.0001 size=3 method="elev" exponent=0 zscale=1 output=outputeff3de2ba0ff46d787709a6b30dc4084 --overwrite
g.region raster=outputeff3de2ba0ff46d787709a6b30dc4084
r.out.gdal -t -m input="outputeff3de2ba0ff46d787709a6b30dc4084" output="C:\Users\bas\AppData\Local\Temp\processing_ZjrbNe\93af5685db724d68b3ef001104b6b50d\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
WARNING: Concurrent mapset locking is not supported on Windows
C:\OSGeo4W\bin>chcp 1252 1>NUL
C:\OSGeo4W\bin>g.proj -c wkt="C:/Users/bas/AppData/Local/Temp/processing_ZjrbNe/5927cccaa379489a9004130344fd2749/crs.prj"
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
C:\OSGeo4W\bin>r.in.gdal input="C:\Users\bas\Documents\temp_qgis\Grass-param\DEM_Filled_Holes_50m.tif" band=1 output="rast_64a838b75d5812" --overwrite -o
Over-riding projection check
Importing raster map <rast_64a838b75d5812>...
0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
C:\OSGeo4W\bin>g.region n=935052.0 s=924102.0 e=115478.0 w=104928.0 res=50.0
C:\OSGeo4W\bin>r.param.scale input=rast_64a838b75d5812 slope_tolerance=1 curvature_tolerance=0.0001 size=3 method="elev" exponent=0 zscale=1 output=outputeff3de2ba0ff46d787709a6b30dc4084 --overwrite
C:\OSGeo4W\bin>g.region raster=outputeff3de2ba0ff46d787709a6b30dc4084
ERROR: Raster map <outputeff3de2ba0ff46d787709a6b30dc4084> not found
C:\OSGeo4W\bin>r.out.gdal -t -m input="outputeff3de2ba0ff46d787709a6b30dc4084" output="C:\Users\bas\AppData\Local\Temp\processing_ZjrbNe\93af5685db724d68b3ef001104b6b50d\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
ERROR: Raster map or group <outputeff3de2ba0ff46d787709a6b30dc4084> not found
C:\OSGeo4W\bin>exit
Press any key to continue . . .
Execution completed in 1.00 seconds
Results:
{'output': 'C:\\Users\\bas\\AppData\\Local\\Temp\\processing_ZjrbNe\\93af5685db724d68b3ef001104b6b50d\\output.tif'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/bas/AppData/Local/Temp/processing_ZjrbNe/93af5685db724d68b3ef001104b6b50d/output.tif
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.`

Log with no error in 3.26: 
`QGIS version: 3.26.3-Buenos Aires
QGIS code revision: 65e4edfdada
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.5.1
GEOS version: 3.10.3-CAPI-1.16.1
PROJ version: Rel. 9.1.0, September 1st, 2022
PDAL version: 2.4.3 (git-version: 6311a6)
Algorithm started at: 2023-07-07T11:56:15
Algorithm 'r.param.scale' starting…
Input parameters:
{ '-c' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'curvature_tolerance' : 0.0001, 'exponent' : 0, 'input' : 'C:/Users/bas/Documents/temp_qgis/Grass-param/DEM_Filled_Holes_50m.tif', 'method' : 0, 'output' : 'TEMPORARY_OUTPUT', 'size' : 3, 'slope_tolerance' : 1, 'zscale' : 1 }

g.proj -c wkt="C:/Users/bas/AppData/Local/Temp/processing_VJAHUW/f241272ec0054a2f8ef86b0fbc41a85a/crs.prj"
r.in.gdal input="C:\Users\bas\Documents\temp_qgis\Grass-param\DEM_Filled_Holes_50m.tif" band=1 output="rast_64a8359f5f17b2" --overwrite -o
g.region n=935052.0 s=924102.0 e=115478.0 w=104928.0 res=50.0
r.param.scale input=rast_64a8359f5f17b2 slope_tolerance=1 curvature_tolerance=0.0001 size=3 method="elev" exponent=0 zscale=1 output=output5745f4fc16ea428f9901866009da123c --overwrite
g.region raster=output5745f4fc16ea428f9901866009da123c
r.out.gdal -t -m input="output5745f4fc16ea428f9901866009da123c" output="C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\33cac851b7c4434d88f723c3cfb7fd4c\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
Starting GRASS GIS...
WARNING: Concurrent mapset locking is not supported on Windows
Cleaning up temporary files...
Executing <C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\grassdata\grass_batch_job.cmd> ...
C:\Program Files\QGIS 3.26.3\bin>chcp 1252 1>NUL
C:\Program Files\QGIS 3.26.3\bin>g.proj -c wkt="C:/Users/bas/AppData/Local/Temp/processing_VJAHUW/f241272ec0054a2f8ef86b0fbc41a85a/crs.prj"
Default region was updated to the new projection, but if you have multiple mapsets `g.region -d` should be run in each to update the region from the default
Projection information updated
C:\Program Files\QGIS 3.26.3\bin>r.in.gdal input="C:\Users\bas\Documents\temp_qgis\Grass-param\DEM_Filled_Holes_50m.tif" band=1 output="rast_64a8359f5f17b2" --overwrite -o
Over-riding projection check
Importing raster map <rast_64a8359f5f17b2>...
0..3..6..9..12..15..18..21..24..27..30..33..36..39..42..45..48..51..54..57..60..63..66..69..72..75..78..81..84..87..90..93..96..99..100
C:\Program Files\QGIS 3.26.3\bin>g.region n=935052.0 s=924102.0 e=115478.0 w=104928.0 res=50.0
C:\Program Files\QGIS 3.26.3\bin>r.param.scale input=rast_64a8359f5f17b2 slope_tolerance=1 curvature_tolerance=0.0001 size=3 method="elev" exponent=0 zscale=1 output=output5745f4fc16ea428f9901866009da123c --overwrite
2..5..8..11..14..17..20..23..26..29..32..35..38..41..44..47..50..53..56..59..62..65..68..71..74..77..80..83..86..89..92..95..98..100
C:\Program Files\QGIS 3.26.3\bin>g.region raster=output5745f4fc16ea428f9901866009da123c
C:\Program Files\QGIS 3.26.3\bin>r.out.gdal -t -m input="output5745f4fc16ea428f9901866009da123c" output="C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\33cac851b7c4434d88f723c3cfb7fd4c\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
ERROR 6: C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\33cac851b7c4434d88f723c3cfb7fd4c\output.tif, band 1: SetColorTable() only supported for Byte or UInt16 bands in TIFF format.
Checking GDAL data type and nodata value...
2..5..8..11..14..17..20..23..26..29..32..35..38..41..44..47..50..53..56..59..62..65..68..71..74..77..80..83..86..89..92..95..98..100
Using GDAL data type <Float64>
Input raster map contains cells with NULL-value (no-data). The value nan will be used to represent no-data values in the input map. You can specify a nodata value with the nodata option.
Exporting raster data to GTiff format...
2..5..8..11..14..17..20..23..26..29..32..35..38..41..44..47..50..53..56..59..62..65..68..71..74..77..80..83..86..89..92..95..98..100
r.out.gdal complete. File <C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\33cac851b7c4434d88f723c3cfb7fd4c\output.tif> created.
C:\Program Files\QGIS 3.26.3\bin>exit
Execution of <C:\Users\bas\AppData\Local\Temp\processing_VJAHUW\grassdata\grass_batch_job.cmd> finished.
Cleaning up temporary files...
Execution completed in 1.23 seconds
Results:
{'output': 'C:\\Users\\bas\\AppData\\Local\\Temp\\processing_VJAHUW\\33cac851b7c4434d88f723c3cfb7fd4c\\output.tif'}

Loading resulting layers
Algorithm 'r.param.scale' finished`

### Steps to reproduce the issue

1. Load Raster
2. Run r.param.scale for any of the outputs. e.g. Planc 
3. See error in the log.

### Versions

QGIS version
3.33.0-Master
QGIS code revision
891037950a
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.8.0dev-ea323128fe
Running against GDAL/OGR
3.8.0dev-d0acdbabb3
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Raster layer for tests. 
[DEM_Filled_Holes_50m.zip](https://github.com/qgis/QGIS/files/11984074/DEM_Filled_Holes_50m.zip)

**Comment by agiudiceandrea** [comment]
Hi @baswein, I think this is very likely a packaging issue. I suggest you to file a ticket at https://trac.osgeo.org/osgeo4w/

**Comment by neteler** [comment]
BTW, please consider the modern [r.geomorphon](https://grass.osgeo.org/grass-stable/manuals/r.geomorphon.html) instead of the old `r.param.scale` command.

**Comment by baswein** [comment]
That

**Comment by baswein** [comment]
Thanks @agiudiceandrea after upgrading to the latest version this is now working. Thanks for your response and sorry to not reply. @neteler Thanks for the tip! That seems like a very cool tool. However, I'm using this as an input in a random forest model and it seems like the geomorphon classifies the output rather than giving me a gradient of forms that I think would be the most valuable. In param scale I and using the plan and profile curvatures.

**Comment by neteler** [comment]
> In param scale I and using the plan and profile curvatures.

I see. For plan and profile curvatures, see also https://grass.osgeo.org/grass-stable/manuals/r.slope.aspect.html
