### ISSUE TITLE
impossible de charger une couche wms

### ISSUE THREAD

**Issue by Greekoss** [qgis/QGIS#53857]
### What is the bug or the crash?

Bonjour,

Lors du chargement d'une couche wms voici ce que le logiciel m'affiche , plus aucun ajout est possible 

<img width="1254" alt="Capture d'écran 2023-07-18 à 21 56 21" src="https://github.com/qgis/QGIS/assets/139920643/ee2dfce1-fcb3-4a47-bc53-89b3f85ac150">

### Steps to reproduce the issue

COUCHE--> AJOUTER UNE COUCHE WMS--> ENTRER L'URL--> OK --> CLIQUER SUR CONNEXION --> LE MESSAGE APPARAIT 

### Versions

Version de QGIS | 3.32.0-Lima | Révision du code | b9862de816
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.3.2
Version de Proj | 8.1.1
Version de la base de données du registre EPSG | v10.028 (2021-07-07)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.11.5
Version de l'OS | macOS 13.4
  |   |   |  
Extensions Python actives
quick_map_services | 0.19.33
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

Version de QGIS
3.32.0-Lima
Révision du code
[b9862de816](https://github.com/qgis/QGIS/commit/b9862de816)
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.3.2
Version de Proj
8.1.1
Version de la base de données du registre EPSG
v10.028 (2021-07-07)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.35.2
Version de PDAL
2.3.0
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.11.5
Version de l'OS
macOS 13.4

Extensions Python actives
quick_map_services
0.19.33
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by gacarrillor** [comment]
Bonjour @Greekoss, est-ce que vous pouvez partager avec nous l'URL du WMS ? Ça aiderait beacoup à comprendre qu'est-ce qu'il passe.

-----
_Hi @Greekoss, could you share the WMS's URL with us? That'll help a lot to understand what's happening here._

**Comment by Greekoss** [comment]
https://wxs.ign.fr/administratif/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities

https://wxs.ign.fr/cartes/geoportail/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities

Cela s'implique à l'ensemble des WMS IGN et d'autres , les couches WFS on le même soucis et l'extension Quick map service télécharge difficilement les données du géoportail

**Comment by agiudiceandrea** [comment]
It seems to me there is an incorrect translation in France language. @Greekoss, could you please change the GUI language to American English and try again? Could you please also add an English description of the issue?

**Comment by gacarrillor** [comment]
> @Greekoss, I don't see any issue using the WMS https://wxs.ign.fr/administratif/geoportail/r/wms?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetCapabilities with QGIS 3.28 on Windows.

Neither do I on Linux (QGIS 3.28.6).

However, I haven't been able to test it on QGIS 3.32, used by @Greekoss.

**Comment by gacarrillor** [comment]
QGIS 3.30 can also load the WMS with no issue.

![image](https://github.com/qgis/QGIS/assets/652785/0f84e5e7-a45e-45eb-b832-55602e960208)

**Comment by alexbruy** [comment]
No issues with the latest master (9b2c94e2e34b9d61c809b133887c3b45188156ae).

**Comment by pnrm** [comment]
Hello,
We have the same problem with the recent ign flow https://data.geopf.fr/private/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities
since version 3.34.6 of QGIS Windows 10 (it works on previous versions).
![image](https://github.com/qgis/QGIS/assets/18323883/a3d2c810-7d0d-4880-861e-4016998c9110)
