### ISSUE TITLE
switched headers in [join attributes by nearest]

### ISSUE THREAD

**Issue by HenkLenting** [qgis/QGIS#53850]
### What is the bug or the crash?

when joining attributes by nearest, column "A" and "B" were partially switched. The header for the joined column "A" showed data from column "B" and vice versa

### Steps to reproduce the issue

in the processing toolbox, choose [Join attributes by nearest]
Under [layer 2 fields to copy] first select a field way down the list, in my case field number 11
close  [layer 2 fields to copy]
open  [layer 2 fields to copy] again, select a field on the top of the list, in my case field number 2
I also added a joined prefix (not sure if relevant)
save to file
Run

### Versions

QGIS version
3.22.14-Białowieża
QGIS code revision
4cde646c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
b4udignl2
2.3.0
BGTImport
3.16
FreehandRasterGeoreferencer
0.8.3
ImportPhotos
3.0.4
kmltools
3.1.26
MapsPrinter
0.9
pdokservicesplugin
4.1.3
qfieldsync
v3.4.4
splitmultipart
1.0.0
SpreadsheetLayers
2.0.1
topo_tijdreis
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@HenkLenting thanks for reporting. QGIS 3.22 is no longer supported. Could you please actually try if the issue does occur using a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) as requested in the issue report form? Could you please provide sample layers with which the issue occurs?
