### ISSUE TITLE
QGIS crash when I want to open Attribute table

### ISSUE THREAD

**Issue by cvejaa** [qgis/QGIS#53870]
### What is the bug or the crash?

Hi,

I have layers with millions of features, and I have loaded those layers via GeoServer. Every time I try to 'Open Attribute table' QGIS crashes. I have changed the settings -> Data Sources to the 'Show Features Visible on Map' and when I meninge to open the attributes table -> try to 'zoom map to the selected rows' QGIS crashes.

BR,
Aleksandar

### Steps to reproduce the issue

1. Open QGIS
2. Add layers through GeoServer (no problem to load)
3. zoom into some area
4. right click on the layer 
5. Open the Attribute table
6. QGIS (Not Responding) for a while time
7. Error message 

### Versions

QGIS version
3.10.13-A Coruña
QGIS code revision
311f3bbade
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.1.4
Running against GDAL/OGR
3.1.4
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
6.3.2
Running against PROJ
Rel. 6.3.2, May 1st, 2020
OS Version
Windows 10 (10.0)
Active python plugins
DigitizingTools; 
feature_finder; 
go2streetview; 
hyperoptic_log_in; 
hz_tracker; 
pluginbuilder3; 
plugin_reloader; 
qfieldsync; 
quick_map_services; 
ZoomToPostcode; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@cvejaa, thanks for reporting. QGIS 3.10 is no longer supported. Please try if the issue does occur using a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) as requested in the issue report form.

**Comment by cvejaa** [comment]
@agiudiceandrea  I have installed the QGIS3.32.1 version and still have the same problem, QGIS crashes when I try to open attributes table for layer which contain over million features.

**Comment by agiudiceandrea** [comment]
@cvejaa, how dows Geo Server serves the layer? Is it a WFS? Have you tried if the issue does occur using a new QGIS user profile without any external plugin installed? What is the "Error message" displayed by QGIS? Could you provide the stack trace displayed in the QGIS crash handler window, if any?

**Comment by nyalldawson** [comment]
This is still waiting on submitter feedback, at the moment there's insufficient detail
