### ISSUE TITLE
Inconveniente al crear un poligono

### ISSUE THREAD

**Issue by santiago77182** [qgis/QGIS#53884]
### What is the bug or the crash?

El problema  es al querer delimitar una capa ( con un poligono), el inconveniente lo tengo al delimitar la zona, me sale un relleno al fondo del mismo que no me deja visualizar los vértices, intente poniéndole la opción sin relleno , pero me sigue saliendo con el mismo inconveniente.

### Steps to reproduce the issue

![image0](https://github.com/qgis/QGIS/assets/140027738/3c23b64f-6638-4d06-9776-739c6bfa0d8f)
![image1](https://github.com/qgis/QGIS/assets/140027738/c9198bd2-f36e-469e-bdfb-645521fbdb3c)

### Versions

Mi version de Qgis es 3.16.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@santiago77182, thanks for reporting. QGIS 3.16 is no longer supperted. Please actually try if the issue does occur using a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) as requested in the issue report form. Could you please also add a description in English?
