### ISSUE TITLE
3.32.0 Lima lose usernames and passwords for wms connections

### ISSUE THREAD

**Issue by Laatulupaus** [qgis/QGIS#53893]
### What is the bug or the crash?

When you add a new wms connection, everyone else's connection passwords and usernames disappear from memory

### Steps to reproduce the issue

_

### Versions

QGISin versio
3.32.0-Lima
QGIS-koodin versio
311a8cb8a6
Qt:n versio
5.15.3
Python-versio
3.9.5
GDAL/OGR:n versio
3.7.0
PROJ-versio
9.2.1
EPSG-rekisteritietokannan versio
v10.088 (2023-05-13)
GEOS-versio
3.11.2-CAPI-1.17.2
SQLite-versio
3.41.1
PDAL-versio
2.5.3
PostgreSQL:n asiakkaan versio
15.2
SpatiaLite-versio
5.0.1
QWT-versio
6.1.6
QScintilla2-versio
2.13.1
Käyttöjärjestelmän versio
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Please provide more details. Are you using auth database or basic auth? What do you mean by "disappear from memory": credentials are erased from the connection settings or from the currently loaded layers? Have you tried with the new profile?
