### ISSUE TITLE
DB Manager fail

### ISSUE THREAD

**Issue by DRainGMatics** [qgis/QGIS#53896]
### What is the bug or the crash?

I can't add new connection in PostGIS from the DB Manager tab.
The mouse right click doesn't work, no pop up command appear, no other commands are available.

### Steps to reproduce the issue

1. Go to DB Manager window
2. right click from PostGIS data source in order to add a new connection
3. it doesn't work, it doesn't apper any "add new connection" tab

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @DRainGMatics, the "New Connection…" context menu action is currently only available for GPKG and Spatialite
https://github.com/qgis/QGIS/blob/3eeaf5b96cc2923da5ab91567ed42777f7b570f0/python/plugins/db_manager/db_tree.py#L138C1-L139
Could you please use a more meaningful title for this report?
I would change this report from an issue report to a feature request. What do you think?
