### ISSUE TITLE
Unicode error (warning) in "User expressions" log panel

### ISSUE THREAD

**Issue by phidrho** [qgis/QGIS#53897]
### What is the bug or the crash?

I created a custom user expression and saved it to the disk with name "oib_extract.py" from QGIS.
My function contains docstring ending with triple-quote.

I didn't see this bug before 3.32.0 Lima.

When I open QGIS I get following error in `User expressions` tab on `Log Messages` panel with contents:

```
2023-07-21T13:45:48     WARNING    The user expression oib_extract is not valid
             Traceback (most recent call last):
              File "C:\OSGeo4W/apps/qgis/./python\qgis\user.py", line 46, in load_user_expressions
              __import__("expressions.{0}".format(name), locals(), globals())
              File "C:\OSGeo4W/apps/qgis/./python\qgis\utils.py", line 888, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:\Users/vedran.stojnovic/AppData/Roaming/QGIS/QGIS3\profiles\default/python\expressions\oib_extract.py", line 15
              """
              ^
             SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe8 in position 10: invalid continuation byte
```

When I open file that contains code with Visual Studio Code I can see that the file is saved with [windows-1250](https://en.wikipedia.org/wiki/Windows-1250) encoding which is default my machine as set in Windows OS - see picture:
![encoding settings](https://github.com/qgis/QGIS/assets/1849293/8ee6b5c4-8f6f-4ba0-a60e-93282c9c63dd)

So Qt obviously uses default Windows setting while writing and reading `User expressions` source code to disk - since everything looks fine when I read code myself from QGIS, but python code in `C:\OSGeo4W/apps/qgis/./python\qgis\user.py` doesn't seem to open it properly and reports a warning.

### Steps to reproduce the issue
See video: [qgis warning custom functions](https://youtu.be/Bc7ttBzyWoE).
Create user expression on Windows OS with locale setting that doesn't use UTF-8 by default and save it to disk. Then restart QGIS and open `Log Messages` panel with `User expressions` tab.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.0-Lima | QGIS code revision | 311a8cb8
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
document_management_system | 0.3.3
flight_planner | 0.6.1
geometric_attributes | 0.4
GroupStats | 2.2.7
inspireatomclient | 0.8.1
kmltools | 3.1.29
networks | 2.7.8
qfieldsync | v4.5.0
QGIS3-getWKT | 1.5
topojson_writer | 0.1.1
wfsclient | 0.9.11
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.32.0-Lima
QGIS code revision
[311a8cb8](https://github.com/qgis/QGIS/commit/311a8cb8)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
document_management_system
0.3.3
flight_planner
0.6.1
geometric_attributes
0.4
GroupStats
2.2.7
inspireatomclient
0.8.1
kmltools
3.1.29
networks
2.7.8
qfieldsync
v4.5.0
QGIS3-getWKT
1.5
topojson_writer
0.1.1
wfsclient
0.9.11
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@phidrho, could you please specify with which QGIS version the issue doesn't occur?
It seems to me Python assumes utf-8 as encoding for importing modules.

**Comment by phidrho** [comment]
> @phidrho, could you please specify with which QGIS version the issue doesn't occur?
> It seems to me Python assumes utf-8 as encoding for importing modules.

I can't say for sure that this didn't exist, but I don't remember I've seen it before. I created this custom user expression sometime in 3.28.
I will try to create a new user expression in new version of QGIS, to see its behavior when saving and opening in new version and will report back.

**Comment by phidrho** [comment]
@agiudiceandrea
I did a bigger research on this.
Only if the script contains local letters, e.g. either one of `šđčćž` then it's saved to disk with local encoding and QGIS displays a warning. The workaround is to manually put a Python encoding instruction at the beginning of the script (in my case it's `cp1250` which is the same as `windows1250` in VSCode).

I think that relying on users to manually put an encoding line is not a good design. The entire editor and environment should work in UTF-8, including saving to and reading from disk, because that is how it's presumed by the Python interpreter, and leave manually setting up encoding settings only for advanced users and Python programmers.

I recorded a [video](https://youtu.be/Bc7ttBzyWoE) to see the bug in practice.
This shouldn't be a hard bug to fix in my opinion, but maybe it is because of Qts implementation.

**Comment by agiudiceandrea** [comment]
@phidrho, thanks for providing the screen recording. It's now more clear where the issue occurs: the "Function Editor" dialog window.
It seems the "Function Editor" writes the user expression using the local system encoding, while Python expects it to be in the UTF-8 encoding.
