### ISSUE TITLE
Active label masks stopping colour ramp being applied to DEM on layout export

### ISSUE THREAD

**Issue by Fordonian** [qgis/QGIS#53901]
### What is the bug or the crash?

When exporting from a layout my DEM has a custom ramp applied which exports, however when applying label masks between a point layer and contours, the ramp shows in the layout but does not export.

I've seen some other layout issues here but not this specific one. The problem stops if I turn the masks off. Attached image with the ramp applied does have some other styling applied to the labels but not the masks. Tried several times with the masks on and off and it always occurs when they're switched on between the labels and contours.

![qgis dem export with ramp 220723](https://github.com/qgis/QGIS/assets/39958061/e5dd629c-dbb4-4bdc-a17a-60f8c45ae7d3)
![qgis dem export problem 220723](https://github.com/qgis/QGIS/assets/39958061/c7a5cd3d-dbf8-4d10-9489-9a4d27530718)

### Steps to reproduce the issue

1. Apply label masks via the layer style tab
2.  Select the vector (contour in this case) 
3. Go to layout and export 

### Versions

QGIS version
3.28.3-Firenze
QGIS code revision
c12bcb2f76c
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AcATaMa
23.4
area_weighted_average
0.2
batch_gps_importer
version 1.0.1
BGTImport
3.17
BivariateRenderer
1.0.1
Climb
1.1
concavehull
2.0
DataPlotly
4.0.3
DEMto3D
3.51
floodrisk2
0.7
gml_application_schema_toolbox
1.3.1
GpxSegmentImporter
2.5
HCMGIS
23.7.19
inundation_calculator
0.1
mapswipetool_plugin
1.2
Mergin
2023.1
OpenTopography-DEM-Downloader
2.0
OSMDownloader
1.0.3
OSTranslatorII
3.2.4
planet_explorer
2.3.0
PluginLoadTimes
3.0.2
postgisQueryBuilder
2.0.1
postgis_geoprocessing
0.9
Qgis2threejs
2.7.1
qgis_resource_sharing
1.0.0
qProf
0.5.1
QuickOSM
2.2.2
SemiAutomaticClassificationPlugin
7.10.11
Smart_Map
1.3.3
topo_tijdreis
1.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Looks like a duplicate of https://github.com/qgis/QGIS/issues/49488
