### ISSUE TITLE
Change the unit's style in the Elevation Profile in Print Composer

### ISSUE THREAD

**Issue by JuanBreva** [qgis/QGIS#53916]
### Feature description

It seems it is not possible to customise the way the units are displayed in the Elevation Profile in Print Composer. Although I understand it is not possible to change the units themselves, like from metres to feet, it would be nice, for the sake of a better styling, to convert from metres to kilometres, so the labels don't show units like 200000, 300000 or 400000 metres instead of, much easier to understand, 200, 300 or 400 km.

Also, the only way to add the units in the labels is changing the format to "Currency", which is not totally accurate when displaying distances, for example.

**Comment by DelazJ** [comment]
Is this not convered by https://github.com/qgis/QGIS/pull/53235 or do I misunderstand the request?
