### ISSUE TITLE
Qgis Custom Build Missing Erdas Compressed Wavelength file format

### ISSUE THREAD

**Issue by SI-Lab** [qgis/QGIS#53923]
### What is the bug or the crash?

Finally built Qgis on windows 11 using cmake/vs 2019. Working well thought cant load ECWs files due to missing Erdas compressed wavelength file data type.

During cmake build, what could I have missed to check or uncheck?

any help will be highly appreciated. 

### Steps to reproduce the issue

Run the application under development environment.
Click on Layer menu-Add Layer-Add Raster Layer-Raster dataset file type

Error: No ecws file type

### Versions

Qgis 3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
Does your GDAL contain ECW support?

**Comment by SI-Lab** [comment]
> Does your GDAL contain ECW support?

Hello Sir,
I am not sure. How do i check on that?

**Comment by SI-Lab** [comment]
I used the OSGeo4W(Qgis-dev) for my build.

**Comment by jef-n** [comment]
Did you install gdal-ecw?

**Comment by SI-Lab** [comment]
> Did you install gdal-ecw?

Yes. And i have 3 files inside gdal plugins
C:\OSGeo4W\apps\gdal\lib\gdalplugins----gdal_ECW_JP2ECW.dll
                                                            ----Driver
                                                           -----gdal_MrSID.dll

**Comment by SI-Lab** [comment]
@jef-n Thank very much.

It worked. Had to rebuild from scratch. I can now use ECW files.
