### ISSUE TITLE
Processing scripts cannot be opened, saved or run in Processing Script Editor

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#53921]
### What is the bug or the crash?

![grafik](https://github.com/qgis/QGIS/assets/7661092/a81f5a01-e79d-4009-9a33-5ea14aab9c40)

The four buttons on the left (Open, Save, Save as, Run) as well as the Find button do not trigger anything.

### Steps to reproduce the issue

1. Use any of the three ways to open the Processing Script Editor (Create new script or open existing)
2. Click the buttons
3. Nothing happens

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.32.0-Lima | QGIS code revision | 311a8cb8a6
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.6
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Confirmed by grayshade on IRC using QGIS via Flatpak.

Ctrl-S, Ctrl-F etc also do not do anything.

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/pull/53908

**Comment by kannes** [comment]
Who gave you a time machine!
