### ISSUE TITLE
Vetor tab still exist in my language when switching to english

### ISSUE THREAD

**Issue by mastrolube** [qgis/QGIS#53936]
### What is the bug or the crash?

Hi, I've switched the language of QGIS from Italian to English.
I have the tab **Vector** and also **Vettore** (the translation in Italian of vector).
The first one is almost empty, the second contains all the options. Also the subfolder are in italian instead of english
![immagine](https://github.com/qgis/QGIS/assets/52335835/a9e247ba-5574-4c9b-a6f3-49ec8fedd8ea)
![immagine](https://github.com/qgis/QGIS/assets/52335835/8de5c95a-c826-4721-ad08-e51d95547f7d)
![immagine](https://github.com/qgis/QGIS/assets/52335835/6f6bd10f-b3d0-492c-9ecc-026b66505967)

### Steps to reproduce the issue

Switch the language from Italian to English

### Versions

3.32

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by mblesius** [comment]
I have the same problem with the German locale.

**Comment by agiudiceandrea** [comment]
It seems to me the same issue as reported at https://github.com/qgis/QGIS/issues/52449? @mastrolube @mblesius can you confirm?

**Comment by mastrolube** [comment]
Sort of, in my case I have both ventor menu, in English and Italian (only the last one is populated).
The other guy doens't have the English version at all

**Comment by nicogodet** [comment]
Batch layer saver likely comes from a plugin
Did you actually try with a new QGIS user profile ?

**Comment by DelazJ** [comment]
> Sort of, in my case I have both vector menu, in English and Italian (only the last one is populated).
The other guy doens't have the English menu at all

@mastrolube This is the same issue as #52499. The screenshot there is just not wide enough to show the place where the English "vector" menu is supposed to be. Its german version is at the end, probably populated as yours.
