### ISSUE TITLE
QGIS crashes at startup when opening a project

### ISSUE THREAD

**Issue by tomboudiboudi** [qgis/QGIS#53939]
### What is the bug or the crash?

Hi,

Before saving my project, I just had set a scale-based rule on a specific layer to define line thickness relative to map scale. Just after, I saved my project, and it started to freeze. Then, I restarted QGIS and try opening the project. QGIS get it loaded to 100%, then crash immediately. Now, it crashes that way each time I try to open this project.

I seriously don't know what to do, and I'm quite scared of losing hours of work...

## Report Details

**Crash ID**: 93ed11fd1bac2a1657efafea858a49d69e021fb2

**Stack Trace**

```

RaiseException :
__FrameHandler4::CxxCallCatchBlock frame.cpp:1391
RcConsolidateFrames :
QgsProject::readVersionMismatchOccurred :
QgsSimpleLineSymbolLayer::drawPathWithDashPatternTweaks :
QgsSimpleLineSymbolLayer::renderPolyline :
QgsLineSymbolLayer::drawPreviewIcon :
QgsSymbol::drawPreviewIcon :
QgsSymbolLayerUtils::symbolPreviewPixmap :
QgsSymbolLegendNode::data :
QgsLayerTreeModel::legendIconEmbeddedInParent :
QgsLayerTreeModel::data :
QSortFilterProxyModel::data :
QModelIndex::data :
QStyledItemDelegate::initStyleOption :
QStyledItemDelegate::sizeHint :
QTreeView::indexRowSizeHint :
QTreeViewPrivate::itemHeight :
QTreeViewPrivate::updateScrollBars :
QTreeView::updateGeometries :
QAbstractItemView::doItemsLayout :
QTreeView::doItemsLayout :
QTreeView::sizeHintForColumn :
QHeaderView::resizeSections :
QHeaderView::sectionSize :
QHeaderView::currentChanged :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsLayerTreeView::setCurrentLayer :
QgisApp::addProject :
QgisApp::openProject :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.30.3-'s-Hertogenbosch
QGIS code revision: 2411cec1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

QGIS Version: 3.30.3-'s-Hertogenbosch

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
If the symbology is the issue could you provide a test case with the same symbology to replicate?

To salvage your project you could edit the content of the QGZ to remove the symbology you created and see if that fixes the crash, you might need to be careful when removing stuff in text form to not cause more crashes.

**Comment by tomboudiboudi** [comment]
Hi roya0045 and thanks for your reply,

What do you mean by providing a test case ?

When I open the .qgz file in Notepad++, I get this kind of code... Is there a way to make it readable ?
![image](https://github.com/qgis/QGIS/assets/136840794/1b816008-9b99-4758-88d4-00286198889d)

**Comment by roya0045** [comment]
> Hi roya0045 and thanks for your reply,
> 
> What do you mean by providing a test case ?
> 
> When I open the .qgz file in Notepad++, I get this kind of code... Is there a way to make it readable ? ![image](https://user-images.githubusercontent.com/136840794/255944764-1b816008-9b99-4758-88d4-00286198889d.png)

unzip it first

**Comment by tomboudiboudi** [comment]
Thanks, just opened it in Notepad++.
I know the name of the layer involved (name : 3e ligne), could you guide me to find the lines about its symbology ?
Here is the .qgs file I just saved to .txt :
[230721_DVA_TLS_AFNT.txt](https://github.com/qgis/QGIS/files/12162814/230721_DVA_TLS_AFNT.txt)

**Comment by tomboudiboudi** [comment]
Actually, the problematic layer (3e ligne) is packed inside PLAN_STRATEGIQUE.gpkg

**Comment by nyalldawson** [comment]
Can you attach a zip containing both the qgs file and the offending geopackage? This is required to reproduce the crash.
