### ISSUE TITLE
Scale bar is unreadable

### ISSUE THREAD

**Issue by TurntSnackoo** [qgis/QGIS#53946]
### What is the bug or the crash?

The scale bar and only the scale bar text window has shrunk so as to obscure all of the numbers. 
![image](https://github.com/qgis/QGIS/assets/140560866/d0a57caf-5aee-4f9f-b094-2847e7ed2214)
I've tried removing it and re-adding it to the status bar, I've tried removing everything else from the status bar, I've tried changing the font sizes and text colors, that didn't fix it either.

### Steps to reproduce the issue

Open Qgis. Open project. See error.

### Versions

QGIS version
3.30.1-'s-Hertogenbosch
QGIS code revision
9035a01e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.3
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
please update to 3.32.1
This should have been fixed since 3.30.1

**Comment by TurntSnackoo** [comment]
Right, sorry for the wait. Yes, updating it fixed it, thank you.
