### ISSUE TITLE
Halfway through the installation, the installation program is stuck

### ISSUE THREAD

**Issue by KaiTang2** [qgis/QGIS#53948]
### What is the bug or the crash?

bug?

### Steps to reproduce the issue

run the *.msi

### Versions

3.28.0 ~ 3.30.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

![image](https://github.com/qgis/QGIS/assets/33851010/a5da07dc-c5a5-473c-b538-452dd436ccad)

![image](https://github.com/qgis/QGIS/assets/33851010/1a8486c4-4875-447a-a177-c40ca2d0cde0)
like this ,Each version will be stuck in this position.Although the things being installed in each version are different, the Progress bar stops at this location

My os is windows11 Windows 11 Home Version 21H2
os version is 22000.2176

**Comment by agiudiceandrea** [comment]
@KaiTang2, thanks for reporting. I suggest you to file the issue report to https://trac.osgeo.org/osgeo4w/, since this issue is related to the installer/packaging infrastructure.

**Comment by alexbruy** [comment]
Is this still an issue with latest versions?
