### ISSUE TITLE
processing algorithm execution problem

### ISSUE THREAD

**Issue by vjohannn** [qgis/QGIS#53945]
### What is the bug or the crash?

Version de QGIS : 3.30.0-'s-Hertogenbosch
Révision du code : f186b8efe0e
Version de Qt : 5.15.3
Version de Python : 3.9.5
Version de GDAL : 3.6.2
Version de GEOS : 3.11.1-CAPI-1.17.1
Version de Proj : Rel. 9.1.1, December 1st, 2022
Version de PDAL : 2.4.3 (git-version: f8d673)
Algorithme commencé à: 2023-07-25T09:38:22
Démarrage de l'algorithme 'r.fill.dir'…
Paramètres en entrée:
{ '-f' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'areas' : 'TEMPORARY_OUTPUT', 'direction' : 'TEMPORARY_OUTPUT', 'format' : 0, 'input' : 'C:/Users/AÏSSI/Documents/SIG ET TELEDETECTION/Epreuve Rattrapage sig/Epreuve Repris/Raster.tif', 'output' : 'TEMPORARY_OUTPUT' }

g.proj -c wkt="C:/Users/AÏSSI/AppData/Local/Temp/processing_uNUfjC/7b8cdd3839534f28986412356e43d9a4/crs.prj"
r.in.gdal input="C:\Users\AÏSSI\Documents\SIG ET TELEDETECTION\Epreuve Rattrapage sig\Epreuve Repris\Raster.tif" band=1 output="rast_64bf89ff0cfda2" --overwrite -o
g.region n=12.432647711308041 s=6.204304965503286 e=3.8758686548985914 w=0.7368921515820746 res=0.004510023711661662
r.fill.dir input=rast_64bf89ff0cfda2 format="grass" output=outputfeca37f186db41979e85a2776a81b9b4 direction=directionfeca37f186db41979e85a2776a81b9b4 areas=areasfeca37f186db41979e85a2776a81b9b4 --overwrite
g.region raster=outputfeca37f186db41979e85a2776a81b9b4
r.out.gdal -t -m input="outputfeca37f186db41979e85a2776a81b9b4" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_uNUfjC\181c28f7bf08478a95ede8d271f600c0\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=directionfeca37f186db41979e85a2776a81b9b4
r.out.gdal -t -m input="directionfeca37f186db41979e85a2776a81b9b4" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_uNUfjC\746f59123c8c4cc3a4fe9a7162380408\direction.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=areasfeca37f186db41979e85a2776a81b9b4
r.out.gdal -t -m input="areasfeca37f186db41979e85a2776a81b9b4" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_uNUfjC\00b5199585f947ddaa14f97fd5218f5c\areas.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
DÃ©marrage du SIG GRASS ...
ATTENTION: Le verrouillage concurrent de jeux de cartes n'est pas pris en charge dans Windows
Nettoyage des fichiers temporaires ...
access: No such file or directory
DÃ©marrage du SIG GRASS ...
ATTENTION: Le verrouillage concurrent de jeux de cartes n'est pas pris en charge dans Windows
Nettoyage des fichiers temporaires ...
access: No such file or directory
Execution completed in 1.59 secondes
Résultats:
{'areas': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_uNUfjC\\00b5199585f947ddaa14f97fd5218f5c\\areas.tif',
'direction': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_uNUfjC\\746f59123c8c4cc3a4fe9a7162380408\\direction.tif',
'output': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_uNUfjC\\181c28f7bf08478a95ede8d271f600c0\\output.tif'}

Chargement des couches de résultat
Les couches suivantes n'ont pas été générées correctement.
• C:/Users/AÏSSI/AppData/Local/Temp/processing_uNUfjC/00b5199585f947ddaa14f97fd5218f5c/areas.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_uNUfjC/181c28f7bf08478a95ede8d271f600c0/output.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_uNUfjC/746f59123c8c4cc3a4fe9a7162380408/direction.tif
Vous pouvez vérifier le Panel de messages du journal dans la fenêtre principale de QGIS pour trouver plus d'informations à propos de l'exécution de l'algorithme.

____________________________________________________________________ (After installing with another version QGIS 3.16.15 - Hannover still the same problem)

Version de QGIS : 3.16.15-Hannover
Révision du code : e7fdad64
Version de Qt : 5.15.2
Version de GDAL : 3.4.0
Version de GEOS : 3.10.0-CAPI-1.16.0
Version de Proj : Rel. 8.2.0, November 1st, 2021
Traitement de l'algorithme…
Démarrage de l'algorithme 'r.fill.dir'…
Paramètres en entrée:
{ '-f' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'areas' : 'TEMPORARY_OUTPUT', 'direction' : 'TEMPORARY_OUTPUT', 'format' : 0, 'input' : 'C:/Users/AÏSSI/Documents/SIG ET TELEDETECTION/Epreuve Rattrapage sig/Epreuve Repris/Raster.tif', 'output' : 'TEMPORARY_OUTPUT' }

g.proj -c wkt="C:/Users/AÏSSI/AppData/Local/Temp/processing_KWfTXV/cf1d0dc8db60424e9c94e4f47da4222a/crs.prj"
r.in.gdal input="C:\Users\AÏSSI\Documents\SIG ET TELEDETECTION\Epreuve Rattrapage sig\Epreuve Repris\Raster.tif" band=1 output="rast_64bf8f17e72c52" --overwrite -o
g.region n=12.432647711308041 s=6.204304965503286 e=3.8758686548985914 w=0.7368921515820746 res=0.004510023711661662
r.fill.dir input=rast_64bf8f17e72c52 format="grass" output=output168a2d32c0de42449503c887d9c69bd0 direction=direction168a2d32c0de42449503c887d9c69bd0 areas=areas168a2d32c0de42449503c887d9c69bd0 --overwrite
g.region raster=output168a2d32c0de42449503c887d9c69bd0
r.out.gdal -t -m input="output168a2d32c0de42449503c887d9c69bd0" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_KWfTXV\ff88cef593b0474c8dbad35b1e7eeafc\output.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=direction168a2d32c0de42449503c887d9c69bd0
r.out.gdal -t -m input="direction168a2d32c0de42449503c887d9c69bd0" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_KWfTXV\5d7dc7dda5464a81989d88e4551c3938\direction.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
g.region raster=areas168a2d32c0de42449503c887d9c69bd0
r.out.gdal -t -m input="areas168a2d32c0de42449503c887d9c69bd0" output="C:\Users\AÏSSI\AppData\Local\Temp\processing_KWfTXV\8a53fc25770047f880b95416f5244f01\areas.tif" format="GTiff" createopt="TFW=YES,COMPRESS=LZW" --overwrite
DÃ©marrage du SIG GRASS ...
ATTENTION: Le verrouillage concurrent de jeux de cartes n'est pas pris en charge dans Windows
Nettoyage des fichiers temporaires ...
access: No such file or directory
Traceback (most recent call last):
File "C:\PROGRA~1/QGIS31~1.15/apps/qgis-ltr/./python/plugins\processing\algs\grass7\Grass7Algorithm.py", line 434, in processAlgorithm
Grass7Utils.executeGrass(self.commands, feedback, self.outputCommands)
File "C:\PROGRA~1/QGIS31~1.15/apps/qgis-ltr/./python/plugins\processing\algs\grass7\Grass7Utils.py", line 398, in executeGrass
for line in iter(proc.stdout.readline, ''):
File "C:\PROGRA~1\QGIS31~1.15\apps\Python39\lib\encodings\cp1252.py", line 23, in decode
return codecs.charmap_decode(input,self.errors,decoding_table)[0]
UnicodeDecodeError: 'charmap' codec can't decode byte 0x8f in position 29: character maps to <undefined>

L’exécution a échoué après 2.86 secondes

Chargement des couches de résultat
Les couches suivantes n'ont pas été générées correctement.
• C:/Users/AÏSSI/AppData/Local/Temp/processing_KWfTXV/5d7dc7dda5464a81989d88e4551c3938/direction.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_KWfTXV/8a53fc25770047f880b95416f5244f01/areas.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_KWfTXV/ff88cef593b0474c8dbad35b1e7eeafc/output.tif
Vous pouvez vérifier le Panel de messages du journal dans la fenêtre principale de QGIS pour trouver plus d'informations à propos de l'exécution de l'algorithme.

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/123867560/3aec00ca-c527-4490-a255-5c547f8b2067

### Versions

Version de QGIS
3.30.0-'s-Hertogenbosch
Révision du code
f186b8efe0e
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.2
Version de Proj
9.1.1
Version de la base de données du registre EPSG
v10.076 (2022-08-31)
Version de GEOS
3.11.1-CAPI-1.17.1
Version de SQLite
3.39.4
Version de PDAL
2.4.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
LecoS
3.0.1
processing_saga_nextgen
0.0.7
SRTM-Downloader
3.1.17
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

**_Bug title:_** Error when using GRASS GIS tools in QGIS

**_Description :_**

I'm having trouble using GRASS GIS tools in QGIS. I have installed several versions of QGIS, including version 3.30.0-'s-Hertogenbosch, and still have the same problem.

Here is the flow of the problem:

I open QGIS and load a raster file (e.g. grd, gri, vrt).

Then I try to use GRASS GIS tools such as r.fill.dir, r.watershed, r.tovect, etc. on the loaded raster.

However, every time I try to run one of these tools, I get an error saying "access: No such file or directory".

I have tried reinstalling QGIS, changing temporary files settings, specifying another folder for output files, but the problem persists.

Here is an example of the error I get:
-----------------------------------------------------
Version de QGIS : 3.30.0-'s-Hertogenbosch
Révision du code : f186b8efe0e
Version de Qt : 5.15.3
Version de Python : 3.9.5
Version de GDAL : 3.6.2
Version de GEOS : 3.11.1-CAPI-1.17.1
Version de Proj : Rel. 9.1.1, December 1st, 2022
Version de PDAL : 2.4.3 (git-version: f8d673)

Démarrage de l'algorithme 'r.fill.dir'…
Paramètres en entrée:
{ '-f' : False, 'GRASS_RASTER_FORMAT_META' : '', 'GRASS_RASTER_FORMAT_OPT' : '', 'GRASS_REGION_CELLSIZE_PARAMETER' : 0, 'GRASS_REGION_PARAMETER' : None, 'areas' : 'TEMPORARY_OUTPUT', 'direction' : 'TEMPORARY_OUTPUT', 'format' : 0, 'input' : 'C:/Users/AÏSSI/AppData/Local/Temp/processing_njOuud/61221a85d5d8448ea33f5135d68d3a3f/OUTPUT.tif', 'output' : 'TEMPORARY_OUTPUT' }

...

Execution completed in 1.36 secondes
Résultats:
{'areas': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_njOuud\\7523e6114c5148efaed9799fc2dae67f\\areas.tif',
'direction': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_njOuud\\417bde55ae5b4939a07d332ac08ebba7\\direction.tif',
'output': 'C:\\Users\\AÏSSI\\AppData\\Local\\Temp\\processing_njOuud\\edaf0d30e30544feba398584606cf26b\\output.tif'}

Chargement des couches de résultat
Les couches suivantes n'ont pas été générées correctement.
• C:/Users/AÏSSI/AppData/Local/Temp/processing_njOuud/417bde55ae5b4939a07d332ac08ebba7/direction.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_njOuud/7523e6114c5148efaed9799fc2dae67f/areas.tif
• C:/Users/AÏSSI/AppData/Local/Temp/processing_njOuud/edaf0d30e30544feba398584606cf26b/output.tif

-----------------------------------------------------

I would like to report this issue as it affects my ability to effectively use the GRASS GIS tools in QGIS to perform advanced geospatial analyses.

Hope this information will help you to solve the problem.

Cordially,
AISSI

**Comment by nicogodet** [comment]
Can you try with layers stored in path without accented characters and spaces ?
Your user contains `Ï` and folders have spaces in folder names.
