### ISSUE TITLE
THE EDITOR ISNT ACTIVATE

### ISSUE THREAD

**Issue by caroline2199** [qgis/QGIS#53947]
### What is the bug or the crash?

HELP ME¡ 
THE EDITION IS WRONG 
IT ISNT ACTIVATE
![image](https://github.com/qgis/QGIS/assets/120980376/f9e2d45c-240c-41b3-8503-bc4ceb0b63d6)

### Steps to reproduce the issue

BARRA DE HERRAMIENTAS
DIGITALIZACION 

### Versions

![image](https://github.com/qgis/QGIS/assets/120980376/dd101186-b619-498d-8650-043ed6d90340)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by caroline2199** [comment]
PLEASE HELP ME :C

**Comment by nyalldawson** [comment]
Your dataset is read-only. There's many reasons why this may be the case:

- A data format which only has read only support
- A database source where you do not have edit permissions
- A dataset stored in a read-only folder
- A project or layer level setting which has set the layer as read only in your project.

There's insufficient detail to diagnose further here -- please open this question on gis.stackexchange.com for user level support.

**Comment by caroline2199** [comment]
you have the reason. THANK YOU SO MUCH.
