### ISSUE TITLE
QGIS unusable in ubuntu 22.04.2

### ISSUE THREAD

**Issue by AnnaelleBenard** [qgis/QGIS#53957]
### What is the bug or the crash?

Lastest QGIS update is not usable in ubuntu 22.04.2 due to graphical bug

### Steps to reproduce the issue

1. get lastest versions of QGIS and QGIS-plugin-grass packages from ubuntu 22.04 repo (current version is 1:3.32.1+36jammy)
2. open QGIS

![Capture d’écran du 2023-07-26 16-25-55](https://github.com/qgis/QGIS/assets/70482681/018fde5d-4194-418e-a319-01151883f651)
![Capture d’écran du 2023-07-26 16-38-18](https://github.com/qgis/QGIS/assets/70482681/d24c8e7d-4255-4aa0-accb-e28ecb76fa2c)

### Versions

Can't use the QGIS interface, but package is 3.32.1 Lima

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Are you using a wayland session ?

**Comment by AnnaelleBenard** [comment]
> Are you using a wayland session ?

The issue is the same with both wayland and X11

**Comment by gremau** [comment]
I'm having this issue on Debian and it persisted after upgrading from 3.32.1 to 3.32.2. Perhaps related to a recent Qt update (just a guess though). System info:

QGIS version | 3.32.2-Lima | QGIS code revision | c0b88339649
Qt version | 5.15.10
Python version | 3.11.4
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.42.0
PostgreSQL client version | 15.4 (Debian 15.4-1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Debian GNU/Linux trixie/sid

Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

**Comment by parisa-hr** [comment]
I have that problem too, I can't build it in both Fedora 38 and Ubuntu 22.04.

**Comment by gremau** [comment]
Well for what its worth to anyone now... this seems to be a Qt scaling issue that is not specific to QGIS. It may be related to a recent update in Qt 5, and I'm not sure if QGIS configurations or system-wide configurations (I'm on Debian, seems like Ubuntu & Fedora is affected too) should be updated to fix it yet. For now I have worked around it by slightly scaling up the Qt ui when I launch QGIS by launching from the terminal with `env QT_SCALE_FACTOR=1.05 qgis` The QGIS goes back to normal when I do this, but perhaps a different scaling number will work better for others....

**Comment by alexbruy** [comment]
Seems not related to QGIS itself, rather some system configuration (maybe at DE/WM level). I'm can't reproduce on latest Ubuntu 22.04.

**Comment by Gabriel-Goes** [comment]
![qgis_interface_bug](https://github.com/qgis/QGIS/assets/82617518/0ecd1ad5-4b3c-427b-bf3b-5da2791f11b0)
![print_ok](https://github.com/qgis/QGIS/assets/82617518/11ebb41a-19d9-423a-8322-ce35ac34932a)

same erros here, today i discovered that it is an error of user configuration, like environment variables. when i run qgis with other user from my computer it works, but with my main user it does not. when i print env the variables are different for each user. But i did not figured it out how to solve the problem yet
