### ISSUE TITLE
QGis crashes when digitizing with snapping

### ISSUE THREAD

**Issue by Forstkarte** [qgis/QGIS#53956]
### What is the bug or the crash?

When we open a project with activated snapping, it crashes when we want to start digitizing.(since Version 3.30; reproduced the crash with 3.32.0).
We noticed, that this is not a problem, when you start the project and the first move is drawing a line with the default settings (no zooming, not activating any other layer etc.). When the initial line is drawn you can work as used to. Otherwise it crashes, sometimes even without one starting to draw a new line.

### Steps to reproduce the issue

1. Get in a Project with alot of different layers and enabled snapping (all layers or with advanced settings.
2. Zoom in and drawing a line
3. Crash

### Versions

Python Stack Trace
Windows fatal exception: access violation

Windows fatal exception: access violation

Thread 0x00003448 (most recent call first):

Stack Trace

QgsExpression::referencedColumns :
QgsProperty::prepare :
QgsPropertyCollection::prepare :
QgsSymbolLayer::prepareExpressions :
QgsSymbol::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::startRender :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.30.1-'s-Hertogenbosch
QGIS code revision: 9035a01e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

--------------------------------------------------------------------------------------------------------------------
Python Stack Trace
Windows fatal exception: access violation

Thread 0x00000494 (most recent call first):

Windows fatal exception: access violation

Thread 0x00000494 (most recent call first):

Stack Trace

QHashData::nextNode :
QgsPropertyCollection::prepare :
QgsSymbolLayer::prepareExpressions :
QgsSymbol::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::startRender :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

We are working with the advanced settings within snapping. 
We could also reproduce this crash when snapping on all layers. Never reproduced when only snapping on activated layer.
Tried to remove all Z and M values – still is crashing.

**Comment by roya0045** [comment]
The stacktrace points to something going with your symbology. Try figuring it out if that's the problem or snapping.

If you found the issue you can shared a sample project to reproduce it.

**Comment by Forstkarte** [comment]
Thanks for the hint @roya0045. 
It seemes like it has do to something with the symbology on the layer LinienGeruest in combination with snapping to it - but coudn't find the cause within the symbology. It isn't that complicated; there are layers with a way more specified ruleset within the symbology and they don't let QGIS crash.

Here would be the data for the project: 
[R_Operat.zip](https://github.com/qgis/QGIS/files/12181535/R_Operat.zip)

Way to reproduce the crash: 
1. Open the project
2. Zoom in or activate a non activated layer.
3. start editing on layer Linien with the preset snapping settings.
4. QGis crashes as soon as you move your mouse in the map area.

Way to get around the crash:
1. Open the project.
2. Don't zoom; don't to anything.
3. Start editing a line on layer Linien. (You don't have do save this initial line)
4. After the initial line is drawn you can zoom in activate and deactivate as many layers as you want and still can digitize new lines with the preset snapping setting; it won't crash again.
5. Have to redo this step everytime you open the project otherwise it just crashes. 

I really don't unterstand why this is happening, nether do i get why this work around works.

**Comment by Forstkarte** [comment]
We found the bug. -

**Comment by Forstkarte** [comment]
We think, we found the bug. 
It's within the symbology. In the expression builder for the colour. 
We used a:   **if(is_layer_visible(xx)= true, color_rgba( 255,255,0,255), color_rgba( 255,120,0,255)).**
As soon as we remove these expressions from within the symbology we can snap again, without QGIS chrashing as soon as we start to digitize.

The variable map_layers also isn't working probably  anymore; maybe this is also connected with the is_layer_visible bug.
consequential the variable layer in the Projectproperties shows a [<Kartenebene>,<Kartenebene>,<Kartenebene>...]

This prolem occoured since nearly a year.

**Comment by elpaso** [comment]
@Forstkarte why did you close this issue? If there is a crash it has to be fixed.

**Comment by Forstkarte** [comment]
Sorry, i didn't notice that.
Reopend it.

**Comment by Forstkarte** [comment]
Python Stack Trace
Windows fatal exception: access violation

Thread 0x00000ce8 (most recent call first):

Windows fatal exception: access violation

Thread 0x00000ce8 (most recent call first):



Stack Trace

QHashData::nextNode :
QgsPropertyCollection::prepare :
QgsSymbolLayer::prepareExpressions :
QgsSymbol::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::Rule::startRender :
QgsRuleBasedRenderer::startRender :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :



QGIS Info
QGIS Version: 3.34.4-Prizren
QGIS code revision: decd43dc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044


________________________________________________________________________________________________

QGIS still crashes with the new LTR-Version. Also tried it on the 3.6.0; still the same.

**Comment by stafoo** [comment]
Hello
I'm still experiencing this bug in QGIS 3.34.5 when editing features with active snap.
I can confirm this bug was not present in QGIS 3.28.
