### ISSUE TITLE
error installing Qgis "Firenze"

### ISSUE THREAD

**Issue by Sistemiinformatic** [qgis/QGIS#53953]
### What is the bug or the crash?

when installing Qgis I get the following errors:

![1](https://github.com/qgis/QGIS/assets/140610698/5dbd4b92-28e2-4bee-98fc-cf0a4fc701a2)
![2](https://github.com/qgis/QGIS/assets/140610698/1e70997d-404c-4bd1-b6a0-e782541bdd06)

### Steps to reproduce the issue

q

### Versions

VErsion Qgis 3.28.8
Windows 10 2H22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @Sistemiinformatic, thanks for reporting. I suggest you to file the issue report to https://trac.osgeo.org/osgeo4w/, since this issue is related to the installer/packaging infrastructure.

**Comment by alexbruy** [comment]
Looks like you are runinng the installer as a user with limited privileges. Does this happen if you have permissions to update registry entries?
