### ISSUE TITLE
QGIS custom Python expressions not loading on startup when containing non ASCII characters

### ISSUE THREAD

**Issue by MalikAlMaut** [qgis/QGIS#53955]
### What is the bug or the crash?

Opening QGIS and trying to use an existing expression from the python function editor results in an error 'Function is not known'.

After switching to the 'Function Editor' tab and clicking 'Save and Load Functions' (without editing anything) the expression is working.

### Steps to reproduce the issue

save and load a python function and close QGIS (or copy the *.py file to %QGISPROFILE%\python\expressions)
Load any project with a layer
open e.g. field calculator
notice the missing expression 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.9-Firenze | QGIS code revision | 66f4d63ad4
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
create_layer_from_selected_features | 1.2
firstaid | 3.0.3
joinmultiplelines | Version 0.4.1
searchlayers | 3.0.12
splitmultipart | 1.0.0
db_manager | 0.1.20
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I tried QGIS LTR and newest stable built as well a a new profile.
I tried reindenting the file.

**Comment by agiudiceandrea** [comment]
@MalikAlMaut, thanks for reporting. Could you please provide the Python script file containing the expression? Are there any error messages in the "User expressions" tab on Log Messages panel? Does the Python script file contain non ASCII characters?

**Comment by MalikAlMaut** [comment]
The Error message is '_Function is not known_'.
Also the group for the _qgsfunction_ is not created.
What puzzles me most is, that a short testing script (see below) is loading automatically. Also the functions not loading automatically are working without error after being loaded manually.

Unfortunately I cannot provide my large script since it contains many personal data and I wouldn't know where to start purging.
But I have another function not loading: This shortened algorithm from [this project](https://github.com/provinzkraut/cologne_phonetics):

```
from qgis.core import *
import re
import unicodedata

@qgsfunction(args='auto', group='Custom', usesgeometry=False)
def cologne_phonetics(data, concat, feature, parent):

    """
    Cologne_phonetics is a Python implementation of the cologne-phonetics, a phonetic
    algorithm similar to soundex but optimized for the German language.
    Documentation can be found at https://github.com/provinzkraut/cologne_phonetics
    A detailed explanation of the cologne phonetics can be found at:
    https://en.wikipedia.org/wiki/Cologne_phonetics

    :param data: Input to be encoded. Whitespace characters will be interpreted as a wordbreak.
    :param concat: The intended behavior of the cologne-phonetics is to ignore special characters.
                   This leads to concatenation for strings with hyphens. If ``concat`` is set to ``True``,
                   hyphenated string will be treated as separate words.
    :return: Encoded substring(s).
    """


    def remove_diacritics(s):
        return "".join(
            c for c in unicodedata.normalize("NFD", s) if unicodedata.category(c) != "Mn"
        )

    def replace_by_rules(rules, s):
        for rule in rules:
            s = rule[0].sub(rule[1], s)
        return s

    rgx_special_chars = re.compile(r"[äüöß]")

    rgx_special_char_replacements = [
        (re.compile(r"ä"), "ae"),
        (re.compile(r"ö"), "oe"),
        (re.compile(r"ü"), "ue"),
        (re.compile(r"ß"), "s"),
    ]

    rgx_rules = [
        # ignore special characters that have not been replaced at this point
        (re.compile(r"[^a-z]"), ""),
        # d,t replacements
        # not before c,s,z
        (re.compile(r"[dt](?![csz])"), "2"),
        # before c,s,z
        (re.compile(r"[dt](?=[csz])"), "8"),
        # x replacements
        # not after c,k,q
        (re.compile(r"(?<![ckq])x"), "48"),
        # after c,k,q. insert new x for later comparison. will be removed later
        (re.compile(r"(?<=[ckq])x"), "x8"),
        # c replacements
        # at the start before a,h,k,l,o,q,r,u,x
        # | not after s,z before a,h,k,o,q,u,x
        (re.compile(r"^c(?=[ahkloqrux])|(?<![sz])c(?=[ahkoqux])"), "4"),
        # not before a,h,k,o,q,u,x
        # | not before s,z
        # | at the start, not before a,h,k,l,o,q,r,u,x
        (re.compile(r"c(?![ahkoqux])|(?<=[sz])c|^c(?![ahkloqrux])"), "8"),
        # p not before h
        (re.compile(r"p(?!h)|b"), "1"),
        # p before h and f,v,w
        (re.compile(r"p(?=h)|[fvw]"), "3"),
        (re.compile(r"[hx]"), ""),
        (re.compile(r"[aeijouy]"), "0"),
        (re.compile(r"[gkq]"), "4"),
        (re.compile(r"l"), "5"),
        (re.compile(r"[mn]"), "6"),
        (re.compile(r"r"), "7"),
        (re.compile(r"[sz]"), "8"),
        # repeating digits
        (re.compile(r"(\d)(?=\1)"), ""),
        (re.compile(r"\B0"), ""),
    ]

    def encode(data, concat=False):
        if not concat:
            data = data.replace("-", " ")
        data = data.lower()

        words_encoded = []
        for word in data.split(" "):
            word_clean = remove_diacritics(replace_by_rules(rgx_special_char_replacements, word))
            word_encoded = replace_by_rules(rgx_rules, word_clean)
            words_encoded.append((word_clean, word_encoded))
        return words_encoded

    return [r[1] for r in encode(data, concat=concat)]
```

BUT then again my short testing function is loading automatically:

```
from qgis.core import *
from qgis.gui import *

"""
This is for testing
"""
'''
  Testing
'''

@qgsfunction(args='auto', group='TEST', referenced_columns=[])
def TEST(feature, parent, context):
    geometry = feature.geometry()    # TESTING
      #TESTING
    ombb_geom, ombb_area, ombb_angle, ombb_width, ombb_height = geometry.orientedMinimumBoundingBox()
    return ombb_geom
```

I also tried several things in the testing script without breaking it (not that I really know, what I'm doing):
- indentation with tabs or spaces (even mixing them in different function definitions)
- empty lines
- comments with """, ''' and # (well indented and 'crooked')
- function definitions inside and outside of other definitions
- other imports
- using classes
- using @staticmethod

**Comment by agiudiceandrea** [comment]
@MalikAlMaut could you please specify, as already requested, if there are error messages (and what they are) in the "User expressions" tab (or in any other tab) of the "Log Messages" panel?
As you can see, the provided non automatically loading script contains non ASCII characters. Could you please check if in your script there are non ASCII characters?

**Comment by MalikAlMaut** [comment]
Sorry, I completely forgot about the log message panel.
You are right, the special characters are the problem. 

 ```
Traceback (most recent call last):
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\user.py", line 46, in load_user_expressions
  __import__("expressions.{0}".format(name), locals(), globals())
  File "C:\OSGeo4W/apps/qgis-ltr/./python\qgis\utils.py", line 888, in _import
  mod = _builtin_import(name, globals, locals, fromlist, level)
  File "C:\Users/---/AppData/Roaming/QGIS/QGIS3\profiles\---/python\expressions\Soundex Cologne Phonetics.py", line 32
  rgx_special_chars = re.compile(r"[����]")
  ^
 SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xe4 in position 1: invalid continuation byte
```
In my script the error message is slightly different: (but here I can prevent this now, because this only occurs in a string return)

```
[...]
^
SyntaxError: (unicode error) 'utf-8' codec can't decode byte 0xfc in position 17: invalid start byte
```

**Comment by agiudiceandrea** [comment]
The issue has been already reported (https://github.com/qgis/QGIS/issues/53897) and fixed (https://github.com/qgis/QGIS/pull/53903). The issue is due the the fact that the "Function editor" incorrectly writes the user expression Python script using the system codec instead of the UTF-8 codec. The "Function editor" will correctly use the UTF-8 codec to write the user expression Python script starting from QGIS versions 3.32.2, 3.28.11, 3.34.0.
