### ISSUE TITLE
Background of texts contains wrong colors in exported SLD-style

### ISSUE THREAD

**Issue by hebersgit** [qgis/QGIS#53964]
### What is the bug or the crash?

If a labelling is defined for a layer, type _single Labels_ in easiest case, and a background is defined for this labelling, and the style is exported as SLD-style, the background is exported as a node _Graphics/Mark_ within the _TextSymbolizer_. 
While the "_shape_"-setting is exported correctly within attribute _WellKnownName_, the color of this background is _always_ exported as _fill=#ffffff_ and the stroke (with doesn't exist for this feature) is exported as _stroke=#808080_. The real color-setting is ignored.

### Steps to reproduce the issue

- load a point-layer into QGIS
- open _properties_, goto tab _Labels_
- switch to option _Single Labels_
- below in the dialog, open tab _Background_
- check _Draw Background_ and switch the color to yellow e.g.
- export it as SLD-style (via _Style->Save Style..._ at the bottom of this dialog)
- the exported SLD-style-file contains this wrong part:

```
<se:Rule>
   <se:TextSymbolizer>
     [...]
     <se:Graphic>
       <se:Mark>
         <se:WellKnownName>square</se:WellKnownName>
         <se:Fill>
           <se:SvgParameter name="fill">#ffffff</se:SvgParameter>
         </se:Fill>
         <se:Stroke>
           <se:SvgParameter name="stroke">#808080</se:SvgParameter>
           <se:SvgParameter name="stroke-width">0.5</se:SvgParameter>
         </se:Stroke>
       </se:Mark>
       [...]
     </se:Graphic>
   </se:TextSymbolizer>
</se:Rule>     
```

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
excel_sync
3.6
infas_lt_geocoder
1.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.1
qgis2web
3.16.0
topojson_writer
0.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@hebersgit , thanks for reporting this, it has been fixed, expect it in 3.34.0 (or 3.34.1).
