### ISSUE TITLE
Qgis - Cursor is sluggish in editing mode and over MapView

### ISSUE THREAD

**Issue by PierreB35** [qgis/QGIS#53966]
### What is the bug or the crash?

Hello !

I have a weird problem with QGIS : the cursor becomes very sluggish in editing mode. It only happens when hovering over the Map View (so when I want to create, modify or move an entity : point, line…).

- If I quit editing mode, everything is normal.
- If I stay in editing mode but move the cursor over a panel, the menu bar or the toolbars, everything immediately gets back to normal.
- If I stay in editing mode and move the cursor over the MapView, but in Select Feature mode for example (not trying to create or modify a feature), everything is normal again.

It happens with shapefile, geopackage… I run Fedora 38, everything up to date. I tried different release of Qgis (including 3.22 and 3.28), remove all plugins and created new profiles : it does not solve the problem. I reinstalled Fedora, then QGis, wiping out every data on my ssd, nothing changed.  My set-up seems ok : AMD Ryzen 5 3600 × 12, 16 Go RAM, AMD Radeon RX 5600 XT. Everything else works like a charm on this computer, including more demanding softwares.

Finally, I don’t have this issue on a Fedora 38 laptop, nor on a Windows 10 tablet.
I need QGis to work, thanks a lot to anyone who can help !

### Steps to reproduce the issue

![ok](https://github.com/qgis/QGIS/assets/140704179/0891db52-293f-4c71-b5cc-923d0e684ac6)
Works fine

![not ok](https://github.com/qgis/QGIS/assets/140704179/a25c0cf1-0f36-42e1-8988-bc0c4020eb2a)
Horribly sluggish

### Versions

![version](https://github.com/qgis/QGIS/assets/140704179/1beeb0fc-685f-461e-bbe3-c140dd192adc)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Thank you !

**Comment by PierreB35** [comment]
I forgot the debug :
![debug1](https://github.com/qgis/QGIS/assets/140704179/4a735a72-21af-4af0-a7f6-ae7b6e305252)
![debug2](https://github.com/qgis/QGIS/assets/140704179/9e41acf3-1be2-42c2-bc60-e8c85b4325f1)

**Comment by alexbruy** [comment]
Are you using wayland? Does this happen with all projects or only with specific one? Do you use snapping? Please provide more information that can help reproduce the issue, including test dataset. Unfortunately with information you provided it is not possible to guess what can be wrong.

**Comment by Detritalgeo** [comment]
Have this issue also.

3.44.x LTR
Ubuntu LTS 24.04.4
Wayland session
