### ISSUE TITLE
Building virtual point cloud on QGIS 3.32.1 standalone install for Windows fails with pg_wrench.exe fail to start

### ISSUE THREAD

**Issue by newcomb-d** [qgis/QGIS#53970]
### What is the bug or the crash?

Building a VPC on QGIS 3.32.1 Standalone install for Windows fails on 1186 tile LAZ group   

QGIS version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.1
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.2.1, June 1st, 2023
PDAL version: 2.5.5 (git-version: a7569c)
Algorithm started at: 2023-07-27T08:36:47
Algorithm 'Build virtual point cloud (VPC)' starting…

Process C:/PROGRA~1/QGIS33~1.1/apps/qgis/./pdal_wrench.exe failed to start. Either C:/PROGRA~1/QGIS33~1.1/apps/qgis/./pdal_wrench.exe is missing, or you may have insufficient permissions to run the program.
Execution failed after 853.85 seconds (14 minutes 14 seconds)

The command works with up to 305 LAZ 1.4  tiles , so it does not sound like it is a permission issue for pdal_wrench.exe  and more a limitation on the number of tiles that can be handled at one time. 

Perhaps is is the length of file names and the number of characters windows can handle? I have run into those issues before when passing lists of files to a command on windows. The file names I'm using ( as downloaded from USGS) are 58 characters long.

### Steps to reproduce the issue

1. Go to Processing Toolbox
2. Double click on  Build Virtual Point Cloud
3. Click on 3 dot box next to input layers 
4. Click on Add Files
5. Select 500 .LAZ files
6. Click Run

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf63
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
Cadastral_Divisions-main | 1.2
DataPlotly | 4.0.3
dissect_dissolve_overlaps | 0.3
geocatbridge | 4.4
geometric_attributes | 0.4
go2streetview | 8.6
KP_find | 3.1.0
latlontools | 3.6.12
mmqgis | 2021.9.10
panorama_viewer | 1.0
pointsamplingtool | 0.5.4
processing_fusion | 3.5
processing_r | 3.1.1
qgis-project-as-utm | 1.1
qgis_stac | 1.1.1
quick_map_services | 0.19.33
RasterAttributeTable | 1.2
segment_reshape_plugin | 0.1.4
shapetools | 3.4.14
slyr | 6.4.3
stripchart | 0.66
Submission | 0.7
grassprovider | 2.12.99
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf63](https://github.com/qgis/QGIS/commit/4a078ecf63)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Cadastral_Divisions-main
1.2
DataPlotly
4.0.3
dissect_dissolve_overlaps
0.3
geocatbridge
4.4
geometric_attributes
0.4
go2streetview
8.6
KP_find
3.1.0
latlontools
3.6.12
mmqgis
2021.9.10
panorama_viewer
1.0
pointsamplingtool
0.5.4
processing_fusion
3.5
processing_r
3.1.1
qgis-project-as-utm
1.1
qgis_stac
1.1.1
quick_map_services
0.19.33
RasterAttributeTable
1.2
segment_reshape_plugin
0.1.4
shapetools
3.4.14
slyr
6.4.3
stripchart
0.66
Submission
0.7
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The function fails with 1186 tiles, and 506 tiles, but succeeds with 305 tiles with names 58 characters long. I will try renaming the .laz files to shorter names and running again just to check to see if it is a number of characters issue.

**Comment by newcomb-d** [comment]
After taking the name length of the laz files down from 58 to 20 characters, I was able to create a 506 tile virtual file, so it seems that there is a filename list limit for input

**Comment by saberraz** [comment]
I think this is an upstream bug with pdal

**Comment by newcomb-d** [comment]
There may be a need for a similar option to gdalbuildvrt,  https://gdal.org/programs/gdalbuildvrt.html , -input_file_list <mylist.txt>

**Comment by wonder-sk** [comment]
> There may be a need for a similar option to gdalbuildvrt, https://gdal.org/programs/gdalbuildvrt.html , -input_file_list <mylist.txt>

This has been added recently to pdal_wrench, but it is not released yet: https://github.com/PDAL/wrench/pull/15

**Comment by agiudiceandrea** [comment]
It looks like either the issue still occurs or it occurs again using QGIS 3.34.11: see https://github.com/qgis/QGIS/issues/58894.
