### ISSUE TITLE
HERRAMIENTA DE VERTICES

### ISSUE THREAD

**Issue by CLAUIODAV** [qgis/QGIS#53989]
### What is the bug or the crash?

Al intentar eliminar puntos de vertice de manera masiva, con la herramienta de vertices, se produce un error
![image](https://github.com/qgis/QGIS/assets/140844276/ac4c2825-58c0-4aca-a35c-d316d8ea4a8f)

### Steps to reproduce the issue

4

### Versions

3.16.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @CLAUIODAV, thanks for reporting. QGIS 3.16 is no longer supported. Please try if the issue does occur using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule). Please provide the full stack trace text.
