### ISSUE TITLE
Glitch in print layout scale bar properties dialog

### ISSUE THREAD

**Issue by joto** [qgis/QGIS#53990]
### What is the bug or the crash?

The dialog showing the scalebar properties in print layout has two options "Fixed width" and "Fit segment width", each switch off and on certain parameters to the right of those options. But when the dialog is first opened all parameters are changeable.

### Steps to reproduce the issue

1. Open a new print layout
2. Add scalebar
3. Go to item properties of that scale bar
4. Try switching the "Fixed width" and "Fit segment width"

### Versions

QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.8
Python version
3.11.2
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.3 (Debian 15.3-0+deb12u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Debian GNU/Linux 12 (bookworm)

Active Python plugins
QuickOSM
2.2.2
quick_map_services
0.19.33
mapswipetool_plugin
1.2
latlontools
3.6.11
nominatim_locator_filter
0.2.4
Qgis2threejs
2.7.1
QuickWKT
3.1
cartography_tools
1.2.1
mercator-grid
1.0
lockzoom
3.0.3
MetaSearch
0.3.6
processing
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The issue does also occur using QGIS 3.28. The issue didn't occur using QGIS 3.22.
