### ISSUE TITLE
Project gets corrupted when PG can't be reached 

### ISSUE THREAD

**Issue by bloigge** [qgis/QGIS#54004]
## User Feedback

Project was opened before but connection to Postgres was not possible as I forgot to start my local PG Docker Container. QGIS Project wasn't saved and QGIS was closed. After starting Docker PG Container and restarting QGIS this error now shows up. The Project wasn't saved. Only solution was to re-create the whole project

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00007e28 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\selectors.py", line 315 in _select
    r, w, x = select.select(r, w, w, timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\selectors.py", line 324 in select
    r, w, _ = self._select(self._readers, self._writers, [], timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\socketserver.py", line 232 in serve_forever
    ready = selector.select(poll_interval)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 892 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 954 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 912 in _bootstrap
    self._bootstrap_inner()

Current thread 0x00005bfc (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Create a project with a layer where the source is PG 
2. Close the project
3. Stop PG
4. Reopen 
5. Do not save anything and close QGIS Project

### Versions

3.32.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can't reproduce using provided steps. When I open project with stopped PostgreSQL server I first asked for server credentials, then a missed layers dialog appears showing all postgis layers as unavailable and providing options to keep, remove or fix missed layers. If option to keep unavailable layer is selected and then project is closed without saving, next time project is open all layers are there.
