### ISSUE TITLE
QGIS crashes opening a project with unavailable GPX layer

### ISSUE THREAD

**Issue by martinr36** [qgis/QGIS#54021]
### What is the bug or the crash?

I was attemting to open a project that contained links to gpx files which were located on another machine, I was going to change the data source so told QGIS to keep the layers

This is the bug report that QGIS produced

## User Feedback

Trying to open a project that contains some gpx files that were on another machine

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00005cd4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

providerMetadataFactory :
providerMetadataFactory :
providerMetadataFactory :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayerFeatureSource::getFeatures :
QgsMapHitTest::runHitTestFeatureSource :
QgsMapHitTestTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

1. clicked on project to open it (project had previously been saved on another machine)
2. table came up telling me the data for 4 layers couldn't be found
3. clicked on keep the layers
4. QGIS crashed

![image](https://github.com/qgis/QGIS/assets/107694493/411f3920-43fe-46a5-9a0e-1b1d39ecd368)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf63
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf63](https://github.com/qgis/QGIS/commit/4a078ecf63)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@martinr36 thanks for reporting. It would be helpful if you provide the affected project.

**Comment by martinr36** [comment]
***@***.*** has shared a OneDrive file with you. To view it, click the link below.




Hudson Meadows.qgz <https://d.docs.live.net/015a54c5579d5e41/Drone%20stuff/QGIS%20Projects/Hudson%20Meadows.qgz> 


Hi Andrea

 

Please find project attached, any problems or should you need further info, just ask

 

Regards

Martin

**Comment by agiudiceandrea** [comment]
@martinr36, it is not possible to send any file to GitHub vie e-mail. Please attach the zipped project file directly to this issue report on the GitHub web interface.

**Comment by martinr36** [comment]
Andrea I tried to add it and it says it is to big at 34 MB

**Comment by martinr36** [comment]
If its of any use here's a link to the zipped file on my onedrive
https://1drv.ms/u/s!AkFenVfFVFoBifEhhCy1xrX_nysh1A?e=ynbK4I

**Comment by agiudiceandrea** [comment]
It seems to me the issue doesn't occur using QGIS 3.28.

**Comment by martinr36** [comment]
Hi Andrea
Just downloaded 3.28, and can confirm it doesn't crash

**Comment by agiudiceandrea** [comment]
The attached [test_project_1.zip](https://github.com/qgis/QGIS/files/12241240/test_project_1.zip) file is a sample minimal zipped file project with only 1 unavailable test_layer.gpx layer file (Provider: gpx - Storage: GPS eXchange file - added via Data Source Manager -> GPS -> GPX dataset) that makes QGIS crash.

The attached [test_project_2.zip](https://github.com/qgis/QGIS/files/12241263/test_project_2.zip) file is a sample minimal zipped file project with only 1 unavailable test_layer.gpx layer file (Provider: ogr - added via Data Source Manager -> Vector -> Vector dataset) that doesn't make QGIS crash.

@martinr36, could you please change the issue report title to a more meaningful one (something like "QGIS crashes opening a project with unavailable GPX layer")?

**Comment by martinr36** [comment]
Andrea, title changed
