### ISSUE TITLE
Centroid fill symbology does not highlight selected polygon features

### ISSUE THREAD

**Issue by Ludoohh** [qgis/QGIS#54037]
### What is the bug or the crash?

When using the Single Symbol -- Fill -- Centroid fill symbology, selected features are not highlighted.

### Steps to reproduce the issue

1. Select a polygon vector layer
2. In Symbology, select Single Symbol -- Fill -- Centroid fill (for instance so as to make a circle for each feature (instead of its outline)
3. Select features
4. The features do not get highlighted as they should (default bright yellow)

### Versions

3.32.0 Lima

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@Ludoohh , fixed, thanks for reporting.
