### ISSUE TITLE
PostgreSQL: nextval(NULL) in unique field

### ISSUE THREAD

**Issue by CBRBO** [qgis/QGIS#54058]
### What is the bug or the crash?

QGIS shows "nextval(NULL)" when a new item is inserted. Nothing is shown  (that's right way) if the constraint is deleted from the database
![1](https://github.com/qgis/QGIS/assets/108810932/965daefa-232b-46ab-bdb3-9c5350aca8f6)
![2](https://github.com/qgis/QGIS/assets/108810932/353f25ad-faeb-42e8-a316-9ade4be21192)
![3](https://github.com/qgis/QGIS/assets/108810932/0d7156c6-0feb-4954-aec1-5ccd7f0765e2)
![4](https://github.com/qgis/QGIS/assets/108810932/63916add-c6d7-4d89-8ecc-2670515eefcd)
![5](https://github.com/qgis/QGIS/assets/108810932/ef3a0cb9-a6a2-4a90-a98e-cd28556ab709)
![6](https://github.com/qgis/QGIS/assets/108810932/6fb0d30d-64a8-4aea-bd09-b3a3d0b8ff2c)

### Steps to reproduce the issue

Insert a new item with a unique constraint filed

### Versions

3.28-9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
That's probably the given default value for the field in the database, so that should be fixed in the database.

**Comment by CBRBO** [comment]
No default value is defined for that field

![image](https://github.com/qgis/QGIS/assets/108810932/9d4145d5-0f55-46e1-a517-12499da39976)

**Comment by samueldurante** [comment]
Hi, I run into the exact same problem with PostGIS layers.
I got the issue also on PRIMARY KEYS when there is **no default value and text data type** :

![image](https://github.com/qgis/QGIS/assets/54809024/1178cb5a-8072-4736-a491-0e4b34cfbe94)
![image](https://github.com/qgis/QGIS/assets/54809024/64a6e1f2-ea40-4894-8c2e-555880f47e5d)

When I type an already existing value for that field, the error "unique" is popping. So I think it is more likely to be related with NOT NULL constraint without Default value in database and not with "unique" constraint.
![image](https://github.com/qgis/QGIS/assets/54809024/3e2e6f42-0863-4fc1-95cc-be9d825dd033)

If I type "NULL", the error is shown :
![image](https://github.com/qgis/QGIS/assets/54809024/16823883-2393-4342-afe3-498ad3b34447)

But on new feature QGIS set a not null default value which is "nextval(NULL)". PostGIS then throw the NOT NULL error and feature isn't added.
I tried to set "NULL" default value in form settings but still show "nextval(NULL)" and no error is shown, event if the NOT NULL constraint is enforced.

Thanks for helping, this is a very frustrating bug !!

best regards.

**Comment by jef-n** [comment]
```sql
test=> create table foo(i integer unique);
CREATE TABLE
Time: 893,957 ms
test=> \d foo
                 Table "public.foo"
 Column |  Type   | Collation | Nullable | Default
--------+---------+-----------+----------+---------
 i      | integer |           |          |
Indexes:
    "foo_i_key" UNIQUE CONSTRAINT, btree (i)

test=> select pg_get_serial_sequence('foo','i');
 pg_get_serial_sequence
------------------------
 (NULL)
(1 row)

Time: 1,808 ms
```

```diff
diff --git a/src/providers/postgres/qgspostgresprovider.cpp b/src/providers/postgres/qgspostgresprovider.cpp
index 3aca8318828..abba60ae790 100644
--- a/src/providers/postgres/qgspostgresprovider.cpp
+++ b/src/providers/postgres/qgspostgresprovider.cpp
@@ -1390,7 +1390,7 @@ bool QgsPostgresProvider::loadFields()
                              .arg( quotedValue( mQuery ) )
                              .arg( quotedValue( fieldName ) );
       QgsPostgresResult seqResult( connectionRO()->PQexec( seqSql ) );
-      if ( seqResult.PQntuples() == 1 )
+      if ( seqResult.PQntuples() == 1 && !seqResult.PQgetisnull( 0, 0 )  )
       {
         defValMap[tableoid][attnum] = QStringLiteral( "nextval(%1)" ).arg( quotedValue( seqResult.PQgetvalue( 0, 0 ) ) );
       }
```
