### ISSUE TITLE
Placing comments in qgis filters causes features to disappear from canvas. 

### ISSUE THREAD

**Issue by DurstDog87** [qgis/QGIS#54068]
### What is the bug or the crash?

When using SQL filters on vector feature data, placing a comment anywhere in the filter `--` causes all features to disappear from the canvas.

### Steps to reproduce the issue

Steps:
- open a new qgis project
- add any vector feature layer to the map canvas.
- right click on the layer and select 'filter'
- add filter to the sql editor. Adding a comment here causes features on canvas to completely disappear. 

Example
Filtering works as expected.
```sql
datafield1 = 'foo' AND datafield2 = 'bar'
```
Adding a comment causes features to dissappear from canvas.
```sql
datafield1 = 'foo' --AND datafield2 = 'bar'
```

### Versions

QGIS version | 3.28.3-Firenze | QGIS code revision | 9ae208a46d

Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.5

Active Python plugins
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

3.28.3-Firenze
QGIS code revision
[9ae208a46d](https://github.com/qgis/QGIS/commit/9ae208a46d)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.5

Active Python plugins
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (ae45e662c6a6f6ad61b3297a3f34efde8a63eec0)
