### ISSUE TITLE
Protected WFS Layer does not show in QGIS

### ISSUE THREAD

**Issue by doublebyte1** [qgis/QGIS#54064]
### What is the bug or the crash?

After creating an authenticated WFS connection, QGIS does not list the protected layers.  Only the unprotected ones.

Maybe QGIS is attempting to read GetCapabilities without authenticating first, and when it succeeds to do so, it does not trigger the authentication. The result is that protected layers are not listed on the unprotected GetCapablities and therefore, not accessible in QGIS.

This could be a regression bug, as everything was working before, on 3.26>Buenos Aires.

### Steps to reproduce the issue

1. Create an authenticated WFS connection on the "Add layer menu" or "browser panel". Store the credentials as configuration.
2. Connect to the server and list the layers. The protected layers won't show up. Only unprotected ones.

### Versions

I'm on 3.33.0-Master on this code revision: https://github.com/qgis/QGIS/commit/031179e9a9

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

If necessary, I can facilitate a server with protected and unprotected layers for testing.

**Comment by nirvn** [comment]
@doublebyte1 , can you provide a sample project to facilitate debugging of this regression? Thanks.
