### ISSUE TITLE
QGIS Crashes Upon Exporting Layout to PDF when Using Random Point Fill Symbology

### ISSUE THREAD

**Issue by HughKelley** [qgis/QGIS#54065]
### What is the bug or the crash?

I've built a basic layout with a single map and no other elements. 

It has census block polygons for the state of Wisconsin, symbolized with the random point fill option. I've tried both 10 points per polygon and 1, as well as my original goal which was expression based.

### Steps to reproduce the issue

add a layer >> symbolize as random point fill >> create a layout >> export to pdf. 

I think I've seen in some cases, if the layout extent is smaller, the crash does not happen. I am not certain about this. 

Exporting to png does not crash QGIS so far. 

I've tried this on both 3.28.9 and 3.32.1 with the same result.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.28.9-Firenze | QGIS code revision | 66f4d63ad4
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.9-Firenze
QGIS code revision
[66f4d63ad4](https://github.com/qgis/QGIS/commit/66f4d63ad4)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

data source here https://www.dropbox.com/s/9wyuyrsz9zyvvjp/20230803_data.gpkg?dl=0

qgis file here: https://www.dropbox.com/s/4ydy6vgrnt9cb9q/20230804_demo_rebuild.qgz?dl=0

**Comment by troopa81** [comment]
Could you share a project sample and data and the exact step to reproduce the crash?

**Comment by nirvn** [comment]
Crash confirmed, occurs in the poly2tri library which gets stuck in an infinite loop here:

```
    (this=0x55555c746990, tcx=..., ep=..., eq=..., t=0x55555ade3a50, p=...) at /home/webmaster/dev/cpp/QGIS/external/poly2tri/sweep/sweep.cc:739
# 0x00007ffff1858b74 in p2t::Sweep::FlipScanEdgeEvent(p2t::SweepContext&, p2t::Point&, p2t::Point&, p2t::Triangle&, p2t::Triangle&, p2t::Point&)
    (this=0x55555c746990, tcx=..., ep=..., eq=..., flip_triangle=..., t=..., p=...) at /home/webmaster/dev/cpp/QGIS/external/poly2tri/sweep/sweep.cc:801
# 0x00007ffff18587e0 in p2t::Sweep::FlipEdgeEvent(p2t::SweepContext&, p2t::Point&, p2t::Point&, p2t::Triangle*, p2t::Point&)
```
