### ISSUE TITLE
Merging linestrings can confuse vertex tool

### ISSUE THREAD

**Issue by thbaumann** [qgis/QGIS#54084]
### What is the bug or the crash?

When you merge certain linestrings the vertex-tool shows the vertex-marker afterwards on the wrong line feature and you can not move vertices of affected features.

The following screencasts show how to replicate the error. Test-Shapefile is attached.

https://github.com/qgis/QGIS/assets/20082727/e228f823-162d-413d-b556-99c505fd27db

[testdata_vertextool.zip](https://github.com/qgis/QGIS/files/12267071/testdata_vertextool.zip)

https://github.com/qgis/QGIS/assets/20082727/787c1433-82e0-4e89-845d-668cc7f99bea

I know that linestrings should not have self-intersections but some users still produce them and I think it would be good if the vertex tool would not get confused by it.

### Steps to reproduce the issue

1. Move the vertex of one linestring to the outer vertex of another linestring 
(in my test it were linestrings with opposite digitizing direction and the moving of the vertices to get a connected linestring resulted in a self intersection when features were merged)
2. Merge the two linestrings
3. Try to hover with activated vertex tool over the linestrings
--> you will see that the vertex tool gets confused 

### Versions

3.28.9 and 3.32.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (ae45e662c6a6f6ad61b3297a3f34efde8a63eec0)
