### ISSUE TITLE
Right-to-Left languages characters in each label words are reversed

### ISSUE THREAD

**Issue by hareldunn** [qgis/QGIS#54098]
### What is the bug or the crash?

This is a recurrence of a bug similar fixed long ago for all rtl languages like Hebrew, Persian and Arabic. It was solved, at times, with using the [curved label](https://github.com/qgis/QGIS/issues/21940) option, but not any more.

Each word, although in correct word order, has it's letters reversed, akin to:
Hello World -> olleH dlroW 

Here's the bad labelling in 3.32, note for example the word for chapel קפלה is displayed in reverse הלפק
![image](https://github.com/qgis/QGIS/assets/24369355/4ab4a9da-6f8f-4c26-933c-529748032d70)

Here's the correct text handling in 3.28.9 LTR
![image](https://github.com/qgis/QGIS/assets/24369355/986dfc67-bc33-4646-bae6-6da8d75f86b6)

### Steps to reproduce the issue

Add any layer with RTL language in attribute table
Display label based on field

Or open QGZ from GPGK here
[qgisbug.zip](https://github.com/qgis/QGIS/files/12269243/qgisbug.zip)

I've added English, Arabic and Hebrew labels from the OSM amenity data

### Versions

3.32.1
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf](https://github.com/qgis/QGIS/commit/4a078ecf)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It appears the change happened between 3.30 and 3.32, a colleague had his computer replaced and installed a new QGIS version 3.32 standalone that showed this issue. I guided him with installing the network installer for 3.32 and had the same issue. I tested his project and layers on my computer, and it too showed the bug in 3.32, but not in 3.28 LTR. He claims his project worked fine in his old computer running 3.30, so this pinpoints the bug to 3.30 -> 3.32

**Comment by agiudiceandrea** [comment]
Hi @hareldunn, thanks for reporting. Could you please specify the difference between the issue you reported and the one reported at https://github.com/qgis/QGIS/issues/21940? In the https://github.com/qgis/QGIS/issues/21940 issue report, users claim that the issue occurs also in QGIS 3.28 and QGIS 3.30 and previous version.
Could you please clarify what do you mean with "Each word, although in correct word order, has it's letters reversed" as it seems to me in the provided images the entire label is reversed, not only the letters of the single words.

**Comment by hareldunn** [comment]
Hi @agiudiceandrea, you are correct, I somehow managed to confuse myself.
Yes, the flip is indeed for the entire label string, "Hello World" -> "dlroW olleH"

As for recent QGIS version, I didn't have that issue, nor did my colleague, only in 3.32.

I also found another mention of this on [GIS.SE](https://gis.stackexchange.com/questions/465205/left-to-right-flipped-names-in-arabic), seems to be the same issue

**Comment by agiudiceandrea** [comment]
Hi @hareldunn, thanks for checking. I cannot replicate the issue neither using QGIS 3.28, QGIS 3.30 nor QGIS 3.33-master: it seems to me the labels are correctly displayed.
See the exported images of point with full_id field value of n2954804553:

QGIS 3.28
![3_28](https://github.com/qgis/QGIS/assets/16253859/283a0f55-f80c-40fe-a3e6-c3ebe9236684)

QGIS 3.30
![3_30](https://github.com/qgis/QGIS/assets/16253859/2f16c438-ec20-4756-9e54-641df38c8262)

QGIS 3.33-master
![master](https://github.com/qgis/QGIS/assets/16253859/e2bf67c2-0096-449d-92be-5d1c4ff80dc0)

**Comment by micha-silver** [comment]
I can confirm this issue on Windows, QGIS 3.32.3.
We reverted to 3.28.11 and the backwards RTL text problem does **not** appear
(Also, the problem does not appear on Linux, with the same QGIS version)

**Comment by agiudiceandrea** [comment]
@micha-silver , thanks for reporting. Could you please provide a simple project and a simple layer with only one feature in order to replicate the issue?

**Comment by drarbib** [comment]
Hi I have the same issue, working on windows 10. and it's been persistent since above gis 3.30.0, including the recent 3.34. It's not only that the letter order is reversed it's also outside the label box 

Here's a screenshot using 3.34:
![image](https://github.com/qgis/QGIS/assets/150327591/1c769b9e-7558-436e-9771-e8500d153cef)


But when I revert to 3.30.0, it displays correct:
![image](https://github.com/qgis/QGIS/assets/150327591/5fdcda5a-8d2f-43f9-a7b8-f8426df048d6)

As you can see numbers are displayed correctly

**Comment by agiudiceandrea** [comment]
@drarbib, thanks for reporting. Could you please provide a simple project and a simple layer with only one or few features in order to replicate the issue? Could you please specify the OS locale / language and the locale / language set in QGIS?

**Comment by drarbib** [comment]
[RTL problem.zip](https://github.com/qgis/QGIS/files/13307355/RTL.problem.zip)

Hi, here's a simple file, created in 3.30.0, opened in 3.34 the problem is consistent. in fact even if i edit ans save it in 3.34 and open it in 3.30.0 it displays correct, but not in 3.34.

windows:
Edition	Windows 10 Pro
Version	20H2
Installed on	‎27/‎04/‎2021
OS build	19042.985
Serial number	PF21WWN7
Experience	Windows Feature Experience Pack 120.2212.2020.0

Locale:
QGIS settings:
![image](https://github.com/qgis/QGIS/assets/150327591/b16c87b4-06d2-4662-8167-39cb52010fff)
windows settings:
![image](https://github.com/qgis/QGIS/assets/150327591/6dec91bf-501f-4d62-8038-75805183b40e)
![image](https://github.com/qgis/QGIS/assets/150327591/c5d743e3-df85-45c9-97d7-148c7dd21599)

**Comment by agiudiceandrea** [comment]
It seems to me the issue doesn't occur on my system Windows 10 Italian it_IT using QGIS 3.34.0

![image](https://github.com/qgis/QGIS/assets/16253859/43f81707-88b3-4714-99b7-797945302f51)

**Comment by drarbib** [comment]
grazie mille Andrea, First off thank you for your time and effort. I just DLed and installed 3.34.1 and the issue persists (yet in 3.30 it works fine). 
![image](https://github.com/qgis/QGIS/assets/150327591/27c24789-500a-4b7e-b1db-4a63b15a166f)


I do not know how I can help to resolve it. I am completely incompetent in programming. My common sense teIls me that somehow RTL support is created by an extra command that reverses the letter order, and maybe in my version of windows with Hebrew support it somehow does it double, whereas with your Italian one it does not. again what's weird to me is until 3.30 it never was a problem, so I wonder what was changed in the code. If there is anything I can do (like provide more system info)  to help, please let me know 
  
![image](https://github.com/qgis/QGIS/assets/150327591/361d866f-e70c-4a95-b064-6bb8c09f43be)

**Comment by agiudiceandrea** [comment]
@drarbib, have you tried if the issue occurs also using a new QGIS user profile?

**Comment by micha-silver** [comment]
Hi @agiudiceandrea 
My (unchecked) idea is that the prob is a combination of Windows 11 and QGIS >= 3.30.
I could not see the problem in a Win 10 machine. And the issue does not appear on either version of Windows when QGIS <= 3.28.  I have to ask some colleagues who have Win 11 to retest. I'll report back...

**Comment by ryangentry** [comment]
I'd like to add any info that could be relevant, as I am also experiencing this bug. It did not exist sometime before 3.30. I am using 3.34 on Windows 11 and the problem still exists. On the photo below, look at Tel Aviv, look at Ramat HaSharon. The Hebrew and Arabic translations say "NorshHa Tamar". The alignment here is set to "Center" but I can't get it to align the lines over one another like it worked in previous versions. I can add any other necessary info
![Screenshot 2024-01-02 154001](https://github.com/qgis/QGIS/assets/46385139/617ee409-ee9c-42ea-b586-6fd4591c57a7)

**Comment by agiudiceandrea** [comment]
@micha-silver , from the previous comments and from https://gis.stackexchange.com/questions/465205/left-to-right-flipped-names-in-arabic, it looks like the issue occurs on some systems both when using Windows 10 and Windows 11 with QGIS >= 3.32, and it didn't occur with QGIS 3.30.0 and previous versions.

**Comment by nyalldawson** [comment]
Is anyone able to supply a super simple, easy to understand demo project and data showing this issue? Simple enough so that the issue is clearly evident for someone with absolutely zero experience in right to left languages. Ideally with a mock-up of what the label should look like too.

I've tried to investigate this, but just lack understanding of exactly what's required here.

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, a simple project is in comment https://github.com/qgis/QGIS/issues/54098#issuecomment-1803655676 with right and wrong displayed map.
Anyway I cannot replicate the issue.

**Comment by nyalldawson** [comment]
How does QGIS even know when to use RTL text layout though? Is that dependent on the QGIS language setting? Or the system locale? Or the font used?  Or the unicode characters in use? 

I'm utterly clueless here, I need absolute "for dummies" / 5-year-old-kid-level instructions on how this should be handled so that I can update the QGIS internal text placement logic accordingly.

**Comment by ShieldsUpRedAlert** [comment]
I have the same issue in print layouts too (including labels, attribute tables and legend items):

QGIS LTR 3.28 (displays correctly):
![image](https://github.com/qgis/QGIS/assets/81363423/5994c34b-615e-4ee6-b21d-6ca04aa1ba88)

QGIS 3.36:
![image](https://github.com/qgis/QGIS/assets/81363423/4c44952a-b055-4d09-b6f0-12f4f6475422)

I'm on Windows 11, V23H2. Locale EN_GB. The source data files are UTF-8.

**Comment by nyalldawson** [comment]
@ShieldsUpRedAlert see https://github.com/qgis/QGIS/issues/54098#issuecomment-1953305511

**Comment by ShieldsUpRedAlert** [comment]
@nyalldawson I don't know how QGIS handles RTL text internally, but as a user, Unicode RTL text (used to) appear RTL. You just  align it to the right in the horizontal alignment (left/centre/right/justify) settings.

**Comment by ilyessmap** [comment]
1. Open Automated placement engine
2. Text rendering: select label as text


https://gis.stackexchange.com/a/477655/239933

**Comment by agiudiceandrea** [comment]
@ilyessmap, thanks for sharing a workaround. It will likely also help to fix the issue.
@hareldunn @micha-silver @drarbib @ryangentry @ShieldsUpRedAlert may you please confirm the workaround works for you too?

**Comment by ShieldsUpRedAlert** [comment]
@agiudiceandrea, working for me in the main map window. In print layouts, the text is still mirrored on screen, but when I export as PDF everything looks fine.

**Comment by drarbib** [comment]
First off thank you @ilyessmap and thank you @agiudiceandrea,

like @ShieldsUpRedAlert the workaround works for me in the main window but not in the layouts 

![image](https://github.com/qgis/QGIS/assets/150327591/98291316-f2f3-4d00-9606-e42b4af91cda)
![image](https://github.com/qgis/QGIS/assets/150327591/37cd821a-738a-455a-bb8c-c1757f2b520c)

**Comment by agiudiceandrea** [comment]
@nyalldawson, here https://github.com/qgis/QGIS/issues/56645 another issue report with a sample layer attached.
According to various reporters, the issue occurs if the "Text rendering" parameter (in the "Automated Placement Engine" dialog window) is set to "Always Render Labels as Paths (Recommended)".
If such parameter is set to "Always Render Labels as Text", then the label text is:
- correctly displayed on the map canvas
- not correctly displayed in the print layout
- correctly displayed in the PDF file exported from the print layout

**Comment by nyalldawson** [comment]
@agiudiceandrea I still can't do anything with these reports yet, they all assume too much existing knowledge of how RTL languages work

**Comment by ryangentry** [comment]
> @nyalldawson, here #56645 another issue report with a sample layer attached. According to various reporters, the issue occurs if the "Text rendering" parameter (in the "Automated Placement Engine" dialog window) is set to "Always Render Labels as Paths (Recommended)" (which is the default). If such parameter is set to "Always Render Labels as Text", then the label text is:
> 
> * correctly displayed on the map canvas
> * not correctly displayed in the print layout
> * correctly displayed in the PDF file exported from the print layout

This workaround works fine for the text, but text buffers are still displayed incorrectly. See:

![image](https://github.com/qgis/QGIS/assets/46385139/0ffb1bbc-986b-40da-b034-8486be8ac8e4)

**Comment by agiudiceandrea** [comment]
See also: https://github.com/qgis/QGIS/issues/57123.

**Comment by nyalldawson** [comment]
@agiudiceandrea can we readd the feedback label here? I still can't do anything with the information present in this report.

**Comment by bogind** [comment]
Has been handled in any way?
Because using 3.34.6 on windows 11 I'm getting correct RTL rendering, with multiple fonts.


Adding my system info for comparison:


QGIS version | 3.34.6-Prizren | QGIS code revision | 623828f5
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.5
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

**Comment by agiudiceandrea** [comment]
@bogindm thanks for reporting. Have you experienced the issue with previous QGIS versions? If yes, which one?
AFAIK the issue has not been addressed on the QGIS side: see the thread at https://lists.osgeo.org/pipermail/qgis-developer/2024-May/066811.html

**Comment by drarbib** [comment]
i second @bogind findings, i just downloaded and used 3.36.3 Maidenhead and the problem is magically resolved even if I render the labels as paths
![image](https://github.com/qgis/QGIS/assets/150327591/1ff63d4c-f64a-4766-981a-a99d99fbf5fd)

**Comment by agiudiceandrea** [comment]
Hi @hareldunn @ryangentry @ilyessmap @ShieldsUpRedAlert, please check if the issue no longer occurs on your Windows systems using QGIS 3.36.3 or QGIS 3.34.7.

**Comment by ShieldsUpRedAlert** [comment]
I just checked and confirm that the issue is no longer present for me on V3.36.3.

**Comment by micha-silver** [comment]
Sorry, but I see that the bug persists in 3.36.3. It only occurs, as @nyalldawson  pointed out, when applying curved labels.
![QGIS_3 36_RTL_small](https://github.com/qgis/QGIS/assets/3841768/da82f0cd-bf43-4cb5-8185-d3d31d875d92)

**Comment by hareldunn** [comment]
I had the same issue, as @micha-silver mentioned, earlier this week on a different machine with a fresh 3.36.3. Regular labels worked, curved didn't. Don't have a screenshot

**Comment by agiudiceandrea** [comment]
The RTL issue in curved labels is a longstanding issue already reported about 10 years ago https://github.com/qgis/QGIS/issues/21940 probably having a different root cause.
