### ISSUE TITLE
QGIS Time error: UTC = Australian Central Standard Time

### ISSUE THREAD

**Issue by garrytre** [qgis/QGIS#54092]
### What is the bug or the crash?

QGIS version 3.26.3-Buenos Aires
Ubuntu 20.04.6 LTS

I originally made a GPS waypoint approximately lunch time in central Australia.

In QGIS I import a gpx file with waypoint

<time>2023-04-23T01:12:40Z</time>

The resultant feature's attribute table has time:

23/4/23 01:12:40 (ACST)

So somewhere is an awareness that I live in Australian Central Standard Time, but the calculation hasn't been done to convert UTC to ACST.

### Steps to reproduce the issue

Have a .gpx with <time> as above
Drag into QGIS
look at attribute table

This is the text in the .gpx, copied from kwrite (text editor). Longer gpx files have the same prob.

<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<gpx xmlns="http://www.topografix.com/GPX/1/1" creator="MapSource 6.13.7" version="1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.garmin.com/xmlschemas/GpxExtensions/v3 http://www.garmin.com/xmlschemas/GpxExtensions/v3/GpxExtensionsv3.xsd http://www.topografix.com/GPX/1/1 http://www.topografix.com/GPX/1/1/gpx.xsd">

  <metadata>
    <link href="http://www.garmin.com">
      <text>Garmin International</text>
    </link>
    <time>2023-08-03T08:43:39Z</time>
    <bounds maxlat="-30.5188039" maxlon="138.7377789" minlat="-30.5190697" minlon="138.7346331"/>
  </metadata>

  <wpt lat="-30.5190697" lon="138.7377789">
    <ele>500.0000000</ele>
    <time>2023-04-23T01:12:40Z</time>
    <name>zcp</name>
    <cmt>&gt;10 trees on Brachina Fm but only on road cutting, not on weathered surface.
garrytre@bigpond.com</cmt>
    <desc>&gt;10 trees on Brachina Fm but only on road cutting, not on weathered surface.
garrytre@bigpond.com</desc>
    <sym>Waypoint</sym>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>

  <wpt lat="-30.5188039" lon="138.7346331">
    <ele>503.0000000</ele>
    <time>2023-04-23T01:08:20Z</time>
    <name>zcpPowerLine100m</name>
    <cmt>&gt;10 trees on Brachina Fm but only on road cutting, not on weathered surface.
Powerline 100meters away.
garrytre@bigpond.com</cmt>
    <desc>&gt;10 trees on Brachina Fm but only on road cutting, not on weathered surface.
Powerline 100meters away.
garrytre@bigpond.com</desc>
    <sym>Waypoint</sym>
    <extensions>
      <gpxx:WaypointExtension xmlns:gpxx="http://www.garmin.com/xmlschemas/GpxExtensions/v3">
        <gpxx:DisplayMode>SymbolAndName</gpxx:DisplayMode>
      </gpxx:WaypointExtension>
    </extensions>
  </wpt>

</gpx>

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.26.3-Buenos Aires | QGIS code revision | 65e4edfdad
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.6 LTS
  |   |   |  
Active Python plugins
valuetool | 3.0.15
quick_map_services | 0.19.33
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99

</body></html>QGIS version
3.26.3-Buenos Aires
QGIS code revision
[65e4edfdad](https://github.com/qgis/QGIS/commit/65e4edfdad)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.12 (Ubuntu 12.12-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.6 LTS

Active Python plugins
valuetool
3.0.15
quick_map_services
0.19.33
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I originally put this in
https://gis.stackexchange.com/questions/464570/qgis-time-error-utc-australian-central-standard-time?noredirect=1#comment758644_464570
and was advised to put it here.

**Comment by agiudiceandrea** [comment]
@garrytre, thanks for reporting. QGIS 3.26 is no longer supported: please try if the issue does occur also using a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) as requested in the issue report form (you can try the [Flatpak](https://qgis.org/en/site/forusers/alldownloads.html#flatpak) version, since QGIS 3.28 and 3.32 are not available on Ubuntu 20.04).
Could you please provide a sample gpx file attaching it as a zipped file to this issue report?
Have you tried to add the gpx flle in QGIS using the Data [Source Manager -> GPS](https://docs.qgis.org/3.28/en/docs/user_manual/managing_data_source/opening_data.html#gps) dialog window instead of dragging and dropping it?

**Comment by garrytre** [comment]
[agiudiceandrea](https://github.com/agiudiceandrea) thank you for your attention

I can't install the flatpak, nor a later version of QGIS. I'll have to wait for ubuntu24.04 plus whatever latest QGIS.

Not sure if there's any point investigating my old version, but you've asked, so here goes.

Below is the zipped gpx
[Codon_pyr_2023-04-25.gpx.zip](https://github.com/qgis/QGIS/files/12274252/Codon_pyr_2023-04-25.gpx.zip)

Have you tried to add the gpx flle in QGIS using the Data [Source Manager -> GPS](https://docs.qgis.org/3.28/en/docs/user_manual/managing_data_source/opening_data.html#gps) dialog window instead of dragging and dropping it?

Yes, really interesting. Two screendumps show that the method of importing produces different results. Drag-n-drop has about 30 fields, DataSourceManager has 6, NOT including time. 
![DataSourceMgr](https://github.com/qgis/QGIS/assets/18093829/1194450a-77f5-4bb5-af80-a672333560d0)
![drag-n-drop](https://github.com/qgis/QGIS/assets/18093829/f8e1a1df-cfda-4083-b464-bb05068b5c30)

Anyway, thanks again, and I'll have to put this off for another day.

**Comment by agiudiceandrea** [comment]
@garrytre, using QGIS 3.28 the time is correctly displayed (my system tz is currently UTC+2 CEST):

![image](https://github.com/qgis/QGIS/assets/16253859/dee40284-ac73-4d93-a3da-340e5bb68350)

**Comment by garrytre** [comment]
Yes but that's not the point.
In your screen dump the time is 01:02:24 (UTC), which is what the original gpx file had, as z. That's correct.
But my attrib table says 01:02:24 (ACST), ie the UTC time but labelled as ACST.

But anyway, if it's a problem with an old version, maybe not a newer version, and it isn't too much of a problem for me, and I'll eventually get a QGIS update, I'm happy to drop it. Call it solved?

![image](https://github.com/qgis/QGIS/assets/18093829/e3badd4e-9bed-48ad-82e6-883a8b0329d1)
from drag-n-drop

But I'm still fascinated by the different resultant fields depending on whether I drag-n-drop, or I do a DataSourceManager import. Apparently not a bug, but I'm now aware of it, ie if I do a DataSourceManager import, then I loose time + other fields. Something to watch out for.

Thank you.

**Comment by agiudiceandrea** [comment]
@garrytre, the issue about the loose of the "time" field when you import the GPX layer in QGIS using the Data Source Manager -> GPS dialog window has been fixed with PR https://github.com/qgis/QGIS/pull/54632.
