### ISSUE TITLE
Random deadlock during batch processing

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#54124]
### What is the bug or the crash?

Since few QGIS updates, I randomly encounter a deadlock during a batch processing of hundreds of file.
No crash, no nothing

Processing just stops during algorithm initialization, I'm unable to cancel.
![image](https://github.com/qgis/QGIS/assets/39594821/3123d9ba-6f4d-4d7a-b11f-93bbef88efd2)

In above image, there is a deadlock and it will be stuck at this step forever.

Windows process manager shows 0 activity 
![image](https://github.com/qgis/QGIS/assets/39594821/0e338d6a-afcd-4cb0-b93e-14bb6af7b03c)

### Steps to reproduce the issue

Use a simple alg on lightweight files (like warp)

1. Open Warp
2. Switch to batch processing
3. Load lot of files (100 or 200 at least)
4. Define output files (in my case `file_path(file_path( @INPUT )) || '\\temp\\' ||  file_name( @INPUT )` )
5. start processing

Random part...

6. see deadlock

### Versions

3.32.1 / Master on Win10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

@haubourg can confirm too

Of course I can provide files to reproduce but I think that it can be easily reproduced.

For sure it didn't happen with 3.10 or 3.16 as I remember processing hundreds of file like I do now without issues.

May be linked to https://github.com/qgis/QGIS/pull/47769 ? gentle ping @nyalldawson

**Comment by roya0045** [comment]
Duplicate of https://github.com/qgis/QGIS/issues/53806

**Comment by nicogodet** [comment]
Oh yeah
Was on holidays when it was posted, I missed it.
