### ISSUE TITLE
Temporal time slider problem

### ISSUE THREAD

**Issue by HarrieBar** [qgis/QGIS#54121]
### What is the bug or the crash?

I my case there are layers per year from 1812 until 2023. By using fixed time periods per year a year layer is switched on and off. The time starts e.g. at 2018-01-01 00:00:00 and ends at 2018-12-31 23:59:59.
However when using the time slider to select a frame from 2017-01-01 <=t< 2018-01-01 00:00:00 the layer for 2018 is also selected.
The problem only gets away of I add 1 second to the setting. So it seems like the end of the period is included, or like the step size adds more than 1 year with milliseconds  behind the displayed end time.

### Steps to reproduce the issue

Create yearly layers between 1995-2023 and use for each of them the following temporal setting:
![setting](https://github.com/qgis/QGIS/assets/130652642/2a654c2a-ab16-49d1-9b88-8ddafebe31cb)

Use time management for a period of 1995-2023 with a step of 1 year.
![Using](https://github.com/qgis/QGIS/assets/130652642/5b7f6709-540f-4789-9702-2841c1fce7e1)

Step to the frame 2017-01-01 <=t< 2018-01-01 and verify whether 2018 is included. In my case it is, unless I use a fixed period of 2018-01-01 00:00:01.

### Versions

Qgis Version 3.28.6 and 3.32.1

QGIS-versie
3.32.1-Lima
QGIS code revisie
4a078ecf63
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.7.1
PROJ versie
9.2.1
EPSG-register databaseversie
v10.088 (2023-05-13)
GEOS versie
3.12.0-CAPI-1.18.0
SQLite versie
3.41.1
PDAL versie
2.5.5
PostgreSQL client versie
15.2
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
geopunt4Qgis
2.3.0.5
nominatim
1.4.5
openlayers_plugin
2.0.0
pdokbaggeocoder
0.6.6
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lbartoletti** [comment]
@HarrieBar Please, can you provide your data to reproduce and fix the error? Thanks.

**Comment by HarrieBar** [comment]
[_NL Historie_Gemeentegrenzen.zip](https://github.com/qgis/QGIS/files/14165279/_NL.Historie_Gemeentegrenzen.zip)
I recreated a project which demonstrates the problem.
Please note that two layers instead of one are selected after you start the project

**Comment by HarrieBar** [comment]
[_NL Historie_Gemeentegrenzen.zip](https://github.com/qgis/QGIS/files/14627416/_NL.Historie_Gemeentegrenzen.zip)
Sorry, this one should work
