### ISSUE TITLE
[Processing][GUI] multiple layer selector issue with r.pattch 

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#54129]
### What is the bug or the crash?

As the algorithm r.patch depends on the order of the input, the provided GUI is currently inadequate. The generated algorithm generates the list as shown in the layer selector. This means that the layer order cannot be modified and the results cannot be generated properly.

### Steps to reproduce the issue

1. Enable GRASS provider
2. Use r.patch
3. Select layers
4. Export as python/etc

### Versions

Tested on 3.28.7 but should not be relevant as the layer selection widget is unchanged and doesn't allow reordering

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can you elaborate? Layers in the multiple layer input widget can be reordered with drag-and-drop and this order is taken into account when command is exported to Python and other formats.

**Comment by roya0045** [comment]
> Can you elaborate? Layers in the multiple layer input widget can be reordered with drag-and-drop and this order is taken into account when command is exported to Python and other formats.

I mostly had in mind cases for the modeler, where reordering in the widget is not doable. But I guess doing manually could be doable.
