### ISSUE TITLE
NAS.xml files no longer importable

### ISSUE THREAD

**Issue by Revo2022** [qgis/QGIS#54138]
### What is the bug or the crash?

In 3.28.9 it is no longer possible to load German cadastre based NAS files. 
Prior (working in 3.28.6), QGIS was able to load these .xml files by creating a secondary .gfs file if not existing. Only if these .gfs files exist, it is still possible to load them with 3.28.9. Thus - if one never loaded a .xml file before, it is now impossible. 
In 3.28.9  a .gfs file is still being created when trying to import a .xml file, the contents are invalid though.

example file:
[BENUTZUNGSERGEBNIS_DAVID_20230808T135730Z.XML.txt](https://github.com/qgis/QGIS/files/12290982/BENUTZUNGSERGEBNIS_DAVID_20230808T135730Z.XML.txt)
(please remove .txt ending)

### Steps to reproduce the issue

- Drag'n'Drop xml file into QGIS 3.28.9
- Get "file not supported error"
- look at faulty .gml being created in the process

vs.
- Delete faulty .gml file that was created at xml's location
- Drag'n'Drop xml file into e.g. QGIS.3.28.6
- Confirm import dialog in QGIS
- Enjoy map with features
- look at correct .gml being created in the process

### Versions

QGIS-Version
3.28.9-Firenze
QGIS-Codeversion
66f4d63ad4
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.7.1
PROJ-Version
9.2.1
EPSG-Registraturdatenbankversion
v10.088 (2023-05-13)
GEOS-Version
3.12.0-CAPI-1.18.0
SQLite-Version
3.41.1
PDAL-Version
2.5.5
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
DbgBaum
3.4.5
PostNAS_Search
1.4.0
profiletool-master
4.2.6
db_manager
0.1.20
grassprovider
2.12.99
Kaufpreiskarte
1.0
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
schlubigo
0.9.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Works fine on 3.32.1 and 3.28.9 with provided file and .gfs file is created.

**Comment by Revo2022** [comment]
Interesting, everyone at work has the exact same issue. I just installed 3.28.9 at my private pc at home and it also works fine.

**Comment by Revo2022** [comment]
[ergb_0001FA8B.xml.txt](https://github.com/qgis/QGIS/files/12298630/ergb_0001FA8B.xml.txt)

@nicogodet please test again with this file

**Comment by nicogodet** [comment]
GDAL fails to detect layer in this file
```
>>> ogrinfo --version
GDAL 3.7.1, released 2023/07/06

>>> ogrinfo ergb_0001FA8B.xml --debug ON
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_KEA.dll using GDALRegister_KEA.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\ogr_FileGDB.dll using RegisterOGRFileGDB.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\ogr_HANA.dll using RegisterOGRHANA.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\ogr_MSSQLSpatial.dll using RegisterOGRMSSQLSpatial.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GDAL: Auto register C:\OSGeo4W\apps\gdal\lib\gdalplugins\ogr_SOSI.dll using RegisterOGRSOSI.
NAS: This file could be recognized by the NAS driver. If this is desired, you need to define the NAS_GFS_TEMPLATE configuration option.
NAS: This file could be recognized by the NAS driver. If this is desired, you need to define the NAS_GFS_TEMPLATE configuration option.
GML: Using Expat reader
GDAL: GDALOpen(ergb_0001FA8B.xml, this=000002466EA649C0) succeeds as GML.
INFO: Open of `ergb_0001FA8B.xml'
      using driver `GML' successful.
OGR: GetLayerCount() = 0

GDAL: GDALClose(ergb_0001FA8B.xml, this=000002466EA649C0)
```

```
>>> ogrinfo --version
GDAL 3.6.2, released 2023/01/02

>>> ogrinfo ergb_0001FA8B.xml --debug ON
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\gdal_ECW_JP2ECW.dll using GDALRegister_ECW_JP2ECW.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\gdal_GEOR.dll using GDALRegister_GEOR.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\gdal_HDF5.dll using GDALRegister_HDF5.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\gdal_MrSID.dll using GDALRegister_MrSID.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\ogr_MSSQLSpatial.dll using RegisterOGRMSSQLSpatial.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\ogr_OCI.dll using RegisterOGROCI.
GDAL: Auto register C:\PROGRA~1\QGIS32~1.16\apps\gdal\lib\gdalplugins\ogr_SOSI.dll using RegisterOGRSOSI.
NAS: Loading classes from ergb_0001FA8B.gfs
GDAL: GDALOpen(ergb_0001FA8B.xml, this=000001DAC341EC50) succeeds as NAS.
INFO: Open of `ergb_0001FA8B.xml'
      using driver `NAS' successful.
OGR: GetLayerCount() = 1

1: ALKIS_beziehungen (None)
NAS: Clearing classes.
GDAL: GDALClose(ergb_0001FA8B.xml, this=000001DAC341EC50)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

Not a QGIS issue.
GDAL change how it handles this kind of file 
On GDAL 3.6.2, it use NAS driver 
On GDAL 3.7.1, it use Expat driver instead of NAS driver `NAS: This file could be recognized by the NAS driver. If this is desired, you need to define the NAS_GFS_TEMPLATE configuration option.`
Ref. : https://github.com/OSGeo/gdal/pull/7532 and https://github.com/OSGeo/gdal/issues/7529

**Comment by rouault** [comment]
> gentle ping @rouault for further explanations

I don't have much to provide than the discussion of https://github.com/OSGeo/gdal/issues/7529 . Basically opening NAS requires a bit of configuration, and in particular setting the NAS_GFS_TEMPLATE configuration option, as explained in https://gdal.org/drivers/vector/nas.html

**Comment by Revo2022** [comment]
ok thanks, but even after reading documentation of gdal, im still not sure about where i can set it in qgis configuration, so the default behavior of loading these xml files changes. Also if it defaults to "NAS-Operationen;AAA-Fachschema;aaa.xsd;aaa-suite", what am I supposed to set it to?

**Comment by rouault** [comment]
> where I can set it in qgis configuration

Settings -> Options -> Environment -> Use custom variables, and then add a new one with Variable = NAS_GFS_TEMPLATE and Value let as empty (untested)

**Comment by Revo2022** [comment]
Tried null, empty string and setting an actual gfs file (https://raw.githubusercontent.com/norBIT/alkisimport/master/alkis-schema.gfs as an example), but with no luck
