### ISSUE TITLE
Identify Features - no features found when using rectangle to identify

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#54140]
### What is the bug or the crash?

When using the mode "Layer selection" there are no features found when using a **rectangle** to identify. For the other three modes it works without issues.

![grafik](https://github.com/qgis/QGIS/assets/20856381/f219d633-4759-4516-b064-6eb25a1bc16e)

### Steps to reproduce the issue

1. Add a vector layer to the project
2. For the tool "Identify Features" use the mode "Layer selection" 
3. Drag a rectangle to select feature(s)
4. See error -> No features found at this position

### Versions

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2016 Version 1607

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Duplicates #27074.

**Comment by pathmapper** [comment]
Thanks @alexbruy
