### ISSUE TITLE
Splitting MultiLineStrings gives awkward results

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#54155]
### What is the bug or the crash?

Using the _Split Features_ tool on a MultiLineString with several disjoint parts eventually splits more parts than those intersected.

![Peek 2023-08-09 09-57](https://github.com/qgis/QGIS/assets/11358178/46ee2a45-a3b6-40d3-a58e-1137dd562971)

### Steps to reproduce the issue

1. Get a layer with several non intersecting lines 
2. Generate a MultiLineString using _Dissolve_ processing algorithm
3. Use the _Split Features_ tool to split one of the MultiLineString's segments
4. Other segments are also split

### Versions

479d66ab

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

@ghtmtt Is this what you described on the mailing list?

**Comment by ghtmtt** [comment]
@uclaros that's exactly what I described yes!
