### ISSUE TITLE
qgis crash when open project

### ISSUE THREAD

**Issue by iraklisar68** [qgis/QGIS#54156]
### What is the bug or the crash?

not open project

### Steps to reproduce the issue

1. open project
2. loading
3. crash
4. bug reports

### Versions

QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
CalculateGeometry
0.6.8
changeDataSource
3.1
ClipMultipleLayers
3.2.0
clipper
1.2
GroupStats
2.2.7
latlontools
3.6.12
Qgis2threejs
2.7.1
qgiscloud
3.8.12
searchlayers
3.0.12
splitmultipart
1.0.0
SplitPolygonShowingAreas
0.13
zoomview
1.1.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## User Feedback

not open project

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x0000080c (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QIODevice::channelReadyRead :
QIODevice::write :
QTcpServer::proxy :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
multipleProviderMetadataFactory :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by iraklisar68** [comment]
What can we do?

**Comment by roya0045** [comment]
Different stack trace, different problems.

**Comment by GeoPlam1** [comment]
> Different stack trace, different problems.

It's different every time. Not a recurring cause. This is the message from a while ago:

## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x8001010d

Current thread 0x000004a4 (most recent call first):
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\core\cloud_api.py", line 194 in auth
    auth_manager.loadAuthenticationConfig(authcfg, cfg, True)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_login_dialog.py", line 96 in __init__
    cfg = self.network_manager.auth()
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_login_dialog.py", line 59 in show_auth_dialog
    CloudLoginDialog.instance = CloudLoginDialog(network_manager, parent)
  File "C:\Users/User/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\qfieldsync\gui\cloud_browser_tree.py", line 91 in createChildren
    CloudLoginDialog.show_auth_dialog(self.network_manager)
Windows fatal exception: access violation

Current thread 0x000004a4 (most recent call first):
<no Python frame>
```


**Stack Trace**

```

QObjectPrivate::isSignalConnected :
QVariantAnimation::qt_metacast :
QPropertyAnimation::updateState :
QUnifiedTimer::setSlowdownFactor :
QFocusFrame::trUtf8 :
QDockWidgetLayout::wmSupportsNativeWindowDeco :
QDockWidgetLayout::wmSupportsNativeWindowDeco :
QDockWidgetLayout::wmSupportsNativeWindowDeco :
QTabBarPrivate::~QTabBarPrivate :
QTabBarPrivate::isAnimated :
QMainWindow::restoreState :
pdal::operator< :
QgisApp::showEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::show_helper :
QWidgetPrivate::setVisible :
QWidget::setVisible :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```



**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1



**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

**Comment by Forstkarte** [comment]
@ZuzanaSp Maybe you have the same problem as us #53956 . Would be nice if you try our workaround and get back to me if this works for you, or if you found any other way to work around this issue.

**Comment by nyalldawson** [comment]
This ticket is currently un-actionable. There's too many comments from different issues, and no steps to reproducible any of the crashes reliably. 

I'm closing for now -- please re-open individual tickets for each issue and provide detailed step-by-step guides to reproduce.
