### ISSUE TITLE
not reproducable crash

### ISSUE THREAD

**Issue by teesix** [qgis/QGIS#54165]
## User Feedback

I'm not suprised the thing crashed. I had OSM as a layer and open sea map seamark with http://t1.openseamap.org/seamark/{z}/{x}/{y}.png , but the latter gave a timeout loading. Before all off this I had a crash while making MBtiles, sqlite3.OperationalError: database is locked might be caused by old hardware. I tried to close the timeout message. Thes I tried to close the app, but then e message poped up about a tilemaking process still running. I pressed ok for stop the process, but the message keept poping up. then afer severerall more attepts this crash message apeared. All of this is not very helpfull think

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00000958 (most recent call first):
<no Python frame>
```

**Stack Trace**
No stack trace is available.

**QGIS Info**
QGIS Version: 3.26.0-Buenos Aires
QGIS code revision: 0aece2818e
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.0
Running against GDAL: 3.5.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

can't be reproduced, to many clicks

### Versions

QGIS-versie
3.26.0-Buenos Aires
QGIS code revisie
0aece2818e
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.5.0
PROJ versie
9.0.1
EPSG-register databaseversie
v10.064 (2022-05-19)
GEOS versie
3.10.3-CAPI-1.16.1
SQLite versie
3.38.1
PDAL versie
2.3.0
PostgreSQL client versie
unknown
SpatiaLite versie
5.0.1
QWT versie
6.1.6
QScintilla2 versie
2.13.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Just did what you asked, I do not expect any follow up, just reporting because that was asked for.
kind regards,

Paul

**Comment by agiudiceandrea** [comment]
@teesix, thanks for reporting. QGIS 3.26 is no longer supported.
