### ISSUE TITLE
Missing icon for Scene tab in Data Source Manager

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#54172]
### What is the bug or the crash?

Open the data source manager and watch the scene tab

### Steps to reproduce the issue

![scene_icon](https://github.com/qgis/QGIS/assets/7983394/32657c96-5b44-45ec-918d-638aae9424ce)

### Versions

master 3.33 af1dbc282a on Win 10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
Fixed.
