### ISSUE TITLE
Wrong numerical scale in printed map 

### ISSUE THREAD

**Issue by Energeo1** [qgis/QGIS#54175]
### What is the bug or the crash?

I have a problem with the numerical scale on every printed map I created. 
In the layout of the maps I always set both a scale bar and a numerical scale.
When I manually measure the distances on the printed map and use the scale bar for calculating, it matches the digitally measured distances in the QGIS project. Though distances manually calculated using the numerical scale do not match. This happens with every map, at every scale I try and irrespective of the chosen projection and coordinate system of the project. 
Does anybody refer to this problem?
For the maps I create it is really important to have a correct scale so I would feel happy about a bug-fix for this problem. 
Attached a simplified example map. 
![Example_Scale_Problem](https://github.com/qgis/QGIS/assets/141151894/6da5751d-4d72-4e92-a373-34624d2bf5bd)

### Steps to reproduce the issue

1. I create a project with the coordinate system WGS 84 (EPSG: 3857)
2. I add all my layers, mostly in the projection ETRS 89 UTM Zone 32 N (EPSG: 25832)
3. I create a layout and add a map that uses the coordinate system of the project, a scale bar and a numerical scale
4. I export the created layout map to pdf and print it

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.28.9-Firenze | QGIS-Codeversion | 66f4d63ad4
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.7.1
PROJ-Version | 9.2.1
EPSG-Registraturdatenbankversion | v10.088 (2023-05-13)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.0.1
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
AnotherDXF2Shape | 1.2.9
autoSaver | 2.6
ClipMultipleLayers | 3.2.0
DigitizingTools | 1.5.2
dimensioning | 0.2
HCMGIS | 23.7.19
joinmultiplelines | Version 0.4.1
mmqgis | 2021.9.10
openlayers_plugin | 2.0.0
PointConnector | 2.0
qchainage | 3.0.1
qfieldsync | v4.5.0
qgis_points2one | 0.3.1
qgsAzimuth | 0.9.15
QRectangleCreator | 0.3
quick_map_services | 0.19.33
rectanglify | 1.0.3
SRTM-Downloader | 3.1.17
SuperLabeling | ver.1.4
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.28.9-Firenze
QGIS-Codeversion
[66f4d63ad4](https://github.com/qgis/QGIS/commit/66f4d63ad4)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.7.1
PROJ-Version
9.2.1
EPSG-Registraturdatenbankversion
v10.088 (2023-05-13)
GEOS-Version
3.12.0-CAPI-1.18.0
SQLite-Version
3.41.1
PDAL-Version
2.5.5
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
AnotherDXF2Shape
1.2.9
autoSaver
2.6
ClipMultipleLayers
3.2.0
DigitizingTools
1.5.2
dimensioning
0.2
HCMGIS
23.7.19
joinmultiplelines
Version 0.4.1
mmqgis
2021.9.10
openlayers_plugin
2.0.0
PointConnector
2.0
qchainage
3.0.1
qfieldsync
v4.5.0
qgis_points2one
0.3.1
qgsAzimuth
0.9.15
QRectangleCreator
0.3
quick_map_services
0.19.33
rectanglify
1.0.3
SRTM-Downloader
3.1.17
SuperLabeling
ver.1.4
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Energeo1, thanks for reporting. The issue is due to the fact that the CRS EPSG:3857, which you are using for the map in the print layout, greatly distorts distances.
Please see https://github.com/qgis/QGIS/issues/50193#issuecomment-1246991362, https://github.com/qgis/QGIS/issues/29180#issuecomment-627430274, https://gis.stackexchange.com/questions/217306/qgis-print-composer-scale-problems, https://docs.qgis.org/3.28/en/docs/gentle_gis_introduction/coordinate_reference_systems.html.
