### ISSUE TITLE
Reading DXF in AutoCAD not possible

### ISSUE THREAD

**Issue by wkaper** [qgis/QGIS#54176]
### What is the bug or the crash?

It is not possible to read an exported DXFfile into AutoCAD.
  Only when I delete all the following lines from the DXF file can I read the DXF into AutoCAD:

 41
nan.0
 42
nan.0
[DXFtest.zip](https://github.com/qgis/QGIS/files/12312599/DXFtest.zip)

### Steps to reproduce the issue

Project
Importeren/Exporteren
Export Project naar DXF...

### Versions

3.32.0-1
3.32.1-1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@wkaper, thanks for reporting. Could you please provide the layer that you have exported to DXF and describe the exacts steps e parameter used to export such layer to DXF?

**Comment by wkaper** [comment]
Project

                Nieuw

Drag and Drop extract.zip into the project

Double click layer “dkk_perceel.gml”

Symbologie

                Stijl

                               Stijl laden

                               … Bladeren

Choose “perceelnummers.qml”

Openen

Stijl laden

OK

Project

                Inporteren/Exporteren

                               Exporteer project naar DXF…

                               Choose directory en give it a name

                               Opslaan (Save)

                               OK

 



                

 

 

Van: Andrea Giudiceandrea ***@***.***> 
Verzonden: vrijdag 11 augustus 2023 13:04
Aan: qgis/QGIS ***@***.***>
CC: wkaper ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [qgis/QGIS] Reading DXF in AutoCAD not possible (Issue #54176)

 

@wkaper <https://github.com/wkaper> , thanks for reporting. Could you please provide the layer that you have exported to DXF and describe the exacts steps e parameter used to export such layer to DXF?

**Comment by agiudiceandrea** [comment]
@wkaper, it is not possible to provide the file via e-mail message. Please attach the file directly in a comment in this issue report using the GitHub web interface.

**Comment by roya0045** [comment]
> @wkaper, it is not possible to provide the file via e-mail message. Please attach the file directly in a comment in this issue report using the GitHub web interface.

I'm assuming they are referencing the zip provided in the main post.

**Comment by wkaper** [comment]
Project
                Nieuw
Drag and Drop extract.zip into the project
Double click layer “dkk_perceel.gml”
Symbologie
                Stijl
                               Stijl laden
                               … Bladeren
Choose “perceelnummers.qml”
Openen
Stijl laden
OK
Project
                Inporteren/Exporteren
                               Exporteer project naar DXF…
                               Choose directory en give it a name
                               Opslaan (Save)
                               OK
[perceelnummers.zip](https://github.com/qgis/QGIS/files/12334312/perceelnummers.zip)
[extract.zip](https://github.com/qgis/QGIS/files/12334314/extract.zip)
[perceelnummers.zip](https://github.com/qgis/QGIS/files/12334325/perceelnummers.zip)

**Comment by agiudiceandrea** [comment]
> I'm assuming they are referencing the zip provided in the main post.

@roya0045, the zip provided in the main post only contains the exported dxf file and a QGIS project file without the original layer.

The subsequently provided files [extract.zip](https://github.com/qgis/QGIS/files/12334314/extract.zip) and 
[perceelnummers.zip](https://github.com/qgis/QGIS/files/12334325/perceelnummers.zip) allow me to confirm the reported issue: it does occur using current QGIS Master, while it doesn't occur using QGIS 3.28.9 or QGIS 3.30.3 on Windows.

Excerpt from the DXF exported by QGIS Master:
```
dkk_perceel.gml
  2
symbolLayer0
 50
0.0
 41
nan.0
 42
nan.0
 10
105689.52599999999802094
 20
502778.78999999997904524
```

Excerpt from the DXF exported by QGIS 3.30.3 or QGIS 3.28.9:
```
dkk_perceel.gml
  2
symbolLayer0
 50
0.0
 10
105689.52599999999802094
 20
502778.78999999997904524
```

The DXF exported by QGIS master contains the following additional lines that make AutoCAD unhappy:
```
 41
nan.0
 42
nan.0
```

From https://images.autodesk.com/adsk/files/autocad_2012_pdf_dxf-reference_enu.pdf, it seems the 41 and 42 codes have the following meaning:
```
41 X scale factor (optional; default = 1)
42 Y scale factor (optional; default = 1)
```
