### ISSUE TITLE
"New" button to connect a scene in Data Source Manager

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#54174]
### What is the bug or the crash?

Open the Data source Manager dialog
Enable the "Scene" tab
Under Connections, there is a "New" button with an arrow next to it. That arrow contains a single item so it is not necessary that the button is a menu. It should be a single click directly opening the connection dialog.

~~Another issue is that the Connection dialog that opens refers to "vector Tiles" instead of "3D tiles"~~

### Steps to reproduce the issue

![new_scene](https://github.com/qgis/QGIS/assets/7983394/e70c674c-33bf-4e52-89f0-ecd7ab836fb9)

### Versions

master 3.33 af1dbc2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
> Another issue is that the Connection dialog that opens refers to "vector Tiles" instead of "3D tiles"

Fixed by https://github.com/qgis/QGIS/commit/3a4a9f08bdc7630120ab7a0f55d5f8e68371c50b I think

**Comment by DelazJ** [comment]
Indeed. I'm on osgeo4w build, 9h older than the fix.

**Comment by nyalldawson** [comment]
This is by design-- the intention is that this page is generic, and in future will also support other formats like i3s. Right now the page itself doesn't explicitly mention cesium tiles anywhere else, so this is the only clue a user gets as to the currently supported scene types.

**Comment by alexbruy** [comment]
Can be closed?
