### ISSUE TITLE
Hide Maps

### ISSUE THREAD

**Issue by Annalross93** [qgis/QGIS#54188]
### What is the bug or the crash?

I have issues with qgis graphics /  maps, can you help me with it?

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/142001690/74ad4fb7-7e24-4fbd-ab03-9af64135ce5b)

### Versions

3.28

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Annalross93** [comment]
not

**Comment by agiudiceandrea** [comment]
Hi @Annalross93, thanks for reporting. 
Could you explain more precisely what exactly the problem is? Which layer type is not displaying correctly? Could you provide all the details of that layer? Could you provide all the steps and info an user must follow in order to replicate the same issue?

**Comment by Annalross93** [comment]
Hi thanks for the reply. The layers are google satellite e google terrain; at a given scale they disappear or remain cut off so I can’t see the details of the area I’m interested in. I’m not so good with QGIS, this is the properties of the layer hope this is useful.
Thanks again 


 

Da: Andrea Giudiceandrea ***@***.***> 
Inviato: venerdì 11 agosto 2023 12:55
A: qgis/QGIS ***@***.***>
Cc: Annalross93 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [qgis/QGIS] Hide Maps (Issue #54188)

 

Hi @Annalross93 <https://ddec1-0-en-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fAnnalross93&umid=c19fc8cd-4375-4611-acdb-7593271ab571&auth=aac75b56bd2e3787dfb27f7959629fc8d80e4011-6adbc886f43f52e104f0ae51839671972c951352> , thanks for reporting.
Could you explain more precisely what exactly the problem is? Which layer type is not displaying correctly? Could you provide all the details of that layer? Could you provide all the steps and info an user must follow in order to replicate the same issue?

**Comment by agiudiceandrea** [comment]
@Annalross93, the issue is very likely not a QGIS issue but it may be a network issue from your side or a Google Satellite service issue. I don't have any issue displaying the WMS/XYZ Google Satellite or Google Terrain layers added using the QuickMapServices plugin.
I suggest you to clear the Network cache (Settings->Options->Network->Cache Settings->Clear cache button) or to create and use a new QGIS user profile.

**Comment by Annalross93** [comment]
Ok i’ll try thank you again!!!

 

Da: Andrea Giudiceandrea ***@***.***> 
Inviato: venerdì 11 agosto 2023 13:36
A: qgis/QGIS ***@***.***>
Cc: Annalross93 ***@***.***>; Mention ***@***.***>
Oggetto: Re: [qgis/QGIS] Hide Maps (Issue #54188)

 

@Annalross93 <https://ddec1-0-en-ctp.trendmicro.com:443/wis/clicktime/v1/query?url=https%3a%2f%2fgithub.com%2fAnnalross93&umid=dd764f19-87a4-4a78-92b7-2a6bad4c5fee&auth=aac75b56bd2e3787dfb27f7959629fc8d80e4011-ffdfb253c957c667d41af8e05770e4a473e638ec> , the issue is very likely not a QGIS issue but it may be a network issue from your side or a Google Satellite service issue. I don't have any issue displaying the WMS/XYZ Google Satellite or Google Terrain layers added using the QuickMapServices plugin.
I suggest you to clear the Network cache (Settings->Options->Network->Cache Settings->Clear cache button) or to create and use a new QGIS user profile.
