### ISSUE TITLE
The spinbox for the attribute row cache setting is too narrow on dark themes

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#54201]
### What is the bug or the crash?

This is likely an issue related to High DPI scaling. Since QGIS 3.32, on dark themes, the spinbox for the attribute table row cache setting is too narrow, thus the reset button is placed above the last digits of the value.

3.32 (night mapping)
![grafik](https://github.com/qgis/QGIS/assets/78353871/d29d89d5-e4f8-4329-9053-4fb309cc7574)

3.28 (night mapping):
![grafik](https://github.com/qgis/QGIS/assets/78353871/ab974c7c-efe0-4995-bd6d-e931fb1a25a2)

Same applies for the _blend of gray_ theme.

### Steps to reproduce the issue

1. Create a new profile
2. Change the theme to either _night mapping_ or _blend of gray_
3. Restart QGIS
4. Open settings, switch to the _Data sources_  tab

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf63
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Screen resolution: 3840 x 2160 px
Scale factor: 150% (The described appearance does not change when switched to 100%)

**Comment by nirvn** [comment]
To be fixed by https://github.com/qgis/QGIS/pull/54213
