### ISSUE TITLE
QGIS kubernetes deployment connect issue

### ISSUE THREAD

**Issue by rkhandha** [qgis/QGIS#54208]
### What is the bug or the crash?

I am following QGIS kubernetes deployment in https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html
in Openshift platform. 

QGIS pod is up
2023-08-10 19:40:31,328 INFO Included extra file "/etc/supervisor/supervisor.d/supervisor.xvfb.conf" during parsing
2023-08-10 19:40:31,330 INFO supervisord started with pid 1
2023-08-10 19:40:32,332 INFO spawned: 'Xvfb' with pid 7
2023-08-10 19:40:33,333 INFO success: Xvfb entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)

I have deployed nginx with with fastcgi it is up as well but when  to connect 

2023/08/10 20:09:46 [error] 27#27: *13 connect() failed (111: Connection refused) while connecting to upstream, client: x.x.x.x, server: _, request: "GET /qgis-server HTTP/1.1", upstream: "fastcgi://x.x.x.x:5555", host: "xxx.xom"

### Steps to reproduce the issue

Kubernetes deploy 

1. Docker Image used -  docker.io/qgis/qgis
2.  QGIS deployment https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html in Openshift platform. 
3. Nginx deployment docker.io/nginx:stable-alpine3.17-slim
4. nginx conf 
server {
  listen 8080;
  server_name _;
  location / {
    root  /usr/share/nginx/html;
    index index.html index.htm;
  }
  location /qgis-server {
    proxy_buffers 16 16k;
    proxy_buffer_size 16k;
    gzip off;
    include fastcgi_params;
    fastcgi_pass qgis-server-svc:5555;
  }
}

5. Nginx deployment 
nginx service as ClusterIP instead of NodePort.

### Versions

$ qgis --version
QGIS 3.33.0-Master 'Master' (exported)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Could you take a look at this PR https://github.com/qgis/QGIS-Documentation/pull/8407 ?
See if it solves your issue ?

**Comment by rkhandha** [comment]
PR https://github.com/qgis/QGIS-Documentation/pull/8407 Did not solve my issue.  I still have the sam issue.  How can I kubernetes environment test that qgis-server can communicate with nginx.

**Comment by elpaso** [comment]
This does not seem a QGIS bug, maybe a documentation one.
