### ISSUE TITLE
QgsSnappingConfig.setEnabled

### ISSUE THREAD

**Issue by qgis2000** [qgis/QGIS#54243]
### What is the bug or the crash?

Can not disable project snapping config.

### Steps to reproduce the issue

Python Console

>>> iface.mapCanvas().project().snappingConfig().setEnabled(False)
>>> iface.mapCanvas().project().snappingConfig().enabled()
True

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
```
config = QgsProject.instance().snappingConfig()
config.setEnabled(False)
QgsProject.instance().setSnappingConfig(config)
```
