### ISSUE TITLE
QGIS crashes when I choose to open new file without closing current unsaved file

### ISSUE THREAD

**Issue by usubaliev** [qgis/QGIS#54249]
### What is the bug or the crash?

**QGIS crashes when I choose to open new file without closing current unsaved file. In the unsaved file there is a scratch layer temporary. In a warning promt dialog about loosing temp layer I accept OK then QGIS gives error after 30 sec. waiting.**

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003f44 (most recent call first):

Stack Trace

QMimeType::staticMetaObject :
QgsMapCanvas::setMapTool :
QgisApp::activateDeactivateLayerRelatedActions :
QgisApp::layerEditStateChanged :
QObject::qt_static_metacall :
QgsVectorLayer::rollBack :
QgisApp::saveDirty :
QgisApp::fileNew :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

**QGIS crashes when I choose to open new file without closing current unsaved file. In the unsaved file there is a scratch layer temporary. In a warning promt dialog about loosing temp layer I accept OK then QGIS gives error after 30 sec. waiting.**

### Versions

QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@usubaliev, thanks for reporting. With "file" do you mean "QGIS project file"? Could you please try if the issue does occur also using a new QGIS user profile and/or the latest currently available QGIS version?
