### ISSUE TITLE
Drag and drop geopackage with multiple layers hits assert

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#54259]
### What is the bug or the crash?

If a geopackage containing multiple layers is drag and dropped into qgis, then more than one layer is selected to be added to the map, an assert is hit in debug builds `Fatal: ASSERT: "ds->refCount > 0" in file /home/uclaros/dev/cpp/QGIS/src/core/providers/ogr/qgsogrproviderutils.cpp, line 2299`

### Steps to reproduce the issue

0. Start your qgis debug build
1. Drag and drop geopackage containing multiple layers
2. Select more than one layer to be added to the map
3. Assert is hit

```
Fatal: ASSERT: "ds->refCount > 0" in file /home/uclaros/dev/cpp/QGIS/src/core/providers/ogr/qgsogrproviderutils.cpp, line 2299
```

### Versions

3a685e5b

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
fixed per https://github.com/qgis/QGIS/pull/54603
