### ISSUE TITLE
Provided raster symbol size override not when applied when set on hidden symbol

### ISSUE THREAD

**Issue by roya0045** [qgis/QGIS#54262]
### What is the bug or the crash?

In the layout legend there seems to be an issue with raster symbol size override.

If the dimensions of the color ramp of a raster were set when the ramp was not displayed, the values will not be taken into account.

To fix this the value must be set again or modified slightly when the symbol is sivisble. This will force the redraw and the value in the box to be applied.

### Steps to reproduce the issue

1. Add raster ro the legend of a layout
2. Hide those raster (with a theme or from the main canvas)
3. Change the size override of the raster symbol in its properties (like 2o of height)
4. Display the raster in the linked canvas
5. Raster symbol size is still the default size
6. Go it its property and add a 1 in the decimal of the size
7. Symbol is updated to the proper size

### Versions

Tested in 3.28.7, couldn't test on newer at the moment.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (ae45e662c6a6f6ad61b3297a3f34efde8a63eec0), but not sure I made it correctly.

**Comment by roya0045** [comment]
@alexbruy I just hit this again and after some digging in the code, I think I found the issue.

When editing the size of a legend item, setting the size will hit https://github.com/qgis/QGIS/blob/fa961c7b5bbb60fca014cdc514cfc66bcfb3291c/src/gui/layout/qgslayoutlegendwidget.cpp#L1800

At that point in the code it will iterate over the symbol nodes ( I don't think line 1805 is evaluated to true) and it runs in the next condition that fetches symbol nodes. As the node is inactive when the value is set, it get ignored? https://github.com/qgis/QGIS/blob/fa961c7b5bbb60fca014cdc514cfc66bcfb3291c/src/core/layertree/qgslayertreemodel.cpp#L1698C1-L1698C64

Though the value wouldn't be retrieved, which is not the case.. Here's a gif for reference 

![image](https://github.com/user-attachments/assets/a4ce8184-11e7-4bd1-b012-9cca8e5dab32)
