### ISSUE TITLE
Activating notify/listen feature crash QGIS

### ISSUE THREAD

**Issue by CATER-COM** [qgis/QGIS#54260]
### What is the bug or the crash?

Activating "actualize layer on notification" in rendering tab or activating  "execute if message is ..." in python action, will freeze QGIS when applying. Need to crach QGIS to restart it. 

### Steps to reproduce the issue

1. Open new project
2. Load postgres layer
3. Got to rendering tab in layer property 
4. Activate "actualize layer on notification" 
5. Click "apply" or saving the project
6. QGIS Freeze

Follow the same steps on 
step 4 got to Action tab, set a python action, type a message in "Execute if message is "

![20230816-095444](https://github.com/qgis/QGIS/assets/6432485/1a15e88f-47ff-42f7-8705-348603c39c3a)
![20230816-095251](https://github.com/qgis/QGIS/assets/6432485/61ed769f-8d20-438c-8709-717f229ce980)

### Versions

3.28.9 and 3.32

Version de QGIS | 3.28.9-Firenze | Révision du code | 66f4d63ad4
Version de Qt | 5.15.3
Version de Python | 3.10.6
Version de GDAL/OGR | 3.4.1
Version de Proj | 8.2.1
Version de la base de données du registre EPSG | v10.041 (2021-12-03)
Version de GEOS | 3.10.2-CAPI-1.16.0
Version de SQLite | 3.37.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.11.6
Version de l'OS | Ubuntu 22.04.3 LTS

Extensions Python actives
SpreadsheetLayers | 2.1.0
ImportPhotos | 3.0.5
refFunctions | 1.6
pickLayer | 3.9.6
EasyCustomLabeling | 2.1
qfieldsync | v4.5.0
MemoryLayerSaver | 5.0.1
openlayers_plugin | 2.0.0
attributePainter | 5.3
processing | 2.12.99
db_manager | 0.1.20
sagaprovider | 2.12.99
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tested on Windows 10 and Ubuntu 22.04.3 LTS

**Comment by CATER-COM** [comment]
Can also reproduce the bug with 3.22.16. Bug appear on layer with or without geometry.

**Comment by troopa81** [comment]
I fail to reproduce on Linux with master and 3.28.

Can you provide a dataset and a project sample?

**Comment by CATER-COM** [comment]
Hi @troopa81 i will send you postgres test database auth by e-mail.
