### ISSUE TITLE
r.watershed not working on Grass 8.3

### ISSUE THREAD

**Issue by skollll** [qgis/QGIS#54279]
### What is the bug or the crash?

This grass command works on GRASS 7.8 

r.watershed dem thresh=1000 accum=ac_10k drain=ddir_10k basin=basin_10k stream=rivers -b  --o

But not on GRASS 8.3 

Is is not calculating correctly the watershed areas 

### Steps to reproduce the issue

# need some tifs of the area that you want to show the rivers 
gdalwarp *.tif DEM.tif
r.in.gdal input=DEM.tif output=p1 --o
g.region rast=p1
r.watershed p1 thresh=1000 accum=ac_10k drain=ddir_10k basin=basin_10k stream=rivers -b  --o
r.null map=rivers setnull=0
r.to.vect -s rivers out=rios type=line --o
v.out.ogr input=rios type=line output=RIVERS.shp format=ESRI_Shapefile  --o

### Versions

8.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Are you using QGIS processing or directly GRASS in shell ?

If you are doing exact same steps using both version and command executed are the same, issue could come from GRASS, not QGIS.
