### ISSUE TITLE
Invalid Data Source: /home/parisa/Downloads/apps/BlueMarble/ttMaps/Maps/BlueMarble/01.ecw is not a valid or recognized data source.

### ISSUE THREAD

**Issue by parisa-hr** [qgis/QGIS#54277]
### What is the bug or the crash?

`Invalid Data Source: /home/parisa/Downloads/apps/BlueMarble/ttMaps/Maps/BlueMarble/01.ecw is not a valid or recognized data source.`

**Cant load ECW Maps**

### Steps to reproduce the issue

Hi 
I want to load ECW maps in QGIS 3.22 In ubuntu 22.04
I ran the latest version (master repo) of the code with Qt 5.15 and also tried it by installing it ( QGIS 3.22.4-Białowieża) 
In both ways, I can't load `.ecw maps` 

I also tried StackOverflow questions said like [this](https://gis.stackexchange.com/q/27247/200592) or [this GitHub repo](https://github.com/bogind/libecwj2-3.3) but the problem is that these ways are too old and they didn't work.

![image](https://github.com/qgis/QGIS/assets/44742050/af7830a5-ad58-48c0-985c-88c5b9e8d1c3)

![image](https://github.com/qgis/QGIS/assets/44742050/f823c059-b8a5-4062-ad87-c5d7c4861076)

### Versions

QGIS 3.22.4-Białowieża

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Please help me I am not a master in GIS.

**Comment by elpaso** [comment]
Did you try to run gdalinfo on the file?
If it run successfully, can you attach the file for testing?
