### ISSUE TITLE
Mesh label

### ISSUE THREAD

**Issue by Q-R-B** [qgis/QGIS#54307]
### Feature description

First thanks for the great mesh fonctionalities in Qgis.

A great addition would be to be able to label vertices and faces.

Is this something that could be implemented?

many thanks
Quentin

**Comment by saberraz** [comment]
Hi @Q-R-B 
This is something we had looked into and have a good idea of how to implement based on previous requests.

Feel free to drop me a line if you want to fund this feature.

**Comment by saberraz** [comment]
Addressed by https://github.com/qgis/QGIS/pull/55708 and follow up PRs.
