### ISSUE TITLE
install fail : qtbase-abi-5-15-3

### ISSUE THREAD

**Issue by muscatelle** [qgis/QGIS#54308]
### What is the bug or the crash?

Cannot install qgis on fresh KDE Neon ( on ubuntu 22.04).
I've read previous bug reports and note that this is a fresh install.

### Steps to reproduce the issue

sudo pkcon install qgis
Resolving                               [=========================]         
Testing changes                         [=========================]         
Finished                                [=========================]         
Fatal error: The following packages have unmet dependencies:
  qgis-providers: Depends: qtbase-abi-5-15-3

sudo cat /etc/apt/sources.list.d/qgis.sources
Types: deb deb-src
URIs: https://qgis.org/ubuntu
Suites: jammy
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg

lsb_release -a
No LSB modules are available.
Distributor ID: Neon
Description:    KDE neon 5.27
Release:        22.04
Codename:       jammy

### Versions

Latest Release | 3.32.x Lima ​-

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

qtbase-abi appears to be part of qt5core5a and this installation appears to use a much later version
sudo pkcon search  libqt5core5a
Installed       libqt5core5a-5.15.10+p22.04+tunstable+git20230801.0307-0.amd64 (auto:user_jammy-jammy-main)     Qt 5 core module

My first installation attempt was some 3 weeks ago and I tried the nightly release with no change so waited patiently for the next point release on  2023-08-18- but the problem remains.

I've also installed gdal-bin as previous reports indicated qtbase-abi was a gdal dependency problem, but the gdal-bin installed with no errors

**Comment by jef-n** [comment]
jammy has 5.15.3+dfsg-2.    KDE Neon apparently uses a newer version of Qt.
