### ISSUE TITLE
"min zoom level" isn't respected when using vector tiles

### ISSUE THREAD

**Issue by rkettelerij** [qgis/QGIS#54312]
### What is the bug or the crash?

When adding a Vector Tiles connection one can specify a min zoom level and a max zoom level. The min zoom level isn't respected by QGIS. For example if I add a vector tiles server and set min zoom = 17 and max zoom = 17 then QGIS tries to load tiles even on zoom level 1.

This crashes QGIS - and potentially the vector tiles server - since loading tiles on a deep zoom level such as WebMercator 17 when we're actually on zoom level 1 (country/world level) results in too many HTTP requests.

### Steps to reproduce the issue

- Vector Tiles > New Generic Connection
- Add a XYZ url. 
   - This could even be a non-existing URL such as http://example.com/{z}/{y}/{x}.pbf, that's sufficient to reproduce this issue
- Set min and max zoom level to the same number. And use a deep zoomlevel (e.g. 16 or 17 in webmercator)
- Save
- Open View > Panels > Debug tools

Now zoom in and observe that QGIS starts making requests right away (for zoom level 17), even when we're not (even close) on zoom level 17. This overloads QGIS and potentially the backend.

Note: you can optionally add a WMTS basemap to make zooming in more easy/clear.

### Versions

Tested against multiple versions. Occurs in all of them.

- 3.22 LTR
- 3.28 LTR
- 3.30.1
- 3.32
- Nightly build of August 21, 2023

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This isn't what "minimum zoom" means in QGIS -- it's a way of limiting the range of tile z values to fetch, so by setting the minimum zoom to 17 then you are instructing QGIS **NOT** to fetch tiles from zoom levels 1-16, and are forcing it to retrieve all the zoom level 17 tiles for smaller zoom scale maps instead. So it's working as intended.

If you want to prevent the layer showing ANYTHING at smaller scales, then you should set the layer's "scale visibility" instead.
