### ISSUE TITLE
Faulty docker images published to docker hub

### ISSUE THREAD

**Issue by CodeBardian** [qgis/QGIS#54314]
### What is the bug or the crash?

I am using the `qgis_testrunner.sh` script to run some unit tests for a QGIS-Plugin. Recently, the test runner always returns with `ERROR: no output from the test runner! (exit code: 0)`

This is basically the same issue as https://github.com/qgis/QGIS/issues/50729, but now it is affecting the recent `release-3_28` and `release-3_30` images and I believe this time it has a different cause.

From what I can tell there seem to be two different issues at play here:

1. The Github Actions Runner is running out of disk space when building the images. This causes the build to fail. 

```
 > [ 8/13] RUN SUCCESS=OK   && cmake   -GNinja   -DUSE_CCACHE=OFF   -DCMAKE_BUILD_TYPE=Release   -DCMAKE_INSTALL_PREFIX=/usr   -DWITH_DESKTOP=ON   -DWITH_SERVER=ON   -DWITH_3D=ON   -DWITH_BINDINGS=ON   -DWITH_CUSTOM_WIDGETS=ON   -DBINDINGS_GLOBAL_INSTALL=ON   -DWITH_STAGED_PLUGINS=ON   -DWITH_GRASS=ON   -DSUPPRESS_QT_WARNINGS=ON   -DDISABLE_DEPRECATED=ON   -DENABLE_TESTS=OFF   -DWITH_QSPATIALITE=ON   -DWITH_APIDOC=OFF   -DWITH_ASTYLE=OFF   ..   && ninja install || SUCCESS=FAILED   && echo "$SUCCESS" > /QGIS/build_exit_value:
9363.4   file INSTALL cannot copy file "/QGIS/build/output/i18n/qgis_ja.qm" to
9363.4   "/usr/share/qgis/i18n/qgis_ja.qm": No space left on device.
```

2.  Somehow the faulty images where the build did not succeed still get uploaded to docker hub and replace the previously working images. 

e.g. checking the build exit value shows that the build did not succeed
```
~$ docker exec -it qgis28 sh -c "cd /QGIS && cat build_exit_value"
FAILED
```

### Steps to reproduce the issue

1. `docker pull qgis/qgis:release-3_28`
2. `docker run -d --name qgis28 -e DISPLAY=:99 qgis/qgis:release-3_28`
3. `docker start qgis28`
4. `docker exec -it qgis28 sh -c "qgis_testrunner.sh"`
```
~$ docker exec -it qgis28 sh -c "qgis_testrunner.sh"
ERROR: no output from the test runner! (exit code: 0)
```

### Versions

release-3_28, release-3_30

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Fixed by https://github.com/qgis/QGIS/commit/26a85ec69601559813cad337627e0e4bb55e194c
