### ISSUE TITLE
Popup appears hidden behind QGIS

### ISSUE THREAD

**Issue by dlejay** [qgis/QGIS#54332]
### What is the bug or the crash?

After selecting a target for a file, the popup disappears behind QGIS.

### Steps to reproduce the issue

1. Open the “Save vector features to file” popup.
2. In “Saved features” click “...” , then “Save to File...“
3. Select your favourite GeoPackage
4. The popup disappears in the background and QGIS has focus.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.9-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.4
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.42.0
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.3
OS version | macOS 13.4
  |   |   |  
Active Python plugins
QuickOSM | 2.2.3
profiletool | 4.2.6
processing_saga_nextgen | 0.0.7
Serval | 3.10.5
valuetool | 3.0.17
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.28.9-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.10
Python version
3.11.4
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.42.0
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.3
OS version
macOS 13.4

Active Python plugins
QuickOSM
2.2.3
profiletool
4.2.6
processing_saga_nextgen
0.0.7
Serval
3.10.5
valuetool
3.0.17
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This is a widespread bug. In many cases the popup window gets placed behind the QGIS window.

**Comment by agiudiceandrea** [comment]
Hi @dlejay, this issue my be specific to macOS an the official QGIS distribution for macOS. Please try if the issue does occur using QGIS from Conda or MacPorts as suggested in your other bug reports.

**Comment by dlejay** [comment]
I tried with the Macports version. Same issue.

**Comment by agiudiceandrea** [comment]
@dlejay, does the issue occurs using QGIS from both MacPorts and qgis.org?

**Comment by dlejay** [comment]
@agiudiceandrea Yes, it occurs for both.

And it occurs for many different popups. I guess the bug should be the same in every case, so I documented only one reproducible case.

**Comment by kom177** [comment]
This very annoying bug is still persist in latest releases of QGIS-LTR (Bratislava 3.40.5) and latest macOS Sequoia.
But not for _every_ 'file saving' dialog. For example, vector layer "Export/Save as..." tool works normally (doesn't hide).
It looks like that it is the bug feature for specific types of dialog windows (as a suggestion: those that have temp file alternative).

Please, reopen.
