### ISSUE TITLE
Endless loop if profile is drawn outside layer extent

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#54349]
### What is the bug or the crash?

With 1 layer
![image](https://github.com/qgis/QGIS/assets/39594821/44b5af18-270c-4f4f-92ac-465cce8c2498)

With 2 layers
![image](https://github.com/qgis/QGIS/assets/39594821/0dbb259c-c39f-46df-a451-2ddc491f7039)

If both layers are downloaded first and added to QGIS using local files, no issue.
Only happens with distant layers

### Steps to reproduce the issue

1. Load both layers 
   - https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/IQ/LHD_FXX_0572_6280_PTS_C_LAMB93_IGN69.copc.laz
   - https://storage.sbg.cloud.ovh.net/v1/AUTH_63234f509d6048bca3c9fd7928720ca1/ppk-lidar/IQ/LHD_FXX_0573_6280_PTS_C_LAMB93_IGN69.copc.laz
2. Open profile tool
3. Draw profile
4. See endless loading
5. Remove one layer
6. Draw profile
7. Success

Bonus:
1. Download both layers
2. Added them
3. Draw profile
4. Success

### Versions

Version de QGIS
3.33.0-Master
Révision du code
1778cbbb0e

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pblottiere** [comment]
I can reproduce the issue, I'm taking a look.

**Comment by nicogodet** [comment]
Reopening as a regression
