### ISSUE TITLE
IDWInterpolation algorithm crashing the program and incorrect output

### ISSUE THREAD

**Issue by cucumber-turtle** [qgis/QGIS#54345]
### What is the bug or the crash?

I am running a python command to do IDWInterpolation using my database as an input. I have tried the same command in the QGIS Python console, and in my own stand-alone program. Both end up crashing when running the command, and a tif file is outputted that is 1kb big and if inserted into QGIS it says it's not recognised or may be corrupt. My expected file size is around ~10,000kb.

Linking this since I also put my code and question on stack exchange: https://gis.stackexchange.com/questions/465765/idw-processing-not-running-as-expected-in-standalone-script

### Steps to reproduce the issue

1. Import processing
2. Specify the IDWInterpolation parameters. I used a pixel size of 0.0009 and an extent covering approximately 500km ('174.547209636,175.536797982,-41.691839082,-40.745909046 [EPSG:4326]').
3. I used a postgis database as a source, so if possible do that for a faithful replication of the issue.
4. Run the algorithm

### Versions

3.32.0-lima

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The issue occurred in the QGIS software interface, and using the PyQGIS API outside QGIS. When trying processing with a different algorithm, it worked as expected. It looked to me like it was just this specific algorithm crashing.

**Comment by agiudiceandrea** [comment]
Thanks for reporting. Could you provide the data which makes the algorithm crash?

**Comment by cucumber-turtle** [comment]
> Thanks for reporting. Could you provide the data which makes the algorithm crash?

Hi, unfortunately I can't share the data because it's somewhat sensitive. I'll see if I can compile some shareable data that shows the same behaviour.
