### ISSUE TITLE
Cant build QGIS In Fedora 38

### ISSUE THREAD

**Issue by parisa-hr** [qgis/QGIS#54348]
### What is the bug or the crash?

It is a problem with Sip although I installed whatever you mentioned in [INSTALL.md](https://github.com/qgis/QGIS/blob/master/INSTALL.md#311-on-fedora-linux)
But I can't build it.
I should mention that I use make -j7 or -j4 to build it faster, but as I Run the make command In 70 or 71, it stops.

I don't know what I should do there is no sip-devel in a fedora and I have **installed** `python3-sip-devel`.

### Steps to reproduce the issue

sip-build: /home/parisa/Projects/QGIS/build/python/core/core.sip: line 94: column 9: 'QtXml/QtXmlmod.sip' could not be found
/home/parisa/Projects/QGIS/build/python/core/core.sip: line 95: column 9: 'QtNetwork/QtNetworkmod.sip' could not be found
/home/parisa/Projects/QGIS/build/python/core/core.sip: line 96: column 9: 'QtSql/QtSqlmod.sip' could not be found
/home/parisa/Projects/QGIS/build/python/core/core.sip: line 98: column 9: 'QtPrintSupport/QtPrintSupportmod.sip' could not be found
/home/parisa/Projects/QGIS/build/python/core/core.sip: line 99: column 9: 'QtWidgets/QtWidgetsmod.sip' could not be found
/home/parisa/Projects/QGIS/build/python/core/core.sip: line 100: column 9: 'QtPositioning/QtPositioningmod.sip' could not be found

### Versions

Qt 5.15.2
QGIS 3.33 master branch.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

please help me.

**Comment by ptitjano** [comment]
These sip files are provided by the `python3-qt5-devel` package.

**Comment by parisa-hr** [comment]
@ptitjano  Thanks for your response.I have already install it.

![Screenshot from 2023-08-26 08-24-56](https://github.com/qgis/QGIS/assets/44742050/1a30ef26-b794-4985-b449-9990d0f0a333)


![Screenshot from 2023-08-26 08-26-50](https://github.com/qgis/QGIS/assets/44742050/51371e5d-8ffb-4fb5-a9f9-6d1a4a0a4f23)




![Screenshot from 2023-08-26 08-26-14](https://github.com/qgis/QGIS/assets/44742050/7d373c7d-5974-48e0-9114-67e2b4283eea)

**Comment by manisandro** [comment]
This is likely because of [1] (see also [2]) which also causes the cmake python module to return

    Python_SITEARCH = /usr/local/lib64/pythonX.Y/site-packages

instead of 

    Python_SITEARCH = /usr/lib64/pythonX.Y/site-packages

A workaround is to add

    EXECUTE_PROCESS(COMMAND ${Python_EXECUTABLE} -c "import sysconfig;print(sysconfig.get_path(\"platlib\", \"rpm_prefix\"), end=\"\")" OUTPUT_VARIABLE Python_SITEARCH)


after

    find_package(Python ...)

in the toplevel `CMakeLists.txt`.  Not sure yet what is the best true way to fix this.

[1] https://github.com/fedora-python/cpython/commit/d8d9d756232c5d1306fc70ef0aefb32a8391a080#diff-d593bd299ba58e440ba411ffa0640ccd9d20d518b0cf2644ed4bdb75a82a3e70
[2] https://discuss.python.org/t/pep-668-marking-python-base-environments-as-externally-managed/10302/64

**Comment by parisa-hr** [comment]
@manisandro Thanks for your response , I apologize, but  I didn't understand. I follow [INSTALL.md](https://github.com/qgis/QGIS/blob/master/INSTALL.md#311-on-fedora-linux) and my fedora was fresh install,why I cant build project?


![Screenshot from 2023-08-26 15-24-30](https://github.com/qgis/QGIS/assets/44742050/5ffbe9ca-f626-4fe2-909a-4420b9b3b7f3)

on the other hand I can see sip file in `/usr/lib64/python3.11/site-packages/PyQt5/bindings` 

![Screenshot from 2023-08-26 15-32-44](https://github.com/qgis/QGIS/assets/44742050/191b8a06-029e-406d-8c3a-7f7e3ba4362f)

![Screenshot from 2023-08-26 15-32-57](https://github.com/qgis/QGIS/assets/44742050/79abcdb0-b1d3-469b-b2c0-f8aad1d61636)


For example I can see there is `QtSqlmod.sip` in `/usr/lib64/python3.11/site-packages/PyQt5/bindings/QtSql/QtSqlmod.sip` but it get error!
I didn't understand what should I do to fix it.
