### ISSUE TITLE
qgis_process doesn't always assume the default value of an algorithm argument

### ISSUE THREAD

**Issue by florisvdh** [qgis/QGIS#54370]
### What is the bug or the crash?

At least one algorithm exists (see below) – maybe many more – where an argument that has a default value still needs to be passed explicitly for it to work, otherwise it errors with _'The following mandatory parameters were not specified: ....'_.

There are other algorithms where not passing default arguments just works (e.g. not passing the `DISTANCE` argument of `native:buffer`). Hence foregoing error is inconsistent behaviour.

### Steps to reproduce the issue

```bash
$ wget -q https://github.com/r-spatial/qgisprocess/raw/main/inst/longlake/longlake.tif
$ 
$ gdalinfo longlake.tif -nomd | tail -12
Band 1 Block=553x4 Type=Byte, ColorInterp=Red
  Min=25.000 Max=255.000 
  Minimum=25.000, Maximum=255.000, Mean=186.550, StdDev=25.493
  NoData Value=255
Band 2 Block=553x4 Type=Byte, ColorInterp=Green
  Min=74.000 Max=255.000 
  Minimum=74.000, Maximum=255.000, Mean=213.882, StdDev=13.690
  NoData Value=255
Band 3 Block=553x4 Type=Byte, ColorInterp=Blue
  Min=46.000 Max=255.000 
  Minimum=46.000, Maximum=255.000, Mean=188.777, StdDev=29.440
  NoData Value=255
$ 
$ myJSON=$(</dev/stdin)
{
  "inputs": {
    "INPUT": "longlake.tif",
    "BAND": 1
  }
}
$ 
$ echo "$myJSON" | qgis_process run native:rasterlayerstatistics - | tail -10
  "results": {
    "MAX": 253.0,
    "MEAN": 186.31545289003526,
    "MIN": 25.0,
    "RANGE": 228.0,
    "STD_DEV": 25.51306231112349,
    "SUM": 47168179.0,
    "SUM_OF_SQUARES": 164787284.61674687
  }
}$ 
$ 
$ myJSON=$(</dev/stdin)
{
  "inputs": {
    "INPUT": "longlake.tif"
  }
}
$ 
$ echo "$myJSON" | qgis_process run native:rasterlayerstatistics - | tail -10
ERROR: The following mandatory parameters were not specified

	BAND:	Band number
$ 
$ qgis_process help native:rasterlayerstatistics
Raster layer statistics (native:rasterlayerstatistics)

----------------
Description
----------------
This algorithm computes basic statistics from the values in a given band of the raster layer.

----------------
Arguments
----------------

INPUT: Input layer
	Argument type:	raster
	Acceptable values:
		- Path to a raster layer
BAND: Band number
	Default value:	1
	Argument type:	band
	Acceptable values:
		- Integer value representing an existing raster band number
OUTPUT_HTML_FILE: Statistics (optional)
	Argument type:	fileDestination
	Acceptable values:
		- Path for new file

----------------
Outputs
----------------

OUTPUT_HTML_FILE: <outputHtml>
	Statistics
MIN: <outputNumber>
	Minimum value
MAX: <outputNumber>
	Maximum value
RANGE: <outputNumber>
	Range
SUM: <outputNumber>
	Sum
MEAN: <outputNumber>
	Mean value
STD_DEV: <outputNumber>
	Standard deviation
SUM_OF_SQUARES: <outputNumber>
	Sum of the squares
```

### Versions

```
$ qgis_process --version
QGIS 3.32.2-Lima 'Lima' (c0b88339649)
QGIS code revision c0b88339649
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.6.4
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.2
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
A default value is a different concept vs a optional parameter in processing. At least within the GUI the default value just represents the initial value shown in the corresponding widget.

I can see that this doesn't necessarily translate well to qgis process, since it means that a lot of seemingly "default" parameters must be specified on the command line, even when their default value is sufficient.

We could potentially treat things different in qgis process and consider any parameter which isn't explicitly specified as having its default value. We'd just then need to make sure there's some way to un-specify an optional parameter which has a non-null default value....

**Comment by florisvdh** [comment]
> We'd just then need to make sure there's some way to un-specify an optional parameter which has a non-null default value

Yes, assuming the default value should not happen for the optional parameters I think.

Current problem for a user is that the distinction isn't clear from the algorithm help - so that might be another way to solve:

`native:buffer` shows:

```
DISTANCE: Distance
	Default value:	10
	Argument type:	distance
	Acceptable values:
		- A numeric value
		- field:FIELD_NAME to use a data defined value taken from the FIELD_NAME field
		- expression:SOME EXPRESSION to use a data defined value calculated using a custom QGIS expression
```

and it will work without providing `DISTANCE`.

`native:rasterlayerstatistics` shows:

```
BAND: Band number
	Default value:	1
	Argument type:	band
	Acceptable values:
		- Integer value representing an existing raster band number
```

and you need to pass it explicitly.

Both `DISTANCE` and `BAND` are required arguments (non-optional), both have a default value, but only `BAND` must be passed explicitly. IIUC it would be possible to make it unnecessary to pass arguments that have default values, while limiting such behaviour to the non-optional arguments.

**Comment by agiudiceandrea** [comment]
@nyalldawson, something similar was addressed in the past: see https://github.com/qgis/QGIS/issues/37692 and https://github.com/qgis/QGIS/pull/37694.

**Comment by nyalldawson** [comment]
@florisvdh I think we're actually doing everything OK here, it's just a problem isolated to the raster band parameter type alone.

What other algorithms have you identified this as happening with?

**Comment by florisvdh** [comment]
> I think we're actually doing everything OK here, it's just a problem isolated to the raster band parameter type alone

Great :rocket:

> What other algorithms have you identified this as happening with?

@nyalldawson I didn't, I just assumed there may be more. I see the discussion going on about this in PR #54414.

**Comment by florisvdh** [comment]
Confirmed this now works great. Thanks a lot!!!

```bash
$ echo "$myJSON" | ~/git_repositories2/QGIS/build-4e83c82a/output/bin/qgis_process run native:rasterlayerstatistics - | tail -10
  "results": {
    "MAX": 253.0,
    "MEAN": 186.31545289003526,
    "MIN": 25.0,
    "RANGE": 228.0,
    "STD_DEV": 25.51306231112349,
    "SUM": 47168179.0,
    "SUM_OF_SQUARES": 164787284.61674687
  }
}
```
