### ISSUE TITLE
No features found at this position

### ISSUE THREAD

**Issue by informaticahf** [qgis/QGIS#54373]
### What is the bug or the crash?

Hello

We made a migration from postgres 9 to postgre14. 
we are using qgis 3.32 do manipulate
![OLD_CONNECTION](https://github.com/qgis/QGIS/assets/143203811/00697546-48a1-4a90-b231-6a051e51d60b)
![NEW_CONNECTION](https://github.com/qgis/QGIS/assets/143203811/f7568764-8fc3-4e2e-a963-c92f22d5d76e)

When we use the qgis with the connection to the old database, we can select the features and see the attributes of the selected feature
When we change the connection to the new database, we can see the features on the "map" but when we try to select them, it says "No features found at this position"

I send 2 screenshoots  where u can see visually  the situation

### Steps to reproduce the issue

select a feature on the selected layer

### Versions

3.32.2 lima

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
What's different between the databases?  Any output in the log?  Provide steps to reproduce that make it possible to reproduce the problem anywhere.

**Comment by informaticahf** [comment]
Good morning

OLD CONNECTION -
PostGres +PostGis

"PostgreSQL 9.1.1, compiled by Visual C++ build 1500, 32-bit"
PostGis version

"POSTGIS="1.5.5" GEOS="3.3.5-CAPI-1.7.5" PROJ="Rel. 4.6.1, 21 August 2008" LIBXML="2.7.8" USE_STATS (procs from 1.5 r7360 need upgrade)"


NEW CONNECTION
"PostgreSQL 14.8 (Ubuntu 14.8-0ubuntu0.22.04.1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 11.3.0-1ubuntu1~22.04.1) 11.3.0, 64-bit"

"POSTGIS=""3.2.0 c3e3cc0"" [EXTENSION] PGSQL=""140"" GEOS=""3.10.2-CAPI-1.16.0"" PROJ=""8.2.1"" LIBXML=""2.9.12"" LIBJSON=""0.15"" LIBPROTOBUF=""1.3.3"" WAGYU=""0.5.0 (Internal)"""


I can send u a backup from the database so that u can test ---

thanks
Pedro

**Comment by informaticahf** [comment]
Hello...

Weird solution, with qgis 2.2 (VALMIERA) everything works on the connection to the new database.
We can create, select and display the information of the point
