### ISSUE TITLE
setDataSource() - What is the format of a "data source"? And what is a "base name"?

### ISSUE THREAD

**Issue by velle** [qgis/QGIS#54381]
Regarding the `setDataSource` method on `QgsVectorLayer`. 

- Link to C++ API documentation: https://api.qgis.org/api/3.0/classQgsVectorLayer.html#af984f244d3a6d7598c41baf71eb461bb
- Link to Python API documentation: https://qgis.org/pyqgis/3.0/core/Vector/QgsVectorLayer.html#qgis.core.QgsVectorLayer.setDataSource

The documentation on the arguments is nothing but tautologies :)

![image](https://github.com/qgis/QGIS/assets/4488298/1d6bed3b-d2dc-442b-a44b-225512372365)

I tried googling in several ways, and I did find stuff, but not what I was looking for, and I still have not solved my problem.

### What is a _data source_?

A path? A URL? A URI? Some other kind of descriptor or reference? 

I figured out by trial an error that a string like the following does work. 

`pagingEnabled='false' preferCoordinatesForWfsT11='false' restrictToRequestBBOX='1' srsname='EPSG:25832' typename='favrskov:gadelysskab' url='https://foobar.io/wfs/jdoe@foobar/baz/25832' version='1.1.0'`

In the QGIS GUI this string is called a _URI_, though I don't think thats a URI. 

![image](https://github.com/qgis/QGIS/assets/4488298/8e79b029-c3c0-46b6-bb69-7e5e1f8951f7)

It seems like a string, with `key=value` pairs, using spaces between pairs. It certainly does not stick to the format of a URI. But maybe sometimes it is simply a URI/URL?

Where is this text based data source descriptor documented? Is it a format defined by (and only used by) QGIS? 

### What is a _base name_?

Again, by trial and error, I found out that inside QGIS GUI the layer name changes to the value of `baseName`. That corresponds to calling the `setName` function. But _maybe_ the name change of the LayerTreeLayer is only a side effect, and baseName is really about something different? 

### What is a _provider string_?

I know that `WFS` is a valid provider string. Again, I found out by trial and error. But what else is a valid value? I am guessing that 

### What is the behavior if given invalid arguments?

Many qgs functions return an integer value representing the state; whether success or error. This function does not. If I supply an invalid provider string (e.g. `foobar` then the function simply returns as if everything went well, but the data source remains unchanged (correction: I was wrong, it seems to change every time, though some times into an invalid state). Is there any way of getting any status, or does the caller need to write code, that tests if the data source was actually changed? 

The fact that I don't know how its supposed to behave makes it even harder to figure out how to use it properly by trial and error. 

Sincerely

**Comment by nyalldawson** [comment]
> What is a data source?
> A path? A URL? A URI? Some other kind of descriptor or reference?

All of the above, and more :laughing: 

It depends on the underlying driver. For an ogr disk based format it's generally the file name (eg for a shapefile). For databases, remote services, etc it's usually a url + extra bits.

> Is it a format defined by (and only used by) QGIS?

Yes

> Where is this text based data source descriptor documented?

It's not documented in depth. There's some documentation starting at https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#memory-data-providertype-memory .

The best way to discover the correct format is to add the layer from the GUI, and then copy the source string and adapt.

> Again, by trial and error, I found out that inside QGIS GUI the layer name changes to the value of baseName

It's just the layer's name. The documentation could definitely be improved here!

> What is a provider string?

It's the "driver name". You can get a full list of available providers by:

    QgsProviderRegistry.instance().providerList()

> What is the behavior if given invalid arguments?

You'll get an invalid layer. Test via `layer.isValid()`. It will be True only if the connection all worked correctly. (For 4.0 this will likely be modified to raise an exception in python -- see https://github.com/qgis/qgis4.0_api/issues/84

**Comment by velle** [comment]
I looked at your commit, and it looks great; a whole lot more helpful now, thanks :)

I have a question/comment, which may be irrelevant depending on how the documentation actually appears when rendered. So let me ask the questions below first. 

I'm guessing that you write the documentation in the source code itself (src/core/qgsmaplayer.h) and then the sip.in file is rendered by some build process. 

Is the sip.in file a format for documentation? 

Is there anyway that I can see the rendered version of the updated documentation?
