### ISSUE TITLE
Add possibility to change selection color for individual layer

### ISSUE THREAD

**Issue by fmeier1995** [qgis/QGIS#54385]
### Feature description

It's possible to change the color of the selected objects in map canvas for every layer in QGIS options or project properties.

But I guess it could be nice to add this propertie on layer level, so for example I could set that selected objects in layer 1 appears in yellow, selected objects in layer 2 appears in purple and so on - it is sometimes a little bit hard to differentiate if objects of several layers are selected (for example several line layers with the same width, several polygon layers, ...).

**Comment by DelazJ** [comment]
@fmeier1995 Already fixed in https://github.com/qgis/QGIS/pull/53977? You might want to try master.

**Comment by fmeier1995** [comment]
Well, yes, I should've checked master first. Sorry!
Thanks for doing this, great work.
