### ISSUE TITLE
Scripts accessing pandas.read_excel() crashing in 3.28.9

### ISSUE THREAD

**Issue by meisterlix** [qgis/QGIS#54400]
### What is the bug or the crash?

Since upgrading from 3.22 to 3.28 python scripts run in the console that access the pandas.read_excel() function crash due to a ModuleNotFoundError: no module named 'openpyxl'. 

### Steps to reproduce the issue

- Open a script that imports pandas and calls it's read_excel() function

### Versions

3.28.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
You need to install the python library "python3-openpyxl".

Which OS ? How did you install QGIS ?

**Comment by meisterlix** [comment]
Windows 10 Pro 22H2 (19045.3324)
I updated from QGIS 3.22 on an enterprise managed PC via the Matrix42 Unified Endpoint Management System.

As this is a managed system I cannot install openpyxl by itself, but as far as I can tell openpyxl was shipped with QGIS 3.22.
Is it no longer shipped with QGIS' Python?

**Comment by nicogodet** [comment]
Them you should contact your IT department.
openpyxl is not an essential dependency for QGIS so not ship by default I guess.

As it concerns windows packaging, you should check https://trac.osgeo.org/osgeo4w/report.

Closing as not a QGIS issue but packaging one.

**Comment by meisterlix** [comment]
alright then. So I reckon I should check if openpyxl is no longer shipped in the currently used osgeo42 release?

Thanks very much!
