### ISSUE TITLE
Polyline geometry not updating after extending

### ISSUE THREAD

**Issue by Coastal0** [qgis/QGIS#54416]
### What is the bug or the crash?

Following extension of a polyline, the values returned by `x_min($geometry),y_min($geometry),x_max($geometry),y_max($geometry)` do not appear to update to reflect the extended line values. 

'$x_at(0), $x_at(-1), $y_at(0), $y_at(-1)'

e.g. for a N-S oriented polyline which has been extended by 25 m on either side, the `min_y` and `max_y` should match the `y_end` and `y_start`  (respectively), but `min_y` and `max_y` are incorrect.

y_start	y_end	y_min	y_max
7242825	7242675	7242700	7242800

### Steps to reproduce the issue

1. Create a polyline
2. Extend the polyline using the "Extend lines" process by some amount
3. Fill attribute table with $y_at(0) and y_max($geometry)
4. Note difference in two results

### Versions

QGIS version
3.32.2-Lima
QGIS code revision
c0b8833964
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
DataPlotly
4.0.3
deactivate_active_labels
0.5
geoscience
1.11
Group_and_Sort_Layers
1.2
MemoryLayerSaver
5.0.1
processing_saga_nextgen
0.0.7
profiletool
4.2.6
ProjectPackager
0.7.2
quick_map_services
0.19.33
slyr
6.4.6
SRTM-Downloader
3.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Thanks for reporting. It seems to me the issue is due to the `QgsLineString::extend` function (used by the `QgsGeometry::extendLine` function used in turn by the "Extend lines" processing algorithm) which forgets to update the bounding box of the line geometry after it was extended.
