### ISSUE TITLE
Qgis deja de funcionar al seleccionar la opcion GDAL

### ISSUE THREAD

**Issue by cdv13** [qgis/QGIS#54427]
### What is the bug or the crash?

Crash ID: [fe65144a08acecbb8e2eb713d507a1c37caf542a](https://github.com/qgis/QGIS/search?q=fe65144a08acecbb8e2eb713d507a1c37caf542a&type=Issues)

Stack Trace

GDALDriverManager::ReorderDrivers :
QgsMapToolLabel::isPinned :
QgsMapToolLabel::isPinned :
QgsRuleBasedRendererModel::finishedAddingRules :
QgsRuleBasedRendererModel::finishedAddingRules :
QgsRuleBasedRendererModel::finishedAddingRules :
QMetaObject::activate :
QStackedWidget::qt_static_metacall :
QMetaObject::activate :
QStackedLayout::setCurrentIndex :
QMetaObject::activate :
QListWidgetItem::`default constructor closure' :
QMetaObject::activate :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsProcessingProvider::versionInfo :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsProcessingProvider::versionInfo :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgsMapToolLabel::isPinned :
QgsMapToolLabel::isPinned :
QgsMapToolLabel::isPinned :
QgsMapToolLabel::isPinned :
QgsMapToolLabel::isPinned :
QMetaObject::activate :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsProcessingProvider::versionInfo :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsProcessingProvider::versionInfo :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
QgsMapToolLabel::isPinned :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.16.10-Hannover
QGIS code revision: a25c2d8c2e
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.4.0dev
Running against GDAL: 3.4.0dev

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.1.7601

### Steps to reproduce the issue

1. Al ir a la sección Configuración
2. Seleccionar "Opciones"
3. En la ventana emergente, ir a la pestaña de GDAL
4. Qgis deja de funcionar

### Versions

Versión de QGIS
3.16.10-Hannover
Revisión del código de QGIS
a25c2d8c2e
Compilado contra Qt
5.11.2
Ejecutándose contra Qt
5.11.2
Compilado contra GDAL/OGR
3.4.0dev
Ejecutándose contra GDAL/OGR
3.4.0dev
Compilado contra GEOS
3.8.1-CAPI-1.13.3
Ejecutándose contra GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
Versión del cliente PostgreSQL
11.5
Versión de SpatiaLite
4.3.0
Versión de QWT
6.1.3
Versión de QScintilla2
2.10.8
Compilado contra PROJ
8.2.0
Ejecutándose contra PROJ
Rel. 8.2.0, November 1st, 2021
Versión del SO
Windows 7 SP 1 (6.1)
Esta copia de QGIS escribe salida de depurado.
Active python plugins
ee_plugin; 
latlontools; 
OSMDownloader; 
qgsAzimuth; 
quick_map_services; 
SemiAutomaticClassificationPlugin; 
SRTM-Downloader; 
db_manager; 
MetaSearch; 
processing

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
> Versión de QGIS
3.16.10-Hannover

@cdv13 3.16 is too old and no longer maintained (not a supported QGIS version, unlike the box you checked). Please update to a more recent version and check whether the issue still occurs.

PS: better file the issue report in English, much easier for the contributors here. You can use an online translator tool if necessary.

**Comment by nicogodet** [comment]
Try with a new qgis user profile too (I can see some plugins not from core in your report).

**Comment by DelazJ** [comment]
@cdv13 IIRC the limitation on versions you can install on Windows 7 has been unlocked so it should be possible to install recent versions. What I am not sure of is whether you might need to go the osgeo4w install process way or if it is also available in the standalone installer also. But I'd bet it's available in both.
