### ISSUE TITLE
"Apply default value on update" on navigating attribute table

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#54446]
### What is the bug or the crash?

Disclaimer: No data corruption.

When I have a default value expression that ***depends on another field*** value, the form inserts the default value even when I don't change something in the form (not even in edit mode) The default value is not stored after. But it's a pain because it's (a) confusing for the user and (b) in case the expressions trigger some calculations it can slow down the performance.

![image](https://github.com/qgis/QGIS/assets/28384354/ecd8a54b-979e-4d80-9b74-d39e7a7e6561)

It's only in the attribute table form view and only on expressions depending on other fields. This here would not mind (here we don't use `"name" `but just a string instead):
![image](https://github.com/qgis/QGIS/assets/28384354/e3308da5-430e-4947-bda7-0c7c7f89f777)

This might be related to #53678 and #54421

### Steps to reproduce the issue

I have the config like above. 

My table looks like this:
![image](https://github.com/qgis/QGIS/assets/28384354/a054ac66-d672-4130-8b27-b4b843abe91d)

When I navigate in the attribute table form view I see the values are filled up in 'operator_anmeldung' when I just navigate from one to another entry: 
![image](https://github.com/qgis/QGIS/assets/28384354/6c0fe44d-facc-4227-a963-9d51828978c6)
![image](https://github.com/qgis/QGIS/assets/28384354/78039a64-0b14-4927-84f9-b58d66a2e60f)
![image](https://github.com/qgis/QGIS/assets/28384354/bbd4deee-4c83-4544-b7fe-05c010d9530c)

When I check the data again in the table view, I can see that it did not change my data:
![image](https://github.com/qgis/QGIS/assets/28384354/5f816008-a889-4564-942d-efb7cc69fc0f)

### Versions

QGIS version | 3.28.10-Firenze | QGIS code revision | e2edb9c468b
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
Active Python plugins
ordered_relation_editor | 0.2.7
quick_map_services | 0.19.33
linking_relation_editor | v1.2.0
qfieldsync | v4.5.0
QgisModelBaker | v7.5.2
grassprovider | 2.12.99
sagaprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS version
3.28.10-Firenze
QGIS code revision
[e2edb9c468b](https://github.com/qgis/QGIS/commit/e2edb9c468b)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by domi4484** [comment]
I think when navigating trough the attribute table the default values should not be evaluated even in edit mode.

They should be evaluated only:
- For a new to be created feature.
- When a form value is edited (but only if "Apply default values on update" is checked)

But maybe there are use cases I don't see. For example if someone "misuses" the default values to display updated remote live values. In this case the "Apply default values on update" checkbox could be changed to an enum with those possibilities:
- Apply default values on create new feature
- Apply default values on update
- Apply default values on show (Implies apply on update and has performance drawback in attribute table!)

**Comment by signedav** [comment]
Thanks for your feedback.

I totally agree on you. I can imagine that we would only have (more) problems, when data is updated with changed remote values just on showing them. So I suggest to fix this by doing the following: Don't evaluate them when no value is edited.

And your suggestion with the "Apply default values on show" we could consider to create a feature request with (in case someone is interested in it - what I'm not sure about)...

**Comment by signedav** [comment]
Note: This issue here concerns the situation when the expression ***depends on another field***. When it's not depending on another field, there is an opposite issue #53722

**Comment by jusabatier** [comment]
> But maybe there are use cases I don't see. For example if someone "misuses" the default values to display updated remote live values. In this case the "Apply default values on update" checkbox could be changed to an enum with those possibilities:
> 
> * Apply default values on create new feature
> * Apply default values on update
> * Apply default values on show (Implies apply on update and has performance drawback in attribute table!)

I use MerginMap with a survey that allow multiple photos. 

They are stored in a related table as explained here : https://merginmaps.com/docs/layer/attach-multiple-photos-to-features/

I tried to add a field in the survey to retrieve the list of photo's filenames separated with '|', I defined the default value as : 

```
with_variable(
    'unique_id',
    "UNIQUE_ID",
    aggregate( 
        'photos',
        'concatenate',
        photo, 
        filter:= regexp_match("ponctuel-pk", @unique_id), 
        concatenator:='|'
    )
)
```

And the problem I have is that when a user add a photo without modify another field value, the field value isn't updated.

Maybe it's a usecase that need to force calculate before save ?
