### ISSUE TITLE
Minor inconvenience, when setting a two digit number of classes for a graduated symbology

### ISSUE THREAD

**Issue by maxwesemeyer** [qgis/QGIS#54443]
### What is the bug or the crash?

This is something in between a bug and a feature request. When working with large layers and setting the number of classes to a two digit number for a graduated symbolization, Qgis is really slow (e.g. classes to 10). It seems like QGis first calculates the classes for 1 and then realizes that another digit is coming and has to do it for 10 again. Maybe a very small waiting time can fix this. 

### Steps to reproduce the issue

1. Load a vector layer with a lot of features (>100 000).
2. Go to symbology, then set graduated and chose any numeric column 
3. set the number of classes to any two digit number
4. See that it calculates the classes before the second digit appears

### Versions

QGIS 3.22

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/49333 ?
