### ISSUE TITLE
QGIS crash when adding mesh dataset groups as input in the design modeler

### ISSUE THREAD

**Issue by Amalvir** [qgis/QGIS#54442]
### What is the bug or the crash?

In the design modeler, just adding mesh dataset groups as input causes the crash of QGIS with the following report. The crash is only cause by this input, not the other. I tried with a Windows computer QGIS 3.32.2, an Ubuntu Xorg QGIS 3.32.2 and 3.28.10 clean installation, and it was all the same. 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000042ec (most recent call first):
  File "C:\OSGeo4W/apps/qgis/./python/plugins\processing\modeler\ModelerDialog.py", line 297 in addInput
    dlg = QgsProcessingParameterDefinitionDialog(type=paramType,
```

**Stack Trace**

```

QByteArray::QByteArray :
QgsProcessingParameterFieldMapping::parentLayerParameterName :
QgsProcessingMeshDatasetGroupsParameterDefinitionWidget::QgsProcessingMeshDatasetGroupsParameterDefinitionWidget :
QgsProcessingMeshDatasetGroupsWidgetWrapper::createParameterDefinitionWidget :
QgsProcessingGuiRegistry::createParameterDefinitionWidget :
QgsProcessingParameterDefinitionWidget::QgsProcessingParameterDefinitionWidget :
QgsProcessingParameterDefinitionDialog::QgsProcessingParameterDefinitionDialog :
PyInit__gui :
PyType_GenericNew :
PyObject_MakeTpCall :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QgsModelerToolboxModel::flags :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.2-Lima
QGIS code revision: c0b8833964
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Open the design modeler
2. Go to 'inputs'
3. Double click or drag and drop 'Mesh dataset groups'
4. Wait 3 sec for the crash 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.32.2-Lima | Révision du code | c0b8833964
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.1
Version de Proj | 9.2.1
Version de la base de données du registre EPSG | v10.088 (2023-05-13)
Version de GEOS | 3.12.0-CAPI-1.18.0
Version de SQLite | 3.41.1
Version de PDAL | 2.5.5
Version du client PostgreSQL | 15.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
AnotherDXF2Shape | 1.2.9
autoSaver | 2.6
french_locator_filter | 1.0.4
GroupStats | 2.2.7
profiletool | 4.2.6
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Version de QGIS
3.32.2-Lima
Révision du code
[c0b8833964](https://github.com/qgis/QGIS/commit/c0b8833964)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.1
Version de Proj
9.2.1
Version de la base de données du registre EPSG
v10.088 (2023-05-13)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
15.2
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
AnotherDXF2Shape
1.2.9
autoSaver
2.6
french_locator_filter
1.0.4
GroupStats
2.2.7
profiletool
4.2.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@Amalvir , thanks for reporting this, it has been fixed (https://github.com/qgis/QGIS/pull/55047).
