### ISSUE TITLE
awful

### ISSUE THREAD

**Issue by goliath20** [qgis/QGIS#54456]
### What is the bug or the crash?

This is the worst program I have ever used. I've used hundreds of software programs in my 30 years and this is the worst. Bad install, bad documentation, takes SO long to install and uninstall, like jesus, how incompetent can you be? If I'm using an installer then it should be effort free in 2023. 

### Steps to reproduce the issue

install, uninstall

### Versions

win 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Flagged as abuse and @goliath20 has been blocked
