### ISSUE TITLE
Timestamps in Processing History window are all the current time

### ISSUE THREAD

**Issue by atlight** [qgis/QGIS#54454]
### What is the bug or the crash?

All timestamps in the Processing History window reflect the current system time, not the actual time the tool was run.

Curiously, the folder headings are correct:
![image](https://github.com/qgis/QGIS/assets/653361/182cfbdd-cc40-4fb9-b425-fc9bfec5a68e)

### Steps to reproduce the issue

Processing menu > History, view the items in the list.

### Versions

QGIS version
3.32.2-Lima
QGIS code revision
c0b8833964
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
QuickOSM
2.2.3
QuickWKT
3.1
Serval
3.10.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

As a side note, I'd love it if the box could provide some indication that double-clicking on the tool item actually does something. This actually took me a long time to figure out. I assumed the only way to re-run the tool, short of manually recreating the listed inputs, was to copy-paste the provided Python code!

**Comment by nicogodet** [comment]
> As a side note, I'd love it if the box could provide some indication that double-clicking on the tool item actually does something.

![image](https://github.com/qgis/QGIS/assets/39594821/51275876-e02c-4802-b82a-d6aa169f6ed6)

This is already the case :)

**Comment by atlight** [comment]
> This is already the case :)

Hah, true! I don't exactly blame myself for not noticing this though; it's written in a code comment even though it has no connection to the code, and it's in a poorly contrasting colour (pale orange on white). Anyway, that's not a discussion that needs continuing on this issue.

Thanks @nyalldawson for looking into this!
