### ISSUE TITLE
native:rectanglesovalsdiamonds - not working with ovals

### ISSUE THREAD

**Issue by BeritMohrGFA** [qgis/QGIS#54469]
### What is the bug or the crash?

Good Morning the algorithm does not work on the Oval Shape:
It does work when selecting Rectangle and Diamond but not with the 'Shape = 2'
```
processing.run("native:rectanglesovalsdiamonds", {'INPUT':QgsProcessingFeatureSourceDefinition('XX', selectedFeaturesOnly=True, featureLimit=-1, geometryCheck=QgsFeatureRequest.GeometryAbortOnInvalid),'SHAPE':2,'WIDTH':400,'HEIGHT':600,'ROTATION':30,'SEGMENTS':1,'OUTPUT':'TEMPORARY_OUTPUT'})
`processing.run("native:rectanglesovalsdiamonds", {'INPUT':QgsProcessingFeatureSourceDefinition('XX', selectedFeaturesOnly=True, featureLimit=-1, geometryCheck=QgsFeatureRequest.GeometryAbortOnInvalid),'SHAPE':1,'WIDTH':400,'HEIGHT':600,'ROTATION':30,'SEGMENTS':1,'OUTPUT':'TEMPORARY_OUTPUT'})`
```

I am using the QGIS 3.32.0 version

### Steps to reproduce the issue

Select 'Rectangles, ovals, diamonds, 
Add the AoI and select 'Oval' as your shape. 

### Versions

3.32.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The 'feature' is somehow created but not showing anywhere.

**Comment by agiudiceandrea** [comment]
@BeritMohrGFA, thanks for reporting. The issue you are experiencing is due to the fact that you have specified the value `1` as the number of line segments (parameter `SEGMENTS`) to use for creating the polygonal oval shape: this value is obviously too small to create a polygonal oval shape. Please try with a larger value (e.g. > 20 ).
