### ISSUE TITLE
Speed up Atlas navigating within layout ui and layout exports when using 'Follow map theme'

### ISSUE THREAD

**Issue by patc-wwind** [qgis/QGIS#54461]
### Feature description

Using 'Follow map theme' slows down the layout ui when moving between pages of atlas (not responding ~ 3-4 seconds after each page change) and whilst exporting atlas to pdf. It would be good to speed this up so it matches that of 'Lock layers'. Using 'Lock layers' option switching between atlas pages has no noticeable slow down.

To compare export, legend is switched off so just looking at impact from map item itself for 21 page atlas.

- Export atlas using 'Follow map theme'    time - 4 min 59 sec
- Export atlas using locked layers (from the map theme, identical layers/styling and output)   time - 2 min 9 sec

These produce identical pdf exports

**Comment by nyalldawson** [comment]
Can you test on 3.32? It should be much improved

**Comment by patc-wwind** [comment]
Yeah both much improved for export

- Export atlas using 'Follow map theme' time - 1 min 28 sec
- Export atlas using locked layers (from the map theme, identical layers/styling and output) time - 59 sec

The atlas page navigation appears to have sped up significantly also, not as quick as lock layers but faster than in 3.28.10

Cheers
