### ISSUE TITLE
Shape export with random flip normals

### ISSUE THREAD

**Issue by snickerweb** [qgis/QGIS#54488]
### What is the bug or the crash?

When I export a SHAPE file and import in Blender GIS, the normals is random flipped.

### Steps to reproduce the issue

1. Import .gml
2. Export .shp
3. Install Blender 3.6.1 (newest)
4. Install plugin Blender GIS in edit/preferences
5. click in Blender GIS/import/Shape
6. click on face orientation in the viewport settings
[LoD2_Schwalbenweg_fertig.zip]

attach cityGML file and export SHAPE File
(https://github.com/qgis/QGIS/files/12516916/LoD2_Schwalbenweg_fertig.zip)

screenshot from blender
![flip](https://github.com/qgis/QGIS/assets/7456455/2e93f8ff-048e-4f7b-aeb1-c4145d6d07ad)

### Versions

QGIS 3.32.2-Lima
Blender 3.6.1 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Why do you think this is a qgis issue?

**Comment by snickerweb** [comment]
I dont know. But i think is the exporter. I test it with a other CityGML file from NRW (the first is from bavaria). Is the same problem.
![flip2](https://github.com/qgis/QGIS/assets/7456455/fcaa14b0-915d-486a-a9fe-1b237e47f77f)

**Comment by nyalldawson** [comment]
It's not a qgis issue -- shapefiles have no concept of normals, so there's nothing QGIS is doing wrong here. It's either something in blender gis or something you have to manually fix.

**Comment by snickerweb** [comment]
thank you for the clarification, and the fast reaction ;)

**Comment by snickerweb** [comment]
> It's not a qgis issue -- shapefiles have no concept of normals, so there's nothing QGIS is doing wrong here. It's either something in blender gis or something you have to manually fix.

Hi. I would like to ask here again. When I load the CityGML file and set the symbolization to 2,5 I see that polygons are not visible. These are the same that are displayed in BlenderGIS as rotated normals.
![image](https://github.com/qgis/QGIS/assets/7456455/212d0239-c75e-4c16-8249-73cd99db8e39)
