### ISSUE TITLE
[Identify features] Right-click with "select by polygon" tool returns results from non-identifiable layers

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#54484]
### What is the bug or the crash?

Let's say you have a project with two layers, with features overlapping
In Project properties, data sources, layers capabilities, uncheck the "identifiable" cell of one of the layers. Apply
Enable the "Identify features" tool
Activate the "Identify feature(s)" selection  tool
Right-click in the map canvas (let's say, where you have overlapping features), the result will be the feature of the identifiable layer. 
Now select the "Select by polygon" tool and right-click: it will return features from all the layers (including the non-identifiable layer)

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/7983394/7526dfb6-b004-4981-8161-b1ee751545dd

It may not be obvious but I'm doing right-click. And the identify by radius and by freehand tools do NOT return results at all but issue already at #27079.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.33.0-Master | QGIS code revision | c6a8e94ca9
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PDAL version | 2.6.0
PostgreSQL client version | 15.3 (Debian 15.3-0+deb12u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux 12 (bookworm)
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ismailsunni** [comment]
First of all, I didn't know that we have this feature :)

I tried to replicate it, but I had a different result. When I right-click, all of the layers are shown in the context menu, but when I click one of them, including the non-identifiable one, I still only get the identifiable layer.

![Peek 2023-09-06 23-00](https://github.com/qgis/QGIS/assets/1421861/2c9fe47c-aa65-4b0c-ba80-c7c42a490395)

Am I doing the wrong, probably?

**Comment by nyalldawson** [comment]
This is not a bug -- the features from the non-identifiable layers can still show in the menu for the identify by polygon tool, but they WON'T show up in the actual identify results. (You can still use them as the boundary to identify features from other layers, so they SHOULD show up in the pop up menu)

**Comment by DelazJ** [comment]
Well I didn't retry meanwhile but Nyall, you confirm what I was saying in my last message. Closing then.
