### ISSUE TITLE
Paste feature ignores avoid overlap

### ISSUE THREAD

**Issue by uclaros** [qgis/QGIS#54492]
### What is the bug or the crash?

When pasting features on a layer with _avoid overlaps_ enabled, the geometry is no longer modified to _avoid overlaps_ but the whole geometry is pasted as is.
This is a regression.

### Steps to reproduce the issue

1. Load a polygon layer
2. Digitize two overlapping polygons
3. Select one of the two polygons and cut it (ctrl+x)
4. Enable _Avoid overlap on current layer_
5. Paste (ctrl+v)
6. No overlap avoidance is performed resulting in two overlapping polygons 

### Versions

defb622e8dd

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@uclaros , fixed in https://github.com/qgis/QGIS/pull/55046 .
