### ISSUE TITLE
Inconsistent Feature Count in Output Layer After Running "Join by Location"

### ISSUE THREAD

**Issue by datarealtor** [qgis/QGIS#54490]
### What is the bug or the crash?

When running the "Join attributes by Location" algorithm in QGIS using intersect as the geometric predicate with a polygon layer as the input/"Join to features in" layer and a line layer (buffered by 17.5 ft) as the overlay/"By comparing to" layer and the option to create temporary output layers for both joined and unjoined features, the feature count in the output layer often does not match the "joined count" displayed in the algorithm's log. This inconsistency occurs despite using a "one-to-one"  join (tested on both first matching and most overlap join type) . The issue appears to be related to the output process. In a few instances the temp joined layer seemed to increase its feature count after output. I would open the attribute table initially to check results then when I would open the same table later it would load a number of features greater than what it initially had. It appears to be either duplicating the features in the "joined" layer during or after output or recombining the features from the "unjoined" layer back into the "joined".

### Steps to reproduce the issue

Steps to Reproduce:
Run the "Join by Location" algorithm with "intersect" as the geometric predicate and "one-to-one" join type on layers with differing geometries (e.g., line and polygon).
Choose to create temporary output layers for both joined and unjoined features.
Note the feature count of the newly created "joined" layer immediately
Observe the "joined count" in the algorithm's log.
Open the attribute table for the "joined" layer
Close table and open it again
Compare the feature count in the output layer to the "joined count" and the feature count of the input layer used.

Expected Behavior:
The feature count in the output layer for "Joined" should match the "joined count" displayed in the algorithm's log and have less features than the input layer.

Actual Behavior:
The feature count in the output layer "Joined" sometimes equals or even exceeds the feature count of the input layer.
The algorithm log shows a different "joined count" compared to the actual feature count in the output layer.
The inconsistency persists even when directing the algorithm to save both outputs as separate files.
Sometimes the "joined" temp. layer would show features from the "unjoined" layer

Troubleshooting Steps Taken:
Check validity of geometries for both layers and run "fix geometries" when necessary.
Checked for the existence of a spatial index for both layers.
Ensured both layers were in the same coordinate system (2230).
Copy and pasted the content of the algorithms log after output into ChatGPT4  Advanced Data  Analytics conversation to check for errors and make suggestions
Workaround:
Rerunning the algorithm with the option to discard unjoined features resolves the issue most of the time, there may have been one instance where this did not work.

### Versions

QGIS Version: 3.32.2. 
Operating System: MacOS Silicon

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Additional Context:
This issue seems to impact the reliability of the "Join by Location" algorithm, specifically when dealing with differing geometries and when creating both joined and unjoined temporary output layers.
I am a new user of QGIS and new to working with GIS software. I have been teaching myself with the assistance of GPT4, so I understand that there is a high chance of user error. But I took all possible steps within my abilities to troubleshoot and the issue persisted. I did find a solution/work around but I am submitting this so I can make sure that any inconsistencies due to my user error are fixed or find the issue in my data and/or software that is causing this.

**Comment by agiudiceandrea** [comment]
@datarealtor. thanks for reporting. It would be very useful in order to let some developers understand the root cause of the issue if you provide the data needed to replicate it.

**Comment by alexbruy** [comment]
@datarealtor can you please provide sample dataset?
