### ISSUE TITLE
QGIS cannot connect to MySQL if user's password contains commas.

### ISSUE THREAD

**Issue by kochizufan** [qgis/QGIS#54493]
### What is the bug or the crash?

When QGIS tries to connect to MySQL, the connection fails if the user's password contains commas.

### Steps to reproduce the issue

1. Create user at MySQL Server (I tried with MySQL 8.1.0)
2. Make password of the user to contain commas.
3. Create spatial table at MySQL.
4. Try to connect from QGIS to MySQL through Layer > Data Source Manager
5. Connection failed.

### Versions

QGIS version
3.30.3-'s-Hertogenbosch
QGIS code revision
2411cec1
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

QGIS stores Connection string like
'MySQL:geo_test,host=localhost,port=3306,user=root,password=XXXXXXX'
So if password contains commas, password is splitted by comma.
<aybe this is the reason of this bug.

**Comment by elpaso** [comment]
This is a GDAL issue

**Comment by kochizufan** [comment]
Thank you for clarifying, I'll report this to GDAL.

**Comment by kochizufan** [comment]
Sorry I found this, thank you
https://github.com/OSGeo/gdal/issues/8385

**Comment by elpaso** [comment]
Let's leave this open: changes to QGIS are also required.

**Comment by elpaso** [comment]
It turned out that it is a QGIS fault not quoting the username and password correctly when needed.
