### ISSUE TITLE
Hang on using 3D map in qgis 3.28

### ISSUE THREAD

**Issue by H-Barati** [qgis/QGIS#54497]
### What is the bug or the crash?
In QGis version 3.28, when using a 3D map, sometimes the software hangs after a few zooms and moves in 3D mode and it is no longer possible to work with the software, this problem does not exist in versions 3.24.

### Steps to reproduce the issue

The video of the defect mentioned at the end of the comment

### Versions

3.28

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

https://github.com/qgis/QGIS/assets/141843926/241216f7-ce8a-487b-943e-cd79270d5935

**Comment by alexbruy** [comment]
Is this still an issue with the latest master/LTR?

**Comment by H-Barati** [comment]
I tested with the stable version 3.28.6, the problem still persists.  Regarding the release of version 3.28.13, I will test with it in the next few days and let you know the result, thanks
