### ISSUE TITLE
error when exporting PDF

### ISSUE THREAD

**Issue by EssamAboud** [qgis/QGIS#54535]
### What is the bug or the crash?

When exporting PDF format from QGIS layout, it takes very long time and no result.

### Steps to reproduce the issue

NA

### Versions

QGIS version
3.32.2-Lima

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No more

**Comment by troopa81** [comment]
Did you use the option "Always export as vector" ? Could you share a project sample and data ?

**Comment by EssamAboud** [comment]
Dear Julien
Thanks for your feedback. I discovered that the main issue was in the downloaded SRTM file from the web. Once I removed this file, it works well.

regards
Essam
