### ISSUE TITLE
[georeferencer] Not supported anymore, still on  the manual.

### ISSUE THREAD

**Issue by jotisa** [qgis/QGIS#54538]
### What is the bug or the crash?

You still list Georeferencer as an active plugin when it's no longer on the repository.  What made you take it off?

### Steps to reproduce the issue

In the plugins menu, I click Manage and Install Plugins and there's no Georeferencer plugin anymore.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.2-Lima | QGIS code branch | Release 3.32
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.10.12
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.36.0
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.5
QScintilla2 version | 2.11.6
OS version | KDE Flatpak runtime
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.32.2-Lima
QGIS code branch
[Release 3.32](https://github.com/qgis/QGIS/tree/release-3_32)
Qt version
5.15.10
Python version
3.10.12
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.36.0
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.11.6
OS version
KDE Flatpak runtime

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
MetaSearch
0.3.6
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Seems there are many tutorials that cite the Georeferencer plugin and there is no introduction to it's replacement.  Many thanks.

**Comment by jotisa** [comment]
Seems Georeferencer is now on the layers menu and this was not showing many thanks I close this.

**Comment by agiudiceandrea** [comment]
@jotsia, could you please indicate in which page of the official documentation for the current QGIS version did you read that the Georeferencer is a plugin available in the plugin repository?
