### ISSUE TITLE
"Export -> Save selected features as" in postgresql SQL Dump format lacks insert commands

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#54548]
### What is the bug or the crash?

`Export -> Save selected features as -> postgresql SQL Dump` comes up empty.

This occurs both in version 3.32.2 and in 2.18 LTR.
Also, `Add saved file to map` is rightly grayed out in the save as dialog, but (wrongly at least sometimes) in a selected state. Adding to map is not going to happen (by design).

### Steps to reproduce the issue

Load a feature set / layer
Select one or more features
Right click layer in TOC
choose export -> save selected features as
choose format Postgresql SQL dump
choose OK
inspect or import generated SQL file to find it not containing feature data.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.2-Lima | QGIS code revision | c0b8833964
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.2-Lima
QGIS code revision
[c0b8833964](https://github.com/qgis/QGIS/commit/c0b8833964)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Trying to figure out how to actually do this, I see several problems.
ogr2ogr will not, afaik, produce SQL output using insert commands; (it will still need some sql to input into a (postgres) table, so perhaps I'm missing an option.)
pg_dump does not work with queries / selections of tables.
A solution would be to create a table from the selection and create SQL output from that. However, access might be lacking and side-effects may be judged undesirable.
Suggestion:
Since PG_dump is present in the bin directory (as well as psql.exe), switch to pg_dump like format and construct the output as follows:
Start with dumping the schema: `pg_dump -s -t <table> -f <filename>.sql`
Then update the output file by inserting after the create table command:
- Add line like `COPY public.<outputtable> (<comma separated fieldlist>) FROM stdin;`
- Copy the requested records, using the list of selected (primary) keys:
`psql -U <user> -d <database> -c "COPY (SELECT * FROM <inputtable> WHERE array[<primarykey>] <@ '{<comma separated keylist>}' TO stdout" > dataout.sql`
- Then insert the content of dataout.sql after the last inserted line, and follow with a line containing `\.`.
Afaik, that could/should do it.

Remarks:
- complete the psql commands with other access options as needed, e.g. a port.
- The sql result can simply be imported by: `psql -U <user> -d <table> < output.sql`. PG_restore is not even needed for this.

**Comment by agiudiceandrea** [comment]
@janhec, thanks for reporting.
I cannot replicate the issue. I've added the World Map layer to a new project, I've selected the features corresponding to the France and Spain countries, I've exported the selected features to PostgreSQL SQL Dump and the resulting file is not empty and contains the selected features: [dump.zip](https://github.com/qgis/QGIS/files/12643864/dump.zip)

**Comment by janhec** [comment]
Sorry for the late reply and thanks for things done.
I tried a fresh case and now found the selected items in the export.
So I seem to have been mistaken and suggest closing the issue.
