### ISSUE TITLE
Composición de planos colapsa QGIS Al regenerar un plano generado correctamente antes.

### ISSUE THREAD

**Issue by opfcl** [qgis/QGIS#54550]
## User Feedback

Re-Generando un plano que ya había funcionado antes.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005624 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsMapRendererStagedRenderJob::renderCurrentPart :
QgsLayoutItemMap::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsScene::render :
QgsLayoutExporter::renderRegion :
QgsLayoutExporter::renderPage :
QgsLayoutExporter::printPrivate :
QgsLabelPosition::operator= :
QgsLayoutExporter::handleLayeredExport :
QgsLayoutExporter::exportToPdf :
QgsGeoreferencerMainWindow::dragEnterEvent :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Al hacer correr la generación de un PDF
![image](https://github.com/qgis/QGIS/assets/99933879/3e9196fd-cb6d-44db-8639-45be71a39e8b)

### Versions

QGIS Version: 3.32.0-Lima
QGIS code revision: https://github.com/qgis/QGIS/commit/311a8cb8a654d24ef300c6c12177d4ba8d062c43
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

PAsó exactamente lo mismo con la version 3.22.10 Beatowieza

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Have you tried with the new profile without any 3rd party plugins installed? Does it work in latest master/LTR?

Also please provide sample data and steps to reproduce the issue.
