### ISSUE TITLE
0 port in OAuth2 callback URI

### ISSUE THREAD

**Issue by honza2** [qgis/QGIS#54562]
### What is the bug or the crash?

In case that OAuth2 authorization fails (bad client_id, redirect_uri, server does not respond...) called programmatically via QgsApplication.authManager().updateNetworkRequest, the library will during next attempt to login insert port 0 in the redirect URI part which is part of the authorization URL instead of the set port in auth manager. The first attempt always goes well. Only restarting QGIS will solve this.

### Steps to reproduce the issue

Failed port in callback URI during second attempt to login:
![image](https://github.com/qgis/QGIS/assets/30647487/00daae3f-68b6-4289-b57b-b98b8709f089)

### Versions

QGIS 3.26 and higher

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
@honza2 I've looked at the implementation and there is nothing that looks suspicious regarding the local port, do you have any clue how I can reproduce this issue in order to debug it?

**Comment by honza2** [comment]
Hello, thank you for your response. I have prepared a code snippet executable in the python console of QGIS. The code adds two records to the authentication manager for the servers I use for authentication - watlas and hub4everybody. To set up the situation, the client_id for watlas is wrong. The correct client_id for testing purposes is this: NRGplX4hmldiGuqwCwUW54jIrPZVnDrnRZ1bAlAi . If everything is correct I can authenticate correctly with both servers and everything works fine. If anything on the path fails (in our case the client_id) the console behaves slightly differently. The script then no longer responds to any changes and the solution is to restart QGIS as in my plugin. 
Please create a test account here: https://watlas.lesprojekt.cz/en/accounts/signup/
https://hub4everybody.com/accounts/signup/
The account can be fictitious, no email verification is required.

As for the script, just switch the auth_file variable. True means failure with bad client_id on watlas server. False will pass correctly with the Hub4everybody server.

Here is the script uploaded to onedrive:
https://1drv.ms/u/s!AvP1Ar0zxMvEgatlxjPHys5EcervXA?e=QbodfH

If you have any questions, please contact me. 

Thank you in advance
Jan

**Comment by elpaso** [comment]
@honza2 thanks for the instructions, I'll have a look.

**Comment by elpaso** [comment]
There is no issue here, it's just the timeout which internally is multiplied by 5 (I don't know why) so you have 5 minutes timeout.

Maybe we can drop the * 5.

**Comment by honza2** [comment]
Thank you for finding the cause. Can you think of any way how can I avoid this behavior so that if authentication fails, I can immediately retry authentication or switch to another server?
