### ISSUE TITLE
Advanced Digitzing Panel text is barely readable with Night Mapping theme

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#54565]
### What is the bug or the crash?

When switching to the *Night Mapping* theme, the text in the *Advanced Digitizing Panel* becomes hardly readable.

<img src="https://github.com/qgis/QGIS/assets/78353871/b3f01546-9ee9-4139-a826-ef76322b8590" width="400" />

### Steps to reproduce the issue

1. Create a new profile
2. Go to Options... -> Switch to *Night Mapping* theme
3. Restart QGIS
4. Create a *New Temporary Scratch Layer*
5. Start editing
6. Activate the *Advanced Digitizing Panel* and *Option*

### Versions

Tested with QGIS 3.32.2 "Lima" and 3.28.10 "Firenze"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.32.2-Lima | QGIS-Codeversion | c0b8833964
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.7.1
PROJ-Version | 9.2.1
EPSG-Registraturdatenbankversion | v10.088 (2023-05-13)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | 15.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The issue does not occur with the *Blend of Gray* UI theme.

**Comment by nirvn** [comment]
@mblesius , can't reproduce on master, e.g.:

![image](https://github.com/qgis/QGIS/assets/1728657/0e2b4437-ff7c-4f49-aede-dad31e1de399)

**Comment by mblesius** [comment]
I just tested with a new profile on https://github.com/qgis/QGIS/commit/4178ace22a4a79e31c4fff016e0c5b9e6413515a MingW64 build of the master branch and the issue is still present.

Maybe its specific to Windows builds?

**Comment by mblesius** [comment]
Still present in QGIS 3.34.0 "Prizren"

**Comment by mblesius** [comment]
Still present in QGIS 3.34.1 "Prizren" and QGIS 3.28.13 "Firenze" (keeping the Bot away).

**Comment by mblesius** [comment]
@nirvn Can the feedback label be removed to the bot from closing the issue? I tested again with a recent master build ([#a5c3785](https://github.com/qgis/QGIS/commit/7c679b65370f27e27010a6640d0959945705808e)) and found it is still present.

Besides, #55104 is likely a duplicate.
