### ISSUE TITLE
Error saving edit on PostGIS geometry when table also contains geography

### ISSUE THREAD

**Issue by derekwatling** [qgis/QGIS#54572]
### What is the bug or the crash?

When a PostGIS table contains both geometry and geography (not GENERATED) features, editng the geometry gives an error when saving edits as it is trying to call a PostGIS function that does not exist:
PostGIS error while changing attributes: ERROR:  function **st_geographyfromewkt**(unknown) does not exist

My research shows that the correct PostGIS function is: **st_geographyfromtext()**

### Steps to reproduce the issue

1. Create a PostGIS table containing both a geometry and a geography feature (where the geography is not GENERATED)
2. Load the geometry into QGIS and edit a feature
3. Save the edit

![image](https://github.com/qgis/QGIS/assets/2980145/b1fac8a2-25f7-4229-8be5-48fa2d626527)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.10-Firenze | QGIS code revision | e2edb9c468
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.10-Firenze
QGIS code revision
[e2edb9c468](https://github.com/qgis/QGIS/commit/e2edb9c468)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Running on Windows 11 Pro 22H2
PostgeSQL 15.4
PostGIS 3.4

I have tested on other setups with same result.

**Comment by elpaso** [comment]
Can you please attach the table SQL definition (and minimal data if needed) to reproduce the issue?

**Comment by derekwatling** [comment]
[geom_and_geog.txt](https://github.com/qgis/QGIS/files/12657147/geom_and_geog.txt)

Some further testing indicates that this only(?) occurs when "Merging" geometries.

**Comment by elpaso** [comment]
Data corruption added because original features are deleted even if the insert fails.
