### ISSUE TITLE
edit geometries function

### ISSUE THREAD

**Issue by jc-sdev** [qgis/QGIS#54570]
### What is the bug or the crash?

Hello 

In the 'edit geometries' menu, I use the 'add a part' button to create multipoligones and when I validate I get an error message saying that the geometry of the new part is empty or invalid.

I have QGIS version 3.32 but on version 3.30 it works.

is there another manipulation to do?

Thanks
Jean Claude

### Steps to reproduce the issue

I made a multipolygon layer in gpk. I placed a first right-of-way by filling in the fields. Then I selected this right-of-way and wanted to add a part.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.32.2-Lima | Révision du code | c0b88339
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.1
Version de Proj | 9.3.0
Version de la base de données du registre EPSG | v10.094 (2023-08-08)
Version de GEOS | 3.12.0-CAPI-1.18.0
Version de SQLite | 3.41.1
Version de PDAL | 2.5.5
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
AdressesFr | 1.1
aide | 0.0.4
AnotherDXF2Shape | 1.3.1
cadastre | 1.18.0
debug_vs | 0.8
DICT | 1.0.1
exportDBmapper | 0.2.0
gestion_ecp | 0.9.7b
help_recolement | 0.1
help_reseau | 0.1
ImportPhotos | 3.0.5
lizmap | 3.16.4
lumigis | 0.9.2
menu_from_project | v2.1.0-beta1
plugin_reloader | 0.9.3
QBano | 1.8
qgis_resource_sharing | 1.0.0
QompliGIS | v1.2.0
StreetView | 3.2
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Version de QGIS
3.32.2-Lima
Révision du code
[c0b88339](https://github.com/qgis/QGIS/commit/c0b88339)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.1
Version de Proj
9.3.0
Version de la base de données du registre EPSG
v10.094 (2023-08-08)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
AdressesFr
1.1
aide
0.0.4
AnotherDXF2Shape
1.3.1
cadastre
1.18.0
debug_vs
0.8
DICT
1.0.1
exportDBmapper
0.2.0
gestion_ecp
0.9.7b
help_recolement
0.1
help_reseau
0.1
ImportPhotos
3.0.5
lizmap
3.16.4
lumigis
0.9.2
menu_from_project
v2.1.0-beta1
plugin_reloader
0.9.3
QBano
1.8
qgis_resource_sharing
1.0.0
QompliGIS
v1.2.0
StreetView
3.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jc-sdev, thanks for reporting. The issue has been already reported at https://github.com/qgis/QGIS/issues/54537.

**Comment by agiudiceandrea** [comment]
Issue fixed with PR https://github.com/qgis/QGIS/pull/54611.
