### ISSUE TITLE
"Aggregate" function does not sort by order when 'order_by' using $geometry and 'expression' not using $geometry

### ISSUE THREAD

**Issue by blacktesta** [qgis/QGIS#54580]
### What is the bug or the crash?

Hello community and developers!
I have two layers polygon and polyline. Polygon layer has **"source_field"** and polyline layer has **"destination_field"** both integer type.   My goal is to have value from **"source_field"** to **"destination_field"** for newly digitized polyline. I want value from polygon which has longest intersection with new polyline. 

![image](https://github.com/qgis/QGIS/assets/74047515/014fe158-caf5-43da-b930-a9ed096c7edd)

Default expression for **"destination_field"** is: 
```
aggregate(
    layer:='polygon_layer_d71d9114_3109_4eac_a7f5_935350625030',
    aggregate:='array_agg', 
    expression:="source_field",
    order_by:=-length(intersection($geometry,geometry(@parent)))
    )
```
I'm not adding 'array_first' in this example so it is possible to see whats happening. I have added polyline above sixth polygon of "polygon_layer". So **6** must be the first in list. But it's not.  

![image](https://github.com/qgis/QGIS/assets/74047515/11cdb400-f6e9-47b8-bd4b-3e33cbbf0b3b)

When I change 'expression' parameter to **"source_field" || $geometry** function sorts values right.

```
aggregate(
    layer:='polygon_layer_d71d9114_3109_4eac_a7f5_935350625030',
    aggregate:='array_agg', 
    expression:="source_field" || $geometry,
    order_by:=-length(intersection($geometry,geometry(@parent)))
    )
```

![image](https://github.com/qgis/QGIS/assets/74047515/fc18f4d0-3e2b-45f9-bcd4-f5edac5a8335)

### Steps to reproduce the issue

See the description above.

### Versions

QGIS version	3.32.2-Lima	QGIS code revision	c0b8833964
Qt version	5.15.3		
Python version	03.09.2005		
GDAL/OGR version	03.07.2001		
PROJ version	09.02.2001		
EPSG Registry database version	v10.088 (2023-05-13)		
GEOS version	3.12.0-CAPI-1.18.0		
SQLite version	3.41.1		
PDAL version	02.05.2005		
PostgreSQL client version	15.2		
SpatiaLite version	05.01.2000		
QWT version	06.01.2006		
QScintilla2 version	2.13.1		
OS version	Windows 10 Version 2009		
			
Active Python plugins			
processing	02.12.1999

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
test project: [aggregate_test.zip](https://github.com/qgis/QGIS/files/12645961/aggregate_test.zip)

**Comment by pigreco** [comment]
have you tried using the `filter` argument too?

```
aggregate(
    layer:='poligono',
    aggregate:='array_agg', 
    expression:="fid",
	filter:= intersects($geometry,geometry(@parent)),
	order_by:=-length(intersection($geometry,geometry(@parent)))
    )
```

**Comment by blacktesta** [comment]
@pigreco Yes, I had. This is what I am trying to avoid. Using filter in such way( when both filter and order_by using spatial operations like intersect) leads to slowing calculations much. I don't have computer right now. I'll upload a sample project in a couple of days to show what I am talking about.

**Comment by DelazJ** [comment]
> I want value from polygon which has longest intersection with new polyline

Not to invalidate the report but maybe you want to look at [overlay_intersects](https://docs.qgis.org/testing/en/docs/user_manual/expressions/functions_list.html#overlay-intersects)

**Comment by blacktesta** [comment]
@pigreco Yes, I had. This is what I am trying to avoid. Using filter in such way( when both filter and order_by using spatial operations like intersect) leads to slowing calculations much. I don't have computer right now. I'll upload a sample project in a couple of days to show what I am talking about.

**Comment by blacktesta** [comment]
@DelazJ It looks like more suitable for my case. Thank you! I will try it. 
Anyway I have opened this issue because of weird behavior I observed, not because i cant do what i want🙂 If it is right behavior the issue can be closed.

**Comment by elpaso** [comment]
Awaiting for test project & data to reproduce the issue.

**Comment by pigreco** [comment]
@elpaso 
> Awaiting for test project & data to reproduce the issue.

here my project with test data

[test_20230918.zip](https://github.com/qgis/QGIS/files/12645951/test_20230918.zip)

**Comment by blacktesta** [comment]
@elpaso I updated the issue with sample project
