### ISSUE TITLE
Why is QGIS too slow to load a project?

### ISSUE THREAD

**Issue by Marctrix14** [qgis/QGIS#54588]
### What is the bug or the crash?

Hi everyone,

I'm working as IT assistant and in the company that I work on there is a problem with QGIS in one of the workstations. 

QGIS takes 10 minutes to load a project, where in another PC of the same specifications, it takes 30 seconds.
If I press the mouse or the keyboard while loading the project, QGIS crashes. 

The specifications of this PC are:

- Model: Dell Precision 3630 Tower

- CPU: Xeon E-2174G @3.80

- 16GB RAM

- SSD 256 GB

- W11 Pro

The project has 70 GB, but the disk has 50 GB free. 

I don't know what's wrong, here's what I tried:

- Reinstall QGIS multiple times. 
- Try different versions (QGIS 3.28.8, 3.28.10, 3.32.2).
- Close the window browser. 

None of the previous attempts decreased the load time. 
Maybe this is not considered as a bug, but I'm exposing my problem here to try get some feedback. 
I already contacted the StackExchange community and the Spanish Telegram group for help.

I checked that plugins load correctly through the plugin "Load Times". 
I'll try with a new profile and tell you how it goes. 

So, apart from that, I'd appreciate if anyone could give me any clue on how I could solve this problem as I've been investigating it for the past 3 weeks.

Thank you.

Marc

### Steps to reproduce the issue

1. Open project 

### Versions

Currently 3.28.8, previously had 3.32.2 and 3.28.10. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Marctrix14** [comment]
To give you more information, I attach 2 screenshoots from today. 
It's from the debugger where the project load time is shown. 

![tiempoCarga_proyectoQGIS_Drive_14_9_2023](https://github.com/qgis/QGIS/assets/78456629/541180c9-4bca-49ac-9914-50674b7fb876)
![tiempoCarga_2_proyectoQGIS_Drive_14_9_2023](https://github.com/qgis/QGIS/assets/78456629/2ad7d103-9798-4fe9-a2f7-ded639183024)

**Comment by jef-n** [comment]
Doesn't give clue about which datasources you are using.

**Comment by Marctrix14** [comment]
> Doesn't give clue about which datasources you are using.

How I can check which datasources are being used?, so that I could tell you which are.

**Comment by Marctrix14** [comment]
I tried with a new profile and now the project loads in 10-20s.
I'll have to find out if the following missing plugins are necessary:

- qgis2web 
- quick_map_services 
- profiletool
- ParallelLineConstruction 
- qgiscloud
- IPyConsole 
- PluginLoadTimes 
- qchainage
- db_manager

**Comment by HusseinKabbout** [comment]
@Marctrix14 Is the project published on QGISCloud?

> How I can check which datasources are being used?, so that I could tell you which are.

The data source of a layer can be checked by opening the layer settings and choosing the `Information` tab. In the `General` section you should find the `Source` String and the `Provider`.

**Comment by Marctrix14** [comment]
Thank you @HusseinKabbout for the information.

The project is not published on QGISCloud, that's why we don't need to use that plugin and I opted for disabling it.
