### ISSUE TITLE
non-editable csv layer

### ISSUE THREAD

**Issue by jc-sdev** [qgis/QGIS#54599]
### What is the bug or the crash?

Hello 

It is impossible to edit the csv layer to modify the attributes.

Thanks

Jean Claude 

### Steps to reproduce the issue

add a layer of delimited text

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.32.2-Lima | Révision du code | c0b88339
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.1
Version de Proj | 9.3.0
Version de la base de données du registre EPSG | v10.094 (2023-08-08)
Version de GEOS | 3.12.0-CAPI-1.18.0
Version de SQLite | 3.41.1
Version de PDAL | 2.5.5
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
AnotherDXF2Shape | 1.3.0
debug_vs | 0.8
french_locator_filter | 1.0.4
lumigis | 0.9.1
menu_from_project | v2.0.8
plugin_reloader | 0.9.3
StreetView | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>Version de QGIS
3.32.2-Lima
Révision du code
[c0b88339](https://github.com/qgis/QGIS/commit/c0b88339)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.1
Version de Proj
9.3.0
Version de la base de données du registre EPSG
v10.094 (2023-08-08)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
AnotherDXF2Shape
1.3.0
debug_vs
0.8
french_locator_filter
1.0.4
lumigis
0.9.1
menu_from_project
v2.0.8
plugin_reloader
0.9.3
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jc-sdev** [comment]
Hello,

You're obviously waiting for feedback, but can you tell me what you need?

**Comment by antoniolocandro** [comment]
CSV layers are read only in QGIS and most GIS as far as I can tell, you would need to edit the CSV externally and it should be automatically reloaded if you are watching the file. 

In any case this wouldn't be a bug but a feature request and I am not sure editing CSV would be a good addition
