### ISSUE TITLE
Join excel - Upsert on edit does not work

### ISSUE THREAD

**Issue by frspp** [qgis/QGIS#54590]
### What is the bug or the crash?

Bug

### Steps to reproduce the issue

Add geopackage (with lines) 
Add xlsx file (contains details about lines)
Open Layer Settings for geopackage > Join 
Join with excel on common field.
Tick "Editable"
Tick "Upsert on edit" -- meaning _"update an existing row if a specified value already exists in a table, and **insert a new row if the specified value doesn’t already exist."_**
Tick "Delete cascade"
Tick "joined fields" and choose field
![image](https://github.com/qgis/QGIS/assets/22942340/03c6b208-fb12-4c22-aab3-2a0c9bfd2df2)

Toggle editing for both layers
Choose geopackage layer
Open attribute table
Make edits to line which does not exist in excel.
Save both layers.
Edits are lost because those are not saved into excel. 

--> Conclusion: Upsert does not add a new row with **the common join value in its field** to excel. It (sometimes) adds new rows but the common join value is missing on the new rows.

### Versions

3.32.2 and previous versions too

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can you provide sample data needed to reproduce the issue?
