### ISSUE TITLE
Copy and move map tool duplicates original feature

### ISSUE THREAD

**Issue by JuhoErvasti** [qgis/QGIS#54607]
### What is the bug or the crash?

When using the copy and move features map tool it duplicates the original feature in addition to the new copied and moved feature. GIF to demonstrate:
![copyandmovebug](https://github.com/qgis/QGIS/assets/118284595/13614f1b-5844-41da-8f94-8a68dc1208d2)

### Steps to reproduce the issue

1. Create a new (temporary) layer (geometry type doesn't matter)
2. Add a new feature.
3. Use the 'copy and move feature(s)' map tool to copy the feature.
4. Check if the original feature was duplicated (by moving, or check the attribute table/use identify etc.)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.33.0-Master | QGIS code revision | 569d60ddb7
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.3
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.2 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
infrao | 0.1.1
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.33.0-Master
QGIS code revision
[569d60ddb7](https://github.com/qgis/QGIS/commit/569d60ddb7)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.3
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

This copy of QGIS writes debugging output.

Active Python plugins
quick_map_services
0.19.33
infrao
0.1.1
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tried also in 3.32.0, doesn't appear there. Might be related to #53965?

**Comment by pigreco** [comment]
I confirm

## OSGeo4W win 10 PRO

**Comment by agiudiceandrea** [comment]
@pigreco, does the issue occurs also with 3.32.2 or 3.32.3 or only in 3.33.0-Master?

**Comment by pigreco** [comment]
> @pigreco, il problema si verifica anche con 3.32.2 o 3.32.3 o solo con 3.33.0-Master?

- I just tested in 3.32.2-2 and confirm no bugs;
- I just downloaded and tested in 3.32.3-1 and confirm no bugs;
- I just updated the master 3.33.0-575-b 168b20516-1 and tested and confirmed the bug!!!

https://github.com/qgis/QGIS/assets/7631137/20281034-bf47-46c0-af72-f9f81adafaac

**Comment by agiudiceandrea** [comment]
@JuhoErvasti @pigreco, thanks for reporting and testing. A PR https://github.com/qgis/QGIS/pull/54622 has been submitted ti fix the issue.
