### ISSUE TITLE
order of QgsProcessingParameterNumber arguments is incorrect in grass7.txt

### ISSUE THREAD

**Issue by twest820** [qgis/QGIS#54618]
### What is the bug or the crash?

%ProgramFiles%\QGIS 3.32.2\apps\qgis\python\plugins\grassprovider\grass7.txt documents QgsProcessingParameterNumber as
```
QgsProcessingParameterNumber|[name of GRASS parameter]|[description of parameter to show]|QgsProcessingParameterNumber.Integer or QgsProcessingParameterNumber.Double|[min value]|[max value]|[default value]|[True/False, indicating if the parameter is optional or not]
```

Using this syntax prevents newly added GRASS commands from appearing in the processing toolbox (possibly silently, it's unclear if an error's logged anywhere). From a look at the existing .txt addon files (r.out.png's compression level's a good example) the correct order of arguments has the min and max values at the end:
```
QgsProcessingParameterNumber|[name of GRASS parameter]|[description of parameter to show]|QgsProcessingParameterNumber.Integer or QgsProcessingParameterNumber.Double|[default value]|[True/False, indicating if the parameter is optional or not]|[min value]|[max value]
```

### Steps to reproduce the issue

Follow grass7.txt's instructions to add a GRASS command. For example, create r.tpi.txt with
```
r.tpi
Calculates the multiscale topographic position index
Raster (r.*)
QgsProcessingParameterRasterLayer|input|Input DEM from which to calculate mTPI|None|False
QgsProcessingParameterNumber|minradius|Minimum neighborhood radius in cells for DEM smoothing|QgsProcessingParameterNumber.Integer|1|None|1|False
QgsProcessingParameterNumber|maxradius|Maximum neighborhood radius in cells for DEM smoothing|QgsProcessingParameterNumber.Integer|1|None|31|False
QgsProcessingParameterNumber|steps|Number of steps to use for DEM generalization between minradius and maxradius|QgsProcessingParameterNumber.Integer|1|None|5|False
QgsProcessingParameterRasterDestination|output|Multi-scale topographic position index
```

### Versions

QGIS version
3.32.2-Lima
QGIS code revision
c0b8833964
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
coordinate_capture
0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@twest820, thanks for reporting. Would you propose a pull request to fix the issue?
