### ISSUE TITLE
r.tpi is missing from QGIS GRASS support

### ISSUE THREAD

**Issue by twest820** [qgis/QGIS#54619]
### Feature description

[r.tpi](https://grass.osgeo.org/grass83/manuals/addons/r.tpi.html) has been present in GRASS since at least 2021 but hasn't been surfaced in QGIS.

### Additional context

For r.tpi.txt I have
```
r.tpi
Calculates the multiscale topographic position index
Raster (r.*)
QgsProcessingParameterRasterLayer|input|Input DEM from which to calculate mTPI|None|False
QgsProcessingParameterNumber|minradius|Minimum neighborhood radius in cells for DEM smoothing|QgsProcessingParameterNumber.Integer|1|True|1|None
QgsProcessingParameterNumber|maxradius|Maximum neighborhood radius in cells for DEM smoothing|QgsProcessingParameterNumber.Integer|1|True|1|None
QgsProcessingParameterNumber|steps|Number of steps to use for DEM generalization between minradius and maxradius|QgsProcessingParameterNumber.Integer|5|True|1|None
QgsProcessingParameterRasterDestination|output|Multi-scale topographic position index
```

This allows an r.tpi launch from the processing toolbox but fails with
```
r.tpi input=rast_65049e4d5f0003 minradius=1 maxradius=31 steps=5 output=output0f7db2cc771e4c54b8a3217694745610 --overwrite
'r.tpi' is not recognized as an internal or external command, operable program or batch file.
```
so some additional setup beyond what's specified in %ProgramFiles%\QGIS 3.32.2\apps\qgis\python\plugins\grassprovider\grass7.txt appears to be needed.

Notably, there's no r.tpi.exe in QGIS 3.32.2\apps\grass\grass83\bin. If I launch the GRASS UI from the installed QGIS link Settings -> Addons extensions -> Install extensions from addons I get an infinite wait cursor and the list of extensions never populates. This suggests a dependency on #53048 for supporting r.tpi.

**Comment by agiudiceandrea** [comment]
@twest820 r.tpi is a GRASS-GIS add-on so it is not provided by default with GRASS-GIS distribution and thus it is not present by default in QGIS.
Have you tried to first install the add-on using the g.extension.manage GRASS algorithm?
Please see https://github.com/qgis/QGIS/pull/53049 and https://github.com/qgis/QGIS/pull/53246.

**Comment by twest820** [comment]
> Have you tried to first install the add-on using the g.extension.manage GRASS algorithm?

Did you mean `g.extension`, which is what Settings -> Addons extensions -> Install extensions is labelled to use? Not getting search hits on `g.extension.manage`.

QGIS 3.28.11 does manage something of an error log before the GRASS UX hangs. Interesting that git's involved here and, even though the QGIS installer should presumably set GRASS up with its git dependency, also curious GRASS can't find system git from the default path.
```
Exception in thread
Thread-14
:
Traceback (most recent call last):
  File
"C:\PROGRA~1\QGIS32~1.11\apps\Python39\lib\threading.py",
line 954, in _bootstrap_inner

self.run()
  File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\gui\wxpython\core\gthread.py", line 154, in __run

self.__run_backup()
  File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\gui\wxpython\core\gthread.py", line 117, in run

ret = vars()["callable"](*args, **kwds)
  File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\gui\wxpython\modules\extensions.py", line 369, in Load

raise GException(_("Unable to load extensions. %s") % msg)
core.gcmd
.
GException
:
Unable to load extensions. Traceback (most recent call
last):
File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\scripts\g.extension.py", line 2855, in <module>
sys.exit(main())
File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\scripts\g.extension.py", line 2803, in main
xmlurl = resolve_xmlurl_prefix(original_url, source=source)
File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\scripts\g.extension.py", line 2492, in resolve_xmlurl_prefix
version_branch = get_version_branch(VERSION[0])
File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\scripts\g.extension.py", line 507, in get_version_branch
branch = gs.Popen(
File "C:\PROGRA~1\QGIS32~1.11\apps\grass\grass83\etc\python\grass\script\core.py", line 55, in __init__
raise OSError(_("Cannot find the executable {0}").format(args[0]))
OSError: Cannot find the executable git
```

**Comment by agiudiceandrea** [comment]
> Did you mean g.extension

No. `g.extension.manage` is a processing algorithm allegedly available (along with -`g.extension.list`) in QGIS 3.32. See also https://github.com/qgis/QGIS/pull/53049 by @AlisterH .

**Comment by twest820** [comment]
Already looked at both #53049 and #53246 per earlier request. They're cryptic if you're not involved in the development. There's no obvious option for `g.extension.manage` in the GRASS UX and it's unknown on the GRASS command line.

Based on grepping the install

- C:\Program Files\QGIS 3.32.3\apps\qgis\python\plugins\grassprovider\description\g.extension.manage.txt
- C:\Program Files\QGIS 3.32.3\apps\qgis\python\plugins\grassprovider\ext\g_extension_manage.py

it appears "processing algorithm" here refers to QGIS's processing toolbox rather than GRASS. However, the failure's the same as with `g.manage`:
```
>g.extension extension="r.tpi" operation="add" --overwrite
Traceback (most recent call last):
File "C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\scripts\g.extension.py", line 2855, in <module>
sys.exit(main())
File "C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\scripts\g.extension.py", line 2830, in main
get_addons_paths(gg_addons_base_dir=options["prefix"])
File "C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\scripts\g.extension.py", line 2734, in get_addons_paths
addons_branch = get_version_branch(VERSION[0])
File "C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\scripts\g.extension.py", line 507, in get_version_branch
branch = gs.Popen(
File "C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\etc\python\grass\script\core.py", line 55, in __init__
raise OSError(_("Cannot find the executable {0}").format(args[0]))
OSError: Cannot find the executable git
Press any key to continue . . .
Execution completed in 1.44 seconds
Results:
{}

Loading resulting layers
Algorithm 'g.extension.manage' finished
```

**Comment by AlisterH** [comment]
This appears to be something that they broke in GRASS (responding to changes by github?) and they have just recently fixed: https://github.com/OSGeo/grass/issues/3077
Don't know how soon QGIS will be available with the fixed GRASS, but you can workaround by pointing it at a git install.

**Comment by agiudiceandrea** [comment]
Thanks Alister.
