### ISSUE TITLE
Make 'render scale' property available to symbology/labeling expressions

### ISSUE THREAD

**Issue by Ricmokodo** [qgis/QGIS#54623]
### Feature description

Providing some form of "current render scale" accessible as a property to symbology expressions would allow a new level of flexibility to quickly rendering features on screen and in map layouts.

The property would be similar in some respects to the property returned by `map_get( item_variables('Map 0'), 'map_scale')` symbology expression but the property would be relative to whatever the renderer is doing, so as to be applicable to the map on screen or a layout render.

In theory, it would work as a alternative to "scale-dependent" symbology techniques, wherein you set a value explicitly at preset scales. In the case of ArcGIS Pro, the renderer also interpolates the value linearly. Distinctively, this would allow you to set a symbology value _as a function of_ renderer map scale.

This has been a dream of mine, but I admit there are some aspects I'm sure I haven't considered. 

### Additional context

For simplicity, suppose a map is rendered in EPSG:3857 and we refer to scale as the standard webmap zoom levels 0-23, or whatever range of scale values. In QGIS symbology expressions, one could set the size value on a point feature layer equal to 'current_map_scale',  in pixels for example. So, in this example, at zoom level 16 the point is rendered with a size of 16 pixels.

Given a user input max/min scale range, a 'current_map_scale' property could be translated to a 0 to 1 float value. The user could write any expression to calculate the symbology value at any scale, or use 'case-when' statements to achieve the aforementioned alternative to scale-dependent symbology techniques.

**Comment by DelazJ** [comment]
> In theory, it would work as a alternative to "scale-dependent" symbology techniques, wherein you set a value explicitly at preset scales. In the case of ArcGIS Pro, the renderer also interpolates the value linearly. Distinctively, this would allow you to set a symbology value as a function of renderer map scale.

@Ricmokodo Unless I misunderstand your request (if so sorry for the noise), and although it is not translated as an expression variable, there is an ability to scale symbols properties along a range of scale. For example, use "map units" for let's say "stroke width" of a symbol and press the options icon next to it. See https://docs.qgis.org/testing/en/docs/user_manual/introduction/general_tools.html#unit-selector

**Comment by Ricmokodo** [comment]
@DelazJ Yes, setting symbology units can be an effective solution for some techniques, but I don't think it is the more universal one that I am imagining. For example, if I wanted to set the opacity of a polygon _as a function of map scale_ (a common practice in my world) I don't believe the 'map units' approach would get us there.

Exposing a current_map_scale property to expressions would not seem to be all that complicated (I don't really know), however setting a custom scale range to arrive at a 0-1 value would require some kind of expression function with min_scale, max_scale as the user input parameters.

Thanks for engaging and for the opportunity to clarify the idea.

**Comment by DelazJ** [comment]
> Exposing a current_map_scale property to expressions would not seem to be all that complicated (I don't really know), 

Can you give a look to the variable `@map_scale` ?

**Comment by DelazJ** [comment]
And i didn't test but maybe, combined to [scale_linear](https://docs.qgis.org/testing/en/docs/user_manual/expressions/functions_list.html#scale-linear) , you can get to what you are looking for?

**Comment by Ricmokodo** [comment]
Ahah! QGIS never lets you down. That's it. Actually, I think `@vector_tile_zoom` and similarly `@zoom_level` are very close to what I had in mind. This one can be closed.

Thanks @DelazJ !
