### ISSUE TITLE
Export Layers to DXF does not maintain the CRS of the new dxf file

### ISSUE THREAD

**Issue by afsneto** [qgis/QGIS#54656]
### What is the bug or the crash?

When I use the "Export Layers to DXF" tool, the output file does not maintain the CRS of the original shapefile.

### Steps to reproduce the issue

1. Load the shapefile GO_5205109_APP.shp
[APP.zip](https://github.com/qgis/QGIS/files/12653763/APP.zip)

2. Open the "Reproject Layer" tool, set the Target CRS to EPSG:31982, and Run.
3. Select the new layer "Reproject" and open the tool "Export layers to DXF". ![export_layers_to_dxf](https://github.com/qgis/QGIS/assets/32796832/108888c6-f3a1-4dbe-a644-93a4f5d97bee)
4. Load GO-APP_utm22.dxf. [GO-APP_utm22.zip](https://github.com/qgis/QGIS/files/12653871/GO-APP_utm22.zip)
5. Select the layer properties, and the CRS project is set to invalid. ![layer_properties](https://github.com/qgis/QGIS/assets/32796832/a40fa8d1-474d-45e2-983d-507e47267b73)

### Versions

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
kmltools
3.1.30
Save-DXF
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
DXF doesn't know about CRS.
