### ISSUE TITLE
Bug: Tessellate processing tool discarding parts of valid source polygon layer

### ISSUE THREAD

**Issue by remtav** [qgis/QGIS#54652]
### What is the bug or the crash?

We are having an issue with the tesselate algorithm. On some of our extractions, big chunks of road network as polygons are deleted after the tesselate. There is no error in log.

Altough all geometries are valid under "fix geometries" and "check validity" tools, I personnaly suspect the source data to having some kind of invalid geometry, causing this bug. A hint to support this theory is that I encounter similar bugs with other processing tools down the line: https://github.com/NRCan/geo_sim_processing/issues/21.

1. Source polygons
![image](https://github.com/qgis/QGIS/assets/34774759/adc24bd2-2d5a-4694-be8f-e9d60118af43)

2. Tesselation
![image](https://github.com/qgis/QGIS/assets/34774759/6b4df1de-02da-4664-aeb8-cdc566cab766)

Zoomed out before:
![2023-09-18 10_52_22-_Untitled Project — QGIS](https://github.com/qgis/QGIS/assets/34774759/80819b61-4104-4e01-93f5-f96111df4288)

Zoomed out after:
![image](https://github.com/qgis/QGIS/assets/34774759/a439a390-0fce-4175-a7a3-9b20b37e3bed)

Log (no errors):
![image](https://github.com/qgis/QGIS/assets/34774759/eb7fee6e-df0e-484a-9aff-2d77852034bc)

### Steps to reproduce the issue

Sample vector data causing problems (all geometries are valid under "fix geometries" and "check validity" tools in QGIS):
[QC_SaintJeanSurRichelieu_WV02_20210524-017162145010_01_P001-WV02_ROAI_raw_clipped.zip](https://github.com/NRCan/geo_sim_processing/files/12613280/QC_SaintJeanSurRichelieu_WV02_20210524-017162145010_01_P001-WV02_ROAI_raw_clipped.zip)

1. Open "Tesselate" processing tool
2.  Choose attached file as source layer
3. Run

### Versions

QGIS version
3.30.2-'s-Hertogenbosch
QGIS code branch
Release 3.30
Qt version
5.15.3
Python version
3.10.6
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.2 LTS

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

*** ALSO TESTED WITH: ***

QGIS version
3.26.3-Buenos Aires
QGIS code revision
65e4edfdada
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.1.0
EPSG Registry database version
v10.074 (2022-08-01)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geoml-stac-browser-master
1.0.0
geo_sim_processing-Dan-Eli-master
0.6.1
go2streetview
8.6
HCMGIS
23.7.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
It seems like your main feature is too topologically complex and causes crash.

In the meantime using the `Polygon generalization` tool from saga next-gen prior to running tesselate seems to bypass the issue.
