### ISSUE TITLE
python error: couldn't load plugin 'qgis gee data catalog' due to an error

### ISSUE THREAD

**Issue by hntrak** [qgis/QGIS#54671]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/145478960/eb61aa5d-e04b-43c3-8df4-7f5359c25f0b)

![image](https://github.com/qgis/QGIS/assets/145478960/e43e5fd0-1b6e-42c2-a06d-74fa3b05f992)

This appears anytime I open up the Qgis program.

### Steps to reproduce the issue

Anytime I open the program this appears at the top of the screen.

### Versions

![image](https://github.com/qgis/QGIS/assets/145478960/f2fb58c0-fd82-4eae-93a3-c142c5b28a51)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @hntrak, thanks for reporting. The issue seems due to the qgis_gee_data_catalog ("Google Earth Engine Data Catalog") plugin and not to QGIS itself: if you want to get rid of the error message you can disable or uninstall such plugin or you can create and use a new QGIS user profile.

**Comment by hntrak** [comment]
Andrea,

Thank you for the information - I will look into the uninstall or reinventing myself! 🙂

Thank you,

Matthew Doerksen, Cad Technician
New Horizons Telecom, Inc.
Palmer, Alaska
907-761-6072
nhtiusa.com
[cid:15d22692-c7ee-4924-b736-e536e27e0a1b]
________________________________
