### ISSUE TITLE
[DB Manager] problem with 'WITH' query to create new layer from query (using Geopackage)

### ISSUE THREAD

**Issue by thomas-szczurek** [qgis/QGIS#54677]
### What is the bug or the crash?

Within DB Manager and the SQL Windows, with a Geopackage, creating a new layer from a SELECT SQL query is properly working.
But when trying to use the exact same request with a CTE to create a new layer it doesn't work.
The problem seems to be the same as issue #15470 but with geopackages instead of postgis.
However, it works with a virtual layer.

### Steps to reproduce the issue

1. Create a new geopackage with a polygon layer named "test_cte"with two fields (geom and pk_id)
2. insert a square with

``` SQL 
INSERT INTO test_cte (geom, pk_id) VALUES
(GeomFromText('POLYGON((0 0,1 0,1 1,0 1,0 0))',4326),1)
```
3. Create a connection toward the geopackage
4. In the db manager SELECT * FROM test_cte and then load as a new layer by clicking on "load as new layer". See it working
5. try with 
``` SQL
WITH test AS (SELECT * FROM test_cte) SELECT * FROM test
```
and load as a new layer. The new layer will contain no object.
You can find here a zip containing a gpkg to reproduce these steps.
[cte.zip](https://github.com/qgis/QGIS/files/12671357/cte.zip)

### Versions

3.32-3 and 3.28-11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@thomas-szczurek, thanks for reporting.
A simple fix would be to allow both SELECT and WITH statements at the begging of a selection SQL query at https://github.com/qgis/QGIS/blob/e5e6a1367127d003d33bf129aa7591fd8ecbbf76/src/core/providers/ogr/qgsogrproviderutils.cpp#L1392
What do you think?

**Comment by agiudiceandrea** [comment]
@thomas-szczurek, thanks for reporting.
A simple fix would be to allow both SELECT and WITH statements at the begging of a selection SQL query at https://github.com/qgis/QGIS/blob/e5e6a1367127d003d33bf129aa7591fd8ecbbf76/src/core/providers/ogr/qgsogrproviderutils.cpp#L1392
What do you think?
