### ISSUE TITLE
Point to Path tool causes QGIS to crash

### ISSUE THREAD

**Issue by andremano** [qgis/QGIS#54686]
### What is the bug or the crash?

Running the **Points to Path** tool (like shown below) makes QGIS crash (no error message, QGIS simply shuts down)

![image](https://github.com/qgis/QGIS/assets/6665872/8c247782-1ca4-4691-a664-8986547b5035)

### Steps to reproduce the issue

I was trying to run the tool using this [dataset](https://drive.google.com/file/d/19m1Xn7J6lB757DrbLEaYUXu26_woZNv_/view?usp=sharing).

### Versions

QGIS version
3.28.10-Firenze
QGIS code revision
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
cartography_tools
1.2.1
postgis_toolbox
1.0
qgis_resource_sharing
1.0.0
quick_map_services
0.19.33
SemiAutomaticClassificationPlugin
7.10.11
SRTM-Downloader
3.2.0
valuetool
3.0.17
visualist
0.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pblottiere** [comment]
I can reproduce the crash with the dataset, I'm taking a look.

**Comment by agiudiceandrea** [comment]
@andremano, thanks for reporting. The provided GPKG layer of POINT geometry type strangely contains both Point geometries and LineString geometries and this is the cause of the crash. If you remove from such layer the features with a LineString geometry associated, then the processing algorithm will execute without crashing.
