### ISSUE TITLE
QGIs 3.28 - program closes automatically

### ISSUE THREAD

**Issue by hubik98** [qgis/QGIS#54689]
### What is the bug or the crash?

Hello, I have a problem with QGis. The program closes without a message and without load. The only thing is information from the logger (PL). The problem occurs on 3.22 and 3.28. Reinstalling the application does not help.

![image](https://github.com/qgis/QGIS/assets/145680095/943ec9a5-2e5e-41aa-86e5-f453593c97c8)

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/145680095/943ec9a5-2e5e-41aa-86e5-f453593c97c8)

### Versions

3.22.13-1
3.28.11-1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@hubik98, thanks for reporting. Please specify the exact steps that lead QGIS to crash in your system. Please specify the content of the QGIS Help->About menu.
