### ISSUE TITLE
Map Tip - black outline/border is missing on Windows

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#54684]
### What is the bug or the crash?

Windows:
![grafik](https://github.com/qgis/QGIS/assets/20856381/820b7166-2361-46f2-9df3-79971b327071)

Ubuntu:
![grafik](https://github.com/qgis/QGIS/assets/20856381/ae12996e-b092-4a1d-91e3-06f2f0c170ba)

### Steps to reproduce the issue

1. Drag'n'drop the GPKG in QGIS [test.zip](https://github.com/qgis/QGIS/files/12681674/test.zip).
2. Enable "Show Map Tips".
3. Hover over feature.
4. See error -> black outline/border is missing

### Versions

QGIS-Version | 3.32.3-Lima | QGIS-Codeversion | 67d46100b5
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.7.2
PROJ-Version | 9.3.0
EPSG-Registraturdatenbankversion | v10.094 (2023-08-08)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | 15.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 1809
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by YoannQDQ** [comment]
I could not reproduce this... Could you try adding ` #QgsWebViewContainer {border: 5px solid}` in the `<style>` section of your maptip, and tell me if all or part of the border is still missing?

When the maptip use size constraints that make is wider than canvasWidth/2 or taller than canvasHeight/2, it can be cropped though, so part of the border disappears as well, but the border should not disappear altogether.

This issue should hopefully be mitigated by #54730, which fixes the scrollbar, and tweak the map tip size policy.

**Comment by pathmapper** [comment]
@YoannQDQ, thanks for looking into this!



> adding  #QgsWebViewContainer {border: 5px solid} in the <style> section of your maptip

It works 👍 , preview is fine:

![grafik](https://github.com/qgis/QGIS/assets/20856381/6155b71b-6dc0-459b-8d6a-1ed5749dfdee)

Map Tip border is missing on the right side:

![grafik](https://github.com/qgis/QGIS/assets/20856381/ed18436d-bf2d-4007-9aa8-be52d9987e54)

> When the maptip use size constraints that make is wider than canvasWidth/2 or taller than canvasHeight/2, it can be cropped

Yep, seems to be the issue, when increasing the map canvas, the border is fully visible:

![grafik](https://github.com/qgis/QGIS/assets/20856381/21f560ea-5799-4d8e-a7f7-1d801f9ab9b1)


> This issue should hopefully be mitigated by https://github.com/qgis/QGIS/pull/54730, which fixes the scrollbar, and tweak the map tip size policy.

I'll give it a try on Windows.

**Comment by pathmapper** [comment]
> I'll give this PR a try on Windows.

#54730 has a better behaviour, but for some cases the issue still exists, especially when the Map Tip is located left of the mouse pointer:

![grafik](https://github.com/qgis/QGIS/assets/20856381/4b00ac64-de86-4b95-bc20-79fd944f0b4a)

---

Same canvas size and Map Tip located right of the mouse pointer:
![grafik](https://github.com/qgis/QGIS/assets/20856381/3d28388c-7c23-4a18-abcd-09193c15ae93)

**Comment by pathmapper** [comment]
Not reproducible anymore with 3.34.3 -> closing
