### ISSUE TITLE
Commit to error 

### ISSUE THREAD

**Issue by KambuaGH** [qgis/QGIS#54690]
### What is the bug or the crash?

After digitizing there is no id (instead it brings the Action column) inside the column is a duplicate feature. When I try to save the edits in the attribute table, it clears all the edits and changes the language of the fields added. Then going back to QGIS workspace there is pop of commit to layer (it cannot save the layer edits). I've tried to uninstall and reinstall the application, but the error still remains.
<img width="417" alt="Attribute Table" src="https://github.com/qgis/QGIS/assets/142331383/4cde5cfd-7f7a-41cc-901f-1434cc1b0f8a">
<img width="366" alt="Commit to error" src="https://github.com/qgis/QGIS/assets/142331383/d6e17a1b-6334-49ef-b943-142c7b4cccba">

### Steps to reproduce the issue

<img width="366" alt="Commit to error" src="https://github.com/qgis/QGIS/assets/142331383/fe8e21f3-a952-49b5-834b-c6791feeb74e">

### Versions

QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf63
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.33
RasterAttributeTable
1.2
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@KambuaGH, thanks for reporting. Could you please provide a sample layer with which the issue does occur and exact minimal steps to reproduce the issue with such layer? Could you please specify what is the Windows system language and the language and locale set in QGIS?
