### ISSUE TITLE
Getting 'Add part : New part's geometry is empty or invalid.' when trying to add part to an existing feature

### ISSUE THREAD

**Issue by EranGeo** [qgis/QGIS#54693]
### What is the bug or the crash?

When attempting to add additional part to a feature in a multipolygon layer, one is getting the following error message `Add part : New part's geometry is empty or invalid.`

### Steps to reproduce the issue

1. Create a new scratch layer with a multipolygon geoemtry type.
2. Toggle editing and create a feature using the `Add Polygon Feature` command.
3. Select the newly created feature.
4. In the `Advanced Digitizing Toolbar` use the `Add Part` command and try digitizing additional polygonal part for the selected feature. 

**Observations**

1. The new part disappears from the canvas and message is being prompted - `Add part : New part's geometry is empty or invalid.`
2. I tested this issue against a development version of QGIS (3.33) and against an LTR version (3.28.11). The issue could only be reproduced against the development version.
3. I could also reproduce the issue using a different provider (PostgreSQL).

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.33.0-Master | QGIS code revision | e5e6a13671
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.0dev-bba72b1374
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.33.0-Master
QGIS code revision
[e5e6a13671](https://github.com/qgis/QGIS/commit/e5e6a13671)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0dev-bba72b1374
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

This copy of QGIS writes debugging output.

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by EranGeo** [comment]
After submitting this issue, I saw that that it very much resembles issue #54537. Especially [this comment](https://github.com/qgis/QGIS/issues/54537#issuecomment-1713345802 ). Therefore I'm not sure if my issue to be considered to be duplicated or not.

**Comment by agiudiceandrea** [comment]
@EranGeo, thanks for reporting. You are experiencing the same issue reported in https://github.com/qgis/QGIS/issues/54537. A fix for such issue has been already submitted: https://github.com/qgis/QGIS/pull/54611.

**Comment by EranGeo** [comment]
Thanks @agiudiceandrea . Just wanted point that I was able to reproduce the issue in the latest development version, which is compiled against a [commit from the 24 hours](https://github.com/qgis/QGIS/commit/e5e6a13671) (or at least this is what I understand from the About section). In In this prospect, the fix that was submitted in #54611 , was done [last week](https://github.com/qgis/QGIS/pull/54611/commits/5ea6b0ed3fe3668952e00e09f709ac404f0a9272). Therefore, I think there's a chance it might not be a duplicated issue or that the provided fix didn't fixed the issue entirely.

**Comment by agiudiceandrea** [comment]
@EranGeo , the fix has not been merged yet in the master branch. The issue will continue to occur in QGIS dev until the PR #54611 is merged.
