### ISSUE TITLE
Band Rendering different between layout and model space

### ISSUE THREAD

**Issue by mastrolube** [qgis/QGIS#54712]
### What is the bug or the crash?

Hello, I've noticed that legend band rendering is different than actually correct view from model.
![immagine](https://github.com/qgis/QGIS/assets/52335835/2d0aadc6-2e01-4799-af75-4bc626ea0453) ![immagine](https://github.com/qgis/QGIS/assets/52335835/5c0eaa38-f441-453a-a66d-1eb9523be928)

As you can see it's not considering the opacity.
![immagine](https://github.com/qgis/QGIS/assets/52335835/acfd1014-13f0-4fe3-b2ed-7b49cf024a04)

### Steps to reproduce the issue

Create a legend band, set the opacity, add the legend band in a layout.
![immagine](https://github.com/qgis/QGIS/assets/52335835/48638191-9c40-4444-bd1a-6c4b5ccede47)

### Versions

3.28.11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Looks like duplicate of #45131.
