### ISSUE TITLE
Elevation profile does not recognise VPC as an input layer

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#54728]
### What is the bug or the crash?

The elevation profile tool ignores the Virtual Point Cloud and does not generate a profile from the layer.

### Steps to reproduce the issue

1- Open QGIS
2- Add a VPC layer
3- Create an elevation profile from the layer
4- No data is shown in the elevation profile plot area

### Versions

QGIS maste https://github.com/qgis/QGIS/commit/6b371430693

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jsmoreau** [comment]
We hit this limitation last week. Any update on this @wonder-sk ?

**Comment by wonder-sk** [comment]
@jsmoreau no update for now, unfortunately... This is pretty much a missing feature rather than a bug: the code to handle VPCs is simply not there yet. Hopefully we will do another crowdfunding campaign and this is high on my wish list to get sorted...
