### ISSUE TITLE
Natural Neighbor not working

### ISSUE THREAD

**Issue by Ladrigan** [qgis/QGIS#54723]
### What is the bug or the crash?

Hello:
When I run Natural Neighbor to draw contour lines, I get the following error message.

**The following layers were not correctly generated.
• C:/Users/alesm/AppData/Local/Temp/processing_XwJgaV/7a3f5fa309e1479c87afdfb8d9fa3cb4/TARGET_OUT_GRID.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.**

I tried to install Saga separately, but it doesn't work. Neither with version 3.28 of Qgis. Somebody could help me?
Thank you so much.

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/145926782/67bb2e02-a917-410f-acf1-6084f3a4426d)

### Versions

3.32

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Ladrigan, thanks for reporting. The SAGA-GIS processing core plugin is not available in QGIS 3.32. Do you have installed an external plugin in order to use the SAGA-GIS tools in QGIS? Which one? Could you please provide the full processing log? Could you please provide the full QGIS info as requested by the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here.")?

**Comment by Ladrigan** [comment]
I have installed **SAGA-GIS 7.8.2**

QGIS version: 3.32.3-Lima
QGIS code revision: 67d46100b5b
Qt version: 5.15.3
Python version: 3.9.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.5 (git-version: 24f78d)
SAGA Next Gen version: 0.0.7
Algorithm started at: 2023-09-24T23:56:48
Algorithm 'Natural neighbour' starting…
Input parameters:
{ 'FIELD' : 'ele', 'METHOD' : 1, 'POINTS' : 'G:\\.shortcut-targets-by-id\\0B6kLGoM02KzkUUU2NkcyUjlXQVk\\[AUXILIAR]\\99 PROYECTOS TEMPORAL\\CAMANGO PATIÑO\\Topografia\\20230923044347-51045-data.gpx|layername=track_points', 'TARGET_OUT_GRID' : 'TEMPORARY_OUTPUT', 'TARGET_USER_SIZE' : 0.0005, 'TARGET_USER_XMIN TARGET_USER_XMAX TARGET_USER_YMIN TARGET_USER_YMAX' : None, 'WEIGHT' : 0 }

grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -POINTS "C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/8370ed5c8ca340db8769810bb10c3082/POINTS.shp" -FIELD "ele" -TARGET_USER_SIZE 0.0005 -METHOD 1 -WEIGHT 0.0 -TARGET_OUT_GRID "C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/e6ac756d7551426880a39f1fa2c1bc8c/TARGET_OUT_GRID.sdat"

C:\Users\alesm\Documents>set SAGA=C:/OSGeo4W/apps\saga

C:\Users\alesm\Documents>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

C:\Users\alesm\Documents>PATH=C:\OSGeo4W\apps\qgis-rel-dev\bin;C:\OSGeo4W\apps\grass\grass83\lib;C:\OSGeo4W\apps\grass\grass83\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python39\Scripts;C:\OSGeo4W\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

C:\Users\alesm\Documents>saga_cmd grid_gridding "Natural Neighbour" -TARGET_DEFINITION 0 -POINTS "C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/8370ed5c8ca340db8769810bb10c3082/POINTS.shp" -FIELD "ele" -TARGET_USER_SIZE 0.0005 -METHOD 1 -WEIGHT 0.0 -TARGET_OUT_GRID "C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/e6ac756d7551426880a39f1fa2c1bc8c/TARGET_OUT_GRID.sdat"
____________________________

##### ## ##### ##
### ### ## ###
### # ## ## #### # ##
### ##### ## # #####
##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

____________________________
library path: C:\OSGeo4W\apps\saga\tools\
library name: grid_gridding
library : grid_gridding
tool : Natural Neighbour
identifier : 3
author : O.Conrad (c) 2008
processors : 8 [8]
____________________________

Load shapes: C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/8370ed5c8ca340db8769810bb10c3082/POINTS.shp...
Error: DBase file does not contain any records.
failed
Error: input file [C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/8370ed5c8ca340db8769810bb10c3082/POINTS.shp]
Error: Points

Usage: saga_cmd grid_gridding 3 [-POINTS <str>] [-FIELD <str>] [-TARGET_DEFINITION <str>] [-TARGET_USER_SIZE <double>] [-TARGET_USER_XMIN <double>] [-TARGET_USER_XMAX <double>] [-TARGET_USER_YMIN <double>] [-TARGET_USER_YMAX <double>] [-TARGET_USER_COLS <num>] [-TARGET_USER_ROWS <num>] [-TARGET_USER_FITS <str>] [-TARGET_TEMPLATE <str>] [-TARGET_OUT_GRID <str>] [-METHOD <str>] [-WEIGHT <double>]
-POINTS:<str> Points
Shapes, input
-FIELD:<str> Attribute
Table field
-TARGET_DEFINITION:<str> Target Grid System
Choice
Available Choices:
[0] user defined
[1] grid or grid system
Default: 0
-TARGET_USER_SIZE:<double> Cellsize
Floating point
Minimum: 0.000000
Default: 1.000000
-TARGET_USER_XMIN:<double> West
Floating point
Default: 0.000000
-TARGET_USER_XMAX:<double> East
Floating point
Default: 100.000000
-TARGET_USER_YMIN:<double> South
Floating point
Default: 0.000000
-TARGET_USER_YMAX:<double> North
Floating point
Default: 100.000000
-TARGET_USER_COLS:<num> Columns
Integer
Minimum: 1
Default: 100
-TARGET_USER_ROWS:<num> Rows
Integer
Minimum: 1
Default: 100
-TARGET_USER_FITS:<str> Fit
Choice
Available Choices:
[0] nodes
[1] cells
Default: 0
-TARGET_TEMPLATE:<str> Target System
Grid, input, optional, CMD
-TARGET_OUT_GRID:<str> Target Grid
Grid, output
-METHOD:<str> Method
Choice
Available Choices:
[0] Linear
[1] Sibson
[2] Non-Sibsonian
Default: 1
-WEIGHT:<double> Minimum Weight
Floating point
Maximum: 0.000000
Default: 0.000000

C:\Users\alesm\Documents>exit
Execution completed in 3.56 seconds
Results:
{'TARGET_OUT_GRID': 'C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/e6ac756d7551426880a39f1fa2c1bc8c/TARGET_OUT_GRID.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/alesm/AppData/Local/Temp/processing_gfBHER/e6ac756d7551426880a39f1fa2c1bc8c/TARGET_OUT_GRID.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.



QGIS version
3.32.3-Lima
QGIS code revision
67d46100b5b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009




This copy of QGIS writes debugging output.




Active Python plugins
processing_saga_nextgen
0.0.7
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

**Comment by nyalldawson** [comment]
This is a bug with the third party Saga Next Gen plugin, please report at https://github.com/north-road/qgis-processing-saga-nextgen
