### ISSUE TITLE
Point input in graphical modeler doesn’t work

### ISSUE THREAD

**Issue by katagen** [qgis/QGIS#54720]
### What is the bug or the crash?

The input « point » in the graphical modeler doesn’t seem to work.
If you use it, and you start the script, you can click on the 3 dots, but nothing is happening.

### Steps to reproduce the issue

Create a new script
Use point as input, and set for exemple 0,0 as default (to make a test)
Use the algorithm « create layer from point »
Start the script by using the default value, and you get a point layer at 0,0
Restart the script, but click on the 3 dots to click in Qgis screen to set a new value… nothing is happening.

### Versions

LTR 3.28.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by YoannQDQ** [comment]
No sure it's actually a bug.

This only occurs if you run the model from the Model Designer.
If you run the model from the Processing ToolBox, the default value is correctly applied.

Actually, whenever the model is run from the Model Designer, the parameters used for this specific run are saved alongside the model (in the "designerParameterValues" of the model XML).

https://github.com/qgis/QGIS/blob/5d497bc4356102b46d132fd77ae3609f239e1096/python/plugins/processing/modeler/ModelerDialog.py#L148-L155

**Comment by katagen** [comment]
It is not what you said... the tool "point as layer" works in the modeler and in the tool processing, no problem!
The problem is the "point" input, which is specific for the graphical modeler.

**Comment by alexbruy** [comment]
Duplicates #31969.
