### ISSUE TITLE
Pixelated warning icon in Remove Layers dialog on High DPI screens

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#54737]
### What is the bug or the crash?

This is another issue related to High DPI scaling. The warning icon of the *Remove layers and groups* dialog looks blurry/pixelated on Windows when the display scale factor is larger than 100%.

Edit: Appears to be only present with Night Mapping theme

<img src="https://github.com/qgis/QGIS/assets/78353871/27ef1a1f-8658-46a6-ac53-0d059857d876" width="250">

### Steps to reproduce the issue

1. Open or create a QGIS project
2. Add any layer to the project
3. Select the layer in the layers panel
4. Hit Remove Layer/Group (CTRL+D)

### Versions

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
mapswipetool_plugin | 1.2
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
QuickOSM | 2.2.3
QuickWKT | 3.1
SpreadsheetLayers | 2.1.0
db_manager | 0.1.20
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
This is a stock image coming from upstream Qt. With a bit of luck, that'll be fixed in Qt 6. There's nothing much we can do on our end.

**Comment by malbles** [comment]
Seems to be fixed with Qt6 / in QGIS 4.0 ❤️
