### ISSUE TITLE
Cant save properties of features when the  field's type is hstore of postgres 

### ISSUE THREAD

**Issue by github725** [qgis/QGIS#54742]
### What is the bug or the crash?

Cant save properties of new features when the  field's type is hstore of postgres .
when save features more than one
line 2686 of qgspostgresprovider.cpp should judge
value.type() == QVariant::Map

### Steps to reproduce the issue

click savelayer button,when save features more than one and  field's type is hstore of postgres 
then the properties were lost

### Versions

QGIS版本
3.26.1-Buenos Aires
QGIS代码版本
b609df9ed4d
Qt版本
5.15.3
Python版本
3.9.5
GDAL/OGR版本
3.5.1
PROJ版本
9.0.1
EPSG注册数据库版本
v10.064 (2022-05-19)
GEOS版本
3.10.3-CAPI-1.16.1
SQLite版本
3.38.1
PDAL版本
2.3.0
PostgreSQL客户端版本
unknown
SpatiaLite版本
5.0.1
QWT版本
6.1.6
QScintilla2版本
2.13.1
操作系统版本
Windows 10 Version 2009

激活Python插件
addCheck
1.0
data_fusion
0.1
data_matching
0.1
valhalla_test
0.1
auto_edge_joining
1.3
clear_connection
1.2
connectionrelationshipidentification
1.0
Generalizer3
1.0
geohey_toolbox
0.4
lane_centerlines_connection
2.0
lane_object_overlap
1.0
lane_offset
1.0
make_exchange_area_curve
1.0
make_junction_line
3.0
make_trafficcontrol
3.2
mandatory_makelane
1.0
pie_gc_toolbox
1.2.6
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
polygon_builder
1.0
select_re_intersection
0.1
show_relationship
1.0
split_linegeom
1.1
╜╓╛░═╝╞¼▓Θ┐┤▓σ╝■
3.0.3
db_manager
0.1.20
processing
2.12.99

the latesst version

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Can you please attach a minimal SQL data and a step by step description about how to reproduce the issue?
