### ISSUE TITLE
Crash when using labels on layer

### ISSUE THREAD

**Issue by swaxolez** [qgis/QGIS#54747]
### What is the bug or the crash?

QGIS will consistently crash when I turn labels on for a layer.  Started when I upgraded to 3.28.11 LTR from 3.16 LTR. 

### Steps to reproduce the issue

create a new project
import single vector layer
turn on single label for a field
zooming in and out will cause it to crash
no error report.
when run from terminal I see: zsh: trace trap  ./QGIS3

### Versions

QGIS version | 3.28.11-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.43.1
PDAL version | 2.5.6
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.3
OS version | macOS 13.6
  |   |   |  
Active Python plugins
firstaid | 3.0.3
quick_map_services | 0.19.33
latlontools | 3.6.15
plugin_reloader | 0.9.3
PluginLoadTimes | 3.0.2
processing | 2.12.99
sagaprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.28.11-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.10
Python version
3.11.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.43.1
PDAL version
2.5.6
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.3
OS version
macOS 13.6

Active Python plugins
firstaid
3.0.3
quick_map_services
0.19.33
latlontools
3.6.15
plugin_reloader
0.9.3
PluginLoadTimes
3.0.2
processing
2.12.99
sagaprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I can't create a new profile.  Trying to create a new profile will also crash the system.  I've tried cleaning and re-installing.  This is the macports installation.

**Comment by DelazJ** [comment]
> I can't create a new profile. Trying to create a new profile will also crash the system. I've tried cleaning and re-installing. This is the macports installation.

You can go to the active [profile folder](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), cut and paste the folder elsewhere. And restart QGIS: it should create a new profile.

**Comment by swaxolez** [comment]
I tried that originally, but also tried it again.  When I delete all profiles and start GIS it will try to re-create its default profile but crashes immediately

**Comment by swaxolez** [comment]
Here's what I get when starting from the terminal with my profiles folder deleted:

willem@Willems-MacBook-Pro MacOS % ./QGIS3
Warning: Populating font family aliases took 80 ms. Replace uses of missing font family "FreeSans" with one that exists to avoid this cost. 
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
Warning: QWidget::insertAction: Attempt to insert null action
zsh: trace trap  ./QGIS3

**Comment by swaxolez** [comment]
Ok I tried a fresh install with macports on another MacBook M1 and it works well.  I can create profiles, I can use labels.  No issues other than the error you get when first launching.  I think this is a bad macport installation.  I'll close this.
