### ISSUE TITLE
Export Geospatial PDF includes unchecked layers

### ISSUE THREAD

**Issue by Kevin814** [qgis/QGIS#54759]
### What is the bug or the crash?

When exporting GeoSpatial PDF, "unchecked" Layers are included in the PDF Viewer (Adobe Reader).

### Steps to reproduce the issue

1. Go to Map Canvas
2. Create map with different layers
3. Export as GeoSpatial PDF
4. Only check the desired layers

### Versions

QGIS-Version
3.28.6-Firenze
QGIS-Codeversion
868c9fa03b
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.4
PROJ-Version
9.2.0
EPSG-Registraturdatenbankversion
v10.082 (2023-02-06)
GEOS-Version
3.11.2-CAPI-1.17.2
SQLite-Version
3.41.1
PDAL-Version
2.5.2
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
ClipMultipleLayers
3.2.0
coordinates_converter
1.0
DigitizingTools
1.5.2
nominatim
1.4.5
qad
3.0.4
QuickOSM
2.2.2
Save-DXF
0.1
SRTM-Downloader
3.1.17
weissflaechenkartierung
3.1.4
zoomtopaste
3.0.3
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Kevin814, thanks for reporting.
Could you please better specify in details what is the expected output and what is the actual output?
If you are referring to the "Layer Structure" section and the "Initially Visible" check-boxes
![image](https://github.com/qgis/QGIS/assets/16253859/bb946e91-8076-4ce9-b0f3-057c871fd93b)
then those check-boxes are not intended to exclude layers from the exported PDF, but to make such layer only initially not visible.
Could you please provide a sample project and sample layers and PDF export parameter and exported PDF?

**Comment by Kevin814** [comment]
Unfortunately, I cannot provide a sample project. 

I have a project with about 30 layers. From these 30 layers, about 5 are ticked and visible in map canvas. 
In the export window, QGIS lists all 30 layers. Boxes for "initially visible" and "attributes" are randomly selected/unselected. 
Some layers which are selected in the export window are not even active in map canvas. 

If I untick the undesired layers and keep the desired ones (which are also visible in map canvas), QGIS creates a pdf map that includes some of the unselected/inactive layers (which are listed but with no data behind) and some of the selected/active layers. However, some of the selected layers, which should be initially visible, are not in fact.
