### ISSUE TITLE
Crash in Data Source Manager | Geopackage | Set Filter

### ISSUE THREAD

**Issue by solisgb** [qgis/QGIS#54755]
## User Feedback

In Data Source Manager | Geopackage | Set Filter and suddenly Qgis crashed

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000047d0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QStandardItem::text :
QgsProjectStorageGuiProvider::QgsProjectStorageGuiProvider :
QgsAbstractDbSourceSelect::filterResults :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Data Source Manager
2.  Geopackage
3.  Set Filter

### Versions

QGIS version
3.28.11-Firenze
QGIS code revision
b02458a196
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Cannot reproduce on current master.

**Comment by pathmapper** [comment]
I've seen a similar crash report and using a new profile fixed it.

**Comment by pathmapper** [comment]
@solisgb does your "thumb up" means with a new QGIS profile the crash doesn't happen anymore?

**Comment by solisgb** [comment]
It means that I appreciate the proposal and it is an idea that I will consider. First, I will continue with my current profile to test if a crash occurs again; if it does, I will try a new profile. So far, the crash has not happened to me again, but it is an operation I do not perform frequently.
