### ISSUE TITLE
Not possible to create a new geometry part with "Add part" tool

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#54762]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/20856381/c39b504a-4a92-4451-839b-c164f11cd46b)

### Steps to reproduce the issue

1. Create a new temporary scratch layer of type `MultiPolygon`.
2. Draw a polygon using "Add Polygon Feature" tool.
3. Select the drawn feature.
4. Select "Add part" tool.
5. Draw another geometry.
6. When saving the geometry there is always the message: "New part's geometry is empty or invalid"

### Versions

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5b
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.8.0dev-5c11a8f34f
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pathmapper** [comment]
Not reproducible in `master`.

**Comment by agiudiceandrea** [comment]
Already prevously reported and fixed with PR https://github.com/qgis/QGIS/pull/54611.
