### ISSUE TITLE
When I choose the screen blend mode my maps disappear 

### ISSUE THREAD

**Issue by sabasasa** [qgis/QGIS#54763]
### What is the bug or the crash?

After assigning a pseudocolor styling to my bands, from Landsat (B2, B3, B4 in this case) and then try to switch the the screen blend mode I lose the map. It happens with a number of other blend mode options that I tried, but not all. 
What is happening? 

### Steps to reproduce the issue

1. Go to Layer Styling
2. click on blend mode
3. scroll down to 'screen' and select
4. see error

### Versions

I tried this in both 3.26.2 and 3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is expected. See https://docs.qgis.org/3.22/en/docs/user_manual/introduction/general_tools.html#blend-modes "Screen: Light pixels from the source are painted over the destination, while dark pixels are not. This mode is most useful for mixing the texture of one item with another item (such as using a hillshade to texture another layer).".
