### ISSUE TITLE
Occasional corruption of tab-delimited text layer when loading QGIS-file

### ISSUE THREAD

**Issue by mrindholt** [qgis/QGIS#54785]
### What is the bug or the crash?

I often load tab separated .csv files into QGIS, but when opening a QGIS file, occasionally the delimited text layer seems corrupted because an error in the loading of the .csv file.

It seems like the delimiter for tab in the source URI is changed from the HEX value of **%5Ct** to the ASCII value of **\t**, which by in my case is interpreted as if the delimiter is **t**.

### Steps to reproduce the issue

**Note**
Both the QGIS file and .csv file are located on a network drive, we have at my workplace, so it is accessed by both me and my coworkers, but always from the same location (Drive letter).

**Procedure to reproduce** 
Load a tab delimited .csv file into QGIS as a delimited text layer, and save the QGIS file.

The error orccurs sometimes when the QGIS file is opened, and the delimited text layer is loaded. Sometimes on the same computer and version of QGIS but not always. Sometimes also when loaded from a different computer with the same or a different version of QGIS, but also not always.

The occation that made me create this issue, the .csv file was loaded on one computer with a newer version of QGIS, but then the QGIS file was loaded from another computer with a slightly older version og QGIS.

### Versions

Last occation was on version 3.22.10, when loaded a QGIS file from version 3.28.9, but also experienced solely on 3.28.9 and other previous versions.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It can be fixed by manually change the delimiter **\t** back to it's HEX value **%5Ct** in the source URI.

**Comment by agiudiceandrea** [comment]
@mrindholt, thanks for reporting. Could you please specify the content of your QGIS Help->About menu as requested in the issue report form? ("QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here.")
Could you please provide a sample project with a sample layer with which the issue does occur?

@elpaso this seems this issue report may have something in common with the previous issue report https://github.com/qgis/QGIS/issues/48587 which you fixed with PR https://github.com/qgis/QGIS/pull/51881.

**Comment by mrindholt** [comment]
Current version of QGIS, where the error last occured:

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009


Active Python plugins
changeDataSource
3.1
Dataforsyningen
0.4
FreehandRasterGeoreferencer
0.8.3
geosearch_dk
2.0.0
qgiscloud
3.8.13
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by mrindholt** [comment]
@agiudiceandrea in the Data Source Manager, I add a Delimited Text layer and select my .csv file, which I have exported from Excel with _windows 1252_ encoding. I select _Custom delimiters_ and _Tab_ as the delimiter. In _Records and Fields Options_ I select _First record has field names_, _Detect field types_ and _Decimal separator is comma_. There is no geometry in my file, as it is being joined with another layer, containing the geometry features.

**Comment by agiudiceandrea** [comment]
Thanks @mrindholt. Could you please provide a sample project with a sample layer with which the issue does occur?

**Comment by elpaso** [comment]
@agiudiceandrea Please ping me if you can reproduce, I might have a look.

**Comment by mrindholt** [comment]
I didn't know the best way to share a sample project, so I've uploaded the files a folder on Sharepoint:
https://dfpamba-my.sharepoint.com/:f:/g/personal/mr_dfp_dk/Ev5Yu1MtpMxNrXppnoUJmDgBnyVkPN2SFfDgwRivMFBU8A?e=0kb9fh

**Comment by agiudiceandrea** [comment]
> I didn't know the best way to share a sample project,

@mrindholt, the best way is to put it and the relevant files in a zip file and attach the zip file to a comment.

**Comment by agiudiceandrea** [comment]
I've downloaded the provided files (now attached [QGIS-test.zip](https://github.com/qgis/QGIS/files/13052778/QGIS-test.zip) to this comment for future reference).

I've put the "Tabsberegner_eksport.csv" file in the folder at "F:\Ledningsdimensionering\" (which is on a local hard drive).
I don't see any issue opening the project file QGIS-test.qgz using either QGIS 3.33.0 or QGIS 3.28.9.

**Comment by mrindholt** [comment]
@agiudiceandrea if you look in the Source URI what is your delimiter?

**Comment by agiudiceandrea** [comment]
It is `delimiter=%5Ct;`: `file:///F:/Ledningsdimensionering/Tabsberegner_eksport.csv?encoding=windows-1252&type=csv&delimiter=%5Ct;&maxFields=10000&detectTypes=yes&decimalPoint=,&geomType=none&subsetIndex=no&watchFile=no`
