### ISSUE TITLE
Export produces huge PDF file when label mask are enabled in 3.28.11 compared to 3.22.16

### ISSUE THREAD

**Issue by jeremieprudhomme** [qgis/QGIS#54788]
### What is the bug or the crash?

With the same project file, opened in 3.22.16 and 3.28.11, I am getting a huge difference in file size when exporting to PDF.
1 Mb vs 100 Mb.

Only the case when I activate the label mask.

### Steps to reproduce the issue

Add a mask on the label of layer A.
Activate it on the mask tab in the properties of layer B.

If activated, the PDF export is very long and produces huge PDF in 3.28.11, not in 3.22.16.

### Versions

Version de QGIS
3.28.11-Firenze
Révision du code
b02458a196
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.2
Version de Proj
9.3.0
Version de la base de données du registre EPSG
v10.094 (2023-08-08)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
active_fire
0.3
CustomSVG
0.1
DigitizingTools
1.5.0
french_locator_filter
1.0.4
GroupStats
2.1.5
ImportPhotos
3.0.5
latlontools
3.6.15
lizmap
3.14.1
lockzoom
3.0.3
mask
1.10.2
MemoryLayerSaver
4.0.4
menu_from_project
v2.0.8
nominatim_locator_filter
0.2.4
OSMDownloader
1.0.3
PluginLoadTimes
3.0.1
processing_saga_nextgen
0.0.7
project_report
1.2
qfieldsync
3.1.5
qgis2web
3.16.0
qgis_preview_mode_plugin
0.1.0
QNEAT3
1.0.4
quick_map_services
0.19.11.1
refFunctions
1.6
SpreadsheetLayers
2.1.0
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

With a new profile, QGIS crashed during the export.

Test project downloadable : https://acloud.zaclys.com/index.php/s/aK2cZGTjYt4gHA4

Layer "Centre d'incendie et de secours" has a label mask
Layers Commune and Département have the mask activated with the label mask of "Centre d'incendie et de secours".

**Comment by agiudiceandrea** [comment]
@jeremieprudhomme, thanks for reporting. Could you please specify all the options set in the PDF Export Options window before exporting the layout to PDF?
I've tested the provided project file and gpkg layer file: on Windows, exporting the layout to PDF makes QGIS 3.28 and 3.33.0-Master crash, while it succeeds using QGIS 3.22.

**Comment by jeremieprudhomme** [comment]
I've tested different settings (but not the GeoPDF) : 
- Always export as vector checked or not
- Add georeferencing informations checked or not
- Export RDF metadata checked or not
For Text export I always left the default recommanded option "Always export as path"
For the image compression I always left the option "Lossy (JPEG)"
In the advanced options, I left unchecked the option to desactivate the export of tiled raster layers (I don't have such a layer)
I left checked the option to simplify the geoms to reduce fil size.

Hope this helps.
I didn't checked if the option names I wrote in this post are the correct ones, my QGIS is in French and I translated them litteraly, I think they are understandable :)
