### ISSUE TITLE
AWS S3 Raster CRS projection shift

### ISSUE THREAD

**Issue by searchant01** [qgis/QGIS#54794]
### What is the bug or the crash?

When adding a Raster layer (.tif) from AWS S3  , QGIS 3.28.11 produce a offset from local Raster file in both EW and NS direction.

### Steps to reproduce the issue

1. Go to 'Layer'
2. Clicke on 'Add Layer' -> 'Add Raster Layer'
3. Source Type - Protocol: HTTP(s),cloud,etc.
4. Type AWS S3
5. Type in Bucket and Object Key

### Versions

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
qgis-plugin-findreplace-main
1
quick_map_services
0.19.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by NyakudyaA** [comment]
Can you add gdalinfo of the raster stored in s3, a screenshot of the crs info when the layer is loaded in QGIS and perhaps the link to the bucket if it's public.

If you download the raster and load it directly does the shift occur?

**Comment by searchant01** [comment]
unfortunately the bucket is not public.
After download the raster from S3 and load it to QGIS. the image shift to new location (from North America to south America). The image CRS changed after uploading to S3 and downloading from S3.

**Comment by NyakudyaA** [comment]
If the CRS info changed after uploading to s3 then QGIS is not to blame here. QGIS is basically reading info as it is from the bucket. I think you need to identify how the CRS is changing and how are you pushing the raster to the bucket.
