### ISSUE TITLE
QGIS crashes after executing plugin, even though it runs until return.

### ISSUE THREAD

**Issue by tiagoacarvalho** [qgis/QGIS#54791]
## User Feedback

Happens every time the attached script is executed.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00006124 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QObject::thread :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
pdal::Option::getName :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Open the following plugin script in QGIS
[script and inputs.zip](https://github.com/qgis/QGIS/files/12768581/script.and.inputs.zip)
2. Parameters as follows:
![image](https://github.com/qgis/QGIS/assets/52931413/d347406f-e935-4f91-b3dc-bbe493b9b097)
3. Click execute
4. If plugin window closes, it will crash after running (even though an output appears)

### Versions

QGIS Info
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by tiagoacarvalho** [comment]
On further debugging, found that the "it will crash" state happens after around 150 pixels processed.

**Comment by pathmapper** [comment]
Could be a threading issue, try this version [mdtreco_FlagNoThreading.zip](https://github.com/qgis/QGIS/files/12770014/mdtreco_FlagNoThreading.zip) where I added:

```
def flags(self):
    return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```
