### ISSUE TITLE
Export to MapInfo .tab file change coordinates of objects 

### ISSUE THREAD

**Issue by rswmajor** [qgis/QGIS#54795]
### What is the bug or the crash?

When exporting to the format MapInfo .tab file, the coordinates of objects change.

### Steps to reproduce the issue

Open the .gpkg layer. Right click "Export - Save objects as". Format MapInfo TAB.

https://github.com/qgis/QGIS/assets/19249084/dba92469-6cb5-40cc-a1e8-e2e5afc1a97a

### Versions

Версия QGIS
3.32.3-Lima
Ревизия
67d46100b5
Версия Qt
5.15.3
Версия Python
3.9.5
Версия GDAL/OGR
3.7.2
Версия PROJ
9.3.0
Версия базы данных реестра EPSG
v10.094 (2023-08-08)
Версия GEOS
3.12.0-CAPI-1.18.0
Версия SQLite
3.41.1
Версия PDAL
2.5.5
Версия PostgreSQL
15.2
Версия SpatiaLite
5.1.0
Версия QWT
6.1.6
Версия QScintilla2
2.13.4
Версия ОС
Windows 10 Version 2009

Включенные модули Python
coord_list2
0.31х
latlontools
3.6.15
lftools
1.12.1
numericalDigitize
0.4.7
plugin_reloader
0.9.3
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rswmajor** [comment]
[map-test.zip](https://github.com/qgis/QGIS/files/12775087/map-test.zip)

**Comment by blacktesta** [comment]
@rswmajor MAPINFO TAB file requies defining BOUNDS parameter which affects the accuracy of coordinates. Try to set right BOUNDS parameter for your layer.

**Comment by rswmajor** [comment]
> @rswmajor MAPINFO TAB file requies defining BOUNDS parameter which affects the accuracy of coordinates. Try to set right BOUNDS parameter for your layer.

Thank you. Defining boundaries solves the problem. Can be closed
