### ISSUE TITLE
Topology Checker crash with change in parameters or area

### ISSUE THREAD

**Issue by DrRichLangford** [qgis/QGIS#54801]
## User Feedback

Regardless of the size of the layer, this happens a lot when I change the Topology Checker area, or choose a different parameter. It happens most after finding a lot of gaps, then looking for something else.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001c74 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QVariant::QVariant :
version :
QAbstractProxyModel::headerData :
QSortFilterProxyModel::headerData :
QHeaderView::paintSection :
QHeaderView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QProgressDialog::setValue :
QObject::qt_static_metacall :
version :
version :
version :
version :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf63
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Vector --> Topology Checker
![image](https://github.com/qgis/QGIS/assets/136798905/dbd4122f-32ed-42ba-9236-53daf47a7afb)
Validate extent
![image](https://github.com/qgis/QGIS/assets/136798905/d0f7c55b-b719-4eaf-a29d-1a30d37b6b61)
"must not overlap" frozen at 1%
"Abort" not responding...
Or, the system crashes.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf63
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
autoSaver | 2.6
HCMGIS | 23.7.19
mmqgis | 2021.9.10
processing_saga_nextgen | 1.0.0
realcentroid | 1.0.3
splitmultipart | 1.0.0
SwapVectorDirection | 0.9
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf63](https://github.com/qgis/QGIS/commit/4a078ecf63)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
autoSaver
2.6
HCMGIS
23.7.19
mmqgis
2021.9.10
processing_saga_nextgen
1.0.0
realcentroid
1.0.3
splitmultipart
1.0.0
SwapVectorDirection
0.9
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@DrRichLangford, thanks for reporting. Could you please provide a sample layer and exact steps and options for which the issue does occur?

**Comment by nyalldawson** [comment]
Related ticket: https://github.com/qgis/QGIS/issues/53425
