### ISSUE TITLE
Deleting QgsRendererRange when a symbol is shared causes the crash of QGIS under Python console

### ISSUE THREAD

**Issue by jhpark16** [qgis/QGIS#54804]
### What is the bug or the crash?

When I shared a symbol to create QgsRendererRange under the Python console, a delete operation on QgsRendererRange crashed QGIS.
I believe the (default) destructor of QgsRendererRange does not check whether it can destory the symbol or not.
The destructor of QgsRendererRange should check whether it is safe to delete the symbol. In this case, the second deletion caused the crash. Although it is possible to warn users about this behaviour by updating the document, I believe it is not an ideal solution.

### Steps to reproduce the issue

To run this script, you need to a have a loaded vector layer.
Open Plugins->Python console, click show editor, paste the the code in this section on the editor, and run. QGIS will crash.
If you copy symbol inside the loop, QGIS will not crash.

project = QgsProject.instance()
num_classes = 2
rangeLst = []
# vec1 = QgsVectorLayer('Temp.shp', 'Temp', "ogr")
vec1 = project.mapLayer(list(project.mapLayers().keys())[0])
symbol1 = QgsSymbol.defaultSymbol(vec1.geometryType())
for idx1 in range(num_classes):
	# symbol1 = QgsSymbol.defaultSymbol(vec1.geometryType())
	v1, v2 = 0.001+idx1*0.07,0.001+(idx1+1)*0.07
	qcRange = QgsClassificationRange('{:.2f} - {:.2f}'.format(v1,v2),v1,v2)
	rangeLst.append(QgsRendererRange(qcRange, symbol1))

del(rangeLst)

### Versions

Bugs are found in QGIS 3.28.11 and 3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is expected -- ownership of the symbol is transferred to QgsRendererRange, so by re-assigning the same symbol instance to a new range you'll get double ownership, and a crash.

Solution is to use a clone:

    rangeLst.append(QgsRendererRange(qcRange, symbol1.clone()))

**Comment by jhpark16** [comment]
Dear Nyall Dawson,

I checked the C++ code and understood this was an expected behaviour.
For a C++ programming paradigm, this behaviour is acceptable but it is not
acceptable in the Python paradigm. In Python, everything is expected to be
managed automatically.
Python is the main script language for QGIS and this behaviour without any
documentation is time consuming and frustrating. Even if you update the
documentation, many Python programmers would be frustrated with this
behaviour. The only message I got was "Kernel crash" in Python and, due to
slow garbage collection, the location of Kernel crash is not constant.
Without C++ programming background, it is difficult to troubleshoot this
issue. Either there should be a clear warning in the document or it should
be automatically managed. I believe the second option is the better one in
this case.

Regards,
Jungho Park

**Comment by nyalldawson** [comment]
> but it is not  acceptable in the Python paradigm

I agree that it's not desirable, but it's the nature of the PyQGIS api and the fix is far from trivial. It ideally belongs in the underlying SIP python binding generator -- it should raise an exception here with a message like "cannot transfer ownership of symbol1, this object is already owned by another c++ object" (or similar). 

I tried to workaround this downstream a couple of years ago (see https://github.com/nyalldawson/QGIS/commit/b618ef10c3906f4cda8757a8cc842772e83db5da), but I'm not confident that it's the right approach and would also need to applied in all the places ownership is transferred in PyQGIS (ie 100's of methods). 

Maybe this a potential project for a future QGIS funding grant... :thinking:
