### ISSUE TITLE
Color Ramp for Raster is Not Displaying Properly

### ISSUE THREAD

**Issue by maellevd** [qgis/QGIS#54818]
### What is the bug or the crash?

We are currently facing an issue related to the Color Ramp for raster layers: the intermediate colors in QGIS's default palettes are missing and appear as transparent. While it is possible to edit each color individually, this process is time-consuming. 

### Steps to reproduce the issue

1.Lload a raster
2. Change the Render type to Singleband pseudocolor. Select Color ramp

![Bug_QGIS_colorRamp](https://github.com/qgis/QGIS/assets/37191185/1ccd0e8c-e9df-41d9-bbe5-3481c041260f)
![QGIS-bug-Transparent](https://github.com/qgis/QGIS/assets/37191185/fa9cace9-e514-4655-b7d8-25a0e83ca120)

### Versions

We have installed version QGIS 3.22.4 for our students, as it comes pre-installed on Ubuntu 22.04 (Jammy) by default (due to a bug in graded classification on QGIS ≥ 3.28.5 (cf.https://github.com/qgis/QGIS/issues/53745).

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

We tried to reinstall QGIS but we still have the issues. It appears that this problem has been occurring since QGIS 3.22.16 (refer to https://gis.stackexchange.com/questions/452348/qgis-color-ramp-is-not-being-displayed-properly).

**Comment by nyalldawson** [comment]
3.22 is no longer supported -- there will not be any more releases of this version. You'll need to instead focus on the issues preventing you from running the latest supported releases.
