### ISSUE TITLE
Snapping defunct after mouse move when processing

### ISSUE THREAD

**Issue by strokovnjaka** [qgis/QGIS#54828]
### What is the bug or the crash?

Snapping to vertices becomes defunct when mouse is moved while processing point feature insertion at the clicked location. Subsequently snapping does not work for some vertices, while it does for others.

### Steps to reproduce the issue

I have a plugin that uses snapping to vertices for inserting nodes and edges. After e.g. a node is inserted, some processing takes place (lasting about 1s). 
If I move the mouse pointer during that time, snapping becomes defunct: it does not work for some vertices.
If I then use the QGIS's own "Add point feature" tool the behavior is the same.
To make snapping work ok again, I have to e.g. add another feature point and not move the mouse while processing takes place.

### Versions

```
QGIS version
3.32.1-Lima
QGIS code revision
4a078ecf
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
firstaid
3.0.3
ONaNiNO-dev
0.5.1-dev
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
```

and

```

QGIS version
3.33.0-Master
QGIS code revision
99608cedac
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0dev-949ac934a6
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




This copy of QGIS writes debugging output.




Active Python plugins
firstaid
3.0.3
ONaNiNO-dev
0.5.1-dev
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@strokovnjaka, thanks for reporting. Does the issue only occur using the external plugin (which plugin?) tool? If yes, then you may need to report the issue to the plugin author.

**Comment by strokovnjaka** [comment]
@agiudiceandrea, yes I only managed to reproduce this with an external plugin. As I am the plugin's author, I debugged it but  everything seems by the book, at least to my knowledge. 
My reasoning is that even if my plugin left QGIS in a state that snapping is defunct, at least error should be reported by QGIS (when that state was reached).

I would appreciate any ideas on how to check what I could be doing wrong in the plugin.

**Comment by agiudiceandrea** [comment]
@strokovnjaka, if you think you found a bug in QGIS, please provide everything (code/steps) needed to replicate the issue in order to let a QGIS developer to find the cause of the bug, if any, and fix it.
If you need help for developing/debugging your plugin, you could submit the questions to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or to other support forums such as https://gis.stackexchange.com/ or to the qgis-developer mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-developer
