### ISSUE TITLE
Browser - Error listing tables

### ISSUE THREAD

**Issue by robbitt** [qgis/QGIS#54821]
### What is the bug or the crash?

In the browser pane, if I right-click on a layer within an expanded geopackage - I get popup error like: 
`Error listing tables from (path to my particular gpkg): Error executing SQL SELECT c.table_name, data_type, description, c.srs_id, g.geometry_type_name, g.column_name FROM gpkg_contents c LEFT JOIN gpkg_geometry_columns g ON (c.table_name = g.table_name) WHERE c.table_name NOT IN ("ogr_empty_table"): Could not open (path to my particular gpkg)`

### Steps to reproduce the issue

1). In the QGIS Browser - Create a new geopackage
2). Copy many layers into this geopackage
3). Right-click on any layer within the expanded geopackage

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.32.3-Lima
QGIS code revision
[67d46100b5](https://github.com/qgis/QGIS/commit/67d46100b5)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I disabled all plugins - and this error persisted.

**Comment by nyalldawson** [comment]
Can you share the gpkg? I can't reproduce this.

**Comment by robbitt** [comment]
Hi @nyalldawson - thanks for your help. I put a copy of the offending gpkg here: [https://www.sacramentoriver.org/forum/temp/my_files/GIS_open_garbage.gpkg](https://www.sacramentoriver.org/forum/temp/my_files/GIS_open_garbage.gpkg)

**Comment by robbitt** [comment]
I hope this doesn't go stale
