### ISSUE TITLE
Visual Style preventing feature highlighting when Identify Results is active

### ISSUE THREAD

**Issue by beyhh** [qgis/QGIS#54830]
### What is the bug or the crash?

When using the _Identify Features_ tool from the _Selection Toolbar_, the feature gets highlighted in red when hovering over the item in the selection list. However, once the feature is selected and the information is being displayed in the _Identify Results_ window/panel, the feature is no longer highlighted with a red outline, as it used to be in the past. Looking at the Identify Results window/panel you cannot tell to which feature this information is relating to. This undesired behaviour is observed when a layer from a PostgreSQL source is used. 

**Note:** _It seems that only a specific layer is having this problem. If I change the visual style to one of the QGIS default ones the highlighting actually works. It seems as if a certain configuration of the visual style prohibits the highlighting of the feature. I therefore attach the style file to the post._

[Style_RESARE.zip](https://github.com/qgis/QGIS/files/12813409/Style_RESARE.zip)

### Steps to reproduce the issue

- Have several objects with properties in the chart canvas. 
- Activate the Identify Features tool from the Selection Toolbar
- Right-click on feature and select the object from the context menu for displaying the Identify Results window
  (Note: the feature gets highlighted in red while hovering over the list item in the context menu)
- Click on the list item to open the Identify Results for this feature, 
- The highlighting of the feature disappears

![image](https://github.com/qgis/QGIS/assets/66669404/43feed9d-34b3-412d-a433-f346833117b7)

![image](https://github.com/qgis/QGIS/assets/66669404/18032754-7bdf-48ca-87c4-908125bd17eb)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.10-Firenze | QGIS code revision | e2edb9c468
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.5.0
db-style-manager | 0.8
DigitizingTools | 1.5.2
latlontools | 3.6.15
layerGroupFilter | 0.2
mmqgis | 2021.9.10
multiple_layers_tools | 1.2
postgis_geoprocessing | 0.9
quick_map_services | 0.19.33
shapetools | 3.4.14
splitmultipart | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.10-Firenze
QGIS code revision
[e2edb9c468](https://github.com/qgis/QGIS/commit/e2edb9c468)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.5.0
db-style-manager
0.8
DigitizingTools
1.5.2
latlontools
3.6.15
layerGroupFilter
0.2
mmqgis
2021.9.10
multiple_layers_tools
1.2
postgis_geoprocessing
0.9
quick_map_services
0.19.33
shapetools
3.4.14
splitmultipart
1.0.0
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Can you attach a screencast showing this issue? I've tried to reproduce and it all works correctly for me.

**Comment by beyhh** [comment]
Thank you for investigation Nyall! 
I should have added that I'm using layers fetched from a PostgreSQL source. Maybe that makes the difference. 
The behaviour is then as shown in the screenshots.

**Comment by nyalldawson** [comment]
Ok, I can reproduce now. It has to be a very transparent symbol for the issue to kick in.
