### ISSUE TITLE
Processing Toolbox / Slope fails to run - MINUSERPIXELVALUE must be specified

### ISSUE THREAD

**Issue by Malvineous** [qgis/QGIS#54848]
### What is the bug or the crash?

Running a number of different GDAL algorithms currently seems to be failing.  It looks like GDAL has a new mandatory variable that QGIS is not specifying, causing many operations to fail.  Slope calculation is one of them, which produces this output:
```
QGIS version: 3.33.0-Master
QGIS code revision: 5566e42635
Qt version: 5.15.10
Python version: 3.11.5
GDAL version: 3.7.2
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.0, September 1st, 2023
PDAL version: 2.5.6 (git-version: Release)
Algorithm started at: 2023-10-05T15:21:20
Algorithm 'Slope' starting…
Input parameters:
{ 'INPUT' : '/path/to/file.tif', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'Z_FACTOR' : 1 }

Execution completed in 0.04 seconds
Results:
{'OUTPUT': '/tmp/processing_Drwntf/301448acddc346e0b470fbdd488e000d/OUTPUT.ter'}

Loading resulting layers
The following layers were not correctly generated.
• /tmp/processing_Drwntf/301448acddc346e0b470fbdd488e000d/OUTPUT.ter
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```
The error is not very descriptive (and there is no information in the Log Messages Panel), but if I copy the qgis_process command and run that I get more detail:
```
qgis_process run native:slope --distance_units=meters --area_units=m2 --ellipsoid=EPSG:7030 --INPUT=/path/to/file.tif --Z_FACTOR=1 --OUTPUT=TEMPORARY_OUTPUT

----------------
Inputs
----------------

INPUT:  /path/to/file.tif
OUTPUT: TEMPORARY_OUTPUT
Z_FACTOR:       1

Using ellipsoid:        EPSG:7030
Using distance unit:    meters
Using area unit:        square meters

ERROR 5: MINUSERPIXELVALUE must be specified.

----------------
Results
----------------

OUTPUT: /tmp/processing_RPUPab/37448435d2894a6cada29991cf417849/OUTPUT.ter
```

I get this same error about `MINUSERPIXELVALUE` for other things too, such as merging rasters.  In the raster merge window I can add the variable manually and that solves the error, but it looks like it may need to be added as some sort of default supplied everywhere unless otherwise overridden by the user?

### Steps to reproduce the issue

1. Processing Toolbox, Slope
2. Pick any layer, Run
3. Failure

### Versions

Tried with current release and git master.

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.33.0-Master | QGIS code revision | 5566e42635
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.43.1
PDAL version | 2.5.6
PostgreSQL client version | 15.4
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
profiletool | 4.2.6
MetaSearch | 0.3.6
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.33.0-Master
QGIS code revision
[5566e42635](https://github.com/qgis/QGIS/commit/5566e42635)
Qt version
5.15.10
Python version
3.11.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.43.1
PDAL version
2.5.6
PostgreSQL client version
15.4
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Arch Linux

Active Python plugins
profiletool
4.2.6
MetaSearch
0.3.6
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Looking at the GDAL docs, this is obviously a format specific thing so there is no need to change anything on the QGIS side. In your case it is enough to specify `MINUSERPIXELVALUE` and `MAXUSERPIXELVALUE` creation options when running algorithm(s).

**Comment by Malvineous** [comment]
That's strange, because this worked before when I used the same formats a few months ago.

There is no way that I can see to specify these values in the Slope tool - how do you specify MINUSERPIXELVALUE?

**Comment by Malvineous** [comment]
@alexbruy Should I open a new bug report for this?  I asked on the qgis-users list but nobody seems to know how to specify MINUSERPIXELVALUE for the slope plugin so it looks like the option to specify custom variables is missing, if that's how you're meant to do it with recent versions.
