### ISSUE TITLE
Extract by attribute: allow operator 'in'

### ISSUE THREAD

**Issue by bru500** [qgis/QGIS#54857]
### Feature description

In model builder I use the Extract by attribute tool. I need to extract all features with one of 12 different Codes. Therfore I need something like: 'ZONENCODE' IN 1,2,3,6,7,9,15,18,20,23,17,32. It is painful to do 12 diffrent extractions and then to do an union. 

Of course I can add a filter to a layer and then export it. But this is not possible in model builder.

### Additional context

The same should be possible in the tool Select by attribute.

**Comment by roya0045** [comment]
Why not use extract by expression instead.

**Comment by nirvn** [comment]
Closing as this is already implemented in the extract by expression algorithm.
