### ISSUE TITLE
"Generate XYZ tiles (Directory)" ignores BACKGROUND_COLOR when outputting JPG

### ISSUE THREAD

**Issue by mryellow** [qgis/QGIS#54876]
### What is the bug or the crash?

When selecting JPG output for "Generate XYZ tiles (Directory)" the generated images do not have the intended background colour.

### Steps to reproduce the issue

* Set `'BACKGROUND_COLOR'` + JPG output
* Resulting images have background of `#fff`

### Versions

QGIS version: 3.10.14-A Coruña (Most recent available on Debian Bullseye)
Qt version: 5.15.2
GDAL version: 3.2.2
GEOS version: 3.9.0-CAPI-1.16.2
PROJ version: Rel. 7.2.1, January 1st, 2021

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
3.10 is not supported, you must test with the latest release, LTR and/or master

**Comment by mryellow** [comment]
Story of my life.

**Comment by mryellow** [comment]
Stalebots are never helpful.

**Comment by nirvn** [comment]
@mryellow , a fix will make its way into upcoming QGIS 3.34 as well as the current LTR branch (3.28).

In the future, I suggest you try to engage in a more polite/less sarcastic way. @alexbruy was giving you a useful step for you to undertaken that would have helped confirming this as being an issue sooner.
