### ISSUE TITLE
Error when clipping by layer mask

### ISSUE THREAD

**Issue by laurasanttoss** [qgis/QGIS#54873]
Hello, I'm having problems trying to crop an INPE image by the layer mask of a vector file in qgis. When I try, the following error appears:

GDAL command output:
ERROR 1: Key Unknown-0 of TIFFTagLocation=0 has count=0, whereas only 1 is legal.
ERROR 1: Key Unknown-0 of TIFFTagLocation=0 has count=0, whereas only 1 is legal.
Warning 1: C:/Users/laura/Downloads/09S375ZN/09S375ZN.tif: GeoTIFF tags apparently corrupt, they are being ignored.
ERROR 1: Cannot compute bounding box of cutline. Cannot find source SRS
Process returned error code 1

The following message appears in the message log panel: 2023-10-04T19:15:42 INFO gdalwarp -overwrite -of GTiff -cutline "C:\\Users\\laura\\Desktop\\banco_dados_qgis\\Mapas PIBEX\\ Vetorizacao_Faz_Urumbeta_Final.shp" -cl Vetorizacao_Faz_Urumbeta_Final -crop_to_cutline C:/Users/laura/Downloads/09S375ZN/09S375ZN.tif C:/Users/laura/Desktop/banco_dados_qgis/arquivos_raster/faz_urumbeta_recortado.t if

**Comment by alexbruy** [comment]
Please attach raster you are trying to clip.

Looking at the error
```
ERROR 1: Cannot compute bounding box of cutline. Cannot find source SRS
```
I suspect your raster is not georeferenced.
