### ISSUE TITLE
Existing style not overwritten in postgis database (QGIS 3.28)

### ISSUE THREAD

**Issue by linea974** [qgis/QGIS#54884]
### What is the bug or the crash?

When an existing style is saved in public.layer_styles table, a message appears to confirm to overwrite it but a new record is added to the table. The only difference with the original record is the id column.

On this page :
[https://api.qgis.org/api/classQgsVectorLayer.html#a194c677ac41de3bf8c96cee237527305](url)

I found this :

> Note
Prior to QGIS 3.24, this method would show a message box warning when a style with the same styleName already existed to confirm replacing the style with the user. Since 3.24, calling this method will ALWAYS overwrite any existing style with the same name. Use [QgsProviderRegistry::styleExists()](https://api.qgis.org/api/classQgsProviderRegistry.html#a1b8c92b9ccfb75c07ddb2f139f4f76d8) to test in advance if a style already exists and handle this appropriately in your client code.

Is it the origin of the issue ?

On QGIS 3.22 the style is correctly overwritten

### Steps to reproduce the issue

- On layer style dialog, save current style
- Choose in Postgres database option
- Enter the existing style name
- Confirm overwriting
- A new record is added to layer_style table

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.28.5-Firenze | Révision du code | 50adba36f2
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.6.3
Version de Proj | 9.2.0
Version de la base de données du registre EPSG | v10.082 (2023-02-06)
Version de GEOS | 3.11.2-CAPI-1.17.2
Version de SQLite | 3.41.1
Version de PDAL | 2.5.2
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
db-style-manager | 0.8
DigitizingTools | 1.5.2
lockzoom | 3.0.3
map-units-per-pixel | 0.2.1
menu_from_project | v2.0.8
numericalDigitize | 0.4.7
qfieldsync | v4.6.0
qgis2web | 3.16.0
QMetaTiles | 1.5
QNEAT3 | 1.0.5
qtiles | 1.7.2
zoom_level | 0.1
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>Version de QGIS
3.28.5-Firenze
Révision du code
[50adba36f2](https://github.com/qgis/QGIS/commit/50adba36f2)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.6.3
Version de Proj
9.2.0
Version de la base de données du registre EPSG
v10.082 (2023-02-06)
Version de GEOS
3.11.2-CAPI-1.17.2
Version de SQLite
3.41.1
Version de PDAL
2.5.2
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
db-style-manager
0.8
DigitizingTools
1.5.2
lockzoom
3.0.3
map-units-per-pixel
0.2.1
menu_from_project
v2.0.8
numericalDigitize
0.4.7
qfieldsync
v4.6.0
qgis2web
3.16.0
QMetaTiles
1.5
QNEAT3
1.0.5
qtiles
1.7.2
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
Additionally an error message is displayed in the console (french version) :

> WARNING    Requête erronée : SELECT styleName FROM layer_styles WHERE f_table_catalog='my_catalog' AND f_table_schema='my_schema' AND f_table_name='my_table' AND f_geometry_column=='the_geom' AND (type='Polygon' OR type IS NULL) AND styleName='my_style_name' a retourné 7 [ERREUR: l'opérateur n'existe pas : character varying == unknown
             LINE 1: ...D f_table_name='courseaucad' AND f_geometry_column=='the_geo...
              ^
             HINT: Aucun opérateur ne correspond au nom donné et aux types d'arguments.
             Vous devez ajouter des conversions explicites de type.

f_geometry_column=='the_geom' logically throws an error

_No response_

**Comment by mhassi** [comment]
Hi, i have same problem.

How many different styles same layer should have in database layer_styles table?

Just one or multible styles according used Qgis version?


QGIS version
3.28.4-Firenze
QGIS code revision
fd0fb72ab3
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009




Active Python plugins
CalculateGeometry
0.6.8
copy_coords
0.2
GeometryShapes
0.7
gistools
0.3
gml_application_schema_toolbox
1.3.1
GpxSegmentImporter
2.5
LocatePoints
0.3.4
mmqgis
2021.9.10
Multi_Ring_Buffer
1.1
pathfinder
version 0.4.2
qfieldsync
v4.4.9
QGISDigitransitGeocoding-master
0.7.2
Tieosoitetyokalu
1.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99
