### ISSUE TITLE
Qgis shows each WFS point twice

### ISSUE THREAD

**Issue by frspp** [qgis/QGIS#54885]
### What is the bug or the crash?

Bug

### Steps to reproduce the issue

Add WFS source: https://lipas.fi/geoserver/lipas/ows
Add layer "lipas kaikki pisteet" to map
Make a selection over single point. Qgis selects point twice. Data source has each point only once.  

Note: For first selection it looked like it selects each point only once, but with next selection gets each point twice.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGISin versio | 3.32.3-Lima | QGIS-koodin versio | 67d46100b5
-- | -- | -- | --
Qt:n versio | 5.15.3
Python-versio | 3.9.5
GDAL/OGR:n versio | 3.7.2
PROJ-versio | 9.3.0
EPSG-rekisteritietokannan versio | v10.094 (2023-08-08)
GEOS-versio | 3.12.0-CAPI-1.18.0
SQLite-versio | 3.41.1
PDAL-versio | 2.5.5
PostgreSQL:n asiakkaan versio | 15.2
SpatiaLite-versio | 5.1.0
QWT-versio | 6.1.6
QScintilla2-versio | 2.13.4
Käyttöjärjestelmän versio | Windows 10 Version 2009
  |   |   |  
Aktiiviset python-lisäosat
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGISin versio
3.32.3-Lima
QGIS-koodin versio
[67d46100b5](https://github.com/qgis/QGIS/commit/67d46100b5)
Qt:n versio
5.15.3
Python-versio
3.9.5
GDAL/OGR:n versio
3.7.2
PROJ-versio
9.3.0
EPSG-rekisteritietokannan versio
v10.094 (2023-08-08)
GEOS-versio
3.12.0-CAPI-1.18.0
SQLite-versio
3.41.1
PDAL-versio
2.5.5
PostgreSQL:n asiakkaan versio
15.2
SpatiaLite-versio
5.1.0
QWT-versio
6.1.6
QScintilla2-versio
2.13.4
Käyttöjärjestelmän versio
Windows 10 Version 2009

Aktiiviset python-lisäosat
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
I don't reproduce this with QGIS master with "Identify features", "Select feature(s)" or "Select features by polygons". Which selection tool do you use exactly ?
