### ISSUE TITLE
Bug while deleting only one layer in a layout legend.

### ISSUE THREAD

**Issue by solisgb** [qgis/QGIS#54912]
## User Feedback

It is a similar case to another I have reported previously, I am sending it to you for additional information. This time it has occurred when deleting in a layout legend only one layer (not many at once as in the previous crash). The layer was not visible on the map.
(Auto update is off)

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x0000a548 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsLayerTreeModel::node2index :
QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayerTreeModel::setLegendFilter :
QgsLayoutItemLegend::doUpdateFilterByMap :
QgsLayoutItemLegend::paint :
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Layout
Edit a layout
Resize the page layout from Custom to A2 
Move legend position
Copy the legend
Paste a new legend.
Edit the previous legend.
Delete item by item.
Bug deleting one item (previously no errors deleting other items in the same legend).  

### Versions

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Similar to https://github.com/qgis/QGIS/issues/52268

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/issues/52268 has been closed, adding feedback.
