### ISSUE TITLE
qgis_process plugins enable <plugin> may lead to unreliable output about plugin usability

### ISSUE THREAD

**Issue by florisvdh** [qgis/QGIS#54915]
### What is the bug or the crash?

`qgis_process plugins enable <plugin>` does not test whether the enabled plugin can be loaded, so AFAIK it will always result in output that lists the plugin as enabled. However, when running `qgis_process plugins` after that, all plugins are tested and if a problem exists in the enabled plugin, only now this will become clear and lead to the plugin marked as disabled again.

Maybe `qgis_process plugins enable <plugin>` should end by testing whether the specific plugin can be loaded, before deciding on its status and returning the output of enabled/disabled plugins. Non-functioning plugins would then not be allowed to be enabled, at least when using `qgis_process` (the plugin problem may be limited to `qgis_process` and not present in the GUI, as was the case in the example below). An error thrown at this point would also allow to make better decision in R package {qgisprocess} whether to update the package cache or not.

### Steps to reproduce the issue

Described behaviour could e.g. be observed with an older version of the Valhalla plugin:

1. Download and install the previous version of the Valhalla plugin, i.e. 2.4.1, from https://plugins.qgis.org/plugins/valhalla/version/2.4.1/
2. Disable the plugin in the QGIS GUI (via plugin manager)
3. Run `qgis_process plugins enable valhalla`
4. Run `qgis_process plugins`

The output of steps 3 and 4 is included in the first message of https://github.com/gis-ops/valhalla-qgis-plugin/issues/12.

### Versions

```
$ qgis_process --version
QGIS 3.32.3-Lima 'Lima' (67d46100b5)
QGIS code revision 67d46100b5
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.6.4
PROJ version 9.1.1
EPSG Registry database version v10.076 (2022-08-31)
GEOS version 3.11.1-CAPI-1.17.1
SQLite version 3.37.2
OS Linux Mint 21.2
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
With the latest master (a2643b801c9b3a765ce5e0fabd235762f25aa7fe) `qgis_process` output is pretty clear about the error in the valhalla plugin
```
NoneType: None

src/core/qgsmessagelog.cpp:39 : (logMessage) [1ms] 2023-11-12T11:10:18 Couldn't load plugin 'valhalla' - plugin has no initProcessing() method[1] Couldn't load plugin 'valhalla' - plugin has no initProcessing() method


NoneType: None


NoneType: None
```
But later in the output it still marks it as enabled.

**Comment by florisvdh** [comment]
@alexbruy thanks. AFAIK 'logMessage' is only shown for QGIS [compiled with](https://github.com/qgis/QGIS/blob/master/INSTALL.md#8-debug-output-and-running-tests) `CMAKE_BUILD_TYPE=DEBUG` (may be the case for nightly builds, at least from ubuntugis-nightly-release)
