### ISSUE TITLE
Pretty breaks graduation takes wrong number of classes

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#54922]
### What is the bug or the crash?

1. Enable graduated symbology for a vector layer
2. Switch to "Pretty breaks" classification mode
3. Change the number of classes and notice that there is no synchronization 

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/7983394/299437c5-45fd-46eb-b042-516cac791b4b

### Versions

On 3.33 and 3.28
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Version de QGIS | 3.33.0-Master | Révision du code | 4cf834499b
-- | -- | -- | --
Version de Qt | 5.15.8
Version de Python | 3.11.2
Version de GDAL/OGR | 3.6.2
Version de Proj | 9.1.1
Version de la base de données du registre EPSG | v10.076 (2022-08-31)
Version de GEOS | 3.11.1-CAPI-1.17.1
Version de SQLite | 3.40.1
Version de PDAL | 2.6.0
Version du client PostgreSQL | 15.3 (Debian 15.3-0+deb12u1)
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.4
Version de QScintilla2 | 2.13.3
Version de l'OS | Debian GNU/Linux 12 (bookworm)
  |   |   |  
Cette copie de QGIS dispose d'une sortie de débogage.
  |   |   |  
Extensions Python actives
MemoryLayerSaver | 5.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
@DelazJ I don't think it's  bug: it is the way pretty breaks works, the number of classes is more a hint than a constraint.

**Comment by DelazJ** [comment]
Got it @elpaso . thanks
