### ISSUE TITLE
Model Designer fail to produce output

### ISSUE THREAD

**Issue by ulfboge** [qgis/QGIS#54949]
### What is the bug or the crash?

The Model Designer fails to produce an output when a raster layer is processed.

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/53839582/58b98c18-7caf-4fec-9481-1a86cdc2a2dd)
1. Open New Model in Model Designer
2. Add Raster Layer as Input
3. Add Algorithm (Raster Calculator or Reclassify by Table)
4. Fill in the parameters and add a name to produce an output.
5. No Output is created
![image](https://github.com/qgis/QGIS/assets/53839582/5a2e71a0-440a-4afc-b049-94cc37ff51c8)

This is not a consistent problem. I managed to create an output at first, but once it starts to act up it does not produce any output. Restart or using a different user profile does not work. 

### Versions

QGIS version
3.32.3-Lima
QGIS code revision
67d46100b5
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
felt
1.1.0
OpenTopography-DEM-Downloader
2.0
QuickOSM
2.2.3
quick_map_services
0.19.33
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Not reproducible on Linux and Windows using latest master and LTR. Please provide test data and model which fails for you.
