### ISSUE TITLE
WCS layers get broken as soon as some layer property is changed

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#54950]
### What is the bug or the crash?

WCS layers get broken as soon as some layer property is changed.

### Steps to reproduce the issue

Add a WCS layer, i.e. http://wms.pcn.minambiente.it/wcs/dtm_75m , so far so good

Open its properties and try apply a new color ramp, or make transparent some pixel values. After clicking "ok" the layer goes missing:

![image](https://github.com/qgis/QGIS/assets/1951107/156e06a6-133d-42d5-b5e9-afd8daa8910a)

### Versions

3.28.11
3.32.3

Windows 11.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can't reproduce with the latest master (a2643b801c9b3a765ce5e0fabd235762f25aa7fe). Color ramp is applied to the image and layer still shown as available. But in the console there errors, probably the server is not functioning properly
```
src/core/qgsmessagelog.cpp:39 : (logMessage) [0ms] [thread:0x55c78f56d870] 2023-11-12T11:28:12 WCS[1] No data received
src/core/qgsmessagelog.cpp:39 : (logMessage) [221173ms] [thread:0x55c78f53afa0] 2023-11-12T11:31:53 WCS[1] composed error message '(No error code was reported)
The WCS vendor also reported: msDrawRasterLayerLow(): Unable to access file. Corrupt, empty or missing file 'SDE:192.168.10.100,5151,cartoraster,sde,sde,cartoraster.sde.dtm_75_9999,raster' for layer 'EL.DTM.75M'. SE_connection_create: -51/Underlying DBMS error
  '.
```

**Comment by gioman** [comment]
@alexbruy indeed, seems fixed on master.
