### ISSUE TITLE
"Contour" returns error if output is temporary (wrong parameter passed?)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#54952]
### What is the bug or the crash?

The "contour" tool in the Processing toolbox seems to have lost the ability to output to temp file. If specifying an real output (i.e. gpkg or shp) it works as expected. The problem seems to be to be the parameter` -f "Interlis 2"` that it passed, and probably should not:

```
GDAL command:
gdal_contour -b 1 -a ELEV -i 200.0 -f "Interlis 2" GPKG:C:/Users/giovanni/Desktop/SVR/test.gpkg:mdt C:/Users/giovanni/AppData/Local/Temp/processing_GXQWCj/cdcbd9ff07604c918419db19f781250c/OUTPUT.xtf
GDAL command output:
Warning 1: Model file not specified.
Process returned error code 1
Execution completed in 0.36 seconds
Results:
{'OUTPUT': 'C:/Users/giovanni/AppData/Local/Temp/processing_GXQWCj/cdcbd9ff07604c918419db19f781250c/OUTPUT.xtf'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/giovanni/AppData/Local/Temp/processing_GXQWCj/cdcbd9ff07604c918419db19f781250c/OUTPUT.xtf
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.
```

### Steps to reproduce the issue

Add a DEM to a project and try extract the contour with a temp output.

### Versions

3.28.11
3.32.3

Windows 11.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
`-f "Interlis 2"` is passed because you seem have "Interlis 2" set as a default output format.

**Comment by gioman** [comment]
@alexbruy that was the case, anyway is very strange I never changed that option and in fact this was also observed on other people machines where QGIS was only recently installed.

**Comment by agiudiceandrea** [comment]
It seems a recurring issue. I've seen various users reports on forums and facebook groups about the issue due to that setting they actually didn't set.

**Comment by agiudiceandrea** [comment]
Another issue report about the xtf "Interlis 2" default output vector format: https://github.com/qgis/QGIS/issues/55110.

**Comment by agiudiceandrea** [comment]
Another issue report about the nc default output raster format: https://lists.osgeo.org/pipermail/qgis-user/2024-January/053885.html

**Comment by agiudiceandrea** [comment]
Other reports about the "Interlis 2" (.xlt) default output vector format issue: 
https://gis.stackexchange.com/questions/463507/contour-polygons-warning-model-file-not-specified
https://gis.stackexchange.com/questions/477614/polygonize-error
https://gis.stackexchange.com/questions/474162/qgis-converting-simple-png-raster-file-yields-warning-1-model-file-not-specifi
https://gis.stackexchange.com/questions/463099/clip-raster-by-mask-layer-attempt-gives-error-1-netcdf-chunk-fetch-failed
https://gis.stackexchange.com/questions/467079/qgis-polygonize-tool-error

**Comment by kannes** [comment]
xtf and nc are the last entries in the lists for Processing's "Default output [raster|vector] layer extension".

In profiles where the xtf and nc are set, the `QGIS3.ini` contains:
```
Configuration\DefaultOutputRasterLayerExt=-1
Configuration\DefaultOutputVectorLayerExt=-1
```

There is [some code catching that and use the wanted defaults (gpkg and tif)](https://github.com/qgis/QGIS/blob/da9afac631f509593cfb0f9722aa82a62f89c663/src/core/processing/qgsprocessingutils.cpp#L1511-L1525) but I guess there is a bug with the population of the combobox of chooseble formats in the Processing options.

**Comment by agiudiceandrea** [comment]
Thanks @kannes for looking at this. I also suggested the same root cause in a recent message to the qgis-developer mailing list https://lists.osgeo.org/pipermail/qgis-developer/2024-February/066539.html.
See also https://github.com/qgis/QGIS/pull/53458.

**Comment by agiudiceandrea** [comment]
Another recent report: https://github.com/qgis/QGIS/issues/56588.

**Comment by agiudiceandrea** [comment]
@ar-siddiqui, if you have experienced the issue about the settings change without your consent, please open an issue report or inform the qgis-developer mailing list replaying to the at thread https://lists.osgeo.org/pipermail/qgis-developer/2024-February/066539.html. If other user have experienced such issue, please ask them to open an issue report.

**Comment by agiudiceandrea** [comment]
Other issue reports: https://github.com/qgis/QGIS/issues/55110#issuecomment-1873415345, https://github.com/qgis/QGIS/issues/57250.

**Comment by ar-siddiqui** [comment]
I ran into this issue today as well. I did not change any settings or installed any plugins that might have updated the settings.

**Comment by ar-siddiqui** [comment]
Why has this issue been closed, please reopen this as many people are observing and reporting this. @agiudiceandrea

**Comment by agiudiceandrea** [comment]
@ar-siddiqui, this issue report has been closed by the reporter, since this specific issue has been fixed by himself just reverting the default output vector extension to the default value.
You can open a new issue report about the unexpected setting change.

**Comment by ar-siddiqui** [comment]
A master issue has been created to track this bug https://github.com/qgis/QGIS/issues/57676
