### ISSUE TITLE
Plugin Manager does not unload plugins before upgrading them

### ISSUE THREAD

**Issue by alexbruy** [qgis/QGIS#54968]
After downloading a plugin package, Plugin Manager tries to unzip it and overwrite exiting plugin files without unloading the plugin first, see https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/qgsplugininstallerinstallingdialog.py#L150-L161.

In some cases, when plugin directory contains locked/open files (for example, some resources are open or libraries are loaded) this operation fails on Windows, making it impossible to reinstall/upgrade plugin in a usual way. In that case one has to close QGIS, manually delete plugin folder, then start QGIS again and install plugin.

**Comment by alexbruy** [comment]
@borysiasty do you remember why it was implemented this way?

**Comment by borysiasty** [comment]
Hi Alex!
Ooops, my old ugly code...

No particular reason, it was just overlooked. I can fix it if you have a reproducible test case / the affected plugin, or do you prefer to fix it by yourself? 

I guess  the best place for unloading is before calling that QDialog: 
https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/installer.py#L318

but then the loading back (line 345) should be also performed in lines 323/324, in case the downloading failed or was aborted.

And the same problem applies to installing from a local zip:
https://github.com/qgis/QGIS/blob/master/python/pyplugin_installer/installer.py#L615

**Comment by alexbruy** [comment]
This was found when investigating an issue with Mergin plugin updates (https://github.com/MerginMaps/qgis-mergin-plugin/issues/504). While in this particular case unloading plugin is not enough, IMHO this is still a valid issue and Plugin Manager should unload plugin before updating it.

I will prepare PR.
