### ISSUE TITLE
Crash for complex map composition

### ISSUE THREAD

**Issue by coldon82** [qgis/QGIS#54970]
## User Feedback

There is no information on the canvas, only one map composition, but a bit complex. I need to recovery, there is so much work behind it

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004780 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsLayoutTable::rowsVisible :
QgsLayoutTable::rowRange :
QgsLayoutTable::render :
QgsLayoutFrame::draw :
QgsLayoutItem::paint :
QGraphicsScene::~QGraphicsScene :
QGraphicsScene::drawForeground :
QGraphicsScene::dragMoveEvent :
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::size :
QWidgetPrivate::syncBackingStore :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processExposeEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QWindowSystemInterface::flushWindowSystemEvents :
UserCallWinProcCheckWow :
DispatchClientMessage :
_fnDWORD :
KiUserCallbackDispatcherContinue :
NtUserDispatchMessage :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

[informe_subvencio.zip](https://github.com/qgis/QGIS/files/12995368/informe_subvencio.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.28.9-Firenze | Revisión del código de QGIS | 66f4d63ad4
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.5
Versión de GDAL/OGR | 3.7.1
Versión de PROJ | 9.2.1
Versión del registro de base de datos EPSG | v10.088 (2023-05-13)
Versión de GEOS | 3.12.0-CAPI-1.18.0
Versión de SQLite | 3.41.1
Versión de PDAL | 2.5.5
Versión del cliente de PostgreSQL | unknown
Versión de SpatiaLite | 5.0.1
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.1
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Versión de QGIS
3.28.9-Firenze
Revisión del código de QGIS
[66f4d63ad4](https://github.com/qgis/QGIS/commit/66f4d63ad4)
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.7.1
Versión de PROJ
9.2.1
Versión del registro de base de datos EPSG
v10.088 (2023-05-13)
Versión de GEOS
3.12.0-CAPI-1.18.0
Versión de SQLite
3.41.1
Versión de PDAL
2.5.5
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Will be fixed by https://github.com/qgis/QGIS/pull/54907

**Comment by nirvn** [comment]
@nyalldawson , can we close this?

**Comment by coldon82** [comment]
making a copy of map composition there was no problem to open it
