### ISSUE TITLE
Delete part digitizing tool on polygons remove only the geometry part

### ISSUE THREAD

**Issue by jsmoreau** [qgis/QGIS#54975]
### What is the bug or the crash?

When digitizing a feature layer, if a user want to remove a feature by using the delete part tool, only the geometry gets removed. The attribute table still shows the attributes of that feature although there are no geometries associated with it. I agree that selecting the feature and deleting it should be the correct way to do this. However, our users often use the delete part by mistake which leaves the file in a broken state after editing.
I think that in that case, the delete part tool should detect that the "part" is actually a complete feature and should therefore be removed completely.

### Steps to reproduce the issue

- Unzip de shape file polygones_fantomes.

[polygones_fantomes.zip](https://github.com/qgis/QGIS/files/13022980/polygones_fantomes.zip)

- Add it in the project
- Open the attribute table, you will see that the layer contains 36 features
- Activate editing on the layer
- Activate the delete part tool
- Click on a feature. It gets deleted
- Open the attribute table, you will see that the number of features is still 36.

### Versions

QGIS version
3.32.0-Lima
QGIS code revision
311a8cb8a6
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.0
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.3
PostgreSQL client version
15.2
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
geo_sim_processing
1.2.0
LAStools
1.4
latlontools
3.6.14
metadataplugin
0.1.0
planet_explorer
2.3.1
pluginbuilder3
3.2.1
profiletool
4.1.8
qgis_stac
1.1.1
QuickWKT
3.1
rasterdataplotting
1.6.3
systeme-prod-plugin-qgis
1.0
zoomtopaste
3.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
I'd argue this is the intended behavior, as users may actually want a feature with no geometry.
Maybe adding a messageBar entry stating that the last geometry part has been deleted would make more sense.

**Comment by nyalldawson** [comment]
This is definitely by design. 

If it's causing issues in your organisation you could potentially hide this action away by customising the interface and removing that button.

**Comment by jsmoreau** [comment]
Thank you for your answers! I'll try to customise the toolbar.
