### ISSUE TITLE
Server / API Features - 500 Internal Server Error after timout

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#54973]
### What is the bug or the crash?

End of script output before headers: qgis_mapserv.fcgi

QGIS Server logs:

```
[Wed Oct 18 11:01:18.169403 2023] [fcgid:warn] [pid 5654:tid 139865758574144] [client XXX] mod_fcgid: read data timeout in 120 seconds, referer: https://...
[Wed Oct 18 11:01:18.169475 2023] [core:error] [pid 5654:tid 139865758574144] [client XXX] End of script output before headers: qgis_mapserv.fcgi, referer: https://...
```

### Steps to reproduce the issue

1. Request OGC API Features items HTML page with a high limit to trigger a timout e.g. `items.html?offset=0&limit=50000`
2. Get error 500
3. Inspect QGIS Server logs

### Versions

QGIS Server 3.32.3 / Ubuntu / Apache

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I don't feel this is a QGIS Server issue. The timeout is probably triggered by the webserver tier (apache/nginx whatever).

**Comment by pathmapper** [comment]
The timout yes, this is only a warning in the logs [fcgid:warn]. But the error comes after the timeout [core:error] referring to qgis_mapserv.fcgi.

But I trust your feelings, closing here :-)

**Comment by elpaso** [comment]
You can test your project with the standalone server qgis_mapserver bypassing the webserver and see what happens.
