### ISSUE TITLE
Adding/updating legend for print layout leads to enabling "Show Feature Count"  when option "Show feature count for newly added layers" is enabled

### ISSUE THREAD

**Issue by blacktesta** [qgis/QGIS#54974]
### What is the bug or the crash?

Everything in the title, details below

### Steps to reproduce the issue

1. Enable "Show feature count for newly added layers" in Options
2. Create project with some layers
3. Disable "Show Feature Count" for some or all layers
4. Create print layout
5. Add map to layout
6. Add legend to layout
Result: "Show Feature Count" have been enabled for all layers
Same happens when you turn on auto updating of the legend

Video: https://github.com/qgis/QGIS/assets/74047515/d8105ad0-8dab-4549-9eee-f29e96338578

### Versions

QGIS version 3.32.2-Lima
QGIS code revision https://github.com/qgis/QGIS/commit/c0b883396492bf6e78ac65b6a1019489ec1eb1d8
Qt version 5.15.3
Python version 3.9.5
GDAL/OGR version 3.7.1
PROJ version 9.2.1
EPSG Registry database version v10.088 (2023-05-13)
GEOS version 3.12.0-CAPI-1.18.0
SQLite version 3.41.1
PDAL version 2.5.5
PostgreSQL client version 15.2
SpatiaLite version 5.1.0
QWT version 6.1.6
QScintilla2 version 2.13.1
OS version Windows 10 Version 2009

Active Python plugins
processing 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

P.S.  For me it is common situation when feature count needs to be shown in Layer panel, but not in print layout legend. Adding "Show Feature Count" for layers in layout legend would be great solution. But i understand that it require more work than just fixing the bug.

**Comment by alexbruy** [comment]
Duplicates #51896?

**Comment by blacktesta** [comment]
> Duplicates #51896?

Yes.
