### ISSUE TITLE
Mapbox GL Styling on Vector Tile Sets converts to style filter incorrectly?

### ISSUE THREAD

**Issue by jasonjanofsky** [qgis/QGIS#54980]
### What is the bug or the crash?

Upon referencing a Vector Tile layer and specifying a style.json MapBox GL Standard file.  QGIS does not appear to be properly interpreting the filter array in the layers object of the MapBox standard.

EX:
`[ 
        "==",
        "name",
        "staining"
],`

Produces the style with a filter
`"name" is 'staining'`

inside QGIS in the styles dialog.  Upon reviewing the map, the filter is not applied and the map doesn't update w/the fill color.  If, however, one changes the filter to use double quotes on the value, the styling applies.  Changing the style filter to:
`"name" IS "staining"`
the filter applies.

### Steps to reproduce the issue

From a blank map, right click on the browser -> Vector Tiles.
Click "New Generic Connection" -> Enter a vector tile layer.
Reference a style.json file with a layer that has a filter in it to a shape attribute.  Something like
`[ 
        "==",
        "name",
        "staining"
],`

Add the new tile layer to the current map.  Click on the properties and symbology modal.  The filter should show up with a label that corresponds to the layer.  The filter should show up like this:
`"name" IS 'staining'` with a single quote around the value.

From here, we should note that the filtered color is not applied.  If, however, we change the value from 
`"name" IS 'staining'` to `"name" IS "staining"` and hit apply styles, the filter is applied properly.

### Versions

3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jasonjanofsky** [comment]
It's an attribute in the dataset.
![CleanShot 2023-10-18 at 10 41 00@2x](https://github.com/qgis/QGIS/assets/4860840/3d464c5b-ac2f-46d5-9eeb-280a541cb15e)

Shows up like this ^^^

**Comment by nyalldawson** [comment]
If `staining` is the attribute value then the use of single quotes is definitely correct.

Does `"name"='staining'` work ok?

**Comment by jasonjanofsky** [comment]
Good question, no
`"name"='staining'` doesn't work, however the literal copy of the filter value `==` does.
IE: 
`"name" == 'staining'`

**Comment by nyalldawson** [comment]
Both `"name" is "staining"` and `"name"=='staining'` are invalid qgis expressions, and effectively disable the filter. 

Is this data and style public?

**Comment by jasonjanofsky** [comment]
No, the style sheet is something I am working on, internally, following the MapBox docs.  It looks like the filter setup is correct in that I am using:
https://docs.mapbox.com/help/glossary/filter/

Any thoughts on a better way to do this is appreciated.

**Comment by nyalldawson** [comment]
It's tricky to go further without more detail. Is the staining feature completely missing from the map? Or are all features showing with this rule? Screenshots would help

**Comment by jasonjanofsky** [comment]
Ah, ok, here's the full style sheet -- note the layer "all" works fine for the default style on polygons.

`
{
  "version": 8,
  "name": "Test Style",
  "sources": {
    "mystyle": {
      "type": "vector",
      "tiles": [
          "http://localhost/tiles/{z}/{x}/{y}"
      ],
      "maxzoom": 23
    }
  },
  "center": [
    -81.382495, 28.535999
  ],
  "layers":
  [ 
    {
      "id": "staining",
      "type": "fill",
      "source": "mystyle",
      "filter":
      [ 
        "==",
        "name",
        "staining"
      ],
      "layout":
      {
          "visibility": "visible"
      },
      "paint":
      {
        "fill-color": "rgb(0, 200, 255)"
      }
    },
    {
      "id": "all",
      "type": "fill",
      "source": "betterview",
      "layout":
      {
          "visibility": "visible"
      },
      "paint":
      {
          "fill-color": "rgb(230, 233, 229, 0.5)",
          "fill-outline-color": "rgb(200, 0, 255)"
      }
    }
  ]
}`

**Comment by jasonjanofsky** [comment]
![CleanShot 2023-10-18 at 11 31 00@2x](https://github.com/qgis/QGIS/assets/4860840/00e54f2a-81d3-4f4e-8b44-315ba3fd3270)
Here's a sample image with the default style ^^
![CleanShot 2023-10-18 at 11 31 27@2x](https://github.com/qgis/QGIS/assets/4860840/b1c2d235-009c-4437-b259-898c01b7730e)

Here's a cap of the the symbology window ^^^
![CleanShot 2023-10-18 at 11 32 06@2x](https://github.com/qgis/QGIS/assets/4860840/42d730f2-14e4-455d-939a-4797075ff1d5)
In this capture, I changed the symbology window filter manually: ^^^
![CleanShot 2023-10-18 at 11 32 47@2x](https://github.com/qgis/QGIS/assets/4860840/2c35a042-7aa6-4eb2-9de3-17afb734654d)
and, when I change, I get this ^^^

**Comment by jasonjanofsky** [comment]
Now the tiles are coming from Postgres doing something like:
select st_asmvt(geom, name) from xxx

the tiles are then served up from a simple tile server coming out as vector pbf format.

**Comment by nyalldawson** [comment]
Can you share also what that region looks like when opened in a browser based map using the same stylesheet?
