### ISSUE TITLE
Broken graduated symbology UI using multiline virtual field

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#54999]
### What is the bug or the crash?

I defined a virtual field and for readability I used a multi line expression 
![image](https://github.com/qgis/QGIS/assets/39594821/f3daa8a8-7fb3-4c3c-b2b2-095ab0d90bf0)

And here is what symbology UI looks like
![image](https://github.com/qgis/QGIS/assets/39594821/c02a1f65-6b1e-4a4a-be2d-b31b02e71a47)
![image](https://github.com/qgis/QGIS/assets/39594821/117b8f67-b51d-4e47-8afa-f4f61aa8319f)

Pretty unusable

If I remove this virtual field, UI is fine
![image](https://github.com/qgis/QGIS/assets/39594821/1ac65a0d-1679-4499-98f1-21d02fd593a1)

### Steps to reproduce the issue

I could provide a sample project but right now this one contains sensitive info.

1. Create layer and define a virtual field with a multi line expression
2. Define graduated symbology
3. Close and reopen layer properties
4. See broken UI
5. Delete virtual field and reset symbology
6. Close and reopen layer properties
7. See UI is fine

### Versions

3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
It seems that it does not happen using layer style panel 
![image](https://github.com/qgis/QGIS/assets/39594821/1238e147-a9c5-4ab5-8837-2c5943bca816)

**Comment by troopa81** [comment]
Isn't the same as https://github.com/qgis/QGIS/issues/54549 ? Can you check with master if it is fixed?

**Comment by nicogodet** [comment]
Exactly same issue
Will check on master

**Comment by nicogodet** [comment]
Seems fine on 3.34.
