### ISSUE TITLE
QGIS Client | WMS | MAP parameter - substring "map" is converted to upper case

### ISSUE THREAD

**Issue by relume** [qgis/QGIS#55003]
### What is the bug or the crash?

If a project is served from a QGIS Server (apache2) as WMS and the projects path contains a substring "map" the QGIS Client converts the substring "map" in the URL for following sub request to upper cases "MAP" resulting that data can not retrieved.

if the following URL is defined in the QGIS Client WMS setting:

`https://mapservice.myhost.org/cgi-bin/qgis_mapserv.fcgi?MAP=/home/myservice/www_mapservice/projects/world.qgs&LAYERS=countries&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&CRS=EPSG:4326&WIDTH=400&HEIGHT=200&BBOX=-90,-180,90,180`

All project Capabilities are retrieved and the layer names are shown. By adding the layer selection to the QGIS Client project, they layer are added but ayer data is not loaded/retrieved. In the QGIS Client console there are listed warnings about "Error transferring  ... " and "Internal server replied: Internal Server Error ..". Together are displayed the  reuqested and problematic URLs like:

`https://mapservice.myhost.org/cgi-bin/qgis_mapserv.fcgi?MAP=/home/myservice/www_MAPservice/projects/world.qgs&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=47.04663559284336571%2C8.116892040499150696%2C47.80708859809933386%2C9.102497737211537654&CRS=EPSG%3A4326&WIDTH=2068&HEIGHT=1595&LAYERS=countries&STYLES=&FORMAT=image%2Fjpeg&DPI=72&MAP_RESOLUTION=72&FORMAT_OPTIONS=dpi%3A72]`

The issue is, that QGIS Client converts in the URL parameter string "MAP" every substring "...map..." to upper case:

`"…/www_mapservice/…" > "/www_MAPservice/"`

Thus the URL is not valid anymore resulting that layer data can not be loaded/retrieved.

### Steps to reproduce the issue

1. serve a project on a QGIS Server with an project path that contains a substring "map":
`e.g. "/home/my_maps/projects/..." or "/home/my_mapservice/projects` 

2. in QGIS Client add the QGIS Server as WMS service
3. retrieve WMS layers with the URL parameter "MAP
4. check if layer data is loaded and check QGIS Client console warnings

### Versions

- QGIS 3.16.3
- QGIS 3.32.2
- QGIS Server 3.32.3+38lunar

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by kannes** [comment]
Probably fixed by https://github.com/qgis/QGIS/pull/54639

**Comment by relume** [comment]
Hello

Many thanks for your reference. We have installed on Ubuntu lunar the distro package qgis-server 3.32.3+38lunar.

best regards

**Comment by relume** [comment]
Many thanks! 
I confirm that in the QGIS Server 3.33.0-Master nightly build (Unbuntu Lunar) the bug is fixed. Layer data is now correctly loaded/retrieved.

**Comment by relume** [comment]
Many thanks!
I confirm that in the QGIS Server 3.33.0-Master nightly build (Unbuntu Lunar) the bug is fixed. Layer data is now correctly loaded/retrieved.

**Comment by kannes** [comment]
Awesome, thanks for testing a nightly build!
