### ISSUE TITLE
Error de complemento

### ISSUE THREAD

**Issue by Dany0937** [qgis/QGIS#55015]
### What is the bug or the crash?

Recientemente me he encontrado con un error en el complemento Semi-Automatic Classification Plugin de QGIS y necesito su ayuda para solucionarlo lo más pronto posible. El mensaje de error que estoy recibiendo es el siguiente:

2023-10-21T19:36:11 WARNING Semi-Automatic Classification Plugin: Error. Por favor, instale la biblioteca de Python requerida remotior_sensus.
He estado utilizando este complemento de QGIS y es de suma importancia para mi trabajo actual. Sin embargo, parece que falta una biblioteca de Python llamada remotior_sensus que es necesaria para el correcto funcionamiento del complemento.

Me gustaría pedirles su colaboración para encontrar una solución a este problema. Si alguien tiene experiencia con este error o conoce cómo instalar la biblioteca remotior_sensus, les agradecería mucho que compartieran su conocimiento.

### Steps to reproduce the issue

 INFO    No module named 'remotior_sensus'

### Versions

Qgis 3.28.11 LTR

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
This issue tracker is for QGIS.
For plugins please go their respective issue tracker, for the Semi Automatic Classification Plugin, that would be here: https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues

Have a look at this issue which looks very similar. Thank you https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin/issues/301
