### ISSUE TITLE
QGIS hangs when setting label font size less than 1.0

### ISSUE THREAD

**Issue by ccrook** [qgis/QGIS#55024]
### What is the bug or the crash?

When setting the text font size in the Labels layer properties QGIS hangs if the size is set to less than 1.0 (not 100% sure of numeric conditions when this applies)

### Steps to reproduce the issue

From a blank project:
* Create a new scratch layer with Geometry type Point
* In the Layers panel select the layer and then right click and open Properties.
* Select Labels
* Set the label type to "Single Labels"
* Select the "Text" dialog from the dialog sidebar
* Select the size
* Enter a value such as 0.1

When I try the last step the Size text box stops updating after I have entered "0.".  The QGIS process is taking 100% of a CPU and I cannot do anything more with QGIS other than Force Quit.  I assume it is in an infinite loop.

I have tried setting different units for the size (I want to use map units), but the results are the same regardless.

### Versions

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.3
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | 14.2 (Ubuntu 14.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
sagaprovider | 2.12.99
MetaSearch | 0.3.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ccrook, thanks for reporting. Anyway QGIS 3.22 is no longer supported. I cannot reproduce the issue, following the provided steps, neither using QGIS 3.28 or QGIS 3.33.0 on Windows. Could you please try if the issue does occur using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) as requested in the issue report form?
