### ISSUE TITLE
QGIS fails to request more than one WMS-Layer

### ISSUE THREAD

**Issue by thbaumann** [qgis/QGIS#55042]
### What is the bug or the crash?

If you choose more than one WMS-layer in the WMS-connection dialog QGIS will only use one of these layers in the layers-parameter of the WMS-GetMap-Request. So you can not request more than one layer at once:

### Steps to reproduce the issue

1. Connect to a WMS-Service like https://wms.geo.admin.ch/ 

2. Choose more than one layer
![grafik](https://github.com/qgis/QGIS/assets/20082727/6a13f21d-cfeb-4df3-a674-e8ff0121893e)
or use the first entry of the GetCapabilities Response:
![grafik](https://github.com/qgis/QGIS/assets/20082727/52425231-9260-4e2c-9e6a-d7f7d63fc550)

3. The name of the layers will appear in the layer name but only one layer of them will be requested:

![grafik](https://github.com/qgis/QGIS/assets/20082727/d61b6402-c4c2-4ca0-95d2-0443209d3682)

![grafik](https://github.com/qgis/QGIS/assets/20082727/aac5412b-54c9-4fe7-8c13-3087f9649887)
 

### Versions

3.32 and nightly

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.30. QGIS 3.28 and previous versions.

**Comment by DelazJ** [comment]
@thbaumann what happens if you check "Load as separate layers" in your first screenshot?

**Comment by DelazJ** [comment]
Ah OK I see the issue: the displayed data and symbology are from one layer
