### ISSUE TITLE
vector , Raster and Processing toolbox

### ISSUE THREAD

**Issue by kashimnv** [qgis/QGIS#55066]
### What is the bug or the crash?

neither the processing toolbox is shown , neither raster layer working and neither is the raster layer working plugins can't be installed

### Steps to reproduce the issue

just click on vector and it is not working and i have tried with other versions also same problem is arising

### Versions

QGIS 3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@kashimnv, could you please provide the info requested in the issue report form? ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.")

Have you tried to enable the "Processing" core plugin (menu Plugins->Manage and Install Plugins->Installed)?
Have you actually tried if the issue does occur also creating and using a new QGIS user profile?
