### ISSUE TITLE
Attribute table removes records without a geometry

### ISSUE THREAD

**Issue by GeoJGH** [qgis/QGIS#55065]
### What is the bug or the crash?

If a Shapefile or a in memory layer contains a record without geometry, this record will be shown in the attribute table when it is first opened and will disappear if the "show [...]" button is touched. That is, if opting to show "selected features" and then back to "show all", the geometry-less rows will be removed from the attribute table.

It is particularly an issue if the default is "show features visible on map", as clicking on "show all features" will filter out the geometry less features!

Interestingly, it works fine if using a virtual layer.

### Steps to reproduce the issue

Create a temporary layer, point, with one field.
Create a point feature, set a value to the field.
Open the attribute table, create a feature from there (so without a geometry), set another value to the field.

Click on  Show Selected Features -> all records are filtered, fine.
Click on Show All Features -> only the 1st feature, the one with a geometry, is shown.

![image](https://github.com/qgis/QGIS/assets/39196082/7f1a2f80-e8b8-4b11-b900-2ed2b7db1ce3)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.9-Firenze | QGIS code revision | 66f4d63ad4
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
Discovery | 2.5.8
latlontools | 3.6.14
ProcessX | 1.5
qgis_resource_sharing | 1.0.0
QuickWKT | 3.1
quick_map_services | 0.19.33
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99
CustomToolBar | 1.1

</body></html>QGIS version
3.28.9-Firenze
QGIS code revision
[66f4d63ad4](https://github.com/qgis/QGIS/commit/66f4d63ad4)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Discovery
2.5.8
latlontools
3.6.14
ProcessX
1.5
qgis_resource_sharing
1.0.0
QuickWKT
3.1
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99
CustomToolBar
1.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I cannot reproduce on master.

**Comment by alexbruy** [comment]
Not reproducible with a2643b801c9b3a765ce5e0fabd235762f25aa7fe on Windows and Linux.
