### ISSUE TITLE
Crash on calculating Jenks breaks on gtfs aggregated stops

### ISSUE THREAD

**Issue by kimollivier** [qgis/QGIS#55060]
### What is the bug or the crash?

When trying to make graduated symbols for a lot of points (20,000) I get a crash. I have written a Jenks Break calculator myself and it does not handle very large numbers well. I suggest that the points are sampled to leave a small number (say 100-200) and do the Jenks analysis on the sample. This way it is fast and guaranteed to never fail with large datasets.

## User Feedback

Trying to do a Jenks Breaks graduated symbols. Suggest that a sample is done if there are more than a few hundred. The breaks will be the same. Python has an easy way to sample. 

 # resample to keep under 1000 or it never finishes
    if len(dStat) > 3000:
        step = int(len(dStat)/1000)
    else :
        step = 1
    sample = [ v for v in dStat.values() if v is not None and v > 0][::step]
    msg = 'Calculating 10 Jenks breaks on {} resampled to {} using step {}'.format(len(dStat),len(sample),step)
    arcpy.AddMessage(msg)
    breaks = jenks.getJenksBreaks(sample,10) # skip nulls
    print 'breaks',breaks
    breakLabels = ["{:5.0f} -{:5.0f}".format(breaks[i],breaks[i+1]) for i in range(len(breaks)-1)]
    print breakLabels

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x0000852c (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsMessageOutputConsole::destroyed :
QgsClassificationJenks::calculateBreaks :
QgsClassificationMethod::classes :
QgsGraduatedSymbolRenderer::updateClasses :
QgsGraduatedSymbolRendererWidget::classifyGraduatedImpl :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

Loaded Auckland gtfs file using GTFS GO plugin. 
Data is stored in a folder in geojson
Layers are loaded into QGIS and symbolised
I thought I would like a different range of symbols
Tried various options and then Jenks Breaks - crash.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 1.5.0
dms_2_deg | 0.3
GeoCoding | 2.19
GTFS-GO-master | 3.2.2
GTFS_Loader | 1.0.0
linz-data-importer | 2.3.1
nominatim_locator_filter | 0.2.4
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.3-Lima
QGIS code revision
[67d46100b5](https://github.com/qgis/QGIS/commit/67d46100b5)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
1.5.0
dms_2_deg
0.3
GeoCoding
2.19
GTFS-GO-master
3.2.2
GTFS_Loader
1.0.0
linz-data-importer
2.3.1
nominatim_locator_filter
0.2.4
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I notice there are some NaN values in the count used to symbolize the points. A sample and filter would be necessary to remove these from the Jenks analysis. My experience is that these cause a crash in my function.

**Comment by alexbruy** [comment]
Tested latest master (a2643b801c9b3a765ce5e0fabd235762f25aa7fe) with point layer (memory and geopackage) containing 30000 point. No crash when calculating Jenks breaks.

Could you please provide test dataset and exact steps to reproduce the issue?

**Comment by kimollivier** [comment]
1. Download Auckland gtfs zip file: https://transitfeeds.com/p/auckland-transport/124
(30 MB)

2. Open a new project with NZTM (2193) as default projection

2. Install gtfs loader plugin GTFS GO

3. Load in zip file into a new folder called auckland
	Set aggregate route frequency
	.... takes a few minutes
4. Reduce label threshold and symbolise aggregated stops count [equal interval], looks good
5.  Now try Jenks Breaks
[crash]
![gtfs_go_loadform](https://github.com/qgis/QGIS/assets/3343876/a47486e0-f315-47c3-baf8-731ac27dbe3a)
![plain_stops](https://github.com/qgis/QGIS/assets/3343876/c0d7c00f-9ec7-4a31-96c2-239858a8fe1c)
![simple stops](https://github.com/qgis/QGIS/assets/3343876/a9721e2f-2cc2-41f0-8659-984de3daaf91)

**Comment by kimollivier** [comment]
Equal count has strange NaN ranges in the legend, yet I have checked there are no null values in the 4096 records.
Similarly with Jenks.
Exporting the layer to sqlite fixes the problem, so there is something wrong with the geojson layer interpretation

**Comment by kimollivier** [comment]
![Uploading jenks_form.png…]()

**Comment by kimollivier** [comment]
![Uploading jenks_form.png…]()

**Comment by kimollivier** [comment]
![jenks_form](https://github.com/qgis/QGIS/assets/3343876/ae9fd082-c9c1-4ebc-81b3-0d0d22090279)

**Comment by nyalldawson** [comment]
I can't reproduce this with the dataset curently available from that site. Is this still an issue? If so, can you supply data which demonstrates?

**Comment by kimollivier** [comment]
I didn't notice the feedback until it went stale. I will give it another trial soon.
