### ISSUE TITLE
QGIS Closing unexpectedly after opening .h5 file

### ISSUE THREAD

**Issue by krishnaglodha** [qgis/QGIS#55086]
### What is the bug or the crash?

I'm trying to open _.h5_ file on QGIS, that I downloaded from https://n5eil01u.ecs.nsidc.org/SMAP/SPL2SMP.008/2015.04.01/
<img width="1285" alt="Screenshot 2023-10-30 at 10 05 31 AM" src="https://github.com/qgis/QGIS/assets/47075664/b9e1447f-0262-4bf7-808c-ac5bcc94e2ef">

Once I drag the file in QGIS, It stops unexpectedly and gives following error 
<img width="531" alt="Screenshot 2023-10-30 at 10 04 32 AM" src="https://github.com/qgis/QGIS/assets/47075664/b95327e8-0795-4f51-950b-29e7d3c34743">
 

### Steps to reproduce the issue

1. Download first 3 files from https://n5eil01u.ecs.nsidc.org/SMAP/SPL2SMP.008/2015.04.01/ 
2. Drag files on QGIS 

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Are you on Mac? Most likely this is a Mac-only issue due to outdated dependencies.

The file can be opened on Windows and Linux, but it does not contain GCP and transformation data.
