### ISSUE TITLE
Keep commented filter lines

### ISSUE THREAD

**Issue by pmaselkowski** [qgis/QGIS#55083]
### What is the bug or the crash?

Commented filter lines are removed after closing filter window

### Steps to reproduce the issue

1. Right click on layer, then filter
2. Type some valid expression and confirm
3. Open filter again
4. Comment filter (part) with `--` and confirm
5. Open filter window again

Current:
The filter input is empty

Expected and previous behavior:
Filter keeps the commented part so that it can be uncommented if needed

### Versions

Wersja QGIS
3.32.3-Lima
Rewizja QGIS
67d46100b5
Wersja Qt
5.15.3
Wersja Pythona
3.9.5
Wersja GDAL/OGR
3.7.2
Wersja PROJ
9.3.0
Wersja bazy danych Rejestru EPSG
v10.094 (2023-08-08)
Wersja GEOS
3.12.0-CAPI-1.18.0
Wersja SQLite
3.41.1
Wersja PDAL
2.5.5
Wersja klienta PostgreSQL
15.2
Wersja SpatiaLite
5.1.0
Wersja QWT
6.1.6
Wersja QScintilla2
2.13.4
Wersja systemu operacyjnego
Windows 10 Version 2009

Active Python plugins
BDOT10k_GML_SHP_Loader
1.0.8
joinmultiplelines
Version 0.4.1
QGISSortAndNumber-master
1.0
quick_map_services
0.19.33
searchlayers
3.0.14
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Poulpator** [comment]
I can confirm the issue on latest 3.34

The latest working was Qgis 3.30

**Comment by agiudiceandrea** [comment]
The issue occurs with the OGR data provider, while it doesn't occur e.g. with the Memory data provider.
It may be related to https://github.com/qgis/QGIS/pull/53266. What do you think @rouault?

**Comment by rouault** [comment]
fix in https://github.com/qgis/QGIS/pull/55264
