### ISSUE TITLE
Failed upgrade to 3.34 from OSGeo4w on Windows 11

### ISSUE THREAD

**Issue by Antoviscomi** [qgis/QGIS#55084]
### What is the bug or the crash?

The upgrade works fine on Windows 10 but not on Windows 11
------------------------------

_Edizione	Windows 11 Enterprise
Versione	22H2
Data installazione:	‎24/‎10/‎2023
Build sistema operativo	22621.2506
Esperienza	Windows Feature Experience Pack 1000.22677.1000.0_

I attach here the full OSGeo4W log
Is this an OSGeo Bug?

[setup.log.full.txt](https://github.com/qgis/QGIS/files/13198576/setup.log.full.txt)

### Steps to reproduce the issue

try to upgrade on a windows 11 pc by OSGeo4W

### Versions

Versione di QGIS
3.32.3-Lima
Revisione codice QGIS
67d46100b5b
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
15.2
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Questa copia di QGIS scrive messaggi di debug.

Plugins Python attivi
annotation_labels
1.0.1
BivariateLegend
1.0.2
bulkvectorexportwithstyle
0.6.7
CalculateGeometry
0.6.9
cgl_tools
2.0
coins
0.2
concavehull
2.0
contour
2.0.12
coord_attributable
0.1
corrector_vector
0.3.1
DataPlotly
4.0.3
DeepLearningTools
0.2.0
DigitizingTools
1.5.2
epmgis
3.0.25b
flexigis
0.2
GeofabrykaToolbox
0.5
GeometryShapes
0.7
google-street-view-layer-master
0.1
Hotlink
0.8.6
HouseNumbering3
version 0.0.5
Label2Attr
1.0
label_connector
1.0
LCPNetwork
version 0.1.5
lizmap
3.18.1
mmqgis
2021.9.10
networks
2.7.12
numerator
0.5
openlayers_plugin
2.0.0
pgtopoeditor
0.3.1
pg_raster_import
3.2.0
plugin_reloader
0.9.3
PostGISQueries
0.2
postgisQueryBuilder
2.0.1
postgis_geoprocessing
0.9
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qdraw
3.0.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
QPackage
1.5
qProf
0.5.1
QuickMultiAttributeEdit3
version 3.0.3
QuickOSM
2.2.3
QuickWKT
3.1
quick_map_services
0.19.33
QWeb
0.2.1
realcentroid
1.0.3
RenameField
0.1
SentinelHub
2.0.2
smooth_geometry
1.1.1
splitmultipart
1.0.0
SplitPolygon-master
1.2
StreetView
3.2
VectorMCDA
3.0.1
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Could you retry ?
You update very early. It's recommended (even if it's not written somewhere) to wait at least monday.
I updated successfully this morning.

**Comment by Antoviscomi** [comment]
> Could you retry ? You update very early. It's recommended (even if it's not written somewhere) to wait at least monday. I updated successfully this morning.

@nicogodet the update it seems to works today, but only the 3.34 nightly starts without trouble,
if I try to starts from 3.34, I receve an error pop-up like on the attaced screenshot, this only on Winows 11.
in Windows 10 all works fine

W11 Info
-----------------------
Versione di QGIS
3.34.0-Prizren
Revisione codice QGIS
c288e41f5f1
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
15.2
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009




Questa copia di QGIS scrive messaggi di debug.




Plugins Python attivi
annotation_labels
1.0.1
BivariateLegend
1.0.2
bulkvectorexportwithstyle
0.6.7
CalculateGeometry
0.6.9
cgl_tools
2.0
coins
0.2
concavehull
2.0
contour
2.0.12
coord_attributable
0.1
corrector_vector
0.3.1
DataPlotly
4.0.3
DeepLearningTools
0.2.0
DigitizingTools
1.5.2
epmgis
3.0.25b
flexigis
0.2
GeofabrykaToolbox
0.5
GeometryShapes
0.7
google-street-view-layer-master
0.1
Hotlink
0.8.6
HouseNumbering3
version 0.0.5
Label2Attr
1.0
label_connector
1.0
LCPNetwork
version 0.1.5
lizmap
3.18.1
mmqgis
2021.9.10
networks
2.7.12
numerator
0.5
openlayers_plugin
2.0.0
pgtopoeditor
0.3.1
pg_raster_import
3.2.0
plugin_reloader
0.9.3
PostGISQueries
0.2
postgisQueryBuilder
2.0.1
postgis_geoprocessing
0.9
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qdraw
3.0.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
QPackage
1.5
qProf
0.5.1
QuickMultiAttributeEdit3
version 3.0.3
QuickOSM
2.2.3
QuickWKT
3.1
quick_map_services
0.19.33
QWeb
0.2.1
realcentroid
1.0.3
RenameField
0.1
SentinelHub
2.0.2
smooth_geometry
1.1.1
splitmultipart
1.0.0
StreetView
3.2
VectorMCDA
3.0.1
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
-----------------------

W10 info
----------------------

Versione di QGIS
3.34.0-Prizren
Revisione codice QGIS
ffbdd67881
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
15.2
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009




Plugins Python attivi
annotation_labels
1.0.1
AutoLayoutTool
1.1
BivariateLegend
1.0.2
bulkvectorexportwithstyle
0.6.7
CalculateGeometry
0.6.9
cartography_tools
1.2.1
cgl_tools
2.0
coins
0.2
concavehull
2.0
contour
2.0.12
coord_attributable
0.1
corrector_vector
0.3.1
DeepLearningTools
0.2.0
DigitizingTools
1.5.2
epmgis
3.0.25b
flexigis
0.2
GeofabrykaToolbox
0.5
GeometryShapes
0.7
google-street-view-layer-master
0.1
Hotlink
0.8.6
HouseNumbering3
version 0.0.5
Label2Attr
1.0
label_connector
1.0
LAStools
1.4
LCPNetwork
version 0.1.5
lizmap
3.18.1
mmqgis
2021.9.10
MzSTools
1.8.3
networks
2.7.12
network_gt
1.0
numerator
0.5
openlayers_plugin
2.0.0
ORStools
1.6.0
OSMDownloader
1.0.3
pgtopoeditor
0.3.1
plugin_reloader
0.9.3
postgis_geoprocessing
0.9
postgis_sampling_tool
1.5.1
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qdraw
3.0.2
Qgis2threejs
2.7.1
qgis2web
3.16.0
QNEAT3
1.0.5
QPackage
1.5
qProf
0.5.1
QuickMultiAttributeEdit3
version 3.0.3
QuickWKT
3.1
quick_map_services
0.19.33
realcentroid
1.0.3
RenameField
0.1
SentinelHub
2.0.2
shapetools
3.4.15
smooth_geometry
1.1.1
splitmultipart
1.0.0
SplitPolygon-master
1.2
StreetView
3.2
VectorMCDA
3.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
![image](https://github.com/qgis/QGIS/assets/12639444/b33c8153-ea05-4c5b-8496-a3a9dc7801d9)

-----------------
W11 panel
-----------------

![image](https://github.com/qgis/QGIS/assets/12639444/7d21d94a-ba11-4f78-995f-fb862b3dd363)
-----------------

W10 panel
-------------------

![image](https://github.com/qgis/QGIS/assets/12639444/53b1d0c6-ceed-4883-91f4-9de0c0ef759a)

**Comment by nicogodet** [comment]
It seems you installed a lot of QGIS version (probably all available on OSGEO4w). Is this something you want ?

Installing only one of this metapackages is often enough for regular users.
![image](https://github.com/qgis/QGIS/assets/39594821/dc1d3e2f-b45c-482f-879e-dda249f006c6)
`qgis-full` is probably what you want.

Anyway, this error looks like a local error more than a QGIS error.

**Comment by agiudiceandrea** [comment]
@nicogodet, usually there are no issues installing all the available QGIS version using the OSGeo4W network installer.
@Antoviscomi, since this is not a QGIS issue, but an OSGeo4W installer / system issue, I think it would be better to report the issue on the dedicated OSGeo4W issue tracker at https://trac.osgeo.org/osgeo4w/.

**Comment by Antoviscomi** [comment]
> @nicogodet, usually there are no issues installing all the available QGIS version using the OSGeo4W network installer. @Antoviscomi, since this is not a QGIS issue, but an OSGeo4W installer / system issue, I think it would be better to report the issue on the dedicated OSGeo4W issue tracker at https://trac.osgeo.org/osgeo4w/.

thank you @agiudiceandrea , can I link this topic there?
