### ISSUE TITLE
QGIS_SERVER_API_WFS3_MAX_LIMIT ignored

### ISSUE THREAD

**Issue by lucamanga** [qgis/QGIS#55097]
### What is the bug or the crash?

I set "QGIS_SERVER_API_WFS3_MAX_LIMIT" to 10.000, but this value is ignored and when I do a WFS3 get features, it returns me the first 10.

This is from the log of QGIS Server:

`2023-10-31 08:59:05,987 DEBUG   [45]    Qgis: Server:   - QGIS_SERVER_API_WFS3_MAX_LIMIT / '/qgis/server_api_wfs3_max_limit' (Maximum value for "limit" in a features request, defaults to 10000): '10000' (read from ENVIRONMENT_VARIABLE)`

### Steps to reproduce the issue

URL to test:

https://gis.comune.trento.it/wfs3/collections/sensori_parcheggio/items.json

See the total items at bottom.

### Versions

QGIS Server 3.28 LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
if you don't specify limit, it uses the default (10)

```json
{
    "limit": {
        "description": "The optional limit parameter limits the number of items that are presented in the response document.\nOnly items are counted that are on the first level of the collection in the response document.  Nested objects contained within the explicitly requested items shall not be counted.\nMinimum = 1.\nMaximum = 10000.\nDefault = 10.",
        "example": 10,
        "explode": false,
        "in": "query",
        "name": "limit",
        "required": false,
        "schema": {
            "default": 10,
            "maximum": 10000,
            "minimum": 1,
            "type": "integer"
        },
        "style": "form"
    }
}

**Comment by lucamanga** [comment]
Now I understand. Is there any way to override this default value?

**Comment by elpaso** [comment]
> Now I understand. Is there any way to override this default value?

no
