### ISSUE TITLE
Importing dwg/dxf files.

### ISSUE THREAD

**Issue by Darko325** [qgis/QGIS#55096]
### What is the bug or the crash?

When I go to Project-Import/Export-Import Layers from DWG/DXF. In the source drawing I get .gpkg and for target package I get dxf. It looks like they have change its places. So the tool is useless now and I cant import .dxf files into qgis now.

### Steps to reproduce the issue

![Screenshot_2023-10-31_05-36-36](https://github.com/qgis/QGIS/assets/97731606/e1db7db1-3720-48b9-ba45-fd180cfe09c3)
Here is a side by side comparison between the old version on the left and the new version on the right.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
quick_map_services | 0.19.33
QuickOSM | 2.2.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Linux Mint 21.2

Active Python plugins
processing_saga_nextgen
1.0.0
quick_map_services
0.19.33
QuickOSM
2.2.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
I see you have a .gpkg as the source drawing in the "new version", if I understand correctly, there should be a dxf/dwg. Is it not possible to load a dxf/dwg in there?

**Comment by Darko325** [comment]
No the source drawing has nothing to do with .gpkg, and there is no options
to ad .dxf it is like they change places, mixed of code placement I suppose.
You can install and try it yourself.

**Comment by andreasneumann** [comment]
Yes - something went wrong in the dialogue. The source drawing widget has a .gpkg filter on it. This is where one should select the dxf/dwg file.

This definitely needs to be fixed as soon as possible. Definitely before 3.34 becomes the LT version.

**Comment by Darko325** [comment]
Glad that i was clear with my explanation and help point out the issue.

**Comment by m-kuhn** [comment]
Thank you for clarifying and reporting
@domi4484 can you take care of that?

**Comment by domi4484** [comment]
@Darko325 thanks for the feedback. It has been done like that because to show the layers, those have to be written in the geopackage.
It means that if a geopackage with that name already exists, the content would be replaced directly when choosing a DXF. How is it done now you still have a chance to choose another geopackage before importing. This is also why the `Import` button is still there.

But maybe my concern is not a real problem. In that case I would be happy to make the behavior smoother as you proposed.

**Comment by Darko325** [comment]
My concern is that the import process doesn't commence until someone changes the 'expand block geometries' setting to something different, such as 'add only insert points.' This can be time-consuming, particularly for larger drawings, as one must wait for the entire import before making the necessary change.

My workaround involves selecting an option I don't need, like 'add only insert points,' importing the source drawing, and then changing the setting to 'expand block geometries.' While this may not disrupt the workflow, it can be annoying, especially for beginners or those with less powerful computers.

**Comment by domi4484** [comment]
To start the import process you should be able to just press the `Import` button. Or is that not working?

But I agree that the whole thing is not very smooth. Maybe it would be better to automatically always import to a temporary file, and only when the dialog is accepted to replace the gpkg chosen by the user with the temporary one. This would allow to completely remove the `Import` button.

**Comment by Darko325** [comment]
"To start the import process you should be able to just press the Import button. Or is that not working?" Yes, it works, and yes, you got my point now. As I mentioned, it is not workflow-breaking or anything. I just tried to think of it from a beginner user's perspective(by making the process with fewer steps). However, this is much better than how it was before in the older versions of Qgis.
