### ISSUE TITLE
Unresponsive "Add record" button in non-geometry layer editing

### ISSUE THREAD

**Issue by averduc** [qgis/QGIS#55092]
### What is the bug or the crash?

When editing a non-geometry layer (table-only) in QGIS, the "Add record" button in the main interface becomes unresponsive after accepting or canceling changes in the corresponding form. The button remains in a pressed state, preventing users from clicking it again to add a new record. To add a new element to the table, users have to cancel the editing process and re-activate it. Only then can the "Add record" button be clicked again. 

### Steps to reproduce the issue

- Create a new project in QGIS.
- Add a non-geometry layer (e.g., Temporal, Geopackage, Shapefile).
- Activate the editing mode for the layer.
- Click the "Add record" button in the interface.
- If the layer has attributes, accept or cancel the changes made in the form.
- Notice that the "Add record" button remains pushed and unclickable.
![imagen](https://github.com/qgis/QGIS/assets/104026356/a5283b56-4810-4e8c-93c7-af896fedf271)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

Versión de QGIS | 3.34.0-Prizren | Revisión del código de QGIS | ffbdd67881
-- | -- | -- | --
Versión Qt | 5.15.3
Versión de Python | 3.9.5
Versión de GDAL/OGR | 3.7.2
Versión de PROJ | 9.3.0
Versión del registro de base de datos EPSG | v10.094 (2023-08-08)
Versión de GEOS | 3.12.0-CAPI-1.18.0
Versión de SQLite | 3.41.1
Versión de PDAL | 2.5.5
Versión del cliente de PostgreSQL | 15.2
Versión de SpatiaLite | 5.1.0
Versión de QWT | 6.1.6
Versión de QScintilla2 | 2.13.4
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
coordinate_capture | 0.2
DigitizingTools | 1.5.2
MemoryLayerSaver | 5.0.1
processing_fusion | 3.5
processing_saga_nextgen | 1.0.0
profiletool | 4.2.6
qad | 3.0.4
qgis_resource_sharing | 1.0.0
quick_map_services | 0.19.33
searchlayers | 3.0.14
SLD4raster | 1.0
Spanish_Inspire_Catastral_Downloader | 2.0
StreetView | 3.2
VectorBender | 0.2.1
wfsclient | 0.9.11
db_manager | 0.1.20
otbprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This issue was not present prior to at least QGIS version 3.30.1, as far as I know. The first version in which it appeared was 3.32.

**Comment by Isaacson33** [comment]
I don't know if you've noticed, but the button does not suffer from the same problem in the attribute table window. I've been using that button to add records as a workaround.
