### ISSUE TITLE
3.34 Plugin Updates and 3D Scenes crash

### ISSUE THREAD

**Issue by EmHain8** [qgis/QGIS#55105]
## User Feedback

I had installed plugin updates as notified (saga, slyr and model baker). I then tried to drag a scene in. 
I noticed the required for updates was still there. 
The scene file I dragged in from the browser was sticky and would not release

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003f08 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsMapCanvas::dragEnterEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processDrag :
QWindowSystemInterface::handleDrag :
CPrivDragDrop::PrivDragDrop getif.cxx:772
PrivDragDrop getif.cxx:920
CDropTargetAdapter::DragOver drag.cpp:3306
CDragOperation::DragOver drag.cpp:2293
DoDragDrop drag.cpp:3106
QDragManager::drag :
QDrag::exec :
QAbstractItemView::startDrag :
QAbstractItemView::mouseMoveEvent :
QTreeView::mouseMoveEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.0-Prizren
QGIS code revision: ffbdd67881
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.2.9200

### Steps to reproduce the issue

Click on Install updates
Update All
On finishing, I opened up Data Source Manager to scences and took an screen shot of it. I then closed it. 
I then selected a Scene to drag in (Cesium - Mooloolaba (Street Level) but it got sticky and wouldnt release
I noticed that Plugin Updates had returned 

### Versions

3.34.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by EmHain8** [comment]
When I reloaded QGIS, it said `Cesium ion: QGIS authentication system not available -- please configure and retry`

**Comment by alexbruy** [comment]
It would be useful to have test data to reproduce crash.

**Comment by EmHain8** [comment]
Absolutely. I thought I had put it in. I'll check.

**Comment by EmHain8** [comment]
Here's the data: https://qld.digitaltwin.terria.io/api/v0/data/35eedd6a-5652-405a-b37c-d3688f446be1/3DTiles_UM_Mooloolaba_SL_17/tileset.json

**Comment by EmHain8** [comment]
it doesn't occur anymore so closing this
