### ISSUE TITLE
Illegibility in dark mode

### ISSUE THREAD

**Issue by Graziano8890** [qgis/QGIS#55104]
### What is the bug or the crash?

In QGis ltr 3.28.11 desktop version with dark interface (windows10&11) inside the advanced digitizing panel the numbers have the same background's color (dark gray). The numbers turn out to be almost illegible.

### Steps to reproduce the issue

1. Activate the dark theme for Qgis desktop in the 3.28.11 LTR
2. activate the advanced digitalization and its panel
3. try to create a geometry and then you can notice the problem
4. you can see the numbers only if you select them; in that case the selection is green and the numbers are coloured in white.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.28.11-Firenze | Revisione codice QGIS | b02458a196
-- | -- | -- | --
Versione Qt | 5.15.3
Versione Python | 3.9.5
Versione GDAL/OGR | 3.7.2
Versione PROJ | 9.3.0
Versione database del Registro EPSG | v10.094 (2023-08-08)
Versione GEOS | 3.12.0-CAPI-1.18.0
Versione SQLite | 3.41.1
Versione PDAL | 2.5.5
Versione client PostgreSQL | unknown
Versione SpatiaLite | 5.1.0
Versione QWT | 6.1.6
Versione QScintilla2 | 2.13.4
Versione SO | Windows 10 Version 2009
  |   |   |  
Plugins Python attivi
AzureMapsCreator | 1.0.1
batch_gps_importer | version 1.0.1
cdu_creator-master | 1.3
citydb-tools | 0.8.4
CLETools | 0.5
Cxf_in | 9.2
gna | 1.1.0
htpgeoprocessor | 1.2
ImageServerConnector | 2.1.1
kmltools | 3.1.31
LandSurveyCodesImport | v0.3.0
LAStools | 1.4
lizmap | 3.18.1
map_tile_loader | 0.1.2
Multi_Ring_Buffer | 1.1
nominatim | 1.4.5
OsmAnd_bridge | 1.0
OSMDownloader | 1.0.3
osminfo | 0.7.1
pointsamplingtool | 0.5.4
precisioncursor4qgis-main | 0.2E
qfieldsync | v4.6.0
qgis2web | 3.16.0
qmapshaper | 0.8.2
qrbarcodeitem | 0.2.0
quick_map_services | 0.19.33
StreetView | 3.2
TAF-to-CSV-main | 1.2
terra_antiqua | 1.1
totalopenstationToQgis | 5.4
valuetool | 3.0.17
wbt_for_qgis | 1.0.9
XYZHubConnector | 1.9.8
db_manager | 0.1.20
processing | 2.12.99

</body></html>Versione di QGIS
3.28.11-Firenze
Revisione codice QGIS
[b02458a196](https://github.com/qgis/QGIS/commit/b02458a196)
Versione Qt
5.15.3
Versione Python
3.9.5
Versione GDAL/OGR
3.7.2
Versione PROJ
9.3.0
Versione database del Registro EPSG
v10.094 (2023-08-08)
Versione GEOS
3.12.0-CAPI-1.18.0
Versione SQLite
3.41.1
Versione PDAL
2.5.5
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
AzureMapsCreator
1.0.1
batch_gps_importer
version 1.0.1
cdu_creator-master
1.3
citydb-tools
0.8.4
CLETools
0.5
Cxf_in
9.2
gna
1.1.0
htpgeoprocessor
1.2
ImageServerConnector
2.1.1
kmltools
3.1.31
LandSurveyCodesImport
v0.3.0
LAStools
1.4
lizmap
3.18.1
map_tile_loader
0.1.2
Multi_Ring_Buffer
1.1
nominatim
1.4.5
OsmAnd_bridge
1.0
OSMDownloader
1.0.3
osminfo
0.7.1
pointsamplingtool
0.5.4
precisioncursor4qgis-main
0.2E
qfieldsync
v4.6.0
qgis2web
3.16.0
qmapshaper
0.8.2
qrbarcodeitem
0.2.0
quick_map_services
0.19.33
StreetView
3.2
TAF-to-CSV-main
1.2
terra_antiqua
1.1
totalopenstationToQgis
5.4
valuetool
3.0.17
wbt_for_qgis
1.0.9
XYZHubConnector
1.9.8
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Can you try latest nightly build? There were some fixes to the night mapping theme recently.

**Comment by Graziano8890** [comment]
Thank you. Do you mean that I should use Blend of grey theme? For me it’s not the same because I use night mapping cause have not to stress my eyes.

**Comment by Graziano8890** [comment]
Unfortunately, the situation is also the same in Qgis 3.28.12-Firenze

**Comment by alexbruy** [comment]
Can you try master? These changes were not ported to 3.28

**Comment by Graziano8890** [comment]
Yes, I tried on new 3.34 Prizren but it’s the same.

**Comment by alexbruy** [comment]
3.34 is not master. I'm talking about nightly builds, if you are using OSGeo4W installed this package is called `qgis-dev`. Sorry if I was not very clear in my previous comments.

**Comment by Graziano8890** [comment]
I’ll try this. Don’t worry thank you for the support!
