### ISSUE TITLE
App crash while trying to switch between layer styles

### ISSUE THREAD

**Issue by eronlloyd** [qgis/QGIS#55128]
## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x800706be

Current thread 0x00005f24 (most recent call first):
<no Python frame>
Windows fatal exception: code 0x800706ba

Current thread 0x00005f24 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Thread 0x00005f24 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QByteArray::QByteArray :
providerMetadataFactory :
providerMetadataFactory :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

I was trying to switch between styles on a PostGIS layer and the app crashed.The DB was remote and connected via VPN, which was still working properly before and after the crash.

### Versions

QGIS Version: 3.34.0-Prizren
QGIS code revision: ffbdd67881
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@eronlloyd , I'm afraid without more information and ideally a test project, this crash will not be addressed as it is impossible to replicate based on what is provided here.

**Comment by eronlloyd** [comment]
Understandable. I've not experienced the problem since, so will close this issue. Thanks.
