### ISSUE TITLE
Problème lors de la sélection de couche suite à un enregistrement modification

### ISSUE THREAD

**Issue by MJFDC21** [qgis/QGIS#55134]
### What is the bug or the crash?

Je rencontre un problème suite à des enregistrements de modifications de couches mais aussi lors d'exports d'entités
Lorsque j'enregistre les modifications de couche, une partie de mon polygone n'est plus sélectionnable, des erreurs de superficie apparaissent... (parfois superficie négative). De plus, lorsqu'on zoome sur le polygone en question, celui-ci disparaît (pas de visibilité à l'échelle).

### Steps to reproduce the issue

- sélection d'entités sur un projet A
- clic droit sur la couche --> exporter les entités sélectionnées sous 
![image](https://github.com/qgis/QGIS/assets/149703053/e063059b-c61b-4a99-97f7-585c356003eb)
- enregistrer les entités dans la couche désirée du projet B / ajouter à la couche
![image](https://github.com/qgis/QGIS/assets/149703053/9957a29a-d65e-4963-80ac-bdbe340b26c6)
- les entités apparaissent bien dans la couche de du projet B 
- ![image](https://github.com/qgis/QGIS/assets/149703053/03035b9a-f42f-4ec6-9ab7-7feddcc5795d)
- ouvrir le mode édition pour fusionner les entités. La totalité de l'entité est sélectionnable
![image](https://github.com/qgis/QGIS/assets/149703053/8bdd7315-dead-4354-a0f6-f2d60eda4001)
- enregistrement des modifications (certaines parties ne sont plus sélectionnables, ici la partie haute du polygone au niveau de la croix bleue) alors que la partie du bas fonctionne (au niveau de la croix rouge)
![image](https://github.com/qgis/QGIS/assets/149703053/4f077f8e-c643-47d9-9cfe-15c3df450b35)
![image](https://github.com/qgis/QGIS/assets/149703053/6be00797-819f-4cab-8c64-cceafd780ad5)

### Versions

Version de QGIS
3.28.11-Firenze
Révision du code
b02458a196
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.2
Version de Proj
9.3.0
Version de la base de données du registre EPSG
v10.094 (2023-08-08)
Version de GEOS
3.12.0-CAPI-1.18.0
Version de SQLite
3.41.1
Version de PDAL
2.5.5
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
GroupStats
2.2.7
SpreadsheetLayers
2.1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@MJFDC21m thanks for reporting. It would be useful if you could add an English description and if you could provide a sample layer in order to let a developer replicate the issue on his system and try to fix the issue if any.

**Comment by MJFDC21** [comment]
I encounter a problem following recording of layer modifications but also when exporting entities.
When I save the layer modifications, part of my polygon is no longer selectable, while it is still in my attribute table. In addition, when we zoom in on the polygon in question, it disappears.
For example, if I draw 2 separate polygons, then merge them and save, then there is only one polygon selectable, the other does not work. And that for all the modifications I want to make.

**Comment by MJFDC21** [comment]
Comment joindre une couche ?

**Comment by MJFDC21** [comment]
I encounter a problem after saving layer modifications but also when exporting entities.
When I save the layer changes, part of my polygon is no longer selectable, although it is still in my attribute table. In addition, when we zoom in on the polygon in question, it disappears.
For example, if I draw 2 separate polygons, then merge them and save them, there is only one polygon selectable, the other does not work. And this for all the modifications that I wish to make.


***@***.***

De : Andrea Giudiceandrea ***@***.***>
Envoyé : vendredi 3 novembre 2023 09:58
À : qgis/QGIS ***@***.***>
Cc : Marine JULIEN ***@***.***>; Author ***@***.***>
Objet : Re: [qgis/QGIS] Problème lors de la sélection de couche suite à un enregistrement modification (Issue #55134)


@MJFDC21m thanks for reporting. It would be useful if you could add an English description and if you could provide a sample layer in order to let a developer replicate the issue on his system and try to fix the issue if any.

**Comment by agiudiceandrea** [comment]
> Comment joindre une couche ?

Please put all the layer files in a zip archive and attach the zip archive to a comment using the GitHub web interface (dragging & dropping the zip archive in the comment while in "Write" mode).

**Comment by MJFDC21** [comment]
[TEST QGIS.zip](https://github.com/qgis/QGIS/files/13249372/TEST.QGIS.zip)

**Comment by agiudiceandrea** [comment]
@MJFDC21, it would have been great if you had provided the original layer before merging the geometry.
If the issue only occurs using an ESRI Shapefile layer, the it looks like the issue may be the same as the one previously reported at https://github.com/qgis/QGIS/issues/54537. Such issue has been fixed: the issue should not occur using QGIS 3.28.12 and QGIS 3.34.0.

**Comment by MJFDC21** [comment]
[TEST QGIS.zip](https://github.com/qgis/QGIS/files/13250314/TEST.QGIS.zip)
I traced two unmerged polygons into the layer.

**Comment by agiudiceandrea** [comment]
@MJFDC21, thanks. I can confirm the issue is the same as the one previously reported at https://github.com/qgis/QGIS/issues/54537. Please use QGIS >= 3.28.12 or QGIS >= 3.34.0 when they will be available for your OS.

**Comment by agiudiceandrea** [comment]
QGIS 3.28.12 and QGIS 3.34.0 are now available for Windows
