### ISSUE TITLE
Inform users of needed packages for Plugin support

### ISSUE THREAD

**Issue by firefoxlover** [qgis/QGIS#55136]
### Feature description

I installed qgis on Fedora 39 and tadaaa, no plugins available because no Python detected. Installed `python3`, still no support detected.

The full install command to make it work is:

```
sudo dnf install -y qgis python3-qgis
```

### Additional context

This will vary between distributions but a placeholder instead of this not very helpful message is needed, so that every Distro can add the specific package name. Or even a button, that does the install? I will report a Fedora bug too.

[Fedora Bug](https://bugzilla.redhat.com/show_bug.cgi?id=2247673)

**Comment by agiudiceandrea** [comment]
Hi @firefoxlover, thanks for reporting. The instructions to install QGIS on Fedora https://www.qgis.org/en/site/forusers/alldownloads.html#fedora already mention to install python3-qgis:

> Fedora
> Get packages for any Fedora by typing:
> 
> sudo dnf install qgis python3-qgis qgis-grass qgis-server

**Comment by firefoxlover** [comment]
I was not redirected to that site, so this was not suited to help at least in the current implementation. Also, the site is a bit outdated, as the COPR repos are currently unmaintained poorly. I could edit the page

**Comment by kannes** [comment]
This is a Fedora bug, it is their decision how to package QGIS and which dependencies are defined.

If you could update the QGIS wiki page, that would be ace!

**Comment by firefoxlover** [comment]
I will report it to fedora
