### ISSUE TITLE
Take altitude QGIS

### ISSUE THREAD

**Issue by 016852902FREDY** [qgis/QGIS#55130]
### Feature description

How to configure a field so that a point layer can take the altitude when taking data in the field after exporting to qfield.?

### Additional context

How to configure a field so that a point layer can take the altitude when taking data in the field after exporting to qfield.?

**Comment by agiudiceandrea** [comment]
Hi @016852902FREDY, "Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features."
