### ISSUE TITLE
Raster Calculator dialog box is too large in the vertical using QGIS 3.34 Prizren

### ISSUE THREAD

**Issue by robricks86** [qgis/QGIS#55140]
### What is the bug or the crash?

The size of the dialog box GUI for Raster Calculator is too large in the vertical, not allowing a user to select the buttons on the bottom of the box for processing. 

### Steps to reproduce the issue

Go to Raster on menu toolbar;
Click on Raster Calculator;
Fill out fields;
Attempt to click on Run or Cancel button, but unable to reach them below the edge of the screen. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.4
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Ubuntu 23.04
  |   |   |  
Active Python plugins
AttributeAssignment | 2.3
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.8
Python version
3.11.4
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.4 (Ubuntu 15.4-0ubuntu0.23.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Ubuntu 23.04

Active Python plugins
AttributeAssignment
2.3
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

![screen](https://github.com/qgis/QGIS/assets/11169260/b330bec8-d066-4b84-be2b-07d2a22c0759)

**Comment by DelazJ** [comment]
@robricks86 This is a new issue or it was already the case in earlier versions? You can in the meantime collapse the "Operators" group to reach the buttons...

**Comment by robricks86** [comment]
Thanks for the tip!
