### ISSUE TITLE
Layer Filter not used for multiple GRASS processing functions

### ISSUE THREAD

**Issue by disarticulate** [qgis/QGIS#55155]
### What is the bug or the crash?

I have a *.gpkg with multiple 3d MultiPolygonZ features in a table, which I split into multiple layers based on filter functions like so:
```"object" IN ('2023-10-23-CD-SURVEY')```

I've tried two functions and I assume more are affected:
```v.clean from GRASS: It ignores the layer filter and cleans _every_ row in the table```

```TIN Interpolation: crashes with vague error:
File "C:\PROGRA~1/QGIS33~1.3/apps/qgis/./python/plugins\processing\algs\qgis\TinInterpolation.py", line 187, in processAlgorithm
writer.writeFile(feedback)
Exception: unknown
```
For the TIN, I assume one of the other layers has the problem, but the v.clean algorithm clearly cleans _all_ the rows and not just the filtered one.

### Steps to reproduce the issue

1. Create a geopackage with multiple rows with geometry (MultiPolygonZ) in this case
2. Create an arbitrary filter to select a single row (or more?)
3. Run a processing function on that layer such as ```v.clean```

### Versions

QGIS version
3.32.3-Lima
QGIS code revision
67d46100b5
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.3.1
changeDataSource
3.1
DEMto3D
3.6
FreehandRasterGeoreferencer
0.8.3
HCMGIS
23.7.19
pg_raster_import
3.2.0
Qgis2threejs
2.7.1
qgiscloud
3.8.13
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I can provide a reference file if someone can't reproduce the above. This seems like a reversion but I tried it in 3.28.10, with the same result. It's only obvious when there's features that overlap, which is often.

I searched briefly for other potential duplicates but didn't see anything. Seems odd this wouldn't be noticed elsewhere.

**Comment by uclaros** [comment]
This seems to apply to grass processing algorithms only. Can you confirm and update the title/description accordingly?

**Comment by disarticulate** [comment]
Can confirm, it does look like it's related to GRASS. The TIN interpolation appears un affected when I attempted a different layer.
