### ISSUE TITLE
SAGA error while running Channel Network and Drainage Basins

### ISSUE THREAD

**Issue by anandhusjone** [qgis/QGIS#55164]
### SAGA error while running Channel Network and Drainage Basins

QGIS version: 3.34.0-Prizren
QGIS code revision: ffbdd678812
Qt version: 5.15.3
Python version: 3.10.12
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: Release)
SAGA Next Gen version: 1.0.0
Algorithm started at: 2023-11-04T13:02:37
Algorithm 'Channel network and drainage basins' starting…
Input parameters:
{ 'BASIN' : 'TEMPORARY_OUTPUT', 'BASINS' : 'TEMPORARY_OUTPUT', 'CONNECTION' : 'TEMPORARY_OUTPUT', 'DEM' : '/tmp/processing_jFVHbY/c71f7863c5cd40b98a83e56596437892/TARGET_OUT_GRID.sdat', 'DIRECTION' : 'TEMPORARY_OUTPUT', 'NODES' : 'TEMPORARY_OUTPUT', 'ORDER' : 'TEMPORARY_OUTPUT', 'SEGMENTS' : 'TEMPORARY_OUTPUT', 'SUBBASINS' : True, 'THRESHOLD' : 5 }

Problem with SAGA installation: unsupported SAGA version (found: 7.3.0, required: >=9.1.).
ta_channels "5" -DEM "/tmp/processing_jFVHbY/35f004a1f92d49288c8836a5943964d4/TargetGrid.sgrd" -THRESHOLD 5 -SUBBASINS true -DIRECTION "/tmp/processing_jFVHbY/26054a9b76bc4e2694fd7c85891223af/DIRECTION.sdat" -CONNECTION "/tmp/processing_jFVHbY/8f09f4a88306449b81f7f0f244fe973f/CONNECTION.sdat" -ORDER "/tmp/processing_jFVHbY/4b99f7ff5a414954b4bb1b0e50766cba/ORDER.sdat" -BASIN "/tmp/processing_jFVHbY/69b59a2344fa4524b20cae335ceb4d19/BASIN.sdat" -SEGMENTS "/tmp/processing_jFVHbY/6a47017369c84ccfaa2f03f81c4e09cc/SEGMENTS.shp" -BASINS "/tmp/processing_jFVHbY/5813a16995c8486280959a1abffa86a7/BASINS.shp" -NODES "/tmp/processing_jFVHbY/63312dc8e86f405284e478ce48ce888b/NODES.shp"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.3.0

Unknown option 'SUBBASINS'
____________________________
library path: /usr/lib/x86_64-linux-gnu/saga/
library name: libta_channels
library : ta_channels
tool : Channel Network and Drainage Basins
identifier : 5
author : O.Conrad (c) 2003
processors : 16 [16]
____________________________

Usage: saga_cmd ta_channels 5 [-DEM <str>] [-DIRECTION <str>] [-CONNECTION <str>] [-ORDER <str>] [-BASIN <str>] [-SEGMENTS <str>] [-BASINS <str>] [-NODES <str>] [-THRESHOLD <num>]
-DEM:<str> Elevation
Grid (input)
-DIRECTION:<str> Flow Direction
Grid (optional output)
-CONNECTION:<str> Flow Connectivity
Grid (optional output)
-ORDER:<str> Strahler Order
Grid (optional output)
-BASIN:<str> Drainage Basins
Grid (optional output)
-SEGMENTS:<str> Channels
Shapes (output)
-BASINS:<str> Drainage Basins
Shapes (output)
-NODES:<str> Junctions
Shapes (optional output)
-THRESHOLD:<num> Threshold
Integer
Minimum: 1
Default: 5
Execution completed in 0.19 seconds
Results:
{'BASIN': '/tmp/processing_jFVHbY/69b59a2344fa4524b20cae335ceb4d19/BASIN.sdat',
'BASINS': '/tmp/processing_jFVHbY/5813a16995c8486280959a1abffa86a7/BASINS.shp',
'CONNECTION': '/tmp/processing_jFVHbY/8f09f4a88306449b81f7f0f244fe973f/CONNECTION.sdat',
'DIRECTION': '/tmp/processing_jFVHbY/26054a9b76bc4e2694fd7c85891223af/DIRECTION.sdat',
'NODES': '/tmp/processing_jFVHbY/63312dc8e86f405284e478ce48ce888b/NODES.shp',
'ORDER': '/tmp/processing_jFVHbY/4b99f7ff5a414954b4bb1b0e50766cba/ORDER.sdat',
'SEGMENTS': '/tmp/processing_jFVHbY/6a47017369c84ccfaa2f03f81c4e09cc/SEGMENTS.shp'}

Loading resulting layers
The following layers were not correctly generated.
• /tmp/processing_jFVHbY/26054a9b76bc4e2694fd7c85891223af/DIRECTION.sdat
• /tmp/processing_jFVHbY/4b99f7ff5a414954b4bb1b0e50766cba/ORDER.sdat
• /tmp/processing_jFVHbY/5813a16995c8486280959a1abffa86a7/BASINS.shp
• /tmp/processing_jFVHbY/63312dc8e86f405284e478ce48ce888b/NODES.shp
• /tmp/processing_jFVHbY/69b59a2344fa4524b20cae335ceb4d19/BASIN.sdat
• /tmp/processing_jFVHbY/6a47017369c84ccfaa2f03f81c4e09cc/SEGMENTS.shp
• /tmp/processing_jFVHbY/8f09f4a88306449b81f7f0f244fe973f/CONNECTION.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Steps to reproduce the issue

Just ran the SAGA Next Gen for Channel Network and Drainage Basins using an ALOS PALSAR DEM. Tried it in other machines that is running qgis 3.22.7 , 3.32, and 3.34 but the same error popped up.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
SRTM-Downloader | 3.2.0
CityJSON-loader | 0.8.1
qgis_resource_sharing | 1.0.0
mmqgis | 2021.9.10
citygen | 0.3
moving_feature | 2.0
profiletool | 4.2.6
QWater | 3.1.8
nominatim | 1.4.5
ViewshedAnalysis | 1.8
los_tools | 1.0
quick_map_services | 0.19.33
annotationManager | 0.5
DataPlotly | 4.0.3
MultiJoin | 1.0
QuickOSM | 2.2.3
DEMto3D | 3.51
joinmultiplelines | Version 0.4.1
LAStools | 1.4
easy_raster_splitter | 2.1
location_lab | 2.2.2
NNJoin | 3.1.3
ORStools | 1.6.0
latlontools | 3.6.16
google_maps_geocoder | 0.0.3
OSMDownloader | 1.0.3
Qgis2threejs | 2.7.1
ProjectPackager | 0.7.2
qgis_geonode | 1.0.1
qgis2web | 3.16.0
SemiAutomaticClassificationPlugin | 8.1.0
postgis_geoprocessing | 0.9
QPackage | 1.5
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
processing_saga_nextgen
1.0.0
SRTM-Downloader
3.2.0
CityJSON-loader
0.8.1
qgis_resource_sharing
1.0.0
mmqgis
2021.9.10
citygen
0.3
moving_feature
2.0
profiletool
4.2.6
QWater
3.1.8
nominatim
1.4.5
ViewshedAnalysis
1.8
los_tools
1.0
quick_map_services
0.19.33
annotationManager
0.5
DataPlotly
4.0.3
MultiJoin
1.0
QuickOSM
2.2.3
DEMto3D
3.51
joinmultiplelines
Version 0.4.1
LAStools
1.4
easy_raster_splitter
2.1
location_lab
2.2.2
NNJoin
3.1.3
ORStools
1.6.0
latlontools
3.6.16
google_maps_geocoder
0.0.3
OSMDownloader
1.0.3
Qgis2threejs
2.7.1
ProjectPackager
0.7.2
qgis_geonode
1.0.1
qgis2web
3.16.0
SemiAutomaticClassificationPlugin
8.1.0
postgis_geoprocessing
0.9
QPackage
1.5
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by shikafali** [comment]
Same issue

**Comment by agiudiceandrea** [comment]
@anandhusjone, thanks for reporting. The issue is caused by the plugin processing_saga_nextgen "Processing Saga NextGen Provider", not by QGIS itself. The issue is due to the fact that the version 1.0.0 of the plugin is designed for SAGA-GIS 9.1 (as stated in the plugin [description](https://plugins.qgis.org/plugins/processing_saga_nextgen/) and in the processing log), while you are using SAGA-GIS version 7.3.0 in which the SUBBASINS option is not available for the Channel Network and Drainage Basins tool.
You can try to use a previous version of the plugin or manually modify the ta_channels_channel_network_and_drainage_basins.txt "description" file. You can also report the issue on the plugin GitHub repository at https://github.com/north-road/qgis-processing-saga-nextgen.
