### ISSUE TITLE
Print layout toolbars visibility not remembered

### ISSUE THREAD

**Issue by JBacc1** [qgis/QGIS#55169]
### What is the bug or the crash?

When opening/closing/opening the print layout window, the disposition of the different toolbars is remembered. However, their visibility (or rather, unvisibility) is not remembered. 
("No, I really do not want this Atlas Toolbar, that has not the same width than the other toolbars and will therefore not be anchored, to be visible. And yes, I'll keep hiding it again and again.")

### Steps to reproduce the issue

Go to the print layout window
Hide the Atlas toolbar (right click or View/Toolbars)
Close the print layout window
Open the print layout window
"Ha, there is the Atlas toolbar again!"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Linux Mint 21.2

Active Python plugins
quick_map_services
0.19.33
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by YoannQDQ** [comment]
This only applies to the Atlas Toolbar. 

Culprit seems to be the `createAtlasWidget` method that always shows the atlas toolbar.

https://github.com/qgis/QGIS/blob/2d4258a35f1a2d99b29e321ae63c85440c685029/src/app/layout/qgslayoutdesignerdialog.cpp#L4119-L4130
