### ISSUE TITLE
CRS instances become invalid in python test environments

### ISSUE THREAD

**Issue by jakimowb** [qgis/QGIS#55161]
### What is the bug or the crash?

The `qgis.test.start_app` function initializes a QgsApplication instance and allows to use the PyQGIS API.
However, if a `QgsCoodinateReferenceSystem` instances are used before calling `start_app`, it is not possible to create valid CRS instances from WKT strings.

Assume we have a python code like:
````python
# it is supposed to be good style to have the import first 
from qgis.testing import start_app
from my.deep.nested.code.structure import myfunction


start_app() #  
````
If somewhere in the (potentially many) imports a call is made to `QgsProject.instance()` or a `QgsCoordinateReferenceSystem` is created, the following code will raise an exception in case of the last assert statement:

````python
crs1 = QgsCoordinateReferenceSystem('EPSG:4326')
assert crs1.isValid()
crs2 = QgsCoordinateReferenceSystem.fromWkt(crs1.toWkt())
assert crs2.isValid()  # <-- raises error
````

### Steps to reproduce the issue

Run the following python code that calls `qgis.testing.start_app` to initialize a `QgsApplication`:

```python
from qgis.testing import start_app
from qgis.core import QgsCoordinateReferenceSystem, QgsProject, Qgis

print(f'QGIS Version: {Qgis.version()}  ({Qgis.versionInt()})')

# if a QgsCoordinateReferenceSystem instance is created before start_app(), the assert in the last line will fail
if True:

    # something like the following definition might be used deep in a nested python project structure
    # and this way become hard to detect
    def myCrs(crs: QgsCoordinateReferenceSystem = QgsCoordinateReferenceSystem('EPSG:4326')):
        print(f'CRS: {crs}')

start_app()

crs1 = QgsCoordinateReferenceSystem('EPSG:4326')
assert crs1.isValid()
crs2 = QgsCoordinateReferenceSystem.fromWkt(crs1.toWkt())
assert crs1.toWkt() == crs2.toWkt()
assert crs2.isValid()  # <-- raises error

```

### Versions

QGIS 3.34 and 3.35 (Ubuntu and OSGeo4W)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
We should probably crash if we don't have a `QgsApplication`, just like when a `QWidget` is used before a `QApplication` is constructed.

```py
>>> from PyQt5.QtWidgets import QWidget
>>> QWidget()
QWidget: Must construct a QApplication before a QWidget
[1]    951044 IOT instruction (core dumped)
```

**Comment by Joonalai** [comment]
I think there is a bug introduced in QGIS 3.34 causing this behaviour. 

During investigating of [pytest-qgis issue](https://github.com/GispoCoding/pytest-qgis/issues/56), I reproduced the issue and traced down the reason into line `QGISAPP = QgsApplication(argvb, myGuiFlag)`. In fact, just creating QgsApplication object (and saving the reference into variable) anywhere in the code makes crs behave oddly in some occasions. 

Running the following test with unittest framework works just fine, but when running it with pytest (even with no other libraries installed), the last assert fails. 

```python
import unittest
from pathlib import Path

from qgis.core import (
    QgsApplication,
    QgsCoordinateReferenceSystem,
    QgsRasterLayer,
    QgsVectorLayer,
)

app = QgsApplication([], GUIenabled=False)


class TestCrs(unittest.TestCase):
    def test_crs_copying(self):
        crs1 = QgsCoordinateReferenceSystem("EPSG:4326")
        assert crs1.isValid()
        crs2 = QgsCoordinateReferenceSystem.fromWkt(crs1.toWkt())
        assert crs1.toWkt() == crs2.toWkt()
        assert crs2.isValid()  # <-- raises error
```

As can be seen in [actions  run of pytest-qgis](https://github.com/GispoCoding/pytest-qgis/actions/runs/7253713952/job/19760910411?pr=57), it worked just fine with QGIS versions before QGIS 3.34.
