### ISSUE TITLE
Merge Tool Error

### ISSUE THREAD

**Issue by Angus-Fiona** [qgis/QGIS#55188]
### What is the bug or the crash?

After merging features, only one of the merges polygons becomes 'clickable' and therefore only one is understood (by QGIS) to exist. Visually this has no effect, as the polygons appear merged, however, when trying to use these polygons within an Atlas, QGIS will only focus on one of the polygons and exclude the other. 

This issue is affecting a handful of user - not all - who upgraded to 3.28.9. Reverting back to the previous version (within the organisation that's 3.22) fixes this issue. 

### Steps to reproduce the issue

1. Select two polygons, click merge tool, then okay
2. Polygons appear merged. Use select tool to select any area of merged poly
3. If selecting an area that was previously part of the larger polygon (I think), whole polygon will highlight 
4. if selecting an area that was previously part of the smaller polygon, nothing will highlight

This issue is only affecting a small amount of users, and whilst they can replicate the issue on their machine, I can not replicate it on mine. For me it works as it should. 

### Versions

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
BulkVectorExport
1.1
Discovery
2.5.8
pg_metadata
1.2.2
qfieldsync
v4.6.0
quick_map_services
0.19.33
SelectWithin
0.4
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Angus-Fiona, thanks for reporting. The described issue (already reported: https://github.com/qgis/QGIS/issues/55134, https://github.com/qgis/QGIS/issues/54537) occurred with QGIS LTR <= 3.28.11 and QGIS <= 3.32.3 only when using GDAL 3.7 library and only when editing ESRI Shapefile layers.
The issue has been fixed (https://github.com/qgis/QGIS/pull/54761, https://github.com/OSGeo/gdal/pull/8483) and no longer occurs using QGIS 3.28.12 and QGIS 3.34.0.
Feel free to reopen this issue report if you find that the issue still occurs using QGIS >= 3.28.12 or QGIS >= 3.34.0.
