### ISSUE TITLE
Csw add services does not add the services to  the  wms(t)services menu

### ISSUE THREAD

**Issue by kungzlatan** [qgis/QGIS#55183]
### What is the bug or the crash?

Add data does not add the selected data to the wms(t) layer box 

see video

https://github.com/qgis/QGIS/assets/61743853/a11c2fba-6769-4732-bf75-77427a3c8787

it try to use the latest used wms connection instead

it was fine in version 2.28 and below

see video

https://github.com/qgis/QGIS/assets/61743853/6c2aff97-d458-4140-8a8d-3d4deeee0ec9

### Steps to reproduce the issue

See videos

### Versions

![image](https://github.com/qgis/QGIS/assets/61743853/3ba67f6a-e4b3-4084-a877-c4bc423316ef)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@3nids, this issue may be related to the change in the settings handling like it was https://github.com/qgis/QGIS/issues/54144. Could you please have a look?

**Comment by 3nids** [comment]
I'm not very familiar with MetaSearch.

I just gave it a try this morning and could not reproduce:
1. Add default services
2. Set the Canadian one
3. Do a search
4. Load layer as WMS

and it worked as expected (layer loaded in QGIS).

I did several tries and it worked each time.

**Comment by kungzlatan** [comment]
https://github.com/qgis/QGIS/assets/61743853/16522ed1-5b15-44aa-99aa-ee9ff5c33fd0

It always use the latest used wms/wmts services you have added before

in the video it adds osm instead of the services i find in the meta serach due to i used the osm services before.

could maybe be if you never had add a wms/wmts services it works from meta serach

**Comment by agiudiceandrea** [comment]
@kungzlatan, it would be useful if you could provide detailed step by step instructions starting from a new QGIS user profile.
Could you also confirm the issue doesn't occur using QGIS 3.28?

**Comment by kungzlatan** [comment]
Does work when i created a new profile

**Comment by agiudiceandrea** [comment]
@3nids, the issue may have the same root cause of various previous issues which involves user profile created with QGIS 3.28 and used with QGIS >= 3.32.

**Comment by 3nids** [comment]
I still cannot reproduce:

1. open QGIS 3.28, add WMS url
2. open QGIS 3.34, open metasearch => the correct WMS group is set

**Comment by agiudiceandrea** [comment]
Thanks both for checking.
@kungzlatan, please reopen this issue report when you find a reproducible way to replicate the issue.
