### ISSUE TITLE
Wrong version picture in installer for windows

### ISSUE THREAD

**Issue by kungzlatan** [qgis/QGIS#55184]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/61743853/e674a17e-5c49-4d61-8311-ad65e19db748)

### Steps to reproduce the issue

Download the installer (windows version) from https://www.qgis.org/en/site/forusers/download.html and launch it

### Versions

![image](https://github.com/qgis/QGIS/assets/61743853/703b05a7-b742-4d5e-9ca6-ac494f3afa40)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@kungzlatan, thanks for reporting. Since this issue is related to the OSGeo4W installer, I've filed an issue report on the OSGeo4W isntaller/packaging tickets system: https://trac.osgeo.org/osgeo4w/ticket/809.

**Comment by agiudiceandrea** [comment]
@kungzlatan, the issue has been allegedly fixed in the latest currently available installer QGIS-OSGeo4W-3.34.0-2.msi.

**Comment by kungzlatan** [comment]
Yes did download and installed it. was correct now so issue could be closed @agiudiceandrea

**Comment by agiudiceandrea** [comment]
Thanks for checking. The issue has been already closed.
