### ISSUE TITLE
3.34 Prizren unavailable for Mac

### ISSUE THREAD

**Issue by gregmohler** [qgis/QGIS#55185]
### What is the bug or the crash?

The "Download for macOS" [link](https://qgis.org/downloads/macos/qgis-macos-pr.dmg) points to 3.32.3-Lima.
The [pr-latest.png](https://download.qgis.org/downloads/macos/qgis-macos-pr.latest.png) shows "failed".
It looks like it has been failing everyday since 10/27 in the [pr directory](https://download.qgis.org/downloads/macos/pr/?C=M;O=D).

### Steps to reproduce the issue

Go to: https://qgis.org/en/site/index.html
Click "Download" to go: https://qgis.org/en/site/forusers/download.html
Download from Mac section: https://qgis.org/downloads/macos/qgis-macos-pr.dmg
Installs 3.32.3 from 9/15.

### Versions

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5b
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.6
Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

QGIS version
3.32.3-Lima
QGIS code revision
[67d46100b5b](https://github.com/qgis/QGIS/commit/67d46100b5b)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 13.6

Active Python plugins
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
QGIS 3.34.0 dmg installer macOS is available now.

**Comment by gregmohler** [comment]
@agiudiceandrea Thank you.
