### ISSUE TITLE
Add missing variable " @row_number " to filter-rule-expessions in rule-based-symbology

### ISSUE THREAD

**Issue by koenigherford** [qgis/QGIS#55201]
### Feature description

It will be great to have access to a  missing-"@row_number "-variable in filter-rule-expressions in rule-based-symbology.

This will -for example - allow to highlight the last unsaved digitized feature by a different symbology. Till now you you are only able to do this in a state, when all features are saved (by "id"=aggregate( 'my_layer, 'max',"id"). By implementing this this will work in a unsaved state too.

![grafik](https://github.com/qgis/QGIS/assets/28433436/5e73ef98-e4d0-4b7f-b431-a7bf7311089e)

**Comment by nyalldawson** [comment]
This isn't really possible -- there's no concept of "rows" during rendering, and only the features currently in the visible map extent (and which match the rule based filter rules) are fetched and available for counting. So if we added an incremental counter and called it "row_number" here, it's going to be misleading as row 1 will differ depending on the visible map extent.
