### ISSUE TITLE
Crash when query/filter for NULL 

### ISSUE THREAD

**Issue by Bernd-Vogelgesang** [qgis/QGIS#55202]
### What is the bug or the crash?

When trying to either filter layer rows for multiple NULL values in multiple fields, create a new field based on a CASE WHEN ... IS NULL OR ... etc, QGIS is crashing while typing the parameters either in the filter query or in the field calculator window.

Testing a filter with only one NULL query gives "An error occurred when executing the query, please check the expression syntax." which is not found in the Messages.

This happened some versions before, as I recall.

### Steps to reproduce the issue

1. Create a new project and a new geopackage point layer
2. Create some columns a, b, c, d (string, integer, datetime etc)
3. Create some points, leaving out entries for one, more or no field.
4. Right-click layer in the panel -> choose Filter ...
5. Filter for rows which are complete (have no NULL value): "a" IS NOT NULL OR "b" IS NOT NULL ...
6. While typing the second NOT NULL, QGIS is crashing

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.6.4
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.37.2
PDAL version | 2.5.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.6.4
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.37.2
PDAL version
2.5.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Linux Mint 21.2

Active Python plugins
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Bernd-Vogelgesang** [comment]
Update. The problem does not seem to be the NULL in the query, but the OR.
QGIS just crashed on another layer query not including any NULL parameters

**Comment by Bernd-Vogelgesang** [comment]
Next update. Filters also crash with AND

**Comment by uclaros** [comment]
And the crash happens while typing? Do you have a stacktrace?
