### ISSUE TITLE
Incorrect location of North arrow and Scale bar

### ISSUE THREAD

**Issue by NHM55** [qgis/QGIS#55204]
### What is the bug or the crash?

Two map 'decorations' that I routinely use --the North Arrow and the Scale Bar-- will not properly locate themselves in upper LH corner and lower RH corner. They are stuck about halfway across the map. This started a week ago when I went from full screen to a much smaller window. The problem occurs in any project file. 

I have downloaded latest version of qGIS, saved without the two items being shown, etc., but nothing changes. 

### Steps to reproduce the issue

See screenshot:
![image](https://github.com/qgis/QGIS/assets/86746323/def9ae99-08d1-4f8e-babe-758a012e7863)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd67881
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AzimuthDistanceCalculator | 2.0.2
ee_plugin | 0.0.6
FreehandRasterGeoreferencer | 0.8.3
GeometryShapes | 0.7
getthemfiltered | 0.2.0
GroupStats | 2.2.7
ImportPhotos | 3.0.5
indiana_ortho | 0.1.7
LAStools | 1.5
layerGroupFilter | 0.2
LocatePoints | 0.3.4
mmqgis | 2021.9.10
numericalDigitize | 0.4.7
pointsamplingtool | 0.5.4
profiletool | 4.2.6
qgis_resource_sharing | 1.0.0
qgsAzimuth | 0.9.16
qtiles | 1.7.2
quick_map_services | 0.19.33
raster_tracer | 0.3.3
toggle_labels_widget | 1.0.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd67881](https://github.com/qgis/QGIS/commit/ffbdd67881)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AzimuthDistanceCalculator
2.0.2
ee_plugin
0.0.6
FreehandRasterGeoreferencer
0.8.3
GeometryShapes
0.7
getthemfiltered
0.2.0
GroupStats
2.2.7
ImportPhotos
3.0.5
indiana_ortho
0.1.7
LAStools
1.5
layerGroupFilter
0.2
LocatePoints
0.3.4
mmqgis
2021.9.10
numericalDigitize
0.4.7
pointsamplingtool
0.5.4
profiletool
4.2.6
qgis_resource_sharing
1.0.0
qgsAzimuth
0.9.16
qtiles
1.7.2
quick_map_services
0.19.33
raster_tracer
0.3.3
toggle_labels_widget
1.0.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@NHM55, thanks for reporting. Could you please try if the issue does occur also actually using a new QGIS user profile without any external plugin isntalled?

**Comment by agiudiceandrea** [comment]
@NHM55, thanks for reporting. Could you please try if the issue does occur also actually using a new QGIS user profile without any external plugin isntalled?

**Comment by NHM55** [comment]
I tried with a new profile and no external plugins. Sorry to say, but the misplaced Decorations problem is still unresolved.

**Comment by NHM55** [comment]
Hi Andrea,

RE: Misplaced canvas decorations ('N arrow' and 'Scale bar')

Today I took the following steps:

- Uninstalled version 3.34.0.
- Opened an existing project file in 3.32.3 using the new profile that I created yesterday. The 'N arrow' and 'Scale bar' decorations both appeared in the correct location on the canvas.
- I then reloaded version 3.34.0 and opened the same project (as in Step 2), again using the new profile. Upon loading, the N arrow and scale bar were not placed correctly, i.e. they were both in locations toward the center of the canvas. The placement of the decorations suggests that software shifted them inward for a less-than-full-screen canvas but can't relocate outward for a full-screen canvas. See screenshots, below.

Conclusion: Decoration location is correct in 3.32.3 but incorrect in 3.34.0. It would appear the bug is in newest version.

Chris M.

[image.png]

[image.png]

**Comment by YoannQDQ** [comment]
This is very probably linked to #53891

**Comment by ReinierNL** [comment]
I have the same problem. It seems that this is related to using scaling on a high dpi monitor.
When I move the QGIS window to my not-scaled monitor, the 'problem' goes away.
It seems that the decorations (at the bottom or at the right, but also middle) calculate their position in pixels wrong, by a factor (in my case) of 1 / 150%.

**Comment by NHM55** [comment]
Reinier,

Thank you for your comment. You are light years ahead of me in terms of understanding the technical aspects of monitors and what can go wrong.

I certainly hope folks at qGIS are reading this.

CM

**Comment by NHM55** [comment]
Excellent. Thank you!!

CM

**Comment by NHM55** [comment]
Hi Andrea,

I am having difficulties with GRASS. Specifically, several raster algorithms that I frequently use simply aren't working. Sorry, but I do not know if GRASS is considered a plugin or a core component of QGIS. Where should I report this problem or seek more help. Any advice?

FYI: I'm running 3.34.1.

By the way, the new release has resolved my earlier problem with mis-placed North arrow and Scale bar. Thanks again to all who worked on correcting this particular issue.

Thanks for your assistance,

Chris Mumford

**Comment by NHM55** [comment]
Thank you. And my apologies for the incorrect contact method.

**Comment by agiudiceandrea** [comment]
Hope you have fixed both the old ad the new issue.

**Comment by NHM55** [comment]
Thanks again for your help, Andrea, and yes, all is good today with qGIS.

Chris M.
