### ISSUE TITLE
Unsupported Data Source: ecw is not a supported raster data source

### ISSUE THREAD

**Issue by Korto19** [qgis/QGIS#55205]
### What is the bug or the crash?

After yesterday update Qgis dev not load ecw

### Steps to reproduce the issue

Load a raster ecw 

### Versions

QGIS version 3.35.0-Master
QGIS code revision b508e4f87e
Qt version 5.15.3
Python version 3.9.5
Compiled against GDAL/OGR 3.8.0dev-18e2079c60
Running against GDAL/OGR 3.8.0beta1
PROJ version 9.3.0
EPSG Registry database version v10.094 (2023-08-08)
GEOS version 3.12.0-CAPI-1.18.0
SQLite version 3.41.1
PDAL version 2.5.5
PostgreSQL client version 15.2
SpatiaLite version 5.1.0
QWT version 6.1.6
QScintilla2 version 2.13.4
OS version Windows 11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pigreco** [comment]
I confirm although the library is installed

![image](https://github.com/qgis/QGIS/assets/7631137/31076b9c-ec50-4abe-bf60-e090bb5926aa)

**Comment by agiudiceandrea** [comment]
@Korto19 since the issue is very likely related to the OSGeo4W installer and GDAL/OGR and ECW plugin builds from OSGeo4W and not to QGIS itself, such issue should be reported to https://trac.osgeo.org/osgeo4w/.

**Comment by agiudiceandrea** [comment]
@Korto19, thanks for reporting. Since the issue is very likely related to the OSGeo4W installer and GDAL/OGR and ECW plugin builds from OSGeo4W and not to QGIS itself, such issue should be reported to https://trac.osgeo.org/osgeo4w/.

**Comment by agiudiceandrea** [comment]
@Korto19 @pigreco anyway it looks like the issue no longer occurs using the latest available qgis-dev qgis-dev-3.35.0-621-9b2c94e2e3-1 with gdal-dev dev309-runtime-3.9.0-422-170bc256a6-1.
