### ISSUE TITLE
Possibility to rename an attachment based on expression

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#55203]
### Feature description

It would be good to allow user to duplicate an attachment in the form with a new name (and location) based on an expression. Currently, the user can only select a file and link it in the form from an existing path and filename. But for a more organised document management, it would be useful, to have the possibility to make a copy of the file with an expression based name (& path).

**Comment by uclaros** [comment]
This was implemented in #43882 :
I believe _Storage Type: Simple Copy_ does what you describe

**Comment by saberraz** [comment]
@uclaros indeed, the PR addresses half of this feature request:
- Renaming path :heavy_check_mark: 
- Renaming file is not supported ❌

**Comment by saberraz** [comment]
OK, it looks like the path expression works for the filename too.
