### ISSUE TITLE
QGIS corrupting TAB file

### ISSUE THREAD

**Issue by matjash** [qgis/QGIS#55222]
### What is the bug or the crash?

Tab file was created in QGIS, all worked fine. When I tried to add column, i could not save changes so i discarded them. After this, layer was empty, also I couldnt import layer anymore, I got Invalid data source error. 

Behaviour is not consistent, sometimes I can successfuly add field.
When I opened .tab in notepad I noticed number of fields was increased by one but field was not listed:

!table
!version 300
!charset Neutral

Definition Table
  Type NATIVE Charset "Neutral"
  Fields 3
    id Integer (10) ;
    poba_st Char (8) ;

### Steps to reproduce the issue

1. Toggle editing
2. New field
3. 
![slika](https://github.com/qgis/QGIS/assets/32578708/f04a8602-366c-4cf3-b7aa-59083fec746e)

4. Error:
Could not commit changes to layer 4_spremembe_SDOPN2_preseki

Errors: ERROR: 1 new attribute(s) not added
  
  Provider errors:
      OGR error creating field EUP_OZN: WriteTABFile(): Unsupported field type

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.11-Firenze | QGIS code revision | b02458a196
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
StreetView | 3.2
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.11-Firenze
QGIS code revision
[b02458a196](https://github.com/qgis/QGIS/commit/b02458a196)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by blacktesta** [comment]
I confirm this bug. I've been dealing with it for a long time and some other difficulties QGIS handling tab format. Like wrong geometry type (it has to be multi every time for tab format), wrong coordinates after saving (in situation when for example defined BOUNDS gives 0.01 coordinate accuracy and geometry precision of layer properties is 0.01. After saving layer raw coordinates can differ from edited in QGIS. Its like rounding working differently in QGIS and MITAB). But tab is a shitty format for nowdays and I use it only because of my organisation uses it. IMHO its better for users to use geopackage rather than QGIS developers must to mess around with legacy format.

**Comment by Gis-kost** [comment]
This bug ist fix in new fersion 3.34

**Comment by rouault** [comment]
> This bug ist fix in new fersion 3.34

closing then
