### ISSUE TITLE
native:buffer selectedFeaturesOnly

### ISSUE THREAD

**Issue by Octansf** [qgis/QGIS#55237]
### What is the bug or the crash?

I'm working in Windows 10 with QGIS 3.28.12-Firenze. I'm new one with pyqgis.
When I use Processing Toolbox: Buffer, I can use the parameter Selected Features Only. I can check or not this parameter and the result layer is correct.
But when I try to use this script inside of python script the result layer is empty, when I use the parameter Selected Features Only equal True; if this parameter is False the result layer is correct.
I can't explain what happend. I try everything. New project, with only one layer. Existing Project with others layer. And de result layer always is empty when mark Selected Feature Only equal True.

This is part of code:

try:

lay = processing.run("native:buffer",  
    { 
        'INPUT': QgsProcessingFeatureSourceDefinition(v3.dataProvider().dataSourceUri() 
        , selectedFeaturesOnly=False  # With False,  works correcto. In True, result layer is empty.
        , featureLimit=-1 
        , geometryCheck=QgsFeatureRequest.GeometryNoCheck) 
        ,'DISTANCE':0.004500 
        ,'SEGMENTS':5 
        ,'END_CAP_STYLE':0 
        ,'JOIN_STYLE':0 
        ,'MITER_LIMIT':2 
        ,'DISSOLVE':False 
        ,'OUTPUT':  'ogr:dbname=\'D:/tmp/mbt_4/buf_4_85300.gpkg\' table="buf_layer" (geom)' 
        }, context=ct, feedback=fb); 
except Exception as e:

QgsMessageLog.logMessage(str(e),'Buffer_test', Qgis.Info) 

### Steps to reproduce the issue

Open Plugin menu
Deploy Python Console 
And write python code in console
You can show editor and create python scripts, save python script and running

### Versions

QGIS version 
3.28.12-Firenze 
QGIS code revision 
dcc633b2de 
Qt version 
5.15.3 
Python version 
3.9.5 
Compiled against GDAL/OGR 
3.7.2 
Running against GDAL/OGR 
3.7.3 
PROJ version 
9.3.0 
EPSG Registry database version 
v10.094 (2023-08-08) 
GEOS version 
3.12.0-CAPI-1.18.0 
SQLite version 
3.41.1 
PDAL version 
2.5.5 
PostgreSQL client version 
unknown 
SpatiaLite version 
5.1.0 
QWT version 
6.1.6 
QScintilla2 version 
2.13.4 
OS version 
Windows 10 Version 2009 

 Active Python plugins 
MBTiles2img 
0.4 
plugin_reloader 
0.9.3 
QMetaTiles 
1.5 
qrbarcodeitem 
0.2.0 
Submission 
0.7 
tile_index_generator 
1.0 
union_mbtiles 1a 
1a 
zoom_level 
0.1 
processing 
2.12.99 
genera_mbtiles_vx1 
x1 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
and can you get the right number of selected features from your vector layer https://qgis.org/pyqgis/master/core/QgsVectorLayer.html#qgis.core.QgsVectorLayer.selectedFeatures

**Comment by Octansf** [comment]
I try with one and two Selected Features, I tried before with Little more

**Comment by uclaros** [comment]
This is not a bug.
You're passing the layer's _URI_ as a source for the algorithm, not the actual layer, so the algorithm does not see the selection.
Pass the layer object instead, and it should work as you'd expect. :)

**Comment by Octansf** [comment]
> This is not a bug. You're passing the layer's _URI_ as a source for the algorithm, not the actual layer, so the algorithm does not see the selection. Pass the layer object instead, and it should work as you'd expect. :)

Hi uclaros, your recommendation does not work. It does nothing when you run the script. Before changing the uri to the layer object, it created the empty layer now it does nothing. For other side, how can you explain when I marked selectedFeaturesOnly = False the algorithm run perfectly and build de layer with the buffer of the objects? Thanks

**Comment by uclaros** [comment]
Hi @Octansf , sorry, `QgsProcessingFeatureSourceDefinition` needs the _layer id_ instead, not the layer.

Here's a working sample:
```python
vl = QgsVectorLayer('Point?crs=EPSG:4326', 'points', 'memory')
f = QgsFeature()
f.setGeometry(QgsPoint(1, 1))
vl.dataProvider().addFeature(f)
f.setGeometry(QgsPoint(2, 2))
vl.dataProvider().addFeature(f)
QgsProject.instance().addMapLayers([vl])
vl.select(1)

result = processing.run("native:buffer",
{
'INPUT': QgsProcessingFeatureSourceDefinition(vl.id()
,selectedFeaturesOnly=True
,featureLimit=-1
,geometryCheck=QgsFeatureRequest.GeometryNoCheck)
,'DISTANCE':0.500
,'SEGMENTS':5
,'END_CAP_STYLE':0
,'JOIN_STYLE':0
,'MITER_LIMIT':2
,'DISSOLVE':False
,'OUTPUT': 'memory'
})

vl2 = QgsVectorLayer(result['OUTPUT'])
QgsProject.instance().addMapLayers([vl2])
```



> For other side, how can you explain when I marked selectedFeaturesOnly = False the algorithm run perfectly and build de layer with the buffer of the objects?

When using the uri, your source file is used as a _new_ layer, with no selected features. Using `selectedFeaturesOnly=False` works, but setting it to `True` no features get exported as nothing is selected.

**Comment by Octansf** [comment]
Hi uclaros.
When I use id() the process algorithm give an error
2023-11-10T 17:42:20 INFO Unable to execute algorithm
             Could not load source Laye for INPUT: (my layer name) not found

I don/t know what happened. But when you run de algorithm from Processing Toolbox, the definition of de layer use de Uri.
You can verify this running the algorithm, with or without checking selected Features Only in the dialog box.

I had previously made a script with the same statement and it worked perfectly. I upgraded to Qgis 3.28.12 and the algorithm stopped working.

In section 26.7. Using processing algorithms from the console, explain how to use the algorithm and it is clear you can use name, source, id, but when I tried to replicated that use it is impossible. I am using an existing layer and the selection was made manually. Sorry for my insistence, but the algorithm was worked perfectly before the update

**Comment by Octansf** [comment]
Finally, I was able to run it; but it's strange. I just removed all the spaces between parameters and values, like:
, selectedFeaturesOnly = True => This Line
, selectedFeaturesOnly=True => for this line
and I do the same for all Lines with parameters
Thanks for all your kind attention.
