### ISSUE TITLE
Point Cloud renderer treats Unsigned8 data as Signed8

### ISSUE THREAD

**Issue by hobu** [qgis/QGIS#55236]
### What is the bug or the crash?

UserData fields in LAS content is interpreted as Signed8 (`int8_t`) instead of Unsigned8 (`uint8_t`), which they should be.  

The attached data should be showing data in the following range:

```
      {
        "average": 150.1949131,
        "count": 69472,
        "maximum": 254,
        "minimum": 127,
        "name": "UserData",
        "position": 10,
        "stddev": 37.30480778,
        "variance": 1391.648683
      },
```

As shown by the screen shot, it is in the wrong range

![Screenshot 2023-11-09 at 8 47 00 AM](https://github.com/qgis/QGIS/assets/87751/29ae8f3a-f209-44ab-ac72-3fd4a0e7712f)
[user-data.copc.laz.zip](https://github.com/qgis/QGIS/files/13310009/user-data.copc.laz.zip)

### Steps to reproduce the issue

See screenshot

### Versions

3.32. I haven't checked the latest.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ntw-au** [comment]
Might this be related in some way to https://github.com/qgis/QGIS/issues/54365, both being misinterpretation of extra bytes fields?

**Comment by ntw-au** [comment]
Possibly unrelated due to different fields in play, but https://github.com/qgis/QGIS/issues/54365 also relates to field type misinterpretation.

**Comment by max-mapper** [comment]
I am also experiencing this issue, but it's preventing me from using the Export > Save As dialog. When I try to save a `.las` file I get this error:

```
Export failed: A problem occurred while exporting: Unable to set data and convert as requested: UserData:int(-57) -> uint8_t
```
