### ISSUE TITLE
Native:buffer selectedFeaturesOnly

### ISSUE THREAD

**Issue by Octansf** [qgis/QGIS#55247]
### What is the bug or the crash?

I'm working in Windows 10 with QGIS 3.28.12-Firenze. I'm new one with pyqgis.
When I use Processing Toolbox: Buffer, I can use the parameter Selected Features Only. I can check or not this parameter and the result layer is correct.
But when I try to use this script inside of python script the result layer is empty, when I use the parameter Selected Features Only equal True; if this parameter is False the result layer is correct.
I can't explain what happend. I try everything. New project, with only one layer. Existing Project with others layer. And de result layer always is empty when mark Selected Feature Only equal True.

This is part of code:

try:

lay = processing.run("native:buffer",
{
'INPUT': QgsProcessingFeatureSourceDefinition(v3.dataProvider().dataSourceUri()
, selectedFeaturesOnly=False # With False, works correcto. In True, result layer is empty.
, featureLimit=-1
, geometryCheck=QgsFeatureRequest.GeometryNoCheck)
,'DISTANCE':0.004500
,'SEGMENTS':5
,'END_CAP_STYLE':0
,'JOIN_STYLE':0
,'MITER_LIMIT':2
,'DISSOLVE':False
,'OUTPUT': 'ogr:dbname='D:/tmp/mbt_4/buf_4_85300.gpkg' table="buf_layer" (geom)'
}, context=ct, feedback=fb);
except Exception as e:

QgsMessageLog.logMessage(str(e),'Buffer_test', Qgis.Info)

### Steps to reproduce the issue

Open Plugin menu
Deploy Python Console
And write python code in console
You can show editor and create python scripts, save python script and running

### Versions

QGIS version
3.28.12-Firenze
QGIS code revision
https://github.com/qgis/QGIS/commit/dcc633b2de5d12de3c795760c21d79ddbc2c9a73
Qt version
5.15.3
Python version
3.9.5
Compiled against GDAL/OGR
3.7.2
Running against GDAL/OGR
3.7.3
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
MBTiles2img
0.4
plugin_reloader
0.9.3
QMetaTiles
1.5
qrbarcodeitem
0.2.0
Submission
0.7
tile_index_generator
1.0
union_mbtiles 1a
1a
zoom_level
0.1
processing
2.12.99
genera_mbtiles_vx1
x1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Uclaros send me this response: This is not a bug. You're passing the layer's URI as a source for the algorithm, not the actual layer, so the algorithm does not see the selection. Pass the layer object instead, and it should work as you'd expect. 
But when I use a layer like uclaros say, algorithm work with entire layer not select.

I need it the selection instead the entire layer. 

The python command function like I paste in the explanation of the issue

This is it an issue or bug

**Comment by alexbruy** [comment]
This is not a bug. Selection exists only in layers loaded in the QGIS, so if you create a layer object but does not add it to a project there will be no result. It works fine with layers loaded in the project.

**Comment by Octansf** [comment]
Hi alexbury, layer exist into project. It is not a temporary layer

**Comment by alexbruy** [comment]
@Octansf then you are doing something wrong in your code. I tested and everything works fine using `QgsProcessingFeatureSourceDefinition` in a way similar to how it is defined in your snippet.

**Comment by Octansf** [comment]
Hi alexbruy. I review every step on my code and when I check True selectedFeaturesOnly, having selected features or one feature only in my layer the result layer is empty. I try everything.  I begin new project and put only one layer in there. And always is the same error when ejecute de processing run from python code, not from the Processing Toolbox

**Comment by Octansf** [comment]
Finally, I was able to run it; but it's strange. I just removed all the spaces between parameters and values, like: 
, selectedFeaturesOnly = True => This Line 
, selectedFeaturesOnly=True => for this line
Thanks for all your kind attention.
