### ISSUE TITLE
Qgis crash when using QgsVectorLayer.pyqtConfigure() in pyqgis

### ISSUE THREAD

**Issue by Poulpator** [qgis/QGIS#55259]
### What is the bug or the crash?

Qgis crash when using QgsVectorLayer.pyqtConfigure() in pyqgis

I tried to use the `pyqtConfigure` method of  `QgsVectorLayer` and it crashes qgis without a stacktrace or leaving a report windows

### Steps to reproduce the issue

* Open a project and select any vector layer

* In the python console write : 
```
L = iface.activeLayer()
L.pyqtConfigure()
```
* Qgis crashes without a stacktrace

### Versions

QGIS version : 3.34.0-Prizren
OS: Windows 10 also tested in Ubuntu

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Poulpator** [comment]
I tried to search for `pyqtConfigure` in the source code and the only occurrence i could find is in python/qsci_apis/PyQt5.api at line  at line 1414

`PyQt5.QtCore.QObject.pyqtConfigure?4(object)`

**Comment by alexbruy** [comment]
There is no such method in the `QgsVectorLayer` and `QgsMapLayer` classes. The `pyqtConfigure()` method is a PyQt method for setting the values of properties and connecting a signal to a slot, it should be called with correct set of arguments. There is no crash if method called with correct arguments.

**Comment by Poulpator** [comment]
> There is no such method in the `QgsVectorLayer` and `QgsMapLayer` classes. 

It's weird because I'm able to call `pyqtConfigure` throught  `QgsVectorLayer`
![image](https://github.com/qgis/QGIS/assets/30632058/688b6ba9-c623-4de4-a834-a69362504508)

> it should be called with correct set of arguments. There is no crash if method called with correct arguments.

I personally think we should not be able to crash Qgis even if we use the the API incorrectly and we should rather handle error more gracefully 

Besides that I let you close the bug ticket if you judge it's not a bug
