### ISSUE TITLE
DWG/DXF Import issue

### ISSUE THREAD

**Issue by rbadawid** [qgis/QGIS#55268]
### What is the bug or the crash?

You cant import .dxf/.dwg file because it forces you to choose from .gpkg extension 

The "choose dxf/dwg file" and input a location for a GeoPackage file are swapped 

![Przechwytywanie](https://github.com/qgis/QGIS/assets/150667847/50d7a6fa-ad53-45cd-9ce0-38048d1052fa)

### Steps to reproduce the issue

1. Go to" Project ‣ DWG/DXF Import..."
2. Click on "..." in the dwg source
3. Cant chose DWG because you can only choose from gpkg extensions

### Versions

Wersja QGIS
3.34.0-Prizren
Rewizja QGIS
ffbdd67881
Wersja Qt
5.15.3
Wersja Pythona
3.9.5
Wersja GDAL/OGR
3.7.2
Wersja PROJ
9.3.0
Wersja bazy danych Rejestru EPSG
v10.094 (2023-08-08)
Wersja GEOS
3.12.0-CAPI-1.18.0
Wersja SQLite
3.41.1
Wersja PDAL
2.5.5
Wersja klienta PostgreSQL
15.2
Wersja SpatiaLite
5.1.0
Wersja QWT
6.1.6
Wersja QScintilla2
2.13.4
Wersja systemu operacyjnego
Windows 10 Version 2009

Active Python plugins
bdot10k
1.0
BDOT10k_GML_SHP_Loader
1.0.8
ImportPhotos
3.0.5
pobieracz_danych_gugik
1.0.6
postgis_geoprocessing
0.9
profiletool
4.2.6
qfieldsync
v4.5.0
StreetView
3.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jef-n** [comment]
Already fixed in 63e90d970c10d9

**Comment by agiudiceandrea** [comment]
@rbadawid, the issue has been already fixed https://github.com/qgis/QGIS/pull/55153 and the fix will land in QGIS 3.34.1 (https://github.com/qgis/QGIS/pull/55199). QGIS LTR 3.28.12 is not affected by the issue.
