### ISSUE TITLE
QGIS crash when using measuring tool

### ISSUE THREAD

**Issue by NPnzhp** [qgis/QGIS#55263]
## User Feedback

Trying to use the measuring tool. I can open the tool and select which type of measurement I want, but QGIS freezes and then crashes when I select the start point of my measurement.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x000032b4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QIODevice::write :
QTcpServer::proxy :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
multipleProviderMetadataFactory :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.12-Firenze
QGIS code revision: dcc633b2de
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

1. measure line
2. go to click location where measurement is to start from
3. screen freeze to 'not responding'
4. crash report window appears

### Versions

QGIS Desktop version 3.28.12

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
Are you using snapping and a web layer?

**Comment by agiudiceandrea** [comment]
@NPnzhp, thanks for reporting. Have you tried if the issue does occur also using a new QGIS user profile? If yes, does the crash occur every time in the described situation or for specific project? If yes, could you please provide the minimal set of project and layer(s) and exact steps in order to replicate the issue on another system?
