### ISSUE TITLE
QGIS Error

### ISSUE THREAD

**Issue by FeydRautha73** [qgis/QGIS#55282]
### What is the issue about the documentation?

I have a problem with the new version of QGIS 
QGIS version, 3.34.0-Prizren, can someone please help me?
A Python error appears during TIN interpolation.

OverflowError: cannot convert float infinity to integer 
Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged
    rows = max(round(self.extent.height() / cell_size) + 1, 1)
OverflowError: cannot convert float infinity to integer

Python-Version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] 
QGIS-Version: 3.34.0-Prizren Prizren, ffbdd67881

**Comment by FeydRautha73** [comment]
Even if I now use an earlier version of QGIS than version 3.34.0, I get the same error. I need the processing for my studies in civil engineering!

Von: Alexander Bruy ***@***.***>
Gesendet: Dienstag, 14. November 2023 10:28
An: qgis/QGIS ***@***.***>
Cc: Feyd-Rauther ***@***.***>; Author ***@***.***>
Betreff: Re: [qgis/QGIS] QGIS Error (Issue #55282)


This was already fixed in #55211<https://github.com/qgis/QGIS/pull/55211>. You should wait for next point release or use nightly build.

**Comment by agiudiceandrea** [comment]
@FeydRautha73, what is exactly the earlier version of QGIS for which the issue occurs? Does the issue occur using QGIS LTR 3.28.12? Could you please provide a sample layer and exact steps and parameter for which the issue occurs using QGIS LTR 3.28.12?
