### ISSUE TITLE
Georeferencer

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#55298]
### What is the bug or the crash?

Just finished the georeferencing, the message that appears at the top of the map canvas is Georeference Success: Raster was successfully georeferenced even if I use a vector!!!

![image](https://github.com/qgis/QGIS/assets/7631137/e08fc191-561e-4faa-8da8-98966446181d)

### Steps to reproduce the issue

1. georeferencing a vector
2. the message shall be as described above

### Versions

QGIS version
3.28.11-Firenze
QGIS code revision
d45af7d8c26
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Would be enough to change the message to "the layer was successfully georeferenced"?
Ref: https://github.com/qgis/QGIS/blob/master/src/app/georeferencer/qgsgeorefmainwindow.cpp#L1686
