### ISSUE TITLE
plugin tooglegroupvisibility crashed

### ISSUE THREAD

**Issue by hor3** [qgis/QGIS#55295]
## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x8001010d

Current thread 0x00005334 (most recent call first):
<no Python frame>
Windows fatal exception: access violation

Current thread 0x00005334 (most recent call first):
  File "C:\Users/Asus/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\togglegroupvisibility\togglegroupvisibility.py", line 269 in currentChanged
    node = self.modelRoot.index2node( current )
```

**Stack Trace**

```

QMetaObject::cast :
pdal::MetadataNode::value :
PyArg_ParseTuple_SizeT :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyFloat_FromDouble :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QItemSelectionModel::setCurrentIndex :
QAbstractItemView::setCurrentIndex :
QgsLayerTreeView::setCurrentLayer :
QgisApp::addProject :
QgisApp::openProject :
QgsTemporalControllerDockWidget::temporalController :
QObject::qt_static_metacall :
QAbstractItemView::activated :
QAbstractItemView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/150901925/61e2cb1d-b90d-4b2f-b246-1bffc9f54189)

### Versions

3.28.11

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@hor3, thanks for reporting.
Anyway, as you can read in the screenshot provided by you, 
![image](https://github.com/qgis/QGIS/assets/16253859/68cfb101-ab37-406a-a2e8-7fb75ba1b063)
you need to report the issue to the author(s) of the tooglegroupvisibility, which caused QGIS to crash.

The same instructions are displayed in the "New issue" page:

![image](https://github.com/qgis/QGIS/assets/16253859/3f23220b-2d5a-400e-b065-2b677fdd66b6)
