### ISSUE TITLE
Font size change>Crash

### ISSUE THREAD

**Issue by alexrod1968** [qgis/QGIS#55309]
### What is the bug or the crash?

I ahcned the font size from the general option menu and the program crashed.

## User Feedback

I changed the font size from general options and the program crashed.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001db4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QTableWidgetItem::text :
QgsMapToolShapeRegularPolygonCenterPointMetadata::name :
QgsOptions::saveOptions :
QObject::qt_static_metacall :
QDialogPrivate::finalize :
QObject::qt_static_metacall :
QDialogButtonBox::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showOptionsDialog :
QgisApp::options :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QMenu::metaObject :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/151064113/e6d56d02-6c88-4d29-85a4-7ed5abcfc693)
![image](https://github.com/qgis/QGIS/assets/151064113/dc76a088-c832-4eac-bc73-5cecfbfb6b5f)

### Versions

Versión de QGIS
3.32.3-Lima
Revisión del código de QGIS
67d46100b5
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.7.2
Versión de PROJ
9.3.0
Versión del registro de base de datos EPSG
v10.094 (2023-08-08)
Versión de GEOS
3.12.0-CAPI-1.18.0
Versión de SQLite
3.41.1
Versión de PDAL
2.5.5
Versión del cliente de PostgreSQL
15.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
AnotherDXF2Shape
1.3.1
batch_gps_importer
version 1.0.1
DigitizingTools
1.5.2
Discovery
2.5.8
FreehandRasterGeoreferencer
0.8.3
ImportPhotos
3.0.5
LocatePoints
0.3.4
lrs
1.2.3
NNJoin
3.1.3
OSMDownloader
1.0.3
profiletool
4.2.6
ProjectPackager
0.7.2
qgis2web
3.16.0
qgis_resource_sharing
1.0.0
QuickOSM
2.2.3
quick_map_services
0.19.33
road_inspection_viewer
1.2.5
SpreadsheetLayers
2.1.0
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@alexrod1968, thanks for reporting. QGIS 3.32 is no longer supported. Please try if the issue also occurs using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and/or if the issue also occurs using a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) as requested in the issue report form.
