### ISSUE TITLE
Add Processing models in toolbar

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#55319]
### Feature description

Like for all the other algorithms it would be nice to have the chance to add Processing models in the toolbar with a custom icon:

![image](https://github.com/qgis/QGIS/assets/2884884/65a9201b-fb0b-44a5-bc50-65c6d7594b3e)

**Comment by DelazJ** [comment]
@ghtmtt Unless I misunderstood, it looks like this is already available

https://github.com/qgis/QGIS/assets/7983394/9b88ea22-4c1e-455e-8057-bad24789697c
