### ISSUE TITLE
copy attribute value from id'ed feature does not work

### ISSUE THREAD

**Issue by janhec** [qgis/QGIS#55311]
### What is the bug or the crash?

The bug is that using the identify tool, attributes from the resulting list cannot be individually copied.
Copy feature attributes (all of them) does work.
This is a bit annoying to me since I often do so debugging programs producing gis output.
As seen in the version list, this is about a Windows installation.

### Steps to reproduce the issue

Load a project with one or more featuressets
Highlight any featureset (with attibutes) in the TOC
Use the identify tool to get attributes from a(ny) feature in the chosen featureset
right click an attribute, chose copy feature
In e.g. notepad, choose paste
Observe that nothing appears.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd67881
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
GeoCoding | 2.19
go2streetview | 8.6
inspireNL | 2.8
moving_feature | 2.0
nominatim_locator_filter | 0.2.4
pdokservicesplugin | 4.1.5
pdok_locatieserver_locator_filter | 0.2.1
quick_map_services | 0.19.33
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd67881](https://github.com/qgis/QGIS/commit/ffbdd67881)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
go2streetview
8.6
inspireNL
2.8
moving_feature
2.0
nominatim_locator_filter
0.2.4
pdokservicesplugin
4.1.5
pdok_locatieserver_locator_filter
0.2.1
quick_map_services
0.19.33
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
> right click an attribute, chose copy feature

_Copy feature_ does exactly what it says: copies the __feature__.
You're obviously trying to copy the attribute value here, so you should use _Copy attribute value_ instead.

**Comment by uclaros** [comment]
Sorry @janhec, the correct _Copy attribute value_ option does not work indeed, this is a regression.
