### ISSUE TITLE
Crash when zooming out after reprojecting layer

### ISSUE THREAD

**Issue by joaoambiente** [qgis/QGIS#55323]
## User Feedback

I have reprojected a point layer (data from Melbourne region) from EPSG 4326 to EPSG 7855.
The reprojected layer was not being displayed in the map.
Saved the qgis project
Zoomed out quickly to "worldwide extent"
Crash!

After reloading the qgis project, the reprojected layer was showing in the map.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005978 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_context_delete_cpp_context :
proj_create_operations :
proj_create_crs_to_crs_from_pj :
QgsCoordinateTransform::transformPolygon :
QgsCoordinateTransform::transformCoords :
QgsCoordinateTransform::transformBoundingBox :
QgsMapRendererJob::reprojectToLayerExtent :
QgsMapRendererJob::prepareJobs :
QgsMapRendererParallelJob::startPrivate :
QgsMapCanvas::refreshMap :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.1-Lima
QGIS code revision: 4a078ecf
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1 - reproject a point layer (data from Melbourne region) from EPSG 4326 to EPSG 7855.
2 - See if the reprojected is not being displayed in the map.
3 - Save the qgis project
4 - Zoom out quickly to "worldwide extent"
5 - Observe if Crash!

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.1-Lima | QGIS code revision | 4a078ecf
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
lizmap | 3.18.1
OpenTopography-DEM-Downloader | 2.0
QuickOSM | 2.2.3
quick_map_services | 0.19.33
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.32.1-Lima
QGIS code revision
[4a078ecf](https://github.com/qgis/QGIS/commit/4a078ecf)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
lizmap
3.18.1
OpenTopography-DEM-Downloader
2.0
QuickOSM
2.2.3
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@joaoambiente, thanks for reporting. QGIS 3.32 is no longer supported. Please try if the issue occurs running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and if the issue occurs using a new QGIS user profile as requested in the issue report form: if yes, please provide a sample layer and project and exact steps and parameters in order to replicate the issue.
