### ISSUE TITLE
QGIS 3.32.2-Lima crashes whenever I am casually closing the software after using it a little while

### ISSUE THREAD

**Issue by aluthfian** [qgis/QGIS#55331]
## User Feedback

I am just casually closing QGIS and this happened

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00003db8 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QListData::end :
QgsRuleBasedLabeling::Rule::~Rule :
QgsRuleBasedLabeling::Rule::~Rule :
QgsVectorLayer::setLabeling :
QgsLabelingWidget::writeSettingsToLayer :
QgsLabelingWidget::apply :
QgsLayerStylingWidget::apply :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::processEvents :
UserCallWinProcCheckWow :
DispatchMessageWorker :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.32.2-Lima
QGIS code revision: c0b8833964
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Using the QGIS normally for displaying GIS data. Files in OneDrive and NAS drives, also displaying files from WMS and WCS services.
2. Doing stuff with QGIS for a while.
3. Saving all stuff, wait a while and make sure OneDrive is not syncing.
4. Close QGIS by clicking File > Close.
5. QGIS crashes.

### Versions

3.32.2-Lima

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@aluthfian, thanks for reporting. QGIS 3.32 is no longer supported. Please try if the issue occurs running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and if the issue occurs using a new QGIS user profile.
