### ISSUE TITLE
Adding layers in a group layer from a processing plugin makes layer checked and unchecked status not work correctly

### ISSUE THREAD

**Issue by CamMorin** [qgis/QGIS#55339]
### What is the bug or the crash?

From a processing plugin written in Python, I was not able to add layers to a group layer without having this bug. So, when layers were added to the project in a group, when I wanted to interact with the layers, so make them not visible or visible by checking or unchecking them manually, it would not work. But when I would interact with a layers outside of the group, then the changes in the group would be applied.
So for example, if I had 'group_1' with 2 visible layers in it, unchecking them would do nothing and they would still be visible. But if for example, I went and unchecked another layer outside of 'group_1', then the layers in 'group_1' would now be invisibles, so their unchecked status now would be applied.

I tried to add layers with different functions available in Python, for example either directly with the addLayer and addGroup from the LayerTreeRoot or by using the LayerTreeLayer and LayerTreeGroup class with insertChildNode, and I had the exact same result with both method. If I saved the project in a file and then reloaded the file, the bug was fixed though. After, I decided to switch this part of my plugin to a custom GUI in QGIS and with the exact same function I had created I didn't have the bug anymore.

### Steps to reproduce the issue

1. Create a basic processing plugin in Python with the Plugin Builder.
2. In the initAlgorithm, add a simple file parameter : 
```
self.addParameter(
    QgsProcessingParameterFile(
        name='input_file',
        description=self.tr("Layer to add"),
        behavior = QgsProcessingParameterFile.File
    )
)

```
3. In the processAlgorithm, get the current project reference like this : `project = context.project()`
4. Create a group with : `root = project.layerTreeRoot().addGroup('group1')`
5. Then add the layer to the group like this : 
```
path_layer = self.parameterAsString(parameters, 'input_file', context)
basename = 'test'
layer = QgsVectorLayer(path_layer, basename, 'ogr')
qgs_layer = project.addMapLayer(layer, False)
root.addLayer(layer=layer)
```
6. Then you can create a zip and install the plugin or link the plugin in QGIS, like you prefer.
7. Then launch the plugin with any Shapefile layer for example.
8. When unchecking the layer, it will still be visible in the canvas. If you import another layer in your project, put it outside the group and uncheck or check it, the layer in the group will now apply its checked status in the canvas.
9. You can also try and save the whole project as a qgz file, then opening this file, the layer in the group is now fine.

### Versions

QGIS version
3.30.0-'s-Hertogenbosch
QGIS code revision
f186b8efe0e
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
pluginbuilder3
3.2.1
test_processing_add_layer2
0.1

Note : 
test_processing_add_layer2 is my test plugin I made to test again this problem, so basically only the code I described in the steps to reproduce the issue.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Add 

```
  def flags(self):
      return super().flags() | QgsProcessingAlgorithm.FlagNoThreading
```

to your algorithm class -- you're trying to do thread unsafe operations in a background thread.
