### ISSUE TITLE
Very high execution times in QGIS 3.34.0 for models created with the Graphic Modeler

### ISSUE THREAD

**Issue by news24lor** [qgis/QGIS#55337]
### What is the bug or the crash?

I have been using the new version of **QGIS 3.34.0** for a few days and have found that in running models created by the Graphic Modeler, there is very different performance between version 3.32.3 and 3.34.0.
I have several models created with the modeler including a very complex one with about 100 algorithms that until version 3.32.3 was executed in about 11 minutes, while with version 3.34.0 the same model after more than 3 hours was executed ONLY 18% of the total!!!

In the case of simpler models with very few algorithms the execution times are similar with increasingly better times with version 3.32.3.

I checked and rechecked everything but not much can be done. When "Run" is pressed to execute the model, before the first script appears in the log, several minutes pass while in the previous version 3.32.3 the first model script was executed after a few seconds.

I checked the performance without plugins installed but the result is the same

QGIS 3.32.3 worked well

### Steps to reproduce the issue

Go to... Processing Toolbox
Open Existing Model ...
You have to open a big Model

### Versions

QGIS version 3.34.0-Prizren
QGIS code revision [b77936ec947](https://github.com/qgis/QGIS/commit/b77936ec947)
Qt version 5.15.2
Python version 3.9.5
GDAL/OGR version 3.3.2
PROJ version 8.1.1
EPSG Registry database version v10.028 (2021-07-07)
GEOS version 3.9.1-CAPI-1.14.2
SQLite version 3.35.2
PDAL version 2.3.0
PostgreSQL client version unknown
SpatiaLite version 5.0.1
QWT version 6.1.6
QScintilla2 version 2.11.5
OS version macOS 13.6

Same problem in QGIS 3.34.0 for Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I checked the performance without plugins installed but the result is the same.
I have tested this problem on Windows and Mac version.
The problem is only in QGIS 3.34.0

**Comment by BTreeTech** [comment]
I am having similar issues, I don't think it is model specific as it happens with all of models that I use day to day, but could be a specific algorithm. 
QGIS version
3.34.5-Prizren
QGIS code revision
4b308492
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1

**Comment by nyalldawson** [comment]
Tagging this as needing feedback. Without a sample model there's nothing we can do

**Comment by news24lor** [comment]
Hi, in the last version 3.36.x, the speed is comeback as 3.32.x. I use Qgis with Intel and ARM processor and now the graphic modeler is reusable. In the ARM processor the difference of execution of a big model is huge respect to Qgis on Intel. For me is resolved!
Thank so much!
