### ISSUE TITLE
Wrong WKT with add ring maptool

### ISSUE THREAD

**Issue by lbartoletti** [qgis/QGIS#55361]
### What is the bug or the crash?

There has been a regression in WKT export from the new drawing tools - at least, in 3.20, the behavior is correct.

Indeed, when creating a (multi)polygon, if you add a ring, it is always exported to wkt as a CompoundCurve, even on geometries that aren't of this type where you'd expect basic LineString.

### Steps to reproduce the issue

Draw a polygon "((0 0, 5 0, 5 5, 0 5, 0 0)"
Add a ring "((1 1, 1 2, 2 2, 2 1, 1 1))"
Copy/paste the feature/get the wkt.

You'll have : MultiPolygon (((0 0, 5 0, 5 5, 0 5, 0 0),CompoundCurve ((1 1, 1 2, 2 2, 2 1, 1 1))))
Instead of MultiPolygon (((0 0, 5 0, 5 5, 0 5, 0 0),(1 1, 1 2, 2 2, 2 1, 1 1)))

### Versions

> 3.24?

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lbartoletti** [comment]
cc @troopa81 @3nids @Djedouas

**Comment by uclaros** [comment]
This has already been reported in #50869
Fill ring tool is also affected.
