### ISSUE TITLE
python disabled on fresh linux install, error: Couldn't load SIP module. Python support will be disabled.

### ISSUE THREAD

**Issue by stibinator** [qgis/QGIS#55379]
### What is the bug or the crash?

Basically the same error as https://github.com/qgis/QGIS/issues/37783 but on Linux, the other one was closed because ... I don't know why, but it's obvious that it's still broken

### Steps to reproduce the issue

Install Qgis on linux
start it up
expected: program runs properly
observed: error Couldn't load SIP module. Python support will be disabled. Plugins do not load.
To fix it I had to uninstall PyQt5 using `pip uninstall pyqt5`, so obviously something is borked with Qt. This is a pretty fresh install of Ubuntu.

### Versions

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd678812
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.33
osminfo | 0.7.1
QuickOSM | 2.2.3
qgis-maptiler-plugin | 3.2
nominatim | 1.4.5
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd678812](https://github.com/qgis/QGIS/commit/ffbdd678812)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
quick_map_services
0.19.33
osminfo
0.7.1
QuickOSM
2.2.3
qgis-maptiler-plugin
3.2
nominatim
1.4.5
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
You don't say how you installed QGIS and how you installed PyQt5, but it seems that you installed PyQt5 from pip which  probably installs another version of PyQt5 in addition to the one provided by the deb packages.  

Just guessing.

**Comment by m-kuhn** [comment]
> You don't say how you installed QGIS and how you installed PyQt5, but it seems that you installed PyQt5 from pip which probably installs another version of PyQt5 in addition to the one provided by the deb packages.
> 
> Just guessing.

Pretty sure that's the case. A pip installed PyQt5 on PYTHONPATH has a high chance to cause troubles (just like pip installing other libs e.g. with gdal inside).
I am not sure we can do anything from QGIS side to detect such a situation and print a warning (and even less sure we can do something to prevent such an issue).
Does someone have an idea?

**Comment by stibinator** [comment]
I haven't personally installed pyqt5, and I'm pretty sure no other apps did, but that might be the case. I installed using the instructions on the QGIS installation page here: https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu

**Comment by stibinator** [comment]
Wouldn't it be possible to add `pip list | grep PyQt5` to the installer somewhere to check?

**Comment by m-kuhn** [comment]
> Wouldn't it be possible to add `pip list | grep PyQt5` to the installer somewhere to check?

This is shown here also when installed from the system packages (and not only when installed via pip).
How did you find out that a pip installed PyQt5 was the problem?

**Comment by jef-n** [comment]
> I haven't personally installed pyqt5, and I'm pretty sure no other apps did, but that might be the case.

So what did?  The package only depends on the distribution's PyQt5.
