### ISSUE TITLE
Possible bug in /usr/share/qgis/python/plugins/processing/gui/Postprocessing.py

### ISSUE THREAD

**Issue by SimoParmeg** [qgis/QGIS#55374]
### What is the bug or the crash?

I created a model that runs two custom algorithms in sequence,
at the end of the model seems this postprocessing.py is automatically executed and tries to load my output in the attribute table, even if i explicitly given the command not to do it.

The output is properly formatted, however this error appears and is not elegant:
![image](https://github.com/qgis/QGIS/assets/70708372/415ce22f-325f-4c60-927d-541da983b449)

![image](https://github.com/qgis/QGIS/assets/70708372/8965aae2-af18-4e63-9221-5bf735347160)

### Steps to reproduce the issue

go to the following repo

https://github.com/SimoParmeg/ferrovienord

follow instructions to install the scripts and the model.
Try the model with two point layer or with a line and a point layer

### Versions

3.34 Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@SimoParmeg, thanks for reporting. It looks like the issue doesn't occur using QGIS 3.28. It may be related to https://github.com/qgis/QGIS/pull/52984.

**Comment by nyalldawson** [comment]
This should be fixed in current releases -- can you please test?

**Comment by SimoParmeg** [comment]
Just tested and it looks solved.
thanks for support
