### ISSUE TITLE
Weird list of layers in the Raster calculator Expression in Model Designer context

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#55388]
### What is the bug or the crash?

The "Raster calculator expression" widget is filled with weird list of layers (A, B, C... G)

### Steps to reproduce the issue

Open model designer dialog
Add one of the native Raster Calculator algorithms
Press the epsilon button of the Expression parameter, opening the "Raster calculator expression" dialog
The "Layers" widget is prepopulated with layers from A to G
![raster_calcexpr_modeler](https://github.com/qgis/QGIS/assets/7983394/7674ea05-0780-4d78-9df5-af8fdc20b054)

Also I don't know if it is expected to list the layers I selected in the "Input layers" parameter of the alg, but it doesn't seem to show them.

### Versions

master (https://github.com/qgis/QGIS/commit/a16114124d4674db6436db5d26b085ee1f1858af) on Windows 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Not a bug, this is intentional. In modeler context we don't have real inputs, instead we use "A", "B", "C"... names to represent first, second, third… inputs.

**Comment by DelazJ** [comment]
Oh... This does not seem obvious to me, but I see. Is this a (QGIS) convention known by modeler users? Mentioned somewhere?
