### ISSUE TITLE
Optional layername and path attributes added in "Merge vector layers" tool

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#55397]
### Feature description

The idea is to add an option (checkbox) in the processing tool Merge vector layers to let the user choose to add or not the path and layername of the individual input vector layers used. Currently, the attribute "path" and "layer" are always added to the output layer. For backward compatibility reason, this new option could be set as true by default.
![merge_vectors_option](https://github.com/qgis/QGIS/assets/32580398/a14f758a-6f01-4d33-bc7d-44b9d58d3202)

**Comment by ERHash** [comment]
Agree for confidential abt the path
