### ISSUE TITLE
local xyz tiles: probably correct path structure is detected as incorrect

### ISSUE THREAD

**Issue by noname8556** [qgis/QGIS#55391]
### What is the bug or the crash?

My goal is to create a link to local xyz tiles in the browser.

There is an error message for this path:

`file:///path/{z}/{x}/{y}.jpg`
Invalid Data Source: type=xyz&url=file:///path/%7Bz%7D/%7Bx%7D/%7By%7D.jpg&zmax=16&zmin=0&http-header:referer= is not a valid or recognised data source.

and this path is accepted:

`/path/{z}/{x}/{y}.jpg`

the second one is not displayed at the end.

### Steps to reproduce the issue

- add new local xyz tiles in the browser with a path like `file:///path/{z}/{x}/{y}.jpg`
- try to add (double click) -> error message
- edit connection: path to `/path/{z}/{x}/{y}.jpg`
- try to add, should work
- layer is not displayed
- layer properties: layer source: url to `file:///path/{z}/{x}/{y}.jpg`
- layer should be displayed

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.5
Compiled against GDAL/OGR | 3.7.2 | Running against GDAL/OGR | 3.7.3
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.44.0
PDAL version | 2.5.6
PostgreSQL client version | 16.0
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
ViewshedAnalysis | 1.8
profiletool | 4.2.6
active_fire | 0.3
qProf | 0.5.1
zoom_level | 0.1
lockzoom | 3.0.3
ORStools | 1.6.0
valuetool | 3.0.17
processing | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.11
Python version
3.11.5
Compiled against GDAL/OGR
3.7.2
Running against GDAL/OGR
3.7.3
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.44.0
PDAL version
2.5.6
PostgreSQL client version
16.0
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Manjaro Linux

Active Python plugins
ViewshedAnalysis
1.8
profiletool
4.2.6
active_fire
0.3
qProf
0.5.1
zoom_level
0.1
lockzoom
3.0.3
ORStools
1.6.0
valuetool
3.0.17
processing
2.12.99
db_manager
0.1.20
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by noname8556** [comment]
I just noticed that 'file:/path/{z}/{x}/{y}.jpg' instead of 'file:///path/{z}/{x}/{y}.jpg' also works. Not sure which is the correct spelling.

**Comment by alexgoussev** [comment]
There is the same behaviour on Windows 10. A path like DISK_LETTER:/path/{z}/{x}/{y}.jpg is accepted only. But nothing is displayed at the end and there is a lot of errors in WMS log like this:
2024-01-31T00:19:56     WARNING    Tile request max retry error. Failed 3 requests for tile 13 of tileRequest 2 (url: x:/cache_ma/googlesat/13/6055/2728.jpg)

**Comment by alexgoussev** [comment]
I have been able to fix the problem manually.
1) Unpack zipped QGIS project file .qgz.
2) Open unzipped .qgs project file in text editor.
3) Find two strings with xyz tile path. They look like (my case):
FIRST
<layer-tree-layer source="http-header:referer=&amp;tilePixelRatio=1&amp;type=xyz&amp;url=X:/cache_ma/googlesat/%7Bz%7D/%7Bx%7D/%7By%7D.jpg&amp;zmax=18&amp;zmin=0" id="_f83d0dca_2540_4c64_8b7d_c5aeb4870a2f" expanded="1" legend_exp="" legend_split_behavior="0" checked="Qt::Checked" providerKey="wms" patch_size="-1,-1" name="Google Sat (local)">
SECOND
<datasource>http-header:referer=&amp;tilePixelRatio=1&amp;type=xyz&amp;url=X:/cache_ma/googlesat/%7Bz%7D/%7Bx%7D/%7By%7D.jpg&amp;zmax=18&amp;zmin=0</datasource>
4) Remove "http-header:" part from each of them. 
5) Add "file:///" immediately after "url=" part. 
6) Save .qgs project file and replace it in .qgz ZIP-archive.
Done.

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.28.

**Comment by nirvn** [comment]
This has been fixed, it will work in 3.34.4 and 3.36.0 onward.

**Comment by prusswan** [comment]
Apart from XYZ sources, this also affects other connections like WMS/WMTS if local file uri is used (e.g. file:///c:/path_to_config.xml)

**Comment by agiudiceandrea** [comment]
@prusswan , please create a new detailed issue report.
