### ISSUE TITLE
The check result of constraints sometimes differs in the form and attribute table view

### ISSUE THREAD

**Issue by lp-dj** [qgis/QGIS#55390]
### What is the bug or the crash?

I am referring to the relatively new, great feature "Show Features with Failing Constraints" to filter features in the attribute table.

I observe cases here where after activating the "Show Features with Failing Constraints" function, features are filtered and certain columns are marked as failing in the table view, but the same fields are marked with a green checkmark in the form view.

In my opinion, the check results displayed in the form view should be correct in the corresponding cases.

### Steps to reproduce the issue

Unfortunately, this is a customer project which I cannot post here for illustrative purposes. As it only seems to affect very specific cases, I have not yet managed to recreate the case in an MWE.

For example, the constraint expression of one case in question is

```
if(
"kontrolle_rahmen" =  'Pflege- und Funktionskontrolle',
CASE
WHEN "funktion_umsetzungsstand" in ( 'umgesetzt' , 'tlw. umgesetzt' ) 
 and  "pflege_status" IS NOT NULL THEN True
WHEN "funktion_umsetzungsstand" in ( 'nicht umgesetzt' ,  'unklar, ob umgesetzt' ) 
 and  "pflege_status" IS NULL THEN True 
WHEN "pflege_beschreibung" <> '' and "pflege_status" = 'in Planung' THEN True
WHEN "pflege_dauerhaft" = '0' and "pflege_status" = 'in Planung' THEN True
ELSE False
END,
True)
```

Any idea what the problem could be? Is the constraint expression "problematic" in some way or is it a bug in the "Show Features with Failing Constraints" function?

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-Version | 3.34.0-Prizren | QGIS-Codeversion | ffbdd67881
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
Kompiliert mit GDAL/OGR | 3.7.2 | Läuft mit GDAL/OGR | 3.7.3
PROJ-Version | 9.3.0
EPSG-Registraturdatenbankversion | v10.094 (2023-08-08)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.41.1
PDAL-Version | 2.5.5
PostgreSQL-Client-Version | 15.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It looks like the query of the operating system in the QGIS Help menu -> About is not working properly. I am actually using Windows 10 Pro, 22H2.

![grafik](https://github.com/qgis/QGIS/assets/80956612/c0750ee8-b686-43dc-817e-3ebde6130849)

**Comment by lp-dj** [comment]
I have gained further insights into this issue.

1) The crucial field where the evaluation differs is "pflege_dauerhaft". This field is a string type field. For the attribute form, this field is configured as a checkbox. The checked state is defined as 1, the unchecked state as 0.

2) However, the raw value is actually '' (empty string, not to be confused with NULL!?). This is very difficult to recognize because QGIS lacks the function to switch the display between raw values and displayed values (see #29109). Is there anything new in this regard? Instead of the raw value (empty string), a pair of brackets '()' is displayed in the attribute table in the cases mentioned, which I thought was a '0' for a long time.

3) Thesis: The constraint check probably produces different results because the attribute table view checks the raw_value and the form view checks the value specified for the unchecked status. Therefore, in the formula from the initial post, the case `WHEN "pflege_dauerhaft" = '0' ` is considered fulfilled in the attribute form, but not in the attribute table view. Strictly speaking, contrary to my initial assumption, the check in the attribute table was right.

All in all, this issue is probably due to several causes: inconsistent behavior of QGIS depending on whether you are looking at the data via form view or table view; user error, as I wrote the formula incorrectly (queried on '0' instead of ''); and the lack of ability of QGIS to display raw values in the attribute table once widgets are configured, which would have been helpful to avoid the user error or at least detect it earlier.

For now, I was able to work around it by correcting the constraint formula after I realized my mistake. I find the function to filter for failed constraints ingenious and extremely helpful for my work.

My suggestions for improvements/additions in this context would be the following:

    - consistent behavior of the constraint check, regardless of the view and preferably based on the actual raw values
    - Possibility to display the raw values in the table view
    - Performance improvement: Currently, it is hardly possible to make changes to the data when the "Failing Constraints" filter is switched on (at least for a somewhat more complex data set). Apparently the whole layer is filtered again with every change? If so, is it possible to perform the constraint check only for the current object again? Alternatively, could the constraint check only be filtered again after saving the layer changes or after clicking on the filter function again? Another possibility would be a toggle checkbox for "live" filtering, such as in the QGIS main window at the bottom left for map rendering.

Many thanks for your great work, the attention for this somewhat longer post and best regards

**Comment by nirvn** [comment]
@lp-dj , I think one way to improve your scenario here is to insure the checkbox editor widget reflects null / not set state instead of assuming false for anything other than true. A PR is coming.

**Comment by lp-dj** [comment]
Nice to see that you're on it, thanks @nirvn.

I appreciate your idea of dealing with the problem in the form view! Sounds plausible.

Wanted to test your PR, but unfortunately [the link to the corresponding Windows build](https://github.com/qgis/QGIS/suites/20116780650/artifacts/1194863035) according to #56002 seems to be broken.

Are there any additional plans to give the user the option of displaying the raw values instead of the represented values in the table view and/ or to improve the performance while the "Failing Constraints" filter is active?
