### ISSUE TITLE
The Qgis  3.28.12 couldn't open. 

### ISSUE THREAD

**Issue by ginny15625** [qgis/QGIS#55409]
### What is the bug or the crash?

I have used  Qgis  3.28.12 for four months, but i don't know why it couldn't open know. Even, I reloud or install Qgis 3.34.0 it 
also couldn't open. Thank you.

### Steps to reproduce the issue

1.open the Qgis
2.the Qgis ended unexpectly
![Qgis end](https://github.com/qgis/QGIS/assets/152069772/f745b1d5-190c-464a-8744-2905ff0d0afe)
 

### Versions

Qgis 3.28 12

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by ginny15625** [comment]
"C:\Users\Public\Desktop\QGIS 3.28.12\Qt Designer with QGIS 3.28.12 custom widgets.lnk" . "If the answer isn't precise, please let me know. However, when I use a new user profile, QGIS runs. Thank you for the response.

**Comment by agiudiceandrea** [comment]
Since the issue doesn't occur using a new QGIS user prpfile, then it was very likely due to an external plugin installed in the old iuser profile.
