### ISSUE TITLE
Hexagon shape digitizing mismatch

### ISSUE THREAD

**Issue by SGroe** [qgis/QGIS#55422]
### What is the bug or the crash?

The icon of 'Regular polygon....' from the Shape Digitizing Toolbar indicates a pentagon, however it produces a hexagon on the map.

I think the icon should match the resulting geometry.

![Screenshot 2023-11-27 083110](https://github.com/qgis/QGIS/assets/11455516/6365e37d-01af-4a45-b028-ce43221cdab5)

### Steps to reproduce the issue

1. Show Shape Digitizing Toolbar
2. Draw a "Regular polygon ..." (using pentagon icon)
3. See hexagon on map

### Versions

QGIS version
3.34.0-Prizren
QGIS code revision
ffbdd67881
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.3.1
changeDataSource
3.1
Mergin
2023.4.1
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
qfieldsync
v4.6.1
qgiscloud
3.8.14
slyr_community
5.0.0
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lbartoletti** [comment]
It's not hexa,penta,octo gone. It's a regular polygon and you can set the number of sides you want.

**Comment by SGroe** [comment]
How can I produce a e.g. pentagon using "Regular polygon from 2 points"?

**Comment by SGroe** [comment]
Ah... I found it now. :-)
@lbartoletti Thank you.
