### ISSUE TITLE
GPKG in DBeaver

### ISSUE THREAD

**Issue by Gis-kost** [qgis/QGIS#55449]
### Feature description

Dear friends.

I strongly need to support to use GPKG in DBeaver!

But i cant find driver or something else way how to use it like in DB Manager.

I know, that i can use SQLite-driver, but its only table, without GEOspatial functions, like intersects(geom,geom)

**Comment by alexbruy** [comment]
Please file this request in DBeaver tracker, this is not related to QGIS at all

**Comment by Gis-kost** [comment]
> Please file this request in DBeaver tracker, this is not related to QGIS at all

Almost i did this, but no right answers.. may be pepople who use Qgis try something to work with GPKG in DBeaver
