### ISSUE TITLE
Random Points in Polygons - Crash

### ISSUE THREAD

**Issue by hbnsarah** [qgis/QGIS#55445]
### What is the bug or the crash?

Hello!
I try to create a new layer with random points in polygons.
I select my shp (on which I applied a filter)
I just add a number of points to the layer but dont touch to other parameters (just for a first test) and if I click on "Run" , QGIS is crashing.
projection system is standard one: EPSG:4326

![Screenshot 2023-11-28 at 10 38 48](https://github.com/qgis/QGIS/assets/114160212/19dcf317-115a-4ad5-a8d8-8fb4fa32ece3)

### Steps to reproduce the issue

Go to vector creation in toolbox, 
click on Random points in polygons
select the polygon layer
Add a number of points for each feature
click on Run
Crash

### Versions

First Lima version but tried on the Prizren as well and same bug.
Same in 3.28 LTR version

Model: MacBookPro16,1, BootROM 2020.41.1.0.0 (iBridge: 21.16.1069.0.0,0), 8 processors, 8-Core Intel Core i9, 2,3 GHz, 32 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: AMD Radeon Pro 5500M, AMD Radeon Pro 5500M, PCIe, 4 GB
Display: Color LCD, 3072 x 1920 Retina, Main, MirrorOff, Online
Display: S22F350, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2667 MHz, Micron, MT40A2G8NEA-062E:J
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x7BF), wl0: Jul 10 2023 12:53:18 version 9.30.503.0.32.5.92 FWID 01-c06f991b
AirPort: 
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB3.1 Hub
USB Device: USB3.0 Card Reader
USB Device: AX88179A
USB Device: USB31Bus
USB Device: USB2.1 Hub
USB Device: 2.4G Wireless Mouse
USB Device: T2Bus
USB Device: composite_device
USB Device: Touch Bar Backlight
USB Device: Touch Bar Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: Ambient Light Sensor
USB Device: FaceTime HD Camera (Built-in)
USB Device: Apple T2 Controller
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5
Thunderbolt Bus: MacBook Pro, Apple Inc., 63.5

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@hbnsarah, thanks for reporting. Please:
- provide the full version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.")
- try if the issue occurs also using a new QGIS user profile: if yes, then please provide a layer with which the issue occurs (put its file(s) in a zipped file and attach the zipped file to a comment).

**Comment by lbartoletti** [comment]
@hbnsarah I can't reproduce, can you please provide your data/project? Thanks.
