### ISSUE TITLE
NetCDF Points file not valid data source when global attribute "Conventions" is capitalised

### ISSUE THREAD

**Issue by janomecopter** [qgis/QGIS#55455]
### What is the bug or the crash?

When opening a NetCDF file containing point based data, if the file contains a global attribute named "Conventions" (capitalised as per CF/ACDD standards), QGIS will fail to load the file, claiming that the file is an invalid data source.

### Steps to reproduce the issue

1. Obtain files from the attached [archive](https://github.com/qgis/QGIS/files/13496008/output_tests.zip).
2. test_lower.nc contains ten points coordinated with lat/lon coordinates with two data variables, and one global attribute with the name "conventions". This file will load as points if dragged into the QGIS interface.
3. test_upper.nc contains the same data as test_lower.nc, apart from a capital letter on the front of the attribute name. This file will refuse to load when dragged into QGIS, and a warning message about "Invalid Data Source" will be displayed on the top banner of the View screen.

### Versions

QGIS version
3.32.3-Lima
QGIS code revision
67d46100b5
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

```
> nccmp -fgN test_upper.nc test_lower.nc
DIFFER : NAME OF GLOBAL ATTRIBUTE : Conventions : GLOBAL ATTRIBUTE DOESN'T EXIST IN "test_lower.nc"
DIFFER : NAME OF GLOBAL ATTRIBUTE : conventions : GLOBAL ATTRIBUTE DOESN'T EXIST IN test_upper.nc
DIFFER : VARIABLE : latitude : ATTRIBUTE : _FillValue : VALUES : nan <> nan
DIFFER : VARIABLE : longitude : ATTRIBUTE : _FillValue : VALUES : nan <> nan
DIFFER : VARIABLE : depth : ATTRIBUTE : _FillValue : VALUES : nan <> nan
```

I feel this bug may be tangentially related to #55239 , in that it's another instance of NetCDF metadata attributes causing data handling issues on file import.

**Comment by agiudiceandrea** [comment]
@janomecopter, could you provide the output of the `ogrinfo test_upper.nc` and `ogrinfo test_upper.nc test_upper` commands? I suppose the issue is due to the old version of GDAL in your system.

**Comment by janomecopter** [comment]
I haven't been able to isolate the version of GDAL from the build in question, but I have success with running `ogrinfo` for the two files for versions before and after it:
![20231205-140816](https://github.com/qgis/QGIS/assets/12651485/69ddf39a-e309-4a50-8c04-cb62689b4de9)
I've also managed to get my hands on a more recent build of the program now (QGIS 3.34.1 built on GDAL 3.7.1) which seems to handle the data (with a bunch of HDF warnings), so I guess this problem has been rectified.
