### ISSUE TITLE
Desktop icon is white/blank

### ISSUE THREAD

**Issue by IgorKozarchuk** [qgis/QGIS#55452]
### What is the bug or the crash?

After several couple of update desktop icon is shown as default white thumbnail. It looks normal in File Explorer but becomes blank as soon as sent to desktop.

### Steps to reproduce the issue

1. Install QGIS
2. Copy icon to desktop

### Versions

3.34.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@IgorKozarchuk, thanks for reporting. Please specify the full version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") or at least the name and the version of the Operative System which QGIS is running on.

**Comment by IgorKozarchuk** [comment]
I rebuilt icon cache and now everything is ok. Probably it was the problem with Windows.

**Comment by IgorKozarchuk** [comment]
Still an issue.
After installing new version of QGIS and moving the icon to desktop, the icon becomes blank/white/default.
If you move it to any other folder, it shows QGIS logo. Weird and does not happen with any other app.

**Comment by IgorKozarchuk** [comment]
People report on reddit:
https://www.reddit.com/r/QGIS/comments/a3pjb5/qgis_34_on_windows_10_desktop_icon_issue/
