### ISSUE TITLE
Merge Vector Layer/Drag and Drop layers from Layer Panel doesn`t work

### ISSUE THREAD

**Issue by Darko325** [qgis/QGIS#55461]
### What is the bug or the crash?

I have tested this on Windows and Linux; it seems to be related to older versions of QGIS. When I grab two or more layers and try to drop them into 'Input layers,' of the Merge Vector Layer tool, they no longer receive a checkmark as they did before. This is a problem, especially since I have some layers here with the same name, and the only way/easiest/fastest way I can know that I'm merging the layers I want/need is through this method.
![image](https://github.com/qgis/QGIS/assets/97731606/5b894d96-621d-4c0a-adcd-c37fc814a26d)

When I do the same in a newer version of QGIS, it is possible to do that, and the correct layers receive the checkmark.
![image](https://github.com/qgis/QGIS/assets/97731606/7a587943-f9ef-4394-93e5-cfae64b37559)

This is happening on almost every older version I've tried, except for version 3.34.X.

### Steps to reproduce the issue

Just pick two or more line layers and try to drag and drop them into the Merge Vector Layer tool; you won't get a checkmark. Disclaimer: 'I know you can't merge lines with polygons and so on...'

### Versions

The none working version
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.3
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | 14.2 (Ubuntu 14.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
merge_selected_features | 0.1
quick_map_services | 0.19.34
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.5
sagaprovider | 2.12.99

</body></html>QGIS version
3.22.4-Białowieża
QGIS code branch
[Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)
Qt version
5.15.3
Python version
3.10.3
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PostgreSQL client version
14.2 (Ubuntu 14.2-1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Linux Mint 21.2

Active Python plugins
processing_saga_nextgen
1.0.0
merge_selected_features
0.1
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.5
sagaprovider
2.12.99

"This one too is none working"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.12-Firenze | QGIS code branch | Release 3.28
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.6
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
Compiled against SQLite | 3.44.0 | Running against SQLite | 3.44.2
PDAL version | 2.5.6
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
merge_selected_features | 0.1
quick_map_services | 0.19.34
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.12-Firenze
QGIS code branch
[Release 3.28](https://github.com/qgis/QGIS/tree/release-3_28)
Qt version
5.15.8
Python version
3.11.6
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
Compiled against SQLite
3.44.0
Running against SQLite
3.44.2
PDAL version
2.5.6
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Linux Mint 21.2

Active Python plugins
processing_saga_nextgen
1.0.0
merge_selected_features
0.1
quick_map_services
0.19.34
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
sagaprovider
2.12.99

"WORKING VERIOSN"

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.12.0
GDAL/OGR version | 3.8.0
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.44.2
PDAL version | 2.6.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
merge_selected_features | 0.1
quick_map_services | 0.19.34
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.1-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.8
Python version
3.12.0
GDAL/OGR version
3.8.0
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.44.2
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Linux Mint 21.2

Active Python plugins
processing_saga_nextgen
1.0.0
merge_selected_features
0.1
quick_map_services
0.19.34
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The tests were done on bare metal, virtual machines, and virtual Python environments, and I got the same result in all of those situations.

**Comment by roya0045** [comment]
1) bugfix won't change existing versions. 2) as this is a new feature it's normal that it only exist on more recent releases.

**Comment by Darko325** [comment]
It is interesting, as I can recall having worked with the same workflow in the same tool a couple of months ago. However, I am not sure if I worked in a 'Long-Term Release Repository' or a 'Development Version. Not sure at all...

**Comment by agiudiceandrea** [comment]
@Darko325, thanks for reporting. IIUC the issue occurs using QGIS 3.28 and 3.22, while it doesn't occur using QGIS 3.34: this is normal since the new feature https://github.com/qgis/QGIS/pull/51382 was introduced in QGIS >= 3.32.
