### ISSUE TITLE
interpolation

### ISSUE THREAD

**Issue by nimaycgwb** [qgis/QGIS#55478]
### What is the bug or the crash?

I am  not able to use interpolation using IDW function. It is showing the error as listed below
 Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.
023-12-01T15:13:24     WARNING    warning:C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\osgeo\gdal.py:290: FutureWarning: Neither gdal.UseExceptions() nor gdal.DontUseExceptions() has been explicitly called. In GDAL 4.0, exceptions will be enabled by default.
              warnings.warn(
             
             traceback: File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232, in executeAlgorithm
              self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 432, in executeAlgorithm
              dlg.exec_()
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 308, in on_complete
              self.finish(ok, results, self.context, self.feedback, in_place=self.in_place)
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\AlgorithmDialog.py", line 355, in finish
              if not handleAlgorithmResults(
              File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\gui\Postprocessing.py", line 235, in handleAlgorithmResults
              details.project.addMapLayer(owned_map_layer, False)
              File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\RasterAttributeTable.py", line 122, in updateRatActions
              if has_rat(layer):
              File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 523, in has_rat
              if get_rat(raster_layer, band).isValid():
              File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 71, in get_rat
              ds = gdal.OpenEx(raster_layer.source())
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\osgeo\gdal.py", line 5344, in OpenEx
              _WarnIfUserHasNotSpecifiedIfUsingExceptions()
              File "C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\osgeo\gdal.py", line 290, in _WarnIfUserHasNotSpecifiedIfUsingExceptions
              warnings.warn(
             

Kindly help me

### Steps to reproduce the issue

<img width="662" alt="Screenshot 2023-12-01 163134" src="https://github.com/qgis/QGIS/assets/152607307/b1712f0d-896e-421b-890f-139035b6a1d7">

### Versions

QGIS version
3.34.0-Prizren
QGIS code revision
ffbdd67881
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
RasterAttributeTable
1.2
SRTM-Downloader
3.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@nimaycgwb, thans for reporting. The provided message only shows a "warnig", not an "error".
It looks like such message is generated by the RAT RasterAttributeTable third-party external plugin
```
          File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\RasterAttributeTable.py", line 122, in updateRatActions
          if has_rat(layer):
          File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 523, in has_rat
          if get_rat(raster_layer, band).isValid():
          File "C:\Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\RasterAttributeTable\rat_utils.py", line 71, in get_rat
          ds = gdal.OpenEx(raster_layer.source())
```
so I'm closing this issue report because you need to report the issue to the plugin authors or the plugin GitHub source code repository as stated in the issue report form:

> Issue: Bug/Crash report but not related to a third party plugin
> If the issue is related to a plugin, you should file the issue in the plugin code repository.
> You can find the URL in the QGIS Plugin Manager.

Anyway, since QGIS 3.30, much of the RAT RasterAttributeTable external plugin functionalities are now part of the core functionalities of QGIS: please see https://www.qgis.org/it/site/forusers/visualchangelog330/index.html#feature-raster-attribute-tables-rat-support, https://github.com/qgis/QGIS/pull/50687 and https://github.com/qgis/QGIS-Documentation/issues/7877.

**Comment by agiudiceandrea** [comment]
If you have issue with the "IDW Interpolation" QGIS processing algorithm, please provide the whole algorithm execution log and the input layer(s) and algorithm parameter used.

**Comment by nimaycgwb** [comment]
Sir,
Greetings Sir,
I am preparing water quality maps in QGIS. I wanted to do IDW
interpolation but could not do that. I have attached the shape file of the
map , the data table on which I want to process IDW and the message error
coming.

One error is copied and posted below:

An error has occurred while executing Python code:
OverflowError: cannot convert float infinity to integer

Traceback (most recent call last):
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py",
line 305, in pixelSizeChanged
    rows = max(round(self.extent.height() / cell_size) + 1, 1)
OverflowError: cannot convert float infinity to integer


Python version: 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC
v.1928 64 bit (AMD64)]
QGIS version: 3.34.0-Prizren Prizren, ffbdd67881
Python Path:

   - C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python
   - C:/Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python
   -
   C:/Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
   - C:/PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins
   - C:\PROGRA~1\QGIS33~1.0\apps\grass\grass83\etc\python
   - C:\Users\Nimay\Documents
   - C:\Program Files\QGIS 3.34.0\bin\python39.zip
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\DLLs
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib
   - C:\Program Files\QGIS 3.34.0\bin
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\win32\lib
   - C:\PROGRA~1\QGIS33~1.0\apps\Python39\lib\site-packages\Pythonwin
   - C:/Users/Nimay/AppData/Roaming/QGIS/QGIS3\profiles\default/python

**Comment by agiudiceandrea** [comment]
> Traceback (most recent call last): File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python/plugins\processing\algs\qgis\ui\InterpolationWidgets.py", line 305, in pixelSizeChanged rows = max(round(self.extent.height() / cell_size) + 1, 1) OverflowError: cannot convert float infinity to integer

@nimaycgwb the bug generating such error message has been already fixed by PR https://github.com/qgis/QGIS/pull/55211. Please use QGIS 3.34.1 which is not affected by such issue.

**Comment by nimaycgwb** [comment]
after using  QGIS 3.34.1 version i am facing the below error as IDW not
working
