### ISSUE TITLE
Missing simple marker symbols preview in the Symbology dialog

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#55483]
### What is the bug or the crash?

Try to edit a symbology using the simple marker symbol leaf. You will notice that the preview widget at the bottom is empty. Left (3.28), right (3.34)
![image](https://github.com/qgis/QGIS/assets/7983394/0ebfb52d-f73b-4e61-921c-2185006bec59)
![image](https://github.com/qgis/QGIS/assets/7983394/57b7de5e-6c6d-4d15-b4ed-d88e1e737062)
I don't know if it is the same as https://github.com/qgis/QGIS/issues/55349 but you will notice in the first screenshot that the circle size is not rendered in top left widget with the same size, despite the same properties

### Steps to reproduce the issue

See above

### Versions

</head><body>

QGIS version | 3.34.1-Prizren | QGIS code revision | 133927424d9
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 13.6
  |   |   |  
Active Python plugins
changeDataSource | 3.1
qtribu | 0.14.2
bdtopo_importer | 0.2
MemoryLayerSaver | 4.0.4
MapsPrinter | 0.9
lizmap | 3.8.3
StreetView | 3.2
processing | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
I suspect this is mac os specific -- can you reproduce on a different system?

**Comment by nkkkki** [comment]
The problem is still persistent.
