### ISSUE TITLE
PANEL DE PROPIEDADES DE CAPA INUTILIZABLE

### ISSUE THREAD

**Issue by MAIRAMORALES** [qgis/QGIS#55486]
### What is the bug or the crash?

tengo un problema con el panel de propiedades de capa. La ventana que se abre ocupa toda la altura de la ventana y no veo los botones porque están detrás de la barra de tareas. Si trato de mover o reducir el tamaño, el panel desaparece y se desactivan la página hasta que pulso e<<<cape. Como puedo reducir el panel para poder usarlo. No tiene botones para minimizarlo, solo el aspa para cerrarlo.

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/152666974/19f3cc00-e39d-4e52-b841-319d4665c4cc)

### Versions

Versión de QGIS
3.28.13-Firenze
Revisión del código de QGIS
3b4db4f561
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.8.0
Versión de PROJ
9.3.0
Versión del registro de base de datos EPSG
v10.094 (2023-08-08)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.41.1
Versión de PDAL
2.6.0
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
LAStools
2.0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@MAIRAMORALES, thanks for reporting. It seems to me the issue has been already reported: https://github.com/qgis/QGIS/issues/43276.
