### ISSUE TITLE
Vector Cut

### ISSUE THREAD

**Issue by Leaafaar** [qgis/QGIS#55508]
### What is the bug or the crash?

Once you selected a layer and you use the tool, the cut don't do what it seem to do. Don't cut by the mask layer, instead, it recreates the layer. 

### Steps to reproduce the issue

1. You want just a part o the map. 
![image](https://github.com/qgis/QGIS/assets/91898122/9958126e-2002-44de-961c-05a0c964f17d)
2. Go to "vector cut by mask layer"
![image](https://github.com/qgis/QGIS/assets/91898122/86d3302e-cdb3-40e4-ae7f-f768ccc5fede)
3. Select your input layer and your mask layer, then execute 
![image](https://github.com/qgis/QGIS/assets/91898122/b8ca6a34-7a7c-4c8e-a374-548305ad3e76)
4. You have a new layer but it's not cutted. 
![image](https://github.com/qgis/QGIS/assets/91898122/2743c3dd-f1f6-4e99-b60c-c64d74ac53b9)

### Versions

Versión de QGIS
3.34.1-Prizren
Revisión del código de QGIS
133927424d
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.8.1
Versión de PROJ
9.3.1
Versión del registro de base de datos EPSG
v10.098 (2023-11-24)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.41.1
Versión de PDAL
2.6.0
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
OGR processing tools do not work with memory layers.
I guess we should not list them as available layers for those algorithms.
You can use the _Clip_ native qgis algorithm instead.

**Comment by agiudiceandrea** [comment]
> OGR processing tools do not work with memory layers.

@uclaros, are you sure? AFAIK OGR processing tools works also with memory layers as they are automatically converted to temporary GPKG (or the format specified in the processing settings) files.

**Comment by uclaros** [comment]
> @uclaros, are you sure?

Not at all ;P I was tricked by the weird ogr2ogr generated command!
They do work perfectly indeed!

@Leaafaar can you share the data you are trying to clip?
