### ISSUE TITLE
DWG Import Tool default polyline layer style - thick symbol applied when "width" field is NULL

### ISSUE THREAD

**Issue by she-weeds** [qgis/QGIS#55512]
### What is the bug or the crash?

When importing a .dwg using the DWG Import Tool, the polylines layer has a style applied by default. There are two symbols, a thin line and a thick line.

The thick line is erroneously applied when the `"width"` field is `NULL`, resulting in undesirable output as below (and extra steps to disable this). 

![thick lines](https://github.com/qgis/QGIS/assets/41975056/7ae799c6-127c-4d87-9dd0-b35f70b92185)

This is because the thick line symbol has a data-defined override of `"width" > 0`.  Could the data-defined override be changed to `coalesce("width",0) > 0` or similar to avoid unwanted thick line symbols?

### Steps to reproduce the issue

1. Import DWG using DWG Import Tool 
2. A polylines layer is generated with a default style. The style has two symbols.
3. The thin line symbol visibility is controlled by a data-defined override expression of `"width" = 0` and the stroke width is controlled by `"linewidth"`. This is okay.
4. The thick line symbol visibility is controlled by a data-defined override expression of  `"width" > 0` and the stroke width is controlled by `"width"` and a default GUI value  of 0.26 map units.
5. However, if the polylines layer features have a width of NULL, the stroke width defaults to the default GUI value which is 0.26 map units. This is unreasonably thick as a default and confusing for less technically inclined users

![polylines_style](https://github.com/qgis/QGIS/assets/41975056/fcbfb80f-50b7-4694-a88b-13d99708afe3)

Attached is an example of a polylines output from QGIS 3.34 (initial style is saved as default in gpkg). 

[github_dwg_import.zip](https://github.com/qgis/QGIS/files/13554285/github_dwg_import.zip)

### Versions

QGIS version
3.34.1-Prizren
QGIS code revision
133927424d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
https://github.com/qgis/QGIS/blob/724311fb228e32aedf486eeb674618e966adcbaa/src/app/dwg/qgsdwgimportdialog.cpp#L368
https://github.com/qgis/QGIS/blob/724311fb228e32aedf486eeb674618e966adcbaa/src/app/dwg/qgsdwgimportdialog.cpp#L379
