### ISSUE TITLE
Saving feature in vector layer with default boolean value represented by string   

### ISSUE THREAD

**Issue by PeterPetrik** [qgis/QGIS#55517]
### What is the bug or the crash?

Saving feature in vector layer with default boolean value represented by string  is not working anymore in QGIS 3.34.x
This was introduced in https://github.com/qgis/QGIS/pull/54905/files 

It may be bug or feature (?), but definitely it is change of behaviour between versions. 

If the new behaviour is intended, feel free to close the bug report.

### Steps to reproduce the issue

1. open project in QGIS 3.34.0 or 3.34.1
project has boolean field that is populated by string `'true'` or `'false'` as default value 
2. add new point
3. end digitizing 
4. on save  `wrong data type for attribute 1 of feature -2: 10`

Project:
[truefalseregression.zip](https://github.com/qgis/QGIS/files/13561993/truefalseregression.zip)

Error:
![Screenshot 2023-12-05 at 15 52 00](https://github.com/qgis/QGIS/assets/804608/3a62f690-f675-496d-9e58-20ecf0a51cdb)

### Versions

3.34.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
Expression `true = 'true'` still evaluates as `1`, so I believe this is a bug

**Comment by TSanderPGG** [comment]
I can also confirm and would like to add our experiences with the issue. It is also happening with QField 3.1.0. While we were able to fix the issue in QGIS using the suggestion mentioned here: [https://merginmaps.com/docs/field/broken-project/#saving-of-feature-failed-vector-layer](url) (remove single quotation marks), this did not fix the issue in QField. We were still not able to save a feature although we removed the single quotation marks in the default value.
In addition to boolean fields we also had an issue using "uuid('WithoutBraces')" as an default value in text fields.
**Error:**
![image](https://github.com/qgis/QGIS/assets/80879779/285e3b62-ee33-4b65-adcd-1dd63dfecc54)
**Attribute 1:**
![image](https://github.com/qgis/QGIS/assets/80879779/38bc0e0b-68ad-44f6-ab54-52a2c92b2b58)
**Attirbute 7:**
![image](https://github.com/qgis/QGIS/assets/80879779/80659657-377a-422a-84c2-89021175c07f)
**Error in QField after removing the single quotation marks and the "uuid()" default value:**
![Screenshot_20231218-094750](https://github.com/qgis/QGIS/assets/80879779/3f8c9e89-7e63-4c9f-ad16-b621236e9725)
