### ISSUE TITLE
Annotation does not end up on selected annotation layer

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#55515]
### What is the bug or the crash?

I cannot toggle visibility for my annotations and they even stay after removing the annotation layer on which they were added.

### Steps to reproduce the issue

1. Have a new QGIS project
2. Add a new annotation layer using the toolbar
3. Make sure the annotation layer is the active layer
4. Add an text annotation (the rightmost T in the blue speech bubble) using the toolbar
5. Toggle the visibility of the annotation layer
6. **The annotation is still visible.**
7. Remove the annotation layer
8. **The annotation is still visible.**

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.34.0-Prizren | QGIS-Codezweig | Release 3.34
-- | -- | -- | --
Qt-Version | 5.15.11
Python-Version | 3.11.5
GDAL-Version | 3.7.3
PROJ-Version | 9.3.0
EPSG-Registraturdatenbankversion | v10.094 (2023-08-08)
GEOS-Version | 3.12.0-CAPI-1.18.0
SQLite-Version | 3.44.0
PDAL-Version | 2.6.0
PostgreSQL-Client-Version | 16.0
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Manjaro Linux
  |   |   |  
Aktive Python-Erweiterungen
plugin_reloader | 0.9.3
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS-Version
3.34.0-Prizren
QGIS-Codezweig
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt-Version
5.15.11
Python-Version
3.11.5
GDAL-Version
3.7.3
PROJ-Version
9.3.0
EPSG-Registraturdatenbankversion
v10.094 (2023-08-08)
GEOS-Version
3.12.0-CAPI-1.18.0
SQLite-Version
3.44.0
PDAL-Version
2.6.0
PostgreSQL-Client-Version
16.0
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Manjaro Linux

Aktive Python-Erweiterungen
plugin_reloader
0.9.3
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

it feels like they get added to the secret main annotation layer instead of the active layer?

**Comment by YoannQDQ** [comment]
There are currently two annotation systems coexisting in QGIS:

- The legacy, "speech-balloon" annotations (Text, Form, SVG and HTML)
- The newer layer-based annotations, with text, line, symbol and polygon annotations 

New-style annotations are automaticaly created on the active annotation layer. If no layer is selected, they are created on the main annotation layer.

Legacy annotations aren't. In fact, legacy annotation can be linked to any layer (see the 'linked layer' combobox in the screenshot below)

![image](https://github.com/qgis/QGIS/assets/9693475/e62f99ef-7756-43bb-87bd-f24214831785)

If you manually link them to the annotation layer, you kinda get the behavior you're looking for ; they will be toggled on and off alongside the layer. They won't be deleted if the linked layer is removed though. Instead, the behavior is kinda glitchy: they are hidden when the layer is deleted, but not removed, then reappear when another layer visibility is toggled.


A possible way forward would be to:
- Automatically link legacy annotation to the selected annotation layer (if any)
- Automatically remove annotation when their linked layer is removed

However, IIUC, the end-goal is to drop the legacy system in favor of the new one, so there is little motivation to do some work for the doomed speech-ballons annotation.

**Comment by kannes** [comment]
Whew, so I was just thoroughly confused about annotations in general. As a user who had not user annotations before it is super weird how there are different things in that toolbar. Sounds like a possible UI/UX bug or feature request but I'll close this one as PEBKAC. :)

I had created a annotations layer (new system) and then used the speech-ballon annotations (old system). I will switch to modern annotations instead.

Thank you!
