### ISSUE TITLE
Drag and Drop from Windows Explorer into Layers or Map Canvas not working

### ISSUE THREAD

**Issue by eortmayr** [qgis/QGIS#55521]
### What is the bug or the crash?

QGIS 3.28 LTR allows the user to drag and drop .SHP and .TIF files from windows file explorer onto the Map Canvas or Layers to add the data without going through the Browser. QGIS 3.34.1 does not allow the user to do this, so I assume this is a bug. 

### Steps to reproduce the issue

On a Windows 11 PC running QGIS 3.34.1:
Go to: windows explorer and navigate to a folder that has a .SHP and a .TIF file in it. 
Click on: .SHP or .TIF file and drag onto the Map Canvas or the Layers panel
See error: the user gets a red circle with a stripe through it. When the user lets the mouse button go, the layer is not added to the QGIS project. 

On the same PC using QGIS 3.28.9:
Go to: windows explorer and navigate to a folder that has a .SHP and a .TIF file in it. 
Click on: .SHP or .TIF file and drag onto the Map Canvas or the Layers panel
See error: the user gets a +COPY icon and the layer is added to the QGIS project when the mouse button is let go. 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code revision | 133927424d
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.1
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
felt | 1.1.0
Qgis2threejs | 2.7.1
qgis2web | 3.17.0
raster_clip | 0.1
survey_plot_pts | 2.1
what3words | 4.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.1-Prizren
QGIS code revision
[133927424d](https://github.com/qgis/QGIS/commit/133927424d)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
felt
1.1.0
Qgis2threejs
2.7.1
qgis2web
3.17.0
raster_clip
0.1
survey_plot_pts
2.1
what3words
4.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@eortmayr, thanks for reporting. The reported issue is usually due to the fact that QGIS is incorrectly run as Administrator. Please see: https://superuser.com/questions/59051/drag-and-drop-file-into-application-under-run-as-administrator.

**Comment by eortmayr** [comment]
Thank you for your help, this worked!

Indeed, I was running as administrator on 3.34.1 and not with the other version:

***@***.***

When unchecked, the drag and drop worked fine!  I see the issue is very old, I am surprised I haven't run into this before now.

Regards,

Eric
