### ISSUE TITLE
Measurement Tool with Radius Circle

### ISSUE THREAD

**Issue by NickGeoJo** [qgis/QGIS#55523]
### Feature description

QGIS would rock even more if the Measurement Tool had a circle at the radial distance it was measuring. 
Similar to a measuring tools in other MAPping/geographic INFOrmation systems software, it'd be useful in measuring how far different features of a map are from each other without having to swing the mouse around at each one.

Currently I'd use Buffers on Points, set the transparency and then check out if features are overlaid by the buffers.

Useful for:
- Quickly working out the closest train station to a landmark
- Working out how many bends in a river from a central bridge
- Visualsing horizontal distances between trees

I don't have much experience with programming but would be happy to be pointed in the right direction to help out.

**Comment by benwirf** [comment]
I wouldn't mind looking into adding this feature. As a first step, I have put together a rough, basic PyQGIS implementation of this and packaged it into a minimal Plugin. You can download the plugin as a zip file from my [GitHub repo](https://github.com/benwirf/measure-radius) and Install from ZIP via the Plugin Manager in QGIS.

![Screenshot from 2023-12-10 19-42-25](https://github.com/qgis/QGIS/assets/47767794/4b441715-7966-4a96-9823-9c0735d55eeb)

I will try to spend some time over the Christmas break to get it working in a local build, with a view to submitting a PR. Of course there's no guarantee it would be accepted and merged though.

In the meantime, feel free to use and test the plugin- I would appreciate any feedback on behavior/ functionality etc.

Below is a quick screencast (apologies for the poor quality).

![output3](https://github.com/qgis/QGIS/assets/47767794/3ba07a1e-ecd1-4655-a1cc-3cdfd20d140f)

**Comment by NickGeoJo** [comment]
Simply A-mazing @benwirf .
Exactly what I was looking for.
I downloaded, added to qgis plugin as zip etc. works well.

- I like the semi-transparent circle, line width and colours are a good choice. 
- Left-Click= start and Right-Click= lock is great too.
- Only minor issue is if I Left-Click a second time I lose always-on-top/focus of the Distance calculator window. I've got a second screen and can move that window but if you only had a single screen it'd be a little annoying.
- Hopefully more people pick up on this as it's very useful.
Thanks.

**Comment by benwirf** [comment]
@NickGeoJo, that's great- thanks for the feedback. Do you use Windows or OS? Because I didn't encounter that issue on Ubuntu. I will test on Windows & try to add a fix.
Cheers

**Comment by NickGeoJo** [comment]
I'm using Windows 11. I'm happy to use as is, your work is appreciated!

**Comment by benwirf** [comment]
Have just added a feature I've been meaning to implement for a while- snapping functionality. Any active project snapping settings are now respected by the radius map tool.

**Comment by benwirf** [comment]
OK, I've started porting this to C++. Hopefully this will be added to core for a future release in the not to distant future.
