### ISSUE TITLE
Editing vertices of multiple layers sometimes leaves in a crashed, but partially responding state

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#55536]
### What is the bug or the crash?

QGIS some times stops working properly during vertex editing. I have not found a clean reproducible example but want to share my findings so far:

- My project CRS is EPSG:25833.
- I have 12 layers from 1 GeoPackage. 7 are Point, 5 are LineString geometries. There are less than 50 features in total.
- The default OSM background layer is loaded.
- In their digitizing settings all layers are set to a precision of 0.01, do drop duplicate nodes and line layers are set to check validity.
- All layers are in editing state and the node editor is active.
- Snapping is enabled on all layers and vertices.
- Topological editing is enabled.

I was fixing topology errors like line endings not meeting or points not being on line endings. I was also moving line vertices around, which topologically moved points and other lines' vertices. I zoom and pan around a lot, sometimes with a node "picked up" by the mouse.

QGIS freezes in a way where:
- The map canvas rendering is stuck with a cached image from mid pan/zoom.
- I see a moving progress bar on the left of the coordinate field at the bottom of the QGIS window. At some point this freezes.
- Sometimes I see red lines highlighting when I move the mouse around on the canvas, just as if I could edit them, for a short while.
- The mouse cursor is still a crosshair
- Sometimes I can save all edits and disable editing mode for a short while.

After a while QGIS is completely frozen. There is no significant CPU usage or anything.

There is no interesting information in the terminal, just several lines of `Warning: QPen::setWidthF: Setting a pen width that is out of range`.

If I attach with `strace` then all I see is:
```
$ sudo strace -p $(pidof qgis)
strace: Process 20555 attached
futex(0x55b9662a77b4, FUTEX_WAIT_PRIVATE, 2147483667, NULL
```

The only way to continue is to kill the QGIS process.

### Steps to reproduce the issue

I haven't managed to reproduce the exact steps, it happened multiple times within the last hour while working with the dataset mentioned above. Also in a new profile. I can share the data privately if necessary.

I suspect it happens if I have a node "picked up" (from an existing node or from a line midpoint) and zooming/panning at the same time because I think every time I had a map canvas that was before re-rendering (eg pixelated OSM basemap).

I don't know if topological editing is involved or snapping or the multiple layers in edit mode.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.5
GDAL/OGR version | 3.7.3
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
Compiled against SQLite | 3.44.0 | Running against SQLite | 3.44.2
Compiled against PDAL | 2.6.0 | Running against PDAL | 2.6.1
PostgreSQL client version | 16.0
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.11
Python version
3.11.5
GDAL/OGR version
3.7.3
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
Compiled against SQLite
3.44.0
Running against SQLite
3.44.2
Compiled against PDAL
2.6.0
Running against PDAL
2.6.1
PostgreSQL client version
16.0
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Manjaro Linux

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
This sounds familiar!
Maybe the same as/related to #38206 ?

**Comment by kannes** [comment]
That sounds very likely, I will try to disable parallel rendering tomorrow and see if I get no freezes anymore.

**Comment by kannes** [comment]
Yes, that seems like the same bug. Thank you!
