### ISSUE TITLE
Snapping to Segment is overlapping or behaving completely random

### ISSUE THREAD

**Issue by firefoxlover** [qgis/QGIS#55540]
### What is the bug or the crash?

A newly created polygon with snapping to area, segment and Vertex, just overlaps the other Polygon.

This is very bad, and is not fixable even manually. Snapping to the polygon does not work!

### Steps to reproduce the issue

Create a polygon, try to snap to its side by selecting "snap to area" and "snap to segment".

See the attached video

### Versions

3.34.0
Qt 5.15.11
Python 3.12.0

Fedora 39

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

https://github.com/qgis/QGIS/assets/78762110/a373abd3-2b17-4daa-828e-a8e058f9ed2b

**Comment by firefoxlover** [comment]
this is quite horrible because I am failing an class excersize due to many many overlaps

**Comment by firefoxlover** [comment]
also I found out I had snapping errors all over the shapefile, resulting in tiny gaps.

Not everywhere but a lot of times, and I use aggressive snapping to avoid this

**Comment by firefoxlover** [comment]
I am using Gauß-Krüger DHDN zone 3

[example-snapping-problem.zip](https://github.com/qgis/QGIS/files/13605734/example-snapping-problem.zip)

Didnt know snapping to segment was problematic... But disabling it and only having "snap to area" it has the same effect

**Comment by firefoxlover** [comment]
weird, I thought I was using DHDN z3 which would fit there?

So If I want to snap to the rim of a polygon I should use snap to segment? How do I enable this topological editing?

I dont know this doesnt seem to be a bug then, but until I cant reproduce I would leave it open. Just need to say that without any descriptions of what the settings do, this is very confusing and bad UX

**Comment by DelazJ** [comment]
> How do I enable this topological editing?

Going to the right on the same snapping toolbar https://docs.qgis.org/testing/en/docs/user_manual/working_with_vector/editing_geometry_attributes.html#topological-editing ?

**Comment by uclaros** [comment]
> Just need to say that without any descriptions of what the settings do, this is very confusing and bad UX

Could you elaborate? What would you change to make it less confusing for you?

**Comment by firefoxlover** [comment]
I am still confused. Why are there multiple DHDN gauß krüger zone 3? I changed the CRS again in the property settings and they where all displayed as the same thing.

And I still have the issue, some objets snap perfectly together and some are randomly moving, like in the videos. Some are perfectly on one point...

**Comment by uclaros** [comment]
You should be getting one DHDN gauß krüger zone 3
![image](https://github.com/qgis/QGIS/assets/11358178/74c9c6ac-12e8-4b0d-acdb-e83f417a7a92)

You should set your _Project's_ crs to match that.

You should make sure the coordinates you digitize fall inside the coordinates range of the selected crs. This should not be actually needed if both layer and project crs match, but it really does not make any sense to have coordinates outside the crs' usable area.

**Comment by firefoxlover** [comment]
https://github.com/qgis/QGIS/issues/29648

This bug is caused by that old and closed bug! Changing the projects CRS to that of the layer fixed it. 

So that named bug is not fixed! Until it is reopened I propose to keep this one open

**Comment by DelazJ** [comment]
It is unclear to me where your workflow actually uses topology editing but #51245 is already a replacement for #29648.

**Comment by firefoxlover** [comment]
@DelazJ I created regular polygons in a polygon shapefile layer. No idea of topological editing so I suppose not

**Comment by firefoxlover** [comment]
Even though having displayed multiple DHDN options, that was not the problem.

Thanks for your support, it was the projects CRS which for some reason is not the layer CRS. Will close this issue and open a FR to fix this.

I can imagine that this is an intended / wontfix bug, as solving this could be a pain.

**Comment by uclaros** [comment]
I think you got this wrong: Snapping works when using different crs for layer and project. The issue with your project is that you were digitizing _way_ outside your CRS's extent, causing a _ballpark-oinly_ transform to be used and a warning about that to be displayed.
