### ISSUE TITLE
Impossible to set "Maximum cores to use for map rendering" to 1

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#55555]
### What is the bug or the crash?

I want to set "Maximum cores to use for map rendering" to 1 but I can only choose "All Available (16)" or a number between  (inclusive) 2 and 16.

### Steps to reproduce the issue

1. Find Options -> Rendering -> "Maximum cores to use for map rendering"
2. Try to set it to 1
3. When going down from 2 it will read "All Available (n)", where n is your system's number of cores

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.5
GDAL/OGR version | 3.7.3
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
Compiled against SQLite | 3.44.0 | Running against SQLite | 3.44.2
Compiled against PDAL | 2.6.0 | Running against PDAL | 2.6.1
PostgreSQL client version | 16.0
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Manjaro Linux
  |   |   |  
Active Python plugins
db_manager | 0.1.20
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
It's by design. Qt internals require at least two threads for rendering.
