### ISSUE TITLE
QGIS crashes regularly after completely fresh install.

### ISSUE THREAD

**Issue by Xadamo** [qgis/QGIS#55578]
## User Feedback

Qgis keeps on crashing every 30 minutes while I am creating simple farm roads. The only consistent pattern I see is that it keeps happening after I have used the Forest Road Designer plugin. Strangely enough, the crash mostly happens after the use of the plugin when I am working on my new road layer, so I dont actually think it is the plugin itself that makes QGIS crash.. 

It happens both in QGIS 3.34.1 and in QGIS 3.28 LTR. I also tried creating a new profile..

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005a6c (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QGraphicsItem::setVisible :
QgsVertexTool::mouseMoveNotDragging :
QgsVertexTool::cadCanvasMoveEvent :
QgsMapCanvas::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.13-Firenze
QGIS code revision: 3b4db4f561
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.1
Running against GDAL: 3.8.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

1. create a road layer.

2. Use the forest road designer plugin to create new roads.

3. Merge and copy the new road segments into the new road layer.  

4. Do this several times and you will end up with a crash...

### Versions

**QGIS Info**
QGIS Version: 3.28.13-Firenze
QGIS code revision: 3b4db4f561
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.1
Running against GDAL: 3.8.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
If this issue shows only after using that plugin then the fault is with the plugin, and needs to be reported to the plugin authors.

**Comment by Xadamo** [comment]
I think it is indeed just a problem with the forest road designer plugin and I reported it tot the plugin creators.
