### ISSUE TITLE
It is possible to bind to one of the layers when multiple layers are created

### ISSUE THREAD

**Issue by Zexere** [qgis/QGIS#55582]
### What is the bug or the crash?

I work with QGIS through Python, I create new layers in memory based on WFS layers from Geoserver, in a random layer creation session I have no opportunity to adequately work with one of them (random), I cannot do Snepping to it, hide from Vertex is a layer, it is quite possible that in the next iteration of creating layers everything will be okay, but I need something that will always work

### Steps to reproduce the issue

mem_layer = QgsVectorLayer('LineString?crs=epsg:3857', 'Tower', "memory")

for feat in layer_object.getFeatures():
    feats.append(feat)

attr = layer_object.dataProvider().fields().toList()
mem_layer_data.addAttributes(attr)
mem_layer.updateFields()
mem_layer_data.addFeatures(feats)
QgsProject.instance().addMapLayer(mem_layer, False)
self.edit_group.addLayer(mem_layer)

### Versions

Version QGIS
3.28.10-Firenze
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.3
quick_map_services
0.19.33
db_manager
0.1.20
dtekvalidator
0.1
grassprovider
2.12.99
MetaSearch
0.3.6
parser_2
0.1
processing
2.12.99
sagaprovider
2.12.99
dtekqgiseditor
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Zexere, it seems to me you are asking a question about how to use PyQGIS. In this case, please consider that:

> Question
> Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.
