### ISSUE TITLE
"Delete Seleted" button not working properly in a not geometric layer

### ISSUE THREAD

**Issue by JOTAELE1012** [qgis/QGIS#55618]
### What is the bug or the crash?

Hi everybody,
In the Canvas, when I'm using the edition mode with a not geometric layer (a layer without any geometry column), if I select one or more features, the "Delete Selected" button is not able to be used. That button is able to be used once you have changed the active layer in the "Layers Panel" and come back again to your not geometric layer.

I'm using QGIS 3.28.X and Windows 11.

### Steps to reproduce the issue

1.- Turn on the edition mode a not geometric layer
2.- In the Canvas, select one or more features.
3.- Then you´ll see the "Delete Selected" button is not able to be used.
4.- Change another active layer in the "Layers Panel"
5.- Come back to active the previous not geometric layer in the "Layers Panel"
6.- Then, the "Delete Selected" button is able to work properly.

### Versions

QGIS 3.28.X and Windows 11

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@JOTAELE1012, thanks for reporting. May you please provide the **exact steps** and and exact names of the tool used e the type of the layer involved in order to replicate the described behaviour? May you please explain how do you select one or more features in the map canvas if the current layer in editing mode is a "no geometry" layer (which cannot have any feature geometry, so there is no geometry visible and selectable in the map canvas)?

**Comment by JOTAELE1012** [comment]
Hi @agiudiceandrea, thanks for your answer. You are right, I do the selection of the feature using the "Select Features by Values... (F3 key)" button (in the Selection Toolbar). I have tested this bug in different types of layers, as PostGIS tables or GeoJSON. So, the exact steps to replicate this behaviour are:

1.- Turn on the edition mode a not geometric layer.
2.- In the Canvas, select one or more features using using the "Select Features by Values... (F3 key)" button (in the Selection Toolbar).
3.- Then you´ll see the "Delete Selected" (in the Digitizing Toolbar) button is not able to be used.
4.- Change another active layer in the "Layers Panel"
5.- Come back to active the previous not geometric layer in the "Layers Panel"
6.- Then, the "Delete Selected" button is able to work properly.

Although I can avoid it in several ways: Going to the attribute table and the "Delete Selected" will be able to be used, or turning on the edition mode after selecting the features... I see this as a bug that should not happen.

Thanks

**Comment by DelazJ** [comment]
It looks like this affects also vector layers with geometry IF the layer is turned off when you do the selection (from attribute table, from selection toolbar using select by value, select all, select by expression) or the deselection. And it is not only about the "Delete selected features" button but afaics all this block of tools (copy features, cut features, modify attributes for selected features, delete selected features)
![image](https://github.com/qgis/QGIS/assets/7983394/2605c6ce-e808-4f81-9d54-db15469028ec)
 
Reselecting the layer after another one, **without changing its visibility status**, makes the tool(s) available.

https://github.com/qgis/QGIS/assets/7983394/a3231ecb-15cf-48cb-9d4b-15b601c54c49

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.35.0-Master | QGIS code revision | 4dca98c9aae
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PDAL version | 2.6.0
PostgreSQL client version | 15.5 (Debian 15.5-0+deb12u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux 12 (bookworm)
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
qgis_resource_sharing | 1.0.0
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>
