### ISSUE TITLE
Cannot make graduated symblogy with joined fields

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#55626]
### What is the bug or the crash?

When trying to set symbology on a layer with joined fields, the joined fields do not appear in the drop-down list for the Value field. if you try to type them in, once you move away from the field it is cleared.

### Steps to reproduce the issue

1. start a new project
2. create new layer with a few features and and an attribute for joining and save it as an ESRI shapefile
3. create a CSV file with two columns, the joinable column and another column with arbitrary number data for the same number of rows as the shapefile has features
4. load the CSV file as a layer
5. in the shapefile layer, do a join with the CSV layer
6. go to the Symbology tab o fteh layer properties window
7. change to 'Graduated'
8. try to select the joined arbitrary number data field 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.35.0-Master | QGIS code revision | 6cf940c20d6
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
quick_map_services | 0.19.34
buffer_without_overlaps | 0.2
splitmultipart | 1.0.0
debug_vs | 0.8
IPyConsole | version 2.0
naficp | 1.0
GroupStats | 2.2.7
QuickOSM | 2.2.3
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.35.0-Master
QGIS code revision
[6cf940c20d6](https://github.com/qgis/QGIS/commit/6cf940c20d6)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.9 (Ubuntu 14.9-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

This copy of QGIS writes debugging output.

Active Python plugins
quick_map_services
0.19.34
buffer_without_overlaps
0.2
splitmultipart
1.0.0
debug_vs
0.8
IPyConsole
version 2.0
naficp
1.0
GroupStats
2.2.7
QuickOSM
2.2.3
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
Is the field available if you select "Categorized" symbology? Also what happens if you apply/OK the properties dialog before trying to use the join for symbology?

**Comment by CoryAlbrecht** [comment]
@DelazJ

> Is the field available if you select "Categorized"

With "Categorized" I can select the joined field for categorized, but that doesn't produce a gradient that matches a numerical value.

> Also what happens if you apply/OK the properties dialog before trying to use the join for symbology?

That does not make a difference.

**Comment by CoryAlbrecht** [comment]
So I noticed today that the CSV file as a layer has all fields interpreted as text, even when numeric and not quoted, and that this cannot be changed.

**Comment by CoryAlbrecht** [comment]
Example project 
[qgis-issue-55626.zip](https://github.com/qgis/QGIS/files/13688634/qgis-issue-55626.zip)

**Comment by CoryAlbrecht** [comment]
Using CSVT files did not change this bug.

**Comment by CoryAlbrecht** [comment]
Somebody needs to stop the github-actions 'bot from automatically marking things as stale and then later closing them. Tickets fro needed fixes get lost that way. :-1:  :disappointed:

**Comment by DelazJ** [comment]
Using a csvt with following content recognizes your integer field, making them available for graduated rendering
> "string","integer","integer","integer","integer","integer"

![image](https://github.com/qgis/QGIS/assets/7983394/79474e86-d602-4f11-89fc-c0269ad4a394)

**Comment by CoryAlbrecht** [comment]
When I downgraded from Master to 3.34.2 recently, because of another issue, the CSVT file started having an effect.
