### ISSUE TITLE
Changing symbology using Layers panel doesn't trigger project dirty status

### ISSUE THREAD

**Issue by fruitbaticus** [qgis/QGIS#55623]
### What is the bug or the crash?

Changing a layer's symbology using the legend in the layer browser panel doesn't mark the project as having changed. Therefore the project save dialog isn't triggered when quitting which can cause lost work.

### Steps to reproduce the issue

1. Add a vector layer to a project (tested with spatialite and PostGIS).
2. Set the symbology to categorized and categorize the layer based on an attribute.
3. Make sure project is saved.
4. Change symbology of one of the categories using the layer browser preview
![image](https://github.com/qgis/QGIS/assets/747442/859a8142-9f33-4f6d-aae9-5417b217e9ec)
5. Note that the project name doesn't have the "changed" asterisk, and when closing it does not prompt to save.

### Versions

QGIS version
3.34.1-Prizren
QGIS code revision
133927424d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by JuhoErvasti** [comment]
I can confirm this one (3.32- Lima). The selections are saved to the project file if you remember to save the project but the project is not marked as modified.

**Comment by uclaros** [comment]
Also applies to adding/changing/pasting style through the context menu.
