### ISSUE TITLE
Pandas import failes with QGIS 3.32, 3.34 under Windows 10

### ISSUE THREAD

**Issue by hoettges** [qgis/QGIS#55637]
### What is the bug or the crash?

import pandas causes an error in QGIS 3.32 and 3.34 (Windows 10)
in QGIS 3.30 and older everything works fine...

### Steps to reproduce the issue

Open python console in QGIS on Windows 10
Type: "import pandas"

### Versions

3.32, 3.34

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I didn't try with a new QGIS profile, but used freshly installed versions of QGIS 3.32 and QGIS 3.34

**Comment by agiudiceandrea** [comment]
@hoettges, thanks for reporting. On my Windows 10 system I can import pandas without issues in the Python console neither using QGIS 3.34.1. May you please explain in more details how did you install QGIS and what is the issue and provide the error messages displayed importing the pandas module, if any? Please, also try if the issue occurs also using a new QGIS user profile.

**Comment by agiudiceandrea** [comment]
@hoettges, thanks for reporting. On my Windows 10 system I can import pandas without issues in the Python console using QGIS 3.34.1.
May you please explain in more details how did you install QGIS and what is the issue and provide the error messages displayed importing the pandas module (if any)?
Please, also try if the issue occurs also using a new QGIS user profile and provide the full QGIS version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") as requested in the issue report form.

**Comment by hoettges** [comment]
Problem fixed (for me...)! I deleted a site-package from an old standalone python39 in C:\Users\{user}\AppData\Roaming\Python. But how did QGIS 3.34 try to use this package?
