### ISSUE TITLE
Tileservers always blurry

### ISSUE THREAD

**Issue by TurntSnackoo** [qgis/QGIS#55644]
### What is the bug or the crash?

All tileserver layers I've tested appear blurry and unfocused, regardless of the zoom level. Issue is ***not*** because the projection is incorrect. Project CRS and tileserver CRS are all at 3587. I've even tried switching project and/or tileserver CRS to 4326 and vice versa to find some compatibility issue or something, no luck.
![image](https://github.com/qgis/QGIS/assets/140560866/17b28439-3c80-4e5c-96e1-0faa936ee3e4)

### Steps to reproduce the issue

Open QGIS. Add any XYZ tileserver layer. See error.

### Versions

QGIS version
3.34.1-Prizren
QGIS code revision
133927424d
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I encountered this error first on 3.32. One of the things I tried to do to fix it was update to the current version, but the problem remains.

**Comment by TurntSnackoo** [comment]
I wouldn't be suprised if I did something stupid to cause this to happen and it's not actually a bug but still I have tried things people suggested me to do to fix it and northing works and I have no idea what I am doing :c

**Comment by TurntSnackoo** [comment]
*whoops

**Comment by mblesius** [comment]
Do the tiles also appear blurred on an exported layout?

**Comment by TurntSnackoo** [comment]
> Do the tiles also appear blurred on an exported layout?

Yeah, when just viewed in the layout manager screen it still looks blurry

**Comment by mblesius** [comment]
Can you verify this, by exporting a layout to pdf or image? The issue might be a rendering bug due to incorrect scaling in the map canvas, thus appearing there but not in the exported layout.

**Comment by TurntSnackoo** [comment]
I see, i'm not familiar with the layout stuff at all so I had to look up what you meant :P
Hmmm... I think it might be a bit less blurry? But i think it's still a bit more blurry than it once used to be, though I'm not 100% on that.
Here's a comparison with the view in the layout manager vs the exported PDF:
![image](https://github.com/qgis/QGIS/assets/140560866/f27e6231-baad-4521-9e22-82f47d0538d3)
![image](https://github.com/qgis/QGIS/assets/140560866/23c2757f-ce51-4317-8fe7-1bc76f2077de)

**Comment by mblesius** [comment]
> Hmmm... I think it might be a bit less blurry? But i think it's still a bit more blurry than it once used to be, though I'm not 100% on that.

The standard OpenStreetMap tiles are low resolution, not sure if 72 or 90 dpi, but they look blurry on a high dpi screen. They are not designed for printing in a higher resolution, e. g. 300 dpi. Thus, I think the layout looks fine. But the map preview in the print layout may look blurry due to incorrect high dpi scaling (a bug in QGIS). Are you using a 4K monitor?

For reference see:
https://wiki.openstreetmap.org/wiki/High-resolution_tiles
https://www.maptilesapi.com/retina-tiles/compare/

This may apply to other tiled web services as well.

**Comment by TurntSnackoo** [comment]
Yeah you're right, it's just been like 6 months since the last time I used QGIS without the bug so I forgot, haha.
Anyway, no, my monitor is 1080p.
