### ISSUE TITLE
Empty polygon causes tool `Extract vertices` to crash

### ISSUE THREAD

**Issue by jfbourdon** [qgis/QGIS#55656]
### What is the bug or the crash?

Trying to extract the vertices of an empty polygon (empty geometry) with the native processing tool `Extract vertices` causes QGIS to crash instead of returning a QgsVectorLayer without any points. Doing the same operations with an empty linestring doesn't crash. The issue seems to arise strangely only when the tool is run via the GUI. Also, the tool `Extract specific vertices` doesn't seem too be affected.

```
Stack Trace

QgsAbstractGeometry::vertex_iterator::digDown :
QgsAbstractGeometry::vertex_iterator::vertex_iterator :
QgsExtractBinaryFieldAlgorithm::tags :
QgsProcessingFeatureBasedAlgorithm::processAlgorithm :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
pdal::Option::getName :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

```python
lyr = QgsVectorLayer("polygon?crs=epsg:3857", "polygon", "memory")
geom = QgsGeometry.fromWkt('Polygon ()')
geom.isEmpty()  # True
fet = QgsFeature()
fet.setGeometry(geom)
lyr.dataProvider().addFeature(fet)

# Doesn't crash:
processing.run("native:extractvertices", {'INPUT':f'memory://{lyr.source()}','OUTPUT':'TEMPORARY_OUTPUT'})

# Crash:
QgsProject.instance().addMapLayer(lyr)
# Then run  'Extract vertices' on the newly created layer via the GUI

```

### Versions

QGIS 3.28.13
QGIS 3.34.1

Windows 10 Enterprise 21H2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
gdb backtrace on Windows:
```
#0  0x000007fecb7e8983 in QgsAbstractGeometry::vertex_iterator::digDown () at /__w/QGIS/QGIS/src/core/geometry/qgsabstractgeometry.cpp:531
#1  0x000007fed85fd57e in QgsAbstractGeometry::vertices_begin () at /__w/QGIS/QGIS/src/core/geometry/qgsabstractgeometry.h:1001
#2  QgsExtractVerticesAlgorithm::processFeature () at /__w/QGIS/QGIS/src/analysis/processing/qgsalgorithmextractvertices.cpp:144
```
