### ISSUE TITLE
[QGIS Server][WMS] getLegend - Raster layers values not showed in legend

### ISSUE THREAD

**Issue by vprint** [qgis/QGIS#55651]
### What is the bug or the crash?

this URL : http://localhost:8081/cgi-bin/qgis_mapserv.fcgi.exe?/wms&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=image%2Fpng&LAYER=SVF&LAYERS=SVF&WIDTH=100&BOXSPACE=0&TRANSPARENT=true&SYMBOLHEIGHT=25&LAYERTITLE=false&RULELABEL=false give me the following png
![legend_png](https://github.com/qgis/QGIS/assets/42189444/fe89c726-798e-4ddd-8b70-31d79ab5621d).

But if i try te get legend in JSON format like this : http://localhost:8081/cgi-bin/qgis_mapserv.fcgi.exe?/wms&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetLegendGraphic&FORMAT=application%2Fjson&LAYER=SVF&LAYERS=SVF&WIDTH=100&BOXSPACE=0&TRANSPARENT=true&SYMBOLHEIGHT=25&LAYERTITLE=false&RULELABEL=false i got this simple json : {"nodes":[{"symbols":[{"title":" "},{"title":""}],"title":"","type":"layer"}],"title":""}. Min and max values are not showed.

### Steps to reproduce the issue

1) Create qgis project with raster layers
2) Publish qgis project
3) Try a wms getLegend over the raster layer

### Versions

qgis 3.34

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Fixed with https://github.com/qgis/QGIS/pull/56026 but the output is not ideal: that legend is built upon two different items: the first contains just the title of the band and the second contains the color ramp icon and information.

The JSON output is now:
```json
{
   "nodes":[
      {
         "symbols":[
            {
               "title":"Band 1 (Red)"
            },
            {
               "icon":"iVBORw0K...........",
               "max":255,
               "min":1,
               "title":""
            }
         ],
         "title":"bluemarble",
         "type":"layer"
      }
   ],
   "title":""
}
```
