### ISSUE TITLE
Workflow "OGC tests for QGIS Server" is failing since Dez 19, 2023

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#55683]
### What is the bug or the crash?

https://github.com/qgis/QGIS/actions/workflows/ogc.yml

e.g.

![grafik](https://github.com/qgis/QGIS/assets/20856381/5979f8b5-c057-4ad0-bf91-9eef0767ef03)

**Comment by pathmapper** [comment]
Running `pyogctest` on http://qgis4.qgis.org:8080/certification_qgisserver_master (which seems to be not available currently) gives the same error:

``` bash
sudo -E ./pyogctest.py -s wms130 -u http://qgis4.qgis.org:8080/certification_qgisserver_master
============================================== OGC test session starts ===============================================
testsuite: WMS 1.3.0
Traceback (most recent call last):
  File "/home/user/dev/pyogctest/./pyogctest.py", line 182, in <module>
    r.dump_prompt(args.verbose, args.regex)
  File "/home/user/dev/pyogctest/pyogctest/report/report.py", line 23, in dump_prompt
    self.parser.dump_prompt(verbose, regex)
  File "/home/user/dev/pyogctest/pyogctest/report/wms130/wms130.py", line 91, in dump_prompt
    self._parse()
  File "/home/user/dev/pyogctest/pyogctest/report/wms130/wms130.py", line 234, in _parse
    root = ET.fromstring(self.xml)
  File "/usr/lib/python3.10/xml/etree/ElementTree.py", line 1343, in XML
    return parser.close()
xml.etree.ElementTree.ParseError: no element found: line 1, column 0
```

So for the CI failure it looks like the QGIS Server is not available for some reason:
https://github.com/qgis/QGIS/blob/7b41268c9900832dee30338e4400739538dec74d/.github/workflows/ogc.yml#L99

**Comment by pathmapper** [comment]
Seems related to upstream changes with teamengine.

With the latest docker image [ogccite/ets-wms13](https://hub.docker.com/r/ogccite/ets-wms13/tags)

<img src="https://github.com/qgis/QGIS/assets/20856381/4eeb27e2-7654-485b-9d3d-108f61d147ba" width="500" />
<br><br>

which is used by https://github.com/pblottiere/pyogctest/

https://github.com/pblottiere/pyogctest/blob/fd332aef680c0130b841c1a1abeb5eb1627723e9/pyogctest/teamengine.py#L14

the following request returns a 401

https://github.com/pblottiere/pyogctest/blob/fd332aef680c0130b841c1a1abeb5eb1627723e9/pyogctest/teamengine.py#L94


According to the response headers an authentication is required.
```
{'Server': 'Apache-Coyote/1.1', 'WWW-Authenticate': 'Basic realm="Insert credentials"', 'Content-Length': '0', 'Date': 'Sat, 23 Dec 2023 16:27:07 GMT'}
```

---

Authentication is not required for an older docker image like `ogccite/ets-wms13:1.30-teamengine-5.4.1` where the request returns a 200 and the response headers for the same request are:

 ```
{'Server': 'Apache-Coyote/1.1', 'Content-Type': "application/xml; qs=0.5;charset='utf-8'", 'Transfer-Encoding': 'chunked', 'Date': 'Sat, 23 Dec 2023 16:40:20 GMT'}
```

**Comment by pblottiere** [comment]
Hello @pathmapper,

Thanks for creating this issue, I didn't noticed that the OGC tests workflow was failing lastly.

I'm going to take a look.

**Comment by pblottiere** [comment]
> Running pyogctest on http://qgis4.qgis.org:8080/certification_qgisserver_master (which seems to be not available currently) gives the same error:

(BTW, the endpoint on `qgis4` is available only during formal OGC certification process)
