### ISSUE TITLE
PostGIS json/jsonb field not editable in json-view

### ISSUE THREAD

**Issue by jon-m-l** [qgis/QGIS#55682]
### What is the bug or the crash?

Editing a json/jsonb-field in the attribut-table using the json-view is not possible.
Editing the field using the text-widget is possible. (after changing it in the layer properties)

![grafik](https://github.com/qgis/QGIS/assets/61020213/dc2d100a-d09d-48b5-8c0b-087ee4c9898c)

### Steps to reproduce the issue

1. Create PostGIS layer with jsonb column
2. Create an element in the layer
3. Open the attribute table
4. Go to edit mode
5. Try to type something in the jsonb-field (no typing possible)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.34.1-Prizren | QGIS-Codeversion | 133927424d
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.5
GDAL-Version | 3.8.1
PROJ-Version | 9.3.1
EPSG-Registraturdatenbankversion | v10.098 (2023-11-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.41.1
PDAL-Version | 2.6.0
PostgreSQL-Client-Version | unknown
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
changeDataSource | 3.1
deepness | 0.5.4
dzetsaka | 3.70
ImportPhotos | 3.0.5
latlontools | 3.6.15
m150xml | 2.3.9
nominatim_locator_filter | 0.2.4
pg_raster_import | 3.2.0
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
postgis_geoprocessing | 0.9
pp_attribut_updaten | 1.0
pp_tools | 0.1
radolan2map | 1.7
wbt_for_qgis | 1.0.9
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.34.1-Prizren
QGIS-Codeversion
[133927424d](https://github.com/qgis/QGIS/commit/133927424d)
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.8.1
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
changeDataSource
3.1
deepness
0.5.4
dzetsaka
3.70
ImportPhotos
3.0.5
latlontools
3.6.15
m150xml
2.3.9
nominatim_locator_filter
0.2.4
pg_raster_import
3.2.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
postgis_geoprocessing
0.9
pp_attribut_updaten
1.0
pp_tools
0.1
radolan2map
1.7
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Apparently "by design": https://github.com/qgis/QGIS/pull/43164#issuecomment-1443670394  :confused:

**Comment by andreasneumann** [comment]
> Apparently "by design": [#43164 (comment)](https://github.com/qgis/QGIS/pull/43164#issuecomment-1443670394) 😕

Other are welcome to improve on this. But it isn't a "bug", but would be a new "feature". As mentioned, an editing mode would also have to check for validness and refuse invalid JSON content.
