### ISSUE TITLE
Launch multiple startup Python scripts from directory

### ISSUE THREAD

**Issue by posikifi** [qgis/QGIS#55714]
### Feature description

It seems that PlanetFederal/Boundless version of QGIS has feature where you can put multiple startup Python scripts to one directory (and use QGIS_INIT_SCRIPTS_DIRECTORY environment variable to point a specific folder). This will be nice feature when you need to create centrally managed QGIS enviroments.

More information from these web sites:
- StackExchange: https://gis.stackexchange.com/questions/319224/central-deployment-of-startup-py-in-qgis
- PlanetFederal GitHub: https://github.com/planetfederal/desktop-documentation/blob/master/docs/source/system_admins/init_scripts.rst

Ping @SrNetoChan 

### Additional context

If additional funds are need for implementation, please let me know.

**Comment by elpaso** [comment]
Hi, I was the author of that functionality, a similar behavior can now be implemented with  `PYQGIS_STARTUP`

See:
https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/intro.html#running-python-code-when-qgis-starts

**Comment by posikifi** [comment]
Hi!

Yes, I was aware that possibility. But I was just thinking that one (1) directory could be easier to handle. Of course I can create Python-script which will implement this feature.

However, I'm a little bit confused about different ways to run python code in startup. So, I have learn following:

- Python script behind `PYQGIS_STARTUP` will be run before QGIS. So you can't include QGIS Python libraries.
- `startup.py` -file will be launch after QGIS has started up, so you can you use QGIS Python libraries.
- If I have multiple `startup.py` -files in different directories, will all those files launched in startup?
- If I will use `--code` parameter, will this Python script execute before or after `startup.py` -file?

Maybe these are more related to documention. I can create other issue into documentation, if I can get answer on these.

I presume all the answers are in the Code, but I have limited capability to read the Code.

P
