### ISSUE TITLE
Cell Statistics having one Statistics Parameter wrong

### ISSUE THREAD

**Issue by Kickerich** [qgis/QGIS#55732]
### What is the bug or the crash?

The Tool "Cell Statistics"  mentions a couple of Functions that can be used, ranging from Sum to Variance etc. 
As seen in the (albeit german) Screenshot, Variance (Varianz) is mentioned twice in the Drop-Down Menu, even tho "Variety" (Varietät) is mentioned in the Help-Box to the right. 
Both "Variances" do the exact same thing so i guess there is some kind of Programming Error going on.
![ee61ece40d77592bf0f0807263afca1b](https://github.com/qgis/QGIS/assets/141320942/ab86b57a-3cd1-4e7c-9ce1-c07ca8d49642)

### Steps to reproduce the issue

1. Go to the Toolbox
2. Find "Cell Statistics" 
3. Everything is said there like in the Screenshot

### Versions

QGIS-Version
3.34.1-Prizren
QGIS-Codeversion
133927424d
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.8.1
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by root676** [comment]
Could you try to switch to the english user interface translation? I just checked the sourcecode - it should work fine. Maybe there is a translation problem?

**Comment by DelazJ** [comment]
I can confirm that in transifex, "variety" is translated as "varianz" for a number of algorithms. That explains the duplicate display issue. So @Kickerich "varietät" is the correct word to use there?

![image](https://github.com/qgis/QGIS/assets/7983394/2e70e78d-b8cf-4438-988f-13151ea7d74a)

**Comment by root676** [comment]
Maybe we should call it "Wertvielfalt"? @Kickerich what do you think? It is difficult do directly translate 'Variety' into german...

**Comment by Kickerich** [comment]
@root676 , i think "Varietät" might be the smartest Option. As you said, its a difficult Word to properly translate due to its several meanings, but I think the way its mentioned in the Helpbox in my original Screenshot (Varietät: Anzahl eindeutiger Werte) explains it pretty well already.

**Comment by DelazJ** [comment]
>  i think "Varietät" might be the smartest Option.

Done. so would be available at next release.
