### ISSUE TITLE
Label Tolbar functions doesn't works good

### ISSUE THREAD

**Issue by ivandragas88** [qgis/QGIS#55731]
### What is the bug or the crash?

Label Tolbar doesnt work good, because if we have already labeled point numbers and I want to move Point label in project to make better visualisation in layout, he will make that, but after saving and closing project, sometimes he will bring label in position from begining and that means you need to make new Layot from begining.

### Steps to reproduce the issue

1. label tolbar
2. click on move label diagram or collaut
3. save and close file few times
4. he will bring label in first position
![Error 5](https://github.com/qgis/QGIS/assets/155195267/59042346-25e4-4463-9977-84af3170079f)

### Versions

All versions of Qgis

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
> All versions of Qgis

Hi @ivandragas88 This is not the kind of reply expected here. Name the most recent version you have the issue with and copy paste the details from the Help --> About dialog (to show the context of your QGIS version: OS, dependencies versions, ...)
And again, a project file showcasing the situation is more than desirable. Having used that tool in the past, I'm surprised the bug affects all versions, so maybe something is missing in your project or your steps (that you could also describe to help people reproduce exactly)
IOW, the more information you provide to understand how to exactly reproduce your issue (reason why there is a issue template), the more chance you have to get it resolved...

**Comment by DelazJ** [comment]
Forgot to ask: did you select a field with **unique values** to use as primary key when the message box pops up?
