### ISSUE TITLE
Postgres raster: sparse rasters disappear

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#55753]
### What is the bug or the crash?

When adding sparse postgis rasters (rasters that omit some of the blocks/tiles), rasters might disappear when zooming around. Also sparse values are not displayed correctly as no-data values (black area around the recangular raster in GIF below).

![raster_disappears](https://github.com/qgis/QGIS/assets/33314057/b00df414-2a7e-4195-99a9-d96d1dc92af9)

In addition the many similar lines appear in the log:

```
CRITICAL    No tiles available in table "public"."raster_sparse_3035" for the requested extent: 4080050.0000000000000000,2430625.0000000000000000 : 4080326.0000000000000000,2430855.0000000000000000
```

If black the black areas around the actual raster are identified, it returns -9999 (layer's no-data value) but following lines appear in the log:

```
WARNING    NOTICE: row number 0 is out of range 0..-1
WARNING    Cannot convert identified value to float
```

Sparse rasters should be valid as stated in the [early specification](https://trac.osgeo.org/postgis/wiki/WKTRaster/SpecificationWorking01)

> It is permissible to for regular_blocking rasters to omit some blocks/tiles (sparse rasters) in which case the missing tiles should be assumed to be all NODATA or zero valued. 

The same behaviour happens whether the regular_blocking is used or not.

### Steps to reproduce the issue

To reproduce the bug I provided [test_data.zip](https://github.com/qgis/QGIS/files/13819731/test_data.zip)  containing docker-compose.yml and sql file containing lines to add postgres raster with larger extent than the data actually is. Making it thus sparse.

1. Download and extract [test_data.zip](https://github.com/qgis/QGIS/files/13819731/test_data.zip)
2. docker-compose up -d
3. Start QGIS and set project CRS to EPSG:3035
4. Add following PostGIS server connection: `dbname=rasterdb host=localhost port=5455 username=postgres password=postgres`
5. Add `raster_sparse_3035` to the project
6. Zoom deep into layer and remove it
7. Add the layer again
8. Zoom out and see how it disappears like in GIF

### Versions

<details>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.11
Python version | 3.11.6
Compiled against GDAL/OGR | 3.8.0 | Running against GDAL/OGR | 3.8.2
Compiled against PROJ | 9.3.0 | Running against PROJ | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.44.2
Compiled against PDAL | 2.6.1 | Running against PDAL | 2.6.2
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | EndeavourOS
  |   |   |  
Active Python plugins
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.34.1-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.11
Python version
3.11.6
Compiled against GDAL/OGR
3.8.0
Running against GDAL/OGR
3.8.2
Compiled against PROJ
9.3.0
Running against PROJ
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.44.2
Compiled against PDAL
2.6.1
Running against PDAL
2.6.2
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
EndeavourOS

Active Python plugins
db_manager
0.1.20
processing
2.12.99
grassprovider
2.12.99

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I debugged the code a bit and noticed that this might be the workflow how the happens:

1. First `mLoadedIndexBounds` is initialized normally https://github.com/qgis/QGIS/blob/6880909ee7f7da686ed699fffb2fff3d03365001/src/providers/postgres/raster/qgspostgresrastershareddata.cpp#L59
2. This condition is not necessarily met: https://github.com/qgis/QGIS/blob/6880909ee7f7da686ed699fffb2fff3d03365001/src/providers/postgres/raster/qgspostgresrastershareddata.cpp#L63 and code continues to method `fetchTilesIndex` but since `mTiles` already got all the tiles, it leaves `overallExtent` to null geometry and invalidates the `mLoadedIndexBounds` cache in line https://github.com/qgis/QGIS/blob/6880909ee7f7da686ed699fffb2fff3d03365001/src/providers/postgres/raster/qgspostgresrastershareddata.cpp#L305
3. Next time tile is searched via method `fetchTilesIndexAndData` but again since `mTiles` already contains all the tiles, `response` is left empty

**Comment by Joonalai** [comment]
@elpaso what do you think, could support for sparse raster be added as a fix for this?

**Comment by elpaso** [comment]
> @elpaso what do you think, could support for sparse raster be added as a fix for this?

Yes, absolutely. I can help with reviewing the code if you need.

**Comment by Joonalai** [comment]
@elpaso, I created a PR to solve the disappearing issue. It also allows identify to work without `Cannot convert identified value to float` warning. After some investigation, I thought that showing the omitted values properly as invisible no-data values may be more difficult than I expected. Maybe I could make another issue for that to be done later? For our project, fixing disappearing is more urgent right now.
