### ISSUE TITLE
[ci] Workflow MSYS2 MinGW-w64 Windows 64bit Build is failing constantly

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#55761]
### What is the bug or the crash?

https://github.com/qgis/QGIS/actions/workflows/mingw-w64-msys2.yml

`AutoMoc: D:/a/QGIS/QGIS/src/gui/inputcontroller/qgs2dgamepadcontroller.h:0: Note: No relevant classes found. No output generated.`

![image](https://github.com/qgis/QGIS/assets/20856381/b637507d-cf79-4b82-9c2e-5044e99ef7bf)

**Comment by nyalldawson** [comment]
@pathmapper 

That's just a warning. The actual error is :

```
2024-01-04T22:05:24.4205310Z [7796/11090] Running crssync
2024-01-04T22:05:24.4982136Z FAILED: src/crssync/CMakeFiles/synccrsdb D:/a/QGIS/QGIS/build/src/crssync/CMakeFiles/synccrsdb 
2024-01-04T22:05:24.5105241Z C:\Windows\system32\cmd.exe /C "cd /D D:\a\QGIS\QGIS\build\src\crssync && D:\a\QGIS\QGIS\build\output\.\crssync"
```

**Comment by nyalldawson** [comment]
(in other words, absolutely nothing of any troubleshooting value to work with :disappointed: )

**Comment by pathmapper** [comment]
Additionally to https://github.com/qgis/QGIS/commit/dfd2686866707fd95160164ad5b1433d5b18098a it could be that the worflow must be removed as required in the repo settings / branch protection rules to fix this for existing PRs.

**Comment by MehdiChinoune** [comment]
There was an unnoticed issue with gdal, We missed to rebuild it after a change on libaec https://github.com/msys2/MINGW-packages/commit/c3c322ae5f39860aa124fcfe93b8d9411287bc2e.
It should buils now after https://github.com/msys2/MINGW-packages/commit/064caefbb45791539861da3e9cc788a700fce8d9.

**Comment by pathmapper** [comment]
Workflow is active again -> https://github.com/qgis/QGIS/pull/55837
