### ISSUE TITLE
Installation on Debian Bullseye (in Docker) fails due to package issue

### ISSUE THREAD

**Issue by tiagojsag** [qgis/QGIS#55760]
### What is the bug or the crash?

I am running QGIS server using Docker, using [the official docs](https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html). My Dockerfile is exactly as the one in the link. Two weeks ago the docker image was building just fine (we do it in Github Actions), today it no longer builds. 

In an attempt to debug this, I broke down the problematic large RUN chain of commands into smaller pieces, and tried to build the docker image locally. The output of the build process is as follows:

`
 > [ 3/11] RUN apt-get install --no-install-recommends --no-install-suggests --allow-unauthenticated -y         qgis-server         spawn-fcgi         xauth         xvfb:                                                                                                                                          
0.276 Reading package lists...                                                                                                                            
0.518 Building dependency tree...                                                                                                                         
0.566 Reading state information...
0.598 Some packages could not be installed. This may mean that you have
0.598 requested an impossible situation or if you are using the unstable
0.598 distribution that some required packages have not yet been created
0.598 or been moved out of Incoming.
0.598 The following information may help to resolve the situation:
0.598 
0.598 The following packages have unmet dependencies:
0.627  python3-qgis : Depends: python3-qgis-common (= 1:3.34.1+16bullseye) but it is not going to be installed
0.627  qgis-providers : Depends: qgis-providers-common (= 1:3.34.1+16bullseye) but 1:3.34.2+16bullseye is to be installed
0.633 E: Unable to correct problems, you have held broken packages.
`

This is the same output I am getting on GH Actions, which uses a different linux distro than mine (Ubuntu 22.04 on GH vs Arch locally) so host-related causes seem pretty unlikely. I also tried to use a previous version of the base image, based on logs I had of past successful runs - that did not fix the issue either.

### Steps to reproduce the issue

1. Copy the Dockerfile from https://docs.qgis.org/3.28/en/docs/server_manual/containerized_deployment.html#simple-docker-images to your local machine
2. run "docker build ."
3. fireworks!!! (the bad kind)

### Versions

While I have no way to confirm this, I believe I am running the latest version of QGIS and its packages, as available at https://qgis.org/debian for bullseye

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Apologies in advance if this is not the correct place to report this issue - if that's the case, please point me in the right direction so I can report it where I should. TIA

**Comment by tiagojsag** [comment]
Upon further digging, I found the "note" at https://qgis.org/en/site/forusers/alldownloads.html#repositories which I suspect may be related. I tested switching to the nightly build for bullseye, and that solved the issue. I have also tested and migrated to Debian bookworm (stable) which also works. If the issue explained in the "note" I linked above is the explanation for that issue, I think this caveat should be made clearer somewhere. I am happy to submit a docs update PR, just point me in the right direction

**Comment by maxfreu** [comment]
Thanks, nightly works. I guess 3.34.1+16bullseye just has broken dependencies and we have to wait for the next release to overcome this. In the meantime the broken package should be purged from the repo...

**Comment by jef-n** [comment]
1:3.34.2+16bullseye-1

**Comment by tmuguet** [comment]
Hi,

The issue seems to have reappeared on the debian-ltr bullseye repo:

> The following packages have unmet dependencies:
>  python3-qgis : Depends: python3-qgis-common (= 1:3.34.11+16bullseye) but it is not going to be installed
>  qgis-providers : Depends: qgis-providers-common (= 1:3.34.11+16bullseye) but 1:3.34.12+16bullseye is to be installed
> E: Unable to correct problems, you have held broken packages.

I can confirm switching to debian-nightly-ltr or upgrading to bookworm works.
