### ISSUE TITLE
[ci] Tests failing for master since Nov 1, 2023

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#55776]
### What is the bug or the crash?

https://github.com/qgis/QGIS/actions/workflows/run-tests.yml?query=branch%3Amaster+event%3Apush

Looks like this is the culprit https://github.com/qgis/QGIS/pull/55113/commits/6ffb7efdbf7684d303cf03903a18066aea421e1a.

Seems like something has changed regarding the upload to the registry, there is an auth error in the logs:  

```
#30 exporting cache to registry
#30 preparing build cache for export 0.9s done
#30 writing layer sha256:02ce4b7fda659a45bf496603edf018d56c9a7e19058a1434ee56bb7bc7f6de7e 0.8s done
#30 ERROR: error writing layer blob: unexpected status from POST request to https://ghcr.io/v2/elpaso/qgis3-build-deps-22.04-stages/blobs/uploads/: 403 Forbidden
```
Also it tries to upload to the registry of the person who has merged the PR (not sure if it's correct):

e.g.
https://github.com/qgis/QGIS/actions/runs/7439559374/job/20239606388#step:7:18316
https://github.com/qgis/QGIS/actions/runs/7340315128/job/19986138142#step:7:23817

**Comment by nyalldawson** [comment]
Yeah, this is weird -- it seems it's now using the committer's username in the ghcr url, instead of QGIS' username.

**Comment by pathmapper** [comment]
Tests on `master` are passing, thanks @3nids.
