### ISSUE TITLE
Crash ID: 62c06df51ba84c32376002e25009cb4640285a25

### ISSUE THREAD

**Issue by plennert** [qgis/QGIS#55771]
## User Feedback

Hi
QGIS crashed.

## Report Details

**Crash ID**: [62c06df51ba84c32376002e25009cb4640285a25](https://github.com/qgis/QGIS/search?q=62c06df51ba84c32376002e25009cb4640285a25&type=Issues)

**Stack Trace**

```

QNetworkAccessManager::cookieJar :
QgsNetworkAccessManager::setupDefaultProxyAndCache :
QgsNetworkAccessManager::instance :
QgsNetworkContentFetcher::fetchContent :
QgsNetworkContentFetcherTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.14-Firenze
QGIS code revision: b09131c512
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.2
Running against GDAL: 3.8.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

by startingqgis

### Versions

3,28,14-Firenze LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@plennert , we'll need a lot more information than this to dissect this crash. A description of what you were attempting to do when QGIS crashed as well as steps to replicate the crash would be a good start :)
