### ISSUE TITLE
QGIS crashes when importing netCDF4

### ISSUE THREAD

**Issue by coderodyhpc** [qgis/QGIS#55787]
### What is the bug or the crash?

QGIS crashes with a segmentation fault when importing netCDF4 from the python console (also when imported from a script). 
 
![QGIS_crash](https://github.com/qgis/QGIS/assets/79646720/36786a39-1914-4c6e-b481-e5ce3ad1babe)

### Steps to reproduce the issue

Open QGIS v3.34 and go to python console. Type:
`import netCDF4 as nc`  

### Versions
QGIS version 3.34.0-Prizren
QGIS code branch Release 3.34
Qt version 5.15.3
Python version 3.10.12
GDAL/OGR version 3.4.1
PROJ version 8.2.1
EPSG Registry database version v10.041 (2021-12-03)
GEOS version 3.10.2-CAPI-1.16.0
SQLite version 3.37.2
PDAL version 2.3.0
PostgreSQL client version 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version 5.0.1
QWT version 6.1.4
QScintilla2 version 2.11.6
OS version Ubuntu 22.04.3 LTS
Active Python plugins
MetaSearch 0.3.6
grassprovider 2.12.99
processing 2.12.99
db_manager 0.1.20
_This was not an issue with v3.30_ (have not tested v3.32).

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@coderodyhpc, thanks for reporting. Please provide the full version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."). I think it would be useful to also describe how did you install QGIS and the the netCDF4 Python module.

**Comment by rouault** [comment]
> Not really sure what you mean by how I installed QGIS as I unpacked qgis-3.34.0.tar.bz2, used `ccmake` to configure and `make` to build.
> 
> I installed netCDF4 via pip ($ python3 -m pip install netCDF4). The same command provides version info:

This likely install a native libnetcdf library used by the netCDF4 package which is incompatible of the system libnetcdf library.  Do "pip uninstall netCDF4", and do "apt-get install python3-netcdf4" instead
