### ISSUE TITLE
Ability to change polygon start/end point so that previous start/end can be converted to a curve with Shift+O

### ISSUE THREAD

**Issue by AlisterH** [qgis/QGIS#55791]
### Feature description
What the title says.

Current behaviour:
- Create a CurvePolygon layer
- Digitize a polygon
- You can toggle a vertex to a curve and vice versa by selecting it with the vertex tool and pressing `Shift+O`, if it isn't the endpoint of a curve, in which case you get this:
![image](https://github.com/qgis/QGIS/assets/714600/989b9174-1bb6-4879-8426-4eed3ab71d61)
- But if you try to toggle the start/end point of the polygon (or ring), you get this:
![image](https://github.com/qgis/QGIS/assets/714600/3e647efb-7851-433f-ad47-ba51b3bfb7eb)
This is not user-friendly.
In many situations the user is unlikely to know that they have selected the start/end point, so the error message doesn't necessarily make any sense to them, because from their perspective they have only selected one vertex.  Assuming they do know what it means, what can they do about it, other than tracing the polygon as an entirely new feature?
Perhaps ideally `Shift+O` would automatically recreate the polygon with the start and end points at a different vertex, so that it can convert this vertex into a curve.  Or it could give a more informative message, and the user could use a "reorder vertices" tool to change the start and end points of the polygon (but I don't think such a tool currently exists). 

Also note that one of those messages is a warning and the other is "info".  This seems strange - wouldn't it make sense for them both to be the same?

**Comment by AlisterH** [comment]
> Also note that one of those messages is a warning and the other is "info". This seems strange - wouldn't it make sense for them both to be the same?

Relevant code is in src/app/vertextool/qgsvertextool.cpp if anyone wants to get there in a hurry:
````
  {
    // TODO support more than just 1 vertex
    QgisApp::instance()->messageBar()->pushMessage(
      tr( "Could not convert vertex" ),
      tr( "Conversion can only be done on exactly one vertex." ),
      Qgis::Info );
    return;
  }
````

**Comment by DelazJ** [comment]
see also #53817?

**Comment by AlisterH** [comment]
Yes, essentially this is a duplicate - I couldn't find your ticket so obviously didn't search hard enough.

Note that I suggested an alternative to adding a lot of magic to make this feature work might be to provide a more informative error message and a separate tool to change a polygon start/end vertex.
Also, the title of your ticket might be better simplified to "Make it possible to turn start/end point of a polygon into a curve".

**Comment by AlisterH** [comment]
Duplicate of #53817
