### ISSUE TITLE
csv file export of decimal data in quotation marks after forced string quoting

### ISSUE THREAD

**Issue by GISreceiver** [qgis/QGIS#55808]
### What is the bug or the crash?

Since some minor update around 2 months ago, I have not been able to export a GeoPackage layer as a csv file  anymore without decimal data (real) also getting written in quotation marks. This is now happening in QGIS versions 3.28.14 and 3.34.2, but not in version 3.10.14.

### Steps to reproduce the issue

1. Export GeoPackage layer with right click on layer, and click on "Save Feature as...."
2. Select Format "Comma Separated Value [CSV]", name, and folder
3. Scroll down to "Layer Options" and select "ALWAYS" as parameter for "STRING_QUOTING"
4. See created csv file for decimal datatyp written in quotation marks 

**Layer Properties - Data types of sample data**
![image](https://github.com/qgis/QGIS/assets/128184570/7c50edfc-bdc9-41f1-bb8f-3481860c4f71)

**Screenshot of exported csv file**
![image](https://github.com/qgis/QGIS/assets/128184570/bf8d9ec8-6759-4c50-88b2-01b852495b95)

**Sample data**
[Bug reporting.zip](https://github.com/qgis/QGIS/files/13884795/Bug.reporting.zip)

### Versions

QGIS version
3.28.14-Firenze
QGIS code revision
b09131c512
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.2
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The issue doesn't occur on Windows using QGIS 3.28.8 with GDAL/OGR 3.7.1.
@rouault, it seems to me the issue may be due to a change in the GDAL/OGR library.

**Comment by rouault** [comment]
yes, this is indeed a 3.8.1 regression. Cf https://github.com/OSGeo/gdal/pull/9048
Using STRING_QUOTING=IF_AMBIGUOUS is the best workaround I can propose with the faulty versions
