### ISSUE TITLE
Set baudrate for serial port sensors

### ISSUE THREAD

**Issue by jtornero** [qgis/QGIS#55820]
### The problem:
With QGIS 3.34 is not possible to set the baudrate for a serial port sensors.

It looks like at

https://github.com/qgis/QGIS/blob/aa47316116567071c40bc994768be2e0775bbfef/src/core/sensor/qgsiodevicesensor.cpp#L356-L369

baudrate is fixed at 9600 baud.

### The feature request:
Being able to set the baudrate of the sensor would make possible connecting many sensors currently out of scope. For instance, any NMEA0182/0183 (not only GPS devices) connect at 4800 baud, while other sensors could transmit data way faster than 9600.

### My approach/help wanted:

I'll try to tackle this myself (Although I DO REALLY FEAR all the subsequent, PR, git, etc) an probably will need some directions. 

At first I think it is enough to add getter/setter for baudrate like this:

```
int QgsSerialPortSensor::baudrate() const
{
  return mBaudrate;
}

void QgsSerialPortSensor::setPortName(int &baudrate)
{
  if ( mBaudrate == baudrate )
    return;

  mBaudrate = baudrate;
}

void QgsSerialPortSensor::handleConnect()
{
  mSerialPort->setPortName( mPortName );
  mSerialPort->setBaudRate( mBaudrate );
  if ( mSerialPort->open( QIODevice::ReadOnly ) )
  {
    setStatus( Qgis::DeviceConnectionStatus::Connected );
  }
  else
  {
    setStatus( Qgis::DeviceConnectionStatus::Disconnected );
  }
}
```

With this I guess it could be enough to being able to setup the speed programatically (for instance, for a standalone application o r a plugin).

To make it really useful, I guess the next steps should be:

- Modify `src/ui/sensor/widget_serialportsensor.ui` by adding a combobox (`mBaudrate`) for the usual baudrate values (4800, 9600, 19200, etc). It could default to 9600 anyway.

- Modify `src/gui/sensor/qgssensorwidget.cpp` for creation/updating the sensor properly:

```
QgsAbstractSensor *QgsSerialPortSensorWidget::createSensor()
{
  QgsSerialPortSensor *s = new QgsSerialPortSensor();
  s->setPortName( mSerialPortComboBox->currentData().toString() );
  s->setBaudrate mBaudrateComboBox->currentData().toInt() );
  return s;
}

bool QgsSerialPortSensorWidget::updateSensor( QgsAbstractSensor *sensor )
{
  QgsSerialPortSensor *s = dynamic_cast<QgsSerialPortSensor *>( sensor );
  if ( !s )
    return false;

  s->setPortName( mSerialPortComboBox->currentData().toString() );
  s->setBaudrate mBaudrateComboBox->currentData().toInt() );

  return true;
}
```

Just let me know it the approach to solve the problem is correct and I'll try to make a PR, etc to improve the feature.

Tanks a lot

**Comment by nirvn** [comment]
@jtornero , you're definitively on the right track. I'd be more than happy to offer guidance and review once you open a PR :)

**Comment by jtornero** [comment]
@nirvn Thanks a lot. I'm trying to testing the changes but I'm having some issues with teh compilation. I'll come back as soon as I have tested the thing. Then I'll try do my bests with the [pull request guide](https://docs.qgis.org/testing/en/docs/developers_guide/git.html#pull-requests).

Thanks a lot.

**Comment by jtornero** [comment]
@nirvn  I've sent the PR , you can check it here:

https://github.com/qgis/QGIS/pull/55848

I hope I think i've followed the PR guides and stuff well and no help with GIT would be neccessary.

By the way, it looks like at lower speeds (4800, 9600 and 19200 at least) the data is not received at once or it is split arbitrarily, so for instance the data stored at sensor.data().lastValue is not a whole sentence but chunks of it (it doesn't happen with UPD/TCP connections). Not sure how to fill an issue for this, maybe describing it with a screencast?

Cheers!

**Comment by lbartoletti** [comment]
Congrats @jtornero !
