### ISSUE TITLE
Problems running GRASS in QGIS

### ISSUE THREAD

**Issue by Raul-Santiago** [qgis/QGIS#55828]
### What is the bug or the crash?

I belong to a work team of four people, and all four of us have problems running GRASS in QGIS.
The version we have of QGIS is 3.28.2.
We have tried installing previous versions. Specifically, we have installed 3.18.3. We have tried installing it on personal computers, to see if it was a problem on the corporate computer, and it hasn't worked either.

### Steps to reproduce the issue

We open any GRASS tool in QGIS through the Toolbox. For example r.fill.dir applied to a digital terrain model.
When running this, or any other tool, whether for raster or vector, it gives us the same error command:

Loading the resulting layers
The following layers were not generated correctly.
• C:/Users/RaúlSantiagoMartín/AppData/Local/Temp/processing_IONDnR/0f5bd278cc5c42bb843f3949180eb94d/areas.tif
• C:/Users/RaúlSantiagoMartín/AppData/Local/Temp/processing_IONDnR/424a1a9d244446429d8d399e4c46e254/output.tif
• C:/Users/RaúlSantiagoMartín/AppData/Local/Temp/processing_IONDnR/e6fb9f806a324707980fe5e87d2b46ae/direction.tif
You can check the “Log Message Panel” in the main QGIS window to find more information about the algorithm execution.

![Captura de pantalla 2024-01-12 123251](https://github.com/qgis/QGIS/assets/156426920/4a3e4514-910e-4c90-865b-15bd60c891e8)
![Captura de pantalla 2024-01-12 123319](https://github.com/qgis/QGIS/assets/156426920/bf67be60-1757-4117-b9ce-775f80cdbd97)

### Versions

Same error in versions 3.18.3. and 3.28.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Raul-Santiago, thanks for reporting.
Please actually try using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) as requestesd in the issue report form.
Please also provide the full QGIS version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") and the full text of the processing log.
It would be useful if you provide the input layer and all the algorithm parameters set.

**Comment by samuelaojih** [comment]
Process completed successfully
Results: {'OUTPUT': 'C:/Users/User/AppData/Local/Temp/processing_XNsxLJ/17c28be8eac54147abb7df976f770c51/OUTPUT.tif'}
Error: Algorithm grass7:r.fill.dir not found

Error: Algorithm grass7:r.fill.dir not found

Execution failed after 1.15 seconds

Loading resulting layers
Algorithm 'Stream Network with Order' finished

**Comment by agiudiceandrea** [comment]
@samuelaojih QGIS doesn't have natively an algorithm called "Stream Network with Order". You you are using a processing plugin you need to report the issue to the author of such plugin.
