### ISSUE TITLE
bug on reading with R-QGIS a filtered vector layer

### ISSUE THREAD

**Issue by fpirotti** [qgis/QGIS#55830]
### What is the bug or the crash?

When creating an R script in QGIS with a vector input layer, the column names of the vector are getting **truncated to 10 characters**. This happens only when such vector layer is filtered with a query in the feature filter. This leads to further processing that requires to select columns impossible.

### Steps to reproduce the issue

1. create R script with the following
```
##My scripts=group 
##Layer=vector   
print(names(Layer))
```
2. add a vector layer with long (>10 characters) column names
3. go to properties of the vector layer and build a dummy query on the feature filter
4. try to run the r script 

### Versions

3.32, 3.24

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@fpirotti, thanks for reporting. QGIS 3.32 and QGIS 3.24 are no longer supported. Are you using the "Processing R Provider" https://plugins.qgis.org/plugins/processing_r/ external plugin or any other external plugin? If yes, please file the issue report following the "Browse and report bugs" link in the plugin page.

**Comment by fpirotti** [comment]
Yes, thanks  I just did that - below the link for future reference
[https://github.com/north-road/qgis-processing-r/issues/130](https://github.com/north-road/qgis-processing-r/issues/130)
