### ISSUE TITLE
No tooltip text

### ISSUE THREAD

**Issue by Colins2** [qgis/QGIS#55845]
### What is the bug or the crash?

This is the first time I have used QGIS since the last update. Someone else must have noticed this behaviour but I couldn't find anything in the list.
I just open QGIS and it all appears as normal but if I hover over any of the tool icons there is no text. A small window appears but is blank. While looking to see if there was a setting related to tool tips I checked the Settings | Interface Customization menu item and that is frozen. The window opens and various checkboxes are ticked but the window is inactive. I can neither scroll down nor check/uncheck any of the items. I wonder if these 2 things are related?

### Steps to reproduce the issue

Steps are above.

### Versions

QGIS version | 3.34.2-Prizren | QGIS code revision | 7d199797fcc
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.2
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Colins2, thanks for reporting. What is the previous version with which the issue didn't occur on your Linux Mint system?
The issue doesn't occur using QGIS 3.34.2 (OSGeo4W) on my Windows 10 system.

**Comment by Colins2** [comment]
I can't be too sure as I haven't used QGIS for  a few months but it was
definitely OK in Firenze.
I haven't actively sought to upgrade but QGIS updates appear in the
software manager when they are released and I just upgrade from there.
From the roadmap it seems that 3.34.3 will be out in a few days, maybe it
will be fixed in that release.

The Settings | Interface Customization does work OK, I had overlooked the
enable box at the top but I couldn't find anything in there regarding the
tooltips.

**Comment by Colins2** [comment]
I have just upgraded to 3.34.3, again, done through the software manager, not something I have done directly myself.
The issues mentioned are still there but slightly changed.
The empty tooltip boxes seem to be bigger than they were. Maybe the tooltip text has been expanded and the box is automatically bigger?
Also, something I didn't notice before: If I go to the Settings | Interface Customization menu and open the dialog, the icons in there also exhibit the same behaviour - blank boxes.

**Comment by agiudiceandrea** [comment]
@Colins2, thanks for updating the issue info.
It looks like to me the issue occurring on your system may be the same of the one already reported at https://github.com/qgis/QGIS/issues/53143. In that case, which depends on the Qt system theme, the the tooltips are not blank but the text inside the tooltip is almost completely not visible.
I suggest you to try to change the chosen and Qt system "Style" and/or "UI theme" used by QGIS in Settings > Options > General > Application, and restart QGIS.

**Comment by agiudiceandrea** [comment]
@Colins2, thanks for updating the issue info.
It looks like the issue occurring on your system may be the same of the one already reported at https://github.com/qgis/QGIS/issues/53143. In that case, which depends on the Qt system theme, the tooltips are not blank but the text inside the tooltip is almost completely not visible.
I suggest you to try to change the chosen Qt system "Style" and/or "UI theme" used by QGIS in Settings > Options > General > Application, and restart QGIS.

**Comment by Colins2** [comment]
@agiudiceandrea 
Thanks Andrea, the solution in that post worked fine for me.
