### ISSUE TITLE
Incorrect method description of QgsGeometryUtils.segmentSide

### ISSUE THREAD

**Issue by SGroe** [qgis/QGIS#55853]
### What is the bug or the crash?

https://qgis.org/pyqgis/3.34/core/QgsGeometryUtils.html#qgis.core.QgsGeometryUtils.segmentSide

says:

> For line defined by points pt1 and pt3, find out on which side of the line is point pt3. Returns -1 if pt3 on the left side, 1 if pt3 is on the right side or 0 if pt3 lies on the line.

pt2 is not mentioned in this description! Is pt2 the end point of the line or left/right of the line?

### Steps to reproduce the issue

Read method description

### Versions

3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lbartoletti** [comment]
@SGroe Has been fixed in https://github.com/qgis/QGIS/pull/55366

**Comment by agiudiceandrea** [comment]
@lbartoletti, it looks like the fix has not been backported to 3.34.
