### ISSUE TITLE
QGIS "Check Validity" processing tool cannot handle JSON fields from PostGIS

### ISSUE THREAD

**Issue by CoryAlbrecht** [qgis/QGIS#55863]
### What is the bug or the crash?

When trying to check feature geometries for problems, the QGIS algorithm cannot handle JSON fields from PostGIS.

```
QGIS version: 3.34.2-Prizren
QGIS code revision: 6e5e95821b1
Qt version: 5.15.3
Python version: 3.10.12
GDAL version: 3.4.1
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 8.2.1, January 1st, 2022
PDAL version: 2.3.0 (git-version: Release)
Algorithm started at: 2024-01-16T14:37:05
Algorithm 'Check validity' starting…
Input parameters:
{ 'ERROR_OUTPUT' : 'TEMPORARY_OUTPUT', 'IGNORE_RING_SELF_INTERSECTION' : False, 'INPUT_LAYER' : QgsProcessingFeatureSourceDefinition('dbname=\'Alternate History\' host=pg1.db.cory.albrecht.name port=5432 sslmode=require authcfg=c866l6b key=\'id\' estimatedmetadata=true srid=4326 type=MultiPolygon checkPrimaryKeyUnicity=\'1\' table="bop"."timeline_level_0" (geom)', selectedFeaturesOnly=True, featureLimit=-1, geometryCheck=QgsFeatureRequest.GeometryAbortOnInvalid), 'INVALID_OUTPUT' : 'TEMPORARY_OUTPUT', 'METHOD' : 1, 'VALID_OUTPUT' : 'TEMPORARY_OUTPUT' }

Feature could not be written to Invalid_output_decad4d0_7ef6_450f_82d2_c0a19d2f856c: Could not store attribute "predecessors": Could not convert value "" to target type "map"
Feature could not be written to Valid_output_bc447575_ddcd_4ee2_86dc_f83ee613c81c: Could not store attribute "predecessors": Could not convert value "" to target type "map"
Feature could not be written to Valid_output_bc447575_ddcd_4ee2_86dc_f83ee613c81c: Could not store attribute "predecessors": Could not convert value "" to target type "map"
Feature could not be written to Valid_output_bc447575_ddcd_4ee2_86dc_f83ee613c81c: Could not store attribute "predecessors": Could not convert value "" to target type "map"
Execution completed in 0.03 seconds
Results:
{'ERROR_COUNT': 1,
'ERROR_OUTPUT': 'Error_output_ac79e393_d8d8_4bd4_bee7_d0126c5b0330',
'INVALID_COUNT': 1,
'INVALID_OUTPUT': 'Invalid_output_decad4d0_7ef6_450f_82d2_c0a19d2f856c',
'VALID_COUNT': 3,
'VALID_OUTPUT': 'Valid_output_bc447575_ddcd_4ee2_86dc_f83ee613c81c'}

Loading resulting layers
Algorithm 'Check validity' finished
```

### Steps to reproduce the issue

1. Create a PostGIS layer with JSON fields.
2. Open up QGIS and load that layer.
3. Create a few features, the JSON fields can be empty (NULL) or have JSON in them. (My usage case is an array of integers.)
4. Try to run the "Check Validity" processing tool and it will not work.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.2-Prizren | QGIS code revision | 6e5e95821b1
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
quick_map_services | 0.19.34
buffer_without_overlaps | 0.2
splitmultipart | 1.0.0
debug_vs | 0.8
IPyConsole | version 2.0
naficp | 1.0
db-style-manager | 0.8
GroupStats | 2.2.7
QuickOSM | 2.2.3
otbprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.2-Prizren
QGIS code revision
[6e5e95821b1](https://github.com/qgis/QGIS/commit/6e5e95821b1)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
quick_map_services
0.19.34
buffer_without_overlaps
0.2
splitmultipart
1.0.0
debug_vs
0.8
IPyConsole
version 2.0
naficp
1.0
db-style-manager
0.8
GroupStats
2.2.7
QuickOSM
2.2.3
otbprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@CoryAlbrecht , could you share a screenshot of your vector layer's fields panel, i.e.:

![Screenshot from 2024-01-24 10-51-55](https://github.com/qgis/QGIS/assets/1728657/c11c5627-76fe-4f1f-a9b6-654f0cb94f21)

I've not been able to replicate this issue using a postgres table I created in QGIS with field type json.

**Comment by gacarrillor** [comment]
The issue seems to be more generic.

I'm reopening this because when adding a value like `[1, 2, 3]` to the json field in the PostGIS layer, and leaving the output as temporary (i.e., using the memory provider), the issue can be replicated. This is the message I get:

```
Feature could not be written to Valid_output_a2ab42c6_0145_4453_b2e5_6f11af13cfba: Could not store attribute "json_values": Could not convert value "" to target type "map"
Could not write feature into VALID_OUTPUT
Execution failed after 0.55 seconds
```

Note: saving the output to a GPKG works with no errors. The OGR provider can convert the JSON value without problem, whereas the memory provider doesn't seem to handle JSONs, but maps, and attempting to save an array/list of integers to a map produces the error.

One could think of storing that value as a list of integers, well supported by the memory provider, but then all features should come as lists of integers, which won't be necessarily the case. Moreover, one can store values like `[1, 2, "foo", null]` in PostgreSQL, which would not be possible to map to the memory provider (unless converting everything to string or something like that).

I guess the real solution for this issue is to add a JSON data type to the memory provider.
