### ISSUE TITLE
sql query yields wrong data in virtual table

### ISSUE THREAD

**Issue by celmi** [qgis/QGIS#55879]
### What is the bug or the crash?

I have an SQL query, that yields a correct result in the database editor, but as soon as I load the results/query to a virtual table, the data is wrong.

### Steps to reproduce the issue

My data contains datapoints of animal observations. Each datapoint has a year (year of observation). The query summarizes observations per animalspecies and observation-point. The observation years are concatenated minimum year and maximum year (if several distinct years available). 

I'm using this query in the SQL-Code:

```
		CASE 
			WHEN (min(year)=max(year)) THEN min(year)
			ELSE min(year)||'–'||max(year) 
		END as years
```

This works as expected in the DB-Manager.  The result is:

```
species |  number_of_observations | years
-------------------
Leopard | 2 | 2018-2024
Lion | 1 | 2023
```

However, if I save the results to a virtual layer, the layer will look like this:

```
species |  number_of_observations | years
-------------------
Leopard | 2 | 2018
Lion | 1 | 2023

```

QGIS somehow does not correctly interpret the SQL statement or drops the second part of the result ("-2024")

### Versions

QGIS 3.28.14

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
@celmi It would be easier to investigate if you provide a minimal project (with the source layer) reproducing the issue

**Comment by celmi** [comment]
I've recreated a very simple file to show the but and guess what.... it worked just fine. Can't reproduce this error except in that other project file. I can't share that one, data is a bit sensitive. But even if – it's most likely just an oddity and not worth investigating. So sorry (especially for my own time reporting ;-).
