### ISSUE TITLE
Two geometry columns not supported since 3.28

### ISSUE THREAD

**Issue by sylviaobk** [qgis/QGIS#55871]
### What is the bug or the crash?

QGIS 3.22 could handle 2 columns of geometry. Since QGIS 3.28 this is not possible anymore. 
This is necessary to use another geometrytype for the same object. point for the center and polygon for the area.

### Steps to reproduce the issue

To see how it should work open QGIS 3.22
1. Add Postgis Layer flaeche.sql
2. Right mouseclick on layer and export - objects save as Geopackage.
3. You see the field with type geometry
![322_export_menu](https://github.com/qgis/QGIS/assets/20552367/1b3ecb5a-f386-45cd-b4df-9f9fec2595cd)
Export successfull

Now do the same steps in QGIS 3.28
5. Add Postgis Layer flaeche.sql
6. Right mouseclick on layer and export - objects save as Geopackage.
![328_export_menu](https://github.com/qgis/QGIS/assets/20552367/7f64b87c-2ce5-4d5e-ac60-648e031135e3)

error: Not supported type for field wkb_geometry_center
![328_export_menu_Fehlermeldung](https://github.com/qgis/QGIS/assets/20552367/631c202c-9335-47ca-94d0-2eb6ff4ad078)

[flaeche_sql.txt](https://github.com/qgis/QGIS/files/13961167/flaeche_sql.txt)

### Versions

QGIS-Version
3.22.11-Białowieża
QGIS-Codeversion
106d33d7
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.5.1
PROJ-Version
9.1.0
EPSG-Registraturdatenbankversion
v10.074 (2022-08-01)
GEOS-Version
3.10.3-CAPI-1.16.1
SQLite-Version
3.38.1
PDAL-Version
2.4.3
PostgreSQL-Client-Version
14.3
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
attributeBasedClustering
2.2.1
bkggeocoder
1.3.3
drucker
3.1.0
geometry_paster
0.4
OSMDownloader
1.0.3
pluginbuilder3
3.2.1
postgis_geoprocessing
0.9
punkte_setzen
1.0
qdraw
3.0.2
spatial_filter
1.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.5
processing
2.12.99
sagaprovider
2.12.99
----------------------------------------------------

QGIS-Version
3.28.4-Firenze
QGIS-Codeversion
fd0fb72ab3
Qt-Version
5.15.3
Python-Version
3.9.5
GDAL-Version
3.6.2
PROJ-Version
9.1.1
EPSG-Registraturdatenbankversion
v10.076 (2022-08-31)
GEOS-Version
3.11.1-CAPI-1.17.1
SQLite-Version
3.39.4
PDAL-Version
2.4.3
PostgreSQL-Client-Version
unknown
SpatiaLite-Version
5.0.1
QWT-Version
6.1.6
QScintilla2-Version
2.13.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
attributeBasedClustering
2.2.1
bkggeocoder
1.3.3
drucker
3.1.0
geometry_paster
0.4
OSMDownloader
1.0.3
pluginbuilder3
3.2.1
postgis_geoprocessing
0.9
punkte_setzen
1.0
qdraw
3.0.2
spatial_filter
1.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
The geopackage format has a strict limitation of one geometry field per table.

The older versions would just export the geometry as a string field. You could recreate the old behaviour using a tool like "refactor fields" from the processing toolbox and using an expression to export the geometry to a wkt string.

**Comment by sylviaobk** [comment]
Hello nyalldawson,

thank you.
But it is the same behaviour with Shape-Format and Mapinfo-TAB.

**Comment by nyalldawson** [comment]
Neither of those formats support multiple geometry columns either

**Comment by sylviaobk** [comment]
Ok, I open a new issue with vector-menu clipping and temporary layer.

**Comment by andreasneumann** [comment]
> Neither of those formats support multiple geometry columns either

@sylviaobk - if you need two or more geometry columns in Geopackage, you will have to deposit your wish at the OGC and the Geopackage working group. QGIS cannot change specifications of data formats we use.

**Comment by rouault** [comment]
> you will have to deposit your wish at the OGC and the Geopackage working group

probably not going to go much further, as this was already considered and rejected by the Geopackage working group: https://github.com/opengeospatial/geopackage/issues/646

That said, I have been involved in discussions with other QGIS community members to implement that as an extension, but no news on that front for now

**Comment by sylviaobk** [comment]
Thank you very much for the insight.
