### ISSUE TITLE
Open Feld Calculator Crash

### ISSUE THREAD

**Issue by ExaElise** [qgis/QGIS#55898]
### What is the bug or the crash?

QGIS crash because I created a new field in open field calculator

### Steps to reproduce the issue

1. Click the Layer
2. Go to Open Attribute Table
3. Go to Open Field Calculator
4. Click the Create New Field
5. Edit the Output Field Name
6. Go to Search
7. Search the Fields and Values
8. Double Click the selected Fields and Values
9. Click OK
10. See error

### Versions

QGIS version
3.34.2-Prizren
QGIS code revision
7d199797fc
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.2
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
GeoCoding
2.19
qgis_resource_sharing
1.0.0
QuickOSM
2.2.3
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x0000183c (most recent call first):

Stack Trace

QVariant::operator= :
QgsAttributeTableModel::prefetchSortData :
QgsAttributeTableFilterModel::setAttributeTableConfig :
QgsDualView::hideEvent :
QObject::qt_static_metacall :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsFieldCalculator::accept :
QObject::qt_static_metacall :
QDialogButtonBox::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgsAttributeTableDialog::mActionOpenFieldCalculator_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.34.2-Prizren
QGIS code revision: 7d199797fc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.2
Running against GDAL: 3.8.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by pigreco** [comment]
I did a test with a geopackage on win 10 and QGIS 3.34.3,
I can't reproduce the problem described
