### ISSUE TITLE
QGIS never stops fetching symbol images from web resource

### ISSUE THREAD

**Issue by webeht** [qgis/QGIS#55893]
### What is the bug or the crash?

Hi, 

we have a layer with SVG Markers, the style chooses the image based on an attribute. It works like it expected, and all SVGs are visible on the map, but QGIS never leaves the background tasks despite all are at 100% and everything is loaded. One or more tasks never get finished. Hovering the mouse shows 0 seconds remaining. 
I can work on the map and save the project but there is no way to leave QGIS. When closing the application it askes if i want to cancel unfinished background tasks but clicking YES does nothing. We always have to kill the process...really annoying...

![image](https://github.com/qgis/QGIS/assets/115455706/c37a45fc-eaca-4362-9709-bf3dec63f79c)

### Steps to reproduce the issue

Create a single symbol with a dynamic URL based on attribute like:

![image](https://github.com/qgis/QGIS/assets/115455706/d57cb9de-7c8f-4c21-a51d-7b320e26217e)

### Versions

QGIS version | 3.34.2-Prizren | QGIS code revision | 7d199797fcc
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.6
GDAL/OGR version | 3.7.1
PROJ version | 9.2.1
EPSG Registry database version | v10.088 (2023-05-13)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.42.0
PostgreSQL client version | 15.5 (Ubuntu 15.5-0ubuntu0.23.10.1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Ubuntu 23.10
  |   |   |  
Active Python plugins
batch_gps_importer | version 1.0.1
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Can you please attach the smallest possible sample project and data to reproduce the issue?

**Comment by webeht** [comment]
[sample.zip](https://github.com/qgis/QGIS/files/14022573/sample.zip)
I can reproduce this issue with the sample project and data attached...
