### ISSUE TITLE
QGis crashes when opening new 3D-MapView of LAZ-File

### ISSUE THREAD

**Issue by JaqucesT** [qgis/QGIS#55918]
### What is the bug or the crash?

QGis crashes reproducably when trying to visualize a LAZ-File in a new 3D-MapView

### Steps to reproduce the issue

1.) Download LAZ-File, i used for this:
https://www.opengeodata.nrw.de/produkte/geobasis/hm/3dm_l_las/3dm_l_las/3dm_32_280_5660_1_nw.laz
2.) Drag-and-Drop this Laz-file into a freshly opened new QGis-Instance and wait, till QGis calculated the contained point  types
3.) Open a new 3D-View for this LAZ-File
--Sometimes the QGis CrashHandler comes immeadiately after opening the 3D-Window or at least when i try to resize it or zoom in the window.
Tested this with a fresh installed QGis 3.34 and the nightly 3.35.

### Versions

QGis 3.34 and the nightly 3.35

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

After starting up without a profile i has also problems with resizing the main program window.

**Comment by uclaros** [comment]
Thanks!
This is an upstream QT bug, already filed as #53941
