### ISSUE TITLE
Drill down widget not working when parent field has the `completer` option activated

### ISSUE THREAD

**Issue by ghtmtt** [qgis/QGIS#55922]
### What is the bug or the crash?

When setting up a drill down form, if the parent field widget (`Value Relation`) has the `Use completer` option checked, the child widget is not filtered (no values can be chosen at all). 

Here a sample project where the `test` layer has both widgets as `Value Relation`  [Archive.zip](https://github.com/qgis/QGIS/files/14020607/Archive.zip)

And here a couple of screenshots:

**Parent** field widget:

![image](https://github.com/qgis/QGIS/assets/2884884/8d9fd6b3-e92e-4ba5-b356-b80a0d5b6d7b)

**Child** field widget:

![image](https://github.com/qgis/QGIS/assets/2884884/59594408-b058-440a-9bf9-57071f5e0218)

Empty field:

![image](https://github.com/qgis/QGIS/assets/2884884/7761bd74-e1f7-4f3f-a365-484e7a0af2ed)

### Steps to reproduce the issue

* toggle the editing mode for `test` layer and add a feature
* type some letter in the `county` field (e.g. F for Firenze)
* the `munic` field is empty

To make it work:

* enter in the layer properties of the `test` layer
* go in the `Attributes form` tab and select the `county` field
* deactivate the `Use completer` checkbox
* re-do all the steps of above to add a new feature and the `munic` field is filtered with the parent values

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.2-Prizren | QGIS code revision | 7d199797fcc
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.5 (Debian 15.5-0+deb12u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Debian GNU/Linux 12 (bookworm)
  |   |   |  
Active Python plugins
lizmap | master
ps-speed | 0.3.1
etra_plugin | 0.13.1
firstaid | 3.0.3
pluginbuilder3 | 3.2.1
faunalia_toolkit | 0.1.0
plugin_reloader | 0.9.3
SpreadsheetLayers | 2.1.0
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20
plugin_air_service | 0.1

</body></html>QGIS version
3.34.2-Prizren
QGIS code revision
[7d199797fcc](https://github.com/qgis/QGIS/commit/7d199797fcc)
Qt version
5.15.8
Python version
3.11.2
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.5 (Debian 15.5-0+deb12u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Debian GNU/Linux 12 (bookworm)

Active Python plugins
lizmap
master
ps-speed
0.3.1
etra_plugin
0.13.1
firstaid
3.0.3
pluginbuilder3
3.2.1
faunalia_toolkit
0.1.0
plugin_reloader
0.9.3
SpreadsheetLayers
2.1.0
grassprovider
2.12.99
processing
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20
plugin_air_service
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Did you attach the wrong project?

![immagine](https://github.com/qgis/QGIS/assets/142164/19c25cb0-f462-47ec-84b1-6c30867f8be8)

**Comment by ghtmtt** [comment]
@elpaso sorry, my bad. I've updated the zip file just now

**Comment by ghtmtt** [comment]
tested, and it works perfectly! Thanks @elpaso!
