### ISSUE TITLE
SLD: Hang when saving sld with linepattern orientation greater then 90

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#55920]
### What is the bug or the crash?

QGIS 3.34 hangs (not responding) when trying to save a style as .sld in a very specific situation.
I am using a linepattern fill with one being 45 degrees and the other being 135 degrees in different colours so I can differentiate between two features that overlap.
After testing multiple situations I finaly tracked it down (I hope) to a reproducible error. When using a linepattern with the orientation set to > 90 degrees, QGIS hangs.

### Steps to reproduce the issue

With QGIS 3.34 on windows 10
Pick any polygon layer
Symbology: Single symbol >  Line Pattern Fill
set orientation to 91 degrees
Apply
Save style as .sld

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I am happy to look at this problem, can you please provide the smallest possible project and data to reproduce the issue?

**Comment by Jeroen-GroeneBij** [comment]
Here is Italy, from the QGIS World map, with the symbology set to line pattern fill with the orientation set at 91 degrees.
[italy_test_svg.zip](https://github.com/qgis/QGIS/files/14010709/italy_test_svg.zip)
