### ISSUE TITLE
Boolean discrepancy between expression editor and layer property

### ISSUE THREAD

**Issue by NMonteix** [qgis/QGIS#55923]
### What is the bug or the crash?

There is a major discrepancy between the expression editor and the proper use of expressions e.g. in the symbology panel of the layer properties 

### Steps to reproduce the issue

To have a symbol appearing in response to a boolean field used as a rule, the proper coding would be: `"Filed_name"=true`.
But, if you use the expression editor, clicking first on the field name, then on one of the two possible field value, you obtain this:  `"Field_name" = 'true'`.
It happens to be verified in the visualization line in the expression editor. But, in the "Edit rule" window or in the layer properties window, the count is always 0 and nothing appears on map.

### Versions

3.28.15

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Djedouas** [comment]
> It happens to be verified in the visualization line in the expression editor.

Can you confirm that you are talking about the result preview line?

![image](https://github.com/qgis/QGIS/assets/34267385/54ec1082-9892-4d31-8665-916b8e644a0a)

On this line, with a test if a boolean field equals `'false'` or equals `'true'` it always shows a preview of `0`, confirming that this is incorrect and should be written `true` or `false` without quotes.

That is to say, in the preview line or in the symbology panel the result is coherent (always `0` when writing the boolean value between quotes).

**Comment by Djedouas** [comment]
Never mind, I deleted my previous comment, I mis-tested
