### ISSUE TITLE
Pole of inaccessibility returns NULLs when used in custom processing algorithm with derived layer as input

### ISSUE THREAD

**Issue by Malichmal** [qgis/QGIS#55945]
### What is the bug or the crash?

Algoriothm Pole of inaccessibility, when used in custom processing algorithm with derived layer as input, produces output point layer correctly BUT column dist_pole is empty. It works fine, with source layer as input (see Steps to reproduce the issue for minimal example or https://gis.stackexchange.com/questions/474106/pole-of-inaccessibility-returns-nulls-when-used-in-custom-processing-algorithm?noredirect=1#comment774851_474106 for more info)

### Steps to reproduce the issue

```python
#...
input_layer = self.parameterAsVectorLayer(parameters, self.INPUT, context)
another_input_layer = self.parameterAsVectorLayer(parameters, self.INPUT_2, context)

another_algo_product = processing.run("native:dissolve", {'INPUT': another_input_layer,
                                              'FIELD': ['whatever', ],
                                              'OUTPUT': 'memory:'},
                          context=context, feedback=feedback)['OUTPUT']

#  produces layer with empty column
my_new_lyr = processing.run("native:poleofinaccessibility", {
    'INPUT': another_algo_product, #  <--difference
    'TOLERANCE': 1, 'OUTPUT': 'memory:'},
                            context=context, feedback=feedback)['OUTPUT']

#  everything works as intended
my_new_lyr = processing.run("native:poleofinaccessibility", {
    'INPUT': input_layer, #  <--difference
    'TOLERANCE': 1, 'OUTPUT': 'memory:'},
                            context=context, feedback=feedback)['OUTPUT']
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
gissupport_plugin | 2.1.1
QPackage | 1.5
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
gissupport_plugin
2.1.1
QPackage
1.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.13-Firenze | QGIS code revision | 3b4db4f561
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.1
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
gissupport_plugin | 2.1.1
QPackage | 1.5
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>QGIS version
3.28.13-Firenze
QGIS code revision
[3b4db4f561](https://github.com/qgis/QGIS/commit/3b4db4f561)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.1
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
gissupport_plugin
2.1.1
QPackage
1.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Malichmal, thanks for reporting. I cannot replicate the reported issue using the latest available QGIS 3.35.0 and 3.34.3 on Windows.
Please provide a sample layer with which the issue does occur.

**Comment by Malichmal** [comment]
I made a mistake. The cause lies in another place.

**Comment by Malichmal** [comment]
I am sorry, but I made a mistake. The cause lies in another place. I will open another issue.
