### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by ishimweaxcel** [qgis/QGIS#55942]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00001644 (most recent call first):

Stack Trace

QVariant::QVariant :
version :
QAbstractProxyModel::headerData :
QSortFilterProxyModel::headerData :
QHeaderView::paintSection :
QHeaderView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QProgressDialog::setValue :
QObject::qt_static_metacall :
version :
version :
version :
version :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.34.2-Prizren
QGIS code revision: 7d199797fc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.2
Running against GDAL: 3.8.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.21996

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/72905717/1ad6118c-df18-4282-9f1b-90e04ad8edcf)

### Versions

QGIS VERSION 3.34.2-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Djedouas** [comment]
@ishimweaxcel , thanks for reporting. Could you please describe in what situation or after what operations QGIS crashed? Does the crash happen every time you do the same operations? Could you please try if the issue does occur also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?

**Comment by ishimweaxcel** [comment]
Thanks for getting back to me. Yes after sometime when am editing the
topology on study area after a while in the process it does shutdown
everytime. It also happened several times today

**Comment by DelazJ** [comment]
Can you try in a [new user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles), i.e. without any third-party plugins or custom config?
