### ISSUE TITLE
format_number() doesn't respect thousand separator setting

### ISSUE THREAD

**Issue by louis2607** [qgis/QGIS#55972]
### What is the bug or the crash?

The format_number() function doesn't follow the "Show group (thousand)" separator settings.

![qgis-bin_lIe6UVkIor](https://github.com/qgis/QGIS/assets/36734223/7b0a727a-866a-42bf-8393-bf3f295d93f7)
![qgis-bin_OZlgJLT0tW](https://github.com/qgis/QGIS/assets/36734223/045695bb-b7a9-465b-bc05-6e591cf0c404)
And this is with the unchecked configuration option
![qgis-bin_3QPxk7hsJW](https://github.com/qgis/QGIS/assets/36734223/9aa500dd-30ce-4c1a-b223-de123bfac12e)

Which make it impossible to have a label with the right decimal separator and NO thousand separator. 

![qgis-bin_97KeO6l8mw](https://github.com/qgis/QGIS/assets/36734223/c020240e-cf8e-455b-8ad9-63987f02c6d5)

### Steps to reproduce the issue

Create/use any line layer with atleast a 1000+ meters line and label its length with  `format_number($length, x)`

### Versions

QGIS version
3.34.0-Prizren
QGIS code revision
ffbdd67881
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
disconnected-islands
2.0.2
geo_sim_processing
1.2.0
GroupStats
2.2.5
HCMGIS
23.11.23
ILIAD_BAR
1.52
ILIAD_UTILS
0.18
MemoryLayerSaver
4.0.4
QNEAT3
1.0.4
QuickOSM
2.2.1
QuickWKT
3.1
quick_map_services
0.19.27
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @louis2607, thanks for reporting.
The description of the [format_number](https://docs.qgis.org/3.34/en/docs/user_manual/expressions/functions_list.html#format-number) function states that it "Returns a number formatted with the locale separator for thousands. By default the current QGIS user locale is used. Also truncates the decimal places to the number of supplied places". So, it is not stated that it respects the "Show group (thousand) separator" setting.

If you want the group (thousand) separator to be omitted, you can set the "omit_group_separators" option:
`format_number( $length, 2, omit_group_separators:=true )`

**Comment by louis2607** [comment]
Thanks!! I mainly use qgis 3.22 which didn't have this argument and when I tried on 3.34 I didn't notice there was a new argument either.
