### ISSUE TITLE
QGIS crashes everytime I try to open a specific project

### ISSUE THREAD

**Issue by emanuele0933** [qgis/QGIS#56011]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x0000287c (most recent call first):

Stack Trace

QCoreApplicationPrivate::sendPostedEvents :
QThread::currentThreadId :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.1-Firenze
QGIS code revision: fde3b8fbb8c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.0
Running against GDAL: 3.6.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

### Steps to reproduce the issue

Just after opened the project file, some seconds later it will crash, no matter what I do or not do

### Versions

3.28.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@emanuele0933, thanks for reporting. The latest available QGIS 3.28 version is QGIS 3.28.15 which is also the last released version in the 3.28 serie, so it will be no longer supported. Please check if the issue occur also using QGIS 3.34.3 and also using a new QGIS user profile without external third-party plugin installed and provide the affected project file.

**Comment by emanuele0933** [comment]
My only third party plugins are QuickMapServices,  Street View and Coordinate Capture, I will try updating the software

**Comment by uclaros** [comment]
> However QGIS website says that my version, 3.28 is the more stable and recommended for now

3.28.**15** that is! Your version 3.28.**1** is _14_ patch versions behind

**Comment by emanuele0933** [comment]
Ok, I've updated to 3.28.15 but it still keeps crashing

**Comment by agiudiceandrea** [comment]
@emanuele0933 the "Geometric Attributes" and "NumericalDigitize" plugins are external third-party plugins.
Please try if the issue occurs using a new QGIS user profile and please provide the project with which the issue occurs.

**Comment by emanuele0933** [comment]
> @emanuele0933 the "Geometric Attributes" and "NumericalDigitize" plugins are external third-party plugins. Please try if the issue occurs using a new QGIS user profile and please provide the project with which the issue occurs.

if they are, I didn' installed them by myself... How can I use another user profile? I don't use any specific user profile to be honest, or, better, I didn't know I was using one

**Comment by agiudiceandrea** [comment]
> How can I use another user profile?

The "Geometric Attributes" and "NumericalDigitize" plugins don't come preinstalled using the official QGIS installers for Windows available on the [QGIS wesite](https://www.qgis.org/). Did you use a QGIS installer for Windows other then the one available on [QGIS wesite](https://www.qgis.org/)?
The documentation page on how to create and use a new QGIS user profile is linked in the issue report form that you have compiled: https://docs.qgis.org/3.28/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles
