### ISSUE TITLE
Python package install

### ISSUE THREAD

**Issue by Bandit253** [qgis/QGIS#56032]
### What is the bug or the crash?

I am making a plugin to create an animation from the output of the Temporal Controller, but I want to install a python package with pip, to be able to publish.
Is there a way to achieve this?  I have tried a couple of methods but none work.

### Steps to reproduce the issue

`subprocess.check_call([sys.executable, "-m", "pip", "install", "moviepy"])`

### Versions

3.32

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Sorry, I realise this may not be the right tag, but I couldn't find the one that seemed correct.

**Comment by Bandit253** [comment]
I thought I had the solution try with matplotlib, but that appears to be lacking the FFMpegWriter.
```
Message: 'MovieWriter %s unavailable; using Pillow instead.'
Arguments: ('ffmpeg',)
```

**Comment by elpaso** [comment]
This is more a question than a bug, please ask on other channels (like the mailing lists), see for instance https://lists.osgeo.org/pipermail/qgis-developer/2024-January/066390.html
