### ISSUE TITLE
unable to copy/paste a feature with boolean field in a geopackage

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#56031]
### What is the bug or the crash?

copy/paste a feature with boolean field in a geopackage and try to save my edits, QGIS gives:

```
Could not commit changes to layer labs

Errors: ERROR: 1 feature not added.
  
  Provider errors:
      wrong data type for attribute 5 of feature -9: 10
```

Then I manually set the field value via "attribute editor" or "field calculator" and succeed to save. It does not matter what is the original value of the boolean field of the source feature (true/false/NULL).

### Steps to reproduce the issue

create a layer/table with a boolean field in a geopackage. add it to the map and create some features/rows. Then copy and paste that feature in an edit session and try to save your edits.

### Versions

3.28.15

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
I can't reproduce with QGIS master

**Comment by nirvn** [comment]
@faridcher , try to include a sample geopackage with which your issue can be reproduced.

**Comment by faridcher** [comment]
@nirvn I just created a geopackage and layer from scratch using QGIS GUI. I will try to test with the master. thanks
