### ISSUE TITLE
Add Delimited Text Layer dialog box closes after selecting file

### ISSUE THREAD

**Issue by seancarmody** [qgis/QGIS#56039]
### What is the bug or the crash?

When opening the Data Source Manager | Delimited Text dialog box and selecting a file the dialog box simply closes. To add the layer you have to open up the dialog box again (which now has the file name selected) and Add. I believe this is a bug rather than intended behaviour

### Steps to reproduce the issue

Open Data Source Manager | Delimited Text dialog box via Layer > Add Layer > Add Delimited Text layer. Click the '...' next to filename, browse for file and press "Open". The entire dialog box simply closes at this point, returning you to the main window. If you then open the Delimited Text dialog box again the previously selected file is there and the layer can be added. I am assuming that the correct behaviour should be to return to the dialog box after the file is selected.

### Versions

3.34.2-Prizren
MacOS 13.6.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
I bet the dialog does not close, it just get minimized. Also this is MacOS only issue.

**Comment by seancarmody** [comment]
Thanks for the prompt - led me to further investigation. It turns out that it's not minimised but it disappears behind the main window which then gets the focus. That does make for a quicker workaround (alt-` to cycle through windows) but I assume that it is still not intended behaviour, even if only for Macs

**Comment by agiudiceandrea** [comment]
It looks like similar to https://github.com/qgis/QGIS/issues/55167.

**Comment by seancarmody** [comment]
Interesting. I used the georeferencing tool very recently on the same machine and didn't experience that problem.

**Comment by nirvn** [comment]
@seancarmody , are you seeing this for other panels in the data manager dialog? I.e., if you try to open a vector dataset via the file picker, does it quick the dialog behind QGIS' main window?

**Comment by seancarmody** [comment]
I have upgraded to 3.34.3-Prizren and the problem no longer arises for me for any file type.
