### ISSUE TITLE
Expanding PostGIS table/schema in browser panel triggers slow inspection of all tables in schema

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#56069]
### What is the bug or the crash?

# Environment
I have ~150 tables and ~150 views in a PostGIS schema. Some with a geometry column with mixed geometry types (`GEOMETRY`). Some without unique primary keys.

# Problem
When I expand the node of a table in the browser panel, QGIS seems to inspect *all* tables in the schema with two types of queries:

```
WITH pkrelid AS (
SELECT indexrelid AS idxri FROM pg_index WHERE indrelid='"schema"."table"'::regclass AND (indisprimary OR indisunique)
ORDER BY CASE WHEN indisprimary THEN 1 ELSE 2 END LIMIT 1)
SELECT attname FROM pg_index,pg_attribute, pkrelid
WHERE indexrelid=pkrelid.idxri AND indrelid=attrelid AND pg_attribute.attnum=any(pg_index.indkey);
```
as in https://sourcegraph.com/github.com/qgis/QGIS@4293d4f1c57614e0a4d3835b7d9f18b3a78bcbd1/-/blob/src/providers/postgres/qgspostgresproviderconnection.cpp?L699:94-699:106

 ```
SELECT 0, array_agg(DISTINCT 25832::text || ':' || UPPER(geometrytype("geom_column"))  || ':' || ST_Zmflag("geom_column")) 
FROM (SELECT "geom_column" FROM "schema"."table" AS _unused
 ```
as in https://sourcegraph.com/github.com/qgis/QGIS@4293d4f1c57614e0a4d3835b7d9f18b3a78bcbd1/-/blob/src/providers/postgres/qgspostgresconn.cpp?L2236:70-2236:79

The queries seem to look for a usable identifier/primary key column and some geometry info. The second query can be very slow as it seems to scan the whole table(s).

For the mentioned environment the browser will be unusable for 15-30 minutes, depending on the size of the scanned tables.

# Attempts to find the reason
I have tried to find any way to prevent this, so that QGIS at least only scans the single table whose node I tried to expand in the browser. But no success. Here is what I tried:

I tried many variations of the connection options so that QGIS at least only scans the single table whose node I tried to expand in the browser. But I could not find any way to prevent it.

The following three options had no effects at all:
- *Only show layers in the layer registries*
- *Also list tables with no geometry*
- *Use estimated table metadata*

Only *Don't resolve type of unrestricted columns (GEOMETRY)* has some effect:

- With *Don't resolve type of unrestricted columns (GEOMETRY)* **off** QGIS will run the costly geometry identification query on all the schema's tables once I expand the *schema* node already

- With *Don't resolve type of unrestricted columns (GEOMETRY)* **on** QGIS will run both queries on all the schema's tables if I expand a table node within the schema tree. Expanding the schema node triggered no such queries.

# Expectation
With *Don't resolve type of unrestricted columns (GEOMETRY)* expanding a schema and/or table in the browser panel should be virtually instant.

### Steps to reproduce the issue

I have no (yet?) set up a minimal DB that reproduces this because it would take considerable time and I assume it might not be necessary. Otherwise please just say something. :)

### Versions

```
QGIS-Version 3.28.12-Firenze
QGIS-Codeversion dcc633b2de
Qt-Version 5.15.3
Python-Version 3.9.5
GDAL-Version 3.7.2
PROJ-Version 9.3.0
EPSG-Registraturdatenbankversion v10.094 (2023-08-08)
GEOS-Version 3.12.0-CAPI-1.18.0
SQLite-Version 3.41.1
PDAL-Version 2.5.5
PostgreSQL-Client-Version unknown
SpatiaLite-Version 5.1.0
QWT-Version 6.1.6
QScintilla2-Version 2.13.4
BS-Version Windows Server 2016 Version 1809

Aktive Python-Erweiterungen
db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.6
processing 2.12.99
sagaprovider 2.12.99
```

Sorry, the formatting did not survive mailing...

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I could swear I saw some related issues a while back but could not find anything at all.

I have tested some combinations of connection options in 3.32.3 too with the same results.

**Comment by elpaso** [comment]
Does this qualify as a bug?

There is certainly room for improvement but it works doesn't it?

**Comment by kannes** [comment]
> Does this qualify as a bug?
> 
> There is certainly room for improvement but it works doesn't it?

To me it seemed weird that expanding a _single_ layer node will inspect all _sibling_ layers. To the user they are not relevant in that moment.
