### ISSUE TITLE
Expression String Builder Expected Format for offset Simple Line array instead of scalar

### ISSUE THREAD

**Issue by jjvanhoutte** [qgis/QGIS#56083]
### What is the bug or the crash?

When styling a line layer, in symbol settings trying to create an offset, using the expression string builder. The expected format is listed as "string of doubles 'x,y' or array of doubles [x, y]". Entering an expression that results in either of these formats does not create an offset. Only a scalar value creates an offset. 

### Steps to reproduce the issue

![QGIS array](https://github.com/qgis/QGIS/assets/87080460/8c130940-78eb-4948-a649-44f382729d89)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.28.15-Firenze | QGIS code revision | 252ad49ddc
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows Server 2016 Version 1607
  |   |   |  
Active Python plugins
changeDataSource | 3.1
encoded-polyline | 0.9.1
exportDBmapper | 0.2.0
geopunt4Qgis | 2.3.0.5
multiple_layers_tools | 1.2
QuickOSM | 2.2.3
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.28.15-Firenze
QGIS code revision
[252ad49ddc](https://github.com/qgis/QGIS/commit/252ad49ddc)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows Server 2016 Version 1607

Active Python plugins
changeDataSource
3.1
encoded-polyline
0.9.1
exportDBmapper
0.2.0
geopunt4Qgis
2.3.0.5
multiple_layers_tools
1.2
QuickOSM
2.2.3
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jjvanhoutte, thanks for reporting. It seems to me the this issue has been already previously reported at https://github.com/qgis/QGIS/issues/47642. May you check if it is the same issue?

**Comment by jjvanhoutte** [comment]
It does seem very similar. I assume fixing this message in one place (hover) will also fix it in the other(edit form). I wonder why it didn't show up when I searched.
Thank you for finding this
Jeroen
