### ISSUE TITLE
3d map view - point clouds classification symbology changes (check/uncheck classes) not honored

### ISSUE THREAD

**Issue by Brent-Edwards** [qgis/QGIS#56109]
### What is the bug or the crash?

The 3d map view does not update to reflect changes in symbology when checking/unchecking classes.

### Steps to reproduce the issue

1) Add point cloud
2) Add 3d map view
3) Check/uncheck classes

### Versions

QGIS version
3.34.0-Prizren
QGIS code revision
ffbdd67881
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
basemesh
2.0.11
changeDataSource
3.1
gmsh
version 0.2.2
HCMGIS
23.11.23
ImportPhotos
3.0.5
latlontools
3.6.17
leastcostpath
1.1
openlayers_plugin
2.0.0
processing_fusion
3.5
processing_saga_nextgen
1.0.0
QPackage
1.5
QuickMultiAttributeEdit3
version 3.0.3
splitmultipart
1.0.0
TerrainShading
0.9.4
valuetool
3.0.17
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
This happens when checking/unchecking classes in the _layers panel_, it works as expected using the _styling panel_.
Note that toggling classes in the layers panel should only affect 3D views if the layer's 3D renderer is set to _Follow 2D Symbology_, otherwise toggling classes for 3D views can only be done using the _styling panel_/_layer properties_

**Comment by Brent-Edwards** [comment]
> This happens when checking/unchecking classes in the _layers panel_, it works as expected using the _styling panel_. Note that toggling classes in the layers panel should only affect 3D views if the layer's 3D renderer is set to _Follow 2D Symbology_, otherwise toggling classes for 3D views can only be done using the _styling panel_/_layer properties_

Thanks for the clarification. I was unaware of the nuance between the symbology changes directly in the layers panel vs those made in the styling panel/layer properties.
