### ISSUE TITLE
Millimeters and meters are swapped in Layout Legend symbology, only for ellipse symbol layers

### ISSUE THREAD

**Issue by andre-kotze** [qgis/QGIS#56104]
### What is the bug or the crash?

In the layout legend, the point layer symbology uses the wrong units for ellipse layers (simple marker works normally). For example, with these three symbol layers: 
Simple Marker, size 30 meters
Simple Marker, size 200 meters
Ellipse Marker, size 400 x 600 meters
the symbols display correctly in the main canvas and on any layout map item. However, in the layout legend, the Simple Markers are both the correct size, but the Ellipse Marker is rendered smaller than the 30 m Simple Marker, but the total symbol size in the legend is 400 x 600 **layout millimeters** (mm of the page), meaning that the symbol takes a huge space in the legend, but the ellipse is tiny. 
If you then change it in the legend item properties to a Custom Symbol, and change meters to millimeters, it shows in the legend in meters.

### Steps to reproduce the issue

1. Create a symbology (for a point layer) with a Simple Marker and an Ellipse Marker, with their sizes in meters.
2. Create a Layout with a Map and Legend
3. The point layer legend symbol will be huge
4. Set the point layer symbol to Custom Symbol
5. Change the Ellipse Marker width and height units from meters to millimeters

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234acd
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Linux Mint 21.3
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
SpreadsheetLayers | 2.1.0
qgis2web | 3.17.3
quick_map_services | 0.19.34
HCMGIS | 24.1.12
valuetool | 3.0.17
openlayers_plugin | 2.0.0
Qgis2threejs | 2.7.2
reventogis | 1.0.3
QuickOSM | 2.2.3
qgis_stac | 1.1.1
qgiscloud | 3.9.2
mmqgis | 2021.9.10
plugin_reloader | 0.9.3
AnotherDXF2Shape | 1.3.1
quick-geojson | 1.0
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234acd](https://github.com/qgis/QGIS/commit/47373234acd)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Linux Mint 21.3

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
SpreadsheetLayers
2.1.0
qgis2web
3.17.3
quick_map_services
0.19.34
HCMGIS
24.1.12
valuetool
3.0.17
openlayers_plugin
2.0.0
Qgis2threejs
2.7.2
reventogis
1.0.3
QuickOSM
2.2.3
qgis_stac
1.1.1
qgiscloud
3.9.2
mmqgis
2021.9.10
plugin_reloader
0.9.3
AnotherDXF2Shape
1.3.1
quick-geojson
1.0
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I've been using EPSG:25832

**Comment by elpaso** [comment]
Can you please check if https://github.com/qgis/QGIS/issues/56236 fixes also this issue?

If you cannot test it please attach a small sample project that can help me to reproduce the issue, instructions were not completely clear to me and I wasn't able to reproduce.
