### ISSUE TITLE
Processing toolbox result layers are placed at the top of the layer tree in version 3.34.3

### ISSUE THREAD

**Issue by danzig666** [qgis/QGIS#56129]
### What is the bug or the crash?

Processing toolbox result layers are placed at the very top of the layer tree in version 3.34.3.
In previous version the results were placed **above the currently selected layer**.

### Steps to reproduce the issue

Select an existing layer, then run any algorithm from the Processing Toolbox (e.g. Buffer). The result layer appears as the topmost layer in the layer tree.

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
In Settings --> Options --> Canvas & Legend, what is the value of "Behavior used when adding new layers"? Does it have any effects ? (#50381 is more about drag-and-drop or manual loading but... who knows?)

**Comment by agiudiceandrea** [comment]
It seems to me the regression may have been introduced in 3.32 or 3.34, after #50381 has been merged in QGIS 3.30.0. Using QGIS 3.30.3 the issue doesn't occur: https://github.com/qgis/QGIS/pull/50381#issuecomment-1953087306.

**Comment by spatialthoughts** [comment]
Confirm that this is broken in QGIS LTR 3.34. Also there is a change of behavior where after running a processing algorithm, the newly added layer is not being set as the current layer. I have filed the issue https://github.com/qgis/QGIS/issues/57003 which maybe related to this one.
