### ISSUE TITLE
Missing expression scope in batch processing expression builder

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#56132]
### What is the bug or the crash?

This is a bad regression 

3.28.15
![image](https://github.com/qgis/QGIS/assets/39594821/86f77be2-b49a-47ea-b088-5f7b59f90114)

3.34.3
![image](https://github.com/qgis/QGIS/assets/39594821/983ab1f0-4225-42f1-8412-1d0a49080125)

### Steps to reproduce the issue

1. open any alg
2. Switch to batch mode
3. Use expression builder to set ouput name (for example)
4. See missing context variable

### Versions

3.34.3

OK in 3.28.15

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
@pblottiere This is the culprit https://github.com/qgis/QGIS/commit/9df62b90f38ea964a5c7cc35ba96815f14b98080

I removed this commit and it fixes the issue.
This pussMessage should not be under `not warnOnInvalid`.

Did you remember why you added this in addition to safeguards in https://github.com/qgis/QGIS/pull/54800 ?

**Comment by nyalldawson** [comment]
@nicogodet can you test https://github.com/qgis/QGIS/pull/56411 ? I think that's a safer/better fix

**Comment by pblottiere** [comment]
> @pblottiere This is the culprit https://github.com/qgis/QGIS/commit/9df62b90f38ea964a5c7cc35ba96815f14b98080

Argh, I'm sorry @nicogodet, I completely missed this issue :sweat:.

And thanks @nyalldawson for cleaning my mess...
