### ISSUE TITLE
value relation widget in a custom ui with combobox not working with qgis > 3.28

### ISSUE THREAD

**Issue by fpennica** [qgis/QGIS#56135]
### What is the bug or the crash?

When editing a layer with:

- a field set with a value relation widget
- simple custom UI form created with QT Designer
- QComboBox inside form with objectName = field name

![test_value_relation](https://github.com/qgis/QGIS/assets/14745333/cf3a0099-92f0-4163-ad7e-3390453a366d)

the combobox is empty (QGIS 3.34):

![test_value_relation_qgis_3 34](https://github.com/qgis/QGIS/assets/14745333/beef3594-65c0-42d0-a86f-92f53c21d9bc)

The combobox is properly populated with QGIS 3.28 LTR:

![test_value_relation_qgis_3 28_LTR](https://github.com/qgis/QGIS/assets/14745333/401d22f5-42b9-41d4-82d9-2ef302a900fe)

### Steps to reproduce the issue

1. Download the test project and open `test_value_relation.qgz` in QGIS 3.34: [test_value_relation_custom_ui.zip](https://github.com/qgis/QGIS/files/14127782/test_value_relation_custom_ui.zip)
2. Insert a new feature in `test_points` layer
3. open the custom editing form 
4. the combobox is empty
5. do the same in QGIS LTR 3.28 -> the combobox is properly populated

### Versions

QGIS version | 3.34.3-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.12
Python version | 3.11.6
Compiled against GDAL/OGR | 3.8.2 | Running against GDAL/OGR | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.45.0
PDAL version | 2.6.2
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Garuda Linux
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by koenigherford** [comment]
I think issue can be closed (is solved last week by https://github.com/qgis/QGIS/pull/55964 (based on #55621))

**Comment by fpennica** [comment]
Completely missed that... thanks.
