### ISSUE TITLE
Unable to download LTR on mac

### ISSUE THREAD

**Issue by CB-Info** [qgis/QGIS#56149]
### What is the bug or the crash?

<img width="290" alt="Capture d’écran 2024-01-19 à 11 18 46" src="https://github.com/qgis/QGIS/assets/72599289/7016166f-799e-4a5d-bd53-f09052084102">

### Steps to reproduce the issue

download LTR for mac

### Versions

last LTR

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
Hello,
![image](https://github.com/qgis/QGIS/assets/7983394/de21e7bd-2dec-48e3-9550-adecf605fd02)
