### ISSUE TITLE
XYZ Tiles - The raster map has severe aliasing

### ISSUE THREAD

**Issue by uint64-t** [qgis/QGIS#56169]
### What is the bug or the crash?

QGIS Desktop
![20240204-143354](https://github.com/qgis/QGIS/assets/34449060/bb00ce4c-5175-4f39-8b5d-ec5c814133b4)

### Steps to reproduce the issue

Go to 'XYZ Tiles'
Add New Connection 'https://b.tile.openstreetmap.org/{z}/{x}/{y}.png'
See error on map view

### Versions

QGIS版本
3.34.2-Prizren
QGIS代码版本
7d199797fc
Qt版本
5.15.3
Python版本
3.9.5
GDAL/OGR版本
3.8.2
PROJ版本
9.3.1
EPSG注册数据库版本
v10.098 (2023-11-24)
GEOS版本
3.12.1-CAPI-1.18.1
SQLite版本
3.41.1
PDAL版本
2.6.0
PostgreSQL客户端版本
15.2
SpatiaLite版本
5.1.0
QWT版本
6.1.6
QScintilla2版本
2.13.4
操作系统版本
Windows 10 Version 2009

已激活的Python插件
GeoCoding
2.19
geohey_toolbox
0.4.2
latlontools
3.6.17
qgis-maptiler-plugin
3.2
QuickOSM
2.2.3
QuickWKT
3.1
quick_map_services
0.19.34
valhalla
2.4.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uint64-t** [comment]
help

**Comment by uclaros** [comment]
XYZ tiles are served in EPSG:3857 per the spec. If your project uses a different crs tiles will be resampled. I don't think this is a bug

**Comment by uint64-t** [comment]
Thanks for your attention

use EPSG:3857

You can achieve better results on a web application(based on leaflet) in a browser, but not on a desktop program(QGIS). 
?
![screenshot-20240205-163147](https://github.com/qgis/QGIS/assets/34449060/5b200467-2ada-491c-8c46-15dc806aeaf6)

![screenshot-20240205-163147](https://github.com/qgis/QGIS/assets/34449060/ccfbb1bb-6344-4553-aa0f-b7d433011c5e)

**Comment by uint64-t** [comment]
> XYZ tiles are served in EPSG:3857 per the spec. If your project uses a different crs tiles will be resampled. I don't think this is a bug

Thanks for your attention.

**Comment by nirvn** [comment]
@uint64-t , good news, this has been fixed, you can expect rendering to go back to normal in the next version of QGIS (to be released by end of the month).

**Comment by uint64-t** [comment]
> @uint64-t , good news, this has been fixed, you can expect rendering to go back to normal in the next version of QGIS (to be released by end of the month).

@nirvn Thank you very much.

**Comment by uint64-t** [comment]
QGIS 3.36.0 fixed this problom.

**Comment by wonder-sk** [comment]
(Fixed by https://github.com/qgis/QGIS/pull/56047)
