### ISSUE TITLE
Temporal controller panel bug in print layout

### ISSUE THREAD

**Issue by partas1982** [qgis/QGIS#56181]
### What is the bug or the crash?

the temporal controller panel itselfs works fine, I can browse through the different time steps e.g. of en multitemporal wms.
when I want to prepare a print layout with an item of the multitemporal WMS controlled by th temporal controller panel, it's not working fine. in the print layout it's always the newest dataset of the multitemporal WMS, that means I can not control the time steps for print layouts.
![bug_temporal_control_panel](https://github.com/qgis/QGIS/assets/46675131/0c6b3fec-b6b5-4be4-9668-7a01eb48116d)

### Steps to reproduce the issue

adfadf

### Versions

3.28.9
3.35.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
Have you tried to setup the map item [temporal range](https://docs.qgis.org/3.28/en/docs/user_manual/print_composer/composer_items/composer_map.html#temporal-range)?

**Comment by partas1982** [comment]
Thanks a lot for the hint, my fault
