### ISSUE TITLE
Export Save features to gpkg does not keep Field Domains, but using Convert Format does

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#56184]
### What is the bug or the crash?

I have a geopackage with Field Domains set. When I want to export a selection of the data into a new geopackage, I want to have all existing field domains in the new geopackage as well. Simply use Export > Save features as does not transfer the field domain settings to the new gpkg.
Using the Convert Format tool without any additional settings, does actually copy the gpkg_data_columns and gpkg_data_column_constraints from the original gpkg into the new gpkg and thus transferring the field domains into the new gpkg.

### Steps to reproduce the issue

Use the attached gpkg.
[domaintesting.zip](https://github.com/qgis/QGIS/files/14164755/domaintesting.zip)

It has a field domain: values_for_codes 
The values_for_codes is applied to the field codes

Add the layer to a new project
Export > Save features as gpkg
The new gpkg will not have the Field Domain.

Use the Convert format tool from the processing toolbox to save the original layer, do not change any settings, so no additional creation options.
The resulting gpkg will have the Field Domain.

I find it weird that the Convert Format tool, which is actually just calling ogr2ogr without any additional visible options set does copy the Field Domain, whereas the Export > Save feature menu-item does not. Doesn't it call the same ogr2ogr command?

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
batchvectorlayersaver | 0.9
geocatbridge | 4.4
GroupStats | 2.2.7
inspireatomclient | 0.8.1
latlontools | 3.6.18
maplibrary | 1.3
pdokbaggeocoder | 0.6.7
pdokservicesplugin | 4.2.0
pdok_locatieserver_locator_filter | 0.2.1
PluginLoadTimes | 4.0.2
qfieldsync | v4.7.0
qgis2web | 3.17.3
QNEAT3 | 1.0.5
QuickWKT | 3.1
quick_map_services | 0.19.34
refFunctions | 1.6
RuimtelijkePlannen | 3.5.2
SpreadsheetLayers | 2.1.0
wfsclient | 0.9.11
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
geocatbridge
4.4
GroupStats
2.2.7
inspireatomclient
0.8.1
latlontools
3.6.18
maplibrary
1.3
pdokbaggeocoder
0.6.7
pdokservicesplugin
4.2.0
pdok_locatieserver_locator_filter
0.2.1
PluginLoadTimes
4.0.2
qfieldsync
v4.7.0
qgis2web
3.17.3
QNEAT3
1.0.5
QuickWKT
3.1
quick_map_services
0.19.34
refFunctions
1.6
RuimtelijkePlannen
3.5.2
SpreadsheetLayers
2.1.0
wfsclient
0.9.11
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
fix in https://github.com/qgis/QGIS/pull/56209

**Comment by rouault** [comment]
> Doesn't it call the same ogr2ogr command?

no it doesn't
