### ISSUE TITLE
Render problem for WMS layers

### ISSUE THREAD

**Issue by pb-bennett** [qgis/QGIS#56183]
### What is the bug or the crash?

QGIS has functioned well for me for years.  After having to reinstall the OS on my PC (Windows 11, previous was 10) I have not been able to configure WMS layers to display clearly, as if something is wrong with the rendering, text and lines appear pixelated/jagged.  I include screenshots, one from QGIS and the other from a map preview at the source.  Before the reinstall QGIS used to render exactly as in the preview.  I use 'ETRS89 / UTM zone 33N' (for northern Norway) for the project and I have set this projection for the layers too - the WMS supports this projection.  I have also tried background maps from Google and OSM, which also display with the same lack of sharpness.  
I am not sure if this is a bug or a case of user error with a simple fix, apologies in advance if it is the latter.

[https://openwms.statkart.no/skwms1/wms.norges_grunnkart?request=GetCapabilities&service=WMS](https://openwms.statkart.no/skwms1/wms.norges_grunnkart?request=GetCapabilities&service=WMS)

![QGIS-screengrab](https://github.com/qgis/QGIS/assets/97233485/a176b535-ec91-4c09-bdba-203e9456a200)

![QGIS-screengrab-2](https://github.com/qgis/QGIS/assets/97233485/4fd91f7f-63cc-4b1e-93b3-11d0ac9e534d)

### Steps to reproduce the issue

1. Add [https://openwms.statkart.no/skwms1/wms.norges_grunnkart?request=GetCapabilities&service=WMS](https://openwms.statkart.no/skwms1/wms.norges_grunnkart?request=GetCapabilities&service=WMS) to project

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
can you try if "Respect screen DPI" in Settings->Options->Canvas&Legend changes anything?

You can also try to change 
![immagine](https://github.com/qgis/QGIS/assets/142164/18fcf6ed-7201-4b1e-ba51-1d58fb65049a)

**Comment by pb-bennett** [comment]
> can you try if "Respect screen DPI" in Settings->Options->Canvas&Legend changes anything?
> 
> You can also try to change ![immagine](https://private-user-images.githubusercontent.com/142164/302352514-18fcf6ed-7201-4b1e-ba51-1d58fb65049a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDcxNTE1MzIsIm5iZiI6MTcwNzE1MTIzMiwicGF0aCI6Ii8xNDIxNjQvMzAyMzUyNTE0LTE4ZmNmNmVkLTcyMDEtNGIxZS1iYTUxLTFkNThmYjY1MDQ5YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjA1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIwNVQxNjQwMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02YzY3MzZkMjkxMGMzYzNjZjUwODQxYzA3MjU5MmZhYTY2N2JlMmFhMzg5ZjI4N2VjYjZiZTFhZmM5M2VjNmUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.2xRmptI0J-FGvv7AGGGeV1Wud4SXyKCdR4nf6JuvQUs)

Thank you for taking the time to help me!  Changing the "Respect screen DPI" didn't solve the problem.  Where can I find the WMS DPI-Mode setting?  I am probably just being bad at looking for things, but I can't see it.

One thing I just discovered that I feel a bit embarrassed about not checking before is that for whatever reason when I export as an image or pdf the result is as it should be, despite the preview in the Print Layout window being as jagged as the main QGIS display.  It seems the problem is the way QGIS displays the map during editing etc, and not with whatever is going on behind the scenes to render the export - if that makes any sense.

This means I can at least continue working even though it is with a rather ugly display, knowing that what I produce at the end of the day will look as it should do.

**Comment by nirvn** [comment]
@pb-bennett , good news, I'm pretty confident this was addressed in the series of high DPI / Qt scaling fixes I've applied. Please check against the next version of QGIS (published at the end of February), things should be looking good again.

**Comment by YonatanBT** [comment]
Try different projections. Worked for me based on comments here: https://github.com/qgis/QGIS/issues/48655
