### ISSUE TITLE
QGIS 3.34.3 - Selection frame enlarged when coordinates grid is added

### ISSUE THREAD

**Issue by Bilou020285** [qgis/QGIS#56242]
### What is the bug or the crash?

In the layout tool in QGIS, when adding a map frame, the selection frame match to the extent of the map. 
If a grid is added, a margin appears around the map and it is difficult to use the magnetic grid to place all the object on the layout.

This is very annoying and disturbing...

### Steps to reproduce the issue

In the layout tool, add a new map. Add a new grid and the selection frame appears with a margin.

![2024-02-07_16h05_32](https://github.com/qgis/QGIS/assets/59787652/6cba476e-3e91-40bb-b5a4-e0b0ce7eb17e)

### Versions

3.34.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by tanrak** [comment]
Version 3.34.5 still contains this annoying bug.

**Comment by agiudiceandrea** [comment]
Hi @Bilou020285, thanks for reporting. This issue has been already previously reported at https://github.com/qgis/QGIS/issues/54931.
