### ISSUE TITLE
Plugin not available after update

### ISSUE THREAD

**Issue by sickel** [qgis/QGIS#56277]
### What is the bug or the crash?

When doing plugin development, I am sometimes reinstalling my plugin from zip. Most times, if not always, I will then have to disable and reenable the plugin to get it enabled. It seems as if the newly updated plugin is disabled even though the enable checkbox is checked.

My plugin Altitude corrector is accessible:
![bilde](https://github.com/qgis/QGIS/assets/3080462/c07d7ad1-555f-469f-b2bd-170f46b4c66e)

After having reinstalled it from the zipfile, it seems to still be active:
![bilde](https://github.com/qgis/QGIS/assets/3080462/7641f463-d51c-42fe-82c2-d46241239382)

But it has disappeared from the menu.
![bilde](https://github.com/qgis/QGIS/assets/3080462/fcb41d16-22fc-45d5-a1ac-4ac037374327)

This is also an issue when updating to a new version from the plugin repository.

### Steps to reproduce the issue

Install a plugin, see that any menu item for the plugin is visible
Reinstall the same plugin from zip file, the menu item is gone.
Disable and reenable the plugin, the menu item is back

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.3-Prizren | QGIS code revision | 47373234ac
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
altitudecorrector | 1.0
DataLoader | 1.11
DataPlotly | 4.1.0
FilterLayersAtOnce-master | 1.0
kartverket_adresse | 1.1
latlonbuffer | 0.1
openlayers_plugin | 2.0.0
pg_raster_import | 3.2.0
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.3
PostGISQueries | 0.2
postgis_geoprocessing | 0.9
postgis_toolbox | 1.1
QCopycanvas | 0.7
QGIS3-getWKT | 1.6
qgisSpectre | 1.21
qgis_resource_sharing | 1.0.0
SOSIexpressions | 1.11
SpreadsheetLayers | 2.1.1
stripchart | 1.0
timemanager | 3.6
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.34.3-Prizren
QGIS code revision
[47373234ac](https://github.com/qgis/QGIS/commit/47373234ac)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
altitudecorrector
1.0
DataLoader
1.11
DataPlotly
4.1.0
FilterLayersAtOnce-master
1.0
kartverket_adresse
1.1
latlonbuffer
0.1
openlayers_plugin
2.0.0
pg_raster_import
3.2.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
PostGISQueries
0.2
postgis_geoprocessing
0.9
postgis_toolbox
1.1
QCopycanvas
0.7
QGIS3-getWKT
1.6
qgisSpectre
1.21
qgis_resource_sharing
1.0.0
SOSIexpressions
1.11
SpreadsheetLayers
2.1.1
stripchart
1.0
timemanager
3.6
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I am pretty sure this has been an issue through all versions of QGIS 3.34, I am also pretty sure it worked quite recently. This bug report is written from a windows 11 machine, but I do see the same issue on a ubuntu machine also running v3.34-3

**Comment by sickel** [comment]
Sorry to say. The same issue still happens, both in 3.6 rc and the newest nightly, 5f1465f7bf. 

When installing an existing plugin from a zip file, it will disappear from the menu until it is disabled and re-enabled in the plugin dialog.

**Comment by pathmapper** [comment]
@sickel thanks for reporting, this is fixed for 3.38 -> https://github.com/qgis/QGIS/pull/57752
