### ISSUE TITLE
Edit menu opened hidden other top bar menu

### ISSUE THREAD

**Issue by ERHash** [qgis/QGIS#56301]
### What is the bug or the crash?

Hi,

When we open Edit menu in QGIS, in some screen (according to resolution), the edit menu cover the others menus in the top of the app (because the list is too long and it touch the bottom of the screen)

![image](https://github.com/qgis/QGIS/assets/67637529/b4f20b47-e1a6-4589-8851-04734ced5323)
![image](https://github.com/qgis/QGIS/assets/67637529/66431bab-d586-4ab4-a7d3-bfcc8aa40736)

That can happening with every menu I guess, 

Should have a scroll bar solution in the menu for fix it ?
 

### Steps to reproduce the issue

1) Open QGIS
2) Reduce the windows, or use a low resolution screen
3) open the edit menu

### Versions

All versions

Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ERHash, thanks for reporting. What QGIS version are you using? Are you sure you are using a currently supported QGIS version?

This is the Edit menu in QGIS 3.28 and QGIS 3.34:
![image](https://github.com/qgis/QGIS/assets/16253859/25cd9fbf-4da4-45c2-b2e7-57d0dd2ed59b)

**Comment by uclaros** [comment]
@ERHash You are using a quite old version of QGIS there!
This has been fixed way back in 3.18 #40812
