### ISSUE TITLE
Better link organization in Data Browser panel

### ISSUE THREAD

**Issue by arno974** [qgis/QGIS#56312]
### Feature description

When having a lot of WMS link, it can be difficult to find the one you are looking for. In addition, it is important to remember the name you gave to this link.

In the browser Panel, it would be interesting to be able to create "virtual directory" where you can drag and drop your WMS links. For example you could create directory depending on the region or the thematic and then organize WMS links according to your folder organization. In fact, it's similar to the spatial bookmarks where you already can store this bookmarks in specific "folder".

My initial idea was to have such functionality for WMS link, but It would probably be interesting to generalize this functionality to every data sources listed in the Data Browser Panel

**Comment by agiudiceandrea** [comment]
@arno974, thanks. The functionality you are requesting is the same as the one already requested at https://github.com/qgis/QGIS/issues/56043, isn't it?

**Comment by arno974** [comment]
Yes you are right, I didn't find this proposal. But it's exactly the same idea.
