### ISSUE TITLE
Zoom to Filtered Feature(s)

### ISSUE THREAD

**Issue by cm0001** [qgis/QGIS#56336]
### Feature description

Right-click on layer in Layers panel, choose "Zoom to Filtered Feature(s)" from context menu.

**Comment by agiudiceandrea** [comment]
When a layer is filtered, then only the filtered featured are displayed and considered part of the layer, thus "Zoom to Layer(s)" just zooms to the filtered features. Doesn't it?

**Comment by cm0001** [comment]
No it doesn't (for me at least).

QGIS version
3.28.15-Firenze
QGIS code revision
252ad49ddc
Layers where behavior noticed: Oracle database and shapefile layers.

**Comment by agiudiceandrea** [comment]
@cm0001, may you please provide a sample layer / project and exact steps to replicate the describe behaviour?

See a screen recording in which it is shown that the "Zoom to Layer(s)" functionality actually zooms the map to the filtered features of an ESRI Shapefile layer:

https://github.com/qgis/QGIS/assets/16253859/33fae3ac-25b9-4b2b-aa19-2a56187e330f

**Comment by bkepl** [comment]
I have never had this problem with QGIS. I have assigned a keyboard shortcut (so I don't have right click on the layer in the layer tree) that will zoom to the extents of the selected layer, and if I have a filter on that layer, the extents are always those of the features returned by the filter. (If the filter is on a rule-based symbology, the layer's extents are unchanged.)

**Comment by cm0001** [comment]
This occurs with a feature having a custom form (Qt Designer created). I cannot provide data/workspaces at this time. So, maybe just closing this request is best.
