### ISSUE TITLE
WFS: Unnecessary and misleading language paramter in a GetFeature Request

### ISSUE THREAD

**Issue by Bfrichet2** [qgis/QGIS#56348]
### What is the bug or the crash?

Dear

I work for Brussels region authority and I do want to add one of our own WFS in QGIS. We do maintain that WFS' getcapabilties in several languages (French - Dutch - English as default language).

As I try to add a specific language in QGIS 3.34.0 (for instance https://geoservices-urbis.irisnet.be/geoserver/urbisvector/wfs?version=2.0.0&language=fre) I can perfectly display the content of that French GetCapababilities in the table of content (see in green).

![image](https://github.com/qgis/QGIS/assets/78801313/2a136eff-0239-4a5b-842d-cb506b8bd5f9)

Nevertheless, I cannot display any data on the main window of QGIS (see in red above). After analysis I find that QGIS adds an unnecessary parameter to the GetFeature request to the server (see in red below). QGIS sends that GET request: http://geoservices-urbis.irisnet.be/geoserver/urbisvector/wfs?Language=fr&SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=urbisvector:Municipalities&STARTINDEX=0&COUNT=1&SRSNAME=urn:ogc:def:crs:EPSG::31370

![image](https://github.com/qgis/QGIS/assets/78801313/52e2bbb3-4a2b-4a1a-8cbc-7f5bc29013a7)

The "Language" paramater is not needed in a GetFeature request and there is a kind of problem in QGIS: instead of using ISO alpha-3 code list's value that is required and specified in my original endpoint (see in green), QGIS creates uses a ISO alpha-2 codes list's value (fr instead of fre). 

The following perfectly works http://geoservices-urbis.irisnet.be/geoserver/urbisvector/wfs?Language=fre&SERVICE=WFS&REQUEST=GetFeature&VERSION=2.0.0&TYPENAMES=urbisvector:Municipalities

I would suggest these two fixes:

1) removing the "Language" parameter in the GetFeature request that is not really usefull;
2) systematically use a [ISO alpha-3](https://www.loc.gov/standards/iso639-2/php/code_list.php) value instead of an ISO alpha-2 value as requested.

### Steps to reproduce the issue

1) create a WFS connection with a language parameter (like that one https://geoservices-urbis.irisnet.be/geoserver/urbisvector/wfs?language=fre)

2) try to add a feature type in QGIS

### Versions

QGIS 3.34.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Bfrichet2, isn't this the same server side issue as explained in https://github.com/qgis/QGIS/issues/56346?

**Comment by Bfrichet2** [comment]
@agiudiceandrea  indeed I was about to write it too. thank you very much

**Comment by Bfrichet2** [comment]
dear @agiudiceandrea , there are no  "Ignore GetMap/GetTitle/... URI reported in capabilities" option in the connection details of the WFS server connection like in the case of the WMS connection?

Regards

**Comment by agiudiceandrea** [comment]
Unfortunately, such feature has not yet been implemented. See https://github.com/qgis/QGIS/issues/29474.
