### ISSUE TITLE
WMS: Unsolicitated and uncorrect Language paramter in a GetMap Request

### ISSUE THREAD

**Issue by Bfrichet2** [qgis/QGIS#56346]
### What is the bug or the crash?

Dear

I work for Brussels region authority and I do want to add one of our own WMS in QGIS. We do maintain that WMS' getcapabilties in several languages (French - Dutch - English as default language).

As I try to add a specific language in QGIS 3.34.0 (for instance https://geoservices-urbis.irisnet.be/geoserver/UrbisAdm/ows/?version=1.3.0&language=fre) I can perfectly display the content of that French GetCapababilities in the table of content (see in green).
![image](https://github.com/qgis/QGIS/assets/78801313/96cc8eb9-d768-4eb9-a7e2-cc8fad0c84d3)

Nevertheless, I cannot display any map on the main window of QGIS (see in red above). After analysis I find that QGIS adds an unsolicited and uncorrected parameter in the GetMap request  (see in red below). QGIS sends that GET request:  http://geoservices-urbis.irisnet.be/geoserver/UrbisAdm/ows?Language=fr&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=49.48129482212485186%2C2.420151420104537543%2C51.52680103476731688%2C6.489436656568244643&CRS=EPSG%3A4326&WIDTH=571&HEIGHT=287&LAYERS=urbisFRGray&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE)

![image](https://github.com/qgis/QGIS/assets/78801313/a9574bd8-ae70-4fcd-91ab-274d1aa2a948)

The "Language" paramater is not needed in a GetMap request and there is a kind of problem in QGIS: instead of using ISO alpha-3 code list's value that is required and specified in my original endpoint (see in green), QGIS creates uses a ISO alpha-2 codes list's value (fr instead of fre). The following perfectly works http://geoservices-urbis.irisnet.be/geoserver/UrbisAdm/ows?Language=fre&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=49.48129482212485186%2C2.420151420104537543%2C51.52680103476731688%2C6.489436656568244643&CRS=EPSG%3A4326&WIDTH=571&HEIGHT=287&LAYERS=urbisFRGray&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE)

I would suggest these two fixes:  

1) removing the "Language" parameter in the GetMap request that is not really usefull;
2) systematically use a [ISO alpha-3](https://www.loc.gov/standards/iso639-2/php/code_list.php) value instead of an ISO alpha-2 value as requested.

### Steps to reproduce the issue

1) create a WMS connection with a language parameter (like that one https://geoservices-urbis.irisnet.be/geoserver/urbisgrid/ows/?request=getcapabilities&service=wms&version=1.3.0&language=fre)

2) try to display the map on QGIS 

### Versions

QGIS 3.34.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Bfrichet2, thanks for reportin. It seems to me even http://geoservices-urbis.irisnet.be/geoserver/UrbisAdm/ows?Language=fre&SERVICE=WMS&VERSION=1.3.0&REQUEST=GetMap&BBOX=49.48129482212485186%2C2.420151420104537543%2C51.52680103476731688%2C6.489436656568244643&CRS=EPSG%3A4326&WIDTH=571&HEIGHT=287&LAYERS=urbisFRGray&STYLES=&FORMAT=image%2Fpng&DPI=96&MAP_RESOLUTION=96&FORMAT_OPTIONS=dpi%3A96&TRANSPARENT=TRUE doesn't work. The server replays with:
```
<ServiceExceptionReport xmlns="http://www.opengis.net/ogc" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="1.3.0" xsi:schemaLocation="http://www.opengis.net/ogc http://geoservices-urbis.irisnet.be/geoserver/schemas/wms/1.3.0/exceptions_1_3_0.xsd">
<script> try { Object.defineProperty(navigator, "globalPrivacyControl", { value: false, configurable: false, writable: false }); document.currentScript.parentElement.removeChild(document.currentScript); } catch(e) {}; </script>
<script/>
<ServiceException> java.lang.reflect.UndeclaredThrowableExceptionNo such resource: StreetAxes(gray).sld in workspace WorkspaceInfoImpl[UrbisAdm] </ServiceException>
</ServiceExceptionReport>
```

**Comment by Bfrichet2** [comment]
@agiudiceandrea , there was an independent update of our SLD styles. Now it's done, the request works again, sorry

**Comment by agiudiceandrea** [comment]
@Bfrichet2, there is an issue in the capabilities document provided by the server.
Using https://geoservices-urbis.irisnet.be/geoserver/urbisgrid/ows/?version=1.3.0&language=fre&SERVICE=WMS&REQUEST=GetCapabilities the Capabilities document contains the following elements for the GetMap request:

```
<DCPType>
  <HTTP>
    <Get>
      <OnlineResource xlink:type="simple" xlink:href="http://geoservices-urbis.irisnet.be/geoserver/urbisgrid/ows?SERVICE=WMS&Language=fr&"/>
    </Get>
  </HTTP>
</DCPType>
```
As you can see, an incorrect URL is present.

QGIS adhere with the info provided in the capabilities document and uses such URL for the GetMap request.

You can workaround the issue on QGIs side setting the "Ignore GetMap/GetTitle/..." option in the connection details of the WMS server connection.

**Comment by agiudiceandrea** [comment]
@Bfrichet2, there is an issue in the capabilities document provided by the server.

Using https://geoservices-urbis.irisnet.be/geoserver/urbisgrid/ows/?version=1.3.0&language=fre&SERVICE=WMS&REQUEST=GetCapabilities the capabilities document contains the following elements for the GetMap request:

```
<DCPType>
  <HTTP>
    <Get>
      <OnlineResource xlink:type="simple" xlink:href="http://geoservices-urbis.irisnet.be/geoserver/urbisgrid/ows?SERVICE=WMS&Language=fr&"/>
    </Get>
  </HTTP>
</DCPType>
```
As you can see, an incorrect URL with the ISO alpha-2 language code is present.

QGIS adhere with the info provided in the capabilities document and uses such URL for the GetMap request.

You can workaround the issue on QGIS side setting the "Ignore GetMap/GetTitle/... URI reported in capabilities" option in the connection details of the WMS server connection.

**Comment by Bfrichet2** [comment]
@agiudiceandrea , thank you very much. That explains also why I saw an http URL instead of the https that I gave first. This is a bug from  my service software I guess then (i.e. geoserver)
