### ISSUE TITLE
Image info finds extra bands from some TIFF images

### ISSUE THREAD

**Issue by jratike80** [qgis/QGIS#56349]
### What is the bug or the crash?

Image information from Layer - Properties shows an extra band from some TIFF images. It the image has 4 bands, QGIS finds 5, or if if the image is a single band image, QGIS finds 2 bands.
**gdalinfo:**
```
Band 1 Block=100x10 Type=UInt16, ColorInterp=Red
Band 2 Block=100x10 Type=UInt16, ColorInterp=Green
Band 3 Block=100x10 Type=UInt16, ColorInterp=Blue
Band 4 Block=100x10 Type=UInt16, ColorInterp=Undefined
```
**QGIS:**
<img width="175" alt="image" src="https://github.com/qgis/QGIS/assets/1751612/838100dc-469d-441b-87e2-660a8a9fbb3f">

### Steps to reproduce the issue

- Open the attached image "4band16bit.tif" and check the image information.
- Create derivatives with gdal_translate and repeat the test
`gdal_translate -b 1 4band16bit.tif 1band16bit.tif`
`gdal_translate -b 1 -ot byte 4band16bit.tif 1band8bit.tif`
- Compare with the output from gdalinfo and tiffinfo

[4band16bit.tif.zip](https://github.com/qgis/QGIS/files/14279389/4band16bit.tif.zip)

### Versions

QGIS 3.35.0-Master, GDAL 3.9.0dev on Windows from OSGeo4W.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

QGIS also adds one pixel into the width of the image. Gdalinfo shows 100x100 but QGIS 101x100.

<img width="196" alt="image" src="https://github.com/qgis/QGIS/assets/1751612/bbb236d2-d025-498f-b59f-429dbb29f581">

**Comment by nirvn** [comment]
@rouault , I've looked into this and interestingly, the band count in QGIS is retrieved through GDALGetRasterCount  (i.e. here https://github.com/qgis/QGIS/blob/master/src/core/providers/gdal/qgsgdalprovider.cpp#L3764C6-L3764C60), and that gdal API returns 5. Do you have an idea as to why that API function would return a band count of 5 while gdalinfo shows only 4 bands against the same geotiff?

**Comment by rouault** [comment]
> Do you have an idea as to why that API function would return a band count of 5 while gdalinfo shows only 4 bands against the same geotiff?

This file contains a geotransform with rotation terms, hence it is not directly used, but used through GDALAutoCreateWarpedVRT() which adds a on-the-fly 5th alpha channel to take into account the fact that making the image north-up requires transparency

**Comment by nirvn** [comment]
@rouault , nice; that also perfectly explains the 1 pixel difference in width. Shall we close this issue then?

**Comment by jratike80** [comment]
Nice, I did not even notice that rotation term.
Does QGIS find a sort of on-the-fly alpha for all rotated images? What if the source image has an alpha already, will QGIS find then two alphas?

**Comment by rouault** [comment]
> Does QGIS find a sort of on-the-fly alpha for all rotated images?

yes

>  What if the source image has an alpha already, will QGIS find then two alphas?

No, it will pretty much behave like gdalwarp -srcalpha -dstalpha
