### ISSUE TITLE
Feature to Raster (Rasterize)

### ISSUE THREAD

**Issue by ARTCON2020** [qgis/QGIS#56351]
### What is the bug or the crash?

Error: dbf read: could not open file
Error: DBase file could not be opened.

### Steps to reproduce the issue

QGIS version: 3.34.3-Prizren
QGIS code revision: 47373234ac
Qt version: 5.15.3
Python version: 3.9.18
GDAL version: 3.8.3
GEOS version: 3.12.1-CAPI-1.18.1
PROJ version: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)
SAGA Next Gen version: 1.0.0
Algorithm started at: 2024-02-14T09:56:58
Algorithm 'Rasterize' starting…
Input parameters:
{ 'FIELD' : 'objtype', 'GRID' : 'TEMPORARY_OUTPUT', 'GRID_TYPE' : 7, 'INPUT' : 'D:/Min disk/Larvik/DrainageAnalysis/Bygningområdet/FKB_Bygningområde.shp', 'LINE_TYPE' : 0, 'MULTIPLE' : 4, 'OUTPUT' : 0, 'POLY_TYPE' : 0, 'TARGET_USER_FITS' : 0, 'TARGET_USER_SIZE' : 1, 'TARGET_USER_XMIN TARGET_USER_XMAX TARGET_USER_YMIN TARGET_USER_YMAX' : '544239.049900000,570616.990000000,6533530.609600000,6592777.469700000 [EPSG:25832]' }

grid_gridding "0" -TARGET_DEFINITION 0 -INPUT "D:/Min disk/Larvik/DrainageAnalysis/Bygningområdet/FKB_Bygningområde.shp" -FIELD "objtype" -OUTPUT 0 -MULTIPLE 4 -LINE_TYPE 0 -POLY_TYPE 0 -GRID_TYPE 7 -TARGET_USER_XMIN 544239.0499 -TARGET_USER_XMAX 570616.99 -TARGET_USER_YMIN 6533530.6096 -TARGET_USER_YMAX 6592777.4697 -TARGET_USER_SIZE 1.0 -TARGET_USER_FITS 0 -GRID "C:/Users/tasaz0604/AppData/Local/Temp/processing_ZlEiFY/367f31bcf91a4dcaaa9af55055c99d53/GRID.sdat" -COUNT ""

C:\Users\tasaz0604\Documents>set SAGA=C:/IT/saga-9.1.0_x64

C:\Users\tasaz0604\Documents>set SAGA_MLB=C:/IT/saga-9.1.0_x64\modules

C:\Users\tasaz0604\Documents>PATH=C:\PROGRA~1\QGIS33~1.3\apps\qgis\bin;C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\lib;C:\PROGRA~1\QGIS33~1.3\apps\grass\grass83\bin;C:\PROGRA~1\QGIS33~1.3\apps\qt5\bin;C:\PROGRA~1\QGIS33~1.3\apps\Python39\Scripts;C:\PROGRA~1\QGIS33~1.3\bin;C:\windows\system32;C:\windows;C:\windows\system32\WBem;;C:/IT/saga-9.1.0_x64;C:/IT/saga-9.1.0_x64\modules

C:\Users\tasaz0604\Documents>saga_cmd grid_gridding "0" -TARGET_DEFINITION 0 -INPUT "D:/Min disk/Larvik/DrainageAnalysis/Bygningområdet/FKB_Bygningområde.shp" -FIELD "objtype" -OUTPUT 0 -MULTIPLE 4 -LINE_TYPE 0 -POLY_TYPE 0 -GRID_TYPE 7 -TARGET_USER_XMIN 544239.0499 -TARGET_USER_XMAX 570616.99 -TARGET_USER_YMIN 6533530.6096 -TARGET_USER_YMAX 6592777.4697 -TARGET_USER_SIZE 1.0 -TARGET_USER_FITS 0 -GRID "C:/Users/tasaz0604/AppData/Local/Temp/processing_ZlEiFY/367f31bcf91a4dcaaa9af55055c99d53/GRID.sdat" -COUNT ""
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 9.1.0 (64 bit)

____________________________
library path: C:\IT\saga-9.1.0_x64\tools\
library name: grid_gridding
library : grid_gridding
tool : Shapes to Grid
identifier : 0
author : O.Conrad (c) 2003
processors : 20 [20]
____________________________

Loading shapes: D:/Min disk/Larvik/DrainageAnalysis/Bygningomr+_det/FKB_Bygningomr+_de.shp...
Error: dbf read: could not open file
Error: DBase file could not be opened.
failed
Execution completed in 2.93 seconds
Results:
{'COUNT': '',
'GRID': 'C:/Users/tasaz0604/AppData/Local/Temp/processing_ZlEiFY/367f31bcf91a4dcaaa9af55055c99d53/GRID.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/tasaz0604/AppData/Local/Temp/processing_ZlEiFY/367f31bcf91a4dcaaa9af55055c99d53/GRID.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
crayfish
3.6.0
processing_saga_nextgen
1.0.0
profiletool
4.2.6
valuetool
3.0.17
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

 
The same file format works well with ArcGIS PRO

**Comment by agiudiceandrea** [comment]
@ARTCON2020, the SAGA-GIS processing provider is no longer part of QGIS. Since you are using the SAGA Next Gen external third-party plugin, you should report your issue at https://github.com/north-road/qgis-processing-saga-nextgen/issues as already previously advised.
Anyway, the issue may be due to the presence of non ASCII characters in the file name and path.
