### ISSUE TITLE
QGIS crashes when iterating points in scratch layer

### ISSUE THREAD

**Issue by eanema** [qgis/QGIS#56352]
### What is the bug or the crash?

QGIS crashes when attempting to extract the QgsPoints from the memory layer selected in the ToC 

### Steps to reproduce the issue

1. open a new project
2. create a new temporary scratch layer
3. draw a series of random line segments, save the layer and toggle editing mode back to off, and make sure the layer is selected
4. open the python console and paste this code:

```
for feature in iface.layerTreeView().selectedLayers()[0].getFeatures():
    for point in feature.geometry().get():
        print(point)
```

The first point is displayed then QGIS crashes. I am aware that this code is missing a bunch of error checking, but this should trigger the error I'm experiencing. The code takes the (first) selected layer and attempts to print every point. It prints the first point to the console then locks up. The very similar code:

```
>>> count = 0
>>> for feature in iface.layerTreeView().selectedLayers()[0].getFeatures():
...     for point in feature.geometry().get():
...         count += 1
>>> print(count)
14
```

Works Just fine. Accessing the point is where the error occurs. 

### Versions

QGIS version
3.28.15-Firenze
QGIS code revision
252ad49ddc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
GpxSegmentImporter
2.5
pluginbuilder3
3.2.1
plugin_reloader
0.9.3
qconsolidate3
0.2.0
scriptrunner3
3.0.5
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Stack trace as copied from the crash dialog:
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00004cac (most recent call first):
  File "C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\code.py", line 90 in runcode
    exec(code, self.locals)
  File "C:\PROGRA~1\QGIS32~1.15\apps\Python39\lib\code.py", line 74 in runsource
    self.runcode(code)
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\console\console_sci.py", line 553 in runsource
    return super(ShellScintilla, self).runsource(source, filename, symbol)
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\console\console_sci.py", line 520 in runCommand
    more = self.runsource(src)
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\console\console_sci.py", line 500 in entered
    self.runCommand(self.text())
  File "C:\PROGRA~1/QGIS32~1.15/apps/qgis-ltr/./python\console\console_sci.py", line 338 in keyPressEvent
    self.entered()

Stack Trace

pdal::MetadataNode::value :
PyObject_IsSubclass :
PyErr_NormalizeException :
PyObject_MakeTpCall :
PySequence_GetItem :
PySequence_GetItem :
PyObject_GetAttrId :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyEval_EvalCodeWithName :
PyEval_EvalCodeEx :
PyEval_EvalCode :
PyCodec_DecodeText :
PyCodec_DecodeText :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyObject_GC_Del :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyObject_GC_Del :
PyVectorcall_Call :
PyObject_Call :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit__gui :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.28.15-Firenze
QGIS code revision: 252ad49ddc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19044

**Comment by agiudiceandrea** [comment]
@eanema, you need to use `constGet()`

```python
for feature in iface.layerTreeView().selectedLayers()[0].getFeatures():
    for point in feature.geometry().constGet():
        print(point)
```

or you need to store the geometry object in a variable

```python
for feature in iface.layerTreeView().selectedLayers()[0].getFeatures():
    geom = feature.geometry()
    for point in geom.get():
        print(point)
```

see https://github.com/qgis/QGIS/issues/45956#issuecomment-964542376.

Or you can use a dedicated method

```python
for feature in iface.layerTreeView().selectedLayers()[0].getFeatures():
        for point in feature.geometry().vertices():
            print(point)
```
