### ISSUE TITLE
Invalid Geometry (GEOS test) after copy / paste feature into Shapefile

### ISSUE THREAD

**Issue by okami29200** [qgis/QGIS#56361]
### What is the bug or the crash?

When using Copy /paste feature from a layer (gpkg) into an existing shapefile, it creates an invalid Geometry.
First the 2 features with a very complex geometry in the gpkg are valid (GEOS test) but after using copy/paste into a shapefile, the geometry check on the shapefile sends and invalid error on the copied features.
See attached gpkg file https://filetransfer.io/data-package/mnsPeLD1#link
If I use the merge layer instead of copy paste no issue.

### Steps to reproduce the issue

Select features
Copy
Select shapefile
Paste
Check GEOS geometry => error hole outside

### Versions

3.28.7

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by okami29200** [comment]
I didn't check with latest version.Here is the version tested :
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.28.7-Firenze | Révision du code | fedae0eb52
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.5
Version de GDAL/OGR | 3.7.0
Version de Proj | 9.2.0
Version de la base de données du registre EPSG | v10.082 (2023-02-06)
Version de GEOS | 3.11.2-CAPI-1.17.2
Version de SQLite | 3.41.1
Version de PDAL | 2.5.3
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.1
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
latlong_zoom | 0.1
plugin_reloader | 0.9.3
Proximity_Analyser_Processing | 0.1
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Version de QGIS
3.28.7-Firenze
Révision du code
[fedae0eb52](https://github.com/qgis/QGIS/commit/fedae0eb52)
Version de Qt
5.15.3
Version de Python
3.9.5
Version de GDAL/OGR
3.7.0
Version de Proj
9.2.0
Version de la base de données du registre EPSG
v10.082 (2023-02-06)
Version de GEOS
3.11.2-CAPI-1.17.2
Version de SQLite
3.41.1
Version de PDAL
2.5.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.13.1
Version de l'OS
Windows 10 Version 2009




Extensions Python actives
latlong_zoom
0.1
plugin_reloader
0.9.3
Proximity_Analyser_Processing
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

**Comment by agiudiceandrea** [comment]
@okami29200 , if the issue actually occurs with the old version your are using, while it seems to me it doesn't occur using a newer version, this means that the issue may have been already fixed.
