### ISSUE TITLE
QGIS crash when using Update Extents / Spatial Index in Layer Properties  (on a large Postgis table).

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#56379]
### What is the bug or the crash?

See https://lists.osgeo.org/pipermail/qgis-user/2024-February/054005.html

In a loaded Postgis layer (loaded via Browser, and with a lot of features), QGIS will crash when using Spatial Index or Update Extents in the Layer Properties.

I can reproduce a crash here in QGIS Master on a large table (osm_points).
But NOT in QGIS 3.34

And it seems related tp if you have saved the project or not. 
As a saved project seems not to crash.

### Steps to reproduce the issue

Having a large database (10.000.000 polygons in mail list screenshot, or 191.516.712 in case of my osm planet)
After loading a small portion of that data in a layer, you can get the Layer Properties from it.
In the source tab, you can either create a Spatial Index or Update Extents:

![image](https://github.com/qgis/QGIS/assets/731673/39a22009-d515-427c-be12-067cc2a93971)

In my case, there is already a spatial index which I do not want to drop, but apparently both that one and the Update Extents will crash QGIS silently without any more info.
Click on Update Extents
Then OK
Crash

```
QGIS died on signal 11src/app/qgscrashhandler.cpp:71 : (handleCrash) [0ms] /tmp/qgis-crash-info-98511
src/app/qgscrashhandler.cpp:124 : (handleCrash) [0ms] /home/richard/bin/qgis_/master/debug/qgiscrashhandler
/home/richard/bin/qgis: line 28: 98511 Aborted                 /home/richard/bin/qgis_/master/debug/bin/qgis "$@"
```

### Versions

QGIS version | 3.35.0-Master | QGIS code revision | ef1d7a1104e
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.8
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.2 (Debian 16.2-1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Debian GNU/Linux trixie/sid

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I cannot reproduce, but I only have a 2.7E+6 features DB.

**Comment by rduivenvoorde** [comment]
@elpaso if you sent me your public key, I can give you temporarily ssh access to my db machine, so you can test it via a ssh tunnel?

I reproduced in QtCreator, then it stops here:

![image](https://github.com/qgis/QGIS/assets/731673/7b032b4b-2cfd-46f7-b09d-e8f521ace059)

Looks like we have a 'size problem' :-)  ?

**Comment by rduivenvoorde** [comment]
I can also try to create a dummy table with random 10.000.000 points if you want?

**Comment by rduivenvoorde** [comment]
Via tunnel reproduced, I now get:
```
[New LWP 108862]
[New LWP 108864]
[New LWP 108867]
[New LWP 108872]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
0x00007f76bb2f1237 in __GI___wait4 (pid=113500, stat_loc=0x55a0aa84cdd4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
30	../sysdeps/unix/sysv/linux/wait4.c: No such file or directory.
[Current thread is 1 (Thread 0x7f76ab4af0c0 (LWP 108826))]
#0  0x00007f76bb2f1237 in __GI___wait4 (pid=113500, stat_loc=0x55a0aa84cdd4, options=0, usage=0x0) at ../sysdeps/unix/sysv/linux/wait4.c:30
        sc_ret = -512
        sc_cancel_oldtype = 0
#1  0x000055a0a6364654 in qgisCrash(int) (signal=11) at /home/richard/git/qgis/src/app/main.cpp:351
        status = 43
        pidstr = "--pid=108826\000\177\000\000\210˄\252\240U\000\000U\004\000\000v\177\000"
        gdbpid = 113500
        exename = "/home/richard/bin/qgis_/master/debug/bin/qgis\000\000\000\310˄\252\240U\000\000S\004\000\000v\177\000\000\000\000\000\000\000\000\000\000\373\001\000\000v\177\000\000\350˄\252\240U\000\000\030\000\000\000v\177\000\000\000P2*v\177\000\000\001\000\000\000v\177\000\000\000P2*v\177\000\000=\000\000\000+\000\000\000=\000\000\0000\000\000\000\000P2*v\177", '\000' <repeats 18 times>, "=\000\000\000+\000\000\000=\000\000\0000\000\000\000\030\000\000\000v\177\000\000\000P2*v\177\000\000\001\000\000\000v\177\000\000\000P"...
        len = 45
#2  0x00007f76bb25a510 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#3  __pthread_kill_implementation (threadid=<optimized out>, signo=signo@entry=11, no_tid=no_tid@entry=0) at ./nptl/pthread_kill.c:44
        tid = <optimized out>
        ret = 0
        pd = <optimized out>
        old_mask = {__val = {140144782869589}}
        ret = <optimized out>
#4  0x00007f76bb2a81cf in __pthread_kill_internal (signo=11, threadid=<optimized out>) at ./nptl/pthread_kill.c:78
#5  0x00007f76bb25a472 in __GI_raise (sig=11) at ../sysdeps/posix/raise.c:26
        ret = <optimized out>
#6  0x00007f76bb25a510 in <signal handler called> () at /lib/x86_64-linux-gnu/libc.so.6
#7  QListData::size() const (this=0x55a0b18bd180) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:115
#8  0x00007f76c2fcb6ac in QList<QTreeWidgetItem*>::count() const (this=0x55a0b18bd180) at /usr/include/x86_64-linux-gnu/qt5/QtCore/qlist.h:359
#9  0x00007f76c2fc9b5e in QTreeWidgetItem::childCount() const (this=0x55a0b18bd150) at /usr/include/x86_64-linux-gnu/qt5/QtWidgets/qtreewidget.h:193
#10 0x00007f76c1156273 in QgsAttributesFormProperties::apply() (this=0x55a0aa911000) at /home/richard/git/qgis/src/gui/vector/qgsattributesformproperties.cpp:959
        i = 1
        editFormConfig = {d = {d = 0x55a0a9be18e0}}
        fieldContainer = 0x55a0b18bd150
        relationContainer = 0x7ffc8db80908
#11 0x00007f76c11b3977 in QgsVectorLayerProperties::apply() (this=0x55a0addd8120) at /home/richard/git/qgis/src/gui/vector/qgsvectorlayerproperties.cpp:818

```

**Comment by elpaso** [comment]
Is there any chance these crashes are due to a faulty build? 
Old libraries laying around is a common cause.

If you don't figure it out here is my pub key: https://termbin.com/ywrd

**Comment by rduivenvoorde** [comment]
@elpaso I added your key and will sent you some instructions in private, so if you find time you can try if you want

**Comment by nirvn** [comment]
@nyalldawson , looking at the stacktrace screenshot above (https://github.com/qgis/QGIS/issues/56379#issuecomment-1949908047) , this feels like the crash-on-apply you just fixed right?

**Comment by nyalldawson** [comment]
Yep, it's the same

**Comment by rduivenvoorde** [comment]
Just to confirm: today's master is NOT showing this anymore.

So https://github.com/qgis/QGIS/commit/086d5cfa28ea1427d1854bdc0b9d0bffc9a43111 fixed it
