### ISSUE TITLE
Rule Based Line Symbology weird behaviour changes on zoom

### ISSUE THREAD

**Issue by jteez** [qgis/QGIS#56373]
### What is the bug or the crash?

HI All,
I've find an issue that just appeared out of nowhere... was working fine then just started misbehaving...

Fairly straight forward in principle... just a line layer with gradient on an attribute. I've converted that to rules and added other nested rules based on attributes.

This is how it looks (and used to at any scale) at 1:1565

![image](https://github.com/qgis/QGIS/assets/11745072/5d2a577e-2aa0-43bb-8018-ef5418408896)

However when I zoom out to 1:6257 and beyond it looks like this (basemap disabled to obscure location):
![image](https://github.com/qgis/QGIS/assets/11745072/3963021f-355a-490e-bea6-434dd09123b6)

The rule appears to have jumped from the if (thicker lines with graduated colour) to the else (thin lines fixed colour) on zoom.... The attribute is just a text field so shouldn't change. It didn't used to do this and then it suddenly started, initially it was a bit quirky in that I could zoom out far enough and it would start working again and it seems to have degenerated to the point where it only displays properly if I've very zoomed it.

Full Rules here:
![image](https://github.com/qgis/QGIS/assets/11745072/cf108b2b-fa25-4cd5-8b87-3fb6c7991b5e)

Additionally I have tried to copy the layer delete the rules and start again, no luck. 
I've also reimported the layer and saved as a separate file, still the same.
Restarted QGIS a couple of times.
I've also just upgraded to latest QGIS (3.34.3-Prizren) still the same.
Also created new user profile.

Is it possible if just messed up a setting someone, I can't see any scale symbology settings, or is it a genuine bug...

Thanks team,

### Steps to reproduce the issue

For me just zoom out, I doubt anyone would be able to recreate as it wasn't doing it before...

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234ac
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.3
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
GeoCoding
2.19
multilayerselect
1.5.0
pointsamplingtool
0.5.4
processing_saga_nextgen
1.0.0
qchainage
3.0.1
QuickOSM
2.2.3
SRTM-Downloader
3.2.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jteez, thanks for reporting, anyway it may be difficult to find the root cause of the bug without a project and layer(s) with which the issue occurs.

**Comment by jteez** [comment]
Thanks for the response, it's private data, so I can't just share... I am trying to set up a test set that can show it...  I came close to replicating it and had other issues appear that seemed to be related to 'Render layers as Group' - by toggling that I was able to reset some issues... I'll post with an update when I'm able to...

**Comment by jteez** [comment]
It's definitely related to 'Render layers as Group' I was able to reproduce today by checking and unchecking that box and the issue came and went. I do have multiple nested layers of 'render as a group'... I will add more detail if I can.

**Comment by nyalldawson** [comment]
We'll definitely need a sample project to diagnose this one. Can you put one together using anonymized data?
