### ISSUE TITLE
Generate XYZ Tiles (dir) - PNG Quality and Size Affected by JPG Setting, and, Aliasing toggle not working

### ISSUE THREAD

**Issue by corepuncher** [qgis/QGIS#56382]
### What is the bug or the crash?

1) When generating PNG tiles, even though it says "Quality (JPG Only)", this value will affect PNG image output.

2) "Enable anti-aliasing"  toggle does not appear to work on PNG images.

3) Quality of the PNG images appears grainy.

### Steps to reproduce the issue

In the "Generate XYZ" raster tiles interface, it says that the quality level (which defaults to 75) is "JPG Only".

If you choose PNG format, and then adjust the value anyway to >=90, all PNG tiles will have the exact same size, even if they are blank. 256 kb.

If you adjust this value to < 90, say 89, then the blank pngs become small again (around 1.24 kb).

In addition, when generating png images, the "Enable anti-aliasing" toggle does not appear to affect quality at all. 

Further, the PNG output images IMO appear noisy; even the background part with no lines has much noise. That is why I was trying to adjust these setting in order to get a sharper image.

### Versions

I'm using a new install of 3.34.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @corepuncher, thanks for reporting. Do you know if the issue also occur using any QGIS version < 3.34?

**Comment by corepuncher** [comment]
I created some test png tiles using version 3.28.15. Put Quality at 100 even though it's not jpg.  
Same result. All tiles have size 256 kb which is interesting since the size of the tiles is 256x256.

**Comment by agiudiceandrea** [comment]
@corepuncher, I've submitted a patch that I think should fix both issues.
If you are using Windows, you can check if the patched build of QGIS works also for you, just downloading the QGIS MingW64 Windows 64bit Build https://github.com/qgis/QGIS/pull/56395#issuecomment-1951000382 and executing it (see: https://gist.github.com/agiudiceandrea/c95c4eac00879f0b8108a57d6aa4e652).
