### ISSUE TITLE
QGIS on OpenSuse Tumbleweed has no Python module available

### ISSUE THREAD

**Issue by frankbroniewski** [qgis/QGIS#56401]
### What is the bug or the crash?

Hello,

on OpenSuse Tumbleweed, there is no Python `qgis` module available. Importing qgis in a Python console results in a `ModuleNotFoundError`.

```
Python 3.11.8 (main, Feb 08 2024, 08:03:16) [GCC] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import qgis
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'qgis'
>>> 
```

The cause for the error is a missing qgis module for install. There is no python3-qgis package (or similary named) availabe for install.
```
frank@schnipsel:~> zypper search qgis
Repository-Daten werden geladen...
Installierte Pakete werden gelesen...

S  | Name                            | Summary                                          | Type
---+---------------------------------+--------------------------------------------------+-----------
i+ | qgis                            | A Geographic Information System (GIS)            | Paket
   | qgis                            | A Geographic Information System (GIS)            | Quellpaket
   | qgis-debuginfo                  | Debug information for package qgis               | Paket
   | qgis-debugsource                | Debug sources for package qgis                   | Paket
   | qgis-devel                      | Development Libraries for QGIS                   | Paket
   | qgis-ltr                        | A Geographic Information System (GIS)            | Paket
   | qgis-ltr                        | A Geographic Information System (GIS)            | Quellpaket
   | qgis-ltr-debuginfo              | Debug information for package qgis-ltr           | Paket
   | qgis-ltr-debugsource            | Debug sources for package qgis-ltr               | Paket
   | qgis-ltr-devel                  | Development Libraries for QGIS                   | Paket
   | qgis-ltr-plugin-grass           | GRASS Support Libraries for QGIS                 | Paket
   | qgis-ltr-plugin-grass-debuginfo | Debug information for package qgis-ltr-plugin--> | Paket
   | qgis-ltr-sample-data            | QGIS sample data                                 | Paket
   | qgis-plugin-grass               | GRASS Support Libraries for QGIS                 | Paket
   | qgis-plugin-grass-debuginfo     | Debug information for package qgis-plugin-grass  | Paket
i+ | qgis-sample-data                | QGIS sample data                                 | Paket
```

I use the OpenSuse repository mentionned on the QGIS [download page](https://qgis.org/en/site/forusers/alldownloads.html#suse-opensuse).
```
frank@schnipsel:~> zypper lr -Pu
#  | Alias                                | Name                                   | Enabled | GPG Check | Refresh | Priority | URI
---+--------------------------------------+----------------------------------------+---------+-----------+---------+----------+---------------------------------------------------------------------------------------
 1 | Geo                                  | Geo                                    | Ja      | (r ) Ja   | Ja      |   90     | https://download.opensuse.org/repositories/Application:/Geo/openSUSE_Tumbleweed/
```

In addition, I noticed that the OpenSuse standard [repo](https://download.opensuse.org/tumbleweed/repo/oss/x86_64/) has QGIS as well (3.34.1) - but python3-qgis isn't there either. Is the Geo-repository still necessary?

```
frank@schnipsel:~> cat /etc/*release
NAME="openSUSE Tumbleweed"
# VERSION="20240216"
ID="opensuse-tumbleweed"
ID_LIKE="opensuse suse"
VERSION_ID="20240216"
````

### Steps to reproduce the issue

1. Install Tumbleweed
2. Optional: add QGIS-repo as shown on the QGIS download page
3. search in zypper for qgis

### Versions

n/a

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

On the packaging team's [site](https://qgis.org/en/site/getinvolved/governance/governance.html) there's Angelos Tzotsos mentioned as maintainer, unfortunately I do not know how to contact him.

**Comment by agiudiceandrea** [comment]
Have you properly set the `PYTHONPATH` environment variable on your system as explained in the [docs](https://docs.qgis.org/3.28/en/docs/pyqgis_developer_cookbook/intro.html#running-custom-applications)?

**Comment by frankbroniewski** [comment]
Hey Andrea, now I feel dumb ...

In my defense, I never had to set a PYTHONPATH variable on any Linux system I used before (Fedora and Ubuntu). There you just install python3-qgis and the QGIS Python module is installed in the correct path for system wide Python packages, i.e. `/usr/lib/python3/dist-packages/qgis/` on Ubuntu. I never had to mess with PYTHONPATH, that's why developing on Linux is so much nicer in comparison to Windows ...

That OpenSuse is different here and the QGIS Python module is somewhere non-standard came as a surprise to me. Guess you never stop learning ...
