### ISSUE TITLE
[DOC] Missing chapter "16.2.6. Creating one or many to many relations" in QGIS 3.34 documentation 

### ISSUE THREAD

**Issue by swiss-knight** [qgis/QGIS#56422]
### Feature description

QGIS 3.28:
![image](https://github.com/qgis/QGIS/assets/19967599/0fb50dde-b81c-4f2e-a063-4964b382e44f)

QGIS 3.34:
![image](https://github.com/qgis/QGIS/assets/19967599/23870a10-a5d2-4558-91a2-40a2c34bfdec)

The former chapter "[16.2.6. Creating one or many to many relations](https://docs.qgis.org/3.28/en/docs/user_manual/working_with_vector/attribute_table.html#id43)" doesn't exist anymore in the QGIS 3.34 documentation.

**Comment by agiudiceandrea** [comment]
Ping @DelazJ.

**Comment by DelazJ** [comment]
See https://docs.qgis.org/3.34/en/docs/user_manual/working_with_vector/joins_relations.html

**Comment by agiudiceandrea** [comment]
Thanks!
