### ISSUE TITLE
QGIS: Snap geometries to layer - not all points are snapping

### ISSUE THREAD

**Issue by Pavlovhadgeenkat** [qgis/QGIS#56424]
### What is the bug or the crash?

I am trying to snap sample collection points to the nearest location on a path, however, not all points are snapping correctly.

I use the tool snap geometries to layer and choose the option prefer closest point, insert new vertices to get snapped points that are now somewhere along the path. I set the tolerance limit to 10 metres.

The output shows some points are correctly snapping, but there are many which do not, despite being within the tolerance limit.

### Steps to reproduce the issue

Here is an example. I'm showing my line and a 10 m buffer so you can see which points should be snapped and and which shouldn't.
I also symbolised them by distance to the line. Only the stars should be snapped.
![image](https://github.com/qgis/QGIS/assets/26501198/d9d83964-1336-41d7-8931-5ced08e22a1e)

If i run the tool Snap geometries to layer (vector processing), with 10m tolerance my output will look exactly the same as the input. Nothing gets snapped.
If i ramp up the distance, only at 100m all my points will get snapped. Some additional points get snapped too, a bit randomly which ones...
![image](https://github.com/qgis/QGIS/assets/26501198/d771f8c1-cebf-4384-afcd-80f859977683)

if i overlay my input and output dataset (output indicated with blue shade) with ID as label, you can see it's a bit random which points get projected and which don't!
![image](https://github.com/qgis/QGIS/assets/26501198/f77b59ee-0772-4c20-a438-798453a0a6d8)

EPSG of both shapefiles is  28992 , the projected system RD new. Input files are added.
[input files.zip](https://github.com/qgis/QGIS/files/14344003/input.files.zip)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.0-Prizren | QGIS code revision | ffbdd67881
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.7.2
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.0-CAPI-1.18.0
SQLite version | 3.41.1
PDAL version | 2.5.5
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows Server 2016 Version 2009
  |   |   |  
Active Python plugins
BGTImport | 3.18
color_attribute | 0.2.1
DataPlotly | 4.1.0
pdokservicesplugin | 4.2.0
profiletool | 4.2.6
timemanager | 3.6
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.0-Prizren
QGIS code revision
[ffbdd67881](https://github.com/qgis/QGIS/commit/ffbdd67881)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.2
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows Server 2016 Version 2009

Active Python plugins
BGTImport
3.18
color_attribute
0.2.1
DataPlotly
4.1.0
pdokservicesplugin
4.2.0
profiletool
4.2.6
timemanager
3.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@Pavlovhadgeenkat , thanks for reporting this issue. Expect it fixed in the next release (end of Feb.).
