### ISSUE TITLE
Opening a compound table in mssql

### ISSUE THREAD

**Issue by LStensson** [qgis/QGIS#56457]
### What is the bug or the crash?

The crash came when trying to open a table in MSSQL which contains compound geometry, line, point and polygon.
## User Feedback

Opening a compound table in mssql

## Report Details

**Crash ID**: [a0f1dd599d393bd8d56b8bbbd3a54f33062b64e8](https://github.com/qgis/QGIS/search?q=a0f1dd599d393bd8d56b8bbbd3a54f33062b64e8&type=Issues)

**Stack Trace**
<pre>
RtlEnterCriticalSection :
EnterStmtCS :
SQLFetchScroll :
QSqlQuery::next :
providerMetadataFactory :
QgsAbstractDatabaseProviderConnection::QueryResult::rows :
providerMetadataFactory :
QgsAbstractDatabaseProviderConnection::table :
QgsFieldsItem::QgsFieldsItem :
providerMetadataFactory :
QgsDataItem::runCreateChildren :
QgsDataItem::runCreateChildren :
QgsDataItem::removeChildItem :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.14-Bia?owie?a
QGIS code revision: 4cde646c
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.1
Running against GDAL: 3.6.1

### Steps to reproduce the issue

Source, 
MSSQL,
database,
click on arrow to the table.

### Versions

QGIS Version: 3.22.14-Bia?owie?a

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@LStensson, thanks for reporting. QGIS 3.22 is no longer supported. Please try if the issue occur using a currently supported QGIS version and a new QGIS user profile. If the issue still occurs, then please provide a sample layer with which the issue occurs.
