### ISSUE TITLE
QGIS cannot handle 'Composite Keys' in GDAL database connections (tested: Mysql, Mariadb, Postgis)

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#56463]
### What is the bug or the crash?

Having a Mysql table with points in a table with a 'CompositeKey' as primary key:
- QGIS will show all 10 points (2 groups)
- on select only use half of they key (in this case show half of the points as selected).
- in attribute table only show 2 records

![Screenshot from 2024-02-21 16-01-39](https://github.com/qgis/QGIS/assets/731673/35444d7a-f21c-4b4c-a6e9-49b52616819f)

Then testing this in Mariadb:
- behaves the same as mysql

![image](https://github.com/qgis/QGIS/assets/731673/98b11c61-ebfd-4f7c-92f4-38b338f8d861)

Then in Postgis (via Add vector layer/Database, NOT via the native postgresql provider!):
- QGIS will show all 10 points
- but trying to select 1 another one gets selected
- attribute table will show all records

![image](https://github.com/qgis/QGIS/assets/731673/fdbc09b9-cea3-4421-82cb-a1771e799d6c)

### Steps to reproduce the issue

(copied the docker test db idea from @rouault, thanks Even!)

Run a container with a database 'test; to be able to load data in and connect with QGIS:
```
NOTE: best to run the lines one by one:


# mysql root/passwd on port 33060
docker run --name gdal-mysql1 -e MYSQL_ROOT_PASSWORD=passwd -e "MYSQL_ROOT_HOST=%" -p 33060:3306 -d mysql:8.0.34 mysqld --default-authentication-plugin=mysql_native_password
docker exec gdal-mysql1 sh -c "echo 'CREATE DATABASE test; SELECT Version()' | mysql -uroot -ppasswd"

# mariadb root/passwd on port 33061
docker run --name gdal-mariadb1 -e MARIADB_ROOT_PASSWORD=passwd -e "MYSQL_ROOT_HOST=%" -p 33061:3306 -d mariadb:11.2 
docker exec gdal-mariadb1 sh -c "echo 'CREATE DATABASE test; SELECT Version()' | mysql -uroot -ppasswd"

# postgis postgres/passwd on port 54322
docker run --name gdal-postgis1 -p 127.0.0.1:54322:5432 -e POSTGRES_PASSWORD=passwd -d postgis/postgis
docker exec gdal-postgis1 sh -c "PGPASSWORD=passwd;echo 'CREATE DATABASE test; SELECT Version();' | psql -U postgres"
docker exec gdal-postgis1 sh -c "PGPASSWORD=passwd;echo 'create extension postgis;select postgis_version();' | psql -U postgres test"
```

Now create the table and records with the following sql's:

```
-- mariadb and mysql
CREATE TABLE `tblqgistest` (
  `dossierid` int NOT NULL,
  `proefnaam` varchar(6) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `meetmethod` tinyint unsigned DEFAULT NULL,
  `relta` varchar(44) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `coord` geometry NOT NULL /*!80003 SRID 31370 */,
  `gw` varchar(54) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `orderid` int NOT NULL,
  `ts` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`dossierid`,`proefnaam`),
  SPATIAL KEY `coord` (`coord`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- postgres	
CREATE TABLE tblqgistest (
  dossierid int NOT NULL,
  proefnaam varchar(6) NOT NULL,
  meetmethod int DEFAULT NULL,
  relta varchar(44) DEFAULT NULL,
  coord public.geometry(point, 31370),
  gw varchar(54) DEFAULT NULL,
  orderid int NOT NULL,
  ts timestamp NULL,
  PRIMARY KEY (dossierid,proefnaam)
)

-- some records (a set of 2 groups)
INSERT INTO tblqgistest (dossierid,proefnaam,meetmethod,relta,coord,gw,orderid,ts) VALUES
	 -- set 1
	 (1531415,'S05',2,'+44.65 m',ST_GeomFromText('POINT (241102.98 324414.29)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1531415,'S06',2,'+44.52 m',ST_GeomFromText('POINT (241122.91 324411.91)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1531415,'S10',2,'+45.16 m',ST_GeomFromText('POINT (241053.37 324420.3)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1531415,'S11',2,'+44.89 m',ST_GeomFromText('POINT (241039.1 324425.99)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 -- set 2
	 (1545715,'S03B',2,'+45.12 m',ST_GeomFromText('POINT (241063.29 324419.11)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1545715,'S12',2,'+45.19 m',ST_GeomFromText('POINT (241043.43 324421.51)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1545715,'S13',2,'+45.12 m',ST_GeomFromText('POINT (241023.58 324423.91)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1545715,'S14',2,'+45.02 m',ST_GeomFromText('POINT (241003.72 324426.29)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1545715,'S15',2,'+45.00 m',ST_GeomFromText('POINT (240983.88 324428.69)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0'),
	 (1545715,'S16',2,'+44.93 m',ST_GeomFromText('POINT (240970.53 324430.28)', 31370),'D: 0.00 m',1,'2024-02-20 14:20:55.0');

```

Use the following QGIS project to connect load all data to (these specific dockers), unzip first!:

[issue-project.zip](https://github.com/qgis/QGIS/files/14361527/issue-project.zip)

OR you could connect via GDAL/QGIS to the databases:
![image](https://github.com/qgis/QGIS/assets/731673/e5472d35-dd0e-4187-b635-6d22ef130a56)

### Versions

Tried different versions of QGIS, GDAL: 3.8.3

QGIS version | 3.35.0-Master | QGIS code revision | f6e073f0eed
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.8
GDAL/OGR version | 3.8.3
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.2 (Debian 16.2-1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Debian GNU/Linux trixie/sid

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
> QGIS cannot handle 'Composite Keys' in GDAL database connections 

This is more a OGR limitation. Its model of FID is based on a single column int64 primary key.
