### ISSUE TITLE
Crash when loading WMTS layer

### ISSUE THREAD

**Issue by rhuesken** [qgis/QGIS#56484]
## User Feedback

Add a new WMTS layer. The legend is shown, QGIS crashes immediately after retrieving tiles

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x0000bc30 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QAbstractFileEngineIterator::~QAbstractFileEngineIterator :
QIODevice::channelReadyRead :
QIODevice::write :
QTcpServer::proxy :
QHttpMultiPart::qt_metacast :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QThread::exec :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.3-Prizren
QGIS code revision: 47373234ac
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Add WMTS layer, select the layer based on the capabilities, click a ADD.
The legend urls is called and the legend is displayed, QGIS crashes immediately

### Versions

QGIS Info
QGIS Version: 3.34.3-Prizren
QGIS code revision: 47373234ac
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@rhuesken, thanks for reporting. Does the crash occur using with any WMTS layer or only with a specific one? Please try if the issue does occur also using a new QGIS user profile. It it does, please provide a WMTS layer URL with which the issue occurs.

**Comment by rhuesken** [comment]
Hi, Thanks for your suggestion. The issue occurred with a specific WMTS (our own, proprietaty implementation). However, I created a new user profile and now the WMTS layer loads without problems.

**Comment by agiudiceandrea** [comment]
Thanks for checking and reporting back.
