### ISSUE TITLE
Spatial Bookmark Manager crash

### ISSUE THREAD

**Issue by yljxhh** [qgis/QGIS#56493]
### What is the bug or the crash?

A crash happened when using Spatial Bookmark Manager.

## User Feedback

1 open  Spatial Bookmark Manager,
2 then,add 6 bookmarks,
3 after that, delete the 4 and 5 bookmarks at the same time,
4 then, add a new bookmark.
5 oops, may cause a crash!

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006738 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QSortFilterProxyModel::parent :
QSortFilterProxyModel::mapToSource :
QSortFilterProxyModel::flags :
QModelIndex::flags :
QAbstractItemView::focusInEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::setFocusWidget :
QWidget::setFocus :
QApplication::setActiveWindow :
QApplicationPrivate::notifyActiveWindowChange :
QGuiApplicationPrivate::processActivatedEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

**QGIS Info**
QGIS Version: 3.28.4-Firenze
QGIS code revision: fd0fb72ab3
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.2
Running against GDAL: 3.6.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
While I cannot replicate the Crash on my system, I can see that there is an issue removing multiple items using the Spatial Bookmark Manager:


https://github.com/qgis/QGIS/assets/16253859/946173cd-66e8-4e8f-b689-6fff54a5cd9e

Ping @elpaso.
