### ISSUE TITLE
Plug-In Repo not available in 3.36

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#56507]
### What is the bug or the crash?

Plug-ins repo not available for new install of v3.36.
https://plugins.qgis.org/plugins/plugins.xml?qgis=3.36

### Steps to reproduce the issue

Open plug-in manager

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Unfortunately it seems this is a recurring issue that happens at almost every new release. I hope someone having admin access rights (maybe @gustr) can add the missing release versions.

**Comment by Gustry** [comment]
It will be fixed soon, the cache will be updated.

I will keep this ticket open for myself.

**Comment by agiudiceandrea** [comment]
Thanks!

**Comment by agiudiceandrea** [comment]
It's fixed now.
