### ISSUE TITLE
Can't start flatpak release, "error while loading shared libraries: libprotobuf-lite.so.25.3.0"

### ISSUE THREAD

**Issue by polyene** [qgis/QGIS#56521]
### What is the bug or the crash?

After some update I'm not able to start QGIS v3.36.0 at all from the flatpak distribution. Trying to run in a terminal window gives the following message:
`qgis: error while loading shared libraries: libprotobuf-lite.so.25.3.0: cannot open shared object file: No such file or directory`

### Steps to reproduce the issue

Open a terminal window and run
`flatpak run org.qgis.qgis`

### Versions

v3.36.0 installed from Flathub. Running Linux Mint 21.3. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @polyene, thanks for reporting. Since the issue is due to the build process of QGIS for the Flatpak distribution, you'ld need to report the issue to the Flatpak repository- Anyway the issue has been already reported there https://github.com/flathub/org.qgis.qgis/issues/439.

**Comment by ximex** [comment]
confirm that this is fixed with newest flatpak version

**Comment by polyene** [comment]
Thank you for responding so quickly. The updated flatpak solved this issue!
