### ISSUE TITLE
QGIS expression display double at concave sections

### ISSUE THREAD

**Issue by neogeomat** [qgis/QGIS#56528]
### What is the bug or the crash?

Using qgis expression to display polygon vertices as font markers. 
![](https://i.stack.imgur.com/RVNuv.png)

When the Line offset is -5 positive the text 'P7' is displayed far from the point. So I changed the Line offset to 5, and an extra vertex gets added (p8).
![](https://i.stack.imgur.com/TeAWQ.png)
On concave sections, an extra vertex is displayed. 
![](https://i.stack.imgur.com/iiLkQ.png)

More detail in [gis.stackexchange](https://gis.stackexchange.com/questions/477630/why-qgis-expression-display-double-at-concave-sections)

### Steps to reproduce the issue

1. Draw a concave polygon.
2. display polygon vertices as font markers. 
![](https://i.stack.imgur.com/RVNuv.png)
3. Change Line Offset

### Versions

QGIS version 3.28.5-Firenze
QGIS code revision 50adba36f2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
Can you attach a project or a symbology file?

**Comment by blacktesta** [comment]
@neogeomat line offset makes a buffer of geometry. Buffer can and almost always contains different amount of verticies than original geometry.
