### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by wildgunfighter** [qgis/QGIS#56532]
### What is the bug or the crash?

Crash happens randomly when saving an object after editing in pop-up window, then the app ended unexpectedly.

Stack Trace

QSortFilterProxyModel::`default constructor closure' :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::dataChanged :
QSortFilterProxyModel::`default constructor closure' :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::dataChanged :
QgsAttributeTableModel::bulkEditCommandEnded :
QObject::qt_static_metacall :
QgsVectorLayer::endEditCommand :
QgsAttributeForm::saveEdits :
QgsAttributeForm::saveWithDetails :
QObject::qt_static_metacall :
QgsVectorLayer::isModified :
QgsRelationWidgetWrapper::aboutToSave :
QgsAttributeForm::saveWithDetails :
QgsAttributeDialog::accept :
QObject::qt_static_metacall :
QDialogButtonBox::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
 

QGIS Info
QGIS Version: 3.20.2-Odense
QGIS code revision: 9f59a156
Compiled against Qt: 5.15.2
Running against Qt: 5.15.2
Compiled against GDAL: 3.3.1
Running against GDAL: 3.3.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

As I've written before, it happens randomly.

### Versions

Wersja QGIS
3.20.2-Odense
Rewizja QGIS
9f59a156
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.1
PROJ version
8.1.0
EPSG Registry database version
v10.027 (2021-06-17)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
13.0
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows Server 2016 Version 1809

Active Python plugins
coordinate_capture
qgis_attachments
db_manager
MetaSearch
processing

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@wildgunfighter thanks for reporting. QGIS 3.20 is no longer supported. Please try if the issue occurs using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please reopen this issue report and provide a sample project / layer and exact steps to replicate the issue.
