### ISSUE TITLE
3.36 PostGIS layers have no spatial extent

### ISSUE THREAD

**Issue by Komz0** [qgis/QGIS#56541]
### What is the bug or the crash?

Layers loaded from a PostgreSQL / PostGIS database have no spatial extent.
Extent in Information tab of layer is set to Null.
Zoom to layer functionality throw this warning :  
WARNING    result of extents query invalid: BOX(144881.046875 200921.21875,505398.1875 515061.03125)

The issue is 3.36 specific ; the same layers works in 3.32 and 3.28.
No issues with a Geopackage layer.

### Steps to reproduce the issue

Load a layer from a PostGIS database.

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
fms_cycles
0.1
sln_acquire
0.1
string_importer
0.1
db-style-manager
0.8
firstaid
3.1.0
HouseNumbering3
version 0.0.5
lizmap
4.2.2
pg_metadata
1.3.0
plugin_reloader
0.9.3
plume
1.1.1
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qfieldsync
v4.7.1
Qgis2threejs
2.7.3
qgis2web
3.18.2
QGISSortAndNumber-master
1.0
quick_map_services
0.19.34
StyleLoadSave
1.0
ViewshedAnalysis
1.8
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

PostgreSQL 15.3
PostGIS 3.3 USE_GEOS=1 USE_PROJ=1 USE_STATS=1

**Comment by elpaso** [comment]
I cannot reproduce on QGIS 3.6, can you attach a minimal SQL dump of a database table that shows the issue?

**Comment by Komz0** [comment]
I tried to make a minimal SQL, but It doesn't occur with small dataset (limit seems around 1000 rows). Also, I noticed it only occur with the "Use estimated table Metadata" option activated.

**Comment by tbnobody** [comment]
I am facing the same issue. Could reproduce it as shown in the attached pdf

[qgis_bugifx.pdf](https://github.com/qgis/QGIS/files/14601043/qgis_bugifx.pdf)

**Comment by Antoviscomi** [comment]
in mine 3.36:
1. PG layer

![Schermata del 2024-03-21 09-57-07](https://github.com/qgis/QGIS/assets/12639444/8032f3ad-2a04-40fa-bade-be4d5574c9b9)

the same layer exported in local

![Schermata del 2024-03-21 10-52-27](https://github.com/qgis/QGIS/assets/12639444/806f3f4e-51f7-4385-acc0-58a8e5d433bf)

**Comment by Antoviscomi** [comment]
in addition I'm not able to clean a spatial filer on source properties as you can see in screencast

[Video del 21-03-2024 11:22:01.webm](https://github.com/qgis/QGIS/assets/12639444/ab03dece-118f-4195-8beb-fa717e8e4d7e)

I dont know it's related but this behaviour came out only in Spatiaally filtered layers

 
![Filtered](https://github.com/qgis/QGIS/assets/12639444/6e16cad2-0e1c-48c5-a8c0-f43de84e9325)

while in non filtered layer

![nonFiltered](https://github.com/qgis/QGIS/assets/12639444/3b66466e-bb89-43ef-a24b-b79fbe3c825c)

**Comment by Antoviscomi** [comment]
this seems very very strange

[Video del 21-03-2024 13:07:13.webm](https://github.com/qgis/QGIS/assets/12639444/12c70155-3441-46bb-9e5b-8d31678cf807)

**Comment by Antoviscomi** [comment]
persists in 3.36.1-Maidenhead | Revisione codice QGIS | 3e589453264
-- | -- | --


</body></html>3.36.1-Maidenhead
Revisione codice QGIS
[3e589453264](https://github.com/qgis/QGIS/commit/3e589453264)

**Comment by PeterDrexel** [comment]
Try to turn off “Use estimated table metadata” in the PostGIS Connection Options.
This works for me in QG 3.36 und 3.37.

**Comment by Antoviscomi** [comment]
@PeterDrexel it's not true for me, the "Estimated metadata" box was unflagged as you can see below but no spatial extension 
![Schermata del 2024-04-23 13-50-26](https://github.com/qgis/QGIS/assets/12639444/2be9f539-73be-481d-ad29-5556ab12c028)

but no spatial extension as you can see in below

![Schermata del 2024-04-23 13-52-09](https://github.com/qgis/QGIS/assets/12639444/f78a53a5-6de1-4db6-aaec-1c5dadd5b2f2)

**Comment by strk** [comment]
According to code what makes the result of extent query invalid is not matching this regexp:
`const thread_local QRegularExpression rx( "\\((.+) (.+) (.+),(.+) (.+) (.+)\\)" );`

**Comment by strk** [comment]
Removing the duplicated backslashes fixes the issue for me, PR coming next.

**Comment by strk** [comment]
Sorry, I'm taking it back, it's not the backslashes but the number of ordinates expected, why are 3 ordinates expected instead of 2 ?

**Comment by strk** [comment]
@benoitdm-oslandia want to deal with this ?

**Comment by strk** [comment]
My version of the fix: https://github.com/qgis/QGIS/pull/57323
tests from original reporters are welcome

**Comment by benoitdm-oslandia** [comment]
@strk I will have a look asap

**Comment by PeterDrexel** [comment]
Sorry for the late feedback: Its fine now again, thank you very much for fixing it!
Peter
