### ISSUE TITLE
Mrge vector layer wrong result in modeller

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#56559]
### What is the bug or the crash?

Merging two vector layers in the modeller returns a results that is different if the the operation is done without the modeller.

### Steps to reproduce the issue

[bug_merge.zip](https://github.com/qgis/QGIS/files/14424686/bug_merge.zip)

The attaches ZIP contains two shapefiles and the offending model.

The two vectors are passed trough the "drop z/m values" before merging.

With the modeler:

![image](https://github.com/qgis/QGIS/assets/1951107/058dba5f-4ab5-442c-8459-5eb0256c37d6)

without:

![image](https://github.com/qgis/QGIS/assets/1951107/be39369e-6c60-4976-8957-dd78050bfa80)

### Versions

QGIS 3.281.5 and 3.34.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @gioman, it seems to me the "Merge vector layers" algorithm in the model is incorrectly set. It looks like `LAYERS` ("Input layers") parameter is set to the output of "Tornar 2d urbano" and the `CRS` ("Destination CRS") parameter is set to the output of "Tornar 2d rustico"

![image](https://github.com/qgis/QGIS/assets/16253859/1be66a70-238f-42cb-9d36-a203e80f1dbf)
```
Running Merge áreas urbanas e rustivas [3/3]
Input Parameters:
{ CRS: 'memory://MultiPolygon?crs=EPSG:5015&field=fid_1:double(18,11)&field=POVOAMENTO:string(50,0)&field=COD_:string(50,0)&field=S_EXISTENT:string(150,0)&field=Shape_Leng:double(18,11)&field=Shape_Area:double(18,11)&field=SituacaoEx:string(50,0)&uid={f9d5c667-e28b-46a8-999e-36f9e454869d}', LAYERS: ['memory://MultiPolygon?crs=EPSG:5015&field=fid_1:double(18,11)&field=OBJECTID:double(18,11)&field=S_EXISTENT:string(254,0)&field=FONTE:string(30,0)&field=Shape_Leng:double(18,11)&field=Shape_Area:double(18,11)&field=SituacaoEx:string(50,0)&uid={584a2907-c23b-4cde-9254-7d7153ac3a9e}'], OUTPUT: 'TEMPORARY_OUTPUT' }
```


This means that only the output of "Tornar 2d urbano" is merged.

You need to set both the output of "Tornar 2d urbano" the output of "Tornar 2d rustico" in the `LAYERS` ("Input layers") parameter of the "Merge vector layers" algorithm.

See https://gis.stackexchange.com/questions/394525/merging-multiple-temporal-inputs-in-qgis-graphical-modeler.
