### ISSUE TITLE
Bug in TIN interpolation

### ISSUE THREAD

**Issue by ezdanapak** [qgis/QGIS#56556]
### What is the bug or the crash?

When I interpolated the TIN from isolines in version 3.4 of QGIS, it looked very nice visually. However, when I use any newer version, it seems awful.
I have tried using other isolines, and the result is the same: you can identify every pixel, and it shows values, but a categorized and classified TIN shows only white pixels.
The results vary; sometimes the north part is visualized normally, but the south is affected. From another viewpoint, you can't guess how the result is generated.
![S1_chiatura3_4v](https://github.com/qgis/QGIS/assets/36360197/52c1f69d-510c-4d45-94f3-cc48deb35123)
![S2_chiatura3_4v](https://github.com/qgis/QGIS/assets/36360197/000444f6-f32a-4b46-bd28-c1befa9e772b)
![S2_TIN_topo_3_4v](https://github.com/qgis/QGIS/assets/36360197/aeffd872-72ac-4aa6-a5ea-8ced14fd02c1)
![S3_TIN_topo_3_4v](https://github.com/qgis/QGIS/assets/36360197/68abfb06-191b-4eb8-8c78-82c101419351)
![S4_chiatura_3_34v](https://github.com/qgis/QGIS/assets/36360197/3787915b-7393-49e4-9be8-83a4009ff147)

### Steps to reproduce the issue

Used tool is from toolbox 
Interpolation > TIN interpolation

### Versions

QGIS 3.4.15 - Madeira
QGIS 3.X ; example 3.28 or 3.34...

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ezdanapak, thanks for reporting. Please provide e sample layer and the parameters used with the processing algorithm.
It is not clear to me if you think the processing algorithm's output raster is incorrectly created or is incorrectly displayed. May you please clarify it?

**Comment by ezdanapak** [comment]
> @ezdanapak, thanks for reporting. Please provide e sample layer and the parameters used with the processing algorithm. It is not clear to me if you think the processing algorithm's output raster is incorrectly created or is incorrectly displayed. May you please clarify it?

I zipped files, you can check. There is one screenshot, : interpolate attribute, Type, Extent, Pixel size, output...
After Windows I tried to use the same data, tool on newer version on linux, unfortunately  output raster is incorrectly displayed when you use render type Unique values with color ramp and classify button
[topo.zip](https://github.com/qgis/QGIS/files/14470593/topo.zip)

**Comment by agiudiceandrea** [comment]
@ezdanapak, the provided raster file is Float64 grid raster containing more than 170 thousands unique floating points cells values. QGIS can only handle 65536 unique values (you can see le warning in the Log Messages panel).
Anyway, what's the point to render a raster with continuous cells values and more than 170 thousands unique cells values as a "Paletted/Unique value"?
I think you could either reclassify the raster to a lower number of classes or use the "Singleband pseudocolor" render type which is suitable for a raster with continuous cells values.

The raster created by the "TIN interpolation" algorithm using QGIS 3.4 is the same as the one created using QGIS 3.28 or QGIS 3.34. Anyway QGIS 3.4 displays the raster incorrectly creating the unique values list as integer values instead of floating point values, thus reducing the number of classes to about 1700 and thus actually not rendering it as "Paletted/Unique value" since the values displayed are not unique.

So, it seems to me the issue is in a limitation of the raster layer symbology rendering, rather then in the "TIN interpolation" processing algorithm.

**Comment by ezdanapak** [comment]
> @ezdanapak, the provided raster file is Float64 grid raster containing more than 170 thousands unique floating points cells values. QGIS can only handle 65536 unique values (you can see le warning in the Log Messages panel). Anyway, what's the point to render a raster with continuous cells values and more than 170 thousands unique cells values as a "Paletted/Unique value"? I think you could either reclassify the raster to a lower number of classes or use the "Singleband pseudocolor" render type which is suitable for a raster with continuous cells values.
> 
> The raster created by the "TIN interpolation" algorithm using QGIS 3.4 is the same as the one created using QGIS 3.28 or QGIS 3.34. Anyway QGIS 3.4 displays the raster incorrectly creating the unique values list as integer values instead of floating point values, thus reducing the number of classes to about 1700 and thus actually not rendering it as "Paletted/Unique value" since the values displayed are not the cells values actually in the raster.
> 
> So, it seems to me the issue is in a limitation of the raster layer symbology rendering, rather then in the "TIN interpolation" processing algorithm.
> 
> Does it make sense to you?

Can I change the number of unique values for mechanical limitations from 65536?

What if I have more classes and I can't categorize them?
If not, that's okay. Thank you."

**Comment by agiudiceandrea** [comment]
> Can I change the number of unique values for mechanical limitations from 65536?
> What if I have more classes and I can't categorize them? If not, that's okay. Thank you."

May you provide a case in which more than 65536 classes are needed?

**Comment by ezdanapak** [comment]
> > Can I change the number of unique values for mechanical limitations from 65536?
> > What if I have more classes and I can't categorize them? If not, that's okay. Thank you."
> 
> May you provide a case in which more than 65536 classes are needed?

![2024-03-18_112352](https://github.com/qgis/QGIS/assets/36360197/a989f540-e591-40b4-8717-524b0576209b)
I can do the same in ArcMAP, I thought that may be QGIS has this option.
