### ISSUE TITLE
Crash when exporting to .gpkg format

### ISSUE THREAD

**Issue by Mmito24** [qgis/QGIS#56563]
## User Feedback

I was doing an export in .pkgk format when the crash happened

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x0001bcc8 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

CPLODBCDriverInstaller::RemoveDriver :
QgsVectorFileWriter::writeFeature :
QgsVectorFileWriter::addFeatureWithStyle :
QgsVectorFileWriter::writeAsVectorFormatV2 :
QgsVectorFileWriterTask::run :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.8-Firenze
QGIS code revision: 5ac45272b5
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 6.3.9600

### Steps to reproduce the issue

1. I had a dot layer and a vector layer
2. I joined some fields of the dot layer to the vector layer
3. I tried to export the resultant vector layer into .gpkg by doing right click over the vector layer and then selecting "export" and .gpkg format.
4. A few minutes after started the export, the "QGIS ended unexpectedly" appeared, asking me to send the report.

### Versions

Versión de QGIS
3.28.8-Firenze
Revisión del código de QGIS
5ac45272b5
Versión Qt
5.15.3
Versión de Python
3.9.5
Versión de GDAL/OGR
3.7.0
Versión de PROJ
9.2.1
Versión del registro de base de datos EPSG
v10.088 (2023-05-13)
Versión de GEOS
3.11.2-CAPI-1.17.2
Versión de SQLite
3.41.1
Versión de PDAL
2.5.3
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.0.1
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.1
Versión del SO
Windows Server 2012 R2 Version 6.3 (Build 9600)

Complementos activos de Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Mmito24, thanks for reporting. QGIS 3.28 is no longer supported. Please try if the issue does occur using a currently supported version and using a new QGIS user profile. It would be useful if you could provide the project and layers and exact steps and parameters with which the issue occurs.

**Comment by Mmito24** [comment]
Ok, thank you Andrea. I will install another QGIS version then
