### ISSUE TITLE
No geometries loaded by WFS 2.0 service

### ISSUE THREAD

**Issue by coefficient1900** [qgis/QGIS#56589]
### What is the bug or the crash?

Using a WFS 2.0 connection from specific German state geoservices (e. g. the bavarian digital land model: https://geoservices.bayern.de/wfs/v1/ogc_atkis_basisdlm.cgi?) returns only the attribute tables of the specific layers. No geometries are received and therefore the map canvas remains empty.
(With the older plugin "WFS 2.0 client", the WFS server delivers geometries too.)

### Steps to reproduce the issue

1. Establish the open source WFS connection (type: 2.0)

<img width="1639" alt="wfs" src="https://github.com/qgis/QGIS/assets/86417466/b3e527ea-2de9-4df9-ab4a-1598ca4d6e18">

2. When everything is loaded,

<img width="1647" alt="wfs1" src="https://github.com/qgis/QGIS/assets/86417466/de54d78e-0455-4047-ac32-3f6759cf844a">

try to add some features from the layer tree. Only the attribute tables are loaded, no geometries.

<img width="1699" alt="wfs3" src="https://github.com/qgis/QGIS/assets/86417466/f970cdbc-6e92-4d3d-9fc6-332ea1dba104">

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.0-Maidenhead | QGIS code revision | 09951dc0
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
qfieldsync | v4.2.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.0-Maidenhead
QGIS code revision
[09951dc0](https://github.com/qgis/QGIS/commit/09951dc0)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
qfieldsync
v4.2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

With QGIS 3.28.15 same issue. Also tried on different MS Windows machines (Win 10 and 11).

Could it be linked to this issue: https://github.com/qgis/QGIS/issues/54942 ?

**Comment by rouault** [comment]
https://geoservices.bayern.de/wfs/v1/ogc_atkis_basisdlm.cgi?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=2.0.0&TYPENAMES=adv:AX_Friedhof&NAMESPACES=xmlns(adv,http://www.adv-online.de/namespaces/adv/gid/7.1)&TYPENAME=adv:AX_Friedhof&NAMESPACE=xmlns(adv,http://www.adv-online.de/namespaces/adv/gid/7.1)

returns

```xml
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema" xmlns:adv="http://www.adv-online.de/namespaces/adv/gid/7.1" xmlns:gco="http://www.isotc211.org/2005/gco" xmlns:gmd="http://www.isotc211.org/2005/gmd" xmlns:gml="http://www.opengis.net/gml/3.2" targetNamespace="http://www.adv-online.de/namespaces/adv/gid/7.1" elementFormDefault="qualified">
  <import namespace="http://www.isotc211.org/2005/gco" schemaLocation="http://schemas.opengis.net/iso/19139/20070417/gco/gco.xsd" />
  <import namespace="http://www.isotc211.org/2005/gmd" schemaLocation="http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd" />
  <import namespace="http://www.opengis.net/gml/3.2" schemaLocation="http://schemas.opengis.net/gml/3.2.1/gml.xsd" />
  <element name="AX_Friedhof" substitutionGroup="adv:AX_TatsaechlicheNutzung" type="adv:AX_FriedhofType" />
  <complexType name="AX_FriedhofType">
    <complexContent>
      <extension base="adv:AX_TatsaechlicheNutzungType">
        <sequence>
          <element minOccurs="0" name="funktion" type="adv:AX_Funktion_FriedhofType" />
          <element minOccurs="0" name="name" type="string" />
          <element minOccurs="0" name="zustand" type="adv:AX_Zustand_FriedhofType" />
        </sequence>
      </extension>
    </complexContent>
  </complexType>
</schema>
```

This schema lacks a include directive where to find the schemas for elements in the "adv" namespace. This should be reported to the organization providing that service

QGIS since 3.36 has two modes:
- the old mode where it just looks at the DescribeFeatureType response without following the include chains. Here we are out of luck because the AX_FriedhofType has no explicit geometry element (it is likely defined in the base AX_TatsaechlicheNutzungType type)
- the new mode introduced in 3.36 that fully analyzes the schema, including resolving deep chains of include. However that implies that all schemas are properly linked, which is not the case here.

Nothing we can easily fix on QGIS side. The issue must be resolved by the responsible of the service

**Comment by coefficient1900** [comment]
Feedback of the service provider: The underlaying database scheme of this WFS service is too complex to get represented correctly.

**Comment by rouault** [comment]
> The underlaying database scheme of this WFS service is too complex to get represented correctly.

That's a joke, isn't it? Why on earth are they using (censoring swear word) XML schemas if they don't do the exercice completely???

**Comment by coefficient1900** [comment]
I will give it another try and ask them exactly this but I do not think, they will get the job done. They are not willing to do so and - I guess - they don't know, how to do it correctly. That is the administration in certain German states. Sad but the truth.
Sorry so far.

**Comment by pathmapper** [comment]
@coefficient1900 you could mention the corresponding WFS of the state of North Rhine-Westphalia (NRW) as an example how to do it: https://www.wfs.nrw.de/geobasis/wfs_nw_atkis-basis-dlm_aaa-modell-basiert


![image](https://github.com/qgis/QGIS/assets/20856381/a8824732-47b8-49f8-8bf0-c3cf9d0b7e02)


https://www.wfs.nrw.de/geobasis/wfs_nw_atkis-basis-dlm_aaa-modell-basiert?SERVICE=WFS&REQUEST=DescribeFeatureType&VERSION=2.0.0&TYPENAMES=adv:AX_Friedhof&NAMESPACES=xmlns(adv,http://www.adv-online.de/namespaces/adv/gid/7.1)&TYPENAME=adv:AX_Friedhof&NAMESPACE=xmlns(adv,http://www.adv-online.de/namespaces/adv/gid/7.1)

**Comment by JuergenWeichand** [comment]
> This schema lacks a include directive where to find the schemas for elements in the "adv" namespace. This should be reported to the organization providing that service
> 
> QGIS since 3.36 has two modes:
> 
>     * the old mode where it just looks at the DescribeFeatureType response without following the include chains. Here we are out of luck because the AX_FriedhofType has no explicit geometry element (it is likely defined in the base AX_TatsaechlicheNutzungType type)
> 
>     * the new mode introduced in 3.36 that fully analyzes the schema, including resolving deep chains of include. However that implies that all schemas are properly linked, which is not the case here.
> 
> 
> Nothing we can easily fix on QGIS side. The issue must be resolved by the responsible of the service.

WFS is fixed. Thanks @rouault
