### ISSUE TITLE
Color ramp show abnormality existing in early version when two version QGIS installed 

### ISSUE THREAD

**Issue by yanshiwei2020** [qgis/QGIS#56580]
### What is the bug or the crash?

Color ramp show abnormality existing in early version when two version QGIS installed 
![color ramp](https://github.com/qgis/QGIS/assets/72858003/bc92dabe-106c-4c17-9ece-841963cc8d64)

### Steps to reproduce the issue

1.install one version such as QGIS 3.32，All functions run well
2.install early version such as QGIS 3.22,the color ramp can not show integrally under the 'symbology' option in the 'Layer Properties' 
3.while the higher version's function run well 
4.reinstallation,alternative version repalcement can not fix it

### Versions

two different version existing in one computer,any early version's color ramp show abnormality

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
If you create a new profile, it should be okay.

Backward compatibility is not supported by QGIS (if it works, it's more luke than a feature).
