### ISSUE TITLE
crash related to the attribute table

### ISSUE THREAD

**Issue by filippofratini** [qgis/QGIS#56582]
### What is the bug or the crash?

When I try to convert geographic coordinates from the attribute table using the following formula y(transform($geometry,'EPSG:32633','EPSG:4326'))  the programme closes.
I had the same problem with both QGIS 3.30 and the 3.28 version. A colleague of mine doesn't have similar problems using another pc. Do you have suggestions?

### Steps to reproduce the issue

![Screenshot_20240228_085422_Studio](https://github.com/qgis/QGIS/assets/161570845/a9ba5b12-99e1-427b-a826-a28da7fd78a4)

### Versions

QGIS 3.30 and the 3.28 version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@filippofratini, thanks for reporting. Please provide a sample layer with which the issue occurs.
