### ISSUE TITLE
crash when opening a project (not empty)

### ISSUE THREAD

**Issue by virgigin91** [qgis/QGIS#56583]
### What is the bug or the crash?

QGIS crashes when I try to open two existing projects I have to work on. I tried dragging the file and opening through the "open project" icon, but crashed anyway.

### Steps to reproduce the issue

Click on "open project", select project file from the a selected folder, QGIS crashes
or
Drag project file to QGIS, it crashes

### Versions

Version 3.36.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
@virgigin91 We'd need that you attach both the project and the data source files it may reference to this ticket

**Comment by virgigin91** [comment]
Hello,

Unfortunately, I can’t as it’s a project from work and I’m not allowed to share information.
