### ISSUE TITLE
Perpendicular snap in advanced digitising act strange

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#56593]
### What is the bug or the crash?

I need to draw two nodes on a line before perpendicular snap can be used/accessed.

I do have the QAD plugin that have better snap but it would be nice if the default snap tool worked right.

### Steps to reproduce the issue

Try it

### Versions

3.34 and 3.36

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Lovely software otherwise!

**Comment by uclaros** [comment]
> Try it

Would you mind elaborating a bit? Describing the steps as well as what should be the correct behavior greatly increases the chances of someone fixing this!
