### ISSUE TITLE
Crash on "Save As"

### ISSUE THREAD

**Issue by CCPAirborne** [qgis/QGIS#56607]
### What is the bug or the crash?

QGIS will open and view an existing project but will crash when the Save As dialog is opened.

## User Feedback

This error occurs when the Save As dialog is opened. When first opened, the round blue "working" icon appears, then disappears as the app freezes.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x000045c0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

RtlpFreeHeapInternal :
RtlFreeHeap :
free free.c:51
DllUnregisterServer :
DllUnregisterServer :
CServerContextActivator::CreateInstance actvator.cxx:881
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CApartmentActivator::CreateInstance actvator.cxx:2189
CProcessActivator::CCICallback actvator.cxx:1640
CProcessActivator::AttemptActivation actvator.cxx:1527
CProcessActivator::ActivateByContext actvator.cxx:1371
CProcessActivator::CreateInstance actvator.cxx:1271
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
CClientContextActivator::CreateInstance actvator.cxx:570
ActivationPropertiesIn::DelegateCreateInstance actprops.cxx:1983
ICoCreateInstanceEx objact.cxx:2032
CComActivator::DoCreateInstance immact.hxx:392
CoCreateInstance actapi.cxx:121
_SHCoCreateInstance :
CreateAndCacheIconOverlay :
CFSIconOverlayManager::GetOverlayIconInformation :
CFSIconOverlayManager::LoadIconOverlayIdentifiers :
CFSIconOverlayManager::_s_LoadIconOverlayIdentifiers :
CFSIconOverlayManager::LoadNonloadedOverlayIdentifiers :
EnableExternalOverlayIdentifiers :
CFSIconOverlayManager::GetFileOverlayInfo :
CFSFolder::_GetOverlayInfo :
CNscOverlayTask::_Extract :
CNscOverlayTask::InternalResumeRT :
CRunnableTask::Run :
CShellTask::TT_Run :
CShellTaskThread::ThreadProc :
CShellTaskThread::s_ThreadProc :
ExecuteWorkItemThreadProc :
RtlpTpWorkCallback :
TppWorkerThread :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.4-Prizren
QGIS code revision: decd43dc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

1. Open app to create new project
2. Click Save As to save and name the project
3. app crashes

### Versions

Same result in 3.28 and 3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@CCPAirborne, thanks for reporting. Please provide details on how you installed QGIS on your system and please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).

**Comment by dimatr** [comment]
Remove "Dell Backup and Recovery" utility, as it causes many Qt apps to crash. See https://github.com/qgis/QGIS/issues/59126

More tech details here
https://www.dell.com/community/en/conversations/productivity-software/backup-and-recovery-causing-applications-using-qt5-dlls-to-crash/647f54c6f4ccf8a8dee57b89
