### ISSUE TITLE
cesium ion plugin can not be working on version 3.36.

### ISSUE THREAD

**Issue by sendreams** [qgis/QGIS#56637]
### What is the bug or the crash?

while installed cesium ion plugin, show the error "TypeError: invalid result from CesiumIonDataItemProvider.capabilities(), int cannot be converted to qgis._core.DataItemProviderCapabilities in this context"

### Steps to reproduce the issue

1、plugin - install plugin
2、install "cesium ion " plugin
3、 click configration 
4、type password
5、reopen qgis and show error.

### Versions

3.36
windows 10

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@sendreams , thanks for reporting. This issue tracker is for QGIS bug reports not related to a third party plugin.
Since the issue concerns a third party plugin, then please raise your issue in the dedicated bug tracker for that specific plugin (as listed in the plugin's description).
