### ISSUE TITLE
 QGIS version 3.34.4-Prizren

### ISSUE THREAD

**Issue by batobolg** [qgis/QGIS#56636]
### What is the bug or the crash?

I just download  QGIS version 3.34.4-Prizren and it got this error, 
Couldn't load plugin 'DigitizingTools' due to an error when calling its initGui() method TypeError: QgsRubberBand(): argument 2 has unexpected type 'bool'

then I refer this site
https://gis.stackexchange.com/questions/455784/typeerror-qgsrubberband-argument-2-has-unexpected-type-bool
temporary fixed it, the files is blow.
vi "/Users/bato/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools/dtmovesidebydistance.py"
vi "/Users/bato/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools/dttools.py"
vi "/Users/bato/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools/dtmovesidebyarea.py"
vi "/Users/bato/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools/dtmovesidebyarea.py"

### Steps to reproduce the issue

when just start qgis

### Versions

 QGIS version 3.34.4-Prizren

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
This is related to a plugin not QGIS itself.
Report on issue tracker linked on the plugin page

**Comment by batobolg** [comment]
Just update plugin will be OK
