### ISSUE TITLE
Unicode text is not rendered properly.

### ISSUE THREAD

**Issue by nabazgharib** [qgis/QGIS#56645]
### What is the bug or the crash?

Hi all,
I created a new layer, and some Unicode Kurdish texts, but when I label the feature using the field that contains the text, the text is not rendered properly. It is rendered inbackward and every letter is rendered separately.
This is the text on 
QGIS version
3.36.0-Maidenhead
![image](https://github.com/qgis/QGIS/assets/4522358/2e47bb91-dc5d-4603-9a99-caefb456b084)

This is same layer on :
QGIS version
3.34.4-Prizren
![image](https://github.com/qgis/QGIS/assets/4522358/bdd2167f-68e2-4e0e-894b-44ad44072519)

The correct display of the text should like this:
![image](https://github.com/qgis/QGIS/assets/4522358/8693547d-ca0c-43d1-9388-f730ac08f72e)

### Steps to reproduce the issue

1. I attached the file contains the text.
2. Added the layer to a map
3. label the layer by **name** field
This font on Google support the Unicode Kurdish text. you can try it with this font.
https://fonts.google.com/selection?query=nas

### Versions

same issue on both version:

QGIS version
3.34.4-Prizren

QGIS version
3.36.0-Maidenhead

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I created a file for the test, you can try test it on this layer.
[Unicode_layer_test.zip](https://github.com/qgis/QGIS/files/14470363/Unicode_layer_test.zip)

**Comment by agiudiceandrea** [comment]
@nabazgharib, thanks for reporting. It looks like you are experiencing an issue already previously reported at https://github.com/qgis/QGIS/issues/54098. You can mitigate the issue using a workaround described at https://github.com/qgis/QGIS/issues/54098#issuecomment-1968600152.

**Comment by nabazgharib** [comment]
> @nabazgharib, thanks for reporting. It looks like you are experiencing an issue already previously reported at #54098. You can mitigate the issue using a workaround described at [#54098 (comment)](https://github.com/qgis/QGIS/issues/54098#issuecomment-1968600152).

Thanks you for your reply, the solution works when the placement is horizontal, but when **changed to curve** the issue pops up. Hope it is fixed in the next update.
labels are one of the crucial elements of making a good map. So please fix this issue because it affects the visual of the maps.
