### ISSUE TITLE
NNJoin Crashed QGIS

### ISSUE THREAD

**Issue by piecesofeveryday** [qgis/QGIS#56665]
### What is the bug or the crash?

Hi, 

When NNJoin is used and run, it crashed QGIS and i am unable to proceed. 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000017bc (most recent call first):
  File "C:\Users/65850/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\NNJoin\NNJoin_plugin.py", line 177 in run
    self.dlg.exec_()
```

**Stack Trace**

```

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit_QtWidgets :
PyObject_Str :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyObject_GC_Del :
PyVectorcall_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.3-Prizren
QGIS code revision: 47373234ac
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Versions

[QGIS 3.34]

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tried to use NNJOin plugin but keeps crashing.

**Comment by rouault** [comment]
Issues with plugins should be reported to the issue tracker of the specific plugin. Looking quiclly at https://github.com/havatv/qgisnnjoinplugin/issues , it seems to be the same as the already reported https://github.com/havatv/qgisnnjoinplugin/issues/35 . Closing as not as QGIS (core) bug
