### ISSUE TITLE
Missing values (NULL) incorrectly handed in Statistics Panel

### ISSUE THREAD

**Issue by colemanjj** [qgis/QGIS#56675]
### What is the bug or the crash?

The Statistics Panel (accessible from the summation button) does not seem to recognize NULL values. I have a layer with about 10% NULL values but the Statistics Panel reports "Missing (null) values" as 0. I don't think this is a problem with the specific QGIS version because I've seen this in previous versions but didn't dig into it. The "Basic Statistics for fields" Processing Toolbox routine does correctly recognize and report those NULL values. See screen shots of the two differing results.
![Qgis-NULL_Capture2a](https://github.com/qgis/QGIS/assets/45085414/d7085dd6-ce3e-452e-acde-61cf10261208)

![Qgis-NULL_Capture2](https://github.com/qgis/QGIS/assets/45085414/3882df58-0002-4747-b2d8-95cf8659f8b1)

attached a example shapefile that shows the problem.
[STAND_AGE_Cheat.zip](https://github.com/qgis/QGIS/files/14474985/STAND_AGE_Cheat.zip)

### Steps to reproduce the issue

Load shapefile with at last one numeric field. Us the "Statistics Panel", available from the "Show Statistical Summary" button available in the "Attributes Toolbar".
Calculate statistics on a numeric field that has some NULL values. Statistics Panel will show zero null values

### Versions

3.36.0-Maidenhead

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I posted the issue at:  https://gis.stackexchange.com/questions/477858/missing-values-null-handling-in-qgis-statistics-panel
Other user confirmed the problem

**Comment by agiudiceandrea** [comment]
@colemanjj, thanks for reporting. A patch has just been proposed to fix the issue. See https://github.com/qgis/QGIS/pull/56688.

**Comment by colemanjj** [comment]
@agiudiceandrea Wow. Thanks for the quick response.  Love the Statistics Panel because it is so easy to use. I will go back to using it.

**Comment by colemanjj** [comment]
I just re-installed 3.36.1 from https://download.osgeo.org with osgeo4w-setup.exe and error is still there. Where and when would I find the fixed version of 3.36.1?  thanks

**Comment by agiudiceandrea** [comment]
@colemanjj, QGIS 3.36.1 is not yet available. QGIS 3.36.1 will be available towards the end of March as you can see at https://www.qgis.org/en/site/getinvolved/development/roadmap.html.
You can test the fix using the QGIS 3.36 developer version (qgis-rel-dev-full package through the OSGeo4W setup).
