### ISSUE TITLE
Snapping on segment does not create topological points to all layers

### ISSUE THREAD

**Issue by vaahtokarkki** [qgis/QGIS#56689]
### What is the bug or the crash?

When snapping is enabled for all layers, digitizing a new feature with vertex tool does not create topological points for all layers, if the snapped segment is shared by multiple layers:
![qgis](https://github.com/qgis/QGIS/assets/12064374/4ba06524-e26e-4b01-bd8f-3a270e4e7982)

### Steps to reproduce the issue

- Open [snapping.zip](https://github.com/qgis/QGIS/files/14479443/snapping.zip) project (open from - geopackage)
- Enable editing for all three layers
- Make sure topological editing is enabled
- Make sure snapping on segment and all layers is enabled
- Digitize new feature for line layer
  - Snap to the shared boundary of both polygons
- Topological point is created only for feature in polygon 1 layer

### Versions
<details>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.0-Maidenhead | QGIS code revision | 09951dc0
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.0-Maidenhead
QGIS code revision
[09951dc0](https://github.com/qgis/QGIS/commit/09951dc0)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
</details>

<details>
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.1-Prizren | QGIS code revision | 133927424d
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.5
GDAL/OGR version | 3.8.0
PROJ version | 9.3.0
EPSG Registry database version | v10.094 (2023-08-08)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 15.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.1-Prizren
QGIS code revision
[133927424d](https://github.com/qgis/QGIS/commit/133927424d)
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.0
PROJ version
9.3.0
EPSG Registry database version
v10.094 (2023-08-08)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
15.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by JuhoErvasti** [comment]
I noticed another related issue; if you're trying to edit only one of the layers and it has overlapping segments with the other layer the topological point is added to neither one of them since it is only added to the snapped layer (see #37824).

![topobug](https://github.com/qgis/QGIS/assets/118284595/4e7aee17-6ce7-4067-8376-04fe93872e46)

The order in which layers are snapped to seems to be dependent on the order in the layer panel.
