### ISSUE TITLE
Attribute/Processing Issues When Saving

### ISSUE THREAD

**Issue by NickWavve** [qgis/QGIS#56699]
### What is the bug or the crash?

While trying to clean some bathymetric data I begun experiencing many challenges within QGIS. I ran into what I believe was a bug with the attribute table in QGIS in 3.24.1. If I extracted certain individual contour values as scratch layers, they would have a value in the attribute table. However, as soon as I went ahead and saved it, the value would disappear like this:
![image](https://github.com/qgis/QGIS/assets/120218025/ea092f57-2611-4268-9fa4-8d50312af035)
If I went back and tried to to add a value with the 'Field' calculator, QGIS would eventually crash and the value wouldn't save.

I figured this was an older QGIS version, so I went ahead and updated to 3.36.0 and faced a new set of issues. First, I tried to load some layers I created in 3.24 and received a 'Invalid Data Source' error message. I went ahead and reprocessed some of the data in 3.36. The layers that were giving me attribute issues previously were completely functional in 3.36 and the attribute data loaded even as a saved layer - I thought my issue was solved here. However, if I try to process these layers as temporary scratch layers then save, it fails to do so and gives a 'Repair Data Source' error.
![image](https://github.com/qgis/QGIS/assets/120218025/831b4dee-d775-4c84-badd-8a824cab5e8d)
The log message doesn't provide any errors:
![image](https://github.com/qgis/QGIS/assets/120218025/fb9b21ae-958e-4803-9c3f-e4fcf454bac9)

The output also is added to the specified file path and I am able to open/read the output file without issues. The only message I see is the 'Repair Data Source' error message beside the layer itself. And as soon as it saves the layer becomes invalid, it doesn't render, I can't open the attribute table, etc.
![image](https://github.com/qgis/QGIS/assets/120218025/0227cc04-29b2-431f-bbeb-fb327e624ab8)
![image](https://github.com/qgis/QGIS/assets/120218025/4a11eb33-85c5-43bc-9d1f-bac9ab82a00c)

Note: As scratch layers, the data visually processes as expected within QGIS, but any effort to save it seems to corrupt the data. This issue also only occurs for select layers within the dataset, some layers can be processed (merge, difference, saved) process where others result in the behavior described above.

### Steps to reproduce the issue

**Cleaning Process - High Level**
I took my dataset and followed the below steps:

1. Identify and fix any dangles within the dataset
2. 'Lines to Polygon' the data
3. Dissolve (by contour value)

Then since these polygons all overlap, I merge then execute the difference of each contour (this is where I run into issues).

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
dissect_dissolve_overlaps
0.3
osminfo
0.8.1
QuickOSM
2.2.3
quick_map_services
0.19.34
SelectWithin
0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@NickWavve , thanks for reportimg. Please try if the issue occurs also using a new QGIS user profile. If it does, please provide a sample layer and detailed steps to replicate the issue.

**Comment by NickWavve** [comment]
Hi Andrea,

Thanks for following up! I have created a new QGIS user profile and the
issue still persists. Although it appears to only occur when trying to save
the data as a GeoJSON file. I have attached a link to a .ZIP file where you
can download the sample contour files.

Google Drive Link:
https://drive.google.com/drive/folders/1ofNJlPW30qL8Ts8FK7rNzRKc-JA7Vx-X?usp=sharing

After downloading the files please follow these steps to replicate the
issue:

   1. Load CONTOUR_0 - CONTOUR_500 into QGIS
   2. Open the processing toolbox and select 'Merge Vector Layers'
      1. Tap 'Select All'
      2. Then deselect 'CONTOUR_0'
         1. [image: image.png]
         3. Select 'Run'
   3. Then in the processing toolbox select the 'Difference' tool
      1. Add 'CONTOUR_0' as your input layer
      2. Use the 'Merged' file from step #2 as your overlay layer
         1. [image: image.png]
         3. Select 'Run'
   4. See the output result as a temporary scratch layer - note it renders
   without issue and processes as anticipated.
   5. Save locally as a 'Geojson' file and see the error.
      1. [image: image.png]
      2. Note you can not modify the file after saving it (attribute table,
      etc.)
      3. You are unable to load the file into another QGIS project
      4. If you open the GeoJSON as text there are no issues and file
      appears to save properly
      5. No errors are printed to 'Log Messages' in QGIS

If you repeat the process and save the file as a GeoPackage or Shapefile it
saves and works as expected. In the Google Drive link you will find a
GeoPackage and Shapefile of the processed file. I followed the exact same
steps but just changed the type of file saved and it worked as expected.

I look forward to your response.

Best,

Nick

**Comment by agiudiceandrea** [comment]
@NickWavve, the issue is due to the fact that the resulting layer contains a single feature with a multi-part geometry consisting of about 7 thousands parts and 3 millions points.
The GeoJSON GDAL/OGR driver limits by default the memory dimension of an accepted single feature https://gdal.org/drivers/vector/geojson.html#configuration-options.
Thus, if you want to open such GeoJSON file with QGIS you need remove such limitation setting the OGR_GEOJSON_MAX_OBJ_SIZE environment variable to 0 https://docs.qgis.org/3.34/en/docs/user_manual/introduction/qgis_configuration.html#system-settings.
Otherwise you need to convert the resulting layer to a single-part layer using the "Multipart to singlepart" processing algorithm and then exporting the result to a GeoJSON file which can be opened in QGIS without the need to set the OGR_GEOJSON_MAX_OBJ_SIZE environment variable to 0.
Anyway the GeoJSON format is not suitable for such huge number of vertices to be displayed smoothly since it is a text format without a spatial index.
You have to use a more optimized format with a spatial index like the GeoPackage format in order to properly handle such layer with QGIS.

**Comment by NickWavve** [comment]
Hi again Andrea,

Thank you for this explanation, it is greatly appreciated and I
completely understand the situation now. I apologize for marking this as a
bug,

Rather than removing the limitation by adjusting the environment variables
I went ahead and reprocessed the data using the 'Multipart to singlepart'
tool and as you suggested, the issue I previously experienced did not occur
and the Geojson file was saved properly. I will keep this new information
in mind moving forward and look into a more optimized file format.

Once again, thank you for the prompt reply.

All the best,

Nick
