### ISSUE TITLE
The Point Cloud tools do not show up in the Processing Toolbox

### ISSUE THREAD

**Issue by GISNEWBIE5230** [qgis/QGIS#56712]
### What is the bug or the crash?

There are no point cloud menus showing up in the processing toolbox.  I have tried installing both 3.34 on Mac and Windows machines.  I can bring a .las file into QGIS; however, I lack the processing toolbox functions required the manipulate them into vectors.

### Steps to reproduce the issue

N/A

### Versions

3.34 and 3.36

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
On Mac it's "normal", there is an existing issue about it, please search.

On the opposite, you should have them on windows.
Could you provide more info ?
Windows version ? Did you try with a new QGIS user profile ?
How did you install QGIS (msi or network install) ?

**Comment by GISNEWBIE5230** [comment]
I did a regular install and did try a new user profile on mac and windows.  I managed to get the point cloud menus to show up on windows 10 after uninstalling all previous QGIS versions then reinstalling.

**Comment by nicogodet** [comment]
Can we close ?
