### ISSUE TITLE
Raster (TIF) - endless rendering with resampling bilinear and early resampling

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#56769]
### What is the bug or the crash?

Raster layer never gets rendered with resampling bilinear and early resampling:

![image](https://github.com/qgis/QGIS/assets/20856381/7482914a-a06b-4c9f-b71a-a179fd5248a3)

### Steps to reproduce the issue

1. Drag'n'drop the [test.zip](https://github.com/qgis/QGIS/files/14535073/test.zip) into QGIS.
2. In layer properties, change resampling to bilinear and check early resampling:
<img src="https://github.com/qgis/QGIS/assets/20856381/f484ebc4-74c8-41c1-a2c7-d400866226a6" width="400" />

3. -> endless rendering

### Versions

QGIS version | 3.37.0-Master | QGIS code revision | e5611c91424
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.9.0dev-d7aed6e0b0
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

It may be that the provided TIF is somehow corrupt, when exporting the raster layer as GeoTIFF there are no issues with the resulting file using resampling bilinear and early reampling.

**Comment by elpaso** [comment]
Upstream issue in GDAL. I'll file a bug report.

**Comment by pathmapper** [comment]
Thanks @elpaso

**Comment by pathmapper** [comment]
Fixed upstream (thanks!) in https://github.com/OSGeo/gdal/pull/9428 / https://github.com/OSGeo/gdal/pull/9438, fix available with GDAL 3.8.5
