### ISSUE TITLE
Qgis Update to 3.34.4 and SAGA tools

### ISSUE THREAD

**Issue by Forna73** [qgis/QGIS#56783]
### What is the bug or the crash?

After having update Qgis to version from 3.28.15 to 3.34.4 via Osgeo4W the SAGA tools in processing windows have disappeared....
Looking in plugin manager it shows the SAGAPROVIDER plug in corrupted and can't be reinstalled or updated.
In the Qgis folder I can see 2 versions of SAGA 7.8 and 9.2... I always had only 1...
I reinstalled SAGA via Osgeo4W, trying having only 1 version at time, but nothing change... I also reinstalled the Qgis LTR, but nothing change.

### Steps to reproduce the issue

1. update Qgis via Osgeo4W
2. go in processing
3. if SAGA tools aren't there, check the plugin manager to see SAGA provider plug in corrupted

### Versions

Versione di QGIS
3.28.15-Firenze
Revisione codice QGIS
252ad49ddc
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.3
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
unknown
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
azimuth_distance_measurement
0.4
dimensioning
0.2
latlontools
3.6.19
MagneticDeclination
2.4.4
qgis_points2one
0.3.1
rvt-qgis
0.9.6
zoom_level
0.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Forna73** [comment]
For Job necessities I turned back in 3.28.15... so the log for version shows 3.28.15...

**Comment by agiudiceandrea** [comment]
@Forna73, the SAGA-GIS processing provider core plugin has been removed since QGIS 3.30. See: https://github.com/qgis/QGIS/pull/50834.

**Comment by Forna73** [comment]
So... how to use SAGA tools in processing?
I assume there's something wrong with the installer Osgeo4W if I'm
experiencing this.

Il Sab 9 Mar 2024, 12:10 Andrea Giudiceandrea ***@***.***> ha
scritto:
