### ISSUE TITLE
[sensorthings] follow navigationlinks and add links to attribute table

### ISSUE THREAD

**Issue by pvgenuchten** [qgis/QGIS#56805]
### Feature description

Sensorthings adds to each type (sensor, location, datastream) a set of navigationlinks which enable linkage between the types, actually one needs to follow the link to retrieve the actual identifier of the linked entity, or use the [$expand](https://docs.ogc.org/is/18-088/18-088.html#expand) option on the  query to expand the basic query with additional types. 

```
https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams?$expand=Observations&$top=10
```

Qgis currently does not include these navigation links in the attribute table, which makes it hard to link datastreams to their related location and observations

Some samples:

https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Sensors(15424)
```
{
    "@iot.selfLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Sensors(15424)",
...
    "Datastreams@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Sensors(15424)/Datastreams",
    "MultiDatastreams@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Sensors(15424)/MultiDatastreams"
}
```

https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)

```
{
    "@iot.selfLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)",
...
    "ObservedProperty@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)/ObservedProperty",
    "Sensor@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)/Sensor",
    "Thing@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)/Thing",
    "Observations@iot.navigationLink": "https://airquality-frost.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/Datastreams(19801)/Observations"
}
```

![image](https://github.com/qgis/QGIS/assets/299829/68e1c77d-7b4f-4fad-9c3f-740a7a6f8550)

Suggestion would be to include the navigationlinks as column(s) to the attribute table, either as a json string like the properties snippet, or as an array by link type

### Additional context

[Sensorthings spec](https://docs.ogc.org/is/18-088/18-088.html#usage-address-navigation-property)

This would enable me to add locations, things, datastreams and observations to my project and link them using joins, location has the coordinates, observations contains the actual measured values. I can even use the (latest) value in observation to style the icon of the location.

**Comment by pvgenuchten** [comment]
Other option here would be to enable a multiselect on the Entity type in the sensorthings data source manager

![image](https://github.com/qgis/QGIS/assets/299829/6306863f-d11b-4055-8620-53863224db3c)

QGIS would $expand the query with the selected entity types (which would be the main type?)

The result would be a hierarchical object of the main type and its children, is QGIS able to visualise such a data structure in the attribute table?

The logic behind user selection of main and subtypes is that every sensorthings API is different, some have a focus on feature-of-interest, some on location.

In order to prevent loading the full database it is important to limit the result by filters, or else a max number ($top). Providing user friendly filter options may be challenging, because filters may apply at any level (observation/result > 0, location/geometry within map bounds, observedProperty/name = 'FE')

**Comment by nyalldawson** [comment]
@pvgenuchten this is on it's way for 3.38 :+1:

**Comment by pvgenuchten** [comment]
Nice! Always available to test/share thoughts..

**Comment by sgrellet** [comment]
Thanks Paul for testing and providing this idea, feel free to add some more and spread the word :)

**Comment by pvgenuchten** [comment]
I tested this today on 3.42, it works nicely!
i started from feature of interest, i could expand to datastream and property, but I couldn't expand into things (which has the base properties of the feature-of-interest, such as depth)
I probably should have started from location?
I asked Hylke/Kathi for feedback
