### ISSUE TITLE
QGIS crash when saving rendered image CRS

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#56817]
### What is the bug or the crash?

QGIS crashes when saving a rendered image with a new CRS.

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/21163329/e174200d-da6a-4a13-a67a-75cfe52c2b36)

### Versions

QGIS version
3.34.4-Prizren
QGIS code revision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
grd_loader-main
0.1.1
openlog
1.0.1
processing_saga_nextgen
1.0.0
Qgis2threejs
2.7.3
qgis_resource_sharing
1.1.0-beta1
quick_map_services
0.19.34
SemiAutomaticClassificationPlugin_v7-master
7.10.11
SpreadsheetLayers
2.1.2
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## User Feedback

QGIS crashes when changing the CRS when saving a rendered image in a different projection.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004660 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_context_delete_cpp_context :
proj_as_proj_string :
QgsCoordinateReferenceSystem::geographicCrsAuthId :
QgsCoordinateReferenceSystem::pushRecentCoordinateReferenceSystem :
QgsProjectionSelectionTreeWidget::~QgsProjectionSelectionTreeWidget :
QgsProjectionSelectionTreeWidget::~QgsProjectionSelectionTreeWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsRasterHistogramWidget::QgsRasterHistogramWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMultiBandColorRendererWidget::QgsMultiBandColorRendererWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsMapLayerConfigWidgetFactory::operator= :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsCrsSelectionWidget::~QgsCrsSelectionWidget :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsProjectionSelectionWidget::selectCrs :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::saveAsRasterFile :
QgisApp::saveAsFile :
QgsBookmarksItem::sortKey :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.4-Prizren
QGIS code revision: decd43dc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by agiudiceandrea** [comment]
@grantboxer, thanks for reporting. Please provide a sample layer and exact steps in order to replicate the issue.

**Comment by grantboxer** [comment]
I have tried a new profile and it does not crash. It looks like it might be caused by a plug-in. I will investigate further to see which one might be causing it, but my suspicions are EnMap-box.
Cheers Grant

**Comment by agiudiceandrea** [comment]
@grantboxer, thanks for investigating. Please report the issue to the plugin developers.
