### ISSUE TITLE
labelling

### ISSUE THREAD

**Issue by oussou-toure** [qgis/QGIS#56810]
### What is the bug or the crash?

If I want to display orientation angle labels for line type shapefiles it only displays the angle.
Example when I type '**round ($length,0)  || 'm ' || ' '  ||  coalesce(   round( atan(  ( (  y_at( -1 )  - y_at( 0 ) ) / (  x_at(-1 )  - x_at(0 ) ) ) )  * 200 /  3.14159265358979   , 0 )  || 'gr' , 'vide')**'
output example  **'5/9 41m vide'**

### Steps to reproduce the issue

![input](https://github.com/qgis/QGIS/assets/129565715/0e024315-d6c2-4548-a85d-1b984f8d0ee5)
![outpout](https://github.com/qgis/QGIS/assets/129565715/46c00111-94ca-40db-9905-2140c90a7011)

### Versions

3.34.4-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by oussou-toure** [comment]
why it displays it like that and how to correct it. I need your help urgently.

**Comment by agiudiceandrea** [comment]
@oussou-toure, !questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.!
