### ISSUE TITLE
Print Layout text boxes converted to HTML frame and expressions evaluated when opening projects created in 3.30.3 or earlier.

### ISSUE THREAD

**Issue by laidlaw42** [qgis/QGIS#56813]
### What is the bug or the crash?

When opening projects created in 3.30.3 or earlier in any later version, print layouts that have text box items with _Render as HTML_ enabled are automatically converted into HTML frames with any expressions that were in the text box evaluated.

### Steps to reproduce:

1. Create a print layout in 3.30.3 or earlier
2. Create some text boxes with _Render as HTML_ enabled
3. Enter some data and expressions into the text boxes e.g. Date: [%format_date(now(),'yyyy-MM-dd')%]
4. Save the project
5. Open it in a later version of QGIS
6. Check the print layout's _Items_ panel
7. All text boxes will have <HTML frame> instead text boxes and the expressions entered will be evaluated text instead of the expression code.

The issue persists on a new profile and on multiple machines with new and existing installations of QGIS.

### Screenshots
This is an example project made in 3.30.3:
![qgis-bin_gUbtiej8nA](https://github.com/qgis/QGIS/assets/26688892/fa15449c-5c9d-4ecc-a00c-d00811bab68e)
![qgis-bin_qaKzWL0ESD](https://github.com/qgis/QGIS/assets/26688892/15dea219-a597-4898-9882-c2b4489a2d1e)

This is what happens when you open the project in 3.36.0, but has persisted in all versions after 3.30.3:
![qgis-bin_ZPKISoPOK5](https://github.com/qgis/QGIS/assets/26688892/8b74aead-1649-4a25-b4da-bbcdcddfdc43)
![qgis-bin_0DBGeklUtc](https://github.com/qgis/QGIS/assets/26688892/f47e4272-0ccf-4e69-9c62-3b94feb3b160)

### Workaround
I have a work around but it's impractical. If you uncheck the _Render as HTML_ checkbox for each text box in the print layout, then save the project, and open it in a later version, the text boxes remain text boxes, and then you can re-check _Render as HTML_. However, I'd have to do this four to five times per print layout per project which adds up to ~5000 times for all the projects that this affects. So, if there's a more elegant and simple solution please let me know.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.0-Maidenhead | QGIS code revision | 09951dc0
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
changeDataSource | 3.1
FeatureGridCreator | 3.0.0
Group_and_Sort_Layers | 1.2
icsm_ntv2_transformer | 1.1.1
ImageServerConnector | 2.1.1
ImportPhotos | 3.0.5
InvisibleLayersAndGroups | 2.2
layout_loader | 1.1
layout_panel-main | 0.3
LocatePoints | 0.3.4
mmqgis | 2021.9.10
MultiDistanceBuffer | 3.2.4
Multi_Ring_Buffer | 1.1
pickLayer | 3.9.12
pluginbuilder3 | 3.2.1
project_report | 1.2
qfieldsync | v4.8.1
qgis2web | 3.18.2
qlyrx | 0.3.3
quicksaveqml | 0.1.6
road_slope_calculator | 0.5
shapetools | 3.4.18
slyr_community | 5.0.0
splitmultipart | 1.0.0
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
BackgroundToggler | 0.1

</body></html>QGIS version
3.36.0-Maidenhead
QGIS code revision
[09951dc0](https://github.com/qgis/QGIS/commit/09951dc0)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
FeatureGridCreator
3.0.0
Group_and_Sort_Layers
1.2
icsm_ntv2_transformer
1.1.1
ImageServerConnector
2.1.1
ImportPhotos
3.0.5
InvisibleLayersAndGroups
2.2
layout_loader
1.1
layout_panel-main
0.3
LocatePoints
0.3.4
mmqgis
2021.9.10
MultiDistanceBuffer
3.2.4
Multi_Ring_Buffer
1.1
pickLayer
3.9.12
pluginbuilder3
3.2.1
project_report
1.2
qfieldsync
v4.8.1
qgis2web
3.18.2
qlyrx
0.3.3
quicksaveqml
0.1.6
road_slope_calculator
0.5
shapetools
3.4.18
slyr_community
5.0.0
splitmultipart
1.0.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
BackgroundToggler
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@laidlaw42 , it's not a bug but rather a feature. Starting wiht QGIS 3.32, the label item uses a different engine to render HTML content. It was changed to allow for interactive hyperlink support in HTML-enabled label items when exporting to PDF. While the new engine creates interactive hyperlinks, it does not render content exactly the same as before. That's why we automatically transform those into HTML items, which use the same rendering engine as what label relied on pre 3.32.

That said, if you create an HTML label item in 3.32, it will remain a label item.
