### ISSUE TITLE
Python script set in `PYQGIS_STARTUP` environment variable runs twice

### ISSUE THREAD

**Issue by ostr00000** [qgis/QGIS#56823]
### What is the bug or the crash?

Script configured in`PYQGIS_STARTUP` runs twice if the set path is absolute.
I believe that this initialization script should be called only one time, because it may cause some problems if code in the script cannot be executed twice.
Also, it makes QGIS initialization more complicated to follow by programmer.

### Steps to reproduce the issue

1. Create file `/home/$USER/my_start.py` with content:
    ```python
    print("Running 'my_start' script")
    ```
2. Run QGIS with command `PYQGIS_STARTUP=/home/$USER/my_start.py qgis`.
3. Watch console to see that message from init script shows twice.

### Versions

QGIS version
3.34.3-Prizren
QGIS code revision
47373234acd
Qt version
5.15.3
Python version
3.10.12
Compiled against GDAL/OGR
3.4.1
Running against GDAL/OGR
3.4.3
PROJ version
8.2.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.4 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Problem source
The code that call this script is in https://github.com/qgis/QGIS/blob/3da05d3fc93e52abf593505e4fc66f60a1ba09af/src/python/qgspythonutilsimpl.cpp#L55-L64

As you can see, the script can be called twice. One time it uses explicit path from `pythonPath`. The second time it uses path returned from `os.path.join(pythonPath(), pyqgstart)`. `pythonPath` in Linux is usually `/usr/share/qgis`. `pyqgstart` is the value we provide in environment variable.

What is not obvious at first glance, is that `os.path.join` return unchanged path from the last argument. 
According to [Python docs](https://docs.python.org/3/library/os.path.html#os.path.join):
>  If a segment is an absolute path (which on Windows requires both a drive and a root), then all previous segments are ignored and joining continues from the absolute path segment.

### Fix proposal
I propose to add another condition to check if concatenated path differ from the original one (it was already called, so we can skip it).

### Workaround
There is a possible workaround. We can check in the script if it has already been executed:
```python
import __main__

if not getattr(__main__, 'qgisScriptInitialized' False):
    print("Running 'my_start' script")
    qgisScriptInitialized = True
```

**Comment by agiudiceandrea** [comment]
@ostr00000, thanks for reporting. Are you thinking of proposing a pull request in order to fix the issue?

**Comment by ostr00000** [comment]
Yes, I can do it. 
It should be a very small fix, especially when I tracked down the source of the problem.
