### ISSUE TITLE
Projection page 

### ISSUE THREAD

**Issue by YounessKassbi** [qgis/QGIS#56837]
### What is the bug or the crash?

Affichage de la carte map satellitaire est lent à 5000mm. 
L'exportation de la carte Map ne dépasse pas 5000mm

### Steps to reproduce the issue

Scroll down to see forward. il vaut mieux qu'il y ait une possibilité d'avoir plus que 5000mm de la mise en page QGIS.

### Versions

Lima 3.32.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@YounessKassbi, thanks for reporting. QGIS 3.32 is no longer supported.
Please try if the issue occurs running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please provide:
- an English description with detailed steps to replicate the issue
- a sample project and layer with which the issue occur
- the full QGIS version info: "In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."

**Comment by agiudiceandrea** [comment]
@YounessKassbi, thanks for reporting. QGIS 3.32 is no longer supported.
Please try if the issue occurs running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please provide:
- an English description with detailed steps to replicate the issue
- a sample project and layer with which the issue occur
- the full QGIS version info: "In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."
Please also change the issue report title to a meaningful one.
