### ISSUE TITLE
SensorThings API Provider - Layer name

### ISSUE THREAD

**Issue by sgrellet** [qgis/QGIS#56838]
### What is the bug or the crash?

When adding geospatial layers, the SensorThings Data Provider only name the layer using its geometry type (Point, Line, etc...).

If you add Locations, and Features Of Interest of the same type and/or Locations and FoI from various ST API endpoints, you end up not know knowing which is which based on the sole display of the Table Of Content (see image below).

suggestion : 
1°/ at least prefix the geometry type with the Table name => "Locations_Point"
but this won't work if accessing several ST API endpoints

2°/ add to 1°/ a prefix with the SensorThings Connexion first letters (or a short name)
ex based on my image would then be => "lubw_Locations_Point" and "USGS WQ IE_Locations_Point"

![image](https://github.com/qgis/QGIS/assets/16756304/a5a00c02-2e5e-4a60-b8b7-0bedb49337ce)

### Steps to reproduce the issue

1. connect to a SensorThings endpoint (ex : this one for points https://lubw.k8s.ilt-dmz.iosb.fraunhofer.de/v1.1/)
2. add Point for both "Locations" and "Features of Interest"

### Versions

QGIS 3.36

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Can you confirm that this works as desired from the Data Source Manager? 

I don't think this is a SensorThings specific issue -- rather it's a limitation in the behaviour of adding layers (from any source) via the QGIS browser.

**Comment by sgrellet** [comment]
Indeed, this works fine when going through the Data Source Manager.

![image](https://github.com/qgis/QGIS/assets/16756304/38d39611-8e1b-473e-a8e0-482aa2d7ac88)
