### ISSUE TITLE
Raster temporal extent from filename

### ISSUE THREAD

**Issue by HegerM** [qgis/QGIS#56839]
### Feature description

I have a large number of raster files, each with a year in its filename. It would be great if I could use that filename to dynamically define a temporal extent instead of having to set it manually in the "Temporal" settings for each raster. Somewhat similar to how vector layers support expressions to define the start/end time.

**Comment by saberraz** [comment]
There have been two new features added over the past week:
https://github.com/qgis/QGIS/pull/56902
https://github.com/qgis/QGIS/pull/56900

What you can do, is to merge your files into a single multi-band raster [1] and then assign temporal extent to each band using the new feature to display them as a single raster time series.

[1] `gdalbuildvrt -separate /vsistdout/ first.tif second.tif third.tif|gdal_translate /vsistdin/ merged.tif`

**Comment by HegerM** [comment]
Thanks! That would help somewhat, I can package them into a multi-band raster file for visualization. Unfortunately what I'm dealing with is being used in external code that relies on those rasters being in the single-year, single-band format and I can't mess with that too much.

Maybe I can script it from the console from within QGIS?

**Comment by saberraz** [comment]
Actually thinking about, you do not need to merge them as multi band. You just need to enable this configuration for each raster:
![image](https://github.com/qgis/QGIS/assets/2649047/b1b8f89d-3429-4ca6-adf4-5d961ab61950)

And then using expressions like  `base_file_name` define start and end time. This feature will be available in QGIS 3.38.

I mark this ticket as completed!

**Comment by HegerM** [comment]
Awesome, that you so much!

**Comment by Djedouas** [comment]
@HegerM Same problem here, and interested to know how you dealt with this :-)

Thanks
