### ISSUE TITLE
Frequent crash because of QtWebKit QGIS-LTR 3.34

### ISSUE THREAD

**Issue by dlejay** [qgis/QGIS#56835]
### What is the bug or the crash?

Random crashes happening consistently during work sessions.
The crash report mentions QtWebKit everytime.

Part of my last crash report:
```
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QGIS3-LTR [94924]
Path:                  /Applications/MacPorts/QGIS3-LTR.app/Contents/MacOS/QGIS3-LTR
Identifier:            org.qgis.qgis3
Version:               3.34.4 (3.34.4 (exported))
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-03-13 08:31:08.8651 +0100
OS Version:            macOS 14.4 (23E214)
Report Version:        12
Anonymous UUID:        C524CD6A-9B77-53D0-07F0-5CA1B188086A

Sleep/Wake UUID:       E1ECCB8F-B49A-4EDD-93B0-F1A66AD487DA

Time Awake Since Boot: 210000 seconds
Time Since Wake:       1567 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   exc handler [94924]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4332306424
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10239c000-102400000    [  400K] r-x/r-x SM=COW  /Applications/MacPorts/QGIS3-LTR.app/Contents/MacOS/QGIS3-LTR

Thread 0 Crashed::  Dispatch queue: com.apple.main-thread
0   QtWebKit                      	       0x10d0a1050 JSC::CodeBlock::~CodeBlock() + 84
1   QtWebKit                      	       0x10d15cd08 0x10c37c000 + 14552328
2   QtWebKit                      	       0x10d15c85c 0x10c37c000 + 14551132
3   QtWebKit                      	       0x10d0d1614 JSC::Heap::deleteAllCompiledCode() + 68
4   QtWebKit                      	       0x10d0d0228 0x10c37c000 + 13976104
5   QtWebKit                      	       0x10d15e7f0 0x10c37c000 + 14559216
6   QtWebKit                      	       0x10d0d3b7c 0x10c37c000 + 13990780
7   CoreFoundation                	       0x189335f90 __CFRUNLOOP_IS_CALLING_OUT_TO_A_TIMER_CALLBACK_FUNCTION__ + 32
8   CoreFoundation                	       0x189335c34 __CFRunLoopDoTimer + 972
9   CoreFoundation                	       0x18933576c __CFRunLoopDoTimers + 356
10  CoreFoundation                	       0x189318ba4 __CFRunLoopRun + 1856
11  CoreFoundation                	       0x189317e0c CFRunLoopRunSpecific + 608
12  HIToolbox                     	       0x193ab3000 RunCurrentEventLoopInMode + 292
13  HIToolbox                     	       0x193ab2e3c ReceiveNextEventCommon + 648
14  HIToolbox                     	       0x193ab2b94 _BlockUntilNextEventMatchingListInModeWithFilter + 76
15  AppKit                        	       0x18cb70970 _DPSNextEvent + 660
16  AppKit                        	       0x18d362dec -[NSApplication(NSEventRouting) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 700
17  AppKit                        	       0x18cb63cb8 -[NSApplication run] + 476
18  libqcocoa.dylib               	       0x102621ebc 0x1025f4000 + 188092
19  QtCore                        	       0x10465dd0c QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) + 316
20  QtCore                        	       0x1046603cc QCoreApplication::exec() + 124
21  QGIS3-LTR                     	       0x1023b9cfc main + 19740
22  dyld                          	       0x188eb20e0 start + 2360
```

### Steps to reproduce the issue

The issue arises randomly.

One example: during a work session, click "Manage and Install plugins" → Crash.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.4-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.12
Python version | 3.11.8
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 15.6
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.3
OS version | macOS 14.4
  |   |   |  
Active Python plugins
QuickOSM | 2.2.3
profiletool | 4.2.6
DataPlotly | 4.1.0
layertilesmapcanvas | 1.4
processing_saga_nextgen | 1.0.0
Serval | 3.32.0
rasterdataplotting | 1.6.3
valuetool | 3.0.19
StreetView | 3.2
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.4-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.12
Python version
3.11.8
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
15.6
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.3
OS version
macOS 14.4

Active Python plugins
QuickOSM
2.2.3
profiletool
4.2.6
DataPlotly
4.1.0
layertilesmapcanvas
1.4
processing_saga_nextgen
1.0.0
Serval
3.32.0
rasterdataplotting
1.6.3
valuetool
3.0.19
StreetView
3.2
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Version installed with MacPorts. It gets the missing Python fault handler warning everytime.

```
>port installed | grep qtwebkit

  qt5-qtwebkit @5.9.2_7 (active)

>port installed | grep qgis     

  qgis3-ltr @3.34.4_0+draco+grass+plugin_support311+postgresql15+proj9+python311 (active)
```

**Comment by agiudiceandrea** [comment]
@dlejay , thanks for reporting. Anyway this looks like a MacPorts specific issue. I suggest yuo to report the issue to the MacPorts repository https://ports.macports.org/port/qgis3-ltr/
