### ISSUE TITLE
Project Properties UI Bug, Project Specific

### ISSUE THREAD

**Issue by Lunate-Lance** [qgis/QGIS#56860]
### What is the bug or the crash?

When attempting to change Project CRS, clicking "Apply" redirects to Project Properties - Terrain tab.

### Steps to reproduce the issue

1) Open Project Properties - CRS tab by clicking CRS button at bottom-right of QGIS main window or through main menu Project->Properties
2) Click the "Apply" button.

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
LAStools
2.0.1
processing_saga_nextgen
1.0.0
QuickOSM
2.2.3
rvt-qgis
0.9.6
open_lidar_tools
2.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Lunate-Lance, thanks for reporting. I cannot replicate the described behavior using QGIS 3.36.0 on Windows 10 following the provided steps.
Please try if the issue occurs also using a new QGIS user profile. If it does, please provide more detailed steps to replicate the issue.

**Comment by Lunate-Lance** [comment]
User error. Project Properties->Terrain Type had been changed from "Flat Terrain" to "DEM" unintentionally and without an elevation layer being selected resulted in an error. Once changed to Flat Terrain everything worked as expected.
