### ISSUE TITLE
Georeference option 

### ISSUE THREAD

**Issue by Pratikkk07** [qgis/QGIS#56872]
### Feature description

I have a version of Maidenhead of 3.36.0 and it doesn't have Georeference option in Raster option and also even after searching in Plugins to install still not finding it what should i do now ?

**Comment by agiudiceandrea** [comment]
The start the Georeferencer: Layer ► ![image](https://github.com/qgis/QGIS/assets/16253859/ad09da79-2283-49c9-8421-01a92327c713) Georeferencer.
See https://docs.qgis.org/testing/en/docs/user_manual/working_with_raster/georeferencer.html#usual-procedure.
