### ISSUE TITLE
Parts of the screeen are blank, some superimposed and nothing is actually where they look like on screen

### ISSUE THREAD

**Issue by JPNunes6** [qgis/QGIS#56880]
### What is the bug or the crash?

I spent some time without opening QGIS and now i is behaving like this...
I'm running the LTR version on Ubuntu 22.04 and have tried to reinstall, download different versions, use the one from snapstore and noting changes. I have tried deleting all files related to qgis but the plugins remain so I don't know if they are stored in a different place or if using "sudo apt-get remove --purge" is insufficient to delete all of qgis from your computer
Anyway, I don't know what else to do

### Steps to reproduce the issue

To be honest, I don't know how you could reproduce this. The only plugins I have are acatama, dzetsaka and QuickMapServices. I spent about a month on vacation without using qgis, but I have gone longer without opening it without issue.
Here is what this bug looks like:
![Screenshot from 2024-03-16 00-10-33](https://github.com/qgis/QGIS/assets/163609479/c3bf7235-f804-440a-a62e-a133ddb3624d)
![Screenshot from 2024-03-15 23-26-07](https://github.com/qgis/QGIS/assets/163609479/e4df2af2-5f14-41f9-be01-0434750b425b)
![Screenshot from 2024-03-15 23-25-38](https://github.com/qgis/QGIS/assets/163609479/2faf6dff-ad78-4fc4-bf50-1275f7cececd)
![Screenshot from 2024-03-15 23-25-19](https://github.com/qgis/QGIS/assets/163609479/7efec59c-a28d-4a08-825f-3179dffdd9d4)

### Versions

I con't access the About button, but I'm on 3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@JPNunes6 please try if the issue does occur also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If you cannot access the "Settings-> User Profiles" menu, you can move or rename the <UserProfiles> folder.
You can also try using QGIS from Flatpak https://qgis.org/it/site/forusers/alldownloads.html#flatpak.

**Comment by agiudiceandrea** [comment]
Same question posted at https://www.facebook.com/groups/612486875596534/user/100007117806734/.

**Comment by JPNunes6** [comment]
Thank you very much! Creating a new profile did not solve it, but the Flapjack version is working perfectly!
