### ISSUE TITLE
Export as image (with georef.) feature produce tiff that does not align with base map is taken from

### ISSUE THREAD

**Issue by Dret42** [qgis/QGIS#56882]
### What is the bug or the crash?

Using the "Export as Image" function (under "Project" menu), the TIFF resulting is not aligned with the base map is taken from.

### Steps to reproduce the issue

1) Set a project in **EPSG 32633**,
1) Open an XYZ layer with Google Satellite (or another base map),
2) Create e **temporary poligon layer** and select an area on the map,
3) Under "Project" menu select "Export as Image",
4) Select DPI, Scale and the temporary poligon layer as map extension as exporting options,
5) Start process,
6) File TIFF is created with georef file,
7) Reload TIFF into the project,
8) The TIFF image is not aligned with the below base map.

### Versions

Versione di QGIS
3.34.4-Prizren
Revisione codice QGIS
decd43dc
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.4
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
16.1
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
BezierEditing
version 1.3.8
ImportPhotos
3.0.5
MagneticDeclination
2.4.4
mmqgis
2021.9.10
nominatim
1.4.5
poiexport
3.0.4
profiletool
4.2.6
qgis-maptiler-plugin
3.2
qgis2web
3.18.2
qgis_resource_sharing
1.0.0
QuickOSM
2.2.3
quick_map_services
0.19.34
spline
0.2
TerrainShading
0.9.5
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
kmltools
3.1.32

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Note: If I export the image from base map using the "Export > Save as" layer option the result is well aligned.

**Comment by agiudiceandrea** [comment]
@Dret42 , thanks for reporting. I cannot replicate the described issue. Please provide all the detailed steps, layer and parameters in order to replicate the issue starting from a new QGIS user profile and and a blank project.
Are you using an high-dpi display?

**Comment by Dret42** [comment]
I have some news about my problem:

I tested with a New QGIS User but without success, problem remain.

So I tryed with screen resolution: my laptop resolution is 1920x1080 **BUT** WIN10 set  a **125% enlargement by default** as suggested parameter (without this setting all elements on screen are too small).
I re-set the enlargment to 100% and the problem seems resolved.

The problem is now: how to make QGIS works right with 125% resolution on WIN10 (work at 100% is really impossible!!!)

Any Ideas?
(Thanks for support!)

**Comment by agiudiceandrea** [comment]
@Dret42 I suspect the issue may be the same as the one already recently fixed with PR https://github.com/qgis/QGIS/pull/56768. In that case, the the fix for such issue will be available since the upcoming QGIS 3.34.4 and QGIS 3.36.1 releases and in the current build of QGIS 3.37.0-Master.

**Comment by Dret42** [comment]
Thanks, I'll wait for the update!

**Comment by nirvn** [comment]
That's definitively fixed in the next version.
