### ISSUE TITLE
Changes to data provider filter reset after clicking "OK" or "APPLY" in the Layer-Properties window

### ISSUE THREAD

**Issue by mapandre** [qgis/QGIS#56893]
### What is the bug or the crash?

The following bug appeared on multiple Geopackage layers as well as shapefiles from different sources:

When adding/ altering or deleting a data provider filter (Layer properties -->source--> Provider Feature Filter) the filter is correctly applied at first (Only the desired features appear in the canvas window), but after clicking OK or APPLY in the layer properties window it resets to the state from before (e.g. if you entered a filter it is deleted and if you try to delete a filter, the filter defined previously is applied.
(Edit: Only the way via the layer properties seems effected.  Rightclick on layer-->filter seems to work)

### Steps to reproduce the issue

1) On a Shapefile or Geopackage layer go to layer properties --> source -->Provider Feature Filter

2) Set a filter eg.  "NAME" like 'foo' (make sure you can see the map canvas extent to verify the filter initialy works)

3) you should be able to see the desired result on the map canvas and  The "Test" button shows the correct number of features

4) Click OK or Apply on the layer properties window

5) The filter resets to whatever filter was previously set (none if there no filter was previously set)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.36.0-Maidenhead | QGIS-Codeversion | 09951dc0
-- | -- | -- | --
Qt-Version | 5.15.3
Python-Version | 3.9.18
GDAL-Version | 3.8.4
PROJ-Version | 9.3.1
EPSG-Registraturdatenbankversion | v10.098 (2023-11-24)
GEOS-Version | 3.12.1-CAPI-1.18.1
SQLite-Version | 3.41.1
PDAL-Version | 2.6.0
PostgreSQL-Client-Version | 16.1
SpatiaLite-Version | 5.1.0
QWT-Version | 6.1.6
QScintilla2-Version | 2.13.4
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
BezierEditing | version 1.3.8
DataDrivenInputMask | 2.4.3
DEMto3D | 3.6
Hqgis | 1.2.3
latlontools | 3.6.19
nominatim_locator_filter | 0.3.2
ORStools | 1.7.1
Projestions | 1.0.1
qgis-maptiler-plugin | 3.2
Qgis2threejs | 2.7.3
QNEAT3 | 1.0.5
QuickOSM | 2.2.3
quick_map_services | 0.19.34
SRTM-Downloader | 3.2.1
street_facing_side | 0.5
valuetool | 3.0.19
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.36.0-Maidenhead
QGIS-Codeversion
[09951dc0](https://github.com/qgis/QGIS/commit/09951dc0)
Qt-Version
5.15.3
Python-Version
3.9.18
GDAL-Version
3.8.4
PROJ-Version
9.3.1
EPSG-Registraturdatenbankversion
v10.098 (2023-11-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.41.1
PDAL-Version
2.6.0
PostgreSQL-Client-Version
16.1
SpatiaLite-Version
5.1.0
QWT-Version
6.1.6
QScintilla2-Version
2.13.4
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
BezierEditing
version 1.3.8
DataDrivenInputMask
2.4.3
DEMto3D
3.6
Hqgis
1.2.3
latlontools
3.6.19
nominatim_locator_filter
0.3.2
ORStools
1.7.1
Projestions
1.0.1
qgis-maptiler-plugin
3.2
Qgis2threejs
2.7.3
QNEAT3
1.0.5
QuickOSM
2.2.3
quick_map_services
0.19.34
SRTM-Downloader
3.2.1
street_facing_side
0.5
valuetool
3.0.19
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mapandre, thanks for reporting. Anyway it seems that issue is the same as the one already reported https://github.com/qgis/QGIS/issues/56536 and fixed https://github.com/qgis/QGIS/pull/56542 https://github.com/qgis/QGIS/pull/56575.
