### ISSUE TITLE
Layer filter does not work with variables

### ISSUE THREAD

**Issue by TNogatz** [qgis/QGIS#56927]
### What is the bug or the crash?

Filtering a layer using variables (right click a layer > Filter...) does not work depending on the layer type. Tested with clean QGIS environment.

### Steps to reproduce the issue

1. create a new temporary scratch layer, a new shapefile and a new geopackage (i.g. point layer, WGS 84)
2. add a field "name" (text 254) to each layer
3. go to **settings > options > variables** and copy the content of **user_full_name**  to the clipboard
4. create a point feature for each of the 3 created layers, name = content of **user_full_name**
5. create a filter for each of the 3 created layers: right click a layer > Filter ... > type in: **"name" = @user_full_name** > click the Test Button

Result: 
- temporary layer: no problem, it works. Query Result = The where clause returned 1 row.
- geopackage: Error: Query Result = The where clause returned 0 rows. 
- shape file: Query Result: 
An error occurred when executing the query.
The data provider said:
OGR[3] error 1: SQL Expression Parsing Error: syntax error, unexpected $undefined. Occurred around :
"name" = @user_full_name
         ^

Expected: Query Result = The where clause returned 1 row.
for each of the layers

### Versions

QGIS version
3.34.4-Prizren
QGIS code revision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
This is because the layer filter is not an expression.
See also https://gis.stackexchange.com/a/212605 and the linked answer.

We could think of a feature request to make a new layer filter based on expressions.

**Comment by TNogatz** [comment]
Thank you for the answer. It would be great if it would be possible to filter a layer by user name to show only the areas of interest to the user - especially in QField projects. I've created a feature request: #56957
