### ISSUE TITLE
WFS connection problems after QGIS Update from LTR 3.28.2 to LTR 3.34.4

### ISSUE THREAD

**Issue by mapos7** [qgis/QGIS#56931]
### What is the bug or the crash?

After QGIS LTR Update to the version 3.34.4-1 (Long term repo 3.34.4., release date 2024-02-23 acoording to the [QGIS Road Map](https://qgis.org/en/site/getinvolved/development/roadmap.html)) there are connectivity issues with an (firm-internal) WFS layer. WFS data import is very slow or fails completely (no firm-internal changes in the backend, no QGIS profile changes, ...). Authentification credentials had to be re-specified after the first QGIS installation of the new LTR, even though the WFS credentials stored in the QGIS *.ini file.

In the QGIS LTR 3.28.2 no WFS issues.
No issues with external WFS connections in QGIS QGIS LTR 3.34.4

What has been done so far?
- new WFS definition in default profile
- new WFS definition in one of the exisiting profiles
- new WFS definition in a new profile
- adjustment of QGIS network settings incl. cache, timeout for network requests

Debugging mode shows 401 error code (status 500):

QGIS 3.28.2
 ```
{
    "Bytes Received": 400612,
    "Bytes Total": -1,
    "Cache (control)": "Always load from network, do not check cache",
    "Cache (save)": "Result cannot be stored in cache",
    "Headers": {
      "Authorization": "<>",
      "User-Agent": "Mozilla/5.0 QGIS/32802/Windows 10 Version 2009"
    },
    "ID": "src\\providers\\wfs\\qgsbasenetworkrequest.cpp:142 (QgsBaseNetworkRequest::sendGET)",
    "Initiator": "QgsBaseNetworkRequest",
    "Operation": "GET",
    "Query": {
      "BBOX": "<>,"EPSG:4326",
      "REQUEST": "GetFeature",
      "SERVICE": "WFS",
      "SRSNAME": "EPSG:4326",
      "TYPENAMES": "<>",
      "VERSION": "2.0.0"
    },
    "Replies": 15,
    "Thread": "0x0000023ce90a34f0",
    "Total time (ms)": 0,
    "URL": "<>"
  },
```
QGIS 3.34.4
```
{
    "Bytes Received": 546,
    "Bytes Total": 546,
    "Cache (control)": "Always load from network, do not check cache",
    "Cache (save)": "Result cannot be stored in cache",
    "Headers": {
      "Authorization": "<>",
      "User-Agent": "Mozilla/5.0 QGIS/33404/Windows 10 Version 2009"
    },
    "ID": "src\\providers\\wfs\\qgsbasenetworkrequest.cpp:214 (QgsBaseNetworkRequest::sendGET)",
    "Initiator": "QgsBaseNetworkRequest",
    "Operation": "GET",
    "Query": {
      "COUNT": "1",
      "FILTER": "<>",
      "REQUEST": "GetFeature",
      "SERVICE": "WFS",
      "SRSNAME": "EPSG:4326",
      "TYPENAMES": "<>",
      "VERSION": "2.0.0"
    },
    "Replies": 2,
    "Reply": {
      "Cache (result)": "Read from network",
      "Error": "Error transferring <>",
      "Error Code": "401",
      "Headers": {
        "cache-control": "no-cache, no-store, max-age=0, must-revalidate",
        "content-type": "application/xml;charset=UTF-8",
        "date": "Thu, 21 Mar 2024 09:46:22 GMT",
        "expires": "0",
        "pragma": "no-cache",
        "server": "<>",
        "strict-transport-security": "max-age=<>;includeSubDomains;preload",
        "transfer-encoding": "chunked",
        "x-content-type-options": "nosniff",
        "x-frame-options": "DENY",
        "x-xss-protection": "1; mode=block"
      },
      "Status": "500"
    },
    "Thread": "0x000001fe0baf48f0",
    "Total time (ms)": 30116,
    "URL": "<>"

```

Differences in the qgsbasenetworkrequest.cpp::, the GET parameters (BBOX parameter in 3.28.2 but missing in 3.34.4) and the threads between both QGIS LTR versions.

Since no changes were made to the other QGIS settings or the components related to the WFS GET request and the WFS connection works well in 3.28.2, it is reasonable to assume that changes were made in the new QGIS release that cause the incorrect WFS behavior. Possibly a change in QgsBaseNetworkRequest or maybe a bug in QGIS? Are some QGIS settings necessary?

### Steps to reproduce the issue

![image](https://github.com/qgis/QGIS/assets/116223739/ffd512ae-d79a-4c6d-a9d6-c06116edaf61)

### Versions

for QGIS LTR 3.28.2:
---
QGIS version
3.28.2-Firenze
QGIS code revision
b47e00ba601
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.1
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.39.4
PDAL version
2.4.3
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009
---

and

--
QGIS version
3.34.4-Prizren
QGIS code revision
decd43dc
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009
---

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
I would assume that your WFS server is buggy. There have been changes in the WFS provider, to implement new functionality / fixes, that may cause new requests to be issued. That works fine with a lot of WFS servers around
Closing as not a QGIS bug
