### ISSUE TITLE
Not possible to use both Vertical and Temporal filters at the same time

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#56938]
### What is the bug or the crash?

I have a [netcdf](https://drive.google.com/file/d/1KNVCOUJiNxAk4iaBKbaFZxYQOBEfC5T4/view?usp=drive_link) which contains both vertical (at 5, 10, 20, 30) and temporal data (between 2022-07-12 00:00:00 and 2022-07-17 12:00:00).

When I load the file as a raster and assign the vertical and temporal values to the bands, I cannot see changes in the temporal controller when Elevation filtering is enabled.

The expressions I used to populate elevation:
` regexp_substr(@band_name,'height=(.*?)\\s')`

For temporal values:
`datetime_from_epoch(to_int( replace(regexp_substr(@band_name,'(?<=time=)(.*)(?= \(seconds)'),'(','')-7200)*1000)`

### Steps to reproduce the issue

See above

### Versions

QGIS master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
@saberraz I'm working on this already 👍

**Comment by saberraz** [comment]
Brilliant, thanks a lot!
