### ISSUE TITLE
App crashes when trying to open WFS link

### ISSUE THREAD

**Issue by eziomrc** [qgis/QGIS#56939]
## User Feedback

App crashes when trying to open WFS link (https://idt2-geoserver.regione.veneto.it/geoserver/ows)

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00002230 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QBasicMutex::lockInternal :
QWaitCondition::wakeAll :
multipleProviderMetadataFactory :
QObject::qt_static_metacall :
QgsNetworkAccessManager::sslErrorsOccurred :
QgsNetworkAccessManager::onReplySslErrors :
QObject::qt_static_metacall :
QNetworkReply::sslErrors :
QTcpServer::proxy :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
multipleProviderMetadataFactory :
QgsDataItem::runCreateChildren :
QgsDataItem::runCreateChildren :
QgsDataItem::removeChildItem :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.0-Maidenhead
QGIS code revision: 09951dc0
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22000

### Steps to reproduce the issue

1. Open QGIS project;
2. Go to browser;
3. WFS section;
4. Click on custom WFS server connection ("Geoportale Regione Veneto") (WFS link: https://idt2-geoserver.regione.veneto.it/geoserver/ows);
5. App crashes.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.36.0-Maidenhead | Revisione codice QGIS | 09951dc0
-- | -- | -- | --
Versione Qt | 5.15.3
Versione Python | 3.9.18
Versione GDAL/OGR | 3.8.4
Versione PROJ | 9.3.1
Versione database del Registro EPSG | v10.098 (2023-11-24)
Versione GEOS | 3.12.1-CAPI-1.18.1
Versione SQLite | 3.41.1
Versione PDAL | 2.6.0
Versione client PostgreSQL | 16.1
Versione SpatiaLite | 5.1.0
Versione QWT | 6.1.6
Versione QScintilla2 | 2.13.4
Versione SO | Windows 10 Version 2009
  |   |   |  
Plugins Python attivi
densityanalysis | 2024.1.23
quick_map_services | 0.19.34
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Versione di QGIS
3.36.0-Maidenhead
Revisione codice QGIS
[09951dc0](https://github.com/qgis/QGIS/commit/09951dc0)
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.4
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
16.1
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
densityanalysis
2024.1.23
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@eziomrc, thanks for reporting. I cannot replicate the crash following the provided steps using QGIS 3.36.0 on Windows 10.

https://github.com/qgis/QGIS/assets/16253859/9c16a6d5-dd6f-41c0-8125-9a9a3b1f2d24

Please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it does, please provide more details in order to replicate the issue.
