### ISSUE TITLE
CI fails because not enabled to retrieve hana binary

### ISSUE THREAD

**Issue by troopa81** [qgis/QGIS#56932]
### What is the bug or the crash?

It's impossible to retrieve the hana binary at the moment

we get the following error

```
#24 329.1 curl: (18) transfer closed with 41364704 bytes remaining to read
#24 ERROR: process "/bin/sh -c curl -j -k -L -H \"Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt\" https://tools.hana.ondemand.com/additional/hanaclient-latest-linux-x64.tar.gz --output hanaclient-latest-linux-x64.tar.gz   && tar -xvf hanaclient-latest-linux-x64.tar.gz   && mkdir /usr/sap   && ./client/hdbinst -a client --sapmnt=/usr/sap   && rm -rf client   && rm hanaclient*" did not complete successfully: exit code: 18
------
 > [binary-only 2/2] RUN curl -j -k -L -H "Cookie: eula_3_1_agreed=tools.hana.ondemand.com/developer-license-3_1.txt" https://tools.hana.ondemand.com/additional/hanaclient-latest-linux-x64.tar.gz --output hanaclient-latest-linux-x64.tar.gz   && tar -xvf hanaclient-latest-linux-x64.tar.gz   && mkdir /usr/sap   && ./client/hdbinst -a client --sapmnt=/usr/sap   && rm -rf client   && rm hanaclient*:

 75  160M   75  120M    0     0   376k      0  0:07:16  0:05:28  0:01:48     0
329.1 curl: (18) transfer closed with 41364704 bytes remaining to read
```

See [here](https://github.com/qgis/QGIS/actions/runs/8373074134/job/22925399437?pr=56922#step:7:5287) for instance

@mrylov Can you take a look please? I think we should cache or store somewhere this kind of binaries to avoid such issues.

### Steps to reproduce the issue

Create a PR

### Versions

master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by mrylov** [comment]
@troopa81, thanks for reporting the issue. We will try to resolve the issue as soon as possible.
Sorry for the inconvenience.

**Comment by mrylov** [comment]
It seems the issue has been resolved, see https://github.com/qgis/QGIS/actions/runs/8385282040/job/22964554793.

**Comment by troopa81** [comment]
@mrylov Do you have any idea why it was broken ? Was it a server side issue?

**Comment by mrylov** [comment]
@troopa81, I don't have any information on that.

**Comment by elpaso** [comment]
Failing again @mrylov  :disappointed: 

See: https://github.com/qgis/QGIS/actions/runs/8556624119/job/23446899465?pr=57046#step:7:4984

**Comment by troopa81** [comment]
Thanks @mrylov :+1:
