### ISSUE TITLE
Missing bands when opening netcdf

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#56941]
### What is the bug or the crash?

I am not sure if this is a GDAL issue or QGIS. I have a [netcdf](https://drive.google.com/file/d/1KNVCOUJiNxAk4iaBKbaFZxYQOBEfC5T4/view?usp=drive_link) with 131 time steps at 4 levels. When I open it in QGIS, I expect to see 524 bands. But I can only see 216 bands.

I also tried `gdalinfo` and it only goes as far as 216 bands.

### Steps to reproduce the issue

See above

### Versions

QGIS master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
ncdump gives me

```shell
dimensions:
        time = 54 ;
        height = 4 ;
```

so 4 x 54 = 216 bands. I don't see 131 time steps in the given file.
