### ISSUE TITLE
[Print layout] prints the first page of an atlas twice

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#56967]
### What is the bug or the crash?

after updating to QGIS 3.34.5 the printing of complex and high quality atlases (A3, 150 dpi etc...) duplicates the first page.

I cannot attach any projects or data because the problem occurs on complex atlases.

### Steps to reproduce the issue

1. create a complex atlas (A3, 150 dpi, print as vector etc...)
2. launch the print using a filter in the atlas
3. open PDF, the first page is present twice

## OSGeo4W 64b win 11

Versione di QGIS
3.34.5-Prizren
Revisione codice QGIS
4b308492
Versione Qt
5.15.3
Versione Python
3.9.18
Versione GDAL/OGR
3.8.4
Versione PROJ
9.3.1
Versione database del Registro EPSG
v10.098 (2023-11-24)
Versione GEOS
3.12.1-CAPI-1.18.1
Versione SQLite
3.41.1
Versione PDAL
2.6.0
Versione client PostgreSQL
16.2
Versione SpatiaLite
5.1.0
Versione QWT
6.1.6
Versione QScintilla2
2.13.4
Versione SO
Windows 10 Version 2009

Plugins Python attivi
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Without a sample project this issue cannot be fixed. You'll need to provide one for this ticket

**Comment by pigreco** [comment]
> Without a sample project this issue cannot be fixed. You'll need to provide one for this ticket

Unfortunately I am not authorized to share the data, I am closing the issue.
Sorry for the noise

**Comment by matjash** [comment]
This is duplicated issue of #38356.
