### ISSUE TITLE
Actions not displayed correctly in Attribute Table after reload

### ISSUE THREAD

**Issue by CodeBardian** [qgis/QGIS#56966]
### What is the bug or the crash?

After triggering the Duplicate Feature action from within the Attribute Table, the newly added features will show the Duplicate Feature button widget in the first column instead of the actual content of the field. 

See screencast below:
![qgis5](https://github.com/qgis/QGIS/assets/49531816/dc817261-554a-4059-9e38-4a01aca78500)

### Steps to reproduce the issue

1. Create a new layer (provider type does not matter, e.g. with memory layer).
2. Add some fields and a feature.
3. Enable the Action Widget in the Organize Table Columns Dialog of the Attribute Table.
4. Trigger the Duplicate Features action and observe that the content of the first column will show the action instead of the field content.

### Versions

3.34, master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by CodeBardian** [comment]
Same issue also appears when using any of the column sort indicators in the table:
![qgis6](https://github.com/qgis/QGIS/assets/49531816/c069f2f7-9443-4259-850c-73706e94f3dc)

**Comment by signedav** [comment]
As @CodeBardian mentioned correctly this also happens on sorting. Same with copy-pasting or filter. This leads to crashes...

I renamed the title accordingly.

**Comment by CodeBardian** [comment]
Thanks for picking up on this @signedav. I had already started investigating this issue, but ultimately gave up on fixing it, due to my lacking Qt knowledge. 
I was wondering if the following statement is the culprit, as it seems to map invalid indices in the source model (which applies to the action column) to column 0, therefore drawing the action widget in the first column (?). https://github.com/qgis/QGIS/blob/53476114df64ee419583c5504d038c2f03f32029/src/gui/attributetable/qgsattributetablefiltermodel.cpp#L710-L713

I was thinking about drawing the widgets from a delegate instead of using setIndexWidget, but again could not make any progress.

**Comment by signedav** [comment]
Yeah I wonder if it needs to return a valid QModelIndex at all, since we usually get the feature via the property "fid" in the actions:

https://github.com/qgis/QGIS/blob/53476114df64ee419583c5504d038c2f03f32029/src/gui/attributetable/qgsattributetableview.cpp#L483
