### ISSUE TITLE
Run extern optimization package

### ISSUE THREAD

**Issue by redsalmon7** [qgis/QGIS#56997]
## User Feedback

I have written a Python script that uses parameters from the QGIS user interface as input for an imported optimization model from an external Python package. When I run this script and the optimization, QGIS crashes:

Windows fatal exception: access violation

Thread 0x00005380 (most recent call first):

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00005380 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QObject::thread :
QgsLazInfo::vlrData :
_CallSettingFrame_LookupContinuationIndex handlers.asm:98
__FrameHandler4::CxxCallCatchBlock frame.cpp:1367
RcConsolidateFrames :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
pdal::Option::getName :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

Own optimization script (pyomo, glpk)

### Versions

**QGIS Info**
QGIS Version: 3.28.10-Firenze
QGIS code revision: e2edb9c468
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
Chances are high the problem is within your script or another dependency and most likely not something within QGIS itself. I would propose you check via a support channel and we close this bug here.
