### ISSUE TITLE
EPSG:4269 and EPSG:5498 treated as identical though they use different vertical datums?

### ISSUE THREAD

**Issue by evanapplegate** [qgis/QGIS#56999]
### What is the bug or the crash?

Used gdalbuildvrt to create a VRT with 9x DEM TIFFs, all TIFFs are in EPSG:4269
Added VRT to QGIS, which reads it as EPSG:5498 (?)
Warping the VRT to EPSG:26943 yielded odd elevation values, a pixel with value 50 became value -20, etc.
Fixed issue by setting source SRS to EPSG:4269 instead of EPSG:5498 in the warp dialog.

In the QGIS CRS properties window, the descriptions of EPSG:4269 and EPSG:5498 are identical https://www.diffchecker.com/GqzL56l7/

But in EPSG.io they're very different, see WKT in https://epsg.io/4269 vs. https://epsg.io/5498 ; 5498 uses the NAVD88 vertical datum and that caused the strange values when I reprojected.

### Steps to reproduce the issue

![projection_change](https://github.com/qgis/QGIS/assets/6709659/44af2e6a-4b96-404a-b104-ff16e032597e)
See gif, TIFFs and VRT in this folder:
https://www.dropbox.com/scl/fo/8ut7hwwm1ihhlsqy1hoaq/h?rlkey=t7hd08m16oa5pw0cdb7yonb7b&dl=0

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.32.3-Lima | QGIS code revision | 67d46100b5b
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.7
  |   |   |  
Active Python plugins
QuickOSM | 2.2.3
quick_map_services | 0.19.34
SaveAllScript | 1.0
buntinglabs-qgis-plugin | 1.7
latlontools | 3.6.18
TerrainShading | 0.9.3
ProcessX | 1.7
shapetools | 3.4.18
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.32.3-Lima
QGIS code revision
[67d46100b5b](https://github.com/qgis/QGIS/commit/67d46100b5b)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.7

Active Python plugins
QuickOSM
2.2.3
quick_map_services
0.19.34
SaveAllScript
1.0
buntinglabs-qgis-plugin
1.7
latlontools
3.6.18
TerrainShading
0.9.3
ProcessX
1.7
shapetools
3.4.18
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@evanapplegate, QGIS 3.32 is no longer supported. Please actually try if the issue occurs using the currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and actually using a new QGIS user profile.
In QGIS 3.34 and 3.36 on Windows, the two CRS have different WKT representation:

EPSG:4269
```
NAD83
Properties
Geographic (uses latitude and longitude for coordinates)
Static (relies on a datum which is plate-fixed)
Celestial body: Earth
Method: Lat/long (Geodetic alias)
WKT
GEOGCRS["NAD83",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Geodesy."],
        AREA["North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. Puerto Rico. United States (USA) - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Hawaii; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands. British Virgin Islands."],
        BBOX[14.92,167.65,86.45,-40.73]],
    ID["EPSG",4269]]
Proj4
+proj=longlat +datum=NAD83 +no_defs
Extent
167.65, 14.92, -40.73, 86.45
```

EPSG:5498
```
NAD83 + NAVD88 height
Properties
Units: degrees
Static (relies on a datum which is plate-fixed)
Celestial body: Earth
Method: Lat/long (Geodetic alias)
WKT
COMPOUNDCRS["NAD83 + NAVD88 height",
    GEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        CS[ellipsoidal,2],
            AXIS["geodetic latitude (Lat)",north,
                ORDER[1],
                ANGLEUNIT["degree",0.0174532925199433]],
            AXIS["geodetic longitude (Lon)",east,
                ORDER[2],
                ANGLEUNIT["degree",0.0174532925199433]]],
    VERTCRS["NAVD88 height",
        VDATUM["North American Vertical Datum 1988"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1]]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United States (USA) - CONUS and Alaska - onshore - Alabama; Alaska mainland; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming."],
        BBOX[24.41,-168.26,71.4,-66.91]],
    ID["EPSG",5498]]
Proj4
+proj=longlat +datum=NAD83 +vunits=m +no_defs
Extent
-168.26, 24.41, -66.91, 71.40
```

**Comment by agiudiceandrea** [comment]
@evanapplegate, QGIS 3.32 is no longer supported. Please actually try if the issue occurs using the currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and actually using a new QGIS user profile.
Moreover, the macOS installers available at www.qgis.org ship old versions of the GDAL and PROJ libraries and of the EPSG database. Please try if the issue occurs also using MacPorts (as suggested at https://qgis.org/en/site/forusers/download.html#mac):

"Alternatively, for native support of both Intel x86 and Apple ARM architectures, together with the latest versions of key components (e.g. GDAL, PDAL, GRASS GIS) see: [MacPorts Installing Instructions](https://qgis.org/en/site/forusers/alldownloads.html#macports)"

In QGIS 3.34 and 3.36 on Windows, the two CRS have different WKT representation:

EPSG:4269
```
NAD83
Properties
Geographic (uses latitude and longitude for coordinates)
Static (relies on a datum which is plate-fixed)
Celestial body: Earth
Method: Lat/long (Geodetic alias)
WKT
GEOGCRS["NAD83",
    DATUM["North American Datum 1983",
        ELLIPSOID["GRS 1980",6378137,298.257222101,
            LENGTHUNIT["metre",1]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433]],
    CS[ellipsoidal,2],
        AXIS["geodetic latitude (Lat)",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433]],
        AXIS["geodetic longitude (Lon)",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433]],
    USAGE[
        SCOPE["Geodesy."],
        AREA["North America - onshore and offshore: Canada - Alberta; British Columbia; Manitoba; New Brunswick; Newfoundland and Labrador; Northwest Territories; Nova Scotia; Nunavut; Ontario; Prince Edward Island; Quebec; Saskatchewan; Yukon. Puerto Rico. United States (USA) - Alabama; Alaska; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Hawaii; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming. US Virgin Islands. British Virgin Islands."],
        BBOX[14.92,167.65,86.45,-40.73]],
    ID["EPSG",4269]]
Proj4
+proj=longlat +datum=NAD83 +no_defs
Extent
167.65, 14.92, -40.73, 86.45
```

EPSG:5498
```
NAD83 + NAVD88 height
Properties
Units: degrees
Static (relies on a datum which is plate-fixed)
Celestial body: Earth
Method: Lat/long (Geodetic alias)
WKT
COMPOUNDCRS["NAD83 + NAVD88 height",
    GEOGCRS["NAD83",
        DATUM["North American Datum 1983",
            ELLIPSOID["GRS 1980",6378137,298.257222101,
                LENGTHUNIT["metre",1]]],
        PRIMEM["Greenwich",0,
            ANGLEUNIT["degree",0.0174532925199433]],
        CS[ellipsoidal,2],
            AXIS["geodetic latitude (Lat)",north,
                ORDER[1],
                ANGLEUNIT["degree",0.0174532925199433]],
            AXIS["geodetic longitude (Lon)",east,
                ORDER[2],
                ANGLEUNIT["degree",0.0174532925199433]]],
    VERTCRS["NAVD88 height",
        VDATUM["North American Vertical Datum 1988"],
        CS[vertical,1],
            AXIS["gravity-related height (H)",up,
                LENGTHUNIT["metre",1]]],
    USAGE[
        SCOPE["Engineering survey, topographic mapping."],
        AREA["United States (USA) - CONUS and Alaska - onshore - Alabama; Alaska mainland; Arizona; Arkansas; California; Colorado; Connecticut; Delaware; Florida; Georgia; Idaho; Illinois; Indiana; Iowa; Kansas; Kentucky; Louisiana; Maine; Maryland; Massachusetts; Michigan; Minnesota; Mississippi; Missouri; Montana; Nebraska; Nevada; New Hampshire; New Jersey; New Mexico; New York; North Carolina; North Dakota; Ohio; Oklahoma; Oregon; Pennsylvania; Rhode Island; South Carolina; South Dakota; Tennessee; Texas; Utah; Vermont; Virginia; Washington; West Virginia; Wisconsin; Wyoming."],
        BBOX[24.41,-168.26,71.4,-66.91]],
    ID["EPSG",5498]]
Proj4
+proj=longlat +datum=NAD83 +vunits=m +no_defs
Extent
-168.26, 24.41, -66.91, 71.40
```

The provided "ncei19_n36x75_w121x75_2023v1.tif" GeoTIFF raster layer have the GeoTIFF CRS tag set to "NAD83 + NAVD88 height" (EPSG:5498). Such CRS is recognized by gdalinfo and by QGIS for the provided GeoTIFF raster layer.

**Comment by rouault** [comment]
> Used gdalbuildvrt to create a VRT with 9x DEM TIFFs, all TIFFs are in EPSG:4269

They aren't, at least with recent enough GDAL versions. They are actually recognized as EPSG:5498 "NAD83 + NAVD88 height"  and this is consistent with EPSG:4269 "NAD83" being registered as the GeographicCRS and NAVD88 height being registered as the VerticalCRS in the geotiff keys.

> Warping the VRT to EPSG:26943 yielded odd elevation values, a pixel with value 50 became value -20, etc.

See https://gdal.org/programs/gdalwarp.html#vertical-transformation for explanations and ways to disable this behaviour

**Comment by evanapplegate** [comment]
@agiudiceandrea Thank you, I misread the roadmap table, thought whatever was on that table was currently supported.

Used Macports to install 3.36.1, which updated GDAL/OGR from 3.3.2 to 3.8.4 and PROJ from 8.1.1 to 9.4.0

Those TIFFs now correctly load as EPSG:5498, closing issue.
