### ISSUE TITLE
 Newly added layer from Processing Algorithms is not being selected as the active layer

### ISSUE THREAD

**Issue by spatialthoughts** [qgis/QGIS#57003]
### What is the bug or the crash?

This is a regression from QGIS LTR 3.28 to QGIS LTR 3.34. In the current version, when you run the processing algorithm, the newly generated layer is not being selected as the active layer. This used to be the behavior in the previous versions which made it easy and intuitive for users to run a series of processing algorithms without manually changing the layer. 

Input Layer -> algorithm1 ->  output A
output A -> algorithm2 -> output B
output B -> algorithm3 -> final output

In the current version, the user has to always change the input layer manually in the tool to select the previously generated layer. This is error prone and creates additional work for the user.

The screen recording below shows the issue
![activelayer](https://github.com/qgis/QGIS/assets/5227506/f8b884d8-5293-4fe6-88ef-16fb340bb24b)

### Steps to reproduce the issue

Select an input layer. Run any processing tool that generates an output layer. Once the new layer is added, it will be NOT be the active layer.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.4-Prizren | QGIS code revision | 1e052ed1f5e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 14.0
  |   |   |  
Active Python plugins
ORStools | 1.7.1
QuickOSM | 2.2.3
quick_map_services | 0.19.34
qgis_stac | 1.1.1
processing | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.34.4-Prizren
QGIS code revision
[1e052ed1f5e](https://github.com/qgis/QGIS/commit/1e052ed1f5e)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 14.0

Active Python plugins
ORStools
1.7.1
QuickOSM
2.2.3
quick_map_services
0.19.34
qgis_stac
1.1.1
processing
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Probably related to https://github.com/qgis/QGIS/issues/56129.
