### ISSUE TITLE
GeoPackage - Delete Style

### ISSUE THREAD

**Issue by brunellop** [qgis/QGIS#57019]
### What is the bug or the crash?

Good morning, I have found that using both QGIS LTR version 3.34 and 3.36, it is impossible to remove GeoPackage related styles with the "Delete Style" option. 
By retrying the operation with version 3.28, I was able to confirm that the command works correctly up to this version.

### Steps to reproduce the issue

![ERROR](https://github.com/qgis/QGIS/assets/39586569/2252c0be-651d-4419-af11-fabce2092896)

### Versions

QGIS version
3.34.5-Prizren
QGIS code revision
4b308492
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.34
processing
2.12.99
lftools
1.12.8

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @brunellop, thanks for reporting. Please add a sample GeoPackage file with which the issue occurs.

**Comment by agiudiceandrea** [comment]
@brunellop, the provided URL does not allow to retrieve the GPKG file.

**Comment by brunellop** [comment]
> @brunellop, the provided URL does not allow to retrieve the GPKG file. The issue may be related to #54558.

The link is now available for download.
