### ISSUE TITLE
QuickOSM bug report

### ISSUE THREAD

**Issue by nagandori** [qgis/QGIS#57026]
### What is the bug or the crash?

Error in the QGIS log window, then the QuickOSM panel, copy/paste it and please report it, if you know how to copy/paste QGIS logs. Please check pinned tickets first.

### Steps to reproduce the issue

The following error occurs when executing a query.
Error in the QGIS log window, then the QuickOSM panel, copy/paste it and please report it, if you know how to copy/paste QGIS logs. Please check pinned tickets first.

### Versions

3.34.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Should be reported here https://github.com/3liz/QuickOSM
And create a more detailled issue.
