### ISSUE TITLE
QGIS LTR version should notify about LTR releases

### ISSUE THREAD

**Issue by kadarivan** [qgis/QGIS#57032]
### What is the bug or the crash?

QGIS 3.34.5 LTR do advertise to install QGIS 3.36.1 while it should not
![kép](https://github.com/qgis/QGIS/assets/18245793/2e46fa24-d77f-47e9-ab18-16782f609a65)
The same issue has already happened some other times (see e.g. https://github.com/qgis/QGIS/issues/42577, https://github.com/qgis/QGIS/issues/34685, https://github.com/qgis/QGIS/issues/33494, https://github.com/qgis/QGIS/issues/21240) and was then fixed by @jef-n.

### Steps to reproduce the issue

Open QGIS LTR

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-verzió | 3.34.5-Prizren | QGIS forráskódverzió | 4b308492
-- | -- | -- | --
Qt-verzió | 5.15.3
Python-verzió | 3.9.18
GDAL/OGR-verzió | 3.8.4
PROJ-verzió | 9.3.1
EPSG-nyilvántartási adatbázis verziója | v10.098 (2023-11-24)
GEOS-verzió | 3.12.1-CAPI-1.18.1
SQLite-verzió | 3.41.1
PDAL-verzió | 2.6.0
Postgresql kliens verziója | 16.2
SpatiaLite-verzió | 5.1.0
QWT-verzió | 6.1.6
QScintilla2-verzió | 2.13.4
OS-verzió | Windows 10 Version 2009
  |   |   |  
Aktív Python-modulok
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-verzió
3.34.5-Prizren
QGIS forráskódverzió
[4b308492](https://github.com/qgis/QGIS/commit/4b308492)
Qt-verzió
5.15.3
Python-verzió
3.9.18
GDAL/OGR-verzió
3.8.4
PROJ-verzió
9.3.1
EPSG-nyilvántartási adatbázis verziója
v10.098 (2023-11-24)
GEOS-verzió
3.12.1-CAPI-1.18.1
SQLite-verzió
3.41.1
PDAL-verzió
2.6.0
Postgresql kliens verziója
16.2
SpatiaLite-verzió
5.1.0
QWT-verzió
6.1.6
QScintilla2-verzió
2.13.4
OS-verzió
Windows 10 Version 2009

Aktív Python-modulok
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jef-n, the issue is occurring again. Probably the Apache configuration rewrite rule should be updated.
