### ISSUE TITLE
Identify Pane Stuck Open

### ISSUE THREAD

**Issue by Angus-Fiona** [qgis/QGIS#57030]
### What is the bug or the crash?

When using the Identify tool in QGIS, the a pane pops up (as expected) but this panel is both immovable and unclosable. I get get round it by moving my qgis window to a different screen, and the panel stays put. The identify tool is still useable, as if i click on a feature, it moves 

### Steps to reproduce the issue

1. Open my Project
2. Select the layer I wish to identify
3. Click the identify Tool
4. Panel appears, and am unable to remove or move

### Versions

QGIS version
3.28.9-Firenze
QGIS code revision
66f4d63ad4
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
BulkVectorExport
1.1
Discovery
2.5.8
floodrisk2
0.7
FreehandRasterGeoreferencer
0.8.3
pg_metadata
1.2.2
qfieldsync
v4.6.0
quick_map_services
0.19.33
SelectWithin
0.4
slyr_community
5.0.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

![image](https://github.com/qgis/QGIS/assets/150059144/839cb4ca-9265-41f7-a7b4-4416ab379333)
![image](https://github.com/qgis/QGIS/assets/150059144/15573c41-506f-488b-a550-70a6369bee95)

**Comment by agiudiceandrea** [comment]
@Angus-Fiona, thanks for reporting. QGIS 3.28 is no longer supported. Please actually try if the issue occurs running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).

**Comment by agiudiceandrea** [comment]
The currently supported QGIS versions are QGIS LTR 3.34 and QGIS 3.36.
![image](https://github.com/qgis/QGIS/assets/16253859/147cd4b2-01ac-4f95-9cbd-bbb52a430310)
![image](https://github.com/qgis/QGIS/assets/16253859/de2d3cad-dfbf-406e-9931-d217bdf6eb06)

Using a new QGIS user profile, the Identify features panel always opens docked to the right panels bar and not floating as a separate window.

Anyway, you can manage the Identify features panel windows as normal windows on Windows: using the alt+space shortcut and M (for Move if Windows in English) and then use the arrows keys
https://superuser.com/questions/316282/what-can-i-do-to-retrieve-windows-that-have-gone-off-screen

**Comment by Angus-Fiona** [comment]
used alt+space move to get the panel out the way, and scheduled an updated version of qgis :)
