### ISSUE TITLE
QGIS crashed when opening properties of WMS layer

### ISSUE THREAD

**Issue by kpasceri** [qgis/QGIS#57047]
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004278 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_list_operations :
proj_log_error :
proj_list_ellps :
proj_list_ellps :
pj_phi2 :
proj_list_ellps :
proj_trans :
proj_trans_generic :
QgsCoordinateTransform::transformCoords :
QgsLineString::transform :
QgsGeometry::transform :
QgsCoordinateOperationWidget::setMapCanvas :
QgsDatumTransformDialog::QgsDatumTransformDialog :
QgsDatumTransformDialog::run :
QgsRasterLayerProperties::mCrsSelector_crsChanged :
QObject::qt_static_metacall :
QgsProjectionSelectionWidget::crsChanged :
QgsProjectionSelectionWidget::setCrs :
QgsRasterLayerProperties::QgsRasterLayerProperties :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

## User Feedback

Layers:
- WMS 
- Three vector files 

Action when QGIS crashed: 
- Opening properties of WMS layer

### Versions

**QGIS Info**
QGIS Version: 3.32.3-Lima
QGIS code revision: 67d46100b5
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@kpasceri, thanks for reporting. QGIS 3.32 is no longer supported. Please try if the issue occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it does, please provide a sample project with the WMS layer with which the issue occurs.

**Comment by kpasceri** [comment]
Okay, thank you for your response!
