### ISSUE TITLE
Version 3.36 broke setNavigationMode()

### ISSUE THREAD

**Issue by JohanR1988** [qgis/QGIS#57043]
### What is the bug or the crash?

Prior to 3.36 i could change the temporalController navigation mode to FixedRange with python using setNavigationMode(2).
After 3.36 i get: 
 TypeError: QgsTemporalNavigationObject.setNavigationMode(): argument 1 has unexpected type 'int'
 
 

### Steps to reproduce the issue

run python script:

canvas = iface.mapCanvas()
temporal_controller = canvas.temporalController()
temporal_controller.setNavigationMode(2)

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
Use the enum, not an int, see  https://github.com/qgis/QGIS/blob/810a61a791e92af1bbfdb2483764228c9f140ade/tests/src/python/test_qgsmapcanvas.py#L849

**Comment by JohanR1988** [comment]
Thank you.
