### ISSUE TITLE
Cannot add a remote PMTile

### ISSUE THREAD

**Issue by frafra** [qgis/QGIS#57041]
### Feature description

I tried to add a PMTile file available over HTTP, but it does not seem possible in QGIS, since it says that the source is invalid or not recognized. Opening a remote GPKG works as expected.

### Additional context

I tried to add the layer manually, using the Python console, without success:

```python
v = QgsVectorLayer("/vsicurl/https://pycsw.nina.no/media/maps/sources/30/02_Fritidsbebyggelse.pmtiles", "layer", "ogr")
QgsProject.instance().addMapLayer(v)
```

I also wonder if there is a simpler way to open generic gdal/ogr resources, by taking advantage of the wide range of supported formats as well as VFS.

**Comment by NyakudyaA** [comment]
From the gdal documentation it looks like you need gdal >3.8 for this
https://gdal.org/drivers/vector/pmtiles.html

Please check what gdal version you are running qgis with

**Comment by four43** [comment]
Using QGIS 3.38.3 and  GDAL 3.9.2 this does not work well for me given @frafra 's example. QGIS doesn't complain but it's working very hard on a seemingly small problem...

**Comment by kannes** [comment]
In 3.44.7 with GDAL 3.12.1 and the project zoomed to a small region (not the whole earth, not an initial blank project where the first layer sets extent/CRS), adding these as Vector Layers via "Protocol: HTTP(S)..."

- https://data.source.coop/vida/google-microsoft-osm-open-buildings/pmtiles/goog_msft_osm.pmtiles loads well and fast, there are just building polygons inside

<img width="534" height="443" alt="Image" src="https://github.com/user-attachments/assets/6f60f763-c29b-4286-8cf3-4d954e4466b2" />

- https://demo-bucket.protomaps.com/v4.pmtiles shows me a layer chooser and all I get are geometry-less, zero feature layers.

<img width="714" height="628" alt="Image" src="https://github.com/user-attachments/assets/7458fee9-f268-4175-acf4-49c5a31fb017" />

- https://overturemaps-tiles-us-west-2-beta.s3.amazonaws.com/2025-04-23/places.pmtiles also works fine, some simple point data

<img width="669" height="487" alt="Image" src="https://github.com/user-attachments/assets/cff8d14e-9a97-44d1-af5b-0d9fdd2e6cf9" />
