### ISSUE TITLE
Add transparency option for Grids in Layout

### ISSUE THREAD

**Issue by antoniolocandro** [qgis/QGIS#57054]
### Feature description

Sometimes I just need the labels for the grid and do not require the grid itself, in QGIS for this part of the UI it doesn't show transparency as an option like in other parts

From Grid Option
![image](https://github.com/qgis/QGIS/assets/4627073/508ae02d-7373-4ad4-8a7a-a084b4512364)

From Fill Option
![image](https://github.com/qgis/QGIS/assets/4627073/0b24d16d-1063-4d7d-818f-e83c3c1d1cf8)

### Additional context

You can of course play with the opacity slider  
![image](https://github.com/qgis/QGIS/assets/4627073/22d80b49-8a26-4890-a226-d7fa9d12f9bf)

**Comment by roya0045** [comment]
There's an opacity slider and the grid type options. Not sure a new feature is needed to cover this need.

**Comment by antoniolocandro** [comment]
> There's an opacity slider and the grid type options. Not sure a new feature is needed to cover this need.

There is a transparency box as shown for other options, so it seems natural that the UI be consistent

**Comment by antoniolocandro** [comment]
> @antoniolocandro, isn't it suitable for your needs to just set the "Grid type" option to "Frame and annotations only"?

Thank you! I didn't notice the option. This achieves the result I intended.
