### ISSUE TITLE
Layer > Paste style does not paste setting of "Additional no data value" in Layer Properties > Transparency

### ISSUE THREAD

**Issue by fgfletcher** [qgis/QGIS#57053]
### What is the bug or the crash?

failure to paste the value in Layer Properties > Transparency > Additional no data value
occurs in this LTR version and in previous versions

### Steps to reproduce the issue

using a Raster layer with Layer Properties > Symbology set for Singleband Gray
go to the layer's Layer Properties > Transparency 
set Additional no data value = 255
exit Layer Properties
with layer selected: Layer > Copy Style
select another similar Raster layer with Layer Properties > Symbology set for Singleband Gray, 
  in its Layer Properties > Transparency, ensure that Additional no data value is empty or != 255
close the Layer Properties dialog
with this 2nd layer selected: Layer > Paste Style
reopen its Layer Properties > Transparency
  the Additional no data value will NOT have been updated

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.5-Prizren | QGIS code revision | 4b308492cd5
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS High Sierra (10.13)
  |   |   |  
Active Python plugins
FreehandRasterGeoreferencer | 0.8.3
DigitizingTools | 1.5.2
geometric_attributes | 0.4
qProf | 0.5.1
stationlines | 0.2.0
BezierEditing | version 1.3.8
processing_saga_nextgen | 1.0.0
MemoryLayerSaver | 5.0.2
valuetool | 3.0.19
LocatePoints | 0.3.4
coordinate_capture | 0.2
road_slope_calculator | 0.5
processing | 2.12.99
otbprovider | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.5-Prizren
QGIS code revision
[4b308492cd5](https://github.com/qgis/QGIS/commit/4b308492cd5)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS High Sierra (10.13)

Active Python plugins
FreehandRasterGeoreferencer
0.8.3
DigitizingTools
1.5.2
geometric_attributes
0.4
qProf
0.5.1
stationlines
0.2.0
BezierEditing
version 1.3.8
processing_saga_nextgen
1.0.0
MemoryLayerSaver
5.0.2
valuetool
3.0.19
LocatePoints
0.3.4
coordinate_capture
0.2
road_slope_calculator
0.5
processing
2.12.99
otbprovider
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

not a "show stopper", but a real nuisance as I have to manually change that setting layer-by-layer with more than 300 layers to do...

**Comment by agiudiceandrea** [comment]
@fgfletcher, thanks for reporting. The behaviour has been already previously reported at https://github.com/qgis/QGIS/issues/36953. Please add your comment in such report.
