### ISSUE TITLE
[BUG?] Can't add new toolbar from qgis macros script

### ISSUE THREAD

**Issue by lpofredc** [qgis/QGIS#57052]
### What is the bug or the crash?

Adding a new custom widget from QGIS macros script (Menu `project`>`settings`>`macros`) seem to not working as expected. The following script don't add any new toolbar whereas executing `openProject` function content in python console add correctly this new toolbar.

No error are raised.

### Steps to reproduce the issue

1. Create a new project with this macro code
2. Restart qgis
3. Enable macros on session 

```python
from qgis.PyQt.QtWidgets import QPushButton
from qgis.utils import iface

def openProject():
    toolBar = iface.addToolBar('TEST')
    toolBar.setObjectName("TEST")
    testButton = QPushButton('test')
    testButton.setToolTip('test')
    toolBar.addWidget(testButton)

def saveProject():
    pass

def closeProject():
    pass
```

### Versions

tested on **3.34** (ubuntu 23.10) and **3.28** (windows 10)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by fiddlersfan** [comment]
@lpofredc This should not be a bug. The toolbar will be displayed by using iface.mainWindow() instead of iface.
Try this code and give me feedback if the problem still exists:

```
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QPushButton
from qgis.utils import iface

def openProject():
    toolBar = iface.mainWindow().addToolBar('TEST')
    toolBar.setObjectName("TEST")
    testButton = QPushButton('test')
    testButton.setToolTip('test')
    toolBar.addWidget(testButton)

def saveProject():
    pass

def closeProject():
    pass
```

**Comment by fiddlersfan** [comment]
@agiudiceandrea Can u add the feedback label pls?

**Comment by lpofredc** [comment]
Yes, it works! Thanks a lot!!!
