### ISSUE TITLE
Open Sans font installation failed

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#57070]
### What is the bug or the crash?

The font installation constantly fails for every new QGIS installation / user profile.

- in the top notification bar:
`Open Sans font installation failed`
- clicking on View Error:
`Font Install Failed`
`Could not read fonts from data
`
- in the Log Messages panel (Messages):
`2024-04-04T14:47:34     WARNING    Open Sans font installation failed`
- in the Log Messages panel (General):
`2024-04-04T14:47:34     WARNING    Error opening zip archive: 'C:/Users/Andrea/AppData/Local/Temp/QGIS3.mSskqY' (Error code: 19)`

The `font` folder in the user profile folder is empty.

### Steps to reproduce the issue

1. Create a new QGIS user profile
2. see the error messages

### Versions

QGIS 3.34.5 / QGIS 3.36.1 on Windows

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The font download mechanism was introduced with https://github.com/qgis/QGIS/pull/49020.

It seems something changed in how the URL https://fonts.google.com/download used for the font download works. Please see https://trac.osgeo.org/osgeo4w/ticket/824 and https://github.com/google/fonts/issues/7481.

**Comment by EricUniqueUsername** [comment]
Hi all-
I'm new here. Is there a way short of adding a comment such as this one to indicate that I'm encountering the same issue as Andrea?
Eric
QGIS version | 3.36.1-Maidenhead
Windows 10

**Comment by agiudiceandrea** [comment]
@kannes @EricUniqueUsername, see https://github.com/qgis/QGIS/pull/49020#issuecomment-2041205595.

**Comment by wklmeu** [comment]
I had the same issue on installing version 3.34.5-1.

**Comment by brandyballoon** [comment]
I have the same error on a new installation of QGIS 3.36.1 on Windows 11 Pro version 23H2 build 22631.3447

**Comment by kannes** [comment]
No need to worry, just install the next version once available.

**Comment by agiudiceandrea** [comment]
The issue still occur using QGIS 3.38.0 (OSGeo4W) on Windows with a new QGIS user profile.

**Comment by hebersgit** [comment]
If download-mechanism will not work anymore, would it be an alternative to install some of these fonts with the qgis setup? It could use the same mechanism as for the downloaded fonts, that means the fonts are placed as font-files in some directory and are recognized by qgis-application (and do not need to be installed for the operating system).
The feature #49020 is important for map-layouting because one need fonts where one can rely on theire availability.

**Comment by hrdawson** [comment]
Still an issue for a fresh install of QGIS on my re-imaged machine. Manually downloading and installing the font to `/Library/Fonts` from https://fonts.google.com/specimen/Open+Sans fixed the error message.

**QGIS Version** 3.34.11-Prizren (long-term release)
**OS** Mac OS 14.7 Sonoma (23H124)

**Comment by xillibit** [comment]
> Still an issue for a fresh install of QGIS on my re-imaged machine. Manually downloading and installing the font to `/Library/Fonts` from https://fonts.google.com/specimen/Open+Sans fixed the error message.

Where is the  `/Library/Fonts` folder ?

**Comment by kannes** [comment]
On MacOS.

Check your operating system's instructions for font installation or drop them in your QGIS profile under `/fonts/`

**Comment by 772** [comment]
Can this please be reopened? This is not fixed at all.

**Comment by agiudiceandrea** [comment]
@772, which QGIS version exactly are you using?

**Comment by 772** [comment]
> @772, which QGIS version exactly are you using?

The newest 3.38.3-Grenoble for Windows.

It also happens on all computers in our company with the newest 3.34 LTS version installed. I checked the 3.38.3 today to check if the problem is gone there.

**Comment by agiudiceandrea** [comment]
@772 please try if the issue still occurs using QGIS 3.34.0 and QGIS LTR 3.34.12 when they will be available on your system.

**Comment by agiudiceandrea** [comment]
@772 please try if the issue still occurs using QGIS 3.40.0 and QGIS LTR 3.34.12 when they will be available on your system.

**Comment by kristianrl** [comment]
The issue is solved on my installation of 3.38.3 on MacOS. It occured on earlier 3.38-versions.

**Comment by agiudiceandrea** [comment]
@vvmdipie, please provide the full version info of QGIS ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."). Please provide the error messages reported in the "Network" and "Messages" tabs of the [Log Messages Panel](https://docs.qgis.org/3.34/en/docs/user_manual/introduction/general_tools.html#log-messages-panel).

**Comment by 772** [comment]
> @772 please try if the issue still occurs using QGIS 3.40.0 and QGIS LTR 3.34.12 when they will be available on your system. The URL issue has been recently fixed with PR #59142.

Today, I tested the new QGIS-OSGeo4W-3.34.12-1 and yes, it's finally fixed. Thank you, I appreciate your work on this useful software. :)

And sorry. When I demanded reopening this issue I saw that the newest QGIS release was much younger than the date where this bug was closed so I thought all relevant changes where already in 3.34.12-0 LTS or the newest non-LTS version.

**Comment by vvmdipie** [comment]
I had the open sans Error yesterday with this version:
QGIS-Version 3.34.12-Prizren QGIS-Codeversion eeb6af3638
After a new start of QGIS I have a good Message at the upper message field : "Schriftart Open Sans installiert"
I think the font was installed in a second step.

**Comment by arqlourdesmartinez-oss** [comment]
hola ayuda me sale un error fallo en instalación  de letra tipo open sants y no se instalaron o cargaron nigun complemento tengo windows 11 instale qgis 3.40.12

**Comment by agiudiceandrea** [comment]
@arqlourdesmartinez-oss please check if your system is properly set to connect to the Internet and that QGIS is properly set to connect to the Internet. If QGIS can connect to the Internet, please provide more detailed information (possibly in English language) about your system, your QGIS version, the issues you are experiencing.
