### ISSUE TITLE
Align rasters processing tool - missing output file parameter in the pop out box?

### ISSUE THREAD

**Issue by wkhchow** [qgis/QGIS#57088]
### What is the bug or the crash?

Trying to run Align rasters processing tool in QGIS 3.34.5-Prizren. I am putting all the basic required parameters in the pop out box.

When I try to run, I get the following error: Failed to align rasters: Unable to create output file: 

By looking at the log file, you can tell the output file parameter is left blank.

If you copy the python command and run it in the python console, while adding the output path and file name for output file. The tool will run successfully.

Shouldn't there be a target output path/file option available in the tool for anyone not looking to use it in the python console?

### Steps to reproduce the issue

1. Load in 2 raster datsets (same area, different resolution for the purpose of align rasters)
2. Open align rasters tool (raster tools -> align rasters)
3. Fill in parameters
![image](https://github.com/qgis/QGIS/assets/59062243/de698e41-4430-4481-ad9c-ba44d7a14b51)
4. Run tool. It would fail with error below.
![image](https://github.com/qgis/QGIS/assets/59062243/07a17c02-a82b-4117-a4e7-3a9d44681fa8)
5. It would work if you put in a output file location, so copy the python command in the tool and paste in the python console, and update the output file location and run.
![image](https://github.com/qgis/QGIS/assets/59062243/190a883d-00c7-46e6-b236-8d1824533ac2)

### Versions

QGIS version
3.34.5-Prizren
QGIS code revision
4b308492
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
QChatGPT
0.3
quick_map_services
0.19.33
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
You need to select the raster from the input list, then click "configure":

![image](https://github.com/qgis/QGIS/assets/1829991/f6b1ea7e-a7b5-4b17-915e-ae801b82b4bb)

This gives access to the output file setting:

![image](https://github.com/qgis/QGIS/assets/1829991/b858bd7c-f05c-430a-9db5-2c85dc89a585)

**Comment by wkhchow** [comment]
Thanks!
