### ISSUE TITLE
Error while building from public installation site

### ISSUE THREAD

**Issue by muscatelle** [qgis/QGIS#57085]
### What is the bug or the crash?

[ 63%] Linking CXX shared library ../../output/lib/libqgis_3d.so
[ 63%] Built target qgis_3d
make: *** [Makefile:166: all] Error 2

### Steps to reproduce the issue

Followed the instructions at https://github.com/qgis/QGIS/blob/master/INSTALL.md#31-building-qgis-with-qt-5x

### Versions

Not sure - I'm new to building from source

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This isn't a qgis bug -- can you reach out to the qgis -dev mailing list for assistance like this instead please?
