### ISSUE TITLE
Align rasters tool fails to create output

### ISSUE THREAD

**Issue by duboisAM87** [qgis/QGIS#57102]
### What is the bug or the crash?

Hello, it seems that that the new Align rasters tool needs some looking at. The tool gives a critical error saying it can't create the output no matter what we do. 
![image](https://github.com/qgis/QGIS/assets/166548722/c9814893-6425-4540-bca5-c94fceccef7b)

![image](https://github.com/qgis/QGIS/assets/166548722/93527112-84d1-4115-92de-110617438e1d)

I've looked at the doc and there seems to be many parameters missing (output for one but also some parameters related to inputs)

![image](https://github.com/qgis/QGIS/assets/166548722/69a756ba-c5a3-4702-9fed-c17a7e8b3a89)

Hopefully this can be fixed as there is no other tools to do what this tool does.

Thanks,

### Steps to reproduce the issue

1. Go to raster > Align rasters
2. Specify one raster as input
3. Specify one raster as reference

### Versions

Version de QGIS
3.34.5-Prizren
Révision du code
4b308492
Version de Qt
5.15.3
Version de Python
3.9.18
Version de GDAL/OGR
3.8.4
Version de Proj
9.3.1
Version de la base de données du registre EPSG
v10.098 (2023-11-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.41.1
Version de PDAL
2.6.0
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
assets
0.5
processing_r
4.1.0
profiletool
4.2.6
qgis_resource_sharing
1.0.0
QuickMultiAttributeEdit3
version 3.0.3
quick_map_services
0.19.34
SemiAutomaticClassificationPlugin
8.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Thanks for reporting. This issue has been already previously reported: please see https://github.com/qgis/QGIS/issues/57096.
