### ISSUE TITLE
Issue with add entity on non spatial layers

### ISSUE THREAD

**Issue by ponceta** [qgis/QGIS#57108]
### What is the bug or the crash?

I don't know if it's a possible **feature** or a **bug**

But now on QGIS 3.34.4 LTR when you add an entity, the button stick on adding entities which

- [ ] Enable you to add several entities in the speed of light
- [ ] Edit these entities forms afterward
- [ ] Gain efficiency
- [ ] Need maybe some fine tuning

![image](https://github.com/qgis/QGIS/assets/8614223/18b67daf-f7ee-4fdf-a376-8e9b429cd582)

BUT when dealing with a non spatial layer :

- [ ] Since clicking on the map won't trigger anything you will be stuck after adding your first entity:

![image](https://github.com/qgis/QGIS/assets/8614223/3b70814a-5081-43bd-9cdd-4e410e3c9c11)

Meaning you will have to :

- [ ] Either stop and start editing to create a new entity
- [ ] Go through the attribute table and add entities through that way

### Steps to reproduce the issue

1. Add a non spatial table to your projet
2. Start editing
3. Add an entity
4. You can't add a second entity

### Versions

Version de QGIS
3.34.4-Prizren
Révision du code
decd43dc
Version de Qt
5.15.3
Version de Python
3.9.18
Version de GDAL/OGR
3.8.4
Version de Proj
9.3.1
Version de la base de données du registre EPSG
v10.098 (2023-11-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.41.1
Version de PDAL
2.6.0
Version du client PostgreSQL
16.1
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
document_management_system
0.3.3
DPFE
1.3.7
EasyImport
3.5.0
geomapfish_locator
1.3.3
linking_relation_editor
v1.2.0
ordered_relation_editor
0.2.8
pg_history_viewer
2.2
qfieldsync
v4.8.0
qgepplugin
dev
QgisModelBaker
v7.8.1
teksi_wastewater
0.0.0
trackable_project_files
v1.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ponceta, thanks for reporting. It seems to me the issue reported by you has been already previously reported https://github.com/qgis/QGIS/issues/55092.
