### ISSUE TITLE
regexp and /

### ISSUE THREAD

**Issue by EulenspiegelTill** [qgis/QGIS#57111]
### What is the bug or the crash?

Was using a regexp_replace in Layout, to get clean atlas output names and no subfolders. With the update to 3.34 expressiosn with regexp_replace and / seem not to be working anymore

### Steps to reproduce the issue

1. expression
2. 
regexp_replace('QGIS SHO/ULD ROCK','\\sSHO/ULD\\s',' DOES ')  -->'QGIS SHO/ULD ROCK'
expectect behaviour: → 'QGIS DOES ROCK'

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.4-Prizren | QGIS code revision | 1e052ed1f5e
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 12.7
  |   |   |  
Active Python plugins
qfieldsync | v4.9.1
volume_calculation_tool | 0.4
GroupStats | 2.2.7
swiss_locator | 2.0.8
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20

</body></html>QGIS version
3.34.4-Prizren
QGIS code revision
[1e052ed1f5e](https://github.com/qgis/QGIS/commit/1e052ed1f5e)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 12.7

Active Python plugins
qfieldsync
v4.9.1
volume_calculation_tool
0.4
GroupStats
2.2.7
swiss_locator
2.0.8
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
this works:
```regexp_replace('QGIS SHO/ULD ROCK','SHO/ULD',' DOES ')```
