### ISSUE TITLE
gdal_merge.bat replaced by gdal_merge.py

### ISSUE THREAD

**Issue by ArchGuyWu** [qgis/QGIS#57147]
### What is the bug or the crash?

gdal_merge.bat no longer exists, and gdal_merge.py accepts the same parameters as gdal_merge.bat.

### Steps to reproduce the issue

1. Go to 'Toolbox' to search for 'merge'
2. Click on 'GDAL/Raster miscellaneous/Merge'
3. Input layers like dem, and run the tool

### Versions

QGIS version 3.36.1-Maidenhead
QGIS code branch Release 3.36
Qt version 5.15.13
Python version 3.11.8
GDAL/OGR version 3.8.4
PROJ version 9.3.1
EPSG Registry database version v10.098 (2023-11-24)
GEOS version 3.12.0-CAPI-1.18.0
SQLite version 3.45.2
PostgreSQL client version unknown
SpatiaLite version 5.1.0
QWT version 6.2.0
QScintilla2 version 2.14.1
OS version Windows Server 2022 Version 2009

Active Python plugins
db_manager 0.1.20
grassprovider 2.12.99
MetaSearch 0.3.6
processing 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

QGIS version: 3.36.1-Maidenhead
Qt version: 5.15.13
Python version: 3.11.8
GDAL version: 3.8.4
GEOS version: 3.12.0-CAPI-1.18.0
PROJ version: Rel. 9.3.1, December 1st, 2023
Algorithm started at: 2024-04-14T09:27:42
Algorithm 'Merge' starting…
Input parameters:
{ 'DATA_TYPE' : 5, 'EXTRA' : '', 'INPUT' : ['C:/Users/user/Downloads/dem/ASTGTM_N30E107W.img','C:/Users/user/Downloads/dem/ASTGTM_N30E108Y.img','C:/Users/user/Downloads/dem/ASTGTM_N31E107Q.img','C:/Users/user/Downloads/dem/ASTGTM_N31E108D.img','C:/Users/user/AppData/Local/Temp/processing_CgLFlI/fd728ed1143e4abe9ce1005eb922242c/OUTPUT.tif'], 'NODATA_INPUT' : None, 'NODATA_OUTPUT' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'PCT' : False, 'SEPARATE' : False }

GDAL command:
gdal_merge.bat -ot Float32 -of GTiff -o C:/Users/user/AppData/Local/Temp/processing_CgLFlI/de45273e07c046dc8c1b3136b292b43a/OUTPUT.tif --optfile C:/Users/user/AppData/Local/Temp/processing_CgLFlI/0d8749b4d030401db655fa1411b162f8/mergeInputFiles.txt
GDAL command output:
Process gdal_merge.bat failed to start. Either gdal_merge.bat is missing, or you may have insufficient permissions to run the program.
Execution failed after 0.02 seconds

Loading resulting layers
Algorithm 'Merge' finished

**Comment by agiudiceandrea** [comment]
@ArchGuyWu, please provide the full QGIS version as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") and the full processing log.

**Comment by ArchGuyWu** [comment]
> @ArchGuyWu, please provide the full QGIS version as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") and the full processing log.

modified

**Comment by agiudiceandrea** [comment]
@ArchGuyWu, how did you install QGIS?
QGIS on your system uses different versions of some libraries from the one used by QGIS installed on Windows using either the OSGeo4W network installer osgeo4w-setup.exe or the OSGeo4W stand-alone all-in-one installer QGIS-OSGeo4W-3.36.1-1.msi: e.g. Python 3.9.18, GEOS 3.12.1-CAPI-1.18.1, SQLite 3.41.1, ...

In particular, the gdal_*.bat files are contained in the python3-gdal OSGeo4W package and are installed by the OSGeo4W installers in the Python39 folder `\apps\Python39\Scripts\`.

**Comment by ArchGuyWu** [comment]
> @ArchGuyWu, how did you install QGIS? QGIS on your system uses different versions of some libraries from the one used by QGIS installed on Windows using either the OSGeo4W network installer osgeo4w-setup.exe or the OSGeo4W stand-alone all-in-one installer QGIS-OSGeo4W-3.36.1-1.msi: e.g. Python 3.9.18, GEOS 3.12.1-CAPI-1.18.1, SQLite 3.41.1, ...
> 
> In particular, the gdal_*.bat files are contained in the python3-gdal OSGeo4W package and are installed by the OSGeo4W installers in the Python39 folder `\apps\Python39\Scripts\`.

I got it from msys2.

**Comment by agiudiceandrea** [comment]
> I got it from msys2.

That is not an official installation method. I think you need to report the issue to the msys2 packagers or you have to to make the gdal_*.bat files available for QGIS on your system.

**Comment by ArchGuyWu** [comment]
Ok, can you tell me where qgis defined to use gdal_merge.bat in source code? I cannot find it.

**Comment by agiudiceandrea** [comment]
> Ok, can you tell me where qgis defined to use gdal_merge.bat in source code? I cannot find it.

https://github.com/qgis/QGIS/blob/9a6cb9ff47eb1d41d439f8d7d2eef63e11b2673b/python/plugins/processing/algs/gdal/merge.py#L182

**Comment by ArchGuyWu** [comment]
> > Ok, can you tell me where qgis defined to use gdal_merge.bat in source code? I cannot find it.
> 
> https://github.com/qgis/QGIS/blob/9a6cb9ff47eb1d41d439f8d7d2eef63e11b2673b/python/plugins/processing/algs/gdal/merge.py#L182

Thanks.
