### ISSUE TITLE
Model Designer - Model name in model designer main dialog not updating on load

### ISSUE THREAD

**Issue by onplot** [qgis/QGIS#57145]
### What is the bug or the crash?

When I open a model the name shown on the top bar does not update to the name of the currently loaded model - it seems to be stuck on a previously loaded model.

### Steps to reproduce the issue

Go to Processing>Model Designer the resulting Model Designer window displays "Model Designer - model" in the top bar of the dialog
![image](https://github.com/qgis/QGIS/assets/22997180/8df53abf-5941-4a0f-8850-69305b1cae81)

Go to Model>Open Model and in my case I'm loading a model called Bathymetry_Contours_for_laser_prep.model3
![image](https://github.com/qgis/QGIS/assets/22997180/326665a0-a977-42ee-b742-ebf7f361cde0)

For some reason the top bar of the dialog reverts to the name of a previously loaded model BUT I have also exited the model designer and QGIS and when I restart and follow the above steps I still get that model name!?
![image](https://github.com/qgis/QGIS/assets/22997180/0669ab44-d209-4654-840e-678770b9afb4)

### Versions

QGIS version
3.34.5-Prizren
QGIS code revision
4b308492
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AnotherDXF2Shape
1.3.1
citygen
0.3
clickfu
0.7
DEMto3D
3.51
Generalizer3
1.0
GeoCoding
2.19
OSMDownloader
1.0.3
processing_saga_nextgen
1.0.0
profile-manager
0.31
qgis-maptiler-plugin
3.2
Qgis2threejs
2.7.1
qgis_resource_sharing
1.0.0
QuickOSM
2.2.3
quick_map_services
0.19.33
slyr_community
5.0.0
tanaka_contours
0.8
TerrainShading
0.9.4
TomBio
3.4.2
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Mainly this is causing confusion when skipping between two models - because the loaded model name doesn't change I'm never sure whether any changes I've saved have been done to the right model which is wasting a lot of time

**Comment by nyalldawson** [comment]
Can you check what the model name is set to in the Model Properties panel?
