### ISSUE TITLE
Project file read error/Invalid Data Source

### ISSUE THREAD

**Issue by StrataHeritage** [qgis/QGIS#57159]
### What is the bug or the crash?

I am getting the following error when trying to open my GIS project file:

"Project file read error in file /Users/XXX/Documents/XXXX.qgs: error occurred while parsing element at line 1 column 1"

Invalid Data Source: /Users/XXXXX/Documents/XXXXX/Umu 95_ 087 rocks.shp is not a valid or recognized data source.

### Steps to reproduce the issue

Won't let me upload the project file

### Versions

QGIS version 3.34.5-Prizren

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Downloaded and installed the latest version, went to open the project and it came up with the logs above. Having viewed the other error logs herein they mention renaming the file name extension to .qgs from within the GIS, however QGS won't recognize the project file. When I try to open the .QGZ instead QGIS says that it cannot unzip the file (it's not zipped in its format on the drive).

Also tried moving the project folder onto my internal HD.

**Comment by agiudiceandrea** [comment]
@StrataHeritage, the .qgz project file is actually a zipped file archive containing a .qgs project file and other files: you can make a copy of it, rename the extension of the copy to .zip and open the .zip file to view and extract the contained files.

Are the "Umu 95_ 087 rocks.shp" ESRI Shapefile layer file and its sidecar files available in "/Users/XXXXX/Documents/XXXXX/"? Have you tried to create a new QGIS project and add such ESRI Shapefile layer to the new QGIS project? Is it correctly displayed?

Please provide the affected .qgz project file if it does not contain sensitive / non shareable data.

**Comment by StrataHeritage** [comment]
Hi @agiudiceandrea, 

Many thanks for taking the time and thought to get back to me with your recommendation. I have done as you suggested, however the archive utility on my iMac is unable to expand the zip file as its 'is in an unsupported format'. Attached is the file with the extension changed to .zip and the original project:


[Waipapa GIS.zip](https://github.com/qgis/QGIS/files/14992510/Waipapa.GIS.zip)
[Archive.zip](https://github.com/qgis/QGIS/files/14992687/Archive.zip)

 Thank you again :)

**Comment by agiudiceandrea** [comment]
@StrataHeritage, unfortunately the provided files "Waipapa GIS.qgs", "Waipapa GIS.qgs~" and "Waipapa GIS.qgz" in Archive.zip don't contain any project data: they are all filled by zeroes. It is not possible that opening either such "Waipapa GIS.qgs" or "Waipapa GIS.qgz" using QGIS the "Invalid Data Source: /Users/XXXXX/Documents/XXXXX/Umu 95_ 087 rocks.shp is not a valid or recognized data source." error message will be displayed, since there is no data source info in such project files.

**Comment by donlab78** [comment]
It happened to me as well with version 3.44.9-Solothurn. I tried removing the tilde from the backup file, but it still appears to be corrupted. I also tried compressing the file by changing the extension to .zip. When opening the .zip file, it also appears to be corrupted
