### ISSUE TITLE
Decimal Places of QGIS Longitude and Latitude are too long

### ISSUE THREAD

**Issue by flyingQian** [qgis/QGIS#57156]
### What is the bug or the crash?

The decimal places of longitude and latitude in the copied WKT format are too long。If there are too many vertices in a polygon, it will exceed the length of Excel cells and cannot be processed using Excel for vertex longitude and latitude. Can we shorten the decimal places of the copied WKT format coordinates?

### Steps to reproduce the issue

MultiPolygon (((103.71372700000000577 30.86349200000000081, 103.71575699999999642 30.86021399999999915, ......

### Versions

QGIS
3.32.3-Lima

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by jgrocha** [comment]
Hi @flyingQian,

1) You should fill the "Steps to reproduce the issue" section.

2) In QGIS, you can choose the precision of WKT strings.

Example:

```python
print( QgsGeometry.fromWkt( 'Point Z (0.12345678 0.12345678 0.12345678)' ).asWkt(3) )
```
Output:
```text
PointZ (0.123 0.123 0.123)
```
The method `asWkt()` has an [optional parameter to indicate the precision](https://qgis.org/pyqgis/3.0/core/Geometry/QgsGeometry.html?highlight=wkt#qgis.core.QgsGeometry.asWkt).

I don't consider this a bug and I'll close it for now.

Please reopen it if you can provide a better context.
