### ISSUE TITLE
Georeferencer doesn't render SVG vector images

### ISSUE THREAD

**Issue by nans207** [qgis/QGIS#57162]
### What is the bug or the crash?

When trying to georeference svg vector images, the georeferencer window stays blank. This was tested with several different .svg files.

### Steps to reproduce the issue

1. Click Layer>Georeferencer to open the georeferencer
2. click the vector icon to open a vector image
3. select and open an svg vector image
4. The area where the georefencer usually displays georeferencable data stays blank.

### Versions

 Item|Version|_|_  
-- | -- | -- | --
QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453264
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
QuickOSM | 2.2.3
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I tested a few different svg files to make sure i didn't use a corrupt one.

**Comment by nyalldawson** [comment]
The georeferencer relies on gdal's svg driver, which currently only supports svgs made by "Cloudmade Vector Stream Server"

See https://gdal.org/drivers/vector/svg.html

Closing as an upstream feature request
