### ISSUE TITLE
SQL server tables do not show while connected

### ISSUE THREAD

**Issue by LStensson** [qgis/QGIS#57168]
## User Feedback

Cannot connect to sql server

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00003fa4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QMutex::lock :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsVectorLayerFeatureIterator::close :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.15-Firenze
QGIS code revision: 252ad49ddc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

## User Feedback

Cannot connect to sql server

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00003fa4 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QMutex::lock :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsVectorLayerFeatureIterator::close :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.15-Firenze
QGIS code revision: 252ad49ddc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Versions

3.28.15

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Steps to reproduce?
