### ISSUE TITLE
Unable to load a spatialite layer with Point Z geometry 

### ISSUE THREAD

**Issue by florentfgrs** [qgis/QGIS#57169]
### What is the bug or the crash?

Impossible to load a spatialite table in QGIS when it has a geometry of type Z Point when I use sql query and PyQGIS

### Steps to reproduce the issue

I have a spatialite base named `base.sqlite` and in it I have a table structured like this : 

**table** :
id | x | y | z | srid 
-- | -- | -- | -- | --| 
1 | 5 | 5 | 0 | 4326 

I want to load this table into QGIS with a PyQGIS script, so I do: 

```python
sql = ("SELECT id,  MakePointZ(x,y,z,srid) as geom FROM the_table")

dbpath = '/path/to/my/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
QgsProject.instance().addMapLayer(layer)
```
Résult : 

![image](https://github.com/qgis/QGIS/assets/36446612/94d513a4-feaa-48c0-979a-9b1689eb4d3e)

Whereas if I build my point without the Z it's fine.

```python
sql = ("SELECT id,  MakePoint(x,y,srid) as geom FROM the_table")

dbpath = '/path/to/my/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
QgsProject.instance().addMapLayer(layer)
```
![image](https://github.com/qgis/QGIS/assets/36446612/b1cee9e1-9319-4672-8396-2c6afcd5d54f)

### Versions

![image](https://github.com/qgis/QGIS/assets/36446612/695d024d-9923-42c3-98d9-86ed578ea57a)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

#### Without Z

```python
sql = ("SELECT id,  MakePoint(x,y,srid) as geom FROM the_table")
dbpath = '/path/to/my/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
print(layer.geometryType())
print(layer.wkbType())
```
Résult : 
```python
GeometryType.Point
WkbType.Point
```

#### With Z

```python
sql = ("SELECT id,  MakePointZ(x,y,z,srid) as geom FROM the_table")
dbpath = '/path/to/my/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
print(layer.geometryType())
print(layer.wkbType())
```
Résult : 
```python
GeometryType.Unknown
WkbType.Unknown
```

_No response_

**Comment by agiudiceandrea** [comment]
@florentfgrs, thanks for reporting. It would be useful if you provided a SpatiaLite table with which the issue occur.

**Comment by florentfgrs** [comment]
@agiudiceandrea Of course, here's a simple database to reproduce the error. 
[base.sqlite.zip](https://github.com/qgis/QGIS/files/15011852/base.sqlite.zip)

Or the table creation script : 

```sql
-- Création de la table
CREATE TABLE IF NOT EXISTS the_table (
    id INTEGER PRIMARY KEY,
    x DECIMAL,
    y DECIMAL,
    z DECIMAL,
    srid INTEGER
);

-- Ajout d'une ligne
INSERT INTO the_table (id, x, y, z, srid) VALUES (1, 5, 5, 2, 4326);
```

**Comment by lbartoletti** [comment]
More information (maybe not related to the problem):

> 2024-04-17T16:13:39     WARNING    Erreur SQLite : no such column: the_table
>              SQL: SELECT sql FROM sqlite_master WHERE type='table' AND name="the_table"

Here, it's quoted with " instead of ' : 

https://github.com/qgis/QGIS/blob/master/src/providers/spatialite/qgsspatialiteprovider.cpp#L932

**Comment by agiudiceandrea** [comment]
@lbartoletti, I can replicate exactly the behavior reported by @florentfgrs.

Extracting base.sqlite from the provided base.sqlite.zip in `/path/`

- executing:

```python
sql = ("SELECT id,  MakePoint(x,y,srid) as geom FROM the_table")

dbpath = '/path/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
QgsProject.instance().addMapLayer(layer)
```
a valid layer named Query (Source: `dbname='C:/Users/Andrea/Downloads/base.sqlite' table='(SELECT id, MakePoint(x,y,srid) as geom FROM the_table)' (geom)`, Provider: `spatialite`, Geometry: `Point (Point)`, CRS Name: `EPSG:4326 - WGS 84`) is added to the project

- while executing:

```Python
sql = ("SELECT id,  MakePointZ(x,y,z,srid) as geom FROM the_table")

dbpath = '/path/base.sqlite'
uri = f"dbname='{dbpath}' table='({sql})' (geom)"
layer = QgsVectorLayer(uri, "Query", "spatialite")
QgsProject.instance().addMapLayer(layer)
```
a "Unavailable" layer named Query (Source: `dbname='C:/Users/Andrea/Downloads/base.sqlite' table='(SELECT id, MakePointZ(x,y,z,srid) as geom FROM the_table)' (geom)`, Provider: `spatialite`) is added to the project and the following warning is logged in the SpatiaLite tab of the Log Messages panel:

```
2024-04-17T17:17:15     WARNING    SQLite error: unknown cause
             SQL: SELECT srid("geom"), geometrytype("geom") FROM (SELECT id, MakePointZ(x,y,z,srid) as geom FROM the_table) as "subQuery_0" limit 1
```

**Comment by agiudiceandrea** [comment]
It looks like the issue is due to the fact that the "POINT Z" geometry type is not correctly recognized by the spatialite data provider in `QgsSpatiaLiteProvider::getQueryGeometryDetails()`:

https://github.com/qgis/QGIS/blob/dd0412da898d7b85938c7654115353b9947838a5/src/providers/spatialite/qgsspatialiteprovider.cpp#L5738-L5763
