### ISSUE TITLE
Rubberband/digitizing not working correctly with snapping after database trigger has normalized polygon with inner ring during saving

### ISSUE THREAD

**Issue by rnousia** [qgis/QGIS#57181]
### What is the bug or the crash?

If a polygon with inner ring is changed in the database with trigger after saving edits (e.g. due to normalization of polygon), rubberband snaps to old vertices and not to the updated ones if the inner ring is used as snapping target.  This looks very confusing to the user although in some cases the actual snapping seems to work (maybe if the digitized ring was symmetrical?) and resulting feature is created as digitized.

The problem occurs only with inner rings and only if digitizing + saving is done in a specific order. So it is quite difficult to reproduce but at least the steps in the following section describe one case where this issue occurs.

![snapping-issue](https://github.com/qgis/QGIS/assets/12234068/51842264-b7ad-4ebc-8d59-2a4b313c124c)
Here the digitized ring also seems to be incorrect (not the using the vertices snapped).

### Steps to reproduce the issue

1. Create tables with trigger that normalizes geometry before insert or update (tested with postgis database):
```sql
-- create trigger function to normalize polygons
CREATE OR REPLACE FUNCTION public.normalize_geom()
RETURNS trigger AS $$
BEGIN
  NEW.geom = ST_Normalize(NEW.geom);
  RETURN NEW;
END; $$ LANGUAGE 'plpgsql';

-- create test tables
CREATE TABLE normalized_polygons_1
(
    id bigserial NOT NULL,
    geom geometry(POLYGON, 3067),
    CONSTRAINT "PK_normalized_polygons_1" PRIMARY KEY (id)
);

CREATE TABLE normalized_polygons_2
(
    id bigserial NOT NULL,
    geom geometry(POLYGON, 3067),
    CONSTRAINT "PK_normalized_polygons_2" PRIMARY KEY (id)
);

-- create triggers
CREATE TRIGGER normalize_geom
BEFORE INSERT OR UPDATE ON normalized_polygons_1
FOR EACH ROW EXECUTE PROCEDURE public.normalize_geom();

CREATE TRIGGER normalize_geom
BEFORE INSERT OR UPDATE ON normalized_polygons_2
FOR EACH ROW EXECUTE PROCEDURE public.normalize_geom();
```

2. Add layers to QGIS and digitize a polygon to both layers that are overlapping each other, like so:
<img width="614" alt="initial-polygons" src="https://github.com/qgis/QGIS/assets/12234068/3c5bddc6-b484-4e8f-ac0a-132e24239223">

3. Save edits on all layers (this is important step as the issue only happens if layer is saved before adding the inner ring)
4. Add a ring to one of the layers and save edits (again, saving must be done at this step, otherwise everything works correctly in next step)
6. Start adding ring to the other layer with vertex snapping on -> digitized rubberband is drawn to wrong vertices

I couldn't figure any way to reset this behaviour once it starts happening. Also, as mentioned in the steps, this only occurs if edits are saved after each step **and** layer is not changed before saving the first ring creation.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.5
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.1-Maidenhead
QGIS code revision
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
Is this also a #31251 duplicate?

**Comment by Djedouas** [comment]
Reproduced on master https://github.com/qgis/QGIS/commit/623ceab11d8

With a more simple test case, on one polygon only:

https://github.com/user-attachments/assets/62a5b29a-b975-46fa-94a6-16dca375154f

It seems to be related to how the vertices order is not updated in the cache, when saving after a modification action, but it is updated when saving after digitizing a new feature.

This vertex confusion stays even after digitizing other features.

A refresh via the toolbar ![image](https://github.com/user-attachments/assets/da8326ca-cfc5-4c3c-9f17-c6aa96cd2be2) reorders everything.

I will investigate further into the code.

**Comment by Djedouas** [comment]
Having the vertex tool cache and the snapping index always synced with the map canvas (which is always up-to-date with the latest geometries) can fix this issue, as well as #57784 and #31251, and is being discussed in https://github.com/qgis/QGIS-Enhancement-Proposals/issues/275

A PyQGIS macro workaround can be found here https://github.com/MorriganR/index_updater/blob/master/README.md

**Comment by Djedouas** [comment]
Another solution is to check the layer itself in `Dependencies` section of the layer properties.

In this way, every change on the layer will trigger a full refresh of the data, caches, and rubber bands.

**Comment by rnousia** [comment]
Thank you for the workaround suggestions. We tried these and using "refresh layer on notification" option did solve the issue but unfortunately this created a new one: each layer with the option enabled seems to create a new Postgresql connection and therefore the maximum connection limit is reached at some point. We have about 100 layers and 100 users so this would result in 10 000+ extra connections? I tested this with QGIS-3.34.3-1 though and QGIS crashed if number of layers exceeded database's max_connection-setting (the crashing may have been fixed in https://github.com/qgis/QGIS/issues/54260 but not sure if the number of connections used is fixed).

However, we came up with a 3rd workaround: reloading the layer after the layer is saved. This seems to fix vertex ordering.

```python
# pseudo code, not actually tested with this
layer.afterCommitChanges.connect(lambda: layer.reload())
```

**Comment by Djedouas** [comment]
> each layer with the option enabled seems to create a new Postgresql connection and therefore the maximum connection limit is reached at some point. We have about 100 layers and 100 users so this would result in 10 000+ extra connections?

@troopa81 What are your thoughts about this?
