### ISSUE TITLE
Build from source on Ubuntu get segmentation fault

### ISSUE THREAD

**Issue by TerryBryant** [qgis/QGIS#57194]
### What is the bug or the crash?

Segmentation fault (core dumped)
make[2]: *** [src/crssync/CMakeFiles/synccrsdb.dir/build.make:71: src/crssync/CMakeFiles/synccrsdb] Error 139
make[1]: *** [CMakeFiles/Makefile2:8228: src/crssync/CMakeFiles/synccrsdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

### Steps to reproduce the issue

```
cmake ..
make -j8
```
The process stuck at ```make -j8```

### Versions

3.28.14

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@TerryBryant, thanks for reporting. QGIS 3.28 is no longer supported. Please actually try with a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

**Comment by jef-n** [comment]
Report too short to be useful. BTW the "regular" build on Debian/Ubuntu uses ninja.

**Comment by TerryBryant** [comment]
> Report too short to be useful. BTW the "regular" build on Debian/Ubuntu uses ninja.

Below are the output log of ```make -j8```,
[output.log](https://github.com/qgis/QGIS/files/15056696/output.log)

and the rest of output are
```
/usr/bin/ld: warning: libproj.so.22, needed by /lib/x86_64-linux-gnu/libgeotiff.so.5, may conflict with libproj.so.25
/usr/bin/ld: warning: libproj.so.22, needed by /lib/x86_64-linux-gnu/libgeotiff.so.5, may conflict with libproj.so.25
/usr/bin/ld: warning: libproj.so.22, needed by /lib/x86_64-linux-gnu/libgeotiff.so.5, may conflict with libproj.so.25
Segmentation fault (core dumped)
make[2]: *** [src/crssync/CMakeFiles/synccrsdb.dir/build.make:71: src/crssync/CMakeFiles/synccrsdb] Error 139
make[1]: *** [CMakeFiles/Makefile2:7296: src/crssync/CMakeFiles/synccrsdb.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
sip-build: '/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -recursive QGIS.pro' failed returning 3
make[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/build.make:815: python/core/build/_core/sip_corepart0.cpp] Error 1
make[2]: *** Deleting file 'python/core/build/_core/sip_corepart0.cpp'
make[1]: *** [CMakeFiles/Makefile2:8200: python/CMakeFiles/python_module_qgis__core.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

**Comment by jef-n** [comment]
Looks like a local proj issue to me. And that doesn't happen w/o `-j8`.

**Comment by TerryBryant** [comment]
> Looks like a local proj issue to me. And that doesn't happen w/o `-j8`?

That happens during make period, w/o -j8 just means whether to use multi process.

**Comment by TerryBryant** [comment]
> Looks like a local proj issue to me. And that doesn't happen w/o `-j8`?

Hello, any advice? I‘m really stucked at here.

**Comment by jef-n** [comment]
> `libproj.so.22, needed by /lib/x86_64-linux-gnu/libgeotiff.so.5, may conflict with libproj.so.25`

Seems to be a local conflict - you have two versions of proj installed and are trying to use both at once.

**Comment by TerryBryant** [comment]
> > `libproj.so.22, needed by /lib/x86_64-linux-gnu/libgeotiff.so.5, may conflict with libproj.so.25`
> 
> Seems to be a local conflict - you have two versions of proj installed and are trying to use both at once.

I removed the redundant proj, now the warning disappeared. But I still get below error message
```
sip-build: '/usr/lib/x86_64-linux-gnu/qt5/bin/qmake -recursive QGIS.pro' failed returning 3
make[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/build.make:815: python/core/build/_core/sip_corepart0.cpp] Error 1
make[2]: *** Deleting file 'python/core/build/_core/sip_corepart0.cpp'
make[1]: *** [CMakeFiles/Makefile2:8200: python/CMakeFiles/python_module_qgis__core.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
```

I think the problem is more likely to related to sip/sip_corepart0, but I really don't know how to fix it.
