### ISSUE TITLE
Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)

### ISSUE THREAD

**Issue by swiss-knight** [qgis/QGIS#57201]
### What is the bug or the crash?

Hello,

when trying to load the QGIS processing toolbox from a standard Python 3.10.12 console on Ubuntu 22.04.4 LTS (Jammy Jellyfish), the following error is raised before a crash dump: `Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)`

### Steps to reproduce the issue

On Ubuntu 22.04.4 LTS (Jammy Jellyfish), having Python 3.10.12 and QGIS 3.34.5 installed:
```
# python3
Python 3.10.12 (main, Nov 20 2023, 15:14:05) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis import processing
Cannot mix incompatible Qt library (5.15.3) with this library (5.15.2)
Aborted (core dumped)
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453264
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.4
swissgeodownloader | 2.0.1
kart | 1.0.14
Serval | 3.32.0
qgis-maptiler-plugin | 3.3
interlis | 0.14.8
QuickWKT | 3.1
changeDataSource | 3.1
linking_relation_editor | v1.3.0
QgisModelBaker | v7.8.3
helloworld | 0.1
profiletool | 4.2.6
QuickOSM | 2.2.3
pluginbuilder3 | 3.2.1
quick_map_services | 0.19.34
gmsh | version 0.2.2
oneatlas-qgis-plugin-1_0_1 | 1.3.0
crayfish | 3.6.0
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6
grassprovider | 2.12.99

</body></html>QGIS version
3.36.1-Maidenhead
QGIS code revision
[3e589453264](https://github.com/qgis/QGIS/commit/3e589453264)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.4 LTS

Active Python plugins
plugin_reloader
0.9.4
swissgeodownloader
2.0.1
kart
1.0.14
Serval
3.32.0
qgis-maptiler-plugin
3.3
interlis
0.14.8
QuickWKT
3.1
changeDataSource
3.1
linking_relation_editor
v1.3.0
QgisModelBaker
v7.8.3
helloworld
0.1
profiletool
4.2.6
QuickOSM
2.2.3
pluginbuilder3
3.2.1
quick_map_services
0.19.34
gmsh
version 0.2.2
oneatlas-qgis-plugin-1_0_1
1.3.0
crayfish
3.6.0
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6
grassprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Apt version table:

```
# apt-cache policy qgis
qgis:
  Installed: 1:3.36.1+36jammy
  Candidate: 1:3.36.1+36jammy
  Version table:
 *** 1:3.36.1+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
        100 /var/lib/dpkg/status
     1:3.36.0+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
     1:3.34.3+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
     1:3.34.2+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
     1:3.34.1+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
     1:3.34.0+36jammy 500
        500 https://qgis.org/ubuntu jammy/main amd64 Packages
     3.22.4+dfsg-3build1 500
        500 http://ch.archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
```

Any further information would be added here.

**Comment by agiudiceandrea** [comment]
@swiss-knight, thanks for reporting. Isn't Python3 version 3.10.6 on Ubuntu 22.04 https://packages.ubuntu.com/jammy/python3 ?
