### ISSUE TITLE
SQL console in QGIS Browser can't run just the selected part of an SQL statement (unlike DB Manager SQL console)

### ISSUE THREAD

**Issue by gioman** [qgis/QGIS#57202]
### What is the bug or the crash?

Title says it all. Also notice that the "clear" and "execute" buttons are not placed where expected... I find myself all the time pressing "clear" instead of "execute", and the damn thing does not even support undo (when pressing "clear").

### Steps to reproduce the issue

Title says it all.

### Versions

3.34.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by gioman** [comment]
> I find myself all the time pressing "clear" instead of "execute"

because of course in DB Manager that we all use since ages, that buttons order is inverted.

**Comment by gioman** [comment]
My bad, definitively a feature request and not a bug. Also apologies for the harsh comment: I had just wiped out a very complex query and just found there was no UNDO.

**Comment by nyalldawson** [comment]
@gioman 
> I had just wiped out a very complex query and just found there was no UNDO.

Try this (from the qgis python console):

```
w=QgsHistoryWidget("dbquery")
w.show()
```

Should give you a dialog listing a history of all sql executed from the browser :+1:
