### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by Exodia1217** [qgis/QGIS#57213]
### What is the bug or the crash?

I opened QGIS Firenze. Clicked on the project I wanted to open containing bathymetry dem maps from gebco. Then a small blank tab with the logo of QGIS in the upper left corner of the tab appeared for a minute or two. Then a tab appeared with the message "QGIS ended unexpectedly" with the report details as well as the options reload QGIS or Quit.

### Steps to reproduce the issue

Open QGIS Firenze. Click on a project containing bathymetry dem maps from gebco. Then a small blank tab with the logo of QGIS in the upper left corner of the tab appears for a minute or two. Then a tab appears with the message "QGIS ended unexpectedly" with the report details as well as the options Reload QGIS or Quit. Click Reload QGIS. QGIS doesn't reload. Open QGIS again. Click on a project containing bathymetry dem maps from gebco. The same thing happens all over again.

### Versions

3.28.5-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Report details:

## User Feedback

I opened QGIS Firenze. Clicked on the project I wanted to open. Then a small blank tab with the logo of QGIS in the upper left corner of the tab appeared for a minute or two. Then a tab appeared with the message "QGIS ended unexpectedly" with the report details as well as the options reload QGIS or Quit.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000048d0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.5-Firenze
QGIS code revision: 50adba36f2
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.6.3
Running against GDAL: 3.6.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

**Comment by agiudiceandrea** [comment]
Hi @Exodia1217, QGIs 3.28 is no longer supported. Please actually try if the issue occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it does, please provide sample project / layer(s) with which the issue occurs and / or detailed step by step instruction to reproduce the issue.
