### ISSUE TITLE
Annotation not drawing from annotation layer - QGIS 3.36

### ISSUE THREAD

**Issue by imperialbeachca** [qgis/QGIS#57223]
### What is the bug or the crash?

I have created an annotation layer in QGIS.  This layer has about 215 entries which are "Text at a point".  These were created using current versions of QGIS in the last 6 months, starting Nov. 2023.  I have been busy on other projects and just came back to this one.  In the meantime, I upgraded QGIS to 3.36.0-Maidenhead.  Now, when I open the project, the annotation objects are not showing up on the map.  They are still visible in the count of objects on the layer.
I am not sure what is causing them to not show up.  Any ideas would be greatly appreciated.

### Steps to reproduce the issue

1. Using version of QGIS prior to 3.36.0, on Annotation toolbar, create New Annotation Layer
2. Create "Text Annotation at Point" entries on this layer.  I used all text, no backgrounds or leader lines.
3. Upgrade QGIS to 3.36.0
4. Annotation layer shows in table of contents.  Selecting "Properties", shows count of features in Annotation layer.  Features do not show up on map.
![ScreenConnect WindowsClient_2aiFiPqAG9](https://github.com/qgis/QGIS/assets/51243816/3b81b7b6-6ade-47e0-83be-2a52c6ef822f)

### Versions

QGIS version
3.36.0-Maidenhead
QGIS code revision
09951dc0
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
AppendFeaturesToLayer
2.0.0
clipper
1.2
create_layer_from_selected_features
1.2
DigitizingTools
1.5.2
LAStools
2.1.0
latlontools
3.6.20
Mergin
2024.1
qgis_resource_sharing
1.0.0
quick_map_services
0.19.34
SelectWithin
0.4
slyr_community
5.0.0
splitmultipart
1.0.0
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Not sure what else to add here.  Pretty frustrating that this is not showing up anymore and no indication that it is broken in some way.  I can't tell if there is a setting somewhere that I am missing which would make it not display any longer, or something.  I asked for any input on twitter, but that is a black hole these days, so this is sort of my last resort for assistance.

**Comment by nyalldawson** [comment]
@imperialbeachca could you share your project here?

**Comment by imperialbeachca** [comment]
Project is attached.
[FireStation_WallMap.zip](https://github.com/qgis/QGIS/files/15068573/FireStation_WallMap.zip)

**Comment by nyalldawson** [comment]
Ok, fix in https://github.com/qgis/QGIS/pull/57224

To repair this project, select the annotation layer and then from the QGIS python console run:

```
for i in iface.activeLayer().items().values():
    i.setEnabled(True)
```

**Comment by imperialbeachca** [comment]
Nyall,
That did the trick.  Thank you so much for your quick response, I really appreciate it!
Russell
