### ISSUE TITLE
Running Topology Checker more than once causes crash

### ISSUE THREAD

**Issue by esnyder-rve** [qgis/QGIS#57222]
### What is the bug or the crash?

QGIS crashes with an Access Violation when running the topology checker more than once (fix an issue, then re-run checker).

### Steps to reproduce the issue

1. Open polygon dataset (parcels in this case)
2. Setup topology checker rules:
    * Parcel layer must not have invalid geometry
    * Parcel layer must not have gaps
    * Parcel layer must not have overlaps
3. Run topology check
4. Edit geometry to fix an error
5. Save edits
6. Re-run topology check
7. QGIS Crash (Access Violation)

### Versions

| QGIS version|3.36.1-Maidenhead|
| -- | -- |
| QGIS code revision | 3e589453 |
| Qt version | 5.15.13 |
| Python version | 3.12.3 |
| GDAL/OGR version | 3.8.5 |
| PROJ version | 9.4.0 |
| EPSG Registry database version | v11.004 (2024-02-24) |
| GEOS version | 3.12.1-CAPI-1.18.1 |
| SQLite version | 3.45.1 |
| PDAL version | 2.6.3 |
| PostgreSQL client version | 16.2 |
| SpatiaLite version | 5.1.0 |
| QWT version | 6.2.0 |
| QScintilla2 version | 2.14.1 |
| OS version | Windows 10 Version 2009 |

| Active Python plugins | |
| -- | -- |
| MemoryLayerSaver |5.0.2 |
|db_manager |0.1.20 |
| grassprovider |2.12.99 |
| MetaSearch |0.3.6 |
| processing |2.12.99 |

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006b78 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```
QVariant::QVariant :
version :
QAbstractProxyModel::headerData :
QSortFilterProxyModel::headerData :
QHeaderView::paintSection :
QHeaderView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QHeaderView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:602
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:602
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QProgressDialog::setValue :
QObject::qt_static_metacall :
version :
version :
version :
version :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:602
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:602
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1834
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by agiudiceandrea** [comment]
@esnyder-rve, thanks for reporting. It seems to me the issue has been already previously reported at https://github.com/qgis/QGIS/issues/53425. Is https://github.com/qgis/QGIS/issues/53425 the same issue as the one reported by you?

**Comment by esnyder-rve** [comment]
@agiudiceandrea
Yes, this does appear to be a duplicate.

**Comment by lbartoletti** [comment]
Closed, duplicate.
