### ISSUE TITLE
Geoarrow geometries not rendered in QGIS 3.36.2 & 3.34.6

### ISSUE THREAD

**Issue by freeshrugsxd** [qgis/QGIS#57228]
### What is the bug or the crash?

Hey,

since the update .arrow or .parquet files are not rendered on the map canvas anymore if GEOARROW was set as geometry encoding during export.

I expect that https://github.com/jef-n/OSGeo4W/commit/cf3e48835a676262507d9d30385792702354756d has something to do with this.

### Steps to reproduce the issue

load files and note that _geoarrow.* files are not rendered on the map canvas whereas the _wkb.* files of the same file type are rendered
[geoarrow_vs_wkb_test_data.zip](https://github.com/qgis/QGIS/files/15075279/geoarrow_vs_wkb_test_data.zip)

### Versions

| QGIS version | 3.36.2-Maidenhead |
| -- | -- |
| QGIS code revision | 6d250527 |
| Qt version | 5.15.13 |
| Python version | 3.12.3 |
| GDAL/OGR version | 3.8.5 |
| PROJ version | 9.4.0 |
| EPSG Registry database version | v11.004 (2024-02-24) |
| GEOS version | 3.12.1-CAPI-1.18.1 |
| SQLite version | 3.45.1 |
| PDAL version | 2.6.3 |
| PostgreSQL client version | 16.2 |
| SpatiaLite version | 5.1.0 |
| QWT version | 6.2.0 |
| QScintilla2 version | 2.14.1 |
| OS version | Windows 10 Version 2009 |

Active Python plugins | |
| -- | -- |
db_manager | 0.1.20 |
grassprovider | 2.12.99 |
MetaSearch | 0.3.6 |
processing | 2.12.99 |

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

got the msi from the norbit download mirror

**Comment by rouault** [comment]
ok, this is actually a GDAL bug that was introduced in 3.8.5 per https://github.com/OSGeo/gdal/commit/a554f27d6a7519eea2f00ebe85ca58d3c48be894. I've reverted in the 3.8 branch per https://github.com/OSGeo/gdal/commit/4cd5e33285204ea798f7f498db6cede388ed5552 . But there won't be any 3.8 release any more at that point. However the 3.9 release that should land beginning of May won't have this issue, so this is a matter of waiting for QGIS to be updated to it.
