### ISSUE TITLE
Repeated Crash when using Reshape Feature Tool

### ISSUE THREAD

**Issue by Nick2253** [qgis/QGIS#57225]
### What is the bug or the crash?

I'm working on digitizing historical political borders based on old maps.  Regularly (at least 5-10% of the time), when I right-click to complete a polygon reshape using the Reshape Feature tool, QGIS crashes (see stack trace below).

In other QGIS work that I've done, I've never encountered this kind of instability.  With a fresh install of QGIS and a fresh profile, I'm seeing the same behavior.

It doesn't appear to matter how complicated my polygons are, as I've had it crash when adding just a few vertices, and I've also had it work when adding thousands.  If it crashes (apart from one case, where it happened twice in a row) it always works after I re-open QGIS.

I'm not sure if it's relevant, but I'm using the snap feature to trace some of the existing geometries.

### Steps to reproduce the issue

1. Create a new layer (if it matters, I'm using a GeoPackage Layer of geometry MultiPolygon).
2. Create a polygon in the layer.
3. Using the "Reshape Features" tool from the Advanced Digitizing toolbar, reshape the polygon to add new area.
 a. If it matters, use the snap tool and tracing to trace at least part of some existing geometry as part of the reshape process.
4. Right click to complete, and observe QGIS crashing.
 a. (Happens about 5-10% of the time)

### Versions

QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

```Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000015b8 (most recent call first):



Stack Trace


QgsPointXY::QgsPointXY :
QgsVectorLayerEditUtils::addTopologicalPoints :
QgsVectorLayer::addTopologicalPoints :
QgsMapToolReshape::reshape :
QgsMapToolReshape::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045
```

**Comment by agiudiceandrea** [comment]
@Nick2253, does the issue also occur using QGIS 3.34 or previous versions?

**Comment by Nick2253** [comment]
@agiudiceandrea It's possible, but I can't recall experiencing a crash.  However, I've never used the trace tool to the extent that I'm using it now, so it may be something that would have happened, but I never ran into the specific combinations that triggered it.

To add to the issue, I'm noticing that sometimes the trace tool does (for lack of a better term) a "loopback".  Not sure how well I can explain it, but imagine that you're using the trace tool to go from point A to B.  However, the trace isn't just from A to B, but goes past B, and then loops back along the same segment.  I've only noticed this three times, but twice it crashed, so I'm guessing that there's some weird geometry issue that's triggering the crash.

While experimenting, I've never been able to intentionally trigger this loopback.  Even in places where I experienced it in the first place, I've been unable to duplicate it.

**Comment by Nick2253** [comment]
I'm not entirely sure, but #49475 might be related.

**Comment by Nick2253** [comment]
It seems like I've finally found a repeatable example.

It appears to have something to do with invalid geometry.  As part of my project, I'm using Natural Earth's Land and Lakes vector shape files.  It appears that two of the lakes have invalid geometry, and if I get rid of everything else, I'm still getting a crash.

Attached is the Project file, along with three minimal GeoPackage files:  Map Data (my drawn map), Land data (just the single relevant polygon from the Natural Earth Land Data), and Lake data (just the invalid lakes from the Natural Earth Land Data).  Together, I've been able to reliably crash QGIS.

Here's a GIF of the process.  It doesn't show the error that pops up at the end, but rest assured it does, and it's the same as the stack trace from the original post.

![2024-04-24 10-37-17](https://github.com/qgis/QGIS/assets/926554/44bc422d-2d70-4e14-8e78-24f73c3074cc)

Zip folder with layer files: [Crash Test Map Layer.zip](https://github.com/qgis/QGIS/files/15098316/Crash.Test.Map.Layer.zip)

**Comment by bhjolly** [comment]
Am also having this issue with 3.38 (Mac, installed via conda-forge). My geometry is valid, I've found that tracing part of the existing poly makes it more likely to happen, as well as if the intended outcome could be ambiguous. I wouldn't care so much if the operation just failed, it's the hard crash causing loss of work that's getting to me.

**Comment by troopa81** [comment]
I manage to reproduce the issue, thanks @Nick2253. I'm gonna try to fix it.
