### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by celisantos** [qgis/QGIS#57221]
### What is the bug or the crash?

WHAT error is this?

<img width="942" alt="Captura de tela 2024-04-22 133904" src="https://github.com/qgis/QGIS/assets/88805319/963b61a0-fbc2-4e59-8b15-1401106aa936">

### Steps to reproduce the issue

When the program opens and I can't do anything

### Versions

Qgis 3.34.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Installation error

**Comment by agiudiceandrea** [comment]
@celisantos, you need to just click on the X icon 
![image](https://github.com/qgis/QGIS/assets/16253859/4f779c1b-202f-4cb2-9dcd-4df3c5ba02ea)
Please update to QGIS 3.34.6 as soon as it is available for your system.

**Comment by agiudiceandrea** [comment]
Hi @celisantos, thanks for reporting. The issue has been already reported and fixed.
You just need to click on the X icon 
![image](https://github.com/qgis/QGIS/assets/16253859/4f779c1b-202f-4cb2-9dcd-4df3c5ba02ea)
Please update to QGIS 3.34.6 as soon as it is available for your system. In the meantime you can disable such functionality, and thus avoid the display of the error, unchecking the "Automatically download missing, freely-licensed fonts" in Settings -> Options -> Fonts.

**Comment by celisantos** [comment]
thank you @agiudiceandrea for answer me.
