### ISSUE TITLE
qgis_core build is failing

### ISSUE THREAD

**Issue by rajiv2502** [qgis/QGIS#57236]
### What is the bug or the crash?

Creating library E:/OSGeo4W/QGIS/build64/src/core/Release/qgis_core.lib and object E:/OSGeo4W/QGIS/build64/src/core/Release/qgis_core.exp
3>absl_str_format_internal.lib(arg.cc.obj) : error LNK2019: unresolved external symbol __std_find_trivial_1 referenced in function "char const * __cdecl std::_Find_unchecked<char const *,char>(char const *,char const * const,char const &)" (??$_Find_unchecked@PEBDD@std@@YAPEBDPEBDQEBDAEBD@Z)
3>absl_strings.lib(charconv_bigint.cc.obj) : error LNK2001: unresolved external symbol __std_find_trivial_1
3>absl_str_format_internal.lib(arg.cc.obj) : error LNK2019: unresolved external symbol __std_find_trivial_2 referenced in function "private: static bool __cdecl absl::lts_20240116::str_format_internal::FormatArgImpl::Dispatch<wchar_t const *>(union absl::lts_20240116::str_format_internal::FormatArgImpl::Data,class absl::lts_20240116::str_format_internal::FormatConversionSpecImpl,void *)" (??$Dispatch@PEB_W@FormatArgImpl@str_format_internal@lts_20240116@absl@@CA_NTData@0123@VFormatConversionSpecImpl@123@PEAX@Z)
3>draco.lib(point_cloud.cc.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "int * __cdecl std::_Find_unchecked<int *,int>(int *,int * const,int const &)" (??$_Find_unchecked@PEAHH@std@@YAPEAHPEAHQEAHAEBH@Z)
3>absl_log_internal_log_sink_set.lib(log_sink_set.cc.obj) : error LNK2019: unresolved external symbol __std_find_trivial_8 referenced in function "class absl::lts_20240116::LogSink * * __cdecl std::_Find_unchecked<class absl::lts_20240116::LogSink * *,class absl::lts_20240116::LogSink *>(class absl::lts_20240116::LogSink * *,class absl::lts_20240116::LogSink * * const,class absl::lts_20240116::LogSink * const &)" (??$_Find_unchecked@PEAPEAVLogSink@lts_20240116@absl@@PEAV123@@std@@YAPEAPEAVLogSink@lts_20240116@absl@@PEAPEAV123@QEAPEAV123@AEBQEAV123@@Z)
3>E:\OSGeo4W\QGIS\build64\output\bin\Release\qgis_core.dll : fatal error LNK1120: 4 unresolved externals

### Steps to reproduce the issue

Build with Visual Studio 2019

### Versions

3.37 dev

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Build is failing

**Comment by 3DGISKing** [comment]
same for me.
@rajiv2502  did you fix this?

**Comment by rajiv2502** [comment]
Able to fix one by compiling draco and giving library reference.  Issue "draco.lib(point_cloud.cc.obj) : error LNK2019: unresolved external symbol __std_find_trivial_4 referenced in function "int * __cdecl std::_Find_unchecked<int *,int>(int *,int * const,int const &)" (??$_Find_unchecked@PEAHH@std@@YAPEAHPEAHQEAHAEBH@Z). 
Others are not able to fix.

**Comment by 3DGISKing** [comment]
thank your for your explnation.
maybe I need to compile https://github.com/abseil/abseil-cpp

**Comment by 3DGISKing** [comment]
fixed by using Microsoft Visual Studio Community 2022 (64-bit) (Version 17.9.6).

**Comment by wong-hao** [comment]
> fixed by using Microsoft Visual Studio Community 2022 (64-bit) (Version 17.9.6).

Hi, I am building with QT Creator. How to solv exactly? I find a packet called draco that I can download in OSGeo4W, but where is the absl_strings?
