### ISSUE TITLE
When importing raster data to geopackage, the user-defined layer name entered is invalid.

### ISSUE THREAD

**Issue by Alien-2022** [qgis/QGIS#57238]
### What is the bug or the crash?

I need to export the local raster data to the geopackage database, but when I import the raster data to the geopackage, the user-defined layer name is invalid, and the imported data will be named after the current database by default. Moreover, if it is imported with the user-defined layer name, the raster layer and the whole geopackage will be unable to be deleted.

### Steps to reproduce the issue

1. Create a new geopackage database and prepare a raster image.
2. Right-click the raster image, click export-> savaas, select the export location as the newly-built geopackage, customize the layer name as test, and click export.
3. It can be found that a raster data has been added to Exercise1.gpkg, but the name is still "Exercise1", not the "test" I named myself. Right-clicking to delete the raster layer or directly deleting the geopackage will give an error.
![Uploading 1.jpg…]()
![Uploading 2.jpg…]()
![Uploading 3.jpg…]()
![Uploading 4.jpg…]()

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
@Alien-2022 the images you attached are not visible, can you please re-attach them?

**Comment by Alien-2022** [comment]
@elpaso Sorry, I can't find the picture I cut at that time, but my problem has been solved. I updated QGIS to 3.34.0, and this problem has not appeared.
