### ISSUE TITLE
Is it possible to draw geometry above the print with bbox coordinates

### ISSUE THREAD

**Issue by LouisBoyaval** [qgis/QGIS#57232]
### What is the issue about the documentation?

I found nothing in the documentation about adding geometry on a print, for example with mapfish-print I can add them by passing: 
`{
                    "properties": {
                      "name": ""
                    },
                    "geometry": {
                      "type": "Polygon",
                      "coordinates": [
                        [
                          [
                            [
                              x,
                              y
                            ],
                            [
                              x,
                              y
                            ],
                            [
                              x,
                              y
                            ],
                            [
                              x,
                              i
                            ],
                            [
                              x,
                              y
                            ]
                          ]
                        ]
                      ]
                    }
                  }`

**Comment by agiudiceandrea** [comment]
@LouisBoyaval, I think it would be better to follow the instructions:

"Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features."

![image](https://github.com/qgis/QGIS/assets/16253859/c8161cf2-bd38-4310-9776-0943a6263101)
