### ISSUE TITLE
Is it possible to print a PDF with multiple pages ?

### ISSUE THREAD

**Issue by LouisBoyaval** [qgis/QGIS#57233]
### What is the issue about the documentation?

I found nothing in the documentations about printing a PDF with multiple pages.

**Comment by stafoo** [comment]
https://gis.stackexchange.com/questions/285474/adding-multiple-pages-in-qgis-print-composer
I think this is what you need

**Comment by LouisBoyaval** [comment]
I saw that but I want to do it dynamically with the GetPrint API

**Comment by agiudiceandrea** [comment]
@LouisBoyaval, I think it would be better to follow the instructions:

"Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features."

![image](https://github.com/qgis/QGIS/assets/16253859/c8161cf2-bd38-4310-9776-0943a6263101)
