### ISSUE TITLE
Importing dxf mesh?

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#57242]
### Feature description

It would help if it was possible to import dxf mesh as a mesh layer.

The file formats that can be imported are hard to convert into.

Landxml would also work.

**Comment by saberraz** [comment]
You can use https://github.com/lutraconsulting/qgis-landxml-mesh-plugin to import LandXML in QGIS as a mesh.

**Comment by APOS80** [comment]
> You can use https://github.com/lutraconsulting/qgis-landxml-mesh-plugin to import LandXML in QGIS as a mesh.

Doesnt work, i get an error.

**Comment by saberraz** [comment]
Could you file an issue there with the error and some sample data?
