### ISSUE TITLE
gdal_polygonize breaks on... long paths?

### ISSUE THREAD

**Issue by margaroch** [qgis/QGIS#57250]
### What is the bug or the crash?

While trying to convert raster to polygon ('poligonizar' in the Spanish translation), using a temporary file casues a break in gdal_plygonize (partial output follows) like this:

```
Comando GDAL:

gdal_polygonize.bat C:/DavidCB/Pastos/dNDVI_desbro_David.tif -b 1 -f "Interlis 2" C:/Users/DAVID/AppData/Local/Temp/processing_LUIziD/dae2da5a693a4da08f93d44cec6004ef/OUTPUT.xtf OUTPUT DN

Salida del comando GDAL:

Creating output C:/Users/DAVID/AppData/Local/Temp/processing_LUIziD/dae2da5a693a4da08f93d44cec6004ef/OUTPUT.xtf of format Interlis 2.
_Traceback (most recent call last): 
File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\osgeo_utils\auxiliary\gdal_argparse.py", line 226, in main 
self.doit(**kwargs) 
File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\osgeo_utils\gdal_polygonize.py", line 351, in doit 
return gdal_polygonize(**kwargs) 
File "C:\PROGRA~1\QGIS33~1.5\apps\Python39\lib\site-packages\osgeo_utils\gdal_polygonize.py", line 162, in gdal_polygonize 
dst_layer = dst_ds.CreateLayer( 
AttributeError: 'NoneType' object has no attribute 'CreateLayer'

El proceso devolvió el código de error 1_

Execution completed in 2.03 seconds

Results:

{'OUTPUT': 'C:/Users/DAVID/AppData/Local/Temp/processing_LUIziD/dae2da5a693a4da08f93d44cec6004ef/OUTPUT.xtf'}

```
If, instead, a specific output file (with a shorter path) is used, it works fine (partial output follows):
Comando GDAL:
```

gdal_polygonize.bat C:/DavidCB/Pastos/dNDVI_desbro_David.tif -b 1 -f "GPKG" C:/DavidCB/Pastos/vectorizado.gpkg vectorizado DN

Salida del comando GDAL:

Creating output C:/DavidCB/Pastos/vectorizado.gpkg of format GPKG.

0...10...20...30...40...50...60...70...80...90...100 - done.

Proceso completado exitosamente

Execution completed in 1.58 seconds

Results:

{'OUTPUT': 'C:/DavidCB/Pastos/vectorizado.gpkg'}
```
I suspect this may be related to a path limit in Windows but I don't know how to fix it. It can be worked around, obviously, as the second output shows.

### Steps to reproduce the issue

1. Try to polygonize a TIFF file using the default settings (which include creating temporary folder and file names)

### Versions

QGIS 3.34.5 LTR

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @margaroch, thanks for reporting. The issue is due to the fact that the default output vector layer extension has been incorrectly set to the "xtf" extension ("Interlis 2" format).

In order to avoid the issue, you need to set the Default output vector layer extension (in Settings->Options->Processing->General) to a value other than "xtf" e.g. to the value "gpkg" (GeoPackage) which is the default for such option.

**Comment by ar-siddiqui** [comment]
I am the maintainer of the Curve Number Generator plugin and multiple people have reported this issue.

**Comment by agiudiceandrea** [comment]
@ar-siddiqui , please inform the qgis-developer mailing list replaying to the at thread https://lists.osgeo.org/pipermail/qgis-developer/2024-February/066539.html.

**Comment by margaroch** [comment]
> Hi @margaroch, thanks for reporting. The issue is due to the fact that the default output vector layer extension has been incorrectly set to the "xtf" extension ("Interlis 2" format).
> 
> In order to avoid the issue, you need to set the Default output vector layer extension (in Settings->Options->Processing->General) to a value other than "xtf" e.g. to the value "gpkg" ("GeoPackage" format) which is the default for such option.

Thanks so much for your suggestion. Unfortunately, "gpkg" was already the default format for vector layers.

**Comment by agiudiceandrea** [comment]
@margaroch, please try to: go to Settings->Options->Processing->General and change the default output vector layer extension to something else, then click OK, then go again to Settings->Options->Processing->General and change the default output vector layer extension to "gpkg" and click OK.
Otherwise, create and use a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).

**Comment by margaroch** [comment]
Well, now I'm confused. It started working even though I changed no options. It seems I made some other kind of mistake. I will have to stay vigilant in case it crops up.
I will close the issue.
Thanks for your help :-)
