### ISSUE TITLE
Flatpak version cannot edit files stored over a network

### ISSUE THREAD

**Issue by M-Rick** [qgis/QGIS#57263]
### What is the bug or the crash?

The Flatpak version cannot load not modify files, especially GPKG when they are stored over a network.
No problem with the Debian version.

### Steps to reproduce the issue

Create a new project and try to save on a network.
or
Try to open a project or files stored over a network.

If it is a QGIS project, QGIS cannot resolve the layer paths.
If it is a GIS file, QGIS cannot open databases based files such as SQLite or GPKG. With non database based files like Geojson, they can be open, but not modified.
`Invalid Data Source: /run/user/1000/doc/2ca1ff96/gtfs-tan-02-2024.gpkg is not a valid or recognized data source.`

With the database manager, try to connect a Geopackage from a network.
`"/run/user/1000/doc/2ca1ff96/gtfs-tan-02-2024.gpkg" unfound`

### Versions

All the Flatpak versions.
Mine:

QGIS version
3.36.0-Maidenhead
QGIS code branch
Release 3.36
Qt version
5.15.10
Python version
3.11.7
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.44.2
PDAL version
2.5.6
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.5
QScintilla2 version
2.14.1
OS version
KDE Flatpak runtime

Active Python plugins
cadastre
1.19.1
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99
 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@M-Rick, thanks for reporting. I think you need to report the issue to the Flatpak repository https://github.com/flathub/org.qgis.qgis since it looks like a Flatpak only issue.
