### ISSUE TITLE
Can not extract conture lines from raster 

### ISSUE THREAD

**Issue by urupeange** [qgis/QGIS#57267]
### What is the bug or the crash?

![image](https://github.com/qgis/QGIS/assets/168233974/b471bf0c-4155-4c3b-9a1f-1281dbe9089e)
the image was made from interpolation TIN 

### Steps to reproduce the issue

create a raster image with TIN interpolation from a layer of points from a gpt file. 
![image](https://github.com/qgis/QGIS/assets/168233974/c3f1330f-9bd2-4708-ac16-887d820e217e)
![image](https://github.com/qgis/QGIS/assets/168233974/f308f157-3275-4909-a708-b9e55ac84764)
Then go to the window raster and click on extract, then conture lines. 
![image](https://github.com/qgis/QGIS/assets/168233974/e1137186-48c8-4b81-a5cd-e439226b44cc)
then this error hapens:

Versión de QGIS: 3.34.5-Prizren
Revisión del código de QGIS: 4b308492
Versión de Qt: 5.15.3
Python version: 3.9.18
Versión de GDAL: 3.8.4
Versión de GEOS: 3.12.1-CAPI-1.18.1
Versión de PROJ: Rel. 9.3.1, December 1st, 2023
PDAL version: 2.6.0 (git-version: 3fced5)
El algoritmo comenzó en: 2024-04-28T15:10:44
Algoritmo 'Curvas de nivel' comenzando…
Input parameters:
{ 'BAND' : 1, 'CREATE_3D' : False, 'EXTRA' : '', 'FIELD_NAME' : 'ELEV', 'IGNORE_NODATA' : False, 'INPUT' : 'C:/Users/HP/AppData/Local/Temp/processing_wEQFLE/4723ab28af9347b4877cfc52e44865d1/OUTPUT.nc', 'INTERVAL' : 10, 'NODATA' : None, 'OFFSET' : 0, 'OUTPUT' : 'TEMPORARY_OUTPUT' }

Comando GDAL:
gdal_contour -b 1 -a ELEV -i 10.0 -f "Interlis 2" C:/Users/HP/AppData/Local/Temp/processing_wEQFLE/4723ab28af9347b4877cfc52e44865d1/OUTPUT.nc C:/Users/HP/AppData/Local/Temp/processing_wEQFLE/c49aa167ae3941069bcd02d89885a4c4/OUTPUT.xtf
Salida del comando GDAL:
Warning 1: Model file not specified.
El proceso devolvió el código de error 1
Execution completed in 0.81 seconds
Results:
{'OUTPUT': 'C:/Users/HP/AppData/Local/Temp/processing_wEQFLE/c49aa167ae3941069bcd02d89885a4c4/OUTPUT.xtf'}

Cargando las capas resultantes
Las siguientes capas no se generaron correctamente.
• C:/Users/HP/AppData/Local/Temp/processing_wEQFLE/c49aa167ae3941069bcd02d89885a4c4/OUTPUT.xtf
Puede comprobar el «Panel de mensajes del registro» en la ventana principal de QGIS para encontrar más información sobre la ejecución del algoritmo.

### Versions

3.34.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @urupeange , thanks for reporting. The issue is due to the fact that the default output vector layer extension has been incorrectly set to the "xtf" extension ("Interlis 2" format).

In order to avoid the issue, you need to set the Default output vector layer extension (in Settings->Options->Processing->General) to a value other than "xtf" e.g. to the value "gpkg" ("GeoPackage" format) which is the default for such option.
