### ISSUE TITLE
New Postgis/Postgres connection NOT saving username/password when requested

### ISSUE THREAD

**Issue by rduivenvoorde** [qgis/QGIS#57284]
### What is the bug or the crash?

I often just use the 'Basic' tab and 'Store' username/password checkboxes when testing db's. (I know it is safer to ... etc...).

But recently it seems that after successfull Test Connection, the username/password is NOT saved. Often after configuring the same db again (via the dialog), then it is saved.

I have the idea that this always worked.

I saw this commit https://github.com/qgis/QGIS/commit/d7db887357ddffdaa9538d944561482a800e28ae and thought, maybe this is related?

### Steps to reproduce the issue

To reproduce I use podman (or docker) to create a temporarily database (db01 on localhost:54321) owned by user test/test:

```
export POSTGRES_PASSWORD=postgres
export POSTGRES_PORT=54321
export POSTGRES_CONTAINER_NAME=db01
podman run --name $POSTGRES_CONTAINER_NAME -p $POSTGRES_PORT:5432 -e POSTGRES_PASSWORD=$POSTGRES_PASSWORD -d postgis/postgis
# create test db, and db-owner
export PGUSER=test
export PGPASSWORD=test
export PGDATABASE=test
# create a test user
podman exec $POSTGRES_CONTAINER_NAME sh -c "PGPASSWORD=$POSTGRES_PASSWORD;echo 'CREATE ROLE $PGUSER WITH NOSUPERUSER NOCREATEDB NOCREATEROLE INHERIT LOGIN NOREPLICATION NOBYPASSRLS CONNECTION LIMIT -1 PASSWORD '\''$PGPASSWORD'\'';' | psql -U postgres"
# create db owned by test user
podman exec $POSTGRES_CONTAINER_NAME sh -c "PGPASSWORD=$POSTGRES_PASSWORD;echo 'CREATE DATABASE $PGDATABASE owner $PGUSER;' | psql -U postgres"
podman exec $POSTGRES_CONTAINER_NAME sh -c "PGPASSWORD=$POSTGRES_PASSWORD;echo 'create extension postgis;select version();select postgis_version();' | psql -U postgres $PGDATABASE"

# check if you can log in using psql
psql -h localhost -p 54321 -U test -w test -d test
```

Now in a fresh profile, via the Browser(! but I have the feeling this is also true for the normal connection dialog):

Create a new connection (localhost:54321, test/test db:test)
Make sure to click the 'Store' checkboxes AND Test the Connection via the Test Connection button:

![Screenshot from 2024-04-30 09-36-26](https://github.com/qgis/QGIS/assets/731673/7d551af0-fd50-42c2-b057-e4fe61cfbaab)

Click OK and get presented by the 'Warning' box:

![Screenshot from 2024-04-30 09-36-59](https://github.com/qgis/QGIS/assets/731673/f7e35556-ba85-4191-b469-41d2f7e4ecfe)

Click OK again (to save username password).

Now try to open the connection in the Browser, and I get:

![Screenshot from 2024-04-30 09-37-34](https://github.com/qgis/QGIS/assets/731673/7859a4f3-123f-40b1-b8b0-25c9d7d39879)

IF you give username/password there (test/test), you will get connected.

BUT after closing QGIS and starting it again, trying to open the test db in Browser it is still not saved.

If you now edit the connection, and opt to save username/password again, it IS saved.

Optionally, remove your db:

```
podman rm -f db01
```

### Versions

QGIS version | 3.37.0-Master | QGIS code revision | 0f9e0cbd61d
-- | -- | -- | --
Qt version | 5.15.10
Python version | 3.11.8
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.2 (Debian 16.2-1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Debian GNU/Linux trixie/sid
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99
MetaSearch | 0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
> I saw this commit https://github.com/qgis/QGIS/commit/d7db887357ddffdaa9538d944561482a800e28ae and thought, maybe this is related?

I don't think it's related. Oracle had it's own special way of dealing with credentials cache and I removed it to have a similar behavior than PG or other providers.

**Comment by landam** [comment]
@elpaso Are you planning to backport it to 3.34 LTR branch?

**Comment by elpaso** [comment]
> @elpaso Are you planning to backport it to 3.34 LTR branch?

That's not in my radar for now but it looks like a good idea.

**Comment by landam** [comment]
> > @elpaso Are you planning to backport it to 3.34 LTR branch?
> 
> That's not in my radar for now but it looks like a good idea.

@elpaso Yes, that would be great. That's reason why QGIS has LTR to my understanding :-)

**Comment by landam** [comment]
I may confirm that 3.34.13 is affected by this bug.
