### ISSUE TITLE
QGIS 3.34.6 qgis.r.in8.exe File Status MALICIOUS Determination trojan.tedy

### ISSUE THREAD

**Issue by readmanr** [qgis/QGIS#57283]
### Feature description

After upgrading from QGIS 3.34.4 to QGIS 3.34.6 I received a notificiation for trojan.tedy

Install Source: https://download.osgeo.org/qgis/windows/QGIS-OSGeo4W-3.34.6-1.msi

Filename: qgis.r.in8.exe
Filepath: C:\Program Files\QGIS 3.34.6\apps\qgis-ltr\grass\modules\
Fullpath: C:\Program Files\QGIS 3.34.6\apps\qgis-ltr\grass\modules\qgis.r.in8.exe
Creation Date: 19/04/2024 05:09:44 PM
Modification Date: 19/04/2024 05:09:44 PM
MD5: 6ab2af0a055ff98b3aa480c8277ee6e8
SHA128: 32317b69f03d34e06ac6f65b3c5a7441332255e2
SHA256: 9f21dbacbc2dfbb76e568e40a71e26402e2f3db8f6bfeeba094ca5f9cc1dd98b
SHA384: bca62271826c4e3c97bfd6117268f88df753a749b174d56707ae8deee8d4ce5e7fdddc702461574b8ff19ca410c665a6
SHA512: 3f2c75e0cf7482d47ac29ff8f8a6c4bfb611e80b252e1a1830d7c6f33ae9a0506c879f86557968a9dfb2929e2fc0a94f08e0da16ab36ab0dad84531584f239c1

Virus Total 11 vendors of 71
Source: https://www.virustotal.com/gui/file/9f21dbacbc2dfbb76e568e40a71e26402e2f3db8f6bfeeba094ca5f9cc1dd98b/detection

File Status MALICIOUS Determination trojan.tedy

ALYac - Gen:Variant.Tedy.540082
Arcabit - Trojan.Tedy.D83DB2
BitDefender - Gen:Variant.Tedy.540082
Bkav Pro - W64.AIDetectMalware
Emsisoft - Gen:Variant.Tedy.540082 (B)
eScan - Gen:Variant.Tedy.540082
GData - Gen:Variant.Tedy.540082
MAX - Malware (ai Score=86)
MaxSecure - Trojan.Malware.300983.susgen
Trellix (FireEye) - Gen:Variant.Tedy.540082
VIPRE - Gen:Variant.Tedy.540082

**Comment by jef-n** [comment]
Probably a false positive.  virustotal is now down to 2 of 74 vendor (miscounted? only MaxSecure still believes it's infected with Trojan.Malware.300983.susgen).
