### ISSUE TITLE
Text in message box 'Font Install Failed' is poorly legible in Night Mapping theme

### ISSUE THREAD

**Issue by mblesius** [qgis/QGIS#57290]
### What is the bug or the crash?

The text in the message box that can be opened when the installation of a missing font fails, is barely readable in the Night Mapping theme.

See the text 'Could not read fonts from data' in the screenshot below.

![image](https://github.com/qgis/QGIS/assets/78353871/41332bfe-961a-45aa-803b-492c7afda259)

### Steps to reproduce the issue

1. In QGIS options, select 'Night Mapping' as UI theme
2. When a font installation fails, click on the button 'View Error' in the message bar.

### Versions

Tested with QGIS 3.34.5 "Prizren".

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mblesius, thanks for reporting. Anyway this error message shouldn't be displayed in the currently available QGIS version 3.36.2 and 3.34.6. Have other error messages the same issue?

**Comment by mblesius** [comment]
@agiudiceandrea So far, I haven't seen any other dialogs or messages boxes having the same issue. I also haven't installed the latest versions yet, so if the message box does not appear in these and in future versions, the issue may be closed.

**Comment by agiudiceandrea** [comment]
@nirvn, I suppose this issue may affects any QgsMessageViewer window.
