### ISSUE TITLE
print composer pdf 10x filesize when opacity is less than 100

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#57330]
### What is the bug or the crash?

When exporting a map through the print composer - export as PDF the pdf file increases about 10x in filesize when the symbology opacity is set to anything less than 100.

### Steps to reproduce the issue

on windows 10, with QGIS 3.36.1

take any vector polygon layer (I have not tested this with lines or points)
make sure the opacity of a simple fill is set to 100%
create a layout a printcomposer
Export as PDF (with default settings), note the file size

set the opacity of the simple fill to anything less than 100
create a layout a printcomposer
Export as PDF (with default settings), note the file size

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.1-Maidenhead | QGIS code revision | 3e589453
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.1-Maidenhead
QGIS code revision
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Maybe related to #50543

**Comment by Jeroen-GroeneBij** [comment]
I did test this now with 3.22.16 and the same issue is there as well

**Comment by nyalldawson** [comment]
This is expected. When you set a layer wide opacity (for a vector layer at least) it forces a rasterised rendering of the layer during pdf exports. Depending on the size of the layer, this may be a considerable increase in file size.
