### ISSUE TITLE
setting labeling font size to less than 0.3 freezes qgis with meters units

### ISSUE THREAD

**Issue by faridcher** [qgis/QGIS#57336]
### What is the bug or the crash?

In a new project, add a vector layer from a geopackage and label with a Text field. Then try to set the font Size to 0.3 when units is either "Map Units" (my crs is in meters) or "Meters at Scale". It should work fine if it is set to 0.4. But as soon as I enter a value equal or less than 0.3 QGIS freezes! I either have to wait for 5 min or force close QGIS. If I wait for the GUI to set it to 0.3, once I want to show the Properties page of the layer, it then freezes QGIS.

### Steps to reproduce the issue

create a new project and a new geopackage with vector layer and a Text field. add the layer to the map and label the Text field and set the font Size to 0.3 and the units to Meters at Scale

### Versions

3.34.6-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
Tested in QGIS 3.37 on windows 11 with a font size of 0.1 meter at scale and no issue. Even at 0.001 there were no issues.

**Comment by faridcher** [comment]
@roya0045 I have tested on two separate PC with Debian OS. Could it be OS dependent?

**Comment by roya0045** [comment]
That's a possiblity

**Comment by agiudiceandrea** [comment]
@faridcher, thanks for reporting. Please provide a simple project and layer with which the issue occurs on your system.

**Comment by faridcher** [comment]
@agiudiceandrea You may create a new project, a new geopackage layer with a Text field for labeing.

## Software Information:
- **OS Name:**                                     Debian GNU/Linux trixie/sid
- **OS Type:**                                     64-bit
- **GNOME Version:**                               46
- **Windowing System:**                            Wayland
- **Kernel Version:**                              Linux 6.7.12-amd64

thank  you

**Comment by elpaso** [comment]
> @agiudiceandrea You may create a new project, a new geopackage layer with a Text field for labeing and digitize a few features

That information was already in the issue description. There is a good reason to ask for a sample project and data because many configurations could be different and trigger the issue.

Maybe it's just me but without sample data and project  I won't spend a minute of my time trying to reproduce this issue.

**Comment by faridcher** [comment]
@elpaso  attached. thank you for your time
[Uploading test.zip…]()

**Comment by elpaso** [comment]
@faridcher thank you for the sample project. 
I tested it and, while it is certainly very slow and it temporarily freezes QGIS, it comes back eventually. Is that what you also observe or does it freeze forever?
