### ISSUE TITLE
Empty space after host name in SQL server, cause inconsistent error

### ISSUE THREAD

**Issue by Ertmann** [qgis/QGIS#57358]
### What is the bug or the crash?

This is a sneaky mistake that can prevent novice users from using QGIS with MS SQL server, simply by them doing a copy-paste of the host name. Because an empty space can sneak in undeteced, like so; "MyDomainsServer ".
The inconsistency comes when editing the connetion; the buttons "Test connection" and "List databases" works just fine, and you can see the tables in the database. But when you're done editing and go back to press connect. You get this error: 
![image](https://github.com/qgis/QGIS/assets/7080901/9bc3b2f8-acc3-4b87-af2e-c4327b5357e5)

### Steps to reproduce the issue

1. Add an empty space after the hosname of a MS SQL server connection you know already works.
2. (Optional) Edit the connetion; to see that the buttons "Test connection" and "List databases" works just fine.
3. Press the connect button.
![image](https://github.com/qgis/QGIS/assets/7080901/943f48e1-1681-456a-822b-a23b4d063f5d)

### Versions

4.10.3-A Coruña
3.28.8-Firenze

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
https://stackoverflow.com/a/3523068/23076275 confirms a white space in a hostname is invalid

**Comment by Ertmann** [comment]
yeah, so instead of telling the user this, the inconsistency can help lead them astray.

**Comment by elpaso** [comment]
Actually, the host is trimmed (trailing/leading spaces removed): https://github.com/qgis/QGIS/blob/master/src/providers/mssql/qgsmssqlnewconnection.cpp#L306 but not when it's written: https://github.com/qgis/QGIS/blob/master/src/providers/mssql/qgsmssqlnewconnection.cpp#L160

I'll fix that.
