### ISSUE TITLE
Don't available URL for plugins time-out error

### ISSUE THREAD

**Issue by CrisYaselga** [qgis/QGIS#57352]
### What is the bug or the crash?

When Qgis try to connect to URL: https://plugins.qgis.org/ for download plugins, this URL return time-out error, because it´s don´t avalible.

### Steps to reproduce the issue

In toolbar, Complements, next install complementes and select quickMapServices, try to download, but return a time out error.

### Versions

3.34.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@CrisYaselga, thanks for reporting. Does the issue still occur?
