### ISSUE TITLE
Dropdown to choose crs when exporting doesn't work

### ISSUE THREAD

**Issue by CrashT3st** [qgis/QGIS#57363]
### What is the bug or the crash?

In the export layer dialog when choosing which crs to export the layer with, if you use the dropdown and choose a crs it will not take it, and it will still use the original crs the layer you want to export has. If instead the crs is chosen through the "choose crs" button on the right of the dropdown, then the layer will be exported with the chosen and correct crs.

### Steps to reproduce the issue

Right click on a layer, choose export then "save elements as", and then try to change the crs through either the dropdown or the button next to it, and the results will be different.

### Versions

3.36.0-Maidenhead

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Update to the latest 3.36 release, this has been fixed already
