### ISSUE TITLE
Grass Tools: Exporting contours to DXF with height values

### ISSUE THREAD

**Issue by Mallayz** [qgis/QGIS#57360]
### What is the bug or the crash?

The GrassTools  process to export contours with height values to a DXF is yeilding a funny result.
the contours when vied in a DXF file are elevated according to the height values at 90 degrees in a straight vertical elevation and not elevated at the original location  to the required height value.
Dont know if the explanation  makes sense. 
attached are screen grabs
![Contours 2D](https://github.com/qgis/QGIS/assets/168139771/f0b3ec52-44fe-4493-9766-e38fc2d8c11e)
![Contours Elevated](https://github.com/qgis/QGIS/assets/168139771/2a71755f-adbd-47fc-8fa2-c6c905492fc7)

### Steps to reproduce the issue

![Contours 2D](https://github.com/qgis/QGIS/assets/168139771/14dc4e5d-e949-4ba1-8361-45b62c25a0cc)
![Contours Elevated](https://github.com/qgis/QGIS/assets/168139771/caa8a05d-e08a-43ef-8e2f-69120fa82e7b)

### Versions

QGIS Desktop 3.36.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mallayz, thanks for reporting. Please provide a sample layer, the exact name of the processing algorithm and related parameters used and / or exact steps to replicate the issue.
