### ISSUE TITLE
cmake出错

### ISSUE THREAD

**Issue by wwhwwxlz** [qgis/QGIS#57374]
### What is the bug or the crash?

ModuleNotFoundError: No module named 'PyQt5.Qsci'
-- Could NOT find HDF5 (missing: HDF5_LIBRARIES HDF5_INCLUDE_DIRS) (found version "")
-- Could NOT find NetCDF (missing: NETCDF_LIBRARY NETCDF_INCLUDE_DIR)
-- Using PROJ >= 6 srs database.
-- Qsci sip file not found - disabling bindings for derived classes
-- QtGamepad not enabled - disabling bindings for derived classes
-- Ctest Binary Directory set to: /home/dev/cpp/QGIS-final-3_34_2/build/output/bin
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
/home/dev/cpp/QGIS-final-3_34_2/src/core/QTKEYCHAIN_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/core
/home/dev/cpp/QGIS-final-3_34_2/src/core/SPATIALINDEX_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/core
/home/dev/cpp/QGIS-final-3_34_2/src/gui/QSCINTILLA_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/gui
/home/dev/cpp/QGIS-final-3_34_2/src/gui/QWT_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/gui
Protobuf_LITE_LIBRARY
    linked by target "qgis_core" in directory /home/dev/cpp/QGIS-final-3_34_2/src/core
QSCINTILLA_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/arcgisrest
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/spatialite
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/providers/wfs
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
QTKEYCHAIN_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
QTKEYCHAIN_LIBRARY
    linked by target "qgis_core" in directory /home/dev/cpp/QGIS-final-3_34_2/src/core
QWT_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
QWT_LIBRARY
    linked by target "qgis_gui" in directory /home/dev/cpp/QGIS-final-3_34_2/src/gui
    linked by target "qgis_app" in directory /home/dev/cpp/QGIS-final-3_34_2/src/app
    linked by target "qgis_3d_sandbox" in directory /home/dev/cpp/QGIS-final-3_34_2/tests/src/3d/sandbox
SPATIALINDEX_INCLUDE_DIR
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/src/analysis
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
   used as include directory in directory /home/dev/cpp/QGIS-final-3_34_2/python
SPATIALINDEX_LIBRARY
    linked by target "qgis_core" in directory /home/dev/cpp/QGIS-final-3_34_2/src/core

### Steps to reproduce the issue

mkdir build && cd build
cmake ..

### Versions

3.34.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is a local issue, not a qgis issue. I'd suggest reaching out to the QGIS developer list if you need assistance building qgis.

**Comment by wwhwwxlz** [comment]
如何联系

**Comment by jef-n** [comment]
> 如何联系 [How to contact]

https://qgis.org/en/site/getinvolved/mailinglists.html#qgis-mailinglists

**Comment by wwhwwxlz** [comment]
CMakeFiles/CMakeError.log:70:/usr/bin/ld: cannot find -lpthreads
我在公司没有权限发邮件呢
