### ISSUE TITLE
Setting very high cache size crashes QGIS at startup

### ISSUE THREAD

**Issue by lhilarides** [qgis/QGIS#57380]
### What is the bug or the crash?

Using QGIS 3.34.5 on Windows 11, I changed my cache size (settings --> options --> network) from 2GB to 12GB ( value of 12048000 KiB). I have plenty of free diskspace (>400 GB). After changing that setting I was no longer able to start QGIS, it wouldn't even show the loading screen. After removing the [cache] section entirely from the qgis.ini file in my QGIS profile, things were back to normal again.

### Steps to reproduce the issue

1. Change network cache size to 12GB or more
2. Close QGIS
3. Start QGIS (it won't start)
4. Clear [cache] section from qgis.ini in the profile
5. Start QGIS (it will start now)

### Versions

3.34.5 and also reproducible on 3.36.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by kentstanton** [comment]
Also occurs for me. Running 3.34.4-Prizren or 3.26.2 on Windows 11.

Setting the network cache value to anything larger than 2090000 causes QGIS to crash on startup as described above. 

In QGIS3.ini the cache values:
**works when the value is set to 2000000 in the UI**
[cache]
size=@Variant(\0\0\0\x81\0\0\0\0z\x12\0\0)

**Fails when the value is set to 2100000 in the UI**
[cache]
size="@Variant(\0\0\0\x81\xff\xff\xff\xff\x80,\x80\0)"

**Comment by agiudiceandrea** [comment]
Setting the value 2100000, the following debug message printed:
`[28444] qgsnetworkaccessmanager.cpp(759) : (QgsNetworkAccessManager::setupDefaultProxyAndCache) [305ms] maximumCacheSize: -2144567296`
