### ISSUE TITLE
Qgis crash when trying to install a plugin

### ISSUE THREAD

**Issue by lubumoon1437** [qgis/QGIS#57383]
### What is the bug or the crash?

When I try to install a plugin from the Qgis interface, the program crashes and doesn't allow me to do anything other than close it.

### Steps to reproduce the issue

1. I open Qgis
2. I open the plugin tab
3. I wait a few seconds and it crashes
https://github.com/qgis/QGIS/assets/169311870/72b1546e-f347-448b-a80b-2c055d1bc875

### Versions

Versión de QGIS
3.36.2-Maidenhead
Revisión del código de QGIS
6d250527
Versión Qt
5.15.13
Versión de Python
3.12.3
Versión de GDAL/OGR
3.8.5
Versión de PROJ
9.4.0
Versión del registro de base de datos EPSG
v11.004 (2024-02-24)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.45.1
Versión de PDAL
2.6.3
Versión del cliente de PostgreSQL
16.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.2.0
Versión de QScintilla2
2.14.1
Versión del SO
Windows 11 Version 2009

Complementos activos de Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I previously modified some ArcGis Pro Python files,

**Comment by agiudiceandrea** [comment]
Please try if the issue occurs also using a new QGIS user profile.

**Comment by agiudiceandrea** [comment]
Does the issue still occurs?
