### ISSUE TITLE
plugins.qgis.org: 504 Gateway timeout

### ISSUE THREAD

**Issue by benz0li** [qgis/QGIS#57428]
### What is the bug or the crash?

Accessing https://plugins.qgis.org results in a 504 Gateway timeout.

### Steps to reproduce the issue

Open https://plugins.qgis.org in a browser or try to install a QGIS plugin.

### Versions

all

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by benz0li** [comment]
Ping @agiudiceandrea @dimasciput

**Comment by agiudiceandrea** [comment]
@benz0li please see https://lists.osgeo.org/pipermail/qgis-user/2024-May/054439.html.

**Comment by benz0li** [comment]
> We plan to add some rules that require a captcha or similar if you want to download the zip files for plugins from the web site (i.e. if the user agent is not QGIS Desktop)

@agiudiceandrea I assume CLI command `qgis-plugin-manager` is [treated] the same as the "Plugins manager" in QGIS Desktop. Correct?

Otherwise, this will break the build pipelines for my/b-data's [JupyterLab QGIS docker stack](https://github.com/b-data/jupyterlab-qgis-docker-stack)

* https://gitlab.b-data.ch/jupyterlab/r/qgisprocess/-/pipelines
* https://gitlab.b-data.ch/jupyterlab/cuda/r/qgisprocess/-/pipelines

and the ones for my [JupyterLab](https://github.com/b-data/jupyterlab-r-docker-stack) [R docker stack](https://github.com/b-data/r-docker-stack)

* https://gitlab.b-data.ch/r/qgisprocess/-/pipelines
* https://gitlab.b-data.ch/cuda/r/qgisprocess/-/pipelines
* https://gitlab.b-data.ch/jupyterlab/r/qgisprocess/-/pipelines
* https://gitlab.b-data.ch/jupyterlab/cuda/r/qgisprocess/-/pipelines

**Comment by agiudiceandrea** [comment]
The issue no longer occurs.
qgis-plugin-manager is not a core QGIS funtionality. You need to contact the qgis-plugin-manager authors at https://github.com/3liz/qgis-plugin-manager and add comment on https://github.com/qgis/QGIS-Django/issues/402.
