### ISSUE TITLE
There is already an enum member in scope with the same Python name

### ISSUE THREAD

**Issue by wwhwwxlz** [qgis/QGIS#57449]
### What is the bug or the crash?

sip: /home/dev/cpp/QGIS-final-3_34_2/build/python/core/auto_generated/qgis.sip:442: There is already an enum member in scope with the same Python name
make[2]: *** [python/CMakeFiles/python_module_qgis__core.dir/build.make:857: python/core/sip_corepart0.cpp] Error 1
make[2]: *** Deleting file 'python/core/sip_corepart0.cpp'
make[1]: *** [CMakeFiles/Makefile2:8695: python/CMakeFiles/python_module_qgis__core.dir/all] Error 2

### Steps to reproduce the issue

make

### Versions

3_34_2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
this must be a local issue: QGIS 3.34 is built daily on Linux by several people and by CI without issues.

**Comment by wwhwwxlz** [comment]
我装了半个多月了，你们有在ARM64上编译的案例参考吗？

**Comment by wwhwwxlz** [comment]
> 这一定是一个本地问题：QGIS 3.34 每天由几个人和 CI 在 Linux 上构建，没有问题。

有在ARM64上构建的案例参考吗？我装了好久，问题一个又一个。

**Comment by cehui0303** [comment]
> > 这一定是一个本地问题：QGIS 3.34 每天由几个人和 CI 在 Linux 上构建，没有问题。
> 
> 有在ARM64上构建的案例参考吗？我装了好久，问题一个又一个。

我就是再arm64构建，已经搞了快一个月了，一直没成功，目前出现上面同样的问题。

**Comment by wwhwwxlz** [comment]
> > > 这一定是一个本地问题：QGIS 3.34 每天由几个人和 CI 在 Linux 上构建，没有问题。
> > 
> > 
> > 有在ARM64上构建的案例参考吗？我装了好久，问题一个又一个。
> 
> 我就是再arm64构建，已经搞了快一个月了，一直没成功，目前出现上面同样的问题。

嘿嘿，我早就编译好了，就是sip，pyqt，qt这三个版本的问题
我用的版本是sip6.8.3，pyqt5.15.10，qt5.15.5。

**Comment by cehui0303** [comment]
> > > > 这一定是一个本地问题：QGIS 3.34 每天由几个人和 CI 在 Linux 上构建，没有问题。
> > > 
> > > 
> > > 有在ARM64上构建的案例参考吗？我装了好久，问题一个又一个。
> > 
> > 
> > 我就是再arm64构建，已经搞了快一个月了，一直没成功，目前出现上面同样的问题。
> 
> 嘿嘿，我早就编译好了，就是sip，pyqt，qt这三个版本的问题 我用的版本是sip6.8.3，pyqt5.15.10，qt5.15.5。

能加个Q或W联系吗？ Q:450380306,Wechat:cehui0303,跪谢
