### ISSUE TITLE
QGIS crash on image repojection

### ISSUE THREAD

**Issue by grantboxer** [qgis/QGIS#57451]
### What is the bug or the crash?

When opening a satellite image in a projection other than that of the main map window, QGIS is crashing.

### Steps to reproduce the issue

Opening an image

### Versions

QGIS version
3.36.2-Maidenhead
QGIS code revision
6d250527
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
enmapboxplugin
3.14.2
FreehandRasterGeoreferencer
0.8.3
geoscience
1.12
grd_loader-main
0.1.1
mapswipetool_plugin
1.2
mineral_exploration_web_services
0.1
openlog
1.1.0
processing_saga_nextgen
1.0.0
Qgis2threejs
2.7.3
SpreadsheetLayers
2.1.2
SRTM-Downloader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## User Feedback

When opening a satellite image in a different projection to that of the map window.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000042f0 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsAnnotation::appearanceChanged :
QgsCoordinateTransform::transformPolygon :
proj_context_delete_cpp_context :
proj_as_proj_string :
QgsCoordinateReferenceSystem::geographicCrsAuthId :
QgsCoordinateReferenceSystem::toProj :
QgsCoordinateReferenceSystemRegistry::pushRecent :
QgsProjectionSelectionTreeWidget::~QgsProjectionSelectionTreeWidget :
QgsProjectProperties::~QgsProjectProperties :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAnimationExportDialog::QgsAnimationExportDialog :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
pdal::StageFactory::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QSizePolicy::operator== :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsTemporalControllerDockWidget::temporalController :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
pdal::StageFactory::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
pdal::StageFactory::`default constructor closure' :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAbout::QgsAbout :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAbout::QgsAbout :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgisApp::projectProperties :
QgisApp::projectPropertiesProjections :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.2-Maidenhead
QGIS code revision: 6d250527
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by grantboxer** [comment]
This problem does not seem to happen in 3.34.

QGIS version
3.34.6-Prizren
QGIS code revision
623828f5
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009




Active Python plugins
enmapboxplugin
3.14.2
FreehandRasterGeoreferencer
0.8.3
geoscience
1.12
grd_loader-main
0.1.1
mapswipetool_plugin
1.2
mineral_exploration_web_services
0.1
openlog
1.1.0
processing_saga_nextgen
1.0.0
Qgis2threejs
2.7.3
SpreadsheetLayers
2.1.2
SRTM-Downloader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
otbprovider
2.12.99
processing
2.12.99

**Comment by agiudiceandrea** [comment]
@grantboxer, thaks for reporting. Please try if the issue does occur using a new QGIS user profile. If it does, please provide a sample layer and exact in order to replicate the issue.
