### ISSUE TITLE
Vector: Research Tools: Regular Points

### ISSUE THREAD

**Issue by qahtya0b** [qgis/QGIS#57458]
### What is the bug or the crash?

Hi ,

I am trying to distribute points inside a polygon using regular points command in vector research tools
<img width="514" alt="calculate from polygon layer" src="https://github.com/qgis/QGIS/assets/166681619/544306dc-5261-47ae-b635-0cd3b98caf6c">
<img width="374" alt="Vector" src="https://github.com/qgis/QGIS/assets/166681619/6d8b4406-70f8-4bca-a9c1-93ee9f85c666">
 . However, the points is distributed in square shape instead of being distributed only within the provided polygon layer. Kindly, can you fix this issue, please ?

screenshots are attached.

### Steps to reproduce the issue

mentioned in the screenshots above.

### Versions

QGIS version
3.36.2-Maidenhead
QGIS code revision
6d250527
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
Group_and_Sort_Layers
1.2
profiletool
4.2.6
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@qahtya0b, please see the description of the "Regular Points" processing algorithm at https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/qgis/vectorcreation.html#regular-points:

"Creates a new point layer with its points placed in a regular grid within a given extent.

The grid is specified either by the spacing between the points (same spacing for all dimensions) or by the number of points to generate. In the latter case, the spacing will be determined from the extent. In order to generate a full rectangular grid, at least the number of points specified by the user is generated for the latter case."

**Comment by qahtya0b** [comment]
Hi Andrea,

Kindly, share with me the procedure step by step instructions preferrably with screenshots, please. It is not described in the link below since there is no "Regular points inside polygon" procedure.

Kind Regards,
Yahya
________________________________

**Comment by qahtya0b** [comment]
Hi,

Also, the regular points extent from layer seems to pick random layers instead of specific ones that i need in a specific folder. Kindly, how do i specify which folder i should be getting the layer from, please?
So far, the layers appear randomly and does not show the layers that i need.

[cid:903aebb2-e119-4127-82ed-a874633d1335]
Below shows a random layers that appear instead of showing specific folder for specific layers that i saved.
[cid:c82e50c6-5caa-4b20-8bcc-9a3677f7999d]
________________________________

**Comment by agiudiceandrea** [comment]
@qahtya0b, this issue report form is for reporting bugs or request new features. Please follow the instruction for asking questions

![image](https://github.com/qgis/QGIS/assets/16253859/45d36425-17e0-47fb-aaf5-13995bb99310)

> Question
> Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.

**Comment by qahtya0b** [comment]
Hi Andrea,

I registered but i am not sure where to post my question exactly as there are many lists and some lists are old and not active.

By the way, is creating regular points possible inside a polygon or on a line ? is it working for you ? i followed the steps and it seems there is a glitch.

Thank you,
Yahya
________________________________
