### ISSUE TITLE
Add record button stays toggled on non-geom-layers

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#57464]
### What is the bug or the crash?

After adding a feature on non geometric layers by the add-record-button, it stays - like it's expected on geometric layers - toggled. I need to do something else after to "reset" the button.

[addrecord.webm](https://github.com/qgis/QGIS/assets/28384354/e38a8c5d-2d49-4408-be80-bd3de50a8762)

I really wonder why it hasn't been reported before. But maybe I've overseen the issue.

### Steps to reproduce the issue

1. Create layer without geometry
2. Add a feature with "Add record"
3. Add another - you can't, you have to do something else first (like e.g. untoggle and toggle edit mode)

### Versions

3.34.5 (at least) untill master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
#55092 duplicate
Also see #56416

**Comment by signedav** [comment]
Ah perfect. Thanks.
