### ISSUE TITLE
Buffer in v3.36.2 doesn't work properly

### ISSUE THREAD

**Issue by JavierGGitHub** [qgis/QGIS#57462]
### What is the bug or the crash?

Buffer tool doesn't allow to set the distance value. It's set in degrees and it's impossible to choose another different value like meters or miles ect. It shows a warning sign. 

### Steps to reproduce the issue

Go to Vectorial menu. Then to geoprocess tools and finaly click on buffer

### Versions

Versión de QGIS
3.36.2-Maidenhead
Revisión del código de QGIS
6d250527
Versión Qt
5.15.13
Versión de Python
3.12.3
Versión de GDAL/OGR
3.8.5
Versión de PROJ
9.4.0
Versión del registro de base de datos EPSG
v11.004 (2024-02-24)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.45.1
Versión de PDAL
2.6.3
Versión del cliente de PostgreSQL
16.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.2.0
Versión de QScintilla2
2.14.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

![QGIS-BUFFER-BUG](https://github.com/qgis/QGIS/assets/45859097/555f6f46-7859-47c1-ba77-046dc5df69f2)

**Comment by DelazJ** [comment]
@JavierGGitHub Could you try with your data NOT in epsg:4326 (whose unit is degree)?

**Comment by JavierGGitHub** [comment]
Thanks. My data are in UTM projection. EPSG: 25830.

**Comment by DelazJ** [comment]
Not what is indicated for "huella_carto_v03_entities" in your above screenshot.

**Comment by agiudiceandrea** [comment]
@JavierGGitHub, this is not a bug. It is the expected behaviour.
The "Distance" parameter's unit is the same as the unit of the layer's CRS.
In you case, the layer's CRS is EPSG:4326 whose unit is the degree, thus the "Distance" parameter's unit is the degree.

**Comment by JavierGGitHub** [comment]
You are right. I didn't realise it. Thanks for the clarification indeed.
