### ISSUE TITLE
Issues with special character encoding

### ISSUE THREAD

**Issue by alexCCI** [qgis/QGIS#57472]
### What is the bug or the crash?

The letter é does not display correctly in the 'Vector' dropdown menu in the French version.

![image](https://github.com/qgis/QGIS/assets/78025843/3b9b0801-ce74-4d57-82ac-2e7619dd1b80)

### Steps to reproduce the issue

1. Go to the 'Vector' dropdown menu

### Versions

3.34.6-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@alexCCI, thanks for reporting. Please provide the full QGIS version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") and try if the issue does occur also using a new QGIS user profile.

The issue doesn't occur on my Windows 10 system:
![image](https://github.com/qgis/QGIS/assets/16253859/783b8f56-f119-4dba-aef0-35f8cb71e788)

**Comment by alexCCI** [comment]
> ###
> [May 17, 2024](#issuecomment-2118135579)

Version de QGIS
3.34.6-Prizren
Révision du code
623828f5
Version de Qt
5.15.13
Version de Python
3.12.3
Version de GDAL/OGR
3.8.5
Version de Proj
9.4.0
Version de la base de données du registre EPSG
v11.004 (2024-02-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.45.1
Version de PDAL
2.6.3
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.2.0
Version de QScintilla2
2.14.1
Version de l'OS
Windows 10 Version 2009




Extensions Python actives
openlog
1.0.1
Ouvrages de DataPlate-forme
1.2
pcraster_tools
0.3.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.4
QuickOSM
2.2.3
quick_map_services
0.19.34
raster_tracer
0.3.3
slyr_community
5.0.0
SRTM-Downloader
3.2.2
StreetView
3.2
Topo
1.3.6
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
indows 10 Version 2009


**In a new profile, the problem is not present.**

**Comment by agiudiceandrea** [comment]
> In a new profile, the problem is not present.

The issue may be due to some installed third-party plugin or to some non default settings.

**Comment by DelazJ** [comment]
@alexCCI Maybe due to the fonts in use? Yours is different from the usual one. Did you or a plugin play with it?

**Comment by DelazJ** [comment]
Also note that the first two entries (C++ plugins) are rendered correctly while the Processing menus do not.

**Comment by alexCCI** [comment]
> @alexCCI Maybe due to the fonts in use? Yours is different from the usual one. Did you or a plugin play with it?

The font was manually changed.
Reverting to the default font did not make any difference.

**Comment by alexCCI** [comment]
Ultimately, the issue was caused by the QGIS.ini file. Something modified it by adding the names of native tools in the [Processing] section. The special characters in these names were improperly encoded.

**Comment by alexCCI** [comment]
Ultimately, the issue was caused by the QGIS.ini file. Something modified it by adding the names of native tools in the [Processing] section. The special characters in these names were improperly encoded.

**Comment by agiudiceandrea** [comment]
@alexCCI, have you tried if the issue occur also using a new QGIS user profile as requested?

**Comment by alexCCI** [comment]
> @alexCCI, have you tried if the issue occur also using a new QGIS user profile as requested?

Yes, it's mentioned in the message about versioning. Creating a new profile resolved the problem. This once again proves that it was caused by the QGIS.ini file.
