### ISSUE TITLE
Inverse Trigonometric Functions (asin, atan, acos) in GDAL and in the Graphical Modeller

### ISSUE THREAD

**Issue by geoandfil** [qgis/QGIS#57473]
### What is the bug or the crash?

In QGIS raster calculator, trigonometric functions like asin, atan, and acos work seamlessly. 
When using the GDAL raster calculator, these functions fail evaluation of calculation atan(radians(A)) failed NameError: name 'atan' is not defined
In the Graphical Modeller also QGIS raster calculator fail 

### Steps to reproduce the issue

Load a raster layer
Start a GDAL Raster Calculator
Insert this function: atan(A)

----
Open a new graphic model
Insert a raster
Add a raster calculator (QGIS) and Insert this function: atan(A)

Run
 

### Versions

3.34.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by esnyder-rve** [comment]
The QGIS raster calculator and the GDAL raster calculator are two different programs. The GDAL raster calculator (which is the `gdal_calc` program) uses NumPy array functions and has a different feature set and function naming convention from the QGIS raster calculator. For instance, the `atan()` function in QGIS is called `arctan()` in NumPy.
