### ISSUE TITLE
Regression: No longer possible to create a new child in an n-m relationship

### ISSUE THREAD

**Issue by rbovard** [qgis/QGIS#57474]
### What is the bug or the crash?

It's no longer possible to create a new child in an N-M relationship (the form disapears), we can only select one existing one.

![create_child](https://github.com/qgis/QGIS/assets/4549666/423623de-b0f6-4b9e-9c93-3273625666ba)

It was working fine with last LTR.

### Steps to reproduce the issue

1. Open a form with a N-M relation
2. Click on add child feature --> The intermediate table opens
3. Click on the green + to create a new child --> NOK: The form closes (and the new form for the child never open)

### Versions

3.34.6

```
QGIS version
3.34.6-Prizren
QGIS code revision
623828f5
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@rbovard, thanks for reporting. Please provide the full QGIS version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") as requested in the issue report form, and a simple project and layers with which the issue occurs.

**Comment by 3nids** [comment]
This is probably coming from https://github.com/qgis/QGIS/commit/5ac470cb6d9d759f5fd32ca52495b254ac04c0a7
