### ISSUE TITLE
系统打不开

### ISSUE THREAD

**Issue by 117ren** [qgis/QGIS#57479]
### What is the bug or the crash?

bug
![F9FB4D720E7AC9B9B5FD0A20247E5800](https://github.com/qgis/QGIS/assets/170199036/193e3278-f8fc-4fde-9adb-8eccec5ea3a5)

### Steps to reproduce the issue

![F9FB4D720E7AC9B9B5FD0A20247E5800](https://github.com/qgis/QGIS/assets/170199036/5e073524-e58a-4449-b7b7-3e4fd00abed3)

### Versions

![F9FB4D720E7AC9B9B5FD0A20247E5800](https://github.com/qgis/QGIS/assets/170199036/211b137d-b46c-4d61-a7d7-7e0948defe9b)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

希望解决问题
![F9FB4D720E7AC9B9B5FD0A20247E5800](https://github.com/qgis/QGIS/assets/170199036/cf2922d8-a039-420a-bc0c-2e735a28bd29)

**Comment by m-kuhn** [comment]
Please add more information, what operating system are you using and how did you install qgis.
