### ISSUE TITLE
Rotated north arrow disappears on location edit with mouse

### ISSUE THREAD

**Issue by Coastal0** [qgis/QGIS#57489]
### What is the bug or the crash?

North arrow x/y locations updates to 9999999/9999999 when adjusting location via mouse movement for a rotated map layout.

### Steps to reproduce the issue

Create map layout
Change map rotation (e.g. 35 degrees)
Place north arrow
Move location of the north arrow using the mouse
North arrow has disappeared and Position and Size window updates x and y location to 9999999

### Versions

QGIS version
3.36.2-Maidenhead
QGIS code revision
6d250527
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.5
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
changeDataSource
3.1
deactivate_active_labels
0.5
exportStyles
1.0
geoscience
1.12
layer_tree_tools
1.2.1
MemoryLayerSaver
5.0.2
processing_saga_nextgen
1.0.0
profiletool
4.2.6
quick_map_services
0.19.34
slyr
7.4.0
SRTM-Downloader
3.2.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by johnwbryant** [comment]
I'm also running into this problem on 3.38.1 on Ubuntu.

![Peek 2024-09-20 10-44](https://github.com/user-attachments/assets/3ce5ccbf-1ac6-45d8-b5de-984f974fd1c3)
