### ISSUE TITLE
WMS/WFS http headers not saved

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#57499]
### What is the bug or the crash?

A WMS connection is set with a http header 
![image](https://github.com/qgis/QGIS/assets/39594821/325e6bd7-af90-4610-a419-96259393746a)

After closing and reopening QGIS, header is gone.

### Steps to reproduce the issue

1. Create new WMS connection
2. URL : https://data.geopf.fr/private/wms-r?VERSION=1.3.0
3. In HTTP headers, advanced, add new key : `apikey` with value `ign_scan_ws`
4. Connect and you can add a layer.
5. Close QGIS
6. Open QGIS
7. Try to connect to previouly added connection
8. Error
9. If you edit, you can see header is gone.

### Versions

3.36.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
I believed it used to work in previous version (maybe before the whole refactoring of settings).

**Comment by elpaso** [comment]
CC @3nids

**Comment by 3nids** [comment]
I just tried it using WMS. The headers are part of the request:

<img width="548" alt="image" src="https://github.com/qgis/QGIS/assets/127259/e55162a7-c571-4982-add3-f0ecb3afe9b7">

But it might be an issue of settings migration.
It could be that you defined this in older version and it doesn't work in a recent one or vice-versa.
Could you confirm a path to reproduce?

**Comment by nicogodet** [comment]
If headers are set during current QGIS session, no issue. This is not the issue I described in first post.

The issue occurs if you exit and restart QGIS.
Previously added WMS layers still have headers in URI.
But if you try to connect to WMS server to add another layer, there is an error. Edit connection and see headers are missing.

Steps provided in first post reproduce the issue on fresh profile.

**Comment by 3nids** [comment]
After closing and reopening, I do see the header in the config and it's added to the new connection.
Tried both from add layer and browser.

I suspect there is something wrong with backward compatibility.
I've spotted this: https://github.com/qgis/QGIS/pull/57585

I hope it solves this scenario (which is probably yours):
* WMS connection defined in pre 3.30
* QGIS 3.30+ opens and migrates the settings
* On close, headers were not correctly backported
* On reopen, headers are migrated empty from old settings entries (badly backported on former step)

**Comment by nicogodet** [comment]
@3nids You tried on master ?
I tired on both 3.34 and 3.36 with a new profile and I have the described issue with both. I will retry to be sure...

**Comment by 3nids** [comment]
do you have a chance to check with and without the related fix?

**Comment by nicogodet** [comment]
QGIS3.ini after QGIS is closed
![image](https://github.com/qgis/QGIS/assets/39594821/c932894d-89e2-40ec-8674-250d3d4e196c)

QGIS3.ini after I opened it
![image](https://github.com/qgis/QGIS/assets/39594821/8f48d84b-d8de-46b8-b17f-412aa650cc27)

on fresh profile.

I will try the windows build once it's done ;)
