### ISSUE TITLE
QGIS 3.36 - Export Map to Image (Append Georeference Information embedded or via world file)

### ISSUE THREAD

**Issue by aerosp** [qgis/QGIS#57512]
### What is the bug or the crash?

QGIS 3.36 - Export Map to Image (Append Geo reference Information embedded or via world file)

Geo reference image coordinates not matching with the actual coordinates  

### Steps to reproduce the issue

Project --> Import/Export --> Export Map to Image

### Versions

3.36

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
Can you please attach a ZIP file with a small project and dataset and the step-by-step instructions on how to reproduce this issue?
