### ISSUE TITLE
The difference between the display line style and the printed line style

### ISSUE THREAD

**Issue by ireneuszwojcik** [qgis/QGIS#57516]
### What is the bug or the crash?

I have the following problem: I need to set the styling of a layer on the printout to a dashed line with a segment length of 6 mm and a gap length of 2 mm. I set the line style parameters, but when printing at a scale of 1:1000, these values are different: the segment is about 7 mm and the gap is 0.5 mm. Below is an example of the printout, on the left how it should look, and on the map, you can see how it actually looks. Can anyone help with this issue? Could it be a bug in QGIS?

### Steps to reproduce the issue

et a custom line style with a 6 mm segment and a 2 mm gap for the line.
Print at a scale of 1:1000 and measure the lengths.
![qgis1](https://github.com/qgis/QGIS/assets/47793320/81f02a60-529f-4e55-b19f-9ea12d69b54c)

### Versions

3.16, 3.22, 3.30

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

afasdfsfd

**Comment by Coastal0** [comment]
Try setting your Cap style to 'flat'

![image](https://github.com/qgis/QGIS/assets/25240257/1a873ee5-0609-4e72-8fcb-61ac2a7191a5)
