### ISSUE TITLE
Importing cvs files

### ISSUE THREAD

**Issue by mateusfraga** [qgis/QGIS#57524]
### What is the bug or the crash?

Good afternoon everybody!

I am unable to import coordinate points file with the .cvs extension (UTF-8). After the document is added to the creation form, parameterized and added, the LIMA version of Qgis only adds the spreadsheet and does not create the points on the map. The information in the imported file continues to state that the x and y coordinates remain as text. Any suggestion? I have already completed all the steps suggested in the documentation.

![Erro_qgis_Lima](https://github.com/qgis/QGIS/assets/36503667/44c45b78-e6ae-4d0f-ac7b-2fade53459c0)
[SN3_Acesso_1_anterior.csv](https://github.com/qgis/QGIS/files/15407360/SN3_Acesso_1_anterior.csv)

### Steps to reproduce the issue

I dont understand.

### Versions

Lima

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by aborruso** [comment]
You should uncheck this. Coordinates are not DMS

![image](https://github.com/qgis/QGIS/assets/30607/2ff4e134-ed7e-4980-9953-ebf955be5b26)

**Comment by mateusfraga** [comment]
I achieved! This was the error. Thanks.

**Comment by aborruso** [comment]
> I achieved! This was the error. Thanks.

Ok, please close the issue
