### ISSUE TITLE
Show the number of item select 

### ISSUE THREAD

**Issue by ERHash** [qgis/QGIS#57520]
### Feature description

Hello the community,

I think its nice to show the number of item selected from the map

Could be a notifaction alert above the attribute table or above the current layer 

Best regards

**Comment by uclaros** [comment]
You mean other than the status bar:
![image](https://github.com/qgis/QGIS/assets/11358178/71cbedfe-1911-4632-bc74-8669b2ed09ce)
And attribute table title bar:
![image](https://github.com/qgis/QGIS/assets/11358178/7f139b76-9afd-4fdd-aad2-e5db723cd90c)
?
