### ISSUE TITLE
ATTRIBUTE TABLE

### ISSUE THREAD

**Issue by andredhe90** [qgis/QGIS#57529]
### What is the bug or the crash?

when I export A SELECTION OF SHP FILE THE NEW ARCHIVE IS NOT CORRECT ATTRIBUTE TABLE
![Captura de tela 2024-05-21 233423](https://github.com/qgis/QGIS/assets/170586154/a3c859cb-89c5-4dd9-a521-2d3b3b752688)
![Captura de tela 2024-05-21 233442](https://github.com/qgis/QGIS/assets/170586154/6e633722-0bd9-4ec7-aaa9-82049b797cdc)
![Captura de tela 2024-05-21 233457](https://github.com/qgis/QGIS/assets/170586154/b666425e-796a-4273-b11a-534436c72118)

### Steps to reproduce the issue

.

### Versions

ALL VERSION .

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicholas-ys-tan** [comment]
What do you have in this dropdown menu?

![image](https://github.com/qgis/QGIS/assets/39729063/e64a6322-c623-4c42-8dea-3621aad77a62)

Also curious as to what's going on with the language? Noted you have spanish set but the attribute header is in Korean in one of your screenshots

**Comment by andredhe90** [comment]
now i change the lenguage to english
follow the print
![Captura de tela 2024-05-22 224937](https://github.com/qgis/QGIS/assets/170586154/04bbc36f-b297-4397-967b-b23d15f68583)

**Comment by andredhe90** [comment]
the korean goes just when i export save features. Also the itens of atribute tables not show, like the original shp file

**Comment by uclaros** [comment]
It seems your weird encoding choice causes troubles. Try setting the encoding back to utf-8

**Comment by andredhe90** [comment]
Perfect. thks!
________________________________
De: Stefanos Natsis ***@***.***>
Enviado: quinta-feira, 23 de maio de 2024 03:29
Para: qgis/QGIS ***@***.***>
Cc: andredhe90 ***@***.***>; Author ***@***.***>
Assunto: Re: [qgis/QGIS] ATTRIBUTE TABLE (Issue #57529)


It seems your weird encoding choice causes troubles. Try setting the encoding back to utf-8
