### ISSUE TITLE
3.34.6 problem with opening .qgz on network share

### ISSUE THREAD

**Issue by lemielek** [qgis/QGIS#57535]
Bug: when opening qgz file from network share - mapped disk - on Windows, we get error cannot open that file.
this file opens properly when copied to local disk. 
But it is shared project with many connected files (rasters, etc.) so this is no go.
Error message in the QGIS log panel "error code 28" is displayed.
I found that thread on mail list
https://www.mail-archive.com/qgis-user@lists.osgeo.org/msg53704.html
saying that it is probably connected to updated libzip in 3.34.6.

When we overwrite zip.dll and zlib.dll with files from 3.22.15 problem is gone.

### Steps to reproduce the issue

Install 3.34.6.
Double click on .qgz file on network drive.
Error message appears.

### Versions

Wersja QGIS
3.34.6-Prizren
Rewizja QGIS
623828f5
Wersja Qt
5.15.13
Wersja Pythona
3.12.3
Wersja GDAL/OGR
3.8.5
Wersja PROJ
9.4.0
Wersja bazy danych Rejestru EPSG
v11.004 (2024-02-24)
Wersja GEOS
3.12.1-CAPI-1.18.1
Wersja SQLite
3.45.1
Wersja PDAL
2.6.3
Wersja klienta PostgreSQL
16.2
Wersja SpatiaLite
5.1.0
Wersja QWT
6.2.0
Wersja QScintilla2
2.14.1
Wersja systemu operacyjnego
Windows 11 Version 2009

Active Python plugins
bdot10k
1.0.1
gissupport_plugin
2.1.2
nmt_gugik
1.3
ObliczWysokosc
0.6
pobieracz_danych_gugik
1.0.10
wody_polskie_wms
1.0.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jef-n, since it looks like libzip 1.10.1 currently provided by OSGeo4W makes QGIS not able to open qgz project files on a network share, would it be feasible to downgrade libzip to the previous available version 1.7.3 with which the issue doesn't occur?

**Comment by j-lippmann** [comment]
I can confirm this issue.

**Comment by Skipper-is** [comment]
Can also confirm. Have rolled back to libzip 1.7.3, but it still seems to have the same issue.
![image](https://github.com/qgis/QGIS/assets/28678069/a90e2426-7a15-4b0b-8d50-d9ef9a9f614e)
