### ISSUE TITLE
"Download of schemas in progress"

### ISSUE THREAD

**Issue by aroche** [qgis/QGIS#57540]
### What is the bug or the crash?

Not really a bug, just something to improve.

When you open a project with WFS layers, this message can pop up "Download of schemas in progress..." : 
![image](https://github.com/qgis/QGIS/assets/1985028/b8ab06f2-df0f-4e9d-b6e6-32e10eb27965)
I get that this is related to WFS services, but the message is not really informative, because it doesn't specify what kind of schemas are downloaded.

https://github.com/qgis/QGIS/blob/b6504759be15e93c4112005239ad4cd4c693efa6/src/providers/wfs/qgswfsprovider.cpp#L1828

### Steps to reproduce the issue

Open a project containing WFS layers (not sure exactly which ones cause this message to appear)

### Versions

Version de QGIS
3.36.1-Maidenhead
Révision du code
3e589453
Version de Qt
5.15.3
Version de Python
3.9.18
Version de GDAL/OGR
3.8.4
Version de Proj
9.3.1
Version de la base de données du registre EPSG
v10.098 (2023-11-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.41.1
Version de PDAL
2.6.0
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
commune_cadastre
0.1
Go2NextFeaturePlus
3.0
mask
1.10.2
pluginbuilder3
3.2.1
plugin_reloader
0.9.4
profiletool
4.2.6
SpreadsheetLayers
2.1.2
StreetView
3.2
valuetool
3.0.19
ViewshedAnalysis
1.9
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by pathmapper** [comment]
You'll get this message for a WFS referencing XML schema(s) which triggers the GMLAS driver (https://gdal.org/drivers/vector/gmlas.html). This happens usually for a WFS with complex attributes.

Added some more info to the message in #57546.
