### ISSUE TITLE
Searching "log" in settings crashes qgis (new blank profile fixes it)

### ISSUE THREAD

**Issue by matkoniecz** [qgis/QGIS#57565]
### What is the bug or the crash?

Searching "log" in settings crashes qgis

### Steps to reproduce the issue

Go to Setting menu, select options, place cursor in top-left menu, type "log"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.27.0-Master | QGIS code revision | 9c08adf5ef
-- | -- | -- | --
Qt version | 5.12.8
Python version | 3.8.10
GDAL/OGR version | 3.0.4
PROJ version | 6.3.1
EPSG Registry database version | v9.8.6 (2020-01-22)
Compiled against GEOS | 3.8.0-CAPI-1.13.1 | Running against GEOS | 3.8.0-CAPI-1.13.1
SQLite version | 3.31.1
PDAL version | 2.0.1
PostgreSQL client version | 12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version | 4.3.0a
QWT version | 6.1.4
QScintilla2 version | 2.11.2
OS version | Ubuntu 20.04.6 LTS
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
pobieracz_danych_gugik | 1.0.10
quick_map_services | 0.19.34
archiwalna_ortofotomapa | 1.0.5
MetaSearch | 0.3.6
sagaprovider | 2.12.99
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.27.0-Master
QGIS code revision
[9c08adf5ef](https://github.com/qgis/QGIS/commit/9c08adf5ef)
Qt version
5.12.8
Python version
3.8.10
GDAL/OGR version
3.0.4
PROJ version
6.3.1
EPSG Registry database version
v9.8.6 (2020-01-22)
Compiled against GEOS
3.8.0-CAPI-1.13.1
Running against GEOS
3.8.0-CAPI-1.13.1 
SQLite version
3.31.1
PDAL version
2.0.1
PostgreSQL client version
12.11 (Ubuntu 12.11-0ubuntu0.20.04.1)
SpatiaLite version
4.3.0a
QWT version
6.1.4
QScintilla2 version
2.11.2
OS version
Ubuntu 20.04.6 LTS

This copy of QGIS writes debugging output.

Active Python plugins
pobieracz_danych_gugik
1.0.10
quick_map_services
0.19.34
archiwalna_ortofotomapa
1.0.5
MetaSearch
0.3.6
sagaprovider
2.12.99
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [?] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

(I admit to be greatly confused by roadmap release schedule, but in all projects where I reported bugs before reporting bugs in nightlies was welcome so I assumed the same here)

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

it does NOT crash in a new user profile. Is it automatically making it WONTFIX or should I submit user profile somehow?

Checked https://github.com/qgis/QGIS/blob/a6a32bd1fd97826a0a0e2e6e879cbb949f15681b/.github/CONTRIBUTING.md and there was nothing about issue tracker there

" You must try with a new profile to check if the issue remains." is unclear whether I should bother with reporting if new blank user profile fixes it.

I tried also on version available for focal from https://qgis.org/debian

later I moved to https://ubuntu.qgis.org/ubuntu-nightly/ to check is it in latest version

![Peek 2024-05-25 10-01](https://github.com/qgis/QGIS/assets/899988/9c4c23e5-da18-4bfc-b640-5e7e610177b1)

**Comment by agiudiceandrea** [comment]
@matkoniecz, thanks for reporting. QGIS 3.27 is no longer supported. The latest currently supported versions are QGIS LTR 3.34 and QGIS 3.36 (which is now EOL and will be superseded by QGIS 3.38). Ubuntu 20.04 is no longer supported, so QGIS 3.34 / 3.36 and 3.38 are not available using the qgis.org repositories (see https://qgis.org/en/site/forusers/alldownloads.html#repositories).
QGIS from [Flatpak](https://qgis.org/it/site/forusers/alldownloads.html#flatpak) or [Spack](https://qgis.org/it/site/forusers/alldownloads.html#spack) are usually more up-to-date.
Anyway, if the issue doesn't occur using a new QGIS user profile, then the issue may be due to a non default setting or to an installed external third-party plugin. You could find which one is causing the issue, just disabling the non core's ones one at a time and check each time if the issue does occur.

**Comment by matkoniecz** [comment]
I guess that it is wontfix and I should change OS (and I need to upgrade from Ubuntu to something that is not adware anyway)
