### ISSUE TITLE
Expression output won't show until you open the attribute table (PostGIS layers)

### ISSUE THREAD

**Issue by derekvb** [qgis/QGIS#57578]
### What is the bug or the crash?

When using expressions to show attribute values in a print lay-out in a label object (text object), attribute values will not appear automatically. They will only appear after you've opened the attribute table. This is the case when you're using a PostGIS table to fetch the values from. It does not occur when using for example a GeoPackage layer. 
For some reason QGIS does not automatically fetch values from a PostGIS table in an expression. 

User will have to manually open the attribute table. This undermines the value of using expressions a bit, since they're supposed to reduce the amount of manual work. 

### Steps to reproduce the issue

1. Open a print layout
2. Insert an expression that utilizes some attribute in a PostGIS layer in a label, such as: `attribute( get_feature_by_id( 'project_1c673826_5226_4fe3_b4b1_24ee6e0b44b5',1),  'en_opdrachtgever' )`
3. The attribute value will not show, neither in the lay-out nor in the Insert Expression window preview
![qgis-bin_F5PpDhUWwA](https://github.com/qgis/QGIS/assets/50830605/a25b5741-0057-49cc-9aee-6cb55857a802)
4. Open the attribute table 
5. The attribute value will now show
![afbeelding](https://github.com/qgis/QGIS/assets/50830605/42782f5e-4d6b-4815-88aa-58fe5288a318)

https://github.com/qgis/QGIS/assets/50830605/119d1d3e-6b3a-4cd5-b9f2-b7aadc277673

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS-versie | 3.34.7-Prizren | QGIS code revisie | 6f7d735c
-- | -- | -- | --
Qt versie | 5.15.13
Python versie | 3.12.3
GDAL/OGR versie | 3.9.0
PROJ versie | 9.4.0
EPSG-register databaseversie | v11.004 (2024-02-24)
GEOS versie | 3.12.1-CAPI-1.18.1
SQLite versie | 3.45.1
PDAL versie | 2.6.3
PostgreSQL client versie | 16.2
SpatiaLite versie | 5.1.0
QWT versie | 6.2.0
QScintilla2 versie | 2.14.1
OS versie | Windows 10 Version 2009
  |   |   |  
Actieve Python plug-ins
CityJSON-loader | 0.8.1
geoscience | 1.12
MemoryLayerSaver | 5.0.2
pdokservicesplugin | 5.0.1
QuickOSM | 2.2.3
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I cannot reproduce on 3.36 and master. Can you check if this issue has been fixed in more recent versions?

**Comment by derekvb** [comment]
I can reproduce the issue on 3.36.3
However, enabling 'Use estimated table metadata' in the PostGIS connection window makes a difference: when enabled, the attribute values will appear immediately in the Insert Expression Window. However, when I close the whole project and re-open it, and then re-open the print lay-out, the attribute values will still not be shown untill I've opened the attribute table.

**Comment by derekvb** [comment]
I did some further testing. I strongly suspect the issue only occurs with tables with no geometry. I could not reproduce the issue with tables with geometry.
