### ISSUE TITLE
GRASS Tools Modules list view goes blank if I attempt to search

### ISSUE THREAD

**Issue by gregorywaynepower** [qgis/QGIS#57572]
### What is the bug or the crash?

I was attempting to follow the instructions from [26.9. Importing data into a GRASS LOCATION](https://docs.qgis.org/3.34/en/docs/user_manual/grass_integration/grass_integration.html#importing-data-into-a-grass-location) and ran into the following:

GRASS Tools tab goes blank once I attempt to search through the modules. Even if I delete my search terms, I can't interact with the Module's tab list view anymore and have to restart QGIS to be able to interact with Modules within the Modules tab list view.

### Steps to reproduce the issue

1. Go to Plugins
2. Go to Open Mapset
3. Add string to Filter box.

https://github.com/qgis/QGIS/assets/31050507/efc46906-9baf-4182-b591-59083ac0cbdf

### Versions

QGIS version
3.36.3-Maidenhead
QGIS code revision
2df96554
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
DigitizingTools
1.5.2
felt
2.0.1
latlontools
3.6.20
Mergin
2024.1
orfeoToolbox_provider
3.0.3
ORStools
1.8.2
processing_saga_nextgen
1.0.0
qfieldsync
v4.9.1
QNEAT3
1.0.5
QuickOSM
2.2.3
quick_map_services
0.19.34
slyr_community
5.0.0
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

I have also tested this on the ubuntugis-unstable as well to the same affect:

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df9655469b
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.37.2
PDAL version | 2.6.2
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Pop!_OS 22.04 LTS
  |   |   |  
Active Python plugins
QNEAT3 | 1.0.5
latlontools | 3.6.20
wbt_for_qgis | 1.0.9
quick_map_services | 0.19.34
processing_saga_nextgen | 1.0.0
GeometryShapes | 0.7
mmqgis | 2021.9.10
HCMGIS | 24.1.12
DigitizingTools | 1.5.2
slyr_community | 5.0.0
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.36.3-Maidenhead
QGIS code revision
[2df9655469b](https://github.com/qgis/QGIS/commit/2df9655469b)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.37.2
PDAL version
2.6.2
PostgreSQL client version
14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version
5.1.0
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Pop!_OS 22.04 LTS

Active Python plugins
QNEAT3
1.0.5
latlontools
3.6.20
wbt_for_qgis
1.0.9
quick_map_services
0.19.34
processing_saga_nextgen
1.0.0
GeometryShapes
0.7
mmqgis
2021.9.10
HCMGIS
24.1.12
DigitizingTools
1.5.2
slyr_community
5.0.0
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This was fixed by https://github.com/qgis/QGIS/pull/56924
