### ISSUE TITLE
[Layout manager] The `wordwrap` expression function fails if the legend item is set to `hidden`

### ISSUE THREAD

**Issue by MrChebur** [qgis/QGIS#57589]
### What is the bug or the crash?

In the `Legend` item of the `Layout Manager`, you can set an expression like this: 
`wordwrap(@symbol_label, 15, ' ')`
which inserts a new lines in the text if it is too long.

`wordwrap` fails if you enable the atlas and set the legend item `hidden`, and works again if you set it back to `group` or `subgroup`.

Also the `wordwrap` function works if you click on the legend item and press `refresh` button. 
And it doesn't work if you deselect the legend item and click `refresh` button.

Here is a screencast of the bug and `qgs` file with data for testing: [Bug screencast and qgs file.zip](https://github.com/qgis/QGIS/files/15467688/GITHUB.4.legend.word.wrap.refresh.zip)

![bug](https://github.com/qgis/QGIS/assets/20655102/d283b0e7-3dc5-404b-a8a4-ec951efeed18)

### Steps to reproduce the issue

1. Open QGIS project (see attached zip archive).
2. Open layout manager and open layout `test`.
3. Turn on the `Preview atlas` button.
4. Turn legend item to `hidden` state (it's already done in the `test` layout).
5. Push `next feature` or `previous feature` button.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df96554
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
AppendFeaturesToLayer | 2.0.0
DigitizingTools | 1.5.2
firstaid | 3.1.1
FreehandRasterGeoreferencer | 0.8.3
Go2NextFeature3 | 2.1
latlontools | 3.6.20
loadthemall | 3.4
MapsPrinter | 0.9
orfeoToolbox_provider | 3.0.3
pluginbuilder3 | 3.2.1
plugin_reloader | 0.9.4
quick_map_services | 0.19.34
scheme_builder | 0.1
valuetool | 3.0.19
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I tested the project with current master (on Linux) and I cannot reproduce it, can you please check if the problem has been solved in current master on a Windows build?

**Comment by MrChebur** [comment]
@elpaso
