### ISSUE TITLE
ign wmts stream access problem

### ISSUE THREAD

**Issue by pnrm** [qgis/QGIS#57592]
Hello,
We have the problem with the recent ign stream https://data.geopf.fr/private/wmts?SERVICE=WMTS&VERSION=1.0.0&REQUEST=GetCapabilities
since version 3.34.6 of QGIS on Windows 10 (it works on previous versions).
![image](https://github.com/qgis/QGIS/assets/18323883/a3d2c810-7d0d-4880-861e-4016998c9110)

_Originally posted by @pnrm in https://github.com/qgis/QGIS/issues/53857#issuecomment-2135313568_

**Comment by nicogodet** [comment]
Root cause is linked to https://github.com/qgis/QGIS/issues/57499

Workaround : Edit connection and add http headers again.

**Comment by nicogodet** [comment]
@3nids probably not in the scope of your current PR but it could be nice to have a meaningful error message instead of the one currently displayed.

Without header, server returns a 401 error Authorization Required.

**Comment by nicogodet** [comment]
Existing connections will have to be edited to re-add headers but the fact they disappears is fixed in https://github.com/qgis/QGIS/pull/57585.

**Comment by pnrm** [comment]
problem resolved, this certigna certificate was missing on the stations where it did not work
