### ISSUE TITLE
Qgis crashes while digitising lines 

### ISSUE THREAD

**Issue by simonh65** [qgis/QGIS#57617]
### What is the bug or the crash?

QGIS hangs/crashes/unresponsive when digitising/creating new line elements.
I have tried editing an existing shape file and temporary scratch layer.
Using 3.36.3, and updated from 3.36.2 - same problem

### Steps to reproduce the issue

set layer to edit mode
Select Add line feature (ctrl .)
digitise points
complete attributes menu
..... thats it! nothing else 

### Versions

QGIS version
3.36.3-Maidenhead
QGIS code revision
2df96554
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
Failed to reproduce on master with a memory layer.

Could you try with a clean profile ? or current LTS with 3.34.7 ?

**Comment by simonh65** [comment]
Look like a corrupt user profile - weird!
Apologies

Simon
________________________________

**Comment by troopa81** [comment]
I close, please reopen if you manage to reproduce it
