### ISSUE TITLE
QGIS crash when exporting a composition to pdf

### ISSUE THREAD

**Issue by ThiccLegss** [qgis/QGIS#57619]
### What is the bug or the crash?

When i try to save to PDF a composition the app just crashes without any message whatsoever, the module thats causing the issue is: Qt5Widgets.dll

### Steps to reproduce the issue

Go to 'Design' in a composition, click on 'Export as PDF', see error.

### Versions

3.34.3-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
probably a duplicate of to https://github.com/qgis/QGIS/issues/50543. Are you using masks ?

If no, please share project and data
