### ISSUE TITLE
Right mouse click deletes new vertex, it doesn't close/lock it.

### ISSUE THREAD

**Issue by Jubbagash** [qgis/QGIS#57629]
### What is the bug or the crash?

1. Create new scratch layer
2. Add polygon using 'Add polygon feature' button
3. Draw polygon on map
4. Right clicking mouse button should finalise the new polygon, but it deletes it instead

### Steps to reproduce the issue

1. Create new scratch layer
2. Add polygon using 'Add polygon feature' button
3. Draw polygon on map
4. Right clicking mouse button should finalise the new polygon, but it deletes it instead

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df9655469b
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 14.5
  |   |   |  
Active Python plugins
profiletool | 4.2.6
quick_map_services | 0.19.34
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>QGIS version
3.36.3-Maidenhead
QGIS code revision
[2df9655469b](https://github.com/qgis/QGIS/commit/2df9655469b)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 14.5

Active Python plugins
profiletool
4.2.6
quick_map_services
0.19.34
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
I cannot reproduce this.
Are you sure @Jubbagash that you're adding at least 3 vertices?
Are you using _Digitize with segment_ mode?
![image](https://github.com/user-attachments/assets/e5e1dd3e-51dc-4a49-8dd6-ee91b9616fba)
