### ISSUE TITLE
vector tab no drop down menu

### ISSUE THREAD

**Issue by AswinAB128** [qgis/QGIS#57626]
### What is the bug or the crash?

I have installed QGIS version 3.34.6. I can't access the vector drop-down menu. I have tried uninstalling it and updating the software but still not working. 
![image](https://github.com/qgis/QGIS/assets/171329227/edde63a0-8e60-4ab1-a895-890578f93e4d)

### Steps to reproduce the issue

na

### Versions

QGIS version
3.34.6-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
@AswinAB128 Activate the "Processing" plugin in "Plugins --> Manage and Install plugins..." dialog.
