### ISSUE TITLE
QGIS Server wrongly positions the map objects in the output when there's more than one map

### ISSUE THREAD

**Issue by tudorbarascu** [qgis/QGIS#57631]
### What is the bug or the crash?

Having this project: 
[ziua_11.zip](https://github.com/user-attachments/files/15512141/ziua_11.zip) when doing the export from QGIS the pdf is looking as in the project but when doing it from the server the maps objects in the response pdf are not positioned where they should be.

How it looks in the layout and in QGIS Desktop export:
![image](https://github.com/qgis/QGIS/assets/3179646/66c31b73-f53d-4e35-b8a1-6614179e5eb6)

How it looks through QGIS Server GetPrint:
![image](https://github.com/qgis/QGIS/assets/3179646/66eb52e1-1e8b-42b8-9dda-586cb2bd90fa)

I tested on QGIS Server 3.34.7 both on Ubuntu 22.04 and on 24.04.

### Steps to reproduce the issue

1. Add the project above in QGIS Server:

2. Make this request (with your QGIS Server url of course): http://localhost:8089/qtb/ziua_11?SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&TEMPLATE=raport1&DPI=150&STYLES=default&LAYERS=terenuri&FORMAT=pdf&CRS=EPSG:3844&filtertoken=&map0:SCALE=20000&map0:EXTENT=591468.5645834132,392378.97707454,592884.1307850145,394477.61707453994&map0:ROTATION=0&map1:SCALE=20000&map1:EXTENT=591468.5645834132,392378.97707454,592884.1307850145,394477.61707453994&map1:ROTATION=0&map2:SCALE=20000&map2:EXTENT=591468.5645834132,392378.97707454,592884.1307850145,394477.61707453994&map2:ROTATION=0

3. The maps objects are now in their original position.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.7-Prizren | QGIS code revision | 6f7d735cae3
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.4
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.2 (Ubuntu 16.2-1ubuntu4)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Ubuntu 24.04 LTS

</body></html>QGIS version
3.34.7-Prizren
QGIS code revision
[6f7d735cae3](https://github.com/qgis/QGIS/commit/6f7d735cae3)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.4
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PostgreSQL client version
16.2 (Ubuntu 16.2-1ubuntu4)
SpatiaLite version
5.1.0
QWT version
6.1.4
QScintilla2 version
2.14.1
OS version
Ubuntu 24.04 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

If I change the reference map of the detailed maps I get different location of the map objects in the GetPrint output
![image](https://github.com/g3w-suite/g3w-admin/assets/3179646/df172a63-0422-4c13-9ff8-c47b68623844)

**Comment by jgrocha** [comment]
Confirmed

**Comment by elpaso** [comment]
@tudorbarascu I'm not sure this is a bug: the server respects the BBOX which is smaller (shorter) than size of the element and resizes it accordingly.

The QGIS desktop layout exporter does all the extent calculations to fix the map into the desired map item frame size.

In the server this  is delegated to the caller that can "resize" the map by defining a different BBOX.

To get what you want you need to change the call to get the extent `EXTENT=591468.5645834132,392758.97707454,592884.1307850145,394477.61707453994` that fits into the frame (almost) exactly.

**Comment by elpaso** [comment]
Also, this can be reproduced with just a single map and to my understanding it's not about positioning of the map element but about resizing. 
Changing the anchor point will obviously alter the positioning.

**Comment by elpaso** [comment]
Here is an example with the new BBOX (I changed the test template to have a single map and added a label below to check the alignment but it doesn't change the basic behavior).

![immagine](https://github.com/qgis/QGIS/assets/142164/02d00db7-6df8-43be-a47f-e3f16eea7504)

**Comment by wlorenzetti** [comment]
@tudorbarascu it's a QGIS-Server BUG

**Comment by elpaso** [comment]
> @tudorbarascu it's a QGIS-Server BUG

@wlorenzetti  I am not sure it is a bug in the server:. you are supposed to pass the exact extent (BBOX) and SCALE of the map you want to appear into the map item or it will be resized. The calling application must do all the calculations to make sure the BBOX height and width are proportional to the map frame size and the SCALE must also be calculated correctly.

This gives to the application the flexibility to resize the map if needed, by specifying a BBOX or a SCALE that do not fit exactly in the map frame.

**Comment by jgrocha** [comment]
Thank you @elpaso for looking into this. I agree with you: the calling application should do the calculations and provide the correct options for the GetPrint call.

I don't think this is a bug.

Using my own web application, the layout is generated as expected.

Using these arguments:
```
SERVICE=WMS&VERSION=1.3.0&REQUEST=GetPrint&FORMAT=pdf&TRANSPARENT=true&TEMPLATE=raport1&DPI=400&CRS=EPSG:3857&map0:extent=2626915.757572769,5913293.09519144,2627125.017572769,5913434.0551914405&map0:SCALE=2000&map0:LAYERS=terenuri&map1:extent=2626725.3175727692,5913086.57519144,2627315.457572769,5913640.57519144&map1:SCALE=2000&map1:LAYERS=terenuri
```
 The generated output is:

[print.pdf](https://github.com/user-attachments/files/15536616/print.pdf)

**Comment by wlorenzetti** [comment]
> > @tudorbarascu it's a QGIS-Server BUG
> 
> @wlorenzetti  I am not sure it is a bug in the server:. you are supposed to pass the exact extent (BBOX) and SCALE of the map you want to appear into the map item or it will be resized. The calling application must do all the calculations to make sure the BBOX height and width are proportional to the map frame size and the SCALE must also be calculated correctly.
> 
> This gives to the application the flexibility to resize the map if needed, by specifying a BBOX or a SCALE that do not fit exactly in the map frame.
> 
> 

ok Thanks @elpaso

**Comment by elpaso** [comment]
I think we can close this.

**Comment by tudorbarascu** [comment]
Thanks for the info!
