### ISSUE TITLE
3d views are completely black on Qt 6.7

### ISSUE THREAD

**Issue by nyalldawson** [qgis/QGIS#57640]
### What is the bug or the crash?

I'm not sure if this is an upstream regression, or indicative of something we are doing wrong -- but on Qt 6.7.0 / 6.7.1 all 3d views and renders are completely black. There's no errors or warnings logged by Qt3d, we just get.... nothing.

I can't find any related upstream issues. There's a similar report at https://github.com/organicmaps/organicmaps/issues/7838 though.

### Steps to reproduce the issue

1. Use a build based on Qt 6.7
2. Try to open a 3d window, run the 3d rendering tests, or run the 3d sandbox app.

### Versions

All

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
@wonder-sk 

> Ouch... which platform is that? (and if linux - is it wayland or x11?)

Fedora 40, on x11 (Wayland is *still* broken for common operations like toolbar drags 🤷‍♂️)

I looked through the commit history for qt3d and can't see anything which jumps out, it all seems quite minor changes....

**Comment by t0b3** [comment]
@nyalldawson unable to reproduce black 3d view here using Qt6.7.3
![image](https://github.com/user-attachments/assets/fa13da39-2eb8-4ff4-bc66-4fff8cf23768)
HTH

**Comment by nyalldawson** [comment]
@t0b3 right, I can confirm that this is also fixed on 6.8.0! Thanks!
