### ISSUE TITLE
Shift in the map legend

### ISSUE THREAD

**Issue by cbouchardt** [qgis/QGIS#57660]
### What is the bug or the crash?

It seems that there is a shift of the legend frame when saving a layout in pdf
<img width="1212" alt="Layout_saved_as_pdf" src="https://github.com/qgis/QGIS/assets/107418001/f837cc07-712a-4ada-acda-e712a445f8a0">
![Layout](https://github.com/qgis/QGIS/assets/107418001/779a57bc-28bf-4ac7-b2f5-d49f980c3279)

### Steps to reproduce the issue

1. Go to the layout creator tool
2. Insert a map
3. Insert a legend
4. position the legend so you can see the shift
5. Save as pdf

### Versions

Version de QGIS | 3.34.7-Prizren | Révision du code | 6f7d735cae3
-- | -- | -- | --
Version de Qt | 5.15.2
Version de Python | 3.9.5
Version de GDAL/OGR | 3.3.2
Version de Proj | 8.1.1
Version de la base de données du registre EPSG | v10.028 (2021-07-07)
Version de GEOS | 3.9.1-CAPI-1.14.2
Version de SQLite | 3.35.2
Version de PDAL | 2.3.0
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.6
Version de QScintilla2 | 2.11.5
Version de l'OS | macOS 14.2
  |   |   |  
Extensions Python actives
LAStools | 2.1.0
qchainage | 3.0.1
MapsPrinter | 0.9
pointsamplingtool | 0.5.4
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

</body></html>Version de QGIS
3.34.7-Prizren
Révision du code
[6f7d735cae3](https://github.com/qgis/QGIS/commit/6f7d735cae3)
Version de Qt
5.15.2
Version de Python
3.9.5
Version de GDAL/OGR
3.3.2
Version de Proj
8.1.1
Version de la base de données du registre EPSG
v10.028 (2021-07-07)
Version de GEOS
3.9.1-CAPI-1.14.2
Version de SQLite
3.35.2
Version de PDAL
2.3.0
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.0.1
Version de QWT
6.1.6
Version de QScintilla2
2.11.5
Version de l'OS
macOS 14.2

Extensions Python actives
LAStools
2.1.0
qchainage
3.0.1
MapsPrinter
0.9
pointsamplingtool
0.5.4
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
My guess is that your legend is set to resize and during the final eval it just reduced the blank space on the right.

**Comment by cbouchardt** [comment]
Indeed, that was the problem. I uptaded recently to the last LTR and the resize option was not available or automatically activated on the previous QGIS version i was using.  Thank you for the quick answer
