### ISSUE TITLE
JSON-String not read from GPKG

### ISSUE THREAD

**Issue by SGroe** [qgis/QGIS#57673]
### What is the bug or the crash?

I converted a DXF file to GPKG using ogr2ogr. Some block attributes are written to the field BlockAttributes (layer entities). According to ogrinfo (see below), the key-value-pairs are set correctly. Reading the GPKG in QGIS, I see an empty String ("") instead of the (JSON) value.

### Steps to reproduce the issue

1. Download example DXF file https://github.com/OSGeo/gdal/blob/master/autotest/ogr/data/dxf/attrib.dxf
2. Convert DXF to GPKG using `ogr2ogr --config DXF_INLINE_BLOCKS FALSE -f "GPKG" C:/Users/sgr/Downloads/attrib.gpkg "C:/Users/sgr/Downloads/attrib.dxf"`
3. See BlockAttributes value set at first feature of layer entities using `ogrinfo C:/Users/sgr/Downloads/attrib.gpkg entities -geom=no`
4. Also see the field type String(JSON)
5. Load GPKG file in QGIS
6. Open attribute table of layer "attrib — entities"
7. Field BlockAttributes has type JSON, but the value is not set

### Versions

QGIS-Version
3.36.3-Maidenhead
QGIS-Codeversion
2df96554
Qt-Version
5.15.13
Python-Version
3.12.3
GDAL-Version
3.9.0
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.1-CAPI-1.18.1
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I cannot reproduce, I followed your instructions but there is no JSON type:

```
gh_57673.gpkg entities -geom=no
INFO: Open of `gh_57673.gpkg'
      using driver `GPKG' successful.

Layer name: entities
Geometry: Unknown (any)
Feature Count: 2
Extent: (10.000000, -10.000000) - (110.000000, 20.000000)
Layer SRS WKT:
GEOGCRS["Undefined geographic SRS",
    DATUM["unknown",
        ELLIPSOID["unknown",6378137,298.257223563,
            LENGTHUNIT["metre",1,
                ID["EPSG",9001]]]],
    PRIMEM["Greenwich",0,
        ANGLEUNIT["degree",0.0174532925199433,
            ID["EPSG",9122]]],
    CS[ellipsoidal,2],
        AXIS["latitude",north,
            ORDER[1],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]],
        AXIS["longitude",east,
            ORDER[2],
            ANGLEUNIT["degree",0.0174532925199433,
                ID["EPSG",9122]]]]
Data axis to CRS axis mapping: 2,1
FID Column = fid
Geometry Column = geom
Layer: String (0.0)
PaperSpace: Integer(Boolean) (0.0)
SubClasses: String (0.0)
Linetype: String (0.0)
EntityHandle: String (0.0)
Text: String (0.0)
BlockName: String (0.0)
BlockScale: String (0.0)
BlockAngle: Real (0.0)
BlockOCSNormal: String (0.0)
BlockOCSCoords: String (0.0)
BlockAttributes: String (0.0)
Block: String (0.0)
AttributeTag: String (0.0)
OGRFeature(entities):1
  Layer (String) = 0
  PaperSpace (Integer(Boolean)) = (null)
  SubClasses (String) = AcDbEntity:AcDbBlockReference
  Linetype (String) = (null)
  EntityHandle (String) = 56B
  Text (String) = (null)
  BlockName (String) = AttBlock
  BlockScale (String) = (3:1,1,1)
  BlockAngle (Real) = 0
  BlockOCSNormal (String) = (3:0,0,1)
  BlockOCSCoords (String) = (3:10,20,0)
  BlockAttributes (String) = (3:MYATT1 super test,MYATTMULTI_001 Corps,MYATTMULTI_002 plpl)
  Block (String) = (null)
  AttributeTag (String) = (null)

OGRFeature(entities):2
  Layer (String) = 0
  PaperSpace (Integer(Boolean)) = (null)
  SubClasses (String) = AcDbEntity:AcDbBlockReference
  Linetype (String) = (null)
  EntityHandle (String) = C07
  Text (String) = (null)
  BlockName (String) = AttBlock
  BlockScale (String) = (3:1,1,1)
  BlockAngle (Real) = 0
  BlockOCSNormal (String) = (3:0,0,1)
  BlockOCSCoords (String) = (3:110,-10,0)
  BlockAttributes (String) = (1:MYATTMULTI )
  Block (String) = (null)
  AttributeTag (String) = (null)
```

The content does not look like valid JSON:

![immagine](https://github.com/qgis/QGIS/assets/142164/7419a511-4655-4693-bbf6-071315f5e200)

**Comment by SGroe** [comment]
ogrinfo gives me:

```
...
OGRFeature(entities):1
  Layer (String) = 0
  PaperSpace (Integer(Boolean)) = (null)
  SubClasses (String) = AcDbEntity:AcDbBlockReference
  Linetype (String) = (null)
  EntityHandle (String) = 56B
  Text (String) = (null)
  BlockName (String) = AttBlock
  BlockScale (String(JSON)) = [ 1.0, 1.0, 1.0 ]
  BlockAngle (Real) = 0
  BlockOCSNormal (String(JSON)) = [ 0.0, 0.0, 1.0 ]
  BlockOCSCoords (String(JSON)) = [ 10.0, 20.0, 0.0 ]
  BlockAttributes (String(JSON)) = [ "MYATT1 super test", "MYATTMULTI_001 Corps", "MYATTMULTI_002 plpl" ]
  Block (String) = (null)
  AttributeTag (String) = (null)
...
```

This is a valid JSON list.

@elpaso: do you use an older/newer version of gdal?

**Comment by SGroe** [comment]
This is my GPKG file that I cannot read correctly in QGIS.

[attrib.zip](https://github.com/user-attachments/files/15641946/attrib.zip)

**Comment by elpaso** [comment]
> ogrinfo gives me:
> 
> ```
> ...
> OGRFeature(entities):1
>   Layer (String) = 0
>   PaperSpace (Integer(Boolean)) = (null)
>   SubClasses (String) = AcDbEntity:AcDbBlockReference
>   Linetype (String) = (null)
>   EntityHandle (String) = 56B
>   Text (String) = (null)
>   BlockName (String) = AttBlock
>   BlockScale (String(JSON)) = [ 1.0, 1.0, 1.0 ]
>   BlockAngle (Real) = 0
>   BlockOCSNormal (String(JSON)) = [ 0.0, 0.0, 1.0 ]
>   BlockOCSCoords (String(JSON)) = [ 10.0, 20.0, 0.0 ]
>   BlockAttributes (String(JSON)) = [ "MYATT1 super test", "MYATTMULTI_001 Corps", "MYATTMULTI_002 plpl" ]
>   Block (String) = (null)
>   AttributeTag (String) = (null)
> ...
> ```
> 
> This is a valid JSON list.
> 
> @elpaso: do you use an older/newer version of gdal?

ogr2ogr --version
GDAL 3.4.1, released 2021/12/27

**Comment by elpaso** [comment]
I forgot to state the obvious: changing the widget type from "key/value" to "list" in the form configuration fixes this issue.

**Comment by SGroe** [comment]
@elpaso : thank you for your suggestion of changing the form configuration and the proposed improvement
