### ISSUE TITLE
Default output format of vector and raster layers are getting changed to .xtf and .nc respectively without user consent causing Processing Algorithms to crash

### ISSUE THREAD

**Issue by ar-siddiqui** [qgis/QGIS#57676]
### What is the bug or the crash?

A lot of users are reporting that processing algorithms are crashing due to the default output format of vector and raster layers being changed to .xtf and .nc respectively without the user's consent. This occurred to me as well. I do not remember installing any new plugins recently, that might have updated settings without my permission.

Many issues have been reported before but have been prematurely closed. There has been discussion in those issues as well about the cause of the bug without any conclusion.

Of course if a new profile is created, the settings are default, hence the issue no longer exists.

https://github.com/qgis/QGIS/issues/54952
https://github.com/qgis/QGIS/issues/54375
https://github.com/qgis/QGIS/issues/55110#issuecomment-1873415345
https://github.com/qgis/QGIS/issues/57250
https://github.com/qgis/QGIS/issues/57267

https://lists.osgeo.org/pipermail/qgis-developer/2024-February/066539.html

https://www.facebook.com/groups/qgiscommunityofficialvirtualgroup/posts/2523886831123186/
https://www.facebook.com/groups/qgiscommunityofficialvirtualgroup/posts/2534859280025941/
https://www.facebook.com/groups/GisItalia/posts/10161207159211385/
https://www.facebook.com/groups/GisItalia/posts/10161423743961385

https://gis.stackexchange.com/questions/463507/contour-polygons-warning-model-file-not-specified
https://gis.stackexchange.com/questions/477614/polygonize-error
https://gis.stackexchange.com/questions/474162/qgis-converting-simple-png-raster-file-yields-warning-1-model-file-not-specifi
https://gis.stackexchange.com/questions/463099/clip-raster-by-mask-layer-attempt-gives-error-1-netcdf-chunk-fetch-failed
https://gis.stackexchange.com/questions/467079/qgis-polygonize-tool-error

### Steps to reproduce the issue

N/A

### Versions

3.28.11
3.32.3
and many more

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ar-siddiqui, thanks for reporting.
I think it would be useful if you checked and reported the `default-output-vector-layer-ext`,  `default-output-raster-layer-ext`,  `DefaultOutputVectorLayerExt`, `DefaultOutputRasterLayerExt` settings values stored in the `QGIS3.ini` file located in `user profile folder / QGIS /` for the affected systems.
