### ISSUE TITLE
<string>:1: DeprecationWarning: setapi() is deprecated Command --noversioncheck not known!

### ISSUE THREAD

**Issue by sugizo** [qgis/QGIS#57683]
### What is the bug or the crash?

**execute** 
`qgis_process`

**result**
```
<string>:1: DeprecationWarning: setapi() is deprecated
Command --noversioncheck not known!
```

### Steps to reproduce the issue

**install qgis from debian repo** 
```
apt update
apt install -y qgis
```

### Versions

**execute**
`qgis -v`

**result**
`QGIS 3.22.16-Białowieża 'Białowieża' (exported)`

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@sugizo, thanks for reporting. QGIS 3.22 is no longer supported. Please try if the issue occurs also using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

**Comment by sugizo** [comment]
fixed in latest version, thanks

**steps**
```
sudo apt update
sudo apt install -y gnupg software-properties-common
sudo wget -O /etc/apt/keyrings/qgis-archive-keyring.gpg https://download.qgis.org/downloads/qgis-archive-keyring.gpg
sudo cat << EOF > /etc/apt/sources.list.d/qgis.sources
Types: deb deb-src
URIs: https://qgis.org/debian
Suites: bookworm
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
EOF
sudo apt update
sudo apt install -y qgis
qgis_process
```

best regards
