### ISSUE TITLE
Model in model: misleading error message

### ISSUE THREAD

**Issue by pathmapper** [qgis/QGIS#57698]
### What is the bug or the crash?

There is a misleading error message for a model that is used in another model

"The following layers were not correctly generated." 

![image](https://github.com/qgis/QGIS/assets/20856381/b48c6158-fbc0-4951-9f07-fc6b8400cf9a)

![image](https://github.com/qgis/QGIS/assets/20856381/7bd15e4f-903b-47ea-8966-14f732d4f9cb)

### Steps to reproduce the issue

1. Open test project: [test.zip](https://github.com/user-attachments/files/15685503/test.zip)
2. Run project model "model1" 
![image](https://github.com/qgis/QGIS/assets/20856381/ba192134-558b-4733-9e23-11149cf66772)

### Versions

QGIS version | 3.37.0-Master | QGIS code revision | 756cb0552e3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.9.0dev-18f9ed2b7c
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99
db_manager | 0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The issue occurs using QGIS 3.34.7 and QGIS 3.36.3. The issue didn't occur using QGIS 3.28.15.

**Comment by pathmapper** [comment]
Thanks for the confirmation, @agiudiceandrea.
