### ISSUE TITLE
Check validity core plugin issue

### ISSUE THREAD

**Issue by Majo172** [qgis/QGIS#57704]
### What is the bug or the crash?

I am suspecting a problem with the "check validity" core plugin. It is not giving me all the invalid points there are. I made a polygon riddled with errors to test it and it only gave me a single error output in each polygon I drew. Am anyone else experiencing the same issue?
Let me add that I am not using the latest edition, I am using "Firenze". I am bound by a work computer. I am not allowed to update it. 
![image](https://github.com/qgis/QGIS/assets/167202085/0ee24d18-fccc-4bd1-b8d2-b593c6a16369)
See green polygons in photo. I am only getting a single error in each polygon. I would think there should be a lot more.

### Steps to reproduce the issue

Draw a polygon riddled with errors (lots of overlaps) and Vector --> Geometry Tools --> "check validity" on the layer you drew the polygon in.

### Versions

QGIS version
3.28.6-Firenze
QGIS code revision
868c9fa03b
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.6.4
PROJ version
9.2.0
EPSG Registry database version
v10.082 (2023-02-06)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.41.1
PDAL version
2.5.2
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
Dataforsyningen
0.4
dmpcatalogue
1.1.1
EasyCustomLabeling
2.1
GeoCoding
2.19
GeometryShapes
0.7
geosearch_dk
2.0.0
NNJoin
3.1.3
QGIS3-getWKT
1.6
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
Please read the documentation for the tool. You can choose different method to check for errors and will receive all geometry errors at once.
