### ISSUE TITLE
impossible à ouvrir après téléchargement sur MAC BOOK PRO

### ISSUE THREAD

**Issue by Carinecc76** [qgis/QGIS#57716]
### What is the bug or the crash?

en Français SVP : j'ai pu téléchargé un jour l'application que j'ai supprimé car elle prenait trop de place... j'en ai absolument pour un devoir à rendre à l'université... et mon ordinateur macbook pro ne veut plus ouvrir le fichier téléchargé :( comment résoudre le problème SVP merci merci

### Steps to reproduce the issue

impossible d'ouvrir

### Versions

QGIS 3.36 et 3.34 c'est pareil

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
See https://github.com/qgis/QGIS/issues/32167

**Comment by m-kuhn** [comment]
More precisely https://github.com/qgis/QGIS/issues/32167#issuecomment-539938962

**Comment by agiudiceandrea** [comment]
As it is also explained in the download page

![image](https://github.com/qgis/QGIS/assets/16253859/713aabf2-1bdf-415b-9b55-0f1dce22372f)

**Comment by Carinecc76** [comment]
thank you and I specified that I tested the two possibilities that you shared with me...

> As it is also explained in the download page:
> 
> https://qgis.org/fr/site/forusers/download.html#mac
> 
> ![image](https://private-user-images.githubusercontent.com/16253859/337888096-713aabf2-1bdf-415b-9b55-0f1dce22372f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc4NTk3NjksIm5iZiI6MTcxNzg1OTQ2OSwicGF0aCI6Ii8xNjI1Mzg1OS8zMzc4ODgwOTYtNzEzYWFiZjItMWJkZi00MTViLTliNTUtMGYxZGNlMjIzNzJmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjA4VDE1MTEwOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZTQ5N2ZkZjUyZDZlMTFlZDRkMmI3NjRhMTE4Y2U5MmY4ZGIyNDQ1M2I0ZTI2ZGI4ZjRmMGM2M2RkY2IzMDAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rkqzGinKkUHjeo8PubjWMEJbpR-20AuljrK48ffCXU8)
> 
> > Après installation,QGIS renverra un message d'échec pour raison de sécurité lors du premier lancement. Pour activer QGIS, faites un clic droit sur son icône dans le dossier Applications et sélectionnez Ouvrir dans le menu contextuel. Une fenêtre de confirmation s'ouvrira de laquelle vous cliquerez à nouveau sur Ouvrir. Cette procédure est à réaliser une seule fois.

**Comment by Carinecc76** [comment]
I'm on monterey 12.7.1

> More precisely [#32167 (comment)](https://github.com/qgis/QGIS/issues/32167#issuecomment-539938962)

**Comment by m-kuhn** [comment]
Please read carefully through the linked discussion and try the suggestions.
If they don't work, please describe exactly what you tried and what you are seeing / what errors you get.

Thank you

**Comment by Carinecc76** [comment]
> Please read carefully through the linked discussion and try the suggestions. If they don't work, please describe exactly what you tried and what you are seeing / what errors you get.
> 
> Thank you

if I could ever have an exchange in French that would help me better too thank you :)

**Comment by agiudiceandrea** [comment]
@Carinecc76, you can use the forum of QGIS's francophone users at https://discourse.osgeo.org/c/qgis/qgis-fr-user/.
