### ISSUE TITLE
Missing symbology

### ISSUE THREAD

**Issue by Icaro-Fonseca** [qgis/QGIS#57732]
### What is the bug or the crash?

Não aparece as opções de simbologia padrão que acompanhava as demais versões do programa.

### Steps to reproduce the issue

![QGIS_bug](https://github.com/qgis/QGIS/assets/172390999/97b07bf7-a12a-492a-b15a-99b1205f6ccd)

### Versions

The current available LTR version of QGIS is 3.34.7. 
The latest available version of QGIS is 3.36.3. 
We are working on 3.37-Master. It will go into feature freeze on 2024-05-17 12:00:00 UTC and be released as 3.38 on 2024-06-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Icaro-Fonseca, thanks for reporting. Please provide the full QGIS version info as request in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") and please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
