### ISSUE TITLE
Unable to install any Plugins cause of error

### ISSUE THREAD

**Issue by gafzgarrr** [qgis/QGIS#57742]
### What is the bug or the crash?

Since i installed QGIS 3.28.12 parallel to an existing 3.22.12 Version on my Windows 10 Device, i am no longer able to install any Plugin from Repository or ZIP File.

Here is the Error-Log (same from Repository):

Fehler bei der Ausführung folgenden Codes:
pyplugin_installer.instance().installFromZipFile(r'C:\Users\bernst\Downloads\becagis-23.7.19.zip')
 

Traceback (most recent call last):
  File "", line 1, in 
  File "C:\PROGRA~1/QGIS32~2.12/apps/qgis-ltr/./python\pyplugin_installer\installer.py", line 664, in installFromZipFile
    loadPlugin(pluginName)
  File "C:\Users/bernst/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 122, in patched_load_plugin
    self.check_deps_and_prompt_install(additional_plugins=[packageName])
  File "C:\Users/bernst/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\a00_qpip\plugin.py", line 144, in check_deps_and_prompt_install
    if os.path.dirname(dist._path) != self.site_packages_path:
  File "C:\PROGRA~1\QGIS32~2.12\apps\Python39\lib\ntpath.py", line 223, in dirname
    return split(p)[0]
  File "C:\PROGRA~1\QGIS32~2.12\apps\Python39\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not Path

  

Python-Version:
3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)]

QGIS-Version:
3.28.12-Firenze 'Firenze', dcc633b2de

Python-Pfad:
['C:\\Users\\bernst\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\dependencies\\Lib\\site-packages', 'C:/PROGRA~1/QGIS32~2.12/apps/qgis-ltr/./python', 'C:/Users/bernst/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:/Users/bernst/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python/plugins', 'C:/PROGRA~1/QGIS32~2.12/apps/qgis-ltr/./python/plugins', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\grass\\grass83\\etc\\python', 'C:\\Users\\Default\\Documents', 'C:\\Program Files\\QGIS 3.28.12\\bin\\python39.zip', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\DLLs', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\lib', 'C:\\Program Files\\QGIS 3.28.12\\bin', 'C:\\Users\\bernst\\AppData\\Roaming\\Python\\Python39\\site-packages', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\lib\\site-packages', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\lib\\site-packages\\win32', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\lib\\site-packages\\win32\\lib', 'C:\\PROGRA~1\\QGIS32~2.12\\apps\\Python39\\lib\\site-packages\\Pythonwin', 'C:/Users/bernst/AppData/Roaming/QGIS/QGIS3\\profiles\\default/python', 'C:\\Users\\bernst\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\mmqgis/forms', 'C:\\Users\\bernst\\AppData\\Roaming\\QGIS\\QGIS3\\profiles\\default\\python\\plugins\\qfieldsync\\libqfieldsync.whl']

### Steps to reproduce the issue

Install QGIS 3.22.12.
After that install a second instance of QGIS with 3.28.12
Try to install any Plugin in any of the Versions

### Versions

3.22.12 and 3.28.12

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I already deleted both versions and only installed 3.28.12
The same issue.

**Comment by agiudiceandrea** [comment]
@gafzgarrr, QGIS 3.28 is no longer supported. The issue is due to the a00_qpip plugin. I suggest you to actually create and use a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
