### ISSUE TITLE
FileGDB with 64-bit ObjectID is not read by QGIS

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#57741]
### What is the bug or the crash?

The attached file was produced with ArcGIS PRO starting from a GeoPackage created with QGIS.

Reopening the GDB file in QGIS, some feature classes are no longer read by qgis and I accidentally discover that they have 64-bit ObjectIDs, could this be the cause?

In the GDB file that I attach, the feature class `AOI_cs_mar_Clip2` has a 64-bit ObjectID (it is not read by QGIS), `quadro_unione` has a 32-bit ObjectID and is read correctly by QGIS.

ArcGIS PRO correctly reads both 32 and 64 FCs.

[test64bit.gdb.zip](https://github.com/user-attachments/files/15801059/test64bit.gdb.zip)

### Steps to reproduce the issue

Start QGIS and load the GDB file;
some Feature Classes are empty

## OSGeo4W 64 bit 

QGIS 3.34.7 LTR Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @pigreco, it seems to me this issue is the same as already reported at https://github.com/qgis/QGIS/issues/57471.
@rouault. The issue should be fixed using GDAL 3.10.

**Comment by rouault** [comment]
yes, same as #57471
