### ISSUE TITLE
Collect geometries does not work since version 3.26

### ISSUE THREAD

**Issue by otisweb** [qgis/QGIS#57743]
### What is the bug or the crash?

I have used the same file and the same parameters with the collect geometries tool. In version 3.24, holes are generated in the polygons (Dissolve in ArcGis). In version 3.44 the polygons are grouped according to a field, but the gaps are not made.
![V324_1](https://github.com/qgis/QGIS/assets/172484451/42303bca-49ae-4a12-9d2a-b0e8255f9a82)
![V334_1](https://github.com/qgis/QGIS/assets/172484451/4b41c018-b485-4cc1-9366-23f600eafa3e)

### Steps to reproduce the issue

1. Load the shape. Establish coordinates system.
2. -> Collect geometries . 
3. Select a field.
4. Save to a file.
5. Execute

### Versions

3.34 

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@otisweb, thanks for reporting. Please provide a sample layer and exact parameters of the "Collect geometries" processing algorithm with which the issue occurs.

**Comment by otisweb** [comment]
[jarmac.zip](https://github.com/user-attachments/files/15814518/jarmac.zip)

The field to collect is cod.

**Comment by uclaros** [comment]
> In version 3.24, holes are generated in the polygons (Dissolve in ArcGis).

Can you clarify this? Neither _Collect Geometries_ not _Dissolve_ should be generating holes!

**Comment by otisweb** [comment]
In image 1, the result (JPII1) is correct. They are bushy masses and have holes. Made with version 3.24
In image 2, the result (JPII2) is incorrect. The creation of the multipart elements has not been done well and the interior holes of the polygons do not appear.

**Comment by uclaros** [comment]
> In image 1, the result (JPII1) is correct. They are bushy masses and have holes. Made with version 3.24

Your initial data _does not_ have holes. Why would you think that _Collect geometries_ should create holes that do not exist in the source data?
