### ISSUE TITLE
rasterize added to the GDAL Python interface

### ISSUE THREAD

**Issue by as18g13** [qgis/QGIS#57740]
### Feature description

Features like polygonize exist in the gdal python interface but there isnt one for rasterize as far as I can find. Would be good to add one as the polygonize function is written well and useful

**Comment by agiudiceandrea** [comment]
@as18g13, may you please give more details? There are already 3 "Rasterize *" processing algorithms that use the gdal_rasterize program:
- [Rasterize (vector to raster)](https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#rasterize-vector-to-raster)
- [Rasterize (overwrite with attribute)](https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#rasterize-overwrite-with-attribute)
- [Rasterize (overwrite with fixed value)](https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/vectorconversion.html#rasterize-overwrite-with-fixed-value)

**Comment by as18g13** [comment]
@agiudiceandrea thanks. I mean one that is a standalone script like the gdal_polygonize.py which is located in the C:\Program Files\QGIS 3.34.0\apps\Python39\Scripts file path of the QGIS distribution.

**Comment by agiudiceandrea** [comment]
@as18g13, thanks for reporting and clarification.
gdal_rasterize is provided by the GDAL/OGR library as an binary executable compiled program, not as a Python script utility like it is for gdal_polygonize. You need to submit the feature request to the GDAL/OGR GitHub repository https://github.com/OSGeo/gdal/issues.
