### ISSUE TITLE
Guia Vetor não expande as funções

### ISSUE THREAD

**Issue by LailaTvrs787** [qgis/QGIS#57753]
### What is the bug or the crash?

A Guia vetor não funciona e nem expande para as ferramentas, ao clicar na guia nada acontece. 

### Steps to reproduce the issue

https://github.com/qgis/QGIS/assets/172544083/0c05cfa5-5b96-4328-86f6-2db9078b7ba1

### Versions

Versão do QGIS
3.34.7-Prizren
Código da versão do QGIS
6f7d735c
Versão Qt
5.15.13
Versão do Python
3.12.3
Versão GDAL/OGR
3.9.0
Versão PROJ
9.4.0
Versão da base de dados do registro EPSG
v11.004 (2024-02-24)
Versão GEOS
3.12.1-CAPI-1.18.1
Versão SQLite
3.45.1
Versão PDAL
2.6.3
Versão cliente PostgreSQL
16.2
Versão SpatiaLite
5.1.0
Versão QWT
6.2.0
Versão QScintilla2
2.14.1
Versão OS
Windows 11 Version 2009

Plugins Python ativos
FreehandRasterGeoreferencer
0.8.3
mapbiomascollection
1.4
quick_map_services
0.19.34
SgmExpressionFunctions
3.0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@LailaTvrs787, you need to activate the "Processing" core plugin https://docs.qgis.org/3.34/en/docs/user_manual/plugins/plugins.html#core-and-external-plugins
