### ISSUE TITLE
Deleting raster from geopackage does nothing

### ISSUE THREAD

**Issue by mastrolube** [qgis/QGIS#57751]
### What is the bug or the crash?

I have that gpkg with a raster inside. 
[dummy aree allagabili.zip](https://github.com/user-attachments/files/15806054/dummy.aree.allagabili.zip)
I'm not able to delete it / rename from DBManager.
![immagine](https://github.com/qgis/QGIS/assets/52335835/73f7ea3d-b3d4-44d9-b4e4-f6fe54d9b27f)
![immagine](https://github.com/qgis/QGIS/assets/52335835/0ffe1504-5781-4340-ac83-52c4c6029045)

No error, but nothing happens.

If you open the file with DB Browser, all the data is still inside it.
![immagine](https://github.com/qgis/QGIS/assets/52335835/8d81f6de-1b58-41d1-a4f2-cbf1ab72b2fa)

Thanks!

### Steps to reproduce the issue

1. connect the file in the DB Manager
2. try to delete / rename the raster

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.7-Prizren | QGIS code revision | 6f7d735c
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
  |   |   |  
Active Python plugins
AutoLayoutTool | 1.1
changeDataSource | 3.1
data_exporter | 0.1
firstaid | 3.1.1
FreehandRasterGeoreferencer | 0.8.3
GroupStats | 2.2.7
Group_and_Sort_Layers | 1.2
group_transparency | 0.2
layout_loader | 1.1
layout_panel-main | 0.3
MultipleLayerSelection | 2.0.1
OSMDownloader | 1.0.3
profiletool | 4.2.6
ProjectPackager | 0.7.2
QGISSortAndNumber-master | 1.0
QPackage | 1.5
QuickOSM | 2.2.3
quick_map_services | 0.19.34
quick_shape_update | 0.1
RimoPrinting_QGIS3 | 1.0
searchlayers | 3.0.16
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mastrolube, thanks for reporting. It looks like also the Rename functionality doesn't work for a raster layer in a GeoPackage.
