### ISSUE TITLE
Pluggin Issue

### ISSUE THREAD

**Issue by Sm665** [qgis/QGIS#57778]
### What is the bug or the crash?

QGIS Official Plugin Repository is unavailable in version- 2.8.9
 URL -    http://plugins.qgis.org/plugins/plugins.xml

### Steps to reproduce the issue

![QGIS](https://github.com/qgis/QGIS/assets/173033619/1d3b7249-55a9-4e77-a8bd-02b7613f2755)

### Versions

2.8.9

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Qgis 2.x is not supported

**Comment by Sm665** [comment]
If 2. x is not supportable then how can I run MOLUSCE pluggin'
