### ISSUE TITLE
report .SHP no carga

### ISSUE THREAD

**Issue by smblnts21** [qgis/QGIS#57771]
### What is the bug or the crash?

Warning: QString::arg: Argument missing: Shapefiles, *.shp *.SHP

### Steps to reproduce the issue

Warning: QString::arg: Argument missing: Shapefiles, *.shp *.SHP

### Versions

The current released version of QGIS is 3.36.3. 
We are working on 3.37-Master. It will go into feature freeze on 2024-05-17 12:00:00 UTC and be released as 3.38 on 2024-06-21 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No carga archivos .shp que estén en una de las carpetas de favoritos

**Comment by agiudiceandrea** [comment]
@smblnts21, thanks for reporting.
Please provide:
- the QGIS full version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") as requested in the issue report form
- the files of the ESRI Shapefile layer with which the issue occurs and the exact steps to reproduce the behavior as requested in the issue report form

**Comment by gioman** [comment]
@smblnts21 can you please edit the title and make in in english?
