### ISSUE TITLE
Missing help button in Layer Diagram Properties dialog

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS#57790]
### What is the bug or the crash?

When opening the `Layer Diagram Properties` dialog from the `Label toolbar`, it is displayed without a `Help` button.

![image](https://github.com/qgis/QGIS/assets/652785/f6dfe7ee-9b3b-4f00-b3e8-6f46f4671ca3)

It would be nice and expected to have it there, just as `Layer Properties --> Diagrams` does:

![image](https://github.com/qgis/QGIS/assets/652785/35fdea6e-7b40-4759-ab05-1e85537ade34)

### Steps to reproduce the issue

Go to the `Label toolbar` and click on `Layer Diagram Options` button.
See the open dialog.

### Versions

QGIS master 3.37.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Proposed fix: https://github.com/qgis/QGIS/pull/57794.
