### ISSUE TITLE
the Saga version 7.8.2 is not officially supported

### ISSUE THREAD

**Issue by DevanshWFT11** [qgis/QGIS#57814]
### What is the bug or the crash?

when you try to use fill sink (Wang & Liu) it shows the following the Saga version 7.8.2 is not officially supported. What is the issue?
same is shown when trying to use Strahler Order.

### Steps to reproduce the issue

QGIS version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.2
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 1c17a7)
SAGA version 7.8.2 is not officially supported - algorithms may encounter issues
Algorithm started at: 2024-06-20T15:21:49
Algorithm 'Fill Sinks (Wang & Liu)' starting…
Input parameters:
{ 'ELEV' : 'C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif', 'FDIR' : 'TEMPORARY_OUTPUT', 'FILLED' : 'TEMPORARY_OUTPUT', 'MINSLOPE' : 0.1, 'WSHED' : 'TEMPORARY_OUTPUT' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd" -FILES "C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif"
ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd" -MINSLOPE 0.1 -FILLED "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/d69dac245bf0477ea5cad328747a0be5/FILLED.sdat" -FDIR "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/c3eb0f2d42eb4c089014320675ac1217/FDIR.sdat" -WSHED "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/f0004f2ea3bb4850b1aa822bea360fae/WSHED.sdat"

C:\Users\WFT\Documents>set SAGA=C:/PROGRA~1/QGIS32~1.2/apps\saga

C:\Users\WFT\Documents>set SAGA_MLB=C:/PROGRA~1/QGIS32~1.2/apps\saga\modules

C:\Users\WFT\Documents>PATH=C:\PROGRA~1\QGIS32~1.2\apps\qgis\bin;C:\PROGRA~1\QGIS32~1.2\apps\grass\grass78\lib;C:\PROGRA~1\QGIS32~1.2\apps\grass\grass78\bin;C:\PROGRA~1\QGIS32~1.2\apps\qt5\bin;C:\PROGRA~1\QGIS32~1.2\apps\Python39\Scripts;C:\PROGRA~1\QGIS32~1.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:/PROGRA~1/QGIS32~1.2/apps\saga;C:/PROGRA~1/QGIS32~1.2/apps\saga\modules

C:\Users\WFT\Documents>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd" -FILES "C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

87 loaded tool libraries (754 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *

*) tool chain libraries

Error: select a library
type -h or --help for further information

C:\Users\WFT\Documents>call saga_cmd ta_preprocessor "Fill Sinks (Wang & Liu)" -ELEV "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd" -MINSLOPE 0.1 -FILLED "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/d69dac245bf0477ea5cad328747a0be5/FILLED.sdat" -FDIR "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/c3eb0f2d42eb4c089014320675ac1217/FDIR.sdat" -WSHED "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/f0004f2ea3bb4850b1aa822bea360fae/WSHED.sdat"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS32~1.2\apps\saga\tools\
library name: ta_preprocessor
library : ta_preprocessor
tool : Fill Sinks (Wang & Liu)
identifier : 4
author : Copyrights (c) 2007 by Volker Wichmann
processors : 4 [4]
____________________________

Loading grid: C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd...
failed
Error: input file [C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/b5e6776f4d0647f4a643d63af316c107/n21e0701arcv3.sgrd]
Error: DEM

Usage: saga_cmd ta_preprocessor 4 [-ELEV <str>] [-FILLED <str>] [-FDIR <str>] [-WSHED <str>] [-MINSLOPE <double>]
-ELEV:<str> DEM
Grid, input
-FILLED:<str> Filled DEM
Grid, output
-FDIR:<str> Flow Directions
Grid, output
-WSHED:<str> Watershed Basins
Grid, output
-MINSLOPE:<double> Minimum Slope [Degree]
Floating point
Minimum: 0.000000
Default: 0.100000

C:\Users\WFT\Documents>exit
Execution completed in 20.03 seconds
Results:
{'FDIR': 'C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/c3eb0f2d42eb4c089014320675ac1217/FDIR.sdat',
'FILLED': 'C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/d69dac245bf0477ea5cad328747a0be5/FILLED.sdat',
'WSHED': 'C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/f0004f2ea3bb4850b1aa822bea360fae/WSHED.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/d69dac245bf0477ea5cad328747a0be5/FILLED.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

QGIS version: 3.24.2-Tisler
QGIS code revision: 13c1a028
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.4.2
GEOS version: 3.10.2-CAPI-1.16.0
PROJ version: Rel. 9.0.0, March 1st, 2022
PDAL version: 2.3.0 (git-version: 1c17a7)
SAGA version 7.8.2 is not officially supported - algorithms may encounter issues
Algorithm started at: 2024-06-20T15:26:59
Algorithm 'Strahler Order' starting…
Input parameters:
{ 'DEM' : 'C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif', 'STRAHLER' : 'TEMPORARY_OUTPUT' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd" -FILES "C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif"
ta_channels "Strahler Order" -DEM "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd" -STRAHLER "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/0644a5ba66e141b6971ee354d7aa0dae/STRAHLER.sdat"

C:\Users\WFT\Documents>set SAGA=C:/PROGRA~1/QGIS32~1.2/apps\saga

C:\Users\WFT\Documents>set SAGA_MLB=C:/PROGRA~1/QGIS32~1.2/apps\saga\modules

C:\Users\WFT\Documents>PATH=C:\PROGRA~1\QGIS32~1.2\apps\qgis\bin;C:\PROGRA~1\QGIS32~1.2\apps\grass\grass78\lib;C:\PROGRA~1\QGIS32~1.2\apps\grass\grass78\bin;C:\PROGRA~1\QGIS32~1.2\apps\qt5\bin;C:\PROGRA~1\QGIS32~1.2\apps\Python39\Scripts;C:\PROGRA~1\QGIS32~1.2\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\system32\WBem;C:/PROGRA~1/QGIS32~1.2/apps\saga;C:/PROGRA~1/QGIS32~1.2/apps\saga\modules

C:\Users\WFT\Documents>call saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd" -FILES "C:/Users/WFT/Desktop/n21_e070_1arc_v3.tif"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

87 loaded tool libraries (754 tools):
- tin_viewer
- tin_tools
- table_tools
- table_calculus
- ta_slope_stability
- ta_profiles
- ta_preprocessor
- ta_morphometry
- ta_lighting
- ta_hydrology
- ta_compound
- ta_cliffmetrics
- ta_channels
- statistics_regression
- statistics_points
- statistics_kriging
- statistics_grid
- sim_rivflow
- sim_qm_of_esp
- sim_landscape_evolution
- sim_ihacres
- sim_hydrology
- sim_geomorphology
- sim_fire_spreading
- sim_erosion
- sim_ecosystems_hugget
- sim_cellular_automata
- sim_air_flow
- shapes_transect
- shapes_tools
- shapes_polygons
- shapes_points
- shapes_lines
- shapes_grid
- pointcloud_viewer
- pointcloud_tools
- pj_geotrans
- pj_georeference
- io_webservices
- io_virtual
- io_table
- io_shapes_dxf
- io_shapes
- io_pdal
- io_grid_image
- io_grid
- io_gps
- io_esri_e00
- imagery_tools
- imagery_svm
- imagery_segmentation
- imagery_photogrammetry
- imagery_maxent
- imagery_isocluster
- imagery_classification
- grids_tools
- grid_visualisation
- grid_tools
- grid_spline
- grid_gridding
- grid_filter
- grid_calculus_bsl
- grid_calculus
- grid_analysis
- garden_webservices
- garden_learn_to_program
- garden_games
- garden_fractals
- garden_3d_viewer
- docs_pdf
- docs_html
- dev_tools
- db_pgsql
- db_odbc
- contrib_perego
- climate_tools
- tta_tools *
- toolchains *
- terrain_analysis *
- imagery *
- group_files *
- grid_filter *
- gc_tools *
- climate_tools *
- Shapes Tools *
- Polygon Tools *
- Grid Tools *

*) tool chain libraries

Error: select a library
type -h or --help for further information

C:\Users\WFT\Documents>call saga_cmd ta_channels "Strahler Order" -DEM "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd" -STRAHLER "C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/0644a5ba66e141b6971ee354d7aa0dae/STRAHLER.sdat"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 7.8.2 (64 bit)

____________________________
library path: C:\PROGRA~1\QGIS32~1.2\apps\saga\tools\
library name: ta_channels
library : ta_channels
tool : Strahler Order
identifier : 6
author : Victor Olaya, Volker Wichmann (c) 2004-17
processors : 4 [4]
____________________________

Loading grid: C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd...
failed
Error: input file [C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/ac56f163ee94442cae71eb1b3f64c2e8/n21e0701arcv3.sgrd]
Error: Elevation

Usage: saga_cmd ta_channels 6 [-DEM <str>] [-STRAHLER <str>]
-DEM:<str> Elevation
Grid, input
-STRAHLER:<str> Strahler Order
Grid, output

C:\Users\WFT\Documents>exit
Execution completed in 12.32 seconds
Results:
{'STRAHLER': 'C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/0644a5ba66e141b6971ee354d7aa0dae/STRAHLER.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/WFT/AppData/Local/Temp/processing_kKDyjK/0644a5ba66e141b6971ee354d7aa0dae/STRAHLER.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Versions

QGIS version
3.24.2-Tisler
QGIS code revision
13c1a028
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.4.2
PROJ version
9.0.0
EPSG Registry database version
v10.054 (2022-02-13)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.3
QScintilla2 version
2.11.5
OS version
Windows 10 Version 2009

Active Python plugins
contour
2.0.10
HCMGIS
24.1.12
nominatim
1.4.5
QuickOSM
2.2.3
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Qgis 3.24 is no longer supported, and support for saga was moved to a 3rd party plugin.
