### ISSUE TITLE
UNIQUE constraints in GeoPackage not considered

### ISSUE THREAD

**Issue by signedav** [qgis/QGIS#57823]
### What is the bug or the crash?

While QGIS considers not null constraints in the attribute form settings, it does not for unique constraints. 

### Steps to reproduce the issue

1. I have this table in the attached GeoPackage:
    ```
   CREATE TABLE "test" (
	"f1uniquenotnull"	INTEGER UNIQUE NOT NULL,
	"f2unique"	INTEGER,
	"f3notnull"	INTEGER NOT NULL
      ,CONSTRAINT f2unique_key UNIQUE (f2unique)
    )
    ```
2. When I open it in QGIS (via Browser) it recognizes the NOT NULL constraint but not the UNIQUE constraints:
    ![image](https://github.com/qgis/QGIS/assets/28384354/19734ae3-92d5-4370-bad9-c6758f7c5ebb)
3. But I cannot store duplicate values in those fields (as expected):
    > Layer test : OGR error creating feature -10: failed to execute insert : UNIQUE constraint failed: test.f2unique

In the Code it looks like this is implemented: 
https://github.com/qgis/QGIS/blob/master/src/core/providers/ogr/qgsogrprovider.cpp#L866-L874

But while it recognizes the NOT NULL with `OGR_Fld_IsNullable` the unique constraint is not detected with `OGR_Fld_IsUnique`.

### Versions

QGIS version | 3.37.0-Master | QGIS code revision | 1f40e530bc3
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.9.0dev-365401613a
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 16.2 (Ubuntu 16.2-1.pgdg22.04+1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS

As well as:

QGIS version | 3.34.5-Prizren | QGIS code revision | 4b308492cd5
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.11 (Ubuntu 14.11-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by signedav** [comment]
@rouault Do you know about this problem? Did it work once?

**Comment by elpaso** [comment]
@signedav if GDAL doesn't recognize the constraint I think this is GDAL issue and not a QGIS one.

**Comment by rouault** [comment]
@signedav As far as I can see, GDAL only recognizes constraints when the column definition is "column_name type UNIQUE [other_constraint]", or if there's a "CREATE UNIQUE INDEX name on table_name(column_name)". But not ", CONSTRAINT constraint_name UNIQUE (column_name)" at the end of the CREATE TABLE statement.  SQLite3 doesn't offer a proper API to find unique constraints, so one has to painfully parse the DDL of CREATE TABLE and CREATE UNIQUE.

**Comment by signedav** [comment]
But the `f1uniquenotnull` in the format `column_name type UNIQUE [other_constraint]` is working neither. The ` UNIQUE INDEX` way I'll try...

**Comment by rouault** [comment]
> But the `f1uniquenotnull` in the format `column_name type UNIQUE [other_constraint]` is working neither.

it is working for me:
```
$ ogrinfo test.gpkg test
[...]
f1uniquenotnull: Integer64 (0.0) UNIQUE NOT NULL
f2unique: Integer64 (0.0)
f3notnull: Integer64 (0.0) NOT NULL
```

And I've just submitted a GDAL fix in https://github.com/OSGeo/gdal/pull/10262 to recognize ', CONSTRAINT name UNIQUE (column_name)' at the end of CREATE TABLE. Now I get:
```
f1uniquenotnull: Integer64 (0.0) UNIQUE NOT NULL
f2unique: Integer64 (0.0) UNIQUE
f3notnull: Integer64 (0.0) NOT NULL
```

**Comment by signedav** [comment]
> it is working for me:
Sorry, you are right. Not sure what I did wrong last time. Did another test:

```
CREATE TABLE "test2" (
"f1uniquenotnull"	INTEGER UNIQUE NOT NULL,
"f2unique"	INTEGER,
"f3notnull"	INTEGER NOT NULL
  ,CONSTRAINT f2unique_key UNIQUE (f2unique)
);

CREATE UNIQUE INDEX f3notnull_unique on test2(f3notnull)
```

and yes. f1 and f3 are concerned. f2 not yet, but apparently with your fix it will be solved. Thanks a lot.
