### ISSUE TITLE
The raster calculator produces non-compliant outputs

### ISSUE THREAD

**Issue by alexCCI** [qgis/QGIS#57820]
### What is the bug or the crash?

The raster calculator produces non-compliant outputs. Initial raster splits into two.
The interface is no longer adaptable.
![3](https://github.com/qgis/QGIS/assets/78025843/9f4152e7-8363-4887-89be-cf7bf88405dd)
![2](https://github.com/qgis/QGIS/assets/78025843/1f325bfd-88b2-41b3-8610-d1df660d9d9b)
![1](https://github.com/qgis/QGIS/assets/78025843/dc8807e9-0501-445e-a658-d734520486a3)

### Steps to reproduce the issue

1. Choose a multi-band raster
2. Perform a calculation using multiple bands
3. It is important to save it as a TIFF (the on-the-fly version works correctly)!!!

### Versions

Version de QGIS
3.34.7-Prizren
Révision du code
6f7d735c
Version de Qt
5.15.13
Version de Python
3.12.4
Version de GDAL/OGR
3.9.0
Version de Proj
9.4.0
Version de la base de données du registre EPSG
v11.004 (2024-02-24)
Version de GEOS
3.12.2-CAPI-1.18.2
Version de SQLite
3.45.1
Version de PDAL
2.6.3
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.2.0
Version de QScintilla2
2.14.1
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
db-style-manager
0.8
pcraster_tools
0.3.0
pluginbuilder3
3.2.1
plugin_reloader
0.9.4
processing_saga_nextgen
1.0.0
QuickOSM
2.2.3
quick_map_services
0.19.34
raster_tracer
0.3.3
slyr
7.4.1
SRTM-Downloader
3.2.2
StreetView
3.2
Topo
1.3.8
wbt_for_qgis
1.0.9
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@alexCCI, thanks for reporting. It would be useful if you provided a minimal set o layers and all the parameter used in order to replicate the issue.

**Comment by alexCCI** [comment]
> @alexCCI, thanks for reporting. It would be useful if you provided a minimal set o layers and all the parameter used in order to replicate the issue.

I made a clip test to reduce the raster size [](https://we.tl/t-w42is3nOYw) 
You can try any formula with some bands, for example "clip@1" + "clip@2" + "clip@3"

**Comment by agiudiceandrea** [comment]
@alexCCI, I cannot replicate the issue using QGIS 3.34.7 on Windows 10 and the provided layer [clip.zip](https://github.com/user-attachments/files/15938408/clip.zip) and expression in the Raster Calculator.

https://github.com/qgis/QGIS/assets/16253859/c0790eeb-4b6d-4c9d-af95-1ab5838cbc02

Does the issue actually occur using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)? If it does, please provide more detailed steps to replicate the issue.

**Comment by alexCCI** [comment]
> @alexCCI, I cannot replicate the issue using QGIS 3.34.7 on Windows 10 and the provided layer [clip.zip](https://github.com/user-attachments/files/15938408/clip.zip) and expression in the Raster Calculator.
> 
>  Video_2024-06-22_123123.mp4 
> Does the issue actually occur using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)? If it does, please provide more detailed steps to replicate the issue.

Thank you for your response!
I thought I had taken a test under a new profile, but after another attempt, I received the result without error.
My apologies for the inconvenience.
Do you have any idea how I could fix the problem with my current profile?

**Comment by agiudiceandrea** [comment]
> Do you have any idea how I could fix the problem with my current profile?

You can try to uninstall or disable the third-party external plugin one by one to check if one of them is the cause of the issue.

**Comment by agiudiceandrea** [comment]
@alexCCI, the issue may have been due to the fact the you have possibly enabled the "OpenCL acceleration" (in Settings->Options->Acceleration).
See https://github.com/qgis/QGIS/issues/60077 and https://github.com/qgis/QGIS/pull/60339.
