### ISSUE TITLE
"bad $-escape" error when building QGIS 3.38.0

### ISSUE THREAD

**Issue by imincik** [qgis/QGIS#57831]
### What is the bug or the crash?

When building QGIS for Nixpkgs, I get a following error message:

```
-- Configuring done (10.5s)
-- Generating done (1.9s)
CMake Error:
  Running

   '/nix/store/v3wh3z7j8dxlb3306ackf25h8hw7lzg2-ninja-1.12.1/bin/ninja' '-C' '/home/imincik/Projects/nix/nixpkgs/code/dev/source/build' '-t' 'recompact'

  failed with:

   ninja: error: build.ninja:37990: bad $-escape (literal $ must be written as $$)
```

### Steps to reproduce the issue

-

### Versions

QGIS 3.38.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Line 37990 of `build.ninja` contains following:

```
  DEFINES = -DPROTOBUF_USE_DLLS -DQT_3DCORE_LIB -DQT_3DEXTRAS_LIB -DQT_3DINPUT_LIB -DQT_3DLOGIC_LIB -DQT_3DRENDER_LIB -DQT_CONCURRENT_LIB -DQT_CORE_LIB -DQT_DBUS_LIB -DQT_DEPRECATED_WARNINGS -DQT_DISABLE_DEPRECATED_BEFORE=0x050800 -DQT_GUI_LIB -DQT_MULTIMEDIAWIDGETS_LIB -DQT_MULTIMEDIA_LIB -DQT_NETWORK_LIB -DQT_NO_CAST_TO_ASCII -DQT_NO_DEBUG -DQT_PLUGINS_DIR=\"/build/qtbase-0e1ff2f/$(out)/$(qtPluginPrefix)\" -DQT_POSITIONING_LIB -DQT_PRINTSUPPORT_LIB -DQT_QMLMODELS_LIB -DQT_QML_LIB -DQT_QUICKWIDGETS_LIB -DQT_QUICK_LIB -DQT_SERIALPORT_LIB -DQT_SQL_LIB -DQT_SVG_LIB -DQT_UITOOLS_LIB -DQT_USE_QSTRINGBUILDER -DQT_WIDGETS_LIB -DQT_XML_LIB -DQWT_POLAR_VERSION=0x060200 -DSIP_VERSION=0x060803 -DTEST_DATA_DIR=\"/home/imincik/Projects/nix/nixpkgs/code/dev/source/tests/testdata\" -DWITH_BINDINGS -DWITH_QWTPOLAR

```

This problem occurs only when building with ninja, doesn't happen when building with make.

**Comment by rouault** [comment]
@imincik Isn't there rather an issue with your QT environment ?

The QT_PLUGINS_DIR variable is initialized by https://github.com/qgis/QGIS/blob/087368956a2fe421db1174a5cafcea5aa6fcb91a/CMakeLists.txt#L552

so it seems that "qmake -query QT_INSTALL_PLUGINS" would return this unexpanded "/build/qtbase-0e1ff2f/$(out)/$(qtPluginPrefix)" value for you, which doesn't seem right

You could likely workaround the issue by specifying -DQT_INSTALL_PLUGINS=/some/real/path but you should likely fix your QT installation first

**Comment by imincik** [comment]
> @imincik Isn't there rather an issue with your QT environment ?
> 
> The QT_PLUGINS_DIR variable is initialized by
> 
> https://github.com/qgis/QGIS/blob/087368956a2fe421db1174a5cafcea5aa6fcb91a/CMakeLists.txt#L552
> 
> so it seems that "qmake -query QT_INSTALL_PLUGINS" would return this unexpanded "/build/qtbase-0e1ff2f/$(out)/$(qtPluginPrefix)" value for you, which doesn't seem right
> 
> You could likely workaround the issue by specifying -DQT_INSTALL_PLUGINS=/some/real/path but you should likely fix your QT installation first

Thank you very much for quick answer @rouault . It looks like you might be right and the issue will be most likely in Nixpkgs build environment. I am closing this issue.
