### ISSUE TITLE
Vector Menu does not function

### ISSUE THREAD

**Issue by Dionde001** [qgis/QGIS#57850]
### What is the bug or the crash?

The Vector in the Upper menu does not open. When I click, other options does not dropped down 

### Steps to reproduce the issue

Go to 'Vector' then
Click on to drop down

### Versions

QGIS version
3.34.6-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Could you check that "Processing" extension is activated in Extensions ?
I see you didn't check "I tried with a new QGIS profile" in issue form so if issue persists, pleaser retry with a new profile.
