### ISSUE TITLE
Cant change folders in profile

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#57857]
### What is the bug or the crash?

Cant change folders for processing/scripts/output in Profile settings.

I was able to go into "QGIS3.ini" file in the profile map and change them.

### Steps to reproduce the issue

Copy profile to another computer or user.
Klick settings and try to change the folders.
Press okay.
Se error messages of missing folders pointing to the old folder you dont have.

Look into settings again and the path's has not changed. 

### Versions

3.34.1-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@APOS80, thanks for reporting. It seems to me the issue doesn't occur using QGIS 3.34.8 on Windows and changing the paths in Settings-> Options -> Processing -> General / Output folder - Models / Models folder - Scripts / Scripts folder(s)

Please try if the issue doesn't occur using the latest currently supported QGIS version.

**Comment by agiudiceandrea** [comment]
@APOS80, thanks for reporting. It seems to me the issue doesn't occur using QGIS 3.34.8 on Windows and changing the paths in Settings-> Options -> Processing -> General / Output folder - Models / Models folder - Scripts / Scripts folder(s)

Please try if the issue still occurs using the latest currently supported QGIS version.
