### ISSUE TITLE
import fiona fails in 3.36.3

### ISSUE THREAD

**Issue by ChrisWGeorge** [qgis/QGIS#57878]
### What is the bug or the crash?

import fiona in the Python console produces
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\code.py", line 63, in runsource
    code = self.compile(source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\codeop.py", line 161, in __call__
    return _maybe_compile(self.compiler, source, filename, symbol)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\codeop.py", line 73, in _maybe_compile
    return compiler(source, filename, symbol, incomplete_input=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\codeop.py", line 126, in __call__
    codeob = compile(source, filename, symbol, flags, True)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<input>", line 1
    iport fiona
          ^^^^^
SyntaxError: invalid syntax
import fiona
Traceback (most recent call last):
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\code.py", line 90, in runcode
    exec(code, self.locals)
  File "<input>", line 1, in <module>
  File "C:\PROGRA~1/QGIS 3.36.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\PROGRA~1\QGIS 3.36.3\apps\Python312\Lib\site-packages\fiona\__init__.py", line 41, in <module>
    from fiona._env import (
  File "C:\PROGRA~1/QGIS 3.36.3/apps/qgis/./python\qgis\utils.py", line 923, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _env: The specified module could not be found.

### Steps to reproduce the issue

1.  Open Pytyhon console
2. import fiona

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df96554
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
plugin_reloader | 0.9.4
QSWATPlus3_12 | 2.5.3
remotedebug | 0.4.3
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.36.3-Maidenhead
QGIS code revision
[2df96554](https://github.com/qgis/QGIS/commit/2df96554)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
plugin_reloader
0.9.4
QSWATPlus3_12
2.5.3
remotedebug
0.4.3
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No problem with LTR 3.34.6

**Comment by ChrisWGeorge** [comment]
Just discovered the bug is in LTR 3.34.7 as well

**Comment by agiudiceandrea** [comment]
@ChrisWGeorge, it seems to me there is no issue using QGIS 3.38.0 or QGIS 3.34.8 on Windows (you can find the stand-alone all-in-one .msi installers in https://download.qgis.org/downloads/?C=M;O=D).

**Comment by Djedouas** [comment]
I confirm the issue on LTR 3.34.7 on Windows.

I confirm that the issue is gone and that everything is fine on LTR 3.34.8 and 3.38.0 on Windows.
