### ISSUE TITLE
Deactivate option to view attribute table based on visible features for non spatial layers

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#57889]
### Feature description

* Load a non spatial layer in QGIS
* Navigate to the Attribute Toolbar
* Select `Open Attribute Table (Visible Features)`

The attribute table opens up with all the features in the table. 
We should deactivate the visible options since the table doesn't have any geometry

**Comment by agiudiceandrea** [comment]
It think this is a bug.

**Comment by agiudiceandrea** [comment]
@NyakudyaA, may you test the windows build available at https://github.com/qgis/QGIS/pull/57897#issuecomment-2191948003?

**Comment by NyakudyaA** [comment]
> @NyakudyaA, may you test the windows build available at [#57897 (comment)](https://github.com/qgis/QGIS/pull/57897#issuecomment-2191948003)?

It works, thanks for the quick fix

**Comment by NyakudyaA** [comment]
@agiudiceandrea There are other issues related to non-spatial tables that need to be fixed, I will open a separate issue
