### ISSUE TITLE
Elevation profile PDF export

### ISSUE THREAD

**Issue by zsiki** [qgis/QGIS#57880]
### What is the bug or the crash?

Exporting any elevation profile to PDF there is a scaling problem in the created PDF. Only a very small part of the upper left corner of the profile is visible in the exported PDF. Export the profile as image is correct using the same chart ranges as in PDF export.
I suppose it is a scaling problem.

### Steps to reproduce the issue

1. Open an elevation raster/DEM
2. Open the elevation profile panel
3. Capture a line on the DEM
4. Click on Export PDF tool
5. Accept default chart ranges ans save
6. Open the exported PDF to see the issue.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333b10
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.4 LTS
  |   |   |  
Active Python plugins
ClipMultipleLayers | 3.2.0
quick_map_services | 0.19.34
cesium_ion | v1.0.2
fuzzy_join | 0.1
StreetView | 3.2
thematics | 0.6
QuickOSM | 2.2.3
processing_saga_nextgen | 1.0.0
arearatio | 0.2
configurable_search | 0.5
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.34.8-Prizren
QGIS code revision
[91642333b10](https://github.com/qgis/QGIS/commit/91642333b10)
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.12 (Ubuntu 14.12-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.4 LTS

Active Python plugins
ClipMultipleLayers
3.2.0
quick_map_services
0.19.34
cesium_ion
v1.0.2
fuzzy_join
0.1
StreetView
3.2
thematics
0.6
QuickOSM
2.2.3
processing_saga_nextgen
1.0.0
arearatio
0.2
configurable_search
0.5
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Kasmhyr** [comment]
Hello, I’m totally new to GitHub and encountered the same problem in QGIS when importing an elevation profile from a PDF. Could you please teach me how to implement the solution provided in this post in my QGIS?

**Comment by agiudiceandrea** [comment]
@Kasmhyr, this isse report is about **exporting** an elevation profile to PDF using the Elevation Profile panel.
Please create a new issue report providing all the requested detailed info.

**Comment by Kasmhyr** [comment]
@agiudiceandrea 
Ohh, sorry.

**Comment by zsiki** [comment]
@nyalldawson your correction does not work for me in QGIS version 3.34.9 and 3.34.10
![image](https://github.com/user-attachments/assets/9764f868-9e97-4f87-b8fb-43364569c516)

**Comment by zsiki** [comment]
A better picture:
![image](https://github.com/user-attachments/assets/8564f417-340e-4193-8342-7124407abcd7)

**Comment by agiudiceandrea** [comment]
@zsiki unfortunately the fix is currently only available in the latest QGIS 3.38.
@nyalldawson the automatic backport to 3.34 failed.

**Comment by zsiki** [comment]
Thanks, a reason to upgrade...
