### ISSUE TITLE
QGIS SSL certificates Expired

### ISSUE THREAD

**Issue by Angus-Fiona** [qgis/QGIS#57898]
### What is the bug or the crash?

Having issues connecting the WMS servers, where the error is 'Failed to Parse Capabilities'. Upon opening QGIS, there is _sometimes_  an error popping up saying that it cant get the Local Issuer certificate. 
![image](https://github.com/qgis/QGIS/assets/150059144/acfc24fb-c10e-4200-884d-61e8dfc67128)

A quick look as the SSL cert manager in QGIS reveals: 
![image](https://github.com/qgis/QGIS/assets/150059144/854f6a84-c519-425d-84b7-d33d18965c2c)

Now, the person who handled this before me has set a lot of these errors to default ignore, which is whatever, but as you can see these certificates expired up to 6 years ago, and im not sure why we are only having problems now. 

### Steps to reproduce the issue

Local issuer certificate is not easily reproduced, as it just comes and goes as it pleases. 

The issues with connection to WMS' is persistent 

### Versions

QGIS version
3.28.10-Firenze
QGIS code revision
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2012 Version 6.2 (Build 9200)

Active Python plugins
Discovery
2.5.7
pg_metadata
1.2.1
qfieldsync
v4.2.0
QGISSortAndNumber-master
1.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

QGIS version
3.28.10-Firenze
QGIS code revision
e2edb9c468
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.7.1
PROJ version
9.2.1
EPSG Registry database version
v10.088 (2023-05-13)
GEOS version
3.12.0-CAPI-1.18.0
SQLite version
3.41.1
PDAL version
2.5.5
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows Server 2012 Version 6.2 (Build 9200)

Active Python plugins
Discovery
2.5.7
pg_metadata
1.2.1
qfieldsync
v4.2.0
QGISSortAndNumber-master
1.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

My windows version is so old, hence the older version of QGIS but......

**Comment by agiudiceandrea** [comment]
@Angus-Fiona, thanks for reporting. Anyway, a you are using a no longer supported QGIS version. Please try if the issue still occur using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and / or using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).

If the issue still occur also using a a currently supported QGIS version and / or using a new QGIS user profile, please file separate issue reports for different issues and provide the WMS URL and exact steps to replicate the issue.
