### ISSUE TITLE
problem whit vectorials procces

### ISSUE THREAD

**Issue by Viccarrot03** [qgis/QGIS#57900]
### What is the bug or the crash?

_The algorithm "native:intersection" is no longer available. (Perhaps a plugin was uninstalled?)_ AND  _The algorithm "gdal:contour" is no longer available. (Perhaps a plugin was uninstalled?)_. **I reinstall Qgis already** and the problem is still there.

### Steps to reproduce the issue

Go to Vectorial/ Tools of geoproces/ Intersection. See error

### Versions

QGIS version
3.36.3-Maidenhead
QGIS code revision
2df96554
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
db_manager
0.1.20
quick_map_services
0.19.34
SemiAutomaticClassificationPlugin
8.2.2
SpreadsheetLayers
2.1.2
mmqgis
2021.9.10

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Viccarrot03, thanks for reporting. The issue doesn't occur on my Windows 10 system. Have you actually tried if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)? If not, please try if the issue occurs also using a new QGIS user profile.
If it does, please:
- specify if `native:intersection` and `gdal:contour` are the only missing algorithms in your system or not
- please execute the following command in the Python console:
```python
print({provider.id():len(provider.algorithms()) for provider in QgsApplication.processingRegistry().providers()})
```
  The command should print the number of available algorithms for each processing provider, e.g. on Window for a new QGIS user profile with a OSGeo4W standard installation:
```python
{'3d': 1, 'gdal': 56, 'grass': 307, 'model': 0, 'native': 268, 'pdal': 17, 'project': 0, 'qgis': 51, 'script': 0}
```
