### ISSUE TITLE
QGIS Model Builder - Error with saving file outputs in batch mode

### ISSUE THREAD

**Issue by astuartmiller** [qgis/QGIS#57928]
### What is the bug or the crash?

![image](https://github.com/mkoenigb/ProcessX/assets/127142701/5ac96370-32c9-4263-aff7-8b59cb9037dc)
![image](https://github.com/mkoenigb/ProcessX/assets/127142701/d93abeb4-c61c-4fbf-bd82-3afbf8e2869e)

When I run this as a temporary layer output it works fine. However, when I batch the process I get an error stating that the files were not created correctly. I am saving to a file path with no spaces, and have tried .shp and gpkg with the same results

### Steps to reproduce the issue

Yes, a third party plugin was involved, but sections of the model that do not include the model are producing the same error. Removing the third party plugin also does not fix the error. This error does not appear if you check "open layers on completion", or you output only to temporary layers. The issue does not present when copy the model into a script and running it.

### Versions

QGIS version | 3.36.3-Maidenhead

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
Another user seems to have the same error on stackexchange:
https://gis.stackexchange.com/questions/467219/attributeerror-in-qgis-model-during-batchmode-processing

_No response_

**Comment by nyalldawson** [comment]
Please test with 3.38.0, this should be fixed.
