### ISSUE TITLE
Unable to connect to internet behind a proxy 

### ISSUE THREAD

**Issue by wilcar** [qgis/QGIS#57922]
#### Context : 

- I have 25 computers running Windows 10 behind a proxy (at University)
- My internet connection is working except for QGIS.
-  My proxy is setup in QGIS preferencies.
- My university use environnement variables and a script to configure the proxy settings

#### Bug : 
- Most computers can't connect, but some computers can (never the sames). 
- Often the first computer on which QGIS is launched has an Internet connection (but not always).
- Sometimes, when I press CTRL alt -supp disconnect / connect, the computers recover their connection.
- When a lot of machines manage to connect, they can lose their connection after 5/10 minutes when OSM is used

### Steps to reproduce the issue

launch QGIS

### Versions

3.28

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@wilcar, QGIS 3.28 is no longer supported. Please try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and with a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
