### ISSUE TITLE
Crash for QGis MacOs

### ISSUE THREAD

**Issue by Christophe-Wacheux** [qgis/QGIS#57925]
### What is the bug or the crash?

QGis crashes when you set up extremal values for visualisation of a raster file, using pseudo-color of a unique given band. If, during the set up, you put the **same value for min and max values**, QGis crashes immediately.

I am a MacOs user, so I hope this bug is only for MacOs, but in any case, if you can fix it for everyone (including MacOs ^^) this would be great !

Cheers

### Steps to reproduce the issue

1. Open a raster .tif file with QGis
2. Right-click on it in the list of layers, and click on "Properties..."
3. Go to symbology, and choose "Pseudo-color with unique band". You should get something like this : 
![image](https://github.com/qgis/QGIS/assets/73313219/9683a521-7aa9-4651-9e85-12d54b65fb19)
4. In the image above, Min is set to 5, Max is set to 10. If the Min is set to 10, or the Max is set to 5, QGis crashes immediately. You don't even need to apply it to the raster.

### Versions

Version de QGIS | 3.34.7-Prizren | Branche de code de QGIS | Release 3.34
-- | -- | -- | --
Version de Qt | 5.15.12
Version de Python | 3.12.4
Version de GDAL/OGR | 3.9.0
Version de Proj | 9.4.1
Version de la base de données du registre EPSG | v11.006 (2024-03-13)
Version de GEOS | 3.12.1-CAPI-1.18.1
Version de SQLite | 3.46.0
Version de PDAL | 2.7.1
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.3
Version de l'OS | macOS 14.3
  |   |   |  
Extensions Python actives
FreehandRasterGeoreferencer | 0.8.3
SemiAutomaticClassificationPlugin | 8.2.2
ee_plugin | 0.0.6
profiletool | 4.2.6
extractor | 1.2
Serval | 3.32.0
pointsamplingtool | 0.5.4
qgis-maptiler-plugin | 3.3
valuetool | 3.0.19
raster_tracer | 0.3.3
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

Version de QGIS
3.34.7-Prizren
Branche de code de QGIS
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Version de Qt
5.15.12
Version de Python
3.12.4
Version de GDAL/OGR
3.9.0
Version de Proj
9.4.1
Version de la base de données du registre EPSG
v11.006 (2024-03-13)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.46.0
Version de PDAL
2.7.1
Version du client PostgreSQL
unknown
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.3
Version de l'OS
macOS 14.3

Extensions Python actives
FreehandRasterGeoreferencer
0.8.3
SemiAutomaticClassificationPlugin
8.2.2
ee_plugin
0.0.6
profiletool
4.2.6
extractor
1.2
Serval
3.32.0
pointsamplingtool
0.5.4
qgis-maptiler-plugin
3.3
valuetool
3.0.19
raster_tracer
0.3.3
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Christophe-Wacheux, thanks for reporting. The issue doesn't occur on my Windows 10 system using ether QGIS 3.34.8 or QGIS 3.38.0 using one of my raster layers.
How did you install QGIS on your macOS system?
Please try if the issue occur also using a new QGIS user profile and please provide a sample raster layer with which the issue occur.

**Comment by agiudiceandrea** [comment]
@Christophe-Wacheux, thanks for reporting. The issue doesn't occur on my Windows 10 system using ether QGIS 3.34.8 or QGIS 3.38.0 using one of my raster layers.
How did you install QGIS on your macOS system? Did the crash generate a crash report?
Please try if the issue occur also using a new QGIS user profile and please provide a sample raster layer with which the issue occur.
