### ISSUE TITLE
No features are added to WCS layer due to wrong parameters in GetCoverage URL

### ISSUE THREAD

**Issue by tomcueue** [qgis/QGIS#57930]
### What is the bug or the crash?

Since ltr 3.26, GetCoverage calls to WCS layer return an empty layer. By activating the network logger it can be seen that the GetCapabilities call functions properly, while the URL that is subsequantly generated for the GetCoverage call shows a wrong bbox (depending on QGIS version it may be 0,0,0,0 or tottally unreasonable numbers), resulting in adding to tthe canvas an empty layer. Parameters WIDTH and HEIGHT also seem to be off.

Below part of the problematic URL generated with the GetCoverage call:

ows?SERVICE=WCS&VERSION=1.0.0&REQUEST=GetCoverage&FORMAT=GeoTIFF&COVERAGE=p_bz-Elevation:DigitalTerrainModel-0.5m&BBOX=179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368&CRS=EPSG:25832&RESPONSE_CRS=EPSG:25832&WIDTH=6&HEIGHT=3

### Steps to reproduce the issue

 1. Click on "Add WCS Layer"
 2. Connect to a WCS service
 3. Add a WCS layer to the map

### Versions

QGIS version
3.36.3-Maidenhead
QGIS code revision
2df96554
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
annotationManager
0.5
batchvectorlayersaver
0.9
ClipMultipleLayers
3.2.0
ConvertLabels
0.3
ee_plugin
0.0.6
latlontools
3.6.20
mapflow
2.6.1
qfieldsync
v4.9.1
QlrBrowser
3.0.0
quick_map_services
0.19.34
rivergis
3.0
VoGisProfilTool
3.0.2
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@tomcueue, thanks for reporting. Please try if the issue occurs also unchecking the "Extent (current: map view)" setting. May you please provide the WCS URL and the exact parameters and steps in order to replicate the issue?
It seems to me the issue is the same as the one already reported at https://github.com/qgis/QGIS/issues/50432.
