### ISSUE TITLE
Elevation Profile: Negative Scale and Offset

### ISSUE THREAD

**Issue by miili** [qgis/QGIS#57947]
### Feature description

Allow for negative scale and offset.

![image](https://github.com/qgis/QGIS/assets/4992805/908d1705-debd-4a6b-b74e-1992ad30585d)

### Additional context

Limiting scale/offset to positive values only is not reasonable.

**Comment by ptitjano** [comment]
Indeed, a negative scale does not make sense. However, a negative offset is possible and makes sense.

**Comment by miili** [comment]
Well, a negative scale makes sense to reverse the direction of the data.

For example a dataset where depth is positive. For a meaningful plot the scale has to be `-1.0`.

**Comment by miili** [comment]
Many thanks!
