### ISSUE TITLE
crash when closing View/Elevation

### ISSUE THREAD

**Issue by marjamakaroni** [qgis/QGIS#57975]
## User Feedback

when clicked the x to close the Elevation View

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00004b80 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QGraphicsScene::removeItem :
QgsPlotRectangularRubberBand::~QgsPlotRectangularRubberBand :
QgsPlotRectangularRubberBand::~QgsPlotRectangularRubberBand :
QgsPlotToolZoom::~QgsPlotToolZoom :
QgsDwgImportDialog::updateUI :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsDwgImportDialog::updateUI :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsAbout::QgsAbout :
QObjectPrivate::deleteChildren :
QWidget::~QWidget :
QgsDwgImportDialog::updateUI :
QObject::event :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.8-Prizren
QGIS code revision: 91642333
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

I didn't try to reproduce

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.4
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
latlontools | 3.6.20
openlayers_plugin | 2.0.0
pointsamplingtool | 0.5.4
qProf | 0.5.1
QuickOSM | 2.2.3
quick_map_services | 0.19.34
slyr_community | 5.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.8-Prizren
QGIS code revision
[91642333](https://github.com/qgis/QGIS/commit/91642333)
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
latlontools
3.6.20
openlayers_plugin
2.0.0
pointsamplingtool
0.5.4
qProf
0.5.1
QuickOSM
2.2.3
quick_map_services
0.19.34
slyr_community
5.0.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Could you provide steps to reproduce the crash ?
I use elevation profile every day without crashes...
