### ISSUE TITLE
unable to run ogrinfo using Master

### ISSUE THREAD

**Issue by NyakudyaA** [qgis/QGIS#57974]
### What is the bug or the crash?

When trying to solve https://github.com/qgis/QGIS/issues/57954 and https://github.com/qgis/QGIS/issues/57945 
![Screenshot 2024-07-03 at 14 43 56](https://github.com/qgis/QGIS/assets/2510900/3ff02109-165b-4008-9b82-d1f481c2765a)

I encounter the following
<img width="1259" alt="Screenshot 2024-07-03 at 15 06 46" src="https://github.com/qgis/QGIS/assets/2510900/00135b9c-aa19-4ec8-a874-1ac352986690">

This only occurs when you select vector data, this seems to be introduced by  https://github.com/qgis/QGIS/commit/e38849d750381958f3706d0214e8dd60ae1dcfbb

### Steps to reproduce the issue

I haven't set my build environment yet so I manually edited `/Applications/QGIS.app/Contents/Resources/python/plugins/processing/algs/gdal/ogrinfo.py` and pasted ogrinfo from https://github.com/qgis/QGIS/commit/e3c085ab5f6c75d8f24263c339bac832c76a4a6c and added some changes [as depicted in https://github.com/NyakudyaA/QGIS/tree/ogrinfo](https://github.com/NyakudyaA/QGIS/blob/ogrinfo/python/plugins/processing/algs/gdal/ogrinfo.py)

### Versions

QGIS Master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tested on Mac

**Comment by NyakudyaA** [comment]
@agiudiceandrea I am using code from Master for the orgrinfo, Kinda of a hack to test till I setup my build on Mac

**Comment by agiudiceandrea** [comment]
I'm also proposing a PR for https://github.com/qgis/QGIS/issues/57945. Feel free to also propose your.

**Comment by NyakudyaA** [comment]
@agiudiceandrea I am happy to let you take over, Maybe you can take a look at what I have already running in https://github.com/NyakudyaA/QGIS/blob/ogrinfo/python/plugins/processing/algs/gdal/ogrinfo.py, this already adds the JSON output and additional commands line options.

**Comment by agiudiceandrea** [comment]
It seems to me there are some flaws:
- `self.tr('HTML files (*.html)','JSON files (*.json)')))` doesn't work correctly this way (have you tried to actually save to a JSON file or to a temporary output?)
- the `-so` option doesn't work with the `-json` option
- a `-feature` option is needed
- if a layer name is added to the ogrinfo command `arguments.append(input_details.layer_name)`, then only the single layer info are written in the output file; a parameter is needed to let the user chose to only obtain the layer info or the info about all the layers in a dataset
- ```
         with open(output, 'w') as f:
            f.write('<pre>')
            for s in console_output[1:]:
                f.write(str(s))
            f.write('</pre>')
```
  this incorrectly writes `<pre>` HTML tags in the JSON output file which becomes invalid and also incorrectly writes additional CRLF at the end of the lines on a Windows system.
