### ISSUE TITLE
Mapbox GL style converter skips `step` expressions

### ISSUE THREAD

**Issue by 1ec5** [qgis/QGIS#57989]
### What is the bug or the crash?

When opening an MVT layer with a Mapbox or MapLibre stylesheet, QGIS attempts to convert the stylesheet to QGIS symbology, but this converter lacks support for the very common [`step`](https://maplibre.org/maplibre-style-spec/expressions/#step) expression operator, causing significant glitches in the resulting layer.

### Steps to reproduce the issue

1. Follow [these instructions](https://wiki.openstreetmap.org/wiki/OpenHistoricalMap/QGIS#Vector_tiles) to create a vector tile layer that has many symbols and labels based on an OpenHistoricalMap style.
2. Note the banner warning that “Style could not be completely converted”. Click the Details button.

Many of the layers include properties or filters set to `step` expressions, which result in the following warnings:

> * roads_motorway: Skipping unsupported expression
> * roads_motorway_construction: Skipping unsupported expression
> * roads_motorwaybridgetop: Skipping unsupported expression
> * roads_motorwaybridgetop_construction: Skipping unsupported expression

### Versions

(Yes, I know v3.36 is a couple releases behind, but it’s the most recent version currently available for macOS.)

QGIS version | 3.36.3-Maidenhead | QGIS code revision | 2df9655469b
-- | -- | -- | --
Qt version | 5.15.2
Python version | 3.9.5
GDAL/OGR version | 3.3.2
PROJ version | 8.1.1
EPSG Registry database version | v10.028 (2021-07-07)
GEOS version | 3.9.1-CAPI-1.14.2
SQLite version | 3.35.2
PDAL version | 2.3.0
PostgreSQL client version | unknown
SpatiaLite version | 5.0.1
QWT version | 6.1.6
QScintilla2 version | 2.11.5
OS version | macOS 14.5
  |   |   |  
Active Python plugins
QuickOSM | 1.16.0
nominatim_locator_filter | 0.2.3
processing | 2.12.99
grassprovider | 2.12.99
db_manager | 0.1.20
MetaSearch | 0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The warnings come from here:

https://github.com/qgis/QGIS/blob/5e53e183a5da95b68c4d8a259109cb02ce2cdaba/src/core/vectortile/qgsmapboxglstyleconverter.cpp#L3110

The converter has some support for the `interpolate` operator, so `step` should be handled similarly.

**Comment by pathmapper** [comment]
Here is a style which isn't working with master:

https://krzn.ldproxy.net/lika/styles/vw-tn-flst-geb?f=mbs

**Comment by pathmapper** [comment]
Here a simplified version [vw-tn-flst-geb.json](https://github.com/user-attachments/files/16981994/vw-tn-flst-geb.json):

`"text-field" : [ "step", [ "zoom" ], "default", 16, "test" ]`
