### ISSUE TITLE
I can't use "Standard Deviational Ellipse" on QGIS

### ISSUE THREAD

**Issue by ssspca** [qgis/QGIS#57993]
### What is the bug or the crash?

I can't use "Standard Deviational Ellipse" on QGIS
**Python error: An error has occurred while executing Python code: See message log (Python Error) for more details.**
![messageImage_1720165846958](https://github.com/qgis/QGIS/assets/174781305/584cf31b-bf42-4766-9a08-1772458199cc)
![messageImage_1720165836689](https://github.com/qgis/QGIS/assets/174781305/bd1686c4-4b8f-4ebd-a777-ba034b592402)
![messageImage_1720165859049](https://github.com/qgis/QGIS/assets/174781305/7e7f497c-9fa3-4525-93ab-1155b0f8c2fb)

### Steps to reproduce the issue

Go to 'Vector'
Click on 'Standard Deviational Ellipse'
See error
![messageImage_1720165846958](https://github.com/qgis/QGIS/assets/174781305/aa8a9099-d75e-42b9-bc5e-408d8c1676d0)

### Versions

QGIS version
3.38.0-Grenoble

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by alexbruy** [comment]
This is a plugin issue, please file bugreport at the plugin bugtracker.
