### ISSUE TITLE
Exporting vector layer to CSV doesnt include coordinates

### ISSUE THREAD

**Issue by APOS80** [qgis/QGIS#58007]
### What is the bug or the crash?

Exporting vector layer to CSV doesnt include coordinates

### Steps to reproduce the issue

Make scratch layer
draw point
export to CSV

### Versions

QGIS version
3.34.7-Prizren
QGIS code revision
6f7d735c
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
cigeoe_mirror_view_no_git
1.0
GeometryShapes
0.7
GroupStats
2.2.7
HCMGIS
24.1.12
kmltools
3.1.33
LandSurveyCodesImport
v0.3.0
landxmlconvertor
0.2.0
lftools
1.12.11
nominatim
1.4.5
profiletool
4.2.6
ProjectPackager
0.7.2
qad
3.0.6
qgis_hub_plugin
0.1.2
splitmultipart
1.0.0
volume_calculation_tool
0.4
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by borysiasty** [comment]
This is the default behaviour of the CSV GDAL's driver. Please change layer options: GEOMETRY to `AS_XY` or `AS_WKT` and try again. Note QGIS reads CSV with WKT geometry out of the box (even by drag n drop), while XY requires a few more clicks.

**Comment by APOS80** [comment]
Okay, missed it.

Maybe the setting could be a bit more obvious .

**Comment by borysiasty** [comment]
Then I'd say it's  a feature request and not a bug :)
