### ISSUE TITLE
add windbarb for grib raster data

### ISSUE THREAD

**Issue by ianleework** [qgis/QGIS#58017]
### Feature description

qgis 3.38 has already add windbarb renderer for mesh datasets, how about add windbarb renderer for grib2 raster layer?

**Comment by saberraz** [comment]
You can add your grib2 as a mesh instead of raster and it should be able to display wind speed as wind barbs.

**Comment by ianleework** [comment]
> You can add your grib2 as a mesh instead of raster and it should be able to display wind speed as wind barbs.

how to add grib file as mesh?
