### ISSUE TITLE
ElevationProfile Export+Atlas giving different results

### ISSUE THREAD

**Issue by Ursenstein** [qgis/QGIS#58015]
### What is the bug or the crash?

Hello Colleagues!

I want to create an elevation profile for a planned cable route and I want other lines/cables that intersect the route to be displayed in the profile. I have represented these with their parameters such as laying depth (range), diameter, and safety distance using a style (including geometry generator/buffer). (1st image)
![Screenshot 2024-07-03 190130](https://github.com/qgis/QGIS/assets/61330083/ed0d99d1-bfc1-4bbf-a30d-36d2d3d8a3a5)

The crossing features are displayed by: 
1. Substract maximum z for laying depth range (by value in the Attribute Table)
2. Extort the given z variance (by value in the Attribute Table)
3. Draw upper and lower limit with diameter length (by value in the Attribute Table)
4. Draw central circle with  diameter  (by value in the Attribute Table)
5. Draw Buffer with safety distance via Geometry Generator  (by value in the Attribute Table)

However, when I export this section as a PNG, it distorts my created style. (2nd image)
![Screenshot 2024-07-03 190151](https://github.com/qgis/QGIS/assets/61330083/f0da3d7b-6009-4443-8906-971c882aa656)
(Ignore the upper and lower Indicators here, they are supposed to be there and on the first image aswell, just overlapped by the diameter.)

And when I create the route using a report/atlas, it looks even more distorted, and the style I created is completely ignored (3rd image)
![Screenshot 2024-07-03 190208](https://github.com/qgis/QGIS/assets/61330083/1c0b7de4-6c02-4eb2-b266-0cd1f016c25a)

Is this an error/bug, or is the tool simply not that far developed yet?

PS: Exporting as PDF is kinda broken aswell : https://gis.stackexchange.com/questions/481988/qgis-elevation-profile-issues-when-exporting-to-pdf

### Steps to reproduce the issue

1. Create a Elevation Profile with Extortion and a custom Style
3. Export as PNG
4. Export via Report/Atlas

### Versions

3.36
3.38

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
> PS: Exporting as PDF is kinda broken aswell : https://gis.stackexchange.com/questions/481988/qgis-elevation-profile-issues-when-exporting-to-pdf

Could you create a separate issue ?

**Comment by nyalldawson** [comment]
Can you attach a sample project please?

**Comment by Ursenstein** [comment]
Sorry for the late reply, I’ve been very busy. I will post the requested examples in this thread in the next few days.

Thanks to everyone!
