### ISSUE TITLE
Raster clip extend / clip mask not working anymore

### ISSUE THREAD

**Issue by mastrolube** [qgis/QGIS#58041]
### What is the bug or the crash?

Hi!
I'm not able to clip raster using extend or mask with the last LTR 3.34.8. I tried with old version and it works so I think it's related to the last one only.

### Steps to reproduce the issue

Set a new project with EPSG: 32632 and import that attached source DTM layer (also in EPSG:32632).
[DTM buca 26.zip](https://github.com/user-attachments/files/16141310/DTM.buca.26.zip)

Try "clip raster by mask layer" or "clip raster by extend", you will get that error:

> Process was unexpectedly terminated
> Execution failed after 0.13 seconds

If you look at OGR messages there is that log ('drow on map canvas' option in that case):

> 2024-07-09T11:26:56     WARNING    Cannot open 565632.434500000,565693.112700000,4990028.842400000,4990068.385500000 [EPSG:32632] (Invalid range specified
>              ).(Invalid range specified
>              )
> 2024-07-09T11:26:56     WARNING    Cannot open 565632.434500000,565693.112700000,4990028.842400000,4990068.385500000 [EPSG:32632] (Invalid range specified
>              ).(Invalid range specified
>              )
> 2024-07-09T11:26:56     WARNING    Cannot open 565632.434500000,565693.112700000,4990028.842400000,4990068.385500000 [EPSG:32632] (Invalid range specified
>              ).(Invalid range specified
>              )

> 2024-07-09T11:26:56     WARNING    Cannot open 565632.434500000,565693.112700000,4990028.842400000,4990068.385500000 [EPSG:32632] (Invalid range specified
>              ).(Invalid range specified
>              )
> 

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.4
GDAL/OGR version | 3.9.0
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
  |   |   |  
Active Python plugins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.8-Prizren
QGIS code revision
[91642333](https://github.com/qgis/QGIS/commit/91642333)
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mastrolube, thanks for reporting. The issue about the incorrect `WARNING Cannot open ...  (Invalid range specified).(Invalid range specified)` logged in the Log Messages panel has been already reported https://github.com/qgis/QGIS/issues/57758 and fixed https://github.com/qgis/QGIS/pull/57772. Such fix is available in QGIS 3.38.0 and will be available in the upcoming QGIS 3.34.9.

Anyway, it seems to me such warnings don't prevent the "Clip raster by extent" GDAL processing algorithm to actually work using QGIS 3.34.8 on Windows 10.

https://github.com/user-attachments/assets/0182d555-4a26-439d-b3b7-db5562de5c03

Please provide the full processing log and exact steps in order to replicate the issue.
