### ISSUE TITLE
Properties of invalid layer crashes QGIS

### ISSUE THREAD

**Issue by kudlav** [qgis/QGIS#58043]
## User Feedback

Trying to display Properties of invalid layer crashes QGIS.

Reproducible: Always on multiple sources.
_Reload QGIS_ button doesn't reload QGIS, only closes QGIS.

### Steps to reproduce the issue

1. Layer → Add Layer → Add Raster Layer
2. Select OGC API as a Source Type
3. Put the given URL into the OGC API Endpoint: https://maps.gnosis.earth/ogcapi/collections/Daraa
4. Add
5. Add all items
6. Go through rows, on a item with a question mark right-click, select Properties

### Versions

**QGIS Info**
QGIS Version: 3.38.0-Grenoble
QGIS code revision: 37aa6188bc
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002a14 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsMapToolShapeRectangleCenterMetadata::category :
QgsPointCloudLayerProperties::syncToLayer :
QgsMapToolShapeRectangleCenterMetadata::category :
QgsRasterLayerProperties::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QMenu::exec :
QMenu::exec :
QgsLayerTreeView::contextMenuEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**Comment by agiudiceandrea** [comment]
The issue doesn't occur using QGIS 3.34.8. QGIS 3.38.0 is also slower than QGIS 3.34.8 to retrieve the layers' list and to add the layers to the map.

**Comment by kudlav** [comment]
I can confirm that obtaining the list of layers or adding layers takes a few minutes and during that time, QGIS app is unresponsive.
