### ISSUE TITLE
Systematic error when running python code

### ISSUE THREAD

**Issue by TAGILOS** [qgis/QGIS#58045]
### What is the bug or the crash?

Crash ID: [53689bc66b257b53353f6ccc94dac03870bd897e] (https://github.com/qgis/QGIS/search?q=53689bc66b257b53353f6ccc94dac03870bd897e&type=Issues)

Stack Trace

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.7-Bia?owie?a
QGIS code revision: 5a65627a
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.4.3
Running against GDAL: 3.4.3

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Systematic error when running python code

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
> QGIS Version: 3.22.7-Bia?owie?a
This version is out dated. Retry on 3.34 or 3.38

> Systematic error when running python code
Which code ?

Please add more details to your issue report. Provide data and steps to reproduce the issue.
The more details you give, best are the chance it will be fixed.
