### ISSUE TITLE
Area/Length measure tool returning substantial difference on small sample between Cartesian and Ellipsoidal

### ISSUE THREAD

**Issue by oucil** [qgis/QGIS#58059]
### What is the bug or the crash?

I am using the measure tool to get the area, in acres, of a small parcel of land. When switching between Ellipsoidal vs Cartesian method, I'm getting a difference in results that is far too large. In the first image, the Cartesian area is calculated as 1.167ac which seems about right for a space that is roughly 250' x 160'...

![Cartesian](https://github.com/qgis/QGIS/assets/3843802/ff532f5c-a767-4685-bf2d-469226c48fcb)

When I switch to Ellipsoidal, I'm getting a value of only 0.563ac, only half as large...

![Ellipsoidal](https://github.com/qgis/QGIS/assets/3843802/55b1a888-f61e-4bee-b69e-45ec46328499)

My ellipsoidal setting is set to 'WGS 84 (EPSG: 7030)

![Projection](https://github.com/qgis/QGIS/assets/3843802/b2fd847e-f52e-4443-98d2-2ea7ec2cd18e)

The way I understand it is ellipsoidal uses the curvature of the earth in its measurement, and cartesian is flat. There is no way that an area could be different by such a degree over a field smaller than a soccer pitch. I've tested with just the measure length tool as well and get similarly off results.

UPDATE:

I have the $length variable in use in a number of labels for my line layers and they seem to show the correct value.

### Steps to reproduce the issue

1. Use the measure tool to mark of an area about the size of an acre.
2. Switch between Cartesian and Ellipsoidal.

### Versions

3.36.3-Maidenhead (Rev. 2df96554)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
What crs is your project using?

**Comment by oucil** [comment]
@nyalldawson WGS 84 Pseudo-Mercator

**Comment by nyalldawson** [comment]
@oucil that's not a projection designed for accurate planar length/measurement calculation. You'll get nonsense values like this back using Cartesian calculations in that projection.

Closing as not a qgis issue.

**Comment by oucil** [comment]
@nyalldawson I switched the project to WGS 84 World Mercator and I'm getting similar results.  I'm doing a smaller map area of only about a square km. Is there a different CRS you would suggest?

**Comment by nyalldawson** [comment]
@oucil that depends entirely on the geographic area you are working in. I'd suggest searching up your local city / state / territory for recommended local projections to use.
