### ISSUE TITLE
Qgis Can't read Shapefiles

### ISSUE THREAD

**Issue by pruuuuu** [qgis/QGIS#58078]
### What is the bug or the crash?

Hi, Qgis doesn't show me any type of map, I've already tried several different shapefiles and they all open with a blank attribute table, I've already reinstalled the program 4 times. My problem is very similar to the report #37527

### Steps to reproduce the issue

every time I import a shp file

### Versions

3.34.8

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by kannes** [comment]
Does https://www.naturalearthdata.com/http//www.naturalearthdata.com/download/50m/cultural/ne_50m_admin_0_countries.zip work?

**Comment by agiudiceandrea** [comment]
@pruuuuu , please also provide the QGIS full version info ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.") as requested in the issue report form and please provide an ESRI Shapefile layer with which the issue occurs and exact steps to replicate the issue.
