### ISSUE TITLE
Processing caused crash

### ISSUE THREAD

**Issue by mercerraa** [qgis/QGIS#58074]
## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x0000530c (most recent call first):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\algs\gdal\GdalUtils.py", line 154 in runGdal
    res = proc.run(feedback)
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\algs\gdal\GdalAlgorithm.py", line 133 in processAlgorithm
    GdalUtils.runGdal(commands, feedback)

Thread 0x00000830 (most recent call first):
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\ProcessingPlugin.py", line 435 in executeAlgorithm
    dlg.exec()
  File "C:\PROGRA~1/QGIS33~1.2/apps/qgis/./python/plugins\processing\gui\ProcessingToolbox.py", line 232 in executeAlgorithm
    self.executeWithGui.emit(alg.id(), self, self.in_place_mode, False)
```

**Stack Trace**

```

QgsVectorLayerFeatureCounter::symbolFeatureCountMap :
QgsVectorLayer::onSymbolsCounted :
QgsVectorLayer::onFeatureCounterCompleted :
QMetaCallEvent::placeMetaCall :
QObject::event :
QgsPresetSchemeColorRamp::clone :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QEventDispatcherWin32::processEvents :
QEventLoop::exec :
QgsRunProcess::~QgsRunProcess :
QgsBlockingProcess::run :
pdal::MetadataNode::value :
PyLong_FromString :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
PyArg_CheckPositional :
PyObject_Call :
PyObject_Call :
PyInit_sip :
PyInit_sip :
pdal::StreamPointTable::reset :
pdal::PointView::table :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
pdal::PointView::table :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.2-Maidenhead
QGIS code revision: 6d250527
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Ran GDAL vector to raster tool

### Versions

3.36.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@mercerraa, QGIS 3.36 is no longer supported. Please try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) with a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it occurs, please provide exact steps and layers and parameters with which the issue occurs.
