### ISSUE TITLE
Check "Only show items inside current atas feature" in legend.

### ISSUE THREAD

**Issue by jmmarcotte-GIS** [qgis/QGIS#58088]
## User Feedback

I checked "Only show items inside current atas feature" in my legend. Then I loaded the atlas and it crashed. When I don't check it works fine

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006414 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsLayoutItemLegend::doUpdateFilterByMap :
QgsLayoutItemLegend::paint :
QGraphicsScene::dragMoveEvent :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.6-Prizren
QGIS code revision: 623828f5
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Go to Print composer
Click on legend item
Check "Only show items inside current atas feature" 
Load Atlas
See error

### Versions

**QGIS Info**
QGIS Version: 3.34.6-Prizren
QGIS code revision: 623828f5
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jmmarcotte-GIS , thanks for reporting. Please provide a sample project and layers with which the issue occurs.

**Comment by jamesmica** [comment]
Still an issue, but you can actually use this feature by selecting a linked map BEFORE checking "Only show items inside current atas feature". (click Legend --> Linked map, which is probably empty by defaut)
