### ISSUE TITLE
Add favourites section in processing panel

### ISSUE THREAD

**Issue by GitHubMLee** [qgis/QGIS#58104]
### Feature description

Currently the processing panel includes a list of the last 5 scripts/algorithms used under 'Recently used'. It would be good to mark scripts/algorithms as 'Favourites' and include in a new section within the Processing panel to have easy access. This would assist me as I often find it difficult to find scripts that I regularly use - particularly Vector algorithms as they are listed under 8 different sub-folders.

**Comment by nyalldawson** [comment]
This is already implemented for QGIS 3.40 -- see https://github.com/qgis/QGIS/pull/57956
