### ISSUE TITLE
How to fix font failed problem in Qgis??

### ISSUE THREAD

**Issue by Learner1907** [qgis/QGIS#58123]
### What is the bug or the crash?

Whenever I open the Qgis application I can see an error. Can someone please help me to solve the issue in the application?
![Screenshot (57)](https://github.com/user-attachments/assets/88cd3b17-28d3-40fe-8586-cb3be462a98f)

### Steps to reproduce the issue

![Screenshot (57)](https://github.com/user-attachments/assets/fc52f25d-1bac-41a7-8a06-1620386d1fdd)

### Versions

Qg
![Screenshot (57)](https://github.com/user-attachments/assets/9c6b6a4b-d71e-4302-b848-60e6696786f2)
is version 3.38.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by marylaGIS** [comment]
Try to install Open Sans font on your machine. Check it here https://gis.stackexchange.com/questions/479435/open-sans-font-installation-failed

**Comment by Learner1907** [comment]
> Try to install Open Sans font on your machine. Check it here https://gis.stackexchange.com/questions/479435/open-sans-font-installation-failed

Thanks for the comment. I will try it

**Comment by agiudiceandrea** [comment]
Fixed by https://github.com/qgis/QGIS/pull/59142.
