### ISSUE TITLE
Image only displays in older version of qgis 

### ISSUE THREAD

**Issue by apawlaczek** [qgis/QGIS#58128]
### What is the bug or the crash?

The photo (.jgw) only displays normally in version 3.34.4 (GDAL/ORG 3.8.4) while in version 3.34.8 (GDAL/ORG 3.9.0) the same photo loads, displays correct statistics, the same as the older version, but it is not visible. Nothing is displayed when zooming on the layer. I would also add that all settings, coordinate system, etc. are the same when trying in both versions.

### Steps to reproduce the issue

Every time I import this one specific .jgw file in version 3.34.8 (GDAL/ORG 3.9.0).

### Versions

Image displays in:
QGIS Version: 3.34.4-Prizren
Qt Version: 5.15.3
GDAL/OGR Version: 3.8.4

Image does not display in:
QGIS Version: 3.34.8-Prizren
Qt Version: 5.15.13
GDAL/OGR Version: 3.9.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@apawlaczek, thanks for reporting. The .jpw file is a text file that only contains the georeferencing info of the image, not the image itself. Please provide the image file .jpg and the associated georeferencing "world file" .jpw with which the issue occurs.
