### ISSUE TITLE
QGIS reads shp with 11 character attribute header

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#58152]
### What is the bug or the crash?

A colleague created, using matlab, an empty shapefile (only with one line with NULL attributes) and with an attribute with a header with 11 characters (consistency)
QGIS reads it and also allows you to add features, while ArcGIS PRO reads it but truncates the header at the tenth character.

I'm reporting this because it could be a bug!

![image](https://github.com/user-attachments/assets/6205e668-d093-44d0-9a17-1381f5c07f5d)

![image](https://github.com/user-attachments/assets/ad084da7-d9b4-4587-89c9-17f927802645)

### Steps to reproduce the issue

1. load the shapefile into QGIS 
2. and look at the attribute properties

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

[header11.zip](https://github.com/user-attachments/files/16262366/header11.zip)

**Comment by agiudiceandrea** [comment]
The DBF format has 11 bytes to store a `0` terminated string as a field name, so the field name is actually up to 10 characters. It looks like matlab doesn't add the `0` as ending byte, allowing to use all the 11 characters to store the field. I don't think this is actually an issue. Anyway the OGR provider sanitizes the fields name to 10 characters max when exporting to the ESRI Shapefile format.
Ping @rouault.

**Comment by rouault** [comment]
Yes, this is the intended behavior. Cf following constants of the shapelib library:
```
/* Shapelib read up to 11 characters, even if only 10 should normally be used */
#define XBASE_FLDNAME_LEN_READ 11
/* On writing, we limit to 10 characters */
#define XBASE_FLDNAME_LEN_WRITE 10
```

**Comment by aborruso** [comment]
> Yes, this is the intended behavior.

Thank you @rouault . Do you know why this choice was made, to object only to one character and not, for example, 3?

**Comment by rouault** [comment]
> Do you know why this choice was made, to object only to one character and not, for example, 3?

Answered by @agiudiceandrea in https://github.com/qgis/QGIS/issues/58152#issuecomment-2233161669

**Comment by aborruso** [comment]
> Answered by @agiudiceandrea in [#58152 (comment)](https://github.com/qgis/QGIS/issues/58152#issuecomment-2233161669)

Thank you.

We could introduce an additional check during reading. If the eleventh byte is a null character (\0), treat it as the standard terminator. Otherwise, raise an error indicating that the field name is not correctly terminated.
Therefore, it would be acceptable to have 11 characters only if the eleventh character is the \0  terminator.

What do you think about

**Comment by rouault** [comment]
> Therefore, it would be acceptable to have 11 characters only if the eleventh character is the \0 termin

The field name is encoded on 11 bytes: not less, not more. So it is nominally 10 characters or less + a \0 terminator (or the non-standard situation of 11 characters without a \0 terminator)

**Comment by aborruso** [comment]
> or the non-standard situation of 11 characters without a \0 terminator

Please don't hate me: and why was it decided here that the software must accept a nonstandard situation, since it is easily mapped as wrong?
I probably do not understand you, because I am not technically prepared. And I apologize for that.

**Comment by rouault** [comment]
> and why was it decided here that the software must accept a nonstandard situation

I don't know. Probably the common logic: "be lax on reading, and strict on writing". This dates back to the initial revision of shapelib 29 years ago: https://github.com/OSGeo/shapelib/commit/4af7724fe663aee90bc81eb800371fb979228679#diff-dad95b297ecd1ec47ff997ebfc36e4be7104f688b01954f704f0393a58ba5e09R543

**Comment by aborruso** [comment]
But if it is 12 characters is it always lax on reading? 🙃

Okay, I'll stop here. For me it is something that should be changed, because the case is left open and it fits, because it may be 10 or 11, for the reasons said, but it is not mapped correctly.

Thank you for your time

**Comment by pigreco** [comment]
Thanks @agiudiceandrea for the reply and thanks @rouault for your time and thanks @aborruso for the time you wasted (it's wasted at this point)
I would just like to understand why Nyall put the label "it won't work out", what does this label mean?

**Comment by nyalldawson** [comment]
It means there'll be no action taken
