### ISSUE TITLE
Scale Dependent Visibility on layer wrong on scale interval edges in EPSG:25832

### ISSUE THREAD

**Issue by chau-intl** [qgis/QGIS#58150]
### What is the bug or the crash?

I have two layers, L1 and L2, and both has `Scale Dependent Visibility` (Layer Properties / Rendering) enabled:
- L1 has `Maximum (inclusive)` set to `1:1` and has `Minimum (exclusive)` set to `1:100`.
- L2 has `Maximum (inclusive)` set to `1:100` and has `Minimum (exclusive)` set to `1:1,000`.

When setting the zoom level of QGIS to exactly `1:100` both L1 and L2 are visible. I would expect L1 to be invisible (since it has exclusive on Minimum) and L2 to be visible (since it has inclusive on Maximum).

I didn't submit this ticket just because of issues with scale `1:100`. I see the same issue at scale `1:10,000`, `1:25,000`, `1:100,000`, `1:250,000` and `1:1,000,000` but not at scale `1:50,000`, `1:500,000` and `1:5,000,000`.
### Steps to reproduce the issue

Add two layers and set the scale dependent visibility of both layers according to the bug-description.

### Versions

3.34.8, 3.38.0, 3.39 (67e056379e) - all on Windows 10.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Looking briefly at the code I see this:

https://github.com/qgis/QGIS/blob/9e47ca4230edfe5d72bc2130d5d584086f3a8402/src/core/qgis.cpp#L56
https://github.com/qgis/QGIS/blob/9e47ca4230edfe5d72bc2130d5d584086f3a8402/src/core/qgsmaplayer.cpp#L1147-L1151

Could the `SCALE_PRECISION` be the reason that both layers are rendered at exactly `1:100` in EPSG:25832?

**Comment by gacarrillor** [comment]
@chau-intl, this should be solved for QGIS 3.40, which will be available on 25th October.
Feel free to reopen if you still find issues.

**Comment by chau-intl** [comment]
@gacarrillor, I have just tested the QGIS nightlies and in my use cases now it works. Thanks a lot for looking into this!

**Comment by gacarrillor** [comment]
Great! Thanks for reporting.
