### ISSUE TITLE
GeoJSON export conform RFC7946, not working as expected

### ISSUE THREAD

**Issue by jkr-wrk** [qgis/QGIS#58169]
### What is the bug or the crash?

When exporting to GeoJSON with the following settings:

COORDINATE_PRECISION 3 (or 4)
RFC7946 YES

The data is not reprojected from 28992 to urn:ogc:def:crs:OGC::CRS84

When exporting to GeoJSON with the following settings:

COORDINATE_PRECISION 5 (or 10,15 or 16)
RFC7946 YES

The data is reprojected to urn:ogc:def:crs:OGC::CRS84

The RFC7946 setting is unclear about what it does, but I think it should influence if data is or is not reprojected.

### Steps to reproduce the issue

Create a dataset in epsg:28992
Right click on layer and export features
Set a save as file name
Fill in coordinate precision 3
Select RFC7946 YES
Click okey

Repeat but with coordinate precision 5

### Versions

QGIS version
3.34.8-Prizren
QGIS code revision
[91642333](https://github.com/qgis/QGIS/commit/91642333)
Qt version
5.15.13
Python version
3.12.4
Compiled against GDAL/OGR
3.9.0
Running against GDAL/OGR
3.9.1
PROJ version
9.4.0
EPSG Registry database version
()
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by EramarkMedia** [comment]
Good day.

I just noticed the same yesterday actually, as i picked up a project that i had exported GeoJSON assets for, quite some time ago.
Took a while before i got to comparing the outputs...

I'm on: **QGIS version | 3.22.4-Białowieża**

**Comment by rouault** [comment]
> The data is reprojected to urn:ogc:def:crs:OGC::CRS84

yes, this is fully expected. Cf https://gdal.org/drivers/vector/geojson.html#rfc-7946-write-support

**Comment by jkr-wrk** [comment]
I'm sorry I was not clear about the issue.

The issue is that exporting sometimes is converted and sometimes is not, with the same setting for RFC7946 to YES.
There is nothing in the page you reference about NOT reprojecting when precision is 3 digits.

Could you reopen the issue?

**Comment by agiudiceandrea** [comment]
@jkr-wrk , I cannot replicate the reported behaviour using QGIS 3.34.9 on Windows. Following your steps, the coordinates are always reprojected to WGS84 either setting the precisione to 3, 4 or 5.

**Comment by jkr-wrk** [comment]
[Reprojecting when yes.qgz.zip](https://github.com/user-attachments/files/16332387/Reprojecting.when.yes.qgz.zip)
[test_json_from_wfs_3.34.8_RFC7946_YES_P3.geojson.json](https://github.com/user-attachments/files/16332393/test_json_from_wfs_3.34.8_RFC7946_YES_P3.geojson.json)

![2024-07-22_13-50-09](https://github.com/user-attachments/assets/5be71116-0fe1-4cda-b212-b0d0af5b3fe8)

**Comment by jkr-wrk** [comment]
Tried it in 3.39.0 as well.

Same result, clean profile, only PDOK plugin.

<table width='100%' align='center'><tr><td colspan="2"><b>Libraries</b></td><tr><td>QGIS-versie</td><td>3.39.0-Master</td></tr><tr><td>QGIS code revisie</td><td><a href="https://github.com/qgis/QGIS/commit/67e056379e">67e056379e</a></td></tr><tr><td>Qt versie</td><td>5.15.13</td></tr><tr><td>Python versie</td><td>3.12.4</td></tr><tr><td>GDAL/OGR versie</td><td>3.10.0dev-60133b1f8b (Compiled)<br/>3.10.0dev-6b9627aa8f (Running)</td></tr><tr><td>PROJ versie</td><td>9.4.0</td></tr><tr><td>EPSG-register databaseversie</td><td> ()</td></tr><tr><td>GEOS versie</td><td>3.12.2-CAPI-1.18.2</td></tr><tr><td>SQLite versie</td><td>3.45.1</td></tr><tr><td>PDAL versie</td><td>2.6.3</td></tr><tr><td>PostgreSQL client versie</td><td>16.2</td></tr><tr><td>SpatiaLite versie</td><td>5.1.0</td></td></tr><tr><td>QWT versie</td><td>6.2.0</td></tr><tr><td>QScintilla2 versie</td><td>2.14.1</td></tr><tr><td>OS versie</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2"><i>Deze versie van QGIS schrijft debug-informatie.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Actieve Python plug-ins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>pdokservicesplugin</td><td>5.1.1</td></tr></table>

**Comment by agiudiceandrea** [comment]
@rouault it looks like the issue is layer specific, indeed, more precisely, geometry specific.

It occur also using ogr2ogr: if the coordinate_precision is too low, then a geometry can became invalid and in this case such geometry is not reprojected. In debug mode, in such case the `GeoJSON: Running SetPrecision() to correct an invalid geometry due to reduced precision output` message is displayed.

```
ogr2ogr -lco COORDINATE_PRECISION=7 -lco RFC7946=YES --debug ON Provincie_prec_7.geojson WFS:"https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0" bestuurlijkegebieden:Provinciegebied

[...]
GDAL: GDALOpen(WFS:https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0, this=000001B9A7B26B70) succeeds as WFS.
GDAL: Using GeoJSON driver
GDAL: GDALDriver::Create(GeoJSON,Provincie_prec_7.geojson,0,0,0,Unknown,0000000000000000)
[...]
GeoJSON: Running SetPrecision() to correct an invalid geometry due to reduced precision output
GeoJSON: Running SetPrecision() to correct an invalid geometry due to reduced precision output
[...]
GDAL: GDALClose(WFS:https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0, this=000001B9A7B26B70)
GDAL: GDALClose(Provincie_prec_7.geojson, this=000001B9A97C4ED0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

```
ogr2ogr -lco COORDINATE_PRECISION=8 -lco RFC7946=YES --debug ON Provincie_prec_8.geojson WFS:"https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0" bestuurlijkegebieden:Provinciegebied

[...]
GDAL: GDALOpen(WFS:https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0, this=00000269C5307B00) succeeds as WFS.
GDAL: Using GeoJSON driver
GDAL: GDALDriver::Create(GeoJSON,Provincie_prec_8.geojson,0,0,0,Unknown,0000000000000000)
[...]
GDAL: GDALClose(WFS:https://service.pdok.nl/kadaster/bestuurlijkegebieden/wfs/v1_0, this=00000269C5307B00)
GDAL: GDALClose(Provincie_prec_8.geojson, this=00000269C580FDF0)
GDAL: In GDALDestroy - unloading GDAL shared library.
```

**Comment by rouault** [comment]
> It occur also using ogr2ogr: if the coordinate_precision is too low, then a geometry can became invalid and in this case such geometry is not reprojected.

ok, this is a GDAL 3.9.0 regression. Will be fixed per https://github.com/OSGeo/gdal/pull/10466

**Comment by jkr-wrk** [comment]
Thanks, I think I understand why it was happening with my dataset and this specific settings.

As I understand: With a coordinate-precision of 3 and using WGS84, the coordinates will move about 100 meters, this could result in points overlapping or line-intersecting. This error will stop the re-projecting but will still export the data.

And I was testing with 3 because without reprojecting this would be a reasonable precision for 28992.

Does the proposed fix raise an error that geometry will be invalid with the current precision setting? Or does it export the re-projected data even if it is invalid? Just curious.

**Comment by jkr-wrk** [comment]
Btw. thanks for looking into this. And fixing in such short time.

**Comment by rouault** [comment]
> Does the proposed fix raise an error that geometry will be invalid with the current precision setting?

it runs the GEOS' MakeValid operation after reprojection + SetPrecision to obtain a geometry that is both valid and has the request precision.
