### ISSUE TITLE
Atlas export lags because of mask display

### ISSUE THREAD

**Issue by erwan-GIS** [qgis/QGIS#58167]
### What is the bug or the crash?

i've created an atlas that contains layers using labbels with the mask option. all fine exept once I generate an Atlas in the template. then the export option to pdf or png is taking hours to procede. while when I remove the masking option on the labbel, it works fine.

### Steps to reproduce the issue

note an actual error just a huge lag once using masked labblel in an Atlas (especially once exporting in pdf or png)

### Versions

![image](https://github.com/user-attachments/assets/8b70056c-1c74-4f2b-ab9e-0395bda975ac)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Please try with a nightly of 3.38 or master -- this should be fixed already

**Comment by erwan-GIS** [comment]
no better with 3.38 "grenoble"

**Comment by nyalldawson** [comment]
@erwan-GIS it needs testing against a nightly of 3.38 -- there's changes queued for 3.38.1
