### ISSUE TITLE
QGIS unable to open vector tiles using OGCAPI

### ISSUE THREAD

**Issue by doublebyte1** [qgis/QGIS#58174]
### What is the bug or the crash?

It is unclear whether vector tiles should be opened using the "Add Raster Layer" option, or "Add Vector Layer" option, as the [OGCAPI driver](https://gdal.org/drivers/raster/ogcapi.html) is part of the raster drivers of GDAL. However, none of these options work.

### Steps to reproduce the issue

Go to "Add Vector Layer..." and select `OGCAPI` and add the following endpoint: https://maps.gnosis.earth/ogcapi/collections/montreal

In API options, select "Tiles"
![image](https://github.com/user-attachments/assets/8f4ce282-556d-4b7d-bb84-b970bf915605)

QGIS will get stuck in a loop trying to read the zoom levels

![Screenshot from 2024-07-18 21-02-22](https://github.com/user-attachments/assets/668b21ae-b990-41b4-afb6-5630c0a8a788)

Trying to read the layer using "Add Raster Layer..." also won't work, as QGIS will try to read bands from a raster image and then fail with this message:

`   CRITICAL    Invalid Data Source : OGCAPI:https://demo.pygeoapi.io/master/collections/lakes|option:API=TILES is not a valid or recognized data source.`

![Screenshot from 2024-07-18 21-05-52](https://github.com/user-attachments/assets/32987bac-1af2-40aa-9f46-b52c89a09cb7)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.39.0-Master
-- | --
QGIS code revision | 399f7df1c7
Qt version | 5.15.3
Python version | 3.10.3 (Compiled)(Running)
GDAL/OGR version | 3.10.0dev-126a88523a
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.37.2
PDAL version | 2.6.2

</body></html>QGIS version
3.39.0-Master
QGIS code revision
[399f7df1c7](https://github.com/qgis/QGIS/commit/399f7df1c7)
Qt version
5.15.3
Python version
3.10.3 (Compiled)
(Running)
GDAL/OGR version
3.10.0dev-126a88523a
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.37.2
PDAL version
2.6.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Opening the layer using GDAL appears to be working correctly:

```
 ogrinfo "OGCAPI:https://maps.gnosis.earth/ogcapi/collections/montreal" -oo API=TILES
INFO: Open of `OGCAPI:https://maps.gnosis.earth/ogcapi/collections/montreal'
      using driver `OGCAPI' successful.
Metadata:
  TITLE=montreal
1: Zoom level 0
2: Zoom level 1
3: Zoom level 2
4: Zoom level 3
5: Zoom level 4
6: Zoom level 5
7: Zoom level 6
8: Zoom level 7
9: Zoom level 8
10: Zoom level 9
11: Zoom level 10
12: Zoom level 11
13: Zoom level 12
14: Zoom level 13
15: Zoom level 14

```

**Comment by doublebyte1** [comment]
@nyalldawson  @rouault with this fix QGIS is able to iterate over the zoom levels and displays them, prompting the user to choose a zoom level.

![Screenshot from 2024-07-31 16-01-12](https://github.com/user-attachments/assets/6d9fe4b9-9cd0-44ae-85a9-ddbf2ee44fd0)

It seems that each zoom level is identified as a layer? Not sure this is the behavior a user would expect. After choosing a zoom level, QGIS is able to correctly open the layer.
 
![Screenshot from 2024-07-31 16-02-01](https://github.com/user-attachments/assets/39ab11bf-06e9-46f7-81c5-f059905eee75)

**Comment by rouault** [comment]
> Not sure this is the behavior a user would expect.

Probably not, but we don't have better to offer. The OGR/vector API doesn't have a concept of zoom level

**Comment by jerstlouis** [comment]
@doublebyte1 See https://github.com/OSGeo/gdal/issues/7979 and https://github.com/OSGeo/gdal/issues/7980 for related improvement suggestions.

This issue is also related to https://github.com/OSGeo/gdal/issues/7969
