### ISSUE TITLE
Fix parsing of HSL color with floats

### ISSUE THREAD

**Issue by lazaa32** [qgis/QGIS#58170]
### What is the bug or the crash?

HSL color definition consists of:
- `hue` - in degrees 0-360
- `saturation` - in percentage 0-100
- `lightness` - in percentage 0-100

Unlike RGB where parameters are integers, for HSL valid color definition can be e.g. `hsl(74.5, 15.6%, 77.1%)` (float), however trying to parse this fails. On the other hand parsing `hsl(74, 15%, 77%)`  (only integers) goes without any problem. I'm using `gsSymbolLayerUtils.parseColor()` method.

### Steps to reproduce the issue

Open Python console (Ctrl+Alt+P)
Run this code:
```
from qgis.core import QgsSymbolLayerUtils
QgsSymbolLayerUtils.parseColor('hsl(77,50%,50%)')
>>> <QColor: HSLA 77, 127, 127, 255>
QgsSymbolLayerUtils.parseColor('hsl(77.1,50.2%,50.2%)')
>>> <QColor: invalid>
```

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.38.0-Grenoble | QGIS code revision | 37aa6188bc3
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.4
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.5 (Ubuntu 15.5-0ubuntu0.23.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | Ubuntu 23.04
  |   |   |  
Active Python plugins
processing | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.6
db_manager | 0.1.20

</body></html>QGIS version
3.38.0-Grenoble
QGIS code revision
[37aa6188bc3](https://github.com/qgis/QGIS/commit/37aa6188bc3)
Qt version
5.15.8
Python version
3.11.4
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.5 (Ubuntu 15.5-0ubuntu0.23.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
Ubuntu 23.04

Active Python plugins
processing
2.12.99
grassprovider
2.12.99
MetaSearch
0.3.6
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by lazaa32** [comment]
The values are casted to int before giving to Qt.https://github.com/qgis/QGIS/blob/2f3bbc667055e0c87f60c1aa04de665c68f212b2/src/core/symbology/qgssymbollayerutils.cpp#L3944-L3946
But the regex https://github.com/qgis/QGIS/blob/2f3bbc667055e0c87f60c1aa04de665c68f212b2/src/core/symbology/qgssymbollayerutils.cpp#L3940 matches only integer `"^\\s*hsl\\(?\\s*(\\d+)\\s*,\\s*(\\d+)\\s*%\\s*,\\s*(\\d+)\\s*%\\s*\\)?\\s*;?\\s*$"`

**Comment by lazaa32** [comment]
> Qt itself only accepts int, https://doc.qt.io/qt-6/qcolor.html#getHsl

Qt accepts float as well, https://doc.qt.io/qt-6/qcolor.html#setHslF

**Comment by roya0045** [comment]
> > Qt itself only accepts int, https://doc.qt.io/qt-6/qcolor.html#getHsl
> 
> 
> 
> Qt accepts float as well, https://doc.qt.io/qt-6/qcolor.html#setHslF
> 
> 

If they are in the range 0 to 1.0, not bigger.

**Comment by lazaa32** [comment]
> > > Qt itself only accepts int, https://doc.qt.io/qt-6/qcolor.html#getHsl
> > 
> > 
> > Qt accepts float as well, https://doc.qt.io/qt-6/qcolor.html#setHslF
> 
> If they are in the range 0 to 1.0, not bigger.

Oh yes, you're right. 
I would still expect this:
```
QgsSymbolLayerUtils.parseColor('hsl(77,50%,50%)')
>>> <QColor: HSLA 77, 127, 127, 255>
QgsSymbolLayerUtils.parseColor('hsl(77.1,50.2%,50.2%)')
>>> <QColor: HSLA 77, 127, 127, 255>
```
