### ISSUE TITLE
Mesh - bad allocation error

### ISSUE THREAD

**Issue by bbjr-creator** [qgis/QGIS#58181]
### What is the bug or the crash?

When loading a mesh (2dm-file) of size 5GB theres a bad allocation error. Is there any possibility to increase the memory threshold for mesh files for a significant amount to also load mesh files of size 40-50 GB?

![QGIS_Fehlermeldung](https://github.com/user-attachments/assets/b29d2541-2605-43c4-844d-9b87c99600ec)

### Steps to reproduce the issue

1. Load 2dm file of size 5GB or bigger.

### Versions

3.38

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by saberraz** [comment]
Is your 2dm an ascii file? It is not the most ideal format to handle large meshes. It is best to use binary 2dm or UGRID if possible.

**Comment by bbjr-creator** [comment]
Yes, unfortunatley im obligated to use an ascii file.
