### ISSUE TITLE
[Error] select a library issue

### ISSUE THREAD

**Issue by Muidz** [qgis/QGIS#58189]
### What is the bug or the crash?

got same issue as this bug = https://github.com/qgis/QGIS/issues/47285 ( Wrong module name in some SAGA description files #47285 ).

running SAGA using SAGA NextGen Plugin.

I've tried uninstall and reinstall using osgeo4w, but the issue still happen.

I also try to edit the second line in "terrain_analysis_upslope_height,_slope,_aspect.txt" as suggested by others, from "toolchains_terrain_analysis" to "terrain_analysis". but the txt file 2nd line already shows as "terrain_analysis" 
[C:\Users\__\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins\processing_saga_nextgen\description] folder

happen similarly when try to run Flow accumulation (one step) tool.

QGIS version: 3.34.8-Prizren
QGIS code revision: 91642333
Qt version: 5.15.13
Python version: 3.12.4
GDAL version: 3.9.1
GEOS version: 3.12.2-CAPI-1.18.2
PROJ version: Rel. 9.4.0, March 1st, 2024
PDAL version: 2.6.3 (git-version: b5523a)
SAGA Next Gen version: 1.0.0
Algorithm started at: 2024-07-19T22:28:29
Algorithm 'Upslope height, slope, aspect' starting…
Input parameters:
{ 'ASPECT' : 'TEMPORARY_OUTPUT', 'DEM' : 'D:/Documents/SRTM/Clip.tif', 'FLOW_METHOD' : 4, 'HEIGHT' : 'TEMPORARY_OUTPUT', 'SLOPE' : 'TEMPORARY_OUTPUT' }

io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/0805ed557080431382554c85cbed51be/Clip.sgrd" -FILES "D:/Documents/SRTM/Clip.tif"
terrain_analysis "upslope_height" -DEM "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/0805ed557080431382554c85cbed51be/Clip.sgrd" -FLOW_METHOD 4 -HEIGHT "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/5bd1ee985ed8436c8be3aeb5b17ef260/HEIGHT.sdat" -SLOPE "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/f2b4a702df6f424a8cffa876f89878cd/SLOPE.sdat" -ASPECT "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/262ca84ed36b4191854f9b4dcfa267c2/ASPECT.sdat"

D:\Documents>set SAGA=C:/OSGeo4W/apps\saga

D:\Documents>set SAGA_MLB=C:/OSGeo4W/apps\saga\modules

D:\Documents>PATH=C:\OSGeo4W\apps\qgis-ltr\bin;C:\OSGeo4W\apps\qt5\bin;C:\OSGeo4W\apps\Python312\Scripts;C:\OSGeo4W\bin;C:\Windows\system32;C:\Windows;C:\Windows\system32\WBem;C:/OSGeo4W/apps\saga;C:/OSGeo4W/apps\saga\modules

D:\Documents>saga_cmd io_gdal 0 -TRANSFORM 1 -RESAMPLING 3 -GRIDS "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/0805ed557080431382554c85cbed51be/Clip.sgrd" -FILES "D:/Documents/SRTM/Clip.tif"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 9.3.1 (64 bit)

____________________________
library path: C:\OSGeo4W\apps\saga\tools\
library path: C:\OSGeo4W\apps\saga\tools\
library name: io_gdal
library : io_gdal
tool : Import Raster
identifier : 0
author : O.Conrad (c) 2007 (A.Ringeler)
processors : 12 [12]
____________________________

[Import Raster] Execution started...

__________
[Import Raster] Parameters:

Grids: No objects
Files: "D:/Documents/SRTM/Clip.tif"
Multiple Bands Output: automatic
Subsets:
Select from Multiple Bands:
Transformation: true
Resampling: B-Spline Interpolation
Extent: original

Dataset: D:/Documents/SRTM/Clip.tif

Driver: GTiff

Bands: 1

Rows: 1499

Columns: 1225

loading: Clip

__________
total execution time: 0 milliseconds (less than 1 millisecond)

[Import Raster] Execution succeeded (less than 1 millisecond)

Saving grid: C:/Users/__/AppData/Local/Temp/processing_PhJRzN/0805ed557080431382554c85cbed51be/Clip.sgrd...

okay

D:\Documents>saga_cmd terrain_analysis "upslope_height" -DEM "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/0805ed557080431382554c85cbed51be/Clip.sgrd" -FLOW_METHOD 4 -HEIGHT "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/5bd1ee985ed8436c8be3aeb5b17ef260/HEIGHT.sdat" -SLOPE "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/f2b4a702df6f424a8cffa876f89878cd/SLOPE.sdat" -ASPECT "C:/Users/__/AppData/Local/Temp/processing_PhJRzN/262ca84ed36b4191854f9b4dcfa267c2/ASPECT.sdat"
____________________________

##### # ## ##### # ##
____________________________

SAGA Version: 9.3.1 (64 bit)

88 loaded tool libraries (756 tools):
- climate_tools
- contrib_perego
- db_odbc
- db_pgsql
- docs_html
- docs_pdf
- garden_fractals
- garden_webservices
- grid_analysis
- grid_calculus
- grid_calculus_bsl
- grid_filter
- grid_gridding
- grid_spline
- grid_tools
- grid_visualisation
- grids_tools
- imagery_classification
- imagery_isocluster
- imagery_maxent
- imagery_photogrammetry
- imagery_segmentation
- imagery_svm
- imagery_tools
- io_esri_e00
- io_gdal
- io_gps
- io_grid
- io_grid_image
- io_pdal
- io_shapes
- io_table
- io_virtual
- io_webservices
- pj_georeference
- pj_geotrans
- pj_proj4
- pointcloud_tools
- shapes_grid
- shapes_lines
- shapes_points
- shapes_polygons
- shapes_tools
- shapes_transect
- sim_air_flow
- sim_cellular_automata
- sim_ecosystems_hugget
- sim_erosion
- sim_fire_spreading
- sim_geomorphology
- sim_hydrology
- sim_ihacres
- sim_landscape_evolution
- sim_qm_of_esp
- sim_rivflow
- statistics_grid
- statistics_kriging
- statistics_points
- statistics_regression
- ta_channels
- ta_cliffmetrics
- ta_compound
- ta_hydrology
- ta_lighting
- ta_morphometry
- ta_preprocessor
- ta_profiles
- ta_slope_stability
- table_calculus
- table_tools
- tin_tools
- vis_3d_viewer
- _tool_chains_uncategorized *
- climate_tools *
- grid_filter *
- grid_tools *
- grids_tools *
- imagery_classification *
- imagery_segmentation *
- io_table *
- shapes_grid *
- shapes_points *
- shapes_polygons *
- shapes_tools *
- statistics_grid *
- ta_hydrology *
- ta_morphometry *
- tta_tools *

*) tool chain libraries

[Error] select a library

type -h or --help for further information

D:\Documents>exit
Execution completed in 4.36 seconds
Results:
{'ASPECT': 'C:/Users/__/AppData/Local/Temp/processing_PhJRzN/262ca84ed36b4191854f9b4dcfa267c2/ASPECT.sdat',
'HEIGHT': 'C:/Users/__/AppData/Local/Temp/processing_PhJRzN/5bd1ee985ed8436c8be3aeb5b17ef260/HEIGHT.sdat',
'SLOPE': 'C:/Users/__/AppData/Local/Temp/processing_PhJRzN/f2b4a702df6f424a8cffa876f89878cd/SLOPE.sdat'}

Loading resulting layers
The following layers were not correctly generated.
• C:/Users/__/AppData/Local/Temp/processing_PhJRzN/262ca84ed36b4191854f9b4dcfa267c2/ASPECT.sdat
• C:/Users/__/AppData/Local/Temp/processing_PhJRzN/5bd1ee985ed8436c8be3aeb5b17ef260/HEIGHT.sdat
• C:/Users/__/AppData/Local/Temp/processing_PhJRzN/f2b4a702df6f424a8cffa876f89878cd/SLOPE.sdat
You can check the 'Log Messages Panel' in QGIS main window to find more information about the execution of the algorithm.

### Steps to reproduce the issue

1. go to processing toolbox (SAGA
2. select upslope height, slope and aspect
3. put srtm data
4. run
5. got the error

### Versions

QGIS version | 3.34.8-Prizren | QGIS code revision | 91642333
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.4
Compiled against GDAL/OGR | 3.9.0 | Running against GDAL/OGR | 3.9.1
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 11 Version 2009
  |   |   |  
Active Python plugins
processing_saga_nextgen | 1.0.0
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Muidz, thanks for reporting. Anyway, the issue is related to the third-party external plugin "SAGA NextGen Plugin", so you need to report the issue to the "SAGA NextGen Plugin" developers in order for the issue to be fixed.
