### ISSUE TITLE
QGIS Server filter does not work as expected for intersection filters

### ISSUE THREAD

**Issue by timlinux** [qgis/QGIS#58220]
### What is the bug or the crash?

I am unable to get OGC Feature filters to work properly with spatial filters.

### Steps to reproduce the issue

Scenario 1: Requesting features intersecting with a point should return zero features if the point does not intersect any feature:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?filter=intersects(geometry,%20POINT(10.0,20.0))

![image](https://github.com/user-attachments/assets/141cf1e4-58c6-4a7f-ba6f-8e256a76766e)

Scenario 2: Requesting features intersecting with a point should return zero features if the point does not intersect any feature AND the point is outside the layer bbox:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?filter=intersects(geometry, POINT(-1000.0,1000.0))

![image](https://github.com/user-attachments/assets/36d85e6a-3c10-4599-89be-76472cb03517)

Scenario 3:  Requesting features using a bbox filter where the bbox does not intersect, the layer bbox correctly returns 0 records:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?bbox=1000.0,2000.0,1001.0,2001.0

![image](https://github.com/user-attachments/assets/104567dc-632e-470c-9ce2-c0f3a8da358a)

Scenario 4:  Requesting features using a bbox filter where the bbox **does** intersect, the layer bbox incorrectly returns  5 records:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?bbox=0.0,0.0,0.001,0.001

![image](https://github.com/user-attachments/assets/0a5e0a2d-a12d-4b24-b572-123c50245836)

Scenario 5: Requesting features using a point filter where the point overlays a polygon should return 1 feature but it returns all features:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?filter=intersects(geometry,%20POINT(2.13,21.80))

![image](https://github.com/user-attachments/assets/dbef06d5-03e8-459a-a12c-d264b5f0f651)

Scenario 6: Requesting features using a zero dimension bbox filter where the point overlays a polygon should return 1 feature but it returns 9 features:

http://37.27.93.162:8080/ogc/wfs3/collections/world/items?bbox=2.13,21.80,2.13,21.80

![image](https://github.com/user-attachments/assets/3836b966-f43a-49ba-85d1-e739b1ca910d)

And a valid box returns the same: http://37.27.93.162:8080/ogc/wfs3/collections/world/items?bbox=2.13,21.80,2.14,21.81
@elpaso Do you have any idea about this? Am I misunderstanding the spec or QGIS Server capabilities?

### Versions

Docker image for QGIS Server qgis/qgis-server:stable

qgis-server-1  | 12:52:02 INFO Server[18]: QGIS Server Starting : 3.38.1-Grenoble (3d4177afc6b)

## Validation

I did validate that doing the same query in QGIS using a pg layer and select by location behaves as expected:

![image](https://github.com/user-attachments/assets/d849a6ab-558c-432c-88df-cf8df12f0ddd)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
@timlinux where did you see `filter` is supported? It is not, and it is not in the API description.

**Comment by elpaso** [comment]
@timlinux I have tested all BBOX scenarios and I cannot reproduce any of the issues with current master.
