### ISSUE TITLE
wkbType() now only returns integer instead of string

### ISSUE THREAD

**Issue by lgouzin** [qgis/QGIS#58227]
### What is the bug or the crash?

In previous versions (at least up until Lima 3.32), geom.wkbType() would return a string (i.e.: WkbType.PointZ ), latest LTR version now return an integer (i.e. 1001).
The same output can be done using QgsWkbTypes.displayString(wkb_type)

### Steps to reproduce the issue

Open a vector layer and the python console. 
Run:

layer = iface.activeLayer()
for feature in layer.getFeatures():
    geom = feature.geometry()
    print(geom.wkbType(),QgsWkbTypes.displayString(geom.wkbType()))

### Versions

QGIS version
3.34.9-Prizren
QGIS code revision
cbbc7bdf
Qt version
5.15.13
Python version
3.12.4
Compiled against GDAL/OGR
3.9.0
Running against GDAL/OGR
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
alasqa
0.1
icsm_ntv2_transformer
1.1.1
ImportPhotos
3.0.5
ntv2_transformations
0.20
plugin_20200801_Sydney_trainsv3
0.3
plugin_reloader
0.9.4
qbeaver
1.2.8
Qgis2threejs
2.7.3
qgis2web
3.21.0
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@lgouzin, I cannot confirm the described behavior. It seems to me the provided python script, applied to a PointZ layer with a PointZ feature, prints `1001 PointZ` using either QGIS LTR 3.34 or QGIS LTR 3.28 or QGIS LTR 3.16.

**Comment by lgouzin** [comment]
Here is a better comparison using an example from https://qgis.org/pyqgis/master/core/QgsPoint.html

pt = QgsPoint(30, 40, wkbType=QgsWkbTypes.PointZ)
pt.z() # nan
print(pt.wkbType())


This is from 3.34.9-Prizren:
![image](https://github.com/user-attachments/assets/98dd3dde-8e09-4ed9-9447-57870ab19b9c)
QGIS version
3.34.9-Prizren
QGIS code revision
cbbc7bdf
Qt version
5.15.13
Python version
3.12.4
Compiled against GDAL/OGR
3.9.0
Running against GDAL/OGR
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
icsm_ntv2_transformer
1.1.1
ImportPhotos
3.0.5
ntv2_transformations
0.20
plugin_reloader
0.9.4
qbeaver
1.2.8
Qgis2threejs
2.7.3
qgis2web
3.21.0
db_manager
0.1.20
processing
2.12.99



And this is from Lima 3.32.1:
![image](https://github.com/user-attachments/assets/8b149fc3-2f0e-4347-9dcd-06b06d679a1f)


QGIS version	
3.32.1-Lima	QGIS code revision	4a078ecf
Qt version
5.15.3
Python version	
3.9.5
GDAL/OGR version	
3.7.1
PROJ version	
9.2.1
EPSG Registry database version	
v10.088 (2023-05-13)
GEOS version	
3.12.0-CAPI-1.18.0
SQLite version	
3.41.1
PDAL version	
2.5.5
PostgreSQL client version	
unknown
SpatiaLite version	
5.1.0
QWT version	
6.1.6
QScintilla2 version	
2.13.1
OS version	
Windows 10 Version 2009
			
Active Python plugins
db_manager	
0.1.20
grassprovider	
2.12.99
MetaSearch	
0.3.6
processing	
2.12.99

**Comment by agiudiceandrea** [comment]
@lgouzin, on my Windows 10 system, `print(pt.wkbType())` outputs `1001` using either QGIS LTR 3.34 or QGIS LTR 3.28 or QGIS LTR 3.22 or QGIS LTR 3.16.
It the QGIS Python API it is clearly stated that the output should be `1001`.
Not sure why in your system the output is `QgsWkbTypes.PointZ` using QGIS 3.32. Maybe there was a bug in QGIS 3.32.

**Comment by lgouzin** [comment]
Yeah ok, fair enough. Thanks for checking.
