### ISSUE TITLE
Decorations Misplaced Using Version 3.38.0-Grenoble

### ISSUE THREAD

**Issue by JeauxyPatton** [qgis/QGIS#58237]
### What is the bug or the crash?

Decorations such as the title label, the copyright label, etc. display correctly on the main viewer, but are misplaced when saving images using the temporal controller. See the images below for examples of this displacement. The bounding box/perspective of the images is correct, but the decorations are not in the correct place when saving. These decorations should all be right justified, and the copyright label should be along the bottom of the images. This happens on brand new projects as well as old projects. This issue appeared to start when QGIS was updated to version 3.38.0 on my machine. 
![20240227_Severe_TornadoPaths_Outlooks_GLM_FED_New0003](https://github.com/user-attachments/assets/54ffb574-38c4-48a3-836b-6437ccff2efa)
![20240227_Severe_TornadoPaths_Outlooks_GLM_FED_New0007](https://github.com/user-attachments/assets/57a9d811-a454-410f-8ab7-1d07657db6ff)
![20240401_Severe_LargeHail_Outlook_GLM16_MFA_0000](https://github.com/user-attachments/assets/27b138f1-f8a3-44f4-80c7-e94552b615af)

Issue persists with new user profiles. No external plugins are installed besides core plugins which cannot be uninstalled. 

### Steps to reproduce the issue

1. Import layer of any kind.
2. Add any decorations, such as title label.
3. Go to Temporal Controller.
4. Click on the save icon.
5. Save images.
6. See displaced decorations.

### Versions

QGIS version
3.38.0-Grenoble
QGIS code revision
37aa6188bc
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@JeauxyPatton, thanks for reporting. Please provide a minimal sample project and layer(s) an exact steps with which the issue does occur.
