### ISSUE TITLE
Road layer line overflow

### ISSUE THREAD

**Issue by lakma-rajini** [qgis/QGIS#58256]
### What is the bug or the crash?

Unfortunately my road layer lines are not aligning  to the center of the road. When i drew the lines, it worked perfectly and aligned to the middle of the road. There are more drawings and need a quick fix for this.

### Steps to reproduce the issue

![Screenshot 2024-07-27 185907](https://github.com/user-attachments/assets/7e8334ba-7bde-4ce1-bdab-2a7dcd37a30b)

### Versions

- QGIS version - 3.16, 3.34
- satellite view - http://mt0.google.com/vt/lyrs=s&hl=en&x={x}&y={y}&z={z}
- CRS -  WGS 84 EPSG:4326

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
Hi @lakma-rajini 
Inless I misunderstood your point, I fail to get where this is a QGIS issue. It certainly has to do with the scale at which you digitized the line and the one at which you are visualizing.
Zoom less and you'll get the feeling that they are aligned, or select the best scale for digitizing and redo cleanly the work.

**Comment by agiudiceandrea** [comment]
@lakma-rajini, moreover, Google Satellite imagery doesn't have a stable georeferencing, so it's likely that the currently available imagery from Google Satellite is shifted compared to the imagery used some time ago to digitize the lines.
