### ISSUE TITLE
Custom User-Agent header set incorrectly

### ISSUE THREAD

**Issue by MatzFan** [qgis/QGIS#58253]
### What is the bug or the crash?

If I set the custom User-Agent header in Network Options an incorrect value is used in HTTP requests.

### Steps to reproduce the issue

In any project which makes HTTP requests, go to Settings/Options and select Network options. Set the User-Agent to a custom value - e.g: "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0".

Open the Debugger panel, select a network request and copy as cURL. Observe that the custom User-Agent is merely prepended to the existing QGIS default, in my case "QGIS/33801/LMDE 6 (faye)" - so the new User-Agent header is "Mozilla/5.0 (Windows NT 10.0; rv:109.0) Gecko/20100101 Firefox/115.0 QGIS/33801/LMDE 6 (faye)"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.38.1-Grenoble | QGIS code revision | 3d4177afc6b
-- | -- | -- | --
Qt version | 5.15.8
Python version | 3.11.2
GDAL/OGR version | 3.6.2
PROJ version | 9.1.1
EPSG Registry database version | v10.076 (2022-08-31)
GEOS version | 3.11.1-CAPI-1.17.1
SQLite version | 3.40.1
PostgreSQL client version | 15.7 (Debian 15.7-0+deb12u1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.13.3
OS version | LMDE 6 (faye)
  |   |   |  
Active Python plugins
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.38.1-Grenoble
QGIS code revision
[3d4177afc6b](https://github.com/qgis/QGIS/commit/3d4177afc6b)
Qt version
5.15.8
Python version
3.11.2
GDAL/OGR version
3.6.2
PROJ version
9.1.1
EPSG Registry database version
v10.076 (2022-08-31)
GEOS version
3.11.1-CAPI-1.17.1
SQLite version
3.40.1
PostgreSQL client version
15.7 (Debian 15.7-0+deb12u1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.13.3
OS version
LMDE 6 (faye)

Active Python plugins
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
AFAIK, it's by design to always add a QGIS/version/OS string to the user agent string set in Settings->Options->Network->User-Agent:

https://github.com/qgis/QGIS/blob/5f6debbb6d2455a9f7ae5a0b12722d3954dfb450/src/core/network/qgsnetworkaccessmanager.cpp#L303-L307

See https://github.com/qgis/QGIS/commit/266c592c86fe41a76edc13baa817aee93794e401, https://issues.qgis.org/issues/7361.

**Comment by MatzFan** [comment]
Again, thanks for the quick response.

Very odd. I can see how it may be desirable to have the default behavior as setting the UA to a string identifying the QGIS version and host system, but cannot see why providing the ability to add a custom UA header would not override it. If that really is the intended functionality I'll close this issue and open a feature request to be able to override the UA header.
