### ISSUE TITLE
QGIS LTR QgsSQLiteExpressionCompiler access violation at idle

### ISSUE THREAD

**Issue by twest820** [qgis/QGIS#58254]
### What is the bug or the crash?

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00003100 (most recent call first):
  <no Python frame>
```

**Stack Trace**
```
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererCustomPainterJob::doRender :
QgsMapRendererCustomPainterJob::staticRender :
QgsMapRendererCustomPainterJob::renderSynchronously :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

### Steps to reproduce the issue

QGIS error popup while idling in background (was working in another app) so, particularly as a few unsaved edits in a couple GeoPackage layers open for edit were lost, this might be related to WAL operations. As with many QGIS crash log popups there is no reasonable repex so this'll need to be addressed by code inspection or improved logging. Stack is similar to #51262, #55137, #56881, #57168, #57265, and #58086.

Pretty typical project with probably ~75 GeoPackage and GeoTIFF/virtual raster layers, hundreds of 3.34.6 uptime hours on it without other issues. I've bumped to 3.34.9.

### Versions

QGIS Version: 3.34.6-Prizren
QGIS code revision: 623828f5
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.8.5
Running against GDAL: 3.8.5

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by nyalldawson** [comment]
There's nothing we can do here without a reproducible test case. I'll tag as feedback required.
