### ISSUE TITLE
version.txt out of date

### ISSUE THREAD

**Issue by multiquadric** [qgis/QGIS#58255]
### What is the bug or the crash?

version check info does not show latest release information
https://version.qgis.org/version.txt
https://version.qgis.org/version-ltr.txt 

### Steps to reproduce the issue

'''
% curl -s https://version.qgis.org/version.txt | grep Version | cut -d'|' -f 1 | cut -d' ' -f3
33800
% curl -s https://version.qgis.org/version-ltr.txt | grep Version | cut -d'|' -f 1 | cut -d' ' -f3
33408
'''

### Versions

3.34.9 and 3.38.1

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
See also https://github.com/qgis/QGIS-Hugo/issues/372.

**Comment by jef-n** [comment]
fixed with qgis/QGIS-Sysadmin-Documentation#61
