### ISSUE TITLE
QGIS ended unexpectedly

### ISSUE THREAD

**Issue by KToteng92** [qgis/QGIS#58265]
### What is the bug or the crash?

Python Stack Trace
Fatal Python error: Aborted

Current thread 0x00005998 (most recent call first):

Windows fatal exception: access violation

Current thread 0x00005998 (most recent call first):

Stack Trace

RtlEnterCriticalSection :
NCS::CMutex::Lock :
NCS::CMultiLock::LockExclusive :
NCS::CView::Close :
NCS::CView::Close :
NCS::CView::~CView :
NCS::CView::operator= :
CPLJSONArray::ConstIterator::operator* :
CPLJSONArray::ConstIterator::operator* :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
raise :
Py_gitversion :
raise :
abort :
_purecall purevirt.cpp:29
QGraphicsSceneEvent::widget :
QGraphicsSceneEvent::widget :
QGraphicsSceneEvent::widget :
QGraphicsSceneEvent::widget :
QGraphicsScene::items :
QGraphicsScene::destroyItemGroup :
QGraphicsScene::mouseMoveEvent :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGraphicsViewPrivate::mouseMoveEventHandler :
QgsLayoutView::mouseMoveEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.32.0-Lima
QGIS code revision: 311a8cb8a6
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.0
Running against GDAL: 3.7.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Sensitive

### Versions

3.32.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@KToteng92, thanks for reporting. QGIS 3.32 is no longer supported. If the issue still occur using a currently supported QGIS version, please create a new issue report describing the exact steps that lead to the crash.
