### ISSUE TITLE
Issue Clipping Raster using Mask Layer

### ISSUE THREAD

**Issue by Leamota** [qgis/QGIS#58263]
### What is the bug or the crash?

I am having trouble clipping raster using the mask layers. The error message I receive is" Unable to execute algorithm" and "Could not load source layer for MASK:D:/Earthengine_Data/output/test/mask.tif not found". I have used several windows systems, changed file path, yet the same error message and attach is the error message. 
Thanks for your assistance.  
[Error Message.docx](https://github.com/user-attachments/files/16416238/Error.Message.docx)

### Steps to reproduce the issue

Add Layer
Add Raster Layer
Create Mask:
- Raster Calculator ("raster@1 != 0" * 1)
Clip the Raster Using Mask Layer: 
- Go to Raster> Extraction>Clip Raster by Mask Layer
- Select your original raster layer as input layer
- Select the mask just created in previous step above as the mask layer
- Ensure the clipping mode is set to mask layer
- Set the No data value option to 0
- Check the box Match the resolution of the clipped raster to the resolution of the input mask
- Choose a file path to save the output and click run

### Versions

QGIS-OSGeo4W-3.38.1-1 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Leamota, thanks for reporting. Please provide a sample layer with which the issue does occur.

**Comment by Leamota** [comment]
Please see the attached screen shot. Uploading the sample satellite imagery .tiff format is not supported, and size is beyond the 25MB limit
![Screenshot (3)](https://github.com/user-attachments/assets/0af167aa-d845-4c7b-bca6-9317b8d12d98)
![QGIS_error_msg](https://github.com/user-attachments/assets/64bf7ec0-4a91-4354-8235-b58d580e6665)

**Comment by agiudiceandrea** [comment]
@Leamota, please provide: a sample layer with which the issue does occur, exact parameters' values used in the processing algorithm and the full processing log.

**Comment by nicogodet** [comment]
Mask layer should be a vector layer, not a raster one.

https://docs.qgis.org/3.34/en/docs/user_manual/processing_algs/gdal/rasterextraction.html#clip-raster-by-mask-layer

**Comment by nicogodet** [comment]
Closing as user miss use, not QGIS issue.

**Comment by agiudiceandrea** [comment]
@nicogodet it shouldn't be possibile to select a raster layer as mask layer.

**Comment by nicogodet** [comment]
@agiudiceandrea it's possible in every Qgs"MapLayer"ProcessingParameter to select a not allowed layer using "Select file..." and using "All files *.*" filter.
I'm not sure this is a behavior that can be changed.
