### ISSUE TITLE
Crash with a Model Designer when calling Extract Vertices with a null input

### ISSUE THREAD

**Issue by cecgeology** [qgis/QGIS#58267]
### What is the bug or the crash?

In my model designer I have various steps of adding fields etc then I extract by expression.  This results in two outputs, matching and non matching. For debugging I am outputting both layer (memory) and feed one of the results to the extract vertices algorithm. If the input is null, QGIS crashes instantly, with a fatal exception, stack trace attached.
Last thing I can see in the log is "Prepare algorithm:nativeextractvertices_1"
I reran the model designer with a non null input layer to extract vertices (in this case I chose the matching features which was valid, as opposed to the other layer) and model completed fine with example log like this:

Results:
  Matching: Matching_features_68df6811_b96e_43d3_b490_b64eafcc3322
  Non-Matching: NULL

which is why I think the null layer fed into the extract vertices algorithm is responsible

### Steps to reproduce the issue

Here are a few wkt line that can be pasted into qgis and the subset of the model that crashes the program (as model3 text)

wkt_geom	grad
LineStringZM (629083.05000000004656613 4337929.96999999973922968 555.89999999999997726 47184.44325010337342974, 629083.07999999995809048 4337928.5 555.96000000000003638 47117.18647116124338936)	45.74338594
LineStringZM (629357.69999999995343387 4338271.20000000018626451 590.19000000000005457 47263.94195219425455434, 629357.76000000000931323 4338271.28000000026077032 590.17999999999994998 47262.02842239118763246)	19.13529801
LineStringZM (629357.83999999996740371 4338270.29999999981373549 590.25 47264.64689960540272295, 629357.83999999996740371 4338270.21999999973922968 590.25 47265.03650662877043942)	4.870087788
LineStringZM (629357.82999999995809048 4338270.48000000044703484 590.25 47263.9364855708918185, 629357.82999999995809048 4338270.38999999966472387 590.25 47264.3132925881727715)	4.1867446
LineStringZM (629357.80000000004656613 4338270.75999999977648258 590.24000000000000909 47263.02046450693160295, 629357.81000000005587935 4338270.66000000014901161 590.25 47263.43087153025408043)	4.083702528

<!DOCTYPE model>
<Option type="Map">
  <Option type="Map" name="children">
    <Option type="Map" name="native:extractbyexpression_1">
      <Option type="bool" name="active" value="true"/>
      <Option name="alg_config"/>
      <Option type="QString" name="alg_id" value=""/>
      <Option type="QString" name="color" value=""/>
      <Option type="Map" name="comment">
        <Option type="QString" name="color" value=""/>
        <Option type="QString" name="component_description" value=""/>
        <Option type="double" name="component_height" value="60"/>
        <Option type="double" name="component_pos_x" value="0"/>
        <Option type="double" name="component_pos_y" value="0"/>
        <Option type="double" name="component_width" value="100"/>
        <Option type="bool" name="outputs_collapsed" value="true"/>
        <Option type="bool" name="parameters_collapsed" value="true"/>
      </Option>
      <Option type="QString" name="component_description" value=""/>
      <Option type="double" name="component_height" value="30"/>
      <Option type="double" name="component_pos_x" value="0"/>
      <Option type="double" name="component_pos_y" value="0"/>
      <Option type="double" name="component_width" value="200"/>
      <Option name="dependencies"/>
      <Option type="QString" name="id" value=""/>
      <Option name="outputs"/>
      <Option type="bool" name="outputs_collapsed" value="true"/>
      <Option type="bool" name="parameters_collapsed" value="true"/>
      <Option name="params"/>
    </Option>
    <Option type="Map" name="native:extractbyexpression_2">
      <Option type="bool" name="active" value="true"/>
      <Option name="alg_config"/>
      <Option type="QString" name="alg_id" value="native:extractbyexpression"/>
      <Option type="QString" name="color" value=""/>
      <Option type="Map" name="comment">
        <Option type="QString" name="color" value=""/>
        <Option type="QString" name="component_description" value=""/>
        <Option type="double" name="component_height" value="60"/>
        <Option type="double" name="component_pos_x" value="1858.9532619279455"/>
        <Option type="double" name="component_pos_y" value="972.6728334956183"/>
        <Option type="double" name="component_width" value="100"/>
        <Option type="bool" name="outputs_collapsed" value="true"/>
        <Option type="bool" name="parameters_collapsed" value="true"/>
      </Option>
      <Option type="QString" name="component_description" value="Extract high Gradients"/>
      <Option type="double" name="component_height" value="30"/>
      <Option type="double" name="component_pos_x" value="346.4410905550144"/>
      <Option type="double" name="component_pos_y" value="271.33446932814013"/>
      <Option type="double" name="component_width" value="200"/>
      <Option name="dependencies"/>
      <Option type="QString" name="id" value="native:extractbyexpression_2"/>
      <Option type="Map" name="outputs">
        <Option type="Map" name="big grad">
          <Option type="QString" name="child_id" value="native:extractbyexpression_2"/>
          <Option type="QString" name="color" value=""/>
          <Option type="Map" name="comment">
            <Option type="QString" name="color" value=""/>
            <Option type="QString" name="component_description" value=""/>
            <Option type="double" name="component_height" value="60"/>
            <Option type="double" name="component_pos_x" value="137"/>
            <Option type="double" name="component_pos_y" value="-75"/>
            <Option type="double" name="component_width" value="100"/>
            <Option type="bool" name="outputs_collapsed" value="true"/>
            <Option type="bool" name="parameters_collapsed" value="true"/>
          </Option>
          <Option type="QString" name="component_description" value="big grad"/>
          <Option type="double" name="component_height" value="30"/>
          <Option type="double" name="component_pos_x" value="504.91139240506277"/>
          <Option type="double" name="component_pos_y" value="383.4001947419665"/>
          <Option type="double" name="component_width" value="200"/>
          <Option type="invalid" name="default_value"/>
          <Option type="bool" name="mandatory" value="false"/>
          <Option type="QString" name="name" value="big grad"/>
          <Option type="QString" name="output_name" value="OUTPUT"/>
          <Option type="bool" name="outputs_collapsed" value="true"/>
          <Option type="bool" name="parameters_collapsed" value="true"/>
        </Option>
        <Option type="Map" name="low grad">
          <Option type="QString" name="child_id" value="native:extractbyexpression_2"/>
          <Option type="QString" name="color" value=""/>
          <Option type="Map" name="comment">
            <Option type="QString" name="color" value=""/>
            <Option type="QString" name="component_description" value=""/>
            <Option type="double" name="component_height" value="60"/>
            <Option type="double" name="component_pos_x" value="137"/>
            <Option type="double" name="component_pos_y" value="-75"/>
            <Option type="double" name="component_width" value="100"/>
            <Option type="bool" name="outputs_collapsed" value="true"/>
            <Option type="bool" name="parameters_collapsed" value="true"/>
          </Option>
          <Option type="QString" name="component_description" value="low grad"/>
          <Option type="double" name="component_height" value="30"/>
          <Option type="double" name="component_pos_x" value="504.8831548198634"/>
          <Option type="double" name="component_pos_y" value="336.79211295034065"/>
          <Option type="double" name="component_width" value="200"/>
          <Option type="invalid" name="default_value"/>
          <Option type="bool" name="mandatory" value="false"/>
          <Option type="QString" name="name" value="low grad"/>
          <Option type="QString" name="output_name" value="FAIL_OUTPUT"/>
          <Option type="bool" name="outputs_collapsed" value="true"/>
          <Option type="bool" name="parameters_collapsed" value="true"/>
        </Option>
      </Option>
      <Option type="bool" name="outputs_collapsed" value="true"/>
      <Option type="bool" name="parameters_collapsed" value="true"/>
      <Option type="Map" name="params">
        <Option type="List" name="EXPRESSION">
          <Option type="Map">
            <Option type="int" name="source" value="2"/>
            <Option type="QString" name="static_value" value="attribute('grad') >=  @maximum_gradient  "/>
          </Option>
        </Option>
        <Option type="List" name="INPUT">
          <Option type="Map">
            <Option type="QString" name="parameter_name" value="layer"/>
            <Option type="int" name="source" value="0"/>
          </Option>
        </Option>
      </Option>
    </Option>
    <Option type="Map" name="native:extractvertices_1">
      <Option type="bool" name="active" value="true"/>
      <Option name="alg_config"/>
      <Option type="QString" name="alg_id" value="native:extractvertices"/>
      <Option type="QString" name="color" value=""/>
      <Option type="Map" name="comment">
        <Option type="QString" name="color" value=""/>
        <Option type="QString" name="component_description" value=""/>
        <Option type="double" name="component_height" value="60"/>
        <Option type="double" name="component_pos_x" value="1518.4410905550144"/>
        <Option type="double" name="component_pos_y" value="892.3344693281401"/>
        <Option type="double" name="component_width" value="100"/>
        <Option type="bool" name="outputs_collapsed" value="true"/>
        <Option type="bool" name="parameters_collapsed" value="true"/>
      </Option>
      <Option type="QString" name="component_description" value="Extract vertices Big Grad"/>
      <Option type="double" name="component_height" value="30"/>
      <Option type="double" name="component_pos_x" value="667.4566699123654"/>
      <Option type="double" name="component_pos_y" value="223.76144109055508"/>
      <Option type="double" name="component_width" value="200"/>
      <Option name="dependencies"/>
      <Option type="QString" name="id" value="native:extractvertices_1"/>
      <Option type="Map" name="outputs">
        <Option type="Map" name="big grad points">
          <Option type="QString" name="child_id" value="native:extractvertices_1"/>
          <Option type="QString" name="color" value=""/>
          <Option type="Map" name="comment">
            <Option type="QString" name="color" value=""/>
            <Option type="QString" name="component_description" value=""/>
            <Option type="double" name="component_height" value="60"/>
            <Option type="double" name="component_pos_x" value="137"/>
            <Option type="double" name="component_pos_y" value="-75"/>
            <Option type="double" name="component_width" value="100"/>
            <Option type="bool" name="outputs_collapsed" value="true"/>
            <Option type="bool" name="parameters_collapsed" value="true"/>
          </Option>
          <Option type="QString" name="component_description" value="big grad points"/>
          <Option type="double" name="component_height" value="30"/>
          <Option type="double" name="component_pos_x" value="906.4566699123654"/>
          <Option type="double" name="component_pos_y" value="230.76144109055508"/>
          <Option type="double" name="component_width" value="200"/>
          <Option type="invalid" name="default_value"/>
          <Option type="bool" name="mandatory" value="false"/>
          <Option type="QString" name="name" value="big grad points"/>
          <Option type="QString" name="output_name" value="OUTPUT"/>
          <Option type="bool" name="outputs_collapsed" value="true"/>
          <Option type="bool" name="parameters_collapsed" value="true"/>
        </Option>
      </Option>
      <Option type="bool" name="outputs_collapsed" value="true"/>
      <Option type="bool" name="parameters_collapsed" value="true"/>
      <Option type="Map" name="params">
        <Option type="List" name="INPUT">
          <Option type="Map">
            <Option type="QString" name="child_id" value="native:extractbyexpression_2"/>
            <Option type="QString" name="output_name" value="FAIL_OUTPUT"/>
            <Option type="int" name="source" value="1"/>
          </Option>
        </Option>
      </Option>
    </Option>
  </Option>
  <Option type="Map" name="designerParameterValues">
    <Option type="QgsProcessingOutputLayerDefinition" name="big_grad">
      <Option type="Map">
        <Option type="Map" name="create_options">
          <Option type="QString" name="fileEncoding" value="windows-1252"/>
        </Option>
        <Option type="Map" name="sink">
          <Option type="bool" name="active" value="true"/>
          <Option type="int" name="type" value="1"/>
          <Option type="QString" name="val" value="TEMPORARY_OUTPUT"/>
        </Option>
      </Option>
    </Option>
    <Option type="QgsProcessingOutputLayerDefinition" name="big_grad_points">
      <Option type="Map">
        <Option type="Map" name="create_options">
          <Option type="QString" name="fileEncoding" value="windows-1252"/>
        </Option>
        <Option type="Map" name="sink">
          <Option type="bool" name="active" value="true"/>
          <Option type="int" name="type" value="1"/>
          <Option type="QString" name="val" value="TEMPORARY_OUTPUT"/>
        </Option>
      </Option>
    </Option>
    <Option type="QString" name="layer" value="Calculated_420afffb_0b95_48f2_b24a_320268296a05"/>
  </Option>
  <Option name="groupBoxes"/>
  <Option name="help"/>
  <Option type="QString" name="internal_version" value="Version2"/>
  <Option name="modelVariables"/>
  <Option type="QString" name="model_group" value=""/>
  <Option type="QString" name="model_name" value="Crash Test Model"/>
  <Option type="QString" name="outputGroup" value=""/>
  <Option name="outputOrder"/>
  <Option type="Map" name="parameterDefinitions">
    <Option type="Map" name="big_grad">
      <Option type="bool" name="create_by_default" value="true"/>
      <Option type="int" name="data_type" value="-1"/>
      <Option type="invalid" name="default"/>
      <Option type="invalid" name="defaultGui"/>
      <Option type="QString" name="description" value="big grad"/>
      <Option type="int" name="flags" value="0"/>
      <Option type="QString" name="help" value=""/>
      <Option type="Map" name="metadata">
        <Option type="QString" name="_modelChildId" value="native:extractbyexpression_2"/>
        <Option type="QString" name="_modelChildOutputName" value="big grad"/>
        <Option type="QString" name="_modelChildProvider" value="native"/>
      </Option>
      <Option type="QString" name="name" value="big_grad"/>
      <Option type="QString" name="parameter_type" value="sink"/>
      <Option type="bool" name="supports_append" value="false"/>
      <Option type="bool" name="supports_non_file_outputs" value="true"/>
    </Option>
    <Option type="Map" name="big_grad_points">
      <Option type="bool" name="create_by_default" value="true"/>
      <Option type="int" name="data_type" value="0"/>
      <Option type="invalid" name="default"/>
      <Option type="invalid" name="defaultGui"/>
      <Option type="QString" name="description" value="big grad points"/>
      <Option type="int" name="flags" value="0"/>
      <Option type="QString" name="help" value=""/>
      <Option type="Map" name="metadata">
        <Option type="QString" name="_modelChildId" value="native:extractvertices_1"/>
        <Option type="QString" name="_modelChildOutputName" value="big grad points"/>
        <Option type="QString" name="_modelChildProvider" value="native"/>
      </Option>
      <Option type="QString" name="name" value="big_grad_points"/>
      <Option type="QString" name="parameter_type" value="sink"/>
      <Option type="bool" name="supports_append" value="true"/>
      <Option type="bool" name="supports_non_file_outputs" value="true"/>
    </Option>
    <Option type="Map" name="layer">
      <Option type="List" name="data_types">
        <Option type="int" value="1"/>
      </Option>
      <Option type="invalid" name="default"/>
      <Option type="invalid" name="defaultGui"/>
      <Option type="QString" name="description" value="Layer"/>
      <Option type="int" name="flags" value="0"/>
      <Option type="QString" name="help" value=""/>
      <Option name="metadata"/>
      <Option type="QString" name="name" value="layer"/>
      <Option type="QString" name="parameter_type" value="vector"/>
    </Option>
    <Option type="Map" name="low_grad">
      <Option type="bool" name="create_by_default" value="false"/>
      <Option type="int" name="data_type" value="-1"/>
      <Option type="invalid" name="default"/>
      <Option type="invalid" name="defaultGui"/>
      <Option type="QString" name="description" value="low grad"/>
      <Option type="int" name="flags" value="8"/>
      <Option type="QString" name="help" value=""/>
      <Option type="Map" name="metadata">
        <Option type="QString" name="_modelChildId" value="native:extractbyexpression_2"/>
        <Option type="QString" name="_modelChildOutputName" value="low grad"/>
        <Option type="QString" name="_modelChildProvider" value="native"/>
      </Option>
      <Option type="QString" name="name" value="low_grad"/>
      <Option type="QString" name="parameter_type" value="sink"/>
      <Option type="bool" name="supports_append" value="false"/>
      <Option type="bool" name="supports_non_file_outputs" value="true"/>
    </Option>
    <Option type="Map" name="maximum_gradient">
      <Option type="int" name="data_type" value="1"/>
      <Option type="double" name="default" value="5"/>
      <Option type="invalid" name="defaultGui"/>
      <Option type="QString" name="description" value="Maximum Gradient"/>
      <Option type="int" name="flags" value="0"/>
      <Option type="QString" name="help" value=""/>
      <Option type="double" name="max" value="1.7976931348623157e+308"/>
      <Option name="metadata"/>
      <Option type="double" name="min" value="-1.7976931348623157e+308"/>
      <Option type="QString" name="name" value="maximum_gradient"/>
      <Option type="QString" name="parameter_type" value="number"/>
    </Option>
  </Option>
  <Option name="parameterOrder"/>
  <Option type="Map" name="parameters">
    <Option type="Map" name="layer">
      <Option type="QString" name="color" value=""/>
      <Option type="Map" name="comment">
        <Option type="QString" name="color" value=""/>
        <Option type="QString" name="component_description" value=""/>
        <Option type="double" name="component_height" value="60"/>
        <Option type="double" name="component_pos_x" value="1221.6666666666665"/>
        <Option type="double" name="component_pos_y" value="801.6666666666667"/>
        <Option type="double" name="component_width" value="100"/>
        <Option type="bool" name="outputs_collapsed" value="true"/>
        <Option type="bool" name="parameters_collapsed" value="true"/>
      </Option>
      <Option type="QString" name="component_description" value="layer"/>
      <Option type="double" name="component_height" value="34"/>
      <Option type="double" name="component_pos_x" value="350"/>
      <Option type="double" name="component_pos_y" value="172"/>
      <Option type="double" name="component_width" value="200"/>
      <Option type="QString" name="name" value="layer"/>
      <Option type="bool" name="outputs_collapsed" value="true"/>
      <Option type="bool" name="parameters_collapsed" value="true"/>
    </Option>
    <Option type="Map" name="maximum_gradient">
      <Option type="QString" name="color" value=""/>
      <Option type="Map" name="comment">
        <Option type="QString" name="color" value=""/>
        <Option type="QString" name="component_description" value=""/>
        <Option type="double" name="component_height" value="60"/>
        <Option type="double" name="component_pos_x" value="599.1441090555015"/>
        <Option type="double" name="component_pos_y" value="515.9055501460564"/>
        <Option type="double" name="component_width" value="100"/>
        <Option type="bool" name="outputs_collapsed" value="true"/>
        <Option type="bool" name="parameters_collapsed" value="true"/>
      </Option>
      <Option type="QString" name="component_description" value="maximum_gradient"/>
      <Option type="double" name="component_height" value="30"/>
      <Option type="double" name="component_pos_x" value="336"/>
      <Option type="double" name="component_pos_y" value="448"/>
      <Option type="double" name="component_width" value="200"/>
      <Option type="QString" name="name" value="maximum_gradient"/>
      <Option type="bool" name="outputs_collapsed" value="true"/>
      <Option type="bool" name="parameters_collapsed" value="true"/>
    </Option>
  </Option>
</Option>

### Versions

3.39.0-Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

## User Feedback

Running a model from the designer, crashed on starting up Extract vertices
last thing in the log window is "Prepare algorithm:nativeextractvertices_1

## Report Details

**Python Stack Trace**
```
Windows fatal exception: code 0x8001010d

Current thread 0x000087f4 (most recent call first):
  <no Python frame>
Windows fatal exception: access violation

Current thread 0x000087f4 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsExtractBinaryFieldAlgorithm::QgsExtractBinaryFieldAlgorithm :
QgsProcessingAlgorithm::prepare :
QgsProcessingModelAlgorithm::reattachAlgorithms :
QgsProcessingModelAlgorithm::reattachAlgorithms :
QgsProcessingModelAlgorithm::reattachAlgorithms :
QgsProcessingModelAlgorithm::reattachAlgorithms :
QMetaCallEvent::placeMetaCall :
QObject::event :
QgsApplication::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
PyInit__gui :
QgsModelDesignerDialog::run :
QgsModelChildDependenciesWidget::updateSummaryText :
QgsModelChildDependenciesWidget::updateSummaryText :
QgsModelChildDependenciesWidget::updateSummaryText :
QgsModelChildDependenciesWidget::updateSummaryText :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.39.0-Master
QGIS code revision: 5f6debbb6d
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.10.0dev-d4fd6215fc
Running against GDAL: 3.10.0dev-4e11f2e5c9

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

**Comment by agiudiceandrea** [comment]
@cecgeology, thanks for reporting. Please provide the minimal reproducible set of layer(s), model and parameter in order to replicate the issue.

**Comment by cecgeology** [comment]
Very sorry, I thought I had attached them before
[TestLinesWKT-Model.zip](https://github.com/user-attachments/files/16429093/TestLinesWKT-Model.zip)
any utm zone should work, and the lines are very short

**Comment by agiudiceandrea** [comment]
Thanks. It looks like the issue occurs with either "Extract vertices", "Extract specific vertices" or "Save vector features to file" processing algorithms.
