### ISSUE TITLE
Report view: attribute table with "show features visible within a map" and "show only features intersecting report feature" do an extremely slow full table scan

### ISSUE THREAD

**Issue by miceg** [qgis/QGIS#58274]
### What is the bug or the crash?

I have a report based on a point layer, and I want to find features in 5 other vector polygon layers which intersect my point layer.

The point data is stored in PostgreSQL, and the polygons are stored ArcGIS MapServer feature layers, accessed via the ArcGIS REST API.

While testing this, I've pre-filtered my point layer to only show a single point. One of the vector layers contains about 4M rows, the other three contain < 10K rows. There should be no more than 2 rows in any of the layers which intersect with the point.

My report is based on the point layer with:

* a small map (`Map 1`) centred on the point of interest, showing a ~200 metre radius
* attribute tables for each of the vector polygon layers, with:
  * ✅  show features visible within a map: `Map 1`
  * ✅  show only features intersecting report feature
  * limit to 2 results

When adding the attribute tables, QGIS runs the query each of the layers, and becomes unresponsive.

In the background, I can see QGIS making hundreds of HTTPS connections to each of the ArcGIS servers with `netstat`. If I run a profiler against QGIS, I can see it is spending most of its time in `QgsLayoutItemAttributeTable::getTableContents`, but is waiting on the network at `QgsArcGisRestQueryUtils::queryService`.

I'm unable to see the requests in the network debugging panel, as QGIS UI is completely unresponsive while it's querying.

In the event QGIS _doesn't_ execute the query immediately, and I'm able to save my project file, it's impossible to re-open the project file, because QGIS evaluates all reports when opening a project.

If I make copies of these layers locally (using GeoDatabase for the 4M row table, GeoPackage for the others), then the reports render, but still very slowly – around 30 seconds if including the largest table.

I'm not keen to figure out how long it would _actually_ take to load the layers over ArcGIS REST – it looks like QGIS is flooding the server with requests, and as I don't operate the servers in question, I don't think it's reasonable to take up those resources. 😅 

By comparison, using the "identify feature" tool on these tables as ArcGIS layers or local files takes less than a second, even for the largest layer – so something is very wrong with attribute tables in reports.

### Steps to reproduce the issue

As above

### Versions

```
QGIS version
3.38.1-Grenoble
QGIS code revision
3d4177afc6
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

`QgsLayoutItemAttributeTable::getTableContents` looks like it tries to pre-filter queries:

https://github.com/qgis/QGIS/blob/a4125bd463ca434979fcdfabb540069bfb07ad8c/src/core/layout/qgslayoutitemattributetable.cpp#L434-L485

But it also does a full table scan to filter features:

https://github.com/qgis/QGIS/blob/a4125bd463ca434979fcdfabb540069bfb07ad8c/src/core/layout/qgslayoutitemattributetable.cpp#L511-L545

This shouldn't be needed if the filters earlier on work correctly.

The performance characteristics, profile and network behaviour I'm seeing suggests that QGIS is doing a full table scan, and isn't taking advantage of indexes or protocol-specific query functionality.

This makes attribute tables in reports unusable for large data sets accessed over a network, and will flood the service with requests.

The number of HTTPS connections made makes me think `QgsArcGisRestQueryUtils` isn't using a connection pool. While it is a contributing factor, I don't think it's the problem to solve. 😄

**Comment by agiudiceandrea** [comment]
@miceg, thanks for reporting. Did the issue occurs using any previous version of QGIS? Providing a sample project + layers + exact steps to replicate the issue may be useful.
