### ISSUE TITLE
QGIS not recognizing CRS "EPSG:3301 - Estonian Coordinate System of 1997" in MapInfo mid/mif and tab formats

### ISSUE THREAD

**Issue by asko456** [qgis/QGIS#58283]
### What is the bug or the crash?

1) When exporting mid/mif file with CRS "EPSG:3301 - Estonian Coordinate System of 1997" to another mid/mif file with CRS "EPSG:3301 - Estonian Coordinate System of 1997" in QGIS the Layer Properties--> Information does not show exported layer's CRS --- it is "unnamed" instead of "EPSG:3301 - Estonian Coordinate System of 1997".

2) Possible QGIS bug: when opening mid/mif file, which was created in QGIS with CRS "EPSG:3301 - Estonian Coordinate System of 1997" (although is showing CRS as "unnamed") in MapInfo there is 50 mm gap between original mid/mif's (point 1) tab and tab from QGIS mid/mif. There is no gap when exporting files to and from (tab--> mid/mif; mid/mif to tab) within MapInfo without using QGIS.

### Steps to reproduce the issue

1) I open to QGIS a mid/mif file created in MapInfo Pro version 2023 (Release Build 142, Formatting Date 31.03.2021 13:45:00, Formatting number -12345.67). Mid/mif file name is "E_101_kivi_p_sel". 

Mid/mif file CRS  in QGIS is "EPSG:3301 - Estonian Coordinate System of 1997" (figure below).

![QGIS_origin_mif_info](https://github.com/user-attachments/assets/956ff55d-e4ad-4fc7-bde5-2ffc650179e7)

In MapInfo the mid/mif file projection (it can be seen when opening mif file in notepad) is also EPSG:3301 and is described as follows:

CoordSys Earth Projection 3, 115, "m", 24, 57.51755393056, 58, 59.33333333, 500000, 6375000 Bounds (-503054.5255, 5371945.474) (1503054.526, 7378054.526)

2) I export this mid/mif file to another mid/mif file in QGIS (Export--> Save Features As). Exported file is named as "E_101_kivi_sel_QGISmif". When exporting I'm using parameters like in figure below:

![FromQGIS_to_mif](https://github.com/user-attachments/assets/b26c60a5-ba21-4633-a7f9-fc424f7076e8)

3) I open previously exported file "E_101_kivi_sel_QGISmif" to QGIS. **Possible bug:** Layer Properties--> Information does not show  layers CRS, it is "unnamed" instead of "EPSG:3301 - Estonian Coordinate System of 1997" (figure below).

![QGISmif_info](https://github.com/user-attachments/assets/81bf69d4-2c41-49cf-88b7-0d34c16015e8)

4) Now I export (Export--> Save Features As) the first mid/mif file ("E_101_kivi_p_sel") to .tab file in QGIS with EPSG3301 (figure below). The exported file is named as "E_101_kivi_QGIS_tab".

![QGIS_origin_to_tab](https://github.com/user-attachments/assets/123f82c6-29da-4041-9c9f-c8e8b946fe2d)

5) I open previously exported file "E_101_kivi_QGIS_tab" to QGIS. **Possible bug:** CRS is "unnamed" and measured gap between previous layers is 10 mm. Maybe this behavior is explained with issues described [here.](https://gdal.org/drivers/vector/mitab.html#vector-mitab). Although I tried also custom bounds when exporting in QGIS without results.

6) I guess this is not an QGIS issue (?), but when opening mid/mif file "E_101_kivi_sel_QGISmif" (which was created in QGIS, point 4) in MapInfo (MapInfo saves it as .tab before opening, that .tab name is "E_101_kivi_sel_QGISmif.tab") there is 50 mm gap between first mid/mif's ("E_101_kivi_p_sel") tab and "E_101_kivi_sel_QGISmif" (figure below).

![Origin_vs_QGIS_miftab_measure](https://github.com/user-attachments/assets/aa18fb8b-b2f4-451e-af2a-520ec4e6632b)

When opening "E_101_kivi_sel_QGISmif" mif file in Notepad the projection is as follows: 

CoordSys Earth Projection 3, 104, "m", 24, 57.5175539305556, 59.3333333333333, 58, 500000, 6375000

7) QGIS project with files are here:
[Files.zip](https://github.com/user-attachments/files/16451825/Files.zip)

### Versions

QGIS version
3.38.1-Grenoble
QGIS code revision
3d4177afc6
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by asko456** [comment]
Steps to reproduce the issue, point 1, mid/mif file "E_101_kivi_p_sel" is here:

[E_101_kivi_p_sel.zip](https://github.com/user-attachments/files/16444959/E_101_kivi_p_sel.zip)

**Comment by nyalldawson** [comment]
This is an upstream (gdal) issue. (Ping @rouault )
