### ISSUE TITLE
QGIS uninstalling automatically

### ISSUE THREAD

**Issue by KathrynRoseW** [qgis/QGIS#58282]
### What is the bug or the crash?

Hello,

QGIS has been uninstalling automatically the last couple of weeks. It seems that QGIS usually updates itself - but sometimes fails to install the new version, yet the old one is removed still. Does anyone have the same issue or know how to avoid this happening? This is happening on Windows 11, and I am installing QGIS from the internet manually.

### Steps to reproduce the issue

This is happening in the background - without any action taken. When I restart the computer from time to time, it is gone. 

### Versions

 I am using QGIS 3.38.0 as of now.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@KathrynRoseW, thanks for reporting. Please provide the OS name and version and all the QGIS info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot."). Please also describe how did you install QGIS on such OS.
AFAIK QGIS doesn't either update or uninstall itself automatically.

**Comment by KathrynRoseW** [comment]
Thank you so much! I have updated my report form with the info request, though not the QGIS version info as it has already uninstalled and has yet to install again. It has happened the last couple of weeks.

**Comment by agiudiceandrea** [comment]
@KathrynRoseW did you install QGIS using the OSGeo4W stand-alone all-in-one Installer QGIS-OSGeo4W-3.38.0-1.msi or the OSGeo4W Network Installer osgeo4w-setup.exe? May it happens that any antivirus software installed on your system be responsible for uninstalling QGIS?
QGIS doesn't have the ability to automatically uninstall or update itself automatically.

**Comment by KathrynRoseW** [comment]
Hi Andrea, I used the all-in-one installer QGIS-OSGeo4W-3.38.0-1.msi. It thought so too that my antivirus system is responsible for uninstalling QGIS, as it is patching QGIS, but I suspect that it goes wrong when it needs to install the new patch/version. I have e-mailed them about this, and they couldn't give me an answer as to why this happens repeatedly. Thank you so much for your help!

**Comment by TheITcrowd123** [comment]
Buongiorno, ho lo stesso problema si rimuove in automatico ( versione 3.40.9) ci sono sviluppi in merito ? mi succede una volta a settimana

**Comment by jef-n** [comment]
> Buongiorno, ho lo stesso problema si rimuove in automatico ( versione 3.40.9) ci sono sviluppi in merito ? mi succede una volta a settimana

No.  Did you see the reference to #58698?
