### ISSUE TITLE
Pantalla en blanco

### ISSUE THREAD

**Issue by Lydiatortosa** [qgis/QGIS#58297]
### What is the bug or the crash?

Cuando cargo un proyecto, la pantalla se queda en blanco, no se ven las capas ni la cartografía. No se que hacer, así que creo otro proyecto cargando otra vez lo mismo y guardándolo con el mismo nombre.

### Steps to reproduce the issue

también tengo el problema que al crear planos, se queda bloqueado y tengo que cerrar la vista continuamente y abrirla.

### Versions

3.32

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

quisiera saber si hay forma de solucionar el problema sin tener que crear otra vez el proyecto.
y porque se queda bloqueado cuando genero planos.

**Comment by agiudiceandrea** [comment]
@landryb QGIS 3.32 is no longer supported. Please try if the issue still occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it still occurs also running a currently supported QGIS version and using a new QGIS user profile, please open a create a new issue report with a meaningful title and description in English, providing a project and layer(s) and exact steps to replicate the issue.
