### ISSUE TITLE
Add Style>Save/Load Style to context menu

### ISSUE THREAD

**Issue by roscopoppolis** [qgis/QGIS#58306]
### Feature description

Add the Style>Load/Save Style dropdown in the Properties menu to the context menu, alongside Copy/Paste Symbol. Obviously not critical, but it would save a lot of clicks! 
Thanks for all yall do.

**Comment by fiddlersfan** [comment]
This is a similar feature request as #55165. Maybe the closed PR can be reactivated and supplemented.

**Comment by alexbruy** [comment]
Duplicates #55165.
