### ISSUE TITLE
No filtered color settings when opening "select color" dialog the first time

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#58302]
### What is the bug or the crash?

A minor issue but this is what I got the first time I ever  open the dialog (i.e. never interacted with the color model combobox)
![image](https://github.com/user-attachments/assets/71b9a2f1-7f7a-478b-9e3d-1cd0394401e3)

### Steps to reproduce the issue

see above

### Versions

master 3.39 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
Actually this occurs every time I click to add a new color (from Project properties > Colors > +)

**Comment by nyalldawson** [comment]
FYI @troopa81
