### ISSUE TITLE
QGIS keeps crashing (unresponsive) for a particular project

### ISSUE THREAD

**Issue by Oisin-JK** [qgis/QGIS#58300]
### What is the bug or the crash?

I have a project containing various geopackage layers and virtual layers.
QGIS repeatedly becomes unresponsive. I'm nmot certain, but it seems ot happen when saving the project, or committing edits to a layer - I'm mostly editing a single point layer, which has a non-spatial child relation.

I get no error messages.  Log files in C:\Users\xxxx\AppData\Local\Temp are empty. I've tried creating a log using Mattheus Kuhn's script from here: https://gis.stackexchange.com/questions/84790/where-does-qgis-write-its-error-log-messages. But no log file is produced.

### Steps to reproduce the issue

Project specific. I'm unable to share the project as its commercially sensitive.

### Versions

QGIS version
3.34.9-Prizren (and 3.38.1-Grenoble)
QGIS code revision
cbbc7bdf
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

How am I able to trace the cause of the crash?

**Comment by agiudiceandrea** [comment]
@Oisin-JK, thanks for reporting. As correctly stated at https://gis.stackexchange.com/a/148353 (see also https://qgis.org/pyqgis/master/core/QgsLogger.html), QGIS outputs debug messages only if it is a debug build. On Windows, debug builds can be installed using the [OSGeo4W Network installer](https://qgis.org/resources/installation-guide/#osgeo4w-installer) or using a weekly snapshot [standalone installer](https://qgis.org/resources/installation-guide/#standalone-installers).
Have you actually tried if the issue occurs also using a new QGIS user profile?
