### ISSUE TITLE
GRASS r.colors can only be used with named color tables.

### ISSUE THREAD

**Issue by jedfrechette** [qgis/QGIS#58301]
### What is the bug or the crash?

It is a bug that prevents usage of some of the tool's features.

### Steps to reproduce the issue

1. Open the GRASS/Raster/r.colors tool and select an input raster.
2. Set the named color table to `[Not Selected]` or `not selected` (I'm not sure what the intended difference here is).
3. Chose another raster to copy a color table from.
4. Run the tool.
5. Inspect the log and notice that it has failed for 2 reasons. First the value set in step 2 was passed to the `color` parameter and was not recognized. Second the `color`, `rules`, and `raster` parameters are mutually exclusive so in this scenario no value should be passed to `color`. 

The same issue also prevents using r.colors with the `color rules` or `color rules file` options because those parameters also need to be passed in by themselves without also passing a value to `color`.

### Versions

QGIS version
3.38.0-Grenoble
QGIS code revision
37aa6188bc
Qt version
8.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
9.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
geoez
0.1
firstaid
3.2.0
nominatim
1.4.5
plugin_reloader
0.9.4
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@jedfrechette, thanks for reporting. Please check if the proposed fix https://github.com/qgis/QGIS/pull/58307 actually fixed the issues.

**Comment by jedfrechette** [comment]
@agiudiceandrea thanks for the quick fix. I don't have a build environment setup for QGIS so will likely need to wait until I can test with a weekly build that includes your fix. The Windows build generated for your PR doesn't seem to include the GRASS tools so I can't test with that..

**Comment by jedfrechette** [comment]
Ahh, I didn't notice this was a Python only fix. Testing your changes, the behavior of the different modes are as I would expect. The only change I might make would be to have the help message be even more explicit:

"The color table, color rules and raster map parameters are mutually exclusive. You need to set one and only one of them!"

As you noted in the PR r.colors does have some other usability issues:

1. Not being able to save to a temp directory.
2. Always saving to an output file named like `map_0` with no extension.
3. Providing the options for both `[Not selected]` and `not selected` in the Color table menu.

I'm not sure how general those are to other GRASS integrations, but in any case they should probably be separate issues as your changes do fix the core functionality of r.colors.

Thanks again,

**Comment by agiudiceandrea** [comment]
> "The color table, color rules and raster map parameters are mutually exclusive. You need to set one and only one of them!"

Thanks for the suggestion. Addressed in the new version of the PR.

**Comment by agiudiceandrea** [comment]
> 1. Not being able to save to a temp directory.

 See https://github.com/qgis/QGIS/issues/58345.
