### ISSUE TITLE
Relation between colors model lists when setting a color gradient ramp

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#58324]
### What is the bug or the crash?

I don't know whether this is a bug, a feature request or a question...I don't know much on the topic. but here we go.
![image](https://github.com/user-attachments/assets/a11f6859-ad5c-4845-bba6-e636c53a1d1b)

In the above image, should there be a relation between the colors model set? Or in other words, assuming I have CMYK colors, is it coherent to have RGB interpolation? Or should CMYK be an option in this list also?

### Steps to reproduce the issue

The above is the dialog for adding a gradient color ramp from the style manager

### Versions

<table width='100%' align='center'><tr><td colspan="2"><b>Libraries</b></td><tr><td>QGIS version</td><td>3.39.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/4dfd18ff7dd">4dfd18ff7dd</a></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.11.2</td></tr><tr><td>GDAL/OGR version</td><td>3.6.2</td></tr><tr><td>PROJ version</td><td>9.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.076 (2022-08-31)</td></tr><tr><td>GEOS version</td><td>3.11.1-CAPI-1.17.1</td></tr><tr><td>SQLite version</td><td>3.40.1</td></tr><tr><td>PDAL version</td><td>2.6.0</td></tr><tr><td>PostgreSQL client version</td><td>15.7 (Debian 15.7-0+deb12u1)</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.13.3</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 12 (bookworm)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MemoryLayerSaver</td><td>5.0.2</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
CMYK gradiant are on my todo list, but I didn't spot that UI issue. I'll fix this.
