### ISSUE TITLE
"Colors model" drop-down doesn't default to the one set in Project properties

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#58323]
### What is the bug or the crash?

In Project properties --> Colors tab, you can set a color model (https://github.com/qgis/QGIS/blame/893da91e3211158f70fdad4ebf37e3d99132f310/src/ui/qgsprojectpropertiesbase.ui#L1595C72-L1596C28)
> Color model used as default when selecting a color in the whole application.
Any color defined in a different color model than the one specified here will be converted to this color model when exporting a layout.

Afaict, it is not used as default, RGB model seems to always be the default when you try to add a color

### Steps to reproduce the issue

Open Project properties --> Colors tab and set the model color to CMYK and apply
You can now try to add a new color, be it from the same project properties dialog or from the style manager, the color model that is proposed by default is the RGB one.

### Versions

<table width='100%' align='center'><tr><td colspan="2"><b>Libraries</b></td><tr><td>QGIS version</td><td>3.39.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/4dfd18ff7dd">4dfd18ff7dd</a></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.11.2</td></tr><tr><td>GDAL/OGR version</td><td>3.6.2</td></tr><tr><td>PROJ version</td><td>9.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.076 (2022-08-31)</td></tr><tr><td>GEOS version</td><td>3.11.1-CAPI-1.17.1</td></tr><tr><td>SQLite version</td><td>3.40.1</td></tr><tr><td>PDAL version</td><td>2.6.0</td></tr><tr><td>PostgreSQL client version</td><td>15.7 (Debian 15.7-0+deb12u1)</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.13.3</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 12 (bookworm)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>MemoryLayerSaver</td><td>5.0.2</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

maybe is this related to #58302?

**Comment by troopa81** [comment]
Yet to be done indeed :+1:
