### ISSUE TITLE
Adding an XYZ layer with a broken URL causes a crash

### ISSUE THREAD

**Issue by Malvineous** [qgis/QGIS#58322]
### What is the bug or the crash?

When adding a bad XYZ URL, QGIS crashes

### Steps to reproduce the issue

1. Add layer, XYZ
2. Paste in URL `http://mt3.google.com/mapslt?x={x}&y={y}&z={z}` and click Add
3. Observe layer is added but with an error
4. Right click on the layer and choose properties (e.g. as if you were trying to fix the URL)
5. QGIS freezes for a few moments then crashes

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.38.0-Grenoble | QGIS code branch | Release 3.38
-- | -- | -- | --
Qt version | 5.15.14
Python version | 3.12.4
GDAL/OGR version | 3.9.0
PROJ version | 9.4.1
EPSG Registry database version | v11.006 (2024-03-13)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.46.0
Compiled against PDAL | 2.7.1 | Running against PDAL | 2.7.2
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
latlontools | 3.6.20
MetaSearch | 0.3.6
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99

</body></html>QGIS version
3.38.0-Grenoble
QGIS code branch
[Release 3.38](https://github.com/qgis/QGIS/tree/release-3_38)
Qt version
5.15.14
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.1
EPSG Registry database version
v11.006 (2024-03-13)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.46.0
Compiled against PDAL
2.7.1
Running against PDAL
2.7.2
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Arch Linux

Active Python plugins
latlontools
3.6.20
MetaSearch
0.3.6
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by NyakudyaA** [comment]
Maybe this fix needs to be added for xyz layers https://github.com/qgis/QGIS/pull/58159

**Comment by nyalldawson** [comment]
That fix isn't in 3.38.0, but it will also fix this crash.

Closing as already fixed.
