### ISSUE TITLE
Georeferencer Dialog Not Working with 3.34.8 LTR

### ISSUE THREAD

**Issue by LucySaluki** [qgis/QGIS#58341]
### What is the bug or the crash?

The enter coordinates window does not open properly in 3.34.8 - please note this is not on all computers, two members of my team have seen the issue, the other two but (as far as I am am aware) we all have the same set up.
![georeferencer](https://github.com/user-attachments/assets/62afa676-bce7-4b19-a862-3f8d7b253f80)

### Steps to reproduce the issue

adding control points when georeferencing - consistent every time.

### Versions

3.34.8 only (we have reverted to 3.28 and it works fine in that)

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

we always only download the LTR.

**Comment by agiudiceandrea** [comment]
@LucySaluki, thanks to reporting. Please provide the full QGIS version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.").

**Comment by LucySaluki** [comment]
QGIS version
3.34.8-Prizren
QGIS code revision
91642333
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

**Comment by agiudiceandrea** [comment]
@LucySaluki, does the issue occurs also using a a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)?
