### ISSUE TITLE
QGIS takes almost 1min to open to UI. Older versions taking <10 secs

### ISSUE THREAD

**Issue by weca-theo** [qgis/QGIS#58348]
### What is the bug or the crash?

I've recently downloaded and installed QGIS LTR 3.34.9. This exists alongside an older LTR of 3.22.8 and 3.16.6 on the same machine.
Without an existing QGIS interface or process running, here is how long QGIS takes to open the initial UI (not opening a project).

- 3.34.9 = 55 seconds (including a 50 second wait for the splash screen to appear)
- 3.22.9 = 9 seconds (including <1 second wait for the splash screen to appear)
- 3.16.6 = 10 seconds (including <1 second wait for the splash screen to appear)

I need to roll out a new QGIS upgrade (eg. 3.34.9) to over 100 users, but this wait time is unacceptable compared to what they're used to. The debugger timing logs don't help at all, as they only record the time between the splash appearing and the UI appearing, which in both versions is <5 seconds, so this isn't the main issue. Instead the issue seems to be surrounding whatever QGIS (3.34.9) is doing between a user clicking the launcher icon and the green splash screen appearing. Any ideas what this could be?

I only have 2 third party plugins installed (Get WKT and QuickWKT which are v lightweight and don't contribute to any significant load time)

### Steps to reproduce the issue

1. Make sure all QGIS instances are closed.
2. Open QGIS 3.34.9
3. observe how long it takes to a) see the splash screen appear and b) see the UI/home screen appear)
4. repeat process for an earlier version of QGIS, like 3.22.8

### Versions

QGIS version
3.22.8-Białowieża
QGIS code revision
8d5e9761df
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.0
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Laptop is a Dell Latitude 3510 and is more than capable of loading QGIS.

**Comment by agiudiceandrea** [comment]
@weca-theo, thanks for reporting. Please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) and provide the full QGIS version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot").

You can use the [Debugging/Development Tools Panel](https://docs.qgis.org/3.34/en/docs/user_manual/introduction/general_tools.html#debug-dev-tools) in order to try to understand why QGIS takes so much time to start.

Maybe you are experiencing the same issue already previously reported at https://github.com/qgis/QGIS/issues/57671.
Such issue has been allegedly fixed. The fix https://github.com/qgis/QGIS/pull/58250 will be available since QGIS 3.34.10.

**Comment by weca-theo** [comment]
> @weca-theo, thanks for reporting. Please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles) and provide the full QGIS version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot").
> 
> You can use the [Debugging/Development Tools Panel](https://docs.qgis.org/3.34/en/docs/user_manual/introduction/general_tools.html#debug-dev-tools) in order to try to understand why QGIS takes so much time to start.
> 
> Maybe you are experiencing the same issue already previously reported at #57671. Such issue has been allegedly fixed. The fix #58250 will be available since QGIS 3.34.10.

ah interesting... using a new blank user profile reduces the boot time from 55 seconds to under 10 seconds. Obviously, I need to use my existing profile, so using a blank profile isn't a workaround I can stick to. I hope this is indeed fixed in the next minor version release later this month.
