### ISSUE TITLE
Variable distance buffer doesn't work in QGIS Modeler

### ISSUE THREAD

**Issue by GuillaumeBertho** [qgis/QGIS#58349]
### What is the bug or the crash?

In QGIS, it is possible to create a buffer whose size depends on a value of a predetermined field 
![image](https://github.com/user-attachments/assets/a787a22c-ad4b-4cf4-a7ec-c1a357b0944d)

In the modeler, the same process should work like this :
Distance buffer size set up on PreCalculated value : attribute('Field_name_here')
![image](https://github.com/user-attachments/assets/33e1adc0-bd78-4880-840d-a830fe8cca20)

but it won't.
Nothing happens, polygons aren't buffered. 

### Steps to reproduce the issue

See above

### Versions

QGIS 3.38 and earlier versions (windows 11)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
User issue, use the same input as you do normally, not the precalculated value. Check the doc to see why this is not what you want: https://docs.qgis.org/3.34/en/docs/user_manual/processing/modeler.html#definition-of-the-workflow

**Comment by GuillaumeBertho** [comment]
No you can't do it normally.
The list is empty if you do it this way.

![image](https://github.com/user-attachments/assets/9be70d42-5eec-4c8b-9869-6e3d9703451f)

**Comment by roya0045** [comment]
Yes, just click edit and type the name.
Model alg shouldn't present you with a list of field as its assumed that the input of a model can be anything, so there's not reason to access any specific layers to retreive the fields. 
You could also use another input to your model to get the field and then eval it in the field expression. Which makes more sense  and would be safer than a static field name. Just need to eval the field name. 

Regardless this is not a bug, I get why this might not seem intuitive at first.

**Comment by GuillaumeBertho** [comment]
I made differents tests and it's definitely a bug :

![image](https://github.com/user-attachments/assets/45af92a2-da7b-4cd3-89ef-e7c111a568e6)
![image](https://github.com/user-attachments/assets/57f09fd4-99be-4d0f-ab29-0e6344b32322)
"Field not found" although it exists in the input layer....

**Comment by GuillaumeBertho** [comment]
My bad !
Not intuitive indeed, especially the message "Field not found"..
![image](https://github.com/user-attachments/assets/ec145d5f-8733-4cde-8919-4fe93b5a3490)

![image](https://github.com/user-attachments/assets/ed66e5cf-b204-4b26-bef6-0520d82537c4)

I tried before but i added an @....
Thanks a million !!

**Comment by roya0045** [comment]
Dont forget that in expressions doublequotes(") indicate a field name and single quote (')are for strings . Imo it's safer to indicate field this way instead of having it raw, especially for anything more complex.
