### ISSUE TITLE
Falha no Python

### ISSUE THREAD

**Issue by IohanaSilva** [qgis/QGIS#58344]
### What is the bug or the crash?

Quando abro o software QGIS aparece a informação de que houve um erro ao executar o código Python.

### Steps to reproduce the issue

Abrir o software.

### Versions

A versão que normalmente uso é a 3.28.6, tentei usar a mais atualizada, mas apareceu o mesmo erro.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Segue um print da tela.
![Captura de tela 2024-08-08 085427](https://github.com/user-attachments/assets/36cc57a0-c755-4fe2-b9e7-d4a49043f94c)

**Comment by jef-n** [comment]
English please.
The error message is incomplete.  From what's visible it tries to load something using pandas and is missing (python5-)html5lib.  I guess it's a plugin producing the error, so you should identify, which one (by looking at the full message) and file an issue there (or maybe revisit it's documentation as that might have instruction what (else) needs to installed to get it going)
