### ISSUE TITLE
Crash when layer with reused QgsFillSymbol is removed

### ISSUE THREAD

**Issue by robbertbloem** [qgis/QGIS#58358]
### What is the bug or the crash?

I used Python to import two Shapefiles and use a custom QgsFillSymbol, the same for both layers (`asymbol`). The code below works fine, until I remove one of the two layers. After confirming I want to remove a legend entry, QGIS crashes. 

When I use different QgsFillSymbols for the two layers (`asymbol` and `bsymbol`) this does not happen. 

### Steps to reproduce the issue

1. open QGIS
2. open Python console
3. run `exec(Path('.../bug_report_v1.py').read_text())`
4. choose one of the two layers in the Layers-panel
5. click on "Remove Layer/Group"
6. Confirm you want to remove the layer. 
7. Crash. 

The code below reliably reproduces the crash. When the second-to-last line is commented and the last line uncommented, QGIS does not crash.

For debugging I used a Shapefile from the training https://docs.qgis.org/3.34/en/docs/training_manual/foreword/intro.html 

The crash also occurs when using different Shapefiles. 

bug_report_v1.py:
```python
path = "" # I used "QGIS-Training-Data-master/exercise_data/shapefile/protected_areas.shp"

asymbol = QgsFillSymbol.createSimple({"outline_style": "solid", "fill_color": '255,255,0,255', "outline_width": 2, "outline_color": '255,0,0,255', "stroke_width": 2}) 

bsymbol = QgsFillSymbol.createSimple({"outline_style": "solid", "fill_color": '255,255,0,255', "outline_width": 2, "outline_color": '255,0,0,255', "stroke_width": 2}) 

alayer = QgsVectorLayer(path, "Layer A", "ogr")
if not alayer.isValid():
    print("Buffer A is NOT valid")
else:
    print("Buffer A is valid")
    alayer = QgsProject.instance().addMapLayer(alayer)
alayer.renderer().setSymbol(asymbol)

blayer = QgsVectorLayer(path, "Layer B", "ogr")
if not blayer.isValid():
    print("Buffer B is NOT valid")
else:
    print("Buffer B is valid")
    blayer = QgsProject.instance().addMapLayer(blayer)
blayer.renderer().setSymbol(asymbol) # crashes when a layer is removed from the legend
# blayer.renderer().setSymbol(bsymbol) # works fine
```

### Versions

QGIS version
3.34.9-Prizren
QGIS code revision
[cbbc7bdfb66](https://github.com/qgis/QGIS/commit/cbbc7bdfb66)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 14.6

Active Python plugins
QuickOSM
2.2.3
quick_map_services
0.19.34
pdokservicesplugin
5.1.1
HCMGIS
24.1.12
OSMDownloader
1.0.3
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@robbertbloem, see https://qgis.org/pyqgis/3.34/core/QgsSingleSymbolRenderer.html#qgis.core.QgsSingleSymbolRenderer.setSymbol:
`Ownership of the symbol is transferred to the renderer.`

**Comment by agiudiceandrea** [comment]
@robbertbloem, see https://qgis.org/pyqgis/3.34/core/QgsSingleSymbolRenderer.html#qgis.core.QgsSingleSymbolRenderer.setSymbol:
`Ownership of the symbol is transferred to the renderer.`
and https://github.com/qgis/QGIS/issues/54804#issuecomment-1743965738, https://github.com/qgis/QGIS/issues/42317#issuecomment-802451406.

**Comment by robbertbloem** [comment]
It may not be a bug (or at least not something that can easily be solved), but maybe this can be explained in the documentation? I have a lot of Python programming experience but I'm not a programmer. I think "Ownership of the symbol is transferred to the renderer" does not explain why QGIS crashes. Maybe it can be added as a note (or maybe multiple notes) in the PyQGIS Cookbook?

**Comment by agiudiceandrea** [comment]
I suggest to write to the qgis-developer mailing-list https://lists.osgeo.org/mailman/listinfo/qgis-developer.
See also https://www.mail-archive.com/qgis-developer@lists.osgeo.org/msg24459.html.
