### ISSUE TITLE
Failed To Parse Capabilities 

### ISSUE THREAD

**Issue by Angus-Fiona** [qgis/QGIS#58362]
### What is the bug or the crash?

Connection to our WMTS aerial photography provider no longer works on QGIS 3.36.1 

it now generates the error 'Failed to Parse Capabilities'. 

The URL hasn't changed, but once we updated our QGIS version, it stopped working. I've been in touch with our provider and they've confirmed that nothing has changed on their end. 

### Steps to reproduce the issue

As above

### Versions

QGIS version
3.36.1-Maidenhead
QGIS code revision
3e589453
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
BulkVectorExport
1.1
Discovery
2.5.8
floodrisk2
0.7
FreehandRasterGeoreferencer
0.8.3
pgversion
3.4.0
pg_metadata
1.2.2
qfieldsync
v4.6.0
quick_map_services
0.19.33
SelectWithin
0.4
slyr_community
5.0.0
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Angus-Fiona, if the WMTS previously worked using QGIS 3.36.1 but now it doesn't work using the same QGIS 3.36.1 version, then it's very unlikely that the issue is on the QGIS side. Anyway QGIS 3.36 is no longer supported. Please actually try if the issue occurs running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and please provide the WMTS' URL and all the parameter used for the WMTS connection.

**Comment by agiudiceandrea** [comment]
@Angus-Fiona, QGIS 3.36 is no longer supported. Please actually try if the issue occurs running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and please provide the WMTS' URL and all the parameter used for the WMTS connection.
