### ISSUE TITLE
QgsMessageLog.logMessage: argument notifyUser doesn't change anything

### ISSUE THREAD

**Issue by pers-ephone** [qgis/QGIS#58367]
### What is the bug or the crash?

A call to QgsMessageLog.logMessage with notifyUser=True seem to be the same as with notifyUser=False whatever the level.

The doc states "If notifyUser is True, then the message should be brought to the user’s attention by various UI hints.", one would expect a call to the message bar, a forced opening of the message log window, or other direct and systematic communication to the user. For now as a plugin dev i have to consider this argument as always false and manage all communication to the user.

The argument seem to only allow [this messageReceived signal](https://github.com/qgis/QGIS/blob/29bf082ed38707760356491a03c0e810571442fb/src/core/qgsmessagelog.h#L76) to be sent and not in the case of an INFO message. So info messages fully ignore the argument, and otherwise i don't know what uses the signal but i see no difference in use.

### Steps to reproduce the issue

in python console:
`QgsMessageLog.logMessage("test", "tab", Qgis.Warning, False)`
`QgsMessageLog.logMessage("test", "tab", Qgis.Warning, True)`

`QgsMessageLog.logMessage("test", "tab", Qgis.Info, False)`
`QgsMessageLog.logMessage("test", "tab", Qgis.Info, True)`

`QgsMessageLog.logMessage("test", "tab", Qgis.Critical, False)`
`QgsMessageLog.logMessage("test", "tab", Qgis.Critical, True)`

### Versions

QGIS 3.28.12-Firenze

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@pers-ephone, QGIS 3.28 is no longer supported. Anyway, it seem to me there is a UI hint using QGIS 3.34:

notifyUser=False
![image](https://github.com/user-attachments/assets/4f4f3da1-f79a-4a76-bdc8-858a25eede59)

notifyUser=True
![image](https://github.com/user-attachments/assets/0f4d9062-0429-4add-a099-37fbd07fab6a)

**Comment by pers-ephone** [comment]
@agiudiceandrea  Ok i was wrong this is just very very subtle if not looking for it. One question still stands, why do log messages with level=Qgis.Info never notify the user, ignoring the notifyUser argument?

**Comment by agiudiceandrea** [comment]
> One question still stands, why do log messages with level=Qgis.Info never notify the user, ignoring the notifyUser argument?

It looks like by design: https://github.com/qgis/QGIS/blob/69f3a387f7ca18371029aa970fdb54d9692ac88a/src/core/qgsmessagelog.cpp#L49-L52

See https://github.com/qgis/QGIS/pull/2310 and https://github.com/qgis/QGIS/pull/7259.
