### ISSUE TITLE
QGIS Server WMS GetMap cuts labels at the tile’s border 

### ISSUE THREAD

**Issue by NivGreenstein** [qgis/QGIS#58380]
### What is the bug or the crash?

I have QGIS project with VTPK data that I serve via QGIS Server over WMS GetMap to clients. I noticed however that symbols and labels of point features that overlap 2 tiles of the map are only rendered in the tile that actually contains the feature.
I have tried TILES=TRUE with tile buffer size with various sizes but still no luck. 

I saw posts online from few years ago with the same issue but couldn’t resolve it with the suggested solutions. 

![image](https://github.com/user-attachments/assets/9b827d18-506f-4bea-9726-82cff7bb3582)

![image](https://github.com/user-attachments/assets/714de2b0-d87f-4909-9099-f9396f774107)

### Steps to reproduce the issue

Create simple yet dense data with labels as shown in the image. 
Serve it via QGIS Server (I’m using containerized) 
Send WMS GetMap request 

### Versions

QGIS 3.36.0-Maidenhead 'Maidenhead' (09951dc0acf)
QGIS code revision 09951dc0acf
Qt version 5.15.2
Python version 3.9.2
GDAL/OGR version 3.2.2
PROJ version 7.2.1
EPSG Registry database version v.10.008 (2020-12-16)
GEOS version 3.9.0-CAPI-1.16.2
SQLite version 3.34.1
OS Debian GNU/Linux 11 (bullseye)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by troopa81** [comment]
You have probably automatic label placement enabled and so from one tile to another the label place is different. That's why you get that. You have to set label at fixed position with the mode `Offset from centroid` in Placement tab from labels properties widget.

You would still have to set a tile offset regarding the size of your labels, which could be big if you have long names.
