### ISSUE TITLE
Crashing during layout and slow in general 

### ISSUE THREAD

**Issue by Carolinah23** [qgis/QGIS#58402]
## User Feedback

Hello, I have been using Qgis for a couple of years and recently it started to be super slow, I am using version 3.22.9.
It usually crashes when I am in layout. But it is so slow that saving changes can take 2-3 minutes. To change symbology it is the same.
I often have problems with the layout, but I just started having issues with the map.

These are the report details for this time. Please let me know if there is anything that I should try to make it faster.

## Report Details

**Crash ID**: [e5c8e7d69e1c4ebcbf505e9e47b26a68cf18da95](https://github.com/qgis/QGIS/search?q=e5c8e7d69e1c4ebcbf505e9e47b26a68cf18da95&type=Issues)

**Stack Trace**
<pre>
QGraphicsItem::dragMoveEvent :
QGraphicsEffectSource::draw :
QgsLayoutEffect::draw :
QGraphicsScene::drawItems :
QGraphicsScene::drawItems :
QGraphicsView::paintEvent :
QgsLayoutView::paintEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::paintSiblingsRecursive :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
QGraphicsScene::~QGraphicsScene :
QObject::event :
QGraphicsScene::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
</pre>

**QGIS Info**
QGIS Version: 3.22.9-Bia?owie?a
QGIS code revision: a8e9e6fa
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.1
Running against GDAL: 3.5.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

My layout has 4 maps and only one page. Each map has a shapefile with 76 points, a shapefile with polygon (a river), a shapefile with two lines, and a Google layer (https://mt1.google.com/vt/lyrs=s&x={x}&y={y}&z={z}) 

### Versions

**QGIS version
3.22.9-Białowieża**
QGIS code revision
a8e9e6fa
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.5.1
PROJ version
9.0.1
EPSG Registry database version
v10.064 (2022-05-19)
GEOS version
3.10.3-CAPI-1.16.1
SQLite version
3.38.1
PDAL version
2.3.0
PostgreSQL client version
14.3
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.13.1
OS version
Windows 10 Version 2009

Active Python plugins
ee_plugin
0.0.6
GroupStats
2.2.7
profiletool
4.2.6
pstimeseries
0.3.1
qgsAzimuth
0.9.18
quick_map_services
0.19.34
db_manager
0.1.20
MetaSearch
0.3.5
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is fixed in newer versions . Please update to 3.38.

**Comment by Carolinah23** [comment]
Hello @nyalldawson , thanks for your answer!

I updated QGIS to 3.34.9 (the last long-term version for Windows), it is still super slow and now the legend looks pixelated, like a bad screenshot. My layout only has the shapefiles and the google map that I mentioned before. The symbology I am using is a SVG (an arrow) that usually looks pretty good on QGIS on previous versions.

Should I still update QGIS to 3.38? Have you or anyone had similar problems?

Thanks

**Comment by agiudiceandrea** [comment]
@Carolinah23, please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
