### ISSUE TITLE
Python Library Remotior Sensus is outdated 

### ISSUE THREAD

**Issue by Geosaumitra** [qgis/QGIS#58422]
### What is the issue about the documentation?

Python Library Remotior Sensus is outdated  so showing error to load Semiautomated Classification Plugin

**Comment by agiudiceandrea** [comment]
@Geosaumitra, thanks for reporting. The Python Library Remotior Sensus and the Semi-Automatic Classification Plugin are not part of the QGIS's code base. Depending on what is your OS and installation procedure, you need to install it or update it by yourself following the Semi-Automatic Classification Plugin Documentation https://semiautomaticclassificationmanual.readthedocs.io/en/latest/. Any issue about such plugin should be reported at https://github.com/semiautomaticgit/SemiAutomaticClassificationPlugin.
