### ISSUE TITLE
Crashed when export to dxf

### ISSUE THREAD

**Issue by DesHero** [qgis/QGIS#58426]
### What is the bug or the crash?

Crashed when tried to export to dxf

## User Feedback

Trying to Export to dxf

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005c10 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

geos::noding::SegmentNodeList::size :
geos::geom::prep::PreparedGeometryFactory::create :
initGEOS :
GEOSPreparedIntersects_r :
pal::LabelPosition::intersects :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsDxfExport::writeEntities :
QgsDxfExport::writeToFile :
QgisApp::dxfExport :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.0-Maidenhead
QGIS code revision: 09951dc0
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

tried to export project to dxf

## User Feedback

Trying to Export to dxf

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00005c10 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

geos::noding::SegmentNodeList::size :
geos::geom::prep::PreparedGeometryFactory::create :
initGEOS :
GEOSPreparedIntersects_r :
pal::LabelPosition::intersects :
pal::Pal::extractProblem :
QgsLabelingEngine::solve :
QgsDefaultLabelingEngine::run :
QgsDxfExport::writeEntities :
QgsDxfExport::writeToFile :
QgisApp::dxfExport :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.0-Maidenhead
QGIS code revision: 09951dc0
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@DesHero, thanks for reporting. QGIS 3.36 is no longer supported. Please try if the issue occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it does, please provide a simple project and layer(s) and exact steps and parameters which make QGIS crash.

**Comment by nirvn** [comment]
@DesHero , in addition to what @agiudiceandrea mentioned above, a sample dataset that leads to crashes would be helpful in replicating this issue. Thanks.
