### ISSUE TITLE
QGIS installation with Chocolatey errors

### ISSUE THREAD

**Issue by florisvdh** [qgis/QGIS#58428]
### What is the bug or the crash?

In a GitHub Actions workflow with `windows-latest`, following error is present since at least several weeks, preventing successful QGIS installation:

```
  Progress: Downloading QGIS 3.38.1... 100%
  
  qgis v3.38.1 [Approved]
  qgis package files install completed. Performing other installation steps.
  WARNING: No registry key found based on  'QGIS *'
  Installing QGIS can take a few minutes.  Please be patient.
  Attempt to use original download file name failed for '/downloads/QGIS-OSGeo4W-3.38.1-1.msi'.
  Copying qgis
    from '/downloads/QGIS-OSGeo4W-3.38.1-1.msi'
  Cannot find path 'D:\downloads\QGIS-OSGeo4W-3.38.1-1.msi' because it does not exist.
  ERROR: Chocolatey expected a file to be downloaded to 'C:\Users\runneradmin\AppData\Local\Temp\chocolatey\QGIS\3.38.1\qgisInstall.MSI' but nothing exists at that location.
  The install of qgis was NOT successful.
```

See https://github.com/r-spatial/qgisprocess/actions/runs/10416802701/job/28930673659?pr=217#step:13:18 for the full output.

### Steps to reproduce the issue

Run `C:\ProgramData\Chocolatey\bin\choco.exe install qgis --allow-unofficial` (from the referred GHA workflow)

Uses Chocolatey v2.3.0 invoked by GitHub Action https://github.com/crazy-max/ghaction-chocolatey.

### Versions

Uses QGIS 3.38.1 from https://community.chocolatey.org/packages/QGIS

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Note that **LTR** does work!

`C:\ProgramData\Chocolatey\bin\choco.exe install qgis-ltr --allow-unofficial`

(see e.g. https://github.com/r-spatial/qgisprocess/actions/runs/10416802701/job/28930673028?pr=217#step:14:18)

**Comment by jef-n** [comment]
We don't package for Chocolatey.  The MSI is however available for download at https://qgis.org/downloads/QGIS-OSGeo4W-3.38.1-1.msi.  Not sure why the process doesn't use it.
