### ISSUE TITLE
Prise en compte du système de coordonnées référence de la projection cartographique de mon pays le Brukina Faso dans vos prochaine mise à jours

### ISSUE THREAD

**Issue by Kapson-kreate** [qgis/QGIS#58430]
### What is the bug or the crash?

Je sollicite dans les prochaine mise à jours de prise en compte du système de coordonnées de référence de la projection cartographique de mon pays le Burkina Faso.
En effet, mon pays sentant l'usage difficile de la projection UTM d'une part et avec les déformation qu'elle engendre d'autre part a adopté une projection cartographique propre et mieux adaptée a son territoire.cette projection est baptisée BFTM (Burkina Faso Transvers Mercator) a pour paramètre:
référentiel géodésique: ITRF 2008;
ellipsoide : GRS80;
méridien central:-1.5°;
méridien d'origine: Greenwich 0
 false easting : x0 = 600 000,00 m ; 
 false northing y0 = 0,00 m ; 
 Facteur d'échelle : 0,9996 ;
Il s'agit en claire du UTM zone 30 élargi de tel sort a faire tenir le pays sur une seule zone.
voici le SCR en WKT:

PROJCS["BFTM30",    GEOGCS["WGS 84",        DATUM["ITRF_2008",            SPHEROID["GRS 1980",6378137,298.257222101,                AUTHORITY["EPSG","7019"]],
            TOWGS84[0,0,0,0,0,0,0],
            AUTHORITY["EPSG","1149"]],
        PRIMEM["Greenwich",0,            AUTHORITY["EPSG","8901"]],
        UNIT["degree",0.0174532925199433,            AUTHORITY["EPSG","9122"]],
        AUTHORITY["EPSG","4149"]],
    PROJECTION["Transverse_Mercator"],
    PARAMETER["latitude_of_origin",0],
    PARAMETER["central_meridian",-1.5],
    PARAMETER["scale_factor",0.9996],
    PARAMETER["false_easting",600000],
    PARAMETER["false_northing",0],
    UNIT["metre",1,        AUTHORITY["EPSG","9001"]],
    AXIS["Easting",EAST],
    AXIS["Northing",NORTH],
    AUTHORITY["EPSG","32630"]]

### Steps to reproduce the issue

Le fait que le SCR de la projection cartographique de mon pays ne soit pas définit défaut dans le logiciel limite son usage au Burkina Faso 

### Versions

toute version confondu

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Hi @Kapson-kreate 

It would be better if you create ticket in English. 
Nevertheless I'm French and I will comment your request.

QGIS rely on PROJ library for projections.
Best would be to open a ticket on PROJ github repository (look for "proj github" in your favorite browser) mostly rewrite your message (but in English).

**Comment by Kapson-kreate** [comment]
"Hello, sorry for the late response. You asked me to rewrite my request by opening a ticket on the Proj GitHub repository. However, I'm not very familiar with that, and my English is limited. Could you please explain it to me further?

**Comment by nicogodet** [comment]
You can use this form -> https://github.com/OSGeo/PROJ/issues/new?assignees=&labels=feature+request&projects=&template=feature_request.md

Describe your request, why you want this new projection, your motivation, if there is any official references to this projection, ... (you can use an online translator).
I do not garantee, it will be added (it seems this projection exists for few years now and it is not part of PROJ, it could be for a good reason..)

You can also add a custom projection directly in QGIS : https://documentation.qgis.org/3.34/fr/docs/user_manual/working_with_projections/working_with_projections.html#custom-coordinate-reference-system

**Comment by rouault** [comment]
Was filed in PROJ in https://github.com/OSGeo/PROJ/issues/4232. Not a QGIS bug
