### ISSUE TITLE
Python error

### ISSUE THREAD

**Issue by wesley2source4** [qgis/QGIS#58453]
### What is the bug or the crash?

There are issues. We already tried to reinstall the program but the issue keeps returning. 
first issue with NL.IMRO. there returns an python error. 

pdokservicesplugin.lib.http_client.PdokServicesNetworkException: Host geodata.nationaalgeoregister.nl niet gevonden 
Traceback (most recent call last):
 File "C:\Users/xxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\pdokservicesplugin.py", line 598, in toolbar_search_get_suggestions
   results = suggest_query(search_text, self.create_type_filter())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users/xxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\lib\locatieserver.py", line 118, in suggest_query
   content_obj = get_request_json(url)
                 ^^^^^^^^^^^^^^^^^^^^^
 File "C:\Users/xxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\lib\http_client.py", line 54, in get_request_json
   reply = get_reply(url)
           ^^^^^^^^^^^^^^
 File "C:\Users/xxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pdokservicesplugin\lib\http_client.py", line 31, in get_reply
   raise PdokServicesNetworkException(reply_error_message)
pdokservicesplugin.lib.http_client.PdokServicesNetworkException: Host geodata.nationaalgeoregister.nl niet gevonden

Python versie: 3.12.4 (main, Jun 10 2024, 12:48:35) [MSC v.1938 64 bit (AMD64)] 
QGIS versie: 3.34.9-Prizren Prizren, cbbc7bdf

Python pad:
C:/PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python
C:/Users/xxxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/xxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python/plugins
C:\PROGRA~1\QGIS33~1.9\apps\grass\grass83\etc\python
C:\Users\xxxx\Documents
C:\Program Files\QGIS 3.34.9\bin\python312.zip
C:\PROGRA~1\QGIS33~1.9\apps\Python312\DLLs
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib
C:\Program Files\QGIS 3.34.9\bin
C:\PROGRA~1\QGIS33~1.9\apps\Python312
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\win32
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\win32\lib
C:\PROGRA~1\QGIS33~1.9\apps\Python312\Lib\site-packages\Pythonwin
C:/Users/xxxxxxx/AppData/Roaming/QGIS/QGIS3\profiles\default/python

### Steps to reproduce the issue

Is for a customer I am support for.

### Versions

We tried both the 
The current version is QGIS 3.38.1 'Grenoble' and was released on 2024-07-19.
The long-term builds currently offer QGIS 3.34.9 'Prizren'.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by wesley2source4** [comment]
Issue 1 
![phython error](https://github.com/user-attachments/assets/80227082-cfff-419f-8b09-ccebf9eb06c4)

Issue 2 how it is now
![image](https://github.com/user-attachments/assets/f9edeac5-7e43-41cd-bdb2-5b76716c5232)

Issue 2 Underneath how it should be. 
![image](https://github.com/user-attachments/assets/b92d2add-d474-4eb3-9496-071916c6b7cd)

**Comment by jef-n** [comment]
Apparently not a QGIS issue but in pdokservicesplugin (looks like the server it's using is not available)
