### ISSUE TITLE
version.txt out of date

### ISSUE THREAD

**Issue by multiquadric** [qgis/QGIS#58459]
### What is the bug or the crash?

version check info does not show latest release information
https://version.qgis.org/version.txt
https://version.qgis.org/version-ltr.txt

### Steps to reproduce the issue

Not applicable.

### Versions

<li>The current available LTR version of QGIS is 3.34.9.
<li>The latest available version of QGIS is 3.38.1.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

see recent (same issue as the last new release):
https://github.com/qgis/QGIS/issues/58255

**Comment by agiudiceandrea** [comment]
Currently also the QGIS Website reports the latest available versions for download as 3.34.9 and 3.38.1.
Probably not all the binary packages and installers for the various OS are ready.
Ping @jef-n.
