### ISSUE TITLE
Vector geometry - Multi-ring buffer (constant distance) label generator is bugged

### ISSUE THREAD

**Issue by gza-austin-elliott** [qgis/QGIS#58465]
### What is the bug or the crash?

Reproducible bug when adding labels to a polygon created with the built-in "multi-ring buffer (constant distance)" tool. Nearly all placement modes have some unwanted behavior. Perimeter modes (likely most useful) place labels upside-down/mirrored and more importantly fix neighboring labels on same lines.
![qgis bug](https://github.com/user-attachments/assets/40bb17ae-b599-45ff-9b9d-13a92b31a152)

### Steps to reproduce the issue

Create a point layer with a single point. Create a new layer and use the multi-ring buffer (constant distance) to create buffers. I'm using 5000 meter buffers. Add labels. Adjust scale and extent and watch how the labels inconsistently place themselves.

### Versions

QGIS version
3.28.14-Firenze
QGIS code revision
b09131c512
Qt version
5.15.3
Python version
3.9.5
GDAL/OGR version
3.8.2
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
processing_saga_nextgen
1.0.0
Qgis2threejs
2.7.3
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@gza-austin-elliott you probably need to properly set the labels placement properties 

![image](https://github.com/user-attachments/assets/b67dd274-3dfe-44e5-bfcd-82e1029ef3b2)
