### ISSUE TITLE
No version of QGIS with PDAL for Ubuntu Noble (24.04)

### ISSUE THREAD

**Issue by JanCaha** [qgis/QGIS#58485]
### Feature description

I am currently using QGIS from `https://qgis.org/ubuntugis` on Ubuntu Jammy (22.04) derivative (Mint 21.3) which is build against `ubuntugis-unstable` PPA. It comes with PDAL algorithms enabled.  

I started to think about upgrading to Ubuntu Noble (24.04) derivative (Mint 22) and use QGIS build against `ubuntugis-unstable` PPA. But to my surprise the PDAL algorithms are not there.

I understand that previously there have been issues with PDAL builds being in correct versions etc. But that should be mostly solved now, right? Is there specific reason why the **Noble** builds are missing **PDAL** support even for `ubuntugis-unstable` versions? Would be great if it would be possible to include **PDAL** support for those builds.

**Comment by uclaros** [comment]
Gentle ping @jef-n, is this something you handle?

**Comment by JanCaha** [comment]
Thanks a lot :+1:

**Comment by KommandorKeen** [comment]
Do I have to build from source to enable PDAL support or is there a precompiled version? I did not realise how much I had come to accept that QGIS had point cloud support. So much so that I am about to re-install Ubuntu 22.04 if I cannot work out how to get PDAL support back in 24.04. Great work overt the years team. QGIS is now a de facto standard.

**Comment by ptitjano** [comment]
> Do I have to build from source to enable PDAL support or is there a precompiled version? I did not realise how much I had come to accept that QGIS had point cloud support. So much so that I am about to re-install Ubuntu 22.04 if I cannot work out how to get PDAL support back in 24.04. Great work overt the years team. QGIS is now a de facto standard.

The QGIS version provided by the `ubuntugis` repository has PDAL support.  
FWIW, the flatpak version of QGIS also has PDAL support.

**Comment by KommandorKeen** [comment]
> The QGIS version provided by the `ubuntugis` repository has PDAL support. FWIW, the flatpak version of QGIS also has PDAL support.

That's strange. The version for 22.04 definitely did. BUT for 24.04 'noble' QGIS just does nothing when I click on a .las file or a .copc file. No warning, no error, just doesn't load. I have installed (ad de-installed) the flatpack and the QGIS versions and have the nightly build version from ubuntugis currently installed and PDAL from the same location.
