### ISSUE TITLE
QGIS very slow to close!

### ISSUE THREAD

**Issue by chuxohl** [qgis/QGIS#58481]
### What is the bug or the crash?

I am building a database of gis data for a particular state. I have loaded a variety of NAIP tif files and have discovered some confusing behaviour with the application. Each NAIP file is about 1.5 GB.  I loaded the first and then the second and things were quite normal. When I loaded the third and/or fourth the rendering of images became very, very slow.  In fact so slow I thought the app was hung up.  I looked at my RAM usage and found that I was using only about 17GB of memory.  Typically my system is using 8-9GB before I start QGIS. My system has 64GB of RAM but tops out at this size.  My thought was that there might be an environmental variable for the amount of ram.  I could find no such place.  And then, after loading in 3 or 4 NAIP files and used the red X in the upper right corner to close it out.  At that point it took almost a minute and a half simply to close.  I nearly rebooted but decided to wait.  

So is there a way to improve performance for QGIS in Windows 11. Or should I simply not use that many NAIP files simultaneously?  I also experienced a point where one of the images was not rerendering to a higher resolution when I zoomed up.  Any suggestions would be greatly appreciated.

### Steps to reproduce the issue

1. Open QGIS
2. Load a project
3. Add 4 NAIP full resolution images to the project
4. Zoom and move about the map view
5. Close the application

### Versions

3.36.3 Maidenhead on Windows 11

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
Hi @chuxohl 3.36 is end of life.
Can you try with a currently supported version and provide sample data to test with?

**Comment by chuxohl** [comment]
I was notified this was stale.  It appears that I am unsure how to answer other than with the comments already provided.  I did as instructed and the behavior continued.  If I need to download data it will have to be not public ....so where do I load the data to.  They are huge files.......

**Comment by chuxohl** [comment]
Thanks for the note.  I thought this was where bugs were reported and handed out.  I have no idea how to get someone assigned and I do not know any support companies.

**Comment by m-kuhn** [comment]
It is where bugs are reported to. But without a way to inspect it in a development environment, it will be hard to do anything about it. Ideally you can leave a dataset here to allow developers to work on it, try modifying (and possibly reducing the size of) the dataset to make it publicly shareable.

**Comment by chuxohl** [comment]
I have tried.  Cannot figure out where to put the data......
________________________________
