### ISSUE TITLE
QGIS Add CSW Layer Faulty Bounding box

### ISSUE THREAD

**Issue by ithomas0001** [qgis/QGIS#58495]
### What is the bug or the crash?

I have a server that is hosting a WCS service. I'm trying to visualize it inside QGIS version 3.38. However, the bounding box is set incorrectly on the layer request resulting in initialization errors.

### Steps to reproduce the issue

I have found one possible way of adding the wcs layer and one faulty way.

1. Inside the data sources tab, right click wcs and select add connection.
2. Set name and attach link to wcs endpoint and press ok.

Everything is good so far, the connection is fine and my layer is seen in the underlying tree.

Visualizing WCS layer (Working)
1.From the data source WCS tree, expand and find the underlying layers.
2.Right click on layer and select add layer to project.
Result: All good!

Visualizing WCS layer (Not working)
1.From menu tab, top of the client window, select layers.
2. Select add layer, then select WCS layer.
3. From prompt window, connect to source, select layer and then finally press "Add" at the bottom of the prompt window.
Result: Error couldnt read data,  faulty parameter value is invalid 
--------------------
Förfrågan innehåller ett ogiltigt parametervärde.
             WCS leverantören meddelade också:Parameter value is invalid: BBox:=179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,-179769313486231570814527423731704356798070567525844996598917476803157260780028538760589558632766878171540458953514382464234321326889464182768467546703537516986049910576551282076245490090389328944075868508455133942304583236903222948165808559332123348274797826204144723168738177180919299881250404026184124858368,urn:ogc:def:crs:EPSG::4326'.
2024-08-27T13:54:53     WARNING    No data received
--------------
Sorry for the Swedish in the logs, but the problem seem to be the bounding box, not sure how the bounding box is set from capabilities, but the search and set algorithm doesn't seem to attach a correct value.

One way of solving the issue is to click on the warning box, select the wcs layer and reload it, now the visualization works with a correct bounding box request.

### Versions

version 3.38
Also faulty in version 3.32.3 where the bounding box is set to 0,0,0,0 (tested to see if the latest release solved this but that was not the case)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@ithomas0001, thanks for reporting. The issue about adding a WCS layer using the Data Source Manager has been already previously reported at https://github.com/qgis/QGIS/issues/50432. Unfortunately it was not yet fixed. As a workaround, you could uncheck the "Extent" option before adding the layer to the map:
![image](https://github.com/user-attachments/assets/1afbc3e6-977a-44c7-9347-4c817c6d3e82)
