### ISSUE TITLE
HTML frame not rendering text

### ISSUE THREAD

**Issue by hwanderer28** [qgis/QGIS#58491]
### What is the bug or the crash?

when creating a HTML frame either within the print layout or report section, the entered text (whether it is directly entered source code or via embedded file/link) will not be rendered on the page. 

however adding a label item and rendering it as HTML works.

I have also tried downgrading to the current LTR - same issue. then I tried on my office machine today - also LTR - but windows OS and it worked there.

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/48435394-067e-430e-a856-f7b7897e242f)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

QGIS version | 3.38.1-Grenoble | QGIS code branch | Release 3.38
-- | -- | -- | --
Qt version | 5.15.14
Python version | 3.12.4
GDAL/OGR version | 3.9.1
PROJ version | 9.4.1
EPSG Registry database version | v11.006 (2024-03-13)
GEOS version | 3.12.2-CAPI-1.18.2
Compiled against SQLite | 3.46.0 | Running against SQLite | 3.46.1
PDAL version | 2.7.2
PostgreSQL client version | 16.3
SpatiaLite version | 5.1.0
QWT version | 6.3.0
QScintilla2 version | 2.14.1
OS version | Arch Linux
  |   |   |  
Active Python plugins
ViewshedAnalysis | 1.9
slyr_community | 5.0.0
SentinelHub | 2.0.2
quick_map_services | 0.19.34
QuickOSM | 2.2.3
qgis_hub_plugin | 0.1.2
processing_saga_nextgen | 1.0.0
QNEAT3 | 1.0.5
qfieldsync | v4.10.1
qgis-maptiler-plugin | 3.3.2
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@hwanderer28 have you clicked on "Refresh HTML" after the text was added in the Source text box?

**Comment by hwanderer28** [comment]
> @hwanderer28 have you clicked on "Refresh HTML" after the text was added in the Source text box?

yes I did, pardon me for not mentioning it.

**Comment by agiudiceandrea** [comment]
I think this may be an ArchLinux issue only.

**Comment by nyalldawson** [comment]
Probably the arch build has disabled Qt webkit support. In which case there's nothing we can do, HTML support will be disabled in that build.

Suggest we close as a downstream issue only.

**Comment by agiudiceandrea** [comment]
Confirmed:
https://github.com/archlinux/svntogit-community/commit/783d52696588264257eed9d32c9fd212d0fdeace
https://gitlab.archlinux.org/archlinux/packaging/packages/qgis/-/commit/a13bdd70c2579e2b16878d3278235f3c90e08b05
https://gitlab.archlinux.org/archlinux/packaging/packages/qgis/-/blob/main/PKGBUILD?ref_type=heads#L41
https://lists.archlinux.org/hyperkitty/list/arch-dev-public@lists.archlinux.org/thread/Z3YJQFKJT3AXDTI33SBU52C6JK75GL5X/
