### ISSUE TITLE
QGIS Properties Dialog Slides Off Screen

### ISSUE THREAD

**Issue by sevensonmaps** [qgis/QGIS#58497]
### What is the bug or the crash?

https://github.com/user-attachments/assets/e127431c-4fb2-42fd-8d13-ca9f3702a4d6

When I attempt to select a sensor and setup the baud rate and dilimeter I can't hit okay because it is off the screen of my Windows tablet. Any ideas on what is going on or how to fix this? It's preventing me from getting our sensor connected and utilized in QField

### Steps to reproduce the issue

1. Open QGIS 3.38.2
2. Open project
3. Open Properties dialog box
4. Navigate to Sensors
5. See error

### Versions

QGIS version
3.38.2-Grenoble
QGIS code revision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Thanks for reporting. Does this only occurs with the "Sensor" tab?

**Comment by sevensonmaps** [comment]
No worries, it's been driving me crazy all morning. It happens on all properties tabs, the sliders are visible on some tabs but the "Ok" or "Apply" buttons are not visible. The screen resolution is 1280x800, per recommended resolution on the Trimble T7 tablet series.

**Comment by DelazJ** [comment]
@sevensonmaps In the "Elevation" tab, collapse the "global map shading" group and try again to resize the dialog

**Comment by sevensonmaps** [comment]
@DelazJ That worked! Thanks so much!
