### ISSUE TITLE
fc4b25945b8684770dd1dd420ce97cdda575be37

### ISSUE THREAD

**Issue by chicoteixeira** [qgis/QGIS#58507]
### What is the bug or the crash?

Stack Trace

QgsSingleBandColorDataRenderer::block :
QgsBrightnessContrastFilter::block :
QgsHueSaturationFilter::block :
QgsRasterResampleFilter::block :
QgsRasterProjector::block :

### Steps to reproduce the issue

QGIS Info
QGIS Version: 3.14.1-Pi
QGIS code revision: de08d6b71d
Compiled against Qt: 5.11.2
Running against Qt: 5.11.2
Compiled against GDAL: 3.0.4
Running against GDAL: 3.0.4

### Versions

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@chicoteixeira thanks for reporting, anyway QGIS 3.14 is no longer supported.

**Comment by chicoteixeira** [comment]
@agiudiceandrea Thank you for your reply! Indeed I have tried with the currently QGIS LTR version without success. Maybe the problem is related to my shapefiles.

**Comment by agiudiceandrea** [comment]
@chicoteixeira, please create an new issue report providing all the requested info and the affected layer and the detailed steps to replicate the issue.
