### ISSUE TITLE
LAS2DEM utility produces elevation values equal to '0'.

### ISSUE THREAD

**Issue by chuxohl** [qgis/QGIS#58525]
### What is the bug or the crash?

I downloaded a LAZ file from TNRIS.org which is the Texas Geographic Information Office. I used the las2dem(file) option and picked the input laz file. I took all the defaults (step 1 and keep class 2). The DEM I got back had a number of linear stripes left in it. When I queried the stripe with the Identify Features tool I got a popup that indicated the value was zero. I tried changing to a step size of 2 to no avail. Stripes were still present.

I returned to the layer properties and discovered that the default Classification choice for symbology contained only the values of 'Unclassified' and 'Ground'. Thinking the 'Unclassified' was a problem I filtered them out and reran the process. This tool results in the same exact stripes.

My instinct suggests the conversion to raster has an issue. I do not know how to handle this situation. Please advise!
![las2dem](https://github.com/user-attachments/assets/a3aa0443-afc5-4640-95fe-221b3ae3cdac)
![las2dem2](https://github.com/user-attachments/assets/cf96490b-b305-4d01-a6af-96d579d6d0c6)

I also reported this issue in the plugin section.

### Steps to reproduce the issue

Download LAZ file
Display in map canvas using browser
Start las2dem(file) and load file
Take defaults
Name output file with .tif extension
Display DEM using single band pseudocolor
Use identify Features tool

### Versions

QGIS 3.38.2
LAStools 2.1.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Windows 11 OS

**Comment by uclaros** [comment]
LAS2DEM is not part of QGIS, you should contact the plugin author if you think there is a bug.

Or

you can actually use QGIS for this and use the _Export to raster_ processing tool located in the _Point cloud conversion_ group. You can then set a filter expression to limit the points used to Ground points.

**Comment by chuxohl** [comment]
Turns out the issue is that it requires a license. So the errors are introduced.
