### ISSUE TITLE
Application crashes with data layers

### ISSUE THREAD

**Issue by josecarlosbcn** [qgis/QGIS#58527]
### What is the bug or the crash?

I'm totally newbie with QGis. 

I want to draw in a layer several polygons. To do this, I load the data in the layer from a csv file. This csv file has a total amount of 65.000 rows and a weight of 109MB. The load of information in the layer works fine. 

The problem is when I try to get this information and process it. 

the 65,000 records in the csv file but when I read the information the application crashes.

### Steps to reproduce the issue

If I try to process the total amount in a batch processing.

`
layer = iface.activeLayer()
features = layer.getFeatures()

batch_size = 5000
batch = []

def process_batch(batch):
    for feat in batch:
       id_pts = feat["id_"]
       pts_perim = feat["points"]
       print(id_pts)
       #print(pts_perim)
    print("Batch processing succesfully!!!")

for i, feat in enumerate(features):
    batch.append(feat)
    print(f"Feature {i} added to the list")
    if i % batch_size == 0:
        process_batch(batch)
        batch = []
`

The process usually to crash in this line of code `for i, feat in enumerate(features):`

And it's not possible to advance because the application crashes. ¡¡¡In other computer happens the same!!!

However, If I try to get access to the information loading this infromation over a dataframe, I can run through the entire dataframe and print the value of the variable id_ on the screen.!!!

Here is my code:

`
import pandas as pd
pd.options.display.max_columns = None

df = pd.read_csv('F:\Proyectos\QGis\cent_cont_P8_xd3_id.csv')

df["points"] = df["points"].astype("string")
#df["coords"] = df.points.split(";")

df["coords"] = 0
for index, row in df.iterrows():
    df["coords"][index] = df["points"][index]
    df["coords"][index] = df["points"][index].split(";")
    df["coords"][index] = [tuple(map(float, cadena.strip('()').split(','))) for cadena in df["coords"][index]]

batch_size = 5000
batch = []

for index, row in df.iterrows():
    print(row["id_"])
print("Proceso finalizado!!!")

`
This code works for me from time to time. Because the same code with the same data sometimes works fine and another the application crashes. But in another computer the application crashes always!!! How is that possible? This other computer has installed the version 3.23 of QGis.

I am desperate, because I have learned how to create a polygon on the layer, but now I need to create a polygon based on each of the registers of the csv file, around 65.000 polygons.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versión de QGIS | 3.34.10-Prizren | Revisión del código de QGIS | 113de9e1
-- | -- | -- | --
Versión Qt | 5.15.13
Versión de Python | 3.12.5
Versión de GDAL/OGR | 3.9.2
Versión de PROJ | 9.4.0
Versión del registro de base de datos EPSG | v11.004 (2024-02-24)
Versión de GEOS | 3.12.2-CAPI-1.18.2
Versión de SQLite | 3.45.1
Versión de PDAL | 2.6.3
Versión del cliente de PostgreSQL | 16.2
Versión de SpatiaLite | 5.1.0
Versión de QWT | 6.2.0
Versión de QScintilla2 | 2.14.1
Versión del SO | Windows 10 Version 2009
  |   |   |  
Complementos activos de Python
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>Versión de QGIS
3.34.10-Prizren
Revisión del código de QGIS
[113de9e1](https://github.com/qgis/QGIS/commit/113de9e1)
Versión Qt
5.15.13
Versión de Python
3.12.5
Versión de GDAL/OGR
3.9.2
Versión de PROJ
9.4.0
Versión del registro de base de datos EPSG
v11.004 (2024-02-24)
Versión de GEOS
3.12.2-CAPI-1.18.2
Versión de SQLite
3.45.1
Versión de PDAL
2.6.3
Versión del cliente de PostgreSQL
16.2
Versión de SpatiaLite
5.1.0
Versión de QWT
6.2.0
Versión de QScintilla2
2.14.1
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
More information is required here. Please provide the full script and sample data which demonstrates the crash.
