### ISSUE TITLE
Geopackage CRS issue

### ISSUE THREAD

**Issue by DannyJJD** [qgis/QGIS#58537]
### What is the bug or the crash?

When reprojecting GeoPackages the CRS, when projected in WGS84/UTM zones, does not seem to 'stick' to the file i.e., it needs to be reassigned every time the GeoPackage is added to the UI and stops geopandas being able to read the CRS. This does not happen with ESRI shape files, so I assume it's something to do with reading/writing the geopackages stored metadata?

### Steps to reproduce the issue

1. Add geopackage projected in one of the WGS84/UTM zones, does not have CRS attributed. 
2. Add ESRI shapefile projected in one of the WGS84/UTM zones, does have CRS attributed.

### Versions

QGIS version
3.38.2-Grenoble
QGIS code revision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
()
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
agknow_qgis
0.7.5
attributeBasedClustering
2.2.1
coordinates_converter
1.0
coordinate_capture
0.2
gis_cloud_publisher
1.0.9
GroupStats
2.2.7
ImportPhotos
3.0.6
LandXml
2.4
latlontools
3.7.0
mmqgis
2021.9.10
nafi
1.0.4
orfeoToolbox_provider
3.0.3
pluginbuilder3
3.2.1
pointsamplingtool
0.5.4
processing_saga_nextgen
1.0.0
qtiles
1.7.2
quick_map_services
0.19.34
raster_divider
1.4
slyr_community
5.0.0
SRTM-Downloader
3.2.3
wbt_for_qgis
1.1.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@DannyJJD, thanks for reporting. Please actually try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). If it does, please provide a sample GPKG layer with the issue occurs and details on how such layer was created or from where it was downloaded.
