### ISSUE TITLE
Styles >> Copy/paste >> Attribute Form only copies columns selected in 'Form Layout' but does not copy other modified attributes/columns

### ISSUE THREAD

**Issue by jeremyferris** [qgis/QGIS#58549]
### Feature description

With 'Drag and Drop Designer' selected, when doing a Copy/Paste of 'Attribute Form' from one layer to another, it appears that only the fields in the 'Form Layout' section get copied.

FEATURE REQUEST: add capability (checkbox?) to include ALL attributes in a copy of the 'Attribute Form' to be able to paste to subsequent layers, in addition to the ones explicitly available to the user in the form.

Case Point: I have attributes; id, uuid, name, notes, description. I want id and uuid hidden from the user in the 'Attribute Form' but I also want the 'id' and 'uuid' to use default values rather than duplicating those fields. This is settable in the 'Attributes Form' section of the 'Layer Properties' dialogue and works for a given layer, however, this functionality is not copied unless the fields 'id' and 'uuid' are included in the 'Form Layout' section of the dialogue.

### Additional context

I think this best fits in the 'Feature Request' category, but I think it best to report it as a bug:

To replicate this behavior:

1. Create two layers with attributes: id, uuid, name, notes, description
2. in the 'Attribute Form' dialogue of the first layer, change from 'Automatic' to ' Drag and Drop Designer'
3. Remove layers 'id' and 'uuid' from the 'Form Layout' section.
4. make changes to fields in the 'Form Layout' section
5. make changes to 'id' and 'uuid' in the 'Available Widgets' section of your first feature.
  - ie. under 'Policies' change 'Duplicate Value' to 'Use Default Value'
6. Close dialogue, right-click on edited first layer, hover over 'Styles' >> 'Copy Style' >> 'Attribute Form' and click to copy.
7. Right-click second layer, hover over 'Styles' >> 'Paste Style' >> 'Attribute Form' and click to paste.

Notice that while the drag-and-drop designer and selected fields are copied to all attributes in the 'Form Layout' section, policies applied to attributes that are not in 'Form Layout' do not have these new policies applied.

**Comment by nirvn** [comment]
@jeremyferris , the split policy and default value settings are associated with fields, not with attribute form. If you copy/paste the Field category, you'll see those settings are copied properly.

**Comment by jeremyferris** [comment]
@nirvn, Thank you for that, that appears to work on my first test.

Interesting that the policies are not editable under the 'Fields' layer dialogue. Intuitively, I would have expected copy/paste of 'Styles' >> 'Fields' to actually copy and paste the set of fields from one layer to another, but it does not appear to do this, it appears to only copy policies for fields that are named identically from one layer to another.

While this information effectively answers this feature request / bug, It may be worthwhile to study how to better indicate what is copy/pasted in the UI under the various categories.

Thanks again for the response, it will save me quite a bit of tedium on my project with 171 layers.

**Comment by nirvn** [comment]
@jeremyferris , if your mouse stays on the Fields (or any other category) menu item for long enough, you'll get a tooltip that expands a bit on what is covered by each section. It's not an ideal UI, tooltips on menu items are really not intuitive. 

The documentation here (https://docs.qgis.org/3.34/en/docs/user_manual/introduction/general_tools.html#manage-custom-style) could be improved. Do you feel like providing a bit of your time there? :)
