### ISSUE TITLE
My QGIS stopped running.

### ISSUE THREAD

**Issue by LordVladAfolabi** [qgis/QGIS#58567]
### What is the bug or the crash?

This is what was written in the report details:

"Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000056d0 (most recent call first):
  

Stack Trace

QObject::thread :
QgisApp::messageBar :
instance :
pdal::Stage::run :
QgsPythonRunner::run :
QgisApp::QgisApp :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.36.3-Maidenhead
QGIS code revision: 2df96554
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631"

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/07c3bb50-30d4-427c-8101-8b0714b6d21d)

### Versions

QGIS Desktop 3.36.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by beb190** [comment]
Hi,
It the same message when I try to open the layer...
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x000005fc (most recent call first):
  


Stack Trace


QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsOptionsDialogBase::addPage :
QgsLayerPropertiesDialog::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :




QGIS Info
QGIS Version: 3.34.10-Prizren
QGIS code revision: 113de9e1
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2



System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

**Comment by nyalldawson** [comment]
More information is needed here. How can this crash be reliably reproduced?
