### ISSUE TITLE
Bug/error qgis-providers package post-installation script subprocess returned error exit status 139

### ISSUE THREAD

**Issue by juangomes376** [qgis/QGIS#58571]
### What is the bug or the crash?

I had a version of qgis-server 1:3.28.14+36jammy installed, but I noticed that parts were not working. I tried to upgrade to see if it was an update and that's when I came across this error.

 sudo apt upgrade
Lecture des listes de paquets... Fait
Construction de l'arbre des dépendances... Fait
Lecture des informations d'état... Fait      
Calcul de la mise à jour... Fait
Les paquets suivants ont été installés automatiquement et ne sont plus nécessaires :
  libjs-leaflet libqgis-3d3.34.9 libqgis-analysis3.34.9 libqgis-app3.34.9 libqgis-core3.34.10 libqgis-core3.34.9
  libqgis-gui3.34.10 libqgis-gui3.34.9 libqgis-native3.34.10 libqgis-native3.34.9 libqgis-server3.34.9 libqgisgrass7-3.34.10
  libqgisgrass8-3.34.9 libqgispython3.34.9 libqt5charts5 python3-pyqt5.qtmultimedia qgis-common qgis-plugin-grass-common
  qgis-provider-grass qgis-server-dummy qgis-server-landingpage qgis-server-wcs qgis-server-wfs3 qgis-server-wms
  qml-module-qtcharts
Veuillez utiliser « sudo apt autoremove » pour les supprimer.
Get more security updates through Ubuntu Pro with 'esm-apps' enabled:
  python3-jupyter-core libde265-dev gsasl-common libheif1 libjs-jquery-ui
  python3-scipy libgsasl7 libheif-dev libgsl27 libgslcblas0 libde265-0
Learn more about Ubuntu Pro at https://ubuntu.com/pro
Les paquets suivants ont été conservés :
  update-manager-core
0 mis à jour, 0 nouvellement installés, 0 à enlever et 1 non mis à jour.
9 partiellement installés ou enlevés.
Après cette opération, 0 o d'espace disque supplémentaires seront utilisés.
Souhaitez-vous continuer ? [O/n] o
Paramétrage de qgis-providers (1:3.28.14+36jammy) ...
Segmentation fault (core dumped)
dpkg: erreur de traitement du paquet qgis-providers (--configure) :
 installed qgis-providers package post-installation script subprocess returned error exit status 139
dpkg: des problèmes de dépendances empêchent la configuration de python3-qgis :
 python3-qgis dépend de qgis-providers (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.

dpkg: erreur de traitement du paquet python3-qgis (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-common :
 qgis-server-common dépend de qgis-providers (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-providers n'est pas encore configuré.
 qgis-server-common dépend de python3-qgis (= 1:3.28.14+36jammy) ; cependant :
 Le paquet python3-qgis n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-common (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-landingpage :
 qgis-server-landingpage dépend de qgis-servAucun rapport « apport » n'a été créé car le message d'erreur indique une erreur c
onsécutive à un échec précédent.
                                Aucun rapport « apport » n'a été créé car le message d'erreur indique une erreur consécutive à
 un échec précédent.
                    Aucun rapport « apport » écrit car MaxReports a déjà été atteint
                                                                                    Aucun rapport « apport » écrit car MaxRepo
rts a déjà été atteint
                      Aucun rapport « apport » écrit car MaxReports a déjà été atteint
                                                                                      Aucun rapport « apport » écrit car MaxRe
ports a déjà été atteint
                        Aucun rapport « apport » écrit car MaxReports a déjà été atteint
                                                                                        Aucun rapport « apport » écrit car Max
Reports a déjà été atteint
                          er-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-landingpage (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-wms :
 qgis-server-wms dépend de qgis-server-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-wms (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-dummy :
 qgis-server-dummy dépend de qgis-server-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-dummy (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-wcs :
 qgis-server-wcs dépend de qgis-server-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-wcs (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-wfs3 :
 qgis-server-wfs3 dépend de qgis-server-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-wfs3 (--configure) :
 problèmes de dépendances - laissé non configuré
dpkg: des problèmes de dépendances empêchent la configuration de qgis-server-wfs :
 qgis-server-wfs dépend de qgis-server-common (= 1:3.28.14+36jammy) ; cependant :
 Le paquet qgis-server-common n'est pas encore configuré.

dpkg: erreur de traitement du paquet qgis-server-wfs (--configure) :
 problèmes de dépendances - laissé non configuré
Des erreurs ont été rencontrées pendant l'exécution :
 qgis-providers
 python3-qgis
 qgis-server-common
 qgis-server-landingpage
 qgis-server-wms
 qgis-server-dummy
 qgis-server-wcs
 qgis-server-wfs3
 qgis-server-wfs
needrestart is being skipped since dpkg has failed
E: Sub-process /usr/bin/dpkg returned an error code (1)

I've found several people complaining about a similar problem but no one has found a solution. Can anyone who has had this problem and managed to solve it help me because I don't know what to do? I went back to version 1.34.X and I still have the same problem. Now I've gone back to version 1.28 because on my system the Lizmap registration plugin only works correctly in version 1.28.

people with the same error as mine apparently
https://github.com/qgis/QGIS/issues/51886
https://github.com/qgis/QGIS/issues/57729

### Steps to reproduce the issue

sudo apt upgrade

### Versions

ubuntu 22.04
qgis 1:3.28.14+36jammy
lizmap 3.6.7

 Extension:
atlasprint	3.3.2
cadastre	1.18.2
Lizmap server	2.8.1
wfsOutputExtension	1.8.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@juangomes376 thanks for reporting. Is your issue the same or similar to the one already reported at https://github.com/qgis/QGIS/issues/57729?
