### ISSUE TITLE
qgis can't search for postgis elsewhere than in the public schema

### ISSUE THREAD

**Issue by thomas-szczurek** [qgis/QGIS#58577]
### What is the bug or the crash?

It seems that qgis automatically searches after postgis in postgresql's public schema rather than in its `search_path` parameter. If postgis is installed in another schema (something you may want to do as postgresql policy is try to not use the public schema anymore), qgis can no longer understand table geometries, can't find any functions ...

### Steps to reproduce the issue

- create a new database testdb
- create a schema named extensions
- install postgis with :

```sql
CREATE EXTENSION postgis SCHEMA extensions;

ALTER DATABASE testdb SET search_path = public,extensions;
```

- open qgis and try to create a connection toward this database

### Versions

3.38

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
I cannot reproduce locally, I followed your instructions but QGIS is able to create and to see all spatial tables in both `extensions` and `public` schema.

![immagine](https://github.com/user-attachments/assets/4c31bca8-4e45-432d-a21b-05839a0ff2a1)


![immagine](https://github.com/user-attachments/assets/5acc19f5-4b01-4632-b72f-00d3e1c198a6)

**Comment by thomas-szczurek** [comment]
My mistake sorry. I tried it first by moving postgis to a different schema from an existing install.  Following my own steps from 0 it's working fine.

**Comment by ionosphere** [comment]
Hi,

I have the same problem when postgis extension is not loaded in the public schema.

In my case, i have data in one schema and spatial_ref_sys table in postgis schema

**=> Qgis does not detect SRID and spatial type**

When i add a search path for my user on postgresql
```SQL
ALTER ROLE api_user SET SEARCH_PATH = 'XXXXXXXXXX-ekyviti', 'postgis', 'topology';
```
**=> Qgis detect SRID and spatial type**

So i supposed that it could be great to add a field on database connection to ask the other schema to look at for spatial reference.
