### ISSUE TITLE
unregisterPluginTreeNode crashes QGIS when any node has 3 or more child nodes or child setting entries

### ISSUE THREAD

**Issue by freeshrugsxd** [qgis/QGIS#58595]
### What is the bug or the crash?

This is a strange one. When `QgsSettingsTree.unregisterPluginTreeNode` is called on a plugin while it or any of its child nodes has three or more child nodes or settings, then QGIS crashes. Two of any is fine.

@3nids I hope it is alright to ping you because I know you worked on this 🙏

### Steps to reproduce the issue

The following python script will execute without any error. However, uncomment any of the commented lines and it will crash QGIS.

```python
root = QgsSettingsTree.createPluginTreeNode(pluginName='crash_at_three')
s1 = QgsSettingsEntryString('root setting 1', root, 'value', 'desc')
s2 = QgsSettingsEntryString('root setting 2', root, 'value', 'desc')
# s3 = QgsSettingsEntryString('setting 3', root, 'value', 'desc')

n1 = root.createChildNode('node 1')
n1s1 = QgsSettingsEntryString('node 1 setting 1', n1, 'value', 'desc')
n1s2 = QgsSettingsEntryString('node 1 setting 2', n1, 'value', 'desc')
# n1s3 = QgsSettingsEntryString('node 1 setting 3', n1, 'c', 'node 1 desc 3')

n1c1 = n1.createChildNode('node 1 child 1')
n1c1s1 = QgsSettingsEntryString('node 1 child 1 setting 1', n1c1, 'value', 'desc')
n1c1s2 = QgsSettingsEntryString('node 1 child 1 setting 2', n1c1, 'value', 'desc')
# n1c1s3 = QgsSettingsEntryString('node 1 child 1 setting 3', n1c1, 'value', 'desc')

n1c2 = n1.createChildNode('node 1 child 2')
n1c2s1 = QgsSettingsEntryString('node 1 child 2 setting 1', n1c2, 'value', 'desc')
n1c2s2 = QgsSettingsEntryString('node 1 child 2 setting 2', n1c2, 'value', 'desc')
# n1c2s3 = QgsSettingsEntryString('node 1 child 2 setting 3', n1c2, 'value', 'desc')

# n1c3 = n1.createChildNode('node 1 child 3')

n2 = root.createChildNode('node 2')
n2s1 = QgsSettingsEntryString('node 2 setting 1', n2, 'value', 'desc')
n2s2 = QgsSettingsEntryString('node 2 setting 2', n2, 'value', 'desc')
# n2s3 = QgsSettingsEntryString('node 2 setting 3', n2, 'value', 'desc')

# n3 = root.createChildNode('node 3')

root = QgsSettingsTree.unregisterPluginTreeNode(pluginName='crash_at_three')
```

### Versions

QGIS-Version | 3.34.10-Prizren
------------ | ---------------
QGIS-Codeversion | 113de9e1
Qt-Version | 5.15.13
Python-Version | 3.12.5
GDAL-Version | 3.9.2
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.2-CAPI-1.18.2
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 11 Version 2009

Aktive Python-Erweiterungen
name | version
---- | -------
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by 3nids** [comment]
Thanks a lot for the very precise report, I will try to fix this.
