### ISSUE TITLE
QGIS ended unexpectedly.

### ISSUE THREAD

**Issue by maxmarumbwa** [qgis/QGIS#58596]
### What is the bug or the crash?

Crash ID: [a117107e4e99008015b6d851b0c13805d1cc2b2a](https://github.com/qgis/QGIS/search?q=a117107e4e99008015b6d851b0c13805d1cc2b2a&type=Issues)

Stack Trace

QResource::fileName :
QResource::lastModified :
QResource::data :
QFSFileEngine::entryList :
QFileInfo::fileTime :
QFileInfo::exists :
QFileInfo::exists :
QLibraryInfo::buildDate :
QAbstractFileEngine::isRelativePath :
QLibraryInfo::buildDate :
QLibraryInfo::location :
QCoreApplication::libraryPathsLocked :
QCoreApplication::libraryPaths :
QFactoryLoader::update :
QFactoryLoader::QFactoryLoader :
QPlatformScreen::windows :
QPlatformIntegrationFactory::keys :
QGuiApplicationPrivate::init :
QGuiApplicationPrivate::createPlatformIntegration :
QGuiApplicationPrivate::createEventDispatcher :
QCoreApplicationPrivate::init :
QGuiApplicationPrivate::init :
QApplicationPrivate::init :
QApplication::QApplication :
QgsApplication::QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.22.12-Bia?owie?a
QGIS code revision: b8534cb1
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.5.2
Running against GDAL: 3.5.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Crashed before loading

### Versions

QGIS Version: 3.22.12-Bia?owie?

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No

**Comment by agiudiceandrea** [comment]
@maxmarumbwa QGIS 3.22 is no longer supported. Please try if the issue occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please open a new issue report providing all the requested info and all the steps to replicate the issue also providing, if necessary, a minimal set of project + layer(s).
