### ISSUE TITLE
Can't create geometry in Virtual layer using geom_from_wkt() (Bug in 3.38.2, works in 3.34.10)

### ISSUE THREAD

**Issue by Oisin-JK** [qgis/QGIS#58644]
### What is the bug or the crash?

Bug is in 3.38.2
Works in 3.34.10

Using geom_from_wkt() in SQL does not create a valid geometry.

### Steps to reproduce the issue

Create a blank project.
Create a virtual layer
use the following sql 
`select geom_from_wkt( 'POINT(4 5)' )`
Add virtual layer.
View attribute table and map pane. An invalid geometry is shown in attribute table, the feature is not rendered in the map pane - as screenshot below.
![image](https://github.com/user-attachments/assets/52a7f00c-c06a-4afa-b980-a91621887819)

In contrast, the same in QGIS LTR (3.34.10) gives the following result
![image](https://github.com/user-attachments/assets/402b2823-e513-4620-bf34-3ae8a8056d7f)

### Versions

QGIS version
3.38.2-Grenoble
QGIS code revision
130c432394
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
magic_map_loader
1.0
qfieldsync
v3.4.1
qgis2web
3.22.0
StreetView
3.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Oisin-JK, thanks for reporting. As a workaround, you can use `select st_geomfromtext( 'POINT(4 5)' )` instead.
