### ISSUE TITLE
messure angle is error sometimes

### ISSUE THREAD

**Issue by radi2015** [qgis/QGIS#58654]
### What is the bug or the crash?

messure angle result is error 

first picture is right
![image](https://github.com/user-attachments/assets/8946d8c5-0e2c-4d77-b1dc-dd180122695a)

second picture is error where linestring is rotate
![image](https://github.com/user-attachments/assets/893ce972-c417-440e-aaa0-8b66ceb1ba23)

### Steps to reproduce the issue

messure datas:
LineString (116 39, 117 39, 117 40)
LineString (116 39.00000000000000711, 116.89100652418837001 39.45399049973955385, 116.43701602444882326 40.34499702392790965)

### Versions

3.34.8-Prizren

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@radi2015, thanks for reporting. You are using a geographic CRS and the angle measurement is made on the ellipsoid set in project properties. In fact, the value of measured angle shown in the first screenshot for the unrotated line is not 90°, as it should be if the angle was measured on the CRS Cartesian plane instead.

If you want to measure the angle on the CRS cartesian plane, you need to set the project's Ellipsoid to "None \ Planimetric" (in Project->Properties->General->Measurement).

**Comment by agiudiceandrea** [comment]
@radi2015, thanks for reporting. You are using a geographic CRS and the angle measurement is made on the ellipsoid set in the project's properties. In fact, the value of the measured angle shown in the first screenshot for the unrotated line is not 90°, as it should be if the angle was measured on the CRS Cartesian plane instead.

If you want to measure the angle on the CRS Cartesian plane, you need to set the project's Ellipsoid to "None \ Planimetric" (in Project->Properties->General->Measurement). See https://docs.qgis.org/3.34/en/docs/user_manual/map_views/map_view.html#general-information.

**Comment by radi2015** [comment]
great! thinks very much
