### ISSUE TITLE
General map

### ISSUE THREAD

**Issue by k22limbo** [qgis/QGIS#58668]
### What is the bug or the crash?

The general map of the world shows the temporarily occupied territory of Ukraine (the Crimean peninsula) as the territory of Russia. This is a violation of international law

### Steps to reproduce the issue

![Знімок екрана 2024-09-11 234520](https://github.com/user-attachments/assets/c0c53663-ddaf-4961-a0f1-b96e93d160ba)

### Versions

3.22

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@k22limbo, you are using a no longer supported QGIS version.
The reported issue doesn't occur using a currently supported QGIS version.

**Comment by jef-n** [comment]
duplicate of #46810
