### ISSUE TITLE
In QGIS 3.38.2 when deleting an attribute from a gdb file, all the fields in the remaining attributes get deleted as well

### ISSUE THREAD

**Issue by Francis24855** [qgis/QGIS#58669]
### What is the bug or the crash?

I have a gdb shape file with many attributes, let's say A100, A200, A300 and with many fields. When I go to the edit through the "Open attribute table" and delete A200, all the fields in A100 and A300 disappear upon saving the changes. Is this a bug, or what I am trying to perform is not possible for a gdb file? The process that I described is what I usually perform for a shp file. A work around is to save the gdb file an uncheck the attribute from the saving dialog box. However, I discovered that the data is there.  If you press the reload data icon (4th icon - 2 blue arrows) the data reappear.

### Steps to reproduce the issue

Open the gdb table, put in edit mode, delete an attribute, save changes, close edit mode you will see that some data just disappear.  However, when you press the reload the table, the data appear again.  If you don't do that you have the impression that the data are no longer there

### Versions

3.38.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Related question on gis.stackexchange.org: https://gis.stackexchange.com/questions/485776/in-qgis-3-38-2-when-deleting-an-attribute-from-a-gdb-file-all-the-fields-in-the
Test FileGeodatabase layer from the same question: [test-2-gdb_2024-09-11_1917.zip](https://github.com/user-attachments/files/16970876/test-2-gdb_2024-09-11_1917.zip)

The issue occurs running QGIS 3.38.2 and 3.34.10 with GDAL/OGR 3.9.2 and QGIS 3.39-Master (e6e4484850) with GDAL/OGR 3.10.0dev-5999d8b87c on Windows (OSGeo4W) only when the GDL/OGR "OpenFileGDB" driver (the default one) is used, while it doesn't occur when the GDAL/OGR "FileGDB" driver (based on the ESRI FileGDB API proprietary library) is used.
