### ISSUE TITLE
Crash while a project is been saved

### ISSUE THREAD

**Issue by solisgb** [qgis/QGIS#58688]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x0000303c (most recent call first):
  

Stack Trace

QObject::thread :
QgsProcessingAlgorithm::runPrepared :
QgsProcessingAlgRunnerTask::run :
pdal::PointView::table :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

### Steps to reproduce the issue

Unexpected while I was closing QGIS

### Versions

QGIS Info
QGIS Version: 3.34.10-Prizren
QGIS code revision: 113de9e1
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

**Comment by nyalldawson** [comment]
There's nothing actionable here. Can you provide more details on how to reproduce this crash?

**Comment by solisgb** [comment]
The crash was completely unexpected, so I was only able to retrieve the auto-generated report from QGIS. It has not happened again.
