### ISSUE TITLE
Qgis project keeps crashing

### ISSUE THREAD

**Issue by xyzadh** [qgis/QGIS#58683]
### What is the bug or the crash?

This is the crash report. The project keeps crashing. I have not seen a reason why, that is, once it crashed when I was in print layout moving an object, once when I was editing etc

### Steps to reproduce the issue

Python Stack Trace
Windows fatal exception: access violation

Thread 0x0000075c (most recent call first):
  

Stack Trace

sqlite3_bind_int64 :
sqlite3_bind_int64 :
sqlite3_bind_int64 :
CPLODBCDriverInstaller::RemoveDriver :
CPLODBCDriverInstaller::RemoveDriver :
QgsSQLiteExpressionCompiler::operator= :
QgsAbstractFeatureIterator::nextFeature :
QgsVectorLayerFeatureIterator::fetchFeature :
QgsAbstractFeatureIterator::nextFeature :
QgsPointLocator::rebuildIndex :
QgsPointLocator::waitForIndexingFinished :
QgsTask::start :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.34.9-Prizren
QGIS code revision: cbbc7bdf
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.1
Running against GDAL: 3.9.1

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Versions

Qgis 3.34.9

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nirvn** [comment]
@xyzadh , we'll need a sample project to dissect this.
