### ISSUE TITLE
Get UTC-Time of Points in a Pointcloud-File using the Identify-Tool

### ISSUE THREAD

**Issue by PeterDrexel** [qgis/QGIS#58695]
### Feature description

When I click on a point of a loaded lidar-pointcloud I get the lidar-attributes, one of them is the GPS-Time. 
In newer Lidarfiles this is usually stored as Adjusted Standard GPS Time (see [https://www.asprs.org/wp-content/uploads/2019/03/LAS_1_4_r14.pdf](https://www.asprs.org/wp-content/uploads/2019/03/LAS_1_4_r14.pdf) page 10). 
It would be great to get this value displayed as UTC in the identification results (for example along with the GpsTime or as a derived attribute). 

Sample-Point: 
Time-Value value stored in las-File (Adjusted Standard GPS Time): 1375406941.3252351
Convert to Standard GPS Time (add 1000000000): 1375406941.3252351
Convert to UTC (Seconds form 1980-01-06 00:00:00 UTC): 2023-08-07 01:28:43.3252351 UTC
See https://www.andrews.edu/~tzs/timeconv/timeconvert.php?

Peter

**Comment by wonder-sk** [comment]
Fixed in https://github.com/qgis/QGIS/pull/59383
