### ISSUE TITLE
QGIS uninstalling itself / Core subfolders going missing seemingly randomly.

### ISSUE THREAD

**Issue by ProneticWilliam** [qgis/QGIS#58698]
### What is the bug or the crash?

Multiple people from 2 of our separate client companies have reported to us that occasionally, seemingly randomly, they log on and find that QGIS has uninstalled itself. The only common factor between them I can think of is that they both use Heimdal antivirus, however I can't find any evidence of Heimdal removing or blocking any files in it's logs. I also haven't found any log files or events in Windows that can provide any insight.

This issue has been reported before for another user (https://github.com/qgis/QGIS/issues/58282) but it hasn't helped me so far.

Both companies have been using the latest release at the time of install (3.38.2 Grenoble most recently), but i've also tried installing 3.34.10 Prizren LTR for them and it doesn't seem to make a difference. Everytime i've installed QGIS, i've used the MSI installers.

Everyone affected has been using Windows 11 Pro

I've noticed that when this happens, not all files are removed. Despite this, a fresh install is required. I've attached a screenshot of what's leftover from previous versions that have had this problem. 

Normally this issue is quite rare, but for one individual it has occurred multiple times in a single week.

I hope this is enough information, but please ask questions if you need to. If anyone can confirm that this isn't a QGIS-specific problem, please can you point me in the right direction for troubleshooting?

![Screenshot 2024-09-12 144656](https://github.com/user-attachments/assets/9caa86de-6eda-4acb-ae9e-273deb07561e)

### Steps to reproduce the issue

Unable to reproduce, I have installed QGIS 3.34.10 on my own machine and not had any problems so far. Other people from both companies either don't have this problem, or it's extremely rare.

### Versions

This is the version installed on my PC.

QGIS version
3.34.10-Prizren
QGIS code revision
113de9e1
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I work for an MSP, and 2 of our client companies use QGIS.

**Comment by agiudiceandrea** [comment]
See a previous report of a similar issue: https://github.com/qgis/QGIS/issues/58282.

**Comment by ProneticWilliam** [comment]
This morning, the issue was reported to me again. I spent some time checking the antivirus on the local machine instead of the admin centre, and found that qgis-bin.exe and qgis-ltr-bin.exe were both being blocked. I've added an exclusion in the admin centre and reinstalled QGIS, so now i'll just wait and see if the issue reoccurs.

![Screenshot 2024-09-13 112110 (2)](https://github.com/user-attachments/assets/eecdd38f-8fa9-4b77-8005-29151269f975)

**Comment by KathrynRoseW** [comment]
Did you find a solution? It was me who made the post you were referring to - and my company also uses Heimdal antivirus. I have had e-mail correspondances with them, but to no avail. I figured it was Heimdal, but they denied it at first, then agreed it might be them patching it without success, but had no solution in the end.

**Comment by ProneticWilliam** [comment]
> Did you find a solution? It was me who made the post you were referring to - and my company also uses Heimdal antivirus. I have had e-mail correspondances with them, but to no avail. I figured it was Heimdal, but they denied it at first, then agreed it might be them patching it without success, but had no solution in the end.


Kathryn,

I figured out that Heimdal's Zero-Trust Execution Protection (ZTEP) was blocking the QGIS executable(s), which is what causes it to go missing.
I added an exclusion for the QGIS file path to Group Policy from the Heimdal Dashboard and have not had any reports of QGIS being blocked since then, almost a month ago now. 
I won't claim to be an expert on configuring Heimdal, so I'm not sure if that's the safest, most elegant or best practice solution, but it allows the exclusion to apply to both of my client companies. I've linked some of Heimdal's knowledge base articles that you might find helpful, as well.

https://support.heimdalsecurity.com/hc/en-us/articles/360001861477-Assigning-a-Group-Policy-to-an-endpoint-or-a-group-of-endpoints
https://support.heimdalsecurity.com/hc/en-us/articles/360009168138-Next-Gen-Antivirus-MDM

**Comment by KathrynRoseW** [comment]
Hi William,

Thank you so much for the suggestion, it is very helpful and appreciated! 

I have struggled with this alongside Heimdal Support, and some employees had this happen on a daily basis much to their frustration. Your solution makes sense.

**Comment by TheITcrowd123** [comment]
Good morning, I have the same problem. I don't use Hemida, the classic Windows Defender antivirus. What do you recommend to solve the problem?

**Comment by ProneticWilliam** [comment]
> Good morning, I have the same problem. I don't use Hemida, the classic Windows Defender antivirus. What do you recommend to solve the problem?

Hi,

You might want to start by checking the protection history for your PC in Windows Defender inside Windows Security to see if anything QGIS-related is being quarantined. If there is anything blocked by Windows Defender, you should be able to add an exclusion for it, and then reinstall QGIS. 

If it's not being blocked by Windows Defender, then i'm not quite sure. Do you have any other security software (AV / EDR / Zero-Trust) installed?

**Comment by TheITcrowd123** [comment]
I went to the Windows defence history and apparently QGIS is not reported. i have only windows defender

**Comment by agiudiceandrea** [comment]
@TheITcrowd123, as already written, QGIS doesn't and cannot uninstall automatically itself. So you need to investigate what's going on in your system.
