### ISSUE TITLE
Stamen web maps not working

### ISSUE THREAD

**Issue by bvjohnson87** [qgis/QGIS#58700]
### What is the bug or the crash?

When I add a stamen web map (such as Terrain) through Quick Map Services, the layer shows in the table of contents, but nothing shows in the map.  This was just working fine a couple months ago.  Did something change?

### Steps to reproduce the issue

Go to Web>Quick Map Services>Stamen
Choose Stamen Terrain
The layer adds to my table of contents but nothing shows in the map.  Even when zooming and panning.

### Versions

QGIS version
3.34.10-Prizren
QGIS code revision
113de9e1
Qt version
5.15.13
Python version
3.12.5
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
quick_map_services
0.19.34
SRTM-Downloader
3.2.2
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@bvjohnson87, thanks for reporting. The issue is not due to QGIS. You need to obtain an API key https://docs.stadiamaps.com/guides/migrating-from-stamen-map-tiles/.

**Comment by bvjohnson87** [comment]
Than you, this is very helpful!
