### ISSUE TITLE
expression coding hint is blocking the cursor line 

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#58720]
### What is the bug or the crash?

Often, when typing an expression in the expression builder, there is a coding hint popping up, suggesting the next part of the expression. However, also often this is actually blocking the line where the cursor is, so you can't see what your typing.

![afbeelding](https://github.com/user-attachments/assets/fa992a29-c367-4efd-a5db-f86bc5966cf1)

It would be nice if this coding hint is moved to somewhere where it doesn't block the cursor.
For instance, the autocomplete suggestions are always below the cursor.
![afbeelding](https://github.com/user-attachments/assets/80923738-50ae-4f9c-b0e8-99f063b01491)

### Steps to reproduce the issue

Open the expression builder, and start building an expression which uses multiple elements, such as concatenate.
Start writing the expression, and type , after the first element. This will trigger the coding hint.
It will not always block the cursor line, or sometimes block it partially, but at times it will block the cursor line. This behaviour might be dependent on screen sizes, resolutions, or interface settings.

Therefore I think it would be great to move the coding hint to somewhere were it will for sure not block the cursor line.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-versie | 3.38.2-Grenoble | QGIS code revisie | 130c432394
-- | -- | -- | --
Qt versie | 5.15.13
Python versie | 3.12.5
GDAL/OGR versie | 3.9.2
PROJ versie | 9.4.0
EPSG-register databaseversie | v11.004 (2024-02-24)
GEOS versie | 3.12.2-CAPI-1.18.2
SQLite versie | 3.45.1
PDAL versie | 2.6.3
PostgreSQL client versie | 16.2
SpatiaLite versie | 5.1.0
QWT versie | 6.2.0
QScintilla2 versie | 2.14.1
OS versie | Windows 10 Version 2009
  |   |   |  
Actieve Python plug-ins
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-versie
3.38.2-Grenoble
QGIS code revisie
[130c432394](https://github.com/qgis/QGIS/commit/130c432394)
Qt versie
5.15.13
Python versie
3.12.5
GDAL/OGR versie
3.9.2
PROJ versie
9.4.0
EPSG-register databaseversie
v11.004 (2024-02-24)
GEOS versie
3.12.2-CAPI-1.18.2
SQLite versie
3.45.1
PDAL versie
2.6.3
PostgreSQL client versie
16.2
SpatiaLite versie
5.1.0
QWT versie
6.2.0
QScintilla2 versie
2.14.1
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
The issue also occurs using the Python console
![image](https://github.com/user-attachments/assets/299661cf-f2cf-45ba-9a94-8d0832fe2642)
