### ISSUE TITLE
Random points in polygon does not produce the desired number of points

### ISSUE THREAD

**Issue by belg4mit** [qgis/QGIS#58739]
### What is the bug or the crash?

Random points in polygon does not produce the desired number of points

### Steps to reproduce the issue

Specify a field to create random points in a polygon with the default limit of 0 units permitted between points and very rarely do you end up with enough points to represent the sum of all the values in the specified field (once eliminating any bogus points for zero/null field values). Frequently it is quite off. With no restrictions on proximity, the tool should be creating exactly as many points as it is told, only the location should be random, not the count.

### Versions

Grenoble

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@belg4mit, thanks for reporting. It would be useful is you provided a sample layer and the parameters' value to set for the processing algorithm in order to replicate the issue.
