### ISSUE TITLE
Vector problem

### ISSUE THREAD

**Issue by Bamodi** [qgis/QGIS#58735]
### What is the bug or the crash?

I cannot use the vector function. Every time I click the vector button, it will turn blue without showing its function. Should I download the APP again or install some plug-in?

### Steps to reproduce the issue

![Screenshot 2024-09-13 231212](https://github.com/user-attachments/assets/624d2d36-5d40-4ef7-9556-ce8cae24744c)

### Versions

QGIS version
3.34.9-Prizren
QGIS code revision
cbbc7bdf
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
grassprovider
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Bamodi, you need to enable the Processing core plugin  https://docs.qgis.org/3.34/en/docs/user_manual/processing/intro.html#introduction
