### ISSUE TITLE
Random Points in Polygons behaves unexpectedly

### ISSUE THREAD

**Issue by belg4mit** [qgis/QGIS#58737]
### What is the bug or the crash?

Although the on-screen description of this feature explains that a point is created for every feature in the source layer, the principle of least surprise would suggest that when the number of points to create is specified by a field that polygons with a null or zero value for the given value should be skipped. Otherwise one can end up with incorrect results if one does not notice this counter-intuitive behavior and removes the null entries. If there is some need for null points, it should be via checkbox which is unchecked by default if a field is used for the point count.

### Steps to reproduce the issue

Select a polygon layer with a sparse numeric field and use said field as the point count for this tool.

### Versions

Grenobile

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Thanks for reporting. As a workaround, you could use the expression `coalesce("field_name", 0)` as data-defined override property in order to make the algorithm create no point for features with null value in the "field_name" field.
