### ISSUE TITLE
Crash on Menu.Layer.Properites command

### ISSUE THREAD

**Issue by EmAlvin** [qgis/QGIS#58775]
## User Feedback

Well, before this crash I updated the QField plugin (QGis notified me about an available upgrade of that plugin); then I opened a recent simple project (that I had previously synched with QField back and forth in the past days); then I walked around the map of the project; then I deleted 2 points on a shapefile points layer; QGist warned me I was not in edit mode; I entered edit mode and deleted those 2 points. Finally I opened the layer properties page from the menu bar. I actually tried to do so because, after a while, QGis crashed asking me to report what I am writing. Have luck!

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001228 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QObject::parent :
QLayout::addChildWidget :
QStackedLayout::insertWidget :
QgsOptionsDialogBase::addPage :
QgsLayerPropertiesDialog::addPropertiesPageFactory :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.10-Prizren
QGIS code revision: 113de9e1
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

menu -> Layer -> Properties

### Versions

QGIS Version: 3.34.10-Prizren
QGIS code revision: 113de9e1
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
If reproducible, this is a bug in the QField plugin and needs to be reported to the QField authors
