### ISSUE TITLE
In Qgis 3.34.4 / 3.38.3 vector layer saved as KML does not allow deleting of polygon features.

### ISSUE THREAD

**Issue by beng-tang** [qgis/QGIS#58780]
### What is the bug or the crash?

In Qgis 3.34.4 / 3.38.3 vector layer saved as KML does not allow deleting of polygon features.
When a polygon feature is selected, the dustbin icon is greyed out. Pressing the delete key results in an error message saying Provider does not support deletion.

### Steps to reproduce the issue

1. Open Qgis 3.34.4 / 3.38.3 
2. Create a new scratch layer using the icon in the toolbar to do so. My layer settings are shown in the image below.
![kmlbug1](https://github.com/user-attachments/assets/459c1870-c31e-465f-8228-6201e78bf2e7)

3. Draw some polygons using the icon in the toolbar to open the draw polygon function.
4. Save the layer as a KML file.
![kmlbug3](https://github.com/user-attachments/assets/ea757110-6d25-4ad2-baf3-f70a0183e67f)

5. Select one of the polygons you drew in the layer you just saved as a KML file while the layer is still in edit mode.
6. Try to delete it by pressing Del.
![kmlbug5](https://github.com/user-attachments/assets/7f66314b-7071-423f-90a6-ff529b7fc1ec)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.38.3-Grenoble | QGIS code revision | 37f9e6efeec
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.4
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Linux Mint 22
  |   |   |  
Active Python plugins
Group_and_Sort_Layers | 1.2
DigitizingTools | 1.5.2
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.38.3-Grenoble
QGIS code revision
[37f9e6efeec](https://github.com/qgis/QGIS/commit/37f9e6efeec)
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.4
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PostgreSQL client version
16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
SpatiaLite version
5.1.0
QWT version
6.1.4
QScintilla2 version
2.14.1
OS version
Linux Mint 22

Active Python plugins
Group_and_Sort_Layers
1.2
DigitizingTools
1.5.2
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This happens in Qgis 3.34.4 (the Linux Mint repository version) and 3.38.3, running in Linux Mint 22

**Comment by agiudiceandrea** [comment]
Not sure if it is an actual missing feature of the LIBKML driver or if it is a bug in the OGR provider.

**Comment by rouault** [comment]
> Not sure if it is an actual missing capability of the GDAL/OGR LIBKML driver

It was indeed lacking. Queue for GDAL 3.10 in https://github.com/OSGeo/gdal/pull/10840
