### ISSUE TITLE
Bub/Crash opening a project in QGIS

### ISSUE THREAD

**Issue by rtdupree** [qgis/QGIS#58802]
## User Feedback

I've tried to open a few different projects, and QGIS crashes just before the project can open.  Not sure if it is a "bug" issue with a file I recently loaded or something else.  Any help would be greatly appreciated.  Thank you in advance.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006144 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.3-Maidenhead
QGIS code revision: 2df96554
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

## User Feedback

I've tried to open a few different projects, and QGIS crashes just before the project can open.  Not sure if it is a "bug" issue with a file I recently loaded or something else.  Any help would be greatly appreciated.  Thank you in advance.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006144 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsCustomization::preNotify :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.3-Maidenhead
QGIS code revision: 2df96554
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Versions

Version 3.36.3-Maidenhead

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@rtdupree, QGIS 3.36 is no longer supported. Please try if the issue occurs also running a currently supported QGIS version and using a new QGIS user profile without any external third-party plugin installed.
If it does, please provide a sample project and layer with which the issue occurs.

**Comment by rtdupree** [comment]
Thanks Andrea.  I downloaded the latest QGIS and also figured out it was a
plugin causing the problem.  All is resolved.

Thanks again.
Best,
Ryan
