### ISSUE TITLE
Incorrect display of menus and toolbars

### ISSUE THREAD

**Issue by tbalay** [qgis/QGIS#58801]
### What is the bug or the crash?

Menus and toolbars are not displayed correctly and completely.

Just look at this screenshot :

https://github.com/user-attachments/assets/7c2508f3-78dc-4edc-9646-337700cabd56

### Steps to reproduce the issue

For menus : just point mouse on it.

### Versions

Version de QGIS | 3.38.3-Grenoble | Révision du code | 37f9e6efeec
-- | -- | -- | --
Version de Qt | 5.15.13
Version de Python | 3.12.3
Version de GDAL/OGR | 3.8.4
Version de Proj | 9.4.0
Version de la base de données du registre EPSG | v11.004 (2024-02-24)
Version de GEOS | 3.12.1-CAPI-1.18.1
Version de SQLite | 3.45.1
Version du client PostgreSQL | 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.4
Version de QScintilla2 | 2.14.1
Version de l'OS | Ubuntu 24.04.1 LTS
  |   |   |  
Extensions Python actives
quick_map_services | 0.19.34
grassprovider | 2.12.99
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>Version de QGIS
3.38.3-Grenoble
Révision du code
[37f9e6efeec](https://github.com/qgis/QGIS/commit/37f9e6efeec)
Version de Qt
5.15.13
Version de Python
3.12.3
Version de GDAL/OGR
3.8.4
Version de Proj
9.4.0
Version de la base de données du registre EPSG
v11.004 (2024-02-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.45.1
Version du client PostgreSQL
16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
Version de SpatiaLite
5.1.0
Version de QWT
6.1.4
Version de QScintilla2
2.14.1
Version de l'OS
Ubuntu 24.04.1 LTS

Extensions Python actives
quick_map_services
0.19.34
grassprovider
2.12.99
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by AhmadMahmoodRana** [comment]
maybe this will help

https://bit.ly/4eugCty
If you don't have the c compliator, install it.(gcc or clang)

**Comment by tbalay** [comment]
> maybe this will help
> 
> https://bit.ly/4eugCty If you don't have the c compliator, install it.(gcc or clang)

There is something wrong with your file : 
![image](https://github.com/user-attachments/assets/5a88da2f-e21e-4ff7-bc63-2a35c1807bbc)

**Comment by agiudiceandrea** [comment]
@tbalay, it looks like the issue has been already previously reported at https://github.com/qgis/QGIS/issues/57511 https://github.com/qgis/QGIS/issues/57345.
