### ISSUE TITLE
Crash upon switching atlas page

### ISSUE THREAD

**Issue by feldmrob** [qgis/QGIS#58823]
## User Feedback

Advancing between atlas pages

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000083ac (most recent call first):
<no Python frame>
Windows fatal exception: code 0xc0000374

Thread 0x000083ac (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsEffectStack::QgsEffectStack :
QgsEffectStack::clone :
QgsFeatureRenderer::copyRendererData :
QgsMergedFeatureRenderer::clone :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayer::createMapRenderer :
QgsMapRendererJob::prepareJobs :
QgsMapRendererCustomPainterJob::startPrivate :
QgsLayoutItemMap::recreateCachedImageInBackground :
QObject::qt_static_metacall :
QTimer::timerEvent :
QObject::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QEventDispatcherWin32Private::sendTimerEvent :
QEventDispatcherWin32::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.34.5-Prizren
QGIS code revision: 4b308492
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22621

### Steps to reproduce the issue

In Layout, use selector to change atlas page.

### Versions

QGIS Version: 3.34.5-Prizren
QGIS code revision: 4b308492
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is fixed in newer QGIS versions

**Comment by feldmrob** [comment]
Much appreciated, thank you!
