### ISSUE TITLE
 ImportError at the start 

### ISSUE THREAD

**Issue by Felagund-89** [qgis/QGIS#58840]
### What is the bug or the crash?

Hi everyone. After using QGIS 3.34.11 Prizren and QSWAT3_12 without a problem for over two months, I encountered an error upon entering the software, which caused the SWAT button to disappear too. The error message is as follows:

2024-09-23T11:03:33     INFO    QSWAT failed to import Visualise: Traceback (most recent call last):
              File "C:\Users/BARU74/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWAT3_12\QSWAT\qswat.py", line 68, in
              from .visualise import Visualise # type: ignore # @UnresolvedImport
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\Users/BARU74/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\QSWAT3_12\QSWAT\visualise.py", line 63, in
              from .jenks import jenks # type: ignore # @UnresolvedImport
              ^^^^^^^^^^^^^^^^^^^^^^^^
              File "C:\PROGRA~1/QGIS33~1.9/apps/qgis-ltr/./python\qgis\utils.py", line 892, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              File "jenks.pyx", line 1, in init QSWAT3.QSWAT.jenks
             ImportError: numpy.core.multiarray failed to import (auto-generated because you didn't call 'numpy.import_array()' after cimporting numpy; use 'numpy._import_array' to disable if you are certain you don't need it).
             
2024-09-23T11:03:33     INFO    Failed to load Cython module: wrong architecture?

I am not sure if this issue originated from QGIS or QSWAT, but I could not figure out what to do, so any help on solving this error is most welcome.

### Steps to reproduce the issue

![qswat plugin](https://github.com/user-attachments/assets/5c55bf6b-d510-4e65-82ba-3490a3d7dbbf)
![image](https://github.com/user-attachments/assets/19d64e46-2ec7-4f11-b89e-398e9e904932)

### Versions

QGIS version
3.34.11-Prizren
QGIS code revision
2904bcec
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
QSWAT
2.0.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Not a QGIS issue.

Please report this on QSWAT repo : https://github.com/swat-model/QSWAT/issues/new
