### ISSUE TITLE
Basic editing using "Automatic Transaction Groups" generates a critical error

### ISSUE THREAD

**Issue by jrosleo** [qgis/QGIS#58845]
### What is the bug or the crash?

Basic editing fails in the context that is described.

### Steps to reproduce the issue

1. Create a Geopackage and add two related tables (1-n). In this [template](https://github.com/user-attachments/files/17099746/template.zip) there are a `geoname` point layer and a non geometric `geoname_type` table. Both tables have and **id** and **name** field. The first one, also a **type_id** field.
2. Load the tables in a empty QGIS project.
3. Activate **Automatic Transaction Groups** and **Evaluate default values on provider side** project options.  
![img_1](https://github.com/user-attachments/assets/809398d4-6e70-4c9c-8de6-7122f17d16b1)
4. Toogle Editing on and create a point feature, type a name, let the type_id empty and press OK. 
![img_2](https://github.com/user-attachments/assets/4df3b4f5-84c9-49f1-a5db-3edd12c7541d)
5. Toogle Editing off and press the Save button.
6. Toogle Editing on and this error appears. 
![img_3](https://github.com/user-attachments/assets/0b0a1be6-9bb4-4c91-8328-b3b39e98f2a0)

### Versions

QGIS version
3.38.3-Grenoble
QGIS code revision
37f9e6efee
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
linking_relation_editor
v1.3.0
QgisModelBaker
v7.8.3
qgis_versioning
1.0
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

If SpatiaLite is used instead of GeoPackage the error does not occur.

**Comment by elpaso** [comment]
You didn't tell how you configured the relations and the form and I cannot reproduce, can you please attach the project too?

**Comment by nyalldawson** [comment]
@elpaso there's an existing test for this which is failing when run on newer gdal versions (ie for the qt6 build)

**Comment by elpaso** [comment]
> In case it is of interest, I attach the project: [test_project.zip](https://github.com/user-attachments/files/17329663/test_project.zip)

Thank you for the test project. Still no luck to reproduce the issue: all I get is a warning:
`2024-10-10T18:02:23     WARNING    Unbalanced call to leaveUpdateMode() w.r.t. enterUpdateMode()`

**Comment by jrosleo** [comment]
I hope the [video](https://github.com/user-attachments/assets/5e16d2f9-1be5-4d24-aa9a-1b3a325464dd) is useful.

**Comment by elpaso** [comment]
> I hope the [video](https://github.com/user-attachments/assets/5e16d2f9-1be5-4d24-aa9a-1b3a325464dd) is useful.

It was, thank you, I can now reproduce the issue with GDAL master.
