### ISSUE TITLE
Installation failed on Mac 15.o

### ISSUE THREAD

**Issue by momeni133** [qgis/QGIS#58846]
### What is the bug or the crash?

It seems that Mac 15 doesn't support clang 14 anymore. 
When I try to install QGIS on my MacBook using 'sudo port install qgis3 +grass'
I receive the below error message: 
"Computing dependencies for qgis3-ltr
clang-14 is known to fail. Try to install anyway? [y/N]: n
Error: clang-14 is known to fail
Error: Follow https://guide.macports.org/#project.tickets if you believe there"

### Steps to reproduce the issue

"Computing dependencies for qgis3-ltr
clang-14 is known to fail. Try to install anyway? [y/N]: n
Error: clang-14 is known to fail
Error: Follow https://guide.macports.org/#project.tickets if you believe there"

### Versions

latest version

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is an issue in the macports build only, which isn't officially supported. You'll need to report it to macports instead.

**Comment by bryanrscott** [comment]
Ticket created on macports
https://trac.macports.org/ticket/70914#ticket
