### ISSUE TITLE
QGIS closes when additional column added to an attribute table for a layer

### ISSUE THREAD

**Issue by amj1711** [qgis/QGIS#58842]
### What is the bug or the crash?

I am adding a column to a vector layer attribute table, called TITLE REF, set as text and 20 characters. When clicking okay QGIS immediately shuts down.

I then get the Apple, your program closed down unexpectedly and gives the following information;

-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               QGIS [32315]
Path:                  /Applications/QGIS-LTR.app/Contents/MacOS/QGIS
Identifier:            org.qgis.qgis3
Version:               3.34.11 (3.34.11 ())
Code Type:             X86-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2024-09-23 15:00:08.3792 +0100
OS Version:            macOS 14.6.1 (23G93)
Report Version:        12
Bridge OS Version:     8.6 (21P6074)
Anonymous UUID:        E8FD65C6-FBA0-E3F1-FA0E-2135D83FB1B8

Sleep/Wake UUID:       3C910DEB-7091-4D32-9F2B-1E9D981DE73A

Time Awake Since Boot: 35000 seconds
Time Since Wake:       9102 seconds

System Integrity Protection: enabled

Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000008
Exception Codes:       0x0000000000000001, 0x0000000000000008

Termination Reason:    Namespace SIGNAL, Code 11 Segmentation fault: 11
Terminating Process:   QGIS [32315]

VM Region Info: 0x8 is not in any region.  Bytes before following region: 4481605624
      REGION TYPE                    START - END         [ VSIZE] PRT/MAX SHRMOD  REGION DETAIL
      UNUSED SPACE AT START
--->  
      __TEXT                      10b1fe000-10b266000    [  416K] r-x/r-x SM=COW  /Applications/QGIS-LTR.app/Contents/MacOS/QGIS

Kernel Triage:
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter
VM - (arg = 0x3) mach_vm_allocate_kernel failed within call to vm_map_enter

### Steps to reproduce the issue

Open an attribute table
Select Edit
Add a column
Click Okay

### Versions

QGIS Version:               3.34.11 (3.34.11 ())
OS Version:            macOS 14.6.1 (23G93)

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by Ipickedausername** [comment]
I have the same crashes, I think. When adding / removing a column (even when selecting a field in the attribute form after changing the default value of another field). 

But I have never been able to reproduce these crashes. It seems random. 

I hope your issue will help !

**Comment by agiudiceandrea** [comment]
@Ipickedausername, what is the exact QGIS version are you using and on which Operative System?

**Comment by jgrocha** [comment]
Not able to reproduce the error with the current master.

I've created a new shapefile, then I added the new column. No problem.

I've edited the shapefile and added two points.

Then I added another field. No problem.

![image](https://github.com/user-attachments/assets/2c83175c-6975-4f90-9986-921cc66b6c28)

@amj1711 Where is your shapefile? Can you check if you have permission to read/write the shapefile (and the folder where it is)?

**Comment by Ipickedausername** [comment]
@agiudiceandrea I'm working on this version 3.36.1-Maidenhead ; using Windows 10. 
I cannot try another version for now, as long as I don't have a proper internet access..
But I don't want to change the topic of this issue. If I find a way to reproduce the issue, I will open another issue.
