### ISSUE TITLE
Persistent crashing while editing legend label text in layout

### ISSUE THREAD

**Issue by MoltenRainbow** [qgis/QGIS#58853]
## User Feedback

Editing text for legend units in the layout screen. This has been persistently happening for the same file the whole morning. I can maybe make one or two edits in the legend (removing or adding units, editing label text, etc) before the whole program freezes and crashes. 

It is a large map (size A0) with several complex layers and symbology based on categories. 
This is an issue that has been happening for a longer period of time already, especially with larger project files

Edit: attempted step by step crash trigger: 
- Open QGis 3.28.11 and load project file that contains a large number of layers (some 10+ at least).
- most of the layers are the mapinfo .TAB file format, though several of .SHP and .GEOJSON formats are also present.
- Several of these layers have a category-based symbology, which all need to be combined to form one big legend in the layout. 
- Layout size A0 to fit the entire map, scale is 1:xx 
- start putting the legen together, this is where the crashes start happening, most often when: 

1) often by the third categorised layer being added into an already existing legend 
Or 
2) when editing a label text, editing symbology, copy-pasting label texts or even doing as much as highlighting text and then pressing backspace to delete a label text. All of these apply for already existing legend items (in case it didn't crash while adding the items at the previous bullet point). 

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000054dc (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsLayerTreeModel::node2index :
QgsLayerTreeView::updateExpandedStateFromNode :
QgsLayerTreeView::modelRowsInserted :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QSortFilterProxyModel::insertRows :
QSortFilterProxyModel::sortRoleChanged :
QSortFilterProxyModel::qt_static_metacall :
QObject::qt_static_metacall :
QAbstractItemModel::endInsertRows :
QgsLayerTreeModel::addLegendToLayer :
QgsLayerTreeModel::refreshLayerLegend :
QgsLayoutLegendNodeWidget::labelChanged :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QWidgetTextControl::qt_static_metacall :
QWidgetTextControl::qt_metacall :
QObject::qt_static_metacall :
QTextDocumentPrivate::finishEdit :
QTextDocumentPrivate::remove :
QTextCursorPrivate::remove :
QTextCursor::deletePreviousChar :
QWidgetTextControl::isWordSelectionEnabled :
QWidgetTextControl::processEvent :
QWidgetTextControl::processEvent :
QPlainTextEdit::selectionChanged :
QPlainTextEdit::keyPressEvent :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.11-Firenze
QGIS code revision: b02458a196
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.2
Running against GDAL: 3.7.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

not really applicable I think? Since this error is related to crashing of the software while trying to edit label texts in the layout screen. 

### Versions

QGIS-versie
3.28.11-Firenze
QGIS code revisie
b02458a196
Qt versie
5.15.3
Python versie
3.9.5
GDAL/OGR versie
3.7.2
PROJ versie
9.3.0
EPSG-register databaseversie
v10.094 (2023-08-08)
GEOS versie
3.12.0-CAPI-1.18.0
SQLite versie
3.41.1
PDAL versie
2.5.5
PostgreSQL client versie
unknown
SpatiaLite versie
5.1.0
QWT versie
6.1.6
QScintilla2 versie
2.13.4
OS versie
Windows 10 Version 2009

Actieve Python plug-ins
archoltools
0.60
b4udignl2
2.3.0
FeatureGridCreator
3.0.0
pdokservicesplugin
5.1.1
profiletool
4.2.6
qgis_resource_sharing
1.1.0
QRectangleCreator
0.3
sminq
1.00
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by elpaso** [comment]
A test project and data and a detailed step-by-step description about how to trigger the crash would be useful.

**Comment by MoltenRainbow** [comment]
> A test project and data and a detailed step-by-step description about how to trigger the crash would be useful.

The issue is that there isn't much of a step by step description that I can provide, but I'll try my best and edit it into the original post. 

As for test data, how could I best supply that? Since the files are all local on a network server and such.

**Comment by elpaso** [comment]
> > A test project and data and a detailed step-by-step description about how to trigger the crash would be useful.
> 
> The issue is that there isn't much of a step by step description that I can provide, but I'll try my best and edit it into the original post.
> 
> As for test data, how could I best supply that? Since the files are all local on a network server and such.

You can try to create a small project and put the smallest possible sample of data in a GPKG file then zip it all together, then attach it here.

Bottom line is that a developer needs the procedure and if needed the project and data to reproduce the error on his/her local machine in order to debug it.
