### ISSUE TITLE
Layout manager: item snapping

### ISSUE THREAD

**Issue by 1511eq** [qgis/QGIS#58858]
### Feature description

When compiling multiple maps (items) together in layout manager it would be great if you could snap items together, as you can in vector graphics editors. So the edges would neatly snap together, without overlaping or gaps.

**Comment by YoannQDQ** [comment]
I'm not sure what you're asking for. Snapping is already implemented and seems to work fine. 
What version of QGIS are you on? Could you maybe add a screenshot to demonstrate the behavior you're expecting?

**Comment by antoniolocandro** [comment]
@1511eq You may want to check if the smart guide option is enabled 

https://github.com/user-attachments/assets/71b7836e-ae76-4129-ac32-e42f43074406
