### ISSUE TITLE
SLD, Server - Service=WMS&Request=GetStyles: LabelPlacement/Displacement malfunction

### ISSUE THREAD

**Issue by lorenzogrv** [qgis/QGIS#58862]
### What is the bug or the crash?

Under certain conditions, the WMS service does not include the `se:Displacement` of text's `se:LabelPlacement` within the StyledLayerDescriptor when it should.

Expected result: The StyledLayerDescriptor includes de LabelDisplacement whenever either of offsets (X, Y) are not equal to zero
Actual result: The information is missing when:  both values are `< 0` or one of the values is zero buy the other is  `< 0`

Let me ilustrate with examples. I'm talking about the text label offset which is configurable through the following dialog at qgis desktop:

![screenshot](https://github.com/user-attachments/assets/7f74cfe7-dd30-4a47-b1b4-0d6f8e119e22)

Some XML excerpts from the GetStyles request given different values:

**Correct** cases

```xml
<se:LabelPlacement>
<se:PointPlacement>
<se:AnchorPoint>
<se:AnchorPointX>1</se:AnchorPointX>
<se:AnchorPointY>0</se:AnchorPointY>
</se:AnchorPoint>
<se:Displacement>
<se:DisplacementX>4</se:DisplacementX>
<se:DisplacementY>12</se:DisplacementY>
</se:Displacement>
</se:PointPlacement>
</se:LabelPlacement>
```

```xml
<se:LabelPlacement>
<se:PointPlacement>
<se:AnchorPoint>
<se:AnchorPointX>1</se:AnchorPointX>
<se:AnchorPointY>0</se:AnchorPointY>
</se:AnchorPoint>
<se:Displacement>
<se:DisplacementX>4</se:DisplacementX>
<se:DisplacementY>-12</se:DisplacementY>
</se:Displacement>
</se:PointPlacement>
</se:LabelPlacement>
```

```xml
<se:LabelPlacement>
<se:PointPlacement>
<se:AnchorPoint>
<se:AnchorPointX>1</se:AnchorPointX>
<se:AnchorPointY>0</se:AnchorPointY>
</se:AnchorPoint>
<se:Displacement>
<se:DisplacementX>-4</se:DisplacementX>
<se:DisplacementY>12</se:DisplacementY>
</se:Displacement>
</se:PointPlacement>
</se:LabelPlacement>
```

```xml
<se:LabelPlacement>
<se:PointPlacement>
<se:AnchorPoint>
<se:AnchorPointX>1</se:AnchorPointX>
<se:AnchorPointY>0</se:AnchorPointY>
</se:AnchorPoint>
<se:Displacement>
<se:DisplacementX>0</se:DisplacementX>
<se:DisplacementY>12</se:DisplacementY>
</se:Displacement>
</se:PointPlacement>
</se:LabelPlacement>
```

**INCORRECT cases**: Same result for:

- `X = 0, Y = -12`
- `X = -4, Y = -12`
- `X = -4, Y = 0`

```xml
<se:LabelPlacement>
<se:PointPlacement>
<se:AnchorPoint>
<se:AnchorPointX>1</se:AnchorPointX>
<se:AnchorPointY>0</se:AnchorPointY>
</se:AnchorPoint>
</se:PointPlacement>
</se:LabelPlacement>
```

__

### Steps to reproduce the issue

1. Setup a proyect with one Point layer and one feature, i.e. at null island
2. Setup a simple label for that layer with any constant text for a sake of simplicity
3. Publish layer through QGisServer
4. For each offset pair:
    - Reconfigure the label text placement offset
    - Hit the `/?service=WMS&request=GetStyles&layers=test_layer` endpoint to obtain the StyledLayerDescriptor
    - Observe the `NamedLayer/UserStyle/se:FeatureTypeStyle/se:Rule/se:TextSymbolizer/se:LabelPlacement` xml node to test for presence/absence of the expected `se:Displacement` node

### Versions

Server version:

```plain
QGIS 3.34.11-Prizren 'Prizren' (exported)
QGIS code branchRelease 3.34
Qt version 5.15.13
Python version 3.12.6
GDAL/OGR version 3.9.2
Compiled against PROJ 9.4.1
Running against PROJ 9.5.0
EPSG Registry database version v11.016 (2024-08-31)
GEOS version 3.13.0-CAPI-1.19.0
SQLite version 3.46.1
OS Debian GNU/Linux trixie/sid
```

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I dived through source until <https://github.com/qgis/QGIS/blob/master/src/server/services/wms/qgswmsgetstyles.cpp>, but I don't have in-depth knowledge of qgis source code internals, so could not follow the `getSld` thing.

I'm pretty sure any qgis developer can find the place way faster than me, or at least provide indications so I can properly follow the source and submit a PR.

Thanks in advance

**Comment by elpaso** [comment]
Looks like it needs changes to `if ( settings.xOffset > 0 || settings.yOffset > 0 )`

**Comment by lorenzogrv** [comment]
Nice, learned a bit through changes at linked PR. Maybe some day I will be able to contribute code in addition to reports :sweat_smile:
