### ISSUE TITLE
Allow edit mode for GDB with OpenFileGDB driver

### ISSUE THREAD

**Issue by cvetelinandreevdreamix** [qgis/QGIS#58872]
### Feature description

On the official page of the open source driver https://gdal.org/en/latest/drivers/vector/openfilegdb.html says that it provides read, write and update access to vector layers of File Geodatabases (.gdb directories). I can't see the edit mode button enabled when I import a gdb directory into QGIS. I can confirm that I can edit gdb files with geopandas that rely on this driver.

Thank you!

**Comment by roya0045** [comment]
That's because you require v 3.6 of GDAL, if your version of QGIS doesn't have GDAL that is recent enough you can't edit GDB. I have a version with GDAL 3.7 and editing GDB is doable. I haven't tested raster reading though.

Regardless the feature you request already exist if you have the right dependencies.

**Comment by cvetelinandreevdreamix** [comment]
Thanks. It seems that the latest QGIS for my Mac M1 has 3.3.2 and that's the reason I can't edit them.

AFAICS I can't change the QGIS to use the gdal version I have installed with homebrew (3.9.2). So my chance is to use QGIS on Windows.

**Comment by agiudiceandrea** [comment]
@cvetelinandreevdreamix you can install QGIS on macOS also either from MacPorts or Conda.

**Comment by eflaten** [comment]
try this one:
https://github.com/opengisch/qgis-conda-builder

**Comment by cvetelinandreevdreamix** [comment]
Thanks. I use a windows machine and is working fine.

The condo build was taking too much time and space AFAIR.

Tsvetelin Andreev
+359 889 651 656
