### ISSUE TITLE
Delete expression in Default value + click on another field in the attribute form manager = Crash

### ISSUE THREAD

**Issue by Ipickedausername** [qgis/QGIS#58887]
### What is the bug or the crash?

QGIS crashes when I remove an expression from the default value and then click on another field while in the attribute form tab of the layer's properties.

### Steps to reproduce the issue

I've shared a project for you to try. 

1.   After opening the properties of layer 2, go to the attribute form and remove the expression in the default value for the field 'test_crash.' 
2.   Then, click on the field 'testcrash2' in the left panel.

This causes QGIS to crash.

[Test_project.zip](https://github.com/user-attachments/files/17160553/Test_project.zip)

https://github.com/user-attachments/assets/de6600b6-c752-46a7-b5bd-d41d9c5fd74a

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Version de QGIS | 3.36.1-Maidenhead | Révision du code | 3e589453
-- | -- | -- | --
Version de Qt | 5.15.3
Version de Python | 3.9.18
Version de GDAL/OGR | 3.8.4
Version de Proj | 9.3.1
Version de la base de données du registre EPSG | v10.098 (2023-11-24)
Version de GEOS | 3.12.1-CAPI-1.18.1
Version de SQLite | 3.41.1
Version de PDAL | 2.6.0
Version du client PostgreSQL | 16.2
Version de SpatiaLite | 5.1.0
Version de QWT | 6.1.6
Version de QScintilla2 | 2.13.4
Version de l'OS | Windows 10 Version 2009
  |   |   |  
Extensions Python actives
GroupStats | 2.2.7
mapswipetool_plugin | 1.3
networks | 2.7.19
OpenTopography-DEM-Downloader | 2.0
qfieldsync | v4.9.1
quick_map_services | 0.19.34
SemiAutomaticClassificationPlugin | 8.2.2
db_manager | 0.1.20
processing | 2.12.99

</body></html>Version de QGIS
3.36.1-Maidenhead
Révision du code
[3e589453](https://github.com/qgis/QGIS/commit/3e589453)
Version de Qt
5.15.3
Version de Python
3.9.18
Version de GDAL/OGR
3.8.4
Version de Proj
9.3.1
Version de la base de données du registre EPSG
v10.098 (2023-11-24)
Version de GEOS
3.12.1-CAPI-1.18.1
Version de SQLite
3.41.1
Version de PDAL
2.6.0
Version du client PostgreSQL
16.2
Version de SpatiaLite
5.1.0
Version de QWT
6.1.6
Version de QScintilla2
2.13.4
Version de l'OS
Windows 10 Version 2009

Extensions Python actives
GroupStats
2.2.7
mapswipetool_plugin
1.3
networks
2.7.19
OpenTopography-DEM-Downloader
2.0
qfieldsync
v4.9.1
quick_map_services
0.19.34
SemiAutomaticClassificationPlugin
8.2.2
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I cannot download another version of QGIS, this one is no longer supported I think.
Maybe the latest version doesn't have it anymore? 

And this is what the crash report says: 

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00003198 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 305 in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 250 in recv
    buf = self._recv_bytes()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 576 in _handle_results
    task = get()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Thread 0x00002710 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 528 in _handle_tasks
    for taskseq, set_length in iter(taskqueue.get, None):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Thread 0x000030a4 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 811 in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 879 in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 499 in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 519 in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Current thread 0x000035b8 (most recent call first):

Stack Trace

QgsAttributeTypeDialog::editorWidgetType :
QgsAttributesFormProperties::storeAttributeTypeDialog :
QgsAttributesFormProperties::loadAttributeSpecificEditor :
QgsAttributesFormProperties::onAttributeSelectionChanged :
QObject::qt_static_metacall :
QTreeWidgetItem::`default constructor closure' :
QTreeWidget::qt_static_metacall :
QObject::qt_static_metacall :
QItemSelectionModel::emitSelectionChanged :
QItemSelectionModel::select :
QTreeViewPrivate::select :
QTreeView::setSelection :
QAbstractItemView::mousePressEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QDialog::exec :
QgisApp::showLayerProperties :
QgisApp::layerProperties :
QgisApp::layerTreeViewDoubleClicked :
QObject::qt_static_metacall :
QAbstractItemView::doubleClicked :
QTreeView::mouseDoubleClickEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.3

**Comment by nicogodet** [comment]
3.36.1 is a bit old, could you update to 3.36.11 ?

Anyway, I can't reproduce on 3.38.3 but still there is a strange behavior in GUI.
![Animation8](https://github.com/user-attachments/assets/6e55a4ee-7436-4c18-b18d-6106334f5021)

See, it needs 2 clicks after altering default value lineedit to change field

**Comment by mblesius** [comment]
I Just tested with https://github.com/qgis/QGIS/commit/bfbbdac22ab3b95c862240a3aa443461b575b408 from QGIS Master 3.39.0 and I observe the same behavior as described by @nicogodet 
> See, it needs 2 clicks after altering default value lineedit to change field

Under 3.34.11 it seems to work as I can't reproduce either of the two behaviors.

**Comment by Ipickedausername** [comment]
Great if there is no more crash in the last version.
Should I leave this issue open, regarding the second issue raised by @nicogodet ?
