### ISSUE TITLE
Python notification when starting QGIS 3.38

### ISSUE THREAD

**Issue by stinanickel** [qgis/QGIS#58889]
### What is the bug or the crash?

When starting QGIS3.38 it says: 
Ein Fehler trat bei der Ausführung von Python-Code auf: 

TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:   overload 1: argument 'type' has unexpected type 'int'   overload 2: argument 1 has unexpected type 'str' 
Traceback (most recent call last):
  File "/Users/dt/Library/Application Support/QGIS/QGIS3/profiles/default/python/plugins/localmaxfilter/interfaces/localmaxfilter_processing.py", line 101, in initAlgorithm
    param_window = QgsProcessingParameterNumber(
TypeError: QgsProcessingParameterNumber(): arguments did not match any overloaded call:
  overload 1: argument 'type' has unexpected type 'int'
  overload 2: argument 1 has unexpected type 'str'

Python-Version: 3.9.5 (default, Sep 10 2021, 16:18:19) [Clang 12.0.5 (clang-1205.0.22.11)] 
QGIS-Version: 3.38.3-Grenoble Grenoble, 37f9e6efeec 

Python-Pfad:
/Users/dt/Library/Application ....

Do I nee a different Version of Python installled?
After dismissing this notifiacation I could work normal. No crashing.

### Steps to reproduce the issue

This is the Mac I strated QGIS 3.38:  

Modellname:	MacBook Pro
  Modell-Identifizierung:	MacBookPro15,1
  Prozessortyp:	8-Core Intel Core i9
  Prozessorgeschwindigkeit:	2,3 GHz
  Anzahl der Prozessoren:	1
  Gesamtanzahl der Kerne:	8
  L2-Cache (pro Kern):	256 KB
  L3-Cache:	16 MB
  Hyper-Threading Technologie:	Aktiviert
  Speicher:	16 GB
  Systemfirmwareversion:	1968.140.7.0.0 (iBridge: 20.16.6072.0.0,0)
  Hardware-UUID:	9F300828-FCE6-55F3-BE9E-77CF8EAECCE9
  Bereitstellungs-UDID:	9F300828-FCE6-55F3-BE9E-77CF8EAECCE9
  Status der Aktivierungssperre:	Aktiviert

### Versions

QGIS 3.38

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by roya0045** [comment]
That's a plugin issue, please report it to the author, it isn't caused by QGIS itself.
