### ISSUE TITLE
Add expression variable to get the current timestamp of the temporal controller

### ISSUE THREAD

**Issue by kannes** [qgis/QGIS#58897]
### Feature description

Trying to style and animate some vector data that has one column per timestep (e.g. "2022-01-01", "2022-02-01") per feature I was surprised that I could not use an available expression variable to get the temporal controller's current timestamp.

Instead I had to calculate it using `@animation_start_time`, `@frame_timestep` and `@frame_number`.

It would be great if there was a `@animation_current_time` variable.

**Comment by nyalldawson** [comment]
It's already available- see  @map_start_time , @map_end_time

**Comment by kannes** [comment]
Oh, how did I miss that! Thanks.
