### ISSUE TITLE
OTB does not show up in the processing panel

### ISSUE THREAD

**Issue by BaBoWaGa** [qgis/QGIS#58929]
### What is the bug or the crash?

Hi, I have installed the latest version of QGIS LTR
I enabled OTB in the plugins, restarted QGIS, but it doesn't show the OTB provider, maybe it conflicts with other versions of OTB that I had installed for other versions of QGIS?

NB
The link in the plugin leads to this page

Greetings

### Steps to reproduce the issue

Open processing panel can't see OTB provider

### Versions

Versione di QGIS
3.34.11-Prizren
Revisione codice QGIS
2904bcec
Versione Qt
5.15.13
Versione Python
3.12.6
Versione GDAL/OGR
3.9.2
Versione PROJ
9.4.0
Versione database del Registro EPSG
v11.004 (2024-02-24)
Versione GEOS
3.12.2-CAPI-1.18.2
Versione SQLite
3.45.1
Versione PDAL
2.6.3
Versione client PostgreSQL
16.2
Versione SpatiaLite
5.1.0
Versione QWT
6.2.0
Versione QScintilla2
2.14.1
Versione SO
Windows 11 Version 2009
Plugins Python attivi
HCMGIS
24.8.27
nominatim
1.4.5
qgis-maptiler-plugin
3.3.2
quick_map_services
0.19.34
raster_cutter
0.6.1
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
The OTB plugin was demoted to a third party, community maintained plugin. It's no longer supported here.

**Comment by BaBoWaGa** [comment]
Thank you for replying, clicking on bug tracker of the plugin you are directed here ( see attachment )
![Screenshot 2024-10-01 113109](https://github.com/user-attachments/assets/e9f9ccea-938f-4847-8e2c-12c76fe320eb)

**Comment by agiudiceandrea** [comment]
@nyalldawson, the OrfeoToolbox provider plugin is still a core plugin in QGIS LTR 3.34.
@BaBoWaGa, you need to properly install OTB on your system and to properly configure the OrfeoToolbox provider plugin. Please see https://docs.qgis.org/3.34/en/docs/user_manual/processing/3rdParty.html#otb-applications.

**Comment by SpaceCyclist** [comment]
Hi, I'm a developer of OTB.
I'm posting here a reply in case people with the same problem come here.
The updated doc of OTB and plugin installation is here https://www.orfeo-toolbox.org/CookBook/QGISInterface.html .
Before plugging OTB with QGIS, OTB  needs some adjustments described here and for those with python > 3.8 to recompile bindings. All instructions are here https://www.orfeo-toolbox.org/CookBook/Installation.html#id1 .

The issue and further discussion about this problem are here https://gitlab.orfeo-toolbox.org/orfeotoolbox/otb-qgis-plugin/-/issues/5 , please use this issue if you have a related problem.

Thank you, Tristan from OTB team

**Comment by BaBoWaGa** [comment]
Hello everyone , sorry for the delay but my laptop motherboard failed. Thank you all for the clarification. I will try to make the changes you described.
