### ISSUE TITLE
Georefering plugin missing

### ISSUE THREAD

**Issue by Sandra9LA** [qgis/QGIS#58940]
### What is the bug or the crash?

I've downloaded today the QGIS latest version (not the Long-term version) and I just cannot find the georeferecing tool. 

### Steps to reproduce the issue

1. I go to "Manage and Install Plugins" and select "Georeference Extension" (is the only plugin for georeference I find)
2. I go to Raster menu and it is not there.

### Versions

3.38.3-Grenoble

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
See multiples existing issues (eg. https://github.com/qgis/QGIS/issues/49768)

Not a bug, Georeferencer has been moved to Layer menu since it can now (since 3.26), georeference vector data.
