### ISSUE TITLE
grass7:v.rast.stats fails with QGIS >= 3.34.10

### ISSUE THREAD

**Issue by a-benini-2** [qgis/QGIS#58961]
### What is the bug or the crash?

After updating _**QGIS LTR**_ from _**3.34.9**_ to _**3.34.10**_ `grass7:v.rast.stats` does not calculate univariate statistics from a raster map based on vector polygons. Instead of uploading statistics to new attribute columns, `grass7:v.rast.stats` returns these new attributes with only _**NULL**_ s as sole value. Further updating to _**QGIS LTR 3.34.11**_ hasn’t helped to overcome this issue. While running `grass7:v.rast.stats` with a parallel installed _**QGIS**_ version _**3.34.9**_ works fine.

My operating system is Windows 10.

### Steps to reproduce the issue

1. Go to _https://github.com/qgis/QGIS-Sample-Data_
2. Download _QGIS-Sample-Data-master.zip_ on the computer where you have _QGIS 3.34.11_ installed
3. unzip _QGIS-Sample-Data-master.zip_ --> _QGIS-Sample-Data-master_
4. Open _QGIS 3.34.11_ and start a new project
5. Go within folder _QGIS-Sample-Data-master_ to _~\qgis_sample_data\shapefiles\lakes.shp_ and _~\qgis_sample_data\raster\SR_50M_alaska_nad.tif_. Drag and drop these two files / layers into the new QGIS project you just started
6. Open the _Processing Toolbox_ and search for _v.rast.stats_
7. Open _v.rast.stats_ set _lakes_ as vector input and _SR_50M_alaska_nad_ as raster input, specify column prefix, optionally select 1 or more methods and change percentile. Leave _Advanced Parameters_ as they are.
![grafik](https://github.com/user-attachments/assets/2544e748-e39e-4bf1-85b1-f51d9c909ecf)
8. Press the _Run_ button and wait until `grass7:v.rast.stats` has finished. The log should reveal some error:
[log_file_v.rast.stats_QGIS_3.34.11.txt](https://github.com/user-attachments/files/17247034/log_file_v.rast.stats_QGIS_3.34.11.txt)

<img width="776" alt="log_file_v rast stats_QGIS_3 34 11" src="https://github.com/user-attachments/assets/a9acf836-f427-4585-bdc7-e4e6952c02b9">

9. Inspect attribute table of `grass7:v.rast.stats` ' s output _Rast stats_ . The new statistic-attributes only consist of _NULL_ s:

![attribute_table_2](https://github.com/user-attachments/assets/4ca5bb9c-cb9e-402a-92de-2e354c8a051c)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.34.11-Prizren | QGIS-Codeversion | 2904bcec
-- | -- | -- | --
Qt-Version | 5.15.13
Python-Version | 3.12.6
GDAL-Version | 3.9.2
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.2-CAPI-1.18.2
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
db_manager | 0.1.20
grassprovider | 2.12.99
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS-Version
3.34.11-Prizren
QGIS-Codeversion
[2904bcec](https://github.com/qgis/QGIS/commit/2904bcec)
Qt-Version
5.15.13
Python-Version
3.12.6
GDAL-Version
3.9.2
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.2-CAPI-1.18.2
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

When running `grass7:v.rast.stats` on _QGIS 3.34.10_ or _QGIS 3.34.11_ with different inputs I’ve seen varying error messages returned by the log. But the one thing that was consistent, was that returned statistics attributes only included _NULL_ s.

**Comment by agiudiceandrea** [comment]
@a-benini-2, thanks for reporting. The issue is not due to QGIS itself. As you can see in the log, the error is due to an issue which prevents the `v.rast.stats` GRASS-GIS module to correctly process the input raster data:

```
WARNING: LZ4 decompression error
ERROR: Error uncompressing null data for row 17 of <rast_66feda4aa04625> 
```

The issue also occurs even directly using GRASS-GIS 8.4.0 installed by the OSGeo4W installer for QGIS 3.34.11 on Windows 10.

The issue didn't occur directly using GRASS-GIS 8.3.2 installed by the OSGeo4W installer for QGIS 3.34.9.

The issue is very likely due to a bug in GRASS-GIS (and should be reported to https://github.com/OSGeo/grass/issues) or in the way GRASS-GIS or some libraries it depends on are built by OSGeo4W (probably @jef-n knows how to check).

**Comment by a-benini-2** [comment]
Thanks [agiudiceandrea](https://github.com/agiudiceandrea) for the quick response. As advised I’ve reported this issue as [a bug]( https://github.com/OSGeo/grass/issues/4443) to https://github.com/OSGeo/grass/issues.
