### ISSUE TITLE
HTML frame doesn't show content

### ISSUE THREAD

**Issue by dsanjurjo** [qgis/QGIS#58975]
### What is the bug or the crash?

In composer, when adding a HTML Frame, it doesn't show any content, neither by url or source.
I've tried in diferent versions (including a flatpak install), and none works.

I've a openSUSE system. First I tried with Tumbleweed, and then with Leap 15.6 (fresh install).

Launching Qgis from console, I get this log:
```

src/app/main.cpp:514 : (main) [0ms] Starting qgis main
src/core/qgsmessagelog.cpp:34 : (logMessage) [576ms] 2024-10-04T15:41:33 [0] Successfully loaded globalsettingsfile path: /usr/share/qgis/resources/qgis_global_settings.ini
src/core/providers/qgsproviderregistry.cpp:367 : (init) [477ms] Loaded 30 providers (OAPIF;WFS;arcgisfeatureserver;arcgismapserver;arcgisvectortileservice;cesiumtiles;copc;delimitedtext;ept;gdal;gpx;mbtilesvectortiles;mdal;memory;mesh_memory;mssql;ogr;pdal;postgres;postgresraster;spatialite;tiledscene;vectortile;virtual;virtualraster;vpc;vtpkvectortiles;wcs;wms;xyzvectortiles) 
src/core/qgsmessagelog.cpp:34 : (logMessage) [1753ms] 2024-10-04T15:41:35 Plugins[0] Loaded MetaSearch Catalog Client (package: MetaSearch)
src/core/qgsmessagelog.cpp:34 : (logMessage) [255ms] 2024-10-04T15:41:35 Plugins[0] Loaded DB Manager (package: db_manager)
src/core/qgsmessagelog.cpp:34 : (logMessage) [738ms] 2024-10-04T15:41:36 Plugins[0] Loaded GRASS GIS provider (package: grassprovider)
src/core/qgsmessagelog.cpp:34 : (logMessage) [646ms] 2024-10-04T15:41:36 Plugins[0] Loaded Processing (package: processing)
src/core/qgsmessagelog.cpp:34 : (logMessage) [244ms] 2024-10-04T15:41:37 [0] Application state:
QGIS_PREFIX_PATH env var:
Prefix:         /usr
Plugin Path:            /usr/lib64/qgis
Package Data Path:      /usr/share/qgis
Active Theme Name:      default
Active Theme Path:      /usr/share/qgis/resources/themes/default/icons/
Default Theme Path:     :/images/themes/default/
SVG Search Paths:       /usr/share/qgis/svg/
                /home/daniel/.local/share/QGIS/QGIS3/profiles/default/svg/
User DB Path:   /usr/share/qgis/resources/qgis.db
Auth DB Path:   /home/daniel/.local/share/QGIS/QGIS3/profiles/default/qgis-auth.db
```

Creating a new Print Layout:

`src/app/layout/qgslayoutdesignerdialog.cpp:4074 : (restoreWindowState) [17174ms] restore of layout UI geometry failed`

And creating, filling (source) and refresing a new HTML Frame, no logs, but no content rendered neither.

I've deleted previous profile too.

### Steps to reproduce the issue

Open Qgis
Create a new Print Layout
Create a new HTML Frame.
Fill source or select a URL
Press "Refresh HTML"

HTML Frame stays empty

### Versions

QGIS version | 3.34.1-Prizren | QGIS code branch | Release 3.34
-- | -- | -- | --
Qt version | 5.15.12
Python version | 3.11.5
GDAL/OGR version | 3.8.3
PROJ version | 7.2.1
EPSG Registry database version | v10.008 (2020-12-16)
GEOS version | 3.11.2-CAPI-1.17.2
SQLite version | 3.44.0
PDAL version | 2.5.6
PostgreSQL client version | 16.2
SpatiaLite version | 5.0.1
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | openSUSE Leap 15.6
  |   |   |  
This copy of QGIS writes debugging output.
  |   |   |  
Active Python plugins
MetaSearch | 0.3.6
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.1-Prizren
QGIS code branch
[Release 3.34](https://github.com/qgis/QGIS/tree/release-3_34)
Qt version
5.15.12
Python version
3.11.5
GDAL/OGR version
3.8.3
PROJ version
7.2.1
EPSG Registry database version
v10.008 (2020-12-16)
GEOS version
3.11.2-CAPI-1.17.2
SQLite version
3.44.0
PDAL version
2.5.6
PostgreSQL client version
16.2
SpatiaLite version
5.0.1
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
openSUSE Leap 15.6

This copy of QGIS writes debugging output.

Active Python plugins
MetaSearch
0.3.6
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@dsanjurjo, the HTML frame item is based on QtWebkit and it looks like that in both the openSUSE and the Flatpack builds of QGIS the use of QtWebkit is disabled.

See https://github.com/qgis/QGIS/issues/58491, https://forums.opensuse.org/t/what-happened-to-libqt5-qtwebkit/148414, https://build.opensuse.org/projects/openSUSE:Factory/packages/qgis/files/qgis.spec, https://github.com/flathub/org.qgis.qgis/blob/9c0ec8ed22265ed68124fc3795dcf59e4aa87aa5/org.qgis.qgis.json#L72

**Comment by dsanjurjo** [comment]
So can I download WebKit (including dev libraries), Qgis srpm, and then recompile and rebuild the rpm for Qgis including WebKit support, or is it more complicated than this?

Or is there a repository where I can download qgis for openSuse with WebKit support (and to realize my wet dreams, a gdal library with ECW support too*)?

*I know (and did) how to rebuild gdal rpm with ECW support, but it is always easier if you find it done.

**Comment by agiudiceandrea** [comment]
@dsanjurjo, QGIS distributed by Conda-forge has the QtWebkit support enabled.

**Comment by dsanjurjo** [comment]
Thanks, @agiudiceandrea . I'll give it a try.

**Comment by nyalldawson** [comment]
We should show a user - visible warning when this functionality is disabled. The current approach definitely isn't user friendly!
