### ISSUE TITLE
ESIR Personal GeoDatabase BUG

### ISSUE THREAD

**Issue by itsroc** [qgis/QGIS#58980]
### What is the bug or the crash?

Unable to open mdb files with Chinese path, file name, table name, and layer name, as well as internal layers and tables. The vector data conversion tool has the same issue

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/de644a64-3b7c-4f0b-825f-92270a62abf9)

### Versions

3.34.11-Prizren

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by NyakudyaA** [comment]
Can you natively open this using gdal i.e https://gis.stackexchange.com/questions/80360/import-esri-personal-geodatabase-mdb-to-postgis

If you encounter issues with gdal opening it most likely an upstream issue rather than QGIS

**Comment by agiudiceandrea** [comment]
@itsroc, please provide the full QGIS version info as requested in the issue report form ("In the QGIS Help menu -> About, click in the table, Ctrl+A and then Ctrl+C. Finally paste here. Do not make a screenshot.")

Are there any warning/error messages in the Log Messages panel?
Does the issue only occurs using the QGIS Browser or also using the Data Source Manager or dragging and dropping the ESRI Personal GeoDatabase in QGIS?
Does the issue only occurs if the file path\name contains Chinese chars or does it occur also if the file path\name contains only ASCII chars but the table\layer names contain Chinese chars?
Does the issue occurs if both the file path\name and table\layer names contain only ASCII chars?

**Comment by agiudiceandrea** [comment]
I can confirm the issue on Windows 10. The issue occurs when the file name contains non ASCII characters.
The issue occurs even using ogrinfo.

**Comment by agiudiceandrea** [comment]
Issue report opened upstream https://github.com/OSGeo/gdal/issues/10960.
