### ISSUE TITLE
Open Sans font installation failedq

### ISSUE THREAD

**Issue by AmmAmmer** [qgis/QGIS#58988]
### What is the bug or the crash?

Open Sans font installation failed

### Steps to reproduce the issue

Error transferring https://github.com/google/fonts/raw/main/ofl/opensans/OpenSans[wdth,wght].ttf - server replied: Not Found

### Versions

QGIS version
3.38.3-Grenoble
QGIS code revision
37f9e6efee
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Hi @nyalldawson, it looks like the issue already previously reported by me https://github.com/qgis/QGIS/issues/57070 and already fixed by you with a couple of PR, is occurring again.

**Comment by mbernasocchi** [comment]
@agiudiceandrea only a pointer url encoding [ and ] works at least interactively.
