### ISSUE TITLE
Displaying labels for vector tile layers

### ISSUE THREAD

**Issue by frgis** [qgis/QGIS#58994]
### What is the bug or the crash?

Hello,

when I add the following vector tile background: https://data.geopf.fr/tms/1.0.0/PLAN.IGN/metadata.json/

If I move this layer below all the others, are the labels still displayed above all the layers?

Thanks

### Steps to reproduce the issue

1 Add the vector tile layer: https://data.geopf.fr/tms/1.0.0/PLAN.IGN/metadata.json/
2 Move the vector tile layer below the others.
3 Vector tile layer labels appear above all map layers when they should be below.

### Versions

QGIS Desktop 3.34.8

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
QGIS labels are ALWAYS rendered above the map. See https://github.com/qgis/QGIS/issues/17889
