### ISSUE TITLE
Vector Tiles line-join is not honored. Miter line-join looks off as well.

### ISSUE THREAD

**Issue by tiagoacarvalho** [qgis/QGIS#58990]
### What is the bug or the crash?

The "line-join" parameter in mapbox style is not honored.
![image](https://github.com/user-attachments/assets/49a07e7b-7d9f-4c4a-92cf-e7fdf604b7e1)
![image](https://github.com/user-attachments/assets/b501c633-0324-4a60-a347-bf64ca8df9ad)
Also, "miter" line-join in small scales looks very off.
![image](https://github.com/user-attachments/assets/62874b8c-374f-4c68-90a9-922c948f2dcb)

### Steps to reproduce the issue

1. Go to top menu -> Layer -> Add Layer -> Add Vector Tile Layer
2. Add a Vector Tile Layer with a style json which includes a line style that has the "line-join" parameter set to "bevel" or "round"
3. Load Vector Tile Layer
4. See in the layer properties that the "line-join" is set to "miter", and that it looks weird in small scales.

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versão do QGIS | 3.28.10-Firenze | Código da versão do QGIS | e2edb9c468
-- | -- | -- | --
Versão Qt | 5.15.3
Versão do Python | 3.9.5
Versão GDAL/OGR | 3.7.1
Versão PROJ | 9.2.1
Versão da base de dados do registro EPSG | v10.088 (2023-05-13)
Versão GEOS | 3.12.0-CAPI-1.18.0
Versão SQLite | 3.41.1
Versão PDAL | 2.5.5
Versão cliente PostgreSQL | unknown
Versão SpatiaLite | 5.1.0
Versão QWT | 6.1.6
Versão QScintilla2 | 2.13.1
Versão OS | Windows 10 Version 2009
  |   |   |  
Plugins Python ativos
debug_vs_plugin-fix-configure-debugpy-python-path | 0.8
lftools | 1.12.10
plugin_reloader | 0.9.4
QuickOSM | 2.2.3
db_manager | 0.1.20
MetaSearch | 0.3.6
otbprovider | 2.12.99
processing | 2.12.99
sagaprovider | 2.12.99

</body></html>Versão do QGIS
3.28.10-Firenze
Código da versão do QGIS
[e2edb9c468](https://github.com/qgis/QGIS/commit/e2edb9c468)
Versão Qt
5.15.3
Versão do Python
3.9.5
Versão GDAL/OGR
3.7.1
Versão PROJ
9.2.1
Versão da base de dados do registro EPSG
v10.088 (2023-05-13)
Versão GEOS
3.12.0-CAPI-1.18.0
Versão SQLite
3.41.1
Versão PDAL
2.5.5
Versão cliente PostgreSQL
unknown
Versão SpatiaLite
5.1.0
Versão QWT
6.1.6
Versão QScintilla2
2.13.1
Versão OS
Windows 10 Version 2009

Plugins Python ativos
debug_vs_plugin-fix-configure-debugpy-python-path
0.8
lftools
1.12.10
plugin_reloader
0.9.4
QuickOSM
2.2.3
db_manager
0.1.20
MetaSearch
0.3.6
otbprovider
2.12.99
processing
2.12.99
sagaprovider
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
@tiagoacarvalho line-join is a "layout" property, not a "paint" property. See https://docs.mapbox.com/style-spec/reference/layers/#layout-line-line-join

This is already handled in QGIS for valid style json documents.
