### ISSUE TITLE
[Expression Builder] Find and Replace in the GUI

### ISSUE THREAD

**Issue by pigreco** [qgis/QGIS#58992]
### Feature description

Sometimes expressions inside the Expression Builder are long and complex, it would be useful to be able to activate a Find and Replace (Ctrl +H)
![image](https://github.com/user-attachments/assets/36cb0879-52e8-4051-bbf2-f8a56bb7e5ca)
In the example I should replace `CUS16` with `CUS19` and doing it by hand is tedious and you risk making mistakes

**Comment by Korto19** [comment]
Very useful feature for those who often use expressions

**Comment by nyalldawson** [comment]
On current QGIS versions this is already supported -- use Ctrl + F to open the find bar, or Ctrl + R to open the replace bar.

**Comment by pigreco** [comment]
> On current QGIS versions this is already supported

I didn't know this, but is this a feature documented somewhere? I can't find it in the changelogs

**Comment by pigreco** [comment]
@nyalldawson 
using regex, if I accidentally type `^` or `$` at the beginning of the search it crashes

https://github.com/user-attachments/assets/6a92c058-ed87-4dad-871e-3fc9e28df86e

**Comment by nyalldawson** [comment]
@pigreco can you file a new ticket please?

**Comment by pigreco** [comment]
@nyalldawson 

> can you file a new ticket please?

https://github.com/qgis/QGIS/issues/59002
