### ISSUE TITLE
Can't download package with Resource Sharing

### ISSUE THREAD

**Issue by marcantoinerheault** [qgis/QGIS#59005]
### What is the bug or the crash?

When I try to install a collection with Resource Sharing, I get the Error : No host Specified

### Steps to reproduce the issue

1.Go to 'Resource Sharing'
2.Click on any collection
3.Install the collection
4.Error: No host specified

### Versions

3.38.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is a bug with a third party plugin, you'll need to report it on the Resource Sharing project page.
