### ISSUE TITLE
Raster Calculator

### ISSUE THREAD

**Issue by javierelgueta** [qgis/QGIS#59012]
## User Feedback

Raster calculator

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00002708 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 305 in _recv_bytes
    waitres = _winapi.WaitForMultipleObjects(
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 250 in recv
    buf = self._recv_bytes()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 576 in _handle_results
    task = get()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Thread 0x000006a8 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 528 in _handle_tasks
    for taskseq, set_length in iter(taskqueue.get, None):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Thread 0x00002948 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 811 in _exhaustive_wait
    res = _winapi.WaitForMultipleObjects(L, False, timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\connection.py", line 879 in wait
    ready_handles = _exhaustive_wait(waithandle_to_obj.keys(), timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 499 in _wait_for_updates
    wait(sentinels, timeout=timeout)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\multiprocessing\pool.py", line 519 in _handle_workers
    cls._wait_for_updates(current_sentinels, change_notifier)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 917 in run
    self._target(*self._args, **self._kwargs)
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 980 in _bootstrap_inner
    self.run()
  File "C:\PROGRA~1\QGIS33~1.1\apps\Python39\lib\threading.py", line 937 in _bootstrap
    self._bootstrap_inner()

Current thread 0x00000ae0 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QgsRasterCalculator::processCalculation :
QgisApp::showRasterCalculator :
QObject::qt_static_metacall :
QAction::activate :
QMenu::actionGeometry :
QMenu::actionGeometry :
QMenu::mouseReleaseEvent :
QWidget::event :
QMenu::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Raster calculator then it crash

### Versions

QGIS version
3.36.1-Maidenhead
QGIS code revision
3e589453
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
easy_raster_splitter
2.1
HCMGIS
24.8.27
mmqgis
2021.9.10
molusce
4.0.0
OpenTopography-DEM-Downloader
3.0
PluginLoadTimes
4.1.0
processing_saga_nextgen
1.0.0
profiletool
4.2.6
qgis_resource_sharing
1.0.0
QuickOSM
2.2.3
quick_map_services
0.19.34
SemiAutomaticClassificationPlugin
8.3.0
slyr_community
5.0.0
SRTM-Downloader
3.2.3
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@javierelgueta, QGIS 3.36 is no longer supported. Please try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please provide sample data and step by step instructions that lead to the crash.

**Comment by agiudiceandrea** [comment]
@javierelgueta, thanks for reporting. QGIS 3.36 is no longer supported. Please try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please provide sample data and step by step instructions that lead to the crash.

**Comment by javierelgueta** [comment]
Hi Andrea, thanks for your reply, when the raster calculator is run by the
processing toolbox it have no issue, but if it is run by the raster menu,
qgis crash.
Thanks again
Best regards

Javier Elgueta Alvarez
+56 9 5001 2988
