### ISSUE TITLE
Can't save modifications on geojson entities 

### ISSUE THREAD

**Issue by Ashzero0** [qgis/QGIS#59029]
### What is the bug or the crash?

Saving changes to entities in edition mode doesn't work for geojson files. 
You can edit geojson entities in edition mode, but when you save the attribute table, the changes aren't saved.  

Entity modifications are OK if you don't save, but export.

### Steps to reproduce the issue

1. Import geoson files and go to attribute table
2. Select editing mode 
3. Edit an entity (change is visible)
4. Save the changes
5. The modification isn't save 

### Versions

QGIS Version : 3.38.3 Grenoble

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No problem saving modified entities from an shp file

**Comment by agiudiceandrea** [comment]
Already reported https://github.com/qgis/QGIS/issues/58261 and fixed #58740.
