### ISSUE TITLE
SVG (e.g. North arrow) position not adjustable

### ISSUE THREAD

**Issue by Dominik-CHE** [qgis/QGIS#59094]
### What is the bug or the crash?

I encountered this error similar times. If I adding a .svg graphic to a layout, sometimes when I trying to move it via mouse the box for the graphic is moving to this position and is resized (see screenshot below). But it dissapear every time when restarting QGIS. The X/Y Position isn't changable at that time anymore, it jumps always back to the 99999999 when clicking on the other coordinate. 

![grafik](https://github.com/user-attachments/assets/0870af68-e94c-4626-8549-faa32113316d)

It happens with costumized .svg as also the implemented ones provided in the SVG Browser. 

### Steps to reproduce the issue

In layout with a map theme:
Case A: 
1. Add picture or North arrow
2. choose any svg
3. Change properties: Zoom and Resize Frame
4. click on graphic box.

or case B:
1. Add picture or North arrow
2. choose any svg
3. Change properties: Zoom and Resize Frame
4. Close QGIS
5. Reopen Layout

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.4-Prizren | QGIS code revision | decd43dc
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.9.18
GDAL/OGR version | 3.8.4
PROJ version | 9.3.1
EPSG Registry database version | v10.098 (2023-11-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.41.1
PDAL version | 2.6.0
PostgreSQL client version | 16.1
SpatiaLite version | 5.1.0
QWT version | 6.1.6
QScintilla2 version | 2.13.4
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
EasyCustomLabeling | 2.1
style_exporter | 1.0
swissgeodownloader | 2.0.1
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99

</body></html>QGIS version
3.34.4-Prizren
QGIS code revision
[decd43dc](https://github.com/qgis/QGIS/commit/decd43dc)
Qt version
5.15.3
Python version
3.9.18
GDAL/OGR version
3.8.4
PROJ version
9.3.1
EPSG Registry database version
v10.098 (2023-11-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.41.1
PDAL version
2.6.0
PostgreSQL client version
16.1
SpatiaLite version
5.1.0
QWT version
6.1.6
QScintilla2 version
2.13.4
OS version
Windows 10 Version 2009

Active Python plugins
EasyCustomLabeling
2.1
style_exporter
1.0
swissgeodownloader
2.0.1
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Dominik-CHE, it seems to me I cannot replicate the issue using QGIS 3.34.11:


https://github.com/user-attachments/assets/9797496b-81ba-49cf-bb7e-6032827d94bf

Please try if the issue occurs also running a currently supported QGIS version and using a new QGIS user profile. If it does occur, please provide more detailed step by step instructions in order to replicate the issue.

**Comment by esnyder-rve** [comment]
Duplicate of #37460
