### ISSUE TITLE
Qgis crashed in the 3D view window

### ISSUE THREAD

**Issue by GJoe2** [qgis/QGIS#59101]
## User Feedback

I was doing a 3d map view, I was looking for settings to increase scale model. Then I move the windows and lagged and finally it crashed

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00006e24 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QWindowsStylePrivate::altDown :
QHashData::free_helper :
QHeaderView::logicalIndexAt :
QMainWindow::tr :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidgetPrivate::setStyle_helper :
QWidgetPrivate::inheritStyle :
QWidget::setParent :
QWidgetPrivate::setWidgetParentHelper :
QgsDockableWidgetHelper::~QgsDockableWidgetHelper qgsdockablewidgethelper.cpp:45
QgsDockableWidgetHelper::`vector deleting destructor' :
Qgs3DMapCanvasWidget::~Qgs3DMapCanvasWidget qgs3dmapcanvaswidget.cpp:275
Qgs3DMapCanvasWidget::`vector deleting destructor' :
QObject::event :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify qgsapplication.cpp:542
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main main.cpp:1726
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.15-Firenze
QGIS code revision: 252ad49ddc
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.3
Running against GDAL: 3.8.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

1-Have a dem model ,hillshade  and pseudoband monocolor raster
2-Create a new 3D view
3-Close it and create another one
4-Doodle around with the settings 
5-Move and rotate the camera
6- Move the actual 3d view window
7- It will crash, at least it happened that way to me  

### Versions

Versión de QGIS
3.28.15-Firenze
Revisión del código de QGIS
252ad49ddc
Versión Qt
5.15.3
Versión de Python
3.9.18
Versión de GDAL/OGR
3.8.3
Versión de PROJ
9.3.1
Versión del registro de base de datos EPSG
v10.041 (2021-12-03)
Versión de GEOS
3.12.1-CAPI-1.18.1
Versión de SQLite
3.41.1
Versión de PDAL
2.6.0
Versión del cliente de PostgreSQL
unknown
Versión de SpatiaLite
5.1.0
Versión de QWT
6.1.6
Versión de QScintilla2
2.13.4
Versión del SO
Windows 10 Version 2009

Complementos activos de Python
OpenTopography-DEM-Downloader
3.0
profiletool
4.2.6
Qgis2threejs
2.7.3
quick_map_services
0.19.34
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@GJoe2, thanks for reporting, anyway QGIS 3.28 is no longer supported. Please try if the issue occurs also running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles). It would ve useful if you provided a sample project + layer(s) in order to replicate the issue.
