### ISSUE TITLE
QGIS cannot open a file if the filepath contains ".target"

### ISSUE THREAD

**Issue by Saudruch** [qgis/QGIS#59106]
### What is the bug or the crash?

When I try to open any raster (specifically geoTIFF in this case) in QGIS I will get this error message

`Invalid Data Source: /home/user/Desktop/folder.test.target/raster.tif is not a valid or recognized data source.`

However when I change the path by excluding the ".target" the file will open without a problem.

`/home/user/Desktop/folder.test/raster.tif`
`/home/user/Desktop/folder.test-target/raster.tif`

### Steps to reproduce the issue

1. Download or create any tif file. For example found some sample files here:  https://download.osgeo.org/geotiff/samples/made_up/bogota.tif
2. Open it in QGIS. 
3. change the file name to target.bogota.tif (or alternatively change the folder name so it contains .target)
4. try to open it again, you should get the error
5. change the file name to something.bogota.tif
6. it should open (so it is not an issue with the "." but specifically with ".target"

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.11-Prizren | QGIS code revision | 2904bcec7c9
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.12
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PDAL version | 2.3.0
PostgreSQL client version | 14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.5 LTS
  |   |   |  
Active Python plugins
coordinate_capture | 0.2
latlontools | 3.6.3
BoundingBox | 2.1
db_manager | 0.1.20
processing | 2.12.99
MetaSearch | 0.3.6

</body></html>QGIS version
3.34.11-Prizren
QGIS code revision
[2904bcec7c9](https://github.com/qgis/QGIS/commit/2904bcec7c9)
Qt version
7.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.13 (Ubuntu 14.13-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
8.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.5 LTS

Active Python plugins
coordinate_capture
0.2
latlontools
3.6.3
BoundingBox
2.1
db_manager
0.1.20
processing
2.12.99
MetaSearch
0.3.6

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Tested it on different computers with slightly different QGIS versions. I am running Ubuntu 22.04 LTS on one computer and Ubuntu 24.04 LTS on another. Also the another computer I tested on it does have only BoundingBox plugin installed so I think it probably isn't plugin issue.

**Comment by Saudruch** [comment]
<img width="765" alt="image" src="https://github.com/user-attachments/assets/65086e14-7dbe-43fe-86fb-307738038c46">
I was able to reproduce this on macOS QGIS LTS version

QGIS version
3.34.6-Prizren
QGIS code revision
[623828f58c2](https://github.com/qgis/QGIS/commit/623828f58c2)
Qt version
5.15.2
Python version
3.9.5
GDAL/OGR version
3.3.2
PROJ version
8.1.1
EPSG Registry database version
v10.028 (2021-07-07)
GEOS version
3.9.1-CAPI-1.14.2
SQLite version
3.35.2
PDAL version
2.3.0
PostgreSQL client version
unknown
SpatiaLite version
5.0.1
QWT version
6.1.6
QScintilla2 version
2.11.5
OS version
macOS 15.0




Active Python plugins
processing
2.12.99
grassprovider
2.12.99
db_manager
0.1.20
MetaSearch
0.3.6

**Comment by agiudiceandrea** [comment]
I can also confirm the issue both using QGIS LTR 3.34.11 and QGIS 3.38.3 (from OSGeo4W) when the file path\name contains the ".target" string.

The issue occurs either trying to add the layer via drag&drop:
```
CRITICAL    Invalid Data Source : C:/path/abc.target.test.tif
WARNING    Unable to load C:/path/abc.target.test.tif is not a valid or recognized data source.
```
```
CRITICAL    Invalid Data Source : C:/Users/Andrea/Downloads/abc.target.test/test.tif is not a valid or recognized data source.
WARNING    Unable to load C:/Users/Andrea/Downloads/abc.target.test/test.tif
```

or using the Data Source Manager -> Raster:
`CRITICAL    Unsupported Data Source : C:\path\abc.tar/get.test.tif is not a supported raster data source`
`CRITICAL    Unsupported Data Source : C:\path\abc.tar/get\test.tif is not a supported raster data source`

(**notice the ".tar/get" string instead of ".target" in the error messages"**)

The layer is not displayed in the QGIS Browser.

It looks like the issue doesn't occur using QGIS 3.39.0-Master bb9a7165e6

The issue actually occurs when the file path\name contains at least one of the following strings: ".tar", ".zip", ".gz", ".tgz".

**Comment by nyalldawson** [comment]
This was fixed by https://github.com/qgis/QGIS/pull/58240

**Comment by nyalldawson** [comment]
I think we should close this -- it's not an issue with 3.40, and it's not enough to backport just https://github.com/qgis/QGIS/pull/58240 alone.
