### ISSUE TITLE
Advanced digitising tools not enabled.

### ISSUE THREAD

**Issue by iyer424** [qgis/QGIS#59113]
### Feature description

Advanced digitising tools not enabled.
.please help to to retreive.

**Comment by DelazJ** [comment]
Not sure of what your issue actually is, @iyer424. The advanced digitizing tools is a toolbar you can activate from the View menu --> Toolbars ([read tip](https://docs.qgis.org/3.34/en/docs/user_manual/introduction/qgis_gui.html#toolbars))
