### ISSUE TITLE
QgsProject.instance().mapLayers() methods result in no changes

### ISSUE THREAD

**Issue by coderodyhpc** [qgis/QGIS#59136]
### What is the bug or the crash?

Several methods associated with QgsProject.instance().mapLayers() seem to not be working as desired:
-values() works OK (in my test case it lists 1 raster layer and 3 vector layers as it should)
-pop(*,*) does nothing (actually the objective is to move the raster of the layer from first to last position but the order is not changed)
-clear() didn't clear the map canvass as I expected
I also tried calling the method update() but didn't make any difference. 

### Steps to reproduce the issue

A PyQGIS snippet reads:  

```
    def layer_move(self):
        mapII = QgsProject.instance().mapLayers()
        for num1, capa2 in enumerate(mapII.values()):
            print ("LAYER ", num1, capa2)
        mapII.pop(-1, self.my_raster_layer)
        mapII.update()
        for num2, capa3 in enumerate(mapII.values()):
            print ("LAYERs after popping ", num2, capa3)

        mapII.clear()
        for num3, capa4 in enumerate(mapII.values()):
            print ("LAYERs after clearing ", num3, capa4)

```

### Versions

QGIS version
3.34.0-Prizren
QGIS code branch
Release 3.34
Qt version
5.15.3
Python version
3.10.12
GDAL/OGR version
3.4.1
PROJ version
8.2.1
EPSG Registry database version
v10.041 (2021-12-03)
GEOS version
3.10.2-CAPI-1.16.0
SQLite version
3.37.2
PDAL version
2.3.0
PostgreSQL client version
14.10 (Ubuntu 14.10-0ubuntu0.22.04.1)
SpatiaLite version
5.0.1
QWT version
6.1.4
QScintilla2 version
2.11.6
OS version
Ubuntu 22.04.3 LTS

Active Python plugins
NuPrGvtres
1.0.0
TABULA
1.0
MetaSearch
0.3.6
grassprovider
2.12.99
processing
2.12.99
db_manager
0.1.20

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
This is expected -- those methods return a copy of the list or dictionary, so changes only affect the returned list or dictionary. Use methods like  https://qgis.org/pyqgis/master/core/QgsProject.html#qgis.core.QgsProject.removeMapLayer instead

**Comment by nyalldawson** [comment]
The order in the project isn't important. If you're trying the change the render order or legend order, then look into the QgsLayerTree* classes.
