### ISSUE TITLE
Qgis crashes

### ISSUE THREAD

**Issue by paulsoz** [qgis/QGIS#59138]
## User Feedback

The program crashes when I want to add a string field with a width of 250 to an attribute table

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00014660 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsField::QgsField :
QgsFields::at :
QgsAttributeTableModel::getWidgetData :
QgsAttributeTableModel::prefetchSortData :
QgsAttributeTableFilterModel::setAttributeTableConfig :
QgsDualView::hideEvent :
QObject::qt_static_metacall :
QgsVectorLayer::updateFields :
QgsVectorLayerUndoCommandAddAttribute::redo :
QUndoStack::push :
QgsVectorLayerEditBuffer::addAttribute :
QgsAttributeTableDialog::mActionAddAttribute_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.38.3-Grenoble
QGIS code revision: 37f9e6efee
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

1. Open attribute table, 
2. Enable editing,
3. Field name: Genealogy
4.. Add string field, width 250, 
5. Save
6. Program crashes

### Versions

QGIS-versie
3.38.3-Grenoble
QGIS code revisie
37f9e6efee
Qt versie
5.15.13
Python versie
3.12.6
GDAL/OGR versie
3.9.2
PROJ versie
9.4.0
EPSG-register databaseversie
v11.004 (2024-02-24)
GEOS versie
3.12.2-CAPI-1.18.2
SQLite versie
3.45.1
PDAL versie
2.6.3
PostgreSQL client versie
16.2
SpatiaLite versie
5.1.0
QWT versie
6.2.0
QScintilla2 versie
2.14.1
OS versie
Windows 11 Version 2009

Actieve Python plug-ins
addresssearch
1.4
BGTImport
3.18
citydb-tools
0.8.9
google-street-view-layer-master
0.1
OSMDownloader
1.0.3
osminfo
0.9.1
pdokservicesplugin
5.1.1
qgis2web
3.22.0
quick_map_services
0.19.34
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@paulsoz, I cannot replicate the issue. Please try if the issue occurs also using a new QGIS user profile. If it does, please provide more details and / or a sample layer with which the issue occurs.
