### ISSUE TITLE
Missing parameters in documentation / VCPKG install 

### ISSUE THREAD

**Issue by danodom-tcb** [qgis/QGIS#59135]
### What is the issue about the documentation?

The Install.md needs some additional parameters added to the VCPKG section.   When I ran the command as stated in the install.md, it threw errors missing the paths for Flex and Bison.  

Thanks to @jef-n  for updating the instructions as I am now almost completed building in Windows 11, but have an issue that I opened as well.  There were a few other items that I ran into, and I will also try to remember and paste those so they can be updated in the documentation.

Open a Developer PowerShell for VS 2022

- We assume you have a copy of the QGIS source code available
- and have changed the working directory into it

- Configure
cmake -S . \
      -B build \
      -DSDK_PATH="path/to/vcpkg-export-[date]" \
      -DBUILD_WITH_QT6=ON \
      -DWITH_QTWEBKIT=OFF \
      -DVCPKG_TARGET_TRIPLET=x64-windows-release

this needs to add reference to the location of the flex(win_flex) and bison(win_bison) executable : 

cmake -S . \
      -B build \
      -DSDK_PATH="path/to/vcpkg-export-[date]" \
      -DBUILD_WITH_QT6=ON \
      -DWITH_QTWEBKIT=OFF \
      -DVCPKG_TARGET_TRIPLET=x64-windows-release \
      -DFLEX_EXECUTABLE="path/to/flex.exe   \
      -DBISON_EXECUTABLE="path/to/bison.exe" \

**Comment by rouault** [comment]
@danodom-tcb It looks you might want to directly open a pull request with your proposed changes? Just go to https://github.com/qgis/QGIS/edit/master/INSTALL.md and submit your changes

**Comment by danodom-tcb** [comment]
> @danodom-tcb It looks you might want to directly open a pull request with your proposed changes? Just go to https://github.com/qgis/QGIS/edit/master/INSTALL.md and submit your changes

Roger that, and thank you.

**Comment by danodom-tcb** [comment]
@rouault PR created, closing issue.
