### ISSUE TITLE
Box add resources: "Add" WMS not displayed on the screen

### ISSUE THREAD

**Issue by ico20** [qgis/QGIS#59140]
### What is the bug or the crash?

I recently upgrade to Ubuntu 24.04 and Qgis 3.38 (both clean install). I try to add a WMS layer but the add/close buttons are not displayed (too low on the screen), so I cannot add this resource. I try to resize the box but doesn't work, I try to change the resolution of the screen (default is 1366x768) and it doesn't work. This happens for "WMS/WMTS" and "Virtual Layer", not for vector or raster or other resources.
If anyone can help, Thx

### Steps to reproduce the issue

Go to ' add resources'
Select 'wms/wmts'
Scroll down to "add"/"close" button
Not displayed the lower part of the box on the screen

### Versions

The current released version of QGIS is 3.38.3. 
We are working on 3.39-Master. It will go into feature freeze on 2024-09-13 12:00:00 UTC and be released as 3.40 on 2024-10-25 12:00:00 UTC. 
Details on changes can be found on github at https://github.com/qgis/QGIS/commits/master. 

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
> This happens for "WMS/WMTS" and "Virtual Layer", not for vector or raster or other resources.

For the Virtual layer, does it work if you collapse the "Geometry" and/or "Embedded layers" widgets?

![image](https://github.com/user-attachments/assets/f6c2ac96-6c2d-4535-8b78-37ae42274982)

**Comment by ico20** [comment]
Thanks, yes it'a a workaround for "virtual layer", but it's not possible to do the same for WMS resource because there the is no section to collapse. Thx!
