### ISSUE TITLE
QGIS - Visual Studio build - Projects missing build options (/bigobj)

### ISSUE THREAD

**Issue by danodom-tcb** [qgis/QGIS#59157]
### What is the issue about the documentation?

I am working on building QGIS on Windows 11 using Visual Studio 2022.

The process from the updated install.md is working really well and finding subtle little things in the process I am working through.

One of the things is that 2 of the projects that were built in the Visual Studio solution were missing some build options.    I am not sure of where these would need to be set in the code to fix this issue, so wanted to bring this up here.

qgis_test
qgis_core

It was missing the "/bigobj" build option (see end pasted below) as this was reported by a build error.  Once I added this for these 2 projects, they built successfully.

%(AdditionalOptions) /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtCore" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtGui" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtXml" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtWidgets" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSvg" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtNetwork" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSql" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtConcurrent" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/QtCrypto" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtSerialPort" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtPrintSupport" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/share/Qt6/mkspecs/win32-msvc" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/geos" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/libxml2" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/minizip" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtCore5Compat" /external:I "C:/QGIS/vcpkg-export-20241015-154141/installed/x64-windows-release/include/Qt6/QtPositioning" /utf-8 -Zc:__cplusplus -utf-8 **/bigobj**

**Comment by danodom-tcb** [comment]
I found another that is having the same issue and needs the same compiler option added.  /bigobj

qgis_core_autogen

**Comment by m-kuhn** [comment]
Can you try adding `target_compile_options(qgis_core PRIVATE /bigobj)` (and potentially other affected targets) (somewhere around here, after the target is added https://github.com/qgis/QGIS/blob/master/src/core/CMakeLists.txt#L2343)?

**Comment by m-kuhn** [comment]
@nicogodet feel free to directly open a PR with these adjustments, thanks !

**Comment by nicogodet** [comment]
https://github.com/qgis/QGIS/blob/42a3bcf290e1a0ac24a83137878b7b5c2db1e16b/src/core/CMakeLists.txt#L2183-L2189

Found this

**Comment by m-kuhn** [comment]
Which looks more precise (setting this only for certain files)
Does it not work in our case?

**Comment by nicogodet** [comment]
qgis_gui failed too, Need /bigobj. Retrying...

**Comment by m-kuhn** [comment]
One thing is automoc, I think we want to avoid one big moc file and split it up which means adding a nes `#include <.....moc>` file to many header files.
