### ISSUE TITLE
QGIS Documentation - What does removing WITH_BINDINGS disable (functionality)

### ISSUE THREAD

**Issue by danodom-tcb** [qgis/QGIS#59158]
### What is the issue about the documentation?

Question about the Compilation flags for QGIS and I understand that this option will determine if the Python bindings need to be built or not, but what will occur if I set this to false, or remove it in a Windows build?

I am wondering if there is functionality will be disabled or removed, have to provide specific libraries, etc.

Can someone help me understand this?  The build issue I am having it Python-specific, but curious if I actually need that option set.

**Comment by troopa81** [comment]
>  but what will occur if I set this to false, or remove it in a Windows build?

You don't get any python related feature including the python console, project python macros, python plugin, processing also (a large part is written in python and so need binding).

**Comment by m-kuhn** [comment]
See https://github.com/qgis/QGIS/blob/11c70a7e60301580497b4e7086ca86e100b428c8/CMakeLists.txt#L22

I don't think this needs more docs
