### ISSUE TITLE
Static linked binaries

### ISSUE THREAD

**Issue by fedya-eremin** [qgis/QGIS#59161]
### Feature description

I would be really glad if there will be any binaries for releases. It is a huge pain to compile 11k targets on Linux every time. If I am not right, please, provide any link to them.

**Comment by agiudiceandrea** [comment]
@fedya-eremin, not sure what you are looking for exactly, anyway binaries are provided for various GNU/Linux OS: see https://qgis.org/resources/installation-guide/#linux.

**Comment by fedya-eremin** [comment]
Thank you! E.g. I am using Arch, and I need to install LTR version. All I have is bz2 source code archive (on github and in my package manger), which I need to compile. Is there any way to get a binary distribution of QGIS?

**Comment by agiudiceandrea** [comment]
You can install QGIS following the instructions provided in the already linked web page.

**Comment by agiudiceandrea** [comment]
@fedya-eremin, you can install QGIS following the instructions provided in the already linked [web page](https://qgis.org/resources/installation-guide/#arch-linux).
