### ISSUE TITLE
QGIS build - Custom Compiler options being overwritten

### ISSUE THREAD

**Issue by danodom-tcb** [qgis/QGIS#59170]
### What is the bug or the crash?

I have a related issue already on this, but it appears that some builds may be overwriting custom build options.  

I am building on : 
Windows 11
Visual Studio 2022
using the instructions for vcpkg

For a couple of the projects, it requires a the /bigobj compiler option to compile successfully.  The projects inside the solution that need this option to compile is "qgis_test" and "qgix_core".  After working with @m-kuhn yesterday on another issue, I was able to get past the other issue, then ran into the missing "/bigobj" option again yesterday.  When I looked, it appeared to  have been in qgis_core, which I had already updated.

Is there something overwriting files on the build?  If so, where can I add this additional compiler option to make sure if it's overwritten in the future, that it doesn't cause an issue?

Error : 
5>C:\QGIS\QGIS\build\src\core\qgis_core_autogen\mocs_compilation_Release.cpp(1,1): error C1128: number of sections exceeded object file format limit: compile with /bigobj

### Steps to reproduce the issue

I have a related issue already on this, but it appears that some builds may be overwriting custom build options.  

I am building on : 
Windows 11
Visual Studio 2022
using the instructions for vcpkg

For a couple of the projects, it requires a the /bigobj compiler option to compile successfully.  The projects inside the solution that need this option to compile is "qgis_test" and "qgix_core".  After working with @m-kuhn yesterday on another issue, I was able to get past the other issue, then ran into the missing "/bigobj" option again yesterday.  When I looked, it appeared to  have been in qgis_core, which I had already updated.

Is there something overwriting files on the build?  If so, where can I add this additional compiler option to make sure if it's overwritten in the future, that it doesn't cause an issue?

Error : 
5>C:\QGIS\QGIS\build\src\core\qgis_core_autogen\mocs_compilation_Release.cpp(1,1): error C1128: number of sections exceeded object file format limit: compile with /bigobj

### Versions

latest code from master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by m-kuhn** [comment]
VS projects are generated via cmake. If something in a cmake file changes, cmake is rerun and overwrites the VS project.
If `/bigobj` is required it needs to be added to the cmake files. This is tracked in https://github.com/qgis/QGIS/issues/59157 so I would vote to close this.

**Comment by danodom-tcb** [comment]
@m-kuhn , will close this one if it's related to the cmake changes we were making yesterday when we were triaging another issue.  I am actually glad to hear there's a known reason why it occurred.

ty.. closing.
