### ISSUE TITLE
Missing menu bar on Linux Wayland

### ISSUE THREAD

**Issue by tockudex** [qgis/QGIS#59196]
### What is the bug or the crash?

The main menu bar is not appearing in QGIS.

Reinstalling QGIS and clearing the .cache/QGIS/ and .local/share/QGIS/ does not resolve the problem.

System info:
OS: Arch Linux x86_64
Kernel: 6.11.5-zen1-1-zen
DE: KDE Plasma 6.2.2 (KDE Framework 6.8.0)
Qt: 6.8.0
Graphics platform: Wayland 

### Steps to reproduce the issue

1. Open QGIS (through application menu or terminal).
2. Main menu bar does not appear.  

### Versions

3.38.3

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

A few months ago (I don't recall QGIS' version) the described issue was not present, as the menu bar appeared.

All other Qt programs (Qt5 or Qt6) always have a menu bar.

**Comment by tockudex** [comment]
I solved my problem by installing some missing pseudo-dependencies (`plasma5-integration` on KDE Plasma 6, Arch Linux), which I had removed a few weeks ago, because they did not appear to be required anymore.

**Comment by jangboolee** [comment]
> I solved my problem by installing some missing pseudo-dependencies (`plasma5-integration` on KDE Plasma 6, Arch Linux), which I had removed a few weeks ago, because they did not appear to be required anymore.

This also worked for me on KDE, EndeavourOS. Thank you for the solution.
