### ISSUE TITLE
Add "Selected Features Only" Option in Model Designer

### ISSUE THREAD

**Issue by viniciuspg** [qgis/QGIS#59198]
### Feature description

I would like to suggest the addition of a "Selected Features Only" functionality in the QGIS Model Designer, similar to the option available in native algorithms.

Currently, QGIS native algorithms allow users to process only the selected features, making spatial analysis and processing more focused on specific subsets of data. However, when working in the Model Designer, this option is not natively available, limiting workflows when processing large datasets where only selected features are required.

Adding a "Selected Features Only" checkbox directly in the parameters of the Model Designer would bring the following benefits:

Greater Flexibility: Allow models to be applied only to selected features without needing to manually filter or modify the dataset beforehand.
Efficiency: Avoid the need for additional processes to filter features within the model, saving time and simplifying workflows.
Consistency: Maintain consistency between native algorithms and the Model Designer, as this functionality already exists outside the model environment.
This feature would be especially useful for those working with large datasets and wishing to perform analyses or data processing only on selected parts of the data, thus keeping workflows streamlined.

Thank you for considering this suggestion, and I would be happy to collaborate further if any additional details are needed for its implementation.

Possible Implementation:

Add a "Selected Features Only" checkbox in the Model Designer’s input parameters, similar to the one present in native algorithms like "Filter Features" and "Process Features".
Best regards,
Vinicius Gonçalves

**Comment by roya0045** [comment]
I fail to see how this is not addressed by the "Vector Features" as the model input or using another processing tool to extract selected features.

**Comment by viniciuspg** [comment]
The idea is not to extract selected features, but to process only the selected features, whatever the algorithm. For example, in the "fix geometries" algorithm, when using native feature in the toolbox, it has a checkbox to select and process only the selected features of the layer. When this same algorithm is used in the modeler, there is no way to enable this option to be enabled in the customized algorithm in the modeler (at least I didn't find how to do it).

**Comment by nyalldawson** [comment]
You need to ensure you are using the "vector features" input type, NOT "vector layer" input type.

**Comment by viniciuspg** [comment]
You are completely correct nyalldawson. QGIS was so well developed that it already includes this functionality, I was using Vector Layer in the input, instead of vector feature. Thank you very much for the tip. I will close the issue.

**Comment by viniciuspg** [comment]
You are completely correct nyalldawson. QGIS was so well developed that it already includes this functionality, I was using Vector Layer in the input, instead of vector feature. Thank you very much for the tip. I will close the issue.
