### ISSUE TITLE
qgis 3.36.1 crashes continuasly

### ISSUE THREAD

**Issue by gtsolakis** [qgis/QGIS#59213]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Thread 0x00000700 (most recent call first):

Stack Trace

QCoreApplication::translate :
QCoreApplication::translate :
QCoreApplication::translate :
QRegularExpressionMatchIterator::regularExpression :
QRegularExpressionMatch::capturedView :
QRegularExpression::match :
QgsArcGisRestUtils::variantToAttributeValue :
QgsArcGisRestUtils::variantToAttributeValue :
QgsRasterIdentifyResult::error :
QgsArcGisRestUtils::variantToAttributeValue :
QgsRasterIdentifyResult::operator= :
QgsProviderUtils::suggestLayerNameFromFilePath :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.36.1-Maidenhead
QGIS code revision: 3e589453
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

click qgz file, opens QGIS then crashes

### Versions

3.36.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@gtsolakis, thanks for reporting. QGIS 3.36 is no longer supported. Please actually try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
