### ISSUE TITLE
qgis crashes when i close it

### ISSUE THREAD

**Issue by Guts6384** [qgis/QGIS#59218]
## User Feedback

WHEN I CLOSE QGIS IT CRASHES

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00002360 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

PyGen_Finalize :
PyGen_Finalize :
vtkPythonCommand::~vtkPythonCommand :
vtkPythonCommand::operator= :
vtkObject::RemoveAllObservers :
vtkObjectBase::UnRegisterInternal :
vtkSmartPointerBase::~vtkSmartPointerBase :
<lambda_f03950bc5685219e0bcd2087efbe011e>::operator() :
__crt_seh_guarded_call<int>::operator()<<lambda_7777bce6b2f8c936911f934f8298dc43>,<lambda_f03950bc5685219e0bcd2087efbe011e> &,<lambda_3883c3dff614d5e0c5f61bb1ac94921c> > :
execute_onexit_table :
vtkWin32ProcessOutputWindow::Write :
vtkWin32ProcessOutputWindow::Write :
LdrpCallInitRoutine :
LdrShutdownProcess :
RtlExitUserProcess :
ExitProcessImplementation :
exit_or_terminate_process :
common_exit :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.38.3-Grenoble
QGIS code revision: 37f9e6efee
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

i close qgis pressing X on top-right corner
it crashes

### Versions

QGIS Info
QGIS Version: 3.38.3-Grenoble
QGIS code revision: 37f9e6efee
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Please try with a new QGIS profile : https://www.youtube.com/watch?v=mKTRHL5YLjI
