### ISSUE TITLE
Missing icons in Locator

### ISSUE THREAD

**Issue by nicogodet** [qgis/QGIS#59243]
### What is the bug or the crash?

3.40 and Master
![image](https://github.com/user-attachments/assets/128952fc-bddf-4edb-a9a6-1a497b1f27d8)

3.34.12
![image](https://github.com/user-attachments/assets/d23cb416-c327-4c0c-9c8a-7023e467e85c)

### Steps to reproduce the issue

.

### Versions

3.40 and Master

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
@3nids Might this be related to your recent work on locator ?

**Comment by 3nids** [comment]
yes, looking into it
