### ISSUE TITLE
Having multiple compound CRS layers makes QGIS really slow

### ISSUE THREAD

**Issue by Joonalai** [qgis/QGIS#59266]
### What is the bug or the crash?

Having multiple compound CRS (a coordinate reference system using two other independent coordinate reference systems, one for the horizontal component and one for the vertical component) layers makes editing layers really slow in QGIS 3.40.0. 

After digitizing new feature it takes few seconds to recover. 

![compound_freeze_3_40](https://github.com/user-attachments/assets/1f26b896-ec20-4465-acb0-771fb17fdda4)

### Steps to reproduce the issue
To reproduce the bug I prepared a [compound_gpkg.zip](https://github.com/user-attachments/files/17586504/compound_gpkg.zip) containing compound.gpkg which has 20 polygon tables with EPSG:3067 (horizontal_<number>) and 20polygon tables with [EPSG:3903](https://epsg.io/3903) (compound_<number>). All tables are empty.

1. Download and extract [compound_gpkg.zip](https://github.com/user-attachments/files/17586504/compound_gpkg.zip)
2. Start QGIS and open project from that geopackage
3. Add new feature for some of the layers
4. Move mouse over toolbar buttons to observe the slowness

Another way to reproduce using PostGIS (and docker):

<details>

To reproduce the bug I prepared a [compound.zip](https://github.com/user-attachments/files/17567827/compound.zip)
 containing docker-compose.yml and sql file containing lines to add 100 polygon tables with EPSG:3067 into schema "horizontal_crs" and 100 polygon tables with [EPSG:3903](https://epsg.io/3903) into schema "compound_crs". All tables are empty.

1. Download and extract [compound.zip](https://github.com/user-attachments/files/17567827/compound.zip)
3. docker-compose up -d
4. Start QGIS
5. Add following PostGIS server connection: `dbname=layerdb host=localhost port=5430 username=postgres password=postgres`
6. Add all layers from schema compound_crs into the project
7. Add new feature for some of the layers
8. Move mouse over toolbar buttons to observe the slowness

</details>

### Versions

<details>

QGIS version
3.40.0-Bratislava
QGIS code revision
b56115d874
 
Libraries
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.9.3
PROJ version
10.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009
 
Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

</details>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This does not happen with layers with horizontal CRS:

![horizontal_no_freeze_3_40](https://github.com/user-attachments/assets/bdecfc7c-7a9c-4b26-91e7-a00aa6b10082)

And not in version 3.34.4 so this must be fairly new bug:

![compound_no_freeze_3_34](https://github.com/user-attachments/assets/ebb9eb79-b3f6-473f-a02b-ac0993b2ed1f)

**Comment by Joonalai** [comment]
The bug does not seem to occur on Linux. At least not with the official [3.40.0. docker image](https://hub.docker.com/layers/qgis/qgis/3.40.0/images/sha256-4bdbf9b8f85c71e1ff4d8e2482fec58cd66ab59187f873aac138d4c833ac2690?context=explore) via Distrobox.

Version details:
<details>

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.40.0-Bratislava
-- | --
QGIS code revision | b56115d8743
 
Libraries
Qt version | 5.15.13
Python version | 3.12.3
GDAL/OGR version | 3.8.4
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.1
PostgreSQL client version | 16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
SpatiaLite version | 5.1.0
QWT version | 6.1.4
QScintilla2 version | 2.14.1
OS version | Ubuntu 24.04.1 LTS
 
Active Python plugins
db_manager | 0.1.20
MetaSearch | 0.3.6
processing | 2.12.99
grassprovider | 2.12.99

</body></html>QGIS version
3.40.0-Bratislava
QGIS code revision
[b56115d8743](https://github.com/qgis/QGIS/commit/b56115d8743)
 
Libraries
Qt version
5.15.13
Python version
3.12.3
GDAL/OGR version
3.8.4
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.1-CAPI-1.18.1
SQLite version
3.45.1
PostgreSQL client version
16.4 (Ubuntu 16.4-0ubuntu0.24.04.2)
SpatiaLite version
5.1.0
QWT version
6.1.4
QScintilla2 version
2.14.1
OS version
Ubuntu 24.04.1 LTS
 
Active Python plugins
db_manager
0.1.20
MetaSearch
0.3.6
processing
2.12.99
grassprovider
2.12.99

</details>

**Comment by JuhoErvasti** [comment]
I can confirm this happens on 3.38.3 and 3.40.0 (both on Linux).

Also on my machine the horizontal layers also cause significant slowing down:

![horizontal_layers](https://github.com/user-attachments/assets/8044fd75-a30d-4509-bbd2-b7a2b71d862b)

I'd say it's still a bit worse with the compound layers, although it's a bit difficult to tell / measure.

**Comment by nyalldawson** [comment]
Could you make a self contained project which **doesn't** require a docker image to test with?

**Comment by Joonalai** [comment]
I can test this issue with geopackage as well and provide it here.  

But for future reference I would like to ask why there is a problem with providing test data using docker images? If the problem lies with not wanting to use Docker, these can be run using Podman and docker-compose binary as well both on Windows and Linux. I personally use podman and docker-compose with podman-docker package.

I understand that it is easier to just open the project from geopackage in some trivial cases, but for some issues (e.g. #55753 and #56059) it is almost impossible to provide easy-to-replicate test data without containerization.

**Comment by Joonalai** [comment]
@nyalldawson the issue description is now updated with a geopackage way of replicating the bug. And it does behave the same way: slowness only occurs with compound crs layers and both compound and horizontal layers work just fine on 3.34.4.

**Comment by JuhoErvasti** [comment]
For me the 20 layers weren't enough to notice any slowing down, but with 60 layers I definitely notice the difference between 3.38.3 and 3.40.0, and also the difference between the horizontal/compound layers. I've attached a geopackage with 60 layers for testing.

[compound_60lyrs.zip](https://github.com/user-attachments/files/17587832/compound_60lyrs.zip)

**Comment by nyalldawson** [comment]
@Joonalai 
> But for future reference I would like to ask why is there a problem with providing test data using docker images? 
> I understand that it is easier to just open the project from geopackage in some trivial cases, but for some issues (e.g. https://github.com/qgis/QGIS/issues/55753 and https://github.com/qgis/QGIS/issues/56059) it is almost impossible to provide easy-to-replicate test data without containerization. I think that the threshold of reporting bugs should be kept as low as possible and if it's too difficult to create a reliably replicated use case without docker, some issues might be left unreported.

It's 100% about the effort in testing a bug. There's 1000s of open tickets here, and if a bug report makes a developer go through ANY unnecessary steps to reproduce then the outcome is that they'll just move onto a different ticket and the report will get buried in the past. IMO reducing the work for a developer to reproduce/fix is MUCH more important than reducing the work for a ticket to get reported.

Thanks for providing the GPKG version -- I can successfully reproduce using these.

**Comment by Joonalai** [comment]
Thank you so much for the really quick fix! :raised_hands:

> It's 100% about the effort in testing a bug. There's 1000s of open tickets here, and if a bug report makes a developer go through ANY unnecessary steps to reproduce then the outcome is that they'll just move onto a different ticket and the report will get buried in the past. IMO reducing the work for a developer to reproduce/fix is MUCH more important than reducing the work for a ticket to get reported.

I am really thankful for all the hard work you and the team put into developing the project. I did not in any way mean to be ungrateful or impolite in my previous message. I genuinely wanted to understand why docker is problematic. For me as a developer, it honestly felt like the simplest method for testing bugs, and I am sorry to hear that this is not the case.

If I may ask, could you possibly provide some guidance on the preferred methods for submitting test data, particularly in cases of non-file-provider-specific issues? For instance, with PostGIS, would it be more appropriate to include just a single SQL file? I always include SQL files even with a docker-compose zips to avoid relying on a running PostGIS instance. In the case of OAPIF, is there an alternative approach to containerization or perhaps would providing a pygeoapi config file be sufficient?

Thanks again for your time and insight. I'll make sure my future reports better fit your workflow to help with easier bug resolution.

**Comment by nyalldawson** [comment]
@Joonalai 

> am really thankful for all the hard work you and the team put into developing the project. I did not in any way mean to be ungrateful or impolite in my previous message. 

All good, I didn't get any "negative" tones from your reply! 👍

> I genuinely wanted to understand why docker is problematic. For me as a developer, it honestly felt like the simplest method for testing bugs, and I am sorry to hear that this is not the case.

> If I may ask, could you possibly provide some guidance on the preferred methods for submitting test data, particularly in cases of non-file-provider-specific issues? For instance, with PostGIS, would it be more appropriate to include just a single SQL file? 

I think for a postgres specific issue providing the self contained docker build is great -- that definitely reduces work.

But definitely a single file gpkg + embedded project is the SIMPLEST way to reproduce an issue.... Then there's absolutely nothing mucking around with paths or repairing projects or anything.

> In the case of OAPIF, is there an alternative approach to containerization or perhaps would providing a pygeoapi config file be sufficient?

A container also sounds great for this situation!

**Comment by Joonalai** [comment]
Thank you for the clarifications. It is good to know that docker can still be used when it is most needed in complex situations.
