### ISSUE TITLE
Crash when pressing the button to enter Google maps API Key

### ISSUE THREAD

**Issue by avikla** [qgis/QGIS#59294]
### What is the bug or the crash?

Crash when pressing the button to enter Google maps API Key

### Steps to reproduce the issue

When opening QGIS

### Versions

3.3.4
Python Stack Trace
Windows fatal exception: access violation

Current thread 0x0000173c (most recent call first):
  

Stack Trace

PyEval_SetTrace :
PyObject_Call :
PyObject_Call :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
PyInit_QtCore :
QObject::qt_static_metacall :
QAbstractButton::clicked :
QAbstractButton::mousePressEvent :
PyInit_QtWidgets :
QWidget::event :
PyInit_QtWidgets :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.34.11-Prizren
QGIS code revision: 2904bcec
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by DelazJ** [comment]
> **What is the bug or the crash?**
Crash when pressing the button to enter Google maps API Key
**Steps to reproduce the issue**
When opening QGIS

@avikla Afaict by default there is no button to enter Google maps API Key when launching QGIS. So you need to provide more details on the steps to follow in order to reproduce the crash, and whether you are using a plugin (in which case it might be worth reporting to the plugin author).
