### ISSUE TITLE
cannot import ui file from qt creator

### ISSUE THREAD

**Issue by GammaGames** [qgis/QGIS#59310]
### What is the bug or the crash?

While trying to update a plugin with QT Creator I get the following error while trying to import a plugin:

```log
  File "/home/username/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/sync/interfaces/settings_dialogue.py", line 8, in 
    FORM_CLASS, _ = uic.loadUiType(os.path.join(os.path.dirname(__file__), 'settings_dialogue.ui'))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/share/qgis/python/qgis/PyQt/uic/__init__.py", line 36, in __loadUiType
    return __PyQtLoadUiType(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/PyQt5/uic/__init__.py", line 207, in loadUiType
    exec(code_string.getvalue(), ui_globals)
  File "", line 10
    self.button_box.setOrientation(QtCore.Qt.Qt::Orientation::Horizontal)
                                               ^
SyntaxError: invalid syntax
```

### Steps to reproduce the issue

Create a basic UI and try to import it in a python plugin. For example here's my ui:
![image](https://github.com/user-attachments/assets/450023a0-df53-498a-9324-d3198a623c26)
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ui version="4.0">
 <class>ProjectDialogBase</class>
 <widget class="QDialog" name="ProjectDialogBase">
  <property name="geometry">
   <rect>
    <x>0</x>
    <y>0</y>
    <width>184</width>
    <height>47</height>
   </rect>
  </property>
  <property name="windowTitle">
   <string>Settings</string>
  </property>
  <widget class="QDialogButtonBox" name="button_box">
   <property name="geometry">
    <rect>
     <x>-10</x>
     <y>10</y>
     <width>181</width>
     <height>23</height>
    </rect>
   </property>
   <property name="orientation">
    <enum>Qt::Orientation::Horizontal</enum>
   </property>
   <property name="standardButtons">
    <set>QDialogButtonBox::StandardButton::Cancel|QDialogButtonBox::StandardButton::Ok</set>
   </property>
  </widget>
 </widget>
 <resources/>
 <connections>
  <connection>
   <sender>button_box</sender>
   <signal>rejected()</signal>
   <receiver>ProjectDialogBase</receiver>
   <slot>reject()</slot>
   <hints>
    <hint type="sourcelabel">
     <x>20</x>
     <y>20</y>
    </hint>
    <hint type="destinationlabel">
     <x>20</x>
     <y>20</y>
    </hint>
   </hints>
  </connection>
  <connection>
   <sender>button_box</sender>
   <signal>accepted()</signal>
   <receiver>ProjectDialogBase</receiver>
   <slot>accept()</slot>
   <hints>
    <hint type="sourcelabel">
     <x>20</x>
     <y>20</y>
    </hint>
    <hint type="destinationlabel">
     <x>20</x>
     <y>20</y>
    </hint>
   </hints>
  </connection>
 </connections>
</ui>
```

### Versions

* QGIS - 3.38.3
* QT Creator - 14.0.2

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

This used to work. According to [a comment](https://stackoverflow.com/questions/79148480/ui-files-made-with-qt-creator-have-invalid-syntax-for-qgis) on stackoverflow:

> The changed happened a few versions ago for Qt Designer (and therefore the parts of Creator using its elements), which introduced full namespaces for all enums, in order to make it full compliant with the same aspect in Python (IIRC). The latest PyQt versions should be able to cope with that, so the problem may be that QGIS doesn't have a properly updated pyuic.

**Comment by nyalldawson** [comment]
This isn't a qgis bug, but rather a pyqt/qt creator issue.
