### ISSUE TITLE
Crash after enter a python line

### ISSUE THREAD

**Issue by dpth44** [qgis/QGIS#59329]
## User Feedback

I opened the project, loaded two layers then I opened the oython console and entered : QgsLayerTreeView().selectedLayers() and QGIS crashed.

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000037a4 (most recent call first):
  File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\code.py", line 90 in runcode
    exec(code, self.locals)
  File "C:\PROGRA~1\QGIS33~1.0\apps\Python312\Lib\code.py", line 74 in runsource
    self.runcode(code)
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\console\console_sci.py", line 260 in runsource
    return super(PythonInterpreter, self).runsource(source, filename, symbol)
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\console\console_sci.py", line 237 in execCommandImpl
    res = self.runsource(src)
  File "C:\PROGRA~1/QGIS33~1.0/apps/qgis/./python\console\console_sci.py", line 360 in keyPressEvent
    super().keyPressEvent(e)
```

**Stack Trace**

```

QItemSelectionModel::selectedIndexes :
QgsLayerTreeView::selectedNodes :
QgsLayerTreeView::selectedLayerNodes :
QgsLayerTreeView::selectedLayers :
PyInit__gui :
PyObject_Call :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyDict_MergeFromSeq2 :
PyEval_EvalCode :
PyEval_GetBuiltins :
PyEval_GetBuiltins :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
Py_hashtable_compare_direct :
PyObject_Call :
PyObject_Call :
PyInit_sip :
PyInit_sip :
PyInit__gui :
QgsCodeEditor::runCommand :
QgsCodeEditor::keyPressEvent :
QgsCodeEditorPython::keyPressEvent :
PyInit__gui :
PyObject_Call :
PyObject_Vectorcall :
PyObject_Vectorcall :
PyEval_EvalFrameDefault :
PyFunction_Vectorcall :
Py_hashtable_compare_direct :
PyObject_Call :
PyObject_Call :
PyInit_sip :
PyInit_sip :
PyInit__gui :
QWidget::event :
QFrame::event :
QAbstractScrollArea::event :
PyInit__gui :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processKeyEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.38.0-Grenoble
QGIS code revision: 37aa6188bc
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.0
Running against GDAL: 3.9.0

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

Open the project
Add any layers
Open the python console 
Enter the following line : QgsLayerTreeView().selectedLayers()
Crash happen

### Versions

QGIS version
3.38.0-Grenoble
QGIS code revision
37aa6188bc
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.0
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
AnotherDXF2Shape
1.3.2
BoundingBox
2.2
coordinates_converter
1.0
ORStools
1.8.4
pluginbuilder3
3.2.1
plugin_reloader
0.17
qgis-maptiler-plugin
3.3.2
slyr_community
5.0.0
SRTM-Downloader
3.2.3
voltalia_romania_tools
0.1
voltalia_south_africa_tools
0.1
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
In order to obtain the list of the selected layer, you need to use `iface.layerTreeView().selectedLayers()`.

**Comment by dpth44** [comment]
> In order to obtain the list of the selected layer, you need to use `iface.layerTreeView().selectedLayers()`.

I ran accross another bug in my plugin when trying to retrieve the selectedLayers after the iface.layerTreeView().currentLayerChanged() event. So I tried another method QgsLayerTreeView().selectedLayers(), which caused the crash.
