### ISSUE TITLE
QGis silently crashes on the Diagram page

### ISSUE THREAD

**Issue by ivan-n-gor** [qgis/QGIS#59324]
### What is the bug or the crash?

QGis silently crashes when I try to set Diagram properties of the layer.

### Steps to reproduce the issue

1. Add a new or existing point layer
2. Go to layer properties and select _Diagrams_ page
3. Try to change Diagram type from _No Diagrams_ to anything
4. Crash

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.12.2</td></tr><tr><td>GDAL/OGR version</td><td>3.8.5</td></tr><tr><td>PROJ version</td><td>9.4.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.004 (2024-02-24)</td></tr><tr><td>GEOS version</td><td>3.12.1-CAPI-1.18.1</td></tr><tr><td>SQLite version</td><td>3.46.0</td></tr><tr><td>PDAL version</td><td>2.7.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.5</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>ALT Starterkit 11 (Salvia)</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>arc_3d</td><td>0.2</td></tr><tr><td>ssg_lab_support</td><td>0.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Same crash occurs in the OSgeo4W version 3.40 under Windows

**Comment by hanreev** [comment]
same here QGIS 3.40 on Ubuntu 24.04 and Windows OSGeo4W

**Comment by m-kuhn** [comment]
Cc @gacarrillor

**Comment by gacarrillor** [comment]
@ivan-n-gor and @hanreev, thank you for reporting the issue. It's been fixed and will be soon available via QGIS nightly builds, or in the next point release (v3.40.1) due 2024-11-22 12:00:00 UTC.
