### ISSUE TITLE
QGIS 3.40 Crash MacOS Sequoia

### ISSUE THREAD

**Issue by FalconWing04** [qgis/QGIS#59338]
### What is the bug or the crash?

QGIS Python Non-Functional in this version, I did a clean install, came up with the same issue, all previous versions work including QGIS 3.38.3. I looked at the error and it seems to be not detecting the correct MacOS, it is showing MacOS 10.13. when it is MacOS 15.

I suggest disabling the download link temporarily:)

### Steps to reproduce the issue

Reproduced error through clean install instead of replacing QGIS which was completed earlier.

### Versions

QGIS 3.40 only.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@FalconWing04, is it the same issue reported at https://github.com/qgis/QGIS/issues/59321?

**Comment by FalconWing04** [comment]
Yes, looks like the same issue QGIS 3.40.0. It should be noted that QGIS 3.83.3 works without any issues in MacOS Sequoia.
