### ISSUE TITLE
deleting a field in an fgdb leads to a messed up attribute table

### ISSUE THREAD

**Issue by Jeroen-GroeneBij** [qgis/QGIS#59348]
### What is the bug or the crash?

Using a file gedodatabse in QGIS 3.34.10 on Windows.
When deleting a field using the Delete Field option in the Attribute Table screen and the clicking the save icon completely messes up the attribute table and the layer visualization does not work (the referenced fields have no data or wrong data.
However, on reloading the project (F5), or removing and re-adding the layer everything is fine again.

### Steps to reproduce the issue

I added a test fgdb with Dutch Natura2000 area's which I created by exporting WFS data as Esri File Geodatabase in QGIS.
I noticed the bug using an fgdb which I can not share, but I don't think the source matters, I think it has something to do with the way the attribute table handles an fgdb.

[natura2000.gdb.zip](https://github.com/user-attachments/files/17644943/natura2000.gdb.zip)
Add the layer in QGIS, open the Attribute Table, Delete field "vhnNew", click Save and notice the messed up Attribute Table.
Reload the Project (F5) and notice the correct Attribute table.
This behaviour is also visible when deleting a field through the Layer Properties Fields menu with the attribute table open. As soon as you Save the table is messed up.

Original table
![afbeelding](https://github.com/user-attachments/assets/12fc3d53-385b-40ee-b949-182fce7c979f)

Before Reloading
![afbeelding](https://github.com/user-attachments/assets/33577368-4dc8-44e4-909d-ca59c96e0f4a)

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS version | 3.34.11-Prizren | QGIS code revision | 2904bcec
-- | -- | -- | --
Qt version | 5.15.13
Python version | 3.12.6
GDAL/OGR version | 3.9.2
PROJ version | 9.4.0
EPSG Registry database version | v11.004 (2024-02-24)
GEOS version | 3.12.2-CAPI-1.18.2
SQLite version | 3.45.1
PDAL version | 2.6.3
PostgreSQL client version | 16.2
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.14.1
OS version | Windows 10 Version 2009
  |   |   |  
Active Python plugins
batchvectorlayersaver | 0.9
GroupStats | 2.2.7
inspireatomclient | 0.8.1
maplibrary | 1.3
pdokservicesplugin | 5.1.1
pdok_locatieserver_locator_filter | 0.2.1
PluginLoadTimes | 4.1.0
qgis2web | 3.23.0
QNEAT3 | 1.0.5
quick_map_services | 0.19.34
SelectionFilter | 1.0
SpreadsheetLayers | 2.1.2
wfs_styler | 1.0.1
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>QGIS version
3.34.11-Prizren
QGIS code revision
[2904bcec](https://github.com/qgis/QGIS/commit/2904bcec)
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
batchvectorlayersaver
0.9
GroupStats
2.2.7
inspireatomclient
0.8.1
maplibrary
1.3
pdokservicesplugin
5.1.1
pdok_locatieserver_locator_filter
0.2.1
PluginLoadTimes
4.1.0
qgis2web
3.23.0
QNEAT3
1.0.5
quick_map_services
0.19.34
SelectionFilter
1.0
SpreadsheetLayers
2.1.2
wfs_styler
1.0.1
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Jeroen-GroeneBij, thanks for reporting. It seems to me the reported issue has been already previously reported https://github.com/qgis/QGIS/issues/58669 and fixed https://github.com/qgis/QGIS/pull/58733.
Please try if the issue does occur using QGIS 3.34.0 or the upcoming QGIS LTR 3.34.13.

**Comment by Jeroen-GroeneBij** [comment]
Thanks for spotting that earlier issue. And it seems to be fixed in 3.40.0
For now it is still present in 3.34.12. I'll check when 3.34.13 is out.
