### ISSUE TITLE
Custom Splash Screen for QGIS?

### ISSUE THREAD

**Issue by danodom-tcb** [qgis/QGIS#59356]
### What is the issue about the documentation?

Is there a way to replace the current splash screen with a custom splash screen"

I see that there is splash.png in the source repo, which appears to be the one used for custom builds.  From what I can tell, this turns into an embedded resource somewhere in the process as I am not seeing a splash.png in the build artifacts.

Mainly, the question is, if I want a custom splash screen, I assume that I have to to replace the Splash.png with a custom image and build?  or is there a way to change this once the artifacts are built.

**Comment by arno974** [comment]
You can easily customize the QGIS Splashscreen : https://geotribu.fr/articles/2021/2021-06-11_qgis_personnaliser_splash_screen/#activer-la-personnalisation-de-linterface (in french).

**Comment by agiudiceandrea** [comment]
> Questions should go to the qgis-user mailing list at https://lists.osgeo.org/mailman/listinfo/qgis-user or other support forums such as https://gis.stackexchange.com/. GitHub issues are for bug reports and suggestions for new features.

**Comment by kannes** [comment]
https://gis.stackexchange.com/questions/68988/customising-splash-image-of-qgis
