### ISSUE TITLE
QGIS crashes after opening

### ISSUE THREAD

**Issue by Hiwijk** [qgis/QGIS#59365]
### What is the bug or the crash?

QGIS crashes after opening, even without doing anything. Happens not always but often, also in different computers and projects.

### Steps to reproduce the issue

Open a project

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

QGIS-Version | 3.34.9-Prizren | QGIS-Codeversion | cbbc7bdf
-- | -- | -- | --
Qt-Version | 5.15.13
Python-Version | 3.12.4
GDAL-Version | 3.9.1
PROJ-Version | 9.4.0
EPSG-Registraturdatenbankversion | v11.004 (2024-02-24)
GEOS-Version | 3.12.2-CAPI-1.18.2
SQLite-Version | 3.45.1
PDAL-Version | 2.6.3
PostgreSQL-Client-Version | 16.2
SpatiaLite-Version | 5.1.0
QWT-Version | 6.2.0
QScintilla2-Version | 2.14.1
BS-Version | Windows 10 Version 2009
  |   |   |  
Aktive Python-Erweiterungen
GroupStats | 2.2.7
iso4app | 1.5
QuickOSM | 2.2.3
SpreadsheetLayers | 2.1.2
processing | 2.12.99

</body></html>QGIS-Version
3.34.9-Prizren
QGIS-Codeversion
[cbbc7bdf](https://github.com/qgis/QGIS/commit/cbbc7bdf)
Qt-Version
5.15.13
Python-Version
3.12.4
GDAL-Version
3.9.1
PROJ-Version
9.4.0
EPSG-Registraturdatenbankversion
v11.004 (2024-02-24)
GEOS-Version
3.12.2-CAPI-1.18.2
SQLite-Version
3.45.1
PDAL-Version
2.6.3
PostgreSQL-Client-Version
16.2
SpatiaLite-Version
5.1.0
QWT-Version
6.2.0
QScintilla2-Version
2.14.1
BS-Version
Windows 10 Version 2009

Aktive Python-Erweiterungen
GroupStats
2.2.7
iso4app
1.5
QuickOSM
2.2.3
SpreadsheetLayers
2.1.2
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Hiwijk, please try if the issue occurs also using a new QGIS user profile without any external third-party plugin installed.

**Comment by Hiwijk** [comment]
Sadly I can not provide a crash report. The qgis window closes without any warning or report.
