### ISSUE TITLE
QGIS ended unexpectedly.

### ISSUE THREAD

**Issue by MortGis** [qgis/QGIS#59379]
## User Feedback

Yesterday the program worked without any problems.
I was using version 3.36 Maidenhead.
The error shows during startup.
I downloaded and installed the latest version 3.40, but the program still does not run.

## Report Details

**Crash ID**: [a6a8c2b5b52f9b428aeb328dad77f27062bef96f](https://github.com/qgis/QGIS/search?q=a6a8c2b5b52f9b428aeb328dad77f27062bef96f&type=Issues)

**Stack Trace**

```

eglGetProcAddress :
eglGetProcAddress :
eglGetProcAddress :
eglGetProcAddress :
eglGetProcAddress :
eglGetProcAddress :
eglGetProcAddress :
IcdPresentBuffers :
IcdPresentBuffers :
IcdPresentBuffers :
DrvSetCallbackProcs :
DrvSetCallbackProcs :
pgldrvLoadAndAllocDriverInfo :
LoadAvailableDrivers :
_DescribePrimaryPixelFormat :
wglNumHardwareFormats :
wglDescribePixelFormat :
wglChoosePixelFormat :
ChoosePixelFormat :
QOpenGLContext::create :
QGuiApplicationPrivate::init :
QApplicationPrivate::init :
QApplication::QApplication :
QgsApplication::QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.40.0-Bratislava
QGIS code revision: b56115d874
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.3
Running against GDAL: 3.9.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.19045

### Steps to reproduce the issue

Just start the program 

### Versions

3,36 Maidenhead and 3,40 

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@MortGis, please try if the issue occurs also using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
