### ISSUE TITLE
Crash on project save

### ISSUE THREAD

**Issue by avikla** [qgis/QGIS#59389]
### What is the bug or the crash?

Python Stack Trace
Windows fatal exception: access violation

Current thread 0x00003b78 (most recent call first):
  

Stack Trace

QgsVertexTool::~QgsVertexTool :
QgsPointLocator::verticesInRect :
SpatialIndex::MovingRegion::getProjectedSurfaceAreaInTime :
SpatialIndex::MovingRegion::getProjectedSurfaceAreaInTime :
QgsPointLocator::nearestVertex :
QgsVertexTool::findCoincidentVertices :
QgsVertexTool::startDraggingMoveVertex :
QgsVertexTool::startDragging :
QgsVertexTool::cadCanvasReleaseEvent :
QgsMapToolAdvancedDigitizing::canvasReleaseEvent :
QgsMapCanvas::mouseReleaseEvent :
QWidget::event :
QFrame::event :
QGraphicsView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :

QGIS Info
QGIS Version: 3.34.11-Prizren
QGIS code revision: 2904bcec
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.2
Running against GDAL: 3.9.2

System Info
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

While strying to save a vector layer

### Versions

latest LTR

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@avikla, thanks for reporting. Please try if the issue occurs also using a [new QGIS user profil](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)e. Please specify if the issue occurs saving the project (as stated in the report's title) or saving the layer (as stated in the report's description). If the former, please provide the affected project, if the latter, please provide the affected layer.
