### ISSUE TITLE
problem saving changes to a project

### ISSUE THREAD

**Issue by aymenelka** [qgis/QGIS#59396]
### What is the bug or the crash?

while using the Qgis desktop app, when trying to save changes to a layer, I get the message ''could not commit changes to layer...''

### Steps to reproduce the issue

<img width="296" alt="Screenshot 2024-11-10 221738" src="https://github.com/user-attachments/assets/47114653-d0d0-4367-87d1-0d4e77f46573">
![QHE qgz](https://github.com/user-attachments/assets/9789c2b6-aaf5-4291-923c-da8749777bab)

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/b56115d874">b56115d874</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@aymenelka, thanks for reporting. Please provide the affected layer and detailed step by step instruction in order to replicate the issue.

**Comment by aymenelka** [comment]
I can't save both the project and the layers.
here is the project file
![QHE qgz](https://github.com/user-attachments/assets/a6cd2ec2-e3df-4329-be98-bcba9f7e8b7d)

**Comment by aymenelka** [comment]
[PROJ_COLLINE.zip](https://github.com/user-attachments/files/17739270/PROJ_COLLINE.zip)
1-make a modification in a layer .
2-save the project or save the chages in the layer you modified.

**Comment by agiudiceandrea** [comment]
@aymenelka I cannot replicate the reported issue running QGIS 3.40.0 on Windows 10 and Windows 11 and using the provided project and following the provided steps:


https://github.com/user-attachments/assets/0bcc0625-a9f8-4cf9-8488-ec2696f24f4b
