### ISSUE TITLE
qgis crached when dleting a virtual field in teh attribute tabels

### ISSUE THREAD

**Issue by damstep** [qgis/QGIS#59417]
## User Feedback

deleteing a virtual field in a table

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x000052a0 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QgsField::QgsField :
QgsFields::at :
QgsAttributeTableModel::data :
QSortFilterProxyModel::data :
QgsAttributeTableFilterModel::data :
QgsAttributeTableDelegate::paint :
QTableView::doItemsLayout :
QTableView::paintEvent :
QWidget::event :
QFrame::event :
QAbstractItemView::viewportEvent :
QCoreApplicationPrivate::sendThroughObjectEventFilters :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::drawWidget :
QWidgetPrivate::moveRect :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QCoreApplicationPrivate::sendPostedEvents :
qt_plugin_query_metadata :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QgsDualView::progress :
QObject::qt_static_metacall :
QgsAttributeTableModel::progress :
QgsAttributeTableModel::loadLayer :
QObject::qt_static_metacall :
QObject::qt_static_metacall :
QgsVectorLayer::updateFields :
QgsVectorLayer::deleteAttribute :
QgsVectorLayer::deleteAttributes :
QgsAttributeTableDialog::mActionRemoveAttribute_triggered :
QObject::qt_static_metacall :
QAction::activate :
QAbstractButton::click :
QAbstractButton::mouseReleaseEvent :
QToolButton::mouseReleaseEvent :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QApplicationPrivate::sendMouseEvent :
QSizePolicy::QSizePolicy :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processMouseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.40.0-Bratislava
QGIS code revision: b56115d874
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.3
Running against GDAL: 3.9.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

in attribute table create a virtual field.
then delete the vitrual field

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/b56115d874">b56115d874</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 11 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>active_fire</td><td>0.3</td></tr><tr><td>attributePainter</td><td>5.3</td></tr><tr><td>autoSaver</td><td>2.9</td></tr><tr><td>coordinate_capture</td><td>0.2</td></tr><tr><td>FreehandRasterGeoreferencer</td><td>0.8.3</td></tr><tr><td>GeoCoding</td><td>2.19</td></tr><tr><td>GeometryShapes</td><td>0.7</td></tr><tr><td>geoscience</td><td>1.15</td></tr><tr><td>GroupStats</td><td>2.2.7</td></tr><tr><td>ioGAS</td><td>ioGAS plugin for QGIS ver 3.22 (build 201683)</td></tr><tr><td>MagneticDeclination</td><td>2.4.4</td></tr><tr><td>Mergin</td><td>2024.2.1</td></tr><tr><td>processing_saga_nextgen</td><td>1.0.0</td></tr><tr><td>qfieldsync</td><td>v4.11.0</td></tr><tr><td>qgis-stereonet</td><td>0.3</td></tr><tr><td>quick_map_services</td><td>0.19.34</td></tr><tr><td>SemiAutomaticClassificationPlugin</td><td>8.4.0</td></tr><tr><td>slyr</td><td>7.5.3</td></tr><tr><td>SpreadsheetLayers</td><td>2.1.2</td></tr><tr><td>SRTM-Downloader</td><td>3.2.3</td></tr><tr><td>zoom_level</td><td>0.3.1</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@damstep, thanks for reporting. Please actually try if the issue does occur also using a new QGIS user profile without any third-party external plugin installed. If it does, please provide a sample project and layer and detailed step-by-step instruction in order to replicate the issue.
