### ISSUE TITLE
QGIS Crashes When Changing to Pie Chart Symbology (Diagrams

### ISSUE THREAD

**Issue by charles483** [qgis/QGIS#59412]
### What is the bug or the crash?

When attempting to change the symbology of a layer to Pie Charts (Diagrams) in the latest version of QGIS, the application crashes unexpectedly. The crash occurs when selecting the Diagrams option under the Symbology tab, and specifically when trying to apply pie charts to display the relationship between population and area within polygons.

### Steps to reproduce the issue

Open a layer with polygons (e.g., subcounty boundaries with attributes for population and area).
Go to the Symbology tab in the Layer Properties window.
Change the symbology type to Diagrams.
Select Pie Chart as the diagram type.
Configure the data fields for the pie chart (e.g., population and area).
Apply the changes.

### Versions

QGIS version
3.40.0-Bratislava
QGIS code revision
b56115d874
 
Libraries
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.9.3
PROJ version
9.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009
 
Active Python plugins
geocatbridge
4.5.1
mmqgis
2024.11.8
QuickOSM
2.2.3
quick_map_services
0.19.34
SVG2ColoR
1.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

No relevant error messages displayed, only an immediate crash.

**Comment by agiudiceandrea** [comment]
Already reported https://github.com/qgis/QGIS/issues/59324 and already fixed https://github.com/qgis/QGIS/pull/59340. The fix will be available in QGIS 3.40.1.
