### ISSUE TITLE
PermissionError with faulthandler on QGIS 3.40.0 (MacBook Air M1, macOS Sequoia 15.1, MacPorts)

### ISSUE THREAD

**Issue by K-Dai48** [qgis/QGIS#59439]
### What is the bug or the crash?

An error occurred while executing the following code:
faulthandler.enable(file=qgis.utils.__qgis_fault_handler_file)

Traceback (most recent call last):
  File "", line 1, in 
PermissionError: [Errno 1] Operation not permitted

### Steps to reproduce the issue

1. Open QGIS3 Desktop.
2. Observe that a Python error window appears immediately upon startup.

### Versions

QGIS version: 3.40.0-Bratislava
OS: macOS Sequoia 15.1
Device: MacBook Air (M1)
Installation method: MacPorts

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

I’m using a MacBook Air (M1) with macOS Sequoia 15.1 and installed QGIS 3.40.0-Bratislava via MacPorts. To troubleshoot this issue, I’ve tried the following steps:
	•	Checked directory permissions to ensure that QGIS has write access.
	•	Attempted to set up faulthandler to capture error logs in an external file.
	•	Created and tested with a new QGIS profile to rule out profile-related issues.
	•	Granted QGIS “Full Disk Access” in macOS security settings.
	•	Reinstalled QGIS to ensure a clean installation.

Despite these efforts, the error persists on every startup. Any guidance on resolving this issue would be greatly appreciated. Thank you.

**Comment by agiudiceandrea** [comment]
The issue has been already previously reported at https://github.com/qgis/QGIS/issues/52987.
