### ISSUE TITLE
Shape file upload - Incomplete

### ISSUE THREAD

**Issue by JCRanger100** [qgis/QGIS#59443]
### What is the bug or the crash?

I'm uploading a large shape file. Only one portion of the shape file is showing on the map.

The shape file should cover the area to the north upto the road.

I have tried with several files all with the same issue.

![image](https://github.com/user-attachments/assets/3d506b71-4234-4ed7-98f8-448ed4c98271)

### Steps to reproduce the issue

![Screenshot 2024-11-14 101935](https://github.com/user-attachments/assets/962274a1-190a-4970-b96f-2d6cebe24e0b)

### Versions

QGIS version
3.34.11-Prizren
QGIS code revision
2904bcec
Qt version
5.15.13
Python version
3.12.6
GDAL/OGR version
3.9.2
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
ArcGeekCalculator
2.4beta
arc_3d
0.2
DEMto3D
3.6
HCMGIS
24.10.20
ImageServerConnector
2.1.1
oneclickrasterstacking
1.1.0
pg_raster_import
3.2.0
pml_geopackager
1.0
polygonclickmap
0.7
processing_saga_nextgen
1.0.0
QuickOSM
2.2.3
RiverBankErosionAccretion-main
0.1
rivergis
3.0
RiverMetrics
1.2
shapefile_encoding_fixer
0.7.1
TerrainShading
0.9.5
terrainzones
2.0
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99
pcraster_tools
0.3.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@JCRanger100, thanks for reporting. May you please clarify where are you uploading the layer and how exactly?

**Comment by agiudiceandrea** [comment]
@JCRanger100, the ESRI Shapefile file format can only store vector data, not images.
If I understand correctly, you have added in a QGIS a raster layer (which format exactly?) created by en external third-party software, but it doesn't display the way you expect it to be.
I suggest you to check that the image was created correctly by the external third-party software. If the issue persist, you need to provide the raster layer file in order to verify if there is actually a bug in QGIS and try to fix it.
