### ISSUE TITLE
Ignore NoData values Zonal Statistics

### ISSUE THREAD

**Issue by adlai-nelson** [qgis/QGIS#59457]
### Feature description

Zonal Statistics currently does not have an option to ignore nodata values in the raster. 

For example, if you are calculating the mean of a raster within a polygon and the image has any nodata values, the mean of the entire polygon will be listed as n/a. I am proposing to add a feature to ignore nodata values, and returns the calculated mean excluding those nodata pixels.

This does not seem too difficult to implement, and it would make geoprocessing a lot easier.

**Comment by nicogodet** [comment]
I use zonal statistics on daily basis and I don't have your issue (mean is calculated on non NoData values)
Could you share a sample data ?

**Comment by adlai-nelson** [comment]
Thank you for your response. I was using the [Biodiversity Intactness](https://planetarycomputer.microsoft.com/dataset/io-biodiversity#Example-Notebook) dataset as available on planetary computer and read in using the [STAC browser plugin](https://stac-utils.github.io/qgis-stac-plugin/). I think my issue is that I was building a virtual raster to do this analysis, I'm not sure why that wouldn't work but I guess I need to download and mosaic the images.

**Comment by nicogodet** [comment]
@adlai-nelson This may comes from STAC plugin. I saw PR to implement this plugin in QGIS Core: https://github.com/qgis/QGIS/pulls?q=is%3Apr+STAC+is%3Aclosed
I suggest to retry with core feature (QGIS >3.40).

For sure, with a raster loaded with GDAL, NoData pixels are ignored from stat computations.

**Comment by adlai-nelson** [comment]
Thank you! That's great to hear - I was on 3.34 LTR but I'll try with the latest version.

**Comment by adlai-nelson** [comment]
Using QGIS 4.40 extracted zonal statistics correctly- thanks again @nicogodet for your responses.
