### ISSUE TITLE
QgsTask does not call finished after run completed

### ISSUE THREAD

**Issue by nabazgharib** [qgis/QGIS#59464]
### What is the bug or the crash?

I created a Task from (QgsTask), after runing it does not call finished function.

### Steps to reproduce the issue

1. Create a plugin
2. Create a task class
3. call the task class from the plugin.

```
from qgis.core import QgsTask

class MyTask(QgsTask):

    def __init__(self,description=None):

        super().__init__(description, QgsTask.CanCancel)
        self.exception = None

    def run(self):
        return True

    def finished(self, result):

        if result:
            print("Finished Function True ")
        else:
            print("Finished Function False ")
```

### Versions

QGIS version
3.34.12-Prizren
QGIS code revision
eeb6af3638
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.9.3
PROJ version
9.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 11 Version 2009

Active Python plugins
plugin_reloader
0.17
elevation_tile_plugin
0.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
From `QgsTask::finished` docs: 
_If the task is managed by a QgsTaskManager, this will be called after the task has finished_

```python
>>> t=MyTask()
>>> QgsApplication.taskManager().addTask(t)
5
Finished Function True
```
How do you run the task?

**Comment by nabazgharib** [comment]
Did you run the code in the python console i side QGIS? It works in the console, however it does not work inside a plugin. Create a simple plugin and run the class, using taskManger().addTask(t).

**Comment by uclaros** [comment]
Also works as expected in a plugin:
```python
from PyQt5.QtWidgets import QAction, QMessageBox
from qgis.core import QgsApplication, QgsTask

class MyTask(QgsTask):

    def __init__(self,description=None):

        super().__init__(description, QgsTask.CanCancel)
        self.exception = None

    def run(self):
        return True

    def finished(self, result):

        if result:
            print("Finished Function True ")
        else:
            print("Finished Function False ")

def classFactory(iface):
    return MinimalPlugin(iface)


class MinimalPlugin:
    def __init__(self, iface):
        self.iface = iface

    def initGui(self):
        self.action = QAction('Go!', self.iface.mainWindow())
        self.action.triggered.connect(self.run)
        self.iface.addToolBarIcon(self.action)

    def unload(self):
        self.iface.removeToolBarIcon(self.action)
        del self.action

    def run(self):
        self.t = MyTask()
        QgsApplication.taskManager().addTask(self.t)
```
gives
```
Finished Function True
```

**Comment by nabazgharib** [comment]
I look like something was wrong about the QGIS I installed on my machine, because other errors popped up. therefore, I reinstall it.

It works now, 

appreciate your quick reply,

**Comment by jjperez9000** [comment]
I came across this problem, and my issue ended up being that I forgot to assign the task to self. Not assigning to self will run the task "run" function, *but not the "finish" function.*
essentially 

runs finish:
```python
def run(self):
   self.t = MyTask()
   QgsApplication.taskManager().addTask(self.t)
```

skips finish:
```python
def run(self):
  task = MyTask()
  QgsApplication.taskManager().addTask(task)
```
