### ISSUE TITLE
Error during execution (startup) involving python

### ISSUE THREAD

**Issue by danardoin** [qgis/QGIS#59467]
### What is the bug or the crash?

QGIS error during application startup (open the app). Three code execution errors occurred. QGIS loaded but I'm not sure what execution errors failed to include.

![QGIS Startup error 1](https://github.com/user-attachments/assets/d6d0090b-7755-4b33-a1ac-46009dc9adcf)
![Image 11-17-24 at 1 31 PM](https://github.com/user-attachments/assets/d67a8364-ad3f-419c-ae54-d083f6cf31eb)
![Image 11-17-24 at 1 31 PM (1)](https://github.com/user-attachments/assets/b24431df-9f8c-4dfd-9828-1e7f54ea0144)

### Steps to reproduce the issue

Open the QGIS application.

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/1d561ad8ad9">1d561ad8ad9</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.2</td></tr><tr><td>Python version</td><td>3.9.5</td></tr><tr><td>GDAL/OGR version</td><td>3.3.2</td></tr><tr><td>PROJ version</td><td>8.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.028 (2021-07-07)</td></tr><tr><td>GEOS version</td><td>3.9.1-CAPI-1.14.2</td></tr><tr><td>SQLite version</td><td>3.35.2</td></tr><tr><td>PDAL version</td><td>2.3.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.6</td></tr><tr><td>QScintilla2 version</td><td>2.11.5</td></tr><tr><td>OS version</td><td>macOS 15.1</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>slyr_community</td><td>5.0.0</td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>kmltools</td><td>3.2.2</td></tr><tr><td>qgis_hats</td><td>1.8</td></tr><tr><td>active_fire</td><td>0.3</td></tr><tr><td>joinmultiplelines</td><td>Version 0.4.1</td></tr><tr><td>qgis-fit-plugin</td><td>0.3</td></tr><tr><td>quick_map_services</td><td>0.19.35</td></tr><tr><td>cartography_tools</td><td>1.2.1</td></tr><tr><td>QuickPrint</td><td>3.6.1</td></tr><tr><td>aino-qgis-plugin-main</td><td>0.1.2</td></tr><tr><td>trail_elevation_stats</td><td>0.2</td></tr><tr><td>valuetool</td><td>3.0.19</td></tr><tr><td>annotationManager</td><td>0.5</td></tr><tr><td>road_slope_calculator</td><td>0.5</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>CustomToolBar</td><td>1.1</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/59321
