### ISSUE TITLE
End caps rendering on top of different rule style

### ISSUE THREAD

**Issue by gotjoshua** [qgis/QGIS#59475]
### What is the bug or the crash?

When i make rule based styles for a linestring vector layer, the caps for the bottom rule are rendering above the line for the top rule.

![Screenshot from 2024-11-18 11-53-59](https://github.com/user-attachments/assets/85c09e78-a3b9-4084-a97f-5f19cd245162)
![Screenshot from 2024-11-18 11-53-41](https://github.com/user-attachments/assets/2d1773bd-a41e-43f5-be09-cebe7b2c413f)
![Screenshot from 2024-11-18 11-53-34](https://github.com/user-attachments/assets/bc9d7804-d299-4db3-a709-4b75b1bd648c)

### Steps to reproduce the issue

Setup 2 rules, one with an empty filter, one with a meaningful filter.
place the empty one with a more thin line style at the bottom of the list (so that it renders on top)
toggle the cap style for the "lower" layer
notice that it blocks the rendering of the other rule

### Versions

QGIS version | 3.36.3-Maidenhead | QGIS code branch | Release 3.36
-- | -- | -- | --
Qt version | 5.15.14
Python version | 3.11.10
GDAL/OGR version | 3.8.5
PROJ version | 9.4.1
EPSG Registry database version | v11.006 (2024-03-13)
GEOS version | 3.12.1-CAPI-1.18.1
SQLite version | 3.45.3
PDAL version | 2.7.2
PostgreSQL client version | unknown
SpatiaLite version | 5.1.0
QWT version | 6.2.0
QScintilla2 version | 2.13.2
OS version | NixOS 24.05 (Uakari)
  |   |   |  
Active Python plugins
qgis-maptiler-plugin | 3.3.2
pg_raster_import | 3.2.0
HCMGIS | 24.10.20
processing_saga_nextgen | 1.0.0
Mergin | 2024.2.1
autoSaver | 2.9
db_manager | 0.1.20
processing | 2.12.99
grassprovider | 2.12.99
GeometryShapes | 0.7
bearing_distance | 1.0
qfieldsync | v4.11.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by andreasneumann** [comment]
Hi @gotjoshua - this is not a bug.

You'll have to use "symbol levels" to avoid that behavior.

See https://docs.qgis.org/3.40/en/docs/user_manual/working_with_vector/vector_properties.html#symbol-levels or Google for it to find discussions or tutorials around symbol levels.

![grafik](https://github.com/user-attachments/assets/a94d880d-8b0f-4721-adb6-c2a303f2659e)

**Comment by gotjoshua** [comment]
thanks @andreasneumann  - i really searched a fair bit, but maybe it was too specific to the "end caps rendering" issue i had. cheers!
