### ISSUE TITLE
'Prompt for CRS setting not working'

### ISSUE THREAD

**Issue by elk95** [qgis/QGIS#59480]
### What is the bug or the crash?

QGIS 3.40.0 'Bratislava' after changing options for CRS Handling under CRS for Layers to 'Prompt for CRS' for a new layer with no CRS, importing a layer without CRS does not trigger the prompt window. I am currently teaching a course and this happened to a few people so it's not just on my computer

### Steps to reproduce the issue

Go to Settings > Options
Click on CRS Handling
Under CRS for Layers: 'When new layer is created, or when a layer is loaded that has no CRS' select 'Prompt for CRS'
Click ok
Open shapefile which doesn't have an associated .prj file (example attached)
[Natura2000Sites.zip](https://github.com/user-attachments/files/17805807/Natura2000Sites.zip)
Layer is loaded without a CRS and no prompt for CRS window opening
![image](https://github.com/user-attachments/assets/6d9f9e7f-0b69-479b-9f3b-19214e8da48f)

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.0-Bratislava</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/b56115d874">b56115d874</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.13</td></tr><tr><td>Python version</td><td>3.12.7</td></tr><tr><td>GDAL/OGR version</td><td>3.9.3</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.46.1</td></tr><tr><td>PDAL version</td><td>2.8.1</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>Windows 10 Version 2009</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>Mergin</td><td>2024.1</td></tr><tr><td>NNJoin</td><td>3.1.3</td></tr><tr><td>quick_map_services</td><td>0.19.34</td></tr><tr><td>TomBio</td><td>3.4.4</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
Thanks for reporting. It looks like that the issue occurs using QGIS >= 3.38 and that even the other options ("Use project CRS" and "Use default layer CRS") don't work.
