### ISSUE TITLE
For Mapinfo table, in feature embeddedSymbol is None

### ISSUE THREAD

**Issue by grig27** [qgis/QGIS#59518]
### What is the bug or the crash?

Get feature.embeddedSymbol() return = None.

### Steps to reproduce the issue

Open Mapinfo table. 
Renderer set is QgsEmbeddedSymbolRenderer.

In map, layer style changed for features.

### Versions

3.40.0

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Can you provide more details please? This report is only partially completed.

**Comment by grig27** [comment]
1. Open Mapinfo table.
2. Select feature on map canvas.
3. Execute - 
`
l = iface.activeLayer()
sf = l.selectedFeatures()
s = sf[0]
es = s.embeddedSymbol()
`
es is None
