### ISSUE TITLE
Merge Raster converts Red to Gray (Band 1)

### ISSUE THREAD

**Issue by CWGwaltney** [qgis/QGIS#59558]
### What is the bug or the crash?

Merge Raster converts Red to Gray (Band 1)

### Steps to reproduce the issue

![image](https://github.com/user-attachments/assets/a7c42b33-e708-4714-92d0-cd008bc6d767)

![image](https://github.com/user-attachments/assets/bb63f716-f5ff-4a63-82e9-4936860d4561)

![image](https://github.com/user-attachments/assets/fef4dd45-45fc-4e5c-8a07-085d841269b5)

![image](https://github.com/user-attachments/assets/c3cec44b-d447-426a-b96f-f5196b1a0a80)

Source RGB Ortho Photo Tiles
 Raster->Miscelanious->Merge->Save As Tiff

Source Raster is RGB
Merged Raster is Band 1-Gray and the red is removed or distorted in the merged raster

### Versions

QGIS version
3.38.1-Grenoble
QGIS code revision
3d4177af
Qt version
5.15.13
Python version
3.12.4
GDAL/OGR version
3.9.1
PROJ version
9.4.0
EPSG Registry database version
v11.004 (2024-02-24)
GEOS version
3.12.2-CAPI-1.18.2
SQLite version
3.45.1
PDAL version
2.6.3
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.2.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
imagefootprint_plugin
1.1
processing_saga_nextgen
1.0.0
qmapshaper
0.8.2
MetaSearch
0.3.6
processing
2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@CWGwaltney, the task is actually performed by the GDAL library. It looks like you have set the "Output data type" parameter to "Float32", while AFAIK and typical RBG raster image data type is "Byte". Have you tried to set to "Output data type" parameter to "Byte"?
May you provide the raster layers and the exact algorithm's parameters used in order to replicate the issue?

**Comment by CWGwaltney** [comment]
Thanks! This was the solution... I didnot understand this... I think the Raster DEM is supposed to be float 32 but i didnt not know the RGB was Byte..but it makes total sence now!
