### ISSUE TITLE
raster reproject (warp) - unfinished process

### ISSUE THREAD

**Issue by aum7** [qgis/QGIS#59574]
## User Feedback

98 .xyz files , slo system epsg:10245
menu : raster > ... > reproject (warp)
batch reproject ...
target epsg:4236 gw? 84
run

progress bar reached 69 % then stopped

clicking on [x] of the process (bottom bar popup) did nothing

i started another reproject run
reached 16 % then froze

2 frozen processes were 'running' - cold room it was lol

then crash 

win11 about a week old installation (aka fresh install)
16 gb ram
r7 4000 series (2019)
nv2060 6 gb graphics
asus laptop

also ui keeps resetting - i have settings on bigger font, keeps resetting (mid-use) to default nano font size - a pain on 15" screen

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Current thread 0x00001364 (most recent call first):
  <no Python frame>
```

**Stack Trace**

```

QEventDispatcherWin32::staticMetaObject :
QgsTaskManager::cancelAll :
QgisApp::fileExit :
QWidget::event :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QWidgetPrivate::close_helper :
QSizePolicy::QSizePolicy :
QApplicationPrivate::notify_helper :
QApplication::notify :
QgsApplication::notify :
QCoreApplication::notifyInternal2 :
QGuiApplicationPrivate::processCloseEvent :
QWindowSystemInterface::sendWindowSystemEvents :
QEventDispatcherWin32::processEvents :
qt_plugin_query_metadata :
QEventLoop::exec :
QCoreApplication::exec :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.40.0-Bratislava
QGIS code revision: b56115d874
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.3
Running against GDAL: 3.9.3

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.26100

### Steps to reproduce the issue

see above

### Versions

**QGIS Info**
QGIS Version: 3.40.0-Bratislava
QGIS code revision: b56115d874
Compiled against Qt: 5.15.13
Running against Qt: 5.15.13
Compiled against GDAL: 3.9.3
Running against GDAL: 3.9.3

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [x] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Duplicates https://github.com/qgis/QGIS/issues/53806 ?

**Comment by aum7** [comment]
yep, looks much alike duplicate
still present in 3.40 bratislava
