### ISSUE TITLE
Duplicated menus when localization changes (possible regression?)

### ISSUE THREAD

**Issue by arielsbecker** [qgis/QGIS#59583]
### What is the bug or the crash?

Vector and Raster top menus (mVectorMenu and mRasterMenu) are empty if a non-US-En interface translation was being used then changed for another one. New vector and raster menus also appears, in the selected interface language, but are not recognized as mVectorMenu or mRasterMenu objects.

### Steps to reproduce the issue

1. Have a localized version of your OS (in my case it's Ubuntu with Spanish/Argentina as my main language).
2. Install QGIS
3. Use QGIS
4. Change OS localization
5. Open QGIS
6. You'll probably see an empty mVectorMenu object, an empty mRasterMenu object, and two new Vector and Raster menus (not recognized as mVectorMenu or mRasterMenu objects by QGIS) with localized names (in my case, Vectores and Ráster).

Workaround to fix it:

1. Create a new user profile.
2. Menus (and everything else) will be reset to the original state. No duplicates menus anymore.

This alternative seems to work sometimes too (this is why I think it's probably a regression of #23262):

1. Disable Processing core plug-in.
2. Close QGIS.
3. Open QGIS again.
4. Re-enable Processing.
5. Vector and Raster menus are now unified, as intended.

### Versions

QGIS version | 3.22.4-Białowieża | QGIS code branch | Release 3.22
-- | -- | -- | --
Qt version | 5.15.3
Python version | 3.10.3
GDAL/OGR version | 3.4.1
PROJ version | 8.2.1
EPSG Registry database version | v10.041 (2021-12-03)
GEOS version | 3.10.2-CAPI-1.16.0
SQLite version | 3.37.2
PostgreSQL client version | 14.2 (Ubuntu 14.2-1)
SpatiaLite version | 5.0.1
QWT version | 6.1.4
QScintilla2 version | 2.11.6
OS version | Ubuntu 22.04.3 LTS

Active Python plugins |  version
-- | -- 
sagaprovider | 2.12.99
grassprovider | 2.12.99
MetaSearch | 0.3.5
db_manager | 0.1.20
processing | 2.12.99

QGIS version: 3.22.4-Białowieża  
QGIS code branch: [Release 3.22](https://github.com/qgis/QGIS/tree/release-3_22)   
Qt version:  5.15.3  
Python version: 3.10.3   
GDAL/OGR version: 3.4.1  
PROJ version: 8.2.1  
EPSG Registry database version: v10.041 (2021-12-03)  
GEOS version: 3.10.2-CAPI-1.16.0  
SQLite version: 3.37.2  
PostgreSQL client version: 14.2 (Ubuntu 14.2-1)  
SpatiaLite version: 5.0.1  
QWT version: 6.1.4  
QScintilla2 version: 2.11.6  
OS version: Ubuntu 22.04.3 LTS  

Active Python plugins
sagaprovider: 2.12.99  
grassprovider: 2.12.99   
MetaSearch: 0.3.5  
db_manager:  0.1.20
processing:  2.12.99

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

OS: Ubuntu 22.04.3 LTS x86_64 
Kernel: 6.8.0-49-generic
Localization used until this bug occured: Spanish/Argentina
Localization changed to: English/US

**Comment by agiudiceandrea** [comment]
@arielsbecker, thanks for reporting. Unfortunately, QGIS 3.22 is no longer supported. Please try if the issue does occur also using a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).
