### ISSUE TITLE
Expressions export not working

### ISSUE THREAD

**Issue by Voghera** [qgis/QGIS#59678]
### What is the bug or the crash?

How detailed below, if I write a valid Expression I cannot correctly export it and import does not work. 

### Steps to reproduce the issue

Go to "Expression Based Preview"
In "Expression" write a valid expression formula
Press "Export User Expressions" and save the Json file in a directory 
The Json file is unusable because does not contain the expression:
For instance:
{
    "author": "Giovanni Talpone",
    "exported_at": "2024-12-01T12:48:14",
    "expressions": [
    ],
    "qgis_version": "3.34.13-Prizren"
}
In "Expressin" press "Import User Expressions"
Nothing happens.

### Versions

QGIS version
3.34.13-Prizren
QGIS code revision
222b5995
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.9.3
PROJ version
9.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

Active Python plugins
geocsv-main
1.0
gna
1.3.0
GpxSegmentImporter
3.2
kmltools
3.2.2
latlontools
3.7.2
mgrs
3.1.1
naficp
1.0
OSMDownloader
1.0.3
Qgis2threejs
2.8
QuickOSM
2.2.3
quick_map_services
0.19.36
db_manager
0.1.20
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
If there is no "user expression" stored, then the "Export User Expressions" action will not export any "user expression".
You need to [add the current expression](https://docs.qgis.org/3.34/en/docs/user_manual/expressions/expression.html#saving-expressions) to the "user expressions" before using the "Export User Expressions" action if you want to export the current expression.
