### ISSUE TITLE
Error when adding a STAC server

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#59693]
### What is the bug or the crash?

I am trying to add https://brazildatacube.dpi.inpe.br/stac/ to QGIS and I get JSON parse error:

### Steps to reproduce the issue

Open QGIS
In STAC connection under Browser Panel and add https://brazildatacube.dpi.inpe.br/stac/
When you expand the connection, it shows Error parsing JSON.

### Versions

3.40 and master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
The linked catalog is _stac_version 0.9.0_, while minimum required is 1.0.0
We should probably report _incompatible version_ instead of _error parsing_
