### ISSUE TITLE
Conda enviroment is failing for main 3.40.1

### ISSUE THREAD

**Issue by MarcelGeo** [qgis/QGIS#59746]
### What is the bug or the crash?

it's not possible to import something from qgis.core in conda environment.

Following error is here:
```
$ python
Python 3.12.7 | packaged by conda-forge | (main, Oct  4 2024, 16:05:46) [GCC 13.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from qgis.core import QgsProject
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/marcelkocisek/miniconda3/envs/qgis-ltr/share/qgis/python/qgis/core/__init__.py", line 28, in <module>
    from qgis._core import *
ImportError:  /miniconda3/envs/qgis-ltr/share/qgis/python/qgis/../../../../lib/./libgdal.so.35: undefined symbol: sqlite3_total_changes64
>>> 
```

### Steps to reproduce the issue

```bash
conda install conda-forge::qgis
```

### Versions

3.40.1 conda forge

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nicogodet** [comment]
Should be reported here: https://github.com/conda-forge/qgis-feedstock/issues
