### ISSUE TITLE
Wen building source code project 'qgis_core', there are C2712/C2713 errors.

### ISSUE THREAD

**Issue by wong-hao** [qgis/QGIS#59768]
### What is the bug or the crash?

Wen building source code 'activate' function in qgsopenclutils.cpp file of qgis_core project with Microsoft Visual Studio 2022, there there are C2712/C2713 errors.
![image](https://github.com/user-attachments/assets/1c3563f5-a6c0-40ae-8d7c-c5d4fce76f0b)

### Steps to reproduce the issue

1. go to the source code.
2. right click project qgis_core and click 'build'.

### Versions

3.41

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context
![image](https://github.com/user-attachments/assets/4e6e35fb-d210-40c9-b44f-50e02471e87e)
_No response_

**Comment by wong-hao** [comment]
> @wong-hao Can you give a try at #59784 ?

![image](https://github.com/user-attachments/assets/56c8ba1b-d907-4d12-b455-9f2b66ca591f)

Is this a unique issue on my end? Does it seem like a new error has occurred?

**Comment by rouault** [comment]
> Is this a unique issue on my end?

probably not. I'm not developing on Windows, and our CI doesn't trigger that code path. Anyway hopefully should be fixed now per https://github.com/qgis/QGIS/pull/59789

**Comment by wong-hao** [comment]
> > Is this a unique issue on my end?
> 
> probably not. I'm not developing on Windows, and our CI doesn't trigger that code path. Anyway hopefully should be fixed now per #59789

Finally, no error!
