### ISSUE TITLE
Crash upon start-up of QGIS

### ISSUE THREAD

**Issue by lsbbaker** [qgis/QGIS#59765]
## User Feedback

Don't seem to be able to open it up at all. It just crashes upon start-up of  application.

## Report Details

**Crash ID**: [d754324f5658a9821c7807fcb96eb7b5426513f2](https://github.com/qgis/QGIS/search?q=d754324f5658a9821c7807fcb96eb7b5426513f2&type=Issues)

**Stack Trace**

```

IcdPresentBuffers :
IcdPresentBuffers :
IcdPresentBuffers :
DrvSetCallbackProcs :
DrvSetCallbackProcs :
pgldrvLoadAndAllocDriverInfo :
LoadAvailableDrivers :
_DescribePrimaryPixelFormat :
wglNumHardwareFormats :
wglDescribePixelFormat :
wglChoosePixelFormat :
ChoosePixelFormat :
QOpenGLContext::create :
QGuiApplicationPrivate::init :
QApplicationPrivate::init :
QApplication::QApplication :
QgsApplication::QgsApplication :
main :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.36.0-Maidenhead
QGIS code revision: 09951dc0
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.8.4
Running against GDAL: 3.8.4

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.22631

### Steps to reproduce the issue

It crashed upon starting up the application.

### Versions

3.36.0

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@lsbbaker, QGIS 3.36 is no longer supported. Please try if the issue occurs also running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS user profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
