### ISSUE TITLE
In QGIS 3.34 Python Console, pyarrow cannot be imported or used by other packages (but comes with QGIS by default).

### ISSUE THREAD

**Issue by Katsdog** [qgis/QGIS#59776]
### What is the bug or the crash?

In QGIS python console:

```
import pyarrow
ImportError: DLL load failed while importing lib: The specified procedure could not be found.

_
import geopandas as gpd
gdf=gpd.read_feather(r'example.feather')
ImportError: Missing optional dependency 'pyarrow.feather'. pyarrow is required for Feather support.  "
"Use pip or conda to install pyarrow.feather.

```

This issue occurs despite pyarrow being successfully installed and functional in the OSGeo4W terminal. The problem seems related to how qgis-ltr-bin.exe handles the Python environment, as the sys.executable (in the QGIS python console) points to qgis-ltr-bin.exe instead of python.exe.

I believe that in the geopandas call,  pandas is trying to import pyarrow for but is unable to.

[feather_example.zip](https://github.com/user-attachments/files/18041928/feather_example.zip)

### Steps to reproduce the issue

- Install QGIS 3.34
- In QGIS python console:
  1. import geopandas as gpd
      gdf=gpd.read_feather(r'example.feather')
  2. import pyarrow

### Versions

QGIS 3.34

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

My goal is to read feather files via Geopandas from python console. 
It does not make sese that this works for shapefiles but does not currently work for this other formats readable by pandas/geopandas.

This is what I've tried:

Verified pyarrow Installation:
•	Confirmed that pyarrow works in the OSGeo4W shell but fails in the QGIS Python console.
Checked Python Paths:
•	Verified sys.executable and sys.path in the QGIS Python console, ensuring the correct Python and site-packages directories were included.
Reinstalled Dependencies:
•	Reinstalled pyarrow with specific versions (e.g., 12.0.1, 15.0.2, 18.1.0) to test compatibility.
•	Reinstalled geopandas and its dependencies.
Added Missing DLLs:
•	Copied pyarrow DLL files from its installation directory to the QGIS bin folder.
•	Temporarily added the pyarrow directory to the PATH environment variable.
Tried Workarounds for QGIS Python Configuration:
•	Manually added the pyarrow path to sys.path in the QGIS Python console.
•	Attempted to force QGIS to use python.exe instead of qgis-ltr-bin.exe.

**Comment by agiudiceandrea** [comment]
@Katsdog, please indicate the exact QGIS version installed and the `python3-pyarrow` and `arrow-cpp` OSGeo4W packages' version installed.
I cannot replicate the reported issue using the latest available currently supported QGIS versions installed via OSGeo4W.
@jef-n: it seems weird to me that the latest python3-pyarrow package version is `0.0.0-1`

**Comment by jef-n** [comment]
On Fri, 06. Dec 2024 at 16:08:00 -0800, Andrea Giudiceandrea wrote:
> @Katsdog, please indicate the exact QGIS version installed and the
> `python3-pyarrow` and `arrow-cpp` OSGeo4W packages' version installed.

> I cannot replicate the reported issue using the latest available currently
> supported QGIS versions installed via OSGeo4W.

> @jef-n: it seems weird to me that the latest python3-pyarrow package version
> is `0.0.0-1`

Yes, the newer version of python3-pyarrow from arrow-cpp didn't pickup the
version number of arrow anymore and defaulted to 0.0.0 instead - which
obviously isn't higher as the previous version number - so the update of
pyarrow wasn't triggered and the previous one doesn't work with the new
arrow-cpp package.  The quick fix was to declare 0.0.0-1 as the latest version.

The actual fix will be to update arrow-cpp (along with PROJ, GDAL, Python and
Qt6).


Jürgen

-- 
Jürgen E. Fischer           norBIT GmbH             Tel. +49-4931-918175-31
Dipl.-Inf. (FH)             Rheinstraße 13          Fax. +49-4931-918175-50
Software Engineer           D-26506 Norden            https://www.norbit.de
QGIS release manager (PSC)  Germany                 IRC: jef on Libera|OFTC

norBIT Gesellschaft fuer Unternehmensberatung und Informationssysteme mbH
Rheinstrasse 13, 26506 Norden
GF: Juergen Fischer, Nils Kutscher HR: Amtsgericht Aurich HRB 100827
Datenschutzerklaerung: https://www.norbit.de/83/

**Comment by agiudiceandrea** [comment]
@jef-n, anyway it looks like there is actually an issue with pyarrow: using the latest QGIS 3.41.0-Master (qgis-dev-3.41.0-857-da86bc17a6-1, arrow-cpp-17.0.0-1, python3-pyarrow-0.0.0-1, python3-geopandas-1.0.0-1), while there is no `ImportError` after importing pyarrow, pyarrow itself doesn't work and makes also geopandas not working:

```python
import pyarrow as pa
days = pa.array([1, 12, 17, 23, 28], type=pa.int8())
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "pyarrow\\array.pxi", line 273, in pyarrow.lib.array
  File "pyarrow\\array.pxi", line 55, in pyarrow.lib._is_array_like
  File "pyarrow\\pandas-shim.pxi", line 124, in pyarrow.lib._PandasAPIShim._have_pandas_internal
  File "pyarrow\\pandas-shim.pxi", line 103, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow\\pandas-shim.pxi", line 106, in pyarrow.lib._PandasAPIShim._check_import
  File "pyarrow\\pandas-shim.pxi", line 50, in pyarrow.lib._PandasAPIShim._import_pandas
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\compat\pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\util\version\__init__.py", line 341, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

```
import geopandas as gpd
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\geopandas\__init__.py", line 3, in <module>
    from geopandas.geoseries import GeoSeries
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\geopandas\geoseries.py", line 9, in <module>
    import pandas as pd
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\__init__.py", line 26, in <module>
    from pandas.compat import (
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\compat\__init__.py", line 27, in <module>
    from pandas.compat.pyarrow import (
  File "C:\OS022F~1/apps/qgis-dev/./python\qgis\utils.py", line 966, in _import
    mod = _builtin_import(name, globals, locals, fromlist, level)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\compat\pyarrow.py", line 10, in <module>
    _palv = Version(Version(pa.__version__).base_version)
                    ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\OS022F~1\apps\Python312\Lib\site-packages\pandas\util\version\__init__.py", line 341, in __init__
    match = self._regex.search(version)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: expected string or bytes-like object, got 'NoneType'
```

geopandas can be imported without issue if python3-pyarrow is not installed.

**Comment by Katsdog** [comment]
@agiudiceandrea, please see below.

Can you please try the below on the .feather file I shared? I believe this best replicates the issue I'm having. Thank you
```
import geopandas as gpd
gdf=gpd.read_feather(r'example.feather')
```

QGIS Version: 3.34.13-Prizren
pyarrow version: 18.1.0
arrow-cpp is not installed. 

In QGIS python console  ` pkg_resources.get_distribution("arrow-cpp").version`
> File "C:\PROGRA~1\QGIS33~1.13\apps\Python312\Lib\site-packages\pkg_resources\__init__.py", line 839, in _resolve_dist
>     raise DistributionNotFound(req, requirers)
> pkg_resources.DistributionNotFound: The 'arrow-cpp' distribution was not found and is required by the application


In OSGeo terminal: `pip show pyarrow`

> C:\Program Files\QGIS 3.34.13>pip show pyarrow
> Name: pyarrow
> Version: 18.1.0
> Summary: Python library for Apache Arrow
> Home-page: https://arrow.apache.org/
> Author:
> Author-email:
> License: Apache Software License
> Location: C:\Users\Dkats\AppData\Roaming\Python\Python312\site-packages
> Requires:
> Required-by:

**Comment by agiudiceandrea** [comment]
@Katsdog if you have installed QGIS LTR 3.34.13 using either the stand-alone all-in-one .msi OSGeo4W installer or the .exe OSGeo4W network installer, then the OSGeo4W `arrow-cpp` 17.0.0-1 package is actually automatically installed since it is required by the GDAL/OGR library. Since on OSGeo4W there is no pyarrow version 18.1.0 available (the latest are 15.0.0-1 and 0.0.0-1), then I guess you are not using the pyarrow Python module that comes with QGIS by default.

**Comment by agiudiceandrea** [comment]
Provided that the "arrow-cpp" version 17.0.0-1 and "python3-pyarrow" version 0.0.0-1 QSGeo4W's packages are installed (if "python3-pyarrow" version 15.0.2-1 QSGeo4W's packages is installed instead of version 0.0.0-1, then upgrading the "python3-pyarrow" OSGeo4W's package to version 0.0.0-1 is needed), a simple workaround, which also makes both geopandas and pandas work well when python3-pyarrow 0.0.0-1 is installed, is to change line 59 in `apps\Python312\Lib\site-packages\pyarrow\__init__.py` from pyarrow.__version__ = None to pyarrow.__version__ = '17.0.0'.

**Comment by Katsdog** [comment]
@agiudiceandrea  Thank you for looking into this. The difference in the pyarrow Python module is due to my attempts to pip reinstall pyarrow in response to the below message.

Just so I understand correctly- in your configuration you do not get the below error? 
If so, I'll reinstall QGIS and follow your instructions.

> import geopandas as gpd
> gdf=gpd.read_feather(r'example.feather')
> ImportError: Missing optional dependency 'pyarrow.feather'. pyarrow is required for Feather support.  "
> "Use pip or conda to install pyarrow.feather.

**Comment by agiudiceandrea** [comment]
> Just so I understand correctly- in your configuration you do not get the below error?

I don't get any error after executing `gdf=gpd.read_feather('C:/test/feather_example.feather')` and `print(gdf)` outputs:
```
                    ParcelLoc                                            geometry
0.0    32.9425944 -96.8967582   POLYGON ((696610.027 3646906.323, 696612.759 3...
1.0    32.9424208 -96.8846587   POLYGON ((697774.694 3646900.486, 697775.1 364...
2.0    32.9420312 -96.8798399   POLYGON ((698190.657 3646874.243, 698218.094 3...
3.0    32.9420592 -96.8871974   POLYGON ((697506.958 3646865.233, 697525.248 3...
4.0    32.9420327 -96.8822457   POLYGON ((697963.639 3646867.382, 697966.38 36...
                                                                      ...
96.0   32.9509217 -96.7593143   POLYGON ((709463.173 3648055.843, 709444.119 3...
97.0   32.9505804 -96.7419796   POLYGON ((711084.856 3648048.812, 711065.527 3...
98.0   32.9505825 -96.7421863   POLYGON ((711065.527 3648048.627, 711046.188 3...
99.0   32.9506575 -96.7469136   POLYGON ((710625.447 3648091.539, 710626.431 3...
100.0  32.9507785 -96.7667459   POLYGON ((708787.834 3648076.638, 708789.472 3...

[101 rows x 16 columns]
```

**Comment by agiudiceandrea** [comment]
I'm closing this issue report since it is a downstream issue not related to the QGIS source code.

**Comment by agiudiceandrea** [comment]
@Katsdog, the issue has been fixed. The updated python3-pyarrow version 17.0.0-1 OSGeo4W package, besides the arrow-cpp version 17.0.0-2 OSGeo4W package, contains the fix and makes pyarrow, pandas and geopandas work as expeted.

**Comment by Katsdog** [comment]
@agiudiceandrea Thank you!
