### ISSUE TITLE
Raster band as a temporal range does not work properly

### ISSUE THREAD

**Issue by saberraz** [qgis/QGIS#59777]
### What is the bug or the crash?

I have a raster with 7 bands:

1. 2023-06-04 00:00:00
2. 2023-06-06 00:00:00  
3. 2023-06-09 00:00:00
4. 2023-06-11 00:00:00
5. 2023-06-14 00:00:00
6. 2023-06-16 00:00:00
7. 2023-06-24 00:00:00

I have set them up as band for each time step:
![image](https://github.com/user-attachments/assets/1305e6ad-50c3-4dd6-b0d0-4797777c3b2f)

But when I go to the temporal controller and move the time slider it does not update the image.
[Archive.zip](https://github.com/user-attachments/files/18043151/Archive.zip)

I have attached the data + QGIS project.

### Steps to reproduce the issue

See the report.

### Versions

Master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by saberraz** [comment]
CC @VictorVerhaert

**Comment by nyalldawson** [comment]
The issue is that you're using a multi-band renderer, so there's no way to dynamically just change the renderer band as the time changes.

I've fixed the GUI to reflect this in https://github.com/qgis/QGIS/pull/59815

**Comment by saberraz** [comment]
Thanks @nyalldawson!
