### ISSUE TITLE
Remove "Optional" flag from Processing boolean input parameters

### ISSUE THREAD

**Issue by DelazJ** [qgis/QGIS#59794]
### What is the bug or the crash?

Some algorithms\* show an `[Optional]` flag next to boolean parameters while others don't. Before I try to create a PR removing the flag, I'd like to know if there is a reason behind this and what an optional boolean means.

\* The ones I found in [the docs](https://github.com/qgis/QGIS-Documentation/pull/9458): Export atlas layout as ..., Extract labels, Generate XYZ tiles (Directory), (ST-)DBSCAN Clustering, Points to path, Reproject layer, Polygonize and GDAL Raster to vector.

### Steps to reproduce the issue

Open one of the abovementioned algs and you'll find a checkob element with `[optional]` at the end

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.41.0-Master</td></tr><tr><td>QGIS code revision</td><td><a href="https://github.com/qgis/QGIS/commit/3c143d501a8">3c143d501a8</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.8</td></tr><tr><td>Python version</td><td>3.11.2</td></tr><tr><td>GDAL/OGR version</td><td>3.6.2</td></tr><tr><td>PROJ version</td><td>9.1.1</td></tr><tr><td>EPSG Registry database version</td><td>v10.076 (2022-08-31)</td></tr><tr><td>GEOS version</td><td>3.11.1-CAPI-1.17.1</td></tr><tr><td>SQLite version</td><td>3.40.1</td></tr><tr><td>PDAL version</td><td>2.6.0</td></tr><tr><td>PostgreSQL client version</td><td>15.10 (Debian 15.10-0+deb12u1)</td></tr><tr><td>SpatiaLite version</td><td>5.0.1</td></td></tr><tr><td>QWT version</td><td>6.1.4</td></tr><tr><td>QScintilla2 version</td><td>2.13.3</td></tr><tr><td>OS version</td><td>Debian GNU/Linux 12 (bookworm)</td></tr><tr><td colspan="2"><i>This copy of QGIS writes debugging output.</i></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr><tr><td>processing</td><td>2.12.99</td></tr></table>

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
When adding parameters to an existing algorithm, those parameters need to be marked as optional, so that existing scripts and models don't break. In the GUI then, `[optional]` gets automatically added to the label.
I guess we could indeed skip showing `[optional]` for bools

**Comment by nyalldawson** [comment]
Actually it's almost entirely redundant -- if a parameter value isn't specified, it automatically takes the default value.

So the ONLY reason for an optional Boolean parameter is when there's three states: true, false and not set/null. I'm not sure if any algorithms actually require that right now.
