### ISSUE TITLE
Buffered Transaction groups - Deleting layer causes instability

### ISSUE THREAD

**Issue by fruitbaticus** [qgis/QGIS#59828]
### What is the bug or the crash?

When using "Buffered Transaction Groups", deleting a vector layer causes instability. When trying to enter edit mode on another layer it will hard crash QGIS.

### Steps to reproduce the issue

1. Add at least 2 vector layers to QGIS (don't even have to contain geometry)
2. In Properties -> Data Sources change **Transaction Mode** to **Buffered Transaction Groups**
3. Delete one of the vector layers
4. Select a remaining vector layer
5. Try to enter edit mode

For me this produces a hard crash without even the error handler appearing.

I managed to get VS attached to the process and get:
```
Exception thrown: read access violation.
layer->**** was 0xFFFFFFFFFFFFFF2F.
```
With this call stack:
```
>	qgis_core.dll!QgsVectorLayerEditBufferGroup::modifiedLayers() Line 53	C++
 	qgis_app.dll!QgisApp::toggleEditingVectorLayer(QgsVectorLayer * vlayer, bool allowCancel) Line 10658	C++
 	qgis_app.dll!QgisApp::toggleEditing(QgsMapLayer * layer, bool allowCancel) Line 10601	C++
 	qgis_app.dll!QgisApp::toggleEditing() Line 10576	C++
 	qgis_app.dll!QgisApp::createActions::__l2::<lambda_40>::operator()() Line 3054	C++
 	qgis_app.dll!QtPrivate::FunctorCall<QtPrivate::IndexesList<>,QtPrivate::List<>,void,`QgisApp::createActions'::`2'::<lambda_40>>::call(QgisApp::createActions::__l2::<lambda_40> & f, void * * arg) Line 146	C++
 	qgis_app.dll!QtPrivate::Functor<`QgisApp::createActions'::`2'::<lambda_40>,0>::call<QtPrivate::List<>,void>(QgisApp::createActions::__l2::<lambda_40> & f, void * __formal, void * * arg) Line 257	C++
 	qgis_app.dll!QtPrivate::QFunctorSlotObject<`QgisApp::createActions'::`2'::<lambda_40>,0,QtPrivate::List<>,void>::impl(int which, QtPrivate::QSlotObjectBase * this_, QObject * r, void * * a, bool * ret) Line 449	C++
 	Qt5Core.dll!00007ffb0c0f4193()	Unknown
 	Qt5Widgets.dll!00007ffb346b5daf()	Unknown
 	Qt5Widgets.dll!00007ffb3478f0fd()	Unknown
 	Qt5Widgets.dll!00007ffb347900f3()	Unknown
 	Qt5Widgets.dll!00007ffb34868f9f()	Unknown
 	Qt5Widgets.dll!00007ffb346e797d()	Unknown
 	Qt5Widgets.dll!00007ffb346c4a71()	Unknown
 	Qt5Widgets.dll!00007ffb346c293e()	Unknown
 	qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 628	C++
 	Qt5Core.dll!00007ffb0c0d505b()	Unknown
 	Qt5Widgets.dll!00007ffb346c5d91()	Unknown
 	Qt5Widgets.dll!00007ffb34710064()	Unknown
 	Qt5Widgets.dll!00007ffb3470df34()	Unknown
 	Qt5Widgets.dll!00007ffb346c4a71()	Unknown
 	Qt5Widgets.dll!00007ffb346c3b1a()	Unknown
 	qgis_core.dll!QgsApplication::notify(QObject * receiver, QEvent * event) Line 628	C++
 	Qt5Core.dll!00007ffb0c0d505b()	Unknown
 	Qt5Gui.dll!00007ffb205d5428()	Unknown
 	Qt5Gui.dll!00007ffb205bf044()	Unknown
 	Qt5Core.dll!00007ffb0c11dae1()	Unknown
 	qwindows.dll!00007ffaf84231d9()	Unknown
 	Qt5Core.dll!00007ffb0c0d148d()	Unknown
 	Qt5Core.dll!00007ffb0c0d4095()	Unknown
 	qgis_app.dll!main(int argc, char * * argv) Line 1828	C++
 	qgis-dev-bin.exe!WinMain(HINSTANCE__ * __formal, HINSTANCE__ * __formal, char * __formal, int __formal) Line 215	C++
 	[Inline Frame] qgis-dev-bin.exe!invoke_main() Line 102	C++
 	qgis-dev-bin.exe!__scrt_common_main_seh() Line 288	C++
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

### Versions

QGIS version
3.41.0-Master
QGIS code revision
d1de2574de
 
Libraries
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.11.0dev-d511807003
PROJ version
9.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
16.2
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009
This copy of QGIS writes debugging output.
 
Active Python plugins
db_manager
0.1.20
grassprovider
2.12.99
MetaSearch
0.3.6
processing
2.12.99

But also every older version I've tried this experiment with.

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

Note that I have seen this exception be thrown in different places in the code, but always while Q is trying to access a layer (that has presumably been deleted)

We use Buffered Transaction groups a lot and see a fair few errors in this class (look like memory access violations). This is the first one that I've been able to track right down to a specific cause and event, but there may be more issues around dealing with layers while in buffered transaction group mode.

**Comment by agiudiceandrea** [comment]
Hi @domi4484, may you have a look a this issue report?
