### ISSUE TITLE
Label Features display too Slow

### ISSUE THREAD

**Issue by sivansakthi** [qgis/QGIS#59849]
### What is the bug or the crash?

If I added the label to features take too much Time to appear on the screen. why? Please see the attached Video.
If i already added the label then change it then reflect on the screen. 

https://github.com/user-attachments/assets/cd6fabdb-c3f4-4438-864c-b9024ef4b89b

### Steps to reproduce the issue

Please improve the label reflect on the screen fast.

### Versions

QGIS version
3.40.0-Bratislava
QGIS code revision
b56115d874
 
Libraries
Qt version
5.15.13
Python version
3.12.7
GDAL/OGR version
3.9.3
PROJ version
9.5.0
EPSG Registry database version
v11.016 (2024-08-31)
GEOS version
3.13.0-CAPI-1.19.0
SQLite version
3.46.1
PDAL version
2.8.1
PostgreSQL client version
unknown
SpatiaLite version
5.1.0
QWT version
6.3.0
QScintilla2 version
2.14.1
OS version
Windows 10 Version 2009

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [X] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by nyalldawson** [comment]
Please try with a clean user profile, no plugins installed

**Comment by sivansakthi** [comment]
Hello nyalldawson,
 I did before still same issues are present it.

**Comment by nyalldawson** [comment]
In your screencast you have many plugins installed -- can you take a screencast with a clean profile?

**Comment by sivansakthi** [comment]
I looking which plugin is locking the label display slow down. As per all the plugin clear then add the label appears very fast. For last 2 week I sick that's why I could not be able to reply as soon.
