### ISSUE TITLE
QGIS ENDS UNEXPECTEDLY

### ISSUE THREAD

**Issue by Azm-Mev** [qgis/QGIS#59912]
## User Feedback

have no idea

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00001808 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QCoreApplication::translate :
QCoreApplication::translate :
QCoreApplication::translate :
QRegularExpressionMatchIterator::regularExpression :
QRegularExpressionMatch::capturedView :
QRegularExpression::match :
QgsProjectStorage::QgsProjectStorage :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsOgrProviderUtils::wildcards :
QgsSQLiteExpressionCompiler::operator= :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayerFeatureSource::getFeatures :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

## User Feedback

have no idea

## Report Details

**Python Stack Trace**
```
Windows fatal exception: access violation

Thread 0x00001808 (most recent call first):
<no Python frame>
```

**Stack Trace**

```

QCoreApplication::translate :
QCoreApplication::translate :
QCoreApplication::translate :
QRegularExpressionMatchIterator::regularExpression :
QRegularExpressionMatch::capturedView :
QRegularExpression::match :
QgsProjectStorage::QgsProjectStorage :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsSQLiteExpressionCompiler::operator= :
QgsOgrProviderUtils::wildcards :
QgsSQLiteExpressionCompiler::operator= :
QgsVectorLayerFeatureIterator::QgsVectorLayerFeatureIterator :
QgsVectorLayerFeatureSource::getFeatures :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsVectorLayerProfileResults::visitFeaturesInRange :
QgsMapRendererParallelJob::renderLayerStatic :
QgsProfilePlotRenderer::replaceSourceInternal :
QgsMapRendererParallelJob::renderingFinished :
QgsMapRendererParallelJob::takeLabelingResults :
QtConcurrent::ThreadEngineBase::run :
QThreadPoolPrivate::reset :
QThread::start :
BaseThreadInitThunk :
RtlUserThreadStart :
```

**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

**System Info**
CPU Type: x86_64
Kernel Type: winnt
Kernel Version: 10.0.17763

### Versions

**QGIS Info**
QGIS Version: 3.28.9-Firenze
QGIS code revision: 66f4d63ad4
Compiled against Qt: 5.15.3
Running against Qt: 5.15.3
Compiled against GDAL: 3.7.1
Running against GDAL: 3.7.1

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
@Azm-Mev QGIS 3.28 is no longer supported. Please try if the issue occurs running a currently supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule) and using a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles).
If it does, please provide step-by-step instructions and sample project and layer in order to replicate the issue.
