### ISSUE TITLE
WFS loading features very slow from 3.34 for Win

### ISSUE THREAD

**Issue by francescomarucci** [qgis/QGIS#60008]
### What is the bug or the crash?

dear all,
I'm verifying very slow loading features from a WFS service in QGIS from the 3.34.x & 3.40.2 versions in Win10, since in debian 3.34.x or in QGIS 3.22.x & 3.28.x in Win the same service is very fast.

for example, this is the log for QGIS from the 3.34.x & 3.40.2 versions in Win 10 installed from osgeo4w installer (the request takes 114 seconds):

{
  "Bytes Received": 19874406,
  "Bytes Total": 19874406,
  "Cache (controllo)": "Carica sempre dalla rete, ignora la cache",
  "Cache (salva)": "Il risultato non può essere memorizzato in cache",
  "ID": "src\\providers\\wfs\\qgsbasenetworkrequest.cpp:214 (QgsBaseNetworkRequest::sendGET)",
  "In risposta": {
    "Cache (risultato)": "Leggi dalla rete",
    "Stato": "200",
    "Titoli": {
      "Connection": "Keep-Alive",
      "Content-Encoding": "gzip",
      "Content-Type": "text/xml; subtype=gml/3.1.1; charset=UTF-8",
      "Date": "Tue, 24 Dec 2024 10:01:12 GMT",
      "Keep-Alive": "timeout=5, max=100",
      "Server": "Apache/2.2.22 (Debian)",
      "Strict-Transport-Security": "max-age=15768000",
      "Transfer-Encoding": "chunked",
      "Vary": "Accept-Encoding"
    }
  },
  "Iniziatore": "QgsBaseNetworkRequest",
  "Interrogazione": {
    "REQUEST": "GetFeature",
    "SERVICE": "WFS",
    "SRSNAME": "urn:ogc:def:crs:EPSG::4326",
    "TYPENAME": "bt_v_complessi_pt",
    "VERSION": "1.1.0"
  },
  "Operazione": "GET",
  "Replies": 7,
  "Thread": "0x0000017f98c05e20",
  "Titoli": {
    "User-Agent": "Mozilla/5.0 QGIS/33414/Windows 10 Version 2009"
  },
  "Total time (ms)": 114035,
  "URL": "https://www.patrimonioculturale-er.it/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=bt_v_complessi_pt&SRSNAME=urn:ogc:def:crs:EPSG::4326"
}

and this is the log from QGIS 3.22.07 in Win10 installed from the QGIS installer (the request takes 2.7 seconds):

{
  "Bytes Received": 19874406,
  "Bytes Total": 19874406,
  "Cache (controllo)": "Carica sempre dalla rete, ignora la cache",
  "Cache (salva)": "Il risultato non può essere memorizzato in cache",
  "ID": "src\\providers\\wfs\\qgsbasenetworkrequest.cpp:141 (QgsBaseNetworkRequest::sendGET)",
  "In risposta": {
    "Cache (risultato)": "Leggi dalla rete",
    "Stato": "200",
    "Titoli": {
      "Connection": "Keep-Alive",
      "Content-Encoding": "gzip",
      "Content-Type": "text/xml; subtype=gml/3.1.1; charset=UTF-8",
      "Date": "Tue, 24 Dec 2024 10:06:23 GMT",
      "Keep-Alive": "timeout=5, max=100",
      "Server": "Apache/2.2.22 (Debian)",
      "Strict-Transport-Security": "max-age=15768000",
      "Transfer-Encoding": "chunked",
      "Vary": "Accept-Encoding"
    }
  },
  "Iniziatore": "QgsBaseNetworkRequest",
  "Interrogazione": {
    "REQUEST": "GetFeature",
    "SERVICE": "WFS",
    "SRSNAME": "urn:ogc:def:crs:EPSG::4326",
    "TYPENAME": "bt_v_complessi_pt",
    "VERSION": "1.1.0"
  },
  "Operazione": "GET",
  "Replies": 6,
  "Thread": "0x0000017c8310cae0",
  "Titoli": {
    "User-Agent": "Mozilla/5.0 QGIS/32207"
  },
  "Total time (ms)": 2751,
  "URL": "https://www.patrimonioculturale-er.it/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=bt_v_complessi_pt&SRSNAME=urn:ogc:def:crs:EPSG::4326"
}

and this is the same for QGIS 3.34.04 in Debian (the request takes 2.5 seconds):

{
  "Bytes Received": 19874406,
  "Bytes Total": 19874406,
  "Cache (controllo)": "Carica sempre dalla rete, ignora la cache",
  "Cache (salva)": "Il risultato non può essere memorizzato in cache",
  "Errori SSL": {
    "Errore": "Nessun certificato può essere verificato"
  },
  "ID": "workrequest.cpp:214 (sendGET)",
  "In risposta": {
    "Cache (risultato)": "Leggi dalla rete",
    "Stato": "200",
    "Titoli": {
      "Connection": "Keep-Alive",
      "Content-Encoding": "gzip",
      "Content-Type": "text/xml; subtype=gml/3.1.1; charset=UTF-8",
      "Date": "Tue, 24 Dec 2024 10:19:11 GMT",
      "Keep-Alive": "timeout=5, max=100",
      "Server": "Apache/2.2.22 (Debian)",
      "Strict-Transport-Security": "max-age=15768000",
      "Transfer-Encoding": "chunked",
      "Vary": "Accept-Encoding"
    }
  },
  "Iniziatore": "QgsBaseNetworkRequest",
  "Interrogazione": {
    "BBOX": "37.36898687368669414,4.76751266043808375,51.80589274569861402,17.14200340787687793,urn:ogc:def:crs:EPSG::4326",
    "REQUEST": "GetFeature",
    "SERVICE": "WFS",
    "SRSNAME": "urn:ogc:def:crs:EPSG::4326",
    "TYPENAME": "bt_v_complessi_pt",
    "VERSION": "1.1.0"
  },
  "Operazione": "GET",
  "Replies": 5,
  "Thread": "0x00007f78b4049ff0",
  "Titoli": {
    "User-Agent": "Mozilla/5.0 QGIS/33404/Debian GNU/Linux 12 (bookworm)"
  },
  "Total time (ms)": 2522,
  "URL": "https://www.patrimonioculturale-er.it/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=bt_v_complessi_pt&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=37.36898687368669414,4.76751266043808375,51.80589274569861402,17.14200340787687793,urn:ogc:def:crs:EPSG::4326"
}

I'm the owner of this WFS service, so I can make some tests on the server (Mapserver + Postgis layer).

from the wget command I receive:
Risoluzione di www.patrimonioculturale-er.it... 46.255.85.138
Connessione a [www.patrimonioculturale-er.it](http://www.patrimonioculturale-er.it/)|46.255.85.138|:443... connesso.
AVVERTIMENTO: impossibile verificare il certificato di [www.patrimonioculturale-er.it](http://www.patrimonioculturale-er.it/), rilasciato da "/C=AT/O=ZeroSSL/CN=ZeroSSL RSA Domain Secure Site CA":
  Impossibile verificare localmente l'autorità dell'emittente.
HTTP richiesta inviata, in attesa di risposta... 200 OK
Salvataggio in"wfs@SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=bt_v_complessi_pt&SRSNAME=urn%3Aogc%3Adef%3Acrs%3AEPSG%3A%3A4326"  18,95M  9,64MB/s  in 2,0s

could be an SSL problem?

I also tried adding the [https://www.patrimonioculturale-er.it:443](https://www.patrimonioculturale-er.it/) in the Server certificates trusted (in Certificates management window), but nothing changed. 

thanks,
francesco

### Steps to reproduce the issue

add a WFS connection to https://www.patrimonioculturale-er.it/wfs
connect
load the bt_v_complessi_pt layer

### Versions

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0//EN" "http://www.w3.org/TR/REC-html40/strict.dtd">
<html><head><meta http-equiv="Content-Type" content="text/html; charset=utf-8" /><style type="text/css">
p, li { white-space: pre-wrap; }
</style></head><body>

Versione di QGIS | 3.34.14-Prizren | Revisione codice QGIS | 0cdaf6d9
-- | -- | -- | --
Versione Qt | 5.15.13
Versione Python | 3.12.8
Versione GDAL/OGR | 3.9.3
Versione PROJ | 9.5.0
Versione database del Registro EPSG | v11.016 (2024-08-31)
Versione GEOS | 3.13.0-CAPI-1.19.0
Versione SQLite | 3.46.1
Versione PDAL | 2.8.1
Versione client PostgreSQL | 16.2
Versione SpatiaLite | 5.1.0
Versione QWT | 6.3.0
Versione QScintilla2 | 2.14.1
Versione SO | Windows 10 Version 2009
  |   |   |  
Plugins Python attivi
archeo_db | 2.9.3
coordinate_capture | 0.2
DissolveWithStats | 0.6
geometric_attributes | 0.4
go2streetview | 8.8
OSMDownloader | 1.0.3
plugin_reloader | 0.10
qfieldsync | v4.12.0
quick_map_services | 0.19.34
road_slope_calculator | 0.5
db_manager | 0.1.20
grassprovider | 2.12.99
processing | 2.12.99

</body></html>Versione di QGIS
3.34.14-Prizren
Revisione codice QGIS
[0cdaf6d9](https://github.com/qgis/QGIS/commit/0cdaf6d9)
Versione Qt
5.15.13
Versione Python
3.12.8
Versione GDAL/OGR
3.9.3
Versione PROJ
9.5.0
Versione database del Registro EPSG
v11.016 (2024-08-31)
Versione GEOS
3.13.0-CAPI-1.19.0
Versione SQLite
3.46.1
Versione PDAL
2.8.1
Versione client PostgreSQL
16.2
Versione SpatiaLite
5.1.0
Versione QWT
6.3.0
Versione QScintilla2
2.14.1
Versione SO
Windows 10 Version 2009

Plugins Python attivi
archeo_db
2.9.3
coordinate_capture
0.2
DissolveWithStats
0.6
geometric_attributes
0.4
go2streetview
8.8
OSMDownloader
1.0.3
plugin_reloader
0.10
qfieldsync
v4.12.0
quick_map_services
0.19.34
road_slope_calculator
0.5
db_manager
0.1.20
grassprovider
2.12.99
processing
2.12.99

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by rouault** [comment]
There's definitely an issue with the server:
```
$ curl -v "https://www.patrimonioculturale-er.it/wfs?SERVICE=WFS&REQUEST=GetCapabilities"
*   Trying 46.255.85.138:443...
* TCP_NODELAY set
* Connected to www.patrimonioculturale-er.it (46.255.85.138) port 443 (#0)
* ALPN, offering h2
* ALPN, offering http/1.1
* successfully set certificate verify locations:
*   CAfile: /etc/ssl/certs/ca-certificates.crt
  CApath: /etc/ssl/certs
* TLSv1.3 (OUT), TLS handshake, Client hello (1):
* TLSv1.3 (IN), TLS handshake, Server hello (2):
* TLSv1.2 (IN), TLS handshake, Certificate (11):
* TLSv1.2 (OUT), TLS alert, unknown CA (560):
* SSL certificate problem: unable to get local issuer certificate
* Closing connection 0
curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: https://curl.haxx.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
```

**Comment by francescomarucci** [comment]
thanks for the answer: this means that since the 3.34.x the SSL connection to a service is more accurate? in this case, why in debian or in a pre 3.34.x version the connection to that sevice is fast? and why it takes so long to load the data? if that were the case I would expect it not to load the data, and why others requests (GetCapabilities and DescribeFeature) from QGIS works perfectly? in the same host I have also a WMS service and it is working perfectly...

**Comment by agiudiceandrea** [comment]
Running QGIS 3.34.14 on Windows 10 from Italy I don't see any particular slowness:

https://github.com/user-attachments/assets/e3b70c54-2432-46f3-a31f-1544fb9203fa

The request takes about 5 seconds to complete, which is about the same even using QGIS 3.28.15 on the same system.

```json
{
  "Bytes Received": 19874406,
  "Bytes Total": 19874406,
  "Cache (control)": "Always load from network, do not check cache",
  "Cache (save)": "Result cannot be stored in cache",
  "Headers": {
    "User-Agent": "Mozilla/5.0 QGIS/33414/Windows 10 Version 1903"
  },
  "ID": "src\\providers\\wfs\\qgsbasenetworkrequest.cpp:214 (QgsBaseNetworkRequest::sendGET)",
  "Initiator": "QgsBaseNetworkRequest",
  "Operation": "GET",
  "Query": {
    "BBOX": "39.87373576839853229,4.76751266043808375,49.30114385098677587,17.14200340787687793,urn:ogc:def:crs:EPSG::4326",
    "REQUEST": "GetFeature",
    "SERVICE": "WFS",
    "SRSNAME": "urn:ogc:def:crs:EPSG::4326",
    "TYPENAME": "bt_v_complessi_pt",
    "VERSION": "1.1.0"
  },
  "Replies": 3,
  "Reply": {
    "Cache (result)": "Read from network",
    "Headers": {
      "Connection": "Keep-Alive",
      "Content-Encoding": "gzip",
      "Content-Type": "text/xml; subtype=gml/3.1.1; charset=UTF-8",
      "Date": "Tue, 24 Dec 2024 20:37:41 GMT",
      "Keep-Alive": "timeout=5, max=100",
      "Server": "Apache/2.2.22 (Debian)",
      "Strict-Transport-Security": "max-age=15768000",
      "Transfer-Encoding": "chunked",
      "Vary": "Accept-Encoding"
    },
    "Status": "200"
  },
  "Thread": "0x0000027480e2eb60",
  "Total time (ms)": 5441,
  "URL": "https://www.patrimonioculturale-er.it/wfs?SERVICE=WFS&REQUEST=GetFeature&VERSION=1.1.0&TYPENAME=bt_v_complessi_pt&SRSNAME=urn:ogc:def:crs:EPSG::4326&BBOX=39.87373576839853229,4.76751266043808375,49.30114385098677587,17.14200340787687793,urn:ogc:def:crs:EPSG::4326"
}
```

**Comment by francescomarucci** [comment]
sorry @agiudiceandrea, I did not tried with a clean user profile, thanks to your suggestion I created a brand new user profile and definitely it works very well! I mean, the service is loaded normallly in fews seconds.
the question now is: what is then the problem of the default user profile? there is a way to "clean" it, without loosing all the configurations the users have in the default profile? (I need now write a deep manual for the users of that WFS service...)
thanks a lot!

**Comment by agiudiceandrea** [comment]
@francescomarucci, the issue may be due to a particular setting set in the user profile or due to a particular plugin installed in the user profile. You can tray to check if the issue is due to a plugin e.g.:
- starting QGIS with the old user profile and the `--noplugins` option
- uninstalling the plugins one by one from the old user profile or installing the plugins one by one in the new user profile.

**Comment by francescomarucci** [comment]
I'm sorry if I reopen the issue... but I found the problem: if the option "logDatabaseQueries=true" then the loading of features of a WFS service is very slow: I don't know why, but in some case this option is the default in the user profile...

the solution is to turn off database logging in the debugging panel:

![immagine](https://github.com/user-attachments/assets/839d93bf-baaa-486c-8dcd-6e939fed78a1)


hoping this can help someone...
