### ISSUE TITLE
WFS GetCapabilities request URL incompatible with some providers

### ISSUE THREAD

**Issue by kommen** [qgis/QGIS#60013]
### What is the bug or the crash?

I'm trying to add https://apps.bev.gv.at/bev.webservice/inspire as a WFS provider to QGIS.

This fails with this error:

> Download of capabilities failed: Error transferring https://apps.bev.gv.at/ bev.webservice/inspire?
SERVICE=WFS&REQUEST=GetCapabilities&ACCEPTVERSIONS=2.0.0,1.1.0, 1.0.0
> - server replied: Internal Server Error

<img width="648" alt="Screenshot 2024-12-25 at 11 17 31" src="https://github.com/user-attachments/assets/226dfc0f-72dc-456c-b0a8-6ca5c9ad6abf" />

It seems the server chokes on the url param name `REQUEST` being up-cased. 

Using curl, this works:

```
$ curl -I https://apps.bev.gv.at/bev.webservice/inspire\?service\=WFS\&request\=GetCapabilities\&VERSION\=2.0.0
HTTP/1.1 200 OK
Server: Oracle-Application-Server-10g OracleAS-Web-Cache-10g/9.0.4.1.0
Content-Length: 7626
Cache-Control: private
Content-Type: text/xml;charset=UTF-8
Date: Wed, 25 Dec 2024 10:20:03 GMT
Strict-Transport-Security: max-age=157680000; includeSubDomains
```

This causes an error:

```
curl -I https://apps.bev.gv.at/bev.webservice/inspire\?service\=WFS\&REQUEST\=GetCapabilities\&VERSION\=2.0.0
HTTP/1.1 500 Internal Server Error
Server: Oracle-Application-Server-10g OracleAS-Web-Cache-10g/9.0.4.1.0
Content-Length: 1709
Cache-Control: private
Content-Type: text/html
Date: Wed, 25 Dec 2024 10:19:56 GMT
Strict-Transport-Security: max-age=157680000; includeSubDomains
```

Unfortunately it seems there is no way to configure the URL with QGIS, as the `REQUEST` seems hardcoded here: 

https://github.com/qgis/QGIS/blob/af5edcb665ccd78fc7dc48b78d68e9cda565107e/src/providers/wfs/qgswfscapabilities.cpp#L44-L48

### Steps to reproduce the issue

- Chose Layer > Add Layer > Add WFS Layer
- Click the "New..." button under Server Connections
- Chose a name and use `https://apps.bev.gv.at/bev.webservice/inspire` as the URL
- click OK
- click Connect

### Versions

<table width='100%' align='center'><tr><td>QGIS version</td><td>3.40.1-Bratislava</td></tr><tr><td>QGIS code branch</td><td><a href="https://github.com/qgis/QGIS/tree/release-3_40">Release 3.40</a></td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Libraries</b></td></tr><tr><td>Qt version</td><td>5.15.15</td></tr><tr><td>Python version</td><td>3.11.10</td></tr><tr><td>GDAL/OGR version</td><td>3.9.2</td></tr><tr><td>PROJ version</td><td>9.5.0</td></tr><tr><td>EPSG Registry database version</td><td>v11.016 (2024-08-31)</td></tr><tr><td>GEOS version</td><td>3.13.0-CAPI-1.19.0</td></tr><tr><td>SQLite version</td><td>3.47.0</td></tr><tr><td>PDAL version</td><td>2.8.0</td></tr><tr><td>PostgreSQL client version</td><td>unknown</td></tr><tr><td>SpatiaLite version</td><td>5.1.0</td></td></tr><tr><td>QWT version</td><td>6.3.0</td></tr><tr><td>QScintilla2 version</td><td>2.14.1</td></tr><tr><td>OS version</td><td>macOS 14.7</td></tr><tr><td colspan="2">&nbsp;</td></tr><tr><td colspan="2"><b>Active Python plugins</b></td></tr><tr><td>QuickOSM</td><td>2.2.3</td></tr><tr><td>quick_map_services</td><td>0.19.36</td></tr><tr><td>splitmultipart</td><td>1.0.0</td></tr><tr><td>GeoCoding</td><td>2.19</td></tr><tr><td>qgis2web</td><td>3.24.0</td></tr><tr><td>qfieldsync</td><td>v4.12.1</td></tr><tr><td>mmqgis</td><td>2024.11.8</td></tr><tr><td>StreetView</td><td>3.2</td></tr><tr><td>processing</td><td>2.12.99</td></tr><tr><td>grassprovider</td><td>2.12.99</td></tr><tr><td>db_manager</td><td>0.1.20</td></tr><tr><td>MetaSearch</td><td>0.3.6</td></tr></table>

### Supported QGIS version

- [X] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by uclaros** [comment]
The bug is on the server's side. The standard explicitly states that parameter names shall not be case sensitive. 
You could try contacting the service provider.

**Comment by agiudiceandrea** [comment]
See https://docs.ogc.org/is/04-094r1/04-094r1.html#102, https://docs.ogc.org/is/04-094r1/04-094r1.html#22, https://docs.ogc.org/is/04-094r1/04-094r1.html#130.

**Comment by kommen** [comment]
Thank you @agiudiceandrea and @uclaros, I have written to the service to provider.
